### ISSUE TITLE
Unable to save to desktop on Windows

### ISSUE THREAD

**Issue by RMRubert** [rstudio/rstudio#10001]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  Windows 10 x64
    R Version       :  R 4.1.1 from CRAN

### Steps to reproduce the problem
in console write: plot(cars)
Now select save as image in the export option on the plot panel on rstudio.
Select the desktop folder, mind that for whatever reason it tries the following strange relative path "~/../Desktop".
![Captura de pantalla 2021-10-23 214326](https://user-images.githubusercontent.com/11463633/138570937-c27918d6-6306-42da-b5d8-843f049fde6f.png)
Click on export and it will give you the error on the screen.

Note that: 

- Saving in any other place, where you get a full path (like other disk drive) will have no such a problem.
- This problem affects EVERYTHING, saving a .R file -> Same error. Rmd -> same error. pdf too. 
- It is a problem of the path I think
- No other software has any problem at writing on the desktop folder.
- Error also happens if Rstudio is run with admin privileges.

### Describe the problem in detail
Rstudio can't write, save or use anything in the desktop folder. It will be able to read, but it cannot save the file and you need to save as and select another drive to force the full path. I am pretty sure there is an option somewhere to force full paths that will solve this bug, but can't find it.

### Describe the behavior you expected
Being able to save on the DEsktop folder.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@RMRubert Thank you for raising the issue! I can't reproduce it, though—the `Desktop` directory URL is showing up correctly for me in the same version and environment: `~/Desktop`

1. What happens if you switch to another directory, such as `Documents`?
2. After doing so, what happens if you switch back to `Desktop`?

**Comment by RMRubert** [comment]
I haven't been able to reproduce it in any other computer like my work one either.
I think the main problem is with two different conditions that together make the bug.

- If the path contains the ~ symbol
- Not all of my user folder are under C:\Users\Yourusername, as I have used the location tab under properties to change them to a different hard drive. ![imagen](https://user-images.githubusercontent.com/11463633/141013909-4f846d96-faf6-4756-9963-20300ed7b2b6.png)

I think when both conditions happen, you get the error, probably is trying to find the desktop folder as a relative of the document folder or installation folder and they are... not in the same drive.

It is just a theory.
