### ISSUE TITLE
`shinymod` snippet is outdated

### ISSUE THREAD

**Issue by pnacht** [rstudio/rstudio#10009]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : 10.0
    R Version       : 4.1.1

### Steps to reproduce the problem
Write `shinymod` and press <kbd>Tab</kbd> on the keyboard

### Describe the problem in detail
`shinymod` is a snippet which gives a skeleton for Shiny modules. It's currently defined as:

```
snippet shinymod
	${1:name}_UI <- function(id) {
	  ns <- NS(id)
	  tagList(
		${0}
	  )
	}
	
	${1:name} <- function(input, output, session) {
	  
	}
```

However, this is an outdated method which eventually relies on `callModule(...)` in the app's server.

### Describe the behavior you expected

A snippet that follows the more modern `moduleServer` approach would be:
```
snippet shinymod
	${1:name}UI <- function(id) {
	  ns <- NS(id)
	  tagList(
		${0}
	  )
	}
	
	${1:name}Server <- function(id) {
	  moduleServer(
	    id,
	    function(input, output, session) {
	    
	    }
	  )
	}
```

(I took the liberty of removing the underscore from the UI name and adding `Server` to the server name, keeping the style displayed in the `moduleServer` man page and Shiny's overall camelCase style)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gsmolinski** [comment]
Can be closed now, updated snippet looks OK in the Prairie Trillium version.

**Comment by ronblum** [comment]
@gsmolinski and @pnacht Thank you for letting us know!
