### ISSUE TITLE
render commit.template in commit message window

### ISSUE THREAD

**Issue by andybeet** [rstudio/rstudio#10008]
After adding a commit.template file to gits config

```
git config --global commit.template ~/gitmessage.txt
```

I was hoping to see the template appear in the commit message text field under the git tab in Rstudio.

**Comment by colearendt** [comment]
Oooh that would be nice! TIL about commit.template 🤩

**Comment by statnmap** [comment]
I also would like to see this feature coming in. Thanks.

**Comment by dm807cam** [comment]
We would also like to see this feature introduced. Are there any updates on this?
