### ISSUE TITLE
Visual editor incorrectly rewrites escaping of hashes

### ISSUE THREAD

**Issue by ulyngs** [rstudio/rstudio#10012]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2021.09.0 Build 351
    OS Version      :  macOS Big Sur, v11.6
    R Version       : 4.0.5

### Steps to reproduce the problem

Write this in an R Markdown document:

```
-   \# First-level heading

-   \#\# Second-level heading

-   \#\#\# Etc.
```

Open the visual editor and switch back to the normal editor.
The escaping of hashes has been rewritten to

```
-   \# First-level heading

-   ## Second-level heading

-   ##\# Etc.
```

### Describe the problem in detail
Sometimes you need to show literal e.g. hashes, often for pedagogical purposes. E.g. the above example is meant to teach the reader how increasing number of hashes creates sections, with this rendered output in PDF:

<img width="505" alt="Screenshot 2021-10-27 at 08 16 02" src="https://user-images.githubusercontent.com/23137032/139018023-2889d832-bfbf-494e-989e-e627088882e7.png">

The visual editor sometimes rewrites escaping incorrectly, as in this example. With the rewritten version, the PDF output is

<img width="504" alt="Screenshot 2021-10-27 at 08 16 49" src="https://user-images.githubusercontent.com/23137032/139018138-e2cb97f9-a46e-423b-a2cb-8c0fe410f074.png">

Indeed, there doesn't actually seem to be any way to insert a literal \# from the visual editor?

### Describe the behavior you expected
I expect it to leave the escaping untouched in this case, i.e. this is preserved

```
-   \# First-level heading

-   \#\# Second-level heading

-   \#\#\# Etc.
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Reported as bug upstream here: https://github.com/jgm/pandoc/issues/7726

**Comment by jjallaire** [comment]
Fixed in Pandoc so this should be resolved on our end once a new Pandoc release is available: https://github.com/jgm/pandoc/commit/51f6f0e3a1533a0e1bb94538f55bdc9db380a028

**Comment by llrs** [comment]
Just wanted to add up that I also have these modifications reported by @agnesevardanega (even when initially I delete them then later on Rstudio adds it back). In addition, there was a [new release of pandoc](https://github.com/jgm/pandoc/releases) recently. Hope this can be handled on Rstudio soon. Thanks!

**Comment by romainfrancois** [comment]
Verified in RStudio 2022.06.0-daily+373. After a round trip, I see this, which is correct: 

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2625526/167376235-6fada6a0-4113-4876-9e6b-cc4c2a4a584b.png">
