### ISSUE TITLE
32-bit RStudio crashes viewing any help file

### ISSUE THREAD

**Issue by ldecicco-USGS** [rstudio/rstudio#10023]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717 and 2021.12.0 
    OS Version      : Windows 10 x64
    R Version       : R version 4.1.1 (2021-08-10)

### Steps to reproduce the problem

In Tools -> Global, change from the 64 bit version of R to 32 bit.
Restart RStudio
Try viewing literally any help function:
```r
?lm
```
RStudio crashes

### Describe the problem in detail

There seem to be other 32 bit crashes that I can't isolate, but the help file one is most easily demonstrated.

### Describe the behavior you expected

I'd expect to be able to view a help file.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7436888/diagnostics-report.txt)

I tried, I'm not sure I did it in the right order?

- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7436889/diagnostics-report.txt)

**Comment by mikebessuille** [comment]
are you able to run 32-bit R from the command line?

**Comment by ldecicco-USGS** [comment]
I'll try later today (I assume the only way to do that is to change the PATH to R?). 

One of my co-workers sent me this a few weeks ago (which is what kicked off my exploration of 32-bit problems):
"We know it's not an issue with RStudio because we can run the scripts in the RGui, so it must be an issue with R Studio. Has anyone else experienced this? If so, has anyone figured out a workaround or fix? The workaround that we found is to run the scripts in RGui and to look for package help online, but this is a cumbersome workaround. Thanks for any suggestions. "

A separate co-worker sent this independently:
"I am having problems with RStudio crashing on really benign commands. Like, as benign as opening a new session, typing "?log" and RStudio crashes. RStudio also crashes if I navigate to the "Help" tab on the GUI. It also crashes periodically on more involved tasks, like plotting (ggplot2, I haven't identified the pattern crashing here) or running WQReview 2.2 through the RStudio console (but WQReview 2.2 works if run as an application, without RStudio). I'm running the most recent IT-installed updates, R4.1.0 and RStudio 1.4.1717. Any suggestions for trouble-shooting/fixing? Thanks in advance!"

The "WQReview" application is a shiny app.

I think the reason so many of my co-workers are running into this issue is that we have an Oracle database that (for whatever reason....) is in a native 32-bit format. As far as I know, the only way we can make a connection to that database is to use 32-bit R.
