### ISSUE TITLE
https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb returns 404

### ISSUE THREAD

**Issue by N0rbert** [rstudio/rstudio#10026]
It seems that you do not want to create APT repository for Debian-based distributions, so https://github.com/rstudio/rstudio/issues/4186  is still not fixed.

Currently the fallback URL from the issue title returns 404:

```
$ wget -c https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
--2021-10-29 21:16:44--  https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
Resolving rstudio.org (rstudio.org)... 45.33.2.142
Connecting to rstudio.org (rstudio.org)|45.33.2.142|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-29 21:16:45 ERROR 404: Not Found.

$ wget -c --spider https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
Spider mode enabled. Check if remote file exists.
--2021-10-29 21:17:20--  https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
Resolving rstudio.org (rstudio.org)... 45.33.2.142
Connecting to rstudio.org (rstudio.org)|45.33.2.142|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
Remote file does not exist -- broken link!!!
```

Such moments do not make RStudio and Debian/Ubuntu users happy. Please do one of the following:

* create official APT/deb repository for RStudio products;
* provide direct links to download RStudio in clear and do not change them, they should point to correct release and should return deb-package with 200 HTTP code.

Thanks.

**Comment by N0rbert** [comment]
What a surprise, the RStudio Server link also returns 404:

```
$ wget --spider https://rstudio.org/download/latest/stable/server/bionic/rstudio-server-latest-amd64.deb
Spider mode enabled. Check if remote file exists.
--2021-10-29 21:19:12--  https://rstudio.org/download/latest/stable/server/bionic/rstudio-server-latest-amd64.deb
Resolving rstudio.org (rstudio.org)... 45.33.2.142
Connecting to rstudio.org (rstudio.org)|45.33.2.142|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
Remote file does not exist -- broken link!!!
```

**Comment by jmcphers** [comment]
Internal note: also tracked in https://github.com/rstudio/rstudio-pro/issues/3067

**Comment by N0rbert** [comment]
2022-01.0 is to late. Please fix the 404 issue sooner.

**Comment by ronblum** [comment]
@N0rbert Marking this for the Prairie Trillium in this case means that we are actively working on this in the current release cycle rather than waiting for a later cycle.

[Tagging #9743 as well.]

**Comment by N0rbert** [comment]
Still 404.

**Comment by N0rbert** [comment]
Still 404. How long? Is it too difficult to change some symlink on some web server? Should we really wait for January? Or maybe for 2023 year?

**Comment by jeffvroom** [comment]
Apologies for the delays. This should be fixed now. Let me know if you see a problem... for reference, here's the list of stable URLs for the desktop, server, and workbench versions:

https://rstudio.org/download/latest/stable/desktop/windows/RStudio-latest.exe 
https://rstudio.org/download/latest/stable/desktop/mac/RStudio-latest.dmg
https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
https://rstudio.org/download/latest/stable/desktop/redhat64/rstudio-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/desktop/debian9/rstudio-latest-amd64.deb
https://rstudio.org/download/latest/stable/desktop/opensuse15/rstudio-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/desktop/centos8/rstudio-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/bionic/rstudio-server-latest-amd64.deb
https://rstudio.org/download/latest/stable/server/debian9_64/rstudio-server-latest-amd64.deb
https://rstudio.org/download/latest/stable/server/redhat7_64/rstudio-server-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/suse12_64/rstudio-server-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/opensuse15/rstudio-server-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/centos8/rstudio-server-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/bionic/rstudio-workbench-latest-amd64.deb
https://rstudio.org/download/latest/stable/server/debian9_64/rstudio-workbench-latest-amd64.deb
https://rstudio.org/download/latest/stable/server/redhat7_64/rstudio-workbench-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/suse12_64/rstudio-workbench-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/opensuse15/rstudio-workbench-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/server/centos8/rstudio-workbench-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/stable/session/bionic/rsp-session-bionic-latest.tar.gz
https://rstudio.org/download/latest/stable/session/debian9_64/rsp-session-debian9-latest.tar.gz
https://rstudio.org/download/latest/stable/session/redhat7_64/rsp-session-centos7-latest.tar.gz
https://rstudio.org/download/latest/stable/session/centos8/rsp-session-centos8-latest.tar.gz
https://rstudio.org/download/latest/stable/session/suse12_64/rsp-session-opensuse-latest.tar.gz
https://rstudio.org/download/latest/stable/session/opensuse15/rsp-session-opensuse15-latest.tar.gz

**Comment by N0rbert** [comment]
https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb is now alive, thanks.
