### ISSUE TITLE
Error: Temporary server error, please try again (login impossible)

### ISSUE THREAD

**Issue by M-Stenzel** [rstudio/rstudio#10022]
Hallo,

I am running rstudio-server on an opensuse system 

and cannot login, this is what I receive:

[rserver] ERROR Failed to validate sign-in with invalid CSRF form; LOGGED FROM: bool rstudio::server::auth::common::validateSignIn(const rstudio::core::http::Request&, rstudio::core::http::Response*) src/cpp/server/auth/ServerAuthCommon.cpp:132

My rserver.conf reads:
# Server Configuration File
www-address=127.0.0.1
www-root-path=/rstudio/
www-enable-origin-check=0

I installed the latest rpm (2021.09.0+351)

I run rstudio behind an apache proxy, snippet:
RedirectMatch permanent ^/rstudio$ /rstudio/

RewriteEngine on
RewriteCond %{HTTP:Upgrade} =websocket
RewriteRule /rstudio/(.*)     ws://localhost:8787/$1  [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket
RewriteRule /rstudio/(.*)     http://localhost:8787/$1 [P,L]
ProxyPass /rstudio/ http://localhost:8787/
ProxyPassReverse /rstudio/ http://localhost:8787/
ProxyRequests off
<Location /rstudio>
                Require all granted
                Satisfy any
</Location>

Apache does not yield any error. Using nginx instead of apache does not change things.

I am lost, any suggestions?

Martin.

**Comment by M-Stenzel** [comment]
> The login page uses a cookie called rs-csrf-token, and that error means the server is not seeing that cookie. I think to fix this you can either set www-root-path=/rstudio in rserver.conf (which assumes the rserver is not being accessed without the proxy) or add a directive to apache to set the header: X-RStudio-Root-Path to the value /rstudio. There's also a directive that will rewrite cookie paths but I think those other options are a better way to solve the problem.

Thank you for the information.
I put both a header statement and this line in rserver.conf, however, this did not change matters.

**Comment by M-Stenzel** [comment]
> @M-Stenzel Thank you for raising this! Could this be a duplicate of the issue described here? #9768

Thank you for your support. Maybe it is the same problem, but how to verify?
Martin.

**Comment by M-Stenzel** [comment]
Problem is solved, it was caused by information given here (as of 2021-10-31):

https://www.traccar.org/secure-connection/

**Comment by ronblum** [comment]
@M-Stenzel Thank you for letting us know!
