### ISSUE TITLE
Update RStudio version in conda 

### ISSUE THREAD

**Issue by Benfeitas** [rstudio/rstudio#10039]
Dear all,

I'm wondering if it would be possible for you to update the rstudio version in anaconda cloud. The [latest version is v1.1.456](https://anaconda.org/r/rstudio), though [there is another one pushed 3 years ago](https://anaconda.org/rdonnelly/rstudio) that is v1.2.502. Recent r-base and package versions have lots of issues with these older rstudio versions.

Would be great if you could update it! Many thanks in advance

**Comment by ronblum** [comment]
@Benfeitas This is a good suggestion! However, we don't maintain conda and have no control over it. You would have to make this request from Anaconda.

[CC @jmcphers in case anything has changed.]

**Comment by Benfeitas** [comment]
Many thanks @ronblum , will do that

**Comment by ronblum** [comment]
@Benfeitas You're welcome! And if you have any updates, it would be great if you'd let us know—both for us and any users who might be interested.
