### ISSUE TITLE
Decoupled and dedicated RMarkdown editor for content creation and collaboration?

### ISSUE THREAD

**Issue by trinhdhk** [rstudio/rstudio#10036]
## Motivation

Occasionally in my workflow do I have to collaborate with other paper authors, who's focus is content writing and obviously not R coding. RStudio, like all Qt programs, suffers from its being too powerful, to a level of overwhelming (and sometimes laggy and stuffy). Hence, to collaborate with non -developers, I have not choice but to compile the file into Word to make use of its collaborative features and familiar UI, which is disruptive to my workflow. 

## Potential solution

Together with adding more collaborative tools (like critic markup, as in #8794), it would be greatly helpful to have a light-weighted, dedicated version of RMarkdown editor, decoupled from the big, fat IDE, (like Jupyter Notebooks to Jupyter Lab), potentially run on the Web or wrapped within Electron, so that it can becomes more friendly to non-technical users. RMarkdown is great, and even greater with the Visual markdown editor. That's why I think it can be improved and developed independently. Now that we also have Quartz for Python, the need for decoupling would encourage the markdown use in that world, rather than depend on Jupyter.

### What might be:

- Rnb real-time preview
- Visual editor
- Critic markups support
- Linting
- Documentation (may be simplified)
- Git **(not really but may be nice to have)**

### What might not be:

- Projects
- Variable explorer
- Data explorer
- Connection
- Devtools
- Script writer
- Addins
- Dedicated htmlWidget and plot viewer (inline only)

**Comment by jmcphers** [comment]
@trinhdhk Thank you for this suggestion! It's a great idea, but really a request for a different product rather than something we could implement in the IDE, so I'm closing it as an RStudio issue.
