### ISSUE TITLE
Open File in New Column Fails on Desktop

### ISSUE THREAD

**Issue by valerie-rstudio** [rstudio/rstudio#10033]
### System details

    RStudio Edition : Desktop & Desktop Pro
    RStudio Version : 2021.09.1+369 & 2021.09.1+369.pro1
    OS Version      : mac OS 11.5.2
    R Version       : 3.6.3

### Steps to reproduce the problem
1. Click on "File > Open File in New Column..."
2. **Expected**: A file menu appears, allowing user to select file to open in new column.
3. **Actual**: Nothing appears to occur. If steps are repeated enough times, the error message "You cannot add more than 3 columns" appears, even though there are less than three columns showing in the IDE.
![Screen Shot 2021-11-01 at 12 57 17 PM](https://user-images.githubusercontent.com/75644399/139721014-cd2d284b-71d2-4281-890d-605d629ec7b5.png)

If this issue is repro'd through the Command Palette, an error does initially occur:
1. In a newly opened instance of RStudio, open the Command Palette
2. In the Command Palette, select "Open File in New Column..."
3. Expected: A file menu appears, allowing user to select file to open in new column.
4. Actual: And error occurs saying `Command Execution Fails` with an exception `Exception caught: Exception caught: Enum constant undefined: Presentations`. If the steps are repeated enough times, the error then switches to "You cannot add more than 3 columns", even though there are less than three columns showing in the IDE.
![Screen Shot 2021-11-01 at 1 02 38 PM](https://user-images.githubusercontent.com/75644399/139721134-44c56084-3600-46fa-bac6-297070f8f83c.png)

**Comment by melissa-barca** [comment]
Hm, just downloaded 2021.09.1+369 and I'm not able to reproduce this in macOS 11.6

**Comment by melissa-barca** [comment]
The "Presentation**s**" tab exists in PT but not GO - I believe this behavior is being caused by attempting to use a preference schema created by PT with GO. @valerie-rstudio if you remove ~/.config/rstudio/rstudio-prefs.json, do you still have this issue?

**Comment by valerie-rstudio** [comment]
### Verified Not A Bug

### Summary
Verified that removing `~/.config/rstudio/rstudio-prefs.json` stopped this issue from occurring.

**Comment by kevinushey** [comment]
To double check, would users who upgrade to PT but later downgrade to GO (or an older release) for some reason run into these issues?

**Comment by melissa-barca** [comment]
> To double check, would users who upgrade to PT but later downgrade to GO (or an older release) for some reason run into these issues?

Yes, I think so. I believe the issue is that Presentations was added to the default pane configuration so if that was created in PT, it will stick around in GO:
https://github.com/rstudio/rstudio/blob/f376917a73293f6ae82c8c1cf93f005c175a21b1/src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java#L70
