### ISSUE TITLE
debugger does not load package when command copied

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#10046]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.01.0 Build 183
    OS Version      : macOS Big Sur 11.6
    R Version       : 3.6.3

### Steps to reproduce the problem

Opened the rsconnect project and added a breakpoint to the very start of rsconnect::deploySite (in R/deploySite.R).

Copy this function into the console and run it.

```
rsconnect::deploySite(siteDir = ".")
```

The function will err without hitting the breakpoint. The error is OK, but we should have hit the breakpoint.

### Describe the problem in detail

The debugger breakpoints are not loaded when the command is copied into the console before it is run. The breakpoints are added if the target command is typed-in (perhaps as a consequence of auto-complete?).

### Describe the behavior you expected

The debugger breakpoints should be loaded when the command is copied into the console, either from the system clipboard or from the History pane.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@ronblum is this a regression?

**Comment by ronblum** [comment]
It's not—it looks like the problem was introduced in 1.3.1093, and worked in 1.2.5042 (using RStudio Desktop on MacOS 12).

**Comment by aronatkins** [comment]
Testing note: You may need to restart your R session in order for the breakpoint to appear as inactive (because the target package is not yet loaded).

Workaround: Either `library(packagename)` or type `packagename::` in the R console -- which triggers autocompletion and is enough to load the package.
