### ISSUE TITLE
Python Plotly not working on R notebooks

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/rstudio#10044]
The following python code fails in R notebooks

````python
```{python}
from datar.all import  * 
from pipda import options,register_verb
from datar.datasets import mtcars
import cufflinks as cf
options.assume_all_piping = True
iplot = register_verb(lambda df, *args, **kwargs: df.iplot(*args, **kwargs))
```

```{python}
mtcars.reset_index() >> filter(f.mpg >21) >> group_by(f.cyl) >> summarize(n = n()) >> iplot(kind= 'bar', x = 'cyl', y = 'n')
```

````

<img width="889" alt="Python_plotly_in_R_notebooks" src="https://user-images.githubusercontent.com/61335136/140187097-2f5d878f-c63a-4b9e-926a-09af8bbc5477.PNG">

However the same code works without issues in VSCode Jupyter notebooks 

<img width="1273" alt="Python_plotly_in_VSCode_Jupyter_notebooks" src="https://user-images.githubusercontent.com/61335136/140180635-c12ada9e-dc16-44b2-b8e4-96f8547f8f6b.PNG">

**Comment by kevinushey** [comment]
https://github.com/santosjorge/cufflinks/issues/151

Seems to be a common issue that affects anyone not running within an ipython shell?
