### ISSUE TITLE
Unrecognized CRS in RStudio console, functions as expected in Terminal

### ISSUE THREAD

**Issue by tylerdrudolph** [rstudio/rstudio#10052]
#### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 351
    OS Version      : Windows 10 x64 (build 19042)
    R Version       : R version 4.1.2 (2021-11-01)

#### Describe the problem in detail
Defining a legitimate Coordinate Reference System (CRS) in the RStudio Console draws an unexpected error that does not occur when run in the Terminal. See https://github.com/rspatial/raster/issues/232 for background on this issue.   

#### Steps to reproduce the problem
From the RStudio Console in a clean new project:
````
> library(raster)
# Loading required package: sp
> x <- raster(xmn=273366.5, xmx=1870587, ymn=359771.8, ymx=1735721, crs="EPSG:3005")
# Error in sp::CRS(SRS_string = x) : NA
>crs(x)
# CRS arguments: NA
````
From the RStudio Terminal:
````
> library(raster)
#Loading required package: sp
> x <- raster(xmn=273366.5, xmx=1870587, ymn=359771.8, ymx=1735721, crs="EPSG:$
> writeRaster(x, driver='GTiff', filename='x.tif', overwrite=T)
# Warning message:
# In .local(x, filename, ...) : all cell values are NA
> crs(x)
# CRS arguments:
 +proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000
+y_0=0 +datum=NAD83 +units=m +no_defs
````
#### Describe the behavior you expected
The following result should occur whether invoked from RStudio or directly from within R:
````
> sp::CRS("EPSG:3005")`
# CRS arguments:
 +proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000
+y_0=0 +datum=NAD83 +units=m +no_defs
````
What the call returns instead is the following error:
````
> sp::CRS("EPSG:3005")
# Error in sp::CRS("EPSG:3005") : NA
````

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I see the same behavior with RGui 4.1.1, and I also see the same behavior in an R process launched as a child from an RStudio session, so I don't think this is specific to RStudio.

```
library(raster)

x <- raster(
  xmn = 273366.5,
  xmx = 1870587,
  ymn = 359771.8,
  ymx = 1735721,
  crs = "EPSG:3005"
)

crs(x)
```

**Comment by tylerdrudolph** [comment]
@kevinushey I am seeing this problem recurring in Rterm as well now. 
Closing this for the time being and re-opening https://github.com/rspatial/raster/issues/232.

**Comment by tylerdrudolph** [comment]
This issue still occurs with the latest versions of R, sp package and RStudio.

**Comment by tylerdrudolph** [comment]
Any idea at RStudio as to what might be causing this? Or suggestions as to what I might try next?

@kevinushey are you still encountering this problem? Does the following fail in both R and Studio Console?

````
sp:CRS("EPSG:3005")
````

**Comment by kevinushey** [comment]
This is what I'm seeing now:

```
> x <- raster(
+   xmn = 273366.5,
+   xmx = 1870587,
+   ymn = 359771.8,
+   ymx = 1735721,
+   crs = "EPSG:3005"
+ )
> crs(x)
Coordinate Reference System:
Deprecated Proj.4 representation: NA 
Warning message:
In wkt(x) : CRS object has no comment
```

However, the issue went away after I installed the `rgdal` R package, e.g. with

```
install.packages("rgdal")
```

So it seems like the behavior here somehow depends on the `rgdal` package being installed, at least for me.
