### ISSUE TITLE
R4.2: support R graphics engine 15

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10058]
https://github.com/wch/r-source/commit/4d38ac04ee88c79b9e9da3fcd1c3e79658dbe0c2

I wrote up https://github.com/rstudio/rstudio-pro/wiki/RStudio-Graphics-Device last time we updated the graphics device to capture what is generally required.

This will need to be done in time for the release of R 4.2.0, which (following the previous release schedules) is expected for April 2022.

**Comment by jmcphers** [comment]
We will also want to backport this change to Ghost Orchid since it's still well within the support window (people shouldn't have to switch to Prairie Trillium to use R 4.2)

**Comment by mikebessuille** [comment]
Jonathan and I agreed that this, and any other R4.2-specific, issue should be back-ported to the GO patch branch, but we will not explicitly issue a new GO patch solely based on R4.2 support.

**Comment by ronblum** [comment]
Ref: See #9251 for previous change from graphics engine upgrade from 13 to 14.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.02.0+377 on MacOS 12.1
- RStudio Desktop 2022.02.0+377 on Windows 10
- RStudio Server 2022.02.0+377 on Red Hat 8.5 via Firefox & Chrome on MacOS 12.1

Tested with the following:
1) ggplot2::ggplot()
2) grid::grid.newpage()
3) demo(graphics, package = "graphics”, ask = TRUE)
4) demo(image, package = "graphics", ask = TRUE)
5) Preview of default R Notebook after running chunk
6) From https://www.r-graph-gallery.com/275-add-text-labels-with-ggplot2.html : 
```
data=head(mtcars, 30)
ggplot(data, aes(x=wt, y=mpg)) +
  geom_point() + # Show dots
  geom_text(
    label=rownames(data), 
    nudge_x = 0.25, nudge_y = 0.25, 
    check_overlap = T
  )	
```

**Comment by jgutman** [comment]
Backported to 2021.09.2 Ghost Orchid patch

**Comment by ronblum** [comment]
I'm reopening and marking this issue as "test" again as a reminder to retest in Ghost Orchid 2021.09.2

**Comment by ronblum** [comment]
Ghost Orchid: Still testing it, but I'm moving this back to "Done" because that's how the rest are handle, indicating that they're already verified in Prairie Trillium.

**Comment by ronblum** [comment]
Note: Verified the backport in Ghost 2021.09.2+382.
