### ISSUE TITLE
Allow content-related panes to appear in additional column

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#10067]
The additional source panes are extremely helpful! It'd also be helpful if some of the content-related panes could also appear in an additional column. In particular, I think that these panes would be good candidates:

- Viewer
- Tutorial
- Help
- Plots

This would enable, for example, opening a shiny app as a full-height preview in a new column next to the standard RStudio layout. Here's an example faking it with the popped out window.

![image](https://user-images.githubusercontent.com/5420529/141131439-524745c3-a0b4-4633-93d7-0b114bd87f34.png)

Or (the use case I'm most interested in) users could open a tutorial in a third column next to the standard layout. They could then work in the IDE while reading through the tutorial. In this case, asking learners to arrange their windows can be a difficult ask if we want to guarantee that they see the content and panes we expect them to see.

![image](https://user-images.githubusercontent.com/5420529/141143409-48b2932b-32ae-44b8-bf17-e28429255c47.png)

**Comment by gadenbuie** [comment]
Btw, we can get pretty close to the intended feel by adding an extra source column, moving all source files to that column, moving the tutorial and viewer panes to the far right column and then overloading the left column. But this sacrifices one pane area from the right column and the layout doesn't feel as natural as having the tutorial on the left side of the IDE.

![image](https://user-images.githubusercontent.com/5420529/141144723-c405c6d0-9636-454c-82d3-ef7a3b636c8b.png)

**Comment by francisbarton** [comment]
Just commenting to link this issue to a similar idea previously posted in https://github.com/rstudio/rstudio/issues/2204#issuecomment-409341412

**Comment by gadenbuie** [comment]
Keep it fresh, stalebot

**Comment by francisbarton** [comment]
Keep on keeping it fresh please!

**Comment by francisbarton** [comment]
Such a shame
