### ISSUE TITLE
rscript.exe --version prints to  stderr instead of stdout on Windows

### ISSUE THREAD

**Issue by sitmo** [rstudio/rstudio#10066]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows 10 enterprrise
    R Version       :  4.1.1

### Steps to reproduce the problem
In a cmd terminal type:
rscript --version 2>> error.txt
and you should see that the version info is written via stderr to the error.txt file.

### Describe the problem in detail
I was trying to read the version from stdout but instead I learned that it is printed to stderr.

### Describe the behavior you expected
I was expecting the version info to be printed to stdout, but instead, it's printed to stderr.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
rscript is part of R rather than RStudio; see these resources for help: https://www.r-project.org/help.html
