### ISSUE TITLE
Display source markers in source code pane

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#10062]
Currently, custom source markers created with `rstudioapi::sourceMarkers()` don't appear in the actual source pane like other code diagnostics.

![image](https://user-images.githubusercontent.com/5420529/140973381-b26b7c18-159c-48ae-a3ba-cfb73c4a0c95.png)

In addition to being helpful for packages like [lintr](https://github.com/jimhester/lintr), it would also be a useful approach for calling attention to particular lines of code from within a [learnr tutorial](https://github.com/rstudio/learnr) or other interactive feedback system. Currently, if the message only appears in the Markers pane the annotations are too disconnected from the source to be effective for learning.

Additionally, #9010 was closed as stale but appears to provide a relatively easy solution to fix the bug that currently prohibits `message`s with class `"html"` from being rendered as HTML.

**Comment by jmcphers** [comment]
Consider: These should probably show up in the visual editor, too, if they're inside a code chunk there.

**Comment by timtmok** [comment]
Initial changes have been merged into spotted wakerobin. I'm going to make another change since source markers allow ANSI codes so the gutter markers also render those.

**Comment by jgutman** [comment]
Note this does not appear to be working fully in 2022.6.0.76

**Comment by timtmok** [comment]
I'll take a look. It seems that the gutter is not displaying the markers.

**Comment by timtmok** [comment]
I can reproduce the issue using the daily but not in dev. It also seems to work with R arm64 but not if I use x86.

**Comment by jgutman** [comment]
On Mac OS 12.2 with R 4.2 x86_64 and RStudio Desktop 2022.6.0.128, the custom markers show up in both the gutter and the Source Marker pane, but the HTML element styling doesn't render.

For example:

`~/test_10062.R`
```
foo <- shiny::HTML('<div style="color:red;">I am red</div>')
bar <- shiny::HTML('<p style="color:red;">I am red</p>')
inherits(foo, "html")
#> [1] TRUE
inherits(bar, "html")
#> [1] TRUE

markers <- list(
  list(
    type = "error",
    file = paste(getwd(), "test_10062.R", sep = "/"),
    line = 11,
    column = 1,
    message = foo),
  list(
    type = "info", 
    file = paste(getwd(), "test_10062.R", sep = "/"),
    line = 19,
    column = 1,
    message = bar))

rstudioapi::sourceMarkers("Test Name", markers)
```

<img width="629" alt="image" src="https://user-images.githubusercontent.com/7817881/154726362-4f4ddc6d-cdcb-4dfd-a70c-083296988c89.png">
<img width="364" alt="image" src="https://user-images.githubusercontent.com/7817881/154726383-9fea09b2-0c63-4c61-8bc4-8f30ba375105.png">
<img width="336" alt="image" src="https://user-images.githubusercontent.com/7817881/154726430-adfb2cf6-5b12-4a2d-b741-d6948050527e.png">

I thought that the text would be rendered in red in the source markers pane and the left gutter. 

@timtmok Thoughts?

**Comment by timtmok** [comment]
@jgutman Supporting HTML styling potentially opens up a vulnerability for JS script injection so the alternative is providing ANSI code support. This provides basic formatting like italics, bold, font colours and underlining. Any HTML will be rendered literally. It wasn't mention in this issue so that was my fault for not conveying the result of my conversation with Kevin.

**Comment by jgutman** [comment]
> @jgutman Supporting HTML styling potentially opens up a vulnerability for JS script injection so the alternative is providing ANSI code support. This provides basic formatting like italics, bold, font colours and underlining. Any HTML will be rendered literally. It wasn't mention in this issue so that was my fault for not conveying the result of my conversation with Kevin.

Ah okay, makes sense. Is there a way to do the red color styling with ANSI for this example?

**Comment by jgutman** [comment]
Confirmed this renders properly with
```
foo <- cli::bg_br_white(cli::col_red("I am red!"))
bar <- cli::bg_br_yellow(cli::col_cyan("I am cyan!"))

markers <- list(
  list(
    type = "error",
    file = paste(getwd(), "test_10062.R", sep = "/"),
    line = 11,
    column = 1,
    message = foo),
  list(
    type = "info", 
    file = paste(getwd(), "test_10062.R", sep = "/"),
    line = 19,
    column = 1,
    message = bar))

rstudioapi::sourceMarkers("Test Name", markers)
```

![Screen Shot 2022-02-18 at 12 29 25 PM](https://user-images.githubusercontent.com/7817881/154732786-8be06591-21d3-4d6e-9079-2ac0f2c15e9e.png)
