### ISSUE TITLE
`Import Text Data` preview table grid inconsistent

### ISSUE THREAD

**Issue by pcdi** [rstudio/rstudio#10076]
### System details

    RStudio Edition : Desktop 
    RStudio Version : RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) for Windows
    OS Version      : x86_64-w64-mingw32/x64 (64-bit) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    R Version       : R version 4.1.1 (2021-08-10) -- "Kick Things"

### Steps to reproduce the problem
File -> Import Dataset -> From Text (readr) ...
or
In the Files pane click on a `.csv` and select `Import Dataset ...`

#### Example Data:

```csv
variable,year,value
this_is_only_a_test,2019,297
```

Make any column wider by dragging the separator line in the header.

### Describe the problem in detail

The widths of the header and the rest of the preview table do not match anymore.

![Screenshot illustrating the problem](https://user-images.githubusercontent.com/4654151/141459525-ca946b43-156d-48a2-bd87-cca350e1b244.png)

### Describe the behavior you expected

The widths should be the same.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@pcdi Thank you for raising the issue! We'll review this as we continue to develop RStudio.

Reproducible in RStudio Desktop 2021.09.0+351 on Windows 10.
Not reproducible (works correctly) in RStudio Desktop on MacOS 12, nor with RStudio Server on Ubuntu 20.04 via Safari on MacOS 12.

**Comment by mikebessuille** [comment]
Does this display correctly in the data viewer, once you import?

**Comment by ronblum** [comment]
Yes—at that point it's just an R data frame viewed through the Data Viewer. We had similar issues with the Data Viewer a long while back, but they've been resolved.

**Comment by romainfrancois** [comment]
This appears to be fixed, at least in RStudio 2022.12.0-daily+280 "Elsbeth Geranium" Daily, but probably sooner. 

https://user-images.githubusercontent.com/2625526/197167809-64940b15-e2d0-4873-9a16-678ba61ade92.mov
