### ISSUE TITLE
Ctrl-Enter does not capture the full expression when there are multi-line strings in the middle

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#10077]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0
    OS Version      : Windows 10
    R Version       : 4.1.2

### Steps to reproduce the problem

1. Paste the code below into a code window
2. Press `Ctrl-Enter` at line 1 to execute the assignment into the `Parser` variable

Code:
```r
Parser <-
  R6::R6Class(
    "Parser",
    public=list(
      tokens=TOKENS,
      literals=LITERALS,
      value=list(),
      p_datetime=function(doc="datetime : date 'T' time", p) {
      },
      p_date=function(doc="date : year
                                | year subyear", p) {
      },
      p_subyear=function(doc="subyear : month
                                      | week
                                      | oday", p) {
      },
      p_month=function(doc="month : digit2
                                  | digit2 mday", p) {
      },
      p_mday=function(doc="mday : digit2
                                | digit2 subday") {
      },
      p_week=function(doc="week : 'W' digit2
                                | 'W' digit2 weekday", p) {
      },
      p_weekday=function(doc="weekday : DIGIT
                                      | DIGIT subday", p) {
      },
      p_oday=function(doc="oday : digit3
                                | digit3 subday", p) {
      },
      p_subday=function(doc="subday : 'T' hour", p) {
      },
      p_hour=function(doc="hour : digit2
                                | digit2 ':' minute", p) {
      },
      p_minute=function(doc="minute : digit2
                                    | digit2 second", p) {
      },
      p_second=function(doc="second : digit2
                                    | digit2 fraction", p) {
      },
      p_fraction=function(doc="fraction : DECIMALPOINT multi_digit", p) {
      },
      p_multi_digit=function(doc="multi_digit : DIGIT
                                              | DIGIT multi_digit", p) {
      }
    )
  )
```

### Describe the problem in detail

The last two parentheses are not included in the execution, so R waits for the closing parentheses.  I think that it is related to strings that cross multiple lines in the middle of the code.

### Describe the behavior you expected

All lines are executed, and the "Parser" object is assigned.  (For the code to fully work, you would also need to install the "rly" library, but that is not required to see the issue.)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: Reproducible in RStudio Desktop on MacOS 12, as well, in version 2021.09.1+371 and 1.2.5042.

**Comment by billdenney** [comment]
This issue is still present in 

RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by kevinushey** [comment]
For reference, here's the big glob of goo that handles execution of multi-line expressions.

**Comment by billdenney** [comment]
This would be a big change, but might it be easier to use anltr with the R grammar: https://github.com/antlr/grammars-v4/blob/master/r/R.g4

(I'm not one to implement such a change, but it seems that you're using regexps for what would better fit with a parser.)

**Comment by billdenney** [comment]
P.S.  I like the use of the technical term "big glob of goo" 😄

**Comment by mikebessuille** [comment]
See Hadley's simple reprex in https://github.com/rstudio/rstudio/issues/11124

**Comment by billdenney** [comment]
Yes, the other two issues appear to be the same underlying problem with simpler examples.

**Comment by jonvanausdeln** [comment]
Verified on
2022.11.0-71
Windows 11, MacOS 12.4, Linux 22.04

Works as expected with several different code snippets
