### ISSUE TITLE
Custom `format()` method isn't always utilized in data viewer

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#10073]
Follow up to https://github.com/rstudio/rstudio/pull/7240, CC @kevinushey since you were the author

If you have an object with >1 classes and a custom format method, then the format method won't be used in the data viewer because `getS3Method()` requires `class` to be length 1.

i.e.

```r
library(vctrs)

# We have a format method
vctrs:::format.vctrs_list_of
#> function(x, ...) {
#>   format.default(x)
#> }
#> <environment: namespace:vctrs>

x <- list_of(1)

# Oh dear
.rs.formatDataColumnDispatch(x)
#> Error in utils::getS3method("format", class = class(col), optional = TRUE): length(class) == 1L is not TRUE

# i.e.
utils::getS3method("format", class = class(x), optional = TRUE)
#> Error in utils::getS3method("format", class = class(x), optional = TRUE): length(class) == 1L is not TRUE

# vs 
utils::getS3method("format", class = class(x)[[1]], optional = TRUE)
#> function(x, ...) {
#>   format.default(x)
#> }
#> <environment: namespace:vctrs>
```

You could probably just do `class(col)[[1]]` here https://github.com/rstudio/rstudio/blob/51009f4cff7b0f45f9bd8762d7c0514b0de537bd/src/cpp/session/modules/SessionDataViewer.R#L46

Or maybe you'd want to loop through the classes of `col`, stopping on the first with a `format()` method?

**Comment by DavisVaughan** [comment]
reprex, I think:

``` r
format.foo <- function(x) {
  rep("Hi there!", length(x))
}

x <- structure("x", class = c("foo", "bar", "character"))

.rs.formatDataColumnDispatch(x)
#> Error in utils::getS3method("format", class = class(col), optional = TRUE): length(class) == 1L is not TRUE

# df <- data.frame(x = x)
# View(df)
```

**Comment by kevinushey** [comment]
> `getS3Method()` requires class to be length 1.

Well, that's silly!

> Or maybe you'd want to loop through the classes of col, stopping on the first with a format() method?

I wonder why we don't just use `format(col)` here directly (catching errors and checking output as appropriate).

**Comment by DavisVaughan** [comment]
I guess cause you'd rather call `as.character()` unless you _know_ that a `format()` method has been implemented? Not sure if that is the right approach, but that seems to be the rationale for the current behavior

**Comment by kevinushey** [comment]
Ah, you're exactly right. That makes sense.

In that case, we should probably iterate over the classes for that object.

**Comment by jgutman** [comment]
Verified in RStudio Desktop 2022.06.0-daily+26 on Mac OS 12.1.

Created package with the following code
```
#' format foo
#' @rdname format
#' @export
format.foo = function(x, ...) {
  rep("Hi there!", length(x))
}

#' subset foo
#' @rdname subsetter
#' @export
`[.foo` = function(x, ...) {
  print("using custom subsetter")
  structure(NextMethod(), class = class(x))
}
```

And tested with 

```
devtools::load_all("~/testfoo")
x <- structure(1:3, class=c("foo", "bar", "character"))
format(x)
x[1]
df <- data.frame(x=x)
View(df)
```

displays as expected
<img width="118" alt="Screen Shot 2022-01-26 at 8 35 47 AM" src="https://user-images.githubusercontent.com/7817881/151172810-6cda802b-a1db-40ea-8b22-980bf11f4c7d.png">

**Comment by jgutman** [comment]
Note that I also tested the above in 2022.06.0+14, which does not have #10390 in it, and it appeared to work in that build as well

**Comment by kevinushey** [comment]
FYI; if you want to make testing of S3 dispatch a bit easier you can register S3 methods directly within a session (without requiring a separate package), e.g.

```
x <- structure(c("a", "b", "c"), class = "foo")
registerS3method("format", "foo", toupper)
format(x)
```

which would give here:

```
> format(x)
[1] "A" "B" "C"
attr(,"class")
[1] "foo"
```

**Comment by jgutman** [comment]
> FYI; if you want to make testing of S3 dispatch a bit easier you can register S3 methods directly within a session (without requiring a separate package), e.g.
> 
> ```
> x <- structure(c("a", "b", "c"), class = "foo")
> registerS3method("format", "foo", toupper)
> format(x)
> ```
> 
> which would give here:
> 
> ```
> > format(x)
> [1] "A" "B" "C"
> attr(,"class")
> [1] "foo"
> ```

Yes, Romain had done that in his code snippet testing the fix, but I wanted to do the extra check

**Comment by kevinushey** [comment]
Ah, sorry, you're right. Thank you for the extra due diligence!
