### ISSUE TITLE
PMCP - Create / configure the AWS subaccounts

### ISSUE THREAD

**Issue by rodrigobrim** [rstudio/rstudio#10084]
# Package Manager Cloud Project

The first part of this project would be to build out three new AWS sub-accounts:

rstudio package manager team
rstudio package manager staging
rstudio package manager production

The company is moving toward Pulumi as a cloud provisioner software, so these environments would be version-controlled and deployed via Pulumi in an automated fashion, and the sensitive data will be controlled/stored by a secret/key manager.

Each environment must have its configuration, which will store its peculiarities, but share the core of functionalities by Pulumi shared libraries.

### rstudio-pm-team
This account could either be called “-dev” or “-qa” and will be used to host all non-production or staging workloads. This means it will be the new account where Package Manager developers spin up “grid” EC2 instances. It also means that it will be used for short-lived prototypes or ephemeral jobs like disaster recovery investigations. The final use-case for this environment will be to create temporary environments that mimic customer topologies to make debugging support issues easier.

### rstudio-pm-staging
The staging account will be a 1:1 replica of production where the same S3 buckets, applications, and Kubernetes clusters live. Like its name implies, it will be used to stage deployments, software upgrades, hardware changes, etc. before either rolling back or deploying the same changes to production.

### rstudio-pm-prod
The production account will first run a number of applications including:

Public Package Manager (external)
Solo Package Manager (internal/QA, SQLite-backed RSPM)
S3 Package Manager (internal/QA, S3-backed RSPM)
Cluster Package Manager (internal/QA, PostgreSQL-backed RSPM)
Traditional Package Manager (internal/QA, EC2-based RSPM for systemd, etc.)
New CRAN “server”: Clone of the existing CRAN server
Binary building K8s clusters

It will also become the new home of the R package binaries and RSPM deployment S3 buckets which currently live in the main account.

The other net-new responsibility for our production account will be a new Kubernetes cluster that will replace the GKE and Azure clusters currently used for R package binary building. This will require some changes to the existing manifest / jenkins job, but designed correctly should scale and recover more quickly (currently if one OS/R version fails we need to re-run the entire job).

**Comment by ronblum** [comment]
@rodrigobrim I moved https://github.com/rstudio/rstudio-pro/issues/3091 to the rstudio-pro repo because of the use of Kubernetes. Should this be in pro, as well?

**Comment by tylfin** [comment]
Please close this belongs in github.com/rstudio/aws-package-manager
