### ISSUE TITLE
RStudio crashes at opening

### ISSUE THREAD

**Issue by ecardenes** [rstudio/rstudio#10083]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.4.1717
    OS Version      : macOS Catalina 10.15.7
    R Version       : 4.1.2

### Steps to reproduce the problem
Launch RStudio
### Describe the problem in detail
It crashes in a few seconds (or less!)
### Describe the behavior you expected
Normal opening of the four panels

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

After updating both R and RStudio, I am unable to use RStudio. Part of the crash report is:

Process:               RStudio [6401]
Path:                  /Applications/RStudio.app/Contents/MacOS/RStudio
Identifier:            RStudio
Version:               1.4.1717 (1.4.1717)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RStudio [6401]
User ID:               501

Date/Time:             2021-11-14 11:21:44.540 +0100
OS Version:            Mac OS X 10.15.7 (19H1519)
Report Version:        12
Anonymous UUID:        AA292BFC-753F-8964-7561-56B44C673BD2

Sleep/Wake UUID:       8AC88F29-EB99-4526-9C06-E0226C3763A1

Time Awake Since Boot: 20000 seconds
Time Since Wake:       4100 seconds

System Integrity Protection: enabled

Crashed Thread:        22  Chrome_InProcGpuThread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Application Specific Signatures:
Graphics kernel error: 0xfffffffb

The R version is:

platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie  

And the sessionInfo()

R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2

**Comment by ronblum** [comment]
@ecardenes Thank you for raising this! Did this work in previous versions of RStudio Desktop and R? If so, which versions? Also note that the current release of[ RStudio Desktop is 2021.09.1+372 Ghost Orchid](https://dailies.rstudio.com/version/2021.09.1+372.pro1/).

**Comment by kevinushey** [comment]
Likely the same as https://github.com/rstudio/rstudio/issues/10020.
