### ISSUE TITLE
Make button "Load workspace" explicitely call base::load

### ISSUE THREAD

**Issue by ATpoint** [rstudio/rstudio#10089]
The `Load workspace` button should always explicitely call `base::load` rather than `load` as this can be masked, e.g. by `renv::load` when `renv` is `library()`-ed (I know, bad practice, but can happen). 

MWE:
```
library(renv)
# and then try to load a Rdata file with the button -- will conflict.
```

**Comment by ronblum** [comment]
@ATpoint Thank you for raising this issue!

To reproduce:
1. `Session -> Save Workspace As...`
2. Name the file `MySpace.RData` and click `Save`
3. In Console: `library(renv)`
4. `Session -> Load Workspace`
5. Choose `MySpace.RData` and click `Open`

Output:
> \> load("~/MySpace.RData")
Error: failed to create directory at path '/Users/ronblum/MySpace.RData/renv/library/R-4.1/x86_64-apple-darwin17.0'
In addition: Warning message:
In dir.create(rownames(info), recursive = TRUE) :
  cannot create dir '/Users/ronblum/MySpace.RData', reason 'Not a directory'

**Comment by jennybc** [comment]
Feels somewhat related to #8031

**Comment by mikebessuille** [comment]
Try to address this at the same time as #8031.  Check with Kevin.

**Comment by jgutman** [comment]
QA: 


To reproduce:

Session -> Save Workspace As...
Name the file MySpace.RData and click Save
Session -> Load Workspace
Choose MySpace.RData and click Open

Console should show `load(MySpace.RData)`.

Then, `library(renv)`
Session -> Load Workspace
Choose MySpace.RData and click Open

In this case, console should show `base::load(MySpace.RData)`

Neither should error.

**Comment by romainfrancois** [comment]
✅ 

<img width="462" alt="image" src="https://user-images.githubusercontent.com/2625526/154046218-ffe50a2e-74fe-4971-be2d-10cae2c38ac9.png">
