### ISSUE TITLE
Add hover text to the button that returns Files pane to top-level of Project

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#10092]
This tweet has gotten lots of love <https://twitter.com/JennyBryan/status/1460296605186228224>, because this button is super useful.

<img width="571" alt="snap-to-project" src="https://user-images.githubusercontent.com/599454/142047148-8d817e22-5e05-45c0-b05b-5d449b03214e.png">

It's clear that lots of people don't know about it. In a reply, @noamross has a good suggestion, which is that it should have hover text that helps people discover what it does.

**Comment by ronblum** [comment]
Verified that
1) Hover text appears: "Go to project directory"
2) Drilling down into a directory, then clicking on the icon, returns the Files Pane to the project directory

in
- RStudio Desktop 2022.02.0+364 on MacOS 12.1
- RStudio Server 2022.02.0+364 on Ubuntu 20.04 via Chrome on MacOS 12.1
