### ISSUE TITLE
Installing dev dependencies gives permission denied on clean machine (Mac)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10094]
### Steps to reproduce the problem

On a Mac that hasn't been used for RStudio development, clone the repo and run "install-dependencies-osx" from `rstudio/dependencies/osx`.

### Describe the problem in detail

Fails with:

```
➜  osx git:(main) ./install-dependencies-osx
[I] RSTUDIO_TOOLS_ROOT: /opt/rstudio-tools/x86_64
[I] Found BREW_X86: /usr/local/bin/brew
mkdir: /opt/rstudio-tools/x86_64/../x86_64: Permission denied
```

### Describe the behavior you expected

You can work around this by creating /opt/rstudio-tools (with sudo) then `chown` it to your user account, then run the script again.

Shouldn't have to do this! Confirmed happens on both Intel and M1 Mac.

**Comment by kevinushey** [comment]
> You can work around this by creating /opt/rstudio-tools (with sudo) then chown it to your user account, then run the script again.

FWIW, I think it should be unnecessary to `chown` it back to your own user account -- we more carefully check whether `sudo` is required for installing dependencies in other contexts; it's just the case where the directory is first created that we don't handle.
