### ISSUE TITLE
RStudio IDE on RHEL freezes during "Open File" dialog

### ISSUE THREAD

**Issue by anjasummaabb** [rstudio/rstudio#10101]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.463-1
    OS Version      : RHEL 7
    R Version       : several

### Steps to reproduce the problem
Open RStudio IDE, click on "File", click on "Open File..."
### Describe the problem in detail
The file select dialog opens, but then the GUI freezes. No error visible in command line or in GUI. Thread keeps running.
Fun fact: It works through the file browser on the right side. Just not through the dialog.

More information in case that helps:
I searched through your code a bit and ended up in [..]src/cpp/desktop/DesktopGwtCallback.cpp:
There I saw that you use QFileDialog.
I found a description of it here: https://doc.qt.io/qt-5/qfiledialog.html
"By default, a platform-native file dialog will be used if the platform has one. In that case, the widgets which would otherwise be used to construct the dialog will not be instantiated, so related accessors such as layout() and itemDelegate() will return null. You can set the DontUseNativeDialog option to ensure that the widget-based implementation will be used instead of the native dialog."
And a discussion of using that dialog on Linux here: https://github.com/OPM/ResInsight/issues/6345
"The native file dialog can cause full freeze on some Linux systems. To make sure this is handled correctly and identically in all situations, add a thin wrapper around QFileDialog. On Linux, always use Qt file dialog. On Windows, use native file dialog as before."
I am not an expert in cpp or QT, but I hope this may help you.
We tried to find out which file browser is used in the background, but failed. We opened several ones directly from the command line (gnome and xcde (??))  and that worked without freezing.

There are several users on this Linux workstation and that problem occurred recently for one of them. We tried to eliminate all other causes - since it works one way, but not through the dialog, we think the problem comes from there. 
### Describe the behavior you expected
I expect it to allow me to select a file and open that.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@anjasummaabb RStudio Desktop 1.1.463 is no longer supported. The current version is 2021.09.1+371, available at https://www.rstudio.com/products/rstudio/download/#download . What do you see with the current version?

**Comment by ronblum** [comment]
@anjasummaabb What happens if you change to sofwtare rendering? Instructions for it are available at https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by anjasummaabb** [comment]
We tried that (using the environment variable) to no avail. The user still cannot even start RStudio IDE, the error message stays the same.
Do you have any other ideas how to solve that problem?

**Comment by anjasummaabb** [comment]
It seems to me that this current problem we're facing (RStudio IDE not starting) is due to some changes in the GUI. I think I did not mention that before, but we use RStudio via X11 forwarding (MobaXTerm or Putty+Xming). This worked well with the older version, but obviously not with the new one. Is there anything we have to change in our server's configuration?

**Comment by anjasummaabb** [comment]
Since the newest version does not start for us at all, we're reverting back to an old version.
We hope that that will at least allow us to work through that workaround and that we won't have to upgrade RStudio as long as we have to use the RHEL7 workstation.
