### ISSUE TITLE
Hierachial file list in Git tab to make it easier to choose individual files in subfolders

### ISSUE THREAD

**Issue by sorenoneill** [rstudio/rstudio#10102]
When using the git tab to select files for staging, only files in the top folder level is listed.

Sub-folders are also listed and can be staged, but this stages every file in the sub-folder (and lists them in the git tab).

This makes it difficult to select individual files in a sub-folder.

# Work around

It is possible to simply use `git add` from a terminal, but that is not optimal for the less tech accomplished user.

# Suggested solution

Retain current functionality, i.e. when staging a sub-folder every file is staged

Add an 'unfold' option to the folders listed in the git file panel that unfolds the folder content and allows users to stage individual files.

**Comment by sorenoneill** [comment]
Git tab files list including the sub-folder 'gfx'

![Screenshot from 2021-11-17 17-29-30](https://user-images.githubusercontent.com/13156743/142241608-e788eb52-5bec-42d1-9a92-e09542a8160d.png

When staging the sub-folder 'gfx' every file in it is staged.

![Screenshot from 2021-11-17 17-29-55](https://user-images.githubusercontent.com/13156743/142241628-a1946639-01e7-4768-b176-c470bd5ddf5b.png)
)

**Comment by ronblum** [comment]
@sorenoneill Thank you for the suggestion!

**Comment by colearendt** [comment]
Yes! I love this idea!
