### ISSUE TITLE
R session failed to start on arm64 version of R

### ISSUE THREAD

**Issue by vincentleooo** [rstudio/rstudio#10100]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2022.01.0-daily+214
    OS Version      : macOS 11.6.2
    R Version       : 4.1.2-arm64

### Steps to reproduce the problem

Opening RStudio with Apple Silicon R fails to start R session. R works normally when run through CLI or VS Code. Attempted to uninstall latest stable build of RStudio and installed the latest daily build too.

##### RStudio Version

RStudio 2022.01.0-daily+214, "Prairie Trillium" (e5d5b4f4, 2021-11-16) for macOS

Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

##### Error message

[No error available]

##### Process Output

The R session exited with code 6. 

Error output:

```
dyld: could not load inserted library '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' because no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Resources/lib/libR.dylib: mach-o, but wrong architecture
	/Library/Frameworks/R.framework/Resources/lib/libR.dylib: stat() failed with errno=1


```

Standard output:

```
[No output emitted]
```

##### Logs

*/Users/vincentleonardo/.local/share/rstudio/log/rsession-vincentleonardo.log*

```
2021-11-11T09:47:23.388430Z [rsession-vincentleonardo] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-11-11T09:47:23.388882Z [rsession-vincentleonardo] ERROR r error 5 (R symbol not found) [symbol: .rs.extractRCode]; OCCURRED AT rstudio::core::Error rstudio::r::exec::RFunction::call(SEXP, bool, SEXP *, sexp::Protect *) src/cpp/r/RExec.cpp:475; LOGGED FROM: void rstudio::session::modules::code_search::RSourceIndexes::update(const boost::shared_ptr<SourceDocument> &) src/cpp/session/modules/SessionCodeSearch.cpp:997
2021-11-11T09:47:23.388882Z [rsession-vincentleonardo] ERROR r error 5 (R symbol not found) [symbol: .rs.extractRCode]; OCCURRED AT rstudio::core::Error rstudio::r::exec::RFunction::call(SEXP, bool, SEXP *, sexp::Protect *) src/cpp/r/RExec.cpp:475; LOGGED FROM: void rstudio::session::modules::code_search::RSourceIndexes::update(const boost::shared_ptr<SourceDocument> &) src/cpp/session/modules/SessionCodeSearch.cpp:997

```
                
### Describe the behavior you expected

R session starts as per normal.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@vincentleooo Thank you for raising this! Does the current released version,[ RStudio Desktop 2021.09.1+372](https://www.rstudio.com/products/rstudio/download/#download), work?

**Comment by ronblum** [comment]
Note: This is the same error as in #9543, with a solution provided at https://github.com/rstudio/rstudio/issues/9543#issuecomment-906839088. I'm uncertain if this is the expected solution, hence tagging it for `qa repro` and Prairie Trillium for the moment.

**Comment by vincentleooo** [comment]
> @vincentleooo Thank you for raising this! Does the current released version,[ RStudio Desktop 2021.09.1+372](https://www.rstudio.com/products/rstudio/download/#download), work?

The current released version works as per normal with x86 R, but also didn't work with AS at first.



> Note: This is the same error as in #9543, with a solution provided at [#9543 (comment)](https://github.com/rstudio/rstudio/issues/9543#issuecomment-906839088). I'm uncertain if this is the expected solution, hence tagging it for `qa repro` and Prairie Trillium for the moment.

Wow, this actually works. From what I see, it's about the `rsession` being x86 only, and thus symlinking it to `rsession-arm64` makes sense. Thanks, you made my day :).

This actually initially happened as I updated my brew packages, and it automatically installed an arm64 version of R. I'm not sure if my problems can be fixed by doing checks in RStudio and doing the `rsession` changes automatically. This will probably help people who updated their R installation (realising it or not) to a different architecture. Maybe we can include this as a guide since I have had a hard time finding posts on it for the past few days too. CMIIW, though.

**Comment by vincentleooo** [comment]
Closing this as the solution is from #9543.

**Comment by astayleraz** [comment]
I was not able to reproduce this on my m1 with version 2022.01.0-daily+214 and R4.1.0.
