### ISSUE TITLE
Electron dev mode startup fails to show config error dialogs, then hangs

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10114]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : main branch
    OS Version      : macOS Monterey (haven't tried other macOS versions)
    R Version       : Any

### Steps to reproduce the problem

This is a dev-environment-only issue.

Build the native code using `-DRSTUDIO_TARGET=Server`. Specifically, don't build the Qt Desktop.

Then try to start the Electron app using `yarn start`.

### Describe the problem in detail

The Electron icon appears, but no UI, and you can't quit the Electron app. Have to force-kill it.

### Describe the behavior you expected

There should be an error dialog displaying saying the `rdesktop-dev.conf` file wasn't found. Currently you have to build Qt Desktop to create this file.

We will get rid of this dependency, but more concerned with why showing a dialog with `dialog.showErrorBox` isn't working. In this case, it happens here:

https://github.com/rstudio/rstudio/blob/2853a5d4aa92f323856ec944db77f70d528cc173/src/node/desktop/src/main/application.ts#L117

It is supposed to be safe to use this API even during app startup before `ready`, and it was previously working. Probably either an Electron update, or an electron-forge update somehow broke this.

If we can't make this work then we should switch to just showing the error via `logger().logErrorMessage`, but it would be nice to be able to show error dialogs during startup!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by matheustavaresdev** [comment]
@gtritchie please review #10136
