### ISSUE TITLE
SQLite window functions fail when using RStudio Knit button (work fine with manual knit)

### ISSUE THREAD

**Issue by byteit101** [rstudio/rstudio#10122]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 351
    OS Version      :  Linux Debian 10 x64
    R Version       :  3.6.3

### Steps to reproduce the problem

Open this RMarkdown file in RStudio:

    ---
    title: "Testing"
    author: "Me"
    date: "12/2/2021"
    output: html_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = F,tidy=F)
    library(RSQLite)
    library(DBI)
    
    
    con <- dbConnect(RSQLite::SQLite(), "test.sqlite3")
    ```
    
    ## R Markdown
    
    This is an R Markdown document.
    
    ```{r}
    
    temporal_modes = dbGetQuery(con, "select row_number() over (order by myindex desc) rank from MyTable  group by mygroup") 
    ```

Have a SQLite3 database with the following table in a file called test.sqlite3:
```sql
CREATE TABLE `MyTable` (
	`somethingelse`	INTEGER,
	`myindex`	INTEGER,
	`mygroup`	INTEGER
);
```

### Describe the problem in detail

Using the Knit button in RStudio, you will get this error:
```
Quitting from lines 22-24 (testing.Rmd) 
Error in result_create(conn@ptr, statement) : near "(": syntax error
Calls: <Anonymous> ... .local -> new -> initialize -> initialize -> result_create
Execution halted
```

### Describe the behavior you expected

Using `knit`/`render` in the console, the file knits successfully

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@byteit101 Thank you for raising this! The code didn't come through, though. Could you either:
1) Attach a file to the issue in a comment? I'd do so via the web page; replying by email doesn't always seem to work.
2) Or, paste it into a comment, surrounded by four quotes: ` ```` `

Thanks!

**Comment by byteit101** [comment]
Oh, wait, what? I must have confused github when I went to try to make a test case for the bug. Updated with test case
