### ISSUE TITLE
"Insert Section" should have auto-indent

### ISSUE THREAD

**Issue by brb-arraytools** [rstudio/rstudio#10123]
I would suggest "Insert Section" in the RStudio menu should have auto-indent for the added section line. 

Now it always starts from the beginning of the line. If I use the "Reindent Lines" command, the line will be indented.

**Comment by ronblum** [comment]
@brb-arraytools Thank you for raising this! However, I'm not sure why you would expect sections to be indented. Using a few online sources, it appears that sections are not expected to be indented:
- https://bookdown.org/yih_huynh/Guide-to-R-Book/r-conventions.html#built-in-data
- https://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R

Also, can you please provide a couple of things:
1) Sample code ton which you're using "Reindent Lines"—I don't get the indentation for sections, so I'd like to try to reproduce this.
2) The environment you're working with:
    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by brb-arraytools** [comment]
Hi Ron,

I see. I don't mind that the sections do not indent. The problem is that after I use "Reindent lines", they will indent. It seems to be a bug.

  1.  Sample code ton which you're using "Reindent Lines"—I don't get the indentation for sections, so I'd like to try to reproduce this.

I attached one of my code files. All my code files are the same: sections indent after applying the command "Reindent lines". I use the Dracula theme in RStudio. Will that affect the performance?

  1.  The environment you're working with:
RStudio Edition :
  2.  RStudio Version :
  3.  RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
OS Version : Windows 10
R Version : 4.1.2

Thank you,
Qian


________________________________
