### ISSUE TITLE
"Show Internals" text in Traceback can overflow

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10133]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.1.0.235
    OS Version      : macOS Monterey 12.0.1
    R Version       : R version 4.1.2 (2021-11-01)

---

<img width="234" alt="Screen Shot 2021-11-24 at 12 12 17 PM" src="https://user-images.githubusercontent.com/1976582/143307132-d77181d9-a1d6-4d63-93fe-1089dce358ad.png">

**Comment by jgutman** [comment]
@ronblum are you able to reproduce this? @kevinushey do you have more detail? 

I tried this myself on both 2022.2.0.366 and 2021.9.1.372 Desktop Open source, and for me Show internals doesn't overflow, it just gets truncated as expected

1. Run `debug(stats::rnorm)` and  then `stats::rnorm()` to open the traceback pane.
2. Make the window smaller so "Show internals" doesn't fit

"Show internals" gets truncated to "Show" with no overflow

![image](https://user-images.githubusercontent.com/7817881/149171922-6c65a678-5962-41f3-a8fa-929f3ed5170d.png)

**Comment by kevinushey** [comment]
Strangely, I can't reproduce this behavior anymore either. :-/

I'll close this for now, but if I see it again I'll re-open with extra details.
