### ISSUE TITLE
Spell check "abc" button should not always appear greyed-out/inactive

### ISSUE THREAD

**Issue by sellorm** [rstudio/rstudio#10144]
This has bothered me for years, but is ridiculously minor.

The spell check button in the IDE always appears as though it's greyed out. This isn't a problem, except that it may lead some users to falsely believe that it is not currently possible to perform a spell check

Here's a screenshot from a recent daily:

<img width="483" alt="Screenshot 2021-11-26 at 15 03 49" src="https://user-images.githubusercontent.com/2036487/143599981-5e6a88eb-2b89-4698-9476-6637e522d111.png">

In the screenshot, the "forward" button _is_ greyed-out, but the "abc" button, although it appears similarly grey, is actually active.

Ideally, the button should appear to be active at times when it's possible to perform a spell check and greyed out at times when it's not.

**Comment by ronblum** [comment]
@sellorm That's a good point—thank you for raising it!

**Comment by jmcphers** [comment]
It's a little better in light mode; I think this is one of those icons that wasn't redone for dark themes.

![image](https://user-images.githubusercontent.com/470418/143913933-67116ce4-ec1b-480b-b542-7b7e4a81e1c1.png)

**Comment by sellorm** [comment]
It is a little better @jmcphers, but even in light mode it doesn't carry the same visual weight as the find and knit icons. To my eye it looks more like the greyed out save icon. I think it's probably just because of the grey font used for the "abc" that's throwing it off.
