### ISSUE TITLE
Keyboard shortcuts to cut/delete code chunks in R Markdown

### ISSUE THREAD

**Issue by yuanx749** [rstudio/rstudio#10147]
There are buttons and keyboard shortcuts to insert and run code chunks in RStudio. It will be great that more options could be added, such as delete/cut/paste. Now my workaround is to use `shift` to select lines or fold the chunk and delete it, which is a bit tedious.

Jupyter Notebook supports many operations on cells like insert/run/cut/copy/move, with corresponding keyboard shortcuts. However, in my opinion R Markdown has advantanges in many usecases. Therefore, it would be super helpful if these sorts of features could be implemented in Rmd.

Thanks for this excellent product!

**Comment by ronblum** [comment]
@yuanx749 Thank you for the suggestion! Are you suggesting that we include additional keyboard options, in addition to the system shortcuts, such as <kbd>Cmd-X</kbd> and <kbd>Ctrl-X</kbd> for cut?

Also, thank you for the kind words!

**Comment by yuanx749** [comment]
@ronblum Thank you for your reply.

Not really, I mean more options on the code chunk as a unit.

In a code chunk of Rmd, we can press `Run Current Chunk` to execute all the lines in the chunk. But if I want to cut all the lines in a chunk, I have to select all manualy and cut them. I think it would be convenient to include these kinds of operations on code chunk as a whole, which could be some buttons or keyboard shortcuts.

**Comment by BlakeWallace** [comment]
Have there been any updates to this topic?  I am interested in using keyboard shortcuts to delete a chunk in a Quarto document.  I have control+alt+I to insert a chunk.  Why am I not finding a keyboard shortcut to delete an entire chunk?

**Comment by 1151k** [comment]
Really? Still no solution??
