### ISSUE TITLE
Ctrl+Up/Down jumps to function

### ISSUE THREAD

**Issue by Pestudkaru** [rstudio/rstudio#10140]
Ctrl+Up/Down is a default hotkey combination that scrolls the editor. But if there happens to be a user defined function(s) in the script then this shortcut jumps to the beginning of said functions. There doesn't seem to be a way to turn off this functionality. It is an extremely annoying behavior! Especially since I quite often click Ctrl and up/down by accident and end up god knows where.

**Comment by ronblum** [comment]
@Pestudkaru Thank you for raising this! Can you please provide the following?

1) The environment in which you're running:

###
    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

2) A simple example of code with which you're running into the issue.

**Comment by Pestudkaru** [comment]
I hope this is what you need! 
RStudio Edition : <Desktop>
RStudio Version : <1.4.1717> <Juliet Rose>
OS Version      : <mingw32>
System           : <x86_64>
R Version       : <4.1.0><Camp Pontanezen>

**Comment by CGMossa** [comment]
How do I disable this shortcut? It is unbelievably annoying.
