### ISSUE TITLE
Python chunks in knitted Rmd ignore figure size options

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#10145]
When knitting an Rmd file with R chunks that have plots, one can control the size of the plots through `fig.height` and `fig.weight` in the chunk setup, and when having python chunks, these will successfully control the figure size of the output that is generated **through the green "play" button** in the chunk", but **will be ignored in the produced HTML file** when the Rmd file is knitted through the blue "Knit" button at the top of the file.

Example .Rmd file:
````
---
title: "deleteme"
output: html_document
---

```{python, fig.width=1, fig.height=2}
import numpy as np, pandas as pd, plotnine as p9

rng = np.random.default_rng(seed=123)
df = pd.DataFrame({
    "col1" : rng.standard_gamma(1, size=10000)
})
plt = (
    p9.ggplot(df, p9.aes(x="col1"))
    + p9.theme_bw()
    + p9.geom_histogram(bins=50, fill="navy", color="navy")
)
print(plt)
```
````

This will produce an HTML in which the plot shows with its default size, while the figure that's generated below the chunk through the "play" button looks tall and narrow as specified by the options.

Changing the chunk options to `repr.plot.width` and `repr.plot.height` does not make any difference.

**Setup:** RStudio 2021.09.0 Build 351, R 4.1.2, Python 3.9.7 (conda), reticulate 1.22.

**Comment by ronblum** [comment]
@david-cortes Thanks! I can reproduce this as far back as RStudio Desktop 1.4.1106-3 on MacOS 12.1. Note that before that, even running individual chunks didn't respect `fig.height` and `fig.weight`.
