### ISSUE TITLE
Error at renv project startup from script in the .Rprofile

### ISSUE THREAD

**Issue by FedericoTrifoglio** [rstudio/rstudio#10154]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.1+372
    OS Version      :  Windows 10
    R Version       :  4.1.2

### Steps to reproduce the problem

1. clone repo https://github.com/FedericoTrifoglio/RStudio-2021.09.1.372-Bug.git
2. open project
3. run renv-setup.R
4. close RStudio
5. open project (might need to repeat 4.-5. a few times before you get the error)

### Describe the problem in detail
The error I usually get is "package or namespace load failed" but the message and where the error occurs can vary. 
![error](https://user-images.githubusercontent.com/45310182/143913769-b0c04881-91c2-4acf-a940-87dccec06bce.png)
Sometimes I also get some `random *** recursive gc invocation`

From my tests, this below in the .Rprofile of the project is what I think causes the error
```
  source("renv/activate.R")
  setHook("rstudio.sessionInit", function(newSession) {
    if (newSession) {
      rstudioapi::sendToConsole("rstudioapi::navigateToFile(\"foo.R\")")
      rstudioapi::sendToConsole("source(\"init.R\")")
    }
  }, action = "append")
```
If any of these is missing the error doesn't seem to occur
- it needs to be a renv project
- a script needs to be loaded up via rstudioapi (this is usually a script for the user to run interactively)
- a script needs to be sourced via rstudioapi (this is usually a helper file with custom functions)

I don't know maybe it's something that get executed to early or too late.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7619960/diagnostics-report.txt)

### Describe the behavior you expected
The error doesn't occur with previous versions of RStudio (at least not with 1.2 to 1.4). As a matter of fact, the repo used for this example vaguely resembles the structure of the repos we use internally in my team.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you also see this issue with the latest daily builds of RStudio? https://dailies.rstudio.com/

We recently fixed an issue that could cause errors of this form when R code was run immediately after starting the R session.

**Comment by FedericoTrifoglio** [comment]
Just tried on the most recent daily (259) using a few different examples and had no issues. So it seems this issue will be fixed in the next release.

**Comment by kevinushey** [comment]
Phew, that's great to hear. Thanks for taking the time to test!
