### ISSUE TITLE
Default datum in R markdown template as ISO

### ISSUE THREAD

**Issue by romunov** [rstudio/rstudio#10152]
When a R markdown document is created, header of the .Rmd file includes a `date` field. For example:

```
---
title: "Untitled"
author: "Roman Luštrik"
date: "11/29/2021"
output: html_document
---
```

Would it be possible to have this date in ISO format, i.e. `2021-11-29` by default?

**Comment by ronblum** [comment]
@romunov Thank you for the suggestion!

**Comment by ronblum** [comment]
Validated that this works in RStudio Desktop 2022.02.0+364.

@romainfrancois Should the date be in single or or double quotes? I was going to suggest using double quotes, consistent with the title and author fields, but I also found this about how we treat them: https://stackoverflow.com/a/25389694/15776955

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.02.0+389 on MacOS 12.1
- RStudio Server 2022.02.0+389 on Ubuntu 20.04 via Chrome on MacOS 12.1

Tested the following:
1) With the "Use current date" field unchecked:
    - The date field in the UI shows the current date
    - The date is displayed in the format YYYY-MM-DD
    - Anything can be typed in the field (it's a text field with a default value, no restriction on characters or format)
    - The value for the `date: ` line in the new document is populated with whatever was in the dialog
2) With the "Use current date" field checked:
    - The date field in the UI shows the current date
    - The date is displayed in the format YYYY-MM-DD
    - The date field is grayed out and uneditable
    - The `date: ` line in the new document is `date: "`r Sys.Date()`"`

I'm leaving this open for consideration for an automated test.

**Comment by ronblum** [comment]
For reference, this is the updated UI:
<img width="361" alt="rmarkdown_date" src="https://user-images.githubusercontent.com/31009952/150606452-28ff4bc5-ca9e-4c0a-bf8c-d8339262b0d8.png">

**Comment by ronblum** [comment]
Added automated test for the the current date used when "Use current date" isn't checked: https://github.com/rstudio/rstudio-ide-automation/pull/575

Submitted request for an automated test of the checkbox, for a later date: https://github.com/rstudio/rstudio-ide-automation/issues/577
