### ISSUE TITLE
Lint symbol remains in gutter during editing in visual editor

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#10156]
### System details

    RStudio Edition : Any
    RStudio Version : 2022.01.0-daily+255

### Steps to reproduce the problem

1. Create new R Markdown document in visual mode.
2. Edit one of the chunks so that it contains a syntax error in its R code.
3. Wait a few seconds for the linter to detect and display the syntax error.
4. Edit the line containing the syntax error.

### Describe the problem in detail

The gutter symbol (red X) lingers even while the line is being edited.

![image](https://user-images.githubusercontent.com/470418/143943780-920e3692-ff10-4b8d-98fa-e39dc1ab00de.png)

It remains in place until the linter is re-run and verifies that there is no lint on the line. 

### Describe the behavior you expected

The gutter symbol should be cleared while the line is being actively edited, in the same way that we clear the red squiggle. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cm421** [comment]
Verified fixed
```
R version:       4.1.2
Rstudio version: 2022.01.0-daily+271.pro2
OS version:      Ubuntu 20.04
```

Created the same syntax error shown above and checked that the red error logo disappeared at the same time as the red squiggle line when editing the line
