### ISSUE TITLE
Error  when trying to create new project. 

### ISSUE THREAD

**Issue by abalter** [rstudio/rstudio#10160]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) 
    OS Version      :  Windows 10 
    R Version       :   4.0.5

### Steps to reproduce the problem

Select "Project">"New Project"

### Describe the problem in detail
I get the following error:

![image](https://user-images.githubusercontent.com/5349876/144026192-23460589-efcf-4880-a1f4-09bb151f60a4.png)

### Describe the behavior you expected

Be able to create a new project

**Note:** I uninstalled and reinstall RStudio but that  didn't fix the problem.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7624815/diagnostics-report.txt)
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This seems potentially related? From the diagnostics report:

> 2021-11-30T09:58:46.939037Z [rsession-balter] ERROR system error 127 (The specified procedure could not be found) [description: The system cannot find the path specified.
|||]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::session::`anonymous-namespace'::quartoExec(const class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,const class rstudio::core::FilePath &,struct rstudio::core::system::ProcessResult *) src/cpp/session/modules/quarto/SessionQuarto.cpp:277; LOGGED FROM: class rstudio::core::json::Value __cdecl rstudio::session::quarto::quartoCapabilities(void) src/cpp/session/modules/quarto/SessionQuarto.cpp:631

Do you also see this issue in the latest [daily builds](https://dailies.rstudio.com) of RStudio?

**Comment by abalter** [comment]
Interesting. New Project no longer creates an error with the daily build.

I'm getting some weird behavior. I have a project in `\\wsl$\spectre_ubuntu\home\balter\arollig-16s`. When I try to open the project, i.e. open the `\\wsl$\spectre_ubuntu\home\balter\arollig-16s\arollig-16s.Rproj` file  in

```
C:\Users\balter>dir \\wsl$\spectre_ubuntu\home\balter\arollig-16s
 Volume in drive \\wsl$\spectre_ubuntu has no label.
 Volume Serial Number is 0000-0000

 Directory of \\wsl$\spectre_ubuntu\home\balter\arollig-16s

11/30/2021  12:26 AM                75 .gitignore
11/28/2021  08:56 PM               234 microbiome_databases
11/28/2021  08:56 PM                13 README.md
11/30/2021  12:26 AM            62,392 general_utilities.R
11/30/2021  12:29 AM    <DIR>          .git
11/28/2021  08:56 PM         4,924,243 asv_matrix_wide.rds
11/28/2021  08:56 PM             1,183 venn_diagrams.md
11/29/2021  05:25 AM    <DIR>          .Rproj.user
11/29/2021  05:27 AM            10,468 .Rhistory
11/30/2021  12:26 AM             1,703 phyloseq_test.R
11/30/2021  01:55 AM    <DIR>          analysis
11/30/2021  12:26 AM           792,845 microbiome_workflow.nb.html
11/30/2021  12:26 AM             3,142 microbiome_workflow.Rmd
11/29/2021  05:25 AM               205 vr-16s.Rproj
11/28/2021  08:56 PM    <DIR>          metadata
11/30/2021  12:26 AM    <DIR>          ..
11/30/2021  12:26 AM    <DIR>          .
              11 File(s)      5,796,503 bytes
               6 Dir(s)  185,168,199,680 bytes free
```

I get the following dialog:

![image](https://user-images.githubusercontent.com/5349876/144113972-78127103-58bd-412b-a246-eab8f5b3530f.png)

That directory doesn't even exist:

```
C:\Users\balter>dir E:\
 Volume in drive E is OneDrive
 Volume Serial Number is 6827-44D5

 Directory of E:\

10/25/2021  10:25 AM    <DIR>          OneDrive
11/30/2021  10:58 AM    <DIR>          spectre_ubuntu
               0 File(s)              0 bytes
               2 Dir(s)  158,073,655,296 bytes free
```

Likewise, when I try to create a project with an existing directory, 

![image](https://user-images.githubusercontent.com/5349876/144114545-b4031db0-9107-4d43-a30c-67dd3681ade8.png)

It tries to create it, but ends up with:

![image](https://user-images.githubusercontent.com/5349876/144114812-20f62ef9-bf95-4fb2-8ae7-36f88fcfae4d.png)

What have I done to deserve this behavior? RStudio is acting like my teenager.

**Comment by abalter** [comment]
Ok, now get this, I went and just double-clicked on the .Rproj file, and lo and behold it opened the project as expected.

**Comment by kevinushey** [comment]
Thanks for taking the time to test. To confirm, you don't see any of these issues with the previous releases of RStudio? Those are available here: 

https://www.rstudio.com/products/rstudio/older-versions/

Did you see anything like this with e.g. RStudio 1.4?

**Comment by abalter** [comment]
Correct.

**Comment by kevinushey** [comment]
Can you share any other details on your environment setup?

It sounds like you're using RStudio on Windows, with projects that live as part of your Windows Subsystem for Linux installation. `\\wsl$\spectre_ubuntu\home\balter\arollig-16s` is presumedly a network drive mapping to that space, but RStudio is (at least in some context) trying to resolve that to somewhere on the `E:/` drive. Is that correct?

Any other details you can share so that we might be able to try and reproduce locally would be helpful.

**Comment by abalter** [comment]
Everything you said is correct. I'm running 

OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

using Bootcamp on a 2021 MacBook pro.

WSL2 ubuntu 20.04

I should see what happens if I work from a windows directory. I'll try that and report back.

**Comment by 20210930** [comment]
Hi I also had the same problem when using creating new project. Have you solved this problem?
