### ISSUE TITLE
Password UI removes single space after commas and periods

### ISSUE THREAD

**Issue by allenbaron** [rstudio/rstudio#10164]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.1
    OS Version      : MacOS 11.6.1
    R Version       : 4.1.1

### Steps to reproduce the problem

1. `.rs.askForPassword("test , test . test")` (text has 1 space before and 1 after each comma and period)
2. `.rs.askForPassword("test,  test.  test")` (text has two spaces after both the comma and period)

### Describe the problem in detail

The RStudio password UI removes a single space after each `,` and `.` when displaying the prompt message. It does not remove spaces preceding them. Other punctuation marks appear to be unaffected, though I have not tested them exhaustively

Result of 1. <img width="386" alt="Screen Shot 2021-11-30 at 4 16 28 PM" src="https://user-images.githubusercontent.com/21225409/144129553-e0ef3244-5cd4-4f38-881d-d7f9430d6bc3.png">

Result of 2. <img width="385" alt="Screen Shot 2021-11-30 at 4 17 05 PM" src="https://user-images.githubusercontent.com/21225409/144129527-bfd95375-f711-4de3-a6af-f97cfa8c7a30.png">
 
I reported this previously to askpass (https://github.com/r-lib/askpass/issues/5) but it does not occur when skipping RStudio's password UI with `askpass:::askpass_mac("test, test")`. I also tested the RStudio's secrets UI `.rs.askForSecret`, which does not remove spaces.

### Describe the behavior you expected

I expect the text provided in the prompt argument to appear as typed in the password UI prompt message without the removal of spaces after commas and periods.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@allenbaron Thank you for raising the issue! I can reproduce this in version 0.13 of `rstudioapi` in
- RStudio Desktop 1.2.5042 and 2022.01.0-daily+252 and others in between on MacOS 12.1
- RStudio Server 2021.09.1+372

However, I haven't checked with earlier versions of `rstudioapi`. @mikebessuille please let me know if you'd like me to check that as well.

**Comment by mikebessuille** [comment]
@ronblum I don't think it's necessary to check older versions

**Comment by kevinushey** [comment]
Note that the `rstudioapi` package isn't actually involved here as the internal RStudio API is being called directly.

**Comment by kevinushey** [comment]
I don't think spaces are being removed here; the font rendering + spacing is just odd because of how the macOS dialog decides to render the `t` and `,` here. For example, with:

```
.rs.askForPassword("t,t,t : t , t , t")
```

I see:

<img width="416" alt="Screen Shot 2021-12-02 at 1 59 51 PM" src="https://user-images.githubusercontent.com/1976582/144510015-b07d665a-5901-4191-a22d-522244c937ba.png">

It'd be worth checking if the rendering here is different in Electron.

**Comment by gtritchie** [comment]
Here's how each of those cases looks in Electron on macOS 12.0.1.

![Screen Shot 2021-12-05 at 15 35 08](https://user-images.githubusercontent.com/10569626/144768585-849cf271-6763-4e31-b724-e71f29f54e0d.png)

![Screen Shot 2021-12-05 at 15 35 40](https://user-images.githubusercontent.com/10569626/144768591-35e39a44-6ac7-4988-8aaa-7fc2bde8c062.png)

![Screen Shot 2021-12-05 at 15 36 02](https://user-images.githubusercontent.com/10569626/144768595-75599b07-eab5-4046-8e85-6e709d6a40d8.png)

**Comment by gtritchie** [comment]
Confirmed this issue goes away with the Electron build.
