### ISSUE TITLE
Go to File using shortened filepaths

### ISSUE THREAD

**Issue by Nelson-Gon** [rstudio/rstudio#10161]
Hi, 

For the "Go to File/Function" popup accessible via `CTRL` + `.` on Windows,  I think it would be great if one could provide a file path to go to a file that is not currently in the workspace. 

For instance, if I wanted to go to a file that is in the next directory, I would insert `../my_file.R` and open this. I think this may be possible via the "File Open" shortcut (CTRL + O) but this also seems not to support file paths at least on Window$. 

Sorry if this is a duplicate.
Thanks,
NelsonGon

![image](https://user-images.githubusercontent.com/42792514/144029943-5c981919-6c47-411c-acc0-99ae8e2071b1.png)

**Comment by ronblum** [comment]
@Nelson-Gon Thank you for the suggestion! And no worries if it's a duplicate. FWIW, I found a few possibly related suggestions, but not a duplicate of yours.
