### ISSUE TITLE
Add Electron Desktop to the Mac build pipeline

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10169]
Goal: Automatically build the Electron desktop application for Mac via Jenkins when there is a change made in github (same as happens with the Qt desktop builds).

Work completed so far:

- ability to package the app (completed via #9957)
- build versioning (completed via #10167)

More work (do in whatever order makes sense to you):

- universal (one DMG containing RStudio.app that runs natively on both Intel and M1 Macs; tracked separately via #9957)
- Apple notarization (might be able to just reuse the same logic that's in `make-package`, if not for some reason, look at using the electron-forge feature for doing it)
- Create separate `Jenkinsfile.electron.macos` in root of repo (use `Jenkinsfile.macos` as a model)
    - That needs to invoke make-package with the `--rstudio-target=Electron` switch
    - Upload the resulting DMG to S3 bucket
    - (Eventually) Publish the results to https://dailies.rstudio.com/ (we don't want to do this yet)
    - (For now) Create a new page showing Electron builds so QA doesn't have to scrape S3 buckets
- Create a new Jenkins pipeline for open-source by duplicating the `macos-pipeline` from https://build.rstudioservices.com/job/IDE/ and pointing it at the new Jenkinsfile

**Comment by mikebessuille** [comment]
[ ] test
