### ISSUE TITLE
Add "openxlsx" as an option to Import Dataset -> Excel

### ISSUE THREAD

**Issue by luisvalenzuelar** [rstudio/rstudio#10179]
Hi there, I would suggest that the "Import Database" -> Excel option is expanded by allowing both `readxl` and `openxlsx` packages (like "From Text" with `base` and `readr`).

**Why?** Because sometimes one is working with excel files created with R (like with the `openxlsx` package, command `write.xlsx`). If the saved object is a dataframe, the class of the imported object with `readxl` and `openxlsx` are different, which creates some problems with certain commands. I have a question on stackexchange about it [here](https://stackoverflow.com/questions/70189504/write-xlsx-not-saving-data-as-dataframe).

**Comment by ronblum** [comment]
@raspatan Thank you for the suggestion, and for reference the StackOverflow discussion!

**Comment by kevinushey** [comment]
Why not just call `as.data.frame()` on object returned?
