### ISSUE TITLE
Emoji and Unicode panels don't appear using visual editor "Insert" dropdown

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10176]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.01.0-daily+252 & +267
    OS Version      : MacOS 12.1 and Ubuntu 20.04.2 (via Safari and Chrome on MacOS 12.1)
    R Version       : 4.1.2

### Steps to reproduce the problem

1. Open an R Markdown document in the IDE.
2. Switch to visual mode, if not already in it.
3. <kbd>Insert -> Special Characters -> Insert Emoji..."</kbd>
    - The emojis panel doesn't show up.
4. <kbd>Insert -> Special Characters -> Insert Unicode..."</kbd>
    - The Unicode character panel doesn't show up.

### Describe the problem in detail

It's not possible to insert emojis and Unicode characters using the dropdown menu.

### Describe the behavior you expected

The emoji and Unicode panels appear.

Note that this is a regression in Prairie Trillium, as it works correctly in Ghost Orchid 2021.09.1+372

**Comment by ronblum** [comment]
Oops—this should be in "test" in order to verify in the build. (Assigning to @ronblum to test.)

**Comment by ronblum** [comment]
Manual test: Follow the steps above, and include actually clicking on an emoji and Unicode character to make sure that this works fully (very simple and straightforward).

Automated test: Same as the manual test. I think this is worth automating.

**Comment by ronblum** [comment]
Confirmed manually with emoji and Unicode with
- RStudio Desktop 2022.01.0-daily+290 on MacOS 12.1
- RStudio Desktop 2022.01.0-daily+290 on Windows 10
- RStudio Server 2022.01.0-daily+290 on Ubuntu 20.04.2 via Safari on MacOS 12.1

Leaving open for automated test.

**Comment by ronblum** [comment]
Assigning to @cm421 for automated tests.

**Comment by cm421** [comment]
Automated tests are in with https://github.com/rstudio/rstudio-ide-automation/pull/519
