### ISSUE TITLE
RStudio UI flickers (panels and windows appear and disappear all the time)

### ISSUE THREAD

**Issue by matguidi** [rstudio/rstudio#10194]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.1.372-1
    OS Version      : Manjaro Linux with GNOME 41.1
    R Version       : 4.1.2 (2021-11-01) -- "Bird Hippie"

### Steps to reproduce the problem

Launch RStudio

`/usr/lib/rstudio/bin/rstudio`

### Describe the problem in detail

When I open RStudio, the UI is practically unusable. Panels, pop-up windows, etc. come and go all the time. Mouse clicks often do not work. Base R works, but it is hardly usable.

### Describe the behavior you expected

I expect RStudio to have a stable and usable UI.

I suspect the issue to be investigated is the recurring message in the log file:

`2021-12-07T11:21:58.384919Z [rsession-*myname*] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::__cxx11::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335`

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by matguidi** [comment]
Here is the full diagnostic report

[RStudio diagnostic report.txt](https://github.com/rstudio/rstudio/files/7668005/RStudio.diagnostic.report.txt)

**Comment by matguidi** [comment]
Here is a video showing the problem:
https://user-images.githubusercontent.com/59918868/145023796-f43aa6ae-ec0b-4520-8dc2-39273ad913b6.mp4

**Comment by ronblum** [comment]
@matguidi Thank you for raising the issue! We don't support Manjaro. The full of supported platforms is available at https://www.rstudio.com/about/platform-support/ However, it's worth keep track of. A few questions:

1) Does changing the rendering make a difference? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
2) Did previous versions of RStudio work?

**Comment by matguidi** [comment]
Thanks! Very quickly:

1. No, unfortunately. Not even with older versions.
2. They used to work. Now they don't work any more. So it must be some package that has been updated in the distro rather than something that has changed in RStudio.

I think the error message in the log file is the key, but I don't know how to interpret it.

**Comment by matguidi** [comment]
Apparently the problem was due to some package updates *unrelated to RStudio*.

Those packages were downgraded (probably because they were causing problems to other programmes as well) and now the issue is no longer present. I don't know which package in particular was responsible for this, so I'll give the list of all the packages that were downgraded.


`[2021-12-09T11:08:17+0100] [ALPM] downgraded vulkan-radeon (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded vulkan-intel (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded mesa-vdpau (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded libva-mesa-driver (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded lib32-vulkan-radeon (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded lib32-vulkan-intel (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded lib32-mesa-vdpau (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded lib32-mesa (21.3.1-0.1 -> 21.2.5-1)`
`[2021-12-09T11:08:17+0100] [ALPM] downgraded mesa (21.3.1-0.1 -> 21.2.5-1)`

**Comment by ronblum** [comment]
@matguidi Thank you for the update and added info! This is very helpful, especially for other users.

**Comment by grantmcdermott** [comment]
Thanks for the report and tip @matguidi. I just ran into the same problem after updating my Arch system. Downgrading `mesa`/`lib32-mesa`/`mesa-vdpau` all to 21.2.5-1 fixed the issue for me.

As an aside, I wonder if this is related to the upstream issues with (c)python 10.1.1. Apparently, it's causing a bunch of other things to [break](https://bbs.archlinux.org/viewtopic.php?id=272121).

**Comment by matguidi** [comment]
In Manjaro (stable branch) all those packages are still at 21.2.5-1. If they downgraded them it's certainly because they were causing issues to other software as well, not just RStudio. I hope they will release the upgrade only when all these problems are fixed.

**Comment by bshor** [comment]
I'm now experiencing this problem with Garuda Linux (an Arch derivative).

**Comment by matguidi** [comment]
> I'm now experiencing this problem with Garuda Linux (an Arch derivative), and downgrading the three packages @grantmcdermott mentions worked. Now I have to make sure they don't get reupdated.
> 
> I also had to combine this with switching to the daily binary because of the [other issue](https://github.com/rstudio/rstudio/issues/10280) I have had with an Arch derivative.

Downgrading the packages listed above should work in your case as well.

**Comment by bshor** [comment]
Yes, I needed to downgrade the 3 packages and it worked again.

**Comment by thunderbird-1990** [comment]
I have been experiencing the same issue on Arch.

However, on my machine, changing the rendering engine of RStudio from "OpenGL" to "Software" (as suggested by @ronblum ronblum) did fix this problem for me, just that the interface is now naturally less responsive.

**Comment by matguidi** [comment]
Just to report that the issue came up again today, after another update. Downgrading mesa (only) to version 21.2.5-1 worked for me.

**Comment by bshor** [comment]
A new version of Rstudio (build 382) has just been released. It fixed my[ Arch startup problem](https://github.com/rstudio/rstudio/issues/10280) that I temporarily dealt with by switching to daily binaries. Perhaps it might fix this panel problem, too?

**Comment by matguidi** [comment]
I confirm that with this build and the latest version of mesa (for my system this is v. 21.3.2-1), the issue is no longer there.

**Comment by dagdrommer** [comment]
The startup Problems I never had, however the flickering drives me nuts. I run Arch as well, the latest RStudio build 382 and `mesa 21.3.4-1`.

As I am depended on R and R-Studio for work, I already think about changing to an officially supported distro. However, the officially supported Distro-Versions are terribly outdated (e.g. Fedora 28, Ubuntu 18). For instance, Ubuntu 18.04 LTS has only `r-base 3.4.4-1` in its official repos.

**Comment by ronblum** [comment]
@dagdrommer We support Ubuntu 20, as well; the page is missing a plus sign—it should say "Ubuntu 18+". I'll follow up on that. For R, [we provide binaries](https://docs.rstudio.com/resources/install-r/)s that you can install at https://docs.rstudio.com/resources/install-r/. 

I can't make any claims about Arch, though, since we don't support or certify on it. But hopefully this helps!

**Comment by dagdrommer** [comment]
Thank you very much @ronblum for your immediate answer.

I'll wait now for Ubuntu 22 LTS and then make the switch on my work PC. However until then I have good news for the Arch-Community here. The flickering disappears when you compile R-Studio from source (or with the AUR package `rstudio-desktop`). Unfortunately the binary AUR package causes the trouble.

**Comment by matguidi** [comment]
This is probably due to a bug in mesa 21.3: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731. Hopefully it will get fixed soon. In the meantime, downgrading to mesa 21.2 solves the issue.

**Comment by bshor** [comment]
Great catch @matguidi. Looks like it is specifically about Intel GPUs, and it looks like a fix is inbound soon for us.
