### ISSUE TITLE
Problem with identify() in RStudio, works fine in RGui (Again)

### ISSUE THREAD

**Issue by Mirror-fish** [rstudio/rstudio#10193]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : windows 11
    R Version       : 4.0.2

### Steps to reproduce the problem

plot(speed ~ dist , data = cars)
with(cars,
     identify(speed ~ dist, labels=rownames(cars), n=1))

### Describe the problem in detail

Same as the issue in #3162 
It works well in RGui with the same code.

### Describe the behavior you expected

I expect it to label the points with the rownames (or anything else one might choose).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Mirror-fish** [comment]
@ronblum yes, totally the same as #3162 .

**Comment by Mirror-fish** [comment]
@bweidel Thank you! It works!
And @ronblum , could please notice this issue again? I think @bweidel find the reason that triggers this problem.

**Comment by ronblum** [comment]
Reopening! It looks like the numbers being reported are incorrect starting at a certain value. But I'm also seeing this in R, outside of RStudio, with R 4.3.0 on MacOS 13.4. What are you seeing?

**Comment by bweidel** [comment]
The Error I was getting was : Error: "warning: no point within 0.25 inches".  If by chance I clicked far off my plot it would sometimes return a point value, which I think was due to the different zoom levels. 

I tried a host of different (older) R and Rstudio versions , we tried it on all different computers, but not Macs I guess.   This issue was maddening for years and turns out it was a zoom issue.

**Comment by ronblum** [comment]
So a few things:
1. I can definitely reproduce what you're seeing on Windows, including that it works at zoom of 100%.
2. This occurs on MacOS even at zoom of 100%.
3. I was misreading the numbers returned when successfully clicking on some of the points, so ignore my comment above.
