### ISSUE TITLE
debugger is often launched in mostly-minimized state

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10191]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2021.9.1.372
    OS Version      : macOS Monterey 12.0.1
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

Unfortunately, I don't have a solid reproducible example for this, but I see it fairly often when the RStudio debugger activates.

### Describe the problem in detail

The debugger call stack is "mostly" minimized; e.g. see here:

<img width="802" alt="Screen Shot 2021-12-06 at 3 41 44 PM" src="https://user-images.githubusercontent.com/1976582/144940192-f2f52c89-0b9b-4043-ae51-81c182bb5453.png">

You can barely tell, but the debugger callstack is displayed below the solid line near the bottom of the pane. After clicking to drag and expand that window:

<img width="802" alt="Screen Shot 2021-12-06 at 3 43 40 PM" src="https://user-images.githubusercontent.com/1976582/144940236-198db172-d65c-4622-b37d-02bb48977335.png">

### Describe the behavior you expected

The traceback pane should have a minimum height when displayed.

**Comment by gtritchie** [comment]
I did a variety of manual testing where the debugger was invoked, and in all cases the traceback area was visible. This was with daily build 2022.06.0-daily+239 on MacOS 12.3.
