### ISSUE TITLE
session process supervisor should require callbacks run on main thread by default

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10192]
Distilled from a conversation with @jjallaire and @jeffvroom.

In general, code within the R session assumes it is running on the main thread; however, some recent changes to allow for handling of offline RPC requests have led to some cases where that same code is executed on a background thread. One example of this is child processes; if the main thread is busy, the background thread might run process callbacks; this is something that should be opt-in rather than opt-out.

We have a process supervisor singleton used by the session here:

https://github.com/rstudio/rstudio/blob/da714bd16c03755efc8ac1856e9f6e8a5484c3ae/src/cpp/session/SessionModuleContext.cpp#L2353-L2357

We should provide a mechanism for constructing that in a way that assumes (by default) callbacks will run on the main thread, but with the ability to override on a case-by-case basis if appropriate.

**Comment by jeffvroom** [comment]
This will be an easy thing to add to another issue I have for PT.

**Comment by jeffvroom** [comment]
@jjallaire and @kevinushey - when I changed the default value of callbacksRequireMainThread to false, it caused the runProgram call in rserver of rserver-acls to hang - and led to [this bug](https://github.com/rstudio/rstudio-pro/issues/3202). The code that calls runProgram to start rserver-acls uses its own ProcessSupervisor, and AsyncChildProcess and requires processSupervisor.poll() to be made for it to process I/O.  In this case, it poll() is called in a scheduled thread and not the "main thread" of rserver.  I'll create a PR that sets this flag to false for all uses of AsyncChildProcess in rserver, but let me know if you think we should handle this some other way. I could see adding an "enforceMainThread" global flag that is only true for rsession and then just only doing this test there so we don't change the default behavior for our APIs.

**Comment by kevinushey** [comment]
Your proposed solution sounds like the right way forward to me.

> I could see adding an "enforceMainThread" global flag that is only true for rsession and then just only doing this test there so we don't change the default behavior for our APIs.

I still think this should probably be done on a case-by-case, since (in theory) other processes not using R might not to be thread-safe by default. (unless I might be misunderstanding your proposal?)

**Comment by jeffvroom** [comment]
Thanks, yeah I agree. I'll redo that PR so there's a new method: `enforceMainThreadScheduling(true/false)` where the default is 'false'. In SessionMain, where we currently call initializeMainThreadId(..) we'll also call enforceMainThreadScheduling(true). The new test we added this release in poll() will only skip the poll if both enforceMainThreadScheduling and callbacksRequireMainThread are true.

**Comment by jeffvroom** [comment]
That PR is ready for review with this change. Thanks Kevin!  

https://github.com/rstudio/rstudio-pro/pull/3207
