### ISSUE TITLE
Consider formatting and location of toggle between visual and source mode

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10195]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.01.0-daily+290
    OS Version      : Multiple
    R Version       : 4.1.x

### Steps to reproduce the problem

Open an R Markdown file

### Describe the problem in detail

The toggle button between the visual editor and source editor is missing.

### Describe the behavior you expected

Reintroduce the toggle button.

Note that the shortcuts work, as well as the Command Palette. This is a regression (it worked in previous Prairie Trillium builds).

**Comment by kevinushey** [comment]
Those buttons were moved and should now be visible on the sub-toolbar just below:

<img width="471" alt="Screen Shot 2021-12-07 at 11 39 10 AM" src="https://user-images.githubusercontent.com/1976582/145094980-ce299f8c-1ca7-477b-b7c3-91cbe5d9e326.png">

Are you seeing those buttons?

**Comment by ronblum** [comment]
Ah! Yes, I see that. I didn't realize that was meant to replace the button. Thanks!

There's a discrepancy between what's a currently selected file and what's the currently selected editor mode. For files, light gray = selected, dark gray = unselected. For the editor mode, light gray = unselected, dark gray = selected. This is a bit confusing. We can repurpose this non-issue for this, or I can open a separate issue. But I think these should be consistent.

**Comment by kevinushey** [comment]
That's a good point, especially since that's what we do for "selected" or "active" icons in the Visual Editor toolbar:

<img width="803" alt="Screen Shot 2021-12-07 at 12 28 11 PM" src="https://user-images.githubusercontent.com/1976582/145101402-476e8445-1a83-48e7-a766-8c4f41024bdb.png">

I also think it's worth considering whether we could collapse the two toolbars into a single toolbar...

**Comment by mikebessuille** [comment]
For consideration to improve in PT.  I agree we need consistency of selection colours, and I don't personally like the 2nd row toolbar.

**Comment by mikebessuille** [comment]
@jjallaire  i know you're already addressing this with a new design per https://rstudio.slack.com/archives/C0155CA4L2W/p1638909514025300.   This issue identifies the inconsistency in selection colours that you might want to consider.

**Comment by mikebessuille** [comment]
@ronblum, JJ is done with changes in this area.

**Comment by ronblum** [comment]
Verified and looks good, checking a couple of browsers, too:
- RStudio Desktop 2022.02.0+364 on MacOS 12.1
- RStudio Server 2022.02.0+364 on Ubuntu 20.04.3 via Chrome on MacOS 12.1
- RStudio Server 2022.02.0+364 on Red Hat 8.5 via Safari on MacOS 12.1

It might be valuable to include an automated test that the toggle works, if possible, so I'm leaving this open for the moment.
