### ISSUE TITLE
*Internal Server Error* message after ?`/`

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#10202]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2021.09.0 Build 351, "Ghost Orchid" Release (077589bc, 2021-09-20) for Ubuntu Bionic
    OS Version      :  Arch Linux x86_64-pc-linux-gnu (64-bit)
    R Version       :  4.1.2 (2021-11-01)

### Steps to reproduce the problem

1. Create a new R project, an R package named "dummy"
2. Build & install the package with Ctrl+Shift+B
3. Now load with `devtools::load_all(".")` or Ctrl+Shift+L
4. Now attempt to open the help page for the division operator `/` with `` ?`/` ``.
5. Instead of getting the help page on Arithmetic Operators I get an *Internal Server Error* message on the Help pane.

### Describe the problem in detail

After following the steps described above, after issuing the command `` ?`/` `` I get this:

![snap](https://user-images.githubusercontent.com/19862384/145237018-4e40d426-bd9e-4c32-9f92-16b6cb6740e1.png)

### Describe the behavior you expected

I expected it to open R's base Arithmetic Operators help page. It works fine with the other arithmetic operators documented in the same page. For some strange reason, when it comes to the division operator it tries to retrieve a help page from the package --- inferred from the message *Rendering development documentation for "/"*.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ramiromagno Thank you for raising this!

Note: Reproducible on MacOS 12.1 in RStudio Desktop 1.3.1093 and 2022.01.0-daily+290.

**Comment by kevinushey** [comment]
This can be reproduced outside of RStudio -- it is a bug in the `devtools` package.

```
> devtools::load_all()
ℹ Loading renv
> ?"/"
ℹ Rendering development documentation for "/"
Warning in file(con, "r") :
  'raw = FALSE' but '/Users/kevin/r/pkg/renv/man//' is not a regular file
Warning in file(con, "r") :
  cannot open file '/Users/kevin/r/pkg/renv/man//': it is a directory
Error in file(con, "r") : cannot open the connection
```

Can you please file this at https://github.com/r-lib/devtools/issues?

**Comment by ramiromagno** [comment]
Sure, I'll refer to this one.
