### ISSUE TITLE
Make tab/pane names localizable

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10208]
The tab/pane names are currently hardcoded. Investigate how to make these localizable (there may be some non-obvious assumptions in the code that the names are fixed that I want to check on).

Specific things to check include:

PaneManager -> "Console"
BuildPane -> "Build"
BuildTab -> "Build"
ConnectionsTab -> "Connections"
ConnectionsPane -> "Connections"
ConsolePane -> "Console"
FilesTab -> "Files"
Help -> "Help"
HelpPane -> "Help"
HelpTab -> "Help"
HistoryTab -> "History"
HistoryPane -> "History"
ViewerTab -> "Viewer"
ViewerPane -> "Viewer"
TutorialTab -> "Tutorial"
TutorialPane -> "Tutorial"
TerminalTabPresenter -> ...
TerminalTab -> "Terminal"
TerminalPane -> "Terminal"
Presentation2Tab -> "Presentation"
Presentation2Pane -> "Presentation"
PresentationPane -> "Presentation"
PresentationFrame -> "Presentation Frame"
PlotsTab -> "Plots"
PlotsPane -> "Plots"
PackagesTab -> "Packages"
PackagesPane -> "Packages"
TestsOutputTab -> "Tests"
TestsOutputPresenter -> "Tests"
SourceCppOutputTab -> "Source Cpp"
SourceCppOutputPane -> "Source Cpp"
RSConnectDeployOutputTab -> "Deploy"
RSConnectDeployOutputPresenter -> "Deploy"
RenderRmdOutputTab -> "Render"
MarkersOutputTab -> "Markers"
MarkersOutputPane -> "Markers"
FindOutputTab -> "Find in Files"
FindOutputPane -> "Find Results"
DataOutputTab -> "SQL Results"
DataOutputPane -> "Data Output"
CompilePdfOutputTab -> "Compile PDF"
CompilePdfOutputPresenter -> "Compile PDF"
LauncherJobsPane -> "Launcher"
JobsPane -> "Jobs"
JobsTab -> "Jobs"
LauncherJobsTab -> "Launcher"
EnvironmentPane -> "Environment"
EnvironmentTab -> "Environment"

**Comment by rohank07** [comment]
@gtritchie wanted to follow up on this.

**Comment by gtritchie** [comment]
@rohank07 missed your ping on this, sorry. Have added to the Spotted Wakerobin milestone.
