### ISSUE TITLE
Localize keyboard shortcuts

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10217]
The keyboard shortcuts in Commands.cmd.xml are not currently localizable. They should be. There is WIP on this already, but may not get it done right away to opening this to track.

**Comment by skyeturriff** [comment]
Update:

https://github.com/rstudio/rstudio/issues/9083#issuecomment-988317780
https://github.com/StatCan/daaas/issues/760

**Comment by gtritchie** [comment]
This work was completed some time ago.
