### ISSUE TITLE
Fold/unfold only chunks, not sections

### ISSUE THREAD

**Issue by stevepowell99** [rstudio/rstudio#10226]
When writing a longer document, focusing on the non-code material, it is very convenient to have the code chunks folded but the rest of the sections unfolded. However it seems almost impossible to work like this, because the code fold and unfolding commands treat sections and chunks the same. You either have to fold everything and unfold every section and subsection manually, or unfold everything and fold each chunk manually. You can use multiple cursors to select all headings (or all chunk headers) but the fold/unfold shortcuts don't work on multiple selections.
Best I can do is define a keyboard shortcut for Go To Next Chunk and then repeat this shortcut + AltL multiple times.

**Comment by ronblum** [comment]
@stevepowell99 Thank you for raising this!

**Comment by stevepowell99** [comment]
For those interested, I wrote an AutoHotKey script to fold up to 90 chunks in a document and assigned it to a keyboard shortcut. The details depend on your shortcut keys for Rstudio, which in my case are Alt; for Next Chunk and AltL for folding. 
```
!k::  ;repeat next chunk then codefold for rstudio
Loop, 90
{
Send !`;
Sleep, 10
Send !l
Sleep, 10
}
return

```

**Comment by Alex123-droid** [comment]
In seems very interesting, I would like to use it

It gaves me this error though:

`Error: unexpected ';' in "!k::  ;"`

Do you happen to know why?

**Comment by Alex123-droid** [comment]
Oh My

I was so happy to find the fix that It appears I didn't want to see it properly. You are right

Thank you
