### ISSUE TITLE
Global Options "General" tab incorrectly labeled as "Graphics"

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10223]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : RStudio-2022.01.0-daily+275
    OS Version      : macOS 12.0.1
    R Version       : 4.1.2

### Steps to reproduce the problem
- open General
- see this starting with PR build 275 (was ok with build 271, there were no Mac builds of 272, 273, 274 to try)

![Screen Shot 2021-12-09 at 14 15 34](https://user-images.githubusercontent.com/10569626/145485357-745c2f77-bd9c-4ebc-9ed3-2943352cd5fe.png)

### Describe the problem in detail

First tab is labeled as "Graphics".

### Describe the behavior you expected

First tab labeled "General" as seen here in build 271.

![Screen Shot 2021-12-09 at 14 23 04](https://user-images.githubusercontent.com/10569626/145485472-a103b8e7-9a8d-4ff8-9726-ebd7e023ef10.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
Verified in 2022.02.0-daily-316 this is showing correctly. No tests were added as this already is covered and showed failing as of build 2022.01.0-daily+275. Closing issue.
