### ISSUE TITLE
Header 1 formatting option is no longer visible in Block Format dropdown menu in Visual R Markdown toolbar

### ISSUE THREAD

**Issue by cm421** [rstudio/rstudio#10228]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.01.0-daily+300.pro1 and 2022.01.0-daily+295.pro1
    OS Version      : Ubuntu 20.04 docker container, accessing from Firefox on MacOS 12
    R Version       : 4.1.2

### Steps to reproduce the problem
In a R Markdown document, in visual mode, `Header 1` is not a visible option in the Block Format dropdown menu:
![Screen Shot 2021-12-10 at 11 17 39 AM](https://user-images.githubusercontent.com/56326543/145624704-9c57e2cd-17e8-470e-864d-0a384c2eef1f.png)

It's in the page source, but greyed out.
![Screen Shot 2021-12-10 at 11 34 26 AM](https://user-images.githubusercontent.com/56326543/145624665-08f765ad-5e0a-4907-a117-7f45f82004b7.png)

Automated selenium tests are unable to find the `Header 1` option when searching for the id `rstudio_label_heading_1_command`, and the shortcut `⌥⌘1` does not work

### Describe the behavior you expected
The `Header 1` format option should be visible, clickable, and accessible via its keyboard shortcut.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Just confirming that it works correctly in RStudio Desktop 2021.09.1+372 Ghost Orchid.

**Comment by jmcphers** [comment]
It looks like this was removed intentionally. https://github.com/rstudio/rstudio/commit/898299b58ff04e033b1cb33c7f3c46a6504cbb01#diff-e6b80021dffd9dc8f868e302235bc49936473385d419014fae99cc09c6234504

**Comment by cm421** [comment]
Interesting. If this is expected behavior I can update the automated test to expect this and close this issue

**Comment by jmcphers** [comment]
I'm not totally sure if it's expected or not, but it even though it was intentionally removed the resulting UI doesn't look right to me. I've opened a PR and asked JJ to review it.

**Comment by jmcphers** [comment]
JJ has confirmed that this was a fully intentional change, made to reduce the headaches caused by using Level 1 headings in Pandoc documents. https://github.com/rstudio/rstudio/pull/10241
