### ISSUE TITLE
make it easier to report bugs in the RStudio IDE

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10221]
The GitHub issue template has a large number of fields which normally need to be filled out by hand (e.g. the RStudio version, the R version, and so on). It'd be useful to have a tool (both internally, and for users) for reporting of bugs.

**Comment by AndrewMcClain** [comment]
On Ubuntu 20.04.3 LTS I installed `rstudio-2022.02.0-daily-318-amd64.deb` and when invoking `.rs.bugReport()` I receive the following error. Is there a missing dependency or something?

`Error: Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.`

![Screenshot from 2021-12-14 14-11-57.png](https://codetreeusercontent.s3.amazonaws.com/uploads/b590ad51-7393-4bbc-91cd-d19aa0eb1412/Screenshot+from+2021-12-14+14-11-57.png)

**Comment by kevinushey** [comment]
Thanks for catching that -- I should fix this to use RStudio Desktop's internal tools for reading the clipboard.

**Comment by AndrewMcClain** [comment]
Confirmed working in desktop and server as of 2022.02.0-daily+326
