### ISSUE TITLE
R Markdown: some chunks disappeared - no errors, works when I run the chunks

### ISSUE THREAD

**Issue by erdnaxel** [rstudio/rstudio#10233]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Windows 10 Enterprise, 10.0.18363
    R Version       : 4.0.0

### Steps to reproduce the problem
Problem arose without any changes to my code and only affects some parts of the report, with very similar parts elsewhere running as expected. I don't know how I could reproduce it.

### Describe the problem in detail
I have an RMarkdown report that I've been running every week for months. It's html, using flex_dashboard. 

After weeks of running with no issues, the output for some tabs doesn't appear anymore, without any changes in the code. When I run the chunks individually, they produce the expected output. I don't get any errors when knitting and all the info about the individual chunks is accurate. I've triple checked that Eval=TRUE.

Those chunks use datatable(), but I have other tabs with datatable outputs in the same report that run as expected.

In the faulty tabs, the text between chunks renders properly. For one of the tables, the columns names appear, but not the content of the table itself.

### Describe the behavior you expected

I expected the chunks to be part of the output, as they have been for months.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ can't - managed by IT] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@erdnaxel Thank you for raising the issue. A couple of things:
1) Can you provide an example of code that results in the issue?
2) Since you're unable to install the latest version, are you able to use the installer-less zip file under the "Zip/Tarballs" section, near the bottom of [the download page?](https://www.rstudio.com/products/rstudio/download/#download)
