### ISSUE TITLE
Typing a tab when within Roxygen comments

### ISSUE THREAD

**Issue by oduilln** [rstudio/rstudio#10235]
When typing the tab key within a roxygen comment, autocomplete suggests some things:

<img width="266" alt="Screenshot 2021-12-12 at 22 38 12" src="https://user-images.githubusercontent.com/33176127/145732404-7964caef-d3fa-4ffd-a8e6-29c6ab661e1a.png">
<img width="213" alt="Screenshot 2021-12-12 at 22 38 20" src="https://user-images.githubusercontent.com/33176127/145732406-ba4639f2-5fc8-4aee-8878-841f52b0b286.png">

Hitting tab again inserts the top suggestion. Is there any way I can close the autocomplete menu and actually type a tab?
I like to use roxygen comments for long comments because the IDE automatically inserts #' when I hit enter on a new line.

I would like a way to type the tab without disabling "use tab for autocompletion" because I use that feature, I would like a quick way typing of a tab, like I hit ESC to close the menu and hit tab again, so some keyboard shortcut like shift + tab (I don't know if that's a good binding but just an example) to force insert a tab and ignore autocomplete

**Comment by kevinushey** [comment]
I agree it's probably over-aggressive to autocomplete when pressing Tab in this context -- we should probably require that an `@` is just before the cursor.

Besides, we already automatically pop up completions after typing `@` so Tab as a completion key here has relatively little added utility.

**Comment by colearendt** [comment]
Agree!
