### ISSUE TITLE
Any Rstudio Version > 1.1.463 Extremely slow (Rnotebook) on corporate laptop

### ISSUE THREAD

**Issue by synthds** [rstudio/rstudio#10240]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.01
    OS Version      :  Windows 10 Enterprise: 11th gen Intel(R) Core i5-1145G7
    R Version       : 4.1.2

### Steps to reproduce the problem
Utilizing any Rstudio version > 1.1.463 causes extreme slowdowns in Rnotebook performance.  As I am on a corporate connection, I have installed both Rstudio and R on local drives. After loading in tidyverse, see the below code and execution times. Interestingly enough, the same code performs fast on console, or on VScode rmarkdown much faster. I am not having these issues on my personal machine with the exact same version of R and Rstudio, only work computer. Just to reiterate, if I download Rstudio 1.1.463, I do not have these speed issues. Rstudio performs exactly the same as any other machine I use it on. Also, when I click on "run chunk" there is often a lag between clicking and actual execution that I experience on no other machine or lower versions of Rstudio. Using the below YAML to send my output to console as opposed to inline completely removes the problem as well

```
---
output: html_document
editor_options: 
  chunk_output_type: console
---
```

### Describe the problem in detail

Code executes extremely slow when output is displayed inline on work laptop (connected to corporate network). This
slowdown can be significant for code that is trivial on other machines using the same installations.

```
timein <- proc.time()
tibble(
  x = 1:5000000,
  y = 1,
  z = x*0.5
)
timeout <- proc.time() - timein
print(timeout)
```

Rstudio rnotebook timing:
```
user system elapsed
0.16 0.05 2.81
```
Rstudio Console timing:
```
user system elapsed
0.13 0.02 0.16
```
Vscode rmd chunk timing:
```
user system elapsed
0.16 0.01 0.22
```

### Describe the behavior you expected
Looking to have Rnotebooks to execute chunks in similar speed.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@synthds Thank you for raising the issue! Can you also include a diagnostics report? You can do so with <kbd>Help Menu -> Diagnostics -> Write Diagnostics Report</kbd> or more information is available at https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

**Comment by synthds** [comment]
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7721252/diagnostics-report.txt)

See the attached. Thank you!
