### ISSUE TITLE
Reflow comment should not break up inline r code fragments

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rstudio#10244]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 build 351
    OS Version      :  MacOS
    R Version       : 4.2.0

### Steps to reproduce the problem

Create an rmarkdown document like this:

```
---
title: "Untitled"
author: "Author"
output: html_document
---

Lorem ipsum dolor sit amet, nunc amet maecenas vel sit diam mi ligula `r 2+2+2+2+2+2+2+2+2+2` molestie justo. `Sed nostra aenean. Sed duis etiam ac sed maximus fusce, mi finibus justo. Luctus tristique sed risus mauris nunc, sit. Suscipit, proin. Pellentesque, malesuada in ut ante leo! Nullam lectus ut quisque diam in imperdiet netus. 
```

where the paragraph is a single line with no breaks.

Select the paragraph and hit "reflow" (with max width set to 80).

### Describe the problem in detail

The paragraph will be reflowed to max width 80.
The inline R fragment will be broken over two lines.
This can be hard to spot, especially if you reflow a large paragraph. 
It then causes errors when knitting.

### Describe the behavior you expected

Any of the below would work:

* The R fragment should be kept on one line.
* knitr should parse inline R fragments that span newlines.
* Workaround: highlight inline R fragments that span newlines, e.g. like a code error.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@hughjonesd Thank you for raising this! I can reproduce this in
- RStudio Desktop 1.2.5042 on MacOS 12.1
- RStudio Desktop 2022.09.0-daily-310 on MacOS 12.1
- RStudio Server 2022.09.0-daily-318 on Ubuntu 20.04.2 via Safari on MacOS 12.1

Comparison point: When adding a bunch of spaces so that the reflowed line places the inline code on the same line, knitting works as expected:
```
Lorem ipsum dolor sit amet, nunc amet maecenas vel sit diam mi ligula                 `r 2+2+2+2+2+2+2+2+2+2` molestie justo. `Sed nostra aenean. Sed duis etiam ac sed maximus fusce, mi finibus justo. Luctus tristique sed risus mauris nunc, sit. Suscipit, proin. Pellentesque, malesuada in ut ante leo! Nullam lectus ut quisque diam in imperdiet netus. 
```

**Comment by colearendt** [comment]
Agree!
