### ISSUE TITLE
RStudio Freezes after Restart R

### ISSUE THREAD

**Issue by arnyeinstein** [rstudio/rstudio#10243]
Hi

RStudio freezes after a restart of R. This happens irregularly after two or more restarts of R. 
Often it is impossible to close RStudio even by using the Taskmanager. 
Unfortunately, I couldn't reproduce this with an example script. 

Renger 
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7709271/diagnostics-report.txt)

**Comment by ronblum** [comment]
@arnyeinstein Thank you for raising this!
1) Does this happen after doing anything in particular? And by restart of R, do you mean going to <kbd>Session -> Restart R</kbd>?
2) Based on the diagnostics report, can you confirm that this is the environment you're working with?

###
    RStudio Edition : Desktop
    RStudio Version : 2021.09.1+372
    OS Version      : Windows 10
    R Version       : 4.1.2

**Comment by arnyeinstein** [comment]
Hi
This is happening almost every day I work with RStudio at least once. The environment is still the same.
Renger

**Comment by jmcphers** [comment]
> 2021-12-14T06:26:09.540953Z [rsession-renge] ERROR system error 10053 (An established connection was aborted by the software in your host machine) [request-uri: /events/get_events]; 

This usually means that security or antivirus software is severing the connection between the UI and the R session (which is plain old HTTP). Are you running any software like this? If so, can you add exclusions for rstudio.exe and rsession.exe?
