### ISSUE TITLE
attempting to build package without testthat installed produces error in console

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10252]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.1.0.303
    OS Version      : macOS Monterey 12.1
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

1. Create a new R Package project,
2. Ensure `testthat` is uninstalled (`remove.packages("testthat")`),
3. Try to build the package (`Cmd + Shift + B`).

### Describe the problem in detail

An error is printed to the console:

```
Error in packageVersion(pkg) : there is no package called 'testthat'
```

### Describe the behavior you expected

No error.

**Comment by ronblum** [comment]
Verified using the above steps in
- RStudio Desktop 2022.02.0-daily-335
- RStudio Server 2022.02.0-daily-331

Note: Checked in an earlier version that I could reproduce the problem.
