### ISSUE TITLE
Cannot launch RStudio with the UCRT R-devel on Windows

### ISSUE THREAD

**Issue by yutannihilation** [rstudio/rstudio#10255]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2021.09.1+372, "Ghost Orchid" (8b9ced18, 2021-11-08) for Windows
    OS Version      : Windows 10
    R Version       : R-devel

### Steps to reproduce the problem

1. Install R-devel from https://cran.r-project.org/bin/windows/base/rdevel.html
2. Launch RStudio

### Describe the problem in detail

As the log is about something related to file paths, I guess this is somehow because RStudio doesn't assume the encoding can be UTF-8 on Windows? (Note that the system encoding is not UTF-8).

![image](https://user-images.githubusercontent.com/1978793/146394838-74fa7284-048b-469c-9955-a38b3c75b753.png)

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

(It seems Diagnostics Report cannot be generated even from the command line)

**Comment by jmcphers** [comment]
UCRT support for R-devel is available in RStudio's own development branch, currently 2022.02. Does one of these builds work for you?

https://dailies.rstudio.com/

**Comment by yutannihilation** [comment]
I didn't notice it, thanks. Confirmed the daily build works fine with UCRT R-devel! 🎉

**Comment by jmcphers** [comment]
Great, glad to hear it! (h/t @kevinushey who made the magic happen)

**Comment by yutannihilation** [comment]
Thank you @kevinushey!!! I'll probably use R-devel + RStudio daily as my main environment. Please feel free to mention me when you need a Windows tester on CJK locale :)
