### ISSUE TITLE
Disabling "Restore .RData" not working

### ISSUE THREAD

**Issue by Hoeze** [rstudio/rstudio#10268]
### System details

    RStudio Edition : RStudio workbench
    RStudio Version : 1.4.1717-3
    OS Version      : Centos 8
    R Version       : 4.1.0

### Steps to reproduce the problem
1) Disable storing .RData:
    ![image](https://user-images.githubusercontent.com/1200058/146755268-3dbf57e4-8ec0-4375-b3a9-668452834922.png)
2) Restart your session

### Describe the problem in detail
When restarting my session, I keep waiting for >10mins when my previous session was large (~100GB)

### Describe the behavior you expected
R starts a fresh session without loading unnnecessary stuff from old sessions

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Did you disable it in your project options (as opposed to global options)?
