### ISSUE TITLE
Custom roxygen tags in autocomlete

### ISSUE THREAD

**Issue by mikldk** [rstudio/rstudio#10266]
Autocomplete is available for writing `roxygen2` code in RStudio. This is (I guess) made possible via [this code](https://github.com/rstudio/rstudio/blob/7ce19c54507e53de8859502605774a825cced146/src/cpp/session/modules/SessionRCompletions.R#L221).

My package [`roxytest`](https://github.com/mikldk/roxytest) introduces two new tags, `@tests` and `@testexamples` (see [here](https://github.com/mikldk/roxytest)).

Is it somehow possible to add custom tags into RStudio's autocomlete system?

(This is related to mikldk/roxytest#23 by @shahronak47.)

**Comment by mikldk** [comment]
I hope indeed that this will be implemented at some point, and thus I would like to keep this issue open.

**Comment by kevinushey** [comment]
Right now, the set of known roxygen tags is hard-coded here:

https://github.com/rstudio/rstudio/blob/f72551b40e7a0b53a4950a652356ce192807536a/src/cpp/session/modules/SessionRCompletions.R#L160-L217

We could consider reading tags from other packages loaded in the session, though. Is there a way that RStudio could ask `roxytest` what Roxygen tags it is defining / exporting?

**Comment by mikldk** [comment]
@kevinushey Yes, indeed: I submitted a PR where I added the two tags: rstudio/rstudio#11470. It is not a beautiful way of solving this, but on the other hand - if only a few packages define custom tags - it may not hurt doing it this way.

Doing what you suggest requires agreeing on the packages providing e.g. a special function (or declaring a tag in the `DESCRIPTION`), but RStudio would have to go through all packages everything. It may not take that long, but it would often (too often IMO) be in vein.

**Comment by mikldk** [comment]
@kevinushey I think we continue discussing it here rather than in rstudio/rstudio#11470. My suggestion there was simply to edit the hard-coded list:
https://github.com/rstudio/rstudio/blob/f72551b40e7a0b53a4950a652356ce192807536a/src/cpp/session/modules/SessionRCompletions.R#L160-L217
I.e., by adding the two tags:
```
      # Two tags from roxytest (https://github.com/mikldk/roxytest/).
      # They must be here as later it is checked whether
      #    if (.rs.acContextTypes$ROXYGEN %in% type)
      # and the roxytest tags are used in roxygen context
      "@tests ",
      "@testexamples "
```
This approach was not ideal as noted in rstudio/rstudio#11470. Instead, @kevinushey "prefer a solution that queried packages loaded in the current session for the tags they support". Below I will list a few variations and give a few pros/cons from my point of view. Both rely on that both `roxygen2` and the package with new tags needs to be installed for auto-completion to work. 

Suggestions:

1. Query loaded packages in the current session for the tags they support (e.g. via [`methods("roxy_tag_parse")`](https://roxygen2.r-lib.org/reference/roxy_tag.html) as demonstrated below) [@kevinushey]
2. Use information in the `DESCRIPTION` file (e.g. the `Roxygen` `roclets` list: [example](https://github.com/mikldk/roxytestdemo/blob/master/DESCRIPTION)) - here the package `roxytest` is found with extra roclets. 

With **1** you need the packages to be loaded in the session, bot that is not necessarily natural for neither `roxygen2` nor `roxytest` to be loaded in the session for actually using the packages for package development (although they of course can be). With **2** it does not matter whether they are loaded or not. Plus you only need to query the packages that actually provide roclets and not all the other packages that may be loaded (potentially many).

For both solutions we do something like this behind the scenes:

``` r
methods("roxy_tag_parse")
#> Error in .S3methods(generic.function, class, envir): no function 'roxy_tag_parse' is visible

library(roxygen2)
tags <- methods("roxy_tag_parse")
head(tags)
#> [1] "roxy_tag_parse.default"             "roxy_tag_parse.roxy_tag_aliases"   
#> [3] "roxy_tag_parse.roxy_tag_author"     "roxy_tag_parse.roxy_tag_backref"   
#> [5] "roxy_tag_parse.roxy_tag_concept"    "roxy_tag_parse.roxy_tag_describeIn"
length(tags)
#> [1] 58


library(roxytest)
tags2 <- methods("roxy_tag_parse")
length(tags2)
#> [1] 60

new_tags <- setdiff(tags2, tags)

new_tags_short <- gsub("roxy_tag_parse.roxy_tag_", "", new_tags, fixed = TRUE)
new_tags_short
#> [1] "testexamples" "tests"
```

And for **2** something like this (the regex is quick and dirty, more thought should go into it):

``` r
# remotes::install_github('mikldk/roxytestdemo')
roclets <- utils::packageDescription("roxytestdemo")$Roxygen
if (!is.null(roclets)) {
  roclets <- gsub(".*[^A-Za-z](.+)::.*", "\\1", roclets)
  roclets
}
#> [1] "roxytest"
```

What do you think, @kevinushey?

**Comment by kevinushey** [comment]
I like the idea in (2), where some metadata is included in the installed package's files that RStudio could read and use to learn what roclets are supported by packages installed on the system.

We index installed packages for other reasons, e.g. when enumerating RStudio Addins and other features, so adding supported roxygen tags seems a reasonable extension.

That said, it's not clear to me how we can map these:

https://github.com/mikldk/roxytestdemo/blob/master/DESCRIPTION#L20-L24

to the set of supported roxygen tags, without attempting to load the package. Maybe there's a way to load or introspect an installed package's R code without loading the whole package?

**Comment by kevinushey** [comment]
It's possible to peek at what R objects are defined by an R package by looking at its R code index. For example:

```
> indexFile <- system.file("R/roxytest.rdx", package = "roxytest")
> index <- readRDS(indexFile)
> grep("roxy_tag_parse", names(index$variables), value = TRUE)
[1] "roxy_tag_parse.roxy_tag_testexamples" "roxy_tag_parse.roxy_tag_tests"   
```

Or, we could load the lazy-load database with something like:

```
filebase <- system.file("R/roxytest", package = "roxytest")
envir <- new.env(parent = emptyenv())
lazyLoad(filebase = filebase, envir = envir)
```

**Comment by mikldk** [comment]
@kevinushey Thanks for the input. I agree that we need to find the tags without loading the package. Either by your suggestions or by reading the `NAMESPACE` and finding `S3method(roxy_tag_parse,*)`, e.g.:
https://github.com/mikldk/roxytest/blob/master/NAMESPACE#L15-L16

``` r
nmsp <- system.file("NAMESPACE", package = "roxytest")
lns <- readLines(nmsp)
tags <- grep("S3method(roxy_tag_parse,roxy_tag_", lns, value = TRUE, fixed = TRUE)
substr(tags, nchar("S3method(roxy_tag_parse,roxy_tag_")+1L, nchar(tags)-1L)
#> [1] "testexamples" "tests"
```
Unfortunately, I do not know the RStudio infrastructure well enough to know how to get started on implementing it this way. Do you have any leads on the top of your head? Or how do you suggest to move forward?

**Comment by kevinushey** [comment]
We have some code here to handle indexing of package resources:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionPackageProvidedExtension.cpp

For an example usage, for addins:

https://github.com/rstudio/rstudio/blob/f72551b40e7a0b53a4950a652356ce192807536a/src/cpp/session/modules/SessionRAddins.cpp#L359-L373

We'd need to add a similar worker for extracting roxygen tags supported by a package.

**Comment by mikldk** [comment]
I still hope that this will get some attention (by me or others) at some point.

**Comment by mikldk** [comment]
I hope this can stay open as I think it is still relevant.

**Comment by kevinushey** [comment]
The roxygen package now includes all of the tags it defines in the installed package, e.g.

https://github.com/r-lib/roxygen2/blob/main/inst/roxygen2-tags.yml

Perhaps if packages offering their own roxygen tags did something similar, we could index those and provide those as completion candidates?

For reference: https://github.com/rstudio/rstudio/blob/750a82c78c2d32eb10e6bef5b0c34b4a30016629/src/cpp/session/modules/SessionRCompletions.R#L133

**Comment by mikldk** [comment]
Yes, that's a good idea. But how can a package notify Rstudio that it offers a `roxygen2-tags.yml` file (to avoid Rstudio traverse all install packages...)?

**Comment by kevinushey** [comment]
RStudio already does index all installed packages -- for example, this is done when populating [RStudio Addins](https://rstudio.github.io/rstudio-extensions/rstudio_addins.html) -- so RStudio could also check for the existence of a `roxygen2-tags.yml` file during that indexing process.

**Comment by kevinushey** [comment]
Which is all to say; if we decide that packages can also provide their own `roxygen2-tags.yml` file to declare the supported Roxygen tags, it should be straightforward for RStudio to support that.

**Comment by mikldk** [comment]
@kevinushey That sounds like a potential plan. I guess RStudio needs to decide whether they think it is something they wish to support. Do I need to submit an official proposal elsewhere?

**Comment by whipson** [comment]
I'd also love to see this supported.
