### ISSUE TITLE
null is not an object (evaluating 'WBh(this.d).a'

### ISSUE THREAD

**Issue by ta-scm** [rstudio/rstudio#10262]
### System details

    RStudio Edition : Server
    RStudio Version : rstudio-server-1.2.5019
    OS Version      : CentOS 7.9
    R Version       : 4.1.2

### Describe the problem in detail
Seeing this client exception TypeError in the logs:
```
rserver[33167]: CLIENT EXCEPTION (rsession-xxxxx): (TypeError) : null is not an object (evaluating 'WBh(this.d).a');|||org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java#57::previewKeyDown|||org/rstudio/studio/client/workbench/views/console/shell/Shell.java#523::onKeyDown|||com/google/gwt/event/dom/client/KeyDownEvent.java#55::dispatch|||com/google/web/bindery/event/shared/SimpleEventBus.java#173::doFire|||com/google/gwt/event/shared/HandlerManager.java#117::fireEvent|||com/google/gwt/event/shared/HandlerManager.java#117::fireEvent|||com/google/gwt/event/dom/client/DomEvent.java#110::fireNativeEvent|||https://ondemand.yyyyy.zzzzz.com/rnode/node1.yyyyy.zzzzz.com/3352/#-1::anonymous%7C%7C%7Ccom/google/gwt/core/client/impl/Impl.java#236::apply%7C%7C%7Ccom/google/gwt/core/client/impl/Impl.java#275::entry0%7C%7C%7Chttps://ondemand.yyyyy.zzzzz.com/rnode/node1.yyyyy.zzzzz.com/3352/#-1::anonymous%7C%7C%7CClient-ID: 8775f2a7-395c-490c-bd46-b3470b632e8c|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15

rserver[33167]: CLIENT EXCEPTION (rsession-xxxxx): (TypeError) : null is not an object (evaluating 'WBh(this.d).a');|||org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java#57::previewKeyDown|||org/rstudio/studio/client/workbench/views/console/shell/Shell.java#523::onKeyDown|||com/google/gwt/event/dom/client/KeyDownEvent.java#55::dispatch|||com/google/web/bindery/event/shared/SimpleEventBus.java#173::doFire|||com/google/gwt/event/shared/HandlerManager.java#117::fireEvent|||com/google/gwt/event/shared/HandlerManager.java#117::fireEvent|||com/google/gwt/event/dom/client/DomEvent.java#110::fireNativeEvent|||https://ondemand.yyyyy.zzzzz.com/rnode/node1.yyyyy.zzzzz.com/3352/#-1::anonymous%7C%7C%7Ccom/google/gwt/core/client/impl/Impl.java#236::apply%7C%7C%7Ccom/google/gwt/core/client/impl/Impl.java#275::entry0%7C%7C%7Chttps://ondemand.yyyyy.zzzzz.com/rnode/node1.yyyyy.zzzzz.com/3352/#-1::anonymous%7C%7C%7CClient-ID: 8775f2a7-395c-490c-bd46-b3470b632e8c|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
```

This is followed by 587061739 lines of this warning:
`rsession-xxxxx[54365]: WARNING rConsoleRead called in forked processs; LOGGED FROM: bool rstudio::session::console_input::rConsoleRead(const string&, bool, rstudio::r::session::RConsoleInput*) /var/lib/jenkins/workspace/IDE/open-source-pipeline/v1.2-patch/src/cpp/session/SessionConsoleInput.cpp:171
`
### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ta-scm Thank you for reporting this! Do you have a reproducible example of when this occurs? Also, has this always been an issue, or is this new, and did any change cause it?

Also, please note that RStudio Server 1.2.5019 is no longer supported. The current release is [2021.09.1+372 Ghost Orchid](https://www.rstudio.com/products/rstudio/download-server/redhat-centos/), which is available at https://www.rstudio.com/products/rstudio/download-server/redhat-centos/.
