### ISSUE TITLE
MacOS states that future versions of the app are incompatible with future versions of the OS due to Python 2

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10270]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0-daily-335
    OS Version      : MacOS 12.1
    R Version       : 4.1.1

### Steps to reproduce the problem

I'm not always to reproduce this, but this time it occurred when creating a new package.

### Describe the problem in detail

A pop-up modal appears that "the app" is incompatible with future versions of MacOS. If I click on "Learn More," I'm directed to a page about Python 2's sunsetting. I imagine this is because I have Python 2 installed, even though I don't have it selected.

<img width="249" alt="incompatible" src="https://user-images.githubusercontent.com/31009952/146948583-3b06104b-bcb9-4c43-a904-19fa4c5b9638.png">

### Describe the behavior you expected

It would be great if MacOS tolerated Python 2, but there might not be anything we can do. I'm filing this primarily so that we're aware that this is happening, especially if it's expected. For now, I'm marking this as a bug for Prairie Trillium until confirmation that this is expected.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
This should be a support article that explains why you'd get this message, and that it's because you have Python 2 installed, not because of a python 2 dependency in RStudio.

**Comment by kevinushey** [comment]
This is probably happening because we're trying to run `/usr/bin/python` or similar as part of Python discovery.

**Comment by jgutman** [comment]
Per Mac OS release notes(https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes), Python 2 installation in `/usr/bin/python` is going away entirely in Mac OS 12.3, which is why they added this deprecation notice in Mac OS 12.0.1. So I suspect this is likely a temporary issue that will only be present in Mac OS 12.0 - 12.2, and the deprecation warning should be far less common in 12.3 onwards unless the user has specifically installed Python 2 in `/usr/bin/python`, as it will no longer be installed by default

**Comment by mikebessuille** [comment]
On those grounds I think we can close this issue.

**Comment by ronblum** [comment]
[@mikebessuille you beat me to it as I was typing!]

Future note: When MacOS 12.3 is released, check to see what kind of warning or error will be present if Python2 is already installed or added.
