### ISSUE TITLE
Redirect RStudio server warnings from the R console

### ISSUE THREAD

**Issue by cboettig** [rstudio/rstudio#10282]
### System details

    RStudio Edition : Server
    RStudio Version :  1.4.1717
    OS Version      :  ubuntu linux 20.04
    R Version       :  4.1.2

### Steps to reproduce the problem

RStudio server open source edition logs numerous issues directly to the R console, such as "Warning: no memory cgroup found".  Others show up as errors (I think doing to git, such as:

```
[rsession-cboettig] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) src/cpp/r/RExec.cpp:140
2021-12-22T05:24:17.998118Z [rsession-cboettig] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXPREC* rstudio::r::options::getOption(const string&) src/cpp/r/ROptions.cpp:83
```

Usually these appear to be benign  and have no visible influence on the end user, are not related to R code execution, and appear to be the kind of thing the application ought to report to a log file / stderr.  but because they show up directly in the user's R concsole
 Rocker users are frequently concerned by these messages and report them https://github.com/rocker-org/rocker-versioned2/issues/306.  

I believe the professional edition of RStudio allows users to configure error logs (a frequently requested feature in rocker as well), but as far as I've been able to determine, the open source edition does not give us that control.  Of course it is entirely understandable if RStudio(TM) wants to reserve that feature for the enterprise product.  All the same, I think the open source version would be much improved if there was a way to at least suppress these distracting warnings and errors.

### Describe the problem in detail

Please let me know what additional detail may be useful.

### Describe the behavior you expected

Either the ability to redirect these errors to a log file, or merely suppress them from the console entirely.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Thanks for all you do!

**Comment by kevinushey** [comment]
We have an option that controls whether options are logged to stderr, here:

https://github.com/rstudio/rstudio/blob/902bf7f95b1e2ff83521f9d8e2656002272ca129/src/cpp/session/session-options.json#L67-L76

That shouldn't be on by default, although we do turn it on in our own development configurations:

https://github.com/rstudio/rstudio/blob/902bf7f95b1e2ff83521f9d8e2656002272ca129/src/cpp/conf/rsession-dev.conf#L20-L21

But I do see it being used in Rocker here:

https://github.com/rocker-org/rocker-versioned2/blob/979d7364f63fa8e7b7307c50bffbb32e8ced71cb/scripts/rsession.sh#L11

so perhaps you want to turn that off?

**Comment by kevinushey** [comment]
It looks like our log options aren't documented within the open source product, but they should still be available, e.g.

https://github.com/rstudio/rstudio/blob/902bf7f95b1e2ff83521f9d8e2656002272ca129/src/cpp/core/LogOptions.cpp#L33-L51

So the documentation in https://docs.rstudio.com/ide/server-pro/server_management/logging.html?q=log should be relevant for the open source product as well.

**Comment by cboettig** [comment]
Thanks @kevinushey , brilliant as always!

**Comment by cboettig** [comment]
hmm... I don't think https://github.com/rocker-org/rocker-versioned2/blob/979d7364f63fa8e7b7307c50bffbb32e8ced71cb/scripts/rsession.sh#L11 is actually in use, I believe the rstudio container invokes the RStudio session as `rserver`, 
https://github.com/rocker-org/rocker-versioned2/blob/053a7c0bdeba5592a1bbbfd8a36395c9bdfd69ff/scripts/install_rstudio.sh#L106

so maybe we are turning it on elsewhere?  (the rsession.sh script was an attempt to configure a container for a single-user setup, but I don't think I ever got that working)

**Comment by cboettig** [comment]
ah! probably this:
https://github.com/rocker-org/rocker-versioned2/blob/cca6e18851380133f36f4c64645c06166e0956e3/scripts/install_rstudio.sh#L122

**Comment by kevinushey** [comment]
@cboettig, does this provide you what you need in the Rocker images?

**Comment by cboettig** [comment]
Thanks @kevinushey , yup I think so, though haven't had much chance to test.  Let's close this and I'll follow up if there's any remaining issues! Thanks as always for all your help.
