### ISSUE TITLE
Rstudio startup failure on Arch-derived Linux, complaint of missing libboost library

### ISSUE THREAD

**Issue by bshor** [rstudio/rstudio#10280]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.1.+372-2
    OS Version      : Garuda Linux (Arch derivative), 5.15.10 kernel
    R Version       : 4.1.2

### Steps to reproduce the problem

Startup fails entirely.

### Describe the problem in detail

I have R and Rstudio both installed via AUR, which keeps things perfectly updated for me automatically. Today I tried to open Rstudio via the desktop icon, and no luck. Starting up via the command line gives me a problem with a missing libboost library:

`rstudio: error while loading shared libraries: libboost_thread.so.1.76.0: cannot open shared object file: No such file or directory
`

Looks like the boost-libs package, which contains this library, are [now on 1.78.0 ](https://archlinux.org/packages/extra/x86_64/boost-libs/)on Arch. This is likely the source of the problem. The issue is that I am not a good enough of a Linux hacker to know what to do at this point.

### Describe the behavior you expected

Normal startup behavior.

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report). [I have tried diagnostics, but I get the same crash]
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by grantmcdermott** [comment]
Hi @bshor 

To ask the obvious question first, have you tried updating both the boost-libs package and your RStudio build? Definitely do the latter if you got RStudio through the AUR.

It might not be related, but a couple of us Arch users recently ran into #10194. For me, downgrading my `mesa` libraries sorted everything out. As I mention further below in the thread, however, I know that Python 3.10.1 is causing all sorts of downstream issues. The Arch forum has got a bunch of examples of different applications breaking. The price of living on cutting edge :'-| 

If neither of these work, it might be worth [reverting](https://linuxconfig.org/how-to-rollback-pacman-updates-in-arch-linux) to your previous system upgrade until things stabilise.

**Comment by bshor** [comment]
Thanks @grantmcdermott for the suggestions.

Yes, I'm fully updated on both RStudio (2021.09.1.+372-2) and libboost (1.78.0-1).

I don't have the problems in that issue.

I guess I will try reverting -- never tried it before! Is that the same thing as "downgrading" ?

**Comment by bshor** [comment]
Good news is that build 382 no longer has this problem. I can go back from using daily binaries to the released versions.

**Comment by bshor** [comment]
Build 382 on a KDE desktop also failed to startup. Switching to the "rstudio-desktop" package on the chaotic-aur repository fixed me again.

**Comment by bshor** [comment]
I was ok for a while and then Build 492 failed. I switched to "rstudio-desktop-bin" and all is well again. This is to warn Arch and Arch-derivative users that one way to address problems like this is to switch between different versions of rstudio on the AUR.
