### ISSUE TITLE
syntax highlighting in css chunk (Rmd)

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#10286]
It's so nice that I can add css chunks to an Rmd to get the output I'm looking for. It would be great if the syntax highlighting would come through so that my comments are easier to discern

![image](https://user-images.githubusercontent.com/14003618/147434314-b39ecae1-3be1-4457-b9ae-d599046da67f.png)

I am expecting it to look closer to the code below. The two things to point out are:
* hex codes seem to act like comments (that blue color ☝️  is the color for comments with the Cobalt theme)
* true comments `/*... */` don't look any different

```css
/* dont show url on print */
@media print {
  a[href]:after {
    content: none !important;
  }
}

body {
  color: #333333!important;
  line-height: 1.2;
}

**Comment by ronblum** [comment]
@rjake Thank you for raising the issue! I can reproduce the issue with hex codes, but the comments show up correctly using `/*... */`. Can you provide the following information so that I can try to reproduce?

1) System details:

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

2) The theme you're using.
3) Also, if you're using RStudio Server, the browser and OS you're connecting from would be helpful.

**Comment by rjake** [comment]
Ah, I updated one computer but the one where I posted the issue was still out of date (1.4.1717). Updating to the latest version of RStudio (2021.09.1-372) fixed both issues. Thanks.
![image](https://user-images.githubusercontent.com/14003618/147582851-b2c2e880-e3d9-4b05-94c6-4e237d171dcb.png)

**Comment by ronblum** [comment]
@rjake Thank you for checking! And FWIW, for hex codes I misidentified the new correct behavior as still an issue. In other words, we're in a agreement that this now works. 😄
