### ISSUE TITLE
Rendering Large Markdown Files with Visual Markdown Editor 

### ISSUE THREAD

**Issue by zooman** [rstudio/rstudio#10285]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 351
    OS Version      : Monterey 12.1
    R Version       : 4.0.3 Bunny-Wunnies

### Steps to reproduce the problem
Open a large markdown file with code and text, ex; 9000 rows.  Then click switch to visual markdown editor.  It renders in about 15 seconds, which is okay.  

However, then try to SCROLL  down or up within the document - becomes Extremely Sluggish, as you scroll qtwebengineprocess over 100% cpu, memory seems near 500MB for the qt process.  

Try page up and page down as well, it freezes immediately for me on multiple machines we have tried.  Freezes up for about 20 seconds then it will page down.  Also notice memory grows over time, started at 400MB up to 700MB now, post just trying to scroll.  I am not running any R code, just rendering the markdown with the top right icon, "visual markdown editor" button.     Seems like CPU is getting crunched.  I am running on the INTEL 5k IMAC, also same behavior on new 16 inch Macbook pro max chip, as well as intel windows machines.  

### Describe the problem in detail
See above.   We have tested on different markdown files, only common element is over 5000 lines of code in the notebook.   Again, we are not running the code to replicate the issue.  Its just open the RMD file and press the visual editor button.  

### Describe the behavior you expected
Would like to scroll up and down in the rendered view of markdown relatively smoothly.  Its not possible right now - very sluggish on scroll.  Or page up and page down.  

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report. Would you be able to share an example document where you see this behavior, just so we can understand what kind of document is being rendered?

For what it's worth, in testing I saw somewhat similar issues but disabling real-time spellchecking appeared to alleviate the problem. You can disable it from the command palette (Tools -> Show Command Palette); look for the "Use real-time spellchecking" setting)

**Comment by zooman** [comment]
The document I would not want to share publicly, i can email it to you directly if you like.  Let me know.  

I just tried  - uncheck - "use real time spellchecking", this feels like it helps, specifically when i scroll with the mouse on the vertical scroll bar.  However, using the keyboard for some reason its still sluggish.  Ex - page up / page down, or command up arrow, command down arrow.   Let me know how to email you the file.
