### ISSUE TITLE
Make window titles reflect the active document in the window

### ISSUE THREAD

**Issue by AltfunsMA** [rstudio/rstudio#10293]
Currently, the window titles of an RStudio instance (Desktop or Server) remain rather uninformative after the minor improvement of changing from full/path/to/project_name, to project_name (#5943).

The final step should be to display the filename of the active document or object. E.g. if "loading.R", "wrangling.R" and "plotting.R" scripts and the object "cool_plot" are open; it's best to see those names in the four window titles rather than them all showing "My Project".

Most programs, even those with the ability to display multiple tabs, use this strategy as illustrated below.

![image](https://user-images.githubusercontent.com/26325512/147705879-1a3ef81e-bf57-4580-aee6-a8fd42a17351.png)

The option to toggle project name instead should be maintained for those people who are more likely to have several "loading.R" across several projects.

**Comment by nriley** [comment]
This issue is being tracked in #2427.
