### ISSUE TITLE
R Markdown Reference Guide does not exist anymore.

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#10297]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.2.0.337
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.1 (2021-08-10)

### Steps to reproduce the problem

Click on the link in the menu

![image](https://user-images.githubusercontent.com/6791940/147948966-e5f1caff-edcd-4aa3-bdae-d9b0bd8cd34e.png)

### Describe the problem in detail

https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf does not exists anymore. So link is 404

![image](https://user-images.githubusercontent.com/6791940/147949026-6aad7aee-541a-4d7e-b8fb-83de40ccaf72.png)

### Describe the behavior you expected

The menu item should be removed has it has been decided to remove this resource completely. See comment https://github.com/rstudio/rstudio/issues/9764#issuecomment-904761994 and this follows work on new R Markdown Cheatsheet: https://github.com/rstudio/cheatsheets/pull/180

I could try to make a PR to fix this and update also the other links based on the comment.

**Comment by cderv** [comment]
> I could try to make a PR to fix this and update also the other links based on the comment. 

This probably require several adjustments: 

* Removal of the link in rstudio/rstudio-web: https://github.com/rstudio/rstudio-web/blob/cf572231921a1655bc5af8ddd6f72524145bd691/web/rstudio.org/site/links/.htaccess#L46
* Removal of UI element in the IDE, probably in several places in the codebase. I may not be the better one to offer a PR. 

Someone with better knowledge of RStudio UI would do that quicker 😅 

I'll open another issue for the item to add.

**Comment by kevinushey** [comment]
@cderv, can you clarify: is there a new R Markdown reference guide that we can link to, or do you think we should remove the cheat sheet entry altogether? It's a bit unfortunate since removal of this guide implies it's no longer available for older versions of the IDE, which we cannot change.

**Comment by cderv** [comment]
For the story, I discovered the removal of this resource in https://github.com/rstudio/rmarkdown/issues/2268. After asking around, I understand it has been decided to remove it while working on the new cheatsheet (https://github.com/rstudio/cheatsheets/pull/180) - @mine-cetinkaya-rundel will know more. 

I think this happened at the same time of the migration for RStudio website and the resource seems to have been really removed (and not just unfeatured from the cheatsheet page). 
So currently, I think the resource is no more online at all - I don't have a new link of this resource to share. 

I did not thought about old IDE version so I think best move is that I reopen 
https://github.com/rstudio/rstudio.com/issues/392 so that we can effectively put back online the last version of the resource and update the redirect in the IDE, but not feature anywhere the unmaintained reference guide.

Otherwise, an other idea would be to keep this button, but link to The R Markdown Definitive Guide (https://bookdown.org/yihui/rmarkdown/) - but that is different content.

**Comment by mikebessuille** [comment]
@jgutman this looks like it's working now in SW.  Can you please verify and close?

**Comment by jgutman** [comment]
Verified in 2022.06.0-daily+104 (on Windows 11).

**Comment by cderv** [comment]
Reference guide is back online at https://github.com/rstudio/rstudio.com/commit/0a847e2f0d27218caebee2391015fe4e1a808891

Links are working now for all version I believe. thanks!
