### ISSUE TITLE
Slow `Knit` button on Windows while on a network drive

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#10298]
My wife uses RStudio (Version 2021-9-1 Build 372) on a Windows machine. She has an RStudio Project folder mounted on a network drive. In that folder are Rmds that she typically knits with the `Knit` button in RStudio. Lately, hitting `Knit` makes RStudio completely unresponsive (locking up everything including the console), and it doesn't seem to ever actually knit the document (I waited for around 5 minutes but nothing happened). It is a little odd because this seemed to work around 2-3 weeks ago, so possibly her work's network drive has gotten incredibly slow lately.

I was able to get a Log right after hitting Knit and it looked something like this:
![IMG_0576](https://user-images.githubusercontent.com/19150088/147951035-8231f633-075b-4f9e-9a3d-f038838bd001.jpg)

In response to this, I turned Autocompletions from Automatic to Manual (Tab) and tried again. Still completely locked up, but this time I get this Log:
![IMG_0577](https://user-images.githubusercontent.com/19150088/147951061-802da16a-a758-43e3-a30d-25dff0208866.jpg)

Note that I have zoomed out a few times here, this is a log over the course of around 2-3 minutes.

Is there anything else I can try to toggle to possible make this work again?

For now, I am having her run `rmarkdown::render()` manually, which seems to work fine, but kind of sucks.

I think this is somewhat related to https://github.com/rstudio/rstudio/issues/8034. I tried the offered advice of changing the refresh of the Environment pane from automatic to manual, but that didn't seem to make a difference here.

CC @kevinushey since you in particular have helped me with a few of these issues in the past

**Comment by kevinushey** [comment]
Based on the output, it's almost surely because `render_rmd` is doing something that's taking an unexpectedly long amount of time. RStudio performs the render here in a separate R process; are you able to use something like [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see what is being run by the child process performing the render, and why it's taking so long?
