### ISSUE TITLE
Visual Editor toolbar menu items show up in Source mode after toggling outline

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10306]
### System details

    RStudio Edition : 2022.2.0.330
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.1
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

First, note that this issue seems to only reproduce if a document is opened in Source mode, without first toggling to Visual mode. Toggling from Visual mode back to Source mode seems to cause this issue to no longer occur.

1. Open an R Markdown document in Source mode.
2. Click the "Outline" button to toggle the document outline.

### Describe the problem in detail

The visual editor toolbar menu items are displayed:

<img width="676" alt="Screen Shot 2022-01-04 at 12 16 24 PM" src="https://user-images.githubusercontent.com/1976582/148118453-9691705e-8b72-4368-9bf3-684849e8c143.png">

### Describe the behavior you expected

These menu items should only ever display in visual mode.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20.6.0 (64-bit)
Running under: macOS Monterey 12.1

Matrix products: default
LAPACK: /opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.1.2    fastmap_1.1.0     cli_3.1.0         htmltools_0.5.2  
 [5] tools_4.1.2       yaml_2.2.1        rmarkdown_2.11    knitr_1.37       
 [9] xfun_0.29         digest_0.6.29     rlang_0.99.0.9003 evaluate_0.14    
```

</details>

**Comment by mikebessuille** [comment]
Looks to be fixed in SW

**Comment by romainfrancois** [comment]
LGTM on SW build 160.
