### ISSUE TITLE
Copying the contents of the 'Build' pane.

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#10305]
Hello,

  We cannot copy the contents of the 'Build' pane. This would be desirable, especially when we compile a package with C/C++ code and there are screens and screens of warnings. I'd like to copy in order to examine these warnings more conveniently.

**Comment by ronblum** [comment]
@stla Thank you for raising this! You should be able to copy the portion you need by selecting the portion you want to copy and either right-click and choose "Copy", or use the standard keyboard copy keyboard shortcuts, <kbd>Cmd-C</kbd> or <kbd>Ctrl-C</kbd>. What environment are you using?

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by gtritchie** [comment]
Duplicate of #8469?

**Comment by stla** [comment]
I'm using RStudio Desktop 2021.09 on Windows 10.

"Copy" is disabled when I right-click on the Build pane, and clicking "Select all" or typing Ctrl+A selects the contents of the console.

![rstudio](https://user-images.githubusercontent.com/4466543/148091553-3c9e7c9a-1950-493b-8573-91ea141f8b83.gif)

**Comment by stla** [comment]
> Duplicate of #8469?

Yes, looks like a duplicate.
