### ISSUE TITLE
Rstudio can't open with the error information( Error Starting R )

### ISSUE THREAD

**Issue by eternal-bug** [rstudio/rstudio#10304]
Hello, my Rstudio start with the **Error Starting R**.

## System details

```
RStudio Edition : Desktop 
RStudio Version : RStudio-2021.09.1-372.exe
OS Version      : WINDOWS 10
R Version       : 4.1.2
```

## Describe the problem in detail

same as [#10151](https://github.com/rstudio/rstudio/issues/10151) and [#4856](https://github.com/rstudio/rstudio/issues/4856), I encounter the **Error Sarting R** Rstudio Startup errors. 

However, this error did not occur in the beginning. The Rstudio normally work for many days. Onr day, after I the computer was rebooted, Rstudio had this error, and the R executable could not be executed in CMD. So I removed the original R and later reinstalled the new R 4.1.2 and Rstudio did not work either.

**my Rstudio error detial**

---

### Error Starting R

The R session failed to start.

RSTUDIO VERSION

```
RStudio 2021.09.1+372, "Ghost Orchid" (8b9ced18, 2021-11-08) for Windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

ERROR MESSAGE

```
[No error available]
```

PROCESS OUTPUT

The R session process exited with code 10.

ERRORS

```
[No errors emitted]
```

OUTPUT

```
[No output emitted]
```

RECENT LOG

C:/Users/admin/AppData/Local/RStudio/log/rsession-admin.log

```
2022-01-04T01:58:42.951364Z [rsession-admin] ERROR Unable to retrieve user home path. HRESULT: -2147024893; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool) src/cpp/core/system/Win32System.cpp:338
2022-01-04T05:26:54.675980Z [rsession-admin] ERROR Unable to retrieve user home path. HRESULT: -2147024893; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool) src/cpp/core/system/Win32System.cpp:338
2022-01-04T05:49:21.190635Z [rsession-admin] ERROR Unable to retrieve user home path. HRESULT: -2147024893; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool) src/cpp/core/system/Win32System.cpp:338
```

---

the error log different from the issues. it same as the question at the Rstudio Community [RStudio - Error Starting R](https://community.rstudio.com/t/rstudio-error-starting-r/118497). I have try the

+ delete the all `C:/Users/admin/AppData/Local/RStudio` and reinstall Rstudio.
+ install R with 32-bit version.
+ Reinstall Rstudio with administrator.
+ Update the windows environment variable

But I can't work yet and raise the **Error Starting R**. The Rstudio menu bar cannot be opened.

**Comment by ronblum** [comment]
@eternal-bug Thank you for raising this! A couple of questions:
1) You mention that at first, R from the command line—outside of RStudio—wasn't working. Does it work after the reinstall?
2) If so, is there a difference if you use the 32-bit version of R, instead of 64-bit? This is going by the comments at https://community.rstudio.com/t/rstudio-error-starting-r/118497/3

**Comment by eternal-bug** [comment]
Hello!
1. The new reinstall R can work. I guess the Rstudio's R path is old, but the Rstudio menu bar can't open, I would like to confirm whether deleting `C:/Users/admin/AppData/Local/RStudio` and reinstall Rstudio can delete the configuration of Rstudio for the path of R?
2. It makes no difference, Rstudio have the same error message.

**Comment by kevinushey** [comment]
> 2022-01-04T01:58:42.951364Z [rsession-admin] ERROR Unable to retrieve user home path. HRESULT: -2147024893; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool) src/cpp/core/system/Win32System.cpp:338

That code lives here:

https://github.com/rstudio/rstudio/blob/a8c2fb38729956dd10b6784e611db1bd29ddf58f/src/cpp/core/system/Win32System.cpp#L318-L343

And https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpathandsubdirw documents the return values. HRESULT error codes are documented here:

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/705fb797-2175-4a90-b5a3-3918024b10b8

But the error code doesn't seem to match any of the documented error codes; e.g.

```
> as.hexmode(-2147024893)
[1] "80070003"
```

And google suggests that error code is usually associated with Windows Update failures.

I don't have any great ideas, beyond ensuring that your copy of Windows is up to date...

**Comment by ronblum** [comment]
I think this and #10151 might be duplicates. As one user, I've been getting code -1073740791, but logged in as a different user I get -2147024893.

**Comment by eternal-bug** [comment]
Thanks! It work! 
I found that I had made a mistake before. I should deal with the `%appdata%\RStudio` rather than `%localappdata%\RStudio`. I just followed @ronblum at [#10151](https://github.com/rstudio/rstudio/issues/10151) answer. At the previous steps, The Rstudio is work!. The error would be reported again if I restored the previous configuration folder later, so I directly deleted the original configuration folder.

Same as @ronblum answer 1-3 step. My Step：

1. Close Rstudio.
2. Open file Manager.
3. Enter `%appdata%` at address bar.
4. mv `RStudio` to new name, such as `RStudio_Bak1`.
5. Open Rstudio, It work!

Thank!

**Comment by ronblum** [comment]
@eternal-bug I'm glad that it works, and thank you for the update! Usually resetting with `%localappdata%\RStudio` is enough to reset the state, so you were correct in doing so. 🙂

**Comment by ronblum** [comment]
@eternal-bug Do you by chance also have R-devel (4.2.0) on your machine, even though you're using 4.1.2? I'm trying to figure out when this happens.

**Comment by eternal-bug** [comment]
@ronblum Hello, I have two R( all are 4.1.1 version ) before reinstall 4.1.2 R: one is normal install R, other is R at Anaconda. The former takes precedence over the latter at environment variable, and Rstudio use former R. 

A piece of my mind: I thought it was strange that the R executable didn't work when my Rstudio didn't work. Is it possibile because of the sudden loses power or something wrong with the computer disk that Rstudio was implicated in R's Problem? ( my computer loses power and Check disk after Startup before Rstudio  )

**Comment by ronblum** [comment]
It's possible that having the Anaconda and CRAN R versions on the same machine is part of the issue. We've run into issues with having both installed on the same machine. It wouldn't explain how I ran into the issue.

I'll close this since resetting the state worked. The issue will still be here, though, for other people who might run into the issue, and I'll keep an eye on it to see if it becomes a pervasive problem—and @eternal-bug, if you run into the issue again, please let us know!

**Comment by mactony** [comment]
> Thanks! It work! I found that I had made a mistake before. I should deal with the `%appdata%\RStudio` rather than `%localappdata%\RStudio`. I just followed @ronblum at [#10151](https://github.com/rstudio/rstudio/issues/10151) answer. At the previous steps, The Rstudio is work!. The error would be reported again if I restored the previous configuration folder later, so I directly deleted the original configuration folder.
> 
> Same as @ronblum answer 1-3 step. My Step：
> 
> 1. Close Rstudio.
> 2. Open file Manager.
> 3. Enter `%appdata%` at address bar.
> 4. mv `RStudio` to new name, such as `RStudio_Bak1`.
> 5. Open Rstudio, It work!
> 
> Thank!

Use this, it works!!!!!!!!!!!!!!!!

**Comment by dkapt** [comment]
> if you have anaconda installed, open terminal and type command; conda start then open rstudio ,it worked for me in ubuntu (22.04)

I having some trouble opening RStudio.


## R Session Startup Failure Report

### RStudio Version

RStudio 2023.09.1+494 "Desert Sunflower " (cd7011dc, 2023-10-16) for Ubuntu Jammy

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 127. 

Error output:

```
/usr/lib/rstudio/resources/app/bin/rsession: error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory

```

Standard output:

```
[No output emitted]
```

### Logs

*Log File*

```
[No logs available]
```

**Comment by huihuihui-1997** [comment]
## R Session Startup Failure Report

### RStudio Version

RStudio 2024.04.2+764 "Chocolate Cosmos " (e4392fc9, 2024-06-05) for windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 3221225477. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*Log File*

```
[No logs available]
```
