### ISSUE TITLE
Changing LANGUAGE env var inside RStudio IDE console does not have expected effect

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#10308]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.2.0.345
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

* Open RStudio

````r
> Sys.setenv(LANGUAGE="fr")
> mean[[1]]
Error in mean[[1]] : object of type 'closure' is not subsettable
````

* Open R Gui

````r
> Sys.setenv(LANGUAGE="fr")
> mean[[1]]
Erreur dans mean[[1]] : objet de type 'closure' non indiçable
````

* Open R Term

````r
> Sys.setenv(LANGUAGE="fr")
> mean[[1]]
Erreur dans mean[[1]] : objet de type 'closure' non indiçable
````

### Describe the problem in detail

Following investigation for an issue in **testthat** (https://github.com/r-lib/testthat/issues/1534), it seems there could be an issue with RStudio IDE as the behavior is different with RGui and R Term - This was reported first in https://github.com/r-lib/withr/issues/189

Is there anything specific with how translation are handled for inside RStudio ?

### Describe the behavior you expected

I would expect the same behavior than in R Gui or R Term from within RStudio IDE console. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
See also: https://github.com/rstudio/rstudio/issues/4127

**Comment by kevinushey** [comment]
Even weird is that some error messages are properly translated, but others are not. For example:

```
> Sys.setenv(LANGUAGE = "en")
> oops
Error: object 'oops' not found
> vignette("oops", package = "nope")
Error in find.package(package, lib.loc) : 
  there is no package called ‘nope’
> 
> Sys.setenv(LANGUAGE = "fr")
> oops
Error: object 'oops' not found
> vignette("oops", package = "nope")
Error in find.package(package, lib.loc) : 
  aucun package nommé ‘nope’ n'est trouvé
```

This makes me think that R is caching translations (maybe only for the base package?) and those aren't getting appropriate reset when `LANGUAGE` changes.

**Comment by kevinushey** [comment]
Or, perhaps it's related to the default domain used by R? See https://bugs.r-project.org/show_bug.cgi?id=18092 for some motivation.

The translations work in RStudio, when explicitly requested from the right domain:

```
> Sys.setenv(LANGUAGE = "fr")
> gettext("object '%s' not found", domain = "R")
[1] "objet '%s' introuvable"
> gettext("there is no package called %s", domain = "R-base")
[1] "aucun package nommé %s n'est trouvé"
```

So perhaps the domain is not being correctly set when an error condition occurs in RStudio.

**Comment by kevinushey** [comment]
https://github.com/wch/r-source/blob/777b35108d3aaf87ad9afece6b9652acb2d3c5fb/src/main/errors.c#L1104-L1180 is probably relevant.

**Comment by kevinushey** [comment]
@cderv, are you willing to try and investigate more?

**Comment by cderv** [comment]
I can try. `gettext()` and this domain topic are new to me but I can add that to the list of things to learn and investigate.

**Comment by cderv** [comment]
Still need to look into this

**Comment by phgrosjean** [comment]
This bug is long-lasting now. Could you, please, look at it?

**Comment by kevinushey** [comment]
Ok, I finally have a toehold on this issue. The problem here occurs because the default domain being computed in RStudio seems to differ from "regular" R instances. For example, in RStudio, I see (using a debug build of R)

```
(gdb) p domainname
$4 = 0x7ffb4e301b60 <libintl_nl_default_default_domain> "messages"
```

Whereas, in R GUI, I see:

```
(gdb) p domainname
$1 = 0x257d2818500 "R"
```

The next step will be figuring out why that default domain name differs in each case, and whether there's a way for us to try and set it.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.09.0-daily+290 on Windows 11. (It was already working elsewhere.)
