### ISSUE TITLE
Find and Replace buttons are too small

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10316]
### System details

    RStudio Edition : 2022.2.0.330
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.1
    R Version       : R version 4.1.2 (2021-11-01)

Reproduce by pressing <kbd>Cmd + F</kbd> to open the Find and Replace bar in an editor instance. See:

<img width="502" alt="Screen Shot 2022-01-06 at 9 39 45 AM" src="https://user-images.githubusercontent.com/1976582/148426450-c1366d9f-b98c-4140-abcb-d617c98fdddf.png">

The associated buttons are much too small. Compare with RStudio 1.4:

<img width="552" alt="Screen Shot 2022-01-06 at 9 41 18 AM" src="https://user-images.githubusercontent.com/1976582/148426549-3e602694-9fc8-4ab8-be2a-533279c15d55.png">

cc: @jmcphers in case this is fallout from the removal of the classic theme.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin21.1.0 (64-bit)
Running under: macOS Monterey 12.1

Matrix products: default
LAPACK: /opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.1.2  fastmap_1.1.0   htmltools_0.5.2 tools_4.1.2    
 [5] yaml_2.2.1      rmarkdown_2.11  knitr_1.37      xfun_0.29      
 [9] digest_0.6.29   rlang_0.4.12    evaluate_0.14  
```

</details>

**Comment by kevinushey** [comment]
Note for QA: it would be worth double-checking that these UI elements are rendered correctly (and alignment is good) on the various platforms + flavors.

**Comment by ronblum** [comment]
Verified the buttons are good sizes and legible in:
- RStudio Desktop 2022.02.0+366/7 on MacOS 12.1, Ubuntu 20.04.3, and Windows 10
- RStudio Server 2022.02.0+366 on Red Hat 8.5 and Ubuntu 20.04.3 via Firefox and Chrome on MacOS 12.1
