### ISSUE TITLE
Allow different custom keybindings to be assigned to a command

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [rstudio/rstudio#10312]
I need (or may be it's implemented, but I do not know how to) to assign multiple keybindings to the same command.

E. g. I have a personal convention that includes the 'alt + 4', 'alt + 5', 'ctrl + n'  keybindings all to open a new R script, just to be sure that I do not miss the correct keybinding while not looking at the keyboard, and of course, to use the most convenient shortcut for a moment.
There is a respective question 5 years ago by Tim Courtney here, but unlike most others, it was left unanswered: 
https://support.rstudio.com/hc/en-us/articles/206382178-Customizing-Keyboard-Shortcuts-in-the-RStudio-IDE?page=2#comments
I failed to find any relaunches of this discussion on the RStudio Community website. 
A vs code extension allows an arbitrary number of keybindings to be assigned to the same action.

**Comment by ronblum** [comment]
@gjirokastrelbasanit34 Thank you for the suggestion! And extra thanks for referencing both the RStudio Community article and the VS Code comparison point.

**Comment by colearendt** [comment]
I like this idea
