### ISSUE TITLE
R Studio 2021.09.1+372 and Prior 2021.09.051 crashes when it started in Mac Monterey 12.1

### ISSUE THREAD

**Issue by iMarcello** [rstudio/rstudio#10324]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0+351 and 2021.09.1+372
    OS Version      : Mac OS 12.1 (21C52)
    R Version       :   R 4.1.2 and R 4.1.0

### Steps to reproduce the problem

Starting the app inmmediately crashs woth two different R versions R 4.1.2 and R 4.1.0 and R Studio Versions 2021.09.0+351 and 2021.09.1+372 as indicated.

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/46616553/148625621-4cd747b9-6231-4a50-af39-d9bab38a0d5f.png)

### Describe the behavior you expected

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7832144/diagnostics-report.txt)

**Comment by milesalanmoore** [comment]
I was experiencing a very similar issue. After beginning a new project for work, cloning a repo, and installing new packages, R studio started crashing before I ever even ran any code in the console. I was also receiving this error message along with the bomb dialogue.

<img width="256" alt="Screen Shot 2022-01-08 at 7 31 39 AM" src="https://user-images.githubusercontent.com/79930428/148648822-7817ebdd-2254-4d35-9bb7-4c9c42f0f0a4.png">


 I used this script (below) to uninstall all user installed packages after trying to reinstall R, Rstudio, and deleting/recloning the repo the error seems to start in.

`
# create a list of all installed packages
 ip <- as.data.frame(installed.packages())
 head(ip)
# if you use MRO, make sure that no packages in this library will be removed
 ip <- subset(ip, !grepl("MRO", ip$LibPath))
# we don't want to remove base or recommended packages either\
 ip <- ip[!(ip[,"Priority"] %in% c("base", "recommended")),]
# determine the library where the packages are installed
 path.lib <- unique(ip$LibPath)
# create a vector with all the names of the packages you want to remove
 pkgs.to.remove <- ip[,1]
 head(pkgs.to.remove)
# remove the packages
 sapply(pkgs.to.remove, remove.packages, lib = path.lib)
`
(Source: https://www.r-bloggers.com/2016/10/how-to-remove-all-user-installed-packages-in-r/ )


and it seemed to fix the problem for me (will update if that changes).

**Comment by ronblum** [comment]
@iMarcello Thank you for raising the issue! A couple of questions:
1) We you able to run an earlier version of RStudio Desktop, and if so, which one?
2) Were you able to run on a previous version of MacOS, and if so, which one?
3) Does switching to software rendering help? See https://github.com/rstudio/rstudio/issues/10020#issue-1038543531

@milesalanmoore Thank you for the added info! I suspect it's a different issue, though, since the problem happens after startup. Would you mind opening a new issue for it, as well as including a diagnostics reports? Instructions for getting them for RStudio Desktop are about halfway down at https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostic-Report

**Comment by iMarcello** [comment]
Hi @ronblum, **thanks for your reply!**. Please find my comments below.
1.- **YES**, I've downloaded Version 1.4.1717 and it run **OK**.
2.- **NO**, I'm not able to run other MacOS version.
3.- **NO**, I tried the recommndation mentioned, however the issue **not was solved**.
Kindest Regards.

**Comment by ronblum** [comment]
@iMarcello Thanks! You note using both R 4.1.0 and 4.1.2. Do you have them both installed side-by-side? If so, were they installed from a CRAN binary, conda, brew, or anything else?

**Comment by kratzera** [comment]
Dear all, I have a similar problem.
Rstudio: 2023.06.0+421
R version: 4.3.1
Mac OS BigSur 11.7.8
I was running some code and it was working. Then another one, which gave me some problems and errors, so I decided to upgrade and now, whenever I try to to run a script, R crashes with the fatal error message. Should I downgrade to a lower version? Best and thanks, Heidi
