### ISSUE TITLE
What are the preamble-xxx.pch files in the temp folder? 

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#10329]
Hello,

  I'm using RStudio Desktop 2021.09 with R-4.1.2 and Windows 10. It seems to me that RStudio creates some files `preamble-xxx.pch` i the `Temp` folder. Such a file takes more than 60 Mb, and they are not automatically deleted, so they quickly fill my hard drive. What is the role of these files? Would it be possible that RStudio automatically deletes them?

**Comment by kevinushey** [comment]
Can you share a reproducible example? When exactly do you see these files being created?

The `.pch` extension makes me believe these are precompiled headers, used for compilation of C / C++ code. However, we'll need to know information to know whether those are being created by RStudio, or an R package being used in your project.

**Comment by stla** [comment]
Ah that's possible I'm currently working on a package with Rcpp. I don't know when the files are created, I will observe next time.
