### ISSUE TITLE
`View()` does not display matrix-columns in tibbles correctly.

### ISSUE THREAD

**Issue by Aariq** [rstudio/rstudio#10332]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.1
    OS Version      : macOS 12.0.1
    R Version       : 4.0.2

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

A tibble that includes a matrix as a column prints the values in each matrix column in the console, but with `View()` in RStudio only the first column is visible and there is no indication that other columns exist.  This does not occur when `View()` is run from R running in Terminal (an X11 window opens with multiple columns shown) so it seems to be an RStudio specific issue.

## Reprex
``` r
library(tibble)
set.seed(123)
my_matrix <- matrix(rnorm(100), nrow = 10)
tbl <- tibble(x = letters[1:10], mat_col = my_matrix)
tbl
#> # A tibble: 10 × 2
#>    x     mat_col[,1]   [,2]   [,3]    [,4]    [,5]    [,6]    [,7]   [,8]
#>    <chr>       <dbl>  <dbl>  <dbl>   <dbl>   <dbl>   <dbl>   <dbl>  <dbl>
#>  1 a         -0.560   1.22  -1.07   0.426  -0.695   0.253   0.380  -0.491
#>  2 b         -0.230   0.360 -0.218 -0.295  -0.208  -0.0285 -0.502  -2.31 
#>  3 c          1.56    0.401 -1.03   0.895  -1.27   -0.0429 -0.333   1.01 
#>  4 d          0.0705  0.111 -0.729  0.878   2.17    1.37   -1.02   -0.709
#>  5 e          0.129  -0.556 -0.625  0.822   1.21   -0.226  -1.07   -0.688
#>  6 f          1.72    1.79  -1.69   0.689  -1.12    1.52    0.304   1.03 
#>  7 g          0.461   0.498  0.838  0.554  -0.403  -1.55    0.448  -0.285
#>  8 h         -1.27   -1.97   0.153 -0.0619 -0.467   0.585   0.0530 -1.22 
#>  9 i         -0.687   0.701 -1.14  -0.306   0.780   0.124   0.922   0.181
#> 10 j         -0.446  -0.473  1.25  -0.380  -0.0834  0.216   2.05   -0.139
View(tbl)
```

<sup>Created on 2022-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       macOS  10.16                
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2022-01-10                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  backports     1.4.0   2021-11-23 [1] CRAN (R 4.0.2)
#>  cli           3.1.0   2021-10-27 [1] CRAN (R 4.0.2)
#>  crayon        1.4.2   2021-10-29 [1] CRAN (R 4.0.2)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.0.2)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.0.2)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.0.2)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.2)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.0.2)
#>  glue          1.6.0   2021-12-17 [1] CRAN (R 4.0.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.2)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.0.2)
#>  knitr         1.36    2021-09-29 [1] CRAN (R 4.0.2)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.0.2)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
#>  pillar        1.6.4   2021-10-18 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.0.2)
#>  rlang         0.4.12  2021-10-18 [1] CRAN (R 4.0.2)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.0.2)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.7.6   2021-11-29 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  styler        1.5.1   2021-07-13 [1] CRAN (R 4.0.2)
#>  tibble      * 3.1.6   2021-11-07 [1] CRAN (R 4.0.2)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.0.2)
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.0.2)
#>  withr         2.4.3   2021-11-30 [1] CRAN (R 4.0.2)
#>  xfun          0.28    2021-11-04 [1] CRAN (R 4.0.2)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

The X11 window when run in R from console:
<img width="766" alt="Screen Shot 2022-01-10 at 12 15 39 PM" src="https://user-images.githubusercontent.com/25404783/148809016-5207081d-e6c3-455f-881b-294183ff027f.png">

The View tab in RStudio:
![Screen Shot 2022-01-10 at 12 15 01 PM](https://user-images.githubusercontent.com/25404783/148808923-41f50175-0200-498c-a4e6-5b883cc9a3dc.png)

**Comment by ronblum** [comment]
@Aariq Thank you for raising this! I can reproduce it in:
- RStudio Desktop 1.2.5042 & 2022.02.0+364 on MacOS 12.1
- RStudio Server 2022.02.0+31st 64 on Ubuntu 20.04 via Chrome on MacOS 12.1

Notes:
1) This appears to be an existing issue, going back at least to 1.2.5042.
2) The data is showing up in the Environment Pane. I reduced the tibble to 2x2 in order to view it all:
<img width="735" alt="little_tibble" src="https://user-images.githubusercontent.com/31009952/148828007-3fd873b8-71df-4893-bf9d-b1f527e4be02.png">

```
library(tibble)
set.seed(123)
my_matrix <- matrix(rnorm(4), nrow = 2)
tbl <- tibble(x = letters[1:2], mat_col = my_matrix)
tbl
View(tbl)
```

**Comment by romainfrancois** [comment]
I think I can pick it up, and take inspiration from how `tibble` / `pillar` displays it on the console.

**Comment by kevinushey** [comment]
I'm not positive on what the best way to approach this is, but you probably want to start around here:

https://github.com/rstudio/rstudio/blob/bc4df12db4721bdba676bd4c88e40d6c9651dc1a/src/cpp/session/modules/SessionDataViewer.R#L702-L712

**Comment by romainfrancois** [comment]
Tracked this down to `.rs.flattenFrame` : 

https://github.com/rstudio/rstudio/blob/d02233de212643cc0b1aac7711c617cc670aa9b4/src/cpp/session/modules/SessionDataViewer.R#L347-L386

**Comment by Aariq** [comment]
Tibbles with matrix columns also don't show up at all in in-line R Markdown with paged data frames.  Do you think this likely fixes that problem as well, or should I open a separate issue?

**Comment by romainfrancois** [comment]
I think this is a different problem.

**Comment by jgutman** [comment]
Verified on RStudio Desktop 2022.06.0-daily+36 on Mac OS 12.1 (with R-devel 4.2.0)
