### ISSUE TITLE
Make 'File > New file > C++ file' more agnostic or more responsive

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#10337]
The new file created via *File > New file > C++ file* is pre-populated with very helpful content **if** you're developing with Rcpp.

I just used it in a project that, instead, uses cpp11, in which case that content is not helpful.

I wonder if the template could be more agnostic? Or include scaffolding for both Rcpp and cpp11 (assuming the user can delete unneeded content)? Or, in a package, consult DESCRIPTION to make a smarter guess?

cc @romainfrancois

**Comment by kevinushey** [comment]
For context, the template lives here:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/resources/templates/rcpp.cpp

and gets rendered from here:

https://github.com/rstudio/rstudio/blob/87992ca25458ec27ed2938fd56b439bd45094775/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java#L913-L929

I would prefer keeping Rcpp as default, but using a `cpp11`-tailored version if we could figure out that was relevant; e.g. we saw `LinkingTo: cpp11` in the package `DESCRIPTION` file or something similar.

**Comment by kevinushey** [comment]
And see, in the Packages preferences pane:

<img width="615" alt="Screen Shot 2022-01-10 at 4 54 21 PM" src="https://user-images.githubusercontent.com/1976582/148862351-29b56803-ec5e-42c2-8dbc-f09074e02771.png">

**Comment by romainfrancois** [comment]
Thanks for the pointers @kevinushey. That'll get me started.

**Comment by romainfrancois** [comment]
Kept as in progress for now, so that we can incorporate https://github.com/rstudio/rstudio/pull/10386 too.

**Comment by romainfrancois** [comment]
For qa, see https://github.com/rstudio/rstudio/pull/10386

**Comment by jgutman** [comment]
Verified in RStudio Desktop 2022.02.0-preview+405 on Mac OS 12.1 with R 4.1.2, using both the Global Options and Linking To methods.

**Comment by jgutman** [comment]
Should still be added to NEWS for Prairie Trillium
