### ISSUE TITLE
Displaying filepath when multiple files with same name are open

### ISSUE THREAD

**Issue by linogaliana** [rstudio/rstudio#10350]
- In `RStudio Desktop` (my version is `""Ghost Orchid" Release (fc9e2179, 2022-01-04) for Windows`) when using a project, you might open different files that have the same name, e.g. in my capture `action.yml`

![image](https://user-images.githubusercontent.com/33896139/149304155-88c7631a-ede1-45f0-a121-43567e6a68d4.png)

- It is sometimes confusing to determine which file we see in the editor pane. `VisualStudio` proposes a solution that I think can be used as a source of inspiration:

 
![image](https://user-images.githubusercontent.com/33896139/149304452-56aab0d5-068b-41e9-9ce1-ab2def4e2865.png)

- This feature request might be related to #10293 but I think this one is more specific to the use case of having the same name for multiple projects. However, if you think this is a duplicated __issue__, please feel free to close this one.

**Comment by kevinushey** [comment]
If you let your mouse hover over the file name in the tab, the full path will be displayed in a tooltip:

<img width="186" alt="Screen Shot 2022-01-13 at 10 51 04 AM" src="https://user-images.githubusercontent.com/1976582/149391347-6fda3c77-e5ea-4573-8bca-6ab54e6ad9d7.png">

Is this sufficient?

**Comment by linogaliana** [comment]
Thanks for your answer. Yes that does the job, did not pay attention.

You can close the _issue_
