### ISSUE TITLE
More featured addins functionality

### ISSUE THREAD

**Issue by AEBilgrau** [rstudio/rstudio#10356]
The addins are great. But having a even more featured addins system would be fantastic and add a lot of value to the IDE and package ecosystem.

Our current small wishlist is:

  1. Ability to favorite addins (then shown first or otherwise highlighted) and possibly hide unwanted
  2. Ability to have dropdown of package-specific addin (maybe only if you've fav'd it) 
  3. Ability to bundle an icon/fav-icon with the addin
  4. Ability to place the addin in other panels and places (so I e.g. can create my own source/knitr-like functions which has other effects)

But taking the idea even further and separating the package-provided functionalities (for packages such as knitr and rmarkdown) from the IDE more cleanly and sharply might also make sense from architectural PoV.  This would likely alleviate some of the [R-package version requirements by the Rstudio Workbench](https://raw.githubusercontent.com/rstudio/rstudio/v2021.09.0+351/src/cpp/session/resources/dependencies/r-packages.json) which currently does not always play well with Rstudio Package Manager lockdates and multiple R-versions though that is now partly solved by commit bd380a72bf34826cf3c9c28a352ba00896d451f7.

Thanks!

**Comment by ronblum** [comment]
@AEBilgrau Thank you for the detailed enhancement suggestions!
