### ISSUE TITLE
Extremely minor issue: View() description of POSIX missing a character

### ISSUE THREAD

**Issue by pvanlaake** [rstudio/rstudio#10359]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Intel Mac OS X 11_5_2
    R Version       : 4.1.1

### Steps to reproduce the problem
View(x) where x is a POSIX* 

### Describe the problem in detail
When viewing a variable of type POSIX*, the View() function gives as Type: "double (S3: POSIXct, POSIXt)", obviously missing an "l".
### Describe the behavior you expected
View(x) should give as Type: "double (S3: POSIXct, POSIXlt)"

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is expected; e.g.

```
> class(Sys.time())
[1] "POSIXct" "POSIXt" 
```

POSIXct and POSIXlt are seen as "specializations" of the POSIXt type.
