### ISSUE TITLE
Use project/working directory by default when running local job

### ISSUE THREAD

**Issue by kinto-b** [rstudio/rstudio#10365]
Currently, the `Working Directory` path in the `Start Local Job` dialogue box defaults to the directory in which the currently open script resides. However, in almost all cases I find myself wanting to run the job in my current working directory, which is almost always the project directory. This means having to manually set the `Working Directory` path almost every time I run a local job. 

I expect most RStudio users are in the same position. So I'd say using the project directory (or the current working directory) instead as a default would be preferable.

(Thanks for maintaining such a great product!)

**Comment by jmcphers** [comment]
Would the changes proposed in https://github.com/rstudio/rstudio/issues/8985 address this issue for you?

**Comment by kinto-b** [comment]
@jmcphers Ah, apologies. I did search for an existing issue, but clearly not thoroughly enough. Yes, one of the changes proposed there would address this. Thanks!
