### ISSUE TITLE
Package manager should not default to compiling from source on MacOS

### ISSUE THREAD

**Issue by aourednik** [rstudio/rstudio#10360]
On MacOS systems, the default behaviour of `install.packages("pacakage_name")` is to compile from source. By default, RStudio launches this very command when installing new packages with the package manager. 

This is __hard on the users__, since many packages have compilation issues (notably sf, terra, rgl and their dependencies) that only people well acquainted with llvm, gcc and other compilers can solve. The need to define multiple Makevars files to accomodate specific compilation needs (such as fopenmp for data.table) makes things worse. 

To solve this, RStudio's package manager should:

1. See if a binary is available for the specific Mac architecture
2. Install the binary if available by launching `install.packages("path_to/found_binary.tgz", repos = NULL, type = .Platform$pkgType)` 
3. Only if a binary is not available, attempt to compile with `install.packages("pacakage_name")` 

Example. Installing "sf" on a Apple Silicon am64 : 

1. Verify binaries for the architecture -> finds: https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.1/sf_1.0-5.tgz
2. Since a binary was found, runs `install.packages("https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.1/sf_1.0-5.tgz", repos = NULL, type = .Platform$pkgType)` instead of `install.packages("sf")` .

That's it. 

Very simple and saving so much time for the end-user!

**Comment by kevinushey** [comment]
> On MacOS systems, the default behaviour of install.packages("pacakage_name") is to compile from source. By default, RStudio launches this very command when installing new packages with the package manager.

This is not true for CRAN releases of R; those will have:

```
> getOption("pkgType")
[1] "both"
```

which implies that R will prefer installing binaries where appropriate.

Other builds of R on macOS (e.g. Homebrew) are not configured to install binaries from CRAN, because there's less guarantee that CRAN binaries are compatible with other builds of R.

**Comment by aourednik** [comment]
Thanks for pointing this out @kevinushey. I am running a Homebrew build of R indeed. Is there a way to reconfigure the behaviour of install.packages even in this case?

Another aspect: is `.Platform$pkgType = "mac.binary"`enough to distinguish between arm64 and x86_64 builds, i.e., is install.packages able to automatically choose the right one?

Still I think it would be a huge time-saver if RStudio's package manager double-checked this independently. Or better, give an explicit choice to the user with a simple checkbox ("compile from source?" ☐ or ☑ ) and issue to corresponding command to R

**Comment by kevinushey** [comment]
You can hack it in the following way:

```
platform <- .Platform
platform$pkgType <- "mac.binary"

unlockBinding(".Platform", .BaseNamespaceEnv)
assign(".Platform", platform, envir = .BaseNamespaceEnv)
lockBinding(".Platform", .BaseNamespaceEnv)

options(pkgType = "both")
```

Then, I see R (even with Homebrew) installing CRAN binaries.

```
> install.packages("rlang")
Installing package into '/Users/kevin/Library/R/homebrew/aarch64/4.1'
(as 'lib' is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/rlang_0.4.12.tgz'
Content type 'application/x-gzip' length 1328105 bytes (1.3 MB)
==================================================
downloaded 1.3 MB


The downloaded binary packages are in
	/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//RtmpjhR1Mn/downloaded_packages
```

Alternatively, if Homebrew builds of R wanted to support this, they could use:

```
#define PLATFORM_PKGTYPE "mac.binary"
```

as per https://github.com/wch/r-source/blob/777b35108d3aaf87ad9afece6b9652acb2d3c5fb/src/main/platform.c#L299-L306.

**Comment by ronblum** [comment]
Note: Closing as `external` since the behavior is driven by the R distribution, but this issue will be searchable for anyone else who might want the workarounds.
