### ISSUE TITLE
Show a global progress notification when important requests are waiting for the R main thread

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#10364]
If the R runtime is busy, and not calling the "polledEventHandler", many operations in the IDE will wait without feedback. We do have the GlobalProgressIndicator registered for some operations that are known to take a long time - e.g. installing dependencies, but if the operation is normally fast, for example: "New RMarkdown" file, there's no feedback when it's stuck waiting for R to finish something.

We could either add GlobalProgressIndicators individually in the UI for all of these important operations that might block due to R being busy, or it might be easier to code this up in a general way in the rsession. In this approach, we'd use the offline thread (part of SessionOfflineService.cpp) that already periodically checks the mainConnectionQueue. It would need a table mapping the important RPC request names to user visible ones for the operation. Once a minimum delay for a given request has been exceeded, it would send an event back to the IDE with a description of the pending operation, and the pending request id.  In response to the event, the UI would trigger a GlobalProgressIndicator that is completed when the async reply for that request is received.

**Comment by colearendt** [comment]
This would be a huge help!!
