### ISSUE TITLE
Unable to Change Pane Layout

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#10367]
### System details

    RStudio Edition : Desktop
    RStudio Version : >= 2022.02.0-daily+353
    OS Version      : macOS 12.1 / Ubuntu 20.04
    R Version       : 4.1.2 / 4.0.4

### Steps to reproduce the problem

1. Open RStudio
2. Go to the Global options
3. From the Pane Layout tab, change the layout
4. Click "Apply" or "Okay"

### Describe the problem in detail

Nothing changes.

### Describe the behavior you expected

The pane layout should change.

This works in Ghost Orchid.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mine-cetinkaya-rundel** [comment]
In my case, starting with non-default pane layout, I'm able to change the layout once back to default, but it won't let me make further updates to the pane layout (e.g., back to a non-default layout).

**Comment by MariaSemple** [comment]
Interesting! My layout started in the default state, so it sounds like it might only be allowing users to change the layout to default.

**Comment by ronblum** [comment]
FWIW, this change happened somewhere between Prairie Trillium builds 337 and 356.

**Comment by kevinushey** [comment]
The following errors are emitted when trying to change the layout in the JS console:

```
Invaliding tabset config (Presentation index)
Pane config is not valid
Pane config is not valid
```

**Comment by kevinushey** [comment]
Looks like it was unfortunately caused by https://github.com/rstudio/rstudio/pull/10250. I'll take a look.

**Comment by kevinushey** [comment]
I've reverted the associated changes for now. Here's how the layout looks to me:

<img width="818" alt="Screen Shot 2022-01-18 at 1 24 10 PM" src="https://user-images.githubusercontent.com/1976582/150021084-4ef1b84b-413f-4779-96b4-4e1e6c0d5220.png">

I'm not sure what the solution here is, since the Presentation pane (for R presentations) and the Presentations pane (for Quarto presentations?) are different things that happen to have the same name, and (even if nobody seems to use it?) we still provide UI for creating and running R Presentations.

**Comment by ronblum** [comment]
What about keeping them both and giving them slightly more distinguishing names, like "R Presentations" and "Quarto Presentations," or whatever is appropriate?

**Comment by kevinushey** [comment]
I think we can at least confirm that the regression has been fixed, and leave any other changes for this part of the codebase to SW (just because the pane layout code is so fragile)

**Comment by R-Hannibal** [comment]
### Verified Fixed

    RStudio Edition : Desktop / Workbench
    RStudio Version : 2022.02.0 Build 386.pro3
    OS Version      : MacOS / rhel7
    R Version       : 4.1.2

### Summary
Verified that the ability to change pane layout has been restored. User can successfully move Console/Source/etc. quadrants around successfully and the changes are saved and successfully applied.

### Automation
- According to @kevinushey 's comment [above](https://github.com/rstudio/rstudio/issues/10367#issuecomment-1017108631), the pane layout code is fragile and therefor it makes sense to me to add an E2E test here. Leaving the ticket open to see if I can add a quick test to cover changes in pane layout. 

### Notes
- The breakage that occurred here was preventing the quadrants of the IDE (Source. Console, etc.) from being moved. The ability to add source columns or move Files/Connections/etc. panes between the quadrants they appear in was unaffected.

**Comment by R-Hannibal** [comment]
Filed an automation ticket so this ticket can be closed while I work on it: https://github.com/rstudio/rstudio-ide-automation/issues/584
