### ISSUE TITLE
update rtools42 URL when CRAN-stable link is available

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10361]
https://github.com/rstudio/rstudio/blob/01ef6e05e3a5e02f39741e78cc6519b6b074b20d/src/cpp/core/r_util/RToolsInfo.cpp#L292-L296

**Comment by ronblum** [comment]
QA Note: In testing, include verification that
1) A fresh installation of R 4.2 (no previous installation of R and Rtools) triggers installation of Rtools42
2) Installing R 4.2 on top of earlier versions of R and Rtools triggers installation of Rtools42
3) Installing an earlier version of R (such as R 3.6.3) triggers installation of earlier versions of Rtools (e.g. Rtools35)

**Comment by kevinushey** [comment]
For PT, I wonder if we should just use our own copy of Rtools in an S3 bucket, and later update that to an appropriate CRAN URL in a patch release (or later)?

**Comment by mikebessuille** [comment]
@kevinushey this seems like a very reasonable approach to me, because we can control the version for the period of PT that it's needed.  In a patch we can update it.

**Comment by kevinushey** [comment]
Done with https://github.com/rstudio/rstudio/commit/1bf4233bb0230021cf673d96fc4c896d17332f1f.

**Comment by kevinushey** [comment]
Moving this to SW just to indicate it's not part of the current release work (we can bring it back for a patch release milestone later if necessary)

**Comment by jgutman** [comment]
https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html

Looks like the link is available now

**Comment by jgutman** [comment]
Ah actually looks like the exe is still versioned so I guess it's not stable yet?

**Comment by kevinushey** [comment]
FWIW I've contacted Tomas at R Core to ask if they'll plan to publish Rtools with a stable URL that RStudio could use here, in tandem with the R 4.2.0 release.

**Comment by ronblum** [comment]
[Note: just tracking, today the link is https://cran.r-project.org/bin/windows/Rtools/rtools42/files/rtools42-5168-5107.exe]

**Comment by jgutman** [comment]
See discussion in #10205 . It looks like a stable URL might not become available. What might be the best way forward is using the https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html URL, and parsing the [Rtools42 installer](https://cran.r-project.org/bin/windows/Rtools/rtools42/files/rtools42-5253-5107.exe) hyperlink to grab the exe file from there. The actual link target has updated, but the link embedded in that page has remained consistent.

**Comment by jgutman** [comment]
Essentially duplicate issue, will test in #10205
