### ISSUE TITLE
visual editor: problems with column attribute display/layout

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#10370]
From @mine-cetinkaya-rundel:

This might be more of a visual editor thing instead of a quarto thing but I keep encountering it when I'm in quarto so I'll mention here -- in the two column layout, if you insert an image into a column, the visual editor looks a bit wonky (see screenshot).

```markdown
## Slide with columns

::: columns
::: {.column width="50%"}
hello
:::

::: {.column width="50%"}
![](elephant.png){fig-alt="Elephant"}
:::
:::
```

<img width="591" alt="Screen Shot 2022-01-17 at 3 25 21 PM" src="https://user-images.githubusercontent.com/104391/149857026-f178afc9-2e29-49a1-a786-12141d89a430.png">

**Comment by jjallaire** [comment]
The problem seems to be that resizing the image causes a new decorator to be created (but the old one remains)

**Comment by jjallaire** [comment]
Should be fixed here: https://github.com/rstudio/rstudio/commit/81a8e220ac1e35eaeb2b52a0cabd527c769af855

**Comment by romainfrancois** [comment]
Verified in : RStudio 2022.06.0-daily+373

<img width="734" alt="image" src="https://user-images.githubusercontent.com/2625526/167373269-af774cfa-e1e4-4f3b-ab69-52a433d7de0b.png">
