### ISSUE TITLE
Source button does not recognize cpp11 files.

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#10387]
When editing a cpp11 styled c++ file, e.g. 

```cpp
#include <cpp11.hpp>

// This is a simple example of exporting a C++ function to R. You can
// source this function into an R session using `cpp11::cpp_source()`.

// Learn more about cpp11 at: 
//
//   https://cpp11.r-lib.org/index.html

[[cpp11::register]]
double sum(cpp11::doubles x) {
    double total = 0.0;
    for (double value: x) {
        total += value;
    }
    return total;
}
```

The source button still calls `Rcpp::sourceCpp()` which gives: 

```
> Rcpp::sourceCpp("/tmp/test.cpp")
test.cpp:1:10: fatal error: 'cpp11.hpp' file not found
#include <cpp11.hpp>
         ^~~~~~~~~~~
1 error generated.
make: *** [test.o] Error 1
```

### System details

RStudio 2022.01.999-dev+999 "Prairie Trillium" Daily (9bbfe5b1278ec5a165a1a4b8b5658458cc835705, 2022-01-19) for Unknown OS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
QA: 

create new c++ file and copy this code in: 

```cpp
#include <cpp11.hpp>

// This is a simple example of exporting a C++ function to R. You can
// source this function into an R session using `cpp11::cpp_source()`.

// Learn more about cpp11 at: 
//
//   https://cpp11.r-lib.org/index.html

[[cpp11::register]]
double sum(cpp11::doubles x) {
    double total = 0.0;
    for (double value: x) {
        total += value;
    }
    return total;
}
```

Click on the source button: 

![image](https://user-images.githubusercontent.com/2625526/151121014-e01a0ec8-4ce0-46b7-a194-7af2c53e0ac2.png)

This will send `cpp11::source_cpp()` in the console, and execute it.

Run `sum(c(1, 2, 3))`

**Comment by jgutman** [comment]
Verified in 2022.06.0+36 RStudio Desktop on MacOS 12.1 with R 4.1.2 and `cpp11` 0.4.2
Also verified in 2022.06.0+36 RStudio Desktop on Windows 11 Enterprise with R 4.1.2 (32-bit), Rtools 4.0 and `cpp11` 0.4.2

Tested with:
```
#include <cpp11.hpp>

[[cpp11::register]]
double sum(cpp11::doubles x) {
  double total = 0.0;
  for (double value: x) {
    total += value;
  }
  return total;
}
```
and sourcing with the Source button (which ran `cpp11::cpp_source("test_sourcecpp11.cpp")`)
