### ISSUE TITLE
Rstudio displays a black screen in Windows Remote Desktop environment.

### ISSUE THREAD

**Issue by Sadaree** [rstudio/rstudio#10395]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.2+382 (the latest version publicly available)
    OS Version      : Windows 10 Education (21H1, build 19043.1466, Korean language)
    R Version       : 4.1.2

### Steps to reproduce the problem
1) First open Rstudio outside of the remote desktop environment.
2) Open any existing project. 
3) Log into the same PC using the Remote Desktop client program (or the app).
(Specifically, I checked that this behavior is present when using the Mac and iOS versions of Remote Desktop.)

### Describe the problem in detail
Rstudio just becomes a wall of black screen, and becomes unusable afterward. (Please refer to the picture below)

![IMG_0141](https://user-images.githubusercontent.com/53806983/150275993-9b8a3485-4d0e-429e-8c23-7c485ed95416.PNG)

I believe it is just a cosmetic issue, since I see a cursor change when I move the mouse to the spot where R scripts are usually located.

A few notes:
 - This behavior had not been observed in prior versions of Rstudio (e.g. version 1.3).
 - This also does not happen the other way around: if one first opens Rstudio within the remote desktop environment, then log into the same PC where it is physically located, Rstudio displays its contents without any issues.

### Describe the behavior you expected
It should run and display all contents normally, without displaying that black screen above.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I could not reproduce on my setup:

- Microsoft Remote Desktop client Version 10.7.4 (1968) on MacOS 12.1 Monterey
- RStudio 2021.09.2 Build 382
- Windows-10 21H2 (19044.1466) English

I have the default rendering options selected:

![Screenshot of RStudio General Advanced options](https://user-images.githubusercontent.com/10569626/150437522-589ec683-96cc-4115-bd0c-3fb085b0db1b.png)

**Comment by Sadaree** [comment]
Thank you for looking into the problem, @gtritchie!
After your reply, I changed the rendering engine from "auto-detect" to "software", and it seems to display everything fine, even in Remote Desktop environment! (at least for now)
However, if I set the engine to "auto-detect" or "openGL", then it will still display the black screen that I mentioned above.
Although I fixed my problem regarding this black screen issue, I'm still not sure whether to call it case-closed, since it worked without any hiccups prior to updating Rstudio to the latest version. (I think I was using 1.3.1093 before updating.)

**Comment by jmcphers** [comment]
FWIW, RStudio is _supposed_ to use software rendering by default on remote desktop for this very reason:

https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/cpp/desktop/DesktopMain.cpp#L303-L306

(maybe worth checking to make sure the way we're testing this is still working on newer Windows versions)
