### ISSUE TITLE
Code folding by indentation

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#10404]
The code folding is quite nice and while there are a few issues related to folding at different markers, I'd like the ability to fold code based on indentation. Now that I use `styler` 💯of the time, the indentation in my code has become uniform. It would be nice to collapse large `mutate()` and `case_when()` statements or fold code from assignment to assignment.

Here is where VS Code would rollup the lines and it matches what I would like to see. One difference however is that VS Code rolls up lines 1:4 instead of just lines 1:3. Ideally, RStudio would determine if the expression is over or not and only fold the lines relevant to that expression. Keeping some vertical space between the different assignments is important to me.

Thanks for your consideration.

![image](https://user-images.githubusercontent.com/14003618/150429314-2befe407-b0cc-40d2-97a7-6954dc4f28c7.png)

**Comment by ronblum** [comment]
@rjake Thank you for this suggestion, as well!
