### ISSUE TITLE
Shortcuts for outlines?

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#10405]
The outline feature in RStudio is 👌 I find myself creating markers to know where new objects are made or for reactive elements in dashboards. I'd like to suggest some comment helpers that RStudio can use in the outlines. The suggestion is 
`#prefix <----` where `#` kicks off the comment, the optional text after the `#` becomes a prefix and the `<----` triggers the outline to use anything up-to the assignment arrow as the suffix with a space in-between.

![image](https://user-images.githubusercontent.com/14003618/150435114-6afa188a-3e90-4b99-855c-802caed4ed4e.png)

Note, the last example doesn't trigger a difference because it uses `----` instead of `<----`

Here's an example outline from one of my dashboards

![image](https://user-images.githubusercontent.com/14003618/150435729-d5cdc5c9-ef4f-4a3f-a2a4-75f487bc78b8.png)

**Comment by ronblum** [comment]
@rjake Thank you for the suggestion! We'll review it as we continue development of RStudio.
