### ISSUE TITLE
rstudio fatal error during dada2 dereplication step

### ISSUE THREAD

**Issue by ranjanmanishblue** [rstudio/rstudio#10409]
I am facing fatal error during running this command as follows:
9. Dereplicate FASTQ files to speed up computation
derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)

however, I am getting my RAM of 16GB not supporting with all the files (large data) at once, and process getting aborted after some time. 
please suggest alternative to it. thanks.

**Comment by ronblum** [comment]
@ranjanmanishblue Thank you for raising this! Does this occur only in RStudio, or does the same happen when run in standalone R, either in a terminal or an R GUI?

**Comment by ranjanmanishblue** [comment]
> @ranjanmanishblue Thank you for raising this! Does this occur only in RStudio, or does the same happen when run in standalone R, either in a terminal or an R GUI?

I have not tried standalone R, this is happening in Rstudio, specifically R GUI.

**Comment by mikebessuille** [comment]
This doesn't look like an RStudio issue.  When you say "specifically R GUI" do you mean the R gui application that comes with R?  That is not produced by RStudio.  Please let us know what behaviour you're seeing in standalone R, and how that compares with the behaviour in the RStudio Desktop IDE.   If they are different, we'd be happy to look into this further.

**Comment by ranjanmanishblue** [comment]
> This doesn't look like an RStudio issue. When you say "specifically R GUI" do you mean the R gui application that comes with R? That is not produced by RStudio. Please let us know what behaviour you're seeing in standalone R, and how that compares with the behaviour in the RStudio Desktop IDE. If they are different, we'd be happy to look into this further.

This was computing capacity error, required HPC to work around it, thanks 👍😊
