### ISSUE TITLE
Rstudio UI flicker with 3200x1800

### ISSUE THREAD

**Issue by weirdo67** [rstudio/rstudio#10408]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.01.999-dev+999
    OS Version      : ArchLinux, 5.16.1-arch1-1
    Windows Manager: i3
    everything else default Arch install
    R Version       :  4.1.2

### Steps to reproduce the problem
Open Rstudio and type, screen will flicker and flash, thats it.

Here is a video of me doing just that:
https://youtu.be/6ofCIZwMYcs

### Describe the problem in detail
Opening up the terminal fixing it seems weird, I'm not sure how to go into more detail so i included a link of the bug in action on youtube.
This is a fresh install of Rstudio I just installed it tonight actually
the frame rate isnt that bad, nor is it that zoomed in irl, the actual file size just would of been 4gb.

here is my Xresources
`
  1 !!XRANDR
  2 Xft.dpi:       220
  3 Xft.antialias: true
  4 Xft.hinting:   true
  5 Xft.rgba:      rgb
  6 Xft.autohint:  false
  7 Xft.hintstyle: hintslight
  8 Xft.lcdfilter: lcddefault
  9 
 10 !!URxvt
 11 URxvt.keysym.Shift-Control-V: perl:clipboard:paste
 12 URxvt.keysym.Shift-Control-C: selection_to_clipboard
 13 URxvt.iso14755: False
 14 URxvt.perl-ext-common:deault,clipboard
 15 URxvt.scrollBar:false
 16 URxvt.font: xft:Terminus:style=monospace:pixelsize=26:antialias=false
 17 
`

The request log:

`1642747034118
1642746568839,1664634375,"{""method"":""get_events"", ""params"":[145], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746578869,"{""result"":[{""id"":146,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3138864,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746578892,1850770725,"{""method"":""get_events"", ""params"":[146], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746588921,"{""result"":[{""id"":147,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3125212,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746588946,-1190092184,"{""method"":""get_events"", ""params"":[147], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746598966,"{""result"":[{""id"":148,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3111364,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746598998,-715456252,"{""method"":""get_events"", ""params"":[148], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746609012,"{""result"":[{""id"":149,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3193740,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746609030,-938524600,"{""method"":""get_events"", ""params"":[149], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746619016,"{""result"":[{""id"":150,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3170996,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746619041,-1988181464,"{""method"":""get_events"", ""params"":[150], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746629051,"{""result"":[{""id"":151,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3119264,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746629061,-1600219965,"{""method"":""get_events"", ""params"":[151], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746639099,"{""result"":[{""id"":152,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3130140,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746639105,2130784173,"{""method"":""get_events"", ""params"":[152], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746649102,"{""result"":[{""id"":153,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3122952,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746649116,-9482943,"{""method"":""get_events"", ""params"":[153], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746659150,"{""result"":[{""id"":154,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3135148,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746659163,467914295,"{""method"":""get_events"", ""params"":[154], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746669193,"{""result"":[{""id"":155,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3146200,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746669205,1434515554,"{""method"":""get_events"", ""params"":[155], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746679243,"{""result"":[{""id"":156,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3123020,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746679250,504676256,"{""method"":""get_events"", ""params"":[156], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746689249,"{""result"":[{""id"":157,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3108764,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746689263,216439182,"{""method"":""get_events"", ""params"":[157], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746699298,"{""result"":[{""id"":158,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3149460,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746699309,-1664502756,"{""method"":""get_events"", ""params"":[158], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746709334,"{""result"":[{""id"":159,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3118044,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746709342,-1235872948,"{""method"":""get_events"", ""params"":[159], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746719338,"{""result"":[{""id"":160,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3120384,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746719351,491215215,"{""method"":""get_events"", ""params"":[160], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746729381,"{""result"":[{""id"":161,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3096152,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746729393,835570229,"{""method"":""get_events"", ""params"":[161], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746739428,"{""result"":[{""id"":162,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3105100,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746739440,-1823404417,"{""method"":""get_events"", ""params"":[162], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746749428,"{""result"":[{""id"":163,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3093780,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746749441,771041822,"{""method"":""get_events"", ""params"":[163], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746759479,"{""result"":[{""id"":164,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3116144,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746759501,1051208704,"{""method"":""get_events"", ""params"":[164], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746769526,"{""result"":[{""id"":165,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3127568,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746769538,1666352608,"{""method"":""get_events"", ""params"":[165], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746779573,"{""result"":[{""id"":166,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3127200,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746779592,281052058,"{""method"":""get_events"", ""params"":[166], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746789617,"{""result"":[{""id"":167,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3078048,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746789626,-1996028683,"{""method"":""get_events"", ""params"":[167], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746799667,"{""result"":[{""id"":168,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3099268,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746799681,-1604159629,"{""method"":""get_events"", ""params"":[168], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746809671,"{""result"":[{""id"":169,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3114892,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746809684,379232639,"{""method"":""get_events"", ""params"":[169], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746819721,"{""result"":[{""id"":170,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3091860,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746819737,2121381521,"{""method"":""get_events"", ""params"":[170], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746829722,"{""result"":[{""id"":171,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3124036,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746829735,205193673,"{""method"":""get_events"", ""params"":[171], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746839770,"{""result"":[{""id"":172,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3085976,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746839782,-900358032,"{""method"":""get_events"", ""params"":[172], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746849772,"{""result"":[{""id"":173,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3007816,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746849785,-1545790005,"{""method"":""get_events"", ""params"":[173], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746859817,"{""result"":[{""id"":174,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3044756,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746859824,-815004083,"{""method"":""get_events"", ""params"":[174], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746869864,"{""result"":[{""id"":175,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3012796,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746869879,-463237615,"{""method"":""get_events"", ""params"":[175], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746879865,"{""result"":[{""id"":176,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3018148,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746879876,-1892601784,"{""method"":""get_events"", ""params"":[176], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746889908,"{""result"":[{""id"":177,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3018292,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746889916,1460150136,"{""method"":""get_events"", ""params"":[177], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746899912,"{""result"":[{""id"":178,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3008620,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746899926,1028654653,"{""method"":""get_events"", ""params"":[178], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746909960,"{""result"":[{""id"":179,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":2990048,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746909974,371053403,"{""method"":""get_events"", ""params"":[179], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746919967,"{""result"":[{""id"":180,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3011156,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746919989,2129602475,"{""method"":""get_events"", ""params"":[180], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746930012,"{""result"":[{""id"":181,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3064112,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746930022,208999369,"{""method"":""get_events"", ""params"":[181], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746940054,"{""result"":[{""id"":182,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":2957556,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746940066,-629106608,"{""method"":""get_events"", ""params"":[182], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746950101,"{""result"":[{""id"":183,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3036340,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746950126,361777286,"{""method"":""get_events"", ""params"":[183], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746960142,"{""result"":[{""id"":184,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3010860,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746960159,-1790648908,"{""method"":""get_events"", ""params"":[184], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746970194,"{""result"":[{""id"":185,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":2991204,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746970200,-2141873407,"{""method"":""get_events"", ""params"":[185], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746980199,"{""result"":[{""id"":186,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":2994260,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746980209,-785247096,"{""method"":""get_events"", ""params"":[186], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642746990232,"{""result"":[{""id"":187,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":2986896,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642746990241,-1586808608,"{""method"":""get_events"", ""params"":[187], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642747000279,"{""result"":[{""id"":188,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":2990320,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642747000291,1950164744,"{""method"":""get_events"", ""params"":[188], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642747010322,"{""result"":[{""id"":189,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3027312,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642747010331,58712748,"{""method"":""get_events"", ""params"":[189], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642747020324,"{""result"":[{""id"":190,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3002960,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642747020332,588656552,"{""method"":""get_events"", ""params"":[190], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642747026428,"{""result"":[{""id"":191,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3329192,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642747025387,-483911546,"{""method"":""set_client_state"", ""params"":[{},{""workbenchp"":{""rightpanesize"":{""panelwidth"":1584, ""windowwidth"":1600, ""splitterpos"":[736]}}},{""windowlayoutstate"":{""left"":{""splitterpos"":324, ""topwindowstate"":""NORMAL"", ""panelheight"":840, ""windowheight"":878}, ""right"":{""splitterpos"":528, ""topwindowstate"":""NORMAL"", ""panelheight"":840, ""windowheight"":878}}}], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642747025414,"{""result"":null,""ep"":""false""}"
1642747025895,1814350424,"{""method"":""set_workbench_metrics"", ""params"":[{""consoleWidth"":98, ""buildConsoleWidth"":85, ""graphicsWidth"":734, ""graphicsHeight"":481, ""devicePixelRatio"":2}], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642747025900,"{""result"":null,""ep"":""false""}"
1642747026432,302337082,"{""method"":""get_events"", ""params"":[191], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1642747030323,"{""result"":[{""id"":192,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":7568928,""provider"":6},""used"":{""kb"":3153136,""provider"":6},""process"":{""kb"":177756,""provider"":5}}}],""ep"":""false""}"
1642747030326,1306460519,"{""method"":""get_events"", ""params"":[192], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",0
`

### Describe the behavior you expected
no flicker of ui

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by matguidi** [comment]
Do you have an Intel GPU? It might have to do with [this](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731) bug in mesa which causes flickering in several apps using using OpenGL rendering.

**Comment by mikebessuille** [comment]
See the previous comment related to mesa.  If that's not the problem, would you be willing to try out a build of our electron-based desktop, and let us know if the problem persists?
You can get a daily build of the Electron desktop (for testing purposes, not ready for production yet) at an URL for your distro, similar to:
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/bionic/
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/rhel8/
etc...
