### ISSUE TITLE
Test RStudio IDE on Windows 11 and document

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10402]
Mainly, I'm thinking that we should report "Windows 10+" in our download page at https://www.rstudio.com/products/rstudio/download/#download.

<img width="1149" alt="Screen Shot 2022-01-20 at 10 41 00 AM" src="https://user-images.githubusercontent.com/1976582/150401574-ef606527-4e2c-4ba0-95d1-df8484ea0d7a.png">

**Comment by MariaSemple** [comment]
I think we should set it to `Windows 10/11` to be explicit. We can do this in the downloads.json.erb in rstudio/rstudio-com.

**Comment by mikebessuille** [comment]
Prefer to say "Windows 10/11" to avoid the expectation that we support, say, Windows 12 if we haven't tested it.

**Comment by mikebessuille** [comment]
I believe this is already done for PT.  @AndrewMcClain I think you updated a webpage or installer to indicate this?  Is there anything else needed for SW?

**Comment by MariaSemple** [comment]
I don't believe anything else should be needed.

**Comment by mikebessuille** [comment]
PT pages still show Windows 10.  Dailies page shows Windows 10+

**Comment by AndrewMcClain** [comment]
I have an update in a pull request that will update the download page to show Windows 10/11
https://github.com/rstudio/rstudio-com/pull/118

**Comment by AndrewMcClain** [comment]
downloads page now show Windows 10/11

**Comment by mikebessuille** [comment]
Great!  closing this as we're now testing with Windows 11 and the downloads pages look correct.
