### ISSUE TITLE
More zoom levels /  custom zoom %

### ISSUE THREAD

**Issue by karlmakepeace** [rstudio/rstudio#10407]
https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/node/desktop/src/main/gwt-window.ts#L26

Can more zoom levels be added?
The jump from 75% -> 50% is too great.
Suggest 5% or 10% increments from 150% --> 50%

Alternatively (better), let the user set a custom zoom %.

**Comment by ronblum** [comment]
@karlmakepeace Thank you for the suggestion!
