### ISSUE TITLE
The server and workbench post install scripts are making the wrong rstudio-server log directory

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#10419]
### System details

    RStudio Edition : Server/Workbench
    RStudio Version : ghost-orchid

### Steps to reproduce the problem

Install the server or workbench versions and notice that the directory `/var/log/rstudio-server` was created. It should be:

`/var/log/rstudio/rstudio-server/`

### Describe the problem in detail

We make this log directory up front to eliminate a race condition where nginx can fail to start if this directory does not exist.  The first time rstudio-server starts, it will create the directory, and I think it will attempt to restart nginx a few times if it fails to start so it might not be a real problem. But right now, we are creating this directory that is not used and might confuse some users and the first time, you might see errors regarding nginx failing to start in the logs.

**Comment by MariaSemple** [comment]
I noticed something related to this a while ago and might have fixed it: https://github.com/rstudio/rstudio/blob/64ee43493bae9754916b9f18f91fe79a6ba9b8a9/package/linux/debian-control/postinst.in#L46

**Comment by astayleraz** [comment]
### Verified Fixed
    RStudio Edition    :  Workbench
    RStudio Version(s) : 2023.03.0-daily+274.pro6
    OS Version         : ubuntu20, rhel8

### Environment details
 


### Test scenario(s) 

I verified I do not see the directory /var/log/rstudio-server

![Screen Shot 2023-01-27 at 1 19 46 PM](https://user-images.githubusercontent.com/1482677/215197202-648e6084-e64d-4aa7-bbcf-643db8a40f4d.png)

### Automated tests 

This did not seem like a good candidate to automate with selenium but it can be added if we think there is value adding it.
