### ISSUE TITLE
R runtime is accessed from offline thread in onDetectChanges callback

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#10424]
### System details

    RStudio Edition : All
    RStudio Version : Ghost orchid and above

### Steps to reproduce the problem

After each RPC request, even when not on the main thread, the onDetectChanges event is sent. This event is handled by the SessionEnvironment.cpp callback that calls an R runtime method: rstudio::r::sexp::listEnvironment(), that uses R_lsInternal - an internal R function that should only be used on the main thread. 

Unfortunately this happens to run without errors most of the time, but intermittently when I run all offlineable requests on a separate thread, and for various automated tests I see this message from R:

`*** recursive gc invocation`

Presumably, this call is made while the main thread is in the midst of a GC and the R_in_gc flag is set that triggers an error when an attempt to access the heap is made from the offline thread.

Most recently it took two runs of the test suite: test_VisualMarkdownEditor to hit this problem (it showed up during different tests).  

### Describe the behavior you expected

* We should not try to refresh the environment from R if not on the main thread. 
* The listEnvironment function (and probably others in RSexp.cpp) should have an ASSERT_MAIN_THREAD directive so we catch problems like this more quickly
* Need to go through other onDetectChanges event listeners to see if any of them can access the main thread

**Comment by MariaSemple** [comment]
Verified fixed.

I was not able to reproduce with 4 test runs on `2022.02.0-preview+401.pro1`, and @ronblum was able to reproduce on `2022.02.0-preview+386.pro2`
