### ISSUE TITLE
completion popup doesn't exit when clicking into active code chunk in visual mode

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10420]
### System details

    RStudio Edition : 2022.2.0.389
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.1
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

1. Open the visual editor,
2. Begin editing an R code chunk,
3. Do something to trigger completions,
4. Try to dismiss completions by clicking somewhere in that chunk.

### Describe the problem in detail

The cursor position moves on mouse click, but the completion popup is not dismissed.

### Describe the behavior you expected

Completion popup should be dismissed if the cursor moves up or down during a completion 'session'.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin21.1.0 (64-bit)
Running under: macOS Monterey 12.1

Matrix products: default
LAPACK: /opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.1.2  Matrix_1.4-0    tools_4.1.2     rstudioapi_0.13
 [5] Rcpp_1.0.8      reticulate_1.23 grid_4.1.2      jsonlite_1.7.3 
 [9] png_0.1-7       lattice_0.20-45
```

</details>

**Comment by mikebessuille** [comment]
@kevinushey is this a problem in the released PT?

**Comment by kevinushey** [comment]
I believe this was fixed with https://github.com/rstudio/rstudio/commit/58fe40ddc81775297dd1f43298606e991a95c65c (and that commit is part of the PT release).
