### ISSUE TITLE
When using single quotes around a multi-character string in Rcpp, Rstudio encounters a fatal error in R instead of flagging the C++ error

### ISSUE THREAD

**Issue by lfmcmillan** [rstudio/rstudio#10421]
### System details

    RStudio Edition :  Desktop
    RStudio Version :   2021.09.2 Build 382
    OS Version      :  Windows 10 Pro 21H1 19043.1466
    R Version       :  4.1.2

Rstudio:
2021.09.2 Build 382
© 2009-2022 RStudio, PBC
"Ghost Orchid" Release (fc9e2179, 2022-01-04) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem

Start new RStudio Project with Rcpp. Add a new C++ file, and make this the contents:

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector timesTwo(NumericVector x) {
    if (x['try'] == 1) {
        x[0] += 5;
    }
  return x * 2;
}

/*** R
timesTwo(42)
*/
```

Then use Rcpp::sourcecpp to source this file.

### Describe the problem in detail

As soon as you try to source this file, you get an instant fatal error in R. And while you're editing the file, the 'try' string is highlighted the same as "try".

### Describe the behavior you expected

At the point of trying to compile the C++, I would expect to see RStudio flagging the problem in the C++, namely that "try" should have double quotes around it instead of single quotes, instead of crashing.

At the very least, it would help to have different syntax highlighting for 'try' and "try" in C++ (they're equivalent in R, but not in C++, and C++ already has different syntax highlighting rules so it should be possible to add a different rule for strings in C++.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [!] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

I tried running a diagnostics report, by pasting the necessary command into Windows Run just after I had the fatal error in R, but got the following error:

2022-01-24T20:41:30.578680Z [rsession-LFM] ERROR r error 4 (R code execution error) [errormsg: Error in file(file, if (append) "a" else "w") : |||  cannot open the connection|||]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::r::exec::`anonymous-namespace'::evaluateExpressionsUnsafe(struct SEXPREC *,struct SEXPREC *,struct SEXPREC **,class rstudio::r::sexp::Protect *,enum rstudio::r::exec::`anonymous-namespace'::EvalType) src/cpp/r/RExec.cpp:194; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::session::module_context::sourceDiagnostics(void) src/cpp/session/SessionModuleContext.cpp:2366

**Comment by romainfrancois** [comment]
I don't think this is an rstudio specific error, when running the file outside of rstudio, I'm also getting a segfault:

```
% Rscript -e "Rcpp::sourceCpp('/tmp/test.cpp')"
test.cpp:6:9: warning: multi-character character constant [-Wmultichar]
  if (x['try'] == 1) {
        ^
1 warning generated.

> timesTwo(42)

 *** caught segfault ***
address 0x7fde47431468, cause 'memory not mapped'

Traceback:
 1: .Call(<pointer: 0x10855e680>, x)
 2: timesTwo(42)
 3: eval(ei, envir)
 4: eval(ei, envir)
 5: withVisible(eval(ei, envir))
 6: source(file = srcConn, local = env, echo = echo)
 7: Rcpp::sourceCpp("/tmp/test.cpp")
An irrecoverable exception occurred. R is aborting now ...
zsh: segmentation fault  Rscript -e "Rcpp::sourceCpp('/tmp/test.cpp')"
```

The problem is that this is a mere compile *warning* so I'm not even sure this can be considered an Rcpp problem, the code does compile, and the `timesTwo` exists, but at runtime, you get a segfault. 

Maybe Rcpp developers would have more ideas: https://github.com/RcppCore/Rcpp/issues

**Comment by romainfrancois** [comment]
I see this diagnostic: 

![image](https://user-images.githubusercontent.com/2625526/150976909-c0b753cc-9b3e-416c-a240-2ef662a9db2a.png)

**Comment by romainfrancois** [comment]
``` r
Rcpp::sourceCpp("/tmp/test.cpp")
timesTwo
#> function (x) 
#> .Call(<pointer: 0x10e95a680>, x)
```

**Comment by ronblum** [comment]
Note: I can reproduce this, but I only run into it by running `Rcpp::sourcecpp()` from the console. If I click on "Source" in the Source Pane, or run this with either method in a file outside of the project, the code runs as expected. (I still get a warning, though.)
