### ISSUE TITLE
Create unique locator ID for date field in new R Markdown file dialog

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10433]
When creating a new R Markdown document <kbd>File -> New File -> R Markdown</kbd>, the pop-up dialog contains both an author and a date field. However, the locater ID is duplicated—both are `rstudio_new_rmd_author`. Can we change the locater ID for the date field to something like `rstudio_new_rmd_date`?

**Comment by kevinushey** [comment]
@romainfrancois, do you want to take a look? Is this related to your recent PR?
