### ISSUE TITLE
Electron font-selection logic

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10438]
The fonts used by Electron are currently hardcoded, e.g. here: https://github.com/rstudio/rstudio/blob/spotted-wakerobin/src/node/desktop/src/renderer/desktop-info-bridge.ts

Need to implement logic for selecting these; at a minimum replicate what we have in the Qt version, but also consider #4134 and #8659.

**Comment by timtmok** [comment]
https://github.com/rstudio/rstudio/issues/10801 will address validating the values written.

**Comment by kevinushey** [comment]
Almost looks ready. One thing I noticed is that one cannot select different font styles for a particular installed font on macOS; only the "regular" font is available.

---

## Ubuntu 20.04

### Electron

<img width="185" alt="Screen Shot 2022-03-28 at 4 48 42 PM" src="https://user-images.githubusercontent.com/1976582/160505443-fa68b52b-d1b7-4f95-b01c-8efe81e6bed1.png">

### Qt

[TBA]

## macOS

### Electron
<img width="187" alt="Screen Shot 2022-03-28 at 4 50 03 PM" src="https://user-images.githubusercontent.com/1976582/160505577-2ca0987a-c8e9-401b-890a-72482f785c1c.png">

### Qt

<img width="193" alt="Screen Shot 2022-03-28 at 4 50 48 PM" src="https://user-images.githubusercontent.com/1976582/160505648-add49bac-283c-49bd-b594-a31af70b2172.png">

## Windows

### Electron

<img width="186" alt="Screen Shot 2022-03-28 at 4 57 58 PM" src="https://user-images.githubusercontent.com/1976582/160506372-88ad568c-93a2-4b1e-9b4c-6bd48f422ab4.png">

### Qt

<img width="189" alt="Screen Shot 2022-03-28 at 4 58 43 PM" src="https://user-images.githubusercontent.com/1976582/160506428-4c792ce8-dff9-4868-8dab-8ce788ba43a6.png">

**Comment by timtmok** [comment]
I think the native implementation provided in `node-system-fonts` could be patched to return fonts with their style options. I'm checking Apple docs to see if it's possible to get a font list similar to what Qt was providing.
