### ISSUE TITLE
Pass R code execution error messages to the RPC instead of always replacing with "R code execution error"

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#10443]
When an executing R function hits an error, an error gets passed to the RPC, and can be accessed on the frontend to display the error to the user. Unfortunately, the message that actually gets passed, no matter what the R error message should happen to be, is often just [R code execution error](https://github.com/rstudio/rstudio/blob/8f85b6b8ed4e7db1ac167b2007d17e26c947e4fd/src/cpp/r/RErrorCategory.cpp#L57). The actual error message and location get lost. It would be helpful if the actual error info in errc::CodeExecutionError could get passed more easily into the RPC for access on the frontend, in cases where it would be helpful to display some or all of the error to the user.

**Comment by gtritchie** [comment]
I verified this new behaviour on build 2022.06.0-daily+239 on MacOS, using the steps described in #10793. Got the detailed error message. Closing.
