### ISSUE TITLE
Implement RStudio Electron command-line switches

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10448]
RStudio Desktop (Qt) has several command-line switches:

* --run-diagnostics
* --session-server
* --session-url
* --use-temp-cookies
* --version

RStudio Electron adds these:

* --version-json
* --log-level
* --session-delay
* --session-exit

These are implemented in an ad-hoc fashion; follow the trail from here: [application.ts](https://github.com/rstudio/rstudio/blob/50602bb32574b0922d52677376b60912fa3228ca/src/node/desktop/src/main/application.ts#L43-L52).

Since adding in electron-forge these don't seem to work, at least in a developer configuration (haven't tried against a package build). See also: #9459, #9460.

Some are not implemented yet (session-server, session-url, use-temp-cookies are pro-only).

We should:

* fix so command-line switches work again (in dev config and package build)
* consider adding a --help switch to show usage info (nice to have)
* consider using an existing command-line parsing package such as http://yargs.js.org/ rather than manually parsing these things

**Comment by matheustavaresdev** [comment]
We can reference them via `process.argv`, not sure if bringing `yargs` would be of much benefit. I will investigate. Also, as we run it via `yarn start`, we should use for example `yarn start -- -- --version-json` for passing through those arguments. I will work on detecting and getting them on `application.ts` and when it's done I will get in touch for further implementation needs and how to test!

**Comment by gtritchie** [comment]
Confirmed.
