### ISSUE TITLE
Implement opt-in for showing non-English UI

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10455]
Upon merging of [PR 10358](https://github.com/rstudio/rstudio/pull/10358) RStudio (desktop and server) will show French localized UI if the user's OS language is French (desktop) or if French has a higher-priority in their browser languages than English (Server).

The French UI is considered an experimental feature at this time, so we need to implement an opt-in approach instead of solely relying on external settings (os/browser).

**Comment by gtritchie** [comment]
Seeing an issue where the UI loads twice at startup (at least with Electron desktop). Moving back to in-progress while I work on a fix.

**Comment by gtritchie** [comment]
https://github.com/rstudio/rstudio/commit/6a13c2123d07ef2314236667d77c5b91e32536f8 fixes the reload problem for English. It is still loading twice when French UI is selected (in Electron) due to failure to persist browser local storage. Looking into that.

**Comment by gtritchie** [comment]
Now working as expected for Server and Electron desktop. Qt-desktop still has the extra GWT load when UI is set to French; that is tracked here: https://github.com/rstudio/rstudio/issues/10993

**Comment by romainfrancois** [comment]
Verified with version: 

```
RStudio 2022.06.0-daily+351 "Spotted Wakerobin" Daily (ab19e471486aa89e6d350db4e93027845e0847f2, 2022-05-03) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
````

from English to French, with the labels in the target language in parenthesis: 

<img width="531" alt="image" src="https://user-images.githubusercontent.com/2625526/166663334-2a8b8ede-beb4-4fe0-87a8-66c9c2357f7a.png">

Ok, or apply restarts the ide with some French: 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/2625526/166663574-b18dcdab-2786-4d0b-b7ef-81c08e7a66e7.png">

Then the choices are presented in French: 

<img width="542" alt="image" src="https://user-images.githubusercontent.com/2625526/166663731-6b27865e-1c66-4f2e-8da1-9f0a9b4ff850.png">

I'll do a pull request to translate "User Interface Language" though. 

In devmode, this triggers a recompile, but I guess it's ok.

**Comment by romainfrancois** [comment]
Creating the `/etc/rstudio/rstudio-prefs.json` with : 

```
{
    "ui_language": "fr"
}
```

does indeed bring 🇫🇷 when restarting the desktop ide. 

Not with devmode though ? Does this answer to a different file ? I'm still getting: 

```
     [java]    Job org.rstudio.studio.RStudioSuperDevMode_1_0
     [java]       starting job: org.rstudio.studio.RStudioSuperDevMode_1_0
     [java]       binding: locale=en
     [java]       binding: rstudio.desktop=false
     [java]       binding: rstudio.electron=false
     [java]       binding: rstudio.remoteDesktop=false
```

**Comment by kevinushey** [comment]
For devmode, we set up the locale property here:

https://github.com/rstudio/rstudio/blob/c260961b0576f90980fe5bc6e2e7e01a72f7584a/src/gwt/src/org/rstudio/studio/RStudio.gwt.xml#L152-L156

But we don't set up any devmode-friendly method of reading and using the default locale, so I think that ends up taking precedence.

Compare with 'rstudio.desktop', where we inject a bit of JavaScript to figure out what the property value should be.

https://github.com/rstudio/rstudio/blob/c260961b0576f90980fe5bc6e2e7e01a72f7584a/src/gwt/src/org/rstudio/studio/RStudio.gwt.xml#L21-L31
