### ISSUE TITLE
Keyboard Shortcut to Replace "\" with "/" on a line

### ISSUE THREAD

**Issue by abfleishman** [rstudio/rstudio#10453]
# Feature Requested
In windows, when you copy a file path from Windows Explorer (say the path to a data file you want to read), the slashes in the path are in the wrong direction.  I lose time and have anguish every time I have to edit those slashes manually.  If there was a keyboard shortcut, say `Ctrl` + `\`,  to string replace the `\` with `/`  on the cursor line OR in the current selection, I would gain hours of my life back every year.  

Please consider adding this feature

# Alturnative idea
Of course, the other idea would be to have a keyboard shortcut to paste paths that auto-changes slashes to the correct direction.  This could be one better if normal paste did this by "sensing" that you were pasting paths but that sounds complicated, and there are lots of opportunities for mistakes.

# Similar open issues but different
#4572

**Comment by kevinushey** [comment]
This seems like it would be a good candidate for an RStudio Addin: https://rstudio.github.io/rstudioaddins/

**Comment by abfleishman** [comment]
There are several steps here but @kevinushey you were on to something! 
Juraj Sofranko (@sfr)  has written a Rstudio adding to do this, see (sfr/RStudio-Addin-Snippets)[the https://github.com/sfr/RStudio-Addin-Snippets] and specifically the function they are using,  (flip.slash)[https://github.com/sfr/RStudio-Addin-Snippets/blob/master/R/flip.slash.R]. 

By installing this package, and then using a custom keyboard shortcut pointing at the addin, I can get what I was looking for (mostly).  The only issue is if slash direction is mixed it doesn't work as I need it because it just switches from whatever direction it is to the other direction.  

Also, it is many steps to set up so when moving around to many VMs/workstations it will be a bit of a pain.  
```
devtools::install_github("sfr/RStudio-Addin-Snippets", type = "source")
```

**Comment by sfr** [comment]
@abfleishman, if there is a bug in the  [flip.slash](https://github.com/sfr/RStudio-Addin-Snippets/blob/master/R/flip.slash.R) function, please open an issue in the [sfr/RStudio-Addin-Snippets](https://github.com/sfr/RStudio-Addin-Snippets) project. Or is the functionality not exactly what you expected? Because it was originally meant to copy paths in Windows.
