### ISSUE TITLE
Ace editor preview doesn't get monospace font

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10463]
### System details

    RStudio Edition : 2022.6.0.40
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.1
    R Version       : R version 4.1.2 (2021-11-01)

---

<img width="608" alt="Screen Shot 2022-01-27 at 4 06 37 PM" src="https://user-images.githubusercontent.com/1976582/151463954-ef07df17-843c-48e4-a24f-5bda85aa2e66.png">

**Comment by gtritchie** [comment]
Related to: #10438

**Comment by timtmok** [comment]
I'll take a look at this while looking at #10438

**Comment by kevinushey** [comment]
Verified fixed in RStudio 2022.06.0-daily+242 "Spotted Wakerobin" Daily (65af00457f533e066883e4a96833153a68c4aa4b, 2022-03-28) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.06.0-daily+242 Chrome/98.0.4758.109 Electron/17.1.2 Safari/537.36.

<img width="607" alt="Screen Shot 2022-03-28 at 4 17 28 PM" src="https://user-images.githubusercontent.com/1976582/160502832-30a3d43e-5d38-4e88-b7f3-b50157ffd9ae.png">
