### ISSUE TITLE
quarto yaml chunk labels don't show up in scope widget 

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#10473]
For example, see:

<img width="717" alt="Screen Shot 2022-01-29 at 1 54 08 PM" src="https://user-images.githubusercontent.com/104391/151673828-3798064e-ef50-4e43-a5cc-d6edb0724931.png">

This screenshot is in source mode. The same issue also occurs in visual mode (don't recall if there is a distinct codepath in play there or not).

Note you can see that some accommodation was made for parsing quarto-style labels here: https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java#L1078-L1079

**Comment by jjallaire** [comment]
Note that this affects the scope widget as well as the document outline at right.

**Comment by mikebessuille** [comment]
I'm going to move this to Spotted Wakerobin, as we just started certification on Friday so we only want to accept critical bugs into PT at this point

**Comment by romainfrancois** [comment]
I'll pick this one up, this is same territory as https://github.com/rstudio/rstudio/pull/11108

**Comment by jgutman** [comment]
With setting: Show in Document Outline set to "Sections and Chunks"

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/7817881/168607491-6aad2184-f305-463c-9bca-9d928034f332.png">

Verified in 2022.6.0.406 RStudio Desktop on MacOS 12.3.1
