### ISSUE TITLE
Review/implement copy/paste callbacks for Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10486]
This batch of desktop callbacks related to copy/paste is unimplemented in Electron. Figure out if they need to be implemented and implement them. Copy/paste/undo seems to be working currently without triggering these (probably through Electron built-in behavior and command roles).

See also #10485 for the clean_clipboard callback, and #10484 which mentions the menuItemRoles in a different context.

https://github.com/rstudio/rstudio/blob/b9cfb0cead45532141eb11bb772ff501a047bd51/src/node/desktop/src/main/gwt-callback.ts#L166-L207

**Comment by kevinushey** [comment]
Somewhat related; the undo + redo menu items don't seem to do the right thing when Ace is focused. (They seem to work when other text fields are focused, e.g. our various search widgets.)

**Comment by matheustavaresdev** [comment]
After many tests, the menu items and keyboard shortcuts for this seems to be working as they should.  I was not able to test the `Ace` that @kevinushey mentioned though.

**Comment by timtmok** [comment]
I've tried Mac and Windows so far and there are some inconsistencies with the context menu, Edit menu, and keyboard shortcut behaviour.

Windows
* Edit > Undo doesn't seem to work but Ctrl+Z does
* Edit > Redo doesn't work either but Ctrl+Shift+Z does, Ctrl+Y as labeled does not

Mac
* Edit > Undo/Redo doesn't work at all, shortcuts work as labeled
* Edit menu and context menu copy/paste are always enabled even if nothing is selected or clipboard is empty (`pbcopy < /dev/null` to clear clipboard)
* Outside of the Ace editor, copy/paste behaves mostly normally. The odd part is the console only enables context menu paste if the menu is opened where the cursor is located, not anywhere in the console.

**Comment by kevinushey** [comment]
Verified fixed on Ubuntu 20.04 with RStudio 2022.06.0 build 242.
