### ISSUE TITLE
Source diagnostic gutter symbols are different in source editor versus visual editor, with some symbols missing

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#10483]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0-preview+412
    OS Version      : Mac OS 12.1 M1 
    R Version       : R-devel 4.2.0 (64-bit)

### Steps to reproduce the problem

Create an Rmd file with an R code check with some diagnostic issues in it. All R diagnostics are enabled.
![image](https://user-images.githubusercontent.com/7817881/152016735-66b6968f-b0a2-4bc1-93d7-747f67c01029.png)
![image](https://user-images.githubusercontent.com/7817881/152016799-ea5c6e63-28ea-48ee-9880-2b3bad46f22a.png)

Code chunk:
~~~
```{r}
print(123 digits=3)
x <- yy

purrr::map ( 1 : 5)
```
~~~

In the source editor, we see 3 diagnostic marker icons displayed in the gutter.
ERROR (red X in circle): with the tooltip message `unexpected token 'digits'` and `unexpected token '='`
WARNING (yellow exclamation point in triangle): with the tooltip message `no symbol named 'yy' in scope`
INFO (blue `i` in circle): with the tooltip message `unnecessary whitespace` and `unexpected whitespace around extraction operator`

However, when we switch over to the visual editor 
1) At first, there are no diagnostic markers displayed. However if we edit and save the file, they do appear.
2) For lines which had multiple diagnostic messages associated with them in the source editor, only the last one appears.
3) The INFO (blue `i` in circle) symbol does not appear at all. ERROR (red X in circle) and WARNING (yellow exclamation point in triangle) do appear as before though.

![image](https://user-images.githubusercontent.com/7817881/152018067-c4ba9e4c-f213-4526-8116-c7b1b5a3e3b8.png)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
![image](https://user-images.githubusercontent.com/7817881/152037584-70de35b2-0c82-4937-86a8-68f704c26f65.png)

![image](https://user-images.githubusercontent.com/7817881/152038053-d887b165-78ec-4801-871c-326128115b01.png)


Note that the info `i` marker does appear in some, but not all cases. It doesn't seem to appear for style diagnostics/whitespace (although the message does appear if you hover over where the nonexistent icon should be.

**Comment by jgutman** [comment]
Note: When the option to display line numbers in visual mode code chunks is enabled (Global Options > RMarkdown > Visual > Show line numbers in code blocks), the blue `i` icons for whitespace issues appear visible, and lines with multiple code dx messages show all associated messages. 

![image](https://user-images.githubusercontent.com/7817881/152178878-19a8e662-f060-4e31-b585-256683d6def1.png)
 
 However when the line number option is unchecked again, these issues return.
 
 
![image](https://user-images.githubusercontent.com/7817881/152179022-e2965e9f-8af5-443d-a4b8-9bef352254a7.png)

**Comment by timtmok** [comment]
At least it was already like this in Prairie Trillium before the source marker changes to support ANSI codes! It's likely missing an update to the gutter markers after linting. It's a different code path since visual mode has to render the code chunks instead of all the code together.

**Comment by gtritchie** [comment]
We should check if this is still a problem, was opened a while ago.

**Comment by ronblum** [comment]
This is still an issue. Note that because of #10984, I used the following: 

````
y <- 1
y
y
y
y
y
y
y
y
y
y

print(123 digits=3)
x <- yy
print(b)
purrr::map ( 1 : 5)
b <- "Hello world"
```
````

**Comment by kevinushey** [comment]
I'm seeing something probably related: in source mode, the markers no longe render on the correct line.

<img width="264" alt="Screen Shot 2022-05-09 at 1 01 53 PM" src="https://user-images.githubusercontent.com/1976582/167488357-060c243b-1270-4652-b4a9-fc028ec2b0da.png">

**Comment by jgutman** [comment]
Yep we have a separate issue for that as well here: https://github.com/rstudio/rstudio/issues/10984

There are a handful of issues with this part of the code right now so @timtmok and I will collaborate on sorting them out

**Comment by jgutman** [comment]
In my opinion, this may not be a high priority for backport, but since we have a PT branch with some changes it could be worth throwing it on there for whenever the next patch is cut

**Comment by timtmok** [comment]
Looks like the missing gutter marker is because the marker type (style) isn't handled. This only occurs when the visual mode has line numbers disabled. With line numbers enabled, the gutter markers are rendered the same way as in source mode (no line numbers hides the gutter so we create a virtual gutter to show markers).

**Comment by jgutman** [comment]
Verified in RStudio Desktop (Electron) 2022.06.0-daily+439 on Mac OS

<img width="822" alt="image" src="https://user-images.githubusercontent.com/7817881/170782504-ee8ce1c0-3d7a-46bf-859c-1e9eb63645d9.png">
