### ISSUE TITLE
Implement Electron cleanClipboard callback

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10485]
In the Electron IDE, invoke "Copy" (e.g. in the Console) via right-click menu, or keyboard shortcut, or Edit / Copy, and you'll get a dialog saying: `desktop_clean_clipboard callback NYI`.

This needs to be implemented here: https://github.com/rstudio/rstudio/blob/b2a98ae29ca3a7218fd4d4f8ba19fcc763a2fd23/src/node/desktop/src/main/gwt-callback.ts#L410-L412

The C++ implementation (Qt) for MacOS is here:
https://github.com/rstudio/rstudio/blob/b2a98ae29ca3a7218fd4d4f8ba19fcc763a2fd23/src/cpp/desktop/DesktopGwtCallback.cpp#L1041-L1108

For other platforms this callback is a no-op.

**Comment by kevinushey** [comment]
QA Notes -- note that this PR affects macOS only.

- Select some text in the Console history (e.g. using the mouse, and then clicking and dragging to create a selection),
- Press Ctrl + C to copy the text to the clipboard,
- Open the Pasteboard Viewer application (https://apps.apple.com/us/app/pasteboard-viewer/id1499215709?mt=12), and confirm that only a single entry is present, with the copied text.

<img width="619" alt="Screen Shot 2022-02-22 at 2 43 31 PM" src="https://user-images.githubusercontent.com/1976582/155232044-8fff0aba-5221-4d2a-971b-9d00a0923151.png">

**Comment by gtritchie** [comment]
Verified with build 2022.06.0-daily+244 on MacOS 12.3.
