### ISSUE TITLE
`str_c()` can't work normally in Japanese characters, at RStudio-2021.09.2-382.

### ISSUE THREAD

**Issue by Doubt-0KB** [rstudio/rstudio#10502]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-2021.09.2-382
    OS Version      : Windows 10 x64
    R Version       : R version 4.1.2

### Steps to reproduce the problem

    str_c("文字", "化け")
    [1] "\u0095�\u008e\u009a\u0089�\u0082�"

### Describe the problem in detail

After updating to the latest version, stringr functions like `str_c()` can't use Japanese in RStudio.
At Rgui and RStudio-2021.09.1-372, this code works correct.

When I enter these characters normally, they will be displayed without any problem.

    "文字化け"
    [1] "文字化け"

And, this code gave the result I expected.

    paste0("文字", "化け")
    [1] "文字化け"

Here is the locale getting by `Sys.getlocale()`.

    Sys.getlocale()
    [1] "LC_COLLATE=Japanese_Japan.932;LC_CTYPE=Japanese_Japan.932;LC_MONETARY=Japanese_Japan.932;LC_NUMERIC=C;LC_TIME=Japanese_Japan.932"

I changed the locale and ran the code, and it worked fine (but I have no idea why it worked).

    Sys.setlocale("LC_ALL", "English_US")
    [1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
    
    str_c("文字", "化け")
    [1] "文字化け"

I think this is similar to #10451, and I reproduce the same problem.

    dir() #correctly displayed as "メモ.txt"
    [1] "繝｡繝｢.txt"

### Describe the behavior you expected

    str_c("文字", "化け")
    [1] "文字化け"

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It seems to work for me:

```
> library(stringr)
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 22581)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.4.0

loaded via a namespace (and not attached):
[1] compiler_4.1.3 magrittr_2.0.2 tools_4.1.3    stringi_1.7.6 
> str_c("文字", "化け")
[1] "文字化け"
```

Can you provide any other details? Or, do you see the same issue with the latest daily builds at https://dailies.rstudio.com?

**Comment by Doubt-0KB** [comment]
@kevinushey Yes, in the locale "English_United States.1252", it works correctly. But in "Japanese_Japan.932", it doesn't.
And in the latest daily builds, it works correctly.

**Comment by Doubt-0KB** [comment]
I'm so sorry for my mistake. When I checked about daily builds RStudio and Rgui, I used the machine with Windows11 installed.
I checked again in Windows10, and I confirmed it doesn't work as expected.

So, current situation is as follows.

- In Windows10,
    + RStudio : not work
    + Rgui : not work
    + RStudio(daily builds) : not work
- In Windows11,
    + RStudio : not work
    + Rgui : work
    + RStudio(daily builds) : work

Here is the sessionInfo.

```{r}
# Windows10
sessionInfo()

#> R version 4.1.3 (2022-03-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)

#> Matrix products: default

#> locale:
#> [1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932
#> [4] LC_NUMERIC=C                   LC_TIME=Japanese_Japan.932    
#> system code page: 65001
```


```{r}
# Windows11
sessionInfo()

#> R version 4.1.3 (2022-03-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 22000)

#> Matrix products: default

#> locale:
#> [1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932
#> [4] LC_NUMERIC=C                   LC_TIME=Japanese_Japan.932    
#> system code page: 65001
```

**Comment by yutannihilation** [comment]
> #> system code page: 65001

No idea what's happening, but I guess the problem is somehow related to the fact that the OS's default encoding (UTF-8) is different from that of the R session (CP932). I hope R 4.2, which will be released on this weekend, will save you...!

**Comment by kevinushey** [comment]
FWIW, I expect this issue should be resolved in the current daily builds of RStudio.

**Comment by Doubt-0KB** [comment]
I installed the newest R 4.2, and `str_c()` does not have any problems on both Windows10 and Windows11.
Thank you very much for your advises!
