### ISSUE TITLE
Option to turn off compression during import/export

### ISSUE THREAD

**Issue by anirban-mukherjee** [rstudio/rstudio#10511]
At the moment, RStudio Server uses compression when importing/exporting files (see https://support.rstudio.com/hc/en-us/articles/200713893-Uploading-and-Downloading-Files-in-RStudio-Workbench-or-RStudio-Server for details).

I suggest providing an option to turn off this feature and perhaps even changing the interface to accommodate this in a given upload/download.

When a large number of files are uploaded/downloaded then the archive/zip instruction runs in the background. In my experience, it is common for this function to cause RStudio server to hang if there is any problem with the compression/decompression and/or if the files are large and/or if there is a file system problem. This happens often in my experience (even when a server has >500 GB of RAM and tons of resources) perhaps due to the hard drive being a bottle neck and perhaps because the zip algorithm is single threaded --- the reasons likely differ in different cases. In my experience, anything more than 100 GB causes problems (I am on high-speed fiber optic so transferring 100 GB of data is reasonable).

Case in point --- I have a hung server (which is motivating me to file this issue) where the server has almost 1 TB of RAM, about 100 cores, and it has hung trying to export about 30 GB of RData files. My fault for not tar-ing the files and then downloading as  a single file or even sequentially downloading the files but this is just something so easy to trip up on. I would be fine with the server transferring the files one at a time without any compression or simultaneously as multiple downloads.

A possibility is to present an option to turn off compression when uploading/downloading in preferences. Another is to turn off compression if the files are too large and ask the user to explicitly create an archive using the terminal or to export the files simultaneously as separate downloads.

Also, I am guessing that often enough what is being uploaded/downloaded (as in my case) are already RData files which are compressed. If so then compression does not save bandwidth.

A final point --- RStudio is assuming compression can take place. That may not be true. In some cases, I run out of hard drive space because the original provisioning was not enough. That's perhaps another source of failure because one cannot compress >50% of the hard drive space and yet its reasonable enough to want to export that much data. In this case, the server is going to really get hung because it will try to compress for a long time before finally running out of space.

Sorry for this issue taking on the tone of a rant --- I just lost a bunch of time and effort because my instance has become unresponsive and R will need to be terminated. This is a simple issue but it is a pain point in my workflow and its just so easy to select 2 or more files instead of 1 to export.

**Comment by anirban-mukherjee** [comment]
@ronblum Thanks so much for the super gracious reply.

1. Sorry, I should have been clearer. I mean the former---I cannot do anything in the IDE when the files are being compressed. Moreover, it is typical that RStudio Server IDE "freezes" for the user in the sense that if the connection is closed/dropped then the same user can no longer connect to RStudio. One either has to wait for the compression to succeed/fail/timeout or one has to terminate R from the screen that shows up when R is unresponsive.

2. 

```
RStudio Edition : Server (open source license)
RStudio Version : 2021.09.2-382
OS Version      :  Debian Buster
R Version       : 4.1.2
```

**Comment by ronblum** [comment]
Note: For `qa repro` label, especially check both:
1. download of multiple files which together are very large, using 30 GB as a starting point
2. download of a large single file, using 30 GB as a starting point

**Comment by anirban-mukherjee** [comment]
I typically connect from Mac OS using Safari.

A single file should not cause any issue because that should not trigger the formation of an archive. If more than one file is selected for export then that automatically triggers the formation of a (compressed) archive.

I completely understand the prioritisation of bug reports and enhancement requests. I can't imagine I will personally interact with anyone else who has this issue so I will have to depend on the search engine genies to direct any such folks here but I completely understand RStudio's constraints and resource allocation; thank you for following up!

**Comment by ronblum** [comment]
Gotcha—thank you, I overstated my instructions for out internal QA. I'll update that. And thank you for all of your work and understanding—it help both us improve the product, and more importantly, fellow users!

**Comment by jmcphers** [comment]
A generic way to solve this would be to make it possible for server admins to specify the command used to create archives when exporting -- you could craft one that uses low/no compression, optimizes for performance, and wraps it all up in `nice` so it doesn't pre-empt more important tasks on the server.

**Comment by anirban-mukherjee** [comment]
Sure. My suggestion is to have an option in preferences that is the compression level in `gzip` with 1 corresponding to no compression and 9 corresponding to maximum compression, and a default of 6, which is the `gzip` default. I think that would suffice. If a different compression command/program is used by RStudio instead then options from that can be used instead. But your suggestion is more general than mine.

At any rate, wrapping in `nice` is an excellent idea regardless of whether or not there is an option to turn off compression. That can only enhance stability.

**Comment by jmcphers** [comment]
See also: https://github.com/rstudio/rstudio/issues/4345
