### ISSUE TITLE
Some characters as part of variable aren't formatted as a variable in the Console pane

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10515]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.1.463 and 2022.02.0+420/2
    OS Version      : MacOS 12.1 and Ubuntu 20.04 via Chrome
    R Version       : 3.6.3 & 4.1.2 (really, N/A)

### Steps to reproduce the problem

Do the following in the Console pane.

*Icelandic*

1. `iceland_ð <- c(1, 2, 3)` and click <kbd>Return</kbd>
2. `iceland_ð`
    - Note that `ð` isn't formatted as part of the variable name
3. Click <kbd>Return</kbd>
    - Note that `ð` is now formatted as part of the variable name    

<img width="200" alt="icelandic" src="https://user-images.githubusercontent.com/31009952/152810712-e69d104d-f7b8-44f9-ae33-1338f6dead17.png">

*French*

4. `accent_é <- c(4, 5, 6)` and click <kbd>Return</kbd>
5. `accent_é`
    - Note that `é` isn't formatted as part of the variable name
6. Click <kbd>Return</kbd>
    - Note that `é` is now formatted as part of the variable name    

<img width="196" alt="french" src="https://user-images.githubusercontent.com/31009952/152810765-190bc01d-9896-452f-a15d-a6614555add7.png">

### Describe the problem in detail

Some characters in variable names are not highlighted in the same way as the rest of its name (steps 2 and 5). Compare this to others which are working:

*Chinese (Simplified)*
7. `chinese_你 <- c(7, 8, 9)` and click <kbd>Return</kbd>
8. `chinese_你`
    - Note that `你` is formatted correctly

<img width="205" alt="chinese" src="https://user-images.githubusercontent.com/31009952/152810824-a750bd8c-af35-4603-9a67-13bb319b71f0.png">

### Describe the behavior you expected

The whole variable name should be highlighted as a variable.

Reproduced in
- RStudio Desktop 1.1.463 on MacOS 12.1
- RStudio Desktop 2022.02.0+420 on MacOS 12.1
- RStudio Server 2022.02.0+422 on Ubuntu 20.04 via Chrome on MacOS 12.1

Notes:
1) This is not a regression, as this is also the behavior in 1.1.463.
2) The two characters that don't work are extended ASCII, and the character that works is UTF-8.
3) Discovered as part of reproducing #10512.
4) Marking as triage to review the milestone.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This might be fixed in the latest daily builds -- we made some changes to improve tokenization of arbitrary unicode identifiers.

<img width="125" alt="Screen Shot 2022-03-30 at 11 40 16 AM" src="https://user-images.githubusercontent.com/1976582/160907723-0ccadda6-c83f-4f44-bad5-5dbadad73499.png">

**Comment by jonvanausdeln** [comment]
Verified on
2022.11.0-78
Windows11, MacOS 12.4, Ubuntu 22.04

Tested with various characters from different locale's and all highlighted correctly
