### ISSUE TITLE
Can Find in Files ignore the `revdep/cloud.noindex/` folder?

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#10529]
This is somewhat related to https://github.com/rstudio/rstudio/issues/8090

When working on packages that have a large number of revdeps like dplyr, tidyr, or ggplot2, if you have used `revdepcheck::cloud_check()` and downloaded the results into `revdep/cloud.noindex`, then Find in Files will be dramatically slower because it tries to search for results in these files.

It seems very rare that I'd want to search in this folder for anything, and I don't think it would be practical because there can be so many results, so maybe this folder should just be ignored entirely?

CC @romainfrancois

**Comment by kevinushey** [comment]
Assuming you're working in a Git-managed project, wouldn't using the standard git exclusions work here?

<img width="434" alt="Screen Shot 2022-02-11 at 1 47 47 PM" src="https://user-images.githubusercontent.com/1976582/153674854-de55a8a7-cc90-45ec-95fa-b2440eb1cd7e.png">

**Comment by DavisVaughan** [comment]
That does seem to work. But honestly I had _no_ idea what that feature did

**Comment by kevinushey** [comment]
Do we need a better name? E.g "use .gitignore" or something that makes that clear?

**Comment by DavisVaughan** [comment]
Can you help me understand why this option works at all?

In my package level `.gitignore` I have:

```
.Rproj.user
.Rhistory
.RData
inst/doc
.httr-oauth
revdep/checks
revdep/library
revdep/checks.noindex
revdep/library.noindex
revdep/data.sqlite
docs
```

and in my `revdep/` folder `.gitignore` I have:

```
**/
checks
library
checks.noindex
library.noindex
data.sqlite
*.html
```

but none of those point to `revdep/cloud.noindex/`, even though it does seem to get ignored when this option is set

**Comment by DavisVaughan** [comment]
Oh it's the `**/` that matches the `cloud.noindex/` folder. 

I think I would have understood `"Files ignored by git"` as the filter name

**Comment by romainfrancois** [comment]
back to `in progress` for: 

> "Filed matched by .gitignore" sounds good to me as well. IMHO, we should probably make that the default since one rarely wants to search within their .gitignored files.

**Comment by DavisVaughan** [comment]
It looks like modern calls to `usethis::use_revdep()` will automatically add `cloud.noindex` to the `.gitignore`, so we should be fine without that now?

```r
> usethis::use_revdep
function () 
{
    check_is_package("use_revdep()")
    use_directory("revdep", ignore = TRUE)
    use_git_ignore(directory = "revdep", c("checks", "library", 
        "checks.noindex", "library.noindex", "cloud.noindex", 
        "data.sqlite", "*.html"))
    new <- use_template("revdep-email.yml", "revdep/email.yml")
    ui_todo("Run checks with {ui_code('revdepcheck::revdep_check(num_workers = 4)')}")
    invisible(new)
}
```

**Comment by romainfrancois** [comment]
Thanks. I'll remove the special case for now.
