### ISSUE TITLE
`.rs.api.documentOpen()` doesn't scroll cursor into view

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10521]
### System details

    RStudio Edition : 2022.2.999.999
    RStudio Version : Server [Open Source]
    OS Version      : macOS Monterey 12.2
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

Try to open a large document using `.rs.api.documentOpen()`, e.g.

```
.rs.api.documentOpen("path/to/script.R", line = 200, moveCursor = TRUE)
```

### Describe the problem in detail

The cursor is moved to the requested location, but the cursor is not scrolled into view.

### Describe the behavior you expected

The cursor should be scrolled into view.

**Comment by romainfrancois** [comment]
Introduced in #10411

**Comment by jgutman** [comment]
Verified in 2022.06.0-daily+104 RStudio Desktop on Windows 11.
