### ISSUE TITLE
Bug: Completion with "mrgmod" S4 class object and `%>%`

### ISSUE THREAD

**Issue by FelicienLL** [rstudio/rstudio#10538]
### System details

    RStudio Edition : Desktop
    OS Version      : Windows 10 x64 (build 16299)
    R Version       : 4.1.2 (2021-11-01)
### Steps to reproduce the problem
Rstudio completion does not work on "mrgmod" S4 class objects when used inside a `%>%` pipe. 
```r
library(mrgsolve)
mod <- modlib("irm1")
mod |> mrgsim(
# +tab: completion works
mod %>% mrgsim(
# +tab: completion returns error messages and stops
```
### Describe the problem in detail

Because it works with the base `|>` pipe, I assumed the problem was related to magrittr, but apparently it is more related to Rstudio (see https://github.com/tidyverse/magrittr/issues/253#issuecomment-1032887051 ).

These are quite special S4 objects, since they have `names()` and a `$` extraction method.

I tried to debug Rstudio completion method with `debug(search_envs()[["tools:rstudio"]]$.rs.getRChainCompletions)`. Just noticed that: 
- with `%>%`, the value `chainObjectName` was equal to "mod", which triggers a `[[ ]]` extraction of each element in names, which is the origin of the error messages. Completion aborts. 
- with base `|>`, `chainObjectName` was NULL, thus the aforementioned extraction step is skipped (`if(length(chainObjectName))` statement), and the completion is provided by an other part of the code. Named elements never got evaluated and the proposed completion was accurate (i.e. returned the arguments of the `mrgsim` function, but it is the same for any function).

Do you think there something that could be fixed on your side ?

Many thanks for your help !

Félicien

**Comment by romainfrancois** [comment]
Currently getting the same error for both cases: 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/2625526/200267519-9a87c305-8758-43d2-954c-261fcd6e0539.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/2625526/200267698-0ec4aa36-467b-4867-84a5-be0ec9d0370f.png">

The chain based completions derives information from `names()`, which it assumes to be a character vector. 

https://github.com/rstudio/rstudio/blob/f3eb68a11735d56130ea51cc72f96fb6d2bb7852/src/cpp/session/modules/SessionRCompletions.R#L2740-L2745

but we get: 

```r
> names(mod)
$param
 [1] "CL"   "V2"   "Q"    "V3"   "KA"   "KA2"  "KIN"  "KOUT" "IC50" "IMAX" "n"    "VMAX" "KM"  

$init
[1] "EV1"    "CENT"   "PERIPH" "RESP"   "EV2"   

$capture
[1] "CP"

$omega
character(0)

$sigma
character(0)

$omega_labels
named list()

$sigma_labels
named list()
```

which trips up the `vapply()` call.

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0-daily+301
Windows 11, Ubuntu22

Autocomplete works as expected.
