### ISSUE TITLE
Problems with verifyRequestSignature and the http date header

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#10537]
### System details

    RStudio Edition : Server/Workbench
    RStudio Version : Ghost-orchid or higher

### Steps to reproduce the problem

Send an HTTP Date header to an rsession with a date that's 60 seconds away from the session node's current time. This will triggers the verifyRequestSignature method to respond to RPC requests with an error.

If the request happens to have been converted to AsyncRpc, an assertion warning accompanies the error (and the client will never receive a response event for that request). This could cause the client to hang if the wrong request is not responded to.

Seen in the logs provide for https://rstudioide.zendesk.com/agent/tickets/69896 

### Describe the problem in detail

Not sure if the Date header comes from the browser, or the nginx proxy server but it might work to fake a Date header in the nginx config.  Also, if you set session-async-rpc-timeout-ms=0 all requests are turned into async rpc so it will be easier to test. 

If the Date header comes from the browser, we shouldn't be trusting that header value. If we are concerned with replay attacks, it seems like the date should be signed or provided by rserver always. 

### Describe the behavior you expected

When the code calls ptrConnection->sendResponse() for an async rpc, we should instead be sending an error event with the async handle. 

I believe we also should be calling verifyRequestSignature in all places where we call mainConnectionQueue.deque(). Right now, it's not called from polledEventHandler().

**Comment by AndrewMcClain** [comment]
Duplicate of rstudio/rstudio-pro#4325
