### ISSUE TITLE
Starting a tutorial in RStudio Desktop works but results in warnings and an error message

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10549]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0+427
    OS Version      :  Red Hat 7.9 and MacOS 12.1
    R Version       : 4.1.2

### Steps to reproduce the problem

1. Run RStudio Desktop.
2. In the Tutorial Pane, start a tutorial such as "Data basics". (You might first be instructed to click to install the `learnr` package.)

### Describe the problem in detail

The tutorial runs. However:
1. In RStudio 2022.02.0+425 Prairie Trillium, the following errors appear in the terminal:
```
"WARNING: No dependency record found for package 'checkmate' (required by feature 'tutorial')\n\tat Unknown.new Vk(rstudio-0.js)\n\tat Unknown.YUd(rstudio-0.js)\n\tat Unknown.Vrf(rstudio-0.js)\n\tat Unknown.Bsf(rstudio-0.js)\n\tat Unknown.a9l(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.Cm(rstudio-0.js)\n\tat Unknown.Fm(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.onclick(http://127.0.0.1:11860/tutorial/home)\n"
"WARNING: No dependency record found for package 'fastmap' (required by feature 'tutorial')\n\tat Unknown.new Vk(rstudio-0.js)\n\tat Unknown.YUd(rstudio-0.js)\n\tat Unknown.Vrf(rstudio-0.js)\n\tat Unknown.Bsf(rstudio-0.js)\n\tat Unknown.a9l(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.Cm(rstudio-0.js)\n\tat Unknown.Fm(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.onclick(http://127.0.0.1:11860/tutorial/home)\n"
"WARNING: No dependency record found for package 'rappdirs' (required by feature 'tutorial')\n\tat Unknown.new Vk(rstudio-0.js)\n\tat Unknown.YUd(rstudio-0.js)\n\tat Unknown.Vrf(rstudio-0.js)\n\tat Unknown.Bsf(rstudio-0.js)\n\tat Unknown.a9l(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.Cm(rstudio-0.js)\n\tat Unknown.Fm(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.onclick(http://127.0.0.1:11860/tutorial/home)\n"
"WARNING: No dependency record found for package 'rprojroot' (required by feature 'tutorial')\n\tat Unknown.new Vk(rstudio-0.js)\n\tat Unknown.YUd(rstudio-0.js)\n\tat Unknown.Vrf(rstudio-0.js)\n\tat Unknown.Bsf(rstudio-0.js)\n\tat Unknown.a9l(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.Cm(rstudio-0.js)\n\tat Unknown.Fm(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.onclick(http://127.0.0.1:11860/tutorial/home)\n"
"WARNING: No dependency record found for package 'withr' (required by feature 'tutorial')\n\tat Unknown.new Vk(rstudio-0.js)\n\tat Unknown.YUd(rstudio-0.js)\n\tat Unknown.Vrf(rstudio-0.js)\n\tat Unknown.Bsf(rstudio-0.js)\n\tat Unknown.a9l(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.Cm(rstudio-0.js)\n\tat Unknown.Fm(rstudio-0.js)\n\tat Unknown.eval(rstudio-0.js)\n\tat Unknown.onclick(http://127.0.0.1:11860/tutorial/home)\n"
"Uncaught ReferenceError: $ is not defined"
```

2. In RStudio Desktop 2021.09.2+382 Ghost Orchid, only last message appears:
```
"Uncaught ReferenceError: $ is not defined"
```

Note that the packages described above, such as `withr`, are installed.

### Describe the behavior you expected

We shouldn't get any of these errors.
- The error message `"Uncaught ReferenceError: $ is not defined"` appears in both Prairie Trillium and Ghost Orchid, so it's not a regression.
- The list of warnings are new in Prairie Trillium. @jmcphers noted (offline) that the issue is that the JSON files are missing information about what version of the packages are required and how to install them, which might be a regression from https://github.com/rstudio/rstudio/commit/87992ca25458ec27ed2938fd56b439bd45094775. 

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
We have an entry for Tutorials which depends on these packages:

https://github.com/rstudio/rstudio/blob/05379d085c79942006739191317591d7dbbc491e/src/cpp/session/resources/dependencies/r-packages.json#L537-L557

But I suspect the actual entries were inadvertently removed as part of our previous work. I think we need to bring back entries for each package, but just make sure those entries aren't part of the shiny feature set.

**Comment by rich-rstudio** [comment]
verified on 2022.02.0 Build 434
