### ISSUE TITLE
Update two-file shiny app template

### ISSUE THREAD

**Issue by ismirsehregal** [rstudio/rstudio#10542]
Currently, when creating a new two-file shiny app via:

_File -> New File -> Shiny Web App... -> Application type: multiple file_

A template is created using `shinyServer()` and `shinyUI()` which are [superseded](https://shiny.rstudio.com/reference/shiny/1.7.0/shinyServer.html).

I think this should be updated to use a server function;

`server <- function(input, output, session) {}`

and:

`ui <- fluidPage()`

just like the "shinyapp"-snippet.

**Comment by ronblum** [comment]
@ismirsehregal Thank you for raising this issue! I'll mark it as a bug for now, in case the IDE is not behaving as expected. And we'll review this as part of our ongoing development of RStudio.

**Comment by ismirsehregal** [comment]
This is still the case and it should be adjusted.

**Comment by ismirsehregal** [comment]
Creating some activity: This is still the case and it should be adjusted.
