### ISSUE TITLE
project subdirectory fro .Rprofile and .Renviron

### ISSUE THREAD

**Issue by Danny-dK** [rstudio/rstudio#10559]
I was wondering if it would be possible to make Rstudio look in a subfolder within the project directory to find .Rprofile and .Renviron files (maybe something like .settings folder). I would like to keep these files organized in a subdirectory.

As far as I understand, upon opening an Rproj, R / Rstudio will look in the system home location, user home location, project root directory for any of the .Rprofile and .Renviron files. Would it be possible to make Rstudio also check if a settings directory is available to check for these files?

So instead of:
```
- project_directory
    * somescript.R
    * somescript2.R
    * .Rprofile
    * .Renviron
  -somesubdirectory
  -somesubdirectory2
```
Something like:
```
-project_directory
    * somescript.R
    * somescript2.R
 - .settings
    * .Renviron
    * .Rprofile
 -somesubdirectory
 -somesubdirectory2
```

**Comment by jmcphers** [comment]
It isn't likely, because these files are read and executed by R itself, not RStudio. 

https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html

**Comment by kevinushey** [comment]
See also https://cran.r-project.org/web/packages/startup/index.html; there might be something within there you could use (or you could make a request to the package maintainer to support this particular configuration).
