### ISSUE TITLE
Tutorials with old version of shiny fail instead of prompting for a package update

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10552]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.02.0+422 and 426
    OS Version      : MacOS 12.1 and Ubuntu 20.04 via Chrome on MacOS 12.1
    R Version       : 4.1.2

### Steps to reproduce the problem

1. In the Console Pane: `remotes::install_version("shiny", "1.5.0")`
    - This install version 1.5.0 of `shiny`
2. In the Tutorial Pane, choose one of the tutorials. You might first be prompted to install the `learnr` package.

### Describe the problem in detail

1. The Tutorial Pane only gets as far "Loading Tutorial" but never moves past it, with a spinning wheel.
2. The following appears in the Jobs Pane:
```
Error: 'getCurrentTheme' is not an exported object from 'namespace:shiny'
Execution halted
```

### Describe the behavior you expected

The tutorial should run, as it does with later versions of `shiny`. Tutorials have a dependency on version 1.6.0 or later. We don't prompt updates for the `shiny` as aggressively as we did previously, so we're not prompting for an update.

This is a regression from Ghost Orchid, as we prompted for an update to `shiny` and didn't try running the tutorial without it.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is effectively a regression that re-introduced https://github.com/rstudio/rstudio/issues/8703 because we took back the bump to Shiny 1.6.0 that fixed that issue; now it's back. 

The dependency chain is tutorials => rmarkdown => Shiny; you only need the new Shiny if you also have the new rmarkdown.

**Comment by judyshatkin** [comment]
This is happening to me. I tried to use RStudio on my mac that had 10.12. Now I updated to Ventura 13.0.1 but it's just stuck on "tutorial loading..."

**Comment by judyshatkin** [comment]
I tried uninstalling R and Rstudio and did CleanMyMac to remove all components, but it still has the files from before I updated the Mac.

**Comment by judyshatkin** [comment]
After I installed "sass" and loaded library(sass) the tutorials started working
