### ISSUE TITLE
Title and message missing on "Error Starting R" page (Electron desktop)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10554]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : 2022.06.0-daily-87 (electron)
    OS Version      : MacOS 12.1
    R Version       : 4.1.2

### Steps to reproduce the problem

- Force the "Error Starting R" page to display by executing Electron RStudio.app as follows:

`RSTUDIO_SESSION_EXIT_ON_STARTUP ./RStudio.app/Content/MacOS/RStudio`

![screenshot from Electron](https://user-images.githubusercontent.com/10569626/153308293-b6f487ed-a1bd-4b14-a4c7-d1c5d3934482.png)

- Compare with same from a Qt desktop build:

![screenshot from Qt desktop](https://user-images.githubusercontent.com/10569626/153308484-3040840f-4177-483c-ae1a-3b3602f2853c.png)

### Describe the problem in detail

The Electron page is missing the text "Error Starting R" and "The R session failed to start.". Instead it shows "uiFolder.rSessionFailedToStart".

### Describe the behavior you expected

These should match. Possibly a regression from localization work?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Verified fixed in RStudio 2022.06.0 build 242 on Ubuntu 20.04.
