### ISSUE TITLE
Verbose info about i18next written to console when running RStudio Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10553]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : 2022.06.0-daily-87
    OS Version      : macOS 12.1
    R Version       : 4.1.2

### Steps to reproduce the problem

Execute RStudio.app from the terminal, i.e.:

`./RStudio.app/Contents/MacOS/RStudio`

### Describe the problem in detail

A bunch of info gets displayed related to i18next:

```
➜  Desktop ./RStudio.app/Contents/MacOS/RStudio
i18next: languageChanged en
i18next: initialized {
  debug: true,
  initImmediate: true,
  ns: [ 'translation' ],
  defaultNS: [ 'translation' ],
  fallbackLng: [ 'en' ],
  fallbackNS: false,
  supportedLngs: false,
  nonExplicitSupportedLngs: false,
  load: 'all',
  preload: false,
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  partialBundledLanguages: false,
  saveMissing: false,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  postProcessPassResolved: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: false,
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
  interpolation: {
    escapeValue: true,
    format: [Function: bound value],
    prefix: '{{',
    suffix: '}}',
    formatSeparator: ',',
    unescapePrefix: '-',
    nestingPrefix: '$t(',
    nestingSuffix: ')',
    nestingOptionsSeparator: ',',
    maxReplaces: 1000,
    skipOnVariables: true
  },
  resources: { en: { translation: [Object] } },
  ignoreJSONStructure: true,
  lng: 'en'
}
```

### Describe the behavior you expected

This shouldn't be displayed when running the program normally, except maybe if using debug logging, e.g.:

`./RStudio.app/Contents/MacOS/RStudio --log-level=debug`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by matheustavaresdev** [comment]
Gotcha! Will fix that!

**Comment by gtritchie** [comment]
Confirmed this is no longer happening. Closing.
