### ISSUE TITLE
Providing either Global or Project limits on the number or storage cost of Plot History

### ISSUE THREAD

**Issue by jw5** [rstudio/rstudio#10556]
Plot history is a great feature that I use daily. However, it has always had a few issues around customization and GUI support.

In this latest project I am generating plots with gg:ggplot objects in the 8-10GB range. Yes, 10GB per plot. They can take several minutes to render. Yes there are issues with alpha blending when the point count exceeds 20M, but I've found workarounds.

Unfortunately, the cumulative cost of these plots starts to add up. After doing a dozen, unless I'm very thorough in deleting each one as I go, I end up with a long list of painfully slow to re render images. This makes the rm plot button less than ideal. I usually have to just kill rstudio and restart. But that in turn entails reloading the data set (~40GB) which takes several looong minutes.

Possible mitigations:
1. Allow a per project/global option to set the max number of retained plots.
2. Allow a per project/global option to set the max memory of retained plots.
3. When paging through plot history with the forward and back buttons reuse the temp pngs and don't re render unless the plot window size has changed.
4. Provide an enhanced UI around the retained plots that provides a matrix view of the available plots (using the temp pngs) and provides user checkbox selection for printing, saving, deletion etc.

Thanks,
Jim

**Comment by ronblum** [comment]
@jw5 Thank you for the suggestions! And wow, that's pretty impressive, 10 GB for a plot. We'll review this as we continue development of RStudio.
