### ISSUE TITLE
Rename Makefile projects

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#10564]
as a follow up to https://github.com/rstudio/rstudio/pull/10432 Makefile projects are the only type of projects using "Clean and Rebuild" which should then probably be renamed.

**Comment by romainfrancois** [comment]
Actually, perhaps we can use the same approach as for packages, and only keep the "Build All" button: 

![image](https://user-images.githubusercontent.com/2625526/156572681-a2c59867-afe0-4cc2-a564-a673c3ff80be.png)

But condition first running `make clean` on the "Clean before install" checkbox: 

![image](https://user-images.githubusercontent.com/2625526/156573006-232dc35f-569f-4a62-9376-8eb07ad65e0b.png)

**Comment by romainfrancois** [comment]
QA: On a `Makefile` project with this Makefile: 

```
all:
	echo "hello"

clean:
	echo "cleaning"
```

The build pane will look like this: 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2625526/161500521-f6386b07-fff0-4309-9b7a-de9e1214012f.png">

"Clean All" will: 

<img width="530" alt="image" src="https://user-images.githubusercontent.com/2625526/161500722-20949b8c-bc1c-4dc0-8913-2664ed148337.png">

and "Build All": 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/2625526/161500763-e6c58524-61e2-4558-aee7-0ed49ae2a048.png">

The build menu: 

<img width="340" alt="image" src="https://user-images.githubusercontent.com/2625526/161500797-c1ef7b12-ac83-4124-ad9f-07fb7895f10f.png">

**Comment by jgutman** [comment]
Verified on 2022.06.0-daily+333 with Mac OS 12.3.1
