### ISSUE TITLE
Create Quarto Project website flow is broken

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rstudio#10569]
### System details

    RStudio Edition : 
    RStudio Version : 2021.09.2 Build 382
    OS Version      : MacOS
    R Version       : 4.1.1

### Steps to reproduce the problem
1. Click `New Project
![Screen Shot 2022-02-10 at 3 32 15 PM](https://user-images.githubusercontent.com/17551950/153500199-4730c771-3355-4f4d-812c-93b1b0f94dc0.png)

2. In `New Project Wizard`, click `New Directory`
3. Click `Quarto Project`
4. Select `Website` from the `type` drop down 
![Screen Shot 2022-02-10 at 3 34 12 PM](https://user-images.githubusercontent.com/17551950/153500271-8da72040-48d4-44a7-b287-ffb09ab3f4ae.png)
5. Populate `Directory Name`
6. Click `Create Project`

**Result:**
`ERROR: Unsuppported project type site`
![Screen Shot 2022-02-10 at 3 35 06 PM](https://user-images.githubusercontent.com/17551950/153500390-4029bfe1-b0a7-4b78-8c53-7a3d1cc1f1b4.png)

### Describe the problem in detail
IDE Create Quarto Project website flow is broken

### Describe the behavior you expected
Quarto website project should be created without any issue 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ChaitaC** [comment]
With the latest ID daily build, this issue is resolved. Thus, Closing the ticket

**Comment by modche** [comment]
Ok, thanks. But I am still getting the same error message.
