### ISSUE TITLE
Quarto: New Project Wizard dialogue box disappears if you try to exit out of error model 

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rstudio#10570]
### System details

    RStudio Edition : 
    RStudio Version : 2022.06.0 Build 93
    OS Version      : MacOS
    R Version       : 4.1.1

### Steps to reproduce the problem
1. Click `New Project
![Screen Shot 2022-02-10 at 3 32 15 PM](https://user-images.githubusercontent.com/17551950/153500199-4730c771-3355-4f4d-812c-93b1b0f94dc0.png)

2. In `New Project Wizard`, click `New Directory`
3. Click `Quarto Project`
4. Keep `Default`and populate Directory Name `TestQuarto`
5. Now, try to create another project with the same name (repeat steps 1-4)
6. Since the directory name exits you see an validation error 
![Screen Shot 2022-02-10 at 3 38 08 PM](https://user-images.githubusercontent.com/17551950/153501308-fe42db0e-9924-4b6e-9901-375ad69943ba.png)
7. Click `OK`

**Result:** 
Along with the error pop-up, the New Project wizard also closes. 

### Describe the problem in detail
The New Project Wizard dialogue box disappears if you try to exit out of the error model if the directory name already exists. 

### Describe the behavior you expected
Error model should disappear but the New Project Wizard dialogue should stay and allow the user to select a new file name

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
Similar with e.g. new shiny projects. 

OTOH, `distill` projects will happily install its things even if the directory exist. cc @cderv

**Comment by cderv** [comment]
Thanks @romainfrancois 

I believe Quarto project, and probably shiny project creation are integrated into RStudio IDE. For R Markdown related project, I believe this is relying on RStudio Project template and a function in the package are called. 

It seems that those function called in R Console or through template project in IDE are not erroring when a directory exist. 
It is interesting that this has not been reported yet 🤔 Even if we were changing that in the R function, I am not sure it would error the same way as shown above as the code is run in R directly the error would be thrown there (in current windows or new session if selected). 

You think we should change the current behavior right ?

**Comment by romainfrancois** [comment]
I have a fix for quarto, that borrows from how things are done for packages. I'll check if I can prevent calling the function in the rmarkdown cases.

**Comment by jgutman** [comment]
Error message:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/7817881/168605776-edb5dfc4-bfa9-446b-a12b-e74ef97ba505.png">

After hitting OK, new project wizard is still open:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/7817881/168605807-f7f5ac79-78cb-45c2-a3a3-600185471da1.png">

Verified in 2022.6.0.406 RStudio Desktop on Mac OS 12.3.1
