### ISSUE TITLE
Console toolbar stuck in Python mode after restart

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#10579]
### System details

    RStudio Edition : Both
    RStudio Version : RStudio 2022.02.0+424 "Prairie Trillium"

### Steps to reproduce the problem

Noticed this during @jgutman's demo today. 

1. Ensure Python and the reticulate package are installed.
2. Run some Python code, by e.g. creating a new .py script, adding the text `1 + 1` to it, and pressing Cmd+Enter to run the line.
3. Restart the R session.

### Describe the problem in detail

The console prompt is an R prompt, but the console toolbar still says we're in Python mode.

![image](https://user-images.githubusercontent.com/470418/153654119-d4d3c81e-6f24-4b0d-aa97-03ee752cb98b.png)

Related: https://github.com/rstudio/rstudio/issues/8011

### Describe the behavior you expected

The console toolbar should be in sync with the state of the interpreter, and indicate that we're at an R prompt. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
Good eye! I think this is also the same issue as #10458 
We don't listen for Rsession restarts and update the UI accordingly

**Comment by ronblum** [comment]
Tested by
1) running in the console with `reticulate::reply_python()`
2) running within a Python file, which does the same as no. 1

Verified in
- RStudio Desktop 2022.06.0-daily+151 on MacOS 12.1
- RStudio Server 2022.06.0-daily+151 on Ubuntu 20.04 via Chrome on MacOS 12.1
