### ISSUE TITLE
File viewer doesn't refresh after using the UI to move (and delete?) files

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#10580]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.06.0-daily+93
    OS Version      :  Mac OS 12.2
    R Version       :  R-devel 4.2 x86_64

1. In the file viewer, check the box for a file, Click on More and then Move... to move the file
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7817881/153655338-1677476e-2d0d-4324-9e72-fde22b490c28.png">
2. Move the file to another directory

3. Check the file viewer. The file still appears in the original location (now unchecked).
<img width="369" alt="image" src="https://user-images.githubusercontent.com/7817881/153655429-8292a4e2-4457-4110-a89a-841eb0f59431.png">
4. Double click the file to open. It will show there is no such file (because it has been moved)
<img width="284" alt="image" src="https://user-images.githubusercontent.com/7817881/153655485-64d237f1-e59a-41e8-84dd-4145b50ff7ce.png">

I thought moving these files would refresh the file viewer UI so that they no longer appear under the current directory

**Comment by jgutman** [comment]
I just ran into this myself, but cannot reproduce

**Comment by jgutman** [comment]
This just happened again -- seems to happen when moving multiple files (perhaps of different types) into a folder (perhaps a subfolder)? @ronblum are you able to consistently reproduce?

**Comment by ronblum** [comment]
See also #8276.
