### ISSUE TITLE
Auto-formatting for `<summary>` element in qmd creates blank line in HTML

### ISSUE THREAD

**Issue by batpigandme** [rstudio/rstudio#10589]
### System details

    RStudio Edition : Desktop
    RStudio Version :  "Prairie Trillium" Release (cd40e7dd, 2022-02-09) for macOS
    OS Version      :  macOS
    R Version       :  4.1.2

### Steps to reproduce the problem

In a quarto document (`.qmd`) that renders to HTML create `<details> <summary>` block, e.g.:
```html
<details>

<summary>The Summary</summary>

The details

</details>
```
If you save, this will automatically reformat to put the  summary tags on their own line:

```html
<details>

<summary>

The Summary

</summary>

The details

</details>
```

When rendered to HTML, the summary will then have an undesired blank line in it (screenshot below):
![quarto documents before and after auto-formatting and rendered HTML with extra linebreak](https://user-images.githubusercontent.com/831732/153759057-ff00da85-fc5f-4188-a71e-7946779d748e.png)

### Describe the problem in detail

The auto-formatting for Quarto/`.qmd` for folding/Disclosure summary element is resulting in a blank line in rendered HTML. (See example code above). It is the line break _after_ the opening `<summary>` tag that moves the text of the summary to the next line (see also @mine-cetinkaya-rundel's thread in internal slack [here](https://rstudio.slack.com/archives/C0155CA4L2W/p1612180466011900)).

### Describe the behavior you expected

Expect that the auto-formatting will either allow the format necessary to avoid the blank line (i.e. `<summary>Blah</summary>`) or that the formatting will result in the desired output (i.e. without the blank line).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
This should be fixed here: https://github.com/rstudio/rstudio/commit/e608370bff472f699a14bf36a1fee08471182139

**Comment by romainfrancois** [comment]
Verified in `RStudio 2022.06.0-daily+361`: 

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/2625526/167138097-3459ead1-c123-4d1b-afb6-892921ea6bf2.png">

saving does not change the document. then it looks like correct; 

<img width="905" alt="image" src="https://user-images.githubusercontent.com/2625526/167138260-e3668e10-0805-4092-a3b8-30d7576f9107.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/2625526/167138279-fbcd06d5-8f95-4d33-b435-eeeb4d8634ec.png">
