### ISSUE TITLE
Windows Electron installer doesn't detect running Electron RStudio

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10588]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : Any Windows Electron package build
    OS Version      : Windows-10
    R Version       : Any

### Steps to reproduce the problem
- Install RStudio Electron on Windows
- Start RStudio
- Run the RStudio Electron installer

### Describe the problem in detail

- The installer should warn that you have RStudio running and must close it before installing/uninstalling RStudio
- It does detect the Qt RStudio, via code here: https://github.com/rstudio/rstudio/blob/b936403eb9a1f3fece55a1b66146acfc2a273a8b/package/win32/cmake/modules/NSIS.template.in.electron#L992-L999

### Describe the behavior you expected

- Should detect if either Qt-based or Electron-based RStudio is running
- We can't use the same techinque as Qt detection; the window class of an Electron app is the same as for Chrome, Edge, and likely many other applications; so, if you had downloaded RStudio via Chrome and still have that tab open, it would be detected as an instance of RStudio
- Ideally we'll detect the rstudio.exe process and key off that instead of looking for window classes/titles

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily-268 Windows Desktop

Correctly blocked when another electron instance was running. Also blocked when a QT version was already running.
