### ISSUE TITLE
Prairie Trillium breaks many/most custom 3rd party themes

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#10598]
### System details

    RStudio Edition : Both
    RStudio Version : RStudio 2022.02.0+438 "Prairie Trillium"  

### Steps to reproduce the problem

1. Install @gadenbuie's rsthemes package, `remotes::install_github("gadenbuie/rsthemes")`. https://github.com/gadenbuie/rsthemes
2. Install all the themes with `rsthemes::install()`. 
3. Try a few themes.

### Describe the problem in detail

They don't look very good, and certainly don't look like their previews.

"Oceanic" looks like this:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/470418/153957112-55e3b8d3-7cfd-443f-9f19-8d2e39e5de7d.png">

And here's "Material Palenight"

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/470418/153957193-f1fd51ae-1e3a-4a5a-959c-072d6afde85f.png">

The problem was introduced with https://github.com/rstudio/rstudio/pull/10081, which sought to dramatically simplify our CSS by removing all vestiges of the Classic theme. Unfortunately, as noted by @gadenbuie in https://github.com/rstudio/rstudio/issues/10216, a lot of third-party themes relied on one of those vestiges in particular: the `rstudio-themes-flat` selector.

### Describe the behavior you expected

We shouldn't break all the community's themes; they should work like they did in RStudio 2021.09. For example here's what Oceanic _should_ look like:

![image](https://user-images.githubusercontent.com/470418/153957683-39b732f6-f3f8-4e8f-979a-a56743858011.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Just noticed this was also reported on the community forum: https://community.rstudio.com/t/rstudio-themes-dont-work-as-expected-in-newer-rstudio-versions/128949

**Comment by GCRev** [comment]
I've verified that themes from rsthemes behave "as I would expect them to" -- which means no glaring contrast issues and panes that jump out as offensive -- on Chrome, MacOS Desktop, and Windows Desktop. I would say we can close out this ticket, but it's always possible that I missed something.
