### ISSUE TITLE
Write a script to flag modified English UI text so French translations can be updated

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10595]
When existing UI text gets tweaked in English, we need to know to review the translations (currently only French) to ensure they get updated as well.

Consider writing a script that can identify such changes made since the last release.

**Comment by kevinushey** [comment]
In addition, from @gtritchie:

> We also want it to flag existing strings that changed from PT to SW, so we know to have them retranslated.

So, as I understand it, the script should accept two branches as arguments, find out which translations have changed (for a particular language), and see if there is a similar change reflected in other language files.

**Comment by gtritchie** [comment]
Tools has been merged. See #11320 for details.
