### ISSUE TITLE
git diff (Review Changes) window fails to load

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10606]
For Electron. It looks like it's trying to query `window.desktopInfo`, but that object isn't populated in windows other than the main window.

**Comment by gtritchie** [comment]
This was working in early January 2022 (at 60e4de7c0c). Working to identify the source of the regression.

**Comment by gtritchie** [comment]
Upgrading Electron from v15 to v16 broke this. Working on the fix.

Related to https://github.com/rstudio/rstudio/pull/9737

**Comment by gtritchie** [comment]
Note to self: https://www.electronjs.org/docs/latest/api/window-open/

**Comment by kevinushey** [comment]
Verified fixed on Ubuntu 20.04 with RStudio 2022.06.0 build 242.
