### ISSUE TITLE
Editor windows not loading (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10607]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : 2022.06.0-daily+109 "Spotted Wakerobin" 
    OS Version      : macOS 12.12.1 (also observed on Windows-10 with Electron build)
    R Version       : 4.1.2

### Steps to reproduce the problem

- start Electron desktop
- File / New File / R Script
- Click on arrow in editor to move to a separate window

### Describe the problem in detail

- window displays but never finishes loading (spinner)

![Screen Shot 2022-02-15 at 10 15 11](https://user-images.githubusercontent.com/10569626/154114771-811a4ff3-73cb-4b15-93bd-b599126b1c86.png)

### Describe the behavior you expected

- editor loads

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Upgrading Electron from v15 to v16 broke this. Working on the fix.

Related to https://github.com/rstudio/rstudio/pull/9737

**Comment by kevinushey** [comment]
Verified fixed on Ubuntu 20.04 Build 242, as well as recent daily builds on macOS.
