### ISSUE TITLE
Secondary windows showing menubar (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10610]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : 2022.06.0-daily-111
    OS Version      : Windows-10 or Linux
    R Version       : Any

### Steps to reproduce the problem

- In Electron on Linux or Windows, bring up a secondary window in the IDE, such as an editor window or showing Help in another window

### Describe the problem in detail

- The secondary window gets the menubar just like the main window

### Describe the behavior you expected

- No menubar on anything but the main window

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Upgrading Electron from v15 to v16 broke this. Working on the fix.

Related to https://github.com/rstudio/rstudio/pull/9737

**Comment by kevinushey** [comment]
Verified on Ubuntu 20.04 with RStudio 2022.06.0 Build 243.

<img width="667" alt="Screen Shot 2022-03-28 at 4 39 49 PM" src="https://user-images.githubusercontent.com/1976582/160504683-91688dab-9dc8-4091-817b-7e475ccc2b11.png">
