### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by rsdmse** [rstudio/rstudio#10616]
We have a secure cluster that does not have internet connection. It is based on AlmaLinux 8.5. I have tried the following methods:

- The tarball for CentOS 7 does not work even though I installed all the system libraries such that `ldd rstudio` looks ok. The error message is:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Aborted (core dumped)
```
I can provide the verbose output with `QT_DEBUG_PLUGINS=1` if that is necessary. I believe this route is likely a dead-end maybe due to incompatible libraries between CentOS 7 and 8.

- Because it is a shared machine, the RPM for CentOS 8 cannot be installed at the system level. If I try to install it under a different location I get the error `path / is not relocatable`.

- I tried to build from source but had trouble with the dependency installation. Since there is no internet connection, I cannot use the scripts. I installed e.g. yaml-cpp separately but then cmake cannot detect it, regardless of setting `CMAKE_MODULE_PATH`, `YAML_CPP_INCLUDE_DIR`, `YAML_CPP_LIBRARIES` via `-D` or even hardcoding into `src/cpp/CMakeLists.txt`.

Up to now this may seem more like a bug report, but what I'm really asking for is a self-contained offline installation method. A tarball for CentOS 8 would be the most convenient for us, but I understand due to its EOL this may not be in your support roadmap.

If you need more information on any of the three methods that I described I'd be happy to provide that. I would appreciate other suggestions too. Thanks in advance!

**Comment by rsdmse** [comment]
I found a workaround: https://github.com/rstudio/rstudio/issues/3382#issuecomment-416659732
The CentOS 7 tarball still gives some error messages but it didn't crash and I can run commands in the console:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 682, resource id: 4194366, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by kevinushey** [comment]
Great, I'm glad to hear it! Does that workaround suffice for your use case?

> A tarball for CentOS 8 would be the most convenient for us, but I understand due to its EOL this may not be in your support roadmap.

We do have builds that should be compatible with CentOS 8 -- see https://dailies.rstudio.com/ for some of those published builds. These builds are generated using Rocky Linux 8 (https://rockylinux.org/) and should be compatible with CentOS 8 / RHEL 8 systems.

**Comment by rsdmse** [comment]
Thanks for providing the dailies link that I wasn't aware of! I tried the RedHat 8 one. It still needed the workaround and gave the libGL errors, but other than that both the CentOS 7 and RedHat 8 tarballs seem to be working.
