### ISSUE TITLE
UI element clears when performing a replace with Find in Files using a regular expression

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#10626]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.6.0.116
    OS Version      :  Seen on both Mac OS 12.2 and Windows 11
    R Version       :  N/A (seen with both 4.0 and 4.2)

### Steps to reproduce the problem
1. Cmd + Shift + F to open Find in Files dialog
<img width="407" alt="image" src="https://user-images.githubusercontent.com/7817881/154538022-8be3f6a7-cccb-4c5c-88f7-52a751b0f12b.png">

2. Perform a search without using regular expression. A match is found
<img width="766" alt="image" src="https://user-images.githubusercontent.com/7817881/154538165-561c31a7-cf9d-431f-8164-2cf538c7abc1.png">

3. Enter a replacement in the replacement box. The pane says `Results for "hello" in ~/search` as expected
<img width="759" alt="image" src="https://user-images.githubusercontent.com/7817881/154538315-c7fc03ad-0fb3-4dc5-ba0d-8530556610b6.png">

4. Now do the same, but with regular expression checked. Initial dialog before entering a replacement appears as expected
<img width="759" alt="image" src="https://user-images.githubusercontent.com/7817881/154538683-a29f6a99-336c-4a62-8ca4-c79b339b9798.png">

5. Once I enter a replacement, the UI element that said `Results for /hello/ in ~/search` disappears
<img width="765" alt="image" src="https://user-images.githubusercontent.com/7817881/154538842-3de69465-f051-4b65-9148-5163bff02a1f.png">

**Comment by ronblum** [comment]
Note: Marking as `triage` for consideration in Spotted Wakerobin.

**Comment by romainfrancois** [comment]
Verified on SW build 220 (`2022.06.0 + 220`).
