### ISSUE TITLE
Cannot save or load from folders with special characters å, ä, and ö

### ISSUE THREAD

**Issue by LoveBohman** [rstudio/rstudio#10623]
**Creating** folders with the Swedish/Scandinavian letters å, ä, or ö from within RStudio works fine. **However, saving and loading** from the folders is not possible.

```
# Creating and saving and loading from a folder without the special characters works just fine:
dir.create("fold_a")
var <- 1:10
save(object = var, file = "fold_a/var.RData")
load("fold_a/var.RData")

dir.create("fold_ö")          # Creating folder with special character works fine
var <- 1:10
save(object = var, file = "fold_ö/var.RData")  # However, I cannot save to the folder
# Manually move file to fold_ö
load("fold_ö/var.RData")   # I cannot load from the folder either
```

This works fine from plain R, so it seems to be an issue with RStudio

R version: 4.1.2 (2021-11-01)
RStudio version: 2021.09.2+382 "Ghost Orchid" for Windows
Platform: x86_64-w64-mingw32

**Comment by jgutman** [comment]
Thanks for reporting this issue! I believe this was a regression that has already been addressed in recent patches and later versions. Would you try downloading the latest daily version for RStudio "Ghost Orchid" 2021.09.3+385 from https://dailies.rstudio.com/rstudio/ghost-orchid/ or the preview version for RStudio "Prairie Trillium" 2022.02.0+442 from https://www.rstudio.com/products/rstudio/download/preview/ and let us know if this resolves the issue?

**Comment by jgutman** [comment]
This has already been backported to Ghost Orchid, but the patch 2021.09.3 has not yet been released

**Comment by jgutman** [comment]
Closing but let us know if this does not solve your issue, and we will re-open!

**Comment by LoveBohman** [comment]
Many thanks!
That solved the issue.

Have a nice day!
Love
