### ISSUE TITLE
Cursor offset with autocompletion in rmd code chunk

### ISSUE THREAD

**Issue by gael-j** [rstudio/rstudio#10639]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0 Build 443
    OS Version      : Macintosh; Intel Mac OS X 12_1_0)
    R Version       : 4.1.1

### Steps to reproduce the problem
in rmd file:
Using automatic completion with the tab button for filling in the file name from "Folder" and selecting the name while writing the following code
```{r}
foo<-read.delim("Folder/SubFolder/SubsubFolder/données.csv"|
...
```

### Describe the problem in detail
This results in an offset of the cursor of 2 characters to the right of where the changes actually happen. In the example above, if I press backward delete while my cursor is at the place illustrated by the pipe, the "s" will be deleted, not the ". 
This offset remains for the line, but not at other places of the rmd document.
This problem does not occur if I enter the path entirely manually.

### Describe the behavior you expected
By entering any key, it should appear right at the cursor's place, not with an offset of two characters.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gael-j Thank you for raising this issue! We've seen it before, because of certain characters. In this case, it might be the `é` in the file name. I'll check to see if I can trace the other issue.

**Comment by ronblum** [comment]
@gael-j Found it: #6836. I'll leave this issue open, in case it's not a duplicate.

**Comment by gael-j** [comment]
> 

Indeed, if the accented characters are not present in the filename or path, this strange behavior disappears also! 
It does seem to be related to issue #6836, well traced ! ;^)

**Comment by kevinushey** [comment]
A workaround (albeit not ideal) for cases like these is to use a unicode escape rather than the character literal; e.g.

```
> stringi::stri_escape_unicode("Folder/SubFolder/SubsubFolder/données.csv")
[1] "Folder/SubFolder/SubsubFolder/donn\\u00e9es.csv"
```
