### ISSUE TITLE
Git tag naming? (with prefix "v" or without prefix)

### ISSUE THREAD

**Issue by eitsupi** [rstudio/rstudio#10635]
### System details

    RStudio Edition : both
    RStudio Version : 2022.02.0+443
    OS Version      : none
    R Version       : none

### Describe the problem in detail

Since the move to calendar-based versioning, there seems to be some confusion in the release tag naming conventions with and without the prefix "v".
In the latest version released yesterday, it seems be back to tags without "v" again.
Is this a mistake? Or is it a permanent change in the naming convention?

![image](https://user-images.githubusercontent.com/50911393/154613499-6dd2eea7-65ae-4035-94d6-1aea412116a7.png)

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@eitsupi Thank you for raising this issue! It's a mistake on our part—the `v` should be present at the start. We're working on it as we speak (or write).

**Comment by ronblum** [comment]
@eitsupi Lightning quick update: We've fixed the problem. Would you be willing to confirm? Thanks!

**Comment by eitsupi** [comment]
Thank you for taking care of it so quickly !
It's much easier to find out about RStudio versions now that they are in release order when sorted by tags.

**Comment by ronblum** [comment]
@eitsupi Our pleasure—and thank you for checking so quickly! 🚀
