### ISSUE TITLE
YAML style chunk option  for `eval` not recognized with "Run all chunks above" 

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#10645]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : mac OS 12.2.1
    R Version       : 4.1.2

### Steps to reproduce the problem

Create a Quarto or an R Markdown document and add the following content.

```
    ```{r}
    #| eval: false
    
    # runs with "Run all chunks above", unexpected behaviour
    1 + ___
    ```
    
    ```{r eval = FALSE}
    
    # doesn't run with "Run all chunks above", correct behaviour
    2 + ___
    ```
    
    ```{r}
    2 + 2
    ```
```

Then, click on the "Run all chunks above" button for the last chunk.


### Describe the problem in detail

`eval` option for code chunks behaves differently depending on how it's expressed (`eval = FALSE` vs. `#| eval: false`) when clicking on "Run all chunks above".

### Describe the behavior you expected

Neither of the top two chunks should run when clicking on "Run all chunks above" in the last chunk. 

<!-- 
Please keep the below portion in your issue, and check `[x]` the applicable boxes.
-->

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mine-cetinkaya-rundel Is the second chunk getting evaluated? When I run the code as is, the first one gets evaluated, but not the second. If I remove the first chunk, same thing—it's not getting evaluated. I tried both R Markdown and Quarto in RStudio Desktop 2022.02.0+443 on MacOS 12.1.

**Comment by mikebessuille** [comment]
@kevinushey is this meant to be supported?

**Comment by kevinushey** [comment]
Yes, we'll need to support this as YAML chunk options are going to become the norm soon (especially with Quarto).

**Comment by mine-cetinkaya-rundel** [comment]
@ronblum Correct, the first one gets evaluated and the second doesn't. However, the correct behaviour would be for neither of them to be evaluated. I provided both as an example of one that works as expected and one that doesn't.

**Comment by jgutman** [comment]
Thanks for raising -- this appears to be the case for all YAML chunk options, and not only for eval.

**Comment by kevinushey** [comment]
For reference, some pieces of related code:

https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java

(This is the UI shown when one clicks the gearbox icon at the top-right of a chunk)

https://github.com/rstudio/rstudio/blob/c59c01f7c2a9b12afb1b3da64e7f4daa896875ad/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java#L147-L211

(This is the parser for the chunk header; we likely need a similar primitive parser for embedded YAML)

https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/assist/RChunkHeaderParser.java

(A separate chunk header parser; I don't recall the motivation for having two separate implementations for the same task...)

**Comment by kevinushey** [comment]
And more specifically for this issue, I think:

https://github.com/rstudio/rstudio/blob/c59c01f7c2a9b12afb1b3da64e7f4daa896875ad/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetChunks.java#L300-L311

**Comment by jgutman** [comment]
Ah okay, I've been looking at the chunk parser in https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionRmdNotebook.R#L611-L649

which specifically only looks at the first line of each chunk -- believe this function will need to be modified

**Comment by jgutman** [comment]
> (This is the UI shown when one clicks the gearbox icon at the top-right of a chunk)

Thanks for raising this, I've updated the behavior on the backend to properly parse the yaml chunks, but can update these bits so it's reflected in the frontend gearbox popups as well.

**Comment by hadley** [comment]
I'm still seeing this problem (with Mine's reprex) in 2022.06.0 Build 412

**Comment by hadley** [comment]
Oh I bet the difference is again that I have "Chunk output in console"

**Comment by jgutman** [comment]
Aha! Yes, that appears to be it, I just tried it on 412 and checking/unchecking that setting does indeed control whether or not that chunk gets run. We have this issue to track updating that setting's behavior: 
https://github.com/rstudio/rstudio/issues/10677
I'll add this info there to help our tracking

**Comment by kevinushey** [comment]
I think that implies this is an MRE:

`````
---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#| eval: false
print("I shouldn't run")
```

```{r}
print("I should run")
```
`````

**Comment by hadley** [comment]
Or even more obviously

````md
---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#| eval: false
stop("I shouldn't run")
```

```{r}
print("I should run")
```
````

**Comment by jgutman** [comment]
Actually, whether or not the chunk option is respected appears to be controlled entirely by the setting "Show chunk output inline in all documents in the Global Options/command palette, and not by 
```
editor_options: 
  chunk_output_type: console
```
With @hadley's reprex above:
Show chunk output inline in all documents: On -> Chunk with `#| eval: false` is not run in the console and output is not displayed inline 😄 
Show chunk output inline in all documents: Off -> Chunk with `#| eval: false` is run in the console 😞 
This behavior is unchanged regardless of whether or not `chunk_output_type: console` is set

**Comment by romainfrancois** [comment]
Verified with RStudio 2022.06.0-daily+421 "Spotted Wakerobin" Daily. 

Clicking on the "Run all chunks above" in the last chunk: 

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/2625526/169786557-a3943c47-698b-4fc9-95ae-f741103935af.png">
