### ISSUE TITLE
latest stable links point to old releases

### ISSUE THREAD

**Issue by mwt** [rstudio/rstudio#10642]
Like #9743 but it applies to the current stable release instead.

For example, 

https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb

points to `2021.09.2-382` instead of the new release. Do these tags have to be set manually?

**Comment by ronblum** [comment]
@mwt Thank you for raising the problem! We're looking into the issue and hope to have it resolved soon.

**Comment by mwt** [comment]
It seems that this has been fixed 🥳
