### ISSUE TITLE
Rstudio only open works with root privileges (sudo)

### ISSUE THREAD

**Issue by dsmaynard** [rstudio/rstudio#10643]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.2 Build 382
    OS Version      : Arch v 5.16.10
    R Version       :  4.1.2 (Bird Hippie)

### Steps to reproduce the problem

Install the deb of rstudio desktop from the github. Open rstudio without root access. Then open rstudio with root access (sudo) from terminal. 

### Describe the problem in detail
I downgraded my rstudio install from the daily preview to the stable github branch. Now, when I open rstudio as normal, either from the terminal or the gnome apps menu, it opens but just displays a white screen. The menus are still  there (file, edit, code, etc) but cannot be interacted with. I can't close the app either, I have to kill it from the task manager. 

![image](https://user-images.githubusercontent.com/18264819/154943719-c44a9a98-8477-466f-8714-cd723f3956ae.png)

However, if I open rstudio with sudo, it does open and seems to work fine, but it also has the old outdated menus and file manager when I go to "Open file" for example. 
![image](https://user-images.githubusercontent.com/18264819/154943241-572ed98f-5440-4e29-b1a2-d6677609c274.png)

I've tried removing the .cache and .local/share files, and setting the permissions to 750, but that didn't seem to fix things. I tried reinstalling java, but that didn't fix it either. 

### Describe the behavior you expected
I expect Rstudio to open as normal without needing to use root privileges. 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

EDIT: Based on [this bug report](https://github.com/rstudio/rstudio/issues/4640) it seems somewhat similar to problems people have had with gpu issues. The fixes suggested there don't work for me (export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-gpu" and desktop.renderingEngine=software), but perhaps it's something related. Here is a diagnostics report when running as root
[Diagnostics_report.txt](https://github.com/rstudio/rstudio/files/8109561/Diagnostics_report.txt)
And the GPU report. 
[GPU_diagnostics.txt](https://github.com/rstudio/rstudio/files/8109508/GPU_diagnostics.txt)
 
I've also tired creating a new user and opening rstudio from that login, but I get the same error.

**Comment by luccastermans** [comment]
I have exactly the same problem. Starting with sudo indeed helps.  I am on Debian 10, bookworm/sid

**Comment by dsmaynard** [comment]
It's seems to be the same issue discussed [here](https://github.com/rstudio/rstudio/issues/9854#issuecomment-1046321775). Opening rstudio with the --no-sandbox option ($ rstudio-bin --no-sandbox) works for me, but it would be ideal to find another solution that doesn't come with the added vulnerabilities.

**Comment by ronblum** [comment]
Thank you for raising the issue, and thank you @dsmaynard for addressing the workaround! I am closing this as a duplicate for https://github.com/rstudio/rstudio/issues/9854, which is the main discussion of this problem.
