### ISSUE TITLE
Print dialog ignores page selection

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#10648]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.0+443 "Prairie Trillium" Release
    (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for macOS
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 
    Chrome/69.0.3497.128 Safari/537.36
    OS Version      : macOS Catalina 10.15.7
    R Version       : 4.1.0 (but not involved)

### Steps to reproduce the problem

Open a medium to large source file. 

Choose `File | Print...` to open the print preview.

Click on the Printer icon to open the print dialog.  (I also chose two-sided printing, as shown in the attached screenshot.)

Click on Print.  

### Describe the problem in detail

The full file prints.  It printed two sided, but all pages, not just the two I selected.

### Describe the behavior you expected

I should only have seen pages 13 and 14.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dmurdoch Thank you for raising the issue! At the risk of wasting more paper...
1. Does the issue occur only with two-sided printing, or one-sided as well?
2. I'm probably stating the obvious, but does this work correctly for documents in other applications?

**Comment by dmurdoch** [comment]
1.  Same problem one-sided.
2. Usually the page selection works.  Just confirmed it in Textedit, which uses a slightly different layout for the print dialog:
![Screen Shot 2022-02-22 at 10 38 22 AM](https://user-images.githubusercontent.com/1935680/155166345-a27c3beb-f81e-46e8-80ce-f2761b4a8bdd.png)

**Comment by ronblum** [comment]
@dmurdoch Thank you for investigating! I'll try to reproduce this. A couple more questions:
3. It probably doesn't make a difference, but is this an R source file or R Markdown? I just want to make sure that I try to emulate your experience as closely as possible when trying to reproduce.
4. I see that you're using our brand new release—excellent! Do you by chance know if this worked correctly or failed in previous versions?

**Comment by dmurdoch** [comment]
3.  I've seen it in both R code and C++ code.
4. I just updated today, after seeing it in the previous release.  I forget what the previous version was, but it was quite recent, 2021.09.xxx .

**Comment by dmurdoch** [comment]
The problem appears to still be present in RStudio 2022.07.1 Build 554.

**Comment by dmurdoch** [comment]
Sorry, I can't test for about a week -- I'm at a cottage with very limited bandwidth.

**Comment by dmurdoch** [comment]
Testing <https://dailies.rstudio.com/version/2022.11.0-daily+150>:  it appears to be fixed now.

**Comment by kevinushey** [comment]
Glad to hear it -- thanks for taking the time to test!
