### ISSUE TITLE
Set "copy to clipboard" (plots) default size

### ISSUE THREAD

**Issue by maxpel** [rstudio/rstudio#10644]
I regularly use the useful "copy to clipboard" feature in the Rstudio plots pane. The default width and height is a bit too low for me, so I always double it. Often, I forget to set "maintain aspect ratio" and I end up distorting the plot. Is there any way to set the default width and height or, even better, to "scale" it (to double the current default for example, similar to the parameter in ggsave)? This would save a lot of time, especially for the early collaborative phase of a project that involves a lot of quickly sharing graphs. I tried to search for this feature and couldn't find any hint hat it already exists, therefore I wanted to file this request.

**Comment by ronblum** [comment]
@maxpel Thank you for raising this! 

@kevinushey Do you know if there is any to do what @maxpel describes above?
