### ISSUE TITLE
OPENBLAS_CORETYPE Ignored by RStudio Server

### ISSUE THREAD

**Issue by yulijia** [rstudio/rstudio#10641]
Hi,

I want to report a bug similar to https://github.com/rstudio/rstudio/issues/9969

 

### System details

    RStudio Edition :  Server
    RStudio Version : Version 1.4.1717
    OS Version      :  Debian GNU/Linux 11 (bullseye)
    R Version       :  4.1.1 (2021-08-10) -- "Kick Things"

### Steps to reproduce the problem and  Describe the problem in detail

In the terminal, I set up `export OPENBLAS_CORETYPE=Nehalem` in my `HOME/.bashrc` file, and I can run the R in the terminal with correct openblas settings, also get the right calculation result.

```r
pca <- irlba::irlba((matrix(rnorm(10000000), ncol = 1000)), nv = 50)
pca$u[1:6, 1:6]
```

![right_answer](https://i.imgur.com/4hsAIpS.png)

However, using the Rstudio server, whatever I export the variable in `.Renviron` file or set it manually in Rstudio server Console `Sys.setenv(OPENBLAS_CORETYPE="Nehalem")`,  when running my code in the Rstudio server, I found that this `OPENBLAS_CORETYPE` will be ignored, and I get the wrong calculation result (some value of principal components are incredible large).

![wrong_answer](https://i.imgur.com/4HesHfM.png)

 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@yulijia Thank you for raising this issue! Note that we've had two releases since 1.4.1717: Ghost Orchid and Prairie Trillium. Would you be able to try one of them out? Prairie Trillium 2022.02.0+443 is the latest, available at the bottom of https://dailies.rstudio.com/release/

(I realize, though, that upgrading RStudio Server is more involved than RStudio Desktop, so I also I understand any reluctance to update just yet.)

**Comment by jmcphers** [comment]
> whatever I export the variable in .Renviron file or set it manually in Rstudio server Console Sys.setenv(OPENBLAS_CORETYPE="Nehalem")

The problem is likely that you are setting this variable too late; many environment variables of this nature must be set before the session starts (by the time .Renviron is running the session has already begun). You might try setting this variable for the RStudio server process itself using your system's service manager. 

Alternately, RStudio Workbench runs R sessions inside a Bash session, so your .bashrc approach would work there. Docs: https://docs.rstudio.com/ide/server-pro/r_sessions/session_startup_scripts.html

**Comment by yulijia** [comment]
Hi, @jmcphers 
Thank you for your reply.
I read the Docs, and added `OPENBLAS_CORETYPE="Nehalem"` to `.Rprofile` in my home directory.
However, the problem is still there. 

Hi @ronblum 
Thank you for your reply.
Because I didn't have permission to update the Rstudio-server, I will contact my admin to see if we could update the Rstudio-server and to test the problem using the latest release.

**Comment by yulijia** [comment]
Hi @jmcphers,

Could you provide any suggestion in detail that what file (file name and path/folder) should be used for setting the variable `OPENBLAS_CORETYPE="Nehalem"`?

I tried to set up it in .Rprofile,  `Sys.setenv(OPENBLAS_CORETYPE="Nehalem")` , or,  in the .Renviron
`OPENBLAS_CORETYPE=Nehalem`. I can see the variable in the Rstudio console via using `Sys.getenv()`, but it doesn't work. 


Many thanks.

**Comment by kevinushey** [comment]
Hi @yulijia, as @jmcphers said, setting it in the `.Rprofile` would be too late -- you need to set it earlier, before the R session is launched. So this advice still applies:

> You might try setting this variable for the RStudio server process itself using your system's service manager.

**Comment by yulijia** [comment]
Quick feedback, our server admin has tried to set up the environment variable in /etc/rstudio/env-vars, doesn't work. I couldn't find the `OPENBLAS_CORETYPE`  when applying `Sys.getenv()`

**Comment by jmcphers** [comment]
`/etc/rstudio/rsession-profile` is only applicable to RStudio Workbench -- are you using the open source edition?

**Comment by yulijia** [comment]
I use the Rstudio-server 

> RStudio Server
Version 1.4.1717
© 2009-2021 RStudio, PBC
"Juliet Rose" (df86b69e, 2021-05-24) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36


Because we didn't know which configure file should be used to set up variables for Rstudio server process, we tried several options and may likely edit the useless configure files.

**Comment by yulijia** [comment]
Upgrade Rstudio-server to the latest version. Still have the issue.

> RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36

**Comment by yulijia** [comment]
Our server admin solved this problem by creating a new script to exec the real rsession with the environment variable.

The new rsession file (rsession.wrapper) is

```
# Replace /usr/lib/rstudio-server/bin/rsession by this script:
#   cd /usr/lib/rstudio-server/bin/
#   mv -i rsession rsession.real
#   cp -ip rsession.wrapper rsession
# (may need to re-do at any update of rstudio-server).

# The docs say:
#   https://docs.rstudio.com/ide/server-pro/r_sessions/r_executable_and_libraries.html
#     Profile Script Execution
#     RStudio launches R sessions under a bash login shell. ...
# but quite clearly that does NOT happen, it is started "directly".
#
# Somewhat similarly, the /etc/rstudio/rserver.conf option
# rsession-exec-command is not available in the free open-source version: see
#   https://community.rstudio.com/t/rsession-exec-command-value-returns-error-in-etc-rstudio-rserver-conf/20158
#   https://docs.rstudio.com/ide/server-pro/rstudio_server_configuration/rserver_conf.html
#
# Worse than just starting rsession "directly", it seems that rsession loads
# and initializes the various libraries without R or its settings, so by the
# time R is run, the OPENBLAS_NUM_THREADS and OPENBLAS_CORETYPE settings are
# ineffective.


export OMP_NUM_THREADS=1
export GOTO_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export OPENBLAS_CORETYPE=Nehalem

exec /usr/lib/rstudio-server/bin/rsession.real "$@"
```


I will close the issue in 2 days.

**Comment by schatzcleat** [comment]
@yulijia  This is the closest I've gotten to solving some memory management issues on my rstudio server open source instance. Alas when I try to set rsession.wrapper to rsession and start rstudio I get a connection error  `system error 8 (Exec format error) [child-path: /usr/lib/rstudio-server/bin/rsession]; OCCURRED AT rstudio::core::Error rstudio` 

Holding out hope that you may know what this is referring to/a way to fix. I am working in Ubuntu 24 and the most recent rstudio open source. 

Trying to have environment variables set before launch. 

Thanks! 

> Our server admin solved this problem by creating a new script to exec the real rsession with the environment variable.
> 
> The new rsession file (rsession.wrapper) is
> 
> ```
> # Replace /usr/lib/rstudio-server/bin/rsession by this script:
> #   cd /usr/lib/rstudio-server/bin/
> #   mv -i rsession rsession.real
> #   cp -ip rsession.wrapper rsession
> # (may need to re-do at any update of rstudio-server).
> 
> # The docs say:
> #   https://docs.rstudio.com/ide/server-pro/r_sessions/r_executable_and_libraries.html
> #     Profile Script Execution
> #     RStudio launches R sessions under a bash login shell. ...
> # but quite clearly that does NOT happen, it is started "directly".
> #
> # Somewhat similarly, the /etc/rstudio/rserver.conf option
> # rsession-exec-command is not available in the free open-source version: see
> #   https://community.rstudio.com/t/rsession-exec-command-value-returns-error-in-etc-rstudio-rserver-conf/20158
> #   https://docs.rstudio.com/ide/server-pro/rstudio_server_configuration/rserver_conf.html
> #
> # Worse than just starting rsession "directly", it seems that rsession loads
> # and initializes the various libraries without R or its settings, so by the
> # time R is run, the OPENBLAS_NUM_THREADS and OPENBLAS_CORETYPE settings are
> # ineffective.
> 
> 
> export OMP_NUM_THREADS=1
> export GOTO_NUM_THREADS=1
> export OPENBLAS_NUM_THREADS=1
> export OPENBLAS_CORETYPE=Nehalem
> 
> exec /usr/lib/rstudio-server/bin/rsession.real "$@"
> ```
> 
> I will close the issue in 2 days.

**Comment by yulijia** [comment]
“Hi @schatzcleat, this post isn’t related to the memory issue. Please try installing the RStudio Server daily build version to test if the memory issue still exists.
