### ISSUE TITLE
Rstudio interface Settings, theme backgrounds, Gui interfaces are different from other panel background themes

### ISSUE THREAD

**Issue by xiao55555** [rstudio/rstudio#10656]
options\appearance\Rstudio theme :Set only the other three screens to the same theme, and the Console (Gui) window remains modern
![86414051_p2_master1200](https://user-images.githubusercontent.com/75713273/155327852-bbacd4f8-9d88-4b1f-90fe-5a45b9fc2667.jpg)

**Comment by ronblum** [comment]
@xiao55555 Thank you for raising the issue! I can't reproduce it, though, in a recent version. A few questions:

1) What theme are you using?
2) Can you provide the following system details?

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :
