### ISSUE TITLE
No icon / desktop entry created for RStudio Electron on Linux

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10653]
### System details

    RStudio Edition : Electron Desktop (Linux Bionic)
    RStudio Version : 2022.06.0-daily+138
    OS Version      : Ubuntu Focal
    R Version       : Any

### Steps to reproduce the problem

- install RStudio Electron desktop on Linux
- Scenario One: Try to search for it (e.g. tap the Windows/Command key and type "rstudio")
- Scenario Two: From a terminal, execute `rstudio`

### Describe the problem in detail

- Scenario One: RStudio not found
- Scenario Two: RStudio starts but has a blank icon

### Describe the behavior you expected

- should be able to search for RStudio and execute it, and no matter how you start it should have the RStudio icon

(I know what's wrong here, just opening this to track it until I get to fixing it)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Now working on both DEB and RPM-based Electron desktop installs.

**Comment by kevinushey** [comment]
Verified on Ubuntu 20.04 with 2022.06.0-243.

<img width="394" alt="Screen Shot 2022-03-28 at 4 38 21 PM" src="https://user-images.githubusercontent.com/1976582/160504560-7135e2a2-770e-43f1-accf-c551fd09c005.png">

<img width="186" alt="Screen Shot 2022-03-28 at 4 38 06 PM" src="https://user-images.githubusercontent.com/1976582/160504565-090d37e4-3a79-48a8-88b1-ed2a5becd473.png">
