### ISSUE TITLE
Select columns displayed in data viewer

### ISSUE THREAD

**Issue by tiredofmakingnewusernames** [rstudio/rstudio#10667]
Currently, the data viewer displays all columns that can fit on the screen, with the option to scroll right to see more.  With wide data,  it would be helpful to have the option to choose which columns are displayed.  Ideally, this would come in the form of a button in the upper left of the data viewer.  Once pressed, the list of variable names would display in a drop-down box with checkboxes next to each, allowing one to select the variables they want to see.

Thank you

**Comment by ronblum** [comment]
@tiredofmakingnewusernames Thank you for the suggestion! We'll review it as part of our ongoing development of RStudio.
