### ISSUE TITLE
create debian-10 build image

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10676]
Per https://www.rstudio.com/about/platform-support/ we stop supporting debian9 in June 2022, but continue supporting debian10 and 11 for several more years each.

Attempting to build Electron on debian9 has proven difficult due to old packages, so we should look at creating a builder based on debian 10 to produce builds of spotted-wakerobin.

**Comment by mikebessuille** [comment]
Also: include in the NEWS file for SW that we no longer support Debian 9.

**Comment by mikebessuille** [comment]
This isn't strictly an Electron issue, but I'm moving it to the electron milestone because that's the project that needs this done, and there isn't any time available otherwise.

**Comment by gtritchie** [comment]
Debian-10 Electron builds now available: https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/debian10/

I installed and ran the first build on Debian 11. Closing this issue.
