### ISSUE TITLE
Error when switching to visual mode of R Markdown and Quarto documents

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10674]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-2022.06.0-daily-146 electron
    OS Version      : MacOS 12.1
    R Version       : 4.2.0 devel

### Steps to reproduce the problem

1. Open a new R Markdown or Quarto documents.
2. Switch to the visual editor if not already in this mode.

### Describe the problem in detail

An error pops up, and the visual mode is just a blank screen with a spinning circle.

Note that you can switch back to source mode and it'll work fine.

### Describe the behavior you expected

The visual editor should be usable.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
From the rsession log:

`2022-02-24T23:46:29.064467Z [rsession-gary] ERROR system error 2 (No such file or directory) [exe: /Applications/RStudio-SW-Electron-149.app/Contents/Resources/MacOS/quarto/bin/pandoc]; OCCURRED AT rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:819; LOGGED FROM: rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:821
2022-02-24T23:46:29.064467Z [rsession-gary] ERROR system error 2 (No such file or directory) [exe: /Applications/RStudio-SW-Electron-149.app/Contents/Resources/MacOS/quarto/bin/pandoc]; OCCURRED AT rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:819; LOGGED FROM: rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:821`

**Comment by gtritchie** [comment]
Note this scenario works for me in a dev config, but does repro with package build per above error message.

**Comment by samperman** [comment]
RStudio Cloud is hitting this issue when opening projects that were created with previous versions of the ide: https://community.rstudio.com/t/pandoc-error-when-knitting-rmd/131131

**Comment by kippandrew** [comment]
I suspect the issue here is related to stale data when resuming a session. Creating a new session seems to correct this.

**Comment by kevinushey** [comment]
This issue is tracking the different path to `pandoc` specifically in the context of the Electron rewrite; I think the issue seen in https://community.rstudio.com/t/pandoc-error-when-knitting-rmd/131131 is slightly different.

The underlying cause is probably the same -- the path to the bundled version of `pandoc` has changed. RStudio broadcasts its `pandoc` path via the `RSTUDIO_PANDOC` environment variable; my guess is that old sessions are retaining the "old" pandoc path, which no longer exists. A session restart would likely force that to refresh to the new path.

**Comment by aronatkins** [comment]
Related to pandoc -- the Quarto installation also appears to be incomplete.

From the "Jobs" pane when attempting to render a Quarto project:

```
/Applications/RStudio.app/Contents/Resources/app/bin/quarto/bin/quarto: line 77: cd: /Applications/RStudio.app/Contents/Resources/app/bin/quarto/bin/../share: No such file or directory
ERROR: TypeError: Module not found "file:///Users/aron/dev/rstudio/standalone/cloud-execution/editor/tools/yaml/yaml-intelligence-resources.json".
```

From a terminal:

```bash
/Applications/RStudio.app/Contents/Resources/app/bin/quarto/bin/quarto --version
#=> /Applications/RStudio.app/Contents/Resources/app/bin/quarto/bin/quarto: line 77: cd: /Applications/RStudio.app/Contents/Resources/app/bin/quarto/bin/../share: No such file or directory
#=> cat: /Users/aron/dev/rstudio/connect/version: No such file or directory
```

**Comment by Enchufa2** [comment]
This error also happens when Quarto is disabled. In Fedora, we build RStudio with `-DQUARTO_ENABLED=FALSE`, and yet this path to pandoc is hardcoded somewhere?

**Comment by Enchufa2** [comment]
Here it is guarded by an `ifdef`:

https://github.com/rstudio/rstudio/blob/e400bbf755174d8fb74691d22f03160d6a4b0c89/src/cpp/session/include/session/SessionConstants.hpp#L140-L144

Does this mean that setting `-DQUARTO_ENABLED=FALSE` for cmake counts as defined?

The path also appears here:

https://github.com/rstudio/rstudio/blob/e400bbf755174d8fb74691d22f03160d6a4b0c89/src/cpp/session/session-options.json#L693-L699

but I'm unsure about the role of this file. For further info, in a build with `-DQUARTO_ENABLED=FALSE` I see:

```r
Sys.getenv("RSTUDIO_PANDOC")
[1] "/usr/libexec/rstudio/bin/quarto/bin"
```

and should be `/usr/libexec/rstudio/bin/pandoc` instead. Any guidance on how to properly build RStudio with Quarto completely disabled would be appreciated.

**Comment by kevinushey** [comment]
Right now, in CMake we control `QUARTO_ENABLED` here:

https://github.com/rstudio/rstudio/blob/fe46875f579a13cfb0dcbc7bbad716cb14377212/CMakeGlobals.txt#L231-L240

Unfortunately, we don't provide any facilities for letting users override that value at the CMake configuration step so we probably need to add a check for that.

**Comment by Enchufa2** [comment]
Ok, so I'll patch `CMakeGlobals.txt` directly for now to disable Quarto in all cases.

Has the `src/cpp/session/session-options.json` file any impact in the build process? Should I patch it too?

**Comment by kevinushey** [comment]
Good question. In this case, I think it's ignored in this case as we use a different default value depending on whether Quarto is enabled or not, so the value in `session-options.json` is effectively ignored.

That said, one could also set an `external-pandoc-path` R session option to override the path to pandoc with their own altogether; that is, by creating a file at `/etc/rstudio/rsession.conf` and adding something like:

```
external-pandoc-path: /path/to/pandoc
```

But patching the RStudio build here is probably still preferable.
