### ISSUE TITLE
Inserting emojis with menus is case-sensitive

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10671]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.02.0+443
    OS Version      : MacOS 12.1 and Ubuntu 20.04 via Chrome on MacOS 12.1
    R Version       : N/A

### Steps to reproduce the problem

1. Open an R Markdown document in visual mode.
2. <kbd>Insert -> Special Characters -> Insert Emoji</kbd>
3. In the "emoji name" text box, type `GRIN` in all upper case,
     - All the emojis are gone (bug),
4. Replace the word with `grin` in all lower case,
    - Emojis that match "grin" remain,
5. Click in the document.
6. Type `:grin` in all lower case.
    - Emojis that match "grin" remain,
7. Click in the document.
8. Type `:GRIN` in all uppdate case.
    - Emojis that match "GRIN" remain, the same ones as with "grin".

### Describe the problem in detail

Inserting emojis with the drop down menus is case sensitive (3).

<img width="460" alt="Screen Shot 2022-02-23 at 11 09 46 PM" src="https://user-images.githubusercontent.com/31009952/155529423-0b2a3c5b-4139-4004-8933-cfa40f09a323.png">

### Describe the behavior you expected

Inserting emojis in this way should be case insensitive, like insert in the document with `:` (4, 6, 8).

<img width="460" alt="Screen Shot 2022-02-23 at 11 09 56 PM" src="https://user-images.githubusercontent.com/31009952/155529505-7f8a6b91-a4af-4f22-9b42-90cb75cc6e23.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Fixed with: https://github.com/rstudio/rstudio/commit/3c9254ca1c82fdaf049a93f3068a3c05010dac20

**Comment by ronblum** [comment]
Verified using the above steps in RStudio Desktop 2022.11.0+166 on MacOS 13.
Tested using visual mode in both R Markdown and Quarto documents.
