### ISSUE TITLE
Push-button-deploy to Rsconnect: "Could not find files to deploy: Error occurred while executing method"

### ISSUE THREAD

**Issue by cropland-bv** [rstudio/rstudio#10672]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.2.0.443
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.1.1 (2021-08-10)

### Steps to reproduce the problem
1. Press blue publishing button.

### Describe the problem in detail
After upgrading R version 3.6.3 to R version 4.1.1 and upgrading RStudio the following error occurred while trying to publish application to Rsconnect:
![image](https://user-images.githubusercontent.com/90844360/155529960-90305cce-6118-48e2-bdcb-3e8f10277df4.png)

The Console gives the following error message:
`Error in rle(toplevel) : 'x' must be a vector of an atomic type` 

Related issue: https://github.com/rstudio/rstudio/issues/3754
But no special character in path. 

Error occurs while trying to deploy different applications with varying paths.

### Describe the behavior you expected
Expected a clear error explanation or the ability to publish application.

**Comment by ronblum** [comment]
@cropland-bv Thank you for notifying us of this! Can you please provide a sample document for which this occurs—it can be just a few lines. This will help me try to reproduce the issue. Thanks!

**Comment by cropland-bv** [comment]
Error occurs not while trying to publish  Shiny Web applications, but not while publishing a RMarkdown document.
Code example:
`
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("Old Faithful Geyser Data"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
        ),

        # Show a plot of the generated distribution
        mainPanel(
           plotOutput("distPlot")
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    output$distPlot <- renderPlot({
        # generate bins based on input$bins from ui.R
        x    <- faithful[, 2]
        bins <- seq(min(x), max(x), length.out = input$bins + 1)

        # draw the histogram with the specified number of bins
        hist(x, breaks = bins, col = 'darkgray', border = 'white')
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
`

Regarding the RStudio Desktop version, I don't know the specific version but probably 1.3.

**Comment by wimpel** [comment]
same problem here... No special characters in filenames..
RStudio 2022.02.0 Build 443

**Comment by ronblum** [comment]
Thank you both! I can reproduce this in Prairie Trillium on Windows 10, while it continues to work on MacOS 12.1, and worked previously in Ghost Orchid.

Triage: regression in Prairie Trillium, strong candidate for patch.

**Comment by gtritchie** [comment]
I repro'd this problem with R 3.6.3, on Windows-10, with RStudio 2022.2.0.443. This was a clean Windows-10 machine where only R 3.6.3, RTools 3.5, and that version of RStudio were installed.

So, not related to the upgrade to R 4.1.1 mentioned in the repro steps; purely an RStudio thing it appears.

**Comment by gtritchie** [comment]
This problem started with build 416 on 2022-02-02; build 415 works.

**Comment by kevinushey** [comment]
Thanks for the bug report. As a workaround, you can execute:

```
.rs.files.restoreBindings()
```

before attempting to deploy your application. We'll try to get this fixed soon.

**Comment by kevinushey** [comment]
A fix will be part of https://github.com/rstudio/rstudio/pull/10682; the underlying issue here is that we were failing to expand tilde-prefixed paths in our `list.files()` shim.

**Comment by jmcphers** [comment]
Also spotted on Community recently: https://community.rstudio.com/t/2022-02-0-443-broke-my-ability-to-publish-content/130506

**Comment by astayleraz** [comment]
I verified this is working as expected on Windows 10 with version 2022.02.0+455. I was able to publish successfully a shiny app as well as other file types and also got the expected output in the steps in https://github.com/rstudio/rstudio/issues/10679 Lower level automation tests were added so I did not add any end to end tests for this at this time, but I think it might warrant us having end to end tests of publishing all file types. Closing issue.

**Comment by samrit2442** [comment]
> 

Thanks a lot. It is working after executing that code.

**Comment by costavale** [comment]
still the same error, the deploying worked only after passing the code 
.rs.files.restoreBindings()

**Comment by costavale** [comment]
2022.02.0 with R updated this morning to 4.1.3
I am working with Windows 11 and I run into this error today after updating R to 4.1.3

**Comment by astayleraz** [comment]
@costavale which version of 2022.02.0 exactly? The version of R should not matter I do think.

**Comment by costavale** [comment]
Build 443, "Prairie Trillium" Release (9f796939, 2022-02-16) for Windows

**Comment by jgutman** [comment]
Unfortunately 2022.02.0+443 is the version that still contains the error. We're about to release a patch release for Prairie Trillium that will contain this fix, but in the meantime if you'd like to try the fixed version you can download 2022.02.1+457 from here: https://dailies.rstudio.com/rstudio/prairie-trillium/

**Comment by costavale** [comment]
Thank you for the suggestion. With the 457 version, now the deployment is working again!

**Comment by ronblum** [comment]
@costavale Glad to hear it, and thank you for confirming!

**Comment by enzedonline** [comment]
Good to find this, was trying to figure out what I was doing wrong ;-) 
Can confirm the upgrade fixes the problem, thanks!
