### ISSUE TITLE
Duplicate option "Enable X11 clipboard monitoring" 

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#10688]
![image](https://user-images.githubusercontent.com/73080/155888792-de5bc8de-d231-43ae-b354-10a240bf502f.png)

Seen on ubuntu 20, *not* seen on windows. On build 2022.02.0 Build 443

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0 Build 443
    OS Version      :  Ubuntu 20
    R Version       :  4.1.2

### Steps to reproduce the problem
Open Tools / Global options/ General / Advanced.
- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
The second one should read "Show full path to project in window title". Almost certainly a regression from the localization work.

Here's the same pane on Mac; same problem (minus the first "Enable X11 clipboard monitoring" which isn't an option on Mac or Windows).

![Screen Shot 2022-02-27 at 17 26 42](https://user-images.githubusercontent.com/10569626/155906744-84c84289-9eab-4dc8-9b27-f9e82f98cc12.png)

**Comment by gtritchie** [comment]
This is a regression in the Prairie Trillium release.

**Comment by mikebessuille** [comment]
We should fix in SW and backport to the PT patch branch

**Comment by gtritchie** [comment]
I've already got a fix made over the weekend. Assigning back to me.

**Comment by gtritchie** [comment]
Fix has been merged into prairie-trillium, and ported forward to main (both open-source and pro).

**Comment by romainfrancois** [comment]
Verified on spotted wakerobin build 160. 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/2625526/156147014-cf5485fa-1c90-40fa-ab8a-6a78c7599faf.png">

**Comment by dfalty** [comment]
Also verified the fix made it to the latest PT patch release 2022.02.1-456
