### ISSUE TITLE
Open project in a new R session doesn't do anything (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10687]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : 2022.06.0-daily+155
    OS Version      : macOS 12.2.1
    R Version       : 4.1.2

### Steps to reproduce the problem

- Try to open a previously-opened project in a new R session via the little widget in the Projects dropdown

![Screen Shot 2022-02-26 at 12 00 21](https://user-images.githubusercontent.com/10569626/155855885-d83e5a15-43a7-49b3-bc6e-c4b593997347.png)

### Describe the problem in detail

- Nothing happens

### Describe the behavior you expected

- A new IDE main window loads the selected project

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Writing down some notes:

The logic for opening a project in a new window eventually lands here.

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/node/desktop/src/main/application-launch.ts#L37-L40

The Qt analogue for this lives here:

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/cpp/desktop/DesktopPosixApplicationLaunch.cpp#L198-L224

The argument list can accept the path to a project file as the first argument; e.g. as done here:

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/cpp/desktop/DesktopGwtCallback.cpp#L1140-L1142

And then we have a trail of logic for parsing the opened project file (or other files as well) early on in main, here:

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/cpp/desktop/DesktopMain.cpp#L680-L694

So, we need to replicate this workflow in Electron, following mostly the same steps. I'll need to also learn how to make sure this plays nicely with yargs.

**Comment by kevinushey** [comment]
Other breadcrumbs:

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/cpp/desktop/DesktopMain.cpp#L193-L195

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/cpp/desktop/DesktopMain.cpp#L226-L229

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/cpp/desktop/DesktopMain.cpp#L198-L202

https://github.com/rstudio/rstudio/blob/7c71d560b0bb8c5bd02f08272976f7c8bcfe7039/src/cpp/core/include/core/r_util/RUserData.hpp#L21-L23

So it seems like most of the information about the project to be launched are communicated through these environment variables, and we should hopefully be good to go if those are read and set appropriately at startup time.

**Comment by gtritchie** [comment]
Verified with Electron build 2022.06.0-daily+244 on Mac and Windows.
