### ISSUE TITLE
Jump to folder of current opened file in File panel

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#10680]
I have a project with multiple folders, and often need to switch between different files, like a document, Rmarkdown, files in Shiny app folder etc. It's easy to jump to a file in RStudio using ctrl + ., however if I need to edit/manipulate files under certain folder, I have to navigate step by step, which can be slow as Files Panel seemed need some time to refresh when changing folder.

I'd suggest to have a button, once clicked will change Files Panel to the folder of current opened file in editor. This way it'll be much easier to switch between different context.

The feature should be simple to implement. Actually if rstudioapi package had some support on Files panel, users can implement this feature or other related feature by themselves.

**Comment by ronblum** [comment]
@dracodoc Thank you for the suggestion! I'll double-tag this as both "files pane" and "rstudioapi" to reflect your last suggestion, for review as we continue RStudio development.

**Comment by jmcphers** [comment]
We have one already! Right-click on the tab and select "Set Working Directory":

<img width="269" alt="image" src="https://user-images.githubusercontent.com/470418/155773131-34412a8e-47fc-40e6-9fee-b0cf00e2e748.png">

This will navigate the Files panel and set your console working directory at the same time, putting you in context for the file.

**Comment by jmcphers** [comment]
The other useful setting here is "Synchronize Working Directory":

<img width="427" alt="image" src="https://user-images.githubusercontent.com/470418/155773354-8492af18-1fb4-4d66-9073-8bf2e607637c.png">

So another way to do this would be to (1) enable this option, and then (2) set a keybinding for the "set working directory to current document". That'll give you a hotkey to do what you want.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/470418/155773464-ac7ec4cc-3a65-4f46-988e-904d2ccd4e0f.png">

**Comment by dracodoc** [comment]
If I'm understanding correctly, this working directory is the working directory in R with `getwd()` and `setwd`.

In my R development I actually never make changes to working directory. I either use absolute path or use relative path to R project root. If I keep switching the working directory it could cause lots of problems and that's definitely a good practice.

**Comment by jmcphers** [comment]
You're right, none of the built in gestures will let you navigate the Files panel without also changing the working directory. 

> Actually if rstudioapi package had some support on Files panel, users can implement this feature or other related feature by themselves.

You mean like this? :-)

**Comment by dracodoc** [comment]
Yes! I checked the online document site before submitting the feature request and didn't find it. The online documentation looks to be too old
https://rstudio.github.io/rstudio-extensions/pkgdown/rstudioapi/reference/index.html

I can implement this feature in my own rstudio addin now, thanks! Feel free to close this request if this doesn't fit to the official UI plan.

**Comment by dracodoc** [comment]
I implemented the feature in my [addin](https://github.com/dracodoc/mischelper) so this request can be closed.

**Comment by ronblum** [comment]
@dracodoc That's awesome!
