### ISSUE TITLE
Implement Electron rendering engine settings

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10695]
In Qt desktop we provide several ways to control the rendering engine used by Chromium. This is usually to work around problems on specific platforms/graphics cards/resolutions, etc.

- command-line switches
- UI in the "Choose R Installation" dialog shown at startup on Windows
- Global Options / General / Graphics

We need to ensure these are properly plumbed to work with Electron.

There's a related unimplemented callback, as well: `desktop_set_desktop_rendering_engine`.

**Comment by kevinushey** [comment]
For testing:

- Confirm that if you hold down Ctrl while launching RStudio, you get the "Choose R" dialog, with an option to select the rendering engine at the bottom. (Windows only)

- Confirm that you are prompted to restart RStudio after changing the rendering engine through the aforementioned dialog. (Windows only)

- Use Help -> Diagnostics -> Show GPU Diagnostics to confirm whether the requested rendering engine is being honored. (If you select software rendering, you should see most "features" using software rendering)

- Confirm that the same rendering engine options can be changed via Tools -> Global Options -> Advanced, and that the options displayed + used there also reflect the same options selected in the Choose R dialog.

**Comment by ronblum** [comment]
Checked in the following, using the above guidance, on:
- MacOS 12.4
- Red Hat 8.5
- Windows

All pass, with one exception: On Red Hat, when using "OpenGL for Embedded Systems," Electron appears to be using software acceleration, while Qt is using hardware acceleration; and the `OpenGL` property is set to `Disabled`. Here are the values under "Graphics Feature Status" as a comparison:

*Electron*
![openglembedded_en.png](https://codetreeusercontent.s3.amazonaws.com/uploads/d1c3b22a-0659-4f80-b80e-c7af91a1332b/openglembedded_en.png)

*Qt*
![openglembedded_qt.png](https://codetreeusercontent.s3.amazonaws.com/uploads/d1c3b22a-0659-4f80-b80e-c7af91a1332b/openglembedded_qt.png)

[Thank you @kevinushey for explaining to me that this is primarily about the settings, etc., and not a thorough evaluation of the rendering engines, per se.]

**Comment by ronblum** [comment]
Note that that's on Red Hat 8.5—on Ubuntu 20.04.3, OpenGL is enabled and hardware acceleration is being used:
<img width="550" alt="ubuntu" src="https://user-images.githubusercontent.com/31009952/168102491-af4f17f7-c4fc-4800-8e71-b121a85c1c83.png">

**Comment by kevinushey** [comment]
> All pass, with one exception: On Red Hat, when using "OpenGL for Embedded Systems," Electron appears to be using software acceleration, while Qt is using hardware acceleration; and the OpenGL property is set to Disabled.

This seems fine to me, since (presumedly) the system is really a desktop system and not an embedded system.
