### ISSUE TITLE
Autocompletion: names with diacritics are not wrapped with backticks

### ISSUE THREAD

**Issue by b4D8** [rstudio/rstudio#10692]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0+443
    OS Version      : Debian GNU/Linux 11 (bullseye)
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

Create the following list of list:

```r
object <- list(
  "non syntactic" = list(
    shown = "value"
  ),
  "with_diàcritic" = list(
    not_shown = "value"
  )
)
```

Then try navigate the list in the console (`|` represents the current cursor position): 
`object$|` here Rstudio correctly offers the 2 subitems' names.
When you select `non syntactic` (press `ENTER`) it wraps it with backticks (``object$`non syntactic` ``) while it doesn't when you select `with_diàcritic` (`object$with_diàcritic`).
As a result, it's not possible to further navigate the list (`object$with_diàcritic$|` doesn't offer anything).

### Describe the problem in detail

The problem is that some characters (including diacritics `é`, `è`, `à` etc.) are not properly wrapped with backticks during navigation through auto-completion.

### Describe the behavior you expected

My understanding is that RStudio should have wrapped `with_diàcritic` with backticks just like it does with `non syntactic` as ``object$`with_diàcritic`$|`` correctly offers `not_shown`.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@b4D8 Thank you for raising the issue! I can reproduce this perfectly on MacOS 12.1 using
- RStudio Desktop 2021.09.2+382
- RStudio Desktop 2022.02.0+443

We'll review this as we continue development of RStudio.

**Comment by kevinushey** [comment]
The underlying issue here is really that, even though `with_diàcritic` is a valid identifier (in UTF-8 locales), RStudio is parsing it as 3 separate tokens:

<img width="233" alt="Screen Shot 2022-03-01 at 10 07 00 AM" src="https://user-images.githubusercontent.com/1976582/156224380-4c5fb776-56b4-49f4-bfde-b4ed44fab48d.png">

I think we could update our Ace highlight rules to accept arbitrary unicode identifiers to support this.

**Comment by kevinushey** [comment]
I think this may have been fixed in the latest daily builds.

<img width="241" alt="Screen Shot 2022-09-15 at 11 20 59 AM" src="https://user-images.githubusercontent.com/1976582/190480510-40e7e376-d975-4f23-b828-430d23336808.png">

**Comment by kevinushey** [comment]
That, and identifiers containing diacritics should be handled without issue with R 4.2.x on Windows I believe.

**Comment by jonvanausdeln** [comment]
This appears to be working in latest daily 2022.12.0-daily+263

![image](https://user-images.githubusercontent.com/6433789/195463839-005254b6-de57-4d65-ab89-05fdcdf00b0f.png)
