### ISSUE TITLE
shinyapps.io deployment failure "Error in rle(toplevel)" from Windows Documents folder, latest version of RStudio

### ISSUE THREAD

**Issue by ellisp** [rstudio/rstudio#10701]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0 Build 443
    OS Version      : Windows Version 10.0.19044 Build 19044
    R Version       : 4.1.1

### Steps to reproduce the problem
- Create a new RStudio project as a subfolder on in your "Documents" 
- create a Shiny app
- select the "Publish application" button

### Describe the problem in detail

Rstudio returns a "could not find files to deploy" error as a popup window:

![image](https://user-images.githubusercontent.com/5740570/156085162-15e55d4f-7e4a-4067-ab44-6420711d85a8.png)

...and in the console you get this error

```
Error in rle(toplevel) : 'x' must be a vector of an atomic type
```
Searching the web reveals this is an expected pattern if you have special characters in your file path. However, there are no special characters in my file path:

```
> getwd()
[1] "C:/Users/peter.ellis/Documents/shiny-reprex"
> list.files("webtool", recursive = TRUE)
[1] "server.R" "ui.R"  
```

And, until the latest RStudio update, these shiny apps deployed fine. 

If I copy the project directly to the C: drive, it deploys fine.

### Describe the behavior you expected

Expected the app to deploy to shinyapps.io

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
This is being tracked via #10672 and a fix is in the works.
