### ISSUE TITLE
matplotlib only renders properly with the plot panel fully extended

### ISSUE THREAD

**Issue by matiasandina** [rstudio/rstudio#10700]
### System details

    RStudio Edition : Desktop
    RStudio Version : "Prairie Trillium" Release (9f796939, 2022-02-16) for Ubuntu Bionic
    OS Version      :  Ubuntu 20.04 LTS
    R Version       :  3.6.3

### Steps to reproduce the problem

Run this code, make sure the plot panel is half-way through

```
import pandas as pd
import matplotlib.pyplot as plt

# Import CSV mtcars
data = pd.read_csv('https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/64f1660f38ef523b2a1a13be77b002b98665cdfe/mtcars.csv')
# Edit element of column header
data.rename(columns={'Unnamed: 0':'brand'}, inplace=True)

plt.figure(figsize=(5,5))
plt.plot(data.hp)
plt.show()

```

Expected output looks like this (panel fully extended)

![image](https://user-images.githubusercontent.com/7494967/156071071-cc55a576-5bbe-41e5-bd1f-2400e6c4d4e4.png)

With panel half-way, it looks like this and it can no longer be resized and re-rendered properly.

![image](https://user-images.githubusercontent.com/7494967/156071149-d1736862-79f7-4855-872e-d9adab9f22f0.png)

Similar issues with

```
data[["mpg"]].hist()
plt.show()

```

![image](https://user-images.githubusercontent.com/7494967/156071580-840700d9-5112-4b13-9da2-154bdd08f6de.png)

And half-way through

![image](https://user-images.githubusercontent.com/7494967/156071612-ea40e476-c477-433d-a393-475162cc52ee.png)

### Describe the problem in detail

When rendering the plot, this only renders properly if the plot panel is not collapsed midway (it doesn't matter what panel is on top of the plot panel, it matters that the plot panel is fully extended). By "render properly" I mean that  I can change the size of the plot using Zoom and the plot will re-render as normal R plots. The other plot does not respond to this, it stays always the same.

Here's the example with the panel half-way (the default size of the plot panel).

![image](https://user-images.githubusercontent.com/7494967/156213566-ae4bc868-51e7-42bd-98ef-992e00011317.png)

Here's the example with the plot panel fully expanded. Note I didn't just expand the panel (the previous plot does not render again when I do that, hence the error). I had to re-run the code, which works as expected when the panel is fully extended before the first rendering.

![image](https://user-images.githubusercontent.com/7494967/156213883-adeb73dd-ec5f-44eb-b23f-9bec0180c23a.png)

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@matiasandina Thank you for raising this! I'm not sure I understand what you mean about the plot panel being half-way through. Could you get a screen shot of RStudio Desktop with this layout, so that I can try to properly reproduce?

**Comment by matiasandina** [comment]
@ronblum Added some screen shots, hope it helps. Half-way through is the default panel order in Rstudio (doesn't work, plot doesn't render when changing sizes). Extended is with the Environment panel collapsed and the plot panel fully extended (the one that works).

I also add  here some examples when clicking zoom. You can see that I can re-render the plot as expected

![image](https://user-images.githubusercontent.com/7494967/156214392-cf6f881c-c3d4-4931-9f24-23d9689a3da1.png)

However, this is not the case for the plot originally rendered with the panel in the default mode.

![image](https://user-images.githubusercontent.com/7494967/156214563-c1816d5a-ede2-426c-83a3-c9f19a5e14b8.png)
