### ISSUE TITLE
ANSI escape code bind keystroke

### ISSUE THREAD

**Issue by DanielRivasMD** [rstudio/rstudio#10702]
Is there a way to bind an ANSI escape code to a keystroke? For example: '\xb1' to '3D'. Appreciated

**Comment by ronblum** [comment]
@DanielRivasMD I don't believe so. @jgutman Could you confirm that this is the case?

**Comment by ronblum** [comment]
@kevin Tagging you instead.

**Comment by kevinushey** [comment]
I don't think so, unfortunately. Can you explain a bit more your use case here? What is generating the escape code `\xb1`?

**Comment by DanielRivasMD** [comment]
Thanks for your response. I want to pass an ANSI escape code to trigger a sequence of characters. I know a way around this on RStudio, but I want to find another method to be used on the console/terminal.
