### ISSUE TITLE
dev.size() does not return the correct size in RStudio with 4K screen

### ISSUE THREAD

**Issue by mtennekes** [rstudio/rstudio#10723]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0 Build 443
    OS Version      :  Ubuntu 20.04.4 LTS
    R Version       :  4.1.2

### Steps to reproduce the problem

Run 

```r
dev.size(units = "cm")
```
and measure the graphics device

### Describe the problem in detail

`dev.size()` does not return the correct size with a 4K screen.

![Screenshot from 2022-03-02 10-29-11](https://user-images.githubusercontent.com/2444081/156335818-f8c1273a-f0f9-459d-af8e-bfd1700d6190.png)

On the left-hand-side, the R console is shown, and at the right-hand-side RStudio. The graphics devices of both are scaled such that they are the same size (more or less), which is measured at approximately 12.5 cm (both width and height).

### Describe the behavior you expected

I expected `dev.size(units = "cm")` to return two values around 12.5. RStudio seems to underestimate by factor of about 2, and the R Console to overestimate by factor 1.5.

Since I don't know whether this issue is caused by RStudio, or by grDevices, I'll contact both.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mtennekes Thank you for raising the issue! Is the R Console on the upper left the Console in RStudio Desktop, or R from a terminal? If it's the RStudio Console, what do you get with standalone R?

**Comment by mtennekes** [comment]
Upper left is the console from standalone R.

With a Full-HD screen my measurements are:

* manually with a ruler: 12.0 x 12.0 cm
* RStudio 9.7 x 10.6 cm
* Standalone R 11.6 x 11.6 cm

**Comment by mtennekes** [comment]
Peter Dalgaard gave some useful feedback on this issue in the r-help mailing list.

When I run xdpyinfo in got

screen #0:
  dimensions:    5120x2880 pixels (903x508 millimeters)
  resolution:    144x144 dots per inch

According to these specs my screen should have a sqrt((5120/144)^2 + (2880/144)^2) = 40.8" diagonal.

However, in practice it is 27", so that perfectly explains the 1.5 factor difference in the R terminal.

What I noticed is that in RStudio, dev.size() is not equal to par("fin"), which caused the problem for me. In the R terminal, these two are equal.
