### ISSUE TITLE
Edit snippets ghosting/blurred

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#10722]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.02.0 b443, release 2022-02-16
    OS Version      : Xubuntu 21.10 
    R Version       : 4.1.2 (2021-11-01) -- "Bird Hippie"
    NVidia driver 470.103.01

### Steps to reproduce the problem
Tools > Global Options > Code > Edit Snippets... > mousewheel scroll

### Describe the problem in detail
Edit snippets blurs rendering. Possibly since nvidia driver update. See video: https://youtu.be/YlGvKtlev_M

I've tried various different options in General > Graphics / Advanced but to no avail.
Also in /Advanced, "Enable X11 clipboard monitoring" is duplicated; the first one is selected for me, the second isn't.

### Describe the behavior you expected

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@SimonDedman Thank you for raising the issue! Does the issue only occur with Edit Snippets, but works correcty in other areas such as the source editor for R Markdown documents, etc.?

Also, please note that technically we only support the LTS versions of Ubuntu, currently 18.04 and 20.04. The next release we'll support is 22.04, which is currently in development with a release data of April 2022. We'll eventually support it, so I'm marking this for review in it.

Note: the duplicate option is covered in #10688 and is slated for an upcoming patch release of 2022.02.x.

**Comment by mikebessuille** [comment]
@simondedman, did you try software rendering, under Global Options -> General -> Advanced, in the rendering engine dropdown?

**Comment by SimonDedman** [comment]
Hi Mike, I did yeah.
