### ISSUE TITLE
Error: pandoc document conversion failed with error 61

### ISSUE THREAD

**Issue by Ale-mvd** [rstudio/rstudio#10735]
Tengo un problema cuando voy a tejer el Rmarkdown. Me sale el siguiente mensaje: 

Could not fetch http://127.0.0.1:21949/chunk_output/7C3931C55EC841F9/D48ED840/caeu87lybc7f1/00004e.png
HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 21949
  secure               = False
  requestHeaders       = []
  path                 = "/chunk_output/7C3931C55EC841F9/D48ED840/caeu87lybc7f1/00004e.png"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.connect: <socket: 584>: failed (Connection refused (WSAECONNREFUSED)))
Error: pandoc document conversion failed with error 61
Además: There were 50 or more warnings (use warnings() to see the first 50)
Ejecución interrumpida

**Comment by englianhu** [comment]
>Finally I think found a solution which works after installing R 3.4.4 and RStudio 1.1.442 at my new Laptop and getting the same troubles.
>
>What solved the problem was to create a Renviron file :
>
>`file.edit("~/.Renviron")`
>and setting there a local path like this `R_USER="C:/Users/my_name"`
>
>Now knitting with `self_contained: yes` is possible without error

The errors suppose not occur because that's human being and purposely use specific words...

---

Reference : 

- [Rmarkdown HTML Template produces pandoc error 61](https://stackoverflow.com/questions/47669535/rmarkdown-html-template-produces-pandoc-error-61)
- [I can't knit Rmd-files to pdf](https://community.rstudio.com/t/i-cant-knit-rmd-files-to-pdf/38187)

**Comment by englianhu** [comment]
>**Pandoc Error 61**
>
>For example: `Error: pandoc document conversion failed with error 61 or Could not fetch...`
>
>Try running RStudio as administrator (right click icon, select run as admin, see above instructions)
Also see if the specific package that was unable to be reached can be moved to C: library.

Source : https://epirhandbook.com/en/r-on-network-drives.html

By refer to above solution, try to run as admin but doesn't help, somebody take a look?

```
:~$ sudo rstudio
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/root/.local/share/rstudio/log/rdesktop.log'.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Empty filename passed to function
Empty filename passed to function
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5082, resource id: 39864422, major code: 40 (TranslateCoords), minor code: 0
```
