### ISSUE TITLE
"error: src/gwt/build.xml" when trying to install in Manjaro KDE

### ISSUE THREAD

**Issue by DavinDiaz** [rstudio/rstudio#10730]
I have been using RStudio for a while in my Manjaro installation, I first installed it via "yay -S rstudio-desktop-bin", but it suddenly started to fail, since it doesn´t launch correctly. 

I tried to install it through the git repository, with "yay -S rstudio-desktop-git", but I get the following error:

`  -> Extracting gwt-2.9.0.zip with bsdtar
==> Iniciando prepare()...
Checking module src/gwt/build.xml...
error: while looking for:
   </target>

   
   <property name="node.version" value="10.19.0"/>
   <property name="node.dir" value="../../dependencies/common/node/${node.version}"/>
   <condition property="node.bin" value="../../../${node.dir}/bin/node">
     <not>
        <os family="windows" />
     </not>
   </condition>
   <condition property="node.bin" value="${node.dir}/node.exe">
     <os family="windows" />
   </condition>

   
   <available
      property="node.bin"
      value="/opt/rstudio-tools/dependencies/common/node/${node.version}/bin/node"
      file="/opt/rstudio-tools/dependencies/common/node/${node.version}/bin/node"/>

   <property name="panmirror.dir" value="./panmirror/src/editor"/>
   <property name="panmirror.build.dir" value="./www/js/panmirror"/>

error: module failed: src/gwt/build.xml:82
error: src/gwt/build.xml: the module does not apply
==> ERROR: An error occcured at prepare().
    Canceling...
 -> error compiling: rstudio-desktop-git`

**Comment by WiseOther** [comment]
I had the same with Arch. Fortunately, solved in rstudio-desktop-bin.

**Comment by KnutJaegersberg** [comment]
Me too on Manjaro. Also, I cannot use the other rstudio-desktop distributions in the AUR. My guess is the latest kernel / gpu driver update broke something. Rstudio screen is just black when I start it up. So currently I have to use Rstudio-Server.

**Comment by bennour007** [comment]
> Me too on Manjaro. Also, I cannot use the other rstudio-desktop distributions in the AUR. My guess is the latest kernel / gpu driver update broke something. Rstudio screen is just black when I start it up. So currently I have to use Rstudio-Server.

I'm using Manjar with an LTS kernel and still having the same issue, it appeared out of no where, first when I had Rstudio working and then started ti have blank non-responsive screen. At some point, I lost hope and reinstalled manjaro again on my PC and couldn't for the love of god install Rstudio, the rstudio-desktop-bin is flagged out of date in the AUR, tried to install the rstudion-desktop-git but it gave me the same error on this issue, and here we are.

**Comment by bennour007** [comment]
> I had the same with Arch. Fortunately, solved in rstudio-desktop-bin.

Rstudio-desktop-bin is flagged out of date in the AUR.

**Comment by KnutJaegersberg** [comment]
This here helped me: 
https://forum.manjaro.org/t/rstudio-does-not-start-after-manjaro-update/104270

"It’s probably due to the glibc update. Older Electron apps are not fully compatible with it. The workaround right now is to open the app with --no-sandbox parameter. See the latest comments in the AUR package’s page: [AUR (en) - rstudio-desktop-bin 71](https://aur.archlinux.org/packages/rstudio-desktop-bin)"
