### ISSUE TITLE
When deploying some reticulate (/ Quarto?) content to RStudio Connect, manifests do not specify `python` unless `RETICULATE_PYTHON` is defined

### ISSUE THREAD

**Issue by toph-allen** [rstudio/rstudio#10736]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 172
    OS Version      : macOS
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Open the above build. Ensure that `RETICULATE_PYTHON` is unset
2. Open this project in the IDE [quarto-website-r-py.zip](https://github.com/rstudio/rstudio/files/8187964/quarto-website-r-py.zip)
3. Use push-button deployment to deploy to an RStudio Connect server

### Describe the problem in detail

Deployment fails with a series of error messages. Here's an example: [rstudio-connect.105.63.135.build_report.BrLSujGBmzicDnJ1.log](https://github.com/rstudio/rstudio/files/8187981/rstudio-connect.105.63.135.build_report.BrLSujGBmzicDnJ1.log)

Deployment will succeed if `RETICULATE_PYTHON` is set.

This issue did not occur until fairly recently. It looks like [src/cpp/session/modules/SessionRSConnect.cpp](https://github.com/rstudio/rstudio/blob/e1e8a2dd70868a625348355e634631414795efa9/src/cpp/session/modules/SessionRSConnect.cpp) includes some recent changes to do with `RETICULATE_PYTHON` handling which may be involved in this issue (h/t @aronatkins).

This seems to be the cause of https://github.com/rstudio/connect/issues/20879.

### Describe the behavior you expected

Deployment succeeds.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by toph-allen** [comment]
After @jgutman and I chatted on Zoom this afternoon, I realized that this required a small change to `rsconnect`, and since I was already working on that package, I went ahead and made the change: https://github.com/rstudio/rsconnect/pull/570

**Comment by jgutman** [comment]
Ultimately, the rsconnect fix will need to be published to CRAN, which will be planned before the next IDE release. If we find more users running into this issue, we can try to expedite that CRAN release and encourage users of the RStudio dailies to download the rsconnect package from Github as a workaround.
