### ISSUE TITLE
File explorer prompt causes extra lines to appear in console.

### ISSUE THREAD

**Issue by ReveStobinson** [rstudio/rstudio#10738]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      :  Windows 10 Enterprise, Build 18363
    R Version       : 4.1.0

### Steps to reproduce the problem
Call any of the following functions in the console, with whatever arguments you want:
`tcltk::tk_choose.dir()`
 `tcltk::tk_choose.files()`
`utils::choose.dir()`
`base::file.choose()`

### Describe the problem in detail

When calling any of the functions listed above, after the function is called, extra lines of blank space will appear in the console. Several lines appear immediately, and then lines continue appearing every so often (every 30-60 seconds) and do not stop. The console is still useable, and the cursor and next input `>` just sit at the bottom. But even after running other code, the random blank lines will continue to appear below the output of whatever you just ran. This problem then persists until RStudio is restarted.

The issue also occurs if any of the above functions are run from a script, either on their own or as part of a larger code block. It also occurs both with and without an RProject open.

This issue does not occur in the standard RGui Console, only in the RStudio Console.

Screenshot of console after a few function calls:
![Picture1](https://user-images.githubusercontent.com/21211494/156829701-1254ca3b-43ce-4161-82da-7c5450ce1422.png)

Screenshot of the same console a couple minutes later, with no input from me:
![Picture2](https://user-images.githubusercontent.com/21211494/156829707-38066a50-cee6-437c-9e15-9419a3a0f452.png)

### Describe the behavior you expected
No extra lines in the console

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
  - I cannot update R or RStudio, since this is a work computer and only specific versions are approved. Reproduction on newer versions necessary.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, I wasn't able to reproduce locally. Do you see this same behavior on other machines (either at work, or on a personal Windows machine you have access to?)
