### ISSUE TITLE
Allow the "light"/"dark" mode for GUI elements to be configured independently of the Editor theme

### ISSUE THREAD

**Issue by iron0012** [rstudio/rstudio#10754]
I strongly prefer a dark-themed editor, but all other UI elements to be light-themed (or "unthemed" and light by default). This was possible in Rstudio until recently, when the "Classic" theme was removed. Now, since "Classic" theme was removed, if the editor is dark-themed, all other GUI elements are also dark, and if the editor is light-themed, all other GUI elements are also light. 

Here is the appearance I desire, from a somewhat older version of Rstudio. This is "Classic" theme with "cobalt" editor theme:
<img width="1440" alt="CEF164B6-985D-4DF7-A550-5648AADB2167" src="https://user-images.githubusercontent.com/8052991/157313274-574c62d3-dd48-4a1c-98c3-2463bca0a6f8.png">

Here is the undesirable "all UI elements are dark" mode that I am now forced into when I use any Rstudio theme ("modern" is shown, but "sky" is identical) with the "cobalt" theme:
![image](https://user-images.githubusercontent.com/8052991/157313504-2b592a5f-010b-4ada-8264-116a55cb480f.png)

I have been able to come close to replicating the appearance I desire by:
1) start with a dark .tmTheme file (I'm using a variant of Cobalt)
2) convert the theme with rstudioapi::convertTheme() and save to a specified directory

```
rstudioapi::convertTheme(
  themePath = '/Downloads/cobalt2.tmTheme',
  add = FALSE,
  outputLocation = '/Downloads/',
  apply = FALSE
)
```

3) Open the resulting .rstheme file in a text editor, and on line 2 manually change rs-theme-is-dark from TRUE to FALSE

4) use rstudioapi::addTheme() to add the modified theme back into rstudio

```
rstudioapi::addTheme(
  themePath = '/Downloads/cobalt2.rstheme'
)
```

The resulting appearance is very close, but notice that the "Environment" and "Files" panels still have a dark background (as does the "Packages" panel). 
As a result, the blue "hyperlinks" to the files that appear in the Files pane (as well as the Packages that appear in the Packages pane) are nearly invisible against the dark background. Ideally, I would either want the background for the Files and Packages (and maybe Environment) panels to be light-colored while the Editor and Console panels remain dark colored. Alternatively, I would like to be able to change the "hyperlink-like" entries for files in the Files panel (and packages in the Packages panel) from blue to some other, lighter color so that they stand out legibly against the dark background. I have not been able to figure out how to do this yet.  

![5A5D6804-3D8F-4439-8D64-5B0BA7DAAA84](https://user-images.githubusercontent.com/8052991/157313561-0201a35f-6b0c-4e15-90cd-c82d0a66b14c.png)

To reiterate: please implement independent control of the Darkness/Lightness of UI elements ("chrome") and the code editor, so that the UI elements are no longer forced to be dark when the code editor is set to dark. Since that was the previous behavior, this is really more of a regression report than a feature request.

**Comment by ronblum** [comment]
@iron0012 Thank you for the suggestion! The intended behavior is that of the panes pick up the same theme, not for only some of the panes—Editor, Console, and Terminal—to have different themes from the rest. An egregious example is the Connections Pane, which has a mixture of both (see below). I'm marking this as an enhancement request, which we'll review as we continue development of RStudio. 

<img width="515" alt="mixed_theme" src="https://user-images.githubusercontent.com/31009952/157684611-d703fb3e-2fad-4f7e-a57e-367c70cfd614.png">

**Comment by jmcphers** [comment]
Another vote from the community forum: https://community.rstudio.com/t/turning-off-automatic-dark-mode-with-a-dark-editor-palette/135655

**Comment by sporella** [comment]
I also prefer a light GUI and dark theme only in script and console. That can't be possible anymore without the "classic" Rstudio Theme option :(

I tried the same that @iron0012 , but it seems that all panels share the same css class.

![rstudio](https://user-images.githubusercontent.com/34949487/166064355-675dc84f-7a78-4b22-88a4-4c4645263945.png)

**Comment by pieterprovoost** [comment]
@ronblum Would it be feasible to add some specific classes to Environment, Files, Packages, etc so they can be targeted individually in an rstheme?

**Comment by pieterprovoost** [comment]
In case anyone is looking for a temporary fix, I get reasonable results with:

```css
/* rs-theme-is-dark: FALSE */

.ace_editor, .rstudio-themes-flat.ace_editor_theme .profvis-flamegraph {
  background-color: #323232;
  color: #FFFFFF
}
.rstudio-themes-flat .ace_editor_theme, .rstudio-themes-flat.ace_editor_theme {
  background-color: #ffffff;
  color: black;
}
```

**Comment by geryan** [comment]
This issue has "inactivity" because the Rstudio team have not fixed it, not because the issue is not an issue. I also strongly prefer a dark editor / console with a light themed window, per @iron0012's original request. This is not even an enhancement, it is something that was possible and now is not.
