### ISSUE TITLE
Can't save a notebook after the default install on Windows 11

### ISSUE THREAD

**Issue by devereaux** [rstudio/rstudio#10751]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.2 Build 443
    OS Version      :  Windows 11 Pro with all updates
    R Version       : 4.1.2

### Steps to reproduce the problem

1. Create a new notebook: File -> New File -> R Notebook

2. Change nothing of the default example with the plot(car)

3. Save the notebook : it should fail

4. Select "preview on save" if the checkbox wasn't checked (it should be checked by default after install)

5. Save the notebook : it fails 100% of the time

Toggling the "preview on save" error before or after attempting to save can't fix the issue.

### Describe the problem in detail

The console reports:

    > source("~/test.Rmd")
    Error in source("~/test.Rmd") : ~/test3.Rmd:6:6: unexpected symbol
    5: 
    6: This is

If we look at the source file, this is just the default text on the 6th line:

    1: ---
    2: title: "R Notebook"
    3: output: html_notebook
    4: ---
    5: 
    6: This is an [R Markdown](http://rmarkdown.rstudio.com) Notebook. When you execute code within the notebook, the result
s appear beneath the code.

Removing the boilerplate doesn't fix the problem: the error then becomes:

    > source("~/test.Rmd")
    Error in source("~/test.Rmd") : attempt to use zero-length variable name

### Describe the behavior you expected

Rstudio should be able to save files using the default configuration (!!) that creates the plot(car) example!!!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by devereaux** [comment]
Full terminal output when trying to save the default notebook under the default directory with generic filename that doesn't use any space or unusual character, then running all the cells, then trying to save again after removing the "This is an [R Markdown](http://rmarkdown.rstudio.com) Notebook...." text
```

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source("~/test.Rmd")
Error in source("~/test.Rmd") : ~/test.Rmd:6:6: unexpected symbol
5: 
6: This is
        ^
> plot(cars)
> source("~/test.Rmd")
Error in source("~/test.Rmd") : ~/test.Rmd:6:6: unexpected symbol
5: 
6: This is
        ^
> source("~/test.Rmd")
Error in source("~/test.Rmd") : attempt to use zero-length variable name
> 
```

**Comment by kevinushey** [comment]
This sounds like a duplicate of https://github.com/rstudio/rstudio/issues/10742. That checkbox shouldn't be visible for notebooks.
