### ISSUE TITLE
Many RStudio processes continue running in background long after projects/sessions have been closed or restarted

### ISSUE THREAD

**Issue by eipi10** [rstudio/rstudio#10760]
I work on a virtual Windows server that I remote into. While using the process monitor over the last few weeks, I've noticed that there are many RStudio processes (sometimes dozens) that continue running in the background even though I have only a few RStudio session open at any given time. For example, I just counted 58 RStudio background process even though I have 3 RStudio sessions open. I'm assuming these are processes that continued running after I closed a project, restarted R within a session, or knitted an RMarkdown document. 

I'm hoping there's a way to ensure that RStudio processes close when the project/session is closed. I'm not sure how to provide a reproducible example, but please let me know what information I can provide or tests I can run that might be helpful. In case it might be relevant, there are also 68 instances of `crashpad_handler.exe` running in the background. My RStudio session has crashed maybe 2 or 3 times in the last few days, but not 68 times. Here is my system setup:

```
RStudio 2022.02.0+423

R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Operating system: Windows Server 2016 Standard, Version 1607, Build 14393.4886
```

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by benyake** [comment]
Any update on this issue? I am experiencing the same issue described above but with the following system setup:
`RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)`

**Comment by kevinushey** [comment]
To clarify, what processes are these? Are they RStudio processes, `rsession.exe` processes, or something else?

A screenshot of the Task Manager (or other process viewer) might help elucidate a bit here.

**Comment by benyake** [comment]
They are `rstudio.exe` processes. In the screenshots below, there are four running in the background with no active RStudio windows open. The RStudio IDE was opened and closed four times, resulting in four background processes.
![image](https://user-images.githubusercontent.com/69048578/190706704-5358a348-228f-4d9a-8e7f-8baa18421793.png)
![image](https://user-images.githubusercontent.com/69048578/190706977-4d21e335-3808-45d4-add4-381ba6d8101e.png)
