### ISSUE TITLE
Feature request: Missing prompt for uninstalled packages in quarto files

### ISSUE THREAD

**Issue by RaymondBalise** [rstudio/rstudio#10767]
`rmarkdown` files with the .Rmd suffix prompt users if a package is not installed:

![image](https://user-images.githubusercontent.com/18148282/157871861-e7367a3a-a48f-43ab-9efe-ea5496d42b87.png)

but `quarto` files with the .Qmd suffix do not.  

For example,  in the RStudio [documentation for Quarto](https://quarto.org/docs/get-started/authoring/rstudio.html) the [demo code](https://quarto.org/docs/get-started/authoring/_authoring.qmd) references `library(openintro)` which I did not have installed. I get an error when I render. 

This will be a nearly universal problem for novices.  Please implement the same prompt as R Markdown files.

**Comment by romainfrancois** [comment]
Verified with build RStudio 2022.06.0-daily+244 "Spotted Wakerobin" 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/2625526/160610508-36e0b27b-9d91-425b-b48c-815ff99349a3.png">
