### ISSUE TITLE
implement print support

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10763]
FIle -> Print should print the document that is currently open + focused in RStudio.

Previously, we used Qt APIs for printing that were quite a kludge:

https://github.com/rstudio/rstudio/blob/ac52c42e2f4a84510e5a6fe8dc0902a0c385ad28/src/cpp/desktop/DesktopGwtCallback.cpp#L125-L202

Hopefully there are Electron APIs for printing that we can take advantage of here.

**Comment by kevinushey** [comment]
Actually, now that we have access to `window.print()`, we could consider reusing the same implementation we have for RStudio Server.

https://github.com/rstudio/rstudio/blob/569f0b60e030bc155b83ea798d556dbc9fc82af8/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#L1466

**Comment by gtritchie** [comment]
The printing itself is working (tried Windows and Mac), but the enabling/disabling of the File / Print menu item and command isn't quite as expected. I will open a separate issue on that.
