### ISSUE TITLE
YAML field is being translated when creating a new Quarto document

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#10768]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.6.0.203
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

- Open RStudio IDE in systeme with non english language (using french here)
- Create a new Quarto document

### Describe the problem in detail

YAML field gets translated 
![image](https://user-images.githubusercontent.com/6791940/157888266-fc66de75-55f9-48f0-add7-d3cabea3d8c1.png)

### Describe the behavior you expected

I think it should stay `editor` so that the field works as documented. I don't think YAML field should be translated in general.

**Comment by romainfrancois** [comment]
Verified on Server, current `main` by setting chrome's language to French: 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/2625526/159251949-bf5356b2-1b5b-4f38-9032-b81413dba7b1.png">

How do I force the desktop version to French ?
