### ISSUE TITLE
Electron: GtkDialog "this is discouraged" message appears when started in terminal

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10784]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily_209 (Electron)
    OS Version      : Ubuntu 18.04.5, RHEL 7.9/8.3
    R Version       : 4.0.2/4.0.3

### Steps to reproduce the problem

1. Start RStudio Desktop from a terminal.
2. Open a dialog, e.g. with `Open Project`
    - The dialog opens
    - The following error appears in the terminal:
```
Gtk-Message: 09:24:53.565: GtkDialog mapped without a transient parent. This is discouraged.
```

### Describe the problem in detail

"Discouraged" message appears in the terminal.

### Describe the behavior you expected

No message.

Note: This is not an issue with Ubuntu 20.04.4.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Followup: This isn't Electron-specific. It occurs in earlier versions of RStudio Desktop, too, e.g. 2022.02.0+423. Perhaps this could fall in the "fixed by Electron" category, in some way?

**Comment by mikebessuille** [comment]
@gtritchie is this something we can easily fix in Electron?

**Comment by gtritchie** [comment]
Not likely, given it was also seen in Qt, seems like something at the Chromium level but I haven't looked into it yet.

**Comment by kevinushey** [comment]
I think we can just ignore this. It's not going to affect anyone who launches RStudio in the "regular" way; that is, using UI in the desktop environment (as there will be no terminal for these sorts of messages to be visible).

It also doesn't seem to be associated with any actual product defect.

**Comment by mikebessuille** [comment]
Closing per Kevin
