### ISSUE TITLE
Electron: RStudio Desktop doesn't start from an Ubuntu 22.04 terminal

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10786]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+209 (Electron)
    OS Version      : Ubuntu 22.04 (dev)
    R Version       : 4.1.2

### Steps to reproduce the problem

1. Start up RStudio Desktop from a terminal.
    - RStudio Desktop doesn't start.
    - The following appear in the terminal:
```
vmware@ubuntu:~$ rstudio
[7428:0315/121918.496330:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is desktop, ANGLE is 
error: Failed to load http://127.0.0.1:28569: Error: ERR_FAILED (-2) loading 'http://127.0.0.1:28569'
```
2. Hit <kbd>Ctrl-C</kbd> to stop the process. You might need to do so a couple of times.
3. Start RStudio Desktop using the icon.
    - RStudio Desktop starts up properly.

### Describe the problem in detail

RStudio Desktop doesn't start from a terminal.

### Describe the behavior you expected

RStudio Desktop should start from the command line.

Note: Ubuntu 22.04 is still in development, but it will be live in April 2022, before Electron beta is released.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I was able to install and run RStudio Electron on Ubuntu 22.04 a few weeks ago so I'll give it another try and see what has changed.

**Comment by gtritchie** [comment]
Ah, it's possible I only tried from the icon and not the terminal.

**Comment by mikebessuille** [comment]
@gtritchie should this be in Epic "Fixed by Electron?"

**Comment by gtritchie** [comment]
No. This issue was opened against Electron IDE, not Qt.

**Comment by gtritchie** [comment]
@ronblum I've been installing and opening numerious Electron builds on Ubuntu 22 (from the terminal) without hitting this problem.

Can you still repro?

**Comment by ronblum** [comment]
Electron runs—all set!

I'm seeing a couple of errors, but I have to go back and see if these match ones I filed previously. But this all set!
