### ISSUE TITLE
Environment variables set by .zprofile, in particular adding brew packages to the path

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#10799]
Binaries installed by homebrew on M1 macs are in "/opt/homebrew/bin" or "/opt/homebrew/sbin" which in the latest versions are added to the path by including `/opt/homebrew/bin/brew shellenv` to .zprofile, which does this:
```
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```

Rstudio does not seem to source .zprofile (nor .zshrc) when launching which makes in this case all of the brew packages unavailable through the `system` command.

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0 Build 443
    OS Version      : Mac OS Monterey 12.2.1 (M1)
    R Version       : 4.1.2

### Steps to reproduce the problem
system("brew")

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gregleleu Thank you for raising this!

@astayleraz Would you mind checking this, since you have the M1 machine?

@kevinushey Is this another thing we need to consider with the way Homebrew now installs on M1 machines?

**Comment by mikebessuille** [comment]
I don't think we should be trying to support every possible shell, but we could describe a workaround?

**Comment by gregleleu** [comment]
@mikebessuille It's the default shell (zsh) on Mac OS Monterey, and I don't think I have done anything exotic. I'm actually surprised the issue hasn't been reported before.

**Comment by jmcphers** [comment]
I don't think RStudio has ever run any shell startup scripts. If you want to influence R's set of environment variables, setting them in `.Renviron` is the idiomatic way to do it.

**Comment by kevinushey** [comment]
On macOS, if you want RStudio to "see" Homebrew, you can edit `/etc/paths` and add an entry `/opt/homebrew/bin`.

**Comment by gregleleu** [comment]
Understood. Apparently, the M1 architecture "broke" things that worked but weren't necessarily meant to...

For what it's worth I ended up adding the line below to my .Renviron and it works. (I'm never too sure about touching etc/paths). Thanks everyone.
`PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}"`
