### ISSUE TITLE
Cannot save cpp file with "The requested operation cannot be performed on a file with a user-mapped section open"

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#10797]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.01.0-daily+214 "Prairie Trillium" Daily (e5d5b4f4030b3d22bf6c24864aadcf123632300c, 2021-11-17) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Windows 10
    R Version       : 4.1.2

### Steps to reproduce the problem

1. Edit a .cpp file (I'm not sure what is important about the file)
2. Try to save it
3. Get this error: ![image](https://user-images.githubusercontent.com/10359931/158705521-a34f9cca-c83a-4bf5-8c21-0e061348d180.png)

### Describe the problem in detail

I cannot save the file.

### Describe the behavior you expected

I wanted to save the file.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@billdenney Thank you for raising this! Version 2022.01.0-daily+214 is an early interim build of Ghost Orchid that was meant for testing purposes only. What happens with either of these stable releases:
- Ghost Orchid release [2021.09.2+382](https://dailies.rstudio.com/version/2021.09.2+382.pro1)
- Prairie Trillium release [2022.02.0+443](https://dailies.rstudio.com/version/2022.02.0+443.pro2/)

**Comment by kevinushey** [comment]
See also:

https://github.com/rstudio/rstudio/issues/6940

The issue is caused when C++ diagnostics fire at the same time one tries to save a C++ file.

**Comment by billdenney** [comment]
Yeah, it's a duplicate of #6940.  I don't know how I missed it in my search.

**Comment by kevinushey** [comment]
I almost missed it too; I don't know what it is, but the GitHub issue search is often not that helpful.
