### ISSUE TITLE
Add PowerPC darwin support?

### ISSUE THREAD

**Issue by barracuda156** [rstudio/rstudio#10790]
From the list of dependencies two are blockers for MacOS PowerPC: `openjdk11` and `qt5`.
On PowerPC the latest Java to exist is a developer build of `openjdk7` and Qt is at `qt4`. Other than that everything is there, `gcc10` and `gcc11` with `gfortran` build, the latest `cmake` and `R` build.

The question is whether it may be feasible to build RStudio with earlier Java and Qt4 or otherwise bypass this limitation?

Thanks in advance for any help.

**Comment by jmcphers** [comment]
You can't build current versions of RStudio for this architecture due to new dependencies. Much older versions of RStudio did use Qt4 and QtWebKit which IIRC can build on PowerPC with some nudging; if you really need to get this to work I'd suggest using a release tag for a very old version (start with 0.97).

**Comment by barracuda156** [comment]
> You can't build current versions of RStudio for this architecture due to new dependencies. Much older versions of RStudio did use Qt4 and QtWebKit which IIRC can build on PowerPC with some nudging; if you really need to get this to work I'd suggest using a release tag for a very old version (start with 0.97).

@jmcphers Thank you, I will try those.

**Comment by barracuda156** [comment]
> From the list of dependencies two are blockers for MacOS PowerPC: `openjdk11` and `qt5`.
> 
> On PowerPC the latest Java to exist is a developer build of `openjdk7` and Qt is at `qt4`. Other than that everything is there, `gcc10` and `gcc11` with `gfortran` build, the latest `cmake` and `R` build.

UPD. Chances are `openjdk8` is fixed for ppc32 soon.

**Comment by barracuda156** [comment]
@jmcphers Do you know how critical is Qt5? Java might get fixed, with Qt hopes are slim, no one has time to deal with it.

I have seen an example of Qt5 software switched successfully to Qt4 (for better compatibility). Though admittedly, it was a simpler piece of software.

**Comment by barracuda156** [comment]
@kevinushey I see, that is hopeless. NodeJS may be fixed, but no one gonna bother fixing Chrome.

**Comment by gtritchie** [comment]
We switched the Qt version of RStudio to use QtWebEngine years ago, and that's only in Qt5+.

QtWebEngine uses Chromium, so even if we hadn't switched to Electron this would be a dead end. You'd have to go back quite a few major versions of RStudio to get to one that still used QtWebKit.
