### ISSUE TITLE
FR: filter console history based on initial typed text

### ISSUE THREAD

**Issue by JimHokanson** [rstudio/rstudio#10811]
Currently, pressing the up arrow in the console switches between all previously entered commands. I would like to be able to type a few letters and then have the up arrow only bring up commands that match my initial typing, rather than ignoring what I have typed and iterating through all previous commands.

For example:
```
> a <- 1
> b <- 2
> c <- 3
> a       
```
Pressing up at that last line (right after the letter a) would ideally bring up `a <- 1` rather than `c <- 3`

This is helpful for quickly toggling between previously used commands  as I am debugging something. I use this a lot with Matlab and Python (Spyder) and would love to have it in Rstudio. Thanks.

**Comment by romainfrancois** [comment]
You can use `Cmd` + `Up`

**Comment by JimHokanson** [comment]
Oh no, I really tried hard to find this before posting. Thanks.

On Windows, `Ctrl` + `Up`

![image](https://user-images.githubusercontent.com/1593287/159280021-bc7941cf-8a80-42b1-a9e0-81443d0d129a.png)
