### ISSUE TITLE
support new form of R_ResetConsole hook for Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10819]
See: https://github.com/wch/r-source/commit/42f496e2592d1ee772fd8599c69752150ff90e0b

With comments from Tomas:

> So, to use the new callback, you would do:
> R_DefParamsEx(Rp, RSTART_VERSION);
> Rp->ResetConsole = myResetConsole;
> 
> and all new code should eventually switch to calling
> R_DefParamsEx(Rp, RSTART_VERSION);
> 
> instead of R_DefParams(Rp)

**Comment by gtritchie** [comment]
Test notes:

- Installed R-Devel (2022-03-27 r81997 ucrt) "unsuffered Consequences" on Windows-10.
- Installed current release of RStudio Desktop (2022.02.1+461)
- Entered following code, selected it all, and ran it

```R
x <- 1
stop("Oh no")
x <- 2
```

With latest RStudio release, all three lines of code executed and final value of `x` was 2.

Then installed latest daily build (2022.06.0-daily+239) and repeated the exercise. This time only the first two lines of code3 executed and the value was 1, as expected with this change.
