### ISSUE TITLE
Git history shows dates in standard US format

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10810]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2021.09.0 and above
    OS Version      : MacOS 12.3, Ubuntu 20.04, and likely all others
    R Version       : N/A

### Steps to reproduce the problem

Using the Git pane, perform a diff on a file and look at its history.

### Describe the problem in detail

[Borrorwed and modified from #2544 posted by @m-macaskill]

The date column and the date label for the selected commit have reverted from the ISO standard of `YYYY-MM-DD` shown in the screenshot above to the ambiguous US convention of `MM-DD-YY`.

This issue is reproducible with
- RStudio Desktop 2021.09.2+382, 2022.02.0+443, and 2022.06.0+198 on MacOS 12.3
- RStudio Server 2021.09.2.382 on Ubuntu 20.04.3 via Chrome on MacOS 12.3

This is true even when setting the date to a non-US date format (tested with RStudio Desktop on MacOS), such as "Congo - Kinshasa" which uses DD/MM/YYYY and "Japan" which uses YYYY/MM/DD.

<img width="335" alt="Screen Shot 2022-03-21 at 12 32 37" src="https://user-images.githubusercontent.com/931027/159190847-adc168de-8004-4b3a-b2ba-448eeda074a2.png">
 
### Describe the behavior you expected

We've switched everyone to a United States-centric date format, which most of the world doesn't use. We need to revert to the unambiguous ISO standard, or apply the user's locale setting from the OS, or provide an RStudio preference for users to control the date format used.

Triage note: This is a regression from every release through Juliet Rose.

Note: See also #2544 for an enhancement request regarding the date format.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Very interested to know why/when this broke

**Comment by gtritchie** [comment]
This started happening when this PR was merged: https://github.com/rstudio/rstudio/pull/9485 (sigh).

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.06.0-daily-282 on MacOS 12.3 by going to
- Git Pane -> Diff -> History
