### ISSUE TITLE
Cmd+W on GPU Diagnostics window closes editor buffer

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10826]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+228
    OS Version      : macOS 12.3
    R Version       : 4.1.3

### Steps to reproduce the problem

- start RStudio Electron on Mac
- have at least one editor tab open
- Help / Diagnostics / Show GPU Diagnostics
- with the GPU window active, type <kbd>Cmd+W</kbd> to close it

### Describe the problem in detail

- instead of GPU diagnostics closing, the current editor tab closes

### Describe the behavior you expected

- <kbd>Cmd+W</kbd> should close the GPU Diagnostics window, as it does in Qt desktop

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.06.0-daily+296 (Electron) in
- Red Hat 8.3
- MacOS 12.3

using the steps above.
