### ISSUE TITLE
Overlap of R Sessions across different users on same Windows server

### ISSUE THREAD

**Issue by stefgehrig** [rstudio/rstudio#10820]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0, "Ghost Orchid"
    OS Version      : Windows Server 2016 (64-Bit)
    R Version       : 4.1.2

### Steps to reproduce the problem

1) Simultaneously open RStudio in two different user accounts on the same remote desktop Windows server
2) Observe that you share the session environment and console output (e.g., it is possible to access objects and funtion defined in the environment of the other user)

### Describe the problem in detail

Two users launch RStudio more or less at the same time (that is, within the seconds of each other) while working on the same Windows server, but using completely separate, password-protected Windows user accounts. Nevertheless, they end up sharing their session, such that, for example, one user can read the console output of the other user in her console. This issue is not known for any other software running on our setup and it could create serious data security issues.

For a group of roughly 10 users/day, this issue did not occur with prior versions of RStudio over at least 3 years, but it occurred around 5-10 times within 3 months after updating to above version.

### Describe the behavior you expected

Separate Windows users running their own copy of RStudio should not have access to the R session of each other, even when working on the same server. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jarauh** [comment]
The problem is absent with version 1.4.1717 ("Juliet Rose"). (This was the version that we used before trying to update. We did not yet try versions in between.)
