### ISSUE TITLE
Support changes to R 4.2.0 help system

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10839]
From https://github.com/wch/r-source/commit/1c74636d6047f49935f7dd259fbe15c80f254922:

>       \item The HTML help system has several new features: LaTeX-like
>       math can be typeset using either \href{https://katex.org/}{KaTeX}
>       or \href{https://www.mathjax.org/}{MathJax}, usage and example
>       code are highlighted using \href{https://prismjs.com}{Prism}, and
>       for dynamic help the output of examples and demos can be shown
>       within the browser if the \CRANpkg{knitr} package is
>       installed. These features can be disabled by setting the
>       environment variable \code{_R_HELP_ENABLE_ENHANCED_HTML_} to a
>       false value.

The enhanced help system looks good with light RStudio themes:

<img width="750" alt="Screen Shot 2022-03-24 at 10 59 34 AM" src="https://user-images.githubusercontent.com/1976582/159980587-b100420c-4440-45bb-bd1c-a28769de9115.png">

But not so great with dark RStudio themes:

<img width="745" alt="Screen Shot 2022-03-24 at 11 00 00 AM" src="https://user-images.githubusercontent.com/1976582/159980657-527dea47-c6ae-40f3-981e-986beb7ee304.png">

We'll likely need to tweak our Help pane CSS to support the new Help rendering.

**Comment by ronblum** [comment]
Verified using `?Normal` that text is displayed correctly using several light and dark themes in
- RStudio Desktop 2022.02.2+481 (Prairie Trillium)
- RStudio Server 2022.02.2+481 (Prairie Trillium)
- RStudio Desktop 2022.06.0-daily+295 (Spotted Wakerobin)

Also verified that no impact in R 4.1.3.
