### ISSUE TITLE
Adapt name of new RMarkdown file in non-English IDE ?

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#10837]
Currently testing the daily version which have internationalization in French for me. 

When creating a new R Markdown document, the file name is also translated. Usually in its `Untitled.Rmd` or folder name is `Untitled` when template has several files. With translation we get `Sans titre.Rmd` or `Sans titre` has a folder name. 

![image](https://user-images.githubusercontent.com/6791940/159936918-d692df1a-1c20-45ea-8f03-9de708071abf.png)

![image](https://user-images.githubusercontent.com/6791940/159937096-721b061a-f89b-4ad9-aeee-8eeb74187840.png)

I would vote in favor of not translating that and keep `Untitled` or at least not creating a space in file name or folder name. The latter is known to create some issues in some OS or file system. 

I don't have any issue yet with that, just suprised by this in the first place, but I am opening this issue to report and maybe discuss if other thinks the same. 

@romainfrancois do you have an opinion as a 🇫🇷 user ?

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.6.0.228
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.1.2 (2021-11-01)

**Comment by gtritchie** [comment]
Data point, I checked with Notepad on Windows-11, and with Windows in French, it also uses "Sans titre" for a new document. However, when you hit "Save", it does not use that as the default filename, you have to supply one.

**Comment by gtritchie** [comment]
Another, perhaps better, comparison: Visual Studio Code, in French, does continue using "Untitled" for a new document. So I'll follow that lead and switch RStudio to match.

**Comment by romainfrancois** [comment]
Sorry for arriving after the fact, but I'm with @cderv. Thanks @gtritchie for the fix.
