### ISSUE TITLE
argument help popup does not display with R 4.2.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10844]
The following error is printed in the console.

> 2022-03-25T18:33:11.596020Z [rserver] ERROR CLIENT EXCEPTION (rsession-kevin): Unexpected help format, no argblock table found;|||rstudio-0.js@8#559::Throwable_4_g$|||rstudio-0.js@18#3070::Error_3_g$|||rstudio-0.js@14#3133::new AssertionError_7_g$|||rstudio-0.js@10#2174::makeAssertionError_Object_0_g$|||rstudio-0.js@23#470267::parseArguments_0_g$|||rstudio-0.js@9#470239::parse_0_g$|||rstudio-0.js@17#429948::onResponseReceived_345_g$|||rstudio-0.js@8#429934::onResponseReceived_344_g$|||rstudio-0.js@36#328440::onResponseReceived_222_g$|||rstudio-0.js@36#328498::onResponseReceived_223_g$|||rstudio-0.js@38#135415::onResponseReceived_6_g$|||rstudio-0.js@17#43353::fireOnResponseReceived_0_g$|||rstudio-0.js@28#43702::onReadyStateChange_0_g$|||rstudio-0.js@18#94072::<anonymous>|||rstudio-0.js@28#24557::apply_0_g$|||rstudio-0.js@16#24616::entry0_0_g$|||rstudio-0.js@14#24595::<anonymous>|||Client-ID: a61434ec-5d99-4360-925d-307080067334|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36

**Comment by jgutman** [comment]
We had some difficulty reproducing the originally reported bug, but tested the current behavior on:

RStudio Desktop 2022.02.2-485, Mac OS 12.3.1
RStudio Desktop 2022.06.0-322, Mac OS 12.3.1
RStudio Desktop 2022.06.0-322, Windows 11

and all verified to be working as expected.
