### ISSUE TITLE
help popup is partially obscured by completion list

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10841]
Hi, 

I noticed two issues on the latest macOS, one is reported in this issue, the other is that the left part of the pop-up help panel can't be displayed properly on Chrome and Edge (see the screenshot below). The only browser that RSW can work is Firefox, at the present. 

I'm wondering if PR #10832 will resolve the pop-up help panel issue for Chrome and Edge on macOS as well?

<img width="614" alt="image" src="https://user-images.githubusercontent.com/8368933/160040337-bd5ace92-7ff0-4267-8036-e8693b2cc112.png">

_Originally posted by @shrektan in https://github.com/rstudio/rstudio/issues/10821#issuecomment-1078584279_

**Comment by kevinushey** [comment]
I'm not able to reproduce with the latest daily builds + Chrome:

<img width="673" alt="Screen Shot 2022-03-28 at 12 20 42 PM" src="https://user-images.githubusercontent.com/1976582/160471047-32c48fef-5721-4c1d-bae4-b31fa9915420.png">

**Comment by kevinushey** [comment]
@shrektan: can you provide any other information that might help us reproduce this locally?

**Comment by shrektan** [comment]
Oddly, I can't reproduce this issue any longer and I haven't upgraded RSW to the latest, yet.
