### ISSUE TITLE
Can't browse to projects in RStudio Electron on Linux

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10859]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily-310
    OS Version      : Ubuntu 20.04.4, CentOS7, OpenSUSE15
    R Version       : 4.0.5

### Steps to reproduce the problem

- File / Open Project...
- Browse to a folder containing an RStudio project
- Try to open it

### Describe the problem in detail

- The .rproj file isn't shown, thus cannot be selected

### Describe the behavior you expected

- Able to browse and open projects
- Same scenario works on equivalent Qt-based desktop build, and works on Electron in Windows and Mac, so is Linux-specific (didn't try any other distros)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Is this worth reporting an Electron bug for?

If we use `{ name: "Project", extensions: ['rproj']}`, is that able to match against the uppercase `.Rproj`? Or is it still ignored there?

**Comment by matheustavaresdev** [comment]
@kevinushey the way you mentioned is exactly the way the code is running right now. I tried filtering by many mixed case forms of `rproj` and nothing worked. I'm taking a look on some electron code here before filing a bug there, as there's a chance that this could be a comparison or regex of some sort.

**Comment by kevinushey** [comment]
https://github.com/kevinushey/electron/blob/9c8323f70e3d0c2d3073d7383b4a31365377f686/shell/browser/ui/file_dialog_gtk.cc#L355-L371

It looks like this is an Electron issue.

**Comment by matheustavaresdev** [comment]
Yes. I got there, seems that it's only checking for full lowercase or uppercase extensions instead of mixed or full match. Did a change and am trying to rebuild electron for Linux but it's not as simple as I thought... Thinking of opening an issue, pointing the fix and waiting for it to be merged I guess... Seems like a plan?

**Comment by kevinushey** [comment]
I think it should be sufficient to just open a bug report (referencing that code) at https://github.com/electron/electron/issues, with an Electron Fiddle example to help demonstrate the issue if possible.

**Comment by matheustavaresdev** [comment]
Opened an issue on electron. Waiting for their fix, but should be released only on Electron v19, which will probably come up in the next 4 weeks or so. How should we proceed @gtritchie ?

**Comment by gtritchie** [comment]
Electron issue: https://github.com/electron/electron/issues/33844

**Comment by gtritchie** [comment]
Let's leave this issue on the backlog while we wait to see if this gets fixed in Electron 19.

**Comment by gtritchie** [comment]
This is marked as fixed in Electron 18.2.1 (https://releases.electronjs.org/release/v18.2.1). Once this is on npm we'll integrate into the project and hopefully that solves this.

**Comment by gtritchie** [comment]
This should now be fixed via https://github.com/rstudio/rstudio/commit/95b8cc84e60454188d7c57fce6dcde2cb5c71e5c.
