### ISSUE TITLE
Can I use RStudio logo as entry point for this open-source project?

### ISSUE THREAD

**Issue by danilopeixoto** [rstudio/rstudio#10856]
I would like to use the RStudio logo, only the blue ball, as an icon and entry point for the open-source server app?
It's possible?

How should I present the entry point icon to the user in scenarios that require a minimalistic and square version?

The [RStudio Logo Usage Guidelines](https://www.rstudio.com/about/logos) does not cover it.

![image](https://user-images.githubusercontent.com/10113621/160521242-212d37d7-bd93-4ec4-a8cb-d8dceccf0a92.png)

**Comment by ronblum** [comment]
@danilopeixoto Good question!

@mikebessuille Do you by chance know the answer, or whom to direct it to?

**Comment by mikebessuille** [comment]
Seems that the question is about legal usage rights?   And you are trying to use the logo on your own site to point your users to an open source RStudio server?   I'll look into who can answer that; I would think either legal or someone in marketing.

**Comment by mikebessuille** [comment]
I got an answer; have a look at our trademark policy:  https://www.rstudio.com/about/trademark/.
If that doesn't answer your questions, send an email with the details to [permissions@rstudio.com](mailto:permissions@rstudio.com) and someone will review that request.

**Comment by mikebessuille** [comment]
In the meantime, I think this resolves this issue so I'll close this github issue.  Please comment if you have further questions.
