### ISSUE TITLE
R 4.2.0: double-check Help changes after release of R 4.2.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10850]
Development of the enhanced R help system is on-going; once R 4.2.0 is released, we should evaluate whether any further changes are required for PT to support it.

**Comment by gtritchie** [comment]
I asked what needed to be tested here, here's what @kevinushey said a couple weeks ago:

> I think there were two main things:
> Make sure it actually works (the Help pane displays the same stuff it did before),
> Make sure dark themes are properly supported in SW (https://github.com/rstudio/rstudio/issues/10839)
> I guess that issue is kind of duplicating https://github.com/rstudio/rstudio/issues/10839?
>
> Also, https://github.com/rstudio/rstudio/issues/10855 is in EG but https://github.com/rstudio/rstudio/issues/11022 is in CB; I’d argue the latter has higher priority.

**Comment by ronblum** [comment]
@jgutman Thanks! I forgot to assign this to myself.

The Help Pane theme mismatch is long-standing, so I'm closing this as verified!

**Comment by ronblum** [comment]
Followup: The existing Help Pane behavior is expected, so everything is hunky dory.
