### ISSUE TITLE
base::units() cannot find Method after Restart R, but can after restart R Studio 

### ISSUE THREAD

**Issue by tmcd82070** [rstudio/rstudio#10854]
I use the `units` library for measurement unit conversion (great package BTW). I am confused about different behavior after Shift-Ctrl-F10 (Restart R) and restarting all of Rstudio.  

Try this code:
```
> x <- units::as_units(1, "m)
> units(x)
$numerator
[1] "m"

$denominator
character(0)

attr(,"class")
[1] "symbolic_units"
```

That's all fine.  Now, restart R (Shift-Ctrl-F10 in Rstudio), and it looks like `base::units()` cannot find the applicable method for `units`:

```
Restarting R session...
> units(x)
Error in UseMethod("units") : 
  no applicable method for 'units' applied to an object of class "units"
```

But, if I close RStudio, save `x` into my default .RData, and restart RStudio, I get:

```
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/Programs/Rdistance/.RData]

> units(x)
$numerator
[1] "m"

$denominator
character(0)

attr(,"class")
[1] "symbolic_units"
> 
```

If, after Restart R, I access any routine in the `units` library (e.g., `units::drop_units(x)`), base units can find the method again.

My question is whether this is correct behavior and whether I should program around it.  This feature causes my package to fail (on first occurrence of units(x)) after Restart R but not after restarting all of Rstudio.  Do I worry about this? Do I need to somehow register a Method for `units` objects when my package is attached (seems like I should not have to).  I am trying to avoid attaching the `units` library in the form of a `Depends` .

This seems like an Rstudio thing, but point elsewhere if this is someone else's issue. 

## Machine details:
I am using: 
`RStudio 2021.09.2+382 "Ghost Orchid" Release (99999999999999999999999999999999, 2022-01-04) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36. `

I am using a project file.  I have a "test" library tree for debugging my package so that I do not install whacky versions into my normal library tree. i.e., 
```
> .libPaths()
[1] "C:/Users/XXX/Documents/Programs/Rdistance/RTestLibrary"
[2] "C:/Users/XXX/Documents/R/win-library/4.1"              
[3] "C:/Program Files/R/R-4.1.2/library"     
```

**Comment by kevinushey** [comment]
I suspect this is because the `units` R package is not loaded after a restart. For example, on the first run:

```
> "units" %in% loadedNamespaces()
[1] TRUE
> units(x)
$numerator
[1] "m"

$denominator
character(0)

attr(,"class")
[1] "symbolic_units"
```

However, after restarting R:

```
> "units" %in% loadedNamespaces()
[1] FALSE
> units(x)
Error in UseMethod("units") : 
  no applicable method for 'units' applied to an object of class "units"
```

It should suffice to reload the package after restarting R, and I think that's the expected behavior (unless I'm misunderstanding a nuance of your workflow).

**Comment by tmcd82070** [comment]
After more thought, I understand the situation better.  I agree that a package cannot rely on a separate package's namespace being loaded IF they do not declare it in IMPORTS: of DESCRIPTION and import(pkg) in NAMESPACE.   That is, I now agree my original "issue" is not an issue and is expected behavior.  My initial problem was not having `units` in BOTH the IMPORTS: statement of DESCRIPTION and an `import(units)` in NAMESPACE (I listed units in DESCRIPTION but not NAMESPACE).

Thank you for the response.  I'm fine closing this issue.
