### ISSUE TITLE
Electron: "Theme parsing error" messages when starting from terminal in Plasma on Ubuntu

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10860]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily-244 (Electron)
    OS Version      : Ubuntu 20.04.4
    R Version       : 4.1.3

### Steps to reproduce the problem

1. In Ubuntu, switch to Plasma.
3. Run RStudio Desktop Electron `rstudio` from the terminal.

### Describe the problem in detail

The following appears in the terminal:
```
(rstudio:54637): Gtk-WARNING **: 08:58:28.208: Theme parsing error: colors.css:71:44: Invalid number for color value

(rstudio:54637): Gtk-WARNING **: 08:58:28.208: Theme parsing error: colors.css:72:44: Invalid number for color value

(rstudio:54637): Gtk-WARNING **: 08:58:28.208: Theme parsing error: colors.css:74:53: Invalid number for color value

(rstudio:54637): Gtk-WARNING **: 08:58:28.208: Theme parsing error: colors.css:75:53: Invalid number for color value

(rstudio:54637): Gtk-WARNING **: 08:58:28.208: Theme parsing error: colors.css:76:56: Invalid number for color value

(rstudio:54637): Gtk-WARNING **: 08:58:28.208: Theme parsing error: colors.css:77:65: Invalid number for color value
```

### Describe the behavior you expected

No errors.

Note: This only appears to be an issue in Plasma, with the Electron builds. GNOME and Ubuntu on Wayland are fine, as are the Qt builds.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Closing as won't fix for now.  If more serious symptoms arise, we should look at it again
