### ISSUE TITLE
"Print the Current File" command availability is inconsistent (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10862]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+244
    OS Version      : macOS 12.3
    R Version       : 4.1.3

### Steps to reproduce the problem

- start the IDE with no open editor tabs
- File / Print menu item disabled (expected)
- Command-palette: "Print the current file" is disabled (expected)
- File / New File / R Script to create a blank file

### Describe the problem in detail

- File / Print menu and "Print the current file" commands remain disabled

### Describe the behavior you expected

- Should be enabled, as they are in the same scenario on RStudio Server
- If you then close and reopen the IDE, coming back with the same untitled document open, the print command is now enabled; ditto if you save the file in the same session where it was created

See also: #10763

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
I've retested and this works now. This change has fixed it: https://github.com/rstudio/rstudio/pull/10935

It triggers a menu rebuild when the menu item changes.
