### ISSUE TITLE
Checkable menu items not checked in Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10866]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+244
    OS Version      : All
    R Version       : All

### Steps to reproduce the problem

- look at main main items that should have checkboxes such as View / Panes, or Debug / On Error

### Describe the problem in detail

- On Electron builds (all platforms) there aren't any checked menu items (screenshot from Electron):

![Screen Shot 2022-03-29 at 16 00 46](https://user-images.githubusercontent.com/10569626/160714394-6495d23e-d2cc-4619-aaef-749687e38535.png)

### Describe the behavior you expected

- Checked menu items (screenshot from Qt version):

![Screen Shot 2022-03-29 at 16 02 32](https://user-images.githubusercontent.com/10569626/160714590-eda8a030-0887-4a84-86e6-07348d40b634.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
`Electron.MenuItem` does have a checked property and I've confirmed that the menu template is updated with the latest state coming from GWT. The menu is rebuilt so it will have the correct state.

I think the fix is setting `MenuItem.type` to `checkbox`. https://github.com/rstudio/rstudio/blob/d39b759d59140787ce5972a04a58156f6b4d4788/src/node/desktop/src/main/menu-callback.ts#L336

**Comment by gtritchie** [comment]
Reactivating. The check marks are showing up, but the state isn't correct. For example:

- Look at "Debug / On Error" submenu
- Only one item should have a checkbox
- Click on a different one
- Open the menu again

On Mac, at least, I'm seeing both items with checkboxes. Can repeat, and get three items with checkboxes.

![Screen Shot 2022-03-31 at 11 12 14](https://user-images.githubusercontent.com/10569626/161112271-0a232907-bb3f-459f-aecb-977c0a882068.png)

Same with Console on Left/Right, able to get both selected:
![Screen Shot 2022-03-31 at 11 12 43](https://user-images.githubusercontent.com/10569626/161112373-f89d5259-ee46-4a93-b9f7-6d0f5207f4d4.png)

**Comment by gtritchie** [comment]
Verified behavior with 2022.06.0-daily+295 (Electron) on macOS. Menu items are checking/unchecking as expected, and settings are persisting and being restored on subsequent launches.
