### ISSUE TITLE
Word Wrap Document Outline for R-Markdown

### ISSUE THREAD

**Issue by N-Accumbens** [rstudio/rstudio#10877]
I regularly use the headers and document outline to quickly jump through my long R-Markdown document, but one issue I've noticed is that if the heading is too long that the document outline will cut-off. I'm wondering if it'd be possible to add word-wrapping to the headers in the document outline?

**Comment by ronblum** [comment]
@N-Accumbens Thank you for the suggestion! We'll review it as we continue development of RStudio.
