### ISSUE TITLE
Download update without quitting RStudio

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rstudio#10870]
Right now the "Update available" pop up offers to "quit and download"  

![image](https://user-images.githubusercontent.com/8617595/160911945-3fa83f1a-f2d3-443c-8e00-5f257f74e479.png)

This means that the only way to quickly go to the download page for the new version is closing a potentially on-going project. It would be nice to have a "Download" without needing to quit.

**Comment by ronblum** [comment]
@eliocamp Thank you for the suggestion! We'll review this request as we continue development of RStudio.

**Comment by colearendt** [comment]
I like this idea!
