### ISSUE TITLE
Find in Files search into RStudio project hidden folder `.Rproj.user`

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#10884]
Found this today while doing a search with default Parameter
![image](https://user-images.githubusercontent.com/6791940/161324214-e380d5b8-9add-4fa0-8817-c7c9662dc115.png)

Content from `.Rproj.user` are search into and result shown. I don't think that is desired. 

Also, let's note the path returned (Windows specific issue ?) which is not `rmarkdown/.Rproj.user` with `/.` missing.

If I exclude `.gitignore` content then it is ok but because the folder is already in my `.gitignore` file
![image](https://user-images.githubusercontent.com/6791940/161326492-ce335749-cb50-4052-abf5-a7cd89351143.png)
(french in screenshot - I can't really switch to english easily anymore)

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.6.0.257
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.1.2 (2021-11-01)

**Comment by romainfrancois** [comment]
It is actually a problem with any directory that starts with `.`

**Comment by romainfrancois** [comment]
It was apparently introduced in this commit: https://github.com/rstudio/rstudio/commit/c8e08fd00e033a251c8632006d7f5e6f73f4e9b4

PT is not concerned by this issue.

**Comment by romainfrancois** [comment]
Some QA notes in https://github.com/rstudio/rstudio/pull/10890
