### ISSUE TITLE
Cannot dismiss `Save File` window if the source file is read-only and cannot be saved

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#10887]
I am using RStudio 2022.02.0 built on M1 macbook with macOS 12.3.1. 

Due to the privilege restrictions, using `file.edit()` does not allow me to save edited profile under Home directory. 
Once this happens, a window pops up to ask to save a copy. The window cannot be dismissed by pressing cancel. If I press cancel button, it won't disappear until I save the file. 

Is this something related to RStudio?

**Comment by ronblum** [comment]
@Fred-Wu Thank you for raising this! I'm having trouble reproducing the problem, though.
1) By "save edited profile," do you mean "save edited file," or are you editing the Rprofile file?
2) How are the restrictions set—is it the individual file, or the directory, or some other mechanism?
3) Does the following show up at the top of the file in the Editor Pane?
<img width="330" alt="readonly" src="https://user-images.githubusercontent.com/31009952/162065099-4e2be8c7-1241-4a0e-871d-89ca2933638c.png">
