### ISSUE TITLE
RStudio adds .Rproj.user to .gitignore

### ISSUE THREAD

**Issue by botanize** [rstudio/rstudio#10883]
Hi, this is still an issue, I have other gitignore rules that cover .Rproj.user, for example `.*`, and yet, RStudio still edits my .gitignore file, without being asked to. I would really appreciate if I didn't have to reject changes to my ignore file every time RStudio thinks it knows better than I do.

_Originally posted by @botanize in https://github.com/rstudio/rstudio/issues/3326#issuecomment-1024481924_

**Comment by ronblum** [comment]
@botanize Thank you for raising this! I can reproduce this, as well. I'm reopening #3326 and closing this issue as a duplicate, so that we can keep track of the full history. I'll also mark the other issue as a regression.
