### ISSUE TITLE
Mac - Open associated files when clicked

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#10893]
After some light testing, dragging files onto the app will launch and attempt to open the file. R projects don't open though. Double-clicking the associated files in Finder should open RStudio as well but it doesn't appear to work.

The existing behaviour should be documented as well.

Split from #10437

**Comment by ronblum** [comment]
Verified that that both double-clicking on the file and dropping it on the application will open RStudio Desktop 2022.06.0-daily-333. Checked the following file types:
- .R
- .qmd
- .Rmd
- .Rproj
