### ISSUE TITLE
Add command to show accessibility diagnostics in Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10899]
We should add a diagnostic command for showing the `chrome://accessibility/` URL in Electron desktop, like we do for gpu diagnostics. This can be helpful in troubleshooting screen-reader issues.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.06.0-daily+296 on
- MacOS 12.3
- Red Hat 8.3

The window is reached via <kbd>Help -> Diagnostics -> Show Accessibility Diagnostics</kbd>. Also confirmed that it's only in Electron, not Qt.
