### ISSUE TITLE
Electron: Open newly rendered docx files with Word

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10897]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-2022.06.0-daily-266 (Electron)
    OS Version      : MacOS 12.3
    R Version       : 4.1.3

### Steps to reproduce the problem

Render a document in Word (docx) format. The default documents suffice.
- R Markdown: Set `output: word_document` in the YAML.
- Quarto: Set `format: docx` in the YAML.

### Describe the problem in detail

In an Electron Desktop, the .docx file is created, but Word doesn't automatically open.

### Describe the behavior you expected

Word (or LibreOffice in Linux, but I haven't tried there yet) should launch and open the rendered document in read-only mode. This is the behavior in the Qt version.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Handling this requires implementing the following callbacks:

https://github.com/rstudio/rstudio/blob/185809a4ca28cecc98ac67cd01d9228223d54796/src/node/desktop/src/main/gwt-callback.ts#L365-L367

https://github.com/rstudio/rstudio/blob/185809a4ca28cecc98ac67cd01d9228223d54796/src/node/desktop/src/main/gwt-callback.ts#L353-L355

We may need to port the associated code here for Windows:

https://github.com/rstudio/rstudio/blob/main/src/cpp/desktop/DesktopWordViewer.cpp

For a short-term solution, it might suffice to just use `shell.openPath()` in each case.

https://www.electronjs.org/docs/latest/api/shell#shellopenpathpath

**Comment by jonvanausdeln** [comment]
Verified on
2022.11.0-71
Windows 11
MacOS 12.4

Verified on both RMarkdown and Quarto documents.
