### ISSUE TITLE
Electron: Open source includes "Launcher" as a Tools menu item

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10900]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-2022.06.0-daily-266 (Electron)
    OS Version      : MacOS 12.3, Red Hat 8.3
    R Version       : 4.1.3

### Steps to reproduce the problem

In the open source version of RStudio Desktop (Electron), click on the "Tools" menu item.

### Describe the problem in detail

One of the items in dropdown list is "Launcher", which should not be available in the open source version.

<img width="255" alt="elec" src="https://user-images.githubusercontent.com/31009952/161632411-3146438b-c314-401a-bcfe-2d8e93ce207b.png">

### Describe the behavior you expected

"Launcher" should not be an option. Compare this to the Qt versions of Prairie Trillium and Spotted Wakerobin: 

<img width="265" alt="qt" src="https://user-images.githubusercontent.com/31009952/161632479-51747292-8909-45d5-9e8b-880b9a228609.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Verified fixed in 2022.06.0-daily+295 (Electron) on macOS.
