### ISSUE TITLE
Electron: Saving a new file doesn't use the chosen name and produces an error

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10905]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0_daily+236
    OS Version      : Red Hat 8.3, Ubuntu 20.04.4
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a new R Markdown file.
2. Click on the Save icon.
3. Enter a file name and click "Save".
4. Stop and restart RStudio Desktop.
 
### Describe the problem in detail

Instead of saving using the entered file name, the file is saved only with the `.Rmd` suffix as
 the name, and then this pop up appears:

<img width="545" alt="Screen Shot 2022-04-05 at 9 13 10 AM" src="https://user-images.githubusercontent.com/31009952/161764137-72d5dd30-440d-48a3-b8a9-caab87b39704.png">

The file's tab is still present in the Editor Pan, with the name `.Rmd`:

<img width="84" alt="Screen Shot 2022-04-05 at 9 13 19 AM" src="https://user-images.githubusercontent.com/31009952/161764294-c19c03f4-582c-4d3d-aac1-4e89cc98e81c.png">

The file is on the file system, named `.Rmd`:

```
-rw-rw-r--. 1 vmware vmware 829 Apr  5 09:13 .Rmd
```

In addition, restarting RStudio Desktop (step 4) results in gray screen with only the system menu options available. Resetting the state by removing `.local/share/rstudio` will fix this.

### Describe the behavior you expected

The file should be saved using the name that was entered, with no error pop ups.

Note: 
1) This is an issue on Linux. It works as expected on MacOS 12.3.
2) Similarly, doing the same with an R Script results in the file called `.R` but without the error.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note: I suspect this occurs whenever a file is saved without an extension, or with an extension that doesn't match the default file extension. For example, if you tried to save an R Markdown file as `test.R` for some reason.

**Comment by gtritchie** [comment]
I repro'd the problem using 2022.06.0_daily+248 on Ubuntu 20, then confirmed the problem no longer happened with build 2022.06.0_daily+287.
