### ISSUE TITLE
Current RStudio version is not installable on Ubuntu Jammy Jellyfish 22.04 LTS daily because of missing libssl1 dependency

### ISSUE THREAD

**Issue by N0rbert** [rstudio/rstudio#10902]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.1-461
    OS Version      : Ubuntu 22.04 LTS development version
    R Version       : 4.1.2

### Steps to reproduce the problem

1. Install latest Ubuntu MATE 22.04 LTS from *Ubuntu-MATE 22.04 LTS _Jammy Jellyfish_ - Daily amd64 (20220404)* ISO.
2. Run

   `wget https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb && sudo apt-get install -y ./rstudio-latest-amd64.deb`

    or

    `wget https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-2022.02.1-461-amd64.deb && sudo apt-get install -y ./rstudio-2022.02.1-461-amd64.deb`

### Describe the problem in detail

```
$ sudo apt-get install -y ./rstudio-latest-amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rstudio' instead of './rstudio-latest-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rstudio : Depends: libssl1.0.0 but it is not installable or
                    libssl1.0.2 but it is not installable or
                    libssl1.1 but it is not installable
           Recommends: r-base (>= 3.0.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

### Describe the behavior you expected

RStudio installs normally on Ubuntu 22.04 LTS.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
https://discourse.ubuntu.com/t/openssl-3-0-transition-plans/24453 has a bit of discussion here; looks like Ubuntu is moving to OpenSSL 3.0.

**Comment by jmcphers** [comment]
Agree with @kevinushey, we need to get builds up soon due to the SSL compatibility issue. A LOT of folks are going to upgrade.

**Comment by eitsupi** [comment]
Ubuntu 22.04 will be released in a week, is there any chance of a patch update (v2022.02.2) to resolve this?

**Comment by mikebessuille** [comment]
@eitsupi no, unfortunately we won't be able to support it on patches of older versions.  We expect to be able to support this with an Electron-based desktop build, which will have a preview ready in the next couple of months.

**Comment by mikebessuille** [comment]
@eitsupi It is possible that we won't be able to support it on patches of older versions. We expect to be able to support this with an Electron-based desktop build, which will have a preview ready in the next couple of months. See https://github.com/rstudio/rstudio/issues/9854 for more detail on how this relates to a bug in QT, which we are replacing with Electron. More investigation is needed...

**Comment by N0rbert** [comment]
It is really temporarily hackable on Ubuntu 22.04 LTS by manual download of [libssl1.1](https://packages.ubuntu.com/impish/libssl1.1) from *impish* repository, so by using commands below:

```
wget https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
wget -c http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
sudo apt-get install -y ./rstudio-latest-amd64.deb ./libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
```

and then run RStudio with `rstudio --no-sandbox` as mentioned in issue #9854 .

**Comment by eitsupi** [comment]
@mikebessuille Thank you for the explanation.
However, I have tried and this problem (OpenSSL problem) also occurs in RStudio Server.
Is this related to Qt or Election?

**Comment by mikebessuille** [comment]
There are at least two separate problems here.  one is the OpenSSL problem, reported here against desktop but which I assume would also be a problem on the server.  That one we could potentially resolve in the next release, Spotted Wakerobin.  However, on the desktop, that won't be enough for RStudio to run; I believe it will also need the Electron build for that.

Given that this is also a server issue, I'm moving this issue back to Spotted Wakerobin so we can at least address the server side sooner.

**Comment by N0rbert** [comment]
For Ubuntu 22.04 LTS one can use [my PPA with libssl1.1 from Ubuntu 21.10](https://launchpad.net/~nrbrtx/+archive/ubuntu/libssl1?field.series_filter=jammy) as follows:

```
sudo add-apt-repository ppa:nrbrtx/libssl1
sudo apt-get update
wget https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
sudo apt-get install -y ./rstudio-latest-amd64.deb
```

**Comment by mbousq** [comment]
distribute Appimage instead of deb ?

**Comment by ronblum** [comment]
Quick note: Both Electron and Qt versions aren't installable.
```
$ gdebi rstudio-2022.06.0-daily-323-amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libssl1.0.0|libssl1.0.2|libssl1.1
```

**Comment by dat-linux** [comment]
Can someone please explain what to do to get Rstudio working on Ubuntu 22.04? Something about an SSL library? Or are we waiting on package updates? What about packages that are installed via apt, will they be updated?

I have latest R, the latest rstudio amd64 binary as zip, downloaded. It opens, then freezes without loading the body of the application. Same for the .deb install. 

22.04 is a LTS release and has been keenly awaited for months.

**Comment by kevinushey** [comment]
Sorry again for the delay. Daily builds of RStudio built for Ubuntu Jammy are now available on the daily builds page:

https://dailies.rstudio.com/

The current daily build is https://s3.amazonaws.com/rstudio-ide-build/desktop/jammy/amd64/rstudio-2022.06.0-daily-340-amd64.deb, and we'd appreciate if you could test and report if RStudio is now able to launch without issue for you.

**Comment by jmbuhr** [comment]
Also works on pop os 22.04 (based on ubuntu 22.04)

**Comment by ronblum** [comment]
Verified that the following install and run on Ubuntu 22.04 with R 4.1.2:
- RStudio Desktop 2022.06.0-daily+340
- RStudio Server 2022.06.0-daily+340
Checked basic functionality, such as R script, R Markdown, and Shiny.

Please note that the dailies are intended for development and testing purposes.

**Comment by bastosfh** [comment]
Hi @kevinushey 
Works perfectly on my install of Ubuntu 22.04, with R 4.1.2 :+1:

**Comment by laur34** [comment]
@kevinushey 
Mine works now, too.
Rstudio Desktop 2022.06.0-daily+340 with R version 4.1.2 on Ubuntu 22.04.

**Comment by Xenolevis** [comment]
All fine:
Rstudio Desktop 2022.06.0-daily+340 with R version 4.2.0 on Ubuntu 22.04.

**Comment by MatthieuStigler** [comment]
Works! Any chance you include this into the current release?

**Comment by ronblum** [comment]
Please note that the dailies are intended for development and testing purposes.

### Verified Fixed
    RStudio Edition    :  Desktop / Desktop Pro / Server
    RStudio Version(s) : 2022.02.3-daily+489 & 2022.06.0-daily+374
    OS Version         : Ubuntu 22.04 (Jammy Jellyfish)

### Environment details

Does not include RStudio Workbench (see https://github.com/rstudio/launcher/issues/341).

### Test scenario(s) 

Checked basic functionality, such as startup, running an R script, and knitting an R Markdown file.

### Automated tests 

If the bug is present, existing RStudio Server automated test will fail because the application won't run.


Notes:
1. RStudio Workbench support is covered in private repos at https://github.com/rstudio/rstudio-pro/issues/3422 and https://github.com/rstudio/launcher/issues/341
2. The Spotted Wakerobin tests are a redundant w.r.t. https://github.com/rstudio/rstudio/issues/10902#issuecomment-1112626636
