### ISSUE TITLE
Electron: Session -> Interrupt R is always enabled and clickable

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10904]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+266
    OS Version      : MacOS 12.3, Red Hat 8.3
    R Version       : 4.1.3

### Steps to reproduce the problem

1. Don't run anything in the R Console.
2. Click on the "Session" dropdown menu.

### Describe the problem in detail

The menu item "Interrupt R" is always enabled and clickable. Nothing happens, though, when clicked on.

<img width="218" alt="session_elec" src="https://user-images.githubusercontent.com/31009952/161760516-e7a66fdf-a515-48d4-9e5d-0e184f30275a.png">

### Describe the behavior you expected

The menu item "Interrupt R" should only be enabled and clickable when the R Console is running something such as `Sys.sleep(1000)`.

Cf. Qt Desktop, with nothing running.

<img width="218" alt="session_og" src="https://user-images.githubusercontent.com/31009952/161760543-466e7347-bf4d-4e22-8d15-ab3d0c0e9386.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
I think the GWT code needs to emit an event to Electron so it can update the menu.

Electron needs this called:
https://github.com/rstudio/rstudio/blob/badc4743b2a0615ae468070af61f46a0d0ae4c55/src/node/desktop/src/main/menu-callback.ts#L257-L270

GWT updates the command here:
https://github.com/rstudio/rstudio/blob/8f85b6b8ed4e7db1ac167b2007d17e26c947e4fd/src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleInterruptButton.java#L67-L74

**Comment by timtmok** [comment]
It appears this was fixed. The code I linked has a commit message that mentions fixing this issue. It was committed 4 days after this issue was opened.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.11.0-daily+160 on MacOS 13.
Checked that
    - Interrupt isn't available when nothing is running.
    - Interrupt works when something is running: `Sys.sleep(1000)`

Double-checked that this continues to work in RStudio Server 2022.11.0-daily+160 on Red Hat 8.6.
