### ISSUE TITLE
Not all Vim keybindings are implemented

### ISSUE THREAD

**Issue by dlebedinsky** [rstudio/rstudio#10917]
### System details

    RStudio Edition : <Desktop>
    RStudio Version :  RStudio 2022.02.1+461 "Prairie Trillium" Release (8aaa5d470dd82d615130dbf663ace5c7992d48e3, 2022-03-17) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  Windows 10
    R Version       :  4.1.3 (2022-03-10) -- "One Push-Up"

### Steps to reproduce the problem
Go to Tools -> Global Options, click on Code, change Keybindings to Vim, and apply. Open any plain text file that takes up more than one full page on the screen, scroll down, and press Ctrl-Y. Nothing happens. This is not how Vim  behaves, see:
vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-Y

### Describe the problem in detail
The command to scroll up by one line without moving your cursor in Vim is Ctrl-Y, and the scroll down command is Ctrl-E. Ctrl-E works in Rstudio's vim keybindings, but Ctrl-Y does not.

### Describe the behavior you expected
Pressing Ctrl-Y should keep the cursor on the current line number, and scroll the file up towards the first line.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ N/A] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dlebedinsky Thank you for raising the issue! I can reproduce it on both MacOS 12.3 and Windows 10, using RStudio Desktop 1.3.1093, 2021.09.2+382, and 2022.06.0-daily-270. I'll mark this as a bug to review as we continue development of RStudio.

**Comment by colearendt** [comment]
Would love to see vim keybinding consistency!
