### ISSUE TITLE
Cross References in Rstudio Visual Editor Not Showing Up 

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#10918]
Reported by @ailich

I am unable to add cross references for things like figures using Rstudio's (version 1.461) visual editor via "insert > cross reference" as the option list shows up as empty. The syntax I'm using to ID the figure seems to be correct as I can cross-reference it if I manually type in "@fig-". I made a small example on github [here](https://github.com/ailich/quartotest) as a demo.

![noccrossrefs](https://user-images.githubusercontent.com/28163862/162010373-ac9ffb3a-92f7-4642-b5f5-01923aec5890.png)

This bug occurs because of a recent change to paths of quarto 3rd party binaries. The fix will be to have RStudio look in both the old and new locations.

**Comment by jjallaire** [comment]
Fixed with https://github.com/rstudio/rstudio/commit/64ca8618f8024c5254d576b8efa418d1c0509695

**Comment by ronblum** [comment]
3b. Verified in RStudio Desktop RStudio-2022.06-daily-317 (Spotted Wakerobin) on MacOS 12.3 with only the bundled CLI (version 0.9.230).
