### ISSUE TITLE
update version of cmake used in dependency scripts

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10916]
We're currently using CMake 3.4.3:

https://github.com/rstudio/rstudio/blob/3c041a08e8e9ac1dbe7ead2858c564c8ecfa44d6/package/linux/install-dependencies#L20

We should consider updating to something newer, especially so we can take advantage of some more modern CMake features (e.g. I wanted to use FetchContent for bundling of fmt).

**Comment by gtritchie** [comment]
Closing; this will be tested via the build pipeline.
