### ISSUE TITLE
respect logging environment variables in desktop

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10929]
For example, here:

https://github.com/rstudio/rstudio/blob/49ed99ad10f7af4f2f589c5ca22b82605fb818b3/src/cpp/core/LogOptions.cpp#L47-L51

The desktop client should read and parse those when determining the right way to log.

**Comment by kevinushey** [comment]
Note: RS_LOG_LEVEL is handled in https://github.com/rstudio/rstudio/pull/10930.

**Comment by ronblum** [comment]
Should we document this in the Desktop Guide, as we do in the RSW Admin Guide?

**Comment by kevinushey** [comment]
That's a good idea; yes we should.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+294 Linux Server and Desktop

Environment variables are respected for logging.
