### ISSUE TITLE
RStudio defaults to using all system memory

### ISSUE THREAD

**Issue by lykaios** [rstudio/rstudio#10925]
I use RStudio on a workstation which is shared by several users. To protect users from each other, I want RStudio sessions to initialize with only a portion of system RAM (e.g. 128GB total -> 32GB default). 

If I directly call an R script, I can use the flag `--max-mem-size=X`. 

This does not seem to work for RStudio, and neither does the previously working ENV variable `R_MAX_MEM_SIZE`. 

I am using RStudio 2021.09.1 on Windows 10/11.

**Comment by kevinushey** [comment]
Unfortunately, those options are no longer going to be supported in the next release of R:

https://github.com/wch/r-source/blob/67dc752717c385d34add8ebbd420334a029d110e/doc/NEWS.Rd#L489-L492

I'm not sure if there's an alternative solution, but given that R won't be supporting this interface going forward I don't think we can investigate further.

**Comment by lykaios** [comment]
Hi Kevin,

Thanks for your quick reply!

I understand that as a downstream user of the language your hands are somewhat tied. I’m puzzled why ´R´ is moving this direction though. Memory allocation for a process was fairly standard, I thought (e.g. JVM).

Do you have any suggestions on how to prevent R/Rstudio on eating a machine’s resources? Or is container-ization (e.g. Docker) the way to go?

Cheers

**Comment by kevinushey** [comment]
> Do you have any suggestions on how to prevent R/Rstudio on eating a machine’s resources? Or is container-ization (e.g. Docker) the way to go?

That would be a solution. I'm unfortunately not aware of other tools that might be used to limit the amount of memory made available to a process.

**Comment by lykaios** [comment]
That's a bit of a bummer... Thanks for the info
