### ISSUE TITLE
Can't create a Quarto document on Windows with bundled binaries

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10922]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+272
    OS Version      : Windows 11
    R Version       : 4.1.3 & 4.2.0

### Steps to reproduce the problem

This is on Windows only.

1. Don't install the Quarto CLI from https://quarto.org. If it's installed, remove it.
2. In RStudio Desktop, try to open a new Quarto document.

### Describe the problem in detail

The document fails to open. Instead, the following pop up appears:

![demo](https://user-images.githubusercontent.com/31009952/162063355-fdbd93e7-3e51-4119-9127-dca7fe1d51f3.png)

Going to the executables: `quarto.cmd` and `demo.exe` both result in the pop up and fail to run.

### Describe the behavior you expected

The Quarto document should be created.

Note that this works fine when Quarto is installed from https://quarto.org.

Triage note: Is this something we need to consider for a backport to Prairie Trillium?

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
RStudio installs various runtime libraries it requires on Windows here:

https://github.com/rstudio/rstudio/blob/7a6d81f19b465f5c74efc75e8ad0635f12e18980/src/cpp/session/CMakeLists.txt#L797-L801

https://github.com/rstudio/rstudio/blob/7a6d81f19b465f5c74efc75e8ad0635f12e18980/src/cpp/desktop/CMakeLists.txt#L519-L521

We might need to add vcruntime140_1.dll to the list. (I'm a little surprised this isn't distributed by default with Windows, though.)

**Comment by timtmok** [comment]
I tried installing build 309 and it looks like it installs `vcruntime140_1.dll` already. I also see it packaged in the archive version of the build as well.

![image](https://user-images.githubusercontent.com/9591545/163819825-6a1d68b0-20f9-4c35-943a-2ca16ee464d6.png)

**Comment by timtmok** [comment]
I think this is only affecting Electron builds. I installed the Electron 309 build and it did not include `vcruntime140_1.dll`. I can't reproduce the issue though but it's likely that it's due to my Windows install has the dll.
