### ISSUE TITLE
Label UI language choices in both languages

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10937]
The dropdown for choosing a UI language is currently only shown in the currently selected language. So if RStudio is currently in French, the choices are as follows (we don't actually have Spanish yet, just including for example):

- Anglais
- Espagnol
- Français

It would be better to show them both in the current language, and in their native language. If nothing else this makes it easier to switch back to a known language if you accidentally switch to one you don't know.

So when in French the choices would be:

- Anglais (English)
- Espagnol (Español)
- Français

In English:

- English
- Español (Spanish)
- French (Français)

**Comment by romainfrancois** [comment]
Verified in 

```
RStudio 2022.06.0-daily+351 "Spotted Wakerobin" Daily (ab19e471486aa89e6d350db4e93027845e0847f2, 2022-05-03) pour macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```
