### ISSUE TITLE
R Console font is Serif on Ubuntu 20.04

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#10939]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06..0-daily+382(.pro1 also)
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.4

### Steps to reproduce the problem

1. Install RStudio
2. Start the application

### Describe the problem in detail

The font in the console is serif:

![image](https://user-images.githubusercontent.com/37987486/162498168-fe8e2cdb-db65-4374-a329-7c10fdde09ad.png)

### Describe the behavior you expected

The font in the console should be non-serif:

![image](https://user-images.githubusercontent.com/37987486/162498235-d0be972e-28a0-42e9-bf08-c210efa813eb.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MariaSemple** [comment]
Note - these are Qt based builds not Electron

**Comment by kevinushey** [comment]
@MariaSemple, just to confirm, what editor font do you see in Tools -> Global Options... -> Appearance?

**Comment by MariaSemple** [comment]
On an older build:
![image](https://user-images.githubusercontent.com/37987486/162803345-3cad88a4-d4d6-4c42-89bf-77fc1282629e.png)

On latest:
![image](https://user-images.githubusercontent.com/37987486/162803589-e26203a7-4db8-4920-aec4-1c7ec54d9c3a.png)

**Comment by timtmok** [comment]
I think it's that `Courier 10 Pitch` isn't the correct way to specify the font family. It's odd that the console doesn't add in the `monospace` fallback like it does in the editor preview. I can see GWT adding the `monospace` fallback but maybe I accidentally removed it from somewhere else while working on font selection for Electron.

**Comment by MariaSemple** [comment]
I'm not sure, this is just the default on my system. I've never changed the font in rstudio

**Comment by gtritchie** [comment]
Maria reports that this is fixed.
