### ISSUE TITLE
soft-wrap source files in other languages (python)

### ISSUE THREAD

**Issue by whtns** [rstudio/rstudio#10940]
I would like to enable soft-wrapping for source files other than R, esp. python. I see a prior issue requesting wrapping for C/C++ files #5110 now marked as stale

**Comment by squiggledid** [comment]
I would also very much like this - especially for for Python.

**Comment by rodo-nunez** [comment]
+1

This point alone makes me go back to VSCode for Python coding

**Comment by rossellhayes** [comment]
I would also like to see this implemented

**Comment by nathhenry3** [comment]
Likewise - this is a crucial feature for code readability in modern IDE's

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+215 on Windows using multiple file types, including Python.
