### ISSUE TITLE
R Markdown PDF outputs show up in window rather than Viewer pane; quarto to PDF works

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/rstudio#10944]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.1 (Build 461)
    OS Version      :  macOS Monterey 12.2.1
    R Version       : 4.0.5 (2021-03-31)

### Steps to reproduce the problem

Render R Markdown file to PDF format.

### Describe the problem in detail

Hi,

When I render a R Markdown document to a PDF format, the document is previewed in a separate window outside of RStudio, despite the setting `Preferences > Show output preview in > Viewer Pane`. However, when I render a Quarto document to PDF, if properly shows up in the Viewer pane in the IDE.

Rendering R Markdown to an HTML format does open up the preview in the Viewer pane. So it seems to be an issue with PDF outputs.

https://user-images.githubusercontent.com/27825069/162544178-a10462f2-2891-46bb-9218-2b4c80e9353d.mov

### Describe the behavior you expected

PDF outputs for Rmd should show up in the Viewer pane of the IDE when this setting is enabled.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mattwarkentin Thank you for raising this! This is the behavior it's been in the past (I just used 1.2.5042, to make sure). Quarto and its features are new, so I'll mark this as an enhancement to see if we can do the same for R Markdown as we do for Quarto.
