### ISSUE TITLE
Redirected to wrong URL when X-Forwarded-Host  header includes multiple hosts

### ISSUE THREAD

**Issue by shota-matsumoto-lm** [rstudio/rstudio#10965]
### System details

    RStudio Edition : Server
    RStudio Version : 2021.09.1 Build 372
    OS Version      : Ubuntu 18.04.6 LTS (rocker docker image)
    R Version       : 4.1.2

### Steps to reproduce the problem
1. Run docker image by `docker run -d -p 8787:8787 -e PASSWORD=password rocker/rstudio:4.1.2`
2. Send request by curl command:
`curl -I 'http://localhost:8787' -H 'X-RStudio-Root-Path: /rstudio' -H 'X-Forwarded-Host: localhost,localhost' -H 'Connection: keep-alive' -H 'User-Agent: "Google Chrome"'`
3. HTTP Response 302 with a wrong location is returned from the server: 
```
HTTP/1.1 302 Moved Temporarily
...
Location: http://localhost,localhost/rstudio/auth-sign-in?appUri=%2F
```
### Describe the problem in detail

When `X-RStudio-Root-Path` is specified other than "/" and `X-Forwarded-Host`
includes multiple hosts separeted by commas, RStudio returns wrong URL including all of those hosts with commas. 
In my actual use case, RStudio is behind two nginx proxy server and deployed in the subdirectory under JupyterHub (such as `/user/foo/bar/rstudio`).

It seems that the cause of this problem exists in the following function, where `X-Forwarded-Host` is used without modification.
https://github.com/rstudio/rstudio/blob/6a13c2123d07ef2314236667d77c5b91e32536f8/src/cpp/core/http/Request.cpp#L96
(As a workaround, I added `Forwarded` header like `"host=localhost"` because it has higher priority than `X-Forwarded-Host`.)

### Describe the behavior you expected

I expect that RStudio returns a URL which includes only the first host in `X-Forwarded-Host`.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@shota-matsumoto-lm Thank you for raising this!

@jeffvroom Do you think the solution to #11010 would cover this as well?
