### ISSUE TITLE
Code folds and real time spell checker make editor unusable in RStudio Server

### ISSUE THREAD

**Issue by philayres** [rstudio/rstudio#10967]
### System details

    RStudio Edition : rstudio-server
    RStudio Version : 1.4.1717 (Juliet Rose) 
    OS Version      :  CentOS 7 (GNOME)
    R Version       :  3.6.1
    Browser     : Firefox (latest)

### Steps to reproduce the problem

- Ensure realtime spellcheck is enabled
- View the following large-ish R file (USGS trustworthy source, even if we are not going to actually run it): https://raw.githubusercontent.com/USGS-R/dataRetrieval/main/R/readNWISunit.r
- Start a new file in RStudio Server.
- Add the following comment line to start a code fold:

```
#### Fold 1 ####
```

- Copy and paste the raw content of the `readNWISunit.r` file into the editor.
- Copy and paste the full content of the editor 7 times, including the new comment at the top, to produce 8 foldable sections of about 5000 lines
- Save the file - *it is important that the file has been saved (new Untitled files won't exhibit the problem)*
- Now go back to the top and click the fold caret for each *Fold 1* comment.

After a few folds the rstudio-server editor becomes unusable, freezes, and the browser displays messages like "this page is slowing down your browser".

This only seems to happen with real scripts (I tried fabricating one with 5 lines and a folding comment above each, repeated 1000 times, and it didn't show the same issue) when using the code folding feature. The more large folding blocks there are, shrunk down, the worse the performance is. A real example one of my colleagues has had me investigate is 4500 lines with about 20 folding sections and quite dense code between them.

Compare this with the same raw source file copied and pasted 8 times without the *Fold 1* comment to produce large folding blocks. It is sluggish but functional, even if you fold the short blocks of code at curly braces.

**Now disable the realtime spellchecker and the problem goes away.**

I checked the browser dev console and there is not very much meaningful showing. No errors. Memory usage is 161MiB. Quite normal.

Profiling performance shows a point where there is a massive delay with a huge number of garbage collections happening within an event handler. My guess is that some interaction between the spell check and large shrunk folded sections (are comment blocks treated differently?) Perhaps the spellchecker is still checking when you fold a section and attempting to update hidden DOM elements? Who knows.

### Describe the problem in detail

The editor becomes unusable.

### Describe the behavior you expected

I should be able edit large files, even if that is poor coding practice.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report. A JavaScript profile:

<img width="396" alt="Screen Shot 2022-04-20 at 11 47 19 AM" src="https://user-images.githubusercontent.com/1976582/164301430-c0b09f86-3dbb-4db3-ab16-ec7a260cd165.png">

Will see if I can dig in more.

**Comment by kevinushey** [comment]
It looks like we're spending a lot of time converting from document indexes (number of characters in the document) to Ace document (row, column) positions.

<img width="946" alt="Screen Shot 2022-04-20 at 12 41 14 PM" src="https://user-images.githubusercontent.com/1976582/164309997-ec15230d-98b6-4ff5-944e-1a47dba96682.png">

This happens multiple times for each word being checked. We probably need to rip out the WordRange object and have instead have a more abstract way of referencing text in the document based on either document positions or indexes.

**Comment by romainfrancois** [comment]
And then again also higher up: 

```java
         if (!spellChecker().shouldCheckSpelling(spellingDoc, wordRange))
            continue;

         // build up the HashMap of words to wordranges
         String word = spellingDoc.getText(wordRange);
```

The `getText()` is a 3rd call to `toAceRange()` for the same `SpellingDoc.WordRange`. 

![image](https://user-images.githubusercontent.com/2625526/167167330-a59064a8-200a-4621-86f5-89ede2dd17f5.png)

**Comment by kevinushey** [comment]
@romainfrancois assigning you because you did some preliminary legwork; feel free to re-assign if you're overloaded.

**Comment by romainfrancois** [comment]
I'll try to eliminate duplicated `toAceRange()` calls, and see if the performance is good enough then.

**Comment by romainfrancois** [comment]
Seems that the `AceEditor > getSpellingDoc > getWords` goes from a thing that iterates on `Range` to a thing that iterates on `WordRange`: 

```java
         @Override
         public Iterable<WordRange> getWords(int start, int end)
         {
            return new Iterable<WordRange>() {

               @Override
               public Iterator<WordRange> iterator()
               {
                  // get underlying iterator
                  Iterator<Range> ranges = AceEditor.this.getWords(
                        fileType_.getSpellCheckTokenPredicate(),
                        fileType_.getCharPredicate(),
                        positionFromIndex(start),
                        end != -1 ? positionFromIndex(end) : null).iterator();

                  // shim it on to spelling doc iterator
                  return new Iterator<WordRange>() {

                     @Override
                     public boolean hasNext()
                     {
                        return ranges.hasNext();
                     }

                     @Override
                     public WordRange next()
                     {
                        Range range = ranges.next();
                        return new WordRange(
                           indexFromPosition(range.getStart()),
                           indexFromPosition(range.getEnd())
                        );
                     }
                  };
               }
            };
         }
```

especially the: 

```java
                       return new WordRange(
                           indexFromPosition(range.getStart()),
                           indexFromPosition(range.getEnd())
                        );
```

which create a `WordRange` from a `Range`. This bit has some cost already, but then `getLint()` spends a lot of time going the other direction (from `WordRange` to `Range`). 

Could there be a way to work directly with the `Range` instead ?

**Comment by romainfrancois** [comment]
Another potentially very relevant thing is how the range of rows we are looking for words from is calculated. e.g. with this on: 

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/2625526/167414452-69c82f79-35a3-4a62-8bf6-0ee32f7b32a5.png">

```java

public void getLint(ServerRequestCallback<JsArray<LintItem>> request)
   {
      JsArray<LintItem> lint = JsArray.createArray().cast();
      SpellingDoc spellingDoc = docDisplay_.getSpellingDoc();

      // only get tokens for the visible screen
      Iterable<SpellingDoc.WordRange> wordSource = spellingDoc.getWords
        (docDisplay_.indexFromPosition(Position.create(docDisplay_.getFirstVisibleRow(), 0)),
        docDisplay_.indexFromPosition(Position.create(docDisplay_.getLastVisibleRow(),
        docDisplay_.getLength(docDisplay_.getLastVisibleRow()))));

      GWT.log("first visible row:" + docDisplay_.getFirstVisibleRow());
      GWT.log("last  visible row:" + docDisplay_.getLastVisibleRow());

... 
```

this reports: 

![image](https://user-images.githubusercontent.com/2625526/167414552-6cbf09c4-4213-40cd-a0c7-5526a9484c7e.png)

which includes all the the folded content, and is probably the cause of the overwhelmingness.

**Comment by romainfrancois** [comment]
See "Steps to reproduce the problem" above, the editor should stay responsive when folding all the folds.

**Comment by jgutman** [comment]
Verified in both RStudio Server and RStudio Desktop 2022.6.0.391 on Google Chrome 101.0.4951.54 and Mac OS 12.3.1
