### ISSUE TITLE
Quarto file types not showing up in New File dropdown for bundled MacOS Quarto

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10966]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily-287 and 295
    OS Version      : MacOS 12.3
    R Version       : 4.1.3, 4.2.0

### Steps to reproduce the problem

In RStudio Desktop on MacOS
1. If Quarto was installed using the CLI from https://quarto.org remove it.
2. <kbd>Tools -> Global Options -> R Markdown -> Quarto</kbd>
3. Make sure that "Enable Quarto previews" is checked. If not, check it, click "OK," and RStudio will restart.
4. <kbd>File -> New File</kbd>

### Describe the problem in detail

Quarto file types aren't in the New File menu.
<img width="495" alt="quarto_missing_295" src="https://user-images.githubusercontent.com/31009952/163180913-1da174d0-d02e-489a-9902-8dcfdd140c32.png">

### Describe the behavior you expected

Quarto Documents and Presentations should be available in the dropdown menu.

Note:
1) This works correctly if the Quarto CLI is installed from https://quarto.org.
2) This started in build 287; 286 and earlier work.
3) This works in RStudio Desktop on Red Hat 8.3, and RStudio Server on Ubuntu 20.04.
4) Existing Quarto files can be opened and renderable, so `quarto` is available.

<img width="535" alt="quarto_present_286" src="https://user-images.githubusercontent.com/31009952/163181083-9fc6e19a-dcc4-44d3-97cb-9c9a7bf2bcbe.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
I can confirm this was an issue with build 287, but I believe this is no longer an issue with current build: RStudio 2022.06.0-daily+391 "Spotted Wakerobin" 

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2625526/168035887-366217b9-e50e-4033-9467-79957e4c3eb2.png">

Presumably from this commit: https://github.com/rstudio/rstudio/commit/8b5fb02590db87ae103f6b896c99044798b2381a
