### ISSUE TITLE
Erroneous linting messages

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#10979]
Some perfectly valid syntax is flagged with warnings or errors by the IDE.

In Keras, the first argument to a Layer can be missing, which indicates that the user is not interested in composing the layer instance with anything and the layer instance should be returned directly. Unfortunately, a convenient way of specifying a missing argument raises a warning.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/8462255/163421304-6a57ab0d-1705-468e-9b0a-43ddb554797c.png">

In a similar vain, Tensorflow Tensors allow users to perform a strided slice like this, which also raises a linting error:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/8462255/163421778-16f1eaac-888c-4fa9-be44-0a25bad7dd24.png">

**Comment by kevinushey** [comment]
The issue with `1:2:3` should be resolved in the next daily builds.

For the issue with linting of missing function calls, I think we should either extend the diagnostics engine to allow users to control this option, or see if we can make the diagnostic "smarter" in some way.
