### ISSUE TITLE
Query box in the Help pane results in Internal Server Error with `[<-`

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#10975]
### Problem

Just type `` `[<-` `` (backticks included!) into your seach box in the Help pane:

![snap](https://user-images.githubusercontent.com/19862384/163291771-b3904acf-6d4d-40c9-bfad-eefbbc06c503.png)

### System details

    RStudio Edition : Desktop 
    RStudio Version : RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for Ubuntu Bionic Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version: Archlinux
    R Version: 4.1.2

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ramiromagno Thank you for raising the issue! I can reproduce this in RStudio Server 2022.06.0-daily+296 as well. Going back to RStudio Desktop 1.0.153, the result is 
> Error in grep(pattern, x, ignore.case = ignore.case, perl = use_UTF8) : invalid regular expression '`[<-`'

I'll mark this for review as we continue to develop and update RStudio.

**Comment by kevinushey** [comment]
The search item being used here is being passed to `help.search()`, which spits a similar error:

```
> help.search("[<-")
Warning in grep(pattern, x, ignore.case = ignore.case, perl = use_UTF8) :
  TRE pattern compilation error 'Invalid character range'
Error in grep(pattern, x, ignore.case = ignore.case, perl = use_UTF8) : 
  invalid regular expression '[<-', reason 'Invalid character range'
```

I'm not sure how many users know (or expect) this field to be a valid regular expression, though.

In addition, if you try to use a leading `\`, you'll see a bunch of warnings in the console:

```
Warning in grep(pattern, matches, value = TRUE, perl = TRUE) :
  PCRE pattern compilation error
	'missing terminating ] for character class'
	at ''
Error in grep(pattern, matches, value = TRUE, perl = TRUE) : 
  invalid regular expression '^[.]*[\]'
```

which we should probably fix.

**Comment by ramiromagno** [comment]
Issue still persists in RStudio version:

RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-20) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by ramiromagno** [comment]
Issue still lives on and well in:

```
"Cherry Blossom" Release (3c53477a, 2023-03-09) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
```

**Comment by ramiromagno** [comment]
Issue still present in:

RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-05) for Ubuntu Focal
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+641 on Windows 11. Note that ``` `[<-` ``` doesn't returning anything, but `[<-` does.
