### ISSUE TITLE
Hyperlinks aren't affected by text colour

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#10977]
### System details

    RStudio Edition : Deskop
    RStudio Version : 2022.06.0 Build 277
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

```R
link <- cli::style_hyperlink("test", "http://rstudio.com")
cli::col_blue("x ", link)
cli::col_white("x ", link)
```

### Describe the problem in detail

<img width="620" alt="Screen Shot 2022-04-14 at 08 35 20" src="https://user-images.githubusercontent.com/4196/163402056-e9e49ee1-f537-4ebd-9fd9-1673c61d8c42.png">

### Describe the behavior you expected

Links should be affected by text colour

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
QA notes from: https://github.com/rstudio/rstudio/pull/11009

```r
pak::pak("r-lib/cli")

library(cli)

link <- cli::style_hyperlink("test", "http://rstudio.com")

# magenta
link

# red
cli::col_red(link)

# red
cli::style_hyperlink(cli::col_red("test"), "http://rstudio.com")
```

**Comment by hadley** [comment]
Having tried out the new behaviour (which is great!) it's probably worth at least asking if the _default_ link colour should also match the text colour (i.e. when not overridden by a specific ANSI colour ). I could argue it either way.

**Comment by romainfrancois** [comment]
I think I would like it. With the dotted lines they already have something that stands out, and then it would be up to the user to decide their colour.

**Comment by romainfrancois** [comment]
after this: https://github.com/rstudio/rstudio/pull/11147: 

```r
# pak::pak("r-lib/cli")

cat(
  cli::style_hyperlink("black", "http://rstudio.com"), 
  cli::style_hyperlink(cli::col_red("red"), "http://rstudio.com"), 
  cli::col_blue(cli::style_hyperlink("blue", "http://rstudio.com")), 
  "\n"
)
```

<img width="552" alt="image" src="https://user-images.githubusercontent.com/2625526/167134009-ac3de94e-a9c5-4119-a0db-12bd0658e740.png">

**Comment by hadley** [comment]
Yeah, that looks good to me.

**Comment by jgutman** [comment]
Verified in 2022.6.0.374 on RStudio Desktop with Mac OS 12.3.1 (cli version 3.3.0.9000, R 4.2)
