### ISSUE TITLE
Wrong help pop-up can be shown sometimes

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#10980]
In this example, the popup shows the signature for `stats::reshape()` which is very different from `tf$reshape()`

<img width="758" alt="image" src="https://user-images.githubusercontent.com/8462255/163422773-ad3ff9ce-c4b2-4b61-bf01-e6e592150b3d.png">

**Comment by ronblum** [comment]
@t-kalinowski Thank you for raising this! We'll review this as part of our ongoing development of RStudio.

**Comment by kevinushey** [comment]
For reference, the call being made is here:

https://github.com/rstudio/rstudio/blob/713739867731e2e9966cd086372f9e9d0de7d2d8/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/SignatureToolTipManager.java#L555-L558

We'd need to enhance our call here with the extra context from where `reshape()` is being invoked, and (most likely) hook up the extra argument autocompletion stuff if relevant for Python objects.

**Comment by t-kalinowski** [comment]
I'm still encountering this bug.
