### ISSUE TITLE
Diagnostic information showing up at the time of R Markdown instead of next to line with problem (source mode)

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10984]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.06.0+296
    OS Version      : MacOS 12.3 and Ubuntu 20.04
    R Version       : 4.1.3 & 4.2.0

### Steps to reproduce the problem

1. Turn on diagnostics in <kbd>Tools -> Global Options -> Code -> Diagnostics</kbd>
2. Open a new R Markdown file; the default works.
3. Switch to source mode.
4. In a chunk, add some bogus code—an undefined object, syntax error, etc. E.g.
````
```{r cars}
summary(cars)
y
print(
```
````
5. Save the file.

### Describe the problem in detail

Diagnostic information showing the problems doesn't appear next to these lines. Instead, they appear at the top.

<img width="263" alt="diag_wrong" src="https://user-images.githubusercontent.com/31009952/163437894-8fd7956f-58bc-4966-91fc-95b36012c8d4.png">

### Describe the behavior you expected

The lines with the problems should be identified in place, as it does with Prairie Trillium 2022.02.2+481.

<img width="283" alt="diag_right" src="https://user-images.githubusercontent.com/31009952/163437918-09664b47-0bfd-4fb3-93d7-afdba5fd7fbd.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Might be related to other problems with diagnostics and gutter information that are assigned to Tim in SW

**Comment by jgutman** [comment]
This regression was introduced in 2022.06.0+252. Behavior works as expected in 2022.06.0+250.

**Comment by jgutman** [comment]
QA: Test that diagnostic code markers show up on the correct line. Also retest the issue from the original PR https://github.com/rstudio/rstudio-pro/issues/3310 to ensure it doesn't unnecessarily flag Quarto docs with no chunks or with python chunks only

**Comment by romainfrancois** [comment]
Verified with RStudio 2022.06.0-daily+391 "Spotted Wakerobin"

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2625526/168029951-ca1085e2-c2c2-4a53-bf48-23794e54d00a.png">

**Comment by romainfrancois** [comment]
> QA: Test that diagnostic code markers show up on the correct line. Also retest the issue from the original PR https://github.com/rstudio/rstudio-pro/issues/3310 to ensure it doesn't unnecessarily flag Quarto docs with no chunks or with python chunks only 

✅ 

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/2625526/168030563-cb000583-3098-4385-8c64-9301e56e2fec.png">

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/2625526/168030614-7dfb8c40-a03d-4922-a524-c791323181b3.png">
