### ISSUE TITLE
R Markdown edit toolbar get shown after displaying document outline

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10987]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0+300
    OS Version      : macOS 12.3.1
    R Version       : 4.2.0

### Steps to reproduce the problem

Create a new R Markdown document, and then click the Toggle Document Outline button.

### Describe the problem in detail

The editor toolbar is displayed, and sometimes even duplicated.

<img width="950" alt="Screen Shot 2022-04-14 at 11 47 48 AM" src="https://user-images.githubusercontent.com/1976582/163457267-fe0e95b4-f174-45cc-9912-0751e070d4ae.png">

### Describe the behavior you expected

The editor toolbar shouldn't ever be displayed if the document is in source mode.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
I'm pretty sure I saw another issue that mentioned the duplicate toolbar but didn't know how to reproduce. I'll see if I can track that one down -- I expect it's probably fixed now too

**Comment by jgutman** [comment]
The issue in question is #10471 -- however, this was linked to visual mode specifically, and lacked a repro, so I can't be confident if this fix would resolve the larger issue. I did notice here however, before this issue (10987) was fixed, toggling the document outline a single time didn't necessarily produce the toolbar, but toggling it on and off repeatedly did inconsistently produce the toolbar, sometimes in duplicate/triplicate etc

**Comment by jgutman** [comment]
Verified in 2022.6.0.374 RStudio Desktop on Mac OS 12.3.1 -- source mode now consistently displays 0 edit toolbars and visual mode consistently displays 1 edit toolbar
