### ISSUE TITLE
`_quarto.yml` files in non-website Quarto projects are not initially selected, or even available, in the Publish wizard

### ISSUE THREAD

**Issue by toph-allen** [rstudio/rstudio#10995]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 305
    OS Version      : macOS 12.3
    R Version       : 3.6.3, but this issue also occurs on 4.*

### Steps to reproduce the problem

1. Create a new Quarto project — just an ordinary project, not a website. The default Quarto project in the IDE includes `name-of-quarto-project.qmd` and `_quarto.yml`.
2. Click the Publish button, select RStudio Connect (maybe optional), and select "Publish document with source code"

### Describe the problem in detail

The `_quarto.yml` file should be selected — it contains project-level metadata. However, it's not even visible in the file pane.

To add it, I have to click "Add More…" and select it, at which point the `.qmd` file is modified to add it as a `resource_file`.

### Describe the behavior you expected

A `_quarto.yml` file should always be included in Quarto deployments if it is present in the project directory.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@toph-allen Thank you for raising this! I can reproduce this in 2022.02.1 as well. However, it looks like this isn't specific to Quarto—the same thing happens in other project types for files beginning with `_` (underscore). I'll mark this for review as part of our ongoing development of RStudio.

Note: Tagging this with the `quarto` label because of the impact this has on Quarto projects, even though they're not the cause.

**Comment by toph-allen** [comment]
@ronblum Yeah, the `quarto` tag makes sense -- I'm not sure what the expected behavior is for other types of project files beginning with `_`, but for Quarto, including the project file is expected.

**Comment by ronblum** [comment]
Question for @romainfrancois (I forgot to tag you).

**Comment by romainfrancois** [comment]
I'm not sure. I think `_quarto.yml` should be unique, and identifies the quarto project, whereas there can be `_metadata.yml` files in sub directories of the project. But I don't know enough about quarto to be sure.

**Comment by jthomasmock** [comment]
https://quarto.org/docs/projects/quarto-projects.html#shared-metadata

> Any document rendered within the project directory will automatically inherit the metadata defined at the project level.
> 
> Note that the project file contains both global options that apply to all formats (e.g. toc and bibliography) as well as format-specific options.
> 
> You can include additional metadata linked via metadata-files and provide per-directory options by adding a _metadata.yml file to any sub-directory of your project. Options provided within these files use the same schema as _quarto.yml, and are merged with any options you’ve already provided in _quarto.yml.

**Comment by ronblum** [comment]
@jthomasmock Thank you for the reference and explanation!

Simple way to verify the `_metadata.yml` behavior:
1) Create a Quarto Blog project.
2) Render the website in the Build Pane using "Render Website."
3) Publish the website, choosing "Publish website with source code."
    - One of the files that gets picked up is `posts/_metadata.yml`

**Comment by romainfrancois** [comment]
Thanks @jthomasmock
