### ISSUE TITLE
Code sections inside curly braces do not indent properly in outline pane

### ISSUE THREAD

**Issue by ghonerka** [rstudio/rstudio#10992]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.2.0.443
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : R version 4.1.3 (2022-03-10)

### Steps to reproduce the problem
Create a new R script in RStudio and define at least two code sections inside a pair of curly braces.

### Describe the problem in detail
When code sections are defined inside a pair of curly braces, the sections following the first section are indented by one level when viewed in the outline pane or Jump To menu.  For example:
`{`
`# Section 1 ----`
`# Section 2 ----`
`}`
In the outline pane, Section 2 is indented, as if it were a subsection of Section 1:
![image](https://user-images.githubusercontent.com/8388830/163473346-879b2863-1a7e-43db-a013-2511051b22bd.png)

### Describe the behavior you expected
I expected Section 2 to be displayed at the same level of indentation as Section 1, as occurs when the sections are not defined inside curly braces:
![image](https://user-images.githubusercontent.com/8388830/163473844-328bdc02-f9b1-4358-9369-76381e1d5721.png)

I notice that the issue disappears if there is at least one subsection nested under Section 1:
![image](https://user-images.githubusercontent.com/8388830/163474214-caa52b3b-8fd2-476c-8666-e7e9995f2a37.png)

**Comment by ronblum** [comment]
@ghonerka Thank you for raising this! I can reproduce this, going as far back as RStudio Desktop 1.0.153, on MacOS 12.3. We'll review this as we continue development of RStudio.
