### ISSUE TITLE
Insert-citation tool doesn't increase collection name line spacing after wrapped Zotero collection name

### ISSUE THREAD

**Issue by rgayler** [rstudio/rstudio#10994]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.02.1 Build 461
    OS Version      :  Ubuntu 21.10 64-bit
    R Version       :  4.1.3

This is only relevant to people who use Zotero to manage references and use the R Studio visual mode insert-citation tool.
It is a problem in how the inser-citation tool formats the list of available Zotero collections in the insert-citations tool.

### Steps to reproduce the problem

* Start Zotero
* Make sure you have at least 2 collections in My Library
* Create a new collection with a very long name *above* the last pre-existing collection. I used "Predictive State Representations & Conceptors"
* Close and re-start Zotero
* Start R Studio IDE
* Make sure the options are set to use Zotero as a citation source
* Create a new R Markdown document
* Use Visual editor mode
* Open the insert-citation tool to insert a citation
* Open the Zotero My Library citation source to display the collections.
* Look at the formatting of the collection names  in the insert-citation tool
  * The really long collection name has been wrapped
  * The spacing above the really long collection name has been increased to allow for the wrapped collection name being multi-line
  * The spacing below the really long collection name has not been increased and consequently the next collection overtypes the last line of the really long collection name
  
### Describe the problem in detail

When a really long collection name has been line-wrapped in the insert-citation tool, the spacing above the really long collection name has been increased to allow for the wrapped collection name being multi-line, but tThe spacing below the really long collection name has not been increased and consequently the next collection name overtypes the last line of the really long collection name

![image](https://user-images.githubusercontent.com/5409051/163528062-70b3bbff-3e1b-4b5d-84fa-7ff83b035f76.png)

### Describe the behavior you expected

I expected the spacing below the wrapped collection name to be increased like the spacing above has been.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by arthursmalliii** [comment]
The same issue applies when multiple Zotero libraries are active.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/2918094/166150000-f7c1dfae-0961-441b-99bb-8239c09ddafd.png">

**Comment by rgayler** [comment]
Just re-mentioning it because of the automated stale flag:

The issue is still present in: 
RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by rgayler** [comment]
Just re-mentioning it because of the automated stale flag:

The issue is still present in:
RStudio 2023.03.1+446 "Cherry Blossom" Release (6e31ffc3ef2a1f81d377eeccab71ddc11cfbd29e, 2023-05-09) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.1+446 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

**Comment by rgayler** [comment]
I was prompted to look at this again because of the automated stale issue flag>

The issue appears to have gone away without any action listed in this thread.
![image](https://github.com/user-attachments/assets/d52256f0-51c5-451a-8009-cec8012a0191)

I have tested in both R Markdown and Quarto files.
The issue is now absent from both, as expected because I presume it was an RStudio issue rather than being a file-format-specific issue.

FWIW I tested on:
RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.4.549 (/opt/quarto/bin/quarto)
