### ISSUE TITLE
Incorrect link in the RMarkdown options menu

### ISSUE THREAD

**Issue by joelostblom** [rstudio/rstudio#11005]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.02.1
    OS Version      :  PopOS 21.10
    R Version       :  4.1.2

### Steps to reproduce the problem

When I click the little question mark next to the `Automatic text wrapping (line breaks)` option, it redirects me to https://rstudio.github.io/visual-markdown-editing/#/markdown?id=line-wrapping, but it seems like the page has moved to https://rstudio.github.io/visual-markdown-editing/markdown.html#line-wrapping

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/4560057/163721819-9c0ec0c1-d337-4e44-92a3-5bc4879d2f9f.png)

### Describe the behavior you expected

Redirect to the correct page

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@joelostblom Thank you for raising the issue! I'll mark it for review as part of our ongoing development of RStudio.

Triage note: If possible, we should consider a redirect since this affects all current versions.

**Comment by jjallaire** [comment]
Just updated the redirects so these links should now be working correctly.

**Comment by romainfrancois** [comment]
Verified in RStudio 2022.06.0-daily+373
