### ISSUE TITLE
mouse back button displays "Loading R" page after changing projects

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11016]
### System details

    RStudio Edition : Electron
    RStudio Version : 2022.06.0 Build 310
    OS Version      : macOS 12.3.1
    R Version       : Any

### Steps to reproduce the problem

Launch RStudio, and try using the mouse back button. Notice that it navigates through the source history. This is expected.

Then, try changing projects (via the drop-down menu at the top right). Then, right using the mouse back button again.

### Describe the problem in detail

The "Initializing R" window is displayed.

<img width="706" alt="Screen Shot 2022-04-19 at 4 53 50 PM" src="https://user-images.githubusercontent.com/1976582/164119717-b71ace85-a463-48fb-b413-ca885106be32.png">

### Describe the behavior you expected

The mouse back button should still navigate through the source history.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For Electron, the mouse back + forward handlers are initialized here:

https://github.com/rstudio/rstudio/blob/0b7dcd0b7094d1bb0c21cb10bcaabde3972aae85/src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java#L127-L137

It looks like those handlers are actually working, but Electron is still seeing and handling the event (despite our attempts to cancel the default behavior).

**Comment by ronblum** [comment]
Step 1: Purchased a mouse with a "back" button. My two current mice don't have it.

**Comment by ronblum** [comment]
Step 2: Unpack Tecknet mouse etc.

---

### Verified Fixed
    RStudio Edition    :  Desktop
    RStudio Version(s) : 2022.06.0-daily-374
    OS Version         : MacOS 12.4, Windows 11

### Environment details
 
Only verified on MacOS and Windows.

### Test scenario(s) 

1. Checked that forward and back buttons go forward and back through files/history
    a. in a project
    b. outside of a project
2. Checked that buttons only use history for the project/no project and
    a. doesn't show the "Initializing R" page 
    b. doesn't try to traverse between projects/no project

### Automated tests 

N/A
