### ISSUE TITLE
Incorrect redirect when X-Forwarded-Proto has multiple values

### ISSUE THREAD

**Issue by kimwnasptd** [rstudio/rstudio#11010]
### System details
Was using the Kubeflow images
https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/base/Dockerfile
https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/rstudio/Dockerfile

    RStudio Edition : Server
    RStudio Version : v1.4.1717
    OS Version      : ubuntu:20.04
    R Version       : 4.1.0

### Steps to reproduce the problem
1. While we bumped into this for KF images, this also holds for the rocker ones:
    ```bash
    docker run -d -p 8787:8787 -e PASSWORD=asdf rocker/rstudio:4.1.0
    ```
2. Send a request with a list of values for `X-Forwarded-Proto`:
    ```bash
    curl -I localhost:8787 \
    -H "User-Agent: Google Chrome" \
    -H "X-RStudio-Root-Path: /rstudio/kubeflow-user/kimwnasptd/" \
    -H "X-Forwarded-Proto: https,https"
    ```
3. The `location` header of the 302 response (due to missing cookies) is incorrect:
    ```
    Location: /auth-sign-in?appUri=%2F
    ```
4. The correct `location` should have been
    ```
    Location: https://localhost:8787/rstudio/kubeflow-user/kimwnasptd/auth-sign-in?appUri=%2F
    ```

### Describe the problem in detail

The problem is that while the server can correctly handle single values, like `X-Forwarded-Proto: https`, it fails to properly parse the proto when it's a list of values, like `X-Forwarded-Proto: https,https`.

We've seen this in a Kubeflow installation in AWS, where there are 2 proxies. First the AWS LoadBalancer, that initially adds the `X-Forwarded-Proto` header, and then an NGINX proxy that appends a protocol value.

Note that this is the default behavior of NGINX, to append values in the `X-Forwarded-*` headers https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

### Describe the behavior you expected

The server should
1. Not fail to construct the whole URL, when a list of proto values is provided
2. Use only the first proto value, in case of a comma-separated list, which is what the client used for talking to the first LoadBalancer

This is a rather common bug we've seen in software that handles the `X-Forwarded-*` headers:
* https://github.com/deis/deis/issues/4997
* https://support.f5.com/csp/article/K08436731

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

EDIT: Just saw there's a very similar issue for the `X-Forwarded-Host` header and multiple values. Seems like we could kill 2 birds with one stone and get this right for all `X-Forwarded-*` headers https://github.com/rstudio/rstudio/issues/10965

**Comment by ronblum** [comment]
@kimwnasptd Thank you for raising this issue, as well as referencing #10965! We'll review this is part of our ongoing development of RStudio.

**Comment by jeffvroom** [comment]
@kimwnasptd Yes, thanks for filing this issue with the nice test case. Looks like a straightforward fix to this function: https://github.com/rstudio/rstudio/blob/88d5f9b1359d261f56a8721ca1bc03d13fbc9701/src/cpp/core/http/Request.cpp#L96  I think in this case, we want the original protocol used so I'm thinking it's the first one in the list?  Also, notice that we will use X-RStudio-Request, or the Forwarded header in place of X-Forwarded-Proto if those headers are supplied, so if you are able to change the config for the proxy server, there might be a workaround.  See the documentation here: https://docs.rstudio.com/ide/server-pro/access_and_security/running_with_a_proxy.html for what's expected from those headers.
