### ISSUE TITLE
Visual Mode adds unnecessary spaces between list operators and list item text

### ISSUE THREAD

**Issue by leowill01** [rstudio/rstudio#11013]
### System details

    RStudio Edition : desktop
    RStudio Version : RStudio 2022.02.1 Build 461
    OS Version      : macOS Monterey Version 12.3.1 (21E258)
    R Version       : R version 4.1.3 (2022-03-10) -- "One Push-Up"

### Steps to reproduce the problem

1. make a new R markdown document with `File > New File > R Notebook`
2. in `Source` mode, insert any kind of markdown list (unnumbered, numbered, task). this list will usually have only one space between the list operator and list item text content. e.g.:

```
- unnumbered item
1. numbered item
- [ ] task item
```

![Screen Shot 2022-04-19 at 11 48 28 AM](https://user-images.githubusercontent.com/43548130/164058775-4228dcb9-6e61-4e12-a469-c7fa5fe1839e.png)

4. turn on `Visual` mode in the RStudio toolbar
5. switch back to `Source` mode
6. extra spaces have been inserted between the list operators and the list contents:

![Screen Shot 2022-04-19 at 11 49 32 AM](https://user-images.githubusercontent.com/43548130/164058812-a0bf3ebc-a89c-45c6-bb65-5a63e10cbd03.png)

### Describe the problem in detail

When switching from `Source` mode to `Visual` mode, extra spaces are inserted in between list operators and the list item text content. This breaks syntax recognition for other programs that expect e.g. especially task lists that have only one space between the `-` and the `[ ]`. I'm not sure why RStudio insists on inserting these extra spaces as it seems unnecessary and breaks other functionality outside of RStudio. I know there must be a reason this was implemented, but I haven't seen any other markdown program use this syntax. Here is an example of the app Zettlr not being able to render task lists effectively:

![Screen Shot 2022-04-19 at 12 09 17 PM](https://user-images.githubusercontent.com/43548130/164058859-db4057dc-d81f-42e3-a272-4779d41d3754.png)

### Describe the behavior you expected

I expect that no extra spaces will be added after list operators when switching between `Source` and `Visual` modes while working with R Markdown documents in RStudio. I would at the very least like to have this as an option that I can turn off.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@leowill01 Thank you for raising this! I suspect that this is driven by Pandoc, but I'll mark this for review.

In the meantime, using canonical mode might address this: https://rstudio.github.io/visual-markdown-editing/markdown.html#canonical-mode

**Comment by ronblum** [comment]
See also https://github.com/jgm/pandoc/issues/7172

**Comment by leowill01** [comment]
@ronblum 

>  I suspect that this is driven by Pandoc and not in RStudio

I did see this mentioned in a thread in RStudio issues a while back that it indeed was a `pandoc` formatting issue, but I can't remember where I saw it at.

>  In the meantime, using canonical mode might address this:

I tried turning on canonical mode and it does not resolve the issue.

>  See also jgm/pandoc#7172

Thanks! I've left a comment there as well.

**Comment by jjallaire** [comment]
This is indeed how pandoc writes lists (and we don't currently have any control over how this happens). See discussion here: https://github.com/jgm/pandoc/issues/7172 (and elsewhere in the pandoc repo where this has been requested). If pandoc creates an option for markdown output to eliminate the spacing we are more than happy to take advantage of it!
