### ISSUE TITLE
Missing value of attributes in Edit Attributes dialog at header after linked image in Visual mode.

### ISSUE THREAD

**Issue by niszet** [rstudio/rstudio#11018]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.06.0 Build 312 (also 2022.02.1+461)
    OS Version      :  Windows10
    R Version       :  4.1.3

### Steps to reproduce the problem
Open an R Markdown file (already exist, shown below) as a Visual mode.
Click the option bottun on the Visual mode view to modify the id and/or class of Header1.

### Describe the problem in detail
There are blank cells in  "Edit Attributes" dialog (even though values are set). No update even if I set the value to those cells.
The value of id and class are shown in Visual mode in glay round box. This issue is only in the "Edit Attributes".

Changing the level of Heading by tool bar on Visual Editor causes option bottun works correctly. (This is my temporary work around solution)
This might be caused by the image with link. Only link or image don't cause this issue in my environment.

Following is my smallest example for this issue.

```markdown
---
output: html_document
---

# Chapter1 {#chapter1 .chapter}

This Heading is OK.

[![](https://www.r-project.org/logo/Rlogo.png){width="230"}](https://www.r-project.org/logo/Rlogo.png)

# Chapter2 {#chapter2 .chapter}

This Heading is NG.

```

Screenshots are attached below. (2 screenshots are added after first note for adding explanation)

View on Visual mode is here. Both chapter's attributes (id, class) are shown.

![image](https://user-images.githubusercontent.com/28832585/164123190-098bf23c-6066-4168-bc8e-a8f8bb673290.png)

Here is an "Edit Attributes" dialog of Chapter1. This seems correctly.

![image](https://user-images.githubusercontent.com/28832585/164125010-75d57182-8e2e-409d-be38-d559cd9b3106.png)

Here is an "Edit Attributes" dialog of Chapter2. No values are set in ID and Classes boxes.

![image](https://user-images.githubusercontent.com/28832585/164125114-016e47d2-b802-417f-bd71-6aadc3a19f44.png)

### Describe the behavior you expected
Attributes are shown correctly and can be edit.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/rstudio/commit/287ab3ac36c7d4e88c8c591c2f62a2592f8faf86

**Comment by romainfrancois** [comment]
Verified in RStudio 2022.06.0-daily+373

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/2625526/167370794-6cd8c8a5-d8b1-4538-bd04-14ef3fd677f2.png">
