### ISSUE TITLE
Indent Rainbow coloring in Editor

### ISSUE THREAD

**Issue by cstepper** [rstudio/rstudio#11023]
Hi, 

I love to work with RStudio as it provides a lot of features, that I use in my daily coding.
However, especially when authoring longer (and nested) code, it is sometimes difficult to spot the right level you're currently working on. Similarily, it makes it hard to detect the location of missing parentheses.

The rainbow parenthesis helped here already. But what I like to ask:
Are there any plans to integrate some option similar to the Indent-Rainbow Extension for VSCode? https://github.com/oderwat/vscode-indent-rainbow

I regularly use this to structure my code.

Thanks for consideration.
Christoph

**Comment by kevinushey** [comment]
That is clever; I love it!

**Comment by SchmidtPaul** [comment]
Sorry but - when and how can I use this?

**Comment by kevinushey** [comment]
This feature is available in the daily builds of RStudio (under development; intended for testing): https://dailies.rstudio.com

![image](https://user-images.githubusercontent.com/1976582/187492639-a5f91e1b-64c8-43f9-ae78-acd0884c812f.png)
