### ISSUE TITLE
Build pane no longer shows Output/Issues after testing

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11026]
I am on a daily version of RStudio (2022.06.0 Build 314). The Build pane used to show `Output` and `Issues` panes after testing your package. The `Issues` pane was useful for quickly jumping to problematic tests. This seems to no longer show up:

Before:

<img width="857" alt="Screen Shot 2022-04-20 at 2 17 40 PM" src="https://user-images.githubusercontent.com/19150088/164298251-cbf11d4e-4441-41ca-84cb-4e9f0bbbbe49.png">
<img width="858" alt="Screen Shot 2022-04-20 at 2 17 51 PM" src="https://user-images.githubusercontent.com/19150088/164298252-9690d387-8c51-4ba7-8907-ef897975e6bc.png">

After:

<img width="835" alt="Screen Shot 2022-04-20 at 2 10 58 PM" src="https://user-images.githubusercontent.com/19150088/164298292-b389a96c-0fb7-4388-b259-9b2c5c1fd7a3.png">

CC @romainfrancois since we talked about this

**Comment by romainfrancois** [comment]
cc @DavisVaughan it's live with last spotted wakerobin build: https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/macos/

I think we can close this now.

**Comment by DavisVaughan** [comment]
I can confirm that the output/issues panes are working with CRAN testthat/cli (no hyperlinks) and dev testthat/cli (with hyperlinks)
