### ISSUE TITLE
RStudio IDE should check the user dictionary for word suggestions

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/rstudio#11036]
Hi,

When words that are not part of the default dictionary are added to the users dictionary, this stops the word from being flagged as incorrectly spelt, but it does not use these words as suggestions for spell check. Not sure if this is possible, but it would improve the spell check a lot but checking against the user dictionary for suggested words.

**Comment by ronblum** [comment]
@mattwarkentin Thank you for the suggestion! We'll review it as we continue development of RStudio.
