### ISSUE TITLE
Expose formatting utility used to convert markdown document to pandoc style markdown in visual mode

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/rstudio#11039]
I recently started using the visual mode of RStudio and by turnig this on, my active markdown document was formatted (apparently with pandoc). There are issues about this already, and I agree it's a feature rather than a bug: https://github.com/rstudio/rstudio/issues/7922. 
I even believe  the process or re-formatting would make sense a s stand-alone tool to format `.Rmd` and friends (like {styler} for pure R code), also as a [pre-commit hook](https://pre-commit.com/). I once build a very inclomplete R markdown formatter [here](https://github.com/lorenzwalthert/stylermd) that I am convinved now should leverage pandoc as a backend. I went ahead and tried to build the functionality myself: 
```
pandoc -s -f markdown+backtick_code_blocks+fenced_code_attributes -t markdown -o new-README.Rmd README.Rmd
```
But this does not get me all the way, as described in https://github.com/lorenzwalthert/stylermd/issues/19.

Hence, I was wondering if you are interested in:

* if it is trivial, share the pandoc command with me that you use so I can built a R markdown formatting tool myself.
* if it is non-trivial, making the functionality you use accessible somehow for third parties.

I belive that using such a formatting tool (e.g. as a pre-commit hooks) when working on R Markdown documents while switching between visual and source mode would also reduce unnecessary commit diff, e.g. when some people are working in one mode and others in the other. 

Another (independent) option worth exploring to reduce this friction between the modes is to add a setting in RStudio to allow `format markdown on save`, so the document is always in the pandoc compatible markdown style. I can open a separate issue for that if you want.

**Comment by ronblum** [comment]
@lorenzwalthert Thank you for the suggestions! I'll tag this for review as part of our ongoing development of RStudio.

**Comment by lorenzwalthert** [comment]
Bump please 😊

**Comment by lorenzwalthert** [comment]
Bump please.
