### ISSUE TITLE
use properly-cased name RStudio in rstudio.exe properties

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11035]
## Qt

<img width="380" alt="Screen Shot 2022-04-21 at 12 41 04 PM" src="https://user-images.githubusercontent.com/1976582/164540062-6b061343-e658-4d77-b1a6-6f33f4c61a72.png">

## Electron

<img width="380" alt="Screen Shot 2022-04-21 at 12 40 40 PM" src="https://user-images.githubusercontent.com/1976582/164539995-42e323d1-41e5-4244-b8bc-82b99d562c12.png">

- The "File description" and "Product name" should be "RStudio" rather than "rstudio". (need to use proper casing)

**Comment by kevinushey** [comment]
Also note that the Copyright is not correctly set.

**Comment by ronblum** [comment]
Verified that the file description, product name, and copyright are correct. Tested using RStudio Desktop 2022.06.0-daily+333 (Electron) on Windows 11.

However, the file version doesn't include the build number, so in this case it's `2022.06.0.0`. Should it be `2022.06.0.333` or is this correct?

**Comment by kevinushey** [comment]
Nice catch; we should probably include the right build number (or just exclude it here).

**Comment by gtritchie** [comment]
@ronblum Can we open a new issue to track the fact the file version is missing the build number? That seems better to track separately so we can close this issue. Also, I noticed this problem (file version not having build number) isn't unique to Electron, I see the same thing with Qt desktop builds.

**Comment by ronblum** [comment]
Issue #12205 filed!

Closing this issue as verified.
