### ISSUE TITLE
Figure not rendered in dev documentation (via `\figure{}{}`)

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#11033]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.02.0 Build 443
    OS Version      :  Archlinux 5.15.10-arch1-1
    R Version       :  4.1.2

### Steps to reproduce the problem

1. While developing an R package, create an roxygen2 block containing lines that use the `\figure{}{}` markup:

```
#' \if{html}{\figure{mapping_approach.svg}{Mapping approach}}
#' \if{latex}{\figure{mapping_approach.png}{options: width=0.5in}}
```

2. Now, document (`devtools::document()`) and load (`devtools::load_all(".")`) the package.

3. Open the development documentation for the object whose documentation included the `\figure{}{}` commands with `?r_object`.

4. The figure is not rendered.

5. If however we install and load (Shift+Ctrl+B) the package, now rendering the same help page correctly renders the figure.

I expected both methods to work fine and render the figure.

### Rendering development documentation
![dev_doc](https://user-images.githubusercontent.com/19862384/164468269-91ba4c33-22cc-4dfa-a21f-b9967856f532.png)

### Rendering installed documentation
![doc](https://user-images.githubusercontent.com/19862384/164468285-7d4c137b-f236-4b14-9402-8b21feefbac5.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hadley** [comment]
This is a known limitation that we've tried to fix in the past, but it's too much work.
