### ISSUE TITLE
RStudio Server request: automatically convert special characters in file name to URL-compatible format

### ISSUE THREAD

**Issue by malisas** [rstudio/rstudio#11045]
Sometimes I will be using RStudio Server, and I will generate a png which has the character `+` in the filename, for example:

`my+file.png`
If I click on it to open it up and view it in a new browser tab, I will get the message
`/files/path/to/my+file.png not found.`
In order to view it, I need to change the `+` in the URL string to `%2b`.

I was thinking it would be nice to have this sort of conversion occur automatically, if possible. Thanks!

(also posted [here](https://community.rstudio.com/t/rstudio-server-request-automatically-convert-special-characters-in-file-name-to-url-compatible-format/134975))

**Comment by ronblum** [comment]
@malisas Thank you for the suggestion! We'll review it as we continue development of RStudio.
