### ISSUE TITLE
Find in files: regexp replacements

### ISSUE THREAD

**Issue by ms609** [rstudio/rstudio#11041]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.1 Build 461
    OS Version      : Windows 10 64-bit
    R Version       : 4.2.0 RC

### Steps to reproduce the problem
Replace a regular expression match with a string

### Describe the problem in detail
- Launch Find in files dialog
- Select a regular expression search with a variable length match: e.g. `Foo\w*\W`
- Confirm that relevant matches are found in files
- Set "Replace with" to a string, e.g. `Bar `, and confirm replacement

### Describe the behavior you expected
- All occurrences of `Foo\w*\W` should be replaced with `Bar `.
- Instead, a dialog box threatens to replace all 42 instances, then replace results reports "42 successful, 0 failed": but no replacement is evident.  The preview intimates that the search hit is being replaced by itself, instead of the replacement text specified.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
I believe this has been fixed recently by @jgutman. Perhaps you can check on a recent daily build: https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/windows/

**Comment by ms609** [comment]
On the most recent RStudio 2022.06.0 Build 322, I see "Error: Parameter type mismatch" in a popup when entering replacement text.

**Comment by romainfrancois** [comment]
I can reproduce this: 

<img width="397" alt="image" src="https://user-images.githubusercontent.com/2625526/164726095-b2b24a59-cbbc-4de8-99f9-ddc45e896a3d.png">

**Comment by jgutman** [comment]
Not a true regression -- this was introduced in an earlier build of Spotted Wakerobin (#10594) and affects all regex find in files replacements.

**Comment by romainfrancois** [comment]
Verified with build `RStudio 2022.06.0-daily+361`
