### ISSUE TITLE
bring back option for installing package with / without preclean

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11047]
I'm realizing now why someone might not always want to `--preclean`: doing so implies cleaning up any created object files in the `src/` folder, and so that implies one would need to recompile everything whenever the package is re-installed, even if none of the source files in the `src/` folder have changed.

For a package with C++ sources, it seems reasonable to have separate menu options for doing an "incremental" rebuild and reinstall, versus a "full" rebuild and reinstall.

I think we should consider bringing back menu items (in the More menu?) for installing the package with / without preclean. (Not yet sure what that UI should look like.)

**Comment by kevinushey** [comment]
In addition, the "Test Package" and "Check Package" menu items are redundant now that they've been promoted to the "main" toolbar.

<img width="422" alt="Screen Shot 2022-04-22 at 12 27 39 PM" src="https://user-images.githubusercontent.com/1976582/164781403-97874116-3d36-4832-80cb-a64ec3040a09.png">

**Comment by romainfrancois** [comment]
Maybe we can have the "Clean before install" checkbox in the toolbar? before Install to control if "Install" does `--preclean`. 

Also perhaps the title should be more explicit: 

<img width="305" alt="image" src="https://user-images.githubusercontent.com/2625526/164883760-586c8994-a5ca-445a-888b-58b2461efb24.png">

**Comment by DavisVaughan** [comment]
There is still currently a way to `Install` without pre cleaning, right?

```
Tools -> Project Options -> Build tools -> Uncheck "Clean before install"
```

That makes the `Install` button not preclean for me. Can you help me understand why we need more UI than that?

**Comment by DavisVaughan** [comment]
Also, I actually didn't notice that preclean is that painful for me, since I use ccache. Since the sources haven't changed at all, the recompilation is essentially instant since they are cached (even for clock, which can take a while to compile normally). I realize not everyone uses that though.

**Comment by romainfrancois** [comment]
I don't but things are fast enough on my machine, so I guess that's why I haven't noticed either.

**Comment by kevinushey** [comment]
> Can you help me understand why we need more UI than that?

Because that is far too many clicks to change a single preference; IMHO it's easy to imagine a user wanting to perform both clean and incremental builds in a project (e.g. because you changed compiler options in a way that RStudio / R didn't see and so you need a one-time clean rebuild of everything; and then incremental rebuilds as you change individual source files)

> Also, I actually didn't notice that preclean is that painful for me, since I use ccache

Right, but the average user does not use ccache and we need to make sure we're not compromising the user experience for non-advanced users.

> I don't but things are fast enough on my machine, so I guess that's why I haven't noticed either.

IMHO one notices the effects very quickly on any project containing C++ code since preclean by default implies rebuilding all C++ source files on every install (even the ones you didn't touch)

**Comment by romainfrancois** [comment]
🤔 probably needs a follow up, the (no preclean) button has disappeared: 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/2625526/167505165-ab864c23-496c-4bbc-b3b9-f3ed554071cf.png">

**Comment by romainfrancois** [comment]
QA notes: 

When this checkbox is checked: 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/2625526/167577948-04da582b-9d83-464f-a491-30ae4518d6ec.png">

The "Install" button should mention `--preclean`: 

<img width="325" alt="image" src="https://user-images.githubusercontent.com/2625526/167578042-8b0bbf6c-5caa-4d58-a930-08c3e1f9bc85.png">

unchecking the checkbox will update the tooltip: 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/2625526/167578237-6e61e084-6a7b-4cfd-b405-c8e197099113.png">

The other buttons are not governed by the checkbox: 

<img width="508" alt="image" src="https://user-images.githubusercontent.com/2625526/167578360-c65104a4-1ea1-4942-93d4-b7a85ac880d3.png">

<img width="457" alt="image" src="https://user-images.githubusercontent.com/2625526/167578392-c210e23b-85e8-4e9c-9d31-c6aa6caa12ea.png">

**Comment by jgutman** [comment]
Verified in RStudio Desktop 2022.6.0.388 using Mac OS 12.3
