### ISSUE TITLE
More comment keyword styling (e.g. # TODO, # FIXME)

### ISSUE THREAD

**Issue by karlmakepeace** [rstudio/rstudio#11053]
Add more comment keywords immediately following comment character(s) (e.g. "# KEYWORD" ) to syntax highlighting/styling.

https://github.com/rstudio/rstudio/blob/295d51d5adc623a7c44d3647bab0dd39926758e1/src/gwt/acesupport/acemode/r_highlight_rules.js#L242

https://github.com/rstudio/rstudio/blob/295d51d5adc623a7c44d3647bab0dd39926758e1/src/gwt/acesupport/acemode/r_highlight_rules.js#L254

To start: in addition to "TODO" and "FIXME" add the [TODOr](https://github.com/dokato/todor) package defaults ([FIXME, TODO, CHANGED, IDEA, HACK, NOTE, REVIEW, BUG, QUESTION, COMBAK, TEMP](https://github.com/dokato/todor#what-can-it-detect)).

Perhaps allow different colors for different keywords (e.g. "TODO" can be a different color than "NOTE").

Perhaps give the user the ability to define custom keywords and assign colors+styling (Foreground/Background/Emphasis/Italic/Underline) through Global Options > Code or > Appearance.

**Comment by jzadra** [comment]
+1

Is there a way to do this manually for now other than editing and compiling the source?  Is the regex exposed after install?

**Comment by romainfrancois** [comment]
Maybe comments starting with a word all upper case can get the style. Now `TODO` and `FIXME` get the styles `["comment", "comment.keyword.operator", "comment"]` which makes: 

![image](https://user-images.githubusercontent.com/2625526/177197441-abba5b83-d34b-42d3-a73d-67fdde31c0aa.png)

Maybe they could get additional styles, e.g. 

![image](https://user-images.githubusercontent.com/2625526/177197535-1ac203e2-4e61-4d11-9260-537cdaffbb2f.png)

that could be themed. 

I'm not sure if `"comment.keyword.operator"` has purpose, or if this is just to get the styles. At the end of the day, the `ace_operator` style is applied: 

![image](https://user-images.githubusercontent.com/2625526/177197756-32364e65-e76b-425c-8432-1c7f2d30950d.png)

Perhaps a dedicated style would be more useful. Maybe to show it in the outline ? Or have the ability to search for those in fuzzy finder ?

**Comment by jzadra** [comment]
I think that highlighting anything matching regex `#[A-Z]{2,}` would be a great solution. It's much more flexible than adding a few additional specific keywords.

**Comment by jzadra** [comment]
Still hoping for this feature!

**Comment by karlmakepeace** [comment]
> Still hoping for this feature!

Likewise.

**Comment by garthmortensen** [comment]
+1

**Comment by aoustrich** [comment]
@romainfrancois I'm not super experienced with HTML/CSS... do those examples you gave [here](https://github.com/rstudio/rstudio/issues/11053#issuecomment-1174023319) work or were they suggestions of how to add different color comments? If that is a solution, could you explain how to implement those changes?

**Comment by luisvalenzuelar** [comment]
At minimum, user should be able to enable line highlighting for TODO or FIXME, as done in other software. Different color is NOT enough. And, all TODOs should show up at the bottom of outline.
