### ISSUE TITLE
The View() function for vectors in RStudio does not display the data correctly

### ISSUE THREAD

**Issue by pprevos** [rstudio/rstudio#11050]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.0 Build 443  
    OS Version      :  Arch Linux
    R Version       :  4.2.0

### Steps to reproduce the problem
`View(mtcars$mpg)`

### Describe the problem in detail
Using the `View()` function on a vector shows it horizontally instead of vertically. When calling `View(as.data.frame(mtcars$mpg))` it gives the desired behaviour. This problem does not occur when using R in the console.

### Describe the behavior you expected
Display the data as a data frame.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [-] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Klorane** [comment]
If I got it right, you are essentially trying to print a column vector. An option would be

```
write.csv(mtcars$mpg, row.names = F)
```

where `row.names`  indicates whether the row names of x have to be written along with x.

**Comment by pprevos** [comment]
The help file for `View()`  states that it coerces a data frame, but it doesn't do this when asking it to display a vector. It has nothing to do with writing a CSV file. The workaround `View(as.data.frame(mtcars$mpg))` does the job, but the function should do the coercing, not the user.

**Comment by ronblum** [comment]
@pprevos Thank you for raising this! It looks like originally the vector was shown this way, but it changed in RStudio 1.4.1103. I'll mark this as a bug to review.
