### ISSUE TITLE
shortcut for global zoom (GUI zoom) mapped but not shown (anywhere ?)

### ISSUE THREAD

**Issue by playmobilmeister** [rstudio/rstudio#11052]
Background: This is really a minor issue but I think fixing it could greatly help newbies with the GUI. It happened when I expanded my desktop to another screen and then couldn't read the GUI's text on the smaller screen. I could not find the keyboard shortcut for zooming in the entire GUI (as in enlarging the zoom level under Global Options > Appearance > Zoom % ). I admit I should have guessed it would be Ctrl + '+', but at the time I wasn't thinking clearly...I went looking for the shortcut everywhere, only to find it finally here, described in one of the closed issues.

### System details

    RStudio Edition : desktop
    RStudio Version : RStudio 2022.02.1+461 
    OS Version      : Windows 10 x64 (build 19044)
    R Version       :  4.1.1

### Steps to reproduce the problem
tools > Modify keyboard shortcuts, then "see all shortcuts", then search for zoom
### Problem in detail
the shortcuts for global zoom (Ctrl+ '+' | Ctrl + '-') work, but they don't appear in the searchable shortcut window.
![image](https://user-images.githubusercontent.com/33288162/164988083-e7edb7d6-810d-4851-8b81-e973aa93ed9d.png)They also don't appear in the
-  Alt+Shift+K splash screen, and in the 
- [keyboard shortcut local help file](file:///C:/Program%20Files/RStudio/www/docs/keyboard.htm)
(file:///C:/Program%20Files/RStudio/www/docs/keyboard.htm)
###  Behavior expected
I expected to be able to figure this shortcut out by one of the above three methods

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@AmirrTAU Thank you for raising this! 
1) The shortcuts are available in the `View` menu. This is from MacOS, but the location it's the same as Windows, except for `Cmd` instead of `Ctrl`:
<img width="225" alt="view" src="https://user-images.githubusercontent.com/31009952/165582007-93438548-bb36-4043-820f-a604e61dc97a.png">

2) They should be showing up in "Modify Keyboard Shortcuts." I can confirm that they do show up in MacOS 12.4, but not in Windows 11. So I'm marking this as a bug for that.

**Comment by AmirrTAU** [comment]
> @AmirrTAU Thank you for raising this!
> 
>     1. The shortcuts are available in the `View` menu. This is from MacOS, but the location it's the same as Windows, except for `Cmd` instead of `Ctrl`:
> 
> 
> <img alt="view" width="225" src="https://user-images.githubusercontent.com/31009952/165582007-93438548-bb36-4043-820f-a604e61dc97a.png">
> 
>     2. They should be showing up in "Modify Keyboard Shortcuts." I can confirm that they do show up in MacOS 12.4, but not in Windows 11. So I'm marking this as a bug for that.

Oh my, I feel even more stupid now 😃:
![image](https://user-images.githubusercontent.com/33288162/165699369-5a2d8e4e-8f6b-4f85-a1d5-a70e17b8a0b5.png)

**Comment by ronblum** [comment]
@AmirrTAU No worries, and there was nothing stupid—I often have to remind myself where shortcuts are shown. And you made a very good find about them not included in the "Modify Keyboard Shortcuts" list, so this was definitely worth it!
