### ISSUE TITLE
"Choose R" dialog box has no text

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11079]
![image](https://user-images.githubusercontent.com/1976582/165622321-1c580aa0-c407-4219-be82-68652ba022f1.png)

Observed with RStudio 2022.06.0-daily+333 "Spotted Wakerobin" Daily (222a55f07242ae455bf0a79b44d4ff729a346568, 2022-04-26) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.06.0-daily+333 Chrome/100.0.4896.127 Electron/18.1.0 Safari/537.36.

**Comment by gtritchie** [comment]
Started with Electron build 328.

**Comment by matheustavaresdev** [comment]
Was able to find the root cause of the issue. Trying to deploy a fix

**Comment by gtritchie** [comment]
With build 2022.06.0-daily+343 on Windows-11, I still see the window without text for several seconds, then the text appears. This is with the language set to English.

It isn't too bad when I view it at startup by holding down Ctrl, but when opened via Tools / Global Options / Change... it displays without text far too long.

**Comment by ronblum** [comment]
### Verified Fixed
    RStudio Edition    :  Desktop
    RStudio Version(s) : 2022.06.0-daily+374
    OS Version         : Windows 11

### Environment details
 
N/A

### Test scenario(s) 

Verified when
1. Starting up and holding on <kbd>Ctrl</kbd> key till menu pops up.
2. Choosing with RStudio Desktop at <kbd>Tools -> Global Options -> Basic -> R Version</kbd>.

Confirmed that 
1. Text appears correctly.
2. Selection are applied.

### Automated tests 

N/A
