### ISSUE TITLE
Keyboard shortcuts containing Shift or Enter don't display in menu in French (Desktop)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11073]
### System details

    RStudio Edition : Desktop (Qt or Electron)
    RStudio Version : 2022.06.0-daily+332
    OS Version      : All
    R Version       : Any

### Steps to reproduce the problem

- Switch the IDE to French UI (Global Options / General / Advanced) and exit
- Run IDE from a terminal/command-prompt
- With Electron, you get a series of warnings (about 39 of them, all the same)

```
[99857:0426/162111.533268:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
...
[99857:0426/162152.021056:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
```
- With Qt, no such warnings

### Describe the problem in detail

- The problem is with shortcuts whose modifier keys or special keys have been localized, e.g. containing <kbd>Shift</kbd> or <kbd>Enter</kbd>
- Also applies to shortcuts containing "Left", "Right", "Up", "Down", "PgUp", "PgDn", "Tab", or "Backspace" (none of the default shortcuts use these, but a user can assign them)

A couple representative examples (in English):

- Help / Keyboard Shortcuts Help (Alt+Shift+K)
- View / Move Focus to Terminal (Alt+Shift+M)
- Code / Terminal / Send to Terminal (Cmd+Alt+Enter)

### Describe the behavior you expected

- No warnings, and shortcuts should show correctly in both French and English

Reference: PR that added localization of shortcuts: https://github.com/rstudio/rstudio/pull/10372

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
I don't know how to approach this one. I can confirm the problem.

**Comment by gtritchie** [comment]
Reference: https://github.com/rstudio/rstudio/pull/10372

**Comment by romainfrancois** [comment]
Confirmed with RStudio 2022.06.0-daily+391
