### ISSUE TITLE
File -> Open File should use current project folder as starting folder

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11088]
On Windows Electron, the starting directory when entering the File > Open File dialog should default to the current working directory. If a user has recently opened a file, the starting directory should be the last used directory (from the last time File > Open File was used). However, this should reset back to the default (WD) if working directory is changed, or if a new project is opened/closed (thereby changing the working directory)

**Comment by ronblum** [comment]
@kevinushey Did you by chance open a file in the home directory while in a project? What I'm seeing is that Open File is always using the directory from which a file was last opened. So if I'm in one project, open a file in it, and then switch or close projects, Open File still uses the previous project directory. Which is a bug.

**Comment by jgutman** [comment]
See also #11778

**Comment by kevinushey** [comment]
Hmm... Here's another piece of the puzzle? I think the starting directory ultimately depends on the R session's working directory, which I didn't capture in my initial report.

On macOS, the starting directory used by the system dialog in File -> Open File seems to depend on the R session's working directory. If I'm working in a project, but run `setwd("~")`, then File -> Open File uses the home directory. This is true for both Electron and Qt builds.

However, it seems like this doesn't occur in the Electron builds of RStudio on Windows -- there, the project directory is always used.

**Comment by kevinushey** [comment]
It also seems like (if the working directory is not changed) then the last-used directory in the File -> Open File dialog is preserved on future file open attempts (which seems okay). Note that opening files via e.g. the Files pane in RStudio doesn't affect that behavior / state though.

**Comment by jgutman** [comment]
See revised description. On windows the last used working directory also seems to persist between sessions, which doesn't seem to be the case on Mac.

**Comment by billdenney** [comment]
I am a "me too" on this issue.

One thing that I don't see in the list is when multiple sessions are open, the File > Open directory seems to be shared between all sessions (which I would not prefer).  I like the way that it used to work which I will try to describe below.  I'm going to use the words "working directory" to mean what is shown with "File > Open" or "File > Save As...".

* Starting working directory is the same as the R session directory.  If you open a file by double-clicking from explorer, it is the directory of that file.
* Each session tracks its own working directory.
* `setwd()` in R changes the working directory.
* Manually moving to a new directory (I open a file from "c:\tmp" while I'm doing most of my work in "c:\mywork") changes the working directory without changing R's `setwd()`.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+270
windows 11

Files all opened in correct directory. Initially from the working directory, and then from the most recently used.  New projects open correctly in the new project directory.
