### ISSUE TITLE
Document outline for test scripts

### ISSUE THREAD

**Issue by maelle** [rstudio/rstudio#11082]
In package projects, for test files under `tests/testthat`, it might be nice if the document outline / table of contents treated the `test_that()` call as headers, so one could easily navigate from one test to the other, or see at a glance all the test names in a test file.

E.g.

```r
test_that("bla() works", {})

test_that("bla() errors well", {})

test_that("bla() when blop not installed", {})

```

would generate an outline to go directly to "bla() works"/"bla() errors well"/"bla() when blop not installed".

**Comment by kevinushey** [comment]
FYI for @romainfrancois: you probably want to start looking around in https://github.com/rstudio/rstudio/blob/4ccbd3e18b485a8633536971accc2618bcb34a49/src/gwt/acesupport/acemode/r_code_model.js#L736. (The function is unfortunately kind of a long mess, but that's where the scope tree structure is built)

**Comment by romainfrancois** [comment]
Not exactly this request, but perhaps `test_that()` calls can be source items so that e.g. fuzzy finder recognizes them.

**Comment by romainfrancois** [comment]
QA: in a package that has unit tests, the outline should show them: 

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/2625526/167243874-a0f4b1c8-eab2-4652-9d2d-beca89e14945.png">

<img width="754" alt="image" src="https://user-images.githubusercontent.com/2625526/167243892-ea2e95ee-03aa-40d8-a9ba-66b0455aa9f4.png">

Also, the fuzzy finder indexes them if the search term starts with "t ": 

<img width="866" alt="image" src="https://user-images.githubusercontent.com/2625526/167243914-46f7d958-43c5-46b0-a567-6874ad9826f0.png">

**Comment by jgutman** [comment]
Great feature! Thanks for the suggestion.

**Comment by maelle** [comment]
Thanks @romainfrancois @kevinushey @jgutman :tada:
