### ISSUE TITLE
Avoid using empty directory for "Create project as subdirectory of:" text box

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11089]
I saw this in the New Project Wizard:

![image](https://user-images.githubusercontent.com/1976582/165847793-7ac0d295-cb16-4686-abdb-885336da9016.png)

We should default to displaying the user's home directory (`~`).

**Comment by gtritchie** [comment]
I could not repro this on daily 2022.06.0-daily+356 on Windows or Mac, but did repro on Ubuntu 22.

**Comment by kevinushey** [comment]
Relevant code is probably here:

https://github.com/rstudio/rstudio/blob/c260961b0576f90980fe5bc6e2e7e01a72f7584a/src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java#L244-L254

I think this implies that the "default project dir" is unexpectedly empty?

https://github.com/rstudio/rstudio/blob/c260961b0576f90980fe5bc6e2e7e01a72f7584a/src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java#L251

**Comment by jgutman** [comment]
I repro'd this on 2022.10.0-daily+51 Mac OS 12.4 as well

**Comment by jgutman** [comment]
Documents is actually the home directory on Windows -- you can check by looking at `Sys.getenv("HOME")` which is usually set to Users/<user>/Documents. More concerning is the fact that you say ~ doesn't resolve. Can you provide more details/screenshots? Or was your concern that it was just resolving to the Documents directory? It's not clear from your comment

**Comment by jgutman** [comment]
I'm not seeing the issue @jonvanausdeln mentioned; however, I notice that when Open Project in new session is unchecked, it correctly opens the project (testing with cloning https://github.com/tidyverse/dplyr into ~; opens as `~/dplyr`). However, when I check Open Project in new session, it doesn't actually open the project. It just opens a new session with no active project. This might be a totally separate issu

**Comment by jonvanausdeln** [comment]
@jgutman, you are correct, I was unclear in my initial comment.  I was just mentioning that the 'home' default was resolving to "Documents".  But I'm okay with leaving it if that's what it's been before.
