### ISSUE TITLE
R raw character constants syntax is not being recognized by R Notebook editor

### ISSUE THREAD

**Issue by GitHunter0** [rstudio/rstudio#11087]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.02.2 Build 485
    OS Version      :  Windows 10
    R Version       :  4.1.1

### Steps to reproduce the problem
Type the code below in an R Notebook:
````
```{r}
x = r"--[  quotes "  ]--"

print(x)
```

```{r}
y = r"--[  brackets and quotes ]"  ]--"

print(y)
```

```{r}
z = "This is not recognized as an R chunk"
```

````

### Describe the problem in detail
As it can be seen in the picture below, R raw character constants syntax is not being recognized by Rstudio.
It understands that `]"` is closing the raw string when what is actually closing it is `]--"`.
Due to this, the chunk with `z`, for example, cannot be run because it is not being recognized as a chunk.
`print(y)` and `z` are in white color, showing that RStudio R Notebook editor did not understand the raw string syntax.

![image](https://user-images.githubusercontent.com/26294221/165845671-9976e88b-e6f3-4279-b4bc-df7af4685541.png)

### Describe the behavior you expected
The editor should understand all kinds of raw strings syntax introduced in R 4.0

Thank you

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I was able to reproduce this locally as well. It looks like the token sequence `]"` is incorrectly terminating the raw string.

The terminal rule here likely needs to be tweaked: https://github.com/rstudio/rstudio/blob/5072281d60d27f46071eee0ff04ca2081528c897/src/gwt/acesupport/acemode/r_highlight_rules.js#L473-L491

**Comment by ronblum** [comment]
@kevinushey FWIW, it works correctly in the visual editor.

**Comment by kevinushey** [comment]
Thanks for verifying! Indeed, I would expect this issue only to manifest in R Markdown documents in source mode.

**Comment by romainfrancois** [comment]
Verified in RStudio 2022.06.0-daily+385
