### ISSUE TITLE
Quarto document won't preview in window

### ISSUE THREAD

**Issue by ailich** [rstudio/rstudio#11096]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.06.0-daily+342
    OS Version      :  Windows 10
    R Version       :  4.0.4

### What I did
Created a new quarto document, clicked the gear button next to render, set it to "Preview in Window", and then clicked "Render"

### What happened
The document rendered in the viewer window

### What I expected to happen
The document to render in a separate pop out window

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@romainfrancois is this ready to be merged?

**Comment by romainfrancois** [comment]
QA notes: see https://github.com/rstudio/rstudio/pull/11178#issuecomment-1136732115

**Comment by jgutman** [comment]
Verified in RStudio Desktop 2022.6.0.454 on Windows Server 2019.

1. First setting is Preview in Viewer Pane. Press Render: Doc renders in viewer pane.
2. Change setting to Preview in Window. Press Render: New browser window opens and doc renders in window.
3. Change doc, keep setting as Preview in Window. Press Render: No new browser window; document is re-rendered in existing browser window
