### ISSUE TITLE
Syntax highlighting breaks with specific code (yet ok with knitr)

### ISSUE THREAD

**Issue by AMChalkie** [rstudio/rstudio#11093]
### System details

© 2009-2022 RStudio, PBC
"Prairie Trillium" Release (8acbd38b, 2022-04-19) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

    RStudio Edition : Desktop
    RStudio Version : 2022.02.2 Build 485
    OS Version      : OSX 12.3.1 (21E258)
    R Version       : R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"

### Steps to reproduce the problem

- View enclosed Rmd file in RStudio.
- Notice syntax highlighting failure.

### Describe the problem in detail

The code outline, including sections and subsections fails  after this piece of code
Syntax highlighting fails after this code.

### Describe the behavior you expected

Code outline to be normal.
Syntax highlighting to be normal.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by AMChalkie** [comment]
[test_rstudio_markdown.Rmd.txt](https://github.com/rstudio/rstudio/files/8587711/test_rstudio_markdown.Rmd.txt)
[test_rstudio_markdown.Rmd.zip](https://github.com/rstudio/rstudio/files/8587712/test_rstudio_markdown.Rmd.zip)

**Comment by kevinushey** [comment]
Your lines of code are too long. Consider placing each matrix row / column on its own line in the document.
