### ISSUE TITLE
system file dialogs are displayed behind RStudio main window when opened

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11100]
Seen on Fedora 35. Also seen on Ubuntu 22 (haven't tried any other Linux distros).

For example, File / New Project / New Directory / New Project, then click on the Browse button next to "Create project as subdirectory of":

![image](https://user-images.githubusercontent.com/1976582/166089338-3ba91e72-c2d4-4870-b0b4-361a48483eb2.png)

Note the file dialog on the left-hand side displayed behind the main window. We should bring the window to the front + into focus after it's displayed.

**Comment by matheustavaresdev** [comment]
This is an Electron issue and is being tracked by https://github.com/electron/electron/issues/32857 . This needs to be fixed before our task can be closed, but this should be automatically fixed as soon as Electron issues a version update on NPM with that fix.

**Comment by mikebessuille** [comment]
Moving to Elsbeth - we are awaiting an electron fix, but that's not urgent for the preview due to Gary's workaround listed above.

**Comment by matheustavaresdev** [comment]
https://github.com/electron/electron/issues/32857#issuecomment-1150935043 - Electron team know why this is happening but dont know how to solve. Might take a while until it's fixed. An alternative seems to be changing every file browse dialog into `<input type="file">` but this could be very time consuming.

**Comment by timtmok** [comment]
There is progress upstream! We may have a fix to consume in the next electron release if all goes well with the PR that's currently open.

**Comment by timtmok** [comment]
Looks like that PR stalled and a different approach is currently under investigation.

**Comment by mikebessuille** [comment]
By the end of Aug 2022, if we don't have an Electron fix, we should switch the IDE to using web dialogs by default on linux (at least, for a specific set of Ubuntu versions?)

**Comment by mikebessuille** [comment]
@timtmok is this in Electron yet? If not, I think we should move ahead now with our plan to use web dialogs by default on Linux - Has that already been done?  I'd like to close this ticket.

**Comment by timtmok** [comment]
I'll take it on

**Comment by timtmok** [comment]
I've merged a change to use web dialogs by default on Linux. Mac and Windows will use native dialogs by default.

It might be a while before there's a build since there's a lack of Windows build agents and it's holding up the entire pipeline. Daily 186 or greater should have the change.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+215
Windows 11, Ubuntu 22.04

Tested several types of projects and other paths to get file selection dialogs. All work as expected.
