### ISSUE TITLE
Inserting code chunk in at bottom of visual editor navigates to footnote

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#11104]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 343
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. Create a new markdown document that contains the following markdown2. 

    ```md
    Paragraph 1
    
    Paragraph 2[^1]
    
    [^1]: This is a footnote
    
    Paragraph 3
    ```

2. Switch to the visual editor and move the cursor to the bottom of the document and press enter to start a new line. 

3. Press `Cmd + shift + I` to create a code chunk

### Describe the problem in detail

The code chunk is created, but the cursor focus is moved to the footnote text.

### Describe the behavior you expected

The cursor focus should be in the code chunk

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: Reproduced in RStudio Desktop 1.4.1717, as well.

**Comment by hadley** [comment]
Ooops yes, sorry. My fingers know it; my brain doesn't.

**Comment by jjallaire** [comment]
Addressed here: https://github.com/rstudio/rstudio/commit/7f2e1e16c751298ac0e1599160786a0f110eedc6

**Comment by romainfrancois** [comment]
Verified in: RStudio 2022.06.0-daily+373

<img width="873" alt="image" src="https://user-images.githubusercontent.com/2625526/167370072-7291923d-5e15-4a7c-b9a7-31760d41ec4a.png">
