### ISSUE TITLE
Visual editor should also spellcheck words in comments

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#11109]
1. Create a new RMarkdown document containing the following text2. 

    ````
    exaple
    
    ```{r}
    # exaple
    ```
    ````
2. Switch to the visual editor mode

<img width="736" alt="Screen Shot 2022-05-03 at 08 04 27" src="https://user-images.githubusercontent.com/4196/166458055-ebc4e10c-7bfc-4847-85cc-9083ea36ce62.png">

Only the spelling mistake in the text, not the code comment, is highlighted.

**Comment by ronblum** [comment]
Note: 
- This applies both to realtime spellchecking and <kbd>Edit -> Check Spelling</kbd>
- Reproducible in RStudio Desktop 1.4.1717 and 2022.06.0-daily-341 on MacOS 12.4
