### ISSUE TITLE
Strange behavior of the build pane when compiling Rcpp (Windows)

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#11106]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09
    OS Version      : Windows 10
    R Version       : 4..1.2

### Describe the problem in detail

Hello,

I launched the built of a package including some Rcpp code this morning. Now it is 20H00 and the built is still running in RStudio, more precisely this is the C++ compilation which is still running, with screens and screens of warnings, but very slow. However I just took a look at the installed package folder and I can see that the package has been installed this morning! Do you understand this behavior? If the package is installed, what is running in RStudio? Is there a "shift" between the real compilation and the apperance of the warnings in the pane? Can I kill the process? (I'd like to progress on my package ^^)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Most likely, RStudio is hanging while trying to render all of the test into the Build pane. There was an effort to virtualize output in the Build pane, but unfortunately we didn't make it over the finish line.

**Comment by stla** [comment]
Ok thanks. Now I'm using `devtools::install` in a terminal.

**Comment by ronblum** [comment]
@stla Would you be able to provide a minimal example of running into the problem? I'm not able to reproduce, so an example would help me go through the same steps you're going through. Thanks!

**Comment by stla** [comment]
Is it ok like this? As you can see, RStudio is running the compilation, but when I go to the library folder, the DLL is already there.

![eigenr](https://user-images.githubusercontent.com/4466543/168752449-6ada414e-4ed2-4a07-aec8-4a246f38dd54.gif)

**Comment by kevinushey** [comment]
My guess is that the IDE itself is now frozen, from the deluge of output within the Build pane. So what you're seeing is the IDE hanging while attempting to render all of the text into the Build pane.

There is one thing you could do to help -- you could add the following to your package's `src/Makevars.win` file.

```
PKG_CXXFLAGS = -Wno-ignored-attributes
```

That will tell the compiler to not warn about the potentially unused attributes in the Eigen headers.

**Comment by stla** [comment]
Thanks, that seems to work. I just have to not forget to remove that for the CRAN submission;
