### ISSUE TITLE
Change behavior of Alt+Left and Alt+Right navigation keys

### ISSUE THREAD

**Issue by jassler** [rstudio/rstudio#11105]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.2+485
    OS Version      :  Windows 10 and MacOS 12.3.1
    R Version       :  4.2

### Steps to reproduce the problem

Open or create any file with some text separated by spaces, i.e.:

```
Some short words to demo navigation
```

Place the text cursor somewhere and use the Alt+Left and Alt+Right keys to navigate word for word (Option+Left and Option+Right on Mac).

### Describe the problem in detail

From the text example above, if the text cursor is at the very beginning, using Alt+Right first skips the word `Some`, then the space between `Some` and `short`, then `short`, then the space between `short` and `words`, etc. (see video below). Comparing this shortcut to most other applications, this feels slow and sluggish.

https://user-images.githubusercontent.com/24298790/166290263-ada6a008-c709-4cdd-bd46-78254c669213.mp4

### Describe the behavior you expected

Using Alt+Right or Alt+Left, I expect the text cursor to skip all spaces *and* the next word. Notice in the video below that, using Alt+Right, the cursor always ends at the end of the next word, whereas with Alt+Left the cursor always ends at the beginning of the previous word.

https://user-images.githubusercontent.com/24298790/166291222-b6753706-0064-4cda-8d66-aa54751df80a.mp4

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jassler Thank you for filing this issue separately!

Another comparison point: PyCharm also follows the pattern of the other applications (under "Describe the behavior you expected").
