### ISSUE TITLE
Pasting fails and clears out the clipboard (Electron)

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11111]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily-322 & 348
    OS Version      : Red Hat 8.5, Ubuntu 20.04.4
    R Version       : 4.0.3, 4.1.3

### Steps to reproduce the problem

Using RStudio Desktop (Electron) on a Linux OS:
1. Copy text from outside of RStudio Desktop (Electron), so that we can rule out copying from RStudio as a factor. For example, copy the word "Congratulations" at the top of https://hmpg.net/
2. In RStudio Desktop, open an R Script or click in the Console.
3. Paste with <kbd>Ctrl-V</kbd>.
    - The word will be pasted, e.g. "Congratulations".
4. Paste again with <kbd>Ctrl-V</kbd>.
    - Nothing is pasted.
5. Switch back to a different application that will accept pasting text, such as in the address bar of a web browser.
7. Paste, presumably with <kbd>Ctrl-V</kbd>.
    - Nothing is pasted.
8. Copy text from somewhere, e.g. again "Congratulations" at the top of https://hmpg.net/
9. In RStudio Desktop, open an R Markdown file.
10. Switch to visual mode.
11. Paste with <kbd>Ctrl-V</kbd> multiple times.
    - The word is pasted multiple times, e.g. `CongratulationsCongratulationsCongratulationsCongratulationsCongratulations`
12. Switch to source mode.
13. Paste with <kbd>Ctrl-V</kbd> multiple times.
    - Nothing is pasted.

### Describe the problem in detail

Except with a markdown file in visual mode, pasting will either only happen the first time (R Script or Console) or not at all (R Markdown in source mode). The clipboard is emptied, so that the former contents can no longer be pasted in other applications, either.

### Describe the behavior you expected

Each paste attempt should result in a paste, and pasting shouldn’t clear the clipboard.

Compare:
* R Markdown in visual mode, in which pasting occurs.
* Qt version of RStudio Desktop.
* RStudio Desktop on MacOS 12.4.
* RStudio Server.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gsgxnet** [comment]
With the electron build 
`RStudio 2022.06.0-daily+482 "Spotted Wakerobin" Daily (8bce7fe783461a4b52405b3d0f406bbc91183abe, 2022-06-06) for OpenSUSE 15
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.06.0-daily+482 Chrome/102.0.5005.63 Electron/19.0.3 Safari/537.36` running on openSUSE Tumbleweed (rolling release, updated last week), KDE desktop, I do have the same / similar problem as described here. 

No cut/copy - paste in markdown.

**Comment by gsgxnet** [comment]
To further pinpoint the problem, I went back in several iterations to the **Electron** 287 build. All times same story, no copy/cut - paste.  
So i gave up, went for the most current **Qt** build, 483. In that version the clipboard works as expected.

**Comment by matheustavaresdev** [comment]
I'm currently working on that @gsgxnet ! Will let you know as soon as it's fixed. 😄

**Comment by matheustavaresdev** [comment]
Tested with `GWT` folder from fabfe8a8e605e4d5897e541954d7732fb30f8402 and copying / pasting works normally with the current `Electron` folder from latest `main`. This is actually a GWT issue. Could either of you @kevinushey or @timtmok help on this?

**Comment by matheustavaresdev** [comment]
This feature broke on this specific commit: https://github.com/rstudio/rstudio/commit/dc7f9e161b1b1fb0276de629b41ccd2c22781720

**Comment by gsgxnet** [comment]
> This feature broke on this specific commit: [dc7f9e1](https://github.com/rstudio/rstudio/commit/dc7f9e161b1b1fb0276de629b41ccd2c22781720)

Well understandable, with so many changes ref clipboard there. From what I remember over the various dailies I had tested in the last few month, there showed up a clipboard quirk some time ago, but not as badly as it is now. I could not pinpoint that early one, so I did not open an issue for it. 

Linux specific is this special double clipboard system. One contains all times the last selection and the other one works as a real clipboard as known in Mac OS and Windows. On one of my Linux systems I had configured under what circumstances ever the copy/pasting to/from clipboard wrong. 
It was wrong in a way, that when I did first a copy of text to the "real clipboard" and later on a selection of some other text, the "standard" paste always pasts the contents from the selection clipboard and not from the real one! 
And I was unable to locate the setting which causes this ugly config.  

The selection clipboard is a desktop / XWindows feature I never found a good use for. If I could totally disable that I would do it immediately.  

(Sorry for the rant .... needed that)

**Comment by kevinushey** [comment]
Thanks for the diagnosis @gsgxnet -- this looks like a think-o since we do correctly set the 'selection' clipboard bit here:

https://github.com/rstudio/rstudio/commit/dc7f9e161b1b1fb0276de629b41ccd2c22781720#diff-023a78f7325792dc7649f425105c3a9220631f1f983f735d5faa0b4748c4a027R280

So presumedly this was an accidental oversight on my part. Sorry!

**Comment by ronblum** [comment]
Verified that copying and pasting works correctly in RStudio Desktop 2022.06.0-daily_530. Tested using the steps in the original post, for both keyboard shortcuts and right-clicking with the mouse.
