### ISSUE TITLE
Text in usage section of help is not wrapped

### ISSUE THREAD

**Issue by frederikziebell** [rstudio/rstudio#11117]
### System details

    RStudio Edition: Desktop
    RStudio Version:  2022.02.2 Build 485
    OS Version: Mac OS 12.2.1
    R Version:  4.2.0

### Steps to reproduce the problem
Run `?limma::lmFit`.

### Describe the problem in detail
Text is not wrapped in the usage section, and thus not all arguments can be seen:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/28304028/166663791-0e408c16-75f1-40dc-a423-0b077d353f83.png">

### Describe the behavior you expected
Text should be wrapped so that no horizontal scrollbar appears.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
FWIW, you'll see the same behavior with the regular R help server:

<img width="631" alt="Screen Shot 2022-05-04 at 11 22 48 AM" src="https://user-images.githubusercontent.com/1976582/166800924-dd6d09f1-2721-4521-8520-ef43060137a7.png">

Arguably, the onus is on the package author to ensure arguments are wrapped at an appropriate length.

**Comment by frederikziebell** [comment]
I disagree. Prior to R 4.2, when the help was just regular text, wrapping worked. Why should the package owner decide what wrapping length is appropriate, when the window the help is displayed in is knowing the correct wrapping for my situation?

**Comment by kevinushey** [comment]
The change was made in R, not RStudio. We're presenting the HTML generated by R here, and it has the same behavior regardless of whether you're viewing it within RStudio or in your browser.

We could do some work in RStudio to make the presentation better but my point here is that we're congruent with R's own behavior.

**Comment by ronblum** [comment]
Marking this as a potential enhancement.
