### ISSUE TITLE
Automatic line breaks by sentence gets confused by citations

### ISSUE THREAD

**Issue by ulyngs** [rstudio/rstudio#11110]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.06.0 Build 348
    OS Version      :  MacOS Monterey (12.3.1)
    R Version       : 4.0.5 ("Shake and Throw")

### Steps to reproduce the problem
1: set the visual editor to automatically insert line breaks after sentences 

<img width="638" alt="Screenshot 2022-05-03 at 11 05 31" src="https://user-images.githubusercontent.com/23137032/166491611-d26c4c3c-87dc-4c74-9b5d-cba051edafeb.png">

2: Put this content in an R Markdown file, in Source mode.

```markdown
This is a test (with a random citation [@davenportAttentionEconomyUnderstanding2001]). This sentence should get a line break automatically added before it [@OptimizingEngagementUnderstanding2019; @orlowski2020], but it does not.

This is a test (with a random citation [@davenportAttentionEconomyUnderstanding2001]). If there's only one citation in this sentence, [@OptimizingEngagementUnderstanding2019], automatic line breaks before it works.

This is a test (with no random citation). If there's no citation in the former sentence [@OptimizingEngagementUnderstanding2019; @orlowski2020], sentence wrapping works.
```

3: Go to the Visual editor, and back again. The source code now looks like this:

```markdown
This is a test (with a random citation [@davenportAttentionEconomyUnderstanding2001]). This sentence should get a line break automatically added before it [@OptimizingEngagementUnderstanding2019; @orlowski2020], but it does not.

This is a test (with a random citation [@davenportAttentionEconomyUnderstanding2001]). 
If there's only one citation in this sentence, [@OptimizingEngagementUnderstanding2019], automatic line breaks before it works.

This is a test (with no random citation). 
If there's no citation in the former sentence [@OptimizingEngagementUnderstanding2019; @orlowski2020], sentence wrapping works.
```

### Describe the problem in detail
The automatic line breaks fail when consecutive sentences involve multiple citations.

### Describe the behavior you expected
The sentence

```markdown
This is a test (with a random citation [@davenportAttentionEconomyUnderstanding2001]). This sentence should get a line break automatically added before it [@OptimizingEngagementUnderstanding2019; @orlowski2020], but it does not.
```

should have automatically received a line break, like so:

```markdown
This is a test (with a random citation [@davenportAttentionEconomyUnderstanding2001]). 
This sentence should get a line break automatically added before it [@OptimizingEngagementUnderstanding2019; @orlowski2020], but it does not.
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ulyngs Thank you for raising the issue! I can also reproduce this in 2022.02.2+485, but it works correctly in 2021.09.03+396. We'll review this as we continue development of RStudio.

Triage: This is a regression in Prairie Trillium.

**Comment by jjallaire** [comment]
We are using the [sentence splitter](https://github.com/azu/sentence-splitter) JS library to do sentence splitting. It implements dozens of heuristics to try to get this right but clearly this particular combination is messing it up. I think our only recourse here is to report as a big to sentence-splitter and see if a fix is forthcoming.

**Comment by jjallaire** [comment]
Fixed with: https://github.com/rstudio/rstudio/commit/5956554a7ace6489fb4bcc93ed9a5423c3a57bca

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.11.0-daily+169 on MacOS 13
- RStudio Server 2022.11.0-daily+169 on Ubuntu 20 via Chrome on MacOS 13

Checked that everything works as expected with:
- The above examples and sentence-wrapping turned on
- The same examples and column-wrapping turned on 
- Similar examples but with no citations
- The examples above but without automatic text wrapping
