### ISSUE TITLE
`Close all saved files` feature

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11127]
Sometimes I have `untitled1` and `untitled2` open that have some scratch work that I don't want to lose, but I've opened a whole bunch of other files in an R package I'm working on and I want to close those. `Close all except current` works when I have exactly 1 untitled file, but not >1. So if there was a way to just close the saved files, then I'd be pretty happy!

**Comment by gadenbuie** [comment]
I requested [a similar feature](https://github.com/rstudio/rstudio/issues/8699) and second that a simple **Close all execpt current** gesture would be excellent.

**Comment by jmcphers** [comment]
@gadenbuie We do have that gesture! It's called _Close other documents_. The keybinding below is the default:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/470418/166826173-8761faae-86e6-4b90-8a58-89ddc40cf32c.png">

**Comment by gadenbuie** [comment]
ugh distracted typing, I meant to echo @DavisVaughan in saying **Close all unsaved**

**Comment by gadenbuie** [comment]
I hope my commenting helps this issue avoid the stalebot. **Close All Saved Files** would be a very helpful feature!

**Comment by olivroy** [comment]
I think this would be awesome too!
