### ISSUE TITLE
Execution of "Multi-line R statement" does not handle raw strings

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#11123]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 343
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. Create a new R script and paste in the following code2. 

    ```R
    r"(
     a
     b
     c
    )"
    ```

2. Place the cursor at "b" and press Cmd + enter

### Describe the problem in detail

"b" is sent to the console

### Describe the behavior you expected

The complete raw string should be sent to the console.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
I can reproduce this in RStudio Desktop on MacOS 12.4 as far back as 1.4.1106. It worked in 1.3.1093, though.

**Comment by mikebessuille** [comment]
related to https://github.com/rstudio/rstudio/issues/10077

**Comment by romainfrancois** [comment]
QA note: also check that it works when the cursor is on the first row.

**Comment by jonvanausdeln** [comment]
Tested/Verified `CMD + Enter` sends entire string to console, with cursor placed on all lines.

RStudio-2022.10.0-daily-37
