### ISSUE TITLE
Find in Files path missing leading slash

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#11125]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+352
    OS Version      :  Mac OS 12.3
    R Version       : 

### Steps to reproduce the problem

Find in Files result path is joined to Find in Files search directory, but leading slash is missing

Find in Files search in a specific directory: e.g. `~/archived_issues`

Results show up as: `~/archived_issuesrest_of_path`
Note that there is no slash between `~/archived_issues` and `rest_of_path` as there should be

<img width="749" alt="image" src="https://user-images.githubusercontent.com/7817881/166738301-9421687e-267d-41df-9e80-32019dfae595.png">

![image](https://user-images.githubusercontent.com/7817881/166739568-c6a4ae70-89b0-431a-9cc2-84acf559f708.png)

**Comment by romainfrancois** [comment]
Verified in `RStudio 2022.06.0-daily+361`
