### ISSUE TITLE
RStudio Unmet dependencies libc6

### ISSUE THREAD

**Issue by felipetac** [rstudio/rstudio#11129]
### System details

    RStudio Edition : Desktop
    RStudio Version : rstudio-2022.02.2-485-amd64.deb
    OS Version      : Pop-OS 21.10
    R Version       : 4.2.0

### Steps to reproduce the problem

  com.github.donadigo.eddy rstudio-2022.02.2-485-amd64.deb
  click "Install"

### Describe the problem in detail

  The following packages have unmet dependencies: libc6-i386: Depend: libc6 (= 2.34-0ubuntu3.2) but 2.35-0ubuntu3 is to be installed

### Describe the behavior you expected

  Rstudio Installed

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
As far as I can see, the error is independent of RStudio? You might need to update or reinstall the libc package.

What does `sudo apt update && sudo apt upgrade` print from a terminal for you?
