### ISSUE TITLE
Visual editor messes up line breaks in block quotes

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#11122]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 343
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. Create a new RMarkdown document and copy and paste the following markdown:

    ```md
    > An explicit missing value is the presence of an absence.\
    > An implicit missing value is the absence of a presence.
    ```

2. Switch to the visual editor and then switch back to the source editor

    ```md
    > An explicit missing value is the presence of an absence.\
    >
    > An implicit missing value is the absence of a presence.
    ```

3. Switch back to the visual editor, delete the two new lines and add a line break to get the desired visual appearance.
    <img width="509" alt="Screen Shot 2022-05-04 at 11 41 18" src="https://user-images.githubusercontent.com/4196/166729544-3ab808e4-3dcb-4958-802d-a3b5a10f6d05.png">

4. Switch to the source editor and then back to the visual editor. It now looks like this:
    <img width="512" alt="Screen Shot 2022-05-04 at 11 41 46" src="https://user-images.githubusercontent.com/4196/166729636-78cccee0-1af9-4a41-8628-0699fefd93a5.png">

### Describe the problem in detail

It seems like line breaks are not correctly preserved and get replaced with a line break and a new line.

### Describe the behavior you expected

You should be able to round trip line breaks in blockquotes.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hadley** [comment]
(I have auto save turned on so it's possible that reproducing the problem requires saving after each step)

**Comment by ulyngs** [comment]
Might be related to #11110  (automatic line breaks fail mysteriously when too many citations are included in sentences)

**Comment by hadley** [comment]
Please stay alive

**Comment by hadley** [comment]
If it helps, I'm still seeing it in 2022.12.0-preview+320

**Comment by ronblum** [comment]
Confirmed that this is happening in RStudio Desktop 2022.07.2-576 and 2022.12.0-preview+330, but not in 2022.02.2-485 or earlier.

The code changes—the blank line is inserted—if sentence wrapping is turned on. With sentence wrapping turned off, the code is unchanged. This is happening because of the period at the end of the sentence.

So with sentence wrapping turned on,

```
> An explicit missing value is the presence of an absence.\
> An implicit missing value is the absence of a presence.

> This line doesn't end in a period\
> because it's not the end of the sentence.
```

becomes

```
> An explicit missing value is the presence of an absence.\
>
> An implicit missing value is the absence of a presence.

> This line doesn't end in a period\
> because it's not the end of the sentence.
```

**Comment by jjallaire** [comment]
Should be resolved here: https://github.com/quarto-dev/quarto/commit/75224a49fc6dedd6c647f6cdaa48e054422d5566

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+312 on MacOS 13.2 using the sample code above.
