### ISSUE TITLE
Execution of "Multi-line R expression" fails with multiline strings

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#11124]
### System details

    RStudio Edition : Desktop
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. Create a new R script and paste in the following R code:

    ```R
    identity(
      paste0("
        "
      )
    )
    ```

2. Place the cursor on `paste0()` and press Cmd + Enter

### Describe the problem in detail

Only part of the expression is sent to the console: 

```R
identity(
  paste0("
    "
  )
```

### Describe the behavior you expected

The complete expression should be sent to the console.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hadley** [comment]
I don't see the problem unless the string is nested inside another function call, i.e. this is ok:

```R
"
a
b
c
  "
```

So I think this is a different problem to #11123

**Comment by ronblum** [comment]
Note: If I'm trying this correctly, this bug has been around since 1.3.1093, maybe earlier.

**Comment by mikebessuille** [comment]
This duplicates https://github.com/rstudio/rstudio/issues/10077
