### ISSUE TITLE
"Reflow comment" should act on paragraphs, not whole documents, when there is no selection

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rstudio#11137]
When writing Rmarkdown documents, I often use "reflow comment" to reflow text so as to keep it within the per-line character limit. If I do this without any text being selected, it reflows the entire document. This is rarely what I want and usually leads to a short panic and Ctrl+Z Undo.

I usually want to reflow single paragraphs. At the moment, I have to select the paragraph and hit the keyboard shortcut. It would be easier if "reflow comment" just applied to the current paragraph when there is no selected text. Then I could just hit the keyboard shortcut without needing to select.

This is in line with behaviour in R scripts, where by default, only the current "comment block" is reflowed if there is no selected text.

**Comment by ronblum** [comment]
@hughjonesd Thank you for raising the suggestion! We'll review this as we continue development of RStudio.

**Comment by hughjonesd** [comment]
It may be that people sometimes want to reflow a whole document. A separate "reflow all" menu item might allow this. 

One reason I don't reflow the whole document is issue #10244, which means that reflowing breaks inline R fragments and I'd have to hunt these down and fix them.
