### ISSUE TITLE
fuzzy finder discoverability

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#11139]
In https://github.com/rstudio/rstudio/pull/11102 we've introduced the ability to restrict the search to `test_that()` items. In general we should make it easier to find out about capabilities of the fuzzy finder: 

 - test 
 - file location, i.e. with the `:<line>:<col>` suffix
 - regex search, i.e. when the search term includes a `*` 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/2625526/166917253-ee6fd060-02fb-4fe9-b3c9-f96b12784eac.png">

Perhaps the "Go to File/Function" label can be more informative ?
Perhaps the dialog should include some non invasive small text hints below the text box ?

**Comment by kevinushey** [comment]
My proposal here would be a question mark button displayed somewhere in the UI:

- Maybe at the top-right corner of the dialog, in the label?
- Or, just have a separate "[?] Using the Fuzzy Finder" Help button + label below the text input, in the dialog.

Clicking that would display a cheat sheet for the fuzzy finder. It could either be a separate RStudio support article, or (IMHO, preferably) something we display inline in the IDE (similar to the Keyboard Shortcuts quick reference).

<img width="1988" alt="Screen Shot 2022-05-05 at 11 04 10 AM" src="https://user-images.githubusercontent.com/1976582/166985330-0cb602ed-997d-4ed2-a7d6-ffe5561ab828.png">

**Comment by romainfrancois** [comment]
I think a document is a bit much for this (at least with the current capabilities). Something like this perhaps: 

<img width="278" alt="image" src="https://user-images.githubusercontent.com/2625526/168840901-7fdacdca-24fc-400c-96d3-c1ab65dd003f.png">

Where the extra information is shown when the "?" is hovered. 

Also, would we want to hint about regular expressions being triggered by a `*` ?

**Comment by kevinushey** [comment]
We do have some existing documentation for the "Go to File / Function" UI, but I doubt many people know about it:

https://support.rstudio.com/hc/en-us/articles/200710523-Navigating-Code-in-the-RStudio-IDE

Overall, I'm a fan of this presentation. My tweaks would be:

- Ensure that this text is only shown when the user clicks on the question mark icon,
- Increase the contrast and make the text a little bit darker,
- Add a bit more padding between the help text and the search box.

Is it worth defining what "fuzzy" means here? (not sure if there's a good way of saying "case-insensitive disjoint subsequence matches").

**Comment by gtritchie** [comment]
To make that accessible you need to make sure the question mark can be reached and activated with keyboard-only, not just by hovering the mouse. There will be other considerations for screen reader users, too.

In other words, try to reuse an existing UI metaphor/widget  if at all possible.

**Comment by romainfrancois** [comment]
🤔 how about the suggestion test would say something like "type ? for help" and the information would appear/disappear based on that ?

**Comment by mikebessuille** [comment]
@romainfrancois, I'm not a fan of that style of help.   Wouldn't it be easy to simply copy an existing ? implementation from another existing pane or dialog?

**Comment by romainfrancois** [comment]
Unless we come up with more special prefixes, this no longer feels useful. I think we can close this now.
