### ISSUE TITLE
rJava will not load within RStudio on Mac ARM 

### ISSUE THREAD

**Issue by daynefiler** [rstudio/rstudio#11130]
### System details

    RStudio Edition : Desktop
    RStudio Version : 
      RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for macOS
      Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
      AND 
      RStudio 2022.06.0-daily+353 "Spotted Wakerobin" Daily (d1cb843e5f1b292e19cfffb13989bf14eb718a6b, 2022-05-04) for macOS
      Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  MacOS 12.3.1 (21E258)
    R Version       :  4.1.2 (aarch64-apple-darwin20)

### Steps to reproduce the problem
Install and load rJava within RStudio w/ Apple silicon.

### Describe the problem in detail

I have installed rJava and can load the package within a terminal. However, when trying to load within RStudio, both the current release and daily Electron builds, I get the following error:

```
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(jli, FALSE)
  error: unable to load shared object '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib':
  dlopen(/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib, 0x000A): tried: '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

Running `R CMD javareconf ` gives the following:

```
Java interpreter : /Users/dayne/mambaforge/jre/bin/java
Java version     : 1.8.0_312
Java home path   : /Users/dayne/mambaforge
Java compiler    : /Users/dayne/mambaforge/bin/javac
Java headers gen.: /Users/dayne/mambaforge/bin/javah
Java archive tool: /Users/dayne/mambaforge/bin/jar

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/jre/lib/server -ljvm
/opt/R/arm64/gfortran/bin/gcc -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Users/dayne/mambaforge/include -I/Users/dayne/mambaforge/include/darwin  -I/opt/R/arm64/gfortran/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/dayne/mambaforge/include   -fPIC  -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -I/Users/dayne/mambaforge/include -c conftest.c -o conftest.o
/opt/R/arm64/gfortran/bin/gcc -fopenmp -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/gfortran/lib -Wl,-rpath,/opt/R/arm64/gfortran/lib -L/Users/dayne/mambaforge/lib -Wl,-rpath,/Users/dayne/mambaforge/lib -o conftest.so conftest.o -L/Users/dayne/mambaforge/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Users/dayne/mambaforge
Java library path: /Users/dayne/mambaforge/jre/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/darwin
JNI linker flags : -L$(JAVA_HOME)/jre/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.
```

### Describe the behavior you expected

It would be great to use rJava within RStudio. 😄 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Where did you obtain your copy of Java from?

**Comment by daynefiler** [comment]
Conda:

```
java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)
```

I originally had v11 (also ARM) and then downgraded to 8 based off a suggestion [here](https://stackoverflow.com/q/67849830/1623354). That's when I learned I could load the package in the terminal, thought the problem was solved, then opened RStudio back up and continued getting the above error when trying to load the package.

**Comment by ronblum** [comment]
@astayleraz Can you do a quick check on the M1 to see what happens? I think you just need to install `rJava` and load it:

```
install.packages("rJava")
library("rJava")
```

(@daynefiler Please correct me if my example to reproduce is incorrect.)

**Comment by astayleraz** [comment]
I was able to reproduce the error @daynefiler got. I followed a suggestion in the link they posted and installed a ‘x86_64’ build of a Java JRE. I then ran `/usr/libexec/java_home -V -a x86_64` and set that path as my $JAVA_HOME in my .zshenv and I was then able to run `library("rJava")` with no issues.

**Comment by daynefiler** [comment]
@astayleraz Is this using an x86 installation of R? Still seems odd to me RStudio isn't able to run the arm Java when R runs it just fine outside the IDE.

**Comment by astayleraz** [comment]
It was with an x86 instalation of R. I got a similar error when I tried this in the terminal console as well.

**Comment by daynefiler** [comment]
I am using arm installations of R & Java, with rJava working on the terminal and NOT in RStudio.

**Comment by astayleraz** [comment]
@kevinushey Not sure if you are able to reproduce this where it works in the terminal but not in RStudio? Maybe I am missing something in my reproduction steps. Perhaps that does not matter and the fact it is an issue in RStudio is enough to move this forward?

**Comment by kevinushey** [comment]
I wasn't able to reproduce; it works fine for me.

The rJava package looks at the JAVA_HOME environment variable, or (if that is not set) the output of `/usr/libexec/java_home`, to figure out what version of Java it should bind to.

My guess is that JAVA_HOME may be set differently in each case; e.g. perhaps `JAVA_HOME` has been set (in RStudio) to point to an x86_64 JDK.

**Comment by daynefiler** [comment]
Any thoughts on why RStudio would be pointing to a different Java version?

**Comment by yildizkoca** [comment]
> error: unable to load shared object '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib':

Quite stupid, but finding the '/Library/Internet Plug-Ins' folder and removing the space in the folder name fixed it for me. So change the folder name from '/Library/Internet Plug-Ins' into '/Library/InternetPlug-Ins'. Hope this helps!

**Comment by kevinariza305** [comment]
@daynefiler were you able to figure this out? @yildizkoca suggestion did not work for me

**Comment by FishyguyNeel** [comment]
I was also not able to install rJava. when I tried doing it gave this error
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(jvm, FALSE)
  error: unable to load shared object '/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/lib/server/libjvm.dylib':
  dlopen(/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/lib/server/libjvm.dylib, 0x000A): tried: '/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/lib/server/libjvm.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/lib/server/libjvm.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/lib/server/libjvm.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by kevinariza305** [comment]
i was able to fix it by addding this line to my .zshrc file

`export JAVA_HOME=$(/usr/bin/java)`

the `/usr/bin/java` comes from finding out the location of where java is installed on my computer (a macbook)

replace that path with where your java sdk is installed

**Comment by jzadra** [comment]
I'm still encountering this issue trying to install tabulizer.  I have tried adding the JAVA_HOME export (mine is located at `/opt/homebrew/opt/openjdk/bin/java`).

Installing the `rJava` package reports as successful, but loading the rJava package produces the same error others have found:

```
> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(jli, FALSE)
  error: unable to load shared object '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib':
  dlopen(/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib, 0x000A): tried: '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (no such file), '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

```

**Comment by marine-ecologist** [comment]
Still encountering this issue here. 
`install.packages("rJava")` appears to install correctly, but throws the following error:

```
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(jli, FALSE)
  error: unable to load shared object '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib':
  dlopen(/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib, 0x000A): tried: '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (no such file), '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

In my case changing  '/Library/Internet Plug-Ins/` to '/Library/InternetPlug-Ins/ made no difference as the folder was empty and missing the relevant contents (`JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib`)
