### ISSUE TITLE
Changing a code block from an unrecognized language adds the new language instead of replacing it

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11132]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 2021.09.0+351 through 2022.06.0-daily-354
    OS Version      : MacOS 12.4, Ubuntu 20.04
    R Version       : 3.6.3 & 4.1.2

### Steps to reproduce the problem

1. Open a new R Markdown document.
2. Switch to visual mode.
3. <kbd>Insert -> Code Block</kbd>
4. For the language, enter `cpp` (we want something that exists) and click "OK".
    - A code block is created, identified as "cpp" in a gray oval.
5. Click on the ellipses in a gray circle. 
6. Change the language to `markdown` (which is recognized) and click "OK".
    - The code block is now identified as "markdown".
7. Click on the ellipses in a gray circle. 
8. Change the language to `md` (which is not recognized) and click "OK".
    - The code block is now identified as ".md".
7. Click on the ellipses in a gray circle. 
8. Change the language to `bash` (which is recognized) and click "OK".
    - The code block is now identified as ".md" and "bash".
7. Click on the ellipses in a gray circle. 
8. Change the language to `markdown` (which is recognized) and click "OK".
    - The code block is now identified as ".md" and "markdown".
9. Switch to source mode
    - The source code for the block is
````
``` {.markdown .md}
```
````

### Describe the problem in detail

If a code block is of a type that isn't recognized, changing the language adds the new one instead of replacing the old one.

### Describe the behavior you expected

The language type should always be replaced, whether or not the language is recognized.

Note: This worked in 1.4.1717 (Juliet Rose) and regressed in 2021.09.0+351 (Ghost Orchid).

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
This is by design as there are only certain languages recognized by pandoc for syntax highlighting and we indicate those by showing them without the leading period.
