### ISSUE TITLE
Project Build Tools Preferences Pane showing &mdash literal text in French UI

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11134]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+354
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem

- Create a package project, then open the Project Preferences, and look at the Build Tools
- In English, looks like this (as expected):

![Screen Shot 2022-05-04 at 5 17 52 PM](https://user-images.githubusercontent.com/10569626/166840572-97c6fabf-530a-417e-a1eb-ff4004d570c1.png)

- Now switch to French UI (Tools / Global Options / Advanced / UI Language) and restart
- Look again at Project Preferences / Build Tools

### Describe the problem in detail

- Instead of seeing dashes you see `&mdash`, which causes lines to wrap and makes content not fit in the pane

![Screen Shot 2022-05-04 at 5 16 14 PM](https://user-images.githubusercontent.com/10569626/166840649-982c796f-29b8-4c5e-aa47-3c871956eeb6.png)

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.05.0-daily+296 on MacOS 13.4 and Red Hat 9.1.
