### ISSUE TITLE
GPU and Accessibility Diagnostics Windows have menubar on Linux and Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11142]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+356
    OS Version      : Windows-11, Ubuntu 22
    R Version       : Any

### Steps to reproduce the problem

On Windows or Linux (only tried Gnome/Ubuntu 22), start IDE and display either the GPU Diagnostics or Accessibility Diagnostics windows.

### Describe the problem in detail

The windows have a menubar (File, Edit, etc).

![gpu-diag](https://user-images.githubusercontent.com/10569626/166959838-fb85b5c4-a42a-42c2-a1a8-1cc7059c47ec.png)

### Describe the behavior you expected

Menubar not displayed.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified that the menu bar is gone in RStudio Desktop 2022.06.0-daily+437 (Electron) on
- MacOS 12.4 (just making sure)
- Red Hat 8.5
- Windows 11
