### ISSUE TITLE
Reopened files in home directory path show up twice in "Recent Files"

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11150]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+356 (Electron)
    OS Version      : MacOS 12.4, Ubuntu 20.04.3
    R Version       : 4.1.2 & 4.2.0

### Steps to reproduce the problem

1. <kbd>File -> Recent Files -> Clear List</kbd> (This isn’t necessary but will make things more apparent.)
2. <kbd>File -> New File -> R Script</kbd>
3. Save it in the user home directory. Let’s use the name `athome.R`.
4. Close the file.
5. <kbd>File -> Recent Files</kbd>
    - The file `athome.R` is listed.
6. Click on `athome.R` to open it.
    - The file opens.
7. <kbd>File -> Recent Files</kbd>
    - The file shows up twice.

### Describe the problem in detail

Files that are saved in the home directory (or subdirectory in it), closed, and reopened using "Recent Files" will then show up twice in "Recent Files". 

On MacOS & Linux, the file shows up once with `~` and a second time with the home directory name.

<img width="148" alt="x_two_homes" src="https://user-images.githubusercontent.com/31009952/167185474-623b862b-3ae7-44a5-93f2-99ae1b4dd104.png">

On Windows, the file shows up once with just the file name, and a second time with the full path.

![w_two_files](https://user-images.githubusercontent.com/31009952/167185642-eea330e9-18f1-4137-a118-e03fd5fb2df9.png)

### Describe the behavior you expected

Only show one record for each file.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Most likely another issue re: use of `\` path separators instead of `/` path separators. (https://github.com/rstudio/rstudio/pull/11135)
