### ISSUE TITLE
Rstudio interface (up to daily build 373 certainly) slow: fixed by setting rendering to "software"

### ISSUE THREAD

**Issue by cpsyctc** [rstudio/rstudio#11155]
### System details

    RStudio Edition :  Desktop
    RStudio Version : build 373
    OS Version      :  Ubuntu 22.04
    R Version       :  4.2.0 (2022-04-22) -- "Vigorous Calisthenics"

### Steps to reproduce the problem

Launch Rstudio on this machine: unusably slow interaction with the interface

### Describe the problem in detail

Anything, selecting options, highlighting code, is unusably slow.

### Describe the behavior you expected

Usable speed!  The issue seems to be down to a moderately widespread issue with this machine and particularly its graphics system.  Similar experience with Chromium and related browsers (but not Firefox), with zoom, teams and even with Ubuntu disks.  If I switch off hardware acceleration in Chromium it then works fine and I have found that if I set Tools, Options, General, Advanced, Rendering engine to "Software" the problem goes away.

Machine is a "Clevo" with "AMD Ryzen 7 5800H with Radeon Graphics" and "GA106M [GeForce RTX 3060 Mobile / Max-Q]" (from lshw).  Diagnostics report follows.

<details>
RStudio Diagnostics Report
==========================

WARNING: This report may contain sensitive security information and / or
personally identifiable information. Please audit the below and redact any
sensitive information before submitting your diagnostics report.

Generated: Mon May  9 14:38:25 2022

RStudio Version
--------------------------------------------------
2022.06.0-daily+373

Session Information
--------------------------------------------------
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.0   fastmap_1.1.0    rsconnect_0.8.25 cli_3.3.0        htmltools_0.5.2  tools_4.2.0      yaml_2.3.5       memoise_2.0.1    distill_1.3      rmarkdown_2.14   downlit_0.4.0   
[12] cachem_1.0.6     knitr_1.39       xfun_0.30        digest_0.6.29    rlang_1.0.2      evaluate_0.15   

System Information
--------------------------------------------------
sysname        : Linux                                      
release        : 5.15.0-27-generic                          
version        : #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022
nodename       : Clevo1                                     
machine        : x86_64                                     
login          : chris                                      
user           : chris                                      
effective_user : chris                                      

Platform Information
--------------------------------------------------
OS.type    : unix
file.sep   : /
dynlib.ext : .so
GUI        : RStudio
endian     : little
pkgType    : source
path.sep   : :
r_arch     : 

Environment Variables
--------------------------------------------------
_R_CHECK_COMPILATION_FLAGS_KNOWN_ : -Wformat -Werror=format-security -Wdate-time
CLICOLOR_FORCE                    : 1
DBUS_SESSION_BUS_ADDRESS          : unix:path=/run/user/1000/bus
DEFAULTS_PATH                     : /usr/share/gconf/ubuntu.default.path
DESKTOP_SESSION                   : ubuntu
DISPLAY                           : :1
EDITOR                            : vi
force_s3tc_enable                 : true
GDMSESSION                        : ubuntu
GIO_LAUNCHED_DESKTOP_FILE         : /usr/share/applications/rstudio.desktop
GIO_LAUNCHED_DESKTOP_FILE_PID     : 115233
GIT_ASKPASS                       : rpostback-askpass
GJS_DEBUG_OUTPUT                  : stderr
GJS_DEBUG_TOPICS                  : JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID          : this-is-deprecated
GNOME_SHELL_SESSION_MODE          : ubuntu
GPG_AGENT_INFO                    : /run/user/1000/gnupg/S.gpg-agent:0:1
GTK_MODULES                       : gail:atk-bridge
HOME                              : /home/chris
INVOCATION_ID                     : e98778eae213421b893cec8b593e35d9
JOURNAL_STREAM                    : 8:105375
LANG                              : en_GB.UTF-8
LANGUAGE                          : en_GB:en
LC_ADDRESS                        : en_GB.UTF-8
LC_IDENTIFICATION                 : en_GB.UTF-8
LC_MEASUREMENT                    : en_GB.UTF-8
LC_MONETARY                       : en_GB.UTF-8
LC_NAME                           : en_GB.UTF-8
LC_NUMERIC                        : en_GB.UTF-8
LC_PAPER                          : en_GB.UTF-8
LC_TELEPHONE                      : en_GB.UTF-8
LC_TIME                           : en_GB.UTF-8
LD_LIBRARY_PATH                   : /usr/lib/R/lib:/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
LN_S                              : ln -s
LOGNAME                           : *** redacted ***
MAKE                              : make
MANAGERPID                        : 4863
MANDATORY_PATH                    : /usr/share/gconf/ubuntu.mandatory.path
MPLENGINE                         : tkAgg
PAGER                             : /usr/bin/pager
PAPERSIZE                         : a4
PATH                              : /usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/lib/rstudio/bin/quarto/bin:/usr/lib/rstudio/bin/postback
PWD                               : *** redacted ***
PYTHONIOENCODING                  : utf-8
QT_ACCESSIBILITY                  : 1
QT_IM_MODULE                      : ibus
R_BROWSER                         : xdg-open
R_BZIPCMD                         : /bin/bzip2
R_DOC_DIR                         : /usr/share/R/doc
R_GZIPCMD                         : /bin/gzip -n
R_HOME                            : /usr/lib/R
R_INCLUDE_DIR                     : /usr/share/R/include
R_LIBS_SITE                       : /usr/local/lib/R/site-library/:/usr/lib/R/site-library:/usr/lib/R/library'
R_LIBS_USER                       : /home/chris/R/x86_64-pc-linux-gnu-library/4.2
R_PAPERSIZE                       : letter
R_PAPERSIZE_USER                  : a4
R_PDFVIEWER                       : /usr/bin/xdg-open
R_PLATFORM                        : x86_64-pc-linux-gnu
R_PRINTCMD                        : /usr/bin/lpr
R_RD4PDF                          : times,inconsolata,hyper
R_SESSION_TMPDIR                  : /tmp/RtmpDzDgFp
R_SHARE_DIR                       : /usr/share/R/share
R_STRIP_SHARED_LIB                : strip --strip-unneeded
R_STRIP_STATIC_LIB                : strip --strip-debug
R_SYSTEM_ABI                      : linux,gcc,gxx,gfortran,gfortran
R_TEXI2DVICMD                     : /usr/bin/texi2dvi
R_UNZIPCMD                        : /usr/bin/unzip
R_ZIPCMD                          : /usr/bin/zip
RETICULATE_PYTHON_FALLBACK        : /usr/bin/python3
RMARKDOWN_MATHJAX_PATH            : /usr/lib/rstudio/resources/mathjax-27
RS_PPM_FD_READ                    : 26
RS_PPM_FD_WRITE                   : 31
RS_RPOSTBACK_PATH                 : /usr/lib/rstudio/bin/rpostback
RS_SHARED_SECRET                  : *** redacted ***
RSTUDIO                           : 1
RSTUDIO_CLI_HYPERLINKS            : true
RSTUDIO_CONSOLE_COLOR             : 256
RSTUDIO_CONSOLE_WIDTH             : 196
RSTUDIO_PANDOC                    : /usr/lib/rstudio/bin/quarto/bin/tools
RSTUDIO_PROGRAM_MODE              : desktop
RSTUDIO_SESSION_PORT              : 60042
RSTUDIO_USER_IDENTITY             : chris
RSTUDIO_WINUTILS                  : bin/winutils
SED                               : /bin/sed
SESSION_MANAGER                   : local/Clevo1:@/tmp/.ICE-unix/5385,unix/Clevo1:/tmp/.ICE-unix/5385
SHELL                             : /bin/bash
SHLVL                             : 0
SSH_AGENT_LAUNCHER                : gnome-keyring
SSH_AUTH_SOCK                     : *** redacted ***
SYSTEMD_EXEC_PID                  : 5408
TAR                               : /bin/tar
TERM                              : xterm-256color
USER                              : chris
USERNAME                          : *** redacted ***
WINDOWPATH                        : 2
XAUTHORITY                        : /run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS                   : /etc/xdg/xdg-ubuntu:/etc/xdg
XDG_CURRENT_DESKTOP               : ubuntu:GNOME
XDG_DATA_DIRS                     : /usr/share/ubuntu:/usr/share/gnome:/home/chris/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_MENU_PREFIX                   : gnome-
XDG_RUNTIME_DIR                   : /run/user/1000
XDG_SESSION_CLASS                 : user
XDG_SESSION_DESKTOP               : ubuntu
XDG_SESSION_TYPE                  : x11
XMODIFIERS                        : @im=ibus

                      

Loaded Packages
--------------------------------------------------
cli       : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/cli      
digest    : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/digest   
distill   : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/distill  
downlit   : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/downlit  
evaluate  : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/evaluate 
fastmap   : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/fastmap  
htmltools : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/htmltools
knitr     : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/knitr    
rlang     : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/rlang    
rmarkdown : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/rmarkdown
xfun      : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/xfun     
yaml      : /home/chris/R/x86_64-pc-linux-gnu-library/4.2/yaml     
base      : /usr/lib/R/library/base                                
compiler  : /usr/lib/R/library/compiler                            
datasets  : /usr/lib/R/library/datasets                            
graphics  : /usr/lib/R/library/graphics                            
grDevices : /usr/lib/R/library/grDevices                           
methods   : /usr/lib/R/library/methods                             
stats     : /usr/lib/R/library/stats                               
tools     : /usr/lib/R/library/tools                               
utils     : /usr/lib/R/library/utils                               
cachem    : /usr/local/lib/R/site-library/cachem                   
memoise   : /usr/local/lib/R/site-library/memoise                  
rsconnect : /usr/local/lib/R/site-library/rsconnect                

R System Profile: /usr/lib/R/library/base/R/Rprofile
--------------------------------------------------
### the wrong environment (user profiles are run in .GlobalEnv).

.GlobalEnv <- globalenv()
attach(NULL, name = "Autoloads")
.AutoloadEnv <- as.environment(2)
assign(".Autoloaded", NULL, envir = .AutoloadEnv)
T <- TRUE
F <- FALSE
R.version <- structure(R.Version(), class = "simple.list")
version <- R.version            # for S compatibility

## for backwards compatibility only
R.version.string <- R.version$version.string

##            --------- ../utils/R/zzz.R

options(keep.source = interactive())
options(warn = 0)
# options(repos = c(CRAN="@CRAN@"))
# options(BIOC = "http://www.bioconductor.org")

## setting from an env variable added in 4.0.2
local({to <- as.integer(Sys.getenv("R_DEFAULT_INTERNET_TIMEOUT", 60))
    if (is.na(to) || to <= 0) to <- 60L
    options(timeout = to)
})
options(encoding = "native.enc")
options(show.error.messages = TRUE)
## keep in sync with PrintDefaults() in  ../../main/print.c :
options(scipen = 0)
options(max.print = 99999)# max. #{entries} in internal printMatrix()
options(add.smooth = TRUE)# currently only used in 'plot.lm'

if(isFALSE(as.logical(Sys.getenv("_R_OPTIONS_STRINGS_AS_FACTORS_",
                                 "FALSE")))) {
    options(stringsAsFactors = FALSE)
} else {
    options(stringsAsFactors = TRUE)
}

if(!interactive() && is.null(getOption("showErrorCalls")))
    options(showErrorCalls = TRUE)

local({dp <- Sys.getenv("R_DEFAULT_PACKAGES")
       if(identical(dp, "")) ## it fact methods is done first
           dp <- c("datasets", "utils", "grDevices", "graphics",
                   "stats", "methods")
       else if(identical(dp, "NULL")) dp <- character(0)
       else dp <- strsplit(dp, ",")[[1]]
       dp <- sub("[[:blank:]]*([[:alnum:]]+)", "\\1", dp) # strip whitespace
       options(defaultPackages = dp)
    })

## Expand R_LIBS_* environment variables.
Sys.setenv(R_LIBS_SITE =
           .expand_R_libs_env_var(Sys.getenv("R_LIBS_SITE")))
Sys.setenv(R_LIBS_USER =
           .expand_R_libs_env_var(Sys.getenv("R_LIBS_USER")))

local({
    if(nzchar(tl <- Sys.getenv("R_SESSION_TIME_LIMIT_CPU")))
        setSessionTimeLimit(cpu = tl)
    if(nzchar(tl <- Sys.getenv("R_SESSION_TIME_LIMIT_ELAPSED")))
        setSessionTimeLimit(elapsed = tl)
})

.First.sys <- function()
{
    for(pkg in getOption("defaultPackages")) {
        res <- require(pkg, quietly = TRUE, warn.conflicts = FALSE,
                       character.only = TRUE)
        if(!res)
            warning(gettextf('package %s in options("defaultPackages") was not found', sQuote(pkg)),
                    call. = FALSE, domain = NA)
    }
}

## called at C level in the startup process prior to .First.sys
.OptRequireMethods <- function()
{
    pkg <- "methods" # done this way to avoid R CMD check warning
    if(pkg %in% getOption("defaultPackages"))
        if(!require(pkg, quietly = TRUE, warn.conflicts = FALSE,
                    character.only = TRUE))
            warning('package "methods" in options("defaultPackages") was not found',
                    call. = FALSE)
}

if(nzchar(Sys.getenv("R_BATCH"))) {
    .Last.sys <- function()
    {
        cat("> proc.time()\n")
        print(proc.time())
    }
    ## avoid passing on to spawned R processes
    ## A system has been reported without Sys.unsetenv, so try this
    try(Sys.setenv(R_BATCH=""))
}

local({
    if(nzchar(rv <- Sys.getenv("_R_RNG_VERSION_")))
        suppressWarnings(RNGversion(rv))
})

.sys.timezone <- NA_character_

local({
    ## create an active binding for .Library.site, so that it can be
    ## modified after the base environment is locked

    ## remove the binding in the lazyload data base 
    .Internal(mkUnbound(as.name(".Library.site")))
    siteLibrary <- character()
    slfun <- function(v) {
        if (!missing(v))
            siteLibrary <<- v
        siteLibrary
    }

    makeActiveBinding(".Library.site", slfun, baseenv())

    ## make .Library.site accessible also from global environment to
    ## preserve functionality of site profiles assigning to it directly
    ## (originally, site profiles were run in base environment)

    makeActiveBinding(".Library.site", slfun, globalenv())
})
###-*- R -*- Unix Specific ----

.Library <- file.path(R.home(), "library")
.Library.site <- Sys.getenv("R_LIBS_SITE") # This is set in Renviron.
.Library.site <-
    if(.Library.site == "NULL") character() else unlist(strsplit(.Library.site, ":"))
.Library.site <- .Library.site[dir.exists(.Library.site)]

local({
    libs <- Sys.getenv("R_LIBS_USER") # This is set in Renviron.
    libs <- if(libs == "NULL") character() else unlist(strsplit(libs, ":"))
    ## .libPaths filters on existence.
    invisible(.libPaths(c(unlist(strsplit(Sys.getenv("R_LIBS"), ":")),
                          libs)))
})
local({
    popath <- Sys.getenv("R_TRANSLATIONS", "")
    if(!nzchar(popath)) {
        paths <- file.path(.libPaths(), "translations", "DESCRIPTION")
        popath <- dirname(paths[file.exists(paths)][1])
    }
    bindtextdomain("R", popath)
    bindtextdomain("R-base", popath)
    assign(".popath", popath, .BaseNamespaceEnv)
})
local({
## we distinguish between R_PAPERSIZE as set by the user and by configure
papersize <- Sys.getenv("R_PAPERSIZE_USER")
if(!nchar(papersize)) {
    lcpaper <- Sys.getlocale("LC_PAPER") # might be null: OK as nchar is 0
    papersize <- if(nchar(lcpaper))
        if(length(grep("(_US|_CA)", lcpaper))) "letter" else "a4"
    else Sys.getenv("R_PAPERSIZE")
}
options(papersize = papersize,
        printcmd = Sys.getenv("R_PRINTCMD"),
        dvipscmd = Sys.getenv("DVIPS", "dvips"),
        texi2dvi = Sys.getenv("R_TEXI2DVICMD"),
        browser = Sys.getenv("R_BROWSER"),
        pager = file.path(R.home(), "bin", "pager"),
        pdfviewer = Sys.getenv("R_PDFVIEWER"),
        useFancyQuotes = TRUE)
})

## non standard settings for the R.app GUI of the macOS port
if(.Platform$GUI == "AQUA") {
    ## this is set to let RAqua use both X11 device and X11/TclTk
    if (Sys.getenv("DISPLAY") == "")
	Sys.setenv("DISPLAY" = ":0")

    ## this is to allow gfortran compiler to work
    Sys.setenv("PATH" = paste(Sys.getenv("PATH"),":/usr/local/bin",sep = ""))
}## end "Aqua"

## de-dupe the environment on macOS (bug in Yosemite which affects things like PATH)
if (grepl("^darwin", R.version$os)) local({
    ## we have to de-dupe one at a time and re-check since the bug affects how
    ## environment modifications propagate
    while(length(dupes <- names(Sys.getenv())[table(names(Sys.getenv())) > 1])) {
        env <- dupes[1]
        value <- Sys.getenv(env)
        Sys.unsetenv(env)             ## removes the dupes, good
        .Internal(Sys.setenv(env, value)) ## wrapper requries named vector, a pain, hence internal
    }
})

local({
    tests_startup <- Sys.getenv("R_TESTS")
    if(nzchar(tests_startup)) source(tests_startup)
})

R Site Profile: /usr/lib/R/etc/Rprofile.site
--------------------------------------------------
##
##
## see help(Startup) for documentation on ~/.Rprofile and Rprofile.site

# ## Example of .Rprofile
# options(width=65, digits=5)
# options(show.signif.stars=FALSE)
# setHook(packageEvent("grDevices", "onLoad"),
#         function(...) grDevices::ps.options(horizontal=FALSE))
# set.seed(1234)
# .First <- function() cat("\n   Welcome to R!\n\n")
# .Last <- function()  cat("\n   Goodbye!\n\n")

# ## Example of Rprofile.site
# local({
#  # add MASS to the default packages, set a CRAN mirror
#  old <- getOption("defaultPackages"); r <- getOption("repos")
#  r["CRAN"] <- "http://my.local.cran"
#  options(defaultPackages = c(old, "MASS"), repos = r)
#})

## We set the cloud mirror, which is 'network-close' to everybody, as default
local({
    r <- getOption("repos")
    r["CRAN"] <- "https://cloud.r-project.org"
    options(repos = r)
})

R User Profile: /home/chris/.Rprofile
--------------------------------------------------
(File does not exist)

R Site Environ: /usr/lib/R/etc/Renviron.site
--------------------------------------------------
##
##
## see help(Startup) for documentation on ~/.Renviron and Renviron.site

# ## Example ~/.Renviron on Unix
# R_LIBS=~/R/library
# PAGER=/usr/local/bin/less

# ## Example .Renviron on Windows
# R_LIBS=C:/R/library
# MY_TCLTK="c:/Program Files/Tcl/bin"

# ## Example of setting R_DEFAULT_PACKAGES (from R CMD check)
# R_DEFAULT_PACKAGES='utils,grDevices,graphics,stats'
# # this loads the packages in the order given, so they appear on
# # the search path in reverse order.

## # Also note that you set this per-user via '%p' and '%v' for platform and version
#R_LIBS_USER=${R_LIBS_USER-'~/R/@R_PLATFORM@-library/@MAJ_MIN_VERSION@'}

##
##
## See Section 8 of the R Internals manual for many more options to customize tests.
_R_CHECK_COMPILATION_FLAGS_KNOWN_='-Wformat -Werror=format-security -Wdate-time'

## edd Mar 2022  Now in Renviron.site reflecting R_LIBS_SITE
R_LIBS_SITE="/usr/local/lib/R/site-library/:${R_LIBS_SITE}:/usr/lib/R/library'"

R User Environ: /home/chris/.Renviron
--------------------------------------------------
(File does not exist)

R Temporary Directory
--------------------------------------------------
/tmp/RtmpDzDgFp

Files in R Temporary Directory
--------------------------------------------------
git-commit-message-1c2e738a2d30.txt             
git-commit-message-1c2e774b25d45.txt            
rs-graphics-176acd9b-9aa8-490e-a36c-2a8ce776367c

Log file: /home/chris/.local/share/rstudio/log/rdesktop.log
--------------------------------------------------

(Not Found)

Log file: /home/chris/.local/share/rstudio/log/rsession-chris.log
--------------------------------------------------

2022-05-08T19:51:34.720383Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-08T19:51:34.720383Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-08T19:51:54.113434Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-08T19:51:54.113434Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-08T19:53:23.371495Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-08T19:53:23.371495Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:28:42.456056Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:28:42.456056Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:29:20.908891Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:29:20.908891Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:31:52.664093Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:31:52.664093Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:32:01.163470Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-05-09T05:32:01.163470Z [rsession-chris] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335

User prefs: /home/chris/.config/rstudio/rstudio-prefs.json
--------------------------------------------------

{
    "initial_working_directory": "~",
    "syntax_color_console": true,
    "show_doc_outline_rmd": true,
    "doc_outline_show": "all",
    "latex_preview_on_cursor_idle": "never",
    "pdf_previewer": "none",
    "posix_terminal_shell": "bash",
    "git_exe_path": "/bin/git",
    "jobs_tab_visibility": "shown",
    "graphics_antialiasing": "none"
}

System prefs: /etc/xdg/xdg-ubuntu:/etc/xdg/rstudio/rstudio-prefs.json
--------------------------------------------------

(Not Found)

User state: /home/chris/.local/share/rstudio/rstudio-desktop.json
--------------------------------------------------

{
    "context_id": "11A24092"
}
</details>

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cpsyctc** [comment]
Hm.  I thought that setting the rendering to software had solved things and certainly it speeded most things up but I have just realised that things remain broken to unusability: selecting and highlighting text in the editor can take so long that to all intents and purposes I have a hang on my hands.   I haven't: if I move the cursor somewhere else in Rstudio it's all still responsive but the code I am trying to select remains unselected apart from whatever initial bit of it got selected before something kicked in and locked the selection from continuing.  SO frustrating: I am now having to use Rstudio in Windows in a VM and that's neither fast nor very enjoyable.  I do hope someone somewhere can see what's wrong (which may not be with Rstudio I realise) and that we can get a fix sometime soon!  TIA!

**Comment by kevinushey** [comment]
Can you provide any other context?

- Does this issue affect all open documents in RStudio, or only certain documents?
- If only certain documents, is there anything unique about these documents, or the document state? (e.g. number of folds)

Any other information you can share that might help us reproduce the issue locally would be useful.

**Comment by cpsyctc** [comment]
Thanks.  The issue with rendering on autodetect is general: I don't even have to have a file open, just trying to select a bit of the R opening message lags seconds behind my mouse movements and everything is slow, drop down menus drop down slowly.  If I go back to software rendering now of course I can't replicate the similar slowness that I saw earlier today but it was definitely there then but I think the #1 issue is what I'm pretty sure is an issue about the graphics driver compatibility.  I am happy to try to give you more diagnostics or to try things out but I'm on trains most of tomorrow (10.v.22) and again on Thursday.  For the moment I will hold things on build 373 unless you want me to move to the latest (376 looking just now).  I can also try changing the nVidia driver but I do know that drivers other than the proprietary 510 loses me the use of an external monitor.  For the moment I will grit my teeth and do real Rstudio/R work in Rstudio in a Windoze VM in the same machine (which works fine but definitely slower than I was used to of course).  Very best, Chris

**Comment by gtritchie** [comment]
As a data point, could you see if this also happens with the Electron build of RStudio? This is still very much under development and isn't ready for production use, but would be good to know if it solves this particular problem. It has a much more recent build of Chromium in it than our Qt-based version.

Try most recent from:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/jammy/

**Comment by cpsyctc** [comment]
Thanks.  Certainly.  I'll be on the move most of today so not today so probably not today but certainly tomorrow.  Should I remove the existing 373 version before doing that?  dpkg --purge Rstudio?

**Comment by gtritchie** [comment]
It will replace the existing RStudio install, so no need to uninstall first.

**Comment by cpsyctc** [comment]
Thanks, good to be reassured.  I have just updated to:

```
RStudio 2022.06.0-daily+400 "Spotted Wakerobin" Daily (8d6614e4f4c0f9ff1234cfbb2debd29f6d9d06fd, 2022-05-13) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

In your electron series and a first very quick test says that you have fixed it: I could switch rendering back to the "detect" default and the UI still seems responsive.  I will try to do some work in it over the next few days and report back if I do get some hours of use in.  Very best, Chris
