### ISSUE TITLE
Rstudio crashes when calling rJava::.jinit()

### ISSUE THREAD

**Issue by schuemie** [rstudio/rstudio#11159]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Windows Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Windows 7 Enterprise
    R Version       : 4.2.0

### Steps to reproduce the problem

```r
install.packages("rJava")
rJava::.jinit()
```

### Describe the problem in detail

When initializing the Java VM using rJava, RStudio crashes. I get a Windows dialog saying 'RStudio R Session has stopped working'. One other user has also reported this in an independent environment / organization. 

Initializing the VM from the vanilla R GUI does not cause any problems. 

### Describe the behavior you expected

No crash.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/8652725/diagnostics-report.txt)

**Comment by romainfrancois** [comment]
I believe this is a duplicate of https://github.com/rstudio/rstudio/issues/11076

**Comment by jgutman** [comment]
Thanks for reporting this issue! We believe this has been fixed in the most recent [R patch for Windows ](https://cran.r-project.org/bin/windows/base/rpatched.html) as of May 8. Could you update the installed R 4.2 using the link and let us know if the problem persists?

**Comment by schuemie** [comment]
Thanks for the quick response, and apologies for the issue duplication.

I've installed the patched version of R, and can confirm the issue is resolved.
