### ISSUE TITLE
Accessibility Zoom optional or not applied to runApp window

### ISSUE THREAD

**Issue by lfmcmillan** [rstudio/rstudio#11152]
Hi,

I'd like to request that the Accessibility Zoom feature (accessed from View --> Zoom In or Out, or from Tools --> Global Options --> Appearance --> Zoom) be only applied to the RStudio app but not to the pop-up Window used for RunApp.

I have my Zoom set to 125% so I don't have to strain my eyes peering at the toolbar and filenames on a high-resolution screen. But this caused me hours of confusion when developing a Shiny app, because when I set that to Run in Window, the built-in pop-up browser window was also zoomed in to 125%. As you can see in the attached screenshot, this meant that all three buttons in the app appear vertically arranged, whereas you can see in the code on the left that the last two buttons are meant to be in a row.

In the case of these two buttons I was able to fix the issue by floating them to left and right respectively in their columns, but in general I'd rather the Shiny RunApp Window was not zoomed in even when the rest of the desktop IDE is zoomed in. 

The hours of confusion were spent trying to change the app ui code again and again without achieving any changes to the appearance, until I tried opening the app in an external browser and suddenly discovered the appearance issues had nothing to do with my code at all.

So it would be great to have a subsidiary option that allows me to not apply the Zoom to that pop-up window. 

Thanks

![rstudio_shiny_window_screenshot](https://user-images.githubusercontent.com/6456880/167239445-3f8530a1-c148-4558-a7a5-ea9f9804a12b.PNG)

**Comment by lfmcmillan** [comment]
I should add that I'm reasonably experienced with Shiny -- I developed an entire educational game using it (and some javascript code for drag-and-drop) in 2016 when Shiny was still relatively new, so the early-development status of the above app is not representative of my level of experience.

**Comment by ronblum** [comment]
@lfmcmillan Thanks for the enhancement request! We'll review it as we continue development of RStudio.

And I'm really curious about the educational game...
