### ISSUE TITLE
Logging in to RStudio Server fails on Fedora 35

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11167]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.06.0-daily+374 (RHEL8)
    OS Version      : Fedora 35
    R Version       : 4.1.3

### Steps to reproduce the problem

Log in to RStudio Server.

### Describe the problem in detail

The gray page with the spinning circle appears for a few seconds, followed by an error message:
<img width="390" alt="fedora35" src="https://user-images.githubusercontent.com/31009952/167640091-dc937299-5dd0-467e-9e8e-11a1c9d9c142.png">

In the logs, the following appears:
> 2022-05-10T13:27:30.121485Z [rserver] ERROR system error 13 (Permission denied); OCCURRED AT rstudio::core::Error rstudio::core::system::launchChildProcess(std::__cxx11::string, std::__cxx11::string, rstudio::core::system::ProcessConfig, rstudio::core::system::ProcessConfigFilter, PidType*) src/cpp/core/system/PosixSystem.cpp:2160; LOGGED FROM: rstudio::core::Error rstudio::core::system::launchChildProcess(std::__cxx11::string, std::__cxx11::string, rstudio::core::system::ProcessConfig, rstudio::core::system::ProcessConfigFilter, PidType*) src/cpp/core/system/PosixSystem.cpp:2161

### Describe the behavior you expected

Login etc. should work.

Note: This is a spinoff from #9854.

Triage note: Suggesting for Spotted Wakerobin.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Same result (i.e. error) on my newly setup Fedora 35 VM.

**Comment by mikebessuille** [comment]
If this is trivial to fix we should do it for SW, otherwise move it to next release.  I've tagged it with Worbench as it belongs on the workbench team, even if it's open source server, I think.

**Comment by jmcphers** [comment]
Do you have SELinux turned on?

**Comment by ronblum** [comment]
I leave it as an exercise to the reader. And why I'm about to close two other issues.
