### ISSUE TITLE
Find more python installations

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#11162]
The IDE has a very nice GUI selector for Python installations (screenshot). It could be improved if it:

a) included an option or instructions for how users can add additional pythons to the list
b) found all the `python`s that are on my PATH (including masked ones)
c) found the `python` that is installed at the the default location by installer from www.python.org: `/Library/Frameworks/Python.framework/Versions/3.9/bin`

<img width="621" alt="image" src="https://user-images.githubusercontent.com/8462255/167484787-ec5be9f2-a45e-4724-bc79-0ec99b988060.png">

**Comment by ronblum** [comment]
@t-kalinowski Thank you for the suggestions! I'll mark these for review as we continue developing RStudio, incuding Python support.
