### ISSUE TITLE
Unknown mark typ 'raw_tex' when switching to a markdown based format in visual mode

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#11161]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.6.0.374
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

### Steps to reproduce the problem

- Create a new Rmd document using menu, and open in Visual mode
- it will be `html_document` by default. Save the file, for example `README.Rmd`
- Change the format to `github_document` and save. This will ask to reload 
![image](https://user-images.githubusercontent.com/6791940/167446069-e2de37a5-870f-4e25-9e95-6664a7964383.png)
- Clicking reload will throw the error
![image](https://user-images.githubusercontent.com/6791940/167446106-9cec32ab-565b-4474-8a97-be63f967e17d.png)

### Describe the problem in detail

Document can't be open in visual mode 

### Describe the behavior you expected

It should be possible to switch to visual mode. It seems like a regression. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Should be fixed here: https://github.com/rstudio/rstudio/commit/93a063c6b74b760a74b6aad19e32564af4febe1d

**Comment by romainfrancois** [comment]
Confirmed with RStudio 2022.06.0-daily+380
