### ISSUE TITLE
Quarto document rendered but not displayed

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11163]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.02.1+461 & 2022.02.2+485
    OS Version      : Multiple
    R Version       : Multiple

### Steps to reproduce the problem

Originally from https://github.com/quarto-dev/quarto-cli/issues/602 which has more detail, including Network information, but here are key posts:

----

[From @alexdeng]

On rstudio server, the viewer pane url is like /p/f425e0d9/
But the render job cannot find the html to serve

```
Watching files for changes
quarto.html
GET: / (404: Not Found)
```

Html exists and can be opened manually.

ps: I am running this with jupyterhub + server proxy. Shiny app and rmarkdown with knitr all works fine. Only quarto have this issue.

---

[From @alexdeng]

Okay. I think I found the issue: the default render button only will view localhost:port/ , instead of using the correct file hame. I changed my qmd file to index.qmd and now the viewer pane works with the render button. So the 404 was due to the url set to / and trying to find default index.html, not the correct qmd file output.

However, when I try rstudio locally, the behavior seems to be correct: I can see the http server using the correct
Watching files for changes
Browse at http://localhost:7233/quarto_proj.html
Quarto local is 0.9.178 on MacOS

When I do this on rstudio server (quarto 0.9.209)
Watching files for changes
quarto_proj.html
GET: / (404: Not Found)

---

[From @DavidPatShuiFong]

I had the same problem, but not on all platforms. Thanks @alexdeng for pointing out the solution!

HTML viewer works properly on Windows 10, RStudio 2022.02.2+485 "Prairie Trillium" using the "Enable Quarto preview" option in Global Options --- R Markdown --- Quarto (Quarto v0.9.348)

The HTML viewer says "not found" on Debian 11 (on a Crostinin container on an x86 Chromebook), RStudio 2022.02.2+485 "Prairie Trillium" using "Enable Quarto preview" option (Quarto v0.9.351)

The HTML viewer says "not found" on openSuSE 15.3 (x86), RStudio 2022.02.2+485 "Prairie Trillium" using "Enable Quarto preview" option

A simple

ln -s quarto_proj.html index.html

in the "Terminal" of RStudio can fix the problem by creating a symbolic link which points from index.html to quarto_proj.html (or whatever the name of the HTML file created by Quarto is)

### Describe the problem in detail

See above.

### Describe the behavior you expected

Show the rendering's output.

Triage note: Candidate for Spotted Wakerobin?

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Thanks @ronblum! I have spent a couple of hours attempting to repro this to no avail. It's likely there is some environmental or linux distro specific thing going on here. Let's try to address this is for SW but I can't do anything further without a repro.

**Comment by ronblum** [comment]
FWIW I tried on Debian 11 and openSUSE 15.3 (VMs, not containers), with no issue, using RStudio Server 2022.02.2+485.pro2. My environments might be too simple, though—I'll follow up and see if other configurations produce the issue.

**Comment by astayleraz** [comment]
I was unable to reproduce this issue with 2022.02.3 Build 489.pro1 on Sles15.3, Mac 11.6.5, and a proxy environment. I was able to successfully render and view the quarto file in all those cases.

**Comment by rhettdharrison** [comment]
I am not sure I understand this thread. However, I had the same problem. When I changed the name of the file to index.qmd, I was able to view the rendered document. I am using Ubuntu 20.04.5 LTS. Has this been fixed?

**Comment by baarthur** [comment]
I'm having the same issue here. It seems to be random; some days it works, some days it doesn't. 

My session info:

R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.2  here_1.0.1      fastmap_1.1.0   rprojroot_2.0.3 cli_3.6.0       htmltools_0.5.4
 [7] tools_4.2.2     rstudioapi_0.14 yaml_2.3.7      rmarkdown_2.20  knitr_1.42      xfun_0.37      
[13] digest_0.6.31   rlang_1.0.6     evaluate_0.20

**Comment by louisahsmith** [comment]
I'm suddenly having the same issue rendering a set of slides in a subdirectory of a quarto website. The preview worked fine until I closed RStudio and reopened it and re-rendered the document. I get "GET: / (404: Not Found)" but the .html file has been rendered. I'm using quarto version 1.3.353 and RStudio version 2023.03.1+446.

```
R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods  
[7] base     

loaded via a namespace (and not attached):
 [1] compiler_4.3.0   here_1.0.1       magrittr_2.0.3  
 [4] rsconnect_0.8.29 rprojroot_2.0.3  cli_3.6.1       
 [7] tools_4.3.0      glue_1.6.2       rstudioapi_0.14 
[10] yaml_2.3.7       stringi_1.7.12   stringr_1.5.0   
[13] lifecycle_1.0.3  rlang_1.1.1      renv_0.17.3   
```

**Comment by MSBack** [comment]
I am also having this issue. Let's say my file is called `hello.qmd`. The localhost address is pointing at
`localhost:port/web/viewer.html`
rather than:
`localhost:port/hello.html`

If I manually type the second address, preview works as expected.

**Comment by MSBack** [comment]
> Would the preview function need to (...would it be possible for it to...) figure out the name of the rendered document and make a more sophisticated address opening call than just `localhost:[randomport]/`?

You can fix the port by using the --port argument for `quarto preview`.

**Comment by MSBack** [comment]
> I am also having this issue. Let's say my file is called `hello.qmd`. The localhost address is pointing at `localhost:port/web/viewer.html` rather than: `localhost:port/hello.html`
> 
> If I manually type the second address, preview works as expected there.

It seems that this is the PDF viewer url, so the bug seems to be that Quarto fails to go back to the html url, after previously previewing a document as PDF. Can anybody reproduce this?

**Comment by MSBack** [comment]
Another debugging data point: opening `localhost:port` on my default browser (Firefox) incorrectly goes to:
`localhost:port/web/viewer.html`

Opening `localhost:port` in a private window in the same browser correctly goes to:
`localhost:port/hello.html`

**Comment by ablack3** [comment]
I'm having the same issue with RStudio Version 2023.06.0+421 (2023.06.0+421) on Mac OS 12.6

**Comment by mvf** [comment]
Same here with Quarto 1.3.433 on VS Code (OS: Void Linux) rendering to `.docx`.

**Workaround A**: Set an `output-dir` (sadly, `.` doesn't work):

```yml
project:
  output-dir: out
```

**Workaround B**: Run `Render DOCX` instead of `Render Project`.

This changes the `quarto preview` invocation as follows:

```diff
-quarto preview /path/to --render all --no-browser --no-watch-inputs
+quarto preview /path/to/my.qmd --to docx --no-browser --no-watch-inputs
```

`Render DOCX` won't auto-open the result, but it does produce a working `Browse at:` URL that ends with the file name.

**Comment by phamdn** [comment]
Same problem with docx output. `Render` with `Preview in Viewer Pane` only opens file with MS Word in the first time but not automatically in the next times.
