### ISSUE TITLE
`\dontshow{}` markup in documentation generates extra line in Help

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#11179]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for Ubuntu Bionic Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  Arch Linux 5.15.10-arch1-1
    R Version       :  4.1.2

### Steps to reproduce the problem

Just notice that documentation that uses the markup `\dontshow{}` will generate an extra line in the help page. This happens in RStudio but not in the R console.

### Describe the problem in detail

Take https://github.com/tidyverse/readr/blob/HEAD/R/write.R documentation examples' section:

https://github.com/tidyverse/readr/blob/85cf1e8e664e2a75eba393f91d89b39060140dab/R/write.R#L55-L71

Ask for its documentation: `?readr::write_delim`.

### RStudio

![snap-rstudio](https://user-images.githubusercontent.com/19862384/167859805-30cb97b3-92e3-4ad9-ba40-6920c36aae97.png)

### R console

![snap-r](https://user-images.githubusercontent.com/19862384/167859961-ff4c0715-2d57-46bc-ba03-650e7cd2403b.png)

### Describe the behavior you expected

I expected no extra line in RStudio help.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ramiromagno Thank you for raising this! I can reproduce this in RStudio Desktop 2022.06.0-daily-379/352 on MacOS 12.4 and Ubuntu 20.04.3. We'll review this as we continue development of RStudio.

**Comment by kevinushey** [comment]
You'll see the same behavior with R's built-in HTML help, e.g. from an R console:

```
options(help_type = "html")
?readr::write_delim
```

Since we're just using the R HTML help content as-is, I'd recommend filing this upstream with R Core.
