### ISSUE TITLE
Provide option to use web dialogs with Electron Desktop

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11184]
Electron has an issue on some Linux distros where the native dialogs don't display on top of the main window as they should: #11100. Although you can get to the dialogs, if you know to go looking for them, it's ugly.

We will hopefully get a fix for this from Electron (or make the fix ourselves), but if this doesn't happen in time for our first preview builds, I propose providing a user preference to tell Electron to use the RStudio Server web-based dialogs instead of the native ones.

This would have a secondary benefit in making it possible to use more of our existing Selenium automation for Electron testing (right now we don't have the ability for Selenium tests to query or operate the native dialogs).

**Comment by ronblum** [comment]
@gtritchie Does the recent Electron update fix this, or do we still need to rely on the option?

In any case, I've tested this, but I'm doing everything with that (mostly) to get some implicit testing.

**Comment by gtritchie** [comment]
The Electron issue is still open: https://github.com/electron/electron/issues/32857

**Comment by ronblum** [comment]
Verified in multiple environments:
- MacOS 12.5
- Red Hat 8.5
- Ubuntu 22.04
- Windows 11

Plus passive testing.
