### ISSUE TITLE
Dailly version of Rstudio cannot be installed on Ubuntu 20.04

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#11197]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily-396-amd64
    OS Version      : Ubuntu 20.04
    R Version       : 4.2.0

### Steps to reproduce the problem

Run the following commands:

```
wget https://s3.amazonaws.com/rstudio-ide-build/desktop/jammy/amd64/rstudio-2022.06.0-daily-396-amd64.deb
sudo dpkg -i rstudio-2022.06.0-daily-396-amd64.deb
rstudio
```

### Describe the problem in detail

The following error message appears and RStudio fails to start:

```
rstudio: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory
```

### Describe the behavior you expected

RStudio should either not install and state which dependency is missing or it should run.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Robinlovelace** [comment]
I did try installing the dependencies listed [here](https://github.com/rstudio/rstudio/blob/main/dependencies/linux/install-dependencies-bionic) and following these instructions but to no avail: https://stackoverflow.com/questions/54124906/openssl-error-while-loading-shared-libraries-libssl-so-3

**Comment by Robinlovelace** [comment]
Interestingly, I found that the Electron version works fine, starting with this URL: https://s3.amazonaws.com/rstudio-ide-build/electron/bionic/amd64/rstudio-2022.06.0-daily-396-amd64.deb

**Comment by jmcphers** [comment]
You're seeing this because you're installing the Ubuntu 22 ("jammy") build on an Ubuntu 20 ("bionic") system. I think you want one of these builds instead:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/bionic/

**Comment by Robinlovelace** [comment]
Thanks for quick response, testing now...

**Comment by Robinlovelace** [comment]
True that! Apologies and thanks :+1:

**Comment by jmcphers** [comment]
Whew, glad that's all it was!

**Comment by Robinlovelace** [comment]
And for completeness, this is what I saw:

```
rstudio                                 
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/xdg/xdg-ubuntu:/etc/xdg/rstudio/logging.conf'. Logging to '/home/robin/.local/share/rstudio/log/rdesktop.log'.
"Failed load Ace snippets for mode 'dcf'"
"Failed load Ace snippets for mode 'dcf'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'dcf'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
"Failed load Ace snippets for mode 'rd'"
[423034:423108:0512/234429.400896:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018

```

**Comment by gtritchie** [comment]
You downloaded the Ubuntu 22 ("Jammy") build which will not work on Ubuntu 20.

Use the "bionic" download, instead.
