### ISSUE TITLE
No autocomplete for data.table "by" or "keyby"

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#11202]
**Steps to reproduce:**
* Execute the following code:
```r
library(data.table)
dt <- data.table(
    col1 = 1:10,
    col2 = 101:110
)
```
* Try to get autocomplete for the column names for an operation like this:
```r
dt[, .N, by=col2]
```
That is, write `dt[, .N, by=col<position here>]` and press Tab.

**Expected behavior:** should bring up column names in the autocomplete.

**Actual behavior:** does not bring up column names in the `by` or `keyby` clauses of `data.table`, only in `i` and `j` (the ones that come before the 2nd comma).

I seem to recall the autocomplete worked correctly for `data.table` objects in earlier versions of rstudio.

**Setup:** RStudio 2022.02.1 Build 461, R 4.2.0, data.table 1.14.2

**Comment by ronblum** [comment]
Hi @david-cortes —I think I'm reproducing what you're seeing: The autocomplete shows this, which doesn't include `col1` or `col2`:

<img width="300" alt="Screen Shot 2022-05-13 at 9 15 53 AM" src="https://user-images.githubusercontent.com/31009952/168292511-8d44f0dc-64d9-4eb6-9ef4-878568adfc7c.png">

I get the same thing with earlier versions of RStudio, including 1.3.1093 and 1.4.1717. When I do the equivalent in R, outside of RStudio, I get:

<img width="609" alt="Screen Shot 2022-05-13 at 9 13 40 AM" src="https://user-images.githubusercontent.com/31009952/168293143-e8a67941-d0b1-4860-a77f-e9b8391cd3ea.png">

So I don't think this is an RStudio issue—it's the behavior of `data.table` in R.

**Comment by kevinushey** [comment]
RStudio does provide some extra autocompletion support for `data.table` beyond base R's completion system, so this would be an RStudio issue.

It looks like autocompletion works when following the comma here:

<img width="174" alt="Screen Shot 2022-05-13 at 11 46 55 AM" src="https://user-images.githubusercontent.com/1976582/168347805-2638b6e7-7114-4178-9c81-fd19ef17415a.png">

But not after `by =`:

<img width="199" alt="Screen Shot 2022-05-13 at 11 47 02 AM" src="https://user-images.githubusercontent.com/1976582/168347803-126c2ad4-3936-4f12-b9cd-b97ab3778dfa.png">

So, I think this could be considered a bug (or enhancement request) in RStudio's autocompletion support for `data.table`.

**Comment by kevinushey** [comment]
This is where we retrieve completion results for `data.table`:

https://github.com/rstudio/rstudio/blob/925ba91c701782b4a3b375fba7852df50b5652eb/src/cpp/session/modules/SessionRCompletions.R#L1231-L1259

But that routine never gets called for argument completions, which are handled via `.rs.getCompletionsArgument()`.

**Comment by ronblum** [comment]
I think I should stop trying to tag this issue. 😄

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2023.03.0-daily+272 on MacOS 13.2
- RStudio Server 2023.03.0-daily+272 on Ubuntu 20.04.5 via Chrome on MacOS 13.2
