### ISSUE TITLE
Include build number in rstudio.exe version info on Windows

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11205]
In the rstudio.exe's info on Windows, the version doesn't include the build number—for example, 2022.06.0.0 instead of 2022.06.0.333. It would be great to include the build number.

Note that we use it on MacOS:

<img width="236" alt="Screen Shot 2022-05-13 at 12 13 36 PM" src="https://user-images.githubusercontent.com/31009952/168324584-36aec143-6773-42fd-bc75-d865e78bc593.png">

[Brought over from #11035.]

**Comment by gtritchie** [comment]
This is (mostly) fixed for Elsbeth Geranium. We now show the full version in the Product Version field.

Here's 2022.07:
![screenshot of RStudio 2022.07 version panel](https://user-images.githubusercontent.com/10569626/204024995-35cd6e5e-3451-4258-ab2a-675986736d15.png)

Here's 2022.12:
![screenshot of RStudio 2022.12 version panel](https://user-images.githubusercontent.com/10569626/204025068-772f622f-1cd3-4257-95f9-393f706de478.png)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.12.0-preview+346 on Windows 11.
