### ISSUE TITLE
Produce builds for Red Hat 9

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11215]
Produce builds for Red Hat 9. The RHEL 8 builds result in `libssl.so.1.1` errors.

See also #11140.

Triage: I think this goes in Spotted Wakerobin, but I'm not certain.

**Comment by mikebessuille** [comment]
We'll build Red Hat 9 builds for SW, and will release dailies, but we won't test against it yet and won't add official support for it in SW, yet.

**Comment by gtritchie** [comment]
I believe we can use the Fedora 36 builds as our RHEL9 builds. In my initial experiments our daily Fedora 36 builds are installing and running fine on RHEL9.

Otherwise we'd have to figure out what Docker base to use for the builds. Either by licensing RHEL9 or waiting on Rocky Linux 9, etc.

**Comment by gtritchie** [comment]
Moving to "test". I was able to install and run Fedora 36 daily of Qt Desktop, Electron Desktop, and Open-Source Server (after disabling SELinux) on RHEL 9.

@ronblum Up to you if want to do your own testing of this, or just go ahead and Trust Me?

**Comment by mikebessuille** [comment]
since it's not being explicitly QA'd or released for SW, I suggest you close this.
