### ISSUE TITLE
Issue while executing JDBC in RStudio

### ISSUE THREAD

**Issue by DIPANKARDOLEY** [rstudio/rstudio#11219]
### System details

    RStudio Edition : Desktop 
    RStudio Version : RStudio-2022.02.2-485
    OS Version      : Windows 10 Enterprise
    R Version       : 4.2

### Steps to reproduce the problem
Specifying a Databse URL, User Name, and Password to connect to DB

library(RJDBC)
dns <-  "jdbc:oracle:thin:@myhost:1521:orcl""
address <- "C:\\Users\\ojdbc6.jar"
username <- "usename"; password <- "mypassword"
drv <- RJDBC::JDBC("oracle.jdbc.OracleDriver",address) **_# Error occurs here_**
con <- dbConnect(drv,dns,username,passsword)

### Describe the problem in detail
Updated the Rstudio to the latest version mentioned above and started facing this issue. Rstudio abruptly throws and fatal error and terminates.
If I run the same Code in R Core (Base R 4.2) then the issue does not appear and gets connected smoothly. The error occurs only while executing through the IDE mentioned above

### Describe the behavior you expected
I was expecting a smooth connection to the DB as earlier versions of Rstudio as well as R was able to do so. It still does wit R 4.2 but only on the base or core R console and not on Rstudio IDE

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
<img width="450" alt="Capture" src="https://user-images.githubusercontent.com/8094219/168683230-a57408f4-b6f2-4f79-9528-52737b8ec8f6.PNG">

**Comment by ronblum** [comment]
@DIPANKARDOLEY Thank you for raising the issue! A couple of questions:
1) What was the last version of RStudio Desktop in which this worked?
2) Is the issue only with R 4.2.0, or is it a problem with earlier versions of R? If you have multiple versions of R installed, you can control which one RStudio Desktop uses at <kbd>Tools -> Global Options -> General -> Basic -> R Version</kbd>.

Thanks!

**Comment by DIPANKARDOLEY** [comment]
Ans 1: A version which i installed somewhere in 2021. Sorry don't exactly remember which one
Ans2:  Yes. With R 3.6.3 it works perfectly fine with the latest Rstudio 485. That's what I am doing interim to pull the data. But few libraries that I am using doesn't gets install due to dependencies for which I have to keep switching for my work :)

**Comment by ronblum** [comment]
It looks like [a related issue ](https://community.rstudio.com/t/rstudio-crashes-when-running-sys-getlocale-lc-messages-but-rgui-and-rscript-work-fine/136743) was posted in the RStudio Community, along with #11076. The problems there appear to be addressed with a [patched version of R 4.2.0](https://cran.r-project.org/bin/windows/base/rpatched.html). Does that resolve the problem you're encountering?

**Comment by DIPANKARDOLEY** [comment]
@ronblum , Thanks you pointing me out on this. The patched version works. Will keep using it till it stablishes or version changes. Thanks for the help

**Comment by ronblum** [comment]
@DIPANKARDOLEY I'm glad it's working, and thanks for the update, which will help anyone else who might run into the issue! :)
