### ISSUE TITLE
Desktop Electron create the files in %APPDATA% instead of XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by firezblade** [rstudio/rstudio#11229]
### System details

    RStudio Edition : Desktop Electron
    RStudio Version :  2022.06.0-daily-416
    OS Version      :  Windows 8.1
    R Version       :  4.2.0

### Steps to reproduce the problem

SET XDG_CONFIG_HOME=D:/xdgconfighome

SET XDG_DATA_HOME=D:/xdgdatahome

START D:\RStudio\rstudio.exe

### Describe the problem in detail

%APPDATA%\RStudio contains:- folders like blob_storage and files like config.json, Local State, Preferences

D:\xdgconfighome\RStudio contains:- folders like dictionary and files like crash-handler, rstudio-prefs.json

D:\xdgdatahome\RStudio contains:- folders like bibliography-index and files like rstudio-desktop.json

### Describe the behavior you expected

Do not create %appdata%\RStudio

Create everything else in either D:\xdgconfighome\RStudio or D:\xdgdatahome\RStudio

Are there any other environment variables i can use to enable this?

Thanks!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@firezblade Thank you for raising this! Does it work as you expect in the non-Electron version of RStudio Desktop?

**Comment by firezblade** [comment]
No it doesn't. For the non electron version,

%APPDATA%\RStudio contains:- the file desktop.ini only

XDG_DATA_HOME\RStudio and XDG_CONFIG_HOME\RStudio contains their usual stuff.

Is it possible to create desktop.ini inside XDG_CONFIG_HOME\RStudio or XDG_DATA_HOME\RStudio?

Thanks!

**Comment by nouvrita** [comment]
Hello I would like to reopen this issue. Rstudio cannot be truly portable : it still writes some files in %APPDATA% eventhough RSTUDIO_CONFIG_HOME and RSTUDIO_DATA_HOME are defined elsewhere.
Tested on latest build 2026.05.0+218 on win11 24H2

**Comment by kevinushey** [comment]
Can you please create a new issue, referencing the specific files that are being written to %APPDATA%?

**Comment by nouvrita** [comment]
It's no longer necessary to repoen it. I think I found a solution with this closed issue  : https://github.com/rstudio/rstudio/issues/17584
I can use --user-data-dir when launching rstudio to redirect all the electron files elsewhere and it's working great. Here is a bat script to launch R and Rstudio in a folder and all written files stay inside :

```
@echo off

SET "ROOT=%~dp0"

SET "R_USER=%ROOT%"

SET "RSTUDIO_WHICH_R=%ROOT%R\R-4.6.0\bin\x64\Rterm.exe"
SET "R_LIBS_USER=%ROOT%R\R-4.6.0\library"

SET "XDG_CONFIG_HOME=%ROOT%RStudio\config"
SET "XDG_DATA_HOME=%ROOT%RStudio\data"
SET "XDG_CACHE_HOME=%ROOT%RStudio\cache"

SET "TEMP=%ROOT%RStudio\tmp"
SET "TMP=%ROOT%RStudio\tmp"

:: Default : %appdata%\RStudio
SET "RSTUDIO_CONFIG_HOME=%ROOT%RStudio\config"
:: Default %localappdata%\RStudio
SET "RSTUDIO_DATA_HOME=%ROOT%RStudio\data"

:: Defaut for --user-data-dir : %appdata%\RStudio
:: Default for --log-dir : %localappdata%\RStudio\log
START "" "%ROOT%RStudio\RStudio-2026.04.0-526\rstudio.exe" --user-data-dir="%ROOT%RStudio\electron" --log-dir="%ROOT%RStudio\log"
```

I checked with Process Monitor by filtering the process `rstudio.exe `and `rsession-utf8.exe` for `WriteFile` operations and the only files getting created outside of the folder are cache shaders :)
