### ISSUE TITLE
Newline after logical operators chooses a bad line break

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#11227]
**Steps to reproduce:**
* Write the following code:
```r
df <- data.frame(col1 = 1:10)
df[
    col1 < 5 &<position here>
]
```
* Put the typing focus where it says `<position here>` and press Enter.

**Expected behavior:**
```r
df <- data.frame(col1 = 1:10)
df[
    col1 < 5 &<position here>
    <Focus should be here>
]
```

**Actual behavior:**
```r
df <- data.frame(col1 = 1:10)
df[
    col1 < 5 &<position here>
        <Focus is here>
]
```

**Setup:** RStudio 2022.02.2 Build 485.

**Comment by kevinushey** [comment]
To confirm, if I understand correctly, you'd prefer that we didn't apply an extra level of indent for boolean operators like `|` and `&`?

In other words:

```
# correct
1 +
  2 + 
  3

# incorrect
4 &
  5 &
  6
```

**Comment by david-cortes** [comment]
That was indeed a bad description - I would also prefer it to keep the same indentation level for mathematical operators - e.g.
```r
plt <- (
    ggplot(df, aes(...)) +
    theme_bw() +
    geom_smooth() +
    ...
)
```

And would prefer it to add a single extra extra indentation for pipe operators - e.g.
```r
df %>%
    some_fun() %$%
    some_col %>%
    hist()
```
