### ISSUE TITLE
Copy-paste on first word of line reindents code

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#11226]
**Steps to reproduce:**
* Write the following code:
```r
library(data.table)
dt <- data.frame(col1=1:10)
dt[
    col1 < 2 |
    col2 > 8
]
```
* Copy `col1` to the clipboard.
* Double-click on where it says `col2` in the code so as to select it.
* Execute the paste shortcut (Ctrl + V).

**Expected behavior:** should replace `col2` with the contents of the clipboard and nothing else.

**Actual behavior:** replaces the selected text **AND** reindents the line.

**Setup:** RStudio 2022.02.2 Build 485.

**Comment by kevinushey** [comment]
This behavior is controlled by the "Auto-indent code after paste" preference:

<img width="608" alt="Screen Shot 2022-05-17 at 2 02 01 PM" src="https://user-images.githubusercontent.com/1976582/168909570-a7c50ee5-d05e-464b-b45e-1cf48540c0c5.png">

You might want to disable that.

We could also consider whether we should reindent on paste if the user already has some text selected. We could probably infer that re-indenting the line is undesired if the selection is non-empty but only spans a single line.

**Comment by david-cortes** [comment]
But I *do* want code to be reintended after pastying full lines, just do not want it to reindent when I am replacing a single word within a line.
