### ISSUE TITLE
Use multiple languages / spell check

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#11222]
Hi,

I work in multiple languages. When writing .Rmd files, sometimes, I'd like to have spell check for 2 languages at the same time. It is not very easy to switch.

Could you consider adding the dictionnary language as a project option?

Thanks

**Comment by ronblum** [comment]
@olivroy Thank you for the suggestion! We'll consider it as part of our ongoing development of RStudio.

**Comment by ncotie** [comment]
I would like to second the suggestion, it would be very helpful.  Pretty much anywhere outside the english-speaking world, RStudio users will often be using a mix of languages in their .Rmd.
Thanks
