### ISSUE TITLE
Rstudio IDE second popup masks help text in the first 

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/rstudio#11224]
### System details

RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for Ubuntu Bionic
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

R Version: Bird Hippie    
### Steps to reproduce the problem
1. Write R code inside a .R file.
2. Type a function name followed by `(`
3. press tab and wait

### Describe the problem in detail
The masking problem is clear in this screenshot and detailed description in this rstudio community post.
![Screenshot 2022-05-17 at 11 57 20 PM](https://user-images.githubusercontent.com/3091624/168890181-1e2e25f8-c2bd-46f0-bf31-dc15c3c69b8c.png)

https://community.rstudio.com/t/rstudio-editor-type-ahead-popup-masking-help-text/135510?u=sanjmeh

### Describe the behavior you expected
I expect the second popup to be moved a little outside so that it is not hidden by the first popup.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists. [ *installed a version recently*]
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! Some things that might help us reproduce this locally, or learn more...

- Does the issue depend on what font is being used in the editor? Does changing the font in Tools -> Global Options... -> Appearance make a difference? (Similarly, does it depend on the font size?)
- Are you using a Macbook? Are you using it docked with external monitors, or just by itself? Similarly, are you using the trackpad or an external mouse? (Sometimes issues of this form come from us incorrectly computing the size of the scrollbars, and whether those scrollbars are presented can depend on a variety of factors)
- Can you clarify a bit more how you're connecting to RStudio Server? It sounds like you're using a macOS machine, and then connecting to an RStudio Server instance that's running on Ubuntu Bionic?

**Comment by sanjmeh** [comment]
Yes I use mac computers (I swap between two machines) and yes I also use external monitor (when i use my macmini). I always connect to rstudio server on ubuntu (now 20 but the problem has been on ubuntu 16 as well). This problem is not on local machine R. I will do all your suggested trials systematically and try to replicate the problem. Please hold on till then.
Thanks

**Comment by sanjmeh** [comment]
So I have tested on both : External monitor and a mac screen. And I get the problem in both.
Below are two screenshots : both from my mac, but in two screen resolutions. The problem stayed in both resolutions.
It is still a mystery why the problem vanishes form time to time and resurfaces. 
![Screen Shot 2022-05-28 at 4 59 20 PM](https://user-images.githubusercontent.com/3091624/170823742-57f74602-cd45-4c38-b351-623f7d0e9769.png)
![Screen Shot 2022-05-28 at 5 03 41 PM](https://user-images.githubusercontent.com/3091624/170823745-e399247f-f25b-44ed-8815-9655fb2c38f7.png)

**Comment by kevinushey** [comment]
I saw this recently on a Windows VM as well; I'm going to mark as SW for further investigation.

**Comment by sanjmeh** [comment]
The problem continues on both MACs.

**Comment by sanjmeh** [comment]
> The problem continues on both MACs.

Still continues

**Comment by sanjmeh** [comment]
I have not seen this in recent versions of rstudio. Hence closing this due to lack of replication.
