### ISSUE TITLE
`.Call` crashes R session in RStudio on M1 Mac

### ISSUE THREAD

**Issue by ahl27** [rstudio/rstudio#11233]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+128, also tested on release version 2022.02.2+485
    OS Version      : MacOS Monterey 12.3.1
    R Version       :  4.2.0 Patched (2022-05-09 r82330)

### Steps to reproduce the problem

1. Compile any R-compatible C code into an object file with `R CMD SHLIB <file.c>`
   - Tested with my own code as well as the example from the [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Calling-_002eCall)
2. Load the object file with `dyn.load("path/to/file.so")`
3. Execute any `.Call` method from within the RStudio Console

Example execution from the [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Calling-_002eCall) `convolve` function:

```
conv <- function(a, b) .Call("convolve2", a, b)

v1 <- 1:5
v2 <- 6:10
conv(v1, v2)
```

### Describe the problem in detail

This is a fairly basic problem, but I haven't been able to find anything to solve it online, and I suspect it has something to do with M1 architecture. Any call to `.Call(...)` immediately crashes the R session with the standard "R session aborted: R has encountered a fatal error" message. The weirdness here is that I can execute any `.Call(...)` calls from within R sessions launched in the terminal, and also from R sessions launched within the Terminal pane of RStudio. The only time this crashes is when the commands are called through the RStudio Console. I'm also still able to run functions from pre-built packages that utilize `.Call`.

This behavior is consistent across release RStudio and the daily RStudio Electron builds. I had initially thought the bug was due to my C code having issues, but this bug persists even with example code taken directly from the official R docs. This happens even when the C function called does nothing. I've tested with just the following and it still crashes:

`testing.c`:
```
#include <R.h>
#include <Rdefines.h>
#include <Rinternals.h>

SEXP dummyFxn(){
    SEXP retval = allocVector(REALSXP, 1);
    return(retval);
}
```
`Rscript`:
```
dyn.load('.../testing.so')
.Call("dummyFxn")
```

I've included a diagnostics report as well as the result of `Sys.getenv()` both inside and outside RStudio. I'm not sure how to provide additional diagnostic info given that I can only reproduce the bug within RStudio, and calling any C function via `.Call` immediately crashes the R session, but I'm happy to provide more details if necessary. 

### Describe the behavior you expected

`.Call` should execute successfully in the same way it does from running `.Call(...)` within an R session launched on the terminal.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/8718828/diagnostics-report.txt)
[Sysgetenv_insideRStudio.txt](https://github.com/rstudio/rstudio/files/8718859/Sysgetenv_insideRStudio.txt)
[Sysgetenv_outsideRStudio.txt](https://github.com/rstudio/rstudio/files/8718860/Sysgetenv_outsideRStudio.txt)

**Comment by kevinushey** [comment]
Here's a reproducible example that works fine for me; self-contained in one R script:

`````
owd <- setwd(tempdir())

script <- '
#include <R.h>
#include <Rinternals.h>

SEXP convolve2(SEXP a, SEXP b)
{
    int na, nb, nab;
    double *xa, *xb, *xab;
    SEXP ab;

    a = PROTECT(coerceVector(a, REALSXP));
    b = PROTECT(coerceVector(b, REALSXP));
    na = length(a); nb = length(b); nab = na + nb - 1;
    ab = PROTECT(allocVector(REALSXP, nab));
    xa = REAL(a); xb = REAL(b); xab = REAL(ab);
    for(int i = 0; i < nab; i++) xab[i] = 0.0;
    for(int i = 0; i < na; i++)
        for(int j = 0; j < nb; j++) xab[i + j] += xa[i] * xb[j];
    UNPROTECT(3);
    return ab;
}
'

writeLines(script, con = "convolve.c")

system("R CMD SHLIB convolve.c")
dyn.load("convolve.so")

conv <- function(a, b) .Call("convolve2", a, b)

v1 <- 1:5
v2 <- 6:10
conv(v1, v2)
`````

With relevant output:

```
> system("R CMD SHLIB convolve.c")
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c convolve.c -o convolve.o
clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o convolve.so convolve.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
> dyn.load("convolve.so")
> conv <- function(a, b) .Call("convolve2", a, b)
> v1 <- 1:5
> v2 <- 6:10
> conv(v1, v2)
[1]   6  19  40  70 110 114 106  85  50
```

**Comment by ahl27** [comment]
<img width="1199" alt="Screen Shot 2022-05-18 at 17 44 12" src="https://user-images.githubusercontent.com/30053966/169160944-e7c40041-a914-4414-b0ab-97e6b1b2610a.png">

I got the same error--maybe it's an issue with my machine?

**Comment by kevinushey** [comment]
Are you using the same version of R to generate the shared library as the one being used by RStudio?

I saw the error at first when I tried switching to Homebrew R, but this fixed it:

`````

owd <- setwd(tempdir())

script <- '
#include <R.h>
#include <Rinternals.h>

SEXP convolve2(SEXP a, SEXP b)
{
    int na, nb, nab;
    double *xa, *xb, *xab;
    SEXP ab;

    a = PROTECT(coerceVector(a, REALSXP));
    b = PROTECT(coerceVector(b, REALSXP));
    na = length(a); nb = length(b); nab = na + nb - 1;
    ab = PROTECT(allocVector(REALSXP, nab));
    xa = REAL(a); xb = REAL(b); xab = REAL(ab);
    for(int i = 0; i < nab; i++) xab[i] = 0.0;
    for(int i = 0; i < na; i++)
        for(int j = 0; j < nb; j++) xab[i + j] += xa[i] * xb[j];
    UNPROTECT(3);
    return ab;
}
'

writeLines(script, con = "convolve.c")

# make sure we're using the same version of R that's currently active
# when compiling the shared library
R <- file.path(R.home("bin"), "R")
system(paste(R, "CMD SHLIB convolve.c"))
dyn.load("convolve.so")

conv <- function(a, b) .Call("convolve2", a, b)

v1 <- 1:5
v2 <- 6:10
conv(v1, v2)
`````

It wasn't clear to me from your issue how you're compiling and preparing the shared object to be loaded into R, but this could be the culprit.

**Comment by ahl27** [comment]
Ah you're a genius, that worked! Thank you so much, it looks like my terminal is calling from Homebrew R, but the RStudio is getting it from `/Library/Frameworks/R.framework/Resources/bin/R`. I'll just change the terminal to use that R installation and work on removing the duplicates from my system.

Thanks again!
