### ISSUE TITLE
Unable to create new Quarto project after restarting R

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#11232]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.06.0 Build 418
    OS Version      : ubuntu20
    R Version       : 4.1.0

### Steps to reproduce the problem
1. session dropdown -> restart R 
2. create new project in new directory
3.  select quarto project and input project name 
4. click create project

### Describe the problem in detail
an error pops up stating R session has crashed

<img width="732" alt="Screen Shot 2022-05-18 at 9 33 08 AM" src="https://user-images.githubusercontent.com/43964690/169067991-ec41a5e7-5a00-48fb-b127-8ec61d234e10.png">

### Describe the behavior you expected
user is able to create quarto project

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
Failing test.
Test passed here:
2022-06-0-daily+411
Started to fail here:
2022-06-0-daily+415
JJ pointed to this commit on it:https://github.com/rstudio/rstudio/compare/9ae42299...85c5a549

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/rstudio/commit/1d9d841390dab07158cd119397c30949552129d9

**Comment by astayleraz** [comment]
### Verified Fixed
    RStudio Edition    :  Server / Workbench
    RStudio Version(s) : 2022.06.0-daily+505.pro1
    OS Version         : ubuntu20

### Automated tests 
Our automation coverage around this that was failing has been passing for some time now. Closing the issue as fixed.
