### ISSUE TITLE
Choose R Version cannot select network executables

### ISSUE THREAD

**Issue by matheustavaresdev** [rstudio/rstudio#11247]
### System details
```
RStudio Edition : Desktop (Electron)
RStudio Version : 2022.06.0-daily+374 (Electron)
OS Version      : Windows 11
R Version       : Multiple
```
### Steps to reproduce the problem
1) Have a R version installed into a network drive
2) Browse to it on `Choose R Installation` modal
3) Select a `R.exe`
### Describe the problem in detail
When the executable is selected, this error shows up:
![image](https://user-images.githubusercontent.com/36674530/169360093-c94ffe18-7711-42a5-b34d-ffd08a23744e.png)

### Describe the behavior you expected
That executable should be selected and used with no errors.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
This is no longer an issue if the default version of R is on a network drive, and the default version of R is selected in the dialog.

However, now the network version of R no longer shows up in the list of available R binaries. @matheustavaresdev was this intentional?

**Comment by matheustavaresdev** [comment]
@ronblum Please see https://github.com/rstudio/rstudio/pull/11168#issuecomment-1129131395 . We have agreed not to have the need of the new path being added to the list, only for it to be used. Just tested here and both network and mapped drivers are working here

**Comment by ronblum** [comment]
Verified that this is now expected behavior. Done!
