### ISSUE TITLE
Implement acceptNavigationRequest in Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11252]
In the Qt desktop app we restrict what can load in a window here: https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/cpp/desktop/DesktopWebPage.cpp#L402-L404

This only has a skeleton implementation in Electron, here: https://github.com/rstudio/rstudio/blob/ecd67f3bf4ed54ca704a8f765683b135a7bda277/src/node/desktop/src/main/desktop-browser-window.ts#L167-L169

Among other things, we need to implement various callbacks that communicate valid URLs, then use this information:

https://github.com/rstudio/rstudio/blob/ecd67f3bf4ed54ca704a8f765683b135a7bda277/src/node/desktop/src/main/gwt-callback.ts#L769-L786

**Comment by timtmok** [comment]
The last automation run on `main` has passed all tests.

For the most part, the changes for this ticket shouldn't be much different. The main part is any of the panes will check what is being loaded and ensure it is approved content coming from the IDE. The other piece is it will launch any external URLs displayed in panes in the web browser.

A related issue is #11611 where clicking an external link crashes the IDE. This still needs a solution but is related to Electron not supporting the `will-frame-navigate` event. We need to detect the click on the external link and open it in the user's default web browser.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0 Build 178
windows11, Ubuntu 22.04

Tested several different pages, links and file types.
