### ISSUE TITLE
Implement (or deprecate) Tools / Shell for Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11253]
On RStudio Desktop there is a command, Tools / Shell... that opens an operating-system terminal (outside RStudio). This predates the addition of the built-in terminal pane.

This isn't implemented in Electron and is a no-op.

We've talked about removing this for years, here's the Big Chance.

If we want to keep it, we need to implement the callback here: https://github.com/rstudio/rstudio/blob/ecd67f3bf4ed54ca704a8f765683b135a7bda277/src/node/desktop/src/main/gwt-callback.ts#L596-L598

This command also appears on the tools dropdown in the version-control pane (git or svn):

![screenshot showing the command's location in the version control pane](https://user-images.githubusercontent.com/10569626/174866326-20a8ae5a-890c-4591-a19f-43519caa3322.png)

If we deprecate Tools/Shell, then we should probably put the Terminal command in its place on this dropdown. It's not uncommon to need to go to the command-line to perform version control operations that our UI doesn't expose.

**Comment by mikebessuille** [comment]
let's take this out.

**Comment by gtritchie** [comment]
See also: #1977

**Comment by ronblum** [comment]
Verified remove in RStudio Desktop 2022.10.0-daily-9 Elsbeth Geranium on MacOS 12.5. I'm leaving this open because I'd like to double-check this on Windows and Linux, which might be overkill, but I just want to make sure.

**Comment by ronblum** [comment]
Checked the following:
1) Shell is no longer in <kbd>Tools</kbd>
2) Shell is no longer in <kbd>Git Pane -> Gear icon</kbd>
3) New Terminal is in <kbd>Git Pane-> Gear icon</kbd> and creates new terminal
4) Shell is unavailable in Command Palette

![tools_menu.png](https://codetreeusercontent.s3.amazonaws.com/uploads/49f52414-71b5-4961-8441-e2a35f510fb3/tools_menu.png)

![git_pane.png](https://codetreeusercontent.s3.amazonaws.com/uploads/49f52414-71b5-4961-8441-e2a35f510fb3/git_pane.png)

![command_palette.png](https://codetreeusercontent.s3.amazonaws.com/uploads/49f52414-71b5-4961-8441-e2a35f510fb3/command_palette.png)


Checked in RStudio Desktop 2022.10.0-daily+55 on MacOS 12.5. Still need to check in Windows and Linux.

**Comment by jonvanausdeln** [comment]
Verified on Windows 11 and Ubuntu 22.04
