### ISSUE TITLE
Problems opening files from Explorer/Finder/etc. (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11251]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+421
    OS Version      : Any
    R Version       : Any

### Overview

Various scenarios opening files in RStudio from the operating system: goal is for Electron to behave the same as Qt on Mac, Linux, and Windows.

#### Steps to reproduce the problem

- ensure RStudio is not running
- double-click on an `*.RProj` file

#### Describe the problem in detail

- working correctly with Electron (including for completeness)
- Mac: ✅
- Linux: ✅
- Windows: ✅

#### Describe the behavior you expected

- the IDE starts and loads the project

#### Steps to reproduce the problem

- ensure RStudio is running
- double-click on an `.RProj` file

#### Describe the problem in detail

- working correctly with Electron (including for completeness)
- Mac: ✅
- Linux: ✅
- Windows: ✅

#### Describe the behavior you expected

- a new instance of the RStudio starts and loads the project
- this happens even if the project is already open in another instance
- in Desktop Pro (once implemented for Electron), also test `.rdprsp` files behave the same way and trigger a new instance

#### Steps to reproduce the problem

- start RStudio and make sure it doesn't have the file open that you're going to double-click on in next step
- close RStudio
- double-click on a file associated with RStudio such as a `*.R`, `*.Rmd`, etc.; might have to right-click and use "Open With..." depending on the file type and what other programs are installed

#### Describe the problem in detail

- Mac: ✅
- Linux: ✅
- Windows: ✅ (tracked separately via #11369)
   - RStudio starts, the editor region displays (blank), and an error shows "Error while opening file" : "The system cannot find the file specified."
   - After closing the error message dialog, the blank editor region remains

![windows-file-open-error](https://user-images.githubusercontent.com/10569626/169410649-21ae2ed7-52a8-4d77-8c98-3ca3c23f384f.png)

#### Describe the behavior you expected

- the IDE starts and loads the file, even on an obscure platform like Microsoft Windows

#### Steps to reproduce the problem

- start RStudio and make sure it doesn't have the file open that you're going to double-click on in next step
- keep RStudio running
- double-click on a file associated with RStudio such as a `*.R`, `*.Rmd`, etc.; might have to right-click and use "Open With..." depending on the file type and what other programs are installed

#### Describe the problem in detail

- Mac: ✅
- Linux: ❌ 
  - A new instance of RStudio is opened, and it opens the file, instead of opening in the existing instance
- Windows: ❌  (not fixed via #11369)
  - A new instance of RStudio is opened, and it fails to open the file with same error message as scenario (3) above

#### Describe the behavior you expected

- the existing instance of RStudio loads the file
- if there are multiple instances of RStudio running, whichever one ends up targeted should open the file

#### Steps to reproduce the problem

- start RStudio and open a file such as an `*.Rmd`
- keep RStudio running
- double-click on that same file from operating system

#### Describe the problem in detail

- Mac: ✅
- Linux: ❌ 
    - A new instance of RStudio is opened, and it opens the file, instead of just bringing the existing instance to the front
- Windows: ❌  (not fixed via #11369)
    - A new instance of RStudio is opened, and it fails to open the file with same error message as scenario (3) above

#### Describe the behavior you expected

- the existing instance is brought to the front but otherwise nothing happens
- if there are multiple instances of RStudio running, then whichever one ends up targeted should have the double-clicked file opened and be brought to the front

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
The code in Qt desktop for dealing with routing requests to an existing instance were not ported to Electron. The hope is we can reimplement using the Electron requestSingleInstanceLock API: https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata

The Qt code is:

https://github.com/rstudio/rstudio/tree/main/src/cpp/desktop/3rdparty/qtsingleapplication
https://github.com/rstudio/rstudio/blob/df26d2643ffecc0b1f4b5c8e99bb6dc1a81d30a8/src/cpp/desktop/DesktopPosixApplication.hpp#L26
https://github.com/rstudio/rstudio/blob/df26d2643ffecc0b1f4b5c8e99bb6dc1a81d30a8/src/cpp/desktop/DesktopWin32ApplicationLaunch.cpp#L27-L38

**Comment by timtmok** [comment]
PR has been merged and building. I want to run a check on the Linux build to see if the Windows fix also covers it.

**Comment by timtmok** [comment]
Scenarios 4 and 5 appear to work for Linux as well with this change. The PR outlines some detail about testing. These scenarios should be working in Linux and Windows now.

Debug logs for desktop will show which process has the instance lock, which determines if it is the process that will respond to an open with request. Open project files will always open in a new instance.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-101
Windows 11, Ubuntu 22.04

Tested all above scenarios as well as those mentioned in PR.
