### ISSUE TITLE
RStudio still freezes after waking up from sleeping/hibernation

### ISSUE THREAD

**Issue by EvoLandEco** [rstudio/rstudio#11266]
I've had this issue for a long time, across different win10/win11 versions and RStudio versions. It is hard to say how to reproduce the issue for sure, but it happened many times after I woke up my laptop,

I just bought a brand new win11 laptop, installed the latest version of RStudio, started coding in RStudio, closed the laptop screen, let it enter sleeping mode (in power management it says sleep, not hibernate). One day after, I waked my laptop up, and RStudio was frozen. 

The cursor was frozen and the whole UI did not respond.

I'd like to know is there a solution to this problem? It makes RStudio unusable as I often put my laptop into sleeping mode, and I'd lose progress if RStudio freezes after waking up. Or at least, is this issue already captured in testing, and is there a plan to fix it? Seems that the same issue was opened and closed various times here, but now with the latest laptop model, latest OS, and brand new installations of all the software and packages, the same issue still exists.

**Comment by ronblum** [comment]
Thanks for the information, @EvoLandEco! Sorry for the impact that this is having.  I'm closing this as a duplicate to consolidate this issue under one ticket, #10831.
