### ISSUE TITLE
RStudio forcibly executes bash files that it finds under conda folders

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#11263]
**Steps to reproduce:**
* Install anaconda (python distribution).
* If desired, add anaconda's python installation path to one's `PATH` environment variable, but do NOT add any automated script from conda to one's `.profile` or `.bash_profile`.
* To make things more clear, modify the bash files that anaconda provides for setting up commands like `conda activate` - e.g. make them print some message (e.g. `echo "this file is being executed" > ~/ran_script.txt`), so that it becomes clear when they are executed.
* Launch RStudio (doesn't matter if it will launch opening a python file or not).

**Expected behavior:** Should try to detect my python interpreters according to what I have configured in my `PATH`, and **in no event** should it execute bash scripts found somewhere within my computer, exept for `~/.profile`, `~/.bash_profile` and similar (which should have already been executed by the time rstudio is launched).

**Actual behavior:** Executes bash scripts from the anaconda installation without my consent:
```
/tmp/RtmpBr14AN/file27c4f7227c5a87.sh: 5: /home/david/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) :
  running command ''/usr/bin/sh' /tmp/RtmpBr14AN/file27c4f7227c5a87.sh' had status 2
```

**Setup:** RStudio 2022.02.2 Build 485.

**Comment by ronblum** [comment]
@david-cortes Thank you for raising this!

**Comment by kevinushey** [comment]
I'm pretty sure this is coming from `reticulate`, not RStudio:

https://github.com/rstudio/reticulate/blob/a4c7184fbb0bb0fa40af340bd3c2d5a16b34b323/R/config.R#L561-L575

And that would be getting executed when RStudio is trying to figure out what copies of Python are available on the system.

**Comment by david-cortes** [comment]
@ronblum It didn't use to happen with earlier versions of RStudio.

@kevinushey I tried removing `reticulate` and still experience the issue.

**Comment by kevinushey** [comment]
The exact same error? This is presumedly coming from reticulate:

```
Error in Sys.setenv(PATH = new_path) : wrong length for argument
```

**Comment by david-cortes** [comment]
I think I might not have removed `reticulate`. Just noticed that I also had a system install from the debian package manager. Tried now reinstalling from `install.packages` and the error does not happen at startup anymore, but it does happen when I load `reticulate` through `library(reticulate)`.

**Comment by kevinushey** [comment]
If it is indeed being caused by `reticulate`, then you may be able to reproduce with something like `reticulate::py_discover_config()`.

**Comment by TongJin7** [comment]
I've met similar problem. It happened when I use reticulate in Rsudio under R version 4.1.0.
`> reticulate::py_config()
/tmp/RtmpuNaxqG/file155d27ec8ac.sh: 4: /home/rtt/miniconda3/envs/r410/etc/conda/deactivate.d/deactivate-r-base.sh: [[: not found
/tmp/RtmpuNaxqG/file155d27ec8ac.sh: 5: /home/rtt/miniconda3/envs/r410/etc/conda/deactivate.d/deactivate-gxx_linux-64.sh: Syntax error: "(" unexpected
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) :
  running command ''/bin/sh' /tmp/RtmpuNaxqG/file155d27ec8ac.sh' had status 2`
And is the problem solved? Thanks!

**Comment by TongJin7** [comment]
I've met a similar problem. It happened when I use reticulate in Rsudio under R version 4.1.0.

> reticulate::py_config() /tmp/RtmpuNaxqG/file155d27ec8ac.sh: 4: /home/rtt/miniconda3/envs/r410/etc/conda/deactivate.d/deactivate-r-base.sh: [[: not found /tmp/RtmpuNaxqG/file155d27ec8ac.sh: 5: /home/rtt/miniconda3/envs/r410/etc/conda/deactivate.d/deactivate-gxx_linux-64.sh: Syntax error: "(" unexpected Error in Sys.setenv(PATH = new_path) : wrong length for argument In addition: Warning message: In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) "" else intern) : running command ''/bin/sh' /tmp/RtmpuNaxqG/file155d27ec8ac.sh' had status 2

And is the problem solved now? I've tried a lot of methods and it still doesn't work, thanks!
