### ISSUE TITLE
The "Compile Pdf"-button does not accpet LuaLatex-compilation

### ISSUE THREAD

**Issue by ahudde** [rstudio/rstudio#11261]
RStudio offers a great "Compile Pdf" button to compile .tex-files using pdfLaTex or XeLaTex via tinytex (as I understand it). The compiler can be chosen by the preamble 

% !TeX program = pdfLaTex

or 

% !TeX program = XeLaTeX

tinytex also offers a lualatex-compiler (by tinytex::lualatex( file )), but the option

% !TeX program = LuaLaTeX

shows the message "unknown latex program". 

Maybe lualatex could also be integrated into this button.

With best regards,

Anselm

**Comment by ronblum** [comment]
@ahudde Thank you for the suggestion! We'll review it as we continue development of RStudio.
