### ISSUE TITLE
Non-ASCII characters not highlighted in function calls

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rstudio#11260]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.2 Build 485
    OS Version      : Windows
    R Version       : 4.2

### Steps to reproduce the problem
Include a non-ASCII character in a function name, then call this function in an R script

### Describe the problem in detail
Non-ASCII characters (and characters preceding them) are not highlighted as function calls in R scripts

### Describe the behavior you expected
Non-ASCII characters should be highlighted like ASCII characters

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

```r
library(pipebind)

λ <- bind

c(a = 1, b = 2, c = 3) |>
  bind(x, paste(names(x), x, sep = " = "))

c(a = 1, b = 2, c = 3) |>
  λ(x, paste(names(x), x, sep = " = "))

c(a = 1, b = 2, c = 3) |>
  aλ(x, paste(names(x), x, sep = " = "))

c(a = 1, b = 2, c = 3) |>
  λa(x, paste(names(x), x, sep = " = "))

c(a = 1, b = 2, c = 3) |>
  aλa(x, paste(names(x), x, sep = " = "))

c(a = 1, b = 2, c = 3) |>
  α(x, paste(names(x), x, sep = " = "))
```

![image](https://user-images.githubusercontent.com/4773225/169629532-ea1ef6ef-646f-443a-9694-280d23c4381f.png)

**Comment by ronblum** [comment]
@bwiernik Thank you for raising this! I can reproduce this in RStudio Desktop 1.4.1717 and both RStudio Desktop and Server 2022.02.2+485. However, this appears to be fixed in the version currently in development, 2022.06.0-daily+421, so I'm marking this a resolved.
