### ISSUE TITLE
More ide agnostic `cli::style_hyperlink(url=)` prefix. 

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#11271]
Maybe `ide:run`, `ide:help`, `ide:vignette` instead of `rstudio:*`. The ide could declare "it knows" about these with e.g. environment variable(s) , e.g. `R_CLI_HAS_HYPERLINK_IDE_RUN` ...

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 2022.06.0-daily+528 on MacOS 12.5
- RStudio Server 2022.06.0-daily+253 on Ubuntu 20.04 via Firefox on MacOS 12.5

Tested by using [sample code from a related issue](https://github.com/rstudio/rstudio/issues/11273#issuecomment-1156193252) then comparing with the results when replacing all occurrences of `ide:` with `rstudio:`. https://github.com/rstudio/rstudio/issues/11273#issuecomment-1156193252
