### ISSUE TITLE
Make executable links safer

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#11273]
The current behaviour of code-executing hyperlinks feels a bit risky — obviously we'll be careful with our use of it, but we have introduced a fairly easy way to introduce easily executable code into the output. I think it would be nice if clicking on the link showed a popup with exactly what code would be run along with a button that would run it.

**Comment by romainfrancois** [comment]
Relatedly, should they be styled slightly differently ? because the action is different: do something rather than go somewhere ? Maybe they can look more like a button ?

**Comment by romainfrancois** [comment]
Would "copy the code in the console" without running it be enough ? Then the user would have to hit enter and so can check the code.

**Comment by hadley** [comment]
I _think_ we still want some way to run the code just by using the mouse

**Comment by mikebessuille** [comment]
@kevinushey @romainfrancois @jgutman Are these links actually running code? I thought they would just take you to a location in the current file, or to an external link.

**Comment by kevinushey** [comment]
> @kevinushey @romainfrancois @jgutman Are these links actually running code? I thought they would just take you to a location in the current file, or to an external link.

They do so by running code in the R session (we have an RPC so that the R session can handle the navigation attempt).

That said, as I understand it, RStudio just understands how to follow file URIs with some extra metadata, and all of that processing goes through `.rs.rpc.console_follow_hyperlink()`. In other words, we're not just evaluating arbitrary user input within a hyperlink; we're handling a semi-internal protocol for generated links. Is that correct, or am I missing something separate?

> Relatedly, should they be styled slightly differently ? because the action is different: do something rather than go somewhere ? Maybe they can look more like a button ?

For what it's worth, I like the current treatment.

**Comment by kevinushey** [comment]
@hadley clarified that it's specifically the `rstudio:run` protocol that would allow this; e.g.

https://github.com/rstudio/rstudio/blob/128552161df9c8463cc92c376d5bc0c2304de261/src/cpp/session/modules/SessionConsole.R#L37-L45

However, the reality is that any installed R package would have the exact same opportunity to run malicious code on load or attach and that would be much easier than using this as an attack vector. (This code is being run with the exact same privileges as any other R code run within the session, including code run by packages on load.)

So ultimately, I don't think this feature increases the attack surface; the onus is already on the user to trust the R packages they have installed and loaded in their session.

**Comment by hadley** [comment]
However, the problem is not just R code directly generating these links, but any R code that displays a file: e.g. `cat(readLines("foo.txt"))` could introduce a clickable link.

**Comment by mikebessuille** [comment]
I'm not concerned about an attack vector of running code in their own package; that is, in effect, the entire nature of our product.  I'd be concerned about external locations such as a web server serving an external URL that could somehow inject code that is run on the user's machine.  It sounds like that can't happen - we're letting the user execute local code that causes them to follow a URL and _display_ the result.  Correct?

**Comment by romainfrancois** [comment]
> actually does something dangerous

and you can also actually not show the code with `echo = FALSE`

```r
cli::style_hyperlink("head(mtcars)", "ide:run:head(mtcars)", params = c(echo = FALSE))
```

Also, malicious 🧙‍♀️ might entirely replace the `.rs.rpc.console_follow_hyperlink()` function. Perhaps that should not be an R function ?

**Comment by jcheng5** [comment]
If I'm following what is being discussed here correctly, I think the dangerous part is having RStudio support hyperlinks that make it possible to run code without displaying it to the user, period. Whether `style_hyperlink` has sensible defaults or not, there are just too many ways things can end up in the terminal to think it can ever be safe. I would strongly recommend that https://github.com/rstudio/rstudio/blob/a912e075aa428e11025e0444d382cd39037aaa06/src/cpp/session/modules/SessionConsole.R#L45 be replaced with UI showing the code to be executed and a confirmation.

(Romain's suggestion to copy the code to the console seems close to equivalent security-wise, but a less obvious user experience)

**Comment by jgutman** [comment]
Then we could do the "paste the code to the console, user must hit enter" as the immediate term solution for the upcoming release, and have a ticket to create the UI with confirmation for subsequent releases @mikebessuille

**Comment by mikebessuille** [comment]
@jgutman I don't think that's sufficient for Spotted Wakerobin.  I agree with Joe; we need to do this carefully and clearly.  Can we show some UI with the code, and a button to run the code?  And if the button is pressed, the code is copied to the console and run (without an enter)?

**Comment by mikebessuille** [comment]
I would hate for a simple "open a help article in a browser" link to have to bring up a dialog first and ask the user if they want to run this code...

**Comment by jmcphers** [comment]
If we have a vector for executing arbitrary code via a gesture that does not indicate trust or intent, we need some safeguards here. I think @kevinushey's proposal is probably the safest; if there are actions people want to take on hyperlinks, we'd be better off just offering them directly instead of giving them a code execution hook. 

However if we really need this extensibility I would suggest the following modifications:

First, style the hyperlink so it's clear *what it does*. Right now you get a dotted underline on the link -- it is not clear at all what is going to happen if you click the link. If it's an `rstudio:run` link, we could do something like decorating the text to execute on hover *plus* showing an execution button that has to be explicitly clicked to initiate execution. Rough mockup:

![image](https://user-images.githubusercontent.com/470418/170349024-3988f546-fe08-4792-ba38-2eff06412e6f.png)

Second, do not allow user/package supplied link text; the link text is always _exactly_ the code that will be executed. That way we don't have to reveal or prompt; what you see is what you get. 

Even reading this issue and the PR that added the functionality (https://github.com/rstudio/rstudio/pull/10416) I'm not totally clear on why we need this and how it's used.

**Comment by kevinushey** [comment]
@hadley mentioned a couple examples; e.g.

> two places where it seems useful: testthat::snapshot_accept() and rlang::last_trace()

I think the intention was to leave the door open for these sorts of usages for packages to experiment without requiring extra changes on the IDE side, but in the interest of safety I think it's okay to just explicitly add these entrypoints as needed.

**Comment by hadley** [comment]
@jmcphers I like your UI proposal.

For a little more context here a two places that we're experimenting with executable code links: 

* In rlang tracebacks:
   <img width="551" alt="Screen Shot 2022-05-25 at 14 17 56" src="https://user-images.githubusercontent.com/4196/170350602-d053a2ab-3796-4b14-a264-228d0de56ca4.png">

* In testthat snapshots:
    <img width="664" alt="Screen Shot 2022-05-25 at 14 19 09" src="https://user-images.githubusercontent.com/4196/170350801-acfda963-9b2c-4f91-80f0-a26cacb98ffa.png">

These both existing UI where previously we just showed the user the code to copy and paste. Personally, I've found the clickable link to be a surprisingly large improvement so I'd be sad if it had to completely go away.

**Comment by romainfrancois** [comment]
I agree that `rstudio:run` (or presumably `ide:run` once #11290) should be styled differently, and I also like @jmcphers proposal. 

We could back away from `rstudio:run` links and offer each action separately (e.g. `last_error()`, `snapshot_accept()`) perhaps using other escape code, e.g. `Application Program Command` (https://en.wikipedia.org/wiki/ANSI_escape_code). 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/2625526/170481143-9804c3ef-7e31-4162-aacf-fbf348b956fd.png">

Then, we would need something between the ide and user packages (`rlang`, `testthat` etc ...) to centralize these commands. Is this something `rstudioapi` can do ? Or maybe another package ? I don't think hard coding in the ide would scale well.

**Comment by romainfrancois** [comment]
Then maybe `cli::style_hyperlink()` would only do hyperlinks and we have something else for commands. 

In the interest of safety, I guess we need to also move `.rs.rpc.console_follow_hyperlink` out of R. It wouldn't be too difficult for some code to replace it and have it do something else when links are clicked. 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/2625526/170485811-583ee9b2-a07d-4b39-8349-b177d4c001e5.png">

**Comment by romainfrancois** [comment]
#11318 did the bulk of the work, but we expect there will be follow up (ui tweaks etc ...) so leaving this as `in progress` for now.

**Comment by kevinushey** [comment]
Some thoughts on the UI here:

<img width="445" alt="Screen Shot 2022-06-08 at 12 45 41 PM" src="https://user-images.githubusercontent.com/1976582/172703968-b22ff816-82fe-4866-b3ca-99065f1671c8.png">

- We should make sure the styles for the header + body match.
- I'm not a big fan of the custom "run" cursor -- instead, we should use a regular pointer, plus (perhaps) some UI adornments on the hyperlink to make it look more button-like (like @jmcphers suggested in https://github.com/rstudio/rstudio/issues/11273#issuecomment-1137751001)

Also, it seems like half the time, the hyperlink doesn't render as an executable link. (In this case, I get the "disabled" mouse cursor.)

<img width="615" alt="Screen Shot 2022-06-08 at 12 48 41 PM" src="https://user-images.githubusercontent.com/1976582/172704518-0542412a-0eac-4b69-aa26-e2e6f581c8b0.png">

Should there be a better description for vignettes?

<img width="239" alt="Screen Shot 2022-06-08 at 12 53 05 PM" src="https://user-images.githubusercontent.com/1976582/172705193-1ecdf3a2-12fd-4a5d-af3b-a0e9ad1dcc91.png">

Popups near the bottom of the window appear to get cut-off.

<img width="458" alt="Screen Shot 2022-06-08 at 12 54 06 PM" src="https://user-images.githubusercontent.com/1976582/172705340-0062b054-18d7-4888-9815-c4c3fcd041cc.png">

**Comment by kevinushey** [comment]
@GCRev, would you be able to share any additional feedback on how we could tweak the display of these popups?

The underlying intention here is to have code "hyperlinks" (which really are acting here as buttons, which will perform some action after being pressed. (This might mean "run code", or "show vignette", "or "show help topic").

I think the ideal here is to have the text hyperlink to be styled like a button (always? on hover?) to indicate to the user that clicking it would run some code (as opposed to just navigating or something a little more innocuous).

If you want to test-drive some of this in the latest daily builds, you can use:

```

# Run some code.
cli::style_hyperlink("head(mtcars)", "ide:run:utils::head(mtcars)")

# Open a vignette.
cli::style_hyperlink("A Vignette", "rstudio:vignette:dplyr::colwise")

# Open a help topic.
cli::style_hyperlink("Help", "rstudio:help:stats::rnorm")
```

**Comment by GCRev** [comment]
@kevinushey sounds like a good candidate for a ::before or ::after pseudo element decorator. Jonathan's suggestion above is very good. I'd probably just add the decorator inline without adding any borders, though, just so that the line-spacing isn't disrupted.

I'm also having trouble actually viewing these links -- the terminal just renders them as plain text. Is there a feature that I have to enable first?

Once I get this working I'll be able to play with the UI a bit to see what I think could be improved upon. Right now it mostly just looks like minor tweaks (alignment, colors)

**Comment by romainfrancois** [comment]
@GCRev maybe you need a newer `cli` package. I have version 3.3.0 from CRAN.

**Comment by romainfrancois** [comment]
> Also, it seems like half the time, the hyperlink doesn't render as an executable link. (In this case, I get the "disabled" mouse cursor.)

Fixed by https://github.com/rstudio/rstudio/pull/11393

**Comment by romainfrancois** [comment]
> Should there be a better description for vignettes?

I suppose we could go further than just using `$Title` from the result of `vignette()`. It's also because this particular vignette does not do `VignetteIndexEntry` well: https://github.com/tidyverse/dplyr/pull/6292

**Comment by kevinushey** [comment]
We might also just leave the description bit out for vignettes altogether; I don't think we can add anything particular illuminating based on just the vignette metadata. (Or perhaps that should just be used directly in the title bar?)

**Comment by romainfrancois** [comment]
Yeah I suppose we can just use the vignette title in the title bar. There's not much point about showing the short name.

**Comment by GCRev** [comment]
I pushed up a branch where I've made some changes to the styling that I think add some polish: https://github.com/rstudio/rstudio/tree/feature/cli-hyperlink-decoration-tweaks

https://user-images.githubusercontent.com/5544965/172952455-9a3fb1a6-4394-4d52-8386-2a575fde8c5e.mov

**Comment by romainfrancois** [comment]
Thanks @GCRev. I think we ruled out adding an extra play button to avoid issues with reflowing the text etc ... https://github.com/rstudio/rstudio/pull/11318#issuecomment-1142283236

I'll try instead to add it inside the popup.

**Comment by romainfrancois** [comment]
Moved to test 🎉 . Code to test below. This should work fine with released version of `cli`. 

```r
# web page ----------------------------------------------------------------
cli::style_hyperlink("rstudio", "https://www.rstudio.com")

# File --------------------------------------------------------------
file <- tempfile(fileext = ".R")
writeLines("hello\nhola\nbonjour", file)
cli::style_hyperlink("file", paste0("file://", file))
cli::style_hyperlink("file", paste0("file://", file), c(line = 2, column = 5))

# Help --------------------------------------------------------------------
cli::style_hyperlink("help page", "ide:help:dplyr::summarise")
cli::style_hyperlink("help page", "ide:help:dply::summarise")
cli::style_hyperlink("help page", "ide:help:dplyr::zummarise")

# Vignette ----------------------------------------------------------------
cli::style_hyperlink("vignette", "ide:vignette:dplyr::dplyr")
cli::style_hyperlink("vignette", "ide:vignette:vctrs::pillar2")
cli::style_hyperlink("vignette", "ide:vignette:vctrs2::pillar")

# Code --------------------------------------------------------------

# rlang is loaded, so the code executes
cli::style_hyperlink("show traceback", "ide:run:rlang::last_error()")

# sessioninfo is not loaded, so the code only gets copied in the console
# the user can then hit enter if they like it
cli::style_hyperlink("show session info", "ide:run:sessioninfo::session_info()")

# foo is not installed, also just copied
cli::style_hyperlink("show foo", "ide:run:foo::bar()")

# safeguards so that we can't do arbitrary mischief
cli::style_hyperlink("show traceback ...", "ide:run:rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(); rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(a = rm(list = ls()))")

cli::style_hyperlink("unsupported", "ide:foo")
```

**Comment by romainfrancois** [comment]
The safety considerations are dealt with by limiting what code may follow `ide:run:`: 
   - it has to be of the form `pkg::fun(<args>)` where `<args>` has no `;`, `(` or `)` 
   - code is only executed if `pkg` is either loaded or in the internal allow list: testthat, devtools, usethis, rlang. Otherwise it just is copied in the console and the use can choose to press enter or not.

**Comment by romainfrancois** [comment]
The "no parenthesis inside the `<args>` list of the `<pkg>::<fun>(<args>)` form might be a bit too strong for anticipated use cases in e.g. `usethis`. Maybe this could be allowed, but not automatically executed. i.e. 

`cli::style_hyperlink("click me", "ide:run:usethis::use_foo(a = b())")`

now gives an unclickable link: 

<img width="593" alt="image" src="https://user-images.githubusercontent.com/2625526/173398269-31bec95d-f769-4605-aed6-19ba9660c39c.png">

perhaps it should be more `cli::style_hyperlink("show session info", "ide:run:sessioninfo::session_info()")` that copies into the console without running it ? cc @jennybc 

would that be safe enough ? cc @Hadley @kevinushey

**Comment by kevinushey** [comment]
> The "no parenthesis inside the <args> list of the <pkg>::<fun>(<args>) form might be a bit too strong for anticipated use cases in e.g. usethis.

What is the specific code that we want to be able to run?

**Comment by romainfrancois** [comment]
There's no specific yet, it's anticipation of when `usethis` will start to ... use this 🙃. With the currently allowed form, `usethis` might have to do some code generation to comply. 

Although from a very quick glance at places that use `ui_code()` in `usethis`: https://github.com/r-lib/usethis/search?p=1&q=ui_code most seem to fit the pattern, so maybe this is not an issue.

**Comment by romainfrancois** [comment]
final QA note: there were a lot of discussion here. Here are some final code to test this: 

```r
# original issue: https://github.com/rstudio/rstudio/issues/1941
# last pull request: https://github.com/rstudio/rstudio/pull/11421

# web page ----------------------------------------------------------------
# clicking should open the webpage
cli::style_hyperlink("rstudio", "https://www.rstudio.com")

# File --------------------------------------------------------------
# clicking should open the file ... 
file <- tempfile(fileext = ".R")
writeLines("hello\nhola\nbonjour", file)
# ... at the beginning
cli::style_hyperlink("file", paste0("file://", file))
# ... at line 2, column 2
cli::style_hyperlink("file", paste0("file://", file), c(line = 2, col = 2))

# Help --------------------------------------------------------------------
# hovering will show preview information about dplyr::summarise
# clicking will open the full help page in the help pane
cli::style_hyperlink("help page", "ide:help:dplyr::summarise")
# same
cli::style_hyperlink("help page", "ide:help", c(topic = "summarise", package = "dplyr"))
# popup says "package not found"
# clicking errors with:
#   Error in find.package(if (is.null(package)) loadedNamespaces() else package,  : 
#   there is no package called ‘dply’
cli::style_hyperlink("help page", "ide:help:dply::summarise")
# hovering says "documentation not found"
# clicking errors with: 
#    No documentation for ‘zummarise’ in specified packages and libraries:
#    you could try ‘??zummarise’
cli::style_hyperlink("help page", "ide:help:dplyr::zummarise")

# Vignette ----------------------------------------------------------------
# popup shows title and description for the vignette
# clicking opens the vignette in the help pane
cli::style_hyperlink("vignette", "ide:vignette:dplyr::dplyr")
# package not found
cli::style_hyperlink("vignette", "ide:vignette:dply::dplyr")
# vignette not found
cli::style_hyperlink("vignette", "ide:vignette:dplyr::dply")

# Code --------------------------------------------------------------

# popup shows help for rlang::last_error
# clicknig runs the code
cli::style_hyperlink("show traceback", "ide:run:rlang::last_error()")

# if sessioninfo is installed, the popup will show some information
# clicking will just copy the code in the console
cli::style_hyperlink("show session info", "ide:run:sessioninfo::session_info()")

# foo is not installed, code also just copied
cli::style_hyperlink("show foo", "ide:run:foo::bar()")

# forbidden, clicking does nothing
cli::style_hyperlink("show traceback ...", "ide:run:rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:base::rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:base::source('http://example.org/code.R')")
cli::style_hyperlink("show traceback ...", "ide:run:base::system('rm -fr /')")

cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(); rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(a = rm(list = ls()))")
```

**Comment by ronblum** [comment]
Closing as complete.
