### ISSUE TITLE
Suggestion: Copy file name/path from Files pane

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#11275]
![image](https://user-images.githubusercontent.com/3200601/169941139-1ffc9b00-840b-4f61-a2d9-cc9260a077a0.png)

I often want to make reference to a file or dataset in my project directory, but there is currently no easy way to get the filepath or even filename of a file, other than copying it from the Explorer/Finder and typing out the directory path myself.

I think it would be great if doing Right-Click → Copy in the Files pane copied the _absolute_ path of a file to your clipboard. With the absolute path, the user could delete the bits they don't want to get a relative filepath, or just the basename of the file by itself. Thanks!

**Comment by ronblum** [comment]
@DesiQuintans—you can actually do that now! In the Files Pane, click on the checkbox to the left of the file for which you want the path. Then, click on the gear dropdown menu, and choose "Copy Folder Path to Clipboard." That will copy the path to the file.

**Comment by DesiQuintans** [comment]
Hi @ronblum, this doesn't complete the request because it only copies the folder path of the currently open folder. It doesn't copy any filenames.

**Comment by ronblum** [comment]
Ah! OK. And sorry—obviously you don't need to check on a file name, since it's copying the folder path.
