### ISSUE TITLE
Quarto render does not display output on additional renders

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#11274]
### System details

    RStudio Edition : Workbench
    RStudio Version : 2022.06.0 Build 379.pro4
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

- Quarto render (standard document example)
- Notice that a new window pops up
- Close new window
- Quarto render again
- Notice that no new window pops up / it is unclear whether the job finished / what the output was

### Describe the problem in detail

The UX is inconsistent and confusing - even a pointer to where the output is / etc. would be better.

### Describe the behavior you expected

Consistent UX where I either get a new window (and the browser moves me there), I get a pop-up that tells me the job is done, etc.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@colearendt I'm trying to reproduce, but I'm haven't been successful. By the window popping up, do you mean the generated document opening up in a separate window?

**Comment by ronblum** [comment]
FWIW, this is the behavior I'm seeing both at https://daily-rsw.soleng.rstudioservices.com/ and a couple of RStudio Server/Workbench 2022.06.0 builds in different environments. This is with "Preview in Window" set. If the job is stopped, though, the next Render will result in a new browser window.
