### ISSUE TITLE
Backslashes added to citations @ signs when switching to visual mode

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11279]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : RStudio-2022.02.2-485 and 2022.06.0-daily+421
    OS Version      : MacOS 12.4, Ubuntu 20.04 via Chrome on MacOS 12.4
    R Version       : 4.2.0

### Steps to reproduce the problem

1. Download and unzip the following: [travis-main.zip](https://github.com/rstudio/rstudio/files/8755903/travis-main.zip)
2. Open the file `README.Rmd`.
4. Switch to visual mode.
5. Switch back to source mode.

Note that the file has to be saved. So if tried by copying the contents of `README.Rmd` into a new file, the new file first needs to be saved before the behavior occurs.
 
### Describe the problem in detail

Backslashes are added to the citations, so `@` becomes `\@` and is no longer treated as a citation. For example,
```
[@wood_visualizing_2011; @vonschmidt_webbased_2019; @morgan2020; @beecham2022]
```

becomes
```
 [\@wood_visualizing_2011; \@vonschmidt_webbased_2019; \@morgan2020; \@beecham2022]
```

### Describe the behavior you expected

Citations should remain unaffected. This looks like another variation of #10075.

Triage: Note that #10075 was backported.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ailich** [comment]
I am also experiencing this when switching between source and visual editor. I have a [reproducible example up on my github](https://github.com/ailich/quartotest/blob/main/test3.qmd). I get a backslash if there is a call to equations with custom prefixes in the same sentence, or if there is no space between the closing parentheses around the figure cross reference and the citation.

For example:
This in source editor
![Screenshot 2022-06-13 110936](https://user-images.githubusercontent.com/28163862/173387655-87fa95b3-9220-4a17-a056-d5955f53f009.png)

Will properly render to this
![Screenshot 2022-06-13 110950](https://user-images.githubusercontent.com/28163862/173387736-57d90041-082f-4606-8728-e0b37bb6bedf.png)

However if I switch to visual editor and then back, backslashes have now been added by around the reference
![Screenshot 2022-06-13 111209](https://user-images.githubusercontent.com/28163862/173387874-e264d8be-6eae-456c-ac24-2f17a9c24a9a.png)

So now it renders to this
![Screenshot 2022-06-13 111244](https://user-images.githubusercontent.com/28163862/173388009-b8143caa-fd03-4efc-91cb-5d5ef0063da1.png)

I'm using R 4.2.0, Rstudio version "2022.06.0-daily+512" and quarto-version: 0.9.254

**Comment by jjallaire** [comment]
The README.Rmd issue is fixed here: https://github.com/rstudio/rstudio/commit/36db3473055f32d467f2e6f39028f45c9214c78a

Will investigate the other report now.

**Comment by jjallaire** [comment]
The other issue is quite complicated to untangle, and I don't think something we can fix for this release (too much risk of regression). Let's validate the first fix and then keep the bug open for the EG release.

**Comment by ronblum** [comment]
Verified that the README behavior is now correct. Moving to next release for part 2.

**Comment by jjallaire** [comment]
The behavior in the original bug report appears to now be fixed in the latest writer code (I did some work on citation escaping a couple of months ago that likely resolved it). Not sure if there are other behaviors described here that should also be verified?

**Comment by ronblum** [comment]
Verified that the second issue, with cross references, is now resolved as well. Tested in RStudio Desktop 2023.03.0-daily+318 on MacOS 13.2.
