### ISSUE TITLE
renv::init() error with R version 3.6.3

### ISSUE THREAD

**Issue by Jain-Paridhi** [rstudio/rstudio#11288]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows 10 Enterprise
    R Version       :  3.6.3

### Steps to reproduce the problem

1. Created a new project in RStudio
2. Added a simple file with only one command, 'library(tidyverse)' and saved it in the project.
3. Run 'renv::init()' in the project dir. Then I get the error.

### Describe the problem in detail
I was trying to create r environment for my R project. When I run renv::init(), I get the following error:
![image](https://user-images.githubusercontent.com/86398937/170210187-38a2ae70-ea5c-4845-9397-790866b536f2.png)

### Describe the behavior you expected
The environment should be created. All these steps worked for R version 4.1.0. Version 4.1.2 gave me the same error.

I'm not able to find the right resource or help.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can you try running the following:

```
trace(renv:::renv_file_link, quote({
  writeLines(sprintf("'Linking: %s' => '%s'", source, target))
}))

trace(renv:::renv_file_copy, quote({
  writeLines(sprintf("'Copying: %s' => '%s'", source, target))
}))

options(error = rlang::trace_back)
renv::init()
```

This should hopefully give us a bit more diagnostic output, and tell us which package is failing to copy into the cache.

**Comment by kevinushey** [comment]
@Jain-Paridhi, can you share an update?
