### ISSUE TITLE
FR: Highlight field name in R6 roxygen2 documentation

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#11280]
The `R6` fields and active bindings can make use of the _roxygen2_ tag `@field`. But the name of the field is currently not highlighted in the IDE, which makes it very difficult to distinguish the **name** of the field from its **description**. 

It would be very helpful if the name was highlighted the same way a function parameter name is highlighted with `@param` tag from _roxygen2_:

![image](https://user-images.githubusercontent.com/11330453/170015566-d79957b6-8666-4a26-abaf-045bfeee454e.png)

Version of RStudio I am using:

![image](https://user-images.githubusercontent.com/11330453/170017807-5faf3a18-6dfb-48e4-82d0-f7c1a403a4f2.png)

**Comment by ronblum** [comment]
@IndrajeetPatil Thank you for the suggestion! We'll review it as we continue developing RStudio.

**Comment by IndrajeetPatil** [comment]
Awesome! Thanks for the quick response.
