### ISSUE TITLE
boost library find error

### ISSUE THREAD

**Issue by kemin711** [rstudio/rstudio#11285]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.05.999-dev+999
    OS Version      :  Ubuntu
    R Version       :  4.2.0

### Steps to reproduce the problem
downloaded source
mkdir build
cd build
cmake ..

### Describe the problem in detail
CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost: Found unsuitable version "1.72.0", but required is
  exact version "1.69.0" (found /usr/local/include)

### Describe the behavior you expected
I have boost 72 in standard place,
I also run necessary dependency install-* scripts and boost 69 is installed at
/opt/rstudio-tools/x86_64/boost/boost_1_69_0

There is a defect in the Cmake file in finding boost.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Does it work if you remove the `CMakeCache.txt` file and re-run CMake?

**Comment by kemin711** [comment]
Yes, it worked. Thanks a lot. I was thinking to modify boost find file (which was too long, discouraged me).  Gland I asked.
Kemin Zhou 510 862-2276
 

    On Wednesday, May 25, 2022, 10:10:50 AM PDT, Kevin Ushey ***@***.***> wrote:  
 
 


Does it work if you remove the CMakeCache.txt file and re-run CMake?

**Comment by kemin711** [comment]
Removing cache solved the problem.
