### ISSUE TITLE
Qt dependency install script install-qt.sh not user friendly

### ISSUE THREAD

**Issue by kemin711** [rstudio/rstudio#11297]
### System details

    RStudio Edition : Server
    RStudio Version :  8acbd38 latest release
    OS Version      :  Ubuntu
    R Version       :  4.2.0

### Steps to reproduce the problem

cmake configure failed: 

CMake Error at src/cpp/desktop/CMakeLists.txt:96 (message):
  Did not find supported Qt SDK

Tried to install with the install-qt.sh failed.

### Describe the problem in detail

./install-qt.sh --version 6.3.0 qtbase
Could not determine a remote URL for qtbase with version 6.3.0

### Describe the behavior you expected

The QT url should be part of the install script, I am not expert on Qt. 
Should not expect user to know everything.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
If you are building RStudio Server, then you don't need Qt at all; it doesn't use it. Only RStudio Desktop uses Qt.

RStudio uses Qt 5.12, and will not work with Qt 6.x.

The install-qt.sh script is only intended for use from the Dockerfiles we use for our build machines. For doing your own build of RStudio Desktop on Linux, recommended way to install Qt is via the online installer. That is mentioned here:

https://github.com/rstudio/rstudio/blob/main/dependencies/linux/README

> - Qt 5.12.8 [Required only for Desktop]
> Installation of Qt SDK
> =============================================================================
>
> To build RStudio Desktop, install Qt from https://qt.io. Include the
> QtWebEngine component.
> 
> If the required version isn't showing up when installing via the Qt online
> installer click the "Archive" checkbox on the "Select Components" screen, then
> the Filter button. The list of available versions will expand to include older
> versions.

**Comment by jmbuhr** [comment]
What is the current recommended way of building rstudio from source on linux? After the steps in https://github.com/rstudio/rstudio/blob/main/dependencies/linux/README.
attempting the configuration in https://github.com/rstudio/rstudio/blob/main/INSTALL fails.

This is because e.g. https://github.com/rstudio/rstudio/blob/main/dependencies/linux/install-dependencies-bionic does not install QT and it is no longer mentioned in the linux dependencies README.

Is the new default to add `-DRSTUDIO_ELECTRON=1` for `cmake`? Though the latest `.deb` package from the rstudio website still used qt:

![image](https://user-images.githubusercontent.com/17450586/181790579-7322b671-c710-425d-8d6c-ef731f8d48ba.png)

**Comment by gtritchie** [comment]
Background:

* the most recent official releases are still using Qt for desktop, that's the 2022.07.x family
* the `main` branch, and daily builds, which will eventually become the next official release later this year, are no longer using Qt, only Electron
* not all instructions have been updated to match (sorry about that)

Give me a few minutes (or an hour or so I can double-check what I write) and I'll update the instructions.

**Comment by jmbuhr** [comment]
Thank you very much!

**Comment by gtritchie** [comment]
Some bad news: `make install` approach on Linux (and probably on Mac and Windows as well) isn't quite working for Electron. I opened #11679.

Until that gets fixed, what you could do is build a setup package (.deb) and install that. You can do this via:

```bash
cd ~/rstudio/package/linux
./make-electron-package DEB
```

This will produce a deb you can then install.
