### ISSUE TITLE
Quarto Shiny documents fail to render on Windows 11

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11291]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+445
    OS Version      : Windows 11
    R Version       : 4.2.0

### Steps to reproduce the problem

1. Create an empty Quarto document.
2. Copy into it one of the Shiny examples at https://quarto.org/docs/interactive/shiny/
3. Render the file.

### Describe the problem in detail

On Windows, RStudio Desktop fails to render the file, with the following message:
```
Warning message:
In system(paste0("quarto serve \"", input, "\" ", "")) : 'quarto' not found
```

### Describe the behavior you expected

The file should be rendered. Note that this works correctly on MacOS and RStudio Server.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I was able to reproduce as well.

Here's where we're trying to create the code that is used to render the Quarto document:

https://github.com/rstudio/rstudio/blob/df59e55c9b5b4834255f3301335602e9ac1b209a/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L593-L600

Do we need to ensure that Quarto is placed on the PATH here?

https://github.com/rstudio/rstudio/blob/df59e55c9b5b4834255f3301335602e9ac1b209a/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L641-L643

**Comment by kevinushey** [comment]
It looks like we normally put Quarto on the PATH when we try to detect it here:

https://github.com/rstudio/rstudio/blob/bb265d0dbedece7ced0325526ba14cb13684cb2d/src/cpp/session/modules/quarto/SessionQuarto.cpp#L218-L225

https://github.com/rstudio/rstudio/blob/bb265d0dbedece7ced0325526ba14cb13684cb2d/src/cpp/session/modules/quarto/SessionQuarto.cpp#L248-L252

But for some reason, that's not happening on Windows. That is, I see:

```
> Sys.which("quarto")
quarto 
    "" 
```

**Comment by cderv** [comment]
To add on that, **quarto** R package looks for `QUARTO_PATH` env var, or use `Sys.which("quarto")` . So if IDE fails to put it on PATH, then **quarto** R package won't find the bundled `quarto` version.

**Comment by jgutman** [comment]
> It looks like we normally put Quarto on the PATH when we try to detect it here:
> 
> https://github.com/rstudio/rstudio/blob/bb265d0dbedece7ced0325526ba14cb13684cb2d/src/cpp/session/modules/quarto/SessionQuarto.cpp#L218-L225
> 
> https://github.com/rstudio/rstudio/blob/bb265d0dbedece7ced0325526ba14cb13684cb2d/src/cpp/session/modules/quarto/SessionQuarto.cpp#L248-L252
> 
> But for some reason, that's not happening on Windows. That is, I see:
> 
> ```
> > Sys.which("quarto")
> quarto 
>     "" 
> ```

This actually doesn't seem to be the source of the issue. If I open a new R session, and run `Sys.which("quarto")` before doing anything else, I get the path to the Quarto binary. If I render a Shiny document, even a non-Quarto Shiny document (just using the default app.R from New File -> Shiny Web App for example) and then I re-run `Sys.which("quarto")` it now returns empty. 

So we are correctly setting the path to the quarto binary in Windows in SessionQuarto.cpp, but something about rendering a Shiny app (even a non-Rmarkdown non-Quarto Shiny app) seems to clobber the path

**Comment by ronblum** [comment]
Verified using 2022.06.0-daily+515. 

1) Cofirmed that the Quarto ["Old Faithful" example](https://quarto.org/docs/interactive/shiny/#hello-shiny) renders properly and launches.
2) Verified that `quarto::quarto_path()` and `Sys.getenv("PATH")` point to the `quarto.cmd` file.

Note that `quarto::quarto_inspect()` results in an error, but I'll open a separate issue for that.

**Comment by jrminter** [comment]
Sys.which(quarto) does nor work on Windows 11. Wiil this be updated?
