### ISSUE TITLE
Rename Jobs tab to "Workbench Jobs"

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#11296]
Rename "jobs" to "Workbench jobs" in accordance with https://github.com/rstudio/rstudio-pro/issues/3453.  This is the IDE portion of that work, and should include reviewing and updating any mention of jobs, sometimes referred to as "launcher jobs", from the jobs pane, menus, tooltips, etc.

**Comment by jgutman** [comment]
As part of this, aren't we also renaming Local jobs to background jobs?

**Comment by mikebessuille** [comment]
Yes, I totally forgot that part.  Local Jobs -> Background Jobs.

**Comment by jgutman** [comment]
Need to coordinate with changes in docs.rstudio.com and rstudioapi repos as well

**Comment by jgutman** [comment]
These changes are now part of the build; documentation and rstudioapi changes are still outstanding

**Comment by jgutman** [comment]
Because of the number of Pro-specific changes, this should likely be tested in RDP or RSW for test of the Workbench Jobs component.

**Comment by timtmok** [comment]
Verified in 2022.06.0-daily+505.pro1
