### ISSUE TITLE
R error when clicking gear icon in setup chunk toolbar

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11303]
### System details

    RStudio Edition : 2022.6.0.439
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.4
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

Create an R Markdown document with the contents:

`````
---
title: "Untitled"
author: "Bug"
date: "2022-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
`````

Then, try to click the gear icon that's displayed in the setup chunk toolbar:

<img width="406" alt="Screen Shot 2022-05-26 at 11 54 46 AM" src="https://user-images.githubusercontent.com/1976582/170557229-a505b7fc-1543-42cb-b4f7-58aa1fb7f7e3.png">

### Describe the problem in detail

An error is displayed in the R console, and the UI for changing chunk options never displays.

```
Error in callName == "knitr:::opts_chunk$set" || callName == "knitr::opts_chunk$set" : 
  'length(x) = 2 > 1' in coercion to 'logical(1)'
```

### Describe the behavior you expected

No error.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.0  fastmap_1.1.0   cli_3.3.0       htmltools_0.5.2
 [5] tools_4.2.0     yaml_2.3.5      rmarkdown_2.14  knitr_1.39     
 [9] xfun_0.31       digest_0.6.29   rlang_1.0.2     evaluate_0.15  
```

</details>

**Comment by ronblum** [comment]
@Trevor-Reid has an M1, so he's going to try it.

**Comment by Trevor-Reid** [comment]
I could not reproduce in my M1 macOS environment. I tried both `2022.02.1+461` and `2022.06.0-daily+467`

```
platform       aarch64-apple-darwin21.3.0  
arch           aarch64                     
os             darwin21.3.0                
system         aarch64, darwin21.3.0       
status                                     
major          4                           
minor          2.0                         
year           2022                        
month          04                          
day            22                          
svn rev        82229                       
language       R                           
version.string R version 4.2.0 (2022-04-22)
nickname       Vigorous Calisthenics 
```

**Comment by Trevor-Reid** [comment]
> @Trevor-Reid Thanks! And is that with this part?
> 
> ```
> Sys.setenv(
>   "_R_CHECK_LENGTH_1_CONDITION_" = "TRUE",
>   "_R_CHECK_LENGTH_1_LOGIC2_" = "TRUE"
> )
> ```

With that variable set, I do see the error:

```
Error in callName == "knitr:::opts_chunk$set" || callName == "knitr::opts_chunk$set" : 
  'length(x) = 3 > 1' in coercion to 'logical(1)'
```

**Comment by ronblum** [comment]
@kevinushey I'm putting this back in "in progress" because it looks like it's still an issue.

**Comment by kevinushey** [comment]
I thought @Trevor-Reid was just verifying that he could reproduce the error with older versions of RStudio?

It doesn't reproduce for me anymore with build 468.

<img width="555" alt="Screen Shot 2022-06-02 at 11 06 25 AM" src="https://user-images.githubusercontent.com/1976582/171697252-56a70fd8-0498-4795-af8d-bd2348278d0c.png">

**Comment by ronblum** [comment]
I think he's seeing it in 2022.06.0-daily+467, though, which I think should work fine?

**Comment by Trevor-Reid** [comment]
@kevinushey yes, I should have more specific. I can reproduce the error in `2022.02.1+461` but cannot reproduce this in the latest daily `2022.06.0-daily+467`

**Comment by ronblum** [comment]
In that case, verified!
