### ISSUE TITLE
occasional white-screen "crash" when editing Quarto document

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11309]
### System details

    RStudio Edition : 2022.6.0.439
    RStudio Version : Electron [Open Source]
    OS Version      : macOS Monterey 12.4
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

Open a Quarto document, and then start editing it.

In particular, put focus in the YAML header block and hit Ctrl+Space to trigger autocomplete.

### Describe the problem in detail

The RStudio window suddenly becomes completely white. The following is printed in the console where RStudio was launched:

> <--- Last few GCs --->
> [91741:0x140088000]       32 ms: Scavenge 2.9 (3.8) -> 2.8 (4.8) MB, 0.2 / 0.0 ms  (average mu = 1.000, current mu = 1.000) external memory pressure;
> 
> 
> <--- JS stacktrace --->
> 
> [91741:0526/175506.998293:ERROR:v8_initializer.cc(689)] V8 process OOM: (WasmCodeManager::Commit: Cannot make pre-reserved region writable).

### Describe the behavior you expected

No crash. Note that this happened on an M1 macOS machine, which might be relevant.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.0  here_1.0.1      Matrix_1.4-1    rprojroot_2.0.3
 [5] tools_4.2.0     Rcpp_1.0.8.3    reticulate_1.25 grid_4.2.0     
 [9] jsonlite_1.8.0  png_0.1-7       lattice_0.20-45
```

</details>

**Comment by gtritchie** [comment]
On the positive side, so far I can't repro in a development build on M1 Mac, which does support the possibility that we're messing up the entitlements when we produce official builds.

**Comment by kevinushey** [comment]
Verified fixed in build 468.
