### ISSUE TITLE
Single User Mode redirect failure when auth-stay-signed-in-days=0

### ISSUE THREAD

**Issue by jeffkeller87** [rstudio/rstudio#11300]
### System details

    RStudio Edition : RStudio Workbench (Open source edition)
    RStudio Version : RStudio 2022.06.0-daily+435 "Spotted Wakerobin" Daily (d0717845d82ddf7467f7061734570f6db215da72, 2022-05-22) for Ubuntu Jammy Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
    OS Version      : Ubuntu 22.04
    R Version       : NA

### Steps to reproduce the problem

1. Fresh installation (i.e. empty `/etc/rstudio/rserver.conf`)
2. As `root` user, run `rserver` in single user mode with an unprivileged user and the following arguments:

    ```bash
    root@remote-machine:~$ USER=jeff /usr/lib/rstudio-server/bin/rserver --www-port=80 --auth-none=1 --server-user=jeff --auth-timeout-minutes=0 --auth-stay-signed-in-days=0
    ```
3. Visit http://remote-machine:80 in a browser.
4. Browser reports a bad redirect and cannot open the RStudio IDE.

### Describe the problem in detail

The issue seems to be related to the `--auth-stay-signed-in-days=0` argument. If this is removed everything works as expected.

### Describe the behavior you expected

That running `rserver` in single user mode as an unprivileged user would work with all auth timeout arguments set to 0 (disabled).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
In single user mode, you should generally run `rserver` itself as the user, as documented here:

https://docs.rstudio.com/ide/server-pro/access_and_security/server_permissions.html#alternate-server-account

Does that fix the problem?

**Comment by jeffkeller87** [comment]
The approach I described is my workaround because I could not get the documented method that you linked to work. I actually thought about opening an issue for that one but wasn't able to probe the problem well enough.

At any rate, I would expect to be able to run `rserver` in single user mode without going through systemd.

**Comment by jeffvroom** [comment]
For me it works fine with auth-timeout-minutes=0 but not with -auth-stay-signed-in-days=0. auth-timeout-minutes=0 means that the cookie is valid forever. The auth-stay-signed-in-days means the cookie expires immediately so you get in an infinite redirect loop cause the cookie we set is never valid.
