### ISSUE TITLE
Error: nanodbc/nanodbc.cpp:1655: HY000: [IBM][Controlador ODBC de System i Access][DB2 para i5/OS] - RSTUDIO

### ISSUE THREAD

**Issue by YrHenao** [rstudio/rstudio#11317]
Tengo error para conectarme a una base de datos por medio del controlador de IBM desde rstudio, anteriormente me conectaba con el mismo codigo y hoy ya no me funciona, no me carga las tablas en el apartado connections de R, agradezco me colaboren:

codig
![Captura](https://user-images.githubusercontent.com/103220741/170876228-dde61a8b-1f17-429c-8bc5-7b2a5203d9e9.PNG)
![Captura2](https://user-images.githubusercontent.com/103220741/170876231-01772a8c-be82-44a4-813c-7fe29ae7f489.PNG)
o

**Comment by ronblum** [comment]
[Spanish translation from Google Translate]
¡Gracias por plantear el problema! Este repositorio es para errores y mejoras de RStudio. No brindamos soporte para errores en el controlador DB2 y el paquete `odbc`. Sin embargo, es un error en RStudio, si el único problema es con el "Connections Pane."

1. ¿Ha cambiado algo con la versión de R y RStudio? Si es así, ¿con qué versiones de R y RStudio funcionó?
2. ¿Ve las tablas si realiza la conexión con `DBI:dbConnect` en el "Console Pane" y luego:
- `odbc::dbListTables(con)`
- `odbc::dbExistsTable(con, "nombre_de_la_tabla")`
- `odbc::dbReadTable(con, "nombre_de_la_tabla")`
3. ¿Puedes intentar lo mismo, pero en R fuera de RStudio?

----

[Original English]
Thank you for raising the issue! This repository is for RStudio bugs and enhancements. We don't provide support for bugs in the DB2 driver and `odbc` package. However, it's a bug in RStudio, if the only problem is with the "Connections Pane."

1. Has anything changed with the version of R and RStudio? If so, what versions of R and RStudio did it work with?
2. Do you see the tables if you make the connection with `DBI:dbConnect` in the "Console Pane," and then:
- `odbc::dbListTables(con)`
- `odbc::dbExistsTable(con, "name_of_table")`
- `odbc::dbReadTable(con, "name_of_table")`
3. Can you try the same thing, but in R outside of RStudio?
