### ISSUE TITLE
Plots not rendering in qmd/Rmd in RStudio project

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/rstudio#11319]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.02.1 Build 461
    OS Version      : Ubuntu 20.04
    R Version       : 4.2.0

RStudio 2022.02.1+461 "Prairie Trillium" Release (8aaa5d470dd82d615130dbf663ace5c7992d48e3, 2022-03-17) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36

### Steps to reproduce the problem

Create an RStudio project on a shared file system and add a qmd or Rmd document with some plots. Run the plotting chunks multiple times.

### Describe the problem in detail

Our research institute is using a shared file system (https://www.beegfs.io/c/), which is available from our workstations via NFS export over Ethernet. Each group has a directory, writable only by members of that group.

When inside of an RStudio project, plots created from code chunks (qmd/Rmd) only show up about 20% of the time.
It works every time when plotting to the plots panel instead of inline.
When the Rmd/qmd file is not in a project it works reliably as well.
Projects local to the workstation not on the shared file system also work fine.

I found the folder where the chunk output is saved when inside of a project (not sure where this is for non-project documents) and indeed, something like `ls -la .Rproj.user/shared/notebooks/991BD52E-test/1/s/c4uy3f9gaquc4/` for a given chunk reveals that there is a png file with the plot for a local project but not for a project on a shared file system.

I have also tested this with multiple versions of RStudio, desktop and server.

### Describe the behavior you expected

Plots show up every time.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jmbuhr Thank you for raising this! Was this working on earlier versions of RStudio, before Prairie Trillium?

**Comment by jmbuhr** [comment]
There is nothing in the logfile (e.g. `sudo journalctl -u rstudio-server`) when this happens, which makes it hard to debug
