### ISSUE TITLE
RStudio crash when there is a missed dep

### ISSUE THREAD

**Issue by latot** [rstudio/rstudio#11323]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.02.2 Build 485
    OS Version      : Ubuntu 20.04.4 LTS
    R Version       : 4.2

### Steps to reproduce the problem

This is a example, there is several ways to do this

1. install libsodium-dev (operating system terminal)
2. Install tidyverse (RStudio console pane)
3. Remove libsodium (like the dev packages) from apt (needed by tidyverse)
4. Execute code that uses it......

### Describe the problem in detail

This bug is cased because RStudio is unable to handle the errors when there is a missed dep in the system, like above, when we compile tidyverse with all the deps installed will compile fine, we will be able to use it, but if a dep like libsodium-dev is removed from the system, when we try to execute a code that uses it will crash rstudio server.

```
may 26 16:30:16 pc rsession-user[3776816]: ERROR The previous R session terminated abnormally; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) src/cpp/session/SessionMain.cpp:698
```

Well, is pretty hard to work with this bug, after a lot of testing I was able to know the cause, but reproduce it is other thing, the reason, is because there is no way to know what line of code causes this from RStudio, this crash breaks everything, RStudio stop working, crash the server, no bug trace, almost no logs, gdb not working too....

Other thing hard with this bug, is once happens, after logging we will always see a grey screen, even if we reinstall and reset all of rstudio, what helps to can enter again to the session is remove the libs in the ```~/R``` folder or where are installed.

Is hard to me show a minimal reproduce example, the server I use is working, and used by more ppl, I can't uninstall the libs and lock it, but I think here is enough to know why/how happens the bug, I did my best to put all the info I was able to collect.

### Describe the behavior you expected

In case a lib is missed, just report in the R terminal as a normal R message.

### Workaround

1) Remove the R libraries from the PC
2) Install all R libs again, the libs that need the missed libs will complain
3) Install the missing libs
4) Install R packages

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports), light reading.
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/10523095/171220761-5061c510-c644-42fd-9026-3225ea42a7d3.png)

**Comment by ronblum** [comment]
@latot Thank you for raising this! Can you provide a minimal example of code that uses `libsodium-dev`? It would help with trying to reproduce the issue.

Also, I made a slight tweak to the original instructions, identifying the OS vs. R packages.
