### ISSUE TITLE
`previewRd()` doesn't load local Rd macros

### ISSUE THREAD

**Issue by lionel-** [rstudio/rstudio#11336]
This is a follow-up to #6871 which implements support for imported macros in previewed Rd files but not for local macros. More context at r-lib/pkgload#120.

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 467
    OS Version      : macOS Monterey
    R Version       : 4.1.2

### Steps to reproduce the problem

Create a new package and add an Rd file in `man/macros/` file containing:

```Rd
\newcommand{\known}{well-known}
```

Then add an R file containing:

```R
#' Topic
#'
#' This macro is \unknown{}. This one is \known{}.
testUnknownMacro <- function() {}
```

Generate the Rd file in man and try to preview it with `previewRd()`.

You can also find an example package at https://github.com/r-lib/pkgload/tree/main/tests/testthat/testUnknownMacro. Load it with `pkgload::load_all()` then call `dev_help("testUnknownMacro")`, which in turn will call `previewRd()` inside RStudio.

### Describe the problem in detail

 The `\known` macro is not expanded.

### Describe the behavior you expected

 The `\known` macro should be expanded.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For reference, we currently prepare the preview via a call to `R CMD Rdconv`.

https://github.com/rstudio/rstudio/blob/38c0bf68719d5e37e72e67ab14d0ca6ead727fb0/src/cpp/session/modules/SessionHelp.cpp#L729-L799

However, as far as I can see, this interface doesn't provide a way for us to request that "local" macros (that is, macros defined within the current package) be loaded as well.

We could probably define and run our own helper script that eventually calls `tools::Rd2HTML()` rather than relying on `R CMD Rdconv` here?

**Comment by lionel-** [comment]
We already generate an html file when running outside RStudio that we then open with `utils::browseUrl()`: https://github.com/r-lib/pkgload/blob/d11a10492e97bed9782b7d0c00eb8eeeebc57281/R/dev-help.R#L68-L73

Is there an API similar to `previewRd()` that we could call to display a pregenerated html file in the help pane?

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+265

Using provided reprex, help file is displayed correctly and the `\known` macro is correcty expanded
