### ISSUE TITLE
Increasing font size in the visual editor causes text to get cut off

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#11338]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.06.0-daily+421 "Spotted Wakerobin" Daily (2572293ae6f54278ae07e0cd10b29a370c69104c, 2022-05-19) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : macOS 12.4
    R Version       : 4.1.3

### Steps to reproduce the problem

Create a Quarto document and add the following text to it.

````
---
title: "Document Title"
author: "Author name"
format: html
---

Some text... and then a multi-line code chunk.

```{r}
library(dplyr)
mtcars |>
  filter(mpg > 30) |>
  group_by(gear) |>
  summarise(mean_mpg = mean(mpg))
```

::: callout-note
And a callout note but let's make this span multiple lines too.
So lots to say here.
Lots and lots...
:::
````

Then, switch over to the visual editor. With the default font size (12), it should look something like the following.

<img width="686" alt="Screen Shot 2022-06-02 at 8 59 48 AM" src="https://user-images.githubusercontent.com/5965649/171635012-5061ca07-1c1d-42ba-882c-90c65afe3557.png">

Then, go to Tools > Global Options > Appearance, and change the font size to something larger (like 24).

### Describe the problem in detail

Now the document looks like the following -- note the text cut off in the yaml and code chunks (those "boxes" didn't get resized) but the regular text and callout look ok.

<img width="683" alt="Screen Shot 2022-06-02 at 9 00 15 AM" src="https://user-images.githubusercontent.com/5965649/171635179-e5cd1e76-bc01-47df-b5bf-fb62a3cd5bb1.png">

### Describe the behavior you expected

I would have expected the yaml and code chunk areas to resize accordingly as well. The current solution is to close the document and re-open and things get resized correctly and the problem of text being cut off is resolved.

Note that a similar issue can be observed where the font size is reduced. Below is the result of reducing to font size 7. Once again, yaml and code chunks don't get resized appropriately, resulting in large spacing between lines.

<img width="681" alt="Screen Shot 2022-06-02 at 9 03 46 AM" src="https://user-images.githubusercontent.com/5965649/171635696-5c216041-24c9-4bb8-8b8a-5b7fbc05b658.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Ace has a mechanism for redrawing itself with the correct line height when font sizes change, but we are deliberately sabotaging it because it creates performance problems. 

https://github.com/rstudio/rstudio/blob/df26d2643ffecc0b1f4b5c8e99bb6dc1a81d30a8/src/gwt/panmirror/src/editor/src/optional/ace/ace.ts#L744-L759

So fixing this would probably involve listening for font size changes _outside_ the editor panels, and pushing an update to them when necessary. 

Note that this only affects chunks already open/active when the font size switch takes place; if you close and reopen RStudio (or even just the file) everything should look fine.
