### ISSUE TITLE
Does RStudio "preloads" packages? Crashing issue with rgl

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#11337]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.2
    OS Version      : Windows 10
    R Version       : 4.2.0

### Steps to reproduce the problem

Open RStudio and open a script file containing `library(rgl)`.

### Describe the problem in detail

Currently when I load the **rgl** package, RStudio crashes. But there's worse: when I just open a script containing `library(rgl)`, it crashes as well. RStudio scans the scripts to check whether packages in `library` calls are installed; then I'm wondering whether it does a kind of "preloading"? Once RStudio has crashed, I am obliged to delete the **RStudio** folder in **LocalAppData**, otherwise it still crashes when I reopen it.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
What version of the `rgl` package are you using? There is a known issue here that should be resolved with the latest release of `rgl`.

Do you also see the crash with older versions of R (e.g. R 4.1.3)?

**Comment by stla** [comment]
Hello,

 The latest version of rgl. I have not tried yet with R < 4.2.0. No problem in Rgui or Eclipse.

**Comment by kevinushey** [comment]
It works for me on my Windows machine (although I'm using R 4.2.0 Patched, but that shouldn't matter)

```
> library(rgl)
> packageVersion("rgl")
[1] ‘0.108.3.2’
> R.version
               _                                               
platform       x86_64-w64-mingw32                              
arch           x86_64                                          
os             mingw32                                         
crt            ucrt                                            
system         x86_64, mingw32                                 
status         Patched                                         
major          4                                               
minor          2.0                                             
year           2022                                            
month          05                                              
day            01                                              
svn rev        82294                                           
language       R                                               
version.string R version 4.2.0 Patched (2022-05-01 r82294 ucrt)
nickname       Vigorous Calisthenics    

> RStudio.Version()$long_version
[1] "2022.02.3+492"
```

**Comment by ronblum** [comment]
I tried it in
* RStudio Desktop 2022.06.0-daily+467 with R 4.1.3 and `rgl` 0.108.3.2 on Windows 11
but it works for me—I can't reproduce the issue. (I figured I'd try another combo.)

**Comment by stla** [comment]
I updated RStudio and no problem no. But now I'm not sure I had the latest **rgl** before... Sorry for the confusion. And thanks for your help.
