### ISSUE TITLE
Open PPT presentations in external app (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11340]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : 2022.06.0-daily+468
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem

- install Microsoft PowerPoint (or another app registered to load PPTX files)
- create a Quarto Presentation, with PowerPoint as the output format
- click on the Render button

![Screen Shot 2022-06-02 at 11 25 42 AM](https://user-images.githubusercontent.com/10569626/171688611-19c77b94-c6a0-40bc-83c8-07ea8c87cbeb.png)

### Describe the problem in detail

- the PowerPoint file is created, but not automatically opened

### Describe the behavior you expected

- PowerPoint (or whatever is registered for the filetype) should open the create file

### Background

Similar to #10897; we need to implement various callbacks (for each platform):

Qt implementation:
https://github.com/rstudio/rstudio/blob/c532ae20fd27a48948c6c7bf05f20c7975d07262/src/cpp/desktop/DesktopGwtCallback.cpp#L620-L629

https://github.com/rstudio/rstudio/blob/c532ae20fd27a48948c6c7bf05f20c7975d07262/src/cpp/desktop/DesktopGwtCallback.cpp#L579-L593

https://github.com/rstudio/rstudio/blob/c532ae20fd27a48948c6c7bf05f20c7975d07262/src/cpp/desktop/DesktopGwtCallbackMac.mm#L379-L389

https://github.com/rstudio/rstudio/blob/c532ae20fd27a48948c6c7bf05f20c7975d07262/src/cpp/desktop/DesktopGwtCallbackMac.mm#L63-L80

Electron NYI placeholders:

https://github.com/rstudio/rstudio/blob/c532ae20fd27a48948c6c7bf05f20c7975d07262/src/node/desktop/src/main/gwt-callback.ts#L359-L361

https://github.com/rstudio/rstudio/blob/c532ae20fd27a48948c6c7bf05f20c7975d07262/src/node/desktop/src/main/gwt-callback.ts#L371-L373

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Verified on:
2022.11.0-70
Windows 11
MacOS 12.4
Ubuntu 22.04

As expected, teh pptx file is opened by the appropriate app on the given OS.  Created several files via RMarkdown and Quatro.

**Comment by frederikziebell** [comment]
I still have this issue on RStudio 2022.12.0 Build 353 under macOS 12.6.2: When I render a quarto presentation, my default browser (Safari 16.2) is opened and automatically downloads the created .pptx file. The last two lines of my knitr output say

```knitr
Watching files for changes
Browse at http://localhost:7031/
```

I guess this is the reason why Safari is opened.
