### ISSUE TITLE
R studio won't open in Catalina (Mac Os 10.15)

### ISSUE THREAD

**Issue by Glyphorhyncus** [rstudio/rstudio#11343]
### System details

    RStudio Edition :Desktop or Server
    RStudio Version : 2022.02.3+492
    OS Version      : 10.15
    R Version       : 4.2.0

### When I try to open R studio I simply get the following error report, nothing else. Even when trying to open through the terminal or trying in safe mode, nothing works at all. 

Process:               RStudio [1356]
Path:                  /Applications/RStudio.app/Contents/MacOS/RStudio
Identifier:            org.rstudio.RStudio
Version:               2022.02.3+492 (2022.02.3+492)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RStudio [1356]
User ID:               501

Date/Time:             2022-06-02 15:30:30.037 -0400
OS Version:            Mac OS X 10.15 (19A583)
Report Version:        12
Anonymous UUID:        8B31D30A-26F2-473F-FD2E-E61C6F2B0C32

Sleep/Wake UUID:       D547B2F5-A209-481F-AD12-BBCFA5B56DFB

Time Awake Since Boot: 4800 seconds
Time Since Wake:       1200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1356]

Application Specific Information:
/Applications/RStudio.app/Contents/MacOS/../Frameworks/libcrypto.1.1.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libcrypto.1.1.dylib           	0x000000010a439a74 DYLD-STUB$$getenv + 0
1   dyld                          	0x000000010dd3c7f8 ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 990
2   dyld                          	0x000000010dd3ca5a ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
3   dyld                          	0x000000010dd37933 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 493
4   dyld                          	0x000000010dd3789e ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 344
5   dyld                          	0x000000010dd3789e ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 344
6   dyld                          	0x000000010dd3789e ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 344
7   dyld                          	0x000000010dd3669c ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 188
8   dyld                          	0x000000010dd3673c ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
9   dyld                          	0x000000010dd254b2 dyld::initializeMainExecutable() + 199
10  dyld                          	0x000000010dd2aaab dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6760
11  dyld                          	0x000000010dd24227 dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 453
12  dyld                          	0x000000010dd24025 _dyld_start + 37

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6ad515b4 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff6ad515b4 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010ddb7268  rbx: 0x000000010a31f2e0  rcx: 0x00007ffee7df5c88  rdx: 0x00007ffee7df5c30
  rdi: 0x000000010a4665c3  rsi: 0x00007ffee7df5c20  rbp: 0x00007ffee7df0860  rsp: 0x00007ffee7df0838
   r8: 0x000000010ddb7330   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x00007fff97b0c618  r13: 0x00007ffee7df08e0  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010a439a74  rfl: 0x0000000000010246  cr2: 0x000000010a4adb10
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     13

Binary Images:
       0x107e0a000 -        0x1080a9ffb +org.rstudio.RStudio (2022.02.3+492 - 2022.02.3+492) <830F55F1-1A2A-3D17-A075-47EEAC4AA164> /Applications/RStudio.app/Contents/MacOS/RStudio
       0x10811c000 -        0x108148ff3 +org.qt-project.QtWebEngine (5.12 - 5.12.10) <E94EB3FD-574F-3BBC-B587-9885F182ABD3> /Applications/RStudio.app/Contents/Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine
       0x108188000 -        0x1081a7ff7 +org.qt-project.QtWebEngineWidgets (5.12 - 5.12.10) <AB3C6B2F-9EBE-34DF-B232-0D170150B469> /Applications/RStudio.app/Contents/Frameworks/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets
       0x1081d2000 -        0x1081fbff7 +org.qt-project.QtPrintSupport (5.12 - 5.12.10) <223CF25F-E06A-30A9-8DBD-220F03A309CC> /Applications/RStudio.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x10822a000 -        0x108235ff3 +org.qt-project.QtQuickWidgets (5.12 - 5.12.10) <422C060F-23AA-3AFA-BBCF-

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2803
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=742.4M resident=0K(0%) swapped_out_or_unallocated=742.4M(100%)
Writable regions: Total=550.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=550.0M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           155.2M       16 
MALLOC guard page                   16K        3 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
PROTECTED_MEMORY                     4K        1 
STACK GUARD                       56.0M        3 
Stack                             9232K        3 
VM_ALLOCATE                         56K        4 
__DATA                            43.0M      382 
__DATA_CONST                       388K       10 
__FONT_DATA                          4K        1 
__LINKEDIT                       356.6M       49 
__OBJC_RO                         31.8M        1 
__OBJC_RW                         1764K        2 
__TEXT                           385.9M      368 
__UNICODE                          564K        1 
mapped file                       28.0M        2 
shared memory                       48K        6 
===========                     =======  ======= 
TOTAL                              1.4G      855 
TOTAL, minus reserved VM space     1.0G      855 

Model: MacBookAir7,2, BootROM 428.60.3.0.0, 2 processors, Dual-Core Intel Core i7, 2.2 GHz, 8 GB, SMC 2.27f2
Graphics: kHW_IntelHDGraphics6000Item, Intel HD Graphics 6000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.105.1 AirPortDriverBrcmNIC-1429)
Bluetooth: Version 7.0.0f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

(I had to remove multiple lines of this report to fit into this post)

### I have already tried the terminal based workarounds and none have been successful. I also tried adjusting the file permissions in the security settings, but R studio does not show up there, even after multiple re-installations. HELP!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
@ronblum, are you able to try and reproduce on a Catalina machine?

@Glyphorhyncus, is updating to a newer version of macOS an option for you?

**Comment by ronblum** [comment]
@kevinushey I can't reproduce this on MacOS 10.15.7—RStudio Desktop runs successfully on both R 3.6.3 and 4.2.0 for me. I'll check if any additional new updates make a difference

**Comment by ronblum** [comment]
With the latest updates to 10.15.7, RStudio Desktop 2022.02.3+492 and 2022.06.0-daily+468 with R 4.2.0 still works for me.

**Comment by burgerga** [comment]
Also ran across this on a student's laptop on MacOS 10.15. She is now updating to a newer Mac OS version. I asked for the backtrace but haven't received it yet, but it also mentioned libcrypto as the first line, so I think almost sure it's the same

**Comment by bettergreen20** [comment]
> 

I'm facing the same issue. Did she try updating to a newer version and did it work? If so, which version did she update to? Thanks!

**Comment by burgerga** [comment]
I don't know, I have asked her several to send me more details via email, but since updating worked she couldn't be bothered :/

**Comment by kevinushey** [comment]
The solution here is indeed to update to the latest version of macOS. If support for an older version of macOS is required, we recommend installing an older version of RStudio from https://www.rstudio.com/products/rstudio/older-versions/.
