### ISSUE TITLE
Tailwind in RStudio Viewer Pane

### ISSUE THREAD

**Issue by kylebutts** [rstudio/rstudio#11352]
Hi there! 

I'm developing examples for `{shiny.tailwind}` which allows people to use [TailwindCSS](http://tailwindcss.com) in shiny apps. I'm using the PlayCDN which is a javascript script that creates the CSS classes on the fly. The problem is that the Viewer tab in RStudio won't run it, so development only works in a browser at the moment. It is a bit of a pain point for using this, e.g. https://github.com/kylebutts/shiny.tailwind/issues/1.

I'm wondering if there's something I'm missing on how to get javascript scripts to run in the Viewer window. 

```r
devtools::install_github("kylebutts/shiny.tailwind")
shiny::runApp(system.file("examples", "01-Old_Faithful", package = "shiny.tailwind"))
```

**Comment by ronblum** [comment]
@kylebutts Thank you for raising the issue! I'll mark it as a bug to review as we continue development of RStudio. Thank you for checking that it works in a browser!
