### ISSUE TITLE
Graphics device backend options differ from Options menu to command palette

### ISSUE THREAD

**Issue by CGMossa** [rstudio/rstudio#11350]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.2.2.485
    OS Version      : "Windows"       "10 x64"  "build 19044"
    R Version       :  4.20

### Steps to reproduce the problem

* Press Ctrl + Shift + P to get the Command Palette and type "graphics". 
* Look at the options menu.

### Describe the problem in detail

There are different options list in the Options menu vs. the Command Palette.
See the images below:

![image](https://user-images.githubusercontent.com/1063624/171847089-58a4db23-8810-424b-a545-92b1ad76bbde.png)
![image](https://user-images.githubusercontent.com/1063624/171847147-93b4c65c-d947-4320-8685-c6148fffa956.png)

### Describe the behavior you expected

I expected the same list.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@CGMossa Thank you for raising this! I can reproduce this in RStudio Desktop RStudio-2021.09.3-396 and RStudio-2022.06.0-daily-468 on MacOS 12.4, as well. We'll review this as we continue development of RStudio.
