### ISSUE TITLE
Error opening files from Windows Explorer (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11369]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : 2022.06.0-daily+482
    OS Version      : Windows 10, 11
    R Version       : Any

### Steps to reproduce the problem

Note: pulled out this Windows-specific issue from https://github.com/rstudio/rstudio/issues/11251 since the fix is simple.

- Install RStudio on Windows
- Double-click a file in Windows Explorer such as a .R or .Rmd file; right-click and use Open With... to target RStudio if other programs such as VSCode are also installed

### Describe the problem in detail

- RStudio starts, the editor region displays (blank), and an error shows "Error while opening file" : "The system cannot find the file specified."
- After closing the error message dialog, the blank editor region remains

### Describe the behavior you expected

The file should open.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
Verified in build 487 installed and installerless. It also worked with project files.
