### ISSUE TITLE
Quarto preview has difficulty displaying PDF previews when using non-default fonts

### ISSUE THREAD

**Issue by adamoshen** [rstudio/rstudio#11365]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.3+492 Prairie Trillium
    OS Version      :  Windows 10 x64 (build 19043)
    R Version       :  4.1.3 (2022-03-10)

### Steps to reproduce the problem

Originally documented here: https://github.com/quarto-dev/quarto-r/issues/7

1. Enable Quarto Preview in RStudio.
2. Create a Quarto pdf and change any of the fonts to a font available on your system.

````
---
title: "Untitled"
format:
  pdf:
    mainfont: Times New Roman
    monofont: IBM Plex Mono
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this 

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
````

### Describe the problem in detail

The PDF preview does not display particular characters properly in the viewer.

![bad](https://user-images.githubusercontent.com/46703463/172225277-b000320b-85cc-4723-9fc1-73af4e5295b3.png)

### Describe the behavior you expected

The PDF file itself is okay, and there are no issues when viewed in an external PDF viewer.

![good](https://user-images.githubusercontent.com/46703463/172225297-26e0290a-ad6b-4f01-93a5-92582b3f6c28.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@adamoshen Thank you for raising this! I can reproduce the issue consistently in RStudio Desktop 2022.06.0-daily+521 as well, though I used ` monofont: PT Mono` instead. We'll review the issue as we continue developing RStudio and its integration with Quarto.

**Comment by jjallaire** [comment]
These fonts are likely not being embedded in the PDF. If there is a way to instruct pdflatex or xelatex to embed the fonts then I think things will work as expected.

**Comment by kevinushey** [comment]
@adamoshen: are you still seeing this issue with the latest release of RStudio (2023.12.1)?

**Comment by adamoshen** [comment]
@kevinushey I am no longer seeing this issue with the latest release of RStudio.

**Comment by kevinushey** [comment]
Great to hear; thanks for confirming!
