### ISSUE TITLE
Bad rendering of equations in help pages

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#11367]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-20) for Ubuntu Bionic Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  Arch Linux kernel version 5.18.1
    R Version       :  4.2.0

### Steps to reproduce the problem

Trigger the documentation of the `quantile()` function with e.g. `?quantile`.

### Describe the problem in detail

![snap](https://user-images.githubusercontent.com/19862384/172241330-13cda7d0-1dbc-43bb-a203-7c61b8a98e80.png)

### Describe the behavior you expected

I was not expecting to see those `\mbox` commands to surface on the help page of `quantile()`.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is a bug in R, not RStudio -- you can see the same with the following with R 4.2.0 in a terminal.

```
options(help_type = "html")
?quantile
```

I'll file a bug on the R bug tracker at https://bugs.r-project.org/.

**Comment by kevinushey** [comment]
It looks like this was already filed at https://bugs.r-project.org/show_bug.cgi?id=18343.
