### ISSUE TITLE
Provide `sidebarViewOnLoad` settings for `pdf.js`

### ISSUE THREAD

**Issue by netique** [rstudio/rstudio#11379]
On macOS, the default PDF Viewer is `pdf.js` and when I knit a `.Rmd` document to PDF, the viewer pops up **with the sidebar with pages thumbnails** open. I have to manually hide it each time to see the document (on macOS, the windows matches the width of the PDF page, unfortunately). However, the `pdf.js` provides a configurable variable `sidebarViewOnLoad`, which you can set to 0, so no sidebar appears on load. I think it is not configurable, so the only possible way is to compile RStudio with an edited `pdf.js` config. I thought maybe it could be part of the Global Options. What do you think? Many thanks for your consideration!

**Comment by ronblum** [comment]
@netique Thanks for the suggestion and the info! We'll consider this as we continue developing and adding improvements to RStudio.
