### ISSUE TITLE
Missing autocompletion for roxygen2 tags `@order` and `@examplesIf`

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11377]
If you open a package that uses roxygen2, most of the time the roxygen tags will autocomplete while you are typing. But `@order` and `@examplesIf` don't.

It looks like they just need to be added to this list:
https://github.com/rstudio/rstudio/blob/85cb949c827a6c89ff942ca3315bd6e272f59a61/src/cpp/session/modules/SessionRCompletions.R#L160-L217

Here are details of `@order`:
https://roxygen2.r-lib.org/articles/rd.html

And `@examplesIf` is mentioned here:
https://roxygen2.r-lib.org/articles/rd.html#functions

Probably faster for someone else to do a PR to fix this than for me to try and get an RStudio dev environment set up locally 😬

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-82

Tested all the methods in the roxygen2 package. All autocomplete as expected.
