### ISSUE TITLE
allow restartSession to control "type" of restart

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11378]
See https://github.com/rstudio/rstudioapi/issues/95 for discussion. Basically, the "type" of restart as triggered by `rstudioapi::restartSession()` and `rstudioapi::executeCommand("restartR")` are subtly different, as they go through different restart code paths.

It'd be nice if we could unify the two implementations, so that users of the `rstudioapi` package could configure some of the R session restart behaviors. (Notably, whether the R workspace is saved and restored on restart.)

**Comment by ronblum** [comment]
Piggybacking on #2841 (these go hand-in-hand).
