### ISSUE TITLE
Lambda function syntax not shown in Document outline

### ISSUE THREAD

**Issue by ColinFay** [rstudio/rstudio#11375]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-16) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Mac oS Monterey
    R Version       :  4.2.0

### Steps to reproduce the problem

Add this to a new document and display the outline

```r
w <- function(){
  print("w")
}

x <- \(){
  print("x")
}

y <- function(){
  print("y")
}
```

### Describe the problem in detail

x is not displayed in the outline

![Screenshot 2022-06-07 at 16 29 49](https://user-images.githubusercontent.com/17936236/172406646-f37d74fd-152e-47a0-827b-b563294172d5.png)

### Describe the behavior you expected

x shown, just like w and y

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The relevant code here: https://github.com/rstudio/rstudio/blob/85cb949c827a6c89ff942ca3315bd6e272f59a61/src/gwt/acesupport/acemode/r_code_model.js#L1117-L1214

**Comment by ColinFay** [comment]
If this is JavaScript all along I might be able to contribute but I'm not sure where to start. 

Is there a doc on how to locally build and run RStudio ?

**Comment by kevinushey** [comment]
The process is documented in the GitHub wiki, e.g.

https://github.com/rstudio/rstudio/wiki/RStudio-Development

And other articles throughout https://github.com/rstudio/rstudio/wiki.

**Comment by romainfrancois** [comment]
I've been there recently for the `test_that()` blocks, I can have a look.

**Comment by romainfrancois** [comment]
We also don't find functions that don't have `{` : 

```r
w <- function(){
  print("w")
}

x <- \(){
  print("x")
}

y <- function() print("y")
```

outline only shows `w`

**Comment by romainfrancois** [comment]
... but that would be tricky because at the moment the `{` is used to identify if the model should go back and look for functions. I think it's ok to keep it that only functions with a body in brace are outlined.

**Comment by kevinushey** [comment]
> ... but that would be tricky because at the moment the { is used to identify if the model should go back and look for functions. I think it's ok to keep it that only functions with a body in brace are outlined.

This would become easier if we had a way of parsing R code into an AST on the JavaScript side, but we don't have that tooling yet.

**Comment by jonvanausdeln** [comment]
Tested on:
RStudio-2022.10.0-daily-53

Verified repro case and several other functions.  and noted limitation of functions without `{` still exists.
