### ISSUE TITLE
scroll bar width covers text in soft-wrapping 

### ISSUE THREAD

**Issue by njtierney** [rstudio/rstudio#11382]
### System details

    RStudio Edition : Desktop
    RStudio Version : "2022.02.3+492"
    OS Version      : "macOS Monterey 12.3.1"
    R Version       : "R version 4.2.0 (2022-04-22)"

### Steps to reproduce the problem

- Use soft-wrapping in an rmarkdown document
- modern theme

### Describe the problem in detail

The scrollbar covers the final 1 or 2 characters of the softwrap, which means that you miss the ends of words.

Strange enough, this appears to only happen when the rstudio session is connected to an external monitor.

For example, the text:

> data cleaning process accountable and transparent is imperative and essential

the character "l" is obscured by the scrollbar

### Describe the behavior you expected

The soft-wrapping should account for the presence of the scroll bar.

Here is a screenshot of the behaviour the characters "l" and "y" are covered

![image](https://user-images.githubusercontent.com/6488485/172523774-a50fbed7-8136-462c-9454-6d45c4aeffc6.png)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@njtierney Thank you for raising this! I'm unable to reproduce this though, with both the laptop monitor and with an external monitor, with mirroring and both as the main and  extended displays.

@kevinushey Do you have any suggestions for any other ways I can try to reproduce this?

**Comment by kevinushey** [comment]
This is just a guess, but I'm guessing that this issue could depend on some combination of these things:

1. Whether or not the laptop is plugged into an external monitor,
2. Whether or not the laptop display itself is open / visible,
3. Whether or not an external mouse is plugged in or in use,
4. Whether one of the above things change while RStudio is open (e.g. plugging in or removing a mouse; opening or closing a laptop display; etc)

It could also depend on the "Show scroll bars:" preference from the macOS General preferences pane:

<img width="684" alt="Screen Shot 2022-06-15 at 10 40 21 AM" src="https://user-images.githubusercontent.com/1976582/173890925-121ff829-37f9-4030-b30b-27ccecd935cb.png">

**Comment by njtierney** [comment]
Thanks for that, @kevinushey ! I'll take a look to see if I can replicate it at work.
