### ISSUE TITLE
Share one console/window across multiple projects.

### ISSUE THREAD

**Issue by joostkruis** [rstudio/rstudio#11383]
I often work in multiple projects at the same time. This generally works well when using a dual/triple monitor setup, however, when working remotely on a single screen it becomes increasingly annoying to constantly switch between screens, especially when you have to compare results across projects. As such, I would like to have a way in which I can work in multiple projects from one R-Studio window, and that share a console. A possible solutions might be:

1. Allow an additional tab-bar above the source pane which contains tabs to the open projects [clicking a tab then changes the tabs below to the files in the source pane for that project].
2. Just as we use $, @, ::, ::: to refer specific instances of a object of function, comparable functionality could be introduced to refer to identically named objects from separate projects, allowing them to be shown in the same console. For example, if I would want to call a function `foo` from project 1 [called pr1] while also having a function `foo` in project 2 [called pr2], this could be differentiated in the console with `pr1~foo` [using ~ in this example as the connector]. 

Thanks a lot!

**Comment by ronblum** [comment]
@joostkruis Thank you for the enhancement request! We'll review it as we continue development of RStudio.
