### ISSUE TITLE
View in Web Browser opens the wrong browser

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#11385]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Build 343
    OS Version      :  Ubuntu 22.04
    R Version       :  4.2

### Steps to reproduce the problem

1. Open the `Files` tab
2. Select an HTML file, and click "View in Web Browser"
3. This opens in Firefox (instead of Chrome)

### Describe the behavior you expected

I expect to open in Chrome, as `browseURL("rstudio.com")` opens in Chrome. The default browser on my system is Chome. I never use FireFox for anything :)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by csgillespie** [comment]
Changing the `browser` doesn't make any difference (tried a few things). Also checks various SO threads to see about default OS browser. As far as I can tell, it's set to google-chrome everywhere.

---

For info, I do/did set my browser in my .Rprofile, but RStudio seems to ignore that setting and change it to

```
✔ [main*]❯ options("browser")
$browser
function (url) 
{
    .Call("rs_browseURL", url, PACKAGE = "(embedding)")
}
```

**Comment by kevinushey** [comment]
> Changing the browser doesn't make any difference (tried a few things).

That is surprising to me, since all R (and hence RStudio) is doing here is calling the moral equivalent of:

```
system(paste(getOption("browser"), filePath))
```

If this doesn't fix the issue:

```
options(browser = "xdg-open")  # or whatever command line tool should 'open' URLs for you
browseURL("rstudio.com")
```

Then it seems unlikely that the issue is caused by RStudio?

**Comment by csgillespie** [comment]
Solved! I don't think it's a bug in RStudio.

The key (now obvious point), is that opening an HTML document in the `Files` browser, is opening a __file__ now a URL.

```
## Look at the mime types for HTML files
mimetype --all ~/Downloads/testing.html 
#/home/ncsg3/Downloads/testing.html: application/x-extension-html
#/home/ncsg3/Downloads/testing.html: text/html
#/home/ncsg3/Downloads/testing.html: text/plain
```
what is my default application
```
xdg-mime query default application/x-extension-html
# firefox
```
To solve
```
xdg-mime default google-chrome.desktop application/x-extension-html
```

---

@kevinushey I think this can be closed?

Thanks
