### ISSUE TITLE
Dock icon doesn't show project (Electron/Mac)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11386]
### System details

    RStudio Edition : Electron
    RStudio Version : 2022.06.0-daily+492 (any Electron build to date)
    OS Version      : macOS 
    R Version       : Any

### Steps to reproduce the problem

- open a project in RStudio Electron
- look at the dock icon
- repeat with the Qt desktop

### Describe the problem in detail

- Project name not displayed in the dock icon by Electron

![RStudio icon in Mac dock without project name](https://user-images.githubusercontent.com/10569626/172674407-ce1e18df-a053-476d-925d-0013e9d1120d.png)

### Describe the behavior you expected

- Shows the project name ("aaa" in this example) in the dock icon as seen here with Qt desktop:

![RStudio icon in Mac dock with project name](https://user-images.githubusercontent.com/10569626/172674533-8a7e020a-3899-49b4-b31a-adc0f1306bc2.png)

### Implementation Details

- Code from Qt needs to be ported, e.g.:

https://github.com/rstudio/rstudio/blob/be0d860a4650b185132484a0a38dd041bb993cf5/src/cpp/desktop/DockTileView.mm#L65-L123 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by matheustavaresdev** [comment]
This requires adding `DockTileView.mm` and calling it's `setLabel` function from inside `src/node/desktop/src/native/desktop.cc` so it can be called from within the Electron Code. You can change the places at https://github.com/rstudio/rstudio/pull/11480 that call `app.dock.setBadge` into the new native function.

**Comment by jonvanausdeln** [comment]
Verifided on
2022.11.0-70
MacOS Monterey 12.4

Tested for most project types
