### ISSUE TITLE
Dock menu missing New RStudio Window command, showing generic icon (Electron/Mac)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11387]
### System details

    RStudio Edition : Electron
    RStudio Version : 2022.06.0-daily+492 (any Electron build to date)
    OS Version      : macOS
    R Version       : Any

### Steps to reproduce the problem

- right-click on RStudio dock icon (Electron)

### Describe the problem in detail

- missing the "New RStudio Window" command
- there's a generic icon shown between checkmark and window title

![RStudio Electron dock menu screenshot](https://user-images.githubusercontent.com/10569626/172676882-9bdfd851-78b4-4756-b8f9-fd48a19b8d19.png)

### Describe the behavior you expected

- should include the "New RStudio Window" command and no generic icon, as seen here in same Qt build:

![RStudio Qt dock menu](https://user-images.githubusercontent.com/10569626/172676928-9e57d32e-c7e7-4075-ba99-fd9b03b0a8f2.png)

### Implementation Notes

The Electron icon not show the project name is tracked via #11386.

Need to port over the code from Qt, e.g.:

https://github.com/rstudio/rstudio/blob/be0d860a4650b185132484a0a38dd041bb993cf5/src/cpp/desktop/DockMenu.cpp#L23-L42

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified that "New RStudio Window" is present and opens a new window, using RStudio Desktop 2022.10.0-daily+55 Elsbeth Geranium.
