### ISSUE TITLE
Electron Desktop doesn't launch system PDF viewer / synctex

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11388]
### System details

    RStudio Edition : Electron Desktop
    RStudio Version : All
    OS Version      : All
    R Version       : All

### Steps to reproduce the problem

- In Electron, create an R Markdown file
- Tools / Global Options / Sweave / "Preview PDF after compile using: System Viewer"
- Check in the RMD editor toolbar's gear dropdown that (No Preview) is NOT selected
- Knit the document to PDF

### Describe the problem in detail

- The PDF is created but not opened

### Describe the behavior you expected

- The PDF is opened in the system PDF viewer as it is with Qt desktop

### Implementation Details

Need to implement callback:

https://github.com/rstudio/rstudio/blob/badc4743b2a0615ae468070af61f46a0d0ae4c55/src/node/desktop/src/main/gwt-callback.ts#L370-L372

The Qt implementation starts here: https://github.com/rstudio/rstudio/blob/badc4743b2a0615ae468070af61f46a0d0ae4c55/src/cpp/desktop/DesktopGwtCallback.cpp#L598-L607

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
if I understand, we haven't implemented synctex at all for Electron, so this implementation should always just use the system default pdf viewer, regardless of platform?

**Comment by jonvanausdeln** [comment]
Verified on 2022.10.0-68

Tested several files and scenarios.
