### ISSUE TITLE
Can't save Viewer pane contents as image (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11392]
### System details

    RStudio Edition : Electron
    RStudio Version : All
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem

- display something in the viewer page; for example, run this code:

```R
tempDir <- tempfile()
dir.create(tempDir)
htmlFile <- file.path(tempDir, "index.html")
writeLines(c("<html><body><p>Hello World</p></body></html>"), htmlFile)
viewer <- getOption("viewer")
viewer(htmlFile)
```

- click on Export / Save As Image... in Viewer pane toolbar

![Screen Shot 2022-06-08 at 4 50 47 PM](https://user-images.githubusercontent.com/10569626/172730489-2cc0942a-9999-47d1-bf63-98b73381cc68.png)

- click Save in the dialog

![Screen Shot 2022-06-08 at 4 52 56 PM](https://user-images.githubusercontent.com/10569626/172730660-94b3598f-0798-486c-a0ec-589cda4c27c7.png)

### Describe the problem in detail

- the dialog dismisses but the file isn't saved

### Describe the behavior you expected

- the file is created; if you had also clicked "View plot after saving" checkbox in that dialog the file would then open in the default application for that file format

### Implementation details

Need to implement this callback: https://github.com/rstudio/rstudio/blob/e80e1a57761c4f52eb9aa72b3ca3f60b82037efc/src/node/desktop/src/main/gwt-callback.ts#L516-L518

The Qt implemention is here: https://github.com/rstudio/rstudio/blob/e80e1a57761c4f52eb9aa72b3ca3f60b82037efc/src/cpp/desktop/DesktopGwtCallback.cpp#L766-L789

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
Note, in Electron 2022.10.0.69, save as image works correctly with actual plots, but does not appear to work with text/html examples as given above. 

```
library(ggplot2)
ggplot(mpg, aes(displ, hwy, colour = class)) + 
    geom_point()
```
and Export > Save as Image... works as expected

**Comment by ronblum** [comment]
Verified that the dialog completes and the filed correctly gets created in
- RStudio Desktop 2022.11.0+91

on
- MacOS 12.5 with R 4.2.1
- Windows 11 with R 4.2.0

using the original reprex above.
