### ISSUE TITLE
paste from word in visual mode

### ISSUE THREAD

**Issue by xtimbeau** [rstudio/rstudio#11398]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.3 build 492
    OS Version      :  windows 11
    R Version       : 4.2

### Steps to reproduce the problem
open new quarto pdf document. 
switch to visual mode
paste some text from word
switch to source mode
paste again the same text

### Describe the problem in detail
pasting in visual mode is adding linebreaks in and around the text pasted
pasting in source mode is ok
### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@xtimbeau Thank you for raising this! As a comparison point, copying from Notepad doesn't add the line breaks. As far as I can tell, the clipboard (<kbd>Win + V</kbd>) doesn't have any additional lines. I'll mark this for review as we continue development of RStudio and the visual editor.
