### ISSUE TITLE
bringMainFrameBehindActive GWT callback not implemented in Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11407]
### System details

    RStudio Edition : Electron
    RStudio Version : all
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

- following is NYI in Electron:

https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/node/desktop/src/main/gwt-callback.ts#L392-L394

### Describe the problem in detail

- this callback is invoked from GWT in a couple places:

https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/gwt/src/org/rstudio/core/client/command/AppCommand.java#L182

https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/gwt/src/org/rstudio/studio/client/application/events/EventBus.java#L87

### Describe the behavior you expected

- callback does same thing it did in Qt: https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/cpp/desktop/DesktopGwtCallback.cpp#L958-L961

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
The case of main window being hidden behind another window works as expected, it is brought back up from behind.  However, on MacOS if the main window is minimized, it is not brought back correctly.  On Windows 11, it IS brought back correctly from minimized state. .. moving back to in-progress

**Comment by jgutman** [comment]
I think this is ready to move back to test?

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-75

Now working when window is minimized on MacOS, Windows, and Linux
