### ISSUE TITLE
Electron reporting hardcoded displayDpi

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11413]
### System details

    RStudio Edition : Electron
    RStudio Version : any
    OS Version      : Windows
    R Version       : any

### Steps to reproduce the problem

- Read the Electron source code and compare it to the Qt source code

### Describe the problem in detail

- The GWT callback getDisplayDpi is hardcoded to return 72: https://github.com/rstudio/rstudio/blob/6b1da6f0dbb2e7ea7a840e51ed1a2fc97915bce9/src/node/desktop/src/main/gwt-callback.ts#L785-L787

### Describe the behavior you expected

- Return a real value, at least on Windows; the Qt implementation does this: https://github.com/rstudio/rstudio/blob/6b1da6f0dbb2e7ea7a840e51ed1a2fc97915bce9/src/cpp/desktop/DesktopUtils.cpp#L354-L361

This api's return value is used on Windows to set a css class `windows-highdpi` when value is >= 192: https://github.com/rstudio/rstudio/blob/6b1da6f0dbb2e7ea7a840e51ed1a2fc97915bce9/src/gwt/src/org/rstudio/core/client/BrowseCap.java#L266-L276

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Verified on:
RStudio-2022.10.0-daily-53
Windows 11, 4K monitor

Source code no longer contains hardcoded dpi. CSS correctly contained 'highdpi' class. Also went through several scenarios of resizing, zooming, etc.  All worked as expected.
