### ISSUE TITLE
Issues printing to console from within `foreach` on RStudio Windows 

### ISSUE THREAD

**Issue by christopherkenny** [rstudio/rstudio#11425]
Hello,

I think this issue is directed correctly to here, as it seems to be an RStudio on Windows specific issue, rather than a Windows or direct package issue. Happy to redirect if you think otherwise.

Thanks in advance,
Chris

### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.3+492
    OS Version      : Microsoft Windows 11 Home
    R Version       :  4.2.0

### Steps to reproduce the problem
Open RStudio and run the following minimum working example from a new file:
```
# libs ----
library(parallel)
library(foreach)
library(doParallel)

# example globals ----
ncores <- 2
iters <- 10

# set up a basic cluster w/ doParallel
cl <- makeCluster(ncores, outfile = "")
doParallel::registerDoParallel(cl, cores = ncores)

# loop along iters and print the number ----
x <- foreach(iter = seq_len(iters)) %dopar% {
    cat(iter, '\n')
}

# clean up ----
stopCluster(cl)
```

### Describe the problem in detail
`foreach` allows for fairly simple parallelization. On most machines, setting the option `outfile = ""` allows it to print directly to the console. This works on RStudio on macOS and RStudio server on Ubuntu, but not RStudio on Windows. Note though, on Windows, it works in RTerm correctly. _RStudio on Windows prints nothing in the console._ Printing to a file (e.g. `outfile = "test.txt"`) works on Windows RStudio.

### Describe the behavior you expected
The goal is to be able to print (infrequent) messages from within a foreach loop that works on the main three OSes on RStudio for using within an R package.

It should print something similar to:
```
1
2
3
4
5
6
7
8
9
10
```
though newlines depend on the timing.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For what it's worth, I see the same behavior with RGui (the default GUI implementation shipped with R) so this might be an R rather than RStudio issue.

Here's an example that reproduces without any extra add-on packages.

```
library(parallel)

cl <- makeCluster(4L, type = "PSOCK", outfile = "")
result <- parLapply(cl, 1:4, function(i) {
  writeLines(paste("Hello from iteration", i))
  invisible(i)
})
stopCluster(cl)
```

**Comment by kevinushey** [comment]
I've filed https://bugs.r-project.org/show_bug.cgi?id=18358 to see if the R Core team considers this something worth changing on their side.

**Comment by christopherkenny** [comment]
Thank you @kevinushey!
