### ISSUE TITLE
RStudio crashes when running a qmd code chunk

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11424]
I'm on the latest daily:

RStudio 2022.06.0-daily+515 "Spotted Wakerobin" Daily (8276b1800bb18153fae35448129d982ca3e0e1ac, 2022-06-13) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

I'm working on this qmd document. It generates quarto slides.
https://github.com/tidymodels/workshops/blob/main/slides/02-data-budget.qmd

When I click the green triangle to run a single code block it crashes. If I just hit `Render` then it works fine

https://user-images.githubusercontent.com/19150088/173431259-2ae301a6-4ad1-4cd3-8b47-9e34089783d1.mov

**Comment by DavisVaughan** [comment]
I've even used this minimal qmd and it crashes for me:

``````
---
title: "Test"
format: revealjs
---

```{r}
library(tidyverse)
```

``````

**Comment by kevinushey** [comment]
I wasn't able to reproduce. Can you provide any other details?

Can you confirm whether it effects R Markdown documents as well? Or, could it be specific to the project you're working on? (Do you see the same issue with a Quarto document that isn't part of any project?)

Are you able to get a stack trace from lldb? You can try running:

```
sudo lldb -n rsession
```

after starting RStudio, but before running the code that's triggering the crash.

**Comment by DavisVaughan** [comment]
Hmm I used `File -> New File -> Quarto Presentation` while outside of any Project and that works perfectly fine. I also pasted in my "reprex" from above and it works fine.

Then I made that the folder that contained that presentation qmd into a real Project and it still works fine.

So it _seems_ like it has something to do with our specific setup. Did you try to reproduce by cloning our repo?

---

That lldb command says I have >1 rsessions running (only 1 instance of RStudio is open)

```
daviss-mbp-2:~ davis$ sudo lldb -n rsession
(lldb) process attach --name "rsession"
error: attach failed: more than one process named rsession:
PID    PARENT USER       TRIPLE                         ARGUMENTS
====== ====== ========== ============================== ============================
8337   8318   davis      x86_64-apple-macosx             /Applications/RStudio.app/Contents/MacOS/rsession --config-file none --program-mode desktop --www-port 64061 --launcher-token 58B25317 --show-help-home 1
39303  10952  davis      x86_64-apple-macosx             /Applications/RStudio.app/Contents/MacOS/rsession --config-file none --program-mode desktop --www-port 62599 --launcher-token 7F0CC2ED
```

So I tried

```
daviss-mbp-2:~ davis$ sudo lldb -p 8337
(lldb) process attach --pid 8337
error: attach failed: attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries, when the attach failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.)
```

Both PIDs give that failure to attach message

**Comment by DavisVaughan** [comment]
Oh I guess something unique about our repo is that it is a quarto website, and the `slides/` directory contains qmd documents that render to slides. So maybe we can make a reprex that mimics that setup

**Comment by DavisVaughan** [comment]
I see this in my `Console.app` about why lldb can't connect to rsession - looks like the RStudio version is hardened

```
macOSTaskPolicy: (com.apple.debugserver) may not get the task control port of (rsession) (pid: 10433): (rsession) is hardened, (rsession) doesn't have get-task-allow, (com.apple.debugserver) is a declared debugger(com.apple.debugserver) is not a declared read-only debugger
```

**Comment by DavisVaughan** [comment]
Now, if I just create a new Quarto Project with `File -> New Project -> Quarto Project` and run the `1 + 1` chunk that appears in the `test.qmd` that that creates, then that works fine and prints the results inline.

So it seems to have to do with quarto websites / blogs + inline code chunk output somehow.
