### ISSUE TITLE
Multi-monitor display window bug

### ISSUE THREAD

**Issue by richard987** [rstudio/rstudio#11420]
I have a 1080p monitor and a 4k monitor. Sometimes the window on the 4k monitor shrinks to half size, possibly from the 1080p monitor, but then only fills a quarter of the screen as shown. To fix it I have to move the Rstudio window into the 1080p screen and back to the 4k screen:
<img width="1160" alt="Untitled" src="https://user-images.githubusercontent.com/6381711/173268859-66e0a345-ab10-405c-ba72-a86a99d89dfe.png">
n

**Comment by ronblum** [comment]
@richard987 Thank you for raising the issue! What happens if you change to software rendering? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by gtritchie** [comment]
Perhaps related to this bit of code: https://github.com/rstudio/rstudio/blob/0c03eea9d8f2670314d21c8c20a743c088b644b3/src/cpp/desktop/DesktopUtils.cpp#L354-L361

The results of that API are used on Windows to set a CSS style for high dpi displays: https://github.com/rstudio/rstudio/blob/0c03eea9d8f2670314d21c8c20a743c088b644b3/src/gwt/src/org/rstudio/core/client/BrowseCap.java#L266-L276

I have NOT confirmed that this is related, just documenting as something to peek at in future investigations.

**Comment by gtritchie** [comment]
What platform are you using? Was it Windows, Mac, or Linux? Screenshot suggests Linux, in which case my theory about that API doesn't apply as it is Windows-only.

**Comment by richard987** [comment]
It's windows 10. Seems to occur when rstudio is on the 4k display,  after I switch to other apps or let the display sleep for a while.

**Comment by richard987** [comment]
I think it happens after the display goes to sleep, will try to confirm that
