### ISSUE TITLE
Electron desktop doesn't give helpful message when R not installed

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11438]
### System details

    RStudio Edition : Electron
    RStudio Version : any
    OS Version      : Windows 10+
    R Version       : none installed

### Steps to reproduce the problem

- on Windows, uninstall all versions of R
- start RStudio desktop (Qt)
- get the "Choose R Installation" dialog with "Choose your machine's default version of R64" selected
- click OK button
- get the following "R does not appear to be installed" error dialog offering to take you to R project website:

![r-not-installed](https://user-images.githubusercontent.com/10569626/173932441-0d1b5f22-d784-4177-8305-7bdbc3448015.png)

- click Yes and web browser launches to https://www.r-project.org/

### Describe the problem in detail

- repeat the above steps with Electron desktop
- the message given is "Error Loading R" / "An error occurred while attempting to load the selected version of R."

![r-not-installed-electron](https://user-images.githubusercontent.com/10569626/173933044-4560ac29-19ef-41ba-86dc-1190d27fbe38.png)

### Describe the behavior you expected

- same behavior with Electron desktop
- Qt implementation of this is here: https://github.com/rstudio/rstudio/blob/14291a089cc42d530688e4961b9ad60dcddbca9e/src/cpp/desktop/DesktopChooseRHome.cpp#L247-L259

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: This is an issue in MacOS, as well, not just Windows.

**Comment by jgutman** [comment]
Did we used to have a message in MacOS in Spotted Wakerobin Qt?

**Comment by ronblum** [comment]
It wasn't the prettiest, but it was informative:
<img width="410" alt="macos_nor" src="https://user-images.githubusercontent.com/31009952/184649305-8b617789-085d-4896-878c-6e56672cd643.png">

**Comment by ronblum** [comment]
Now there are more Windows displayed, none of them helpful.

1. If sticking to the default pre-selected item and clicking "OK", the same error occurs as before.
![Image](https://user-images.githubusercontent.com/31009952/188892875-75cc200e-635b-4795-8231-6d08519c106b.png)

2. If trying to choose a non-existent specific version of R, then the following error appears—still unhelpful.
![Image](https://user-images.githubusercontent.com/31009952/188893061-2ef56014-c60f-41e3-b339-0eb32659c6bd.png)

Clicking "OK" reveals an extra tiny floating window, on top of the original unhelpful error.
![Image](https://user-images.githubusercontent.com/31009952/188893124-0ec20931-3a8a-4915-a2a1-1e0813c48819.png)

**Comment by jgutman** [comment]
On RStudio Desktop 2022.11.0+104 as well as 2022.11.0+178, I'm seeing the following: 

<img width="451" alt="image" src="https://user-images.githubusercontent.com/7817881/190182805-0286bb2c-6e48-48a4-9453-feae78581b8e.png">

This is the expected view. Note that I've been testing by renaming my R folder so that RStudio can't find it. @ronblum can you show me specifically what you're seeing?

**Comment by jgutman** [comment]
I've also just tried specifically uninstalling all versions of R on my windows system, and I still get the same above window. So I can't reproduce what you're seeing.

![Image](https://user-images.githubusercontent.com/7817881/190184141-3c9b3074-14ce-4cb8-ace3-7ece4197cb55.png)

**Comment by jgutman** [comment]
Update: You get the correct error message if both R and Rtools are uninstalled. If R is not installed, but Rtools is installed and added to the registry, we get the incorrect output in Ron's screenshot. We should try to fix this, but it is unlikely many users would be in the situation of having Rtools installed but no R.

**Comment by jgutman** [comment]
@ronblum or @jonvanausdeln -- I think pending the next daily you should be able to re-test, with or without Rtools installed. You should also be able to check the logs `C:\Users\<user>\AppData\Local\RStudio\log` and ensure there are no error messages being written about registry entries not being found (those should now be suppressed)

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+215
Windows 11

Tested 2 versions of R, also with and without RTools. All give expected dialog to download R.
