### ISSUE TITLE
Selection  on code chunk disappear when interacting with addins in visual mode

### ISSUE THREAD

**Issue by danieltomasz** [rstudio/rstudio#11432]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.06.0-daily+520 "Spotted Wakerobin" Daily (977cd167618b3d4e21362d1652c97f049865a1d8, 2022-06-14) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  MacOS 12.4
    R Version       :  4.2

### Steps to reproduce the problem
1. Set file in visual mode
1. Select some code in R chunk
2. Try to open Addins menu
### Describe the problem in detail

Visual Selection disappear when the Addins menu is opening , but I can make the operation on the selected code
The same behavior doesn't happen in  source mode

### Describe the behavior you expected

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@danieltomasz Thank you for raising this! A couple of questions:
* I'm unable to reproduce the issue. Can you get a screenshot, for comparison?
* Do you by chance know if this was working correctly with earlier versions of RStudio Desktop? 

Thanks!

**Comment by danieltomasz** [comment]
hi @ronblum ,  indeed I reported the issue without reporting the most important information - the selection disseaper in  visual mode only, for all type of files
My previous interpretation was wrong
