### ISSUE TITLE
Characters with special regex meaning need to be escaped when in Find in Files whole word mode

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#11435]
When searching in Find in Files with whole word mode checked, I can search for things like `()` and `[]` and other special characters, and receive results (if they exist)

**Comment by ronblum** [comment]
The records are no longer returned. However, if they're escaped with `\`, still no results are returned. Compare this to a regular expression search, in which escaping the characters returns matching records.

Checked in RStudio 2022.11.0+166 on MacOS 13.

**Comment by kevinushey** [comment]
I believe this is intentional and the behavior we decided on. When `Whole word` is checked, we treat the search query as a literal string to be searched, rather than a regular expression. In other words, if you're using "Whole word", you can't escape characters as RStudio is going to do the escaping for you behind the scenes.

If we wanted to close the loop, I think we could:

1. Allow the user to select both Whole word and Regular expression at the same time,
2. Treat the search query as a plain regular expression (ie: don't escape it) if Whole word is checked, but Regular expression is not.

**Comment by jgutman** [comment]
I think the whole point was not to treat whole word as regular expression as far as the user is concerned -- we are not going to expect users to escape characters if they are using whole word. #2 Kevin describes was the behavior prior to this PR but it's confusing for the user; there's nothing that indicates they should be using regex escaping when in whole word mode

**Comment by jgutman** [comment]
Clarification: 
> In a non-Git project, it works or parentheses and square brackets, but not curly brackets
> It doesn’t work in a Git project. (with `git grep`)

**Comment by jgutman** [comment]
> In a non-Git project, it works or parentheses and square brackets, but not curly brackets

This is not actually true. For all of these marks, it will work to find, for example, `()` or `hello()` but not `hello ()` when in Whole word mode. All will work when not in whole word mode. This is because grep considers the transition from a word `hello` to punctuation `()` to be a word boundary, but does not consider the transition from a space ` ` to another non-word punctuation `()` to be a word boundary. Therefore `Dear John {}` gets matched by ` {}` (including a leading space) but not by `{}` when in whole word mode. Both will match when not in whole word. This is grep behavior, I don't think this will affect many users, and there's not really a straightforward way to fix it. But there's no special difference in behavior between `()` `{}` and `[]` here -- all three behave the same

**Comment by jgutman** [comment]
The discrepancy between grep and git grep I will address in the upcoming build

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+215
Windows11, Ubuntu 22.04

Tested examples above and several other strings containing special characters.  As noted previously, when using `\` to escape characters and "whole word" is selected, does not return result.
