### ISSUE TITLE
RStudio should not include `_quarto.yml` by default in static "rendered document only" publications

### ISSUE THREAD

**Issue by toph-allen** [rstudio/rstudio#11444]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 521
    OS Version      : macOS Monterey 12.4
    R Version       : 3.6.3

### Steps to reproduce the problem

0. Using a simple Quarto slideshow ([quarto-slideshow.zip](https://github.com/rstudio/rstudio/files/8922141/quarto-slideshow.zip))
1. Enter the publishing workflow, selecting "Publish finished document only"

### Describe the problem in detail

- The `_quarto.yml` file is selected for publication by default, but it should not be.

![Screen Shot 2022-06-16 at 04 12 13 PM@2x](https://user-images.githubusercontent.com/3117884/174156859-d7481039-0554-441d-b635-5d2607961324.png)

### Describe the behavior you expected

Only the rendered artifacts for the Quarto project should be selected for publication by default in this case.

Note: The `_quarto.yml` file should still be included when publishing the source code for a project.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Is this a followup to #10995, but now we're including `_quarto.yml` in too many places?
