### ISSUE TITLE
Update references from Zotero

### ISSUE THREAD

**Issue by rgaiacs** [rstudio/rstudio#11447]
RStudio v1.4 or later has support to Zotero from the visual markdown editor.

![Screenshot from 2022-06-17 12-13-58](https://user-images.githubusercontent.com/1506457/174223529-6c98f0f5-c1c0-4582-8b82-683957a4db78.png)

When I add a new reference, RStudio will ask Zotero for the BibTeX and save the BibTeX into `references.bib`.

If I later change the reference in Zotero, the reference in `references.bib` does **not** update.

I would love to have have a button in RStudio that

1. remove all references not used in my project from `references.bib`
2. update all the references in `references.bib` based on Zotero

At the moment, I'm using [Better BibTeX for Zotero](https://retorque.re/zotero-better-bibtex/).

**Comment by ronblum** [comment]
@rgaiacs Thank you for the suggestion! I marked it for review as we continue developing RStudio, specifically the visual editor.

**Comment by drfurtado** [comment]
I would love to see this feature implemented.

**Comment by NeuroShepherd** [comment]
I would also find this feature to be quite helpful. In practice, the references I save with Zotero Connector are missing bits of information that I fill out retroactively (i.e. after already inserting a citation into Quarto/RMarkdown documents).

**Comment by jcolomb** [comment]
Would be nice to reopen.

Alternatively, one should change the integration or suppress it: we spend some time including citation, and if it cannot be updated, we loose time using this "feature" as we have to make changes manually.

We could also ask users to create the bib from zotero and use only the .bib in Rstudio.

**Comment by NeuroShepherd** [comment]
> Would be nice to reopen.
> 
> Alternatively, one should change the integration or suppress it: we spend some time including citation, and if it cannot be updated, we loose time using this "feature" as we have to make changes manually.
> 
> We could also ask users to create the bib from zotero and use only the .bib in Rstudio.

I've found that the "poor man's" solution to this is to just delete the `references.bib` file which prompts regeneration of a whole new references file when the document is rendered.

**Comment by jcolomb** [comment]
I do not know how you do that, but in my case, if I erase the .bib file, nothing works anymore, as I expected.

- inserting citations creates one entry in the text corresponding to one new block in the .bib file 
- rendering use the bib file to transform citations into text.

I really do not get how what you mention could work. Is there another function to add citations ?
