### ISSUE TITLE
help preview popups in help pane

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#11450]
Hovering links in the help pane should offer some preview of the help page, similar to `ide:help` hyperlinks: 

<img width="969" alt="image" src="https://user-images.githubusercontent.com/2625526/174302789-f4ff1abf-7247-4b2d-a785-3fd61ffa26f2.png">

**Comment by ronblum** [comment]
@romainfrancois Was this done and ready to test? Here's what I get in 2022.11.0+98:

- RStudio Desktop 2022.11.0+98 on MacOS 12.5
- RStudio Server 2022.11.0+98 on Ubuntu 20.04 via Chrome on MacOS 12.5
- RStudio Server 2022.11.0+98 on Ubuntu 20.04 via Firefox on MacOS 12.5

Here's the help pane:
https://user-images.githubusercontent.com/31009952/184129927-d1f23b45-f03b-48a5-8663-c5f5058b3397.mov

Here's with a function in the Source Editor:
https://user-images.githubusercontent.com/31009952/184131789-1bda896a-5c6a-4c5e-a753-ed5c725683ce.mov

**Comment by romainfrancois** [comment]
The videos don't load here for some reason. I'll open another issue for "function in the Source Editor" because it might take some more work, but help pane should be done and testable.

**Comment by ronblum** [comment]
Verified with several packages' help info:
- RStudio Desktop 2022.11.0-daily+160 on MacOS 13
- RStudio Server 2022.11.0-daily+160 on Red Hat 8.6

https://user-images.githubusercontent.com/31009952/187945641-9a261c08-f9c4-4394-9c37-61f3775d36d3.mov
