### ISSUE TITLE
Mac libclang version requirement is being inherited from Windows

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11452]
On a very new RStudio daily build, code completion for C / C++ has stopped working for me. I see:

```r
> .rs.setClangDiagnostics(2)
Attempting to load libclang for x86_64-apple-darwin17.0 
/Applications/RStudio.app/Contents/Resources/rsclang/libclang.dylib
   (Not Found)
/Library/Developer/CommandLineTools/usr/lib/libclang.dylib
   (Required version 13.0.1 not found (library is version 13.0.0))
```

Note this bit:

> (Required version 13.0.1 not found (library is version 13.0.0))

So it seems I have libclang 13.0.0.

I am on macOS Monterey 12.2.1. I have an Xcode update to do (13.4.1 is what it says I can update to) but haven't done it yet.

@kevinushey mentioned that only Windows should be requiring 13.0.1, so somehow that requirement is leaking into the Mac check.

RStudio 2022.06.0-daily+527 "Spotted Wakerobin" Daily (06b75a5901f4a781fa74dbca6764804bc0373836, 2022-06-15) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

**Comment by ronblum** [comment]
Triage note: Spotted Wakerobin.

**Comment by dfalty** [comment]
### Verified Fixed
    RStudio Edition    :  Desktop 
    RStudio Version(s) : 2022.07.0-541
    OS Version         : Mac 10.15.7 

### Test scenario(s) 
I was able to verify the original issue on version 2022.07.0-531 by creating the default C++, typing out `time`, and code completion not appearing. I also was able to reproduce the output given in the ticket from the console by inputting `.rs.setClangDiagnostics(2)` and getting back `Required version 13.0.1 not found`.

After updating to 2022.07.0-541, it is back to normal.
![image](https://user-images.githubusercontent.com/15237845/175652747-4b05a369-ca46-4395-a052-89984db3907b.png)
