### ISSUE TITLE
Enhance Python code whitespaces or indentation.

### ISSUE THREAD

**Issue by zemega** [rstudio/rstudio#11461]
Title: Enhance Python code whitespaces or indentation.

I'm learning Python and plan to use Python through reticulate package in a Quarto document through RStudio IDE. Going through Python tutorial, it took me a while to figure that I'm unable to see whitespaces or indentation that is needed for Python clearly. I have since enable the options "Show whitespaces characters" and "Show indent Guides". Which result in the appearances below:
![Screenshot 2022-06-20 212621](https://user-images.githubusercontent.com/47267219/174707063-fb983105-21e9-471c-b337-c8769f5185a1.png)
These "whitespaces characters" and "indent guides" are very faint, They're not useful, they needs a lot of concentration to see them. I have since then change the color of "whitespaces characters" into a more visible yellow color.

Nevertheless, the options "Show whitespaces characters" and "Show indent Guides" are not really a good way to show the usage of whitespace or indentation in Python. Please refer to the image below. Which is a screenshot of the same code inside VSCode. There's a line indicating the entirety of the class MyClass, and another line indicating the function f inside MyClass.
![image](https://user-images.githubusercontent.com/47267219/174707501-59ac303e-2d30-4e40-887f-48b9b40291ae.png)

I would like RStudio to implement something similar to the VSCode Python example. Even better, if the lines are also given rainbow treatment like the rainbow parentheses in Rstudio 1.4.

**Comment by ronblum** [comment]
@zemega Thank you for the suggestion, including the screenshot from VS Code as a comparison pointt! We'll review this as we continue development of RStudio.
