### ISSUE TITLE
Edit code snippets window is transparent and has ghosting

### ISSUE THREAD

**Issue by jonspring** [rstudio/rstudio#11476]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.3 Build 492 
RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Windows NT 10.0
    R Version       : 4.2.0

### Steps to reproduce the problem

Open Tool - Edit Code Snippets

### Describe the problem in detail

Code Snippets window loads up, but snippet area is transparent, so text overlaps other RStudio text and charts. When I drag the snippets window, all frames are ghosted cumulatively, leading to a big illegible smudge. I can't read the text to edit it, but can copy-paste it elsewhere to read it and edit it.

### Describe the behavior you expected
I expected the window to load with an opaque background so that its text would be legible in the foreground.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![rstudio_bug_snippets](https://user-images.githubusercontent.com/18709859/175133705-80eb45a0-17f6-4a76-abb7-ef45b80106a5.PNG)

**Comment by ronblum** [comment]
@jonspring Thank you for raising the issue! I'm unable to reproduce it though, also using RStudio Desktop 2022.02.3+492.

We're in the final stages of the upcoming release, Spotted Wakerobin. [Previews are available](https://www.rstudio.com/products/rstudio/download/preview/) for it—would you be will to true it out? Note that while the previews are pretty stable, they're still meant for testing purposes, not production work.

**Comment by jonspring** [comment]
I have updated to pre-release 2022.07.0-preview+536 and I see the same issue.

**Comment by kevinushey** [comment]
You could also try switching to software rendering: https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
