### ISSUE TITLE
Support RStudio on Red Hat 9 (RHEL 9) 

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11477]
Support RStudio Desktop and RStudio Server on Red Hat 9. We currently produce daily builds for it, but they're not fully supported yet (see #11215).

See also #11478 which addresses Fedora 36, although they're currently the same builds.

**Comment by mikebessuille** [comment]
related: https://github.com/rstudio/rstudio-pro/issues/4044

**Comment by mikebessuille** [comment]
1) Create a fuzzbucket environment
2) add jenkins job to run automation nightly
3) Verify that tests are passing, log bugs for failures.

**Comment by AndrewMcClain** [comment]
Test environment up and running, but a small number of tests are failing the nightly build.

Effort to fix tests tracked here : https://github.com/rstudio/rstudio-pro/issues/4288

**Comment by ronblum** [comment]
@AndrewMcClain Do you have a sense of whether this is just a matter of making some changes to tests, or if they indicate a problem with RHEL 9 support?

**Comment by AndrewMcClain** [comment]
It looks like it's problems with the tests, like the numbers of tabs is incorrect, or conditions aren't matching our expectations.

It's a little hard to tell if it's specifically RHEL9, but after peeking on some of the other generated pipelines, it looks like these failures actually might be more widespread than just RHEL9
