### ISSUE TITLE
Stop execution upon error in pre and post-render script within Quarto project

### ISSUE THREAD

**Issue by ghost** [rstudio/rstudio#11484]
**Problem**

Quarto projects allow you to specify a pre and post render script which is executed before and after the main quarto file is rendered. See [here](https://quarto.org/docs/projects/quarto-projects.html#pre-and-post-render-scripts). These scripts are normally used to setup and teardown data and environments required by the main quarto file. If an error occurs in the pre or post render scripts, the main quarto file is still rendered.

**Request**

Ideally, if an error occurs in a pre render script, that should stop the entire render workflow.

**Comment by ronblum** [comment]
@james-ashmore Thank you for raising this! 

@dragonstyle Is this something specific to the RStudio IDE, or should this be in the Quarto repository?
