### ISSUE TITLE
Add cursor above/below current cursor not working in Ubuntu 22.04

### ISSUE THREAD

**Issue by alexandrsanches** [rstudio/rstudio#11481]
### System details

    RStudio Edition : Prairie Trillium
    RStudio Version : 1db809b8
    OS Version: Ubuntu Jammy 
    R Version: 4.2.0 

### Steps to reproduce the problem

Shortcut Ctrol + Alt + Down

### Describe the problem in detail

Using the shortcut doesn't create a new cursor above/below the current cursor.

### Describe the behavior you expected

Create a new cursor above/below my current cursor.

**Comment by ronblum** [comment]
@alexandrsanches Thank you for raising the issue! I can reproduce it in both Ubuntu 22.04 and 20.04. A couple of questions:
- This keyboard shortcut is usually reserved for switching between workspaces—outside of RStudio, do you see this behavior?
- Also, do you know if this was an issue in previous versions, by chance?
