### ISSUE TITLE
Highlighting mode for Julia needs to be improved

### ISSUE THREAD

**Issue by Gabrielforest** [rstudio/rstudio#11485]
### System details

    RStudio Edition : 
    RStudio Version : 2022.02.3
    OS Version      :  mingw32  
    R Version       : 4.1.3

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/63704591/170590943-6ca3e0f8-d4af-46fb-a8d6-285146a30a20.png)

### Describe the problem in detail

Hi! I am using the Quarto package code above that works just fine but the highlighting syntax is wrong. It should be a transpose sign not a string.

### Describe the behavior you expected

This problem occurs on Rstudio IDE (at VS Code it did not happen).

![image](https://user-images.githubusercontent.com/63704591/171488639-a3e97b37-a896-422a-a23c-cee3e849e571.png)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
We're currently using the highlight rules bundled with Ace, which haven't been updated in quite some time:

https://github.com/ajaxorg/ace/commits/master/lib/ace/mode/julia_highlight_rules.js

We could consider updating the highlight rules and submitting those back to Ace.

**Comment by Gabrielforest** [comment]
Nice, I have opened it on their repository before, see at https://github.com/ajaxorg/ace/issues/4813
