### ISSUE TITLE
Make entry label used for Recent projects based on Rproj-filename, not its folder name

### ISSUE THREAD

**Issue by sda030** [rstudio/rstudio#11497]
Recent projects list is great, but it is very much tailored to package developers - where R is the center of attention - rather than applied research teams who have a folder structure more like below where the "technical" analyses in R is more hidden away in a subfolder. In the structure below, the Rstudio Project is stored in 04_Analysis (or even a subfolder of this). 
-Survey to teachers 2022    # Fictious project name
-- 01_Administration
-- 02_Questionnaire
-- 03_Data
-- 04_Analysis                      # Analysis folder might even have researcher-specific subfolders as some use e.g. Stata.
--- 01_Syntax
--- 02_Tables
--- 03_Figures
-- 05_Publication

The point is that in all these cases, the entry in Rstudio is simply "04_Analysis", which is rather uninformative when working on multiple projects. Why not use the name of the .Rproj file? Then one could simply name it "survey_teachers_2022.Rproj". This would work for both package-developers and applied researchers. And as far as I know, nothing besides the recent projects list points to the Rproj-file so should be quite safe to either make this switch, or let the user configure this. 
I understand that the list is hardcoded but I do not imagine that changing the entry label to be the same as the filename is too hard to implement?

P.S. Not found any open or closed issue on "recent projects" matching this issue.

**Comment by ronblum** [comment]
@sda030 Thank you for the suggestion! I can't find a similar enhancement, either, so thanks for filing this—I'll mark this for review as we continue development of RStudio.
