### ISSUE TITLE
Add a keyboard shortcut stub for hash pipe #|

### ISSUE THREAD

**Issue by RaymondBalise** [rstudio/rstudio#11498]
Can you please add a keyboard shortcut for the Quarto hash pipe combination.

I am working with Quarto and I need to add #| (hash pipe) in every code block.  That is a seriously awful keyboard combination. Currently the keyboard shortcuts include an option for "Insert Pipe Operator" but there is not one for "Insert Hash Pipe Operator".  Can you please add a "stub" to the options in keyboard shortcuts for hash pipe.  For all of us who have motor memory for cmd-shift-m it may make sense to have a default binding of cmd-shift-h.

I think this will be an extremely popular/desired addition after Quarto gets a pile of attention at RStudio::conf() 2022.

**Comment by ronblum** [comment]
@RaymondBalise Thank you for the suggestion! I'll tag this as a combination of both Quarto and keyboard shortcuts as we review enhancements for the IDE.
