### ISSUE TITLE
RStudio crashes at startup if java is misconfigured and a package uses it in a file

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/rstudio#11491]
### System details

    RStudio Edition : Desktop 
    RStudio Version : RStudio 2022.02.3+492 "Prairie Trillium" for Windows
    OS Version      : Windows 10
    R Version       : 4.2.0

### Steps to reproduce the problem

1. update Java, so that environment variable JAVA_PATH is outdated, or simply set it to some dummy path
1. install this package `pak::pak("tabulizer")`, which depends on `rJava`
1. create a new file with this code: `#text <- tabulizer::extract_text("")`
1. save this code, nothing happens
1. uncomment the line, save again, RStudio crashes, right after the following message is printed (no error):
> java.home option: 
> JAVA_HOME environment variable: C:\Program Files\Java\jre1.8.0_291

### Describe the problem in detail

RStudio crashed at startup, without me even running some code.
The crash happens after the message about JAVA_HOME.
This popup show right after:
![image](https://user-images.githubusercontent.com/15105152/175530263-ec244698-5ab6-46ff-99e9-7f6723a2f9d9.png)
If in a project, restarting RStudio will show the same error at startup, even if the code is commented back using notepad. The only way to start the project again is to delete `.Rproj.user`.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/8975950/diagnostics-report.txt)
[rsession.log](https://github.com/rstudio/rstudio/files/8975951/rsession-Dan.log)

### Describe the behavior you expected

Show the error without crashing. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@DanChaltiel Thank you for raisin the issue! I'm unable to reproduce it with RStudio Desktop 2022.02.3+492 on Windows 11, both with JAVA_PATH and JAVA_HOME pointing to invalid directories. I'll mark this for review as part of our ongoing development of RStudio.

**Comment by ronblum** [comment]
Also, what happens when you click on "OK"—does RStudio close?

**Comment by DanChaltiel** [comment]
When I click on OK, it usually does nothing. I can type in the console et use the menu (with of course no effect).
Sometimes, instead of this javascript alert, I have the usual RStudio crash screen saying that the R session aborted.
