### ISSUE TITLE
A character `"NA"` name doesn't autocomplete correctly

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11503]
If you use RStudio's autocomplete to autocomplete an `"NA"` name (not `NA_character_`), then it won't autocomplete with backticks, which are required to parse it correctly.

```r
x <- list(1, 2)
names(x) <- c("x", "NA")
x
#> $x
#> [1] 1
#> 
#> $`NA`
#> [1] 2

# This is what RStudio autocompletes
x$NA
#> Error: unexpected numeric constant in "x$NA"

# This is what is required
x$`NA`
#> [1] 2
```

<img width="505" alt="Screen Shot 2022-06-27 at 10 04 03 AM" src="https://user-images.githubusercontent.com/19150088/175960884-7dd0bac5-5316-4172-a8bb-cb642a9b38b7.png">

**Comment by ronblum** [comment]
Reproduced in
* RStudio Desktop 2022.07.0-preview+543 on MacOS 12.5
* RStudio Server 2022.07.0-preview+543 on Ubuntu 20.04 via Safari on MacOS 12.5

**Comment by kevinushey** [comment]
This is where we decide if the value should be quoted:

https://github.com/rstudio/rstudio/blob/3bafffe479bbc3f762a9a29d0deb99ecdf9b348e/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java#L1895-L1931

We probably need to check for keywords as well.

**Comment by DavisVaughan** [comment]
Re: We probably need to check for keywords as well.

Yea, like this:

```r
x <- list(1, 2)
names(x) <- c("x", "function")

x$function
#> Error: unexpected 'function' in "x$function"

x$`function`
#> 2
```

**Comment by jonvanausdeln** [comment]
Verified on:
2022.11.0-71
Windows 11
MacOS 12.4
Ubuntu 22.04

Auto complete works with `NA` and other keywords.

**Comment by jonvanausdeln** [comment]
This is happening again. I am able to reproduce in 2022.12.0-daily+248.  I verified that it was working correctly in a daily from a month ago, so perhaps #12102 caused the regression.

**Comment by romainfrancois** [comment]
Thanks. I'll follow up in the morning.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+257
Windows 11, MacOS 12.4

Regression fixed. Works on expected keywords again.

**Comment by lafarola** [comment]
Having this issue with list names using numbers (used to work fine):

list_name <- list("2022" = c(1, 2, 3))

Autocomplete will not provide the tickmarks:

![backticks1](https://github.com/rstudio/rstudio/assets/128663752/db462b68-f10d-438e-946b-a178b7f02469)

![backticks2](https://github.com/rstudio/rstudio/assets/128663752/43a28686-face-48d3-ab06-b641547cce5c)

Tried in RStudio-2023.03.1-446 and RStudio-2023.06.0-421

**Comment by jonvanausdeln** [comment]
@lafarola , thank you for reporting this.  I have opened a new issue (https://github.com/rstudio/rstudio/issues/13290) to track this.
