### ISSUE TITLE
Proposal: Reorganize release notes by major release instead of patch date

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11504]
On [the Release Notes page](
https://www.rstudio.com/products/rstudio/release-notes/), the section labeled "Previous Release Notes" is ordered by when a patch was released. Maybe we should organize them by the major release, so that all of the Prairie Trillium release notes are grouped together, then Ghost Orchid, etc.? This is comparable to the organization of [Releases under the Dailies subsite](https://dailies.rstudio.com/release/).

I can see the advantage of the current ordering and proposed grouping, hence the *maybe*.

**Release Notes**
<img width="588" alt="release_notes" src="https://user-images.githubusercontent.com/31009952/175970358-ceb823d3-d847-493c-a21f-211e32e7f526.png">

**Releases**
<img width="419" alt="releases" src="https://user-images.githubusercontent.com/31009952/175970587-375212a5-0198-44fd-8430-b95afdbf7005.png">

**Comment by AshleyHenry15** [comment]
This [PR](https://github.com/rstudio/rstudio-pro/pull/4302) will remediate this issue

**Comment by melissa-barca** [comment]
Ashley is handling the majority of this work in #12745, assigning to myself as well to handle the Jenkins job to build and upload the docs.

**Comment by ronblum** [comment]
We're adding this to the release checklist, since we can't check it till we go live. It's not part of the build, though, so we can close this as complete.
