### ISSUE TITLE
No local option when selecting Zotero Library in RStudio Workbench

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#11512]
This is split-out from #9878. I guess it may be because RStudio Workbench cannot see the per user Zotero installation.

### System details

RStudio 2022.07.0-preview+536.pro1 "Spotted Wakerobin" Preview (fffe2a175effa52e77868d7f6d8b30509bd4e117, 2022-06-21) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

    RStudio Edition : Workbench
    RStudio Version : 2022.07.0-preview+536.pro1
    OS Version      : Ubuntu 20.04
    R Version       : 4.2.1

### Steps to reproduce the problem

Open global RMarkdown settings, click on the Citations tab and click on the drop-down menu next to Zotero Library: 

![image](https://user-images.githubusercontent.com/1825120/176037798-7a31f9a1-ddb9-40ab-9c34-00e2b9b4f0cd.png)

### Describe the problem in detail

There is no Local option

### Describe the behavior you expected

I expect there to be a Local option as there is in the Desktop version, or at least documentation on how to add a Zotero library on the host computer.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Robinlovelace Thanks for filing this! I was just looking back to see if this was an bug or an oversight—which I would've missed!—but it's by design: Requiring RStudio Desktop is mentioned at [the end of the visual markdown section about Zotero](https://rstudio.github.io/visual-markdown-editing/citations.html#citations-from-zotero). So, I'll mark this as an enhancement to consider.
