### ISSUE TITLE
set language spelling check at document level or at project level

### ISSUE THREAD

**Issue by xtimbeau** [rstudio/rstudio#11513]
It would be nice to set option for language spelling check in the yaml part of a qmd or rmd. When working with mulitple language it is annoying to go through global option to set that. A middle ground would be to set it at the project level, even if it is not unsual to work with different laguages inside the same project.

**Comment by ronblum** [comment]
@xtimbeau Thank you for the suggestion! I'll mark it for review as we continue development of RStudio.
