### ISSUE TITLE
opening link in new tab from viewer window/panel spawns blank viewer window

### ISSUE THREAD

**Issue by Karel-Kroeze** [rstudio/rstudio#11514]
Note that this bug seems identical to #2767, but that was closed without a resolution for the initial report. I was unable to find any other issues related to the same problem.

### System details
    RStudio Edition : Desktop
    RStudio Version : 2022.02.3 Build 492
    OS Version:  Windows 10 Pro (21H2, 19044.1766)
    R Version:  4.1.3   (x86_64-w64-mingw32/x64)

### Steps to reproduce the problem
The problem manifests itself slightly differently in the viewer _panel_ and the viewer _window_.

In both the panel and window, render any {shiny, markdown, etc.} document with a link in the viewer. Force the link to open in a new tab (e.g. by holding <kbd>Ctrl</kbd> while clicking the link). The link opens in the system browser, but a blank rstudio window is also opened. Note that #2767 references using "open in a new tab" from the right-click context menu, but this option seems to have been removed (perhaps as a mitigation for this issue?).

The below rmarkdown (copied from #2767) is enough to show the problem:
```md
---
title: "Untitled"
output: html_document
---

<https://www.rstudio.com>
```

In addition, in the viewer _window_ only, an anchor tag with `target="_blank"` also triggers rstudio to open an empty viewer window when clicked (without any modifier keys). Note that this behaviour does not seem to occur for such links in the preview _panel_.

The below minimal shiny app is enough to show the problem:
```R
library(shiny)

ui <- fluidPage(
    htmlOutput("test")
)

server <- function(input, output) {
    output$test <- renderPrint(tags$a(href="https://rstudio.com", target="_blank", "rstudio.com"))
}

shinyApp(ui = ui, server = server)
```

### Describe the problem in detail
Opening links in a new tab in the viewer opens the expected content in the system browser, but also an empty rstudio viewer window.

### Describe the behavior you expected
The content should open in the system browser without opening an empty rstudio window.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Karel-Kroeze** [comment]
I just realised the shiny example is overly complicated, please don't hold that against me...

**Comment by ronblum** [comment]
@Karel-Kroeze Thank you for raising this, as well as for opening a new issue—from what I can tell, it looks like we addressed the issue with the buttons but not similarly with using <kbd>Ctrl</kbd> or <kdbc>Cmd</>. I can reproduce this on RStudio Desktop 1.4.1717 and 2022.07.0-preview+543 on MacOS.

And no problem with the issue—it's pretty short and simple as is! Although if you would like to provide another example, by all means, do! 🙂
