### ISSUE TITLE
Restoring session with a package being `load_all()`

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#11527]
```
2022-06-29T09:19:18.349105Z [rsession-romainfrancois] ERROR r error 4 (Error in library(packageName, character.only = TRUE) : 
  ‘dplyr’ is not a valid installed package
) [errormsg: Error in library(packageName, character.only = TRUE) : 
  ‘dplyr’ is not a valid installed package
, context: Error restoring session data (loading package dplyr)]; OCCURRED AT rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:198; LOGGED FROM: void rstudio::r::session::search_path::(anonymous namespace)::loadPackage(const std::string &, const std::string &) src/cpp/r/session/RSearchPath.cpp:202
```

**Comment by mikebessuille** [comment]
@romainfrancois Can you please describe a reprex for this?  Not sure the circumstance where you got this message

**Comment by kevinushey** [comment]
This reproduces the issue consistently for me:

1. Open an R package project,
2. Execute `devtools::load_all()`,
3. Use <kbd>Cmd + Shift + B</kbd> to rebuild the package,
4. Wait for the session to restart.

When RStudio tries to restore the session data, things go awry:

> 2022-07-14T17:40:00.609923Z [rsession-kevin] ERROR r error 4 (Error in library(packageName, character.only = TRUE) :
>   'renv' is not a valid installed package
> ) [errormsg: Error in library(packageName, character.only = TRUE) :
>   'renv' is not a valid installed package
> , context: Error restoring session data (loading package renv)]; OCCURRED AT rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:198; LOGGED FROM: void rstudio::r::session::search_path::(anonymous namespace)::loadPackage(const std::string &, const std::string &) src/cpp/r/session/RSearchPath.cpp:202
> 2022-07-14T17:40:00.609923Z [rsession-kevin] ERROR r error 4 (Error in library(packageName, character.only = TRUE) :
>   'renv' is not a valid installed package
> ) [errormsg: Error in library(packageName, character.only = TRUE) :
>   'renv' is not a valid installed package
> , context: Error restoring session data (loading package renv)]; OCCURRED AT rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:198; LOGGED FROM: void rstudio::r::session::search_path::(anonymous namespace)::loadPackage(const std::string &, const std::string &) src/cpp/r/session/RSearchPath.cpp:202
