### ISSUE TITLE
Ability to access "horizontal rule" with the word "line" in the insert anything tool in the visual editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#11532]
When I want to insert a horizontal line to my document when using the visual editor, my instinct is almost always to look for it using the keyword "line" but this doesn't bring up "horizontal rule" as an option. I think folks who don't know the html `<hr>` tag won't think to look it up with "rule" as the keyword. It would be nice if the insert anything tool brought up "horizontal rule" as an option with the keyword "line".

**Comment by ronblum** [comment]
Proposal: Reverse this, so that we change the name to "Horizontal Line" but make the keyword "rule" work, as well.

**Comment by mine-cetinkaya-rundel** [comment]
Even better!

**Comment by mine-cetinkaya-rundel** [comment]
I'd still love to see this happen!

**Comment by jjallaire** [comment]
Great idea, implemented here: https://github.com/quarto-dev/quarto/commit/61fee2a549d7c549c708f06d4f93bd765c922f2c

**Comment by ronblum** [comment]
Verified in 2023.03.0-daily+312 on MacOS 13.2.

- Both "rule" and "line" match the option.
- The option is now "Horizontal Line."
