### ISSUE TITLE
Quarto header-includes gets lost when publishing to RPubs

### ISSUE THREAD

**Issue by cbrnr** [rstudio/rstudio#11533]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.0 Build 544
    OS Version      : macOS
    R Version       : 4.2.0

### Steps to reproduce the problem
Create the following Quarto document:

```
---
title: "Untitled"
format:
  revealjs:
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet"/>
    footer: |
      <i class="fa-solid fa-envelope"></i>
      <i class="fa-brands fa-chrome"></i>
      <i class="fa-brands fa-twitter"></i>
      <i class="fa-brands fa-github"></i>
---

## Quarto
It seems like `header-includes` gets lost when publishing the presentation on RPubs.
```

### Describe the problem in detail
I'm including some Font Awesome icons by specifying a corresponding `header-includes` as suggested in https://github.com/quarto-dev/quarto-cli/issues/859. When publishing the presentation to RPubs, the icons are not rendered correctly (just squares). Here is the rendered version: https://rpubs.com/cbrnr/quarto-header-includes

### Describe the behavior you expected
I expected the Font Awesome icons to be rendered on RPubs, because I specified the necessary `header-includes`, and it works locally.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@cbrnr Thank you for raising this! I can reproduce the issue using RPubs. It works with RStudio Connect. I'll tag this as a bug, but I'm also going to check internally whether we should file this another repo.

**Comment by jcheng5** [comment]
When RStudio publishes the qmd to RPubs, it invokes quarto with `--self-contained`:
https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/cpp/session/modules/SessionRPubs.cpp#L382

And that doesn't work for some reason. Try `quarto render example.qmd --self-contained` for the local repro.
