### ISSUE TITLE
Viewer Pane results in refused connection and missing buttons for Quarto website

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11540]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.07.0-preview+545
    OS Version      : MacOS 12.5, openSUSE 15 SP3, Ubuntu 20.04 via Chrome on MacOS 12.5
    R Version       : 4.2.0/1

### Steps to reproduce the problem

1. Create a new Quarto Website project.
2. In the `index.qmd` file, use the gear to set "Preview in Viewer Pane."
3. <kbd>Render</kbd>
4. In the Viewer Pane, click on the left arrow.
    - In RStudio Desktop: 
        a. In the Viewer Pane, the left and right arrow buttons disappear.
        b. A web browser window opens with the message "127.0.0.1 refused to connect."
    - In RStudio Server:
        a. In the Viewer Pane, the left and right arrow buttons disappear.
        b. Also in the Viewer Pane, the message "Connection refused" appears.

### Describe the problem in detail

See above.

### Describe the behavior you expected

The arrow buttons should work. Clicking on the left arrow before the site is traversed should result in no action.

Triage: Proposal for Spotted Wakerobin patch, or else Elsbeth Geranium.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: If you re-render the document, it’ll preview again, but the buttons don’t come back. To get the buttons back you have to close and reopen the project.

**Comment by ronblum** [comment]
Also:
1) Re-render the site. This works.
2) Click on the left arrow. This results in a blank page, although the arrows remain. Clicking on the right arrow doesn’t do anything.
3) Re-render: nothing happens.
4) Clear out the Viewer Pane with the white-X-in-a-red-circle button.
5) Re-render: This works. We're back at step 1, though.

**Comment by mikebessuille** [comment]
Discussion here: https://rstudio.slack.com/archives/C03MEDU5E80/p1656608158234879

**Comment by timtmok** [comment]
It might be that it works on the re-render because the first attempt tried to display the preview before it was ready. More investigation is required.

**Comment by romainfrancois** [comment]
This ends up here: 

https://github.com/rstudio/rstudio/blob/b2e50d10a59260a0b1a0f4376833cdbf45d7a06b/src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/quarto/QuartoConnection.java#L156-L162

and then IIUC the `postMessage()` function is implemented in quarto, in one of these I guess: https://github.com/quarto-dev/quarto-cli/search?q=postMessage

**Comment by jjallaire** [comment]
I am going to be reworking all of the Quarto preview stuff in the next week or so, so this issue should get resolved as part of that.

**Comment by ronblum** [comment]
Verified that the buttons no longer disappear in RStudio Desktop 2022.12.0-daily-280 in MacOS 13 and openSUSE 15.4. Traversing between pages works, and the buttons always remain.

However, if the left button is clicked on the first page that was presented, the contents of the pane are cleared, after which the left and right arrows don't restore the content.

https://user-images.githubusercontent.com/31009952/197202981-8f0f88cc-659b-4843-acf0-99a3d6bee386.mov

**Comment by kevinushey** [comment]
One option would be to ask Quarto to clear the page history after being loaded via the IDE.

https://github.com/quarto-dev/quarto-cli/blob/530ee04da60100b571eca85709250a6a7d19f96f/src/resources/editor/devserver/devserver-viewer.html#L6-L16

That way, attempting to click Back wouldn't return to the "empty" first page.

**Comment by mikebessuille** [comment]
@jjallaire are you able to update this per Kevin's suggestion?

**Comment by mikebessuille** [comment]
@jgutman JJ says this is purely in the IDE.  Quarto doesn't maintain a page history.  I'm not sure the remaining issue is really that critical.  Perhaps we should log a separate issue for that, put it in a later milestone, and close this.
