### ISSUE TITLE
RStudio Electron for macOS - extra period auto-inserted by editor when typing spaces

### ISSUE THREAD

**Issue by anwhite003** [rstudio/rstudio#11545]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.02 B 545 Electron
    OS Version      : macOS 12.4 Monterey
    R Version       : 4.2.0 
    Computer: iMac 2020 Intel Core i9

### Steps to reproduce the problem
1. Create a new R Code File in Source Pane2; Type a "#" and then quickly tap spacebar 3 times
2. Result is an unwanted "." is entered by the editor. 
<img width="476" alt="Screen Shot 2022-07-03 at 11 32 58 AM" src="https://user-images.githubusercontent.com/12756355/177057895-319a3e4d-523e-4e88-8a7d-eaa7bafba2f7.png">
## Describe the problem in detail
RStudio Electron for macOS uses default text editor behavior of adding a "." when multiple spacebar taps are made.
### Describe the behavior you expected
No unwanted "." should be entered by the editor!

- [y ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [y ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by anwhite003** [comment]
Update: while I did not observe this behavior before in R Code editing with macOS, 
there is an easy fix on a Mac and with macOS: 
Simply go to Settings - Keyboard - Text, and turn off (un-check) the option for auto-ending a sentence with a periodby tapping spacebar twice.
End of Issue.

**Comment by ronblum** [comment]
@anwhite003 I'm going to keep this open to consider as a bug.

@gtritchie  This happens not just with comments, but also with R code, and similarly in R Markdown and Quarto chunks. Is this correct behavior, or should we override it for code blocks?
