### ISSUE TITLE
Bad signature on RStudio Desktop 2022.02.3 build 492 for Ubuntu 22

### ISSUE THREAD

**Issue by AutumnInfandino** [rstudio/rstudio#11559]
### System details

    RStudio Edition : RStudio Desktop
    RStudio Version : 2022.02.3 build 492
    OS Version      : Ubuntu 22 (debian-package)

there is a bad signature on the current installer of RStudio Desktop
2022.02.3 build 492 for Ubuntu 22 (debian-package). The sha256 checksum
is ok, while the signature is not.

Expected behavior (tested on the Ubuntu 18+ installer):
> sha256sum -c rstudio-2022.02.3-492-amd64.sha256
rstudio-2022.02.3-492-amd64.deb: OK
> dpkg-sig --verify rstudio-2022.02.3-492-amd64.deb
Processing rstudio-2022.02.3-492-amd64.deb...
GOODSIG _gpgbuilder FE8564CFF1AB93F1728645193F32EE77E331692F 1653075733

Observed behavior on the Ubuntu 22 installer:
> sha256sum -c rstudio-2022.02.3-492-amd64.sha256
rstudio-2022.02.3-492-amd64.deb: OK
> dpkg-sig --verify rstudio-2022.02.3-492-amd64.deb
Processing rstudio-2022.02.3-492-amd64.deb...
BADSIG _gpgbuilder

For security reasons this should be fixed.

**Comment by jmcphers** [comment]
Notes for QA: Make sure that you validate the expected case before reproducing the failure mode (since an easy way to fail signature validation is to incorrectly import the public key).

**Comment by Code2Farm** [comment]
The problem persists on yesterdays release of RStudio 2022.07.0+548

Tested on Ubuntu 22 installer:
```
dpkg-sig --verify rstudio-2022.07.0-548-amd64.deb
BADSIG _gpgbuilder
```

Tested on Ubuntu 18 installer:
```
dpkg-sig --verify rstudio-2022.07.0-548-amd64.deb
GOODSIG _gpgbuilder FE8564CFF1AB93F1728645193F32EE77E331692F 1657147404
```

**Comment by timtmok** [comment]
I've got a reprex by creating my own gpg key and signing something on Ubuntu 22. The default compression type was changed to `zst`. I've verified by extracting the Ubuntu 22 and 18 debs and seeing that the compression types are different. Ubuntu 18 uses `xz` and Ubuntu actually had the same problem when switching to `xz` before adding support to `dpkg-sig` to verify this compression type.

So I'm trying to switch the compression type to `xz`, which is supported in `dpkg-sig` for verification. My reprex passes when packaging the same test files using `xz`.

See https://bugs.launchpad.net/ubuntu/+source/dpkg-sig/+bug/1342938 for more details about the `xz` compression type introducing this in Ubuntu 14.04. This is the same issue but now with `xz -> zst`.

**Comment by timtmok** [comment]
I've verified the change in `main`. It's building in `spotted-wakerobin` now.

**Comment by timtmok** [comment]
https://www.rstudio.com/code-signing/ are the instructions to adding the public key. Otherwise, the verification will return an error that the signature is unknown.

**Comment by ronblum** [comment]
Created backport issue #11559 to track this in Spotted Wakerobin and keeping this for Prairie Trillium.

**Comment by ronblum** [comment]
Verified in RStudio Server 2022.02.4+500 on Ubuntu 22.04.

```
root@vmware:/home/vmware# gpg --delete-key 3F32EE77E331692F
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


pub  rsa4096/3F32EE77E331692F 2017-10-18 RStudio, Inc. (code signing) <info@rstudio.com>

Delete this key from the keyring? (y/N) y
root@vmware:/home/vmware# gpg --keyserver keyserver.ubuntu.com --recv-keys 3F32EE77E331692F
gpg: key 3F32EE77E331692F: public key "RStudio, Inc. (code signing) <info@rstudio.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@vmware:/home/vmware# dpkg-sig --verify  rstudio-server-2022.02.4-500-amd64.deb
Processing rstudio-server-2022.02.4-500-amd64.deb...
GOODSIG _gpgbuilder FE8564CFF1AB93F1728645193F32EE77E331692F 1661548505
root@vmware:/home/vmware# dpkg-sig --verify  rstudio-server-2022.02.3-492-amd64.deb 
Processing rstudio-server-2022.02.3-492-amd64.deb...
BADSIG _gpgbuilder
```
