### ISSUE TITLE
RStudio constantly crashing (Session Aborted/Javascript Error)

### ISSUE THREAD

**Issue by woodwards-dnz** [rstudio/rstudio#11550]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.3
    OS Version      :  Windows 10 
    R Version       :  4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

RStudio often crashes a few seconds after starting. Alternatively crashes after switching to a new project, or may be associated with opening the Files pane, possibly git, possibly conflict old versions of .Rproj.user. Problem was not associated with any updates and was also occurring with an older version of the IDE. A particular project seems to crash it more often.

### Describe the problem in detail

RStudio crashes with "R Session Aborted" or else "Javascript Error". I have the latest version of Java 333 installed.

### Describe the behavior you expected

RStudio running stably.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9042895/diagnostics-report.txt)

**Comment by ronblum** [comment]
@woodwards-dnz Thank you for raising the issue and for the diagnostics report! I notice that you're using a directory called OneDrive, and we've seen similar issues with remote storage.
- Are your files stored on Microsoft OneDrive?
- If so, do you run into the issue with locally-stored files?

Thanks!

**Comment by woodwards-dnz** [comment]
Yes the files are stored on OneDrive. Probably this was the issue.

I did a complete reinstall of R and RTools and RStudio (all on C:) and things are working now.

**Comment by ronblum** [comment]
@woodwards-dnz Thank you for checking! Good to know that it now works. I'm leaving this open, since the error itself is a little different from other remote drive issues (though the ultimate cause might be the same).

**Comment by cbccbcc** [comment]
HI! I have encountered similar issue, when I was running ergm model with two sub-graphs, R studio constantly aborted. Do I need to increase the memory or what should I do?
