### ISSUE TITLE
Add a word count to visual editor

### ISSUE THREAD

**Issue by arhot** [rstudio/rstudio#11551]
With various types of reports, there's a word count limit. When writing in the visual editor mode, it would be nice to see/get a ballpark estimate of word count (obviously not fully correct because of code generating text and biography generated on rendering, but something). A simple count of words outside the code chunks would do, whether visible all time somewhere in the pane margins (Word-style), or as a function/menu command to be run to get a current count in the console.

An add-on exists currently for this, wordcountaddin, but it does not work with the visual mode, and getting a count requires switching to source mode and back.

**Comment by arhot** [comment]
It does, I am an idiot and didn't find it. Thank you and sorry about the unnecessary suggestion..

**Comment by ronblum** [comment]
@arhot Haha no problem at all! After nearly five of testing the IDE, I still forget where some options are or that we even have them. 🙂 FWIW I find the Command Palette useful, with <kbd>Shift-Opt-P</kbd> and <kbd>Shift-Ctrl-P</kbd>.

**Comment by ronblum** [comment]
@arhot And I came across issue #11554 while looking at what you raised, so you indirectly helped find a bug!
