### ISSUE TITLE
Offer to commit and push git changes on exit from Rstudio

### ISSUE THREAD

**Issue by thk686** [rstudio/rstudio#11556]
A nice addition to Rstudio would be an optional setting that reminds the user of uncommitted changes and any different from origin when exiting the application. I am aware that commits should represent a coherent bundle of changes rather than a single editing session. Nonetheless, when I am working on multiple machines and in remote places, pushing changes upstream becomes important to avoid losing work or having different machines out-of-sync. If Rstudio could optionally run a `git status` or other commands on exit and offer to commit-push, that would be a helpful reminder. It does not need to be on by default and can easily be declined.

**Comment by ronblum** [comment]
@thk686 Thank you for the interesting suggestion! It sounds like it would be similar, at least in principle, to the way that the IDE checks for unsaved files in the editor. We'll review the request as we continue development of RStudio.

**Comment by MohdAzmiSuliman** [comment]
any update on this suggestion? or was it has already implemented? if it is already implemented, how to set it so that a reminder or prompt on changes that were not committed will pop up every time exiting rsudio?
