### ISSUE TITLE
Find in files does not return results on Mac with submodule recurse = true in the .gitconfig

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#11564]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 2022.07.0+547 & 2022.07.0+547.pro6
    OS Version         : Mac 11.6.5
    R Version            : 4.1.2
    Git Version         : 2.37.0

### Steps to reproduce the problem

1. Set the following in your .gitconfig file:
```
[submodule]
	recurse = true
```
2. Open Rstudio and do a search Edit -> Find in files... for text in a git project that has that text in a file in that project.

Note: For debugging you can create a `.Renviron` file in your home directory and add `RSTUDIO_GREP_DEBUG=TRUE` to see debug info in the console after searching.

### Describe the problem in detail
There are no results returned. This seems to not show any results even when searching outside of the git project. The console output for debugging shows 

`grep '--binary-files=without-match' '-rHn' '--color=always' '--devices=skip' '-i' '-F' '-f' '/var/folders/3h/p1jkz7f14glc1h5xdj44zh240000gn/T/Rtmpkf2r2O/rs_grep15b9524c9f96.txt'
git '-c' 'core.quotepath=false' '-c' 'grep.lineNumber=true' '-c' 'grep.column=false' '-c' 'grep.patternType=default' '-c' 'grep.extendedRegexp=false' '-c' 'grep.fullName=false' '-C' '/Users/andrewtayler/Documents/RStudio Testing/qa' 'grep' '-I' '--untracked' '--no-exclude-standard' '-rHn' '--color=always' '-i' '-F' '-f' '/var/folders/3h/p1jkz7f14glc1h5xdj44zh240000gn/T/Rtmpkf2r2O/rs_grep15b9574813207.txt'
stderr: fatal: option not supported with --recurse-submodules`

![Screen Shot 2022-07-06 at 9 39 34 AM](https://user-images.githubusercontent.com/1482677/177610598-f4e669d8-fa8d-4ae0-b713-feca2e4fb017.png)

### Describe the behavior you expected

I would expect to see results returned. Below is a side-by-side search with a PT build (2022.02.4-496.pro1) on the left vs a SW build on the right.

![Screen Shot 2022-07-05 at 2 40 02 PM](https://user-images.githubusercontent.com/1482677/177610612-f0e0d014-9308-4bf0-ade3-624bf3711dd1.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
Related: https://stackoverflow.com/questions/18810904/how-to-git-grep-the-main-repository-and-all-its-submodules

reports a fatal error when `git grep` is used with the `--recurse-submodules` and `--no-index` flags as in this example. AT was originally using Git version 2.23.0, and this was supposedly fixed in 2.25.1, but apparently he's still seeing the error after upgrading git grep

**Comment by kevinushey** [comment]
I see a slightly different error:

```
git '-c' 'core.quotepath=false' '-c' 'grep.lineNumber=true' '-c' 'grep.column=false' '-c' 'grep.patternType=default' '-c' 'grep.extendedRegexp=false' '-c' 'grep.fullName=false' '-C' '/Users/kevin/rstudio' 'grep' '-I' '--untracked' '--exclude-standard' '-rHn' '--color=always' '-i' '-F' '-f' '/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/Rtmp7DEHFp/rs_grepf7cf5a10a1fa.txt'
stderr: fatal: --untracked not supported with --recurse-submodules
```

We could probably work around this by setting `-c submodules.recurse=false`.

**Comment by jgutman** [comment]
Opening for QA

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-82
MacOS 12,4, Win11, Ubuntu 22.04

Tried several different search params, all worked as expected.
