### ISSUE TITLE
avoid loading reticulate on startup

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11566]
### System details

    RStudio Edition : 2022.07.0+547
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.4
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

Start an R session, and then execute `loadedNamespaces()`.

### Describe the problem in detail

A number of packages are loaded (primarily, `reticulate` and its dependencies).

```
> loadedNamespaces()
 [1] "compiler"   "here"       "Matrix"     "rprojroot"  "graphics"   "tools"     
 [7] "utils"      "grDevices"  "Rcpp"       "reticulate" "stats"      "datasets"  
[13] "grid"       "methods"    "jsonlite"   "base"       "png"        "lattice"   
```

### Describe the behavior you expected

We shouldn't load R packages without an explicit user gesture. Note that this issue is pretty severe for Windows users as they will effectively be unable to update or re-install any of the above packages.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] rlang_1.0.3

loaded via a namespace (and not attached):
 [1] compiler_4.2.0       here_1.0.1           Matrix_1.4-1        
 [4] rprojroot_2.0.3      cli_3.3.0            tools_4.2.0         
 [7] rstudioapi_0.13      Rcpp_1.0.8.3         crayon_1.5.1        
[10] reticulate_1.25-9000 grid_4.2.0           jsonlite_1.8.0      
[13] png_0.1-7            lattice_0.20-45     
```

</details>

**Comment by kevinushey** [comment]
Some debugging points to `.rs.inferReticulatePython()`, which may load Python here:

https://github.com/rstudio/rstudio/blob/d5a1bc209137589551f02a357ba88d0c74ef3e05/src/cpp/session/modules/SessionReticulate.R#L2085-L2108

And that's likely being invoked here on startup:

https://github.com/rstudio/rstudio/blob/d5a1bc209137589551f02a357ba88d0c74ef3e05/src/cpp/session/modules/SessionReticulate.cpp#L46-L69

We either need to tweak how we infer the default version of Python to be used on startup, or adjust `.rs.inferReticulatePython()` so that it doesn't try to load reticulate to infer the default version of Python. (For example, we could have it run R in a sub-process?)

**Comment by jmcphers** [comment]
Do we need to load Python version info at startup? (maybe we could defer until the first time Python is used?)

Alternately, how complicated/self-contained is `py_discover_config`? (maybe we could just have our own copy of that function in the IDE)

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.07.0+548 on MacOS 12.5
- RStudio Desktop 2022.07.0+548 on Red Hat 8.5
- RStudio Desktop 2022.07.0+548 on Windows 11
- RStudio Server 2022.07.0+548 on SLES 15 SP3 via Chrome on MacOS 12.5
