### ISSUE TITLE
Electron loads wrong/unexpected version of R with Brew

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#11567]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2022.10.0 Electron any
    OS Version      :  Mac OS 12.4 M1
    R Version       : any

### Steps to reproduce the problem
1. Install R with `brew`
2. Set path to point to non-brew R
3. Set `RSTUDIO_WHICH_R` environment variable in terminal to point to non-brew R
4. Launch RStudio Electron
5. Run `R.home()` and check which R version is being loaded

### Describe the problem in detail

Electron seems to point to the wrong version of R, even if there is another R higher on the path, even if there is a symlink to another R in `/usr/local/bin/R`, even if RSTUDIO_WHICH_R points to another version of R. The wrong R seems to be chosen

### Describe the behavior you expected

1. Respect the RSTUDIO_WHICH_R env var even when not launched from a terminal
2. Prefer the R that comes first in the user's path if RSTUDIO_WHICH_R is not set

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
It would be nice if we could get RSTUDIO_WHICH_R and which R actually returned the same values as user's default shell, which is not currently the case. But this PR at least aligns electron behavior with former Qt behavior on macs

**Comment by jonvanausdeln** [comment]
Verified on:
2022.11.0-75
MacOS 12.4

Verified R version. Also noted that issue with env variable changes in zsh are still not picked as noted in the PR fix.
