### ISSUE TITLE
RStudio electron doesn't seem to respect options in /etc/rstudio/logging.conf

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11565]
Noticed while debugging with @jgutman.

**Comment by gtritchie** [comment]
Also see #10929.

Correct, the desktop code (Electron main process) logging doesn't currently pay attention to logging.conf. If we want to do this, we'd also need to consider how it behaves on Windows (where `/etc/rstudio` isn't really a thing).

**Comment by mikebessuille** [comment]
Is this the same behaviour in QT?

**Comment by jgutman** [comment]
No
