### ISSUE TITLE
R session aborted with fix()

### ISSUE THREAD

**Issue by mengmx01** [rstudio/rstudio#11570]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.3+492
    OS Version      : windows 8
    R Version       : 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem
`fix()` function aborts R studio session and forces a restart when used on a 2d variable (e.g. data frame, n*n matrix).
### Describe the problem in detail
This is rstudio specific because `fix()` in Rgui does not abort session. Using `fix()` on 1d variables e.g. vectors doesn't run into errors.
### Describe the behavior you expected
R studio should pop a window for viewing the data/variable, instead of aborting the session

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mengmx01 Thank you for raising the issue! I'm unable to reproduce it, though. Can you provide a minimal example so that I can try to reproduce the issue by matching exactly what you're running?

**Comment by mengmx01** [comment]
@ronblum 
This is a piece of code that runs into an abortion:
`a=matrix(c(1,2,3,4),nrow=2)`
`fix(a)`
same with
`a=matrix(c(1,2),nrow=1)`
`fix(a)`
but 
`a=c(1,2)`
`fix(a)` will not run into this issue

As soon as the variable gains a dimension like n*m, running `fix()` will abort R studio
Hope this clarifies the question :)
