### ISSUE TITLE
Color highlighting for CSS files

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#11587]
As an extension of #11546, it would be extra awesome to extend the color highlighting, currently available in strings in R code, to other places where colors are defined. In particular, CSS and SASS/SCSS files (or chunks).

(The limitation to R code only is [mentioned here](https://github.com/rstudio/rstudio/issues/5424#issuecomment-1178965382))

**Comment by gadenbuie** [comment]
Here's a quick reprex Rmd based on the example in the comment linked above

````
---
title: "Color Preview"
output: html_document
---

## R code

```{r}
colors <- c(
  "#7DBFE9","#603A19","#000000","#F57F26","#F57F26","#F57F26","#F57F26","#F57F26",
  "#F398C1","#7DBFE9","#603A19","#000000","#FCEE1A","#FCEE1A","#FCEE1A","#FCEE1A"
)
```

## CSS and friends

```{css}
.rainbow {
  color: #7dbfe9;
  background-color: #603A19;
  border-color: #FCEE1A;
}
```

```{scss}
$primary: #7dbfe9;
$secondary: #603A19;

.rainbow {
  color: $primary;
  background-color: $secondary;
  border-color: #FCEE1A;
}
```
````

**Comment by jmcphers** [comment]
This would be really helpful for people who develop web content in RStudio (Shiny apps, HTML widgets, etc.)

**Comment by mikebessuille** [comment]
@romainfrancois how easy would this be to add?

**Comment by kevinushey** [comment]
I think this would be relatively straightforward; we'd just need to force the CSS highlight rules from Ace and then add our own color rules (borrowing from, or sharing, the implementation for R)

**Comment by ronblum** [comment]
Tried in RStudio Server 2022.11.0-daily+202 on Ubuntu 20.04 in Chrome via MacOS 13.

The CSS and R blocks reflect the colors. SCSS doesn't, though. Is this intentional or does it need to be included?

![Image](https://user-images.githubusercontent.com/31009952/191764488-e33207cd-da28-4e1b-9bf2-b6853a139589.png)

**Comment by romainfrancois** [comment]
Thanks @ronblum; I'll add scss

**Comment by romainfrancois** [comment]
QA note: #12031 has `.scss`, `.sass` and `.less` files and an `Rmd` file with ` ```scss` etc  chunks

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+257
Windows 11 Desktop, Ubuntu 22.03 Server

All colors highlighted as expected in original example.
