### ISSUE TITLE
`crayon::silver()` no longer appears correctly

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11586]
This may not be an Electron issue

It may be related to https://github.com/rstudio/rstudio/pull/11483

I am using:
RStudio theme: Modern
Editor theme: Tomorrow Night Bright

<img width="458" alt="Screen Shot 2022-07-08 at 12 28 06 PM" src="https://user-images.githubusercontent.com/19150088/178043278-51ac81d1-e18e-4cac-a516-0ca1556e118c.png">

You can see that the text is there if you highlight it in the console manually

<img width="449" alt="Screen Shot 2022-07-08 at 12 30 38 PM" src="https://user-images.githubusercontent.com/19150088/178043280-9346fa66-f3eb-4907-a695-529ddce753fb.png">

RStudio 2022.10.0-daily+55 "Elsbeth Geranium" Daily (f895778c3e83e20672af1434f040a31b8f2cf906, 2022-07-07) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.10.0-daily+55 Chrome/102.0.5005.115 Electron/19.0.6 Safari/537.36

**Comment by gtritchie** [comment]
Confirmed this isn't specific to Electron; repros in open-source Server (in Chrome) as well.

**Comment by DavisVaughan** [comment]
This resource tells me that xterm color 8 is grey:
https://www.ditig.com/256-colors-cheat-sheet

And it looks like in #11483, xterm color 8 for my IDE theme was set to `#000000` aka black
https://github.com/rstudio/rstudio/pull/11483/files#diff-f09846daa26b8c2ba1dd0ca38d0a09674a43380c5b996038228529d8824fe5acR206

And then on the crayon side, it looks like crayon maps the ANSI foreground color of `"grey"` to be what crayon `silver()` returns
https://github.com/r-lib/crayon/blob/8b206a8d675d11f59492339fd6c798240c0bb17a/R/styles.r#L64

So I think that explains it? So it does seem like the problem stems from that PR, not sure why it is using black for the "grey" xterm color

**Comment by cderv** [comment]
I also encounter that within the Terminal on Windows. Grey (silver-like) color is not visible : 

This is in Windows Terminal 
![image](https://user-images.githubusercontent.com/6791940/178314415-bb0d591a-b98c-43c6-af58-204dbe13dfcd.png)

This is in the latest daily of the IDE
![image](https://user-images.githubusercontent.com/6791940/178314791-5f9d20a9-4cce-48ef-b3fc-9877da46793f.png)

Probably brings no more information, but just wanted to confirm that this happens also in Terminal part. I am also using Tomorrow night bright

**Comment by ronblum** [comment]
Triage: See consideration for backport to Spotted Wakerobin.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-82
MacOS 12.4, Windows11, Ubuntu 22.04

Tested several themes and color combinations.
