### ISSUE TITLE
"Select all" with CMD+A in Find/Replace menu doesn't work with latest Electron Elsbeth build

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11581]
If you open the find/replace menu and type in something to "find", then CMD+A won't highlight the whole word anymore.

I'm doing it in the video, you just can't see it (because nothing happens):

https://user-images.githubusercontent.com/19150088/178024164-39e4dde3-7f50-4165-87e8-2dc1922c2272.mov

RStudio 2022.10.0-daily+55 "Elsbeth Geranium" Daily (f895778c3e83e20672af1434f040a31b8f2cf906, 2022-07-07) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.10.0-daily+55 Chrome/102.0.5005.115 Electron/19.0.6 Safari/537.36

**Comment by DavisVaughan** [comment]
It also doesn't work correctly in "Go to File/Function", i.e. the menu you get with `Control + .` on a Mac

- `Control + .`
- Type in a function name
- Try to select all with `Cmd + A`

**Comment by DavisVaughan** [comment]
It also doesn't work in `Edit -> Find in Files`. The `Find:` box doesn't work with `Cmd + A` anymore.

**Comment by timtmok** [comment]
I've only been able to reproduce this so far on Mac. Linux and Windows work.

Something else seems to be responding to the keyboard event and preventing the select all.

**Comment by timtmok** [comment]
I'm still not sure of the root cause but I've got a workaround that replicates Qt behaviour.

**Comment by gtritchie** [comment]
I'll take a look at the PR by EOD (Edmonton time).

**Comment by jonvanausdeln** [comment]
Verified on:
2022.11.0-71
MacOS 12.4
Win11
Ubuntu 22.04

Select all works in the input fields in all the mentioned scenarios. Note, the 'wierd' behavior of hitting cmd+a while the 'next' button has focus still exists as it does in the QT version.

**Comment by kevinushey** [comment]
I reverted the PR in https://github.com/rstudio/rstudio/commit/94b86a9bd5821e293f17c1191b3846bae04d85f2; it caused issues with RStudio stealing Cmd + A even when other applications had focus.

**Comment by timtmok** [comment]
Throwing this to the backlog for now. I don't anticipate a fix for EG unless there's more info on why the editor doesn't get or respond to the hotkey event.

**Comment by jonvanausdeln** [comment]
Verified on:
2022.11.0-130
MacOS 12.4
Win11
Ubuntu 22.04
