### ISSUE TITLE
Documentation hover tooltip should disappear when your move your mouse off the text

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11588]
I think this new hover tooltip feature is really awesome, but I think it sticks around a little too long. If possible, I think it should disappear as soon as you move your mouse off the original text that prompted the tooltip to appear. Right now it waits until you click on something else or hover on some other link. It even sticks around when you scroll.

https://user-images.githubusercontent.com/19150088/178048575-d5e46629-d52b-4004-b13f-f0c11d534571.mov

RStudio 2022.10.0-daily+55 "Elsbeth Geranium" Daily (f895778c3e83e20672af1434f040a31b8f2cf906, 2022-07-07) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.10.0-daily+55 Chrome/102.0.5005.115 Electron/19.0.6 Safari/537.36

**Comment by romainfrancois** [comment]
QA notes:  see https://github.com/rstudio/rstudio/pull/11732

**Comment by ronblum** [comment]
Verified that the pop up will got away, in
- RStudio Desktop 2022.11.0+98 on MacOS 12.5 
- RStudio Server 2022.11.0+98 on Ubuntu 20.04 via Chrome on MacOS 12.5.

```
> cli::style_hyperlink("summarise", "ide:help:dpylr::summarise")
<cli_ansi_string>
[1] summarise
> cli::`style_hyperlink`(url = "http://rstudio.com", text = "RStudio")
<cli_ansi_string>
[1] RStudio
```

(`summarise` and `RStudio` are now hoverable and clickable.)

(Note: Used version 2022.07.1+554 as a comparison point. Also, this was the same test as #11664.)
