### ISSUE TITLE
Qt and Electron aren't respecting each other's Zoom setting

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11580]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.0-548 (Qt), 2022.07.0-548 (Electron), 2022.10.0-daily-55 (Electron)
    OS Version      : MacOS 12.5
    R Version       : 4.2.0

### Steps to reproduce the problem

1. Open a Qt version of RStudio Desktop.
2. Change the Zoom setting.
3. Close RStudio Desktop.
4. Open an Electron version of RStudio Desktop.
    - The Zoom setting doesn't match Qt's setting.
5. Change the Zoom setting.
3. Close RStudio Desktop.
4. Open a Qt version of RStudio Desktop.
    - The Zoom setting doesn't match Electron's setting.

### Describe the problem in detail

RStudio Desktop Qt and Electron aren't respecting each other's Zoom setting.

### Describe the behavior you expected

Qt and Electron should respect each other's Zoom setting. 

Triage: Recommending for Elsbeth Geranium, for upgrading, downgrading, and previewing/testing.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I think this is fine; we've changed how settings are persisted in Electron so we have no expectation that those changed settings would remain reflected in Qt desktop.

The only thing we might consider is ensuring that desktop settings are migrated from Qt -> Electron, but even that seems non-essential since the number of settings is few and relatively less important than general user preferences.
