### ISSUE TITLE
RStudio corrupts running git rebase

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [rstudio/rstudio#11584]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 550
    OS Version      : Windows 10 x64 (build 19044)
    R Version       :  3.6.3 (x86_64-w64-mingw32/x64 (64-bit))

### Steps to reproduce the problem

- start a rebase in git with, say, at least 10 commits

### Describe the problem in detail

```
$ git rebase -i main
fatal: Unable to create 'C:/[Path to repo]/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

- Have to start over with `git rebase --abort`
- Workaround: close RStudio project
- Other git clients do not mess with git rebase, namely [GitExtensions](https://github.com/gitextensions/gitextensions)

#### Git version used
```
$ git -v
git version 2.37.0.windows.1
```

### Describe the behavior you expected

No interference with command line git operations like e.g. `git rebase`.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
You didn't really provide a reproducible example, but more likely the answer here is that RStudio is running some git operation in the background (e.g. `git status`) and the repository is locked while RStudio tries to make that call.

There is no corruption here, just (probably) multiple git processes trying to interact with the repository at the same time, which is being prevented via the index.lock lockfile.

**Comment by HenningLorenzen-ext-bayer** [comment]
> There is no corruption here, just (probably) multiple git processes trying to interact with the repository at the same time, which is being prevented via the index.lock lockfile.

1. IIRC, I could *not* get around this with `git rebase --continue`
2. With recent releases (RStudio and git) I cannot remember having trouble that would *not* go away with `--continue`

**Comment by kevinushey** [comment]
Thanks; I'm glad the issue is resolved!
