### ISSUE TITLE
Depth change, and/or styling, of document outline

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11592]
Hi,
as previously posted [here](https://community.rstudio.com/t/how-to-change-style-and-depth-of-document-outline/141814)
and after haven't found the feature.

I would like to Request the next feature for Document Outline
- be able to setup "depth", similarly to the toc_depth.
      - For example: I noted that it comprises up to 6 (######). I would like to show up only a maximum of 3 levels.
- to have some minimum styling.
      - For example "Bold" for main headers

Hopefully already exists? But sorry, I couldn't find it.

**Comment by ronblum** [comment]
@DiegoJArg Thank you for the request—we'll review it as we continue development of RStudio.
