### ISSUE TITLE
Feature to knit a single section instead of whole document

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11593]
Hi,
as previously posted [here](https://community.rstudio.com/t/is-there-a-a-way-to-knit-only-the-current-section-that-i-am-writing-ignoring-the-rest-of-the-document/141681/4) 
And haven't found if the feature already exists.

It would be helpful to set this Feature Request for Rstudio Rmarkdown files.
- Knitt only the currently under-work section as pointed by the cursor.
      - Instead of knitting the entire document.
      - Sometimes I just want to quickly check if my markdown looks pretty enough.

Thanks in advance

**Comment by ronblum** [comment]
@DiegoJArg Thank you for the suggestion! For what you're interested in, does running the individual chunks and previewing the document address what you're looking for?

**Comment by DiegoJArg** [comment]
@ronblum Not really. Running individual chunks are about chunks of code, a Section of rmarkdown may contain multiple chunks and multiple subsections. This is more about the markdown's output than the chunk execution.

Example: Working with a rmarkdown in conclusions of a thesis. I may not want to rebuild calculations over and over again to check the look&feel of that section's output.

**Comment by ronblum** [comment]
@DiegoJArg Got it—thank you for the describing the distinction!
