### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [rstudio/rstudio#11594]
More then 1.000 open issues seems to me that the project is dead. One positive point about that is that the oldest issues is just 5 years old. That is not much when there are so many open.

Isn't there a company behind RStudio?

What is the roudmap and the ressources of that project?
Why there are so many open Issues?

**Comment by ronblum** [comment]
@Codeberg-AsGithubAlternative-buhtz that's an interesting comment. If you take a look at the enhancements that are being implemented and the bugs being fixed, along with releases every 3-4 months, you'd appreciate that the products and projects behind them are very much alive and well.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Why did you erased my question and all the content including your valuable answer?

I am not a troll. The question was serious.

I still would like to know why there are so much open issues. This is the question, not more. I don't mean it like "Why you are so lazy having so much issues open?" or anything like this. It is not personell. I am really interested in the reasons because it is unusual.

As you told in your (deleted) answer there are releases every 3-4 months and the development really goes on what I can see on the commits etc. I assume a company is well organized and has resources. I am interested in your project internas because I want to learn and of course think about contributing. But in my experience so much open issues indicating some problems. Maybe this is not the case in your special situation. That is why I am asking.

btw: Deleting content and my own question feels impolite for me. If you don't want to discuss this topic or give the information's than say it that way or delete the issue. But don't cense it. The current issue title are **not my words** but they look like so.

**Comment by jmcphers** [comment]
To put it another way, it is useful to think of the open issue count as a function of the rate at which issues are opened, minus the rate at which issues are closed, multiplied by the age of the project. So a project with a lot of open issues could be a result of an anomalous value of any of those variables. 

In our case (and VS Code)'s, the dominating factor is the incoming rate -- as a large, successful open source project that interacts with hundreds of other pieces of software and runs in thousands of environments, we receive many bug reports every day, so despite aggressively triaging and closing stale issues (see https://github.com/rstudio/rstudio/wiki/Issue-Grooming), we wind up with a lot of active issues. We try to keep it reasonable, but unless we dismiss most reports out of hand, the number will always be high!

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thank you for your valuable reply. And sorry for my awkwardly worded question.

**Comment by ronblum** [comment]
@Codeberg-AsGithubAlternative-buhtz I apologize. In addition to what @jmcphers said, I also thought this was posted by a bot, based on the GitHub page regarding Codeberg vs. GitHub. I realize now that it's a call to action by a real person. I'm sorry about that—I'll restore the original message.
