### ISSUE TITLE
Git refresh button can disappear with long branch names

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11590]
If I remember right, it used to be the case that the Git menu bar would try extremely hard to always show the Refresh button. Now, when there is a long branch name, it can disappear off the screen.

I was expecting that on resize it would reshape itself in a way that kept the refresh button on the right visible, possibly by shrinking the branch name (I think that is what previous versions did?).

https://user-images.githubusercontent.com/19150088/178060066-5c926fb6-2054-4e77-92b0-365cc37ba86e.mov

RStudio 2022.10.0-daily+55 "Elsbeth Geranium" Daily (f895778c3e83e20672af1434f040a31b8f2cf906, 2022-07-07) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.10.0-daily+55 Chrome/102.0.5005.115 Electron/19.0.6 Safari/537.36

**Comment by gtritchie** [comment]
Unlikely to be related to Electron. Everything in the main window is just a web page, and we show the same web page in Electron that we did in Qt (and for the most part, in Server/Workbench). That said, it's always a possibility!

Confirmed; I can repro this in the Qt release (Spotted-Wakerobin build 548).

**Comment by gtritchie** [comment]
Also repros in Prairie-Trillium desktop, and latest open-source Server.

**Comment by DavisVaughan** [comment]
I must just be super sensitive to weirdness right now. Sorry for the confusion!

**Comment by ronblum** [comment]
I can reproduce this back to 1.4.1743. Proposal: Move the refresh button just a bit to the left, so that it's just to the right of the "More" button?

**Comment by kevinushey** [comment]
I think we should just truncate the branch name (and show the full name on hover)
