### ISSUE TITLE
Editor Zooming via Mouse-Wheel

### ISSUE THREAD

**Issue by buhtz** [rstudio/rstudio#11595]
Zooming in the editor window is possible via `Ctrl`+`-` or `Ctrl`+`+`. But the editor doesn't react on the mouse wheel (scroll wheel) in combination with `Ctrl`. Some other applications does so. I would say this is a "usual" standard behaviour.

Would be great if RS could offer this, too.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Windows 10 64bit.
RStudio 2021.09.2 Build 282

Not able to update RStudio to upstream or latest release because I am not the admin.

**Comment by buhtz** [comment]
OK, I see now how you treat your users/customers.
Bots are so damn impolite!

You don't care about my Issues? You won't give arguments why you close this? Of course you are free to close it. But please "you" (as a human) close it and not a machine.

I won't invest more time in RStudio anymore with Issues or more contributing because of your bots.
