### ISSUE TITLE
No icon for .Rproj in windows 11 explorer, Electron

### ISSUE THREAD

**Issue by conig** [rstudio/rstudio#11598]
### System details

    RStudio Edition : desktop
    RStudio Version : 2022.10.0.59
    OS Version      :  Windows 11, 22000.778
    R Version       :  4.2.1

### Steps to reproduce the problem
1. Create  a  project, view project file in windows explorer

### Describe the problem in detail
There's no icon
![image](https://user-images.githubusercontent.com/12742211/178385989-3c570f3a-9888-41d3-9d18-94258fdf8b8a.png)

### Describe the behavior you expected
An icon

![image](https://user-images.githubusercontent.com/12742211/178386031-9e7d0343-d720-4978-a882-31dc02fb0ab1.png)

**Comment by ronblum** [comment]
@conig Thank you for raising this! This is also true for other types of files that should be associated with RStudio, such as .r, .rmd, .qmd, etc. I believe this is a known issue, but I can't find one for it, so I'll leave this one for review.

**Comment by gtritchie** [comment]
I'm not aware of an existing issue. The icons are _supposed_ to have been set by the installer:

https://github.com/rstudio/rstudio/blob/dda4c2f2789abe40572877205acdad90cf267ae9/package/win32/CMakeLists.txt#L46-L96

It may be because we don't have this bit of cmake logic (seen here in the Qt Desktop CMakeLists.txt) in the Electron cmake file: https://github.com/rstudio/rstudio/blob/dda4c2f2789abe40572877205acdad90cf267ae9/src/cpp/desktop/CMakeLists.txt#L317-L318

**Comment by ronblum** [comment]
@gtritchie Ah! Found it: issue #10010. That was in Qt, though, and I couldn't reproduce it.

**Comment by cderv** [comment]
Some hints that could help understand: 

I encounter this issue when switching to electron daily from previous non electron daily as I was using installer-less version for RStudio IDE. 

All my project where associated with a `rstudio.exe` previously in `bin/` folder (`bin/rstudio.exe`) and with Electron, the `.exe` is now at root of RStudio install folder. 

It was a very specific configuration but could be related so sharing here. I fixed on my side by associated the `.Rproj` to the correct binary. 

@conig if this is related, you could check association of the `.Rproj` extension on your Windows. But if it is not correctly associated, double clicking on the Rproj file should not open the project and error I guess. 

But, hey, maybe it is not related at all. 🤷‍♂️ In that case, sorry for the noise.

**Comment by gtritchie** [comment]
Yes, if you are using the installerless approach, then the necessary registry keys won't be created/updated. As you have noticed, the layout of Electron is different on disk than Qt, so old (Qt) registry keys would be incorrect.

**Comment by conig** [comment]
> @conig Thank you for raising this! This is also true for other types of files that should be associated with RStudio, such as .r, .rmd, .qmd, etc. I believe this is a known issue, but I can't find one for it, so I'll leave this one for review.

Thanks this is correct. All these file types have no icon too.

![image](https://user-images.githubusercontent.com/12742211/178617108-fa051981-c85b-445f-a7df-3087ae11e914.png)


Interestingly the .Rproj will open rstudio as normal, however the others are not associated with RStudio.



![image](https://user-images.githubusercontent.com/12742211/178616347-736baecd-e138-4e71-9e5d-6d7a0144b8b7.png)

> I encounter this issue when switching to electron daily from previous non electron daily as I was using installer-less version for RStudio IDE.

I've only used the .exe installers, I'm not fancy enough for that yet!

I've tested this with the Electron preview: https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2022.07.0-548.exe

As well as the latest daily: https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2022.10.0-daily-64.exe

Same behaviour on both

**Comment by ntluong95** [comment]
I encountered the same problem

**Comment by conig** [comment]
Resolved as per issue #12246

**Comment by zhaoliang0302** [comment]
Same in Windows 11 x64 22H2. I tried several version of Rstudio, all the .R and .Rproj files will not automatically associated with Rstudio after installtion. I should open them and chose Rstudio to open them manually. Icons of all these files look same.
