### ISSUE TITLE
Can't change Spellchecker language, It stays in English

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11599]
RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
Change the spellcheck language to Spanish
In Global Options -> Spellcheck -> Select "Install more languages" -> Select "Spanish" -> Click Apply and OK
The Dialog closes. 
Note that every Spanish word is still marked. 
Go back to Global Options
Note that "English(Austrlia)" is selected

### Describe the problem in detail
Not very hard to understand, but it does not produce the desired result.
I am trying to set Rstudio spellchecker to Spanish.
It seems to download OK and list the available language in the combobox.
After selecting Spanish and confirming changes, nothing really changes.
There is no error output in console.

### Describe the behavior you expected
Spellchecker working in Spanish

### In addition, probably Feature Request
- Shouldn't the language be specified and detected on a per-file basis? Like in the YAML section?

**Comment by ronblum** [comment]
@DiegoJArg Thank you for raising this! I am going to try to reproduce the issue and to see if it came up earlier. In the meantime, can you file a new issue for the feature request about the per-file language choice? Thanks!
