### ISSUE TITLE
Autocomplete of function keyword returns 'function' surrounded by single quotes

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#11591]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.10.0-daily+53
    OS Version      : Windows 11, Ubuntu 22.04
    R Version       : 4.2.1

### Steps to reproduce the problem

1. Open new R file
2. Type func
3. Accept the autocomplete for `function`

### Describe the problem in detail

Autocomplete of `function` returns 
```
 'function'()
```
Surrounded by single quotes.
This happens in both script editor and the console. Does not repro on Spotted Wakerobin QT nor Electron

### Describe the behavior you expected

Autocomplete to return `function` instead of `'function'`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
This is probably related to https://github.com/rstudio/rstudio/pull/11523

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-173
Windows 11, Ubuntu 22.04

Works as expected for all tested keywords
