### ISSUE TITLE
RevealJS presentations don't display in the Presentations Pane

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11609]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.0+548 (Electron) and 2022.10.0-daily+55
    OS Version      : MacOS 12.5
    R Version       : 4.2.0

### Steps to reproduce the problem

In an Electron version of RStudio Desktop:
1. <kbd>File -> New File -> Quarto Presentation</kbd>
2. Make sure that `RevealJS` is checked.
3. <kbd>Create</kbd>
    - A new Quarto file is created with `format: revealjs` in the YAML
4. <kbd>Gear -> Preview in Viewer Pane</kbd>
5. <kbd>Render</kbd>
    - Rendering occurs.
    - Focus switches to the Presentation Pane.
    - The Presentation Pane is empty, though.

### Describe the problem in detail

RevealJS presentations aren't displayed in the Presentations Pane.

https://user-images.githubusercontent.com/31009952/178599390-00b61e26-8e81-430a-87b1-e8e98c60b396.mov

### Describe the behavior you expected

RevealJS presentations should be previewable in the Presentation Pane of an Electron Desktop (so Elsbeth Geranium).

This works correctly:
- In RStudio Desktop Qt.
- With HTML and Beamer formats, though both of these display the output in the Viewer Pane.
- When previewing in a browser window.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@jjallaire not sure if this is something you'd want to look at, or Tim/Jackie, considering this is only in electron

**Comment by cderv** [comment]
Just to share that I get the same behavior on Windows with latest daily and last quarto 

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.11.0.135
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

````
> quarto --version
quarto 1.1.113
````

**Comment by jjallaire** [comment]
Yes, let's have Tim/Jackie look at this -- it's definitely an Electron hosting issue that likely affects other scenarios.

**Comment by kevinushey** [comment]
For reference, I'm seeing the following JS error in the console when the presentation is opened:

<img width="530" alt="Screen Shot 2022-08-24 at 9 54 05 AM" src="https://user-images.githubusercontent.com/1976582/186477532-2e761ea2-ac92-4621-9983-bdd516a4ba38.png">

Presumedly we're missing a required registration for the `setPresentationUrl()` callback?

**Comment by jgutman** [comment]
Maybe... I think @timtmok was just working on something related to this? I haven't started looking at this issue yet anyway

**Comment by timtmok** [comment]
> Maybe... I think @timtmok was just working on something related to this? I haven't started looking at this issue yet anyway

@jgutman Yeah, pretty sure it is the same thing. I noticed it while writing up QA notes for the `acceptNavigationRequest` implementation. `DesktopHooks` calls into Electron but the function doesn't exist so it stops executing the next command, which is setting the URL in the pane.

**Comment by astayleraz** [comment]
This looks like it might be causing a good amount of our files tests to fail around the preview, and rendering of the files.
![Screen Shot 2022-08-24 at 12 54 31 PM](https://user-images.githubusercontent.com/1482677/186511084-744c1f53-4e6e-4348-9bcc-cf1e975f136d.png)

**Comment by jgutman** [comment]
@astayleraz that may be related to #11799 (and #11831) from @timtmok

**Comment by ronblum** [comment]
Verified that this is working correctly in RStudio Desktop 2022.11.0-daily+160 on MacOS 13.

@astayleraz Before closing this, can you confirm whether or not the automated tests are no still failing?

**Comment by astayleraz** [comment]
I can confirm I am no longer seeing automation failures.
