### ISSUE TITLE
Development container failed to start in VS Code Remote-Containers

### ISSUE THREAD

**Issue by kyusque** [rstudio/rstudio#11602]
### System details

    RStudio Edition : both?
    RStudio Version :  main branch (commit 88453ce49a3ab4a5632dd6b9ae79d92be14941b1)
    OS Version      :  Windows 10
    R Version       :  not related to R version

### Steps to reproduce the problem

At the third step in Open Project in VS Code section in https://github.com/rstudio/rstudio/blob/main/VSCODE.md

### Describe the problem in detail

1. Execute Clone repository in Named Container Volume in ... from command pallete.

![image](https://user-images.githubusercontent.com/24940851/178502337-38c0e109-f5b2-4378-918f-abee91e7a5b6.png)

2. Click Clone a repository from GitHub in a Container Volume.
![image](https://user-images.githubusercontent.com/24940851/178502360-4b59772d-436c-4f94-ab56-320081b086a6.png)

3. Input rstudio/rstudio, main and volume name.
![image](https://user-images.githubusercontent.com/24940851/178502370-d1f6c10e-fd36-41fd-bd01-401a0bf3364f.png)

4. Error occurs at COPY
![image](https://user-images.githubusercontent.com/24940851/178502299-0638b644-d81d-456d-a7ac-c0c4394c34e6.png)

### Describe the behavior you expected

I expect to open the project in a development container in VS Code.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kyusque Thank you for the raising the issue! First off: Are you by chance using the professional product (RStudio Workbench), or you using the open source version of RStudio Server?

**Comment by kyusque** [comment]
Thank you for the response.
I'm using the open source version.

**Comment by gtritchie** [comment]
I don't think anybody (internally at RStudio) is actively using or maintaining the VSCode dev container. Unless someone really wants to spend the time getting it healthy, we should consider deleting it. This is the goo under rstudio/.devcontainer.

@jonyoder you were the most interested in the past; are you still using this?

**Comment by gtritchie** [comment]
Ah, the problem (not sure it's the ONLY problem, but it's definitely a problem) is that when I removed our Qt installation from our dependency scripts (now that we're Electron-only), I didn't update the devcontainer to match; so it's still trying to install Qt using scripts that no longer exist.

**Comment by gtritchie** [comment]
I made _some_ fixes to the devcontainer, via https://github.com/rstudio/rstudio/commit/f08afa41153d8d550cba39e21919f7a48d4f5148, but don't have time to test it out right now.

**Comment by kyusque** [comment]
@gtritchie  Thank you for the commit.

I tried to open the container and entered it.
However, the subsequent steps (Choose the GCC kit, and click the Build button) did not work.

![image](https://user-images.githubusercontent.com/24940851/178734331-5fb01f6c-3f28-4f0e-9d2a-ce3a19569a05.png)
![image](https://user-images.githubusercontent.com/24940851/178736451-28087895-f3d4-44c5-ada1-ee08a96b2b34.png)

It's the first time for me to try this feature, so I don't know how it works properly.
If nobody use this feature as you mensioned above, I won't, too. 
I am sorry that you went through the trouble of doing this.

**Comment by gtritchie** [comment]
FYI, we haven't had the time to maintain the devcontainer for open-source, so I'm going to remove it altogether rather than giving people false hope. See also https://github.com/rstudio/rstudio/issues/13889
