### ISSUE TITLE
In-body chunk options not working properly for non R engines when executed interactively

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#11606]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.07.0 Build 548
    OS Version      : Ubuntu Server 20.04 LTS
    R Version       : 4.2.1

### Steps to reproduce the problem
Use in-body chunk options for non-R engines (I think this specifically fails with engines that do not use `#` as a comment
 syntax like SQL and cat) and execute the code interactively.

````
---
title: "Example"
output: html_document
date: "2022-07-12"
---

```{r}
library(DBI)
db = dbConnect(RSQLite::SQLite(), dbname = "sql.sqlite")
```

```{sql}
#| connection = db

SELECT 'test'
```

```{cat}
#| engine.opts = list(file = "tbl.sql", lang = "sql")

SELECT 'test'
```
````
### Describe the problem in detail
When executed interactively, the in-body chunk options are applied, but they are also included in the chunk body that gets executed and since for engines like SQL `#` is not a valid comment syntax, this causes a syntax error.
I think this is related to the RStudio IDE since the same code when knitted (run through `knitr`) works as expected and chunk options do not get included in the chunk body.

### Describe the behavior you expected
I expect in-body chunk options to get removed or not included in the chunk body when the code gets executed interactively so it doesn't cause syntax errors.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by andrie** [comment]
It seems to me that the reproducible example you provided mixes `quarto` and `rmarkdown` conventions.  The output format you specify is a R markdown format (`html_document`), so rendering this will use the R markdown engine.  R markdown doesn't know about the quarto comment conventions.

So it seems to me you should modify the output format to be just `html`.

Can you please try this?

**Comment by andresrcs** [comment]
I think you misunderstand the issue, there is no problem when the document is rendered, in-body chunk options are also a  supported feature of `knitr` not just `quarto` so an `rmd` document renders just fine. The problem happens when the code is executed interactively in the IDE.

Anyways, just in case, I changed the output to `html` as requested and as expected, the problem is still there when the code is executed interactively

**Comment by srowelluf** [comment]
> I think you misunderstand the issue, there is no problem when the document is rendered, in-body chunk options are also a supported feature of `knitr` not just `quarto` so an `rmd` document renders just fine. The problem happens when the code is executed interactively in the IDE.
> 
> Anyways, just in case, I changed the output to `html` as requested and as expected, the problem is still there when the code is executed interactively

FYI - same exact issue here; I have just been using the old style options in SQL chunks and new options for r chunks, and I can then run interactively.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+245
Windows 11 - Desktop
Ubuntu 22.04 - Server

Tested OP reprex as well as a few other chunks. All executed as expected, removing the `#|` comment lines before execution.

**Comment by andresrcs** [comment]
This issue has come back on the latest daily builds (tested on 2023.12.0-daily+170 server for Ubuntu 22 Arm64)

**Comment by jgutman** [comment]
Hi Andres, 

For SQL chunks, the preferred in-body chunk option style is 
```{sql}
--| connection: db

SELECT 'test'
```

Which currently works correctly. 
However, as knitr supports both 
`--| connection: db`
and `#| connection: db`
we should support both as well.

It appears that, in addition, knitr also supports both the colon style chunk options: `--| connection: db` as well as the `=` options ``--| connection = db`. This works for some language engines, but not others.

For example, 
~~~
```{r}
#| fig.width = 5
```
~~~


and 
~~~
```{r}
#| fig.width: 5
```
~~~
 will both work as expected
