### ISSUE TITLE
Be able to toggle between R<>Python consoles

### ISSUE THREAD

**Issue by chendaniely** [rstudio/rstudio#11613]
Feature request for adding a dropdown in the “console” pane similar to the “environment” pane for switching back and forth between R and Python.

## Why

I work a lot in both R and Python simultaneously, and there are many times I need to just look at something quick in the other language.

## Current workaround

There might be a better way I’m not aware below is what I end up regularly doing.

if I’m in R and want to Run python code I have to do either 1 of:

- find python code in my source document. run it. it will switch to the python console (what I want) and also run the code (don't always need the results)
- run `reticulate::repl_python()` to swap to the python console from R

If I want to go from python to R in the console, I have to do 1 of either:

- find R code in my source document. run it. I get the R console with the code output
- type `exit` in the python console to get back into R

**Comment by gadenbuie** [comment]
Just to add a little visuals, we were thinking this might look like the existing language selector on the environment pane but at the top of the console pane.

![The Console pane above the Environment pane with an arrow drawn from the R/Python drop-down selector to the "R 3.6.3" indicator at the top of the console pane.](https://user-images.githubusercontent.com/5420529/178804683-7ab65f93-c855-4d8b-a2a4-557e0f844c66.png)

**Comment by kevinushey** [comment]
I like that idea; we could make the R icon in the Console pane clickable (with a little drop-down arrow on its right) and let the user select between R and Python there.

(One thing to consider; would we _always_ show this UI, or only if Python were already installed / configured on the user's machine?)

**Comment by chendaniely** [comment]
I'm okay with always showing it (since that's what the `environment` panel does).
Maybe by default if you click the python it would do whatever default thing `reticulate` does, otherwise, let the user be able to control which python environment gets loaded up by `reticulate`.

What you want to avoid is the user being confused about why their python code isn't working, and it's because RStudio is auto-loading up a (wrong) reticulated python environment on startup/restart.

as an additional feature, maybe also create an option in the IDE to allow toggling the environment language also toggles the console language?

**Comment by ntluong95** [comment]
one vote for this idea

**Comment by DataStrategist** [comment]
> What you want to avoid is the user being confused about why their python code isn't working, and it's because RStudio is auto-loading up a (wrong) reticulated python environment on startup/restart.

This. To your point @gadenbuie , that dropdown is a great idea. But if it's Python, it should show the specific Python kernel, whether it be just Python, in which case the version should also be shown, or the venv/conda env. 

You could switch these via the Project Options menu, and maybe even provide an option when setting up a new project:
![image](https://user-images.githubusercontent.com/8094091/180162752-54b4e7de-6045-43a6-9a5d-1d79f7ab8d6f.png)

**Comment by Courvoisier13** [comment]
this would be great. I found this as I was going to add an enhancement. 
It would be great to have both consoles, like we have multiple terminals. I suspect it would make switching from R to Python (and vice versa), much quicker. Currently if the python console has large variables (a few GB and millions of rows (30-40)) the switch is very very slow.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+229 on Windows 11.

**Comment by t-kalinowski** [comment]
Awesome! I just gave it a try and it looks great. 
Two nits:

nit 1: Selecting "Python" in the console pane also switches to "Python" in the Environment Pane. However, the inverse is not true. Selecting "Python" in the environment pane does not update the console. Should the two be synchronized? 

nit 2: There is no downward pointing triangle next "R" above the console, indicating that this is a clickable target (like there is in the Environmnet Pane). Not sure anyone will discover this feature without that visual hint indicating there is a dropdown. 
![image](https://github.com/rstudio/rstudio/assets/8462255/000b2d88-23bf-40ae-9ea5-62506a0f7b13)
![image](https://github.com/rstudio/rstudio/assets/8462255/01f8c53c-761a-4c66-b631-da9001f2a93e)

**Comment by ronblum** [comment]
@t-kalinowski I'll reopen this, to get @kevinushey's thoughts.

But my thoughts:
1. I don't think that the Environment Pane should drive the Console, because we might want to see and access Python values while in R and vice versa.
2. Makes sense.

**Comment by kevinushey** [comment]
> nit 1: Selecting "Python" in the console pane also switches to "Python" in the Environment Pane. However, the inverse is not true. Selecting "Python" in the environment pane does not update the console. Should the two be synchronized?

Indeed, as @ronblum said, we thought users might be interested in exploring the R / Python environments independently of whatever language is active in the Console, so we allow the Environment pane to be "navigated" to the other language's active objects.

> nit 2: There is no downward pointing triangle next "R" above the console, indicating that this is a clickable target (like there is in the Environmnet Pane). Not sure anyone will discover this feature without that visual hint indicating there is a dropdown.

This seems reasonable; let me see what I can do.

**Comment by ronblum** [comment]
Verified the downward arrow in RStudio Desktop 2024.07.0-daily+303 on Windows 11.

**Comment by t-kalinowski** [comment]
Just tried it, looks and works great! Thank you!
