### ISSUE TITLE
Click on link in viewer pane in IDE electron crash IDE

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#11611]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.10.0.64
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

### Steps to reproduce the problem

1. Open RStudio daily Electron
2. Create a new quarto document (probably happening with other type too) with the aim to create a HTML document in the viewer with a link
3. Add this simple content 
````markdown
---
format: html
---

<https://rstudio.com>
````

4. Render the document to HTML
5. It will open in the viewer
6. Click the link in the viewer

### Describe the problem in detail

When clicking the link, the IDE window reload completely, and then crash 

See below
![ide-link-crash](https://user-images.githubusercontent.com/6791940/178683274-815d45da-d3e1-41bd-ae3c-468a363a8fbf.gif)

Crash message is this one

![image](https://user-images.githubusercontent.com/6791940/178682446-23a3f893-550d-4da4-a908-6e6faf9c6306.png)

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9100274/diagnostics-report.txt)

### Describe the behavior you expected

I would expect the link to open in external window like preview Qt version but not crash the whole session

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
This is the error produced in the dev console:
```
Uncaught TypeError: ansi_html_community__WEBPACK_IMPORTED_MODULE_0___default(...).setColors is not a function
    at eval (overlay.js?f53e:29:1)
    at ./node_modules/webpack-dev-server/client/overlay.js (index.js:277:1)
    at __webpack_require__ (index.js:489:33)
    at fn (index.js:677:21)
    at eval (index.js?protocol=ws…o&reconnect=10:8:69)
    at ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=info&reconnect=10 (index.js:256:1)
    at __webpack_require__ (index.js:489:33)
    at index.js:1533:11
    at index.js:1537:12
eval	@	overlay.js?f53e:29
./node_modules/webpack-dev-server/client/overlay.js	@	index.js:277
__webpack_require__	@	index.js:489
fn	@	index.js:677
eval	@	index.js?protocol=ws…info&reconnect=10:8
./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=info&reconnect=10	@	index.js:256
__webpack_require__	@	index.js:489
(anonymous)	@	index.js:1533
(anonymous)	@	index.js:1537```

**Comment by timtmok** [comment]
This looks to be an error with trying to navigate to an external site within the pane. I think this might be a restriction with iframes embedding a website. Oddly, the Tutorial pane does not experience this when clicking the links at the bottom of the tutorial home page.

In Prairie Trillium, it opens in your browser. I'm pretty sure this comes from the navigation request and Qt code would open the link in a browser since it's an external url. #11252 is supposed to address the navigation request but Electron lacks the [`will-frame-navigate` event](https://github.com/electron/electron/issues/7097). We would look at the navigation request for the iframe and open the url in a browser. There is some limited workaround for review in #11252 but I don't think it will handle it here. I'm investigating a fix in GWT to add an intercept before url navigation starts. The IDE needs to check the url and decide whether to open it in the browser or not.

**Comment by timtmok** [comment]
No luck so far with finding a workaround in GWT using event previews. It doesn't seem to produce events for the iframe. I have another idea with hooking the click preview events that I'll give a shot.

**Comment by timtmok** [comment]
@mikebessuille I have not found a workaround for this iframe bug. The upstream PR in Electron that adds `will-frame-navigate` looks 95% complete but has had no progress since June. It looks like it needs a fix for a unit test but otherwise the implementation looks okay.

This is really not a good bug to have but it can't be fixed until Electron emits an event to hook into this.

**Comment by mikebessuille** [comment]
This seems like a major breakage; I don't think we can ship with this problem.
1) Is there a way we can help or influence the acceptance of that change in Electron?
2) Is there a completely different way we can support how links get opened, or how previews are displayed, or...?

**Comment by kevinushey** [comment]
It looks like there's been some movement on the Electron side re: the "will-frame-navigate" PR, so hopefully we can wait a couple weeks and hope that lands.

If that doesn't land, we still have one more way out. Right now, RStudio Server servers Viewer content through a proxy URL:

https://github.com/rstudio/rstudio/blob/bf972e0569252db04a37d8c7806239360d35b8d1/src/cpp/server/ServerMain.cpp#L278-L285

This means that the iframe is on the same origin as the RStudio page itself, and so we're free to interact with the iframe window / document via JavaScript, or install a filter on the incoming HTML.

It might also be worth asking whether Quarto could help us out here -- could we configure Quarto to produce pages which always navigate external content in a separate window?

**Comment by kevinushey** [comment]
One other factoid -- in Visual Studio Code, rendered Quarto documents that contain links can be clicked, but that doesn't try to force navigation on the main window (although navigation doesn't happen in an external window; navigation merely just fails). I wonder what makes RStudio different here?

**Comment by ronblum** [comment]
Tested using[ the examples above](https://github.com/rstudio/rstudio/issues/11611#issuecomment-1183264850).

Works in
- RStudio Desktop 2022.11.0-daily+187 (Electron) on MacOS 13
- RStudio Desktop 2022.11.0-daily+174.pro2 (Qt) on MacOS 13

Fails in the same way as described in the code in
- RStudio Server 2022.11.0-daily+187 on Ubuntu 20.04 via Chrome on MacOS 13

**Comment by timtmok** [comment]
I'm going to close this and open a new issue just for server. If it didn't work in server then it would be an existing issue.
