### ISSUE TITLE
IDE hangs when attempting to preview image with empty class

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11619]
### System details

    RStudio Edition : 2022.07.0+548
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.4
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

Create, or open, a Quarto document with the contents:

`````
![](image.png){.}
`````

where `image.png` is the path to an already-existing image.

### Describe the problem in detail

The entire IDE freezes and becomes unresponsive.

### Describe the behavior you expected

The image should be previewed.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0   
```

</details>

**Comment by kevinushey** [comment]
This issue is a bit ugly because it can lead a user to get stuck in a state where the IDE freezes on startup even after a restart.

1. User starts RStudio,
2. RStudio tries to automatically open previously-open files or scripts,
3. The IDE hangs when trying to preview the image in the opened Quarto document.

**Comment by jthomasmock** [comment]
> This issue is a bit ugly because it can lead a user to get stuck in a state where the IDE freezes on startup even after a restart.
> 
> 1. User starts RStudio,
> 2. RStudio tries to automatically open previously-open files or scripts,
> 3. The IDE hangs when trying to preview the image in the opened Quarto document.

I was able to get out of this state by deleting the temp files in my `.Rproj.user` but I'm sure that has side-effects 😢

**Comment by kevinushey** [comment]
I think this is resolved in the latest [daily builds](https://dailies.rstudio.com) -- @jthomasmock, can you give the latest builds a try and let me know if the issue seems resolved for you as well?

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-82
Windows 11, MacOS 12.4, Ubuntu 22.04
Tested on with several different files in different locations and varied document contents.
