### ISSUE TITLE
Running example code within Rd document

### ISSUE THREAD

**Issue by LiNk-NY** [rstudio/rstudio#11616]
Hi, 
I'm cross posting issue No. [142154](https://community.rstudio.com/t/feature-request-run-example-code-within-rd-document/142154). I wasn't aware that this is the place to file feature requests.  

I work on packages, written before `roxygen2`, whose documentation is written in `Rd` format. These packages often have extensive documentation and examples.

In RStudio, there is no easy way to run code within an opened `.Rd` document i.e., `\examples{}` section directly from the editor window (though you can run it via the Help tab). I am often modifying / debugging examples in these Rd files. 

Note. You could say use the `Rd2roxygen` package but that only gets me 80% of the way there at best, especially with these packages that use the S4 system. `Rd2roxygen` does not work well with S4 at the moment. 

It is possible to add a hook that would recognize code in `\examples{}` and make the code run-able / send-able to the console via `Ctrl` + `Enter`? 

Thank you. 

Best regards,
Marcel

Reproducible RD: 

```r
\name{testRd}

\title{Test Rd document}

\description{
    Testing
}

\examples{
    ## runnable code goes here
    1 + 1 ## Ctrl + Enter would send this to the console
}
```

**Comment by ronblum** [comment]
@LiNk-NY Thank you for the suggestion! I'll mark this for review as part of our ongoing development of RStudio.

And I'm glad you found your way here, with a little help from another user. 🙂

**Comment by LiNk-NY** [comment]
Any updates on this?

**Comment by LiNk-NY** [comment]
Was this reviewed? 
Thank you.
