### ISSUE TITLE
Install R-studio in terminal r-base 4.2.1.2204.0 PROBLEM

### ISSUE THREAD

**Issue by Fdm8610** [rstudio/rstudio#11610]
I can't install Rstudio with Ubuntu 22.04 after having installed r-base latest version

sudo apt install --no-install-recommends r-base
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r-base is already the newest version (4.2.1-1.2204.0).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 rstudio : Depends: libclang-dev but it is not going to be installed
           Depends: libxkbcommon-x11-0 but it is not going to be installed
           Depends: libpq5 but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

How to solve this problem?

THANK YOU!

**Comment by Fdm8610** [comment]
Thank you. I reinstalled everything from the vendor binaries. it worked out

**Comment by ronblum** [comment]
@Fdm8610 Excellent—thank you for the update!
