### ISSUE TITLE
Including S4 methods in the "Document Outline" pane

### ISSUE THREAD

**Issue by LiNk-NY** [rstudio/rstudio#11617]
Hi, 

When working within an R file, I don't see the defined methods in the Document Outline pane on the right. 
This makes it very difficult to navigate the R file with the Document Outline pane. 

It would be great if `setMethod` calls could be included in that Document Outline pane. 

Note that the layout for consulting the documentation page of a method is as follows:
`?'<methodName>,<className>-method'`
And it would be good if the Document Outline titles followed this convention. 
Some of the parsing is done already with the <kbd> Ctrl </kbd> + <kbd> . </kbd> command 
A.K.A. the `Go to File / Function` functionality. 

Thank you so much for all that you do for RStudio. 

Best regards,
Marcel

**Comment by ronblum** [comment]
@LiNk-NY Thank you for this suggestion, as well. Would you be willing to include a simple example of such an R file? 

Also, I appreciate the kind words, and I'll pass them on to the rest of the team!

**Comment by LiNk-NY** [comment]
Hi Ron, @ronblum 
Thank you for your response. 
Here is a small example file: 

```r
.A <- setClass("A", representation(a="integer"))

A <- function(a = integer(), ...) {
    .A(a=a, ...)
}

setMethod("show", "A", function(object) {
    cat("This is class", class(object), "with a value of", object@a, ".")
})

setGeneric("transpose", function(x) standardGeneric("transpose"))

setMethod("transpose", "A", function(x) {
    t(x@a)
})
```

Ideally the Document Outline would have all the entries for the five calls listed here. 

Best,
Marcel

**Comment by kevinushey** [comment]
For reference, this is where the scope tree (which is used by the document outline) is built.

https://github.com/rstudio/rstudio/blob/c57579e10f1094328949bb68054e2473e7cd6448/src/gwt/acesupport/acemode/r_code_model.js#L1112-L1214

My guess is we'd have to add some extra parsing code for `setGeneric` and `setMethod` calls.

**Comment by ralmond** [comment]
This issue has not been resolved.  I would also like to see support for S4 code development in RStudio.
