### ISSUE TITLE
Autocompletion + Pipe + Extra arguments in S3 methods

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11627]
Some of our S3 methods have "extra" arguments that aren't present in the S3 generic. For example:

``` r
args(dplyr::mutate)
#> function (.data, ...) 
#> NULL

args(dplyr:::mutate.data.frame)
#> function (.data, ..., .keep = c("all", "used", "unused", "none"), 
#>     .before = NULL, .after = NULL) 
#> NULL
```

If you call `mutate()` with a data frame and _don't_ use the pipe, then autocomplete picks up those extra args

<img width="405" alt="Screen Shot 2022-07-15 at 10 42 57 AM" src="https://user-images.githubusercontent.com/19150088/179246988-2b0f0e69-dd51-48c3-9464-374bc2d2e37a.png">

But if you use the pipe, then they don't show up:

<img width="433" alt="Screen Shot 2022-07-15 at 10 43 10 AM" src="https://user-images.githubusercontent.com/19150088/179247037-afeb5909-c20f-4722-a0c8-48e7848ac453.png">

Note that this is actually opposite of how variable name autocompletion works. If you pipe a data frame into a function then the column names autocomplete, but if you call `mutate(mtcars, )` then the names won't autocomplete.

Is it possible to allow `mtcars %>% mutate()` to also show the "extra" S3 arguments specific to the data frame method?

I realize this is probably a hard problem, because you could have a multi-step pipe chain where you might have a `mutate()` call at the end of the chain, and you don't know if the input is actually a data frame or not.

```r
library(dplyr)

# This is invalid code
mtcars %>% 
  pull(mpg) %>%
  mutate(cyl = cyl + 1)
```

But autocompletion "works" in this case anyways, and seems to take the names from the first input even though the resulting code is technically invalid.

<img width="363" alt="Screen Shot 2022-07-15 at 10 49 17 AM" src="https://user-images.githubusercontent.com/19150088/179248069-5b3b33f3-4043-4c07-b4a7-6181683a42ac.png">

So maybe the S3 method lookup could work the same way? i.e. try to look up a specific S3 method for the first thing in the pipe chain, no matter where you are in the pipe chain. If you find an S3 method, autocomplete all the args for that method, otherwise autocomplete the args for the generic? It would give invalid results in some cases (like the above case) but I feel like it would be a bigger win to have this VS having it incorrectly autocomplete things sometimes.

**Comment by ronblum** [comment]
@DavisVaughan I tagged this as an enhancement, but do you think that's correct or is it a bug?

**Comment by DavisVaughan** [comment]
Other IDE team members might be able to better say, but enhancement feels right to me

**Comment by kevinushey** [comment]
There's actually some code in the IDE that should be handling this sort of thing already:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionRCompletions.R#L2102-L2145

It looks like this worked way back in RStudio 0.98, but regressed in RStudio 0.99.

**Comment by jonvanausdeln** [comment]
Using 2022.12.0-daily+263 Desktop on Windows 11, Server on Ubuntu 22.04

Autocomplete of arguments when piped and not piped are presented.
