### ISSUE TITLE
Column name completion for arrow tables

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#11629]
When using the arrow package, RStudio does not propose or complete column names in a workflow like below, like it does with R tables, or even DBI objects I believe.
The column names are available as part of the Arrow Dataset object created, maybe they can be gathered from there and added to column completion? 

Identifying the right class of object might be a bit tricky, as arrow uses multiple R6 classes:
* opening a dataset from multiple files (open_dataset) returns a "Dataset" object
* opening a single file (read_csv_arrow) returns a "Table" object
* maybe others in other cases

Thanks!

Example 
```
library(arrow)
library(dplyr)

# Create dataset
tf <- tempfile()
data <- dplyr::group_by(mtcars, cyl)
write_dataset(data, tf)
ds <- open_dataset(tf)

# Columns won't be proposed when doing:
ds %>%
  filter(mtcars == ...)

# Column names are in
ds$schema$names

```

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+270 on MacOS 13.2 using the example above and the similar one in #12200.
