### ISSUE TITLE
I am unable to run RStudio 2022.10.0-daily+68 on Windows 10 system

### ISSUE THREAD

**Issue by bhattmaulik** [rstudio/rstudio#11626]
I want to run 2022.10.0-daily+68 on my Windows 10 system. But it just doesn't start. If I open Windows Task Manager, I can see two processes in the list: RStudio and RStudio R Session. There are 4 instances of RStudio in that list, and one instance of RStudio R Session. Despite this, the RStudio window doesn't open.
From the Windows Task Manager, if I kill the RStudio R Session process, then RStudio will open, and report that it cannot start now. But otherwise RStudio window doesn't open at all.
In fact, I have faced this issue in the whole 2022.10.0-daily+xx series. I can successfully install and run 2022.07.0-daily+548. But can't run any versions later than that.

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.10.0-daily+68
    OS Version      : Windows 10
    R Version       : 4.2.1

### Steps to reproduce the problem
Double click on the RStudio desktop shortcut.
### Describe the problem in detail
Till 2022.07.0-daily+548 version, I could run RStudio normally. But ever since the series changed from 2022.07.0 to 2022.10.0, I am unable to open RStudio at all.  When I first installed 2022.10.0-daily+59 version, I noticed two changes. The desktop shortcut didn't work. It was because in the earlier versions, the rstudio.exe file was inside the "rstudio/bin" folder, but in the new version, it's not in the "bin" folder. And after I manually changed the destination of the desktop shortcut, it started another dialogue box, which asked me which R version I want to associate with RStudio. I have only R 4.2.1 version installed on my system. So, I manually selected R 4.2.1 64-bit version. This was the last time I could open RStudio from the 2022.10.0 series. I have tried installing 2022.10.0-daily+64 and finally 2022.10.0-daily+68, but none of them runs on my system. When I need to run RStudio, I have to uninstall this version, and reinstall the 2022.07.0-daily+548. The 2022.07.0-daily+548 is the latest version that I can successfully run on my system.

I am attaching two screenshots with this. One is of the Windows Task Manager, after I launch the RStudio 2022.10.0-daily+68 version, and second screenshot of the error message I get in RStudio 2022.10.0-daily+68 when I manually kill the RStudio R Session from the Windows Task Manager.
### Describe the behavior you expected

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x
![Error](https://user-images.githubusercontent.com/58764997/179230531-042c2ffb-39bb-4485-9ae4-d21c60ec7eb5.png)
![TaskManager](https://user-images.githubusercontent.com/58764997/179230541-a0b1a6bc-1d08-4790-8d45-35eed16ffa97.png)
] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bhattmaulik Thanks for bringing this over from the other issue! I'll mark it for review, specifically the failure at startup. (The issue with file associations is covered in #11598.)

**Comment by jgutman** [comment]
This sounds potentially like it could be an issue with Electron locating the correct version of R to use on a Windows machine

**Comment by ronblum** [comment]
Unable to reproduce in RStudio Desktop 2022.10.0-daily+69 in Windows 10 and 11—we're able to get it to run on both.

**Comment by bhattmaulik** [comment]
Here I am still unable to run it. I uninstalled and re-installed both, R and RStudio, just in case there is some faulty configuration. But it is still not running on my system.

**Comment by bhattmaulik** [comment]
I am experimenting in my system to load the latest daily RStudio version. I have tried to run it in safe mode, and after disabling the antivirus. But still, RStudio doesn't run. When I kill the "RStudio R Session" process in the Windows Task Manager, I get a vague error log. I am pasting the error message below.
```
## R Session Startup Failure Report

### RStudio Version

RStudio 2022.11.0-daily+71 "Elsbeth Geranium " (b446fcb8, 2022-07-19) for Windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+71 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*C:/Users/Maulik/AppData/Local/RStudio/log/rsession-Maulik.log*

```
2022-07-20T12:25:50.667434Z [rsession-Maulik] ERROR system error 2 (The system cannot find the file specified) [path: /usr/bin, path: quarto.bat]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::FilePath::completeChildPath(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class rstudio::core::FilePath &) const src/cpp/shared_core/FilePath.cpp:769
2022-07-20T12:25:50.667434Z [rsession-Maulik] ERROR system error 2 (The system cannot find the file specified) [path: /usr/bin, path: quarto.cmd]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::FilePath::completeChildPath(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class rstudio::core::FilePath &) const src/cpp/shared_core/FilePath.cpp:769
2022-07-20T12:25:50.667434Z [rsession-Maulik] ERROR system error 2 (The system cannot find the file specified) [path: /usr/bin, path: quarto.cmd]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::FilePath::completeChildPath(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class rstudio::core::FilePath &) const src/cpp/shared_core/FilePath.cpp:769

```
```

**Comment by kevinushey** [comment]
> 2022-07-20T12:25:50.667434Z [rsession-Maulik] ERROR system error 2 (The system cannot find the file specified) [path: /usr/bin, path: quarto.cmd]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::FilePath::completeChildPath(const class std::basic_string<char,struct std::char_traits,class std::allocator > &,class rstudio::core::FilePath &) const src/cpp/shared_core/FilePath.cpp:769

That path component (/usr/bin) looks weird for a Windows machine.

Could you create and share a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report) with us?

You can also try resetting RStudio's state: https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by bhattmaulik** [comment]
I am attaching the diagnostic report here.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9164183/diagnostics-report.txt)

**Comment by kevinushey** [comment]
```
R User Environ: C:/Users/Maulik/Documents/.Renviron
--------------------------------------------------
PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"
PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"
PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"
```

It looks like you're trying to put Rtools 4.0 on the PATH but trying to use R 4.2. You should probably remove those entries from your `.Renviron`.

> PATH                             : C:\rtools42/x86_64-w64-mingw32.static.posix/bin;C:\rtools42/usr/bin;\usr\bin;\usr\bin;\usr\bin;C:\Program Files\R\R-4.2.1\bin\x64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Maulik\AppData\Local\Microsoft\WindowsApps;C:\rtools40\usr\bin;C:\Users\Maulik\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\bin;;C:\Program Files\JetBrains\PyCharm Edu 2022.1.1\bin;;C:\Users\Maulik\AppData\Roaming\TinyTeX\bin\win32;C:/Program Files/RStudio/resources/app/bin/quarto/bin

There are a bunch of `\usr\bin` entries there, which is probably coming from the `RTOOLS40_HOME` bits in the `.Renviron`. Those should be removed.

**Comment by bhattmaulik** [comment]
Thanks a lot. That was the culprit. Now I can open "RStudio 2022.11.0-daily+75 "Elsbeth Geranium" Daily (660a43017fe39114a94e18667d78214688b1c656, 2022-07-21) for Windows" version instantly.
Thank you for guiding me throughout this.

**Comment by bhattmaulik** [comment]
The solution worked until I closed the Windows. The very next day it is resurfacing. This time, I am getting different error when I kill the RStudio R Session in the Windows Task Manager. Before launching RStudio, I have deleted the "C:\Users\Maulik\AppData\Local\Rstudio" folder. But still RStudio Window doesn't open. It just remains in the Background Processes in the task manager. When I kill this RStudio R Session process from the Windows Task Manager, I get following error report. 
## R Session Startup Failure Report

### RStudio Version

RStudio 2022.11.0-daily+76 "Elsbeth Geranium " (f223ba88, 2022-07-22) for Windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+76 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*C:/Users/Maulik/AppData/Local/RStudio/log/rsession-Maulik.log*

```
2022-07-23T06:45:27.683193Z [rsession-Maulik] ERROR Unable to retrieve user home path. HRESULT:  0x80070003; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool) src/cpp/core/system/Win32System.cpp:341

```

**Comment by kevinushey** [comment]
> PATH                             : C:\rtools42/x86_64-w64-mingw32.static.posix/bin;C:\rtools42/usr/bin;C:\Program Files\R\R-4.2.1\bin\x64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Maulik\AppData\Local\Microsoft\WindowsApps;**C:\rtools40\usr\bin**;C:\Users\Maulik\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.1\bin;;C:\Program Files\JetBrains\PyCharm Edu 2022.1.1\bin;;C:\Users\Maulik\AppData\Roaming\TinyTeX\bin\win32;C:/Program Files/RStudio/resources/app/bin/quarto/bin

You still have Rtools40 on your PATH; you should remove it if you plan to run R 4.2.x.

```
R User Profile: C:/Users/Maulik/Documents/.Rprofile
--------------------------------------------------
# LanguageServer Setup Start (do not change this chunk)
# to remove this, run languageserversetup::remove_from_rprofile
if (requireNamespace('languageserversetup', quietly = TRUE)) {
  options(langserver_library = 'C:/Users/Maulik/Documents/languageserver-library')
  languageserversetup::languageserver_startup()
  unloadNamespace('languageserversetup')
}
# LanguageServer Setup End
```

You might want to remove this from your `.Rprofile`, in case it's the reason why R / RStudio is failing to start.

> 2022-07-23T08:06:30.152850Z [rsession-Maulik] ERROR Unable to retrieve user home path. HRESULT:  0x80070003; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool) src/cpp/core/system/Win32System.cpp:341

The error code 0x80070003 translates to 'The system cannot find the path specified', so presumedly this means Windows is having trouble figuring out what your user's settings path should be. It's possible your AppData or LocalAppData folders aren't user writable; RStudio tries to read and write state in that folder so you may want to double-check those folders are accessible to your user account.

```
APPDATA                          : C:\Users\Maulik\AppData\Roaming
LOCALAPPDATA                     : C:\Users\Maulik\AppData\Local
```

**Comment by bhattmaulik** [comment]
Finally I can close this issue. I have reinstalled Windows 10 and I can open Rstudio now. Thank you for all your support.

**Comment by ronblum** [comment]
@bhattmaulik I'm glad it's now working for you! Although I'm sorry that it took reinstalling windows to take care of it. If you start encountering issues again, please let us know!

**Comment by bhattmaulik** [comment]
Thanks a lot. I am sure the issue with my windows installation itself, because on the last day before I reinstalled Windows, I was unable to open even LibreOffice programs. So, it was not just specific to RStudio. So, I had no other alternative except formatting and reinstalling Windows.
