### ISSUE TITLE
Repeatedly attaching & detaching an external display hangs RStudio GUI

### ISSUE THREAD

**Issue by luwidmer** [rstudio/rstudio#11624]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.3+492
    OS Version      : Windows 10 64 Bit, OS Build 19042.1826
    R Version       : R version 4.1.0 (2021-05-18), Platform: x86_64-w64-mingw32/x64 (64-bit)

### Steps to reproduce the problem
* Repeatedly attach & detach an external display with different DPI settings

### Describe the problem in detail
* The RStudio Desktop IDE hangs after repeatedly attaching & detaching an external display (in this case with different DPI settings, not sure if this is relevant or not)
* The GUI no longer updates, except for the Menu. The about box no longer works, but exporting a diagnostic report does (see attached).

### Describe the behavior you expected
No hanging.

[diagnostics-report-redacted.txt](https://github.com/rstudio/rstudio/files/9119229/diagnostics-report-redacted.txt)

![Screenshot 2022-07-15 101017 Rstudio bug](https://user-images.githubusercontent.com/9111830/179185586-100e90a9-ba81-49c9-abdb-fb7057319cf2.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@luwidmer Thank you for raising this issue! We've run into a few issues with external monitors.

1) What happens if you [change to software rending](https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors)?
2) We're working on porting RStudio Desktop from the Qt to Electron framework, and the switchover resolves some problems. If you'd like to try out the Electron version:
    - Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
    - The Elsbeth Geranium project currently in development, in which [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 

    Please note that the Electron builds are meant for testing and development purposes, not production.

**Comment by luwidmer** [comment]
Hi @ronblum !
1. This also failed on earlier versions, though I cannot tell you which ones exactly since I overwrote the install.
2. Tried this first. Also fails on Software rendering.
3. Saw this today, I'll test drive this on Monday, thanks!

**Comment by luwidmer** [comment]
@ronblum with the Electron build I could not reproduce the issue

**Comment by ronblum** [comment]
@luwidmer Thank you for verifying! Good to know, because 2022.11.0 will be entirely in Electron.
