### ISSUE TITLE
Popped out windows appear blank (after a crash)

### ISSUE THREAD

**Issue by AltfunsMA** [rstudio/rstudio#11623]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.0 Build 548
    OS Version      :  Windows 10
    R Version       :  4.1.0

### Steps to reproduce the problem

I believe this is what happened:

1. Pop out windows in your Rstudio project 
2. Rstudio is forced to quit
3. Re-open the same project

NB: The problem was there when I came back to a specific project after a few months and after installing the latest Rstudio build. I cannot remember very well, but Rstudio may well not have exited normally the last time. Other projects with popped out windows don't have this problem.

### Describe the problem in detail

Some of the popped out windows appear completely blank and cannot be closed, only minimised. (some) windows still somehow contain the scripts they had before because trying to reopen those scripts consistently brings a specific blank window into focus.

![Screenshot 2022-07-15 082445](https://user-images.githubusercontent.com/26325512/179098666-2590df9b-5142-4a53-a91c-b6488e5d7a5c.png)

The problem persists after restarts.

### Describe the behavior you expected

Windows open normally as in previous builds.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@AltfunsMA Thank you for raising this! When you say crash, do you mean that RStudio Desktop closes altogether, or do you get a pop up which then lets you continue using RStudio?

**Comment by AltfunsMA** [comment]
I mean "not exiting normally". Either one of these two scenarios: not being able to terminate R and having to end the task on the Task Manager; or Windows helpfully keeping my computer protected by sneaking in a restart "outside work hours". Probably the same as far as Rstudio is concerned?

I don't know if that's what caused it but those things certainly could have happened the last time I was using that project. And Right now, I cannot recreate the issue when exiting normally.

Since I posted this, I did go into `.Rproj.user/{my_session}/sources/` to see if I could clean things up because the issue was preventing me from editing a crucial script. That script seemed backed up exactly like the others, but the other blank had a value of: `"project_path": null`. (I simply grepped "project_path" in the most recent folder I could find and had a quick look. I deleted those two files, closed Rstudio normally, reopened it and the two blanks had disappeared.

Sorry I cannot offer any more details.

**Comment by johninpdx** [comment]
Actually, a similar (the same?) problem occurs if more than one popped-out window was open when RStudio was shut down normally (Windows, v.2022.07.2, Build 576). One window always shows the table that was open (albeit only the rows and columns, containing no data). This window can be manually closed or repopulated. Any other such open tables, however, remain open, blank, and cannot be manually closed, and the session hangs and cannot be continued. The workaround is to repeatedly shut down RStudio, each time manually closing one such popped-out window. Once there is only one left, the session can continue.

Hope this is pertinent and useful.
