### ISSUE TITLE
Rendering a Quarto document with a custom format like `jss-pdf` changes preview behavior

### ISSUE THREAD

**Issue by dragonstyle** [rstudio/rstudio#11638]
When previewing typical Quarto pdf output, RStudio uses an embedded preview window with some additional nice features. In the case of custom formats that emit pdf (`quarto-journals` articles), the format name is no longer `pdf`, but is instead something like `jss-pdf` or `springer-pdf`. This is likely evading pdf detection in RStudio and resulting in these types of outputs merely opening an external PDF window.

### Steps to reproduce the problem

1) In the terminal: 

- Use the `jss` template:

`quarto use template quarto-journals/jss`

- create a directory
- name the directory `jss`

2) In RStudio, open the `jss/jss.qmd` file and press the render button

### Describe the problem in detail

An external window for previewing the PDF is opened.

### Describe the behavior you expected

The internal previewer should be used.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This seems to work as expected for me now -- the document is opened in the Viewer pane with the accompanying tooling.

<img width="2032" alt="Screenshot 2024-01-23 at 7 49 59 PM" src="https://github.com/rstudio/rstudio/assets/1976582/d6692178-01c2-404d-b35e-a2e5fc89fe4b">

@dragonstyle if there's something I'm missing please let me know!
