### ISSUE TITLE
"Compile Report" keyboard shortcut not working with script

### ISSUE THREAD

**Issue by dhicks** [rstudio/rstudio#11630]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2022.07.0+548 "Spotted Wakerobin" Release (34ea3031089fa4e38738a9256d6fa6d70629c822, 2022-07-06) for macOS
    OS Version      :  macOS Big Sur 11.6.7
    R Version       :  4.1.2 (2021-11-01)

### Steps to reproduce the problem

1. Create or open a `.R` file in RStudio
2. Hit the keyboard shortcut for "Compile Report" (by default Cmd-Shift-K on Mac)

### Describe the behavior you expected

Expected behavior: RStudio brings up the "Compile Report from R Script" dialog box to request the output format, or (if an output format is specified in a Roxygen-commented YAML header) launches a job in the Render tab.  

Actual behavior: Nothing happens.  No error message or warning is produced.  

### Describe the problem in detail

The "Compile Report" UI button and menu command work as expected. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dhicks Thank you for raising this! This works in 1.4.1743 but was either removed or stopped working in 2021.09.x. I'll check internally to see if this was intentional or a bug.

**Comment by ronblum** [comment]
@psboonstra You're right, it is a duplicate. Let's use that one since it has more history, including multiple posts that indicate how confused I was. 🙂
