### ISSUE TITLE
RStudio Server runs a different R kernel than the rsession itself.

### ISSUE THREAD

**Issue by abalter** [rstudio/rstudio#11632]
### System details

    RStudio Edition :  Server (Community) 
    RStudio Version :  2022.07.0 Build 548
    OS Version      :  Ubuntu 22.04 LTS
    R Version       :   R version 4.1.3 (2022-03-10) -- "One Push-Up"

### Describe the problem in detail
I have installed RStudio Server on an Ubuntu 22.04 VM in GCP. I am using Conda for my environments. In the `/etc/rstudio/rserver.conf` file I set `rsession-which-r=/home/balter/conda/bin/R`. 

When I try to preview a notebook I get this popup:

<img src="https://user-images.githubusercontent.com/5349876/179444958-89cbc682-c64c-4293-b5ac-5049e2319699.png" width=400px />

However, the `rmarkdown` version I have installed is the latest (currently 2.14).

As you can see below, at the Rstudio Server console, I display the package version of rmarkdown, and also render a simple notebook successfully.  This tells me that

----

_RStudio Server itself is running a different R kernel than the rsession_

----

How do I make RStudio Server run the same R---i.e. the one in my Conda environment?

```
> packageVersion('rmarkdown')
[1] ‘2.14’
> rmarkdown::render("~/test.Rmd")


processing file: test.Rmd
  |.............................                                                          |  33%
  ordinary text without R code

  |..........................................................                             |  67%
label: unnamed-chunk-1
  |.......................................................................................| 100%
  ordinary text without R code


output file: test.knit.md

/usr/lib/rstudio-server/bin/quarto/bin/tools/pandoc +RTS -K512m -RTS test.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output test.html --lua-filter /home/balter/conda/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/balter/conda/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --variable bs3=TRUE --standalone --section-divs --template /home/balter/conda/lib/R/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable theme=bootstrap --mathjax --variable 'mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /tmp/RtmpJ8BDLQ/rmarkdown-str6b83089a31e.html --variable code_folding=show --variable source_embed=test.Rmd --include-after-body /tmp/RtmpJ8BDLQ/file6b8888632a.html --variable code_menu=1 --variable kable-scroll=1 

Output created: test.nb.html
```

### Describe the behavior you expected
I wouldn't get the annoying popup. I don't get it on my laptop either in RStudio or RStudio Server locally.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

## Test Notebook
 _test.Rmd_
~~~
---
title: "test"
output: html_notebook
---

# A Test
```{r}
print("hello")
```
~~~

## Note
I ran across this SO answer, and the linked repo. I did not get this to work. However, I think it leads in the direction of solving the problem.

https://stackoverflow.com/q/52381661/188963

https://github.com/grst/rstudio-server-conda/tree/master/local

**Comment by ronblum** [comment]
@abalter Thank you for filing the initial report, and the updated info! So if I understand correctly, the main report, regarding `rmarkdown` and `markdown`, is resolved?

Regarding the version of R: As a starting point, can you run the following in the console and check on which R is being used?
```
Sys.which("R")
R.home()
```
Are they incorrect?

**Comment by abalter** [comment]
Wait, I just added a comment. Where did it go? @ronblum -- were you able to look into this?

**Comment by wbvguo** [comment]
Hello, do you have to figure out a solution that enables Rstudio-server switch between environments with different versions of R?

Thanks
