### ISSUE TITLE
Keyboard expansion inside object viewer stops working

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#11633]
### System details

    RStudio Edition : Both Desktop and Server
    RStudio Version : 1.4.938 (but also newer)
    OS Version      : x86_64-pc-linux-gnu (64-bit)
    R Version       : R 4.0.5

### Steps to reproduce the problem
```r
> dd <- list(a=1, b=2, c=3, d=4, e=5, f=6, g=7)
> ee <- list()
> ee <- lapply(1:40, function(i) ee[[i]] <- dd)
> View(ee)
```
Now continuously expand list elements in the viewer, eg by holding down the right arrow key. See attached screen capture.
https://user-images.githubusercontent.com/73080/179472473-bb8c3291-89ae-4550-934d-9a3145e5bcbe.mp4

### Describe the problem in detail
When navigating inside the display of medium/large objects, after a while element expansion with the keyboard stops working.

### Describe the behavior you expected
Uninterrupted keyboard navigation inside large objects

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@OfekShilon Thank you for raising this! I can also reproduce this in 2022.07.1+551 on MacOS 12.5. This appears to be a combination of the number of lists expanded and the total number of elements.

1) With the above code, the last list that expands is the 30th. (7 col x 40 lists)
2) With one less column (remove `, g=7`), the last one expanded is the 34th. (6 col x 40 lists)
3) With 100 lists, the last one expanded is the 36th. (7 col x 100 lists)

**Comment by OfekShilon** [comment]
Not today, stalebot
