### ISSUE TITLE
Caption for each individual outputs in chunks

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11639]
Hi.
I failed to find this feature if already exists.

If a Chunk produces multiple outputs, it would be nice to attach a Caption to it.
I am not talking about the chunk's output, but each individual output

```{r}
iris                             #CAPTION:""" base::IRIS (line:1) """
mtcars                       #CAPTION:""" base::MTCARS (line:2) """
ggplot2::diamonds    #CAPTION:""" ggplot2::DIAMONDS (line:3) """
```

![image](https://user-images.githubusercontent.com/25246225/179777537-b97eff93-fc9c-4079-86ca-25b0eb4701fb.png)

**Comment by ronblum** [comment]
@DiegoJArg Thank you for the suggestion!

@jgutman Is there a way to do this? I'm not sure if this is something an R or RStudio question.
