### ISSUE TITLE
rstudio-prefs.json settings are not restored in RStudio Server

### ISSUE THREAD

**Issue by julioevi** [rstudio/rstudio#11645]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1106
    OS Version      : ubuntu 18.04 (Domino instance)
    R Version       : 4.0.5

### Steps to reproduce the problem
Copy a json file with the following content to `~/.config/rstudio/rstudio-prefs.json`

```json
{
    "reuse_sessions_for_project_links": true,
    "initial_working_directory": "~",
    "editor_theme": "Material",
    "posix_terminal_shell": "bash"
}
```

### Describe the problem in detail

The new theme is not loaded

### Describe the behavior you expected

RStudio loads with the Material theme

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by julioevi** [comment]
running `sudo rstudio-server restart` just returns 
```
 * Restarting RStudio Server rserver                                                  [ OK ] 
rsession: no process found
```

**Comment by ronblum** [comment]
@julioevi Thank you for raising this! A couple of things:
1) What theme shows up instead of Material?
2) What happens with `rstudio-server stop` followed by `rstudio-server start`?
3) What happens if you delete the `rstudio-prefs.json` file and then run `rstudio-server restart`?

**Comment by julioevi** [comment]
It's working now, your suggestions made me realize I had to run `rstudio-server restart` without sudo privileges. Thanks!
