### ISSUE TITLE
Can't change figure resolution (DPI) in R Markdown Notebook

### ISSUE THREAD

**Issue by isaactpetersen** [rstudio/rstudio#11649]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.7.0.548
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : 4.2

### Steps to reproduce the problem

Try running this chunk in this document.

`````
---
output: html_document
---

```{r dpi=300}
plot(cars)
```
`````

### Describe the problem in detail

The DPI does not change when using an RMarkdown Notebook (`output: html_notebook`). However, the DPI does change when using and knitting a RMarkdown file (`output: html_document`).

This same issue has been reproduced by others:
https://stackoverflow.com/questions/46100065/cant-change-dpi-in-png-image-in-rmarkdown-notebook
https://stackoverflow.com/questions/53884985/how-can-i-change-dpi-inline-code-output-in-notebook-rmarkdown
https://community.rstudio.com/t/r-markdown-chunks-dpi-option-ignored-on-run-current-chunk/34038/2

I'm attaching a reproducible example here: [reproducibleExample.zip](https://github.com/rstudio/rstudio/files/9161263/reproducibleExample.zip)

### Describe the behavior you expected

The figure resolution should change in an RMarkdown Notebook (like it does in an RMarkdown file) when setting the DPI.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@isaactpetersen Thank you for raising the issue! Are you expecting that the different DPI is recognized with the inline rendering of chunks in the Editor Pane, or in the rendered document after clicking on "Preview"?

**Comment by isaactpetersen** [comment]
@ronblum Thanks for the response. I don't see a "Preview" button in UI. Here's what I see:
![image](https://user-images.githubusercontent.com/3749025/181647795-8b547149-bd1b-4c27-82d5-cd1b629a49f9.png)

I'm expecting the different DPI when:
1) I click "Run" -> "Run All" in the top right of the screen, and
2) If I press the green button next to each chunk to render it inline

After doing either of those and saving the file, it creates a `.html` file, but it does not have figures with different DPI. Does that make sense?

**Comment by ronblum** [comment]
@isaactpetersen Thanks for the info! It'll be useful when we consider this. This might be by design, given the differences between knitting vs. running chunks within the document. But I'll keep this tagged as a bug for now.

Also, to get the preview button: 
1. Change the order of the entries of the `output` field in the YAML so that `html_notebook` comes first.
2. Save the file.

The button formerly known as "Knit" will change to "Preview", letting you preview the notebook with only the chunks you've run.

**Comment by isaactpetersen** [comment]
@ronblum Thanks for the tip to get the preview button. I confirmed that the dpi does **not** change when using the preview button.

I'm not sure why it would be design that the user could not change the DPI of the figures when using R Markdown Notebooks. The default figure resolution is quite low. So, the figures from R Markdown Notebooks are essentially not usable for publications or presentations. I understand why the resolution is low by default, but it'd be nice to allow the user to specify a different resolution for figures (to be used in publications, presentations, etc.).

**Comment by cderv** [comment]
Just for reference, a bunch of issues regarding plot should be dealt with and this seems related : https://github.com/rstudio/rstudio/issues/12740

**Comment by cderv** [comment]
I believe this is still an issue

**Comment by dekan-aleksandr** [comment]
I also believe it is highly important

**Comment by LKremer** [comment]
would be nice to have this functionality

**Comment by krshedd** [comment]
Agreed, this would be very helpful for lifting figures out of a notebook. I'm unclear what the DPI arguments are for if they don't work?

**Comment by deaneckles** [comment]
Really missing this functionality. For a workflow where you might want to copy and paste a figure from a notebook to an email or Slack message, this means (as far as I understand) that you need to write each such figure to a separate file to make that possible, otherwise you are stuck with low resolution (often unusable) plots.

**Comment by jxchong** [comment]
@deaneckles describes exactly my workflow. I copy and paste from the notebook to email/slack all the time and it's a pain to have to save each figure to disk (need to come up with a name and the figure/margin/label position settings usually need to be different when written to disk than viewed on screen)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+277 on Windows 11.
