### ISSUE TITLE
Log elapsed time on Chunk execution

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11653]
To be performance-aware, one has to add system.time() calls on every chunk. 

When knitting, there is the chance to [add a hook](https://bookdown.org/yihui/rmarkdown-cookbook/time-chunk.html) that would run when knitting.

The feature request is to log this automatically to console, or any other, when Ctrl+Shift+Enter.

**Comment by ronblum** [comment]
@DiegoJArg Thank you for the suggestion! We'll review this as part of our continuing development of RStudio.
