### ISSUE TITLE
Backport #11586 to 2022.07.2

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#11659]
Tracking backport of #11586 to SW

**Comment by jgutman** [comment]
Commits 
65b3e6e37eba84e37832c39b018e9cab2a3095ec 
28f8db3bee5b348b8a50219704cdfb2548eb9d57 
1e9d6842c88b471f3057bd805d8c8ef85fb86b79

**Comment by jonvanausdeln** [comment]
Verified with 2022.07.2-557

Windows11, Ubuntu 22.04

Tested several different themes
