### ISSUE TITLE
Backport #11619 to 2022.07.2

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#11658]
Track backport of #11619 to SW patch

**Comment by jgutman** [comment]
Merged in [4b668cb](https://github.com/rstudio/rstudio/commit/4b668cbb3f75f6977c21a03624390e3c5c0aead5)

**Comment by jonvanausdeln** [comment]
Verified on 2022.7.2-557
Windows 11, Ubuntu 22.04
Tested on with several different files in different locations and varied document contents.
