### ISSUE TITLE
Character matrix displayed as vector in environment panel

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#11667]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.0+548 "Spotted Wakerobin" 
    OS Version      : Windows 10
    R Version       : 4.2.1

### Steps to reproduce the problem

Create the two matrices below
```r
M1 <- matrix(letters, nrow = 13)
M2 <- matrix(1:26, nrow = 13)
```
Check the environemnt panel

### Describe the problem in detail

The character matrix is displayed as a vector in the environment panel, i.e. as chr[1:26].
For comparison, the numeric matrix is displayed correctly int[1:13, 1:2]

### Describe the behavior you expected

The character matrix displayed in a similar way as the numeric matrix, so with its dimensions included.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@BartJanvanRossum Thank you for raising the issue! I can reproduce it as well in RStudio Desktop 2022.07.1+554 on MacOS 12.5. We'll review this as we continue to develop RStudio.

**Comment by kevinushey** [comment]
Relevant code:

https://github.com/rstudio/rstudio/blob/78304dbc448cec4165bd115d91eb1aac4a52c15f/src/cpp/session/modules/SessionEnvironment.R#L71-L97

**Comment by BartJanvanRossum** [comment]
Issue still exists in RStudio 2022.12.1+356 "Elsbeth Geranium" Release

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2024.04.0-daily+495 on MacOS 14.4
- Posit Workbench 2024.04.0-daily+478.pro12 on Ubuntu 22.04 via Chrome on MacOS 14.4

Also did a quick check that the data shows up correctly in the Data Viewer (this was never a problem, just comparing the data).
