### ISSUE TITLE
Allow customization of Git pane buttons in RStudio preferences

### ISSUE THREAD

**Issue by njlyon0** [rstudio/rstudio#11669]
I use Git via RStudio all the time and love the efficiency of having buttons to push rather than needing to remind myself of the command line equivalents. That said, I often struggle with being able to see the needed buttons due to the rightmost buttons being cropped out when the Git pane is too narrow to display them.

Given that users may use various Git features at different rates, it would be nice if in RStudio's preferences we could remove buttons that we didn't use frequently. This "removal" could just nest selected options under the Settings gear icon (where "Revert" and "Ignore" are currently) so that they'd still be accessible but this would make the tab a lot more manageable.

Here's an example of what this could look like after customization:

![rstudio-custom-git-pane-example](https://user-images.githubusercontent.com/21199610/181080694-2348abc8-ee0b-437a-ae06-b5b588c8cf5c.png)

This I think also gets at the redundant buttons for Diff and Commit (see this issue: https://github.com/rstudio/rstudio/issues/9896) and – I would argue – the redundant History clock button (given that is a tab within the window opened by either the Diff or Commit buttons).

Being able to choose which buttons we want would also help with the issue some users have had (myself included) in being able [to see the refresh button in the top right when branch names are long](https://github.com/rstudio/rstudio/issues/11590)

This would also avoid the addition of new features like Git's `stash` functionality (https://github.com/rstudio/rstudio/issues/9423 & https://github.com/rstudio/rstudio/issues/8603) further cramping the Git pane and making it harder to get to whichever options are furthest to the right.

Thanks for making an amazing IDE and I hope this suggestion is helpful (and adheres to the 'good feature requests' instructions)!

**Comment by ronblum** [comment]
@njlyon0 Thank you for the detailed enhancement request, in! We'll consider it as part of our ongoing development of RStudio. And I appreciate the kind words—I'll pass it on to the rest of the team, as well!
