### ISSUE TITLE
YAML metadata in `.Rmd` docs don't have syntax highlighting if not at the beginning of the document

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#11662]
### Describe the problem in detail

Although YAML metadata is typically at the beginning of the `.Rmd` document, it is perfectly legal to move it to a later position in the document, and the document will knit without any problem.

But the syntax highlighting for YAML metadata seems to work only when it's at the beginning, 

<img width="521" alt="Screenshot 2022-07-23 at 10 42 26" src="https://user-images.githubusercontent.com/11330453/180598100-fa274554-a2a8-4ed2-bd0a-3eca3216cb4f.png">

and not otherwise:

<img width="539" alt="Screenshot 2022-07-23 at 10 42 44" src="https://user-images.githubusercontent.com/11330453/180598101-4ba0819c-29bd-4e5a-89f5-8f861d837e3b.png">

### System details

<img width="911" alt="Screenshot 2022-07-23 at 10 58 05" src="https://user-images.githubusercontent.com/11330453/180598172-19ad371b-bf01-4a39-a666-ceb4aa053e9b.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I believe this is intentional; to the best of my knowledge, R Markdown only considers YAML metadata blocks located at the start of the document (and a lot of RStudio tooling relies on that fact).

**Comment by cderv** [comment]
yes I confirm. @IndrajeetPatil your example won't work with R Markdown - output key won't be picked up by `rmarkdown::render()`

This will work only for Pandoc's variable set in YAML and not process by R Markdown at any point, only with Pandoc - like `title` or `author`.

**Comment by IndrajeetPatil** [comment]
Ah, I see.

Thanks for the explanation for why this won't work :)
