### ISSUE TITLE
python chunks with empty lines aren't run 

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11665]
### System details

    RStudio Edition : 2022.10.0-daily+68
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.4
    R Version       : R version 4.2.1 (2022-06-23)

### Steps to reproduce the problem

Create an R Markdown document, with a chunk containing the following:

`````
```{python}
def example():
  print("I'm part of the function definition!")

  print("I'm also part of the function definition!")

example()
```
`````

Then, try to run it using the chunk Run button.

### Describe the problem in detail

The empty line "ends" the function definition, and so the second `print()` statement doesn't actually become part of the code.

```
>>> def example():
...   print("I'm part of the function definition!")
... 
>>>   print("I'm also part of the function definition!")
I'm also part of the function definition!
>>> 
>>> example()
I'm part of the function definition!
```

### Describe the behavior you expected

The code should be parsed and run as a single unit, so that the resulting code is:

```
>>> def example():
...   print("I'm part of the function definition!")
...   
...   print("I'm also part of the function definition!")
... 
>>> example()
I'm part of the function definition!
I'm also part of the function definition!
```

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] renv_0.15.5-43

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9          here_1.0.1          lattice_0.20-45    
 [4] png_0.1-7           rprojroot_2.0.3     digest_0.6.29      
 [7] grid_4.2.1          jsonlite_1.8.0      evaluate_0.15      
[10] rlang_1.0.4         cli_3.3.0           rstudioapi_0.13    
[13] Matrix_1.4-1        reticulate_1.25     rmarkdown_2.14     
[16] tools_4.2.1         xfun_0.31           yaml_2.3.5         
[19] fastmap_1.1.0       compiler_4.2.1      BiocManager_1.30.18
[22] htmltools_0.5.3     knitr_1.39         
```

</details>

**Comment by kevinushey** [comment]
We have a bunch of code that tries to pre-process console input here, to fix up indents:

https://github.com/rstudio/rstudio/blob/78304dbc448cec4165bd115d91eb1aac4a52c15f/src/cpp/session/SessionConsoleInput.cpp#L161-L288

It seems like this code is working as expected for regular Python scripts, but not for Python chunks in R Markdown documents.

**Comment by kevinushey** [comment]
I think the cleanest solution would be to pre-process chunk code before submitting it, to fix up blank line indentation so that it matches the user's expectation.

**Comment by kevinushey** [comment]
(Another alternative would be to save the last console input / current block indentation on the session side, and then use that to fix up console input -- but we'd need to have some way to differentiate between "blocks" of Python code versus a single empty line of Python code which might intentionally be terminating a block)

**Comment by ronblum** [comment]
Verified fixed in RStudio Desktop 2022.11.0-daily+98 on MacOS 12.5.

````
> reticulate::repl_python()
>>> def example():
...   print("I'm part of the function definition!")
...   
...   print("I'm also part of the function definition!")
...   
... example()
I'm part of the function definition!
I'm also part of the function definition!
>>> 
>>> quit
> 
````

**Comment by ronblum** [comment]
Leaving open as candidate for an automated test. I'm not sure it's worth doing so but at least to be considered.

**Comment by mikebessuille** [comment]
can't leave this open in Elsbeth, as EG is done.  I think I'll close this, as the remaining automation is already reflected in a separate ticket (859).
