### ISSUE TITLE
delay rendering of hyperlink popups

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#11664]
instead of showing the popup immediately, introduce some delay so that the popup only shows if the cursor is still over the hyperlink after some time.

**Comment by romainfrancois** [comment]
QA notes: see https://github.com/rstudio/rstudio/pull/11732

**Comment by ronblum** [comment]
Verified that the pop up takes a moment to show up, in
- RStudio Desktop 2022.11.0+98 on MacOS 12.5 
- RStudio Server 2022.11.0+98 on Ubuntu 20.04 via Chrome on MacOS 12.5.

```
> cli::style_hyperlink("summarise", "ide:help:dpylr::summarise")
<cli_ansi_string>
[1] summarise
> cli::`style_hyperlink`(url = "http://rstudio.com", text = "RStudio")
<cli_ansi_string>
[1] RStudio
```

(`summarise` and `RStudio` are now hoverable and clickable.)

(Note: Used version 2022.07.1+554 as a comparison point.)
