### ISSUE TITLE
Add syntax highlighting for Snakemake and Nextflow

### ISSUE THREAD

**Issue by Dries-B** [rstudio/rstudio#11677]
Dear RStudio developers,

I would like to request to add syntax highlighting for workflow management languages Snakemake (implemented in Python) and Nextflow (an extension of Groovy).

I think that these languages are popular enough with (data) scientists, so that including them in Rstudio would make sense.

**Comment by Dries-B** [comment]
For Snakemake, an easy milestone could already be to allow Rstudio to read files called 'Snakefile' or '*.smk' as a Python file.

**Comment by kevinushey** [comment]
Would you be willing to prepare a pull request? We register a number of filetypes here: https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java#L324

See https://github.com/rstudio/rstudio/commit/59cab5bba624acd1574b144ab828d14728b70561 for an example where we added support for Observable JS (`.ojs`) files.

**Comment by jemunro** [comment]
@kevinushey have made a PR for Nextflow
