### ISSUE TITLE
Unable to start Elsbeth Geranium

### ISSUE THREAD

**Issue by sfr** [rstudio/rstudio#11672]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.11.0-daily-78
    OS Version:  Windows 10 x64 (build 19044)
    R Version: 4.2.1

### Describe the problem in detail
Unable to start Elsbeth Geranium 2022.11.0-daily-78, actually none of the Elsbeth Geranium versions so far. Other versions e.g.  Spotted Wakerobin, start fine.
![err msg](https://user-images.githubusercontent.com/2040557/181179266-93b49e3c-c66a-4cd4-a25a-ba378756b30b.png)

#### Diagnostics
    c:\development\RStudio-2022.11.0-daily-78\resources\app\bin>"Run Diagnostics.lnk"
    ERROR: The system was unable to find the specified registry key or value.
    ERROR: The system was unable to find the specified registry key or value.

#### Registry
I do not have administrative privileges to `HKEY_LOCAL_MACHINE,` so everything is in `HKEY_CURRENT_USER`

    [HKEY_CURRENT_USER\SOFTWARE\R-core]
    
    [HKEY_CURRENT_USER\SOFTWARE\R-core\R]
    "Current Version"="4.2.1"
    "InstallPath"="c:\\development\\r-4.2.1"
    
    [HKEY_CURRENT_USER\SOFTWARE\R-core\R\4.2.1]
    "InstallPath"="c:\\development\\r-4.2.1"
    
    [HKEY_CURRENT_USER\SOFTWARE\R-core\R64]
    
    [HKEY_CURRENT_USER\SOFTWARE\R-core\R64\4.2.1]
    "InstallPath"="c:\\development\\r-4.2.1"
    
    [HKEY_CURRENT_USER\SOFTWARE\R-core\Rtools]
    "InstallPath"="C:\\rtools42"
    "Current Version"="4.2"
    
    [HKEY_CURRENT_USER\SOFTWARE\R-core\Rtools\4.2]
    "InstallPath"="C:\\rtools42"
    "FullVersion"="4.2.0.1"

#### Environment variables (amongst others)
    Path=c:\development\r-4.2.1\bin\x64\
    RTOOLS42_HOME=C:\rtools42
    R_HOME=C:\development\r-4.2.1
    R_LIBS=c:\development\r-4.2.1\library\

#### Session info from working Spotted Wakerobin
    > sessioninfo::session_info()
    ─ Session info ───────────────────────────────────────────────────────────────
     setting  value
     version  R version 4.2.1 (2022-06-23 ucrt)
     os       Windows 10 x64 (build 19044)
     system   x86_64, mingw32
     ui       RStudio
     language (EN)
     collate  English_Ireland.utf8
     ctype    English_Ireland.utf8
     tz       Europe/Prague
     date     2022-07-27
     rstudio  2022.07.1+555 Spotted Wakerobin (desktop)
     pandoc   NA

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sfr Thank you for raising the issue! Does the problem occur on earlier versions of R? You can install multiple versions of R and tell RStudio Desktop to switch to a different version by holding the <kbd>Ctrl<./kbd> key when the application is starting up.

**Comment by kevinushey** [comment]
Indeed, the prior Qt version queried both HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER:

https://github.com/rstudio/rstudio/blob/78304dbc448cec4165bd115d91eb1aac4a52c15f/src/cpp/desktop/DesktopRVersion.cpp#L264-L270

But in Electron we're only looking at HKEY_LOCAL_MACHINE:

https://github.com/rstudio/rstudio/blob/78304dbc448cec4165bd115d91eb1aac4a52c15f/src/node/desktop/src/main/detect-r.ts#L379-L406

We should consider both in Electron as well.

**Comment by jgutman** [comment]
@sfr this should now be fixed in the latest daily build -- [2022.11.0-daily+111](https://dailies.rstudio.com/version/2022.11.0-daily+111) or higher, if you'd like to try it out

**Comment by sfr** [comment]
@jgutman, I tested it on 2022.11.0-daily-113, and it is working. Thank you.

**Comment by ronblum** [comment]
Thank you for verifying, @sfr!
