### ISSUE TITLE
The Desktop edition doesn't install rstudio-server that is needed to get diagnostics report

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#11675]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1+554
    OS Version      : FreeBSD 13.1
    R Version       : 4.2.1

### Steps to reproduce the problem
It asks [here](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report) to run ```rstudio-server``` but in the Desktop edition it isn't installed.

### Describe the problem in detail
Only the Server edition installs ```rstudio-server```.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
This is by-design. Further down that page are the instructions for creating Desktop diagnostics, look under the heading "RStudio Desktop IDE".
