### ISSUE TITLE
'Insert spaces for Tab' doesn't work

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#11673]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1+554
    OS Version      : FreeBSD 13.1
    R Version       : 4.2.1

### Steps to reproduce the problem
Change the checkbox 'Insert spaces for Tab' in Tools/Global Options/Code to ON.

### Describe the problem in detail
After clicking Apply and Ok the editor still keeps typed tabs and doesn't replace them with spaces.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you have auto-detect code indentation enabled? If so, then an indentation inferred from a document could override a user-selected indentation:

<img width="602" alt="Screen Shot 2022-07-27 at 2 49 50 PM" src="https://user-images.githubusercontent.com/1976582/181349580-713974dc-5818-4665-8542-4e123b58b8a6.png">

If not, does this only affect documents which are already currently open, or does it also effect newly-opened documents as well?
