### ISSUE TITLE
Making the choice for syntax highlighting easier

### ISSUE THREAD

**Issue by Dries-B** [rstudio/rstudio#11678]
Dear RStudio developers,

It would be convenient if files that RStudio does not recognize (because of their suffix) would allow for a choice of syntax highlighting.

This could be done by asking the user to choose from a menu of syntax profiles to choose from when a file is loaded. A less intrusive alternative would be providing a hotkey for accessing the language menu:

![image](https://user-images.githubusercontent.com/29752595/181749636-cd917700-bcfd-4224-b47d-29f0b7e16d68.png)

**Comment by ronblum** [comment]
@Dries-B Thank you for the suggestion! Do you mean a file of one type with the syntax highlighting of another type, which is supported by RStudio? In that case, do you mean the equivalent of clicking on the file-type menu at the lower right but right when the file is loaded?

**Comment by Dries-B** [comment]
> Do you mean a file of one type with the syntax highlighting of another type, which is supported by RStudio?

Yes 👍

> In that case, do you mean the equivalent of clicking on the file-type menu at the lower right but right when the file is loaded?

Yes 👍

**Comment by Dries-B** [comment]
Actually, as stated in my original comment, I think having an extra menu pop up might be too intrusive.

Having a 'what to do with these kinds of files' menu, like Firefox has (/ used to have?) might be more convenient, so that .smk files are always opened as Python code.

And I still think a hotkey for "the file-type menu at the lower right" would be useful. I also noticed that this menu currently does not allow for searching/filtering through typing.
