### ISSUE TITLE
Open R files aren't open any more after Tab-related options are changed and the session is restarted

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#11670]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.999 Build 999
    OS Version      : FreeBSD 13.1
    R Version       : 4.2.1

### Steps to reproduce the problem

1. Have several R files open.
2. In Global Options/Code disable tab auto-replacement and change tab space from 2 to 8
3. Restart R session following application recommendation
4. RStudio comes back without R files open

### Describe the behavior you expected

RStudio should preserve open files on restart.

**Comment by ronblum** [comment]
@yurivict Thank you for raising the issue! A couple of questions:

1)  Does this only occur with the change in tabbing, or have you noticed it under other conditions?
2) Do you know if the issue occurs by [installing the distribution package](https://pkgs.org/download/RStudio)? Although we don't develop for FreeBSD ourselves, there's excellent work being done by the FreeBSD Project.

**Comment by yurivict** [comment]
> Does this only occur with the change in tabbing, or have you noticed it under other conditions?

Now with the new version ```2022.07.1+554``` it doesn't ask me to restart session any more.
Perhaps the behavior has changed?

-------------

> Although we don't develop for FreeBSD ourselves, there's excellent work being done by the FreeBSD Project.

I am the maintainer of the FreeBSD port. Thank you.

**Comment by ronblum** [comment]
@yurivict Ha, I didn't realize it! I couldn't remember your GitHub handle, and I was going to check internally on your name so that I could tag you. 🙂 

@kevinushey Do you have any thoughts on this?

**Comment by kevinushey** [comment]
This sort of sounds like user state (normally stored in `~/.local/share/rstudio`) isn't being saved or restored in R sessions on OpenBSD.

Can you share a diagnostics report or anything similar?
