### ISSUE TITLE
Add "Remove current job" option to the Background Jobs feature

### ISSUE THREAD

**Issue by philiporlando** [rstudio/rstudio#11676]
I regularly use the Background Jobs feature after upgrading to RStudio >=1.2 and it's been excellent so far. One thing I would like to see added is the ability to remove a selected job. Currently, it is only possible to remove all of the existing jobs at once. 

![image](https://user-images.githubusercontent.com/24445174/181635186-e76736ee-0c09-4a9c-a9b8-d2b6026c8725.png)

This requested feature would be similar to the existing "Remove current viewer item" option from the Viewer pane, and the "Remove the current plot" option from the Plot pane. 

![image](https://user-images.githubusercontent.com/24445174/181634829-6ba99784-2650-4776-a9ab-bf68ca9d9dfc.png)

The main advantage I see with this feature is that it allows the developer to maintain a cleaner job history. For example, if I accidentally start a background job with the wrong script, it would be helpful to remove this from the job history so I can focus on only the relevant/valid jobs, without having to sacrifice throwing away the history of valid jobs that were run previously.

Please let me know if I can provide any additional details for this request. I'm looking forward to seeing what ~~RStudio~~ Posit comes up with! Thanks!

**Comment by ronblum** [comment]
@philiporlando Thank you for the suggestion! I think you've provided all of the details we would need as we consider this request—especially with the images.
