### ISSUE TITLE
Error "Unable to establish connection with R session when executing 'zotero_get_library_names'" when choosing Tools->Global Options menu

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#11674]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1+554
    OS Version      : FreeBSD 13.1
    R Version       : 4.2.1

### Steps to reproduce the problem

Go to Tools->Global Options

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/271906/181352751-09104f75-78eb-4f9a-9ed1-6a1ed9d5b14d.png)

When Ok is clicked the options screen opens fine.
R programs also run fine.

This problem began happening after I re-installed and re-started 2022.07.1+554 that was working fine previously.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@yurivict A couple of questions:
1. What's the setting for Zotero libraries at <kbd>Tools -> Global Options -> R Markdown -> Citations -> Zotero Library</kbd>?
2. If there's one set, what happens if you switch it to `(None)`?
3. 
Thanks!

**Comment by yurivict** [comment]
It is already ```(None)```.
