### ISSUE TITLE
Ctrl + Enter in visual editor takes code from a wrong floating/undocked window

### ISSUE THREAD

**Issue by martinmodrak** [rstudio/rstudio#11684]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version :  RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) 
        (issue also persists in the latest daily build - 2022.11.0 +82)
    OS Version      :  Windows 10 (Windows NT 10.0; Win64; x64)
    R Version       :  4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

My work setup is to have main RStudio Window open on one monitor with just console, environment and help panes. Then I have two floating/undocked windows side by side with the source/markdown files I am working with (see Figure below)

![image](https://user-images.githubusercontent.com/9483603/182181914-26f1609a-64d0-4264-b809-fc8cfd8ba610.png)

This however appears to mess up with Quarto visual editor - exact reproduction:

1. Start a fresh session of RStudio
2. Create a new Quarto document from the HTML template. Put it in visual mode.
3. Click "show in new window", move the window elsewhere
4. Create a new R script
5. Click "show in new window", move the window elsewhere
6. Type `3+3` in the new R script window and keep the cursor on that line
7. Click into the code chunk containing `1 + 1` in the Quarto document
8. Press `Ctrl + Enter`
9. `3 + 3` gets executed instead of `1 + 1`

### Describe the problem in detail

This problematic state persist, i.e. I can move cursor in the other source window, click back to a code block in the Quarto window, press `Ctrl + Enter` and have a different line from the other window executed.

When I switch the Quarto document from visual to source and then back, the behavior reverts to expected, but as soon as I click into the window with R script again, the problem reappears.

### Describe the behavior you expected

Expecting to execute the code under cursor in the active floating window.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by venpopov** [comment]
Just stumbled upon the same issue. Seems like it's not a high priority to fix, unfortunately

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+229 on Windows 11. Checked with Quarto in visual mode (fix) and source mode (no regressions).
