### ISSUE TITLE
Floating/undocked Windows result in disconnect between the floating Widows and the main RStudio pane

### ISSUE THREAD

**Issue by martinmodrak** [rstudio/rstudio#11686]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version :  RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) 
    OS Version      :  Windows 10 (Windows NT 10.0; Win64; x64)
    R Version       :  4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

1. Start a fresh session of RStudio
2. Create a new RScript (It will be called "Untitled1")
3. Click "show in new window", move the window elsewhere
4. Create a new R script (It will also be called "Untitled1")
5. Click "show in new window", move the window elsewhere
6. Close RStudio
7. Reopen RStudio

### Describe the problem in detail

There are two problems:
1) Upon undocking the first Window, RStudio restarts numbering of untitled documents, i.e. both documents are called "Untitled1"
2) After reopening RStudio, only one of the floating windows gets properly restored, the other is restored, but is blank, contains no documents and cannot be closed, neither can a document be docked to this window. This problem is not unique to untitled documents - even when everything is named and saved in a project, only one window gets restored. It appears that which of the two is correctly restored is random. Closing and restarting RStudio doesn't help, but closing the correctly restored window and then restarting RStudio results in the remaining window now being correctly restored.

I also tested this with RStudio 2022.02.0+443 and while problem 1 (same names) is present, problem 2 (blank window after reopening) cannot be reproduced there, so something had to change since the previous version to make the behavior worse.

A related problem is  #11684 and #11685

It generally feels like the internal model RStudio has for documents and their connection to the console struggles with multiple floating/undocked windows.

### Describe the behavior you expected

Expecting to execute the code under cursor in the active floating window.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astraetech** [comment]
Same here. Driving me crazy. Blank windows after reopening. Closing and opening and loading random projects and then reloading the problematic project sometimes solves this. Totally random. Any floating window: data viewer, rmarkdown, r code can be blanked.

**Comment by astraetech** [comment]
Found a workaround. Right click on the blank window and click "Reload". Never use right click in RStudio outside of copy paste so didn't even think about it.
