### ISSUE TITLE
Blank window instead of images in Notebook Output

### ISSUE THREAD

**Issue by gabrielparriaux** [rstudio/rstudio#11681]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      : macOS Monterey (12.5), apple M1 chip
    R Version       : 4.1.3 (2022-03-10)

### Steps to reproduce the problem

1. In an Rmd file, create a chunk of R code that plots more than one image.

2. Plot one of these images with this code:

``` r
fviz_ca_row (afc, col.row = "contrib",
             gradient.cols = c ("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```

3. Open the images in a new window with the "Show in New Window" button. 

The image created by this code doesn’t display. It appears in a flash, then disappears and the window stays blank. 

### Describe the problem in detail

Plots generated by R code in an Rmd file appear inline, but are small. To observe them in more details, it is useful to open them in a new window and to be able to resize them.

When the script generates one single plot and I open it in a new window, it behaves correctly.

But when the script generates more than one plot and I open it in a new window, the bug mentioned above appears: image being displayed just a short moment, then disappears and I get a blank window.

It doesn’t happen with every kind of images. The code mentioned above produces the problem, but it’s not the only one. 

In contrary, other images are ok, for example:

``` r
fviz_contrib(afc, choice = "row", axes = 1, top = 30)
```

displays correctly in a new window.

### Describe the behavior you expected

Opening the plots in a new window and having the image displayed correctly, being able to resize it.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gabrielparriaux** [comment]
As I realized, writing the post, that I didn’t have the latest version of R, I updated R to the latest 4.2.1 (2022-06-23). 
The problem remains exactly the same as described.

**Comment by ronblum** [comment]
@gabrielparriaux Thank you for raising the issue! Can you provide a simple, minimal Rmd that reproduces the issue? I've installed the `factoextra` package, but since the `afc` object is undefined, I can't successfully run the snippet.
