### ISSUE TITLE
RStudio Quarto "Render" button produces error for PDF with spaces in filename

### ISSUE THREAD

**Issue by NickCH-K** [rstudio/rstudio#11694]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.01 build 554, Spotted Wakerobin
    OS Version      :  Windows 10
    R Version       :  4.2.1

### Steps to reproduce the problem

1. Create a basic Quarto PDF doc (any should do I think):

```
---
title: "Untitled"
format: pdf
---

## Testing My Doc

hello $X$
```

2. Save it as a filename with a space in it, like `test test.qmd`
3. Click the "Render" button

### Describe the problem in detail

In doing this I get the error `'C:/Program' is not recognized as an internal or external command,
operable program or batch file.`

Note that I do **not** get the error, and the document builds fine, if...

1. Rendering to `docx` or `html`
2. Using a filename without a space in it
3. Using `quarto::quarto_render()` instead of the Render button

The third of these is why I think this is an RStudio issue as opposed to a Quarto or LaTeX issue. I suspect there's a filepath in the internal call to `quarto::quarto_render()` (perhaps to tinyTeX, which would also explain why `docx` and `html` are fine) that's being properly quoted or shortnamed most of the time (thus "Program Files" not normally being an issue) but is somehow un-quoted when the filename itself has spaces.

### Describe the behavior you expected

I expected the PDF to render properly.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@NickCH-K Thank you for raising this! I can reproduce the problem in RStudio Desktop 2022.07.01+554 on Windows 11. We'll review this as we continue development of RStudio, including the integration with Quarto.

Note: This works correctly on MacOS 12.5.

**Comment by Acyrologist** [comment]
This issue occurs for me with both html and pdf render formats. I am running RStudio Desktop 2022.07.01+554 on Windows 10.

**Comment by NickCH-K** [comment]
I also now get it for HTML. My initial HTML test might have accidentally used no spaces or something.

**Comment by blakcjack** [comment]
I have the same issue. For me, the issue occurs when the file has space. Just remove the space from name of the quarto (.qmd) file. It works for me.

**Comment by cderv** [comment]
For reference, related to 
* #11885 
* #11763
* #11804

**Comment by lgaborini** [comment]
For me it is `quarto::quarto_inspect()` that is failing (I guess that the path is not escaped when `system2` is called).  
`quarto::quarto_render()` works fine, and the "Render" button in RStudio too.

``` r
quarto::quarto_inspect("C:\\Users\\User\\New folder\\test.qmd")
#> Error: lexical error: invalid char in json text.
#>                                        NA
#>                      (right here) ------^
```

<sup>Created on 2022-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

```
version  R version 4.2.0 (2022-04-22 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Switzerland.utf8
 ctype    English_Switzerland.utf8
 tz       Europe/Berlin
 date     2022-09-21
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   2.18 @ C:/Users/User/RStudioPreview/bin/quarto/bin/tools/ (via rmarkdown)
```

**Comment by cderv** [comment]
@lgaborini this seems like another issue. Please do open one in https://github.com/quarto-dev/quarto-r so that we can check `quarto::quarto_inspect()` correctly read the Quarto CLI output. Before that, please to update Quarto and see if you still got the issue, I can't reproduce on my side for now. 
Thank you.
