### ISSUE TITLE
Clicking on the backtrace link in the build pane causes severe bugs

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/rstudio#11697]
### System details

    RStudio Edition : Desktop 
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (2022-07-22)
    OS Version      :  Win 10
    R Version       : 4.2.1

### Steps to reproduce the problem

* Run a test from a file or from the build panel and get an error
* Click on the link in the header, everything is fine
* Click on the same link in the backtrace, everything goes wrong

### Describe the problem in detail

When you click on the link in the backtrace, it creates an empty file named like the test file at the project's root.

This file cannot be closed (without any error message).

After that, RStudio becomes unstable and shows error messages when saving files. Note that the file is silently saved anyway, although the console still shows the `*` on the file name.

If you restart the project without erasing `.Rproj.user`, RStudio will start but the project won't open and you will have to kill RStudio from the task manager.

Here is a ScreenToGif animation in case you cannot reproduce this behavior:
![Rstudio](https://user-images.githubusercontent.com/15105152/182572479-67015e8e-2966-4da1-89b6-8675993b4e67.gif)

EDIT: I went a bit fast for my example and put the code outside of `test_that()` but this changes nothing about this issue.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@DanChaltiel Thank you for raising the issue, and thank you for providing the  Can you please provide a simple example of code that causes the issue? I'd like to try to reproduce this using the exact same steps and code. Thanks!

**Comment by DanChaltiel** [comment]
Almost any code triggers the issue.

For instance:

```r
#in R
f = function(x) g(x)
g = function(x) stop("foobar")
#in tests
test_that("Example", {
  f(1)
})
```

Which outputs this:
```
══ Testing test-by_factor.R ════════════════════════════════════════════════════

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]

── Error (test-by_factor.R:4:3): Example ───────────────────────────────────────
Error in `g(x)`: foobar
Backtrace:
 1. crosstable::f(1)
      at test-by_factor.R:4:2
 2. crosstable::g(x)
      at crosstable/R/utils.R:604:4


[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]

Test complete
```

Here, the link to `crosstable/R/utils.R:604:4` is working, but the link to `test-by_factor.R:4:2` triggers the bug.

On a second look, I'm wondering if there is a missing step. `utils.R:604:4` is pointing at `g(x)`, but I would also expect a mention to `f(x)` (on `utils.R:603` in this example)

**Comment by ronblum** [comment]
@DanChaltiel Thank you! Your code was much better than what I was doing. I can reproduce this in RStudio Desktop 2022.07.1+554 on MacOS 12.5, as well. We'll review it as we continue development of RStudio.

**Comment by kevinushey** [comment]
Does this meet the bar for a SW patch release?

**Comment by romainfrancois** [comment]
I believe this is `rlang` issue https://github.com/r-lib/rlang/blob/5c97817c28f3120a10493e51314228bf47a8c6e8/R/trace.R#L869
Is `file` here an absolute path ? cc @lionel- 

However, we can probably add some safety net in case the file does not exist.

**Comment by lionel-** [comment]
This comes directly from the srcref attribute so I'd expect `file` to be an absolute path?

**Comment by romainfrancois** [comment]
But `testthat` does this: 

https://github.com/r-lib/testthat/blob/4d256f58e0c6c949f378545f4f5b7d0e5fdfc0cd/R/expectation.R#L270

```r
cli::style_hyperlink(
        paste0(basename(filename), ":", x$srcref[1], ":", x$srcref[2]),
        paste0("file://", file.path(srcfile$wd, filename)),
        params = c(line = x$srcref[1], col = x$srcref[2])
      )
```

**Comment by romainfrancois** [comment]
`debug(rlang:::src_loc)` then running `devtools:::debug_active_file()` (so that it happens in the console instead of the build pane) on this file: 

```r

```

gives me : 

```
Browse[2]> attr(srcref, "srcfile")$filename
[1] "test-link.R"
Browse[2]> attr(srcref, "srcfile")$wd
[1] "/Users/romainfrancois/work/ansilinks/tests/testthat"
```

and then: 

```
Browse[2]> attr(srcref, "srcfile")$filename
[1] "/Users/romainfrancois/work/ansilinks/R/link.R"
Browse[2]> attr(srcref, "srcfile")$wd
[1] "/Users/romainfrancois/work/ansilinks"
```

Maybe this is a job for `normalizePath()` : 

```
Browse[2]> normalizePath(attr(srcref, "srcfile")$filename)
[1] "/Users/romainfrancois/work/ansilinks/tests/testthat/test-link.R"

(...)

Browse[2]> normalizePath(attr(srcref, "srcfile")$filename)
[1] "/Users/romainfrancois/work/ansilinks/tests/testthat/test-link.R"

```

**Comment by romainfrancois** [comment]
QA note: 

`file://` hyperlinks now go through this `rpc` : 

```r
.rs.addJsonRpcHandler("create_aliased_path", function(path)
{
   if (file.exists(path)) {
      return(.rs.scalar(.rs.createAliasedPath(normalizePath(path))))
   } else {
      return(.rs.scalar(""))
   }
})
```

which handles files (or relative to) in the current working directory, absolute files. It is still best however to give an absolute file path to `cli::style_hyperlink()` because the rpc is called when clicked, and the working directory might have changed by then. 

```r
cat("foo", file = "file.txt")
cli::style_hyperlink("file", "file://file.txt")

dir.create("dir", showWarnings = FALSE)
cli::style_hyperlink("file", "file://dir/../file.txt")
cli::style_hyperlink("file", paste0("file://", file.path(owd, "file.txt")))
```

The 3 links go to the same file.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+221
Windows 11

Tested simple example give by OP as well as cases given by romain. All worked as expected.
