### ISSUE TITLE
CNTRL-ALT-SHIFT-R for C++

### ISSUE THREAD

**Issue by MonteShaffer** [rstudio/rstudio#11698]
I use the shortcut CNTRL-ALT-SHIFT-R in a `R-script` to perform documentation within the RStudio IDE.

Is there an equivalent shortcut to document `Rcpp` code.  The `#' ` has to be replaced with `//' `

**Comment by conig** [comment]
As far as I'm aware there's no shortcut, but you could create an rstudio addin to achieve this. You can then assign a hotkey for your addin. Check out this documentation: https://rstudio.github.io/rstudioaddins/

**Comment by ronblum** [comment]
@MonteShaffer I'll mark this as an enhancement request. A close parallel is that <kbd>Ctrl-Alt-C</kbd> creates a `#` comment in R files but `//` in C++ files. But as @conig points out, creating an addin is a good option , as well!
