### ISSUE TITLE
When more than 6 miniatures per chunk, all others change positions on every click

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11707]
### System details

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
Create a Chunk with multiple outputs.

### Describe the problem in detail
Below the chunk, 
at the miniatures sectin, 
after the first row of 6 miniatures is full, 
every time you click on a miniature all others after 6th moves around. 

I have recently updated Rstudio and this behavior didn't change.

### Describe the behavior you expected
Miniatures should stay in a fixed position.

![image](https://user-images.githubusercontent.com/25246225/183057633-30751845-e37c-4fc8-926d-2f40cf678443.png)
![image](https://user-images.githubusercontent.com/25246225/183057722-c0b19f37-4c21-4b56-a2ec-e068007e150a.png)
![image](https://user-images.githubusercontent.com/25246225/183057787-fde688f3-085c-426a-87c4-c44017996969.png)
![image](https://user-images.githubusercontent.com/25246225/183057860-df20062b-f626-4573-8fef-16d8617f8056.png)

**Comment by ronblum** [comment]
@DiegoJArg Thank you for raising the issue! Could you include an example of the code that creates this issue, so that I can try to reproduce it?

**Comment by DiegoJArg** [comment]
Is reproducible by making many outputs on the same chunk.
However, it seems that plots triggers it easier.

```{r}
iris
cat("texto\n")
plot(iris$Sepal.Length,iris$Sepal.Width)
plot(iris$Sepal.Length,iris$Sepal.Width)
iris %>% ggplot() + geom_line( aes( Sepal.Length, Sepal.Width  )  )
cat("texto\n")
cat("texto\n")
iris
iris
iris
iris
iris
iris
iris
iris
iris %>% ggplot() + geom_line( aes( Sepal.Length, Sepal.Width  )  )
plot(iris$Sepal.Length,iris$Sepal.Width)
iris %>% ggplot() + geom_line( aes( Sepal.Length, Sepal.Width  )  )
cat("texto\n")
iris
iris
iris
iris
plot(iris$Sepal.Length,iris$Sepal.Width)
plot(iris$Sepal.Length,iris$Sepal.Width)
iris
plot(iris$Sepal.Length,iris$Sepal.Width)
iris
```

![image](https://user-images.githubusercontent.com/25246225/183474405-09a6e1dd-ba75-4c83-a4ab-ca460591df16.png)
