### ISSUE TITLE
Path issues on Mac when default terminal is fish

### ISSUE THREAD

**Issue by mdhall272** [rstudio/rstudio#11700]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_5_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  macOS Monterey 12.5
    R Version       :  4.2.1

If fish is your default login shell, load RStudio from the macOS GUI and try e.g. 

```
library(devtools)
install(".")
```

for a package directory. It does not work. The error is:

```
   /Library/Frameworks/R.framework/Resources/bin/R: line 143: exec: sh: not found
Error in c("(function (command = NULL, args = character(), error_on_status = TRUE, ",  : 
  ! System command 'R' failed
Type .Last.error.trace to see where the error occurred
```
The problem I think is that the PATH variable as given in RStudio combines fish and zsh/bash syntax:

```
> system("echo $PATH")
/usr/local/Caskroom/miniconda/base/bin /usr/local/Caskroom/miniconda/base/condabin /Users/mdhall/Library/Python/3.7/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Frameworks/R.framework/Resources /Library/Apple/usr/bin /opt/X11/bin /Library/TeX/texbin:/Users/mdhall/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/MacOS/quarto/bin:/Applications/RStudio.app/Contents/MacOS 
```

There are no problems if the default shell is zsh, or indeed if RStudio is loaded at the command line via `open /Applications/RStudio.app`.

This may have something to do with https://github.com/rstudio/rstudio/issues/10997

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dropsplash** [comment]
Dear all, 
I do have the same issue as @mdhall272 even with zsh+oh-my-zsh with the same Rstudio , R and MacOs versions.   I believe they is an issue with setting the paths on macos (can't find tar ... when installing a package, ... ). 

Also I can not 

- open a new project :  **(TypeError) : Cannot read property 'python' of null** 
- neither a Quarto document :  **State not recoverable'**

As @mdhall272 everything works great when open /Applications/RStudio.app via a terminal. 

Kind regards
