### ISSUE TITLE
Error message when previewing HTML file

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#11719]
### System details

    RStudio Edition : Desktop Electron
    RStudio Version : EG daily 87
    OS Version      : Mac 12.4
    R Version       : 4.2.1

### Steps to reproduce the problem
1. Open an HTML file in an editor
2. Use the preview button on the editor toolbar
3. Close the preview
4. Open the preview again

### Describe the problem in detail
The previous satellite window was not cleaned up and results in an error message dialog when showing the preview. The preview opens successfully despite the error.

![image](https://user-images.githubusercontent.com/9591545/183463218-8d7356c6-2604-4b77-b3f4-c4f0966a998e.png)

https://github.com/rstudio/rstudio/blob/24624909eab14c01505d0cf0c6a8b3e636b3e138/src/node/desktop/src/main/satellite-window.ts#L42

The window is registered but does not appear to be unregistered when closed.

### Describe the behavior you expected
No error message should be shown.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
Taking this on as part of #11252. It's preventing the url navigation check because it fails to find the satellite window when launching a Shiny app. There's a mechanism with `gwt-callback` that calls code on the message sender (the satellite window) but encounters errors when checking known windows (previous satellite and secondary windows aren't cleaned up).

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.11.0-daily+160 on MacOS 13
- RStudio Server 2022.11.0-daily+160 on Red Hat 8.6
 
Checked the preview button both when closing the preview window and when the preview window is still open.
Used RStudio Desktop 2022.10.0-daily+64 as a comparison point to reproduce the original issue.
