### ISSUE TITLE
The generated beamer for qmd documents can be previewed in the Viewer Pane, but not for Rmd documents

### ISSUE THREAD

**Issue by chuxinyuan** [rstudio/rstudio#11715]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.7.1.554
    OS Version      : Ubuntu 20.04.4 LTS
    R Version       : 4.2.1

### Steps to reproduce the problem

qmd documents code as follow:

````
---
title: "Quarto beamer"
format: 
  beamer: 
    theme: Verona
---

## Test

Test document.
````
Rmd documents code as follow:

````
---
title: "R Markdown beamer"
output: 
  bookdown::beamer_presentation2: 
    latex_engine: xelatex
    theme: Verona
---

## Test

Test document.
````

The generated beamer for qmd documents can be previewed in the Viewer Pane, but not for Rmd documents

### Describe the behavior you expected

I hope Rmd documents can be previewed in the Viewer Pane.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@chuxinyuan Thank you for raising this! This is a new feature that was introduced for documents rendered by Quarto. I'll mark this as an enhancement request for R Markdown documents, as well.

**Comment by chuxinyuan** [comment]
In fact, I mentioned this a long time ago. Check out #7129

**Comment by ronblum** [comment]
I'll close this one as a duplicate and reference the new capability with Quarto files in #7129.
