### ISSUE TITLE
Dockerfile syntax highlight is only available for a file named 'Dockerfile'

### ISSUE THREAD

**Issue by lisovyk** [rstudio/rstudio#11713]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.2.3.492
    OS Version      :  macOS Monterey 12.4
    R Version       :  R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem
Open RStudio
Create Dockerfile -> you have a syntax highlight
Create another Dockerfile, with a different name(e.g `Dockerfile_libs`, `Dockerfile.scraping`) -> No syntax highlight, no option to choose the correct highlight

### Describe the problem in detail
The problem is simple, another editor I use (VSCode) highlights docker syntax in all docker files that start with `^Dockerfile.*`, RStudio does so only with a file named `Dockerfile`. 
There is no option to choose 'Dockerfile' highlighting in the dropdown menu in the bottom right of the 'Source" panel. It is present when editing a file named `Dockerfile`, though, but is missing otherwise.

### Describe the behavior you expected
I expect RStudio to understand there might be multiple dockerfiles react with correct highlighting to files named `^Dockerfile.*`, and add option to choose highlighting to the dropdown in the bottom right of source panel

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@lisovyk Thank you for raising the issue! We'll review this as we continue development of RStudio.
