### ISSUE TITLE
Can't "Open in browser" after rendering Rmarkdown document

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#11712]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2022.11.0-daily+82 "Elsbeth Geranium" Daily
    OS Version      :  Windows 11
    R Version       :  4.2.1

### Steps to reproduce the problem
Write a Rmarkdown file and render it
### Describe the problem in detail
After rendering, a window pop-up that allow us to "Open in browser". However, this function is not working with this build of Rstudio. For previous build, I use and it is fine
### Describe the behavior you expected
After rending Rmarkdown, the document can open in browser

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ntluong95 Thank you for raising the issue! Can you check with the latest build of RStudio Desktop, 2022.11.0-daily+88? I was able to reproduce the issue with a previous version, but it appears to be resolved.

**Comment by kevinushey** [comment]
I can reproduce with a user account containing non-ASCII characters in the name; for example:

![Screenshot 2022-08-18 153551](https://user-images.githubusercontent.com/1976582/185507266-6e0e3065-08b2-404a-94d9-1c3465c9f63b.png)

Perhaps that's related?

**Comment by kevinushey** [comment]
Ah, no, it's not that -- I think it's instead that we're not resolving the home directory correctly. Note that on Windows, the home directory is by default the document directory:

```
> path.expand("~/")
[1] "C:/Users/kevin/Documents/"
```

This can be overridden by setting the `HOME` or `R_USER` environment variables.

However, we're resolving the home directory in Electron using `os.homedir()`, which only looks at `USERPROFILE`.

https://github.com/rstudio/rstudio/blob/main/src/node/desktop/src/core/user.ts#L21-L29

See the associated code on Qt here:

https://github.com/rstudio/rstudio/blob/main/src/cpp/shared_core/system/Win32User.cpp#L170-L173

I think we need to port this over to Electron; those need to be checked before `os.homedir()` to match R's behavior.

For reference, here's where R figures out the home directory:

https://github.com/wch/r-source/blob/7a0e455716fe488d396bf2c089c9ac5c7765585f/src/gnuwin32/shext.c#L52-L79

And the implementation for ShellGetPersonalDirectory:

https://github.com/wch/r-source/blob/7a0e455716fe488d396bf2c089c9ac5c7765585f/src/gnuwin32/shext.c#L26-L45

**Comment by jgutman** [comment]
Wait I'm confused. Didn't I just fix this in another issue? Is that fix not working, or does it need to be fixed in another area?

**Comment by kevinushey** [comment]
Are you referring to https://github.com/rstudio/rstudio/pull/11756? That fixes the issue where the `R_USER` + `HOME` environment variables weren't being respected, but we still need to choose the correct "default" home location on Windows, which isn't `os.homedir()`.

**Comment by kevinushey** [comment]
I think @jonvanausdeln's comment in https://github.com/rstudio/rstudio/issues/11635#issuecomment-1213504044 also matches what I'm seeing.

**Comment by jgutman** [comment]
Ah yeah 11756 was just made in response to Jon's comment in 11635 but I see what you're saying that there are also a couple of other pieces of that implementation still missing
