### ISSUE TITLE
Quotation mark is not autocompleted for Python code in Rmarkdown but completed in py script

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#11711]
### System details

    RStudio Edition : 
    RStudio Version :  RStudio 2022.11.0-daily+82 "Elsbeth Geranium" Daily
    OS Version      :  Window 11
    R Version       :  4.2.1

### Describe the problem in detail
When in Python code chunk in Rmarkdown file, typing quotation mark will not double as it should be. It happened with both single quotation mark ' and double quotation mark ". 

In the py script, typing one double quotation mark " will autocomplete the other, but typing single quotation mark will not
### Describe the behavior you expected
Quotation mark will autocomplete when writing python script

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ntluong95** [comment]
I noticed that when typing in python console, both single and double quotation mark are auto completed. So the problem is cannot autocomplete single and double quotation mark in python code chunk and cannot autocomplete single quotation mark in .py script

**Comment by ronblum** [comment]
@ntluong95 Thank you for raising the issue! I can reproduce this in in RStudio Desktop 2022.07.1+554 and 2022.11.0+88 on MacOS 12.5, both with R Markdown and Quarto documents. We'll review it as we continue development of RStudio.

**Comment by ntluong95** [comment]
Thanks @ronblum Where I can look if I want to fix the issue?

**Comment by ronblum** [comment]
@ntluong95 Excellent question! We have information about it in [the repository's wiki](https://github.com/rstudio/rstudio/wiki), starting with [A Beginner's Guide to Writing RStudio IDE Features](https://github.com/rstudio/rstudio/wiki/A-Beginner's-Guide-to-Writing-RStudio-IDE-Features) and other topics under the "Developing" section.

**Comment by ntluong95** [comment]
Hi @ronblum, I cannot find the files that containing codes regarding to the issue

**Comment by ntluong95** [comment]
> @ntluong95 Thank you for raising the issue! I can reproduce this in in RStudio Desktop 2022.07.1+554 and 2022.11.0+88 on MacOS 12.5, both with R Markdown and Quarto documents. We'll review it as we continue development of RStudio.

I dont know whether this feature should be fixed, at least for Quarto?

**Comment by lbeiby** [comment]
confirm the bug. It also happens with other languages in Rmarkdown code chunks, not only Python @kevinushey @ronblum

**Comment by kevinushey** [comment]
We'd probably need to implement these here:

https://github.com/rstudio/rstudio/blob/c4bac7949cd5b80d397042022836f49e051a09cc/src/gwt/acesupport/acemode/rmarkdown.js#L207-L220

Alternatively, we can try to use our existing auto-pairing code; it requires modes to set these:

https://github.com/rstudio/rstudio/blob/c4bac7949cd5b80d397042022836f49e051a09cc/src/gwt/acesupport/acemode/auto_brace_insert.js#L42-L57

but I'm not sure if we can cleanly update these based on the "current" mode for a multi-mode document like R Markdown.

**Comment by kevinushey** [comment]
Also, compare with Sweave:

https://github.com/rstudio/rstudio/blob/c4bac7949cd5b80d397042022836f49e051a09cc/src/gwt/acesupport/acemode/sweave.js#L58-L69

**Comment by ntluong95** [comment]
I think we can adapt this to at least several common languages, such as python @kevinushey
