### ISSUE TITLE
Can't start the version 2022.07.1+554 on Windows 10 with a german umlaut in my username

### ISSUE THREAD

**Issue by ObiWanLansi** [rstudio/rstudio#11717]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1+554, "Spotted Wakerobin" (7872775e, 2022-07-22) for Windows
    OS Version      : Windows 10
    R Version       : 

### Steps to reproduce the problem

Maybe create a example user `Harry Fürz`

### Describe the problem in detail

I cant start rstudio.

![RStudioProblem](https://user-images.githubusercontent.com/38795604/183293920-da91f685-7ba9-4d36-99c4-e488858092e0.png)

Recent Log:

```console
2022-08-07T13:48:49.003491Z [rsession-Jörg Lanser Lokal] ERROR system error 2 (Das System kann die angegebene Datei nicht finden); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::crash_handler::initialize(enum rstudio::core::crash_handler::ProgramMode) src/cpp/core/CrashHandler.cpp:322; LOGGED FROM: int __cdecl main(int,char *const []) C:\Users\jenkins\workspace\ide\open-source-pipeline\spotted-wakerobin\src\cpp\session\SessionMain.cpp:2007
```

**Comment by kevinushey** [comment]
Thanks for the bug report, but I wasn't able to reproduce. Can you provide any other details?

I did see some warning messages on startup:

```
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/J�rg Lanser Lokal/Documents": The system cannot find the path specified
```

Do you have something like `options(warn = 1)` in your user `.Rprofile` or something similar?

It seems like `path.expand("~")` is giving a path in the wrong encoding:

```
> path.expand("~")
[1] "C:/Users/J\xf6rg Lanser Lokal/Documents"
```

The above code works as expected with RGui, so this seems like an RStudio issue.

**Comment by kevinushey** [comment]
## RGui

```
> path
[1] "C:\\Users\\Jörg Lanser Lokal\\Documents"
> Encoding(path)
[1] "unknown"
```

## RStudio

```
> path <- path.expand("~")
> Encoding(path)
[1] "unknown"
> Encoding(path) <- "latin1"
> path
[1] "C:/Users/Jörg Lanser Lokal/Documents"
```

For some reason, the path returned by `path.expand()` in RStudio is `latin1`-encoded, but is not marked as such.

**Comment by ObiWanLansi** [comment]
I started RGui standalone and see a R version 3.3.2 (2016-10-31). 
Can this old R version cause the problem? 
But that would be strange because the RDesktop version from last year still worked.

**Comment by kevinushey** [comment]
Hmm, maybe you're right. I get the crash right away if I try to launch with R 3.6.3. I see the same error in that case.

> 2022-08-08T19:26:57.982073Z [rsession-Jörg Lanser Lokal] ERROR system error 2 (The system cannot find the file specified); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::crash_handler::initialize(enum rstudio::core::crash_handler::ProgramMode) src/cpp/core/CrashHandler.cpp:322; LOGGED FROM: int __cdecl main(int,char *const []) C:\Users\jenkins\workspace\ide\open-source-pipeline\spotted-wakerobin\src\cpp\session\SessionMain.cpp:2057

**Comment by kevinushey** [comment]
This works with RStudio 2022.02.3, so appears to be a regression.

**Comment by ObiWanLansi** [comment]
So, i updated to R 4.2.1 and the first error is away, but a new one is there:

![grafik](https://user-images.githubusercontent.com/38795604/183499462-1d0c56a8-0f2d-4965-8f9b-d8628da89d0f.png)

**Comment by ObiWanLansi** [comment]
After clicking `Ok`:

```
Error in nchar(homeDir) : invalid multibyte string, element 1
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/J�rg Lanser/Documents": Das System kann den angegebenen Pfad nicht finden
```

**Comment by kevinushey** [comment]
Let's track that in a separate issue; we'll use this issue to focus on the inability to launch RStudio on Windows with older versions of R. I've filed that here: https://github.com/rstudio/rstudio/issues/11721

**Comment by mikebessuille** [comment]
Added the Automation label so that we fix this, and automate the test so that it doesn't happen again.

**Comment by jgutman** [comment]
Depending on where I install RStudio to (i.e. installed within the user's directory or to C:/Program Files as the default) I get a different error message in older versions of RStudio (2022.02.3)

**Comment by jeffvroom** [comment]
Thanks to Kevin for pointing out this regression I introduced where errors initializing crashpad cause the rsession to exit. My apologies, I'll get that fixed ASAP.

Is it perhaps a workaround to disable crashpad in /etc/rstudio/crash-handler.conf or ~/.r/crash-handler.conf by setting:

`crash-handling-enabled=0`

**Comment by jmcphers** [comment]
Reported on community forum here: https://community.rstudio.com/t/need-help-on-downloading-the-rstudio/145104

**Comment by jgutman** [comment]
Those should be addressed in the very latest dailies if we want to let them know. We're also backpacking a fix to the next SW patch

**Comment by jonvanausdeln** [comment]
Verified 2022.11.0-173
Windows, Ubuntu

Tested with several username variations.

**Comment by helge-baumann** [comment]
I don't know if it's still relevant, but I still can't use RStudio 2022.07.2-576 with German umlauts in my username. Upon start:

```
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Helge-Emmler/OneDrive - Hans-B�ckler-Stiftung/Dokumente": Das System kann den angegebenen Pfad nicht finden
```
When entering `library(pacman)`:

`Error in nchar(homeDir) : invalid multibyte string, element 1
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Helge-Emmler/OneDrive - Hans-B�ckler-Stiftung/Dokumente": Das System kann den angegebenen Pfad nicht finden`

I am using R 4.2.1 (no problem in base Rgui.exe) and the last RStudio version working is RStudio-2021.09.3-396.

**Comment by mikebessuille** [comment]
@helge-baumann this has been fixed in 2022.11; can you try a daily build and see if it's working there?
https://dailies.rstudio.com/

**Comment by helge-baumann** [comment]
> @helge-baumann this has been fixed in 2022.11; can you try a daily build and see if it's working there? https://dailies.rstudio.com/

I'm very sorry, I wasn't aware of daily builds. 

Yes, that seems to work. Many thanks and sorry for the trouble.

**Comment by kevinushey** [comment]
@helge-baumann Thanks for taking the time to confirm! No worries, the daily builds aren't normally advertised by us except when when we might request users test recently-introduced fixes.

**Comment by Frynsolesen** [comment]
Yeess!!! Thank's mikebessuille... Just what I actually needed. Had a similar issue from a devtools-GitHub download... You're a star.
