### ISSUE TITLE
(R 4.2) force UTF-8 output from Python when querying paths

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11725]
Otherwise, users might see errors like:

```
Error in file.exists(pythonPath) :
  file name conversion problem -- name too long?
```

In here: https://github.com/rstudio/rstudio/blob/ffefe5dee28e8090039e725339f1f58db3334b33/src/cpp/session/modules/SessionPythonEnvironments.R#L95-L110

I believe we can add `-Xutf8` to the argument list, and then mark the encoding on `stdout` as UTF-8.

**Comment by jonvanausdeln** [comment]
I'm not sure how this error would manifest.  Can I get some more details on how to reproduce the error? I'm not entirely sure how to test this fix.

**Comment by jgutman** [comment]
@kevinushey -- looking for a reprex for testing

**Comment by kevinushey** [comment]
To reproduce:

1. Select a Windows user account with non-ASCII characters in the username -- for example, I used Crème Brûlée.
2. Install Python from https://www.python.org/downloads/, and select a user install,
3. Try running `.rs.python.findWindowsPython()`. Or, you might just see the error on startup.

Note: depending on how Python is installed on the system, you might also see issues on startup relating to RStudio trying to use an inaccessible version of Python through `py`.

With these steps, I see on startup:

```
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Cr�me Br�l�e/Documents": The system cannot find the path specified
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Cr�me Br�l�e/Documents": The system cannot find the path specified
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Cr�me Br�l�e/Documents": The system cannot find the path specified
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Cr�me Br�l�e/Documents": The system cannot find the path specified
```

And then later:

```
> .rs.python.findWindowsPython()
[1] "C:\\Users\\Cr\xe8me Br\xfbl\xe9e\\AppData\\Local\\Programs\\Python\\Python310\\python.exe"
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Cr�me Br�l�e/Documents": The system cannot find the path specified
```

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2022.12.0-daily+284, Windows 11.

Tested several users with non-ascii usernames. Paths were correct as expected. 
I also verified a build before the fix showed the issue.
