### ISSUE TITLE
(R 4.2) path.expand("~") resolves incorrectly for non-ASCII usernames on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11721]
### System details

    RStudio Edition : 2022.07.1+554
    RStudio Version : Desktop [Open Source]
    OS Version      : Windows 10 x64 (build 25174)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

Create a user account containing non-ASCII (latin1) characters; e.g. Fürz. Then, try to launch RStudio with R 4.2.x.

### Describe the problem in detail

RStudio prints a bunch of warnings, e.g.

> In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/F�rz/Documents": The system cannot find the path specified

In addition, `path.expand("~")` gives:

```
> path.expand("~")
[1] "C:/Users/F\xfcrz/Documents"
```

which is evidently latin1-encoded, but not marked as such.

```
> path <- path.expand("~")
> Encoding(path)
[1] "unknown"
> Encoding(path) <- "latin1"
> path
[1] "C:/Users/Fürz/Documents"
```

### Describe the behavior you expected

`path.expand("~")` should produce a correctly-encoded path.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 25174)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1   
```

</details>

**Comment by jgutman** [comment]
Assigning @kevinushey because you seem to already have a PR in progress, but if you want someone else to take over that's fine too

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-173
Windows 11

Tested with several different usernames containing special characters
