### ISSUE TITLE
Double click to toggle TRUE/FALSE

### ISSUE THREAD

**Issue by ssobelvw** [rstudio/rstudio#11737]
In code, whenever there is a TRUE, it would really be nice to be able to double-click on the TRUE to toggle it to FALSE and vice-versa, since often I am experimenting with a TRUE/FALSE toggle option. Double clicking would avoid deleting TRUE and typing out FALSE using the keyboard. For those that suggest that using T and F as abbreviations to saving typing and re-typing, I would rather have this spelled out in my code.

Thanks!

**Comment by ronblum** [comment]
@ssobelvw Thank you for the interesting suggestion! I'll mark it for review as part of our ongoing development of RStudio.

Comparison points, of toggling between booleans in other software:
* [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=silesky.toggle-boolean)
* [Vim plugins](https://vi.stackexchange.com/questions/5213/swap-values-true-and-false-via-ctrla-ctrlx)

**Comment by ssobelvw** [comment]
I like the other options to toggle other booleans as well.
