### ISSUE TITLE
Right click to get dimensions & column names of a data.frame

### ISSUE THREAD

**Issue by ssobelvw** [rstudio/rstudio#11738]
Hello, request for a cool feature:

- In RStudio can you introduce the ability the right-click on a data.frame to then see a few menu options? For example, an option to see the dimensions of a data.frame and column names. For a vector, the analogous feature would be to see the length and a few values, like head() and/or tail().

Then have the option to copy this information to the clipboard to paste back into code. Getting column names in this way would make it much easier rather than typing names() in code, and copying from the output in the console, back into the code, then possibly formatting/reformatting to get rid of or add quotes, to then have a list of column names.

**Comment by ronblum** [comment]
@ssobelvw Thank you for the enhancement request! We have a future project to refactor the Data Viewer. This is probably outside the scope of the project, but I'll tag it so that we consider your suggestion as we work towards it.

**Comment by ssobelvw** [comment]
Cool! I was not thinking this needs to involve the Data View (I assume the result of View() ?) because this would add a step. So, would prefer a right-click approach when you hover over a data.frame object. But now that you mention the Data Viewer, it would be nice to be able to copy the whole contents (sometimes if there are too many rows or columns, then Ctrl+A does not capture the whole contents), and then be able to paste into a spreadsheet nicely would be a great and much needed enhancement! (when you ctrl+a, copy, then paste into Excel, it begins in formatting from the R Viewer that you then have to clean up every time. Thanks

**Comment by ronblum** [comment]
@ssobelvw Oh, I'm sorry! I immediately jumped to the conclusion that you meant in the data viewer. Do you mean in the environment pane?

As for copying the contents from the data viewer, do you mean something like the request in issue #4574?

**Comment by ssobelvw** [comment]
Hi Ron, actually I mean being able to right-click on a data.frame object in the source pane... like this:

sample code you are working on....:

model <- lm(Petal.Width + Sepal.Length, data = iris)

... then if you hover over "iris" in this code, you can then see the names() of iris and be able to copy the names to the clipboard for pasting into code.

As far as suggestion #4574, I like those ideas, and I can think of more custom type buttons that could be added to RStudio (like Excel's Quick Access Toolbar) that would do certain predefined actions... but my issue is that I am often working in AWS and contents written to the clipboard using code such as clipr do not actually get into my clipboard, perhaps since I'm using Linux or perhaps because I'm using AWS. So, I have to manually copy the Viewer contents using ctrl+a, ctrl+c then go to Excel, then ctrl+v, then the contents get pasted into Excel with formatting that I have to clean up everytime. Usually I just need some small bit of data summary, nothing large. Writing the contents to a csv file requires code every time, then I need to go to some file explorer, then copy the csv file to my local computer, then open it up into Excel... i.e. a lot more cumbersome steps than simply copying & pasting from the Viewer.
