### ISSUE TITLE
windows - open project in new session issue (electron)

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#11730]
New project from Git - Windows - Elsbeth Geranium - Electron

I notice that when Open Project in new session is unchecked, it correctly opens the project (testing with cloning https://github.com/tidyverse/dplyr into ~; opens as `~/dplyr`). However, when I check Open Project in new session, it doesn't actually open the project. It just opens a new session with no active project. This might be a totally separate issue?

_Originally posted by @jgutman in https://github.com/rstudio/rstudio/issues/11089#issuecomment-1190461072_

**Comment by jgutman** [comment]
Can no longer reproduce -- appears to have been fixed?

**Comment by jonvanausdeln** [comment]
I also just verified on 2022.11.0-daily+244.  Projects open correctly in a new session.
