### ISSUE TITLE
Rstudio executes custom search function instead of base::search when using devtools::load_all

### ISSUE THREAD

**Issue by oganm** [rstudio/rstudio#11747]
### System details

    RStudio Edition : Desktop and server
    RStudio Version : 2022.7.1.554 (desktop),  1.4.1717 (server)
    OS Version      : Ubuntu 20.04.2 (desktop), Centos Linux 7 (server)
    R Version       : 4.1.1 (desktop), 3.6.0 (server)

### Steps to reproduce the problem

- Install `devtools` package
- Create a project with [this](https://github.com/oganm/searchIssue) repository which includes a package with a function named `search`
- Load the package using `devtools::load_all()`

### Describe the problem in detail

When using `devtools::load_all` from Rstudio, if a function named `search` exists within the package that is being loaded or in the global environment, Rstudio will execute that version of `search`, presumably instead of `base::search`, twice.

This issue was previously discussed under https://github.com/r-lib/devtools/issues/2458.

### Describe the behavior you expected

Rstudio should use base::search as intended instead of executing custom function

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@oganm Thank you for raising this, and referencing the original `r-lib` discussion! We'll review this as part of our ongoing development of RStudio.

**Comment by kevinushey** [comment]
Probably related to this bit of code: https://github.com/rstudio/rstudio/blob/e9a353085eb42249140c1014aeeb7c4a7a73dfaf/src/cpp/session/modules/SessionRAddins.cpp#L57-L60

There's a variety of places where we try to invoke functions without explicitly qualifying where we expect to find that function that could suffer a similar fate. A similar sample:

https://github.com/rstudio/rstudio/blob/e9a353085eb42249140c1014aeeb7c4a7a73dfaf/src/cpp/session/modules/SessionPlots.cpp#L385-L392

https://github.com/rstudio/rstudio/blob/e9a353085eb42249140c1014aeeb7c4a7a73dfaf/src/cpp/session/SessionModuleContext.cpp#L2386-L2389

In general, I think we should be namespace-qualifying all of these calls we're making.
