### ISSUE TITLE
autocomplete priority within a pipe

### ISSUE THREAD

**Issue by antonaltmannhome** [rstudio/rstudio#11749]
I think the order of suggestions from the autocomplete when piping is strange. I've attached an example:

![rstudio-autocomplete](https://user-images.githubusercontent.com/58005258/184340434-f280a97e-4f98-4f73-8bea-19fc7cc7dc73.png)

I've created a tibble, called myTibble, with a column called 'shotsOnTarget' in it. If I type

myTibble %>% select(sho

and wait for suggestions, surely the overwhelmingly likely thing I want is 'shotsOnTarget'. But instead RStudio suggests a set of completely unrelated global functions or objects. I have to press the Down key many times to get 'shotsOnTarget' or press the Up key to see the bottom half of the list. I've posted this in the RStudio community and been told of a solution, which is to hit Tab as soon as I open the bracket after 'select' and that triggers a search within myTibble. I don't think this is something a user would necessarily think of doing though. Even if it is, I still think the default behaviour in the situation where you haven't remembered to hit Tab is just not correct.

**Comment by ronblum** [comment]
@antonaltmannhome Thank you for raising this! I can reproduce this with a simple example, in which the column `x` would be the most obvious choice when trying to autocomplete the letter `x`.

```
as_tibble(x = 1) %>% tibble(x)
```

<img width="509" alt="tibble" src="https://user-images.githubusercontent.com/31009952/184632476-e5a86e5d-3da9-471c-b6e8-22121e860d2d.png">

**Comment by antonaltmann** [comment]
That's a great simple example! Thanks for adding this to the list

**Comment by antonaltmannhome** [comment]
Thanks for addressing this Romain, this will save R users from a lot of key presses going forwards!

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+270 on MacOS 13.2. 

And thank you @romainfrancois! My example was clever, not smart—pithy but useless.
