### ISSUE TITLE
Backport commit  to Spotted Wakerobin 2022.07.2

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#11743]
Backport commit https://github.com/rstudio/rstudio/commit/5b327c2b09cee2fe3573354982d77fcff7bcaf71 to Spotted Wakerobin 2022.07.2

**Note: This issue is to record the need to backport the linked issue only. Please add comments or discussion relating to the original issue onto it directly.**

**Comment by ronblum** [comment]
Verified on MacOS 13 in
- RStudio-2022.07.2+565 Qt
- RStudio-2022.07.2+570 Electron

Verification consisted of checking that autocompletion for a cross-reference, spec. for a figure.
