### ISSUE TITLE
Quarto documents do not have UI gear for changing chunk options

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#11745]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      :  Mac OS X 12_5_0 on M1 Pro
    R Version       : 4.2

### Steps to reproduce the problem

.rmd have a gear icon on each code chunk, letting users modify chunk options:

<img width="689" alt="Screen Shot 2022-08-11 at 10 17 58 AM" src="https://user-images.githubusercontent.com/29187501/184168872-c9049c61-d82d-42cb-8cd7-0752fd7052eb.png">

Create a .rmd:

````
---
output: html_document
date: "`r Sys.Date()`"
---

```{r}
plot(mtcars)
```

```{r}
plot(mtcars)
```
````

Then change name of document from `file.rmd` to `file.qmd`:

Create a new .qmd or convert a .rmd -> .qmd, the gear UI element present in .Rmd is missing from each code chunk in .Qmd.

![image](https://user-images.githubusercontent.com/29187501/184168837-ba4dab5b-cd11-4246-bca8-7ef5b82b7a15.png)

### Describe the problem in detail

Quarto documents have a "regression" in capability, namely that there is no longer an ability to use the GUI element chunk by chunk to modify chunk options.

### Describe the behavior you expected

Presence of a gear UI element on each chunk, next to the run chunk UI element.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Part of the challenge here is that the "Modify chunk options" dialog hasn't been updated yet to be compatible with the newer YAML chunk option style, so the existing dialog does something that's probably not in line with user expectations -- that is, it just modifies the chunk header.

**Comment by jthomasmock** [comment]
That makes sense as a "regression" - (not really a regression as it's expected).

There is additional work needed to write the new syntax. Thanks!

**Comment by ronblum** [comment]
How about, an enhancement request to make .qmd on par with .rmd?

**Comment by ntluong95** [comment]
Quarto also doesn't have option to create new code chunk as in Rmarkdown. When choose the engine either R or Python, when click on the new code chunk, you cannot select the language

**Comment by steveharoz** [comment]
Since it's being marked as stale, I'll note that it's still an issue.

**Comment by Physikuss** [comment]
In can confirm. I'm on the recent 2023.06.1 Build 524. The gear appears when I load source-View. I disappears as soon as I make a change to chunk. In visual-View the gear is not shown at all.

**Comment by tylerotto** [comment]
If the "modify chunk options" gear icon disappears in the source tab, I've found luck by switching to the visual tab and back to the source tab to get the icon back temporarily. It's better than nothing currently.

**Comment by gtritchie** [comment]
Note to self, consider multiline YAML syntax when implementing this: https://github.com/rstudio/rstudio/issues/11199

**Comment by kevinushey** [comment]
Verified working on macOS with RStudio 2024.11.0 Build 319.

<img width="711" alt="Screenshot 2024-10-24 at 3 25 17 PM" src="https://github.com/user-attachments/assets/e01f7320-c1be-4370-8732-feffe56892e6">
