### ISSUE TITLE
Fuzzy file-finder should index non-function roxygen2 blocks

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#11757]
It's possible to document things other than functions with roxygen2. In particular you can document datasetst and packages with special syntax:

```R
#' This is my dataset
"mydataset"

#' This is my package
"_PACKAGE"
```

It would be cool if the fff could also index these so I could easily jump to them.

As a stretch goal, we're also starting to write topics that aren't attached to any specific object but are either used to explain details of an input used by many different functions or as a kind of FAQ. These can be identified by the presence of a `@name`:

```R
#' @name args_error_context
NULL
```

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0 Build 178
Windows 11, Ubuntu 22.04

Tested several statements in multiple files
