### ISSUE TITLE
Move builds from Fedora 36 to Rocky Linux 9

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#11758]
We currently use Fedora 36 as a platform for our Red Hat Enterprise Linux 9 - compatible builds. This was intended to be temporary. See here:

https://github.com/rstudio/rstudio/issues/11140

As of a month ago, Rocky Linux 9 is now available:

https://rockylinux.org/news/rocky-linux-9-0-ga-release/

We should switch to Rocky Linux 9 because it is more stable and more similar to RHEL 9 than Fedora 36. Other teams at RStudio are also moving from Fedora 36 to Rocky Linux 9 as a build platform for RHEL 9 compatible binaries. See: https://github.com/rstudio/launcher/commit/5e61f02710809142c007889692fd5a01817292da

**Comment by ronblum** [comment]
Ref #11477 and #11478 so that they're aware of this.

**Comment by gtritchie** [comment]
Closing. This was done via https://github.com/rstudio/rstudio/commit/6c7b1b8cd11491673cf1a626fd154ebd23780cff.
