### ISSUE TITLE
Print GUI commands run in the terminal

### ISSUE THREAD

**Issue by theamarks** [rstudio/rstudio#11750]
I am starting to integrate the command line into my workflow for git and creating files. Using the terminal felt intimidating for a while and often felt disconnected from how I used Rstudio. Once learning it literally underpins every mouse click in Rstudio, I wanted to see those commands print out into the terminal as a way of translating my GUI workflow into terminal commands. I think this would be a great enhancement for learning and teaching purposes by adding a bit of transparency to what is under the hood. Could be an option to turn on or off. 

Thanks! And thanks for the super clear guidelines for submitting this :)

**Comment by ronblum** [comment]
@theamarks Thank you for the interesting suggestion! We'll review it as we continue to develop RStudio.
