### ISSUE TITLE
Can not open File in Rstudio!

### ISSUE THREAD

**Issue by msgoussi** [rstudio/rstudio#11759]
### System details

    RStudio Edition : 
    RStudio Version : 2022.07.1 
    OS Version      : Windows 21H2
    R Version       :  4.2.1

### Steps to reproduce the problem
I have two files, if i open file A, and i run, and if i want to open file B, i get an error 

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![image](https://user-images.githubusercontent.com/18138496/184793017-e84702fd-27bf-44ba-9b7a-c3aa84bc97ef.png)

**Comment by kevinushey** [comment]
What are the files called?

**Comment by msgoussi** [comment]
my personal files with r extension

**Comment by kevinushey** [comment]
Thanks; I wanted to rule out whether this could've been caused by the use of a reserved Windows file name (e.g. https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file).

https://stackoverflow.com/questions/41371010/rstudio-error-message-the-device-does-not-recognize-the-command suggests that this error can occur if the file is locked, e.g. because a different program has the same file open. Unfortunately, without more information it's hard for us to know the underlying cause.

**Comment by msgoussi** [comment]
non of above is sutitable for my case, becuase i did not face this problem with the previous version of RStudio.
I wish i can replicate the error.

**Comment by msgoussi** [comment]
I find out what causes the error
i run 
```
Sys.setlocale(locale = "en_US")
```
in file A, i could not open File if i click on it, as it is shown in the attached picture.

![image](https://user-images.githubusercontent.com/18138496/185038376-39b257bb-f765-4938-b001-19011584ac44.png)

**Comment by kevinushey** [comment]
As the warning suggests in the console, you should avoid changing the locale -- does sticking with the default UTF-8 locale suffice?

**Comment by msgoussi** [comment]
i found out that if i use Sys.setlocale(category = "LC_ALL", locale = "English_United States.1252"), it solves the problem.

**Comment by kevinushey** [comment]
Great, glad to hear you found a solution!
