### ISSUE TITLE
Receiving pre-push hook error in RStudio on M2 Mac (Apple silicon)

### ISSUE THREAD

**Issue by jamesrco** [rstudio/rstudio#11755]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      : Mac OS 12.5 (ARM)
    R Version       : R version 4.2.1 (2022-06-23)

### Steps to reproduce the problem

Error when using the RStudio GUI tool (push/pull buttons on "Git" tab) to push a new commit to GitHub from a git-lfs enabled repository. This error prevents the changes on the latest commit from being pushed.

### Describe the problem in detail

I got a new Macbook Air M2 (Apple silicon) and I am trying to get some repositories working in RStudio. I installed R and RStudio, then installed git-lfs using homebrew. I then cloned one of my repos from Github. This repo has never given me any trouble, but then again I've been working on my old Mac MBP Retina with Intel silicon.

I am now receiving the following error when using Git within RStudio in a git-lfs enabled repo:

`This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.`

**Note that I can push and pull with no error (including all files being tracked with git-lfs)** when using Git from the command line within the same repo. So it appears to be something having to do with RStudio and git-lfs on an Apple silicon Mac. Importantly, on the new M1/M2 Macs, git-lfs installs to `/opt/homebrew/bin/git-lfs` and not `/usr/local/bin/git-lfs` as previously on Intel silicon.

### Describe the behavior you expected

I expected to be able to push commits as normal. This repo did not give me any trouble using same versions of R and RStudio on my older Intel-based Mac. 

Note that I [opened an issue](https://github.com/git-lfs/git-lfs/issues/5087) to report this problem on the git-lfs GitHub repo. This was the reply there:

> Hey,
> 
> This is likely because the `PATH` value set by RStudio isn't correct. I don't use that tool, so I'm not sure how you'd configure it, but you'd want to adjust RStudio to include `/opt/homebrew/bin` in the `PATH` that's used.
> 
> Alternately, you can change your `~/.gitconfig` to use an absolute path for the `filter.lfs.process`, `filter.lfs.smudge`, and `filter.lfs.clean` variables.

I am happy to make these changes, but I kind of expected RStudio to set the correct parameters during install. I have never had to modify these parameters specifically for RStudio before.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
My recommendation would be to ensure that `/opt/homebrew/bin` is placed on the PATH for R / RStudio with something like:

```
PATH = /opt/homebrew/bin:$PATH
```

in e.g. `~/.Renviron`.

Note that RStudio (and other GUI applications) will not see any environment variables changes normally made in e.g. shells, so it's necessary to set these in another fashion so they can be visible to RStudio.

**Comment by jamesrco** [comment]
Wanted to provide an update: I did as @kevinushey suggested and added `/opt/homebrew/bin` to `~/.Renviron`

This did not fix the problem. I am still receiving the same error, even after restarting my computer, starting with a new R session etc. Where does RStudio read the location from?

**Comment by kevinushey** [comment]
If you look within Tools -> Global Options... -> Git / SVN, you should see a place where you can configure the Git executable used:

![image](https://user-images.githubusercontent.com/1976582/185503969-4d1b0a30-e7a4-4963-9b45-7bef8363406e.png)

Does setting that to `/opt/homebrew/bin/git` help?

**Comment by jamesrco** [comment]
In the Mac version, that field is not directly editable (for what it's worth, there is no value currently set for it). Clicking the "Browse ..." button allows me to browse my computer via the directory GUI, but there is no way to get to the `/opt/homebrew/bin/git` Linux path.
