### ISSUE TITLE
Error normalizing paths for pandoc/rmarkdown

### ISSUE THREAD

**Issue by ljrk0** [rstudio/rstudio#11754]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1
    OS Version      : Windows 10
    R Version       :  4.1.1

### Steps to reproduce the problem

1. Create a user with a non-ascii user name, e.g., containing `ß`.
2. Create R project
3. Knit the project and export as PDF/DOCX/...

### Describe the problem in detail

Rmarkdown fails to run pandoc successfully, as pandoc can't find the Lua filters due to the path being mangled up.

Log:

```
output file: foo.knit.md

"C:/Program Files/RStudio/bin/quarto/bin/tools/pandoc" +RTS -K512m -RTS foo.knit.md --to docx --from markdown+autolink_bare_uris+tex_math_single_backslash --output foo.docx --lua-filter "C:\Users\Non ASCII ß\Documents\R\win-library\4.1\rmarkdown\rmarkdown\lua\pagebreak.lua" --highlight-style tango
Error running filter: C:\Users\Non ASCII ÃŸ\Documents\R\win-library\4.1\rmarkdown\rmarkdown\lua\pagebreak.lua: No such file or directory
Fehler: pandoc document conversion failed with error 83
```

This happens when a UTF-8 encoded string is interpreted as Windows-1252 and then incorrectly converted to UTF-8:

```
$ cat utf8-file.txt
Non ASCII ß
$ iconv -f windows-1252 -t utf-8 utf8-file.txt
Non ASCII ÃŸ
```

### Describe the behavior you expected

Since the specified filter exists at the location (given the correct encoding) knitting and exporting succeeds.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

FWIW, this looks similar to bug https://github.com/rstudio/rstudio/issues/9566 but not the same(?)

**Comment by ronblum** [comment]
@ljrk0 Thank you for raising this! I'll chain this to issue #11721 which has a similar problem.

**Comment by kevinushey** [comment]
@ljrk0: do you also see this issue with R 4.2.x? The latest releases of R use a UTF-8 codepage by default, so that might alleviate the issue here.

**Comment by ljrk0** [comment]
@kevinushey Indeed this fixed the issue, thanks and mea culpa for raising something that's already fixed in R.  I hope the bug report is still useful for R Studio normalization code though!

On 15 August 2022 18:25:01 UTC, Kevin Ushey ***@***.***> wrote:
***@***.***: do you also see this issue with R 4.2.x? The latest releases of R use a UTF-8 codepage by default, so that might alleviate the issue here.
>

**Comment by kevinushey** [comment]
Great! For what it's worth, this is still probably a bug in RStudio but we're fortunate that a change to using a UTF-8 codepage in R 4.2.x will help ensure a large class of these issues disappear.
