### ISSUE TITLE
Rebrand IDE to change company references to Posit (RStudio IDE is NOT changing names!)

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#11751]
Rebrand the IDE per https://rstudiopbc.atlassian.net/wiki/spaces/ENG/pages/56263099 to change references to RStudio as a company to Posit.  The RStudio IDE will keep its current name and branding.   This should be minimal for the IDE, but the UI, output, error messages, documentation, etc should be reviewed for any place where RStudio should change to Posit (e.g., any reference to the company, not the product itself).

**Comment by waynelapierre** [comment]
how about the package rstudioapi?

**Comment by ronblum** [comment]
@waynelapierre This is specific to changes to the RStudio IDE. Any potential changes to `rstduioapi` would be addressed in its repository at https://github.com/rstudio/rstudioapi.

**Comment by mikebessuille** [comment]
@waynelapierre rstudioapi will not change names.

**Comment by jmcphers** [comment]
No, it will not. The RStudio IDE will still be called "RStudio".

**Comment by ronblum** [comment]
Verified in RStudio Server 2022.11.0-daily+202 on Ubuntu 20.04 via Chrome on MacOS 13.

RStudio Server (open source)
1) About dialog reflect company name of "Posit Software, PBC" or "Posit Software," but product name is still "RStudio Server."

![Image](https://user-images.githubusercontent.com/31009952/191757597-916792dd-6e6e-4e14-b48a-30eeee8129fe.png)

2) Browsers tabs uses "RStudio Server" both in and out of a project.

![Image](https://user-images.githubusercontent.com/31009952/191760225-235a216e-62c9-4ca2-abc8-69d33c2cb89f.png)
![Image](https://user-images.githubusercontent.com/31009952/191760226-2fe88f63-a11f-49b3-841c-4020c0982b94.png)

3) `RStudio.Version()`
```
> RStudio.Version()
$citation

To cite RStudio in publications use:

  Posit team (2022). RStudio: Integrated Development Environment for R.
  Posit Software, PBC, Boston, MA. URL http://www.posit.co/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{Posit team}},
    organization = {Posit Software, PBC},
    address = {Boston, MA},
    year = {2022},
    url = {http://www.posit.co/},
  }


$mode
[1] "server"

$version
[1] ‘2022.11.0.202’

$long_version
[1] "2022.11.0-daily+202"

$release_name
[1] "Elsbeth Geranium"
```

4) Tutorial installation of `shiny` and `learner` reflects the product name "RStudio."

![Image](https://user-images.githubusercontent.com/31009952/191758870-2aa2d557-dcae-45a5-b635-5e1075997c1a.png)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.11.0-daily+2022 on MacOS 13.

RStudio Desktop (open source)
1) About dialog reflect company name of "Posit Software, PBC" or "Posit Software," but product name is still "RStudio."

![Image](https://user-images.githubusercontent.com/31009952/191761856-489ac1a5-2a2e-4a06-985a-0c71cdd0f1fd.png)

2) Browsers tabs uses "RStudio" both in and out of a project.

![Image](https://user-images.githubusercontent.com/31009952/191761902-8653a819-0801-4897-8f88-6135207c1dc8.png)
![Image](https://user-images.githubusercontent.com/31009952/191761903-484bffe3-7c72-4364-89e9-0965bf518cb9.png)


3) `RStudio.Version()`
```
> RStudio.Version()
$citation

To cite RStudio in publications use:

  Posit team (2022). RStudio: Integrated Development Environment for R. Posit
  Software, PBC, Boston, MA. URL http://www.posit.co/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{Posit team}},
    organization = {Posit Software, PBC},
    address = {Boston, MA},
    year = {2022},
    url = {http://www.posit.co/},
  }


$mode
[1] "desktop"

$version
[1] ‘2022.11.0.202’

$long_version
[1] "2022.11.0-daily+202"

$release_name
[1] "Elsbeth Geranium"
```

**Comment by ronblum** [comment]
Verified in RStudio Desktop Pro 2022.11.0-daily+2022 on MacOS 13.

RStudio Desktop Pro
1) About dialog reflect company name of "Posit Software, PBC" or "Posit Software," but product name is still “RStudio Desktop Pro."

![Image](https://user-images.githubusercontent.com/31009952/191762909-38c86628-95b9-4b33-a320-f6176516ef1f.png)

2) Browsers tabs uses “RStudio Pro" both in and out of a project.

![Image](https://user-images.githubusercontent.com/31009952/191762951-18fcaed5-f398-48bb-ab22-b681d5ed1247.png)
![Image](https://user-images.githubusercontent.com/31009952/191762950-212e7f5c-b0c0-4e67-8d84-5029b968089a.png)

3) `RStudio.Version()`
```
> RStudio.Version()
$citation

To cite RStudio in publications use:

  Posit team (2022). RStudio: Integrated Development Environment for R.
  Posit Software, PBC, Boston, MA. URL http://www.posit.co/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{Posit team}},
    organization = {Posit Software, PBC},
    address = {Boston, MA},
    year = {2022},
    url = {http://www.posit.co/},
  }


$mode
[1] "desktop"

$edition
[1] "Professional"

$version
[1] ‘2022.11.0.199.1’

$long_version
[1] "2022.11.0-daily+199.pro1"

$release_name
[1] "Elsbeth Geranium"
```

4) License management dialog.

![Image](https://user-images.githubusercontent.com/31009952/191763112-1c35ed76-51bc-43fc-8323-f77ab464db92.png)

**Comment by ronblum** [comment]
Note: See #12015 for an email address change in the open source components dialog.
