### ISSUE TITLE
Improve multi-tasking with support for multiple interactive user-managed consoles

### ISSUE THREAD

**Issue by combiz** [rstudio/rstudio#11764]
I frequently need to perform multiple analyses simultaneously and interactively, each with its own environment.  The 'Jobs' features added in v1.2 are great but don't provide interactivity.

I can easily add multiple self-managed R consoles in VSCode using self-managed tmux sessions.  These can be switched between seamlessly with `.vsc.attach()`.  As I frequently work with long-running functions, this allows me to multi-task effectively.  A similar level of support for multiple, user-managed R consoles in RStudio would be very welcome!

**Comment by ronblum** [comment]
@combiz Thank you for the suggestion! I'll mark it for review as part of our ongoing development of RStudio.

**Comment by kevinushey** [comment]
I realize it doesn't match the workflow you suggest here, but it's also possible to open separate instances of RStudio, with each instance associated with its own project / R session. See, for example, File -> Open Project in New Session.

You might already be aware of the above, but just in case I wanted to offer that as an existing solution.

**Comment by combiz** [comment]
Thanks @kevinushey, yes that works nicely for local work.  I should probably specify that my work is generally on remote instances in the cloud.  I've used workarounds before to allow interactive multi-tasking with RStudio Server (e.g. rocker/rstudio Docker images with port forward mapping to multiple unique ports), but the self-managed tmux sessions in VSCode are very convenient.

**Comment by jondo** [comment]
Please reopen this issue.
I am used to easily open new console tabs from Spyder, e.g. to run code variants in parallel. This would also be very useful here – much faster and with less window clutter than with parallel GUI sessions.
