### ISSUE TITLE
RStudio / Quarto not rendering PDF or HTML when space in filename

### ISSUE THREAD

**Issue by quinten-goens** [rstudio/rstudio#11779]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.2 Build 485
    OS Version      :  Windows 10
    R Version       :  R-4.2.1

### Steps to reproduce the problem
Make a Quarto file (.qmd) with a space in the filename. E.g. use the following content for the file: 

```
---
title: "Quarto Demo"
author: "Test"
date: "2022-5-24"
---
```

Try to render the file by clicking the ''render'' button. 

### Describe the problem in detail
The rendering is halted. The job in cancelled and returns: 
```
'C:/Program' is not recognized as an internal or external command, operable program or batch file.
```

### Describe the behavior you expected

That the file would render even with a space in the filename. The easy fix is to remove the space in the filename. But ideally spaces would not break the process or alternatively RStudio would give an appropriate message.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This seems like a Quarto bug to me, as RStudio is normally able to run other applications containing spaces in their paths without issue.

As a workaround, I think we can try using a short path name for Quarto on Windows, to avoid the issue with quarto components having spaces in their names.

**Comment by jgutman** [comment]
Closing in favor of #11804
