### ISSUE TITLE
Python: indentation error when `re.sub()` with parenthesis in pattern

### ISSUE THREAD

**Issue by eac-upenn** [rstudio/rstudio#11772]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      : Windows 10 Home 21H2
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

### Steps to reproduce the problem

Python script:

```
import re

for i in range(5):
    print(i)
    print(re.sub(string='foo (bar)', pattern='\(', repl='baz_'))
```
### Describe the problem in detail
Result:
```
0
1
2
3
4
IndentationError: unexpected indent (<string>, line 1)
```

Note that if it's not in a loop (no indentation) works fine:

```
print(re.sub(string='foo (bar)', pattern='\(', repl='baz_'))
```
```
foo baz_bar)
```
### Describe the behavior you expected
Running the same code in a Jupyter notebook under Anaconda, we get the correct result:
```
0
foo baz_bar)
1
foo baz_bar)
2
foo baz_bar)
3
foo baz_bar)
4
foo baz_bar)
```

Also note that the paren is the problem. Without it:
```
for i in range(5):
    print(i)
    print(re.sub(string='foo (bar)', pattern='foo', repl='baz_'))
```
```
0
baz_ (bar)
1
baz_ (bar)
2
baz_ (bar)
3
baz_ (bar)
4
baz_ (bar)
```
Right parens have the same problem.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@eac-upenn Thank you for raising this! I can also reproduce it in RStudio Desktop 2022.11.0-daily+105 on MacOS 13. We'll review this as we continue to improve our support of Python in RStudio.

**Comment by eac-upenn** [comment]
Okay. It doesn't happen on my work machine.

  - R version 4.2.1 (2022-06-23 ucrt)
  - RStudio 2022.07.0 Build 548

How can I find out about what Python interpreter I'm using, in case that helps?

Correct output:

```
0
foo baz_bar)
1
foo baz_bar)
2
foo baz_bar)
3
foo baz_bar)
4
foo baz_bar)
```

**Comment by ronblum** [comment]
Can you try both of these?

- In the Console, when running R: `reticulate::py_exe()`
- In the Python script, or on the Console when `reticulate::repl_python()` is running: 
```
import sys
print(sys.executable)
```

**Comment by eac-upenn** [comment]
These are on the machine where it *does* work correctly:
```
> reticulate::py_exe()
[1] "C:/Anaconda3/python.exe"
```
```
>>> import sys
>>> print(sys.executable)
C:\Users\cohene\AppData\Local\Programs\RStudio\bin\rsession-utf8.exe
```

**Comment by kevinushey** [comment]
It seems like something about the escaped parenthesis in the string is causing issues for `reticulate`. I can reproduce something similar with:

```
>>> while False:
...   '\('
IndentationError: expected an indented block after 'while' statement on line 1 (<string>, line 1)
IndentationError: unexpected indent (<string>, line 1)
```

It may depend on what version of the `reticulate` package is installed; I'm seeing this with reticulate 1.25:

```
> packageVersion("reticulate")
[1] '1.25'
```

**Comment by eac-upenn** [comment]
> It may depend on what version of the `reticulate` package is installed; I'm seeing this with reticulate 1.25:
> 
> ```
> > packageVersion("reticulate")
> [1] '1.25'
> ```

That may be necessary, but not sufficient. The machine I'm on now, where your minimal example does run correctly, is also running reticulate 1.25.

**Comment by kevinushey** [comment]
I suspect the real fix here is using `\\(` instead of `\(`; I was able to reproduce similar behavior using IDLE (Python's builtin REPL). I filed an issue here: https://github.com/rstudio/reticulate/issues/1259

```
>>> import re
>>> for i in range(5):
...     print(i)
...     print(re.sub(string='foo (bar)', pattern='\\(', repl='baz_'))
... 
0
foo baz_bar)
1
foo baz_bar)
2
foo baz_bar)
3
foo baz_bar)
4
foo baz_bar)
```

**Comment by t-kalinowski** [comment]
I can reproduce in `reticulate::repl_python()`, but not in the python repl or the ipython repl. 
I think the difference is that R's parser treats `\` as an escape character in R literal strings, but Python's doesn't.
