### ISSUE TITLE
Daily build called to open a file opens in the user's home instead of file location

### ISSUE THREAD

**Issue by Halberdier** [rstudio/rstudio#11778]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.11.0 Build 113, "Elsbeth Geranium" Daily (cc55ded2, 2022-08-17) for Windows
    OS Version      : Microsoft Windows 10 Enterprise, 10.0.19044
    R Version       : 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid"

### Steps to reproduce the problem
Right-click on a file in Windows File Explorer (e.g., an R script)
Choose "Open With" then RStudio, if RStudio is not already the default app for that file extension

### Describe the problem in detail
RStudio opens the session with the working directory in the user's home.
Not really a bug, but the behavior of this daily build is different from the official release.

### Describe the behavior you expected
In the official release, when RStudio is called to open a file, the working directory is the file location.
In this daily build, the file location has to be set explicitly with setwd(...).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
This may be the same/closely related to #11088

**Comment by jgutman** [comment]
This behavior exists on Electron, on both Mac and Windows

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+215
WIndows 11, MacOS 12.4

Tested against several file types in many paths. Included often problematic paths in windows that contain spaces,etc.
