### ISSUE TITLE
macOS: Make project titles more accessible

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rstudio#11797]
When using RStudio Projects on macOS, it is difficult to quickly determine which icon I need to select from the Dock. The project name is displayed on the icon, but the text is very small unless the icons are made very large. The application title for all of the icons that shows is always just "RStudio". Thus, the only way I can easily determine which icon to click is to click each and read the title of each window.

On Windows, the project title is visible in the tooltip when I hover over the RStudio icon. Would it be possible to do the same on macOS or else to make the project title text larger so that it is easier to read at a glance?

**Comment by jmcphers** [comment]
Ref: https://github.com/rstudio/rstudio/issues/11386

**Comment by bwiernik** [comment]
The referenced issue has been closed, but this one is still not resolved, can it be kept open?

**Comment by bwiernik** [comment]
The referenced issue has been closed, but this one is still not resolved, can it be kept open?

**Comment by bwiernik** [comment]
The issue is still not resolved
