### ISSUE TITLE
some package links are rendered incorrectly

### ISSUE THREAD

**Issue by cboettig** [rstudio/rstudio#11796]
### System details

    RStudio Edition : Server
    RStudio Version :  2022.07.1 Build 554
    OS Version      :  Ubuntu 20.04
    R Version       :  4.2.1

### Steps to reproduce the problem

Install `curl` and search for it in the packages tab in RStudio.

### Describe the problem in detail

Some R packages include annotations on URLs, such as `curl`.  This causes RStudio's package manager's link to the package to be incorrectly parsed.  (see related discussion re {desc} / {roxygen2}, https://github.com/r-lib/roxygen2/issues/1420#issuecomment-1220195729)

![image](https://user-images.githubusercontent.com/222586/185545202-1f23f56c-7681-4d71-9fad-c9fae56e5ddb.png)

### Describe the behavior you expected

Note the mangled link that doesn't actually resolve.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
also need to check https://github.com/r-lib/desc/issues/56, this might have some special cases to consider

**Comment by ronblum** [comment]
@cboettig Thank you for raising this! I can also reproduce this in RStudio Desktop 1.4.1743 and 2022.11.0-daily+153 on MacOS 13. We'll review this as we continue development of RStudio.

**Comment by romainfrancois** [comment]
@ronblum was this not resolved by https://github.com/rstudio/rstudio/pull/11839 ?
