### ISSUE TITLE
Backport #11717 to Spotted Wakerobin 2022.07.2

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#11791]
Backport #11717 to Spotted Wakerobin 2022.07.2

**Note: This issue is to record the need to backport the linked issue only. Please add comments or discussion relating to the original issue onto it directly.**

**Comment by jonvanausdeln** [comment]
Tested on 2022.7.25-576

Tested on Windows and Ubuntu with several account names using different characters.
