### ISSUE TITLE
Observable output not render in Viewer

### ISSUE THREAD

**Issue by rgaiacs** [rstudio/rstudio#11808]
Consider the following minimal working example:

``````
---
engine: knitr
title: "Minimal Working Example"
---

Some text ${x}.

```{ojs}
x = 1
```
``````

When it is render in RStudio Desktop, the Observable variable (`${x}`) is not render.

![image](https://user-images.githubusercontent.com/1506457/185863755-b47ba603-d225-4970-9633-f42155b67e36.png)

The expected result is

![Screenshot 2022-08-22 at 15-28-04 Minimal Working Example](https://user-images.githubusercontent.com/1506457/185864070-18418adb-d855-41a5-b479-bd0bdcaee8f9.png)

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      : Ubuntu 22.04
    R Version       : 4.1.2 (2021-11-01)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@rgaiacs Thank you for raising the issue! I get something else entirely in RStudio Desktop 2022.07.1+554 and 2022.11.0-daily+153:
<img width="519" alt="knit" src="https://user-images.githubusercontent.com/31009952/187458997-3d575c64-fe61-4f77-b12a-156f6745e401.png">

@kevinushey What do you think should be happening?

**Comment by kevinushey** [comment]
It seems to work for me with the latest daily builds (on macOS).

<img width="728" alt="Screen Shot 2022-08-30 at 11 14 33 AM" src="https://user-images.githubusercontent.com/1976582/187512461-c7443502-4eb2-4c04-9805-e431c4a0c461.png">

**Comment by rgaiacs** [comment]
It works for me with the latest daily build (2022.12.0+353) on Ubuntu.
