### ISSUE TITLE
Debugger - pointless read-only window

### ISSUE THREAD

**Issue by avraam-inside** [rstudio/rstudio#11806]
Hi! I use RStudio Server version 2022.07.1 on Ubuntu. 

And I have another problem with the debugger.

I just use a debugger and I get into this ABSOLUTELY pointless, inconvenient read-only window. I have to debagger hundreds of times a day and spend a HUGE amount of time proclaiming the closure of this debagger window.

![image](https://user-images.githubusercontent.com/52919010/185760783-a069306c-109f-4a7f-a2d3-eb92fe001f8a.png)

I NEVER WANT TO GET TO THE READ-ONLY WINDOW IN THE DEBUGGER. How do I can remove it?

I've seen problems with it have already been raised here and they still haven't been fixed.

Please make a setting in RStudio to TURN OFF read-only mode. If R Studio can't find a function, I'll find it myself, OK (and so I'm looking for it), but at least don't make me squeeze the closing of the read-only window hundreds of times.

PS: I apologize for the straightforward tone... But I'm really tired of waiting for the problems with the debugger to be fixed in R Studio, a very annoying and unnecessary read-only window, remove it, just remove it, please.

**Comment by ronblum** [comment]
@avraam-inside Thank you for raising this! Can you provide sample code or file that you're debugging that results in this? This way I can try to reproduce exactly what you're seeing.

**Comment by olivroy** [comment]
This is now fixed in the dev (2024.04.0+558) version of RStudio as part of #13925
