### ISSUE TITLE
Error: Incorrect or invalid username/password

### ISSUE THREAD

**Issue by B-1991-ing** [rstudio/rstudio#11807]
Dear Rstudio support team,

I changed my HPC account's password. And then, I can't log in to my Rstudio server now as shown in the tutorial and got error - **ERROR:Error: Incorrect or invalid username/password**. Could you give me some suggestion?

**1. log in to an interactive node**
<img width="887" alt="Screenshot 2022-08-21 at 15 08 32" src="https://user-images.githubusercontent.com/54441633/185792398-ba3c1746-d425-4ba4-a9d0-e6c7f91d57c7.png">

**2. load RStudio Server Module**
<img width="882" alt="Screenshot 2022-08-21 at 15 09 31" src="https://user-images.githubusercontent.com/54441633/185792425-dabc7483-9070-4e0d-b160-ca7d7b49c4c1.png">

**3. command line: rstudio1.3.1073-R.4.0.0-install**
<img width="885" alt="Screenshot 2022-08-21 at 15 10 17" src="https://user-images.githubusercontent.com/54441633/185792453-f56a0183-5b79-4da2-90cb-c08044506245.png">

**4. ssh -L 8787:<your_interactive_node_name>:8787 <username>@ssh.computerome.dk**
<img width="885" alt="Screenshot 2022-08-21 at 15 10 55" src="https://user-images.githubusercontent.com/54441633/185792477-d2cf77ca-c3e1-4bb5-b0d6-f986a807939b.png">

**5. http://localhost:8787**
<img width="883" alt="Screenshot 2022-08-21 at 15 11 31" src="https://user-images.githubusercontent.com/54441633/185792499-2540e94d-1986-4cd1-93e4-93db3fdf5e56.png">
 
**ERROR:Error: Incorrect or invalid username/password**
<img width="326" alt="Screenshot 2022-08-21 at 15 12 05" src="https://user-images.githubusercontent.com/54441633/185792522-9849ed24-8ac0-43b2-8835-fb67368bcb06.png">

Best,

Bing

**Comment by B-1991-ing** [comment]
Update:

Suddenly, it works now after trying to log in to the Rstudio server using the link - http://localhost:8787/.

Best,

Bing

**Comment by ronblum** [comment]
@B-1991-ing Was this issue resolved? I'm guessing that this was an issue that had to be resolved within Computerome's HPC. 

Sorry for not catching this sooner—we recently changed how we categorize new issues, and a few didn't get flagged correctly.

**Comment by B-1991-ing** [comment]
Hi Blum,

Thank you very much for your reply. Maybe due to HPC admins  also did some updated changes at that time.

Best,

Bing

**Comment by ronblum** [comment]
Bing—glad to hear it, and thank you for the update!
