### ISSUE TITLE
Inline image preview for markdown has inconsistent scale

### ISSUE THREAD

**Issue by steveharoz** [rstudio/rstudio#11818]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 
    OS Version      :  Windows 11
    R Version       :  4.2.1

### Steps to reproduce the problem

Open this RMD file in RStudio and run it (not knit):

````
---
title: "Untitled"
output: html_document
---

```{r setup}
library(ggplot2)
```

```{r}
ggplot(mtcars) +
  aes(x=wt, y=hp) +
  geom_point()
```

```{r fig.height=5, fig.width=7}
ggplot(mtcars) +
  aes(x=wt, y=hp) +
  geom_point()
```
````

### Describe the problem in detail

It does not seem possible to match the default size and scale of the Rstudio preview images. This prevents a functional preview when working with text and labels with custom fonts and font sizes.

![image](https://user-images.githubusercontent.com/2257540/186137533-15e97a39-92f3-4e30-bd67-9a8b8c4a9bc1.png)

### Describe the behavior you expected

Maybe in the chunk settings GUI, it could show information about the default values for figure size and dpi?

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
By default, plots within the notebook (when no figure width or height are set) try to be adaptive to the editor size. For example, if you resize the editor to be smaller, you'll see plots re-rendered at the smaller width.

My recommendation here would be to set a default figure width + height for all plots, with something like:

```
knitr::opts_chunk$set(
  fig.width = 4,
  fig.height = 3
)
```
