### ISSUE TITLE
RStudio session restarts without warning when changing the value of "Soft-wrap R source files"

### ISSUE THREAD

**Issue by andrie** [rstudio/rstudio#11811]
@jgutman

**Comment by ronblum** [comment]
This appears to be an Electron issue. In RStudio Desktop 2022.07.0+548 on MacOS 13, this is a problem in the Electron version but not in the Qt version.

**Comment by mikebessuille** [comment]
changing this setting should not require a reload of R or a refresh of the page (right now it's just refreshing the page, the session stays the same).

IF changing this setting requires a refresh of the page for some reason, we should warn the user like we do with some other settings that relaunch R

**Comment by jgutman** [comment]
I think this is now the case for all Global Options > Code. Any change there triggers a session restart

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+284, Windows 11.

Tested changing several options, and UI/Session didn't refresh unnecessarily.
