### ISSUE TITLE
Fedora 36 daily build conflicts with drawio 20.2.3

### ISSUE THREAD

**Issue by psads-git** [rstudio/rstudio#11810]
When I try install 

`drawio 20.2.3`

I get 

```
Error: Transaction test error:
  file /usr/lib/.build-id/a2/562c52725bb7caa27cd0de814ec368b8c45e7f from install of draw.io-20.2.3-1.x86_64 conflicts with file from package rstudio-2022.07.2+564-1.x86_64

```
Thanks!

**Comment by kevinushey** [comment]
@Enchufa2, does this ring any bells for you?

**Comment by Enchufa2** [comment]
Build ids are unique identifiers for binary objects (shared libraries, etc.). This kind of error happens when the same binary is included in more than one package. What is this drawio and where does it come from?

**Comment by psads-git** [comment]
Thanks, Iñaki! It comes from:

https://github.com/jgraph/drawio-desktop/releases

**Comment by Enchufa2** [comment]
So it's an Electron app, and I suppose that you see that error with an RStudio Electron build. If both apps are bundling the same Electron copy, then it's the same binary and the installer complains. It seems this is a common issue among Electron apps: https://github.com/jgraph/drawio-desktop/issues/259.

The workaround would be to disable build ids in the spec, as e.g. [vscode did](https://github.com/microsoft/vscode/pull/116105/files).
