### ISSUE TITLE
Add option to Quarto Visual editor to insert customize snippets

### ISSUE THREAD

**Issue by rressler** [rstudio/rstudio#11814]
Quarto visual editor does not allow inserting of customized snippets created in the RStudio Tools/Edit Code Snippets. Suggest adding an entry to the Insert menu called Snippets where one can enter the name of the snippet they created and have it execute in the visual editor.

**Comment by ronblum** [comment]
@rressler Thank you for the suggestion! We'll review this as we continue development of the RStudio visual editor.

**Comment by actuariat** [comment]
Very important, so please fix it.
