### ISSUE TITLE
Backport #11804 to SW 2022.07.2

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#11815]
Backport #11804 to SW 2022.07.2
Must include f265d98678 and 82e0174552

**Note: This issue is to record the need to backport the linked issue only. Please add comments or discussion relating to the original issue onto it directly.**

**Comment by jonvanausdeln** [comment]
Verified 2022.07.2-571
Windows 11, Ubuntu 22.04, MacOS 12.4

Tested projects and files with spaces in various places, including multiple spaces. Also included tests of included files with spaces in paths and filenames.
