### ISSUE TITLE
Restarting the R session when a shiny app still runs doesn't close the shiny app

### ISSUE THREAD

**Issue by andrie** [rstudio/rstudio#11812]
This leaves the shiny app in a "weird state" (techical term) and the "stop" button is still visible.

My expectation is that the shiny app will be disconnected on session restart.

This happens in desktop as well as Workbench.

@jgutman

**Comment by jeffvroom** [comment]
To fix this problem, [here](https://github.com/rstudio/rstudio/blob/57af9a15dae0a43331b792d05cabddedf536a4d2/src/cpp/server/session/ServerSessionProxy.cpp#L380-L382) is where we create the socket proxy and call `checkForValidUserSession`.  We could pass in the session id as an extra argument to this callback and have it return false when the session has exited.
