### ISSUE TITLE
When trying to open an R file, "(TypeError) cannot read property 'raw_path' of null"

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#11826]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Windows 11
    R Version       : 4.2.1

### Steps to reproduce the problem

I am not certain of the full steps to reproduce this.  I left R running overnight on my laptop, and I got the error below.

1. Try to open a file in an R session running overnight (not sure of the underlying cause, may be related to #11825)
2. An error pops up.

### Describe the problem in detail

I see this error: 
![image](https://user-images.githubusercontent.com/10359931/186414690-3722cfeb-55f8-4997-9ae0-9dda7765404c.png)

After clicking "ok" on the message window, the file opens as expected.

### Describe the behavior you expected

The file opens without an error message.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by billdenney** [comment]
As I was working in the same session more, could not save files after editing them, and I continued getting similar errors.  I more strongly believe that this is related to #11825.

**Comment by ronblum** [comment]
Note: Not sure if this is directly related, but issue #11769 also has a `TypeError` message.

**Comment by blongworth** [comment]
Seeing the same error and behavior today. Error also shows up when viewing an object by clicking or `View()`.

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.7.2.576
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)
