### ISSUE TITLE
use `<!-- content -->` comment in `md` file through `Ctrl+Shift+C`

### ISSUE THREAD

**Issue by Shitao5** [rstudio/rstudio#11821]
When I write in an `md` file in RStudio source editor and use the shortcut `Ctrl+Shift+C` for comments, it shows `# content` instead of the same as the `rmd` file which is `<!-- content -->` , `#` means a first level heading in the `md` file. Can it be improved so that `md` files can be commented as well as `rmd` files. Thanks!

My RStudio version is `2022.7.1.554`.

**Comment by ronblum** [comment]
@Shitao5 Thank you for raising this! I'll mark it for review as part of our ongoing development of RStudio.

**Comment by Shitao5** [comment]
In RStudio version 2023.03.0-daily+362, the issue still exists. Please do not close this issue.
