### ISSUE TITLE
Export as PDF dimensions only affect width

### ISSUE THREAD

**Issue by gevro** [rstudio/rstudio#11820]
2022.07.1 Build 554

Export as PDF: Changing the dimensions (width or height) both affect width, instead of one affecting height and one affecting width.

**Comment by ronblum** [comment]
@gevro Thank you for raising this! Can you provide the following information so that I can try to reproduce in a similar environment?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by gevro** [comment]
2022.07.1 Build 554

Desktop

OS macOS 12.5.1

R: 4.2.0

 

From: Ron Blum ***@***.***>
Reply-To: rstudio/rstudio ***@***.***>
Date: Tuesday, August 30, 2022 at 10:02 AM
To: rstudio/rstudio ***@***.***>
Cc: gevro ***@***.***>, Mention ***@***.***>
Subject: Re: [rstudio/rstudio] Export as PDF dimensions only affect width (Issue #11820)

 

@gevro Thank you for raising this! Can you provide the following information so that I can try to reproduce in a similar environment?
System details
RStudio Edition : 
RStudio Version : 
OS Version      : 
R Version       :
