### ISSUE TITLE
Can't create new project from Existing directory on Windows 11

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#11824]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.11.0.135
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

### Steps to reproduce the problem

* Open RStudio IDE
* Create new folder in the users Documents directory. For example `test_project`
* Click on File > New Project > Existing Directory 
* Browser and select the newly created directory
* You should have now something like 
   ![image](https://user-images.githubusercontent.com/6791940/186387464-f471655d-16a9-476f-8aae-8d62902a277b.png)

  _Small notes: I think in previous release version, it was a `~` and not the absolute path shown in this windows. Hint for the issue ?_
* Click Create project. This is the error you'll get
   ![image](https://user-images.githubusercontent.com/6791940/186387610-7c877c80-6fe4-4d65-ad14-63a8020396fd.png)

### Describe the problem in detail

New project can't be created from existing directory. 

In addition, this is what we get created inside the selected directory 

````
> fs::dir_tree("test_project/")
test_project/
└── Users
    └── chris
        └── Documents
````

`test_project` was empty, but now it is filled with some files from the whole path. It is like the `C://` was not correctly handle by the IDE. 

### Describe the behavior you expected

Project should be created correctly, and without folder to be created wrongly.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I can reproduce. If you look in the request log you'll see something like:

```
== REQUEST ======
{
  "method": "create_project",
  "params": [
    "C:\\Users\\kevin\\scratch\\example/C:\\Users\\kevin\\scratch\\example.Rproj",
    null,
    null,
    null
  ],
  "clientId": "33e600bb-c1b1-46bf-b562-ab5cba070b0e",
  "clientVersion": ""
}

== RESPONSE ======
{
  "error": {
    "code": 100,
    "message": "Error occurred while executing method",
    "error": {
      "code": 123,
      "category": "system",
      "message": "The filename, directory name, or volume label syntax is incorrect",
      "location": "auto __cdecl rstudio::core::FilePath::openForWrite::<lambda_422506e39d7bd889ea4db0fa5c9fcccd>::operator ()(void) const src/cpp/shared_core/FilePath.cpp:1499"
    }
  }
}
```

It looks like something is going wrong with path manipulation; note the path:

```
    "C:\\Users\\kevin\\scratch\\example/C:\\Users\\kevin\\scratch\\example.Rproj",
```

**Comment by mikebessuille** [comment]
I doubt it's related, but note we have this issue as well: https://github.com/rstudio/rstudio/issues/11769

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+272 Desktop
Windows 11

New projects are created correctly in existing folders.
