### ISSUE TITLE
Find in Files totally stopped working

### ISSUE THREAD

**Issue by ben1787** [rstudio/rstudio#11822]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
Search for something using ctrl+shift+f

### Describe the problem in detail
It takes no time at all and immediately says no results. My path is correct. And I have made no other selections.

### Describe the behavior you expected
It should find the word I am searching for. It finds nothing for any search term.

- [ x] I have read the guide for [submiting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can you please provide some more details?

- Are you working with an RStudio project, or just in the home directory?
- Does that project directory have any non-ASCII characters, or spaces, or similar?
- Is the project managed by version control (`git`)? If so, what version of Git for Windows do you have installed?
- What filters, or options, do you have set on the Find in Files dialog? Can you share a screenshot?

You can also try setting the following environment variable:

```
Sys.setenv(RSTUDIO_GREP_DEBUG = 1)
```

and then execute a Find in Files request, and send us the resulting output printed in the console.

**Comment by ben1787** [comment]
I am looking ~/GitHub/R.

Project managed by git but not through RStudio. To RStudio it is just a folder.

No filters in dialog.

![image](https://user-images.githubusercontent.com/4843501/186254166-7d899a80-4be3-464d-b5ad-bd78999c4fa6.png)

![image](https://user-images.githubusercontent.com/4843501/186254033-13b2541d-f3d9-48ec-ae06-92bcd006a7fb.png)

**Comment by kevinushey** [comment]
Thanks -- updating to the latest version of Git for Windows should fix this issue.

**Comment by ben1787** [comment]
success!! thank you very much

**Comment by jgutman** [comment]
Reopening because we fixed this issue in Elsbeth but it was never tested. Would need to be tested on Windows using an older version of Git.

(If this doesn't get tested that's probably fine but would be ideal to have a quick QA)

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0.334 Desktop, Windows 11

Find in files works as expected, for both git projects and not git projects

**Comment by greenjune-ship-it** [comment]
Dear Dev Team,

This bug also persists in the latest RStudio / Posit Workbench.
Is it possible to fix this bug?

- Many IDEs use Git for this "Find in Files "feature as well and there are no problems with them.
- Many people also still use CentOS7 where the git version is 1.8.3.1. For the HPC environment is it not just "yum update git".
 
So it is not user-friendly to just let this bug continue persisting.
Especially if it is an already known bug that is not even documented in the admin guide (at least like the recommended Git version).

Thank you in advance!
Best regards,
Yulia

**Comment by jgutman** [comment]
This has been fixed, but the fixed version is not yet an official release.
We expect it to be released soon, within the next month. In the meantime,
the fix is available by downloading the daily build from
https://dailies.rstudio.com/

**Comment by tentacles-from-outer-space** [comment]
With RStudio 2022.12.0+353.pro20  on RHEL 7.9 (which had git 1.8.3.1) it is not working. Should be?

**Comment by ronblum** [comment]
@tentacles-from-outer-space It should work. I can try to see if it works for me or if I see a problem, too. Just to make sure that I follow the same steps as you, is the project managed with git in RStudio or externally?

**Comment by tentacles-from-outer-space** [comment]
I see in logs:

```
2023-03-01T18:08:32.722571Z [rserver-monitor] ERROR 2023-03-01T18:08:32.722336Z [rsession-username] ERROR grep: Unknown option: -C
usage: git [--version] [--help] [-c name=value]
[--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
[-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
[--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
<command> [<args>]
LOGGED FROM: void rstudio::session::modules::find::{anonymous}::GrepOperation::onStderr(const rstudio::core::system::ProcessOperations&, const string&) src/cpp/session/modules/SessionFind.cpp:1175|||
```

**Comment by kevinushey** [comment]
@tentacles-from-outer-space what version of `git` do you have installed? Modern versions of `git` should have it: https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt

This piece of the release notes suggests it's been there since git 1.8.5:

https://github.com/git/git/blob/2e71cbbddd64695d43383c25c7a054ac4ff86882/Documentation/RelNotes/1.8.5.txt#L115-L116

**Comment by tentacles-from-outer-space** [comment]
@kevinushey 

> With RStudio 2022.12.0+353.pro20 on RHEL 7.9 (which had git 1.8.3.1) 

I can't update cause is it only system version that exists in RHEL repository.

This is the same case as [in greenjune-ship-it comment](https://github.com/rstudio/rstudio/issues/11822#issuecomment-1326382950). My first comment is about response to it by [jgutman](https://github.com/rstudio/rstudio/issues/11822#issuecomment-1326743625) where she states that it should work but it is not.

**Comment by greenjune-ship-it** [comment]
@tentacles-from-outer-space 

For me, this still doesn't work even after upgrading to the latest version (2022.12.0+353.pro20) in CentOS7. I confirm that the original cause is not fixed, so "Find in Files" feature is still not compatible with default git 1.8.3.1.

I found a workaround and build git as [Easybuild](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/g/git) / lmod module that is loaded within rsession-run scripts. It works with the previous version perfectly, but after upgrading to the latest one it doesn't work anymore.

The cause why it doesn't work anymore is in the fact that Rstudio changes the PATH variable when Rproj is open. The first value is `/usr/bin` that's why system git is used by default instead of lmod one. We are trying to reveal together with the support team the cause of such behaviour, so unfortunately I cannot add anything helpful. But I hope I will!

**Comment by kevinushey** [comment]
The fix would be around here:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionFind.cpp#L1478-L1479

It looks like we already set the process working directory here:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionFind.cpp#L1554-L1555

so the use of `-C <dir>` above might be superfluous; maybe we should just remove it?

**Comment by tentacles-from-outer-space** [comment]
> The cause why it doesn't work anymore is in the fact that Rstudio changes the PATH variable when Rproj is open. The first value is `/usr/bin` that's why system git is used by default instead of lmod one. We are trying to reveal together with the support team the cause of such behaviour, so unfortunately I cannot add anything helpful. But I hope I will!

Well, I am with support on the same thing. We used the Red Hat Software Collection to switch to modern git (2.x), but it also relies on modifying the PATH.

**Comment by kevinushey** [comment]
One potential workaround: in Tools -> Global Options... -> Python, try unchecking the [ ] Automatically activate project-local Python environments preference:

<img width="611" alt="Screenshot 2023-03-06 at 10 10 01 AM" src="https://user-images.githubusercontent.com/1976582/223194702-bfcef0b3-1bd0-44c6-b442-b553ca21de34.png">

**Comment by ronblum** [comment]
Verification tests 1: RStudio Desktop on CentOS 7. All work.

Environment

    RStudio.Version()$long_version
    [1] "2023.03.0+385"
    [vmware@localhost ~]$ git --version
    git version 1.8.3.1
    $ echo $PATH
    /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin

---

No Project
No Python interpreter selected
Python environments checked
WORKS

Sys.getenv("PATH")
[1] "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin

----

No Project
No Python interpreter selected
Python environments unchecked
WORKS

Sys.getenv("PATH")
[1] "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin

---

Regular Project
Python 3.6.8 interpreter selected
Python environments checked
WORKS

Sys.getenv("PATH")
[1] "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

[vmware@localhost ~]$ echo $PATH/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin

---

Regular Project
Python 3.6.8 interpreter selected
Python environments unchecked
WORKS

Sys.getenv("PATH")
[1] "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

$ echo $PATH
/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin


---

Regular Project
Python 3.6.8 interpreter selected
Python environments checked
WORKS

Sys.getenv("PATH")
[1] "/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

$ echo $PATH
/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin

---

Regular Project
Python 3.6.8 interpreter selected
Python environments unchecked
WORKS

$ echo $PATH
/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin

Sys.getenv("PATH")
[1] "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

---

Git Project
Python 3.6.8 interpreter selected
Python environments unchecked
WORKS

Sys.getenv("PATH")
[1] "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

$ echo $PATH
/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin

---

Git Project
Python 3.6.8 interpreter selected
Python environments checked
WORKS

Sys.getenv("PATH")
[1] "/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback"

$ echo $PATH
/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/vmware/.local/bin:/home/vmware/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/usr/bin:/home/vmware/.local/bin:/home/vmware/bin

**Comment by ronblum** [comment]
Filed issue above as #12781.

**Comment by ronblum** [comment]
Verified that this continues to work in RStudio Desktop 2023.03.0+385 on MacOS 13.2 and RStudio Server 2023.03.0+385 on Ubuntu 20.04.5 via Chrome on MacOS 13.2.
