### ISSUE TITLE
Chrome devtools opens when using insert code chunk shortcut in non-markdown file

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#11827]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.11.0+132
    OS Version      : Mac 12.5.1
    R Version       : 4.2.1

### Steps to reproduce the problem
1. Open a file that is not a markdown file, such as an R file
2. Use the insert code chunk shortcut (Option+Command+I on Mac)

### Describe the problem in detail
The Chrome developer tools opens. Qt builds would not do this.

### Describe the behavior you expected
The devtools does not open.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
This is from adding the 'Toggle Developer Tools' menu item. The key accelerator conflicts with the 'Insert Code Chunk' action. Removing the dev tools accelerator seems reasonable.

**Comment by jgutman** [comment]
So then this shortcut will just do nothing in an R file? and that's what the behavior was before in Qt?

**Comment by timtmok** [comment]
> So then this shortcut will just do nothing in an R file? and that's what the behavior was before in Qt?

I think this 'Toggle Developer Tools' is new in Electron. It wasn't present in Qt and you have to right-click and 'Inspect Element' to show the developer tools. This removes the shortcut (Electron adds it by default) so that it won't conflict with 'Insert Code Chunk'. I could only reproduce this behaviour in an R file but a user reported that it wouldn't work in a markdown file where 'Insert Code Chunk' is available.

**Comment by ronblum** [comment]
Verified fixed in RStudio Desktop 2022.11.0-daily+169 on MacOS 13. Used build 2022.10.0-daily+64 as a comparison point.

Note that this doesn't impact on RStudio Server, which is in a browser and therefore the browser's shortcuts take precedence, opening up the developer tools. For this reason, though, we might consider changing the shortcut since it can't be used to insert chunks.
