### ISSUE TITLE
Rebrand:  "RStudio Pro" when launched from Workbench

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#11838]
When the IDE is launched from Workbench, the IDE window should be called "RStudio Pro", and under Help, it should say "About RStudio Pro" instead of "About RStudio".

**Comment by jgutman** [comment]
> the IDE window should be called "RStudio Pro"

Does this refer to the tab name, or something else? It currently shows as RStudio Workbench.

**Comment by mikebessuille** [comment]
the browser tab name, and also "about RStudio Pro".   They should both say "RStudio Pro".   I think the current way of showing "RStudio Workbench" has always been misleading, if we think of workbench as the server and RStudio as the IDE. 
@andrie  to comment.

**Comment by jgutman** [comment]
How about "RStudio Server Home" is that still staying the same?

**Comment by mikebessuille** [comment]
Does it take you back to Workbench or RStudio Server?  If so, it should definitely change, for the case where the IDE was launched from Posit Workbench.

**Comment by jgutman** [comment]
When launched from Workbench, it seems to take the user back to the Posit Workbench homepage. So I can add that to the list to update

**Comment by jgutman** [comment]
Summary:
- Tab name of Workbench home should be "Posit Workbench" not "RStudio Workbench" (separate PR)
- Tab name of IDE launched from Workbench should be "RStudio Pro" not "RStudio Workbench"
- File menu name for launching About dialog should be "About RStudio Pro" not "About RStudio"
- When About dialog is launched, Title should be "About RStudio Pro" and contents should refer to "RStudio Pro" not "About RStudio Workbench"
- Hover text for RStudio symbol to return to Workbench Home should be "Posit Workbench" not "RStudio Server Home"
- File menu name for returning to Workbench Home should be "Posit Workbench" not "RStudio Server Home"

**Comment by jgutman** [comment]
See screenshots in https://github.com/rstudio/rstudio-pro/pull/3839

**Comment by ronblum** [comment]
Just to clarify: When we say IDE in this context, we're talking about launching RStudio Server in a web browser, not RStudio Desktop for a remote connection.

**Comment by jgutman** [comment]
Yes, and it should be called RStudio Pro when launching server in the browser from workbench. And rstudio desktop pro when connecting to a remote desktop session

**Comment by ronblum** [comment]
I just tried it in what should be Posit Workbench 2022.11.0-daily+187.pro2, but everything is still RStudio Workbench,  etc. For example:

<img width="610" alt="Screenshot 2022-09-19 at 11 30 11 AM" src="https://user-images.githubusercontent.com/31009952/191059269-efce44c0-a77d-453a-93c9-b79b3a083b1c.png">

**Comment by jgutman** [comment]
Sorry had to revert changes because I broke the build but will fix up soon

**Comment by ronblum** [comment]
Verified in RStudio Workbench 2022.11.0-daily+199.pro1 on Ubuntu 20.04 via Chrome on MacOS 13.

Both in and out of a project display "RStudio Pro".

<img width="393" alt="project_yes" src="https://user-images.githubusercontent.com/31009952/191753448-93c06bcb-94d8-4129-887e-51fae2bfa6da.png">

<img width="373" alt="project_no" src="https://user-images.githubusercontent.com/31009952/191753449-fc1f6caa-8343-46b3-9951-a735a862e48e.png">
