### ISSUE TITLE
Rstudio window unusable when coming back from monitor sleep with multiple monitors on Windows 11

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#11844]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Windows 11
    R Version       : 4.2.1

### Steps to reproduce the problem

I have an unusual monitor setup.  I have three monitors:  one on my laptop and two external monitors.  Because the monitors are different sizes, they each have different scale settings (windows control panel > Display > scale & layout > scale).

1. Open an Rstudio window
2. Walk away from the computer long enough for the monitors to go to sleep
3. Log back in to the computer

It may be important that this is either not on the main monitor (the laptop screen) or that this is on a screen with a lower zoom than the maximum zoom.  This was on my 3rd monitor by windows counting, and the zoom is 150% compared to 250% on the laptop screen (which is the 1st monitor).

### Describe the problem in detail

The window looks odd with the console area zoomed in and no other parts visible:

![image](https://user-images.githubusercontent.com/10359931/186784668-632feb26-d36f-4ae1-842f-fd394ef5a4fa.png)

After clicking in the area that should have the file view pane, the window became blank:

![image](https://user-images.githubusercontent.com/10359931/186785104-0eafacbf-d82d-45c0-a7cd-3c11a8d16145.png)

### Describe the behavior you expected

The window looks normal.

Might the solution be some form of window reset on monitor turning back on?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by billdenney** [comment]
There is a simple work-around.  Minimizing then restoring the window reset the view.

**Comment by billdenney** [comment]
More observations:  The minimize then restore fix doesn't always work.

Another workaround:  Moving the window from one monitor to another (where the scale is different) seems to work the one time I tried it.  I can move it back to the original monitor, and it will still look correct.

**Comment by kevinushey** [comment]
For reference, we expect this should be fixed in the latest daily builds: https://dailies.rstudio.com

**Comment by ronblum** [comment]
[Note: Tagging as `electron` because this should be fixed by it—this is similar to other issue resulting from sleep on Windows.]

**Comment by billdenney** [comment]
I'm testing the current daily build today.

**Comment by mikebessuille** [comment]
@billdenney did the daily fix this issue for you?

**Comment by billdenney** [comment]
Yes, I've been using the daily (version below) for a couple of weeks without issue.

RStudio 2022.11.0-daily+165 "Elsbeth Geranium" Daily (76ecb84dc8fdf65e181eb5da07752203e46e1b95, 2022-09-02) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+165 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36

**Comment by mikebessuille** [comment]
@billdenney thank you for verifying this!  Much appreciated, and glad this fixes the problem.
