### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by mpettis** [rstudio/rstudio#11846]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      : Windows 10 Enterprise 21H1 (64-bit)
    R Version       : 4.2.1

### Steps to reproduce the problem
Open RStudio, let sit for a few hours.

### Describe the problem in detail
When I leave RStudio open, it gradually eats memory.  It can start around 0.3 - 0.5GB memory, and after a few hours, it can get up to 2GB of memory, and I have not been utilizing it at all.

### Describe the behavior you expected
Memory to stay roughly constant when I don't interact with it.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
To confirm, are you referring to the front-end process (RStudio.exe) or the R session itself (rsession.exe or rsession-utf8.exe)?

**Comment by mpettis** [comment]
I'll report back... I realize I was just looking at the rollup of off of the processes.  I believe it is the RStudio.exe, as I would run `gc()` and reboots of the R session did not reduce the memory footprint.  But I'll monitor now again.

**Comment by mpettis** [comment]
I'm trying to reproduce this, having some issue (I also accidentally shut down the app this morning, so couldn't check).  But I am trying to reproduce it, and will let you know if I can or cannot.  I suspect it may be related to objects that persist in the RStudio session rather than in the R session.  An example that I do a lot is I am making a `listviewer::jsonedit()` call that persists results in RStudio even between restarting R sessions.

**Comment by kevinushey** [comment]
Thanks for the update -- please let us know what you're able to learn.

**Comment by mpettis** [comment]
I am unable to reproduce, I will reopen if I am able to reproduce.

**Comment by mpettis** [comment]
I'd like to reopen this issue.  I opened RStudio (same details as above) and just left it open.  Then I ran the script below (cygwin, bash) to track the memory.  

```
#!/bin/bash

for i in `seq 244`; do
    date
    tasklist | egrep 'rstudio|rsession'
    sleep 300
done >> rstudio-mem.txt
```

The following is the history detail of the memory.

In short, here is the beginning and end of the memory...

```
Wed Oct 19 08:58:50 CDT 2022
rstudio.exe                   9192 Console                    1    476,472 K
rsession-utf8.exe            16224 Console                    1    199,020 K
Wed Oct 19 09:03:51 CDT 2022
rstudio.exe                   9192 Console                    1    475,968 K
rsession-utf8.exe            16224 Console                    1    199,052 K
Wed Oct 19 09:08:52 CDT 2022
rstudio.exe                   9192 Console                    1    453,772 K
rsession-utf8.exe            16224 Console                    1    199,088 K

...

rstudio.exe                   9192 Console                    1  2,020,624 K
rsession-utf8.exe            16224 Console                    1    104,984 K
Thu Oct 20 05:12:09 CDT 2022
rstudio.exe                   9192 Console                    1  2,027,824 K
rsession-utf8.exe            16224 Console                    1    104,988 K
Thu Oct 20 05:17:10 CDT 2022
rstudio.exe                   9192 Console                    1  2,036,012 K
rsession-utf8.exe            16224 Console                    1    104,992 K
```


[rstudio-mem.txt](https://github.com/rstudio/rstudio/files/9855423/rstudio-mem.txt)
