### ISSUE TITLE
Recognize (#[0-9]+) as links to issues and PRs

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11840]
Recognize (#[0-9]+) as links to issues and PRs.

Addressed by #11553, which contains more information.

**Comment by romainfrancois** [comment]
QA: in a package project (e.g. dplyr), in one test file, with the code below. The 5 things in `()` should be underlined, and Cmd + Clicking them should open the issue or url. 

```r
# opens https://github.com/tidyverse/issues/123
test_that("this (#123)", {})

# opens https://github.com/tidyverse/issues/123
test_that("this (tidyverse/dplyr#123)", {})

# opens https://github.com/tidyverse/issues/123
test_that("this (github::tidyverse/dplyr#123)", {})

# opens https://gitlab.com/jimhester/covr/issues/214
test_that("this (gitlab::jimhester/covr#214)", {})

# opens posit.co
test_that("this (https://posit.co)", {})
```

In the DESCRIPTION file, remove the `BugReports` field, cmd-clicking the `#123` pops up an error dialog.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.11.0-daily+169 on MacOS 13
- RStudio Server 2022.11.0-daily+169 on Ubuntu 20 via Chrome on MacOS 13

Tested using
- the above code
- a few other examples in #11553 
- invalid values for `BugReports`
- the `tidyverse/dpylr` repository
- a new default R package

Note that this means that if a hashtag that starts with numbers and no space is intended to be a comment, it'll be considered a link:

![Image](https://user-images.githubusercontent.com/31009952/189435651-5e3e3ec0-d689-41cc-bf9c-b52997947063.png)

However, going by [the comments section](https://style.tidyverse.org/syntax.html#comments) of the Tidyverse style guide (if ever there was one to follow), there should be a space between the hashtag and the start of the comment, so this is very acceptable.
