### ISSUE TITLE
Visual editor does not follow links to local documents (other .qmd for example)

### ISSUE THREAD

**Issue by battmanux** [rstudio/rstudio#11845]
### System details

    RStudio Edition : Server [Open Source]
    RStudio Version : 2022.11.0.139
    OS Version      : Ubuntu 20.04.4 LTS
    R Version       : R version 4.2.1 (2022-06-23)

### Steps to reproduce the problem
Create two .qmd files (t1.qmd and t2.qmd)

``` 
# T1 file content

t1.qmd file has a link to [t2 file](t2.qmd)
```

```
# T2 file content

t2.qmd file has a link to [t1 file](t1.qmd)
```

### Describe the problem in detail

When editing t1.qmd in visual mode, clicking on t2.qmd link try to open https://hostname.tld/t2.qmd 

### Describe the behavior you expected

I would expect the visual editor to switch to t2.qmd in visual mode.

### Possible solution

Test for http before opening as url in
https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/gwt/panmirror/src/editor/src/marks/link/link-popup.tsx#L100

I tested : 
```
 const onLinkClicked = () => {
    props.view.focus();
    if (props.link.heading) {
      props.nav.navigate(NavigationType.Heading, props.link.heading);
    } else if (props.link.href.startsWith('#')) {
      props.nav.navigate(NavigationType.Href, props.link.href.substr(1));
    } else if (props.link.href.match('://')) {
      props.ui.display.openURL(props.link.href);
    } else {
      xref = {file:e.link.href, type: '', id: '', suffix: '', title: ''} // should be populated but i do not know how
      props.ui.display.navigateToXRef(props.link.href, xref); // we should create a new function navigateToFile(path) to reduce side effects
    }
```
### patch for existing install

Tested on ‘2022.7.1.554’
Do not use relative path (start with /.../my_file.qmd or ~/.../my_file.qmd ) as it will produce a bug

```
# from bash
sudo cp /usr/lib/rstudio-server/www/js/panmirror/panmirror.js /usr/lib/rstudio-server/www/js/panmirror/panmirror.js.backup
sudo sed -i "s/e.ui.display.openURL(e.link.href)/e.link.href.match(\':\\/\\/\') ? e.ui.display.openURL(e.link.href) : e.ui.display.navigateToXRef(e.link.href, {file:e.link.href, type: \'\', id: \'\', suffix: \'\', title: \'\'})/" /usr/lib/rstudio-server/www/js/panmirror/panmirror.js
```

### Session info

R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.1  fastmap_1.1.0   htmltools_0.5.3 tools_4.2.1     rstudioapi_0.14 yaml_2.3.5      rmarkdown_2.16 
 [8] knitr_1.40      xfun_0.32       digest_0.6.29   rlang_1.0.4     evaluate_0.16  

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@battmanux Thank you for raising this! I can also reproduce this:
- In RStudio Desktop 2022.11.0-daily+153 on MacOS 13
- In both R Markdown and Quarto documents

We'll review this as we continue development of RStudio.

**Comment by jjallaire** [comment]
I implemented this (using the suggested tactic of a new `navigateToFile()` method) here: https://github.com/rstudio/rstudio/commit/e17710ee9bf0ade855c8e6da61389f10748f44e2

**Comment by ronblum** [comment]
Tested in RStudio Desktop 2022.11.0+166 on MacOS 13: When clicking on the link, which lets you copy the link, remove the link, or edit its attributes. However, then clicking on the link doesn't do anything.

This is as far was we get:
![Image](https://user-images.githubusercontent.com/31009952/188897196-f7cfe42d-bc25-43d0-9e91-b63002870586.png)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.12.0-daily+286 on MacOS 13 using the sample Quarto files `t1.qmd` and `t2.qmd` above. Also verified using R Markdown (rmd) documents.
