### ISSUE TITLE
User Library not displayed on Packages pane on Windows

### ISSUE THREAD

**Issue by sgvignali** [rstudio/rstudio#11847]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      : Windows 10 Pro 21H1
    R Version       : 2.4.1

### Steps to reproduce the problem
1. Open RStudio
2. Check if the default folder for the user library exists: `dir.exists(Sys.getenv("R_LIBS_USER"))`
3. If it does not exist, create it: `dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)`
4. Restart R
5. Check if it has been included in the search path as default folder: `.libPaths()`
6. Install a new package, for example `ggplot2`: `install.packages("ggplot2")`
7. Confirm that the package has been installed in the user library: `dir.exists(file.path(Sys.getenv("R_LIBS_USER"), "ggplot2"))`
### Describe the problem in detail
RStudio does not show the **User Library** in the **Packages** pane and the new package appears in the **System Library** although it is installed in the user library folder.
### Describe the behavior you expected
RStudio should show  the **User Library** in the **Packages** pane with the new package.

The **User Library** in the **Packages** pane is displayed properly if the `R_LIBS_USER` variable points to, for example, `C:/Users/${USERNAME}/Documents/R/win-library/%v.` This was the old default folder for the user library before R version 4.2.0. Since R 4.2.0. it has been moved to `C:/Users/${USERNAME}/AppData/Local/R/win-library/%v` .

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- however, everything looks correct on my side.

<img width="828" alt="Screen Shot 2022-08-26 at 9 51 39 AM" src="https://user-images.githubusercontent.com/1976582/186954415-6ae9918b-58eb-4a5f-84b1-973612ae265c.png">

Can you provide any other details that might help us reproduce here?

**Comment by sgvignali** [comment]
Thank you @kevinushey for checking this. I tried several folders and it works only if I set the user library to the **Documents** folder.
This is a screenshot of the steps, starting from a clean R environment:

![image](https://user-images.githubusercontent.com/22011122/186960464-9fe292e4-e32a-46fa-a8a5-fcb397179d15.png)

As you can see the package is installed in the correct folder but appears among the system packages. What can I provide to help reproducing the problem?

**Comment by kevinushey** [comment]
Ah, sorry, I can reproduce now -- I initially wasn't able to reproduce as I have the following environment variable set:

```
R_USER = %USERPROFILE%
```

However, in a default configuration, the library path is no longer seen as being within the R "home" directory, and so it gets considered as part of the system library.

I will take a closer look; thanks for reporting!

**Comment by sgvignali** [comment]
Thank you. I've also updated the steps to reproduce the problem, as it is necessary to restart R to have the user library in the search path.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-173
Windows 11

Tested against several different packages and User Lib directories

**Comment by sgvignali** [comment]
Thank you for fixing the problem. In which release do you plan to include this fix?

**Comment by kevinushey** [comment]
It will be part of the next release (currently scheduled for November)

**Comment by sgvignali** [comment]
Great, thank you!
