### ISSUE TITLE
Mac installation fails as finder cannot copy 

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/rstudio#11857]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio Desktop 2022.07.1+554
    OS Version      : Mac OS Monterey
    R Version       :  NA

### Steps to reproduce the problem
  - Download Rstudio dmg from https://www.rstudio.com/products/rstudio/download/#download
 - Open the dmg
 - Copy to applications
 
### Describe the problem in detail
At the final step the following error is thrown by my macbook pro
>The Finder can’t complete the operation because some data in “RStudio” can’t be read or written.
(Error code -36)

### Describe the behavior you expected
When I copy a dmg file from downloads to applications it should silently overwrite the previous version. This is the first time the copy has been blocked. 

Please keep the below portion in your issue, and check `[x]` the applicable boxes.
-->

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ NA] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sanjmeh Thank you for raising this issue! I can't reproduce it—I'm able to install one version over another on MacOS. What's the version of RStudio Desktop that you're trying to overwrite? I can try with the exact same configuration that you have.

**Comment by sanjmeh** [comment]
Finally I managed to solve this my going inside my mac's settings -> Privacy & Security and allowing the blocked rstudio (it said rstudio instllation was blocked as it was form an unverified developer. Install Anyway? I said yes. 

To be noted, Apple had blocked rstudio that was downloaded from the official rstudio webiste. Perhaps it is time to get apple certificate.
