### ISSUE TITLE
C autocompletion fails in projects containing mixture of C / C++ source

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11852]
### System details

    RStudio Edition : 2022.08.999-dev+999
    RStudio Version : Server [Open Source]
    OS Version      : macOS Monterey 12.5.1
    R Version       : R Under development (unstable) (2022-08-19 r82730)

### Steps to reproduce the problem

Open a project containing a mixture of C / C++ code -- for example, https://github.com/r-lib/vctrs.

Then, open one of the C files in that project (say, `src/altrep-rle.c`), and try to edit one of the functions. Press Tab, or Ctrl + Space, to request completions.

### Describe the problem in detail

No completions are made available. In addition, the log fills up with errors:

> 2022-08-26T19:08:38.524711Z [rsession-kevin] ERROR Error parsing translation unit /Users/kevin/r/pkg/vctrs/src/altrep-rle.c; LOGGED FROM: rstudio::core::libclang::TranslationUnit rstudio::core::libclang::SourceIndex::getTranslationUnit(const std::string &, bool) src/cpp/core/libclang/SourceIndex.cpp:302

### Describe the behavior you expected

Autocompletion should work in such projects.

cc: @DavisVaughan

---

<details>

<summary>Session Info</summary>

``` r
R Under development (unstable) (2022-08-19 r82730)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.0  tools_4.3.0     rstudioapi_0.14
```

</details>

**Comment by romainfrancois** [comment]
This does fix it for me: 

https://user-images.githubusercontent.com/2625526/187230413-709b5919-cf45-46dd-8197-0717d60686de.mov

**Comment by romainfrancois** [comment]
Verified in RStudio 2022.11.0-daily+153 "Elsbeth Geranium" Daily (7c6b84d958459738b0e8d5ae1c227573c2dfc98c, 2022-08-29) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+153 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36
