### ISSUE TITLE
Background job paralyzes RStudio when there are too many prints

### ISSUE THREAD

**Issue by dipterix** [rstudio/rstudio#11854]
When background job has too many prints, trying to open the job to see the details hangs RStudio.

This happens on the latest OSX, RStudio, and R (all updated today). I bet this will happen as well on other OS

**Comment by ronblum** [comment]
@dipterix Thank you for raising the issue! A few things:

1) Do you have a sense for how much output is necessary before RStudio hangs?
2) Can you provide a simple example that causes the problem? This will help us to try to reproduce the issue.
3) What are the version numbers for the different components? 

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 


Thanks!

**Comment by dipterix** [comment]
Hi @ronblum ,

1. The script I used was a auto-processing script. I don't know exactly how long, but it's printing out 2~10 lines of messages every second, and usually I cannot open that job tab after about 5min. 
2. RStudio does not hang automatically. It hangs when the background job tab is active and when I try to look the latest printed out messages. Try just print out lots of random messages in a job. While it's running, go back to job-list, and re-enter that job to check the messages. RStudio should hang or at least glitch

```
RStudio Edition : Desktop
RStudio Version : 2022.07.1 Build 554
OS Version      : OSX Monterey (tried on M1, M2, and x86)
R Version       :  4.2.1
```

Try run the following script in background jobs for 3min. It took me 10s to open 

```r
while(TRUE){cat(dipsaus:::rand_string(79), "\n"); Sys.sleep(0.01)}
```

RStudio becomes so slow opening the job details that I was able to capture this screenshot easily: UI just stuck there

<img width="671" alt="image" src="https://user-images.githubusercontent.com/8163576/190884980-19835d19-d20e-4e9b-9f69-c3bdc7ee0b51.png">

**Comment by dipterix** [comment]
Bump. 

@ronblum I don't think this issue should be marked with `info needed` and gets ignored (personally think... I know you are probably very busy doing all other things). I have provided all the requested information. The issue & pursuit is very simple: only show limited number of latest messages (say 1000) in the job so the RStudio does not have to spend lots of time trying to render all 100000+ messages. We have a server with 700+GB RAM and yet RStudio server cannot render that many messages...

The reason why users choose to use the background job sometimes just because the job takes long to run. Imagine if you have a shiny app or a pipeline that need to run for minutes/hours, it's very natural to run them as background jobs (alternatively you could use terminal commands, but you are pretty comfortable with RStudio and would love to stay with it, or you are running on  RStudio server and running as background job is the only option). 

Since the job need to run for very long, it dumps bunch of outputs. Normally the outputs are not that important if the results are fine. However, one day you leave the job in background for other things, while coming back realizing the pipeline was bugged. Now to fix the bug, you really want to know what the last words was said by the process. Unfortunately the process had printed too many messages and RStudio cannot render all of these messages at all. It's really frustrating and you have to run the same code in terminal for another hours in order to find the bugs.

**Comment by kevinushey** [comment]
I think this is worth fixing, but a minimal reproducible example would be useful here.

**Comment by dipterix** [comment]
Hi @kevinushey thanks : ) I just checked the newest RStudio, and I think this issue has been fixed. Now the `Background Job` only displays the most recent 500 lines of outputs. Old messages are hidden automatically so that background jobs don't hand the application anymore. This is exactly what I was asking for.

Also thanks @ronblum for fixing this issue. Please feel free to close this ticket.

Here's the code that I used for testing:

```r
dipsaus::rs_exec({
  rand_string <- function(length = 50){
    paste(sample(c(letters, LETTERS, 0:9), length, replace = TRUE), collapse = '')
  }
  i <- 1
  while(TRUE){cat(i, rand_string(79), "\n"); Sys.sleep(0.01); i <- i+1}
})

```

**Comment by kevinushey** [comment]
Thanks @dipterix for taking the time to check!  Please let us know if you encounter any other issues.
