### ISSUE TITLE
Loads of empty space below code chunk in editor mode

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#11859]
Like #11858 I know this is the dev version so let me know if these reports are not useful, but just discovered this unwanted behavior in a chunk in visual editor mode, best communicated in the GIF below. Happy to point you to the source code if anyone wants to reproduce this, thanks for great Visual Editor functionality which is coming together and apologies again for brief report.

![Peek 2022-08-28 22-20](https://user-images.githubusercontent.com/1825120/187095009-7275a242-a8df-4f89-9ad6-eab27788b88f.gif)

**Comment by kevinushey** [comment]
If you could share the source code, or a reproducible example, I think that would be helpful. Thanks!

**Comment by Robinlovelace** [comment]
Sure, here's the Rmd: https://github.com/Robinlovelace/geocompr/blob/main/13-transport.Rmd

**Comment by ronblum** [comment]
@Robinlovelace Thanks! And reports on the dev version are very useful, so we appreciate it.

**Comment by Robinlovelace** [comment]
Think this is fixed. now.
