### ISSUE TITLE
Outline text not readable with dark theme

### ISSUE THREAD

**Issue by djhocking** [rstudio/rstudio#11868]
### System details

    RStudio Edition : Server
    RStudio Version :  2022.07.1 Build 554 ("Spotted Wakerobin" Release (7872775e, 2022-07-22) for RHEL 8)
    OS Version      :  Linux RHEL 8.6 (Ootpa)
    R Version       :  4.2.1 (2022-06-23)

### Steps to reproduce the problem

Login to RStudio Server on Google Chrome and select a dark theme.

### Describe the problem in detail

When I change to a dark theme the document outline text does not change to white/light so it's unreadable. The problem does not go away after switching back and forth or after logging out of and back into the server.

![light_theme](https://user-images.githubusercontent.com/2981696/187481228-b8029de7-54f0-4dba-b35c-db3c778752e0.PNG)

![dark_theme](https://user-images.githubusercontent.com/2981696/187481262-ec728c35-1cf5-477a-9a9a-45a20e4ff78e.PNG)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists. **I cannot request our admin to install a newer version on our server unless I have justification such as this fix)**
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks; I was able to reproduce as well. I'll take a look.

**Comment by kevinushey** [comment]
For QA: we should see if this issue is now reproducing more readily with the latest releases of Chrome (or perhaps other browsers) as it's possible that the issue is seen only with newer releases of Chrome / Chromium-based browsers.

**Comment by ronblum** [comment]
Verified in RStudio Server 2022.11.0-daily+187 on MacOS 13 via
- Chrome Version 105.0.5195.125 (Official Build) (x86_64)
- Firefox 104.0.2 (64-bit)
 
using several dark themes:
- Cobalt
- Chaos
- Dracula

Continues to work in light themes.

**Comment by djhocking** [comment]
Awesome, thanks!

**Comment by ronblum** [comment]
@djhocking You're welcome—and if you still see issue in this if you give one of the current development builds a try, let us know!

**Comment by t-holda** [comment]
I am having the exact same issue in RStudio for windows version 2022.12.0 with R version 2022-10-21 ucrt.  How do I fix this?

**Comment by gse-cc-git** [comment]
@ronblum I have the issue with RStudio 2024.04.0-daily+475 "Chocolate Cosmos" Daily (08d8e552019bf123e310ad5725dc6826020530bf, 2024-02-22) for Ubuntu Jammy Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.0-daily+475 Chrome/120.0.6099.276 Electron/28.2.2 Safari/537.36, Quarto 1.4.550

**Comment by kevinushey** [comment]
@gse-cc-git can you please open a new issue with more details?

**Comment by gse-cc-git** [comment]
@kevinushey  At the first launch after "chocolate cosmos" install, the outline was too dark.
A reboot solved the issue: outline text is now white on dark background. Sorry for the invocation. Thx
