### ISSUE TITLE
Update Quarto usage to point to native executable

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#11873]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.11.0-daily-153
    OS Version      : Windows
    R Version       : N/A

### Steps to reproduce the problem
Quarto 1.1.163 has included a native executable 

### Describe the problem in detail
Quarto now provides a native executable to run it. The old `quarto.cmd` is still available for compatibility but we should be using `quarto.exe`.

### Describe the behavior you expected
Quarto is run using the native executable.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
I think this was already verified, as it was done in Spotted Wakerobin patch 2 #11874. Doesn't hurt to retest, though. 

- Check what happens both with and without the Quarto standalone CLI installed.
- Curious: What happens if `quarto.cmd` is removed?

**Comment by ronblum** [comment]
Actually: @jgutman and @timtmok should this be moved to `test` status? Or was this done only in the patch but not yet in Elsbeth Geranium?

**Comment by timtmok** [comment]
https://github.com/rstudio/rstudio/pull/12090
JJ has confirmed that his PR addresses this. Quarto rendering will still work if `quarto.cmd` is removed. I believe Quarto still includes it (still in their code but I haven't checked the package) since they'll want to support users that upgrade Quarto but still use Spotted Wakerobin or older.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+240
Windows 11, Ubuntu 22.04

Quarto version 1.2.186 correctly installed.  Ran several tests specified in #11874 as well.
