### ISSUE TITLE
UI to display and manage multiple plots (not using code)

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#11878]
Hello,

I think it would be useful to be able to display multiple plots at the same time.
I know that there are multiple R-based solutions for side-by-side plotting, but it would be useful to have a non-code-based approach which would offer more flexibility for data-checking tasks, especially when one wants to compare the actual plot with previous ones.

A few solutions I thought of:
- allow the opening of multiple plots in new windows. Instead of the current extra window which is in sync with what's in the plot, would it be possible to have independent windows like it is now for source files and datasets?
- In addition, it would be nice to have a plot manager/preview mode so that one can have a glance at all plots stored in the index, without having to go through all of them each time to look for a specific one, since each of them can take a while to render. A simple approach could be to store fixed-size, low-dimension raster thumbnails (using the current plot tab aspect ratio) to avoid rerendering and show them all in a new window where users can select them (to display in the plot tab or in an external window), change the order or delete them.

Thanks!

**Comment by ronblum** [comment]
@bakaburg1 Thank you for the suggestion, and the detailed thoughts about possible solutions! We'll review this as part of our ongoing development of RStudio.
