### ISSUE TITLE
Custom themes: `.ace_gutter-active-line` doesn't work

### ISSUE THREAD

**Issue by julian-urbano** [rstudio/rstudio#11877]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      :  Windows 10
    R Version       :  4.2.1

### Steps to reproduce the problem

Edit a custom rstheme with the following (ugly colors for illustration purposes):

```{css}
.ace_marker-layer .ace_active-line {
  background: yellow;
}
.ace_gutter-active-line {
  background-color: red;
}
```

Selector `.ace_gutter-active-line` is documented [here](https://rstudio.github.io/rstudio-extensions/rstudio-theme-creation.html):

<html>
<body>

.ace_gutter-active-line |   | Changes the color and style of the gutter at the active line in the editor.
-- | -- | --

</body>
</html>

Option `Highlight selected line` is enabled under Global Options / Code / Display.

### Describe the behavior you expected

I expected 1) the selected line to have a yellow background, and 2) the gutter at that line to have a red background. However, as shown below, only 1) works. No change in the style of `.ace_gutter-active-line` seem to work, actually.

![image](https://user-images.githubusercontent.com/6097978/187540780-8998b5e3-ac7a-4ffd-af2e-343adc6b0aac.png)

An inspection of the DOM shows that the `<div>` at that gutter line does _not_ have class `.ace_gutter-active-line` as expected:

![image](https://user-images.githubusercontent.com/6097978/187541312-0e48c499-f502-453e-bb06-d2aafad7a3df.png)

The demo ACE editor at <https://ace.c9.io/> does work properly, so I'm guessing this is an option to configure somewhere in the editor?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
It looks like it was disabled here:

https://github.com/rstudio/rstudio/blob/f2c427e6dcbb3a5a707b4baba7040168f7d9dbeb/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java#L111

**Comment by julian-urbano** [comment]
Ah, good that you found it. For what is worth, the reason I was playing with it is that when searching within a document it's nearly impossible with some themes to see where the matches are because of lack of clear clues (lack of contrast). Highlighting the gutter of the active line would help with that.

**Comment by romainfrancois** [comment]
I'll have a look at making this an option.
