### ISSUE TITLE
Consider `.quartoignore` as special hidden file like `.Rbuildignore` and other special ones

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#11881]
From https://github.com/quarto-dev/quarto-cli/discussions/2232

Currently `.quartoignore` file only visible when Show hidden file is activated. 

This file is used for creating custom formats for Quarto (https://quarto.org/docs/extensions/formats.html#format-templates) and it could benefit being shown as default without the special switch. 

Opening this feature request to track the idea, and collect 👍

**Comment by kevinushey** [comment]
We could add to the list here:

https://github.com/rstudio/rstudio/blob/dd22e38fe8b69858a2f730235c0122cfda34bc46/src/cpp/session/resources/schema/user-prefs-schema.json#L974-L997

Marking as EG as it's a one-line change.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.11.0-daily+187 on MacOS 13
- RStudio Server 2022.11.0-daily+187 on Ubuntu 20.04 via Chrome on MacOS 13

Tested that `.quartoignore` is always present
- In Quarto projects and not in a project
- When hidden files are set both to show and hide
