### ISSUE TITLE
Mark unused libraries

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [rstudio/rstudio#11890]
Hello!
to my knowledge it is not yet possible to see just from the color of the imported libraries whether they are actually used in the script. By used I mean whether at least one function or object from the library is in use. If the library is not in use in a script, the color of the library should then be turned slightly towards a more grey tone. 
I have enjoyed this feature in other IDEs with other languages and I think that it is almost indispensable for cleaning up ones code. 

I researched solutions to see which libraries a script uses for R and really didnt find anything comparably practical. So this would be it, in my opinion. 
Thank You!

**Comment by ronblum** [comment]
@GitHubGeniusOverlord Thank you for the suggestion! I'll mark it for review as we continue development of RStudio.

By the way, excellent username. 👍
