### ISSUE TITLE
JavaScript error in recent daily build

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#11898]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.11.0-daily+152 "Elsbeth Geranium" Daily (76b7296e3f600fd339dd7e6024803dd6fc405dec, 2022-08-30) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+152 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36
    OS Version      : Windows 11
    R Version       : 4.2.1

### Steps to reproduce the problem

I'm not certain what the steps are.  I was in the debugger (`options(error=recover)`), and I tried to open a file.

### Describe the problem in detail

I saw this error message.  And, R and the Rstudio windows became unresponsive.  After clicking off of the window below several times, I was able to get back to a responsive session (which I then quit and restarted).

![image](https://user-images.githubusercontent.com/10359931/188247612-97aeafe8-28a0-4ac4-b3a7-e4d731874026.png)

Here is the diagnostic report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9481527/diagnostics-report.txt)

### Describe the behavior you expected

The session continued to respond.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@billdenney Thank you for raising this and for including the diagnostics report! Has this occurred just one time or does it regularly recur?
