### ISSUE TITLE
Cannot find file when generating diagnostic report

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#11897]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.11.0-daily+152 "Elsbeth Geranium" Daily (76b7296e3f600fd339dd7e6024803dd6fc405dec, 2022-08-30) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+152 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36
    OS Version      : Windows 11
    R Version       : 4.2.1

### Steps to reproduce the problem

Click on Help Menu -> Diagnostics -> Write Diagnostics Report

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/10359931/188247793-0719e5a1-e1fe-4d6c-bd4e-cfe176b0e4df.png)

### Describe the behavior you expected

No error window

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@billdenney Thank you for raising this! Judging by #11898, the diagnostics report got generated, is this correct? If so, where did it get written to?

[Ref some other `~` issues on Windows: #11635, #11712, #11888. Not sure if they're directly related.]

**Comment by billdenney** [comment]
Yes, it was generated.  It was written to `C:/Users/wdenn/Documents/rstudio-diagnostics/diagnostics-report.txt`.  The other issues seem to be related, but it is not clear to me if any of them are identical to this.

**Comment by billdenney** [comment]
This still applies with:

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Comment by gtritchie** [comment]
Ah, sorry, I had opened a duplicate issue and the fix is tracked there. ["Write Diagnostics Report" command doesn't show report in Finder/Explorer #12570](https://github.com/rstudio/rstudio/issues/12570).
