### ISSUE TITLE
error installing and updating packages:  could not find function "setClassUnion"

### ISSUE THREAD

**Issue by splaisan** [rstudio/rstudio#11891]
Bioconductor version 3.15 (BiocManager 1.30.18), R 4.2.1 (2022-06-23)
RStudio 2022.07.1 Build 554

Dear support

I am experiencing recurrent issues installing and updating several packages recently (started after upgrading R to 4.2)
This includes "dbplyr", "dplyr", "SeuratObject", "tidytree" and the error is always something with functions that cannot be loaded

eg: tidytree

```
Error in setClassUnion("DNAbin_Or_AAbin", c("DNAbin", "AAbin", "NULL")) : 
  could not find function "setClassUnion"
Error: unable to load R code in package ‘tidytree’
Execution halted
```

I posted on the dplyr and dbplyr github but did not get any help.

Is this something RStudio support can help me fix?

Thanks in advance

**Comment by kevinushey** [comment]
Sorry, the RStudio issue tracker is not for general questions -- we would encourage you to ask your question on the community forums at https://community.rstudio.com.
