### ISSUE TITLE
YAML Quarto Parse error

### ISSUE THREAD

**Issue by lightbluetitan** [rstudio/rstudio#11893]
Hi guys

Every time I try to add a single keyword in a Quarto YAML document I get a parse error, even not touching the YAML header at all
This just happen with a Quarto Python document.
![image](https://user-images.githubusercontent.com/13672461/188005192-359d7004-d64e-4b83-95b6-bca600b8ebe4.png)

**Comment by kevinushey** [comment]
Are you able to share the document, so we can try to reproduce ourselves?

Do you see this if you close the other Quarto documents you have open? (Just in case the parse error is happening in a different document you have open)

You could also try running the following code:

```
trace(yaml::yaml.load, quote(print(rlang::trace_back())))
```

and see if you get more information about where the YAML load error is occurring.

**Comment by ronblum** [comment]
@lightbluetitan Can you also provide the following information? Thanks!
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :
