### ISSUE TITLE
mermaid should be shown in visual editor

### ISSUE THREAD

**Issue by battmanux** [rstudio/rstudio#11903]
### System details

    RStudio Edition : Server [Open Source]
    RStudio Version : 2022.7.1.554
    OS Version      : Ubuntu 22.04.1 LTS
    R Version       : R Under development (unstable) (2022-09-03 r82798)

### Steps to reproduce the problem

Create a qmd file, add a mermaid block. save. run the mermaid chunk

```mermaid

%%{init: {'theme':'forest'}}%%

graph TD
  A[Christmas] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  B --> G[/Another/]
  C ==>|One| D[Laptop]
  C -->|Two| E[iPhone]
  C -->|Three| F[fa:fa-car Car]
  subgraph section
    C
    D
    F
    G
  end
```

### Describe the problem in detail

Mermaid diagrams are not shown in visual editor. [play] button is disabled (ctrl-enter still works).

### Describe the behavior you expected

I would like the diagram to be displayed in visual mode (ideally updated live like in notion.so) 

### Workaround

Using htmltools package I can have mermaid diagram displayed by executing this in a previous chunk

```{r}

mmdoc <- "
<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
</head>
<body>
  <div class=\"mermaid\" style=\"text-align: center;\">
  <mmCode/>
  </div>
 <script src=\"https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js\"></script>
 <script>mermaid.initialize({startOnLoad:true});
</script>
</body>
</html>"

knit_mermaid <- function (options) {
  knit_print <- get("knit_print", envir = asNamespace("knitr"))
  engine_output <- get("engine_output", envir = asNamespace("knitr"))
  
  if (identical(.Platform$GUI, "RStudio") )  {
    widget <- htmltools::HTML(gsub(
      pattern = "<mmCode/>", 
      replacement = paste0(collapse = "\n", options$code), 
      x = mmdoc))
  } else {
    widget <- knitr:::one_string(c("```{mermaid}", options$yaml.code, 
    options$code, "```"))
  }
  
  if (identical(.Platform$GUI, "RStudio")) {
    knitr::opts_current$set(engine=NULL)
    print(widget)
    list()
  }
  else {
    code <- options$code
    out <- widget
    knitr:::one_string(
      c(
        if (length(options$echo) > 1L || options$echo)
          c("``` {.r}", options$yaml.code, options$code, "``` "),
        if (options$results != "hide" && !knitr:::is_blank(out) ) {
          c("```{mermaid}", options$yaml.code, options$code, "```")
        }
      )
    )
  }
}

knitr::knit_engines$set(`mermaid`=knit_mermaid)
```

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@battmanux Actually—can you provide a simple example? I'd like to get an idea whether or not this is an enhancement request or a bug.

**Comment by battmanux** [comment]
[mermaid_example.qmd.zip](https://github.com/rstudio/rstudio/files/9501239/mermaid_example.qmd.zip)
