### ISSUE TITLE
Publish Processed Dataset to RPubs

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11901]
Hi. 
I am working on this [publication](http://rpubs.com/jacobidiego/Bellabeat_Preparar_Fitbit_Dataset) which performs some changes to original datasets.
It would be a great feature if I could publish a data-frame contents as a CSV link on Rpubs every time that I publish the changes, so that every related content stays together.

Of course, I am talking about avoiding links to third party websites and commiting directly with rstudio.

**Comment by ronblum** [comment]
@DiegoJArg Thank you for the suggestion! I'm not certain if this would be something in RPubs, the RStudio's publishing, or if it's even feasible, so for now I'll mark it for an initial review.

Triage: Marking as such to determine if this is the right repo.

**Comment by jthomasmock** [comment]
You can use the `xfun` package to embed CSVs with a download link in an existing RMarkdown document.

https://bookdown.org/yihui/rmarkdown-cookbook/embed-file.html

That would allow you to have both the report and dataset in a single "data product".
