### ISSUE TITLE
Every time I add a python chunk in Quarto RStudio CRASH!!!!

### ISSUE THREAD

**Issue by lightbluetitan** [rstudio/rstudio#11908]
Hi guys

every time i try to add a python chunk in a quarto document and render it, RStudio crash for no particular reason, I got the lastest versión of R programming language, RStudio and Quarto, no idea how to solved.
![image](https://user-images.githubusercontent.com/13672461/188460638-4d8de313-c103-4843-a048-ff180691c03a.png)
![image](https://user-images.githubusercontent.com/13672461/188464061-a0155383-3949-4704-a0d3-c8fcff87e148.png)

**Comment by ronblum** [comment]
@lightbluetitan Thank you for raising the issue. Can you please provide the following?

1. What version of Python are you using?
2. What is the location of Quarto, using `Sys.which("quarto")`
3. You environment information:

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by kevinushey** [comment]
In addition, what is the output of (from the RStudio R console):

```
packageVersion("reticulate")
reticulate::py_config()
```

**Comment by lightbluetitan** [comment]
HI Ronblun
This is my system información and once again every time I add a Python chunk to my Quarto document RStudio just crashed, working with Python 3.10.4, but I don't have the same problem working with Anaconda.
![image](https://user-images.githubusercontent.com/13672461/188912322-6efa3925-fe0f-4bff-8628-ee898843ce10.png)
![image](https://user-images.githubusercontent.com/13672461/188912509-78002940-0d33-44f8-b40b-c3443bdfeacd.png)
![image](https://user-images.githubusercontent.com/13672461/188912791-daa3ed67-055d-47ed-ba98-69850b10ea3b.png)
![image](https://user-images.githubusercontent.com/13672461/188913263-ca88a7fa-fe17-4bf6-ab4a-830d43796f6c.png)
