### ISSUE TITLE
Horizontal scroll bar in help pane ignores examples

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#11904]
**Steps to reproduce:**
* Shrink the help pane horizontally.
* Browse the docs for some function having examples with long horizontal lines. Example: `?remotes::install_github`.
* Check the examples section for the function.
* Try to scroll horizontally through the scrollbar at the bottom.

**Expected behavior:** the scrollbar should browse throughout the length of the help pane, including the examples.

**Actual behavior:** the horizontal scroll bar does not apply to the length of the examples section.
![rstudio_no_hscroll](https://user-images.githubusercontent.com/11860098/188331679-c779507e-18ed-4cff-b970-9dcd49ea4886.gif)

**Comment by ronblum** [comment]
Thanks @david-cortes! I see the same behavior in RStudio 2022.07.02+576 and 2022.11.0+166 on MacOS 13. However, it the horizontal scrolling is happening in a block after clicking on the example, as in the example. This is the behavior in the R executable outside of RStudio, so the IDE behavior is expected, replicating R's behavior.
