### ISSUE TITLE
Quarto rendering job not finalized (runs indefinitely)

### ISSUE THREAD

**Issue by quinten-goens** [rstudio/rstudio#11906]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.2 Build 485
    OS Version      :  Windows 10
    R Version       :  R-4.2.1

### Steps to reproduce the problem
Make a Quarto file (.qmd). E.g. use the following content for the file: 

```
---
title: "Quarto Demo"
author: "Test"
date: "2022-5-24"
---
```

Try to render the file by clicking the ''render'' button. Wait until render completed and viewer is changing the HTML file. Click render again.

### Describe the problem in detail
When the rendering of the quarto file is completed the job (see the `jobs` tab) is continuing to run until I manually kill it. If I do not kill it and I want to rerun the rendering I get a popup; 

```
Error
R code execution error.
```

### Describe the behavior you expected

The job would be killed / closed after the rendering is completed automatically. When I click on render again it does not give the error mentioned above. 

Having to kill the job manually every time you render is a nuisance. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you see this issue in the latest release of RStudio, or in the [daily builds](https://dailies.rstudio.com) of RStudio?

**Comment by quinten-goens** [comment]
I will check and let you know.

**Comment by quinten-goens** [comment]
I checked on RStudio 2022.07.2 and there this is no longer an issue.

**Comment by BartJanvanRossum** [comment]
I have the exact same issue with a recent version of RStudio, except that I don't get the error message mentioned above. I can just rerender the qmd, but the background jobs keeps running forever.

```
RStudio Edition : Desktop
RStudio Version : RStudio 2022.12.1+363 "Elsbeth Geranium" 
OS Version      :  Windows 10
R Version       :  R-4.2.2
 ```
