### ISSUE TITLE
Unable to insert links or images using rstudioapi::selectionSet outside chunks in visual mode

### ISSUE THREAD

**Issue by battmanux** [rstudio/rstudio#11909]
### System details

    RStudio Edition : Server [Open Source]
    RStudio Version : 2022.7.1.554
    OS Version      : Ubuntu 22.04.1 LTS
    R Version       : R Under development (unstable) (2022-09-03 r82798)

### Steps to reproduce the problem

create a qmd file with this md content:
```
# My shiny app helps me create links

When I select www.foo.com, my shiny app converts it into a link
```
Switch to visual mode
select www.foo.com

execute this code:
```r
rstudioapi::selectionSet("[foo](https://www.foo.com)")
```

### Describe the problem in detail

[ and ( characters are escaped when converted to md souce editor (non visual). I cannot insert links, images, tables or any advanced things...

### Describe the behavior you expected

I would expect to see a link for foo in visual mode.
There should exists an insert mode that inserts in the corresponding markdown source code even when I am in visual mode.

# Workaround

Right now I have to switch to source mode to execute my helper tool and then switch back to visual.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@battmanux Thank you for raising this! I can reproduce this in RStudio Desktop 2022.11.0+167 on MacOS, as well. The end result in the source editor is
```
\[foo\](https://www.foo.com)
```

@jjallaire Is this something that we have control over?
