### ISSUE TITLE
Unable to write inline R code to access values from lists in visual editor

### ISSUE THREAD

**Issue by rbcavanaugh** [rstudio/rstudio#11902]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.7.1.554
    OS Version      :  macOS Monterey 12.5 (aarch64-apple-darwin20 (64-bit))
    R Version       : 4.2.1 (2022-06-23)

### Steps to reproduce the problem

1. Open new .rmd document, delete template code
2. Change to visual mode
3. Fit a model

````
```{r}
library(broom)
model <- lm(mpg ~ cyl, data = mtcars)
model_tidy <- tidy(model, conf.int = TRUE)
model_list <- split(model_tidy, model_tidy$term)
```
````

4. Attempt to access model results in list for reproducible inline reporting. 

\`r model_list$cyl$p.value`

### Describe the problem in detail

<img width="853" alt="image" src="https://user-images.githubusercontent.com/46727239/188328556-3b10017b-2967-4f1a-8559-494f0c360ca8.png">

Knitting the .rmd produces the following error: 
```
Error: Failed to parse the inline R code: model_list$cyl$p.value\ (Reason: <text>:1:23: unexpected '\\'
1: model_list$cyl$p.value\
                          ^)
Execution halted
```
Changing to source editor reveals the visual editor has added backslashes before backticks. Removing the ticks, and switching back to visual editor resolves the issue. I'm not sure but perhaps this is related to #9495. 

### Describe the behavior you expected

I was expecting to be able to use \`r \` to run inline R code in the visual editor. Perhaps there is a different way to insert inline R code in the editor I'm not aware of. Thanks as always!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@rbcavanaugh Thank you for raising this! Does this happen only when pasting the inline code, or also when typing it out starting with the first back tick?

**Comment by rbcavanaugh** [comment]
This occurs for me when I'm typing this out - it's fine up to this point:  \`r model_list$cyl but as soon as I add the second $, it switches to inline math (dollar signs turn green). Then as soon as I continue to \`r model_list$cyl$p, "cyl" is formatted in italics. 


https://user-images.githubusercontent.com/46727239/188730882-50281340-e594-4f40-ba55-68b13f8e6dcb.mov

**Comment by mikebessuille** [comment]
@jjallaire in this case, the visual editor is not allowing the user to type an inline code chunk; in this example, when using something between two $  - it's converted to LaTeX syntax when the second $ is typed.  It's not being interpreted as code.

@rbcavanaugh the workaround is to type the inline code in source mode.  Alternatively, to remove the escape \ from the start and end of the ` inline code.

**Comment by rbcavanaugh** [comment]
Thanks! I'm happy to use source mode or escape - it's what I'm used to. I just figured it might be helpful to point out the bug.

**Comment by jthomasmock** [comment]
Or you can type the full string out and then make it `code`.


https://user-images.githubusercontent.com/29187501/191041364-7552ed50-ba16-42dd-afc9-a37197aadc44.mp4

**Comment by jjallaire** [comment]
This should be fixed here: https://github.com/quarto-dev/quarto/commit/d81cfd01ea878075b81fbe3c02d37e37b63129f8

This fix means that if you want inline math that does not have a preceding space you need to explicitly insert it (rather than depending on our auto-recognizer).

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+312. 

![Image](https://user-images.githubusercontent.com/31009952/218545294-00126404-279b-4eb2-8760-d58e2c89b8a2.png)

Also confirmed the behavior change regarding inline math.
