### ISSUE TITLE
Use Lithuanian spellcheck dictionary from RStudio 1.2 again

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#11918]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.7.1.554
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

1. Download all additional spellcheck dictionaries via RStudio's Spelling options
![image](https://user-images.githubusercontent.com/12725868/189220816-a9c04401-a563-4927-96a4-17952040addb.png)
2. Choose the Lithuanian dictionary.
3. Use the dictionary and real-time spell checker to check Lithuanian text.

### Describe the problem in detail

Many correct Lithuanian words are identified as incorrect with the Lithuanian dictionary used in the current RStudio version. This was not the case with the spelling dictionary used in (if I recall correctly) RStudio 1.2 (before a real-time spell-checker was introduced in RStudio). Can RStudio use the older and better version of the Lithuanian dictionary again?

### Describe the behavior you expected

Correct Lithuanian words should be identified as correct again.

**Comment by ronblum** [comment]
Thanks @GegznaV! Can you provide a few examples of words that aren't getting marked incorrectly? I'd like to check if the dictionary we used before is also identifying them as correctly spelled.

**Comment by GegznaV** [comment]
@ronblum, there are 2 lt_LT dictionaries used in the examples below: the old one and the current one. You can compare yourself. These are print screens from Rmd documents in RStudio.

NOTE: even better (than these two) lt_LT dictionary would be preferred as none of the words should be marked as incorrect. Would this be possible? If not, for this time the old lt_LT dictionary would be a huge improvement.

![image](https://user-images.githubusercontent.com/12725868/192784465-253b73bb-1019-4ffd-9e9e-167c1226108d.png)

![image](https://user-images.githubusercontent.com/12725868/192784854-2b716931-bfb7-4751-8ca6-abdd1ecdb6cd.png)

<details><summary>Text to copy</summary>

Šviesūs. Žalsvi. 

Lietuvoje yra maždaug 2600–2800 natūralių ežerų plotu didesnių nei 0,5 ha (LR upių, ežerų ir tvenkinių kadastras[1] nurodo 2610, LR ežerų klasifikatorius[2] – 2790). Jų bendras plotas – 880 km².[3] Šalyje taip pat yra virš 3100 mažesnių (0,05–0,5 ha ploto) natūralios kilmės ežerėlių [4], tačiau bendras jų paviršiaus plotas tesudaro 5,34 km². Dalį mažųjų ežerų sudaro ... bei karstinės kilmės vandens telkiniai, kurių skaičius nuolat kinta, todėl tiksliai įvertinti jų skaičiaus neįmanoma.[5] Visi ežerai užima apie 1,37 proc. Lietuvos teritorijos ploto. Be to, šalyje yra apie 1100 dirbtinių tvenkinių, kurie didesni nei 0,5 ha[1].

Daugiausia ežerų yra Baltijos ir Žemaičių aukštumose, Dainavos ir Neries-Žeimenos žemumose. Ypač ežeringa sritis – Baltijos aukštumų lanko šiaurinė dalis – Aukštaičių aukštuma. Ten susidarę ištisi ežerynai: Molėtų, Dubingių, Zarasų. Aukštaičių aukštumoje telkšo didžiausi, giliausi, ilgiausi (Asveja, Sartai) ežerai šalyje. Dzūkų aukštumose ežerų grupės mažesnės. Ten susidarę Trakų, Aukštadvario ežerynai bei didžiųjų ežerų grupė. Žemaičių aukštumoje tekšo dideli Platelių, Germanto ežerai. Dainavos žemumoje driekiasi Veisiejų ežerynas, o Neries-Žeimenos žemumoje – Ignalinos ežerynas. Didžiausias ežeringumas (>11 %) yra šalies šiaurės rytuose, Ignalinos ir Zarasų rajono rytinėje dalyje. Mažiausiai ežerų yra Lietuvos Vidurio žemumoje (<0,5 %) ir Pajūrio žemumoje. Dauguma ežerų telkšo 100–160 m aukštyje virš jūros lygio.

</details>

The text is modified from https://lt.wikipedia.org/wiki/Lietuvos_e%C5%BEerai

**Comment by GegznaV** [comment]
@ronblum, will this issue be solved soon?

**Comment by ronblum** [comment]
@GegznaV Sorry for the delay. I just took a deeper dive. It looks like we're not handling letters with diacritics correctly, and many words have letters with carons/háčeks, such as `ž`. The words are in the lt_LT.dic dictionary, though. For example,
   ežeringumas
is in the dictionary file as
   eļæ½eringumas/D

I looked at older versions of RStudio Desktop (1.0.153 and 1.2.5042) but I'm getting the current dictionary, which isn't helpful.

1) @GegznaV: Are you able to look at the older dictionary file and see what's encoded in there for ežeringumas? I just searched it for the string `ringumas` to stick to the ASCII portion of the word.
2) Triage: Raising this as a candidate for Cherry Blossom because the spellcheck is no longer very useful. I wonder if this is happening with other dictionaries in which a combination of characters is used to represent one letter.

**Comment by GegznaV** [comment]
I saved the dictionary from the older version of RStudio locally:

[lt_LT.zip](https://github.com/rstudio/rstudio/files/9872433/lt_LT.zip)

Notepad does not show any encoding issues with "ežeringumas" (in English this means "lacustrine", I hope):

![image](https://user-images.githubusercontent.com/12725868/198100797-8f8f5819-86f1-4b28-8001-5cbf8b0a61bc.png)

**Comment by GegznaV** [comment]
Any chance this issue could be solved soon?

**Comment by GegznaV** [comment]
It seems that just replacing the currently broken dictionary with the old one is an extremely easy fix. (Do I miss something here?)

> I looked at older versions of RStudio Desktop (1.0.153 and 1.2.5042) but I'm getting the current dictionary, which isn't helpful.

@ronblum This dictionary does not install with RStudio and is downloaded from the cloud on request. So most probably the version on the cloud was changed. As I understand, this fix should not be related to any particular RStudio version and can be done at any time on the cloud. 
Once again, I add the dictionary I downloaded to the previous RStudio version, in case it lost between the messages:
[lt_LT.zip](https://github.com/rstudio/rstudio/files/9872433/lt_LT.zip)

So what is the status of this issue?

**Comment by kevinushey** [comment]
Sorry for taking so long to follow up. It looks like the encoding of that particular dictionary got messed up somehow; I'm not sure what happened. I'll see if we can re-generate the dictionary files.

**Comment by kevinushey** [comment]
Sorry for the delay -- I have finally updated the Lithuanian dictionaries. If you update your dictionaries locally, you should hopefully see the correct result. (You may need to re-open any currently-open R Markdown files to see the changes take effect.)

For testing, I tried copying a blurb from the Lithuanian Wikipedia front-page and pasted it into an R Markdown document.

<img width="478" alt="image" src="https://github.com/rstudio/rstudio/assets/1976582/81152529-bd26-4212-9d0c-611c023dba57">

**Comment by ronblum** [comment]
@GegznaV Would you be willing to try this out?

**Comment by GegznaV** [comment]
Now Lithuanian spellchecking looks better than before:

![image](https://github.com/rstudio/rstudio/assets/12725868/8532941a-816a-4e1a-85e5-742c87f2f2c2)

It would be nice to have an even better Lithuanian dictionary. But the original issue seems to be solved.

Thank you for fixing this, @ronblum and @kevinushey.

**Comment by kevinushey** [comment]
Thank you for your patience -- I'm sorry it took so long on our end to resolve this.

**Comment by ronblum** [comment]
Included this in #15792 (updating Hunspell dictionaries) to search for a regression.
