### ISSUE TITLE
electron clipboard handing breaks visual editor copy/paste

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#11922]
Copy and paste of HTML content in the visual editor is broken within the Electron version of RStudio. This is a massive regression in capability and is not something we can ship the product with. The issue is that only text formats are placed on the clipboard during a copy. Here is the contents of the Clipboard Viewer when copying a heading and a paragraph in the Electron version:

![Screen Shot 2022-09-09 at 7 37 41 AM](https://user-images.githubusercontent.com/104391/189341564-9b0276e3-80e5-480b-bc4e-71aaeb628ac3.png)

Here are the contents of the clipboard under the Webkit version (note that even the text version delineates between the heading and paragraph whereas the Electron version does not):

![Screen Shot 2022-09-09 at 7 39 41 AM](https://user-images.githubusercontent.com/104391/189341982-92d06e52-e158-4f17-8897-7825013c949c.png) 
![Screen Shot 2022-09-09 at 7 39 51 AM](https://user-images.githubusercontent.com/104391/189342051-dde1a159-01b6-4d2b-9be2-e4ae7c9d6e55.png)

**Comment by ronblum** [comment]
Just confirming when and where it doesn't work: All of Qt works, all of Electron fails.

Problem reproduced in Electron:
- RStudio Desktop 2022.07.0+548, 2022.07.2+576, and 2022.11.0-daily+169

Works correctly in Qt:
-  022.07.0+548, 2022.07.2+576.pro5, 2022.11.0-daily+167.pro4

**Comment by ronblum** [comment]
Triage: consider for Spotted Wakerobin patch.

**Comment by jjallaire** [comment]
I don't think you need this for a patch b/c the problem only occurs in Electron (which isn't GA in SW as far as I know?)

**Comment by jmcphers** [comment]
SW included a GA preview of Electron. https://www.rstudio.com/products/rstudio/download/preview/

**Comment by kevinushey** [comment]
Should be fixed with https://github.com/rstudio/rstudio/commit/c3d218f94ac6b48fe5668bd917f3929067ec1675 -- presumedly the issue only affects macOS and not other platforms?

**Comment by kevinushey** [comment]
IMHO this doesn't meet the bar for a patch release of the SW preview. We can instead direct users to download the latest daily builds and consider an updated EG preview in October.

**Comment by timtmok** [comment]
> Should be fixed with [c3d218f](https://github.com/rstudio/rstudio/commit/c3d218f94ac6b48fe5668bd917f3929067ec1675) -- presumedly the issue only affects macOS and not other platforms?
Yes, I think that's the right fix. I had the same thing locally. I'll push some unit tests as well.

**Comment by ronblum** [comment]
Verified that this works correctly by copying and pasting parts of a document that contain different format levels and code chunks. Checked for fix in Electron, and Qt + RStudio Server to check for regressions. Works correctly in all:

- RStudio Desktop 2022.11.0-daily+187 (Electron)
- RStudio Desktop Pro 2022.11.0-daily+174.pro2 (Qt)
- RStudio Workbench 2022.11.0-daily+187.pro2
