### ISSUE TITLE
Stuck on Initializing R after crash

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#11920]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.11.0-daily+165
    OS Version      : Windows 11
    R Version       : 4.2.1

### Steps to reproduce the problem

1. git clone the current version of gt: git@github.com:rstudio/gt.git
2. Start an Rstudio session
3. `devtools::load_all()`
4. `?tab_footnote`

### Describe the problem in detail

I see this:

![image](https://user-images.githubusercontent.com/10359931/189245354-89120e58-7690-4888-8886-3bb26c6ae712.png)

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9531308/diagnostics-report.txt)

There seemed to be an issue with having another session open.  When I closed Rstudio and restarted without another session open, there was no problem.

### Describe the behavior you expected

Seeing the help for tab_footnote

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@billdenney Thank you for raising the issue! I can't reproduce it though, even with the repository referenced above. Would you mind doing a screen recording to show what you're experiencing? It would help to understand if I'm following your steps correctly.

**Comment by billdenney** [comment]
I've not experienced the issue again since this.  I'll reopen with a reprex, if I find it.
