### ISSUE TITLE
Files pane address bar should remain available when entering Home directory

### ISSUE THREAD

**Issue by hutch3232** [rstudio/rstudio#11926]
When I am working in RStudio interactively, I love being able to click around to different directories via the Files pane's address bar, where each level in the path is clickable:
![image](https://user-images.githubusercontent.com/53956863/189395747-70d5b039-142b-4b68-aa82-4d8aa727888e.png)
This makes it very easy to jump around.

However, when entering into the Home directory (`Sys.getenv("HOME")`), the path disappears and turns into a button. Entering into folders nested to Home then show as a reference to Home, rather than the full file path.
![image](https://user-images.githubusercontent.com/53956863/189396242-3c9140d7-f4aa-4a01-aafe-fa91139e5295.png)
![image](https://user-images.githubusercontent.com/53956863/189396337-47c7c4ea-5335-42a6-92ed-2d2cbf2f198d.png)

That makes it a little tedious to get back out of the Home directory. You have to go to the `...` button and type in the path you want to navigate to.
![image](https://user-images.githubusercontent.com/53956863/189397246-07acb002-bf27-4ffe-aecd-51976add4a1a.png)

I think one possible solution to this would be to always display the full path, even when in the Home directory. There could even be a Home button in the row above (the one with New Folder), similar to how it looks in the Help pane:
![image](https://user-images.githubusercontent.com/53956863/189397080-6abac4ab-f1e8-4dfb-afe1-559068f96758.png)

Note that this same behavior occurs in RStudio Server but the screenshots above are from the Desktop version.

**Comment by ronblum** [comment]
@hutch3232 Thank you for the suggestion! It makes sense, as sometimes it's desirable to see everything as relative to home, and other times it's handier to always see the breadcrumbs for the full path. I'll mark this request for review as we continue development of RStudio.

**Comment by hutch3232** [comment]
Hi @ronblum, I was wondering if there had been a discussion on this suggestion yet? Mainly commenting so that it isn't auto closed since i think it is still a valid issue. Thanks!
