### ISSUE TITLE
Cannot show document in new window

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [rstudio/rstudio#11921]
### System details

```
> sessioninfo::session_info()
- Session info --------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  German_Germany.1252
 ctype    German_Germany.1252
 tz       Europe/Berlin
 date     2022-09-09
 rstudio  2022.11.0-daily+170 Elsbeth Geranium (desktop)
 pandoc   NA

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date (UTC) lib source
 cli           3.3.0   2022-04-25 [1] RSPM
 rstudioapi    0.14    2022-08-22 [1] RSPM (R 3.6.3)
 sessioninfo   1.2.2   2021-12-06 [1] RSPM

 [1] C:/Users/[censored]/R/R-3.6.3/site-library
 [2] C:/Users/[censored]/R/R-3.6.3/library

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
### Steps to reproduce the problem

1. Open a document
2. Show document in new window

### Describe the problem in detail

- JavaScript error window 
![grafik](https://user-images.githubusercontent.com/89191115/189320399-4199fa7c-e862-4629-a340-62a756c9bf40.png)

- Previously opened document is closed

### Describe the behavior you expected

- Document is shown in a new window
- last known 'good' daily build is 169

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks! Should be fixed up now and fixes should be arriving in the next builds.

**Comment by HenningLorenzen-ext-bayer** [comment]
@ronblum Checked with [173](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows/2022-11-0-daily-173/), works fine now 👍
