### ISSUE TITLE
Can't use R Markdown or R Notebook offline

### ISSUE THREAD

**Issue by bgillpgh** [rstudio/rstudio#11928]
### System details

    RStudio Edition : Server
    RStudio Version : rstudio-server-2022.07.1+554-1
    OS Version      : Centos 8.5
    R Version       : 4.13

### Steps to reproduce the problem
Attempt to use the menus to open File->R Markdown or File->R Notebook 

### Describe the problem in detail
A small gray status bar appears at the top of the screen and after several minutes an error indicates that the required versions of xfun(0.21) and rmarkdown(2.10) required aren't available. Newer versions of both packages are already installed.

In this particular configuration users will never have external network access but they are able to use most of the features in rstudio with no trouble. With administrative access I was able to load an R Markdown window when I enabled a web proxy but this does not solve our problem.

### Describe the behavior you expected
A markdown or notebook pane would open

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
You aren't alone! This is already tracked here: https://github.com/rstudio/rstudio/issues/9246 -- please comment/upvote there (I'll link the issues, too.)
