### ISSUE TITLE
error with inline output of empty dataframe with a "difftime" column among others

### ISSUE THREAD

**Issue by iona5** [rstudio/rstudio#11939]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.01
    OS Version      : Windows 10 - 21H2
    R Version       :  4.2.1

### Steps to reproduce the problem

execute the following chunk in a Rmarkdown document with inline preview.

```{r}
dframe = data.frame( 
    d = as.difftime(c(1,2), units = "mins"), 
    d2 = "hey"  
)
head(dframe, 0)
```` 
Executing above chunk it errors with 

```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```
Knitting the Rmarkdown or executing the chunk in the console outputs an empty data frame as expected so i guess the bug is somewhere in the inline rendering of RStudio.

### Probable Cause

It seems like the inline output in Rstudio has a problem with **empty** data frames which contain a "difftime" column. 

It might be related to the fact that the time() function does not take a length argument as opposed to character(), numeric() and friends. so time(0) actually returns a vector with the length of 1 while character(0) returns a vector of with the length of 0.

so i suspect somewhere something like this is executed:

```
data.frame( d = time(0), d2 = character(0) )
```

which raises the same error. Having time-only data frames like this: 

```
dframe = data.frame( 
    d = as.difftime(c(1,2), units = "mins"), 
    d2 = as.difftime(c(3,4), units = "mins") 
)
head(dframe,0)
```

actually renders the dataframe without error but oddly enough reports "1 row".

### Describe the behavior you expected

Render just an empty data frame in inline preview.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] [not a crash] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Looks like the error is coming from here:

https://github.com/rstudio/rstudio/blob/709be26cc1d14976336dee9fb6a0cf5a43a0ec55/src/cpp/session/modules/NotebookData.R#L311-L333

The problem here is that RStudio is assuming `length(x) == length(format(x))`, but that's not true for `"difftime"` objects:

```
> diff <- as.difftime(numeric(), units = "mins")
> format(diff)
[1] " mins"
```

We could work around this in RStudio, but it sort of feels like something that might be fixed in R itself. I'll file a bug report to see if the R Core team agrees.
