### ISSUE TITLE
Allow users to open projects using the keyboard in RStudio Server

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#11931]
A common need when opening RStudio is to open a project. A quick way to do this in RStudio Desktop is

- Ctrl+2 -> navigate to the R console
- `rstudioapi::openProject("project/location")`

There seems to be no way to do this in RStudio Server. If I'm missing a command line trick this is a non-issue but if not it would be great to have a shortcut or other way to avoid having to use the mouse to open projects.

Thanks!

**Comment by ronblum** [comment]
@Robinlovelace Interesting idea. Right now we have the option to create keyboard shortcuts for "Open Project" and "Open Project with New R Session," but they both open up the file dialog. I'll mark you suggestion for review.

**Comment by Robinlovelace** [comment]
Thanks, I'm thinking of people who may not be able to or want to use the mouse for navigation easily, could benefit accessibility if done well without affecting functionality, as it shouldn't.

**Comment by Robinlovelace** [comment]
Please re-open @ronblum. Being able to interact with RStudio with shortcuts, including basic stuff like opening projects, will be a major win for productivity. Could the command pallet (Ctrl+Shift+P in Linux) be available on start-up?

**Comment by gtritchie** [comment]
@Robinlovelace 
> Could the command pallet (Ctrl+Shift+P in Linux) be available on start-up?

Hi, not 100% sure what you mean by that. You want the Command-palette to display automatically when you start RStudio, or did you mean something else?

**Comment by gtritchie** [comment]
@Robinlovelace You should be able to use `rstudioapi::openProject("project/location")` on RStudio Server, same as RStudio Desktop. I just tried it and it worked for me.

What is happening when you try?

**Comment by Robinlovelace** [comment]
When I log in this is what I see. Is there a way to open a new project from the command line from this (I think common) state of the application?

![image](https://user-images.githubusercontent.com/1825120/228008355-620a6530-dee7-4bae-b1ad-d83076915d56.png)

Hope that makes sense, if not let me know, and happy to provide further details/tests.
