### ISSUE TITLE
Pop!_OS Linux issue

### ISSUE THREAD

**Issue by mush-ambo** [rstudio/rstudio#11937]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554 - "Spotted Wakerobin" Release (7872775e, 2022-07-22) for Ubuntu Jammy
    OS Version      : Pop!_OS 22.04 LTS PRETTY_NAME="Pop!_OS 22.04 LTS"
    R Version       : 4.1.2-1ubuntu2

### Steps to reproduce the problem

Installed r-base via command line and RStudio via direct download file.  
No additional packages downloaded or installed from R-cran.
Anaconda installed alongside, not using it for R or RStudio. 

### Describe the problem in detail

Painfully slow GUI  -- over 6 seconds to navigate to Help>About RStudio and have box appear..
Typing into command console has a lag of ~20 characters before text appears.

### Describe the behavior you expected

Not only person with problem, also documented here: https://unix.stackexchange.com/questions/716817/rstudio-running-very-slow-on-popos-surface-go-2/

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mush-ambo Thank you for raising this! We don't support Pop!_OS. However, we do support Ubuntu, so I tried the same version for RStudio Desktop on Ubuntu 22.04. I can't reproduce the problem—the application is respond quickly. Note that in this case `r-base` installs 4.2.0, though.

Do you know if this worked in previous versions of RStudio?

**Comment by mush-ambo** [comment]
@ronblum - Appreciate the speedy response!
I've had no problems in the past with RStudio and Pop! (have fresh
installed since ) .. I cannot recall the exact RStudio version I was using
circa 6-9 months ago, but definitely have not tried since I'd upgraded to
22x LTS. Believe others have suggested could be GPU issue, which means most
likely I should reach out to Pop!s team instead? :)
