### ISSUE TITLE
R session termination and crash when RAM gets filled on Rmarkdown chunk

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11934]
### System details
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
I had made a mistake in my code that took me some time to find.
I believe this may be a Bug, since Termination of R current's processing shouldn't make Rstudio to restart but only to Stop current Run. 

I don't know how to add enough data to make a representative case scenario for you to reproduce.
But basically, it is about filling all the system's available memory.

- Within Rmarkdown chunks
- Load large CSV files into memory
- Merge large databases which would add columns
- Straght forward group_by 
- and summarize
- create incorrect calculations in summarize that would end up storing large vectors on cells and executing that function for each element of each vector
- as a result RAM will grow to reach the limit
- in my case is 8Gb with bare SSD freespace
- After reaching +6Gb, Rstudio will go almost unresponsive
- Cancelation/Termination causes Rstudio to restart

### Describe the problem in detail
The 2 databasetes below minuteActivity.2 and personal, are merged with data meant to be used in calculation for a daily summary. I made a mistake in weeknum and weekday, and as a result, the chunk would never end processing and I was forced to terminate R.

```
db$dailyActivity.2 <- 
  db$personal %>% 
  select( .session_id, stride1, stride2, stride3 ) %>% 
  merge( db$minuteActivity.2, by=by[1], all=TRUE ) %>% 
    group_by( 
      .session_id, 
      .datetime = lubridate::floor_date( .datetime, "1 day" )  ) %>% 
    summarise( 
      weeknum = lubridate::isoweek( .datetime ),
      weekday = lubridate::wday( .datetime, week_start=1 ),
```
Correct expression, adding min()
```
      weeknum = lubridate::isoweek( min(.datetime) ),
      weekday = lubridate::wday( min(.datetime), week_start=1 ),
```

### Describe the behavior you expected
Stop/Terminate R current's Chunk without restarting Rstudio or losing others Chunk's state.

**Comment by ronblum** [comment]
@DiegoJArg Thank you for raising this! I don't know what we can do, but I'll mark it for review as part of our continuing development of RStudio.
