### ISSUE TITLE
Child Project not getting same R Version as Parents in Rstudio.cloud

### ISSUE THREAD

**Issue by jennAllen** [rstudio/rstudio#11935]
This was reported by a customer and investigated by the hosted team. We found that if an assignment is created with an older R version, when the child projects/assignments are made, they are getting the latest R version instead of matching with the parent project. This results in R packages not being installed as expected.

Zendesk ticket: https://rstudioide.zendesk.com/agent/tickets/79023

### System details
    RStudio Version : Rstudio.cloud
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. In a shared space on rstudio.cloud, Create an assignment and select a previous R version - eg 4.1.3
2. As a contributor in that space, start the assignment
3. Wait for the it to load and now note the R version - it is set to the latest (4.2.1)

A more detailed observation revealed:
1. create a child (start the assignment) but navigate away while the task is running so that the IDE doesn’t have a chance to load
2. get a shell on the child pod:
3. check the version    
      ``` # cat RVersion
       4.1.3  
4. in the browser navigate back to the project so the IDE finishes loading
5. check the version
     ``` # cat RVersion
       4.2.1 


### Describe the behavior you expected

The child project should get the same R version as the parent.

It was noted this is a regression from this feature: https://github.com/rstudio/rstudio-pro/issues/506

We logged this on the hosted side as well, but we believe the issue is stemming from the IDE: https://github.com/rstudio/lucid-init-container/issues/429

<!-- 
Please keep the below portion in your issue, and check `[x]` the applicable boxes.
-->

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [N/A ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [N/A ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mbaynton** [comment]
Duplicate pro issue: https://github.com/rstudio/rstudio-pro/issues/3822

**Comment by ronblum** [comment]
@jennAllen and @mbaynton I'll close this as a duplicate. I think this would only be relevant to RStudio Workbench, since RStudio Server (open source) doesn't allow for multiple versions of R. Let me know if you disagree, though.

**Comment by jennAllen** [comment]
Sorry Ron, yes looks like an issue is logged elsewhere now for this! I wasn't quite sure where it belonged! Thanks!
