### ISSUE TITLE
Presence of emojis in code will misalign the text cursor

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#11943]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.11.0 Build 173
    OS Version      : Win11
    R Version       : 4.2.1

On occasion I may have emojis in my code. In this case, the code is the following:

> tweets %>%
  filter(str_detect(full_text, "✅")|str_detect(full_text, "❌")|str_detect(full_text, "🔰")) %>% 
  transmute(name = full_text %>% word(2, sep = ": ") %>% str_trim(),
            full_text,
            created_at) %>% 
  count(name) %>% view()

As you can see in the [gif here](https://i.imgur.com/tX51123.gif) while moving through the code on the same line as the emojis, the cursor will display to the left of where it "actually" is.

If unclear, this is exactly what I'm doing in the gif: starting on the line below the emojis, I'm moving left with the arrow on my keyboard. Already when the cursor comes to the emoji line, it first appears in the middle of the pipe, not on the right of it as you'd expect. Then, moving leftward, I'm deleting and rewriting a few characters to show that they're misaligned from where the cursor is.

It seems like each new emoji will push the cursor to the left a bit more.

Anyway, as far as I can remember, this has been the behaviour for years but I don't code with emojis _that_ often so I wouldn't have noticed any changes.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by martj42** [comment]
For what it's worth, seems like some emojis are fine. Just looked at code with the following ones - 🤯, 😟, 💤, 💩, 🎯, 💎, 🃏, 🍻, 🤷, 🥇, 🥈, 🥉, 🔥, 🍫, 🎖, 🏳, 💶 - and those are all working as expected. Maybe some emojis are different under the hood.

**Comment by kevinushey** [comment]
I think the problem is that ✅ is a dual-width character, but RStudio fails to "see" that (it thinks it's just a single-width character) and so only applies a single indent when positioning the cursor after a line containing that character.

<img width="112" alt="Screen Shot 2022-09-13 at 11 58 23 AM" src="https://user-images.githubusercontent.com/1976582/189987173-850e4575-c5f7-4e7f-a749-edf01de1be2c.png">

**Comment by ronblum** [comment]
To underscore @kevinushey's assessment, an emoji like 🤔 doesn't cause this issue.

**Comment by kevinushey** [comment]
For reference, the Ace code where the cursor position is computed:

https://github.com/ajaxorg/ace/blob/6ad31238870282160daba0a4ab7ce39ba80a6109/src/layer/cursor.js#L151-L166

Ace makes the assumption that each "character" is the same width, which is incorrect.

The generally-accepted solution is to do something like copy the associated text to a separate DOM element, and then measure the computed width of that element, but that is fairly expensive.

This also gets a bit more complicated when we consider word-wrapping.
