### ISSUE TITLE
Rstudio freezes after putting laptop into Hibernation

### ISSUE THREAD

**Issue by iamkarp** [rstudio/rstudio#11941]
This never never happened before but in the last few years, Rstudo freezes after putting the my laptops into hibernaton mode.  Sleep does not cause this issue however, my computer will awaken while asleep causing my laptop to overheat in my bag.

**Comment by renatovargas** [comment]
> @iamkarp Thank you for raising this! This looks like a duplicate of issue #10831, which is currently closed, but might need to be reopened. Can you provide the following information to help determine its proper state? Thanks!
> 
> ### System details
> ```
> RStudio Edition : 
> RStudio Version : 
> OS Version      : 
> R Version       : 
> ```

Hi. Thank you for offering to reopen the issue. I'm having the same problem.  Links keep pointing to #10831 which was closed explaining that the move to Electron had solved it, but I can confirm it's still happening on Windows 11.

The last time, I had RStudio and Chrome open. Closed the lid for a couple of hours (OS goes to sleep) and when reopening everything works fine, except RStudio. The whole interface is unclickable, untypeable, except for the minimize, expand, close buttons.

It has happened every time I put the laptop to sleep before with RStudio open. Sometimes with Chrome open, sometimes other programs as well, such as Visual Studio Code and Excel.

RStudio Desktop
Version: 2022.07.1 Build 554
OS Version: Windows 11 Home, OS Build 22000.978, Windows Feature Experience Pack 1000.22000.978.0 
R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid"
Asus Zephyrus G14
AMD Ryzen 9 5900HS with Radeon Graphics 3.30 Ghz
GeForce RTX 3060 Laptop GPU

**Comment by disr-rockstar** [comment]
I'm also experiencing the same issue. After hibernation, I come back to Rstudio windows being completely unusable and blank (all white). 

Rstudio edition: Desktop
Rstudio Version: 2022.07.1 Build 556
OS Version: Windows 10 Enterprise, Version	21H1, build 19043.2006 Experience Windows Feature Experience Pack 120.2212.4180.0
R version 4.2.1
Intel(R) UHD Graphics 615
