### ISSUE TITLE
adjacent $ operators in R snippets

### ISSUE THREAD

**Issue by srenbo** [rstudio/rstudio#11951]
### System details
RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
 My desired snippet output would be

`MY_MEDIAN <- my_data$my_col`

where my_data and my_col are snippet variables to be filled in by the user.

However, writing the snippet requires adjacent dollar signs ($$)--one $ to indicate the dataframe$column relationship and one $ to create the snippet variable. The adjacent dollar signs are bugging up the snippet:

snippet demo1
   ```
 MY_MEDIAN <- median(${1:my_data}$${2:my_col})
produces MY_MEDIAN <- median(my_data{2:my_variable})

```
I have tried using escapes () but this has not solved my problem.

snippet demo2
   ```
 MY_MEDIAN <- median(${1:my_data}\$${2:my_col})
produces MY_MEDIAN <- median(my_data\{2:my_col})
```

snippet demo3
  ```
  MY_MEDIAN <- median(${1:my_data}\${2:my_col})
produces MY_MEDIAN <- median(my_data${2:my_variable})
```
```

MY_MEDIAN <- median(${1:my_data}\\$${2:my_variable})
produces MY_MEDIAN <- median(my_data\{2:my_variable})
```

### Describe the behavior you expected

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
This probably happens here: 

https://github.com/rstudio/rstudio/blob/b179cbe6f285d7e8da26098191ea1754dab30011/src/gwt/src/org/rstudio/studio/client/workbench/snippets/SnippetHelper.java#L283

**Comment by jonvanausdeln** [comment]
Tested on 2022.11.0-daily+245
Windows 11, Ubuntu 22.04

Using `\` to escape gave the desired results.
Snippet `MY_MEDIAN <- median(${1:my_data}\$${2:my_col})`  resulted in  `MY_MEDIAN <- median(my_data$my_col)`
