### ISSUE TITLE
`run all chunks above` gives error when mixing r and python chunks in the same `Rmd` file

### ISSUE THREAD

**Issue by elgabbas** [rstudio/rstudio#11968]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      :  Windows 11 pro 21H2
    R Version       :  4.2.1

### Steps to reproduce the problem
I encountered an error when I click on the `run all chunks above` button for an `R` chunk preceded by a `python` chunk, and vice versa.
When all previous chunks are of the same type, no error occurred. Knitting the file to HTML works fine.

#### 1. only python chunks
- clicking on `run all chunks above` up to the last chunk works fine

````
---
output: html_document
---

```{python}
import pandas as pd
x = 10
```

```{python}
y = 5
print(x,y)
```

```{python}
z = 15
```
````

#### 2. only R chunks
- clicking on `run all chunks above` up to the last chunk works fine

````
---
output: html_document
---

```{r}
head(iris,2)
```

```{r}
head(iris,2)
```

```{r}
head(iris,2)
```
````

#### 3. R chunks followed by a python chunk
- here, clicking on `run all chunks above` of the python chunk cause error
    -  `NameError: name 'head' is not defined`
    -  `NameError: name 'head' is not defined`
- it seems that `Rstudio` expects that all previous chunks are also python
````
---
output: html_document
---

```{r}
head(iris,2)
```

```{r}
head(iris,2)
```

```{python}
import pandas as pd
```
````

#### 4. python chunks followed by an R chunk
- here, clicking on `run all chunks above` of the R chunk cause error
    -  `Error: unexpected symbol in "import pandas`
- it seems that `Rstudio` expects that all previous chunks are also R

````
---
output: html_document
---

```{python}
import pandas as pd
x = 10
x
```

```{python}
import math
```

```{r}
head(iris,2)
```
````

Thanks,
Ahmed

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@elgabbas Thank you for raising the issue! I'm unable to reproduce the problem though in both 2022.07.1+554 and 2022.11.0-daily+190.

@jgutman Do you have any suggestion of what to look at further?

**Comment by jgutman** [comment]
What is the setting being used for chunk execution? Are they being executed inline in the notebook or in the console? This will not work when chunk execution is being done in the console (because the console does not execute python code) so chunk output must be set to show inline in the notebook

**Comment by elgabbas** [comment]
Thanks @jgutman ... Exactly, the error occurred when using the source view and showing chunk outputs in the console.

**Comment by jgutman** [comment]
I believe this is basically the same issue as #2501. 
We can try to fix this in the future, but as of now if you want to mix chunks of different languages/engines, you must set it to show chunk output inline and not in the console.
