### ISSUE TITLE
prefer project directory as fallback when restarting session from tempdir?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11960]
Currently, if the user is working in a temporary directory and then restarts the session, the R working directory will default back to the home directory:

```
> setwd(.rs.getProjectDirectory())
> print(getwd())
[1] "/Users/kevin/r/pkg/renv"
> print(.rs.getProjectDirectory())
[1] "/Users/kevin/r/pkg/renv"
> setwd(tempdir())
> .rs.restartR("print(getwd())")
NULL

Restarting R session...

> print(getwd())
[1] "/Users/kevin"
```

I think we should reset the working directory to the project directory in this case.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+257
Windows 11, Ubuntu 22.04

Tested with several different directory paths (particularly on windows) and new session was always back in the project directory.
