### ISSUE TITLE
auto complete popup masks text of function help popup just below it

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/rstudio#11973]
### System details
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Ubuntu Bionic
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

### Steps to reproduce the problem
1. Load any source R file in Rstudio.
2. Type any function, opening bracket and pause / press tab e.g. `tidyr::pivot_longer(`

### Describe the problem in detail
I have seen this problem in imac, macbookpro and macbook air and in older and newest version of rstudio.
The problem is the argument desciption gets hidden by the argument list popup.
Here is a screenshot.
<img width="1052" alt="Screenshot 2022-09-19 at 9 02 13 PM" src="https://user-images.githubusercontent.com/3091624/191058182-7f0122a1-736a-4d38-a3d5-8079a8846a22.png">

### Describe the behavior you expected
The lower box should start after the upper box ends.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ -] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For reference, I think this is where the Help popup positioning logic lives:

https://github.com/rstudio/rstudio/blob/6689fa8dcaf32afc003a9ec2e7907a50d8d173a3/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java#L336-L376

We probably need some way to hook up the position computations to the position of the completion list itself.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+248
WIndows 11 and Ubuntu 22.04 desktop
Ubuntu 22.04 Server

Tested several different autocomplete dialogs in addition to original reprex.  All help dialogs were not covered up.

**Comment by sanjmeh** [comment]
> Verified on 2022.12.0-daily+248
> WIndows 11 and Ubuntu 22.04 desktop
> Ubuntu 22.04 Server

is a stable version now available? Or shall we download the daily version?
