### ISSUE TITLE
"Soft wrap long lines" not working after source editor is popped out

### ISSUE THREAD

**Issue by alohacocoa** [rstudio/rstudio#11972]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      :  Windows 10 Home
    R Version       :  latest version

### Steps to reproduce the problem
1 --- Pop out source code window
2 --- Try changing "Soft wrap long lines" under "Code"
3 --- Nothing will happen

### Describe the problem in detail
It seems like any changes made to the "Code" tab will not apply to a popped out source window.

### Describe the behavior you expected
Features such as "Soft wrap long lines" should work regardless of whether the window is popped out or not.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
@alohacocoa thank you for submitting your issue.  I believe this behavior is fixed in the upcoming release.  If you would like to try it to confirm, the lastest builds are available at https://dailies.rstudio.com/
