### ISSUE TITLE
Pango filling all memory - Quickly getting into out of RAM

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11979]
### System details

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
Put this code somewhere, disabled as it is.
Then when knitting and Pango starts, it goes into a memory hungry beast out of control.

````
<!-- ```{r echo=FALSE} -->
<!-- # https://bookdown.org/yihui/rmarkdown-cookbook/embed-file.html -->
<!-- # https://github.com/fmmattioni/downloadthis -->
<!-- # install.packages("downloadthis") -->

<!-- xfun::pkg_load2(c("htmltools", "mime")) -->
<!-- ``` -->


<!-- - `r xfun::embed_file("../input/stage2/personal.csv")`  -->
<!-- - `r xfun::embed_file("../input/stage2/minuteActivity.2.csv")`  -->
````

### Describe the problem in detail
Occurs only when knitting, and the pango process is launched, it starts to quickly take all available memory.
I quickly run out of RAM. 
I have large dataset loaded from CSVs. I first thought that may noob experience in R was doing this.
But I found that it was this miserable disabled code that make me loose about 10 hours to find it out.
I don't exactly which line.

### Describe the behavior you expected
Rmarkdown to be lightweight and fast, avoid any extensive RAM usage.

![image](https://user-images.githubusercontent.com/25246225/191129166-ec7add96-b800-445f-a534-11809b1d18fc.png)
![image](https://user-images.githubusercontent.com/25246225/191130882-184cc90f-bc84-4576-a875-f97b4c0b9302.png)
![image](https://user-images.githubusercontent.com/25246225/191137003-01aa310f-7feb-4fc2-aaad-2a5fdaec61b8.png)

**Comment by kevinushey** [comment]
The problem (as I understand it) is that `knitr` still evaluates inline R code even if within an HTML comment. For example, with this document:

`````
---
title: "Untitled"
author: "Bug"
date: "2022-09-20"
output: html_document
---

<!--
  This code is within an HTML comment. `r x <- 42`
-->

```{r}
print(x)
```
`````

R will still 'see' `x` in the chunk, as the inline R code was evaluated.

<img width="293" alt="Screen Shot 2022-09-20 at 11 06 03 AM" src="https://user-images.githubusercontent.com/1976582/191331919-238004b0-1045-450e-86db-868374bd95c0.png">

I think this would need to be handled either within the `rmarkdown` or `knitr` packages. @yihui, do you have an opinion on where this issue would belong?

**Comment by yihui** [comment]
The correct way to comment out content containing code chunks or inline code in R Markdown is to use the `comment` engine: https://yihui.org/en/2022/01/knitr-news/#the-new-engines-comment-verbatim-and-embed HTML comments don't work. Sorry.

**Comment by DiegoJArg** [comment]
Confirming that the comment block worked to comment this out.
¿Shouldn't this be the normal behavior of Ctrl+Shift+C ?
Also, syntax highlighting seems to not handle this well.

I just wonder where is the RAM going ?
I suspect xfun uses base64, which uses 4 bytes to represent 3 bytes. 
This +33% increase does not explains the total RAM usage seen on pango when knitting.
About 100Mb attached as CSV with xfun plus the rest of html, scales to 2.7 Gb of RAM.
With CSV unziped it was about 160Mb scaling to about 8Gb.
I am guessing that it is not normal to scale that much.

![image](https://user-images.githubusercontent.com/25246225/191384939-408a653c-a580-4644-8053-9ffa8e66e409.png)
![image](https://user-images.githubusercontent.com/25246225/191385040-f32b4e58-fe37-4779-a7a7-51e229890138.png)
![image](https://user-images.githubusercontent.com/25246225/191386213-2cd6e18a-2928-455e-8dc6-7ef25baff259.png)

**Comment by kevinushey** [comment]
That's a good idea; I think it would be a good idea for our comment / uncomment command to use a comment block.
