### ISSUE TITLE
Links to the manual do not work with topics that contain a dot

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#11983]
From https://github.com/r-lib/cli/issues/524

**Comment by romainfrancois** [comment]
QA note: see #12014 or https://github.com/r-lib/cli/issues/524

**Comment by jonvanausdeln** [comment]
Checked on 2022.12.0-daily+265

Works on Windows 11 Desktop 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/6433789/195701243-1b88a32f-d05c-4e73-a4d1-928f8b1ad089.png">
However, it doesn't work on Server.. running on Ubuntu 22.04 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/6433789/195701497-124e1808-4a8c-46e5-bffd-90c1ea2e7cdb.png">
I checked both MS Edge on Windows, and Chrome in Ubuntu .. both gave same result

**Comment by romainfrancois** [comment]
That's odd, are they using the same version of `cli` ? What happens when using `cli::format_inline()`

```
> cli::format_inline("{.topic [as table](base::as.table)}")
[1] "\033]8;;ide:help:base::as.table\aas table\033]8;;\a"
```

Another way to test that the ide does what it is supposed to do is to skip the `cli` interpolation, i.e. use: 

```r
cli::style_hyperlink("as table", "x-r-help:base::as.table")
```

<img width="465" alt="image" src="https://user-images.githubusercontent.com/2625526/195783936-2c347869-5b06-451a-bc0e-0f5bf1248ff9.png">

**Comment by jonvanausdeln** [comment]
It was an older version of `cli`. Once I updated on server it behaved as expected.  Sorry for the false alarm!

All testing passes now.
