### ISSUE TITLE
A JavaScript error occurred in the main process on Daily MacOS Beta ARM

### ISSUE THREAD

**Issue by danieltomasz** [rstudio/rstudio#11984]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 2022.11.0-daily+190
(several previous builds  doesnt work too)
    OS Version      :  MacOS 13.0 beta ARM
    R Version       :  4.2.1

After installing  when I try to start RStudio  I am getting screen with this error

```
Uncaught Exception:
Error: Config schema violation: `view/zoomLevel` must be >= 0.25
at e.exports._validate (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:8:50378)
at set store [as store] (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:8:49337)
at e.exports.set (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:8:48105)
at P.zoomLevel (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:17:41455)
at IpcMainImpl.<anonymous> (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:17:14332)
at IpcMainImpl.emit (node:events:526:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11829)
at EventEmitter.emit (node:events:526:28)
```
and the next screen is this
```
Uncaught Exception:
Error: Config schema violation: `view/zoomLevel` must be >= 0.25
at e.exports._validate (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:8:50378)
at set store [as store] (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:8:49337)
at e.exports.set (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:8:48105)
at P.zoomLevel (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:17:41455)
at BrowserWindow.<anonymous> (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:8:452543)
at BrowserWindow.emit (node:events:538:35)
at node:electron/js2c/browser_init:161:14116
at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

When I try to run diagnostics
I am getting 

```
objc[48699]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x246f681c0) and /Applications/RStudio.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x105ca5348). One of the two will be used. Which one is undefined.
```

The rest of the diagnostic seems to be ok

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@danieltomasz Thank you for raising this! Did you by chance have MacOS 12 recently on the same machine, and was it working there?

@timtmok Any suggestion of what to look at or what might be going on?

**Comment by danieltomasz** [comment]
Unfortunately I  dont have MacOS 12, but I might try to install it via virtual machine; today Apple relesead new beta for developers, I will update when it became public and report if the issue still persist; The Rstudio Preview 2022.07 works well, the same as Rstudio Daily  available through homebrew (which is one of the early builds)

I think the error started after Installing friday daily build, but I did updated from a few daily releases back

**Comment by timtmok** [comment]
@danieltomasz Did you have a previous RStudio install before with the UI zoomed out on it? It looks like it might have picked up an old setting and the preference validation can't handle it.

This will have to be fixed for the release.

**Comment by danieltomasz** [comment]
I dont remember zooming UI, but I had installed previous version of dailys,  I use "Spotted Wakerobin" along Elsbeth Geranium, maybe this  could create a conflict?

**Comment by timtmok** [comment]
@danieltomasz if you can still reproduce, would you mind attaching your preference files? Spotted Wakerobin uses the old preference location on Mac, which is located `/Users/<user>/Library/Preferences/com.rstudio.desktop.plist`. Elsbeth Geranium reads those values and writes out to a new location (`/Users/<user>/Library/Application Support/RStudio/config.json`). You should be able to use either version without worry about a preference incompatibility. FYI, Elsbeth Geranium will not update the old preference file nor read it after the first startup. It's a one-way migration.

**Comment by danieltomasz** [comment]
I uninstalled  all instances of Rstudio using AppCleaner together with all settings, then reinstalled, now it is working :) 

If this atill  might be useful here are   the preferences
( I am including all instances,both Spotted Wakerobin and Elsbeth Geranium,  not sure which is which ;) 

[com.rstudio.desktop.plist.zip](https://github.com/rstudio/rstudio/files/9637351/com.rstudio.desktop.plist.zip)

[org.rstudio.RStudio.plist.zip](https://github.com/rstudio/rstudio/files/9637350/org.rstudio.RStudio.plist.zip)

Issue might be closed :)

**Comment by timtmok** [comment]
@danieltomasz That's good to hear! It sounds like a corrupted preference file. I'm not sure how it got into that state. Current and past versions do not allow for a zoom value lower than 0.25. The current daily does validate the preference setting to prevent this and I can only think that the value was edited externally somehow. I'll still keep this in the backlog since I think there's an improvement to allow the user to reset the preferences to defaults if there's a corrupted preference file.

**Comment by danieltomasz** [comment]
Might it have something  to do with the Stage Manger and the live preview it creates ?
https://9to5mac.com/2022/07/26/stage-manager-on-mac/

**Comment by Jpkeys29** [comment]
Same issue here and I have not being able to fix it. Any suggestions? Thank you!

**Comment by NFordUMass** [comment]
^^

**Comment by danieltomasz** [comment]
@Jpkeys29  the error  diseaperaed when I completely deleted user profile, try first installing/running Rstudio on new MacOS user profile and see if the error still perisist

**Comment by jjnbdal** [comment]
Dear All. Sample problem on Windows. Do you have a step-by-step instruction, please?

**Comment by ronblum** [comment]
@jjnbdal Are you looking for how to reset RStudio's state? If so, instructions are available at https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State.

**Comment by jjnbdal** [comment]
Thank you. I will give it a try.

**Comment by jjnbdal** [comment]
I am not sure if this is related to resetting of the RStudio's state, but this is the error arose when I installed RStudio every time (I did un-install/reinstall three to four times now). I don't know what the error mean. I am still having this problem. Does anyone have the same problem or had this problem before. How to fix it?
 
![image_2024-02-14_204309499](https://github.com/rstudio/rstudio/assets/39582182/3161b388-3f73-4cb1-a037-49d91b2d0a5a)

**Comment by ronblum** [comment]
@jjnbdal This occurs after resetting RStudio's state?

**Comment by danieltomasz** [comment]
@jjnbdal reinstall doesnt remove all  Rstudio config files, you really need to remove `%localappdata%\RStudio` and `%appdata%\RStudio
` on Windows

**Comment by jjnbdal** [comment]
> @jjnbdal This occurs after resetting RStudio's state?

Yes, this occurs after resetting RStudio following the instructions on the posit page. It will be nice to get RStudio to work. Currently, I have to use Jupyter Notebook/lab.

**Comment by timtmok** [comment]
@jjnbdal this looks like: https://github.com/rstudio/rstudio/issues/13864

Your issue does not look related to this one.

**Comment by jjnbdal** [comment]
> @jjnbdal this looks like: #13864
> 
> Your issue does not look related to this one.

Thank you so much. It seems I have to use 2023.06.2 version due to the antivirus installed on my system. Thank you.
