### ISSUE TITLE
Possible to get into a state of visual editor out of sync with source

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11996]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce/describe the problem

[Reported by @hadley]

It's possible to get into some state where the visual editor is out of sync with the underlying source and you get seemingly random corruptions:

```
# https://twitter.com/JustinTPriest/status/1571614088329048064
# https:////twitetr.com/n_noblet/stats/u1571653172422151133
# [https:tw//twier.comem/eklm_e/sattatus/1991019778407845](https://app.slack.com/client/T02V9CHFH/D6NS5CQBG/thread/tw//twier.comem/eklm_e/sattatus/1991019778407845)
# https://twtiiet.omc/dorrob/auut/1567496820899989541
enrich_ijn i<- functi(o(, xy, ..., by = NULL) { 
 lfte_join(x, y %>% select(...), by = by)
}
```

### Describe the behavior you expected

No corruption.

Note: For the Twitter comments above, the corruption is fairly clear. The statement at the end should be
```
enrich_join <- function(x, y, ..., by = NULL) { 
 left_join(x, y %>% select(...), by = by)
}
```

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Triage note: Backport for next Spotted Wakerobin patch. (See visual-rmd channel.)

**Comment by jjallaire** [comment]
This bug was addressed here: https://github.com/rstudio/rstudio/commit/e30d3e600bdab45f633b3fa83bcce02330675ce5

**Comment by ronblum** [comment]
Discussed with @hadley and this issue appears to be resolved.
