### ISSUE TITLE
Trim whitespace from DOIs in "Insert Citation" Menu?

### ISSUE THREAD

**Issue by mikemahoney218** [rstudio/rstudio#12004]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.7.1.554 (Spotted Wakerobin)
    OS Version      :  Ubuntu 22.04
    R Version       :  4.2.1

### Steps to reproduce the problem

In the visual Quarto editor, open the Insert Citation menu (Insert -> Citation -> From DOI) and input a DOI with either leading or trailing whitespace (e.g., `10.1080/15213260701283079 `).

### Describe the problem in detail

If you attempt to create a new citation on the "Insert Citation" screen in RStudio using the DOI search option, having any leading or trailing whitespace in your DOI will return "An error occurred while searching for this DOI", with no further explanation. 

Would it be possible for this menu to trim leading and trailing whitespace "under the hood", as it's likely the result of weird copy-and-paste issues and not an intentional input by the user?

### Describe the behavior you expected

I expected leading and trailing whitespace to be trimmed, and the search to only use the actual characters of the DOI.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mikemahoney218 Thank you for letting us know about the issue!

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here: https://github.com/quarto-dev/quarto/commit/0478427dbec0cc43d246a0a630094a0ccf03d4ba

**Comment by ronblum** [comment]
Verified in RStudio Server 2023.03.0-daily+318 on Ubuntu 20.04.5 via Chrome on MacOS 13.2 using the example above with preceding and trailing spaces.
