### ISSUE TITLE
Add arg to Windows package build to build 64 bit only

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#12003]
Currently, if you run the script to build the Windows package (`package/win32/make-package.bat`) it will fail if you do not have both the 64 bit and 32 bit versions of R installed and in your registry. This is frustrating because recent R versions (e.g. 4.2) do not come with 32-bit builds, so you have to have an older version of R installed, and this also makes the builds take longer when developers usually just care about getting a 64 bit build working and testable. Devs have been working around this by manually commenting out sections of the file `package/win32/make-package.bat` but this is inconvenient. It would be better to have a command line arg to build the package for 64 bits only for local development and testing.

**Comment by kevinushey** [comment]
I can take a stab at this.
