### ISSUE TITLE
Install readxl pachage not working: installation of package ‘readxl’ had non-zero exit status

### ISSUE THREAD

**Issue by Lachsschinken** [rstudio/rstudio#12013]
Hello there, I have problems installing the readxl package to read in excel files ..
I'm using a Macbook Air 2015 with the latest system and I have the latest version of R-Studio. Thank you so much already for every help!!
I added the code responding to my installing approach down low. :)

installing the source package ‘readxl’

trying URL 'https://cran.rstudio.com/src/contrib/readxl_1.4.1.tar.gz'
Content type 'application/x-gzip' length 2090383 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

* installing *source* package ‘readxl’ ...
** package ‘readxl’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘readxl’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/readxl’

The downloaded source packages are in
	‘/private/var/folders/0n/5j81yf0j4ybdsmxnl9hh4y8h0000gn/T/RtmpSbQ649/downloaded_packages’

✔ Package 'readxl' successfully installed.
Warning message:
In utils::install.packages("readxl", repos = "https://cran.rstudio.com/") :
  installation of package ‘readxl’ had non-zero exit status

**Comment by kevinushey** [comment]
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun


You need to reinstall the macOS command line tools. Run this from a terminal:

```
xcode-select --install
```
