### ISSUE TITLE
Do not load previous session by default

### ISSUE THREAD

**Issue by thk686** [rstudio/rstudio#12028]
I always turn off the option to load my previous session and data and I believe these should be the default settings for rstudio. I am working with a package that has a bug that causes the rstudio screen to go blank. In this case, I was using rstudio server but the same idea applies. There was no way for me to fix the problem because I could not access rstudio (server in this case) to turn off the load previous session option. That would be a big problem for a remote user without direct access to the host. I was able to fix it by deleting all my user installed packages. Once the offending package was gone, I could then access an rstudio session. You see the problem -- defaulting to load the previous session is dangerous if it causes rstudio to fail. Same goes for restoring .RData and so on. I would urge you to consider making the default a blank slate. How hard is it to click 'recent projects'?

**Comment by jonvanausdeln** [comment]
Thank you for the issue report!  We'll consider this for future release.

**Comment by jthomasmock** [comment]
Howdy @thk686 !

Changing the default of "Restore .RData into Workspace" and/or Save workspace to .RData on exit would be a change to R's default behavior. As such, we're unlikely to modify it in the short term.

However, you can set both of these settings via the `rstudio-prefs.json`- this would allow you to set these as your local-server defaults for the entire server (`/etc/rstudio`) or for a specific user (`~/.config/rstudio`). This means that you can set these before accessing the RStudio UI, and on new servers in the future, you can transfer your preferred settings.

On a Server, `.rstudio-prefs.json` will be at:

Scope | Default | Environment
-- | -- | --
User | ~/.config/rstudio | XDG_CONFIG_HOME
System | /etc/rstudio | XDG_CONFIG_DIRS

See context around modifying this file at: https://docs.rstudio.com/ide/server-pro/r_sessions/customizing_session_settings.html

And full settings options at: https://docs.rstudio.com/ide/server-pro/session_user_settings/session_user_settings.html

The two settings I believe you're looking for are: 

load_workspace - set to false
save_workspace - set to false

**Comment by cbrnr** [comment]
This is such an unfortunate choice for several reasons. In addition to the issue reported here, these defaults hinder reproducibility (the first thing I tell my students to do before working with RStudio is to change these settings, and I am definitely [not the only one](https://forum.posit.co/t/first-line-of-every-r-script/799/12)).

In my opinion, not wanting to change the default behavior of R is significantly outweighed by the benefits of enabling reproducible data analysis by default. In addition, I think there's nothing wrong with RStudio taking an opinionated approach once in a while.

Finally, when running R from the command line, the workspace is *not* saved by default (the defaults seem to be `--no-save` and `--restore`).

Any chance you might reconsider your decision?

**Comment by kevinushey** [comment]
We definitely recognize the drawbacks, but we're also quite concerned about the potential for the following scenario:

- An RStudio user is accustomed to the default behavior of RStudio saving and loading the workspace as RStudio is launched and closed;
- An RStudio update changes the default, so that the workspace is no longer saved + loaded on start;
- After updating RStudio, it appears to the user as though data were lost.

There are ways for us to navigate this (e.g. notify the user defaults are changing; notify them they can load the workspace by hand; probably other options as well) but it's still an uncomfortable change to make.

**Comment by cbrnr** [comment]
It's great to hear that you are open to discussing changes! I agree it will be uncomfortable for these users, but I am also pretty sure that the new settings will be a welcome change for many other (probably more) users. And RStudio could/should maybe push those people relying on saving/restoring their workspace towards a more reproducible workflow. After all, if they don't like it, they can always manually turn it back on. Finally, new users should definitely be pushed towards using these settings. As to how to notify users, I'm afraid I don't know enough how you usually handle such things. Maybe announcing the upcoming change one release prior to actually implementing the change would be useful. And I think it would be helpful to hear what other RStudio devs think.

**Comment by jimgar** [comment]
Just to follow up on @jthomasmock's comment (wow - two years ago already!)

In case anyone is still a bit confused about how to set defaults in RStudio Server, it's pretty simple.

I have to run RStudio Server out of an Ubuntu container. When building the image I simply copy `rstudio-prefs.json` into `/etc/rstudio/rstudio-prefs.json`. This applies the same configuration to all users of the server instance.

The contents of the prefs file for the OP's purpose should look like this:

```json
{
  "save_workspace": "never",
  "load_workspace": false
}
```

Some other options for even more cleanliness and functionality:

```json
{
  "restore_source_documents": false,
  "save_workspace": "never",
  "load_workspace": false,
  "always_save_history": false,
  "restore_last_project": false,
  "insert_native_pipe_operator": true,
  "rainbow_parentheses": true
}
```

When I open up `Tools` -> `Global Options...`, you can see everything is unchecked and set to `Never`.

<img width="626" alt="rstudio-server-prefs" src="https://github.com/user-attachments/assets/ba65cc82-5b0e-42a9-bf9c-7b73d8be67a6">

If you are logged in as a user and change anything interactively via `Global Options`, then the user-level file at `~/.config/rstudio/rstudio-prefs.json` (macOS and Linux) gets updated. You can use that as an easy source of values to copy into the system-level prefs file, if you ultimately want them to apply to all users.
