### ISSUE TITLE
Cmd+W after sorting in data viewer closes data viewer and the tab left to it 

### ISSUE THREAD

**Issue by gkaramanis** [rstudio/rstudio#12029]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 2022.11.0-daily+186 (2022.11.0-daily+186)
    OS Version      :  MacOS 12.5.1 (21G83)
    R Version       :  R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem
1. Open a dataset in the data viewer next to one or more already open tabs 
2. Sort a column in the dataset
3. Press cmd+W to close the data viewer

### Describe the problem in detail
After sorting in the data viewer, Cmd+W closes the data viewer and the tab left to it 

### Describe the behavior you expected
Cmd+W closes only the data viewer

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

https://user-images.githubusercontent.com/3393168/192087599-8094f613-fc5d-42f6-a460-9141da366351.mov

**Comment by jonvanausdeln** [comment]
Thank you for reporting this issue and the clear repro steps!  I am able to reproduce on Windows, Ubuntu, and MacOS.

Triage: This does not repro on QT versions, so appears to be a regression.

**Comment by kevinushey** [comment]
Note for QA: when testing, it's worth to verify the same scenario works on both Windows + Linux (e.g. Ubuntu desktop).

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+228
Windows 11, Ubuntu 22.04

Tested with multiple files and datasets open.  All closed as expected.
