### ISSUE TITLE
QA for RStudio User Guide Doc Updates - "Code" chapter

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#12027]
## Request

I have created this issue for the QA process. Note that the PR itself is relatively small, but I am asking for review on the files themselves.

PR: https://github.com/rstudio/rstudio/pull/12026

Tagging @AshleyHenry15 and @melissa-barca here as well.

I have added updated sections for the "Code" Section of the User Guide. I am requesting review on the 7 .qmd files in the [`ide/guide/code` directory](https://github.com/rstudio/rstudio/tree/docs-ide/docs/user/rstudio/ide/guide/code) - all screenshots have been updated, as seen in the [preview build](https://colorado.rstudio.com/rsc/content/0337121d-c58a-44ca-8462-8155389ad5e5/).

- code-navigation.qmd
- code-sections.qmd
- console.qmd
- debugging.qmd  
- diagnostics.qmd     
- execution.qmd  
- projects.qmd

Files in docs branch: https://github.com/rstudio/rstudio/tree/docs-ide/docs/user/rstudio/ide/guide/code
Preview Build: https://colorado.rstudio.com/rsc/content/0337121d-c58a-44ca-8462-8155389ad5e5/

**Comment by jthomasmock** [comment]
Closed with PR

**Comment by kelli-rstudio** [comment]
Verified on https://colorado.rstudio.com/rsc/rstudio-user-guide-2022-09-29/
