### ISSUE TITLE
Edits using the visual editor can cause the wrong line to get executed when running individual lines

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12021]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.11.0-daily+202
    OS Version      : MacOS 13, Ubuntu 20.04 via Chrome on MacOS 13
    R Version       : 4.2.1

### Steps to reproduce the problem

1. Create a new Quarto document.
2. Switch to source mode.
3. Paste in the contents of the file at https://github.com/hadley/r4ds/blob/c24e0b86920aba0b57c7ca314215c04716cd0f3c/iteration.qmd
4. Switch to visual mode.
5. Click on the first line in the first chunk, `#| results: "asis"`
6. <kbd>Cmd-Return</kbd>
   - The first bit of code is executed
   - Note: the warning is expected because we didn't create the file being sourced, but that's not important.
```
> #| results: "asis"
> #| echo: false
> source("_common.R")
Warning: cannot open file '_common.R': No such file or directoryError in file(filename, "r", encoding = encoding) : 
  cannot open the connection
```
7. Place the cursor at the end of the first header, `Iteration`, and hit <kbd>Return<kbd>
8. Enter some text, e.g. `Now is the winter of our discontent.`
9. Click on the first line in the first chunk, `#| results: "asis"`
10. <kbd>Cmd-Return</kbd>
   - The new text above is executed.
```
> Now is the winter of our discontent.
Error: unexpected symbol in "Now is"
```
11. Click on the last line in the first chunk, `status("drafting")`
12. <kbd>Cmd-Return</kbd>
    - The line above it is executed.
```
> source("_common.R")
Warning: cannot open file '_common.R': No such file or directoryError in file(filename, "r", encoding = encoding) : 
  cannot open the connection
```

### Describe the problem in detail

After a chunk's line of code is run and new lines are added, running a line of code tries to execute a line above it—even if that line is in the body of the text and not in the chunk.

I haven't been able to pinpoint a minimal example—whether it's the length of the file or something specific to the contents—which is why I'm using all of`iteration.qmd` in the reprex.

### Describe the behavior you expected

<kbd>Cmd-Return</kbd> should always run the current line. This works correctly in RStudio Desktop 2022.07.2+576 on MacOS 13.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: Switching to source mode and back resolves the issue temporarily, but once a new line is inserted again, the problem recurs.

**Comment by kevinushey** [comment]
Also saw this warning in the JS console.

<img width="477" alt="Screen Shot 2022-09-23 at 12 08 35 PM" src="https://user-images.githubusercontent.com/1976582/192040136-82ed54ce-4004-474f-bd07-3536f24948b9.png">

**Comment by kevinushey** [comment]
It looks like the issue might be related to indented chunks (which live as part of a bulleted list)? I can reproduce fairly readily with a document like this:

`````
---
editor: 
  markdown: 
    wrap: sentence
---

# Reprexathon

```{r}
# I'm a chunk!
```

### Indentathon

1.  Here's an indented chunk.

    ```{r}
    # I sure hope I don't break anything!
    ```
`````

**Comment by jmcphers** [comment]
All the code execution happens in the source editor; the warning indicates that the code that aligns the source editor with the visual editor (which we do every time you execute code) isn't seeing a consistent view of the set of chunks. It is almost certainly responsible for the error.

**Comment by hadley** [comment]
It just occurred to me that this setting might also add to the problem:

<img width="332" alt="Screen Shot 2022-09-25 at 09 23 12" src="https://user-images.githubusercontent.com/4196/192148689-c7b41d2b-837f-4cc1-ac5f-4d3d21b18ef9.png">

**Comment by hadley** [comment]
FWIW this is making the visual editor almost unusable for me (and I can't switch back to the released version, because the data corruption there is a worse problem).

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+228
Windows 11, Ubuntu 22.04

Tested with OP example and additional example from Kevin. Both work as expected. I also tried with a few other variations of those 2 examples.

**Comment by hadley** [comment]
I'm still seeing this in 2022.11.0-daily+245 😞

**Comment by hadley** [comment]
Now that I look at it carefully, @kevinushey's reprex doesn't seem to be the same problem as me, because I need to modify chunks to see the issue. I managed to recreate the problem once with this very simple doc:

````
```{r}
1
```

```{r}
2
```

```{r}
3
```
````

But I can't cause it to happen reliably.

**Comment by hadley** [comment]
There's a different race condition where I can sometimes trigger it to send the wrong text once, but when I press `cmd + enter` a second time, it sends the correct text. That seem to be triggered by rapidly pasting in lots of text/chunks so is probably unrelated and not that important.

**Comment by jmcphers** [comment]
I can't seem to get it to reproduce with your example, @hadley. :-(

**Comment by hadley** [comment]
I gave @kevinushey a repro on slack — you need at least two code chunks in a bulleted list at the bottom of the document.

**Comment by hadley** [comment]
Back at my computer. Here's the repro. Create a `.qmd` containing the following code:

````
This is a line.

DELETE ME

```{r}
1
```

-   

    ```{r}
    2
    ```

    ```{r}
    3
    ```
```

Switch to the visual editor, then delete the line that says "delete me". Navigate to the line containing 1 and then press Cmd + enter. The console is sent ````  ```{r} ```` instead of `1`.

**Comment by mikebessuille** [comment]
Per JJ, this is a must-fix for Elsbeth.

**Comment by jmcphers** [comment]
Moved this to Test. @hadley fix should be in build 319 or newer if you want to try it out.

**Comment by hadley** [comment]
DOWNLOADING NOW

**Comment by hadley** [comment]
So far so good!

**Comment by hadley** [comment]
Ok, I hit the problem again, but this time it was because I had accidentally created a corrupted code chunk that looked like this:

````
``` {)}

# They have the same width
str_width(u)
# But a different length
```
````

**Comment by jonvanausdeln** [comment]
When I tried that corrupted chunk, it doesn't execute anything.  The original example works.

**Comment by hadley** [comment]
@jonvanausdeln you would need to put the corrupted chunk somewhere further down the document.

**Comment by jonvanausdeln** [comment]
@kevinushey , should this be moved back to in-progress? Or should this corrupted block be broken out into a separate issue?

**Comment by kevinushey** [comment]
I placed the issue back to in-progress. @jmcphers, do you have the bandwidth to take a look?

**Comment by mikebessuille** [comment]
Is that new problem as critical to fix for Elsbeth?  We are looking to move out anything that isn't absolutely critical at this point...

**Comment by kevinushey** [comment]
@hadley is the existing fix "good enough" or are you still bumping into this on a regular basis?

**Comment by hadley** [comment]
Oh yeah, this is working well for me, thanks!

**Comment by mikebessuille** [comment]
@kevinushey @jonvanausdeln  i feel like if we're going to fix part of this for Elsbeth, and defer the special case, it should be split into a separate issue.

**Comment by jonvanausdeln** [comment]
I agree. I will create a new issue for the special case and close out this one as it resolves the main issue.
