### ISSUE TITLE
rstudio launched from the terminal should properly open a list of files in tabs

### ISSUE THREAD

**Issue by gdevenyi** [rstudio/rstudio#12025]
If I have multiple R files in a directory with, and attempt to open them all in rstudio like so:
```
$ rstudio *R
```

Only the first file in the expanded argument list is loaded. rstudio should load all of them as tabs.

**Comment by ronblum** [comment]
@gdevenyi Thank you for the suggestion! We'll review it as we continue to develop RStudio.

**Comment by gdevenyi** [comment]
This feature request is not stale.

**Comment by gdevenyi** [comment]
This feature request is not stale.

**Comment by gdevenyi** [comment]
This feature request is not stale.

**Comment by kevinushey** [comment]
This appears to be working for me with the latest daily builds of RStudio (tested on macOS + Linux). Can you provide any more details?

**Comment by gdevenyi** [comment]
This does seem to work in
RStudio
2024.09.0 Build 368

**Comment by kevinushey** [comment]
Thanks for confirming!
