### ISSUE TITLE
`install.packages("foo.tar.gz")` does not infer `repos = NULL`

### ISSUE THREAD

**Issue by ms609** [rstudio/rstudio#12034]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Win 10
    R Version       : 4.3.0 devel

### Steps to reproduce the problem
Run
`install.packages("https://github.com/smithlabdurham/palec/archive/refs/tags/2022-09.tar.gz")`
in RStudio

### Describe the problem in detail

I see
```
Warning in install.packages :
  package ‘https://github.com/smithlabdurham/palec/archive/refs/tags/2022-09.tar.gz’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#Installing-packages
```

Manually setting `repos = NULL` installs the package successfully.

### Describe the behavior you expected

When run at the R command line, `repos = NULL` is inferred from the `tar.gz` file ending, per `?install.packages`:

```
Installing package into ‘C:/Users/pjjg18/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from 'pkgs'
trying URL 'https://github.com/smithlabdurham/palec/archive/refs/tags/2022-09.tar.gz'
downloaded 760 KB
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ms609** [comment]
Hi, thanks for taking a look so quickly.  Yes, the `utils::` prefix results in the expected behaviour.

**Comment by jgutman** [comment]
Verified with `install.packages("https://github.com/tidyverse/dplyr/archive/refs/tags/v1.0.10.tar.gz")` on 2022.12.0-daily+270, using Mac OS 12.6
