### ISSUE TITLE
Hangup At Every Start on Windows 10

### ISSUE THREAD

**Issue by drag05** [rstudio/rstudio#12036]
RStudio 2022.07.1 Build 554 has a long hangup at every start. 
From the Log file:

"_2022-09-26T16:58:49.015225Z [rsession-NAME] ERROR system error 10053 (An established connection was aborted by the software in your host machine) [request-uri: /help/library/base/html/library.html]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide\open-source-pipeline\spotted-wakerobin\src\cpp\session\http\SessionHttpConnectionImpl.hpp:156; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide\open-source-pipeline\spotted-wakerobin\src\cpp\session\http\SessionHttpConnectionImpl.hpp:161_"

Deleting/renaming AppData\...\RStudio does not prove to be a real solution.

**Comment by ronblum** [comment]
@drag05 Thank you for raising this! When you say that it's a long hangup, do you mean that RStudio takes a while but eventually starts up? Or it doesn't start at all?

**Comment by drag05** [comment]
@ronblum  Yes, it starts eventually. It worked fine at the first start after deleting the AppData\...\RStudio folder then, started hanging up again next starts. Thank you!
