### ISSUE TITLE
issue regex lookahead

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12032]
`#603A` should not be considered an issue link: 

<img width="177" alt="image" src="https://user-images.githubusercontent.com/2625526/192283067-b3d7925b-8132-4df5-ae16-356adf3e81d7.png">

**Comment by romainfrancois** [comment]
QA: with `test.R` containing: 


```r
#603a
#603B
#603
```

only the last line should be considered a potential issue link: 

<img width="237" alt="image" src="https://user-images.githubusercontent.com/2625526/192288607-49d0301a-213f-4152-9553-f2c2b71803a1.png">

**Comment by kevinushey** [comment]
FWIW one other implementation option would be to use a negative lookahead, e.g.

https://github.com/rstudio/rstudio/blob/edef134be556230a6107f25ab2e133bc374dcc93/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorBackgroundLinkHighlighter.java#L772

Maybe:

```
((?:github|gitlab)::)?([-a-zA-Z0-9.]+/[-a-zA-Z0-9.]+)?#([0-9]+)(?![a-zA-Z])
```

**Comment by romainfrancois** [comment]
I started with this, but then it matched `#60`

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+245
Windows 11, Ubuntu 22.04

Tested several character/number combinations, only correctly formed possible issue numbers gave the link.
