### ISSUE TITLE
Crash on latest Rstudio startup with Arch-derivative Linux

### ISSUE THREAD

**Issue by bshor** [rstudio/rstudio#12050]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2+576-1
    OS Version      :  Garuda (Arch) Linux, kernel 5.19.9
    R Version       : 4.2.1

### Steps to reproduce the problem

Startup crashes. No other step needed.

### Describe the problem in detail

I have been using the latest version of RStudio with R 4.2.1 on an Arch Linux installation for many months. It has been working great, until today when it crashes upon startup when launched through the GUI or terminal. Here is the error message:
```

TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/home/boris/.local/share/rstudio/log/rdesktop.log'.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
2022-09-28T15:04:05.331288Z [rdesktop] ERROR system error 2 (No such file or directory) [path: /usr/lib/rstudio/bin/resources/stylesheets/rstudio-gnome-light.qss]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::openForRead(std::shared_ptr<std::basic_istream<char> >&) const src/cpp/shared_core/FilePath.cpp:1462; LOGGED FROM: void rstudio::desktop::applyDesktopTheme(QWidget*, bool) src/cpp/desktop/DesktopUtils.cpp:176
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
fish: Job 1, 'rstudio' terminated by signal SIGABRT (Abort)
```

This is with the "rstudio" package, but I also get the same error when I use alternative packages like "rstudio-desktop-bin" or "rstudio-desktop-daily-bin" or "rstudio-desktop-preview-bin".

Also, adding --no-sandbox doesn't fix the problem.

### Describe the behavior you expected

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9666428/diagnostics-report.txt)

**Comment by bshor** [comment]
Thank you for letting me know. I can understand RStudio's position.

I'd love to install a daily build, but without an AUR package, I'm leery of trying to "roll my own" by converting a DEB.

**Comment by jmcphers** [comment]
You could try one of the installer-less builds -- just untar into a folder and run from there.
