### ISSUE TITLE
matplotlib hooks don't seem to fire with matplotlib==3.6.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#12053]
RStudio tries to detect when matplotlib is loaded here:

https://github.com/rstudio/rstudio/blob/8e993391c5037935a9dd5a7a1354448701571f9c/src/cpp/session/modules/SessionReticulate.R#L151-L160

However, these hooks don't seem to be running if `matplotlib==3.6.0` is installed when running Python code of the form:

```
from matplotlib import pyplot as plt
```

One can exercise a similar scenario from R with:

```
library(reticulate)
py_install("matplotlib==3.6.0")
options(reticulate.logModuleLoad = TRUE)
py_run_string("from matplotlib import pyplot as plt")
```

and these are all the `matplotlib` modules we see loaded...

```
Loaded module 'matplotlib
Loaded module 'matplotlib._cm'
Loaded module 'matplotlib._cm_listed'
Loaded module 'matplotlib._enums'
Loaded module 'matplotlib._image'
Loaded module 'matplotlib._path'
Loaded module 'matplotlib._pylab_helpers'
Loaded module 'matplotlib.axes._axes'
Loaded module 'matplotlib.axes._base'
Loaded module 'matplotlib.axes._secondary_axes'
Loaded module 'matplotlib.axis'
Loaded module 'matplotlib.backend_bases'
Loaded module 'matplotlib.backend_managers'
Loaded module 'matplotlib.category'
Loaded module 'matplotlib.cm'
Loaded module 'matplotlib.colorbar'
Loaded module 'matplotlib.colors'
Loaded module 'matplotlib.container'
Loaded module 'matplotlib.dates'
Loaded module 'matplotlib.figure'
Loaded module 'matplotlib.fontconfig_pattern'
Loaded module 'matplotlib.gridspec'
Loaded module 'matplotlib.image'
Loaded module 'matplotlib.legend'
Loaded module 'matplotlib.mathtext'
Loaded module 'matplotlib.mlab'
Loaded module 'matplotlib.quiver'
Loaded module 'matplotlib.spines'
Loaded module 'matplotlib.stackplot'
Loaded module 'matplotlib.streamplot'
Loaded module 'matplotlib.table'
Loaded module 'matplotlib.text'
Loaded module 'matplotlib.ticker'
Loaded module 'matplotlib.tri'
```

Marking this as a regression as this is something that technically did work before.

**Comment by jgutman** [comment]
I'm trying this out with RStudio going back to GO but not really seeing this working. Is there some expected behavior with an older version of the IDE/older version of matplotlib that I'm missing @kevinushey ?

**Comment by kevinushey** [comment]
This might actually be a bug in `reticulate`'s import hook:

https://github.com/rstudio/reticulate/blob/bb2ed00609437dc8bcacb0cc34849177e4573a17/inst/python/rpytools/loader.py#L27-L28

We need to be using the `fromlist()` to resolve the module name properly.

**Comment by kevinushey** [comment]
I'm going to take a look.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+279 Desktop on Windows 11, Ubuntu 22.04

The plot appears in the plots pane, and the IDE remains responsive.
