### ISSUE TITLE
Custom completions driven by the function 

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12057]
Followup to #11987 

In some cases, the ide provides the columns as potential completions: 

<img width="476" alt="image" src="https://user-images.githubusercontent.com/2625526/193005403-8bd40ef2-1dce-40d9-8889-802fb460a644.png">

But this: 
 - is not particularly useful, except 
 - is based on some heuristics

It could be more useful to get help from the function, from the description of the `...`. For example, `mutate()` has this for `...` : 

```r
#' @param ... <[`data-masking`][dplyr_data_masking]> Name-value pairs.
#'   The name gives the name of the column in the output.
#'
#'   The value can be:
#'
#'   * A vector of length 1, which will be recycled to the correct length.
#'   * A vector the same length as the current group (or the whole data frame
#'     if ungrouped).
#'   * `NULL`, to remove the column.
#'   * A data frame or tibble, to create multiple columns in the output.
```

Could offer : 
  - `${1:result} = ${2:value}` snippet to create/mutate a variable
  - `${1:result} = NULL` snippet to remove one. 
  - some hint about maybe using `across()` for the last item (`* A data frame or tibble, to create multiple columns in the output.` 

We do hold the `mutate` function in `.rs.getCompletionsFunction` here: 

https://github.com/rstudio/rstudio/blob/41394b2e4f7be1811ad8ef501db23b74af0f0d24/src/cpp/session/modules/SessionRCompletions.R#L729-L739

so we could involve it for better information.

**Comment by romainfrancois** [comment]
Similarly, the `.keep=` argument of `mutate.data.frame()` is documented as: 

```r
#' @param .keep
#'   Control which columns from `.data` are retained in the output. Grouping
#'   columns and columns created by `...` are always kept.
#'
#'   * `"all"` retains all columns from `.data`. This is the default.
#'   * `"used"` retains only the columns used in `...` to create new
#'     columns. This is useful for checking your work, as it displays inputs
#'     and outputs side-by-side.
#'   * `"unused"` retains only the columns _not_ used in `...` to create new
#'     columns. This is useful if you generate new columns, but no longer need
#'     the columns used to generate them.
#'   * `"none"` doesn't retain any extra columns from `.data`. Only the grouping
#'     variables and columns created by `...` are kept.
```

It would be great to have some way to surface this information. 

`.before` and `.after` are documented as: 

```r
#' @param .before,.after
#'   <[`tidy-select`][dplyr_tidy_select]> Optionally, control where new columns
#'   should appear (the default is to add to the right hand side). See
#'   [relocate()] for more details.
```

and so in that case completing with one column or something tidy select aware would be useful

**Comment by romainfrancois** [comment]
Another example, `pr_fetch()` could want to offer some possibilities, i.e. to improve this experience:

https://user-images.githubusercontent.com/2625526/193779370-4f0c7716-a16d-48f2-b2be-41965f385103.mov

The list could show some basic info about possible completions (value, maybe author and title) and the second popup (the one usually showing help page) could have some more information to get a better glimpse of the pr. 

Perhaps such completions would only be allowed when explicit (when the user pressed `<TAB>`) because retrieving the information (with `usethis:::pr_list()` or something) is not instant.

**Comment by olivroy** [comment]
Think this is still interesting to explore. Possibly related to https://github.com/rstudio/rstudio/issues/2200
