### ISSUE TITLE
Knitting RMarkdown crashes RStudio session after new installation

### ISSUE THREAD

**Issue by strametta** [rstudio/rstudio#12068]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.7.2.576
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem
1) Install R
2) Install RStudio
3) Create an empty R Markdown document and save as `tmp.Rmd` in the default R directory (`~/`)
4) Push "Knit" button 
5) RStudio session crashes

    
### Describe the problem in detail
I learn biostatistics and RStudio is compulsory in my class. R and RStudio are new for me: I have not used these pieces of software before.
While trying to Knit R Markdown document, RStudio session crashes with this message:  
![Screenshot (547)](https://user-images.githubusercontent.com/114688785/193220980-29faa0df-a7c0-4acf-b486-fc46d2b0fab2.png) 

I tried to:

1) Reset RStudio state as written in https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
2) Delete/Rename all R, RStudio and quarto related folders in AppData/Local and AppData/Roaming directories.
3) Uninstall and reinstall R and RStudio
4) Restart computer
5) Uninstall R tools
6) Create a subfolder and create an empty RMarkdown in it.

These things did not help solving the issue.

If I convert the subfolder into an RStudio project and open it as a project, the knitting issue disappears.

### Describe the behavior you expected

I expect RStudio to work without crashes. I expect a document to be knitted correctly when no RStudio project is open.

<details><summary>Technical info</summary>

```
> sessionInfo() 
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.1  fastmap_1.1.0   htmltools_0.5.3 tools_4.2.1    
 [5] rstudioapi_0.14 yaml_2.3.5      rmarkdown_2.16  knitr_1.40     
 [9] xfun_0.33       digest_0.6.29   rlang_1.0.6     evaluate_0.16 
```

[diagnostics-report--2022-09-30.zip](https://github.com/rstudio/rstudio/files/9682070/diagnostics-report--2022-09-30.zip)

</details>

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, nothing stands out from the diagnostics report. Is there any chance you would be able to provide us with a Windows Minidump? Some instructions follow below.

---

First, you need to enable Minidumps explicitly. Microsoft provides instructions at https://docs.microsoft.com/en-us/windows/desktop/wer/collecting-user-mode-dumps. If you'd like to automatically enable user-mode dumps, you can also try importing the following registry file:

https://gist.github.com/kevinushey/a4878f7fceef1deacedae94d31c5c744

Restart your computer afterwards to ensure the registry updates take effect.

Next, perform the action that causes the crash to occur. If we're lucky, the crash dump will be written to a folder at:

    C:\Users\%USERNAME%\AppData\Local\CrashDumps

replacing %USERNAME% with your Windows username as appropriate. Note that AppData is a hidden folder, so if you're trying to navigate to it in the Windows explorer you'll need to ensure hidden files and directories are made visible.

Then, within the folder, you should find files of the form:

    rsession*.exe.<id>.dmp

Please share the file with us. If the file is large, you might consider uploading it to a cloud storage provider (DropBox, Google Drive, Windows OneDrive) and sharing a link to that file for us to examine.

If you'd like to later disable Windows minidumps, you can run the following registry file:

https://gist.github.com/kevinushey/c2fb6b700f92d4b7c07d4d1035ba21aa

**Comment by mvolar** [comment]
Hello, 

Sorry to say I have the same problem when kniting to html after updating to the latest R/Rstudio version:
```
R 4.2.2
Rstudio 2022.12.0 Build 353
```
What's interesting is that this error only happens when I try to knit the file which is stored with a Desktop path. All other paths other than Desktop work fine (including other user folders also work Documents, Pictures etc) as well as all other hard drives. I have also tried using top level Desktop path (i.e. Dekstop/test.Rmd) and hide it in a folder (Dekstop/fold1/fold2/fold3/test.Rmd) and still crashes the same way.

Previously I had no problems with kniting, unfortunately I updated both R and R studio at the same time, and I don't want to fiddle with downgrading to find out exactly what and where went wrong.

The minidump is located on the following link, rared (full size around 350mb):

https://www.mediafire.com/file/1t6ol2yiyk9y932/rsession-utf8.exe.12896.rar/file

```
checksums:
Name: rsession-utf8.exe.12896.rar
Size: 87701056 bytes (83 MiB)
CRC32: CD7EDEB0
CRC64: AB95FC9CA9F58BD7
SHA256: 1D6FDCF202BDD9E58FEE9662F485072383172E590CE1228C8D1A43432E984423
SHA1: D42F6039ED0B3AD917BA15894B34D1AE097BD886
BLAKE2sp: 27798D43C59B924ABD368960CC76D6C6D2EC0EC9EC48DEBA084020D272527F5D

```

**Comment by kevinushey** [comment]
This is the call stack I see:

<img width="870" alt="Screenshot 2022-12-30 at 12 23 59 PM" src="https://user-images.githubusercontent.com/1976582/210034359-20680908-58ca-4b4a-9d63-39876ef8ab31.png">

But unfortunately, without debug symbols we don't really have a great idea of what's going on.

Are you by any chance able to reproduce the issue with one of the debug R installations from https://contributor.r-project.org/svn-dashboard/? That would hopefully give us symbol names so we would have a better idea of where exactly the crash is happening.

**Comment by mvolar** [comment]
Can you just give me a checklist of what I would need to do in order to pull/compile the debug R installation on Windows and link it to my Rsstudio session? I am not a software developer so the language is a bit esoteric to me.
