### ISSUE TITLE
Update French UI strings for Elsbeth Geranium release

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12064]
Any new or modified UI strings added in Elsbeth Geranium will need to be translated into French. This involves:

* run script to generate diff report (@gtritchie will do this)
* have someone fluent in French provide the translations
* update / add them in the French property files

This should be done relatively close to the end of the release cycle, when we're done with significant UI changes.

Note we aren't currently localizing pro-only strings, so only have to worry about open-source at this time.

**Comment by mikebessuille** [comment]
We should run the script that identifies the diff, and if it's only a handful of string changes or additions we can ask RStudio french speakers (Romain :)) to translate for us.  Otherwise we could delay this.

**Comment by mikebessuille** [comment]
@romainfrancois could you please run the script Gary created, to generate the  list of new / changed strings, and translate them if there aren't very many?

**Comment by gtritchie** [comment]
Yes I will do that. Figured I'd wait until early November and do it then.

**Comment by gtritchie** [comment]
I've updated the i18n wiki page to mention the "script Gary created" (aka locdiff): https://github.com/rstudio/rstudio/wiki/Internationalization-(i18n)#string-localization-process

The tool lives here: https://github.com/rstudio/rstudio/tree/main/src/gwt/tools/locdiff

I need to make some tweaks to the tool to support the Electron string resource files (those were new in the last release so was no need to "diff" them).

**Comment by gtritchie** [comment]
@romainfrancois I'm attaching an Excel spreadsheet showing all new strings, and strings where the English text was changed.

This was a diff (using loctool) comparing `e7373ef8 - Spotted Wakerobin patch 2 (2022.07.2+576)` with `main` at `9b707e2e`.

There are lots of columns, if you scroll right you'll see I've included the old and current English text, and the old and current French text, which should make it easy to identify where edits are needed.

The Electron strings all live in one file: https://github.com/rstudio/rstudio/blob/main/src/node/desktop/src/assets/locales/fr.json

Let me know if you have any questions (or need the data in something other than an Excel spreadsheet).

[locdiff.xlsx](https://github.com/rstudio/rstudio/files/9824596/locdiff.xlsx)

**Comment by romainfrancois** [comment]
Not sure what `Test` means here, we can either close this or keep it open so that we do it again at a strategic time.

**Comment by mikebessuille** [comment]
I think in this case, test means to validate that the correctly translated strings appear in the UI when running the French version.   After that, this issue should be closed (and we should create a new translation issue for next release).

**Comment by jonvanausdeln** [comment]
I checked that all the strings were translated when changing to French. I can't attest to the accuracy of the translation, but I feel confident enough to close this out.

Tested on 2022.12.0-daily+284
