### ISSUE TITLE
column completion type with long pipe chains

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12067]
From https://github.com/rstudio/rstudio/pull/11987#issuecomment-1262531341 : 

One other thing you might want to take a look at -- in longer chains, we filter completions in a separate way. For example, code around here:

https://github.com/rstudio/rstudio/blob/8efe31a14b9881572cecef97d1f3089ca8a1a9b2/src/gwt/acesupport/acemode/r_code_model.js#L345-L373

The intention being that in code like this:

```
mtcars %>%
  select(mpg) %>%
  mutate(|)
```

we "know" the only column in scope is `mpg`, so we don't need to provide completions from `mpg` itself. Right now that's not getting your new UI treatment:

<img width="592" alt="Screen Shot 2022-09-29 at 9 35 46 AM" src="https://user-images.githubusercontent.com/1976582/193088999-40b95711-278e-43f5-9ccd-e0e2d8a97b55.png">

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+265 Desktop Windows, and Server on Ubuntu 22.04

Autocomplete correctly provides the selected column.
