### ISSUE TITLE
CMakeGlobals.txt: RSTUDIO_VERSION_PATCH should be RSTUDIO_VERSION_SUFFIX?

### ISSUE THREAD

**Issue by HenrikBengtsson** [rstudio/rstudio#12066]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.07.2-576
    OS Version      : Linux
    R Version       : N/A

### Describe the problem in detail

Was 

https://github.com/rstudio/rstudio/blob/4f7063b13bb0bae8377639a36d3ff4b7626de6e3/CMakeGlobals.txt#L46-L50

meant to use:

```
if ("$ENV{RSTUDIO_VERSION_SUFFIX}" STREQUAL "")
```

?  It looks like the current one is a cut'n'paste mistake from similar statements just above.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
This is specific to local builds for development. If there's no issue with official builds and the versioning, I don't see an issue here.
