### ISSUE TITLE
RStudio Server on Ubuntu does not show next and previous arrows in the View() properly when there are more than 50 columns

### ISSUE THREAD

**Issue by m1270** [rstudio/rstudio#12060]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.07.01 Build 554
    OS Version      : Ubuntu 22.04
    R Version       : 4.1.2

### Steps to reproduce the problem
test <- matrix(runif(1000), ncol = 100)
View(test)

### Describe the problem in detail
In "View" mode when the number of columns are more than 50 the next and previous arrows are not shown properly. See the attached screenshots from the Desktop and Server RStudios.

### Describe the behavior you expected
See the attached photo

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![New RStudio Server Ubuntu](https://user-images.githubusercontent.com/75230162/193084040-6ea71991-8c3f-4f16-b55a-d769d9ea9e66.png)
![Old Windows RStudio](https://user-images.githubusercontent.com/75230162/193084049-837ebd5d-82fe-4ef4-8ef5-1ecf56c7126b.png)

**Comment by jonvanausdeln** [comment]
@m1270 Thank you for your reporting your problem!  This issue has been fixed for our next release, targeted for later this year. Please see issue https://github.com/rstudio/rstudio/issues/9623 

If you'd like to try an early build, our daily builds can be found at https://dailies.rstudio.com/
