### ISSUE TITLE
spaces wrongly inserted automatically when writing `@examples` in roxygen

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12070]
Since https://github.com/rstudio/rstudio/pull/12016 when writing code in roxygen `#' @examples` spaces get inserted automatically because of auto suggest completion. 

```r
#' @examples
#'
#' cod|
```

inserts a space automatically, and leaves the editor at: 

```r
#' @examples
#'
#' cod |
```

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+263 windows 11

Space is correctly included only after autocomplete.
