### ISSUE TITLE
Double clicking on words when renaming in Files pane doesn't select the whole word

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#12079]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : macOS 12.6
    R Version       : 4.2.1

### Steps to reproduce the problem

- Check the box for a file in Files pane and click on Rename
- Double click on a word in the file name

### Describe the problem in detail

Double-clicking doesn't select the whole word. See the video below.

https://user-images.githubusercontent.com/5965649/193425824-b653fc17-dbb6-419a-a2b0-87ffacd8fbb7.mov

### Describe the behavior you expected

I expected the whole word to be selected. That's the behaviour in the Mac Finder.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, I wasn't able to reproduce locally.

If I watch the video closely, it looks like the whole word gets briefly selected, and then the selection reverts -- almost like the whole word was selected on the first click, and then later the selection was shortened after the second click.

Can you provide any other details that might help me reproduce locally? Are you using an external mouse, or the built-in trackpad, or something else?

**Comment by mine-cetinkaya-rundel** [comment]
I am using my built-in mouse. Indeed I'm observing that the whole word does get selected briefly and then roughly only up to where my cursor is. I tried with file names that are single-word and multi-word and I'm seeing the same behaviour.

I am certain I didn't experience this a while back (but I'm talking multiple versions ago, it just took me a while to report it). And since you're unable to reproduce it too, this is likely just an issue on my end.

**Comment by jonvanausdeln** [comment]
I just tried with Spotted Wakerobin and a new daily build (2022.11.0-daily+240) and I'm also unable to reproduce the problem.
