### ISSUE TITLE
RStudio startup error while loading shared libraries: libssl.so.1.1 (Fedora 36)

### ISSUE THREAD

**Issue by pedrohgodoys** [rstudio/rstudio#12080]
# System details
- R Edition: RStudio Desktop
- RStudio Version: RStudio 2022.07.2+576 "Spotted Wakerobin"
- OS Version: Fedora Workstation 36 (kernel: 5.19.12-200.fc36.x86_64)
- R Version: 4.1.3 (2022-03-10)
____

# Description
I've just got to Fedora 36 (Workstation) from years of debian-based distros. So far, everything is so much better, and the only thing that is a **must** for me is RStudio. My problem is **exactly** the one reported by @znmeb at the closed issue [#4612 ](https://github.com/rstudio/rstudio/issues/4612#top) but remains unsolved. 

## Steps to reproduce the problem
Once (unfortunately) we don't have a Flatpak or even AppImage (as shown by @jmcphers at #3079), I tried downloading directly from Fedora's repo with `sudo dnf install`. It actually was pretty smooth, but the most updated package was RStudio version _2022.02.*_, thus, the packages I need to use do not function properly (or at all). 

I removed it completely before download the _.rpm_ file of [RStudio 2022.07.2+576 - Fedora 34/Red Hat 8 (64-bit)](https://s3.amazonaws.com/rstudio-ide-build/desktop/rhel8/x86_64/rstudio-2022.07.2-576-x86_64.rpm), and install it with `sudo dnf install <file-name>.rpm`. No unexpected terminal output happened.

### Problem details
When I click the icon, nothing happened, so I tried running `rstudio` at the terminal, returning the following output: `rstudio: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory`.

### Describe the behavior you expected
The expected behaviour was to just open RStudio.

### Additional Information
I did tried out installing `compat-openssl10.x86_64`, `compat-openssl11.x86_64`, `openssl-devel` and `openssl-libs-1:3.0.5-1.fc36.x86_64`, as suggested by @nilesh-iiita, @yulijia at that particular issue. Everything just does not work properly. Thus my last alternative was to try the Electron version at [RStudio 2022.07.2+576 - Fedora 34/Red Hat 8 (64-bit)](https://s3.amazonaws.com/rstudio-ide-build/electron/rhel8/x86_64/rstudio-2022.07.2-576-x86_64.rpm).

Installation: `sudo rpm -ihv rstudio-2022.07.2-576-electron-x86_64.rpm`

### Terminal output:
```
warning: rstudio-2022.07.2-576-electron-x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e331692f: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:rstudio-2022.07.2+576-1          ################################# [100%]
[pedro@fedora Downloads]$ rstudio 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[15061:1001/155238.795990:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
[15061:1001/155243.106946:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[15061:1001/155259.634903:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[15061:1001/155259.642464:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### R Session Startup Failure Report
![image](https://user-images.githubusercontent.com/45294360/193424680-5aa503b7-3a7f-4a5a-9471-daaf75473675.png)

**Error message:** `[No error available]`

**Process Output:** The R session exited with code 127. 
**Error output:** `/usr/lib/rstudio/resources/app/bin/rsession: error while loading shared libraries: libssl.so.1.1: wrong ELF class: ELFCLASS32`
**Standard output:** `[No output emitted]`

**Logs:** */home/pedro/.local/share/rstudio/log/rsession-pedro.log*
```
2022-10-01T08:51:17.984006Z [rsession-pedro] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-10-01T08:56:53.314892Z [rsession-pedro] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
2022-10-01T08:56:53.314892Z [rsession-pedro] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335

```
___

Still, anything works.
Does someone know how to solve it or suggest an alternative? I take most of the RStudio IDE, and I don't want to change it or change Fedora.

Thank you.
____

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
The problem could be just that you're using the wrong build of RStudio! You're on Fedora 36, but are using the binaries for Fedora 34 instead. They are not compatible. 

Would you be willing to try the Fedora 36 binary to see if that resolves your issue? This one ought to work:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/fedora36/2022-07-2-576/

**Comment by pedrohgodoys** [comment]
I never knew that another _download page_ existed besides the one I hyperlinked to previously. **It totally worked!**
![image](https://user-images.githubusercontent.com/45294360/193513276-7ccfc3bc-f871-4dd5-a320-a9109a0a7b73.png)

Thank you very much @jmcphers !

**Comment by jmcphers** [comment]
Nice, glad that's all it was! Fedora 36 support was a beta feature for the previous release, so isn't on the main download page yet. It will be fully supported in the upcoming release (2022.12).

**Comment by pearaujo** [comment]
do you have the link for Debian Bookworm ?
