### ISSUE TITLE
FR: support standard ANSI hyperlink sequence terminator

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/rstudio#12085]
The current sequence with the `\a` terminator is not standard, although it is handled by most terminals. The `ST` (`ESC` `\`) terminator is POSIX standard. Ideally both would be allowed in RStudio. More here: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#the-escape-sequence

This would allow much easier manipulation of ANSI strings, as the `\a` terminator requires special handling.

CC @romainfrancois

**Comment by jgutman** [comment]
Verified in 2022.12.0-daily+270 on Mac OS 12.6
