### ISSUE TITLE
"Find In Files" won't load in file found in results if using subdirectory in search

### ISSUE THREAD

**Issue by vonGameTheory** [rstudio/rstudio#12082]
### System details

    RStudio Edition : Server [Open Source]
    RStudio Version : 2022.7.1.554
    OS Version      : Manjaro Linux
    R Version       : R version 4.2.1 (2022-06-23)

### Steps to reproduce the problem

    1) Be in a project (haven't tried another way -- I always have an active project)
    2) Shift-Ctrl-F to bring up "find in files" search
    3) Hit browse button to set search directory to a subdirectory in the project
    4) Search for something you know will be found in that subdirectory (or deeper), wait for the results
    5) Click on some line in the displayed results -- this should load in the matching file
    6) But it doesn't -- gives not found error.  Can only assume it is trying to use the wrong path.
    
### Describe the problem in detail
    
In this version of Rstudio Server when I use the "find in files" (shift-ctrl-f) search *and* I use the "browse" button to limit the search to a subdirectory of the project directory, then when the results come up they are no longer clickable to bring up the found file -- gives an file not found error.  Works fine if I keep it at the project root directory.  So to be clear the search is working fine and it finds the results, but I am unable to click on a line in the results to then load in the file into studio.  If I do the same search without limiting it to the subdirectory, then it works as expected (I just have to sift through all the extra results unnecessarily because I know what subdirectory it is in so this is just a pain when searching for terms that have many matches).

### Describe the behavior you expected
    
To load in the relevant file when clicking on results after searching with a subdirectory.  Pretty sure this always used to work.

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately I wasn't able to reproduce. Are you able to provide any more details?

It might help to know the actual file path that's being presented in the Find in Files dialog -- does it look correct?

After attempting to open a file from the Find in Files dialog output, you can also use `Help -> Diagnostics -> Request Log`. There should be a short bar for the `stat` request. If you click on it, you should see a summary of the request + response that happened for that action. For example:

<img width="527" alt="Screen Shot 2022-10-03 at 10 43 29 AM" src="https://user-images.githubusercontent.com/1976582/193643673-6371254e-4958-413d-9255-fb9637613d50.png">

Can you share what you see there?

**Comment by vonGameTheory** [comment]
Yes, the path is correct because it does find the correct results -- just can't load in the file by clicking on the result (when using subdirectory of project root).  Looking at the log as you suggest I see the difference is the "exists" field is false when it doesn't work and true when it does, but it is showing the correct path in the response "path" & "raw_path" in both cases.  I can walk-through it and get some screenshots later.

**Comment by kevinushey** [comment]
> Yes, the path is correct because it does find the correct results -- just can't load in the file by clicking on the result (when using subdirectory of project root).

Interesting; is it possible that something permissions-related is preventing RStudio from accessing / opening these files? Or maybe the way that RStudio queries the file for existence is at fault?

Are you able to open these files "manually" in the IDE, e.g. through the Files pane?

**Comment by vonGameTheory** [comment]
Ok, I misspoke yesterday.  In the log under "stat" the displayed paths ("path" & "rawpath") are NOT correct when using subdirectory -- the subdirectory is NOT in the path.  (The files themselves had a prefix similar to the subdirectory that I was seeing I guess.)  

So I did try this on a fresh test project, same result.  I also tried searching with a directory backed out one level from the project root and again you can't load in any of the results (even though it finds them).  So it only works when the search directory matches the project root exactly.

![Screen_Capture_-_Oct_4__9_44_AM](https://user-images.githubusercontent.com/15053894/193837679-de7744f5-e738-414d-a93a-1e5c7aaf2516.png)


^ this result was from search with subdirectory (projectroot = "testproject" with subdirectory called "subdir"), and as you see the subdir is missing from the path.  Here was search box:
![search_box](https://user-images.githubusercontent.com/15053894/193838238-417e9ac8-f891-4430-b9e4-2dac6fd35c80.png)



which finds this file in the subdir
![search_results](https://user-images.githubusercontent.com/15053894/193838560-5408f8a1-ccf0-4a05-aed1-3841dc40aa22.png)


but if you click on the result to open the file  you get and giving the log output above
![search_error](https://user-images.githubusercontent.com/15053894/193838657-bfba32aa-e778-4ed3-8cec-f7b5d3728970.png)

**Comment by kevinushey** [comment]
Okay, got it! Thank you for the extra feedback; I was able to reproduce locally now. Confirming the reproduction steps:

1. Create a new project somewhere in your home directory,
2. Create a subdirectory in that project called `subdir`,
3. Create a file `subdir/hello.R` with the contents `print("Hello world!")`,
4. Open Find in Files, and change the "Search in:" dialog to point at `subdir`,
5. Try searching for "hello".

The search results are presented, but only the name of the file (and not the sub-directory in which it was searched) is included.

**Comment by kevinushey** [comment]
Using `RSTUDIO_GREP_DEBUG`, I see that `grep` on macOS includes a leading `./` on the path returned:

```
grep '--binary-files=without-match' '-rHn' '--color=always' '--devices=skip' '-i' '-F' '-f' '/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/RtmpTYoZvg/rs_grepc2a824437090.txt' '--include=*.r' '--include=*.R'
stdout: ./hello.R:1:print("Hello world!")
```

But on Linux, I'm just seeing the file name directly:

```
grep '--binary-files=without-match' '-rHn' '--color=always' '--devices=skip' '-i' '-F' '-f' '/tmp/RtmpG9EcuN/rs_grep51401eaf08c7.txt'
stdout: hello.R:1:print("Hello, world!")
```

**Comment by vonGameTheory** [comment]
Yeah, the search results as displayed are ok (with the correct path), just won't open the file into the IDE if you click on the result.  (Missing subdirectory in the path only shows in the diagnostic "stat" entry.)

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+258 
Windows 11 Desktop, Ubuntu 22.04 desktop & server

Tested with different files in different subdirectories. Search results were correct, and files opened without issue from search panel.
