### ISSUE TITLE
FR: line and column numbers as URL fragments in ANSI hyperlinks

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/rstudio#12086]
It would be great to allow specifying line and column numbers in `file://` URLs as fragments, e.g. `file:///path/to/file#100:5`. The issue with the currently supported `line` and `col` parameters is that they are not passed to the URL handlers. If the data is part of the URL, then there is no such problem. iTerm2 handles this automatically: https://iterm2.com/documentation-escape-codes.html

CC @romainfrancois

**Comment by jgutman** [comment]
Tested with `cli::style_hyperlink("file", paste0("file://", file, "#12:3"))` [compare `str(cli::style_hyperlink("file", paste0("file://", file, "#12:3")))` versus `str(cli::style_hyperlink("file", paste0("file://", file), c(line = 12, col = 3)))`]
Verified on 2022.12.0-daily+270 with Mac OS 12.6
