### ISSUE TITLE
RStudio doesn't start in Fedora 37 beta due to issues with libssl.so.1.1 libraries

### ISSUE THREAD

**Issue by concienciadesventurada** [rstudio/rstudio#12083]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.2+576 x86_64-redhat-linux-gnu (64-bit)
    OS Version      :  Fedora Linux 37 (Workstation Edition Prerelease)
    R Version       : 4.2.1

### Steps to reproduce the problem

All this in a fresh install of Fedora Linux 37 Workstation, currently in beta.

## Via .rpm

1. Directly downloading the .rpm from the RStudio downloads page.
2. Making a local install with `sudo yum localinstall rstudio-2022.07.2-576-x86_64.rpm`
3. Executing RStudio via terminal with `rstudio`

## Via `dnf`

1. Installing RStudio via terminal with `sudo dnf install rstudio-desktop`
2. Executing RStudio via terminal with `rstudio`

### Describe the problem in detail

Once `rstudio` is started the console retrieves the following error:

`rstudio: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

### Describe the behavior you expected

Opening RStudio normally.

### A viable workaround

#4612 available [here](https://github.com/rstudio/rstudio/issues/4612) contained multiple mentions of different `compat-openssl1.0`, package currently not listed in the Fedora repository. 

Nowadays its enough to enter `sudo dnf install openssl1.1` before or after installing, although it should be implemented as a dependency.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Which download from the downloads page did you use, exactly? There's one compatible with Fedora 36 that might work:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/fedora36/2022-07-2-576/

**Comment by 3bdolly** [comment]
sudo dnf install libssl.so.1.1
Worked for me

**Comment by jzavalar** [comment]
I installed ```R``` and next ```RStudio 2022.12.0 Build 353``` and it worked very well for me:
```$ sudo dnf update```
```$ sudo dnf install R```
```$ sudo dnf install rstudio-desktop```
