### ISSUE TITLE
FR: change hyperlink scheme

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/rstudio#12084]
A requests for changing how RStudio handles hyperlinks, to make it easier to use hyperlinks in other environments.

I would be nice to change the URL schemes, so they do not contain a `:`. The OS parses the scheme until the first `:` only, so for `ide:help:pkg::fun` the scheme will be `ide`, which is very generic. I suggest to change `ide:help` to `x-r-help`, `ide:run` to `x-r-run` and `ide:vignette` to `x-r-vignette`. The `x-` prefix is suggested by some guides and many custom schemes have this form on macOS. Ideally the old scheme would be still supported, so older versions of cli will still work with newer versions of the IDE. With the new schemes, it is easier to define URL handlers on macOS.

We could also support similar schemes for Python, etc., e.g. `x-py-help`.

CC @romainfrancois

**Comment by romainfrancois** [comment]
cc @isabelizimm @machow. Is there something similar in 🐍 world ? Would `x-py-run:<python code>` and `x-py-help:<a python thing>` make sense ?

**Comment by machow** [comment]
I'm not too familiar with these hyperlink schemes -- but maybe one thing similar to it is the format sphinx uses to represent links to API docs?

```python
from sphinx.util.inventory import InventoryFile
from os import path

SQLALCHEMY_DOCS_URL = "https://docs.sqlalchemy.org/"
SQLALCHEMY_INV_URL = f"{SQLALCHEMY_DOCS_URL}/objects.inv"

with open("objects_sqla.inv", "rb") as f:
    inv = InventoryFile.load(f, SQLALCHEMY_DOCS_URL, path.join)
```

```python
list(inv)
```

```
# output
['py:module',
 'py:function',
 'py:parameter',
 'py:class',
 'py:method',
 'py:attribute',
 'py:exception',
 'py:data',
 'std:label',
 'std:term',
 'std:doc']
```

```python
inv["py:function"]["sqlalchemy.sql.expression.intersect"]
```

```
# output
('SQLAlchemy',
 '1.4',
 'https://docs.sqlalchemy.org/core/selectable.html#sqlalchemy.sql.expression.intersect',
 '-')
```

This is how sphinx could know to make `` :py:function:`sqlalchemy.sql.expression.intersect` `` a link to the URL in the above output. Even python.org publishes an inventory file at https://docs.python.org/3/objects.inv, so it's easy to go from some function name to the docs.

**Comment by machow** [comment]
Wait -- reading again, it does seem more like a `x-py-run`, `x-py-help` (which might call the `help()` function) type situation? But no idea what IDEs tend to use 😅

**Comment by romainfrancois** [comment]
yeah, sorry for the lack of context. What we have now in R is links like: `"x-r-help:dplyr::across"` bring the help page of `dplyr::across()` 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/2625526/193986461-361ffa07-78ac-424c-89d8-2cd0f5e3a426.png">

I'll open another issue for `x-py-help` and `x-py-run` schemes.

**Comment by gaborcsardi** [comment]
Just like `x-r-run` is restricted, I think we should be very careful with `x-py-run` as well.

**Comment by romainfrancois** [comment]
Yeah I'll open separate issues for `x-py-run` and `x-py-help` and let them be commented for a while.
