### ISSUE TITLE
Support devcontainers

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#12089]
Context: sometimes you need a level of reproducibility that goes beyond that which can be provided by renv/conda environments. I recently discovered Devcontainers, and found it ideal for reproducing complex data science projects with lots of dependencies (including system dependencies not easily stored in an env), as shown here: https://twitter.com/robinlovelace/status/1576111383531651072

See here for discussion in relation to this R project/repo: https://github.com/Robinlovelace/geocompr/issues/873

I have checked and there is discussion of development containers in various issues, but these seem to be focussed on the development of RStudio itself rather than dev work on data science projects that have a particular development container: https://github.com/rstudio/rstudio/issues?q=devcontainer

There are different approaches to supporting this but one that seems most logical would be support for the established .devcontainer.json format: https://containers.dev/implementors/json_reference/

In terms of UX, a button could appear when users open a project that has a .devcontainer.json or equivalent file: 

![image](https://user-images.githubusercontent.com/1825120/193629701-c2e71e67-9ebd-4074-997a-ec623583b56c.png)

**Comment by jonvanausdeln** [comment]
@Robinlovelace thank you for raising this issue.  We will take it under consideration.

**Comment by eitsupi** [comment]
Maybe duplicate of #10218

**Comment by Robinlovelace** [comment]
Yeah, that earlier issue covers it, well spotted and thanks for flagging prior thinking on this. Deduped!
