### ISSUE TITLE
Autocompletion of assignment methods should result in backticks

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#12091]
Assignment methods, like those for `[<-` and `$<-` and `[[<-` don't result in backticked names, so you can't evaluate them immediately after autocompletion

https://user-images.githubusercontent.com/19150088/193641699-e1dec07c-a867-4f58-9431-ac1430e5e390.mov

@romainfrancois seems like something related to your autocompletion work

**Comment by romainfrancois** [comment]
See https://github.com/rstudio/rstudio/pull/12102#issue-1397541695 for QA notes, including links to previous PRs this might have affected (probably not).

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+248
Windows 11 Desktop, Ubuntu 22.04 server

Tested with several assignment methods and added backticks as expected.  Note, this may have caused a regression in #11503 (I reopened it)
