### ISSUE TITLE
Highlighting is wrong in dev docs

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#12104]
I'm on a pretty new daily build, and for a while now I've been seeing this issue.

It seems like the dev docs loaded by `devtools::load_all()` aren't being highlighted right when you do `?fn`.

In the video, we first look at the "installed" docs, then I load the dev version of the package and try again.

https://user-images.githubusercontent.com/19150088/194101586-8b973498-e1bd-4472-9426-9d18d6e4b7cc.mov

RStudio 2022.11.0-daily+221 "Elsbeth Geranium" Daily (c11dacb8207aceb03a4e7f11cf0f39360a0733d5, 2022-09-27) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+221 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36

**Comment by romainfrancois** [comment]
I'll `pick()*` this up. It may be related to https://github.com/rstudio/rstudio/pull/11507

*: very happy about `dplyr::pick()` btw.

**Comment by romainfrancois** [comment]
The ide serves an html that was made by `pkgload` with: 

```r
topic_write_html <- function(x, path) {
  macros <- load_rd_macros(dirname(dirname(x$path)))

  tools::Rd2HTML(
    x$path,
    out = path,
    package = x$pkg,
    stages = x$stage,
    no_links = TRUE,
    macros = macros
  )

  css_path <- file.path(tempdir(), "R.css")
  if (!file.exists(css_path)) {
    file.copy(file.path(R.home("doc"), "html", "R.css"), css_path)
  }
}
```

It has `no_links = TRUE` so we don't get links, and `dynamic = FALSE` (default in `Rd2HTML`) so no syntax highlighting.

**Comment by romainfrancois** [comment]
@lionel- it seems we've worked on this issue from two different angles in june. Can we go back to use `.rs.api.previewRd()` and we make sure it loads the macros on the ide side ?

`previewRd()` ends up calling this function which would be the perfect spot for injecting macros. 

https://github.com/rstudio/rstudio/blob/dad92308914238cb840634dcae4f122f770997c3/src/cpp/session/modules/SessionHelp.R#L803-L821

And it also does extra stuff to make sure the links work (and go to the dev version too) and it says `(preview) R Documentation`: 

<img width="401" alt="image" src="https://user-images.githubusercontent.com/2625526/194302936-dc8609fd-8686-4567-a4e7-603a16bbb743.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/2625526/194302996-f882d931-251c-4258-8b1d-366b557f13b1.png">

They however don't get the help popups and the Run examples seems broken, but I can fix this here.

**Comment by hadley** [comment]
Who wants to do the PR to pkgload?

**Comment by romainfrancois** [comment]
To test this completely, we need this `pkgload` pull request: https://github.com/r-lib/pkgload/pull/228 which we can get at this point with: 

```r
pak::pak("r-lib/pkgload#228")
```

But we can test that things work in the ide side by calling `.rs.api.previewRd()` e.g. 

```r
.rs.api.previewRd("man/summarise.Rd")
```

**Comment by jonvanausdeln** [comment]
Tested on 2022.12.0-daily+265

Using method described [above](https://github.com/rstudio/rstudio/issues/12104#issuecomment-1277679479) I was able to see correctly formatted documentation.
