### ISSUE TITLE
embedded videos in viewer open as new external windows

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#12106]
For example, try rendering the following Quarto document:

```markdown
---
title: "Video"
format: html
---

{{< video https://www.youtube.com/embed/wo9vZccmqwc >}}
```

The video displays correctly in the viewer, however a new external browser with the video is also opened.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+258
Windows 11, MacOS 12.4, Ubuntu 22.04

Embedded videos show correctly. Extra browser windows is not opened.
