### ISSUE TITLE
pam_exec Non-Zero Return Fails Entire Stack

### ISSUE THREAD

**Issue by vjef** [rstudio/rstudio#12116]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.02.2-485, 2022-07.2-576
    OS Version      : RHEL 7.9
    R Version       : 4.2.0

### Steps to reproduce the problem
Include a line in `/etc/pam.d/rstudio` that uses a non-zero exit code to determine execution of subsequent lines. `pam_exec.so` is a suitable module for this. `rserver-pam` will interpret the non-zero exit code from the script run under `pam_exec` as a failure for the entire PAM stack and login will fail.

Example:
```
auth        requisite     pam_succeed_if.so uid > 1000 quiet_success
auth        required      pam_ldap.so
auth        sufficient    pam_exec.so /usr/local/sbin/return_non-zero.sh
auth        required      pam_permit.so     # Always provides access
```
`/usr/local/sbin/return_non-zero.sh` is a very basic shell script that just returns a non-zero exit code:
```
#!/bin/bash
exit 1
```

### Describe the problem in detail
`rserver-pam` does not appear to allow PAM routing via non-zero exit codes in scripts executed with `pam_exec`. Consider the following example from `/etc/pam.d/rstudio` on a RHEL 7.9 box:

```
auth        requisite     pam_succeed_if.so uid > 1000 quiet_success
auth        required      pam_ldap.so
auth        sufficient    pam_exec.so /bin/bash /usr/local/sbin/duo_sentinel.sh -c
auth        requisite     pam_duo.so
```
The `/usr/local/sbin/duo_sentinel.sh` script does some filesystem checks and returns either a zero (success) or non-zero (fail) exit code. If this line succeeds, the `sufficient` action is satisfied, PAM skips the next line, and the `auth` stack succeeds. However, if anything besides zero is returned, the entire operation fails; we don't reach the `pam_duo.so` line.

Error output from `/var/log/secure`:
`rserver-pam[7949]: pam_exec(rstudio:auth): unexpected response from failed conversation function`

I have verified privileges and permissions required by the script executed by `pam_exec`. Regardless, failure of the script should not indicate failure of the entire `auth` portion of the PAM stack here.

### Describe the behavior you expected
From the example above, the non-zero exit code from the `pam_exec.so` line should fail _only that line_ and PAM should continue onto the `pam_duo.so` line. This is the behavior on other machines where similar PAM configs - identical for the two lines in question - are in place, albeit for non-RStudio Server services (`sshd`, for example).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MariaSemple** [comment]
Could we check whether this is a regression?

**Comment by vjef** [comment]
Any further info on this? Not sure if the question about checking for a regression was a to-do for me or someone else. Thanks!

**Comment by vjef** [comment]
I've verified that this is still an issue in release 2023.03.0-386. Guidance/info on further work would be appreciated.

**Comment by MariaSemple** [comment]
Sorry about that @vjef, I didn't see your response! I was asking if someone on the Posit team could try to check if it's a regression :)

**Comment by jeffvroom** [comment]
See the straightforward fix attached. I recommend including this for CH!

**Comment by vjef** [comment]
Commented on the attachment. Thanks, @jeffvroom!

**Comment by rich-rstudio** [comment]
verified on ubuntu20 and rhel9 2024.07.0+330.pro1 Workbench
