### ISSUE TITLE
Failure to display knit results with circumflex in caption: `get_parentpid()` attempt to apply non-function 

### ISSUE THREAD

**Issue by ms609** [rstudio/rstudio#12112]
### System details

RStudio Desktop 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Win 10
    R Version       : 4.3.0 devel

### Steps to reproduce the problem

1. Create a Markdown file with the content
````Rmd
---
title: "Minimal Reproducible Example"
output: 
  rjtools::rjournal_web_article
---
  
```{r figure, fig.cap = "circum^flex", echo = FALSE}
knitr::include_graphics("https://commons.wikimedia.org/wiki/File:Font_Awesome_5_solid_bug.svg")
```
````

2. Click the "Knit" button
3. The "Render" tab displays

```
Output created: mre.html
Error in get_parentpid() : attempt to apply non-function
Calls: <Anonymous> ... rstudio_stdout -> rstudio_detect -> detect_new -> get_parentpid
In addition: Warning message:
In output_format$post_knit(front_matter, knit_input, runtime, encoding = "UTF-8") :
  A date must be provided for your article. Defaulting to today's date.
Execution halted
```

### Describe the problem in detail

The problem appears to relate to the presence of a circumflex `^` in the figure caption.

### Describe the behavior you expected

A pop-up window should appear displaying the rendered HTML file

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
Alternatively, it might be a `cli` issue (where `rstudio_detect ` lives) cc @gaborcsardi, @ms609 which version of `cli` do you have ?

**Comment by gaborcsardi** [comment]
Do you get the same error when running `rmarkdown::render()` from the terminal? If yes, then this is not an RStudio issue.

But in any case, I cannot easily reproduce this, either. I get 
```
LaTeX failed to compile RJwrapper.tex
```

Is `rjtools::rjournal_web_article` necessary to reproduce this? 

I suspect that the error you are seeing happens while R is trying to format the real error. Nevertheless:
- try updating cli and rlang.
- `^` is a special character in LaTeX, so you might need to do something special if you want to include it in the caption.

If updating still produces the same error, then you'll have to tell us the output of `sessioninfo::sessioninfo()`.

**Comment by ms609** [comment]
After running `update.packages()`, I see a more detailed error message (both in RStudio daily build, and in the release version)

```
Error: 
! error in callr subprocess
Caused by error: 
! LaTeX failed to compile RJwrapper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJwrapper.log for more info.
---
Backtrace:
1. rmarkdown::render("C:/Users/pjjg18/GitHub/TreeSearch-MS/Article/smith.Rmd"…
2. output_format$on_exit()
3. local overlay()
4. callr::r(function(input) { …
5. callr:::get_result(output = out, options)
6. callr:::throw(callr_remote_error(remerr))
7. callr:::callr_remote_error(remerr)
8. callr:::throw(err, parent = remerr[[3]])
---
Subprocess backtrace:
 1. rmarkdown::render(input, output_format = "rjtools::rjournal_pdf_article")
 2. output_format$post_processor(front_matter, input, output_file, …
 3. tinytex::latexmk("RJwrapper.tex", fmt$pandoc$latex_engine, pdf_file = xfun…
 4. tinytex:::latexmk_emu(file, engine, bib_engine, engine_args, min_times, …
 5. local run_engine()
 6. tinytex:::system2_quiet(engine, c("-halt-on-error", "-interaction=batchmode", …
 7. local on_error()
 8. tinytex:::show_latex_error(file, logfile)
 9. base::stop(e, " See ", logfile, " for more info.", call. = FALSE)
10. | base::.handleSimpleError(function (e) …
11. global h(simpleError(msg, call))
```

When I run `rmarkdown::render("Article/mre.Rmd", output_format = "rjtools::rjournal_pdf_article")`, I see 

```
! LaTeX Error: Unknown graphics extension: .png?20220907023645.

Error: LaTeX failed to compile RJwrapper.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJwrapper.log for more info.
```


```
> sessionInfo()
R Under development (unstable) (2022-09-25 r82916 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=C                             
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.4.4        cli_3.4.1         knitr_1.40        rlang_1.0.6      
 [5] xfun_0.33         cranlogs_2.1.1    stringi_1.7.8     purrr_0.3.5      
 [9] hunspell_3.0.2    jsonlite_1.8.2    rticles_0.24      yesno_0.1.2      
[13] htmltools_0.5.3   tinytex_0.42      rmarkdown_2.16    evaluate_0.16    
[17] fastmap_1.1.0     yaml_2.3.5        stringr_1.4.1     compiler_4.3.0   
[21] sessioninfo_1.2.2 fs_1.5.2          Rcpp_1.0.9        rjtools_1.0.1    
[25] rstudioapi_0.14   digest_0.6.29     R6_2.5.1          magrittr_2.0.3   
[29] tools_4.3.0 
```

**Comment by ms609** [comment]
Thanks – I'll follow up there.
