### ISSUE TITLE
Error in RStudioGD() :    Shadow graphics device error: r error 4 (R code execution error) In addition: There were 50 or more warnings (use warnings() to see the first 50)

### ISSUE THREAD

**Issue by IrinaMax** [rstudio/rstudio#12110]
### System details

    RStudio Edition : 
   > version
               _                           
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree 

I look at the similar problem https://github.com/rstudio/rstudio/issues/2214 but nothing work for me.
I try to delete  the folder inside /tmp/ RtmpkmP8GA , restart RStudio-Server and recreate the folder but error just the same.

Last week RStudio-Server stop plotting any plots with error
```
Error in RStudioGD() : 
  Shadow graphics device error: r error 4 (R code execution error)
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by jonvanausdeln** [comment]
@IrinaMax Thank you for the report of your issue.  

What is your RStudio version?  

Does even running
```
plot(mtcars)
```
Not work?
