### ISSUE TITLE
Rainbow fenced divs

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#12115]
I love rainbow parentheses, for my use and for teaching! And while I often use the visual editor for Quarto documents which use fenced divs, sometimes I need to go to the source editor, especially for debugging. It would be great if the `:::` could use color to match opening and closing pairs, like parentheses.

A small example of where this would be super helpful is something like the following where there are nested fenced divs in a slide.

```
---
format: revealjs
---

::: columns
::: {.column width="50%"}
::: {style="color: gray;"}
gray text
:::
:::

::: {.column width="50%"}
::: incremental
-   incremental
-   list
-   items
:::
:::
:::
```

One option would be to add color to just `:::`, e.g.:

![rainbow-fenced-divs 001](https://user-images.githubusercontent.com/5965649/194591889-6123797b-bd12-4413-a864-80b5388ffa4f.png)

Another option would be to carry the color to the definition of that fenced div, e.g.:

![rainbow-fenced-divs 002](https://user-images.githubusercontent.com/5965649/194591978-00ac8917-295c-4a30-9e88-4374094521d1.png)

The latter is more attractive to me, but I might be overlooking important/tricky stuff about syntax highlighting that makes such a thing not-a-good-idea/impossible. Even just color-matching the `:::` would go a long way though!

**Comment by romainfrancois** [comment]
Is there somewhere I can learn about fenced div ? From what I understand: 

 - a line that starts with a series of 3 `:` followed by some stuff opens the fenced div
 - a line that only has the `:`s closes

But I'm probably missing something.

**Comment by kevinushey** [comment]
IIUC this is a pandoc extension described here: https://pandoc.org/MANUAL.html#extension-fenced_divs

**Comment by jgutman** [comment]
Verified in 2023.3.0.84 on MacOS 13
