### ISSUE TITLE
Auto-indent on paste mistreats raw strings

### ISSUE THREAD

**Issue by martinmodrak** [rstudio/rstudio#12127]
### System details

    RStudio Edition :  Desktop or Server
    RStudio Version :  RStudio 2022.12.0-daily+257  (as well as 2022.02 and 2022.07)
    OS Version      :  Windows 10
    R Version       :  4.2.1

### Steps to reproduce the problem

Open a new R script. Copy the following code segment:

```r
r"(
       Indented text
)"
```

Paste it with auto-indent (`Shift + Ctrl + V` if auto-indent is not enabled by default in global options) into the R document

The middle line gets auto-indented, i.e. the code now has:

```r
r"(
Indented text
)"
```

### Describe the problem in detail

It appears that the auto-indenter treats the inner part of a raw string literal as regular code, i.e. if the string literal contains brackets, auto-indentation will occur. 

If I copy paste a normal string literal, no auto-indentation is performed.

### Describe the behavior you expected

I expect no auto-indentation to take place within raw string literals.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Potentially related:

https://github.com/rstudio/rstudio/blob/84fa8decd41a375964063ae0fc708eb1e3ff8d33/src/gwt/acesupport/acemode/r_code_model.js#L1572-L1575

we might need to check for a `rawstring` state as well?

**Comment by kevinushey** [comment]
Actually more likely this code:

https://github.com/rstudio/rstudio/blob/84fa8decd41a375964063ae0fc708eb1e3ff8d33/src/gwt/acesupport/loader.js#L178-L180

**Comment by jgutman** [comment]
Verified -- raw strings get reindented on 2022.12.0, and DO NOT get reindented (as desired) on 2023.03.0+84
