### ISSUE TITLE
skip lint diagnostic for `describe({ it(...) })` 

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12124]
We get these linter errors: 

<img width="718" alt="image" src="https://user-images.githubusercontent.com/2625526/194852581-9431f150-7d90-4394-8d78-609c2ad758d2.png">

But `it()` is part of the `describe()` DSL: 

https://github.com/r-lib/testthat/blob/f8ccf033a74d89e2d1d3cb2ec3c6c4f63ca69055/R/describe.R#L70-L83

**Comment by kevinushey** [comment]
The diagnostics engine keeps a stack of function calls at the current parse position, e.g. we do something similar here:

https://github.com/rstudio/rstudio/blob/84fa8decd41a375964063ae0fc708eb1e3ff8d33/src/cpp/session/modules/SessionRParser.cpp#L2321-L2324

You could probably add a similar type of check here?

https://github.com/rstudio/rstudio/blob/84fa8decd41a375964063ae0fc708eb1e3ff8d33/src/cpp/session/modules/SessionDiagnostics.cpp#L82-L84

**Comment by romainfrancois** [comment]
But before we go there, is the `describe( it()...)` pattern still in fashion ? I've only ever seen it in `cpp11`. cc @hadley @jennybc

**Comment by hadley** [comment]
I have a note to fix this in testthat: https://github.com/r-lib/testthat/issues/1587

**Comment by kevinushey** [comment]
Sounds like this was fixed on the testthat side.
