### ISSUE TITLE
Unevaluated code in Quarto file affects output when run interactively in RStudio

### ISSUE THREAD

**Issue by maxdrohde** [rstudio/rstudio#12123]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  2022.07.2 Build 576
    OS Version      :  Monterey 12.6
    R Version       :  4.1.2

#### Version info copied from RStudio
RStudio 2022.07.2+576 "Spotted Wakerobin"
Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

## Steps to reproduce the problem

I am encountering a perplexing bug where unevaluated code in my Quarto document is affecting the output when run interactively. The best I can think of is providing a screen recording, since the problem occurs when running cells interactively.

The situation is that I have saved the output of `bench::mark()` to a `.rds` file. In this document, I load it in and display it. However, the formatting changes depending whether or not I have another cell that calls the `bench` package in the document, **even if I don't run it**.

Here is the code of my Quarto document:

````
---
title: "Bug test"
format: html
---

```{r}
benchmark_results <- readr::read_rds("benchmark_results.rds")
```

```{r}
summary(benchmark_results)
```

```{r}
bench::hires_time()
```

````

#### (1) Running cells interactively produces incorrect formatting

https://user-images.githubusercontent.com/25734232/194773714-1a30f782-35cb-4b1d-b840-0be5329fc413.mp4

#### (2) Adding an **unevaluated** call to `bench` produces to the correct formatting

https://user-images.githubusercontent.com/25734232/194773691-75fd09e0-d811-44b8-8925-c25fa2d3a4b7.mp4

#### (3) However, using the `Restart R and Run All Chunks` command causes the problem to return

https://user-images.githubusercontent.com/25734232/194773680-fa86ab71-acb1-4ddd-b425-f1393556a4f5.mp4

## Describe the behavior you expected

I expect the output to look like that in (2), but I don't understand why having an unevaluated cell should affect the output.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
My guess is that RStudio is loading the `bench` package behind the scenes for you in the second case, and since the package needs to be loaded in order to format the output here appropriately, you only see that formatting in that case.

My recommendation would be to explicitly load the `bench` package when loading the saved benchmark results.
