### ISSUE TITLE
The Rstudio report a error about vscode

### ISSUE THREAD

**Issue by shangguandong1996** [rstudio/rstudio#12121]
### System details

    RStudio Edition : Server
    RStudio Version :  RStudio Server 2022.02.2 Build 485
    OS Version      :  CentOS Stream 8
    R Version       :  R version 4.2.0 (2022-04-22)

### Describe the problem in detail

Each time I restart the Rstudio, it will report below message. But it do not infulence my Rstuido session.

```

R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/home/sgd/.vscode-server/extensions/ikuyadeu.r-2.3.8/R/session/init.R': No such file or directory
```

Here is my vscode extensions dir
![图片](https://user-images.githubusercontent.com/22555126/194746521-bc291b09-bdaa-4de8-8ba4-4ff547a045ed.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Presumedly you were using VSCode earlier, installed the R code extension, and that wrote some code to your `~/.Rprofile` to try and initialize R. I'd recommend inspecting the file with:

```
file.edit("~/.Rprofile")
```

and remove the errant code trying to source the extension.

If this doesn't help, then I'd recommend asking the VSCode extension authors for assistance.
