### ISSUE TITLE
`fig-path` autocompletion & ordering

### ISSUE THREAD

**Issue by cgoo4** [rstudio/rstudio#12122]
`fig-path` works, but does not appear in RStudio's YAML autocompletion. And although mostly listed alphabetically (which makes it easier to search), some options appear out of sequence.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/32419319/194753205-d181fa86-9589-4eef-a3b0-e6c7c51bb0e3.png">

<img width="255" alt="image" src="https://user-images.githubusercontent.com/32419319/194753361-56f7d5de-5f61-40a8-8d81-a28c29523688.png">

-->

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cscheid** [comment]
I don't know if you can tag me on an rstudio issue, but it would make sense to. We do control the sorting of YAML completions, so that order you're getting isn't arbitrary. 

In the case of `fig-path`, we don't have it in our YAML schemas, so it'll never get suggested. (I believe quarto converts `fig-path` to `fig.path`, but we don't otherwise support that option).

**Comment by jjallaire** [comment]
We actually don't even respect `fig.path` in Quarto (it is always the _files directory) which is why we don't have it in our YAML schema.

**Comment by cscheid** [comment]
@jjallaire oh, I'm sorry. I found https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/rmd/hooks.R#L647-L728 and misinterpreted it to mean that we convert `fig-path` to `fig.path`.
