### ISSUE TITLE
R session aborted when using "clear objects from the Workspace"

### ISSUE THREAD

**Issue by danieltomasz** [rstudio/rstudio#12131]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0-daily+259
    OS Version      : MacOS 13.0 Beta (22A5365d) ARM
    R Version       :  4.2.1

### Steps to reproduce the problem
1. Create and save quatro document
2. run code chunk
```
```{r}
library(dplyr)
library(purrr)
library(tibble)


SEL_VAR <- c(
  "TMT_1", "TMT_5", "TAP_WM_1", "TAP_A_5", "TAP_A_10", # Processing  Speed
  "CVLT_2", "CVLT_3", "CVLT_10", "CVLT_11", "CVLT_12", # Memory
  "TAP_I_6", "TAP_I_13", "TAP_I_20", # Interference/Conflict Resolution
  "WST_1", # Vocabulary
  "TAP_WM_6", "TAP_WM_7"
) # Working Memory

count_files <- list.files(
  path = here::here("data", "Behavioural_Data_MPILMBB_LEMON", "Cognitive_Test_Battery_LEMON"),
  recursive = TRUE,
  pattern = "\\.csv$",
  full.names = TRUE
)
count_lists <- lapply(count_files, read.csv, sep=",", header=TRUE, row.names=1)

df <- purrr::map(count_lists, ~ .x %>%
                 tibble::rownames_to_column('subject')) %>%
     purrr::reduce(full_join, by = 'subject') %>%
     dplyr::mutate(across(everything()))

df_selected <- df  %>%
  dplyr::select(one_of(c("subject", SEL_VAR))) 
```
Use the broom to "clear objects from the Workspace"
3. Try to rerun the chunk
4. R session is crashing

I am  includind the CSV files (are part of LEMON dataset http://fcon_1000.projects.nitrc.org/indi/retro/MPI_LEMON.html)
[Behavioural_Data_MPILMBB_LEMON.zip](https://github.com/rstudio/rstudio/files/9763589/Behavioural_Data_MPILMBB_LEMON.zip)

5. I  tried to reproduce it as a MVE with importing and removing `mtcars` dataset, but it R session doesn't crash, so maybe it is a combination of objects/packages in the workspace
6.  Doing the same in "Spotted Wakerobin" Release (e7373ef8, 2022-09-06)  doesnt result in a crash

### Describe the problem in detail
After a few seconds the R session is aborted and R is restarted.

### Describe the behavior you expected

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I'm not able to run your example.

```
> count_lists <- lapply(count_files, read.csv, sep=",", header=TRUE, row.names=1)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed
```
