### ISSUE TITLE
argument completion with `|||`

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12140]
From @DavisVaughan: 

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/2625526/195613656-5f1d04c4-e443-4df0-aa55-e5afc7e7ded9.png">

https://github.com/rstudio/rstudio/blob/8c4a75320314254a265cac435a5d11c0b06dbea0/src/cpp/session/modules/SessionRCompletions.R#L3494-L3498

**Comment by romainfrancois** [comment]
I believe the fix in #12141 is harmless enough to be included in Elsbeth, but I can retarget the pr if needed.

**Comment by romainfrancois** [comment]
QA note: to test this, we need to be inside a file in a project that uses `rlang`, for example `dplyr`.

**Comment by romainfrancois** [comment]
cc @DavisVaughan, can you confirm build 267 fixes this: 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/2625526/195786306-51935d6e-07c6-4317-8492-ced324a9abc4.png">

**Comment by DavisVaughan** [comment]
RStudio 2022.12.0-daily+267

Looks like it is working for me! Thanks!

https://user-images.githubusercontent.com/19150088/195859695-3c44b9c7-1827-4ce6-b32e-846b422e11c4.mov
