### ISSUE TITLE
Missing completion help for some packages 

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12147]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/2625526/195809029-9d5b259b-ed30-416e-ade8-87ad20cc9560.png">

whereas packages that have a `<pkg>-package` topic get their popup: 

<img width="746" alt="image" src="https://user-images.githubusercontent.com/2625526/195809177-7eb1f371-3f28-4612-a811-e0c441619cbe.png">

https://github.com/rstudio/rstudio/blob/b281eb8ce8a09d3f0ec982ce7520328b75894285/src/cpp/session/modules/SessionHelp.R#L465-L471

We might consider getting inormation from the DESCRIPTION  file instead: 

```
> packageDescription("yaml")
Package: yaml
Type: Package
Title: Methods to Convert R Data to YAML and Back
Date: 2022-01-24
Version: 2.3.5
Suggests: RUnit
Author: Shawn P Garbett [aut], Jeremy Stephens [aut, cre], Kirill Simonov [aut], Yihui Xie [ctb], Zhuoer Dong [ctb], Hadley Wickham
              [ctb], Jeffrey Horner [ctb], reikoch [ctb], Will Beasley [ctb], Brendan O'Connor [ctb], Gregory R. Warnes [ctb],
              Michael Quinn [ctb], Zhian N. Kamvar [ctb]
Maintainer: Shawn Garbett <shawn.garbett@vumc.org>
License: BSD_3_clause + file LICENSE
Description: Implements the 'libyaml' 'YAML' 1.1 parser and emitter (<https://pyyaml.org/wiki/LibYAML>) for R.
URL: https://github.com/vubiostat/r-yaml/
BugReports: https://github.com/vubiostat/r-yaml/issues
NeedsCompilation: yes
Packaged: 2022-02-19 02:41:00 UTC; garbetsp
Repository: CRAN
Date/Publication: 2022-02-21 09:20:02 UTC
Built: R 4.2.0; aarch64-apple-darwin20; 2022-03-22 00:52:07 UTC; unix
Archs: yaml.so.dSYM
RemoteType: standard
RemotePkgRef: yaml
RemoteRef: yaml
RemoteRepos: https://cloud.r-project.org
RemotePkgPlatform: aarch64-apple-darwin20
RemoteSha: 2.3.5

-- File: /Users/romainfrancois/.R/library/4.2/yaml/Meta/package.rds 
```

**Comment by jgutman** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7817881/205692040-5e6b8390-c9dc-4b94-998a-80b75055056e.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/7817881/205692123-662e29ad-a3ee-4b61-a3be-6581d420cd28.png">

Verified in 2023.03.0-daily+3
