### ISSUE TITLE
publishing fails with dirlist error

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#12142]
### System details

    RStudio Edition : desktop
    RStudio Version : 2022.12.0-daily+263
    OS Version      : macOS Monterey 12.6
    R Version       : R 3.6.3

### Steps to reproduce the problem

1. Create a new Quarto project using the IDE workflow; opened in a new session.
2. The `publishing.qmd` file is opened automatically; click the "publish" button in the editor.
3. Choose "Posit Connect".
4. Choose to publish the document with source code.
5. BOOM.

### Describe the problem in detail

When attempting to publish, an error dialog is shown with the text:

> Could not find files to deploy: 
>
> Error occurred while executing method

Additionally, the R console includes the error message:

```
Error in if (dirlist$totalSize >= max_size) NULL else .rs.summarizeDir(dirlist$contents,  : 
  missing value where TRUE/FALSE needed
```

This error occurs both with the CRAN and GitHub versions of `rsconnect`.
This error occurs both with the CRAN and GitHub versions of `rstudioapi` (not sure if relevant).

### Describe the behavior you expected

Publishing is allowed and successful.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@jjallaire know anything about this?  Jackie doesn't think it is related to her recent publishing changes for Cloud.

**Comment by aronatkins** [comment]
This may be Quarto-only; I've done a little testing of other publishing workflows (Shiny, Rmd) and they appear to get past the "Collecting files" phase.

**Comment by jgutman** [comment]
This issue exists in RStudio version 2022.12.0.250, so prior to any of the changes to publishing made to support rstudio.cloud, so definitely seems to be related to Quarto changes

**Comment by aronatkins** [comment]
The problem does not occur with 2022.11.0-daily+236 (the final September daily), but looks to be present in 2022.12.0-daily+255.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/rstudio/commit/05d95dd1e61de555053bdf8b981a2c250088fbd6

**Comment by aronatkins** [comment]
I've been able to successfully publish using RStudio IDE 2022.12.0-daily+267, updating from yesterday's 263 build.

**Comment by jgutman** [comment]
Verified in 2022.12.0-daily+270 on Mac OS 12.6

**Comment by quinfer** [comment]
Hi there. I am getting this error again with 2023.12-daily+302 for mac.

**Comment by ronblum** [comment]
@quinfer I'm unable to reproduce the proble in RStudio Desktop 2023.12.0-daily+313 on MacOS 14.2 (Sonoma). Can you please provide the deployment logs?

**Comment by quinfer** [comment]
@ronblum the quarto version is 1.3.450.  I dont even get to the stage of deployment but get this message
<img width="259" alt="Screenshot 2023-11-22 at 13 08 51" src="https://github.com/rstudio/rstudio/assets/63010208/86da6375-9830-4874-a638-f14c24ce4bac">

When I create a new project and with quarto slide document, it will publish fine to my posit connect server.  I am not sure how to provide a reproducible example of the problem other than share my project files. 
[detection.zip](https://github.com/rstudio/rstudio/files/13440169/detection.zip)

**Comment by quinfer** [comment]
The problem seems to be that when I attempt to publish no rsconnect folder is created in my directory.

**Comment by quinfer** [comment]
Oh and I get this error in my console
`Error in if (dirlist$totalSize >= max_size) NULL else .rs.summarizeDir(dirlist$contents,  : 
  missing value where TRUE/FALSE needed
Error in if (dirlist$totalSize >= max_size) NULL else .rs.summarizeDir(dirlist$contents,  : 
  missing value where TRUE/FALSE needed`

**Comment by jgutman** [comment]
@quinfer Thanks for the info. I was able to reproduce with the following minimal version of what you shared.

RStudio version 2023.12.0.323
rsconnect version 1.1.1
Quarto version 1.3.450

`test_quarto_publish.qmd` 
~~~~~
---
title: "test_quarto_publish"
format: 
  revealjs:
   css: mycss.css
---

```
{r}
quarto::quarto_version()
quarto::quarto_path()
packageVersion("rsconnect")
RStudio.Version()$version
```
~~~~

`mycss.css`

```
.title-slide {
  background-image: url(img/title-slide-img.png);
  background-size: cover;
}
```

`_quarto.yml`
```
project:
  title: "test_quarto_publish"

editor: visual
```

The problem seems to occur when including `url(img/title-slide-img.png)` in the css file, which provides a path to a file that doesn't appear to exist in your directory. If I remove that line from the css, or update the path to a valid path in my project, I no longer get the error. Could you confirm whether or not that resolves the issue?

**Comment by quinfer** [comment]
@jgutman, that works like a dream.  Big thanks
