### ISSUE TITLE
`Error in splat[[2]] : subscript out of bounds`

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12145]
Regression introduced in https://github.com/rstudio/rstudio/issues/12140

<img width="354" alt="image" src="https://user-images.githubusercontent.com/2625526/195788957-db589d08-47fc-458a-8f01-809621a6775f.png">

**Comment by jgutman** [comment]
Ah thanks! I had noticed this and meant to file an issue but looks like you've already resolved

**Comment by kevinushey** [comment]
@PedroMilanezAlmeida can you please file a separate issue with a reproducible example? The error almost surely depends on the content of the R document you're working in, so it'd be helpful to know what R code can trigger this.

**Comment by PedroMilanezAlmeida** [comment]
@kevinushey 

Thank you for your quick comment!

The issues linked below described exactly what is going for me (the diff to 12950 is that for me, the error does not happen only in purrr functions). Unfortunately, the error message is not reproducible, it does not happen all the time. Also, within the same R document (only tried on .R files, I don't work a lot with .rmd or other R file types), sometimes the error message is shown, most of the time it is fine.

https://github.com/rstudio/rstudio/issues/12976

https://github.com/rstudio/rstudio/issues/12950
