### ISSUE TITLE
Avoid showing dummy tooltip with `(...)`

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12159]
Follow up to https://github.com/rstudio/rstudio/pull/11412

Instead of showing the dummy `(...)` maybe the tooltip could just not be displayed at all: 

<img width="172" alt="image" src="https://user-images.githubusercontent.com/2625526/196188766-f9ee2f1e-33b2-4940-b868-2a984d078ab4.png">

**Comment by jgutman** [comment]
Verified on 2023.3.0.84, tooltip appears on hover for `stats::rnorm()` but not on hover for `unknown_fun()`
