### ISSUE TITLE
Character Viewer shortcut not working on macOS

### ISSUE THREAD

**Issue by cbrnr** [rstudio/rstudio#12164]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release
    OS Version      : macOS 11.7
    R Version       : 4.2.1

### Steps to reproduce the problem
Open RStudio, create a new script, press <kbd>Ctrl</kbd><kbd>⌘</kbd><kbd>Space</kbd>, which should open the macOS Character Viewer. However, this does not work in RStudio.

### Describe the problem in detail
The keyboard shortcut to open the Character Viewer does not work (nothing happens). I assume that Qt (or whatever underlying GUI framework is used by RStudio) disables this shortcut, because it does not appear as a menu entry in "Edit – Emoji & Symbols" either.

### Describe the behavior you expected
I expected that global shortcut to also work in RStudio. It's a very convenient way to insert emojis and other special characters.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
@cbrnr, Thank you for your report!  
This appears to be not an issue with the upcoming release (later this year).  You can check with our daily builds found at https://dailies.rstudio.com/.

**Comment by cbrnr** [comment]
Ohhhh, that's great! Thank you @jonvanausdeln, really looking forward to the new release!
