### ISSUE TITLE
Outline sections missing with nested code chunks

### ISSUE THREAD

**Issue by srvanderplas** [rstudio/rstudio#12161]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.07.2 Build 576
    OS Version      :  Ubuntu 22.04
    R Version       :  4.2.1 (2022-06-23) -- "Funny-Looking-Kid"

### Steps to reproduce the problem

Using nested code chunk syntax, as in [authoring/markdown-basics](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/markdown-basics.qmd), results in missing header sections for any sections occurring after the nested code chunks.

### Describe the problem in detail
Create a new Quarto document and paste in the following code. The outline will show sections up to Source code, but will not include the additional sections "Equations" and "Another heading"

`````
---
title: demo
---

## Overview

## Text Formatting

## Headings {#headings}

## Links & Images

## Lists

## Tables

## Source Code


```` markdown
```
code
```
````

## Equations

## Another heading

`````

Notice also that the highlighting for "Equations" and "Another Heading" is not correct.

Desktop screenshot:

![image](https://user-images.githubusercontent.com/2127125/196192861-f31e2faa-3590-4539-a507-f1e3615d403c.png)

Server screenshot:

![image](https://user-images.githubusercontent.com/2127125/196193269-cdf8825e-44bd-4643-90d2-b6938f82654d.png)

### Describe the behavior you expected

I would expect that there would be additional outline sections labeled "Equations" and "Another Heading" after the Source Code section.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
Before/While doing this, maybe we can refactor how `state` works, as hinted here: https://github.com/rstudio/rstudio/pull/12172#discussion_r998630964

**Comment by jthomasmock** [comment]
Cross-posting as this may be related: https://github.com/rstudio/rstudio/issues/10079

**Comment by piiskop** [comment]
i have also reported this [bug](https://github.com/rstudio/rstudio/issues/12788#issuecomment-1456166511).

**Comment by gtritchie** [comment]
Confirmed with Mac Desktop build 2024.10.0-hourly+190. I now see the full outline.
