### ISSUE TITLE
Various errors and issues with "Run examples" in the documentation panel

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#12170]
## Problem 1: Seeing  `Error in loadNamespace(name): there is no package called 'webshot'`

If I load up the documentation for `shinyjs::useShinyjs()`, scroll down to the Examples section, and click on "Run example", I'm brought to a new page. This is what I see:

![image](https://user-images.githubusercontent.com/952340/196295499-cd2d23a2-f020-49ef-9757-553cce69edb9.png)

The example here is trying to run a shiny app. The package shinyjs does not use {webshot} in any way, this is something that I assume RStudio is using in order to display the example. 

The same error also happens when I look at the documentation for `?colourpicker::colourWidget`, even though that's an {htmlwidgets} widget and not a shiny app.

## Problem 2: If I do have {webshot} installed, a non-functional shiny app appears

After installing the {webshot} package to get rid of the above error, I tried again looking at the examples section of `?shinyjs::useShinyjs()`. Now the help panel shows a shiny app but it's unresponsive. The panel also says "Listening on http://127.0.0.1:3452" as if a shiny app is running, but when I go to that URL, there is no active shiny app. Again this is also true with `colourpicker::colourWidget()` even though it's not a shiny app.

It also takes several seconds from clicking "Run examples" until the panel shows up, during which I think my laptop is frozen. Not a good experience.

## Problem 3: Seeing all the "loading package X" messages in the console

Every time I click on "Run examples" in any of the above scenarios, my R console gets filled with startup messages from attaching various packages. This is also poor user experience - when I interact within the Help panel I expect everything to remain within that panel and if any code is run it'll be in an isolated environment. I don't want clicking a button there to result in my RStudio environment and console getting "dirty"

## Problem 4: RStudio becoming unresponsive

When I try to click on "Run examples" in the documentation of `?DT::datatable()`, one of two things happens: sometimes my IDE becomes unresponsive and I must kill it from the operating system. The times when it does respond, my R console seems to be busy forever, I cannot run any commands and I don't have the `>` prompt. I also don't see the red stop sign that I see when I run shiny apps, so I'm not sure what exactly is happening.

---

All in all, it seems that the "Run examples" section should try not to run anything interactive and stick with non-interactive code only perhaps?

---

R version 4.2.1, RStudio version:

```
RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

**Comment by romainfrancois** [comment]
The `Run Examples` button is managed by R's internal help system, it eventually calls `knit::knit()` here: 

https://github.com/r-devel/r-svn/blob/4a49569f97cb80e286f8c76d5ad7ac9441ca3b86/src/library/tools/R/code2html.R#L91

You can reproduce what happens when clicking on the `Run Examples` button with: 

```r
writeLines(tools:::example2html("useShinyjs", "shinyjs")$payload)
```

The ide here is mostly a bystander, and struggles with how the help system is implemented. We have vague plans to redesign the help system here #2083 but a good first step might be to just bypass the `Run Examples` feature and have the code run in the console instead or something.

**Comment by daattali** [comment]
Very happy to know this feature was not poorly implemented by RStudio :D

You can close this issue then if it's not caused by the IDE

**Comment by romainfrancois** [comment]
I have a PR https://github.com/rstudio/rstudio/pull/12174 that removes the link, but potentially we can do something else instead. We can leave this open for now. Thanks for reporting it, I believe we do definitely need to do something about this.
