### ISSUE TITLE
knitr sometimes cannot find "packageVersion"

### ISSUE THREAD

**Issue by krcoombes** [rstudio/rstudio#12182]
Unfortunately, I can't yet produce a minimal example to illustrate the problem. It appears to occur after I have been working interactively with the console in RStudio for  a while, and then press the "knit" button. I get an error message that R cannot find the function "packageVersion" (from the "utils" package). If I close RStudio, restart it, and again try to knit immediately, the error goes away.

I tried commented out the call to the packageVersion after the error appears (without restarting), and then got an error message that R could not find the "rbinom" function (from the "stats" package). In both instances, the error occurs on the first call to a function not in the base package. It appears that something I am doing from the console is causing R not to load the standard packages when started from the knit button. 

The problem only seems to occur in sessions when I have been using either (or both?) the MOFA2 package and parts of the tidyverse (dplyr and tidyr) in the R console.

**Comment by krcoombes** [comment]
That's a great question. I never tried that when the problem happened previously. And I just spent some time trying to make the problem happen again, and wasn't successful at inducing failure.... So, I'm not sure. The next time I accidentally cause the problem, I will try this and let you know.

**Comment by ronblum** [comment]
@krcoombes Thanks! I'll leave this open for now. Also, if you do run into this issue again, can you provide [a diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostic-Report)? The instructions are about halfway down the page.

**Comment by krcoombes** [comment]
Okay. I just made the problem recur. I had to not only load MOFA2, but also get to the point where I had invoked "run_mofa" from the console. (I have now done this twice in a row, so it seems reproducible.) Trying to knit immediately after that caused the "cannot find" error. Using the menu options Session -> Restart R cleared the problem, and the knit was successful.

One unusual feature of MOFA is that the actual algorithm is coded in python, and is called from R using basilisk.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9862486/diagnostics-report.txt)

**Comment by kevinushey** [comment]
I see this in your environment variables:

> R_DEFAULT_PACKAGES               : NULL

This is probably the culprit; setting this to `NULL` means that R won't try to load any add-on packages when it's started, including packages like `utils` and `tools` which would normally be loaded and attached by default.

Do you know where or why that's being set?

**Comment by krcoombes** [comment]
Interesting. I have never set that variable manually. When I start a DOS Command Prompt, and use "set" at the command line, that variable is not there. When I start a new R session and use "Sys.getenv", that variable is not there. When I load the MOFA library, that variable is still not there. But, after I call the "run_mofa" function, which uses "run_basilisk" to connect to the "mofapy2" Python library package, that variable suddenly exists and has the "NULL" value.

That seems to me to be pretty unfriendly behavior by an R package....

**Comment by kevinushey** [comment]
You might get some hints as to where this is happening with some code like:

```
trace(Sys.setenv, quote({
   if ("R_DEFAULT_PACKAGES" %in% names(list(...)))
      print(rlang::trace_back())
}), print = FALSE)
```

Then, you'll (hopefully) see a traceback in the R console the next time something tries to set that environment variable.
