### ISSUE TITLE
"Run All Code Chunks Above" evaluates code chunks with `#| eval: false` in hash pipe syntax if option is not listed first

### ISSUE THREAD

**Issue by stephan-koenig** [rstudio/rstudio#12196]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.2+576
    OS Version      : macOS Monterey 12.6 (21G115)
    R Version       : 4.21

### Steps to reproduce the problem

- Create a new Quarto file.
- Set code chunk `not-evaluated` to not be evaluated with `#| eval: false` in hash pipe syntax as the **second or later** chunk option.
- Select the option to "Run All Code Chunks Above" for the code chunk `last-chunk`.

````
---
title: "Untitled"
format: html
---

```{r}
#| label: not-evaluated
#| eval: false

print("This chunk should not be evaluated.")
```

```{r}
#| label: last-chunk
```

````

### Describe the problem in detail

If a code chunk is set to be not evaluated with `#| eval: false` in hash pipe syntax and is **NOT** the first chunk option, it is still evaluated when running "Run All Code Chunks Above" is selected for a code chunk below it. Only if `#| eval: false` is the first listed option, then the chunk is (correctly) not evaluated.

**Note**: This behaviour might be specific to RStudio on macOS or Desktop versions. When I tested the code above in RStudio Cloud, it had the expected behaviour.

### Describe the behavior you expected

The code chunk should not be evaluated regardless of the position of `#| eval: false` in the chunk options.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
This appears to be fixed in the development version, soon to be released. Tested with Build RStudio 2022.12.0-daily+280 "Elsbeth Geranium" Daily

**Comment by stephan-koenig** [comment]
@romainfrancois, can we reopen this issue? When I select the "Run All Code Chunks Above" option, code chunks are still evaluated for me if `#| eval: false` is not listed first as the chunk options using either RStudio Desktop 2022.12.0+353 or 2023.03.0+386.

```
RStudio Edition : Desktop
RStudio Version : RStudio 2023.03.0+386
OS Version      : macOS Ventura 13.2.1 (22D68)
R Version       : 4.2.3
```
