### ISSUE TITLE
R Studio Server cannot be embedded in the iFrame framework

### ISSUE THREAD

**Issue by syfyufei** [rstudio/rstudio#12197]
### System details

    RStudio Edition: R studio server
    RStudio Version :  2022.07.1+554
    OS Version: Ubuntu 22.04.1 LTS 
    R Version: 4.2.1

### Steps to reproduce the problem

- Add `www-frame-origin=59.66.XX.X(my IP address)` to /etc/rstudio/rserver.conf
- Use `<iframe id="rstudio" src="http://103.238.XXX.XX:8787/"></iframe>` in obsidian or rmd to embed R Studio Server in the iFrame
- Tried to log in, got "Error: Temporary server error, please try again" error
![Screen Shot 2022-10-21 at 4 53 14 PM](https://user-images.githubusercontent.com/58319029/197155426-b3865e70-b439-48ba-b8e8-f8b37eb672ee.png)

### Describe the problem in detail

I tried to embed R Studio Server in Obsidian software to complete my R-Obsidian workflow.
From the [official RStudio manual](https://docs.rstudio.com/ide/server-pro/1.2.981-2/tutorial-api.html#tutorial-api) I found that R Studio disables this embedding by default for security reasons, but it can be set with the parameter `www-frame-origin`. I configured it according to the official R Studio manual but still could not embed it in files like Obsidian or Rmarkdown.

### Describe the behavior you expected

Please check if the above error is caused by R Studio settings

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
This is a pro feature (as denoted in the admin guide).  see https://docs.rstudio.com/ide/server-pro/latest/tutorial_api/configuration.html#allow-iframe
Closing this.
