### ISSUE TITLE
"Find in Files" feature not finding some strings in a javascript file

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#12207]
This is one of those bugs that are leaving me completely confused, making me think that magic exists.

To reproduce (at least on my machine, I tried it three times):

1. Create a new RStudio project using the git repo https://github.com/daattali/timevis/
2. Do a "Find in Files" and unselect all the checkboxes (don't exclude any files/folders, search all file types, don't be case sensitive)
3. Search for the string `setcustomtime`
4. Several results are shown, but it cannot find the results in the file `inst/htmlwidgets/timevis.js`
5. I've been able to replicate this with other strings - they're not found in that one file

Here is a screenshot of the "Find in Files" wizard

![image](https://user-images.githubusercontent.com/952340/197303634-936e8e6f-9b5c-4aca-9497-272ae7b26bca.png)

And these are all the results:

![image](https://user-images.githubusercontent.com/952340/197303650-0753ba67-8b51-4fd4-9d26-13f94176ad9f.png)

---

RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by kevinushey** [comment]
Do you see this in the latest daily builds? We fixed a Find in Files bug that you might be hitting here. https://dailies.rstudio.com

**Comment by kevinushey** [comment]
Also try setting Sys.setenv(RSTUDIO_GREP_DEBUG = 1) and check if anything relevant shows in the console output.

**Comment by daattali** [comment]
That's the fastest github isue reply I've experiened. Will repot in a few minutes

**Comment by daattali** [comment]
Yep the daily has this solved!

**Comment by daattali** [comment]
Very curious to see the issue/fix if you happen to remember the PR for it off hand. Don't worry if not

**Comment by kevinushey** [comment]
See:

https://github.com/rstudio/rstudio/issues/11736

https://github.com/rstudio/rstudio/pull/12019
