### ISSUE TITLE
[FR] Button Run all chunks above to also run children documents assigned with the `child` chunk option

### ISSUE THREAD

**Issue by avila** [rstudio/rstudio#12208]
Button `Run all chunks above` to also run children documents assigned with the `child` chunk option. 

This [has been asked](https://community.rstudio.com/t/best-way-to-run-child-markdowns-and-or-bookdown-chapters-interactively-in-rstudio/46495) a [few times](https://community.rstudio.com/t/how-can-i-run-all-chunks-across-all-documents-in-a-bookdown-project/5557) and seems to be the expected behaviour for documents with children files. 

Since I haven't found an _official_ response whether this is possible to implement (or a bad idea), I'm writing this feature request. I hope this is the correct place for that. If not, apologies. 

BTW, I also asked the question on SO: https://stackoverflow.com/q/73997838

This issue was migrated from https://github.com/rstudio/rmarkdown/issues/2417

**Comment by avila** [comment]
Here is a little reprex to explain better the issue: 

Suppose we have two documents, a main and a child. In the first chunk the child document is called from the main via the `child="path"` option. When compiling the document, eg, via `Ctrl+Shift+K`, it works as expected. 

But when running it interactively, the buttons "Run all chunks above" or "Run Current Chunk" or also calling via `Ctrl+Alt+R` or via the "Run All" button, the child document is not called from the main document. The only way to run it interactively is to open the child(ren) and `run all` from there. 

It would be great if they could be called from the main document. 
----
(Main Doc)

    ---
    title: "Main doc"
    output: html_document
    ---
    
    ```{r from main, child="/tmp/child.Rmd"}
    # call child doc
    ```
    
    ```{r}
    print(x*2)
    ```

----
(child doc)

    ---
    title: "Child doc"
    output: html_document
    ---
    
    ```{r from child}
    # from child doc
    x <- 1
    print(x)
    ```

(Output document)
![image](https://user-images.githubusercontent.com/31955632/197309251-6bb046cd-a630-4b9c-b658-7a02b9fe7dea.png)
(calling from the main doc interactively)
![image](https://user-images.githubusercontent.com/31955632/197309700-587def6e-5522-4302-b320-3aeb1e1a4522.png)

**Comment by ronblum** [comment]
@avila Thank you for raising this, and referencing the Community questions etc. I can reproduce this on MacOS 13 using RStudio Desktop 1.4.1743 and 2022.12.0-daily+286.

Added note: If running just the first chunk, which calls the child doc, `x` doesn't get set:

```
> # call child doc
> x
Error: object 'x' not found
> 
```
