### ISSUE TITLE
Option to not modify .Rbuildignore

### ISSUE THREAD

**Issue by jangorecki** [rstudio/rstudio#12209]
Hello,
I would like to request an option for RStudio to not automatically modify by .Rbuildignore file.
It's a little annoying that file is being regularly modified by RStudio and I need to git restore every time. There should be an option to switch it off, haven't found one like this.

The reproduce just create directory storing new package having .Rbuildignore file, then open RStudio and create a project in that existing directory. .Rbuildignore will get modified by adding extra lines to it.

**Comment by kevinushey** [comment]
What lines are being added, and how are they adversely impacting the package build process?

**Comment by jangorecki** [comment]
I didn't mean those added lines are impacting adversely building of a package. They impacting git process. Lines are related to RStudio files like .Rproj etc.
I get the idea it is useful to have those lines there, but if user decide not to, then this could be respected, and not routinely being added to the file, forcing user to git restore .Rbuildignore repeatedly. Each time when user wants to change a branch. Setting this file to not be tracked in git unfortunately doesn't handle cases like checkout to branch where that file doesn't exist (i.e. gh-pahes). So IMO file should be modified only once, and not repeatedly, or there should be an option to switch it off.

**Comment by kevinushey** [comment]
You could just commit the changes?

**Comment by kevinushey** [comment]
Otherwise, if you were willing to submit a PR, that code lives here. https://github.com/rstudio/rstudio/blob/1675d5d7a716a464208179336d3a99b1aaae90e4/src/cpp/session/projects/SessionProjectContext.cpp#L287-L395

**Comment by jangorecki** [comment]
I could, but they are useless if I don't build package locally. If I only git push and build it remotely, then I don't have to worry about those files, so then I also don't have to worry about putting unrelated things to .Rbuildignore.
