### ISSUE TITLE
Allow Cloud publishing accounts to be deleted

### ISSUE THREAD

**Issue by mbaynton** [rstudio/rstudio#12206]
### System details

    RStudio Edition : Desktop
    RStudio Version : Latest Dailies
    OS Version      : Ubuntu Focal
    R Version       : 4.2

### Steps to reproduce the problem
1. Install rsconnect
2. Add a new Publishing account for Posit Cloud / Rstudio Cloud (Tools -> Global Options)
3. Account cannot be removed ("Disconnect"ed):
![image](https://user-images.githubusercontent.com/3026002/197287175-b6fbd8e8-d713-4b68-ae27-12043d1be66b.png)

### Describe the problem in detail
I think this was a request from the Hosted team and was implemented this way intentionally. We should use this issue to discuss how to allow users some ability to undefine these accounts through the UI.

### Describe the behavior you expected
Users can remove Cloud publishing accounts, at least if they added the accounts themselves.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mbaynton** [comment]
Possible resolutions:
1. Just re-enable the button unconditionally for rstudio.cloud type accounts.
2. Re-enable the button for rstudio.cloud-type accounts that were not injected by the Cloud environment in a running Cloud project. Significantly more work, how important is it?
3. Re-enable the button for rstudio.cloud-type accounts until there is only one such account defined.

**Comment by jgutman** [comment]
I think option 2 would be contingent on there being a method in rsconnect that returns true only for the injected account

**Comment by mbaynton** [comment]
We discussed this in Hosted grooming today and have decided we collectively like option 1

> Just re-enable the button unconditionally for rstudio.cloud type accounts.

**Comment by jgutman** [comment]
@mbaynton do you want the "Reconnect" button re-enabled as well, or just the "Disconnect" ?
for shinyapps.io, "Reconnect" is disabled but "Disconnect" is enabled -- so rstudio.cloud should be same as shinyapps.io?

**Comment by mbaynton** [comment]
@jgutman yeah, same as shinyapps.io. Sorry for the flip-flop on the ask here.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.12.0-preview+299 on MacOS 13:
- Disconnect works.
- Reconnect is disabled.
