### ISSUE TITLE
rsconnect account filtering is based on content type, not server type

### ISSUE THREAD

**Issue by mbaynton** [rstudio/rstudio#12204]
### System details

    RStudio Edition : Desktop
    RStudio Version : Latest Dailies
    OS Version      : Reproed on Ubuntu Focal, Mac
    R Version       : 4.2

### Describe the problem in detail
When publishing a new Rmd document, this window prompts you to select the type of destination to publish to:
![image](https://user-images.githubusercontent.com/3026002/197283251-f2a0d83f-68d1-4275-a6ad-3bd391770f69.png)

If you select Posit Cloud, the next window offers Connect servers as destinations:
![image](https://user-images.githubusercontent.com/3026002/197283462-232b4ba8-6d76-4daa-a53b-cd8aeb449c40.png)

(note that in this screenshot, _only_ connect accounts are shown. If Cloud accounts have been configured, those do also appear. Shinyapps.io accounts do not appear, however, which is correct.)

### Describe the behavior you expected
If I choose Cloud in window 1, I am only shown Cloud accounts in window 2. (and similar for Connect of course)

If no accounts for that server type have been configured, I am prompted to add an account of that type.

### Steps to reproduce the problem
1. Configure a publishing account for Connect in your Global Options
2. Create a new RMarkdown document
3. Publish the document
4. Click Posit Cloud when prompted where to publish to

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
Reconsider for Desert Sunflower?

**Comment by jonvanausdeln** [comment]
What I'm currently seeing:
on Windows 11 & MacOS (M1) 12.6
Latest `rsconnect` package

* Use `rsconnect` to connect an account for posit cloud on console
* Check account shows up correctly in Global Options
* Attempt to publish a .rmd file to cloud, and account does not show up in wizard

![image](https://github.com/rstudio/rstudio/assets/6433789/401f4576-15e9-4520-b22a-9e6b49c0b242)
![image](https://github.com/rstudio/rstudio/assets/6433789/f0abf76f-c3f0-4a09-8ccc-5e7a72f83c70)

This seemed to work as expected on Ubuntu22.

Note, I also tried adding the account in the publishing wizard directly, and still doesn't show.

I also removed all accounts (the rsconnect shown in the screenshots), cloud account still won't show in publishing wizard.  I was however able to add back in the rsconnect account without issue.

**Comment by jgutman** [comment]
I'm going to see if I can reproduce this. Do you see the same behavior with just the rstudioconnect and posit.cloud accounts connected? (If you remove the radixu account). I also really don't understand why this would behave differently on Ubuntu vs Mac and windows

**Comment by jonvanausdeln** [comment]
I agree.. It might be something in my machine setup.. I don't really know. I removed the radixu account (and the beta account as that server doesn't exist now) and added only the cloud account, and didn't see the cloud account in wizard.  I also added the radixu account back in and they show up just fine.

**Comment by jonvanausdeln** [comment]
I also just ran it all directly from console and it works correctly from `rsconnect` directly

```
rsconnect::accounts()
                   name      server
1 4tj90w-jon-vanausdeln posit.cloud
> rsconnect::deployDoc('asdfa.Rmd')
ℹ Discovering document dependencies...
✔ Document dependencies discovered
── Preparing for deployment ────────────────────────────────────────────────────────────
✔ Deploying "asdfa" to "server: posit.cloud / username: 4tj90w-jon-vanausdeln"
ℹ Creating application on server...
✔ Created application with id 6275990
ℹ Bundling 1 file: asdfa.Rmd
ℹ Capturing R dependencies with renv
✔ Found 31 dependencies
✔ Created 17,891b bundle
ℹ Uploading bundle...
✔ Uploaded bundle with id 7529476
── Deploying to server ─────────────────────────────────────────────────────────────────
Waiting for task: 70d40e50-448e-4421-be91-b815892304b1
  started: name=deploy-server-static-application-build-and-render
  started: name=deploy-server-static-application-deploy-result
  success: 
── Deployment complete ──────────────────────────────────────────────────────────────────
✔ Successfully deployed to <https://posit.cloud/content/6275990>
> 
```

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+349](https://dailies.rstudio.com/version/2023.09.0-daily+349)
Windows11, MacOS 12.6 (m1)

I now see the correct accounts for associated destination. And it is published correctly.
