### ISSUE TITLE
Link to add new publishing account always assumes account type is Connect

### ISSUE THREAD

**Issue by mbaynton** [rstudio/rstudio#12205]
### System details

    RStudio Edition : Desktop
    RStudio Version : Latest Dailies
    OS Version      : Ubuntu Focal, Mac
    R Version       : 4.2

### Describe the problem in detail
This relates to the Publish dialog that is shown when publishing an Rmd document. It's similar to #12204 .

If I publish a new Rmd file and select Posit Cloud as the destination where I want to publish to, I get this window:
![image](https://user-images.githubusercontent.com/3026002/197285747-556fb933-38d8-42d9-8c4e-6da02144e823.png)

If I choose Add New Account in the above window, I get the window to create a new Connect account, not a new Cloud account
![image](https://user-images.githubusercontent.com/3026002/197285876-e1838fe8-756c-4357-9bff-31dcf187c965.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified that this works correctly in RStudio Desktop 2022.12.0-daily+299 on MacOS 13.
- Publishing a source document in the IDE
- Publishing a rendered document in a window
- Publishing a rendered document in the Viewer Pane
- Setting up <kbd>Global Options -> Publishing</kbd>

(Granted, these all go through the same flow but still worth verifying.)
