### ISSUE TITLE
Goto file function misbehaving

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/rstudio#12210]
### System details

    RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Ubuntu Bionic
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Steps to reproduce the problem
Open or continue working inside a source file.
Press ^.
Start typing a source file name

### Describe the problem in detail
If I use the usual <.>enter to search for an R file, it is strangely not detecting the R file even if its lying in the current working directory. The feature misbehaves many times and also gets alright on its own. Seems like some index corruption happens periodically.

### Describe the behavior you expected
Expected behaviour is that all the names dropped down must have the typed letters and all matches should be dropped down, not just a few. The highest matching should be at the top. 

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[See the problem replicated in this screencast video.](https://www.loom.com/share/d4e7ff08143f49ec95d94a3e8a3be13f)

**Comment by kevinushey** [comment]
Thanks for taking the time to share a screencast describing the issue. Some other questions:

- Does the issue persist after restarting the R session?
- Does the issue seem to crop up only after some amount of time of working in the session, or something similar?
- Does it make a difference if you open / edit / save the affected file, or does it seem independent of that?

Any other information that you might be able to provide would be helpful, as we'll have trouble fixing this unless we can reproduce locally.

It might also be helpful if you could share a diagnostics report, in case there are any relevant errors in the logs. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

**Comment by sanjmeh** [comment]
> Does the issue persist after restarting the R session?

The issue persists. I just tested it.

> Does the issue seem to crop up only after some amount of time of working in the session, or something similar?

Since it continues after a clean R start we can presume it is not dependent on the time of the session. I definitely noticed it quite frequently after working for some time too. So seems it is independent of time.

> Does it make a difference if you open / edit / save the affected file, or does it seem independent of that?

Tried this just now by editing a couple of files. One of the two files came up in the search while the other is still getting missed. Quite wierd ! 

Attaching screenshots of attempts made.
![Screenshot 2022-10-25 at 1 13 06 PM](https://user-images.githubusercontent.com/3091624/197715035-9e751943-6f79-46d1-8a73-b78417c91603.png) 
Note the file name (`cron_10mins.R`) is shown in parenthesis in search results but not in the main list. Which means it has access to the file, it just doesnt like its name. I have seem this in other files (non numeric names) too just in case you read too much in the construct of the filename.

After making a small edit however this file (`cron_10mins.R` )came up in the results on typing `cron`

![Screenshot 2022-10-25 at 1 23 59 PM](https://user-images.githubusercontent.com/3091624/197716153-18915e8c-0ef4-4199-901b-4862bc7a8c15.png)

But this didnt work on the other experiment I did.
![Screenshot 2022-10-25 at 1 17 14 PM](https://user-images.githubusercontent.com/3091624/197716229-642c3994-3819-492c-aa7e-340acc31245e.png)
So the file `smallfns.R` is still not searchable.

A third file `insights.R`, which is a much larger and an older file, was also excluded in the search -  in case you want to know if the size or age of the file matters. It doesn't.
![Screenshot 2022-10-25 at 1 10 49 PM](https://user-images.githubusercontent.com/3091624/197717651-1c68455b-20d9-464c-8158-37b5e3dbb975.png)



One thing I can say, the size of my home directory is huge with multiple subdirectories.

**Comment by kevinushey** [comment]
Thanks -- it's especially mysterious that you could have completion items parsed from an indexed file, but have the file itself omitted from the search results!

One thing that might be useful to see -- what does the output look like if you run:

```
.rs.listIndexedFilesAndFolders(maxCount = 10000)
```

Do you see the mentioned file as part of that list? Or do you see a large number of indexed files from a separate location?

> One thing I can say, the size of my home directory is huge with multiple subdirectories.

Are you working within an RStudio project? Or just the home directory? It's possible that this could be tripping things up.

**Comment by sanjmeh** [comment]
On running  `.rs.listIndexedFilesAndFolders(maxCount = 10000)` indeed I found more than 10000 files that were in a few error collection subdirectores, and they were very small RDS files so escaped my attention. I have removed all the files and cleaned these subdriectores to zero files, and run the above command again.
This time I still see a thousasnd+ excel files in the list.  See a screengrab here.
![Screenshot 2022-10-27 at 8 22 08 PM](https://user-images.githubusercontent.com/3091624/198324652-9e91a65e-7541-46b7-a752-b59b424fe61f.png)

It seems it is these large number of files that are corrupting the indexing.

So why are data files indexed? 
Ideally rstudio IDE should take only `.[Rr]` and `.[txt]` at the most. But `.csv` and `.xlsx` should never be picked by default. And `.RDS` and `.fst` surely not. Although I admit I forgot the extention on those error files - the `.RDS` was missed hence the indexing algo could have run haywire. My apologies for that goof up.

On the search problem give me some time to see if the problem has gone with these cleanups or not.

Thanks for probing this in depth.
I love Rstudio.

**Comment by sanjmeh** [comment]
Removed 152K RDS files from a subdirectory !! I am extremely sorry to be storing so many RDS files inside the main project directory. But there has to be a `.gitignore` type config in rstudio somewhere to bypass these data files.
![Screenshot 2022-10-27 at 8 45 50 PM](https://user-images.githubusercontent.com/3091624/198329670-3d102bda-cd01-4d4d-997f-62856c6a212f.png)

**Comment by kevinushey** [comment]
> So why are data files indexed?

Good question -- as I understand it, we just index all files in the project folder and then decide post-hoc which would be suitable for presentation in different contexts (e.g. searching in Find in Files). We could probably reconsider that decision, though.

> Thanks for probing this in depth.
> I love Rstudio.

I'm glad to hear it :-) I appreciate your persistence and thorough bug reports!
