### ISSUE TITLE
Enhance the navigation and selection within generated plot.

### ISSUE THREAD

**Issue by coforfe** [rstudio/rstudio#12213]
Hi,

**Current behaviour**: When generating multiple plots, it is very tedious as well as slow to move back and forth with the arrows until selecting the needed chart. Each plot has to be rendered when clicking in any of the arrows, so the navigaion is not smooth.

**Enhancement**: The idea would be to show under the _Plot_ tab, the collection of plots generated (small plots) and just click on the desired one that would be fully rendered.

Thanks,
Carlos Ortega.

**Comment by ronblum** [comment]
@coforfe Thank you for the interesting suggestion! We'll review it as we continue to develop and enhance RStudio.
