### ISSUE TITLE
Javascript exception error trying to preview content in Viewer Pane

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12220]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0-daily+285 "Elsbeth Geranium" Daily
    OS Version      : macOS Monterey 12.6, Windows-11
    R Version       : 4.2.1

### Steps to reproduce the problem

* start RStudio
* File / New File / R Notebook (I also repro'd with a plain Markdown file)
* accept defaults
* save the resulting file (I left it as Untitled.Rmd)
* gear icon in the document toolbar, select "Preview in Viewer Pane"
* click the Preview button

### Describe the problem in detail

* get an error dialog titled "A JavaScript error occurred in the main process"

```
Uncaught Exception:
TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (node:internal/errors:371:5)
at onParseError (node:internal/url:552:9)
at new URL (node:internal/url:628:5)
at _.setViewerUrl (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:8:455241)
at IpcMainImpl.<anonymous> (/Applications/RStudio.app/Contents/Resources/app-x64/.webpack/main/index.js:17:17697)
at IpcMainImpl.emit (node:events:526:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
at EventEmitter.emit (node:events:526:28)
```
* dismiss the dialog, then the content does display in the Viewer

### Describe the behavior you expected

* no error dialog

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio 2022.12.0-preview+299 on MacOS 13.
