### ISSUE TITLE
Warning from pandoc when knitting to PDF

### ISSUE THREAD

**Issue by krcoombes** [rstudio/rstudio#12234]
I recently upgrade RStudio to version 2022.07.2 Build 576. Since that upgrade, I have started getting the following warning whenever I knit an Rmarkdown file to a PDF output:

[WARNING] Deprecated: --self-contained. use --embed-resources --standalone

I don't know if the issue is somewhere in RStudio, or somewhere in knitr (Version 1.39) or somewhere in rmarkdown (Version2.14). (I am using whatever version of pandioc was installed when I upgraded RStudio.)  But, since the warning tells you what to do in order to avoid the message when you invoke pandoc, it would be nice if the appropriate package/program were updated to make the warning go away.

**Comment by kevinushey** [comment]
This should be fixed with rmarkdown 2.16:

https://github.com/rstudio/rmarkdown/blob/607290ccab1ec1acab419bf0a05f1d046d4596b5/NEWS.md#rmarkdown-216

Are you able to update?
