### ISSUE TITLE
Migrate RStudio from Electron to Tauri

### ISSUE THREAD

**Issue by hammer** [rstudio/rstudio#12230]
Hey @jjallaire, have y'all ever discussed whether it makes sense to migrate from Electron to [Tauri](https://tauri.app/)?

**Comment by gtritchie** [comment]
We're still migrating the RStudio IDE TO Electron!

**Comment by ilikegitlab** [comment]
Can someone point me to a tauri build or was this closed as completed in error?

**Comment by kevinushey** [comment]
There are no plans to migrate to Tauri at this time, so we intended to close this as not planned.

**Comment by ilikegitlab** [comment]
thanks for clarifying! Nevertheless quite unfortunate, it would be far easier to package rstudio. Electron is a mess for distro maintainers. I'll hope things change in the future.
