### ISSUE TITLE
No autocomplete for `div` block in RStudio for Quarto

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#12233]
RStudio Edition : Desktop
    RStudio Version : 2022.07.2
    OS Version      : Windows 10
    R Version       : 4.2.1

In VSCode-Quarto, the autocomplete is available for `div` block, but this seems not available in RStudio. 

VSCode-Quarto
![image](https://user-images.githubusercontent.com/4111978/198184325-a73d1049-669b-4013-b741-02b4237a4699.png)

RStudio
![image](https://user-images.githubusercontent.com/4111978/198184426-72822ddf-6f42-4bad-9c01-8ac71af4f8d1.png)

**Comment by ronblum** [comment]
@Fred-Wu Thank you for raising this! I'll mark this for review as we continue development of RStudio's integration with Quarto.
