### ISSUE TITLE
Spell checker should (could?) not run on comments in R chunks in Quarto slides

### ISSUE THREAD

**Issue by lnalborczyk** [rstudio/rstudio#12236]
Hi,

it would be nice if the ABC + check button contained an option to ignore comments in R code chunks when checking the spelling of a Quarto (.qmd) document, which seems to currently not be the case.

As an example, I have some slides hosted at: https://github.com/lnalborczyk/IMSB2022/blob/master/slides/_cours02/Cours02.qmd

Thank you!

Ladislas

My config

RStudio Edition: Desktop
RStudio Version: v2022.07.1
OS Version: macOS Big Sur v11.6 
R Version: 4.2.1

**Comment by ronblum** [comment]
@lnalborczyk Thank you for creating this as a separate issue! I'll mark it for consideration as we continue development of RStudio, Quarto, etc.
