### ISSUE TITLE
Connections to Posit Cloud don't show up in the publishing wizard

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12239]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0-daily+291
    OS Version      : MacOS 13
    R Version       : 4.2.1

### Steps to reproduce the problem

1. Set up publishing to Posit Cloud using https://rstudiopbc.atlassian.net/wiki/spaces/ENG/pages/125403433/Cloud+Publishing#R-Based-Outputs
2. Create a static Rmd document as described in https://rstudiopbc.atlassian.net/wiki/spaces/ENG/pages/126746625/Cloud+Publishing+-+R+Markdown+Static+Documents
    - Do not follow step 7, as we're going to try publishing via the UI.
3. Click on the Publish icon.
4. <kbd>Posit Cloud</kbd>
5. There's a bug trying to get you to publish to Connect, so hit "Cancel".
6. <kbd>Add New Account</kbd> -> <kbd>rstudio.cloud</kbd>
7. In a web browser, log in into RStudio Cloud (currently on staging) and copy the publishing access token.
    - You need to be part of the publishing beta program to do this.
8. In RStudio Desktop, paste the token.
9. <kbd>Connect Account</kbd>
    - We're back to the "Publish" window, with no account added.

### Describe the problem in detail

The connection process doesn't create a connection to Posit Cloud.

<img width="575" alt="cloud_setup_wizard" src="https://user-images.githubusercontent.com/31009952/198349705-fb624939-ba71-4d21-8baf-e2f97863328b.png">

Note that if you switch to <kbd>Global Options -> Publishing</kbd>, a connection shows up, for `shinyapps.io`.

### Describe the behavior you expected

A connection should be added to the publishing wizard, as it does with Posit Connect.

Triage note: This needs to be done for Elsbeth Geranium. Otherwise, I don't see how publishing can actually be done.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Looks like this is blocking Ron from testing this fully.

**Comment by jgutman** [comment]
Are you using the correct version of reconnect? From github? What's the version

**Comment by ronblum** [comment]
Literally all I did was wait a few hours, stop RStudio, and restart it, and now it works. 

Closing this. I'm able to publish successfully.
