### ISSUE TITLE
The title bar above the menu bar is light even in the dark theme (in daily builds)

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12247]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.12.0.292
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

On Windows:

1) Open RStudio and use the dark theme (Modern).
2) Change Windows colors (color theme) to dark 
![image](https://user-images.githubusercontent.com/12725868/198636631-4d245932-4d2a-4668-abbc-9a62b96a9dca.png)
3) Look at RStudio's appearance
4) Change Windows colors (color theme) to light
5) Look at RStudio's appearance

Repeat the same with the RStudio daily builds version and the current stable version. Pay attention to the menu bar and the title bar above it.

### Describe the problem in detail

In the daily builds version, RStudio's menu bar changes color while the title bar above is always light:

![image](https://user-images.githubusercontent.com/12725868/198638296-fe58631b-0bff-4edf-bedb-de500e350a32.png)

![image](https://user-images.githubusercontent.com/12725868/198638372-c496b00f-f81b-495f-94df-688f31e13a8f.png)

That light title bar above now distracts attention. It should also become dark.

### Describe the behavior you expected

I expect the menu bar to be gray as in the current stable RStudio version:
![image](https://user-images.githubusercontent.com/12725868/198640831-bdb5e8d4-f5b7-4c46-9711-52fa07c42fc0.png)
And the title bar should change color in accordance with the Windows color theme.

If it is not possible to change the color of the title bar, it is better to keep the gray menu bar and not black to have less contrast.

**Comment by ronblum** [comment]
@GegznaV Thank you for pointing this out!

@timtmok Do we still have control over this, or did we lose control due to Electron?

**Comment by gtritchie** [comment]
For reference: https://www.electronjs.org/docs/latest/tutorial/dark-mode

**Comment by gtritchie** [comment]
Talked about here:

https://github.com/electron/electron/issues/23479

May finally be fixed (by default) with Electron 20+ on Windows-11 (I haven't tried it to verify), but not on Windows-10 (though there is talk of a fuse that shows how to accomplish it using undocumented Windows APIs).

https://github.com/electron/electron/pull/33624

**Comment by timtmok** [comment]
Based on that, it won't be supported until Electron is updated to 20+.

**Comment by gtritchie** [comment]
We could consider ignoring the OS's dark mode and only displaying the IDE in light mode.

Then we don't get that mismatched title bar/menu bar, but we also then don't get dark-themed dialog boxes.

However, since the rest of our UI (the web part) doesn't pay attention to dark mode (we should do that via media queries, etc. but wouldn't be trivial), perhaps ignoring dark mode altogether is worth considering for now, at least on Windows.

FWIW I tried it on Windows by adding this line to startup() in main.ts and no longer got the dark menubar 

`nativeTheme.themeSource = 'light';`

**Comment by gtritchie** [comment]
Another mitigation would be to finish [the autohide menu feature](https://github.com/rstudio/rstudio/issues/8932) which gives the option to hide the menubar unless you hit the Alt key (WIndows and Linux).

I had started coding that a while back (`feature/autohide-electron-menubar`) only to hit a problem where tapping Alt wasn't making the menubar show. Presumably we're eating that keystroke somewhere but I didn't investigate further. I did confirm it still happens by merging main into that branch and trying it again:.

**Comment by J-T-Nelson** [comment]
I am not trying to get involved in this process but had some issues with the newest version of RStudio "Elsbeth Geranium" which lead me here, though not all problems are reported here. 

The title bar is broken for me too, beyond that, the ability to change themes in Global Options > Appearance, is also entirely nonfunctional. 

I also encountered an issue of attempting to uninstall Elsbeth Geranium then installing the 2022.07.2-576 version in the same folder, but that would fail to actually launch successfully, no process started at all on my machine (running Windows 10). I don't know if this is intended, but I assume it would be ideal to be able to switch versions while preserving user settings and preferences from one to the next all within the same folder, but maybe that is a just a totally wrong assumption of mine. 

Again, I don't want to be deeply involved, that is why I am merely describing these issues. I figured I would share as this set of issues is enough to force me to avoid the new release all together until they're fixed for now.

**Comment by lionel75013** [comment]
I am postponing updating my RStudio version since Spotted Wakerobin because of this. I am restricted to use windows in my work, and cannot stand the visual impact of this white menu bar.
Is there any dirty fix that can be applied on a recent version of Rstudio or even on electron somehow ?
Thanks for the Help.

**Comment by gtritchie** [comment]
@lionel75013 : I am working on fixing this now, and it will be in the next RStudio release (2023.05 - Mountain Hydrangea).

**Comment by ronblum** [comment]
Verified fixed in RStudio 2023.05.0-hourly+165 on Windows 11.
