### ISSUE TITLE
Merge the main title bar and menu bar

### ISSUE THREAD

**Issue by daxiagithub** [rstudio/rstudio#12249]
The current title bar of Rstudio is only used to display Rstudio icon and sometimes project name and leaves large area unused.  Could we merge the menu bar and title bar like those in VS Code (see the screen shots below) to make a cleaner interface and save some screen real estate?  I assume this can be "easily" done since Rstudio is moving to Electron, which is also used by VS Code.  

Thank you very much!

Rstudio
![image](https://user-images.githubusercontent.com/14238547/198713012-6dc7e54a-48f2-4bce-abc8-315077e910d7.png)

VS Code
![image](https://user-images.githubusercontent.com/14238547/198713168-a7b3eef2-66ad-4144-bbff-5ef70d42f717.png)

**Comment by gtritchie** [comment]
FWIW, the last time I looked, this isn't a built-in feature of Electron, but something custom-coded by VS Code.

**Comment by daxiagithub** [comment]
Good to know. Thanks!  Hopefully it's not too hard to custom-code.

**Comment by daxiagithub** [comment]
While reading Kevin's comment on the other issue (https://github.com/rstudio/rstudio/issues/1685#issuecomment-988261412), I just realized that you guys have kind of done this on the Rstudio server already (i.e. getting rid of the title bar and put the R logo in front of  the menu bar and tool bar).  

It would be nice if this can be implemented in the desktop version.

**Comment by olivroy** [comment]
It seems like Electron has some way of supporting that. I think it would make RStudio look better and more usable, especially on Windows. 

It is probably more complicated that a [6 minutes youtube video](https://www.youtube.com/watch?v=I1_aeciYALI), but it sure seems promising. Seems to be using only a few options https://www.electronjs.org/docs/latest/tutorial/window-customization#window-controls-overlay-macos-windows 

```r
createWindow
 frame: false
 autoHideMenuBar: true

```

And then just the idea of adding back the menu items to the top along with RStudio logo, and any other useful feature of a menu bar.

There are a lot of blank space to fill at the right of the menu.
---

![image](https://github.com/rstudio/rstudio/assets/52606734/ef0f3779-8cba-41b5-afb5-f2a5958f3644)

---

**Comment by daxiagithub** [comment]
I guess this is now partially resolved with an option of auto-hiding the menu bar (#8932).  It's nice to have this option, but I'm still thinking about how to utilize those empty space in the title bar :-).

**Comment by olivroy** [comment]
I agree!

**Comment by gtritchie** [comment]
I make zero promises that I or anyone else will have time to look into this further anytime soon, but it's worth keeping this alive so reopening the issue.

**Comment by olivroy** [comment]
I'd still think it's a good idea. However, it seems like this conflicts with solving #8932, which mitigates the issue. So probably better to close this one?
