### ISSUE TITLE
The icon of RStudio project file on Windows changed (in daily builds)

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12246]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.12.0.292
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

Open a folder in Windows Explorer with `.Rproj` file.

### Describe the problem in detail

The icon pr RStudio project file is not the same as in the stable version of RStudio.
![image](https://user-images.githubusercontent.com/12725868/198625978-0b782e21-7608-4ca8-b3e0-19c5d5cdd8ce.png)

### Describe the behavior you expected

I expect the same icon as in the current stable version of RStudio:
![image](https://user-images.githubusercontent.com/12725868/198627122-a89da13b-9131-465f-b1e9-b188b8d0d386.png)

**Comment by gtritchie** [comment]
Also happening on Mac.

**Comment by gtritchie** [comment]
The Windows installer bit that should be doing this is here: https://github.com/rstudio/rstudio/blob/39736ee1b7705e0340dbfba7cdc4e300fcfeee54/package/win32/CMakeLists.txt#L91

But "rstudio.exe" (Electron flavour) is missing icon #2. Here's what's in Electron:

![image](https://user-images.githubusercontent.com/10569626/198688263-4e011be3-b05f-455d-82da-dd3df03e76f8.png)

Here's what's in Qt:

![image](https://user-images.githubusercontent.com/10569626/198688676-d5121e68-58f8-4427-b70e-016f96a1c81d.png)

**Comment by gtritchie** [comment]
The Qt build embeds the icon here. Need to figure out how to do same with our Electron build (or reference the icon elsewhere):

https://github.com/rstudio/rstudio/blob/39736ee1b7705e0340dbfba7cdc4e300fcfeee54/src/cpp/desktop/rstudio.rc.in#L4

**Comment by kevinushey** [comment]
IIUC we rely on electron-forge to embed the icon, and that happens here:

https://github.com/rstudio/rstudio/blob/8da33f1631b19947283b770a71d6b376e5b9e953/src/node/desktop/forge.config.js#L57-L71

https://electron.github.io/electron-packager/main/interfaces/electronpackager.options.html#icon

Is it possible for us to combine the various icons into a single `.ico` here for Windows?

**Comment by kevinushey** [comment]
Apparently electron-packager relies on rcedit for injecting the icon (and other related resources):

https://github.com/electron/rcedit
https://github.com/electron/electron-packager/blob/5aac8c91ba6dda634f5af0c1d163a74002f63791/src/win32.js#L79-L99

so it seems like this workflow is locked into the single `.ico` workflow...

**Comment by gtritchie** [comment]
`electron-builder` seems to support it (though I haven't tried it out). Look at `fileAssociations` here:

https://www.electron.build/generated/platformspecificbuildoptions

Changing our Electron bundling tool at this stage of the release is probably a recipe for sadness.

**Comment by gtritchie** [comment]
This tool _might_ be able to do it: http://angusj.com/resourcehacker/

**Comment by gtritchie** [comment]
Yes! I was able to add the icon to the latest daily build of Electron, and now .rproj files show the correct icon.

I did it interactively, but the program is supposed to be able to do most things via command-line.

**Comment by GegznaV** [comment]
The issue is still present with:

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.12.0.294
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)
    
Or should there be a newer build?

**Comment by gtritchie** [comment]
> The issue is still present with

I didn't fix it, just did a manual experiment to explore possible fixes and provide info to whoever does end up fixing it.

**Comment by gtritchie** [comment]
I had already done most of the work to fix this, so did the final little bit and moved this issue to Elsbeth Geranium.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-preview+307 Desktop Windows 11

Icon shows correctly for project files in explorer

**Comment by zhaoliang0302** [comment]
Same in Windows 11 x64 22H2. I tried several version of Rstudio, all the .R and .Rproj files will not automatically associated with Rstudio after installtion. I should open them and chose Rstudio to open them manually. Icons of all these files look same.
