### ISSUE TITLE
Tab is inserted instead of space (in daily builds)

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12245]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.12.0.292
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

In R code press <kbd>Tab<kbd> (in new line), or press <kbd>Enter<kbd> to create multi-line code when auto indentation appears, or select code and press <kbd>Ctrl<kbd>+<kbd>I<kbd> to auto-indent code.

![RS-tab-instead-of-spaces](https://user-images.githubusercontent.com/12725868/198622944-384c4d45-84a0-4536-bcf2-0d9b94f255f3.gif)

### Describe the problem in detail

Tabs are inserted instead of spaces, even if the setup says not to do that:
![image](https://user-images.githubusercontent.com/12725868/198623548-42adfbf9-f937-463a-b7db-00ee79659ed7.png)

### Describe the behavior you expected

I expect space to be inserted instead of a tab as in the current stable version of RStudio.

**Comment by kevinushey** [comment]
Are you working within an RStudio project? Can you confirm whether the project options have separate editing preferences here? (Tools -> Project Options...)

**Comment by GegznaV** [comment]
Yes, there were changed project options. False alarm. Sorry for bothering you with this issue.

**Comment by GegznaV** [comment]
By the way, is there a way for the project option "Insert spaces for tab" to be inherited from the global option, or do they always have to be set separately?

**Comment by kevinushey** [comment]
Good question -- it looks like we don't have a way of setting that. I think new projects should "inherit" the global value, but that value will then be sticky in the newly-created project.

**Comment by GegznaV** [comment]
So this most probably was the source of my confusion. I thought that all project options can be inherited.
