### ISSUE TITLE
Thinner dividing lines separating panes

### ISSUE THREAD

**Issue by daxiagithub** [rstudio/rstudio#12250]
Another VS Code look-like feature request.  The current thick dividing lines for different panes in Rstudio are taking lots of screen real estates.  It would be nice to make them look like those in VS Code, which are very thin and appear highlighted/thicker only when you mouse over them (figure 2), sometimes even invisible and just separated by different color shades (figure 3).  This will make the interface much cleaner and gain some screen real estate back.   Electron?

Thank you very much!

Dividing lines in Rstudio
![image](https://user-images.githubusercontent.com/14238547/198716960-2444a70b-41e5-4d95-b94d-de329f26f373.png)

Dividing lines in VS Code
![image](https://user-images.githubusercontent.com/14238547/198716904-f3ead051-fa71-453a-bb4d-615ceafcfc39.png)

Different color shades separating menu bar and coding panes
![image](https://user-images.githubusercontent.com/14238547/198717653-b563b1a6-ed2d-4626-ab99-482c66688fc2.png)

**Comment by ronblum** [comment]
@daxiagithub Thank you for the thoughtful design consideration, and for including the VS Code screenshots as a comparison point!
