### ISSUE TITLE
Restarting RStudio launches many external windows on the restart of R

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#12256]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2022.12.0-daily+296 (2022.12.0-daily+296)
    OS Version      :  macOS Monterey
    R Version       : 4.2.0

### Steps to reproduce the problem

- Generate HTML such as a `gt` table in RStudio
- Might throw a Javascript exception (?)
- Restart the R session with Cmd + Shift + 0
- 
https://user-images.githubusercontent.com/29187501/199028857-6fe86fb6-6f2c-44e1-aba9-d230fe29ca87.mp4

### Describe the problem in detail

Generating HTML such as a `gt` table might throw a JavaScript exception and upon restart of the R session will send approximately 20 broken duplicates of the requested content to the default browser.

### Describe the behavior you expected

HTML content should show up in the viewer pane and a restart should clear the environment and any "promised" HTML content.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@timtmok We should at least look at this for Elsbeth; Jackie thinks this might be related to something you were already looking at.

**Comment by timtmok** [comment]
I've managed to reproduce. Looks like it requires running the code once before restarting R.

It looks like the `allowNavigation` check is called on web request. That may trigger opening the external browser if the URL is not on the safe list. This should be moved out to be handled by the caller and only check if the navigation is permitted.

**Comment by timtmok** [comment]
The repo step requires the View pane to be showing content before restarting R. The view tries to refresh the preview with a new URL but has not yet added it to the safe list. By default, URLs not on the safe list will be opened externally and the retries causes multiple open events.

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2022.12.0-preview+316, Windows 11 and MacOS 12.6

With html (similar to initial repro) in the viewer, restarted R numerous times. Behaved as expected without opening many external browser windows/tabs.
