### ISSUE TITLE
auto completion argument echo

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12289]
identified in #12273 but unrelated to the business of the PR. 

When completing a `[`, e.g. `mtcars[foo = <TAB>` the argument is just echo. 

https://user-images.githubusercontent.com/2625526/199948354-757a6404-14aa-4828-9627-b53abfb06457.mov

**Comment by romainfrancois** [comment]
Also an issue in the editor: 

<img width="354" alt="image" src="https://user-images.githubusercontent.com/2625526/199967954-cb5e7bfc-bca7-492b-84ca-ce80c4f38dae.png">

**Comment by romainfrancois** [comment]
Looks like there are already safeguards in place for function calls: 

https://github.com/rstudio/rstudio/blob/0995e6a6a2912a2f5852e43ad1b7492b28e9b664/src/gwt/acesupport/acemode/r_code_model.js#L663-L670

**Comment by mikebessuille** [comment]
@ronblum @jonvanausdeln I am not sure why this doesn't show up on the board? ?  It's correctly in the github project and in the Cherry Blossom milestone.

**Comment by mikebessuille** [comment]
Removed `[` from the start of the title, wondering if that was causing the issue to not show up in the board!

**Comment by mikebessuille** [comment]
Moved it to Mountain Hydrangea to test, and now it shows up on the board.  (Wouldn't when in Cherry Blossom).  Don't know why.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2023.03.0+386 on MacOS 13.2
- RStudio Server 2023.03.0+385 on Ubuntu 20.04 via Chrome on MacOS 13.2


Examples:
*Console*
<img width="337" alt="console" src="https://user-images.githubusercontent.com/31009952/225748805-7ebe1139-19cb-4c9a-8d70-569a68c74eb7.png">

*Editor*
<img width="245" alt="editor" src="https://user-images.githubusercontent.com/31009952/225748831-47140127-8da2-46f1-94da-6743c7927d8e.png">
