### ISSUE TITLE
Request: Make Rmd publishing experience match other publishing types

### ISSUE THREAD

**Issue by mbaynton** [rstudio/rstudio#12287]
The experience when publishing your first Rmd in a project seems to differ from all other content types, in a way that's particularly noticeable for the cloud-to-cloud publishing experience, which pre-configures an `rsconnect` account to publish with your own rstudio.cloud user.

When you click ![Screenshot from 2022-11-03 15-20-27](https://user-images.githubusercontent.com/3026002/199825920-6f59ef3c-4860-4827-a968-c8993b1752af.png) on other content types, e.g. Shiny, and a publishing account supporting that content type has already been configured with `rsconnect`, you are taken directly to this dialog:
![Screenshot from 2022-11-03 15-29-34](https://user-images.githubusercontent.com/3026002/199827654-b920529a-5dee-4765-8496-a397099c8692.png)

When you click ![Screenshot from 2022-11-03 15-20-27](https://user-images.githubusercontent.com/3026002/199825920-6f59ef3c-4860-4827-a968-c8993b1752af.png) on an Rmd, you are taken to this dialog:
![Screenshot from 2022-11-03 15-31-35](https://user-images.githubusercontent.com/3026002/199828019-8098b59f-d91b-4d0b-9ab1-6e94bce785dd.png)

The request is to retain the same behavior across all types of content including Rmds, keeping the cloud-to-cloud publishing experience streamlined.

We notice that in the case of Rmds, there are a few service types that the user could choose (RPubs or Connect). But a choice of services has been managed with Shiny apps for a long time by choosing Other Destination from the publish menu:
![Screenshot from 2022-11-03 15-47-34](https://user-images.githubusercontent.com/3026002/199830892-9e01782c-82ec-4f75-9a21-0a61af1490ea.png)
So we'd propose keeping RPubs accessible as an alternate destination in the same way.

cc @kippandrew

**Comment by kippandrew** [comment]
@ronblum @mikebessuille @jgutman I was wondering if there was additional context about why the IDE behaves this way. It seems possible that the choice of always prompting to connect an account when publishing an RMD was intentional.

**Comment by mikebessuille** [comment]
I don't know the reason for that decision but @kevinushey would probably know?

**Comment by jacodevries** [comment]
@mikebessuille @kippandrew  I noted similar behaviour using RStudio 2022.10.0 on a Macbook, publishing to RStudio Connect (2022.12.0), as well as the most recent version of RStudio Connect (2023.03.0). It seems to be related to the issue @mbaynton raised.

After publishing to Connect the first time, the IDE will create a new .dcf file every time the publish button is pressed and all the settings has to be configured again.  A new bundle is published to Connect every time the publish button is pressed.

To solve this problem, you need to quit the IDE completely and reopen the R project.  The IDE will then load the settings from the .dcf file correctly and will take you to the "Publish to Server " screen directly.  The functionality to publish to the same destination on Connect is then also available, i.e. publishing to the destinations as per the existing .dcf files.   It therefore seems as if the IDE does not load the .dcf settings correctly after publishing the document the first time.

**Comment by jthomasmock** [comment]
Looks like this issue wasn't triaged into a milestone - @kippandrew do you have any thoughts on priority?

**Comment by Alex-Chisholm** [comment]
The issue is also true for Quarto docs and the inconsistency with Shiny/Plumber is more annoying than either approach, imo. 

But since (1) users don't jump between different content types as frequently as we do in testing,  (2) the act of publishing is at the end of a larger workflow, and (3) republishing defaults to the original destination (e.g., Posit Cloud), I don't think the current behavior adds a lot of pain and wouldn't consider it a high priority fix.

@kippandrew or @mbaynton, do you disagree?

**Comment by kippandrew** [comment]
I agree this is more of an annoyance because of the inconsistency. I would consider this medium priority issue, perhaps something that can be addressed next year.

**Comment by jacodevries** [comment]
Alex, Andrew. 

Please refer to my comment, above.  The behaviour which I observe can be classified as a nuisance, once you realise that you need to close the RStudio project and open it up for the publishing to Connect to work.

However, if you do not know about this workaround, it is an extremely frustrating bug which means that the one-click publishing does not work as expected.  It detracts a lot from the value of the products which Posit builds - this in my mind is one of the key selling point of Connect.

Please consider the priority of this task in this context.

Jaco


> @mikebessuille @kippandrew I noted similar behaviour using RStudio 2022.10.0 on a Macbook, publishing to RStudio Connect (2022.12.0), as well as the most recent version of RStudio Connect (2023.03.0). It seems to be related to the issue @mbaynton raised.
> 
> After publishing to Connect the first time, the IDE will create a new .dcf file every time the publish button is pressed and all the settings has to be configured again. A new bundle is published to Connect every time the publish button is pressed.
> 
> To solve this problem, you need to quit the IDE completely and reopen the R project. The IDE will then load the settings from the .dcf file correctly and will take you to the "Publish to Server " screen directly. The functionality to publish to the same destination on Connect is then also available, i.e. publishing to the destinations as per the existing .dcf files. It therefore seems as if the IDE does not load the .dcf settings correctly after publishing the document the first time.

**Comment by ronblum** [comment]
@jacodevries Can you open a new issue for this? To separate the two problems.
