### ISSUE TITLE
Nice new fancy Posit website, with only one issue: it's inconvenient download RStudio

### ISSUE THREAD

**Issue by dipterix** [rstudio/rstudio#12284]
@hadley 

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/8163576/199761416-e8a0d09d-2acc-4c4c-a5f5-4cea3b005519.png">

I have to scroll multiple times to get to the download list, and it's so inconvenient that I cannot see the full list within one screen.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/8163576/199762689-cd39c7cc-6232-45b9-bcd2-eea1170fe8c2.png">

Also I'm using OSX, but the website defaults me to downloading Windows version.

Feel free to close this issue.

**Comment by hadley** [comment]
Thanks for the report; I've moved this to our internal web tracker.
