### ISSUE TITLE
dialogViewer: allow dimensions to go right up until the perimeter of the IDE instead of forcing ~150px margin

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#12282]
Originally posted in https://github.com/rstudio/shiny/issues/3722

When building shiny gadgets, it's common to use `dialogViewer()` to run them inside the IDE. However, one frustrating feature of `dialogViewer()` is that it seems to not allow the viewer to come within ~70-80 pixels of the IDE (from my own testing).

For example, the following code

```r
shiny::runGadget(shiny::shinyApp("test", function(input, output) {}), viewer = shiny::dialogViewer("test", 3000, 3000))
```

Results in this:

![image](https://user-images.githubusercontent.com/952340/199340875-9d00d8d6-c616-4733-b91d-af6ed7ae5c61.png)

In a desktop IDE it's not too bad, but often when running a gadget inside an RStudio Server (inside a browser), those extra pixels make a difference. I often end up making a gadget run in a separate browser window instead of in the IDE just because of this. If `dialogViewer()` allowed me to get right up until the edges of the IDE, it would be much more useable.

**Comment by ronblum** [comment]
@daattali Thank you for raising this! I'm trying to understand the issue: Do you mean that in RStudio Desktop, the window is larger and starts closer to the top? Here's a short movie comparing the results in RStudio Desktop vs. Server.

https://user-images.githubusercontent.com/31009952/199668682-2ec80491-768d-4fd4-b25f-479f123146ff.mov

**Comment by daattali** [comment]
The issue is inherently the same regardless of the environment. It just presents itself more when you're in a browser because the browser itself takes up additional space. It would be nice if the dialogViewer could till the edges, so that in a Desktop IDE it can essentially take up the entire screen, and in a browser it would take up the entire browser usable area.

**Comment by domino-ross-sharp** [comment]
I'd also like to have the ability to change dimensions of my gadgets.

**Comment by daattali** [comment]
bad bot

**Comment by daattali** [comment]
ditto
