### ISSUE TITLE
Session Aborted after remove dataframe object when it is being openned

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#12296]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2022.12.0 Build 313
    OS Version      :  Windows 11
    R Version       :  4.2.1

### Steps to reproduce the problem
View a dataframe, and type in the console to remove it

### Describe the problem in detail
<img width="774" alt="image" src="https://user-images.githubusercontent.com/63569637/200122864-9a402ac0-0685-4ed1-b8a2-f962bb52361b.png">

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I was able to reproduce. Here's a reproducible example:

```
.data <- data.frame(x = 42)
View(.data)
Sys.sleep(1)
rm(".data")
```

**Comment by kevinushey** [comment]
Looks like we need to handle null pointers here:

https://github.com/rstudio/rstudio/blob/d152bb422d6d2af9edfaee66c42b4e9630caaaf7/src/cpp/session/modules/data/DataViewer.cpp#L979

@romainfrancois would you be willing to take a look?

**Comment by romainfrancois** [comment]
Verified on RStudio 2022.12.0-preview+318 "Elsbeth Geranium" Preview (dc4d4161ef601e2ee75b3d7e925524ea7d9219f1, 2022-11-08) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0-preview+318 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
