### ISSUE TITLE
glue knitr engine fails with yaml style chunk options

### ISSUE THREAD

**Issue by richardjtelford** [rstudio/rstudio#12297]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.7.1.554
    OS Version      :  ubuntu 18.04
    R Version       :  4.2.1

### Steps to reproduce the problem

Here is a reproducible example

````
---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(glue)
```
This works
```{glue, echo = "fenced"}
1 + 1 = {1 + 1}
```

Renders but fails when run in Rstudio

```{glue}
#| echo: fenced
1 + 1  = {1 + 1}
```

````

### Describe the problem in detail

glue knitr engine (and possibly other user defined knitr engines) work with either the chunk options in braces or in yaml when the document is rendered
When the glue chunk is run in RStudio, it works when the options are in braces, but fails when the chunk options are in yaml with error

> Error: All unnamed arguments must be length 1

The  traceback is

```
6: stop("All unnamed arguments must be length 1", call. = FALSE)
5: glue_data(.x = NULL, ..., .sep = .sep, .envir = .envir, .open = .open, 
       .close = .close, .na = .na, .null = .null, .comment = .comment, 
       .literal = .literal, .transformer = .transformer, .trim = .trim)
4: (function (..., .sep = "", .envir = parent.frame(), .open = "{", 
       .close = "}", .na = "NA", .null = character(), .comment = "#", 
       .literal = FALSE, .transformer = identity_transformer, .trim = TRUE) 
   {
       glue_data(.x = NULL, ..., .sep = .sep, .envir = .envir, .open = .open, 
           .close = .close, .na = .na, .null = .null, .comment = .comment, 
           .literal = .literal, .transformer = .transformer, .trim = .trim)
   })(c("#| echo: fenced", "1 + 1  = {1 + 1}"), .envir = <environment>)
3: do.call(glue, c(list(options$code), glue_options))
2: knitrEngine(mergedOptions)
1: .rs.runUserDefinedEngine("glue", "#| echo: fenced\n1 + 1  = {1 + 1}", 
       list(echo = "fenced", engine = "glue", label = "example-countSum-autoplot.possible_n-26", 
           error = FALSE))
```

### Describe the behavior you expected

The chunk should run in Rstudio with either style of chunk options

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Seems to work for me in the latest daily builds of RStudio: https://dailies.rstudio.com
