### ISSUE TITLE
When opening two identical files - show the first unique path to the file.

### ISSUE THREAD

**Issue by avraam-inside** [rstudio/rstudio#12302]
Good afternoon! There are very relevant issues: my project code is decomposed into modules, and it's fundamental for me to call the first entrypoint file as `01_main.R` without (!!!) any another variants.
![image](https://user-images.githubusercontent.com/52919010/200315209-c9c5f592-46e0-4215-97b3-a67b57c55004.png)

The problem is that it becomes difficult to navigate in tabs when all files are named the same.

You need to show the first unique name of the root folder for ease of orientation in this.

An example of how this is already done in VSCode:
![image](https://user-images.githubusercontent.com/52919010/200315156-967f9415-f198-46e0-8b02-35fa57ce96b8.png)

It is needed to do about the same in RStudio.

**Comment by ronblum** [comment]
@avraam-inside Thank you for raising this! If you hover over the tab, the path to the file should appear. Does this address what you're looking for?

**Comment by avraam-inside** [comment]
@ronblum Yes, it will appear. But this is not enough - it is inconvenient. Such information should be displayed in a good way without hover, as in VSCode

**Comment by ReinoWCC** [comment]
I can confirm that this happens to me quite frequently. I found it to be related to the popping out of the script pane on two monitors. There are two things this might be related to.  Oftentimes, if I source from the popped-out script window it doesn't recognize the popped-out script in the debugger. That is, if I debugonce a function sourced from a popped-out script, it will debug in the main window instead as if it was anonymous.  Secondly, if I start Rstudio with the option remembering open scripts checked, it will open the popped-out script as expected, however, sometimes if I open the same script locally while the other is still popped out it will duplicate in the main window. Then, if I pop-in the external script, you will get two scripts in the main window. There is no telling which one actually edits the real file at this point.  Therefore, opening another instance popped-out script does not close the popped-out script.

Something that might be related and is reliably reproducible. If you have the remember open scripts option on and you pop out two scripts onto another window, and then close Rstudio. When you open Rstudio it will reopen one of the two scripts (the first one popped out), the second one will remain a completely white unclosable window that never resolves. To fix this you must pop back in the resolved script pane, and turn off and on Rstudio again. 

I have a myriad of other things like this I have noticed. I think it mostly relates to popping out windows and using two monitors to code.

**Comment by avraam-inside** [comment]
I didn't understand longrid at all from the author above.

It's simple - I have five `01_main`-files. It's very uncomfortable to look at them. Pointing the mouse at them 100500 times is also inconvenient. This is an IDE issue - cos there is an industry standard: to show the file name + the first unique name of the root folder if n files with the same name are open.

I would really like such an implementation in RStudio.

**Comment by avraam-inside** [comment]
It's been six months. The FUNCTIONALITY IS VERY NECESSARY. Will it be done then in the end?
