### ISSUE TITLE
Completion help for type `COLUMN`

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12308]
Some completion type get extra help, i.e. 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/2625526/200587640-0108527e-d382-46d2-a8b7-81484b995c19.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/2625526/200587816-2f352c24-dc02-4a05-9f4a-e63f2dd74302.png">

it would be useful to have some hint for `COLUMN` type as well.

**Comment by romainfrancois** [comment]
QA note: 

<img width="556" alt="image" src="https://user-images.githubusercontent.com/2625526/212686724-8ba9b4a6-5e92-41bd-a809-ebb3c06627ba.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/2625526/212686762-e43b5afc-f7bc-4c59-9e9e-689d52e5e841.png">

**Comment by kevinushey** [comment]
Something we should consider (as a separate issue?) is whether we could adjust the styling (e.g. background color) on the Help popup, so that rendered tables look more "natural" as part of the whole presentation.

**Comment by jonvanausdeln** [comment]
Verified with 2023.03.0-daily+301
Desktop - Windows11
Server - Ubuntu22

New help for column types in autocomplete appears as expected.
