### ISSUE TITLE
render qmd or rmd produces cannot read file error for users without admin rights

### ISSUE THREAD

**Issue by Lawrence-Sproul** [rstudio/rstudio#12313]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : windows 10 enterprise 20H2 
    R Version       : 4.2.2

### Steps to reproduce the problem
log in as restricted user without ability to elevate permissions
start Rstudio
Create new Quarto project  
click Render on the default/generated qmd file

OR add a qmd to an existing project and click render

when a rmd document displays the Render button, it also produces the error, but knit still works for rmd documents.

### Describe the problem in detail
produces the following error messages 
I suspect that either quarto is trying to create a temporary file in a restricted folder (e.g. system temp vs user-space temp) or something, perhaps the visual viewer, is locking the file (less likely) 
For QMD:
Error in readLines(con, warn = FALSE) : cannot open the connection
Calls: .main -> execute -> <Anonymous> -> read_utf8 -> readLines
In addition: Warning message:
In readLines(con, warn = FALSE) :
  cannot open file 'q_Recall_CCPs.qmd': Permission denied
Execution halted

For Rmd:
Error in readLines(con, warn = FALSE) : cannot open the connection
Calls: .main -> execute -> <Anonymous> -> read_utf8 -> readLines
In addition: Warning message:
In readLines(con, warn = FALSE) :
  cannot open file 'RMD_Test.rmd': Permission denied
Execution halted

### Describe the behavior you expected
The document should render without error

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Lawrence-Sproul Thank you for raising this! Do you know by chance if this worked in previous versions of RStudio Desktop?
