### ISSUE TITLE
FR: Allow to include/exclude the Roxygen comments in "Find in files"

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#12319]
Currently, the "Find in Files" provides a way to search and/or replace only in package source. 

But, one may wish to do these operations often only in the source code and exclude the Roxygen comments, or vice versa. It'd be great if the IDE can provide an easy way to do this. For example, by providing an additional option called `Exclude Roxygen comments` here?

![Screenshot 2022-11-10 at 17 26 40](https://user-images.githubusercontent.com/11330453/201153305-3fa2ef32-9720-4ed8-87fe-e5381f8b78ba.png)

**Comment by ronblum** [comment]
@IndrajeetPatil Thank you for the suggestion! We'll review it as we continue to develop RStudio.

**Comment by IndrajeetPatil** [comment]
@ronblum This was closed due to inactivity, but I still think this will be a valuable addition to the IDE.

**Comment by IndrajeetPatil** [comment]
@ronblum Is it possible to reconsider this FR? Thanks.
