### ISSUE TITLE
Detection of yaml-cpp library is flawed

### ISSUE THREAD

**Issue by hobbes1069** [rstudio/rstudio#12317]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2-576
    OS Version      : Fedora Rawhide
    R Version       : N/A

### Steps to reproduce the problem
Current detection of yaml-cpp appears to be flawed. 

### Describe the problem in detail
In the following CMake section the test is essentially a string comparison:
```
if(NOT EXISTS "${YAML_CPP_INCLUDE_DIR}")
   message(FATAL_ERROR "yaml-cpp not found (re-run dependencies script to install)")
endif()
```

Since yaml-cpp is installed to the system location `/usr/include`, `YAML_CPP_INCLUDE_DIR` is set to "" and fails the test even though it is set.

With yaml-cpp 0.7.0 on Fedora Rawhide (update in progress):
```
# cat yaml-cpp-config.cmake
# - Config file for the yaml-cpp package
# It defines the following variables
#  YAML_CPP_INCLUDE_DIR - include directory
#  YAML_CPP_LIBRARIES    - libraries to link against

# Compute paths
get_filename_component(YAML_CPP_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(YAML_CPP_INCLUDE_DIR "")

# Our library dependencies (contains definitions for IMPORTED targets)
include("${YAML_CPP_CMAKE_DIR}/yaml-cpp-targets.cmake")

# These are IMPORTED targets created by yaml-cpp-targets.cmake
set(YAML_CPP_LIBRARIES "")
```

### Describe the behavior you expected
A better test would be:
```
if(NOT YAML_CPP_INCLUDE_DIR)
   message(FATAL_ERROR "yaml-cpp not found (re-run dependencies script to install)")
endif()
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [N/A] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [N/A] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hobbes1069** [comment]
Well that didn't quite work either... I think it should be changed to:
```
if(NOT yaml-cpp_FOUND)
...
```

That should work with both module and config CMake methods.

As for the include directory, perhaps it should just be appended if defined and otherwise ignored.

**Comment by hobbes1069** [comment]
This probably needs some tweaking but here's my version of the patch that works:
```
$ cat rstudio-yaml-cpp.patch
Index: rstudio-2022.07.2-576/src/cpp/CMakeLists.txt
===================================================================
--- rstudio-2022.07.2-576.orig/src/cpp/CMakeLists.txt
+++ rstudio-2022.07.2-576/src/cpp/CMakeLists.txt
@@ -218,11 +218,14 @@ else()
    find_package(yaml-cpp REQUIRED)
 endif()
 
-if(NOT EXISTS "${YAML_CPP_INCLUDE_DIR}")
-   message(FATAL_ERROR "yaml-cpp not found (re-run dependencies script to install)")
+if(yaml-cpp_FOUND AND NOT YAML_CPP_LIBRARIES)
+   # Assume yaml was found by config instead by module.
+   set(YAML_CPP_LIBRARIES yaml-cpp)
 endif()
 
-include_directories(SYSTEM "${YAML_CPP_INCLUDE_DIR}")
+if(YAML_CPP_INCLUDE_DIR)
+	include_directories(SYSTEM "${YAML_CPP_INCLUDE_DIR}")
+endif()
 
 # determine whether we should statically link boost. we always do this
 # unless we are building a non-packaged build on linux (in which case
```

**Comment by ronblum** [comment]
@hobbes1069 Thank you for raising the issue! I'll mark it for further review.

**Comment by mikebessuille** [comment]
Is this just a build-time warning ?  Is there an end-user problem that arises from this?

**Comment by hobbes1069** [comment]
Because the CMAKE variables aren't set, it actually errors out.

**Comment by kevinushey** [comment]
> Since yaml-cpp is installed to the system location /usr/include, YAML_CPP_INCLUDE_DIR is set to "" and fails the test even though it is set.

Shouldn't Fedora be defining `YAML_CPP_INCLUDE_DIR = /usr/include` then?

https://github.com/jbeder/yaml-cpp/blob/master/yaml-cpp-config.cmake.in#L1-L11

PRs are otherwise welcome.

**Comment by hobbes1069** [comment]
My guess it the cmake target in yaml-cpp 0.7.0 is filtering it out since it's part of the standard search path.

**Comment by vinisalazar** [comment]
@mikebessuille I've been experiencing this exact problem as an end-user. I'm attempting to build RStudio Server from source and running into this (I'm pretty sure yaml-cpp is installed in my environment).

**Comment by kevinushey** [comment]
@vinisalazar PRs are welcome.

**Comment by hobbes1069** [comment]
<sigh> I'm working 7 days a week right now so can't promise to submit a formal PR but https://github.com/rstudio/rstudio/issues/12317#issuecomment-1310646292 is pretty straightforward to apply. Presumably there is some CI github hooks to make sure it doesn't break anything?

@vinisalazar can you try my patch and see if it helps?

**Comment by kevinushey** [comment]
Let me know if https://github.com/rstudio/rstudio/commit/17a9562b352f9a726188f570dec55e683a663c91 helps.

**Comment by hobbes1069** [comment]
@alanagarunov I think your problem is 0.5.1 does not provide any CMake configuration files, just pkgconf files. The rstudio CMake configuration could add a fallback to try using pkgconf, but you may be better off modifying the spec file to force detection. 

After the `find_package` check, something like:
```
if(yaml-cpp_NOTFOUND)
    find_package(PkgConfig)
    pkg_check_modules(yaml-cpp REQUIRED)
endif()
<assign results to the right variables>
```

Unfortunately I don't have time to explore or test further.

**Comment by gjhltn** [comment]
I'm struggling with this too. I'm on OSX and following this procedure https://github.com/rstudio/rstudio/wiki/M1-Mac-Dev-Machine-Setup 

I'd be hugely grateful for help because it's a total dead end dealbreaker of a blocker. Many MANY thanks!


```
user@computer build-server % cmake ../cpp -DRSTUDIO_TARGET=Server -GNinja
CMake Deprecation Warning at CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
-- Building RStudio 2023.09.999-dev+999
-- Machine architecture: arm64
-- CMake build type: Debug
-- Desktop builds not currently supported on arm64; disabling RSTUDIO_DESKTOP
-- Using RStudio tools root: /opt/homebrew/include
-- Configured to build with libpam features
-- Mac OS X deployment target: 10.12
-- Mac OS X version: 13.5.1
CMake Error at CMakeLists.txt:241 (message):
  yaml-cpp not found (re-run dependencies script to install)
  ```

**Comment by JamesH65** [comment]
Same on Raspberry Pi 5, latest PiOS, main branch of rstudio as of 29/1/2024. Had a play with the CMake files to no avail, but don't have the time to investigate further. YAML_CPP_INCLUDE_DIR does not appear to be set after the find_package call. YAML_CPP_LIBRARIES is set to yaml-cpp

**Comment by alanagarunov** [comment]
> @alanagarunov I think your problem is 0.5.1 does not provide any CMake configuration files, just pkgconf files. The rstudio CMake configuration could add a fallback to try using pkgconf, but you may be better off modifying the spec file to force detection.
> 
> After the `find_package` check, something like:
> 
> ```
> if(yaml-cpp_NOTFOUND)
>     find_package(PkgConfig)
>     pkg_check_modules(yaml-cpp REQUIRED)
> endif()
> <assign results to the right variables>
> ```
> 
> Unfortunately I don't have time to explore or test further.

Pretty late but thank you for the reply, this helped me get closer to a build. I added the following to my spec file:
```
sed -i "s/if(NOT EXISTS \"\${YAML_CPP_INCLUDE_DIR}\")/if(yaml-cpp_FOUND AND NOT YAML_CPP_LIBRARIES)\n   set(YAML_CPP_LIBRARIES yaml-cpp)\n   message(\"I found yaml-cpp but not libraries\")\nendif()\nif(NOT RSTUDIO_USE_SYSTEM_YAML_CPP AND NOT EXISTS \"\${YAML_CPP_INCLUDE_DIR}\")/" src/cpp/CMakeLists.txt
sed -i "s/include_directories(SYSTEM \"\${YAML_CPP_INCLUDE_DIR}\")/if(YAML_CPP_INCLUDE_DIR)\n   include_directories(SYSTEM \"\${YAML_CPP_INCLUDE_DIR}\")\nendif()/" src/cpp/CMakeLists.txt
```

but I had multiple similar dependecy conflicts after resolving yaml-cpp, so in the end I deicded to use a built release instead.
