### ISSUE TITLE
Update intro message when installing RStudio on Linux

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12315]
### System details

    RStudio Edition : Desktop and Server 
    RStudio Version : 2022.12.0-preview+321
    OS Version      : Linux
    R Version       : N/A

### Steps to reproduce the problem

Install RStudio Desktop or RStudio Server.

### Describe the problem in detail

The message that appears at the start is:

> RStudio is a set of integrated tools designed to help you be more productive with R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, and workspace management.

### Describe the behavior you expected

The message is a little out of date. Update, possibly using the language in the upcoming user guide:

>RStudio is a set of integrated tools designed to support multiple languages, including both R and Python. It includes a console, syntax-highlighting editor that supports direct code execution, and a variety of robust tools for plotting, viewing history, debugging and managing your workspace.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
I verified the description on 2023.03.0-daily+284
* Desktop - Ubuntu22, Ubuntu 20
* OS server - Ubuntu22, Ubuntu18
*
@ronblum can you please check a RHEL edition as well? If it's good, this can be closed

**Comment by ronblum** [comment]
The RHEL rpms don't have this message, so verification was easy. (Though see https://github.com/rstudio/rstudio-pro/issues/4300.)
