### ISSUE TITLE
Debug-step takes the browser to the middle of a srcref range instead of the beginning

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#12325]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.1 Build 554
    OS Version      :   Ubuntu 20.04
    R Version       :  4.2.2

### Steps to reproduce the problem
```r
library(data.table)
debug(data.table::`[.data.table`)
dt <- data.table(a=10,b=20)
dt[1,1]
```
-> The editor skips to the middle of the wanted function

### Describe the problem in detail
The code snippet above is just an example of entering a large range while debugging - `[.data.table` is a ~1800 line function, but any with more lines that fit the screen will do. Even more, any statement that spans many lines (`if`, `lapply` etc.) is subject to the same issue: upon entry, the browser scrolls to the middle of the range, forcing a (sometimes lengthy) scroll up to the real location.

### Describe the behavior you expected
It would be much more convenient if the code editor scrolled to the *beginning* of the srcref range.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by OfekShilon** [comment]
@kevinushey  I installed the nightly build:
![image](https://user-images.githubusercontent.com/73080/202000233-73ef6e32-cf0b-472d-ab80-b00ad3a7fd94.png)

and am seeing the same results: https://share.vidyard.com/watch/dmYTZcxz5Q3283UBjkXY4j?

This capture is from rstudio running on WSL 2 over windows 11, but I see the same on windows and direct ubuntu.
This copy of data.table is one built by me, but it certainly isn't needed:  https://share.vidyard.com/watch/8SJZXm6tNNaoaUByZEspJK?

**Comment by kevinushey** [comment]
Thanks -- the video recording makes the issue more clear.

I suspect the issue lies around here, where we try to compute an appropriate position to place the editor when viewing some debugged content:

https://github.com/rstudio/rstudio/blob/c65a4fc6159a08bc95ae4b16d47452da7a6c5af5/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java#L859-L946
