### ISSUE TITLE
Incorrect warning in the margin of saved script file when indexing 2nd+ dimension with native pipe

### ISSUE THREAD

**Issue by patc3** [rstudio/rstudio#12323]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.1 Build 554
    OS Version      : Windows 10
    R Version       : 4.2.1

### Steps to reproduce the problem
```
df <- data.frame(x=rnorm(10))
df |> 
  (`[`)(,1)
```

### Describe the problem in detail
The code-checking in the margin of RStudio in a saved script file incorrectly indicates "missing argument to function call" when using the pipe and the indexing (bracket) operator to index the second dimension of an object

![image](https://user-images.githubusercontent.com/41131893/201357744-06d2ca60-ef41-4219-88d2-3ba79e4856d8.png)

### Describe the behavior you expected
No warning in the margin: the code runs fine

![image](https://user-images.githubusercontent.com/41131893/201358328-ab155a70-b76c-474b-b532-be1065d5f0b1.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
FWIW it's a warning, not an error -- it's pointing out a code that could potentially be incorrect (but might be wrong).

Either way, I'd recommend using something more readable, e.g.

```
df |> .subset2(1)
df |> dplyr::pull(1)
```
