### ISSUE TITLE
Autocompletion isn't right when naming arguments that already exist

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#12326]
Fairly new version of RStudio daily:

RStudio 2022.12.0-preview+299 "Elsbeth Geranium" Preview (24e7bc9fedf84de448c6476fcb6844f1da2c034f, 2022-11-01) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0-preview+299 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

If you have a function that already has unnamed arguments in it and you are trying to use tab to actually name the arguments, then it seems like the autocompletion doesn't fill right for the 2nd (and probably more) arguments

https://user-images.githubusercontent.com/19150088/201533532-192dd83b-94fc-4e14-9203-57f393db5b6c.mov

If you uncomment the first line and hit tab then all 3 arguments will pop up for autocompletion, but if you uncomment the second line you get the behavior seen in the video

```r
check_fn <- function(endpoints,
                     size,
                     by_arg,
                     call = caller_env()) {
  #stop_fn()
  #stop_fn(endpoints_size = endpoints_size, size = size, by_arg = by_arg)
}

stop_fn <- function(endpoints_size, size, by_arg) {
  rlang::abort(
    endpoints_size = endpoints_size,
    size = size,
    by_arg = by_arg
  )
}

```

CC @romainfrancois

**Comment by romainfrancois** [comment]
Seems to be an issue with `.rs.matchCall()` not correctly ruling out unnamed arguments. 

https://github.com/rstudio/rstudio/blob/04a18d1c438a301d9579c800259b8ffadef2dcc6/src/cpp/session/modules/SessionRCompletions.R#L619-L636

```r
> stop_fn <- function(endpoints_size, size, by_arg) {
+   rlang::abort(
+     endpoints_size = endpoints_size,
+     size = size,
+     by_arg = by_arg
+   )
+ }
> 
> call <- quote(stop_fn(endpoints_size = endpoints_size, by_arg))
> .rs.matchCall(stop_fn, call)
stop_fn(endpoints_size = endpoints_size, size = by_arg)
```

**Comment by ronblum** [comment]
@DavisVaughan Would you mind checking in the latest Cherry Blossom dailies if this is working correctly? I tried, but I'm getting slightly different behavior when trying to reproduce it in Elsbeth Geranium, so I can't properly test.

**Comment by DavisVaughan** [comment]
<img width="830" alt="Screen Shot 2023-02-10 at 2 05 32 PM" src="https://user-images.githubusercontent.com/19150088/218176560-0fae7ccc-c039-4643-b8d9-0ec6a2529ffe.png">

Looks to be fixed? I did happen to notice today that it seems like it was working better (i got back on the dailies this week after a critical bug fix was merged in)

**Comment by ronblum** [comment]
@DavisVaughan Thanks! I don't know what I'm doing differently, but I count on your expertise. 😄
