### ISSUE TITLE
allow full-screen in RPubs documents

### ISSUE THREAD

**Issue by helgasoft** [rstudio/rstudio#12334]
## Problem
It could be for security reasons, but full-screen activation does not work from inside RPubs' _&lt;iframe&gt;_.   
Attempt generates a _Uncaught (in promise) TypeError: fullscreen error_
## Example 
The published Rmd document contains a chart in a _&lt;canvas&gt;_. The chart features a toolbar with a fullscreen button.
**A.** for a [regular Rmd](https://rpubs.com/echarty/paris-art) with _iframe_, fullscreen does **not** work
**B.** for the [same Rmd](https://rstudio-pubs-static.s3.amazonaws.com/970673_daa323d3622d42e7a0d22d7e72d7d220.html) without _iframe_,  fullscreen works
There is a very inconvenient workaround on how to get from A to B described in the example.

## Solution
According to [this document](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/fullscreen), adding attributes _allow='fullscreen'_ or _allowFullscreen=true_ to the iframe may fix it.

**Comment by jcheng5** [comment]
Hi @helgasoft, thanks for the very clear report. I will work on getting this change into RPubs.

**Comment by helgasoft** [comment]
@jcheng5 - any ETA ?

**Comment by jcheng5** [comment]
Sorry for the long delay, that change is deployed to RPubs now. Thanks again for reporting this!
