### ISSUE TITLE
Add some kind of check for websocket capabilities to the IDE

### ISSUE THREAD

**Issue by pyltime** [rstudio/rstudio#12335]
The Posit support team runs into a lot of issues with users not being able to use websockets due to proxy settings, etc - enough that we've actually added docs about it! (see: https://docs.posit.co/ide/server-pro/access_and_security/running_with_a_proxy.html#forwarding-websockets )
As they're used for Shiny apps, project sharing functionality, and the Terminal, the inability to open a websocket connection can really cause issues for users.

To help with this, I suggest that we add some kind of check in the IDE that checks whether it's possible to create a websocket connection, then relays that information to the user in the UI so they can investigate it. For instance, a check when a user first tries to create or open a Shiny application might save the user time later when they try to test their Shiny application after writing their code and discover that it can't be opened.

**Comment by rmccombie** [comment]
Example ticket: 79516
