### ISSUE TITLE
Dedicated URL for preview releases?

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#12346]
Previously one could download RStudio preview builds from https://www.rstudio.com/products/rstudio/download/preview/. 

I know there are the dailies but: will there be a new dedicated URL for preview builds or will it these appear under https://posit.co/download/rstudio-desktop/?

**Comment by jmcphers** [comment]
Yes, there will eventually be a new dedicated URL -- it's just one of the features that hasn't been ported to the new website yet!

**Comment by ronblum** [comment]
I'm reopening this so that we can use this for the new URL, in case anyone else misses it.
