### ISSUE TITLE
Highlighting for `Rmd`/`qmd` changes after `verbatim` engine code chunk

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#12342]
### Describe the problem in detail

Using the `verbatim` engine in `.Rmd` or `.qmd` files changes highlighting for the rest of the document (cc @cderv). 

In the example below, note the highlighting for all content that exists after the verbatim chunk. Also note that the document outline no longer contains Heading 3.

<img width="885" alt="Screenshot 2022-11-16 at 10 56 00" src="https://user-images.githubusercontent.com/11330453/202149901-557d852e-eb85-4644-80d0-45091c3776b7.png">

### Steps to reproduce the problem

Create a new Rmd/qmd document, create a verbatim chunk, and write anything below this chunk.

### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.2 Build 576
    OS Version      :  Mac OS X 13_0_0
    R Version       :  4.2.2

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@IndrajeetPatil Thank you for raising this! I can reproduce it in RStudio Desktop 2022.12.0-preview+328 on MacOS 13, using both the code provided, as well as [examples from the *R Markdown Cookbook*](https://bookdown.org/yihui/rmarkdown-cookbook/verbatim-code-chunks.html).


Code from above (with a slight addition):
`````
---
output: html_documen
---

## Heading-2

````{verbatim}
Rmd test content goes here

Code chunk looks like the following:
  
```{r}
1 + 1
```

````

## Heading 2 again

This is all content that comes afterwards.

### Heading 3
Doesn't matter *what# the content is, `r 1 + 1`, highlighting does'nt change.
`````

**Comment by cderv** [comment]
I think this issue is a duplicate of several already opened 

- https://github.com/rstudio/rstudio/issues/10079
- https://github.com/rstudio/rstudio/issues/12161

It is more about nested chunk that just verbatim engine.

**Comment by IndrajeetPatil** [comment]
Thanks, @cderv. Definitely duplicates of those two issues. So closing this one in favour of them.
