### ISSUE TITLE
Quarto file types not showing up in New File dropdown for Linux (CentOS7)

### ISSUE THREAD

**Issue by katgit** [rstudio/rstudio#12358]
### System details

    RStudio Edition : 
    RStudio Version : 2022.07.2 Build 576
    OS Version      : CentOS7
    R Version       : 4.2.1

### Steps to reproduce the problem
There is no Quarto option for New Document and there is no Quarto tab in Global Options -> Markdown

### Describe the problem in detail
Hi, I installed the newest RStudio version (2022.07.2 ) on my local Windows machine and also on a Linux (CentOS7) server.
The Windows RStudio Desktop has "Quatro Option" and "Quatro Presentation" options when I click File -> New Document menu.
However the same version of RStudio installed on the Linux CentOS7 server does not have those option.

I tried to go to Tools -> "Global Options" -> Markdown, but I do not see an option to enable Quatro, neither do I see a "Quatro" tab there. How can I enable it (using builtin Quarto plugin) without installing a separate Quarto library)?

### Describe the behavior you expected

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@katgit Thank you for raising this! Quarto wasn't available for CentOS/RHEL 7 at the time of the 2022.07 release. However, it will be bundled in [the upcoming 2022.12.0 release, which is currently in preview](https://dailies.rstudio.com/).
