### ISSUE TITLE
Run all stops when using chunk references together chunk output type inline

### ISSUE THREAD

**Issue by thothal** [rstudio/rstudio#12355]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  Win 10
    R Version       :  4.2.2

### Steps to reproduce the problem

Consider the following reprex:

``````
---
output: html_document
editor_options: 
  chunk_output_type: inline
---


```{r a, include = FALSE}
a <- 1 + 1
```

Show chunk a after this one (but execute it earlier to use for instance the variable `a` 
inline `r a`).

```{r b}
<<a>>
a + 1
```

```{r c}
a + 1
```
``````

### Describe the problem in detail

If you press `Run All Chunks Above`, R trips over the first chunk and an error is produced in the R console saying:

> `Error: unexpected input in "<<"`

If you change the output to `console` all works as expected.

The following screenshot illustrates the problem.

![Inline_Console](https://user-images.githubusercontent.com/30824940/202707301-39740bbc-b336-47c7-8ae8-cc2ceb3f65eb.gif)

### Describe the behavior you expected

As the issue mentioned in #11995 still prevents me from using `Run All Chunks Above` in the presence of a  `CSS` chunk, I thought by changing `console` to `inline` would at least allow me to use `Run All Chunks Above` to create the necessary objects in my global environment. But as I am using backreferences, I could not use this workaround either.

Eventually, I would like to see `Run All Chunks Above` working regardless of the presence of  `CSS` chunks and irrespective of the output type.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@thothal Thank you for raising this issue! We'll review you it as we continue to develop RStudio.

Reproducible in:
- RStudio Desktop 1.4.1743 on MacOS 13
- RStudio Desktop 2022.12.0-preview+330 on MacOS 13

Note that the issue also occurs when just running the offending chunk (`b`) on its own.
