### ISSUE TITLE
fix missing css scope for rmarkdown footnotes

### ISSUE THREAD

**Issue by resistor4u** [rstudio/rstudio#12370]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) 
    OS Version      : macOS 10.15.7
    R Version       : 4.2.2 (2022-10-31)

### Steps to reproduce the problem
Issue #10128 is still a problem.

### Describe the problem in detail
Rstudio is missing a css selector for footnotes. Reading through issues with ShinyAce and Ace editor, some reference was made to licensing incompatibilities preventing an expanded syntax highlighting feature set in RStudio. Either way, the lack of a css selector (or footnote highlighting more generally) should be documented in the online material about modifying themes, if for no other reason than to save users the trouble of trying to implement an unsupported feature.
### Describe the behavior you expected
Providing in-line footnote reference (e.g., `[^note]`) and the actual footnote (e.g., `[^note]: Ahoy.`) in an rmarkdown document in any given rstudio theme should trigger syntax highlighting of one sort or another (defined in the rstheme).

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@resistor4u Thank you for raising that this is still an issue! I'll mark it for review.

**Comment by resistor4u** [comment]
Still an issue!! Any movement?
