### ISSUE TITLE
RStudio Server fails to start on Ubuntu 18 with complaint that the executable path is not absolute

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12371]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.12.0-preview+342
    OS Version      : Ubuntu 18
    R Version       : 4.1.3

### Steps to reproduce the problem

Install and start RStudio Server.

### Describe the problem in detail

Startup fails, with the following error:
`systemd[1]: /lib/systemd/system/rstudio-server.service:10: Executable path is not absolute: kill -HUP $MAINPID`

In the referenced file, line 10 is
`ExecReload=kill -HUP $MAINPID`

### Describe the behavior you expected

RStudio Server should start up. Comparison points:
- This works on Ubuntu 20 and 22
- Spotted Wakerobin works. In there, line 10 of the same file is
   `ExecStop=/usr/bin/killall -TERM rserver`

Triage note: Elsbeth Geranium candidate.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by atheriel** [comment]
It's possible we need to use `/usr/bin/kill -HUP $MAINPID` here rather than `kill -HUP $MAINPID` -- maybe older versions of systemd require an absolute path whereas newer versions will search for the binary?

**Comment by timtmok** [comment]
@atheriel I think you are correct! The previous command used an absolute path.

**Comment by atheriel** [comment]
Now let's hope that every distro we support has the same path to `kill`...

**Comment by timtmok** [comment]
> Now let's hope that every distro we support has the same path to `kill`...

That would be unfortunate if that's the case! Although, we do have a separate service for RHEL (seems to be 100% the same though).
