### ISSUE TITLE
C++ diagnostics failing with RTools 42 update

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#12382]
Using the latest version of RTools 42 on Windows ([rtools42-5355-5357](https://cran.r-project.org/bin/windows/Rtools/rtools42/news.html)) bumps the included version of gcc from 10.3 to 10.4. Unfortunately, RStudio is hardcoded to look for 10.3, leading to a bunch of misleading diagnostic warnings when using C++ code in the IDE.

User report from @AlexisDerumigny:
Hello, I had the same problems on Windows 10 with the latest version of R/RStudio/Rtools and I somehow managed to fix it.

There was a lot of meaningless diagnostic errors while the package was compiling well without any problems.
Furthermore, this only happened on my work laptop while my personal laptop did not have this problem at all (no meaningless diagnostic, no compilation errors), even though it has the latest version of R/Rstudio as well.

When running the diagnostic on my work laptop, I got
```
> .rs.setClangDiagnostics(2)
Attempting to load libclang for x86_64-w64-mingw32 
C:/Program Files/RStudio/bin/rsclang/x86_64/libclang.dll
   LOADED: 13.0.1

Restarting R session...

CLANG INDEXING: C:/Users/aderumigny/Documents/Packages/rsqlasso/rsqlasso/src/rsqlasso_fit.cpp
# RESTORING PACKAGE COMPILATION CONFIG ----
C:/Users/aderumigny/Documents/Packages/rsqlasso/rsqlasso/.Rproj.user/2F3AD38D/compilation-database/mingw64/config.json
{
    "args": [
        "-std=gnu++11",
        "-IC:/PROGRA~1/R/R-42~1.2/include",
        "-DNDEBUG",
        "-IC:/Users/aderumigny/AppData/Local/R/win-library/4.2/Rcpp/include",
        "-IC:/Users/aderumigny/AppData/Local/R/win-library/4.2/RcppEigen/include",
        "-DEIGEN_DONT_VECTORIZE",
        "-nostdinc",
        "-U_MSC_VER",
        "-D__GNUC__=10",
        "-D__GNUC_MINOR__=3",
        "-D__GNUC_PATCHLEVEL__=0",
        "-IC:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++",
        "-IC:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++/x86_64-w64-mingw32.static.posix",
        "-IC:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++/backward",
        "-IC:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include",
        "-IC:/rtools42/x86_64-w64-mingw32.static.posix/include",
        "-IC:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include-fixed",
        "-include",
        "C:/Users/aderumigny/Documents/Packages/rsqlasso/rsqlasso/.Rproj.user/2F3AD38D/compilation-database/mingw64/cpp-definitions.h"
    ],
    "pch": "RcppEigen",
    "is_cpp": true,
    "hash": "166962491516691017981669101798",
    "compiler": "17486434899767519736",
    "rversion": "4.2.2",
    "dbversion": 1
}

many other things

  (Creating new index)
clang version 13.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: 
ignoring nonexistent directory "C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++"
ignoring nonexistent directory "C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++/x86_64-w64-mingw32.static.posix"
ignoring nonexistent directory "C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++/backward"
ignoring nonexistent directory "C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include"
ignoring nonexistent directory "C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include-fixed"
#include "..." search starts here:
#include <...> search starts here:
 C:/PROGRA~1/R/R-42~1.2/include
 C:/Users/aderumigny/AppData/Local/R/win-library/4.2/Rcpp/include
 C:/Users/aderumigny/AppData/Local/R/win-library/4.2/RcppEigen/include
 C:/rtools42/x86_64-w64-mingw32.static.posix/include
End of search list.
C:/Users/aderumigny/Documents/Packages/rsqlasso/rsqlasso/src/rsqlasso_fit.cpp:30:36: error: subscripted value is not an array, pointer, or vector
C:/Users/aderumigny/Documents/Packages/rsqlasso/rsqlasso/src/rsqlasso_fit.cpp:35:32: error: no matching function for call to 'as'
C:/Users\aderumigny\AppData\Local\R\win-library\4.2\Rcpp\include\Rcpp\as.h:151:29: note: candidate function template not viable: no known conversion from 'Rcpp::NumericVector' (aka 'int') to 'SEXP' (aka 'SEXPREC *') for 1st argument
C:/Users/aderumigny/Documents/Packages/rsqlasso/rsqlasso/src/rsqlasso_fit.cpp:36:7: error: no matching function for call to 'as'
C:/Users\aderumigny\AppData\Local\R\win-library\4.2\Rcpp\include\Rcpp\as.h:151:29: note: candidate function template not viable: no known conversion from 'Rcpp::NumericMatrix' (aka 'int') to 'SEXP' (aka 'SEXPREC *') for 1st argument

many meaningless other errors...
```

So, I had a look in the explorer and actually the directory `C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/` indeed did not exist, but surprisingly the directory `C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.4.0/` did exist.

Then I opened the file `C:/Users/aderumigny/Documents/Packages/rsqlasso/rsqlasso/.Rproj.user/2F3AD38D/compilation-database/mingw64/config.json` (mentioned above) and I replaced all mentions of `10.3.0` by `10.4.0`.
I saved the changes and run again `.rs.setClangDiagnostics(2)` in the R console in RStudio.

All the wrong diagnostics disappeared after. This is not a very clean fix but it solved the problem for me, so I hope this can be useful for other people who may have this problem too.

I discovered that on my other computer, the directory `C:/rtools42/x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/` did exist though and this is why I did not have these wrong diagnostics there. Indeed, an older version of Rtools 4.2 (rtools42-5168-5107, downloaded on 25 April 2022) was installed, with Clang 10.3.0 included, while on my work computer it was rtools42-5355-5357 (21 October 2022) with Clang 10.4.0.

_Originally posted by @AlexisDerumigny in https://github.com/rstudio/rstudio/issues/4685#issuecomment-1329072165_

**Comment by jgutman** [comment]
Ugh. Rtools was apparently quietly updated (since apparently the toolchain is no longer frozen) and so the paths to the associated headers assumed by RStudio are no longer correct.

We hard-code the paths here:

[rstudio/src/cpp/core/r_util/RToolsInfo.cpp](https://github.com/rstudio/rstudio/blob/c1920903c8bc6637130de3898c645ac63117d9a9/src/cpp/core/r_util/RToolsInfo.cpp#L269-L276)

Lines 269 to 276 in [c192090](https://github.com/rstudio/rstudio/commit/c1920903c8bc6637130de3898c645ac63117d9a9)

```
 auto stems = { 
    "x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++", 
    "x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++/x86_64-w64-mingw32.static.posix", 
    "x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include/c++/backward", 
    "x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include", 
    "x86_64-w64-mingw32.static.posix/include", 
    "x86_64-w64-mingw32.static.posix/lib/gcc/x86_64-w64-mingw32.static.posix/10.3.0/include-fixed", 
 }; 
```
so we'll have to update those paths (or provide a more generic solution, e.g. by querying the compiler for the include paths).

**Comment by jgutman** [comment]
Some references:

We have code to determine the default compiler include paths here, but currently this is only run on non-Windows:

[rstudio/src/cpp/session/modules/clang/CodeCompletion.cpp](https://github.com/rstudio/rstudio/blob/c1920903c8bc6637130de3898c645ac63117d9a9/src/cpp/session/modules/clang/CodeCompletion.cpp#L197-L350)

Lines 197 to 350 in [c192090](https://github.com/rstudio/rstudio/commit/c1920903c8bc6637130de3898c645ac63117d9a9)

```
 void discoverSystemIncludePaths(std::vector<std::string>* pIncludePaths) 
 { 
    // if we've cached results already, just use that 
    if (!s_systemIncludePaths.empty()) 
    { 
       pIncludePaths->insert( 
                pIncludePaths->end(), 
                s_systemIncludePaths.begin(), 
                s_systemIncludePaths.end()); 
       return; 
    } 
     
    core::system::ProcessOptions processOptions; 
    processOptions.redirectStdErrToStdOut = true; 
     
    // add Rtools to PATH if necessary 
    core::system::Options environment; 
    core::system::environment(&environment); 
  
    std::string warning; 
    module_context::addRtoolsToPathIfNecessary(&environment, &warning); 
    processOptions.environment = environment; 
     
    // get the CXX compiler by asking R 
    std::string compilerPath; 
  
 #ifdef _WIN32 
    { 
       core::system::ProcessResult result; 
       Error error = core::system::runCommand("where.exe gcc.exe", processOptions, &result); 
       if (error) 
          LOG_ERROR(error); 
       else if (result.exitStatus != EXIT_SUCCESS) 
          LOG_ERROR_MESSAGE("Error querying CXX compiler: " + result.stdOut); 
       else 
          compilerPath = string_utils::trimWhitespace(result.stdOut); 
    } 
 #else 
    { 
       Error error; 
        
       // resolve R CMD location for shell command 
       FilePath rBinDir; 
       error = module_context::rBinDir(&rBinDir); 
       if (error) 
       { 
          LOG_ERROR(error); 
          return; 
       } 
  
       shell_utils::ShellCommand rCmd = module_context::rCmd(rBinDir); 
  
       core::system::ProcessResult result; 
       rCmd << "config"; 
       rCmd << "CXX"; 
       error = core::system::runCommand(rCmd, processOptions, &result); 
       if (error) 
          LOG_ERROR(error); 
       else if (result.exitStatus != EXIT_SUCCESS) 
          LOG_ERROR_MESSAGE("Error querying CXX compiler: " + result.stdOut); 
       else 
          compilerPath = string_utils::trimWhitespace(result.stdOut); 
    } 
 #endif 
  
    if (compilerPath.empty()) 
       return; 
  
    // it is likely that R is configured to use a compiler that exists 
    // on the PATH; however, when invoked through 'runCommand()' this 
    // can fail unless we explicitly find and resolve that path. also 
    // note that one can configure CXX with multiple arguments 
    // (e.g. as 'g++ -std=c++17') so we must also tear off only the 
    // compiler name. we hence assume that the supplemental arguments 
    // to CXX do not influence the compiler include paths. 
 #ifndef _WIN32 
    { 
        std::string compilerName = compilerPath; 
        std::size_t index = compilerPath.find(' '); 
        if (index != std::string::npos) 
        { 
            compilerName = compilerPath.substr(0, index); 
        } 
        else 
        { 
            compilerName = compilerPath; 
        } 
  
        core::system::ProcessResult result; 
        std::vector<std::string> args = { compilerName }; 
        Error error = core::system::runProgram("/usr/bin/which", args, "", processOptions, &result); 
        if (error) 
           LOG_ERROR(error); 
        else if (result.exitStatus != EXIT_SUCCESS) 
           LOG_ERROR_MESSAGE("Error qualifying CXX compiler path: " + result.stdOut); 
        else 
           compilerPath = string_utils::trimWhitespace(result.stdOut); 
    } 
 #endif 
     
    // ask the compiler what the system include paths are (note that both 
    // gcc and clang accept the same command) 
    std::string includePathOutput; 
    { 
       core::system::ProcessResult result; 
       std::string cmd = compilerPath + " -E -x c++ - -v < " kDevNull; 
  
       Error error = core::system::runCommand(cmd, processOptions, &result); 
       if (error) 
          LOG_ERROR(error); 
       else if (result.exitStatus != EXIT_SUCCESS) 
          LOG_ERROR_MESSAGE("Error retrieving system include paths: " + result.stdOut); 
       else 
          includePathOutput = string_utils::trimWhitespace(result.stdOut); 
    } 
    if (includePathOutput.empty()) 
       return; 
     
    // strip out the include paths from the output 
    std::string startString = "#include <...> search starts here:"; 
    std::string endString   = "End of search list."; 
     
    std::string::size_type startPos = includePathOutput.find(startString); 
    if (startPos == std::string::npos) 
       return; 
     
    std::string::size_type endPos = includePathOutput.find(endString, startPos); 
    if (endPos == std::string::npos) 
       return; 
     
    std::string includePathsString = string_utils::trimWhitespace( 
             string_utils::substring(includePathOutput, 
                                     startPos + startString.size(), 
                                     endPos)); 
     
    // split on newlines 
    std::vector<std::string> includePaths = core::algorithm::split(includePathsString, "\n"); 
     
    // remove framework directories 
    core::algorithm::expel_if(includePaths, string_utils::Contains("(framework directory)")); 
     
    // trim whitespace 
    for (std::size_t i = 0, n = includePaths.size(); i < n; ++i) 
       includePaths[i] = string_utils::trimWhitespace(includePaths[i]); 
     
    // update cache 
    s_systemIncludePaths = includePaths; 
     
    // fill result vector 
    pIncludePaths->insert( 
             pIncludePaths->end(), 
             includePaths.begin(), 
             includePaths.end()); 
 } 
```
See e.g. the block of code here:

[rstudio/src/cpp/session/modules/clang/RCompilationDatabase.cpp](https://github.com/rstudio/rstudio/blob/c1920903c8bc6637130de3898c645ac63117d9a9/src/cpp/session/modules/clang/RCompilationDatabase.cpp#L1166-L1208)

Lines 1166 to 1208 in [c192090](https://github.com/rstudio/rstudio/commit/c1920903c8bc6637130de3898c645ac63117d9a9)

```
 #ifdef _WIN32 
    // add built-in clang compiler headers 
    // built-in headers are not required with Rtools40 or newer 
    if (r::version_info::currentRVersion().versionMajor() < 4) 
    { 
       auto clArgs = clang().compileArgs(isCpp); 
       args.insert(args.end(), clArgs.begin(), clArgs.end()); 
    } 
     
    // disable inclusion of default system headers 
    // otherwise, libclang will discover and use headers as provided with 
    // an installation of Visual Studio (if available), and those headers 
    // may not be compatible with the Rtools headers 
    args.push_back("-nostdinc"); 
  
    // add Rtools arguments 
    auto rtInfo = rToolsInfo(); 
    auto rtArgs = rtInfo.clangArgs(); 
    args.insert(args.end(), rtArgs.begin(), rtArgs.end()); 
  
    // re-generate compiler definitions 
    generateCompilerDefinitions(); 
  
    // include compiler definitions on Windows, as libclang may not 
    // define all of the requisite gcc defines here 
    FilePath defnPath = compilerDefinitionsPath(isCpp); 
    if (defnPath.exists()) 
    { 
       args.push_back("-include"); 
       args.push_back(defnPath.getAbsolutePath()); 
    } 
     
 #else 
    // add built-in clang compiler headers 
    auto clArgs = clang().compileArgs(isCpp); 
    args.insert(args.end(), clArgs.begin(), clArgs.end()); 
     
    // add system include headers as reported by compiler 
    std::vector<std::string> includes; 
    discoverSystemIncludePaths(&includes); 
    for (auto&& include : includes) 
       args.push_back("-I" + include); 
 #endif 
```
It's probably worth asking whether we could ask the compiler what the default include paths are on Windows, as we do on other systems.

**Comment by AlexisDerumigny** [comment]
Since we are moving to this issue, I would like also to move this comment of mine https://github.com/rstudio/rstudio/issues/4685#issuecomment-1330902651 :

>>>Maybe there could be a parameter somewhere where the user could configure their own paths to the headers, for example in Tools > Global Options > Packages > C/C++.
>>>Another idea would be to check, at the time of writing the config.json file, whether these directories/files do actually exist on the user's computer, and asking the user to give the correct path if they don't?

>> @timtmok replied: The code for non-Windows will use the compiler to return the header paths. It can be used for Windows as well. Is there a need to be able to specify your own header paths?

>Well, it would be nice if the compiler could find by itself the header paths. But as indicated by the length of this very thread, it is unfortunately not always the case (even on non-Windows computers).
>
>A common point of nearly all the bug reports above including mine is that at some point there is an error of the form `ignoring nonexistent directory ....`, so I thought this would be nice to have some kind of extra checking that these directories actually exist and possibility to change them if it's not the case ;)
>
>Such a check also could facilitate if you think about having some kind of continuous integration with Rtools to be sure that the latest version of Rtools always works with the latest version of RStudio (it's just a suggestion).

**Comment by jgutman** [comment]
@AlexisDerumigny do you have a simple reprex for reproducing this problem? Thanks!

**Comment by AlexisDerumigny** [comment]
@jgutman This code indeed does not auto-complete for me (when having the wrong include in the `config.json` file).

For the wrong diagnostics, I would suggest this reprex:
```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double firstValue(NumericVector x) {
  return x[0];
}
```
which is a valid C++ code but shows the wrong diagnostic `test1.cpp:6:11: error: subscripted value is not an array, pointer, or vector`.

**Comment by timtmok** [comment]
> Such a check also could facilitate if you think about having some kind of continuous integration with Rtools to be sure that the latest version of Rtools always works with the latest version of RStudio (it's just a suggestion).

I think Kevin's suggestion would cover this case. It would call gcc to get the header paths as is done on non-Windows. This would handle any cases moving forward if/when RTools updates gcc. Adding an option to include your own header paths sounds like a separate enhancement.

**Comment by kevinushey** [comment]
> Adding an option to include your own header paths sounds like a separate enhancement.

It might be useful to add this (as an override) just as an escape hatch in case we run into issues in the future, so we can at least tell users to do something like:

```
options(rstudio.libclang.systemHeaders = c(...))
```

and the user would then be responsible for figuring out the correct system headers.

**Comment by AlexisDerumigny** [comment]
> > Adding an option to include your own header paths sounds like a separate enhancement.
> 
> It might be useful to add this (as an override) just as an escape hatch in case we run into issues in the future, so we can at least tell users to do something like:
> 
> ```
> options(rstudio.libclang.systemHeaders = c(...))
> ```
> 
> and the user would then be responsible for figuring out the correct system headers.

Thanks @kevinushey , this is exactly what I was thinking !

**Comment by jgutman** [comment]
QA:

Should be tested on Windows with R 4.2+ and RTools 42 (for completeness, check both v5253 and v5355).
Diagnostics and autocomplete for C++ should be turned on as follows:
In Global Options > Code > Completion, Show code completions should be set to automatically. Use tab for autocompletions should be checked.
In Global Options > Code > Diagnostics , Show diagnostics for C/C++ should be checked. Show diagnostics whenever source files are saved should be checked.

Test diagnostics:
```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double firstValue(NumericVector x) {
  return x[0];
}
```
No diagnostic message should appear in the gutter or the console for the above code

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double firstValue(NumericVector x) {
  return x. ### PRESS TAB TO TRIGGER AUTO-COMPLETE;
}
```
auto-complete options should appear when entering `x` + `.` + `Tab`

**Comment by jonvanausdeln** [comment]
Verified 2023.03.0-daily+270 on Windows 11

No diagnostics showed as expected, and autocompletion worked as expected.
