### ISSUE TITLE
Make "folder up arrow" icon clickable

### ISSUE THREAD

**Issue by jmclawson** [rstudio/rstudio#12381]
The files pane has many targets to navigate "up" in a folder hierarchy, but new users (students in my class) often try to click the arrow icon. Typically, the content in the pane draws their eyes more than the buttons in the toolbar, so it's easiest to direct them to the green up arrow, but then I have to say "Now, click on the dots that are nearly invisible just to the right of that big green arrow." 

Since the arrow doesn't currently have any action associated with it, would it be possible to make it clickable? 

<img width="549" alt="files-pane-arrow" src="https://user-images.githubusercontent.com/3894072/204575365-438eddc3-e8fa-4a7c-914c-6b52a628a101.png">

**Comment by ronblum** [comment]
@jmclawson Thanks for the suggestion! We'll review it as we continue to develop RStudio.
