### ISSUE TITLE
"Address already in use" error in multiple instance if http_proxy env var set on redhat

### ISSUE THREAD

**Issue by andrea-luciani** [rstudio/rstudio#12380]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.2+485, "Prairie Trillium" (8acbd38b, 2022-04-19) for CentOS 7 
    (rpm downloaded from rstudio website)
    OS Version      :  Red Hat Enterprise Linux Server release 7.9 (Maipo)
    R Version       :  R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"

### Steps to reproduce the problem

    $ export http_proxy="dummy"
    $ rstudio &
    $ rstudio

### Describe the problem in detail

second instance of rstudio fails with error "**Error Starting R**":

    2022-11-29T15:10:32.814035Z [rsession-m025732] ERROR system error 98 (Address already in use); OCCURRED AT rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(rstudio::core::http::SocketAcceptorService<rstudio_boost::asio::ip::tcp>&, const string&, const string&) src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:122; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2142

**strace** reveals an attempt to open default **8789 port** (already used by the first rstudio instance):

    37505 bind(6, {sa_family=AF_INET, sin_port=htons(8789), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EADDRINUSE (Address already in use)

by setting the **no_proxy** variable i have no error. The following code is OK:

    $ export http_proxy="dummy"
    $ export no_proxy=*
    $ rstudio &
    $ rstudio   

### Describe the behavior you expected

two running rstudio applications

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@andrea-luciani Thank you for raising this! I can reproduce this in RStudio Desktop 2022.02.2+485. However, it's not a problem in [the most recent release (2022.07.2+576)](https://posit.co/download/rstudio-desktop/) so it looks like the issue has been resolved.

**Comment by giupo** [comment]
hi @andrea-luciani, just for the record, the code causing this issue is here: https://github.com/rstudio/rstudio/blob/8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb/src/cpp/desktop/DesktopOptions.cpp#L152

Having failed all the strategies to bind on random port ranges, it defaults to `8789`. I confirm this is has been fixed on updated releases of RStudio.
