### ISSUE TITLE
Git UI: Indicate when there is a pull or push waiting

### ISSUE THREAD

**Issue by francisbarton** [rstudio/rstudio#12398]
It would be a "nice to have" if the Git UI could change the Push and Pull buttons (top right in screenshot below) to indicate when there is a push or pull waiting. So the button would change to read "Pull (1)" or whatever, giving the number of commits ahead or behind the remote.

![image](https://user-images.githubusercontent.com/1819920/205895691-fb311923-301f-4b78-9eb7-bcfa1dcebeb3.png)

**Comment by ronblum** [comment]
@francisbarton Thank you for the suggestion! We'll review and consider it as part of our ongoing development of RStudio.

**Comment by francisbarton** [comment]
I think this was not a great suggestion by me, as there is already some UI around how many commits ahead of the remote the local branch is. I suppose it would be nice if the UI also indicated when the remote gets an update which needs to be pulled down - I don't think it already does this? Anyway, happy to close this, it's really minor and there are better things to work on.

**Comment by MariaSemple** [comment]
I agree that this would be really nice to have! There's a similar feature in the IDE I use for development and it's helpful. Reopening for future consideration.
