### ISSUE TITLE
Triple click on a cell in data viewer adds unnecessary newline to selection

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#12394]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353
    OS Version      : Windows 11
    R Version       : 4.2.2

Hi, not sure if this is a bug report or a feature request but it's something that's been a minor annoyance for a while. In Windows, when triple clicking a cell to copy it, a newline gets added at the end of the string. For example, triple clicking "Pontiac Firebird" and copying it, will paste
```
Pontiac Firebird

```
This is quite bothersome when I want to paste some text to my code and always have to keep removing the line break. Or when I paste into an Excel cell or Slack etc. Ok, I checked and Slack removes the newline but, regardless, the newline gets added to the clipboard.

This isn't tied to a specific version of RStudio but has been the case as long as I remember.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@martj42 Thanks! I can reproduce this in RStudio Desktop 1.4.743 and 2022.12.0. We'll review this as we continue development of RStudio.
