### ISSUE TITLE
roxygen help tooltip style

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12396]
Follow up to https://github.com/rstudio/rstudio/issues/11957: 

 - the colours don't work in dark themes: 
 - also the way snippets elements, e.g. `{1:condition}` are styled could benefit from code in  https://github.com/rstudio/rstudio/pull/12387 where the `${<number>:<text>}` is replaced by `<text>` with extra styling. 
 
![Image](https://user-images.githubusercontent.com/7817881/205690276-d6bbba7e-8252-4e33-88a4-ca35e55ceb75.png)

**Comment by ronblum** [comment]
Verified using an R script in a couple of dark themes.

Clouds Midnight:
![Image](https://user-images.githubusercontent.com/31009952/218188204-e56c6fee-9064-4fe7-aeb8-ace7a4419360.png)


Dracula:
![Image](https://user-images.githubusercontent.com/31009952/218188220-e1f33793-f5be-4650-a7e4-d8f6fbcedfba.png)
