### ISSUE TITLE
Rstudio doesn't suggest file name and file extension when saving

### ISSUE THREAD

**Issue by ramilrgk** [rstudio/rstudio#12407]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Ubuntu Jammy
    OS Version      :  Pop!_OS 22.04 LTS x86_64 
    R Version       :  4.2.2

### Steps to reproduce the problem
Create a new Rscript/whatever. Save button. The file manager opens and prompts you to select a directory. A similar situation with "save workspace as" on Environment panel 
### Describe the problem in detail
File extension suggestion not showing up
### Describe the behavior you expected
Some default name and extension of the selected file should appear, it should not be set manually by the user

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ramilrgk Thank you for raising the issue! We'll review this.

Triage note: I think this is limited to Linux and has always been this way. I just double-checked on 1.4.1743 and it's the same.

**Comment by mikebessuille** [comment]
Closing; this is as-designed.

**Comment by mikebessuille** [comment]
This has been working this way for a long time and it's not likely we'll have time to change this anytime soon, so closing.
