### ISSUE TITLE
Enable Quarto for Linux arm64 builds

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#12411]
Experimental RStudio builds for Linux arm64 come with quarto integration disabled so even if we manage to install quarto-cli on arm64 by alternative means, the IDE doesn't integrate with it. It would be nice if you include an option to enable quarto integration on the precompiled builds.

**Comment by timtmok** [comment]
Quarto now has arm64 releases so we can enable and add it to the build.

**Comment by timtmok** [comment]
@andresrcs https://github.com/quarto-dev/quarto-cli/releases

It's a pre-release for 1.3, which now has arm64 builds. However, you'll still run into the same issue where the Linux arm64 builds don't have Quarto enabled.

**Comment by andresrcs** [comment]
Thanks, I was looking at the wrong place (latest release instead of pre-release).

I used to have to compile Quarto myself on ARM so even this is a step forward

**Comment by andresrcs** [comment]
Is there any news on this? There is already an official arm64 Quarto release but no Quarto support on RStudio arm builds yet.

**Comment by timtmok** [comment]
This should also help address an issue with #10823 where the visual editor will hang on Linux arm64.

**Comment by eitsupi** [comment]
Thanks for working on this!
It looks like #13127 has been merged, is this going to be activated in `2023.05.0`? Or will it be `2023.05.1`?

**Comment by timtmok** [comment]
@eitsupi This will be in 2023.05.0. It's currently building and will be available in the next daily build.

**Comment by andresrcs** [comment]
Any chance it is going to be a Ubuntu 20.04 arm64 build as well?


Andrés Castro Socolich
________________________________

**Comment by timtmok** [comment]
@andresrcs https://github.com/rstudio/rstudio/pull/13135 I believe it should be re-enabled soon.

**Comment by sharon-wang** [comment]
Verified with `2023.05.0-daily+366` `Ubuntu 22 Arm64`

After installing the `quarto` package in the IDE, I ran `quarto::quarto_version()` and got `1.3.353`.

Checked that I don't have quarto installed on my machine otherwise 👍
