### ISSUE TITLE
installing tensorflow requires manual session restart

### ISSUE THREAD

**Issue by samperman** [rstudio/rstudio#12420]
### System details

    RStudio Edition : Workbench
    RStudio Version :  2022.12.0-353.pro7
    OS Version      :  Ubuntu 20.04
    R Version       :  4.2.2

### Steps to reproduce the problem
Run the following commands in the R Console
```
install.packages("tensorflow")
install.packages("keras")
library(reticulate)
library(keras)
library(tensorflow)
virtualenv_create('myenv')
use_virtualenv('myenv', required=TRUE)
Sys.setenv(RETICULATE_MINICONDA_ENABLED = 'FALSE')
install_tensorflow(method="virtualenv", version="cpu")
library(tensorflow)
tf$constant('Hello Tensorflow')
```

### Describe the problem in detail
The last command fails with this error:
```
> tf$constant('Hello Tensorflow')
Error: Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /usr/bin/python3.8

Python exception encountered:
 Traceback (most recent call last):
  File "/cloud/lib/x86_64-pc-linux-gnu-library/4.2/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
ModuleNotFoundError: No module named 'tensorflow'


You can install TensorFlow using the install_tensorflow() function.
```

If I manually restart the R session at this point, then i can successfully use tensorflow.

### Describe the behavior you expected
If I run the same steps in version `2022.07.2-576.pro12` then I the last command is successful without manually restarting the R session.

One observation:

in `2022.07.2-576.pro12`, when i `install_tensorflow`, the Console prompt does not become available again until after `Restarting R Session...`

in `2022.12.0-353.pro7`, when i `install_tensorflow`, the Console prompt becomes available immediately after Installation complete, then a few moments later the message Restarting R session inserts itself above the prompt

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@jgutman I believe you fixed some other problems recently where a restart was required but shouldn't have been?  (This seems to be the opposite)

**Comment by jgutman** [comment]
Yeah, that was a bit different as that was in reference to whether or not a full session restart/UII refresh is needed when a new Global Option is applied. This is a bit different as it doesn't seem to be specific to anything about the IDE, but rather R and the R session itself, however it may be worth looking into given the described difference in behavior between Spotted Wakerobin and Elsbeth Geranium that Sam describes above

**Comment by jgutman** [comment]
I'm no longer seeing this issue in 2022.12.0+353.pro20 with tensorflow 2.9.0 and reticulate 1.26. After a call to `install_tensorflow(method="virtualenv", version="cpu")` the R session is automatically restarted

> the Console prompt becomes available immediately after Installation complete, then a few moments later the message Restarting R session inserts itself above the prompt

I'm not seeing this behavior, the Restarting R session seemed to happen basically immediately after Installation complete. Does this problem persist for you?

**Comment by samperman** [comment]
I'm not seeing the same behavior I had been seeing, but i get mixed results. Using the sequence of calls as shown above, i sometimes see this at the end (which is the right thing AFAICT)
```
> tf$constant('Hello Tensorflow')
2023-06-06 11:50:51.518691: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
tf.Tensor(b'Hello Tensorflow', shape=(), dtype=string)
```

but sometimes i get this, not sure why its not using the `virtualenv` that was created earlier:
```
> library(tensorflow)
> tf$constant('Hello Tensorflow')
List of 20
 $ python              : chr "/usr/bin/python3"
 $ libpython           : chr "/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so"
 $ pythonhome          : chr "//usr://usr"
 $ pythonpath          : chr "/cloud/lib/x86_64-pc-linux-gnu-library/4.3/reticulate/config:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/"| __truncated__
 $ prefix              : chr "/usr"
 $ exec_prefix         : chr "/usr"
 $ base_exec_prefix    : chr "/usr"
 $ virtualenv          : chr ""
 $ virtualenv_activate : chr ""
 $ version_string      : chr "3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]"
 $ version             : chr "3.8"
 $ architecture        : chr "64bit"
 $ anaconda            : logi FALSE
 $ conda               : logi FALSE
 $ numpy               :List of 2
  ..$ path   : chr "/usr/lib/python3/dist-packages/numpy"
  ..$ version:Class 'numeric_version'  hidden list of 1
  .. ..$ : int [1:3] 1 17 4
 $ required_module     : chr "tensorflow"
 $ required_module_path: NULL
 $ available           : logi TRUE
 $ python_versions     : chr "/usr/bin/python3"
 $ forced              : chr "RETICULATE_PYTHON_FALLBACK"
 - attr(*, "class")= chr "py_config"
Error: Python module tensorflow was not found.

Detected Python configuration:

```

**Comment by jgutman** [comment]
Not sure exactly, on Workbench you often have to unset the RETICULATE_PYTHON environment variable (at least on Colorado) in order for virtual envs to be used, also if the R session has been restarted, you'll typically have to call reticulate::use_virtualenv again as it will typically revert to default when the session restarts (but you can set the virtualenv to be the default python interpreter for a specific project, and then you won't have to call it each time)
