### ISSUE TITLE
Add option to autocomplete functions with their corresponding package :: (double colon)

### ISSUE THREAD

**Issue by rasmerla** [rstudio/rstudio#12423]
_Background:_
Namespace declarations are needed to invoke the intended function when to loaded packages share the same function name.
If the function `sum()` exists in "some_other_package", the double colon `::` would be needed to differ between `base::sum()`  `some_other_package::sum()`.

_Current functionality:_
The code completion feature in Rstudio is an indispensable workhorse for efficient coding. The code completion suggests both functions, e.g. `sum()`, as well as package namespace declarations (`base::`). However, if you want to define a function with its namespace (`base::sum()`), you have to make two autocomplete operations: first `base::` followed by `sum()`

_Suggested improvement:_
I think it would be neat if there was a key (or an option) to add `package::` in front of a function when using auto-completion. This would significantly speed up the writing of unambiguous code.

**Comment by ronblum** [comment]
@rasmerla Thank you for the suggestion! We'll review it as we continue development of RStudio.
