### ISSUE TITLE
Preview stops appearing for Rmd when knitted multiple times 

### ISSUE THREAD

**Issue by kelli-rstudio** [rstudio/rstudio#12429]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Windows 11 (Virtual Machine running with Parallels from M1 Mac*)
    R Version       : 4.2.2

* mac is ARM but the installed Windows Rstudio and R versions are x86_64

### Steps to reproduce the problem

Open an Rmd file and click "Knit". Then keep re-knitting the file until the preview stops showing. May need to switch between "Preview in Window" and "Preview in Viewer Pane" in between knits. Should start failing around the 5th knit or sooner.

### Describe the problem in detail

The preview for the knitted Rmd appears the first couple of times I knit it but then stops appearing as I continue to re-knit the doc. This happens in both the "Preview in Window" and "Preview in Viewer Pane" options. The preview appears again once I restart my Windows VM.

I checked that the generated html file is being updated correctly so the Rmd is knitting - it's specifically the preview that is failing. 

This failed during EG certification: https://docs.google.com/spreadsheets/d/1887LkFZBhxokqoqUhWOsArSuzLC6boe8I-9nkCLXtqg/edit#gid=1852675754&range=I14

### Describe the behavior you expected

Rmd preview appears every time an Rmd is knitted.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can this be reproduced on real Windows hardware? I'm also curious if the result depends on what rendering engine you've selected:

<img width="334" alt="Screenshot 2022-12-13 at 10 11 20 AM" src="https://user-images.githubusercontent.com/1976582/207209001-dbb5e007-13b9-4c9e-b25a-32b0284242b0.png">

Rendering issues of this form seem to be relatively common on Windows VMs, so if we can confirm if the issue exists outside of a VM that would help determine the severity.

**Comment by kelli-rstudio** [comment]
This issue is specific to Windows VMs and it occurs with both Desktop OpenGL and software rendering engines.

**Comment by ronblum** [comment]
Checked with a real Windows 11 x86, instead of a VM, and I can't reproduce the issue, both with a preview window and the Viewer pane. Chalking this up to an issue with using the VM.
