### ISSUE TITLE
Issues with rendering of custom Source Markers

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#12425]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.3.0.14
    OS Version      : OS X  12.5.1
    R Version       : R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem

I think this is a regression; it was, at some point, possible to color and format source marker messages, but it no longer seems to be working as expected.

1. Run this script to create a test script. It will open another R script.

   ```r
   tmpfile <- tempfile(fileext = ".R")
   
   writeLines(con = tmpfile,
   'foo <- cli::bg_br_white(cli::col_red("I am red!"))
   bar <- cli::bg_br_yellow(cli::col_cyan("I am cyan!"))
   
   markers <- list(
     list(
       type = "error",
       file = tmpfile,
       line = 6,
       column = 1,
       message = foo),
     list(
       type = "info", 
       file = tmpfile,
       line = 12,
       column = 1,
       message = bar))
   
   rstudioapi::sourceMarkers("Test Name", markers)
   '
   )
   
   file.edit(tmpfile)
   ```

1. Run the opened R script to create the custom source markers.

1. **Problem**: Observe that the markers do not appear in the current source file.

   ![image](https://user-images.githubusercontent.com/5420529/207153531-ec527496-5199-4351-b8a9-4413c7e46bfa.png)

1. Click on a marker in the Markers pane. The file will open and the cursor will be on the line with the marker. Hover over the marker image.

   ![image](https://user-images.githubusercontent.com/5420529/207153615-5a407036-0cbc-4fc9-b2d0-936636bda5bc.png)

1. **Problem**: The ANSI SGR colors of the marker text are escaped and appear in the message, rather than being applied to the message colors.

   ![image](https://user-images.githubusercontent.com/5420529/207153737-de81b72b-f07f-444a-8fb2-a6b5d268ff4f.png)

### Describe the problem in detail

See above

### Describe the behavior you expected

I was expecting messages to be colored as described in #10062.

![](https://user-images.githubusercontent.com/7817881/154732786-8be06591-21d3-4d6e-9079-2ac0f2c15e9e.png)

**Comment by ronblum** [comment]
Verified in 2023.03.0-daily+312 on MacOS 13.2. The message is now displayed with the text in color instead of the escaped code.


![Image](https://user-images.githubusercontent.com/31009952/218187351-3373b3e7-cf43-4141-8303-c1fde69bac2e.png)
