### ISSUE TITLE
Visual editor doesn't show the content of the last page of paged tables

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#12430]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Ubuntu Server 22.04 LTS
    R Version       : 4.2.2 Patched

### Steps to reproduce the problem
Execute the code chunk on this qmd document in "Visual" mode and go to the last page on the paged table
````
---
title: "Example"
format: html
editor: visual
---

## Paged table:

```{r}
library(dplyr)

iris %>% 
    group_by(Species) %>% 
    slice_head(n = 5)
```
````
### Describe the problem in detail
![image](https://user-images.githubusercontent.com/14981085/207201668-a81886a5-07f0-44c7-a1a8-006e5d17f67e.png)
The last page on the paged table appears empty even if the footer says it is showing rows 11-15 from 15
### Describe the behavior you expected
I expect to see the missing rows like they appear if a change to "Source" mode
![image](https://user-images.githubusercontent.com/14981085/207201887-fe851218-cc01-415b-ab99-e3bc42966883.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@andresrcs Thanks! I'm unable to reproduce the issue in RStudio Server or RStudio Desktop. What browser and OS are you using to connect to RStudio Server?

**Comment by andresrcs** [comment]
I'm using Google Chrome 108.0.5359.125 64-bit on Windows 10 Pro (19045.2364)

Also, I have updated RStudio Server to 2022.12.0 Build 354 and the problem persists.

**Comment by PreshitaDave** [comment]
@andresrcs Go to the metadata.yml in the posts folder and change freeze:true as freeze:false. That seemed to work for me
