### ISSUE TITLE
Rstudio crashes after ODBC query and copying any text from any pane (e.g. editor)

### ISSUE THREAD

**Issue by dleutnant** [rstudio/rstudio#12432]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2 Build 576
    OS Version      : Win 10 Enterprise
    R Version       : 4.2.0

### Steps to reproduce the problem

First, just execute the following Code.

``` r
library(writexl)

# create dummy excel file with mtcars content
tmpfile <- tempfile()
writexl::write_xlsx(mtcars, tmpfile)

# create connection strings
dbq_string <- paste0("DBQ=", tmpfile)
driver_string <- "Driver={Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)};"
connect_string <- paste0(driver_string, dbq_string)

# create connection object
con <- DBI::dbConnect(odbc::odbc(), .connection_string = connect_string)

# read data
result <- DBI::dbReadTable(con, "Sheet1$")

# just to make sure the query suceeded
head(result)
#>    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> 1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> 2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> 3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> 4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> 5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> 6 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1

# close connection
DBI::dbDisconnect(con)
```

<sup>Created on 2022-12-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.0 (2022-04-22 ucrt)
#>  os       Windows 10 x64 (build 19044)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  German_Germany.utf8
#>  ctype    German_Germany.utf8
#>  tz       Europe/Berlin
#>  date     2022-12-13
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  bit           4.0.5   2022-11-15 [1] CRAN (R 4.2.0)
#>  bit64         4.0.5   2020-08-30 [1] CRAN (R 4.2.0)
#>  blob          1.2.3   2022-04-10 [1] CRAN (R 4.2.0)
#>  cli           3.4.1   2022-09-23 [1] CRAN (R 4.2.1)
#>  DBI           1.1.3   2022-06-18 [1] CRAN (R 4.2.0)
#>  digest        0.6.31  2022-12-11 [1] CRAN (R 4.2.0)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
#>  evaluate      0.18    2022-11-07 [1] CRAN (R 4.2.2)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.2.0)
#>  hms           1.1.2   2022-08-19 [1] CRAN (R 4.2.1)
#>  htmltools     0.5.4   2022-12-07 [1] CRAN (R 4.2.2)
#>  knitr         1.41    2022-11-18 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.1)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
#>  odbc          1.3.3   2021-11-30 [1] CRAN (R 4.2.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
#>  purrr         0.3.5   2022-10-06 [1] CRAN (R 4.2.1)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.1)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.2  2022-11-11 [1] CRAN (R 4.2.0)
#>  Rcpp          1.0.9   2022-07-08 [1] CRAN (R 4.2.1)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.0)
#>  rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.1)
#>  rmarkdown     2.18    2022-11-09 [1] CRAN (R 4.2.2)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.1)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
#>  stringr       1.5.0   2022-12-02 [1] CRAN (R 4.2.2)
#>  styler        1.8.1   2022-11-07 [1] CRAN (R 4.2.2)
#>  vctrs         0.5.1   2022-11-16 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
#>  writexl     * 1.4.1   2022-10-18 [1] CRAN (R 4.2.0)
#>  xfun          0.35    2022-11-16 [1] CRAN (R 4.2.0)
#>  yaml          2.3.6   2022-10-18 [1] CRAN (R 4.2.0)
#> 
#>  [1] C:/Program Files/R/R-4.2.0/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

After executing the code above, just try to copy any text from inside the RStudio panes (editor, console, connection tab...) via Ctrl+C. The result is RStudio crashes (R session aborted, R encountered a fatal Error ...). The copied text however is available via clipboard, but RStudio needs to be restarted.

Hint: I know that there are packages for reading Excel files. Initially I encountered this issue when reading data from an MS Access datbase. For the sake of reproducibility, I'm using the odbc connection in this example for reading data from an Excel file and "luckily" get the same issue.

### Describe the problem in detail.
I think, all information is given above. I'm curious to know whether someone can reproduce this issue.

### Describe the behavior you expected
- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
*[Note: I first had to [download and install software from Microsoft ](https://www.microsoft.com/en-us/download/details.aspx?id=54920)to repeat the example.]*

@dleutnant Thank you for raising this! I'm unable to reproduce the issue, using
- RStudio Desktop 2022.07.2-576 on Windows 11
- RStudio Desktop 2022.12.0-353 on Windows 11

That said, we're currently working on a version of RStudio Desktop using a new framework, Electron. We're hoping that the switchover resolves a number of issues. If you're interested in trying it out the Elsbeth Geranium project 2022.12.0 currently in development, [the RStudio Desktop installers are all Electron-based](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows/). 
 
In addition, there is an option to run it on your machine without installing and replacing your current version. For Windows, download an installer-less build from https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows-xcopy/

**Comment by dleutnant** [comment]
@ronblum Do have any idea, how i can further track down this issue?
