### ISSUE TITLE
R and RStudio will not run after updating to R-4.2.2-arm64.pkg 

### ISSUE THREAD

**Issue by aok-1000** [rstudio/rstudio#12433]
Hi,

I’m having an issue similar to one reported here: https://github.com/rstudio/rstudio/issues/9543. I have a M1 Mac (OS Monterey, 12.6) and I updated my R to version 4.2.2. using R-4.2.2-arm64.pkg link on https://cran.r-project.org. I also updated RStudio to 2022.07.2 Build 576. After doing this, I could no longer use R or RStudio, and receive the following error message:

```{r}
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/username/Library/R/3.x/library/xfun/libs/xfun.so':
  dlopen(/Users/ username /Library/R/3.x/library/xfun/libs/xfun.so, 0x0006): tried: '/Users/ username /Library/R/3.x/library/xfun/libs/xfun.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ username /Library/R/3.x/library/xfun/libs/xfun.so' (no such file), '/Users/ username /Library/R/3.x/library/xfun/libs/xfun.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

However, the following does not indicate I have a conflict of architecture: 
```{r}
> Sys.info()[["machine"]]
[1] "arm64"
> system("arch")
arm64
> system("uname -m")
arm64
```

I’ve tried updating my operating system to OS Ventura 13.0.1, and I downloaded an updated XQuartz (2.8.3), re-downloaded R and RStudio, and still have the same issues.  I’ve been searching through github issue threads and have not been able to solve my problem based on previous posts for similar issues, although I have to admit I am not a software/package developer, so many of the suggestions are extremely esoteric to me. Any suggestions would be helpful. Thank you.

**Comment by kevinushey** [comment]
Did you try to configure your R session to use a custom library path somewhere? The error indicates that you're trying to load an R package from an older R 3.x installation:

> '/Users/username/Library/R/3.x/library/xfun/libs/xfun.so'

These are the default library paths I see in my R installation:

```
$ R -s --vanilla -e '.libPaths()'
[1] "/Users/kevin/Library/R/arm64/4.2/library"
[2] "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library"
```

**Comment by aok-1000** [comment]
I have never tried to configure a custom library path for my R session, although the '/Users/username/Library/R/3.x/library' appears to be the default in Rstudio for downloading packages (if I just look at the "Install packages" option in the GUI menu under the 'Tools' tab in RStudio.  When I used the command that you suggested in the Terminal, I received the following output:

```{r}
$ R -s --vanilla -e '.libPaths()'
[1] "/Users/username/Library/R/3.x/library"                             
[2] "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library"
```
So, it appears there are multiple library paths that aren't compatible.  Do you have ideas on how I can fix this?  

In case it provides you with any additional hints as to what the problem is, when I downloaded a package to the 4.2-arm64/Resources/library, e.g.:

```{r}
install.packages("ggplot2", lib="/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library")
```
I could successfully down the package, but then I received a similar error message as before when I attempt to load that package in a .Rmd notebook in Rstudio:

```{r}
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/username/Library/R/3.x/library/colorspace/libs/colorspace.so':
  dlopen(/Users/username/Library/R/3.x/library/colorspace/libs/colorspace.so, 0x0006): tried: '/Users/username/Library/R/3.x/library/colorspace/libs/colorspace.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/username/Library/R/3.x/library/colorspace/libs/colorspace.so' (no such file), '/Users/username/Library/R/3.x/library/colorspace/libs/colorspace.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
``` 

Thanks again

**Comment by kevinushey** [comment]
In:

```
$ R -s --vanilla -e '.libPaths()'
[1] "/Users/username/Library/R/3.x/library"                             
[2] "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library"
```

The fact that you're seeing `"/Users/username/Library/R/3.x/library"` here is quite surprising to me. It implies that something in your R installation (`etc/Rprofile.site`? `etc/Renviron`?) is incorrectly setting the library path.

Or, perhaps, you have an environment variable like `R_LIBS_USER` set (perhaps in your shell?)

Are you able to share an RStudio diagnostics report? (Help -> Diagnostics -> Write Diagnostics Report)

**Comment by aok-1000** [comment]
Sure, here's the diagnostic report. [diagnostics-report.txt](https://github.com/rstudio/rstudio/files/10233526/diagnostics-report.txt)

**Comment by kevinushey** [comment]
Your `~/.Renviron` has this:

```
R User Environ: /Users/username/.Renviron
--------------------------------------------------
R_LIBS_USER=/Users/username/Library/R/3.x/library
```

You should delete that file.
