### ISSUE TITLE
Git pane not showing changes when path contains non-ASCII characters

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#12448]
### System details

Macbook M1 Pro, MacOS X 13.1 Beta (22C5050e), also reproduced on earlier OS X with M1
git version 2.37.1 (Apple Git-137.1), also reproduced on earlier git on a different machine
Version 2023.03.0-daily+3 (2023.03.0-daily+3)

### Steps to reproduce the problem

Create an RStudio project and a git repository inside a directory named along the following lines: `/Users/petr/csandbox/msmt/repoš`

### Describe the problem in detail

No changes are detected and shown in the Git pane when the path to the repository contains non-ASCII characters.

The bug manifests any time there is any non-ASCII character even further up in the path, and disappears when the characted is replaced with an ASCII character.

Other git GUIs and running `git status` in terminal detects the changes.

### Describe the behavior you expected

I expected changes to be shows in the Git pane.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@petrbouchal Thank you for raising this! Did it work in previous versions of RStudio?

**Comment by petrbouchal** [comment]
Yes, this problem manifests on the current stable version as well as the daily, and probably a slightly (~3 mos?) older version which I now cannot track down specifically.
