### ISSUE TITLE
(Ctrl + Enter) and (Run the current line) fails with specific outline 

### ISSUE THREAD

**Issue by pricer-landcare** [rstudio/rstudio#12440]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.2 Build 576
    OS Version      :  Windows 10 Enterprise  19044.2251
    R Version       :  4.1.3

### Steps to reproduce the problem
Use either Ctrl+Enter or the run button to run the current line in each of the following function definitions

#This doesn't run
a1 <- function()
{
  #loop----
  for ( i in 1:10)
  {
    #i----    
  }
  #!!!lands here!!!
}

a2 <- function()
{
  for ( i in 1:10)  
  {
  }
}
#!!!lands herea!!!

#this does run
b <- function(){
  #loop----
  for ( i in 1:10)
  {
    #i----    
  }
}
#!!!lands here!!!

### Describe the problem in detail
The run process stops at the line commented "Lands Here" in each of the cases.

a1) does not fully parset he function
a2) fully parses
b) fully parses

In the first instance that is not the complete function definition.

(selecting and running the code works perfectly ok)

### Describe the behavior you expected
I would expect the code to run to the closing "}" of the function definition in each case.  Took me days to figure out the cause.

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@pricer-landcare Thank you for raising this! I can reproduce the problem in RStudio Desktop 2022.07.2+576 and 2022.12.0+353 on MacOS 13.1. We'll review this as we continue development of RStudio.
