### ISSUE TITLE
R session error/crash running "long <- as.character(1:1E4)" in the console

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#12444]
### System details

    RStudio Edition :  Server and workbench
    RStudio Version : 2023.03.0-daily+25
    OS Version      : ubuntu20
    R Version       : 4.1.3

### Automation notes:

Failing test: https://build.posit.it/job/IDE/job/qa-opensource-automation/1687/testReport/rstudio_server_pro.tests.test_Console/TestConsolePane/test_limit_visible_console_output/
**Last passing build**:2023.03.0-daily+24
**First failure**: 2023.03.0-daily+25

### Steps to reproduce the problem

1. Enter "long <- as.character(1:1E4)" into the console and click enter.
2. Click the enter key again if you get no response.

### Describe the problem in detail
User gets attached error below.
![Screen Shot 2022-12-15 at 7 14 32 AM](https://user-images.githubusercontent.com/1482677/207886559-6f83d51a-c92e-4f54-b6d5-3176087a0fd9.png)

![rCrash](https://user-images.githubusercontent.com/1482677/207890562-e5bc9bf1-5748-4a78-bcfb-0db9bcaec8b1.gif)

### Describe the behavior you expected
No issues or errors and I would expect the environment tab to fill in with the data like below.
![Screen Shot 2022-12-15 at 7 46 45 AM](https://user-images.githubusercontent.com/1482677/207890844-666f24e8-e172-4159-9b19-1c2a36066c8b.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
This is probably fixed by https://github.com/rstudio/rstudio/pull/12445
