### ISSUE TITLE
Valid LaTeX in the RMarkdown header causes visual editor to malfunction

### ISSUE THREAD

**Issue by stephenturner** [rstudio/rstudio#12446]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2 build 576
    OS Version      : MacOS 12.3
    R Version       : 4.2.2

### Steps to reproduce the problem

Put the latex snippet below in the Rmarkdown header and Rmarkdown can't use visual mode.

### Describe the problem in detail

I use the visual editor to insert citations (would be great if I could do this one day without the visual editor, working in source mode). I also want to automatically wrap long lines of code in the PDF output rather than having them fall off the edge of the page, and I use the embedded LaTeX in the Rmd header as shown below to achieve this.

````yaml
---
title: "My title"
author: "Stephen Turner"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document: 
    fig_caption: yes
    toc: yes
header-includes:
- |
  ```{=latex}
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
    breaksymbolleft={}, 
    showspaces = false,
    showtabs = false,
    breaklines,
    commandchars=\\\{\}
  }
  ```
---
````

However, when I do this, I can't use the visual editor ("Unable to activate visual mode (unsupported front matter format or non-top-level YAML block)"). There's nothing actually wrong with the front matter. The PDF compiles just fine. 

![image](https://user-images.githubusercontent.com/460076/207954943-d0d0a147-c987-43ee-a57e-114a131bce1b.png)

Is there another way to achieve what I'm trying to do here in a way that doesn't fool the visual editor into thinking something's wrong?

### Describe the behavior you expected

I expected the RStudio Visual editor to work as normal. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by stephenturner** [comment]
FWIW -- I posted in the RStudio community awhile back to solicit ideas about other ways to handle what I'm trying to do here, but I haven't gotten any response. Maybe there's a better way, but seems like an RStudio bug regardless.

**Comment by ronblum** [comment]
@stephenturner Thank you for raising the issue! I can reproduce in RStudio Desktop 2022.07.2+576 and 2022.12.0+353 on MacOS 13.1.

@dragonstyle I tagged this as a visual editor bug, but do you know if there's a way to make this work, or is this a bug?

**Comment by dragonstyle** [comment]
I'm not 100% sure what is causing the visual editor issues with the raw block in the header-includes, but that definitely appears to be the issue. Since the target output is PDF anyhow, I believe that a workaround would be to exclude the raw block declaration like so:

```markdown
---
title: "My title"
author: "Stephen Turner"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document: 
    fig_caption: yes
    toc: yes
header-includes:
  - |
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
---
```
