### ISSUE TITLE
Ubuntu (jammy) tarball download for electron (2022.12.0-353) does not work. 

### ISSUE THREAD

**Issue by dat-linux** [rstudio/rstudio#12451]
After downloading and unzipping https://download1.rstudio.org/electron/jammy/amd64/rstudio-2022.12.0-353-amd64-debian.tar.gz

Attempt to run "rstudio" inside the folder, an error occurs:

```
~/Downloads/rstudio-2022.12.0+353/rstudio 
**[160719:1217/113906.287093:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
Trace/breakpoint trap (core dumped)**
```

It then proceeds to convert the "rstudio" binary file into an empty file. Which renders it useless.

![screen](https://user-images.githubusercontent.com/99078210/208237958-c4d9e797-deb5-4c73-8b08-10449a40ac60.jpg)

I'm running Ubuntu 22.04 (jammy) on bare metal, with all system updates.

**Comment by dat-linux** [comment]
Same thing occurs for the **Ubuntu 18+/Debian 10+**  version.

**Comment by ronblum** [comment]
@dat-linux I see that you closed the issue—does this mean that you got it to work?

**Comment by dat-linux** [comment]
It's a bit of a glitch. If you run the downloaded binary directly from its directory (./rstudio) then the problem I found occurs. Maybe a conflict with an existing rstudio in the path.
But if you call it from outside the directory (bin/rstudio) it launches correctly.
