### ISSUE TITLE
New project from git: stopping at "could not find UI helper 'GitHub.UI'"

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#12460]
### System details

    RStudio Edition :Desktop
    RStudio Version : RStudio 2022.07.2+576 "Spotted Wakerobin" Release  e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Windows 10
    R Version       : 4.2.2

### Steps to reproduce the problem

Fresh install of RStudio in a windows 10.
Try to clone a repository via the new project from version control > git > and use a repository from https://github.com/ 

### Describe the problem in detail

The cloning of the project stops after creating a folder for the new project but doesn't continue clonning or exists.
The new folder is empty and no new project is opened.
In the cloning window it appears:

```
>>> C:/Users/USER/AppData/Local/Programs/Git/bin/git.exe clone --progress https://github.com/llrs/FOLDER.git FOLDER
Cloning into 'FOLDER'...
warning: could not find UI helper 'GitHub.UI'
```

Git is installed and I push and pull from other respositories to/from github.
It doesn't seem to be a network (or proxy) problem.
I couldn't test in the latest Rstudio 2022.12 (pending IT approval of the new version)

### Describe the behavior you expected

Either an informative error (ie: A message about, please install X or Y) or no warning at all and a getting a functional project. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@llrs Thank you for raising this!

1. Does this occur with both public and private repositories?
2. I tried using the example above, but I don't have access to github.com/llrs/FOLDER. Is this a mask of a private repository?
3. If it's a private repository, are you using a personal access token? If so, do you know if it works with SSH authentication?

Thanks!

**Comment by llrs** [comment]
Hi Ron, the url is masked from a private repository, but it works with a public repository.
I haven't set up (yet) a personal access token (neither was I asked to input one). 
I don't know if I will configure via SSH authentication as this computer is somewhat temporary, (but I can try it once cleared with IT).

Thanks for the quick reply

**Comment by llrs** [comment]
I set a PAT via `gitcreds::gitcreds_set()` and I could successfully create the new project from Github (Via https). Thanks for the pointers @ronblum !

It would be helpful if RStudio could produce a meaningful message, for those of us that forget adding a PAT.
