### ISSUE TITLE
"The terminal is currently busy" when running Build

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#12464]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.03.0-daily+31 (2023.03.0-daily+31)
    OS Version      : 13.2 (a) Beta (22D7750270d)
    R Version       :  R version 4.2.1 (2022-06-23)

### Steps to reproduce the problem

1. Set up a custom script as the build command in RStudio such that the `.Rproj` has these lines:

```
BuildType: Custom
CustomScriptPath: run.R
```

2. Run a command in the terminal that will block it, e.g. `quarto preview`
3. Hit Cmd+Option+B or click the Build All command in the Build pane

### Describe the problem in detail

An alert appears with the text "The terminal is currently busy. Terminal jobs will be terminated. Are you sure?". When I hit yes, the build command runs and the terminal job is not terminated.

Possibly related to #7112

### Describe the behavior you expected

I expect there to be no interaction between the build pane and the terminal.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@petrbouchal Thank you for raising this! Is this new behavior in RStudio Desktop 2023.03 Cherry Blossom, or was this an issue in previous versions, as well?

**Comment by petrbouchal** [comment]
Thanks for following up. 

I think this has been happening for a while but I don't have a way of finding out when it started happening.

**Comment by ronblum** [comment]
Thanks! I can reproduce it on MacOS 13.2 using both RStudio Desktop  2022.07.2+576 and 2022.12.0+353.

**Comment by petrbouchal** [comment]
This is still an issue at least for custom-script build jobs.

**Comment by HowlingHollow** [comment]
Hello, I am only learning R, but I am having this issue with RStudio Desktop. From research, it seems that this is an ongoing and recurring issue throughout many updates. Is this still being actively worked on?

If it helps:
➜ uname -a
Linux pop 6.6.10-76060610-generic #202401051437~1704728131~22.04~24d69e2 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux

Terminal is not actually busy, it can operate fine. It just gives a popup on close, and stop button or CTRL+C does not have an effect on the busy status.
