### ISSUE TITLE
Python interpreter in system is not available

### ISSUE THREAD

**Issue by Sherry520** [rstudio/rstudio#12461]
### System details

    RStudio Edition : 
    RStudio Version : 2022.12.0+353 
    OS Version      : Windows 10 21H2 19044.2251
    R Version       : 4.1.3

### Steps to reproduce the problem
Rstudio --> Tools --> Globale Options --> Python --> Select
### Describe the problem in detail
I have installed python2.7 from https://www.python.org on my computer and add installation path "D:\Software\Python27" to Path Variable.When I want to use python in Rstudio,I can't find Python. It shows None available.
![image](https://user-images.githubusercontent.com/22561797/208427800-5bef5019-5053-4dd2-b56a-b41720f79914.png)
And I have installed the "reticulate" by install.packages("reticulate"). If I type .rs.python.findPythonInterpreters(),it showed something as follows:
> .rs.python.findPythonInterpreters()
$python_interpreters
$python_interpreters[[1]]
$python_interpreters[[1]]$path
[1] "D:/Software/Python27/python.exe"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[1]]$type
[1] "system"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[1]]$version
[1] "2.7.18"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[1]]$description
[1] "2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[1]]$valid
[1] TRUE
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[1]]$reason
NULL

$python_interpreters[[2]]
$python_interpreters[[2]]$path
[1] "D:/Software/Python27/python.exe"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[2]]$type
[1] "system"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[2]]$version
[1] "2.7.18"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[2]]$description
[1] "2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]"
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[2]]$valid
[1] TRUE
attr(,"class")
[1] "rs.scalar"

$python_interpreters[[2]]$reason
NULL

$default_interpreter
[1] ""
attr(,"class")
[1] "rs.scalar"
### Describe the behavior you expected
I want to see Python in Rstudio as described in "Using Python with the RStudio IDE":
![image](https://user-images.githubusercontent.com/22561797/208429011-ef26ee5b-e16d-419e-ac72-643208ec1157.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Sherry520 Thank you for raising this! I believe that this because [Python 2 is no longer supported](https://www.python.org/doc/sunset-python-2/). @timtmok is this correct?

**Comment by ronblum** [comment]
Oops, I asked the wrong person. @jgutman is the above correct?

**Comment by jgutman** [comment]
@Sherry520 could you please report your version of `reticulate`?

**Comment by Sherry520** [comment]
@jgutman reticulate version: 1.26
