### ISSUE TITLE
Data viewer's "Show in new window" results in empty window

### ISSUE THREAD

**Issue by uhkeller** [rstudio/rstudio#12468]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353 and  2023.03.0-daily+31
    OS Version      : macOS 12.6.2 (arm64)
    R Version       : 4.2.2 (arm64)

### Steps to reproduce the problem

1. Open RStudio.
2. Type `View(iris)`.
3. In the data viewer pane, click the "Show in new window" button.
4. In the pop-up window showing the data, click the "Return to main window" button.
5. In the data viewer pane, click the "Show in new window" button again. The window comes up empty.

https://user-images.githubusercontent.com/2323704/208664505-fce4aade-351a-416e-aa38-d9cfd24468b2.mov

### Describe the problem in detail

All but the first clicks on "Show in new window" in the data viewer pane result in an empty window.

### Describe the behavior you expected

I expected the window to no be empty, but to show the data (like it does the first time the button is clicked).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@uhkeller Thank you for raising this! I can reproduce this in RStudio Desktop 2022.12.0+353 on MacOS 13.2 and Ubuntu 22.04. It works in version 2022.07.2+576

Triage: Marking for Cherry Blossom as a regression.

**Comment by johninpdx** [comment]
Also occurs under Windows 10. Same steps as per @uhkeller to reproduce.

**Comment by kalcan83** [comment]
I'm having the same issue on RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Comment by nicholascarey** [comment]
Also seeing this on RStudio Desktop 2022.12.0+353 on MacOS 13.1. 

Even removing the data frame and recreating it does not fix it. Only a quit and restart, and even then not every time.

**Comment by kevinrue** [comment]
FWIW I'm having that issue with Shiny apps too.

Workaround for now: 'Open in browser' does work (still talking about the shiny apps).

**Comment by zjph602xtc** [comment]
I want to report the same problem.

**Comment by CaspervdGeer** [comment]
Same problem for me, has been like this for a few weeks.

"Elsbeth Geranium" Release (7d165dcf, 2022-12-03) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Comment by jonocarroll** [comment]
This can be reproduced in the current daily build

2023.03.0 Build 277

"Cherry Blossom" Daily (3d5918dc, 2023-01-27) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0-daily+277 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

**Comment by sharon-wang** [comment]
I'm seeing `desktop_allow_navigation: Error invoking remote method 'desktop_allow_navigation': TypeError: Object has been destroyed` in the console output of the empty new window, after reproducing the issue using the steps in the issue description.

The same error message is in https://github.com/rstudio/rstudio/issues/12569, but I'm not sure if it's the same underlying issue.

**Comment by jonvanausdeln** [comment]
Verified with 2023.03.0-daily+316 Desktop
Windows 11, MacOS 12.6

The new window shows the data every time as expected, even after "Return to Main Window" several times.

**Comment by CaspervdGeer** [comment]
> Verified with 2023.03.0-daily+316 Desktop Windows 11, MacOS 12.6
> 
> The new window shows the data every time as expected, even after "Return to Main Window" several times.

Hi @jonvanausdeln and @sharon-wang,

This thread has been closed? Meaning that the issue should be solved?

I am still having this issue as per OP's description.

Thnx!
C

**Comment by sharon-wang** [comment]
> @CaspervdGeer It's fixed in the [daily builds](https://dailies.rstudio.com/) if you're courageous and hopefully it will be fixed in the next release slated for March if I'm not mistaken.

@CaspervdGeer -- @uhkeller's spot on here :) If you're still having this issue even with the latest daily builds, then we'll need to dig deeper!

**Comment by johninpdx** [comment]
I have installed the daily build from yesterday (.318) and, upon a quick test, the problem appears to be solved…unless there are other circumstances than I’d originally identified that cause it. So hopefully all good…but @CaspervdGeer, do post if you’ve identified such alternative circumstances.

Thanks to Sharon and  Jon!
~jl

**Comment by ronblum** [comment]
@jwojcikDEC This is a bug in Elsbeth Geranium. It's fixed in Cherry Blossom, which is still in development. If you'd like to try it out, it's available on [the dailies page](https://dailies.rstudio.com/). However, please note that these builds are only for testing purposes, not production.

**Comment by jwojcikDEC** [comment]
> @jwojcikDEC This is a bug in Elsbeth Geranium. It's fixed in Cherry Blossom, which is still in development. If you'd like to try it out, it's available on [the dailies page](https://dailies.rstudio.com/). However, please note that these builds are only for testing purposes, not production.

@ronblum thank you for the link. I understand the dailies are for testing purposes, but I am curious about the build that my coworker is using which doesn't give him the bug. Here is a link to the download page for that specific build: https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/windows/2022-07-2-576/

Where would the "stable" build equivalent to this link be (assuming it's stable since my coworker uses it everyday).

**Comment by datakid** [comment]
Seen in ticket #90460

**Comment by petermott** [comment]
I have this issue in RStudio 2023.12.0+369 "Ocean Storm" , R version 4.3.2, with Windows 11 Home. Also the popout window for help does not open 
![image_2024-01-07_115009456](https://github.com/rstudio/rstudio/assets/7861523/b99b2099-7481-4e76-a4e8-ff55291e2b7d)
