### ISSUE TITLE
Cannot change directory to a folder outside home directory (CentOS7)

### ISSUE THREAD

**Issue by katgit** [rstudio/rstudio#12473]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0-353
    OS Version      : CentOS7
    R Version       : 4.2.1

### Steps to reproduce the problem
Start RStudio:
rstudio --no-sandbox
Change directory using Session -> Set Working Directory -> Choose Directory

### Describe the problem in detail
If when the Rstudio starts, current directory is user's home directory ("~"), then it is impossible to change directory to the root folder "/", where the users can navigate to their project directories.

### Describe the behavior you expected
In the previous versions of RStudio, after selecting "Choose Directory" menu item, and clicking "..." in the pop-up window, we could type "/" and then select the desired path as the subdirectory of the "/" directory. Now, we can only select subdirectories of the home directory ("~").

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@katgit Thank you for raising this! We've made some architectural changes which affect some behavior. Try out the following: Go to <kbd>Global Options -> Advanced</kbd> and check the box for <kbd>Use native file and message dialog boxes</kbd>. Does this return the behavior that you're looking for?

**Comment by katgit** [comment]
Hi @ronblum,  I checked "use native file" box. Now, when I use "Choose Directory", the pop-up window has a different style. It no longer has three dots at the right-top corner. This new pop-up window allows me to navigate to the root-level directory.
Thank you!
Is there a way for us to set this option system-wide, so we do not need to communicate this fix to many hundreds of users on our system.

Also: We updated our RStudio Server as well to the same new 2022.12.0-353 version. But the RServer does not have the same change. Will this change be introduce to the RStudio Server as well?
Thank you and Happy New Year!

**Comment by sklayn** [comment]
I had the same issue with RStudio Desktop v. 2022.12.0 Build 353, on Linux Mint 20. When starting a new project, I was unable to create a project anywhere but the home directory, and navigating to and opening existing files from the "Open file" menu was also not possible. This didn't affect already-existing projects outside the home directory, which was why I only noticed just now..  @ronblum 's solution worked for me too!

**Comment by j-p-courneya** [comment]
Hi im on Rstudio Desktop 2023.03.0 Build 386, on Ubuntu 22.04.2 LTS. When i clicked the "..." in the files pane to navigate to mounted volumes i was unable to navigate outside of the home directory. @ronblum solution fixed the issue for me. Thanks!

**Comment by gtritchie** [comment]
@katgit asked (a while ago, sorry for the delayed response):

> Is there a way for us to set this option system-wide, so we do not need to communicate this fix to many hundreds of users on our system.

Yes. To select "save and restore environment variables" by default for all users on a system, create a file named rstudio-prefs.json containing

```json
{
     "native_file_dialogs": true
}
```

Linux and macOS, save the file at `/etc/rstudio/rstudio-prefs.json` and on Windows to `%PROGRAMDATA%\RStudio\rstudio-prefs.json`.

If you want to set defaults for multiple options, use a comma after each item (but not the last one).

You can figure out preference names by changing them in the RStudio UI and then examining the user preferences file. That is normally in `~/.config/rstudio/rstudio-prefs.json` on Linux and Mac, and `%APPDATA%\RStudio\rstudio-prefs.json` on Windows.

You can also change where these files live using environment variables: see https://docs.posit.co/ide/desktop-pro/settings/settings.html for more details.

More documentation on these preferences is at: https://docs.posit.co/ide/server-pro/reference/session_user_settings.html. 

That document covers RStudio Server Pro, so not all settings will apply to open-source RStudio Server or Desktop, but most will.

**Comment by chuxinyuan** [comment]
when folder outside home directory, There is no git button in the upper right corner.

**Comment by billybarc** [comment]
I'm experiencing this problem too under Ubuntu 18.04.

```
RStudio Edition : Desktop
RStudio Version : 2023.09.1 Build 494
OS Version      : Ubuntu 18.04.6 LTS
R Version       : 4.3.1
```

The Go To Folder dialog opens, but clicking the three dots just opens another version of the dialog and I'm unable to navigate outside of my home directory.

@ronblum's solution also worked for me by switching to my system's file dialog (Caja).

**Comment by gtritchie** [comment]
FYI, we show the non-native file/folder dialogs on Linux by default due to a long-standing Electron bug where these would often open behind the main window. Unfortunately, that issue is still active in Electron, but if and when they fix it, we'll switch RStudio's behaviour to showing the native dialogs by default on Linux.

More here: https://github.com/rstudio/rstudio/issues/11100
Electron issue here: https://github.com/electron/electron/issues/32857

**Comment by gtritchie** [comment]
The issue with the "..." not working correctly in the web-based file dialogs (used on Linux RStudio desktop by default) was tracked separately and is fixed in the next release ("Cranberry Hibiscus"). https://github.com/rstudio/rstudio/issues/14501
