### ISSUE TITLE
RStudio fails to start; "Error Starting R"

### ISSUE THREAD

**Issue by csmtx** [rstudio/rstudio#12476]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353 "Elsbeth Geranium " (7d165dcf, 2022-12-03) for Windows ; Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
    OS Version      : Windows 11
    R Version       : 4.2.2 (latest)

### Steps to reproduce the problem

1. Start RStudio. (I realize this will not reproduce the problem for you; it does for me.)

### Describe the problem in detail

When starting RStudio, RStudio displays an empty window with a spinner. Eventually, a message appears, stating that "R is taking longer to start than usual" and offering two buttons, "Reload" and "Terminate R". Clicking on "Reload" displays an additional "Reloading..." message but otherwise does nothing. Clicking on "Terminate R" initially appears to do nothing but eventually displays an error page ("Error Starting R"). Here is the relevant information from that page (excluding what is already listed above):

#### Error message

[No error available]

#### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

#### Logs

*C:/Users/<user>/AppData/Local/RStudio/log/rsession-<user>.log*

```
2022-12-21T10:11:01.469126Z [rsession-<user>] WARNING Abort requested; LOGGED FROM: bool __cdecl rstudio::session::connection::checkForAbort(class rstudio_boost::shared_ptr<class rstudio::session::HttpConnection>,const class rstudio_boost::function<void __cdecl(void)>) C:\Users\jenkins\workspace\ide\open-source-pipeline\elsbeth-geranium\src\cpp\session\http\SessionHttpConnectionUtils.cpp:135
2022-12-21T10:25:33.645031Z [rsession-<user>] WARNING Abort requested; LOGGED FROM: bool __cdecl rstudio::session::connection::checkForAbort(class rstudio_boost::shared_ptr<class rstudio::session::HttpConnection>,const class rstudio_boost::function<void __cdecl(void)>) C:\Users\jenkins\workspace\ide\open-source-pipeline\elsbeth-geranium\src\cpp\session\http\SessionHttpConnectionUtils.cpp:135
2022-12-21T10:25:33.645031Z [rsession-<user>] WARNING Abort requested; LOGGED FROM: bool __cdecl rstudio::session::connection::checkForAbort(class rstudio_boost::shared_ptr<class rstudio::session::HttpConnection>,const class rstudio_boost::function<void __cdecl(void)>) C:\Users\jenkins\workspace\ide\open-source-pipeline\elsbeth-geranium\src\cpp\session\http\SessionHttpConnectionUtils.cpp:135

```

### Describe the behavior you expected

Both RStudio and R start normally.

### Additional information

1. Using R without RStudio (RGui) works fine; the problem is not on R's side. 
2. There are no running rsession processes.

### Checkboxes

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by csmtx** [comment]
FWIW a reboot fixed this, so unless and until it happens again this is not an urgent issue on my side.

**Comment by ronblum** [comment]
@csmtx Thank you for both raising the problem and providing the update! I'll close this issue, but if you run into this problem again, please let us know.

**Comment by Nasser-R** [comment]
@csmtx Hi - Could you please elaborate more on how you dealt with this issue? I installed the 4.2.2 version of R and updated R studio to the latest version - I am, now, experiencing a similar problem to the one you declared - Rsrudio fails to launch :::
#########
errormsg: Error in .requirePackage(package) :
unable to find required package ‘mapview’
]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::r::exec::`anonymous-namespace'::evaluateExpressionsUnsafe(struct SEXPREC *,struct SEXPREC *,struct SEXPREC **,class rstudio::r::sexp::Protect *,enum rstudio::r::exec::`anonymous-namespace'::EvalType) src/cpp/r/RExec.cpp:198; LOGGED FROM: class rstudio::core::json::Value __cdecl rstudio::session::modules::environment::varToJson(struct SEXPREC *,const struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct SEXPREC *> &) C:\Users\jenkins\workspace\ide\open-source-pipeline\elsbeth-geranium\src\cpp\session\modules\environment\EnvironmentUtils.cpp:223
########

- Many thanks in advance!
