### ISSUE TITLE
Cannot open Rproj from terminal (ubuntu 20.04)

### ISSUE THREAD

**Issue by giabaio** [rstudio/rstudio#12475]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@giabaio Thank you for raising the issue! How are you tying to open Rproj from the the terminal? Also, can you please provide the system information so that we can try to reproduce the issue?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by giabaio** [comment]
Sorry about this --- I was opening an issue, but as of this morning the problem seems to have gone away... I thought that the issue had actually not been opened! If I experience the problem again, I'll make sure to give all the relevant details to help you help me debug!

Thanks

**Comment by ronblum** [comment]
@giabaio Thanks for the update! And definitely, please let us know if you run into the issue again.

**Comment by giabaio** [comment]
Sorry --- I'm having to open this again... I've tried to open a different project from terminal and it fails.

So here are some basic info:
RStudio Edition : Desktop
RStudio Version :  rstudio-2022.12.0-353
OS Version      :  Linux 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 20.04)
R Version       :  4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"

If I open `rstudio` either by clicking on the shortcut from my menubar or by typing on my terminal
```
rstudio &
```
then it does open properly (though, incidentally, the `rstudio` menubar showing "File", "Code", etc, has disappeared!).

If on the other hand I try to open a project, say with
```
cd PATH_TO_MY_PROJECT
rstudio NAME_TO_MY_PROJECT.Rproj &
```
then I get this error
![image](https://user-images.githubusercontent.com/8723145/209128213-7e8c63e9-052f-479e-95bf-00088e20696c.png)

I'm not quite sure why... 

I hope this gives enough information to help, but please let me know if not!
Thank you for your help!

**Comment by giabaio** [comment]
Sorry --- I'm having to open this again... I've tried to open a different project from terminal and it fails.

So here are some basic info:
RStudio Edition : Desktop
RStudio Version :  rstudio-2022.12.0-353
OS Version      :  Linux 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 20.04)
R Version       :  4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"

If I open `rstudio` either by clicking on the shortcut from my menubar or by typing on my terminal
```
rstudio &
```
then it does open properly (though, incidentally, the `rstudio` menubar showing "File", "Code", etc, has disappeared!).

If on the other hand I try to open a project, say with
```
cd PATH_TO_MY_PROJECT
rstudio NAME_TO_MY_PROJECT.Rproj &
```
then I get this error
![image](https://user-images.githubusercontent.com/8723145/209128213-7e8c63e9-052f-479e-95bf-00088e20696c.png)

I'm not quite sure why... 

I hope this gives enough information to help, but please let me know if not!
Thank you for your help!

**Comment by giabaio** [comment]
PS: I have also tried downgrading to the previous `rstudio` version --- now opening projects from terminal *does* work, but I'm still missing the menu bar (weird...). I've not changed any underlying package in my Ubuntu in the last few days...
