### ISSUE TITLE
Upgrade to Electron v22 breaks at least some modals

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#12487]
RStudio was upgraded to Electron 22.0.0 in #12418, which became available in RStudio version [2023.03.0-daily+14](https://dailies.rstudio.com/version/2023.03.0-daily+14). This broke at least one modal (the choose R modal in Windows). 

In [2023.03.0-daily+13](https://dailies.rstudio.com/version/2023.03.0-daily+13):
<img width="388" alt="image" src="https://user-images.githubusercontent.com/7817881/209030778-f7615848-133f-4681-84f8-870e7f898537.png">

In [2023.03.0-daily+14](https://dailies.rstudio.com/version/2023.03.0-daily+14):
![image](https://user-images.githubusercontent.com/7817881/209030757-a1d64edb-1745-4722-aeb0-1b36f408233f.png)

I don't think there were any other changes between these 2 builds. I'm not sure if any other UI modals have been affected.

**Comment by jgutman** [comment]
Moving this back into in progress to see if it's possible to refactor instead of turning on the node integration

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0-daily+340 Desktop
Windows11, MacOS 12.6

Modal appears and works as expected
