### ISSUE TITLE
rstudio fails to open projects using relative path from command line on Ubuntu 22

### ISSUE THREAD

**Issue by pbreheny** [rstudio/rstudio#12495]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353
    OS Version      : Ubuntu 22.04.1 LTS
    R Version       : 4.2.2 Patched (2022-12-14 r83491)

### Steps to reproduce the problem

Opening a project directly from the command line, as in:
```bash
rstudio myproject.Rproj
```
fails every time, every project (rstudio doesn't open, get "Error Starting R" page).

### Describe the problem in detail

Opening rstudio is fine. Opening rstudio, then opening a project: also fine. The problem only arises when opening a project directly from the command line. Interestingly, if you supply the full absolute path, it seems to work fine:

```bash
rstudio /absolute/path/to/project/myproject.Rproj
```

 Here is a copy of the problem report:

### RStudio Version

RStudio 2022.12.0+353 "Elsbeth Geranium " (7d165dcf, 2022-12-03) for Ubuntu Jammy

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*/iahome/p/pb/pbreheny/.local/share/rstudio/log/rsession-pbreheny.log*

```
2022-12-22T22:34:57.052895Z [rsession-pbreheny] ERROR system error 2 (No such file or directory); OCCURRED AT rstudio::core::Error rstudio::core::FilePath::getChildren(std::vector<rstudio::core::FilePath>&) const src/cpp/shared_core/FilePath.cpp:931; LOGGED FROM: rstudio::core::Error rstudio::session::projects::ProjectContext::startup(const rstudio::core::FilePath&, std::string*) src/cpp/session/projects/SessionProjectContext.cpp:268
2022-12-22T22:34:57.053621Z [rsession-pbreheny] ERROR system error 2 (No such file or directory) [path: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::makeCurrentPath(bool) const src/cpp/shared_core/FilePath.cpp:1400; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2255
2022-12-22T22:34:57.053621Z [rsession-pbreheny] ERROR system error 2 (No such file or directory) [path: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::makeCurrentPath(bool) const src/cpp/shared_core/FilePath.cpp:1400; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2255

```

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by evolozzy** [comment]
I tried to recreate the problem, here are my results.

System details
```
RStudio Edition : Desktop
RStudio Version : RStudio 2022.12.0+353
OS Version      : Ubuntu 22.04.1 LTS
R Version       : 4.2.2 Patched (2022-11-10 r83330)
```

Test 1: Using path from home folder. RStudio aborted session, restarted
```
rstudio  path/from/home/folder/some.Rproj
```

Test 2: Using absolute path. Successfully opened session
```
rstudio /absolute/path/to/proj/some.Rproj
```

Test 3: Using tilde for instead of home. Successfully opened session
```
rstudio ~/path/to/proj/some.Rproj
```

I hope this helps. 

P.S. For avoiding some other errors I have an alias set for running `rstudio`  `alias rstudio='rstudio --gpu-disabled'` I have been having some issues with some of the electron apps and to solve that I also set and export `LIBVA_DRIVER_NAME` manually, in my case it is set to `intel`.

**Comment by ronblum** [comment]
Thank you both for raising this and providing the info! I get a failure with RStudio Desktop 2022.12.0+353 on Ubuntu 22.04, though it's a little different: I get the following error repeated many times in the console:
```
[15789:1230/103637.935805:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
```

RStudio opens, but not in a project, and this popup appears:
<img width="371" alt="cmd_line_proj" src="https://user-images.githubusercontent.com/31009952/210087578-5d0e50ff-1bb3-430d-ae83-801f49ed1fe9.png">

On MacOS 13.2, I get the following message in the console:
```
objc[16140]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5c9be0e0) and /Applications/RStudio-2022.12.0-353.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10785fce0). One of the two will be used. Which one is undefined.
```

RStudio opens, but not in a project, and this popup appears:
<img width="248" alt="macos_popup" src="https://user-images.githubusercontent.com/31009952/210088092-ab60a249-af72-4beb-95f3-fae6ad8ca977.png">

Any which way, this worked correctly previously, in version 2022.07.2+576.

Triage: This is a regression.

**Comment by dmkaplan2000** [comment]
I have the same issue as @pbreheny on two different Ubuntu 20.04.5 LTS installations.

**Comment by sgrubsmyon** [comment]
I am experiencing the same issueas @pbreheny, with the same workaround of using `rstudio $PWD/myproject.Rproj` working. I am on an Ubuntu 22.04.1 LTS system using R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid".

**Comment by sgrubsmyon** [comment]
More convenient workaround: Create a minimal shell script in `~/bin`:

```
$ cat ~/bin/rstudio 
#!/bin/bash

/usr/bin/rstudio $PWD/$1
$ chmod +x ~/bin/rstudio
```

**Comment by dmkaplan2000** [comment]
It seems to me that there may be lots of use cases where this may not behave as expected. For example, if you call `rstudio` without an argument or you call `rstudio` with a fully qualified path.

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2023.05.0-daily+180
Windows 11, Ubuntu 22

Tested several pathing options including paths with spaces and usernames with unicode.  All opened as expected.
