### ISSUE TITLE
Assignment operator shortcut (Alt+-) stopped working in RStudio 2022.12.0

### ISSUE THREAD

**Issue by Token42** [rstudio/rstudio#12506]
I recently updated my Desktop RStudio to the latest version, full description follows:

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

and I run R 4.2.1. 

The default shortcut for the assignment operator <- (Alt+-) is no longer working. When I manually change it to something else, for example Al+B, it works just fine. But would rather solve the issue, as I got ussed to the default shortcut. 

I ran out of solution ideas, so I am turning to the masters of GitHub for help. 
Any help is greatly appreciated! Thanks.

NOTE:
When pressing Alt on its own, it selects "File" tab at the top left, which then blocks any changes in the script itself. That might be part of the issue, but I still have no solution.

**Comment by ronblum** [comment]
@Token42 Thank you for raising this! What keyboard layout are you using? This might be the same problem as #12457 which occurs with non-US QERTY keyboards.

**Comment by Token42** [comment]
Thanks, this actually helped! I was actually using Czech and UK QWERTY keyboard, those do not work. But for some reason Czech QWERTZ works fine. I'll mess around with the keyboard settings a bit more, thank you!

**Comment by ronblum** [comment]
@Token42 Thank you for checking this! I've added your findings to #12457, and closing this as a duplicate.
