### ISSUE TITLE
Parens/Quotes insertion cancels selection

### ISSUE THREAD

**Issue by mertgoksel** [rstudio/rstudio#12502]
Whenever i click "(" to encapsulate the selected string to input it into a function i have to move my cursor to the start because my selection wont stay intact and my cursor will be moved to one right. I want the behaviour to be like vs code where selection stays intact after encapsulation so i just press 1 left button to go where i type the function.

**Comment by ronblum** [comment]
@mertgoksel Thank you for raising this! Can you provide a simple example? I'm not sure what I'm doing is the same as you. When I type something like ```x <- function(```, the closing parentheses is automatically created but the cursor is now right after the open parentheses:

<img width="127" alt="function" src="https://user-images.githubusercontent.com/31009952/210086738-75d70865-5e9c-472c-91b0-aba1881db537.png">

Also, can you provide the following information?

### System details



    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by mertgoksel** [comment]
For example:
variable -> *highlight variable -> press "(" -> selection becomes "(variable)" -> your cursor is at "(variable)|" where | is the cursor. 

I wasnt talking about direct function typing.
