### ISSUE TITLE
Too agressive and ugly font smoothing AND 0kb socket file creates at startup

### ISSUE THREAD

**Issue by erydit** [rstudio/rstudio#12507]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Manjaro ( Kernel: 6.1.1)
    R Version       :  4.2.2.

### Steps to reproduce the problem
Start Rstudio and eyes start to leak.

### Describe the problem in detail
1. Font smoothing. Something terrible has happened with font rendering in the 2022.12.0! Fonts now blurred and absolutely unclear! Editor fonts suffered the most, font in the help pages and menus happily are still readable. Setting Options >> Appearance >> Text rendering does not change anything. What happened? how to fix?

2. Socket file. Now (after update to 2022.12 a 0 kb socket file named "rstudio" creates on the desktop or in the project folder at Rstudio startup. What is it? Why it creates?

**Comment by erydit** [comment]
OK, i have found a solution for the font problem. Running Rstudio with "--force-device-scale-factor=1.0" parameter fixes font rendering. Why it is not set by default? Is there any way to set that parameter globally for Rstudio in config files, and not only in icon command?

**Comment by kevinushey** [comment]
AFAIK you are the only user impacted by this issue thus far, so I'm not sure if it's something we'd want to set by default.

> Socket file. Now (after update to 2022.12 a 0 kb socket file named "rstudio" creates on the desktop or in the project folder at Rstudio startup. What is it? Why it creates?

Can you please file a separate issue? While we can try to help, note that Arch Linux / Manjaro is not part of our support matrix.

**Comment by ramiromagno** [comment]
Hi @kevinushey and @erydit:

I have the same issue with the blurring of the fonts in the source pane. Fonts in other places remain unaffected.
Also, blurring does not start immediately but after some time... I can't associate it with anything I am doing.

The solution (`--force-device-scale-factor=1.0`) proposed by @erydit did not work for me.

## System details

```
RStudio Edition : Desktop
RStudio Version : 2022.12.0 Build 353
OS Version      : ArchLinux (Kernel: 6.1.5)
R Version       : 4.2.2.
```
Here are two snapshots that hopefully illustrate the problem. In **snapshot 1** the fonts are fine, after some time (usually seconds to a minute) they become blurry, but only in the source pane. I've tried changing the font several times, and problem seems to persist. In the images below the font used is Inconsolata.

## Snapshot 1

![snap01](https://user-images.githubusercontent.com/19862384/218139966-e8b8b695-864f-4482-b0bf-4e1a48aaf3e3.png)

## Snapshot 2

![snap02](https://user-images.githubusercontent.com/19862384/218139991-dd76586b-96a3-42a2-a6e1-c806b9f01725.png)
