### ISSUE TITLE
Ctrl+X/C/V do not work for block selection ?

### ISSUE THREAD

**Issue by github-wow** [rstudio/rstudio#12509]
When I do Alt+LeftMouseButton+DragVertically a text block is selected but can not be copied/cut/pasted.  
Backspace and Delete keys also do not work.
Typing in the selected text block also does not work.

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Comment by ronblum** [comment]
@github-wow Thank you for raising this! In RStudio, that combination is used for creating multiple cursors, not for dragging text. Is this different from previous versions of RStudio?

**Comment by nwbort** [comment]
Duplicate of #12310
