### ISSUE TITLE
Shift + Click doesn't open links 

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rstudio#12504]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2022.12.0 Build 353
    OS Version      :  elementary OS 6.1 Jólnir Built on Ubuntu 20.04.5 LTS  Linux 5.15.0-56-generic
    R Version       :  4.2.1

### Steps to reproduce the problem

Open RStudio and write an URL (www.google.com). Shift click on the link. 

### Describe the problem in detail

While pressing shift makes the mouse pointer turn into the hand symbol, clicking on the link does nothing. ¡

### Describe the behavior you expected

The link should be opened in the default browser. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@eliocamp Thank you for raising this! A few questions:

1) Is this in the Editor Pane?
2) Is this in source mode, visual mode, or both?
3) Can you provide a simple code example so that I can go through the exact steps as you?

Thanks!

**Comment by eliocamp** [comment]
This is in the editor pane and source mode. In visual mode, shift + click doesn't work, but clicking on a link will open up a small dialogue with the link and that does work. 

I get the issue with just something like this:

```r
url <- "www.google.com"
```

Shift click on the URL and you get the mouse hand but nothing happens.

**Comment by ronblum** [comment]
@eliocamp I can reproduce this using Ubuntu 22.04. It looks like <kbd>Shift+Click</kbd> works in RStudio Desktop 2022.07.2+576, but it switched to <kbd>Ctrl+Click</kbd> in version 2022.12.0+353.

@timtmok Is this change perhaps due to the change to Electron?

**Comment by olivroy** [comment]
In a source pane, when hovering over a link for a few seconds, it says `Shift + Click to open link`

However, this doesn't work. Only Ctrl + Click works. 
It would be good to change that misleading message
Thanks

![image](https://github.com/rstudio/rstudio/assets/52606734/af203a0d-06d0-48f1-8b83-7b908807690f)

Windows, R 4.2.3, 2023.06 (daily 2023-05-31)

**Comment by timtmok** [comment]
This is likely the switch to Electron as the application container. I think the best course of action is updating the tooltip to specify that it is Ctrl+Click

**Comment by gtritchie** [comment]
@Teebusch I've opened a new issue for the "cursor doesn't match the behavior" part you are seeing so this issue can just track the tooltip problem.

#14032

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+327 on Ubuntu 22.04 and checked that everything's still fine on MacOS 14.3. Checked with both R and R Markdown (source mode) files.
