### ISSUE TITLE
New intellisense italics "breaks" when using a font without an italics variant (DinaTTF)

### ISSUE THREAD

**Issue by wbdill** [rstudio/rstudio#12517]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
    OS Version      : Windows 10 home (10.0.19044 Build 19044)
    R Version       : 4.2.2

### Steps to reproduce the problem
Tools -> Global options -> Appearance
Set Editor font to Dina TTF (http://briandill.com/misc/fonts/DinaTTF.ttf)

### Describe the problem in detail
When using intellisense in the script editor for dataframe variables, RStudio appears to use italics and since my installed font does not have an italics flavor the drop-down entries show as empty.  See attached screenshot comparisons

DinaTTF (with no italics variant) breaks the intellisense drop-down
http://briandill.com/misc/fonts/2023-01-02_Rstudio_dinattf.jpg

Lucida Console (with an italics variant) works just fine
http://briandill.com/misc/fonts/2023-01-02_Rstudio_lucida.jpg

### Describe the behavior you expected
When I use Lucida Console everything works fine.  Also in my previous version of RStudio (don't recall exactly which one it was, but was from July 2022) the DinaTTF worked just fine.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! https://developer.mozilla.org/en-US/docs/Web/CSS/font-style suggests that there should be some fallback option for rendering here:

> **italic**
> Selects a font that is classified as italic. If no italic version of the face is available, one classified as oblique is used instead. If neither is available, the style is artificially simulated.

So I wonder why that "artificial simulation" isn't happening with our Electron builds.

For some extra data points, some of the editor themes also use oblique / italic characters; e.g. the "Cobalt" theme uses oblique text for comments in the editor. If you change your editor theme to cobalt, is the comment text similarly invisible?

Compare e.g.

<img width="230" alt="Screenshot 2023-01-04 at 12 31 52 PM" src="https://user-images.githubusercontent.com/1976582/210485011-1dda6b6a-cdbe-4ef5-b902-5d6fc7c4e727.png">

**Comment by wbdill** [comment]
Thanks for the reply.When I change to Cobalt theme, my comments visually disappear (see attached screenshots).The spell checker and URL underlines clearly let you know that something is still there, but it's just not visible.
FYI on my work PC I am using an older RStudio build - 2022.07.1 Build 554 - and the intellisense drop-downs are visually OK (I guess because in that build it wasn't using italics for drop down elements), however when I changed my theme to Cobalt on that PC my comments DID visually disappear even on the older build.
---


W. Brian Dill

bdill  @  leftandwrite.com  /  yahoo.com
 

    On Tuesday, January 3, 2023 at 10:32:15 PM CST, Kevin Ushey ***@***.***> wrote:  
 
 


Thanks for the bug report! https://developer.mozilla.org/en-US/docs/Web/CSS/font-style suggests that there should be some fallback option for rendering here:


italic
Selects a font that is classified as italic. If no italic version of the face is available, one classified as oblique is used instead. If neither is available, the style is artificially simulated.


So I wonder why that "artificial simulation" isn't happening with our Electron builds.

For some extra data points, some of the editor themes also use oblique / italic characters; e.g. the "Cobalt" theme uses oblique text for comments in the editor. If you change your editor theme to cobalt, is the comment text similarly invisible?

Compare e.g.

**Comment by kevinushey** [comment]
Thanks! Unfortunately the screenshots are lost (those don't get preserved from e-mail responses to GitHub threads). But that still helps us understand the scope of the issue.

FWIW, I tried installing the Dina TTF font and it doesn't render anything at all in e.g. Visual Studio Code, so I'm inclined to believe there's something peculiar about how those fonts were prepared.
