### ISSUE TITLE
The pandoc built in with latest Rstudio is incompatible with MAC OS: 13.1 Macbook Air M2

### ISSUE THREAD

**Issue by gunawebs** [rstudio/rstudio#12512]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353
    OS Version      : macOS Ventura 13.1
   R version:  4.2.2 (2022-10-31)
   Platform: aarch64-apple-darwin20 (64-bit)

### Steps to reproduce the problem
Knitting any PDF causes this error, because the pandoc built in with latest Rstudio is incompatible with MAC OS: 13.1 Macbook Air M2

### Describe the problem in detail
Looks like the pandoc built in with latest Rstudio is incompatible with MAC OS: 13.1 Macbook Air M2

I get this error:

sh: /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/pandoc: Bad CPU type in executable

Error in strsplit(info, "\n")[[1]] : subscript out of bounds
In addition: Warning message:
In system(paste(shQuote(path), "--version"), intern = TRUE) :
  running command ''/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/pandoc' --version' had status 126

### Describe the behavior you expected
the PDF should be generated

Note: I then installed pandoc using brew. And when I used that pandoc, by setting the env variable RSTUDIO_PANDOC, things worked fine

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gunawebs Thank you for raising this! I'm marking this first off for me to get ahold of an M2 machine and try to reproduce this.

**Comment by gtritchie** [comment]
Likely has nothing to do with M1 vs. M2, but with us shipping an Intel-only pandoc (thus the "Bad CPU type in executable" message). Presumably this is a dup of https://github.com/rstudio/rstudio/issues/12280.

If so, then the workaround is to install Rosetta2. You can do this when prompted (by trying to run an Intel program) or from the terminal via: `/usr/sbin/softwareupdate --install-rosetta --agree-to-license`.

**Comment by gunawebs** [comment]
@gtritchie Regarding
"Likely has nothing to do with M1 vs. M2, but with us shipping an Intel-only pandoc" 
- I do not think that's the case. 
**- Because same stuff worked fine with mac M2 on Mac OS MontereyVersion 12.4.** 

Hence, I think it is MAC OS: 13.1 (ventura) related.

**Comment by gunawebs** [comment]
@ronblum Thanks so much. 
My guess is it is related to Mac Os. 

FYI, as mentioned on the ticket, when I installed pandoc using brew. And when I used that pandoc, by setting the env variable RSTUDIO_PANDOC by doing:

`Sys.setenv(RSTUDIO_PANDOC="/opt/homebrew/bin")`

things worked fine

However, I would request that things work out of the box with rstudio, down the line.

Thanks so much!

**Comment by kevinushey** [comment]
Just to be sure, can you confirm if Rosetta has been installed and is active? What do you see if you run:

```
ps -p $(pgrep -x oahd)
```

For example, I see:

```
$ ps -p $(pgrep -x oahd)
  PID TTY           TIME CMD
57596 ??         0:00.02 /usr/libexec/rosetta/oahd
```

which is the internal name for the Rosetta daemon that handles code translation (IIUC).

Or similarly, something like:

```
$ arch -x86_64 /bin/bash -c machine
i486
```

**Comment by gunawebs** [comment]
@kevinushey 

Here are the outputs

~ % arch -x86_64 /bin/bash -c machine
arch: posix_spawnp: /bin/bash: Bad CPU type in executable

~ % ps -p $(pgrep -x oahd)
ps: option requires an argument -- p
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
     [-g grp[,grp...]] [-u [uid,uid...]]
     [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
    ps [-L]

**Comment by kevinushey** [comment]
Okay, that implies that Rosetta 2 is not installed, or is not running. Can you please run the code suggested by @gtritchie?

```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

**Comment by shortyatz** [comment]
Well, I got an M2 Ultra on release and am having the same problem.

! No release bundle with name 'pandoc-3\.1\.3(-\d)?-macOS\.zip' available.

I installed Rosetta 2 (see below) and am still having the problem.

ps -p $(pgrep -x oahd)
  PID TTY           TIME CMD
 7711 ??         0:00.01 /usr/libexec/rosetta/oahd

I will restart the computer and see if that helps

**Comment by fcamineiro** [comment]
I had the same problem on a new MacBook Pro M2 Max (Ventura 13.5.1), and installing Rosetta 2 fixed it.
