### ISSUE TITLE
Go to File/Function doesn't always find all instances

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#12511]
I've been having an issue for a little while on the daily builds where `Control + .` to "go to function" isn't finding my function definitions. This has been particularly annoying with C functions, like in vctrs.

Note that `s3_find_method()` exists both at the R and C level. It used to always find both. I'm not sure if the fact that they share the same name has anything to do with it.

<img width="1198" alt="Screen Shot 2023-01-01 at 4 43 21 PM" src="https://user-images.githubusercontent.com/19150088/210185501-a1f693c9-6d2f-415f-a603-7f2ab2fc64c4.png">

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Comment by kevinushey** [comment]
@romainfrancois does this ring any bells?

**Comment by romainfrancois** [comment]
no but I can investigate

**Comment by jennybc** [comment]
Stay alive

**Comment by ronblum** [comment]
@jennybc Is there an example in the https://github.com/hadley/r-pkgs in which the go-to fails? `s3_find_method()` doesn't seem to be in it—or do you have any other repositories or files that should work but don't?
