### ISSUE TITLE
MacOS: Additional inoperable dock icon when loading {tcltk}

### ISSUE THREAD

**Issue by uhkeller** [rstudio/rstudio#12513]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : macOS 12.6.2
    R Version       : 4.2.2

### Steps to reproduce the problem

In RStudio running in macOS, run `library(tcltk)`.

### Describe the problem in detail

An additional, inoperable dock icon depicting a terminal with the text "exec" appears. The tooltip (on my M1) is "rsession-arm64". One such icon appears for each RStudio session {tcltk} is loaded from. This also happens with other packages using {tcltk}, like {gsubfn} (which is how I encountered this).

![image](https://user-images.githubusercontent.com/2323704/210325433-65a9d0e0-9f45-4b7b-a7b9-9af53150fd47.png)

### Describe the behavior you expected

I excpected no additional dock icon.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@uhkeller Thank you for raising this issue! Do you know if this is a new issue in RStudio Desktop 2022.12.0+353, or did it occur in previous versions as well?

@jonvanausdeln I can't reproduce similar behavior on an Intel Mac. Can you try this on M1?

**Comment by jonvanausdeln** [comment]
> @jonvanausdeln I can't reproduce similar behavior on an Intel Mac. Can you try this on M1?

I wasn't able to reproduce on my M1 nor my windows machine.

**Comment by uhkeller** [comment]
@ronblum this happened with the Qt-based versions of RStudio as well, though the additional icon was different (it used to be another RStudio icon without a project/folder name).

I'm using the homebrew-compiled version of R, maybe that's why it only happens on my machine. I'll try with the official version when I find the time.

**Comment by kevinushey** [comment]
The same sort of issue occurs if you run R from a terminal and try to create a plot using the Quartz graphics device (which is the default), except of course the exec'ed application is called R.

Given that this is apparently a behavior in base R rather than RStudio, I would vote this is out of scope. We could consider filing a bug report upstream if we wanted to share reproduction steps using R independently of RStudio.

**Comment by uhkeller** [comment]
Indeed, the same thing happens when loading {tcltk} in an R session in the terminal. My bad, I should have checked this before. So not an RStudio issue.

**Comment by uhkeller** [comment]
I'm now using the official R build instead of the homebrew build and the issue is gone both with RStudio and with R running in a terminal. So not only is this not an RStudio issue, it's not even really an R issue. Sorry again for reporting this here.
