### ISSUE TITLE
Update Ace editor

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12522]
The Ace editor used by the IDE has not been updated in several years.

The last major update I'm aware of was in 2018, to version 1.4.1, via: https://github.com/rstudio/rstudio/pull/3522.

The most recent release as of this writing is 1.14.0. Release notes here: https://github.com/ajaxorg/ace/releases

One change is particularly interesting: screen reader support of autocomplete popups: https://github.com/rstudio/rstudio/issues/6167

That's one of our highest priority accessibility fixes, so if it works as advertised it would be a major improvement.

**Comment by DesiQuintans** [comment]
If updating ACE also adds new syntax highlighting style selectors, that would also be great. For example, both variable names and arg names have the same style applied to them, and can't be styled separately if desired.

**Comment by kevinushey** [comment]
I've merged the PR updating Ace; it would be worth testing what we've gained (or, hopefully not, lost) in terms of accessibility.

**Comment by jonvanausdeln** [comment]
Editors seems to work as expected.

The autocomplete accessibility does seem a little bit better, but not great. (https://github.com/rstudio/rstudio/issues/6167), Leaving this in test for now to spend more time with accessibility testing as time permits.
