### ISSUE TITLE
Error in find.package(package, lib.loc)

### ISSUE THREAD

**Issue by OmarBinSaad** [rstudio/rstudio#12524]
### System details
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

```
### Steps to reproduce the problem
I have created a package and when I used devtools::check() I found an issue :
```
devtools::check()
To check my package
### Describe the problem in detail
I have created a package and when I used devtools::check() I found an issue :
```
❯ checking examples ... ERROR
  Running massageExamples to create 'first-Ex.R' failed
  Error in find.package(package, lib.loc) : 
    there is no package called 'first'
  Calls: <Anonymous> -> Rd_db -> find.package
  Execution halted
   NONE

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@OmarBinSaad Thank you for raising this! I tried reproducing this in RStudio Desktop 2022.12.0+353 on Windows 11 and MacOS 13.2, but it works for me. A few questions:

1) Do you run into this issue with the default R Package project?
2) If not, can you provide a simple reproducible example?
3) What version of RStudio are you using?

Thanks!

**Comment by OmarBinSaad** [comment]
yes, all my settings is defult.
R version 4.2.1 (2022-06-23 ucrt)
