### ISSUE TITLE
Python indentation error with certain characters in regular expression

### ISSUE THREAD

**Issue by shanedenecke** [rstudio/rstudio#12530]
# Title 
Python indentation error with certain characters in regular expression

# Environment details:
Python 3.9.13
Reticulate 1.26 REPL -- A Python interpreter in R.
Rstudio Desktop: RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

# Steps to reporoduce the problem
Make a simple block of code that involves an indent which uses an escape character such as "\".

```
###Import re package for regular expressions
import re

###Define generic list
foo=['apple','pear','rambutan','durian','peach']

###Run for loop using escape character which causes indenetation error to occur
for i in foo:
  if re.search('\S+n$',i):
    print(i)

IndentationError: expected an indented block (<string>, line 1)
IndentationError: unexpected indent (<string>, line 1)
```
In contrast an nearly identical for loop without the special character "\" runs fine

```
###Run similar for loop without escape character which doesn't give an indentation error
for i in foo:
  if re.search('[A-z]+n',i):
    print(i)

rambutan
durian
```

# Detailed description of the problem
The problem appears to be that whenever certain characters are used in the context of a python indentation block, there is an indentation error. I tested it with a few different variations and it seems to be that when I take out the “\” character there is no indentation error. In the examples above, when pasted into another python interpreter (e.g. my system terminal on linux), neither one causes an error. 

# Describe the behavior you expected
I would expect that neither block of code would yield an error and both would return “rambutan” and “durian”. This is what happens in other python consoles. 

# Workaround
Mostly, it is possible for me to design regex strings that do not contain “\”.

**Comment by kevinushey** [comment]
As a workaround, you can escape the slash as e.g. `\\S`. IMHO the slash should be escaped here since otherwise you're relying on Python to treat the "escape code" `\S` as two separate character `\` + `S`; e.g.

```
>>> len('\S')
2
>>> len('\a')
1
```

and it's not clear if this is really what you expect.

**Comment by tomwagstaff-opml** [comment]
I have just encountered exactly the same error - unearthed after a lot of head scratching! For me the weird thing is that this works fine on an unindented line e.g. `re.sub('\d+$', '', "cat1")` outputs the expected `cat`, but as soon as it is in a loop it throws an error. Here is my minimum reproducible example:
````
import re

my_words = ["cat1", "dog2", "mouse3"]

for my_word in my_words:
  print(re.sub('\d+$', '', my_word))
````
For me this has triggered both the `IndentationError` already reported and `SyntaxError: unexpected EOF`.

It is true that double-escaping the regex as per usual R conventions (so `re.sub('\\d+$', '', my_word)` ) avoids the problem in RStudio, as does specifying a raw string (`re.sub(r'\d+$', '', my_word)`) but this code runs fine in other Python interpreters like Spyder. There is some discussion on [StackOverflow about it](https://stackoverflow.com/questions/13902132/regex-deal-with-double-backslash) but here's what ChatGPT told me:

> Unlike normal Python string literals, regular expressions interpret a single backslash as an escape character without requiring an additional level of escaping. Therefore, in the context of regular expressions, you can use "\d" directly to match a digit.

So I don't think REPL is behaving the way a conventional Python interpreter would, and that really makes me uneasy about using it. I don't want to develop code in RStudio, that then doesn't run as expected in another Python interpreter.

One other, minor, difference is that running this code:
````
for my_word in my_words:
  my_word
````
in RStudio prints out the words, despite the lack of an explicit print statement. That doesn't work in Spyder etc. - nothing appears in the console (although the loop runs fine).
