### ISSUE TITLE
Reflow roxygen comments no longer works when `{` and `}` are not balanced on one line

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#12547]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : macOS 12.6.2
    R Version       : 4.2.2

### Steps to reproduce the problem

Write a roxygen comment:

```r
#' \item{\code{foo}}{long long long long long long long long long long long long long long long long}
```

Reflow it with `Ctrl+Shift+/` and we get:

```r
#' \item{\code{foo}}{long long long long long long long long long long long long
#' long long long long}
```

Add more text to the first line:

```r
#' \item{\code{foo}}{long long long long long long long long long long long long more text
#' long long long long}
```

Reflow again, and it won't reflow the long line.

### Describe the behavior you expected

Expecting the long line to be wrapped like this:

```r
#' \item{\code{foo}}{long long long long long long long long long long long long
#' more text long long long long}
```

It used to work. This is probably due to https://github.com/rstudio/rstudio/pull/12012.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by idmn** [comment]
Same thing happens when a comment starts with a hyphen (`-`), both in R comments and in markdown files.
![rstudio-reflow-comment-issue](https://user-images.githubusercontent.com/8419011/213674122-c7ac4267-6859-498d-9aee-22d92d40db50.gif)
