### ISSUE TITLE
Option to permanently set screen split within the Environment Pane (different from the main screen pane split)

### ISSUE THREAD

**Issue by seehorse** [rstudio/rstudio#12542]
It would be handy to be able to permanently set the split location in the Environment Pane. I mean the split between the object column (e.g. data frame name) and the contents description (e.g. 548 obs. of 2749 variables).

Using the mouse to move the split every time the pane refreshes is a pain (pun intended).

An options setting would be good. An API call would be better.

Thanks for your consideration.
 
![image](https://user-images.githubusercontent.com/103534295/211196019-e1837d34-2964-44ee-bb21-1f124b3a2594.png)

**Comment by ntluong95** [comment]
it is nice feature to be considered indeed
