### ISSUE TITLE
Desktop logging level command-line switch not passed to created rsessions

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12557]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353
    OS Version      :  Any
    R Version       : Any

### Steps to reproduce the problem

Make sure you don't have the `RS_LOG_LEVEL` environment variable set, delete any existing logs, then run RStudio desktop from the command line with verbose logging and diagnostics generation. For example, on Windows:

```
del %localappdata%\rstudio\log\*.log
"c:\program files\RStudio\rstudio" --log-level=debug --run-diagnostics
```

Now find and open the session log file (location will be mentioned in the diagnostics report: on Windows it will be in `%localappdata%\rstudio\log\).

### Describe the problem in detail

The session log does not contain `debug` level logging.

### Describe the behavior you expected

The desktop app should pass the requested logging level along to created rsessions, either via environment variable (RS_LOG_LEVEL) or via a command-line switch.

There is a workaround of setting `RS_LOG_LEVEL=debug` in the environment before running RStudio, but that's an added complication we shouldn't need to use.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0-daily+280
Windows11 & Ubuntu22

DEBUG messages are present in log files.
