### ISSUE TITLE
Terminal not working (specified module not found) on Windows 10

### ISSUE THREAD

**Issue by hughandersen** [rstudio/rstudio#12552]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Windows 10
    R Version       : 4.2.2

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

### Steps to reproduce the problem
Starting a new terminal

### Describe the problem in detail
Terminal is not working. Only showing a blinking cursor. I had this in the officially released version too (however without blinking cursor). If I close the open terminal and start a new one, a pop-up appears with "The specific module could not be found"

### Describe the behavior you expected
The  terminal to work

Global Terminal Information
---------------------------
Loaded TerminalSessions: 1
Handle: '67BBB167' Caption: 'Terminal 1'

Terminal List Count: 1
Handle: '67BBB167' Caption: 'Terminal 1' Session Created: true

Global Terminal Information
---------------------------
Caption:     'Terminal 1'
Title:       ''
Cols x Rows  '112 x 58'
Shell:       'Git Bash'
Handle:      '67BBB167'
Sequence:    '1'
Restarted:   'true
Exit Code:   'null'
Full screen: 'client=false/server=false'
Zombie:      'false'
Track Env    'false'
Local-echo:  'false'
Working Dir: 'Default'
Interactive: 'Always'
WebSockets:  'true'

System Information------------------
Desktop:    'true'
Remote:     'false'
Platform:   'Windows'

Connection Information
----------------------
2023/1/10 9:23:24: Connect WebSocket: 'ws://127.0.0.1:5816/terminal/67BBB167/'
2023/1/10 9:23:24: WebSocket connected
2023/1/10 9:23:27: Disconnected
2023/1/10 9:23:27: WebSocket closed

Local-echo Match Failures
-------------------------
<Not applicable>

I have deleted the registry keys as suggested here
https://answers.microsoft.com/en-us/windows/forum/all/the-error-the-specified-module-could-not-be-found/c7a9232c-4748-47d3-b6c5-58864ea47f24#:~:text=Boot%20your%20computer%20into%20Safe,whether%20the%20problem%20is%20solved.

and re-booted but the problem remains.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hughandersen** [comment]
Running as administrator fixed the problem for me

**Comment by ronblum** [comment]
@hughandersen Good to hear that you got this to work! But, I'm reopening this because you shouldn't have to run this as administrator.

**Comment by ronblum** [comment]
@hughandersen Also, did you use previous versions of RStudio Desktop, and if so, was this an issue in the past?
