### ISSUE TITLE
Desktop diagnostics log not included in diagnostics report

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12556]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353
    OS Version      :  Windows 10 or 11
    R Version       : Any

### Steps to reproduce the problem

From a command prompt, delete any existing log files:

```
cd %localappdata%\rstudio\log
del *.log
```

Now run RStudio with maximum logging verbosity, and generate a diagnostics report:

```
"c:\program files\RStudio\rstudio" --log-level=debug --run-diagnostics
```

File explorer opens to show the generated `diagnostics-report.txt` file. Open it in a text editor and search for `rdesktop.log`.

### Describe the problem in detail

The diagnostics shows:

```
Log file: C:/Users/gary_/AppData/Local/RStudio/log/rdesktop.log
--------------------------------------------------

(Not Found)
```

### Describe the behaviour you expected

The desktop log file does exist in %localappdata%\rstudio\log but has timestamp info in the filename. I believe this is related to the log rotation (https://github.com/rstudio/rstudio/pull/10561).

For example:

```
01/10/2023  11:33 AM             2,506 rdesktop.2023-01-10.log
```

We need to fix it so the diagnostics report does find the actual log file and include it in the report.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
The simplest fix might be to back out desktop log rotation. I don't think we did that in the Qt desktop and this particular log file is normally going to be very small.

**Comment by gtritchie** [comment]
This has been merged to both Elsbeth Geranium and Cherry Blossom.

**Comment by jonvanausdeln** [comment]
Verified 2023.03.0-daily+270 on Windows 11 & MacOS

Logs now appear as expected.
