### ISSUE TITLE
Code disappears from RStudio editor when adding CSS code chunk to RMarkdown HTML

### ISSUE THREAD

**Issue by doliv071** [rstudio/rstudio#12562]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Ubuntu Jammy Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
    OS Version      :  Ubuntu 22.04.1 LTS
    R Version       :  4.2.1

### Steps to reproduce the problem
Start a new HTML RMarkdown document
Add css chunk for controlling elements of the html:

`````
```{css, echo = FALSE}
h1 {
  font-size: 24px;
  color: DarkBlue;
}
```
`````

### Describe the problem in detail
When CSS code chunk exists in RMarkdown, RStudio glitches so that no code can be seen in the entire RMarkdown document

### Describe the behavior you expected
I should be able to see my code when I'm editing it...

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I was able to reproduce. @romainfrancois, this may be related to your work on CSS coloring; can you take a look?

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.03.0-daily+270 on MacOS 13.2. Note that this problem only occurs in source mode. It doesn't occur in visual mode, but the color colors feature isn't in it—I'll file an enhancement request for it.
