### ISSUE TITLE
'Error Retrieving Help' on rcmdcheck::rcmdcheck_process

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [rstudio/rstudio#12568]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+354 Elsbeth Geranium (desktop)
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.2 Patched (2023-01-10 r83603 ucrt)

### Steps to reproduce the problem

Type `rcmdcheck::rcmdcheck_` into R console

### Describe the problem in detail

Error window 

> Error Retrieving Help
> (TypeError) : Cannot read properties of null (reading 'rows')

![image](https://user-images.githubusercontent.com/89191115/212347959-fce6372f-ebb7-48dd-8610-76d2891a9119.png)

### Describe the behavior you expected

- No error window which keeps popping up and interferes with typing code.
- Nice to have: help on `rcmdcheck_process` R6 class.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by HenningLorenzen-ext-bayer** [comment]
```
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 Patched (2023-01-10 r83603 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  German_Germany.utf8
 ctype    German_Germany.utf8
 tz       Europe/Berlin
 date     2023-01-13
 rstudio  2022.12.0+354 Elsbeth Geranium (desktop)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 callr         3.7.3   2022-11-02 [1] RSPM (R 4.2.0)
 cli           3.6.0   2023-01-09 [1] RSPM
 crayon        1.5.2   2022-09-29 [1] RSPM (R 4.2.0)
 curl          4.3.3   2022-10-06 [1] RSPM (R 4.2.0)
 desc          1.4.2   2022-09-08 [1] RSPM (R 4.2.0)
 digest        0.6.31  2022-12-11 [1] RSPM
 pkgbuild      1.4.0   2022-11-27 [1] RSPM (R 4.2.0)
 prettyunits   1.1.1   2020-01-24 [1] RSPM (R 4.2.0)
 processx      3.8.0   2022-10-26 [1] RSPM (R 4.2.0)
 ps            1.7.2   2022-10-26 [1] RSPM (R 4.2.0)
 R6            2.5.1   2021-08-19 [1] RSPM (R 4.2.0)
 rcmdcheck     1.4.0   2021-09-27 [1] RSPM
 rprojroot     2.0.3   2022-04-02 [1] RSPM (R 4.2.0)
 rstudioapi    0.14    2022-08-22 [1] RSPM
 sessioninfo   1.2.2   2021-12-06 [1] RSPM
 withr         2.5.0   2022-03-03 [1] RSPM (R 4.2.0)
 xopen         1.0.0   2018-09-17 [1] RSPM
```

**Comment by dbrookeUAB** [comment]
Same problem.  It happens while using `autocomplete` to preview package functions (e.g. `ggplot2::<tab>`). I uploaded an   [example gif](https://s3.gifyu.com/images/error.gif) that shows what it looks like. It's only for some packages, and it's only triggered when a specific function is highlighted.

**Comment by HenningLorenzen-ext-bayer** [comment]
![RStudio_Completion_Error](https://user-images.githubusercontent.com/89191115/213179877-c78a2ec4-cbaa-4fd9-8db1-ad31b1c5a4a5.gif)

**Comment by romainfrancois** [comment]
It looks like `rcmdcheck:: rcmdcheck _process` is not a function but rather an R6 class, and so the `Arguments` section looks different than what we'd typically get from a function: 

https://github.com/r-lib/rcmdcheck/blob/a38200c997f58478c8d3e2c4d2dd5e6244dabcba/R/background.R#L28-L40

so I think the play is to make `HelpInfo.java` more forgiving here: 

https://github.com/rstudio/rstudio/blob/df7efaa7c605d91399201ad68eb607d5c16fda54/src/gwt/src/org/rstudio/studio/client/workbench/views/help/model/HelpInfo.java#L90

`parseArguments()` assumes that there is a `<table>` : 

https://github.com/rstudio/rstudio/blob/df7efaa7c605d91399201ad68eb607d5c16fda54/src/gwt/src/org/rstudio/studio/client/workbench/views/help/model/HelpInfo.java#L172-L198

**Comment by romainfrancois** [comment]
In the case of `limma::anova.<...>` method, the `Arguments` section is also manually generated with a `\section{Arguments}` rather than a `\arguments` https://github.com/cran/limma/blob/1b51b3a5295f9feedb72a0df97e9c3e236592464/man/anova-method.Rd#L13-L20
and this goes against what `parseArguments()` expects to find. 

```
\section{Arguments}{
\describe{
  \item{\code{object}}{object of class \code{MAList}. Missing values in the M-values are not allowed.}
  \item{\code{design}}{numeric vector or single-column matrix containing the design matrix for linear model. The length of the vector or the number of rows of the matrix should agree with the number of columns of M.}
  \item{\code{ndups}}{number of duplicate spots. Each gene is printed ndups times in adjacent spots on each array.}
  \item{\code{...}}{other arguments are not used}
}
}
```

**Comment by romainfrancois** [comment]
The rendered `rcmdcheck::rcmdcheck_process()` help gives this, which also drifts from what `HelpInfo.java` expected to find. 

```html
<!-- [...] -->
<h3>Arguments</h3>


<ul>
<li> <p><code>cp</code>: A new rcmdcheck_process object.
</p>
</li>
<li> <p><code>path</code>: Path to a package tree or a package archive file. This is the
package to check.
</p>
</li>
<li> <p><code>args</code>: Command line arguments to <code style="white-space: pre;">&#8288;R CMD check&#8288;</code>.
</p>
</li>
<li> <p><code>build_args</code>: Command line arguments to <code style="white-space: pre;">&#8288;R CMD build&#8288;</code>.
</p>
</li>
<li> <p><code>check_dir</code>: Directory for the results.
</p>
</li>
<li> <p><code>libpath</code>: The library path to set for the check.
</p>
</li>
<li> <p><code>repos</code>: The <code>repos</code> option to set for the check.
This is needed for cyclic dependency checks if you use the
<code>--as-cran</code> argument. The default uses the current value.
</p>
</li>
<li> <p><code>env</code>: A named character vector, extra environment variables to
set in the check process.
</p>
</li></ul>
```

**Comment by romainfrancois** [comment]
Related to https://github.com/rstudio/rstudio/issues/10844

**Comment by ronblum** [comment]
Note: This occurs in both the Console and Editor Panes. Also, this was a problem in previous releases, such as 2022.07.2+576.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+301 on MacOS 13.2. Tested in both Console and Source Editor, both by typing out the `_` and using autocomplete.

**Comment by klwilson23** [comment]
@ronblum I see you closed this, but what was the fix? I'm getting the same error now from autocomplete in RStudio 2023.03.0 Build 386 "Cherry Blossom" Release (3c53477a, 2023-03-09) for Windows

`Error in if (nchar(current) > nchars) { : missing value where TRUE/FALSE needed`

**Comment by kevinushey** [comment]
@klwilson23 the issue you're describing is different and is tracked in https://github.com/rstudio/rstudio/issues/12918.

**Comment by klwilson23** [comment]
> @klwilson23 the issue you're describing is different and is tracked in #12918.

Fair enough - effectively my error looks like the .gif posted by @HenningLorenzen-ext-bayer associated with autocomplete generating an error
