### ISSUE TITLE
"Write Diagnostics Report" command doesn't show report in Finder/Explorer

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12570]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

Help / Diagnostics / Write Diagnostics Report

NOTE: It is likely there are other scenarios that could encounter this same underlying issue, but I haven't gone looking for that yet.

### Describe the problem in detail

The RStudio Console correctly shows the location of the report, but Finder / File Explorer window isn't shown as it was in prior versions.

On Windows, an additional error dialog is shown saying: "Windows cannot find ~\rstudio-diagnostics".

![image](https://user-images.githubusercontent.com/10569626/212391663-fe7e8f56-2976-4750-853a-87ff6e76c220.png)

### Describe the behavior you expected

Should behave as it did in prior versions.

On Windows, we need to correctly map the Unix home folder concept to the Windows equivalent. This may impact other scenarios as well. We should use the same logic in Electron that we did in Qt.

Specifically, compare the Qt implementation:

https://github.com/rstudio/rstudio/blob/f18a4039982eeb95df9a60826554b69abf752d8d/src/cpp/desktop/DesktopGwtCallback.cpp#L535-L547

to the Electron implementation:

https://github.com/rstudio/rstudio/blob/f18a4039982eeb95df9a60826554b69abf752d8d/src/node/desktop/src/main/gwt-callback.ts#L337-L342

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
This works in Cherry Blossom, should be checked if already fixed in EB patch

**Comment by jonvanausdeln** [comment]
This is **not** fixed in current elsbeth branch, checked on [2022.12.1+366](https://dailies.rstudio.com/version/2022.12.1+366)

**Comment by petetronic** [comment]
Closing as we're no longer considering this for an EB patch.
