### ISSUE TITLE
Incorrect error report:  "system error 100 (Protocol error)"

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#12576]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2022.12.0+353 (2022.12.0+353)
    OS Version      :  MacOS Monterey 12.6.2 (Intel Mac)
    R Version       : 4.2.1

### Steps to reproduce the problem

Start working on a package, e.g. via `File | New project... | New directory | R package` .
Delete the "Package" line from the package DESCRIPTION file.
Try to build the package.

### Describe the problem in detail

The build fails (as it should), but the error message is wrong.  It says

```
Error reading package DESCRIPTION: system error 100 (Protocol error)
```

which is misleading, as it looks as though there's a system error, not just a formatting error in the file.

When using the standard `R CMD build`, the error is

```
* checking for file ‘./DESCRIPTION’ ... OK
 ERROR
invalid ‘Package’ field
```

and `R CMD INSTALL` gives

```
* installing to library ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library’
ERROR: no 'Package' field in 'DESCRIPTION'
```

`devtools::build()` gives

```
Error: No root directory found in /Users/murdoch/svn/MyR/testpackage2 or its parent directories. Root criterion: contains a file "DESCRIPTION" with contents matching "^Package: "
```

These messages all identify the problem; the one from RStudio hides it.
### Describe the behavior you expected

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dmurdoch Thank you for raising this and providing the comparison point! We'll review this as we continue development of RStudio.
