### ISSUE TITLE
Quarto viewer not displaying image without extension

### ISSUE THREAD

**Issue by Sandv** [rstudio/rstudio#12574]
### System details

RStudio Edition : Desktop
RStudio Version : checked on 2023.03.0 Build 76 and latest stable build Version: 2022.12.0+353 
OS Version      : Windows 10

### Steps to reproduce the problem

Thank you for making Quarto! IMHO the best solution for academic writing.
I ran into this issue:

Assume the files image.png and image.pdf are present in the document directory.

In Quarto viewer enter:
```
![Image Caption](image)
```

No image is displayed
### Describe the problem in detail
While image.png would work, I would like to have an image displayed while having pdf embedded in the latex output.

While rendering to PDF works as expected the quarto viewer does not check if an image with a usable extension is present.

### Describe the behavior you expected
Display the image in the editor.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ NA ]x If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Sandv Thank you for raising this! We'll review this as we continue to work on the Quarto integration and the visual editor.

Note: I created three files: image.jpg, image.png, and image.pdf. When leaving out the extension, the PNG file is included when the file is rendered. If I get rid of the PNG file and render, neither the JPEG nor PDF get picked up.

**Comment by kkasra12** [comment]
I had the same problem and solved it by using the `img` HTML tag. I hope it helps for future reference.
