### ISSUE TITLE
Quarto wysiwym for insert inline code 

### ISSUE THREAD

**Issue by drmowinckels** [rstudio/rstudio#12573]
I ran a Quarto through RStudio course today and several course participants felt an insert for inline code was missing from the visual editor. Given the amazing magic that is inline code, I agree this would be a great addition to the insert functionality. 

I can envision there being an `inline code` part, that would expand to choosing language for the code in a sub-menu, just like the code chunk insert.

**Comment by ronblum** [comment]
@drmowinckels Thank you for raising this! However, unlike code chunks, it's only possible to use inline code for R, so I don't think such a menu would apply.

Inserting inline code currently requires clicking on the <kbd>\</\></kbd> button for formatting as code and beginning the text with `r`. I'll keep this open to consider including something like "insert code chunk" under the "Insert" menu, which would create inline code for R.

**Comment by drmowinckels** [comment]
oh right! I actually didnt know inline code only works for R! Is that well-documented? Being an R user I have not considered that this would only work for R, I just assumed it also would work for other languages. 

May I ask a intermediate level technical explanation of why inline code only works for R? (that might be better suited to another repo, just let me know and I'll redirect the question there)

**Comment by ronblum** [comment]
@drmowinckels There's a bit of a discussion about it in the `knitr` repository at https://github.com/yihui/knitr/issues/2026. It's somewhat implied in the [chapter 3 of the *R Markdown Cookbook*](https://bookdown.org/yihui/rmarkdown-cookbook/r-code.html#r-code):
> There are two types of code in an Rmd document: code chunks and inline R code.

Read: code chunks for multiple languages, and inline code only for R. Also, the Quarto documentation only mentions R when using `knitr` in [the section on inline code](https://quarto.org/docs/computations/execution-options.html#knitr).

There's some more info in the *R Markdown Cookbook* about [using R to access Python data](https://bookdown.org/yihui/rmarkdown/language-engines.html#python). The Quarto documentation also shows how it can be done with [dynamically-generated markdown with the Jupyter engine](https://quarto.org/docs/computations/execution-options.html#jupyter). But those are much more complex than simple `r insert_code_here`!
