### ISSUE TITLE
View current citations/references in an RMarkdown or Quarto doc

### ISSUE THREAD

**Issue by colerehbein** [rstudio/rstudio#12584]
I use Quarto for academic writing in psychological science. I'd like a view that lists all of the references that are currently cited in the document I'm working on. This would let me easily view what has already been cited so I can know if I am missing research, or if I inadvertently included a citation by mistake. Being able to do this while editing, before rendering the whole document and references section, would make it easier and quicker to catch reference errors or omissions, and help identify problems when they arise.

Zettlr is an open-source app for editing markdown that implements this feature. This feature is described here in the Zettlr docs: [https://docs.zettlr.com/en/core/sidebar/#references](https://docs.zettlr.com/en/core/sidebar/#references). 

One way this could be implemented is by adding a "References" tab to either the Environment pane or the Output pane. 

Another option is to offer a view similar to the "outline" view in the visual editor that appears to the right of the document text. This may be easier to implement. If the "outline" view is parsing the document for markdown headers and displaying them in hierarchical/formatted order, parsing for citations and presenting them as styled references may follow a similar process.

Ideally, references in this feature would be shown in a specified style provided in a .csl. Zettlr displays citations in the sidebar using a generic Chicago style. This would work fine, as the primary proposed function is to double-check and edit references in the body of the document. Allowing a quick copy/paste of some or all current references in the user's preferred style would be ideal. 

I'm just a beginner developer but I am reading "A Beginner's Guide to Writing RStudio IDE Features." As a workaround, I could write a script that parses the document for citations and saves them in a data frame that I could display and refer to separately. 

Thank you for your consideration!

Cole

**Comment by ronblum** [comment]
@colerehbein Thank you for the suggestion! Thanks for the detailed write up. I'm also glad that you're getting use out of Quarto and exploring "A Beginner's Guide to Writing RStudio IDE Features." If you come up with a solution that you'd like to add, that would be great! That said, I'll mark this for review as we continue to develop RStudio, especially the integration with Quarto.
