### ISSUE TITLE
Font size increase with key buttons

### ISSUE THREAD

**Issue by github-wow** [rstudio/rstudio#12588]
To increase font size: `Ctrl`+`+`, `Ctrl`+`-`, and `Ctrl`+`0` work on the main part of the keyboard; does not work (but worked previously) on numeric keyboard 

```
RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
```

**Comment by ronblum** [comment]
@github-wow Thank you for raising this! This looks like a variation of #12455, although it appears that different zooming key combos are affected differently in different platforms. So, I'm adding your findings to the other issue and closing this one.
