### ISSUE TITLE
Some visual editor keyboard shortcuts execute in the wrong pane when there are multiple panes

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12581]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.02.4+500, 2022.07.2+576, 2022.12.0+353
    OS Version      : MacOS 13.2 and Ubuntu 20.04 (via Chrome on MacOS 13.2)
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Create a new R Markdown file.
2. Create a new source pane: <kbd>View -> Panes -> Add Source Column</kbd>
    - Should now have two source columns: the original and the new one.
3. Change the source to R Markdown using the dropdown on the lower right of the pane.
4. Create another new source pane: <kbd>View -> Panes -> Add Source Column</kbd>
    - Should now have three source columns total.
5. Change the new source to R Markdown using the dropdown on the lower right of the pane.
6. Switch all three to visual mode.
    - We now have three R Markdown, one per column.
7. In all three, create a new R chunks.
8. Add `print(1)`, `print(2)`, `print(3)` in each code chunk, respectively from the leftmost (newest) column to the rightmost (oldest)
    - We'll call these chunks 1, 2, and 3, based on these numbers.
9. Place the cursor in the chunk of pane 3.
10. <kbd>Ctrl-Shift-Enter</kbd>
    - The chunk in pane 1 runs.
11. Clear the output in pane 1.
12. Place the cursor in the chunk of pane 2.
13. <kbd>Ctrl-Shift-Enter</kbd>
    - The chunk in pane 1 runs.
14. Clear the output in pane 1.

Steps 9-13 all happen with <kbd>Ctrl-S</kbd> for saving, as well.
They might not go to pane 1—they might to pane 2. But it's always the same pane.

15. Place the cursor in the chunk of pane 1.
16. <kbd>Ctrl-Shift-Enter</kbd>
    - The chunk in pane 1 runs.
17. Clear the output in pane 1.
18. In each pane, place the cursor below the chunk.
19. In each pane, <kbd>Cmd-I</kbd>, then choose to insert anything.
    - The code is inserted into the correct pane.

### Describe the problem in detail

Some keyboard shortcuts in visual mode happen execute in the wrong pane.

### Describe the behavior you expected

All visual keyboard shortcuts should work in their respective columns. Compare to source mode, in which this isn't an issue.

Also, this appears to be an issue in multiple versions of RStudio. Oddly, while this came up in 2022.12.0+353, I'm seeing this going back for several releases.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by netique** [comment]
https://github.com/rstudio/rstudio/issues/11684 is also related. I suspect the issue also stems from being unable to focus on the right source.

**Comment by ronblum** [comment]
Verified using the scary reprex in RStudio Desktop 2024.07.0-daily+219 on Windows 11.
