### ISSUE TITLE
Rstudio creating socket files in home directory

### ISSUE THREAD

**Issue by 392781** [rstudio/rstudio#12580]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Pop!_OS 22.04
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Launch Rstudio
2. Check the files in ~/ directory

### Describe the problem in detail

Rstudio seems to be creating a socket file called `rstudio` with permissions `srwxrwxr-x` in my home directory (~/).  I have a `.Renviron` file that sets my library directories to be outside of the home directory, yet the socket file persists.

I am unsure if I need to add additional contents to `.Renviron` to prevent this or if this is a setting in Rstudio.  Either way, it doesn't seem to be documented online (as far as I am aware) and this was not happening in older installations of Rstudio. 

### Describe the behavior you expected

All Rstudio/R files should exist ONLY at the locations specified by my `.Renviron` file (including the `rstudio` socket file).  

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Per Tim: this is as designed and required for communicating between multiple instances of RStudio.  Unlikely to change this in the near term, so closing.  Thank you for raising this.

**Comment by kevinushey** [comment]
Surely we can find a location better than the home directory for these sockets? A user-specifix temporary directory?

**Comment by 392781** [comment]
Echoing @kevinushey.  My gripe isn't the existence of the socket files, it's the fact that they're stored in the home directory.

**Comment by jmcphers** [comment]
These should probably be stored in `XDG_RUNTIME_DIR`.
