### ISSUE TITLE
RStudio Server not following my .Renviron

### ISSUE THREAD

**Issue by abalter** [rstudio/rstudio#12592]
### System details

    RStudio Edition : Server
    RStudio Version :  2022.02.0 Build 443
    OS Version:  Red Hat Enterprise Linux Server release 7.9 (Maipo)
    R Version       :  R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem
Restart R in RStudio Server

### Describe the problem in detail

I have this in my .Renviron:

```
(base) balter@exahead1:~$ cat .Renviron
CONDA_PREFIX="/home/users/balter/conda"
R_LIBS_USER=/home/users/balter/conda/lib/R/libraries
RSTUDIO_WHICH_R=/home/users/balter/conda/bin/R
RSESSION_WHICH_R=/home/users/balter/conda/bin/R
R_USER=/home/users/balter/conda/bin/R
R_LIBS_SITE=/home/users/balter/conda/bin/R
R_INCLUDE_DIR=/home/users/balter/conda/lib/R/include
#R_HOME=/home/user/balter/conda/bin/R
```

However, when RSS starts, I have:

```
> .libPaths()
[1] "/home/users/balter/conda/lib/R/libraries"            
[2] "/home/groups/chse/WorkingData/z-chse_admin/chse4/4.1"
[3] "/usr/local/R/4.1.2/lib64/R/library"                  
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
> packageVersion('base')
[1] ‘4.1.2’
> .libPaths()
[1] "/home/users/balter/conda/lib/R/libraries"            
[2] "/home/groups/chse/WorkingData/z-chse_admin/chse4/4.1"
[3] "/usr/local/R/4.1.2/lib64/R/library"                  
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
> packageVersion('base')
[1] ‘4.1.2’
> .libPaths()
[1] "/home/users/balter/conda/lib/R/libraries"            
[2] "/home/groups/chse/WorkingData/z-chse_admin/chse4/4.1"
[3] "/usr/local/R/4.1.2/lib64/R/library"                  
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
> packageVersion('base')
[1] ‘4.1.2’
> .libPaths()
[1] "/home/users/balter/conda/lib/R/libraries"            
[2] "/home/groups/chse/WorkingData/z-chse_admin/chse4/4.1"
[3] "/usr/local/R/4.1.2/lib64/R/library"                  
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
> packageVersion('base')
[1] ‘4.1.2’
```

Why do I have these inconsistent versions of R? Why isn't my R version following what is in `.libPaths()`?

### Describe the behavior you expected

Being able to set my R executable and libraries in my .Renviron file.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
   I am on a managed server that I do not maintain.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@abalter Thank you for raising this! Can you also include what you get with the same commands when running R on its own, outside of RStudio? Presumably using the R located at `/home/users/balter/conda/bin/R`.

**Comment by abalter** [comment]
@ronblum -- ugh. Just noticed I repeated those commands like three times in the output I posted!

Here is at the command line on that server:

```
(base) balter@chse4:~$ R

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> .libPaths()
[1] "/home/users/balter/conda/lib/R/libraries"
[2] "/home/users/balter/conda/lib/R/library"
> R.version
               _
platform       x86_64-conda-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          4
minor          2.2
year           2022
month          10
day            31
svn rev        83211
language       R
version.string R version 4.2.2 (2022-10-31)
nickname       Innocent and Trusting
> packageVersion('base')
[1] ‘4.2.2’
```

**Comment by abalter** [comment]
@ronblum --- any thoughts about this?

**Comment by kevinushey** [comment]
Can you confirm what `.Library` and `.Library.site` are?

> "/home/groups/chse/WorkingData/z-chse_admin/chse4/4.1"

Given the presence of this path in the library paths, there's almost surely a `.Rprofile` or something similar changing the library paths even after the `.Renviron` has been processed.

**Comment by abalter** [comment]
Here is what I have:

```
(base) balter@chse4:~$ cat .Renviron 
CONDA_PREFIX="/home/users/balter/conda"
R_LIBS_USER=/home/users/balter/conda/lib/R/libraries
RSTUDIO_WHICH_R=/home/users/balter/conda/bin/R
RSESSION_WHICH_R=/home/users/balter/conda/bin/R
R_USER=/home/users/balter/conda/bin/R
R_LIBS_SITE=/home/users/balter/conda/bin/R
R_INCLUDE_DIR=/home/users/balter/conda/lib/R/include
#R_HOME=/home/user/balter/conda/bin/R
(base) balter@chse4:~$ cat .Rprofile
cat: .Rprofile: No such file or directory
```

root
```
(base) balter@chse4:/$ find ./ -not \( -path ./root -prune \) -not \( -path ./home -prune \) -name ".R*" 2>&1 | grep -v 'Permission denied'
./usr/local/R/4.2.1/bin/.RData
./usr/local/R/4.2.1/bin/.Rhistory
(base) balter@chse4:/$ ls
bin  boot  dev  etc  home  jupyterhub-proxy.pid  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

**Comment by abalter** [comment]
@kevinushey updates?

**Comment by kevinushey** [comment]
What is the output of `R.home()` in each case? It sort of feels like the version of R being launched in RStudio, versus the version of R being launched in your Terminal, are not the same.

For what it's worth, setting this:

```
RSTUDIO_WHICH_R=/home/users/balter/conda/bin/R
```

in your `.Renviron` would not suffice, since that profile is read by R (and so would be read after R has already been chosen)

**Comment by kevinushey** [comment]
Given that you're using RStudio Server, you should be able to set `rsession-which-r` to point at the R installation you want to use.

https://docs.posit.co/ide/server-pro/reference/rserver_conf.html#rsession-which-r

**Comment by abalter** [comment]
I'm glad I got your attention! But, I may have been too quick on the tricker. The real problem I am trying to solve is this one: https://github.com/rstudio/rstudio/issues/13184

What I and others have been struggling with is that RStudio is currently extremely opinionated about which R it will use for installation, startup, and the console. And, other than the option for RStudio Server, the user has no control over these.

Using my .Renviron was one of my attempts at a workaround.

A simple way I and others can run into the problem is by doing the following:

1. Spin up an ubuntu server
2. Install `{micromamba}` or other _conda_ flavor of your choice. (however, your choice _should_ be `{micromamba}`)
3. Install R and dependencies. Install linux dependencies.
4. Install RStudio or RStudio Server. In the latter case, make sure to set `rsession-which-r` in _/etc/rstudio/rserver/conf._
5. Try to use RStudio

It will fail.

The same happens in Windows. I can install conda and set it as my default python and R (through the environment variables) so that I can open an terminal and launch them. However, if I think install RStudio desktop, it will not start because it can't find `.libR.so`.

**Comment by Oakento** [comment]
Hi I got the same issue that Rstudio server doesn't follow `RSTUDIO_WHICH_R` whatever it's set in .bash_profile or .Renviron. I restarted the rstudio-server service but the R version remains the same. Any ideas?
