### ISSUE TITLE
Unable to start rsession undefined symbol: EXTPTR_PROT

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#12591]
RStudio Edition : server
    RStudio Version : 2023.03.0-daily+85.pro1
    OS Version      : rhel8 and rhel7 
    R Version       : 4.1.3

### Steps to reproduce the problem
unable to start rsession in workbench and rstudio server, seeing this error in logs

```2023-01-18T16:48:00.274356Z [rserver-monitor] ERROR 2023-01-18T16:48:00.274032Z [rserver] ERROR rserver-launcher: /usr/lib/rstudio-server/bin/rsession: symbol lookup error: /usr/lib/rstudio-server/bin/rsession: undefined symbol: EXTPTR_PROT; LOGGED FROM: void rstudio::server::ProcessMonitor::onProcessStderr(rstudio::server::ProcessMonitor::Process, const string&) src/cpp/server/ServerProcessMonitor.cpp:222|||```

### Describe the problem in detail
![Screenshot 2023-01-18 at 11 09 25 AM](https://user-images.githubusercontent.com/43964690/213298013-96d69a85-c187-4cbe-aa6a-9185b8834d34.png)

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dfalty** [comment]
Looks like this is reproducing with R version 4.1.3 and older. I deployed a rhel8 environment and 4.2.0, 4.2.1, and 4.22 work fine and sessions can be created. If I try to switch to 4.1.3, 4.1.1, 4.0.0, and 3.6.3 I get the "Cannot Connect to R Session" message.
`./deployIDE.sh -c rhel8 -v 2023.03.0-daily+85.pro1 -i t3.large -a`

**Comment by mikebessuille** [comment]
@romainfrancois This is urgent to fix for Cherry Blossom; seems you've introduced a dependency on a symbol that doesn't exist in older versions of R?

**Comment by romainfrancois** [comment]
On it.

**Comment by rich-rstudio** [comment]
verified on 2023.03.0-daily+271.pro7
