### ISSUE TITLE
New fun issue

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#12597]

**Comment by timtmok** [comment]
This is not fun

**Comment by gtritchie** [comment]
This is, like, 42 minutes old. Not new at all.

**Comment by jmcphers** [comment]
Did we really address this? I can still reproduce.

**Comment by mikebessuille** [comment]
FFS people.

**Comment by mikebessuille** [comment]
Addressed via https://github.com/rstudio/rstudio/pull/28
Removed all instances of 'method' and 'function' in the code, replacing them with more fun terms like balloon, unicorn, and 'ice_cream'.
