### ISSUE TITLE
Error when searching help for a string containing only one parenthesis

### ISSUE THREAD

**Issue by NgAMB** [rstudio/rstudio#12590]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2
    OS Version      : Windows 10
    R Version       : 4.2.2

### Steps to reproduce the problem
In the Help pane, search for a string containing an open parenthesis and no close parenthesis or visa versa, e.g. "table(" or "str)"
Related, using help.search() in this manner in the Console sometimes returns an error, e.g. help.search("table(") returns an error but help.search("str)") triggers the display of the "No result found" message in the Help pane.

### Describe the problem in detail
The Help pane displays "Internal Server Error" and nothing else
Related, using help.search() with an open parenthesis without a close parenthesis returns the error message
```
Error in grep(pattern, x, ignore.case = ignore.case, perl = use_UTF8) : 
  invalid regular expression 'str(', reason 'Missing ')''
In addition: Warning message:
In grep(pattern, x, ignore.case = ignore.case, perl = use_UTF8) :
  TRE pattern compilation error 'Missing ')''
```

### Describe the behavior you expected
Ideally, I would want something like "table(" to display only results where a function name ends in "table". Barring that, I would hope for the same functionality as searching for "table". Even displaying the "No result found" page could be more useful than an error message -- "No result found" prompts me to change my search parameters, while "Internal Server Error" makes me wonder what went wrong behind the scenes.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@NgAMB Thank you for raising the issue! I can also reproduce it in RStudio Server 2022.12.0+353 on Ubuntu 20.04 via MacOS 13.2. We'll review it as we continue to develop RStudio.
