### ISSUE TITLE
Better error when starting on unsupported macOS

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#12607]
RStudio currently requires macOS 11. However, when you try to run it on an older macOS, the error that comes back is very difficult to understand, and even sophisticated users don't realize that the problem is an outdated macOS. Here is one such error:

```
dyld: Library not loaded: @executable_path/../Frameworks/libssl.1.1.dylib
  Referenced from: /Applications/RStudio.app/Contents/Resources/app/bin/rsession
  Reason: no suitable image found.  Did find:
	/Applications/RStudio.app/Contents/Resources/app/bin/../Frameworks/libssl.1.1.dylib: cannot load 'libssl.1.1.dylib' (load command 0x80000034 is unknown)
	/Applications/RStudio.app/Contents/Resources/app/bin/../Frameworks/libssl.1.1.dylib: stat() failed with errno=1
```

Old macOS problems were one of the primary causes of "RStudio didn't start" reports on our community page before Electron. The Electron release, however, requires macOS 11, which has greatly exacerbated the problem to the point where it is now the *primary* cause of these reports. 

Here are 5 examples (and there are lots more).

https://community.rstudio.com/t/error-starting-r-the-r-session-failed-to-start/157858/2

https://community.rstudio.com/t/error-al-iniciar-rstudio-error-al-iniciar-r/156958/2

https://community.rstudio.com/t/im-getting-error-when-i-start-rstudio-error-starting-r/155752/2

https://community.rstudio.com/t/rstudio-is-not-working-on-my-macos/156428

https://community.rstudio.com/t/issue-with-installing-r-studio-in-mac/136704/2

We should add a macOS version test at startup. If the version is too old to be supported, we should show a friendly message suggesting that the user update macOS to use RStudio, or use an old version that still works with their operating system.

**Comment by ronblum** [comment]
Triage: Suggesting backlog-1 or even sooner.

**Comment by jmcphers** [comment]
Another report: https://community.rstudio.com/t/failure-to-startup-r-session-need-help/158162

**Comment by jmcphers** [comment]
Here's another one: https://community.rstudio.com/t/first-time-problems/158070

**Comment by gtritchie** [comment]
Another one was received via the accessibility alias from a user on High Sierra (10.13). I responded directly to them and pointed them towards the community for future questions of this sort.

> Hello! I have no experience with R, and I am using it for my college statistics course. I have both R 4.2.2 and RStudio (I am using a MacBook Air with macOS high sierra), and when I went to open RStudio, I got the following error message:
> 
> RStudio 2022.12.0+353 "Elsbeth Geranium " (7d165dcf, 2022-12-03) for macOS
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
> 
> dyld: Library not loaded: @executable_path/../Frameworks/libssl.1.1.dylib

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+312.
- MacOS 13.2, which is supported: Starts up and runs as it should.
- MacOS 10.15, which is unsupported: Starts up and runs because it can.
- MacOS 10.13, which is unsupported: Doesn't start up, issuing the following error.


![Image](https://user-images.githubusercontent.com/31009952/218184762-a2dea8d3-0eea-4e19-a747-b3ae5d53eaac.png)
