### ISSUE TITLE
Render LaTeX blocks produced from output of R code in RStudio Quarto documents

### ISSUE THREAD

**Issue by kcandrews** [rstudio/rstudio#12603]
Right now it is possible to specify `output='asis'` or `results='asis'` and see the LaTeX output in the rendered document. However, this does not help at all for treating RStudio as a poor person's computer algebra system with Ryacas or caracas packages. It would be really convenient if the resulting `$$` could be rendered inline. I would imagine such support would also be welcomed for users of tools like SymPy on the python side.

```
library(Ryacas)
quarto_math = function(x) {
  cat("$$", x, "$$", sep = "\n")
}
x = ysym("x")
a = ysym("a")
(x - a)^3 |> y_fn("Expand") |> tex() |> quarto_math()
```

**Comment by ronblum** [comment]
@kcandrews Thank you for the suggestion! We'll consider it as we continue to develop RStudio.
