### ISSUE TITLE
Preview button for a table in a SQL connection tries to read all data - If the table is very big, results take forever...

### ISSUE THREAD

**Issue by fooinha** [rstudio/rstudio#12602]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353 - "Elsbeth Geranium" Release (7d165dcf, 2022-12-03) for macOS
    OS Version      :  macOS Monterey 12.6 - x86_64-apple-darwin17.0  
    R Version       :  version 4.1.2 (2021-11-01) 

### Steps to reproduce the problem

When using the SQL navigation panel , using ODBC to connect to a Postgres database, and, by clicking the preview button for a table that has Millions of rows -- in this case 69M , the results take forever.

The CPU load increases, and the results never get available.

### Describe the problem in detail

By looking to databases statements logs, it seems that a `SELECT *` statement is being sent without any LIMIT n clause.
With tables with millions of rows, this could mean, an extraordinary amount of memory to store all the rows objects. 

<img width="1440" alt="rstudio-read-all-data" src="https://user-images.githubusercontent.com/8560528/213566277-884ec0e5-c62b-44fe-b393-168088c2ed63.png">

### Describe the behavior you expected

I expected to have a preview ready in seconds with of a sample of the rows from the big table.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fooinha Thank you for raising this! We'll review this as we continue development of RStudio.
