### ISSUE TITLE
src/cpp/core/include/core/Thread.hpp uses std::set without #include <set>

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#12611]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353 
    OS Version      : FreeBSD 13.1

### Steps to reproduce the problem
Build breaks:
```
In file included from /wrkdirs/usr/ports/devel/RStudio/work-desktop/rstudio-2022.12.0-353/src/cpp/core/ExponentialBackoff.cpp:18:
In file included from /wrkdirs/usr/ports/devel/RStudio/work-desktop/rstudio-2022.12.0-353/src/cpp/core/include/core/ExponentialBackoff.hpp:24:
/wrkdirs/usr/ports/devel/RStudio/work-desktop/rstudio-2022.12.0-353/src/cpp/core/include/core/Thread.hpp:362:9: error: no template named 'set' in namespace 'std'
   std::set<T, std::less<T>, std::allocator<T> > set_;
   ~~~~~^
1 error generated.
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgenco** [comment]
This looks a boost 1.80.0 -> 1.81.0 change. I made a [small patch](https://github.com/jgenco/jgenco-overlay/issues/4#issuecomment-1368061420) that seemed to work on Linux.

**Comment by ronblum** [comment]
Thanks @yurivict and @jgenco!

**Comment by vkhodygo** [comment]
@ronblum 
The problem persists on rolling-release Linux machines as well.
