### ISSUE TITLE
RStudio Desktop won't launch

### ISSUE THREAD

**Issue by fannylinn** [rstudio/rstudio#12618]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2022.12.0+353
    OS Version      :  Windows 11 Pro
    R Version       :  4.2.2

### Steps to reproduce the problem
Install R 4.2.2 and RStudio 2022.12.0+353 on Windows 11. Launch RStudio.
### Describe the problem in detail
I updated RStudio to the latest version. When I try and launch the RStudio logo shows up (the light-blue circle) but nothing happens after that. When I used task manager to end the session I got a crash report that read "Unable to retrieve user home path". I uninstalled and reinstalled R and RStudio. I also deleted the files in %appdata$/RStudio and %localappdata%/RStudio to reset the state. Finally, I deleted all startup files I could find on my laptop. Nothing has solved the issue. I have now gone back to RStudio 2022.07.2-576 and this version works fine. 

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/10487255/diagnostics-report.txt)

### Describe the behavior you expected
I expected RStudio to launch with a user interface. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fannylinn Thank you for raising this! We've been struggling to figure out this known issue. It's covered by issues #12469 and #12497, so I'm closing this as a duplicate and adding your information to it.
