### ISSUE TITLE
revealjs-specific insert menu items not available with extension formats

### ISSUE THREAD

**Issue by Aariq** [rstudio/rstudio#12617]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353
    OS Version      : macOS 13.1 (22C65)
    R Version       : 4.2.2
    Quarto Version  : 1.2.313

### Steps to reproduce the problem

Use a revealjs extension to create a new .qmd.  For example `quarto use template EmilHvitfeldt/quarto-nes-theme`.  Then, open it in RStudio with the visual markdown editor.  Look in the insert menu and see that there are not "Slide ..." options.

### Describe the problem in detail

If the `format:` of a .qmd is `revealjs` then revealjs-specific items are available in the insert menu such as "Slide Column", "Slide Pause", and "Slide Notes".  However, if a revealjs extension is uses so that `format: themename-revealjs` then these no longer show up even if the theme produces revealjs slides.

### Describe the behavior you expected

I'd expect RStudio to figure out if slides are rendered regardless of the custom format used.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Aariq Thank you for raising this! We'll review this as we continue development of the visual editor and the integration between RStudio and Quarto.
