### ISSUE TITLE
Autocomplete for value matching in dplyr's filter function

### ISSUE THREAD

**Issue by scottdaniel** [rstudio/rstudio#12628]
I love the new autocompletion capability within Rstudio:
![image](https://user-images.githubusercontent.com/1494238/214430605-eb70698c-0065-49fe-81b5-22d81e5fc5fd.png)

This makes it so that I don't have to remember all the column names in a data frame.

A similar problem I face is remembering what values I have within each column.

If I have something simple like this:
`my_df <- tibble(char_variable = factor(c("A", "B", "C")), num_variable = c(1,2,3))`

When I go to filter something, it would be great if Rstudio was able to autocomplete the values within the `char_variable` column. So when I type this:
`my_df %>% filter(char_variable %in% "`
Tab'ing at that point would show a list of unique values in the `char_variable`.

Thank you for making such a useful product. My job would be 10x harder without it!

**Comment by ronblum** [comment]
@scottdaniel Thank you for the suggestion and the kind words! I'm glad that we're helping make you job easier—that's our goal!
