### ISSUE TITLE
IFrames with external URLs pop up multiple time in separate windows

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#12620]
It seems that issue https://github.com/rstudio/rstudio/issues/2756 came back with Electron 

The reprex there is causing the issue 
````r
library(htmltools)
print(browse = TRUE, tags$iframe(src="https://www.rstudio.com/"))
````

On Windows, it opens in the IDE viewer but also 4 tabs in my Google Chrome opened browser

Issue can be encountered with anything showing in the browser like Quarto document 

````markdown
---
format: html
---

## sli.do iframe

```{=html}
<iframe src="https://app.sli.do/event/x37QvAtyvHXNGhFenp3cV1/embed/polls/32cd4326-7c95-4b38-9cef-cdc163ca790e" width="300" height="400"></iframe>
```
## iframe

```{=html}
<iframe src="https://quarto.org/" width="500" height="400"></iframe>
```
## YouTube iframe

```{=html}
<iframe src="https://www.youtube.com/embed/MBCPgQxlrD" width="560" height="315"></iframe>
```
````

Problem also encountered by @mine-cetinkaya-rundel who share the above document in Slack, and working on Mac OS I believe.

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.3.0.270
    OS Version      : Windows 10 x64 (build 22621)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

**Comment by ronblum** [comment]
@cderv Does this look like the same as issue #12494, although with a different reprex?

**Comment by cderv** [comment]
Yes I think it is indeed - it is the same. I missed it sorry. Should we close this on ? 

You get more example above that trigger the behavior. It is not only with Qmd or Rmd, but also from R code. 

Probably somehow linked to what IDE consider to be safe URL or not, as you can observed from the previous example above that Youtube Iframe does not open in external browser

https://github.com/rstudio/rstudio/blob/c6e146b27186c488d4e40c76ed1ec4cc192b5827/src/node/desktop/src/main/url-utils.ts#L79-L90

Hope it helps

**Comment by ronblum** [comment]
@cderv No sweat! I copied all of your description and code, so that we can check it all when testing, and I'll close this one.
