### ISSUE TITLE
Fix autocompletion of column names with "#" in `dplyr::select()`

### ISSUE THREAD

**Issue by dchiu911** [rstudio/rstudio#12632]
### System details

    RStudio Edition : RStudio Desktop
    RStudio Version : 2022.12.0+353 Elsbeth Geranium (desktop)
    OS Version      : macOS Ventura 13.0
    R Version       : R version 4.2.2 (2022-10-31)

### Steps to reproduce the problem

```r
library(dplyr)
tmp <- tibble(`a#b` = 1, `c d` = 2)
tmp %>% select(`a#b`, )
```

### Describe the problem in detail

When I press tab after the comma in the `dplyr::select()` call above, the `c d` column does not show up in an autocomplete popup because the tibble contains a column with the "#" string.

However, the autocomplete works in the following chunk

```r
tmp <- tibble(`a b` = 1, `c d` = 2)
tmp %>% select(`a b`, )
```

### Describe the behavior you expected

I should get the autocomplete popup in the select call for data that contains column names with "#".

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dchiu911 Thank you for raising this! I can reproduce the issue in RStudio Desktop 2022.07.2+576 and 2023.03.0-daily+272 on MacOS 13.2. Interestingly, if the order is reversed, the autocompletion works:
<img width="278" alt="autocomplete" src="https://user-images.githubusercontent.com/31009952/214856390-48e26c14-bfbb-4e45-9515-4b7d3dd4c0ea.png">

We'll review this as we continue to develop RStudio.
