### ISSUE TITLE
Viewer does not refresh automatically

### ISSUE THREAD

**Issue by bixiou** [rstudio/rstudio#12647]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Windows 10
    R Version       : 4.2.2

### Steps to reproduce the problem
Load the package `plotly` and run `plot_ly(x = c(1), y = "Test", type = 'bar')`. Then, change the Viewer width or height, and observe that the plot does not change.

### Describe the problem in detail
I have two computers, each with Windows 10, R 4.2.2 and the last RStudio version.

On my home computer, the Viewer pane automatically refreshes when I adjust its size. This is the normal/expected behavior.

On my professional laptop, the Viewer does not refresh. This is annoying because I am using Plotly to show graphs in the Viewer pane, and the graph parameters (width of the bars, placement of the legend...) should be responsive to the pane's size.

### Describe the behavior you expected
Each time the user adjusts the Viewer pane width or height, the pane should refresh, as with `rstudioapi::executeCommand('viewerRefresh')`.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bixiou Thank you for raising this! For each system, are you only using the laptop screens, or are you using external monitors?

**Comment by bixiou** [comment]
External monitor for both, but I'll check on my laptop on Thursday if the problem remains on the laptop screen.

**Comment by bixiou** [comment]
Hi @ronblum, I have the same problem on the laptop screen.
