### ISSUE TITLE
NEWS button does not work as expected for a local CRAN-like repo

### ISSUE THREAD

**Issue by djhurio** [rstudio/rstudio#12648]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Windows 11 Enterprise
    R Version       : 4.2.2

### Steps to reproduce the problem

Update a package from a local CRAN-like repository and press the corresponding NEWS button.

### Describe the problem in detail

We are maintaining a simple local CRAN like repository (it has been built using `drat::insertPackages`). Users of the repository are updating R packages using the RStudio GUI (Update button in the Packages pane). I have added the "NEWS.html" file on the repository under the URL "https://cran.local/web/packages/pck.name/news/NEWS.html" where "pck.name" is the name of a package. The problem is the NEWS button from the "Update Packages" window can not correctly detect this URL.

![image](https://user-images.githubusercontent.com/744800/215526177-9e7222c1-f900-41a9-b093-93b09cf149cc.png)

After pressing the NEWS button the URL "http://127.0.0.1:23961/news/news.html" is opened (which is not accessible) and there a warning message in the console:

```
Warning message:
In .rs.rpc.get_package_news_url("pck.name", "C:/Users/user/AppData/Local/R/win-library/4.2") :
  Failed to infer appropriate NEWS URL: using 'news/news.html' as best-guess candidate
```

I have investigated the function `.rs.rpc.get_package_news_url()`. I suspect the problem is in [the part where the prefix for the NEWS URL is being detected](https://github.com/rstudio/rstudio/blob/3742521ab2e67528090358a42d9f13933f4400df/src/cpp/session/modules/SessionPackages.R#L659-L667), namely:

```
   # determine an appropriate CRAN URL
   repos <- getOption("repos")
   cran <- if ("CRAN" %in% names(repos))
      repos[["CRAN"]]
   else if (length(repos))
      repos[[1]]
   else
      .Call("rs_rstudioCRANReposUrl", PACKAGE = "(embedding)")
```

The current logic is the following:

- The repo URL with a name "CRAN" is chosen as a prefix.
- If there is no such repo URL, the first repo URL from the `repos` is taken.

I suppose this logic is wrong as it assumes a package will be published at the official CRAN repository which is not the case for me.

I can make it work if those conditions are fulfilled.

- None of the `repos` names is "CRAN".
- The URL of the local repo should be the first one in the `repos`.

For example:

```
> getOption("repos")
                                               CL 
                             "https://cran.local" 
                                             RSPM 
"https://packagemanager.rstudio.com/cran/latest/" 
```

Then `.rs.rpc.get_package_news_url()` provides a correct URL to the NEWS.html file and the NEWS button works as expected.

### Describe the behavior you expected

I expect the NEWS button to be working also for the packages updated from a local CRAN-like repo. Namely, I expect the function `.rs.rpc.get_package_news_url()` to detect the URL prefix using the repo URL from which a package is being updates. That would solve this problem.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Does your package declare the source Repository in its DESCRIPTION file? E.g. a field like:

```
Repository: CL
```

In theory, we could try to match the declared repository name in the DESCRIPTION file with the set of named R repositories, and choose that repository when attempting to query NEWS.

Or perhaps we should try each repository one-at-a-time and take the first that works?

**Comment by djhurio** [comment]
Hello @kevinushey ! I do not have a `Repository` item in the `DESCRIPTION` file. I have not added it as it is not official item for the `DESCRIPTION`. However I am aware some packages like `packrat` do [use it](https://stackoverflow.com/questions/56277832/repository-field-in-r-description-files). Obviously I can add it if needed.

I wonder why you can not detect the repo URL the same way as `update.packages()` does it? If `update.packages()` knows there is an update of a package, it should know also the URL of that repo providing an update. Is it not?

**Comment by kevinushey** [comment]
> I have not added it as it is not official item for the DESCRIPTION.

For context, all packages distributed on CRAN have a field `Repository: CRAN` added to their DESCRIPTION file, so there's at least some precedent for package repositories to include their repository name in the DESCRIPTION files of the packages they publish.

> I wonder why you can not detect the repo URL the same way as update.packages() does it? If update.packages() knows there is an update of a package, it should know also the URL of that repo providing an update. Is it not?

Right, I think we could; the original goal here was to avoid some potentially un-necessary web requests.

**Comment by djhurio** [comment]
Thanks! So I learn `Repository` contains a given name of a repo (not URL), for example `Repository: CRAN`. This does not look as a solid solution as someone can name his repos as he wants for the `repo` option. For example, we do not force our users to name our local repo with a specific name. Obviously we could do so but there was no need for that so far.
It would be more useful if a `Repository` item could contain a repo URL. Maybe it can be URL?

**Comment by djhurio** [comment]
Hello, is there any progress on this issue?

**Comment by gorkang** [comment]
For me, this has been an ongoing issue since I started using the RSPM with binaries for ubuntu 22.04: 

options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/jammy/latest"))

**Comment by minemR** [comment]
This is the main reason I am not using RSPM as I can not easily access NEWS. Are there any plans to look at this?

**Comment by ronblum** [comment]
This appears to be working for me in RStudio Desktop 2024.04.0-daily+668 on Windows 11. However, to get a better idea of real-life usage, would anyone be willing to try this out with a daily build of the release in progress, 2024.04.0 (Chocolate Cosmos)? It's available at https://dailies.rstudio.com. Please note that these builds are for testing purposes only, not production. Thanks!

**Comment by m20l22** [comment]
Thanks a lot! I will try this hopefully during this week or next.

**Comment by gorkang** [comment]
The issue is still there for me in Ubuntu 22.04 with RStudio 2024.04.0-daily+675

After clicking the NEWS icon, an empty browser tab opens in http://127.0.0.1:28545/news/news.html


Full version:

> RStudio 2024.04.0-daily+675 "Chocolate Cosmos" Daily (e33a035105519e9fb1040c98fa46e41d151bafa2, 2024-04-03) for Ubuntu Jammy
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.0-daily+675 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.550 (/opt/quarto/bin/quarto)

**Comment by kevinushey** [comment]
@gorkang can you please be more explicit on what steps you took? What is the output of `getOption("repos")`? What package were you trying to view NEWS for? How was that package installed?

**Comment by gorkang** [comment]
Sorry @kevinushey, I was very vague.

`getOption("repos")`: 
 CRAN 
"https://packagemanager.rstudio.com/all/__linux__/jammy/latest"

This has been happening since I started using the RStudio Package Manager, at least a year ago. AFAIK, it happens with all the packages. I normally install them with `install.packages()` but I also used `renv` or `pak`.

Below an edited screencast to show how with "https://packagemanager.rstudio.com/all/__linux__/jammy/latest" the NEWS do not appear, and with "https://cloud.r-project.org" they do appear.

Please, let me know if you need any other detail.

Thanks!

https://github.com/rstudio/rstudio/assets/6491790/3ccabcdb-18c4-428c-b702-824949846ce9

**Comment by kevinushey** [comment]
Ah, thanks! I think this is because you're using `packagemanager.rstudio.com` rather than `packagemanager.posit.co`, and I had missed that case for the public PPM instance. I can fix that up.

**Comment by gorkang** [comment]
Yes! That was it! Thanks!

**Comment by ronblum** [comment]
Shoot, for what it's worth, I missed that too and was flummoxed because I was otherwise using the same environment. 😥

**Comment by kevinushey** [comment]
Thanks @mabuimo -- this was specifically in reference to behavior in recent daily builds of RStudio. These are available at https://dailies.rstudio.com, if you'd like to test the behavior there.

**Comment by kevinushey** [comment]
Again, as I said, a fix for this is available in the latest daily builds at https://dailies.rstudio.com, if you would like to test.

**Comment by kevinushey** [comment]
Thank you for testing and reporting back -- much appreciated!

**Comment by m20l22** [comment]
Hello! It looks the NEWS button does not work if https://p3m.dev/cran has been set as the package repository. I have observed this on:

- RStudio Desktop on Windows 11 with https://p3m.dev/cran/latest
- RStudio Server on Ubuntu 22.04 with https://p3m.dev/cran/__linux__/jammy/latest

I am receiving the warning message:

> Failed to infer appropriate NEWS URL: using 'news/news.html' as best-guess candidate

The NEWS button is working with the respective https://packagemanager.posit.co/cran URLs.

**Comment by kevinushey** [comment]
Thanks; I made a change in https://github.com/rstudio/rstudio/commit/ad8b43cdf6a68e4bcc72220b394fe9a97ba5496d that should help.
