### ISSUE TITLE
Error gpu_init.cc

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#12646]
Hello,

I've just installed the latest RStudio desktop. I had to change the link on my desktop, previously it was `/usr/lib/rstudio/bin/rstudio`, and now it is `/usr/lib/rstudio/rstudio`.

I have a small problem now: when I launch RStudio, the RStudio icon does not appear in the bar at the bottom of the desktop. Well, I agree it is not dramatic ;-)

But I'm wondering about the following error message and I thought it might interest you. When I launch RStudio from a terminal, this error message is printed (but everything seems to work fine):

```
[1874308:0130/145500.255697:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
```

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022-12-3.0+353
    OS Version      : Linux Mint 20
    R Version       : 4.2.2

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ramiromagno** [comment]
I also had do the fix you mentioned.

**Comment by ronblum** [comment]
@stla and @ramiromagno the errors messages are covered in #10782. If you switch to software rendering, do the messages go away? <kbd>Tools -> Global Options -> Advanced -> Rendering Engine -> Software</kbd>

**Comment by stla** [comment]
> @stla and @ramiromagno the errors messages are covered in #10782. If you switch to software rendering, do the messages go away? Tools -> Global Options -> Advanced -> Rendering Engine -> Software

Yes, the error message has gone away. Thanks.

**Comment by ramiromagno** [comment]
@ronblum: Yes, with software rendering the message is gone.
