### ISSUE TITLE
dictionary file add

### ISSUE THREAD

**Issue by issactoast** [rstudio/rstudio#12651]
![image](https://user-images.githubusercontent.com/13303749/215554285-5f1025d0-d52a-40a2-99ff-a574ba00ef83.png)

Hi I think there are Kor dictionary file which is compatible to Hunspell. 
https://github.com/titoBouzout/Dictionaries/blob/master/Korean.dic
https://github.com/titoBouzout/Dictionaries/blob/master/Korean.aff

Can we add these dic and aff file to the list of langugages that main dictionary language dropbox shows?
I know I can copy and paste to the AppData folder but I want RStudio automatically install these when user hit the install other language button

**Comment by ronblum** [comment]
@issactoast Thank you for the enhancement request! We'll review this as we continue development of RStudio. Can you confirm that spellcheck works correctly when you add the dictionaries?
