### ISSUE TITLE
"Copy To..." deletes all files in Home directory

### ISSUE THREAD

**Issue by stibu81** [rstudio/rstudio#12653]
### System details

    RStudio Edition : Server
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Ubuntu 20.04.5 LTS
    R Version       : 4.2.2

### Steps to reproduce the problem

* Create a new user and login into RStudio
* Create two folders `test` and `test2` in the user's home directory. Create a file in each folder. The files pane now looks like this (the folder `R` was created automatically):
![image](https://user-images.githubusercontent.com/7131000/215708104-a9d8a75f-7b81-4777-b659-603b23984fbd.png)
* Select the folder `test2` and click on "More - Copy To...".
* In the dialogue enter `~` and press return:
![image](https://user-images.githubusercontent.com/7131000/215708352-83b78e84-6b24-488e-b2ad-2fcf617edf08.png)
* RStudio shows an error dialogue "File exists" and all files and folders in the home directory will be deleted.

### Describe the problem in detail

Copying files deletes the home directory without any warning.

This seems only to happen when copying a folder. I have not managed to delete the Home directory by copying a file.

### Describe the behavior you expected

I'm not sure what the correct behaviour would be. Maybe an error message. And certainly, no files should be deleted.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
I was not able to reproduce on Desktop (windows and Ubuntu22).

I suspect it is because desktop uses the OS native dialogs. Windows doesn't expand `~` to a home directory. Ubuntu just gave a "failed" error message.

**Comment by melissa-barca** [comment]
Thank you for reporting this. I was able to reproduce with open source server 2022.12.0+353 and workbench 2022.12.0+353.pro13.

**Comment by melissa-barca** [comment]
@mikebessuille I've fixed this on `main` and notice you tagged this for backport. I believe the bug exists in all currently supported versions so should it be backported to all of them?

**Comment by mikebessuille** [comment]
Since this has existed for awhile, I don't think it needs to be backported to many releases.  However, I do think we should backport it to Elsbeth Geranium, since we're going to do a patch for it sometime soon, particularly for some workbench customers.  I've created a milestone "Patch 2022.12.1" for it; could you create a patch ticket there, linked to this?

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0-daily+301 OS Server & Workbench
Ubuntu22

IDE correctly just moves dialog box to `~` as home directory, doesn't delete anything.
