### ISSUE TITLE
Rstudio loses 'focus' on the script pane

### ISSUE THREAD

**Issue by rasmusrhl** [rstudio/rstudio#12656]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      :  Windows 10 Pro 21H1
    R Version       :  R version 4.2.2 (2022-10-31 ucrt)

### Steps to reproduce the problem

The problem occurs in different conditions (sometimes involving pressing the 'Alt'-key), but I can reproduce one of them:

* Start Rstudio
* Create a new script.
* Pop-out the script in a new window.
* Type some code (e.g. `2+2`), select it, and press `ctrl + shift + p` to open command pallete and click 'style selection'. 
* **Problem**: _Now focus is lost._

* **Failed workaround**: `ctrl + 1` does not regain focus on script, only mouse-click can regain focus on script.

### Describe the problem in detail

*  Sometimes Rstudio loses the 'focus' on the script pane/window.
* By 'focus' I mean ability to type text.
* I can regain focus by clicking with the mouse in script pane/window (but this is not optimal).
### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@rasmusrhl Thank you for raising this! I can also reproduce this in RStudio Desktop 2022.07.2+576 on MacOS 13.2. We'll review this as we continue development of RStudio.
