### ISSUE TITLE
R will not restart (Rstart R) after a the document has been rendered

### ISSUE THREAD

**Issue by rccline** [rstudio/rstudio#12655]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
    OS Version      : x86_64, mingw32 
    R Version       : R version 4.2.2 (2022-10-31 ucrt)

### Steps to reproduce the problem
Rstudio session will restart until Quarto is Rendered.  After the first render, R Session cannot be restarted unless I quit R using "End Task" with the Task Manager.  I can end the session with ending _"Deno: A secure runtime for JavaScript and TypeScript_" task running with the RStudio session.  

### Describe the problem in detail.  After a Qurto document is rendered, I cannot restart an R session.  I can import a csv file with library(readr) and I can still restart the r session.  I cannot create a reprex.  I get the following error:  
> reprex:::reprex_addin()
Loading required package: shiny
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected  

After the forced "End Task" the new R session has objects which were imported in the previous session appearing in the environment.  R does not recognize the objects.  To use the objects in the environment, they must be reimported or re-craeated.  

### Describe the behavior you expected

I expect the session to restart.  Instead, the progress wheel just rotates "Restarting R..."  

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report). DIAGNOSTICS REPORT WILL NOT RUN
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rccline** [comment]
I have no idea why I could not restart session without deploying End Task from my Task Manager.  I suspected it was a bug introduced by {flexdashboard}.  I uninstalled {flexdashboard} but the problem persisted.  Since that time, the issue has resolved itself.  I do not know what caused it, nor do I know how it resolved.  I am closing this issue.

**Comment by ronblum** [comment]
@rccline Thank you for the update! If you run into the issue again, though, please let us know.
