### ISSUE TITLE
hash-pipe style options are not copied with option-command-i

### ISSUE THREAD

**Issue by cscheid** [rstudio/rstudio#12669]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2022.12.0-daily+287 (2022.12.0-daily+287)
    OS Version      : macOS 13.0.1 (22A400)
    R Version       : 4.2.2

### Steps to reproduce the problem

Create a .qmd file with a single r code cell:

````
```{r}
#| echo: false
cat("Hello")
```
````

### Describe the problem in detail

When using option-command-i to split a code-cell in two, RStudio copies the knitr-style chunk options (that's great!). Like so:

````
```{r, echo=FALSE}
cat("Hello")
```
````

<img width="325" alt="image" src="https://user-images.githubusercontent.com/285675/217020134-fd743f06-23c5-4d6d-a74c-b8c3e462146d.png">

After hitting option-command-i, you get this:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/285675/217020220-9f139b37-cc78-4c5c-9861-2a05042bd742.png">
 

### Describe the behavior you expected

Ideally, RStudio would catch the hash-pipe options in addition to the triple-tick line, and copy those as well. But using hash-pipe style, the options are not copied along. If we start with this:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/285675/217020321-e749b367-f649-4e56-8c5b-e18217da2198.png">

we end up with this:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/285675/217020350-c2400f48-8e90-451a-beb1-ff9c58c9f062.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: This is the case for both R Markdown and Quarto files.
