### ISSUE TITLE
Problems recognition of “ quotation marks  

### ISSUE THREAD

**Issue by MikelovA** [rstudio/rstudio#12666]
![quotation mark error](https://user-images.githubusercontent.com/123795541/216798091-3881dada-0073-4628-8c9e-0965d30c2221.PNG)

### System details

    RStudio Edition : 
    RStudio Version : Ratudio Pro Build 353.pro20
![image](https://user-images.githubusercontent.com/123795541/216798243-3c4d3e18-47be-4d22-b8b0-0cc126f906f4.png)

    OS Version      : windows 10 
   

### Steps to reproduce the problem
 I copied code from the web that had different style of quotation mark that posit cloud did not recognize
### Describe the behavior you expected
that the quotation be recognize.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is expected; so-called "smart quotes" are not accepted as quotation marks by the R language.
