### ISSUE TITLE
Bad indentation with more than 10 lines of comments after a pipe

### ISSUE THREAD

**Issue by LuisLauM** [rstudio/rstudio#12674]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353 "Elsbeth Geranium" 
    OS Version      : Windows 10
    R Version       : 4.2.2

### Steps to reproduce the problem

```
mtcars |> 
  
  # Line 1
  # Line 2
  # Line 3
  # Line 4
  # Line 5
  # Line 6
  # Line 7
  # Line 8
  # Line 9
  # Line 10
# Line 11
# Line 12
# Line 13
  sapply(length)
```

### Describe the problem in detail

When you use more than 10 lines of comments after a pipe (both |> or %>%), the indentation changes and make it change for all the code after. This is a little bit annoying because sometimes I use the function `filter` with many conditions that I need to describe and comment.

### Describe the behavior you expected

I suggest to correct this bahaviour in order to keep the indentation with 10 or more lines of comments.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@LuisLauM Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.4.1743 and 2023.03.0-daily+272 on MacOS 13.2. This is true for both R files and an R chunk in an R Markdown file. We'll review this issue as we continue development of RStudio.

**Comment by LuisLauM** [comment]
Hey, please, don't forget this issue. It's still pending and (maybe I'm wrong) it doesn't look like being a big problem in the RStudio 
code (again, maybe I'm wrong).

**Comment by LuisLauM** [comment]
> mtcars |> 
>   
>   # Line 1
>   # Line 2
>   # Line 3
>   # Line 4
>   # Line 5
>   # Line 6
>   # Line 7
>   # Line 8
>   # Line 9
>   # Line 10
> # Line 11
> # Line 12
> # Line 13
>   sapply(length)

Hello, hello. Please, do not forget this issue, is still persisting in the new 2023.12.0 version. Thanks!

**Comment by kevinushey** [comment]
Presumedly this is because of this code:

https://github.com/rstudio/rstudio/blob/6f7af1eab02568be3de327190a96fc5dba2dc247/src/gwt/acesupport/acemode/r_code_model.js#L1558-L1561

If necessary, we could remove / adjust that limit of 10.

**Comment by LuisLauM** [comment]
Hi. Yes, well, I don't think I'm the best person to suggest the best solution, but I do think it's something necessary. A practical example: when you run a `filter` (or a `mutate` or similar) applying several criteria (whose explanation takes more than 10 lines), this problem appears and cuts the indentation of the following lines making you think that there is some typing error (e.g. some wrongly closed parenthesis).

**Comment by ronblum** [comment]
Verified in Posit Workbench 2024.04.0-daily+397.pro21 on Ubuntu 20 via Chrome on MacOS 14.3.

Checked
- With comments longer than 10 lines (went to 20)
- That subsequent code isn't affected
- Interrupting comments with code and then restarting with comments
