### ISSUE TITLE
Oracle RStudio's Professional driver misbehavior with `params` of length > 1

### ISSUE THREAD

**Issue by ThomasSoeiro** [rstudio/rstudio#12673]
### System details

    RStudio Edition : RStudio Pro
    RStudio Version : 2022.12.0 Build 353.pro20 
    OS Version : Red Hat Enterprise Linux Server 7.8 (Maipo)
    R Version : 4.1.2 (2021-11-01)

### Steps to reproduce the problem

1. Connect to an Oracle database using `package:DBI`/`package:odbc` and RStudio's Professional driver;
2. Pass a list of vector(s) as `params` to `dbBind()`/`dbGetQuery()`;
3. `dbFetch()`/`dbGetQuery()` fetches only the first result set without warning.

The issue was first reported against `package:odbc` in r-dbi/odbc#537. [It was suggested](https://github.com/r-dbi/odbc/issues/537#issuecomment-1419628789) to report it here so it can be forwarded it to the third party vendor that supplies the database drivers. Once fixed in the driver, `package:odbc` will be able to let that surface to the user.

### Describe the problem in detail

When using `package:DBI`/`package:odbc` with RStudio's Professional driver, `dbFetch()`/`dbGetQuery()` fetches only the first result set without warning:
```r
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "xxx")

dbWriteTable(con, "iris", iris)

query <- "SELECT * FROM \"iris\" WHERE \"Species\" = ?"
q_params <- list(c("setosa", "versicolor"))

res <- dbGetQuery(con, query, params = q_params)

nrow(res)
# [1] 50

# expected results
nrow(iris[iris$Species %in% c("setosa", "versicolor"), ])
# [1] 100
```

When using `package:DBI`/`package:odbc` with Oracle's OEM driver, `dbFetch()`/`dbGetQuery()` raises an error:
```r
res <- dbGetQuery(con, query, params = q_params)
# Error in result_bind(res@ptr, params, batch_rows) :
#   nanodbc/nanodbc.cpp:1753: 00000: [Oracle][ODBC]SELECT with an array of parameters is not supported
```

And `package:ROracle` raises an error too:
```r
res <- dbGetQuery(con, query, data = q_params)
# Error in .oci.GetQuery(conn, statement, data = data, prefetch = prefetch,  : 
#   bind data has too many rows
```

### Describe the behavior you expected

Ideally (but I don't if it is possible with Oracle), RStudio's Professional drivers should allow to use a vector of length > 1 as `params` as documented in [`?DBI::dbBind`](https://dbi.r-dbi.org/reference/dbbind):
> The elements of the params argument do not need to be scalars, vectors of arbitrary length (including length 0) are supported. For queries, calling `dbFetch()` binding such parameters returns concatenated results, equivalent to binding and fetching for each set of values and connecting via `rbind()`. 

This is also documented in the [Advanced DBI Usage vignette](https://cran.r-project.org/web/packages/DBI/vignettes/DBI-advanced.html).

Otherwise, it should report appropriate feedback to allow `package:odbc` to reports the error as with Oracle's OEM driver.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ThomasSoeiro Thank you for raising this! Are you evaluating the professional version of RStudio Desktop, or you already a customer?

**Comment by ThomasSoeiro** [comment]
The institution through which I access RStudio is already a customer. This is not a trial version. I'm an "affiliate" researcher (not the contract holder) so I don't have detailed information about the contract.

**Comment by ronblum** [comment]
@ThomasSoeiro Since you're a customer, can you also file a Support ticket at https://support.posit.co/hc/en-us/requests/new? Please reference this issue. Also, the drivers are third-party applications, so I also filed the issue in a repo dedicated to them. It's a private repo, but the main communication will be through the professional support system.

Thanks!

**Comment by ThomasSoeiro** [comment]
It's done. Thanks!

**Comment by ThomasSoeiro** [comment]
The issue is not stale. The new version of RStudio ODBC driver does not seem to fix the issue according to tests from my IT department. I will report after more testing (after the new driver will be deployed on our production servers).

**Comment by bschwedler** [comment]
Hi @ThomasSoeiro

The error message was added to the Oracle driver in version `2.0.7`. This update _will not_ add support for multiple bound parameters.
```
Resolved Issues
The following issue has been resolved in Simba Oracle ODBC Connector 2.0.7.

 * [ORCL-837] When there is more than one bound parameter, the connector 
   incorrectly reports the error. 
```

This release was unfortunately delayed due to compatibility issues on RHEL 7.

We expect that the updated `2.0.7` Oracle Driver will be included in the March 2024 release of the professional drivers.

**Comment by ThomasSoeiro** [comment]
The issue should not be closed until it has been confirmed that it has been fixed.

**Comment by ronblum** [comment]
Verified that Oracle driver 2.0.7.1007 is downloaded by RStudio Desktop 2024.09.0+375.pro3 on Windows 11.

**Comment by ronblum** [comment]
@bschwedler Just to confirm, version 2.0.7.1007 of the Oracle pro driver contains the error message? Checking that the fourth level (1007) is correct.
