### ISSUE TITLE
The icon of RStudio project file changed (in daily builds): again

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12684]
The same as:

- #12246 

Just in current daily builds.

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.3.0.304
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.2.2 (2022-10-31 ucrt)

**Comment by mine-cetinkaya-rundel** [comment]
It has also changed in Mac OS as well:

```
RStudio Edition : Desktop [Open Source]
RStudio Version : RStudio 2023.03.0-hourly+681 "Cherry Blossom" Hourly (9853bc106800e1732dc4406535109205d7bdba1d, 2023-02-18) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0-hourly+681 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
OS Version      : Mac OS 13.1
R Version       : R version 4.2.2
```

**Comment by mikebessuille** [comment]
@GegznaV can you include a screenshot of the icon you are seeing?   Does it show up differently from 2022.12.0?

**Comment by GegznaV** [comment]
Current:
![image](https://user-images.githubusercontent.com/12725868/220388313-4b2ed27c-b2cd-42df-b599-0588e6d82454.png)

Expected:
![image](https://user-images.githubusercontent.com/12725868/220388615-11096292-30e3-4f3d-a167-7721e0d41cba.png)

**Comment by gtritchie** [comment]
I broke this here: https://github.com/rstudio/rstudio/commit/bad464d3e5d2ff95863545c83a50037346a5eb43

Specifically:

```bat
if /I "%%A" == "electron" set RSTUDIO_TARGET=Electron && set KNOWN_ARG=1
```
This makes RSTUDIO_TARGET="Electron " (note the trailing space!) which causes comparisons later in the batch file to "Electron" (no trailing space) to fail. This also caused the version reported by running with `--version` to be incorrect (99.9.9).

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0-daily+358
Windows 11

Correct version is given, and Icons look as expected.

**Comment by zhaoliang0302** [comment]
Same in Windows 11 x64 22H2. I tried several version of Rstudio, all the .R and .Rproj files will not automatically associated with Rstudio after installtion. I should open them and chose Rstudio to open them manually. Icons of all these files look same.

**Comment by zhaoliang0302** [comment]
```  
  RStudio Edition : Desktop 
  RStudio Version : 	2023.12.2+407/2023.06.2+561
  OS Version      : Windows 11 x64 version 22621.2134
  R Version       : 4.3.3
```
It might be related to the Windows version, but I can install other software and associate files normally.
