### ISSUE TITLE
RStudio Server crashing during profiling sparklyr code

### ISSUE THREAD

**Issue by krprasangdas** [rstudio/rstudio#12685]
### System details

    RStudio Edition : Server
    RStudio Version : RStudio 2022.07.2+576.pro12 "Spotted Wakerobin" Release (2a128b1827b6319af9d2153d07bb671df848dcce, 2022-09-19) for CentOS 7
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78
    OS Version      : Red Hat Enterprise Linux Server 7.9 (Maipo)
    R Version       : 4.0.2

### Steps to reproduce the problem
Involves proprietary code.

### Describe the problem in detail
I am executing sparklyr code that involves proprietary logic. While the sparklyr code is executing, RStudio session abruptly ends without any error message.
Running diagnostics while profiling the same code has some instances of get_events being cancelled.
Request ID: 1875375984

== REQUEST ======
{
  "method": "get_events",
  "params": [
    4512
  ],
  "clientId": "861df566-6eb9-42dc-8b31-b40e7cac84d7",
  "clientVersion": ""
}

== RESPONSE ======
Cancelled

### Describe the behavior you expected
An error as to why the RStudio session is crashing? How to capture the error that causes unrecoverable exceptions, if any?

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@krprasangdas Thank you for raising the issue!

@kevinushey or @jeffvroom do you have any suggestions for how to investigate this? Without a reprex (due to the proprietary code) I don't know how to proceed.

**Comment by ronblum** [comment]
@krprasangdas It looks like you're using Posit Workbench rather than the open source RStudio Server. Are you a current Posit customer? If so, can you please submit a Support ticket at https://support.posit.co/hc/en-us/requests/new? Also include a reference to this issue, for tracking purposes. Thanks!

**Comment by krprasangdas** [comment]
@ronblum Thanks for your response. I have submitted a support ticket referring this issue.
