### ISSUE TITLE
Cannot paste screenshot into qmd file, in visual editor

### ISSUE THREAD

**Issue by donboyd5** [rstudio/rstudio#12690]
### System details

    RStudio Edition : RStudio Desktop
    RStudio Version :  2023.03.0-daily+301, compared to 2022.12.1+363
    OS Version      : 
    R Version       : 

Edition Windows 11 Pro
Version 22H2
Installed on ‎5/‎13/‎2022
OS build 22623.1250
Experience Windows Feature Experience Pack 1000.22639.1000.0

platform x86_64-w64-mingw32
arch x86_64
os mingw32
crt ucrt
system x86_64, mingw32
status
major 4
minor 2.2
year 2022
month 10
day 31
svn rev 83211
language R
version.string R version 4.2.2 (2022-10-31 ucrt)
nickname Innocent and Trusting

### Steps to reproduce the problem

- work in RStudio Desktop 2023.03.0-daily+301
- in a .qmd file, in visual editor mode
- take a windows screenshot, directed to the clipboard, and
- copy it into the visual editor window

### Describe the behavior you expected

Instead of getting the expected image of the screenshot, I get a broken link. For some reason I can't paste an image of the broken link here, but that is the result in any event.

By contrast, if I do this in RStudio Desktop 2022.12.1+363 the image will appear as expected.

Possibly related to #12270 and #12466.

I have seen this occur before, where in daily builds of an RStudio Desktop version, image pasting into qmd files stops working, but later it is fixed. I think it happened with Elsbeth Geranium, but if not with that, with an earlier version for sure. Because it seems like you are getting close to release of Cherry Blossom, I thought I should mention it now.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@donboyd5 Thank you for raising this! If it's related to #12270, it might have just gotten resolved. Hopefully the next builds—keep an eye out on[ the dailies page](https://dailies.rstudio.com/) for an upcoming build.

**Comment by donboyd5** [comment]
Let me see if I can satisfy the repro requirement. It's a human process, not computer code, however, so I don't know if this will satisfy the requirement.

**What doesn't work**

- Open an RStudio session using 2023.03 Cherry Blossom Windows 10+ 2023.03-daily+317. 
- Create a new quarto project. I called mine test. On my computer, it opens in visual editor mode and the screen looks like this:

![image](https://user-images.githubusercontent.com/6538392/218594453-2c1eb4e4-ed94-48e0-9b39-c501a8c0a9a3.png)

- Place the cursor below the R chunk (or anywhere really)
- Take a screenshot of something using the Windows screenshot capability, letting it go into the clipboard.
- Here's the screenshot I took, of part of the console:

![image](https://user-images.githubusercontent.com/6538392/218595678-eeb9c166-4dee-410b-8721-9af0052f9c6a.png)

- Paste that screenshot into the test.qmd file in visual edit mode. Here's what I see after I do that:

![image](https://user-images.githubusercontent.com/6538392/218595837-63fa5c10-bafb-4152-a317-0fe5a8247854.png)

- In other words, it does not paste properly.
- When I repeat the steps using RStudio Elsbeth Geranium Windows 10+ 2022.12.1-363, pasting (approximately) the same screenshot, I get the following:

![image](https://user-images.githubusercontent.com/6538392/218596812-e3674e30-4655-4784-ab74-60c472b3bcdf.png)

- Which is, of course, what I expected.
- So it works in Elsbeth Geranium but not in Cherry Blossom. I hope this provides what you need.

**Comment by ronblum** [comment]
@donboyd5 Thanks! A few mea culpas:

- `repro needed` is a little confusing, because it really means "more information needed." In this case I meant for finding out if the new dailies have the fix.
- I missed that you had provided more information. I don't always catch when more information has been provided...
- A change was made in #12270, and the same behavior was changed here. It would've been helpful 

The change was that now all of the code—`data:image/etc.`—is no longer pasted. That's the stopgap, but doesn't fully address the issue, which is to paste from the clipboard. The workaround is to save the image, because image files can be pasted into Quarto and R Markdown documents.

I'll mark it for further review.

**Comment by donboyd5** [comment]
Thanks!

**Comment by matthewgson** [comment]
I've been experiencing the same issue since the last stable update (2023-03). I also checked the latest daily build today (2022-04-15), but it still doesn't work.  

Going back to the previous stable build (2022-12) solved the issue. I'm hoping this issue to be fixed soon.

**Comment by Dr-Junior** [comment]
I've had a similar issue (Windows 10), except that in stead of getting a broken link when pasting, nothing happened at all. Reverting to version 2022-12 of solved the issue.

**Comment by donboyd5** [comment]
Yes, me too. I am still using 2022-12 but wish I could upgrade to the
latest.

**Comment by jzadra** [comment]
This isn't working for me anymore either.

RStudio 2023.03.1+44
OSX 13.3.1

**Comment by donboyd5** [comment]
@ronblum I just wanted to note that this issue has become more significant for me and perhaps for other users now that R 4.3 is out. 

So that I do not lose screenshot-pasting capability, I have been avoiding RStudio upgrades, and instead using RStudio 2022.12.1 Build 366.

However, I just installed R 4.3.1 and when I load RStudio 2022.12.1 I get the message, 

`Warning message: R graphics engine version 16 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed.`

Because I don't want to lose the plots tab, I'll either have to stick with R 4.2 and lose R 4.3 compatibility, or use R 4.3 and upgrade RStudio, losing screenshot-capability. For me, the latter will be a significant productivity loss because I often use quarto to put together quick web pages on various analytic issues, for discussion with groups of people I work with, and that often benefits from pasting in screenshots from all sorts of sources. I realize it is possible to save screenshots to a file and import them into a qmd file, but that's a lot less efficient and a lot more work.

I suspect a fair number of other people have a similar workflow issue.

Thus, I am left with only bad choices: fall behind on R, fall behind on RStudio, or be current on both and lose screenshot-pasting capability.

If there is any way to make restoring screenshot-pasting capability a higher priority in RStudio plans, that would be a great help.

Many thanks for considering this.

**Comment by donboyd5** [comment]
@ronblum 

I see now with experimentation that I have a better workaround - I hadn't read your earlier note carefully enough. I don't have to save the image file and import it. I just have to save the image file and paste it. Since my screenshot software (Screenhunter) can be set to automatically save to a file and I can pretty easily retrieve the file, it is not as big a hassle as I expected. Still it is less convenient than what is possible in RStudio 2022.12.1 (pasting directly from the clipboard) and it would be great to get that capability back.

**Comment by LollosaurusRex** [comment]
I have this issue in .Rmd (R Markdown) files as of my update to Rstudio version 2023.06.2-561 Windows 10

**Comment by GegznaV** [comment]
I use RStudio 2023.09.0-daily+414 and the issue is still present.

**Comment by issactoast** [comment]
I really disappointed that RStudio ignored this issue. Direct-paste image from the clipboard function is a sweet functionality for many users and saves so much time. It really was a forte that RStudio IDE had.

**Comment by kevinushey** [comment]
I've started digging in a bit here. For context, image pasting is handled by Quarto here:

https://github.com/quarto-dev/quarto/blob/88775d1172a5308fbc2f30391a246bb42715c39c/packages/editor/src/nodes/image/image-events.ts#L41-L95

However, it seems like the clipboard paste event RStudio is sending to Quarto is somewhat bogus?

<img width="849" alt="Screenshot 2023-09-19 at 4 06 05 PM" src="https://github.com/rstudio/rstudio/assets/1976582/1bf7c015-bd03-435e-9a9f-65615c93bdc5">

That is, it has some dummy name `image.png`, and no actual path recorded. This is for a path copied to the clipboard just via <kbd>Cmd + C</kbd> on macOS.

My guess (haven't verified yet) is that Electron isn't handling the paste for us cleanly, and we're going to have to implement our own paste handling to get this to work consistently.

**Comment by kevinushey** [comment]
Ah, okay, I know what's going on. Panmirror expects the application hosting it to provide a context object with some callbacks for certain operations, one of those being `resolveBase64Images`:

https://github.com/quarto-dev/quarto/blob/88775d1172a5308fbc2f30391a246bb42715c39c/packages/editor/src/nodes/image/image-events.ts#L165

We implement some of these in RStudio, e.g.

https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIContext.java

but we're missing the one for transforming clipboard image blobs into base64 data. Presumedly, if we add that in, things should "just work".

**Comment by donboyd5** [comment]
That would be great! Thank you for working on this.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+196 on MacOS 14, Red Hat 9.2, and Windows 10.

**Comment by donboyd5** [comment]
Unbelievable! Worked perfectly on my initial test.

Thanks so much.

Don

**Comment by matthewgson** [comment]
Updated my old RStudio as soon as I saw this. It works great...

**Comment by ronblum** [comment]
@donboyd5 @matthewgson Great to hear! Let us know if you run into any issues. Also, please keep in mind that these builds are meant for testing purposes right now, not yet for production.

**Comment by matthewgson** [comment]
Edit: I realized that it shows up on the visual editor, but the image breaks when it is rendered.

**Comment by ronblum** [comment]
I see: An `images` directory is created into which the image is inserted. The path used when pasting from the clipboard is relative to the home directory:
```~/Projects/Testing/renver/images/clipboard-2209196497.png```

Knitting and rendering aren't finding the file relative to the home directory. But it work correctly when changing it to use the relative path
```images/clipboard-2209196497.png```
or the full path
```/Users/ronblum/Projects/Testing/renver/images/clipboard-2209196497.png```

So I think that we need to use the relative path, similar to what's done when dragging an image into the editor or using <kbd>Insert -> Figure/Image</kbd>. So reopening. I'll look for or file a separate issue regarding using a path relative to the home directory.



(And tsk tsk to me for earlier only checking that the pasting works, without also checking that render works.)

**Comment by ronblum** [comment]
The directory is now using the full path. Two  things:
1. It looks like this only works for R Mardkown, but not Quarto. I'll file this as a separate bug for Quarto.
2. Perhaps we should use the relative path, to the local `images` directory. This way, if using a project, the entire project can be moved without impact. Otherwise, the full path will no longer be valid. (Moving back to "in progress" to get your thoughts, @kevinushey )

**Comment by kevinushey** [comment]
You should only see a full path if you try to paste an image into an unsaved document, but that seemingly shouldn't be required. I'll take a look!

**Comment by matthewgson** [comment]
Confirmed that RStudio Daily 2023.12.0 + 223 on Mac works. 👍

**Comment by ronblum** [comment]
@matthewgson Awesome! And also verified in RStudio Server 2023.12.0-daily+223 on Ubuntu 22.04 via Chrome on MacOS 14.1.
