### ISSUE TITLE
Unexpected popup window with error message "No such file or directory" when opening multiple instances of RStudio

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#12694]
### System details

```
RStudio Edition : Desktop
RStudio Version : 2022.12.0 Build 353
OS Version      : ArchLinux (Kernel: 6.1.5)
R Version       : 4.2.2.
```

### Steps to reproduce the problem

1. Launch RStudio.
2. Launch another instance of RStudio.
3. Now a popup window with an error message has appeared in the first RStudio instance.

(Also, closing later instances also leads to the same popup window appearing).

### Describe the problem in detail

After the second launch of RStudio, or **any other subsequent launches**, each launch will trigger a popup window with an error message saying **"No such file or directory"** in the very first instance...

![error02](https://user-images.githubusercontent.com/19862384/218149699-e79556e4-30f9-4ec1-b477-6f271c948659.png)

### Describe the behavior you expected

I expected every launch of RStudio to be completed independent and not generate this popup window in the first instance of RStudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ramiromagno** [comment]
I just reverted to RStudio version 2022.07.2 Build 576, and this problem is gone.

**Comment by ramiromagno** [comment]
Hi @ronblum:

Why the "info needed" tag? What else info do you need?

**Comment by ronblum** [comment]
@ramiromagno I have a feeling that I wrote down a question but forgot to click "Comment" to submit it. 🙄 But here's a question: How are you launching multiple instances—are you running them from the terminal, launching the second instance with <kbd>Session -> New Session</kbd>, or another way?

**Comment by ramiromagno** [comment]
I just run rstudio again from the command-line.
