### ISSUE TITLE
Update bundled Quarto to the latest version

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12697]
RStudio is currently bundling version 1.2.280 of Quarto,

1. Dev: Update so that RStudio is pulling in the latest ~development~ released version of Quarto.
2. QA: In addition to testing the Quarto-integration functionality, render and serve a bunch of existing Quarto pages and sites as a regression test.

**Comment by timtmok** [comment]
We'll take 1.2.335

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2023.03.0-daily+323 on MacOS 13.2
- RStudio Server 2023.03.0-daily+323 on Ubuntu 20.04.5 via Chrome on MacOS 13.2

```
> quarto::quarto_version()
[1] ‘1.2.335’
```

Testing by
1. Creating and rendering/building several projects:
- Quarto Project
- Quarto Website
- Quarto Blog
- Quarto Book
- Guide located at https://github.com/quarto-dev/quarto-web
2. Publishing
- Quarto Book (Ubuntu 20.04.5)
- Quarto Website (MacOS 13.2)
