### ISSUE TITLE
Re-publish dialog generates bad url

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#12708]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.03.0-daily+313
    OS Version  : Mac 
    R Version  : 4.2.1 

### Steps to reproduce the problem

When I republish a doc:

<img width="614" alt="Screenshot 2023-02-13 at 16 38 12" src="https://user-images.githubusercontent.com/4196/218590452-29a96e8c-c6ff-4d57-9b08-2554334fba7e.png">

And click on the link in the update panel, it takes me to

https://connect.rstudioservices.com/content/3b119155-220f-42dd-a21c-6701aaaf8e5a/

The correct link is 

https://connect.rstudioservices.com/connect/#/apps/3b119155-220f-42dd-a21c-6701aaaf8e5a

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hadley** [comment]
That url is correct but it's gives a 404 because the content failed to publish.

**Comment by hadley** [comment]
But it still makes sense for the IDE to display the "dashboard" url, because that gives you the information needed to debug it. And generally, I think you want to go to that page, because that's what allows you to set options _and_ see the content.

**Comment by kevinushey** [comment]
These URLs are being generated by `rsconnect`. For example:

```
> str(rsconnect::applications()[1, ])
'data.frame':	1 obs. of  11 variables:
 $ id          : int 11270
 $ name        : chr "failing-doc"
 $ title       : chr "failing-doc"
 $ url         : chr "https://connect.posit.it/content/c0b7db99-d29c-428f-9219-6dec0be79205/"
 $ status      : int 2
 $ created_time: chr "2024-01-26T20:12:05.419221Z"
 $ updated_time: chr "2024-01-26T20:12:06.849207Z"
 $ guid        : chr "c0b7db99-d29c-428f-9219-6dec0be79205"
 $ size        : logi NA
 $ instances   : logi NA
 $ config_url  : chr "https://connect.posit.it/connect/#/apps/11270"
```

And this is coming from the Connect server itself, e.g.

```
Browse[2]> apps <- client$listApplications(accountDetails$accountId)
Browse[2]> str(apps[[1]])
List of 52
 < ... trimmed ... >
 $ url                              : chr "https://connect.posit.it/content/c0b7db99-d29c-428f-9219-6dec0be79205/"
< ... trimmed ... >
```

So, I believe the requisite change would need to happen on the Connect side. @aronatkins, does this sound correct?

The alternative would be for us to use the `config_url` setting rather than the plain `url` setting, but I don't know if that's actually correct.

**Comment by kevinushey** [comment]
Or perhaps the request here is to just use `config_url` instead of `url` for documents here by default?

**Comment by kevinushey** [comment]
Hmm, slightly unfortunate that `client$getApplication()` doesn't seem to return a `config_url`...
