### ISSUE TITLE
IDE does not record failed deployment

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#12707]
### System details

    RStudio Edition :  Version 2023.03.0-daily+313
    RStudio Version : desktop
    OS Version      :  mac
    R Version       :  4.2.1

### Steps to reproduce the problem

(You must have already set up some publishing location for this to work)

1. Create a new empty project
2. Add the following text to a file called `"failing-doc-with-unique-name.Rmd"`

    ```{r}
    f <- function() stop("An error!")
    f()
    ```

3. Save the document and press the publish button.
4. Click Posit Connect. Click publish with source code. Click publish.
5. The deployment will fail, but the document has been successfully published to connect (even though it failed to compile).
6. Press the publish button again — it does not remember where you just published the doc, and you have to re-enter everything.
7. Close and reopen the project.
8. Press "Publish" — it now remembers where you previously deployed it.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can begin our search around here: https://github.com/rstudio/rstudio/blob/4e3916f97aa5edccd1b93ed5236598a3c99dd4d5/src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java#L234-L461

**Comment by aronatkins** [comment]
The IDE can also show stale deployment records after they have been modified or removed using `rsconnect::syncAppMetadata()` and `rsconnect::forgetDeployment()`.

**Comment by kevinushey** [comment]
Thanks @aronatkins -- I filed https://github.com/rstudio/rstudio/issues/13855 to track that.

**Comment by jonvanausdeln** [comment]
Verified on [2023.12.0-daily+234](https://dailies.rstudio.com/version/2023.12.0-daily+234)

Publishing errors and subsequent publishing works as expected.
