### ISSUE TITLE
Reformat code makes the wrong choice on rlang interpolation operator {{

### ISSUE THREAD

**Issue by daniel-simeone** [rstudio/rstudio#12703]
### System details

    RStudio Edition : Desktop
    RStudio Version :   2022.12.0 Build 353
    OS Version      : Windows 11
    R Version       :  4.2.2

### Steps to reproduce the problem
Define a function using the {{ operator, such as:

```
a_function <- function(df,   colname) {
  df |>  select({{colname}})  |> pull()
}

a_function(mtcars, mpg)

```

Select code. Choose 'reformat code' from Code menu in Rstudio.

### Describe the problem in detail

The {{ gets pulled apart strangely:
![image](https://user-images.githubusercontent.com/109553256/218492420-85b184aa-6cad-43ec-8b76-3dcda406326c.png)

### Describe the behavior you expected
Keeping it with the variable column name:
![image](https://user-images.githubusercontent.com/109553256/218492563-a6d234e9-9f8f-467c-a908-e655c045d5c8.png)

I'm not sure of the relationship between this menu item and the package styler, but this appears to have been solved in styler 1.2.0 :
https://www.tidyverse.org/blog/2019/11/styler-1-2-0/

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@daniel-simeone Thank you for raising this! I'll mark it for review as we continue development of RStudio.

**Comment by daniel-simeone** [comment]
In Rstudio 2023.06.0 Build 421, the issue persists.

**Comment by jthomasmock** [comment]
Thanks for posting @daniel-simeone - can you try out the `styler` package?

https://styler.r-lib.org/ -- this adheres to the `tidyverse` style guide.

**Comment by daniel-simeone** [comment]
Styler fixed this in 1.2.0

https://www.tidyverse.org/blog/2019/11/styler-1-2-0/




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jthomasmock** [comment]
Thanks for the link! Does using styler - style active selection resolve your issue in lieu of reformat?

**Comment by daniel-simeone** [comment]
From this:
![image](https://github.com/rstudio/rstudio/assets/109553256/6b5dfc71-be57-4621-abb0-bc095e9ea533)
to:
![image](https://github.com/rstudio/rstudio/assets/109553256/09a65713-ccbf-4561-8d68-74b46ace0072)

Yep. styler looks good.

**Comment by kevinushey** [comment]
Looks like this was fixed via https://github.com/rstudio/rstudio/commit/41777460b5cc50c9d387bfff6dd18123fadaae48?

**Comment by danielsimeone** [comment]
It works!! (In 2024.04.1 Build 748, Windows 64-bit).

**Comment by kevinushey** [comment]
Awesome! Thanks for testing and reporting back.
