### ISSUE TITLE
Project-level configuration for Rmarkdown working directory

### ISSUE THREAD

**Issue by 18kimn** [rstudio/rstudio#12701]
**Problem statement:**
I work in RMarkdown files within R projects for nearly all of my projects, and it is unergonomic to use filenames relative to the project root in my scripts but to have to use filenames relative to the document in RMarkdown files.

To work around this, I always have to add a line like this in my setup chunk:

```r
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

But I have to do this for every RMarkdown file I open, and feels more like a hack than a true supported option.

The other strategy I currently use is to set the global option for the RMarkdown chunk directory to be the project root. But this is not very stable; I find myself 1) having to repeatedly change this option whenever I work in a different project with different filename conventions, and 2) risking the path breaking when a colleague works with the same project, as their global options may be different

**Solution**

In addition to the global option for the Rmarkdown chunk directory, I'd like there to also be a project-level set of options in RStudio for the Rmarkdown chunk directory that would override the global options (currently they are "Document," "Current," and "Project"). This would alleviate the need to manually set the chunk root directory. And because the project options are stored in the `<project name>.Rproj` file, this configuration would be tracked by version control and could be distributed to colleagues, and I wouldn't have to worry about switching options every time I open a different project. 

I'm happy to create a PR if the team thinks this is an acceptable feature. and apologies if this has already been posted; I could not find a corresponding issue in the Github repo

**Comment by ronblum** [comment]
@18kimn Thank you for the suggestion.

1. We'll review it as we continue to develop RStudio.
2. But we're also open to PRs! We would need to review and test it. Here's information about writing features for RStudio: https://github.com/rstudio/rstudio/wiki/A-Beginner's-Guide-to-Writing-RStudio-IDE-Features
