### ISSUE TITLE
Select all in the console

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#12719]
Hello,

I'm using the latest RStudio Desktop with Linux Mint.

When the cursor is in the console and I do "Select all" in the "Edit" menu, nothing happens. 

However when I "select all" with the menu appearing on a right-click, then I can copy the selection with "Copy" in the "Edit" menu.

I would like to be able to do "Select all" in the "Edit" menu to select the contents of the console. ***Ctrl+A*** does nothing as well.

**Comment by ronblum** [comment]
@stla Thank you for the suggestion! We'll consider this request. It looks like with the recent change in framework (from Qt to Electron), we introduced this option among others, but it's only applying to the Editor Pane. Ideally, we could do this for the Console Pane, as well. If that's not possible, we should at least gray out anything that can't be done wherever the cursor is currently located.

**Comment by stla** [comment]
Oddly, you can "select all" with the "Edit" menu and even do ***Ctrl+A*** to select the console contents when the focus is in the "Build" pane. But this also selects the contents of the "Build" pane.
