### ISSUE TITLE
Spell check in Visual editor throws Exception.

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#12712]
### System details

    RStudio Edition : Desktop and Sever
    RStudio Version : 2023.03.0-daily+316.
    OS Version      : Windows, Ubuntu22
    R Version       : 4.2.2

### Steps to reproduce the problem
1. Create an RMarkdown or Quarto document
2. Add some misspelled text to default (e.g. "misssssppellllled")
3. Make sure it is in Visual Editor mode
4. Edit->Check Spelling

### Describe the problem in detail
![image](https://user-images.githubusercontent.com/6433789/218854780-d253c720-7156-490b-9269-e760b95ccdcb.png)

### Describe the behavior you expected
In source mode, the spell check works correctly.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
I briefly chatted with JJ about this issue, and he's going to take over this bug. The bad call to `getBoundingClientRect` is coming from panmirror, initially triggered from this code on the GWT side: https://github.com/rstudio/rstudio/blob/cc82b8560fcdced44c30c02cd5cf81ebcc7acd38/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeSpelling.java#L168

**Comment by jjallaire** [comment]
This should be resolved with this commit to quarto-dev/quarto: https://github.com/quarto-dev/quarto/commit/3f098d26b5024076d3baae58203cc24c67a66e32

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+347 on MacOS 13.2 and RStudio Server 2023.03.0-daily+347 on Ubuntu 20.04.2 via Chrome on MacOS 13.2.
