### ISSUE TITLE
Latest Rstudio(2023.03) request R installation while it is already installed

### ISSUE THREAD

**Issue by yejin1016** [rstudio/rstudio#12711]
### System details

    RStudio Edition : Desktop
    RStudio Version : rstudio-2023.03.0-daily-318-amd64
    OS Version      : Ubuntu 22.04.1 LTS
    R Version       : 4.2.2

### Steps to reproduce the problem

> install rstudio:
> sudo dpkg -i rstudio-2023.03.0-daily-318-amd64.deb

attempt boot:
> rstudio

attempt boot sudo:
> sudo rstudio --no-sandbox

### Describe the problem in detail
![image](https://user-images.githubusercontent.com/79450279/218783595-d13b3fe8-e8e3-471a-9319-129818d7e429.png)
R studio failed to open with an error message saying R is not installed.
I've tried to re-install both R and R studio multiple times, no success.

When tried with --no-sandbox command:
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [81343:0214/165843.702138:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is desktop, ANGLE is 

was the error message, and the same pop-up window showed.

I've tried to use a previous R studio version (2022.07) too, but it didnt work either with an error message:
> R did not return any output when queried for directory location information

Does anyone have a similar issue in Ubuntu?

### Describe the behavior you expected

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by yejin1016** [comment]
Never mind. The issue is solved. The problem was related to Citrix Workspace app, not Ubuntu or Rstudio.

**Comment by ronblum** [comment]
@yejin1016 Thank you for letting us know! I'm glad that the issue is resolved.
