### ISSUE TITLE
External source are missing from citation options

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12710]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0-daily+318
    OS Version      : MacOS 13.2
    R Version       : 4.2.2

### Steps to reproduce the problem

1. In RStudio Desktop, open a new R Markdown or Quarto document.
2. Switch to visual mode.
3. <kbd>Insert -> Citation</kbd>

### Describe the problem in detail

Only "My Sources" shows up. DOI, CrossRef, etc. are missing.
<img width="491" alt="Screenshot 2023-02-13 at 4 39 41 PM" src="https://user-images.githubusercontent.com/31009952/218761800-fd1944e4-d26f-4a3e-b21a-150072b1c355.png">

### Describe the behavior you expected

All sources should be available. Note that this works as expected in RStudio Server.
<img width="439" alt="Screenshot 2023-02-13 at 4 39 11 PM" src="https://user-images.githubusercontent.com/31009952/218761778-2fee03d0-f17c-40de-9416-737265bfabd3.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
Yes I will take a look at it today! I was able to reproduce it locally so hopefully it won't be too bad to track down.

**Comment by dragonstyle** [comment]
@mikebessuille this is fixed and ready to test- I marked the milestone but wasn't able to change the status to `test` (perhaps a permissions thing).

**Comment by mikebessuille** [comment]
@dragonstyle you're awesome Charles, thank you!

**Comment by ronblum** [comment]
QA note: The original environment had Zotero installed on the MacOS desktop but not the Ubuntu server, which is the cause. Verify using RStudio Desktop with and without Zotero.

**Comment by ronblum** [comment]
Verified in RStudio Desktop on MacOS 13.2 and RStudio Server 2023.03.0-daily+347 on Ubuntu 20.04.2 via Chrome on MacOS 13.2.
