### ISSUE TITLE
Double clicking on the document outline does not go to that line in the visual editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#12728]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.03.0-daily+328 "Cherry Blossom" Daily (b094e02b3050315faee82c901cad8836e74d504a, 2023-02-19) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0-daily+328 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
    OS Version      : mac OS 13.1
    R Version       : 4.2.2

### Steps to reproduce the problem

Open a document in the visual editor with multiple section headings. Go to the document outline. Click on a section heading that is lower down in the document.

For example, save the following as `test.qmd`.

```markdown
---
title: Document title
---

## Section 1

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu interdum mi. Donec a neque venenatis, placerat augue vel, lobortis turpis. Proin finibus pharetra ante dignissim faucibus. Vestibulum efficitur posuere aliquam. Donec ut dui viverra, pharetra mauris et, vulputate est. Pellentesque mi ante, efficitur vel bibendum a, pulvinar eu nulla. Phasellus eleifend justo quis sollicitudin fermentum. Donec lacus risus, eleifend eu massa ac, sodales laoreet ante.

## Section 2

Curabitur consectetur quam lorem, sed lacinia nunc vehicula quis. Aenean ut luctus mauris. Nunc non finibus lacus. Quisque eu sem lobortis, posuere dolor sed, pretium sapien. Morbi imperdiet sollicitudin scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In scelerisque sem sit amet lectus euismod, in viverra arcu elementum. Vivamus sagittis tempor mi, in scelerisque arcu porttitor sit amet. Nullam scelerisque dolor nec turpis feugiat laoreet eget quis tortor. Ut molestie scelerisque lobortis. Cras euismod metus eu enim sagittis condimentum. Donec hendrerit odio at suscipit vehicula.

## Section 3

Pellentesque fringilla velit vel metus venenatis, pharetra consequat nunc convallis. Aenean et dui vel libero aliquam dignissim sit amet at arcu. Sed at mi mollis, rhoncus elit quis, auctor massa. Nam at eros porta, molestie justo in, mollis ante. Nullam facilisis odio vestibulum dui ornare lacinia. Praesent sit amet tortor turpis. Praesent pharetra quis ligula eu dignissim. Vestibulum nec convallis metus. Mauris et arcu purus. Integer luctus ex lorem, sed ultrices odio viverra et. Maecenas ut auctor lorem. Donec faucibus nulla et massa cursus iaculis. Praesent sit amet odio eget lectus euismod tristique. Praesent tincidunt tempor leo at vehicula. Nulla tempor accumsan risus at tincidunt. Proin fringilla felis id sapien gravida malesuada.
```

### Describe the problem in detail

When using the visual editor, double clicking on the document outline to jump to a new section does not move the focus in the editor to that line. It appears as though the cursor might be moving (see the `...`s appearing in `Section 2` in the video below.

https://user-images.githubusercontent.com/5965649/220240736-e5b8b50b-85bf-4cda-b17b-34b36b05c7ce.mov

### Describe the behavior you expected

I expected the behaviour to match between the visual and source editors: the focus should move to that line in the editor.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Thanks @mine-cetinkaya-rundel ! I can also reproduce this in
- RStudio Desktop 2023.03.0-daily+344 on MacOS 13.2
- RStudio Server 2023.03.0-daily+344 on Ubuntu 20.04 via Chrome on MacOS 13.2

It works in RStudio Desktop 2022.12.0+353 on MacCOS 13.2, so this is a regression.

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0+374 Desktop
Windows 11, MacOS 12.6

Focus correctly shifts to selected sections as expected.
