### ISSUE TITLE
Exclude own actions from Slack notifications

### ISSUE THREAD

**Issue by sewi-cpan** [rstudio/rstudio#12727]
The ["scheduled reminders" include "real-time alert"](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/managing-your-scheduled-reminders)
![image](https://user-images.githubusercontent.com/2063104/220056108-23e4d335-7f4d-4bf9-aab2-3f85f3060fd8.png)
They speed up teamwork a lot. The one thing missing is an option to **exclude your own actions**.

No real-time messages should be created for the recipients own actions.

**Comment by sewi-cpan** [comment]
> @sewi-cpan did you mean to file this in the RStudio repository or file an issue with GitHub itself?

Sorry, don't know how I ended up here. It's a GitHub problem, not related to RStudio.

**Comment by ronblum** [comment]
@sewi-cpan No problem! FWIW, I believe that GitHub feature requests are made at https://github.com/orgs/community/discussions
