### ISSUE TITLE
Option to show Objects in order created in Environment Pane

### ISSUE THREAD

**Issue by bms63** [rstudio/rstudio#12726]
In my scripts I create a lot of intermediate dataset objects.  As the script is executing they are nicely laid out in the Environment objects pane in alphabetical order.  Is it possible to make this order appear in time the object was created?  Very handy to pick out the last couple of objects created at the bottom of the list rather than naming `zz_` or some other naming convention to have it appear at the bottom of the pane.

This is a nice feature in SAS Studio, although they don't' have the ability to alphabetize the objects!!

**Comment by ronblum** [comment]
@bms63 Thank you for the suggestion! We'll review it as we continue to develop RStudio. And thanks for referencing the behavior of other software (SAS) as a comparison point.
