### ISSUE TITLE
Enable R syntax highlighting in R History pane

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12731]
Enable R syntax highlighting in the R History pane. Currently, no highlighting is used there:

![image](https://user-images.githubusercontent.com/12725868/220391237-6af5dd2b-e20a-4c22-9a06-8b50257a15fa.png)

**Comment by ronblum** [comment]
@GegznaV Thank you for another good suggestion!

**Comment by GegznaV** [comment]
I am still waiting for this feature to be implemented.

**Comment by GegznaV** [comment]
Not implemented yet.

**Comment by GegznaV** [comment]
@ronblum, is it solved?
