### ISSUE TITLE
Saving plot as PDF should provide sizes in metric as well as imperial

### ISSUE THREAD

**Issue by pstraforelli** [rstudio/rstudio#12736]
When exporting a plot as PDF, the device size offered should be available in metric (cm) as well as imperial (which is the only one currently available).

![image](https://user-images.githubusercontent.com/55718352/220423781-37a7a1c0-ac4b-4e1f-911f-900127059967.png)

**Comment by ronblum** [comment]
@pstraforelli Thank you for raising this! We'll review it as we continue development of RStudio.

**Comment by olleh** [comment]
This really is a hassle in fully metric countries. An option to choose unit of measurement would help o lot.
