### ISSUE TITLE
Release notes migration

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#12742]
### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

Migrating release notes from our "archived" pages within the repo and also older versions that are within the rstudio.com GH.

Original issue (closed and transferred: https://github.com/rstudio/rstudio-pro/issues/4282) 
Original PR (closed and transferred: https://github.com/rstudio/rstudio-pro/pull/4302) 

**Related to and closes: #11504**

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

- Create "new" quarto project for "news"
- Migrate all content into a single /docs/news/index.qmd file
- Collaborate with team to decide how we should organize all content
- Organize content after meeting with team
- Have "everyone" review the content to make sure it has been categorized properly
- Make fixes and test
- Then, follow normal review process

**Outstanding!**
- Need to add new release notes link to each guide OR set up a redirect
  - [x]     - Server Admin
  - [ ]     - Desktop - NO (they have a support article currently)
  - [x]     - WB User
  - [x]     - IDE User

PR in docs.posit.co repo to update old release notes links to new URL: https://github.com/rstudio/docs.rstudio.com/pull/1121

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

- Here is the version list from rstudio.com: https://docs.google.com/document/d/1KncCwiUqUfQmR130bm0Q91JLB7BnXrHm39CEQeVnZbE/edit?usp=sharing

### Documentation
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. 

- Adding a new `/news/docs` directory for release notes.

**Comment by melissa-barca** [comment]
All changes for the release notes and publishing job have been merged. There isn't anything to test until we release Cherry Blossom and publish these release notes. I've added validating this issue to the release checklist as an item assigned to @skyeturriff  and @ronblum. I've also updated the process for posting release notes on our pro wiki: https://github.com/rstudio/rstudio-pro/wiki/Stable-Releases#update-the-release-notes
