### ISSUE TITLE
Support R graphics engine 16

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#12751]
https://github.com/rstudio/rstudio/issues/12528#issuecomment-1444018883

We need to support the new R graphics engine or else plots won't work when R 4.3.0 is released in April.

**Comment by kevinushey** [comment]
I wrote up some instructions around preparing for a new graphics engine update here: https://github.com/rstudio/rstudio-pro/wiki/RStudio-Graphics-Device#preparing-for-an-r-update

**Comment by kevinushey** [comment]
See also: https://github.com/wch/r-source/commit/543acd8a43edfb17ab2941619ceb210b2c4c6154

If I understand correctly, that means the main function we need to support is here:

https://github.com/wch/r-source/commit/543acd8a43edfb17ab2941619ceb210b2c4c6154#diff-f340cbf03432dca4ce255b4eed943c02db094d2533ed8488561669513521075aR791-R795

And see from our last update: https://github.com/rstudio/rstudio/commit/97dfec9ce897ab5f4d238991d102e6f33d13c59a

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0+374

Plots pane works as expected with R dev version 4.3

**Comment by datakid** [comment]
Hi team, please always list the R Graphics Version bumps in the NEWS file. Thanks! Seen in ticket 96182
