### ISSUE TITLE
UI strings needing French translations in Cherry Blossom

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12752]
Ran the [locdiff tool](https://github.com/rstudio/rstudio/tree/main/src/gwt/tools/locdiff#readme), comparing Elsbeth Geranium initial release (7d165dcf) to current `main` (3ec419f). See [i18n wiki page](https://github.com/rstudio/rstudio/wiki/Internationalization-(i18n)) for more details.

| FILE ID | STRING ID | STATUS | CURRENT EN | CURRENT FR |
| ------- | --------- | ------ | ---------- | ---------- |
| studio/client/workbench/prefs/model/UserPrefsAccessorConstants | rainbowFencedDivsTitle | added |  Use rainbow fenced divs | 
| studio/client/workbench/prefs/model/UserPrefsAccessorConstants | rainbowFencedDivsDescription | added |  Whether to highlight fenced divs in a variety of colors. |

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0-daily+362

Translations show up. I'll assume they are correct.
