### ISSUE TITLE
Visual Editor for markdown removes link references at the bottom of the file

### ISSUE THREAD

**Issue by Snoopy1964** [rstudio/rstudio#12750]
I am writing a document, where I need the same link (including a lot of parameters) on several places in the document.
So, I used referenced links at the bottom of the document as described in the Markdown Quick Reference in RStudio. This works if I stay in the source editor, but when switching to the visual editor, the editor replaces the reference with the full link in the source file. 

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      :  Windows 10
    R Version       :  4.2.2

### Steps to reproduce the problem

1. open the attached example Rmd file in RStudio with source editor
2.  check reference link at the bottom (`[RMarkdown]: <http://rmarkdown.rstudio.com> "R Markdown page"`).
3. switch to visual editor
4. switch to source editor.

Example file
```R
---
title: "TestIt"
author: "R. Ehret"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: yes
---

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see [RMarkdown].

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this: 
check [RMarkdown]

## Including Plots

You can also embed plots, for example:

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
[RMarkdown] -> This is the 2nd usage of the link defined at the end of this file 

[RMarkdown]: <http://rmarkdown.rstudio.com> "R Markdown page"
```
### Describe the problem in detail
In the following example I just took the standard text when creating a new Rmd File, removed all code chunks, and replaced the link to RMarkdown with the referenced version:

### Describe the behavior you expected

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jorgedelpozolerida** [comment]
Any news on this issue? It happens to me as well. Also, when i try to embed in-line R code for the link, let's say for instance: [Doc_name] (`r mylink`) the same things happens. THanks
