### ISSUE TITLE
dialogViewer breaks when launching shiny gadgets consecutively

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#12760]
(Reported in https://github.com/rstudio/shiny/issues/3784 and was referred to file in this repo as an IDE bug)

Suppose I have a Shiny gadget that returns a value. Based on that value, I may want to run another Shiny gadget. Here is some example code:

```r
library(shiny)

app1 <- shinyApp(
  fluidPage(
    "app1",
    checkboxInput("launch", "launch app2"),
    actionButton("done", "done")
  ),
  function(input, output, session) {
    observeEvent(input$done, {
      stopApp(input$launch)
    })
  }
)

app2 <- shinyApp(
  fluidPage(
    "app2",
    checkboxInput("launch", "launch app1"),
    actionButton("done", "done")
  ),
  function(input, output, session) {
    observeEvent(input$done, {
      stopApp(input$launch)
    })
  }
)

run_app1 <- function() {
  ret <- runGadget(app1, viewer = dialogViewer("app1"))
  if (ret) run_app2()
}

run_app2 <- function() {
  ret <- runGadget(app2, viewer = dialogViewer("app2"))
  if (ret) run_app1()
}

run_app1()
```

This runs app1. If you check the box, then app2 should run after closing. However, the second app that's launched is a grey screen, there is no red stop button in RStudio to stop the app, and the console shows `>` as if the process isn't busy.

If you swap the `dialogViewer()` for `paneViewer()` or `browserViewer()`, then it works as expected.

**Comment by kevinushey** [comment]
From what I can see, it looks like we're sending an interrupt to R when the initial gadget is stopped, and that interrupt is being handled "too late", when the second application is started. To show this is true:

`````
library(shiny)

app1 <- shinyApp(
  fluidPage(
    "app1",
    checkboxInput("launch", "launch app2"),
    actionButton("done", "done")
  ),
  function(input, output, session) {
    observeEvent(input$done, {
      stopApp(input$launch)
    })
  }
)

app2 <- shinyApp(
  fluidPage(
    "app2",
    checkboxInput("launch", "launch app1"),
    actionButton("done", "done")
  ),
  function(input, output, session) {
    observeEvent(input$done, {
      stopApp(input$launch)
    })
  }
)

run_app1 <- function() {
  ret <- runGadget(app1, viewer = dialogViewer("app1"))
  if (ret) {
    tryCatch(Sys.sleep(0.1), interrupt = identity)
    run_app2()
  }
}

run_app2 <- function() {
  ret <- runGadget(app2, viewer = dialogViewer("app2"))
  if (ret) {
    tryCatch(Sys.sleep(0.1), interrupt = identity)
    run_app1()
  }
}

run_app1()
`````

Unfortunately, this isn't really complete since you'll get a warning from RStudio about being unable to interrupt R, so I think the real solution here is to figure out why RStudio is interrupting R, and ask it politely to not do that in this case.

**Comment by kevinushey** [comment]
The interrupt is getting emitted here:

https://github.com/rstudio/rstudio/blob/3fba3707760ee74e14f1d682ec49e726084ac3d3/src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyGadgetDialog.java#L169-L175

And the "disconnect" here:

https://github.com/rstudio/rstudio/blob/3fba3707760ee74e14f1d682ec49e726084ac3d3/src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyGadgetDialog.java#L119-L130

We probably need some way of tracking whether the Shiny application is gracefully stopping.

**Comment by daattali** [comment]
I tried your semi-solution, I'm seeing this dialog pop up

![image](https://user-images.githubusercontent.com/952340/221625739-7f3e1a3b-b5b0-46df-98ec-6933069338a1.png)


Is this what you meant by " you'll get a warning from RStudio about being unable to interrupt R"? I can live with a warning in the console, but this dialog is indeed not workable

**Comment by daattali** [comment]
Bad bot

**Comment by tsahota** [comment]
Not sure if I have the same issue, but when I run the following simple test with dialogViewer(), the app runs, but certain subsequent functions will cause the wrapper function (test_analysis_directory_setup_app) to exit without error and give back the R console.  These functions include, Sys.sleep() I've tried to catch the error but to no avail, it just terminates and never prints any of the final print messages.  With `paneViewer()` and `browserViewer()` it gets to the end of the function just fine.  I am running this on RStudio Server Pro

```r
## The shiny app

library(shiny)
library(miniUI)

server <- function(input, output, session) {
  observeEvent(input$done, {
    res <- reactiveValuesToList(input)
    stopApp(returnValue = res)
  })
}

ui <- miniPage(
  gadgetTitleBar("test app"),
  miniContentPanel(
    checkboxInput("test", label = "test")
  )
)


test_app <- function(){
  
  tryCatch({
    
    ## launching shiny app
    shiny_output <- shiny::runGadget(ui, server, viewer = shiny::dialogViewer(""))
    #shiny_output <- shiny::runGadget(ui, server, viewer = shiny::paneViewer())
    #shiny_output <- shiny::runGadget(ui, server, viewer = shiny::browserViewer())
    
    print(paste("shiny app finished with box checked:", shiny_output$test))
    
    print("start sleep")
    Sys.sleep(5)  ## other functions that fail here: gert::git_commit(), waldo::compare()
    print("finished sleep")

  }, error = function(e){
    print(paste("caught an error: ", e))
  }, finally = function(){
    print("finally of tryCatch executed")
  })
  print("finished function")
  return(shiny_output$test)
  
}

```

Then if I run `test_app()` I get the following - no "finished sleep" or error message caught or finished function:

```r

> Sys.getpid()
[1] 30877
> x <- 1
> test_app()

Listening on http://127.0.0.1:4698
[1] "shiny app finished with box checked: TRUE"
[1] "start sleep"
> Sys.getpid()
[1] 30877
> paste("x:", x)
[1] "x: 1"

```

Note: The R session remains active, and I appear to lose no workspace objects (and the session has same pid)

Please let me know if I should make another issue if this is unrelated

**Comment by Arthfael** [comment]
This is still an issue. I have a rather extensive workflow in R which needs to open consecutively several shiny apps. There is no way these can be combined as one: one selects an input directory and workflow, the next maps files to samples, the third samples to experimental factors, the fourth edits parameters, etc... Whenever two apps open too close in time, typically within a handful of seconds (but I have not checked precisely what is a safe time), in a non-reproducible (but frequent) manner the second one will not load properly, e.g. with an empty grey popup or worse will just skip without resolving.
