### ISSUE TITLE
How to remove python variables from RStudio python environment_ preferable with the broom... 

### ISSUE THREAD

**Issue by HomeStayMom** [rstudio/rstudio#12777]
Hi, I am trying to find a nice and elegant solution for removing variables from RStudio python environment without success.
However I came across an old post as per
https://community.rstudio.com/t/how-to-clear-restart-the-python-environment-within-rstudio/101961
and wonder if there was any improvement in the subject?

**Comment by ronblum** [comment]
@HomeStayMom Thank you for raising this! This is covered by issue #8750, but it has not been implemented. I'll mark this as a duplicate, as the other one already has the history, including interest shown in this.

**Comment by Wolfgang-Garn** [comment]
In RStudio, select the Python console: 
`globals().clear()` removes all variables and functions. 
`del myVar` removes a specific variable.
