### ISSUE TITLE
Find in Files's "open file" feature doesn't respect Source vs Visual for Rmds

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#12774]
If you have an Rmd file that you've been using `Visual` mode with, then opening that file from the Find in Files menu won't respect the fact that you've been using `Visual` mode, and will instead _always_ open it in `Source` mode

I was expecting it to open in Visual mode here

https://user-images.githubusercontent.com/19150088/222190804-d9b09d43-3134-425c-b977-3c116103681b.mov

I'm on a somewhat recent daily

RStudio 2023.03.0-daily+293 "Cherry Blossom" Daily (df7efaa7c605d91399201ad68eb607d5c16fda54, 2023-02-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0-daily+293 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

**Comment by DavisVaughan** [comment]
keep alive

**Comment by olivroy** [comment]
I love the find in files shortcut. So, I think this is worth looking at! Especially in a book project! If #13205 gets implemented, the find in files will be even more useful for Quarto projects, like blog and books. So it would be great to have this one sorted out!

**Comment by olivroy** [comment]
Probably a duplicate of https://github.com/rstudio/rstudio/issues/9012 actually.

**Comment by DavisVaughan** [comment]
Yes I believe it is a dup of #9012 where I post a similar video https://github.com/rstudio/rstudio/issues/9012#issuecomment-791449145
