### ISSUE TITLE
knit Pdf has error: LaTeX Error: Unicode character 长 (U+957F)

### ISSUE THREAD

**Issue by littleshark-xuan** [rstudio/rstudio#12773]
But all my files are in English, I tried many ways to still have this problem, even after downloading someone else's new RMD file, it's still the same, I also uninstalled and reinstalled R many times. Even reset the computer still has this problem.
How can I do

**Comment by ronblum** [comment]
@littleshark-xuan Thank you for raising the issue! A couple of things:
1. Can you provide a bit of code for this? I'd like to use the same code that you're using to try and reproduce.
2. What is you environment? 
    RStudio Edition : (Desktop or Server)
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by littleshark-xuan** [comment]
RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
OS Version：22621.1265
THX！！

[PE-1---Solutions.docx](https://github.com/rstudio/rstudio/files/10872205/PE-1---Solutions.docx)


> @littleshark-xuan Thank you for raising the issue! A couple of things:
> 
> 1. Can you provide a bit of code for this? I'd like to use the same code that you're using to try and reproduce.
> 2. What is you environment?
>    RStudio Edition : (Desktop or Server)
>    RStudio Version :
>    OS Version      :
>    R Version       :

**Comment by ronblum** [comment]
@littleshark-xuan Thank you for providing the environment information! Can you also provide sample code so that we can try to reproduce the issue? The Rmd file that you mention above might by good.
