### ISSUE TITLE
Update to Electron 23

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#12785]
Electron 23 has been released and adopting it would bring the latest Chromium along with fixes and features. The most notable change is using Node 18.

Electron 22 does not have an EOL set yet but the past several major releases have EOL dates less than a year after stable release.

https://www.electronjs.org/docs/latest/tutorial/electron-timelines

**Comment by jonvanausdeln** [comment]
Tested on 2023.05.0-daily+60

New Electron was present. Ran all automated desktop tests and passed without issue.
