### ISSUE TITLE
Reinstate ability to save R script as another file type

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#12780]
My usual workflow for non-R files is Cmd+Shift+N => Cmd+S => type [something.NotR] => confirm dialog. This is faster than Command Palette => type to find Create ... file => Enter etc.

Now I get 'You cannot save this document with extension “.NotR” at the end of the name. The required extension is “.R”.' with no option to override. 

I find this rather unhelpful - the warning to not save files with the wrong extension made sense, but not being able to override feels like too much of a hindrance to actually deciding how I want to save my file, esp. when the "New R file" is at hand and the only "Create file" item with a default keyboard shortcut.

**Comment by petrbouchal** [comment]
Hi @ronblum sorry about the missing info - here it is. I suspect it might be the MacOS 13.3 Beta...

RStudio Edition : Desktop
RStudio Version : Version 2023.03.0+382 (2023.03.0+382)
OS Version      : 13.3 (a) Beta (22E7752300f)
R Version       : 4.2.1

**Comment by petrbouchal** [comment]
Also verified on most recent MacOS 13.. Beta 3 (22E5236f)

**Comment by petrbouchal** [comment]
Hi - just to point out this is still an issue on a non-beta MacOS as well.
![image](https://github.com/rstudio/rstudio/assets/1666657/53b70f82-8740-4983-9872-4f6e9f772c85)

RStudio Version 2023.09.0+448 (2023.09.0+448)
MacOS 13.5.2 (22G91)

**Comment by ronblum** [comment]
Reproduced in MacOS 14 with 2023.09.0+463. This is true for other file types, e.g. trying to save a JSON file with the ending `.xml`.

Two workarounds:
1. In the lower right-hand corner of the Editor Pane, change the file type before the first save.
or
2. After saving, right-click on the document's tab at the type, and choose "Rename".

**Comment by kevinushey** [comment]
Is this still an issue? I'm able to save R files with an arbitrary file extension if I change the format to "All Files" before save.

<img width="814" alt="Screenshot 2024-03-25 at 10 29 49 AM" src="https://github.com/rstudio/rstudio/assets/1976582/0724618d-bc95-46ec-963c-dae345af4095">
