### ISSUE TITLE
Four-tick blocks stop correct code formatting and outline in RMarkdown files 

### ISSUE THREAD

**Issue by piiskop** [rstudio/rstudio#12788]
### System details

    RStudio Edition : Server 
    RStudio Version : RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
    OS Version: No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

    R Version: r ('littler') version 0.3.17

using GNU R Version 4.2.1 (2022-06-23)

### Steps to reproduce the problem

Create an R markdown file that has a four-tick block as follows:

`````
# LaTeX

## Page Orientation

````{verbatim label = "landscape"}
```{=tex}
\begin{landscape}
```

Here is anything that needs to be displayed in landscape mode.

```{=tex}
\end{landscape}
```

````
```{=tex}
\begin{landscape}
```

Here is anything that needs to be displayed in landscape mode.

```{=tex}
\end{landscape}
```

## List of tables and figures  
  
Normally, the caption for a list of tables and a list of figures is shown no matter whether tables or figures exist. 

`````

### Describe the problem in detail

The normal text after a four-tick block is shown gray as in the header of a code chunk. The second three-tick block inside the four-tick block has its content gray not black. The outline does not show anything past the four-tick block.

### Describe the behavior you expected

i expect all the text everywhere to be displayed as it would be displayed if no four-tick blocks are used. i expect the outline to work for all the headings and code chunks no matter whether there is a four-tick block.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@piiskop Thank you for raising this! A couple of similar issues, breaking one for the formatting and a second for the outline, have been filed as #10079 and #12161, so I'm closing this one as a duplicate
