### ISSUE TITLE
Buggy space in copy and paste using visual markdown

### ISSUE THREAD

**Issue by stanleesocca** [rstudio/rstudio#12783]
### System details

    RStudio Edition :  Desktop
    RStudio Version : RStudio 2022.12.0+353 
    OS Version      :  Windows
    R Version       :  4.2.2

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
### Steps to reproduce the problem

A working text document written in quarto/rmarkdown using the visual editor mode. The issue is non-existent for the normal source mode.  For example, using this piece of text in visual markdown mode:

```
Sediment cores were collected with an UWITEC single corer (USC 09000) equipped with 30 kg of ballast. The coring tubes have a length of 120 cm with an internal diameter of 9 cm. At least, two sediment cores were retrieved with a well-preserved sediment-water interface. One core is dedicated to sediment sampling by cutting and the second to pore water sampling for laboratory analysis.
```

### Describe the problem in detail
Using the visual markdown feature is incredibly handy. However, I notice whenever I copy and paste a text with the document, I encountered huge space between the pasted text and the preceeding and proceeding texts. 

![image](https://user-images.githubusercontent.com/31194250/222680889-4e371763-1015-48da-b84c-fdee470c0bea.png)

### Describe the behavior you expected

I anticipate that the pasted text will fit directly without such large spacing. See below for an example of where I have to manually delete the spaces.

![image](https://user-images.githubusercontent.com/31194250/222681499-a4fe76af-192c-4363-8e11-18aa23a52e45.png)

Thanks for this great piece of software. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@stanleesocca Thank you for raising the problem! This is already tracked in issue #12587, so I'll close this bug as duplicate as it's already being tracked.
