### ISSUE TITLE
Unreadable codes (help pane)

### ISSUE THREAD

**Issue by cenkicoz26** [rstudio/rstudio#12793]
### System details

    RStudio Edition : 
    RStudio Version : Version: 2022.12.0+353 
    OS Version      : Windows 10
    R Version       : 4.2.2
![image](https://user-images.githubusercontent.com/81703642/223177247-31ba51c0-2f8d-4b63-9f81-bbac7a54a8e0.png)

After the last update of my R studio version, codes in help pane could not be read. Only solution I get is the change of the editor theme from Idle fingers to white background themes like Chrome or others. I prefer to use black backgrounds.

**Comment by kevinushey** [comment]
I wasn't able to reproduce:

<img width="1685" alt="Screenshot 2023-03-06 at 11 46 34 AM" src="https://user-images.githubusercontent.com/1976582/223214756-1e7f9050-dcbb-46cc-8725-e52f30b99af5.png">

Can you please confirm you are indeed running the latest version of RStudio (via Help -> About RStudio)? The issue you're seeing should be resolved in the current release.

**Comment by cenkicoz26** [comment]
Problem resolved after manually installing the latest version of R studio. I thought my version is the latest one and checked for  the updates in the help menu tnd was told the same also. Thank you.
