### ISSUE TITLE
Error when running x86_64 binaries on M1 Mac without rosetta installed

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#12791]
> Hello.
> 
> I leave this comment in case someone else gets the same error. I'm working on a mac mini running macOS ventura 13.1 with an M1 chip. I have **R 4.2.2** and **RStudio 2022.12.0 Build 353** installed. Everything works fine, except that when I tried to create a .qmd file, I got the error window "State not recoverable". The issue was resolved by installing rosetta with `/usr/sbin/softwareupdate --install-rosetta --agree-to-license`.

_Originally posted by @armelbrizuela in https://github.com/rstudio/rstudio/issues/10871#issuecomment-1387501651_

Users that haven't installed rosetta yet on M1 may encounter an error when RStudio running these executables. Normally, MacOS would present a prompt to guide the user to install rosetta.

It may be helpful to surface this guidance or notify the user that the error is due to needing rosetta.

**Comment by sharon-wang** [comment]
Is there a good place for us to list general M1 Mac troubleshooting instructions? In addition to errors like the above, sometimes users run into architecture mismatch situations which cause errors to occur in RStudio or other dependencies, and those errors don't always indicate that an architecture-related discrepancy needs to be resolved.

For example, someone might have x86_64 R/RStudio, but through `brew` they might install an aarch64 dependency, which is incompatible with their R/RStudio. In the case of the `odbc` driver library installed via `brew`, they might get a "file not found" error or some sort of "failed connection" error from `odbc`, but it's not obvious from those errors that they need the x86_64 version of `odbc`, or alternatively, that they need to install aarch64 R/RStudio to work with their aarch64 `brew` installation of `odbc`.

I'm thinking some generic instructions like:
- ensure you have rosetta installed, here's how: `/usr/sbin/softwareupdate --install-rosetta --agree-to-license`
- try installing the x86_64 version of the library -- install x86_64 `brew`, then use that `brew` to install your library
- ensure you're using either the aarch64 version for each piece of software you're trying to connect together, or the x86_64 version for each piece, but don't mix architectures

**Comment by ronblum** [comment]
@sharon-wang Perhaps as [a support article](https://support.posit.co/hc)?

**Comment by gtritchie** [comment]
Be aware we still ship some Intel-only components with RStudio Desktop, so they require Rosetta: https://github.com/rstudio/rstudio/issues/12572

If you write a support article, consider including a link to https://support.apple.com/en-us/HT211861.

A support article is good, but we could also consider a feature where the app detects it is running on Apple chip and checks to see if Rosetta is installed. If not, we could give a warning that includes a link to the support article (and a "don't show this again"). Probably overkill, unless a lot of users are hitting this.

**Comment by kevinushey** [comment]
> we could also consider a feature where the app detects it is running on Apple chip and checks to see if Rosetta is installed.

I would vote for this approach. https://apple.stackexchange.com/a/435190/158249 suggests it's pretty straightforward to detect if Rosetta is installed / running.

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+369](https://dailies.rstudio.com/version/2023.09.0-daily+369)

**Comment by javentous** [comment]
Hello, I am using the latest stable RStudio v2023.06 and daily RStudio-2023.12.0-daily-311, and I tried both Quarto CLI 1.3.450 and the prerelease Quarto CLI 1.4.506. My R version is 4.3.2. I have reinstalled the stable versions multiple times to no avail.

I still have the "State not recoverable" error when trying create a new Quarto Document or Quarto Presentation.

Also, when I try to render from RStudio by clicking the button with the tutorial hello.qmd I get the following error:

`quarto script failed: unrecognized architecture`
`/Applications/quarto/bin/quarto: line 129: sysctl: command not found`

However when running from Terminal I can `quarto render` and `quarto preview` fine.

I added `/usr/sbin/` to my path as sysctl is in `/usr/sbin/sysctl' which I got from `where sysctl` in my Terminal. I can run sysctl in my Terminal without issue.

**Comment by sharon-wang** [comment]
Hey @javentous, I'm sorry to hear you're having issues. Thanks for sharing this information.

If you are using an M1/M2/Arm64 Mac, do you have Rosetta installed? You can install Rosetta by running `/usr/sbin/softwareupdate --install-rosetta` in your Terminal. After installing, restart RStudio and try to create a new Quarto Document.

If installing Rosetta does not solve the issue for you or if you're using an Intel-based Mac, could you share the following?
- is there a version of RStudio that was previously working for you?
- output of `R.Version()$platform` in the RStudio Console
- output of `which quarto` in your RStudio Terminal
- output of `quarto check` in your RStudio Terminal

**Comment by javentous** [comment]
I have run the `--install-rosetta` command before, I will go through your recommendations. I have an M1 Pro MacBook.
1. Ran `/usr/sbin/softwareupdate --install-rosetta` 
   - No dice, same errors as before
2. Yes, I can't recall the version, it was with Ventura, I believe 8 months to a year ago, I was up-to-date at that time.
3. `> R.Version()$platform`
`[1] "aarch64-apple-darwin20"`
4. `❯ which quarto`
`/Applications/quarto/bin/quarto`
5. `❯ quarto check`
`Quarto 1.4.506`
`[✓] Checking versions of quarto binary dependencies...`
`      Pandoc version 3.1.9: OK`
`      Dart Sass version 1.69.5: OK`
`      Deno version 1.37.2: OK`
`[✓] Checking versions of quarto dependencies......OK`
`[✓] Checking Quarto installation......OK`
`      Version: 1.4.506`
`      Path: /Applications/quarto/bin`
`[✓] Checking tools....................OK`
`      TinyTeX: (not installed)`
`      Chromium: (not installed)`
`[✓] Checking LaTeX....................OK`
`      Tex:  (not detected)`
`[✓] Checking basic markdown render....OK`
`[✓] Checking Python 3 installation....OK`
`      Version: 3.11.6`
`      Path: /opt/homebrew/opt/python@3.11/bin/python3.11`
`      Jupyter: 5.3.1`
`      Kernels: python3, ir, bash, sos`
`[✓] Checking Jupyter engine render....OK`
`[✓] Checking R installation...........OK`
`      Version: 4.3.2`
`      Path: /Library/Frameworks/R.framework/Resources`
`      LibPaths:`
`        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library`
`      knitr: 1.45`
`      rmarkdown: 2.25`
`[✓] Checking Knitr engine render......OK`

**Comment by sharon-wang** [comment]
Hi @javentous!

Thanks for confirming those details. I've opened a [new issue](https://github.com/rstudio/rstudio/issues/13993) so we can track this. Could you please share the OS version of your Mac in the [new issue](https://github.com/rstudio/rstudio/issues/13993)?
