### ISSUE TITLE
Warning in R Console about deprecated --self-contained option

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#12808]
### System details

    RStudio Edition : Desktop (Pro, although it probably doesn't matter)
    RStudio Version : 2023.03.0+385.pro1
    OS Version      : Ubuntu 20.04
    R Version       : 4.1.3

### Steps to reproduce the problem

1. Start an R Session
2. Maybe make and render an R markdown document, make and preview an R notebook, or make and render a Quarto document? Maybe it just happens on startup.

### Describe the problem in detail

This warning text in the console:
```
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
```

### Describe the behavior you expected

No warning. Reference to the option:
https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/ModuleTools.R#L412

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Elmerot** [comment]
Had the exact problem today. Happens as soon as I try to save an R notebook.
RStudio Edition: Desktop
RStudio Version: 2022.12.0+353
OS Version: Mac OS 10.15.7
R Version: 4.2.2 (2022-10-31)

**Comment by lillianhorin** [comment]
Just in case it is helpful. I had the same problem. Had to update base R, RStudio, and try and reinstall rmarkdown ~3 times but eventually the issue stopped.
