### ISSUE TITLE
RStudio (Version: 2022.12.0+353)  Desktop IDE did not Start. Previous version 2022-10-31 works fine

### ISSUE THREAD

**Issue by abzer005** [rstudio/rstudio#12814]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 2022-10-31 ucrt; "Innocent and Trusting"
    OS Version      :  Windows 10 x64 (build 22621)
    R Version       :  4.2.2

### Steps to reproduce the problem
 Try to install the latest R version. I will upload the log report soon

### Describe the problem in detail
Previously I had  the RStudio Version (2022-10-31) and R Version 4.2.2 and everything was working well. Since I got notified to install the lastest R version, I tried to install it (Version: 2022.12.0+353).  RStudio Desktop IDE did not start and gave me error repeatedly. I tried to uninstall R and RStudio, removed all Cache memory in: C:\Users\username\AppData\Local --> Both R and RStudio folders. Then reinstalled R and new release of RStudio. It still crashed. Finally, I uninstalled everything once again and installed the RStudio Version (2022-10-31) and R Version 4.2.2 and it worked fine. 
### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@abzer005 Thank you for raising this! It might be the same issue as #12497, so I'm closing this one as a duplicate. I'll add a couple of notes there.

**Comment by keyvanbts** [comment]
Hi
