### ISSUE TITLE
Editor looks blurry when zoomed in regardless of rendering engine

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#12812]
In the latest debian versions, if I set some zoom level in the editor and scroll through some R file, at random points the picture will become blurry.

This is regardless of the settings that I have for rendering engine, and happens in both stable releases and daily builds. It used to be the case that software rendering didn't suffer from this issue in the past, but now it does too.

![rstudio_is_blurry](https://user-images.githubusercontent.com/11860098/223803265-4630aaf7-bc0b-4832-a1d5-f9bf05092501.png)

**Steps to reproduce:**
* Launch RStudio.
* Go to Tools -> Global Options -> Appearance -> Zoom -> set to 110%.
* Optionally, set the rendering engine to software in General -> Advanced -> OS Integration -> Rendering Engine.
* Open a long file with many lines.
* Scroll throughout the file.

**Observed behavior:** at random points, it comes blurry as I scroll up/down, then becomes normal again as I keep scrolling, then again blurry, etc.

**Expected behavior:** should always look sharp.

**Setup:** R 4.2.2 Patched (2022-11-10 r83330), RStudio 2023.03.0 Build 385.

Bug happens in linux (debian) and mac (m1).

More info from KDE info center when running in linux:
```
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-6-amd64 (64-bit)
Graphics Platform: X11
Processors: 20 × 12th Gen Intel® Core™ i7-12700H
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: SLIMBOOK
Product Name: Executive
```

**Comment by ronblum** [comment]
@david-cortes Was this working in Debian 11 and only started with Debian 12?

**Comment by david-cortes** [comment]
> @david-cortes Was this working in Debian 11 and only started with Debian 12?

I'm not sure. It was working on debian 11 with past versions of RStudio, but I don't know at which RStudio version it started happening.

The bug also occurs with macOS 12 and macOS 13 BTW, on multiple monitors, and on laptop screens too.
