### ISSUE TITLE
Sequence of key chords not working in emacs mode

### ISSUE THREAD

**Issue by mihem** [rstudio/rstudio#12815]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      :  Ubuntu 22.04.2 LTS
    R Version       : 4.2.1

### Steps to reproduce the problem
1. Set keybindings to "Emacs" in "Code".
2. Change command (for example "Copy Lines Down") to Ctrl+C Ctrl+Y via "Modify keyboard shortcuts".

### Describe the problem in detail
The expected command is not executed.

### Describe the behavior you expected
After changing keybinding to "Default" everything works as expected.
Note: some commands, for example "Browse Addins" work fine with "Ctrl-C Ctrl+Y".
"Ctrl-C Y" also works fine for "Copy Lines Down".

There are a few other inconsistencies, for example: "Select All" cannot be set to "C-x h".
Maybe @kevinushey (Thanks for including emacs keybindings!)?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mihem Thank you for raising this! Is this occurring only with the particular key combinations that you describe, or any shortcuts?

**Comment by mihem** [comment]
@ronblum thanks for your support.

It is not limited to that particular key combination, so e.g. changing "Copy Lines Down" to "Ctrl+c Ctr+u" doesn't work, but Ctrl+C Ctrl+C works fine. But then "Ctrl+c Ctrl+u" works fine for "Browser Addins". So seems to be the combination of some (most of?) key comibinations and commands , that don't work.
