### ISSUE TITLE
Option for native dialog has different default in different OSes

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#12823]
If I install RStudio for windows, the setting for using native dialogs is On by default (Tools -> Global Options -> General -> Advanced -> Use native file and message dialog boxes).

But in linux, the same setting is turned off by default.

In general, dialogs look better using the system's QT settings in linux, but IMO they look worse when drawn using the windows dialogs that always present choices vertically and put the same arrow icons on them.

**Comment by gtritchie** [comment]
This was done on purpose (#11100) as a workaround for https://github.com/electron/electron/issues/32857.

This issue can track hopefully undoing that at some point.

**Comment by gtritchie** [comment]
Note that there are no "Qt" dialogs or settings in RStudio starting with the December 2022 (Elsbeth Geranium) release.

We no longer use Qt in any fashion (except in RStudio Desktop Pro, but that will be changing soon as it gets moved over to Electron as well).
