### ISSUE TITLE
[Windows] Cannot browse file system with non-native file picker/dialogs

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#12827]
In windows, if I configure RStudio to **not** use native dialogs, the built-in QT file picker from RStudio will not let me explore the computer's file system beyond the working directory folder. Would be better to decouple the selection of file picker and dialogs, since one is purely about aesthetics while the other involves functionality.

**Steps to reproduce:**
* Set the working directory to the default (user's home directory).
* Launch RStudio.
* Go to Tools -> Global Options -> General -> Advanced -> untick "Use native file and message dialog boxes", press Apply and then Ok.
* Go to File -> New Project -> Existing directory -> Browse.
* Try to have the project under a new folder in `C:\`.

**Expected behavior:** should let me browse the file system, go to any drive letter that's accessible, create folders, etc. Ideally, should always use the native file picker for this.

**Actual behavior:** doesn't let me browse `C:\` or go above the user folder.

**Setup:** RStudio 2022.12.0 Build 353, windows 10.

**Comment by gtritchie** [comment]
Note that RStudio no longer uses Qt in any fashion (except, for the moment, RStudio Desktop Pro, but that will be changing).

The file dialogs are either the native operating system dialogs, or the RStudio Server HTML-based dialogs. Qt doesn't enter into it.
