### ISSUE TITLE
RStudio fails to start when run from vim, and is confused about which framework functions to use.

### ISSUE THREAD

**Issue by esaru** [rstudio/rstudio#12821]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353 "Elsbeth Geranium " 
			(7d165dcf, 2022-12-03) for macOS
    OS Version      : Ventura 13.2.1 on Mackbook Air M1 2020 16GB
    R Version       : 4.2.2 (2022-10-31) -- "Innocent and Trusting"
			aarch64-apple-darwin20 (64-bit)

### Steps to reproduce the problem

Attempt to boot RStudio from inside Vi (or Vim, or NeoVim too)

### Describe the problem in detail

With an fully updated installation of RStudio/R/{vi,vim,nvim} try the following:

in vi/vim/mvim/nvim:

:!/Applications/RStudio.app/Contents/MacOS/RStudio

(which bombs, and throws the errors as attached - RStudio seems 1) unspecific about WebSwapCGLLayer vs. two sources and 2) not to recognize it's arm64)

compare the result with 

:!/Applications/R.app/Contents/MacOS/R

(successfully boots the CRAN GUI...)

further compare this with running /Applications/RStudio.app/Contents/MacOS/RStudio from the command line.

(It throws the frameworks confusion error but successfully boots)

This is happening both on a configured system and on a bare-bones re-install, everything updated, no .Rprofile, totally vanilla .virmrc etc, following all the instructions in the RStudio failure-to-boot page.    Path is confirmed to be the same within vim and in an interactive shell. Shell is set to be zsh by default on MacOS. The deviation was induced by updating RStudio. I have not rolled back to identify when it went sideways.

Attached error transcript:

[error_1.txt](https://github.com/rstudio/rstudio/files/10947691/error_1.txt)
[error_2.txt](https://github.com/rstudio/rstudio/files/10947692/error_2.txt)

### Describe the behavior you expected

Should boot the GUI, and when this is closed, return control to vi/vim/etc.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by esaru** [comment]
I'm closing this, as I've figured out it's from Vim setting the architecture wrong.

see: https://github.com/jalvesaq/Nvim-R/issues/720#issuecomment-1465015180

**Comment by ronblum** [comment]
@esaru Thank you for letting us know! This'll be useful for other RStudio users who run from instead vi, etc., and run into similar issues.
