### ISSUE TITLE
[Windows] Installing package from build pane doesn't offer me to restart R session

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#12828]
If I'm installing a package with `install.packages`, RStudio oftentimes will offer me to restart the R session before installing if something is already loaded. But if I'm installing the package through the "Build" panel, it will not offer me to do so - in windows, this leads to getting an error message about something being non-writtable, since a previous install will have the files locked. It's not obvious to the user that he needs to restart the R session to unlock them.

**Steps to reproduce:**
* Create an R package project with compiled code. Take some random package from CRAN like `Matrix` for this.
* Go to Build -> Install Package.
* After it finishes, click the down arrow in the Install button in the build pane, and select "Clean and Install".

**Expected behavior:** should offer me to restart the R session before installing, so that the operation would succeed.

**Actual behavior:** errors out with an unhelpful message.

**Setup:** RStudio 2022.12.0 Build 353, windows 10.

**Comment by ronblum** [comment]
@david-cortes Thank you for bringing this up!
