### ISSUE TITLE
Website needs to update build version for debian 12

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#12822]
The RStudio builds that say `Ubuntu 18+/Debian 10+` do not work on Debian 12. The correct build for a Debian 12 system is the one that says `Ubuntu 22`. The website should be updated to say `Ubuntu 22+/Debian 12+`.
![rstudio_build_for_debian_wrong_version](https://user-images.githubusercontent.com/11860098/224494683-76b35ddb-0cea-4514-b767-0d6a92c73835.png)

**Comment by ronblum** [comment]
Thanks @david-cortes !

Keeping this as `new` for the moment as a reminder to file an internal change request.

**Comment by ronblum** [comment]
@david-cortes Oh, I meant that we haven't certified RStudio on Debian 12 yet. 🙂  We'll do that a bit after Debian 12 is released. I've use the ISO of their testing builds to do some spot-checking, to make sure that the RStudio Ubuntu 22 build also works on Debian 12, but it's not a full certification—that's more involved.

**Comment by espher1987** [comment]
hi, any update about .deb version for debian 12? thanks in advance. And thanks for your good job.

**Comment by ronblum** [comment]
The Ubuntu 22 download of RStudio runs on Debian 12. However, this config hasn't been fully tested. Now that Debian 12 is live, we hope to certify the next release of RStudio on it—I can't say with certainty, but that's our target.

**Comment by ronblum** [comment]
@Gustavo-Fabris Can you provide sample code that generates this issue?

**Comment by Gustavo-Fabris** [comment]
Hi. I am not A IT guy. I am a veterinarian who works with public health in Brazil. By sample code you mean the part of my script that generated the problem?


RS22_22_23_CICLOS_LOCALIDADES <- read_sheet("https://docs.google.com/spreadsheets/d/18hJMQnlFcRHeqNbtJObD0UCx8L-lOcJpOTYkn849Fcs/edit#gid=764914932")

###Substituindo NA por 200 na planilha. O QGIS não está reconhecendo NA e as variáveis ficam como String no SIG.###

RS22_22_23_CICLOS_LOCALIDADES[is.na(RS22_22_23_CICLOS_LOCALIDADES)] <- 200

The problem is when I try to substitute the NA in the line above...

**Comment by RachaelMDavies** [comment]
Hi, the Ubuntu 22 version does not work properly in Debian 12, there are problems with dependencies. Is there an ETA for the working Debian 12 version? Thanks!

**Comment by earthmoon** [comment]
> Hi, the Ubuntu 22 version does not work properly in Debian 12, there are problems with dependencies. Is there an ETA for the working Debian 12 version? Thanks!

I meet the same problem and has the same hope.

**Comment by ronblum** [comment]
Can you please provide the errors that you're seeing, as well as the version of RStudio and R that you're using? I'm unable to reproduce the problem—the Ubuntu 22 build for RStudio Desktop 2023.09.1+494 works for me on Debian 12.2.

**Comment by earthmoon** [comment]
> Can you please provide the errors that you're seeing, as well as the version of RStudio and R that you're using? I'm unable to reproduce the problem—the Ubuntu 22 build for RStudio Desktop 2023.09.1+494 works for me on Debian 12.2.

R version is 
```
R version 4.3.2 (2023-10-31) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
The version of Debian is 
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
The version of RStudio is 
```
RStudio 2023.09.1+494 "Desert Sunflower " (cd7011dc, 2023-10-16) for Ubuntu Jammy
```

The problem report is
```
## R Session Startup Failure Report

### RStudio Version

RStudio 2023.09.1+494 "Desert Sunflower " (cd7011dc, 2023-10-16) for Ubuntu Jammy

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 127. 

Error output:

/usr/lib/rstudio/resources/app/bin/rsession: error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory

Standard output:
[No output emitted]

### Logs

*/home/zhenyu/.local/share/rstudio/log/rsession-zhenyu.log*

2023-11-17T13:58:31.834461Z [rsession-zhenyu] ERROR r error 4 (Error in readRDS(dest) : error reading from connection
) [errormsg: Error in readRDS(dest) : error reading from connection
]; OCCURRED AT rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) src/cpp/r/RExec.cpp:231; LOGGED FROM: std::string rstudio::session::modules::dependencies::{anonymous}::buildIndividualInstallScript(const std::vector<rstudio::session::modules::dependencies::{anonymous}::Dependency>&) src/cpp/session/modules/SessionDependencies.cpp:430

```
                
Thanks.
