### ISSUE TITLE
Add button to stop Quarto document preview in a more visible place

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12837]
Currently, there is a way to start Quarto document preview (e.g., in a browser or Viewer pane). But there is no one to stop the preview.
This might lead to issues like:

- https://github.com/rstudio/rstudio/issues/12836
 
![image](https://user-images.githubusercontent.com/12725868/225013528-9cf30aeb-b190-4ee2-8278-cfdaa5df3dae.png)

**UPDATE**

There is a "Stop" button in the "Background Jobs" tab but the tab is usually hidden. 
![image](https://user-images.githubusercontent.com/12725868/225056734-60f47520-1664-4f6b-adc6-ed47e6ecf4e8.png)

Can there be an additional "Stop Preview" button somewhere near the `Render` button or/and in the Viewer tab or/and browser tab to make it more obvious how to stop the preview?

**Comment by ronblum** [comment]
Another thought: When a background job is kicked off, keep the Background Jobs displayed instead of refocusing on the Console Pane.

**Comment by GegznaV** [comment]
Is this issue already solved?

**Comment by renatovargas** [comment]
It's a shame that this was closed. It's cumbersome to not have a clear stop preview button. Sometimes you close the browser and forget that the process was running in the background all along, until your laptop battery indicator reminds you a few hours too soon that you should have killed it a long time before.
