### ISSUE TITLE
Bug in RStudio View() loading rows >180 with data.frame longer than 43478 rows.

### ISSUE THREAD

**Issue by baderstine** [rstudio/rstudio#12834]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
    OS Version      : 13.2.1 (22D68)
    R Version       :  R version 4.2.2 (2022-10-31)

### Steps to reproduce the problem

```r
df_x = data.frame(x = 1:43478)
df_y = data.frame(x = 1:43479)

View(df_x) # no problem!
View(df_y) # problem!
```

### Describe the problem in detail

In the RStudio viewer, scroll using the mouse/trackpad down until you get past row 180. The RStudio viewer doesn't load rows past 180 if there are more than 43478 rows in the data.frame. 

You can get it to load the additional rows by: 
a) scrolling to the right any amount, and then scroll back to the left "past" the row numbers (column 0).  OR
b) click and drag the vertical scroller puck rather than use a mouse/trackpad for scrolling.

### Describe the behavior you expected
I would expect the View panel to load all rows past 180. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@baderstine Thank you for raising this! I can also reproduce it in RStudio Desktop 2022.03.0+376 on MacOS 13.2. I also tried with 100,000 records, in which case it stopped at 126. We'll review this issue as we continue development of RStudio.

Note: I can only reproduce this with the trackpad. It works correctly for me when dragging on the scrollbar with the mouse.

**Comment by baderstine** [comment]
@ronblum same for me.  It was an odd one to try to reproduce.

**Comment by baderstine** [comment]
@ronblum did this get fixed or just closed due to inactivity?

**Comment by ronblum** [comment]
@baderstine Closed due to inactivity (the bot comes in once in a while and takes over). But we made a few behind the scene changes, and it works correctly for me now in 2023.09.0+463, the latest release. Can you confirm whether or not it works for you?

**Comment by baderstine** [comment]
Nope. I'm View()ing a data frame that is 55194 rows and it won't load rows beyond row 153 when scrolling with trackpad.  :(

**Comment by ronblum** [comment]
I can reproduce this in RStudio Desktop 2023.09.0+463 on MacOS 14. I think that yesterday I checked it with the scrollbar, which works, instead of the trackpad—oops! Can you confirm whether or not it works when using the scrollbar?

**Comment by snlf** [comment]
> There's a few other bugs with the viewer that may be related:
> 
> 1. when scrolling and loading large sets of rows the viewer jumps up/down past the rows you are currently viewing when it tries to load new rows.
> 2. if you have a filter applied in columns 1-50, and you click > or >> to view columns past 50, the filter is automatically removed so you effectively cannot filter on columns 1-50 and view columns 50+.
> 
> These might need to be created as separate issues.

Was a separate issue created for item "1. when scrolling and loading large sets or rows..."?

I am experiencing these same issues.

**Comment by baderstine** [comment]
See "EPIC: Data Viewer" link above... it contains all of the viewer-related issues.

**Comment by MariaSemple** [comment]
Came up in customer support issue 98866.

**Comment by baderstine** [comment]
still appears to be an ongoing issue in 2024.04.2+764 
`View(df_y)` doesn't load rows past 189.

**Comment by ronblum** [comment]
Checked with `nycflights13::flights` (336,776 × 19 data frame) on Windows 11 with RStudio Desktop 2024.07.0+329.pro1.
- First time the cutoff is 117.
- Scrolling down a bunch will eventually load a block of rows, but scrolling back shows empty space. Then some loading and jumping back.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+210 on Windows 11 using the original example and `nycflights`.
