### ISSUE TITLE
Inserting a citation without first choosing one turns the citation window gray and it can't be dismissed

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12833]
### System details

    RStudio Edition : Desktop, Desktop Pro, and Server
    RStudio Version : 2023.03.0+386
    OS Version      : RHEL 9, Ubuntu 22, MacOS 13, Windows 11
    R Version       : 4.2.2, 4.3 (dev)

### Steps to reproduce the problem

1. Open an R Markdown or Quarto document.
2. Switch to visual ode if not already in it.
3. Click anywhere in the body.
4. <kbd>Insert -> Citation</kbd>
5. Click on <kbd>Insert</kbd>.
   - An expected pop-up appears indicating that at least one citation should be chosen.
6. Click <kbd>OK</kbd>
    - The pop-up disappears.
    - However, the citation window turns gray and it's not possible to do anything in RStudio other than quit. But...
7. <kbd>Right-click</kbd> anywhere and choose <kbd>Reload</kbd>.
    - RStudio refreshes, the citation window is gone, and the IDE becomes usable again.

### Describe the problem in detail

If a user clicks <kbd>Insert</kbd> without first selecting a citation to insert, the pop-up can be dismissed, but the window turns gray and the IDE becomes inoperable.
<img width="919" alt="gray_citation" src="https://user-images.githubusercontent.com/31009952/224830150-eb15bcfe-3a85-4837-b705-a44e7d85e0fc.png">

### Describe the behavior you expected

After the pop-up is dismissed, the citation window should be usable again. 

This is a regression from RStudio 2022.12.0+353.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
I don't think this is a a stop-ship as the user needs to do something unexpected to get into this state (Insert w/ no citation selected). Definitely worth including in a patch release if there is one. I'll investigate a fix right away.

**Comment by jjallaire** [comment]
This is fixed here: https://github.com/quarto-dev/quarto/commit/bb0a3450d35dbaf4b8d5516d38b329f7b0dfa92c

This fix has been back ported to the release/rstudio-cherry-blossom branch so the next time you build cherry blossom you will pick it (it's an extremely safe fix so you shouldn't hesitate to include it in patch release)

**Comment by jonvanausdeln** [comment]
Verified on 2023.05.0-daily+60, desktop
Windows 11, Ubuntu 22.04

After trying to insert blank citation, dialog box dismisses as expected. All citations automated tests passed as well.
