### ISSUE TITLE
Low contrast focus rectangle on Sign In button (server login page) and other misc. A11y

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12846]
### System details

    RStudio Edition : Server
    RStudio Version : Cherry Blossom (also older versions)
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

Primary issue: Tab to focus the "Sign In" button on the login page (RStudio Server or Workbench with name/password auth).

### Describe the problem in detail

The focus rectangle has (almost) identical color to the button itself, and is drawn without any gap between it and the button, so is essentially invisible. For example, the button is focused in this screenshot:

<img width="407" alt="Screenshot of rstudio login page with focus on the Sign In button" src="https://user-images.githubusercontent.com/10569626/225426265-446384d1-8fb7-4145-8718-6c0da303909a.png">

Other minor a11y issues on this page:

* Username and password are required fields, but aren't annotated as required (so it isn't announced by a screen-reader)
* Page has a pointless skip-nav link; this was one of the first things I added when I started working on accessibility; however, it isn't necessary on this page because (1) we already have both a valid `H1` and a `main` landmark for screen-reader users; (2) For a keyboard-only user, the skip-nav link doesn't save any keystrokes:

(current): 3 tabstops to get to the username field (the skip-nav link, then the banner image, then username); or a tabstop (skip-nav) followed by "enter" key (2 keystrokes)
(without skip-nav): 2 tabstops to the username field (banner image, then username)

Here's a screenshot of the skip-nav link:

<img width="619" alt="Screenshot of skip-nav link on login page" src="https://user-images.githubusercontent.com/10569626/225428404-35b458ce-b4bd-4197-b218-eeab46078cce.png">

### Describe the behavior you expected

* visible focus rectangle for Sign In button
* remove skip-nav link
* annotate inputs with `aria-required="true"`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Server 2023.05.0-daily+212 on Ubuntu 20.04 via Chrome on MacOS 13.2. Included using VoiceOver, which announces the username and password fields are required.
