### ISSUE TITLE
New GA Tracking Code

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#12840]
We will need to do this for each guide - both open source and pro

**This needs to b rolled in asap - once the legacy goes away, we will completely lose tracking in GA**

The new Google Tag Manager Tracking code to place on your websites is below. It replaces any Google Analytics code currently in use.

Any questions, please reply here, and feel free to also Slack/email: [#ga4-migration](https://github.com/rstudio/docs.rstudio.com/issues/url), [Andrew.williams@posit.co](mailto:Andrew.williams@posit.co).

On published pages, the `<script>` tag should appear in the `head` of the documents, and the `noscript` tag should appear in the <body> of the documents.

Paste this code as high in the `<head>` of the page as possible:

```
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-KHBDBW7');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening `<body>` tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KHBDBW7" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

Pro issue: [#4437](https://github.com/rstudio/rstudio-pro/issues/4437)

**Comment by ronblum** [comment]
Example of the current behavior in the daily RStudio User Guide:

![Image](https://user-images.githubusercontent.com/31009952/234989539-7b6f3636-d2fa-45c5-9f4c-e5a90d069be8.png)

Leaving open to check a little more thoroughly.

**Comment by ronblum** [comment]
@AshleyHenry15 I see this call throughout, which is correct:
- `https://www.googletagmanager.com/gtm.js?id=GTM-KHBDBW7`

I also see these calls
- `https://www.googletagmanager.com/gtag/js?id=G-2C0WZ1JHG0&l=dataLayer&cx=c`
- `https://www.googletagmanager.com/gtag/js?id=G-X64JZVV9NC&l=dataLayer&cx=c`

Are they correct?

**Comment by awilliams1275** [comment]
Yes, all of these calls are what we should be seeing.
