### ISSUE TITLE
Update to OpenSSL 3

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#12855]
OpenSSL 1.1.1 is EOL Sept 2023.

It will require updating code to conform to v3:
https://github.com/rstudio/rstudio/issues/12550

**Comment by sharon-wang** [comment]
Note that openssl 3.0 and beyond are under the [Apache License 2.0](https://www.openssl.org/source/apache-license-2.0.txt). We will need to update `NOTICE` and the packaged license notice with the new license.

source: https://www.openssl.org/source/license.html

**Comment by kevinushey** [comment]
We still need to update to OpenSSL 3 on the macOS build machine. The update to OpenSSL 3 for Windows should now be complete.

**Comment by kevinushey** [comment]
Now available on macOS.

```
kevin@MBP-P2MQ:/Applications/RStudio.app/Contents/Resources/app/Frameworks
$ strings libcrypto.dylib | grep "OpenSSL 3.2.0"
OpenSSL 3.2.0 23 Nov 2023
```
