### ISSUE TITLE
Update the link on https://dailies.rstudio.com/

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12852]
![image](https://user-images.githubusercontent.com/12725868/225611098-0d528b1e-02a9-4529-86a4-eddabd51e4ca.png)

rstudio.com → posit.co: https://posit.co/download/rstudio-desktop/

**Comment by ronblum** [comment]
Thanks @GegznaV 
One change: Direct to https://posit.co/downloads/ which includes both RStudio Desktop and Server, or just to https://posit.co.

**Comment by astayleraz** [comment]
### Verified Fixed
    RStudio Edition    :  Docs https://dailies.rstudio.com/

### Test scenario(s) 

Verified link now shows and goes to posit.co

### Automated tests 

NA
