### ISSUE TITLE
"Install" in build pane is confusing and default option is not what one usually wants

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#12865]
This button says "Install":
![rstudio_install_1](https://user-images.githubusercontent.com/11860098/225985072-16ea99c6-984b-4a81-beae-f8808a555dcb.png)

This other button has the exact same icon, also has the word "install", yet does a rather different thing:
![rstudio_install_2](https://user-images.githubusercontent.com/11860098/225985178-bb13f8e2-db15-4394-92c9-c37f58097e89.png)

IMO the one on the second (**without** `preclean`) is most often what one wants to do.

**Comment by dmurdoch** [comment]
There's a setting in Project Options called "always use --preclean".  I think it used to control which of the two kinds of install was used:  uncheck it to get what you want.  However, it appears that in version 2023.03.0+386 it is ignored.
