### ISSUE TITLE
Error: 'format_glimpse' is not an exported object from 'namespace:pillar'

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [rstudio/rstudio#12863]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.3.0.407
    OS Version      : Windows 10 x64
    R Version       : R version 3.6.3 (2020-02-29)

#### Session info

Beware: the R runtime is somewhat outdated.

<pre>
- Session info ---------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2023-03-17                  

- Packages -------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] RSPM (R 3.6.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.3)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
 glue          1.4.0   2020-04-03 [1] CRAN (R 3.6.3)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.3)
 pillar        1.4.3   2019-12-20 [1] CRAN (R 3.6.3)
 pkgconfig     2.0.3   2019-09-22 [1] RSPM (R 3.6.3)
 renv          0.13.2  2021-03-30 [1] CRAN (R 3.6.3)
 rlang         0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.3)
 tibble        3.0.1   2020-04-20 [1] CRAN (R 3.6.3)
 utf8          1.1.4   2018-05-24 [1] CRAN (R 3.6.3)
 vctrs         0.3.2   2020-07-15 [1] CRAN (R 3.6.3)
 withr         2.2.0   2020-04-20 [1] CRAN (R 3.6.3)
</pre>

### Steps to reproduce the problem

1. Setup R version and packages as above.
2. Start an RStudio session
3. Submit `tibble::as_tibble(mtcars)`
4. Type `mtcars$`

### Describe the problem in detail

Window with error message pops up, disrupting input:

![image](https://user-images.githubusercontent.com/89191115/225973271-1bddc972-f580-45ad-bcad-6d982a513288.png)

### Describe the behavior you expected

Less disruptive error handling

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mobragauk** [comment]
Same here. Using R 4.0.2.

**Comment by bgwalther** [comment]
I am using R version 4.0.2, and I am having the same problem.

**Comment by maxpohlman** [comment]
For me, this is occurring when auto-complete windows pop up

**Comment by HenningLorenzen-ext-bayer** [comment]
> For me, this is occurring when auto-complete windows pop up

Forgot to mention this...

**Comment by AiramDBG** [comment]
I read in another web that this can be solved by removing and installing following packages: pillar, ellipsis, vctrs.

I tried it and it worked for me also

**Comment by ClauGro** [comment]
Yes, I did the same and it worked for me too.
removing and installing following packages: pillar, ellipsis, vctrs.

**Comment by HenningLorenzen-ext-bayer** [comment]
> I read in another web that this can be solved by removing and installing following packages: pillar, ellipsis, vctrs.
> 
> I tried it and it worked for me also

🤔  this does upgrade the respective package versions, right?

👉  Upgrading to pillar 1.5.1, tibble 3.0.6 and vctrs 0.3.6 is a workaround for me.

<pre>
- Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] RSPM (R 3.6.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.3)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
 glue          1.4.0   2020-04-03 [1] CRAN (R 3.6.3)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.3)
 pillar        1.5.1   2021-03-05 [1] CRAN (R 3.6.3)
 pkgconfig     2.0.3   2019-09-22 [1] RSPM (R 3.6.3)
 renv          0.13.2  2021-03-30 [1] CRAN (R 3.6.3)
 rlang         0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.3)
 tibble        3.0.6   2021-01-29 [1] CRAN (R 3.6.3)
 utf8          1.1.4   2018-05-24 [1] CRAN (R 3.6.3)
 vctrs         0.3.6   2020-12-17 [1] CRAN (R 3.6.3)
 withr         2.2.0   2020-04-20 [1] CRAN (R 3.6.3)
</pre>

**Comment by taoziyu97** [comment]
me too. After update packages it still not work.

**Comment by kevinushey** [comment]
I've pushed a fix that will be live in the next daily builds (available at https://dailies.rstudio.com in the next day or so).

As a workaround, you can make sure you have a recent version of the `pillar` package installed; e.g.

```
install.packages("pillar", type = "source")
```

**Comment by HenningLorenzen-ext-bayer** [comment]
> I've pushed a fix that will be live in the next daily builds (available at https://dailies.rstudio.com in the next day or so).

Works for me with 2023.05.0-daily+210.

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2023.05.0-daily+210
Ubuntu 22.04

Works as expected with old R and pillar versions.

**Comment by a-jakob** [comment]
> > I read in another web that this can be solved by removing and installing following packages: pillar, ellipsis, vctrs.
> > I tried it and it worked for me also
> 
> 🤔 this does upgrade the respective package versions, right?
> 
> 👉 Upgrading to pillar 1.5.1, tibble 3.0.6 and vctrs 0.3.6 is a workaround for me.
> 
> - Packages ------------------------------------------------------
>  package     * version date       lib source        
>  assertthat    0.2.1   2019-03-21 [1] RSPM (R 3.6.3)
>  cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.3)
>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.3)
>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
>  glue          1.4.0   2020-04-03 [1] CRAN (R 3.6.3)
>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 3.6.3)
>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.3)
>  pillar        1.5.1   2021-03-05 [1] CRAN (R 3.6.3)
>  pkgconfig     2.0.3   2019-09-22 [1] RSPM (R 3.6.3)
>  renv          0.13.2  2021-03-30 [1] CRAN (R 3.6.3)
>  rlang         0.4.7   2020-07-09 [1] CRAN (R 3.6.3)
>  rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.3)
>  tibble        3.0.6   2021-01-29 [1] CRAN (R 3.6.3)
>  utf8          1.1.4   2018-05-24 [1] CRAN (R 3.6.3)
>  vctrs         0.3.6   2020-12-17 [1] CRAN (R 3.6.3)
>  withr         2.2.0   2020-04-20 [1] CRAN (R 3.6.3)

Thanks for sharing the packages' versions! It worked on my R 3.3.3.
Here's the fix:
```
# first remove packages
remove.packages(c("pillar", "tibble", "vctrs"))

## Install these versions, restarting session through ctrl F10 between each install

packageurl <- "https://cran.r-project.org/src/contrib/Archive/pillar/pillar_1.5.1.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

packageurl <- "https://cran.r-project.org/src/contrib/Archive/tibble/tibble_3.0.6.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

packageurl <- "https://cran.r-project.org/src/contrib/Archive/vctrs/vctrs_0.3.6.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
