### ISSUE TITLE
Build fails without Quarto: The directory /usr/ports/devel/RStudio/work-desktop/rstudio-2023.03.0-386/src/gwt/lib/quarto/apps/panmirror does not exist

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#12866]
With ```QUARTO_ENABLED=FALSE``` the build fails:
```
i18n-unix-check:
i18n-unix:
i18n-windows-check:
i18n-windows:
generate-i18n:
ext:
   [jscomp] None of the files changed. Compilation skipped.
javac:
    [javac] Compiling 1 source file to /usr/ports/devel/RStudio/work-desktop/rstudio-2023.03.0-386/src/gwt/bin
gwtc:
panmirror:
     [echo] yarn location: yarn
     [echo] panmirror location: ./lib/quarto/apps/panmirror

BUILD FAILED
/usr/ports/devel/RStudio/work-desktop/rstudio-2023.03.0-386/src/gwt/build.xml:173: The following error occurred while executing this line:
/usr/ports/devel/RStudio/work-desktop/rstudio-2023.03.0-386/src/gwt/build.xml:132: The directory /usr/ports/devel/RStudio/work-desktop/rstudio-2023.03.0-386/src/gwt/lib/quarto/apps/panmirror does not exist

Total time: 4 seconds
*** [src/gwt/timestamp] Error code 1
```

### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.03.0+386
    OS Version      : FreeBSD 13.1
    R Version       : n/a

### Steps to reproduce the problem
Regular build with ```QUARTO_ENABLED=FALSE```.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgenco** [comment]
Have you downloaded and placed panmirror in the correct location?. see [install-panmirror](https://github.com/rstudio/rstudio/blob/rel-cherry-blossom/dependencies/common/install-panmirror)
NOTE: panmirror is now located at [quarto-dev/quarto](https://github.com/quarto-dev/quarto) and is different than [quarto-dev/quarto-cli](https://github.com/quarto-dev/quarto-cli)

**Comment by ronblum** [comment]
For reference, see #12316 if the above is the cause.

**Comment by timtmok** [comment]
@jgenco Is this a fresh checkout? The dependency installer script will clone/update the quart-dev/quarto repo (panmirror aka visual editor).

**Comment by timtmok** [comment]
@yurivict Sorry, the above comment is for you.

**Comment by mikebessuille** [comment]
Closed due to inactivity

**Comment by yurivict** [comment]
@timtmok 

The build is using the released version and builds on FreeBSD.

I don't think that Quarto supports FreeBSD, and we would like to cleanly disable it.

Is ```QUARTO_ENABLED``` a wrong cmake variable? It doesn't seem to disable it since this error occurs.

**Comment by kevinushey** [comment]
That should be correct; see https://github.com/rstudio/rstudio/blob/8bc6388537b67e1eb46bc4d40ca44783d71061f1/CMakeGlobals.txt#L249-L264 for how it is used.

**Comment by yurivict** [comment]
@kevinushey 

```QUARTO_ENABLED=OFF``` doesn't cleanly disable Quarto in the NodeJS code.

I've created a separate bug report for this: https://github.com/rstudio/rstudio/issues/13558

**Comment by timtmok** [comment]
The error is with panmirror. `QUARTO_ENABLED` doesn't control panmirror (misleading due to panmirror living in the Quarto project). Quarto doesn't release a built version of the visual editor. The visual editor source is now shared between RStudio and Quarto's VS Code extension.

**Comment by rsdmse** [comment]
We also set `QUARTO_ENABLED=OFF` and are seeing the same error with releases `2023.03.2+454` and `2023.06.2+561`. The last few lines of the log:
```
panmirror:
     [echo] yarn location: ../../dependencies/common/node/16.14.0/bin/yarn
     [echo] panmirror location: ./lib/quarto/apps/panmirror
    [mkdir] Created dir: /tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/www/js/panmirror

BUILD FAILED
/tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/build.xml:173: The following error occurred while executing this line:
/tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/build.xml:132: The directory /tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/lib/quarto/apps/panmirror does not exist

Total time: 35 seconds
[592/596] Building CXX object src/cpp/server/CMakeFiles/rserver-tests.dir/session/ServerSessionRpc.cpp.o
[593/596] Building CXX object src/cpp/server/url-ports/CMakeFiles/rserver-url-tests.dir/TestMain.cpp.o
[594/596] Building CXX object src/cpp/server/CMakeFiles/rserver-tests.dir/session/ServerSessionProxy.cpp.o
ninja: build stopped: subcommand failed.
```
Do you have a patch for the dependency installer script? Or what is the solution?

**Comment by rsdmse** [comment]
I was having the same problem and running `install-panmirror` made further progress. Thanks! Now I'm getting a different error:
```
panmirror:
     [echo] yarn location: ../../dependencies/common/node/16.14.0/bin/yarn
     [echo] panmirror location: ./lib/quarto/apps/panmirror
    [mkdir] Created dir: /tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/www/js/panmirror
     [exec] yarn install v1.22.19
     [exec] [1/4] Resolving packages...
     [exec] [2/4] Fetching packages...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] error An unexpected error occurred: "https://registry.yarnpkg.com/@blueprintjs/icons/-/icons-4.12.1.tgz: ESOCKETTIMEDOUT".
     [exec] info If you think this is a bug, please open a bug report with the information provided in "/tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/lib/quarto/apps/panmirror/yarn-error.log".
     [exec] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

BUILD FAILED
/tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/build.xml:173: The following error occurred while executing this line:
/tmp/uvacse/rstudioserver/2023.03.2+454/goolf-11.4.0_4.1.4-R-4.2.3/rstudio-2023.03.2-454/src/gwt/build.xml:132: exec returned: 1

Total time: 6 minutes 20 seconds
ninja: build stopped: subcommand failed.
```
My network connection is fine.

**Comment by rsdmse** [comment]
I found that appending `<arg value="--network-timeout 1000000"/>` to the install line in `src/gwt/build.xml` fixed the issue.
