### ISSUE TITLE
Unmatched square brackets breaks "run" feature

### ISSUE THREAD

**Issue by stanstrup** [rstudio/rstudio#12862]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Windows 11
    R Version       : 4.2.2

### Steps to reproduce the problem
Create a quarto document with the following code:

````
---
title: "Untitled"
format: html
editor: visual
---

## 

This is an open interval \[1,2)

```{r}
1+2
```
````

### Describe the problem in detail
When you press the play button or "play all" nothing happens. The code chuck is not run.
This seems to be related to the unmatched square bracket. It is interpreted as a math chunk that is never properly closed. If the escaping backslash is removed you can "run" in source mode, but if you go back to visual mode the backslash is added back.

Note that "Render" works. So this seems not to be a Quarto issue.

### Describe the behavior you expected
Run should play the chunk. I am not sure if the bracket should not just be left escaped.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
Thank you for reporting this issue!

I was able to reproduce this on `MacOS 12.6` in `RStudio 2023.03.0+386 "Cherry Blossom"`.

I also tried running the above code in an RMarkdown document, which doesn't add the escaping backslash back if you view in visual mode and go back to source mode. It also allows the R code to be run even though the bracket mismatch is there.

https://user-images.githubusercontent.com/25834218/228945149-80eed86e-3891-4285-b1fb-719b944ffd0d.mov

So it seems we could match how we handle the Quarto code chunk running to how we handle it for RMarkdown, which seems more permissive.

**Comment by stanstrup** [comment]
This should not be closed. It is creating trouble for my students of the kind they cannot fix themselves.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+327 on MacOS 14.3. Checked
- Different run options, such as "Run Next Chunk" and "Restart R and Run All Chunks."
- That rendering works
- Both source and visual modes
- That the chunk has the run icon
