### ISSUE TITLE
visible and actual tab orders differ resulting in unexpected tab switching behaviour

### ISSUE THREAD

**Issue by lotard** [rstudio/rstudio#12867]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386
    OS Version      : MacOS
    R Version       : 4.2.2 

NB: this problem has been around for years, I just never bothered writing a report.

### Steps to reproduce the problem
Open three tabs (say 1,2,3). Manually drag one into a different order (say to end up with visible order 1,3,2). Manually drag another one into different order (say to end up with 3,2,1). Switch between tabs using cmd+alt+arrows. 

Moving only one won't create the problem. Closing/opening project fixes the issue.

### Describe the problem in detail
Switching order will follow original order (1->2->3->1 if wrapping enabled), not visible order (3->2->1->3).

### Describe the behavior you expected
Switching order should follow visible order (3->2->1->3).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
See also #3449

**Comment by andreehrlich** [comment]
I am having the same issue
