### ISSUE TITLE
Can't update to latest version if version was previously ignored

### ISSUE THREAD

**Issue by sharon-wang** [rstudio/rstudio#12874]
### System details

    RStudio Edition : 
    RStudio Version :  Spotted Wakerobin (but this is version-agnostic)
    OS Version      :  MacOS 13.1 (but this is OS-agnostic)
    R Version       :  4.3.2 (but this is R-version agnostic)

### Steps to reproduce the problem

> For QA, I recommend to use the steps in the QA Notes section of https://github.com/rstudio/rstudio/pull/12869 (combines two bugfix testing flows into one)

<details>
    <summary>extra notes when building and testing this locally</summary>

you might need to make the following change to `CMakeGlobals.txt` so that RStudio considers your local build out-of-date

```
# version info
set(CPACK_PACKAGE_VERSION_MAJOR "1000")
# if ("$ENV{RSTUDIO_VERSION_MAJOR}" STREQUAL "")
  # string(TIMESTAMP CPACK_PACKAGE_VERSION_MAJOR "%Y")
  # set(RSTUDIO_UNVERSIONED_BUILD TRUE)
# else()
  # set(CPACK_PACKAGE_VERSION_MAJOR $ENV{RSTUDIO_VERSION_MAJOR})
# endif()
```

</details>

Steps
1. Upon RStudio startup, ignore the newest RStudio version update
2. Manually check for update using Help > Check for Updates
3. Dialog says you're on the newest version

### Describe the problem in detail

If a user has chosen to ignore updating to the newest version of RStudio and then manually checks for updates, we currently tell them that they're on the newest version although that's not true. Rather, they're on the newest un-ignored version.

This is something I noticed while working on https://github.com/rstudio/rstudio-pro/issues/4179. I don't think there's an existing issue regarding this.

Demo of issue:

https://user-images.githubusercontent.com/25834218/226471586-342b8222-c7eb-490e-8679-3958a2939ad7.mov

### Describe the behavior you expected

Following internal Slack discussion, we think it makes the most sense to allow users to update to the newest version, even if they have ignored that version. In this case, the dialog will include text to note that update notifications were disabled for that version.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sharon-wang A few things:
1. Do you know of a way to fake what the newest version is when using a build instead of a development environment?
2. In the dialog, will "Remind Later" remove the `ignoredUpdates` entries and the user will start getting prompted for updates again?

**Comment by sharon-wang** [comment]
> 1. Do you know of a way to fake what the newest version is when using a build instead of a development environment?

I'm not sure how to do this :( I just checked if an older daily considers newer dailies to be updates, but that doesn't appear to be the case.

> 2. In the dialog, will "Remind Later" remove the `ignoredUpdates` entries and the user will start getting prompted for updates again?

Good question. "Remind Later" will not remove the ignored version. We don't currently have a way to remove ignored updates, but in this case, "Remind Later" does not behave as expected.

We can do a couple things here:

- hide "Remind Later" if the user is manually checking for updates and the update is for something they previously ignored
- add functionality to remove the ignored update so that they user is reminded

**Comment by ronblum** [comment]
I think that hiding "remind later" in this case works.

Also, I suggest removing the line telling the user which version is being ignored, but I don't feel remotely strongly about it. 🙂

**Comment by sharon-wang** [comment]
@ronblum I've opened https://github.com/rstudio/rstudio/pull/12903 to hide "Remind Later" in this case.

I kept in the line telling the user which version is being ignored, so that they can reason about why "Remind Later" is hidden, if they're used to seeing that button show up in the dialog. At least I hope it's helpful for a bit of context, as opposed to confusing 😄

**Comment by ronblum** [comment]
Verified using a MacOS 13.2 development builds that trick Mountain Hydrangea into thinking that a newer release is available. I also opened issue #12944 to verify in a production release of Mountain Hydrangea 2023.05.0 once Dessert Sunflower is released.
