### ISSUE TITLE
Copy-paste leads to freezing Rstudio after update on Windows

### ISSUE THREAD

**Issue by kjayhan** [rstudio/rstudio#12879]
After I updated R and Rstudio on my Windows computer, whenever I copy-paste, Rstudio freezes. Otherwise, it works fine.

**Comment by ronblum** [comment]
@kjayhan Thank you for raising this! A few things:
- Do you mean copy and pasting from RStudio or into RStudio?
- Is this in source mode, visual mode, or both?
- Can you provide you environment information?
###

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by veggabo** [comment]
> @kjayhan Thank you for raising this! A few things:
> 
> * Do you mean copy and pasting from RStudio or into RStudio?
> * Is this in source mode, visual mode, or both?
> * Can you provide you environment information?
> 
> ```
> RStudio Edition : 
> RStudio Version : 
> OS Version      : 
> R Version       : 
> ```


I just experienced the same, Rstudio froze when: 

- I copied and then pasted an H2-level heading together with a complete code chunk 
- Inside RStudio in a .qmd-file. 
- In visual mode.
- Froze when I pasted.  

It's still possible to interact with the toolbar and resize the RStudio window, but everything else in the program is unresponsive. 

RStudio Edition: Desktop
RStudio Version: 2023.3.0.386
OS Version: Windows 10 x64, version 21H2 (OS Build 19044.2728)
R Version: 4.2.3 (2023-03-15 ucrt)

**Comment by galenholt** [comment]
Same issue here as soon as I updated Rstudio. The issue seems to be pasting headings plus anything else from a .qmd Visual editor into a .qmd Visual editor- it's happening if I try to paste a heading and code or a heading and text, but does not happen for headings, text, or code alone, or any combination in Source view. 
RStudio Edition : Desktop
RStudio Version : RStudio 2023.03.0+386 
OS Version      :  Windows 11 x64 version 22H2 OS build 22621.1413
R Version       :  4.2.2 (2022-10-31 ucrt)

**Comment by SlavichEve** [comment]
I am also experiencing this. When I am editing a Quarto document in RStudio, my entire RStudio freezes when I try to copy paste as well. I installed R Studio and R only a week ago on this computer, so all the most recent versions.

**Comment by austinwpearce** [comment]
Also experiencing this freezing issue after recent update, and happens only when using the visual editor.

**Comment by kjayhan** [comment]
I think, I realized a similar problem again on my Windows, that when I add a heading with "#" on the visual screen when writing on Quarto, it does not become a heading, but when I go to source screen and come back to visual screen without changing anything, "#" is recognized as a heading.

RStudio edition: desktop
Rstudio version: 2023.03.0+386
OS Version: Windows 11
R Version: Shortstop Beagle, R-4.2.3.

**Comment by galenholt** [comment]
To the question of whether this worked in other versions, I have downgraded to 2022.12.0 353, and do not have the issue anymore. I've never had the issue previously either, and have used most (but not all) other Rstudio versions since the Visual editor was introduced.

**Comment by ronblum** [comment]
Thanks @galenholt! We're actively working on this.

**Comment by ronblum** [comment]
*From issue #12934, paraphrasing report by @VNNikolaidis in order to verify the fix for this as well:*

Create a Quarto document with the following code. Copy the last two lines (from < to >) and paste it below. RStudio IDE freezes.

```
---
title: "01 preprocessing - correlation"
author: "VNN"
format: html
editor: visual
---

\<copy this and the next line:

1.  **mpla mpla** mla:\>
```

**Comment by austinwpearce** [comment]
> To the question of whether this worked in other versions, I have downgraded to 2022.12.0 353, and do not have the issue anymore. I've never had the issue previously either, and have used most (but not all) other Rstudio versions since the Visual editor was introduced.

I also downgraded to 2022.12.0+353, and afterwards, the freezing-after-copy-pasting-while-in-visual-editor problem went away.

(Windows 11 machine)

**Comment by ronblum** [comment]
The bug is fixed in the latest build or an upcoming patch for RStudio 2023.03. [It's build 422 ](https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2023.03.1-422.exe)on the [RStudio dailies page](https://dailies.rstudio.com/). (Tracked in backport issue #12934.)

Please note that the release is still in development. Until we have a fully certified and release, the daily builds are for testing purposes only.

**Comment by kjayhan** [comment]
> As for the main issue (@kjayhan et al), do you know if this worked in previous versions and only popped up in 2023.03.0+386?

Only happened in  2023.03.0+386

**Comment by austinwpearce** [comment]
> The bug is fixed in the latest build or an upcoming patch for RStudio 2023.03. [It's build 422 ](https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2023.03.1-422.exe)on the [RStudio dailies page](https://dailies.rstudio.com/). (Tracked in backport issue #12938.)
> 
> Please note that the release is still in development. Until we have a fully certified and release, the daily builds are for testing purposes only.

The problem no longer occurred for me using the latest daily download (2023.05.0).

Thanks for the patch!

**Comment by ronblum** [comment]
@austinwpearce Thanks for verifying in 2023.05.0! Though I still need to verify it, too—it's only fair. 🙂 

Also, this is an urgent issue, hence including it in #12938 for the upcoming patch release 2023.03.1, curious in furious development. (I can't provide an exact date, though.)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.05.0-daily+212 on Windows 11.

**Comment by siavash-babaei** [comment]
This is really getting on my nerves. Every time I copy/cut+paste in RMarkdown visual mode, RStudio crashes. It doesn't matter if it is a one liner or a large block. RStudio becomes completely non-responsive, and the CPU and RAM usage go through the roof.

R-4.2.3 + RStudio 2023.03.0-386 + Windows 11 x64 (latest updates)
