### ISSUE TITLE
Error in RStudioGD() :    Shadow graphics device error: r error 4 (Error : evaluation nested too deeply: infinite recursion / options(expressions=)

### ISSUE THREAD

**Issue by YangLi-Bio** [rstudio/rstudio#12889]
### System details

    RStudio Edition : 
    RStudio Version : 0.25.0
    OS Version      : RedHat 7.9
    R Version       :  4.2.1

### Steps to reproduce the problem
plot(cars)
### Describe the problem in detail
I cannot generate any plots, because I always get the following error:
Error in RStudioGD() : 
  Shadow graphics device error: r error 4 (Error : evaluation nested too deeply: infinite recursion / options(expressions=)

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
Thank you for bringing up this issue!

Could you please confirm a couple things? This will help me better understand the issue you're having!
1. What is the output of running `RStudio.Version()$long_version` in your RStudio console? 
2. Is there any other output (such as warnings or messages) after `Error in RStudioGD() :
Shadow graphics device error: r error 4 (Error : evaluation nested too deeply: infinite recursion / options(expressions=)`? 

---

Here's something to try as well:

Based on the top solution from [this post](https://stackoverflow.com/questions/19513705/error-in-rstudiogd-shadow-graphics-device-error-r-error-4-r-code-execution), it's possible changing your Graphics backend might resolve the error you're seeing. 

> In R Studio, navigate to Tools, Global, Graphics (top middle), set Backend to AGG*, Apply, Ok

https://user-images.githubusercontent.com/25834218/231284336-46b7e4ac-6b7c-4487-8b5c-09149153102f.mov

**Comment by YangLi-Bio** [comment]
Hi Sharon,

 

I have tried your suggestions and pasted the outputs below:

 

1.             What is the output of running RStudio.Version()$long_version in your RStudio console?

"2022.07.1+554"

2.             Is there any other output (such as warnings or messages) after Error in RStudioGD() : Shadow graphics device error: r error 4 (Error : evaluation nested too deeply: infinite recursion / options(expressions=)?

Error in RStudioGD() : 

  Shadow graphics device error: r error 4 (Error in grSoftVersion() : 

  (converted from warning) unable to load shared object '/apps/R/gnu/11.2/4.2.1/lib64/R/modules//R_X11.so':

  libjpeg.so.9: cannot open shared object file: No such file or directory

)

 

If you demand any other information, please feel free to contact me.

 

Best regards,

**Comment by sharon-wang** [comment]
Thanks for your quick follow-up!

It looks like you might be missing some graphics dependencies.

What is the Terminal output of: `dpkg --get-selections | grep libjpeg`? If the output does not show you have installations of `libjpeg`, perhaps you don't have some necessary dependencies. Did you install dependencies and R using the steps from here: https://docs.posit.co/resources/install-r/?

If the terminal output is not empty (i.e. `libjpeg` is installed on your machine), could you also share the Console output (including any errors or warnings) of:
1. `sessionInfo()`
2. `grSoftVersion()` (get graphics versions)
3. `capabilities()` (check graphics capabilities)
4. `X11.options()` (your last error message includes `R_X11` -- maybe the options will uncover some more information)

**Comment by YangLi-Bio** [comment]
Hi Sharon,

 

Although I have not found the reason, I have fixed this issue by commenting out all lines in my .bash_profile file.

 

Now, this issue is fixed.

 

Thank you!

 

Best regards,

**Comment by YangLi-Bio** [comment]
Thanks!

 

Of course, please close this issue.

**Comment by jayesh1697** [comment]
> Thank you for bringing up this issue!
> 
> Could you please confirm a couple things? This will help me better understand the issue you're having!
> 
> 1. What is the output of running `RStudio.Version()$long_version` in your RStudio console?
> 2. Is there any other output (such as warnings or messages) after `Error in RStudioGD() : Shadow graphics device error: r error 4 (Error : evaluation nested too deeply: infinite recursion / options(expressions=)`?
> 
> Here's something to try as well:
> 
> Based on the top solution from [this post](https://stackoverflow.com/questions/19513705/error-in-rstudiogd-shadow-graphics-device-error-r-error-4-r-code-execution), it's possible changing your Graphics backend might resolve the error you're seeing.
> 
> > In R Studio, navigate to Tools, Global, Graphics (top middle), set Backend to AGG*, Apply, Ok
> 
>  issue_12889.mov



> Thank you for bringing up this issue!
> 
> Could you please confirm a couple things? This will help me better understand the issue you're having!
> 
> 1. What is the output of running `RStudio.Version()$long_version` in your RStudio console?
> 2. Is there any other output (such as warnings or messages) after `Error in RStudioGD() : Shadow graphics device error: r error 4 (Error : evaluation nested too deeply: infinite recursion / options(expressions=)`?
> 
> Here's something to try as well:
> 
> Based on the top solution from [this post](https://stackoverflow.com/questions/19513705/error-in-rstudiogd-shadow-graphics-device-error-r-error-4-r-code-execution), it's possible changing your Graphics backend might resolve the error you're seeing.
> 
> > In R Studio, navigate to Tools, Global, Graphics (top middle), set Backend to AGG*, Apply, Ok
> 
>  issue_12889.mov

thx its works.
