### ISSUE TITLE
Column completions almost unreadable with dark theme when dplyr loaded

### ISSUE THREAD

**Issue by uhkeller** [rstudio/rstudio#12881]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386
    OS Version      : macOS 13.2.1
    R Version       : 4.2.3

### Steps to reproduce the problem

In a new RStudio session using a dark theme (I'm using "Tomorrow Night Bright"), run the following:

```R
library(dplyr)
df1 <- data.frame(a = 1:3)
```

Then type `df1$` on the console. The column completion will show for `df1$a`, but with light grey text on a white background so it's barely readable:

![image](https://user-images.githubusercontent.com/2323704/226867943-1312e426-7acc-4967-84fa-03c96c71e242.png)

### Describe the problem in detail

For some reason, this style of column completion is only used when package dplyr is loaded at the time the object is created. If I don't load dplyr the completion looks like this:

![image](https://user-images.githubusercontent.com/2323704/226868475-f7b2a58a-5552-4bb7-b65c-5fed9bc1e99e.png)

### Describe the behavior you expected

I expected the column completion to be readable.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by lindeloev** [comment]
I can confirm on Rstudio Desktop for Windows 10 Enterprise 22H2.

Bonus info: it's specific to dark themes. White themes look OK. But I guess the appearance should be independent of whether dplyr is loaded.

![image](https://user-images.githubusercontent.com/1439417/227529061-26708c3e-d87d-46e1-a04f-92844cf05aaf.png)

**Comment by dagdrommer** [comment]
+1 for seeing a fix.

Furthermore, I suggest the ability to switch it off, as the colors don't even match most light themes, and it clutters small displays on laptops.

**Comment by ronblum** [comment]
Thank you for raising the issue! I can also reproduce this in the current development build, 2023.05.0-daily+164, on MacOS 13.2. We'll review this as part of our ongoing development of RStudio.

@dagdrommer Regarding turning off the content preview, there's currently only an option to turn off autocompletion altogether. Can you please open a new issue for this enhancement, to selectively turn off only the content preview? Thanks!

**Comment by mikebessuille** [comment]
@romainfrancois we won't have time to look at this in the near term, but if this is broken from code you changed recently, you might want to have a look

**Comment by romainfrancois** [comment]
As in https://github.com/rstudio/rstudio/issues/13097#issuecomment-1545329753 we could either edit the css rules, or disable the feature for now here https://github.com/rstudio/rstudio/blob/afdee25b92abb127646fc345f5be6481ea777a0f/src/cpp/session/modules/SessionHelp.R#L484 as @kevinushey mentioned.

**Comment by sharon-wang** [comment]
@kevinushey any chance this might also be fixed since https://github.com/rstudio/rstudio/issues/13097 was fixed? 😮🤞

**Comment by kevinushey** [comment]
Indeed, this appears to be fixed!

<img width="592" alt="Screenshot 2024-01-23 at 8 12 55 PM" src="https://github.com/rstudio/rstudio/assets/1976582/479bbb09-dd1d-4fd5-b3b8-aa284324ffa6">
