### ISSUE TITLE
RStudio takes a really loooong time to render (through `View()`) an `sf` object

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#12895]
### System details

    RStudio Edition : Desktop
    RStudio Version : "Cherry Blossom" Release (3c53477a, 2023-03-09) for Ubuntu Bionic, Mozilla/5.0 (X11; Linux x86_64)  AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
    OS Version      : Arch Linux, kernel 6.2.8
    R Version       : 4.2.3 (2023-03-15) -- "Shortstop Beagle"

### Steps to reproduce the problem

1. Download a map data set
2. Import that data as an `sf` object
3. Be brave and try to `View()` it!
4. RStudio now takes minutes to show what is essentially a data frame of 357 rows by 19 columns. I can see that RStudio is busy because it is running at 100% in one my vCPUs. Eventually, it finishes.

(Also drawing Edzer's attention: @edzer)

```R
library(sf)

# Downloads a 168.8 MB zip archive
download.file("https://ows.emodnet-seabedhabitats.eu/geoserver/emodnet_open/wfs?request=GetFeature&service=WFS&version=1.1.0&outputFormat=SHAPE-ZIP&typeName=emodnet_open:biogenic_substrate_2021", destfile = "biogenic_substrate_2021.zip")

# Unzip the file to a folder with the same name
unzip("biogenic_substrate_2021.zip", exdir = "biogenic_substrate_2021")

path <- "biogenic_substrate_2021/"
foo <- sf::read_sf(path)

# Watch RStudio taking a loooooong time to show this data frame
# NOTE: the data frame is only 357 rows by 19 columns. I understand
# that the last column `geometry` is the large bit but still I would
# not expect it to take so long to render.
# 
# This also affects how long the R console will take to respond to new commands,
# i.e. it also takes longer. (I think that until the View() finishes running
# everything else gets unresponsive)
View(foo)
```

 `sessionInfo()`'s output:

```R
# `sessionInfo()`'s output
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.11.0
LAPACK: /usr/lib/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_1.0-12

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10        pillar_1.9.0       compiler_4.2.3     profvis_0.3.7      class_7.3-21       tools_4.2.3        digest_0.6.31     
 [8] jsonlite_1.8.4     evaluate_0.20      lifecycle_1.0.3    tibble_3.2.1       pkgconfig_2.0.3    rlang_1.1.0        DBI_1.1.3         
[15] cli_3.6.1          rstudioapi_0.14    yaml_2.3.7         xfun_0.37          fastmap_1.1.1      e1071_1.7-13       knitr_1.42        
[22] dplyr_1.1.1        stringr_1.5.0      generics_0.1.3     vctrs_0.6.1        htmlwidgets_1.6.1  classInt_0.4-9     grid_4.2.3        
[29] tidyselect_1.2.0   glue_1.6.2         R6_2.5.1           fansi_1.0.4        rmarkdown_2.20     magrittr_2.0.3     htmltools_0.5.4   
[36] ellipsis_0.3.2     units_0.8-1        utf8_1.2.3         KernSmooth_2.23-20 proxy_0.4-27       stringi_1.7.12
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by edzer** [comment]
See also https://github.com/r-spatial/sf/issues/1602 and references therein.

**Comment by ronblum** [comment]
@ramiromagno Thank you for raising the issue! I can also reproduce this in 
- RStudio Desktop 2022.07.02 on MacOS 13.2
- RStudio Server 2023.03.0-daily+92 on Ubuntu 20.04 via Chrome on MacOS 13.2

We'll review this as we continue to develop RStudio.

**Comment by FCalderoni** [comment]
Hi, sorry to pop out of the blue but I wanted to note that I am experiencing a similar issue with the View() command for opening basic dataframes and tibbles. 
New workstation, fresh and updated R & RStudio install. Other tasks including loops and simulations are super fast, but View() takes something like 10''...

**Comment by olivroy** [comment]
same issue for me.

I use 

```
dat |> sf::st_drop_geometry() |> View()
```

to make it faster

**Comment by ramiromagno** [comment]
This is still the case with:

RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Focal
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

**Comment by kevinushey** [comment]
@ramiromagno can you please test with the latest daily builds, available at https://dailies.rstudio.com?

**Comment by ramiromagno** [comment]
Hi Kevin (@kevinushey): 

I just tried with 2024.04.0.daily.682. The issue persists.

**Comment by ramiromagno** [comment]
It goes away with `Sys.setenv("LWGEOM_WKT"="true")`, indeed!

It still takes 10 seconds, but it's no longer several minutes.

**Comment by kevinushey** [comment]
Thanks @edzer! Is there anything special RStudio should be doing here when viewing `sf` objects, or is it the user's responsibility to set that environment variable?
