### ISSUE TITLE
Upgrade to non-beta electron-forge for building Electron app

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12904]
We're using an old beta release of `electron-forge` for building. This has been out of beta for a while now (and is an officially supported part of Electron).

https://github.com/rstudio/rstudio/blob/2b0ae91a479b1e7da0e7cf01cba7b462b59d041b/src/node/desktop/package.json#L28-L29

There may be some small breaking changes: see release notes: https://github.com/electron/forge/releases

https://www.electronforge.io/

**Comment by timtmok** [comment]
Implemented here: https://github.com/rstudio/rstudio-pro/issues/5383
