### ISSUE TITLE
Add support for Hippie code completion

### ISSUE THREAD

**Issue by crew102** [rstudio/rstudio#12907]
I'm a big fan of "Hippie" code completion, and I'm wondering if others would find it useful if it were to be included in RStudio. Hippie completion restricts suggestions to just those words/tokens that exist in the active source file, which can limit the size of the suggestion list and hence speed up the completion experience.

Relevant links:

  * Description of the feature from PyCharm: https://www.jetbrains.com/help/pycharm/auto-completing-code.html#hippie_completion.
  * Description of how it works for Emacs, for which it was originally developed: https://www.emacswiki.org/emacs/HippieExpand.
  * My recent Addin-based implementation of Hippie for RStudio: https://github.com/crew102/hippie.
  
It may make sense to just leave this as an Addin option, as Addins seem to be intended for just this kind of thing, but I thought a broader integration into the RStudio was worth exploring. I'd be happy to take a shot at a PR if you think Hippie has a place in the IDE.

Related issues:

* https://github.com/ropensci/unconf18/issues/65
* https://github.com/ropensci/unconf17/issues/52#issuecomment-723090987

Loving the completion improvements in Cherry Blossom by the way.

**Comment by ronblum** [comment]
@crew102 Thank you for the suggestion, and cool that you created the addin! If you'd also like to create a PR to add it as a feature, go for it, and we'll review it. And I'm glad that you're enjoying the improvements!
