### ISSUE TITLE
When characters in columns are selected by holding ALT & drag, new text cannot be input.

### ISSUE THREAD

**Issue by psychbruce** [rstudio/rstudio#12906]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0-386
    OS Version      : Windows 11
    R Version       : 4.2.2

### Steps to reproduce the problem

In an R or Rmd script, when characters in columns (_m_ rows * _n_ columns) are selected by using **ALT** and drag, new text cannot be input to replace the old one through keyboard typing, although with the right click I can "Copy" and "Paste".

![image](https://user-images.githubusercontent.com/34391475/227667101-02300b26-c3e6-4990-9842-8f3688d97914.png)

### Describe the problem in detail

This bug did not exist in RStudio 2022.07.2-576 or earlier, but has existed since 2022.12.

### Describe the behavior you expected

Fix this bug to allow typing new text to replace old code when it is selected in columns with ALT.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
Thank you for opening this issue @psychbruce!

This sounds similar to other source editor alt+select or alt+drag bugs that have been reported. I've added this issue to the Epic where we're tracking these.
