### ISSUE TITLE
Color matching issue of rainbow fenced divs after content edits

### ISSUE THREAD

**Issue by zekiakyol** [rstudio/rstudio#12919]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0 and 2023.06.2+561
    OS Version      : Windows 10 - 22H2
    R Version       : 4.2.3

### Steps to reproduce the problem

---
> **Note**
> The following gif uses "Monokai" editor theme to see colors easier, but the issue also exists in the default theme editor. This color matching problem has no effect functionality of the code.

Following steps create this gif:

![issue](https://user-images.githubusercontent.com/40212849/228210148-0774f4bf-de43-483b-af1a-93432aa8f0da.gif)
---

**Step 1:** Create a .qmd file with following code**
```
---
title: "Untitled"
format: html
---

::: {.callout-tip title="Tip with Title1"}
This is a callout with a title.
:::
```

**Step 2:** Copy and paste existing fenced div and rename its title as `Title1` to `Title2`
```
---
title: "Untitled"
format: html
---

::: {.callout-tip title="Tip with Title1"}
This is a callout with a title.
:::

::: {.callout-tip title="Tip with Title2"}
This is a callout with a title.
:::
```

**Step 3:** Add a random text to the second fenced div, say letter `A`. One second after the edit, the last `:::` changes to a different color that does not match.
```
---
title: "Untitled"
format: html
---

::: {.callout-tip title="Tip with Title1"}
This is a callout with a title.
:::

::: {.callout-tip title="Tip with Title2"}
This is a callout with a title.A
:::
```

**Step 4:** When we delete all the content of second fenced div, color matches again.
```
---
title: "Untitled"
format: html
---

::: {.callout-tip title="Tip with Title1"}
This is a callout with a title.
:::

::: {.callout-tip title="Tip with Title2"}
:::
```

**Step 5:** (Again) Add a random text to the second fenced div, say letter `A`. One second after the edit, the last `:::` changes to a different color that does not match.
```
---
title: "Untitled"
format: html
---

::: {.callout-tip title="Tip with Title1"}
This is a callout with a title.
:::

::: {.callout-tip title="Tip with Title2"}
A
:::
```

### Describe the problem in detail

The color of the second fenced div `:::` does not match after the content edit, i.e. adding letter `A`.

### Describe the behavior you expected

The color of each fenced div should match both before and after the edit of the content.

---

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@zekiakyol Thank you for raising this! I can reproduce the issue in RStudio Desktop 2023.03.0+386 and 2022.05.0-daily+158 on MacOS 13.2. The same occurs if you keep adding fenced divs—the closing `:::` always changes to the color of the first div. We'll review this as we continue development of RStudio.
