### ISSUE TITLE
Electron unit tests not running on Windows build pipeline

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#12910]
The electron unit tests failed on Windows builds (back in March 2023), so we commented them out to get builds.

https://github.com/rstudio/rstudio/commit/d045d2fe34bc150493ae5d62098df8ff00b5d42b

This issue tracks figuring out why they didn't work and reenabling them.

It's possible they simply can't be made to work in a Windows docker container; on Linux we rely on `xvfb-run` so would likely need something similar for Windows in order to run headless.

**Comment by mikebessuille** [comment]
@timtmok @cm421 is this super simple to fix?  Seems to me that any unit test failure should fail the build.

**Comment by kevinushey** [comment]
Are builds with failing unit tests still published somewhere (either as dailies or hourlies)?

**Comment by timtmok** [comment]
I think this should be easy to add back in. It looks like it was removed during the refactoring to matrix builds.
