### ISSUE TITLE
can't select version of R when only one version installed

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#12916]
@kevinushey here's the screenshot. Sorry for the confusion, I meant the "Ok" button is grayed out.

![image](https://user-images.githubusercontent.com/16002036/228069180-725fbc76-4317-49f3-bb6a-95286b36b1ad.png)

EDIT: just downloaded a different R version to check if it might be related to the number of version in the list and yep!

![image](https://user-images.githubusercontent.com/16002036/228069867-1c2be853-a819-4a44-99f3-5720919d6988.png)

**I closed and reopened the cmd prompt and started rstudio without any additional environment variables and it works now!**

_Originally posted by @ctm22396 in https://github.com/rstudio/rstudio/issues/12452#issuecomment-1485878161_

**Comment by gtritchie** [comment]
Also noticed another quirk we should investigate and fix as part of this.

On my Windows developer machine, where I have R 3.6.3 installed into C:\R\R-3.6.3 and no other versions of R at the moment, Qt Desktop (2022.07) shows this, note the radio buttons for "machine's default version" are enabled. There's also a duplicate set of entries in the list below (same paths shown with long and short pathnames) but Electron appears to avoid this problem.

![Screenshot of Choose R dialog from Qt RStudio](https://user-images.githubusercontent.com/10569626/228651419-f736d72c-9887-4272-a06e-4da75777b52a.png)

With Electron build 2023.05.0-hourly+163, the radio buttons are disabled.

![Screenshot of Chooose R dialog in Electron](https://user-images.githubusercontent.com/10569626/228651877-d79e8a78-60a9-4ff0-8ab2-e43451d02fbb.png)

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2023.05.0-daily+206
Windows 11, MacOS 12.6

Tested with only one version of R installed (but with several different versions) and it behaved as expected.
