### ISSUE TITLE
Massive slowdown with Notebooks using nested tibbles

### ISSUE THREAD

**Issue by jonasfoe** [rstudio/rstudio#12923]
### System details

    RStudio Edition : 
    RStudio Version : 2023.03.0 Build 386
    OS Version      : Windows 10
    R Version       : 4.2.3

### Steps to reproduce the problem
Run the following code in a Notebook file (.Rmd, .qmd) in RStudio
```
library(tibble)
library(tidyr)
cars_tibble <- as_tibble(cars)
df_nested <- tibble(id = 1:1e6, nested = replicate(1e6, list(cars_tibble)))
df_renested <- df_nested %>% unnest(nested) %>% nest(nested = -id)
```
### Describe the problem in detail
I have finally found a way to reproduce the performance problem that has been crushing my productivity with RStudio for the past months. My sessions regularly slow down to evaluate no more than one line per second.
See the attached screenshot for an illustration with the supplied code:
![rstudio_slowdown_nested_tibbles](https://user-images.githubusercontent.com/9588/228309191-ed330b09-ce05-401c-9619-0a1ed6e13c95.png)
I am benchmarking chunks with tic, toc to show that once df_renested exists, RStudio fails to execute chunks in any reasonable amount of time.
In principle, df_renested should be the same as df_nested but df_nested causes no issues.
Once df_renested exists, I can watch RStudio submit line by line to the R Console at an absolute crawl.

### Describe the behavior you expected
While large dataframes may in some cases hamper performance, I don't believe it should be possible to cause such performance issues when executing unrelated chunks of code, that R has no problem evaluating in milliseconds.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report; I was able to reproduce with the following script (copying from your example)

`````
```{r}
library(tibble)
library(tidyr)
cars_tibble <- as_tibble(cars)
df_nested <- tibble(id = 1:1e6, nested = replicate(1e6, list(cars_tibble)))
df_renested <- df_nested %>% unnest(nested) %>% nest(nested = -id)
```

```{r}
library(tictoc)
profile <- tempfile()
Rprof(profile)
tic()
{
  invisible()
  invisible()
  invisible()
}
toc()
Rprof(NULL)
summaryRprof(profile)
```
`````

It appears we're spending most of our time recursively crawling that object for external pointers:

<img width="1572" alt="Screenshot 2023-03-28 at 11 17 08 AM" src="https://user-images.githubusercontent.com/1976582/228331039-89a405d4-9fde-4744-b054-d23b83210e16.png">

The simplest fix would probably be to memoize the results here, for objects that we know haven't changed.

cc: @romainfrancois

**Comment by kevinushey** [comment]
I also have a feeling that we want to stop using `std::set` and instead use `std::unordered_set` or even a Boost equivalent.

https://github.com/rstudio/rstudio/blob/380840fe0f97afda0bb1e6e1167d50ea1509304e/src/cpp/session/modules/environment/EnvironmentUtils.cpp#L138-L139

(+ other usages of `std::set` in SessionEnvironment.cpp)

**Comment by jonasfoe** [comment]
Thanks for picking this up so swiftly! That's very encouraging.
Let me know if this indicates any kind of viable workaround until an eventual fix is implemented.

**Comment by mikebessuille** [comment]
@romainfrancois do you think you have time to fix this in the next couple of weeks?

**Comment by timtmok** [comment]
@kevinushey Is this resolved by your PR?

**Comment by kevinushey** [comment]
Indeed it is; this should be ready for testing. (I verified locally that everything looks good in +293)

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2023.05.0-daily+296 on MacOS 13.4
- RStudio Server 2023.05.0-daily+296 on Ubuntu 20.04.5 via Chrome on MaOS 13.4.
