### ISSUE TITLE
Can't save to scripts to UNC path from RStudio 2023.03.0

### ISSUE THREAD

**Issue by tg-nwf** [rstudio/rstudio#12935]
I'm getting a 'network name cannot be found' message when I try to save R scripts to UNC paths within RStudio.

For example, when saving a script called foo.R containing the single line print('Hello World!') to UNC path \\my_host\my_share\my_project_directory\foo.R, I might get a message that says: "Error saving /my_host/my_share/my_project_directory/foo.R. The network name cannot be found".

This error _**does not occur**_ when I try to save this same script from R (i.e. RGui).

It happens intermittently in RStudio, but frequently enough to be a real problem. The error started happening when I upgraded to RStudio version 2022.12 and continues to happen with version 2023.03.0 Build 386.

**Comment by gabowi** [comment]
We have the same problem here. It is quite annoying. Saving a file on a local path, moving it to a network folder, opening it from there and saving it works. But **saving a new R file from R studio on a network folder is not possible**. Also, using "Save as" the same problem occurs.

[Window Title] Error Saving File
[Content] Error saving /somecomputer/someshare/test.R: Das System kann den angegebenen Pfad nicht finden
(Translation: The system cannot find the specified path)

Remarkably, the second slash at the beginning is missing from the directory in the error message. Therefore, I assume the file path handling is implemented incorrectly.

**Comment by gtritchie** [comment]
I have reproduced this and will take a look.

**Comment by sharon-wang** [comment]
Possibly related: https://github.com/rstudio/rstudio/issues/12652

**Comment by gtritchie** [comment]
Closing this as a dupicate of #12652.
