### ISSUE TITLE
Make the 'Go to file/function' search more flexible

### ISSUE THREAD

**Issue by Moohan** [rstudio/rstudio#12931]
Often when I'm reviewing a PR from GitHub I'll want to swap between GitHub and the checked-out code in RStudio. When reviewing on the 'Files changed' tab in GitHub it is very simple to copy the relative path of the file you're looking at (single click copy). This path will be something like `R/foo_bar.R` in a package or `code/functions/foo_bar.R` etc.

The 'Go to file/function' search would find the correct file in both cases if you used `foo_bar` or `foo_bar.R` but not the copied file path `R/foo_bar.R`.

Could 'Go to file/function' be modified to *also* search for relative file paths?

I could imagine other situations where this would be useful, for example if a project had multiple similarly named files / functions, and including (part of) the path would more easily narrow it down.

**Comment by ronblum** [comment]
@Moohan Thank you for the suggestion! We'll review it as we consider enhancement to RStudio features.
