### ISSUE TITLE
Backport #12879 to Cherry Blossom <2023.03.1>

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#12938]
Backport #12879 to Cherry Blossom <2023.03.1>.

**Note: This issue is to record the need to backport the linked issue only. Please add comments or discussion relating to the original issue onto it directly.**

**Comment by ronblum** [comment]
Confirmed fixed in RStudio Desktop 2023.03.1+422 on Windows 10. Verified using both R Markdown and Quarto documents.
