### ISSUE TITLE
mouse back / forward buttons always navigate Help pane, even when not focused

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#12932]
### System details

    RStudio Edition : 2023.03.999-dev+999
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Ventura 13.2.1
    R Version       : R version 4.2.3 (2023-03-15)

### Steps to reproduce the problem

Run some help commands to build the Help pane with some history, e.g.

```
help(rnorm)
help(stats)
```

Then, try pressing the mouse back + forward buttons somewhere in the IDE surface (not targeting help).

### Describe the problem in detail

The Help pane navigates.

### Describe the behavior you expected

The Help pane should only navigate if the mouse was within the bounds of the Help iframe.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.3 (2023-03-15)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.3    ragg_1.2.5        tools_4.2.3       rstudioapi_0.14  
[5] textshaping_0.3.6 systemfonts_1.0.4
```

</details>

**Comment by ronblum** [comment]
Note: This works correctly with the touchpad.

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2023.05.0-daily+180
Windows 11, Ubuntu22

Mouse forward/back buttons worked as expected on Source pane with multiple tabs open, as well as in Help pane for several different packages.
