### ISSUE TITLE
Add ability to type a path in "create project as a subdirectory of:"

### ISSUE THREAD

**Issue by joeroe** [rstudio/rstudio#12930]
When creating a new project, the text input labelled "create project as a subdirectory of" is disabled and can only be changed through the "Browse..." dialog. But if I already know the path I want, I don't need to browse for it, and it would be quicker and easier to just type it in.

**Comment by ronblum** [comment]
@joeroe Thanks for the suggestion! We'll review it as we continue to develop RStudio.
