### ISSUE TITLE
Failure to render development documentation in R 4.3.0 alpha

### ISSUE THREAD

**Issue by pbreheny** [rstudio/rstudio#12945]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0 Build 386
    OS Version      : Ubuntu 20.04.6 LTS
    R Version       : 4.3.0 alpha (2023-03-27 r84084)

### Steps to reproduce the problem

Load the source for any package with `pkgload::load_all()` or `devtools::load_all()`, then request the help file for a documented function in that package (e.g., `?make_graph`).

### Describe the problem in detail

The console displays

```
Rendering development documentation for "make_graph"
```

as usual, but the help panel displays

```
Error in .get_package_metadata(pkgdir) : Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.
```

I have tried this on three different packages, same thing happens every time.

### Describe the behavior you expected

This has always worked in the past, displaying the development documentation. I only saw this problem after upgrading to R 4.3.0 alpha and RStudio 2023.03.0. It seems to be an RStudio issue, because it works fine if I open R itself outside of RStudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Seems like a devtools issue rather than an RStudio issue?

**Comment by pbreheny** [comment]
Perhaps, although as I said above, the issue does not arise when opening R directly (outside of RStudio). The development documentation opens fine in that case (text and html), which is why I opened the issue here rather than with with devtools/pkgload. I could open an issue there as well, I suppose?

**Comment by ronblum** [comment]
@pbreheny Not speaking directly on behalf of @kevinushey (he understand this far more than I do), but I'd suggest [opening an issue in the devtools repo](https://github.com/r-lib/devtools/issues) and linking to this issue—it won't hurt.

**Comment by ronblum** [comment]
@pbreheny Did you by chance file an issue for devtools, and if so, can you provide a link for it? Thanks!

**Comment by pbreheny** [comment]
Well, `devtools::load_all()` is just a wrapper for `pkgload::load_all()`. I suppose I could file an issue there, but I don't see how **devtools** can do anything about it; the problem would need to be fixed on the **pkgload** side (or the RStudio side).

```r
> packageVersion('devtools')
[1] ‘2.4.5’
> packageVersion('pkgload')
[1] ‘1.3.2’
```

**Comment by jonvanausdeln** [comment]
With release of R 4.3.0, we now see this in our automated tests as well.  Here is another reprex

1. Create an RDocumentation doc. `.rs.api.executeCommand('newRDocumentationDoc')`
2. Save document
3. Preview HTML - either api call or the "Preview" button

Results in same error.

_note for QA: RDocumentation test was disabled due to this issue, should be turned back on when fixed._

**Comment by ronblum** [comment]
Note: The issue occurs even with `devtools` remove.

**Comment by lionel-** [comment]
I'm seeing this backtrace which suggests this is an RStudio issue:

```
traceback()
#> 5: stop("Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.")
#> 4: .get_package_metadata(pkgdir)
#> 3: tools::loadPkgRdMacros(file.path(R.home("share"), "Rd", "macros",
#>        "system.Rd"), macros = macros)
#> 2: .rs.RdLoadMacros(file)
#> 1: .rs.Rd2HTML("/Users/lionel/Sync/Projects/R/r-lib/pkgload/man/load_all.Rd",
#>        "pkgload")
```

It looks like this is from https://github.com/r-devel/r-svn/commit/25f168af00e723bc4eb2d43501e79250cda28ae1 which now fails when a `DESCRIPTION` file is absent. The call to `tools::loadPkgRdMacros()` was added to RStudio in https://github.com/rstudio/rstudio/pull/12111

**Comment by kevinushey** [comment]
I'll take a look.

**Comment by dmurdoch** [comment]
I saw this with the Preview button on an Rd file; the nightly 2023.05.0 Build 320 has it fixed. Thanks!

**Comment by ronblum** [comment]
This now works inside of a package. However,, outside of a package, creating a standalone R Documentation file and previewing it still results in an error.

**Comment by kevinushey** [comment]
@ronblum I wasn't able to reproduce; can you elaborate on the steps you're taking?

**Comment by ronblum** [comment]
@kevinushey This is with creating a new document using the API or GUI:
1. <kbd>File -> New File -> R Documentation</kbd> or `.rs.api.executeCommand('newRDocumentationDoc')`
2. Save the file.
3. <kbd>Preview</kbd>

<img width="792" alt="document" src="https://user-images.githubusercontent.com/31009952/236315164-297d70e0-0477-4864-ab1b-bf4248aca29e.png">

I can open a separate issue if you think this is a different problem (with similar output).

**Comment by dmurdoch** [comment]
I can confirm this also happens here.  The key is to create this file someplace unrelated to a package.

**Comment by kevinushey** [comment]
Thanks! I can reproduce now. I think the two key things I was missing was:

- You need to have a (package) project open in RStudio;
- You need to be editing and previewing a `.Rd` file that lives outside of the current project.

**Comment by kevinushey** [comment]
(more generally, it looks like the issue could occur for any `.Rd` file that didn't live as part of a package's `man/` directory)

**Comment by jonvanausdeln** [comment]
@kevinushey , with that [commit ](https://github.com/rstudio/rstudio/commit/a4224d81afee061a484815be7f8630d518870849), is this issue now ready for test?

**Comment by jonvanausdeln** [comment]
Verified on 2023.05.0-daily+333 Desktop
Windows 11, Ubuntu22

Previews now render

**Comment by trinetra75** [comment]
Is there any plan to back-port this fix also to Cherry-Blossom?

**Comment by jonvanausdeln** [comment]
@trinetra75 , There is not another Cherry-Blossom patch planned at this time. I can add this to list of potential backport issues.

**Comment by trinetra75** [comment]
> @trinetra75 , There is not another Cherry-Blossom patch planned at this time. I can add this to list of potential backport issues.

Well I'm developing a package and not being able to preview the man pages does not help...

Also I would like to avoid to install a non-stable build, so if next 'Mountain-Hydrangea' stable release is not too far in the future there is no need, otherwise it would be good to have this fixed also in 'Cherry-Blossom'...

Thanks

**Comment by jonvanausdeln** [comment]
@trinetra75 , I completely understand your dilemma. Mountain Hydrangea is targeted to release end of May, While I can't guarantee a release date, we are fairly confident.

**Comment by trinetra75** [comment]
That is enough for me: I can easily wait the 2/3 weeks to the new release...

Thanks for the prompt answers!

**Comment by dmurdoch** [comment]
I think I am misunderstanding the issue.  I only saw the problem when the .Rd file wasn't in the man directory of a package.  Is there some other issue as well?  Otherwise the simple workaround is to put it in the man directory.  If there's some reason it can't go in the package you are developing, make a dummy package with a man directory.

**Comment by JosiahParry** [comment]
@dmurdoch the only alternative is to _not_ view __development__ documentation but instead install the package which is an cumbsersome alternative when actively developing a package

**Comment by dmurdoch** [comment]
That's not what I'm seeing.  I normally edit each Rd file directly, and when I want to see how it looks, I hit Preview.  That has always worked for me.  What wasn't working was when the .Rd file was in some other unrelated directory, because the code wanted to look at the DESCRIPTION file or something else in the parent directory, and failed if it wasn't there.  That's been fixed in #12945.

If you're using Roxygen, I think you've always had to do the same thing:  process the .R files to produce the .Rd, then hit Preview on the .Rd file.

So it sounds as though you are seeing a different bug than I was seeing.

**Comment by trinetra75** [comment]
The only partial workaround that I know of, is to open a straight `R` session in a terminal and there use the normal `?` command...

**Comment by kevinushey** [comment]
@JosiahParry: is installing a [daily build](https://dailies.rstudio.com) an option?

**Comment by dBenedek** [comment]
I have the same issue: `Error in .get_package_metadata(pkgdir) : 
  Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.` in RStudio. Interestingly, in the command line after running R, I don't get such an error message, the function description appears.
