### ISSUE TITLE
Retest issue 12874 (Can't check for updated releases)

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12944]
Issue #12874 was verified in Mountain Hydrangea using a development build with faking RStudio into thinking that there was a more recent release. Retest using a Mountain Hydrangea 2023.03.x release once Dessert Sunflower is released to verify using a production build.

**Comment by jonvanausdeln** [comment]
Closing as I added this to the Desert Sunflower post-release checklist.
