### ISSUE TITLE
Emacs keybindings: Copy with Alt-w not working

### ISSUE THREAD

**Issue by lynchs61** [rstudio/rstudio#12957]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0-386
    OS Version      : MacOS Ventura 13.2.1
    R Version       : 4.2.3

### Steps to reproduce the problem
Install new copy of RStudio. Set keybindings to Emacs. Highlight a line and copy with Alt-w. Then try to paste and see that what you think you just copied isn't in the clipboard (or kill-ring).

### Describe the problem in detail
Emacs keybindings aren't working as expected. I would expect after changing to emacs keybindings, that commad-c and command-v (ctrl-c and ctrl-v on Windows and Linux) don't work anymore. But they still do. I can see that some emacs keybindings work correctly - like ctrl-w to cut - but not all.

### Describe the behavior you expected
I expect that if I switch to emacs keybindings, the default keybindings would go away and be replaced by the emacs keybindings. But this is not the case. In at least one instance with alt-w for copy, the emacs keybinding doesn't work. I can also still use the default keybindings for cut, copy, and paste but I'd think they should cease to work if I set keybindings to Emacs.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by lynchs61** [comment]
In addition... I thought that I could fix this Alt-w copy behavior by setting it correctly in the "Modify Keyboard Shortcuts" section of the preferences. But I don't see it in the list of keyboard shortcuts.

**Comment by mihem** [comment]
probably related to my open issue https://github.com/rstudio/rstudio/issues/12815
