### ISSUE TITLE
Add Code Tools button to .rmd and .qmd documents

### ISSUE THREAD

**Issue by WilDoane** [rstudio/rstudio#12954]
Version 2023.05.0-daily+191 (2023.05.0-daily+191)

The Code Tools button present when editing .R scripts should also be available in .rmd and .qmd documents, at least when the insertion point is inside an R code block.

**Comment by ronblum** [comment]
@WilDoane This is a fair point—thank you for the suggestion!

**Comment by jellocube** [comment]
Hello, M. Shelley here, not seeing Will Doane’s update on my fork. Safety hazard needing additional aid I assume, from personal experience with this kind of code golf.

**Comment by ronblum** [comment]
@jellocube This wasn't a code change by @WilDoane—it's an enhancement request.
