### ISSUE TITLE
Starting line with hashtag and space doesn't create a header in visual mode

### ISSUE THREAD

**Issue by kjayhan** [rstudio/rstudio#12951]
When I add a heading with "#" on the visual screen when writing on Quarto, it does not become a heading, but when I go to source screen and come back to visual screen without changing anything, "#" is recognized as a heading.

This issue was not there in previous versions.

RStudio edition: desktop
Rstudio version: 2023.03.0+386
OS Version: Windows 11
R Version: Shortstop Beagle, R-4.2.3.

**Comment by ronblum** [comment]
@kjayhan Are you typing a space after the <kbd>#</kbd> character? That should trigger a header.

**Comment by kjayhan** [comment]
Yes, of course.

**Comment by ronblum** [comment]
@kjayhan Thanks! Do you know if this worked in previous versions for RStudio Desktop?

@timtmok I can't reproduce the issue—this is working for me on Windows 11. Do you have any suggestions of what to look at to investigate?

**Comment by kjayhan** [comment]
> @kjayhan Thanks! Do you know if this worked in previous versions for RStudio Desktop?


No, this issue appeared only for 2023.03.0+386. I didn't have a chance to use my Windows, so I couldn't check if this issue persists (I upgraded RStudio in the meantime).

**Comment by kjayhan** [comment]
I am still on the same Rstudio version ("Cherry Blossom" Release (3c53477a, 2023-03-09) for Windows). But the issue does not seem to happen any more.

**Comment by timtmok** [comment]
If it happens again, using the latest daily build would help confirm if it's still an issue. The visual editor has had a lot of changes and currently the daily build will update it to the latest available from quarto-dev/quarto.
