### ISSUE TITLE
Rstudio-ERROR system error 84

### ISSUE THREAD

**Issue by hahahaL** [rstudio/rstudio#12955]
### System details

    RStudio Edition : win-client
    RStudio Version : 2022.02.2+485 (Prairie Trillium)
    OS Version      : Linux 
    R Version       : 3.6

### Steps to reproduce the problem
log-message-system-error-84
### Describe the problem in detail
ERROR system error 84 (Invalid or incomplete multibyte or wide character) [str: 一, len: 9, from: UTF-8, to: ISO8859-1]; OCCURRED AT rstudio::core::Error rstudio::r::util::{anonymous}::iconvstrImpl(const string&, const string&, const string&, bool, std::string*) src/cpp/r/RUtil.cpp:187; LOGGED FROM: rstudio::core::Error rstudio::session::modules::spelling::{anonymous}::checkSpelling(const rstudio::core::json::JsonRpcRequest&, rstudio::core::json::JsonRpcResponse*) src/cpp/session/modules/SessionSpelling.cpp:225

**Comment by ronblum** [comment]
@hahahaL Thanks for bringing the issue over!
1) Are you using RStudio Desktop or RStudio Server?
2) I'm not sure that I understand your configuration. Are you using RStudio Desktop using a Linux VM on a Windows box, or using VNC to access RStudio Desktop on Linux from a Windows machine, or connecting from Windows via a web browser to RStudio Server? Etc.
3) What flavor and version of Windows and Linux are you using?

**Comment by hahahaL** [comment]
> @hahahaL Thanks for bringing the issue over!
> 
> 1. When does the error occur?
> 2. Are you using RStudio Desktop or RStudio Server?
> 3. I'm not sure that I understand your configuration. Are you using RStudio Desktop using a Linux VM on a Windows box, or using VNC to access RStudio Desktop on Linux from a Windows machine, or connecting from Windows via a web browser to RStudio Server? Etc.
> 4. What flavor and version of Windows and Linux are you using?
---------------------------------------------------------------
Sorry for the late reply 
My run-env:
> 1. When running Rstudio application through chroe browser
> 2. Use RStudio Server
> 3. Use Linux to run the RStudio-Server,run the appli throug the browser
> 4. C/S
     C: win10 chrome:110.0.5481.178
     S: 2022.02.2+485 (Prairie Trillium) for CentOS 7

**Comment by mbojan** [comment]
RStudio crashed on me on xUbuntu 22.04 and I'm seeing identical errors in my `syslog`. Session info folded below.

```
Apr 16 14:15:14 carbon rsession-mbojan[25171]: ERROR system error 84 (Invalid or incomplete multibyte or wide character) [str: zajęciach, len: 10, from: UTF-8, to: ISO8859-1]; OCCURRED AT rstudio::core::Error rstudio::r::util::{anonymous}::iconvstrImpl(const string&, const string&, const string&, bool, std::string*) src/cpp/r/RUtil.cpp:268; LOGGED FROM: rstudio::core::Error rstudio::session::modules::spelling::{anonymous}::checkSpelling(const rstudio::core::json::JsonRpcRequest&, rstudio::core::json::JsonRpcResponse*) src/cpp/session/modules/SessionSpelling.cpp:225
Apr 16 14:15:14 carbon rsession-mbojan[25171]: ERROR system error 84 (Invalid or incomplete multibyte or wide character) [str: zajęciach, len: 10, from: UTF-8, to: ISO8859-1]; OCCURRED AT rstudio::core::Error rstudio::r::util::{anonymous}::iconvstrImpl(const string&, const string&, const string&, bool, std::string*) src/cpp/r/RUtil.cpp:268; LOGGED FROM: rstudio::core::Error rstudio::session::modules::spelling::{anonymous}::checkSpelling(const rstudio::core::json::JsonRpcRequest&, rstudio::core::json::JsonRpcResponse*) src/cpp/session/modules/SessionSpelling.cpp:225
```

<details>
<summary>Session info</summary>

      ─ Session info ───────────────────────────────────────────────────────────────────────────────────
       setting  value
       version  R version 4.2.3 (2023-03-15)
       os       Ubuntu 22.04.2 LTS
       system   x86_64, linux-gnu
       ui       RStudio
       language en
       collate  en_US.UTF-8
       ctype    en_US.UTF-8
       tz       Europe/Warsaw
       date     2023-04-16
       rstudio  2023.03.0+386 Cherry Blossom (desktop)
       pandoc   2.9.2.1 @ /usr/bin/pandoc
      
      ─ Packages ───────────────────────────────────────────────────────────────────────────────────────
       package     * version date (UTC) lib source
       callr         3.7.3   2022-11-02 [1] CRAN (R 4.2.3)
       cli           3.6.1   2023-03-23 [1] CRAN (R 4.2.3)
       clipboard     0.0-1   2023-04-16 [1] Github (mbojan/clipboard@69b1b7c)
       colorspace    2.1-0   2023-01-23 [1] CRAN (R 4.2.3)
       crayon        1.5.2   2022-09-29 [1] CRAN (R 4.2.3)
       curl          5.0.0   2023-01-12 [1] CRAN (R 4.2.3)
       desc          1.4.2   2022-09-08 [1] CRAN (R 4.2.3)
       dplyr         1.1.1   2023-03-22 [1] CRAN (R 4.2.3)
       fansi         1.0.4   2023-01-22 [1] CRAN (R 4.2.3)
       farver        2.1.1   2022-07-06 [1] CRAN (R 4.2.3)
       generics      0.1.3   2022-07-05 [1] CRAN (R 4.2.3)
       gganimate     1.0.8   2022-09-08 [1] CRAN (R 4.2.3)
       ggplot2       3.4.2   2023-04-03 [1] CRAN (R 4.2.3)
       gifski        1.6.6-1 2022-04-05 [1] CRAN (R 4.2.3)
       glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.3)
       gtable        0.3.3   2023-03-21 [1] CRAN (R 4.2.3)
       hms           1.1.3   2023-03-21 [1] CRAN (R 4.2.3)
       lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.3)
       magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.3)
       mbtools       0.3-0   2023-03-28 [1] Github (mbojan/mbtools@ed7680f)
       munsell       0.5.0   2018-06-12 [1] CRAN (R 4.2.3)
       pillar        1.9.0   2023-03-22 [1] CRAN (R 4.2.3)
       pkgbuild      1.4.0   2022-11-27 [1] CRAN (R 4.2.3)
       pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.3)
       prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.3)
       processx      3.8.0   2022-10-26 [1] CRAN (R 4.2.3)
       progress      1.2.2   2019-05-16 [1] CRAN (R 4.2.3)
       ps            1.7.4   2023-04-02 [1] CRAN (R 4.2.3)
       R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.3)
       remotes     * 2.4.2   2021-11-30 [1] CRAN (R 4.2.3)
       rlang         1.1.0   2023-03-14 [1] CRAN (R 4.2.3)
       rprojroot     2.0.3   2022-04-02 [1] CRAN (R 4.2.3)
       rsconnect     0.8.29  2023-01-09 [1] CRAN (R 4.2.3)
       rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.3)
       scales        1.2.1   2022-08-20 [1] CRAN (R 4.2.3)
       sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.3)
       stringi       1.7.12  2023-01-11 [1] CRAN (R 4.2.3)
       tibble        3.2.1   2023-03-20 [1] CRAN (R 4.2.3)
       tidyselect    1.2.0   2022-10-10 [1] CRAN (R 4.2.3)
       tweenr        2.0.2   2022-09-06 [1] CRAN (R 4.2.3)
       utf8          1.2.3   2023-01-31 [1] CRAN (R 4.2.3)
       vctrs         0.6.1   2023-03-22 [1] CRAN (R 4.2.3)
       withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.3)
      
       [1] /home/mbojan/R/library/4.2
       [2] /usr/local/lib/R/site-library
       [3] /usr/lib/R/site-library
       [4] /usr/lib/R/library
      
      ──────────────────────────────────────────────────────────────────────────────────────────────────

</details>

**Comment by hahahaL** [comment]
Hi,mbojan
This information doesn't affect me to get the correct result,but I'm afraid this error message will cause other unknown errors.
I don't know if your error has any effect on the correctness of the result

**Comment by luisvalenzuelar** [comment]
This error affects me (Ubuntu 22.04, RStudio 23.12.0). It seems to happen when trying to create a very large database. I managed to avoid the error by disabling real-time spelling check, as suggested [here](https://community.rstudio.com/t/r4-1-0-and-rsession-rstudio-system-error-13-84-invalid-or-incomplete-multibyte-or-wide-character/107645/4). 
Is this related to using UTF-8 scripts, due to special characters? (in my case, Spanish)
