### ISSUE TITLE
Allow to escape a semicolon inside citation in visual mode

### ISSUE THREAD

**Issue by netique** [rstudio/rstudio#12952]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.05.0-daily+177 Mountain Hydrangea (desktop)
    OS Version      : macOS Ventura 13.3
    R Version       : R version 4.2.3 (2023-03-15)

### Steps to reproduce the problem

In source editor mode, write a parenthetical citation entry with preceding text containing an escaped semicolon (see https://github.com/jgm/pandoc-citeproc/issues/271) such as

`[Lorem Ipsum Dolor, LID\; @article2023]`.

Switch to visual mode and the escape vanishes.

### Describe the problem in detail

RStudio actively removes the backslash in the visual mode editor. You can escape the semicolon in source mode, but it gets de-escaped every time I go back to visual mode. In canonical mode, you cannot even write it (as I would expect). Keeping the semicolon as-is will result in the expected citeproc or biblatex error.

EDIT: I have just noticed that the issue exists outside citations.

### Describe the behavior you expected

You should be able to just escape the semicolon with a backslash.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@netique Thank for raising this! I can reproduce this, as well, in RStudio Desktop 2022.07.2+576 on MacOS 13.3. We'll review this as we continue improvements to RStudio and the visual editor.
