### ISSUE TITLE
Autocomplete error

### ISSUE THREAD

**Issue by lebonaz** [rstudio/rstudio#12956]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.03.0+386 "Cherry Blossom" (release for Windows)
    OS Version      : Windows 22H2
    R Version       : 4.2.3

### Steps to reproduce the problem
Write the following code character by character in a new R script
```
mtcars[mtcars$mpg > 22 & (mtcars$carb < 4 | mtcars$cyl > 5), ]
```

### Describe the problem in detail
The following error is thrown in the console as of typing the third character (this is the number of characters as specified in my setting 'Show completions after characters entered') of 'mtcars' inside the first set of round brackets. Options for autocompletion are no longer returned.
![image](https://user-images.githubusercontent.com/129832473/229717272-dfa9cb88-2f98-4054-a605-95b4e8783e53.png)

> traceback()
1: .rs.rpc.get_completions("mtc", list(), list(), list(), "", "mtcars", 
       list(), list(), FALSE, "", "57367322", "mtcars[mtcars$mpg > 22 & (mtc", 
       FALSE)

### Describe the behavior you expected
The expectation is that the autocomplete would work whether or not round brackets are included.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This should be fixed in the latest daily builds, available from https://dailies.rstudio.com/.
