### ISSUE TITLE
data.frame preview on autocomplete menu is dangerous.

### ISSUE THREAD

**Issue by mertgoksel** [rstudio/rstudio#12964]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.03.0 Build 386
    OS Version      :  22H2 22621.1485
    R Version       :  4.2.3

### Steps to reproduce the problem
-Import a big dataset
-Hover over the datasets name in autocomplete menu
-Rstudio Freezes

### Describe the problem in detail
This issue is created by the new feature of data.frame preview on autocomplete menu and there is no option to disable it from what i see. 

### Describe the behavior you expected
Issue can be fixed by adding an option for disabling or making it only show head of the data.

**Comment by kevinushey** [comment]
Can you please share a reproducible example?

**Comment by ergz** [comment]
it would be great to have a way to disable this feature, more than half the time the preview is the wrong dataset usually pointing to a previous dataset in the session. I am running Windows 11 

```
RStudio Edition : Desktop
RStudio Version :  2023.03.0 Build 386
OS Version      :  22H2 22621.1485
R Version       :  4.2.3
```

**Comment by romainfrancois** [comment]
Something probably gets mixed up here: 

https://github.com/rstudio/rstudio/blob/afdee25b92abb127646fc345f5be6481ea777a0f/src/cpp/session/modules/SessionHelp.R#L559-L560

Or maybe there is caching involved in the browser side so the `<iframe>` that host the table is not re-rendered. This should probably not use the same cache key `"completion_popup_dataframe"`

**Comment by romainfrancois** [comment]
In terms of the original problem, perhaps indeed this could only `.rs.assignCachedData("completion_popup_dataframe", head(data, <some number> ), "")` to only show `<some number>` rows

**Comment by tbauer23** [comment]
> 

I too would like to have an option to disable this feature. Is this something in the works?

**Comment by phenrickson** [comment]
Echoing the comments here, I upgraded to a newer version of RStudio recently and this preview on auto complete is causing RStudio to completely freeze every time it attempts to preview a large dataset. I'm on an M1 MacBook, and it seems to happen in particular when previewing lists of any size - I end up with 100% CPU usage and RStudio becomes completely unresponsive.

I have not found any solution to this and I currently have to force quit and restart my code anytime it happens, it would be great to be able to turn off this feature

R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

**Comment by CatherineProulx1** [comment]
+1 on wanting a way to disable this feature globally. It causes my RStudio to hang on heavily nested datasets.

**Comment by jrausch12** [comment]
Also +1. This issue is hindering productivity. How did this feature roll out without being on release notes and without a toggle? Not the level of quality I have come to expect from the Posit team.

**Comment by kevinushey** [comment]
A reproducible example would help us to be certain what the problem is, and what the correct fix is.

**Comment by kevinushey** [comment]
Thanks! Here's a similar example that generates the data more quickly.

```
library(tibble)
data <- replicate(1E4, 1:1E4, simplify = FALSE)
names(data) <- make.unique(rep.int("V", 1E4))
df <- as_tibble(data)
```

I'll take a look.

**Comment by mikebessuille** [comment]
@kevinushey given the size of the change can you please hold off merging it and we will get it into the planned patch 2023.06.1 which is only a couple weeks after the main release?  This is not a good bug, but I think it can wait slightly.

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2023.06.0-daily+411
Windows 11, Ubuntu 22

Large data sets autocomplete much more quickly than in cherry blossom, as expected.

**Comment by rpmeira** [comment]
Is there any fix to this problem yet? 
I've tried every release since RStudio-2022.12.0-353 and all of them have this same problem. (Im on Windows 10)

**Comment by rpmeira** [comment]
@jonvanausdeln Done. Issue #13579
