### ISSUE TITLE
Deletion of chunk option comments in R markdown files

### ISSUE THREAD

**Issue by ms609** [rstudio/rstudio#12968]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
    RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

    OS Version      : Windows 10
    R Version       : R-devel

### Steps to reproduce the problem
1. Create an R Markdown document (with extension `.Rmd`) with content:

```Rmd
---
title: "My Document"
---
  
```{r chunk-name, echo = FALSE}
#| message = FALSE,
#| results = "hide"
print("Some thing")
` `` <<< Omit space, added to nest backticks <<<
```

2. Insert the cursor between pipe and content, i.e. at position indicated by caret `^` below, and press "enter"
`#| ^results = "hide"`

### Describe the problem in detail
The affected lines disappear

### Describe the behavior you expected
A new line should have been inserted:
```Rmd
#| 
#| results = "hide"
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ms609** [comment]
Still present in the latest daily build:

```
RStudio 2023.12.0-daily+159 "Ocean Storm" Daily (3aa860ca56514e7c123143ab87cf4e55a307b7e4, 2023-10-09) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0-daily+159 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
```

**Comment by kevinushey** [comment]
The offending code lives here:

https://github.com/rstudio/rstudio/blob/c8fce22ecb95a119a90fd2f6d5ca68c30a082569/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetQuartoHelper.java#L112-L132

We need to make sure the comment check applies to the whole line, not just up to the cursor position.

https://github.com/rstudio/rstudio/blob/c8fce22ecb95a119a90fd2f6d5ca68c30a082569/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetQuartoHelper.java#L84

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+306](https://dailies.rstudio.com/version/2023.12.0-daily+306)
Windows 11

Newlines are created as expected.

**Comment by ms609** [comment]
Works for me too – thanks very much for constructing this patch.
