### ISSUE TITLE
Menu commands not disabled when a modal dialog is displayed (Electron desktop)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12972]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0-386
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

- In RStudio desktop (electron), show a modal dialog such as Tools / Global Options
- Now open one of the main menus and examine the state of commands

### Describe the problem in detail

- The commands are still enabled, and you can trigger at least some of them

<img width="1407" alt="Screenshot 2023-04-10 at 10 10 37" src="https://user-images.githubusercontent.com/10569626/230943088-39847aa5-6630-4703-a9c5-8386a5499597.png">

- Compare with RStudio Qt (e.g. 2022.07); on Windows and Linux (at least desktops where the main menu is displayed in the app window) the entire menubar is disabled; on Mac, the menus can still be opened but all the commands are disabled

<img width="1198" alt="Screenshot 2023-04-10 at 09 58 59" src="https://user-images.githubusercontent.com/10569626/230942306-621dc829-70d4-4e0a-b09e-f1b49f1ef103.png">

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Note to self: https://github.com/rstudio/rstudio/pull/4790

**Comment by sharon-wang** [comment]
While looking into this, I was wondering why there was some weirdness with the Window/Fenêtre menu bar item (shows up in placeholder menu, but doesn't show up in the regular menu), but I just saw https://github.com/rstudio/rstudio/issues/12972 which explains the situation!

**Comment by timtmok** [comment]
Validated in 2023.08.0-daily+32.pro6

I don't think this functionality can be automated since it requires interaction with the menu (native).

**Comment by timtmok** [comment]
I'm reopening since Linux shows a menubar now in the license dialog.



![Image](https://github.com/rstudio/rstudio/assets/9591545/c4bc964a-07be-4f70-9b71-e1e5cb3a333a)



https://github.com/rstudio/rstudio-pro/blob/main/src/node/desktop/src/ui/modal-dialog.ts#L53

That seems to trigger a placeholder menu for the license dialog. If this is only to address Mac, I think we can do the menu placeholder only on Mac. Linux and Windows disable application menu interaction when a modal is visible.
