### ISSUE TITLE
Poor experience starting RStudio desktop if user-state folder inaccessible

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12988]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03-386
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

- deny your user account access to the RStudio user-state folder:
    - (Mac/Linux): `chmod 0 ~/.local/share/rstudio`
    - (Windows): `icacls %localappdata%\RStudio /deny %USERNAME%:(OI)(CI)F`
- start RStudio

### Describe the problem in detail

- window never appears but process remains running
- if you run from a terminal, you'll see: 

```
(node:71423) UnhandledPromiseRejectionWarning: Error: Cannot create BrowserWindow before app is ready
    at t.createStandaloneErrorDialog (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:19:80580)
    at Object.main (/Applications/RStudio.app/Contents/Resources/app-arm64/.webpack/main/index.js:19:37207)
(Use `RStudio --trace-warnings ...` to show where the warning was created)
```

### Describe the behavior you expected

- Behave more like Qt desktop did in this scenario: on Mac, it would display the main window with an error message so the user has some idea how to fix it; Windows is a bit different
- At a minimum, don't just sit there with no UI and a process running in the background; show SOMETHING and allow user to exit

<img width="1089" alt="example of RStudio 2022.07 behaviour" src="https://user-images.githubusercontent.com/10569626/231827619-d3dfb4db-0bed-4b2b-92dd-542df8008226.png">

### Restoring Folder Access on Windows
- `icacls %localappdata%\RStudio /grant %USERNAME%:(OI)(CI)F`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.05.0-daily+275 on
- MacOS 13.4
- Windows 11
- Ubuntu 22.04.2

**Comment by ronblum** [comment]
Note: see #9704 for the RStudio Server behavior.
