### ISSUE TITLE
R encounterd a fatal error. The session was terminated.

### ISSUE THREAD

**Issue by jjoseph0079** [rstudio/rstudio#12982]
### System details

    RStudio Edition: Desktop
    RStudio Version:  4.2.3 (2023-03-15)
    OS Version:  windows 11
    R Version : 4.2.3

### Steps to reproduce the problem
Running any line of code

### Describe the problem in detail
When running any line of code in RStudio, it aborts the session and gives an error message- R encounter a fatal error. The session was terminated

### Describe the behavior you expected
I expected a normal output depending  on the chunk of the code

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
![Screenshot 2023-04-12 125036](https://user-images.githubusercontent.com/130547557/231422845-6f4227a5-1ae9-48b9-8a22-b431bbf26b9b.jpg)

**Comment by jjoseph0079** [comment]
R 2023.03.0.386 is the R version

**Comment by hckkkk** [comment]
I have met the same question!

**Comment by KnDmitriy** [comment]
I have met the same problem! I didn't solve it and went to use posit cloud.

**Comment by sadettindemirel** [comment]
I have met the same question on my M3 silicon Mac

**Comment by salonibhogale** [comment]
I face this problem too. Running any line of code triggers this. This on the Mac M2.

**Comment by Huiying-Xu** [comment]
> I have met the same problem on my M3 silicon Mac

I have this same issue when I tried to run my R script from my old MacBook. have you resolved this?

**Comment by JoseCastilloPHD** [comment]
Same issue. Decided to restart my learning of "R". Bought "R in Action". Installed R version 4.5.0 (2025-04-11)
Installed last version of RStudio for my MacOS (Monterey-version 12.7.6). The RStudio version is: Version 2024.09.1+394 (2024.09.1+394). The same error appear when I use the old RStudio version. (Version 0.99.903 – © 2009-2016 RStudio, Inc.)
No issues running R. Issue is running RStudio.

**Comment by kevinushey** [comment]
Sorry to say, but macOS 12.7.6 is no longer supported by Apple so it's possible you'll have compatibility issues running newer versions of RStudio with older (no longer supported) versions of macOS. https://endoflife.date/macos

You may have better luck with an older release of RStudio (https://dailies.rstudio.com/release/), but note that there's no guarantee these older versions of RStudio will support the newest releases of R, either.

**Comment by JoseCastilloPHD** [comment]
Issue is with a simple demo() or help() command... It is probably something very fundamental and simple. I appreciate any input.
Thanks
JC

<img width="1386" alt="Image" src="https://github.com/user-attachments/assets/c5166e20-62f4-48b0-81c0-096932f5d547" />

**Comment by JoseCastilloPHD** [comment]
Kevin,

Thank you very much.  I just read issues in installation, so I am going to try that.

JC

From: Kevin Ushey ***@***.***>
Date: Monday, June 2, 2025 at 2:46 PM
To: rstudio/rstudio ***@***.***>
Cc: Jose Castillo ***@***.***>, Comment ***@***.***>
Subject: Re: [rstudio/rstudio] R encounterd a fatal error. The session was terminated. (Issue #12982)

[https://avatars.githubusercontent.com/u/1976582?s=20&v=4]kevinushey left a comment (rstudio/rstudio#12982)<https://github.com/rstudio/rstudio/issues/12982#issuecomment-2932430591>

Sorry to say, but macOS 12.7.6 is no longer supported by Apple so it's possible you'll have compatibility issues running newer versions of RStudio with older (no longer supported) versions of macOS. https://endoflife.date/macos

You may have better luck with an older installation of RStudio (https://dailies.rstudio.com/release/), but note that there's no guarantee these older versions of RStudio will support the newest releases of R, either.

**Comment by andythehero-cmyk** [comment]
I managed to fix it by downgrading R to 4.2.3 and then reinstalling R Studio (2024.04.2). Somehow this worked even though R didn't seem to be the problem (it was working when used via Terminal).
