### ISSUE TITLE
RStudio failing to query R for path locations using R.exe on Windows but RTerm.exe works

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#12984]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.05.0-daily-202
    OS Version      : Windows 10 or 11
    R Version       : Any

### Steps to reproduce the problem

Splitting this out from [RStudio not able to load selected R version on Windows #12452](https://github.com/rstudio/rstudio/issues/12452)

On certain Windows systems (haven't identified the root cause), RStudio's attempt to query for path locations by invoking R.exe fails but works if Rterm.exe is used.

@morrisseyj has reported this problem, but suspect there are many others.

Starting with build 2023.05 (202), there is no way to work around this.

### Describe the problem in detail

Users can't start RStudio on Windows after selecting an R version.

### Describe the behavior you expected

Works on all systems.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Internal research note: there is some precedent for using `rterm.exe` instead of `r.exe` when we ask the chosen version of R for some info during startup. In Qt desktop, we did that here:

https://github.com/rstudio/rstudio/blob/3a3ab49f810c1ede72e53cef39f364cfb90aaf09/src/cpp/desktop/DesktopSessionLauncher.cpp#L585

**Comment by morrisseyj** [comment]
Problem appears to be solved for me.

@gtritchie indicated, in a private correspondence, that the hourly build had been updated to prefer Rterm.exe when executing Rstudio. Just tried it and 

Just tried it using the latest hourly build: 2023.05.0-hourly+216. RStudio launches as expected with no dialogue asking me to select my version of R. 

Hopefully this is all sorted. 

If you need anything else, let me know. 

Thanks @gtritchie  for all of the work to get this resolved.
