### ISSUE TITLE
"Render on Save" Not showing in toolbar

### ISSUE THREAD

**Issue by randrescastaneda** [rstudio/rstudio#12998]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386 Cherry Blossom (desktop)
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.2 (2022-10-31 ucrt)

### Steps to reproduce the problem

My toolbar does not show the **Save on render** checkbox when working on Quarto documents:

![image](https://user-images.githubusercontent.com/35301997/232089099-f9c69615-9895-435c-be1a-9a3b1efc9333.png)
 
### Describe the problem in detail

I have tried to find the solution on the web without success:

I saw [this question](https://community.rstudio.com/t/render-on-save-not-on-toolbar/149384) in the Posit community but it does not have an answer (at least not visible to me).

I also noticed that other people have [the same problem](https://github.com/rstudio/rstudio/issues/12838#issue-1623476584) even though they have not properly reported it.  

### Describe the behavior you expected

I expect to have a functional Save on Render checkbox as explained in the [documentation](https://quarto.org/docs/computations/r.html#render-and-preview):
![image](https://user-images.githubusercontent.com/35301997/232090305-774f131b-0909-4a48-a677-d6513e539202.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@randrescastaneda Thank you for raising this! I'll mark it for review as we consider Quarto-related issues. A couple of questions:
1. Does this happen in visual mode, source mode, or both?
2. Does this happen with R Markdown documents?

**Comment by randrescastaneda** [comment]
Hi @ronblum , 

Thank you for getting back. Regarding your questions, 

1. It happens in both, visual and source modes. 
2. Yes, I don't have any "render on save" checkbox with RMarkdown documents either. 

Thanks.

**Comment by jmcphers** [comment]
Is it possible that you have auto-save turned on? I believe that button gets hidden if you are using auto-save. You can check here, in Global Options -> Code -> Saving:

<img width="291" alt="image" src="https://github.com/rstudio/rstudio/assets/470418/01f192f4-0d8c-421f-90a1-21c117b691bd">

Do you have "Automatically save when editor loses focus" checked, and/or do you have "When editor is idle: Save and write changes" set?

**Comment by randrescastaneda** [comment]
YES! That was the issue. Problem solved!

Thank you so much. 
Best,
