### ISSUE TITLE
Improve code navigation in R files

### ISSUE THREAD

**Issue by doncqueurs** [rstudio/rstudio#12995]
I would like to request a feature that enables a user to quickly navigate the code and thereby increase the productivity of the data scientist. In a nutshell, it would be great if the user can quickly navigate to the point where the function is defined by a double mouse click combined with holding CTRL/Command.

I have two use case scenarios to illustrate what I have in mind:

**1. Normal R file**
In this scenario I would like to focus the cursor on the row where the function is defined when I CTRL + double click inside the mutate function. The same could be the case when the user clicks on mtcars_tbl that the focus is then shifted towards the line where mtcars_tbl is defined. 

Especially in large R files this help me to quicker navigate it instead of scrolling. 

```
some_function <- function(){ ... }

mtcars_tbl <- mtcars

mtcars_tbl %>%
  mutate(
    new_var = some_function()
  )
``` 

**2. in Shiny files** 
Similar to the first example, I would like to see this work for reactive variables in shiny code as well. Hear a basic example, when the user clicks on r_tbl() inside the renderDT, the cursor focus should jump to the line where r_tbl is defined.

```
shinyServer(function(input, output, session) {

r_tbl <- reactive({mtcars})

output$DT <- renderDT({
  r_tbl() %>%
    DT::datatable()
})

}
```

It would be amazing when this is also working when external files are brought into an R file with functions like source(), in this case it could open the file in RStudio and focus on the line where the function is defined.

**Comment by ronblum** [comment]
@doncqueurs Thank you for the suggestion! We'll review it as part of our ongoing evaluation and development of RStudio.
