### ISSUE TITLE
Latest daily build is a .tar.gz instead of .deb/.rpm

### ISSUE THREAD

**Issue by Deleetdk** [rstudio/rstudio#13008]
### System details

    RStudio Edition : Either
    RStudio Version : rstudio-2023.05.0-daily-251
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
Visit https://dailies.rstudio.com/ and see that the daily builds are now .tar.gz files. These are somewhat less user friendly than .deb/.rpm etc. because they do not integrate automatically with GUIs for installing software.

### Describe the problem in detail
Unclear why daily builds are now .tar.gz, might be unintentional.

### Describe the behavior you expected
The regular files.

**Comment by MariaSemple** [comment]
Thanks for this report! A fix is incoming

**Comment by MariaSemple** [comment]
@cm421 were you able to verify this?

**Comment by cm421** [comment]
Yup, verified, but forgot to close. My bad
