### ISSUE TITLE
Dailies Page can have invalid JSON

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#13005]
After some Linux builds failed, the Dailies Page and subsequent JSON API are corrupted, giving invalid JSON.

From https://dailies.rstudio.com/rstudio/latest/index.json

> "jammy-amd64": {
"name": "Ubuntu 22",
"architecture": "x86_64",
"link": "https://s3.amazonaws.com/rstudio-ide-build/electron/jammy/amd64/rstudio-2023.05.0-daily-251-amd64-debian.tar.gz",
"filename": "rstudio-2023.05.0-daily-251-amd64-debian.tar.gz",
"sha256": "",
"channel": "Daily",
"version": "2023.05.0-daily+251",
"size": < no value > ,
"commit": "adf009da13910f7aae13b49a44b6dd31c2ee27df",
"date": "2023-04-15 00:35:05 +0000 UTC"
}

Note the `< no value >`, which is invalid JSON

From Dailies Page:

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/6433789/232591265-43414f30-28a0-4af4-9cf6-40791908034e.png">

It points to a `.tar.gz` 

The invalid JSON breaks one of my scripts and could others.  The dailies page could be confusing to users.

**Comment by ronblum** [comment]
@AndrewMcClain Can you take a look at this? This is referenced in an internal Slack thread.

**Comment by jmcphers** [comment]
Also spotted by @hrbrmstr. https://twitter.com/hrbrmstr/status/1648339825370513409

**Comment by jonvanausdeln** [comment]
Builds are working with not apparent issues, so closing this out.
