### ISSUE TITLE
Find in Files fails when using "Whole word" if the search term has a `.` in it

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#13017]
RStudio 2023.05.0-daily+264 "Mountain Hydrangea" Daily (314f4c031ee1e7de76a4c57b73879e3be02f0ee4, 2023-04-18) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.05.0-daily+264 Chrome/110.0.5481.177 Electron/23.1.2 Safari/537.36

It seems to work if you uncheck `Whole word`, but I actually did want that, and this was a bit surprising

https://user-images.githubusercontent.com/19150088/233095772-6cdf2cde-1d18-47ab-b29e-978270ad3799.mov

**Comment by kevinushey** [comment]
https://stackoverflow.com/questions/7607879/git-grep-and-word-boundaries-on-mac-os-x-and-bsd suggests this might be due to `git grep` not handling `\b` word boundaries.

https://github.com/rstudio/rstudio/blob/17a9562b352f9a726188f570dec55e683a663c91/src/cpp/session/modules/SessionFind.cpp#L1611-L1612

Not quite sure what the right solution is.

**Comment by jennybc** [comment]
I am also seeing this. But I'll add that my search term does not have a `.` in it.

Using Version 2023.03.0+386 (2023.03.0+386) on macOS, git version 2.39.2 (Apple Git-143)

In the gargle package (https://github.com/r-lib/gargle), if I search for "Workbench" unconditionally there are several hits, all of which look like "whole word" hits to me. But if I check "Whole word", I get **no hits**.

**Comment by kevinushey** [comment]
There's a fix incoming in the next daily builds -- @jennybc and @DavisVaughan, can you give this a test drive in the coming days?

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.05.0-daily+326 on MacOS 13.4.

Tested with searches with and without "whole word" checked. Conditions of searched word in the files include:
- surrounded by spaces
- surrounded punctuation, e.g. `,Workbench,`
- the only word on a line
- preceded by period, e.g. `.Workbench`
- preceded by word characters and a period, e.g. `also.Workbench` 

Tested in
- no project
- a git-managed project
- a regular (non-git) project

**Comment by DavisVaughan** [comment]
I can confirm that the original example works for me now with:

RStudio 2023.05.0-daily+326 "Mountain Hydrangea" Daily (c4f507fb638f9ac30e24911ec206da88e639acf2, 2023-05-03) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.05.0-daily+326 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
