### ISSUE TITLE
`Unlink` function makes file appear twice in files pane after creating it manually in RStudio Files pane

### ISSUE THREAD

**Issue by liyongg** [rstudio/rstudio#13016]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.3.0.386
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.3 (2023-03-15 ucrt)

### Steps to reproduce the problem
Work in an arbitrary directory. Create a folder `mydir` and a file in this folder called `test.txt` **using the RStudio files pane.**: `New Folder ` and  `New Blank File -> Text File`.
![image](https://user-images.githubusercontent.com/44399190/233030678-fced58cc-9587-4e4d-8048-cac29d624a56.png)

Source the following code that is contained in `Documents.R`:
```
foo <- function() {
  file.rename(from = "mydir/test.txt", to = "test.txt")
  unlink("mydir", recursive = TRUE)
}

foo()
```

### Describe the problem in detail
The problem that arises is that the RStudio Files pane will show the file `mytest.txt` twice after sourcing `Documents.R`. Selecting one of these will select both of them. In the Windows File Explorer, there is no such duplicate file.
![image](https://user-images.githubusercontent.com/44399190/233031214-9853e5a1-c280-4f3d-8248-312d4ec21c4d.png)

The problem in the Files pane is 'fixed' by refreshing the pane. Also, I have tested that creating the `mydir/test.txt` file and folder in the same `foo` function does behave normally: no duplicate entries in the pane. When using a function to create this folder and file, there are no duplicate entires. _It appears_ that it only happens when using the `New Folder` and `New Blank File` options in the Files pane.

### Describe the behavior you expected
The `test.txt` file should have only one entry in the Files pane. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@liyongg Thank you for raising this! Do you happen to know if this worked for you as expected in a previous versions of RStudio?

**Comment by liyongg** [comment]
@ronblum I have not run any code similar to what I described in the initial post in previous versions of RStudio, so unfortunately no.
