### ISSUE TITLE
Window invisible after restoring a maximized window that was previously minimized on macOS

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13010]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12+ (Electron)
    OS Version      : macOS 13.3.1 (Ventura)
    R Version       : any

### Steps to reproduce the problem

NOTE: this was split out from [Closing and reopening a maximized IDE doesn't return it to its original position when unmaximized #12992](https://github.com/rstudio/rstudio/issues/12992)

* Launch RStudio on macOS
* double-click title bar to maximize
* minimize the window (yellow circle in title bar)
* redisplay the window by clicking on it in dock
* quit and restart RStudio (it should start maximized)
* double-click title bar to unmaximize

### Describe the problem in detail

The window shrinks to nothing (i.e. can't see it).

If you quit, then restart, the window will reappear.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Tested with RStudio Desktop 2023.05.0-daily+275 on MacOS 13.4. The window is still trying to hide, although it's not doing a very good job of it.



![Image](https://user-images.githubusercontent.com/31009952/233685838-dacee62c-0449-4db8-912c-9b3125742bee.png)

**Comment by gtritchie** [comment]
That is the expected behaviour. See the PR notes.
