### ISSUE TITLE
RStudio fails to launch. DEBUG stderr: Fatal error: 'R_TempDir' contains space

### ISSUE THREAD

**Issue by bedalus** [rstudio/rstudio#13012]
### System details

    RStudio Edition : https://dailies.rstudio.com/rstudio/mountain-hydrangea/electron/windows/2023-05-0-daily-217/
    RStudio Version : daily
    OS Version      : Windows 10 Azure m365
    R Version       : 4.2.3

### Steps to reproduce the problem

Start Menu > RStudio

### Describe the problem in detail

Dialogue box pops up showing 4.2.3 as the only option. However, cannot click OK. Browsing for R.exe or RTerm.exe does not work.

### Describe the behavior you expected

A blue circle with R should appear! Followed by the IDE!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

## More Info!

I'm using the daily as per advice in 12452.

Screenshot of our user profile storage:

![image](https://user-images.githubusercontent.com/1886595/232855883-9f2672bb-55e2-42c9-90c0-83645d7aaac3.png)

This issue is occurring for only for users who have spaces in their profile, in the image for example, the second one. You can see this in the log for 'removed.nm (0BC9DCE4)' below:

```
2023-04-18T16:08:38.229Z DEBUG Ready to run
2023-04-18T16:08:38.282Z DEBUG instance lock: true, project: , file: false
2023-04-18T16:08:38.287Z DEBUG net-ipc: creating new message server; socket=C:/Users/removed.nm (0BC9DCE4)/AppData/Local/RStudio/rstudio.socket
2023-04-18T16:08:38.294Z DEBUG Found the following R installations in the registry: [
  "C:\\Program Files\\R\\R-4.2.3"
]
2023-04-18T16:08:38.294Z DEBUG Found R installation at path: C:\Program Files\R\R-4.2.3
2023-04-18T16:08:38.295Z DEBUG Found the following R installations: [
  "C:\\Program Files\\R\\R-4.2.3"
]
2023-04-18T16:08:38.353Z DEBUG net-ipc: 9640 taking over as primary instance
2023-04-18T16:08:38.505Z DEBUG Validating R installation at path: C:\Program Files\R\R-4.2.3\bin\x64\Rterm.exe
2023-04-18T16:08:38.506Z DEBUG Querying information about R executable at path: C:/Program Files/R/R-4.2.3/bin/x64/Rterm.exe
2023-04-18T16:08:38.586Z DEBUG stdout: [no stdout produced]
2023-04-18T16:08:38.586Z DEBUG stderr: Fatal error: 'R_TempDir' contains space

2023-04-18T16:08:38.586Z DEBUG status: 2 [failure]
2023-04-18T16:08:38.586Z DEBUG Error querying information about R: no output available
2023-04-18T16:08:44.715Z DEBUG Using user-selected version of R (C:\Program Files\R\R-4.2.3/bin/x64/Rterm.exe)
2023-04-18T16:08:44.716Z DEBUG Querying information about R executable at path: C:/Program Files/R/R-4.2.3/bin/x64/Rterm.exe
2023-04-18T16:08:44.789Z DEBUG stdout: [no stdout produced]
2023-04-18T16:08:44.789Z DEBUG stderr: Fatal error: 'R_TempDir' contains space

2023-04-18T16:08:44.789Z DEBUG status: 2 [failure]
2023-04-18T16:08:44.789Z DEBUG Error querying information about R: no output available
2023-04-18T16:08:44.789Z ERROR Selected R path: C:\Program Files\R\R-4.2.3/bin/x64/Rterm.exe
2023-04-18T16:08:44.790Z ERROR An unknown error occurred.
2023-04-18T16:09:00.772Z DEBUG Using user-selected version of R (C:\Program Files\R\R-4.2.3\bin\x64\Rterm.exe)
2023-04-18T16:09:00.773Z DEBUG Querying information about R executable at path: C:/Program Files/R/R-4.2.3/bin/x64/Rterm.exe
2023-04-18T16:09:00.845Z DEBUG stdout: [no stdout produced]
2023-04-18T16:09:00.845Z DEBUG stderr: Fatal error: 'R_TempDir' contains space

2023-04-18T16:09:00.845Z DEBUG status: 2 [failure]
2023-04-18T16:09:00.845Z DEBUG Error querying information about R: no output available
2023-04-18T16:09:00.845Z ERROR Selected R path: C:\Program Files\R\R-4.2.3\bin\x64\Rterm.exe
2023-04-18T16:09:00.845Z ERROR An unknown error occurred.
```

I fixed the issue for this user by deleting their profile and their account, then recreating it. The new one had no spaces and worked perfectly. So, presumably the logged error message about R_TempDir containing a space is a reference to the space in their user account name, as per this line:

socket=C:/Users/**removed.nm (0BC9DCE4)**/AppData/Local/RStudio/rstudio.socket

I'd prefer not to have to rebuild every affected account of course! Can you detect and accommodate spaces in paths?

**Comment by kevinushey** [comment]
This apparently comes from R itself:

https://github.com/wch/r-source/blob/e7a21904029917a63b4717b53a173b01eeabcc7b/src/main/sysutils.c#L1942

Your best bet is to set the `TMPDIR` environment variable for these users to some path not containing spaces.

**Comment by bedalus** [comment]
Confirmed using that query. We're blocked by a registry setting: 
```
The registry state is: 1 (Disable 8dot3 name creation on all volumes).
```
I'm unwilling to set a GPO to accommodate an old DOS vestige! I'll try my luck with the TMPDIR. Thanks for the prompt reply and insight!

**Comment by venkmurthy** [comment]
I am experiencing this error #13060 even thought my TMPDIR environment is set as C:\Temp (the user name does have a space though).

![env](https://user-images.githubusercontent.com/855197/234957904-c81ad465-a6d1-427a-9882-0cc8d9e93c31.png)

**Comment by venkmurthy** [comment]
That seems to work. Not sure which of the two (or both) were required. Perhaps to stick my nose slightly out of line, but shouldn't Rstudio only rely on one of these potential variations to avoid potential confusion/mishaps?

**Comment by gtritchie** [comment]
This isn't RStudio, it's R itself, which isn't something we have any control over.

**Comment by venkmurthy** [comment]
Thank you for the clarification

**Comment by kevinushey** [comment]
For reference, R has this documentation in `?tempdir`:

```
     By default, 'tmpdir' will be the directory given by 'tempdir()'.
     This will be a subdirectory of the per-session temporary directory
     found by the following rule when the R session is started.  The
     environment variables 'TMPDIR', 'TMP' and 'TEMP' are checked in
     turn and the first found which points to a writable directory is
     used: if none succeeds '/tmp' is used.  The path should not
     contain spaces.  Note that setting any of these environment
     variables in the R session has no effect on 'tempdir()': the
     per-session temporary directory is created before the interpreter
     is started.
```

I see the following in the R sources:

https://github.com/wch/r-source/blob/6e2902500a59e084ac9e1db25c5ed247788fca28/src/main/sysutils.c#L1890-L1905

So, setting `TMPDIR` should work, as long as the directory exists and is writable. It does seem to work locally for me on a Windows machine:

```
> tempdir()
[1] "C:\\temp\\RtmpaAEO5v"
> Sys.getenv("TMPDIR")
[1] "C:\\temp"
```

**Comment by venkmurthy** [comment]
The weird thing is that setting TMPDIR alone did not seem to be sufficient for me and it was also different in result depending on which Rstudio build I used (all with same R build - 4.2.3)

**Comment by gtritchie** [comment]
We (RStudio) could consider unsetting all three of these before we start the R session (on Windows only) and let R pick its own temp path.

I already do that when detecting R, but not before starting the actual R session.

https://github.com/rstudio/rstudio/blob/a232fe149ac4611b3f84a6b449e9061b91aba696/src/node/desktop/src/main/detect-r.ts#L215-L227

**Comment by venkmurthy** [comment]
Does that explain why earlier builds were working and then stopped right around that time?

**Comment by gtritchie** [comment]
Yes it could be a factor. I'm going to remove that code, it was an experiment but given what we know now it's potentially doing more harm than good.

**Comment by gtritchie** [comment]
I just removed that bit of code, and did some local testing with a user account containing a space, and with 8.3 file generation turned off for the filesystem. You should now be able to successfully set `TMPDIR=C:\temp` and have RStudio start. A build with the change should be available in the next day or so. I'll post a link to it here once it appears.

**Comment by gtritchie** [comment]
Reopening until we've confirmed we've got this working.

**Comment by gtritchie** [comment]
We should consider detecting this specific error from R (`'R_TempDir' contains space`) and give a more specific error message with guidance on how to fix it.

**Comment by gtritchie** [comment]
This build has the change mentioned earlier: https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2023.05.0-daily-319.exe

**Comment by venkmurthy** [comment]
Confirmed that build 319 fixes the issue in that none of TMP, TEMP, TMPDIR need to be a directory without spaces in it to launch Rstudio. "%USERPROFILE%\AppData\Local\Temp" works even if the user name has a space in it.

**Comment by kevinushey** [comment]
> "%USERPROFILE%\AppData\Local\Temp" works even if the user name has a space in it.

For reference, this will only work if so-called "short path names" are enabled on the system, since R tries to convert such paths to short paths in this scenario.

> TMPDIR does need to be set to a directory without spaces though.

Similar to the above, I think it would work to use a short path name so that spaces aren't encoded into the path.

**Comment by venkmurthy** [comment]
> For reference, this will only work if so-called "short path names" are enabled on the system, since R tries to convert such paths to short paths in this scenario.

How does one enable this?

**Comment by kevinushey** [comment]
Short path names are enabled by default on Windows, but administrators can disable this if necessary for some reason. See the documentation at https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-8dot3name for more details.

**Comment by DylanDijk** [comment]
Any updates on a solution to this? I am currently having this problem after installing R-4.3.3.

**Comment by kevinushey** [comment]
Sorry, but there's nothing we can do on the RStudio side, beyond recommending users set `TMPDIR` to a path not containing spaces.

**Comment by DylanDijk** [comment]
Could you advise me on how to do this. In which file do I need to set TMPDIR. Are there clear instructions anywhere you know of?

**Comment by kevinushey** [comment]
The documentation in R from `?Startup` is the definitive source, but likely the best location would be in your R installation's `etc/Renviron.site` file. (You may need to create it, if it doesn't exist.)

You could add something like:

```
TMPDIR = "C:/tmp"
```

to that file.

If that file isn't accessible (e.g. because R was installed by an administrator and so you don't have access to the R installation's `etc` folder), then you could instead place it within your home folder. You could run something like this from R:

```
file.edit('~/.Renviron')
```

and then add `TMPDIR = "C:/tmp"` similar to the above. To confirm, you can then restart the R session, and check the output of `tempdir()` -- it should now point to the temporary directory you've set.

Note that you may also need to set `TEMP` or `TMP` as well, as others have found setting only `TMPDIR` may not be sufficient.

**Comment by DylanDijk** [comment]
Ok thank you, I will try this. Do I set 'TEMP' and 'TMP' to the same as 'TEMPDIR'. Also do I need to set any of the windows environment variables, someone mentioned this on stackexchange.

**Comment by DylanDijk** [comment]
This did not work.

What did work is by going on the "Edit the system environment variables" on the control panel, as mentioned in the earlier [post](https://github.com/rstudio/rstudio/issues/13012#issuecomment-1526140581) and then under user variables: setting all three TEMP, TMP, TMPDIR to `C:/Temp`.
