### ISSUE TITLE
History: "Insert Command into Document" not working for Visual Markdown Editor

### ISSUE THREAD

**Issue by DvP17** [rstudio/rstudio#13028]
### System details

    RStudio Edition : RStudio Desktop
    RStudio Version : RStudio 2023.03.0+386 "Cherry Blossom" Release (2023-03-09) 
    OS Version      :  Windows 10
    R Version       :  R-4.2.1

### Steps to reproduce the problem
1. Open .Rmd file in visual mode and create chunk
2. Switch to history pane 
3. Click "To Source" in history pane or shift + enter
4. Nothing happens

### Describe the problem in detail
It should be possible to copy lines from the history pane to the document in visual mode. Right now, nothing happens when you press "To Source" when the .Rmd file is in visual mode.

### Describe the behavior you expected
1. Open .Rmd file in visual mode and create chunk
2. Switch to history pane 
3. Click "To Source" in history pane or shift + enter
4. Line is copied to document (chunk in .Rmd file in visual mode)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@DvP17 Thank you for raising this! I can reproduce this in RStudio Desktop 1.4.1743 on MaOS 13.4, so it looks like it's always been this way. We'll review this as we continue development of RStudio and the visual editor.

Added note: If the cursor is in the body of the Rmd file, clicking "To source" creates a new R script with the history in it.

**Comment by arhall1** [comment]
My experience is worse than @DvP17.  Using RStudio 2023.03.0 Build 386 in Linux, I get the behavior described by @DvP17 with the additional step that RStudio pastes the line copied from the history pane in random other places in the file I'm aiming at, as well as in other  files currently open in RStudio.  

In response to ronblum's comment:  I have not had this problem with earlier versions of RStudio.  And in this version, copying from history to the console appears to work correctly.
