### ISSUE TITLE
Add ability to opt-in Electron crash handling via environment variable

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13025]
Electron's ability to generate crash dumps (when Electron itself crashes) is not enabled. So if Electron crashes, it just goes away and leaves no clues we can follow, such as in: https://github.com/rstudio/rstudio/issues/13007.

As a first step, support enabling it via an environment variable, but keep it off by default. We don't want it on by default until we've done all the work to support uploading crash dumps tracked in [Hook up crash reporter for Electron desktop #13022](https://github.com/rstudio/rstudio/issues/13022).

Suggested: `RSTUDIO_ENABLE_CRASHPAD=0|1|true|false`

Additionally, add a command (in Electron desktop only) to Help / Diagnostics / Crash RStudio Desktop that will bring up a suitably scary "Are you sure?" dialog. If they say "Yes", then invoke `process.crash()` in the main Electron process.

This will facilitate basic testing of crash dump generation (or lack thereof).

**Comment by ronblum** [comment]
Verified on MacOS 13.4. Windows and Linux TBD.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.05.0-daily+296/304 on
- MacOS 13.4
- Windows 11
- Red Hat 9.1

Checked
- Valid values (0, 1, true, false)
- Invalid value (bogus)
- Variable not defined
