### ISSUE TITLE
JavaScript exception when restoring window on Ubuntu 22

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13027]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.05.0-daily+275
    OS Version      : Ubuntu 22.04.2 (both on a physical machine, and via WSL2 on Windows-11)
    R Version       : 4.1.3

### Steps to reproduce the problem

- start RStudio
- maximize via double-click title bar or the maximize widget
- restore (unminimize) 

### Describe the problem in detail

- an error dialog displays, containing:

> "A JavaScript error occurred in the main process
> Uncaught Exception:
> RangeError: Maximum call stack size exceeded at BrowserWindow.setBounds

![image](https://user-images.githubusercontent.com/10569626/233529850-85c0542b-526b-4c4f-be37-6f12ea6a6a9b.png)

### Describe the behavior you expected

- no JavaScript exception error
- I didn't see any problems other than this error message; but it happens 100% of the time when restoring the window from maximized

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.05.0-daily+296 on Ubuntu 22.04.2.

**Comment by gtritchie** [comment]
Note: Found the underlying Electron issue while looking for something else: [[Bug]: Calling setBounds while listening to the window restore event crashes the main process #36705](https://github.com/electron/electron/issues/36705)
