### ISSUE TITLE
Unresponsive after installing "Spectra"

### ISSUE THREAD

**Issue by piiskop** [rstudio/rstudio#13038]
### System details

    RStudio Edition : Server
    RStudio Version : 
    OS Version      : Ubuntu 20.04 / 22.04
    R Version       : 4.2.3

### Steps to reproduce the problem

I wanted to use _Spectra_ from _BioManager_ and did the following things:

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Spectra")
```

The process took hours and once I could log in again, the system loads all the visible parts but none of them can be used - unresponsive.

### Describe the problem in detail

After installing _Spectra_, I cannot access RStudio Server anymore after logging in.

### Describe the behavior you expected

I expect that I can use RStudio Server after installing a package.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
After BiocManager installs packages, it asks the user whether they'd like to update any out-of-date packages; e.g.

```
Old packages: 'BiocManager', 'lattice', 'MASS', 'Matrix', 'survival'
Update all/some/none? [a/s/n]: 
```

Did you see that prompt? Did you respond to it?

**Comment by piiskop** [comment]
I remember a prompt like this. I responded with _a_.

I spent like eight hours solving the issue which I could use for making my report but I could not make it within the deadline because of that. I was also looking for an option for setting another project as the project that will be opened after logging in instead of the last used project and found zero options for that. Do you know, is it even possible? I even reset the session and renamed the _rstudio_ folder in my home folder in _.local/share_ and nothing helped. Suddenly, like after seven hours of searching and trying several options, the project opened without any files open. Once I opened the RMD file with the call for _Spectra_, RStudio Server became unresponsive again. Even the whole laptop was almost unresponsive and it has 23 GB of RAM. After reopening the project, RStudio Server did not put focus on that particular file but on another file, so I could work again. Then I renamed that file with the call for _Spectra_ and it opened without making anything unresponsive. So the name of the file was somehow eaten into an endless loop. And I could not rename the file outside RStudio Server because it had unsaved changes made over several hours.

**Comment by kevinushey** [comment]
I'm sorry for the trouble. I'm not sure why loading the Spectra package could cause these kinds of issues.

**Comment by piiskop** [comment]
This time it is not about _Spectra_ but something else. Once I log in, RStudio Server keeps eating RAM until it reaches 11 GB and then dies. It is another project. How can I configure RStudio Server to open another project so that I can work again? RStudio Server is useless now as it is impossible to do anything.
