### ISSUE TITLE
rstudio-server.service failing to start in RHEL-9.1

### ISSUE THREAD

**Issue by jagadeswar-devarasetti-dsw** [rstudio/rstudio#13051]
[root@MBIAZPRODAA bin]# sudo systemctl status  rstudio-server.service

× rstudio-server.service - RStudio Server

     Loaded: loaded (/usr/lib/systemd/system/rstudio-server.service; enabled; vendor preset: disabled)

     Active: failed (Result: exit-code) since Wed 2023-04-26 09:40:29 UTC; 3s ago

    Process: 125766 ExecStart=/usr/lib/rstudio-server/bin/rserver (code=exited, status=127)

        CPU: 1ms

 

Apr 26 09:40:29 MBIAZPRODAA systemd[1]: rstudio-server.service: Scheduled restart job, restart counter is at 5.

Apr 26 09:40:29 MBIAZPRODAA systemd[1]: Stopped RStudio Server.

Apr 26 09:40:29 MBIAZPRODAA systemd[1]: rstudio-server.service: Start request repeated too quickly.

Apr 26 09:40:29 MBIAZPRODAA systemd[1]: rstudio-server.service: Failed with result 'exit-code'.

Apr 26 09:40:29 MBIAZPRODAA systemd[1]: Failed to start RStudio Server.

(base) [root@MBIAZPRODAA bin]# cat /etc/os-release

NAME="Red Hat Enterprise Linux"

VERSION="9.1 (Plow)"

ID="rhel"

ID_LIKE="fedora"

VERSION_ID="9.1"

PLATFORM_ID="platform:el9"

PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"

ANSI_COLOR="0;31"

LOGO="fedora-logo-icon"

CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"

HOME_URL="https://www.redhat.com/"

DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"

BUG_REPORT_URL="https://bugzilla.redhat.com/"

 

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"

REDHAT_BUGZILLA_PRODUCT_VERSION=9.1

REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"

REDHAT_SUPPORT_PRODUCT_VERSION="9.1"

**Comment by jagadeswar-devarasetti-dsw** [comment]
Now i am getting below issue

(mchirpy) [root@MBIAZPRODAA ~]# sudo systemctl status rstudio-server.service

× rstudio-server.service - RStudio Server

     Loaded: loaded (/usr/lib/systemd/system/rstudio-server.service; enabled; vendor preset: disabled)

     Active: failed (Result: exit-code) since Wed 2023-04-26 13:30:53 UTC; 21min ago

    Process: 134128 ExecStart=/usr/lib/rstudio-server/bin/rserver (code=exited, status=1/FAILURE)

        CPU: 2ms

 

Apr 26 13:30:53 MBIAZPRODAA systemd[1]: rstudio-server.service: Scheduled restart job, restart counter is at 5.

Apr 26 13:30:53 MBIAZPRODAA systemd[1]: Stopped RStudio Server.

Apr 26 13:30:53 MBIAZPRODAA systemd[1]: rstudio-server.service: Start request repeated too quickly.

Apr 26 13:30:53 MBIAZPRODAA systemd[1]: rstudio-server.service: Failed with result 'exit-code'.

Apr 26 13:30:53 MBIAZPRODAA systemd[1]: Failed to start RStudio Server.

(mchirpy) [root@MBIAZPRODAA ~]# sudo systemctl start rstudio-server.service

Job for rstudio-server.service failed because the control process exited with error code.

See "systemctl status rstudio-server.service" and "journalctl -xeu rstudio-server.service" for details.

(mchirpy) [root@MBIAZPRODAA ~]# sudo systemctl is-enabled rstudio-server.service

enabled

**Comment by ronblum** [comment]
@jagadeswar-devarasetti-dsw Thank you for raising the issue! A few questions:
- What version of RStudio Server are you using?
- Was this working as expected in RHEL 9.0 by chance? 
- What was the latest versions of RStudio Server and RHEL that worked?

**Comment by jagadeswar-devarasetti-dsw** [comment]
Hi @ronblum 

rstudio server version used is rstudio-server-rhel-2023.03.0-386-x86_64.rpm
this is first time we are installing on RHEL 9.1

**Comment by Y055513** [comment]
> 现在我遇到了以下问题
> 
> （mchirpy）[root@MBIAZPRODAA ~]# sudo systemctl status rstudio-server.service
> 
> × rstudio-server.service - RStudio 服务器
> 
> ```
>  Loaded: loaded (/usr/lib/systemd/system/rstudio-server.service; enabled; vendor preset: disabled)
> 
>  Active: failed (Result: exit-code) since Wed 2023-04-26 13:30:53 UTC; 21min ago
> 
> Process: 134128 ExecStart=/usr/lib/rstudio-server/bin/rserver (code=exited, status=1/FAILURE)
> 
>     CPU: 2ms
> ```
> 
> 4 月 26 日 13:30:53 MBIAZPRODAA systemd[1]: rstudio-server.service: 计划重启作业，重启计数器为 5。
> 
> 4 月 26 日 13:30:53 MBIAZPRODAA systemd[1]: 已停止 RStudio 服务器。
> 
> 4 月 26 日 13:30:53 MBIAZPRODAA systemd[1]: rstudio-server.service: 启动请求重复太快。
> 
> 4 月 26 日 13:30:53 MBIAZPRODAA systemd[1]: rstudio-server.service: 失败，结果为“退出代码”。
> 
> 4 月 26 日 13:30:53 MBIAZPRODAA systemd[1]: 无法启动 RStudio 服务器。
> 
> （mchirpy）[root@MBIAZPRODAA ~]# sudo systemctl start rstudio-server.service
> 
> rstudio-server.service 的作业失败，因为控制进程退出并显示错误代码。
> 
> 有关详细信息，请参阅“systemctl status rstudio-server.service”和“journalctl -xeu rstudio-server.service”。
> 
> （mchirpy）[root@MBIAZPRODAA ~]# sudo systemctl is-enabled rstudio-server.service
> 
> 已启用

**Comment by Y055513** [comment]
I encountered the same issue as you. Have you resolved it?
