### ISSUE TITLE
Housekeeping - Pin Quarto and Panmirror

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#13053]
* Pin Quarto to the 1.3.340 release
* Pin Panmirror (visual editor) to the `release/rstudio-mountain-hydrangea` branch
* Upload Quarto 1.3.340 to S3 so it is archived and available for rebuilds

**Comment by ronblum** [comment]
Verified that Quarto is fixed at 1.3.340 and has not been changing (at of RStudio Desktop 2023.05.0-daily+325).
