### ISSUE TITLE
Posit icon for IDE user guide is incorrect.

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#13056]
In the nav bar, our guides use the posit icon sans "posit" text:

<img width="339" alt="2023-04-26_14-30-30" src="https://user-images.githubusercontent.com/31460023/234669917-109968cb-8cd4-4058-a544-c5f143ebebc4.png">

<img width="339" alt="2023-04-26_14-31-01" src="https://user-images.githubusercontent.com/31460023/234669927-d3ff7426-332a-4068-8f30-f23b69d6324c.png">

**Comment by ronblum** [comment]
Verified in 
- RStudio User Guide 2023.05.0 revision 24, published 2023-05-03
