### ISSUE TITLE
Making fonts of Japanese characters sans-serif in Files Pane in electron versions of RStudio Desktop

### ISSUE THREAD

**Issue by k1-ito** [rstudio/rstudio#13063]
### System details

    RStudio Edition : Desktop
    RStudio Version : any electron versions 
    OS Version      : Windows 10/11 Pro 22H2
    R Version       : 4.2.3 and later

### Steps to reproduce the problem

Use an electron version of RStudio Desktop.

### Describe the problem in detail

The font of Japanese characters in Files Pane is serif, inconsistent with Latin characters.
 
For example:
the Qt version of RStudio-2022.07.2+576 
![2023-04-28 (1)](https://user-images.githubusercontent.com/121043466/235075332-d7380985-d2e1-4ea6-849c-7134887db806.png)
Both Latin and Japanese fonts are sans-serif.

RStudio-2023.03.0+386
![2023-04-28 (3)](https://user-images.githubusercontent.com/121043466/235075281-d5b6679c-979d-45b5-be85-5955103deb4e.png)
In the electron version of RStudio Desktop, the Japanese font is serif,
while the Latin font is sans-serif as in Qt versions of RStudio Desktop.

### Describe the behavior you expected

In any electron version of RStudio Desktop, the font of Japanese characters in Files Pane is also sans-serif.

**Comment by ronblum** [comment]
@k1-ito Thank you for raising this! We'll review it as we continue development of RStudio.
