### ISSUE TITLE
Piped functions not showing first argument

### ISSUE THREAD

**Issue by millermc38** [rstudio/rstudio#13065]
Hello,

**Problem:**

When I pipe any function, it does not show the first argument.

I get why it does this--it's just automatically passing to the first arg. This is also why I didn't mark this as a bug. However, I think this is pretty inflexible because I often want to specify the argument anyways for readability or pass to an argument that is NOT the first argument.

**Reproducible Example**

For example, if I do the below, the autocomplete offers me just "file" and not "x" when I go to do autocomplete for the `write()` function:
```
matrix(1:10, ncol = 5)|>write()
```

**Solution:** 

I would like to go back to the old autocomplete where it shows me all of the arguments when I hit tab (the hotkey I have assigned to show the arguments), or even better, give user the option to pick.  Any help is appreciated.

**Session Details:**

RStudio:

I am using a desktop and running everything locally on my machine--
RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

R:

```                      
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.2                              
year           2022                             
month          10                               
day            31                               
svn rev        83211                            
language       R                                
version.string R version 4.2.2 (2022-10-31 ucrt)
nickname       Innocent and Trusting    
```

**Comment by millermc38** [comment]
Okay, looking forward to it, thank you!

**Comment by millermc38** [comment]
At the risk of being a pest, I wanted to make a gentle plug for moving this up on the priority list! Not having accessing to the first argument impacts the efficiency of just about every line of coding users do. Autocomplete effectively doesn't  exist in RStudio at this time, even though one can see the arguments!

**Comment by ronblum** [comment]
Triage: Reconsider this for Desert Sunflower, as this is a regression that was mismarked.

**Comment by millermc38** [comment]
My hero!!! Thank you.

**Comment by millermc38** [comment]
What's the saying? Never meet your heroes? Haha JK--we're all very grateful for RStudio, and I'm sure it's hard to decide what to address and what not to.

Thanks at least for the consideration.

**Comment by olivroy** [comment]
Don't know if it is related, but not showing the first argument of `mean()`, `x`
![image](https://github.com/rstudio/rstudio/assets/52606734/22c7ec25-f155-491e-9f56-e104d74d3dab)
this is another frame. the pipe should only hide `.data`, not `x`

**Comment by kevinushey** [comment]
I'm not seeing this with a recent daily (RStudio 2023.09.0-daily+332 "Desert Sunflower" Daily); I wonder if this was fixed?

<img width="335" alt="Screenshot 2023-08-17 at 2 06 06 PM" src="https://github.com/rstudio/rstudio/assets/1976582/2873eaeb-ba24-4c04-81fb-541db5e73dc2">

Or is there something else I'm missing to reproduce the issue?

@olivroy, I suspect the issue you're reporting may be slightly different -- would you like to file a new issue?

**Comment by kevinushey** [comment]
Putting this in Test just so we can double-check if the issue as reported still occurs. If it does, IMHO we can probably punt to the next release still.

**Comment by jonvanausdeln** [comment]
I am still seeing the issue in [2023.12.0-daily+268](https://dailies.rstudio.com/version/2023.12.0-daily+268) on Windows 11

![image](https://github.com/rstudio/rstudio/assets/6433789/0515e2c7-4f2f-4e1d-b1c9-c8da56bfc246)

**Comment by olivroy** [comment]
Somehow related to #13611  (On RStudio 2023.12.0+274, on mac, I see.)

If on the first line (tidyr not loaded) (data is the first argument of `pivot_longer()`

![Capture d’écran, le 2024-02-01 à 9 08 39 a m](https://github.com/rstudio/rstudio/assets/52606734/a309dad7-6bd5-4626-a8d5-90dbb134ae41)

![image](https://github.com/rstudio/rstudio/assets/52606734/6569c656-7de0-4601-9141-c7c61c9fc0df)


But I would argue it is best not to show the first argument on top, as 90% of piped operations, you will not want the first argument for autocompletion.

**Comment by millermc38** [comment]
[olivroy](https://github.com/olivroy), that's true.  I'm definitely the odd duck out when it comes to this topic, as I regularly fill in the first argument (unless it is *really* banal like ".data"). Upon reflection, I could not determine why that is! I think it is for cases like the following, which don't naturally take a first argument from the pipe, but need one to be explicitly named (I can't see ".x", just ".f")

```
iris%>%
  mutate(test=map())
```

Certainly, there are functions we all probably use with modest enough regularity that it helps to see the first function...though perhaps somehow "set aside" as [olivroy](https://github.com/olivroy) points out.

**Comment by olivroy** [comment]
@millermc38 not seeing the first argument in the nested call is exactly what #13611 is: 

I do see the `.x` and `.f` argument, when only a blank line precedes the call.
![image](https://github.com/rstudio/rstudio/assets/52606734/0151910b-6d74-47d1-90ca-c49699b94657)
Not otherwise
![image](https://github.com/rstudio/rstudio/assets/52606734/6a6f5303-9c55-4a5c-9dc1-24c896fd6e1a)

**Comment by millermc38** [comment]
Sorry for the redundancy! I did notice that about an hour after I posted--oops.

**Comment by millermc38** [comment]
How strange! I have a computer with 4.2.2 for which all the arguments show when I hit tab inside the parentheses of `write()`, as desired. But this is the same version of R I had I issues with. It's a brand new computer, but the highest version of R I can get on it is 4.2.2. In fact, the entire printout from `R.version` is exactly the same as my original post. On my machine with 4.4.0, I still have the issue though. I'm not sure what to make of this.

`matrix(1:10, ncol = 5)|>write()`


`
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          4.0                              
year           2024                             
month          04                               
day            24                               
svn rev        86474                            
language       R                                
version.string R version 4.4.0 (2024-04-24 ucrt)
nickname       Puppy Cup 
`

**Comment by olivroy** [comment]
@millermc38 Is it the case with all lines context? For me, I still encounter the inconsistency.

**Comment by millermc38** [comment]
all lines context? Could you clarify? I was thinking maybe you mean indenting first as in below, in which case yes actually auto complete does not show when I do this. And I'm starting to put lots of args on their own line, so I guess it's still broken:

For a newly installed version of R 4.2.2 on a new machine as of yesterday:
```
matrix(1:10, ncol = 5)|>write() # tab shows me all args!
```

```
matrix(1:10, ncol = 5)|>write(
# :( No autocomplete options when hitting tab
)
```

**Comment by kevinushey** [comment]
Coming back to this. I think the principle here is that the two following cases should give the same completions results:

```r
# no pipe
write(mtcars, |)

# using pipe
mtcars |> write(|)
```

And indeed, this is what I see (and RStudio has had logic to filter out "already-used" arguments from the completion list for some time).

<img width="733" alt="Screenshot 2024-08-26 at 3 48 34 PM" src="https://github.com/user-attachments/assets/1379266c-5ae6-428c-92f9-e07aaf131021">

This dropping of already-used arguments comes from here:

https://github.com/rstudio/rstudio/blob/914c595a243671804c8f04cfd0276ad1509e6bdf/src/cpp/session/modules/SessionRCompletions.R#L1027-L1029

I don't think we can change the default behavior at this point, but we could consider adding a user preference to control if this happens.

---

There is apparently a separate inconsistency where, if you're requesting completions for the first statement in the document, then we don't do that.

<img width="385" alt="Screenshot 2024-08-26 at 3 50 43 PM" src="https://github.com/user-attachments/assets/13d615ce-4e17-4f2c-9554-f2e438679104">

<img width="361" alt="Screenshot 2024-08-26 at 3 50 37 PM" src="https://github.com/user-attachments/assets/f9807e68-b5ce-4f83-845b-d67bb2447c5c">

**Comment by ronblum** [comment]
Going back to the original example
```
matrix(1:10, ncol = 5)|>write()

```

I'm still not getting `x` as an option:

![pipe_complete](https://github.com/user-attachments/assets/279368b2-5c7f-417b-bbb1-f6f2b6495da6)

Checked in RStudio Desktop 2024.10.0-daily+223 on Windows 11.

**Comment by ronblum** [comment]
Never mind--I didn't check the new setting. Confirmed that all show up when the setting is checked, using multiple examples from above. All set!
