### ISSUE TITLE
Update IDE user guide to align with other guides

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#13067]
Currently, we aren't really utilizing the `subtitle` field for our guide descriptions. 

This is a quarto built-in feature and I think that it looks more professional than having us repeat the "guide type, i.e., User Guide" in that field.

Additionally, our welcome pages aren't templatized/standardized so we should have similar verbiage and sections across all of the RStudio and Workbench Guides.

Task list:
    - [x] Intended audience
- [x] User guide
    - [x] Subtitle
    - [x] Description
    - [x] About this guide
    - [x] Intended audience

Companion issue https://github.com/rstudio/rstudio-pro/issues/4592

**Comment by ronblum** [comment]
Verified in RStudio User Guide 2023.05.0 revision 24.
