### ISSUE TITLE
pillar-formatted columns display poorly in data viewer

### ISSUE THREAD

**Issue by banbh** [rstudio/rstudio#13077]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.03.0+386 "Cherry Blossom" Release
    OS Version      :  Windows 10
    R Version       :  4.3.0

### Steps to reproduce the problem
Execute `view(tibble(x = num(seq(-1, 1, len = 5), scale = 100, label = '%')))`.

### Describe the problem in detail
The data viewer displays ANSI codes for negative values.

### Describe the behavior you expected
I expected the data viewer to display only the numerical data.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@banbh Thank you for raising this! This also happens when running this in R outside of RStudio:
<img width="239" alt="r_view" src="https://user-images.githubusercontent.com/31009952/235722617-b9989adb-37f6-46ce-af9d-81151ae40c6d.png">

Since this is a problem with R or possibly `tibble`, this should be filed with the R project or the `tibble` package.

**Comment by banbh** [comment]
@ronblum , your comment about `tibble`s was very interesting since `print(data.frame(x = num(seq(-1, 1, len = 5))))` appears as follows in the console:

```
                                                     x
1                                 -\033[31m1\033[39m  
2 -\033[31m0\033[39m\033[31m.\033[39m\033[31m5\033[39m
3                                                  0  
4                                                  0.5
5                                                  1  
```
which seems like a similar (or identical) problem. However, it's not clear (to me) where to report this. I think I'm lacking enough background in how these different parts of the R ecosystem divide responsability. For instance, perhaps it's a `pillar` problem?
