### ISSUE TITLE
Source editor: the fallback font of Japanese characters in the Electron versions of Rstudio Desktop would look nicer when a different font is used than MS Gothic

### ISSUE THREAD

**Issue by k1-ito** [rstudio/rstudio#13070]
### System details

    RStudio Edition : Desktop
    RStudio Version : any electron versions 
    OS Version      : Windows 10/11 Pro 22H2
    R Version       : 4.2.3 and later

The Electron versions of RStudio Desktop use `MS Gothic` as the fallback font of Japanese characters, while the Qt versions use `Meiryo`.
And Windows 10/11 also include a somewhat similar font `Yu Gothic`. 

I feel `Meiryo` and `Yu Gothic` look nicer than `MS Gothic` because, with regard to their weight and smoothness, `Meiryo` and `Yu Gothic` are more consistent with typical fonts for coding such as `Lucida Console`, `Fira Code` and so on. 

So I would appreciate if the fallback font is changed to `Meiryo` or `Yu Gothic`.
Or, if the CJK font can be set by users separately from the Latin font, it would be the best.

### Steps to reproduce the issue
1. use an electron version of RStudio Desktop.
2. choose an editor font in Tools -> Global Option -> Appearance -> Editor font. (I use `Fira Code` as an example.)
 
a sample text:
吾輩は猫である。名前はまだない。どこで生まれたかとんと見当がつかぬ。
I'm a cat. I don't have my name yet. I don't know at all where I was born.

RStudio-2023.03.0+386:
The fallback font is `MS Gothic`.
![Electron03](https://user-images.githubusercontent.com/121043466/235303193-2f4654d9-a879-4728-a1b5-d3825c63fe94.jpg)

*cf.* the Qt version of RStudio-2022.07.2+576:
The fallback font is `Meiryo`.
![Qt03](https://user-images.githubusercontent.com/121043466/235303190-e9e7beb8-895b-4021-b33a-561e30c32156.jpg)

**Comment by kevinushey** [comment]
See also: https://www.electronjs.org/docs/latest/api/browser-window

We can set the 'defaultFontFamily' within the BrowserWindow object's webPreferences.

**Comment by ronblum** [comment]
@k1-ito Thank you for the suggestion! We'll consider it as we continue to develop RStudio.
