### ISSUE TITLE
No hyperlinks or colors when using run tests on the active file

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#13088]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03+386 / 2024.04.0+558
    OS Version      :  Windows
    R Version       :  4.2.3 / 4.3.2

### Steps to reproduce the problem

Open a package in Rstudio

Open a test file (with a failing test for hyperlinks)

Use the run tests button on the source file (top right corner)

### Describe the problem in detail

In the Build Pane, colors and hyperlinks don't show up. It is all gray,
![image](https://user-images.githubusercontent.com/52606734/236053431-85ab0a7f-3f80-4d03-a242-8bb74a41c93b.png)

Edit: It is also a problem [Document using the Ctrl + Shift + D](https://github.com/search?q=repo%3Arstudio%2Frstudio+roxygenize-package&type=code) keybinding. and I am not seeing this on Mac.

### Describe the behavior you expected

Similar to when when using Ctrl + Shift + T, for Test (test all files), I would expect to see colors and have cli hyperlinks enabled, when I am testing a single file. With the run Tests button in a test file.

Screenshot when using Ctrl + Shift + T.
![image](https://user-images.githubusercontent.com/52606734/236053950-6e0ea920-9c3e-4c7c-9720-b87a2f13e504.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Edit: also tracked in https://github.com/r-lib/testthat/issues/1561#issuecomment-1629770700.

Can be solved by setting  (workaround)
```r
Sys.setenv(RSTUDIO_CLI_HYPERLINKS= TRUE)
Sys.setenv(RSTUDIO = '1')
```

According to https://github.com/rstudio/rstudio/pull/11040/files#r862751287, AsyncRProcess::start() sets the other env vars.

https://github.com/rstudio/rstudio/issues/11969#issuecomment-1624308826

Also reported in https://github.com/rstudio/rstudio/issues/11241

This once worked: as shown in 2022.07.0 screenshot https://github.com/rstudio/rstudio/issues/11697

**Comment by ronblum** [comment]
@olivroy Thank you for raising this! Can you provide a minimal reproducible code sample that I can try out to reproduce? I transcribed some of the code from the screenshots, but I'm not sure that what I've tried is triggering what you're seeing.

**Comment by olivroy** [comment]
Hi,

```r
usethis::create_project("~/temp")
✔ Writing 'temp.Rproj'
✔ Adding '^temp\\.Rproj$' to '.Rbuildignore'
✔ Adding '^\\.Rproj\\.user$' to '.Rbuildignore'
✔ Opening 'C:/Users/RoyO/temp/' in new RStudio session
# In new package project
library(devtools)
use_r("min-fun")

• Modify 'R/min-fun.R'
• Call `use_test()` to create a matching test file
```

`min-fun.R` is just


```r
f <- function(x) {
  x**2
}
```

After that run

```r
usethis::use_test()
✔ Adding 'testthat' to Suggests field in DESCRIPTION
✔ Setting Config/testthat/edition field in DESCRIPTION to '3'
✔ Creating 'tests/testthat/'
✔ Writing 'tests/testthat.R'
✔ Writing 'tests/testthat/test-min-fun.R'
• Modify 'tests/testthat/test-min-fun.R'
```

`tests/testthat/test-min-fun.R` is

```r
test_that("multiplication works", {
  expect_equal(f(2), 4)
})

test_that("failing test works test", {
  expect_equal(f(2), 5)
})
```

After that, I run tests (with Ctrl + Shift + T) (getting what I expect)
![image](https://user-images.githubusercontent.com/52606734/236495579-1e1e91fb-ef0c-435a-89a0-6f04ef71a691.png)

But using the test file button, I don't get the colored output with links in the build pane.
![image](https://user-images.githubusercontent.com/52606734/236495783-d959954a-ad71-4afc-ae97-b5e43b004c48.png)

**Comment by olivroy** [comment]
Thanks so much for the fix! This may seem small, but it is a big quality of life improvement for me!

Documenting also shows color now, in case this is worth adding to NEWS

I will let QA make the final call and will test!
