### ISSUE TITLE
No output from Python loops until the loop completes

### ISSUE THREAD

**Issue by tomwagstaff-opml** [rstudio/rstudio#13089]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.03.0
    OS Version      :  Windows 10
    R Version       :  4.2.3

### Steps to reproduce the problem
```
import time
for i in range(5):
  print(i)
  time.sleep(1)
```

### Describe the problem in detail
When running a Python loop in REPL, there is no output to the console until the entire loop completes. You can see this by running the code block above - the numbers 0 - 4 are printed simultaneously at the end of the run.

### Describe the behavior you expected
Print 0, wait 1 second, print 1, and so on....

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tomwagstaff-opml Thank you for raising this! I can also reproduce this in RStudio Desktop on MacOS 13.4. We'll review this as we continue development of RStudio's Python support.

**Comment by tomwagstaff-opml** [comment]
Just one additional comment on what may be a related issue. I've found that sometimes when running a loop that encounters an error, rather than stopping at the error, I get some feedback from later in the loop once it concludes. Again - order of operations not as expected (or at least what the user can see).
