### ISSUE TITLE
Insert Roxygen comment for current function does not respect indentation

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#13081]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03+386
    OS Version      : Windows 10
    R Version       : 4.2.3

### Steps to reproduce the problem

* Create a R function in an indented R script
* Go in the function definition.
* Go to the line with w
* Press the shortcut Ctrl + Alt + Shift + R to insert Roxygen comment

```r

if (FALSE) {
  f <- function(w) {
    w
  }
}
```

### Describe the problem in detail

After clicking on the shortcut, I get

```r
if (FALSE) {
#' Title
#'
#' @param w 
#'
#' @return
#' @export
#'
#' @examples
  f <- function(w) {
    w
  }
}
```

The tags do not respect indentation, I have to use styler to indent properly

### Describe the behavior you expected

I would expect that inserting Roxygen comments respect the current indentation.

Like so,

```r
if (FALSE) {
  #' Title
  #'
  #' @param w
  #'
  #' @return
  #' @export
  #'
  #' @examples
  f <- function(w) {
    w
  }
}
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@olivroy Thank you for raising this! We'll review it as we continue to develop RStudio
