### ISSUE TITLE
ggplot2 warnings messages in Notebook output show weird characters

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#13080]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03+386
    OS Version      : Windows 10
    R Version       : 4.2.3

### Steps to reproduce the problem

* Create a quarto document.
* Make sure the inline chunk output in on.
* Put a chunk where you get a message from ggplot2

````
---
title: "doc"
format: html
editor: visual
---


```{r}
library(ggplot2)
ggplot(mtcars, aes(vs)) + geom_histogram()
```
````

### Describe the problem in detail

The cli symbols for warnings or messages show up as

 [38;5;232m`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.[39m

This may be an encoding issue in my system.

![image](https://user-images.githubusercontent.com/52606734/235684734-aada4764-f57c-4c5e-b31d-9c3be29f3684.png)

I get the same problem with and without visual editor enabled

### Describe the behavior you expected

Not show weird symbols.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

edit: I think this is because ggplot2 switched from base warnings to rlang / cli. There is some styling that RStudio does for the base warning, but it doesn't account for the cli inline styling characters in notebook mode.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@olivroy Thank you for raising this! I can reproduce similar behavior
- in RStudio 2022.07.2+576 and 2023.05.0-daily+320 on MacOS 13.4
<img width="559" alt="macos" src="https://user-images.githubusercontent.com/31009952/235720161-5cfce24d-b07a-417a-82b7-c661b9b6b4e1.png">

in RStudio 2023.05.0-daily+320 on Ubuntu 22
<img width="526" alt="ubuntu22" src="https://user-images.githubusercontent.com/31009952/235720367-711c4f68-269a-4dba-b2ed-1c2893888077.png">

We'll review this as we continue development of RStudio.

Note: This only occurs when running the chunk code in the Rmd doc. Knitting works fine.

**Comment by olivroy** [comment]
Can no longer see this in the latest daily 2024.04.0+544 

Output seems to go to a different tab, and outputs normally.
![image](https://github.com/rstudio/rstudio/assets/52606734/b7d5b1c4-de17-40d1-a9d4-951c494c592f)

**Comment by ronblum** [comment]
Verified as well, in my case on MacOS 14.4.
