### ISSUE TITLE
Console stops executing any code with R 4.3 underscores

### ISSUE THREAD

**Issue by jmcvw** [rstudio/rstudio#13091]
Bit of a weird one.

As you know, R v4.3 allows indexing values from an object piped into an underscore.
However, when I write a function as below, the console stops executing any code.
It does not freeze or crash - you can still type and use the IDE as normal, there's just no execution.

Example code

```
f <- function() {
  1:3 |>
    _[1]
}
```

The image below illustrates the behaviour.
After opening R the console does nothing - you can see in the image that entering a number produces no output.
After restarting R (from the Session menu) the console begins responding normally.
All that needs to happen for the weirdness to begin again, is to click anywhere in the script pane, then back in the console pane, where you can see enering a number does nothing.

A few other details. The issue seems somewhat inconsistent in an unsaved file, but reproduces 100% of the time if the script is saved.
Occaisionally, the console stops even producing a prompt `>`, as happens in the image towards the bottom of the console.
When this occurs, it is always necessary to force quit RStudio.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43386915/236328332-b1c7336c-4799-4c2f-941a-06e180e13aa5.png">

### System details

RSudio version 2023.3.0.386
R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: GB
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.3.0  tools_4.3.0    
[3] rstudioapi_0.14

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! I was able to reproduce locally; the request log shows calls to `lint_r_source_document` are stacking up:

<img width="384" alt="Screenshot 2023-05-04 at 2 48 38 PM" src="https://user-images.githubusercontent.com/1976582/236337333-7e3a0536-8e2b-4008-b577-3a25bfd35e85.png">

so perhaps the RStudio linter is getting tripped up by code of this form.

As a workaround, you can disable R diagnostics, in Tools -> Global Options... -> Code -> Diagnostics:

<img width="607" alt="Screenshot 2023-05-04 at 2 50 02 PM" src="https://user-images.githubusercontent.com/1976582/236337556-a28bfc1b-49eb-44d8-908e-272a6184ea2b.png">

**Comment by Fred-Wu** [comment]
I think this may also be the source of issue reported in #13084
