### ISSUE TITLE
ggplot2 warning messages in notebook outputs are garbled

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#13090]
### System details

    RStudio Edition : Any
    RStudio Version : 2023.03.0 Build 386

### Steps to reproduce the problem

Create a ggplot2 that emits warnings.

### Describe the problem in detail

The warnings include garbled output that is the result of ANSI escape sequences not being processed properly.

![image](https://user-images.githubusercontent.com/470418/236318567-b1cc9fa3-bf1e-4812-97ab-c9b6af567646.png)

### Describe the behavior you expected

These escape sequences should be either removed or rendered to safe HTML.

**Comment by ronblum** [comment]
@jmcphers I think this is the first time that I've closed one of your bugs as a duplicate! 🙂
