### ISSUE TITLE
Multiple empty .R script files/tabs showing up after closing and reopening project

### ISSUE THREAD

**Issue by fernapx4** [rstudio/rstudio#13095]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0 Build 386
    OS Version      : Windows 10 Enterprise 19044.2846
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Start a new RStudio project.
2. Open at least two Source columns via the Pane Layout.
3. Save .R scripts in each of the Source Panes.
4. With the saved .R scripts open, close RStudio.
6. Reopen the project by double-clicking on the .Rproj file.

### Describe the problem in detail

Upon reopening a Project, one of the Source pane columns has dozens of empty .R script files, with alternating names "Untitled1.R" and "Untitled2.R" files. The saved .R scripts are also present, but the tab bar is cluttered with the empty Untitled scripts.

### Describe the behavior you expected

Show only the files/tabs that were open upon closing RStudio and do not add new, empty, untitled files.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fernapx4 Thank you for raising this!

@jonvanausdeln Can you try this? It works correctly for me in RStudio Desktop 2023.05.0-daily+331, so I wonder if it's a problem on Windows.

**Comment by fernapx4** [comment]
Issue #13158 may be a duplicate of this. When I have two code panes open, the issue sometimes also manifests with empty Untitled1.R and Untitled2.R files in both panes. Several empty tabs with the names of data.frames open in the previous session (i.e., via View(df)) also appear, even if these view tabs were closed prior to closing RStudio.

**Comment by Kairi703** [comment]
I have this same issue with RStudio 2023.06.1+524 and R 4.0.2

**Comment by audricvigier** [comment]
Same issue here with RStudio 2023.09.0+463 "Desert Sunflower" on Windows 10 with R 4.1.2 and 4.2.3
