### ISSUE TITLE
rsession high CPU usage when idle under rstudio server on Ubuntu VM after loading a large list

### ISSUE THREAD

**Issue by mhfathom** [rstudio/rstudio#13103]
**Server**
OS: Ubuntu Mate 22.04.2 LTS, 16-core, 64GB
R: 4.3.0
rstudio server (open source): rstudio-server-2023.03.0-386-amd64.deb
**Client**
rstudio server accessed remotely via HTTP from MacOS 11.7 with Chrome 113.0 

**Problem**
executing the following line in a new rstudio session causes the system to become slow to respond and the rsession process (using top) to remain at >80% CPU usage.
`x <- as.list(1:1e6)
`

Deleting the list restore CPU usage to <1%:
`rm(x)
`

This problem does not occur when the statement is executed using R in the terminal. Also it does not occur when loading a large vector instead e.g.
`x <- rnorm(8e6)
`

**Comment by kevinushey** [comment]
Thanks; I suspect this has already been resolved in the latest [daily builds](https://dailies.rstudio.com) -- can you test and confirm?

**Comment by MatthieuStigler** [comment]
I had same a similar problem on a Ubuntu 22.04 server, and was also finding CPU of 80% with the simple  `x <- as.list(1:1e6)`. Upgrading to daily build 334 seems to work. 

Which build are you exactly referring to @kevinushey, the _latest_ as in 334? It seems for Ubuntu 20.04, only build 331 (2023-05-08) is available? Do you expect that one to work too? Thanks!

**Comment by ronblum** [comment]
@MatthieuStigler Thank you for checking, and noting the missing Ubuntu 20.04! The page is updated—there are now builds 333 and 334 available.

@mhfathom It appears that this is fixed—if you're interested in trying out [the latest daily builds](https://dailies.rstudio.com/) of the upcoming release, they're available at https://dailies.rstudio.com/. Note that these are meant for testing purposes only, not production work.

Also, @mhfathom when you filed the bug report, do you remember [which button you pressed](https://github.com/rstudio/rstudio/issues/new/choose)? GitHub is supposed to automatically tag bug and enhancement reports with the appropriate labels, but sometimes it doesn't and I'm trying to figure why it's misbehaving sometimes.

**Comment by MatthieuStigler** [comment]
thanks @ronblum ! 

About _Note that these are meant for testing purposes only, not production work_: noting that the "super-high CPU for no reason" problem is critical and prevents using v2023.03.0+386 in production (all users were complaining about Rstudio being super slow, we had to hastily move to the daily build), is there any updated production version scheduled soon?  Thanks!

**Comment by mhfathom** [comment]
Thank you all - I confirm that this is fixed in build 334.

@ronblum I filed a new issue, I clicked on the button for bug report.

**Comment by ronblum** [comment]
@MatthieuStigler Excellent question. We're intentionally careful not commit to a specific date because with all of the changes and updates we introduce throughout the development cycle, we'll sometimes find an issue near the end that must be fixed and can hold up the release. But pulling the curtain aside a little bit, we've been targeting this release for the end of May, so hopefully (very likely) it'll be live by the end of month or early June. However, pay no attention to the man behind the curtain. 😄 

@mhfathom Thank you for verifying, and for the info of how you created the issue, which is the way it's supposed to work. Darn, GitHub isn't 100% reliable in applying the "new" tag. Perhaps it's a known GitHub bug—I've got to investigate further.

**Comment by ronblum** [comment]
Verified in Posit Workbench 2023.05.0-daily+334.pro3 on Ubuntu 20.04.5.
- In 2023.03.0, CPU reached 100%, though I had to up the data object to 1e7. Eventually the IDE became unusable
- In 2023.5.0, CPU hovered around 0.3% and continued to work.

**Comment by MatthieuStigler** [comment]
hi @ronblum 

I see there is a `2023.03.1` update, but I don't see this issue mentioned in the release note (https://docs.posit.co/ide/news/#rstudio-2023.03.1)... I assume then the production version `2023.03.1`  also has the same issue?

Thanks!

**Comment by kevinushey** [comment]
Re-opening to remind myself to update NEWS related to the associated change.

**Comment by mikebessuille** [comment]
@kevinushey i believe there are no more code changes for this, just a news file change right?
