### ISSUE TITLE
RStudio terminal does not find packages in R bash files

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#13104]
Hello,

With the help of the **optparse** package, I created a R bash file. [The same at this one](https://laustep.github.io/stlahblog/posts/gifskiBash.html) but on Linux.

It works fine. Except when I run it from the RStudio terminal: I get the error message *library optparse not found*.

### System details

    RStudio Edition : Desktop

    RStudio Version : RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

    OS Version      : Linux Mint

    R Version       :  4.3.0

### Steps to reproduce the problem

1. Save this file under the name **mygifski.R**:

```r
#!/usr/bin/env Rscript
suppressPackageStartupMessages(library("optparse"))
suppressPackageStartupMessages(library("gifski"))

option_list <- list( 
  make_option(
    "--frames", type = "character", 
    help = "png files given by a glob (e.g. pic*.png)"
  ),
  make_option(
    "--fps", type = "integer", default = 20L,
    help = "frames per second (default 20)"
  ),
  make_option(
    c("-l", "--loop"), type = "integer", default = 0L, 
    help = "number of loops, 0 for infinite (the default)",
    metavar = "number"
  ),
  make_option(
    c("-s", "--size"), type = "character", default = "512x512", 
    help = paste0(
      "size of the gif given in the form WxH where W is the width in pixels ", 
      "and H is the height in pixels (default 512x512)"
    ),
    metavar = "WxH"
  ),
  make_option(
    c("-b", "--backward"), action = "store_true", default = FALSE, 
    help = "loop forward and backward"
  ),
  make_option(
    c("-o", "--output"), type = "character", default = "animation.gif", 
    help = "output gif file (default animation.gif)", 
    metavar = "output.gif"
  )
)

opt <- parse_args(OptionParser(
  option_list = option_list, prog = "mygifski.R"
))

# check options are correct
size_ok <- grepl("^\\d.*x\\d.*$", opt$size)
if(!size_ok)
  stop("Invalid 'size' option.")
if(opt$fps <= 0)
  stop("Invalid 'fps' option.")
if(opt$loop < 0)
  stop("Invalid 'loop' option.")
png_files <- Sys.glob(opt$frames)
if(length(png_files) == 0L)
  stop("Invalid 'frames' option.")

# if the user chooses the 'backward' option we duplicate the files 
#   in a temporary directory
if(opt$backward){
  npngs <- 2L * length(png_files)
  fmt <- paste0("pic%0", floor(log10(npngs) + 1), "d.png")
  new_png_files <- file.path(tempdir(), sprintf(fmt, 1L:npngs))
  file.copy(c(png_files, rev(png_files)), new_png_files)
  png_files <- new_png_files
}

# get width and height
wh <- as.numeric(strsplit(opt$size, "x")[[1L]])

# a function to avoid some printed messages
quiet <- function(x) {
  sink(tempfile())
  on.exit(sink())
  invisible(force(x))
}

# run gifski
quiet(gifski(
  png_files = png_files,
  gif_file = opt$output,
  width = wh[1L],
  height = wh[2L],
  delay = 1/opt$fps,
  loop = ifelse(opt$loop == 0L, TRUE, opt$loop)
))

cat("Output written to", opt$output, "\n")
```

2. Make it executable:

```
chmod ug+x mygifski.R
```

3. Try it in a RStudio terminal.

### Describe the problem in detail

The bash file does not work in the RStudio terminal; it does not find the packages.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@stla Thank you for raising the issue! I'm working on trying to reproduce it. Two things to note:
1) We technically don't support Mint, although as you've probably experienced, RStudio Desktop usually works on it. So I'm going to test it on Ubuntu.
2) We're about to drop support for Ubuntu 18—see [the support matrix](https://posit.co/about/platform-support/) at https://posit.co/about/platform-support/ —as the vendor standard support is EOL.

**Comment by ronblum** [comment]
@stla No luck—when I run the script, I get the error below. Any suggestions?

>$ ./mygifski.R 
Error in path.expand(paths) : invalid 'path' argument
Calls: Sys.glob -> path.expand
Execution halted
$ Rscript mygifski.R 
Error in path.expand(paths) : invalid 'path' argument
Calls: Sys.glob -> path.expand
Execution halted

**Comment by stla** [comment]
Please try `mygifski.R -h`, you should get the help. The command `mygifski.R` alone throws an error, that's normal.

Outside of RStudio that perfectly works.

Mint is highly similar to Ubuntu.

**Comment by kevinushey** [comment]
What does `.libPaths()` report in each case? Most likely the library paths being used differ for some reason.

**Comment by stla** [comment]
@kevinushey Good thought!

If I run `Rscript -e ".libPaths()"` in an external terminal, I get `"/home/stla/R/x86_64-pc-linux-gnu-library/4.3"`. But if run the same command in a RStudio terminal, I get `"/home/stla/R/x86_64-pc-linux-gnu-library/4.2"`. That explains the problem. However I use R-4.3.0 in RStudio.
