### ISSUE TITLE
Don't initialize python from restored environment null pointer

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13109]
See reticulate issue https://github.com/rstudio/reticulate/issues/710 and pull request #13108.

Triage: This is checked into main, so I marked this as Mountain Hydrangea.

**Comment by jonvanausdeln** [comment]
Verified on desktop 2023.05.0-daily+358
Windows 11, Ubuntu 22

There is no longer a prompt if the system has python already installed and available.

**Comment by daattali** [comment]
Will this fix make it into RStudio Server soon as well?
