### ISSUE TITLE
Back to not-centered argument names in documentation

### ISSUE THREAD

**Issue by LuisLauM** [rstudio/rstudio#13106]
This is just a suggest. In my opinion, centering the names of the arguments in the help panel could lead missunderstandings in some functions. For instance, the function `rmarkdown::word_document` has arguments with large explainations that includes periods, so it is not clear to find out where starts/ends the definition of some of the arguments.

![image](https://github.com/rstudio/rstudio/assets/8452334/e7471b6e-5ee8-4393-9383-0fadadfe3396)

**Comment by ronblum** [comment]
@LuisLauM Thank you for raising this! As a comparison point, the help from standalone R is top-justified.

<img width="463" alt="justified" src="https://github.com/rstudio/rstudio/assets/31009952/66ba3f54-fc9c-4bf5-a167-fe6e41e196dd">

**Comment by LuisLauM** [comment]
Yes or even maybe just like the terminal version (in line with the text).

![image](https://github.com/rstudio/rstudio/assets/8452334/875739c2-89b7-4ca8-90e8-9b895d4464eb)

**Comment by kevinushey** [comment]
The argument names appear to be top-justified for me:

<img width="849" alt="Screenshot 2023-05-11 at 10 46 10 AM" src="https://github.com/rstudio/rstudio/assets/1976582/504c2428-93f5-4b8a-8848-4d17def45eb6">

This is with 2023.05.0 Build 325. Can you provide more details?

**Comment by kevinushey** [comment]
Ah, this is a change in R 4.3.0 (my prior post was testing with R 4.2.3). Given that this is due to a change in R, not RStudio, I would recommend filing a bug with the R Core team. We could consider modifying the CSS to preserve the old presentation, though.

**Comment by kevinushey** [comment]
For reference, R used to set `vertical-align: top` on the table rows. This is part of the HTML generated with R 4.2.3:

<img width="317" alt="Screenshot 2023-05-11 at 10 51 35 AM" src="https://github.com/rstudio/rstudio/assets/1976582/2f6fed78-9463-453d-973b-ac933af9ea73">

But with R 4.3.0, I see:

<img width="174" alt="Screenshot 2023-05-11 at 10 52 41 AM" src="https://github.com/rstudio/rstudio/assets/1976582/cafcca5a-c14f-4407-919b-f60c6ce15daf">

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.09.0-daily+348 on MacOS 14 using R 3.6.3, 4.2.3, and 4.3.1.

**Comment by joshua-theisen** [comment]
I'm still having this issue with this system:
`> R.Version()[c(1, 14)]
$platform
[1] "x86_64-w64-mingw32"

$version.string
[1] "R version 4.3.0 (2023-04-21 ucrt)"
`
 Rstudio information
`RStudio 2023.06.2 Build 561
"Mountain Hydrangea" Release (de44a311, 2023-08-25) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
AppleWebKit/537.36 (KHTML, like Gecko) 
RStudio/2023.06.2+561 
Chrome/110.0.5481.208 
Electron/23.3.0 
Safari/537.36
`

**Comment by ronblum** [comment]
@joshua-theisen This is fixed in the upcoming release, currently in progress. Builds for it are available at http://dailies.rstudio.com. Please note that these are for test and development purposes only, not production use.

**Comment by ronblum** [comment]
@joshua-theisen No problem—thanks for catching this, regradless. 🙂
