### ISSUE TITLE
Unexpected preview of named and hexadecimal colors in the console

### ISSUE THREAD

**Issue by zekiakyol** [rstudio/rstudio#13118]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.03.1+446
    OS Version      : Windows 10, 22H2
    R Version       : R 4.2.3

---

Because this is an obvious case, I am not sure whether this is an intended behavior but I describe the problem below.
Thank you!

### Steps to reproduce the problem

1. RStudio Desktop > Tools > Global Options > Code > Display > Uncheck "Enable preview of named and hexadecimal colors".
   There is no problem in this step.
3. Crate test.R and write the code below, then save it.
   ```
   plot(mtcars$mpg, mtcars$hp, col = "red")
   plot(mtcars$mpg, mtcars$hp, col = "#2B750E")
   ```
   There is no problem in this step.
4. Copy and paste the same code in Step 2 to console.
5. **Problem:** color preview for `"red"` and `"#2B750E"` is enabled until we run the code by hitting the enter button.
6. When we run the code, color preview disappears. There is no problem in this step.

---

### Steps to reproduce the problem [Gif Version]

![issue_color](https://github.com/rstudio/rstudio/assets/40212849/9f236af5-6d83-49e2-ae80-6ee7556d9993)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

---

### Describe the behavior you expected

When we uncheck the "Enable preview of named and hexadecimal colors" option, we expect to have no color preview in the console both before and after running the code.

**Comment by collinn** [comment]
This issue persists in R Studio Desktop version 2023.09.01+494 on Ubuntu 22.04

**Comment by kevinushey** [comment]
Thanks for the bug report! More concretely, the issue here is that the color preview option is not respected for console input, when highlight is enabled.

**Comment by jonvanausdeln** [comment]
Just tried with [2023.12.0-daily+234](https://dailies.rstudio.com/version/2023.12.0-daily+234) on Windows, and the code is still highlighted in the console regardless of the Global options setting.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/ab120ee81aab0ff19540fdaff67508a2fba29d93

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+302](https://dailies.rstudio.com/version/2023.12.0-daily+302)
Windows 11

Setting is respected in both editor and console pane.
