### ISSUE TITLE
Drag and drop an .R or .Rproj file into Rstudio does nothing

### ISSUE THREAD

**Issue by BdR76** [rstudio/rstudio#13124]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1 Build 446
    OS Version      :  Windows 10
    R Version       :  4.1.1

### Steps to reproduce the problem
1. drag an .R file or .R file
2. drop file in Rstudio

### Describe the problem in detail
Drag and drop an .R or .Rproj file into the Rstudio desktop application windows shows a `+Copy` file icon, but dropping the file does nothing.

![rstudio_drag_and_drop](https://github.com/rstudio/rstudio/assets/7793956/b1a549a8-16c5-40c5-b02a-abad48bbdfa9)

### Describe the behavior you expected
Rstudio should open the .R or .Rproj file, same as `Open file CTRL+O` or `Open project`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
See also #4037.

**Comment by ronblum** [comment]
Closing in favor of #4037, and re-raising #4037 for re-consideration.
