### ISSUE TITLE
sjmisc::rec() - val.labels function is not working

### ISSUE THREAD

**Issue by MarcoJCTeng** [rstudio/rstudio#13121]
Hi, 

I just found out that the `val.labels` function is not working anymore in `sjmisc::rec()`. I have tried to input the labels in both English and Chinese but failed in the end. The following image shows the code and the result of my operation process.

<img width="675" alt="Screenshot 2023-05-10 at 10 23 49 PM" src="https://github.com/strengejacke/sjmisc/assets/123462382/64a648ef-982c-4ded-80d3-6652d70a1ebd">

**Comment by DesiQuintans** [comment]
I see you also submitted this to the sjmisc Github <https://github.com/strengejacke/sjmisc/issues/153>. Is there something about RStudio in particular that contributes to this bug?

**Comment by MarcoJCTeng** [comment]
My apology, I posted this at the wrong place. Thank you so much and I will just close as complete.
