### ISSUE TITLE
Visual editor wrongly corrected url with hexa

### ISSUE THREAD

**Issue by CedricMidoux** [rstudio/rstudio#13131]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1 Build 446
    OS Version : Windows11 22H2 
    R Version : 4.3.0 

### Steps to reproduce the problem

When I switch to Visual R Markdown editor, the editor breaks some URLs with hex codes when trying to correct them.

### Describe the problem in detail

I try to add an image (come from [10.1038/533452a](https://doi.org/10.1038/533452a)) to a quarto document with :

```
![](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2F533452a/MediaObjects/41586_2016_BF533452a_Figd_HTML.jpg)
```

The editor correct to : 
```
![](https://media.springernature.com/full/springer-static/image/art%253A10.1038%252F533452a/MediaObjects/41586_2016_BF533452a_Figd_HTML.jpg)
```

In detail, it replaces the `%` with `%25`.

### Describe the behavior you expected

I want to keep the URLs functional,in source and visual mode.

Thanks in advance

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
@CedricMidoux , Thank you for reporting your issue.  Could you please share an example document that causes your issue?

**Comment by jonvanausdeln** [comment]
@CedricMidoux , I am able to reproduce this now. 

1. Create new Quarto Document
2. Make sure editor is in `Source` mode
3. Insert a URL to an image with `%` in the URL..
```
![](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2F533452a/MediaObjects/41586_2016_BF533452a_Figd_HTML.jpg)
```

4. Switch Editor to `Visual` mode, then back to `Source` mode.

URL is now broken.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto/commit/6d0e563551e590adf87c432556d69995ae6589e0

@timtmok You will need to start building from `quarto-dev/quarto/main` to see this fix.

**Comment by timtmok** [comment]
The fix will be available in the next build

**Comment by timtmok** [comment]
Yesterday's build failed due to infrastructure issues so here's hoping for tonight's build now that the issue has been fixed.

**Comment by timtmok** [comment]
I inspected the Windows build and it doesn't seem to have the change. The Mac and Ubuntu 22 builds do have it though. It might be an image caching issue. The Windows Docker image did update so the next build would use the updated image.

**Comment by timtmok** [comment]
Waiting on build 417, which is rebuilding the Docker image.

**Comment by timtmok** [comment]
[Windows - Build 417](https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2023.06.0-417.zip) should have the change. It's not showing up on the dailies site yet.

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2023.06.0+417
Windows 11, Ubuntu 22

URLs are now maintained correctly between source and visual editor modes
