### ISSUE TITLE
RStudio Use High Resource of CPU and RAM 

### ISSUE THREAD

**Issue by aephidayatuloh** [rstudio/rstudio#13143]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1+446 
    OS Version      : Windows 11 64-bit 21H2
    R Version       : 4.3.0

### Steps to reproduce the problem
Hello, I posted this on Posit Community (https://community.rstudio.com/t/rstudio-use-high-resource-of-cpu-and-ram/166270). I noticed something strange from my RStudio. I just opened RStudio, haven't done anything. Really just open it, there isn't any data in the environment and I didn't save the previous workspace image.

The CPU and RAM usage was very high, even about 2x the RAM usage compared to Google Chrome which had 10 tabs open and one of them was playing a YouTube video.
![image](https://github.com/rstudio/rstudio/assets/11643631/79d894bb-97f2-4560-95d2-2a9682b05743)

I've tried to downgrade the R version to 4.2.3 and RStudio to 2023.03.0 but the problem still the same.

### Describe the problem in detail
Here the one with the highest RAM and CPU usage is "R for Windows Terminal front-end", what's that for? When I End the Task in Task Manager, RStudio can still be used. This happens when I open a Project. When I close the project and the project is "Project: (None)" the "R for Windows Terminal front-end" disappear and usage of CPU and RAM back to normal, RAM less than 500MB and CPU usage ~0%. In my case, this only happened in one project among several projects I have. Even after I restart the R (Ctrl+Shift+F10) the "R for Windows Terminal front-end" come up again.

I've tried opening another project but something like this is only temporary at the beginning when opening the project. After waiting for a while the task "R for Windows Terminal front-end" disappeared. I also opened the base R but there is nothing wrong. The usage still low.

### Describe the behavior you expected
When you just open up RStudio and nothing you've done, the CPU and RAM usage should low right?
Hope my explanation clear enough.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by D3SL** [comment]
I also had this issue with R 4.3.2, with only one project. Updating to R4.4.0 seems to have fixed it.

**Comment by kevinushey** [comment]
That's great to hear -- please let us know if the issue resurfaces, or if you learn anything more.
