### ISSUE TITLE
Duplicated Tabs Over and Over Each Time RStudio is open 

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#13158]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1 Build 446
    OS Version      : Ubuntu 22.04.2 LTS
    R Version       : 4.3.0 (2023-04-21)

### Steps to reproduce the problem
1. Create several new R scripts
2. Close RStudio without saving the newly created scripts
3. Reopen RStudio. The unsaved scripts are duplicated in new tabs (which are not selectable)

### Describe the problem in detail
Since several updated now, the unsaved R scripts (generally `Untitled1`,  `Untitled2` and so on) are duplicated every time RStudio is opened. It seems to occur especially after a crash, but also after quitting RStudio normally.
Also, sometimes, but not always, tabs from a previous session are open after recovering from a crash. Which is very annoying.

### Describe the behavior you expected
Having a unique instance of all the unsaved scripts opened after RStudio started

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by pascaloettli** [comment]
Any progress on this topic? This is really annoying

**Comment by ronblum** [comment]
@pascaloettli I'm unable to reproduce the issue. Can you provide the log files after the next time they occur? Both `rdesktop.log` and `rsession-XXX.log` which you can get with <kbd>Help -> Diagnostics -> Show Log Files</kbd>/ Thanks!

**Comment by pascaloettli** [comment]
@ronblum Please find the requested files below:
[rdesktop.log](https://github.com/rstudio/rstudio/files/12354233/rdesktop.log)
[rsession-oettli.log](https://github.com/rstudio/rstudio/files/12354234/rsession-oettli.log)

**Comment by pascaloettli** [comment]
Without hearing about this issue, I had to recreate a `~/.local/share/rstudio` folder to get rid of the problem.

**Comment by ronblum** [comment]
Thanks @pascaloettli!

@timtmok Is there anything in the logs that would hint at the problem?

**Comment by timtmok** [comment]
I think since `~/.local/share/rstudio` didn't exist, the IDE had trouble saving the session data on close. It should be able to save which documents were open and any untitled documents to be able to properly restore the state. My guess is an untitled document was saved over and over each time it could not persist the session data. Then the next launch would create a duplicated untitled document.

**Comment by pascaloettli** [comment]
> I think since `~/.local/share/rstudio` didn't exist

Sorry, for the misunderstanding. `~/.local/share/rstudio` existed. I renamed it for the IDE to recreate `~/.local/share/rstudio` from scratch, to get rid of this annoying issue. I still have the old `~/.local/share/rstudio` on my machine.

**Comment by pascaloettli** [comment]
Both directories have `drwxr-xr-x` permissions.

If it is helpful, I also attach the results of `find . -exec stat --format='%A %n' '{}' \;`:
 
[Current](https://github.com/rstudio/rstudio/files/12546798/output1.txt) `~/.local/share/rstudio`
[Old](https://github.com/rstudio/rstudio/files/12546799/output2.txt) `~/.local/share/rstudio` (the one with issues)

**Comment by timtmok** [comment]
Thank you for the information! I don't see anything that would indicate a problem with the permissions. I don't know how it would get in this bad state but it's good to know that recreating the directory solved the issue.

**Comment by pascaloettli** [comment]
Just to let you know it started to do it again.

**Comment by pascaloettli** [comment]
Probably due to a termination linked to data.table package (I think I have seen a thread on that but cannot find it at the moment.)

**Comment by kevinushey** [comment]
Thanks @pascaloettli -- let us know if you're able to find that issue, or provide a reproducible example that can trigger the crash (even if it's not 100% reliable).

**Comment by pascaloettli** [comment]
@kevinushey I still have this issue but couldn't find yet a way to reproduce it on demand.

**Comment by csgillespie** [comment]
I also have this issue (can't reproduce). I think it was due to running out of memory and everything crashing
