### ISSUE TITLE
Document outline indention gets mixed up with unlabeled sections

### ISSUE THREAD

**Issue by KonstantinLang** [rstudio/rstudio#13159]
### System details

I experience the issue on both, a server and my desktop PC.

    RStudio Edition : Server
    RStudio Version : RStudio Workbench 2022.02.3
    OS Version      : 18.04.1-Ubuntu SMP
    R Version       : 4.2.1

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.03.0 Build 386
    OS Version      : Windows 10 x64
    R Version       : 4.2.1

### Steps to reproduce the problem

Create a blank RMarkdown document and insert different headers with at least one following an unlabeled section.

**Example**:
```
<!-- The {.tabset} option is not required to reproduce the problem. -->
<!-- I only added the option to show a use case I have frequently in my daily work -->
# section 1 {.tabset}

## section 1.1

## section 1.2

# {.toc-ignore}

# section 2

## section 2.1

## section 2.2 {.tabset}

### section 2.2.1

### section 2.2.2

## {.toc-ignore}

## section 2.3

# section 3

```

### Describe the problem in detail

For unlabeled sections (e.g. when using {.toc-ignore}), the indent of all following sections is **incorrectly** increased by one step in the document outline. The false step size increases with each unlabeled section. See figure below for an example.

![image](https://github.com/rstudio/rstudio/assets/111751107/3507db2a-0ca4-4f19-ab20-e545ac3bcdf3)

### Describe the behavior you expected

I expect the indentation to be the same for each heading level.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by DesiQuintans** [comment]
I found something that might be related to this issue. In a simple RMarkdown document, the Outline View shows headers correctly nested:

``` r
---
title: "Untitled"
output: html_document
date: "2023-05-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Level 1

## Level 2

### Level 3

## Level 2

### Level 3

#### Level 4
```

![image](https://github.com/rstudio/rstudio/assets/3200601/c00a6a78-255d-49b3-b3bf-b68469f2615f)

But if you add a linebreak to the very top of the RMarkdown document, it makes the headers all unnested:

``` r

---
title: "Untitled"
output: html_document
... etc. etc. ...
```

![image](https://github.com/rstudio/rstudio/assets/3200601/8b44fbcd-f6ef-4ae9-b0f0-da41956e4ad7)

It seems like Markdown's 'alternate syntax' for defining headers by underlining them is taking over. Maybe something like that is affecting this issue too?

**Comment by llrs** [comment]
I had a similar bug report in #10705, maybe they are related

**Comment by DesiQuintans** [comment]
Unstale

**Comment by gtritchie** [comment]
Tried this using 2024.07.0-daily+294.

It works as advertised in source mode, but the "untitled" heading is still absent from outline in Visual Mode.

<img width="557" alt="untitled-heading" src="https://github.com/rstudio/rstudio/assets/10569626/e0f6f07d-e57c-4dfe-98e5-3ba814db8933">

<img width="555" alt="visual-mode-missing-heading" src="https://github.com/rstudio/rstudio/assets/10569626/a42ccaa0-b642-461e-b359-5606baea1d3f">

**Comment by kevinushey** [comment]
It looks like the issue still occurs with visual mode because that uses its own widget for the document outline:

https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/panmirror/outline/PanmirrorOutlineWidget.java

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11 in both R Markdown and Quarto documents.
