### ISSUE TITLE
Raw strings ending on closed parentheses get misrecognized

### ISSUE THREAD

**Issue by erikvona** [rstudio/rstudio#13157]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1 Build 446
    OS Version      :  Windows 10 x64 (build 19044)
    R Version       :  4.2.2

### Problem details

Raw strings ending on a closed parenthesis do not appear to get recognized as valid.

To reproduce, create a file with the following R code:

``` r
a <- r"())"
```

This generates an `Unexpected token: 'r"())"'` while it appears to be a valid raw string. I'm not sure why this happens.

![image](https://github.com/rstudio/rstudio/assets/45684074/717f3f80-4e4f-4140-949a-e2906c357259)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by erikvona** [comment]
Appears to be related to #13094, apologies for not checking thoroughly enough

**Comment by kevinushey** [comment]
Thanks for the bug report! I think the problem occurs here:

https://github.com/rstudio/rstudio/blob/928fd383efa7795f769290368fc8e0c966a13556/src/cpp/core/r_util/RTokenizer.cpp#L310-L342

We need to save and reset the iterator location on each walk.

**Comment by erikvona** [comment]
It's a pity this got moved to "later". Raw strings are very useful when using regex to keep regexes readable, but regex strings often end on a closing parenthesis, so I need to work around this bug frequently.

**Comment by kevinushey** [comment]
@erikvona this should be fixed in the next daily builds. Could you please test the builds available at https://dailies.rstudio.com and let us know if the issue appears to be resolved?

**Comment by erikvona** [comment]
Thank you! The daily works well for me, I've got no errors anymore on the file I previously noted them on.

**Comment by kevinushey** [comment]
Great, thank you for confirming!
