### ISSUE TITLE
The file 'rstudio' is too large to open in the source editor (the file is 155.8 MB and the maximum file size is 5 MB)

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#13151]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.03.1 Build 446
    OS Version      :  Xubuntu 23.04
    R Version       :  4.2.2

### Steps to reproduce the problem
Doubleclick to open any script from file manager or within RStudio

### Describe the problem in detail
Spawns title-named popup warning but file opens fine. Files are all simple scripts, typically ~1 KB. I click OK and it goes away. Minor annoyance, nothing more.

### Describe the behavior you expected
This to not happen, haha.

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by SimonDedman** [comment]
Oh sorry, [related](https://github.com/rstudio/rstudio/issues/4341).

**Comment by stla** [comment]
Also related: https://github.com/rstudio/rstudio/issues/13003
