### ISSUE TITLE
Typing interrupted with "Error in if (nchar(current) > nchars) ..."

### ISSUE THREAD

**Issue by shearerpmm** [rstudio/rstudio#13163]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1+446
    OS Version      : OS X 13.2.1 (22D68)
    R Version       : 4.2.3 (2023-03-15)

### Steps to reproduce the problem
It is not possible to give reproducible steps because this issue happens randomly.

### Describe the problem in detail
While typing, RStudio will interrupt me with a prompt with the message:
```
Error in if (nchar(current) > nchars) { : 
  missing value where TRUE/FALSE needed
```
This error message also occurs in the R console. After I click OK I can continue normally. The error may happen multiple times in just a few seconds.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by StevenWallaert** [comment]
I have been encountering the same issue. I believe I have found a way to elicit the error:

The error shows up the moment you try to select the column in the autocompletion pop-up:

```
df <- tibble(adate = seq.Date(from = dmy("01-01-2023"), to = dmy("01-02-2023"), by = 1)) 

df %>% 
  select(adate) # No problem 


df[1:3, 1] <- NA


df %>% 
  select()  # Problem
```

**Comment by shearerpmm** [comment]
Thanks Steven! I had a feeling it had something to do with autocompletion of column names in tibbles but couldn't prove it.

**Comment by sharon-wang** [comment]
Thanks @shearerpmm for reporting this issue and @StevenWallaert for the additional detail!

This sounds like the same issue as https://github.com/rstudio/rstudio/issues/12918, which has been fixed! Could you try out the [latest daily build](https://dailies.rstudio.com/) of the upcoming release and see if this issue still comes up for you? Please note that the daily builds are intended for testing purposes only and shouldn't be used for production work.

**Comment by sharon-wang** [comment]
The latest release containing this fix is now available: https://posit.co/download/rstudio-desktop/#download !
