### ISSUE TITLE
cursor misaligned when typing NA

### ISSUE THREAD

**Issue by oikawac** [rstudio/rstudio#13164]
repeated NA will cause cursor to lag behind the true typing position when using default font
for instance:
c(NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA) #batman

**Comment by DesiQuintans** [comment]
What theme are you using? I've developed some themes and have noticed that ACE Editor (the thing that RStudio uses) cannot represent the cursor position properly for text that is styled to be thicker or larger than normally-styled text.

**Comment by DesiQuintans** [comment]
Pardon me, I mean the editor theme:

![image](https://github.com/rstudio/rstudio/assets/3200601/86521f2c-5ef7-4bc2-a6f5-19edb3a71ced)

**Comment by oikawac** [comment]
I think it's not default actually since I inherited this program on my work computer - I checked and it's IPlastic - changing the theme to Textmate does fix this bug
