### ISSUE TITLE
Quarto editor does not respect 'eval' option

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#13175]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.06.0-daily+400
    OS Version      : Ubuntu Server 22.04 LTS
    R Version       : 4.3.0

### Steps to reproduce the problem
Set a code chunk to `eval: false` and press "Run all" (Ctrl+Alt+R) or Render the file
````
---
title: "Untitled"
format: pptx
editor: visual
---

## FALSE

```{r}
#|eval: false

1 + 1
```

## TRUE

```{r}
#|eval: true

1 + 1
```
````
### Describe the problem in detail

Even if the code chunk `eval` option is set to `false` it will still execute and render

### Describe the behavior you expected

I expect the code chunk to not be evaluated

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by etiennebacher** [comment]
FYI this is because there should be a space between `#|` and `eval`. 

`#|eval: false` is evaluated but `#| eval: false` isn't

**Comment by andresrcs** [comment]
Then the issue changes to the YAML autocompletion feature since that is the way the option is inserted
