### ISSUE TITLE
GraphViz dot chunk does not render on chunk run.

### ISSUE THREAD

**Issue by Obsidian-user** [rstudio/rstudio#13187]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1+446
    OS Version      :  macOS 13.4 (M1)
    R Version       : 4.3.0

### Steps to reproduce the problem

1. Create a new Quatro document.
2. Paste the dot example from Quatro's diagram page

````r
---
title: "Untitled"
format: html
editor: visual
---

```{dot}
graph G {
  layout=neato
  run -- intr;
  intr -- runbl;
  runbl -- run;
  run -- kernel;
  kernel -- zombie;
  kernel -- sleep;
  kernel -- runmem;
  sleep -- swap;
  swap -- runswap;
  runswap -- new;
  runswap -- runmem;
  new -- runmem;
  sleep -- runmem;
}
```
````

### Describe the problem in detail

dot chunks do not render when run with Cmd+Enter but do render on entire document render. Instead I get this output

```
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  Missing argument for -T flag
Usage: dot [-Vv?] [-(GNE)name=val] [-(KTlso)<val>] <dot files>
(additional options for neato)    [-x] [-n<v>]
(additional options for fdp)      [-L(gO)] [-L(nUCT)<val>]
(additional options for memtest)  [-m<v>]
(additional options for config)  [-cv]

 -V          - Print version and exit
 -v          - Enable verbose mode 
 -Gname=val  - Set graph attribute 'name' to 'val'
 -Nname=val  - Set node attribute 'name' to 'val'
 -Ename=val  - Set edge attribute 'name' to 'val'
 -Tv         - Set output format to 'v'
 -Kv         - Set layout engine to 'v' (overrides default based on command name)
 -lv         - Use external library 'v'
 -ofile      - Write output to 'file'
 -O          - Automatically generate an output filename based on the input filename with a .'format' appended. (Causes all -ofile options to be ignored.) 
 -P          - Internally generate a graph of the current plugins. 
 -q[l]       - Set level of message suppression (=1)
 -s[v]   
```

### Describe the behavior you expected

For the dot chunk to render the correct graph underneath the chunk.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Using the above code, I'm getting the following error:

> running: dot dotb6cc43390176.dot -T png -o dotb6cc43390176.png
Error in system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env) : 
  error in running command

**Comment by kevinushey** [comment]
@ronblum, do you have the `dot` command line utility installed? You'll need to install it with e.g.

```
brew install dot
```

assuming you're using Homebrew.

**Comment by ronblum** [comment]
Ah! I waded in too deep—thank you for the floaties.

Verified in RStudio Desktop 2023.12.0-daily+201 on MacOS 14 and Windows 11.
<img width="508" alt="dot" src="https://github.com/rstudio/rstudio/assets/31009952/e3fdc307-f272-409a-bec1-bc9e6a9e96cc">

<img width="556" alt="dot_png" src="https://github.com/rstudio/rstudio/assets/31009952/b509775b-a928-40a7-b7ce-cde3b6ca16ce">

Note: `winget install graphviz` on Windows and `brew install graphviz` on Mac.
