### ISSUE TITLE
Help for ... ellipsis parameter doesn't show and autocomplete for joins doesn't work

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#13196]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.03 and 2023.06 (daily 2023-05-31)
    OS Version      : Windows
    R Version       :  4.2.3

### Steps to reproduce the problem

Type a function that has an ellipsis argument, like dplyr::filter, mutate.
Press Tab (to show autocomplete)
The `...` arg is not documented.

Also, with left_join for example, autocomplete works fine, until you put 3 arguments, then the autocomplete doesn't work.

Outside a pipe 
![image](https://github.com/rstudio/rstudio/assets/52606734/03074766-6c5e-4cae-97bc-e16ff88761a4)

Inside a pipe (magrittr or native)
![image](https://github.com/rstudio/rstudio/assets/52606734/0a863da9-4007-4029-b2b4-2c92c1eafed0)

### Describe the problem in detail

Autcomplete help file of the `...` doesn't show on any functions.
Autocomplete many arguments doesn't work in dplyr::*join() functions. I tested it for another function with many arguments

### Describe the behavior you expected

I would expect the ... documentation to show up, since for certain functions especially those documented with @inheritDotParams, the `...` is very useful!
![image](https://github.com/rstudio/rstudio/assets/52606734/01734bde-f1f0-4e4f-8c59-693ddaa4852b)

It used to be present, as we can see in old screenshots (#11627)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x} I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@olivroy Thank you for raising this! I can reproduce this in 2023.03.2+454 on MacOS 13.4. This seems to work as expected in 2022.12.0-353. We'll review the issue as we continue development of RStudio.

**Comment by ronblum** [comment]
@romainfrancois Can you take a look this?

**Comment by olivroy** [comment]
Is there any chance this will be fixed in the near future? It's important to know if a function has `...` it has an effect on the order of arguments to specify. I used to rely heavily on this feature...

**Comment by ronblum** [comment]
@olivroy It's high on the list but not yet targeted for a specific release.

@sharon-wang Can you take a look at this?

**Comment by sharon-wang** [comment]
@ronblum sure thing!

**Comment by kevinushey** [comment]
It looks like the change was made here: https://github.com/rstudio/rstudio/commit/6786f041d98d214c4ed89f81aa45ef04c043ca95

Perhaps we should just roll back that change?

**Comment by olivroy** [comment]
Well you possibly don't want ... = to popup. 

But it is useful to at least see the documentation in the yellow box, without having to go to the help pane.

**Comment by olivroy** [comment]
> Perhaps we should just roll back that change? 
Yes, maybe at least it would ensure we'd see the documentation in the popup box.

But I may have another suggestion since this seems related..

Maybe instead of hiding the documentation for used parameters, maybe hide it for named ones.

Showing doc for all parameters (except explicitly named ones), but (block?) autocompletion)

```r
dplyr::left_join(mtcars, iris)
```

Would show documentation for all parameters, (x, y, suffix, etc.), but only allow autocompletion for suffix, et al. 
Because when not specifying parameter names, we may realize later, that we didn't provide the correct ordering

```r
dplyr::left_join(x = mtcars, y = iris)
```
Would not show documentation for parameters, (x, y, suffix, etc.), and allow autocompletion for suffix, et al. ..


THis may require further thinking, but I think that maybe.

We should show documentation for all parameters, unless they are explictly named,
Keep autocompletion pattern as is (i.e. not reverting https://github.com/rstudio/rstudio/commit/6786f041d98d214c4ed89f81aa45ef04c043ca95)

But still show help for the other parameters, including `...`

**Comment by sharon-wang** [comment]
I've dug in a bit to see how we might approach this.

Ideally, we'd do something like the following so we can show help text for `...`, but prevent completions. If there are other arguments we'd like to provide help text for, but not provide completions, we could reuse this mechanism.
1. Re-enable including `...` in the help preview results, so users are able to see the help description for the `...` argument
    - Users will still be able to click on this argument, which inserts `... = ` into the editor, which is invalid code that will need to be removed
2. Create a new argument type or add a new property to flag arguments that should show up in completions for help text purposes, but have completions disabled (selecting that argument in the completions list won't insert any code)

For the `dplyr` missing autocomplete suggestions, it looks like we stop providing autocomplete suggestions once values for arguments without defaults have been specified. I tried to reproduce the autocomplete bug with functions that have a similar signature, such as:

```
sumWithEllipsesArg <- function(x, y, ..., a, b) { x+y+a+b+sum(...) }
sumWithEllipsesArgDefaults <- function(x, y, z = NULL, ..., a = 0, b = 0) { x+y+a+b+sum(...) }
```

but I wasn't able to reproduce. Then I realized we have custom handling for `dplyr` join completions, so I think the issue might be in our handling there, but more investigation is needed.

---

I think we should split this issue into two:
1) handle parameters that have help text but no code completions
2) fix bug in dplyr join completions

Both of these require some more investigation and refactoring.

If there's desire for help text for the `...` parameter, I think we should do the quick fix for now and revert https://github.com/rstudio/rstudio/commit/6786f041d98d214c4ed89f81aa45ef04c043ca95.

**Comment by kevinushey** [comment]
> If there's desire for help text for the ... parameter, I think we should do the quick fix for now and revert https://github.com/rstudio/rstudio/commit/6786f041d98d214c4ed89f81aa45ef04c043ca95.

My vote would be to revert that commit. If we wanted to do something smarter later, we could consider some special action if the user selects `...`, but I'm not sure what that action would be. (Would it be better to do nothing, instead of inserting `... = `?)

**Comment by kevinushey** [comment]
@sharon-wang, can we use this issue to track the changes you made in https://github.com/rstudio/rstudio/pull/13413?

Then, I think we might need separate issues for these entries:

- handle parameters that have help text but no code completions
- fix bug in dplyr join completions

**Comment by sharon-wang** [comment]
Sounds good to me!

Here are the new issues for the other entries:
- https://github.com/rstudio/rstudio/issues/13414
- https://github.com/rstudio/rstudio/issues/13415

**Comment by ronblum** [comment]
Verified in 2023.09.0-daily+290 on MacOS 13.5.. I can confirm that `...` shows up in the autocomplete with `dplyr::left_join()`. Also tried with a basic function:
```
a <- function (..., x, y)
{
    print(x + y)
}
a()
```
Then put the cursor between the parentheses and click on <kbd>Tab</kbd>. The ellipses show up, where previously they didn't.
