### ISSUE TITLE
[FeatureReq] Connect to RServer from local Rstudio

### ISSUE THREAD

**Issue by CoolShades** [rstudio/rstudio#13202]
Hi team!!

Exciting idea for the team/community to implement. 

Imagine this. In your local RStudio app locally, File >> Connect to Server >> Enter IP address of RServer.

Boom, the app is now a remote control for R server. No browser required.

**Comment by ronblum** [comment]
@CoolShades Gret suggestion! This feature is available already, but only with our professional products, RStudio Desktop Pro with remote sessions in Posit Workbench.
