### ISSUE TITLE
Ignore update when new update is available does not work as intended

### ISSUE THREAD

**Issue by jrausch12** [rstudio/rstudio#13214]
### System details

    RStudio Edition : Desktop Community
    RStudio Version : 2022.12.0 Build 353
    OS Version      : Windows 10
    R Version       : 4.1.1 (2021-08-10) -- "Kick Things"

### Steps to reproduce the problem
1. Open RStudio
2. Allow "Update Available" dialog box to appear
3. Click "Ignore update"
4. Close RStudio
5. Open RStudio
6. Observe "Update Available" dialog box appearing again

### Describe the problem in detail
The "Ignore update" button in the "Update Available" dialog box does not squelch the "Update Available" box on subsequent RStudio openings.

### Describe the behavior you expected
When an update available dialog box appears and you click "Ignore update", one would expect that dialog box to not pop up again until a newer version is available for download.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
Hi @jrausch12! Thank you for filing this issue report :)

This issue was resolved in #12869 🎉. That fix is available in the latest RStudio release, which you can download here: https://posit.co/download/rstudio-desktop/#download.
