### ISSUE TITLE
No comment/uncomment line functionality in quarto visual mode

### ISSUE THREAD

**Issue by mdeber** [rstudio/rstudio#13229]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0+421
    OS Version      : macOS 12.6.6
    R Version       : 4.1.1

### Steps to reproduce the problem

Open a quarto notebook and insert an R code chunk. Set the quarto notebook to "visual" mode.

### Describe the problem in detail

Use of RStudio's "Comment/Uncomment Lines" feature (either in the "Code" drop-down menu, or using hotkeys e.g., Shift-Cmd-C on a Mac) is not available (grayed out in the drop-down, or nothing happens if using the hotkeys). But change the quarto notebook to "Source" mode (instead of "Visual") and the feature works as expected.

### Describe the behavior you expected

Comment/Uncomment Lines would work within code chunks of quarto notebooks in visual mode as well source mode.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mdeber Thank you for raising this!

**Comment by munoztd0** [comment]
Yeah this is quite a big missing feature I find

**Comment by olivroy** [comment]
Still worth looking at imo!

**Comment by ronblum** [comment]
@olivroy Are you seeing the issue in the recent 2023.12.1 release or the 2024.04.0 dailies?

**Comment by jthomasmock** [comment]
Thanks for raising! I have this working locally on Mac and v2023.12.1: 



![Image](https://github.com/rstudio/rstudio/assets/29187501/1f949c9e-3860-4ef0-8194-1af0537a9f79)

**Comment by olivroy** [comment]
It works too indeed. Indeed, working on Windows as well!
