### ISSUE TITLE
Rstudio cannot load R (An error occurred while attempting to load the selected version of R)

### ISSUE THREAD

**Issue by GregHKim** [rstudio/rstudio#13226]
### System details

    RStudio Edition :  Desktop
    RStudio Version : RSTUDIO-2023.06.0-421.EXE  # 01A61609
    OS Version      :  Window 11
    R Version       : R-4.3.0-win

### Describe the problem in detail
It has been a long-lasting issue and I was hoping it to be solved with the newer version of R... I have deleted older versions of R and Rstudio and re-downloaded the latest versions to make sure everything is installed from blank. 

Still, when I open Rstudio. It automatically opens a pop-up window where I need to select the version of R. I selected "[64-bit] C:\program Files\R\R-4.3.0" which latest and only version of R on my computer. 

When I click OK, consistently an error message pops out saying that "An error occurred while attempting to load the selected version of R. Please select a different R installation." and I am not very sure where to scratch it out.. 

I think the error started after updating my window system from window 10 to window 11 (not 100% sure)... which has been quite a while ago.

### Describe the behavior you expected

Please help me with solving the problem!! P

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
@GregHKim Can you provide debug logs when attempting to start RStudio? Please see the link above to generating a diagnostics report.

**Comment by EssentialFocusing** [comment]
I'm having this error.  Please help!

Diagnostic file:
[10728:0927/163413.613:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[10728:0927/163413.613:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[10728:0927/163413.613:ERROR:disk_cache.cc(205)] Unable to create cache
[10728:0927/163413.613:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[10728:0927/163413.613:ERROR:disk_cache.cc(205)] Unable to create cache
[10728:0927/163413.613:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2

**Comment by timtmok** [comment]
@EssentialFocusing can you try backing up and removing `AppData\Roaming\RStudio` from your user directory?
