### ISSUE TITLE
List of summary of quadratic approximation not displayed correctly

### ISSUE THREAD

**Issue by petzi53** [rstudio/rstudio#13227]
### System details

    RStudio Edition : 
    RStudio Version : 2023.06.0+421 (2023.06.0+421)
    OS Version      :  macOS Ventura 13.4 (22F66)
    R Version       :  4.3.0

### Steps to reproduce the problem
Running the following code results in the console ok, but in RStudio (RMarkdown and Quarto alike) the result is not readable.
```
library(rethinking)

globe.qa <- quap(
    alist(
        W ~ dbinom(W + L, p), # binomial likelihood
        p ~ dunif(0, 1) # uniform prior
    ),
    data = list(W = 6, L = 3)
)

# display summary of quadratic approximation
precis(globe.qa)
````
### Describe the problem in detail
The result is displayed in RStudio Quarto as in the image shown:
<img width="247" alt="image" src="https://github.com/rstudio/rstudio/assets/24394304/f2420444-2cdb-4625-8a84-e06fb663b4e8">

The result gets better when wrapped into print() statement (but it is still not displayed correctly: `p` is not fully displayed.)
`print(precis(globe.qa))` results into:
<img width="436" alt="image" src="https://github.com/rstudio/rstudio/assets/24394304/d2c5f5a6-5f18-4161-bb18-26f48018d919">

### Describe the behavior you expected
Output should be:
```
  mean   sd 5.5% 94.5%
p 0.67 0.16 0.42  0.92
```
or the full values as shown in the RStudio environment variable.
<img width="304" alt="image" src="https://github.com/rstudio/rstudio/assets/24394304/6ddd1459-8018-4876-82f4-9712f7918d5b">

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
I was able to reproduce this a couple of time in visual mode (but not source mode), but now it's working correctly for me. I haven't found a pattern for a 100% reprex, but marking this as a bug to review.
