### ISSUE TITLE
Menu item icons not visible on Linux

### ISSUE THREAD

**Issue by dat-linux** [rstudio/rstudio#13221]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0 Build 421
    OS Version      :  Ubuntu 22.04
    R Version       : 4.3.0 (2023-04-21) -- "Already Tomorrow"

### Steps to reproduce the problem

Download, unzip, and run the Linux/Ubuntu "jammy" standalone RStudio for Linux

### Describe the problem in detail

No visible menu item icons
[screenshot](https://community.rstudio.com/uploads/default/optimized/3X/a/6/a693416f60e2138b10cf885d6ca0731070327059_2_477x499.png)

### Describe the behavior you expected

Visible menu item icons

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [n/a ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by danieltomasz** [comment]
The problem still persists with `2023.12.1`
