### ISSUE TITLE
Build option to disable automatic version check

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rstudio#13236]
## Context
We discussed in the past (e.g. see [here](https://github.com/rstudio/rstudio/issues/10289#issuecomment-1026152330)) that downstream Fedora RPM packaging takes a slightly different approach by providing a `rstudio` package with common bits, and then `rstudio-desktop` and `rstudio-server` subpackages. Additionally, we are FHS-compliant by putting the stuff under `/usr/libexec`. All in all, this means that Fedora-provided packages and the official packages are not compatible.

## Issue
Some of our users still get confused when RStudio Desktop detects a new official version and prompts the user to download it. And this official package on top of a Fedora installation produces conflicts.

## Feature request
It would be nice to have a cmake switch to be able to disable altogether the automatic version check (as well as the "Check for updates" menu item) in RStudio Desktop to avoid this kind of confusion, because we already provide timely updates via the system repositories, only that these updates take a week or so to reach the end users due to the testing period.

## Alternative or temporary workaround
Meanwhile, or if you don't want to merge this feature upstream at all, it would be nice if somebody could help us create a downstream patch to do this, or at least point us in the right direction. /cc @kevinushey

**Comment by Enchufa2** [comment]
It seems that at least there is [this](https://github.com/rstudio/rstudio/blob/376f53f742fbcbc99d76850f5abf7d6e24be833c/docs/news/index.qmd#L2789) to disable the automatic check, right? I would also like to remove the "Check for Updates" entry in the "Help" menu.

**Comment by Enchufa2** [comment]
This is still relevant.

**Comment by gtritchie** [comment]
Can now build RStudio without the check-for-updates feature via cmake option:

`-DRSTUDIO_DISABLE_CHECK_FOR_UPDATES=1`

**Comment by Enchufa2** [comment]
Thanks for this, much appreciated.
