### ISSUE TITLE
Show All Panes hides source pane and console pane when using additional source columns

### ISSUE THREAD

**Issue by kelli-rstudio** [rstudio/rstudio#13230]
### System details

    RStudio Edition : Workbench
    RStudio Version : 2023.06.1 Build 429.pro4
    OS Version      : Ubuntu20
    R Version       : 4.2.2

### Steps to reproduce the problem
1. Add a new source column CMD+F7 or CTLR+F7
2. Show all panes CTRL+SHIFT+0

### Describe the problem in detail
When using the default pane layout, adding a new source column causes the panes to resize which partially covers up the console pane and original source pane (if you have one open). Then clicking "Show All Panes" completely covers up the console and original source pane.

https://github.com/rstudio/rstudio/assets/114421526/e3e3afd9-7546-4347-a416-7221dd76bb24

### Describe the behavior you expected
The panes should resize in a way that doesn't obstruct the view of the console pane and source pane.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible in RStudio Desktop 2022.07.2+576 on MacOS 13.4.

Note that the panes reappear if a source column is added or closed.
