### ISSUE TITLE
don't collapse whitespace in error display

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13239]
For example, if I run:

```
library(testthat)
the <- testthat:::the
the$edition <- 3L

testthat::expect_equal(1:100, 1:200)
```

I see:

<img width="526" alt="Screenshot 2023-06-13 at 5 08 21 PM" src="https://github.com/rstudio/rstudio/assets/1976582/f7194445-c1b3-4445-89a3-bfea8fb42f9d">

However, the correct presentation here would preserve whitespace, e.g.

<img width="606" alt="Screenshot 2023-06-13 at 5 08 55 PM" src="https://github.com/rstudio/rstudio/assets/1976582/b8ff29cb-fec1-454a-a0eb-ab9354304a2b">

Should hopefully just be a CSS update on the right DOM element somewhere.

**Comment by jonvanausdeln** [comment]
Verified on 2023.09.0-daily+290
Windows11, MacOS 12.6

Whitespace is preserved as expected.
