### ISSUE TITLE
Ctrl+Up shortcut not doing what is described in modify shortcuts settings panel

### ISSUE THREAD

**Issue by ergz** [rstudio/rstudio#13242]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-05) for windows
    OS Version      :  Windows 11
    R Version       :  4.3.0

### Steps to reproduce the problem

Open an editor with a file with function definitions and long enough to require scrolling, pressing Ctrl+UP/Down will jump to functions and once the direction being traveled has no more functions it switches to scrolling by line. 

### Describe the problem in detail

Open an editor with a file with function definitions and long enough to require scrolling, pressing Ctrl+UP/Down will jump to functions and once the direction being traveled has no more functions it switches to scrolling by line. 

### Describe the behavior you expected

I expect the document to scroll by line as described here: 

<img width="538" alt="image" src="https://github.com/rstudio/rstudio/assets/10622214/602afc0a-1f4d-483b-8247-d99b6c6c4cb7">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible in RStudio Desktop 2022.07.2+576 on Windows 11, as well. Either the behavior is incorrect or the shortcut description should be more precise.
