### ISSUE TITLE
Backport #13188 to Mountain Hydrangea 2023.06.1.

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13245]
Backport #13188 to Mountain Hydrangea 2023.06.1.

**Note: This issue is to record the need to backport the linked issue only. Please add comments or discussion relating to the original issue onto it directly.**

**Comment by sharon-wang** [comment]
Oh this is a duplicate! Already created this in #13241

**Comment by ronblum** [comment]
Oops!
