### ISSUE TITLE
Window's Desktop reference to Internet Explorer

### ISSUE THREAD

**Issue by datakid** [rstudio/rstudio#13250]
### System details

    RStudio Edition : RStudio Desktop Pro
    RStudio Version : 2023.06.0 Build 419.pro1
    OS Version      : Windows 11 Version	10.0.22631 Build 22631

### Steps to reproduce the problem

Tools->Global Options->Packages->Management tab

"Use Internet Explorer library/proxy for HTTP"

![Screenshot 2023-06-16 134339](https://github.com/rstudio/rstudio/assets/97304/080ba80f-702a-4161-bbd2-39ee608c6a14)

Should we change this to "Internet Explorer or Microsoft Edge"?

### Describe the problem in detail

IE is EoL

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This preference basically governs whether we pass `--internet2` to child R processes, e.g.

https://github.com/rstudio/rstudio/blob/930ebfadbab961276ee339d50aebf954050d27fb/src/cpp/session/modules/SessionUpdates.cpp#L85-L88

But this has been the default in R for some time now:

https://github.com/wch/r-source/commit/575d31ef11e24b07622e8f596e8a4ef2f7f768e5

So I think we can just remove the associated UI + usages in the codebase.

**Comment by datakid** [comment]
@kevinushey @ronblum I think this should be dealt with sooner rather than later. It's a relatively minor change

**Comment by jonvanausdeln** [comment]
Verified with [2024.04.0-daily+456](https://dailies.rstudio.com/version/2024.04.0-daily+456) on Windows 11

Reference is removed and packages download  & update without issue.
