### ISSUE TITLE
2023.06 doesn't start ("GetPackageFamilyName not located") on windows 7 sp1

### ISSUE THREAD

**Issue by jwwq** [rstudio/rstudio#13258]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0
    OS Version      : Windows 7 x64 SP1
    R Version       : 4.2.2

### Steps to reproduce the problem
Start RStudio

### Describe the problem in detail
Instead of R logo I get a messagebox with a text "Procedure entry point GetPackageFamilyName could not be located", and when I close it, RStudio doesn't start.
2023.03 works fine.

P.S. I couldn't find any mention of OSes compatibility restrictions in new version at https://docs.posit.co/ide/news/

### Describe the behavior you expected
RStudio starts as usual

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Sorry, but the latest releases of RStudio do not support Windows 7. (Note that Microsoft ended support for Windows 7 in 2020.)

I recommend updating to a supported release of Windows, or installing an older release of RStudio from https://global.rstudio.com/products/rstudio/older-versions/.

**Comment by Theo1996** [comment]
What is the latest version that supports win 7?
