### ISSUE TITLE
Quarto Document Format for Teaching 

### ISSUE THREAD

**Issue by jmgirard** [rstudio/rstudio#13256]
## Problem Statement
I do a lot of teaching in R and, while I love Quarto, there are several default settings that make this difficult (see below). 

The biggest problem is that, although the default setting of `embed-resources: false` is fast and results in small HTML files when working locally or on the web, the HTML file won't display properly when it is emailed or uploaded to an LMS without the supporting files. Setting `embed-resources: true` fixes this but many students forget to set it and it is also a bit error-prone because you have to get the colons and indenting perfect (which is challenging for many beginners). Less important is that the `df-print: paged` and `page-layout: full` settings are nice for teaching and interactive data science. 

I have two proposed solutions:

## Solution 1
Create a Quarto version of the R Notebook (maybe called a Quarto Notebook or Q Notebook) that sets the following options in the YAML header and maybe creates a setup chunk (or the normal Quarto boilerplate if preferred). I know you can create a quarto template file to do this, but it is not convenient to have to use (and teach) a terminal CLI command to create a new file each time.

````md
---
title: "Untitled"
author: "Name"
format: 
  html:
    embed-resources: true
    page-layout: full
    df-print: paged
---

```{r, setup}
# Load packages here
```
````

Ideally, users would be able to create this using either "File > New File > Quarto Notebook" or "File > New File > Quarto Document > Notebook" without needing to install any new packages so that it can be taught to absolute beginners before they learn about installing and loading packages.

## Solution 2 
Add a checkbox to the quarto document creation wizard called "Embed Resources" that, when checked, adds this to the YAML header.

![image](https://github.com/rstudio/rstudio/assets/6829033/bb221388-274c-462f-8fc5-69006fc6d2bf)

**Comment by cderv** [comment]
Related quarto Discussion for reference: https://github.com/quarto-dev/quarto-cli/discussions/5940
