### ISSUE TITLE
Cannot create a new project

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#13257]
Hello,

As my Linux laptop is broken, I'm using the laptop of my job, on which I have no admin rights. I installed the latest RStudio with the zip archive and I have R-4.3.0. 

At the beginning it didn't work well, then I set the engine to "Software" and it worked better. But now I cannot create a new project. When I try, it starts to switch to the new project and then it suddenly closes. Is there something to do to repair that? Maybe deleting something in the cache folders, I don't know.

RStudio version:
RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by stla** [comment]
It has worked with `rstudioapi::initializeProject` and `rstudioapi::openProject`.

**Comment by stla** [comment]
I ran `rstudio.exe` from a terminal and I got these messages:

```
 [20216:0617/093647.472:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[20216:0617/093647.475:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[20216:0617/093647.684:ERROR:disk_cache.cc(205)] Unable to create cache
[20216:0617/093647.733:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[20216:0617/093647.733:ERROR:disk_cache.cc(205)] Unable to create cache
[20216:0617/093647.734:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[22244:0617/093647.825:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[22244:0617/093647.829:ERROR:disk_cache.cc(205)] Unable to create cache
```

These are the messages I originally got before I switched to engine "Software". I thought these messages were related to the OpenGL engine.

**Comment by ronblum** [comment]
@stla Thank you for raising this! Does it work correctly if you switch the rendering engine? I'm trying to understand if the rendering engine is related or a red herring.

**Comment by stla** [comment]
@ronblum Thank you. It works now. But I didn't change anything.

**Comment by ronblum** [comment]
@stla That's good to hear! I'll close the issue, but if you run into it again, please let us know.
