### ISSUE TITLE
Rstudio.exe not using the most recent installed version of R

### ISSUE THREAD

**Issue by moxboxwa** [rstudio/rstudio#13259]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1 Build 435
    OS Version      : Win 10
    R Version       :  that's the issue (see below)

### Steps to reproduce the problem

I'm not sure it can be reproduced, after it is "fixed" with the steps below

Note I am using one of the daily Rstudio builds, to address https://github.com/rstudio/rstudio/issues/13188 

### Describe the problem in detail

I have installed R version 4.3.1:
![image](https://github.com/rstudio/rstudio/assets/96149051/a76e41ad-3eb5-4be7-b0a6-5c090536ab94)

But Rstudio.exe continues to load version R version 4.2.3

![image](https://github.com/rstudio/rstudio/assets/96149051/eeade293-d79d-44b6-bf84-2e3cfad33218)

 If I move R 4.2.3 into another folder, so that only the updated R 4.3.1 is available 
![image](https://github.com/rstudio/rstudio/assets/96149051/e178d230-a10e-42cd-82a0-5d83ec50ec42)

I get this dialog box pop-up when I start Rstudio
![image](https://github.com/rstudio/rstudio/assets/96149051/93e4794f-20f3-4e18-b03e-36f765e9235a)

And I can force Rstudio to choose the updated (and only) version.

### Describe the behavior you expected

In the past, whenever I've updated my version of R, the Rstudio.exe app automatically finds and loads the most recent version.  I haven't had to delete earlier versions of R, and haven't had that dialog box appear.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@moxboxwa Thank you for raising this! When you have both 4.2.3 and 4.3.1 installed, what does the R-version selection window show? You can access it by holding down <kbd>Ctrl</kbd> during startup, or with <kbd>Tools -> Global Options -> R Versions -> Change</kbd>.
