### ISSUE TITLE
copilot: handle NotAuthorized state

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13267]
I tried this via the build linked in this comment: https://github.com/rstudio/rstudio/pull/13192#issuecomment-1593126128

When trying to authorise, it didn't seem like i was going to finish so I closed rstudio and reopened, hoping to be able to try again.
But it seems like the result is saved, unchecking and rechecking the box doesn't try to re-authorise.
Is there a way to retry the autorisation?

![image](https://github.com/rstudio/rstudio/assets/4944073/e57d45f8-adc9-4cbb-8eaf-ab68370a4ebe)

_Originally posted by @tonyk7440 in https://github.com/rstudio/rstudio/issues/10148#issuecomment-1598656058_

**Comment by AliVaughan** [comment]
hello this has happened to me too 
![Screenshot 2023-07-24 at 10 26 54 am](https://github.com/rstudio/rstudio/assets/99653368/8c07dab8-4f7c-4854-b8ce-a1f125879c8d)

**Comment by ronblum** [comment]
I'm getting something a little bit different when closing RStudio in the middle of authorizing, then restarting.

![Image](https://github.com/rstudio/rstudio/assets/31009952/226f5f10-2b84-401a-ac5c-122f1eb0b381)

This is both with 2023.09.0-daily+246 and 2023.09.0-daily+380. I'll wait for one more build to see if the next one picks up a change.

**Comment by kevinushey** [comment]
@ronblum can you try enabling Copilot diagnostics and checking what you see in the Console after opening the Copilot preferences page?

```
.Call("rs_copilotSetLogLevel", 3L)
```

**Comment by ronblum** [comment]
Verified fixed—starting with build 2023.09.0-daily+381 on MacOS 14, the Global Options Pane now states that the user is signed out and has the link to sign in. (I guess I jumped the gun with build 380. 🙂 )
