### ISSUE TITLE
in Visual mode when chunks run , output is shown beneath the wrong chunk

### ISSUE THREAD

**Issue by DanBennettDev** [rstudio/rstudio#13261]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0 Build 421
    OS Version      :  windows 10
    R Version       : 4.2.2

### Steps to reproduce the problem
Sorry but I cannot work out the pattern that creates this problem. I have been experiencing it for weeks and trying to work out the pattern, but it remains unpredictable. It seems to happen in large notebooks, in visual mode, when I run chunks one by one. Sometimes it just starts putting the output in the wrong place. I can get it to work again for a while by closing the notebook and reloading. I think it always happens in sessions when I have added or removed chunks, but can't say for sure.

### Describe the problem in detail
In visual mode, in a large notebook, I run chunks one by one.  Likely I have edited, added, removed chunks At some point, when I run a chunk (using ctrl shift enter) the output does not display beneath the chunk as expected. Instead it shows beneath a chunk elsewhere in the notebook - either above or below. The window scrolls down to the "output chunk" and the output begins to show in the window beneath it

### Describe the behavior you expected
When I run the chunk, the output appears directly beneath the chunk I am running.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by DanBennettDev** [comment]
Workaround - if I copy a code chunk, delete the chunk, and paste the chunk back in, and then run the chunk, the output appears beneath the chunk

This only works on a per-chunk basis. Other chunks in the same notebook will still output in the wrong place

**Comment by ronblum** [comment]
@DanBennettDev Thank you for raising this! I'm unable to reproduce it, though. A few things:

1) Does this work correctly in source mode?
2) Can you provide a simple example in which this occurs so that I can try to reproduce this?
