### ISSUE TITLE
Skip Columns in Viewer does not work

### ISSUE THREAD

**Issue by docal555** [rstudio/rstudio#13269]
After importing a file it is viewed in "Viewer" but skip columns (if file has more than 50 columns) does not work anymore.
Checked on Mac and on Windows -> not working either

### System details

    RStudio Edition 🖥️ 
    RStudio Version : Version 2023.06.0+421 (2023.06.0+421)
    OS Version      : Ventura 13.4 (22F66)
    R Version       : 4.1.3

### Steps to reproduce the problem
Load a file with more than 50 columns and try to skip through columns 50+ the file in Viewer 

### Describe the problem in detail
Load a file with more than 50 columns and try to skip through columns 50+ the file in Viewer 

### Describe the behavior you expected
Skip through files in Viewer as it was possible before

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x
<img width="225" alt="Bildschirmfoto 2023-06-21 um 09 37 49" src="https://github.com/rstudio/rstudio/assets/45333547/ee2a1dd5-294a-4e68-bdc9-fc25493f2206">
<img width="225" alt="Bildschirmfoto 2023-06-21 um 09 37 49" src="https://github.com/rstudio/rstudio/assets/45333547/505e7294-dc5c-4f59-bd8e-c9c858a23170">
 ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
Hi @docal555, thanks for reporting this! This bug is being discussed in https://github.com/rstudio/rstudio/issues/13220 and a fix is in progress! Please follow along there for updates.

**Comment by docal555** [comment]
the viewer is completely f*** up. Skip past the first 50 columns, filter does not work, sorting does not work....

**Comment by ronblum** [comment]
@docal555 I understand your frustrations. However, I would appreciate it if you refrain from profanities on here.

**Comment by docal555** [comment]
Yep, understood. Sorry

**Comment by ronblum** [comment]
Thanks! 😄
