### ISSUE TITLE
"R Session Aborted" message when quitting RStudio with child processes running

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13272]
### System details

    RStudio Edition : 2023.08.0-daily+34
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Ventura 13.4
    R Version       : R version 4.3.0 (2023-04-21)

### Steps to reproduce the problem

Create a detached process in the background, with e.g.

```
system("sleep 100", wait = FALSE)
```

Then, try to restart the R session.

### Describe the problem in detail

The "R Session Aborted" message is displayed:

<img width="554" alt="Screenshot 2023-06-21 at 12 27 26 PM" src="https://github.com/rstudio/rstudio/assets/1976582/e84af7e2-e987-4ac6-a4a9-c5d7306946b2">

### Describe the behavior you expected

No aborted message.

---

<details>

<summary>Session Info</summary>

``` r
R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.0  tools_4.3.0     rstudioapi_0.14 renv_0.17.3-88 
```

</details>

**Comment by kevinushey** [comment]
The logs have:

```
Jun 21 12:53:59 MBP-P2MQ rsession-kevin[40756]: ERROR system error 48 (Address already in use); OCCURRED AT rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(SocketAcceptorService<boost::asio::ip::tcp> &, const std::string &, const std::string &) src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:141; LOGGED FROM: int main(int, char *const *) src/cpp/session/SessionMain.cpp:2304
```

And, indeed:

```
$ lsof -i :32715
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Electron  30305 kevin   20u  IPv4 0xee268305de573b7b      0t0  TCP localhost:62966->localhost:32715 (ESTABLISHED)
Electron  30305 kevin   22u  IPv4 0xee268305dcda391b      0t0  TCP localhost:62967->localhost:32715 (ESTABLISHED)
Electron  30305 kevin   23u  IPv4 0xee268305de56f91b      0t0  TCP localhost:62972->localhost:32715 (ESTABLISHED)
sleep     43172 kevin    5u  IPv4 0xee268305dcd6b91b      0t0  TCP localhost:32715 (LISTEN)
sleep     43172 kevin   34u  IPv4 0xee268305de38ee0b      0t0  TCP localhost:32715->localhost:62949 (CLOSED)
```

I think we're ended up in a state where R is forking to run the child process, which is inheriting the associated connection. However, when R is shut down, the child process remains alive, and holds onto that TCP connection. Hence, when we try to restart and reuse the same port, that fails.

**Comment by jonvanausdeln** [comment]
Verified in 2023.09.0-daily+203
Windows 11, Ubuntu 22.04

R can now be restarted without the aborted message.
