### ISSUE TITLE
R Studio doesn't open

### ISSUE THREAD

**Issue by dgraetz** [rstudio/rstudio#13274]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-2023.06.0-421
    OS Version      :  Win 11
    R Version       :  4.3.1

### Steps to reproduce the problem

I reinstalled R and R Studio from the website.

### Describe the problem in detail

R Studio-2023.06.0-421 does not open. An Error message is shown instead, titled "Unhandled Exception". The error message is "Unexpected token 'I', "INDX(". Base R works.
R Studio 2021.09.2+ 382 works
R Studio 2023.03.2+ 454 does not give an error message and does not show up. Starts three processes visible in task manager that cannot be closed.
 
### Describe the behavior you expected

R Studio opens.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dgraetz** [comment]
Managed to fix it. Not sure what exactly helped, but I uninstalled R and R Studio, deleted the R and R Studio folders in C:/Users/username/AppData/Local and C:/Users/username/AppData/Roaming and cleared up the System Environment Variables based on the output in log files.

**Comment by ronblum** [comment]
@dgraetz Glad that it worked out! Not ideal, I realize, but sometimes just reseting state (deleting the AppDate folders) will work.
