### ISSUE TITLE
Switching between visual and source editor for qmd files

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [rstudio/rstudio#13285]
Hi, 
    1. when I switch between visual and source editor in RStudio the title of my file is changing in the tab to red colour
    so I need to save it to preserve changes. I did not do anything apart from switching between editors.
    Why is that ? Is it normal behaviour ?
   2. is there any auto formatting turned on for qmd files ? I mean when I write :::: (4) colons down in source editor,
    after saving a file, closing and opening it again in visual editor, I have got ::: (3) instead of :::: (4) colons that I previously had written. Why is that ?
It doesn't seem like an expected or "designed" behavior.

I am on windows 10, quarto version 1.3.361, R version 4.3.0 patched, Rstudio 2023.08.0 Build 60 and 2023.06.0 Build 421.

**Comment by ronblum** [comment]
@Andrzej-Andrzej Thank you for raising this!

For the first thing:
1. Can you grab screenshots of what happens in source and visual mode?
2. What's the YAML, so that I can try to reproduce.
3. What editor theme are you using?

For the second: This is expected behavior—the source code might change to conform to Pandoc standard, as described in the [Quarto "Markdown Output" page](https://quarto.org/docs/visual-editor/markdown.html#overview). Is the display in visual mode, as well as when rendering the file, affected?

**Comment by Andrzej-Andrzej** [comment]
Thank you, I will prepare screenshots.

**Comment by Andrzej-Andrzej** [comment]
Code (qmd file) and screenshots as requested: 

````
---
title: "Just a title"
author: "Andrzej"
format: revealjs
execute:
  echo: true
  output: true
  eval: true
---

# Data - creating data,

::: columns
::: {.column width="75%"}
```{r}
#| output-location: column-fragment
#| code-overflow: wrap

library(tidyverse)
library(magrittr)

dats <- rnorm(20, 4, 5) %>% as.data.frame()

dats %<>% dplyr::rename(Variable1 = ".")

dats

```
:::
:::

# The end

````

Before visual:

![obraz](https://github.com/rstudio/rstudio/assets/28902421/ca9becd8-af1f-42db-9ada-206053d7e644)

After short rundtripping to visual and back to source:

![obraz](https://github.com/rstudio/rstudio/assets/28902421/7413204c-c4ff-4dc9-a1e0-4c6d1f1b2a98)

As you can see, number of colons has changed.
Is it possible to keep number of colons as in source editor somehow, but using visual as well to insert pictures , etc.? 
When I go back to source I want to have the same number of colons as before that roundtripping to visual. Is that possible ? 
Thank you for your kind help.
