### ISSUE TITLE
Add note about git pane not appearing if git repo is in an unsafe directory

### ISSUE THREAD

**Issue by kelli-rstudio** [rstudio/rstudio#13283]
Follow up to https://github.com/rstudio/rstudio-pro/issues/4536 - no product changes need to be made as a result of this issue but would be helpful to add a note in the docs. Perhaps in this section: https://docs.posit.co/ide/user/ide/guide/tools/version-control.html#additional-topics

Users on server environments may experience issues with the git pane not appearing in the RStudio IDE if they create a git-enabled project in a folder that they do not own. This is due to a security fix in git 2.35.2 that disables git repos that are created in directories that are not owned by the user. The user needs to mark the offending directory as safe by adding it with the git config [safe.directory](https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory) variable then the git pane will appear after the uses closes and reopens the project. 

The user will also notice git error messages in Rstudio terminal when submitting git commands. For example:
```
(base) kelli@ip-172-98-0-39:~/ubuntu22-git-test/at-folder$ git status
fatal: detected dubious ownership in repository at '/home/kelli/ubuntu22-git-test/at-folder'
To add an exception for this directory, call:

        git config --global --add safe.directory /home/kelli/ubuntu22-git-test/at-folder
```
This error is not specific to the Rstudio IDE terminal and will also be fixed when the offending directory is marked as safe with the command above.

**Comment by ronblum** [comment]
Verified in RStudio User Guide 2023.09.0 revision 32 at https://docs.posit.co/ide/user/2023.09.0/ide/guide/tools/version-control.html#git-is-installed-but-the-git-pane-doesnt-appear
