### ISSUE TITLE
Issue with data viewer - arrows to view beyond 50 columns not working

### ISSUE THREAD

**Issue by sjackson1236** [rstudio/rstudio#13289]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.06.0 Build 421
    OS Version      : macOS Ventura 13.4.1
    R Version       : 4.3.0

### Steps to reproduce the problem

Create any data frame with more than 50 columns

### Describe the problem in detail

In the RStudio Viewer, the ">, >>, <, <<" buttons to view columns beyond the first 50 do not work. i.e. "Cols: << < 1-50 > >>"

### Describe the behavior you expected

Previously it would show the next set of columns

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
@sjackson1236 , thank you for the report. This issue has been identified and a fix will be in an upcoming patch.

Please see https://github.com/rstudio/rstudio/issues/13220

**Comment by sjackson1236** [comment]
sorry about that - thanks!
