### ISSUE TITLE
Autocomplete issue with list element names using numbers

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#13290]
### System details

    RStudio Edition : All
    RStudio Version : 2023.06.0-421
    OS Version      : All
    R Version       : All

### Steps to reproduce the problem

This was reported in https://github.com/rstudio/rstudio/issues/11503#issuecomment-1608056211

'''
> list_name <- list("2022" = c(1, 2, 3))
> list_name$2022
Error: unexpected numeric constant in "list_name$2022"
'''

Autocomplete after `list_name$` + tab doesn't add tick marks appropriately

### Describe the behavior you expected

This appears to have last worked correctly in Spotted Wakerobin 2022.07.2+576.
2022.12.0-353 (Elsbeth Geranium),  2023.03.1-446 (Cherry Blossom) and 2023.06.0-421 (Mountain Hyddrangea) all have the issue.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/blob/499043d831732afcacca5376fed6d2c020e50207/src/gwt/src/org/rstudio/core/client/RegexUtil.java#L34-L39

We need to exclude numbers from the first characters.

We could also consider whether we can make use of unicode regular expressions, e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode, so we can make use of "ID_start" and "ID_continue" characters: https://unicode.org/reports/tr31/

**Comment by sharon-wang** [comment]
Related issues (might be duplicates)
- https://github.com/rstudio/rstudio/issues/6687
- https://github.com/rstudio/rstudio/issues/12555

**Comment by ronblum** [comment]
I closed the older issues as duplicates, for consolidation.

History:
- This worked from 1.0.153 through 1.2.5042
- Broke in 1.3.1093
- Worked again from 1.4.1106 through 2022.07.2-576
- Broke again in 2022.12.0-353 and up through the latest build, 2023.08.0-daily+160

**Comment by ronblum** [comment]
*Another example with data frames, reported by @BartJanvanRossum in #15343:*

Create a data.frame and try to access the information in the first column using tab completion after the $ sign.
```r
df <- data.frame("1" = 1:3, check.names = FALSE)
df$
```
Autocomplete completes the line above as df$1 instead of the correct ``` df$`1` ```.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+336.pro2 on Windows 11 using the list and data frame examples described above.
