### ISSUE TITLE
Grey out entire screen except for cursor

### ISSUE THREAD

**Issue by Ddfulton** [rstudio/rstudio#13297]
Been cruising around the editor in vim and often lose track of where my cursor is after a big search n' scroll. Would be cool to do what iTerm2 does:

<img width="871" alt="image" src="https://github.com/rstudio/rstudio/assets/12734718/529ea874-f626-44cd-9748-5c3fd3aa5510">

**Comment by ronblum** [comment]
@Ddfulton Thank you for the suggestion and for including a point of reference!
