### ISSUE TITLE
Numeric Columns shows unknown when data frame only has single row

### ISSUE THREAD

**Issue by Leonhardt117** [rstudio/rstudio#13293]
### System details

    RStudio Edition : <Desktop>
    RStudio Version : 2023.06
    OS Version      : 
    R Version       :  4.3.1

### Steps to reproduce the problem
library(data.table)

DS <- data.table(
  ID = c("101", "102", "103", "104", "105"),
  BALANCE = c(500.25, 1000.50, 1500.75, 2000.00, 2500.25)
)

DS2 <- DS[ID == '101',]
DS2 <- subset(DS, ID == '101')
### Describe the problem in detail
the info of a numeric column displayed on hover shows 'unknown' if a data frame only has a single row. 
### Describe the behavior you expected
It should display 'Numeric'

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Leonhardt117 Thank you for raising the issue!

I can reproduce this in RStudio Desktop 2022.07.2+576 on MacOS, as well.
