### ISSUE TITLE
RStudio must let us choose R if it could not find R or if RStudio crash

### ISSUE THREAD

**Issue by Mahmood-Taghavi** [rstudio/rstudio#13299]
I have had two disappointing experiences with  RStudio:
1. First when I incorrectly specified the R location in RStudio, I saw RStudio cannot load R, and the menu for choosing R was not available so I was forced to delete the configuration files of Rstudio to be able to use that again! 
2. Second, when I have a clean installation of Rstudio and R but did not save R location in the Windows registry during setup. I tried to normally Run RStudio but it asked me to install R before starting the RStudio while I expected it to let us to chose R. 
So, I mean RStudio should always provide a chance for a user to specify the R location if it could not find R or if the specified R crash!

**Comment by ronblum** [comment]
@Mahmood-Taghavi Thank you for raising this! Are you using Windows? If so, the menu R-selection menu will appear if you click on the <kbd>Ctrl</kbd> during startup.

**Comment by Mahmood-Taghavi** [comment]
Thank you @ronblum for your prompt response. Yes, indeed I use Windows 10 (22H2) with the latest RStudio desktop (RStudio-2023.06.0-421). RStudio just shows a message box entitled "R Not installed" with two options "Yes" which opens the official R website, and "No" which just closes that message box and nothing happens then. I expect that by clicking the "No" button, RStudio opens the R-selection window to let me specify the location of the installed R.
![RStudio do not let me to choose portable R](https://github.com/rstudio/rstudio/assets/18240221/b95b032b-1239-41fc-85e8-90aeed00961e)

**Comment by ronblum** [comment]
What directory is R installed in? Even if R isn't in the registry, RStudio will look for it in some directories.

**Comment by Mahmood-Taghavi** [comment]
I try to make a portable RStudio and R for myself. As you mentioned RStudio should look at 'R\R-x.x.x\' as well. 
So I put R inside of the installed RStudio folder at the below address:
'C:\Rplus\RStudio\R\R-4.3.1'
However, still it has the same problem, RStudio cannot start as it could not find R in the Windows registry and there is no way to specify the correct path to R. 
If RStudio has any command line parameter that lets us to config this setting that would also definitely help!

**Comment by ronblum** [comment]
You can set the variable `RSTUDIO_WHICH_R`. For example, I moved my R 4.3.0 directory to the root and set the environment variable:
`RSTUDIO_WHICH_R=C:\R-4.3.0\bin\x64\Rterm.exe`
so for you I think it'd be
`RSTUDIO_WHICH_R=C:\Rplus\RStudio\R\R-4.3.1\bin\x64\Rterm.exe`
Does that work?

**Comment by ronblum** [comment]
@Mahmood-Taghavi Glad this solution works! I also filed a documentation request for this, #13306.
