### ISSUE TITLE
Git Revert does nothing despite massive amounts of change between local and remote branches. 

### ISSUE THREAD

**Issue by akframe1** [rstudio/rstudio#13303]
### System details
RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
make a change to a csv file in a local branch then click revert so that it will revert back to the remote branch. nothing will happne.

### Describe the problem in detail
NOTHING HAPPENS WHEN YOU CLICK GIT REVERT. IT ASKS TO BE SURE THEN DOES NOTHING. SIMPLE GIT SHOULD BE THE BREAD AND BUTTER OF ANY IDE
### Describe the behavior you expected
I expect it to revert all my local changes, as thats what git revert does. if not, I expect an error saying it was unable. Nothing happens instead. Unacceptable. 

![image](https://github.com/rstudio/rstudio/assets/104936766/d324c00c-f08c-4874-a298-2a61c35d0bf1)

![image](https://github.com/rstudio/rstudio/assets/104936766/60a80f6e-1a08-4244-91c2-7a4b74ce4b85)

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@akframe1 Thank you for raising this! The "A" next to the staged file and the question marks next to the rest suggest that these are new files, which would explain why revert isn't working properly.

1. Can you provide a screenshot of the Git Pane, rather than the Git pop-up window?
2. What happens if you revert in the Git Pane, not the window?

**Comment by kevinushey** [comment]
"Revert Changes" here does not run `git revert` -- it unstages and discards the changes you've made in the file, reverting to the "original" state for that file on the branch. It's the moral equivalent of:

```
git reset HEAD -- <file>
git checkout -f -- <file>
```
