### ISSUE TITLE
Copilot: provide means for updating Copilot agent

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13307]
Since the resources provided from https://github.com/github/copilot.vim/tree/release/dist may update over time.

Right now, we pin the commit here: https://github.com/rstudio/rstudio/blob/e444633ccd5c7b12fa4052868ca946e96fed2155/src/cpp/session/modules/SessionCopilot.R#L25-L27

**Comment by petetronic** [comment]
@jthomasmock can we defer this to Chocolate Cosmos?

**Comment by kevinushey** [comment]
Chatted with @jthomasmock, and I think we're happy with the current behavior. We don't want to make it too easy to change the version of the Copilot agent used, as we have no way for QA to verify that older or newer versions of the Copilot agent will be functional with RStudio. For that reason, we don't need to provide any explicit UI for changing or updating the Copilot agent version.

That said, if a user needs to change the version of Copilot used for other reasons, they can do something like:

```
options(rstudio.copilot.repositoryRef = <commit hash>)
rstudioapi::executeCommand("copilotInstallAgent")  # or, equivalently, run from command palette
```

and that should be sufficient as an escape hatch if needed in the future.
