### ISSUE TITLE
Paste commands only (paste without the ">")

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#13319]
Hello,

In the context menu (right-click) of Rgui, there is a nice feature: *"paste commands only"*. That means if you copy such a code:

```r
> library(rgl)
> shade3d(cube3d(), color = "red")
```

and you do *"paste commands only"*, that will paste the code without the ">" at the beginning of the lines. 

I'd like to have this feature in RStudio.

**Comment by ronblum** [comment]
@stla Thank you for the suggestion!
