### ISSUE TITLE
No way to cancel GitHub Copilot Auth Flow

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#13312]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.08
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. Navigate to the GitHub Copilot options pane.
2. Enable GitHub Copilot, if not enabled
3. If prompted, installed the GitHub agent
4. If already signed into GitHub Copilot, click the sign out button
5. Click the sign in button.
6. Close the authentication page that opens in the browser.

### Describe the problem in detail

The UI in the IDE sits at this page forever:
![image](https://github.com/rstudio/rstudio/assets/37987486/178d1e17-ef15-4384-b93a-2f7aba57a8eb)

There's no indication given to the IDE that the browser was closed without completing the auth flow, so it sits there waiting. The only way to get out of it is to quit the IDE.

### Describe the behavior you expected

The `Cancel` button should be interact-able

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in 2023.09.0-daily+290 on MacOS 13.5. However, the <kbd>Cancel</kbd> option is almost indistinguishable from the rest, so I overlooked it the first couple of times that I tried it—I kept trying the big grayed-out button below. Is there any way to distinguish it a little more, such as by putting a border around it so that it looks like a button?

**Comment by ronblum** [comment]
Closing as verified, since this works.
