### ISSUE TITLE
Find/Search bar: show number of occurrences of search term in search bar

### ISSUE THREAD

**Issue by IZE85** [rstudio/rstudio#13316]
Hi, when searching for a term in a script, it would be great for RStudio to show the number of finds/occurrences of the searched term in the search bar. e.g,. "1/3" (one of three), meaning you are at the first of three possible occurrences of the search term.

Is there a possibility to show this in the client?

Kind regards

**Comment by ronblum** [comment]
@IZE85 Good suggestion—we'll review it as we continue to develop RStudio.

**Comment by IZE85** [comment]
Thank you!
