### ISSUE TITLE
RStudio Internationalization for Persian language

### ISSUE THREAD

**Issue by Mahmood-Taghavi** [rstudio/rstudio#13323]
I am the coordinator of the R translation team for the Persian language. I am interested to provide Persian translation for the RStudio as well. I see RStudio is translated into French as described at https://github.com/rstudio/rstudio/wiki/Internationalization-(i18n). However, I don't know where to get the list of English phrases to translate them into Persian and how should I send the translated phrases back to the RStudio then.

**Comment by kevinushey** [comment]
Thanks for your interest, and sorry for the slow response!

Unfortunately, we don't have a cleanly-documented process for the submission of new translations. However, the general idea is that languages map keys to their translation in files of the form `_<id>.properties`. For example, all of the English property files:

```
$ find . -name '*_en.properties'
./org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooserRmdTemplateChooserUiBinderImplGenMessages_en.properties
./org/rstudio/studio/client/rmarkdown/ui/ShinyDocumentWarningShinyDocumentWarningUiBinderImplGenMessages_en.properties
./org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsWidgetRmdTemplateOptionsWidgetUiBinderImplGenMessages_en.properties
./org/rstudio/studio/client/rmarkdown/RMarkdownConstants_en.properties
./org/rstudio/studio/client/packrat/PackratConstants_en.properties
< ... >
```

There are also translations in the desktop part of the IDE which are slightly different, e.g.

https://github.com/rstudio/rstudio/blob/feature/copilot-completion-keys/src/node/desktop/src/assets/locales/en.json

You'd just need to provide an equivalent `fa.json` file for the desktop strings.
In theory, we could start accepting translations of the form `_fa.properties` (I believe 'fa' is the correct language code for Persian?), and then later add tooling to the IDE to include Persian as an accepted language.

**Comment by kevinushey** [comment]
One of the bigger downsides, though: currently, RStudio's UI isn't set up to handle RTL text cleanly; we'd likely need to do a fair amount of work to support that here.

**Comment by Mahmood-Taghavi** [comment]
Thanks, @kevinushey for your insightful response :) Yes, the language code of the Persian language is "fa". 
Although it is a Right-To_left language, I think some basic support is natively provided by the operating system. 
So, at this stage, we can treat it like any left-to-right language such as English and French and then I can let you know if any refinement is needed.
I have implemented a minimal translation for the internationalization of RStudio into the Persian(fa) language in the below fork of RStudio. However, I don't know how to test it on the RStudio application! 
[RStudio i18n: Persian (fa) language](https://github.com/Mahmood-Taghavi/rstudio/commit/2f590e09d0b062b6f14408b126468e182bdac5db)

P.S. What are *.pak files in the "locales" folder of the compiled RStudio. Are they generated by compiling _<id>.properties translation files? Is there any trick to easily re-compile them without the need to set up a compiling environment for RStudsio?

Any help is appreciated!

**Comment by kevinushey** [comment]
> P.S. What are *.pak files in the "locales" folder of the compiled RStudio. Are they generated by compiling _.properties translation files? Is there any trick to easily re-compile them without the need to set up a compiling environment for RStudsio?

I think those are Electron-specific files; I don't think there's anything specifically relevant to RStudio localization here.
