### ISSUE TITLE
Warnings are thrown when running a R chunks interactively in Quarto document

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#13326]
Initially asked at 
* https://github.com/yihui/knitr/issues/2267 
* https://github.com/quarto-dev/quarto/issues/211

Other related issues

* https://github.com/quarto-dev/quarto-cli/issues/6341

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.8.0.196
    OS Version      : Windows 11 x64 (build 22621)
    R Version       : R version 4.3.1 (2023-06-16 ucrt)

### Steps to reproduce the problem

* Take this Qmd document

````markdown
---
title: Table
format: html
---

```{r}
#| label: tbl-tab
#| tbl-cap: "mtcars table"
#| tbl-subcap:
#|  - "head = 5"
#|  - "tail = 5"
knitr::kable(head(mtcars, 5))
knitr::kable(tail(mtcars, 5))
```

Look at Table @tbl-tab, just look at it.

````

* Put in a .qmd document 
* Render interactively the chunk  => Warnings
* Render the document 

Then adapt the chunk opions removing `=`
````yaml
#| tbl-subcap:
#|  - "head is 5"
#|  - "tail is 5"
````

Then run interactively, and no more warnings. 

So it seems the parsing with the characters like `=` is causing wrong parsing. 

### Describe the problem in detail

Running the chunk will throw warnings where I don't think it should 
````r
Warning messages:
1: In value[[3L]](cond) : Failed to parse chunk options in body:
Error in parse(text = code, keep.source = FALSE): <text>:1:24: unexpected symbol
1: alist( label: tbl-tab1 tbl
                           ^

2: In opts$engine <- unlist(strsplit(rmdChunkOpts, split = "(\\s|,)+"))[[1]] :
  Coercing LHS to a list
````

One of the warning is definitely from IDE code base 
https://github.com/rstudio/rstudio/blob/a9a0652e3feac02a05caeead5d54e370f3ec4209/src/cpp/session/modules/SessionRmdNotebook.R#L686

Rendering the document is not throwing any warnings, so it seems this is because of some IDE processing probably

### Describe the behavior you expected

No warning shown in the IDE 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Triage: Proposed for possible inclusion in Desert Flower if feasisble.

**Comment by kevinushey** [comment]
This comes from here:

https://github.com/rstudio/rstudio/blob/863683c178621d8a939187c4bbac3b6387ff1f87/src/cpp/session/modules/SessionRmdNotebook.R#L620-L624

We use a very lazy heuristic to guess whether the chunk options appear to be YAML-style or R-code-style options. We probably need something better that more closely models whatever knitr is doing under the hood.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+84 on MacOS 14 using the example above.
