### ISSUE TITLE
Confirm that RStudio can launch successfully on M1 / M2 macOS machines without Rosetta installed

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13335]
We received a report that the latest daily build of RStudio was unable to launch unless Rosetta was installed, even with an arm64 build of R installed. We should try to reproduce this locally, and if so, try to resolve this as RStudio should still be functional without Rosetta.

**Comment by sharon-wang** [comment]
Related: #12791

**Comment by sharon-wang** [comment]
I tried to reproduce this with the latest daily, but I was able to launch and use the Viewer and plots. I'm not sure which components we ship are Intel-only. Maybe the user had a Quarto document open which interfered with starting up the IDE? (Quarto functionality seems to require Rosetta)

### My Steps
1. Install arm64 build of R (4.3.1)
2. Check that rosetta is not installed (no output from `pgrep oahd`)
3. Install daily build of RStudio ([2023.09.0-daily+332](https://dailies.rstudio.com/version/2023.09.0-daily+332))
4. Open RStudio app
    - `plot(iris)`: ✅ 
    - `View(iris)`: ✅ 
    - Create Quarto document:`State not recoverable` error, reported in #12791

**Comment by kevinushey** [comment]
In the absence of more information, I think we can mark this issue as resolved? Especially since now we prompt the user to install Rosetta on startup.
