### ISSUE TITLE
Inspect Elements gives javascript exception after electron update

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#13336]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.08.0-daily+197
    OS Version      : Windows11, MacOS 12.6
    R Version       : 

### Steps to reproduce the problem
1. Install daily build after electron update .. starts with 2023.08.0-daily+197
2. Right click on console window (or anywhere)
3. Select "Inspect Element"

### Describe the problem in detail

<img width="418" alt="image" src="https://github.com/rstudio/rstudio/assets/6433789/762b9a1c-b8c8-4ab8-b048-2da051788e23">

### Describe the behavior you expected

It should open up the chrome dev tools window and highlight the element.  This feature is often used in writing automated tests.

I reproduced on Windows and MacOS.. I didn't check Linux, but assume it will as well there.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Note.. you can still toggle on the developer tools from the `Help -> Diagnostics` menu.  But inspect element still errors.

**Comment by timtmok** [comment]
This is going to affect the image saving action in the context menu on plots.

**Comment by jonvanausdeln** [comment]
Verified on Desktop [2023.09.0-daily+217](https://dailies.rstudio.com/version/2023.09.0-daily+217)
Windows 11

Context menu now works for "inspect element" and saving via plots pane
