### ISSUE TITLE
Long running task in console also trigger a stop button in Viewer pane

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#13330]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.8.0.196
    OS Version      : Windows 11 x64 (build 22621)
    R Version       : R version 4.3.1 (2023-06-16 ucrt)

### Steps to reproduce the problem

I don't know if this is intended or not. It is not a problem per se but if this is undesired, I figured it was useful to report as I observed it by chance. If it could help improve the product and prevent maybe side effect... 

Otherwise feel free to close ! 

* Open Console and Viewer Pane
* Run a long running task in Console  like `Sys.sleep(10)`
* The red stop button will show in Console **but also in the Viewer** 

### Describe the problem in detail

* The red stop button will show in Console **but also in the Viewer** 
* clicking on the button in the viewer pane will stop the running task like it does with the console red button 

https://github.com/rstudio/rstudio/assets/6791940/7f0c66f6-e512-4ff4-8705-43f333add82f

### Describe the behavior you expected

No red stop button in the viewer as this seems confusing to me. Especially because there is no plot involved in the task, and no viewer invoved.

**Comment by ronblum** [comment]
@kevinushey Is this intended?

Note that it shows up in the Viewer Pane if there's a Shiny app running in there, though that seems reasonable.

**Comment by cderv** [comment]
This is still relevant with latest dailies, but again 

> I figured it was useful to report as I observed it by chance. If it could help improve the product and prevent maybe side effect...
