### ISSUE TITLE
Sorted Data Viewer rows are restored to original order when going to the next 50 columns

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13338]
1. Create the following data frame: `df <- as.data.frame(matrix(10:1, nrow=10, ncol = 190))`
2. <kbd>View(df)</kbd>
3. Sort by column 1.
4. Go to the next 50 columns

After sorting, traversing to the next 50 columns, etc., restores the original order of the data frame instead of keeping the most recent sort. 

Initial view:
<img width="304" alt="initial" src="https://github.com/rstudio/rstudio/assets/31009952/be1d1934-db46-4e4b-b31c-360793c16556">

Sorted by column 1 (or any column, since they're all the same):
<img width="306" alt="sorted" src="https://github.com/rstudio/rstudio/assets/31009952/bb1a946e-0d45-4d89-9191-78a9ee9377d6">

After going to the next 50 columns:
<img width="347" alt="next_page" src="https://github.com/rstudio/rstudio/assets/31009952/06cedfb0-c6ff-4ded-8aa5-eb859b690312">

It would be useful if the most recent sort were maintained.

**Comment by sharon-wang** [comment]
Possible Duplicate: https://github.com/rstudio/rstudio/issues/6147

**Comment by sharon-wang** [comment]
Ah gotcha, makes sense to me to keep both of them!

**Comment by rangaro** [comment]
I have a larger data set in which I wanted to sort the dataset by certain columns. While clicking on the sort arrows does something, I would not call the result a sorted dataset. The values in the columns are still not in the correct order. However, whatever sort does, it does it reliably. I always end up with the same wrong order of values.

**Comment by rangaro** [comment]
In V 2023.03.2, it works fine.

**Comment by ronblum** [comment]
@rangaro This problem is addressed in issue #13328 and the upcoming patch release will include the fix for it.
