### ISSUE TITLE
"Update Available" dialog not popping up

### ISSUE THREAD

**Issue by sharon-wang** [rstudio/rstudio#13347]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0
    OS Version      : **UPDATE** this probably happens on all OS's, as long as the user has never ignored an update before, or has removed their ignored updates list (original: Ubuntu 22, Windows 11)
    R Version       : any

### Steps to reproduce the problem

Pre-req: you have never ignored updates on the machine or you've removed your list of ignored updates

1. Install a `2023.06.0` build ~for Ubuntu 22 or Windows 11 (doesn't seem to occur with Mac)~
2. Open the IDE
3. Expect to get an "Update Available" dialog once the IDE starts up, to update to `2023.06.1`

### Describe the problem in detail

The "Update Available" dialog doesn't show on Linux/Windows automatically on startup, nor does it show when manually checking for updates via Help > Check for Updates.

Upon inspecting the network requests, the IDE successfully retrieves the information regarding the new update, but fails to display the dialog.

On Linux, the console shows:

```
ERROR: Processing client events
ConsoleLogger.java:55 Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read properties of undefined (reading 'updates')
ConsoleLogger.java:33 TypeError: Cannot read properties of undefined (reading 'updates')
    at $getIgnoredUpdates_0_g$ (IgnoredUpdates.java:29:1)
    at DesktopApplicationHeader$IgnoredUpdatesStateValue_1_g$.getIgnoredUpdates_1_g$ [as getIgnoredUpdates_2_g$] (DesktopApplicationHeader.java:228:1)
    ...
```

We might be missing a step to create the persistent file for updates, or otherwise something is going wrong with the ignored updates file. This errors and the IDE can't continue to displaying the new update, despite having the information to do it!

### Describe the behavior you expected

When a new major/minor/patch version is related, the user should be presented with the "Update Available" dialog.

If a user is manually checking for updates, we should bypass any code related to ignored updates, because they are not relevant during a manual check.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
~- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).~
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
For QA: give me a shout when you pick this up, and I'll send you some custom builds to test with!

**Comment by jonvanausdeln** [comment]
Fix looks to work using the custom builds.  Updated dialog was correctly offered, and persist file was created.
