### ISSUE TITLE
start rstudio in server ,rstudio can't   display chinese and   Enter Chinese

### ISSUE THREAD

**Issue by nolanjj** [rstudio/rstudio#13349]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353
    OS Version      :  centos
    R Version       : 4.2.0

### Steps to reproduce the problem

I install MobaXterm v23.2.
open  MobaXterm ssh to server
then

I install R and rstudio in conda env
conda create -n 16s 
conda activate 16s
conda install r-base=4.2.0
conda install -c conda-forge rstudio-desktop

I run rstudio command in terminal

then rstudio is open
![image](https://github.com/rstudio/rstudio/assets/35267241/33b4198b-39ce-4e87-aa24-a35365310402)

### Describe the problem in detail

 I find a problem,it can't display chinese
and I can't  Enter Chinese.
I don't know why.
I don't know if it's rstudio problem or MobaXtrem problem

### Describe the behavior you expected
I want to  display chinese and   Enter Chinese

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by nolanjj** [comment]
> 

1. In standalone R,It's normal
![image](https://github.com/rstudio/rstudio/assets/35267241/d9267441-3e9e-418c-bf78-2737a9ce6928)

2.
![image](https://github.com/rstudio/rstudio/assets/35267241/f985497e-1956-4aa5-9044-f54ad241fb0a)

3.
![image](https://github.com/rstudio/rstudio/assets/35267241/118920a5-29b7-4e2e-a626-f8c13f8a80e9)

3.
![image](https://github.com/rstudio/rstudio/assets/35267241/0394c7b4-8c60-4ebe-be43-6e8b1f38de8a)

**Comment by ronblum** [comment]
Thanks! One thing: Can you run `Sys.locale` in RStudio?

**Comment by nolanjj** [comment]
> Thanks! One thing: Can you run `Sys.locale` in RStudio?

Thank you, I can't run Sys.locale in Rstudio
![image](https://github.com/rstudio/rstudio/assets/35267241/25ae812c-47a7-43ba-b5ec-32076d5c6f56)

**Comment by ronblum** [comment]
Oops! I meant `Sys.getlocale()`

That said, @timtmok do you have any suggestions? I tried reproducing this by changing my system to use Chinese (simplified), and the locale changed, but R is using Lithuanian!

```
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20 (64-bit)

R yra laisvoji programinė įranga ir ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS.
Jūs galite perskirstyti tam tikromis sąlygomis.
Surinkite 'license()' or 'licence()' norėdami sužinoti platinimo informaciją.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Norėdami pamatyti kelis pavyzdžius surinkite 'demo()', skaityti internetinį žinyną - 'help()' arba 
atverkite naršyklę norėdami gauti pagalbą - 'help.start()'.
Norėdami baigti darbą su R, surinkite 'q()'.

[Atkurta anksčiau išsaugota darbo aplinka]

> Sys.getlocale()
[1] "C/UTF-8/C/C/C/C"
> quit()
Save workspace image? [y/n/c]: n
ronblum@Rons-Busy-Bee ~ % locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by ronblum** [comment]
And in RStudio, `Sys.getlocal()` is still using English.

```
> Sys.getlocale()
[1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"
```

**Comment by timtmok** [comment]
I don't think this would be an issue with MobaXterm. The X Server protocol works with pixels so I think that eliminates it as the source. It's likely with font support.

@nolanjj Is this file in your workspace also using Chinese in the filename?

![image](https://github.com/rstudio/rstudio/assets/9591545/7d60a5c7-89bb-4c54-ad6d-4a1e750e253d)

Can you try changing the font in Global Options -> Appearance -> Editor font? If changing that doesn't work, you can try installing another Chinese supported monospace font and switching to that in RStudio.

As a last resort, you could change the system locale to English or set the environment variable `LANGUAGE=en_US` for RStudio if you didn't want it to change system-wide. I think this comes down to the OS lacking a monospace font that supports Chinese.
