### ISSUE TITLE
Error when starting Rstudio

### ISSUE THREAD

**Issue by realrealf** [rstudio/rstudio#13354]
### System details

    RStudio Edition : RStudio 2023.06.1+524 "Mountain Hydrangea " (547dcf86, 2023-07-06) for macOS
    RStudio Version : Mountain Hydrangea, 2023.06.1+524
    OS Version      : Ventura 13.4.1 (22F82)
    R Version       : R version 4.3.1 (2023-06-16) -- "Beagle Scouts"

### Steps to reproduce the problem

The problem occurred suddenly, no plan how to reproduce the error
### Describe the problem in detail

Rgui can be started and works, but the connection to Rstudio does not work. When typing in > Sys.which("R") in RGui, the following is the output: 
                 R 
"/usr/local/bin/R"

although R.app is installed under applications and not in the bin. Is that causing issues?

### Describe the behavior you expected

The following error occurred: 

/Users/username/.local/share/rstudio/log/rsession-username.log
2023-07-12T14:21:27.894940Z [rsession-username] ERROR offlineConnectionMatcher: ignoring connection received in the future; LOGGED FROM: bool rstudio::session::offlineConnectionMatcher(boost::shared_ptr<HttpConnection>, std::chrono::steady_clock::time_point) src/cpp/session/SessionOfflineService.cpp:131
2023-07-12T14:21:27.895053Z [rsession-username] ERROR offlineConnectionMatcher: ignoring connection received in the future; LOGGED FROM: bool rstudio::session::offlineConnectionMatcher(boost::shared_ptr<HttpConnection>, std::chrono::steady_clock::time_point) src/cpp/session/SessionOfflineService.cpp:131
2023-07-12T14:21:27.895156Z [rsession-username] ERROR offlineConnectionMatcher: ignoring connection received in the future; LOGGED FROM: bool rstudio::session::offlineConnectionMatcher(boost::shared_ptr<HttpConnection>, std::chrono::steady_clock::time_point) src/cpp/session/SessionOfflineService.cpp:131

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

```[tasklist]
### Tasks
```

**Comment by kevinushey** [comment]
Is your system clock correct?

**Comment by realrealf** [comment]
> Is your system clock correct?

What do you mean by correct? System clock is set to my local time and should automatically adjust depending on the place where I am (actually it is middle European summer time)

**Comment by kevinushey** [comment]
The error message suggests something odd might be going on with the system clock:

> 2023-07-12T14:21:27.894940Z [rsession-username] ERROR offlineConnectionMatcher: ignoring connection received in the future; LOGGED FROM: bool rstudio::session::offlineConnectionMatcher(boost::shared_ptr, std::chrono::steady_clock::time_point) src/cpp/session/SessionOfflineService.cpp:131

Hence the question.

**Comment by realrealf** [comment]
> The error message suggests something odd might be going on with the system clock:
> 
> > 2023-07-12T14:21:27.894940Z [rsession-username] ERROR offlineConnectionMatcher: ignoring connection received in the future; LOGGED FROM: bool rstudio::session::offlineConnectionMatcher(boost::shared_ptr, std::chrono::steady_clock::time_point) src/cpp/session/SessionOfflineService.cpp:131
> 
> Hence the question.

I See; do you have an idea what should be adjusted?
