### ISSUE TITLE
Can't paste into New project from various pop-up dialogues e.g. Git

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#13365]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0-daily+217
    OS Version      : Apple M1 Pro
    R Version       : 4.3.0

### Steps to reproduce the problem

- Copy the URL of a Git repo.
- In RStudio, go to New Project > From version control > Git
- Paste the URL (and observe that you can't paste it)

### Describe the problem in detail

In the last few dailies you can't paste into this dialogue, as well as some other pop-up ones.

<img width="675" alt="Screenshot 2023-07-13 at 1 18 43 PM" src="https://github.com/rstudio/rstudio/assets/5965649/06c2da34-20a4-4f93-978b-0c8c932e1e5b">

### Describe the behavior you expected

I expected to be able to paste the repo URL.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Thanks @mine-cetinkaya-rundel! Looks like this is a regression, as it works in RStudio Desktop 2023.06.1+524 on MacOS 13.4.

**Comment by ronblum** [comment]
Other examples:
- <kbd>Files -> Blank File -> [Any file type)</kbd>
- <kbd>Environment -> Import Dataset -> From Text (base) -> (Choose file) -> Name</kbd>

etc.

**Comment by kevinushey** [comment]
This seems like a weird focus issue. I can reproduce the issue, but it seems to go away if I click away from RStudio (focus a different window), then click back into RStudio. After doing that, I can then copy + paste as normal.

@ronblum, can you confirm whether the issue is macOS-specific?

**Comment by ronblum** [comment]
MacOS only—it works correctly on Windows 11 and Ubuntu 22.04.

**Comment by timtmok** [comment]
I'll check if this was a regression due to the Electron update and verify after taking the latest Electron (25.5.0).

**Comment by timtmok** [comment]
I think this was caused from disabling the menu when there is a dialog. The paste command ends up disabled.

**Comment by petetronic** [comment]
Tim's PR https://github.com/rstudio/rstudio/pull/13507

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.09.0-daily+348 on MacOS 14.
