### ISSUE TITLE
after pasting undoing the paste takes two ctrl-Z keystrokes

### ISSUE THREAD

**Issue by ergz** [rstudio/rstudio#13376]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for windows
    OS Version      :  Windows 11
    R Version       :  4.3.0

### Steps to reproduce the problem

Copy a piece of code that is two blocks (not sure if the two blocks is required), and paste into an R script by highlighting the code you want to replace, if you want to do undo this you must press ctrl+z twice (video attached), it seems the first undo reselects and then the actual undo happens after that.

### Describe the problem in detail
![takes-two-steps-to-undo](https://github.com/rstudio/rstudio/assets/10622214/fddde288-2d98-402d-99c0-bc25d74d84d4)

### Describe the behavior you expected

I would expect the undo to happen with just one press of the undo keyboard combination

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ergz Thank you for raising this! I might be seeing the same thing, but I'm not certain: Is the issue that the first <kbd>Ctrl-Z</kbd> is selecting the opening and closing brackets?
