### ISSUE TITLE
Very wide columns in Viewer with variable labels or long variable names

### ISSUE THREAD

**Issue by torfason** [rstudio/rstudio#13377]
Issue #2383 (Columns in Viewer are very wide when variable labels are displayed) describes the extreme width of columns when variables have labels, or when variable names are very long.

The specific issue there is the misalignment of column headers and data rows, which has been fixed. However, columns can still become unreasonably wide due to long variable names or variable labels. Labels are cut off, but variable names never are. Importantly, it is currently impossible to reduce the width to a narrower setting than the width of the text.

I propose that both variable names and variable labels have variable cutoff lengths. 

* Optimally, variable names and labels would be dynamically trimmed automatically, as column borders are dragged to reduce column width.
* Alternatively, maximum string lengths to be displayed could be passed to the `View()` function, both for variable names and labels (preferably in a separate parameter for each), to prevent extreme width. 
 
The tool-tip makes the resulting cut-off much less of an issue, even a 20-character start of a label serves the important function of highlighting that a label is present and providing a space to hover over to see the label in the tool-tip. The full variable name is currently not incorporated in the tool-tip (because it is never trimmed), but that could be included similarly to how the full variable label is currently tool-tipped.

<img width="1054" alt="wide_label_screenshot" src="https://github.com/rstudio/rstudio/assets/3247510/30021ef2-1b0e-4765-818b-2384933de16f">

<hr/>
ps. As an aside, it would be super nice to show the value labels as well in the data cells themselves, as is now done in the tibble+vctrs view in the console.

<br/>
<img width="355" alt="value_label_screenshot" src="https://github.com/rstudio/rstudio/assets/3247510/ef41830c-90d7-4162-8126-a35175cdff41">

This would alleviete the agonising choice between getting a good look at the variable labels (in the Viewer) and the value labels (in the console).

**Comment by ronblum** [comment]
@torfason Thank you for raising this! Wow, that's a long variable name. :D We'll review this as part of our ongoing development.
