### ISSUE TITLE
"Updates Available" dialog won't go away

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13379]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0+421
    OS Version      : MacOS 13.4
    R Version       : 4.3.0

### Steps to reproduce the problem

**The "updates to RStudio" checkbox referenced below can be found at**
<kbd>Tools -> Global Options -> General -> Basic -> Automatically Notify Me of updates to RStudio</kbd> 

<img width="306" alt="automatically" src="https://github.com/rstudio/rstudio/assets/31009952/f0fe4ac1-a03e-4044-a819-49801a82a625">

&nbsp;

1. Start RStudio Desktop 2023.06.0+421.
2. The "Update Available" dialog should pop up, showing the most recent available version. In this case, it's 2023.06.1+524.
    - If it doesn't show up, make sure that "updates to RStudio" is checked and restart RStudio.
3. Click on "Ignore Updates".
4. Close RStudio Desktop.
5. Start RStudio Desktop.
    - The "Update Available" dialog should pop up again.
6. Click on "Ignore Updates".
7. Go to the "updates to RStudio" option.
    - It should be checked.
8. Uncheck the "updates to RStudio" option.
9. Close RStudio Desktop.
10. Start RStudio Desktop.
    - The "Update Available" dialog should no longer pop up.

### Describe the problem in detail

The "Update Available" dialog pops up, and the "updates to RStudio" checkbox remains checked, even though "Ignore Updates" was previously clicked.

### Describe the behavior you expected

The "Update Available" dialog should stop popping up, and the "updates to RStudio" checkbox should be unchecked, after "Ignore Updates" is clicked. This should remain until the next version of RStudio is released. In this case, it would be when 2023.06.2+XXX is released. 

Note: This seems to be the reverse of #13347.

*Reported at https://twitter.com/wytham88/status/1679943556683952128*

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Getting into this state isn't guaranteed. A consistent way to get there:

1. Close RStudio Desktop if currently opened. RStudio must be first be closed to replicate this.
2. Edit the contents of `~/.local/share/rstudio/client-state/updates.persistent` to the following (create the file if it doesn't exist):
```
{
    "ignoredUpdates": {
        "updates": [
            "2023.06.0+524"
        ]
    }
}
```
3. Open RStudio Desktop 2023.03.x or earlier.

The files is created if "Ignore Updates" is clicked. Note the invalid version above, 2023.06.0+524, which should've been 2023.06.1.+524. This only happens under certain conditions, hence the manual edit.

Verified using a custom build, which contains the fix but is masquerading as an earlier version of RStudio Desktop, on MacOS 13.4.

**Comment by jonvanausdeln** [comment]
Closing as custom builds prove the fix is valid. 
Added this to the Desert Sunflower release checklist to check once there is a release.
