### ISSUE TITLE
Copy plot to clipboard has aliasing (ragg is not used?)

### ISSUE THREAD

**Issue by achetverikov** [rstudio/rstudio#13387]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : 2023.06.1 Build 524
    OS Version      : Windows 10, 21H2 (x86_64-w64-mingw32)
    R Version       : 4.3.0

### Steps to reproduce the problem

Make a figure, do export -> copy to clipboard on the figure panel. You can see that compared to the plot in the figure panel, the plot preview in the 'copy plot to clipboard' window has aliasing issues. The same issues stay when the plot is copied. 

![image](https://github.com/rstudio/rstudio/assets/1465806/c50c6557-6d64-4c29-a702-6f5a5fd1b0f3)

### Describe the problem in detail

This could be because ragg (AGG) is used for the figure preview in the figure panel but not for clipboard preview/copying (?). 

### Describe the behavior you expected

I expect the copied plot to look the same as in the figure preview window (or better). 

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
One thing you can try: if you execute

```
trace(ragg:::agg_png, quote(print(utils::ls.str())))
```

then you'll get some output in the Console every time RStudio renders a plot. For example, I see, for a plot in the Plots pane:

```
Tracing ragg:::agg_png(filename = "/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//RtmpPwx28C/5848895f6c594e42a8e56656f765cef4.png",  .... on entry 
background :  chr "white"
bg : <missing>
bitsize :  num 8
filename :  chr "/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T//RtmpPwx28C/5848895f6c594e42a8e56656f765cef4.png"
height :  int 1154
pointsize :  num 12
res :  int 192
scaling :  num 1
units :  chr "px"
width :  int 1308
```

But in the export plot dialog, I see:

```
Tracing ragg:::agg_png(filename = "/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/RtmpPwx28C/plota0a070d46086.png",  .... on entry 
background :  chr "white"
bg : <missing>
bitsize :  num 8
filename :  chr "/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/RtmpPwx28C/plota0a070d46086.png"
height :  int 577
pointsize :  num 12
res :  int 96
scaling :  num 1
units :  chr "px"
width :  int 654
```

The main thing that I see that differs is `res`. Are you by any chance using a high (or higher)-DPI display?

**Comment by achetverikov** [comment]
Interesting. When I make a plot:

```
> ggplot(data.frame(x = rnorm(50)), aes(x = x))+geom_density()
Tracing ragg:::agg_png(filename = "C:/Users/ANCHE7~1/AppData/Local/Temp/RtmpqKgqK2/c2cf128536fa4a89b40c0f110158fa5b.png",  .... on entry 
background :  chr "white"
bg : <missing>
bitsize :  num 8
filename :  chr "C:/Users/ANCHE7~1/AppData/Local/Temp/RtmpqKgqK2/c2cf128536fa4a89b40c0f110158fa5b.png"
height :  int 809
pointsize :  num 12
res :  int 132
scaling :  num 1
units :  chr "px"
width :  int 633

```

when I try to export:

```
Tracing ragg:::agg_png(filename = "C:/Users/ANCHE7~1/AppData/Local/Temp/RtmpqKgqK2/plot5c20462910da.png",  .... on entry 
background :  chr "white"
bg : <missing>
bitsize :  num 8
filename :  chr "C:/Users/ANCHE7~1/AppData/Local/Temp/RtmpqKgqK2/plot5c20462910da.png"
height :  int 589
pointsize :  num 12
res :  int 96
scaling :  num 1
units :  chr "px"
width :  int 461
Tracing ragg:::agg_png(filename = "C:/Users/ANCHE7~1/AppData/Local/Temp/RtmpqKgqK2/plot5c202df7439.png",  .... on entry 
background :  chr "white"
bg : <missing>
bitsize :  num 8
filename :  chr "C:/Users/ANCHE7~1/AppData/Local/Temp/RtmpqKgqK2/plot5c202df7439.png"
height :  int 589
pointsize :  num 12
res :  int 96
scaling :  num 1
units :  chr "px"
width :  int 461
```

So indeed the resolution seems the only thing different. Would be good to keep it the same (and ideally allow the user to set the desired one both for the figure panel and for the clipboard).

I'm using 1920x1080 display, also the scaling is set to 125% (default) in Windows settings, not sure if it matters.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+212 on MacOS 14.1, as compared to the difference in versions 2023.09.0+463.
