### ISSUE TITLE
Copilot recommends R chunks when asked for R Markdown text

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13396]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0-daily+236
    OS Version      : MacOS 13.4
    R Version       : 4.3.0

### Steps to reproduce the problem

Let's try to get some R Markdown text about bobolinks.

1. Create an empty R Markdown document.
2. Enter a YAML block, e.g. 
```
---
title: "Untitled"
output: html_document
date: "2023-07-19"
---
```
3. Enter the text `# Write some text about bobolinks`
   - Copilot immediately starts an R chunk.
4. Go through and accept the recommendations.
    - Copilot recommends several libraries to load.
    - The same few libraries are recommended over and over.
5. Close the chunk with ` ``` `
6. Write the text `Write some R Markdown text` (no leading pound sign) and wait a moment.
    - Copilot recommends the completion ` about bobolinks`
7. Hit <kbd>Enter/Return</kbd>
    - Copilot recommends an R chunk, followed by the same libraries as above.
8. Close the chunk with ` ``` `
9. Enter the text `Bobolinks are`
    - Copilot recommends the text ` cool`
10. Accept the recommendation.
    - Next, Copilot starts recommending an R chunk.
    - Within the R chunk, it starts recommending the same few libraries as above, over and over again, though this time an extra <kbd>Enter/Return</kbd> is needed to get them.

````
---
title: "Untitled"
output: html_document
date: "2023-07-19"
---

# Write some text about bobolinks

```{r}
library(leaflet)
library(leaflet.extras)
library(leaflet.providers)
library(leaflet.minicharts)
library(leaflet.opacity)
library(leaflet.esri)
library(leaflet.extras2)
library(leaflet.minicharts)
library(leaflet.opacity)
library(leaflet.extras2)
library(leaflet.extras)
library(leaflet.providers)
library(leaflet.extras2)
library(leaflet.extras)
```

Write some R Markdown text about bobolinks

```{r}
library(leaflet)
```

Bobolinks are cool

```{r}
library(leaflet)

library(leaflet.extras)

library(leaflet.providers)
```
````
### Describe the problem in detail

1. When asked for recommendations for R Markdown text, Copilot keeps recommending R chunks.
2. Within the R chunks, it keeps recommending several libraries to load, the same libraries over and over.

### Describe the behavior you expected

1. Copilot should recommend R Markdown text when asked for it.
2. Copilot should recommend each library only once.
3. If recommending a chunk, Copilot should eventually stop recommending some R code, not just loading the libraries (that it shouldn't have recommended in the first place).

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The challenge here is that (at least, last I checked) Copilot has no knowledge of R Markdown, so currently we're just sending R Markdown documents and pretending they're R.
