### ISSUE TITLE
[windows] regularly getting ERROR: cannot remove earlier installation, is it in use?

### ISSUE THREAD

**Issue by cdriveraus** [rstudio/rstudio#13399]
On Windows, for some years now, rstudio regularly reports problems with building and installing packages that involve .dll files, "ERROR: cannot remove earlier installation, is it in use?" (see below for full log). Sometimes this is resolved by waiting a bit, sometimes closing and restarting rstudio helps, but sometimes things are very stuck and I have to manually delete the mentioned package folder. There is no obvious pattern to it. Couldn't Rstudio make a backup of the package folder (in case of build problems), delete the folder, then initiate the build process?

```
==> Rcmd.exe INSTALL --with-keep.source --no-multiarch ctsem

* installing to library 'C:/Users/Driver/AppData/Local/R/win-library/4.3'
* installing *source* package 'ctsem' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/Driver/AppData/Local/R/win-library/4.3/ctsem'
* restoring previous 'C:/Users/Driver/AppData/Local/R/win-library/4.3/ctsem'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\Driver\AppData\Local\R\win-library\4.3\00LOCK-ctsem\ctsem\libs\x64\ctsem.dll to C:\Users\Driver\AppData\Local\R\win-library\4.3\ctsem\libs\x64\ctsem.dll: Permission denied

Exited with status 1.
```

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@cdriveraus Thank you for raising this! Are you able to run
`Rcmd.exe INSTALL --with-keep.source --no-multiarch ctsem`
from the command line, outside of RStudio? If so, what happens?

**Comment by stla** [comment]
You can unload the DLL with `dll.unload`. Also try `pkgload::unload`. And you can restart the R session too. Often, I close the session and I run `devtools::install` from a terminal.

**Comment by cdriveraus** [comment]
@ronblum yes that works fine in cases where it wouldn't via Rstudio, even with Rstudio and the project still open. Really seems like something that Rstudio is doing during the build process. 

@stla Sure, it's a bit of a pain for development though :)

**Comment by stla** [comment]
@cdriveraus Personally I use a `.Rprofile` file like this (here `boodist` is the package name):

```r
dllunload <- function(){
  dyn.unload(
    system.file("libs", "x64", "boodist.dll", package = "boodist")
  )
}

myinstall <- function() {
  try(pkgload::unload("boodist"))
  try(dllunload())
  if(rstudioapi::isAvailable()) {
    rstudioapi::restartSession(
      "devtools::install(quick = TRUE, keep_source = TRUE)"
    )
  } else {
    devtools::install(quick = TRUE, keep_source = TRUE)
  }
}

mydocument <- function() {
  if(rstudioapi::isAvailable()) {
    rstudioapi::restartSession(
      "roxygen2::roxygenise(load_code = roxygen2::load_installed)"
    )
  } else {
    roxygen2::roxygenise(load_code = roxygen2::load_installed)
  }
}
``` 

Then I run `myinstall()` and `mydocument()`.

**Comment by JiscaH** [comment]
Re-opening this thread, as I've been having the same issue as @cdriveraus - simply clicking 'install' used to always work, but at some Rstudio version (some years ago) it has become a recurring frustration. I think there used to be a menu option 'restart & install' or something along those lines, when that option disappeared the issue began.

**Comment by cdriveraus** [comment]
lately, restarting twice in a row seems to work for me...

**Comment by JiscaH** [comment]
For me restart followed by 'clean & install' often works, but yesterday I've needed to delete the installation folder in R/library many times. Sometimes that works with Rstudio open, sometimes I have to close Rstudio first because it complains about files being in use. 

I also tried your suggestion of simply waiting a bit - does seem to work, but I don't have the time or the patience to make that the default solution.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+244 on Windows 11 using example in QA notes. Note: Need to wait a few seconds between installation completion and then running installation again.

**Comment by olivroy** [comment]
I am not sure if this worked properly. 

I got an error while trying `devtools::load_all()` on rlang on Windows (2024.07.0build 294).

I don't know what is *supposed* to work, but a test of trying `devtools::load_all()` on the rlang repo should be done.

```
usethis::create_from_githhub("r-lib/rlang")
```

In the repo

```
devtools::load_all()
```

**Comment by cdriveraus** [comment]
Yes, I'm still regularly having this problem when working with ctsem ( https://github.com/cdriveraus/ctsem )

**Comment by cdriveraus** [comment]
I'm still getting this error regularly when using daily build 2024.08 to build [ctsem ](https://github.com/cdriveraus/ctsem)

**Comment by kevinushey** [comment]
@cdriveraus -- are you testing with the latest daily builds of RStudio? These are available at https://dailies.rstudio.com.

**Comment by cdriveraus** [comment]
@kevinushey  yes ;) 
> I'm still getting this error regularly when using **_daily build 2024.08_** to build [ctsem ](https://github.com/cdriveraus/ctsem)

**Comment by kevinushey** [comment]
@cdriveraus Sorry, somehow I missed you said exactly that. 🙈 We'll try to take another look.

**Comment by cdriveraus** [comment]
In case it helps, it seems like simply *looking at* (i.e., bringing into focus) the `AppData\Local\R\win-library\4.4` folder is sufficient to somehow nudge the system into unloading or whatever it has to do.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+298 on Windows 11 using the `rlang` example in the #15235 QA notes (I couldn't find a better way).
