### ISSUE TITLE
New project type: manuscripts

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#13391]
It would be good to add a new project type, Quarto Manuscript, by the time Quarto 1.4 is bundled with the IDE.

![image](https://github.com/rstudio/rstudio/assets/5965649/e23b7e5d-8c62-4e84-9949-04ba3101551c)

**Comment by petetronic** [comment]
Waiting on https://github.com/rstudio/rsconnect/issues/948 to be included in an rsconnect release, then we'll need RStudio to take that version.

**Comment by petetronic** [comment]
The updated rsconnect is now available on CRAN

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+381](https://dailies.rstudio.com/version/2023.09.0-daily+381)

Note, requires quarto 1.4, which is not yet released and `rsconnect v1.02 (see #13555 )
