### ISSUE TITLE
Error message doesn't show the details

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13398]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0-daily+236
    OS Version      : MacOS 13.4
    R Version       : 4.3.0

### Steps to reproduce the problem

When Copilot gets into the error state "Document for URI could not be found," the error message gets cut off and there's no way to get the details.
<img width="705" alt="error" src="https://github.com/rstudio/rstudio/assets/31009952/f2877112-f0f4-4d07-a64b-4ab9ced6485d">

### Describe the problem in detail

The problem details are missing.

### Describe the behavior you expected

The problem details should be viewable, such as by hovering over the error message.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
No, this is as far as it gets:
> <div class="gwt-Label">Copilot: Document for URI could not be found: rstudio-document://041e4a3c, URIs of the known document are: </div>

**Comment by DavidBlairs** [comment]
> No, this is as far as it gets:
> 
> > Copilot: Document for URI could not be found: rstudio-document://041e4a3c, URIs of the known document are:

![image](https://github.com/rstudio/rstudio/assets/54111529/3bd5572a-5f0e-4724-8007-b6f956406af3)
For further clarification (I'm getting it to)
