### ISSUE TITLE
Add `Insert <details>` shortcut

### ISSUE THREAD

**Issue by matiasandina** [rstudio/rstudio#13416]
Currently, it's possible to add formatted text with shortcuts or via catch-all commands in the visual editor. It works great for code chunks with `ALT+I` or typing `/code` in the visual editor. 

It would be great to have a shortcut that adds a `<details>` block to the text. This could potentially be found using `/details`

<details>
  <summary>Click to Toggle</summary>
  <p>PLACEHOLDER</p>
</details>

Is it possible that there's a way to customize this behavior with the existing functionality or would this need to be implemented in a new release ?

**Comment by ronblum** [comment]
@matiasandina Thank you for the suggestion/question! I'll mark it for review as part of the continuing development of the visual editor.

**Comment by olivroy** [comment]
I think this is a good idea.
