### ISSUE TITLE
`dplyr` join autocompletions missing argument suggestions

### ISSUE THREAD

**Issue by sharon-wang** [rstudio/rstudio#13415]
### System details

    RStudio Edition : Desktop, Server
    RStudio Version : 2023.06, 2023.09.0-daily+244
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

1. Type in `dplyr::left_join(x = iris, y = iris,)` (commas and closing bracket `)` are important!)
2. Press `tab` to trigger completion popup
3. Completion no longer shows remaining parameters, even after inserting one of the suggested values

<img width="500" alt="image" src="https://github.com/rstudio/rstudio/assets/25834218/fac5e329-d260-4ccd-8a90-d2b38565918f">

### Describe the problem in detail

Originally reported in https://github.com/rstudio/rstudio/issues/13196. This issue likely shows up with any of the `dplyr` join functions, since we have custom handling (search for `dplyr` in https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionRCompletions.R).

I am not 100% sure, but it looks like we stop providing autocomplete suggestions once values for arguments without defaults have been specified and/or the autocompletion behaviour is a bit different if the closing bracket is included.

It's also possible this isn't isolated to just `dplyr` functions -- needs investigation.

#### Repro (closing bracket seems to matter)
1. Type in `dplyr::left_join(x = iris, y = iris,` (commas and _missing_ closing bracket `)` are important!)
2. Press `tab` to trigger completion popup
3. Completion shows remaining parameters as expected

<img width="700" alt="image" src="https://github.com/rstudio/rstudio/assets/25834218/c4a4b320-4220-4ad2-a9ab-0dfb84262214">

This completion should have the same behaviour whether the closing bracket is included or not.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
~- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).~
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Vivek-Prakash-US** [comment]
I've also noticed missing autocompletions in dplyr functions if the data argument isn't piped in. For example, autocpletions work for 

mtcars %>% mutate(cyl2 = cyl^2)
but not 
mutate(mtcars, cyl = cyl^2)

**Comment by Vivek-Prakash-US** [comment]
@ronblum Thank you. I have submitted the issue here:
https://github.com/rstudio/rstudio/issues/13437

**Comment by ronblum** [comment]
Triage: Consider for Desert Sunflower.

**Comment by ronblum** [comment]
Verified that the same is displayed both with an without the closing parens:

<img width="500" alt="parens" src="https://github.com/rstudio/rstudio/assets/31009952/a24571d7-2969-44a4-9d51-e61f8318476f">
<img width="496" alt="no_parens" src="https://github.com/rstudio/rstudio/assets/31009952/1eb6ca2e-869d-4e66-932a-c51dd24e47a1">

However, the contents of `iris`, as well as `x` and `y`, aren't provided. Is this expected?

**Comment by kevinushey** [comment]
I think the syntax for dplyr joins must have changed since that autocompletion code was first implemented. Reading from https://r4ds.had.co.nz/relational-data.html?q=left_join#mutating-joins, it looks like joins use a syntax like:

```
x %>% 
  inner_join(y, by = "key")
```

In other words, column variables are only relevant as part of the "by" argument, and appear to be expected as strings.

Alternatively, there's the `join_by()` function, which in theory we could try to handle in a special way.

I think the shorter answer here is: yes, it's expected, but we could potentially (as a new feature) expand how we handle column names in joins to match the newer dplyr syntax.

**Comment by olivroy** [comment]
ALso, having dplyr loaded vs not loaded makes a difference. With dplyr loaded, RStudio knows to autocomplete for which type of data.

the autocomplete becomes `left_join.data.frame()`

**Comment by ronblum** [comment]
I created the barebones #13569 regarding the newer syntax.
