### ISSUE TITLE
No feedback given when trying to enable Copilot without the actual subscription

### ISSUE THREAD

**Issue by netique** [rstudio/rstudio#13418]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.9.0.246
    OS Version      : macOS Ventura 13.4.1
    R Version       : R version 4.3.1 (2023-06-16)

### Steps to reproduce the problem

1. Prepare a GitHub account without Copilot subscription.
2. Try authorizing Copilot in RStudio – tick "Enable GitHub Copilot" in Global options.
3. Navigate to the link provided in the pop-up window, and paste the code (on GitHub says that everything went OK).
4. In RStudio, no error message is given and the authentication process never terminates (well, maybe there is a looong timeout).

### Describe the problem in detail

For accounts without Copilot, the authentication process gets stuck without any information conveyed to the user. However, if you close the window and open it again, there is raw json printed saying 
<img width="582" alt="Snímek obrazovky 2023-07-26 v 10 58 34" src="https://github.com/rstudio/rstudio/assets/34926852/300bb7cb-0c65-4ce6-92b4-468d0af4cd9a">

### Describe the behavior you expected

To get some error message indicating that something went wrong.

**Comment by ronblum** [comment]
@netique Thank you for checking out our Copilot integration and reporting this issue! I'll mark it for review.

Triage: Recommending Copilot authentication for review.

**Comment by sharon-wang** [comment]
This sounds like a different repro case of https://github.com/rstudio/rstudio/issues/13267

**Comment by ronblum** [comment]
@sharon-wang OK! I copied this info over to #13267 and I'm closing this one as a duplicate.
