### ISSUE TITLE
RStudio won't launch (except via .Rproj) 

### ISSUE THREAD

**Issue by AlexanderPico** [rstudio/rstudio#13417]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1+524
    OS Version      : MacOS Ventura 13.3.1(a), M1 Max
    R Version       : 4.3.1

Fresh installations of R and RStudio

### Steps to reproduce the problem

Scenario 1:
 * Click on RStudio launch icon --> get gray screen and loading gif, then option to reload or terminate R.
 * Reload or no action leads to `RStudio Initialization Error: (TypeError) : Cannot read properties of null (reading 'error')` and I have to force-quit.
 * Terminate R, leads to troubleshooting screen with error report (see below).
 
Scenario 2:
 * However, launching RStudio from a preexisting .Rproj file works just fine and I can work with R in RStudio. 
 * I can switch to other projects.
 * But if I close a project, then I get the same gray screen as above and have to force-quit.
 
### Describe the problem in detail

from rsession log:

> 2023-07-25T16:46:29.371573Z [rsession-alexpico] ERROR CLIENT EXCEPTION (rsession-alexpico): (TypeError) : Cannot read properties of undefined (reading 'source_documents');|||org/rstudio/studio/client/workbench/model/SessionInfo.java#184::getSourceDocuments|||rstudio-0.js#-1::new cBt|||org/rstudio/studio/client/workbench/views/source/org_rstudio_studio_client_RStudioGinjector_RStudioGinjectorGinjector_fragment.java#208::get_Key$type$org$rstudio$studio$client$workbench$views$source$SourceWindowManager$_annotation$$none$$|||org/rstudio/studio/client/workbench/views/source/org_rstudio_studio_client_RStudioGinjector_RStudioGinjectorGinjector_fragment.java#157::get_Key$type$org$rstudio$studio$client$workbench$views$source$SourceColumnManager$_annotation$$none$$|||org/rstudio/studio/client/workbench/views/source/org_rstudio_studio_client_RStudioGinjector_RStudioGinjectorGinjector_fragment.java#175::get_Key$type$org$rstudio$studio$client$workbench$views$source$Source$_annotation$$none$$|||org/rstudio/studio/client/application/ApplicationQuit.java#122::prepareForQuit|||org/rstudio/studio/client/application/ApplicationQuit.java#547::onQuitSession|||org/rstudio/studio/client/application/ApplicationQuit_Binder__Impl.java#19::onCommand|||org/rstudio/core/client/command/CommandEvent.java#40::dispatch|||com/google/web/bindery/event/shared/SimpleEventBus.java#173::doFire|||com/google/gwt/event/shared/HandlerManager.java#117::fireEvent|||org/rstudio/core/client/command/AppCommand.java#155::doExecute|||org/rstudio/core/client/command/AppCommand.java#149::execute|||org/rstudio/studio/client/application/DesktopHooks.java#196::quitR|||rstudio-0.js#-1::quitR|||<anonymous>#-1::anonymous|||Client-ID: |||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
                                                                                                                                                       
### Describe the behavior you expected
 * Expected RStudio to launch and work :/

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@AlexanderPico Thank you for raising the issue! Do you remember by chance the combination of R and RStudio versions for which this last worked?

**Comment by AlexanderPico** [comment]
I may be wrong, but I don't recall updating either R or RStudio recently. I tend to leave RStudio open for many weeks at a time, so perhaps 3-4 weeks ago, it must have launched and worked (without specifying a project).

I see a lot of ".java" files mentioned in the log. Could it be something about my Java env that changed??

**Comment by ronblum** [comment]
RStudio 2023.06.1+524 was released only a few weeks ago, which is why I was wondering about previous versions.

**Comment by timtmok** [comment]
@AlexanderPico Can you provide a screenshot of what you are seeing when the error occurs?

**Comment by AlexanderPico** [comment]
I see the initial gray screen with a loading gif icon. Then I'm presented with two options briefly. If I choose "Terminate R," then I get a troubleshooting screen and the error reported in the OP. If I choose "Reload" or nothing at all, then I see this popup error:

![Screenshot 2023-07-25 at 10 43 16 AM](https://github.com/rstudio/rstudio/assets/1418193/ed091b4d-10ac-46e6-9c9a-acdaacfb7829)

**Comment by timtmok** [comment]
Could you try backing up and clearing your RStudio desktop state? https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

I haven't been able to reproduce this locally so it might be a bad state after first opening the IDE and it is stuck in this bad state.

**Comment by AlexanderPico** [comment]
Thanks for the help. 

Previously, I deleted .RData and .Rhistory, and then restinstalled RStudio and R.  Same result.  

Next I will try clearing the config content at ~/.config/rstudio/ and ~/.local/share/rstudio/...

Then I guess I look into Java-related stuff...  or I'll always work within a Project :)

**Comment by timtmok** [comment]
I don't think it's anything that you did. It should be handling the error and allowing you to continue. It seems to be a special case with what you have that is causing the error. Hopefully, we can figure out the steps to reproduce it and fix it!

**Comment by ronblum** [comment]
@AlexanderPico Have you tried clearing out the config/cache directories, and have you had any luck with it?

**Comment by AlexanderPico** [comment]
Sorry. Got a new laptop before fixing this issue. Not an issue on new installation.

**Comment by jayalakc** [comment]
I faced the same issue. Resetting RStudio Desktop's state worked for me, deleting the hidden folder as described here: https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
