### ISSUE TITLE
Rstudio error starting Ubuntu 22.04

### ISSUE THREAD

**Issue by benoitnabholz** [rstudio/rstudio#13421]
### RStudio Version

RStudio 2023.06.1+524 "Mountain Hydrangea " (547dcf86, 2023-07-07) for Ubuntu Jammy

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*/home/benoitnabholz/.local/share/rstudio/log/rsession-benoitnabholz.log*

```
2023-07-26T08:29:36.943515Z [rsession-benoitnabholz] WARNING The tcp http listener initialized without signature validation: --verify-signatures option missing; LOGGED FROM: void rstudio::session::{anonymous}::initTcpHttpConnectionListener(const string&, const string&, rstudio::session::Options&, const string&, const string&) src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:76
2023-07-26T08:29:36.944105Z [rsession-benoitnabholz] ERROR system error 2 (No such file or directory) [path: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::discoverR(rstudio::r::session::RLocations*) src/cpp/r/session/RDiscovery.cpp:62; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2474
2023-07-26T08:29:36.944105Z [rsession-benoitnabholz] ERROR system error 2 (No such file or directory) [path: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::discoverR(rstudio::r::session::RLocations*) src/cpp/r/session/RDiscovery.cpp:62; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2474

```

**Comment by benoitnabholz** [comment]
I didn't find any information regarding my problem. 

Thank-you for your help.
Benoit

**Comment by ronblum** [comment]
@benoitnabholz Thank you for raising this!

@sharon-wang Would you by chance have any leads, based on the logs provided?

**Comment by benoitnabholz** [comment]
Hi,

I couldn't find anything to fix my problem.

**Comment by sharon-wang** [comment]
This looks similar to the logs in https://github.com/rstudio/rstudio/issues/12963#issuecomment-1503776713. The resolution proposed there is to ensure that `desktop.ini` is readable, but I'm not certain that's the same issue here.

The error message `ERROR system error 2 (No such file or directory) [path: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::discoverR(rstudio::r::session::RLocations*) src/cpp/r/session/RDiscovery.cpp:62` seems to imply that `R_HOME` could not be found (empty path).

@benoitnabholz, a few questions for you:
1. What was the last version of RStudio you used, where you didn't experience this startup issue? (if any)
2. When running R directly in a terminal, does `R.home()` return a correct path to R, such as `/usr/lib/R`?
3. Are you opening RStudio via the terminal (if so, are you using `sudo` or passing any parameters?), or are you clicking on the app executable?

**Comment by benoitnabholz** [comment]
Dear @sharon-wang 

1. What was the last version of RStudio you used, where you didn't experience this startup issue? (if any)
**I guess the current version worked at some point (2023.06.1-524).**

2. When running R directly in a terminal, does R.home() return a correct path to R, such as /usr/lib/R?
**Yes**

3. Are you opening RStudio via the terminal (if so, are you using sudo or passing any parameters?), or are you clicking on the app executable?
**By clicking on an app but running from a terminal without "sudo" lead to the same error.**

**Comment by sharon-wang** [comment]
Noting that this may be related to https://github.com/rstudio/rstudio/issues/13184.

**Comment by benoitnabholz** [comment]
My problem persist and my R is installed in /usr/bin/ so it is not https://github.com/rstudio/rstudio/issues/13184 in my case.

**Comment by kevinushey** [comment]
How was R installed on your machine? It looks like RStudio tries to infer some of R's environment variables from the R wrapper shell script, so I wonder if your script has some unexpected contents.

That is, what is the output of:

```
cat /usr/bin/R
```

on your machine?

**Comment by kevinushey** [comment]
Do you see any errors in the system log when you try to start RStudio?

Can you share the output of:

```
cat /spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/r-4.3.0-t2dnho7xg7oaqwpvvvcsxdfzdfbomcwf/bin/R
```

**Comment by xuanblo** [comment]
(base) [guest@ip~]$ l /home/guest/miniconda3/envs/scRNA/bin/R
-rwxrwxr-x 1 guest guest 9.1K Apr 30 22:53 /home/guest/miniconda3/envs/scRNA/bin/R
(base) [guest@ip ~]$ cat /etc/rstudio/rserver.conf
\# Server Configuration File
www-port = 8787
rsession-which-r=/home/guest/miniconda3/envs/scRNA/bin/R
centos 7
(base) [guest@ip ~]$ l /home/guest/miniconda3/envs/scRNA/bin/R
-rwxrwxr-x 1 guest guest 9.1K Apr 30 22:53 /home/guest/miniconda3/envs/scRNA/bin/R
(base) [guest@ip ~]$ sudo rstudio-server verify-installation
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/var/log/rstudio/rstudio-server/rserver.log'.
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/tmp/ef48-12a5-542f-19de/.local/share/rstudio/log/rsession-rstudio-server.log'.
2024-05-06T16:15:43.197082Z [rsession-rstudio-server] ERROR system error 2 (No such file or directory) [path: /home/guest/miniconda3/envs/scRNA/lib/R]; OCCURRED AT rstudio::core::Error rstudio::r::session::discoverR(rstudio::r::session::RLocations*) src/cpp/r/session/RDiscovery.cpp:62; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2494

run on centos 7

i give '`rsession-which-r=/home/guest/miniconda3/envs/scRNA/bin/R`', but why '`rstudio-server verify-installation`' report '`path: /home/guest/miniconda3/envs/scRNA/lib/R`' can't find?
