### ISSUE TITLE
make indicator Cancel button a bit more prominent

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13439]
Verified in 2023.09.0-daily+290 on MacOS 13.5. However, the <kbd>Cancel</kbd> option is almost indistinguishable from the rest, so I overlooked it the first couple of times that I tried it—I kept trying the big grayed-out button below. Is there any way to distinguish it a little more, such as by putting a border around it so that it looks like a button?

_Originally posted by @ronblum in https://github.com/rstudio/rstudio/issues/13312#issuecomment-1660449817_

**Comment by ronblum** [comment]
Thanks @kevinushey! I guess I got a little lazy and didn't open a new issue for this. I'll go close the other one.

**Comment by kevinushey** [comment]
This issue should now be obviated: rather than include a Cancel button in the progress label, we allow the user to click the "regular" Cancel button in the dialog.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+268](https://dailies.rstudio.com/version/2023.12.0-daily+268)
Windows 11, MacOS 12.6

Cancel Button on Dialog works as expected now and is visible.
