### ISSUE TITLE
SQL files get R Copilot suggestions

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13432]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0+daily-285
    OS Version      : MacOS 13.5
    R Version       : 4.3.1

### Steps to reproduce the problem

1. Open a new SQL file.
2. Erase the `SELECT 1` row
3. Type a SQL comment, starting with `-- `, requesting a SQL query. For example,
```
-- Write a SQL query to find the number of unique users who have visited the site in the last 30 days.
```
4. Continue requesting and accepting Copilot suggestions.

### Describe the problem in detail

Eventually, Copilot will can start making non-SQL suggestions, such as R chunks, for example:

````
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())
-- Write a SQL query to find the number of unique users who have visited the site in the last 30 days.
SELECT COUNT(DISTINCT user_id) AS unique_users
FROM page_visits
WHERE visit_date >= DATE('now', '-30 days')
```

```sql
-- Language: sql
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())
-- Write a SQL query to find the number of unique users who have visited the site in the last 30 days.
SELECT COUNT(DISTINCT user_id) AS unique_users
FROM page_visits
WHERE visit_date >= DATE('now', '-30 days')
```

```sql
-- Language: sql
````

### Describe the behavior you expected

Copilot suggestions should be restricted to the type of file it is. For example, a SQL file should only get SQL examples. It might not be possible to distinguish between R and R Markdown, but is it possible to distinguish between R and SQL? Copilot might not be able to distinguish between R and R Markdown (#13396), but is it possible to restrict SQL to only suggest SQL code? Or nothing at all, unless we can access Copilot for SQL.

Note that I seem to get decent C++ code in a cpp file.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I think this is just an artefact of how Copilot is generating its completions; we're not doing any sort of post-processing to try and ask for these chunk-style headers. I don't think there's much we can do so I'm going to punt for now.

**Comment by ronblum** [comment]
I'm still seeing chunk code. In this case, it chose ` ```r` instead of ` ```sql`.

````
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

-- Write a SQL query to find the number of unique users who have visited the site in the last 30 days.

SELECT COUNT(DISTINCT user_id) AS unique_users
FROM page_visits
WHERE date > (SELECT DATE(MAX(date), '-30 days') FROM page_visits);
```

```r
-- Language: sql
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

-- Write a SQL query to find the number of unique users who have visited the site in the last 30 days.

SELECT COUNT(DISTINCT user_id) AS unique_users
FROM page_visits
WHERE date > (SELECT DATE(MAX(date), '-30 days') FROM page_visits);
```

```r
-- Language: sql
````

**Comment by ronblum** [comment]
Note: Checked with RStudio Desktop and Posit Workbench 2024.04.0-daily+531.pro9. I'll put this back in `test` though in case the fix won't get picked up until the next daily build.

**Comment by ronblum** [comment]
Still occurring in version 2024.04.0-daily+550, although the lines with the backticks ` ` ` show up one at a time, as in #13686.

**Comment by kevinushey** [comment]
I'm not able to reproduce locally -- can you share an example project where this is occurring? It most likely depends on the content of the project, as well as whether you have project indexing enabled.

**Comment by ronblum** [comment]
@kevinushey I always start with this on top
```
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

-- Write a SQL query to find the number of unique users who have visited the site in the last 30 days.
```

And then start accepting suggestions. This time I got:
```
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

-- Write a SQL query to find the number of unique users who have visited the site in the last 30 days.
SELECT COUNT(DISTINCT user_id) AS unique_users
FROM page_visits
WHERE date > (SELECT DATE(MAX(date), '-30 days') FROM page_visits);
```

```r
# Execute the query and store the result
unique_users <- dbGetQuery(conn, unique_users_query)

# Print the result
unique_users
```

**Comment by kevinushey** [comment]
Thanks; that's helpful! I'm able to reproduce if I explicitly include:

```
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())
```

in the header. I think Copilot is seeing that, and given the mixture of R + SQL code within the document, it's mistakenly assuming it must be an R Markdown / multimode document of some kind.

Maybe we should strip the preview comment from the text before sending it to Copilot, to avoid this confusion.

**Comment by kevinushey** [comment]
IMHO we should just treat this as won't-fix at this point -- these are being generated by Copilot and there's just not much we can do to influence what it's producing here.

**Comment by ronblum** [comment]
@kevinushey I was thinking the same thing--closing.
