### ISSUE TITLE
Tab autocompletion in dplyr often does not trigger if the dataframe is not piped into the function.

### ISSUE THREAD

**Issue by Vivek-Prakash-US** [rstudio/rstudio#13437]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.2 Build 556 Installer-less
    OS Version      : Windows 11 10.0.22631 Build 22631

    R Version       : 4.3.1 (2023-06-16 ucrt)

### Steps to reproduce the problem
library(tidyverse)

Pressing tab after 'S' results is the variable 'Species' properly displaying in the autocomplete popup.
`iris %>% filter(S`

Pressing tab after 'S' does not display any relevent variables from the tibble.
`filter(iris, S`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Vivek-Prakash-US Thanks for opening a new issue for this! I can confirm that autocompletion will bring up anything imaginable starting with `s` except for the `Sepal.` objects. This is the case going back to at least 2022.07.2+576. We'll review this as we continue to develop RStudio.

**Comment by olivroy** [comment]
I think this has always been the case. 

AFAIK, Autocomplete for column names has always only worked for piped data.
The recent addition is that RStudio autocompletes differently arguments depending on the object type.
