### ISSUE TITLE
Linux: copy-pasting a file into Rstudio returns nothing, should be the full file address

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#13438]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1 Build 524
    OS Version      : Xubuntu 23.04
    R Version       :  latest

### Steps to reproduce the problem
Goto file browser (Thunar), select file, copy (ctrlC or rightmouseclick), goto RStudio, paste: nothing.

### Describe the behavior you expected
Expected: pastes full file address. This works various locations e.g. mousepad (text editor)

### Describe the problem in detail
Would be nice to fix as it allows quick insertion of addresses to read files. Instead you need to copy the folder address from the address bar, paste that, then edit the filename, select all (to grab the extension), escape out, paste.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.

**Comment by SimonDedman** [comment]
There's a chance it's related to [this](https://github.com/rstudio/rstudio/issues/7033), but not sure.

**Comment by ronblum** [comment]
@SimonDedman I'm certain that this is a known issue that was raised previously, but I can't find it, so I'll leave this open. Did this work for you in previous releases?

**Comment by SimonDedman** [comment]
Hi Ron, I'm not sure, in all honesty. Maybe? But certainly not for a long while, IIRC, if ever. Cheers!

**Comment by SimonDedman** [comment]
I know this is low priority but would be cool if it could be looked at - hopefully it's just a simple fix?

I can copy a file from the file manager (Thunar) and paste into text-only boxes like Excel/LibreOffice cells and receive the full address inc filename & extension, so that info must be present, and is somehow being parsed incorrectly in RStudio?

**Comment by kevinushey** [comment]
This seems to work for me on Ubuntu 22.04 with the latest RStudio daily builds at https://dailies.rstudio.com. Is the problem here unique to the Thunar file manager?

**Comment by SimonDedman** [comment]
Hi Kevin; I'm not sure honestly. I've just tried the latest build, 402, and unfortunately I can confirm that it

DOES WORK WOOOOOOOOO

Ok awesome. Cheers Kev & team, as always, y'all rock, have a cracking rest of your week!

**Comment by ronblum** [comment]
@SimonDedman Glad that it works, and thank you for the kind words!

@kevinushey was this the fix #13923? If so, I found the other ticket, woo hoo! #4572

**Comment by kevinushey** [comment]
@ronblum yes indeed!
