### ISSUE TITLE
Version 3.4.1 Rstudio error

### ISSUE THREAD

**Issue by Nkuta** [rstudio/rstudio#13443]
### System details

    RStudio Edition : 
    RStudio Version :  Desktop 
    OS Version      : Windows 10 home edition 
    R Version       : 3.4.1 

### Steps to reproduce the problem
1. installed Rstudio
2. installed R
3. launched Rstudio
4. selected 3.4.1 from R installations (the only one installed)
5. produced the following error: "an error occurred while attempting to load the selected version of R. Please Select a different R installation. 
### Describe the problem in detail
"an error occurred while attempting to load the selected version of R. Please Select a different R installation." this error occurs upon launching my new installation of Rstudio 
### Describe the behavior you expected
I was unable to use the desktop application as error occurs upon launch

- [yes ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ yes] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [yes ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Nkuta Thank you for raising this! 3.4.1 is the version of R. What version of RStudio are you using? You can get it in the <kbd>Help -> About</kbd> window, or in the Console Pane with `RStudio.Version()$long_version`

**Comment by Nkuta** [comment]
Hello, I currently have the most recent version installed (the one
available on the official Rstudio homepage. Under product version in
properties I have : 2023.06.1+524
