### ISSUE TITLE
Backport #13447 to Mountain Hydrangea 2023.06.2

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#13448]
Backport #13447 to Mountain Hydrangea 2023.06.2

**Note: This issue is to record the need to backport the linked issue only. Please add comments or discussion relating to the original issue onto it directly.**

**Comment by jonvanausdeln** [comment]
Verified on [2023.06.2+557.pro1](https://dailies.rstudio.com/version/2023.06.2+557.pro1)
Windows 11, ubuntu22, MacOS 12

All automation tests passed.
