### ISSUE TITLE
Upgrade semver

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#13447]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1
    OS Version      : n/a
    R Version       : n/a

### Steps to reproduce the problem
`semver` is pulled in from Electron and we require a higher version that has a fix that we want.

### Describe the problem in detail
We are currently using `semver@7.3.8` and we want `7.5.2`.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Ran automation on [2023.09.0-daily+349](https://dailies.rstudio.com/version/2023.09.0-daily+349), and all passed.
