### ISSUE TITLE
Clear Project List - Deactivate or Ask

### ISSUE THREAD

**Issue by chrboku** [rstudio/rstudio#13442]
Hello, 

Thank you for the great RStudio software!

Problem
When selecting a project from the list of recent projects in the drop-down list on the right, top side of Rstudio, the 'Clear Project List' is an option that I click unintentionally. Unfortunately, it clears the project list without asking whether I want that. 
![image](https://github.com/rstudio/rstudio/assets/18591761/23e6f733-34c1-4854-b76c-c13d7c8a20a4)

Solution
Please implement an option to deactivate this action or make it ask whether the user really intends to delete the list of recent projects. 

Thank you

Best regards, christoph

**Comment by ronblum** [comment]
@chrboku Thank you for the good suggestion! I'll mark this for review as part of our ongoing development of RStudio.
