### ISSUE TITLE
CoPilot: Toggle between standard intellisense and the new copilot recommendations

### ISSUE THREAD

**Issue by slodge** [rstudio/rstudio#13446]
I'm loving the new CoPilot experience.

However, I'm also missing the old code completion/intellisense experience.

In particular I am missing completions of e.g. function/member lists when I type `rlang::`

e.g. with "legacy" RStudio I frequently use:
![image](https://github.com/rstudio/rstudio/assets/533662/8fbf3421-ad65-4d91-a41c-40f1382324f8)

while with CoPilot I only seem to get:
![image](https://github.com/rstudio/rstudio/assets/533662/da253d24-bb1d-4ac4-9ca9-348ec20f3f71)

Is there any way to allow users to benefit from both sets of recommendations? Or at least to quickly toggle between the two systems?

**Comment by ronblum** [comment]
@slodge Thank you for raising this!

@kevinushey Is there any way around this?

There's a cumbersome workaround: Hit <kbd>Tab</kbd> to accept the Copilot suggestion, delete the suggested code, then hit <kbd>Tab</kbd> again. Note that <kbd>Ctrl-Z</kbd> won't help.

**Comment by slodge** [comment]
Ctrl+SPACE - I found it - maybe just needs publicising?

**Comment by kevinushey** [comment]
The intention is indeed to allow Ctrl + Space to retrieve "regular" completions. There might be other tweaks worth making too; we're still figuring out what the best way to allow these two systems to co-mingle is.

**Comment by jthomasmock** [comment]
I've moved towards a longer delay for Copilot suggestions (> 1,000 ms) and being more aggressive to initiate auto-completion manually via `Tab`.

**Comment by kevinushey** [comment]
Here's a question -- suppose you're in this state, where you have both ghost text and a completion list visible.

<img width="332" alt="Screenshot 2023-08-16 at 2 29 55 PM" src="https://github.com/rstudio/rstudio/assets/1976582/ca4258eb-2f27-487e-9f87-c583b312cce6">

What would you expect:

- The Tab key to do?
- The Enter key to do?

**Comment by jthomasmock** [comment]
It looks like there's some existing write-ups about dev UX on this:

- https://github.com/orgs/community/discussions/9430
- https://visualstudiomagazine.com/articles/2023/02/17/copilot-intellisense.aspx

One takeaway I saw was "I turned off inline editor suggestions and use <kbd>Alt-\</kbd> to trigger Copilot"

I don't think we have a shortcut to force a prompt? Or ability to turn it off for automatic completion, but then manually force it to prompt - that would be excellent.

It looks like the vscode team made progress recently although there was a lot of friction previously: https://visualstudiomagazine.com/articles/2023/06/22/copilot-intellisense.aspx which is linking to: https://devblogs.microsoft.com/visualstudio/github-copilot-visual-studio-intellisense/

> Press <kbd>TAB</kbd> to accept the IntelliSense member, then <kbd>TAB</kbd> again to accept the Copilot prediction.

> Press <kbd>Left CTRL</kbd> to hide the IntelliSense list or accept the prediction to understand the code with syntax highlighting/IntelliSense

**Comment by kevinushey** [comment]
For testing, I ended up making the following changes in https://github.com/rstudio/rstudio/pull/13521:

- If Copilot is enabled, we now show the completion list on top by default, to avoid obscuring ghost text.

<img width="667" alt="Screenshot 2023-08-30 at 10 49 37 AM" src="https://github.com/rstudio/rstudio/assets/1976582/95828bd7-648d-4111-9093-5ee9b41d1e75">

- Pressing Tab will prefer inserting a Copilot code suggestion if available; pressing Enter will always insert from the completion list.

@jthomasmock, do you think we should consider making it easier to dismiss the completion list? For example, if the user pressing Ctrl while the completion list is visible, we could dismiss it.

**Comment by slodge** [comment]
Are we able at all to put a small TAB and ENTER on those displays?

When I've used Jetbrains tools like Resharper they always point out the key
shortcuts (eg alt+enter) in every hint and I find it really helps usability.

**Comment by jthomasmock** [comment]
@kevinushey 

> do you think we should consider making it easier to dismiss the completion list? For example, if the user pressing Ctrl while the completion list is visible, we could dismiss it.

To clarify, since we're using <kbd>Ctrl+Space</kbd> as an option to go to the normal auto-complete, would <kbd>Ctrl</kbd> closing the completion list be confusing?

**Comment by kevinushey** [comment]
> Are we able at all to put a small TAB and ENTER on those displays?

Possibly... but where would we want to display those shortcuts? Would we add this as a blurb below the Help display? Below the completion list? Something else?

> To clarify, since we're using Ctrl+Space as an option to go to the normal auto-complete, would Ctrl closing the completion list be confusing?

Hmm... Right now, pressing Ctrl + Space multiple times has the effect of toggling the completion list on and off, so I think it does sort of make sense to allow Ctrl on its own to dismiss the completion list.

**Comment by jthomasmock** [comment]
> Hmm... Right now, pressing Ctrl + Space multiple times has the effect of toggling the completion list on and off, so I think it does sort of make sense to allow Ctrl on its own to dismiss the completion list.

Sounds good to me then!

**Comment by ronblum** [comment]
I'm running into this issue, in which autocomplete doesn't show up in the Source Editor at all; see #13446, so I can't verify this. (Maybe I should have just reopened this issue, not sure.)

**Comment by ronblum** [comment]
Using RStudio Desktop 2023.09.0-daily+407 on MacOS 14:
- Both completion list and ghost text will show up (one minimal example that I've been using to type `libr`).
- The completion list hovers above the ghost text, instead of over it.
- <kbd>Tab</kbd> accepts the ghost text.
- <kbd>Return</kbd> accepts the completion.
- <kbd>Ctrl-Space</kbd> toggles the presence of the completion list.

However
- <kbd>Ctrl</kbd> doesn't dismiss the completion list. Should it?

**Comment by kevinushey** [comment]
> Ctrl doesn't dismiss the completion list. Should it?

Let's add that as a separate issue and close this one as fixed?

**Comment by ronblum** [comment]
Done! #13615
