### ISSUE TITLE
CoPilot and Corporate Networks

### ISSUE THREAD

**Issue by slodge** [rstudio/rstudio#13455]
### System details

    RStudio Edition : Desktop
    RStudio Version :  August 1st - https://dailies.rstudio.com/rstudio/desert-sunflower/electron/windows/ - 2023.09.0 Build 290
    OS Version      :  Windows 10
    R Version       : R4.2

### Steps to reproduce the problem

Use today's daily build of RStudio

Configure CoPilot

Connect to a corporate network that does man-in-the-middle ssl sniffing

CoPilot doesn't work - the console shows messages like

``` 
[ERROR] [default] [2023-08-03T13:59:41.428Z] Request Error: self signed certificate in certificate chain
[ERROR] [ghostText] [2023-08-03T13:59:41.429Z] Error on ghost text request FetchError: self signed certificate in certificate chain

[ERROR] [default] [2023-08-03T13:59:42.584Z] Request Error: self signed certificate in certificate chain
[ERROR] [ghostText] [2023-08-03T13:59:42.584Z] Error on ghost text request FetchError: self signed certificate in certificate chain

[ERROR] [default] [2023-08-03T13:59:43.729Z] Request Error: self signed certificate in certificate chain
[ERROR] [ghostText] [2023-08-03T13:59:43.729Z] Error on ghost text request FetchError: self signed certificate in certificate chain
```

### Describe the problem in detail

All I have is above

### Describe the behavior you expected

Instructions needed to resolve this...

Instructions for other platforms are in the answers to https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot - for VSCode on Windows, the win-ca extension seems to be the answer...

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by atocharnaud** [comment]
Same issue here at the OECD.

**Comment by kevinushey** [comment]
In the most recent daily builds, it's now possible to set a proxy URL to be used by the Copilot agent for outbound network requests. This can be set by adding the following to your `/etc/rstudio/rsession.conf`:

```
copilot-proxy-url=<host>:<port>
```

In addition, you can disable certificate validation if necessary with:

```
copilot-proxy-strict-ssl=0
```

These builds are available at https://dailies.rstudio.com.

**Comment by markderry** [comment]
@kevinushey I have this same problem, for the solution you propose how do we implement this on a windows desktop machine? I don't believe that there is a `rsession.conf` file. I thought we might be able to put it into the `rstudio-prefs.json `or `config.json`, alternatively could it be set in the .Rprofile?

**Comment by kevinushey** [comment]
@markderry we're still thinking about potential solutions. Do you think it would suffice if we allowed an environment variable like `RSTUDIO_COPILOT_PROXY_URL` or something similar?

**Comment by markderry** [comment]
Yes this would be totally appropriate, alternatively a check box in the global options >> Copilot >> Ignore SSL would also suffice.

**Comment by slodge** [comment]
I think that disabling SSL could be a workaround for a short while 👍 

However, this definitely doesn't feel like a long term solution or one that should be recommended or made too easy to enable.

**Comment by markderry** [comment]
Fair point, if we could supply a certificate that could help as well. 

In vscode they have a plugin win-ca which allows vscode to use the system certificate store and thus the corporate cert is then trusted and the ssl decrypt doesn't cause a failure.

**Comment by jonvanausdeln** [comment]
@slodge , would be able to verify the setting works for you? This is available in our latest daily builds https://dailies.rstudio.com/.

**Comment by slodge** [comment]
I'm afraid I'm away from the office and can't verify until Thursday next
week.

**Comment by jonvanausdeln** [comment]
Related issue #13746 was confirmed externally which utilizes the same feature, so I'm closing this one as well.

If there is a problem, please re-open this issue.
