### ISSUE TITLE
RStudio Viewer to smartly recognize Quarto output directory

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#13458]
When Quarto documents are rendered to a user-specific directory using `_quarto.yml` file, such as
```
project:
  output-dir: output-folder
```

RStudio Viewer does not automatically recognize the output directory and fails to preview. 

<img width="635" alt="image" src="https://github.com/rstudio/rstudio/assets/46496637/6bab4c27-9ec8-46ea-b895-f2939bf1c6d0">

I'm hoping RStudio could preview the output in Viewer wherever the files are stored as it finishes rendering.

My RStudio version is 2022.12.0 Build 353 (A recent bug with the screenshot clipboard copy-pasting feature prevents me from further updates...)

**Comment by timtmok** [comment]
I'll take a look and see if there's a quick fix for this.

**Comment by kevinushey** [comment]
This appears to work for me in the latest daily builds -- these are available from https://dailies.rstudio.com. Can you please test and report back?

**Comment by ronblum** [comment]
Original issue reproduced in 
- RStudio Desktop 2023.09.1+494: Quarto 1.3.433
- RStudio Desktop 2023.12.0+369: Quarto 1.3.450
- RStudio Server 2023.12.1+395: Quarto 1.3.450

Verified correct:
- RStudio Desktop 2024.04.0-daily+270: Quarto 1.3.450
- RStudio Server 2024.04.0-daily+270: Quarto1.3.450

Checked both with viewing in the Viewer Pane and an external window.

**Comment by matthewgson** [comment]
Confirmed that it works on RStudio Desktop 2024.04.0 Build 356. Thank you!
