### ISSUE TITLE
Core Test Failing on both X86 and PPC64le architecture.

### ISSUE THREAD

**Issue by ujwal-akare** [rstudio/rstudio#13456]
### System details

    RStudio Edition : Server
    RStudio Version : main branch
    OS Version      : RHEL8
    Arch            : x86_64   
    R Version       : R4.3.1

### Steps to reproduce the problem
[buildsteps_x86.txt](https://github.com/rstudio/rstudio/files/12259115/buildsteps_x86.txt)

### Describe the problem in detail:
Hi Team,
I am working on validating rstudio for main version on Power(ppc64le) architecture.
As I firstly tried it on ppc64le arch. Then also checked it on x86_64 architecture but the same test case is failing.
on both architectures.
core test case is failing with the following error:
```
/home/test/rstudio/src/cpp/core/system/PosixSystemTests.cpp:351: FAILED:
  CHECK_FALSE( (error) )
with expansion:
  !UnknownError error 1 (Failed to run lsof - exited with code 1); OCCURRED AT
  rstudio::core::Error rstudio::core::system::currentWorkingDirViaLsof(PidType,
  rstudio::core::FilePath*) src/cpp/core/system/PosixSystem.cpp:1322

/home/test/rstudio/src/cpp/core/system/PosixSystemTests.cpp:352: FAILED:
  CHECK_FALSE( (cwd.isEmpty()) )
with expansion:
  !true

/home/test/rstudio/src/cpp/core/system/PosixSystemTests.cpp:353: FAILED:
  CHECK( (cwd.exists()) )
with expansion:
  false

/home/test/rstudio/src/cpp/core/system/PosixSystemTests.cpp:354: FAILED:
  CHECK( (startingDir == cwd) )
with expansion:
  false
```
[rstudio_x86_core_failures.txt](https://github.com/rstudio/rstudio/files/12259121/rstudio_x86_core_failures.txt)
[rstudio_ppc64le_core_failure.txt](https://github.com/rstudio/rstudio/files/12259308/rstudio_ppc64le_core_failure.txt)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
> Failed to run lsof - exited with code 1

These tests depend on the `lsof` utility being installed. Are they not available on your systems?

**Comment by ujwal-akare** [comment]
Hi @kevinushey, Thanks for the reply.
 `lsof` utility is installed by using following command:
 ` yum install -y initscripts lsof`

**Comment by kevinushey** [comment]
Is `lsof` on the `PATH`? What does

```
lsof -a -p $$ -d cwd -Fn
```

return for you in a Terminal?

**Comment by ujwal-akare** [comment]
got the following output for `lsof -a -p $$ -d cwd -Fn`

`p46036
fcwd
n/home/test/rstudio/build/src/cpp
`
