### ISSUE TITLE
Authentication doesn't open browser unless Firefox is already open

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13468]
### System details

    RStudio Edition : Dekstop
    RStudio Version : 2023.09.0-daily+301
    OS Version      : RHEL 9.2
    R Version       : 4.3.1

### Steps to reproduce the problem

Assuming that the web browser is Firefox.
1. Close Firefox.
2. In RStudio, enable Copilot.
3. Sign in to Copilot, to go through the authentication process.
 
### Describe the problem in detail

Authentication begins in RStudio. However, the browser never opens, even though a Firefox process is running. The "Authenticating" pop-up remains and continues to wait.

```
$ ps -ef |grep firefox
vmware      5114    2227  7 06:03 pts/0    00:00:00 /usr/lib64/firefox/firefox https://github.com/login/device
```

### Describe the behavior you expected

Firefox should open and display the Github authorization flow.

This works if Firefox is already open, though. See this issue with Quarto documents: #12811.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Just to confirm, are you saying that when you click on this link:

<img width="497" alt="Screenshot 2023-08-08 at 1 54 30 PM" src="https://github.com/rstudio/rstudio/assets/1976582/70ed6cf8-d494-4b50-b2b6-d8dbddcf0b0c">

Firefox never opens? Does this affect any other kinds of external links in the IDE (e.g. Help links)?

**Comment by ronblum** [comment]
Correct. And other external links work, such as opening an external browser by clicking on "RStudio Community Forum" in the Help Pane which opens Firefox, or opening a .docx file which opens LibreOffice Writer.

**Comment by kevinushey** [comment]
It might be worth testing if the recent Electron upgrade from @timtmok fixes this... if not, we can add a workaround to take control of how that link is opened, I think.

**Comment by kevinushey** [comment]
Ugh, it looks like this is some sort of bad interaction between Electron and Firefox / xdg-open. There are a variety of bug reports:

https://github.com/electron/electron/issues/16149
https://github.com/electron/electron/issues/31485

> And other external links work, such as opening an external browser by clicking on "RStudio Community Forum" in the Help Pane which opens Firefox

Can you confirm? I tried testing, and this only works for me if Firefox is already open. If not, then I see the same behavior where Firefox fails to start.

**Comment by kevinushey** [comment]
This almost seems like an RHEL bug? Even a plain:

```
xdg-open https://www.posit.co
```

fails to open the site for me.

**Comment by kevinushey** [comment]
Okay, confirmed it's a bug in Firefox. See the discussions here:

https://bbs.archlinux.org/viewtopic.php?id=284906
https://bugzilla.mozilla.org/show_bug.cgi?id=1820896

Unfortunately, RHEL 9 ships with an old version of Firefox which doesn't have this fix.

How badly do we want to work to have a workaround for this issue?

**Comment by ronblum** [comment]
Ah! Confirmed that it works with Firefox 102.14.0esr after an update (`yum update firefox`). That's the solution, so I'm closing this.

**Comment by ronblum** [comment]
Verified on both RHEL 9 and SLES 15.5.
