### ISSUE TITLE
Allow pkgload, pkgdown links to run automatically

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#13460]
Hi, I was wondering if pkgload and pkgdown links could be run automatically in addition to  testthat, devtools, usethis and rlang?

https://cli.r-lib.org/reference/links.html#security-considerations

Thanks

pkgload and pkgdown are used when developping a package. In particular when visualizing the dev help.

Loading the packages solves the issue, but I opened the issue anyway since it's probably an easy fix on your side.

**Comment by ronblum** [comment]
@olivroy Thank you for the suggestion! We'll review it as we continue development of RStudio.

**Comment by olivroy** [comment]
Thanks!

 It would just be a change in this code line AFAIK
https://github.com/rstudio/rstudio/blob/eef58db265633af2a1677d344b6d043ca7da43c1/src/cpp/session/modules/SessionPackages.R#L281

**Comment by olivroy** [comment]
That works wonderfully in 2023.12.0+76! Thanks for accepting my PR! 🎉

**Comment by ronblum** [comment]
@olivroy I'm glad it works, and thank you for the submission! 🚀
