### ISSUE TITLE
Vertical offset in Arguments' section

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#13474]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-05) for Ubuntu Focal Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
    OS Version      : Linux 6.4.7-arch1-1 x86_64
    R Version       : 4.3.1

### Issue

I've updated to this new version of RStudio Desktop and now there is a small vertical offset between the argument name and its description. It seems to be a general issue across documentation pages. This is `logical()`'s page:

![snap](https://github.com/rstudio/rstudio/assets/19862384/5b810cb1-06b8-4b50-9fca-1997d41418fd)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This might be related to recent changes in the generated HTML help from R. For what it's worth, I see from a "plain" R instance:


<img width="694" alt="Screenshot 2023-08-09 at 8 24 00 PM" src="https://github.com/rstudio/rstudio/assets/1976582/cbcd0312-f112-413a-ad2e-d5bdcbe58f44">
