### ISSUE TITLE
BUG: Ctrl+Enter sporadically opens variables in a View tab

### ISSUE THREAD

**Issue by GabeAl** [rstudio/rstudio#13478]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1 (build 524)
    OS Version      : Fedora Linux 37 (also tested on a Clear Linux system)
    R Version       : 4.2.3 (also tested on Clear Linux with R 4.2-4.3)

### Steps to reproduce the problem
Problem occurs sporadically running the same code. 
In general: walk through code with Ctrl+Enter to execute lines (either in succession or as a block). This is however unreliable and I have been unable to consistently identify a single minimal set of reproducible instructions. 

However:
- No packages are loaded (only base R). 
- matrix and data frames both suffer from this issue
- The issue did not occur in previous versions of RStudio (2022 versions -- not sure about early 2023)

### Describe the problem in detail
Random variables in the workspace will open up and display in a new tab. This is a huge detriment to my work when the data are very large and it takes a long time to open a visualization tab. 

### Describe the behavior you expected
Ctrl+Enter should simply execute the line as intended and as in all previous versions of RStudio. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by katiedunkley** [comment]
I am having the same problem. Running code chunks sporadically opens up multiple tabs of the same dataframe, function or list. I am running a loop n = 88 times and it opens the same datafile 88 times for example. Takes time to close and becomes more frequent until I restart R. Then it starts again after a further few R chunk runs. I do not have View() anywhere in the code I am running. This is getting very frustrating and I cannot seem to find any help to rectify the situation. 

Using: 
R version 4.3.1 (2023-06-16)

**Comment by bromopsis** [comment]
Hello!
I also started encounter the same problem today. I run the same version as katiedunkley.

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Did anyone find a solution for this?
