### ISSUE TITLE
Colour highlighting in commented line

### ISSUE THREAD

**Issue by zx8754** [rstudio/rstudio#13473]
I like to keep colour hex names in the comments ready for use in the codes. But they do not get highlighted, is it possible to make them highlight even if they are commented?

![image](https://github.com/rstudio/rstudio/assets/5212915/74ed3c6e-2baf-4297-9fd4-d4cdde467b23)

RStudio version:
```
RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
```

**Comment by olivroy** [comment]
To add to that, suggestion to allow them in .md files
