### ISSUE TITLE
Rstudio Copilot not responding

### ISSUE THREAD

**Issue by kenzlegouge** [rstudio/rstudio#13486]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.09.0-daily+310 "Desert Sunflower" Daily (a0ebaba29bb67c20a99fb49587b3b1caf9ebca54, 2023-08-11) for windows
    OS Version      : Windows       10 x64  build 19045
    R Version       : 4.31

### Steps to reproduce the problem

On a fresh intall, log into Github copilot, fill security code in open window. 

### Describe the problem in detail

I am running Daily Build with latest R version. When trying to log into Copilot, the login screen pops up in browser and GitHub registers me as authorized after filling the security code. However, Rstudio fails to register me and waits indefinitly. After 5min, clicking cancel now displays a json string saying "status:NotAuthorized"

Here are the logs for this session :

> 2023-08-13T10:51:01.223287Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id '3c937f6d-e7cc-4642-bb52-826da417b05b', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676
> 2023-08-13T10:51:01.223287Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id '3c937f6d-e7cc-4642-bb52-826da417b05b', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676
> 2023-08-13T10:54:05.948675Z [rsession-KLG] ERROR [onExit]: Agent exited with status 1.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::agent::onExit(int) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:414
> 2023-08-13T10:54:05.948675Z [rsession-KLG] ERROR [onExit]: Agent exited with status 1.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::agent::onExit(int) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:414
> 2023-08-13T10:54:07.356146Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id 'd16595c4-c851-45d1-9a46-f1a2116cd922', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676
> 2023-08-13T10:54:07.356146Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id 'd16595c4-c851-45d1-9a46-f1a2116cd922', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676
> 2023-08-13T10:55:00.589464Z [rsession-KLG] ERROR [onExit]: Agent exited with status 1.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::agent::onExit(int) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:414
> 2023-08-13T10:55:00.589464Z [rsession-KLG] ERROR [onExit]: Agent exited with status 1.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::agent::onExit(int) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:414
> 2023-08-13T10:55:02.902429Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id '7a428079-27ea-4041-b1e5-095b3325d048', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676
> 2023-08-13T10:55:02.902429Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id '7a428079-27ea-4041-b1e5-095b3325d048', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676
> 2023-08-13T10:55:08.855701Z [rsession-KLG] ERROR [onExit]: Agent exited with status 1.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::agent::onExit(int) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:414
> 2023-08-13T10:55:08.855701Z [rsession-KLG] ERROR [onExit]: Agent exited with status 1.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::agent::onExit(int) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:414
> 2023-08-13T10:55:14.663292Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id '45abf40a-cbd6-409f-97c8-c86a918d4583', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676
> 2023-08-13T10:55:14.663292Z [rsession-KLG] WARNING [onBackgroundProcessing]: Received response with id '45abf40a-cbd6-409f-97c8-c86a918d4583', but no continuation is registered for that response.; LOGGED FROM: void __cdecl rstudio::session::modules::copilot::`anonymous-namespace'::onBackgroundProcessing(bool) C:\Users\jenkins\workspace\ide-os-windows\main\src\cpp\session\modules\SessionCopilot.cpp:676

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The error logs indicate that Copilot is exiting unexpectedly. Unfortunately, we don't have any other details why -- we'll probably need to investigate on our side and see if we can reproduce.

**Comment by kevinushey** [comment]
@kenzlegouge: we haven't received a response in a while, so we'll close this issue. Please follow up with more information if you're still having trouble and we can re-open. Thanks!
