### ISSUE TITLE
RStudio becomes slow if a list of large igraph objects is created

### ISSUE THREAD

**Issue by stibu81** [rstudio/rstudio#13489]
### System details

I reproduced this on two systems.

    RStudio Edition : Server
    RStudio Version : 2023.06.1 Build 524
    OS Version      : Ubuntu 20.04.6 LTS
    R Version       : 4.3.1
    igraph Version  : 1.5.1

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1 Build 524
    OS Version      : Ubuntu 22.04.3 LTS
    R Version       : 4.3.1
    igraph Version  : 1.5.1

### Steps to reproduce the problem

Create a list with many large igraph objects as follows (with igraph version 1.5.1):

    library(igraph)
    graphs <- replicate(100, make_full_graph(1000))

### Describe the problem in detail

The list is created but afterwards, CPU usage of the process rsession stays at about 100% for at least one hour (I aborted the running process after that). RStudio reacts only very slowly on any input on the R console or otherwise.

The problem does **not** appear in an ordinary R session, which is why I assume that it has to do with RStudio. Also, the problem does **not** occur with the Server and Desktop version 2022.07.2 Build 576 (Ubuntu 22.04, R 4.3.1).

I have checked that the problem also occurs with igraph versions 1.5.0, 1.4.3, 1.3.5.

This does **not** happen, if I create a single very large graph:

    graphs <- make_full_graph(50000)

This might be something similar to https://github.com/rstudio/rstudio/issues/12908. However, I can confirm that the problem described there does not persist in my RStudio installation.

Unfortunately, the problem is even a bit more complicated. I actually discovered this when I loaded a large list of graphs from an rds-file: RStudio gets very slow after loading the list of graphs with igraph 1.5.1 installed. However, in the case of this list, there is no problem with igraph 1.4.3 and igraph 1.3.5, but unfortunately, I have not managed to create a reproducible example for this (working fine with 1.3.5 and 1.4.3, not working with 1.5.1). But this indicates that the problem could at least partially be connected to this announcement of internal changes to igraph: https://github.com/igraph/rigraph/releases/tag/v1.5.0

### Describe the behavior you expected

The list should be created and RStudio should run smoothly afterwards.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dolchan** [comment]
I am experiencing similar problems with a list of large tidygraph objects created on "RSTUDIO-2023.06.1-524".  As soon as a large list of tidygraph objects is created, the IDE becomes extremely slow.  If I remove the list, it becomes responsive.  The problem disappeared when I downgraded to  "RStudio-2023.03.2-454".  The system I am using is MacBook Pro M2.

**Comment by stibu81** [comment]
@dolchan Since, according to [the documentation](https://tidygraph.data-imaginist.com/#more-data-structure-support), "tidygraph is powered by igraph underneath", I'm pretty sure that your problem is the same as this one.

**Comment by dolchan** [comment]
Thanks for the comment!  I guess so.  However, also the fact the issue disappear when I downgraded to 2023.03.2-454 with nothing else changed indicates there might some changes made to RStudio codes as well causing the problem.  When I tried the same codes with just regular R GUI, there was no issue.

**Comment by stibu81** [comment]
I can confirm that this is fixed in the current daily build of RStudio Server (RStudio 2023.09.0-daily+369). It is still the case that after creating the graphs, CPU usage remains at about 9% even though I'm doing nothing, which has no noticeable effect.

**Comment by kevinushey** [comment]
Thanks @stibu81 -- I think this is the issue described in https://github.com/rstudio/rstudio/issues/13534.

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+369](https://dailies.rstudio.com/version/2023.09.0-daily+369)
