### ISSUE TITLE
copilot: provide more information on why copilot isn't running

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13499]
I saw this when trying to enable copilot:

<img width="381" alt="Screenshot 2023-08-15 at 11 55 31 AM" src="https://github.com/rstudio/rstudio/assets/1976582/876e08b5-d43b-4e5b-a86d-89adab336960">

That's pretty opaque, and doesn't give any idea as to why Copilot isn't running.

**Comment by kevinushey** [comment]
Moving back to In Progress pending merge of https://github.com/rstudio/rstudio/pull/13891.

**Comment by kevinushey** [comment]
This should now be ready. To reproduce, you can try something like the following:

```
cd ~/.cache/rstudio/copilot/dist
cp agent.js agent.js.backup
echo "error" > agent.js
```

Then try navigating to Global Options... -> Copilot. You should see UI of the form:

<img width="654" alt="Screenshot 2023-11-27 at 1 20 06 PM" src="https://github.com/rstudio/rstudio/assets/1976582/4c3100c5-8e35-4c33-b3a1-2d7b75086d67">

And that modal message should be displayed when clicking the "Show Error..." button.

**Comment by jonvanausdeln** [comment]
Verified with https://dailies.rstudio.com/version/2023.12.0-daily+336 Open Source server on Ubuntu22

Error dialog shows as expected.
