### ISSUE TITLE
Add an admin setting to disable copilot

### ISSUE THREAD

**Issue by petetronic** [rstudio/rstudio#13495]
Admins should be able to set whether copilot is available to users in their organization.

**Comment by kevinushey** [comment]
Does this UI seem reasonable enough?

<img width="645" alt="Screenshot 2023-08-16 at 10 04 32 AM" src="https://github.com/rstudio/rstudio/assets/1976582/c8dc6d9d-51bb-4d3c-90db-67043f06ca55">

**Comment by jthomasmock** [comment]
Yes, I think we want to still show the feature but indicate it's disabled.
