### ISSUE TITLE
Copilot: Document in RStudio User Guide

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13504]
We (I) should put together a minimal overview of Copilot for the RStudio User Guide as it moves into Preview for Desert Sunflower:
- Installation of components.
- Authenticate.
- Turn on/off in global options or command palette.
- Basic interactive use with comments or code snippets
- Cross-interaction with normal auto-complete

**Comment by jthomasmock** [comment]
This is 90% done, waiting on some internal review and then will open a PR against rel-desert-sunflower.

**Comment by ronblum** [comment]
Verified in version 32 of the docs at https://docs.posit.co/ide/user/2023.09.0/
