### ISSUE TITLE
Enabling Copilot disables autocomplete

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13506]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0-daily+293
    OS Version      : MacOS 14.0
    R Version       : 4.3.1

### Steps to reproduce the problem

1. Make sure that autocomplete is turned on for automatic completion.
2. Enable Github Copilot.
3. In the Console Pane: `libr`
    - Nothing happens.
4. Disable Copilot.
5. In the Console Pane: `libr`
    - Autocomplete occurs, starting with `library` as an option.

### Describe the problem in detail

Autocomplete doesn't occur automatically if Copilot is enabled.

### Describe the behavior you expected

Autocomplete should happen, especially outside of the Editor Pane

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
To summarize, do you think we shouldn't use Copilot in the Console, and instead rely on the "default" completion behaviors?

**Comment by ronblum** [comment]
Interesting—I took it for granted that we should disable it in the Console, but the way I use the Console might be atypical. Let's rope in @jthomasmock to way in.

**Comment by kevinushey** [comment]
FWIW I think I agree; I suspect Copilot is less useful in the Console and is more useful in regular editor tabs; especially since the Console typically doesn't have much active context to synchronize with the Copilot agent.

**Comment by jthomasmock** [comment]
I agree w/ you both - I have found myself specifically doing some testing in the console without the Copilot prompt. So consider my vote one for "default" completion only in the console.

**Comment by kevinushey** [comment]
Copilot is now disabled in the Console, and you should get regular as-you-type completions there.

**Comment by ronblum** [comment]
Verified in 2023.09.0-daily+380 on MacOS 14 with Copilot enabled:
- In the Console Pane, recommendations are made using autocomplete, not Copilot suggestions.
- In the Editor Pane, recommendations are made using Copilot suggestions.
- In the Editor Pane, `Ctrl-Space` uses autocomplete
