### ISSUE TITLE
diagnostics system fails to detect 'mutate' as NSE function

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13512]
From @DavisVaughan:

Just a note that this exact code doesn't work right for `dplyr::mutate()` because `dplyr:::mutate.data.frame` actually uses `dplyr_quosures(...)` rather than something like `enquos(...)` to capture the vars.

<img width="242" alt="Screenshot 2023-08-17 at 12 35 07 PM" src="https://github.com/posit-dev/amalthea/assets/19150088/de69abe9-bb04-440f-9071-0582c3b3655c">

Also, this "symbol in scope" diagnostic is off in rstudio by default

---

I imagine there are also other cases where the `...` are passed untouched through various layers of function calls before finally being captured with `enquos(...)`. It works a little better with named variables where you have to do `enquo(x)` or `{{ x }}` to pass them through - even at the top level

Although even with named variables there are weird cases, like ggplot2's capturing of `x` and `y` here

```r
> ggplot2:::aes
function (x, y, ...) 
{
    xs <- arg_enquos("x")
    ys <- arg_enquos("y")
    dots <- enquos(...)
```

**Comment by ronblum** [comment]
Verified the first part, that `mutate` no longer throws a warning, in
- RStudio Desktop 2023.09.0-daily+380 on MacOS 14
- RStudio Server 2023.09.0-daily+380 on Ubuntu 20.04.5 via Chrome on MacOS 14

However, in this example from the PR, `pivot_long` is fine in RStudio Desktop, but a warning appears in RStudio Server:

```
library(tidyr)
df <- tibble(x = c("a", "b", "a"))
pivot_longer(df, x)
```

![Image](https://github.com/rstudio/rstudio/assets/31009952/1fa91bef-d111-404c-b1ea-2bc95845a10b)

**Comment by ronblum** [comment]
Sometimes `mutate` still shows a warning, but will later go away (Not certain of the conditions):
<img width="293" alt="mutate_is_back" src="https://github.com/rstudio/rstudio/assets/31009952/4057e84e-ad88-4885-88ea-3e300d89b3d8">

**Comment by kevinushey** [comment]
The issue should go away as soon as the `tidyr` and `dplyr` packages are loaded.

**Comment by ronblum** [comment]
Oops.... Ahem.

The `mutate`/`mpg` warning goes away when I remember to load the libraries. The warning for `pivot_longer` doesn't go away, though.

**Comment by ronblum** [comment]
Never mind—the `mutate` warning came back after a bit, even though the libraries were loaded.

**Comment by kevinushey** [comment]
Is there a way that I could reproduce this?

**Comment by ronblum** [comment]
Well, now I cn't reproduce it at all.... I'll leave this open for a few days and see if it happens to me again.

**Comment by kevinushey** [comment]
I'm going to close this as fixed; if it pops up again we can re-open?

**Comment by ronblum** [comment]
@kevinushey Sounds good!
