### ISSUE TITLE
Turn off Copilot by default in RStudio Server

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13527]
Turn off Copilot by default in RStudio Server. This will give administrators more control over it, who can still turn it on if they wish. (Especially relevant for the initial rollout.)

**Comment by ronblum** [comment]
It looks like this is getting turned off for RStudio Desktop, as well. It should be on for Desktop but off for Server.

**Comment by kevinushey** [comment]
Should be fixed via https://github.com/rstudio/rstudio/commit/355c79d82345a9cfe09384d925767165547e1551; hopefully to be live in the next daily builds.

**Comment by ronblum** [comment]
Verified that RStudio Desktop 2023.09.0-daily+380 on MacOS 14 is back in business. Now to check that Copilot is still disabled in RStudio Server.

**Comment by ronblum** [comment]
Verified in RStudio Server 2023.09.0-daily+380 on Ubuntu 20.04.5 via Chrome:
- Copilot is turned off by default.
- Copilot is turned off with `copilot-enabled=0` in /etc/rstudio/rsession.conf
- Copilot is enabled with `copilot-enabled=1` in /etc/rstudio/rsession.conf, authorization works, and Copilot returns suggestions

Note that while setting `copilot-enabled=1` will work turn on Copilot, is unsupported yet, as it hasn't been tested and certified. This would be strictly for testing purposes only, for the current release (Desert Sunflower).
