### ISSUE TITLE
Enable RStudio IDE to account for a global database connection set with knitr opts_chunks$set() for interactive execution of a SQL chunk.

### ISSUE THREAD

**Issue by rressler** [rstudio/rstudio#13525]
The goal is to have the RStudio IDE recognize the knitr chunk option for setting the database connection so it is recognized when a chunk is executed individually without having to identify the connection in each chunk. Reference is the R Markdown Definitive Guide. 

The solution would allow for each chunk to use the document set up option as the default connection unless overridden by a connection option within the chunk. Thus a document that uses only a single connection would only need it specified in the set up chunk.

Currently the global option works for a rendering but not interactive. The following picture shows an example where the interactive error message for the SQL chunk is on the left but the rendered document is on the right.
![image](https://github.com/rstudio/rstudio/assets/59033325/78e2a971-045b-4b63-831c-349239032b78)

@cderv provided an additional example and comments (See issue 13240).
Example:

`````
---
output: html_document
---

```{r setup}
library(DBI)
# Create an ephemeral in-memory RSQLite database
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)
dbListTables(con)
knitr::opts_chunk$set(connection = con)
```

```{sql}
SELECT * FROM mtcars WHERE cyl = 4
```
`````

Running interactively the second chunk will throw

> Error in .rs.runSqlForDataCapture("SELECT * FROM mtcars WHERE cyl = 4",  : 
>  The 'connection' option (DBI connection) is required for sql chunks.

RStudio IDE is not using knitr when doing interactive execution, and it is not aware of the knitr globally set chunk option.

Rendering the document works because knitr will account for the globally set chunk options.

**Comment by ronblum** [comment]
@jthomasmock Can you provide your thoughts?

**Comment by jthomasmock** [comment]
Thanks for the feature request! Parsing `knitr` options interactively is a fairly complex task but we'll evaluate that as we continue to develop RStudio.

While this is a bit of a workaround, I have used code snippets to make this easier and I always use `con` as the name of the connection.

You can create your own snippets as seen at: https://docs.posit.co/ide/user/ide/guide/productivity/snippets.html

Note, that in RMarkdown or Quarto you will insert them with the <kbd>Shift+Tab</kbd> shortcut.

Here is the snippet I use, and you can save it under the Edit Snippets > Markdown.

````
snippet sql
  ```{sql, connection=con}
  ${1}
  ```
````

https://github.com/rstudio/rstudio/assets/29187501/8024cc1c-dfe6-4df7-85d7-b017fffb2cca

Alternatively, if you want to write SQL but parse it interactively you could always use `DBI::dbGetQuery()`

```r
dbGetQuery(con, "SELECT * FROM mtcars WHERE cyl = 4")
```

OR use `dbplyr`

```r
copy_to(con, nycflights13::flights, "flights",
  temporary = FALSE, 
  indexes = list(
    c("year", "month", "day"), 
    "carrier", 
    "tailnum",
    "dest"
  )
)

flights_db <- tbl(con, "flights")
```

Where `dplyr` is translated to SQL on the fly for execution:

```r
flights_db %>% select(year:day, dep_delay, arr_delay)
#> # Source:   SQL [?? x 5]
#> # Database: sqlite 3.41.2 [:memory:]
#>    year month   day dep_delay arr_delay
#>   <int> <int> <int>     <dbl>     <dbl>
#> 1  2013     1     1         2        11
#> 2  2013     1     1         4        20
#> 3  2013     1     1         2        33
#> 4  2013     1     1        -1       -18
#> 5  2013     1     1        -6       -25
#> 6  2013     1     1        -4        12
#> # ℹ more rows

flights_db %>% filter(dep_delay > 240)
#> # Source:   SQL [?? x 19]
#> # Database: sqlite 3.41.2 [:memory:]
#>    year month   day dep_time sched_dep_time dep_delay arr_time
#>   <int> <int> <int>    <int>          <int>     <dbl>    <int>
#> 1  2013     1     1      848           1835       853     1001
#> 2  2013     1     1     1815           1325       290     2120
#> 3  2013     1     1     1842           1422       260     1958
#> 4  2013     1     1     2115           1700       255     2330
#> 5  2013     1     1     2205           1720       285       46
#> 6  2013     1     1     2343           1724       379      314
#> # ℹ more rows
#> # ℹ 12 more variables: sched_arr_time <int>, arr_delay <dbl>,
#> #   carrier <chr>, flight <int>, tailnum <chr>, origin <chr>, dest <chr>,
#> #   air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>,
#> #   time_hour <dbl>

flights_db %>% group_by(dest) %>%
summarise(delay = mean(dep_delay))
#> Warning: Missing values are always removed in SQL aggregation functions.
#> Use `na.rm = TRUE` to silence this warning
#> This warning is displayed once every 8 hours.
#> # Source:   SQL [?? x 2]
#> # Database: sqlite 3.41.2 [:memory:]
#>   dest  delay
#>   <chr> <dbl>
#> 1 ABQ   13.7 
#> 2 ACK    6.46
#> 3 ALB   23.6 
#> 4 ANC   12.9 
#> 5 ATL   12.5 
#> 6 AUS   13.0 
#> # ℹ more rows
```

**Comment by rressler** [comment]
Thanks for considering this. I am showing the students what you suggested and also how to assign a keyboard shortcut to the RStudio `Insert Chunk S Q L` which makes an SQL chunk with a header argument for connection.
Thanks!

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+84 on MacOS 14 using the example in the original post.

![Image](https://github.com/rstudio/rstudio/assets/31009952/198b3ba3-e697-43a8-b806-12648cef22bf)

**Comment by rressler** [comment]
Ron, Thanks!
RIchard

From: Ron Blum ***@***.***>
Date: Wednesday, September 27, 2023 at 8:40 AM
To: rstudio/rstudio ***@***.***>
Cc: Richard Ressler ***@***.***>, State change ***@***.***>
Subject: Re: [rstudio/rstudio] Enable RStudio IDE to account for a global database connection set with knitr opts_chunks$set() for interactive execution of a SQL chunk. (Issue #13525)

External Email: Use caution with links and attachments.

Verified in RStudio Desktop 2023.12.0-daily+84 on MacOS 14 using the example in the original post.

[Image removed by sender. Image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/31009952/270979735-198b3ba3-e697-43a8-b806-12648cef22bf.png__;!!IaT_gp1N!zeswYiKKVYIxCxaAESq82AjGEkxrmrnjqjLbz2WY3bi7toKUVi-CBjWe7bTWEvFH_od_0Gkp3f8bIUtHvBsC5FLQfr8$>
