### ISSUE TITLE
weird html rendering in rmarkdown in latest Rstudio app (still not solved)

### ISSUE THREAD

**Issue by jlxAtNovozymes** [rstudio/rstudio#13524]
Hi, I downloaded the rstudio of latest version, but weird things happened. when I use highcharter or plotly to generate html graph in rmarkdown, it looks dim.
![image](https://github.com/rstudio/rstudio/assets/90908083/9f16b3d2-9751-416f-912e-f22fc48e1275)

but when I move my cursor to that html graph, it becomes lighter, it's really annoying,  does anyone knows the reason?

**Comment by ronblum** [comment]
@jlxAtNovozymes Thank you for raising this! A couple of things:

1. Does this work correctly in the knitted output?
2. Can you provide you system information?

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jlxAtNovozymes** [comment]
> @jlxAtNovozymes Thank you for raising this! A couple of things:
> 
> 1. Does this work correctly in the knitted output?
> 2. Can you provide you system information?
>    RStudio Edition : "Mountain Hydrangea" Release
>    RStudio Version : RStudio 2023.06.1+524
>    OS Version      : mingw32
>    R Version       : 4.1.0

Hi, Ron, thanks for replying this issue. it works work correctly in the knitted output. this issue only happens when you are editing rmd files or qmd files

below is outout of "version" command:
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          1.0                         
year           2021                        
month          05                          
day            18                          
svn rev        80317                       
language       R                           
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen

**Comment by jlxAtNovozymes** [comment]
@ronblum , did you receive my reply, I added some information you may need

**Comment by jlxAtNovozymes** [comment]
will anyone solve this problem? @ronblum

**Comment by jlxAtNovozymes** [comment]
I think it's still an important issue

**Comment by ronblum** [comment]
@jlxAtNovozymes Can you provide a minimal reproducible example? I tried with transcribing code from the image and installing `highcharter`, but I get an error that `.tbl` is missing.

```
library(magrittr)
library(highcharter)
dplyr::mutate_if(.predicate = is_double,
                 .funs = ~ round(.x, 1)) %>%
  hchart(type = 'scatter',
         hcaes(x = displ, y = cty, group = manufacturer, size = cty))
```

results in 
```
Error in dplyr::mutate_if(.predicate = is_double, .funs = ~round(.x, 1)) : 
  argument ".tbl" is missing, with no default
```
