### ISSUE TITLE
Quarto + Copilot doesn't work

### ISSUE THREAD

**Issue by alanpaulkwan** [rstudio/rstudio#13523]
On the same server where Rstudio copilot is working (thanks!) Quarto doesn't work. 

RMarkdown/RNotebook, which achieve similar purposes, seem great though.

**Comment by ronblum** [comment]
@alanpaulkwan Thank you for raising this! Are you by chance using the visual editor, and if so, what happens if you switch to source mode?

Also, can you provide your system details? Thanks!
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by ronblum** [comment]
@alanpaulkwan Good to know, thank you! There's an issue already open, asking about supporting Copilot recommendations in visual mode, so I'll close this one.

**Comment by VoidTrekker** [comment]
It's been a while that even in source mode my copilot does not work.

---
RStudio Edition : MacOS Desktop>
RStudio Version : Version 2024.12.0+467 (2024.12.0+467)
OS Version      : 15.3.1 (24D70)
R Version       :  R version 4.4.2 (2024-10-31) -- "Pile of Leaves"
---

It is tricky as it works for the first chunk of R codes inserted in the Quarto file. However, after inserting a second chunk, it does not work anymore.

Copilot being in "No more completion available" status.

**Comment by kevinushey** [comment]
Can you please update to RStudio 204.12.1+563 and let us know if the issue still persists?

**Comment by VoidTrekker** [comment]
> Can you please update to RStudio 204.12.1+563 and let us know if the issue still persists?

Hi Kevin,

Thanks, it seems working fine now after updated. I should've checked it before I report. thanks for your help.
