### ISSUE TITLE
No ability to accept copilot suggestions word-by-word

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#13522]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0-daily+347 "Desert Sunflower" Daily (6b14ae05ab615040a0e7a1e66ae1737e6aef3f00, 2023-08-18) 
    OS Version      : Ubuntu Jammy
    R Version       : R version 4.3.1 (2023-06-16)

```
RStudio 2023.09.0-daily+347 "Desert Sunflower" Daily (6b14ae05ab615040a0e7a1e66ae1737e6aef3f00, 2023-08-18) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.09.0-daily+347 Chrome/114.0.5735.289 Electron/25.5.0 Safari/537.36
```

### Steps to reproduce the problem

Authenticate copilot, write something, and try to accept only the first word by pressing Right arrow + Tab.

### Describe the problem in detail

You can only accept all or nothing, as far as I can tell.

### Describe the behavior you expected

It should work like VS Code's copilot where you can accept one word at a time by pressing Ctrl+Right: https://stackoverflow.com/questions/75114315/how-to-accept-only-the-next-word-in-github-copilot-suggestion

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
I tested with [2023.12.0-daily+313](https://dailies.rstudio.com/version/2023.12.0-daily+313) on Windows 11 and Ubuntu22

I can only seem to get full completion, not word-by-word.  I tried several combinations of the right arrow key combinations including `Right Arrow + Tab` as suggested by OP.

Example of what I'm seeing
![image](https://github.com/rstudio/rstudio/assets/6433789/ff53d1c7-8828-4a5f-baea-69cab121b0e3)

I can only get the full line to be accepted.

@kevinushey what is the key combination that should trigger this?

**Comment by kevinushey** [comment]
I didn't set up any default keybinding for this, but if we want to take a page from VSCode, it looks like they use `Cmd + Right` as the default keybinding for accepting the next word of a suggestion. We could consider doing something similar.

**Comment by jonvanausdeln** [comment]
I added a keybind for `Ctrl + Right` and it works as expected! I was able to accept individual words of the copilot suggestion.

**Comment by Robinlovelace** [comment]
Great work guys!

**Comment by jonvanausdeln** [comment]
Instructions to modifying keyboard shortcuts (needed to use this feature) can be found here: https://support.posit.co/hc/en-us/articles/206382178

**Comment by Robinlovelace** [comment]
> Instructions to modifying keyboard shortcuts (needed to use this feature) can be found here: https://support.posit.co/hc/en-us/articles/206382178

Hey @jonvanausdeln I just took a look but this is not a solution for many people. Incrementally accepting suggestions vs all/nothing is *essential* for effective use of co-pilot. Therefore it should work out of the box, right?

I can open a follow-on issue, just wanted to check my logic and that this isn't already being worked on.

**Comment by kevinushey** [comment]
@Robinlovelace A follow-up issue would be greatly appreciated -- thanks!
