### ISSUE TITLE
Visual Editor: Hovering the cursor over a citation key displays a reference without spaces between some of the words

### ISSUE THREAD

**Issue by pedrohbraga** [rstudio/rstudio#13537]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 Build 347
    OS Version      :  Windows 11
    R Version       : 4.3.0

### Steps to reproduce the problem

1. Open a Quarto document, and save it to a directory;
2. Create a `.bib` file with a BibTeX reference in it. Here are a few examples:

```
@article{bragaHistoricalContemporaryProcesses2023,
	title = {Historical and contemporary processes drive global phylogenetic structure across geographical scales: Insights from bat communities},
	author = {Braga, Pedro Henrique Pereira and Kembel, Steven and Peres-Neto, Pedro},
	year = {2023},
	date = {2023},
	journal = {Global Ecology and Biogeography},
	pages = {747--765},
	volume = {32},
	number = {5},
	doi = {10.1111/geb.13650},
	url = {https://onlinelibrary.wiley.com/doi/abs/10.1111/geb.13650},
	note = {{\_}eprint: https://onlinelibrary.wiley.com/doi/pdf/10.1111/geb.13650},
	langid = {en}
}

@article{kisslingCenozoicImprintsPhylogenetic2012,
	title = {Cenozoic imprints on the phylogenetic structure of palm species assemblages worldwide},
	author = {Kissling, W. Daniel and Eiserhardt, Wolf L. and Baker, William J. and Borchsenius, Finn and Couvreur, Thomas L. P. and Balslev, Henrik and Svenning, Jens-Christian},
	year = {2012},
	month = {05},
	date = {2012-05-08},
	journal = {Proceedings of the National Academy of Sciences},
	pages = {7379--7384},
	volume = {109},
	number = {19},
	doi = {10.1073/pnas.1120467109},
	url = {https://www.pnas.org/content/109/19/7379},
	note = {PMID: 22529387},
	langid = {en}
}

@article{thuillerProductivityBegetsLess2020,
	title = {Productivity begets less phylogenetic diversity but higher uniqueness than expected},
	author = {Thuiller, Wilfried and Gravel, Dominique and Ficetola, Gentile Francesco and Lavergne, {Sébastien} and {Münkemüller}, Tamara and Pollock, Laura J. and Zimmermann, Niklaus E. and Mazel, Florent},
	year = {2020},
	date = {2020},
	journal = {Journal of Biogeography},
	pages = {44--58},
	volume = {47},
	number = {1},
	doi = {10.1111/jbi.13630},
	url = {http://onlinelibrary.wiley.com/doi/abs/10.1111/jbi.13630},
	note = {{\_}eprint: https://onlinelibrary.wiley.com/doi/pdf/10.1111/jbi.13630},
	langid = {en}
}

```

4. Write a paragraph using these citation keys. Here is an example:

```
These geographical extents have also been used while studying the causes underlying spatial scale dependence in the structure of ecological communities [e.g., @kisslingCenozoicImprintsPhylogenetic2012; @thuillerProductivityBegetsLess2020; @bragaHistoricalContemporaryProcesses2023]. 
````

5. Add the `.bib` file to the YAML and Render the document. Here is an example of a YAML:

```
---
title: "Hovering"
date: last-modified
number-sections: true
format:
  html: 
    smooth-scroll: true
    embed-resources: true
    self-contained-math: true
comments:
  hypothesis: 
    theme: clean
editor: 
  markdown: 
    wrap: sentence
execute: 
  cache: true
bibliography: references.bib
theme: spacelab
---
```
6. In the Visual Editor, hover over the citation keys.

### Describe the problem in detail

![image](https://github.com/rstudio/rstudio/assets/8599229/0ca1095c-0313-4181-8f5d-923946acb4d1)

![image](https://github.com/rstudio/rstudio/assets/8599229/55f5ee35-1297-428c-bd0b-299fdb744b76)

![image](https://github.com/rstudio/rstudio/assets/8599229/0c560f08-e4e2-49ca-ba96-310dd98c90f1)

### Describe the behaviour you expected

Although the issue is not critical and I am still able to see the text, the lack of spacing between certain words is not expected.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by pedrohbraga** [comment]
It should also be noted that I use Zotero and RStudio's native integration to it.

**Comment by ronblum** [comment]
@pedrohbraga Thank you for raising this! I can reproduce this in RStudio Desktop 2023.03.2+454 and 2023.09.0-daily+358 on MacOS 14, without using Zotero. Note that this is only in hovering in the visual editor—the citations show up properly with a rendered file.
