### ISSUE TITLE
rsconnect update calls wrong version

### ISSUE THREAD

**Issue by martym-sentinel** [rstudio/rstudio#13538]
### System details

    RStudio Edition : DESKTOP
    RStudio Version : Version 2023.06.0+421 (2023.06.0+421
    OS Version      : MAC OS 13.5 (22G74)
    R Version       : 4.3.1

### Steps to reproduce the problem

use the updates window in R Studio to update package RSCONNECT

### Describe the problem in detail

RStudio calls cran to update to version 0.8.29, which is no longer supported by shiny

### Describe the behavior you expected

RStudio SHOULD call rsconnect version 1.0.2 and update it from CRAN

## here's the code

```
install.packages("rsconnect")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://ftp.osuosl.org/pub/cran/bin/macosx/big-sur-x86_64/contrib/4.3/rsconnect_0.8.29.tgz'
Content type 'application/x-gzip' length 701151 bytes (684 KB)
==================================================
downloaded 684 KB
```
##

this problem is the same whether using rstudio or the basic r interface

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@martym-sentinel Thank you for raising this! There's currently an issue with getting the latest version of `rsconnect` for MacOS with R 4.3. (The same occurs outside of RStudio.) We're looking into it.
