### ISSUE TITLE
Hovering over diagnostic symbols doesn't show the messages

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13532]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2023.09.0-daily+348
    OS Version      : MacOS 14 and Ubuntu 22.04.5
    R Version       : 4.3.1

### Steps to reproduce the problem

1. <kbd>Tools -> Global Options -> Code -> Diagnostics</kbd>
2. Let's check everything to make things easy.
3. Create a new R file.
4. Enter the following
```
print(x)
y = "hello" // 12
```
5. Save the file.
6. Wait for the warning and error symbols to appear to the left of the row number.
7. However over the warning and error signs.
    - Nothing happens.

### Describe the problem in detail

Hovering over the warning and error symbols doesn't show the warnings and errors.

<img width="191" alt="diagnostics" src="https://github.com/rstudio/rstudio/assets/31009952/1ba93f67-94da-4781-a65e-3390ebef335c">

### Describe the behavior you expected

The warning and error messages should appear.

This is a regression, as it worked in RStudio 2023.06.2+555.

<img width="383" alt="diagnostics" src="https://github.com/rstudio/rstudio/assets/31009952/d142b283-1cb3-43f5-b43a-c886da80d047">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
https://github.com/rstudio/rstudio/blame/main/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetLintSource.java#L93-L118

This is where the source markers are processed for display. It looks like there was a change here since I last touched it. That might have caused this regression. In any case, this is a good place to start for determining a cause.

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionMarkers.cpp#L89

This is also where the markers are sent to GWT. It's probably fine but it might be helpful to verify that the rsession is passing the correct source markers to GWT.

**Comment by kevinushey** [comment]
It looks like there's a JS exception in Ace when it tries to show the marker:

<img width="493" alt="Screenshot 2023-08-24 at 10 25 25 AM" src="https://github.com/rstudio/rstudio/assets/1976582/32dc85ad-4830-4e53-9eba-3b4d4f5e4352">

This could also be some fallout from a recent Ace update. Apparently Ace is expecting a theme to be set on the renderer:

<img width="340" alt="Screenshot 2023-08-24 at 10 25 52 AM" src="https://github.com/rstudio/rstudio/assets/1976582/a4663722-9b71-47e2-b597-c63a2789395f">

**Comment by kevinushey** [comment]
I can confirm this is related to a recent Ace update -- I'll see if I can dig up the rest.

**Comment by kevinushey** [comment]
The editor previews also look incorrect:

<img width="641" alt="Screenshot 2023-08-24 at 10 40 42 AM" src="https://github.com/rstudio/rstudio/assets/1976582/8cbb4889-0fa3-4af2-8ad2-4381c16899d2">

**Comment by ronblum** [comment]
The details are showing up, but only if:
1) The file is open when RStudio is loaded.
2) This is the first file created after loading RStudio.

Example:
1. Create the file above.
2. Hover over the symbols.
    - The messages show up.
3. Leave the file open, but close RStudio.
4. Reopen RStudio.
5. Hover over the symbols.
    - The messages show up.
6. Close the file.
7. Reopen the file.
8. Hover over the symbols.
    - The messages no longer show up.

**Comment by kevinushey** [comment]
Thanks for catching that @ronblum! It looks like the underlying cause is exactly the same, so the fix in https://github.com/rstudio/rstudio/pull/13551 must have fixed some scenarios.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2023.09.0-daily+380 on MacOS 14
- RStudio Server 2023.09.0-daily+380 on Ubuntu 20.04.5 via Chrome on MacOS 14

Plus, the messages are prettier. 😃 

![Image](https://github.com/rstudio/rstudio/assets/31009952/03f031e8-00ec-48ab-92fa-f6af27000ed9)
