### ISSUE TITLE
Publishing Rmd Site to Posit Cloud results in 404's for some pages of site

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#13535]
### System details

    RStudio Edition : Desktop and Server (posit.cloud)
    RStudio Version : 2023.06.1+524.pro1 (also on 2023.03.1+446)
    OS Version      : All
    R Version       : 4.2

### Steps to reproduce the problem
[mywebsite.zip](https://github.com/rstudio/rstudio/files/12412077/mywebsite.zip)

1) create a new project (new directory > new project)
2) copy the mywebsite directory into the project (attached)
3) install the required viridis package using install.packages('viridis')
4) open the index.Rmd file and click on the Publish button
5) select posit.cloud and publish. notice that the dialog lists all the files in the site.
6) Publish site

### Describe the problem in detail
when the site is published, only the index file is rendered. if you click on other pages in the site, you get a 404

### Describe the behavior you expected
Site to not give 404 for any pages

Note:

If you publish the site manually using rsconnect::deploySite("mywebsite", server = "posit.cloud", render="server"), then all the pages are rendered and you don't get any 404s. The difference is in the manifest.json's metadata section:

via the publish button:

```
"metadata": {
    "appmode": "rmd-static",
    "primary_rmd": "index.Rmd",
    "primary_html": null,
    "content_category": null,
    "has_parameters": false
  },
```
via rsconnect::deploySite:

```
  "metadata": {
    "appmode": "rmd-static",
    "primary_rmd": "index.Rmd",
    "primary_html": null,
    "content_category": "site",
    "has_parameters": false
  }, 
```

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Note.. I added this to DS milestone as `Ready`, but since this has been an issue since at least Cherry Blossom, it might be okay to move out to later release.

**Comment by petetronic** [comment]
@jgutman would this be a low risk fix?

**Comment by jgutman** [comment]
@petetronic @jonvanausdeln Yes, this is low-risk. We should test with website that 1) has been rendered prior to publishing, and 2) has NOT been rendered prior to publishing.

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+385](https://dailies.rstudio.com/version/2023.09.0-daily+385)

All the pages are accessible now and don't return error codes.
