### ISSUE TITLE
Avoid touching the row names of a data frame if they are ALTREP

### ISSUE THREAD

**Issue by krlmlr** [rstudio/rstudio#13540]
The example below works differently in the RStudio IDE and in an R script.

The "materializing" message is triggered by the IDE accessing the `"row.names"` attribute of the `df` variable. The `df` is a special data frame, computation starts to happen (via ALTREP) when something tickles the row names. I suspect that this is because `df` is shown in the environment pane, with details. Can we avoid analyzing the dimensions (row count) of a data frame if the `"row.names"` attribute is ALTREP?

CC @DavisVaughan @hannes @kevinushey.

## RStudio IDE

``` r
options(duckdb.materialize_message = TRUE)

con <- DBI::dbConnect(duckdb::duckdb())

rel <- duckdb:::rel_from_df(con, data.frame(a = 1))

df <- duckdb:::rel_to_altrep(rel)

class(df)
#> [1] "data.frame"
#> materializing:
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> r_dataframe_scan(0x11e98bfd8)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - a (DOUBLE)
#> 
```

<sup>Faked on 2023-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## R script

``` r
options(duckdb.materialize_message = TRUE)

con <- DBI::dbConnect(duckdb::duckdb())

rel <- duckdb:::rel_from_df(con, data.frame(a = 1))

df <- duckdb:::rel_to_altrep(rel)

class(df)
#> [1] "data.frame"
```

<sup>Created on 2023-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I do think we should try and fix this, but a "horrible hack" that at least makes it workable for now is to make the env pane update _manually_. As long as you don't use the env pane it won't materialize early.

<img width="1071" alt="Screenshot 2023-08-23 at 10 02 54 AM" src="https://github.com/rstudio/rstudio/assets/19150088/37b1e688-36f2-43a6-9639-93c421e78894">

**Comment by DavisVaughan** [comment]
I believe I've tracked it down to the `dim()` call here:
https://github.com/rstudio/rstudio/blob/9e5ccb28e99dbc9ac4b055eac543d5025d5ea1e1/src/cpp/session/modules/SessionEnvironment.R#L531-L536

We should probably change this to do something like:

```r
n_cols <- length(obj)

# Query internal row names attribute 
has_altrep_rownames <- .rs.isAltrep(.row_names_info(obj, 0L))

if (has_altrep_rownames) {
  n_row <- -1L
} else {
  n_row <- nrow(obj)
}
```

And then build the string from there, possibly using `??` for the number of rows in the ALTREP case.

---

The goal here would be for the data frame to be able to show up in the Env pane without early materialization until the user presses the "expand this object so i can see the columns" or "show this object in the viewer" buttons. i.e. the same behavior as 
https://github.com/rstudio/rstudio/pull/4764

**Comment by kevinushey** [comment]
Hmm, but:

```
> df <- duckdb:::rel_to_altrep(rel)
> class(df)
[1] "data.frame"
```

Should this have some other custom class here?

**Comment by kevinushey** [comment]
Can we request the length of the vector without materializing it?

**Comment by DavisVaughan** [comment]
> Should this have some other custom class here?

Sorry I spoke incorrectly about that earlier. The data frame that duckdb produces there _is_ a typical run of the mill data frame. But the row-names attribute is ALTREP and the vectors that make up the columns are ALTREP.

You should be able to call `length()` on it to request the number of columns without materializing, yea

**Comment by kevinushey** [comment]
I think duckdb needs to implement dataptr_or_null so that we can query the vector length after it's been materialized here: https://github.com/duckdb/duckdb/blob/3196df79cecac38c867af084f19924c78dfc9d29/tools/rpkg/src/reltoaltrep.cpp#L34-L38

**Comment by DavisVaughan** [comment]
@krlmlr do you think you can implement `Dataptr_or_null` ALTREP methods for your ALTREP types?

Should be fairly straightforward, something like "if this object has been materialized before, return the `DATAPTR()` to it, otherwise return `NULL` to refuse to materialize it"

The deferred string methods should be a good guide
https://github.com/wch/r-source/blob/79e959e4c8ad12fbeeba31667b67e7fe8117aec7/src/main/altclasses.c#L764
https://github.com/wch/r-source/blob/79e959e4c8ad12fbeeba31667b67e7fe8117aec7/src/main/altclasses.c#L855

**Comment by krlmlr** [comment]
I see what you mean, just using `ALTREP()` to query ALTREP-ness won't suffice, I suppose. I'll put something together.

**Comment by kevinushey** [comment]
@DavisVaughan or @krlmlr: would you be able to test with an upcoming daily build of RStudio and confirm if the issue is resolved?

**Comment by krlmlr** [comment]
Sure, happy to test! Will this require a duckdb version with "dataptr or null"?

**Comment by kevinushey** [comment]
It shouldn't, the only downside is that duckdb data.frames will always disable in the Environment pane as having `?? obs. of <n> columns`.

**Comment by krlmlr** [comment]
Draft implementation here. How would I test it?

**Comment by DavisVaughan** [comment]
Rather than `return R_NilValue;` in `RownamesDataptrOrNull()` I think you want to literally return the C `NULL` pointer

---

For testing:
- Get latest daily https://dailies.rstudio.com/
- Make sure your patched package is installed
- Run your original reprex. The env pane should show df but with `??` shown as the number of observations
- Materialize `df` manually
- You may need to hit the refresh button on the env pane, but if it is working correctly then `??` should update to `1` (or however many rows you have)

**Comment by DavisVaughan** [comment]
@kevinushey I see the current expected behavior with CRAN duckdb / duckplyr in the latest daily, thanks!

https://github.com/rstudio/rstudio/assets/19150088/3cd135d8-bb4d-40a5-ae48-a30390532a90

**Comment by kevinushey** [comment]
Awesome, thank you!

**Comment by krlmlr** [comment]
Tested with the nightly, works like a charm. I love how the preview shows the query plan.

With a variant of https://github.com/duckdb/duckdb/compare/main...krlmlr:duckdb:f-dataptr-or-null, the "??" also disappears when I hit the "refresh" button". The "??" remains if I merely click on the "table" icon or on the list item. I wonder if these actions should also trigger a refresh of the clicked item.
