### ISSUE TITLE
Copilot: Option to enable copilot to learn from adjacent files

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13547]
Github copilot in some iterations can take prompts from other open files.

> Copilot looks at the current and open files in your editor to analyze the context and create appropriate suggestions.

It would be nice if there were options to control the prompt files: 
- Only the currently active file
- Current active file + other "visible" files, ie top level files opened in additional source columns
- Current file + all other open files

This would likely also interact with: https://github.com/rstudio/rstudio/issues/13503 and the ability to globally disable Copilot on specific file extensions.

**Comment by kevinushey** [comment]
Not exactly sure how to test this... perhaps try opening an RStudio project, and see if Copilot suggestions seem to take into account information from other R scripts in the project?

**Comment by jthomasmock** [comment]
> Not exactly sure how to test this... perhaps try opening an RStudio project, and see if Copilot suggestions seem to take into account information from other R scripts in the project?'

Awesome to see this!

We should be able to see it in the request with debug logging on right? I also think that this feature should likely be turned off by default so that we don't overwhelm the token limit if folks try Copilot in their root folder (outside of a project) with potentially hundreds of files 😬

**Comment by ronblum** [comment]
Verified by going for a hint that Copilot is very unlikely to provide as the first suggestion. 

With Copilot and project indexing turned on, here's how I tested in RStudio Desktop 2023.09.0-daily+385 on MacOS 14.

1. Create a new project in a new directory.
2. Open a new R script.
3. In the Source Editor: `# What good `
4. Wait a moment for Copilot to make a suggestion. Don't accept it.
    - Copilot will make a coding-related suggestion, for example:
    - ![Image](https://github.com/rstudio/rstudio/assets/31009952/08762384-d6c4-43b9-8b9a-5fc1b458940b)
5. Continue typing, `is sitting alone`
6. Wait a moment. Copilot should now suggest `# What good is sitting alone in your room?`
7. Several times, accept the suggestion and go to the next line. You should end up with the few lines of "Cabaret," from the musical of the same name.

![Image](https://github.com/rstudio/rstudio/assets/31009952/446cb79e-4438-47f8-a240-810a21418ffb)

8. Save the file.
9. Close the file.
10. Close the project. [I don't think that this should be necessary. See below]
11. Reopen the project.
12. Open a new R file.
13. In the Source Editor: `# What good ` and wait a moment.
    - Copilot should suggest the opening line of "Cabaret."
    - ![Image](https://github.com/rstudio/rstudio/assets/31009952/64dd14dd-8422-4cc2-99da-55fc9b5edd3c)
14. Accept the suggestion.
15. Continue to accept suggestions will continue to print the lyrics, and maybe some new stuff.
16. Close the project. 
17. Open a new R file.
18. In the Source Editor: `# What good `
19. Wait a moment for Copilot to make a suggestion.
    - Copilot will make a coding-related suggestion, probably the same as the original suggestion in step 4.

**Comment by ronblum** [comment]
@kevinushey How often does indexing occur? Can't it be forced? I don't think that step 10 (x), closing the project, should be needed.

**Comment by ronblum** [comment]
Another test, this time using code.

1. Start with a new file and a line that says, `# Function that get average mpg from cars dataset`
2. Accept suggestions until a function is defined. For example, in my cases, I got
```
get_average_mpg <- function(dataset) {
  mean(dataset$mpg)
}
```
3. Save this file. 
4. Change the function name near the start, e.g. `get_my_average_mpg`
5. Save the file. (And possibly need  to close and reopen the project.)
6. In a new file, use the beginning of the revised function name, e.g. `x <- get_my` which should autocomplete with the suggestion `x <- get_my_average_mpg(cars)`

<img width="249" alt="Screenshot 2023-09-05 at 10 21 00" src="https://github.com/rstudio/rstudio/assets/31009952/2252e31e-6e14-4bdd-918a-9b24360a3c06">

7. Now start with this line: `# Function that gets the average Sepal.Width from iris dataset`
8. The recommendations should now continue using the change, e.g. in this case the recommendation ends up with
```
# Function that gets the average Sepal.width from iris dataset
# Input: dataset
# Output: average Sepal.width
get_my_average_Sepal_width <- function(dataset) {
  mean(dataset$Sepal.Width)
}
```
9. In the first file, enter 
```
get_your_average_speed <- function(dataset) {
  mean(dataset$speed)
}
```
and save the file.
10. In the second file, type `get_your` which should complete to `x <- get_your_average_speed(cars)`
<img width="281" alt="Screenshot 2023-09-05 at 10 31 45" src="https://github.com/rstudio/rstudio/assets/31009952/85767ef3-a1b1-41ed-bd02-e5c962390898">

**Comment by jthomasmock** [comment]
@kevinushey - I'm sorry for the late update here, but I'm considering whether we should re-open this issue/revisit the feature's scope.

I'm realizing that the "index files on disk" vs "index open files in source pane" is a specific workflow. There's a limit on how much can be sent over to Copilot/used as a prompt. Switching this feature to index the user-selected open files, allows the user to cleanly constrain/expand the additional files that are indexed. I was reminded of this when someone mentioned in the Q/A that they had specific files that they did and didn't want to send to Copilot.

**Comment by kevinushey** [comment]
FWIW the default behavior is "index open files", and open files are always indexed. The preference here just controls whether project files are also indexed by Copilot.

**Comment by jthomasmock** [comment]
Ah! Thanks for clarification. I'll clarify some of that in the user docs instead then. Thanks!
