### ISSUE TITLE
Add French translations for Rosetta installation warning

### ISSUE THREAD

**Issue by sharon-wang** [rstudio/rstudio#13548]
Follow-up to #12791 to include French translations for the strings used in the warning dialog.

Strings in this file will need French translations: https://github.com/rstudio/rstudio/blob/main/src/node/desktop/src/main/detect-rosetta.ts

**Comment by sharon-wang** [comment]
A note on my progress so far:

I have the string translations themselves ready, but I'm running into issues detecting the locale at the point that `detectRosetta` is called. This needs to be resolved because we won't be able to support a language other than the default (English) if we can't detect the LOCALE setting.

Possible workarounds:
- Move the `detectRosetta` call to a later point, when the main window is ready. With access to the main browser window, we can check the cookies for the `LOCALE` value and `changeLanguage()` so the i18n instance switches to the right strings
- Don't initialize a new instance of the i18n manager, which won't know about the `LOCALE`. Where can the strings live so that an existing instance of i18n can set the strings properly?

I've tried working in both of the above workarounds, but keep running into issues around not being able to access the LOCALE or i18n early enough.

WIP branch: https://github.com/rstudio/rstudio/tree/add-fr-translations-rosetta-install-warning

**Comment by kevinushey** [comment]
> Move the detectRosetta call to a later point, when the main window is ready. With access to the main browser window, we can check the cookies for the LOCALE value and changeLanguage() so the i18n instance switches to the right strings

This seems like the right solution. Alternatively, something similar would be to have some kind of way of registering "on load" callbacks with the i18n manager, so you could have something like:

```
i18nManager.onReady(() => {
  // display the Rosetta window
})
```

And then that `onReady()` helper would either run the callback immediately if the i18n manager is already initialized, or register the callback to be run later when it is initialized.

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+414](https://dailies.rstudio.com/version/2023.09.0-daily+414)

French displayed as expected (MacOS only)
