### ISSUE TITLE
Require rsconnect 1.0.2 when publishing Quarto manuscript

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13555]
Pulled from https://github.com/rstudio/rstudio/pull/13528. Rather than update the version of 'rsconnect' required globally, we'll request a new version of rsconnect only when publishing Quarto manuscripts.

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+381](https://dailies.rstudio.com/version/2023.09.0-daily+381)

Note, requires quarto 1.4, which is not yet released.
