### ISSUE TITLE
Ace editor preview themes are not applied correctly

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13552]
For example:

<img width="641" alt="Screenshot 2023-08-24 at 10 40 42 AM" src="https://github.com/rstudio/rstudio/assets/1976582/8cbb4889-0fa3-4af2-8ad2-4381c16899d2">

Compare with the previous release:

<img width="601" alt="Screenshot 2023-08-24 at 2 08 15 PM" src="https://github.com/rstudio/rstudio/assets/1976582/187db291-800b-4a23-890f-4931fde5219b">

_Originally posted by @kevinushey in https://github.com/rstudio/rstudio/issues/13532#issuecomment-1692150085_

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 2023.09.0-daily+381 on MacOS 14
- RStudio Server 2023.09.0-daily+381 on Ubuntu 20.04.6 via Chrome on MacOS 14

Here are some representative examples:


![Image](https://github.com/rstudio/rstudio/assets/31009952/17f763cd-6b13-483a-ae12-4f67528c9251)



![Image](https://github.com/rstudio/rstudio/assets/31009952/badd2444-c30e-421d-bf8e-2f5aefe65e13)



![Image](https://github.com/rstudio/rstudio/assets/31009952/b504b65f-4605-4545-b2eb-366309eec179)


Note that there's an issue with bold fonts, but I'll file that separately.
