### ISSUE TITLE
Handle column names in joins based on the newer `dplyr` syntax

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13569]
For autocomplete, expand how we handle column names in joins to match the newer `dplyr` syntax. For more context, this is from https://github.com/rstudio/rstudio/issues/13415#issuecomment-1688583754.

**Comment by olivroy** [comment]
It would be cool if an indicator of which columns are in both x and y be shown too. Theoretically, you can always have 
`left_join(x, y, by = c(key.x = "key.y"))`, (that has to be supported for sure in a way)

but in most of my experience, the most likely scenario is that the key variable has the same name in both x and y, hence why the common columns should probably be shown first in autocompletion.  (similar for join_by), so I would put more focus in autocompleting this way.

this seems like a promising feature if I understand the intent correctly.

**Comment by olivroy** [comment]
I think this would be cool, although the scope may be too narrow. An approach similar to ggplot2 `aes()` completion could be used (#8444)

**Comment by jthomasmock** [comment]
Thanks @olivroy -- we have a few auto-complete items to work on in the future and will evaluate alongside them.
