### ISSUE TITLE
Administrator disabled Github Copilot?

### ISSUE THREAD

**Issue by JackLandry** [rstudio/rstudio#13563]
### System details

    RStudio Edition :  Desktop
    RStudio Version : Version 2023.09.0-daily+375 (2023.09.0-daily+375)
    OS Version      :  Ventura 13.2.1
    R Version       : R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"

### Steps to reproduce the problem

Not sure what to say besides installing the latest daily build with my setup.

### Describe the problem in detail

When going to global options to enable Github Copilot, I get the message that the administrator has disabled this option. It's my personal machine, and I had the copilot integration working with a previous daily build, so not sure what happened or how I would enable this option.

### Describe the behavior you expected

I expected to be able to set up Github Copilot from the global options menu

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cportner** [comment]
@JackLandry I had the same problem. It looks like a fix was just committed, but not sure when it will show up in the dailies. Until then, you can roll back to a prior daily. It looks like the bug was introduced in 373, so 369 should work.

**Comment by kevinushey** [comment]
Indeed; sorry for the trouble. A fix should be coming in the next daily builds, hopefully to be published tonight if all goes well.

**Comment by cportner** [comment]
[like]  Claus Portner reacted to your message:
________________________________

**Comment by ronblum** [comment]
Verified that out of the box, Copilot is on for RStudio Desktop but off for Server: https://github.com/rstudio/rstudio/issues/13527#issuecomment-1697615499
