### ISSUE TITLE
Copilot Integration Disabled by Administrator

### ISSUE THREAD

**Issue by UUronb** [rstudio/rstudio#13566]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 Build 375
    OS Version : 10.0.22621 Build 22621
    R Version : 4.3.1 (2023-06-16 ucrt) 

### Steps to reproduce the problem
New install of RStudio and R on PC
Attempt to activate copilot through tools -> global options -> copilot
Page displays "GitHub integration has been disabled by administrator"

### Describe the problem in detail
I installed the latest daily build over a previous release of R studio to get Copilot integration. This is a personal laptop and my account is set up as an administrator. I got the error so I uninstalled R Studio and R, reinstalled both and get the same error again. No way to give integration as an administrator or to enable Copilot as a user.

### Describe the behavior you expected
I should get options to enable Copilot.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by UUronb** [comment]
I'll also add that I tried to run R Studio as administrator and install as administrator but neither helped.

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be fixed up in the next daily builds; sorry for the trouble.
