### ISSUE TITLE
pandoc columns syntax interrupts header folding

### ISSUE THREAD

**Issue by henryrscharf** [rstudio/rstudio#13564]
Thanks in advance!

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1+524
    OS Version      : macOS Ventura 13.5 (22G74)
    R Version       : 4.3.1

### Steps to reproduce the problem
The following .Rmd syntax reproduces the problem. When saved as an .Rmd file and loaded into RStudio, there is no folding option for Slide with Bullets. If the ::::: column syntax is removed, the folding option returns.

```
---
title: "Example"
output: beamer_presentation
date: "2023-08-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```(note, extra apostrophes are added to make preview work better; see raw)
## R Markdown

:::::{.columns}
:::{.column width=50%}
This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
:::
:::{.column width=50%}
When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.
:::
:::::

## Slide with Bullets
``` 
(note, extra apostrophes are added to make preview work better)

### Describe the problem in detail

Using pandoc syntax for columns (I use it for pdf slides) as above interrupts the folding options normally offered by RStudio.

### Describe the behavior you expected

I believe the issue is clear and already illustrated above.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@henryrscharf Thank you for raising this! What I'm seeing is that I can fold `## Slide with Bullets` if the cursor is in that section, but if I go to the previous section, folding `## R Markdown` results in `## Slide with Bullets` getting folded into it. Is this what you're seeing?

https://github.com/rstudio/rstudio/assets/31009952/1c4c62ee-c87b-4df3-bf7e-0b4732eb44c4

**Comment by henryrscharf** [comment]
Yep, that's what I see. The keyboard shortcuts for folding seem to function analogously, too. I just noticed that in the following slightly longer example, the "normal" folding behavior seems to return a couple blocks after the column-based interruptions:

---
title: "Example"
output: beamer_presentation
date: "2023-08-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

:::::{.columns}
:::{.column width=50%}
This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
:::
:::{.column width=50%}
When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.
:::
:::::

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```
