### ISSUE TITLE
Green bar in Rmd-file showing besides text after deleting the code chunk which caused the green bar (after execution) to appear next to the output.

### ISSUE THREAD

**Issue by chris-alex-p** [rstudio/rstudio#13573]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.2 +561
    OS Version      :  Windows 11 Home Version22H2 (Build 22621.2134)
    R Version       :  4.3.1

### Steps to reproduce the problem

I myself don't know how to reproduce this "problem". Because sometimes the green bar shows up, other times it doesn't.

### Describe the problem in detail

With execution of an R code chunk in an Rmd-file within RStudio a green bar appeared left of the output (filtering a dataframe with filter()). When I delete the code chunk the green bar on the left is still there. 

Two code chunks show the left bar next to the output all others (ca. 10) don't. 

And something similar is happening if I press the Enter key right below the code chunk (in line 178). The green bar wanders down next to the text (empty line respectively).

### Describe the behavior you expected

I would expect there is always a green bar next to the output or never. And I would expect that the green bar disappears after deletion of the code chunk.

![Screenshot 2023-08-30 093732](https://github.com/rstudio/rstudio/assets/140163053/23ac3072-8c36-4883-b006-6ef410aa4869)

![Screenshot 2023-08-30 093902](https://github.com/rstudio/rstudio/assets/140163053/c0c32d80-0143-416c-889a-85c5e2733af5)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@chris-alex-p Thank you for raising this! Did this just start occurring with the latest release, or was it happening in earlier versions as well?

**Comment by chris-alex-p** [comment]
@ronblum This started occurring with the latest release. But actually I have not worked with RStudio und rmd-files for a longer while before that.

**Comment by ujtwr** [comment]
Is this relevant?

https://github.com/rstudio/rstudio/issues/12474
