### ISSUE TITLE
RMarkdown and Quarto lost the "Run Current Chunk" button

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13572]
### System details

    RStudio Edition : desktop
    RStudio Version : 2023.09.0-daily+380
    OS Version      : aarch64-apple-darwin20 macOS 13.5
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

On an older daily build (+360) and on the latest (+380) I am not seeing the "Run current chunk" button on chunks other than R/Python. I chatted w/ @ronblum briefly and he wasn't able to reprex, but I'm capturing in case others see this and we can try to diagnose a root cause.

Create chunks in RMarkdown or Quarto with a language other than R/Python.

````
```{r setup}
library(DBI)
# Create an ephemeral in-memory RSQLite database
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)
dbListTables(con)
```

```{r}
1 + 1
```

```{python}
1 + 1
```

```{sql connection=con}
SELECT *
```

```{bash}
which r
```

```{Rcpp}
int add(int x, int y, int z) {
  int sum = x + y + z;
  return sum;
}
```
````

Look for the "Run Current Chunk" button (it's not there)

Attempt to use the "Run all chunks below the current one" shortcut after the Python chunk and get the following error, which seems to treat the remaining chunks as R and merges them?

```r
> SELECT *
+ 
+ # Chunk 5
+ which r
#> Error: unexpected symbol in:
#>  "# Chunk 5
#>  which r"
```

### Describe the problem in detail

None of the non-R/Python chunks have a Run Current Chunk button:

![image](https://github.com/rstudio/rstudio/assets/29187501/cbaba8f6-30ca-4261-8c79-2ef88801e3fb)

Attempting to use the "Run all chunks below current one" short returns an error as all the code is run as R code in the console rather than by the specific engine.

### Describe the behavior you expected

The 2023.06 edition has Run Current Chunk button on all the above types:

![image](https://github.com/rstudio/rstudio/assets/29187501/ecdd4f17-e0fa-4067-a6ed-35a6588c06b1)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: This works for me with R 3.6.3, 4.2.3, and 4.3.1. Two differences: I'm using an Intel Mac running MacOS 14 (beta.0

**Comment by jthomasmock** [comment]
Per @kevinushey - this is likely due to the Chunk Output inline vs in console option:

![image](https://github.com/rstudio/rstudio/assets/29187501/96e87e87-783f-43e9-816f-6ad8680e4528)

We can provide the "expected" behavior with a Run button if the Chunk output is set to Inline as other languages are not evaluated purely by R but rather via `knitr`.

https://github.com/rstudio/rstudio/assets/29187501/4c76b3bf-d4d9-475b-9106-859726cefec2
