### ISSUE TITLE
Copilot: Ghost text stays when Copilot is turned off mid-suggestion

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13571]
### System details

    RStudio Edition : desktop
    RStudio Version : 2023.09.0-daily+380
    OS Version      : aarch64-apple-darwin20 macOS 13.5
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

Generate but do not accept Copilot ghost text and then turn off Github Copilot via Tools > Global Options > Copilot.

### Describe the problem in detail

There will be inserted Ghost text that you cannot get rid of.

![image](https://github.com/rstudio/rstudio/assets/29187501/acf5cc6b-8f8a-4555-ab3e-a6cd57e68816)

The ghost text will be removed if you close the current file.

### Describe the behavior you expected

Ghost text either goes away or can be Escaped to remove.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be fixed in the latest builds, but I don't have a specific commit / PR that resolved this issue.

**Comment by jthomasmock** [comment]
Interactive testing suggests this is fixed!
