### ISSUE TITLE
Manually hide and select columns in data viewer pane

### ISSUE THREAD

**Issue by tiredofmakingnewusernames** [rstudio/rstudio#13574]
Requesting a feature in Rstudio that allows you within the data viewer tab to do essentially what the "hide columns" functionality in Excel does. To be more precise, currently when you click on a dataframe that's loaded in your environment, it opens as a tab in the source pane where you can scroll up and down or even use the Filter (hourglass icon) button to filter your values. But it's not possible (that I know of) to hide columns or manually select just a few to display. You can change column width a bit, but that's it. I think the best solution would be something like a horizontal hourglass icon in the upper left corner of the tab. When you click on it all the column names appear and you can select/deselect by name, vector type, etc, essentially all the things you can do with dplyr::select, but point-and-click

**Comment by ronblum** [comment]
@tiredofmakingnewusernames Thank you for the suggestion! We'll review it as we continue development of RStudio.
