### ISSUE TITLE
copilot: mark as preview

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13570]
- [x] Make title in preferences pane have "(Preview)" or similar text to indicate it's a preview release.

**Comment by ronblum** [comment]
What about calling it "Experimental" which I think implies that things might change? We do that for user interface language (Tools -> Global Options -> Advanced).

*[Side note: Maybe it's time to take user interface language out of experimental.]*

**Comment by ronblum** [comment]
👍 

Possibly stating the obvious: The call to cation to open a GitHub issue will replace the Customer Success reference and email address? Since these are specific to Workbench and Desktop Pro.

**Comment by jthomasmock** [comment]
Yes, no need to go through Support/Sales/CS. If we wanted to include language, probably something like the below, but I'll defer to dev team.

> This feature is in preview. To provide feedback or report bugs, please open a [GitHub Issue on the RStudio repo](https://github.com/rstudio/rstudio/issues/new/choose).

**Comment by kevinushey** [comment]
For reference, we now include `(Preview)` in the header here.

<img width="641" alt="Screenshot 2023-09-05 at 3 23 03 PM" src="https://github.com/rstudio/rstudio/assets/1976582/1dad5936-149e-4722-b8b4-a645154159b9">

Perhaps we can also add the blurb in https://github.com/rstudio/rstudio/issues/13570#issuecomment-1699364315 to the panel footer, above the TOS blurb.

**Comment by jthomasmock** [comment]
One small nit, can we change the terms of service to: "By using GitHub Copilot, you agree to abide by THEIR terms of service."

@kevinushey do you want to include a call for explicit feedback?

> This feature is in preview. To provide feedback or report bugs, please open a [GitHub Issue on the RStudio repo](https://github.com/rstudio/rstudio/issues/new/choose).

Here's the language in docs so far:
> GitHub Copilot is available as an opt-in integration with RStudio. This feature is currently in Preview. Copilot support is expected to be generally available in RStudio desktop, RStudio server and Posit Workbench in a future release. To provide feedback or report bugs, please open a [GitHub Issue on the RStudio repo](https://github.com/rstudio/rstudio/issues).

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.09.0+440 on MacOS 14.

![Image](https://github.com/rstudio/rstudio/assets/31009952/36e4ec1c-be3c-4bea-8242-88c44fe2b56a)
