### ISSUE TITLE
Update RStudio dependencies

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13577]
Typically, with new releases, we try to stay relatively current on our dependencies.

This is also important as others will attempt to package RStudio themselves for different Linux distributions, and so typically build against the latest versions of dependencies (even if this is something we don't explicitly support).

## Compile-time Dependencies
- [x] Boost
- [x] CMake
- [x] Soci (already up-to-date)
- [x] yaml-cpp

## Runtime Dependencies
- [x] Node / npm
- [x] Electron

**Comment by petetronic** [comment]
See also https://github.com/rstudio/rstudio/issues/12424

**Comment by jgutman** [comment]
We also have the following ticket for updating Ace: #13592

**Comment by gtritchie** [comment]
Another one to consider is xterm (the terminal emulator); we're many, many years out of date on this. https://github.com/rstudio/rstudio/issues/9195

This is a non-trivial upgrade; a lot of the APIs have changed and some wiseguy used a lot of internal implementation details of xterm to work around limitations at the time and that needs to be unravelled and switched to official APIs when possible.

Seems like suitable punishment for me to do it, if I get the opportunity!

**Comment by ronblum** [comment]
Verified that Electron has been updated to 26.2.4 in RStudio Desktop 2023.09.1+470 and 2023.12.0-daily+131 on MacOS 14.

**Comment by petetronic** [comment]
Moving the remaining work to Chocolate Cosmos

**Comment by jgutman** [comment]
What is the remaining work here? I think the only things not done in Ocean Storm mentioned here were:
yaml-cpp upgrade (currently 0.6.3, latest available 0.8.0)
Upgrade to Node 18 (currently 16.20.2)
Upgrade to openssl 3 (tracked in #12855)
Upgrade xterm (tracked in #9195)

And I believe we determined we won't or couldn't do:
Upgrade to GWT 2.10.0 (tracked in #11505 - currently in the Later milestone)
Allow IDE to be built with JDK 17/18 (tracked in #11242 - currently in the Chocolate Cosmos milestone but I believe the latest update was that it may be intractable)

**Comment by gtritchie** [comment]
I haven't completely given up on building IDE GWT with JDK 17, but so far I've not been successful (the issue is all related to the Gin dependency injection framework, which uses the Java Guice framework at build time). The theory is if we upgrade the version of Guice to one that supports JDK 17 it _might_ work. But I couldn't get it to work at all with any version of Java.

**Comment by kevinushey** [comment]
Updated to yaml-cpp 0.8.0; I think this issue can be closed.

In the future, it'll probably be more straightforward to have separate issues for each dependency to be updated.
