### ISSUE TITLE
Preview on autocomplete menu of a Tibble with list-columns frezes RStudio

### ISSUE THREAD

**Issue by rpmeira** [rstudio/rstudio#13579]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.06.2+561 "Mountain Hydrangea"
    OS Version      : Window 10 22H2
    R Version       : 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"

### Steps to reproduce the problem
1) Create a relatively big tibble with list-columns, like the code below. 
2) Start typing the tibble's name so a pop-up menu for autocomplete will appear with a preview of the tibble's data.
3) RStudio frezes.
``` r
library(tibble)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df_size <- 1E4
data <- replicate(df_size, 1:df_size, simplify = FALSE)
names(data) <- make.unique(rep.int("V", df_size))
df <- as_tibble(data)
df_nest <- df %>% 
  mutate("X" = sample(c(LETTERS, letters), df_size, replace = TRUE)) %>% 
  group_nest(X)
```
![image](https://github.com/rstudio/rstudio/assets/64609486/b0f197c2-6c24-4fe3-b459-3b83cf099d01)

<sup>Created on 2023-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### Describe the problem in detail
RStudio frezes when the Preview appears on autocomplete menu of a Tibble with list-columns
### Describe the behavior you expected
RStudio not to freze (crash). 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Here's an R profile:

```
$by.total
                               total.time total.pct self.time self.pct
"FUN"                               44.28     99.95      9.84    22.21
".rs.formatDataColumn"              44.28     99.95      0.00     0.00
".rs.formatDataColumnDispatch"      44.28     99.95      0.00     0.00
".rs.tryCatch"                      44.28     99.95      0.00     0.00
"doTryCatch"                        44.28     99.95      0.00     0.00
"format.default"                    44.28     99.95      0.00     0.00
"formatter"                         44.28     99.95      0.00     0.00
"tryCatch"                          44.28     99.95      0.00     0.00
"tryCatchList"                      44.28     99.95      0.00     0.00
"tryCatchOne"                       44.28     99.95      0.00     0.00
"withCallingHandlers"               44.28     99.95      0.00     0.00
"lapply"                            34.44     77.74      0.00     0.00
"unlist"                            23.68     53.45     23.68    53.45
"prettyNum"                         10.76     24.29     10.76    24.29
"vapply"                             9.84     22.21      0.00     0.00
"tolower"                            0.02      0.05      0.02     0.05
".rs.fuzzyMatches"                   0.02      0.05      0.00     0.00
".rs.getCompletionsSearchPath"       0.02      0.05      0.00     0.00
".rs.rpc.get_completions"            0.02      0.05      0.00     0.00
".rs.startsWith"                     0.02      0.05      0.00     0.00
"nchar"                              0.02      0.05      0.00     0.00
"Reduce"                             0.02      0.05      0.00     0.00
```

**Comment by kevinushey** [comment]
The problem here is caused by the format method for the `vctrs_list_of` object, which RStudio tries to use when formatting the dataset. Unfortunately, this is very slow for such objects.

```
> system.time(format(df_nest$data))
   user  system elapsed 
 24.801   0.668  25.557 
```

I'm not exactly sure what the most appropriate fix here is. Maybe we should just disable the inline preview for datasets containing list-columns?

**Comment by rpmeira** [comment]
Any news on this?

@kevinushey, having the option to disable this feature would be great.

**Comment by kevinushey** [comment]
No news yet, but we do intend to look at this for the upcoming release.

**Comment by wbvguo** [comment]
I experienced a similar issue with Rstudio-server (version `2023.09.0+463 (Desert Sunflower) for Ubuntu Focal`) when using Rmarkdown; the dataset preview option seems to slow down the interface's response, causing a delay in typing and code execution

**Comment by kevinushey** [comment]
For Ocean Storm, we should at least include a UI preference that allows users to disable this inline preview.

**Comment by rpmeira** [comment]
> For Ocean Storm, we should at least include a UI preference that allows users to disable this inline preview.

That would help a lot. Thank you!

**Comment by kevinushey** [comment]
It will be possible to disable the display of these data previews in the upcoming daily builds -- please see https://github.com/rstudio/rstudio/pull/13902 for more details if necessary.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+306](https://dailies.rstudio.com/version/2023.12.0-daily+306)
Windows 11

Added option to Global Config -> Code -> Completion hides the preview of the datasets.. effectively mitigating the issue for now.
