### ISSUE TITLE
`NA` in tibble is displayed as `NANA` with View()

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#13585]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-05) for Ubuntu Focal Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.1+524 Chrome/110.0.5481.208  Electron/23.3.0 Safari/537.362023.06.1 Build 524
    OS Version: Archlinux
    R Version: 4.3.1

### Steps to reproduce the problem

```
tbl <-
structure(
  list(x = list(NA_character_)),
  row.names = c(NA,
                -1L),
  class = c("tbl_df", "tbl", "data.frame")
)
View(tbl)
```

![snap](https://github.com/rstudio/rstudio/assets/19862384/7bf97bd9-6a82-472a-8c42-168724572056)

### Describe the problem in detail

`NA` in tibble is displayed as `NANA` with View()

### Describe the behavior you expected

I expected the value `NA` in the tibble to be displayed as `NA` with View()

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Verified with [2023.09.0-daily+410](https://dailies.rstudio.com/version/2023.09.0-daily+410)
Windows11, Ubuntu 22.04

`NA` appears correctly in data view. All dataviewer automated tests passed.
