### ISSUE TITLE
copilot: allow project-specific options

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13580]
Since users might want to enable (or disable) Copilot on a project-specific basis.

**Comment by kevinushey** [comment]
For testing, the most important point to verify is that the project-specific options should override the default global options.

If Copilot is disabled for a project, then you should see the following blurb in the Copilot global options making that more clear:

<img width="645" alt="Screenshot 2023-09-13 at 3 05 02 PM" src="https://github.com/rstudio/rstudio/assets/1976582/60ee4818-b636-4d81-a48a-66d5fde8b763">

**Comment by ronblum** [comment]
Checked in RStudio Desktop 2023.09.0+440 on MaOS 13.

- Enable is working correctly, for combinations of enabled and disabled in each.
- Indexing works in most combinations. However, if it's off for the project and on globally, ghost text from other files appears.

**Comment by ronblum** [comment]
QA note: Make sure that files are closed before testing indexing states—otherwise, Copilot will make suggestions based on them.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.09.0+445 on MacOS 14.
