### ISSUE TITLE
partial matching in groupByCompletions

### ISSUE THREAD

**Issue by TimTaylor** [rstudio/rstudio#13595]
Can `package =` be changed to `packages =`  in https://github.com/rstudio/rstudio/blob/c128dd7c4b72c11cb467ba47625dd424a6822f53/src/cpp/session/modules/SessionRCompletions.R#L1001. Currently it can make the session a little noisy if you have warnings for partial matchings turned on.

**Comment by ronblum** [comment]
@TimTaylor Thank you for the suggestion! We'll review it as we continue development of RStudio.
