### ISSUE TITLE
Sync Ace keyboard accessibility flag with the IDE flag

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13593]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2023.09.0-daily+397
    OS Version      : any
    R Version       : any

Ace 1.17 and newer have the `enableKeyboardAccessibility` flag controlling various aspects of keyboard and screen reader behaviour.

We should understand what, exactly, this flag does, and (most likely) keep it in sync with the existing RStudio `enableScreenReader` setting. As part of this, we'll want to conduct testing with the major screen readers and browsers and ultimately update our VPAT documentation.

See also #13592; if we update to a newer Ace (currently at 1.19) there are additional things controlled by this flag.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
Verified on [2023.12.0-daily+237](https://dailies.rstudio.com/version/2023.12.0-daily+237)
windows 11

Screen reader behaves as expected
