### ISSUE TITLE
Autocomplete not showing first argument in functions inside mutate / select (nested calls)

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#13607]
**Note: Solving #13611  seems to solve this issue. Please consider this one instead.** 

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.9.0.401 (and 2023.06)
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.3.1 (2023-06-16 ucrt)

### Steps to reproduce the problem

1. load dplyr
2. write the following code
```r
mtcars |> 
  mutate(
    x = mean()
  )
```
3. Press tab (or wait for autocomplete) ( inside mean)

### Describe the problem in detail

The autocompletion shown is off by one. There is a delay and the autocompletion misinterpretes the pipe.
![image](https://github.com/rstudio/rstudio/assets/52606734/b1d9aae5-2e69-46d6-a168-754eef83138e)

### Describe the behavior you expected

When trying to create a new variable, autocomplete seems to think that the piped data is the first argument.

I expect the same behavior to happen, regardless of the context. 
Currently, autocomplete inside `mutate()`, `select()`, filter()`, etc. works only correctly when there is an empty file with a blank line.

Anything after that doesn't work as expected.

I would expect `x` to show up. Like when I use autocomplete for mean outside mutate.

![image](https://github.com/rstudio/rstudio/assets/52606734/3fe1ed52-13d4-460e-ba07-af00b65ab683)

The correct behaviour is there with the following code
```r
x <- c(1, 2)
x |> mean()
```
![image](https://github.com/rstudio/rstudio/assets/52606734/8d1104cc-79e7-4be1-91c0-af80e9cf09cb)

It seems that the autocomplete thinks that `mean()` should be autocompleted with mtcars.

This seems to be only the case for S3 methods..

I don't see any issues with `sum()` for example, but see them with `dplyr::lag()`

I reported it originally in https://github.com/rstudio/rstudio/issues/13065#issuecomment-1682983674

But I wanted to try a daily version before reporting formally.

thank you so much for RStudio.

Edit: I found this old SO post https://stackoverflow.com/questions/36205848/in-rstudios-auto-complete-how-to-show-the-first-argument-of-a-function-when-us

It shows that it didn't work in 2016, but worked in 2018.
FWIW, a video trying to explain how to circumvent this issue. https://www.youtube.com/watch?v=UvHFLyBvAag

**Comment by olivroy** [comment]
This is especially problematic for functions that have only 2 arguments.
If I use `dplyr::na_if()`

1. Trigering autocomplete inside call.
![image](https://github.com/rstudio/rstudio/assets/52606734/a8e41454-17fa-419c-9a74-8ab8ac7c5095)

2. After inserting the first argument,  there is no more `na_if()` completion.
![image](https://github.com/rstudio/rstudio/assets/52606734/35e1ce51-387b-4be5-a1dc-91bc25ec2cf9)

**Comment by olivroy** [comment]
@ronblum thank you so much for researching this. I have done a fair bit of research on my part to try to understand the history, but you unveiled some very interesting things!

I know I am annoying, but I think that this is for the greater good of beginner R users, as this can be confusing and unexpected.

**Comment by ronblum** [comment]
@olivroy Not annoying at all! Any bug is important and every feature request is welcome. What we prioritize and address, there's no guarantee, but we appreciate all issue reports. 😃

**Comment by olivroy** [comment]
As @ronblum noted in #13069 
it seems that the correct behavior shows up if there is only one blank line above 

![image](https://github.com/rstudio/rstudio/assets/52606734/7d31d1dc-ab97-42a8-ba4d-1fbb7da1f829)

Generally, if there is only a blank line, the behavior is exactly as expected, while there are some things that do not work as expected in other contexts.

**Comment by ronblum** [comment]
Closing in favor of #13611.
