### ISSUE TITLE
Evaluate adding "Publish" next to the blue publish icon

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13604]
The little blue publish button <img src='https://github.com/rstudio/rstudio/assets/29187501/064da742-2b54-48ca-8bc8-378fababb754' width=25> is less descriptive than we'd like it to be per some internal feedback.

We may want to evaluate the Publish button gaining text (similar to the `Render` button). I've modified RStudio in devtools to inject the text as seen below as a potential mockup.

![image](https://github.com/rstudio/rstudio/assets/29187501/627c1b99-84b4-4332-81d0-083292b0ad7a)

**Comment by kevinushey** [comment]
This seems like a good idea to me as well.

**Comment by jthomasmock** [comment]
The current "shrink" behavior appears to respect the new text quite well:


https://github.com/rstudio/rstudio/assets/29187501/c57a46c3-cea1-4eaa-8839-0966b02fb95f

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+80.pro1 on Windows 11 that the button now says "Publish" in the Editor Pane, Viewer Pane, and Preview Window.
