### ISSUE TITLE
Github Copilot disabled "by administrator"

### ISSUE THREAD

**Issue by vmorozov** [rstudio/rstudio#13612]
### System details

    RStudio Edition : server
    RStudio Version :  rstudio-server-2023.09.0-daily-410-amd64
    OS Version      :  Ubuntu 20
    R Version       : 4.3.1

### Steps to reproduce the problem
Tools -> Global Options -> Copilot -> Enable Github Copilot
### Describe the problem in detail
<img width="545" alt="Screenshot 2023-09-08 124019" src="https://github.com/rstudio/rstudio/assets/542092/6f1bba05-abc3-464a-99d9-3e53555d99b8">

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by vmorozov** [comment]
The Rsudio sever is installed on WSL2 with sudo. here is the installation log:
sudo gdebi rstudio-server-2023.09.0-daily-410-amd64.deb 
[sudo] password for vlad: 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

RStudio Server
 RStudio is an integrated development environment (IDE) designed to support multiple languages, including both R and Python. It includes a console, syntax-highlighting editor that supports direct code execution, and a variety of robust tools for plotting, viewing history, debugging and managing your workspace.
Do you want to install the software package? [y/N]:y
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
(Reading database ... 72015 files and directories currently installed.)
Preparing to unpack rstudio-server-2023.09.0-daily-410-amd64.deb ...
Unpacking rstudio-server (2023.09.0-daily+410) over (2023.06.1+524) ...
Couldn't find an alternative telinit implementation to spawn.
Setting up rstudio-server (2023.09.0-daily+410) ...
useradd: user 'rstudio-server' already exists
Couldn't find an alternative telinit implementation to spawn.
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/var/log/rstudio/rstudio-server/rserver.log'.
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/var/log/rstudio/rstudio-server/rserver.log'.

**Comment by ronblum** [comment]
@vmorozov This is intentional—the RStudio Server integration with Copilot integration hasn't been tested for this release, so the preview is currently only available in RStudio Desktop. I would recommend exploring it with RStudio Desktop. However, if you'd like to enable it in the server, you can set `copilot-enabled=1` in `rsession.conf`, but proceed with caution.
