### ISSUE TITLE
Enable Search breadcrumbs for guides

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#13618]
Search within the guides is sometimes confusing because it isn't apparent where/what section the search results reside in. 
A recent request was submitted to the quarto team to enable breadcrumbs in search results so users can easily identify the source of the search results.

Original request and conversation is here: https://positpbc.slack.com/archives/C01LQETLA7L/p1694042877728539

Per Charles:
>The next build of Quarto will include the ability to show search context in search results (from either Fuse or Algolia search indexes). By default this isn’t enabled, but you can enable it with:
search: `show-item-context: true`
Which will show a ‘crumbs’ trail below the document title.
You may also pass any of these values to control what is displayed:
     
    ```
    tree - display a crumb path below the document title

    root - display the title of the root page which contains this item          (to the side)

    parent - display the title of the parent of this item (to the side)
    ```

This is ready to use in Quarto 1.4.354, available now (and enabled for [quarto.org](http://quarto.org/) search as well).

Related Issue: https://github.com/rstudio/rstudio-pro/issues/5088
```[tasklist]
### Tasks
- [x] IDE User Guide
- [x] N/A: News
```

**Comment by melissa-barca** [comment]
Moving to Ocean Storm as our Desert Storm docs will build with Quarto 1.3 and not 1.4

**Comment by jonvanausdeln** [comment]
This feature isn't available until Quarto 1.4, which won't release until after Ocean Storm.. so I'm moving this to Chocolate Cosmos.  I did check the OS docs and they don't have it enabled yet.

**Comment by AshleyHenry15** [comment]
Closing in favor of: https://github.com/rstudio/rstudio/issues/14069

**Comment by petetronic** [comment]
Confirming breadcrumbs now show in daily IDE User Guide
https://docs.posit.co/ide/user/2024.04.0/

**Comment by ronblum** [comment]
Example of breadcrumbs when searching for `dplyr` in revision 30:


![Image](https://github.com/rstudio/rstudio/assets/31009952/da4cd569-66ac-4754-b119-50d4a77e9a12)
