### ISSUE TITLE
Copilot on recent daily builds is disabled?

### ISSUE THREAD

**Issue by alanpaulkwan** [rstudio/rstudio#13617]
I checked and don't think it's a duplicate but apologize if it is or I just did something dumb. I've tried build 410, 414, 397 on Rstudio Server, but when I'm inside of Rstudio Server it says Administrator has disabled Copilot. Going back to 332 it works. Is it a feature or a bug that it's disabled?

I don't think it matters, but I'm inside an Ubuntu 22 vm

<img width="626" alt="image" src="https://github.com/rstudio/rstudio/assets/8321252/fc4f2410-4db2-4bf1-8963-a1d798164239">

**Comment by kevinushey** [comment]
This is intentional for RStudio Server / Workbench installations; you'll need to set `copilot-enabled=1` in your `/etc/rstudio/rsession.conf` file.
