### ISSUE TITLE
Data viewer sometimes shows up blank

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13624]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.2+561.pro5
    OS Version      : MacOS 12.6.8 and 13.5.2 
    R Version       : 4.3.1

### Steps to reproduce the problem

*Cribbed from https://community.rstudio.com/t/view-shows-blank-pane-in-rstudio-desktop-pro-2023-06-2*

In RStudio:
```
x<-data.frame(x=runif(50))
View(x)
```

Sometimes a blank pane appears, showing no data. The same thing happens when clicking on the `x` object in the environment pane.

### Describe the problem in detail

The data viewer shows up as blank in some cases.

### Describe the behavior you expected

The data viewer should always return the data.

Triage: Recommended for Desert Sunflower.

A couple of ways of getting this to work.
- Reinstalling RStudio (not consistent).
- Running the following on the command line (not in RStuio) provided in [the Community post](https://community.rstudio.com/t/view-shows-blank-pane-in-rstudio-desktop-pro-2023-06-2/173187/5?u=rblum):
```
sed -i.bak 's/?? /== undefined ? maxRows : parsedLocation./'  /Applications/RStudio.app/Contents/Resources/resources/grid/dtviewer.js
```
Note: This workaround is *not recommended*. It's provided here for reference, to help diagnose the issue

See also Support ticket 95016.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note; I suspect this only reproduces in the older (QtWebEngine-based) Pro builds.

**Comment by ronblum** [comment]
Note: I haven't been able to reproduce this, in recent and older versions of the open source and pro builds. (So I also didn't try the workaround.)

**Comment by ronblum** [comment]
Asked in the Community post if someone can try this out, since I can't reproduce the problem and so I can't verify it.

**Comment by ronblum** [comment]
Closing, but if anyone runs into this issue, please let us know!

**Comment by ronblum** [comment]
RStudio 2023.09.0+463 Desert Sunflower is now [live as the official release](https://posit.co/downloads/). If you install it, please let us know whether or not this is working. Thanks!
