### ISSUE TITLE
update rstudio.com URLs

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13626]
We still have a lot of references to `rstudio.com` used throughout the RStudio codebase. Should we consider updating all of these to `posit.co` as appropriate?

**Comment by kevinushey** [comment]
I think we can bump this to Ocean Storm, unless we feel there's certain URL links that absolutely need to be updated for this release?

**Comment by jthomasmock** [comment]
> We still have a lot of references to `rstudio.com` used throughout the RStudio codebase. Should we consider updating all of these to `posit.co` as appropriate?

We definitely should update these but it can be pushed to Ocean Storm if needed. For some of the links, they are referencing old support articles that are now reflected in https://docs.posit.co/ide/user/

**Comment by jgutman** [comment]
Some URLs that cannot/should not be updated as of yet: community.rstudio.com (not yet migrated), cran.rstudio.com
