### ISSUE TITLE
Inconsistent indentation after binary operator inside `if` condition and function call in R

### ISSUE THREAD

**Issue by bartekch** [rstudio/rstudio#13628]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0.14, but also checked on 2023.6.2.561
    OS Version      : Windows 11 Pro
    R Version       : 4.1.0

### Steps to reproduce the problem

Open new R script.
Enable `Vertically align arguments indent` option.
Type the following examples.

```r
rstudioapi::writeRStudioPreference("vertically_align_arguments_indent", TRUE)

# 1a
if (
  cond_a ||
  cond_b
) {}

# 2a
foo(
  cond_a ||
    cond_b
)

# 3a
if (cond_a ||
    cond_b) {}


# 4a
foo(cond_a ||
      cond_b)
```

For comparison type the same examples with the option disabled.

```r
rstudioapi::writeRStudioPreference("vertically_align_arguments_indent", FALSE)

# 1b
if (
  cond_a ||
    cond_b
) {}

# 2b
foo(
  cond_a ||
    cond_b
)

# 3b
if (cond_a ||
    cond_b) {}


# 4b
foo(cond_a ||
    cond_b)
```

### Describe the problem in detail

Sometimes there is an extra indent inserted in new line after `||`, and sometimes not.

Extra indent: 2a, 4a, 1b, 2b
No extra indent: 1a, 3a, 3b, 4b

In particular behaviour differs between examples 1a and 2a, and respectively between 3a and 4a, although they seem to be similar cases.

In comparison, when `vertically_align_arguments_indent` is disabled, the behaviour is the same for similar cases (1b-2b and 3b-4b), although it differs between those pairs.

Examples use `||` operator, but I checked also `+` and it behaves the same. I guesss it applies to other operators (logical and math) as well.

### Describe the behavior you expected

To be honest I'm not entirely sure what outcome would be the best. I would say that indentation should behave at least the same in pairs 1a-2a and 3a-4a, but what version exactly should be used I don't know.

Considering that the following two examples have an extra indent, and look the same no matter `vertically_align_arguments_indent` setting, I'd probably lean towards an extra indent option (like in 2a and 4a) in all cases.
```r
cond_a ||
  cond_b

{
  cond_a ||
    cond_b
}
```

To make matters more complicated if we call `styler` on all examples (with `tidyverse_style`, only 2a, 1b, 2b stays untouched - related to https://github.com/tidyverse/style/issues/197. All styled examples below.
```r
# 1a
if (
  cond_a ||
    cond_b
) {}

# 2a
foo(
  cond_a ||
    cond_b
)

# 3a
if (cond_a ||
  cond_b) {}


# 4a
foo(cond_a ||
  cond_b)




# 1b
if (
  cond_a ||
    cond_b
) {}

# 2b
foo(
  cond_a ||
    cond_b
)

# 3b
if (cond_a ||
  cond_b) {}


# 4b
foo(cond_a ||
  cond_b)
```

I guess it's best to avoid such code structure at all, nevertheless sometimes it may be quite convenient.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bartekch Thank you for raising the issue! I can reproduce it in RStudio Desktop 2022.07.2+576 and 2023.09.0+440. We'll review this as we continue development of RStudio.

**Comment by kevinushey** [comment]
This comes from this bit of code:

https://github.com/rstudio/rstudio/blob/1fb8c970fb212301ce2e91834f2b68deb7827169/src/gwt/acesupport/acemode/r_code_model.js#L1793-L1811

with the intention being that vertical alignment within multiline conditionals might be preferred to the regular indentation behavior.
