### ISSUE TITLE
Copilot: don't store project preferences in .Rproj file

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13635]
Right now, Copilot project settings are serialized to the project `.Rproj` file. This has two big consequences:

1. It forces all users of the project to opt-in to the same Copilot project preferences,
2. The changes become visible in version control.

However, because different users working on the same project could potentially want to have differing Copilot project preferences here, I think we need to change this to instead store these within the `.Rproj.user` folder.

**Comment by ronblum** [comment]
Verified that data is stored, but no longer in `.Rproj`, in RStudio Desktop 2023.09.0+445 on MacOS 14.
