### ISSUE TITLE
knitr chunk option `file` is not respected by interactive rendering

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#13636]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.12.0.14
    OS Version      : Windows 11 x64 (build 22621)
    R Version       : R version 4.3.1 (2023-06-16 ucrt)

### Steps to reproduce the problem

* Write the Rmd below using a `file` chunk option to load content of external file  (https://bookdown.org/yihui/rmarkdown-cookbook/option-code.html)

````markdown
---
title: "my project"
output: html_document
---

```{r}
xfun::write_utf8("library(glue)", "setup.R")
```

```{r, file = "setup.R"}
```

```{r}
glue("1 + 1 = {1 + 1}")
```

```{r}
unlink("setup.R")
```
````

* Knit the document => this is working fine
* Use Run All for interactive rendering and the chunk with **glue** will error as `library(glue)` as not be called because `setup.R` not be inserted in chunk. 

cc @topepo

### Describe the problem in detail

RStudio IDE does not know probably how to handle this chunk option, neither in R Markdown or in Quarto (using the in-chunk YAML syntax). 

Probably related to other issues where some **knitr** option are not known or handled correctly when running chunks interactively. 

### Describe the behavior you expected

The same behavior as in rendering where 
* `file` option is seen 
* R file are source as chunk content
* No error in rendering

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+84 on MacOS 14 using the original example.
