### ISSUE TITLE
"Ignore Update" option does not work in "Update Available" dialog

### ISSUE THREAD

**Issue by ms609** [rstudio/rstudio#13640]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0+421
    OS Version      : Win 10
    R Version       : 4.4.0

### Steps to reproduce the problem

Select "Ignore Update" from the "Update Available" dialogue

![image](https://github.com/rstudio/rstudio/assets/1695515/721bf9f1-8e4d-4524-9920-c8e12a1a8cb6)

### Describe the problem in detail

Each time I launch RStudio (or switch projects) I am prompted to update

### Describe the behavior you expected

The "Update Available" dialog should not be shown again until a newer update is available, if "Ignore update" is selected.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [Not possible] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [-] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ms609 Thanks for the bug report! This was previously reported and fixed, covered in issue #13379. It's fixed in [the current release, 2023.06.2+561.](https://posit.co/download/rstudio-desktop/)
