### ISSUE TITLE
Cmd-Z then Cmd-Shift-Z enters code at the bottom of page (wrong place)

### ISSUE THREAD

**Issue by mcsimenc** [rstudio/rstudio#13652]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.06.2+561 (2023.06.2+561)
    OS Version      :  MacOS Monterey v12.0.1 
    R Version       :  4.3.1 (2023-06-16)

Write code in file editing section. Undo with Cmd-Z. Redo with Cmd-Shift-Z.

This problem doesn't occur every time.

After updating RStudio I also noticed that when running `shiny` applications from RStudio and then Cmd-Z it first highlights the entire text and the view goes to the bottom of the file.

The expected behavior is to redo the actions exactly as they were before undoing, but Cmd-Shift-Z sometimes puts code at the bottom of the page.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mcsimenc Thank you for raising this! I'm unable to reproduce this, though. What file types are affected—only R files, or R Markdown, Quarto, etc.? Also, if R Markdown or Quarto, is this in the visual editor, source mode, or both?

**Comment by mcsimenc** [comment]
Hi Ron, thanks for your reply. I have been unable to reproduce it since updating RStudio.
