### ISSUE TITLE
Popup or detachable panels do not load

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#13657]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.09.0 Build 446 for arm64
    OS Version      : Ubuntu Server 22.04 LTS for arm64
    R Version       : 4.3.1

### Steps to reproduce the problem
On a git enabled project open the Diff panel or detach any panel from the original browser window for the session.

### Describe the problem in detail
The popup or detachable panel stays loading forever
![image](https://github.com/rstudio/rstudio/assets/14981085/bd0b2e49-2a4a-4b77-afe0-0b5d4e6ea07a)

### Describe the behavior you expected
I expect to see the panel loaded like with the stable RStudio Server version (2023.06.2 Build 561 for x86_64)
![image](https://github.com/rstudio/rstudio/assets/14981085/9636d1e3-63ae-4d3f-a8bb-e63125066d06)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2023.09.0+448 on Debian 12
- RStudio Desktop 2023.09.0+448 on MacOS 14
- RStudio Desktop 2023.09.0+448 on Windows 10
- RStudio Server 2023.09.0+448 on Ubuntu 20 via Chrome on MacOS 14

Tested with Git Diff pane and rendering an R Markdown file with preview in a window.

**Comment by andresrcs** [comment]
The fix is confirmed, thanks!
