### ISSUE TITLE
Copy Paste does not work, in the find in files dialogue box

### ISSUE THREAD

**Issue by gunawebs** [rstudio/rstudio#13658]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 2023.06.2+561 (2023.06.2+561)
    OS Version      :  Mac OS 11.6.1
    R Version       :  R version 4.1.1 (2021-08-10) -- "Kick Things"

### Steps to reproduce the problem
1. open rstudio
2. open any project of yours
3. copy any text using cmd c (or mouse)
4. open the menu item from rstudio: edit > find in files
5. try and paste the copied text
6.  It would not paste via Cmd V. Hence cannot search
7. If you paste via the mouse, then the Find box is disabled. Hence cannot search

### Describe the problem in detail
1. open rstudio
2. open any project of yours
3. copy any text using cmd c (or mouse)
4. open the menu item from rstudio: edit > find in files
5. try and paste the copied text
6.  It would not paste via Cmd V. Hence cannot search
7. If you paste via the mouse, then the Find box is disabled. Hence cannot search

### Describe the behavior you expected
One should be able to copy paste a string into the find in files, dialogue box
I can swear that it used to work in earlier versions

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gunawebs Thanks for raising this! I can reproduce this issue in the same release, as well. I've also verified that this is now working in RStudio Desktop 2023.09.0+445.

Note: Cf #13365.

**Comment by gunawebs** [comment]
Thanks. But I presume that is not an official release yet

**Comment by kevinushey** [comment]
We're in the process of preparing the next release; hopefully to be published in the coming weeks.

**Comment by gunawebs** [comment]
Perfect, Thanks!

**Comment by gunawebs** [comment]
I confirm that this has been fixed in the latest production release: Version 2023.09.0+463 (2023.09.0+463)

**Comment by ronblum** [comment]
@gunawebs Thank for checking!
