### ISSUE TITLE
Underscores in file names evoke underlining in Tools > Version Control

### ISSUE THREAD

**Issue by fkohrt** [rstudio/rstudio#13662]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.06.2+561
    OS Version      : Fedora 38
    R Version       : 4.3.1

### Steps to reproduce the problem

Open a project in a Git versioned directory, add a file that has underscores in its name and open that file. Go to Tools > Version Control and notice how the underscores in the file names are gone, but instead the following letters are underlined.

### Describe the problem in detail

This a screenshot for the file `This_is_a_test.R`.

![Screenshot from 2023-09-20 11-24-34](https://github.com/rstudio/rstudio/assets/12914806/070f4333-607a-49ea-8510-425c56a7fbeb)

### Describe the behavior you expected

The underscores retained and not underlined parts of the filename.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fkohrt Thank you for raising this! We'll consider it  as we continue development of RStudio.

I can reproduce the missing underscores (but not the underlining) in 
- RStudio Desktop 1.4.1743 on MacOS 14
- RStudio Server 2023.09.0+445 on Ubuntu 20.04.6

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+84 on MacOS 14 using an R file in a Git projec.
