### ISSUE TITLE
Copilot: Only enable project indexer when Copilot itself is enabled

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#13667]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0+401
    OS Version      :  Windows
    R Version       : 4.3.1

### Steps to reproduce the problem

1, Open RStudio project on Network drive (windows)
2. Use setwd() for another place in the network drive. (I use forward slashes to specify the path, and RStudio + `normalizePath()` complain.

### Describe the problem in detail

I get a warning. 

```
Warning message:
File monitoring failed for project at `NW_DRIVE_LOCATION`
Error 2 (Cannot find the specified file) 
Features disabled: R source file indexing, Diagnostics, Copilot indexing
```

This is not bothering me at all. (I am opening the issue more as a heads-up for you).
 So feel free to close if this has been fixed or can't reproduce.

But I never activated Copilot (which is why I think this warning may show up for Windows users that they will not understand once the release is complete.

### Describe the behavior you expected

No warnings. Especially not ones regarding Copilot, when I never used it.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

If you can't reproduce easily, I will close.

Thank you so much for RStudio.

**Comment by ronblum** [comment]
Thanks @olivroy ! A few things:
1) Are you able to open, edit, and save files after doing the above?
2) Can you include the commands that you use for `setwd()` and `normalizePath()`? Scrubbed is fine, but please include the slashes so that I can try to reproduce exactly.
3) Is this still an issue if you use a mapped drive?
4) What version of Windows are you using?

@kevinushey Note Copilot message even though Copilot wasn't enabled.

**Comment by olivroy** [comment]
> 1. Are you able to open, edit, and save files after doing the above?

Yes, things work. I only have this warning that shows up.

> 2. Can you include the commands that you use for `setwd()` and `normalizePath()`? Scrubbed is fine, but please include the slashes so that I can try to reproduce exactly.

The `setwd()` part was irrelevant, sorry.

It is possibly due to the fact, that since` normalizePath()` thinks that my path does not exist (forward slash vs backslash)
 (since I am using forward slashes or fs paths.

> 3. Is this still an issue if you use a mapped drive?

I have not checked on a mapped drive. But it is for a path that starts with "//"

> 4. What version of Windows are you using?

Windows 10, 21H2.


I get warnings like 
```r

Warnings:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="\\SFPHQOKLEASE1": Invalid path

Warning message:
File monitoring failed for project at "//path"
Error 2 (Le fichier spécifié est introuvable)
Features disabled: R source file indexing, Diagnostics, Copilot indexing
```
See how the base R warnings show the `\\` and the copilot warnings show `//`.

**Comment by olivroy** [comment]
Hi, it didn't occur today. It happened yesterday on session restart also if that helps. After setting a wd (with forward slash) outside of the Rproj (while having codes under Rproj.

Since RStudio seems to remember the wd when using Restart R session, that may be why. But if you still cannot reproduce, I will close this.

**Comment by olivroy** [comment]
Thanks! For now, glad you were not able to reproduce!

**Comment by olivroy** [comment]
Maybe from a project on a nw drive. use 
```r
usethis::create_project("//a/nw/path/test-proj")
```
Maybe this will trigger the warning on your side?

**Comment by kevinushey** [comment]
It would be easy enough to ensure the Copilot-related indexing only activated if indexing is actually enabled.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/blob/db7716e93adc5242e1c60a09a43511fd5e5d70f4/src/cpp/session/modules/SessionCopilot.cpp#L1143

**Comment by ronblum** [comment]
@olivroy Do the problems go away with the changes that @kevinushey made? You'd have to install a development version of [RStudio Desktop 2023.12](http://dailies.rstudio.com), so if you do so, please keep in mind that it's for testing purposes only.

**Comment by olivroy** [comment]
Haven't seen this warning in a while (I try to avoid working on network drive as much as possible) The fix looks robust. Since no one else reported this, I think it's safe to close.

Thanks!
