### ISSUE TITLE
Cannot scroll in autocomplete help dialog, click immediately closes it and cursor focus unknown

### ISSUE THREAD

**Issue by BdR76** [rstudio/rstudio#13674]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1 Build 524
    OS Version      :  Windows
    R Version       : 4.3.1

### Steps to reproduce the problem

1. Start a new R script
2. Include the dplyr library (or any library with function and help)
3. Type for example `dplyr::`
4. Press ctrl+space to trigger auto completion
5. Scroll to any function with a yellow help dialog
6. Click in the yellow help dialog

![rstudio_autocomplete_help_dialog](https://github.com/rstudio/rstudio/assets/7793956/bb045cad-e1f5-4e77-b799-cd2254a04a4b)

### Describe the problem in detail

The help dialog display with a scrollbar but clicking it will instantly close the dialog, so you cannot see the entire help text.
Also when clicking in any helpdialog it closes and the focus of the cursor is somewhere outside the code editor (on an invisible widget maybe?). Not a showstopping issue, but weird enough to submit as issue I thought.

### Describe the behavior you expected

I would expect to be able to click the help dialog to scroll down in the help text

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by BdR76** [comment]
Could be related to #13526 maybe?

**Comment by ronblum** [comment]
@BdR76 Thank you for raising this! It looks like this bug's been around for a while: Testing on MacOS 14, it last worked in 2021.09.3 and started failing in 2022.02.3. I'll mark it for review.

**Comment by ronblum** [comment]
Verified fixed in RStudio Desktop 2023.12.0-daily+131 on MacOS 14 using the steps outlined in the original post.
