### ISSUE TITLE
Interim task to update OpenSSL 1.1.1 to latest

### ISSUE THREAD

**Issue by petetronic** [rstudio/rstudio#13683]
### System details

    RStudio Edition : Ocena Storm (dailies)
    RStudio Version : 2023.09.0+463
    OS Version      : Mac and Windows

Before addressing https://github.com/rstudio/rstudio/issues/12855, a short-term task would be to update Windows and Mac dependencies on OpenSSL to latest, i.e. 1.1.1w

**Comment by kevinushey** [comment]
Windows part of this issue has been merged; last remaining task is updating the version of OpenSSL on the macOS builders.

**Comment by gtritchie** [comment]
Updated the mac builder using these commands:

```
arch -x86_64 ~/homebrew/x86_64/bin/brew upgrade openssl@1.1
~/homebrew/arm64/bin/brew upgrade openssl@1.1
```

Confirmed the update by doing the following in an rstudio repo on the builder:

## x86_64
```
cd ~/rstudio
mkdir src/build-x86
cd src/build-x86
PATH=~/homebrew/x86_64/bin:$PATH cmake ../cpp -GNinja -DRSTUDIO_TARGET=Electron
cd ../..
rm -rf src/build-x86
```

```
-- Found OpenSSL:
~/homebrew/x86_64/opt/openssl/lib/libcrypto.dylib (found version "1.1.1w")
```

## arm64
```
cd ~/rstudio
mkdir src/build-arm
cd src/build-arm
PATH=~/homebrew/arm64/bin:$PATH cmake ../cpp -GNinja -DRSTUDIO_TARGET=Electron
cd ../..
rm -rf src/build-arm```
```

```
-- Found OpenSSL:
~/homebrew/arm64/opt/openssl/lib/libcrypto.dylib (found version "1.1.1w")
```

**Comment by gtritchie** [comment]
Not sure how to verify this... For Mac, you could look at the jenkins build log and look for "Found OpenSSL" to confirm it's picking up 1.1.1w (as shown in my earlier comment). Previously it was getting 1.1.1m.

**Comment by kevinushey** [comment]
One possibility would be to use `strings`, e.g.

```
$ strings /Applications/RStudio.app/Contents/Resources/app/Frameworks/libssl.dylib | grep 1.1.1
OpenSSL 1.1.1m  14 Dec 2021
```

**Comment by kevinushey** [comment]
We're now shipping the latest version of OpenSSL on macOS!

```
$ strings /Applications/RStudio.app/Contents/Resources/app/Frameworks/libssl.dylib | grep 1.1.1
OpenSSL 1.1.1w  11 Sep 2023
$ /Applications/RStudio.app/Contents/MacOS/RStudio --version
2023.12.0-daily+268
```
