### ISSUE TITLE
Copilot with Quarto always suggests closing and opening a chunk

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#13686]
When using Copilot with a Quarto doc, all code suggestions include closing backticks and opening ticks for the next chunk. This is problematic because when the user accepts a suggestion, they can't execute it without moving their cursor back to the previous chunk:
![image](https://github.com/rstudio/rstudio/assets/10444878/8bab3071-a4ea-4d2f-99ef-41204dc5dc52)

Ideally Copilot would make the code suggestion without also suggesting closing the current chunk.

**Comment by jthomasmock** [comment]
As far as I know @kevinushey - we aren't post-processing any of the outputs, so to some extent I think we have to "live with it". 

However, I'm curious if:  
- A) this is all artifacts from Copilot or if RStudio is clashing and trying to insert something  
- B) Is post-processing something worth exploring, and how much effort would that be?

**Comment by ronblum** [comment]
If we explore post-processing, let's also consider #13311 and #13396.

**Comment by kevinushey** [comment]
I think some minimal amount of post-processing is warranted here; at least, to strip off superfluous chunk boundaries (which Copilot seems to enjoy including)
