### ISSUE TITLE
Debugging misbehave if a fn argument is set to `file.choose()`

### ISSUE THREAD

**Issue by courtiol** [rstudio/rstudio#13691]
### System details

    RStudio Edition : Desktop AND Server
    RStudio Version : 2023.09.0 Build 463 and earlier versions
    OS Version      : Linux and Windows
    R Version       : 4.3.1

### Steps to reproduce the problem

```r
## run
foo <- function(x = file.choose()) {
  some_variable <- 1
  browser()
}

foo()
## once the debugging mode is on, start typing: some_variable
```

### Describe the problem in detail

When debugging any function with an argument set to `file.choose()`, the windows for choosing the file keeps opening despite not being requested.

It is probably because of the premature auto-evaluation of the promise for the argument set to  `file.choose()`.

### Describe the behavior you expected

The windows for choosing file should not open automatically.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Notes

- On my linux computer the bug does not seem to happen outside RStudio.
- This bug was discovered by @leoniewalter.

**Comment by ronblum** [comment]
@courtiol Thank you for raising this!

It looks like something is happening with autocomplete: Only three characters are enough to trigger this (e.g. `som`), as is typing just one character (e.g. `s`) followed by <kbd>Ctrl-Space</kbd> which should trigger autocompletion but instead opens the file dialog.

Reproduced in RStudio Desktop 2022.07.2+576 on MacOS 14.
