### ISSUE TITLE
"Workbench Install Guide" link is broken in RStudio User Guide

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13697]
### System details

    RStudio Edition : N/A
    RStudio Version : 2023.09.0
    OS Version      : N/A
    R Version       : N/A

### Steps to reproduce the problem

1. Go to the RStudio User Guide: https://docs.posit.co/ide/user/
2. In the menu bar, click on <kbd>Guides</kbd>
3. Choose <kbd>Workbench Install Guide</kbd>
    - The link is incorrect: https://docs.posit.co/ide/user/docs.posit.co/ide/server-pro/getting_started/installation/
    - This leads to a 404 error page.

### Describe the problem in detail

The "Workbench Install Guide" link in the RStudio User Guide doesn't work.

### Describe the behavior you expected

The link should be https://docs.posit.co/ide/server-pro/getting_started/installation/

Note that this is working when I render the guide from source.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
This is now fixed at https://docs.posit.co/ide/user/ and https://docs.posit.co/ide/user/2023.09.0/!

**Comment by jthomasmock** [comment]
Thanks @sharon-wang !

**Comment by ronblum** [comment]
Verified in revision 33 published October 4, 2023. Checked in both guide locations.
