### ISSUE TITLE
shasum mismatch in RStudio Desktop MacOS 2023.09.0+463

### ISSUE THREAD

**Issue by andrewherren** [rstudio/rstudio#13709]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0+463
    OS Version  : MacOS Sonoma 14.0
    R Version  : 4.3.1 (amd64)

### Steps to reproduce the problem

1. [Download the latest RStudio Desktop release](https://posit.co/download/rstudio-desktop/) for MacOS 11+ (filename `RStudio-2023.09.0-463.dmg`)
2. Run `shasum -a 256 RStudio-2023.09.0-463.dmg`

### Describe the problem in detail

The SHA-256 checksum on Posit's website (`4abee0f1aa2b8c100483ef0e83c2a023c364920c914c0e4d0ed557899a223ea7`) is different from the value returned by step 2 above (`54f6c690ba51c2f3887097aff8977e8f90e065ad273e6b1f47399ea9e67c5c58`), which matches the SHA-256 checksum of the September 24 build of RStudio Desktop 2023.09.0+463 available [here](https://dailies.rstudio.com/version/2023.09.0+463.pro11/)

### Describe the behavior you expected

A SHA-256 checksum that matches the reported checksum for MacOS.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@andrewherren Thank you for raising this! We're in the middle of fixing it. I'll update this issue when it's all set.

**Comment by ronblum** [comment]
@andrewherren All set! Let us know if you still see an issue with it.

**Comment by andrewherren** [comment]
Thank you for following up! All set on my end as well.

**Comment by Turbonio** [comment]
This is happening again with RStudio-2023.12.0-369.dmg while stalking through homebrew:

Error: SHA256 mismatch
Expected: 55266ead4cd3d3087d2b0a93f20b5e1edf02ffc628350f98409ef8e26c624fb6
  Actual: 4ef1112722c268282bd7a9f78f42607bbc7f11c5b17091edb8e3a7fa737f2eda

**Comment by ronblum** [comment]
@Turbonio Would you mind including the steps you're using get install with homebrew, including getting the sha256 sum? I want to make sure that I'm doing the same thing? Because the .dmg (downloaded from https://posit.co/download/rstudio-desktop/) is what's listed above as "Actual:". Thanks!
