### ISSUE TITLE
RStudio open a same file twice in the same window

### ISSUE THREAD

**Issue by LuisLauM** [rstudio/rstudio#13719]
### Describe the problem in detail

This bug is a bit complicated to explain, but here goes. I am working inside a folder that contains subfolders where I place data, code and one of the articles I am currently working on.

I started working my code in loose scripts that I then moved to .R files. While I was working, I had a script (places in a file function_files.R) open where I have placed some functions that I then call through the `source` function. However, when I did a debug inside a .qmd file (that is placed in a different directory than the funtions, but in the same source path of the RStudio project), I noticed that RStudio **has opened twice the same file in two different tabs** (of course, inside the same RStudio window).

When I hover the mouse over the files, they look like this:

- DirProject/functions/function_files.R
- DirProject/articles/article1/../../functions/function_files.R

You can see that both paths are equivalent.

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 Build 463 
    OS Version      :  Windows 10
    R Version       : 4.3.1

### Steps to reproduce the problem

As I said, the steps to reproduce the whole bug are not few, so I have decided to put a video on YouTube showing the problem (it's short, only one minute) and the complete reproducible example in a Github repository. I leave the links:

- The repository: [https://github.com/LuisLauM/RStudio_issue](https://github.com/LuisLauM/RStudio_issue)
- The video: [https://youtu.be/ygVG82C4hNQ](https://youtu.be/ygVG82C4hNQ)

### Describe the behavior you expected

I would expect that a debug call would not open the same file in a different tab.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@LuisLauM Thank you for raising this! Do you know if this started only with the latest version of RStudio, or if the problem occurred in earlier releases? And I appreciate the video and sharing the repository, which will make it easier to try to reproduce.

**Comment by LuisLauM** [comment]
I do not really know if the issue was present with previous versions. I have recently noticed it today, but it was just after I installed the last new version of RStudio.

**Comment by kevinushey** [comment]
Thanks for the bug report! I think we need to make sure we normalize the paths encoded in the function's source references when opening them in the IDE.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+262](https://dailies.rstudio.com/version/2023.12.0-daily+262)
Windows 11

When debugging, the file did not open in new tab, but just the original tab was used as expected.
