### ISSUE TITLE
Open Project could use the defaultProjectLocation Global preference

### ISSUE THREAD

**Issue by slodge** [rstudio/rstudio#13717]
RStudio allows you to set a default project location for new projects.

Each time you use the New Project Wizard, it saves the location you use in RStudio's global settings - so that next time you choose to create a New project, then it goes to the same location.

However, that location isn't used for Open Project, and there is no similar Global Setting for the Open Project location - instead the Open Project always defaults to the "~" home folder of the current user.

To help illustrate the change I'd like RStudio to consider, I've added a small, but incomplete, PR which might allow the Open Project dialog to share the New Project global preference in #13716 - but I don't expect this to be complete - and I'm not sure I have the time currently to complete it. (Sorry!)

Notes:
- I mentioned this previously in https://github.com/rstudio/rstudio/issues/12514 - although I think I choose the wrong code links and title there.
- It was also previously requested in https://community.rstudio.com/t/change-default-location-for-open-project/41130 - Posit employee @kevinushey answered there that people should change their Home path...

**Comment by jonvanausdeln** [comment]
Tested with [2023.12.0-daily+266](https://dailies.rstudio.com/version/2023.12.0-daily+266)
Windows 11, MacOS 12.6

This seems to have no effect on Project Open. Only 1File -> Open File1 seems to respect the global setting.  Which is the same behavior seen in the current release 2023.09.1-494. 

Test Steps:
1. Open `Tools -> Global Options`
2. Change `Default Working Directory` to a subdirectory of current HOME. (e.g. ~/Issue13717)
3. Restart IDE (may not be necessary)
4. `File -> Open Project`

It defaults to the previous HOME directory, not the newly added ~/Issue13717 working directory.

**Comment by jonvanausdeln** [comment]
I recommend moving this out to a later release and reversing the [PR/Commit](https://github.com/rstudio/rstudio/pull/13716).

**Comment by jonvanausdeln** [comment]
@slodge , I now see the intent of this issue/PR.  It does now always default to the last directory where a project was created.

It does concern me that now Open Project will always default to that directory with no obvious way to change it.  I'll discuss with the team.

**Comment by slodge** [comment]
Thanks. 💯% understood on the concern. 

Your call on whether this new solution is any better/worse than the current "can't-ever-be-changed" situation. Please do revert/delay this if you need to for longer term usability :+1:

Thanks for considering it 👍

**Comment by jonvanausdeln** [comment]
For this release, we are going to revert the current change.  And we will look at a more complete change for future release.

**Comment by slodge-work** [comment]
OK - understood.

Do I need to open a new issue for this? Do I need to submit another PR? I don't have a full rstudio workspace setup, but I really want this changed - especially as I open maybe 10 projects a day and all of them are a long way from the hard coded "~" folder ... so I'm keen to try :+1:

**Comment by kevinushey** [comment]
I think part of the reason we have some confusion here is that we have a `default_project_location` preference here:

https://github.com/rstudio/rstudio/blob/4dd0ac0bdf12bc9a2c8b982cf2612ece7f6b7665/src/cpp/session/resources/schema/user-prefs-schema.json#L670-L675

which, in theory, maps to a user-selected default project location. However, we also have a so-called user state setting of the same name:

https://github.com/rstudio/rstudio/blob/4dd0ac0bdf12bc9a2c8b982cf2612ece7f6b7665/src/cpp/session/resources/schema/user-state-schema.json#L185-L189

And that user state value is what gets updated whenever a project is opened.

To untangle the knot, I think we could add a new user preference called something like "default open project directory", and use that exclusively in the Open Project dialog.

**Comment by slodge** [comment]
I think that would work - and be a smooth user experience too (In my non-expert opinion)

At a detail level, which folder would we expect that new preference to remember? e.g. 
- if a user opens `C:/my_projects/ProjectA/ProjectA.Rrproj` 
- when she next opens a project, would she initially see: 
     - `C:/my_projects/ProjectA/` ? 
     - or `C:/my_projects/` ?

... but please don't let this conversation get in the way of your release - thanks for all the ongoing work 👍

**Comment by kevinushey** [comment]
I've put together a change in https://github.com/rstudio/rstudio/pull/13903 -- @slodge, please see that PR for details. In the next daily builds, you will be able to set the default "open project" directory in Tools -> Global Options... -> General -> Advanced. Please let us know if that's a good fit!

**Comment by slodge** [comment]
Thanks! I'll download from https://dailies.rstudio.com/ tomorrow and look 👍

**Comment by slodge** [comment]
Tested on Windows 10 on 2023.12.0 Build 274 downloaded from dailies:

Test Steps:

- Open "File -> New Project"
  - it shows "My Documents" 
- Open Tools -> Global Options
- Change "Default open project location" to C:/source/repos
- Open "File -> Open Project"
  - it opens to "C:/source/repos"

So looks 👍  to me - thanks!

--------

As an additional step I also tried with 

- Open "File -> New Project" 
- Choose "New Directory" then "New Project"
   - It shows the old "New Project" location still (is not affected by ) 

So again looks 👍  here. Thanks!

(If it helps explain my passion for this issue... on our corporate machines our Home/My Documents folder is a networked UNC path - so it's a bit slow and often causes problems with R)

**Comment by kevinushey** [comment]
Awesome, thanks for taking the time to verify!
