### ISSUE TITLE
Screen reader mode always announced as disabled and shown as disabled in menu, same with "Toggle Tab Key Always Moves Focus"

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13710]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2023.09.0-463 (Desert Sunflower)
    OS Version      : any
    R Version       : any

### Regression Notes

Worked in 2023.06.2+561 "Mountain Hydrangea" so is a regression in Desert Sunflower.

I repro'd on Mac, open-source Server, and Windows.

It was a late regression. Some quick manual bisecting shows it broke with https://github.com/rstudio/rstudio/pull/13638 which first showed up in build 2023.09.0-443.

### Steps to reproduce the problem

- Under **Help / Accessibility** menu the first item says "Screen reader support (disabled)" which is the correct default state
- Bring up Command Palette and type "screen reader" and you'll see both the command text with (disabled) and the actual checkbox state (unchecked/off)

<img width="628" alt="Screenshot of command palette with screen reader typed into it" src="https://github.com/rstudio/rstudio/assets/10569626/39f2c7b2-df10-40f7-a734-7aeaefb61ffc">

- Now click that "Screen reader support" command and a modal dialog asks if you really want to enable it, say Yes, then the IDE restarts
- Look at Help / Accessibility menu again
- Look at Command Palette and type "screen reader" again

NOTE, the same problem happens with the Help / Accessibility / Focus / "**Toggle Tab Key Always Moves Focus**" command. It always shows as "off" (unchecked) in the menu, even when it is turned on.

### Describe the problem in detail

- Menu command still says it is disabled

<img width="562" alt="Screenshot showing the Help / Accessibility menu" src="https://github.com/rstudio/rstudio/assets/10569626/ebfae132-f499-49c6-9262-5491b9e3db7c">

- Command Palette has a mixed state (text says disabled, checkbox shows enabled)

<img width="645" alt="Screenshot of command palette showing inconsistent state for screen reader mode" src="https://github.com/rstudio/rstudio/assets/10569626/bb12af6e-a815-411d-97c0-790df268cf96">

- Global Options also shows it being checked:

<img width="632" alt="Screenshot of Global Options Accessibility pane" src="https://github.com/rstudio/rstudio/assets/10569626/371ff47a-7a8d-46a0-b796-08a828c91119">

### Describe the behavior you expected

- It should switch to "enabled" as it does in 2023.06.2 and earlier

### Bonus points: repro with a screen reader (real-world scenario)

Turn on a screen reader before you start RStudio. After RStudio starts, it will read what's in the console, then it will say "Warning. Screen reader mode not enabled. Turn on using shortcut ...".

Now try to turn on screen reader mode using the menu, and after the restart you'll again be told that "Screen reader mode not enabled" message again.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Triage: Proposed for Desert Sunflower patch.

**Comment by gtritchie** [comment]
Narrowed down to this commit: https://github.com/rstudio/rstudio/pull/13638

**Comment by ronblum** [comment]
@gtritchie I think screen reader support gets correctly enabled, though reported incorrectly? Even with the menu item under <kbd>Help -> Accessibility</kbd> unchecked, the pop-up will switch between "enable" and "disable".
<img width="253" alt="sre" src="https://github.com/rstudio/rstudio/assets/31009952/54d0caa8-4494-40f3-a118-e7e965f9039c">

**Comment by gtritchie** [comment]
Yes, per the fix, that is accurate. The menu text was always saying
disabled and the announcement warning that screen reader mode is off was
always being made. The underlying setting itself was correctly changing
state as seen in the accessibility preferences pane and the command palette.

For a screen reader user, however, being told the screen reader mode is off
every time RStudio launches (and telling them the shortcut to hit to toggle
it) makes it unusable.

**Comment by gtritchie** [comment]
Changed issue title to be more accurate.

**Comment by ronblum** [comment]
Agreed. Technically working doesn't make up for being repeatedly told that it's not working.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.09.1+470 on MacOS 14 using VoiceOver.
