### ISSUE TITLE
The secondary toolbar missing in the presentation tab and the primary toolbar shows buttons disabled in the quarto presentation

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#13711]
### System details

    RStudio Edition : Server 
    RStudio Version : 2023.12.0 Build 99
    OS Version      : ubuntu20
    R Version       : 4.3.0

### Steps to reproduce the problem

1. Run the following in the console to create a quarto presentation. `.rs.api.executeCommand('newQuartoPres')`
2. Save the file.
3. From the source pane, change the render option in the gear icon to `Preview in Viewer Pane`
4. Click to render the document.
5. Observe the presentation tab.

### Describe the problem in detail
The secondary toolbar missing in the presentation tab and the primary toolbar shows buttons disabled in the quarto presentation. Observe the screen shot comparing 2023.12 vs 2023.09

![Screenshot 2023-09-28 at 10 19 12 AM](https://github.com/rstudio/rstudio/assets/1482677/0143c08d-256d-46cb-a664-9e424024646c)

### Describe the behavior you expected
I would expect the secondary toolbar to show and the primary toolbar to show the button options enabled as it does in the 2023.09 build.

**Note**: `test_render_quarto_presentation` is the test this failed in. We will need to uncomment out some of the commented out checks once this is fixed.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I think the issue here is actually in Quarto, but I've added a mitigation for RStudio so that this can continue to work.

**Comment by ronblum** [comment]
Verified that the toolbar has returned and that the buttons are enabled, in RStudio Desktop 2023.12.0-daily+196 on MacOS 14 and Red Hat 9.2. There's an issue with some of the buttons on Red Hat, but I'll file that separately.
