### ISSUE TITLE
copilot: update agent

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13729]
- [x] Update to the latest version of the Copilot agent
- [ ] Make it easier to install a particular revision / version of the Copilot agent

**Comment by jthomasmock** [comment]
Let me know if this makes sense to add to another/new issue, but I had a customer request for some more info on update/install of the Agent:

- More information on how to install the agent for all their Workbench users
- The URL for the agent location (to allow it to cross proxy/firewall)
- Whether the agent can be installed into user space or requires an admin, they saw the failures below:

```
trying URL 'https://rstudio.org/links/github-copilot/1358e8e45ecedc53daf971924a0541ddf6224faf'
Content type 'application/x-gzip' length 2883449 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

sh: 1: /usr/bin/tar: not found
Error: Copilot Agent installation failed: '/home/<REDACTED>/.cache/rstudio/copilot/dist/agent.js' does not exist.
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In untar(destfile) :
  ‘/usr/bin/tar -xf '/tmp/RtmpdYDCmq/copilot-3f5370a00b99f/copilot.tar.gz'’ returned error code 127
trying URL 'https://rstudio.org/links/github-copilot/1358e8e45ecedc53daf971924a0541ddf6224faf'
Content type 'application/x-gzip' length 2883449 bytes (2.7 MB)
==================================================
downloaded 2.7 MB
```

**Comment by kevinushey** [comment]
> sh: 1: /usr/bin/tar: not found

That is ... very surprising. They need to set the `TAR` environment variable to point at a valid `tar` executable.

**Comment by jthomasmock** [comment]
Moved to a separate issue to not muddy this one too much: https://github.com/rstudio/rstudio/issues/13746

**Comment by kevinushey** [comment]
Updated to 1.10.3 in https://github.com/rstudio/rstudio/commit/7758c28d9b479116e624d32b157321111f438865.
