### ISSUE TITLE
copilot path completion

### ISSUE THREAD

**Issue by petyaracz** [rstudio/rstudio#13725]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.12.0-daily+105 
    OS Version      : macos 13.4
    R Version       : 4.3.1

### Steps to reproduce the problem

1. Enable co-pilot
2. use function with path in it, e.g. `read_tsv`
3. use tab to move around in file structure

### Describe the problem in detail

I think this is a bug report and not a feature request. Feel free to overrule!

Both RStudio path autocomplete and copilot use `tab` to finish a string. So if you use e.g. `read_delim` and try to navigate a directory, copilot will take over and suggest file names that don't exist. The resulting behaviour is very confusing.

In e.g. vscode this issue doesn't exist because there is no path autocomplete by default. However, it is widely used in RStudio and `tab` is reserved for it.

### Describe the behavior you expected

I'm not sure what the good UX solution is. Possibly disabling copilot when the cursor is in a path.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
As an alternative, you can use Ctrl + Space to request completions, and the Enter key to insert the selected completion item. This allows Tab to be reserved for interacting with Copilot completions. Is this a reasonable compromise?

**Comment by kevinushey** [comment]
@petyaracz: do you feel the current behavior is a sufficient compromise for your needs?

**Comment by petyaracz** [comment]
Tried this. On the Mac, the equivalent `Cmd+Space` is reserved for using Spotlight. This is something people use all the time. So `Cmd+Space` is not a good substitute for `Tab`. 

Otherwise I think a different shortcut for path completion is probably the way to go, though it will be tricky to unlearn `Tab` here.

**Comment by kevinushey** [comment]
For macOS, we would encourage using Ctrl + Space rather than Cmd + Space.

**Comment by petyaracz** [comment]
In macOS, Ctrl + Space is the change keyboard layout shortcut. That probably affects fewer people than the tab issue. I would recommend adding path completion to the rstudio shortcut list.
