### ISSUE TITLE
Issues with line numbers in gutter

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13722]
### System details

    RStudio Edition : 2023.09.999-dev+999
    RStudio Version : Server [Open Source]
    OS Version      : macOS Ventura 13.6
    R Version       : R version 4.3.1 (2023-06-16)

###

Saw this when opening a file in RStudio. Perhaps related to the recent Ace update?

<img width="735" alt="Screenshot 2023-09-29 at 3 53 25 PM" src="https://github.com/rstudio/rstudio/assets/1976582/32bfe98c-0454-4f95-9605-2cb0b7912b25">

---

<details>

<summary>Session Info</summary>

``` r
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.3.1         Matrix_1.6-1.1         cli_3.6.1.9000        
 [4] tools_4.3.1            rstudioapi_0.15.0.9000 Rcpp_1.0.11           
 [7] reticulate_1.32.0      grid_4.3.1             jsonlite_1.8.7        
[10] rlang_1.1.1.9000       png_0.1-8              lattice_0.21-8        
```

</details>

**Comment by kevinushey** [comment]
One hint is that some of the errant cells have a class of 'undefined', e.g.

<img width="658" alt="Screenshot 2023-09-29 at 3 55 53 PM" src="https://github.com/rstudio/rstudio/assets/1976582/e1a5ab7e-636a-4adb-9605-6ad999ed2ea9">

**Comment by kevinushey** [comment]
And the issue seems to occur on any line that contains an error or lint; that is, if we tried to draw an Ace annotation for that row.

**Comment by jonvanausdeln** [comment]
Verified with https://github.com/rstudio/rstudio/pull/13716 on Windows 11, MacOS 12.6

Line numbers are correct.
