### ISSUE TITLE
Reloading the visual editor with Quarto `format` changes messes up the editor toolbar

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#13724]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 Build 463
    OS Version      : Mac OS 13.5 (22G74)
    R Version       : 4.3.1

### Steps to reproduce the problem

- Open a quarto document
- Change the format from html to something else, I tried revealjs
- RStudio will prompt you to reload the visual editor, say ok
- Observe the editor toolbar

### Describe the problem in detail

It appears that the editor toolbar is repeated? With the new (functional) toolbar appended to the existing one instead of replacing it.

See screen recording below. Note that when I place my cursor on the H2 header, format type still reads "Normal". And when I extend the editor you can see some menu items repeated.

https://github.com/rstudio/rstudio/assets/5965649/42a100b4-f94f-4b3f-8459-fe8af450ce21

### Describe the behavior you expected

I expected the new toolbar to replace the existing one.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mine-cetinkaya-rundel I think we had a similar bug a while ago. I'll update this issue if I can find it.
