### ISSUE TITLE
Visual Editor not working on build 114, nor on build 105 (2023.12.0)

### ISSUE THREAD

**Issue by pedrohbraga** [rstudio/rstudio#13730]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0 daily 105, and 2023.12.0 daily 114
    OS Version      :  Windows 11
    R Version       : 4.3.1

### Steps to reproduce the problem

1. Create or Open any Quarto document;
2. Attempt using the Visual Editor.

### Describe the problem in detail

I have been having the same issue across any new or already opened Quarto documents, across projects. Once I click on Visual Editor, I obtain the message below, which prevents using the Editor. The issue only stopped when I rolled back to 2023.12.0 build 46.

![image](https://github.com/rstudio/rstudio/assets/8599229/6e1ba9ca-ac21-4f41-9e8b-9d1b05fe3f98)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be fixed by https://github.com/rstudio/rstudio/commit/b52a4c2ef54937226aec5c0d4c66b9810d0ce435.

**Comment by pedrohbraga** [comment]
Thank you! I confirm it is working in the newest version!

**Comment by kevinushey** [comment]
Great, thanks -- sorry for the trouble!
