### ISSUE TITLE
terminal does not respect global option setting for shell

### ISSUE THREAD

**Issue by drmowinckels** [rstudio/rstudio#13747]
### System details

    RStudio Edition : Desktop or Server 
    RStudio Version : 2023.06.2+561 (2023.06.2+561)
    OS Version      :  macOS ventura 13.4 (22F2063)
    R Version       :  4.3.1 (2023-06-16)

### Steps to reproduce the problem
Open a new terminal

### Describe the problem in detail
In my RStudio options for the terminal, I have set zsh to be my preferred shell.
I updated my RStudio today after postponing for a while, and now this option is 
not respected when I open the terminal. It always opens in bash. I have double 
checked that the settings are still set to zsh.

### Describe the behavior you expected
Terminal should open in Zsh (or other selected shell from the global options)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@drmowinckels Thank you for raising this! I'm unable to reproduce the problem (same build but on MacOS 14). Do you know what version you were using previously, in which this still worked? Also, we just released a [new version of RStudio](https://posit.co/download/rstudio-desktop/), 2023.09.0+463. Does this version work correctly, or is still pointing to the wrong shell?

**Comment by drmowinckels** [comment]
hey. Ok. I updated again (I did 2 weeks ago and was so sure I was on the newest, sorry!), and the problem is solved. 
Sorry about that.
