### ISSUE TITLE
Copilot: URLs for download and Copilot Auth/API access behind proxy

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13746]
### System details

    RStudio Edition : Server
    RStudio Version : Posit Workbench 2023.09.1+467.pro6
    OS Version      : Ubuntu 22.04
    R Version       : 

### Steps to reproduce the problem

@Chris-Engelhardt reported an issue both downloading and then using Copilot.

They are behind a proxy running in Ubuntu 22 on Azure server.

Try to download the Copilot User Agent:

```
sh: 1: /usr/bin/tar: not found
Error: Copilot Agent installation failed: '/home/<REDACTED>/.cache/rstudio/copilot/dist/agent.js' does not exist.
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In untar(destfile) :
  ‘/usr/bin/tar -xf '/tmp/RtmpdYDCmq/copilot-3f5370a00b99f/copilot.tar.gz'’ returned error code 127
trying URL 'https://rstudio.org/links/github-copilot/1358e8e45ecedc53daf971924a0541ddf6224faf'
Content type 'application/x-gzip' length 2883449 bytes (2.7 MB)
==================================================
downloaded 2.7 MB
```

This was resolved by:

> the fix to the install challenge was to symlink /bin/tar, where the tarball actually downladed to, with /usr/bin/tar, where I suspect RStudio was looking for it.
After the symlink, the install worked at the user level as expected.

However, after install when they attempted to login via the Global Options > Copilot, the popup for login window is immediately killed. I wonder if the proxy is preventing the API request and it's just failing?

### Describe the problem in detail

Unable to have user-downloaded User Agent and unable to authenticate to the Copilot service.

### Describe the behavior you expected

Should users be able to download the User Agent and dependencies into user space or should admins install for users globally?

Adding on that we'll probably want to document the URLs to allow for firewalls/proxy in order to connect to Copilot API.

```
copilot-proxy.githubusercontent.com
api.github.com (Also used for Self-hosted runners)
```

And/or the info about proxy information Kevin added: https://github.com/rstudio/rstudio/issues/13431#issuecomment-1688943921 - that should probably be added to a global profile if admins want to enable Copilot for their users?

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
In the most recent daily builds, it's now possible to set a proxy URL to be used by the Copilot agent for outbound network requests. This can be set by adding the following to your `/etc/rstudio/rsession.conf`:

```
copilot-proxy-url=<host>:<port>
```

In addition, you can disable certificate validation if necessary with:

```
copilot-proxy-strict-ssl=0
```

These builds are available at https://dailies.rstudio.com.

**Comment by jonvanausdeln** [comment]
@jthomasmock is there a user who reported this that could test the new setting in our daily builds? 

@Chris-Engelhardt, would be able to test our latest Daily build? https://dailies.rstudio.com/.

**Comment by jthomasmock** [comment]
I'll follow-up with Chris separately.

**Comment by markderry** [comment]
Is this available in the windows build?

**Comment by kevinushey** [comment]
On Windows, you can set the `COPILOT_AUTH_PROVIDER` environment variable; I recommend setting it in your `~/.Renviron` or some similar R startup file.

**Comment by markderry** [comment]
Thanks @kevinushey that is most helpful!!
