### ISSUE TITLE
stop indexing 'package' directory in RStudio project

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13744]
Since we might end up editing the wrong source file and quietly losing changes...

<img width="350" alt="Screenshot 2023-10-03 at 5 23 09 PM" src="https://github.com/rstudio/rstudio/assets/1976582/5afc3032-b01e-4e86-bb10-7be7d6709b14">

**Comment by jgutman** [comment]
I have done this before! 🤦‍♀️
