### ISSUE TITLE
Add ctrl-space as a suggested manual autocomplete option

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13752]
Add "ctrl-space" to the option for manual autocomplete, which is needed in the editor if both Copilot suggestions and autocomplete are enabled. That is, change

    Manual (tab)

to

    Manual (tab, ctrl-space)

<img width="642" alt="Screenshot 2023-10-04 at 9 16 16 AM" src="https://github.com/rstudio/rstudio/assets/1976582/3a4d0bb1-47cd-4005-a0f8-926cb551c3ac">

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+306](https://dailies.rstudio.com/version/2023.12.0-daily+306)
Windows 11

New option update. `ctlr + space` works when copilot enable.
