### ISSUE TITLE
Project options are not getting saved

### ISSUE THREAD

**Issue by aylapear** [rstudio/rstudio#13757]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 Build 463
    OS Version      : macOS Ventura 13.5
    R Version       : 4.3.0 (2023-04-21)

### Steps to reproduce the problem

Go to Tools > Project Options > Build Tools and select/tick Generate documentation with Roxygen and press OK

Check in your Build tab that the Documentation option/button is present under the More dropdown. 

Terminate R.

Notice that the Documentation option/button is gone now under the Build tab > More. 

Go to Tools > Project Options > Build Tools and you will see Generate documentation with Roxygen is deselected, press OK.

### Describe the problem in detail

It appears that RStudio is not retaining the options selected under Generate documentation with Roxygen. 

This was not an issue in previous version of RStudio.

### Describe the behavior you expected

Once this option is selected that it stays selected and closing RStudio/ terminating R/etc do not cause the project options to revert to their default setting. In previous version of RStudio when you would select this option it would stay selected under a user came and deselected the option. 

I found another person reporting the same issue within the last couple days: https://community.rstudio.com/t/devtools-document-roxygenise-will-not-work-when-installing/174542

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thank you for the bug report -- we'll try to get this fixed up ASAP!

**Comment by ronblum** [comment]
See note in PR: This affects saving all project options.

**Comment by jgutman** [comment]
Merged into `rel-desert-sunflower` for 2023.09.1 and into main for 2023.12.0

**Comment by jonvanausdeln** [comment]
Verified on DS Patch hourly [2023.09.1-hourly+472](https://dailies.rstudio.com/version/2023.09.1-hourly+472)

Project options persist after R session is restarted.

I will check dailies when available and close out after that.

**Comment by jonvanausdeln** [comment]
Verified on [2023.12.0-daily+155](https://dailies.rstudio.com/version/2023.12.0-daily+155) and [2023.09.1+475](https://dailies.rstudio.com/version/2023.09.1+475)

Project options saved through several scenarios of R session rstarts.
