### ISSUE TITLE
Feature Request: To dull the colour of RStudio Launch Screen or Splash Screen

### ISSUE THREAD

**Issue by shivam7898** [rstudio/rstudio#13768]
The start screen of RStudio blinds with a full white window as a direct hit on my poor eyes :'( 
Is it possible to either - 
1. mute /dull /darken the colour 
2. or allow the user to select a colour choice for startup
3. or note that user has selected a dark theme then change the start screen colour to black/grey

Anything please other than this assault on user's retina. I am using a dark theme as shown in the 2nd image. It feels like a camera flash every time the IDE is opened. 
There is [an year old ssue](https://github.com/rstudio/rstudio/pull/12117) but I am not sure if this was implemented some way or how to enable it, if possible. In the thread where Splash screen was added, [this comment](https://github.com/rstudio/rstudio/issues/11604#issuecomment-1279304220) has some good points but again I am unsure about its status. 

I know branding is important but I already use RStudio. Personally, I code even `Python` in RStudio (I really don't like Jupyter Notebook). However, as a Minimum Viable Product (MVP) a simple change in colour should make the life a lot easier. Thank you for an excellent IDE and everything you have done for `R` ecosystem. 

```
RStudio Edition : Desktop
RStudio Version : RStudio 2023.09.0+463 "Desert Sunflower"
OS Version      : Windows 10 x64 (build 19045) (x86_64-w64-mingw32/x64 (64-bit))
R Version       : 4.3.1
```

![RStudio Splash](https://github.com/rstudio/rstudio/assets/10017658/5b822dcb-0d99-442d-83a0-d87d65762ddc)

![dark studio](https://github.com/rstudio/rstudio/assets/10017658/ff240263-7bbb-4190-acb2-8a240c993a6e)

**Comment by ronblum** [comment]
@shivam7898 Thank you for the suggestion, and I'm sorry that this is painful on the eye! I understand where you're coming from. We'll review this as we continue development of RStudio.

@timtmok Is there a way to get the initial window to recognize the mode when RStudio first starts up, before even starting to load the contents of the IDE?

**Comment by timtmok** [comment]
Yes, we should be able to query the OS if dark mode is enabled and adjust the initial background colour to a darker colour.

Using `nativeTheme`, we can determine what the initial background colour should be.
https://github.com/rstudio/rstudio/blob/a6a932f62ef90cfb28f91e85c7f967b219f248a9/src/node/desktop/src/main/desktop-browser-window.ts#L131

**Comment by ronblum** [comment]
@timtmok Thanks! FWIW, it hurts my eyes, too. 🙂

**Comment by ronblum** [comment]
Proposed solution: Start with a neutral gray.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+426 on MacOS 14.3 that the initial window is now appropriately dull.

Checked with OS dark and light mode and RStudio dark and light themes. (None of which should matter, but just checking.)
