### ISSUE TITLE
switch copilot account in rstudio

### ISSUE THREAD

**Issue by sckinta** [rstudio/rstudio#13772]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 2023.09.0+463 Chrome
    OS Version      : Macintosh; Intel Mac OS X 10_15_7
    R Version       : 4.3.1

### Steps to reproduce the problem

- go to global options under tools menu
- select "Enable GitHub Copilot" and install copilot agent following the dialogue
-  sign in with account A
- go back to global options and sign in with account B

### Describe the problem in detail

I am not sure whether this is an bug or I should request as a new feature. I installed copilot agent following the dialogue and signed in with github account A, but I now want to switch to a different github account B which I have copilot permission. There is no way to do so. I tried to delete cached copilot agent under `/home/<user>/.cache/rstudio/copilot` and restart Rstudio (even reinstall Rstudio) to switch copilot account, but nothing worked. The activate button led to signed in account on github page, and refresh did not pop anything. I am wondering 1) should it be a sign out button somewhere at copilot option? 2) Is anything backend I can change to delete/sign out current copilot account and re-sign in with the new account?

![image](https://github.com/rstudio/rstudio/assets/4685107/2e9ef2d6-82ce-4a32-99cc-0e0f93d205a0)

### Describe the behavior you expected

go back to global options and allow switch github account

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sckinta Thanks for letting us know! We'll review this as we continue to work on the RStudio/Copilot integration.

**Comment by kevinushey** [comment]
FWIW If you use Tools -> Show Command Palette, then you can find a command to sign out:

<img width="634" alt="Screenshot 2023-10-16 at 1 55 12 PM" src="https://github.com/rstudio/rstudio/assets/1976582/bd3d7874-d962-479c-8b9d-d18a063cf68d">

**Comment by sckinta** [comment]
Thanks, Kevin! The method worked (just need to make sure the "Enable Github Copilot" is checked in Global Option). I will close the issue but still wish that there will be a "Sign Out" button at global option in the future release. Thank you for the help!

**Comment by ronblum** [comment]
@sckinta In Global Options, are you now signed in to the account that you intend to, and is there a "sign out" button? E.g.
<img width="308" alt="signout" src="https://github.com/rstudio/rstudio/assets/31009952/49faac2a-ac42-4e1f-89bb-5b5f49aa92d0">

**Comment by ErickValdiviaMtz** [comment]
porque en mis global options no tengo Copilot, ¿como puedo hacer uqe aparezca?
