### ISSUE TITLE
Cache node installs used by dependency scripts in S3/CDN

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13773]
The node.js dependency installation step occasionally breaks the build due to mysterious problems with the download. Been seen on all platforms (Mac/Windows/Linux).

We could cache these in our tools bucket to reduce the likelihood of this problem.

Not much to test here, either the builds work or they don't.

**Comment by jonvanausdeln** [comment]
Builds have been successful since this change and passed automated tests.
