### ISSUE TITLE
Project option ignored: "Disable .Rprofile execution on session start/resume"

### ISSUE THREAD

**Issue by jonovik** [rstudio/rstudio#13780]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 Build 463
    OS Version      : Windows 10, Version 21H2 (OS Build 19044.3448)
    R Version       : 4.3.1

### Steps to reproduce the problem

* RStudio > File > New project > New directory > New project.
* Tools > Project options > General > Miscellaneous > check (tick) "Disable .Rprofile execution on session start/resume".
* Click OK.
* Tools > Project options > General > Miscellaneous > Disable .Rprofile execution on session start/resume is blank again, even though I just ticked it.

### Describe the problem in detail

Context: My ~/.Rprofile changes locale to NO_NB.utf8, but now I want to troubleshoot a student's issue with seemingly random changes to locale. I found a similar issue and am trying to recreate the steps therein: [R locale automatically resets to the default one](https://github.com/rstudio/rstudio/issues/9388).
 To do that, I wish to disable my .Rprofile inside my troubleshooting project, using the checkbox in RStudio > Tools > Project options > General > Disable .Rprofile execution on session start/resume.

However, ticking the checkbox does not "stick", and .Rprofile is not ignored. I can tick the box, close the dialog, reopen the dialog and the checkmark is gone. Here's a screencast:

![disable_rprofile_ignored](https://github.com/rstudio/rstudio/assets/608322/2188431c-b964-4130-8f1c-76a57762665c)

### Describe the behavior you expected

Firstly, I expect to see Project Options to remember my checkmark. Secondly, I'd hope to see my system-default locale in effect after restarting my R session.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jonovik Thank you for raising the issue! As you've noted, the project options are sticking. This is covered by issue #13757, and we're actively working on a patch for this that we're trying to get out ASAP. If you'd like to try it out, you can get[ the latest 2023.09.1 patch dailies](https://dailies.rstudio.com/rstudio/desert-sunflower/), but please note that while very limited in scope, these builds are considered for testing purposes only, not production.
