### ISSUE TITLE
Private github/copilot access

### ISSUE THREAD

**Issue by wedsall** [rstudio/rstudio#13788]
Hello RStudio Team,

I am writing to request a new feature that I believe would greatly enhance the RStudio experience for many users, especially those working in a corporate environment.

Many companies, including ours, use a private Git server for version control. Currently, RStudio supports integration with GitHub, but it would be extremely beneficial if RStudio could also connect to a company's private Git server

Thanks
William

**Comment by ronblum** [comment]
@wedsall Thank you for the suggestion! We'll review this as we continue development of RStudio.

**Comment by ad0861** [comment]
Is this request specific to copilot? Because RStudio can actually work with more than just GitHub. I personally use it with a private BitBucket instance

**Comment by wedsall** [comment]
Yes specific to copilot. I was told that the copilot capability only worked with public github, not private github servers.

**Comment by vitas** [comment]
how to use a corporate github? it is actually public, but has address as : https://github.developer.mycopany/

**Comment by kevinushey** [comment]
I apologize, but I don't quite understand the request:

> Currently, RStudio supports integration with GitHub, but it would be extremely beneficial if RStudio could also connect to a company's private Git server

What exactly are you trying to do? What is the relationship here between what you're doing and Copilot?

**Comment by vitas** [comment]
yes, exactly..it is actually github server, but for enterprise customers

**Comment by wedsall** [comment]
Following up: I may have been misinformed - in my case, it seems that our copilot connection does not use a private copilot server, it does use the github copilot service.

This feature request may invalid unless someone else has a real example of a private copilot system.
