### ISSUE TITLE
Ace reporting misspelled options "completionCharacterThreshold" and "completionDelay"

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13789]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2023.12.0-144 and newer
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

Run a build of RStudio that includes the update to Ace done in https://github.com/rstudio/rstudio/pull/13708.

Start RStudio and do File / New File / R Script, then open dev tools (e.g. Inspect Element on context menu in Desktop, or Chrome dev tools, etc.) and look at the console output.

### Describe the problem in detail

Numerous incidents of two warning messages generated by Ace:

```
misspelled option "completionCharacterThreshold"
misspelled option "completionDelay"
```

### Describe the behavior you expected

No warnings. Don't know if this is causing end-user problems, but we should check on it.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
For QA: While we should definitely check that the messages Gary reported are no longer displaying in the console output, I believe they are just symptomatic of an issue with a couple of autocompletion user preferences not properly being passed on to Ace. What I think we really need to test is the following:

In Global Options > Code > Completion > Completion Delay, play around with the following user preferences:
<img width="492" alt="image" src="https://github.com/rstudio/rstudio/assets/7817881/78317223-5ed8-43c1-be66-3c91f3965d2e">
You should have Show code completions set to Automatically for testing
<img width="349" alt="image" src="https://github.com/rstudio/rstudio/assets/7817881/78daf266-4d5e-4ccc-8b4f-26d424cd16cd">

- Show completions after characters entered should affect the minimum number of characters in a word a user types before autocompletions pop up
- Show completions after keyboard idle (ms) should affect the number of milliseconds after last keystroke before the autocompletion pop up appears

As part of testing, play around with both settings to be confident that these settings are actually being respected in the autocompletion popups.

**Comment by ronblum** [comment]
@jgutman Were the autocomplete settings only getting respected in some case? I've tried setting these in an earlier build, 2023.12.0-daily+131, and both of these settings work in visual and source modes of R, Qmd, and Rmd files, and the Console Pane.

**Comment by ronblum** [comment]
@jgutman Thanks! Just making sure that my testing is valid. 🙂

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+196](https://dailies.rstudio.com/version/2023.12.0-daily+196)
Windows 11, Ubuntu22

Error no longer appears. The autocompletion settings do persist and work as expected.
