### ISSUE TITLE
browser() does not work in Shiny apps run using the GUI

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#13790]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0+463 Desert Sunflower (desktop)
    OS Version      : macOS 14.0
    R Version       : R version 4.3.0 (2023-04-21)

### Steps to reproduce the problem

Create a shiny app.  Insert `browser()` somewhere in the code. Use the Run App button in the RStudio GUI.

### Describe the problem in detail

The browser is not called, no debut state starts. Whether the GUI is set to run app in the console or a background job does not matter.

However, when I use `runApp()` from the console, the `browser()` is called and starts as expected.  

### Describe the behavior you expected

`browser()` will start when a section of code it is in runs.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jzadra Thank you for raising this! I can't reproduce the problem, though, in the same environment. Can you provide a simple code example that causes the problem, so that I can try to reproduce this exactly the same way? If it also happens with the default app, you can just show me exactly which lines in which you've placed `browser()`.

**Comment by jzadra** [comment]
I set up a basic app and it worked if Run App from Console was selected, but did not work when Run in Console was selected.  As usual after opening an issue and creating a small reprex, the app I was originally trying this in started also working in run from console mode. I know I tried that before and it didn't work, but it may have been some other factor.  I will see if I can reproduce it in the future.

On the issue of it not working in "run in background", is it supposed to?  I notice on my "New Shiny Web App" template app that I see debug calls are echoed in the Background Jobs tab when run from background is selected. Hower no browser opens. These result from adding a `browser()` on line 16 of server.R

```

=> shiny::runApp()

Loading required package: shiny

Listening on http://127.0.0.1:3606
Called from: renderPlot()
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#18: x <- faithful[, 2]
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#19: bins <- seq(min(x), max(x), length.out = input$bins + 1)
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#22: hist(x, breaks = bins, col = "darkgray", border = "white", xlab = "Waiting time to next eruption (in mins)", 
main = "Histogram of waiting times")
Called from: renderPlot()
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#18: x <- faithful[, 2]
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#19: bins <- seq(min(x), max(x), length.out = input$bins + 1)
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#22: hist(x, breaks = bins, col = "darkgray", border = "white", xlab = "Waiting time to next eruption (in mins)", 
main = "Histogram of waiting times")
Called from: renderPlot()
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#18: x <- faithful[, 2]
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#19: bins <- seq(min(x), max(x), length.out = input$bins + 1)
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#22: hist(x, breaks = bins, col = "darkgray", border = "white", xlab = "Waiting time to next eruption (in mins)", 
main = "Histogram of waiting times")
Called from: renderPlot()
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#18: x <- faithful[, 2]
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#19: bins <- seq(min(x), max(x), length.out = input$bins + 1)
debug at /Users/myuser/Documents/R Projects/jzadra_misc/shiny browser test/test/server.R#22: hist(x, breaks = bins, col = "darkgray", border = "white", xlab = "Waiting time to next eruption (in mins)", 
main = "Histogram of waiting times")
```
