### ISSUE TITLE
Text highlight in Quarto documents is hard to read in dark theme

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13807]
### System details

    RStudio Edition : 2023.12.0-daily+193
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Ventura 13.6
    R Version       : R version 4.3.1 (2023-06-16)

### Steps to reproduce the problem

Highlight some text in a Quarto document.

### Describe the problem in detail

<img width="717" alt="Screenshot 2023-10-17 at 10 23 01 AM" src="https://github.com/rstudio/rstudio/assets/1976582/211967eb-5465-4398-af28-f50ccb65d124">

### Describe the behavior you expected

Older versions of RStudio gave a legible highlight.

<img width="488" alt="Screenshot 2023-10-17 at 10 24 26 AM" src="https://github.com/rstudio/rstudio/assets/1976582/fe9b4eb6-2949-4eff-b6ef-bc2492f689eb">

---

<details>

<summary>Session Info</summary>

``` r
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.1 tools_4.3.1   
```

</details>

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+196 on MacOS 14, Red Hat 9.2, and Windows 10. Checked that highlighting is legible in dark and light mode, in both visual and source mode for Quarto and R Markdown.
