### ISSUE TITLE
Copy-pasting table from MS Word to Quarto (Visual Editor) duplicates rows and columns

### ISSUE THREAD

**Issue by sda030** [rstudio/rstudio#13806]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0+170 
    OS Version      : Windows 11
    R Version       : 4.3.1
    MS Office       : 365 (18.2306.1061.0)

### Steps to reproduce the problem
1) Open a Microsoft Word-document with a simple table (e.g. 2x2 like below). Copy the table.
```
|-----|-----|
| A   | B   |
|-----|-----|
| C   | D   |
|-----|-----|
```
2) Create an empty Quarto document. Use Visual Editor. 
3) Paste the table. 

### Describe the problem in detail
Observe that rows and columns are duplicated. This occurs both in release version and latest daily build.
```
+-----+-----+-----+-----+----+
|     |     |     |     |    |
+-----+-----+-----+-----+----+
|     | A   |     | B   |    |
+-----+-----+-----+-----+----+
|     |     |     |     |    |
+-----+-----+-----+-----+----+
|     | C   |     | D   |    |
+-----+-----+-----+-----+----+
|     |     |     |     |    |
+-----+-----+-----+-----+----+
```
Contrast this with a HTML-based table from a website which works as intended.

### Describe the behavior you expected
A pasted table should contain as many rows and columns as in the original.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [-] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sda030 Thank you for raising this! What happens when you copy and paste from other file types, such as Notepad?

**Comment by sda030** [comment]
@ronblum, it is not possible to make tables in Notepad.

**Comment by ronblum** [comment]
@sda030 Ah! In step 1, I thought that the source code represents what you were copying from the Word file, not a Word table.

Reproduced in RStudio Desktop 2023.09.0+463 on Windows 11, but works correctly on MacOS 14.

Original table in Word:
![source](https://github.com/rstudio/rstudio/assets/31009952/8fc997e9-9b7b-45f5-86ff-b0eb59eb061e)

Pasted table in the visual markdown mode:
![target](https://github.com/rstudio/rstudio/assets/31009952/418d176c-2d2a-46dc-a394-db46a126ca2f)

**Comment by kevinushey** [comment]
This appears to be a Quarto issue; I've moved the issue to https://github.com/quarto-dev/quarto/issues/303.
