### ISSUE TITLE
Some Presentation Pane buttons don't work

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13814]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0-daily+196
    OS Version      : Red Hat 9.2
    R Version       : 4.2.3

### Steps to reproduce the problem

1. Create a Quarto Presentation.
2. Set it to "Preview in Viewer Pane".
3. Render the file.

### Describe the problem in detail

The presentation is rendered and displayed in the Presentation Pane, and the extra toolbars are present (#13711). However, the "present," "print," "edit," and "present in an external web browser" buttons don't work.

### Describe the behavior you expected

The buttons should work, as they do on MacOS 14.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I wasn't able to reproduce -- is it possible that has since been fixed? (This may also be related to the "can't open external web browser" issues we discussed in the past; does it make a difference if Firefox is already open or not?)

**Comment by ronblum** [comment]
Looks like this has been fixed—the buttons now work in RStudio Desktop 2024.04.0-daily+327 on MacOS 14.3.

**Comment by datos-ine** [comment]
Got the same problem, but only with projects saved in the local computer. Using Windows 10.

**Comment by ronblum** [comment]
@datos-ine This probably warrants a new issue, but first:

1) Can you provide your configuration? 
    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 
2. Regarding the local computer, does this mean that it works if you're using remote storage--Google Drive, OneDrive, etc.?
3. Is it the same Presentation Pane buttons mentioned in the original post?

**Comment by datos-ine** [comment]
@ronblum 
1)
- RStudio Edition: Windows

- RStudio Version: RStudio 2024.09.0+375 "Cranberry Hibiscus" Release (c8fc7aee6dc218d5687553f9041c6b1e5ea268ff, 2024-09-16) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.09.0+375 Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36, Quarto 1.5.57

- OS Version: Windows 10 Pro v. 10.0.19045 compilation 19045 x64 based PC

- R Version: R version 4.4.2 (2024-10-31 ucrt) -- "Pile of Leaves"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64

2) Yes, it works when presentations are stored in remote storage.

3) I'm adding a screenshot of the problem:
# Locally stored presentation
![image](https://github.com/user-attachments/assets/a3311bab-713e-4f4e-8d93-32350201f897)

# Remotely stored presentation
![image](https://github.com/user-attachments/assets/3239f295-d561-4eb3-9ecd-38c68e3331f4)
