### ISSUE TITLE
When opening RStudio, custom shortcut keys sometimes don't work. 

### ISSUE THREAD

**Issue by lijiaqi-github** [rstudio/rstudio#13817]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 Build 463
    OS Version      : Windows 11 Pro for Workstations 22H2 22621.2428
    R Version       : 4.3.1

### Steps to reproduce the problem
When opening RStudio, custom shortcut keys sometimes don't work. 

### Describe the problem in detail
For example, I defined F3 to run the code, but when I just opened RStudio, nothing happened when I pressed F3.

This problem has appeared since the last RStudio version, and custom shortcut keys worked fine before.

### Describe the behavior you expected
I'm not sure if it's my computer's slow response that's causing the problem. If anyone has the same problem, it's probably a bug, otherwise it's a problem with my own computer.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@lijiaqi-github Thank you for raising the issue! A couple of things:
1) Do the custom keyboard shortcuts sometimes work?
2) Is this a problem with all custom shortcuts?
3) Is the custom keyboard shortcut mapping showing up in these files?
```
C:\Users\USERNAME\AppData\Roaming\RStudio\keybindings\editor_bindings
C:\Users\USERNAME\AppData\Roaming\RStudio\keybindings\rstudio_bindings
```

**Comment by lijiaqi-github** [comment]
> @lijiaqi-github Thank you for raising the issue! A couple of things:
> 
> 1. Do the custom keyboard shortcuts sometimes work?
> 2. Is this a problem with all custom shortcuts?
> 3. Is the custom keyboard shortcut mapping showing up in these files?
> 
> ```
> C:\Users\USERNAME\AppData\Roaming\RStudio\keybindings\editor_bindings
> C:\Users\USERNAME\AppData\Roaming\RStudio\keybindings\rstudio_bindings
> ```

1. Do the custom keyboard shortcuts sometimes work?
Yes, they works well in most time, and doesn't work in rare cases in the latest version. I'm not sure if it's my imagination, but in the previous version , this issus occured and shortcuts often didn't work, but in the latest version, it happens less frequently.

2. Is this a problem with all custom shortcuts?
When this issue occurs, all custom shortcuts doesn't work. It's not the kind of situation where some shortcuts can work while others can't.

3. Is the custom keyboard shortcut mapping showing up in these files?
I found them in the file "rstudio_bindings", but not in the "editor_bindings".


C:\Users\USERNAME\AppData\Roaming\RStudio\keybindings\rstudio_bindings
```
{
    "executeCodeWithoutMovingCursor": "F3",
    "paste Last Yank": "",
    "commentUncomment": "F4"
}
```

C:\Users\USERNAME\AppData\Roaming\RStudio\keybindings\editor_bindings
`{}`

By the way, when I met this issus, I always opened the "Modify Keyboard  Shortcuts" in Tool tab, and clicked "Apply". Then the custom shortcuts will work.

I hope my description could help you make Rstudio better.

**Comment by ronblum** [comment]
OK, I'm going to use the exact same mapping and see if I run into the issue. Interesting that it's happening less.

**Comment by donboyd5** [comment]
FWIW, this seems related to #10422. I tried to find a way to reproduce it but did not succeed; I hypothesized that it seems to happen that adding or deleting a line sometimes seems to make shortcuts stop working.

**Comment by Huiqoo** [comment]
Whenever I reconnect to rstudioserver, all custom shortcut restore to default, the Keyboard shortcuts Help also show the default value.

**Comment by ronblum** [comment]
@donboyd5 No luck reproducing the issue—using the same keyboard mapping, `F3` always works for me, even when I add lines. @kevinushey do you have any suggestions of anything to look for?

@Huiqoo What version of RStudio Server are you using? And does the keyboard mapping show the custom or default value in <kbd>Tools -> Modify Keybaord Shortcuts</kbd>?

**Comment by Huiqoo** [comment]
> @donboyd5 No luck reproducing the issue—using the same keyboard mapping, `F3` always works for me, even when I add lines. @kevinushey do you have any suggestions of anything to look for?
> 
> @Huiqoo What version of RStudio Server are you using? And does the keyboard mapping show the custom or default value in Tools -> Modify Keyboard Shortcuts?

it's 2023.03.0+386 (Cherry Blossom) for Ubuntu Jammy. 
The keyboard mapping show the custom value, but it's doesn't work, until I press the **apply** bottom on the **Modify Keyboard Shortcuts** page.
![image](https://github.com/rstudio/rstudio/assets/79576123/f1cd0a75-2cc0-4fd1-8aa3-a8236733c365)

**Comment by donboyd5** [comment]
Hi, the issue rarely arises for me anymore. I opened it awhile ago and
only referenced it recently because someone else had raised it. I do
usually find that clicking Apply resolves it.

I'll make note of when it happens next and will add a new comment to the
issue.

Thanks.

**Comment by Huiqoo** [comment]
> > @donboyd5 No luck reproducing the issue—using the same keyboard mapping, `F3` always works for me, even when I add lines. @kevinushey do you have any suggestions of anything to look for?
> > @Huiqoo What version of RStudio Server are you using? And does the keyboard mapping show the custom or default value in Tools -> Modify Keyboard Shortcuts?
> 
> it's 2023.03.0+386 (Cherry Blossom) for Ubuntu Jammy. The keyboard mapping show the custom value, but it's doesn't work, until I press the **apply** bottom on the **Modify Keyboard Shortcuts** page. ![image](https://user-images.githubusercontent.com/79576123/279379738-f1cd0a75-2cc0-4fd1-8aa3-a8236733c365.png)

And the **Keyboard shortcuts Help** page show the default key values.
![image](https://github.com/rstudio/rstudio/assets/79576123/e0e9cc60-d751-4c27-9d9c-94912186aa4f)

**Comment by lijiaqi-github** [comment]
@ronblum 
I encountered this error again today. I took a video, and you can find the error that I want to show you.

In short, when I open Rstudio, my custom shortcut keys did not work. 

I updated R Version from 4.3.1 to 4.3.2 and RStudio Version to 2023.09.1 Build 494.

https://github.com/rstudio/rstudio/assets/107530058/cc669f96-3a01-46ce-a11d-b4a488c304eb

**Comment by lijiaqi-github** [comment]
https://github.com/rstudio/rstudio/assets/107530058/058a2c91-17e7-4fbf-8425-46b3dfd2b09a

**Comment by lijiaqi-github** [comment]
https://github.com/rstudio/rstudio/assets/107530058/2cef0cc6-a0a2-4129-9bb6-97a9e2af4fa9
