### ISSUE TITLE
Copilot agent not getting installed

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13821]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0-daily+201
    OS Version      : MacOS 14.1 and Windows 11
    R Version       : 4.3.1

### Steps to reproduce the problem

1. Remove the GitHub Copilot agent, if it's already installed.
2. Install the Copilot agent by enabling Copilot, or by using the command palette and search for "install agent".

### Describe the problem in detail

The agent is shown as downloading but not getting installed.

```
trying URL 'https://rstudio.org/links/github-copilot/998cf5ab1b85e844c7e8edb864a997e590df7182'
Content type 'application/x-gzip' length 4912451 bytes (4.7 MB)
==================================================
downloaded 4.7 MB

Error: Copilot Agent installation failed: '/Users/ronblum/.cache/rstudio/copilot/dist/agent.js' does not exist.
```

<img width="524" alt="Screenshot 2023-10-19 at 13 04 11" src="https://github.com/rstudio/rstudio/assets/31009952/f96435e1-4f41-4e8f-b386-3f6e57274f4f">

### Describe the behavior you expected

Agent installs and runs.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: This works in 2023.12.0-daily+170 but fails in build 196. I can pinpoint it further, if it'd be helpful.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+212 on MacOS 14.1.
- The download is now 4.7 MB (used to be 2 MB).
- Copilot suggestion are being provided.

**Comment by krishnakeshav** [comment]
I am getting this error in my setup -
RStudio Edition : Desktop
RStudio Version : 2023.09.1 Build 494
R - 4.3.2
OS - windows 10 x64
