### ISSUE TITLE
provide intermediate shell script for launching copilot

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13823]
So we can have some control over how the Copilot agent is launched, and better debug / confirm details about the process environment, and so on.

**Comment by kevinushey** [comment]
For testing, you could try something like the following in `/etc/rstudio/rsession.conf`:

```
copilot-agent-helper=/tmp/copilot.sh
```

Then, create a file at `/tmp/copilot.sh`, with the contents:

```
#!/usr/bin/env sh
exec "${RSTUDIO_NODE_PATH}" "${RSTUDIO_COPILOT_AGENT_PATH}"
```

Make sure it's executable as well, e.g.

```
chmod 755 /tmp/copilot.sh
```

Now, try using Copilot in the regular way. Everything should function as normal.

Next, try removing that `/tmp/copilot.sh` file. You should see that Copilot now fails to start, as the helper script no longer exists.

**Comment by jonvanausdeln** [comment]
@kevinushey,  I'm getting permission denied error on the shell script, even after setting permissions.

> jon@Ubuntu22:/etc/rstudio$ ll /tmp | grep issue
> -rwxrwxrwx  1 jon  jon     79 Nov 22 08:43 issue13823.sh*
> 
>jon@Ubuntu22:/etc/rstudio$ sudo rstudio-server stop
>
> jon@Ubuntu22:/etc/rstudio$ sudo rstudio-server start
> TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/var/log/rstudio/rstudio-server/rserver.log'.
>
> jon@Ubuntu22:/etc/rstudio$ cat rsession.conf 
> \# R Session Configuration File
> copilot-enabled=1
> copilot-agent-helper=/tmp/issue13823.sh

![image](https://github.com/rstudio/rstudio/assets/6433789/46fb8f24-f3c6-4693-bea2-ef73f56648cf)

**Comment by kevinushey** [comment]
Thanks for catching that -- some changes I made in a recent PR were somehow lost or left uncommitted. I've brought those back in; hopefully the next builds should work as I described originally.

**Comment by jonvanausdeln** [comment]
@kevinushey , I'm testing with [2023.12.0-daily+330](https://dailies.rstudio.com/version/2023.12.0-daily+330), and it does successfully use the script now. However, if I remove the script, restart the session.. it still successfully uses copilot.

<img width="634" alt="image" src="https://github.com/rstudio/rstudio/assets/6433789/4d0a8369-e402-4441-9d0c-f09ad17b63d7">

**Comment by kevinushey** [comment]
Thanks for catching that -- we were falling back to the default implementation whenever the copilot agent path didn't exist.

Next builds should handle this properly -- if the option is set, then we always try to use the agent helper; if it doesn't exist for some reason, we emit an error and stop.

**Comment by jonvanausdeln** [comment]
Verified with https://dailies.rstudio.com/version/2023.12.0-daily+336 server on Ubuntu22

Script now works as expected.
