### ISSUE TITLE
YAML chunk option syntax highlighting doesn't process multi-line chunk options

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#13828]
In RStudio 2023.12.0-daily+170, create a new Quarto document with the following contents

~~~~
---
title: "Untitled"
format: html
---

```{r}
#| fig-cap: "A long long caption."
```

```{r}
#| fig-cap: "A long long 
#|    long long caption."
```

```{r}
#| fig-cap: |
#|  A long long long long caption.
```

```{r}
#| fig-cap: >
#|  A long long long long caption.
```
~~~~

Oh look, we implemented syntax highlighting for in-body yaml chunk options! But unfortunately, the highlighting doesn't seem to work for multi-line chunk options, which are well supported. See the following:

<img width="839" alt="image" src="https://github.com/rstudio/rstudio/assets/7817881/03b7ab98-a7e3-4473-a70e-514fbb27b4e8">

I expect syntax highlighting to work the same whether a single chunk option is written in a single line, or split across several lines, each of which are prefaced by the chunk option prefix (`#| `) 

Originally reported by mine

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+306](https://dailies.rstudio.com/version/2023.12.0-daily+306)
Windows 11

YAML is highlighted correctly.
