### ISSUE TITLE
Add "First Plot" and "Last Plot" buttons and menu items for Plots panel

### ISSUE THREAD

**Issue by FletcherCory** [rstudio/rstudio#13830]
It would be very useful to have "First Plot" and "Last Plot" buttons and menu items for the Plots panel in addition to the current "Previous Plot" and "Next Plot". For example, I frequently output 50+ plots at a time when doing certain analyses and have to manually scroll back through each previous plot every time to get to the first one.

**Comment by ronblum** [comment]
@FletcherCory Thank you for raising this request! We'll consider it as we continue development of RStudio.
