### ISSUE TITLE
Quarto chunk options not highlighted properly and do not show in code outline, but are processed properly by quarto

### ISSUE THREAD

**Issue by donboyd5** [rstudio/rstudio#13831]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0 Build 221
    OS Version      : Windows 11 64 bit
    R Version       :  4.3.1

RStudio 2023.12.0-daily+221 "Ocean Storm" Daily (6405c6ecd83217409d7fb153474284c8106eed8b, 2023-10-20) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0-daily+221 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Steps to reproduce the problem

create a new .qmd file

In source mode, create a chunk such as:

```{r}
#| label: test
#| include: true
#| eval: true

print("hello")

```
save the file

### Describe the problem in detail

Look at the RStudio code outline. Note that instead of seeing the label "test" in the outline you will see chunk 1
Look at the chunk code. The colors will not be right.
Render with quarto. Note that it works properly.

Note that this problem only occurs with the daily builds. A released version does not have this problem.

**I am not sure if you want bug reports for daily builds but I wasn't sure where else I should report this. It is not a problem with a released version of RStudio.**

### Describe the behavior you expected

Expected code-outline label to be "test".
Expected chunk options to be highlighted properly.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Thank you for raising this @donboyd5! We'll review this as we continue development of RStudio. And we definitely  want feedback on dailies, as it helps us with bugs before we release.

Reproducible regression:
- RStudio Desktop 2023.9.1.494 on MacOS 14.1.: Works correctly
- RStudio Desktop 2023.12.0-daily+223 on MacOS 14.1: Fails
Also, this is only an issue in source mode, but works correctly in visual mode.

**Comment by kevinushey** [comment]
Should be fixed in the upcoming daily builds: <img width="253" alt="Screenshot 2023-11-06 at 2 26 20 PM" src="https://github.com/rstudio/rstudio/assets/1976582/185b55dd-6757-4734-8040-ed97da1ffdcc">

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+274](https://dailies.rstudio.com/version/2023.12.0-daily+274)
Windows 11

Chunks show up correctly in navigation.

**Comment by donboyd5** [comment]
Thanks! I noticed that it was fixed, and I appreciate it. Don
