### ISSUE TITLE
Click on file (not *.R) in File pane does not open it if file name in cyrillic

### ISSUE THREAD

**Issue by ariel32** [rstudio/rstudio#13835]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1 Build 494
    OS Version      : Windows 10 Pro x64
    R Version       : R version 4.3.0 (2023-04-21 ucrt)

### Steps to reproduce the problem
Open in File pane any folder with files, some filenames in english, some with cyrillic.
![image](https://github.com/rstudio/rstudio/assets/7060961/d1929e97-90f9-462b-b5bf-94fc909f1bb1)

### Describe the problem in detail
If I click on file with name 'тест.docx' nothing happens. But click on 'test.docx' opens it. 

### Describe the behavior you expected
File opens in Word.

I attached empty word file with russian name:
[тест.docx](https://github.com/rstudio/rstudio/files/13113802/default.docx)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ariel32 Thank you for raising the issue! I can reproduce this in RStudio Desktop 2023.06.2+561 on Windows 11. It works correctly in 2022.07.2+576, as well as on MacOS 14. Also tested with Chinese, `测试.rtf`.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+266](https://dailies.rstudio.com/version/2023.12.0-daily+266)
Windows 11

Files open as expected from files pane.
