### ISSUE TITLE
Environmental variables are `NOT` case sensitive on Windows.

### ISSUE THREAD

**Issue by Lovekumarpatel** [rstudio/rstudio#13834]
Hello, 

Thanks for providing wonderful IDE. I have been using it since six years. It works fantastic and latest integration with other programming languages makes it really easy to put all things at one place. 

### System details

**1. macOS**
    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2023.06.2+561 "Mountain Hydrangea" Release (de44a3118f7963972e24a78b7a1ad48b4be8a217, 2023-08-25) for macOS
     R version 4.3.1 (2023-06-16)
     Platform: x86_64-apple-darwin20 (64-bit)
    Running under: macOS Sonoma 14.0
    
 **2. Windows** 
    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2023.06.2+561 "Mountain Hydrangea" Release (de44a3118f7963972e24a78b7a1ad48b4be8a217, 2023-08-25) for windows
    R version 4.3.1 (2023-06-16 ucrt)
   Platform: x86_64-w64-mingw32/x64 (64-bit)
   Running under: Windows 10 x64 (build 19045)
    
### Steps to reproduce the problem 

**1. macOS**
```
Sys.setenv(TEST = "test")
Sys.getenv("TEST")
Sys.getenv("Test")
```
![Screenshot 2023-10-23 at 4 20 51 PM](https://github.com/rstudio/rstudio/assets/33581114/6db11971-491a-473d-859c-7a45b18a159e)
**2. Windows**
```
Sys.setenv(TEST = "test")
Sys.getenv("TEST")
Sys.getenv("Test")
```
![Screenshot 2023-10-23 at 4 22 01 PM](https://github.com/rstudio/rstudio/assets/33581114/62299214-508a-4528-bc36-0fe2f201a621)

### Problem
Recently, I was working with one of my client in windows system. I noticed something weird, on macOS/Linux R system environment variables are case sensitive whereas on windows it's not. 

Problem arise when I deployed plumber API which uses environmental variables on posit connect, it didn't work. When I performed code review, I found that it was indeed environment variables issue. I attached system details and reprex of both system above.

We generally follow best practices by creating all environment variables uppercase and separated by "_", however, this is something I think it needs to be addressed or documented. 

### Expectation

Windows should be case-sensitive just like a linux and windows. Expected `""` output instead I get value.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the [issue.](

**Comment by ronblum** [comment]
@Lovekumarpatel Thank you for raising this! This is expected behavior, which RStudio inherits from R—you'll get the same results with `Sys.setenv` inside R running in a terminal outside of RStudio. Even though R variables are case-sensitive regardless of the operating system, the difference is because on system variables on Windows aren't case sensitive, while they are on MacOS and Linux. 

And thank you for the kind words! I'll pass this on to the rest of the team. 😃
