### ISSUE TITLE
RStudio feature request: run the selection as one expression i.e. inside the curly braces {...}

### ISSUE THREAD

**Issue by alekrutkowski** [rstudio/rstudio#13848]
Currently, when you select multiple expressions and run the selection in the console, the second and subsequent expressions are still evaluated even if the first one fails with an error. Often, it doesn't make sense, since the the expressions are sequenced so that the subsequent expressions depend of the prior ones being evaluated successfully. This results in a messy console with multiple errors and makes it difficult to find the original error.

Wrapping the whole selection on-the-fly with curly braces (`{}`) before pasting it in the console and executing it (to make it a one big ad-hoc temporary expression) will be enough to make R stop and not run all the following sub-expressions if any single one of them results in an error. I suggest to add this option to the plain old "run the selection" (Ctrl + Enter).

# Example:

## Current behaviour after "run selection":

Assume the selected source code:

```r
a <- stop('a cannot be calculated')
a + b
```

Result:

```
> a <- stop('a cannot be calculated')
Error: a cannot be calculated
> a + b
Error: object 'a' not found
```

## Requested behaviour for the new "run selection as expression":

Assume the selected source code (same as before):

```r
a <- stop('a cannot be calculated')
a + b
```

However, now executed as:

```r
{
a <- stop('a cannot be calculated')
a + b
}
```

Cleaner result:

```
> {
+ a <- stop('a cannot be calculated')
+ a + b
+ }
Error: a cannot be calculated
```

**Comment by jmcphers** [comment]
> when you select multiple expressions and run the selection in the console, the second and subsequent expressions are still evaluated even if the first one fails with an error.

This is an option you can change! If you check the box "Discard pending console input on error":

<img width="631" alt="image" src="https://github.com/rstudio/rstudio/assets/470418/c914a700-c971-42bd-8375-6b1e48bbe1a9">

then I think it does what you want?

<img width="273" alt="image" src="https://github.com/rstudio/rstudio/assets/470418/b7c6d84e-c110-44e1-9391-98fdb7b9e321">

**Comment by alekrutkowski** [comment]
Thanks for the hint. At work, I have RStudio version 1.4.1717, which doesn't include that option (screenshot). Apparently, it has been introduced in a more recent version.
<img src="https://github.com/rstudio/rstudio/assets/7509427/24d76d13-df98-4c9b-9ada-e814a491c391" width="70%" />
