### ISSUE TITLE
Improve error message for connecting to package repositories 

### ISSUE THREAD

**Issue by pyltime** [rstudio/rstudio#13842]
When connecting to a new repository via the Global Options > Packages pane, any issue connecting to the repository will give this error "The given URL does not appear to be a valid CRAN repository":
![image](https://github.com/rstudio/rstudio/assets/2779342/db167261-cdbf-4fdb-bef5-d0218311772c)

However, this error message can be misleading, as you will see the same error message for several potential circumstances:

1. there is a network error preventing a connection to the given URL (this was the case for the screenshot above)
2. the given URL can be connected to, but is not a CRAN repository at all
3. the given URL can be connected to and is a CRAN repository, but is not correctly configured

Since all of these have different potential causes, it would help if instead of outputting a single error message, the IDE could be more explicit about the problem it's encountering, whether it's due to a network connectivity issue or not, and even surface the exact error it's receiving when attempting to query the repository so that the user can troubleshoot more accurately.

**Comment by ronblum** [comment]
No error message appears at all now. Very briefly a message appears that says "Validating CRAN repository" but it quickly goes away and nothing else appears. We should show an error message, but relevant to the cause.

Checked on both RStudio Desktop 2024.4.0+475 and RStudio Server 2024.4.0+469.
Checked both with no network connection and with an invalid repository URL.

**Comment by kevinushey** [comment]
@ronblum can you please provide more details? It works for me:

<img width="692" alt="Screenshot 2024-02-22 at 12 23 34 PM" src="https://github.com/rstudio/rstudio/assets/1976582/3da88229-0e37-416d-af70-72192aeb9d66">

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/assets/1976582/877c80ed-9d43-478e-abde-2d06b18ca0a4

**Comment by ronblum** [comment]
I see it in action now, using RStudio Desktop 2024.04.0-daily+544 on MacOS 14.4 and Posit Workbench 024.04.0-daily+531.pro9 on Ubuntu 22 via Chrome on MacOS 14.4.
