### ISSUE TITLE
set the rmd directory to follow Rproject

### ISSUE THREAD

**Issue by binchen19** [rstudio/rstudio#13845]
I once set the 'evaluate chunks in directory - document/project' in global options. But after updating my R studio, i could not find it. any thoughts on this?

**Comment by ronblum** [comment]
@binchen19 Is this what you're looking for?
<img width="443" alt="directory" src="https://github.com/rstudio/rstudio/assets/31009952/51bb5e77-2be3-47e1-86b2-b7d775053ee1">

If so, it's the little upside-down triangle next to the right of the "Knit" button.

**Comment by binchen19** [comment]
> @binchen19 Is this what you're looking for? <img alt="directory" width="443" src="https://private-user-images.githubusercontent.com/31009952/278353107-51bb5e77-2be3-47e1-86b2-b7d775053ee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTI4OTcsIm5iZiI6MTcyMDQxMjU5NywicGF0aCI6Ii8zMTAwOTk1Mi8yNzgzNTMxMDctNTFiYjVlNzctMmJlMy00N2UxLTg2YjItYjdkNzc1MDUzZWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA0MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NWIzMDViOTQyMjM3NDhiZDMwZTE5ZWMyYWU1MzY1NTczYjYzYzY2ZDBhYjE2Nzk0N2EzMGY3MGYwODc2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VMhKWTD6l8RxpQet8IwoNOZ3pihdhgPbVlVW9aEE-0">
> 
> If so, it's the little upside-down triangle next to the right of the "Knit" button.

Yes! Thank you so much!
