### ISSUE TITLE
Cannot select text in the editor

### ISSUE THREAD

**Issue by entropic-janosch** [rstudio/rstudio#13847]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.09.1+494 "Desert Sunflower" Release (cd7011dce393115d3a7c3db799dda4b1c7e88711, 2023-10-16) for windows - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
    OS Version      : Windows 11 Home, Version: 22H2, OS build: 22621.1344
    R Version       : 4.3.1 (2023-06-16 ucrt)

### Steps to reproduce the problem
The problem occurs immediately, from opening any script in RStudio I cannot select text in the source editor. Please let me know how I could make this reproducable.

### Describe the problem in detail
I recently got a new laptop, switching from an old Lenovo to a ThinkPad E16 Gen1. I've been working on an R project on my old computer and thought I would just copy my folder and continue as usual with more computing power. As soon as I opened my old file on my new computer I realised I cannot select any text in the editor, the curser just sort of swims through the signs ([like this](https://user-images.githubusercontent.com/104391/54929976-d1c35a80-4eec-11e9-9f5e-004e5dcb1ab4.gif)). It's impossible to work like this. The issue is similar [to this one](https://github.com/rstudio/rstudio/issues/13436), but instead of happening sporadically, it is just the default now. I tried everything suggested in this threat too (switching the mouse, reload), but it didn't change anything.

Things I have already tried:
- checked if the problem is in R or R Studio: it's only in R Studio
- tried with the newest as well as legacy versions of R and R Studio
- changed the theme according to [this threat](https://github.com/rstudio/rstudio/issues/4488)
- reset the desktop state by renaming the folders at "%localappdata%\RStudio" and "%appdata%\RStudio" according [to this](https://community.rstudio.com/t/cannot-select-text-in-rstudio-desktop/37776)
- used an old project and a completely new file

Now I can't find anymore tips anywhere on what else to do, and due to working on a new computer I can't really go back to anything when it worked, hence the report.

### Describe the behavior you expected
To be able to select any part of text/code in the source editor.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@entropic-janosch Thank you for raising this! A few questions:
1) Does occur in both source and visual modes?
2) Are you able to select in other panes, like the Console and Help Panes?

**Comment by olivroy** [comment]
It happens sometimes to me too. (Source mode mostly)

I cannot isolated the behavior, but it seems that the editor can lose focus. I use Alt + - to insert `<-` in a script sometimes, and it doesn't work. I find that repeated `<-` call in another script sometimes?

Can't reproduce or pinpoint exactly what is going on, but it seems to happen a lot lately, both on macOS and Windows.

I have to use Right Click + Reload a couple times a day usually.

**Comment by entropic-janosch** [comment]
Thank you for the replies! After restarting a couple more times and changing themes more times it seems to be solved for now actually, at least the behaviour disappeared after a full day of this not working, and while that's not very satisfying as I have no idea what happened, I'll close this issue for now and hope it doesn't return.
