### ISSUE TITLE
RStudio IDE hangs / crashes on startup when rendering very large console outputs

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13857]
We had one user whose RStudio IDE session would freeze, and then crash, on startup. After analysis, it appeared to be due to an overly-large amount of text in the Console history -- the `console_actions` file had:

```
$ ll | grep console_actions
-rw-rw-r--   1 kevin  staff    34M Oct 27 14:22 console_actions
```

So, I suspect the IDE barfed when trying to shove 34MB of text into the Console history.

In this case, the large output was produced by `knitr::kable(<large data>, format = "html")` so that might be useful for making a reproducible example.

**Comment by kevinushey** [comment]
To reproduce, with RStudio Server -- first, create an R file with the contents:

```
library(nycflights13)
knitr::kable(flights, format = "html")
```

Then, execute that code, and wait for the output to be printed in the console. Then, suspend the R session.

Now, come back and reload the tab. RStudio will start attempting to load, and then barf as it tries to load 296MB of Console history 🤮

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/blob/ad0e5854c7a0abed5728c476ec3611f458e52d82/src/cpp/r/session/RConsoleActions.cpp#L95-L111

Perhaps we should split outputs by newlines, or do some other kind of chunking for overly-large outputs? The problem here is that we try to serialize all of the HTML (newlines included!) as one single enormous string; if we instead split on newlines and dropped earlier pieces of output, we'd be in much better shape.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+313](https://dailies.rstudio.com/version/2023.12.0-daily+313)
Ubuntu22 

IDE doesn't hang nor crash
