### ISSUE TITLE
isJob() returns false for Workbench Jobs

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13852]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.09.1
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

Start a Background job that prints `rstudioapi::isJob()` and then a Workbench Job that prints `rstudioapi::isJob()`.

The background job will return TRUE while the Workbench Job will return FALSE

x-link from `rstudioapi`: https://github.com/rstudio/rstudioapi/issues/287

### Describe the problem in detail

In Workbench, as far as I can tell with my testing, `isJob()` returns `TRUE` only when used as Background Job and return FALSE when executed in a Workbench Job.

Could we modify the check so that it also returns `TRUE` when called from within a Workbench Job?

One example was a customer asking for how to have different behavior when run in dev (local interactive session) and use different data for example when run in a Workbench Job in a much lager scaled session.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
> One example was a customer asking for how to have different behavior when run in dev (local interactive session) and use different data for example when run in a Workbench Job in a much lager scaled session.

For what it's worth, I suspect they could also detect this in an ad-hoc way with something like:

```
is.na(Sys.getenv("RSTUDIO", unset = NA))
```

Since the `RSTUDIO` environment variable will be set within the main R session, as well as within background jobs, but not within workbench / launcher jobs.

**Comment by kevinushey** [comment]
Should be ready for testing in the next Pro daily builds, but you'll need the development version of `rstudioapi`:

```
remotes::install_github("rstudio/rstudioapi")
```

**Comment by jthomasmock** [comment]
Awesome progress!

**Comment by ronblum** [comment]
Verified in Posit Workbench 2024.04.0-daily+367.pro2 on Ubuntu 22.04.3.  Checked that works correctly with workbench jobs both Kubernetes and local launcher, and double-checked that background jobs were unaffected.

Leaving this open to double-check once `rstudioapi` is published.

**Comment by ronblum** [comment]
Verified using public release 0.16.0 of `rstudioapi`. Using the code

```
print(packageVersion("rstudioapi"))
print(c("isJob", rstudioapi::isJob()))
print(c("isBackgroundJob", rstudioapi::isBackgroundJob()))
print(c("isWorkbenchJob", rstudioapi::isWorkbenchJob()))
```

we get:

*Background (local) job*
```
[1] ‘0.16.0’
[1] "isJob" "TRUE" 
[1] "isBackgroundJob" "TRUE"           
[1] "isWorkbenchJob" "FALSE"  
```

*Workbench job*
```
[1] '0.16.0'
[1] "isJob" "TRUE" 
[1] "isBackgroundJob" "FALSE"          
[1] "isWorkbenchJob" "TRUE" 
```

*Source (not a job)*
```
> print(packageVersion("rstudioapi"))
[1] ‘0.16.0’
> print(c("isJob", rstudioapi::isJob()))
[1] "isJob" "FALSE"
> print(c("isBackgroundJob", rstudioapi::isBackgroundJob()))
[1] "isBackgroundJob" "FALSE"          
> print(c("isWorkbenchJob", rstudioapi::isWorkbenchJob()))
[1] "isWorkbenchJob" "FALSE"
```
