### ISSUE TITLE
RStudio fails to detect modified deployment records

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13855]
The IDE can also show stale deployment records after they have been modified or removed using `rsconnect::syncAppMetadata()` and `rsconnect::forgetDeployment()`.

_Originally posted by @aronatkins in https://github.com/rstudio/rstudio/issues/12707#issuecomment-1783178535_

**Comment by kevinushey** [comment]
We could probably use our file monitor to detect changes within the project's `rsconnect` folder, and then update / rebuild the deployment button whenever such a change is detected.

**Comment by kevinushey** [comment]
For testing, create a new RStudio project, and then create a new R Markdown document (the default content in fine). Save that document, and then publish it to a Posit Connect server.

After the document has been successfully published, return to RStudio, and click the small dropdown button near the publish button. You should see the published document in that list.

<img width="189" alt="Screenshot 2024-03-26 at 11 24 04 AM" src="https://github.com/rstudio/rstudio/assets/1976582/0375b748-b81c-465a-8e8c-35c9ebca43da">

Then, use `rsconnect::forgetDeployment()` to tell `rsconnect` to forget that deployment. Now, click the small dropdown button near the publish button again. You not see any more publications in the dropdown.

<img width="194" alt="Screenshot 2024-03-26 at 11 25 03 AM" src="https://github.com/rstudio/rstudio/assets/1976582/5bcbf234-cdc0-4cd0-aa7e-225378bd8e72">

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+668 on Windows 11, using the above info.

- Checked multiple types, including an individual Rmd and a Quarto website.
- Deleting `rsconnect` directory clears the list.
- `rsconnect::forgetDeployment()` deletes the `rsconnect` directory and clears the list.
- Clicking on "Clear List" deletes the `rsconnect` directory and clears the list.
- List is cleared in Editor Pane, Viewer Pane, and external window.
- Button in external window changes from "Republish" to "Publish" 

@aronatkins I would not be offended if you took a look at this and confirmed, as well. 🙂

**Comment by aronatkins** [comment]
Testing using 2024.04.0-daily+672 on macOS 14.4.1. The list appears to be kept in sync with the rsconnect records. It is possible to see the list out of sync, but only in the brief window of time after running some console command.

I cannot recall how to adjust which item receives the "check" indicating the default push-button target, but it always appears to be the first one on the list, now. Is the checked item supposed to be the last item that was push-button deployed?

## Sync

1. Publish Shiny application.
2. Delete remotely.
3. `rsconnect::syncAppMetadata()` - deletes local metadata
4. Confirm IDE deployment list is cleared.

## Multiple, updated individually

1. Publish Shiny application using three separate names.
2. Confirm IDE deployment list contains all three.
3. Delete one item remotely and use `rsconnect::syncAppMetadata()`. Confirm IDE list is updated.
4. Delete one item locally using `rsconnect::forgetDeployment(name="shiny-app-the-third", ...)`. Confirm IDE list is updated.
