### ISSUE TITLE
CNTRL+ENTER automatically Views a matrix

### ISSUE THREAD

**Issue by canderson318** [rstudio/rstudio#13856]
### System details

    RStudio Edition : Desert Sunflower

    RStudio Version :RStudio 2023.09.1+494 "Desert Sunflower" Release (cd7011dce393115d3a7c3db799dda4b1c7e88711, 2023-10-16) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

    OS Version      : macOS Sonoma 14.0

    R Version       :  4.3.1 (2023-06-16)

### Steps to reproduce the problem

rm(list = ls())
gc()

library(tidyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyverse)
library(ggpubr)
library(vcd)
library(UpSetR)
library(gridExtra)
library(ComplexHeatmap)
library(viridis)
library(BiocGenerics)
library(mice)
library(Metrics)
library(purrr)
library(SingleCellExperiment)
library(corrplot)

m <- matrix(1, 10, 10)
m <- m %>% t()

### Describe the problem in detail

When running a function on a matrix or dataframe using CNTRL+ENTER, R will sometimes View() the object. This switches to the new data viewer tab away from the script I am working on.  

### Describe the behavior you expected

I expect the function to run without Viewing the result. If I want to View() the object, I expect to have to write that explicitly. 

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
A smaller reproducible example:

```
m <- matrix(1:4, nrow = 2)
View(m)
m <- matrix(5:8, nrow = 2)
```

**Comment by kevinushey** [comment]
Appears to be coming from here: https://github.com/rstudio/rstudio/blob/f8b868fddad91b2c0fa3ce74f6d67d639b84e074/src/cpp/session/modules/data/DataViewer.cpp#L1125-L1127

**Comment by kevinushey** [comment]
I think instead of calling `View` explicitly from the backend there, we need to let the front-end decide if the current view needs to be re-generated.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+313](https://dailies.rstudio.com/version/2023.12.0-daily+313)
Windows 11 (Rstudio Desktop), Ubuntu 22 (Rstudio Server)

View tab no longer opens unnecessarily.

**Comment by canderson318** [comment]
thanks!
