### ISSUE TITLE
Missing Node-Binary for GitHub Copilot

### ISSUE THREAD

**Issue by felixhoffmnn** [rstudio/rstudio#13865]
### System details

    RStudio Edition: Desktop
    RStudio Version: 2023.09.1+494
    OS Version: Fedora 38 (Kernel Linux 6.5.8-200.fc38.x86_64)
    R Version: 4.3.1

### Steps to reproduce the problem

1. Install `R` on Fedora
2. Install RStudio using `dnf install rstudio-desktop`
3. Activate GitHub Copilot in the settings

> Note: I have installed `node@v20.0.0` systemwide

### Describe the problem in detail

- After activating GitHub Copilot, RStudio is trying to start the service
- Due to a missing `node` binary, the service cannot be started

**Logs:**

```
[...]
2023-10-30T22:54:16.906909Z [rsession-felixhoffmnn] ERROR system error 2 (No such file or directory) [path: /usr/libexec/rstudio/../../dependencies/common/node/16.20.2/bin/node]; OCCURRED AT rstudio::core::Error rstudio::session::modules::copilot::{anonymous}::findNode(rstudio::core::FilePath*, rstudio::core::system::Options*) src/cpp/session/modules/SessionCopilot.cpp:290; LOGGED FROM: bool rstudio::session::modules::copilot::{anonymous}::startAgent() src/cpp/session/modules/SessionCopilot.cpp:581
2023-10-30T22:54:40.333006Z [rsession-felixhoffmnn] ERROR system error 2 (No such file or directory) [path: /usr/libexec/rstudio/../../dependencies/common/node/16.20.2/bin/node]; OCCURRED AT rstudio::core::Error rstudio::session::modules::copilot::{anonymous}::findNode(rstudio::core::FilePath*, rstudio::core::system::Options*) src/cpp/session/modules/SessionCopilot.cpp:290; LOGGED FROM: bool rstudio::session::modules::copilot::{anonymous}::startAgent() src/cpp/session/modules/SessionCopilot.cpp:581
[...]
```

### Related Issues

A few issues describe similar behavior. However, those only use Windows and macOS.

- #13445
- #13732
- #13751

> If this issue is redundant based on the listed issues, feel free to close this issue.

### Describe the behavior you expected

The service should start and provide code completion. Also, I would expect that the required `node` version is shipped with RStudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
> Also, I would expect that the required node version is shipped with RStudio.

It is. We don't maintain the builds of RStudio shipped with Fedora, so presumedly something needs to be adjusted in the build.

@Enchufa2, would you be willing to take a look?

**Comment by Enchufa2** [comment]
Sure! When I packaged this version, I read somewhere (I just cannot find it now) that, the same as pandoc or rpostback, several paths were valid, so I just created a symlink `<rstudio_installation_directory>/bin/node`. And since the `src/cpp/session/session-options.json` file defines `"defaultValue": {"code": "kDefaultNodePath", "description": "bin/node"}`, I hoped that worked. Or should the symlink be `<rstudio_installation_directory>/bin/node/node`?

**Comment by kevinushey** [comment]
I believe it should be `bin/node/bin`; at least, that's what the structure is like for an Ubuntu Server installation:

```
kevin@KUBOX:/usr/lib/rstudio-server/bin/node/bin
$ ll
total 79M
drwxr-xr-x 2 root 4.0K Oct 24 11:30 ./
drwxr-xr-x 6 root 4.0K Oct 24 11:30 ../
lrwxrwxrwx 1 root   45 Oct 23 14:11 corepack -> ../lib/node_modules/corepack/dist/corepack.js*
-rwxr-xr-x 1 root  79M Aug  8 15:29 node*
lrwxrwxrwx 1 root   38 Oct 23 14:11 npm -> ../lib/node_modules/npm/bin/npm-cli.js*
lrwxrwxrwx 1 root   38 Oct 23 14:11 npx -> ../lib/node_modules/npm/bin/npx-cli.js*
lrwxrwxrwx 1 root   36 Oct 23 14:11 yarn -> ../lib/node_modules/yarn/bin/yarn.js*
lrwxrwxrwx 1 root   36 Oct 23 14:11 yarnpkg -> ../lib/node_modules/yarn/bin/yarn.js*
```

**Comment by Enchufa2** [comment]
This is what I was talking about: https://github.com/rstudio/rstudio/blob/15fe980f7002d0d5a026127961117c9e2c3e1d5a/src/cpp/session/modules/SessionCopilot.cpp#L267-L268

But I think that the issue comes from `resolveNodePath`. Let me investigate.

**Comment by Enchufa2** [comment]
Yes, the issue was that we don't set `RSTUDIO_PACKAGE_BUILD`

https://github.com/rstudio/rstudio/blob/15fe980f7002d0d5a026127961117c9e2c3e1d5a/src/cpp/session/SessionOptions.cpp#L706-L715

So I just patched that ifdef out. This should be fixed in [this update](https://bodhi.fedoraproject.org/updates/FEDORA-2023-45f77a6077) that will be pushed to testing soon. You can close this issue.

**Comment by felixhoffmnn** [comment]
I installed the patch and it works! Thanks for the quick response :+1:

**Comment by kevinushey** [comment]
Thanks @Enchufa2 -- much appreciated!
