### ISSUE TITLE
[find in files] Refresh find button is not disabled when stop replace is visible, allowing the user to crash RStudio

### ISSUE THREAD

**Issue by jgutman** [rstudio/rstudio#13873]
In Find in Files, if I run a find and then replace all,  I can crash RStudio by hitting the refresh button while a replace event is happening.  

We disable the refresh button and replace it with a stop button while a find is in progress, but we don't do that while a replace is in progress, instead we create a stop replace button but the refresh button remains clickable. If you click on the refresh button while stop replace is visible and a replace is in progress, then BOOM

_Originally posted by @jgutman in https://github.com/rstudio/rstudio/pull/13871#pullrequestreview-1707141318_

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+116 on Windows 11. Tested by checking out a repository with hundreds of files and searching for and replacing the letter "r" to allow enough time to catch the buttons.
