### ISSUE TITLE
The devcontainer.json cannot be built because the AWS URL is not available.

### ISSUE THREAD

**Issue by trukhinyuri** [rstudio/rstudio#13889]
<img width="800" alt="image" src="https://github.com/rstudio/rstudio/assets/1245379/cf1ceb83-59ae-4d72-b03c-6a1ad0badf97">
The devcontainer.json cannot be built because the AWS URL is not available.

**Comment by ronblum** [comment]
@trukhinyuri Thank you for raising this! We're no longer supporting dev container for this anymore—sorry for the confusion. I'm impressed that you found this, though. 🙂 

Keep this open: We should remove these files to avoid confusion since this isn't supported.

**Comment by gtritchie** [comment]
This devcontainer is no longer usable for open-source RStudio, unfortunately. I will be removing it (but will need to make sure we don't stomp the devcontainer in the pro-repo, as that is still useful internally).

**Comment by gtritchie** [comment]
Removed via https://github.com/rstudio/rstudio/pull/14221.
