### ISSUE TITLE
Header of save file dialog is clipped after scrolling to bottom entry

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13895]
### System details

    RStudio Edition : Server [Open Source]
    RStudio Version : 2023.11.999.999
    OS Version      : macOS Sonoma 14.1
    R Version       : R version 4.3.1 (2023-06-16)

### Steps to reproduce the problem

Try to save an unsaved file, and then scroll to the last entry in the list of files.

<img width="538" alt="Screenshot 2023-11-06 at 1 49 07 PM" src="https://github.com/rstudio/rstudio/assets/1976582/6886a317-5c98-4ddc-bf33-2b55ee828b61">

### Describe the problem in detail

The header is collapsed a bit.

### Describe the behavior you expected

Header should remain same size.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+266](https://dailies.rstudio.com/version/2023.12.0-daily+266)
Ubuntu22 Server, Windows 11 & MacOS Client

I didn't see any clipping
