### ISSUE TITLE
[DRAFT] CoPilot - agent needed reinstalling after installing the latest 274 daily rstudio desktop build on Windows 10

### ISSUE THREAD

**Issue by slodge** [rstudio/rstudio#13906]
After testing for https://github.com/rstudio/rstudio/issues/13717 I noticed that CoPilot seemed to be stuck on "waiting for completions"

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0 Build 274 downloaded from dailies:
    OS Version      : Tested on Windows 10 
    R Version       : 4.3.0

### Steps to reproduce the problem

I had 266 installed and CoPilot was working (I think)
This morning I installed 274 to test the fix in #13717
Noticed (some time later) that CoPilot wasn't providing completions
Tried disabling/enabling CoPilot using Ctrl+Shift+P
Looked at the CoPilot settings in GlobalSettings - it asked me to install the CoPilot Agent.
After installing the CoPilot Agent then everything worked again (the agent knew I was already signed in)

### Describe the problem in detail

See above

### Describe the behavior you expected

I normally experience no problems with RStudio upgrades - things normally just continue working.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] - **Not yet tried to repro - got a work deadline right now** - I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] - **Not Applicable** If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] - **Not yet tried to repro - got a work deadline right now** - I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Sorry about that -- we relocated the Copilot installation directory. Normally we should be able to migrate the installation seamlessly, but if that fails you may need to reinstall Copilot manually.

**Comment by slodge-work** [comment]
Phew - I didn't imagine it.

Glad I didn't have to try to repro it too :)
