### ISSUE TITLE
Environemental panel: Number of observations displayed as ??

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#13907]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.09.2+508 "Desert Sunflower"
    OS Version      : Windows 10
    R Version       : 4.3.2

### Steps to reproduce the problem

Create the following data.frame and check the environment panel.

```r
d2 <- data.frame(x = 1:2, row.names = 1:2)
```

It will be displayed like this:
![image](https://github.com/rstudio/rstudio/assets/28725410/7f29446f-7d6f-43d9-adab-9f5a32c7876f)

### Describe the problem in detail

The number of observations is displayed as ?? instead of 2.

### Describe the behavior you expected

The number of observations displayed as two.

Note that all the following examples give the expected result:
```r
d1 <- data.frame(x = 1, row.names = 1L)
d2a <- data.frame(x = 1:2, row.names = c("a", "b"))
d2b <- data.frame(x = 1:2)
d3 <- data.frame(x = 1:3, row.names = 1:3)
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Bug is here:

https://github.com/rstudio/rstudio/blob/8244ebc49cc3188f04aa26bb2c2377aeda315817/src/cpp/session/modules/environment/SessionEnvironment.cpp#L440-L448

We need to check for NA when checking for compact row names.

**Comment by kevinushey** [comment]
I misdiagnosed the issue a bit previously. The issue here is that we try to avoid materializing so-called ALTREP vectors, which was done as part of https://github.com/rstudio/rstudio/pull/13544. I'll see if I can narrow down how we check `duckdb` here.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+313](https://dailies.rstudio.com/version/2023.12.0-daily+313)
Windows 11, Ubuntu 22

Number of observations are displayed correctly.
