### ISSUE TITLE
Header and footer updates

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#13909]
Updates to User Guide and Release Notes:

- Replace Versions drop-down with Version link to Previous Versions page on docs.posit.co (we are forgetting to update these so linking to the Previous Versions page is safer)
- Per doc team and product marketing, remove "posit" logo from header and add to the footer:
https://positpbc.atlassian.net/wiki/spaces/ENG/pages/455639067/docs.posit.co+header+link+to+posit.co
- Replace "house" icon in header with book icon for docs.posit.co
- Remove "house" icon from footer

Related to rstudio-pro issue: https://github.com/rstudio/rstudio-pro/issues/5376

**Comment by jonvanausdeln** [comment]
All the updates look good to me!
