### ISSUE TITLE
RStudio crashes when reading an inline CSV

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#13908]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.09.0+463 (2023.09.0+463)
    OS Version      : mac OS 14.1 (23B74)
    R Version       : 4.3.1

### Steps to reproduce the problem

Run the following lines of code:

```r
library(readr)

x1 <- "text\nEl Ni\xf1o was particularly bad this year"
read_csv(x1)$text
```

This example is from [r4ds](https://r4ds.hadley.nz/strings.html#sec-other-languages).

### Describe the problem in detail

RStudio crashes.

https://github.com/rstudio/rstudio/assets/5965649/d574f6b7-9b27-4015-806a-ee46b682e3a0

### Describe the behavior you expected

I expected it to not crash...

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I was able to reproduce this outside of RStudio, so it appears this is a bug in `readr` itself.

```
> library(readr)

x1 <- "text\nEl Ni\xf1o was particularly bad this year"
read_csv(x1)$text
>
> x1 <- "text\nEl Ni\xf1o was particularly bad this year"
read_csv(x1)$text
> read_csv(x1)$text
Assertion failed: (tmpin > *in), function _citrus_iconv_std_iconv_convert, file citrus_iconv_std.c, line 1059.
Abort trap: 6
```

**Comment by jennybc** [comment]
This does produce an error for me, but it also does not crash R or RStudio:

``` r
library(readr)
x1 <- "text\nEl Ni\xf1o was particularly bad this year"
read_csv(x1)
#> Warning in grepl("\n", path): unable to translate 'text
#> El Ni<f1>o was particularly bad this year' to a wide string
#> Warning in grepl("\n", path): input string 1 is invalid
#> Warning in grepl("^((http|ftp)s?|sftp)://", path): unable to translate 'text
#> El Ni<f1>o was particularly bad this year' to a wide string
#> Warning in grepl("^((http|ftp)s?|sftp)://", path): input string 1 is invalid
#> Warning in regexpr(regex, path, perl = TRUE): input string 1 is invalid UTF-8
#> Warning in grepl("^(/|[A-Za-z]:|\\\\|~)", path): unable to translate 'text
#> El Ni<f1>o was particularly bad this year' to a wide string
#> Warning in grepl("^(/|[A-Za-z]:|\\\\|~)", path): input string 1 is invalid
#> Error: 'text El Ni<f1>o was particularly bad this year' does not exist in
#> current working directory
#> ('/private/tmp/RtmpK2OKfs/reprex-811139c6a0d5-petit-dore').
```

<sup>Created on 2023-11-09 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
For the record, there was a recent disturbance in the cpp11/vroom force, so my non-crashing reprex is with CRAN readr and vroom.

https://github.com/tidyverse/vroom/issues/510
