### ISSUE TITLE
copilot - authenticating is not finished after github finished plugin setup

### ISSUE THREAD

**Issue by vitas** [rstudio/rstudio#13901]
### System details

    RStudio Edition : server
    RStudio Version : 2023.12.0 build 268
    OS Version      : linux ubuntu20
    R Version       :  4.3.2

### Steps to reproduce the problem
activate copilot and follow github link to provide activation code

### Describe the problem in detail
Two problems:
1. After i have setup copilot and provided code in github, rstudio continues to show authenticating banner and does not close the window
2. Thre is no way to provide corporate github url, we cannot use global/private github url. Another ide offers set in the settings, perhaps is there a setting for rssession.conf?

### Describe the behavior you expected
1. Expect after github copilot sucsessfuly setup, rstudio closes registration window and i can use copilot
2. as an admin i would like to provide alternative github link for corporate github

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
> Another ide offers set in the settings

Can you provide another example as a reference for us?

**Comment by vitas** [comment]
in vs code, there is copilot lab extension, in settings has a field:  github-enterprise.uri
I suggest to make such filed in global settings for copilot plugin.

**Comment by kevinushey** [comment]
Thanks. I see the Copilot agent supports something similar:

```
                            authProvider: {
                                type: "string",
                                enum: ["github", "github-enterprise"],
                                enumDescriptions: ["GitHub.com", "GitHub Enterprise"],
                                default: "github",
                                description: "The GitHub identity to use for Copilot"
                            },
```

Or, you can provide something like:

```
authProvider: {
  url: <...>
}
```

I'll take a look.

**Comment by kevinushey** [comment]
The next daily builds will allow you to set, in `rsession.conf`:

```
copilot-auth-provider=<url>
```

I'm not exactly sure what `<url>` should be, but I think it should be the base URL to your GitHub Enterprise instance?

**Comment by vitas** [comment]
@kevinushey i have tried the daily 302 what has to have this option available, but auth still redirects to github.com instead of my set custom url

**Comment by penghexiang** [comment]
@vitas I have the same problem. May I ask you how you solved this problem?
authenticating is not finished after github finished plugin setup

**Comment by vitas** [comment]
in our case the issue was with company"s proxy, we have to whitelist few sites used by copilot

**Comment by kevinushey** [comment]
@vitas: are you able to share what Copilot sites you needed to whitelist with your proxy?

Was the `copilot-auth-provider` configuration option still useful in the end, or not in this case?

**Comment by kevinushey** [comment]
We haven't received any response, so I'll close this issue as fixed. Feel free to re-open if you're still having trouble. Thanks!
