### ISSUE TITLE
Terminals don't start when Terminal pane is set to use WSL

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13918]
### System details

    RStudio Edition : Desktop
    RStudio Version : All builds since early 2022
    OS Version      : Windows specific
    R Version       : Any

### Steps to reproduce the problem
- Ensure you have WSL (Windows Subsystem for Linux) enabled and working
- In RStudio Terminal options, set "New terminals open with" to "Bash (Windows Subsystem for Linux)"
- Try to start a new terminal in the Terminal pane

### Describe the problem in detail
- Some text briefly flashes in the terminal pane then it goes blank
- A new terminal is not started

### Describe the behavior you expected
- A wsl terminal session starts

This appears to have regressed due to https://github.com/rstudio/rstudio/pull/10283/ (early 2022!). I have reproduced this issue with several older builds back to that point, and it worked on builds before that.

The fix is a very simple 1-liner; don't pass `-l` to `bash.exe` when starting the wsl terminal. Given WSL sessions are running in a separate subsystem and a different operating system (unlike a git-bash terminal) I don't think conda integration is meaningful for WSL terminals.

I don't know if this has been 100% broken since then, or if it actually worked on wsl at that time, and has stopped working since then. I've only tested on the latest Windows-11 and WSL,

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Found mentions of this on community forum:

https://community.rstudio.com/t/setting-the-terminal-to-use-wsl-bash-in-windows-10/97904
https://community.rstudio.com/t/terminal-instant-crash-when-set-as-wsl-windows-subsystem-for-linux/157874

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+313](https://dailies.rstudio.com/version/2023.12.0-daily+313)
Windows 11, WSL2

WSL terminal opens up as expected.

**Comment by kamalmdmostafa** [comment]
Some text briefly flashes in the terminal pane then it goes blank

**Comment by gtritchie** [comment]
This is a closed issue, please open a new issue with details on platform, version, and so forth.
