### ISSUE TITLE
Avoid indexing .Renviron files with GitHub Copilot (and other secrets?)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13911]
Since we don't want to send credentials to the GitHub servers.

**Comment by ronblum** [comment]
In a `.Renviron` file with legitimate values of `DATABRICKS_TOKEN` and `DATABRICKS_HOST`, and only these two `DATABRICKS_*` fields, I get

```
DATABRICKS_TOKEN=1234567890abcdefg
DATABRICKS_HOST=https://myhost.cloud.databricks.com
```

with subsequent suggestions
```
DATABRICKS_ORG_ID=1234567890
DATABRICKS_CLUSTER_ID=1234-567890-abcdef
```

The actual values in `.Renviron` aren't shown.

Verified using 2023.12.0-daily+281.pro2 on Ubuntu 22.04.3 via Chrome on MacOS 14.2.
