### ISSUE TITLE
Copilot Sign-in via the command palette fails if the agent is not installed

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#13928]
### System details

    RStudio Edition :  Server 
    RStudio Version : 2023.12.0 Build 282
    OS Version      : ubuntu20
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Open the command palette and type Copilot for user that has not installed the agent.
2. Click `Copilot: Signin`

### Describe the problem in detail
I got the following error.

<img width="434" alt="Screenshot 2023-11-13 at 9 07 33 PM" src="https://github.com/rstudio/rstudio/assets/1482677/17dcdf65-5d09-4d3e-aed2-0d40539cb155">

### Describe the behavior you expected
The user should be prompted to install the agent if they need that to sign in.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in Posit Workbench 2023.12.0-daily+311.pro9 on RHEL 9.3 via Chrome on MacOS 14.2 that the user is now prompted to install the agent.
