### ISSUE TITLE
Copilot check status in the command palette  does nothing when the agent is not installed 

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#13929]
### System details

    RStudio Edition :  Server
    RStudio Version : 2023.12.0 Build 282
    OS Version      : ubuntu20
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Open the command palette for a user that has not install the agent.
2. Type Copilot and click `Copilot: Check status.`

### Describe the problem in detail
Nothing happens and the command palette closes.

### Describe the behavior you expected
I would expect something to happen and let me know the status or what I need to do to use Copilot.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified that in this scenario, RStudio tries prompts the user to install the agent. Tested with Post Workbench 2023.12.0-daily+311.pro9 on RHEL 9.3 via Chrome on MacOS 14.2.
