### ISSUE TITLE
Window resizing when using Windows split screen

### ISSUE THREAD

**Issue by ysdgroot** [rstudio/rstudio#13921]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1 Build 494
    OS Version      : Windows 10
    R Version       : 4.3.2

### Steps to reproduce the problem
- Put main Rstudio window in split screen (Windows key + left/right arrow )  
- Put a R-script in new window (so not in the main Rstudio window) and put this window on the other side of the main window
- Run some code on the new window 
- The main window resizes (bug)
(see video attached)

### Describe the problem in detail
When running code in a 'new window' and using the Windows split screen modus, the main window would resize itself. 
This only happens when the main window has been put to Windows split screen modus.

### Describe the behavior you expected
No window resizing 

https://github.com/rstudio/rstudio/assets/25459775/43610c04-9633-4b68-ab6c-4734b67d463c

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ysdgroot Thank you for raising this!

@jonvanausdeln Can you take a look at this?

**Comment by jonvanausdeln** [comment]
@ronblum , I just repro'd this on my Windows 11 machine.  It appears to have been the case probably since the switch to electron as I can reproduce as far back as 2023.03.1 (I didn't check older versions).
