### ISSUE TITLE
An unexpected error shows in Options if the agent is not installed for Copilot

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#13930]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.12.0 Build 282
    OS Version      : ubuntu20
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Go to tools->options with a user that has not installed the agent.
2. Click Copilot and observe the options for Copilot.

### Describe the problem in detail
The user sees An unexpected error.
<img width="638" alt="Screenshot 2023-11-13 at 12 56 42 PM" src="https://github.com/rstudio/rstudio/assets/1482677/a9a0aead-19b3-4aa3-872f-34126c18cc27">

### Describe the behavior you expected
I would not expect to see any errors.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be addressed by https://github.com/rstudio/rstudio/commit/898215ecee8c7c5bdf5c689999b5b2265f3b5764.

**Comment by ronblum** [comment]
Verified that the message now states that Copilot is not enabled. Tested in Posit Workbench 2023.12.0-daily+311.pro9 on RHEL 9.3 via Chrome on MacOS 14.2.


![Image](https://github.com/rstudio/rstudio/assets/31009952/dbdfb97f-b2c3-4795-bd3b-127cf4ad5b98)
