### ISSUE TITLE
Enabling copilot in the command palette does not prompt the user to install the agent

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#13931]
### System details

    RStudio Edition :  Server 
    RStudio Version : 2023.12.0 Build 282
    OS Version      : ubuntu20
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Open the command palette with a user who has not installed the agent.
2. Type Copilot and select the box to Enable GitHub Copilot and close the command palette.
3. Observe the Copilot settings in Tools->Options->Copilot menu.

### Describe the problem in detail
Copilot shows enabled in the command palette and in the Tools->Options but the user never installed the agent so things will not work if they need that installed.

### Describe the behavior you expected
I would expect the user to be prompted to install the agent before Copilot can be enabled.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in Posit Workbench 2023.12.0-daily+311.pro9 on RHEL 9.3 via Chrome on MacOS 14.2 that the user is now prompted to install the agent.
