### ISSUE TITLE
Uninstalling RStudio on Windows leaves start menu items

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#13936]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1+494 "Desert Sunflower"
    OS Version      : Windows-11 (23H2)
    R Version       : any

### Steps to reproduce the problem

- install RStudio on Windows
- confirm that start menu contains an RStudio folder containing the RStudio shortcut and an uninstall shortcut

> Per #1900, the Start Menu itself may or may not display the RStudio folder as part of the start menu so you might need to examine the actual files at `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio`

- uninstall RStudio from add/remove programs
- look again in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio (and on the Start Menu)

### Describe the problem in detail

- Only the "uninstall" shortcut gets removed from C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio; the RStudio folder and shortcut is still there (but the program has been uninstalled so the shortcut doesn't work)

### Describe the behavior you expected

- Entire "RStudio" folder should be removed from Start Menu as part of uninstall

### Other notes

This seems to be related to the move to Electron, somehow. I installed and uninstalled the Qt build of 2022.07.0-548 and it cleaned up as expected. The same build of Electron leaves the folder behind.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Here are the last few lines of the uninstall log for Electron (from the uninstall program UI):

```
Remove folder: C:\Program Files\RStudio\
Delete file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio\Uninstall.lnk
Completed
```

versus Qt:

```
Remove folder: C:\Program Files\RStudio\
Delete file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio\Uninstall.lnk
Delete file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio\RStudio.lnk
Remove folder: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio\
Completed
```

**Comment by jonvanausdeln** [comment]
Verified with [2024.04.0-daily+456](https://dailies.rstudio.com/version/2024.04.0-daily+456) on Windows 11

Uninstalling from either `Add/Remove Programs` or the Uninstall shortcut both work as expected. The folder is completely removed.
