### ISSUE TITLE
C Stack setting ignored

### ISSUE THREAD

**Issue by boesr** [rstudio/rstudio#13952]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.09.0+463 (Desert Sunflower) for RHEL 8
    OS Version      :  Rocky 8.8
    R Version       :  4.2.2

### Steps to reproduce the problem

Set stack limit at `/etc/security/limits.conf` like

```bash
*       soft    stack   65536
*       hard    stack   65536
````
 
OR

set limit in service config (`/usr/lib/systemd/system/rstudio-server.service.d/stacklimit.conf`) like

```bash
[Service]
LimitSTACK=65536
```

### Describe the problem in detail

A user of our RStudio server encounters the error `C stack usage 7970160 is too close to the limit` due to a highly recursive function. We want to increase the C stack limit. When setting it via the limits.conf it is just ignored. If I try to set it via the service config, rstudio won't start (`Unable to parse version from R, version-info:`).

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Just to confirm, if the limits are set in `/etc/security/limits.conf`, do you see those limits being respected in a "plain" R session, e.g. R launched in a terminal outside of RStudio?

**Comment by kevinushey** [comment]
For reference, this is where R sets the C stack limit: https://github.com/wch/r-source/blob/e26e3f02a5e4255c4aad0842a46e141c03eed379/src/unix/system.c#L204-L309

**Comment by boesr** [comment]
Yes if I start R from terminal and enter `base::Cstack_info()` the limit defined in `/etc/security/limits.conf` is shown.

**Comment by kevinushey** [comment]
Hmm, that's not what I see:

```
$ R -s -e 'Cstack_info()'
      size    current  direction eval_depth 
  63753420      16336          1          2 

$ cat /etc/security/limits.conf 
*	soft	stack	65536
*	hard	stack	65536

$ ulimit -s
65536
```

And this seems to match what I see in an RStudio R session:

```
> system("ulimit -s")
65536

> Cstack_info()
      size    current  direction eval_depth 
  63753420      22368          1          2 
```

**Comment by boesr** [comment]
Hmm that's strange. Here are my logs:

```bash
# the R version RStudio is set to
$ /software/all/R/4.2.2-foss-2022b/bin/R -s -e 'Cstack_info()'
      size    current  direction eval_depth
  63753420      25016          1          2

$ cat /etc/security/limits.conf
  *	  hard   nofile	102400
  *	  soft    nofile	102400
  *       soft    stack   65536
  *       hard   stack   65536
  
$ ulimit -s
65536
```

And RStudio returns:

```R
> system("ulimit -s")
8192

>  Cstack_info()
      size    current  direction eval_depth 
   7969177      33112          1          2 
```

**Comment by ronblum** [comment]
@boesr Do you know if this worked correctly in previous versions of RStudio and if so, which ones?

**Comment by boesr** [comment]
@ronblum Unfortunately I don't any info about that. We just tried to increase the limit because one of our users ran into a problem regarding the stack size.

**Comment by kevinushey** [comment]
For confirmation, are you using the open-source version of RStudio?

**Comment by boesr** [comment]
Yes, I am using this package:  https://download2.rstudio.org/server/rhel8/x86_64/rstudio-server-rhel-2023.09.1-494-x86_64.rpm

**Comment by kevinushey** [comment]
Thanks -- presumedly this is something specific to RHEL / systemd, and how stack limits are set for services (or similarly, child processes launched from service processes).

As a workaround, I can do something like:

```
ExecStart=/bin/bash -c "ulimit -s 65536 && exec /usr/lib/rstudio-server/bin/rserver"
```

in the RStudio Server systemd service file, but there's probably a better way that I'm not aware of.

**Comment by boesr** [comment]
Thanks for the workaround, that does work. 

Regarding your assumption. It probably is specific to systemd. We previously had the server running on Debian and hat the same problem that the  `nofile` setting was ignored.

**Comment by akhst7** [comment]
I will bring this issue up again.   I have an exactly the same issue with Rstudio in my M1 Mac Studio running OSX 14.5 as follows (I set CStack size to 65520 in zshrc.);

```
> Cstack_info()
      size    current  direction eval_depth 
   7953612      19304          1          2

> system("ulimit -s")
8176
```
From my terminal ;
```
ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             65520
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       10666
-n: file descriptors                unlimited
```

```
 R --slave -e 'Cstack_info()["size"]'
    size
63737856
```
I can't use the kevinushey's fix obviously and have not found any workaround yet. I appreciate any suggestions. 

My system:
```
                      'c.                   my@MacStudioAH.local
                 ,xNMM.          -----------------------------
               .OMMMMo           OS: macOS 14.5 23F79 arm64
               OMMM0,            Host: Mac13,2
     .;loddo:' loolloddol;.      Kernel: 23.5.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 6 hours, 36 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 237 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3440x1440
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Monaco 10
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1 Ultra
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1 Ultra
       .cooc,.    .,coo:.        Memory: 5661MiB / 131072MiB


> R.version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          4.1                         
year           2024                        
month          06                          
day            14                          
svn rev        86737                       
language       R                           
version.string R version 4.4.1 (2024-06-14)
nickname       Race for Your Life

Rstudio Version 2024.04.2+764 (2024.04.2+764)

```
