### ISSUE TITLE
Log out option for github copilot

### ISSUE THREAD

**Issue by gormfe** [rstudio/rstudio#13960]

**Comment by ronblum** [comment]
@gormfe Can you please elaborate? There's a "sign out" option if you go to <kbd>Tools -> Global Options -> Copilot</kbd>.

**Comment by gormfe** [comment]
Hey, thanks for the quick response!
I have no Sign Out option when I go to Tools -> Global Options -> Copilot. 
Sorry can't seem to add a picture. 
In the menu I only have GitHub Copilot (Preview), Copilot Indexing and Copilot Completions.

I have the newest version of RStudio as well: Version 2023.09.1+494 (2023.09.1+494).
