### ISSUE TITLE
RStudio Desktop doesn't run on Linux if installed from scratch (upgrade works)

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13966]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0-daily+313
    OS Version      : Debian 12.2, Red Hat 9.2, possibly other Linux builds
    R Version       : 4.2.3

### Steps to reproduce the problem

1. Uninstall RStudio Desktop, if already installed.
2. Install RStudio Desktop.
3. `rstudio`

### Describe the problem in detail

RStudio won't start. Instead, this error appears:
```
bash: /usr/bin/rstudio: Permission denied
```

Here's more detail about the file system.

```
[vmware@localhost ~]$ rstudio
bash: rstudio: command not found...

[vmware@localhost ~]$ which rstudio
/usr/bin/which: no rstudio in (/home/vmware/.local/bin:/home/vmware/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)

[vmware@localhost ~]$ ls -l /usr/bin/rstudio
lrwxrwxrwx. 1 root root 24 Nov 20 11:26 /usr/bin/rstudio -> /usr/lib/rstudio/rstudio

[vmware@localhost ~]$ ls -l /usr/lib/rstudio/rstudio
ls: cannot access '/usr/lib/rstudio/rstudio': Permission denied

[vmware@localhost ~]$ sudo ls -l /usr/lib/rstudio/rstudio
-rwxr-xr-x. 1 root root 168468592 Nov 19 18:56 /usr/lib/rstudio/rstudio

[vmware@localhost ~]$ sudo ls -ld /usr/lib/rstudio
drwx------. 4 root root 4096 Nov 20 11:26 /usr/lib/rstudio
```

### Describe the behavior you expected

RStudio Desktop should start up.

This was working correctly with version 2023.12.0-daily+212. Let me know if you'd like me to figure out which build it started failing on.

Also note that the first couple of times that I tried, this only happens if RStudio is installed from scratch and upgrading from 2023.09.1 worked. Now that doesn't work, either.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
QA note: Try very recent builds as some recent changes may have caused this.

**Comment by jonvanausdeln** [comment]
I get a slightly different issue on Ubuntu 22

> jon@Ubuntu22:~$ dpkg -l  | grep rstudio
>
>ii  rstudio                                    2023.12.0-daily+313                     amd64        RStudio
>
>jon@Ubuntu22:~$ rstudio
>
>rstudio: command not found

**Comment by kevinushey** [comment]
For comparison:

```
$ namei -l /usr/lib/rstudio
f: /usr/lib/rstudio
drwxr-xr-x root root /
drwxr-xr-x root root usr
drwxr-xr-x root root lib
drwxr-xr-x root root rstudio

$ /usr/lib/rstudio/rstudio --version
2023.09.0+445

```

**Comment by ronblum** [comment]
RStudio Desktop on Red Hat 9.2 last works with 2023.12.0_daily+266 and starts to fail with 2023.12.0_daily+268.

**Comment by kevinushey** [comment]
That would point to https://github.com/rstudio/rstudio/commit/d26c0d74ad873a0f48b9153c2b0e56111cae2932 being the potential culprit, but it's hard to reason why updating our Electron dependencies would cascade down in this way.

Perhaps as a band-aid we can repair permissions in our post-install script?

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+330](https://dailies.rstudio.com/version/2023.12.0-daily+330)

Ubuntu22

Installs and launches without issue.
