### ISSUE TITLE
R Notebooks very slow with newer RStudio versions

### ISSUE THREAD

**Issue by MCKnaus** [rstudio/rstudio#13965]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1 Build 494
    OS Version      : Windows 11 Home
    R Version       : 4.3.1

Note that 15 students in my course using a variety of settings had the same problem.

### Steps to reproduce the problem

Create a blank R Notebook and include the following code chunk:

```{r}
# install.packages("grf")
library(grf)
n <- 5000
p <- 10
X <- matrix(rnorm(n * p), n, p)
Y <- X[, 1] * rnorm(n)
r.forest <- regression_forest(X, Y)

# Predict using the forest.
X.test <- matrix(0, 101, p)
X.test[, 1] <- seq(-2, 2, length.out = 101)
r.pred <- predict(r.forest, X.test)
```

Run the code chunk either by pushing the "play button" at the top right of the code chunk or "Run All". Importantly running the same code in the console or knitting the notebook does not produce the problem.

### Describe the problem in detail

After running the code chunk, RStudio is slowed down in a way that even running `2+2` takes several seconds. Some context and what we figured out so far:
- I am using the `grf` package in many R Notebooks for teaching and it worked just fine last year. 
- Inspired by [this issue](https://community.rstudio.com/t/code-running-much-slower-on-rmarkdown-than-r-script-after-update/164474/3) we figured out that the problem is solved by uninstalling current RStudio versions and installing RStudio 2022.07.0 Build 548 instead.
- The problem is less pronounced if, e.g. `n <- 500` in the above code chunk.

### Describe the behavior you expected

That the code chunk runs in a few seconds and that the functionality of RStudio is preserved afterwards. Like it is the case in old RStudio versions or running it in the console.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@MCKnaus Thank you for raising this! I can reproduce the problem in RStudio Desktop 2023.09.1+494. Even restarting R takes a while. I'm getting the same problem in the Console Pane, as well, but not when knitting. The problem goes away if the `r.forest` object is cleared.

**Comment by ronblum** [comment]
@MCKnaus Do you know if this worked in any recent versions of RStudio, between 2022.07 and 2023.09?

**Comment by MCKnaus** [comment]
> @MCKnaus Do you know if this worked in any recent versions of RStudio, between 2022.07 and 2023.09?
> 
> [Note: I can also reproduce this in RStudio Desktop 2023.06.2+561.]

No. I just figured out that 2022.07 solves the issue. I was hoping you guys have an educated guess why this happens. However, I could do some grid search over RStudio versions to figure out where it breaks if this helps.

**Comment by kevinushey** [comment]
The problem here is that it takes RStudio a very long time to decide whether the environment can be safely serialized, because checking the `r.forest` object is very slow:

```
> system.time(.rs.environment.isSerializable())
   user  system elapsed 
  6.701   0.026   6.750 
```

And this check gets done somewhat aggressively (basically, on every console prompt).

We could either:

1. Move the implementation from R to C for some speedup when examining these nested structures;
2. Treat `grf` objects as "known-to-be serializable".

**Comment by jonvanausdeln** [comment]
Verified with https://dailies.rstudio.com/version/2023.12.0-daily+336
Windows 11

The IDE is much more responsive now after running the code chunk.
