### ISSUE TITLE
Speed up core C++ utility FilePath.isDirectory()

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#13969]
The code makes an unnecessary `exists()` call that returns false, when it could just pass in an error code to is_directory() since that returns a "no_such_file_or_directory" error.  The exists() call turns into an unnecessary `stat()` system call.

**Comment by gtritchie** [comment]
Nothing specifically testable here. Unit tests pass, and if this isn't working a lot of things will be noticably broken.
