### ISSUE TITLE
Authentication doesn't stop if trying to sign in with an account that doesn't have Copilot

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13975]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2023.12.0-daily+322.pro4
    OS Version      : MacOS 14.2 and Ubuntu 22.04.3
    R Version       : 4.2.3

### Steps to reproduce the problem

1. At GitHub.com, log in to an account that doesn't have Copilot.
2. In RStudio go to <kbd>Tools -> Global Options -> Copilot</kbd>
3. If Copilot isn't enabled, enable it.
4. Try signing in, following the authentication flow that includes entering the auth code at GitHub.
5. Go back to RStudio.
    - The "Authenticating" message stays and spins indefinitely.

### Describe the problem in detail

If a user tries to authenticate an account that doesn't have Copilot, RStudio will wait and wait endlessly.

### Describe the behavior you expected

The authentication would fail, along with a friendly message saying that Copilot isn't available.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can you try these steps once more, but with these environment variables set?

```
RSTUDIO_COPILOT_LOG_LEVEL = 3
GITHUB_COPILOT_DEBUG = 1
COPILOT_AGENT_VERBOSE = 1
```

Then, can you share what you see in the Console output? Presumedly the Copilot agent itself believes that it's still trying to authenticate, but perhaps there's some other message we're not expecting.

**Comment by koenniem** [comment]
I can confirm this issue. I could not figure out what was wrong until I saw this bug report, so I enabled copilot on Github (I only recently got access and haven't used it yet) and then it immediately logged me on in Rstudio.

**Comment by kevinushey** [comment]
I believe this should be improved now -- we should detect if you haven't yet enabled Copilot with your GitHub account, and provide an `Activate` button to get that set up.

**Comment by ronblum** [comment]
I'm still seeing the issue in RStudio Desktop 2024.04.0-daily+662 on Windows 11. Here are the logs, which I never provided previously: [rsession-RonBlum.log](https://github.com/rstudio/rstudio/files/14774792/rsession-RonBlum.log)

**Comment by ronblum** [comment]
Success! Verified in RStudio Desktop 2024.04.0-daily+668 on Windows 11.
