### ISSUE TITLE
Quick Theme Switching Button and Theme Favorites

### ISSUE THREAD

**Issue by jniedballa** [rstudio/rstudio#13971]
### Problem
When using RStudio I often switch between different themes based on the time of day, the place I am, or specific project requirements (all within the same session). Doing so requires navigating through multiple menus and several clicks to find and apply the desired theme. This is especially difficult when switching from dark to light theme in bright environment because UI elements and the cursor are hard to see.

### Idea
A quick theme-switching button and the ability to mark favorite themes would simplify and speed up switching between themes. It could also help (partly) address teaching mode and other theme-related feature requests (e.g. #4276, #5813, #2350)

#### Quick Theme Switching Button

Introduce a button / keybind / menu option in the RStudio interface that allows users to quickly switch between their preferred themes without navigating through menus.

#### Theme Favorites

- Allow users to mark certain themes as favorites within the RStudio interface (globally and/or project/session-specific).
- Provide a mechanism (such as a star icon) next to each theme in the theme selection menu, allowing users to easily mark themes as favorites.
- (maybe implement a "Favorites" section at the top of the theme selection menu for quick access to the user's preferred themes, or show starred items at the top of the list)

### Potential Benefits

It is more efficient if users can switch between themes with a single click, reducing the time and effort required to customize the appearance of RStudio when required.
The ability to mark favorite themes ensures that users can easily access and apply their most frequently used themes. If the list of favourites is made project / session-specific (and customizable within the project) it would allow even more flexibility.

Thank you for your great work on RStudio!

**Comment by ronblum** [comment]
@jniedballa Thank you for the suggestion! We'll review this as we continue development of RStudio.

**Comment by olivroy** [comment]
Hi you can use functions like ` rstudioapi::applyTheme("Solarized Light")` to do this quickly in the R console inside RStudio.

Mine created RStudio addins for this https://github.com/mine-cetinkaya-rundel/addmins You can install the package and map a shortcut to each.

An idea would be to add this to your R profile, which would show up in interactive sessions.

Therefore, you will see the bullets in your console when you restart your session. You can just click on the one you like.

(It's probably not what you want, but just thought I'd share how you can wrap the `rstudioapi::applyTheme()` function to improve your workflow!)

```r
if (interactive()) {
  # create clickable hyperlinks of your favorite themes
  cli::cli_bullets(c(
  "{.run [Use Solarized theme](rstudioapi::applyTheme('Solarized Light'))}",
  "{.run [Use Light theme](rstudioapi::applyTheme('Chrome'))}",
  "{.run [Use Dark theme](rstudioapi::applyTheme('Tomorrow Night'))}"
  ))

}
```

**Comment by jthomasmock** [comment]
Hi @jniedballa ! Check out the `rsthemes` package - it has addins for switching themes and setting favorites: https://www.garrickadenbuie.com/project/rsthemes/#easy-theme-switching

You can invoke those via RStudio's Command Palette to quickly switch themes! 🎉
