### ISSUE TITLE
Use system's built-in file browser for "Open File" and "Save as..." dialog boxes

### ISSUE THREAD

**Issue by arthur-e** [rstudio/rstudio#13988]
As of a recent RStudio update on Ubuntu GNU/Linux, the "Open File..." dialog has changed. Where as it used to show the system's default (Nautilus?) file browser, with shortcuts on the left-hand side and a breadcrumbs file tree at the top, it now uses a custom, slimmed-down file browser that follows the RStudio UI theme. The "Save as..." dialog is similar and has similar problems.

I prefer the old dialog boxes. The shortcuts really help to find files fast, particularly for a Network File System (NFS) or other remote file systems not located near the user's home directory. The new dialog boxes do not.

My system information:

```
RStudio 2023.03.1+446 "Cherry Blossom" Release (6e31ffc3ef2a1f81d377eeccab71ddc11cfbd29e, 2023-05-09) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.1+446 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
```

**Comment by ronblum** [comment]
@arthur-e What do you get if you check <kbd>Tools -> Global Options -> General -> Advanced -> Use native file and message dialog boxes</kbd>?

**Comment by arthur-e** [comment]
@ronblum Yes, that fixes it. Thanks!

**Comment by ronblum** [comment]
@arthur-e You're welcome! 🙂
