### ISSUE TITLE
Copilot tries to start new code chunk when editing in R Markdown

### ISSUE THREAD

**Issue by bthetford** [rstudio/rstudio#13987]
When editing in R markdown above a code chunk, copilot suggests a completion to my notes, but includes the top of a code chunk `(```{r})`. It's annoying to remove every time, I'd like it to detect that I already have a chunk below, or at least suggest a full code chunk rather than the top characters only. 

![Screenshot 2023-11-24 082849](https://github.com/rstudio/rstudio/assets/57117377/7f9d9e43-1343-4fb7-b77a-c6e08d913e78)

### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.09.1+494 "Desert Sunflower" Release (cd7011dce393115d3a7c3db799dda4b1c7e88711, 2023-10-16) for windows
    OS Version      :  Windows 11
    R Version       :  4.3.2

### Steps to reproduce the problem
Type into an R markdown document outside of a code chunk.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by reddylee** [comment]
I have the similar issue to report. whenever copilot suggestion completed, it always create a new chunk and the cursor jump to the new chunk. I have to go back to the previous chunk with suggestion code to run. It is quite annoying.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+558 on MacOS 14.4. The new chunk suggestion is now separate from the intended completion:
- The first suggestion is the line, e.g. `then, for each time step,` etc.
- After this suggestion is a accepted, the next suggestion can be for opening a chunk, but it can be ignored without affecting the previous suggestion.
