### ISSUE TITLE
setwd not working in R notebook block.

### ISSUE THREAD

**Issue by gevro** [rstudio/rstudio#13999]
Rstudio version: 2023.09.1+494 (2023.09.1+494) on Mac OS

In an R notebook, a ```{r} ``` block contains a setwd() command. When pressing the 'play' button to run the block, the working directory does not get set for some reason.

Manually copy pasting the command into R does execute it.

**Comment by kevinushey** [comment]
I'm not able to reproduce. Can you please provide a reproducible example?

**Comment by gevro** [comment]
I'm not able to reproduce on a second computer. But it is happening repeatedly on the above computer. I will keep trying and will let you know if I can find out what is causing it to happen reproducibly.
