### ISSUE TITLE
List contents appear repeated in Viewer pane when naming list elements

### ISSUE THREAD

**Issue by DCEW** [rstudio/rstudio#13992]
### System details

    RStudio Edition : Desktop  
    RStudio Version : 2023.6.0.421
    OS Version      : Windows 11 Enterprise
    R Version       : 4.3.1 (2023-06-16 ucrt)

### Steps to reproduce the problem
``` r
test <- list(a = data.frame(this = c(1,2,3,4,5)),b = data.frame(that = c("a","b","c","d","f")))

names(test) <- c("a","a")
```

<sup>Created on 2023-11-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### Describe the problem in detail
When names() is used to rename elements of a list, and those names are repeated, when you view the list in the viewer pane (by clicking on the object 'test' now in the Environment) it appears as though the contents of the list are now duplicated, as well as the names.  However in the Console, printing the list shows the correct contents, so this is just an issue with the Viewer.

### Describe the behavior you expected
I expected that viewing the list would show the original contents of the list (in the reprex above, the data frames 'this' and 'that') but each is now called 'a'. (Yes, I know naming elements the same thing is mostly not a good idea....sorry)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by matt-dray** [comment]
For me, `names()` doesn't need to be used for this behaviour to occur. I ran:

``` r
test <- list(
  a = data.frame(this = 1:5),
  a = data.frame(that = LETTERS[1:5])
)
```

And got the same duplication behaviour when I clicked the `test` object in the RStudio Environment pane (or ran `View(test)` from within RStudio).
