### ISSUE TITLE
Width in Visual mode is reset when having more than one .Rmd pane open

### ISSUE THREAD

**Issue by cmmrandau** [rstudio/rstudio#13998]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1+494
    OS Version      :  Ubuntu 23.10
    R Version       :  R version 4.3.1 (2023-06-16)

### Steps to reproduce the problem
Have more than one .Rmd source file open in Visual mode. Click Source, then Visual mode so that the width is changed to Visual mode, i.e., wide margin. Do something, like right-click on a misspelled word or a @citation. This reset width to narrow margin as in the Source mode. Clicking Source and Visual mode again changes the width back. 

### Describe the behavior you expected
I expect the default Visual mode margin not to change wherever I click. The problem does not occur when only one .Rmd file is open. 

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cmmrandau** [comment]
bump. It's strange no one else seems to be having this problem.

**Comment by kevinushey** [comment]
@cmmrandau: any chance you could share a screencast / video recording, just so we can be sure we understand what you're seeing?

**Comment by cmmrandau** [comment]
I have attached a short video. I have two .Rmd files open. If I, e.g., click on misspelled word, the width is reset, or increased. I have to go to source mode and then back to visual mode for it to get back to the default. This does not happen when I only have on .Rmd file open. 

[Screencast from 2024-01-26 12-06-28.webm](https://github.com/rstudio/rstudio/assets/74201440/423358da-0f90-4f7b-a1a7-b877342428b6)
