### ISSUE TITLE
Error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by abalter** [rstudio/rstudio#14000]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.09.1+494 "Desert Sunflower " (cd7011dc, 2023-10-16) for Ubuntu Jammy
    OS Version      :  Ubuntu 22.04
    R Version       :  4.3.2

### Steps to reproduce the problem
1. `wget https://download1.rstudio.org/electron/jammy/amd64/rstudio-2023.09.1-494-amd64.deb`
2. `sudo dpkg -i rstudio-2023.09.1-494-amd64.deb`
3. `rstudio`

### Describe the problem in detail
I have perpetual problems installing RStudio in Linux while using `{conda-forge}`. The way RStudio is written, it does not obey the user's environment. Instead, it looks in hard-coded expected places for libraries. Consequently, it frequently can't find libraries, especially `libR.so`. 

As an example, RStudio won't launch at all unless there is an R executable in `/usr/bin`, even if both user and root have R in their path. I have root set up to seamlessly use my conda environment:

```sh
(base) balter@expiyes:~$ sudo su
(base) root@expiyes:/home/balter# whoami
root
(base) root@expiyes:/home/balter# which R
/home/balter/micromamba/bin/R
(base) root@expiyes:/home/balter# ls -l /usr/bin/R
lrwxrwxrwx 1 root root 29 Nov 27 23:29 /usr/bin/R -> /home/balter/micromamba/bin/R
(base) root@expiyes:/home/balter# ls -l /lib/R
lrwxrwxrwx 1 root root 29 Nov 28 00:05 /lib/R -> /home/balter/micromamba/lib/R
(base) root@expiyes:/home/balter# ls -l /usr/lib/R
lrwxrwxrwx 1 root root 29 Nov 28 00:05 /usr/lib/R -> /home/balter/micromamba/lib/R
(base) root@expiyes:/home/balter# R --version
R version 4.3.2 (2023-10-31) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

(base) root@expiyes:/home/balter# Rscript -e '.libPaths()'
[1] "/home/balter/micromamba/lib/R/library"
(base) root@expiyes:/home/balter# Rscript -e '.Library'
[1] "/home/balter/micromamba/lib/R/library"
```

### RStudio Version

RStudio 2023.09.1+494 "Desert Sunflower " (cd7011dc, 2023-10-16) for Ubuntu Jammy

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 127. 

Error output:

```
/usr/lib/rstudio/resources/app/bin/rsession: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory

```

Standard output:

```
[No output emitted]
```

### Logs

*/home/balter/.local/share/rstudio/log/rsession-balter.log*

```
Linux may have loaded a different libR.so than requested. This can result in "package was built under R version X.Y.Z" user warnings and R_HOME/R version mismatches.
R_HOME: /home/balter/micromamba/lib/R
R Version: 4.3.1]; OCCURRED AT  :0; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) src/cpp/session/SessionMain.cpp:741

```
                

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Mixing software built with Conda with software built outside of Conda is always a challenge, especially because of the potential incompatibilities between the libraries required by your Conda environments and the environments required by software outside of those environments.

Pull requests would be welcomed, but this is not something we can provide extended support for in our open source product.

**Comment by abalter** [comment]
I can't accept that. You could say the same for "software built with apt". The RStudio company has long kept conda on the sidelines as some sort of fringe or fad package manager for people who like Python.

Conda is a full-fledged package manager that is the default in the data science world. I have saved organizations hundreds of hours of headaches by using conda as a package manager instead of `install.packages` which creates huge conflicts.

The problem is, as I have said, that RStudio won't simply use the user's environment. I don't have this issue with any other software.

**Comment by abalter** [comment]
To restate: I'm not asking you to "support conda". I'm asking you to follow a more universal software engineering design that will not block conda.

If my R libraries all work and are up to date, why should RStudio care where they are installed?

**Comment by abalter** [comment]
@kevinushey --- I'd love to have a 1:1 conversation with you about conda if you are willing.
