### ISSUE TITLE
View() opens external pop-up instead of allowing viewing of data frames in pane, within Rproject

### ISSUE THREAD

**Issue by DCEW** [rstudio/rstudio#14009]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0 Build 421
    OS Version      : Windows 11
    R Version       : 4.3.1

### Steps to reproduce the problem
Cannot reproduce, but is static feature in one Rproject

### Describe the problem in detail
When within a particular Rproject, either clicking on a data frame in the Environment window, or putting 'View(df)` in the console, instead of the dataframe being displayed in the top left pane as expected, it eventually appears in an external pop-up (see picture attached).  I have not changed any project or global settings that I know of.
 
![RStudio_popup_error](https://github.com/rstudio/rstudio/assets/112561799/7cfa43e8-c5d5-4641-9443-f30a97cb2ba8)

### Describe the behavior you expected
I expected that when clicking on a data frame object, or list etc, or running View() on an object, for it to be displayed in the top left pane within the IDE.  This is the behaviour I've always seen and continue to see in all my other R projects.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This would normally imply that RStudio's "shims" are no longer at the front of the search path. What is the output of:

```
search()
```

in the R sessions where this occurs?

**Comment by DCEW** [comment]
`search()` gives:

 [1] ".GlobalEnv"                  "package:OHIDLocalHealthTool" "package:lubridate"           "package:forcats"            
 [5] "package:stringr"             "package:dplyr"               "package:purrr"               "package:readr"              
 [9] "package:tidyr"               "package:tibble"              "package:ggplot2"             "package:tidyverse"          
[13] "package:here"                "package:NDRSAfunctions"      "package:rJava"               "package:testthat"           
[17] "devtools_shims"              "package:devtools"            "package:usethis"             "tools:rstudio"              
[21] "package:stats"               "package:graphics"            "package:grDevices"           "package:utils"              
[25] "package:datasets"            "package:methods"             "SciViews:TempEnv"            "Autoloads"                  
[29] "package:base" 

Does this help? When I run search() outside this project, the second element of what's returned is "tools:rstudio"

**Comment by kevinushey** [comment]
Interesting; I had expected that perhaps `package:utils` would be in front of `tools:rstudio`.

Can you then share what the output of the following is when executed in the console?

```
View
environment(View)
```

**Comment by DCEW** [comment]
View gives:
function (x, title) 
{
    check <- Sys.getenv("_R_CHECK_SCREEN_DEVICE_", "")
    msg <- "View() should not be used in examples etc"
    if (identical(check, "stop")) 
        stop(msg, domain = NA)
    else if (identical(check, "warn")) 
        warning(msg, immediate. = TRUE, noBreaks. = TRUE, domain = NA)
    if (missing(title)) 
        title <- paste("Data:", deparse(substitute(x))[1])
    x0 <- as.data.frame(x)
    x <- as.list(format.data.frame(x0))
    rn <- row.names(x0)
    if (any(rn != seq_along(rn))) 
        x <- c(list(row.names = rn), x)
    if (!is.list(x) || !length(x) || !all(sapply(x, is.atomic)) || 
        !max(lengths(x))) 
        stop("invalid 'x' argument")
    if (grepl("darwin", R.version$os)) 
        check_for_XQuartz(file.path(R.home("modules"), "R_de.so"))
    invisible(.External2(C_dataviewer, x, title))
}
<bytecode: 0x000002632593e558>
<environment: namespace:utils>

environment(View) gives: 
<environment: namespace:utils>

**Comment by kevinushey** [comment]
Strange... I wonder if another package you have loaded is re-exporting `utils::View`, and so is putting it on the front of the search path.

**Comment by DCEW** [comment]
I figured this out in the end, thanks to pointers from @kevinushey (thanks!)- I'd put an `@importFrom utils` in one of my packages which had changed the `environment(View)` to the `namespace:utils`. So once I ran `load_all()` it was shifting the viewer device to that weird external thing.  Removed this import and all seems well :-)
