### ISSUE TITLE
Quarto unable to find R if located on path with non-ASCII characters

### ISSUE THREAD

**Issue by sda030** [rstudio/rstudio#14011]
Note that the Quarto developers suggested to move this issue from [there](https://github.com/quarto-dev/quarto-cli/issues/7473) to here.

A colleague with a non-ASCII character in his `USERPROFILE` has R installed in `c:\users\Ørjan\appdata\Local\Programs\R` (due to lack of administrative privileges).

Rendering of the simplest R-chunk errs with
```bash
ERROR: Error executing 'C:\Users\�rjan\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe': Systemet finner ikke angitt bane. (os error 3)
Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```
R works perfectly fine elsewhere, and Quarto renders if not containing any R chunks or if `quarto render` or `quarto serve` is used on the command line. We tried to install R in regular Program Files path but some strange admin rights are missing so not an option for now. Other colleagues (and I) have no problems, and we also have no non-ascii characters in our R paths. 

NOTE: Although I suspect Quarto has the bug, I am open for the idea that there is something strange in the RStudio locale setup for Norwegian, as all my Norwegian colleagues have needed to set LC_ALL="nb.utf8" for non-ascii characters to work - despite R 4.2 supposedly having made everything utf8 default (https://github.com/rstudio/rstudio/issues/12668).

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0 Build 340
    OS Version      :  Windows 11
    R Version       : 4.3.2

```bash
[System.Text.Encoding]::Default.EncodingName
Vesteuropeisk (Windows)

Get-WinSystemLocale | Select-Object Name, DisplayName, 
                        @{ n='OEMCP'; e={ $_.TextInfo.OemCodePage } }, 
                        @{ n='ACP';   e={ $_.TextInfo.AnsiCodePage } }
Name  DisplayName            OEMCP  ACP
----  -----------            -----  ---
nb-NO Norsk (bokmål) (Norge)   850 1252
```

```r
Sys.getenv("LC_ALL") # Note that this must be set to nb.utf8, otherwise we are unable to even run the string "øæå" to the console.
"nb.utf8"
```

```bash
Quarto 1.4.468
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.468
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252
 
[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)
 
[>] Checking LaTeX....................OK
      Tex:  (not detected)
 
[>] Checking basic markdown render....OK
 
[>] Checking Python 3 installation....(None)
 
      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/
 
[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/ØrjanArnevigSamuelse/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25
 
[>] Checking Knitr engine render......OK
```

### Steps to reproduce the problem
````qmd
---
format: html
---

# Regular text works

```{r}
1+1 # R chunk fails
```
````

### Describe the behavior you expected

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Adding this for consideration in the upcoming release; it would be good to check if this issue still occurs in the latest daily builds.

**Comment by gtritchie** [comment]
Confirmed this still happens with:

- 2023.12.1+402 "Ocean Storm" Release
- 2024.04.0-daily+462 "Chocolate Cosmos" Daily 

For example:

```
==> quarto preview quarto-test.qmd --to default --no-watch-inputs --no-browse


ERROR: Error executing 'C:\Users\Orjan\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe': The system cannot find the path specified. (os error 3)

Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```

**Comment by kevinushey** [comment]
This appears to be a Quarto bug, given that the issue occurs while RStudio is invoking `quarto preview`.

In my case, I installed R into a path as follows:

```
> R.home()
[1] "C:/鬼/R/R-4.3.2"
```

and so running `quarto preview` gives me:

```
==> quarto preview qqz.qmd --to html --no-watch-inputs --no-browse


ERROR: Error executing 'C:\?\R\R-4.3.2\bin\x64\Rscript.exe': The filename, directory name, or volume label syntax is incorrect. (os error 123)

Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```
