### ISSUE TITLE
Layout: git branch placement in the console rather than menu bar

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14017]
As RStudio plans for allowing projects to be renamed #1909 in the next release, I would propose to move the branch name out of the window name.

![image](https://github.com/rstudio/rstudio/assets/52606734/3cbc0f8f-ee80-4360-9628-64ad62dc0cd9)

It doesn't need to be displayed when switching tasks either.

I would suggest to add this to the console, as it would be more visible. I think that this would be a more appropriate place to showcase it.

In VScode, it is displayed in the bottom toolbar (but RStudio doesn`t have one.

![image](https://github.com/rstudio/rstudio/assets/52606734/8e7f9a36-aa76-451c-a627-118327fcd1a4)

Feel free to close, if people tend to open different branches of the same project in different RStudio sessions? Not sure it would work since the branches would likely pollute each other?

I saw in a video that Hadley uses a [prompt](https://github.com/gaborcsardi/prompt) to show the git branch. This FR would eliminate this need. Personally, I forget to open new branches, because I don't realize I am still on main. This would help!

Thanks for RStudio!

On another related note:
I think that the layout could be reviewed more broadly. For one, I think it would be awesome if RStudio desktop had a similar [layout as [RStudio Server](https://user-images.githubusercontent.com/470418/138955266-cd2b9e01-8de2-4f80-ad6e-c3849034c80b.png)
Related to #12249 and #1685

**Comment by gtritchie** [comment]
Another issue related to window title tweaks: https://github.com/rstudio/rstudio/issues/2427

**Comment by gtritchie** [comment]
If we ever do this we'd probably have to make this an option (show branch in title/show branch in console/show branch in both); I imagine some would love the change, some would prefer the old behavior, etc.

Also suspect if we show the branch in the Console toolbar the next request would be to make it a dropdown that can also be used to change the current branch, saving a trip to the Git tab or the command-line.

**Comment by gtritchie** [comment]
A more ambitious change would be to add a bottom status bar as seen in VSCode and most other IDEs, and show the branch there. In our ample spare time, of course.

**Comment by olivroy** [comment]
> If we ever do this we'd probably have to make this an option (show branch in title/show branch in console/show branch in both); I imagine some would love the change, some would prefer the old behavior, etc.

Indeed a good idea for mitigation. But as a matter of fact, this only really affects windows, because the dock icon doesn't show the branch name by default on Mac, only on windows.
![image](https://github.com/rstudio/rstudio/assets/52606734/685b03cf-598d-45bd-9fec-b270c5554427)

On Mac I don't see the branch

> Also suspect if we show the branch in the Console toolbar the next request would be to make it a dropdown that can also be used to change the current branch, saving a trip to the Git tab or the command-line.

Oh, wow, this would be great!

**Comment by gtritchie** [comment]
The branch is shown in the Mac title bar, same as on Windows and Linux.

It is true, however, that the dock icon on macOS only shows the project name, not the branch.

For example, have a project named "aaa" opened in Mac RStudio with branch "main":

<img width="701" alt="Screenshot of RStudio on macOS showing branch in title bar" src="https://github.com/rstudio/rstudio/assets/10569626/8990b034-c9f8-4f18-85a0-bff055087d5b">

**Comment by olivroy** [comment]
Thanks for clarifying. I updated my comment accordingly.

**Comment by ronblum** [comment]
@gtritchie Maybe we should see if @olivroy wants to make this contribution, as he's already made at least one so far. 🙂

**Comment by olivroy** [comment]
I'd be happy to take a look with some guidance!

**Comment by gtritchie** [comment]
> I'd be happy to take a look with some guidance!

What platform do you work on? It's easiest (relatively speaking) to do development work on RStudio on Macs and Linux, less easy (but doable) on Windows.

Rather than chat in github, how about you email me at gary at posit dot co and we can continue there!

**Comment by olivroy** [comment]
I still don't know how to set up a dev environnent due to my old system (macOS 10.15) but the fix could be somewhat similar to this one https://github.com/rstudio/rstudio/pull/14810
