### ISSUE TITLE
Update Ace

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14021]
We updated to Ace 1.28 in 2023.12 / Ocean Storm. Ace is making frequent releases these days (now at v1.32 as of this writing) including accessibility fixes and new features, so we should aim to update again in the 2024.04 IDE release.

**Comment by kevinushey** [comment]
We now have an Ace branch for Chocolate Cosmos: https://github.com/rstudio/rstudio/blob/017994e650caa386966773e1208a338354b62074/src/gwt/tools/sync-ace-commits#L4

This was branched from Ace 1.32.5.
