### ISSUE TITLE
Feature request: add search function to data viewer

### ISSUE THREAD

**Issue by apsalverda** [rstudio/rstudio#14024]
The data viewer, activated by for instance "View(iris)", has a box with a magnifying glass in the top right corner that acts as a filter, showing only rows that match data entered in this box. It would be very helpful if the viewer also had the option to search for text. 

What I imagine is that the user would enter text in a search box and the viewer would navigate to the first occurrence of that text, showing some preceding and following rows. The user would then click "Next" or "Previous" to jump to the next or previous occurrence of the text.

**Comment by ronblum** [comment]
@apsalverda Thank you for the request! We'll consider it as we continue development of RStudio.
