### ISSUE TITLE
Inconsistent display of column of type "ivs_iv" "vctrs_rcrd" "vctrs_vctr" across IDE 

### ISSUE THREAD

**Issue by cathblatter** [rstudio/rstudio#14025]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1+494 Desert Sunflower (desktop)
    OS Version      : macOS Ventura 13.6.2
    R Version       : R version 4.3.2 (2023-10-31)

### Steps to reproduce the problem

Its difficult to reproduce the problem, as it occurs inconsistently, but this is an attempt: 

```
# create a test example and save it in a temporary space
(test_df <- tibble::tibble(id = 1:5, 
                   grp = c("a", "a", "b", "b", "b"),
                   start = rep(lubridate::today()+1:5),
                   end = start+7))

# adding an iv-variable to the dataframe
(test_df_iv <- test_df |> 
    dplyr::mutate(range = ivs::iv(start, end)))

# save locally
save(list = "test_df_iv", file = "test_df_iv.RData")

# completely restart RStudio
#  cmd+shift+0 (mac)

# (or manually open the file, same behaviour)

# load the object
load("test_df_iv.RData")

# checking the head reveals this:
head(test_df_iv)

# further details below
```
### Describe the problem in detail

I have two problems: 
1) When I open an object where a column of type ivs_iv is present, I get mismatching display between using code (`head()`) to look at the code and previewing the data in the enviroment (clicking the little white arrow in the blue circle) or using `View()`. 
 Notice in `head()` only the first two rows are filled, the others are shown as NULL. 

There are occurences where I cannot reproduce this (and the display is equivalent both in head(), View() and manual clicking).

2) Sometimes when attaching the tidyverse and trying again to `View()` this object I get an error as follows: 

```
Error in `as.character()`:
! Can't convert `x` <ivs_iv> to <character>.
---
Backtrace:
    ▆
 1. └─.rs.formatDataColumn(`<ivs_iv>`, 1L, 144L)
 2.   └─.rs.formatDataColumnList(col, ...)
 3.     ├─base::as.character(col)
 4.     └─vctrs:::as.character.vctrs_vctr(col)
```

I attached a short video to show what I observe:

https://github.com/rstudio/rstudio/assets/24943957/27eb0492-9dea-4fe5-b963-802b3d757c31

Number 1) might be an issue with the IDE and number 2) might be an issue with my packages, though I did update all of them. Feel free to close, if it doesn't match all needs for a bug report, I really tried my best despite not being able to track the issue down (is it the IDE, is it a package ({vctrs}, {ivs}, {tidyverse},...). Thanks for consideration.

### Describe the behavior you expected

I would like to use ivs-columns as part of my intermedia data-objects. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The problem here is that loading your dataset does not attach the packages which know how to handle that data:

```
> load("test_df_iv.RData")
> search()
 [1] ".GlobalEnv"        "tools:rstudio"     "package:stats"     "package:graphics"  "package:grDevices"
 [6] "package:utils"     "package:datasets"  "local:rprofile"    "package:methods"   "Autoloads"        
[11] "package:base"     
```

You need to manually load `dplyr` and `ivs` after loading your data.

**Comment by cathblatter** [comment]
thanks for answering quickly!
