### ISSUE TITLE
run a code chunk in .rmd file without unfolding the code chunk

### ISSUE THREAD

**Issue by daxiagithub** [rstudio/rstudio#14022]
Currently in "Source" mode, when you click on the run arrow, the code chunk automatically unfolded.  In "Visual" mode, you can't even have access to the run arrow until you unfold the code chunk.

Thanks!

**Comment by ronblum** [comment]
@daxiagithub Thank you for the enhancement suggestion! We'll review it as we continue to develop RStudio.
