### ISSUE TITLE
Rstudio window does not move to a second screen when dragged

### ISSUE THREAD

**Issue by andrew-caudillo** [rstudio/rstudio#14035]
### System details

    RStudio Edition : 
    RStudio Version : 2023.09.1+494
    OS Version      :  Windows 10
    R Version       :  4.3.1

### Steps to reproduce the problem
Using a 2+ monitor setup, drag an Rstudio window to another screen

### Describe the problem in detail
The dragged Rstudio window snaps back to the screen it was dragged from and appears as a small square window

### Describe the behavior you expected
The Rstudio window to appear in another window normally.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonvanausdeln** [comment]
@ronblum , I tried with 2023.09.1+494 on Windows 11 and see no issues with moving between monitors.

**Comment by andrew-caudillo** [comment]
@ronblum , I apologize for letting this slip through the cracks. My issue is the following:
1. I have a laptop that is connected to 2 monitors
2. When I move from laptop to a monitor, there is no issue
3. When I move from monitor to monitor, the windows shrinks down and bounces back to the monitor it was being pulled from.

See the attached video for further info

https://github.com/rstudio/rstudio/assets/84486509/58c8cc80-1636-4b15-b620-8a2c3bda08c8
