### ISSUE TITLE
Cannot create BrowserWindow

### ISSUE THREAD

**Issue by porliange** [rstudio/rstudio#14045]
On Windows Server 2019, using RStudio 2022.12.0 Build 353 (same issue using 2023.06.2-561)

I have this error message, and RStudio does not start:
![error_rstudio](https://github.com/rstudio/rstudio/assets/33019271/5cbe6fb5-cd9e-4732-b54a-437c0c31a070)

Studio works fine on this serveur for all users except one.

**Comment by porliange** [comment]
I finaly remove the user profile on the server, he reconnect on the server and RStudio works again.

**Comment by ronblum** [comment]
@porliange Great! Is RStudio continuing to run smoothly?

**Comment by porliange** [comment]
Yes, it's now working fine. Thanks
