### ISSUE TITLE
Diagnostic Warning for "missing argument to function call" When Diagnostics for Function Calls Are Disabled

### ISSUE THREAD

**Issue by jesse-smith** [rstudio/rstudio#14046]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1
    OS Version      : Windows 10 Enterprise 22H2
    R Version       : 4.3.2

#### Set Up Diagnostics Options
1. Navigate to Tools -> Global Options -> Code -> Diagnostics
2. Ensure "Show diagnostics for R" *is* enabled
3. Ensure "Enable diagnostics within R function calls" *is not* enabled
4. Ensure "Check arguments to R function calls" *is not* enabled
5. Click "Apply" and "OK"
#### Reproduce Warning
6. Create a new R file
7. Save the new file (this warning does not appear if the fileis not saved to disk)
8. Add the code (full reprex w/ session info under the next header):
``` r
df <- data.frame(x = 1:3)
b <- function(x, ...) x[...]
b(df,, 1) # Warning will appear here
```
10. Wait for `⚠️ missing argument to function call` warning to appear

### Describe the problem in detail
I discovered this issue when creating a pipe-able single-bracket (`[`) function. A leading comma with no argument before it triggers a diagnostic warning, even when "Check arguments to R function calls" and "Enable diagnostics within R function calls" are disabled. I have found two sufficient conditions for disabling the warning:
* Uncheck "Show diagnostics for R"
* Do not save the file to disk

A minimal reprex is below (code only - see above for RStudio settings).

``` r
# Create example data
df <- data.frame(x = 1:3)
# Define example function
b <- function(x, ...) x[...]
# Call example function
b(df,, 1) # Warning will appear here
#> [1] 1 2 3
```

<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31 ucrt)
#>  os       Windows 10 x64 (build 19045)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.utf8
#>  ctype    English_United States.utf8
#>  tz       America/Chicago
#>  date     2023-12-12
#>  pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.1   2023-03-23 [1] CRAN (R 4.3.2)
#>  digest        0.6.33  2023-07-07 [1] CRAN (R 4.3.2)
#>  evaluate      0.23    2023-11-01 [1] CRAN (R 4.3.2)
#>  fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.2)
#>  fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.2)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.3.2)
#>  htmltools     0.5.7   2023-11-03 [1] CRAN (R 4.3.2)
#>  knitr         1.45    2023-10-30 [1] CRAN (R 4.3.2)
#>  lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.3.2)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.2)
#>  purrr         1.0.2   2023-08-10 [1] CRAN (R 4.3.2)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.3.2)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.3.1)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.3.1)
#>  R.utils       2.12.3  2023-11-18 [1] CRAN (R 4.3.2)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.3.2)
#>  rlang         1.1.2   2023-11-04 [1] CRAN (R 4.3.2)
#>  rmarkdown     2.25    2023-09-18 [1] CRAN (R 4.3.2)
#>  rstudioapi    0.15.0  2023-07-07 [1] CRAN (R 4.3.2)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.3.2)
#>  styler        1.10.2  2023-08-29 [1] CRAN (R 4.3.2)
#>  vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.3.2)
#>  withr         2.5.2   2023-10-30 [1] CRAN (R 4.3.2)
#>  xfun          0.41    2023-11-01 [1] CRAN (R 4.3.2)
#>  yaml          2.3.7   2023-01-23 [1] CRAN (R 4.3.2)
#> 
#>  [1] D:/ProgramFiles/R/R-4.3.2/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

### Describe the behavior you expected
I would expect this warning to be triggered only if "Check arguments to R function calls" is enabled (following the explanation given in the [user guide](https://docs.posit.co/ide/user/ide/guide/code/diagnostics.html#check-arguments-to-r-function-calls)). I could also see a case for attaching this behavior to "Enable diagnostics within R function calls" (though it seems to fit more naturally  in the "Check arguments..." category IMO). 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jesse-smith Thank you for raising the issue! I can reproduce this in older versions of RStudio as well, such as RStudio Desktop 2022.07.2+576 on MacOS 14.2.

@kevinushey Is this intentional or incorrect?

**Comment by kevinushey** [comment]
Thanks! This seems like an oversight; we should fix this on RStudio's side.

Internal note: check https://github.com/rstudio/rstudio/blob/bf6043eab32ea324f493508f3d760be7d716e862/src/cpp/session/modules/SessionRParser.hpp#L446-L451 + its usages.

**Comment by kevinushey** [comment]
Thanks; will be fixed in the next daily builds!

<img width="358" alt="Screenshot 2024-01-24 at 1 21 53 PM" src="https://github.com/rstudio/rstudio/assets/1976582/fbfdf7b3-7cc8-483d-8e81-e5cf22b6a1a5">
