### ISSUE TITLE
Login failed in FreeIPA's password+otp authentication environment

### ISSUE THREAD

**Issue by geonmo** [rstudio/rstudio#14044]
Hello, rstudio community.

I am running an authentication system based on freeipa(LDAP-like). 

In that system, I can select password or password+otp authentication for each user, and some users are logging in with password+otp.

Currently, I have found that users who authenticate with password+otp cannot log in to rstudio.

This is probably because the PAM-related module pam_conversation is not able to handle such logins.

If we connect with password+otp, the connection method will be changed as below.

~]$ pamtester rstudio user authenticate
First Factor: 
Second Factor: 
pamtester: successfully authenticated

Could you please refer to the above and add a feature to allow access from freeipa OTP environment?

**Comment by gtritchie** [comment]
See the associated PR for comments on why we aren't doing this.
