### ISSUE TITLE
Update dependencies for Desktop IDE

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#14055]
Update Electron and other packages.

**Comment by timtmok** [comment]
This updates Chromium to `120.0.6099.56`

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+270 on MacOS 14.3.



![Image](https://github.com/rstudio/rstudio/assets/31009952/4ec60b74-43aa-4b8f-9420-9b0f664ea48b)
