### ISSUE TITLE
No "Run" button for dot/graphviz engine chunks

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#14063]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.12.0+369 (2023.12.0+369)
    OS Version      : Mac
    R Version       : 4.2.0

### Steps to reproduce the problem

Example code and requires local install of `brew install graphviz` on Mac.

````
```{dot}
graph G {
  layout=neato
  run -- intr;
  intr -- runbl;
  runbl -- run;
  run -- kernel;
  kernel -- zombie;
  kernel -- sleep;
  kernel -- runmem;
  sleep -- swap;
  swap -- runswap;
  runswap -- new;
  runswap -- runmem;
  new -- runmem;
  sleep -- runmem;
}
```
````

### Describe the problem in detail

While GraphViz can be run with Run All or other shortcuts, there is no "Run" green button in the chunk even in inline execution mode: 
![image](https://github.com/rstudio/rstudio/assets/29187501/82f8b73c-36b8-4957-a64a-cde555c7794d)

I'm not sure if this was intended but we do expect that https://github.com/rstudio/rstudio/pull/13745 allows for inline execution.

### Describe the behavior you expected

Given you _can_ run GraphViz inline, I'd expect a run button for that chunk.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Also the case for R Markdown. Reproducible in 2022.07.2-576 as well.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2024.04.0-daily+495 on MacOS 14.4
- Posit Workbench 2024.04.0-daily+478.pro12 on Ubuntu 22.04 via Chrome on MacOS 14.4

Check
- Arrow appears and chunk runs correctly when clicked
- "Run All Below" etc. work correctly
- Source and visual mode
- R Markdown and Quarto documents
