### ISSUE TITLE
Remove Copilot preview label and disclaimer

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#14067]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2023.12.0+363
    OS Version      : Any
    R Version       : N/A

### Steps to reproduce the problem

Go to the Copilot Global and Project Options.

### Describe the problem in detail

We still tell people that Copilot is in preview mode.

### Describe the behavior you expected

Let's celebrate and remove the "preview" label and disclaimer. 🕺 

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I think this is worth fixing for the next patch release, given our intention to announce Copilot as GA in this release.

**Comment by kelli-rstudio** [comment]
### Verified Fixed
    RStudio Edition    :  Desktop and Workbench
    RStudio Version(s) : 2023.12.1+377.pro1 and 2024.04.0-daily+190.pro3
    OS Version         : MacOS (Desktop) and ubuntu22 (Workbench)

### Test scenario(s) 
Verified that preview messaging was removed from GH Copilot Project and Global Options.

### Automated tests 
Tests were updated to stop checking for preview messaging.
