### ISSUE TITLE
curl not able to load from Rstudio but does load from R running in Rstudio terminal

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#14060]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.12.0 Build 330 (also occurs in Build 369)
    OS Version      :  Ubuntu 22
    R Version       : 4.3.2

### Steps to reproduce the problem

Run the below:

docker run --rm -p 8989:8989 vnijs/rsm-msba-arm:2.9.1

Start browser at: http://localhost:8989/rstudio/

### Describe the problem in detail

Try `library(curl)` in Rstudio's console and Rstudio's terminal. Runs fine in the terminal, but not the console.

Console:

> library(curl)
Error: package or namespace load failed for ‘curl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/conda/lib/R/library/curl/libs/curl.so':
  /lib/aarch64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /opt/conda/lib/R/library/curl/libs/../../../../libcurl.so.4)

Terminal:

> library(curl)
Using libcurl 8.5.0 with OpenSSL/3.2.0

Issue does not occur when using the previous version of the docker container.

docker run --rm -p 8989:8989 vnijs/rsm-msba-arm:2.9.0

### Describe the behavior you expected

`library(curl)` works in both the console and the terminal

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
If I understand correctly, the problem here is that RStudio links to and uses the system version of OpenSSL, but that version isn't compatible with the one in your Conda installation:

```
> system(paste("lsof -p", Sys.getpid(), "| grep ssl"))
rsession 2496 jovyan  mem       REG              253,1          3065535 /usr/lib/aarch64-linux-gnu/libssl.so.3 (path dev=0,170)
```

Compare the same command with an R session from a terminal:

```
> system(paste("lsof -p", Sys.getpid(), "| grep ssl"))
R       3625 jovyan  mem    REG  253,1          4223221 /opt/conda/lib/libssl.so.3 (path dev=0,170)
```

I suspect you'll need to set `LD_LIBRARY_PATH` so that libraries within your Conda installation are preferred to the system equivalents, or something similar.

**Comment by vnijs** [comment]
Thanks @kevinushey. That was very helpful.

**Comment by jrdnbradford** [comment]
What setup for `LD_LIBRARY_PATH` finally got this resolved for you, @vnijs? I'm having this exact problem and cannot find a variable setting for `LD_LIBRARY_PATH` in RStudio that resolves my issue.

`libssl` in RStudio console: `/usr/lib/x86_64-linux-gnu/libssl.so.3`
`libssl` in `R` within a terminal: `/opt/conda/lib/libssl.so.3`

No matter what I set `LD_LIBRARY_PATH` to in RStudio I always get:
```R
library(curl)
Error: package or namespace load failed for ‘curl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/conda/lib/R/library/curl/libs/curl.so':
  /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /opt/conda/lib/R/library/curl/libs/../../../../libcurl.so.4)
```

**Comment by jrdnbradford** [comment]
I fixed it with:
```bash
echo "rsession-ld-library-path=/opt/conda/lib" >> /etc/rstudio/rserver.conf 
```

**Comment by leehach** [comment]
Just a note that this also fixes the same problem in running RStudio Desktop in a conda environment.

```
conda env config vars set LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
```
