### ISSUE TITLE
Copilot project options "Loading..." message never goes away

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14064]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0+369
    OS Version      : macOS 14.2
    R Version       : 4.3.1

### Steps to reproduce the problem
- ensure copilot is not enabled in Global Options
- open an R project
- look at copilot settings in Project Options dialog

### Describe the problem in detail

The message "(Loading...)" never goes away. It seems harmless, but somebody might stare at it forever waiting to see what exciting things eventually get loaded, and they might get really hungry.

<img width="588" alt="screenshot of project options copilot pane showing the (Loading...) message" src="https://github.com/rstudio/rstudio/assets/10569626/ecff8303-7b39-4467-a8c2-3f50dbf83c4d">

### Describe the behavior you expected

No teasing that something might eventually load.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 2024.04.0-daily+270 on MacOS 14.3
- RStudio Server 2024.04.0-daily+270 on SLES 15 SP 5 via Chrome on MacOS 14.3
