### ISSUE TITLE
Docs: Enable `search copy-button` for all guides

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#14069]
@SamEdwardes had noted that it would be a convenience if we were able to copy/share search results. After some digging, it seems that quarto offers this functionality and that it is simple to implement.

In the `quarto.yml`, add the following entry:

```
website:
  search:
    copy-button: true
```

@AshleyHenry15 tested this for the admin guide and it works as expected:
- The copy button displays in the search box
- Clicking the copy button copies the URL for the search results
- Pasting the URL in another window automatically opens the search results.

<img width="677" alt="image" src="https://github.com/rstudio/rstudio-pro/assets/31460023/757e8795-79a8-4e5f-be4f-de11ce5daf41">

Implement for the following guides:

- [x] IDE User Guide
- [x] Release Notes

Companion issue for Workbench `rstudio-pro` changes here: https://github.com/rstudio/rstudio-pro/issues/5603

**Comment by jthomasmock** [comment]
That change makes sense to me - do you want to go ahead and open a small PR for it?

**Comment by AshleyHenry15** [comment]
@jthomasmock - I always appreciate as much help that is offered :)

**Comment by petetronic** [comment]
Confirmed search copy button now shows on daily IDE User Guide, and copying captures the query in a URL, e.g.
https://docs.posit.co/ide/user/2024.04.0/?q=Copilot&show-results=1

**Comment by petetronic** [comment]
@AshleyHenry15 are we also intending to add this to the News / Release notes?
https://github.com/rstudio/rstudio/blob/main/docs/news/_quarto.yml#L8C1-L9C1

**Comment by AshleyHenry15** [comment]
@petetronic - I had added an entry already but since I forgot to add it to the news doc project, I also failed to add it to the release notes entry: https://github.com/rstudio/rstudio/blob/067a12b935b22cb7cc24eafda14e65b19a4cc0d0/NEWS.md?plain=1#L29

**Comment by ronblum** [comment]
Verified in revision 30 of the RStudio User Guide https://docs.posit.co/ide/user/2024.04.0 . Search results return the URL https://docs.posit.co/ide/user/2024.04.0/?show-results=1&q=search which shows the most recent search and results. Running a new search updates the results using the same URL.
