### ISSUE TITLE
Docs: Copyright needs to be updated.

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#14078]
All docs, this needs to be updated:
>Copyright © 2022 Posit Software, PBC. All Rights Reserved.

Companion issue in pro: https://github.com/rstudio/rstudio-pro/issues/5614

```[tasklist]
### Tasks
- [x] IDE User Guide: 2009-2024
- [x] Release Notes: 2011-2024 (reference https://github.com/rstudio/rstudio.com/blob/master/content/products/rstudio/release-notes/rstudio-0-93.md)
```

**Comment by petetronic** [comment]
This work was merged, moving to Test

**Comment by petetronic** [comment]
Confirmed copyright range is updated in daily IDE docs:
https://docs.posit.co/ide/user/2024.04.0/

The release notes also reflect the requested range today:
https://docs.posit.co/ide/news/
