### ISSUE TITLE
RStudio 2023.12.0.369 no longer auto-completes Quarto chunk options

### ISSUE THREAD

**Issue by kputschko** [rstudio/rstudio#14074]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0.369
    OS Version      :  Windows 11 Pro 10.0.22631 Build 22631
    R Version       :  4.3.2

### Steps to reproduce the problem

Open a new Quarto document and create a code chunk. 

````
```{r}
|# label: 

```                   #end-chunk
````

### Describe the problem in detail

After typing `#|` there is no popup listing all the available options for code chunks.

### Describe the behavior you expected

I used to be able to start the code option and scroll through the entire list of options, or to narrow it down so that I don't have to memorize the exact option.  For example, I always forget how to specify chunk captions.  I used to be able to start the chunk, type 'cap' and wait for the auto-complete list to filter to all available options containing the string 'cap', leading me to remember that it is 'fig-cap'.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: auto-complete shows up if at least one letter is entered.

**Comment by kevinushey** [comment]
This may be fallout from some changes to how we tokenize Quarto comments. Our code completion class tries to suppress completions within a comment, e.g.

https://github.com/rstudio/rstudio/blob/79f40d52f86dc1d0124240ff068e230cb7500079/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java#L285-L287

But we should allow Quarto chunk comments here.

**Comment by ronblum** [comment]
Verified in Posit Workbench 2024.04.0-daily+397.pro21 on RHEL 9 that labels show up when triggered with <kbd>Tab</kbd> or <kbd>Ctrl-Space</kbd>.

However, when starting to type a label name, the match is only made with the beginning of the label name. So in the example above, `cap` only returns `cap-location` but not `fig-cap`. @kevinushey Should the match be made as is or should it be for anything in the label name?

**Comment by kevinushey** [comment]
What was the behavior for prior releases of RStudio + Quarto?

Completions here are handled by Quarto, so I think if we wanted a change in behavior we'd have to relay that to the Quarto team.

**Comment by ronblum** [comment]
Earlier releases (2023.06.2+561 and 2023.09.1+494) had the same behavior. So this is behaving correctly, and changing it would be a separate enhancement request.  Thanks!
