### ISSUE TITLE
Data viewer isn't auto-refreshing in the new Dec 2023 version

### ISSUE THREAD

**Issue by mparedes96** [rstudio/rstudio#14082]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.12.0+369 "Ocean Storm"
    OS Version      :  Windows 11 Home Single Language (22H2)
    R Version       :  4.3.1

### Steps to reproduce the problem
1. Open an object (matrix, array, data frame, etc.) directly from the Environment or through the View() command.
2. Keep the Viewer open/active.
3. Edit a cell, column, or row of this object.
4. Check the object at the changed values.
5. You will notice the issue if the Viewer doesn't 'blink' when you change windows.

### Describe the problem in detail

I installed RStudio's new version (Ocean Storm, 2023.12.0+369) on Wednesday and have encountered this issue since then. When I modify a matrix, array, or data frame-like object while having it open in the Viewer, the new values don't show up visually (I have checked by calling through the console like df[modified row, ], and they do have the new values, but this doesn't affect the visual object in the Viewer). I had to close and re-open the data frame to see the changes take place. 

This auto-refresh issue has also happened in other versions for other users, but this version was the first time for me.

### Describe the behavior you expected
I expected the data inside the data frame to auto-refresh when opening the Viewer again. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio and confirmed that the issue persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Related: https://github.com/rstudio/rstudio/pull/13863

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2024.04.0-daily+270 on MacOS 14.3
- RStudio Server 2024.04.0-daily+270 on SLES 15 SP5 via Chrome on MacOS 14.3

New behavior: Data is always refreshed.

Old behavior:

```
x <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6), c = c("a", "b", "c")) 

View(x) # Correct data displayed

x[1, "a"] <- 11 # Data not updated
x[2, "b"] <- 22 # Data not updated 
x[3, "c"] <- "q" # Data not updated

View(x) # Data correctly refreshed

x <- cars # Data correctly refreshed
x[3, "c"] <- "q" # Data correctly refreshed
x[3, "c"] <- "e" # Data not updated

View(x) # Data correctly refreshed
```

Also verified that #13856 wasn't reintroduced.
