### ISSUE TITLE
data.table set() creates a new column by ref, that disappears right after first accessing it

### ISSUE THREAD

**Issue by fabiocs8** [rstudio/rstudio#14085]
### System details

    RStudio Edition : Desktop

    RStudio Version : 
RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-17) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

    OS Version      : 
Edição	Windows 10 Home Single Language
Versão	22H2
Instalado em	‎27/‎08/‎2020
Compilação do SO	19045.3803
Número de série	PE02U1N8
Experiência	Windows Feature Experience Pack 1000.19053.1000.0

    R Version       :  
R version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

### Steps to reproduce the problem
[sample_env.zip](https://github.com/rstudio/rstudio/files/13798805/sample_env.zip)

```
library (data.table)
 # # at this point please reconstruct the environment I sent as sample_env.RData, that is inside sample_env.zip.  
 # # dt data.table will appear
dt[, dc := descricao_complementar, verbose = T] #  executes ok
dt$dc #  just to see if dc was created. Executes ok and I can see dc data
dt [, dc := gsub("G\,ML\b", "G/ML", dc, perl=T)]  # ERROR!!!!!!!!
Error in eval(jsub, SDenv, parent.frame()) : objeto 'dc' não encontrado
```

### Describe the problem in detail

This issue is related to [https://github.com/Rdatatable/data.table/issues/5865](url)

I have a data.table dt. Then I create two new columns:
dt[ , id := .I, verbose = TRUE]
Detected that j uses these columns:
Assigning to all 7103 rows
RHS_list_of_columns == false
RHS for item 1 has been duplicated because NAMED==65535 MAYBE_SHARED==1, but then is being plonked. length(values)==7103; length(cols)==1)

dt[ , dc := descricao_complementar, verbose = TRUE]
Detected that j uses these columns: descricao_complementar
Assigning to all 7103 rows
RHS_list_of_columns == false
Direct plonk of unnamed RHS, no copy. NAMED==1, MAYBE_SHARED==0

At this point, I am able to see both columns at RStudio command View(dt). Also, dt$dc correctly shows the contents for dc.

However, when I run the next command, I get an error:

dt[, dc := gsub("G\,ML\b", "G/ML", dc, perl=T)]
Error in is.factor(x) : object 'dc' not found

And the two following commands also provide errors:

dt$id
NULL
dt$dc
NULL

It seems that both columns have both disapeared!

I have this code working properly for many months, and this problem manifested for the first time only today.

### Describe the behavior you expected

I expected that both new columns have not disappeared.

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by fabiocs8** [comment]
IMPORTANT HINT: RStudio may be confusing data.table dt with stats::dt()

**Comment by kevinushey** [comment]
Sorry, but I'm not able to reproduce. I tried running the following code gleaned from your example:

```
# work in tempdir
setwd(tempdir())

# install and load data.table
.libPaths(tempdir())
install.packages("data.table")
library(data.table)

# download sample data
url <- "https://github.com/rstudio/rstudio/files/13798805/sample_env.zip"
download.file(url, destfile = basename(url))
unzip("sample_env.zip")
load("sample_env.Rdata")

# run example code
dt[, dc := descricao_complementar, verbose = T]
dt$dc
dt[, dc := gsub("G,ML\b", "G/ML", dc, perl=T)]
```

but that ran without issue for me. I think we'll need more information in order to reproduce this issue successfully.

**Comment by fabiocs8** [comment]
I tried my best to provide a minimal reproducible example, with no success. The best I got was to capture the environment when the error occurs, but it seems that you also could not reproduce.

This error seems to be related to an internal state of RStudio (thus difficult to reproduce) when tracking data.table dt:
-    when I source the same code in the Terminal, or when I use Rscript, the error does not show up;
-    Note that in data.table, the code dt[, dc := descricao_complementar], dc is created by reference. It is common that just after creating by reference, the new column dc does not show up in the dt in the Environment window, unless you reload manually. I can´t tell whether or not these behaviors are related to each other.

**Comment by fabiocs8** [comment]
Maybe you can instruct me how to gather my current RStudio environment (at a low level copy) just before the error occurs.

**Comment by fabiocs8** [comment]
News: 

1.  I noticed that  after running `dt[, dc := descricao_complementar, verbose = T]`,  if I run `dt` afterward it does not echo in the screen. It only echoes when I run for the second time, and sometimes dc new column appears, sometimes it doesn´t;

2.  Afterwards, I also noticed that when the command `dt[, dc := gsub("G,ML\\b", "G/ML", dc, perl=T)]`  runs by a Control+Enter from a copy in another R file (say Untitled.R),  it executes properly!! In other words, the error occurrence depends on the file one executes the code by Control+Enter! Weird.

**Comment by fabiocs8** [comment]
More news: when using reprex, I get a different error:

``` r
library(data.table)
dt |> is.data.table()  # It is a data.table when I run outside reprex
#> [1] FALSE
dt <- copy(dt)
setDT(dt)
#> Error in setDT(dt): Argument 'x' to 'setDT' should be a 'list', 'data.frame' or 'data.table'
dt |> is.data.table()
#> [1] FALSE
dt[, dc := descricao_complementar |> as.character()]
#> Error in `:=`(dc, as.character(descricao_complementar)): Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

dt[, dc := gsub("G\\,ML\\b", "G/ML", dc, perl=T)]
#> Error in `:=`(dc, gsub("G\\,ML\\b", "G/ML", dc, perl = T)): Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
```

<sup>Created on 2024-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.3.2 (2023-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8   
#> [3] LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C                      
#> [5] LC_TIME=Portuguese_Brazil.utf8    
#> 
#> time zone: America/Sao_Paulo
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] data.table_1.14.10
#> 
#> loaded via a namespace (and not attached):
#>  [1] styler_1.10.2     digest_0.6.33     fastmap_1.1.1     xfun_0.41        
#>  [5] magrittr_2.0.3    glue_1.6.2        R.utils_2.12.3    knitr_1.45       
#>  [9] htmltools_0.5.7   rmarkdown_2.25    lifecycle_1.0.4   cli_3.6.2        
#> [13] R.methodsS3_1.8.2 vctrs_0.6.5       reprex_2.0.2      withr_2.5.2      
#> [17] compiler_4.3.2    R.oo_1.25.0       R.cache_0.16.0    purrr_1.0.2      
#> [21] rstudioapi_0.15.0 tools_4.3.2       evaluate_0.23     yaml_2.3.8       
#> [25] rlang_1.1.2       fs_1.6.3
```

</details>

**Comment by fabiocs8** [comment]
Last remainder, the full code runs wonderfully when sourced or under Rscript.

**Comment by kevinushey** [comment]
A reprex needs to run standalone; because you never defined `dt`, you're just getting the version from `stats::dt`. You'd need to explicitly create / initialize your `dt` object with some code first.
