### ISSUE TITLE
Outdated information on the dailies.rstudio.com site for ARM builds

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14086]
Copied from a community post: https://community.rstudio.com/t/outdated-information-on-the-dailies-rstudio-com-site-for-arm-builds/179254

> This warning message at the top of the download page for ARM builds has not been true for a while now. I hope someone from the RStudio IDE team reads this and takes it out since it can discourage people from trying these builds.
>
> ... They do not include a bundled copy of Quarto or Pandoc (see [quarto-cli#190](https://github.com/quarto-dev/quarto-cli/issues/190)), so these tools must be installed separately to work with Quarto or R Markdown content. Please report any other issues with these builds to our [issue tracker](https://github.com/rstudio/rstudio/issues/new/choose)

For example: https://dailies.rstudio.com/rstudio/chocolate-cosmos/electron/jammy-arm64/

<img width="961" alt="Screenshot of download page with area of concern highlighted" src="https://github.com/rstudio/rstudio/assets/10569626/158fcd54-5f07-4b95-affc-79c6424c72f8">

**Comment by ronblum** [comment]
Putting into Chocolate Cosmos for the Quarto and Pandoc changes. The ARM builds are still considered experimental, though.

**Comment by kevinushey** [comment]
LGTM; screenshot from https://dailies.rstudio.com/rstudio/chocolate-cosmos/electron/jammy-arm64/:

<img width="547" alt="Screenshot 2024-03-21 at 10 46 10 PM" src="https://github.com/rstudio/rstudio/assets/1976582/a80b3dc2-8dc9-4381-9a05-6d9309089124">
