### ISSUE TITLE
R Studio hanging with Copilot

### ISSUE THREAD

**Issue by gabriellenz** [rstudio/rstudio#14095]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2023.12.0 22H2 Build 369 
    OS Version      :  Windows 11 Home 22621.2861
    R Version       :  4.3.2

### Steps to reproduce the problem
IDE hangs after a couple hours of editing and knitting with copilot. I haven't noticed anything else triggering it but it's happened at least five times after restarting the IDE and updating the IDE. IDE doesn't hang with copilot disabled. Diagnostics attached. 

### Describe the problem in detail
IDE stops knitting, stops saving, and Global Options/Copilot goes blank.  

### Describe the behavior you expected
NA

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/13850383/diagnostics-report.txt)

**Comment by kevinushey** [comment]
The next time this occurs, can you share a screenshot of what you see with Help -> Diagnostics -> Request Log as well? I wonder if some requests are getting "stuck" because of failing Copilot RPCs.

**Comment by gabriellenz** [comment]
Will do.

**Comment by gabriellenz** [comment]
Just crashed but the diagnostic won't run. I've attached the session log
file, in case that is helpful.

**Comment by Huangyiqiang1203** [comment]
same problem:
Help -> Diagnostics -> Request Log，
$version.string
[1] "R version 4.3.2 (2023-10-31 ucrt)"

$nickname
[1] "Eye Holes"

Warning message:
In download.file(copilotUrl, destfile = destfile, mode = "wb") :
the 'wininet' method is deprecated for http:// and https:// URLs
> options(download.file.method = 'libcurl')
>

Request ID: -1614853402

== REQUEST ======
{
"method": "get_events",
"params": [
1142
],
"clientId": "33e600bb-c1b1-46bf-b562-ab5cba070b0e",
"clientVersion": ""
}

== RESPONSE ======
undefined

**Comment by jthomasmock** [comment]
This may be related to large files being indexed - #14106 -- we have a fix in the dailies, do you mind testing with one of the daily builds that corresponds to 2023.12.1?

**Comment by gabriellenz** [comment]
Sorry for the slow response but I'm back on the same project and just
experienced the same hanging with 2023.12.1 Build 402.
