### ISSUE TITLE
Copilot UI strings not localized (or localizable)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14092]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2023.12.0+369 "Ocean Storm"
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

Switch the RStudio UI to French (Global Options / General / Advanced / User Interface Language. Then look at Copilot preferences (global and project), and use Copilot.

### Describe the problem in detail

Most UI strings for Copilot are hardcoded in the source and can't be localized. Examples (not comprehensive):

<img width="783" alt="screenshot of editor region in French showing English copilot message" src="https://github.com/rstudio/rstudio/assets/10569626/b47efc73-4062-4f4d-9b9c-2c95d002bcb2">

<img width="634" alt="screenshot of global options showing english copilot strings" src="https://github.com/rstudio/rstudio/assets/10569626/e0988b20-e307-427f-b797-7d5bacf31ff9">

### Describe the behavior you expected

UI strings should be localized.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified RStudio Server 2024.04.0-daily+270 on SLES 15 SP5 via MacOS 14.3.

Global options:
![Image](https://github.com/rstudio/rstudio/assets/31009952/3593596f-2aa3-490c-8d98-b687d90ed881)

Project options:
![Image](https://github.com/rstudio/rstudio/assets/31009952/01cf20a5-5e01-4f52-84e2-595540a7e30c)
