### ISSUE TITLE
Data and help view popout windows not showing

### ISSUE THREAD

**Issue by petermott** [rstudio/rstudio#14097]
### System details

    RStudio Edition : Desktop
    RStudio Version : RSTUDIO-2023.12.0-369
    OS Version      :  any
    R Version       :  4.3.2

### Steps to reproduce the problem
Do `view(iris)` and then Shift-F1 to open a separate window. Next select a help topic like `? cov` and then use `Ctrl-F2` to open the help in a separate window.  

### Describe the problem in detail
The first window opens but is blank.  The second window does not open (nothing happens)

### Describe the behaviour you expected
I expected the windows to open.

### Attempts to fix
Restart RStudio. Restart Windows. Re-install RStudio, checking the SHA256 code is correct.  Revert to RStudio 2023.09.1 Build 494. This last fixed the problem. 

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.

**Comment by snhansen** [comment]
I'm experiencing the same issue. Also on Windows with the same R and RStudio build.

**Comment by gtritchie** [comment]
<kbd>Shift</kbd>+<kbd>F1</kbd> and <kbd>Ctrl</kbd>+<kbd>F2</kbd> aren't standard keyboard shortcuts (you must have them customized with the first bound to "Show Document in New WIndow" and the second to "Show Help in New Window").

That said, I have been able to repro the problems. Sometimes I am able to get the window to open and load (both for help and the data viewer), sometimes the window opens but is blank (for the data viewer, haven't seen that for Help yet), and sometimes nothing happens at all (no window opens).

**Comment by gtritchie** [comment]
Have also reproduced on Mac, so isn't platform-specific.

**Comment by petermott** [comment]
Issue #12468 is the same, I think.

**Comment by gtritchie** [comment]
> Issue #12468 is the same, I think.

Yes, thanks for tracking that down. Keeping this newer issue open for now until I determine if the issue with the Help pane is the same underlying problem or something new and exciting.

**Comment by gtritchie** [comment]
Here's a consistent repro (at least for me), using 2023.12.0+369 "Ocean Storm".

- in the Console: `View(iris)` to show a data table
- in the Console: `? cat` to show content in the Help pane (this is critical; if you try these steps with the Help home page, it doesn't repro!)
- click the widget to show data viewer in a separate window (or use command palette "Show document in new window")
- in the separate window, click the widget to "Return to main window"
- try to show the help in a separate window either via the widget or "Show help in new window" via command palette

Problem: Nothing happens, no help window opens.

- now try to show the Data Viewer in a separate window (again); the window opens but doesn't display properly

<img width="547" alt="broken-data-viewer-window" src="https://github.com/rstudio/rstudio/assets/10569626/40359bd9-0919-47bd-8a0e-e80b7cb51a1f">

**Comment by gtritchie** [comment]
The help pane issue seems to be the key here, and there were some changes in this area for 2023.12. One example is https://github.com/rstudio/rstudio/pull/13582 (I haven't confirmed if this is the culprit, just a suspect at this point).

A more basic issue involving the help pane:

- start RStudio
- `? cat`
- try to show the help in a separate window (via button or command-palette) and nothing happens

Once you've done that, any attempts to show a data viewer in a separate window will result in that mostly-empty window mentioned earlier.

**Comment by gtritchie** [comment]
This was caused by this change: [explicitly use 'show_vignette' RPC when opening vignettes #13754](https://github.com/rstudio/rstudio/pull/13754). Commenting out these lines (added in that change) fixes the issue (but would break other things, so I will work on an actual fix):

https://github.com/rstudio/rstudio/blob/79f40d52f86dc1d0124240ff068e230cb7500079/src/node/desktop/src/main/desktop-browser-window.ts#L182-L196

**Comment by ronblum** [comment]
QA Notes:
- Help Pane interferes with Data Viewer
- Popping out Object Viewer works
- Presentation and Viewer Panes work (they get open in a web browser)

**Comment by kelli-rstudio** [comment]
Verified with 2024.04.0-daily-200 and 2023.12.1-daily-379 Desktop MacOS and Windows 11.

Checked that Data Viewer pops out and back in as expected after opening the Help Pane. Also checked that popping out the Object Viewer, Tutorial Pane, Presentation Pane, and Viewer Pane works as expected and that the Data Viewer continues to pop out/in as expected.
