### ISSUE TITLE
Git UI authentication message

### ISSUE THREAD

**Issue by linogaliana** [rstudio/rstudio#14103]
Rstudio's Git UI is a great way for beginners to learn about Git.

However, when pushing or pulling, the authentication box is misleading beginners that are not aware of the fact that Github does not authorize password authentication:

![image](https://github.com/rstudio/rstudio/assets/33896139/3ecc2061-7d10-4bee-ab3c-95662d2eaafe)

In Git training, many people don't understand the error that occurs when they enter their password (and not a token) in this dialog box:

![image](https://github.com/rstudio/rstudio/assets/33896139/ad2bdbf1-f89f-4866-86ba-bcd5c60f88ad)

Would it be possible to change the message to give it a more accurate meaning:

> Personal Access Token for XXXXX

Or, as Gitlab still allows password authentication

> Token / password for XXX

**Comment by ronblum** [comment]
@linogaliana Thank you for raising this! Good point—I'll mark it for review.

**Comment by jthomasmock** [comment]
This may be related to what Git is actually telling RStudio, but we should look into changing the dialog itself - @kevinushey

**Comment by gtritchie** [comment]
Moving to next release.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+66 on Windows 11. 



![Image](https://github.com/user-attachments/assets/50e9555e-beba-48a5-bd30-2605d4136abd)

**Comment by ronblum** [comment]
Note: On Windows, I first had to remove the entry for github.com in the Credentials Manager.
