### ISSUE TITLE
rstudio drops final component from projects with `.` in name

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14107]
For example, I created a project called `a.b.c.d.e`:

<img width="255" alt="Screenshot 2024-01-10 at 9 57 31 AM" src="https://github.com/rstudio/rstudio/assets/1976582/105df892-29b1-4de9-86aa-d239c88e1c60">

Note that `.e` is omitted from the displayed package name.

**Comment by gtritchie** [comment]
Very likely a regression caused by https://github.com/rstudio/rstudio/pull/14049, taking a look.

**Comment by kevinushey** [comment]
Appears to be fixed!

<img width="268" alt="Screenshot 2024-01-24 at 1 03 33 PM" src="https://github.com/rstudio/rstudio/assets/1976582/bfd0e035-f711-4b4a-b1dd-3957b7477051">
