### ISSUE TITLE
RStudio is not executable in Win Server 2012

### ISSUE THREAD

**Issue by aworklab** [rstudio/rstudio#14105]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Newer than 2023.06.2-561
    OS Version      :  Windows Server 2012 R2
    R Version       :  4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

I don't know
This is VPC in the server

### Describe the problem in detail

1. after I got some code issues in rstudio, I decided to reinstall it 
   (I didn't updated it over a year)
2. I installed RStudio-2023.12.0-369.exe -> not executable
3. I installed RStudio-2023.06.2-561.exe -> not executable
4. I installed RStudio-2023.03.2-454.exe -> executable 

here is the notion page I summarized the situation 
[notion URL](https://delabsgames.notion.site/RStudio-Issue-ea9a9372009c4941b52d5f66312e7862)

### Describe the behavior you expected

Running latest Rstudio version for my projects 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
From https://learn.microsoft.com/en-us/lifecycle/announcements/windows-server-2012-r2-end-of-support:

> Windows Server 2012 and Windows Server 2012 R2 will end on October 10, 2023. After this date, these products will no longer receive security updates, non-security updates, bug fixes, technical support, or online technical content updates. 

From https://posit.co/about/platform-support/#windows-mac

> New releases of Posit products and packages will support operating systems and browsers listed below until either of the following occurs: (1) the vendor no longer supports them

**Comment by gtritchie** [comment]
So, unfortunately, we are unlikely to put any effort into making newer releases of RStudio work on Windows Server 2012.

**Comment by aworklab** [comment]
I understood the situation
Thank you!

**Comment by timtmok** [comment]
This is probably due to upgrading Electron. They've dropped Windows support for versions that are EOL. https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support

This includes Windows 7/8/8.1 and Server 2012/2012 R2. The Electron update is required to stay on top of Chromium releases.
