### ISSUE TITLE
Backport #14106 to Ocean Storm 2023.12.1

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#14117]
Backport #14106 to Ocean Storm 2023.12.1.

**Note: This issue is to record the need to backport the linked issue only. Please add comments or discussion relating to the original issue onto it directly.**

**Comment by gtritchie** [comment]
Note, this was merged into `rel-ocean-storm` not `main`. https://github.com/rstudio/rstudio/pull/14109

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.1+385
- Ignored: jpeg, jpg, mp3
- Included: html, yml, js, css, txt, json, qmd, dcf

Verified in Posit Workbench 2023.12.1+385.pro7
- Ignored: job, mp4, xlsx
- Included: Rmd, md, R, py, Rhistory
