### ISSUE TITLE
Rstudio wouldn't open with a large file in the project folder

### ISSUE THREAD

**Issue by dcaud** [rstudio/rstudio#14138]
I got a message similar to this: https://github.com/rstudio/rstudio/issues/12654, but I am on a mac. 

The file was ~2GB. Maybe it was corrupt. Removing it make the error disappear. I don't have any more time to troubleshoot this or reproduce this, but it was a problem and I'm hoping it can be fixed so others don't experience it.

**Comment by ronblum** [comment]
@dcaud Thank you for raising this! What kind of file was it so that I can try to reproduce?
