### ISSUE TITLE
Github copilot is not working in Rstudio Desktop when signing in

### ISSUE THREAD

**Issue by WangYunHong98** [rstudio/rstudio#14145]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2023.12.0+369
    OS Version      :  Windows 11
    R Version       :  4.2.2

### Steps to reproduce the problem
1. Check 'Enable Github Copilot'
2. 'sign in' is not working

### Describe the problem in detail
![image](https://github.com/rstudio/rstudio/assets/104638954/23ae9642-8328-43bc-aaed-281be97d0d7f)
![image](https://github.com/rstudio/rstudio/assets/104638954/9691ccca-4a97-4347-8943-ba47d4427e48)
And I have tried to add RSTUDIO_COPILOT_LOG_LEVEL=1 to ~/.Renviron

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hualian666** [comment]
I met the same question

**Comment by WangYunHong98** [comment]
@hualian666 Have you solved this problem yet?

**Comment by hualian666** [comment]
NO





---Original---
From: ***@***.***&gt;
Date: Thu, Jan 25, 2024 16:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rstudio/rstudio] Github copilot is not working in RstudioDesktop when signing in (Issue #14145)




 
@hualian666 Have you solved this problem yet?

**Comment by hualian666** [comment]
@ronblum my details were same as @WangYunHong98 
so how to solve it
it seems the copilot is running but I cannot sign in anyway

**Comment by TCDKX** [comment]
一样的问题

**Comment by hualian666** [comment]
who can help us

**Comment by hualian666** [comment]
Please try this way
COPILOT_PROXY_URL=<url>
in your own ~/.Renviron

**Comment by ronblum** [comment]
Can you try with the most logging turn on, with `COPILOT_LOG_LEVEL=3` in `~/.Renviron` ?

**Comment by WangYunHong98** [comment]
@ronblum here are some details using COPILOT_LOG_LEVEL=3:
[onStarted]: Copilot agent has started [PID = 25460]

RESPONSE
------------------
{"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [agent] [2024-02-19T11:19:47.001Z] Agent service starting","metadataStr":"[DEBUG] [agent] [2024-02-19T11:19:47.001Z]","extra":["Agent service starting"]}}
------------------


[sendRequest]: Sending request 'initialize' with id 'a1461d87-5e22-4428-a8d2-17efe3de1ad2'.

REQUEST
----------------
Content-Length: 179

{"jsonrpc":"2.0","method":"initialize","params":{"processId":5184,"clientInfo":{"name":"RStudio","version":"1.0.0"},"capabilities":{}},"id":"a1461d87-5e22-4428-a8d2-17efe3de1ad2"}
----------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"a1461d87-5e22-4428-a8d2-17efe3de1ad2","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2},"workspace":{"workspaceFolders":{"supported":false,"changeNotifications":false}}}}}
------------------


[onBackgroundProcessing]: Invoking continuation with id 'a1461d87-5e22-4428-a8d2-17efe3de1ad2'.
[sendRequest]: Sending request 'setEditorInfo' with id '7717b988-4994-4918-9919-13f55469ab3d'.

REQUEST
----------------
Content-Length: 219

{"jsonrpc":"2.0","method":"setEditorInfo","params":{"editorInfo":{"name":"RStudio","version":"2023.12.0+369"},"editorPluginInfo":{"name":"RStudio","version":"2023.12.0+369"}},"id":"7717b988-4994-4918-9919-13f55469ab3d"}
----------------



RESPONSE
------------------
{"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [agent] [2024-02-19T11:19:47.196Z] Telemetry initialized","metadataStr":"[DEBUG] [agent] [2024-02-19T11:19:47.196Z]","extra":["Telemetry initialized"]}}
------------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"7717b988-4994-4918-9919-13f55469ab3d","result":"OK"}
------------------


[onBackgroundProcessing]: Invoking continuation with id '7717b988-4994-4918-9919-13f55469ab3d'.
[onStarted]: Copilot agent has started [PID = 26652]

RESPONSE
------------------
{"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [agent] [2024-02-19T11:19:52.788Z] Agent service starting","metadataStr":"[DEBUG] [agent] [2024-02-19T11:19:52.788Z]","extra":["Agent service starting"]}}
------------------


[sendRequest]: Sending request 'initialize' with id 'b373a7de-5310-4369-b18b-166bf6a03bc4'.

REQUEST
----------------
Content-Length: 179

{"jsonrpc":"2.0","method":"initialize","params":{"processId":5184,"clientInfo":{"name":"RStudio","version":"1.0.0"},"capabilities":{}},"id":"b373a7de-5310-4369-b18b-166bf6a03bc4"}
----------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"b373a7de-5310-4369-b18b-166bf6a03bc4","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2},"workspace":{"workspaceFolders":{"supported":false,"changeNotifications":false}}}}}
------------------


[onBackgroundProcessing]: Invoking continuation with id 'b373a7de-5310-4369-b18b-166bf6a03bc4'.
[sendRequest]: Sending request 'setEditorInfo' with id '1d76b381-f92d-4b3a-b186-4c7a7ce01d45'.

REQUEST
----------------
Content-Length: 219

{"jsonrpc":"2.0","method":"setEditorInfo","params":{"editorInfo":{"name":"RStudio","version":"2023.12.0+369"},"editorPluginInfo":{"name":"RStudio","version":"2023.12.0+369"}},"id":"1d76b381-f92d-4b3a-b186-4c7a7ce01d45"}
----------------



RESPONSE
------------------
{"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [agent] [2024-02-19T11:19:52.946Z] Telemetry initialized","metadataStr":"[DEBUG] [agent] [2024-02-19T11:19:52.946Z]","extra":["Telemetry initialized"]}}
------------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"1d76b381-f92d-4b3a-b186-4c7a7ce01d45","result":"OK"}
------------------


[onBackgroundProcessing]: Invoking continuation with id '1d76b381-f92d-4b3a-b186-4c7a7ce01d45'.
[ensureAgentRunning]: Copilot is already running; nothing to do.
[sendRequest]: Sending request 'getCompletions' with id '22a9a5c9-4474-4b38-bec1-a23798e4d2de'.

REQUEST
----------------
Content-Length: 191

{"jsonrpc":"2.0","method":"getCompletions","params":{"doc":{"position":{"line":28,"character":0},"uri":"rstudio-document://144772F4","version":1}},"id":"22a9a5c9-4474-4b38-bec1-a23798e4d2de"}
----------------


[ensureAgentRunning]: Copilot is already running; nothing to do.
[sendRequest]: Sending request 'getCompletions' with id '6cc20753-d865-4423-b0d8-f3812d3b1734'.

REQUEST
----------------
Content-Length: 191

{"jsonrpc":"2.0","method":"getCompletions","params":{"doc":{"position":{"line":13,"character":2},"uri":"rstudio-document://74142FFA","version":1}},"id":"6cc20753-d865-4423-b0d8-f3812d3b1734"}
----------------


[ensureAgentRunning]: Copilot is already running; nothing to do.
[sendRequest]: Sending request 'getCompletions' with id '12fa30fe-8b99-492b-b112-1e0674257ef7'.

REQUEST
----------------
Content-Length: 220

{"jsonrpc":"2.0","method":"getCompletions","params":{"doc":{"position":{"line":89,"character":38},"uri":"file://E:/WYH98/OneDrive/桌面/GBB_data_processing.Rmd","version":1}},"id":"12fa30fe-8b99-492b-b112-1e0674257ef7"}
----------------


[ensureAgentRunning]: Copilot is already running; nothing to do.
[sendRequest]: Sending request 'getCompletions' with id '2aebfcca-6a26-4677-95a2-88dd00621ea3'.

REQUEST
----------------
Content-Length: 204

{"jsonrpc":"2.0","method":"getCompletions","params":{"doc":{"position":{"line":3,"character":0},"uri":"file://C:/Users/WYH98/Documents/.Renviron","version":1}},"id":"2aebfcca-6a26-4677-95a2-88dd00621ea3"}
----------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"22a9a5c9-4474-4b38-bec1-a23798e4d2de","error":{"code":1000,"message":"Not authenticated: NotSignedIn"}}
------------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"6cc20753-d865-4423-b0d8-f3812d3b1734","error":{"code":1000,"message":"Not authenticated: NotSignedIn"}}
------------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"12fa30fe-8b99-492b-b112-1e0674257ef7","error":{"code":1000,"message":"Not authenticated: NotSignedIn"}}
------------------



RESPONSE
------------------
{"jsonrpc":"2.0","id":"2aebfcca-6a26-4677-95a2-88dd00621ea3","error":{"code":1000,"message":"Not authenticated: NotSignedIn"}}
------------------


[onBackgroundProcessing]: Invoking continuation with id '22a9a5c9-4474-4b38-bec1-a23798e4d2de'.
[onBackgroundProcessing]: Invoking continuation with id '6cc20753-d865-4423-b0d8-f3812d3b1734'.
[onBackgroundProcessing]: Invoking continuation with id '12fa30fe-8b99-492b-b112-1e0674257ef7'.
[onBackgroundProcessing]: Invoking continuation with id '2aebfcca-6a26-4677-95a2-88dd00621ea3'.

**Comment by kevinushey** [comment]
Works fine for me. RStudio 2024.12.1.

<img width="393" alt="Image" src="https://github.com/user-attachments/assets/53d6f1d8-22bc-40d8-9c22-f18b6ef4985f" />
