### ISSUE TITLE
Bad indentation after copy-paste code within a qmd (or rmd) file.

### ISSUE THREAD

**Issue by LuisLauM** [rstudio/rstudio#14153]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2023.12.0
    OS Version      :  Windows 10 Pro
    R Version       :  4.3.2

### Steps to reproduce the problem

I think the quickest way is through this clip where I show how the code I just copy-pasted into a chunk does not indent correctly:

https://github.com/rstudio/rstudio/assets/8452334/6abb9bd1-5af0-4463-8b05-81596f6676d8

I leave the reproducible code below:

```
pickerInput(inputId = "foo",
            label = "Foo:", 
            choices = list(Mediana = c("a", "b"),
                           Total = c("c", 
                                     "d",
                                     "e")), 
            multiple = FALSE)
```

### Describe the problem in detail

This problem is nothing new, because I have been experiencing it for many years (since I know RStudio). The automatic code identation inside chunks in `.Rmd`/`.Qmd` files does not work as well as it does in `.R` files. The truth is that it can become very annoying when you are working on a project where you are constantly moving code around while testing (trial and error).

### Describe the behavior you expected

It is expected that automatic indentation within chunks will work just as well as with R files.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@LuisLauM Does Does turning off indentation when pasting take care of this? You can get to it with the Command Palette with <kbd>Ctrl-Shift-P</kbd>, type `indent`, and uncheck the option for "Re-indent code when pasting."

**Comment by LuisLauM** [comment]
@ronblum Nope. It seems that it does not solve the problem.

https://github.com/rstudio/rstudio/assets/8452334/b841836e-14c2-49ee-afb8-e11944f4628b

**Comment by sbw78** [comment]
I am also experiencing this same issue. Code will not indent when working in chunks in a quarto document. The usual indent command (CTRL+I or CMD+I) does not work. 

I am using RStudio version 2024.04.1+748

Session Info:
```r
R version 4.3.1 Patched (2023-06-20 r84585)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.6.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0
```

**Comment by jthomasmock** [comment]
Howdy! Would you mind trying out this upcoming release? https://dailies.rstudio.com/version/2024.04.2+757/

We addressed some code-flow/indent items.
