### ISSUE TITLE
Commenting out native pipe leads to weird syntax highlighting

### ISSUE THREAD

**Issue by patc3** [rstudio/rstudio#14159]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0 Build 369 Ocean Storm 33206f75
    OS Version      :  Windows 10
    R Version       :  4.3.1

### Steps to reproduce the problem
comment out native pipe in R script or in R console, e.g.:
`df # |> summary()`

### Describe the problem in detail
my theme is set to: Chaos

in console
![image](https://github.com/rstudio/rstudio/assets/41131893/96e50cf2-57dd-49ca-a415-386d3473bbda)

in script file
![image](https://github.com/rstudio/rstudio/assets/41131893/24729890-10f4-4345-b326-e0ed496ce872)

### Describe the behavior you expected
everything should be greyed out after a comment in a .R file or in R console

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I'll take a look.
