### ISSUE TITLE
Update builds to use JDKs > 8

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14157]
Our builders currently use Java 8 when building GWT.

Starting to hit issues with that; tried to update to the latest elemental2 [here](https://github.com/rstudio/rstudio/issues/13924#issuecomment-1907018578) and discovered that it now requires Java 11 or higher.

We should consider bumping up to at least Java 11 on the build machines. Some of our oldest platforms (e.g. Centos7) might not have easy access to a newer JDK so might need to wait until we no longer need those.

**Comment by kevinushey** [comment]
It looks like CentOS 7 _does_, fortuitously, have OpenJDK 11 available, so we could consider this change now if necessary.

**Comment by gtritchie** [comment]
There's nothing to specifically test here. We already used JDK11 on some platforms, so not breaking new ground by upgrading all of them to JDK11. Closing.
