### ISSUE TITLE
RStudio Electron Desktop RStudio -> About shows old date

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#14166]
### System details

```
RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-17) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)
RStudio/2023.12.0+369
Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
```

### Steps to reproduce the problem

On macOS, click the RStudio menu, then About RStudio.

### Describe the problem in detail

The following dialog appears, which suggests that an old 2022 copy is in use.

<img width="396" alt="image" src="https://github.com/rstudio/rstudio/assets/470418/a41dc7e1-985d-40c5-ba60-e2ee73fae107">

### Describe the behavior you expected

The correct copyright year (2024) should appear in this dialog.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is set here:

https://github.com/rstudio/rstudio/blob/b49b95ec22bd13ce1ef8eb92dde6fe42795b4b24/src/node/desktop/forge.config.js#L63

**Comment by gtritchie** [comment]
Confirmed fixed:


![screenshot of RStudio Desktop About Dialog showing updated copyright](https://github.com/rstudio/rstudio/assets/10569626/258d0485-c677-4b08-bc46-62cf0aae8a09)
