### ISSUE TITLE
Code autocomplete and auto-indentation not working after multi-line YAML string in quarto code chunk

### ISSUE THREAD

**Issue by dakep** [rstudio/rstudio#14160]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0 Build 369
    Platform: x86_64-apple-darwin20 (64-bit)
    Running under: macOS Ventura 13.6.3
    R version 4.3.2 Patched (2024-01-03 r85770)

### Steps to reproduce the problem

1. Create a new Quarto document
2. Add an R code chunk with a multi-line YAML string as the **last** chunk option, e.g., 
````md
```{r}
#| fig-cap: |
#|  Multi-line YAML string in the last chunk option key.
#|  Autocomplete and auto-indentation do *not* work.
library(tidyverse)
cars %>% 
ggplot(aes(x = speed, y = dist)) +
geom_point()
```
````

### Describe the problem in detail

In the above code chunk neither autocomplete nor auto-indentation work.

### Describe the behavior you expected

Autocomplete and auto-indentation should work in the above code chunk regardless of the type of YAML data in the chunk options.
When putting other YAML data at the end of the chunk options (i.e., anything but a multi-line string), autocomplete and auto-indenation work as expected:

````md
```{r}
#| fig-cap: |
#|  Multi-line YAML string in the chunk options, but not the last key.
#|  Autocomplete and auto-indentation work as expected.
#| fig-width: 5
library(tidyverse)
cars %>% 
  ggplot(aes(x = speed, y = dist)) +
  geom_point()
```
````

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment]
For ref, similar to what I reported in https://github.com/rstudio/rstudio/issues/13836#issuecomment-1825982257 a fix was attempted with this commit https://github.com/rstudio/rstudio/commit/1078e7ce89f745cb0cdcf79d2bccd8706aac6545

**Comment by kevinushey** [comment]
Thanks for the report! Should be fixed in the next daily builds.

<img width="741" alt="Screenshot 2024-01-24 at 12 50 07 PM" src="https://github.com/rstudio/rstudio/assets/1976582/f6acedd6-71ba-4e65-8db1-f0530bcc7405">

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+581 on MacOS 14.4. Checked that both autocompletion and indentation are correct.
