### ISSUE TITLE
Render of .qmd with `format: email` in yaml fails

### ISSUE THREAD

**Issue by kmasiello** [rstudio/rstudio#14175]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0-daily+297 "Chocolate Cosmos" Daily (8a7fa575187f3ed04e2a4d75147b85e177bb248e, 2024-01-24) for macOS
    OS Version      :  MacOS Sonoma 14.2.1 (23C71)
    R Version       : 4.2.3

### Steps to reproduce the problem

Include in .qmd yaml the following: 
```
...
format: email
...
```

Diagnostics(?) also shows a red flag in the LHS margin per screenshot:
<img width="260" alt="image" src="https://github.com/rstudio/rstudio/assets/32964481/22ff7a0a-94da-48a3-9f1d-232bf747e97e">

Clicking "Render" yields: 

```
ERROR: Validation of YAML front matter failed.
ERROR: In file test.qmd
(line 3, columns 9--14) Field "format" has value email, which must instead be 'asciidoc'
2: title: test
3: format: email
          ~~~~~~
4: email-preview: true

ERROR: Render failed due to invalid YAML.
```

Running `quarto render test.qmd` on the command line will work without error. This is exclusively an IDE issue around the validation occurring when "Render" is clicked.

### Describe the problem in detail

see above.

### Describe the behavior you expected

Expect Quarto Render button to function without error.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kmasiello** [comment]
cc @rich-iannone

**Comment by kevinushey** [comment]
Presumedly this is because RStudio is still bundled with / using an older version of Quarto?

```
kevin@MBP-P2MQ:~/scratch/poweRlaw/inst/doc
$ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto --version
1.3.450
```

What is the output of `system("quarto --version")` for you? Does the error persist if you install the latest release of Quarto?

**Comment by kmasiello** [comment]
Ah shoot.  

RStudio is using 1.3.450
```{r}
system("quarto --version")
1.3.450
```

However outside of RStudio, my system is running latest
```{bash}
quarto --version
1.4.549
```

I'm managing quarto with `qvm`.  Is this an issue of RStudio not detecting the selected version?

**Comment by kevinushey** [comment]
Possibly -- how does `qvm` work? If `quarto` is on the PATH, then RStudio should prefer using that; otherwise, it'll fall back to using its bundled copy of Quarto.

Alternatively, one can set the `RSTUDIO_QUARTO` environment variable to force RStudio to use a specific Quarto installation.

**Comment by kmasiello** [comment]
`quarto` is on PATH via `qvm` and is higher precedence than the paths added by RStudio, namely, `/Users/katie/Applications/quarto/bin` and `/Applications/RStudio.app/Contents/Resources/app/quarto/bin`

Verified by:
```
$ which quarto
/Users/katie/.config/qvm/bin/quarto

$ ls -l /Users/katie/.config/qvm/bin/quarto
lrwxr-xr-x@ 1 katie  staff  58 Jan 25 10:34 /Users/katie/.config/qvm/bin/quarto -> /Users/katie/.local/share/qvm/versions/v1.4.549/bin/quarto

$ echo $PATH | sed 's/:/\n/g
/Users/katie/.config/qvm/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
/System/Cryptexes/App/usr/bin
/usr/bin
/bin
/usr/sbin
/sbin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
/opt/X11/bin
/Library/Apple/usr/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/Users/katie/.fig/bin
/Users/katie/.local/bin
/Users/katie/Applications/quarto/bin
/Library/TeX/texbin
/usr/texbin
/Applications/RStudio.app/Contents/Resources/app/quarto/bin
/Applications/RStudio.app/Contents/Resources/app/bin/postback
/Users/katie/Library/TinyTeX/bin/universal-darwin
```

**Comment by kevinushey** [comment]
Do you see that within the main R session too; e.g. does `system("quarto --version")` report the same?

**Comment by kmasiello** [comment]
Thanks for the huddle, @kevinushey.  Got it all working!

Closing the loop:

Root cause: RStudio does not read all system configuration files, i.e., `.zshrc` on startup. This is where `qvm` inserts itself on the PATH. For reference, output of PATH from RStudio console is:
```
> system("echo $PATH")
/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/katie/.fig/bin:/Users/katie/.local/bin:/Users/katie/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Users/katie/.local/share/qvm/versions/v1.4.549/bin:/Applications/RStudio.app/Contents/Resources/app/bin/postback:/Users/katie/Library/TinyTeX/bin/universal-darwin
```

Some ways to resolve this issue:
1. Set `RSTUDIO_QUARTO` environment variable in `.Rprofile` or `.Renviron`
2. add `export PATH="$(qvm path add)"` to `.Renviron` 
3. Symlink `~/Applications/quarto/bin` (which RStudio places on the PATH) to the `qvm` path to quarto, `~/.config/qvm/bin/quarto` (e.g., `ln -s /Users/katie/.config/qvm/bin/quarto /Users/katie/Applications/quarto/bin/quarto`)

I opted for method 3 so if any other applications are looking for a Quarto install at `~/Applications/quarto/bin`, it will be correctly routed.
