### ISSUE TITLE
Support Quarto installations installed via qvm

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14177]
See: https://github.com/dpastoor/qvm

`qvm` is a relatively popular tool for managing Quarto installations. We should teach RStudio how to find these Quarto installations, since users might add `quarto` to their path in a `.zshrc` or `.bash_profile`, and hence these `quarto` copies would be visible to shell / Terminal instances but not the main RStudio session itself.

Alternatively, we should consider launching the `rsession` process through a shell?

**Comment by jthomasmock** [comment]
Commenting for posterity from the `qvm` readme:

> NOTE: adding this to your profile instead of ~/.bashrc or ~/.zshrc will enable both the shell sessions and R sessions launched via RStudio/Workbench to pick up the change. If you only add to the rc file, it will only be present in the shell.

**Comment by gtritchie** [comment]
Started tests by creating a new Quarto Project (File / New Project / New Directory / Quarto Project).

## Mac Desktop

- Installed 2024.04.0-hourly+456
- qvm not installed
- About dialog reports `Quarto 1.4.549` (this is the bundled version)
- Able to render the document
- Exit RStudio
- Install qvm via `brew install dpastoor/tap/qvm`
- `qvm init` from terminal
- Open RStudio, confirm we can still render, and that About still reports 1.4.549
- Exit RStudio
- `qvm install v1.5.14`
- `qvm use v1.5.14`
- Open RStudio, confirm we can still render, and About reports the new version and custom location:

<img width="610" alt="mac-custom-quarto" src="https://github.com/rstudio/rstudio/assets/10569626/bd814832-f84c-4eb4-8d7e-32af8acfe752">

- Exit RStudio
- `qvm install v1.4.550`
- `qvm use v1.4.550`
- repeat test and confirm version and ability to render

- To "deactivate" qvm and go back to using RStudio's bundled Quarto:  `rm ~/.config/qvm/bin/quarto`
- I opened a suggestion to add a `qvm deactivate` command to accomplish this: https://github.com/dpastoor/qvm/issues/18

**Comment by gtritchie** [comment]
## Linux Desktop (Ubuntu 22.04.3 / x64)

- Installed 2024.04.0-daily+456
- qvm not installed
- About dialog reports `Quarto 1.4.549` (this is the bundled version)
- Able to render the document
- Exit RStudio
- Install qvm using instructions at https://github.com/dpastoor/qvm/releases/tag/v0.3.0

```
sudo wget https://github.com/dpastoor/qvm/releases/download/v0.3.0/qvm_Linux_x86_64.tar.gz -O /tmp/qvm.tar.gz
sudo tar xzf /tmp/qvm.tar.gz qvm
sudo mv qvm /usr/local/bin/qvm
sudo chmod +x /usr/local/bin/qvm
qvm init
```
- Open RStudio, confirm we can still render, and that About still reports 1.4.549
- Exit RStudio
- `qvm install v1.5.14`
- `qvm use v1.5.14`
- Open RStudio, confirm we can still render, and About reports the new version and custom location:
- Exit RStudio
- `qvm install v1.4.550`
- `qvm use v1.4.550`
- repeat test and confirm version and ability to render

- To "deactivate" qvm and go back to using RStudio's bundled Quarto:  `rm ~/.config/qvm/bin/quarto`

**Comment by gtritchie** [comment]
## Windows Desktop (Windows-11)

- installed RStudio 2024.04.0-daily+456
- qvm not installed
- About dialog reports `Quarto 1.4.549` (this is the bundled version)
- Able to render the document
- Exit RStudio
- Downloaded qvm for Windows via https://github.com/dpastoor/qvm/releases/download/v0.3.0/qvm_Windows_x86_64.zip
- Extracted and put qvm.exe in a folder I have on the `PATH`
- `qvm init`
- Open RStudio, confirm we can still render, and that About still reports 1.4.549
- Exit RStudio
- `qvm install v1.5.14`
- I had to run the following `qvm use` command from an admin command prompt
- `qvm use v1.5.14`
- Open RStudio, confirm we can still render, and About reports the new version and custom location

![screenshot of RStudio About box showing expected quarto information](https://github.com/rstudio/rstudio/assets/10569626/8b87331d-679a-4c45-b4b8-f2112b887ef1)


- Exit RStudio
- `qvm install v1.4.550`
- `qvm use v1.4.550`
- repeat test and confirm version and ability to render

- To "deactivate" qvm and go back to using RStudio's bundled Quarto:  `del %localappdata%\qvm\bin\quarto.cmd`

**Comment by gtritchie** [comment]
Completed testing.
