### ISSUE TITLE
Improve performance when testing for set inclusion

### ISSUE THREAD

**Issue by lhdjung** [rstudio/rstudio#14184]
## Description

R code of the form `single_value %in% vector` can be made "much faster" ([*Advanced R*, ch. 24.4](https://adv-r.hadley.nz/perf-improve.html#be-lazy)) by rewriting it like `any(vector == single_value)`.

I checked all instances of `%in%` in this codebase, and most of them seem to take a length-1 object as their LHS. (In most of these cases, the LHS is a string literal or the result is used as a condition.)

## Proposal
I could make a PR that rewrites all instances of `%in%` as above, **except for** the following cases, where the LHS of `%in%` may have length > 1.

<details>

<summary>List of exceptions</summary>

1. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/sql/SessionSql.R#L384
2. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/r/R/Api.R#L290
3. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/r/R/Api.R#L725
4. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/r/R/Api.R#L759
5. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/r/R/Tools.R#L269
6. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/r/R/Tools.R#L1113
7. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionAskSecret.R#L46
8. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/NotebookData.R#L463
9. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionConnections.R#L450
10. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionConnections.R#L455
11. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionConnections.R#L782
12. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRmdNotebook.R#L133
13. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionObjectExplorer.R#L718
15. https://github.com/rstudio/rstudio/blob/2ec7c0ec441b9e7249dd8e7b93119b70c3a911c6/src/cpp/session/modules/SessionCodeTools.R#L2046
16. https://github.com/rstudio/rstudio/blob/2ec7c0ec441b9e7249dd8e7b93119b70c3a911c6/src/cpp/session/modules/SessionCodeTools.R#L2533
17. https://github.com/rstudio/rstudio/blob/2ec7c0ec441b9e7249dd8e7b93119b70c3a911c6/src/cpp/session/modules/SessionCodeTools.R#L2701
18. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRMarkdown.R#L363
19. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L534
20. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L606
21. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L1033
22. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L1393
23. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L2179
24. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L2845
25. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L2926
26. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L3035
27. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionRCompletions.R#L3735
28. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionPackages.R#L285
29. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionPackages.R#L456
30. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionPackages.R#L780
31. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionPackages.R#L829
32. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/session/modules/SessionPackages.R#L835
33. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/tests/testthat/test-connections.R#L99
34. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/tests/testthat/test-themes.R#L116
35. https://github.com/rstudio/rstudio/blob/b41973fc455a032081d9b3ea1a85c411e4e3e02f/src/cpp/tests/testthat/test-themes.R#L135

</details>

**Comment by kevinushey** [comment]
Thanks for the offer, but it seems like that advice is not true in general:

```
> long <- as.numeric(1:1E3)
> microbenchmark(
+    10 %in% long,
+    any(long == 10)
+ )
Unit: nanoseconds
            expr  min   lq    mean median   uq  max neval
    10 %in% long  615  656  783.10    779  820 3116   100
 any(long == 10) 1640 1722 1778.58   1763 1804 3403   100
```

In addition, it's unlikely that RStudio's usages of `%in%` are bottlenecks in any of their respective code paths, so I don't think we'd want to make these code changes without a more explicit motivation.
