### ISSUE TITLE
Warning message: Unable to parse markdown

### ISSUE THREAD

**Issue by cbclobato** [rstudio/rstudio#14191]
I keep getting the message "Unable to parse markdown".
I already updated rstudio to the newly released version 2023.12.0-369 but it persists.

**Comment by gtritchie** [comment]
Please provide more information as requested by the issue template.

Version of RStudio, platform (Windows/Linux/Mac), Desktop or Server, and version of R.

What are the steps needed to reproduce the issue?

Where do you see the message?
