### ISSUE TITLE
Change pane layout doesn't update pane layout

### ISSUE THREAD

**Issue by TJ213** [rstudio/rstudio#14190]
### System details

    RStudio Edition : Server
    RStudio Version : RStudio Pro 2023.12.0 Build 369.pro3, "Ocean Storm" Release (10c1b662, 2023-12-14)
    OS Version      :  CentOS 7
    R Version       :  4.2.1

### Steps to reproduce the problem

I want to change the pane layout by clicking on 

Tools -> Global Options -> Pane Layout 

and change the layout such that the console is displayed in the upper right quadrant. Then clicking "apply" and then "OK".

Then a "saving" drop down appears and the global options panel goes away but the panel layout remains the same and hasn't changed. 

### Describe the problem in detail

see above

### Describe the behavior you expected

I would expect that the layout would change. 

I have tried to see whether the bug has been reported, but couldn't find any reports.

Can you please check whether you can reproduce the issue?

thanks in advance

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@TJ213 Thank you for raising this! It's an issue with the pro products, so we're tracking it in the pro repo, which is private. I've linked the issues, though, and the fix for this will be in a patch that should be live any day now.

**Comment by ronblum** [comment]
Done—RStudio Desktop Pro 2023.12.1-402.pro1 is now available and contains the fix.

**Comment by zhichengwang59** [comment]
this new 12.1 release requires 
GLIBC_2.32
GLIBC_2.33
GLIBC_2.34

those are not availabe in RHEL 8. please will there be an update for RHEL/Rocky 8?
