### ISSUE TITLE
Quarto shows raw code instead of markdown

### ISSUE THREAD

**Issue by lborcard** [rstudio/rstudio#14193]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : Centos8
    R Version       :  4.1

### Steps to reproduce the problem
Not known
### Describe the problem in detail
I created (yesterday) a .qmd file that contained a table and now I cannot edit it in markdown all I see is that instead of markdown:

```
---
title: monthly report 24
---

# January

<table style="width:96%;">
<caption>January</caption>
<colgroup>
<col style="width: 7%" />
<col style="width: 18%" />
<col style="width: 7%" />
<col style="width: 7%" />
<col style="width: 7%" />
````

thank you for your help,

best

**Comment by lborcard** [comment]
Sorry about the post I just realised that creating a markdown and modifying in visual mode would result in switch permanently to html table mode.

**Comment by ronblum** [comment]
@lborcard Thank you for noting this and the followup! Out of curiosity, what was the original code that you had? Or did you create the table in visual mode?

**Comment by lborcard** [comment]
No the table was created in visual mode
