### ISSUE TITLE
port RStudio IDE to webR

### ISSUE THREAD

**Issue by seanbirchall** [rstudio/rstudio#14211]
This is probably a silly ask but I thought it'd be worth asking, so I can stop working on this or keep going.

Is there any plan to build out RStudio or a minimal RStudio in webR?

I've started building something like that with the hopes that some of the issues I'm already seeing can be solved by myself or others working on webR. Right now it looks like https://github.com/r-wasm/webr/issues/295 could likely turn out to be a fix for one of the bigger issues I've seen which is that I'm unable to display htmlwidgets/plots created from a webR repl app, written in R, likely related to calls to system in base.

A lot of the existing pieces needed to make a very minimal RStudio IDE in R/JS already exist. My plan right now is to fork the rstudio and shinyAce repos and work on pushing all the code completions in shinyAce to JS and following along as best I can with how rstudio does it.

I think this could be pretty useful, low cost, be very good as an internal tool within an org, but also be useful externally on the internet so long as it's connected to proxy severs/services. Most if not all of the core stuff I use in R already just works in webR... which is amazing, there are some obvious limitations, but I still think this would be extremely useful and beneficial to R.     

A version of my very minimal IDE app can be viewed [here](https://www.scrapeable.com/site/index.html) and source code can be found [here](https://github.com/seanbirchall/scrapeable).

**Comment by gtritchie** [comment]
Hi, not a silly question at all!

The RStudio IDE team doesn't currently have any plans to port RStudio to WebR, and it would be a huge, complex task.

An approach to consider would be to think about what you'd like to see that's currently missing from the current front end at https://webr.r-wasm.org/latest/ and open smaller, targeted issues in the webR GitHub repo. That will likely provide quicker feedback and useful results.

https://github.com/r-wasm/webr
