### ISSUE TITLE
Set minimum to R 3.6.0

### ISSUE THREAD

**Issue by petetronic** [rstudio/rstudio#14210]
As requested for Chocolate Cosmos, issue to track updating RStudio to require R 3.6.0 at a minimum.

**Comment by gtritchie** [comment]
For reference, here's the PR from when we bumped up to 3.3.0: https://github.com/rstudio/rstudio/pull/10769

**Comment by jthomasmock** [comment]
We should indicate in the blogpost that you CAN disable package checking and how to do so. This may lead to degraded experience but does allow use of older versions of R in the IDE.

**Comment by ronblum** [comment]
Checked files. Opened issue rstudio/rstudio-pro#5887 for doc updates.
