### ISSUE TITLE
Unable to change variable type in the "import dataset" wizard when localization is french

### ISSUE THREAD

**Issue by dicorynia** [rstudio/rstudio#14224]
### System details

    RStudio Edition : Desktop + server
    RStudio Version : "Ocean Storm" Release (4da58325, 2024-01-28) 
    OS Version      :  Microsoft Windows [version 10.0.19045.3570]
    R Version       : R version 4.3.1

### Steps to reproduce the problem

- Switch to the UI in french: Tools > Global options > General > Advanced >  User Interface Language > French (français)
- In panel "Environnement" > "Importer un ensemble de données" > "À partir du texte (readr)" or "À partir d'Excel"
- Chose a CSV or XLSX file ("Parcourir")
- The preview opens

### Describe the problem in detail

- In the preview header we can't change the type of the variables from the guessed type; the dropdown arrow is inactive

![image](https://github.com/rstudio/rstudio/assets/31208891/f07c3863-d91d-4af5-8d3a-a23a5223d9df)

### Describe the behavior you expected

- In the english UI, the dropdown is active and we can change the variable type (character, double,...)

-------

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+426 using Excel and CSV files.
