### ISSUE TITLE
go to files/function box is too large

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14223]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0+397
    OS Version      :  Windows 10
    R Version       : 4.3.2

### Steps to reproduce the problem

1. Press Ctrl + . to show the Go to Files / function dialog.

I don't know if it is related but I chose to hide menu and tried the full screen mode, but reverting doesn't change the box size.

### Describe the problem in detail

The box is too tall. (taller than before)
![image](https://github.com/rstudio/rstudio/assets/52606734/6b8e09ed-9ab6-4046-82be-08e6c066f54f)

### Describe the behavior you expected

I would expect the box height to be shorter. (height of the text) similar to what is present in the box https://docs.posit.co/ide/user/ide/guide/code/code-navigation.html#go-to-filefunction

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Confirmed this has changed.

In 2023.12.0+369:

<img width="401" alt="screenshot of go to file dialog in build 369" src="https://github.com/rstudio/rstudio/assets/10569626/047c304b-1863-4655-ad75-b94417083fc1">

In 2023.12.1+402:

<img width="408" alt="screenshot of go to file dialog in build 402" src="https://github.com/rstudio/rstudio/assets/10569626/5bb65ec4-be4c-446b-ad61-a3a926b7d633">

**Comment by gtritchie** [comment]
Regression I caused via: https://github.com/rstudio/rstudio/pull/14119 (sigh).

**Comment by gtritchie** [comment]
Another example:

<img width="632" alt="Screenshot 2024-02-06 at 11 24 33" src="https://github.com/rstudio/rstudio/assets/10569626/b583b6a6-cd38-4ab2-bfe1-3440082526ca">

**Comment by olivroy** [comment]
Seems properly fixed ! thanks
