### ISSUE TITLE
Error: bad binding access in continuous loop on console

### ISSUE THREAD

**Issue by mikecrobe** [rstudio/rstudio#14222]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.12.1+402 "Ocean Storm"
    OS Version      :  Windows 10
    R Version       :  4.3.2

### Steps to reproduce the problem

There is no set pattern - see description

### Describe the problem in detail

When I first updated to RStudio 2023.12 I got an issue where the first source script I ran produced some normal output and then RStudio starting outputting Error: bad binding access in a continuous loop
At the time I downgraded back to 2023.12 and the error no longer occurred
I updated to the Jan 29 2023.12 and the error has resumed. 
If I step through the code in debug, there is no error

### Describe the behavior you expected

N/A
I realise this is probably a one-off to do with my installation - but I have seen bug reports on this elsewhere
I am happy to run any diagnostics rewusted

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- if you're able to figure out how to reliably reproduce this issue, please let us know; that will help us greatly in understanding how this issue might be occurring.

**Comment by mikecrobe** [comment]
> Thanks for the bug report -- if you're able to figure out how to reliably reproduce this issue, please let us know; that will help us greatly in understanding how this issue might be occurring.

Yes - I know there is not enough to go on. The laptop works fine on the older RStudio but fails every time with the newer.
Do you have any pointers on the code in Rinlinedfuns.h which at least has a matching error message.

Is there anything I can look at my side which relates the code:

`#if defined(USE_RINTERNALS) || defined(COMPILING_R)
/* inline version of CAR to support immediate bindings */
INLINE_FUN SEXP CAR(SEXP e)
{
    if (BNDCELL_TAG(e))
	error("bad binding access");
    return CAR0(e);
}
#else
SEXP CAR(SEXP e);
#endif`

**Comment by kevinushey** [comment]
R describes so-called "immediate bindings" here:

https://github.com/wch/r-source/blob/trunk/doc/notes/immbnd.md

If I understand the error correctly, RStudio is trying to access an immediate binding in a way that it shouldn't. Those are normally created by e.g. for loops, e.g. in

```
for (i in 1:3) {
  i
}
```

The variable `i` is an immediate binding within that loop. Does that help potentially isolate the issue?

As an aside, a similar issue was reported here:

https://github.com/rstudio/rstudio/issues/12456

**Comment by kevinushey** [comment]
Does the error message depend on what kind of R objects you have in your environment? If you clear your R environment with:

```
rm(list = ls())
```

does the error persist, or go away? (are you still able to execute code once you get into the "bad binding access" loop?)

Does it make any difference if you toggle the Environment pane to refresh manually only?

<img width="411" alt="Screenshot 2024-02-09 at 11 56 19 AM" src="https://github.com/rstudio/rstudio/assets/1976582/e8aa6343-ba31-4ea6-8e04-fd0a7a5b22c3">

**Comment by mikecrobe** [comment]
> Does the error message depend on what kind of R objects you have in your environment? If you clear your R environment with:
> 
> ```
> rm(list = ls())
> ```
> 
> does the error persist, or go away? (are you still able to execute code once you get into the "bad binding access" loop?)
> 
> Does it make any difference if you toggle the Environment pane to refresh manually only?
> 
> <img alt="Screenshot 2024-02-09 at 11 56 19 AM" width="411" src="https://private-user-images.githubusercontent.com/1976582/303761944-e8aa6343-ba31-4ea6-8e04-fd0a7a5b22c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDg0ODYsIm5iZiI6MTcwODM0ODE4NiwicGF0aCI6Ii8xOTc2NTgyLzMwMzc2MTk0NC1lOGFhNjM0My1iYTMxLTRlYTYtOGUwNC1mZDBhN2E1YjIyYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMTMwOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTljY2Y0ODc2MzczMTRhZWI2MDgwNjBhNmU1MTc3NGZiMjJkZGMwMzYxM2U2YjcyN2QyMjFmZmNjMmExZWU1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ng0PYHzRGAGywReXG4pmjfD62B7woon81vrzlNzgXQE">

Thank you. I will make time to restore the new version and try this when work allows.
I did test with a clear environment, but the code runs for a while (and therefore populates the environment) before it fails.
It's tricky to tell which line is causing the issue - partly because everything OK in debug and stepping

Mike

**Comment by JeromeLegras** [comment]
I have the same issue with this version:

RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-28) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

I am using R 4.3.0 Patched

This happens randomly within loops that run perfectly fine normally (not a code issue - the same code will run in Visual Studio Code for example) so this is definitely a RStudio problem.

**Comment by kevinushey** [comment]
@JeromeLegras: can you please share some example code wherein you're seeing this issue?

**Comment by zclch** [comment]
Hi, found this issue Googling. I'm encountering the same issue in a block of code that is a for loop with an if statement.

`
for(cn in interviews.colnames) {
   .local1 <- ...
   .local2 <- ...
   if(.local1 < .local2) {
      ...
   }
}
`

Once I change the if statement to be (local1 < local2) the binding warning spam disappears in future runs.

RStudio 2023.12.1 Build 402
R version 4.3.3 (2024-02-29 ucrt)

**Comment by kevinushey** [comment]
@zclch thank you! I can reproduce the "bad binding access" error if I run this code in a fresh R session:

```
for (cn in c("a", "b")) {
  .local1 <- 1
  .local2 <- 2
  if (.local1 < .local2) {
  }
}
```

We'll try to further investigate.

**Comment by kevinushey** [comment]
@zclch thanks again for providing a reproducible example; I believe we now have a fix for this issue. You should see this available in the daily builds tomorrow at https://dailies.rstudio.com -- if you have a chance, would you be able to test and report back?

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+652 on Windows 11.

**Comment by mikecrobe** [comment]
Thank you all
