### ISSUE TITLE
some packages fail to maintain installed updates 

### ISSUE THREAD

**Issue by jkylearmstrong** [rstudio/rstudio#14235]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1 Build 402
    OS Version      :  Windows Version 22H2 (OS Build 22621.3007)
    R Version       :  R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

when in RStudio if I attempt to update the following packages:

![image](https://github.com/rstudio/rstudio/assets/29757798/75393b87-ecb9-4ff4-ba3f-1c8b0b9485f0)

with 
```
install.packages(c("cluster", "foreign", "lattice", "MASS", "Matrix", "mgcv", "nlme", "rpart"))
```

and then after restarting R and checking the "update" in RStudio the packages will still appear out of date.  

Unsure if the issue is related to `renv` within the project environment or a general problem, but it exists on 2 different windows PCs that I am currently working with. 

## check the boxes 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can you confirm what output you see in the Console after the packages are installed? Can you also share:

```
.libPaths()
find.package("cluster")
``

**Comment by ronblum** [comment]
FWIW, I'm seeing something odd in RStudio Desktop 2023.09.1+494 and 2023.12.1+402 on MacOS 14.3.
- I had two projects with `renv`, and the problem occurred in one and not the other other.
- I created another `renv` project, in which I believe the problem occurred.
- I added another project without `renv` which worked fine.
- Then I jumped around a bunch between all of the above, repeated the updates, restarted, etc. And suddenly, the problem went away.

**Comment by jkylearmstrong** [comment]
@kevinushey 

```
> install.packages(c("cluster", "foreign", "lattice", "MASS", "Matrix", "mgcv", "nlme", "rpart"), lib="C:/Users/tus75918/AppData/Local/R/cache/R/renv/sandbox/R-4.3/x86_64-w64-mingw32/1e360f03")
trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/cluster_2.1.6.zip'
Content type 'binary/octet-stream' length 591496 bytes (577 KB)
downloaded 577 KB

trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/foreign_0.8-86.zip'
Content type 'binary/octet-stream' length 275525 bytes (269 KB)
downloaded 269 KB

trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/lattice_0.22-5.zip'
Content type 'binary/octet-stream' length 1382070 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/MASS_7.3-60.0.1.zip'
Content type 'binary/octet-stream' length 1180409 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/Matrix_1.6-5.zip'
Content type 'binary/octet-stream' length 4562022 bytes (4.4 MB)
downloaded 4.4 MB

trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/mgcv_1.9-1.zip'
Content type 'binary/octet-stream' length 3381394 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/nlme_3.1-164.zip'
Content type 'binary/octet-stream' length 2353441 bytes (2.2 MB)
downloaded 2.2 MB

trying URL 'https://packagemanager.posit.co/cran/latest/bin/windows/contrib/4.3/rpart_4.1.23.zip'
Content type 'binary/octet-stream' length 710685 bytes (694 KB)
downloaded 694 KB

package ‘cluster’ successfully unpacked and MD5 sums checked
package ‘foreign’ successfully unpacked and MD5 sums checked
package ‘lattice’ successfully unpacked and MD5 sums checked
package ‘MASS’ successfully unpacked and MD5 sums checked
package ‘Matrix’ successfully unpacked and MD5 sums checked
package ‘mgcv’ successfully unpacked and MD5 sums checked
package ‘nlme’ successfully unpacked and MD5 sums checked
package ‘rpart’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\tus75918\AppData\Local\Temp\RtmpUREeyk\downloaded_packages
```

After install it seems to be fine:
![image](https://github.com/rstudio/rstudio/assets/29757798/1212d849-d372-43fc-a092-f2148e85aea1)


It's only after restart that I notice the same packages out of date:

![image](https://github.com/rstudio/rstudio/assets/29757798/3e351f57-7238-41d0-abf3-702a3be26fe9)

**Comment by jkylearmstrong** [comment]
@kevinushey 

```
Restarting R session...

- Project 'S:/Clinical Science/ProgrammingKA/KE_SHARE' loaded. [renv 1.0.3]
- The project is out-of-sync -- use `renv::status()` for details.
> .libPaths()
[1] "S:/Clinical Science/ProgrammingKA/KE_SHARE/renv/library/R-4.3/x86_64-w64-mingw32"        
[2] "C:/Users/tus75918/AppData/Local/R/cache/R/renv/sandbox/R-4.3/x86_64-w64-mingw32/1e360f03"
> find.package("cluster")
[1] "C:/Users/tus75918/AppData/Local/R/cache/R/renv/sandbox/R-4.3/x86_64-w64-mingw32/1e360f03/cluster"
```

**Comment by jkylearmstrong** [comment]
@ronblum I cross posted this to `renv` at https://github.com/rstudio/renv/issues/1817

**Comment by kevinushey** [comment]
Thanks, this is helpful. I think I understand the issue -- it looks like RStudio is trying to update packages installed into the system library, as per this output:

```
> install.packages(c("cluster", "foreign", "lattice", "MASS", "Matrix", "mgcv", "nlme", "rpart"), lib="C:/Users/tus75918/AppData/Local/R/cache/R/renv/sandbox/R-4.3/x86_64-w64-mingw32/1e360f03")
```

However, the sandbox is normally supposed to be considered read-only -- it normally just contains links to packages from the system library. We'll try to investigate a bit more on our side and see what we can do to resolve this.

**Comment by ronblum** [comment]
Since the environments in which I saw the issue cleared up, do either of you have an example of how to force the problem to happen?

Also @jkylearmstrong would you be willing to try this out with [a daily build](https://dailies.rstudio.com)? Please note that these are for testing purposes only, not production work.

**Comment by jkylearmstrong** [comment]
@ronblum - interestingly I seemed to have found a way to resolve on one of my PCs. 

I found that going into an empty RStudio session (without a project) and installing these packages seems to resolved the project that has `renv`. 

I would be happy to test out the daily build on my other computer - is the fix applied as of current? If so I can test tomorrow and let you know if it seems to work.

**Comment by jkylearmstrong** [comment]
@kevinushey & @ronblum although I have noticed similar issues with:
```
install.packages(c('gstat','spacetime','xlsx','xlsxjars'))
```

in a project that does not not have `renv`, so hopefully the fix will apply here as well

**Comment by ronblum** [comment]
@jkylearmstrong The latest open source desktop dailies have the fix (pro products are lagging a bit).

**Comment by jkylearmstrong** [comment]
@ronblum I installed the daily build:

RStudio 2024.04.0-daily+440 "Chocolate Cosmos" Daily (017994e650caa386966773e1208a338354b62074, 2024-02-12) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+440 Chrome/120.0.6099.276 Electron/28.2.2 Safari/537.36

after install all projects now read as up-to-date, what's interesting is that I did not have to reinstall the packages that I was having the issue with. As soon as I installed the daily build it just registered the packages as up-to-date:

![image](https://github.com/rstudio/rstudio/assets/29757798/a522a49c-59e2-4098-b536-255826ccfcba)

**Comment by ronblum** [comment]
@jkylearmstrong Awesome, thanks for checking! I'll close this issue as verified. However, if this issue returns, please let us know.
