### ISSUE TITLE
Paste multiple file paths from Windows Explorer

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#14240]
To close #4572, a new feature was added to [2023.12.0-daily+302](https://dailies.rstudio.com/version/2023.12.0-daily+302) that lets Windows users copy a file from the Explorer and paste it into RStudio to get a path. 

Could this feature please be extended so that copying multiple files pastes a path for each one across multiple lines? For example, copying this:

![image](https://github.com/rstudio/rstudio/assets/3200601/562703df-38a8-4ab0-8d94-99528c82fc9a)

would produce:

```
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09A_AUST_SA1.csv"
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09B_AUST_SA1.csv"
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09C_AUST_SA1.csv"
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09D_AUST_SA1.csv"
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09E_AUST_SA1.csv"
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09F_AUST_SA1.csv"
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09G_AUST_SA1.csv"
"C:/Dropbox/Projects/Datasets/Aus Census 2021/All Aus, first release/2021Census_G09H_AUST_SA1.csv"
```

Thank you :3

**Comment by ronblum** [comment]
@DesiQuintans Thank you for the suggestion!

Note: Currently, if multiple files are selected, only the path to the first one is pasted. The order is based on whichever was chosen first, e.g. the top file if chosen top-down if sorted in any order, the bottom file if chosen bottom-up with any sorting, or multiple files chosen individually (e.g. with <kbd>Cmd-Click</kbd> on MacOS).

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 202404.0-daily+555.pro3 on Windows 11
- Posit Workbench 202404.0-daily+555.pro3 on Ubuntu 22.04 via Chrome on Windows 11

Checked with Quarto and R Markdown in visual and source mode.
