### ISSUE TITLE
Viewer very slow for data.frames with nested columns.

### ISSUE THREAD

**Issue by tilltnet** [rstudio/rstudio#14257]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.12.1 Build 402
    OS Version: Ubuntu 23.10 and Windows 11
    R Version: 4.3.1

### Steps to reproduce the problem

```
library(dplyr)
df1 <-
  lapply(1:100,
         \(x) sample(1:40000, 20000)) |>
  as.data.frame()

df2 <-
  tibble(a = lapply(1:30, \(x) slice_sample(df1, n = 15000)))

View(df2)
```

### Describe the problem in detail

When using the RStudio Viewer to inspect a `data.frame` with nested columns that contain `data.frame`s, the Viewer takes a long time to display the data. During that time the R session is unresponsive, files can not be saved. At the `data.frame` size shown in the example above, the issue becomes noticeable. With increased size, the issue gets worse, RStudio seems to be stuck indefinitely, and killing the R session via OS tools is required. This slowdown also happens whenever the autocompletion data preview is triggered on such a `data.frame`. 

### Describe the behavior you expected

The Viewer should display the data without noticeable delay. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tilltnet Thank you for raising this issue! I'm unable to reproduce using the code above, because it depends on the object `motherframe`. Can you provide an example with this defined, or else an example that doesn't depend on it? This way I can try to reproduce using the same steps. Thanks!

**Comment by tilltnet** [comment]
@ronblum I corrected the example.

**Comment by tilltnet** [comment]
This seems to be an R issue at the core. I just tested the example above in RGui. The issue is present there, too. I think RStudio lagging out when the autocompletion data preview is triggered might still be something that could be addressed on the RStudio side.

**Comment by kevinushey** [comment]
We can use the R profiler to see where all of the time is being spent:

```
> Rprof("~/scratch/view.Rprof")
> View(df2)
> Rprof(NULL)
> summaryRprof("~/scratch/view.Rprof")
$by.self
               self.time self.pct total.time total.pct
"as.character"      4.50    98.68       4.50     98.68
"nchar"             0.04     0.88       0.04      0.88
"cb$putconst"       0.02     0.44       0.02      0.44

$by.total
                           total.time total.pct self.time
".rs.formatDataColumn"           4.54     99.56      0.00
".rs.formatDataColumnList"       4.54     99.56      0.00
"as.character"                   4.50     98.68      4.50
"nchar"                          0.04      0.88      0.04
"cb$putconst"                    0.02      0.44      0.02
".rs.callAs"                     0.02      0.44      0.00
"cmp"                            0.02      0.44      0.00
"cmpCall"                        0.02      0.44      0.00
"cmpCallArgs"                    0.02      0.44      0.00
"cmpCallSymFun"                  0.02      0.44      0.00
"cmpfun"                         0.02      0.44      0.00
"compiler:::tryCmpfun"           0.02      0.44      0.00
"doTryCatch"                     0.02      0.44      0.00
"f"                              0.02      0.44      0.00
"genCode"                        0.02      0.44      0.00
"h"                              0.02      0.44      0.00
"tryCatch"                       0.02      0.44      0.00
"tryCatchList"                   0.02      0.44      0.00
"tryCatchOne"                    0.02      0.44      0.00
"tryInline"                      0.02      0.44      0.00
"View"                           0.02      0.44      0.00
"withCallingHandlers"            0.02      0.44      0.00

$sample.interval
[1] 0.02

$sampling.time
[1] 4.56
```

In essence, RStudio is trying to call `as.character()` on each list column to get a textual representation of the column contents, and that's very slow for such large list columns.

Perhaps we should be truncating list columns in some intelligent way before trying to format them for display?

Reference: https://github.com/rstudio/rstudio/blob/2d2dcd9db6f3ee0e15903ae377cf89931fc1f2d0/src/cpp/session/modules/SessionDataViewer.R#L101-L115

**Comment by tilltnet** [comment]
Maybe the process for nested columns in `pillar:::print.tbl()` can be applied here? `pillar:::print.tbl()` gives valuable information on nested columns and prints `df2` from the example instantaneously.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11 and RStudio Desktop Pro 2024.07.0-daily+294.pro1 on Ubuntu 24.04. 

Also @tilltnet I never thanked you for the updated example--thank you!
