### ISSUE TITLE
Attributes "variable.labels" are not shown under column names in the View() function

### ISSUE THREAD

**Issue by arodionoff** [rstudio/rstudio#14265]
### System details

    RStudio Edition : Desktop and Server 
    RStudio Version : Later RStudio **2023.03 "Cherry Blossom"**
    OS Version      : Windows and Ubuntu
    R Version       :  4.*

### Steps to reproduce the problem

When I execute the code

```r
df <- data.frame(x = c(1, 2, 3), y = c(4, 5, 6))
attr(df, "variable.labels") <-  c(x = "This is x", y = "This is y")
View(df)
```
I see attributes of "variable.labels" under column names in the View() function on RStudio **2022.07.4+587 "Spotted Wakerobin"**, RStudio **2022.12.1+366 "Elsbeth Geranium"** & RStudio **2023.03.3+547 "Cherry Blossom"**.

![Show](https://github.com/rstudio/rstudio/assets/25921699/10d762c1-7ae3-4686-9548-fc1ef85faddc)

### Describe the problem in detail

However, with version RStudio **2023.06.3+581 "Mountain Hydrangea**" and **later** (include the last RStudio **2024.04.0**-daily+426 "Chocolate Cosmos") there is no display attributes of "variable.labels".

![NotShow](https://github.com/rstudio/rstudio/assets/25921699/cbeed18c-99da-45df-b726-c6bd2ec4edb1)

There is a similar problem with displaying attributes of "variable.labels" with these versions for Server Solutions, for example, on https://posit.cloud/

### Describe the behavior you expected

Please ensure that "variable.labels" are shown when calling the `View()` function, as was implemented in earlier versions of RStudio and still applies to "labels" (for example, `labelled::set_variable_labels()`).

**Comment by ronblum** [comment]
@arodionoff Thank you for raising this! We'll review this bug as we continue work on RStudio.

Reproducible in RStudio Desktop 2024.04.0-daily+440 on MacOS 14.3 and Posit Workbench 2024.04.0-daily+330.pro5 on Red Hat 9 via Chrome on MacOS 14.3.

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 2024.04.0-daily+495 on MacOS 14.4
- Posit Workbench 2024.04.0-daily+478.pro12 on Ubuntu 22.04 via Chrome on MacOS 14.4

Tested with both the example above and with a label that's too long to be displayed fully.
