### ISSUE TITLE
Display Quarto version information in About dialog

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14263]
It is difficult to know which version of Quarto that RStudio has chosen. Normally it uses the bundled version but there are various ways a user can override this with their own version.

- set the path to alternate Quarto in the `RSTUDIO_QUARTO` environment variable
- add an alternate Quarto to the PATH
- use the Quarto Version Manager / qvm (this is a work in progress, see https://github.com/rstudio/rstudio/issues/14177)

Strategies to determine Quarto version using things like `Sys.which("quarto")`  in the Console or `which quarto` in the Terminal pane aren't guaranteed to give the same result as the version RStudio has chosen (due to potential differences in the environment).

It would be helpful to show the Quarto version info in the About dialog. We already have this information in the SessionInfo.

**Comment by ronblum** [comment]
Things to look for:
- Quarto installed
- Bundled version
- Standalone Quarto
- Changing Quarto version
- No Quarto available (munge the bundled versions path or name)

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2024.04.0-daily+495 on MacOS 14.4
- Posit Workbench 2024.04.0-daily+478.pro12 on Ubuntu 22.04 via Chrome on MacOS 14.4
