### ISSUE TITLE
File name doesn't include extension

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#14261]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0-daily+440:
    OS Version      : MacOS 14.3
    R Version       : 4.3.2

### Steps to reproduce the problem

1. Create a new R script.
2. Save the script.
    - The default name is `Untitled` with no file extensions.
    - The format is `All files`.
3. Change the format to `R`.
    - The file name is changed to `Untitled.R`.

The same occurs for other file types such as Quarto and R Markdown.

### Describe the problem in detail

The default  file name doesn't contain the file extension. In RStudio Desktop 2024.04.0-daily+440:
<img width="363" alt="Screenshot 2024-02-13 at 12 13 17" src="https://github.com/rstudio/rstudio/assets/31009952/5f32338b-e69c-423b-afe3-2a933ace2486">

Compare this to what we get when we set the file type:
<img width="355" alt="Screenshot 2024-02-13 at 12 19 56" src="https://github.com/rstudio/rstudio/assets/31009952/25dc5f1e-e0f5-486f-a88a-09a436b2c597">

And compare to RStudio Desktop 2023.12.1+402:
<img width="360" alt="Screenshot 2024-02-13 at 12 13 51" src="https://github.com/rstudio/rstudio/assets/31009952/5fd25268-4c24-4ccf-8ef8-1646c8c7cdd2">

### Describe the behavior you expected

The file type should be recognized and its extension used in the file name.

I only checked on MacOS. I'll check on Linux.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Cross reference: https://github.com/rstudio/rstudio/pull/14053
