### ISSUE TITLE
Keyboard Shortcuts abruptly stopped working

### ISSUE THREAD

**Issue by mputt** [rstudio/rstudio#14260]
### System details

    RStudio Edition : 2023.12.1+402
    RStudio Version :  4.3.2
    OS Version      :  Sonoma 14.1.2
    R Version       : 

### Steps to reproduce the problem

Press Cmd+Enter no longer works to run current selection or line.
Remapping Keyboard for Run line no longer works

### Describe the problem in detail

This keyboard shortcut abruptly stopped working  while I was coding an R markdown file. I tried remapping using the Global Options > Code menu without any luck. 

This is an intermittent bug. It happened once before. 

I have updated to the most recent version of Rstudio (but not R). I have restarted my computer. I have tried to remap my shortcuts. None of these were successful. Thanks for any insights. 

### Describe the behavior you expected

I expect a keyboard shortcut to work the way it is documented in the keyboard shortcuts menu. 

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mputt Thank you for raising this! Does this only occur for running the current line/selection, or does it occur for other or all shortcuts?

**Comment by mputt** [comment]
It seems to occur for some but not all shortcuts that are under the “Scope=R” section of the shortcuts.

It is very bizarre as it literally stopped working—just broke-- while I was editing some code in Rmarkdown without changing anything. I have tried remapping to various different keystrokes and nothing works.

Iam closing everything and restarting my computer.

Thanks for your help

Mary

Mary Putt, PhD, ScD
Professor & Deputy Director of Biostatistics
621 Blockley Hall
Department of Biostatistics, Epidemiology & Informatics
Perelman School of Medicine, University of Pennsylvania
Philadelphia, PA 19104

Ph. 215-573-7020


From: Ron Blum ***@***.***>
Date: Tuesday, February 13, 2024 at 12:12 PM
To: rstudio/rstudio ***@***.***>
Cc: mputt ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [rstudio/rstudio] Keyboard Shortcuts abruptly stopped working (Issue #14260)

@mputt<https://urldefense.com/v3/__https:/github.com/mputt__;!!IBzWLUs!V_r7M9fV3ZnhLBGYhg2jcDxUdZR8xDqadJkLw7W-_PKbfF28G9DVdQQmxM9uLxdgeLkUncbHqG-oVNyDo6LD9Jc$> Thank you for raising this! Does this only occur for running the current line/selection, or does it occur for other or all shortcuts?

**Comment by mputt** [comment]
OK, closed absolutely everything on my computer including Microsoft packages, zoom and various stuff that opens automatically with Mac OS,  and restarted. I have my shortcuts back. No idea why.

Thanks for looking into this.



Mary

Mary Putt, PhD, ScD
Professor & Deputy Director of Biostatistics
621 Blockley Hall
Department of Biostatistics, Epidemiology & Informatics
Perelman School of Medicine, University of Pennsylvania
Philadelphia, PA 19104

Ph. 215-573-7020


From: Putt, Mary ***@***.***>
Date: Tuesday, February 13, 2024 at 12:29 PM
To: rstudio/rstudio ***@***.***>
Subject: Re: [External] Re: [rstudio/rstudio] Keyboard Shortcuts abruptly stopped working (Issue #14260)
It seems to occur for some but not all shortcuts that are under the “Scope=R” section of the shortcuts.

It is very bizarre as it literally stopped working—just broke-- while I was editing some code in Rmarkdown without changing anything. I have tried remapping to various different keystrokes and nothing works.

Iam closing everything and restarting my computer.

Thanks for your help

Mary

Mary Putt, PhD, ScD
Professor & Deputy Director of Biostatistics
621 Blockley Hall
Department of Biostatistics, Epidemiology & Informatics
Perelman School of Medicine, University of Pennsylvania
Philadelphia, PA 19104

Ph. 215-573-7020


From: Ron Blum ***@***.***>
Date: Tuesday, February 13, 2024 at 12:12 PM
To: rstudio/rstudio ***@***.***>
Cc: mputt ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [rstudio/rstudio] Keyboard Shortcuts abruptly stopped working (Issue #14260)

@mputt<https://urldefense.com/v3/__https:/github.com/mputt__;!!IBzWLUs!V_r7M9fV3ZnhLBGYhg2jcDxUdZR8xDqadJkLw7W-_PKbfF28G9DVdQQmxM9uLxdgeLkUncbHqG-oVNyDo6LD9Jc$> Thank you for raising this! Does this only occur for running the current line/selection, or does it occur for other or all shortcuts?

**Comment by ronblum** [comment]
@mputt Ah yes, turning it off and on again... I'm glad that it's working now! I'll close the issue, but please let us know if you run into it again.
