### ISSUE TITLE
RStudio <Plots> resizes images

### ISSUE THREAD

**Issue by Mortrus** [rstudio/rstudio#14272]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-28) for windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
    OS Version      : Windows 11 Pro x64 (10.0, build 22621) 
    R Version       :  4.3.2

### Steps to reproduce the problem
1. Change size of "Plots" pane to something small
2. Create a new Python script
3. Paste and run the code

```
import matplotlib.pyplot as plt
import seaborn as sns
cm = [[56, 5],[8, 64]]
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=True)
plt.title("A bit long name for Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()
```

### Describe the problem in detail
There is an issue with images displaying that are generated by matplotlib. If the canvas size of Plots is different, the image is rendered stretched or shrunk. Sometimes, when there are additional elements on the plot (custom text, colorbar), they start to overlap each other.
![1](https://github.com/rstudio/rstudio/assets/42960438/7a58aa6f-38ea-451b-8468-41802927b204)
![2](https://github.com/rstudio/rstudio/assets/42960438/deef2328-3102-4d8c-abf3-584d0d14cd46)

If the canvas size of the Plot is bigger than the figure size, extra empty areas around the image are added. Consequently, when you export this image, these areas appear in the output image.
![3](https://github.com/rstudio/rstudio/assets/42960438/b0e82d2e-070e-4d1c-90b4-1b26b6711911)

However, if I save the plt to a file before plt.show(), the saved image is correct. Still, after plt.show(), the bug persists. This indicates that the object inside plt is generated correctly.

### Describe the behavior you expected
1. When displayed, the generated image should not be stretched or shrunk but resized to the size of the Plot canvas.
2. When exported, the original image should be exported as it was set in the plt object (size, dpi, and others).

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Mortrus Thank you for raising this! This is the same with R plots (e.g. `plot(cars)`) and is the expected behavior—control the plot display by adjusting the Plots Pane. However, I'll switch this to an enhancement request to provide an option for maintaining an explicitly defined plot size.
