### ISSUE TITLE
Stepping with duplicated lines can be wrong when `keep.source = FALSE`

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#14276]
CC @kevinushey, this is what I mentioned yesterday about seeing cases where duplicate lines make the debugger bounce around

Let's fake the idea of stepping into a function from a package where you don't have source refs (pretty common)

```r
eval(parse(text = "fn <- function() {
  x <- 1
  1 + 1
  x <- 1
  2 + 2
  3 + 3
  x <- 1
  1
}", keep.source = FALSE))

debugonce(fn)
fn()
```

Note that `x <- 1` is duplicated here. This results in the following stepping behavior:

https://github.com/rstudio/rstudio/assets/19150088/bde8edcf-2fb3-4a3e-889d-afec95a8a57b

If you remove the `keep.source = FALSE` part, then things do work as expected.

I know that when there aren't source refs, we essentially end up grepping for `x <- 1` in the sources of the function itself. It seems like we try and keep track of the previous debug line and use it as a minimum "line preference" here:
https://github.com/rstudio/rstudio/blob/5ebce31057bf85d0d89f975898c5bde957a08dec/src/cpp/session/modules/SessionEnvironment.R#L290

In theory that should work well when it is used here:
https://github.com/rstudio/rstudio/blob/5ebce31057bf85d0d89f975898c5bde957a08dec/src/cpp/session/modules/SessionEnvironment.R#L350-L352

I have a feeling that somehow this `lastDebugLine` is not being updated correctly for some reason in the no-srcref case:
https://github.com/rstudio/rstudio/blob/5ebce31057bf85d0d89f975898c5bde957a08dec/src/cpp/session/modules/environment/SessionEnvironment.cpp#L748

**Comment by jthomasmock** [comment]
Might be related to #13925

**Comment by ronblum** [comment]
Verified that debugger doesn't jump around in
- RStudio Desktop 2024.04.0-daily+573 on MacOS 14.4
- RStudio Server 2024.04.0-daily+573 on Ubuntu 22.04 via Chrome on MacOS 14.4
