### ISSUE TITLE
Error message when requesting completion in a package

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14273]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0+426
    OS Version      : Windows 10
    R Version       : 4.3.2

### Steps to reproduce the problem

Originally reported in https://github.com/rstudio/rstudio/issues/14232#issuecomment-1944042373. (the problem doesn't seem to happen when requesting regular completion, i.e. not via `load_all()`.

1. Open a  package project that contains functions.
2. `devtools::load_all()`
3. In the console (or in R file), type that function and request argument completion via Tab

### Describe the problem in detail

An error message prints to console.

```r
Error in strsplit(file, "/", fixed = TRUE) : 
  argument is not a character
```

I suspect it comes from here.

https://github.com/rstudio/rstudio/blob/bfd6bf382d8ab57268a1bfc788a4d02c9221e1b9/src/cpp/session/modules/SessionHelp.R#L812

After a bit of investigation, I think that for some reason, a function seems to be passed on to file.

I added those lines to the function for debugging
```r
   stop(class(file), args(file) |> format())
      parts <- strsplit(file, "/", fixed = TRUE)[[1L]]
```

With debugging, I see that the function signature is:
```r
function (description = "", open = "", blocking = TRUE, encoding = getOption("encoding"),     raw = FALSE, method = getOption("url.method", "default")) NULL
```
Traceback is 
```r
4: .rs.getHelp(functionName, src)
3: .rs.getHelpArgument(what, from, parent.frame())
2: impl()
1: .rs.rpc.get_help("read_population_data", NULL, 7L)
```

Note that autocompletion system for functions in `load_all()` did not reach this part of the function before a281d7f

When I press Tab, this appears
![image](https://github.com/rstudio/rstudio/assets/52606734/bfe8cdc3-7fc8-461d-957b-7ac3fa30b6b5)

### Describe the behavior you expected

I would expect no message.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks -- I suspect it's related to this commit.

https://github.com/rstudio/rstudio/commit/ac1749b051167b38e338969964d64d20c23d5951

I'll take a look.

**Comment by olivroy** [comment]
All good now!! thanks
