### ISSUE TITLE
Rstudio server doesn't follow RSTUDIO_WHICH_R

### ISSUE THREAD

**Issue by Oakento** [rstudio/rstudio#14284]
### System details

    RStudio Edition : Server
    RStudio Version : RStudio 2023.03.3+547 "Cherry Blossom" Release 
    OS Version      : Ubuntu 22
    R Version       :  4.2.3 and 4.3.0

### Steps to reproduce the problem
```bash
# R-4.2.3 and R-4.3.0 installed in /opt/R/4.2.3 and /opt/R/4.3.0
ln -s /opt/R/4.2.3/bin/* /usr/local/bin
# Rstudio starts with R-4.2.3

echo "export RSTUDIO_WHICH_R=/opt/R/4.3.0/bin/R" >> ~/.bash_profile
sudo systemctl restart rstudio-server.service
# Reload rstudio, but R version remains 4.2.3
```

### Describe the problem in detail
Rstudio server doesn't follow RSTUDIO_WHICH_R set in .bash_profile or .bashrc. Setting the variable in .Renviron doesn't solve the problem.  

### Describe the behavior you expected
Rstudio server loads R-4.3.0.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
RStudio Server isn't running as your user account, so it's not going to see changes you make to your own user account's `.bash_profile`.

Instead, you should probably use `rsession-which-r`:

https://docs.posit.co/ide/server-pro/reference/rserver_conf.html#rsession-which-r
