### ISSUE TITLE
`install.packages()` in RStudio ignores custom `headers` argument when listing available packages

### ISSUE THREAD

**Issue by glin** [rstudio/rstudio#14282]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1
    OS Version      : Ubuntu 20.04
    R Version       : 4.2.3

### Steps to reproduce the problem

In a fresh R session, turn on libcurl debug output and try to install any package with a custom `headers` argument in `install.packages()`:
```r
options(internet.info = 1)
install.packages("R6", headers = c(Authorization = "Bearer test123"))

# > GET /src/contrib/PACKAGES.rds HTTP/1.1
# Host: cloud.r-project.org
# User-Agent: R/4.2.3 (ubuntu-20.04) R (4.2.3 x86_64-pc-linux-gnu x86_64 linux-gnu)
# Accept: */*
# Pragma: no-cache
#
# > GET /src/contrib/R6_2.5.1.tar.gz HTTP/1.1
# Host: cloud.r-project.org
# User-Agent: R/4.2.3 (ubuntu-20.04) R (4.2.3 x86_64-pc-linux-gnu x86_64 linux-gnu)
# Accept: */*
# Authorization: Bearer test123
```
The initial request to `PACKAGES.rds` is missing the custom header, while the subsequent package download includes it.

In another new R session, compare with `utils::install.packages()`:
```r
options(internet.info = 1)
utils::install.packages("R6", headers = c(Authorization = "Bearer test123"))

# > GET /src/contrib/PACKAGES.rds HTTP/1.1
# Host: cloud.r-project.org
# User-Agent: R/4.2.3 (ubuntu-20.04) R (4.2.3 x86_64-pc-linux-gnu x86_64 linux-gnu)
# Accept: */*
# Authorization: Bearer test123
# Pragma: no-cache
#
# > GET /src/contrib/R6_2.5.1.tar.gz HTTP/1.1
# Host: cloud.r-project.org
# User-Agent: R/4.2.3 (ubuntu-20.04) R (4.2.3 x86_64-pc-linux-gnu x86_64 linux-gnu)
# Accept: */*
# Authorization: Bearer test123
```
The initial request to `PACKAGES.rds` includes the custom header.

### Describe the problem in detail

From skimming other issues, this is probably the same type of issue as #13247

Running `install.packages()` in RStudio ignores the custom request `headers` argument on the initial request to list available packages from `PACKAGES.rds`. But passes the headers as expected on the subsequent package download. The vanilla `utils::install.packages()` will pass custom headers correctly in both requests.

This makes it harder to install packages from authenticated repos in the IDE, if you're just using `install.packages()` and want to pass authorization headers through the `headers` arg. It would be nice to fix this, but also maybe not as important if pak or renv end up being the main way users install from authenticated repos.

### Describe the behavior you expected
Custom headers should be passed through on the `PACKAGES.rds` request

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! I think this is coming from here:

https://github.com/rstudio/rstudio/blob/0557cc4c2136a8a34b2abb62f747b9600ead0d71/src/cpp/session/modules/SessionPackages.R#L158

The `.rs.loadedPackageUpdates()` function uses `available.packages()` to check what packages are available, but it doesn't pass along the headers argument:

https://github.com/rstudio/rstudio/blob/0557cc4c2136a8a34b2abb62f747b9600ead0d71/src/cpp/session/modules/SessionPackages.R#L813

**Comment by gtritchie** [comment]
I reproduced the issue using RStudio 2023.12.1 on Ubuntu 22, then upgraded to build 2024.04.0-daily+612 and am now seeing the custom header argument in the both the initial PACKAGES.rds call, and the actual download.

```R
> install.packages("R6", headers = c(Authorization = "Bearer test123"))
> GET /src/contrib/PACKAGES.rds HTTP/2
Host: cloud.r-project.org
user-agent: RStudio Desktop (2024.4.0.612); R (4.1.2 aarch64-unknown-linux-gnu aarch64 linux-gnu)
accept: */*
authorization: Bearer test123
pragma: no-cache
```

```R
> GET /src/contrib/R6_2.5.1.tar.gz HTTP/2
Host: cloud.r-project.org
user-agent: RStudio Desktop (2024.4.0.612); R (4.1.2 aarch64-unknown-linux-gnu aarch64 linux-gnu)
accept: */*
authorization: Bearer test123
```
