### ISSUE TITLE
Unsaved documents modal is not showing when attempting to publish

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#14298]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2024.04.0-daily+456
    OS Version      : ubuntu22
    R Version       : 4.3.2

This was caught in our automation test `test_publishing_rmarkdown_doc`
The test last passed in build: 2024.04.0-daily+440
The test first failed in build: 2024.04.0-daily+456

### Steps to reproduce the problem

1. Create an rmarkdown file with the default content.
2. Click to publish the document. 

### Describe the problem in detail
The user is not prompted to save the document and nothing happens with they click to publish.

### Describe the behavior you expected
I am expecting to see the following modal show for unsaved documents.
![Screenshot 2024-02-20 at 9 34 46 AM](https://github.com/rstudio/rstudio/assets/1482677/e3a15b40-7b29-40e9-80e7-182701b15d75)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
This looks like it might be a similar issue with the test `test_new_connection_enabled_if_deps_install_canceled` The test tries to connect to a databricks instance when the dependencies are not installed and clicks no when prompted to install the required dependencies and then the user should see the following modal but are no longer seeing this modal show.
![Screenshot 2024-02-20 at 1 19 17 PM](https://github.com/rstudio/rstudio/assets/1482677/5fd8c940-dec9-4c9d-9a8b-7e527bb436ad)

**Comment by kevinushey** [comment]
Looks like this started here: https://github.com/rstudio/rstudio/commit/83d56267317c7c16b79697020bb66434e81c50f9

@GCRev, do you recall the motivation for checking whether the message provided is empty in each case?

**Comment by kevinushey** [comment]
Sorry, I misdiagnosed it -- I mixed up the conditional when I refactored some of the code in https://github.com/rstudio/rstudio/commit/87cdcf4ed0c9d6c2e1248f28d1dd41be229a321f#diff-91904e55f8d9d24641be10cdafa440663c98196fdd46fd8bc31f7a58e3b9cecaR358. 😞

**Comment by gtritchie** [comment]
I reproduced the issue with build 2024.04.0-daily+456 on Mac. Installed 2024.04.0-daily+456 and now get the expected dialog:

![screenshot of RStudio showing the expected message dialog](https://github.com/rstudio/rstudio/assets/10569626/604f9e66-c252-49d5-a213-13ea65f81e81)
