### ISSUE TITLE
CLIENT-EXCEPTION:TypeError

### ISSUE THREAD

**Issue by hahahaL** [rstudio/rstudio#14293]
### System details
    RStudio Edition : Server 
    RStudio Version : 2022.02.2+485 (Prairie Trillium) for CentOS 7
    OS Version      : CentOS Linux release 7.6.1810 (Core)
    R Version       : R version 3.6.0 (2019-04-26)

### Steps to reproduce the problem
```
rserver[232013]: ERROR CLIENT EXCEPTION (rsession-): 
TypeError: Cannot read properties of undefined (reading 'cleanClipboard');|||rstudio-0.js#-1::eval|||Client-ID: e3770685-ef71-4156-b607-0165900784d7|||User-Agent: Mozilla/5.0 (Windows NT 10.0  WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
```

**Comment by ronblum** [comment]
@hahahaL Thank you for filing this bug report! Under what conditions does this error occur?
