### ISSUE TITLE
Copilot doesn't include indexed file information when creating suggestions in *Untitled* files.

### ISSUE THREAD

**Issue by JacobBumgarner** [rstudio/rstudio#14291]
### System details

    RStudio Edition : Server
    RStudio Version :  2023.12.1 Build 385
    R version 4.3.1 (2023-06-16)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 18.04.6 LTS

### Steps to reproduce the problem
1. Assuming Copilot is already configured, make sure indexing is enabled.
2. Create an example `R` file with some random but obvious function name. Create a fake pipeline that leads to a clear use case for the function. Try using the pipeline in an `Untitled.R` file, then try the pipeline in a `Named.R` file. Below is an example with a fake function named `ab_plot`.

### Describe the problem in detail
Per the steps above, the files are stored as follows in the `RProj` directory: 
- `code/ab_plot.R`
- `code/saved.R`

**Fake function definition (generated by Copilot...):**
<img width="50%" alt="Screenshot 2024-02-16 at 8 04 58 PM" src="https://github.com/rstudio/rstudio/assets/70919881/8e1955aa-7888-407d-ac9d-96cc03438583">

**Saved file with pipeline that would clearly use the fake function:**
<img width="50%" alt="Screenshot 2024-02-16 at 8 04 51 PM" src="https://github.com/rstudio/rstudio/assets/70919881/11f275e7-bf6d-4eb6-9c33-1a808ea46a0b">

**Untitled file with the same pipeline consistently will not call the function:**
<img width="50%" alt="Screenshot 2024-02-16 at 8 01 57 PM" src="https://github.com/rstudio/rstudio/assets/70919881/ed06db72-c5ee-4175-a57f-9b0d0e1f3418">

### Describe the behavior you expected
Ideally, Copilot would use indexed file recommendations regardless of the active source file. This behavior is unexpected and confusing for the user.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@JacobBumgarner Thank you for raising this! This is covered by issue #14051, so I'm closing this issue as a duplicate
