### ISSUE TITLE
Docs: GitHub Copilot free for students and faculty

### ISSUE THREAD

**Issue by ShKlinkenberg** [rstudio/rstudio#14302]
https://github.com/rstudio/rstudio/blob/018ea143118a15d46a5eaef16a43aef28ac03fb9/docs/user/rstudio/ide/guide/tools/copilot.qmd#L241

Is it worth while to mention here that GitHub Copilot can be used for free by students and faculty through the [education benefits program](https://education.github.com/benefits)?

**Comment by kevinushey** [comment]
Sounds like a good idea to me -- thanks for the heads up!

**Comment by ronblum** [comment]
Verified in RStudio IDE User Guide revision 27 published June 27, 2024.
