### ISSUE TITLE
renv.lock not appearing in Go to File/Function

### ISSUE THREAD

**Issue by fh-mthomson** [rstudio/rstudio#14313]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : Version 2023.12.1+402 and 2023.12.1 Build 402.pro1
    OS Version      :  Mac and Ubuntu Jammy
    R Version       :  4.1.3

### Steps to reproduce the problem

* Open an R project with an `renv.lock` file
* Open `Go to File/Function` (Ctrl + .)
* Search for `renv.lock` or `renv`

![image](https://github.com/rstudio/rstudio/assets/56164984/e5158380-ce0c-4f53-a90f-4596b165bcee)

### Describe the problem in detail
If I want to quickly open a file while working in an R project in RStudio IDE, I use the above workflow to open common files (.Renviron, .R, test files, setup.R etc).

However, `renv.lock` doesn't seem to be indexed; instead I need to navigate to Files -> hope I'm in the right directory -> click on `renv.lock` 

### Describe the behavior you expected

`renv.lock` is returned as an option

![image](https://github.com/rstudio/rstudio/assets/56164984/b97bdbe7-3ba8-4520-9fd7-55e27e084100)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fh-mthomson Thank you for raising this. I can reproduce this. As a comparison point, another special file, `.gitignore`, gets returned; on the other hand, regular files without a suffix get ignored. This might be intentional, but I'll mark this for review.

**Comment by kevinushey** [comment]
Should be resolved via https://github.com/rstudio/rstudio/commit/cb7f275bfe6f290272b6eae6e6667852c1d51d59.

**Comment by ronblum** [comment]
Verified that searches now return `renv.lock` in RStudio Desktop 2024.04.0-daily+558 on MacOS 14.4.
