### ISSUE TITLE
Cmd+Shift+M no longer works, cannot be specified for pipe shortcut

### ISSUE THREAD

**Issue by singing-scientist** [rstudio/rstudio#14316]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1+402
    OS Version      : Apple M2 Max, macOS Sonoma 14.3.1
    R Version       : R version 4.3.1 (2023-06-16) -- "Beagle Scouts"

### Steps to reproduce the problem

Pressing Cmd+Shift+M no longer inserts a pipe. Global Options > Code > Modify Keyboard Shortcuts > "Insert Pipe Operator" defaults to Ctrl+Shift+M but does not allow one to reset it to Cmd+Shift+M, the old default. (No other Shortcut seems to be using Cmd+Shift+M.)

### Describe the problem in detail

Same as above (simple problem).

### Describe the behavior you expected

Cmd+Shift+M should insert a pipe (|> or %>%) and/or it should be possible to manually set the keyboard shortcut to this combination.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@singing-scientist Thank you for raising this! Do you see the issue with both the default `%>%` and with the native `|>` pipe enabled? You can set it at <kbd>Tools -> Global Options -> Use Native Pipe Operator</kbd>  
<img width="171" alt="pipe" src="https://github.com/rstudio/rstudio/assets/31009952/ebb2d30a-f1e7-4e39-9634-4af7d384145b">


Also, I can't reproduce this in RStudio Desktop 2023.12.1+402 and 2024.04.0-daily+475 on MacOS 14.3. It's an Intel Mac, though—I doubt this this makes a difference, but @jonvanausdeln can you try this out on an M1?

**Comment by singing-scientist** [comment]
Greetings @ronblum and thanks so much! Indeed, I have the same issue when the native pipe operator is not checked (I had it checked). When I go to re-define the shortcut myself, it doesn't accept Cmd+Shit+M as an input, i.e., when I delete Ctrl+Shift+M and press the combination I want (Cmd+Shift+M), nothing happens. Contrarily, other combinations work (say, at random, Cmd+Shift+K, pictured).
<img width="746" alt="Screenshot 2024-02-23 at 2 24 31 PM" src="https://github.com/rstudio/rstudio/assets/12587124/50e981cd-cfc7-43f5-abe9-fd82c9e52bce">

**Comment by gtritchie** [comment]
I'm not able to repro on my M1 Mac with 2023.12.1+402.

To determine if this is an issue with RStudio itself or (perhaps) some other application has registered a global shortcut handler for <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>, try this:

Main menu: `Help / Diagnostics / Show Keyboard Shortcut Commands`

This will show a yellow bar at the bottom of the RStudio window. When you type a keyboard shortcut, it will show the name of the command the shortcut is bound to, or "Shortcut not bound".

For me, when I type <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> I see:

<img width="597" alt="Screenshot of the bottom of RStudio window with shortcut bar displayed" src="https://github.com/rstudio/rstudio/assets/10569626/00e424ea-0535-42ed-b8d6-c26af61fd4a4">

If another application has taken over the shortcut, then nothing will happen in this bar when you type it.

When you're done, close the bar via the [x] at the end of the bar.

**Comment by gtritchie** [comment]
Ah, just noticed you wrote:

> it doesn't accept Cmd+Shit+M as an input, i.e., when I delete Ctrl+Shift+M and press the combination I want (Cmd+Shift+M), nothing happens.

That strongly suggests something else has registered a global shortcut handler so the keystroke isn't being seen by RStudio at all. This can be a tricky thing to track down. Did you recently install any new applications / utilities?

**Comment by gtritchie** [comment]
One thing to try is closing all running applications (other than RStudio) and any utilities with icons in the status area (the right-hand side of the menubar), then see if the shortcut starts working in RStudio. Then start things back up one at a time and that might tell you which one is grabbing this key.

**Comment by singing-scientist** [comment]
@gtritchie — you're a genius. I followed the steps you suggested, and it was **WEBEX** (Cisco Webex Meetings)! As soon as I quit that application the shortcut worked again. Thank you so, so much!
