### ISSUE TITLE
Wrong highlighting of comments in nested YAML code

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#14323]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.12.1.402
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

Explore YAML code in Quarto document:

```markdown
---
title: "title "   # Comment: OK
author: author    # Comment: OK
format:           # Comment: wrong highlighting
  html:           # Comment: wrong highlighting
    toc: true     # Comment: OK
editor: visual    # Comment: OK
---
```

### Describe the problem in detail
Comments are not always highlighted as comments (see lines 4 and 5):
![image](https://github.com/rstudio/rstudio/assets/12725868/59c87d72-ccf2-4394-a78f-652487563f51)

### Describe the behavior you expected

Consistent highlighting for code comments

**Comment by GegznaV** [comment]
One more example, just this time **non-comment** is highlighted as a comment. The issue is present if **quotes** are involved, e.g. " or „

![image](https://github.com/rstudio/rstudio/assets/12725868/0938afa6-b550-4704-aea7-03177c79bd67)

```yaml
description: |                     # Comment OK
  "Some text."                     # Non-comment: wrong colors as this is not 
                                   # interpreted as a comment.
```

In the rendered document:

![image](https://github.com/rstudio/rstudio/assets/12725868/48a82cb8-2086-42aa-857f-baf597715961)

**Comment by kevinushey** [comment]
This appears to be resolved for me in the latest daily builds; @ronblum can you double-check?

**Comment by ronblum** [comment]
@kevinushey It is! I was so eager to see if this was a regression that I didn't check the latest dailies. 🙄 

Verified in
- RStudio Desktop 2024.04.0-daily+495 on MacOS 14.4
- Posit Workbench 2024.04.0-daily+478.pro12 on Ubuntu 22.04 via Chrome on MacOS 14.4
