### ISSUE TITLE
The IDE hangs when switching Git branches/tags that touch many files

### ISSUE THREAD

**Issue by krlmlr** [rstudio/rstudio#14320]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1 Build 402
    OS Version      : macOS Sonoma
    R Version       : 4.3.2

### Steps to reproduce the problem

- Open a project tracked in Git with many files
    - Example: https://github.com/duckdb/duckdb-r
- Switch to a branch/tag that touches many files in the `src` directory
    - Example: `git checkout v0.9.2-1`
    - This is my use case, I'm not sure if this problem is limited to this directory though
- Go to another directory in the "Files" pane, or try the File/New/R script command
    - The "Files" pane shows a spinning wheel, the new document is not opened

### Describe the problem in detail

It seems that the IDE is busy processing the changes to the files, and blocks until finished.

### Describe the behavior you expected

Processing of file changes happens in the background.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It looks like the issue here is that each of the changed files is triggering RStudio's C++ compilation database to be rebuilt, which is very expensive with so many changed source files. We should try and debounce this if possible.

**Comment by krlmlr** [comment]
Note that this problem also occurs if the Git pane is switched off (my default setting because it interferes heavily with `git rebase`). https://github.com/rstudio/rstudio/issues/11584 is marked as closed, I might give the Git pane another try at some point.

Another issue in this area: heavy use of `git rebase` sometimes leads to outdated editor buffers. Is this a known problem? Haven't found anything with a search for "rebase".

**Comment by kevinushey** [comment]
@krlmlr: do you still see this issue in the latest daily builds of RStudio? https://dailies.rstudio.com

**Comment by krlmlr** [comment]
Running `brew install rstudio-daily` now, will report here.

What issue should I watch out for:

- slow switch for large codebases
- Git pane interference
- outdated editor buffers

?

**Comment by krlmlr** [comment]
Switching to the daily is difficult:

```
> brew install rstudio-daily
...
==> Downloading https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg
curl: (22) The requested URL returned error: 500
Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
curl: (22) The requested URL returned error: 500
Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
curl: (22) The requested URL returned error: 500
Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
curl: (22) The requested URL returned error: 500           #

Error: Download failed on Cask 'rstudio-daily' with message: Download failed: https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg
```

**Comment by gtritchie** [comment]
> Switching to the daily is difficult:

Download the .dmg from the website, double-click to open it, then double-click RStudio in the opened image. This won't touch any existing installations you have.

Choose the most recent from here: https://dailies.rstudio.com/rstudio/chocolate-cosmos/electron/macos/

**Comment by krlmlr** [comment]
Thanks, good point. What issue should I watch out for:

- slow switch for large codebases
- Git pane interference
- outdated editor buffers

?

**Comment by gtritchie** [comment]
The fix addresses what was originally reported, so "slow switch for large codebases".

The other things mentioned would need to be opened as new issues. I'm not aware of any existing issues for them, but I didn't go looking.

Thanks!

**Comment by krlmlr** [comment]
Switch between v0.9.2-1 and v0.10.0 for the duckdb R package is instantaneous now. Thanks!

**Comment by krlmlr** [comment]
I spoke too soon. The "Files" pane reacts immediately, but I still can't save files, and the terminal freezes.

**Comment by krlmlr** [comment]
I had another RStudio release open. 🤦 

With the daily, switching between very different states of the code now only takes one second until the IDE becomes fully responsive again.

**Comment by gtritchie** [comment]
Great, thanks!
