### ISSUE TITLE
Noisy logs about Github Copilot Agent exiting

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#14328]
### System details

    RStudio Edition : Workbench
    RStudio Version : 2023.12.0
    OS Version      : N/A
    R Version       : N/A

### Steps to reproduce the problem

I saw this in a customer environment but haven't attempted to reproduce locally. Based on the log entries, here's what I believe happened:

1. Have sessions running
2. Stop or restart the Launcher

### Describe the problem in detail

```
Month Day TIME host rsession-username[pid]: ERROR [onExit]: Agent exited with status 143.; LOGGED FROM: void rstudio::session::modules::copilot::{anonymous}::agent::onExit(int) src/cpp/session/modules/SessionCopilot.cpp:780`
```

### Describe the behavior you expected

We should not log errors if this is normal operation.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Sorry, I lost the associated PR -- there was a larger change that removed this particular bit of logging though.

**Comment by ronblum** [comment]
NP! Verified with Posit Workbench 2024.04.0-daily+546.pro4 on Ubuntu 22.04.3.

```
root@ip-172-98-5-128:/var/log/rstudio# rstudio-launcher status
○ rstudio-launcher.service - RStudio Launcher
     Loaded: loaded (/lib/systemd/system/rstudio-launcher.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2024-03-08 12:28:38 UTC; 4s ago
    Process: 12788 ExecStart=/usr/lib/rstudio-server/bin/rstudio-launcher (code=exited, status=0/SUCCESS)
   Main PID: 12788 (code=exited, status=0/SUCCESS)
        CPU: 20.791s

Mar 08 12:25:36 ip-172-98-5-128 systemd[1]: Started RStudio Launcher.
Mar 08 12:28:37 ip-172-98-5-128 systemd[1]: Stopping RStudio Launcher...
Mar 08 12:28:38 ip-172-98-5-128 systemd[1]: rstudio-launcher.service: Deactivated successfully.
Mar 08 12:28:38 ip-172-98-5-128 systemd[1]: Stopped RStudio Launcher.
Mar 08 12:28:38 ip-172-98-5-128 systemd[1]: rstudio-launcher.service: Consumed 20.791s CPU time.
```
