### ISSUE TITLE
Support for editor markdown settings in global `_quarto.yml` instead of `.Rproj`

### ISSUE THREAD

**Issue by jtlandis** [rstudio/rstudio#14330]
Given you can set certain global options for Rstudio visual editor as specified [here](https://quarto.org/docs/visual-editor/options.html#global-options), I was wondering if we could get support to prefer editor specifications in `_quarto.yml`. 

This is comming from issue #14126 and learning we can specify how the visual editor parses text to md through

```qmd
---
editor:
  markdown:
    wrap: sentence
    canonical: true
---
```

however setting the above in the `_quarto.yml` file does not do anything and must instead be placed in the `.Rproj` file

```Rproj
MarkdownWrap: Sentence
MarkdownCanonical: Yes
```
I figured one reason to do this is that quarto isn't intended to be tied to Rstudio forever. Another reason is that I never strictly considered the .Rproj file something that was tracked in git, as it sometimes contains specific user preferences.

What do the maintainers think?

**Comment by jtlandis** [comment]
Also, I wasn't sure if this should have been posted in this repository or in [quarto-cli](https://github.com/quarto-dev/quarto-cli)

**Comment by ronblum** [comment]
@jtlandis Thank you for raising this!

@kevinushey I have the same question—this looks like something that would need to be handled by `quarto`? Or would it be in RStudio, or both?

**Comment by jtlandis** [comment]
I think this is probably an issue for both. I imagine having this parsing is something that needs to be implemented  in the IDE natively or as some plugin upon saving. I tend to use Rstudio IDE whenever I use quarto, so for my purposes I dont mind where this issue sits. However for the big picture, maybe this is something that should be pushed to [quarto-cli](https://github.com/quarto-dev/quarto-cli)
