### ISSUE TITLE
RStudio Desktop exits silently if started without R installed (Linux/Mac)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14343]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1+402
    OS Version      : macOS, Linux
    R Version       : none

### Steps to reproduce the problem

On Linux or Mac, without R installed, try to start RStudio desktop.

### Describe the problem in detail

App fails to start and closes without showing any UI other than the app icon briefly appearing in the dock, etc.

### Describe the behavior you expected

On Windows, we show the "Choose R" window in this scenario; we don't have that for Linux or Mac, but at a minimum, I'd expect us to show an error dialog saying an R installation could not be found.

NOTE: this isn't a regression, at least not a recent one. Still, this seems like a very bad experience for the new RStudio user who isn't aware they need to install R separately.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
This scenario is supposed to show a message box, but it's shows it asynchronously and then immediately exits before it ever appears.

https://github.com/rstudio/rstudio/blob/cf7f1df270e3ed4ce22d42c8c2fb2d00cd5b6d22/src/node/desktop/src/main/application.ts#L353

**Comment by gtritchie** [comment]
Recommend we take this for Chocolate Cosmos; should be a small fix, and goes nicely with https://github.com/rstudio/rstudio/issues/13184 which I am working on for Chocolate Cosmos.

**Comment by ronblum** [comment]
Verified using 
- RStudio Desktop 2024.04.0-daily+531 on MacOS 14.4
- RStudio Desktop 2024.04.0-daily+537 on Red Hat 9.3

Checked by
- Removing the system-level R
- Removing R installations in standard locations
- Setting `RSTUDIO_WHICH_R` to bogus values
    - Note: this has to be done as an environment variable outside of R, e.g. with `EXPORT RSTUDIO_WHICH_R=/path/to/R`
    - Can't use `.Rprofile` and `.Renviron`
