### ISSUE TITLE
No custom completion if prefixed usage of `ggplot2::geom_*()`

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14344]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.513
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

In this example, try to request completion for the label aes in each geom_label calls.
i.e. `ggplot2::geom_label()` vs `geom_label()`

```r
# no completion
library(ggplot2)
# without label aes suggestion
ggplot(mtcars, aes(x = cyl, y = mpg)) +
  ggplot2::geom_label(aes(<tab>))
  ggrepel::geom_label_repel(aes(<tab>))
# with label aes suggestion
library(ggrepel)
ggplot(mtcars, aes(x = cyl, y = mpg)) +
  geom_label(aes(<tab>)) +
  geom_text_repel(aes(<tab>))
```

### Describe the problem in detail

No autocomplete for prefixed calls.
![image](https://github.com/rstudio/rstudio/assets/52606734/ae9e576c-2a45-4bc0-b101-5301accdd677)
![image](https://github.com/rstudio/rstudio/assets/52606734/ba7fb9b7-f0be-4f98-97c1-9698f9af0c40)

### Describe the behavior you expected

@kevinushey I would expect prefixed usage of geom functions to be able to check for required aesthetics. I think that a very minor tweak to the regexp should do the trick? If it is complicated, 

Maybe change regexp to "^geom|\\:\\:geom" right here would do the trick? But would it create issue if a package is not loaded?

Probably around here  (lines changed during #14199)
https://github.com/rstudio/rstudio/blob/cf7f1df270e3ed4ce22d42c8c2fb2d00cd5b6d22/src/cpp/session/modules/SessionRCompletions.R#L1033-L1055

Would expect that prefixed and non-prefixed to work the same
Non-prefixed example:
![image](https://github.com/rstudio/rstudio/assets/52606734/37d30a91-fc9d-4e0e-bf7c-eccf62d98184)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment]
Works out of the box (RStudio 2024.04.0+544)!
 I think the new ggplot2 autocompletion features should be documented! It is pretty incredible from what I saw! Thanks you so much for all your work @kevinushey !

**Comment by kevinushey** [comment]
Thanks for testing!

We could document this, but I'm not sure what the best venue for documentation here would be -- perhaps instead we should highlight this in a blog post accompanying the upcoming RStudio release?
