### ISSUE TITLE
remove focus-visible polyfill

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14352]
All browsers we support now support focus-visible natively. We should consider removing the polyfill.

Some relevant PRs:

- addition of the polyfill: https://github.com/rstudio/rstudio/pull/5452
- script for downloading: https://github.com/rstudio/rstudio/pull/7456
- added to the sign-in page: https://github.com/rstudio/rstudio/pull/5887
- added to Satellite windows: https://github.com/rstudio/rstudio/pull/7884

A potential wrinkle is this: the option for turning off focus rectangles, even for keyboard users, uses features of the polyfill so that might require reworking (or elimination).

- https://github.com/rstudio/rstudio/pull/7351

**Comment by gtritchie** [comment]
This polyfill is now causing problems with latest versions of Chrome (see https://github.com/rstudio/rstudio/issues/15068), so moving this into Kousa Dogwood.

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 2024.10.0-daily+236 on Windows 11
- RStudio Server 024.10.0-daily+250 on Ubuntu 22.04 via Chrome and Edge on Windows 11

Checked that objects like Rmd and Qmd chunks and YAML, and buttons, are surrounded by rectangles when moving focus with <kbd>Tab</kbd>; but there are no rectangles when clicking on them. This is the same behavior as in previous releases (checked on Chocolate Cosmos and Cranberry Hibiscus), before the change, as expected.
