### ISSUE TITLE
Add support for Copilot diagnostics

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14358]
The newest release of the Copilot Agent supports generation of a Copilot diagnostic report. It would be helpful if we made this accessible from RStudio.

**Comment by ronblum** [comment]
Verified that diagnostics show up. Spot-checked some of the values, especially regarding operating system.

Tested with
- RStudio Desktop Pro 2024.04.0-daily+531.pro3 on MacOS 14.4
- Posit Workbench 2024.04.0-daily+531.pro3 on Ubuntu 22.04.3 via Chrome on MacOS 14.4
