### ISSUE TITLE
Presentation Pane buttons don't work (again) in Rstudio desktop Win

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rstudio#14362]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 2024.04.0 Build 531
    OS Version      :  Win11 (x86_64-w64-mingw32)
    R Version       :  4.4 (development

### Steps to reproduce the problem

- Run the following in the console to create a quarto presentation. 
- Save the file.
- From the source pane, change the render option in the gear icon to Preview in Viewer Pane
- Click to render the document.
- Observe the presentation tab.

### Describe the problem in detail

The same problem appears again as described in #13814 and #13711 on the latest daily build version in Win11. 

The presentation is rendered and displayed in the Presentation Pane, and the extra toolbars are present. However, the "present," "print," "edit," and "present in an external web browser" buttons don't work.

### Describe the behavior you expected

The buttons should work (and they did in the rstudio of my linux system.)

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sammo3182 Thank you for raising the issue! Is this a problem in R 4.3 or earlier?

QA Note: This is working in RStudio Desktop 2024.04.0-daily+531 with R 4.3.2. Try on Windows.

**Comment by sammo3182** [comment]
> @sammo3182 Thank you for raising the issue! Is this a problem in R 4.3 or earlier?
> 
> QA Note: This is working in RStudio Desktop 2024.04.0-daily+531 with R 4.3.2. Try on Windows.

So, it is a problem relating with R? 😱I'll try with a stable version of R then. Thanks!

**Comment by ronblum** [comment]
@sammo3182 I don't know if the version of R makes a difference, but it would be great if you can try a stable version to rule it out or learn that it's causing the problem. (The QA note was for me to remember to try Windows and see if the operating system is the cause.)

**Comment by ronblum** [comment]
I can't reproduce the problem on Windows 11 either, using both R 4.3.1 and 4.4 devel with build 2024.04.0-daily+534. @sammo3182 Can you provide the log files so that we can see if there's any useful logging info?
