### ISSUE TITLE
single line functions not indexed in Document Outline

### ISSUE THREAD

**Issue by LiNk-NY** [rstudio/rstudio#14365]
### System details

   "Ocean Storm" Release (\4da58325, 2024-01-29) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
    OS Version      :  Ubuntu 22.04.4 LTS
    R Version       :  R-devel 4.4.0 (r85541)

### Steps to reproduce the problem

Consider the following `test.R` file:

```r
with_braces <- function(x) {
  if (is.character(x)) {
    x <- paste0("{", x, "}")
  }
  x
}

without_braces <- function(x)
    gsub("\\{(.*)\\}", "\\1", x)
```

### Describe the problem in detail

The `Document Outline` pane does not register the `without_braces` function because it does not have enclosing curly braces. It only indexes the `with_braces` function (screenshot below). 

![image](https://github.com/rstudio/rstudio/assets/4392950/adf7de93-cdcf-4838-a7d1-0b4489b44d96)

### Describe the behavior you expected

I expect both functions to show up in the `Document Outline` panel. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@LiNk-NY Thank you for raising this! Reproducible in RStudio Desktop 2022.07.2+576 and 2024.04.0-daily+531 on MacOS 14.4. Note: Items appear or disappear from document outline as soon as an opening brace is added or removed.

**Comment by kevinushey** [comment]
Relevant code: https://github.com/rstudio/rstudio/blob/440e7fcd5da76c497f612888b30b5a08f471c677/src/gwt/acesupport/acemode/r_code_model.js#L1099-L1104

We specifically only create scopes for functions with braces, as it's much easier to compute the function's bounds in that case (just look for that matching `}`).
