### ISSUE TITLE
rstudio terminal fails to retrieve current directory when a quarto project is open 

### ISSUE THREAD

**Issue by kundeng** [rstudio/rstudio#14361]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.12.1+402 (2023.12.1+402)
    OS Version      :  Ventura Mac 
    R Version       : 4.3.2

### Steps to reproduce the problem
It seems that when I unload a quarto project, the terminal works again. But when a quarto project such as a website project is open, the terminal (not the console) can't load current directory. 

I tried all the things below without success. 
* Added /bin/sh to full disk access
* Add rstudio to full disk access. 
* close and reopen project. 

### Describe the problem in detail
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Undefined error: 0
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Bad file descriptor
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Invalid argument
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Undefined error: 0
```
### Describe the behavior you expected
See either the home directory,current directory or project directory; 
Tried all three options, neither worked. 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kundeng Thank you for raising this! Does this also occur with Zsh and Bash?

**Comment by kundeng** [comment]
I have bash.
