### ISSUE TITLE
Weird characters on Help Pane

### ISSUE THREAD

**Issue by bounlu** [rstudio/rstudio#14369]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.12.1
    OS Version      : Ubuntu 22.04
    R Version       : 4.3.3

### Steps to reproduce the problem
`?filter`

### Describe the problem in detail

Help page displays weird character encoding for certain documentation, but not all. For ex:

<img width="492" alt="RStudio_Server_bug" src="https://github.com/rstudio/rstudio/assets/17899927/45bf8ef9-a7a1-4ff8-b4c2-2b6298a77739">

### Describe the behavior you expected

Readable UTF-8 caharacter encoding is expected.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bounlu Thank you for raising the issue! I'm unable to reproduce it though. Are there other help topic besides `filter` that cause this problem, so that I can try them out? Also, is this a new issue in version 2023.12.1, or did it occur in previous versions?

**Comment by bounlu** [comment]
It happens only for those functions with conflict from multiple packages, another example is `?lag` after loading `tidyverse`.
I don't have this problem on my Desktop RStudio with the same version running on Mac, also didn't have this problem in previous versions on the server.
