### ISSUE TITLE
Restore Sumatra as default PDF Viewer in RStudio for RMarkdown PDF Knitting

### ISSUE THREAD

**Issue by jfsalzmann** [rstudio/rstudio#14370]
I understand I'm late to the party as I have not updated RStudio for a long time. Now I realise that Sumatra PDF viewer is not part of the current RStudio setup anymore for viewing PDFs generated from RMarkdown knitting. I found that people talked about it [here](https://community.rstudio.com/t/sumatra-as-viewer-option-is-not-available-in-rstudio-2022-12-0-build-353/155639) and [there](https://community.rstudio.com/t/pdf-not-displayed-after-knitting-a-rmd-file/17548) but haven't seen any solution. Indeed I understood that by default, RStudio wouldn't open the PDFs at all, which irritates me a lot.

So,

- I want to continue viewing RMarkdown knitted PDFs in Sumatra
- immediatly & automatically opened after rendering
- without changing my system default PDF reader (I need that to be Acrobat)

Actually, I wouldn't mind it to be another PDF viewer, however, I really loved the features of Sumatra:

- not requiring to close files before re-rendering
- displaying changes in real-time when rendering
- multiple tabs possible when working on multiple RMarkdown files

As far as I see, the RStudio viewer cannot offer this behavior (no real-time view), and neither can Acrobat (would have to close file before re-rendering).

I.e., I would like to see an option in the RStudio preferences other than just choosing between System Viewer and RStudio Viewer. Being able to set a specific PDF viewer (that allows for real-time viewing without blocking files) would be great solution.

How have people adapted? This can't be just me.

(Or is this merely a sign of people using Sweave instead? Haven't tried it, but understood it allows for some synctex stuff...)

_I [asked](https://community.rstudio.com/t/restore-sumatra-as-default-pdf-viewer-in-rstudio-for-rmarkdown-pdf-knitting/182720) in the RStudio community first and was sent here._

**Comment by ronblum** [comment]
@jfsalzmann Thank you for filing the issue here! We'll review this as we continue development of RStudio. Also, I'm glad that you posted in Community, and I hope that other users provide info for your questions at the end, about how other people have adapted.

**Comment by jthomasmock** [comment]
We did not bring over Sumatra when we switched our desktop framework from Qt to Electron. Thank you for posting - we are going to wait for other users to add on or upvote this issue as we continue to prioritize issues across the IDE.

**Comment by gtritchie** [comment]
Related issues:

- [Electron desktop not giving Sumatra PDF viewer option on Windows #11345](https://github.com/rstudio/rstudio/issues/11345)
- [Implement SyncTex for Electron #11415](https://github.com/rstudio/rstudio/issues/11415)

**Comment by jfsalzmann** [comment]
Thanks for clarifying, @jthomasmock. I would be happy to see at least an option for a custom PDF viewer different from the system default. Would that be difficult to add?

Thanks for linking, @gtritchie.

**Comment by bhafar** [comment]
I'm have the same situation. I upgraded RStudio after using an older version for quite some time only to find my PDFs no longer open with Sumatra. I would very much like to see this feature back as the default behavior for knitting PDFs. For now I'll just stick to the older RStudio version.

**Comment by Minh-AnhHuynh** [comment]
The alternative is to select no viewer option and open the pdf manually, however I would still like for the functionality to be restored as it was before.
