### ISSUE TITLE
More intelligent git pane layout resizing

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14371]
I guesss this is minor since the workaround is just to resize the panel.

but when the right panel is narrow, the "Commit" button is not shown.

Maybe reducing whitespace in the commit message box would be desirable?

![image](https://github.com/rstudio/rstudio/assets/52606734/5930dafb-0f03-4f7b-a793-d0b088245a08)

Feel free to close :)

**Comment by kevinushey** [comment]
It looks like the behavior here might be OS / browser dependent. Here's what I see in RStudio Desktop on macOS with the latest release:

<img width="357" alt="Screenshot 2024-03-05 at 9 39 31 AM" src="https://github.com/rstudio/rstudio/assets/1976582/320b34ff-147e-48ea-ac42-95c76119550e">

Can you provide other details on where you're seeing this?

**Comment by olivroy** [comment]
[Enregistrement-20240305_124523.webm](https://github.com/rstudio/rstudio/assets/52606734/438c68d7-599c-4c5a-8cbd-cc4d953f23db)

It may not be worth doing this after all. If the window is too much reduced, it will create ugly overflow..
