### ISSUE TITLE
Enable incremental copilot suggestions out-of-the-box

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#14395]
Following-on from #13522, I'd like to suggest a feature request that will be important/essential for many people.

Context: Co-pilot and other auto-complete services are now commonplace in programming. However, the most effective use of these services is **not** to blindly accept suggestions but to keep a 'tight leash' on the generative text by **only accepting the bits that make sense (much generative text will not)**.

There is acknowledgement of this need in responses to the issue linked above. However, to my surprise, when I tried testing the fix today I realised that the suggested solution (Ctrl+Right arrow, same as in VS Code) **does not work out of the box**: you have to go to a hard-to-read web page, read about modifying shortcuts, and then manually edit the default settings.

This will be prohibitive for many people, including myself, because I use RStudio on different devices, teach RStudio (so it's important the behaviour on my device matches what students see), and because I think it will benefit many people by addressing the issue upstream.

Two quick wins come to mind:

- [ ] Overwrite the previous meaning of the Ctrl+Right arrow shortcut when you click on "Enable co-pilot" (recommended)
- [ ] Change the shortcut to a combination not reserved for anything else

**Comment by ronblum** [comment]
Checked with
- RStudio Desktop 2024.04.0-daily+558 on MacOS 14.4
- RStudio Desktop Pro 2024.04.0-daily+555.pro3 on Red Hat 9.3
- Posit Workbench 2024.04.0-daily+555.pro3 on Ubuntu 22.04 via Chrome on MacOS 14.4

This partly works, but there are a few issues.

1. Works correctly with text.
2. Gets somewhat confused with code. See video.
3. <kbd>Ctrl-RightArrow</kbd> doesn't work by default—I had to map it first.

https://github.com/rstudio/rstudio/assets/31009952/b0ed6fdd-fb14-4ce3-b4a5-f23fb8910fbb


Note: On MacOS, first uncheck or change the Mission Control keyboard shortcut at <kbd>System Settings -> Keyboard -> Keyboard Shortcuts -> Mission Control -> Mission Control -> Move right a space</kbd>

![Image](https://github.com/rstudio/rstudio/assets/31009952/4bbfbadb-fde5-4a4f-886a-4dcb6392755b)

**Comment by kevinushey** [comment]
@ronblum the PR implementing this change isn't available in build 558; can you please try again once a newer build is available?

**Comment by ronblum** [comment]
Oops! I looked at the PR creation date, not the merge date. I'll retest.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+573 on MacOS 14.4. All works correctly now, with one exception: Sometimes, after reaching `$` or `"` and possibly other characters when naming objects and accepting them, clicks subsequent to the characters will disappear, then reappear with the next acceptance.

https://github.com/rstudio/rstudio/assets/31009952/6d1f6f58-91be-494b-9ab0-7cb56914b50c

**Comment by Robinlovelace** [comment]
This is great to see, thank you!

**Comment by kevinushey** [comment]
@ronblum thanks! Could you file that "ghost text sometimes disappears after inserting a word" issue as a separate issue?

**Comment by Robinlovelace** [comment]
Ready to test on dailies? And when will a stable (default upgrade) version be released? This is really fantastic, giving best of RStudio + CoPilot autocompltion.

**Comment by kevinushey** [comment]
Indeed, ready for testing with the daily builds at https://dailies.rstudio.com.

We're currently aiming for a general release in April, so coming soon!
