### ISSUE TITLE
Environment assignment problem when using `base:::Sys.setenv` for `RSTUDIO_WINUTILS`

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#14396]
In latest daily on windows I am seeing this error at startup 

````
Erreur dans base:::Sys.setenv("C:/Users/chris/scoop/apps/rstudio-daily/current/resources/app/bin/winutils") : 
  tous les arguments doivent être nommés
````

I believe this comes from 
https://github.com/rstudio/rstudio/blob/2f0657a9116d4a9bad61c442774d2dbb657c939e/src/cpp/session/modules/connections/SessionConnections.cpp#L510-L521

and follows very recent change at 25f7cfaf9e5a922890bf08b61fe8007c3edf983e (PR #14385 - cc @kevinushey)

It seems the call to the R function is missing the name of the environment variables `RSTUDIO_WINUTILS`

Hope this helps 

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.550
    OS Version      : Windows 11 x64 (build 22631)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

**Comment by kevinushey** [comment]
Thanks for catching that -- should be fixed up in the next daily builds.
