### ISSUE TITLE
'Reformat Code' option cannot handle negative signs when listing comma-separated entries

### ISSUE THREAD

**Issue by a-s-russo** [rstudio/rstudio#14402]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.6.1.524
    OS Version      : Windows 11 Home (version 23H2)
    R Version       : 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

Define the following function in a new R script in RStudio in the Source pane:

`myfunction <- function() {
  return(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, -10000))
}`

### Describe the problem in detail

In the RStudio Source pane, select all lines (Ctrl+A, or select Edit --> Select All from the menu bar), and then reformat the code (Ctrl+Shift+A, or select Code --> Reformat Code from the menu bar).

Repeatedly reformat the code and observe that the vector with the negative entry (namely, -10000) repeatedly overwrites or inserts the space between it and the previous vector entry.

That is, the 'Reformat Code' option seemingly erroneously toggles indefinitely between inserting and removing a white space when negative signs are involved. The same issue can be observed in other contexts; for example: `select(-Myvar)`.

### Describe the behavior you expected

I expect the 'Reformat Code' option to consistently insert a space before a negative sign when writing a comma-separated list in source code (such as in vector entries or function arguments), and not to toggle back and forth as though it cannot decide whether to remove or insert the space.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@a-s-russo Thank you for raising this! I can reproduce this in earlier versions of RStudio Desktop, and this works correctly in version 2024.04.0-daily+550.
