### ISSUE TITLE
R packages cannot be installed

### ISSUE THREAD

**Issue by kelli-rstudio** [rstudio/rstudio#14404]
### System details

    RStudio Edition : Server and Workbench
    RStudio Version : 2024.04.0-daily-557, 2024.04.0-daily-546.pro4, 2024.04.0-daily-555.pro3
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem
Two issues with package installation (but probably the same cause):

**Issue 1 - reinstalling an previously installed package**
1. Create an RStudio Session and install a package that is already installed (eg. `install.packages("rmarkdown")`). 
2. See error appear in console and dialog box appear.
3. Click yes on the dialog box and see that the console error appears again and the dialog box does not go away

![image](https://github.com/rstudio/rstudio-pro/assets/114421526/21497bd3-3e63-44bf-979d-0ae7ee512582)

**Issue 2 - installing a new package**
1. Create an RStudio Session and try installing a package that is not already installed (eg. `install.packages("tidymodels")`)
2. See that package doesn't install and see that error appears in console 
<img width="1513" alt="image" src="https://github.com/rstudio/rstudio-pro/assets/114421526/6e2faac6-3062-4747-9355-ddf4a8e6bb7b">

### Describe the problem in detail
Unable to install packages.

### Describe the behavior you expected
Should be able to install packages.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
I can also reproduce the issue with a new package (`tidymodels` in the example) in RStudio Desktop 2024.04.0-daily+558.

@kelli-rstudio For the first issue, for an existing, loaded package (`rmarkdown` example), is the same as the existing behavior in #2656 ?

**Comment by kelli-rstudio** [comment]
@ronblum yeah the first issue looks like it's the same as https://github.com/rstudio/rstudio/issues/2656

**Comment by kelli-rstudio** [comment]
### Verified Fixed
    RStudio Edition    :  Server
    RStudio Version(s) : 2024.04.0-daily+573
    OS Version         : ubuntu20

### Test scenario(s) 

Verified that new packages can be installed and that already installed packages can be reinstalled without the infinite loop. Also checked that the previously observed test failures were resolved in the most recent opensource automation run.

### Automated tests 

We have existing automation.
