### ISSUE TITLE
Grammar check in French

### ISSUE THREAD

**Issue by SkelAlex** [rstudio/rstudio#14401]
Dear Posit,

I was wondering if you had any plans to develop an integrated grammar check into RStudio, and more particularly one that allows for French language support. Some colleagues and I are currently writing a book chapter about the use of markup languages for French speakers, and this is the main issue we are noticing when using markup languages in RStudio – as opposed to VS Code or Overleaf, which both provide a LanguageTool integration. We are finding it difficult to write quality texts using LaTeX and Quarto with only a spell check and often need to rely on Word, Overleaf or VS Code for grammar check. We are aware of the Grammarly Desktop extension, but it does not integrate well into RStudio, and Grammarly is only available in English. We are big fans of RStudio while using R, so being able to grammar-check our French-language texts in RStudio would be massively appreciated on our end.

**Comment by rfsaldanha** [comment]
Hi! I am missing a lot this feature too, and started to work in an add-in for RStudio. It is not integrated as native feature, but checks the lines of a notebook using the LanguageTools API.

Take a look here: https://github.com/rfsaldanha/rstudiogrammar

Basically, install it with `remotes::install_github("rfsaldanha/rstudiogrammar")` and run the command `rstudiogrammar::check_document(language = "FR")` 

There is a lot to yet, but is a possibility...

**Comment by ronblum** [comment]
@SkelAlex Confirmed that there are no plans to build this, and that the add-in approach is the best way to do this.

@rfsaldanha I tried the add-in out—pretty cool! I won't get into any feedback regarding coding; I'll leave that to people who know what they're talking about. 😄 But I tried this out in English (my French is subpar). I have a couple of observations that you're probably aware of, but just in case:
1. Only some errors are picked up. But I put in a very badly-worded sentence, and it wasn't flagged: `This sentence very grammarishine and very also badly yooo knowe very.`
2. YAML and chunk code is being evaluated, e.g. it wanted to turn `plot(cars)` to `Plot(cars)`.
3. The prompt
    `Do you want make this X modification on line X?`
    is missing `to` and should be
    `Do you want make this X modification on line X?`

**Comment by rfsaldanha** [comment]
Thank you! Made some modifications to check only the selected text, with `check_selection`.

**Comment by SkelAlex** [comment]
Great add-in @rfsaldanha, and thanks for the answer @ronblum! I was thinking of something that would be integrated directly into the RStudio UI, similar to what Grammarly does in English. An external app would also work if it integrates well with the RStudio UI. I am not sure how feasible it would be to implement such a feature for Francophone users?

**Comment by rfsaldanha** [comment]
I agree with you, something more integrated like Grammarly or LanguageTools (with several languages support) will be better. The add-in is more like a temporary solution.

**Comment by rfsaldanha** [comment]
and changed de package name ;-)

https://github.com/rfsaldanha/rspell

`remotes::install_github("rfsaldanha/rspell")`

Select some text...

`rspell::check_selection()`
`rspell::check_selection(language = "FR")`

**Comment by rfsaldanha** [comment]
I improved the package's readme with more details about how to use it, and created a pkgdown website for it.

https://rfsaldanha.github.io/rspell/
