### ISSUE TITLE
Avoid opening code browser when debugging code with inferred file position

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14417]
To reproduce, create an R document with the contents:

```
foo <- function(x) {
  browser()
  1 + 1
  2 + 2
  3 + 3
  4 + 4
}
```

Then, execute the code with Cmd + Enter, and then run `foo()`. While the debugger is active, make a modification to the `foo()` function, and then save the file. Now try stepping through with `n` in the console.

A separate code browser is opened, as the function definition in the source file has diverged from the one currently being run. Instead of opening the code browser, we should continue debugging in the original source file, with a warning displayed and no debug highlight shown.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+657 on MacOS 14.4.

There appears to be an issue on Windows with the debugger in general showing the source and displaying the tracebacks, but I'll file that separately.

**Comment by ronblum** [comment]
One thing: When the source is changed and saved in the middle of the walkthrough, we should include a warning message.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+668 on Windows 11.



![Image](https://github.com/rstudio/rstudio/assets/31009952/b8f7dc6f-5c39-46bf-973a-6e5c99832692)
