### ISSUE TITLE
Tools / Global options.../ Code / Editing menu is incorrectly displayed. Snippets menu hardly accessible

### ISSUE THREAD

**Issue by vertesy** [rstudio/rstudio#14411]
## System details

<img width="624" alt="image" src="https://github.com/rstudio/rstudio/assets/5101911/ca7aceb6-68da-4d57-be47-06ffd7827a32">

### Steps to reproduce the problem
Click on ``Tools / Global options.../ Code / Editing `

## Describe the problem in detail: Menu inaccessible / Incorrectly displayed on remote version
`Tools / Global options.../ Code / Editing / Snippets` is not displayed, the `Editing` menu is not scroll-able, so the only way to edit snippets is to click on a visible menu and then keep pressing tab - this way you can force it to "scroll".

<img width="625" alt="image" src="https://github.com/rstudio/rstudio/assets/5101911/523ef9c4-ed62-4e5d-8e57-61a319bde94a">

## Describe the behavior you expected: Correctly displayed on local version

![image](https://github.com/rstudio/rstudio/assets/5101911/926e9414-f6ac-4f4f-b814-9510836d053b)

![image](https://github.com/rstudio/rstudio/assets/5101911/96420307-bb50-45fd-8026-b6eecbcec415)

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@vertesy Thank you for raising this! Is there no scrollbar on the right edge of the window?

<img width="496" alt="snippet" src="https://github.com/rstudio/rstudio/assets/31009952/f98b3468-8888-4b3b-be61-5575bc4e478e">

**Comment by vertesy** [comment]
No, scroll bar is not available / visible in either. 
On mac (local) the window is simply big enough to fit all (true for all settings winows, just checked).
Monitors are the same.

**Comment by ronblum** [comment]
The window being a little to long is known, but there should be a scrollbar. @kevinushey Do you have any suggestions of where to look for more info?

**Comment by kevinushey** [comment]
Not off the top of my head, but given that the issue apparently occurs with CentOS 7 (a platform we plan to drop support for soon) I'm inclined to mark this as won't-fix unless we confirm the issue affects other platforms.

Does the issue occur with other RedHat Linux installations when using Firefox?

**Comment by ronblum** [comment]
Not of CentOS, since they converted to CentOS stream. We do continue to support Red Hat. RHEL 7 will drop out of support soon, but we will continue to support versions 8 and 9.

**Comment by vertesy** [comment]
Okay, thanks, clear, wont fix, makes sense.
