### ISSUE TITLE
adapt to R context changes for R 4.4

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14427]
Ref: https://github.com/wch/r-source/commit/be69b7c24664a88679c3f76c2900065eefd28079

This will likely be required to ensure RStudio is compatible with the R 4.4.x release.

**Comment by kevinushey** [comment]
Note: might not require any action since the changes occur in the latter parts of the struct, which we don't normally try to access or use.

**Comment by kevinushey** [comment]
More context changes incoming, this time ones that definitely need to be handled by us: https://github.com/wch/r-source/commit/6a8eb2cfc6eff526d38c1de7428db4de704e2909

**Comment by kevinushey** [comment]
Leaving tis open to monitor for further context changes.

**Comment by kevinushey** [comment]
https://github.com/wch/r-source/commit/8d55e9a98d7cbe9c4a904ce57e9bc40ddbe8c33b

**Comment by ronblum** [comment]
Note for testing: R 4.4.0 is now in beta, so Windows version is at https://cran.r-project.org/bin/windows/base/rtest.html .

**Comment by ronblum** [comment]
Tried out some debugging a per the QA notes, with no issues. Verified in RStudio Desktop 2024.04.0-daily+693 on Windows 11.

**Comment by ronblum** [comment]
Reopening to track validation on the GA version of R 4.4.0, testing was done with development builds and release candidates.

**Comment by kevinushey** [comment]
Also confirming that no changes have occurred in the relevant R structs here: https://github.com/wch/r-source/blob/R-4-4-branch/src/include/Defn.h

So we should be in good shape.

**Comment by ronblum** [comment]
Verified that RStudio Desktop runs with R 4.4.0. Tested on:
- MacOS 14 Intel
- MacOS 14 ARM
- RHEL 9
- SLES 15 SP5
- Ubuntu 22.04
- Windows 11
