### ISSUE TITLE
Cursor shifts to console after restart of R from source pane

### ISSUE THREAD

**Issue by LDalby** [rstudio/rstudio#14425]
When standing in the a source pane and using cmd+shift+0 to restart R, the cursor goes to the console after the restart.
I would really appreciate if the cursor stayed in source pane, if this is where the focus was when the shortcut was activated.
Is this possible?

### System details
    RStudio Edition : Desktop
    RStudio Version :  2023.12.1+402 (2023.12.1+402)
    OS Version      :  macOS 14.3.1 (23D60)
    R Version       :  4.3.2

### Steps to reproduce the problem
With the cursor in the source pane, hit the keyboard shortcut to restart R.

### Describe the problem in detail
Focus shifts to the console although restart was initiated from the source pane.

### Describe the behavior you expected
Cursor stayed where it was when restart of R was initiated.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@LDalby Thank you for bringing this up! I can confirm that this is also the behavior in RStudio Desktop 2022.07.2+576 and 2024.04.0-daily+573 on MacOS 14.4, so this is an old issue that persists.

Note: This happens from anywhere, such as the search boxes in the History and Help Panes.
