### ISSUE TITLE
Can't open external links from popped out help pane.

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14435]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.558
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

1. View a topic that contains an external link. e.g.` ?usethis::create_github_token`
2. Open the help pane in pop out view (view in new window)
3. Click on an external link

### Describe the problem in detail

![image](https://github.com/rstudio/rstudio/assets/52606734/e21dc300-94a8-4e47-906f-9c5472297552)

Nothing happens when clicking on an external link. (Clicking on another help topic works, but no tooltip is shown)

### Describe the behavior you expected

I would expect external links to open in browser, like it would in normal help pane

**Comment by ronblum** [comment]
Thanks @olivroy! I can reproduce this in RStudio Desktop 2024.04.0-daily+573 on MacOS 14.4.

Comparison points: It works correctly with
- Using the Help Pane in RStudio Server 2024.04.0-daily+573 (which opens a web browser)
- Rendering an R Markdown or Quarto document with "Preview in Window"
- Popping out the viewer pane (which opens a web browser)

**Comment by ronblum** [comment]
This last worked correctly in RStudio Desktop 2022.12, and the failure starts with 2023.03.

**Comment by kevinushey** [comment]
This is because our `allowNavigation` checks disallow this:

```
2024-03-15T20:04:53.756Z DEBUG allowNavigation checking https://usethis.r-lib.org/articles/articles/git-credentials.html
2024-03-15T20:04:53.756Z DEBUG allowNavigation: external navigation within IDE is not allowed and URL host is unsafe. URL must be explicitly opened in the browser.
```

https://github.com/rstudio/rstudio/blob/5ab02aa9f44de8123323825cd3ef6d9eca2f68e0/src/node/desktop/src/main/desktop-browser-window.ts#L302-L382

Do we need to set `allowExternalNavigate` for the windows opened to view help topics?

https://github.com/rstudio/rstudio/blob/5ab02aa9f44de8123323825cd3ef6d9eca2f68e0/src/node/desktop/src/main/desktop-browser-window.ts#L366

**Comment by olivroy** [comment]
> This is because our allowNavigation checks disallow this:

Makes sense for safety.

In that case, implementing something like https://github.com/rstudio/rstudio/issues/12135#issuecomment-1999659393 makes a lot of sense before allowing opening external link from popped out help pane. although I think the behavior should be consistent in popped out vs regular help. Perhaps not a high priority.

**Comment by kevinushey** [comment]
The issue doesn't occur for links in the regular Help pane, as we get to modify `<a>` links to explicitly use `target="_blank"`. This happens here:

https://github.com/rstudio/rstudio/blob/e8a4add6ac9ec448a80638d5a300fbdd77c603da/src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java#L517-L519

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+215 on Ubuntu 24.04 and 2024.07.0-daily+219 on Windows. Checked with a couple of packages (`usethis` as above and `dplyr`) as well as the links on the main page.
