### ISSUE TITLE
Add a tooltip for external links in help pane

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14431]
When hovering over external links in the help pane, you can click on them and navigate there.

See 

```r
?usethis::create_github_token
```

and look in the file pane.

When hovering over the link in the first sentence, there is no tooltip
![image](https://github.com/rstudio/rstudio/assets/52606734/3c9b2d53-5f4a-45b9-b6cc-7cb6dbc2434a)

It may be safer to show a tooltip.

Similar to if you ran this in the console, a tooltip shows when hovering
cli::cli_text("{.href [link](https://sketchy-website.com)}")

![image](https://github.com/rstudio/rstudio/assets/52606734/629cb2bf-e15b-42ac-af41-68ad5c340179)

Also, if you pop out the help pane and try to click on an external link, it doesn't open.

![image](https://github.com/rstudio/rstudio/assets/52606734/e21dc300-94a8-4e47-906f-9c5472297552)

**Comment by ronblum** [comment]
Thanks @olivroy! Enhance request #12135 seems to be related.

Regarding the bug: Can you open a separate request for it?

**Comment by olivroy** [comment]
I added to #12135 and opened #14435. Thanks
