### ISSUE TITLE
Formula shown as unknown in environment pane

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#14446]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0-daily+397 
    OS Version      : Windows
    R Version       : 4.3.3

### Steps to reproduce the problem

Create a variable containing a formula by typing the following in the console:
```r
a <- formula(~1)
```

### Describe the problem in detail

Check the variable just created in the environment pane. It will show a value of 'unknown'.

### Describe the behavior you expected

The formula displayed, as text.    
I'm not sure if this is a problem that popped up in the last version of RStudio. I just happened to have a quite complex formula built by concatenating several strings that I wanted to check to see if everything looked ok. The content of the variable itself is fine, it is just not displayed correctly.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@BartJanvanRossum Thank you for raising this! I can also reproduce this as far back as RStudio Desktop 2022.12.0+353 on MacOS 14.4. It last worked in version 2023.03.2+454.

**Comment by kevinushey** [comment]
Looks like a regression from https://github.com/rstudio/rstudio/commit/3067bb8363f2571faf5046073080cae073fe8bc1, but should be a quick fix.

**Comment by gtritchie** [comment]
Verify that it reproduces in 2023.12.1+402 "Ocean Storm" Release.

Works correct in 2024.04.0-hourly+624.
