### ISSUE TITLE
Choose R dialog from global options not showing when R was installed in non-standard location

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14456]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0-daily+624
    OS Version      :  Windows
    R Version       : Any

### Steps to reproduce the problem

NOTE: this is a case I missed when I fixed https://github.com/rstudio/rstudio/issues/14180  via https://github.com/rstudio/rstudio/pull/14197.

- Install R on a Windows machine with no other R installation and no previous RStudio settings, with following options:
  - Choose a custom install location that RStudio doesn't know about (e.g. I used `C:\opt\R`)
  - Don't create shortcuts, and don't let it register itself in the registry or be the default program for R files
- Start RStudio, the Choose R Installation dialog will appear with no versions listed

<img width="329" alt="image" src="https://github.com/rstudio/rstudio/assets/10569626/ba1c1275-545a-4e69-a42c-fb486c3719d3">

- Click Browse, and select the path where you installed (in my case I selected `C:\opt\R\R-4.3.3\bin\x64\R.exe`)
- RStudio starts
- Tools / Global Options, then click on "Change..." to try and change R version

### Describe the problem in detail

- nothing happens

### Describe the behavior you expected

- the "Choose R Installation" dialog should be shown, so you can browse to another custom R location, etc.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+672 on Windows 11, both when RStudio is from the installer-less zip file and the installation executable.
