### ISSUE TITLE
Stopping before finishing code chunks in Quarto when later chunk contains `|> _[]` pipe and placeholder

### ISSUE THREAD

**Issue by andrewbaxter439** [rstudio/rstudio#14463]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-28) for windows
    OS Version      :  Windows 10.0.19044
    R Version       :  4.3.2

### Steps to reproduce the problem

In a .qmd file with the following contents:

     ```{r}
    message("chunk 1")
    Sys.sleep(1)
    message("finished chunk 1")
    ```
    
    ```{r}
    message("chunk 2")
    ```
    
    ```{r}
    list() |> 
      _[]
    ```

Click 'Run current chunk' on chunk 1 or 'Run all chunks above' on chunks 2 or 3. Run them again.

### Describe the problem in detail

Clicking 'Run current chunk' on chunk 1 or 'Run all chunks above' on chunks 2 or 3 often executes lines only in chunk 1 up to the `Sys.sleep()` call:

![image](https://github.com/rstudio/rstudio/assets/45594850/70bc964f-febc-49c2-886c-212fe9fc3fc3)

This occurs only when:
- Executing a Quarto document
- In RStudio
- Piping an object using `|> _[]` syntax (although note that this isn't even running in the above example)
- An above chunk has a small delay in completing (simulated using `Sys.sleep()` here, also experienced when sourcing other files)

### Describe the behavior you expected

'Run current chunk' should output message "finished chunk 1". Running all chunks above chunk 2 and 3 should respectively produce the "finished chunk 1" and the "chunk 2" message.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@andrewbaxter439 Thanks you for raising the issue! I'm unable to reproduce it, using RStudio DEsktop 2024.04.0-daily+641 on Windows 11. I'll try with an earlier release. In the meantime is there a difference if you show chunk output inline instead of sending to console?

**Comment by andrewbaxter439** [comment]
Thanks for looking into this - it does seem quite niche. A colleague replicated it on another computer (Windows 10) and across two 2023-versions of RStudio.

In inline mode it successfully runs all chunks on first try then on subsequent 'run current'/'run above' calls it stops at the sleep (or other delaying) call.

![image](https://github.com/rstudio/rstudio/assets/45594850/a8d287b9-ec2a-4e2e-8ed8-742d86bd1678)

Selecting 'Run all' from menu does seem to work consistently though.

**Comment by andrewbaxter439** [comment]
As a gif to see in action:

![rstudio](https://github.com/rstudio/rstudio/assets/45594850/531bd13b-78e3-48f8-9c23-a8a616c7d8fe)

**Comment by kevinushey** [comment]
I have a suspicion that this might occur if R diagnostics happens to run at the same time as the chunk is running while in `Sys.sleep()`... does the error still occur if R diagnostics are disabled? (disable the [ ] Show diagnostics for R checkbox here)

<img width="647" alt="Screenshot 2024-03-22 at 1 38 23 PM" src="https://github.com/rstudio/rstudio/assets/1976582/e7da0c3e-a15d-44cb-a5d0-a8108d3b45a6">

**Comment by andrewbaxter439** [comment]
Yup working perfectly with the checkbox unchecked!

I also noted one extra things that needs to occur (which might be related) - qmd file needs saved with a name before running chunks to show this behaviour.

**Comment by ronblum** [comment]
This was also failing in RStudio Desktop 2024.04.2+764. However, it's working correctly in the new release, version 2024.09.0+375. @andrewbaxter439 would you be willing to try it out? You can use the installerless zip file if you're not ready to upgrade.

**Comment by andrewbaxter439** [comment]
All seems to be working perfectly now in RStudio 2024.09.0+375! Thanks for this!

**Comment by kevinushey** [comment]
Great news -- thanks for reporting back!
