### ISSUE TITLE
Fix performance problem with rapid writes to RStudio's console history database

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#14466]
Each console output line adds a line to the history database. This happens synchronously, adding a line to a file on the file system and there's no batching. The per op overhead is pronounced on replicated file systems that wait for a write to be committed, before allowing a rapid second write to the same file. 

### Steps to reproduce the problem

Run a benchmark that generates lots of console history output - i.e. 10s to 100s of entries per second

Use strace to trace open/writes to the history database file.

### Describe the problem in detail

[This code](https://github.com/rstudio/rstudio/blob/40bec6017bdedfcec2960a6f0e7fcd9eb39d480d/src/cpp/session/modules/SessionHistory.cpp#L395) can batch multiple commands that occur in the same second into one "append" on the file and one client event.

A pattern I like here is to record the "last-add-time" for each add.  The first write adds it immediately so there's no latency in the common case of one command at a time. If a second command comes in before the min-time has elapsed, it starts a batch that's flushed periodically. Maybe every second or so? 

### Describe the behavior you expected

Faster overall performance when lots of output is generated. Much less performance degradation when using certain file systems that don't allow rapid successive writes to the same file. 

See this PR: https://github.com/rstudio/rstudio/pull/13647 for a similar problem we fixed with the `executing` flag.

**Comment by kevinushey** [comment]
I started some work on this in https://github.com/rstudio/rstudio/pull/14765.

**Comment by kevinushey** [comment]
@jeffvroom, do you have any insight on what the best way to test this is? I implemented some optimizations for console history writes in https://github.com/rstudio/rstudio/pull/14765/files.

**Comment by jeffvroom** [comment]
How about if I add a new "R user scenario test" that emphasizes this code path.  That will make it easy to run it against 2024.04 and a version with this fix. We can compare overall run times, and if necessary run strace to confirm there are fewer open/writes for the new version.

**Comment by kevinushey** [comment]
Sounds good!

**Comment by jeffvroom** [comment]
Verified fixed in 2024.07.0-daily+294.pro1.  It clearly made a big difference.  For my LotsOfStatements.R script it saved 0.5 seconds and eliminated 1980 system calls.  Here are the raw stats:

Testing history_database:

with the fix: 2024.07.0-daily+294.pro1

Success - lots of statements:  199   in: 3.099642 secs

9 references to history_database in the strace

before the fix: 2024.04.2+764.pro1

Success - lots of statements:  199   in: 3.539973 secs

1989 references to history_database in the strace

The script itself was just:

x <- 1
...
x < - 199

This was on a fast aws instance, writing to a local disk.  Imagine over nfs how the latency for those 1900 system calls would really slow things down. Great work @kevinushey!
