### ISSUE TITLE
RStudio on Windows shows Choose R dialog on first-run even though it found an R installation

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14472]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1+402 (but probably all Electron versions)
    OS Version      : Windows-11
    R Version       : 4.1.3 (but happens with any version I've tried)

### Steps to reproduce the problem

NOTE: I'm pulling this out of https://github.com/rstudio/rstudio/issues/12695, which is turning into a bit of a Frankenbug.

- On a clean Windows system, install R 4.1.3 (per-machine, i.e. requires elevation), accepting all defaults
- Install (again, per-machine via elevation) and start RStudio 2023.12.1 (or, really, any release since the move to Electron)

I specify "per-machine" because in some environments users may not be able to install things per-machine, and the installers will instead install them per-user. That should not matter (ideally), but it's a factor that has caused problems reproducing issues in the past on Windows, so it's good to be aware of it.

### Describe the problem in detail

The "Choose R Installation" dialog is displayed at startup:

<img width="345" alt="screenshot of Choose R dialog at RStudio startup" src="https://github.com/rstudio/rstudio/assets/10569626/dd757df9-6b28-4f9f-bd2b-3a025778ea40">

### Describe the behavior you expected

With pre-Electron RStudio on Windows, the dialog is not shown and the main UI appears using the version of R that was detected.

Maybe this was an intentional change in behaviour, but I want to call it out to be sure.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Maybe this is a happy accident? I kind of like this as a feature, as long as it's just the first time.

**Comment by gtritchie** [comment]
> Maybe this is a happy accident? I kind of like this as a feature, as long as it's just the first time.

I don't have strong feelings about it either way.

**Comment by ronblum** [comment]
Let's keep this. Especially useful if a user has installed multiple versions of R before ever getting to RStudio.
