### ISSUE TITLE
In the universal macOS app, on copying code out of the code editor, newlines are represented by carriage returns

### ISSUE THREAD

**Issue by christianp** [rstudio/rstudio#14470]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0 and later; I've tested up to 2023.12.1
    OS Version      : macOS 14.2.1
    R Version       :  4.3.3 (but that doesn't matter)

### Steps to reproduce the problem

Create an R script, and type several lines of text. I typed:

```
a
b
c
```

Copy the text to the clipboard.
Paste the text somewhere else. (I made https://show-clipboard-contents.think.somethingorotherwhatever.com/ to show the contents of the clipboard)

### Describe the problem in detail
Each new line in the text is represented by a carriage return character, ASCII character 13.

I saw `"a\rb\rc"` on my "show clipboard contents" page.

When saving the script to a file, newlines are correctly represented by ASCII character 10. (The code above, when saved to a file, has contents `a\nb\nc`)

### Describe the behavior you expected

The newline character, ASCII code 10, should always be used to mark new lines. 

The versions of RStudio before the move to a universal app did this. (I tested version 2022.07.2, and got `a\nb\nc` in the clipboard when copying the above code)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Looks like this is coming from our `cleanClipboard` implementation:

https://github.com/rstudio/rstudio/blob/045401b9e6e826f7b8afd4871e5f66a0c5f5a6d9/src/node/desktop/src/native/desktop/desktop.cc#L379-L455

We never try to explicitly change the newline markers, so it seems like macOS is doing that behind the scenes for us.

**Comment by kevinushey** [comment]
(sorry, closed accidentally)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+668 on MacOS 14.4. Also:
- Checked on Windows 11, no changes.
- Pasted into several applications, no impact.
