### ISSUE TITLE
ggplot layers with alpha setting missing from "Show plot in new window"

### ISSUE THREAD

**Issue by thackl** [rstudio/rstudio#14479]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2023.12.1 Build 402 (note though, this problem has been around for a long time for me)
    OS Version      : Ubuntu 22.04.4 LTS
    R Version       : R version 4.1.2 

### Steps to reproduce the problem
```{r}
library(ggplot2)

ggplot(mtcars) +
  geom_point(aes(mpg, wt), size=3, color="red", alpha=.75) +
  geom_point(aes(mpg, wt), size=1)
# click GUI item to "Show plot in new window" (aka zoom in)
```
### Describe the problem in detail

If I open ggplot2 figures with `alpha` (or other complex features) in a new plot window, the layers disappear after rerendering to new aspect ratio/resolution. (Also, the fonts are off).

![image](https://github.com/rstudio/rstudio/assets/9363087/b7ec0c6e-8510-45ba-af5b-8851b826a1cc)

### Describe the behavior you expected

Everything should be there in the new window.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Glad to hear it -- thanks for testing and confirming!
