### ISSUE TITLE
Add "Close Tabs To The Right" in Source Editor Tab

### ISSUE THREAD

**Issue by Kaleckian** [rstudio/rstudio#14491]
I am using RStudio 2023.12.1 Build 402 and noted that there is no function to "Close Tabs to The Right" in the Source Editor Tab when you "right click" a particular tab:

![RstudioCloseTabs](https://github.com/rstudio/rstudio/assets/7070818/7092a287-fd04-4e9e-94c9-4652095db7a4)

This feature is not uncommon to other tabs, such as MS Edge. Here is an example:

![CloseTabsToTheRight](https://github.com/rstudio/rstudio/assets/7070818/7862977f-1f76-43de-b543-6db2bf9d92f1)

I have been using RStudio for almost 10 years, so thanks for everything!

**Comment by ronblum** [comment]
@Kaleckian Thank you for the suggestion. And you're welcome! You must've been using it since the first release or even a beta version. I'm glad it's been working for you. 🙂

**Comment by gtritchie** [comment]
For reference, here's the change that added the context menu on editor tabs: https://github.com/rstudio/rstudio/pull/8375

**Comment by olivroy** [comment]
relates to #11127
