### ISSUE TITLE
"View"ed data frames extract wrong rows when trying to investigate component objects by assuming rownames are indices

### ISSUE THREAD

**Issue by oganm** [rstudio/rstudio#14509]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version :  2023.12.1 Build 402 (Desktop), 2023.06.1 Build 524 (Server)
    OS Version      :  Ubuntu 20.04.2 LTS (desktop), CentOS Linux release 7.9.2009 (Core) (Server)
    R Version       :  4.2.2 (Desktop), 4.2.1 (Server)

### Steps to reproduce the problem

- Create a data frame which includes other viewable objects in its columns
- Change colnames to non-consequtive integers
- "View" the data frame
- Try to inspect the elements with out of order indices

```r
df = data.frame(i = c(1,2,3))
df$list_column = list(list(1),list(2),list(3))

rownames(df) = c(1,3,4)
View(df)
```
![image](https://github.com/rstudio/rstudio/assets/6352379/f7f54494-9d94-40fe-bb6d-8227b44e819a)

Upon viewing you will be able to inspect the lists included in the `list_column` column by clicking the magnifying glass icons. inspecting the first one will return the correct list, inspecting the second will return the third list (`View(df[[2]][[3]])`). Inspecting the third (`View(df[[2]][[4]])`) will return a `Error in View : subscript out of bounds` error

In addition, if rownames are not integers, 

```r
df = data.frame(i = c(1,2,3))
df$list_column = list(list(1),list(2),list(3))

rownames(df) = c('a','b','c')
View(df)
```
Any further inspection will not be responded to.

### Describe the problem in detail

`View` in Rstudio allows to inspect specific components of a `data.frame` that are themselves viewable. However when trying to perform this inspection, Rstudio will assume the rownames of the data.frame corresponds to the index of the data and can display wrong information, or fail to display if the rowname leads to out of bounds. In addition, if rownames are not castable to an integer, the inspection will silently fail.

This issue is particularly insidious with integers since it appears to work silently and wrongly

### Describe the behavior you expected

Rstudio should not assume the rownames of a data.frame are indexes and correctly access the requested data. In the data.frame below

```r
df = data.frame(i = c(1,2,3))
df$list_column = list(list(1),list(2),list(3))

rownames(df) = c(1,3,4)
View(df)
```

Trying to view the second element of list_column should either be translated correctly into `View(df[[2]][[2]])` instead of `View(df[[2]][[3]])` or the rownames should be used correctly to get the right data `df['3',][[2]]` (note that this will fail for `data.table`s)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@oganm Thank you for raising this! I can also reproduce this in RStudio Desktop 2024.04.0-daily+668 on Windows 11. I'll mark this for review.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11. 

Also, Here is the Data Viewer content. Note the change in the `list_column` column.
![Image](https://github.com/rstudio/rstudio/assets/31009952/7866a0b1-1be5-44e6-ad7d-45015e25a060)
