### ISSUE TITLE
utils View() and DataViewer does not work in RStudio (server) - Error in .External2(C_dataviewer, x, title) : unable to start data viewer In addition: Warning message: In utils::View(data.frame) : unable to open display

### ISSUE THREAD

**Issue by Corina-Mihaela-Motofeanu** [rstudio/rstudio#14503]
### System details

    RStudio Edition : Server
    RStudio Version : RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Focal
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
    OS Version      : Ubuntu 18.04.6 LTS
    R Version       : 4.3.3

### Session Info
R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so;  LAPACK version 3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] janitor_2.2.0     lubridate_1.9.3   forcats_1.0.0     stringr_1.5.1     purrr_1.0.2      
 [6] readr_2.1.5       tidyr_1.3.1       tibble_3.2.1      ggplot2_3.5.0     tidyverse_2.0.0  
[11] data.table_1.15.4 conflicted_1.2.0  dplyr_1.1.4      

loaded via a namespace (and not attached):
 [1] gtable_0.3.4      compiler_4.3.3    tidyselect_1.2.1  snakecase_0.11.1  scales_1.3.0     
 [6] fastmap_1.1.1     R6_2.5.1          generics_0.1.3    munsell_0.5.1     pillar_1.9.0     
[11] tzdb_0.4.0        rlang_1.1.3       utf8_1.2.4        cachem_1.0.8      stringi_1.8.3    
[16] timechange_0.3.0  memoise_2.0.1     cli_3.6.2         withr_3.0.0       magrittr_2.0.3   
[21] grid_4.3.3        rstudioapi_0.16.0 hms_1.1.3         lifecycle_1.0.4   vctrs_0.6.5      
[26] glue_1.7.0        fansi_1.0.6       colorspace_2.1-0  tools_4.3.3       pkgconfig_2.0.3  

### Steps to reproduce the problem

The code I run in order to load a data.frame

dir_input = file.path("/home","ubuntu","data_2024","input")
data.frame = 
  read.csv(
    file.path(
      dir_input,
      "data"))

After loading, I then click on the loaded data.frame (1900000 observations 31 variables) to view in console. The window to view opens but the data in the data.frame never opens. It does not throw an error it simply does not show anything inside. I maximised the frame and still not working.

I tried with a smaller data.frame ( 6 observations and 31 variables) and still not working. 

I updated RStudio server and problem persists. 

This code and visualising data frames were working and I could visualise the data in the data.frame and filter or arrange it etc.  I recently updated R version and RStudio. All packages are updated. I also restarted RStudio with Ctrl+Shift+F10 and problem persists. Workspace also cleaned but problem persists. 

I also tried utils::View(data.frame) and still not working but it throws an error:

**> utils::View(data.frame)
Error in .External2(C_dataviewer, x, title) : unable to start data viewer
In addition: Warning message:
In utils::View(dmr_nsd2_small) : unable to open display**

**NOTE: I can view functions. I can view plots. But not data frames.** 

What could be the issue and what can be done?

**NOTE: I made a tibble (see code below) to test out View and it still did not work. Not even opening in New Window.** 

test_tibble = 
 tibble(
 "a" = c(1,2,3),
 "b"= c(4,5,6),
 "c"= c(7,8,9)
)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Corina-Mihaela-Motofeanu Thank you for raising this! Jumping straight to the bottom for the easiest reprex, I was able to create the and use `View` with the tibble.

@kevinushey Do you have any suggestions of anything to look for?

Note: Ubuntu 18 is no longer supported, so I'm not sure how much help we'd be able to provide. But my tests was on both Ubuntu 18 and 20.

**Comment by kevinushey** [comment]
Does `View()` succeed with any of the built-in R datasets? For example, does `View(mtcars)` work?

I also don't have any great ideas beyond trying to update to the latest version of Ubuntu. Note that Ubuntu 24.04 is slated for release soon; currently the planned release date is April 25th.

**Comment by Corina-Mihaela-Motofeanu** [comment]
Hi, thanks for the response!

As an update, I can say that:

1. View (1) works 
2. t <- .rs.describeCols(iris, maxFactors = 10)  --> View (t) works
3. View (mtcars) does not work. It opens the window but displays nothing. Only when I add the utils::View(mtcars) it gives same error as before. 

##### I created a new preconfigured R machine on Ronin and updated it to Ubuntu 22:
R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

RStudio server: _rstudio-server-2023.12.1-402-amd64.deb_

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: Asia/Singapore
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.3 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4     purrr_1.0.2     readr_2.1.5    
 [7] tidyr_1.3.1     tibble_3.2.1    ggplot2_3.5.0   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       cli_3.6.2         rlang_1.1.3       stringi_1.8.3     generics_0.1.3   
 [6] glue_1.7.0        colorspace_2.1-0  hms_1.1.3         scales_1.3.0      fansi_1.0.6      
[11] grid_4.3.3        munsell_0.5.1     tzdb_0.4.0        lifecycle_1.0.4   compiler_4.3.3   
[16] timechange_0.3.0  pkgconfig_2.0.3   rstudioapi_0.16.0 R6_2.5.1          tidyselect_1.2.1 
[21] utf8_1.2.4        pillar_1.9.0      magrittr_2.0.3    tools_4.3.3       withr_3.0.0      
[26] gtable_0.3.4 


I did sudo apt-get update and sudo apt-get upgrade for it after installing Ubuntu 22. I also run R and did update.packages() and updated everything after installing R4.3.3. I restarted RStudio as well with sudo rstudio-server restart. I also restarted R session in Rstudio with Ctrl+Shift+F10. 

Nothing works. I can still not View() data frames no matter what Ubuntu version I use. I also tried with an older version of RStudio _rstudio-server-2022.07.2-576-amd64.deb_ but I had same error.

**Comment by BinghuaLi** [comment]
> Hi, thanks for the response!
> 
> As an update, I can say that:
> 
> 1. View (1) works
> 2. t <- .rs.describeCols(iris, maxFactors = 10)  --> View (t) works
> 3. View (mtcars) does not work. It opens the window but displays nothing. Only when I add the utils::View(mtcars) it gives same error as before.
> 
> ##### I created a new preconfigured R machine on Ronin (https://ronin.cloud/) and updated it to Ubuntu 22:
> R version 4.3.3 (2024-02-29) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 22.04.4 LTS
> 
> RStudio server: _rstudio-server-2023.12.1-402-amd64.deb_
> 
> Matrix products: default BLAS: /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so; LAPACK version 3.10.0
> 
> locale: [1] LC_CTYPE=C.UTF-8 LC_NUMERIC=C LC_TIME=C.UTF-8 LC_COLLATE=C.UTF-8 [5] LC_MONETARY=C.UTF-8 LC_MESSAGES=C.UTF-8 LC_PAPER=C.UTF-8 LC_NAME=C [9] LC_ADDRESS=C LC_TELEPHONE=C LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C
> 
> time zone: Asia/Singapore tzcode source: system (glibc)
> 
> attached base packages: [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages: [1] lubridate_1.9.3 forcats_1.0.0 stringr_1.5.1 dplyr_1.1.4 purrr_1.0.2 readr_2.1.5 [7] tidyr_1.3.1 tibble_3.2.1 ggplot2_3.5.0 tidyverse_2.0.0
> 
> loaded via a namespace (and not attached): [1] vctrs_0.6.5 cli_3.6.2 rlang_1.1.3 stringi_1.8.3 generics_0.1.3 [6] glue_1.7.0 colorspace_2.1-0 hms_1.1.3 scales_1.3.0 fansi_1.0.6 [11] grid_4.3.3 munsell_0.5.1 tzdb_0.4.0 lifecycle_1.0.4 compiler_4.3.3 [16] timechange_0.3.0 pkgconfig_2.0.3 rstudioapi_0.16.0 R6_2.5.1 tidyselect_1.2.1 [21] utf8_1.2.4 pillar_1.9.0 magrittr_2.0.3 tools_4.3.3 withr_3.0.0 [26] gtable_0.3.4
> 
> I did sudo apt-get update and sudo apt-get upgrade for it after installing Ubuntu 22. I also run R and did update.packages() and updated everything after installing R4.3.3. I restarted RStudio as well with sudo rstudio-server restart. I also restarted R session in Rstudio with Ctrl+Shift+F10.
> 
> Nothing works. I can still not View() data frames no matter what Ubuntu version I use. I also tried with an older version of RStudio _rstudio-server-2022.07.2-576-amd64.deb_ but I had same error.

I have the exactly same error. Could you please tell me how to solve it?
