### ISSUE TITLE
Go to directory... not opening Go to folder dialog

### ISSUE THREAD

**Issue by blairchesnut-at-duke** [rstudio/rstudio#14501]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1 Build 402
    OS Version      : RH EL7 (3.10.0-1160.114.2.el7.x86_64)
    R Version       : 4.3.1 (2023-06-16)

### Steps to reproduce the problem
1. From main menu, click Session -> Set Working Directory -> Choose Directory ...
On Choose Working Directory dialog window, click ... (Go to directory)

or

2. From Files tab, click ... (Go to directory)

### Describe the problem in detail
1. Another Choose Working Directory dialog window opens behind the first one.
or
2. A Choose Working Directory window opens; clicking on ... (Go to directory) opens another Choose Working Directory dialog

### Describe the behavior you expected
Expected behavior is a Go to Folder dialog to be displayed with a Go to Folder textbox.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

See also https://forum.posit.co/t/go-to-directory-not-working-in-rstudio-2023-12-1-build-402/184704

**Comment by lucasbarriga25** [comment]
j
7

**Comment by blairchesnut-at-duke** [comment]
Same issue occurs with prior versions of RStudio:
2023.06.1 Build 524
2023.03.2 Build 454

Two workarounds
1. use setwd() then More -> Go to Working Directory on Files tab
2. Tools -> Global Options... -> Advanced -> Use native file and message dialog boxes.

**Comment by gtritchie** [comment]
I was able to reproduce this. On RStudio Desktop on Linux, with "Use native file and message dialog boxes" turned off (the default), each click on the "..." button in the "Choose Working Directory" dialog brings up another instance of the same dialog.

For example, clicking here:

<img width="1201" alt="click-here" src="https://github.com/rstudio/rstudio/assets/10569626/ebc3dc49-af28-4b9f-82a9-371fb38bd3e7">

brings up the same dialog (at the exact same location). In this case, I've done it twice, and moved the dialogs so they are visible:

<img width="1205" alt="multiple-dialogs" src="https://github.com/rstudio/rstudio/assets/10569626/a3d2eccd-75d8-4706-a492-526e31624a76">

On RStudio Server, clicking that button instead brings up the correct dialog that lets you type in a path:

<img width="521" alt="correct" src="https://github.com/rstudio/rstudio/assets/10569626/4dc1d981-f567-4ea1-8038-5774f9a9bc27">

**Comment by gtritchie** [comment]
Note to self: https://github.com/rstudio/rstudio/pull/11185

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+131 on Windows 11 and SLES 15.5. Checked that both native and non-native dialogs work.

One issue: The first time that a native dialog is called, it's in front of the IDE. But on subsequent calls, the file explorer is behind the IDE. Is this the same as #14683?
