### ISSUE TITLE
Diagnostics show for spelling in gutter

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14510]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.672
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.3.2 (2023-10-31 ucrt

### Steps to reproduce the problem

Save an R file an create a file with the following contents

```r
# A spellling error
```

### Describe the problem in detail

A tooltip in the margin shows up. 

![image](https://github.com/rstudio/rstudio/assets/52606734/4083ae56-fb57-4048-9206-67cbe6235afd)

It didn't before. I find it quite distracting as I think that the underlining is sufficient to indicate a spelling error...

### Describe the behavior you expected

Either to have the diagnostic not showing up or to have an option to disable that one specifically. Currently, there are options to disable it as far as I can tell. There are options to disable other diagnostics type.

Maybe some persons will like that new feature? But it clutters the side imo, and are harder to ignore than the previous underlining.
From previous screenshots, it doesn't seem to be intentional.. https://github.com/rstudio/rstudio/issues/11306

Screenshot from 2023.12.0+369:
![image](https://github.com/rstudio/rstudio/assets/52606734/3a374f60-cdf0-4a2c-a2d6-7e8607802566)

According to Blame, this was introduced recently with https://github.com/rstudio/rstudio/commit/f882747a9b54c4430b9866f2467ec0c7fd42b028 : https://github.com/rstudio/rstudio/issues/14500

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified fixed in RStudio Desktop 2024.04.0-daily+680 on Windows 11.

**Comment by kevinushey** [comment]
I've noticed the spelling gutter icons will render / flash intermittently while typing in a document; re-opening.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2025.11.0-daily+217 on Windows 11. Tried by typing above, below, in between. and inside misspelled words in both body paragraphs and comments inside a chunk.
