### ISSUE TITLE
Docs: Implement new quarto pro product doc theme 

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#14513]
Implement new[ Posit Product Docs Quarto ](https://github.com/posit-dev/product-doc-theme/tree/main)theme via extension. https://github.com/posit-dev/product-doc-theme/blob/main/README.md

Workbench/server-pro tracking issue: https://github.com/rstudio/rstudio-pro/issues/5729

- [x] News
- [x] IDE User Guide
- [x] Add release notes entry

Overview:

- 99% of styles should now be covered by the theme style sheet (in the _extensions folder).
- Removed entries in quarto.yml file that are now covered by the theme
- There are a few entries that need to be copied from them to the quarto.yml (the nav bar menu drop-down, assets, and the footer icons). These items overwrite what is in the theme, which is expected behavior.
- Removed unused styles from project's styles.scss.
- News project had an extra style sheet that was removed.
- Main things that have changed by the theme implementation:
- Nav bar (font, icons, menu drop-down)
- Project's font, font color, headers, etc.
- Tabsets: Font and font color
- Links: color
- Steps/lists: Color
- Footer (Font, product name and version - center, new icons - right)
- See [Confluence proposal](https://positpbc.atlassian.net/wiki/spaces/ENG/pages/536871053/Pro+Product+Doc+Theme) for overview.

See [extension.yml](https://github.com/posit-dev/product-doc-theme/blob/main/_extensions/posit-docs/_extension.yml) to review quarto entries that are now controlled by the theme.

**Comment by ronblum** [comment]
Verified by visual comparison of revision 41 with 32, spot-checking several areas.
