### ISSUE TITLE
wrong completions in ggplot2 functions

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14519]
@kevinushey A similar fix would be required to be made for completions in the function, but I don't know where it should be.

in `geom_boxplot()` (not within `aes()`, I get the following completions)
![image](https://github.com/rstudio/rstudio/assets/52606734/30734036-f352-4361-8c20-21118e3d473a)

_Originally posted by @olivroy in https://github.com/rstudio/rstudio/issues/14394#issuecomment-2037650919_

A similar fix as in the PR should be done (or possibly applied so that completions of the form `x|y` are excluded from functions + `aes()` calls

**Comment by ronblum** [comment]
Verified fixed in RStudio Desktop 2024.04.0-daily+682.pro1 on Windows 11.
