### ISSUE TITLE
Debugger moves between tabs unexpectedly when invoking `browser()`

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14514]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.672
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

1. Open an RStudio project with some existing files in it
2. Open some existing files in the editor
3. Create a new R document and paste the following

```r
f <- function(x) {
  browser()
  x **2
}
```

4. don't save the document, but execute the function
5.  In the console, type `f(2)`

### Describe the problem in detail

The editor loses focus and goes automatically to the first file I have open. I noticed a behavior change with the latest daily. Didn't notice this before. (in earlier dailies or with released version)

### Describe the behavior you expected

I would expect either to change focus if the source of function is found, but the focus should not be changed if no match is encountered. or maybe find the source location of the function in the unsaved file, but that's probably a stretch.

You can test the difference if you only have the unsaved file open in RStudio

I noticed this also happens when I wrote the function in an existing but modified and unsaved qmd document.

Problem happens:
![image](https://github.com/rstudio/rstudio/assets/52606734/82d8cc9c-c0cc-4c45-8e99-f94e2d2299fb)

Same behavior as in 2023.12.0+369 if only 1 file opened.
 Previous behavior correctly happens
![image](https://github.com/rstudio/rstudio/assets/52606734/4c0293d6-4376-48ee-b826-c68517cdc572)

Note that I didn't notice this in the previous daily I used, but might have missed it!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment]
Also correct with 2024.04+624. maybe https://github.com/rstudio/rstudio/pull/14494 has caused this regression?

**Comment by kevinushey** [comment]
Thanks for catching that! I'll take a look; we'll definitely want to fix this up for the next release.

**Comment by olivroy** [comment]
Awesome, and it moves multiple times. For example, I run the function with the browser() call -> it moves. I navigate back to the function, and then type something in the console, it moves again.

Edit: Wow a one-liner fix. Who would have thought!

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+693 on Windows 11. Although @olivroy if you can check it that'd be great, because I don't think that I was consistently reproducing the issue previously (not sure why).

**Comment by olivroy** [comment]
Sure. I am on the latest daily, will let you know if I see something weird !
