### ISSUE TITLE
`RStudio` randomly causes `R Session Aborted` in combination with `data.table`

### ISSUE THREAD

**Issue by gernophil** [rstudio/rstudio#14517]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1+402
    OS Version      : 14.4.1
    R Version       : 4.3.3

### Steps to reproduce the problem
Use `RStudio` in combination with a compiled from source `data.table`.

### Describe the problem in detail
Since the last version of `Rstudio`, `data.table` is randomly causing an `R Session Aborted` error. I couldn't it narrow down to a specific function, but it only happens with `Rstudio` and not using `Rscript` or `R.app` in combination with the package `data.table`. [I've also filed a report there](https://github.com/Rdatatable/data.table/issues/5957), but it's unclear, if `RStudio` or `data.table` is the source of this issue. Apart from this I don't have any more clues, what could cause it as it happens on various commands (`saveRDS()`, simple assignment of a `dt` to a variable...). I am posting this here, since checking `data.table` for bugs seems to be a dead end so far and the issue only happens in combination with `Rstudio`.

I am using `data.table 1.15.2` compiled from source on macOS 14.4.1 using libomp from [here](https://mac.r-project.org/openmp/).

![Ohne Titel](https://github.com/Rdatatable/data.table/assets/19264855/ff9b0b67-054f-4df4-877a-3a9efb026f32)

### Describe the behavior you expected
I expect the code(s) to run without an error.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gernophil Thank you for raising the problem! I tried reproducing the issue on both MacOS 14.4.1 and Windows 11, but no luck. Can you provide a minimal example of code that triggers this, even if it's inconsistent?

**Comment by gernophil** [comment]
Hey, this is really hard, since it seems to happen completely random. It happens on complex scripts as well as on very simple ones. And sometimes it does not happen for some hours or even days and sometimes multiple times in a row. I still wasn't able to figure out a pattern yet. Just that it's the combination of RStudio and data.table. Did you check the issue at data.table? I know it's annoying for you to check the other thread, but this might be the most informative information, about what's been tried and what not.

In the beginning I was suggesting an issue with setting `R_MAX_VSIZE` to more disk space then physically available, but this turned out to be wrong. Right now, I am trying to figure out, if this is related to installing `data.table` from source using the libomp from [here](https://mac.r-project.org/openmp/). Currently, I have the precompiled binary installed and this hasn't raised the error yet (but I just installed it and haven't used it heavily).

I'll try to sum up the thread and also create a minimal example that raised the error at least once. Not sure, how long that might take.

**Comment by ronblum** [comment]
@gernophil No problem! I've been trying to reproduce with in a few environments, but no luck. I'm using code from a `data.table` vignette that I ran over and over.
```
library(data.table)
DT = data.table(
  ID = c("b","b","b","a","a","c"),
  a = 1:6,
  b = 7:12,
  c = 13:18
)
DT
```

@kevinushey Do you have suggestions of what to look for? I changed to several values of `R_MAX_VSIZE` (no effect) before I realized that @gernophil ruled that out.

**Comment by gernophil** [comment]
Thanks for your help. So, let me try to recapitulate this.
I used The combination of `data.table` compiled from source and `RStudio` successfully for more then a year. I work in bioinformatics and mostly deal with TSV or CSV shaped files (like VCFs) of multiple GBs. I think I massively used it till October '23 without this error and then switched to another project, where I mostly used `tidyverse`. Then beginning February '24 i continued the other project and at this time I realized the error for the first time. So, it was most likely introduced by any of the changes introduced in one of the components during October '23 and February '24. The most likely components would be:
`data.table`: 1.14.8 -> 1.15.0
`RStudio`:  2023.09.0 -> 2023.12.1
`R`: 4.3.1 -> 4.3.3
`Xcode`: 15.0 -> 15.3 (maybe even 14.3.1 or older)
`OpenMP LLVM`: 16.0.4 (no change during that time, but I also used 15.0.7 and 14.0.6 before)
Especially for Xcode and OpenMP LLVM I am not sure, what was the last version I used, when it the error did not happen.

I ruled out that `R_MAX_VSIZE` affects this. I had it at 100Gb, but the error also happens with 50Gb and completely unset. rebuild the package wit Xcode 14.3.1 and OpenMP 15.0.7, but this also didn't help. Another user is having the same issue with `R` 4.3.1 and `data.table` 1.14.10 using `RStudio` 2023.12.1. That might narrow it down, but I don't know, if this user installed from source or precompiled binary.

One thing I just stumbled across is that the file `inst/cc` was changed from 1.14.8 to 1.14.10 from
```
CC=gcc
CFLAGS=-O2
```
to
```
CC=clang -arch arm64
CFLAGS=-falign-functions=64 -Wall -g -O2
```
not sure, if this might be any hint. I'm just poking around in the dark.

**Comment by kevinushey** [comment]
Sorry, but until we have a standalone reproducible example (some code we can try to run locally to reproduce the issue), there's not much we can do.

**Comment by gernophil** [comment]
Ok, here is an MRE that raised the error three times, while coding interactively and running partial with `cmd + alt + b` and running it completely with `cmd + alt + r`.
While the error occurred I had `data.table` version 1.15.4,
installed from source using Xcode 15.3
with OpenMP from LLVM 16.0.4 from [here](https://mac.r-project.org/openmp)
(installed as stated there: `sudo tar fvxz openmp-16.0.4-darwin20-Release.tar.gz -C /`).
This is my `~/.R/Makevars`:
```
CPPFLAGS += -Xclang -fopenmp
LDFLAGS += -lomp
```
R: 4.3.3
Rstudio: 2023.12.1
Ah, and I am using [this theme](https://github.com/patrickshox/Mojave-Dark-RStudio-Theme), maybe that could also be a source of the error?

Here's the MRE:
```
library(data.table)

input <- "https://raw.githubusercontent.com/Rdatatable/data.table/master/vignettes/flights14.csv"
flights <- fread(input)

saveRDS(flights, "flights.rds")

flights <- readRDS("flights.rds")

flights[year == 2014, year := 14]
flights[year == 14, year := 2014] # happened here once
flights[, carrier_origin_dest := paste0(carrier, "_", origin, "_", dest)] # happened here once

flights[, c("carrier_split", "origin_split", "dest_split") := tstrsplit(carrier_origin_dest,
                                                                        "_",
                                                                        fixed = TRUE)]

saveRDS(flights, "flights_modified.rds")
fwrite(flights, "flight_modified.csv") # happened here once

```

**Comment by kevinushey** [comment]
Thanks -- can you also share the output of:

```
system(paste("lsof -p", Sys.getpid(), "| grep dylib"))
```

just so we can confirm where `libomp.dylib` is being loaded from? I wasn't able to reproduce locally, but it looks like my copy of `data.table` is using the version of `libomp.dylib` bundled with R:

```
> system(paste("lsof -p", Sys.getpid(), "| grep dylib"))
rsession- 46535 kevin  txt       REG               1,18    193872           218483700 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib
rsession- 46535 kevin  txt       REG               1,18    157712           218483712 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libgcc_s.1.1.dylib
rsession- 46535 kevin  txt       REG               1,18    793520           227540124 /Applications/RStudio.app/Contents/Resources/app/Frameworks/arm64/libssl.3.dylib
rsession- 46535 kevin  txt       REG               1,18    366800           218483711 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libquadmath.0.dylib
rsession- 46535 kevin  txt       REG               1,18   1613904           218483690 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libomp.dylib
rsession- 46535 kevin  txt       REG               1,18   5126784           218483701 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib
rsession- 46535 kevin  txt       REG               1,18   1864864           218483699 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libgfortran.5.dylib
rsession- 46535 kevin  txt       REG               1,18   1713120           218483713 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib
rsession- 46535 kevin  txt       REG               1,18   4179824           227540125 /Applications/RStudio.app/Contents/Resources/app/Frameworks/arm64/libcrypto.3.dylib
rsession- 46535 kevin  txt       REG               1,18 255647504           223440007 /Library/Developer/CommandLineTools/usr/lib/libclang.dylib
```

Also, for posterity, I was testing with the current development version of `data.table`, installed via `remotes::install_github("Rdatatable/data.table")`.

```
> packageVersion("data.table")
[1] '1.15.99'
```

**Comment by gernophil** [comment]
Here's the output:
```
rsession- 1067 gernophil  txt       REG               1,16    193872           181121152 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib
rsession- 1067 gernophil  txt       REG               1,16    157712           181121164 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libgcc_s.1.1.dylib
rsession- 1067 gernophil  txt       REG               1,16    793520           179499805 /Applications/RStudio.app/Contents/Resources/app/Frameworks/arm64/libssl.3.dylib
rsession- 1067 gernophil  txt       REG               1,16    366800           181121163 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libquadmath.0.dylib
rsession- 1067 gernophil  txt       REG               1,16   5126784           181121153 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib
rsession- 1067 gernophil  txt       REG               1,16   1864864           181121151 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libgfortran.5.dylib
rsession- 1067 gernophil  txt       REG               1,16   1713120           181121165 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib
rsession- 1067 gernophil  txt       REG               1,16   4179824           179499806 /Applications/RStudio.app/Contents/Resources/app/Frameworks/arm64/libcrypto.3.dylib
rsession- 1067 gernophil  txt       REG               1,16   1613904           181121142 /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libomp.dylib
rsession- 1067 gernophil  txt       REG               1,16 255647504           181925547 /Library/Developer/CommandLineTools/usr/lib/libclang.dylib
```

It seems like my data.table is also using the bundled `libomp.dylib`. I never checked for this. Do you know since what version it is bundled with R? Why does r-project link this external `libomp.dylib` at all, if it is included already?

BTW. Today I was able to run the script around 20 times without raising this error once, so I couldn't do any more tests. Maybe this is also connected to some macOS wide garbage collector or sth.?

If I get this "R Session Aborted" does RStudio write any log maybe?

**Comment by kevinushey** [comment]
I think the next best thing you could try would be, from a Terminal, after starting RStudio, try running:

```
sudo lldb -p $(pgrep -nx rsession-arm64)
```

Then, continue using RStudio as normal. If the crash occurs again, `lldb` should catch it, and then you can use:

```
bt
```

to get a backtrace. That might give us some hints, but the lack of debug symbols might obscure things.

**Comment by gernophil** [comment]
I checked, which library is used during install and during loading.

For this I temporarily removed the /usr/local/lib/libomp.dylib and the bundled omp files at /usr/local/include (omp-tools.h, omp.h, ompt.h) or just /usr/local/lib/libomp.dylib.

If I remove all four, I can normally load (or attach) data.table using `library(data.table)`. It is still loaded with multiple threads:
```
data.table 1.15.4 using 4 threads (see ?getDTthreads). Latest news: r-datatable.com
```

It does however make it impossible to install data.table from source with these flags (set in ~/.R/Makevars; I also temporarily removed the omp files from /usr/local/include that are bundled in the tarball)
```
CPPFLAGS += -Xclang -fopenmp
LDFLAGS += -lomp
```

This is the error that happens then:
```
...
In file included from ./data.table.h:1:
./myomp.h:2:12: fatal error: 'omp.h' file not found
#include <omp.h>
^~~~~~~
1 error generated.
make: *** [assign.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/data.table’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/data.table’
Warning in install.packages :
installation of package ‘data.table’ had non-zero exit status
```

If I only remove /usr/local/lib/libomp.dylib, but keep the omp files in place, I can install and attach data.table. So it seems that also here the internal libomp.dylib from R is used. Just the bundled omp files at /usr/local/include (omp-tools.h, omp.h, ompt.h) seem to be used during install. Maybe this is caused by a mismatch of these file and the used libomp.dylib?

P.S.: I couldn't try the backtrace yet, since I was on the non-OpenMP version, but I'*ll try that today.

**Comment by gernophil** [comment]
> I think the next best thing you could try would be, from a Terminal, after starting RStudio, try running:
> 
> ```
> sudo lldb -p $(pgrep -nx rsession-arm64)
> ```
> 
> Then, continue using RStudio as normal. If the crash occurs again, `lldb` should catch it, and then you can use:
> 
> ```
> bt
> ```
> 
> to get a backtrace. That might give us some hints, but the lack of debug symbols might obscure things.

To do this I guess I would also have to start RStudio from terminal, wouldn't I?
