### ISSUE TITLE
Handle `options(help.htmltoc = TRUE)` gracefully

### ISSUE THREAD

**Issue by deepayan** [rstudio/rstudio#14523]
R 4.4.0-to-be includes a new `options("help.htmltoc")`. If set to TRUE, this will add a table of contents to dynamic help pages. Although currently unset, it is likely that this option will be set to TRUE by default in R 4.4.0.

The appearance of this TOC is controlled by a stylesheet shipped with R. As RStudio's help viewer uses its own stylesheet, the TOC currently appears as an unstyled list at the end of the help page (this can be tested by first setting `options(help.htmltoc = TRUE)`). It would be nice if this is handled more gracefully. 

Probably the simplest solution is to add something like this to the RStudio version of R.css:

```
nav.topic { display: none; }
```

**Comment by kevinushey** [comment]
Thanks! Given that the available horizontal space in the Help pane is typically going to be small, I think you're right that we should disable its display by default.

For a future enhancement, I think we should make sure we use `R-nav.css` if the user opens the Help page in a separate page, since they'd then have the requisite available horizontal space.

**Comment by deepayan** [comment]
Sounds good. 

I'm happy to tweak R-nav.css if you have any suggestions.

**Comment by jthomasmock** [comment]
@ronblum to test this out to see if the ToC is displayed with an appropriately wide Help pane.

**Comment by ronblum** [comment]
Can you provide an example in which the table of contents would appear? I tried a number of examples, with a wide Help Pane but no ToC. I don't know if this means that it's not working or if I'm not using proper examples.

Note: The option is null be default.
```
> options("help.htmltoc")
$help.htmltoc
NULL
```

**Comment by kevinushey** [comment]
I could've sworn I did the work to support the TOC in RStudio, but now I can't find it... moving back to Ready.

**Comment by deepayan** [comment]
> Can you provide an example in which the table of contents would appear? I tried a number of examples, with a wide Help Pane, but there's no ToC. I don't know if this means that it's not working or if I'm not using proper examples.
> 
> Note: The option is null by default.
> 
> ```
> > options("help.htmltoc")
> $help.htmltoc
> NULL
> ```

So this seems to "work" as it should with "RStudio Server 2024.04.2 Build 764" (via rocker), thanks to [this](https://github.com/rstudio/rstudio/blob/4af4a8f20924ca73836ea80af89ddbc9833c3d46/src/cpp/session/resources/R.css#L140).

So unless you want to also support a visible TOC for wide pages (via "Show in New Window"?), I don't think there's anything else to be done.

**Comment by ronblum** [comment]
@deepayan I trust your opinion as the user, especially since the fix is what you originally proposed. 🙂
