### ISSUE TITLE
RStudio copyTo operation removes file if src = target and 'overwrite' is true

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#14525]
### Steps to reproduce the problem

Use the copy to dialog, set overwrite to true using the same file name. 

### Describe the problem in detail

This line could ruin someone's day: https://github.com/rstudio/rstudio/blob/1688b56596fcee7bd7edece6a3842151ea1ceac8/src/cpp/session/modules/SessionFiles.cpp#L407

### Describe the behavior you expected

We should at least check for the same file name. Ideally, resolve symbolic links, get the canonical path and then compare as well and return an error. 

From support ticket: https://rstudioide.zendesk.com/agent/tickets/103492

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+131 on Windows 11. Checked both that the file itself remains, and that a symlink to it continues to work.
