### ISSUE TITLE
Can't right-click paste in Console Pane on Windows

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#14538]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.2+454, 2024.04.0-daily+682.pro1
    OS Version      : Windows
    R Version       : 4.3.3, 4.4.0 beta

### Steps to reproduce the problem

1. Copy text from anywhere.
2. Right-click in the Console Pane.
    - Paste isn't available.
    - Copy and other options are available.

### Describe the problem in detail

It's not possible to paste in the Console Pane using right-click.

### Describe the behavior you expected

Right-clicking to paste should be possible in the Console Pane on Windows.

Note that it works correctly:
- On MacOS
- Other panes, such as the search box in the Packages Pane

This has been around for a long time, so this is not a regression.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
QA: Check Qt versions of RStudio Desktop.

**Comment by ronblum** [comment]
@ronblum Please check this.

**Comment by ronblum** [comment]
@ronblum OK I'll check it today hopefully, or tomorrow at the latest.

**Comment by ronblum** [comment]
IT works correctly in the Qt version of RStudio Desktop 2022.07.2+576, and fails in the Electron version.

**Comment by kevinushey** [comment]
We discussed this in triage, but it looks like right click paste _does_ work as long as you click on the Console input line -- if you click on the Console history, it does not. This is perhaps unexpected since we normally drive focus to the console input even if you just click in the console history?

**Comment by gtritchie** [comment]
It is working now if I right-click above the input line (or on the input line), but not if I right-click below the input line. "Paste" is still enabled when I click below, but it doesn't do anything.

This is on Windows; on Mac it works anywhere.

https://github.com/user-attachments/assets/f2332d9e-dcd5-416d-9731-f254f23725ba

**Comment by gtritchie** [comment]
Verified on Windows-11 using build 2024.11.0+345, "paste" from right-click context menu works no matter where you click in the console.

Also double-checked on Linux and Mac, and all are working as expected.
