### ISSUE TITLE
Chunks without code in them break Quarto syntax highlighting and outline in source editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#14544]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0-daily+689 "Chocolate Cosmos" Daily (9ee2b6131e42e36e31cec48a4eb88d2e700e272c, 2024-04-10) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+689 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.553 (/Applications/quarto/bin/quarto)
    OS Version      : Mac OS Ventura 13.5 (22G74)
    R Version       : R version 4.3.3 (2024-02-29) -- "Angel Food Cake"

### Steps to reproduce the problem

In a Quarto document insert some 1st and 2nd level headers and code chunks in each one. For one of the code chunks, add a chunk option but no code in it. (This comes up when that chunk option is `ref-label`, where you don't need to add more code, you just want to refer to an earlier chunk.)

### Describe the problem in detail

The outline and the syntax highlighting for headers and chunks are broken for the remainder of the document.

For example, note the green first level header (Chapter 2) and pink curly braces for the last chunk as well as the lack of indentation for section headers in the document outline.

<img width="1624" alt="Screenshot 2024-04-14 at 8 56 19 AM" src="https://github.com/rstudio/rstudio/assets/5965649/7fb10b01-9300-4e9d-96e4-c7afda253af1">

Things look ok in the visual editor.

<img width="1624" alt="Screenshot 2024-04-14 at 8 56 06 AM" src="https://github.com/rstudio/rstudio/assets/5965649/7fb0701f-001a-4dff-84b5-9b67a3e2c8c5">

### Describe the behavior you expected

I expected things to look like the following even when that middle code chunk doesn't have any code in it.

<img width="1624" alt="Screenshot 2024-04-14 at 8 58 29 AM" src="https://github.com/rstudio/rstudio/assets/5965649/fc1b71df-5263-4da3-9738-ed23254e03dd">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible:
- Problem occurs in RStudio Desktop 2024.04.0-daily+693 on Windows 11.
- This is a regression, as it works in 2023.12.1+402.
- The problem is in source mode--the document outline works correctly in visual mode.

````
---
format: html
---

# Chapter 1

## Section 1.1

Hello

```{r}
#| label: simple-arithmetic
1 + 1
```

## Section 1.2

Mello

```{r}
#| ref-label: simple-arithmetic
```

# Chapter 2

Jello

```{r}
3 + 3
```
````

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0+725 on Windows 11 using the above example and intentionally messing it up in different ways. There's a separate old issue with the outline that I'll file separately.
