### ISSUE TITLE
Syntax highlighting with code chunk options containing `.` don't work properly

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#14545]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0-daily+689 "Chocolate Cosmos" Daily (9ee2b6131e42e36e31cec48a4eb88d2e700e272c, 2024-04-10) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+689 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.553 (/Applications/quarto/bin/quarto)
    OS Version      : Mac OS Ventura 13.5 (22G74)
    R Version       : R version 4.3.3 (2024-02-29) -- "Angel Food Cake"

### Steps to reproduce the problem

In an R Markdown file, add some code chunks with options that contain `.`, e.g., `ref.label`, `out.width`, etc.

### Describe the problem in detail

These words are not highlighted like other code chunk options.

<img width="1653" alt="Screenshot 2024-04-14 at 9 02 13 AM" src="https://github.com/rstudio/rstudio/assets/5965649/c5602ef6-9e56-4b43-9cda-490328fff992">

This is true in the visual editor as well.

<img width="1653" alt="Screenshot 2024-04-14 at 9 04 28 AM" src="https://github.com/rstudio/rstudio/assets/5965649/dfc3fe82-110d-45af-bba9-bbe6a0552b21">

Note, the broken syntax highlighting issue raised in #14544 is also visible in these images.

### Describe the behavior you expected

I expected the code chunk options to be the same color, regardless of whether they're `knitr` options or also Quarto options.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible:
- Problem occurs in RStudio Desktop 2024.04.0-daily+693 on Windows 11.
- This is a regression from 2023.12.1+402. There are different display issues in it, but those go away and are replaced with this bug.

````
---
output: html_document
---

# Chapter 1

## Section 1.1

Hello

```{r}
#| label: simple-arithmetic
1 + 1
```

## Section 1.2

Mello

```{r}
#| ref.label: simple-arithmetic
```

# Chapter 2

Jello

```{r}
3 + 3
```

```{r}
#| out.width: 30%
plot(cars)
```
````

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0+725 on Windows 11. Checked that both source and visual modes work correctly.
