### ISSUE TITLE
Messages print even when `message: false` is set when running a Quarto document interactively

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#14553]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0-daily+689 "Chocolate Cosmos" Daily (9ee2b6131e42e36e31cec48a4eb88d2e700e272c, 2024-04-10) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+689 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.553 (/Applications/quarto/bin/quarto)
    OS Version      : Mac OS Ventura 13.5 (22G74)
    R Version       : R version 4.3.3 (2024-02-29) -- "Angel Food Cake"

### Steps to reproduce the problem

````markdown
---
format: html
---

```{r}
#| echo: false
#| message: false
message("This message shouldn't print below, but it does")
```

```{r}
#| echo: false
#| warning: false
warning("This warning shouldn't print, and it doesn't")
```
````

![image](https://github.com/rstudio/rstudio/assets/5965649/4f166322-2e24-4b8f-8485-3663783d71d0)

### Describe the problem in detail

`message: false` doesn't seem to do anything when running interactively but `warning: false` does.

### Describe the behavior you expected

I'd expect the `warning` behavior from `message` too.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible in RStudio Desktop 2024.04.0-daily+693 on Windows 11. This is a regression, as it works correctly in version 2023.12.1+402.

**Comment by gtritchie** [comment]
This problem started with build 543 (83ef05e3, 2024-03-06).

The changes that went into that build are:
- https://github.com/rstudio/rstudio/pull/14374 (work around un-expanded quarto template)
- https://github.com/rstudio/rstudio/pull/14368 (allow offline RPC execution when running notebook chunks)

**Comment by ronblum** [comment]
Verified that the previous behavior is restored in RStudio Desktop 2024.07.0-daily+303 on Windows 11, so I'm closing this.

However: When setting "Chunk Output Inline," there are no messages. But when using "Checking Output in Console," the messages show up for both. This was the previous behavior, too. Is this the expected behavior, or is this a bug?

**Comment by kevinushey** [comment]
> However: When setting "Chunk Output Inline," there are no messages. But when using "Checking Output in Console," the messages show up for both. This was the previous behavior, too. Is this the expected behavior, or is this a bug?

This seems like a bug to me. Can you please file as separate issue?
