### ISSUE TITLE
The "sign commit" button should be opt-in

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#14559]
After speaking with @mine-cetinkaya-rundel about teaching Git in RStudio:

> piece of evidence from this semester with 300 students learning R and Git at the same time -- the “sign commit” button is killing us :slightly_smiling_face: People keep pressing it just because it’s there. And then get an error. And then they get frustrated and decide “I can’t do this”.

Signing commits is required in some groups while others don't care and is an opt-in feature for Git itself as well as in other tools like VS Code (`"git.enableCommitSigning": true`)

**Comment by WillTirone** [comment]
I agree! I'm a TA for the course and it generates a lot of non-specific errors that can be tricky to debug.

**Comment by gtritchie** [comment]
We could move this checkbox to Global Options (remove it from the commit popup). It doesn't make sense to me to have it in the commit dialog.

Users can also choose to enable commit signing at the git level (e.g. `git config --global commit.gpgsign true`), leaving RStudio out of it altogether. In that case the current checkbox is misleading; commits will be signed even if the checkbox isn't checked (we don't pass `--no-gpg-sign` when the checkbox is unchecked).

Whatever we do, we'll need to update the user guide to match: https://docs.posit.co/ide/user/2024.04.0/ide/guide/tools/version-control.html#git-commit-signing

**Comment by jthomasmock** [comment]
> We could move this checkbox to Global Options (remove it from the commit popup). It doesn't make sense to me to have it in the commit dialog.

I do like this

**Comment by mine-cetinkaya-rundel** [comment]
Agreed!

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+219 on Windows 11. Checked for persistence and absence of checked and unchecked option. Verified that `--gpg-sign` is added if and only if the option is checked in Git/SVN.
