### ISSUE TITLE
Not getting ggplot2 aesthetics completions if assigning to an object

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14566]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.693
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

```r
# Try to get completion for ggplot2 aesthetics with the script
library(ggplot2)
y <- ggplot(mtcars, aes(<TAB>))

```

### Describe the problem in detail

Nothing shows.

### Describe the behavior you expected

I would expect the same completions as if I tried to complete from this script

```r
 ggplot(mtcars, aes(<TAB>))
```

![image](https://github.com/rstudio/rstudio/assets/52606734/a0daf6c6-9a8f-4c2c-8991-c08b0b6ae503)

Relates to #14399 
Thank you for taking the time to file an issue!  -->

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11.
