### ISSUE TITLE
Autocomplete in `reticulate::repl_python()` wraps valid Python names in backticks (`) 

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#14560]
When in the Python repl `reticulalate::repl_python()`, typing this

```python
import anndata
anndata.__v<tab>
```
autocompletes:
```python 
anndata.`__version__`
```

**Comment by ronblum** [comment]
I can reproduce this in RStudio Desktop 2024.04.0-daily+712 and as far back as 2023.03.2+454, although it worked correctly in version RStudio-2022.07.2+576 (all on Windows 11).

Note: This only occurs with the objects surrounded by underscores.

**Comment by kevinushey** [comment]
Presumedly this is because the completion system is confused and thinks we're in R mode, and so treats `__foo__` as a non-syntactic identifier. Probably a simple fix.

**Comment by t-kalinowski** [comment]
This might be a dup of https://github.com/rstudio/rstudio/issues/4231 ... from 2019?

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+223 on Windows 11. Checked with the original `anndata` example and used `numpy` as well. Also verified that there's no impact on other objects (no underscored).
