### ISSUE TITLE
testthat markers in Build Pane are duplicated

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14564]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0+689
    OS Version      : Windows
    R Version       : 4.3.2 (testthat 3.2.1)

### Steps to reproduce the problem

1. open a package projects with tests with testthat
2. Make sure there are a couple of failing tests
3. Run tests with ctrl + Shift + T
4. Go to issues to see markers

### Describe the problem in detail

The source markers are of failing tests are there twice.

Can't show the full output, but you can see the idea

![image](https://github.com/rstudio/rstudio/assets/52606734/96e65699-7015-4cc6-89a2-812a6528f109)

I think that since they are recorded twice (one at run time, and summary at the end, RStudio catches them twice. A solution would just be to use `unique()` to make sure they are displayed only once.

Happens also in 2023.12. I suspect it is more due to how testthat reports failures than how RStudio handles it.

### Describe the behavior you expected

Each source marker only displayed once.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@olivroy What are the duplicated markers? I can't tell from the image above. Thanks!

**Comment by olivroy** [comment]
I created a minimal repo to explain it more clearly https://github.com/olivroy/minipkg

Steps to reproduce
Clone locally
Run tests with testthat (Ctrl / Cmd + Shift + T) 
![image](https://github.com/rstudio/rstudio/assets/52606734/403d9d8c-14e3-4717-b763-1442eebef342)

Go to Issues in the Build Pane
Notice that the marker to failed test is recorded twice. This is caused by the fact that testthat gives failures as it goes, and gives a summary at the end. I wonder if RStudio could work around this, by only displaying unique occurences of markers

![image](https://github.com/rstudio/rstudio/assets/52606734/d0297252-28c1-4945-bf0d-716bdb3c1643)

**Comment by kevinushey** [comment]
Thanks! I think you're right -- RStudio builds the set of markers for failed tests from the console output emitted by testthat, and so we're accidentally duplicating markers because of the summary displayed at the end.

The error parser lives here:

https://github.com/rstudio/rstudio/blob/bc301a554bb352f32f9cc7dd8de999c739f81b9b/src/cpp/session/modules/build/SessionBuildErrors.cpp#L265-L376

The error parser is invoked on output at the end, e.g.

https://github.com/rstudio/rstudio/blob/bc301a554bb352f32f9cc7dd8de999c739f81b9b/src/cpp/session/modules/build/SessionBuild.cpp#L1739-L1748

I suspect the simplest fix here is to have the testthat error parser stop once it encounters the `Results` line.

**Comment by ronblum** [comment]
@olivroy and @kevinushey I'm not sure if what I'm seeing is the same issue or something else. I'm running [the tests for `dplyr`](https://github.com/tidyverse/dplyr), which has several failures. The failures show as duplicates, grouped by file, which are all duplicated. Is this the bug? If so, it's still present in 2024.11.0-daily+261.pro1.
![Image](https://github.com/user-attachments/assets/d79f8695-36f6-4790-a705-8a5242f5ed75)

**Comment by olivroy** [comment]
I am also seeing this. I am not sure the fix worked..

**Comment by ronblum** [comment]
@olivroy Oh this is the bug! I guess I knew what I was doing without realizing it. 🙂

**Comment by ronblum** [comment]
Verified fixed in RStudio Desktop 2024.11.0-daily+269 on Windows 11, with `devtools` version 2.4.5.
