### ISSUE TITLE
Replicate RStudio's Markdown canonicalization outside of RStudio

### ISSUE THREAD

**Issue by salim-b** [rstudio/rstudio#14570]
This is actually more of a question than an actual RStudio feature request. I tried to ask this [on forum.posit.co](https://forum.posit.co/t/pandoc-command-to-replicate-rstudios-markdown-canonicalization/185524) ten days ago, but didn't receive an answer. Hence I dare to make my request here.

---

I like and use RStudio’s Markdown [canonicalization](https://rstudio.github.io/visual-markdown-editing/markdown.html#canonical-mode) feature a lot. If I understand correctly, it is implemented by basically sending the document to a [Pandoc](https://pandoc.org/) "round trip" on save (plus some additional, [at times buggy](https://github.com/rstudio/rstudio/issues/13194) special processing, I think).

What I'd like to be able to do is **replicate the part of the canonicalization which is done via the Pandoc CLI**. Could you provide the exact `pandoc` command that is used for this?

**Comment by kevinushey** [comment]
I believe this happens in Quarto. The associated source code is here:

https://github.com/quarto-dev/quarto/blob/f9edec34e53817e9c9f73cb349f524a82bcc6474/packages/editor/src/editor/editor.ts#L771-L791

You can try tracing the code throughout there, e.g.

https://github.com/quarto-dev/quarto/blob/f9edec34e53817e9c9f73cb349f524a82bcc6474/packages/editor/src/pandoc/pandoc_converter.ts#L96-L152

**Comment by salim-b** [comment]
Thank you very much for the hints, @kevinushey! See https://github.com/quarto-dev/quarto-cli/discussions/9476 for a follow-up Quarto feature request (and the result of my attempt to reproduce Quarto's MD canonicalization).
