### ISSUE TITLE
Right-clicking on commented text in editor does not produce context menu

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14575]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0 Build 729
    OS Version      : macOS Sonoma 14.4.1
    R Version       : 4.3.3

### Steps to reproduce the problem

Create an R document containing a comment; for example,

```
# Hello, world!
```

Then, try to right-click on one of the words in that comment.

### Describe the problem in detail

No context menu is shown; nothing seems to happen.

### Describe the behavior you expected

The default context menu should be shown.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note:
- Reproduced on Windows 11, as well.
- Around for a while, e.g. in RStudio Desktop 2023.03.2+454.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+116 on Windows 11.
