### ISSUE TITLE
Inconsisent behaviour for new file across different menus

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#14589]
I'm on Version 2024.04.0+735 (2024.04.0+735).

There are three ways of getting a new Quarto document:

1. Top Menu: File > New File > Quarto Document... -> Untitled1.qmd with document with sections, code, etc.
2. Top Menu: File > New File > Quarto Document... > Create Empty Document -> Untitled1.qmd with no content but a YAML with title, format, and editor fields.
3. Files Pane: New Blank File > Quarto Doc... -> you get to specify the name but the default is UntitledQMD.qmd and it's actually blank as intended, but it's literally blank, not even a YAML.

There are some notable inconsistencies that constantly make me think "last time I did this there was something else here", but I think the issue is that there are different ways of doing the same thing, each with a slightly different experience.

I _think_ the menus make a distinction between "File" and "Document" as concepts? I'm not sure. But the distinction isn't clear to a new (or experienced) user. I'd suggest keeping the terminology consistent -- either both should call them File or Document (I suggest File but I'm actually good with either).

Further suggestions to make the experience similar across various methods of getting a new file:

- Both menus should say "Quarto Document..." (not "Quarto Doc...", which is unclear)
- Both menus should list the types of files in the same order
- In the New Blank File menu either all options should have ... or none, they all result in a pop-up menu for filename so it doesn't make sense for some to have them and some not
- New File menu should also pop a window that allows the user to specify a name
  - That pop up window should be called "Create a New qmd file in Current Directory"
  - The default filename should be either Untitled1.qmd or whatever the next number is based on saved/unsaved open files or if that's impossible it should be Untitled.qmd (not UntitledQMD.qmd)
- All menus should result in a file with at least a YAML -- blank file would have no content otherwise and non-blank file would have the usual boilerplate.

If there's agreement that this streamlining is useful, I'm happy to write up in further detail what each step should look like, and for other types of files too (not just qmds.)

**Comment by jthomasmock** [comment]
> If there's agreement that this streamlining is useful, I'm happy to write up in further detail what each step should look like, and for other types of files too (not just qmds.)

This would be awesome if you're up for it! We'd like to target this for CH.

**Comment by gtritchie** [comment]
Moving to next next release; no way we'll get to this for 2024.07.

**Comment by kevinushey** [comment]
> I think the menus make a distinction between "File" and "Document" as concepts? I'm not sure. But the distinction isn't clear to a new (or experienced) user. I'd suggest keeping the terminology consistent -- either both should call them File or Document (I suggest File but I'm actually good with either).

IMHO, the difference here is okay, since there are multiple kinds of Quarto files (documents, presentations, etc) so just using Quarto File is somewhat ambiguous. As long as we're consistently using "document" for file-types which we open as documents, we should avoid any confusion.

> New File menu should also pop a window that allows the user to specify a name 

The behavior here is intentionally different -- the New File menu creates new unsaved files (nothing persisted on disk), whereas the Files pane is used to first create a file with some associated name, and then edit that file in RStudio. Is there something we could / should do to make this more clear?

The PR in https://github.com/rstudio/rstudio/pull/15258 takes in all of the other feedback -- thanks!

**Comment by ronblum** [comment]
1) For the Files Pane -> New File -> Quarto Document, I think that the YAML should use `format: html` instead of `output: html_document`.

**Comment by ronblum** [comment]
Verified the changes made to increase consistency. My only concern is the above:

<kbd>File -> New File -> Quarto Document -> Create Empty Document</kbd>
creates a tab containing 
```
---
title: "Untitled"
format: html
editor: visual
---
```

But starting from the Files Pane,
<kbd>New File -> Quarto Document</kbd>
creates a file with the contents
```
---
title: "Untitled"
output: html_document
---
```

The latter is using R Markdown terminology. Quarto recognizes it, but I think that the files should be identical, using the first template which has Quarto terms.

**Comment by kevinushey** [comment]
That's a good catch; I agree the template in the second example should match the first.

**Comment by ronblum** [comment]
Verified file format change in RStudio Desktop 2024.11.0-daily+298 on Windows 11.
