### ISSUE TITLE
Update Electron for 2024.09 (formerly 2024.07)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14582]
RStudio 2024.04 ships with Electron v28; this reaches EOL 2024-Jun-11.

For 2024.07 we should update to Electron v30 (along with the associated npm-based tooling).

<img width="722" alt="screenshot of a table showing electron versions and their support dates" src="https://github.com/rstudio/rstudio/assets/10569626/d5a5ee93-6556-4ee1-9e47-93f54c96d433">

**Comment by ronblum** [comment]
Verified in <kbd>Help -> About</kbd> that we're using Electron 30.0.2, in RStudio Desktop 2024.07.0-daily+116 on Windows.

**Comment by petetronic** [comment]
Further updated to Electron 30.4.0 in https://github.com/rstudio/rstudio/pull/15166

**Comment by MariaSemple** [comment]
Should this issue be closed?

**Comment by ronblum** [comment]
Funny, I was just looking at this! Verified in RStudio Desktop 2024.09.0+375 on Windows 11.
