### ISSUE TITLE
ggplot2 aesthetics missing from geom_boxplot()

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14586]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0 Build 729
    OS Version      : macOS Sonoma 14.4.1
    R Version       : 4.4.0

### Steps to reproduce the problem

Request completions in this code:

```
library(ggplot2)
geom_boxplot(aes())
```

### Describe the problem in detail

A number of aesthetics are missing:

<img width="449" alt="Screenshot 2024-04-23 at 4 15 15 PM" src="https://github.com/rstudio/rstudio/assets/1976582/737c5b89-593b-4f35-b114-33449a928a2b">

### Describe the behavior you expected

We should see required aesthetics like `x` and `y`; for example:

<img width="463" alt="Screenshot 2024-04-23 at 4 15 47 PM" src="https://github.com/rstudio/rstudio/assets/1976582/1e7b6bd4-7c2d-485a-a093-71e76f95c98c">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11.
