### ISSUE TITLE
Comments in R files are no longer properly highlighted if they look like `#|`

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14592]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.693
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

1. Open R file
2. Paste the following code

```r
# | a ad
# | 
#---------------

#' Resolve
#' 
#' @param name description
fn <- function(x) {
  
}


```

### Describe the problem in detail

The comment is not properly highlighted.
![image](https://github.com/rstudio/rstudio/assets/52606734/52296edb-7a0a-4331-82a3-287a0513f083)

### Describe the behavior you expected

Correct highliting of R comment.

Also if your comment ends with `|`, it breaks syntax highlighting of roxygen comments

![image](https://github.com/rstudio/rstudio/assets/52606734/4707f397-36b7-4e4f-89c2-111ec5a0b4b2)

I would expect a regular R comment ending with | to not break syntax highlighting in R files (I suspect it may be due to enhancement of highlighting in Quarto files, which is awesome.

I just noticed this while working on gt, since they have a logo on top of each file

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible. Note that the problems occurred in different releases:
- The incorrect comment formatting appears in 2023.12.
- The incorrect roxygen formatting appears in 2024.04.

**Comment by yuanjp217** [comment]
I experience this issue as well. Here is the erroneous highlighting:
![comment_error](https://github.com/rstudio/rstudio/assets/55602189/1f30eb0b-42ea-42e7-85c1-f808315eb689)

Further, attempting to comment out using ctrl+shift+c (Windows) or cmd+shift+c (Mac) will insert a HTML style comments ("") instead of R-style hashtags ("#")
![comment_error2](https://github.com/rstudio/rstudio/assets/55602189/737ddcb2-81c7-489f-8d6e-263a832f95f5)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+229 on Windows 11.
Checked
- R file
- R Markdown and Quarto documents in both source and visual modes.

R file:
![Image](https://github.com/rstudio/rstudio/assets/31009952/6bf13f63-a5fd-4513-be59-1fddd0782c58)

Quarto document:
![Image](https://github.com/rstudio/rstudio/assets/31009952/4871b2f1-05fb-47fe-858a-35e4e2922817)

**Comment by ronblum** [comment]
@yuanjp217 Can you open a new issue regarding the types of comments? Thanks!
