### ISSUE TITLE
avoid space after package name in install packages message

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14608]
<img width="578" alt="Screenshot 2024-04-29 at 1 57 33 PM" src="https://github.com/rstudio/rstudio/assets/1976582/be9b402d-9c54-409e-886d-7ea942ba1251">

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+116 by including `library` statements for uninstalled packages, in the R chunk of a Quarto file.
