### ISSUE TITLE
Git: Should the latest release tag '2023.12.1+402' be 'v2023.12.1+402'

### ISSUE THREAD

**Issue by HenrikBengtsson** [rstudio/rstudio#14602]
I scan the git tags of this repo to detect new releases and I spotted that the tag for most recent release does _not_ have a `v` prefix;

```sh
$ git tag | grep -E "202[3-4]" 
2023.12.1+402
v2023.03.0+386
v2023.03.1+446
v2023.03.2+454
v2023.06.0+421
v2023.06.1+524
v2023.06.2+561
v2023.09.0+463
v2023.09.1+494
v2023.12.0+369
```

Is that a mistake, or an intentional move?  If a mistake, I guess it's an easy fix.

**Comment by ronblum** [comment]
@HenrikBengtsson Thank you for raising this! I brought this up internally to see what the upshot is.

**Comment by cm421** [comment]
The missing `v` prefix was not intentional, thank you for calling it out @HenrikBengtsson! I've fixed the tag now.

**Comment by petetronic** [comment]
Thanks @cm421 I see the conforming v prefixed tag now there:
```
git fetch --all
git tag | grep -E "2023.12.1"   
```

```
2023.12.1+402
v2023.12.1+402
```

**Comment by cm421** [comment]
Closing as fixed
