### ISSUE TITLE
Review outstanding milestone items

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14612]
https://github.com/rstudio/rstudio/milestone/36
https://github.com/rstudio/rstudio/milestone/37
https://github.com/rstudio/rstudio/milestone/47

**Comment by petetronic** [comment]
We'll review CH at the end of the release, though the other milestones now look like they are 100% done so we can close this issue.

**Comment by petetronic** [comment]
We'll review CH at the end of the release, though the other milestones now look like they are 100% done so we can close this issue.
