### ISSUE TITLE
RStudio is executing RMarkdown / Quarto chunks very slowely when working on a network drive, especially when inside a project.

### ISSUE THREAD

**Issue by marianklose** [rstudio/rstudio#14619]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0+735 "Chocolate Cosmos" Release (a00d0e775dbc93e0d79a1bf474e3e8e8de677383, 2024-04-24) for windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0+735 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.3.450
    OS Version      : x86_64-w64-mingw32 (windows 10)
    R Version       : R version 4.3.0 (2023-04-21 ucrt) (Already Tomorrow)

### Steps to reproduce the problem

1) Create test.qmd (or test.Rmd) file with the following single chunk of code. Also create test.R with the same code, so just without the {r} chunk markup. 

````
```{r}
# define start time
start_time <- Sys.time()

# dummy code
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1
1+1

# define end time
end_time <- Sys.time()

# calculate elapsed time
difftime(end_time, start_time, units = "secs")
```
````

2) Open test.qmd  and execute chunk in RStudio within various scenarios. Compare difftime (time to execute chunk)
a) local drive, no project
`test.qmd:   Time difference of 0.08611608 secs`
`test.R:     Time difference of 0.01601291 secs`
b) local drive, within project
`test.qmd:   Time difference of 0.08609295 secs`
`test.R:     Time difference of 0.01690793 secs`
c) mapped / shared network drive, no project
`test.qmd:   Time difference of 0.26181581 secs`
`test.R:     Time difference of 0.01711988 secs`
d) mapped / shared network drive, within project
`test.qmd:   Time difference of 1.60444383 secs`
`test.R:     Time difference of 0.01676202 secs`

### Describe the problem in detail

We can see that while the execution of `test.R` is nearly unaffected by both the project/no project setting and the shared / local drive setting, the `test.qmd` chunk execution is highly impacted. We can observe a nearly 20-fold longer execution time for the chunk inside `test.qmd` when comparing the _d) mapped / shared network drive, within project_ scenario with the _a) local drive, no project_ or _b) local drive, within project_ scenarios. The same behaviour is reproducible for `test.Rmd` instead of `test.qmd`.

This issue is related to https://github.com/rstudio/rstudio/issues/8034 (which was closed with the request to open a new issue if there are still problems) and https://github.com/rstudio/rstudio/issues/10417.  

### Describe the behavior you expected

I would expect the same execution time for the chunk inside `test.qmd` no matter what scenario (a/b/c/d) we are in. To me, this behaviour makes it very hard to use projects and/or Quarto or RMarkdown files when on a mapped / shared network drive.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
See also #10417.

**Comment by nschan** [comment]
I am experiencing similar problems. I suspect they are related to the use of `renv`, are you using `renv` @marianklose ? For me there is a noticable increase in performance after `renv::deactivate()`.

**Comment by marianklose** [comment]
Hi @nschan, thanks for your suggestion. For me it is actually not related to `renv`. But I haven't tested if using `renv` is slowing down the process even more.

```
> renv::status()
This project does not appear to be using renv.
Use `renv::init()` to initialize the project.
```

**Comment by kevinushey** [comment]
@marianklose: would you be willing to help us collect some more information? There is a Windows utility called [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon), which can be used to check what system calls a particular process is making. Some instructions:

1. First, start RStudio, and open `test.qmd` to prepare for running your example code.
2. Open `procmon`, and use the following filter to capture RStudio's R session activity:

<img width="570" alt="Screenshot 2024-05-29 at 4 14 21 PM" src="https://github.com/rstudio/rstudio/assets/1976582/66d6f74d-9e0c-43d2-ba7c-5a228a0e3960">

3. Run the code from your example. You should see a flurry of filesystem operations in the process monitor.
4. Use File -> Save to save the log to a file, and share that with us.

**Comment by marianklose** [comment]
@kevinushey: Sure, I am happy to help. I am currently on my private windows machine at home connected to my university shared network drive. I am conducting these tests for the two extreme scenarios regarding runtime: a) local drive, no project and d) mapped / shared network drive, within project. Let me know if you also need b) and d).

Here is a screenshot of my `procmon` filter (I unchecked the other filters):

![image](https://github.com/rstudio/rstudio/assets/132135131/63fece8f-4d17-40c1-b75d-5de19865e476)

I first opened the project, then the .qmd and then opened `procmon` and applied the filter. After applying the filter I've waited for 10 seconds before I execute the chunk. I saved the log.csv and log.PML (which I couldn't upload, let me know if you need it).

## a) local drive, no project

- `Time difference of 0.588882 secs`
- log.csv: [Logfile_case_a.CSV](https://github.com/rstudio/rstudio/files/15494801/Logfile_case_a.CSV)

## d) mapped / shared network drive, within project.


- The run time on my private PC connected to the shared network is even worse: `Time difference of 56.29842 secs`
- log.csv: [Logfile_case_d.CSV](https://github.com/rstudio/rstudio/files/15494748/Logfile_case_d.CSV)

Hope that helps! Let me know if you need anything else.

**Comment by kevinushey** [comment]
Thanks! This is very useful. I think this confirms some of our suspicions -- it looks like filesystem access is fairly slow on the network filesystem you're using, and since chunk execution will somewhat eagerly read and write files within the project's `.Rproj.user` folder, code execution gets slowed down.

I have some changes in https://github.com/rstudio/rstudio/pull/14765 that may help for future builds of RStudio, but I feel like the best way to fix this would be to have some way to have the `.Rproj.user` folder's location customized, so you could place it on a faster filesystem (e.g. perhaps a local filesystem). This could have downsides; e.g. your session state wouldn't be preserved if you opened that project on a different machine, but that might be a tradeoff you're willing to make?

**Comment by marianklose** [comment]
Thanks for getting back to me.

> it looks like filesystem access is fairly slow on the network filesystem you're using

Indeed, it will definitely depend on the access speed to the network drive. At home I have a way slower chunk execution time (56 sec) than on my university machine (1.7 sec). On both machines I work on a mapped network drive, but apparently the access speed is higher at university. I can later also share the speed at home, but that's kind of an average writing/reading speed at the university (to and from the network drive):

![image](https://github.com/rstudio/rstudio/assets/132135131/d2f77b83-e685-4230-ac7a-68255113f8f1)

I don't have a reference if that's fast or slow but this results in 1.7 sec execution time within a project. 

> I have some changes in https://github.com/rstudio/rstudio/pull/14765 that may help for future builds of RStudio, but I feel like the best way to fix this would be to have some way to have the .Rproj.user folder's location customized, so you could place it on a faster filesystem (e.g. perhaps a local filesystem). This could have downsides; e.g. your session state wouldn't be preserved if you opened that project on a different machine, but that might be a tradeoff you're willing to make?

Sounds reasonable to me. Personally, the potential downsides are perfectly fine with me. I mainly work with projects to use `here::here()` and whenever I work on packages. Preserving the session state is not really a priority to me.

**Comment by kevinushey** [comment]
Are you able to try a recent daily build of RStudio? We recently implemented some optimizations that may help improve performance here:

https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2024.07.0-daily-180.exe

I'm also curious if using "Chunk Output in Console" makes a difference on execution performance. From the gear icon in the editor toolbar for the .Rmd document you're editing:

<img width="283" alt="Screenshot 2024-05-31 at 9 14 43 AM" src="https://github.com/rstudio/rstudio/assets/1976582/de6c875f-434d-492d-a63f-044049824498">

**Comment by marianklose** [comment]
I've just installed the daily build and I have the following runtime (for the .qmd inside the project on the shared network drive):

```
Time difference of 21.74336 secs
```
so it seems to improve the situation (compared to the 50+ seconds with the previous build), but 22 seconds is still pretty slow. Now using "Chunk Output in Console" speeds up the process signficantly (even when being inside a project):

```
Time difference of 0.006109953 secs
```

Thanks for pointing this out, maybe this solves already quite some speed issues. But I am wondering why there is such a significant delay when using the inline output option. There must be some kind of inefficient reading/writing process involved. This is also related to my previous question:

> I was wondering that even without a project the output from a chunk (graphics, tables etc.) is being preserved even if I close the file and Rstudio and then reopen it again

Would it be possible to turn off preserving the chunk output for the future (so it doesn't have to be written somewhere when executing a chunk)? Maybe then we could use the inline output option (which is preferred) even with a somewhat slow network drive?

**Comment by ronblum** [comment]
The latest daily builds of the release in progress, [Cranberry Hibiscus 2024.07.0](https://dailies.rstudio.com/rstudio/cranberry-hibiscus/), have a fix for this. If anyone is willing to try it out, it would be greatly appreciated. Plese note that the daily builds are meant for testing purposes only, not production.

**Comment by gtritchie** [comment]
> The latest daily builds of the release in progress ... have a fix for this

Note that the fix requires configuring the project to store `.Rproj.user` somewhere other than the cloud drive, see https://github.com/rstudio/rstudio/pull/14875.

**Comment by marianklose** [comment]
> The latest daily builds of the release in progress, [Cranberry Hibiscus 2024.07.0](https://dailies.rstudio.com/rstudio/cranberry-hibiscus/), have a fix for this. If anyone is willing to try it out, it would be greatly appreciated. Plese note that the daily builds are meant for testing purposes only, not production.

Thanks for getting back to this. I am happy to give it a test. Without the fix (new daily build) the estimation time for the chunk inside a project is:

```
Time difference of 1.708584 secs
```

After installing the Cranberry Hibiscus 2024.07.0 daily build and adjusting the project settings (`.Rproj.user` moved to local C:/ drive) accordingly the estimation time is:

```
Time difference of 0.219836 secs
```

So we have a substantial improvement (nearly 10-fold) in execution times. Thanks a lot for that! It is not perfectly matching the excution time which we have when the .qmd is also located on the C:/ drive but I personally can live with that.

Thank you!

**Comment by ronblum** [comment]
@marianklose Thank you very much for testing the execution time improvement!
