### ISSUE TITLE
RStudio doesn't recognize a test file if tests use BDD testing language

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#14627]
If tests are written in [BDD testing language](https://testthat.r-lib.org/reference/describe.html), RStudio think it's a script to be sourced, and not tests to be run.

If you want to reproduce this, open a test file from Posit's own [`{fs}` package](https://github.com/r-lib/fs/blob/main/tests/testthat/test-path.R):

<img width="984" alt="Screenshot 2024-04-30 at 14 13 41" src="https://github.com/rstudio/rstudio/assets/11330453/ef592005-b2db-42c2-a602-f47ff13e69a8">

### RStudio version

<img width="606" alt="Screenshot 2024-05-01 at 14 15 08" src="https://github.com/rstudio/rstudio/assets/11330453/19e77777-af89-4793-bd6d-32f786a68ad3">

**Comment by olivroy** [comment]
I noticed this too.

To circumvent. I just add this to the bottom

```r
test_that("nothing", {
  expect_true(TRUE)
})

and the run tests button appears!

**Comment by ronblum** [comment]
@IndrajeetPatil Thank you for raising this and  @olivroy for the workaround! I can reproduce this in RStudio Desktop 2023.03.2+454 on Windows 11, so this has been around for a while. This might've been by design in the original architecture. I'll mark this for review.
