### ISSUE TITLE
RSTUDIO_USE_SYSTEM_YAML_CPP variable is not honored

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rstudio#14629]
Verify fixed in:
- [ ] Patch: 2024.04.2
- [ ] Release: 2024.07.0

---

### System details

Does not apply, this is about the build process.

### Steps to reproduce the problem

Build with `-DRSTUDIO_USE_SYSTEM_YAML_CPP=Yes`.

### Describe the problem in detail

cmake tries to download yaml-cpp from GitHub.

### Describe the behavior you expected

The build process should use the system yaml-cpp instead, which was what happened in the previous version. [This commit](https://github.com/rstudio/rstudio/commit/b7b0433ac7d976ff44333d102fa96bee8ce01c53) introduced the issue.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kbipinkumar** [comment]
cmake gives following warning

```
-- Packaging RStudio for Arch Linux
-- Configuring done (10.9s)
-- Generating done (0.2s)
CMake Warning:
  Manually-specified variables were not used by the project:

    RSTUDIO_USE_SYSTEM_YAML_CPP
```

**Comment by gtritchie** [comment]
Note, I initially merged this into the wrong branch (rel-chocolate-cosmos); I have backed that out and merged it into main via  04de8ca8b83dcc7fee9fd65e6ef58c372489d5ef.

**Comment by ronblum** [comment]
@Enchufa2 This is fixed in both the release currently in development, and a Chocolate Cosmos patch that we're working on. Would you be willing to try this out to see if it's working?

**Comment by Enchufa2** [comment]
Sure. Should I just apply e7bc203 to the current release? Or do I need something else?

**Comment by Enchufa2** [comment]
I tried with the patch above, builds are fine: https://koji.fedoraproject.org/koji/taskinfo?taskID=118249565

**Comment by ronblum** [comment]
Awesome @Enchufa2 , thank you!
