### ISSUE TITLE
Rstudio installation instructions for RHEL are broken

### ISSUE THREAD

**Issue by dvg-p4** [rstudio/rstudio#14632]
### System details

    RStudio Edition : Server
    RStudio Version : Trying to get the latest (v2024.04.0+735)
    OS Version      : Rocky 8 Linux
    R Version       : N/A

### Steps to reproduce the problem

* Go to https://posit.co/download/rstudio-server/
* Select "Red Hat / CentOS"
* Scroll down to "Step 3: Install RStudio Server"

### Describe the problem in detail

The instructions displayed show:

```bash
wget (rstudio.open_source.stable.server.installer.redhat7_64.url???)
sudo yum install (rstudio.open_source.stable.server.installer.redhat7_64.basename???)
```

which looks an awful lot like some sort of templating error.

<img width="792" alt="image" src="https://github.com/rstudio/rstudio/assets/106110177/42ff3eca-5fcd-49f2-9411-7987f89b3ecd">

### Describe the behavior you expected

Correct, non-broken links and filenames

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- N/A I have installed the latest version of RStudio, and confirmed that the issue still persists
  - this is my goal here
- N/A If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dvg-p4 Thank you for raising this! The option was supposed to be removed, and looks like that only partly took place. I'll ask internally to get this fixed.

Also you probably already know this, but just to make sure: Since you're using Rocky Linux 8, the instructions for the build that you want is under Red Hat 8.

**Comment by ronblum** [comment]
Ref: internal request MKTG-4634.

**Comment by dvg-p4** [comment]
...yup, I definitely realized that, totally didn't forget the difference between the numbers 7 and 8. thanks!

**Comment by ronblum** [comment]
@dvg-p4 You made my morning--I'm literally LOLing. 😄

**Comment by ronblum** [comment]
@dvg-p4 Fixed--thank you for raising this!
