### ISSUE TITLE
Provide a config file for setting electron/chromium flags

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14641]
From a community post: https://forum.posit.co/t/setting-electron-flags-needed-when-running-on-wayland/183487

---

I'm running RStudio on Wayland, and because I have fractional scaling enabled, I need to pass some Electron flags to avoid blurry rendering (as described e.g. in [GUI text and icons blurry with fractional scaling in Ubuntu ](https://forum.posit.co/t/gui-text-and-icons-blurry-with-fractional-scaling-in-ubuntu/140536)):

```
--ozone-platform-hint=auto
--enable-features=WaylandWindowDecorations
--ozone-platform=wayland
```

Some programs read `~/.config/electron-flags.conf`, but RStudio seems to ignore this file. Other Electron-based programs like Visual Studio Code use their own Electron config file (`code-flags.conf`), so I was wondering if something like this exists for RStudio.

**Comment by ronblum** [comment]
Thinking out loud: As far as I can tell, the `*-flags.conf` files are from Arch Linux. So I think that we just added an Arch Linux convention to other Linuxes, MacOS, and Windows? It might be worth documenting.

**Comment by ronblum** [comment]
QA note from PR:
- Linux & MacOS: `~/.config/rstudio/electron-flags.conf` and `~/.config/electron-flags.conf`
- Windows: `%appdata%\RStudio\electron-flags.conf` and `%appdata%\electron-flags.conf`

**Comment by kevinushey** [comment]
> Thinking out loud: As far as I can tell, the *-flags.conf files are from Arch Linux. So I think that we just added an Arch Linux convention to other Linuxes, MacOS, and Windows? It might be worth documenting.

Right -- or at least, as I understand it, this is a convention that's been introduced with the Arch Linux builds of Electron. We did document this in the NEWS file; is that sufficient? I don't think these will be very commonly used on other platforms.

**Comment by ronblum** [comment]
Verified in 2024.07.0-daily+310 (and a few other builds).
