### ISSUE TITLE
Intermittent crash in RStudio's DataViewer when observed object gets free while it's being observed

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#14643]
Found from crash dumps and so don't have a reproducible case yet but have narrowed down the code:

It crashes here in [this Rf_getAttribute call](https://github.com/rstudio/rstudio/blob/1d7af27196412a991eb942cbb64e6a6aa737dfb5/src/cpp/session/modules/data/DataViewer.cpp#L1074)

Note that currently the `observedSEXP` is not protected by a reference. The RStudio DataViewer.cpp code used to look only at the pointer itself to see if it changed, but now looks into the contents of the pointer to see if anything in the object has changed. To do that, we need to protect it with a reference so it can't get freed.  

Here's a [a comment] (https://github.com/rstudio/rstudio/blob/1d7af27196412a991eb942cbb64e6a6aa737dfb5/src/cpp/session/modules/data/DataViewer.cpp#L293C1-L294C1) at roughly the spot where the reference should get added.

**Comment by jeffvroom** [comment]
Customer ticket - 102051

**Comment by ronblum** [comment]
Updated support ticket.

**Comment by ronblum** [comment]
Changing milestone: The change for this is in Cranberry Hibiscus, but it likely won't get external verification one way or the other till the Kousa Dogwood timeframe.

**Comment by ronblum** [comment]
Issue has been resolved.
