### ISSUE TITLE
history doesn't save commands when they are sourced

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#14651]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2024.04.0+735 (2024.04.0+735)
    OS Version      :  macOS Monterey 12.7.4
    R Version       :  4.4.0

### Steps to reproduce the problem

Add some commands to the source pane. 
Click on "source" to run them.

### Describe the problem in detail

I think this is new (so this is a bug rather than a feature request), though I'm not sure.  The history pane just shows 

    source("~/.active-rstudio-document", echo=TRUE)

instead of showing the commands that were sourced.

### Describe the behavior you expected

I'd like to see the commands.  I typically edit the script multiple times, and it is more useful to see the progression of changes than to see the fact that I sourced it.

I get the behaviour I'd like by highlighting the source file, then hitting Cmd-Enter, so there's an easy workaround.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dmurdoch Thank you for raising this! This is the expected behavior--it works the same way in previous releases, such as RStudio Desktop 2023.03.2+454 on Windows 11. So I'll change this to a feature request.

**Comment by kevinushey** [comment]
The behavior of the Source button changes depending on the last "type" of source you did. If you click the small down arrow next to the Source button, you should see Source and Source with Echo:

![image](https://github.com/rstudio/rstudio/assets/1976582/5d4cb4a4-a348-4f2b-bb00-0d69c5c719ae)

If you use Source with Echo, you should see `source(<path>, echo=TRUE)`, and so R commands and output are echoed as they're executed. If you later click Source again, that "preference" is used to infer that you want to source with echo again. Does that describe what you're seeing?

The fact that the behavior of Source here is "sticky" without us presenting any UI here is a bit confusing; I think that is worth fixing up.

**Comment by dmurdoch** [comment]
@kevinushey :  I think I have noticed similar sticky choice behaviour elsewhere.  I'm surprised I never noticed the missing history issue before.

If this feature request is implemented, I think it would be reasonable to only add history for "Source with echo".
