### ISSUE TITLE
Error Starting R | Can't open RStudio since updating to 2024.04.0

### ISSUE THREAD

**Issue by HuEaSi** [rstudio/rstudio#14653]
### System details

    RStudio Edition : RStudio 2024.04.0+735 
    RStudio Version :   "Chocolate Cosmos "
    OS Version      :  Microsoft Windows 11 Home Version 10.0.22631 Build 22631

    R Version       :  4.4.0

### Steps to reproduce the problem

That error message comes everytime I open RStudio.

### Describe the problem in detail

I updated by RStudio one week ago to the newest version.

### Describe the behavior you expected

I just expected my r file to open normaly like always. 

### What I did so far to solve it

- Reinstall R and R Studio multiple times
- Resetting RStudio Desktop's State by deleting folder in %appdata%

### RStudio Version

RStudio 2024.04.0+735 "Chocolate Cosmos " (a00d0e77, 2024-04-24) for windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0+735 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 3221225477. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*C:/Users/duchu/AppData/Local/RStudio/log/rsession-duchu.log*

```
durch den Hostcomputer abgebrochen) [request-uri: /grid_resource/gridviewer.html?obj=studidata&max_rows=1000&max_cols=50&env=.GlobalEnv]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide-os-windows\rel-chocolate-cosmos\src\cpp\session\http\SessionHttpConnectionImpl.hpp:156; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide-os-windows\rel-chocolate-cosmos\src\cpp\session\http\SessionHttpConnectionImpl.hpp:161
2024-05-03T20:06:33.064176Z [rsession-duchu] ERROR system error 5 (Zugriff verweigert); OCCURRED AT auto __cdecl rstudio::core::system::ChildProcess::terminate::<lambda_0837bcc20cbf20264fbd4fbbbf2e36d5>::operator ()(void) const src/cpp/core/system/Win32ChildProcess.cpp:294; LOGGED FROM: void __cdecl rstudio::core::system::ProcessSupervisor::terminateAll(void) src/cpp/core/system/Process.cpp:379
2024-05-03T20:06:33.064176Z [rsession-duchu] ERROR system error 5 (Zugriff verweigert); OCCURRED AT auto __cdecl rstudio::core::system::ChildProcess::terminate::<lambda_0837bcc20cbf20264fbd4fbbbf2e36d5>::operator ()(void) const src/cpp/core/system/Win32ChildProcess.cpp:294; LOGGED FROM: void __cdecl rstudio::core::system::ProcessSupervisor::terminateAll(void) src/cpp/core/system/Process.cpp:379

```
                

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report]
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![Screenshot 2024-05-06 154154](https://github.com/rstudio/rstudio/assets/169027410/6e10a35d-e48f-45d1-8200-2738d06caa8e)
![Screenshot 2024-05-06 154159](https://github.com/rstudio/rstudio/assets/169027410/118778c5-882a-40d4-92b4-847faf64c834)

**Comment by ronblum** [comment]
@HuEaSi Thank you for raising this! What happens if you use a different version of R, like 4.3.3?

**Comment by HuEaSi** [comment]
Thank you for your suggestion! I didn't think of that. I tried two R-Studio versions now, even with a different version of R. With both cases I got the same error report.

RStudio 2023.12.1+402 "Ocean Storm " (4da58325, 2024-01-29) for windows 
+ R 4.4.0
&
RStudio 2023.12.0+369 "Ocean Storm " (33206f75, 2023-12-17) for windows
+ 4.3.3

**## R Session Startup Failure Report**

### RStudio Version

RStudio 2023.12.0+369 "Ocean Storm " (33206f75, 2023-12-17) for windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 3221225477. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*C:/Users/duchu/AppData/Local/RStudio/log/rsession-duchu.log*

```
durch den Hostcomputer abgebrochen) [request-uri: /grid_resource/gridviewer.html?obj=studidata&max_rows=1000&max_cols=50&env=.GlobalEnv]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide-os-windows\rel-chocolate-cosmos\src\cpp\session\http\SessionHttpConnectionImpl.hpp:156; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide-os-windows\rel-chocolate-cosmos\src\cpp\session\http\SessionHttpConnectionImpl.hpp:161
2024-05-03T20:06:33.064176Z [rsession-duchu] ERROR system error 5 (Zugriff verweigert); OCCURRED AT auto __cdecl rstudio::core::system::ChildProcess::terminate::<lambda_0837bcc20cbf20264fbd4fbbbf2e36d5>::operator ()(void) const src/cpp/core/system/Win32ChildProcess.cpp:294; LOGGED FROM: void __cdecl rstudio::core::system::ProcessSupervisor::terminateAll(void) src/cpp/core/system/Process.cpp:379
2024-05-03T20:06:33.064176Z [rsession-duchu] ERROR system error 5 (Zugriff verweigert); OCCURRED AT auto __cdecl rstudio::core::system::ChildProcess::terminate::<lambda_0837bcc20cbf20264fbd4fbbbf2e36d5>::operator ()(void) const src/cpp/core/system/Win32ChildProcess.cpp:294; LOGGED FROM: void __cdecl rstudio::core::system::ProcessSupervisor::terminateAll(void) src/cpp/core/system/Process.cpp:379

```

**Comment by HuEaSi** [comment]
> @HuEaSi Thank you for raising this! What happens if you use a different version of R, like 4.3.3?

Thank you for your suggestion! I didn't think of that. I tried two R-Studio versions now, even with a different version of R. With both cases I got the same error report.

RStudio 2023.12.1+402 "Ocean Storm " (4da58325, 2024-01-29) for windows 
+ R 4.4.0
&
RStudio 2023.12.0+369 "Ocean Storm " (33206f75, 2023-12-17) for windows
+ 4.3.3

**## R Session Startup Failure Report**

### RStudio Version

RStudio 2023.12.0+369 "Ocean Storm " (33206f75, 2023-12-17) for windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 3221225477. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*C:/Users/duchu/AppData/Local/RStudio/log/rsession-duchu.log*

```
durch den Hostcomputer abgebrochen) [request-uri: /grid_resource/gridviewer.html?obj=studidata&max_rows=1000&max_cols=50&env=.GlobalEnv]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide-os-windows\rel-chocolate-cosmos\src\cpp\session\http\SessionHttpConnectionImpl.hpp:156; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide-os-windows\rel-chocolate-cosmos\src\cpp\session\http\SessionHttpConnectionImpl.hpp:161
2024-05-03T20:06:33.064176Z [rsession-duchu] ERROR system error 5 (Zugriff verweigert); OCCURRED AT auto __cdecl rstudio::core::system::ChildProcess::terminate::<lambda_0837bcc20cbf20264fbd4fbbbf2e36d5>::operator ()(void) const src/cpp/core/system/Win32ChildProcess.cpp:294; LOGGED FROM: void __cdecl rstudio::core::system::ProcessSupervisor::terminateAll(void) src/cpp/core/system/Process.cpp:379
2024-05-03T20:06:33.064176Z [rsession-duchu] ERROR system error 5 (Zugriff verweigert); OCCURRED AT auto __cdecl rstudio::core::system::ChildProcess::terminate::<lambda_0837bcc20cbf20264fbd4fbbbf2e36d5>::operator ()(void) const src/cpp/core/system/Win32ChildProcess.cpp:294; LOGGED FROM: void __cdecl rstudio::core::system::ProcessSupervisor::terminateAll(void) src/cpp/core/system/Process.cpp:379

```

**Comment by ronblum** [comment]
@HuEaSi Thank you for the added info! This will be helpful as we review the problem.

**Comment by HuEaSi** [comment]
> durch den Hostcomputer abgebrochen)

I forgot to mention it. In the report is a text passage in the Logs section in German:
"durch den Hostcomputer abgebrochen)"
can be translated to:
"cancelled by the host computer)"

**Comment by HuEaSi** [comment]
@ronblum dear ronblum, do you have any news for me? Can I help somehow by providing more information? Thank you very much for helping!

**Comment by ronblum** [comment]
@HuEaSi Can you try [resetting the user state](https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State)? The Support article describing how is at https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State .

**Comment by ronblum** [comment]
@HuEaSi Glad to hear it! Is 2024.04.0+735 still generating the error, or have you tried it? By the we have [an updated release, 2024.04.1+748.](https://posit.co/download/rstudio-desktop/)

**Comment by Malcolm-Hudson** [comment]
I'm experiencing a similar issue, rstudio login reverts to Rstudio 2023.12.1 build 402 after installing new version 2024.04.1+748 on xubuntu 22.04 running R version 4.4.0
