### ISSUE TITLE
Incorrect PATH set on RStudio Mac

### ISSUE THREAD

**Issue by thomasp85** [rstudio/rstudio#14659]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0+735
    OS Version      : macOS 14.4.1
    R Version       : 4.3.2

### Steps to reproduce the problem

The PATH that RStudio starts up with is not the path of the default shell (zsh)

```
> Sys.getenv("PATH")
/bin:/usr/bin:/usr/ucb:/usr/local/bin:/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/bin/postback:/Applications/RStudio.app/Contents/Resources/app/bin/postback
```

vs

```
▶ echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Applications/VMware Fusion.app/Contents/Public:/Applications/quarto/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/thomas/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/bin/postback
```

This has started happening fairly recent (within this year) without me having done anything obviously to affect the PATH

**Comment by bbitarello** [comment]
I can confirm this is the case for me as well. I wonder if this has something to do with my RStudio startup issue #14622 https://github.com/rstudio/rstudio/issues/14622?

**Comment by dmurdoch** [comment]
Another related issue is present in RStudio Version 2024.04.2+764 (2024.04.2+764). 

 If I run `Sys.getenv("PATH")`, then use the Build | Install command to build and install a package, and afterwards run `Sys.getenv("PATH")` again, then the second display has `/usr/local/bin` added at the front of the PATH, and `/Applications/RStudio.app/Contents/Resources/app/bin/postback` added at the end of it.

**Comment by kevinushey** [comment]
I wonder if this is related to this preference:

<img width="646" alt="Screenshot 2024-06-18 at 11 14 01 AM" src="https://github.com/rstudio/rstudio/assets/1976582/433d57c0-9947-4c91-8d7a-4efa6694320c">

If I have that set, then RStudio seems to put `/opt/homebrew/bin` at the front of the `PATH` in new RStudio sessions, and also prepends that path on build and reload of a package.

**Comment by dmurdoch** [comment]
Yes, I had that set, and unsetting it stops the prepended directory.  I still get the extra `/Applications/RStudio.app/Contents/Resources/app/bin/postback` at the end with each build, but that one is pretty harmless.
