### ISSUE TITLE
Error opening Rnw file with curly brackets in chunk

### ISSUE THREAD

**Issue by brry** [rstudio/rstudio#14650]
Create a little `file.Rnw` with
```r
<<>>=
a={}
@
```
When trying to open it, the new Rstudio gives an  

> Error while opening file  
> (TypeError): Cannot read properties of undefined (reading 'count')

### System details

RStudio 2024.04.0+735 "Chocolate Cosmos" Release (a00d0e775dbc93e0d79a1bf474e3e8e8de677383, 2024-04-24) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0+735 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.553

R version 4.4.0 (2024-04-24 ucrt) Platform: x86_64-w64-mingw32/x64 Running under: Windows 10 x64 (build 19045)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by brry** [comment]
The error occurs when there is a curly bracket in the chunk.  
It also happens when trying to write this in Rstudio (autosave fails, weird cursor behaviour and text display location errors occur)

**Comment by ronblum** [comment]
@brry Thank you for raising the bug! This looks like the same issue described at the top of #14646, so I'll close it but add your minimal example.

**Comment by ronblum** [comment]
@brry No problem! I didn't realize at first that they were the same issue, until I tried to link the two. So I more or less missed it, too, at first. 🙂

**Comment by zedvalenta** [comment]
The same problem here on Mac OS Sonoma 14.5 running RStudio 2024.04.1+748, plus also on another Mac OS computer with Apple M2 pro chip architecture running the latest RStudio 2024. All is fine, however, on yet another comp with Mac OS Catalina 10.15.7, running RStudio version 2023.12.1+402 (December 2023 version). Perhaps we need to get back to this RStudio version.

**Comment by kevinushey** [comment]
Thanks for reporting -- we're in the process of preparing a patch release of RStudio which will rectify this issue.
