### ISSUE TITLE
Two finger vertical scroll is so slow it is unusable

### ISSUE THREAD

**Issue by huguesmercier** [rstudio/rstudio#14664]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0+735
    OS Version      : MacOS 14.4.1 (23E224)
    R Version       : 4.3.2

### Steps to reproduce the problem

Open a reasonably large .R file (300 lines or more) and scroll down and up using two fingers on the trackpad. The vertical scroll is so slow it is unusable.

### Describe the problem in detail

- Setting the "editor scroll speed sensitivity" option to 200 (the maximum allowed) can mitigate the problem somewhat, but not enough to make scrolling usable.
- I tested multiple versions of R in parallel. RStudio-2023.12.0-369 and RStudio-2023.09.1-494 do not have the issue.

### Describe the behavior you expected

The vertical scroll with two fingers should be faster.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For posterity, can you confirm:

- What kind of Apple macOS machine are you using?
- Are you using the laptop trackpad, or an external trackpad?
- Are you hooked up to external monitors, or using the laptop monitor? (This can matter because the monitor DPI can sometimes affect the computed scroll rate)

**Comment by benfarmer05** [comment]
I am having the exact same issue on an Apple M1 2020, with Sonoma 14.4.1. This only occured after updating to RStudio-2024.04.0-735

**Comment by d-bohn** [comment]
Just responding to bump this issue and say I've noticed the same thing. There has been a significant slow down in two finger scrolling with the latest Rstudio update RStudio-2024.04.0-735. Working on an Apple M1 Pro with Sonoma 14.4.1.

**Comment by ronblum** [comment]
Reproduced in RStudio Desktop 2024.04.0+735 on MacOS 14. With a file of about 1K lines, the movement seems to be around 40-50% of the speed as in 2023.12.1+402. It might be slower on Windows as well, but I can't quite tell, even with a large file.

**Comment by z-jiwani** [comment]
same issue here as well.

**Comment by kevinushey** [comment]
If you're encountering this issue, a quick resolution is to use the Command Palette (Ctrl + Shift + P, or Cmd + Shift + P on macOS), type "scroll", and update the Editor scroll speed sensitivity to a sufficiently large value.

<img width="616" alt="Screenshot 2024-06-04 at 4 27 10 PM" src="https://github.com/rstudio/rstudio/assets/1976582/7635572d-9a12-448e-810b-e7561af53fb0">

Most likely, a value of 200 or 400 should be sufficient.

**Comment by huguesmercier** [comment]
> If you're encountering this issue, a quick resolution is to use the Command Palette (Ctrl + Shift + P, or Cmd + Shift + P on macOS), type "scroll", and update the Editor scroll speed sensitivity to a sufficiently large value.
> 
> <img alt="Screenshot 2024-06-04 at 4 27 10 PM" width="616" src="https://private-user-images.githubusercontent.com/1976582/336635965-7635572d-9a12-448e-810b-e7561af53fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjQxMjUsIm5iZiI6MTcxNzY2MzgyNSwicGF0aCI6Ii8xOTc2NTgyLzMzNjYzNTk2NS03NjM1NTcyZC05YTEyLTQ0OGUtODEwYi1lNzU2MWFmNTNmYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDg1MDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyOGNmNzA1OWE3MTViYzY1ZTRlMDVjYWNjNDdhYWVkZjI3NTM0OTg4ZmQyMjFlNzc3NDUzODFlODUyMDczZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Js3QSEwtMeXnC5V6yK2sQ_yPnDE5u81LO9aeUbDVMok">
> Most likely, a value of 200 or 400 should be sufficient.

This indeed solved the issue.

**Comment by ronblum** [comment]
Verified that scrolling in RStudio Desktop 2024.07.0-daily+219 on Windows 11 is much faster than in 2024.04.1+748.

Verified that scrolling in RStudio Desktop 2024.07.0-daily+215 on Ubuntu 24.04 is reasonable.

Will check next on MacOS.

**Comment by ronblum** [comment]
Scrolling speed is vastly greater in RStudio Desktop 2024.07.0-daily+219 on MacOS 14 than in the previous release, maybe about three times faster?

Verified fixed.
