### ISSUE TITLE
Unable to type curly bracket inside of R Sweave code chunk

### ISSUE THREAD

**Issue by jdblischak** [rstudio/rstudio#14667]
Verify fixed in:
- [x] Patch: 2024.04.2
- [ ] Release: 2024.07.0

---

### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0+735
    OS Version      : Windows 11 x64 (build 22631)
    R Version       : 4.3.3 (2024-02-29 ucrt)

### Steps to reproduce the problem

1. Open a new R Sweave file (File -> New File -> R Sweave)
2. Add a code chunk (Ctrl-Alt-I or push the button in the editor UI)
3. Put the cursor inside of the code chunk. Try to type a curly bracket `{`

### Describe the problem in detail

When I follow the steps above, the curly bracket does not appear. Instead I get the following Autosave error:

![image](https://github.com/rstudio/rstudio/assets/1608317/33649897-a925-4611-98bb-a022b99bf65d)

The above is the quickest way to generate the problem. However, attempting to add the curly bracket can cause chaos at any point. For example, if you have code in the code chunk and then add the curly bracket, the code is erased.

Please see this [Posit Community post](https://forum.posit.co/t/problemas-con-la-ultima-version-de-rstudio-24-04-en-rsweave/186326) for the description from the original reporter as well as my reproduction of the bug.

### Describe the behavior you expected

I expected a curly bracket to appear inside the code chunk.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jdblischak Thank you for raising this! We're tracking this bug in issue #14646, so I'll close this one as a duplicate.

**Comment by ronblum** [comment]
Actually I'll keep this open because of the order of events and use both issues for verification.

**Comment by jdblischak** [comment]
> so I'll close this one as a duplicate.

Wow! This repo gets a lot of Issues per day. I skimmed the first couple open and closed Issues and PRs before opening mine, but clearly that was insufficient for such a popular repository. Thanks for the quick reply!

**Comment by ronblum** [comment]
True! It's especially popular right now, since we just had a new release last week, and we're already working on the next release. I'm glad for it, because it means that all y'all care enough to let us know about bugs that you find and improvements that you like.  🙂 Plus the development team never seems sleep, although this QA engineer is often sleeping on the job.

**Comment by ronblum** [comment]
Verified fixed in RStudio Desktop 2024.07.0-daily+133 on Windows 11. If you'd like to try out the fixed, you can download a daily build at https://dailies.rstudio.com. Please note that these are for testing purposes only, not for production use.

**Comment by ronblum** [comment]
Update: We have a fix for this in an upcoming patch. You can get a development version of patch 2024.04.2 at https://dailies.rstudio.com/rstudio/chocolate-cosmos/. The usual caveats apply--this is for testing purposes only, not production.

**Comment by ronblum** [comment]
See automated tests: https://github.com/rstudio/rstudio-ide-automation/pull/1949

Verified in RStudio Desktop 2024.04.2+761 on Windows 11.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+174 on Windows 11 using the same tests.
