### ISSUE TITLE
Comment/uncomment lines does not work for .css file

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#14689]
### System details

```
RStudio Edition : Desktop
RStudio Version : 2024.04.0+735
OS Version      : macOS 14.4.1
R Version       : 4.3.0
```

### Steps to reproduce the problem
Select one or more lines in source editor for a .css file and use Comment/Uncomment Lines

### Describe the problem in detail
Nothing happens.
### Describe the behavior you expected
Expect lines to be surrounded by .css comment, ie `/*...*/`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jzadra Thank you for raising this! I assume you mean using the keyboard shortcut? Some of the editing menu items and shortcuts are only available for some file types. I'll switch this to an enhancement to consider.

**Comment by jzadra** [comment]
I primarily use the keyboard shortuct, but neither that or the menu is working.  I thought it had worked before, but perhaps I was mistaken.  It does work if you are in a {css} chunk in RMarkdowndown with the keyboard shortcut.

**Comment by jzadra** [comment]
Actually in a CSS chunk in RMD, the comments are HTML comments (`<! -- … --> `) as opposed to CSS comments `/* ... */` so that may be another issue.
