### ISSUE TITLE
maximizing zoomed plot window crashes rstudio session

### ISSUE THREAD

**Issue by rmflight** [rstudio/rstudio#14697]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.07.0 Build 116
    OS Version      : Ubuntu 22 (Pop!OS 22.04)
    R Version       : 4.3.0

### Steps to reproduce the problem

* generate a plot

```r
data(mtcars)
plot(mpg ~ cyl, data = mtcars)
```

* hit "zoom" on the plot tab
* try to maximize the zoomed plot window, either by double clicking the window bar, or selecting from the window context menu
* watch RStudio crash

### Describe the problem in detail

The zoomed in view of a plot crashes the RStudio session when I try to maximize the window.

### Describe the behavior you expected

The window maximizes without issue.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/15298211/diagnostics-report.txt)

**Comment by llrs** [comment]
I'm using Ubuntu 22.04, RStudio 2024.04.0+735 with R 4.4.0 and I cannot reproduce this.

**Comment by rmflight** [comment]
Weird. I rebooted my machine (to make sure it wasn't weird issues with applied kernel updates and graphics drivers), and tested with two different daily builds, 2024.07.0-daily-116 and 2024.07.0-daily-89, and both of those daily builds had the exact same issue.

**Comment by ronblum** [comment]
@rmflight Thank you for raising this! I'm unable to reproduce this using build 2024.07.0-daily+131 on Ubuntu 22. What was the last published release for which this worked correctly for you?

**Comment by ronblum** [comment]
@rmflight Also, what happens in other windows, such as when creating a new file in the Editor Pane and then clicking on the icon for "Show in new window?"

**Comment by rmflight** [comment]
@ronblum I can still get it to happen on 2024.07.0-daily+131, although it seems to be intermittent now. Sometimes it happens, sometimes it does not.

New file and then "new window" is fine.

What I have noticed is that it's crashing just as the graphics are being resized to fit the maximized window. So when I double click to maximize, the window is maximized, and then the graphics are subsequently resized. That instant when the graphics are being resized to fit, is right when it crashes if it is going to happen.

**Comment by rmflight** [comment]
@ronblum The last one that I know for sure wasn't affected, was rstudio-2024.04.0-daily-682.

**Comment by gtritchie** [comment]
This is a bug in Electron 30.0.2; it is fixed in Electron 30.0.4 (and newer), so I will bump up the Electron version and that should do it.

From the release notes for 30.0.4: Fixed an inconsistent crash on maximizing window and relayout in Ubuntu. [#42145](https://github.com/electron/electron/pull/42145) (Also in [31](https://github.com/electron/electron/pull/42146))

**Comment by rmflight** [comment]
Awesome sauce! I actually reverted to the last release today b/c daily 131 was doing a slightly different, but very similar crash as well while working on something, and I just wanted to get the work done.

Might steer clear of the dailies for a little while ... 🤔

**Comment by gtritchie** [comment]
@rmflight The Electron update is merged. Once a daily build appears with Electron 30.0.6, please give it a try and report if it solves it for you, thanks!

You can see the Electron version in the Help / About dialog.

**Comment by rmflight** [comment]
Thanks @gtritchie ! I will check it out soon.

**Comment by rmflight** [comment]
Finally had a chance to try out the new daily. Seems to be fixed with the new version of Electron.

**Comment by gtritchie** [comment]
Thanks for checking it!
