### ISSUE TITLE
Folding closed R code blocks from *bottom* of block fails in quarto documents

### ISSUE THREAD

**Issue by JohnnyZoomis** [rstudio/rstudio#14699]
### System details

    RStudio Edition  : Desktop
    RStudio Version : 2024.04.0+735
    OS Version         : MacOS 14.4.1
    R Version            : 4.4.0

### Steps to reproduce the problem

1) Open a quarto document containing unfolded (open) R code blocks in the RStudio source pane.  Here I used the File -> New File -> Quarto Document...   menu commands to create the pristine quarto new document template.

<img width="1032" alt="before" src="https://github.com/rstudio/rstudio/assets/169809078/1fb21ef6-0c72-40c6-863e-7e043f891c97">

2) Attempt to fold closed an unfolded (open) R code block by clicking on the flippy triangle at the *bottom* of the code block.  In the two images, this was at line 16.

<img width="1032" alt="after" src="https://github.com/rstudio/rstudio/assets/169809078/517f51fe-5502-455c-9fe9-37c4608c0134">

### Describe the problem in detail

The text between the bottom of the current block and either the i) header of the next code block, or ii) the end of the file, is folded closed.  See line 16 of second image.  In this case, the folded text went to the header of the *next* code block (line 20).  

### Describe the behavior you expected

The current code block (between lines 14 to 16 inclusive) is folded closed. 

This report is in response to [this discussion](https://forum.posit.co/t/code-blocks-not-closing-properly-from-end-backticks/186641)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@JohnnyZoomis Thank you for bringing this over from the Community post!

Ref: #14640 and #14652.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+245 on Windows 11, both with Quarto and R Markdown documents.
