### ISSUE TITLE
If an RStudio project are open, a non-project RStudio R session will use the other project's .Rprofile

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/rstudio#14695]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio Desktop Pro 2024.04.0 Build 735.pro3 "Chocolate Cosmos" Release (c994988f, 2024-04-24)
    OS Version      :  Windows 11 Edu
    R Version       :  4.4.0

### Steps to reproduce the problem

1. create a `~/.Rprofile`
2. create a RStudio project "A" with its local `.Rprofile`
3. Open project A (it will use its `.Rprofile`)
4. with project A still opened, open a new RStudio session out of any project. The bug is that it will use the `.Rprofile` of project A and not the user `~/.Rprofile`.

### Describe the problem in detail

I have set up RStudio to not enter any project automatically at startup.
So, I have also created an out-of-project `~/.Rprofile` to work outside of any projects.

So, if I open RStudio, the `~/.Rprofile` file will be loaded, as expected.
Next, if I open an RStudio project on a different session/window, the new project will open correctly, loading its own `path/to/proj/.Rprofile` file at startup. Now I have two instances of RStudio: out-of-project and proj.

The issue is that if I restart the R session on the out-of-project RStudio instance at that moment, it loads the `path/to/proj/.Rprofile` file instead of the `~/.Rprofile` one.

Attached:
- A [screen video](https://support.posit.co/attachments/token/QaOuRRTaAXqqUJWn93D455B2d/?name=rstudiopro-issue.mp4) of the procedure generating the issue
- The [diagnostic report](https://support.posit.co/attachments/token/rSDUCTg86FYzF8ArSWYQw6PfD/?name=diagnostics-report.txt) was produced after the procedure was recorded.

Contacted Posit support (Ticket #104756), they asked me to open an issue, and to refer this to #13922 

### Describe the behavior you expected

The out-of-any-project session should always use `~/.Rprofile`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Some investigation: on desktop, we use the `RS_INITIAL_WD` environment variable to communicate the working directory to be used for a new session. For example:

https://github.com/rstudio/rstudio/blob/1b55738c5c7cb7025450e117221bead8a6020db7/src/node/desktop/src/main/application-launch.ts#L72-L74

However, we never unset that after the new session is launched, so it gets "leaked" into restarts of previous IDE sessions.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11, both by following the steps in the video and by setting variable values and monitoring them in the Environment Pane. 

@CorradoLanera thank you for the helpful video! It helped a lot in reproducing the problem.
