### ISSUE TITLE
Error on Windows, can't find the correct path after saving viewer.

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14702]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.12.0.369 + 2024.04.0+693
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

1. Open an RStudio project
2. Run the following code 

```r
library(gt)
exibble |> gt()
```

3. In viewer pane, go to Export, select Save as image

4. Select a directory outside your current project.

5. Select the box open file after saving

### Describe the problem in detail

I get an error. Path not found. However, in the error dialog, the correct target file is displayed.

The file saved appear not to be correct either.

If you can't reproduce, maybe this could be related too:

I use Electron based file dialog. I have set default working directory location?

### Describe the behavior you expected

I would expect to work correctly, like it does when I save the file inside the working directory. I was able to reproduce for 2 versions of RStudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Thanks @olivroy ! I can reproduce this on Windows at least as far back as RStudio Desktop 2023.03.2+454.

**Comment by kevinushey** [comment]
The solution here is fortunately straightforward: ensure we properly sequence the desktop frame callbacks here.

https://github.com/rstudio/rstudio/blob/b000de3b936ea34b45c818d81c170c3d57171267/src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/ViewerPaneSaveAsImageDesktopOperation.java#L45-L55

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+245, with parent and parallel directories. Image opens after saving.
