### ISSUE TITLE
Find/Replace doesn't work with gsub statements

### ISSUE THREAD

**Issue by baderstine** [rstudio/rstudio#14704]
### System details

    RStudio Edition : Desktop
    RStudio Version : 024.04.0 Build 735
    OS Version      : Mac OS Sonoma 14.5 (23F79)
    R Version       : R version 4.3.2 (2023-10-31)

### Steps to reproduce the problem
In a .Rmd file containing a gsub function call. 

e.g., ``` gsub("blah","","sdfoiwje") ```

In "Source" view, Edit > Replace and Find
Search for "," and attempt to replace it with ", " (i.e., add a space after the comma).  

### Describe the problem in detail
When you click replace, it doesn't actually change anything. 

### Describe the behavior you expected
I would expect this code to become:
``` gsub("blah", "", "sdfoiwje") ```

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [- ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@baderstine Thank you for raising this! I can't reproduce this, though. Can you provide a minimal example of an R Markdown file that causes the failure? It'll help with trying to reproduce, in case I'm not using the code in a way that causes the problem.

**Comment by baderstine** [comment]
I just updated to RStudio version 2024.04.1 Build 748 and that seemed to fix it.  Nevermind!

**Comment by ronblum** [comment]
@baderstine That's great! Though if the problem returns, please let us know.

**Comment by baderstine** [comment]
ah no, this is actually just me being an idiot (PEBCAK).  If you try to use keyboard shortcuts for everything it doesn't quite do what i was expecting. 

Steps to reproduce (On a Mac): 
1. Command + F 
2. search for ","
3. tab to replace with ", "
4. click "Next" button because you don't want to replace this result. 
5. hit "enter" to replace second result - in this case, enter is actually just "clicking" next again because that was the last button pressed.

**Comment by ronblum** [comment]
@baderstine Ah! Honestly, I'm sure that I've done the same, too. 🙂 

Also, TIL the acronym PEBCAK.
