### ISSUE TITLE
Copilot missing from Global Options

### ISSUE THREAD

**Issue by Exploration1969** [rstudio/rstudio#14719]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1+748
    OS Version      : macOS Sonoma 14.5 
    R Version       : 

### Steps to reproduce the problem
Just go to Global Options and Copilot is not there

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Exploration1969** [comment]
> ### System details
> ```
> RStudio Edition : Desktop
> RStudio Version : 2024.04.1+748
> OS Version      :macOS Sonoma 14.5 
> R Version       : R 4.3.2
> 
> ### Steps to reproduce the problem
> Just go to Global Options and Copy;ot option is not there
> 
> ### Describe the problem in detail
> ### Describe the behavior you expected
> * [ ]  I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
> * [ ]  I have installed the latest version of RStudio, and confirmed that the issue still persists.
> * [ ]  If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
> * [ ]  I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

r

**Comment by Exploration1969** [comment]
Trying to use this for first time

**Comment by gtritchie** [comment]
Can you provide a screenshot of what you are seeing?

Here's how it should look:

<img width="631" alt="global-options" src="https://github.com/rstudio/rstudio/assets/10569626/db76be5a-3e34-42f8-97da-626e0f2e1e38">

Also, double-check the version information (Help / About) to make sure you aren't actually running an older version

<img width="616" alt="about" src="https://github.com/rstudio/rstudio/assets/10569626/60bb2c75-619c-4a75-b67d-7d935b5bd5dc">
