### ISSUE TITLE
Path completion in R Markdown files does't respect "Evalute chunks in directory" option

### ISSUE THREAD

**Issue by lockjs** [rstudio/rstudio#14710]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2024.04.1+748 (2024.04.1+748)
    OS Version      :  macOS 14.4.1 (23E224)
    R Version       :  4.3.2 (2023-10-31) -- "Eye Holes"

### Steps to reproduce the problem
Open RStudio and change the "R markdown > Evalute chunks in directory" option to "project"
Create a new project in R studio
In the project directory create the subdirectories "data" and "R"
Create a new R markdown file in the "R" directory
Create a new file (for example: data.csv) in the "data" directory 
In the R markdown file insert a code cunk and add the function call read.csv("

### Describe the problem in detail

When attempting to specify the path to data.csv file created in the steps above the suggested autocomplete will be resolved from the location of the R markdown file ("./R") rather than the project directory (./) and so no results will be returned. Providing the path ../ will begin to suggest files as expected.

Note, when knitted or run the code chunk is executed correctly, it's only the autocomplete pop-over that uses the incorrect working directory

### Describe the behavior you expected

Autocomplete should respect the value of the "Evalute chunks in directory" option and resolve file paths based on the project rather than document root

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by DerBergellerWolf** [comment]
Hi there. I had the same issue and found this post.
I'm running R version 4.3.0 (2023-04-21) inside Rstudio 2024.12.0 Build 467 on aarch64-apple-darwin20.

What worked for me is clearing Knit cache after ensuring the Knit directory is set to "Project directory".
To do that you need to go inside the Knit drop-down menu above the source code editor, by clicking on the small pointing down arrow on the right of "Knit".

<img width="456" alt="Image" src="https://github.com/user-attachments/assets/39c3d31d-1f8d-4096-8049-05287fbd17af" />

Hope somebody else may find that useful, enjoy.
DBW
