### ISSUE TITLE
Unable to insert R chunk in .Rnw file. RStudio restart required.

### ISSUE THREAD

**Issue by MatthewHeun** [rstudio/rstudio#14714]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0-735
    OS Version      : macOS Sonoma 14.4.1
    R Version       : 4.4.0

### Steps to reproduce the problem

* Start a fresh RStudio project in an empty directory.
* Create a new .Rnw document with File|New File|R Sweave
* At the cursor location, type "<<>>=" (without the quotes) as if to start a new R chunk.
* Alternatively, instead of typing "<<>>=", choose Code|Insert Chunk. Then, delete the "@" character at the end of the chunk.  

### Describe the problem in detail

When I type the "=" character (or delete the "@" character), I see this message:

![image](https://github.com/rstudio/rstudio/assets/3308246/72cbc621-ac5c-40c8-b076-5169af3cabdf)

And, as suggested, I need to restart RStudio. Pressing the return key while the cursor is inside the chunk provides additional gray lines beneath the "@" symbol, not within the code chunk (as I would expect). 

NOTEs: 

* Reverting to RStudio-2023.12.1-402 fixes the problem.
* Installing RStudio-2024.07.0-daily-138 fixes the problem.

### Describe the behavior you expected

I expected to start a new R code chunk. I expected to be able to add lines inside the R chunk.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Thanks! This is a variation of issue #14667 which was fixed in 2024.07.0, as you've noted, and will be fixed in an upcoming patch, 2024.04.2.
