### ISSUE TITLE
Sudden crash (R session aborted due to fatal error) on OpenSuse

### ISSUE THREAD

**Issue by aaamw2000** [rstudio/rstudio#14729]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0 build 735
    OS Version      : x86_64-suse-linux-gnu, openSUSE Tumbleweed, VERSION="20240507"
    R Version       :  R version 4.4.0 (2024-04-24) Puppy Cup

### Steps to reproduce the problem
1. Open Rstudio
2. define two or three dummy vectors with relatively large numbers
You can also load the software with any other way. I found that it crashes within 5-10 minutes of work for no specific reason regardless of what I am doing.

### Describe the problem in detail
Within 10 or so minutes of work, Rstudio display a popup saying that "R session Aborted" "R encountered a a fatal error." "The session was terminated." Then prompts me to start a new session, and all new sessions crash in a similar manner.

I tested all the commands that caused my R sessions to get aborted in Rstudio in vanilla terminal R, and they all ran successfully. I am more or less certain this has nothing to do with R itself.
 
### Describe the behavior you expected

I expected Rstudio to keep my session alive and allow me to input vectors and make linear models with these vectors.

Diagnostics report: https://text.is/4RR2K

Link to reddit post indicating that other people on Suse software are facing the exact same thing: 
https://www.reddit.com/r/RStudio/comments/1cnafvd/rstudio_keeps_crashing_after_new_update/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Edit:
Apparently, a new version of Rstudio was released yesterday, but it is not packaged for OpenSuse yet. I downloaded this daily version of Rstudio: rstudio-2024.07.0-daily+108, and it works fine.

**Comment by ronblum** [comment]
@aaamw2000 Thank you for raising this! A few things:
1. I'm glad that it's working in 2024.07.0! Please note, though, that Cranberry Hibiscus is in active development, so these builds are for testing and development purposes.
2. There's a download for OpenSUSE 15 at https://posit.co/download/rstudio-desktop/ . Is it missing from another page?

**Comment by jthomasmock** [comment]
@aaamw2000 -- glad it is working ok for you in the daily build, would you be able to try with a different version of R in the release version?
