### ISSUE TITLE
Weird behavior with RStudio "Save as image" function

### ISSUE THREAD

**Issue by VR-Daniel** [rstudio/rstudio#14727]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1 Build 748
    OS Version      : Windows 11 Pro 22H2
    R Version       : 4.3.3 and 4.4.0

### Steps to reproduce the problem

1. Generate whatever plot.
2. Click on "Export as image" in the plot pane.
3. Set a width and a height.
4. Check the final export size.

### Describe the problem in detail

Hi there!

I'm posting it because I'm experiencing a weird behavior with the built-in RStudio function "Save as image". When I save an image and set the width and height parameters, the final plot is larger. I have been using this option a long time ago but this misfunctioning appeared suddenly with the most recent update. For instance, I set a size of 3500 x 1500 px but the final image is 4812 x 2062 px. Previously, the images were exported at 96 dpi (as intended according to [this ](https://github.com/rstudio/shiny/issues/1832)thread), now are 132 dpi by default (in my case, another user in [Posit ](https://forum.posit.co/t/weird-behavior-with-rstudio-save-as-image-function/186928)reported 240 dpi). When saving the images programmatically at 96 dpi they show the right number of pixels. I downgraded to RStudio 2023.09.0 Build 463 and the figures are being exported in the same size as the user defined. However, I didn't find anything related to a change in the default export dpi in the newer versions of RStudio in the change-log.

I opened a topic in the [Posit ](https://forum.posit.co/t/weird-behavior-with-rstudio-save-as-image-function/186928) community and this behavior seems to affect some users but not others.

### Describe the behavior you expected

Get the images exported from the plot pane in the same size the user defined.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by stibu81** [comment]
I have the same problem on a different system:

```
RStudio Edition : Desktop
RStudio Version : 2024.04.1 Build 748
OS Version      : Ubuntu 22.04
R Version       : 4..4.0
```

 In my cases, all sizes are off by a factor 0f 1.25, which is different than in Daniel's case, where the factor is 1.37.

**Comment by mduvekot** [comment]
In my case the scaling factor is 2.5,

 > sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.0 (2024-04-24)
 os       macOS Sonoma 14.5
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Toronto
 date     2024-05-23
 rstudio  2024.04.1+748 Chocolate Cosmos (desktop)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cli           3.6.2   2023-12-11 [1] CRAN (R 4.4.0)
 rstudioapi    0.16.0  2024-03-24 [1] CRAN (R 4.4.0)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.4.0)

**Comment by kevinushey** [comment]
I think these changes are related to RStudio's attempts to support high DPI images. This normally works when viewed in e.g. the Plots pane, as we render plots with the (width, heigh, resolution) all scaled by the device pixel ratio, and then scale the image back to the original intended dimensions for display in the Plots pane. For example, using devtools:

<img width="415" alt="Screenshot 2024-06-11 at 11 09 45 AM" src="https://github.com/rstudio/rstudio/assets/1976582/d42771fe-f8c2-4f61-99f0-f6e18ae69085">

This particular changes comes from here:

https://github.com/rstudio/rstudio/commit/5ab2b3b72437c9dbaa16dbfe2ceb2e54399550fe#diff-b95803aed10de28cbbf086ef142968a54bb300face67bb74c882c59a71fef06bR160

I think the answer here depends on how the generated images are going to be used. If you want the same, high DPI image that you see in the preview window, then we need to render at the larger dimensions, and the image dimensions then need to be properly scaled down wherever the image is later viewed.

However, if we just render without scaling, then you'll get plots with "fuzzy" text like:

<img width="411" alt="Screenshot 2024-06-11 at 11 35 01 AM" src="https://github.com/rstudio/rstudio/assets/1976582/0c611829-9131-4822-afae-593fb002b2fc">

I think the best way forward is to just introduce a checkbox like "[ ] Use device pixel ratio", and use that to control the resolution of the generated plot.

**Comment by kevinushey** [comment]
Also adding one extra bit of confusion. Browsers widths and heights are normally scaled according to the display DPI, so an image that is sized with a width of 400px is really going to be 800px on a display with a 2.0 device pixel ratio.

So even though we're scaling these plots up based on the display DPI, the intention is for them to be scaled to be rendered at the requested width + height.
