### ISSUE TITLE
cli text doesn't change color when changing theme

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14726]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.4.0.735
    OS Version      : macOS 
    R Version       : R version 4.2.3 (2023-03-15)

### Steps to reproduce the problem

1. type this code in console (in Dark theme)

```r
# to switch theme
rstudioapi::applyTheme('Tomorrow Night Blue')
```

```r
cli::cli_inform("text will not switch color")
x <- c("text will switch color")
x
```

2. switch to Light theme

```r
rstudioapi::applyTheme("Chrome")
```

(Also confirmed that the same happens

### Describe the problem in detail

Screenshot before:

![image](https://github.com/rstudio/rstudio/assets/52606734/9d384e73-2817-4179-9ae8-16429e601396)

after changing theme with `rstudioapi::applyTheme("Chrome")`
The cli text does not change color.  

![Capture d’écran, le 2024-05-20 à 10 55 51 a m](https://github.com/rstudio/rstudio/assets/52606734/fdc4fee8-197f-493e-af46-2bcb337fcb55)

### Describe the behavior you expected

I would expect the text to follow the theme. If this bug is confirmed, and a fix is planned, it would be important to ensure it doesn't break https://github.com/rstudio/rstudio/issues/13869.

If this has been around for while, feel free to close as this is probably the expected behavior.

Not sure if this is an RStudio or cli bug. I opened this https://github.com/r-lib/cli/issues/693 and still waiting for an answer.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@olivroy I can reproduce this in 2024.07.0-daily+169 as well, both using `rstudioapi` and Global Options. There's an issue in 2023.03.2+454 as well, but it's reversed: It's viewable in the light theme using black text, but unseen in the dark theme for that reason.
