### ISSUE TITLE
Windows 10, knit.md is not UTF-8 encoded, .qmd not rendering to html correctly after updating RStudio

### ISSUE THREAD

**Issue by darrennorris** [rstudio/rstudio#14724]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1
    OS Version      :  Windows 10 
    R Version       :  4.4.0

### Steps to reproduce the problem
I updated from RStudio 2023.12.1-402 to RStudio 2024.04.0-735 and then 2024.04.1-748.
The problem is the same on 2024.04.0-735 and 2024.04.1-748.

` sessionInfo()
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=C                            
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Cayenne
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.4.0    fastmap_1.1.1     cli_3.6.2         htmltools_0.5.8.1
 [5] tools_4.4.0       rstudioapi_0.16.0 yaml_2.3.8        rmarkdown_2.26   
 [9] knitr_1.46        xfun_0.43         digest_0.6.35     rlang_1.1.3      
[13] evaluate_0.23 `

### Describe the problem in detail
The .qmd file that was rendering to html before the update now returns symbols for accented Portuguese text.
When rendering I now get the message: [WARNING] test.knit.md is not UTF-8 encoded: falling back to latin1.

I tried on the Posit Community but have received no help after 11 days. 
Any suggestions as to how I can solve this.

### Describe the behavior you expected
Example that was produced before the update:
https://rpubs.com/darren75/1179696
Example of what the html file now looks like:
https://rpubs.com/darren75/1184645

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Link to community thread: https://forum.posit.co/t/knit-md-is-not-utf-8-encoded-portuguese-language-qmd-not-rendering-to-html-correctly-after-updating-rstudio/186725

**Comment by ronblum** [comment]
@darrennorris Would you be willing to provide the source file so that we can try to reproduce? Obrigado!

**Comment by darrennorris** [comment]
> @darrennorris Would you be willing to provide the source file so that we can try to reproduce? Obrigado!

Thank you for the message. Here goes - hope this works. . I have tried to include it here in the message as well.

`---
title: "test Animais domésticos: análises descritivas"
author: "Darren Norris"
lang: pt-BR
format: 
  html:
     toc: true
     toc-location: left
     link-citations: true
  pdf: default
editor: source
---

```{r}
#| label: set-sys
#| include: false
Sys.setlocale("LC_TIME", "Portuguese")
```


## Objetivo

Aqui utilizamos o caso dos animais domésticos do Campus Marco Zero.

### Dados

```{r}
#| label: before-after-inds
#| echo: false
#| message: false

# month without accent in name
data_inicio <- as.Date("2024-04-15")
# month with accent in name
data_final <- as.Date("2024-03-15")
label_inicio <- format(data_inicio, '%B %Y')
# Month with accent causes invalid readline error when rendered.
label_final <- format(data_final, '%B %Y')

```

Entre `r label_inicio` e `r label_final`  foram registrados 
45 animais domésticos no campus Marco Zero. 
`

[test.zip](https://github.com/rstudio/rstudio/files/15475106/test.zip)

**Comment by darrennorris** [comment]
@ronblum I have also attached the diagnostics report here.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/15484164/diagnostics-report.txt)

**Comment by ronblum** [comment]
@darrennorris Thank you! I tried this out with RStudio Desktop 2024.04.0+735, but I'm not getting the issue. The only issue I run into is one wonky character:
`Entre abril 2024 e mar�o 2024 foram`

Although interestingly, when I use Chrome to translate the page to English, it seems to handle it:
`Between April 2024 and March 2024,`

I'm trying this with the same locale but on Windows 11, not 10. @gtritchie Do you think that the Windows version could make a difference, or any other suggestions?

**Comment by darrennorris** [comment]
thanks @ronblum . The general problem could also be related to something specific on the install on my laptop. But so far all looks fiine to me.  I have no idea how to go about finding where the problem is. Any sugestions?
The "wonky character" issue also remains a problem,   - but not sure if this case is RStudio or other issue like knitr......?
Any help much appreciated.

**Comment by darrennorris** [comment]
Solved.
@gtritchie @ronblum thank you for your help. I just needed to update the line of code specifying the locale with utf8 as follows:

`Sys.setlocale("LC_TIME", "Portuguese_Brazil.utf8")`

All has now returned to normal. Closing the issue here.
Best,
Darren

**Comment by squirrellina** [comment]
Jumping on here because I didn't see other discussions of the warning "[WARNING] filename.knit.md is not UTF-8 encoded: falling back to latin1.". Maybe someone will consider my problem/solution useful.
Changing the locale didn't work for me because I had a different situation with the same warning. In my case the locale was already correct and the .rmd was UTF-8-encoded already. But because I had read data with umlauts into my environment with the wrong encoding that then was printed in the rmd file apparently the md file was then translated to .tex using the wrong encoding which led to broken umlauts and even problems with translation of custom latex functions from the YAML header (obsolete \textbackslash where they shouldn't have been escaped). A simple read.csv2(x, fileEncoding = "latin1") to fix the underlying data fixed the issue.
