### ISSUE TITLE
Update Electron in Chocolate Cosmos

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14732]
Verify fixed in:
- [x] Patch: 2024.04.2
- [x] ~~Release: 2024.07.0~~

---

For Chocolate Cosmos patch 2, we could update Electron from 28.2.6 to 28.3.1 to pick up the latest fixes.

**Comment by ronblum** [comment]
Verified that Electron 28.3.1 is used in Chocolate Cosmos patch 2024.04.2+761.

**Comment by ronblum** [comment]
This isn't relevant to Cranberry Hibiscus: 2024.07.0-daily+174 is using Electron 30.0.8, as per #14752.
