### ISSUE TITLE
Update node.js in Chocolate Cosmos

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14731]
Verify fixed in:
- [x] Patch: 2024.04.2
- [ ] Release: 2024.07.0

---

For Chocolate Cosmos patch 2:

- update node.js (used by Copilot) to version 18.20.3

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.2+761 on Windows 11.
```
& 'C:\Program Files\RStudio\resources\app\bin\node\node.exe' --version
v18.20.3
```

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+174 on Windows 11.
