### ISSUE TITLE
Update node.js used at build time

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14740]
Currently we use node.js 18.18.2 for build tasks (e.g. building Electron desktop, panmirror, ...).

This is set here (and a few other places):

https://github.com/rstudio/rstudio/blob/912b8a9be9c4544a4f63f87209ca2f6ea714310c/dependencies/tools/rstudio-tools.sh#L466-L470

Electron v30 (Cranberry Hibiscus) uses node 20.11.1 internally, but we should probably go with the latest v20 LTS release.

This isn't urgent, but eventually node 18 will go out of support.

**Comment by gtritchie** [comment]
Nothing to actually test here other than waiting to confirm that builds succeeded on all platforms.

**Comment by ronblum** [comment]
Verified in version 2024.07.0-daily+244. Screenshotting this to show that builds succeeded for all platforms (since sometimes one or two or ten will fail).

![Image](https://github.com/rstudio/rstudio/assets/31009952/846d6160-9a99-4d7c-8be9-8814e4424719)
