### ISSUE TITLE
Run 'Harlequin' (or other Textual terminal apps?) in the Terminal

### ISSUE THREAD

**Issue by daranzolin** [rstudio/rstudio#14745]
My dream is to bounce from the R console to a Terminal and launch [Harlequin, a SQL IDE for terminals.](https://harlequin.sh/) While I can't get the terminal to recognize 'harlequin' as a command, the application launches if I specify the full path to `...\harlequin.exe`. The experience, however, is pretty bad: awkward scrolling, conflicting hot keys, and inconsistent styling make it unusable. I guess it's weird to use an IDE inside an IDE?

After some cursory research, I think this is maybe related to [Textual, a Python framework for apps](https://textual.textualize.io/), with which Harlequin was built. Is running Harlequin inside RStudio feasible? 

Screenshot of Harlequin launching (but not working) in RStudio below:

![image](https://github.com/rstudio/rstudio/assets/9537384/5a037332-ac22-406a-9129-dcddd7c43e73)

**Comment by kevinushey** [comment]
We might have some luck with a newer version of [Xterm.js](https://xtermjs.org/), but I'm not positive.
