### ISSUE TITLE
Linker errors with RSTUDIO_USE_SYSTEM_SOCI=yes

### ISSUE THREAD

**Issue by xiota** [rstudio/rstudio#14753]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1.748
    OS Version      : Arch Linux
    R Version       : 4.4.0

### Steps to reproduce the problem

Try to build `aur/rstudio-desktop` in clean chroot.  The PKGBUILD sets `RSTUDIO_USE_SYSTEM_SOCI=yes` in cmake options.

Problem has now been replicated by three people, all using the AUR package.

### Describe the problem in detail

gcc 14.1.1+r58+gfc9fb69ad62.  Numerous linker errors similar to:
```
/usr/bin/ld: <artificial>:(.text+0x639): undefined reference to `soci::details::statement_impl::dec_ref()'
```

[rstudio-desktop.log](https://paste.ee/r/nBMgF/0)

Version 2023.12.1.402 was previously built successfully on 2024-01-30.

~~Someone has reported that disabling LTO allowed the build to continue successfully, but in my testing, the same, or similar, linker errors still occur.~~

Probably related to cmake changes, such as in 230c0ef.  Related #14426

Setting `SOCI_LIBRARIES=/usr/lib` results in *some* of the linker errors going away.  So I suspect a couple related issues:

* Paths aren't found, so not added to `SOCI_LIBRARIES`.  Because the files associated with the errors changed.
    * However, upon further reflection, the difference may be from parallel builds and race conditions.
* Missing [arguments for] `target_link_libraries`

**Update:** Adding the following allows the build to succeed:
```
export LDFLAGS=" -L/usr/lib -lsoci_core -lsoci_sqlite3"
```

This makes it reasonably certain some `target_link_libraries` commands need adjustment.

**Update:** Rebuilding `soci` with LTO disabled allows `rstudio-desktop` to build successfully.

At this point, I suppose you can consider this not your problem.  But since adjusting LDFLAGS also worked, reviewing the cmake scripts may still be worthwhile.

### Describe the behavior you expected

Build should complete successfully without linker errors.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
    - Majority of this document is not relevant to this issue.
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
    - Not relevant.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
    - Not relevant.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by xiota** [comment]
Attempting to build with `soci` uninstalled and `RSTUDIO_USE_SYSTEM_SOCI=no` results in following:
```
CMake Error at src/cpp/CMakeLists.txt:486 (find_library):
  Could not find SOCI_CORE_LIB using the following names: libsoci_core.a,
  soci_core
```

**Comment by kevinushey** [comment]
Any chance you'd be able / willing to prepare a PR?

**Comment by xiota** [comment]
The AUR package has been modified to work around the issue.  So the reproduction steps above would no longer work.

I am willing to review the cmake file and open a PR if needed, provided that changes addressing the described issues are reasonably likely to be approved.  If you like it how it is and prefer not to change it, I am fine with letting it be.  I've provided enough info that anyone encountering something similar should be able to work around it.

**Comment by xiota** [comment]
It seems commits after the v2024.04.1+748 release make significant changes to the cmake scripts, including [discontinuing the C++/Qt builds](https://github.com/rstudio/rstudio/commit/ebea03703bb720f263d5fff67813b420032c06ba).  If this interpretation is correct, the soci linker errors do not matter anymore.

**Comment by kevinushey** [comment]
Sounds good -- thanks for taking the time to investigate.
