### ISSUE TITLE
Failure to install RStudio on Ubuntu 24.04

### ISSUE THREAD

**Issue by emankhalaf** [rstudio/rstudio#14757]
Hi,

I did the following to install R & RStudio on Ubuntu 24.04 and got the errors below:

`sudo apt -y install r-base`

`R --version`
R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

`sudo add-apt-repository universe`

Then downloaded rstudio-2024.04.1-748-amd64.deb (for Ubuntu 22.04) as there is no .deb for Ubuntu 24.04.

`sudo apt install rstudio-2024.04.1-748-amd64.deb`

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package rstudio-2024.04.1-748-amd64.deb
E: Couldn't find any package by glob 'rstudio-2024.04.1-748-amd64.deb'

Any help!

Thanks!

**Comment by gtritchie** [comment]
Try: `sudo apt install ./rstudio-2024.04.1-748-amd64.deb`

(added `./` in front of the install package)

**Comment by gtritchie** [comment]
Also be aware that RStudio 2024.04.x (nor any earlier versions) is *not* supported on Ubuntu 24. You might be able to get it working, but it's not something we've tested.

You might have better luck with a recent daily build of 2024.07 from https://dailies.rstudio.com/ (Daily builds are intended for testing purposes, and are not recommended for general use)

**Comment by gtritchie** [comment]
Closing under the assumption, it was the missing `./` that was blocking you. Please let me know if this is NOT the case and I'll reopen this.

**Comment by emankhalaf** [comment]
@gtritchie 
Thanks so much for your assistance. Yes, I added the missing ./, then after installation, I got this message "Download is performed unsandboxed as root as file '/home/testing123/Documents/HV/rstudio-2024.04.1-748-amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)"
RStudio is already installed but not accessible.
I am using a machine customized to test R script that needs high RAM and computational power (pooling large number of high throughput sequences. So, I started installing the needed packages to run the script, and I stuck at RStudio installation step. I also skipped RStudio installation and started installing packages on R from command line, but I am challenging many incompatibilities with Ubuntu 24.04, however all of these packages were already installed on my old machine operated by Ubuntu 20.04.
I tried to reinstall using:
`sudo apt install ./rstudio-2024.04.1-748-amd64.deb`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rstudio' instead of './rstudio-2024.04.1-748-amd64.deb'
rstudio is already the newest version (2024.04.1+748).
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.

but RStudio is still not accessible.

Any suggestions here!
Thanks in advance!

**Comment by gtritchie** [comment]
Not sure what you mean by "not accessible". It's installed, what happens when you run RStudio?

**Comment by gtritchie** [comment]
Also, as I said, RStudio 2024.04 is NOT supported on Ubuntu 24. You might be able to find a workaround in this issue: https://github.com/rstudio/rstudio/issues/14336.

**Comment by danieltomasz** [comment]
@emankhalaf  you might have better chances of more compatible Rstudio release using Rstudio daily releases https://dailies.rstudio.com/ The  next version `2024.07` doesn't yet support Ubuntu 24.04 but the Rstudio team working on it, and all the changes they do to fix electron problem and other incompatibilities will land first into daily release

**Comment by Muideen27** [comment]
sudo chmod 4755 /usr/lib/rstudio/chrome-sandbox 

Works for me permanently.

**Comment by cellocgw** [comment]
Muideen27's suggestion worked for me
