### ISSUE TITLE
Differentiate exported functions from non exported functions in R script outline in R packages

### ISSUE THREAD

**Issue by maelle** [rstudio/rstudio#14766]
I use the document outline a lot in R scripts and test files, it's awesome. :pray: 

I wonder if in an R script in an R package, with both exported

```
#' @export
funname <- function() {
```

and not exported functions

```r
internal_fun <- function {
```

the exported functions could be more important, like h1 vs h2 in R Markdown document outlines?

**Comment by olivroy** [comment]
Also, it would be great if they had a different symbol in Find in Files (currently f with blue background)! (and potentially different importance)

![image](https://github.com/rstudio/rstudio/assets/52606734/7cc3b6f8-9223-44f2-a575-dede8d045086)

![image](https://github.com/rstudio/rstudio/assets/52606734/0462f472-72f2-4f8f-a855-cb6569019040)
