### ISSUE TITLE
R project environment not loading when "_quarto.yml" is present in same directory

### ISSUE THREAD

**Issue by jibarozzo** [rstudio/rstudio#14762]
### System details

    RStudio Edition : Desktop
    RStudio Version : 748.4
    OS Version : Arch Linux x86_64 
    R Version : 4.4.0

### Steps to reproduce the problem
1. Create a new Quarto project — just an ordinary project, not a website. The default Quarto project in the CLI by : ` quarto create name-of-quarto-project`. Creates default project with  `_quarto.yml`.
2. Create or add .Rproj to directory: `Project.Rproj`

### Describe the problem in detail
When trying to open .Rproj environment it does not load when `_quarto.yml` file is present. Changing the file name with the same extension or deleting the file solves the issue and R project loads as expected. `_quarto.yml` is needed for rendering of .pdf and .docx, see example:

`project:
  execute-dir: project
  output-dir: manuscript
editor: source
execute:
  echo: false
warning: false

format:
  pdf:
    documentclass: scrartcl
    include-in-header:
        text: '\usepackage{lineno}\linenumbers'
    linestretch: 2.0
    margin-left: 1in
    margin-right: 1in
    margin-top: 1in
    margin-bottom: 1in
    mainfont: TeX Gyre Termes #Alternative to Times New Roman
    sansfont: TeX Gyre Termes #Another option is Liberation Serif
    number-sections: true
    citation-package: biblatex
  docx:
    reference-doc: custom-reference-doc.docx
    number-sections: true
    citation-package: biblatex
`

### Describe the behavior you expected
Load .Rproj with `_quarto.yml` and render documents. Attempted with older version of Rstudio (2023.12.1+402-2) and it presented the same issue.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jibarozzo Thank you for raising this! What happens when you create a Quarto project within in RStudio?

**Comment by jibarozzo** [comment]
Hi @ronblum. Tried doing this. It turns out I run into the issue described in #10966. Previously, I was using Quarto v.1.4.537, I installed v.1.4.544 and it still does not show Quarto projects from within Rstudio. I a new sandbox, I replicated the behavior described above by simply creating a new `_quarto.yml` file from within the IDE. Closed the project , tried opening it and had no success.
