### ISSUE TITLE
Bug Report: Missing Notification for Uninstalled Packages in RStudio Desktop (2024.04.1-748)

### ISSUE THREAD

**Issue by aephidayatuloh** [rstudio/rstudio#14769]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1-748
    OS Version      :  Windows 11 64bit
    R Version       : 4.4.0

When I write library(ranger) (or any other uninstalled package) and save the script in the editor, a notification usually pops up in the script editor indicating that the package is not installed. However, in the RStudio Desktop version (2024.04.1-748), this notification does not appear.

![image](https://github.com/rstudio/rstudio/assets/11643631/9dcd8c70-c200-4127-a366-a55fc938786b)

In contrast, this notification feature is still functioning correctly in RStudio Server.

![image](https://github.com/rstudio/rstudio/assets/11643631/3e339225-3564-4b06-93b1-a65097baa943)

This feature is very useful for me when updating the R version because it helps me identify and install the necessary packages without having to manually check each one.

### Steps to reproduce the problem

1. Open RStudio Desktop version 2024.04.1-748.
2. Create a new script file.
3. Write library(ranger) (assuming 'ranger' is not installed).
4. Save the script.

### Expected Behavior:

A notification should appear in the script editor indicating that the 'ranger' package is not installed.

### Actual Behavior:

No notification appears in the script editor.

Thank you for looking into this issue. This feature is highly beneficial for maintaining an efficient workflow, especially when transitioning between R versions.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@aephidayatuloh Thank you for raising the issue! I can't reproduce the problem, though, including by using the `ranger` package. Does it make a difference whether or not you save the file? Does this occur with other packages?
