### ISSUE TITLE
Update quarto to 1.4.555

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14779]
Verify fixed in:
- [x] Patch: 2024.04.2
- [x] Release: 2024.07.0

---

We're currently bundling Quarto 1.4.553. The latest release is 1.4.555, so we should consider updating.

**Comment by fh-mthomson** [comment]
Is it possible to back port this change into 2024.04.2? The current bundled version of Quarto appears to fail for a number of R versions (https://github.com/quarto-dev/quarto-cli/pull/9660); we're hoping to inherit upstream via a 2024.04.2 release for Workbench in Posit's Docker images, as introduced in https://github.com/rstudio/rstudio-docker-products/pull/727

**Comment by gtritchie** [comment]
It may be too late for patch 2, but I will raise it to the appropriate people and see what they think.

**Comment by gtritchie** [comment]
Good news, we are taking the Quarto 1.4.555 update for patch 2.

**Comment by fh-mthomson** [comment]
Amazing, thank you @gtritchie for the prompt and thoughtful consideration!

**Comment by ronblum** [comment]
Verified in RStudio Desktop Pro 2024.04.2+764.pro1 using `About -> Help` and:

```
> quarto::quarto_version()
[1] ‘1.4.555’
> quarto::quarto_path()
[1] "C:\\PROGRA~1\\RStudio\\RESOUR~1\\app\\bin\\quarto\\bin\\quarto.exe"

**Comment by ronblum** [comment]
Verified in RStudio Desktop Pro 2024.07.0-daily+188.pro20 on Windows 11.

```
> quarto::quarto_version()
[1] ‘1.4.555’
> quarto::quarto_path()
[1] "C:\\PROGRA~1\\RStudio\\RESOUR~1\\app\\bin\\quarto\\bin\\quarto.exe"
```
