### ISSUE TITLE
Find in Files Replace All appears to ignore line ending project preference set in .Rproj

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14796]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0
    OS Version      : Windows
    R Version       : 4.3.2

### Steps to reproduce the problem

1. Use a git repository
2. Set the line ending in .Rproj (on Windows, select Posix line end)
3. Have a file saved in a different line ending standard (also commited into git)
4. Use find in files Replace all feature to replace file
5. Go look at the diff in the git pane after replacing the word

### Describe the problem in detail

The git diff shown in the git pane after replacement shows that the full file has changed, instead of the specific line.
This is typically a sign of change in line ending.

If you open that file in RStudio source editor, make a change, save. It is correctly saved in the .Rproj line ending, which results in a correct diff. 

I am not sure you will be able to reproduce what I am experiencing, but if you could check if that Project preference is passed in the Find in Files Replace All feature

### Describe the behavior you expected

I would expect the Find In Files replace all function to look at the Rproj preference before overwriting files. to consider this when overwriting. 

There is a high chance that my diagnostic is wrong (the workaround is rather easy too), so feel free to close!

git pane discard button works as expected fyi!
- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment]
Actually, I think it should just respect each file's initial line ending convention, especially for version-controlled documents? Do you think it is feasible to do it this way? 
It would be more general too.

**Comment by kevinushey** [comment]
This is probably the relevant bit of code:

https://github.com/rstudio/rstudio/blob/1969484876805144e8939545d29c71c4b862cd45/src/cpp/session/modules/SessionFind.cpp#L506-L512

**Comment by kevinushey** [comment]
For testing, note that you can create a file with Windows line endings on Linux / macOS with something like:

```
conn <- file("test.txt", open = "wb")
writeChar("hello\r\ngoodbye\r\n", conn, eos = NULL)
close(conn)
```

You could then confirm you have windows line endings with e.g.

```
> readChar("test.txt", 128)
[1] "hello\r\ngoodbye\r\n"
```

and note the `\r\n` sequence. Then, you can try performing a Find and Replace with 'hello' => 'HELLO', and confirm you have this afterwards:

```
> readChar("test.txt", 128)
[1] "HELLO\r\ngoodbye\r\n"
```

and note that the `\r\n` line endings were preserved.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11 using the sample above and creating files with POSIX line endings and making sure that they keep the correct line endings.
