### ISSUE TITLE
Update hosted version of MathJax to 2.7.9

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#14803]
Update the hosted MathJax at https://mathjax.rstudio.com/latest/MathJax.js to the latest 2.7 version, 2.7.9, to complement the change we made in RStudio: #11535

**Comment by gtritchie** [comment]
We're still discussing whether this change needs to happen for Cranberry Hibiscus or can wait.

**Comment by gtritchie** [comment]
For reference, this hosted copy of mathjax is used by RMarkdown.

https://github.com/rstudio/rmarkdown/blob/a9497ffa903e124a20e455e9702635ff135d9e9d/R/html_document_base.R#L268-L270

**Comment by jspiewak** [comment]
2.7.9 is uploaded.
Is it possible to test before I make it the default?

**Comment by gtritchie** [comment]
I'm looking into what tests, if any, we can run before going live with this.

**Comment by gtritchie** [comment]
Given the minor version bump (and no obvious way to test this) the RMarkdown team said it should be fine to go live.

**Comment by jspiewak** [comment]
```

**Comment by gtritchie** [comment]
The version I'm seeing at https://mathjax.rstudio.com/2.7.9/MathJax.js is not minified. Should be replaced with https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js.

**Comment by Mosk915** [comment]
I started having issues with the pagedown package a little while ago.  I traced it to this file which is referencing MathJax sources that seem to no longer exist.

https://github.com/rstudio/pagedown/blob/6763538deb2cd78de05631715ea57085a85b8bd6/inst/resources/css/jss-fonts.css#L24

**Comment by gtritchie** [comment]
Yes, appears we've broken things. Will get this reverted back to the previous state ASAP.

**Comment by cderv** [comment]
It seems the fonts are not available at the same place as before 

This is the url used in **pagedown** - note no `latest` used.
````
curl -I http://mathjax.rstudio.com/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
HTTP/1.1 404 Not Found
Connection: keep-alive
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-Key: fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
Date: Tue, 09 Jul 2024 11:59:46 GMT
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 a746325e2c0a55fa6c56e06293f59b40.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: VIE50-P2
X-Amz-Cf-Id: nKplbmiBeafqgDtJHRQsRr91HExPBo5hU73RxoGzRl0PYYIN58odXQ==
````

It seems url that works is `latest` but which points still to 2.7.2
````
> curl -I http://mathjax.rstudio.com/latest/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
HTTP/1.1 302 Moved Temporarily
Content-Length: 0
Connection: keep-alive
Date: Mon, 08 Jul 2024 16:46:36 GMT
Location: https://mathjax.rstudio.com/2.7.2/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
Server: AmazonS3
X-Cache: Hit from cloudfront
Via: 1.1 08f9b351f61685659ad70b790734f9b0.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: VIE50-P2
X-Amz-Cf-Id: qfNq0A--rm08owOFqWUSgh5FQceRLg2gcGLs9FT0p9-o6AVNXLQ7GA==
Age: 69316
````

So are we missing fonts in the update ? 
````
> curl -I http://mathjax.rstudio.com/2.7.9/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff 
HTTP/1.1 404 Not Found
Connection: keep-alive
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-Key: 2.7.9/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
Date: Tue, 09 Jul 2024 12:04:46 GMT
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 63b0889adbeadc5106837d12ac6fbc18.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: VIE50-P2
X-Amz-Cf-Id: gVaMSmVs5zZgrutllnR_x8zjvraAWfo4PImNw4MDrnhklqj8kChgvA==
```

Note that for mathjax itself it works ok and available at `latest/`

So it seems to be only a redirect problem with missing content compare what was exposed before. 
https://github.com/mathjax/MathJax/tree/legacy-v2/fonts/HTML-CSS

**Comment by cderv** [comment]
> This is the url used in pagedown - note no latest used.

I am looking in pagedown why some documents are missing the `latest/` but still the redirect should be toward `2.7.9` not `2.7.2`. 

The document with the fonts url is correctly using `latests/`
https://github.com/rstudio/pagedown/blob/6763538deb2cd78de05631715ea57085a85b8bd6/inst/resources/css/jss-fonts.css

**Comment by jspiewak** [comment]
Trying to figure out what is missing from 2.7.9 on S3.

**Comment by cderv** [comment]
> This would never have worked:

Good. This was probably a bug in pagedown never found. 

> latest points to 2.7.9 for me:

Interesting ! CDN update delay ? Or some other internet sync delay for worlwide usage ?

**Comment by jspiewak** [comment]
> > This would never have worked:
> 
> Good. This was probably a bug in pagedown never found.
> 
> > latest points to 2.7.9 for me:
> 
> Interesting ! CDN update delay ? Or some other internet sync delay for worlwide usage ?

Possibly a delay, maximum might be 24 hours.

**Comment by cderv** [comment]
> I started having issues with the pagedown package a little while ago.

@Mosk915 How long ago ? Could you open an issue in **pagedown** directly with the problem you have exactly ?

**Comment by jspiewak** [comment]
I can run an invalidation once I have resolved the actual content situation.

**Comment by jspiewak** [comment]
The `fonts` directory was missing, uploaded now:

```
(default) ➜  MathJax-2.7.9 curl -IL http://mathjax.rstudio.com/latest/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
HTTP/1.1 302 Moved Temporarily
Content-Length: 0
Connection: keep-alive
Date: Tue, 09 Jul 2024 12:32:03 GMT
Location: https://mathjax.rstudio.com/2.7.9/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
Server: AmazonS3
X-Cache: Hit from cloudfront
Via: 1.1 ed12695f521001f28371bb9e667a7eba.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: BOS50-C2
X-Amz-Cf-Id: CTnsWbhwUKY5MWq9srOqD0XVTNiaWuh6HinRgCALbIkQiHhdKcgpNQ==
Age: 970

HTTP/2 200
content-type: font/woff
content-length: 34164
date: Tue, 09 Jul 2024 12:48:13 GMT
last-modified: Tue, 09 Jul 2024 12:48:10 GMT
etag: "ac72393e49e63038d7a73c31d74d9d37"
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 07da2322976c8f91428dfa17020aeda2.cloudfront.net (CloudFront)
x-amz-cf-pop: BOS50-C2
x-amz-cf-id: yxDcfJiFh1t7bRLOQh9ImTtTkRkFrfPxqDTH8g1omjFmux_EIQB42A==
```

Are there other issues? Is there any way to test/verify?

**Comment by jspiewak** [comment]
> The version I'm seeing at https://mathjax.rstudio.com/2.7.9/MathJax.js is not minified. Should be replaced with https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js.

I'll try to figure out how the older versions were minified later today.

**Comment by cderv** [comment]
Ok so, real issue it seems. Still investigating though

Test document
````
---
title: "Test"
output: 
  html_document:
    math_method:
      engine: mathjax
      url: https://mathjax.rstudio.com/2.7.9/MathJax.js?config=TeX-AMS-MML_HTMLorMML
---

$$
x + y
$$
````

This is using the new mathjax hosted. Open the resulting document in a browser and you'll notice issue with loading fonts. 
This is creating problems in pagedown context because `pagedown::chrome_print()` is failling with 404 resources. It would be same error with html_document. 

Using another cdn seems to work ok 
````
---
title: "Test"
output: 
  html_document:
    math_method:
      engine: mathjax
      url: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-AMS-MML_HTMLorMML
---

$$
x + y
$$
````

And using `2.7.2` seems to not have the issue. 
````
---
title: "Test"
output: 
  html_document:
    math_method:
      engine: mathjax
      url: https://mathjax.rstudio.com/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
---

$$
x + y
$$

````

So something change in 2.7.9 or we are not hosting the configuration same file maybe 🤔 I am looking on Mathjax side to understand this fonts loading level. 

Idea: can we revert the redirection from `latest/` to `2.7.2` previous version, and then we keep investigating this 2.7.9 problem with our hosted version ?

**Comment by jspiewak** [comment]
Yes, we can revert the redirection, as long as we have a means of testing 2.7.9. Working on that now.

**Comment by jspiewak** [comment]
Reverted the redirect and ran invalidations.

**Comment by cderv** [comment]
And bad news: the update in RStudio IDE for local use has the same issue... 

Test file is : 
````markdown
---
title: "Test"
output: 
  html_document:
    self_contained: false
    math_method:
      engine: mathjax
      url: local
---

$$
x + y
$$
````

Browser console shows the same errors. 

It is not the default usage, so I don't think it has caused issue, but when we find the root problem of this update, this probably mean another update for locally bundled mathjax.

**Comment by jspiewak** [comment]
I have an idea for what I did wrong. Will say more in a bit.

**Comment by Mosk915** [comment]
@cderv The issue started yesterday about an hour before I commented.  It's working again now though after everything was reverted so I'm not sure if opening an issue with pagedown is still necessary.

**Comment by cderv** [comment]
@Mosk915 no thank you. I found out the problem is in Mathjax itself, and unrelated to the line you share in your post. The JS is directly loading some fonts, and not in a way that works currently in our hosted mode. 

We'll find a solution before updating again.

**Comment by cderv** [comment]
@jspiewak Do you know where do we retrieved the Mathjax version 2.7.9 for the update ? Did you use same as the one locally added ? 

I believe the change is related to the fact we don't use the `packed` version. If you compare our 2.7.2 and our 2.7.9 version we can see differences. One of them is 

````js
    MathJax.isPacked = true;
````

This is commented in 2.7.9 version, but not in 2.7.2 and in the cdn example above. 

and this is used in Mathjax for the font directory 
````js
          fontDir: e + (b.isPacked ? "" : "/..") + "/fonts",
````

This is why the font url used is probably not right as `/..` applies. 

So we probably need to use a packed version

**Comment by gtritchie** [comment]
@kevinushey prepared the bundled MathJax update not too long ago. Details on what he did here: https://github.com/rstudio/rstudio/pull/14738

**Comment by cderv** [comment]
`chrome_print` is working. So all good - this is the right version, and seems to be the exact same that we bundle in RStudio IDE 
(like the one I have on windows at `rstudio-daily\2024.07.0+293-daily\resources\app\resources\mathjax-27\MathJax.js`

So it seems all good now.

**Comment by jspiewak** [comment]
Great, I will make 2.7.9 the `latest` again, and get all the steps taken (and the test snippet) captured in the hopes of avoiding relearning all of this again in the future.

**Comment by jspiewak** [comment]
2.7.9 is `latest` again and invalidation has run:

```
(default) ➜  ~ curl -IL https://mathjax.rstudio.com/latest/fonts/HTML-CSS/TeX/woff/MathJax_SansSerif-Regular.woff
HTTP/2 302
content-length: 0
location: https://mathjax.rstudio.com/2.7.9/fonts/HTML-CSS/TeX/woff/MathJax_SansSerif-Regular.woff
date: Tue, 09 Jul 2024 17:29:47 GMT
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 cd9c85933a60bbac347299c34015e9ba.cloudfront.net (CloudFront)
x-amz-cf-pop: BOS50-C2
x-amz-cf-id: ae9VbUB4Xpj-1casXP-p4il9miOv8q4tIqXuMnphg_rjV6PJx7vwTw==

HTTP/2 200
content-type: font/woff
content-length: 12668
date: Tue, 09 Jul 2024 17:29:47 GMT
last-modified: Tue, 09 Jul 2024 15:02:28 GMT
etag: "fa1cc243e3d39b6db2a569377cce7f89"
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 cd9c85933a60bbac347299c34015e9ba.cloudfront.net (CloudFront)
x-amz-cf-pop: BOS50-C2
x-amz-cf-id: Zxa3E3E80pPaOZjVKyveBRYn8yrWx6M36xt7LURsZCTwb5BIkLNLlg==
```

**Comment by gtritchie** [comment]
## Testing Suggestions

1. In a web browser, load [https://mathjax.rstudio.com/latest/MathJax.js](https://mathjax.rstudio.com/latest/MathJax.js); this should actually load [https://mathjax.rstudio.com/2.7.9/MathJax.js](https://mathjax.rstudio.com/2.7.9/MathJax.js)
2. The Javascript displayed should be minified (i.e. not the nicely formatted original source code)
3. Search the page and ensure you find version string `2.7.9` a bunch of times, and not the older version `2.7.2`
4. In RStudio, create an RMarkdown file and paste in the "Sample Code" below
5. Knit the file to HTML; confirm preview looks correct (see "Preview Screenshot" below)
6. Go to filesystem and open the generated HTML file in a web browser
7. Confirm it looks correct (same as preview), open developer tools / Network, and confirm there are successful fetches from mathjax.rstudio.com (see "Web Browser Example" below)

### Sample Code

```RMarkdown
---
title: "Test"
output: 
  html_document:
    self_contained: false
    math_method:
      engine: mathjax
---

$$
x + y
$$
```

### Preview Screenshot

<img width="671" alt="screenshot of preview" src="https://github.com/rstudio/rstudio/assets/10569626/7f9bc5b2-48e6-446d-a40b-16c3fe691ebf">

### Web Browser Example

<img width="1333" alt="testing-html" src="https://github.com/rstudio/rstudio/assets/10569626/597eff10-f974-415f-b031-f65a943d3cfe">

**Comment by ronblum** [comment]
Verified using the above steps (thank you @gtritchie !) in RStudio Desktop 2024.07.0-daily+303 on Windows 11. Also added a few extra examples just to make sure nothing in the math has gone awry.


Source mode:
```
---
title: "Test"
output: 
  html_document:
    self_contained: false
    math_method:
      engine: mathjax
---

$$
x + y
$$

$x + 82$

$x / 12 + 56$

$$\int_0^1 x^2 \,dx= \frac13$$ $$\int_0^1 \int_0^{2\pi} r \,d\varphi\,dr$$ $$\iint_{x^2+y^2\le 1} x+y \,dx\,dy$$
```

Visual mode:


![Image](https://github.com/rstudio/rstudio/assets/31009952/ad7f9470-4456-4145-b99a-2791897b619b)

**Comment by cderv** [comment]
Great thank you all !

**Comment by aja08379** [comment]
@cderv @ronblum am I correct in thinking that this will only appear in Cranberry Hibiscus and the current dailies?
