### ISSUE TITLE
Files pane is not showing all the files or the R folder on first use

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#14807]
### System details

    RStudio Edition : Server 
    RStudio Version : 2024.07.0-daily+196 
    OS Version      : ubuntu22
    R Version       : 4.4.0

### Steps to reproduce the problem

1. Login with a fresh user that has never logged in. 
2. Observe Files Pane on first login.
3. Click to the terminal and enter `cd && touch copy.txt`
4. Click the Home button in the files pane and click the refresh button.

![filesPaneIssue](https://github.com/rstudio/rstudio/assets/1482677/5bb0c087-a7ca-4275-9463-bf11b7b4f50d)

### Describe the problem in detail
The R folder is now showing when the user first logs in. The user also does not see the file created from the terminal and refreshing the files.

### Describe the behavior you expected
I expect all files set to show to be visible and I would expect the R folder to be there.

Note: The failing tests last passed in build `2024.07.0-daily+192` and are failing the following tests:

- [ ] TestFilesPane.test_delete_file
- [ ] TestFilesPane.test_upload_file
- [ ] TestFilesPane.test_more_dropdown_menu_copy_to_file
- [ ] TestPyShinyApp.test_creating_and_running_py_shiny_demo_app
- [ ] TestFilesPane.test_more_dropdown_menu_copy_file
- [ ] test_SavePrompt.TestR.test_save_prompt_options
- [ ] TestFilesPane.test_more_dropdown_menu_move_file
- [ ] TestProjectShareAcls.test_file_upload_when_sharing_project

These need to be reenabled once this is fixed.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
These tests are all passing now and were tested in build `2024.07.0-daily+218.pro1` I reenabled the tests to run as well.

**Comment by kevinushey** [comment]
Thanks @astayleraz!
