### ISSUE TITLE
accommodate change in Copilot agent script name change

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14800]
https://github.com/github/copilot.vim/commit/53d3091be388ff1edacdb84421ccfa19a446a84d

agent.js => language-server.js

**Comment by kevinushey** [comment]
Note; example diagnostics output I see with latest version of Copilot agent. Note that the version of the Copilot agent doesn't necessarily match the version of the copilot.vim plugin that this gets pulled from.

---

## Copilot

- Version: 1.200.0
- Build: prod
- Editor: RStudio/2024.06.999-dev+999

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: n/a
- OPENSSL_CONF: n/a

## Feature Flags

- Send Restricted Telemetry: disabled
- Chat: enabled

## Node setup

- Number of root certificates: 141
- Operating system: Darwin
- Operating system version: 23.4.0
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: false
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: enabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- api.githubcopilot.com: HTTP 200
- default.exp-tas.com: HTTP 200

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+244 on Windows 11.
