### ISSUE TITLE
Debug mode focus-jumping behavior inconsistent between Desktop and Server/Workbench

### ISSUE THREAD

**Issue by keatonwilson** [rstudio/rstudio#14816]
### System details

    RStudio Edition : Server & Desktop
    RStudio Version : Server - 2024.04.1 Build 748.pro2 Desktop - 2024.04.01 Build 748 (for comparison)
    OS Version      : Windows
    R Version       : 4.4.0

### Steps to reproduce the problem
See reproducible example at: https://github.com/ksrinc/shiny_debug_reprex
1. Open debug mode (either through breakpoints or `browser`)
2. Navigate to another script or further down the script where debug is opened
3. Run code in console

### Describe the problem in detail
See videos for behavior discrepancy. In Workbench, debug mode jumps focus back to the line/chunk that is being examined when a piece of code is run in the console. This differs from the (expected) behavior on Desktop - where arbitrary code in another script or further down in the script in which debug mode is activated can be run without focus jumps. 

**Workbench Example**
https://github.com/rstudio/rstudio/assets/31970388/77745a57-31c6-4b2f-9cd2-ecc2ae8b4725

**Local Example**
https://github.com/rstudio/rstudio/assets/31970388/0fd750ce-cb1f-4331-9d54-894203705ea6
  
### Describe the behavior you expected
Behavior should be consistent across two products - in some some internal discussions, users prefer the Desktop behavior without focus jumping. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! Strangely, I'm not able to reproduce the issue you described with the same reported version of Workbench, even using the provided repository. Is it possible I'm missing some other steps required to reproduce the issue?

**Comment by keatonwilson** [comment]
@kevinushey Thanks for the follow-up on this. Hmmm. I'm not sure - I just tested in both Chrome and Edge (the two browsers currently available to me) and replicated both times. It wouldn't be anything specific to our a) RStudio Pro settings or b) our Workbench settings, would it? I couldn't find any debug-specific settings that looked related.

**Comment by kevinushey** [comment]
Yes, it sounds very similar -- I'm just flummoxed as to why I cannot reproduce the issue you describe with workbench locally.

**Comment by kevinushey** [comment]
@keatonwilson and I were able to sit down during the conference, and I was able to see the issue reproducing live on his RStudio Workbench installation. (RStudio Pro 2024.04.2, Build 764.pro1; repro'ed with both R 4.4.0 and R 4.1.2)

After executing some code, it looks like the "context_depth_changed" event is being fired from the session, which is triggering the IDE to re-focus the debugged code. Unfortunately, it's not clear what exactly is triggering this -- the event data looks normal (at a brief glance).

We were also able to reproduce outside of Shiny; it seemed to occur even with just a plain:

```R
example <- function() {
  1 + 1
  browser()
  2 + 2
}
```

in a file `example.R` that was sourced. The options from `compiler:::compilerOptions` were also the same (JIT 2).

**Comment by kevinushey** [comment]
Phew! I was able to reproduce locally with our internal Workbench instance; we'll continue to investigate and hopefully will be able to get to the bottom of this soon.

**Comment by keatonwilson** [comment]
Thanks @kevinushey - appreciate all the help today. That's great to hear on replication front - let us know if you need anything else on our end!

**Comment by kevinushey** [comment]
Some good news; I was able to identify the issue, and it appears to be a Workbench-only issue (hence why we weren't able to reproduce with open source / desktop builds of RStudio). We should have a fix available soon. Thanks for your persistence in helping us getting to the bottom of the issue!

**Comment by keatonwilson** [comment]
Success! Glad we could track it down - thanks for all the hard work on this. Our team will be ready for some more fluid debugging!

**Comment by ronblum** [comment]
Verified in
- Posit Workbench 2024.08.0+351.pro61 on Ubuntu 24 via Edge in Windows 11
- RStudio Desktop 2024.08.0+351 on Windows 11 (regression check)

using the repo in the original post, and the the simpler examples above and in issue #9918.
