### ISSUE TITLE
Broken Breakpoints Behavior in Shiny observeEvent Blocks in R 4.4.0

### ISSUE THREAD

**Issue by keatonwilson** [rstudio/rstudio#14815]
### System details

    RStudio Edition : Server & Desktop
    RStudio Version : Server - 2024.04.1 Build 748.pro2 Desktop - 2024.04.01 Build 748
    OS Version      :  Windows
    R Version       :  4.4.0

### Steps to reproduce the problem
Reproducible example can be viewed here: https://github.com/ksrinc/shiny_debug_reprex

### Describe the problem in detail
Tested on Workbench & Desktop. In < R 4.4.0, breakpoints placed inside `observeEvent` blocks behave as expected (debug mode doesn't activate until `observeEvent` block is fired within the Shiny app.  With 4.4.0, the breakpoints are activated initially on app startup and debug mode is entered early, without access to any reactive objects. Equivalent `browser` calls work fine - the issue seems to be with breakpoints specifically (see reprex above). 

### Describe the behavior you expected
Breakpoints, like `browser` calls, should not fire upon source/app launch. In `observeEvent` blocks, behavior should be equivalent - not firing until the particular code chunk fires. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- I think I've successfully reproduced this. If I set a breakpoint within the 'observeEvent' expression callback, and then start the Shiny application, I see:

```
Browse[1]> n
debug: observeEvent
Warning in pos > offsets[linepref] :
  longer object length is not a multiple of shorter object length
Browse[1]> body(sys.function())
{
    {
        .doTrace(browser())
        observeEvent
    }(input$test_button, {
        1 + 1
        2 + 2
        1 + 1
        print("Button Clicked")
    })
    output$distPlot <- renderPlot({
        x <- faithful[, 2]
        bins <- seq(min(x), max(x), length.out = input$bins + 
            1)
        hist(x, breaks = bins, col = "darkgray", border = "white", 
            xlab = "Waiting time to next eruption (in mins)", 
            main = "Histogram of waiting times")
    })
}
```

So, it seems like RStudio is injecting a trace call at the wrong location. I'll see if I can learn more.

**Comment by kevinushey** [comment]
Narrowing it down a bit more, it seems like something has changes in the way R tags expression objects with source references. If I try using:

```
debug(.rs.setShinyBreakpoints)
```

and then compare what happens between R 4.3.3 and R 4.4.0, I see an eventual invocation on each side that ends up producing different debug breakpoint 'steps', seemingly because of the differing source references. For example, we have this function body:

```
Browse[1]> body(env$fun)
{
    observeEvent(input$test_button, {
        print("Button Clicked")
    })
    output$distPlot <- renderPlot({
        x <- faithful[, 2]
        bins <- seq(min(x), max(x), length.out = input$bins + 
            1)
        hist(x, breaks = bins, col = "darkgray", border = "white", 
            xlab = "Waiting time to next eruption (in mins)", 
            main = "Histogram of waiting times")
    })
}
```

But the source references are different now:

## R 4.3.3

```
Browse[2]> attr(body(env$fun)[[2]], "srcref")
NULL
```

## R 4.4.0

```
Browse[1]> attr(body(env$fun)[[2]], "srcref")
[[1]]
observeEvent(input$test_button, {
< ... >
```

For reference:

```
Browse[1]> body(env$fun)[[2]]
observeEvent(input$test_button, {
    print("Button Clicked")
})
```

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+244 on Windows 11 after setting breakpoints in different places.
