### ISSUE TITLE
Insert anything on mac keyboards not working in quarto

### ISSUE THREAD

**Issue by ncjacquinot** [rstudio/rstudio#14824]
Hello,

In mac on a azerty french keyboard, forward slashes are typed with " Shift + : " as the forward slash is above the colon

In order to use the inline "Insert Anything" in Quarto, I would theoretically need to press " Command + Shift + : " but this doesn't give the appropriate Insert Anything shortcut

When starting a new line, the regular " Shift + : " will work as intended and offer the "Insert Anything" shortcut

I think the shortcut hasn't been mapped properly for the French azerty keyboards

Thank you

### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764
    OS Version      : MacBook Air M2 MacOS Sonoma 14.4.1
    R Version       : 4.4.0

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ncjacquinot Thank you for raising this! Did this work in previous versions of RStudio, and if so, do you remember which was the latest?

**Comment by ncjacquinot** [comment]
I have only been aware of "Insert Anything" for the past 2-3 months and this has never worked on neither of the previous versions of RStudio during that time (I keep RStudio regularly updated)

**Comment by gtritchie** [comment]
Reference: Might be similar underlying problem to [this](https://github.com/rstudio/rstudio/pull/13989), but I haven't looked closely enough to be sure.

**Comment by ncjacquinot** [comment]
Yes looks like it too, thank you

**Comment by gtritchie** [comment]
Pulling this into current release so I can take a closer look.

**Comment by kevinushey** [comment]
I did some investigation, and I believe this needs to be resolved on the Quarto side -- I've filed https://github.com/quarto-dev/quarto/issues/594 for more discussion.
