### ISSUE TITLE
Update to quarto 1.5 RC

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14827]
We should start bundling Quarto 1.5 RC with the IDE so we can get more usage and feedback.

Currently, we're pinned to use version 1.4.555; we could either update that pin to the most recent RC or switch back to the technique that uses _prerelease.json to pull down most recent version.

https://github.com/rstudio/rstudio/blob/c5cdc084aec0f885f087bdae8865ed149b76fa01/dependencies/common/install-quarto#L23-L29

**Comment by ronblum** [comment]
@kevinushey Just in time, a new dropped this morning--I'm wondering if we should pick it up, or stop where we are because these are pre-release and there will probably be more and we need to stop some time?

**Comment by gtritchie** [comment]
Moving back to test. Plan is to stay on this RC until the final bits are available (depending on timing vs. our release schedule), and we have a separate issue tracking that (#14884).

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+250.

Windows using `quarto`:
> quarto::quarto_version()
[1] ‘1.5.47’
> quarto::quarto_path()
[1] "C:\\PROGRA~1\\RStudio\\RESOUR~1\\app\\bin\\quarto\\bin\\quarto.exe"
