### ISSUE TITLE
Update node.js shipped with IDE/Workbench

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14826]
We're currently installing node.js version 18.20.3 with RStudio (set here and a couple other locations: https://github.com/rstudio/rstudio/blob/c5cdc084aec0f885f087bdae8865ed149b76fa01/dependencies/tools/rstudio-tools.sh#L480).

We should update to a newer build for next release (exact version TBD, probably v20): https://nodejs.org/en/about/previous-releases

**Comment by gtritchie** [comment]
Two angles for testing this.

(1) Confirm we are indeed installing node 20.15.0 with the IDE; install desktop and find the `node` that gets installed with it; run it via `node --version` from terminal and it will report the version
(2) Confirm that copilot is functioning (it uses this node)

**Comment by ronblum** [comment]
Verified that Copilot works in RStudio Desktop 2024.07.0-daily+306 on Ubuntu 24.04 and Window 11, and Posit Workbench 2024.07.0-daily+305.pro2 on RHEL 9.

Verified node version on Windows 11:
```
Welcome to Node.js v20.15.1.
```

Verified node version in RStudio Desktop (Ubuntu 24.04):
```
/usr/lib/rstudio$ resources/app/bin/node/bin/node --version
v20.15.1
```


Verified node version in Posit Workbench: (Red Hat 9)
```
[rstudio-server]# bin/node/bin/node --version
v20.15.1
[rstudio-server]# bin/pwb-code-server/node --version
v20.15.1
```
