### ISSUE TITLE
I had a question about two rstudio-server in  one machine centos7.9

### ISSUE THREAD

**Issue by honghh2018** [rstudio/rstudio#14837]
Hi  Developer,
     I had a need that one centos7.9 machine launch two rstudio-server with different port 8787 and 8788,
     Is had any advices for this need, how to deploy this scheme.

    In my case, the machine had different R version and need then run at the same time to process the complex data analysis. in current 
circumstances, it seemingly had not chance to  implement
Any advice would be appreciated,
Best,
hanhuihong

**Comment by StephDC** [comment]
I am assuming you are running the rstudio-server via systemd.

Disclaimer: I have not tested such setup before and there must be some better way to specify all of the config file's location. I solely rely on my understanding to the systemd template to write it. Use it at your own risk.

The following systemd unit shipped with rstudio can probably be adopted to support multiple config directories within `/etc/rstudio`.

# Usage:

1. Save the following unit file as `/etc/systemd/system/rstudio-server@.service`
1. Reload systemd with `systemctl daemon-reload`

After initial setup of the new unit file, you can create multiple instances by following these steps.
Assume you want to run a "legacy" instance and a "bleedingedge" instance, you would:

1. Make a directory for each instance of rstudio in `/etc/rstudio`
  You should have `/etc/rstudio/legacy` and `/etc/rstudio/bleedingedge`
1. Copy the following three files into each subdirectory
   1. rserver.conf
   1. rsession.conf
   1. database.conf
1. Make necessary modification to the new rserver.conf so they listen on different address - port.
1. Start each instance using `systemctl start rstudio-server@instance_name`
  namely, `systemctl start rstudio-server@legacy` and `systemctl start rstudio-server@bleedingedge`

```ini
[Unit]
Description=RStudio Server for %i
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
PIDFile=/run/rstudio-server/%i.pid
ExecStart=/usr/lib/rstudio-server/bin/rserver --config-file /etc/rstudio/%i/rserver.conf --database-config-file /etc/rstudio/%i/database.conf --rsession-config-file /etc/rstudio/%i/rsession.conf --server-pid-file /run/rstudio-server/%i.pid --server-data-dir /var/run/rstudio-server/%i
ExecReload=/usr/bin/kill -HUP $MAINPID
EnvironmentFile=-/etc/default/rstudio-server
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
