### ISSUE TITLE
Please keep cmake machinery for Qt builds

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rstudio#14832]
Commit ebea037 not only stopped building Qt-based Desktop Pro, but also removed all the cmake stuff that allowed us in Fedora to make our Qt-based build. I was trying to make a Qt build from `main` to test #14505, and I cannot anymore. :(

Note that Electron is not packaged in Fedora (there have been attempts, but it is hard to package), so we need to stick to Qt.

**Comment by gtritchie** [comment]
Unfortunately, we cannot do that. The Qt-based RStudio desktop is deprecated. We no longer build or test Qt-based RStudio ourselves as part of development and release work, and even if you can get it to build, it will be unlikely to function correctly.

For example, we have already [removed some Qt-specific code](https://github.com/rstudio/rstudio/pull/14573).

Wish I had better news for you.
