### ISSUE TITLE
Support for {webr-r} and {pyodide-python} cells

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#14831]
Similar to https://github.com/rstudio/rstudio/issues/13682

It would be the bees knees if we could have a play button inside of a Quarto document associated with the cell that automatically ran the code based on the language after the dash, e.g. `pyodide-python` would be run as`python`. 

For example, we would have: 

````md
```{pyodide-python}
x = [1, 2]
print(x)
```
````

Be evaluated in console as if it was:

````md
```{python}
x = [1, 2]
print(x)
```
````

Similarly for R, we would have: 

````md
```{webr-r}
message("Hello!")
```
````

Be evaluated as: 

````md
```{r}
message("Hello!")
```
````

This is supported by the VS Code extension for Quarto, which was implemented by JJ. 

Commit from March 2023 introducing the `-` prefix in VS Code: 

https://github.com/quarto-dev/quarto/commit/7cae24f16acefd6a1c3387924d4525bf9fe5db58

Discussion:
https://github.com/quarto-dev/quarto-cli/discussions/4761#discussioncomment-5338631

**Comment by terhorst** [comment]
Would also really like this feature.

**Comment by coatless** [comment]
@kevinushey Some more context as this is re-opened.

Fundamentally, the webR and Pyodide binaries would need to be started and available to be stored as a backend state. The current VS Code hook assumes the commands run in the normal R or Python distributions would work inside of WebAssembly. So, this behavior can be replicated but maybe with a once per session note. Though, a better part of valor may be to create a more detailed error describing that webassembly code cells must be rendered to be viewed. 

Moreover, if using the Quarto Live backend by George, some features would translate 1-to-1 due to piping behind the scenes with Observable middle-man (cross communication between R & Python immediately comes to mind).

**Comment by terhorst** [comment]
Thanks for the quick response. I'm not an RStudio dev and know nothing about its internals, so apologies if I am way underthinking this, but I'm simply looking for something that lets me hit ⌘-Enter on a `{webr}` code block in the IDE and have it evaluated in the local R environment, as works for `{r}` blocks. The current behavior is to return an error `/bin/sh: webr: command not found`.
