### ISSUE TITLE
Window title is always "RStudio" only, without project path

### ISSUE THREAD

**Issue by aushev** [rstudio/rstudio#14853]
I do have the option "Show full path to project in window title" enabled, but I still only have "RStudio" as a window title.

### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for windows
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.4.555

    OS Version      :  Windows 10
    R Version       :  4.4.0

### Steps to reproduce the problem
In the Options, have it checked Options -> General -> Advanced -> OS Integration -> "Show full path to project in window title". Click Apply, restart RStudio

### Describe the problem in detail
Window title is still "RStudio" only

### Describe the behavior you expected
Expected: project name/path in the title

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can you share a screenshot of your RStudio window in a project where you're seeing this behavior, just for extra confirmation? Is there anything unique about the project path you're using? Does this occur in all projects?

**Comment by aushev** [comment]
ouch, I just realized this feature only promises showing path for the actual _projects_ (and it does work for them), but not for any other R files/documents... So I guess this issue can be closed.
Do you know if there's any reason why it was not implemented for R files? - I can submit a feature request, but maybe I am missing something and there is some logic behind?
![image](https://github.com/rstudio/rstudio/assets/7884100/50c06f74-d4a6-40f6-ab9d-e51b7ea7ac95)

**Comment by kevinushey** [comment]
Sorry, the feature is specifically intended to only identify the active RStudio project, not open files.
