### ISSUE TITLE
desktop: file paths are not properly aliased after selection through desktop dialogs

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14851]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem

One example of these dialogs -- in the New Project Wizard, New Directory => New Project; then with the "Create project as subdirectory of:" text box, use the "Browse" button to select a directory within your home directory.

### Describe the problem in detail

You should see `~/directory` rather than `/Users/you/directory` after selection.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+245 on Windows 11.
