### ISSUE TITLE
is.nan() bad warning message

### ISSUE THREAD

**Issue by FredrikH-R** [rstudio/rstudio#14868]
### System details

RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
R Version       :  4.3.1

Note. Work only allows for delayed updating, hence the slightly older version. However, there is no reason to assume that this bug has been corrected in later versions (the warning message must be old, and no issue open or closed popped up when searching for is.nan), but correct me if i'm wrong. 

### Steps to reproduce the problem

c(1,2,NaN,4,"c") == NaN # gives desired result, but Rstudio gives warning message
is.nan(c(1,2,NaN,4))                 # correct use of ?is.nan as recommended in the documentation (numeric vectors only).
is.nan(c(1,2,NaN,4,"c"))   # does not work, but is recommended by Rstudio

### Describe the problem in detail

Rstudio gives a warning on the left hand side of the script window when evaluating a character vector for NaN entries: "use is.nan to check whether expression evaluates to NaN". However, this solution is invalid, as NaN in a character vector gets transformed to a character, which is.nan() doesn't pick up, as it is for numeric vectors only. 

### Describe the behavior you expected

No warning message when evaluating character vectors using x == NaN.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists. [Note. Close enough.}
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
You should use `x == "NaN"` instead of relying on the implicit conversion of `NaN` to the string `"NaN"`.

**Comment by FredrikH-R** [comment]
Oh absolutely. My sloppy coding is not really relevant to this bug report though, which is about Rstudio giving blatantly incorrect suggestions. Your very comment would be a far more sensible warning message than what is currently provided. 

I see you closed the issue - does this mean that the bug has been corrected in Rstudio?
