### ISSUE TITLE
Renaming  current user folder is not working

### ISSUE THREAD

**Issue by ragro** [rstudio/rstudio#14869]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.12.1-402
    OS Version      : Ubuntu 22
    R Version       : 4.4.0

### Steps to reproduce the problem
1. Goto /home directory and select the current user folder i.e mettl in my case.
2. Now click on Rename button.
3. The loader will keep going and no prompt message window comes out. Screen gets stuck as it is.

### Describe the problem in detail
While renaming the folder with name as of current user, loader is always there and does not go away. For every other folder, if we try to rename , loader comes and goes , then we get a prompt message of permission denied.

I checked the network calls and got to know that while renaming the folder, a network call with name "/rpc/rename_file" goes to backend. But in case of current user folder, this call does not happen and we get a message on console section of browser which is "Class$S327: (TypeError) : Cannot read properties of null (reading 'path')". I guess this is the culprit which is causing the loader to keep going always on screen.

### Describe the behavior you expected
While renaming the current user folder, it should work same as of other folders. A prompt window should come to say "Permission denied"
<img width="1792" alt="Screenshot 2024-06-20 at 3 47 14 PM" src="https://github.com/rstudio/rstudio/assets/36126843/1ccba2d7-816c-460b-98b0-269d433cac38">
<img width="1792" alt="Screenshot 2024-06-20 at 3 48 47 PM" src="https://github.com/rstudio/rstudio/assets/36126843/b59e2fd7-3855-4fc3-8cd0-d6f0b10521ba">

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
RStudio relies on state at a known location within the current user's home directory. You shouldn't try to rename your home directory.

**Comment by ragro** [comment]
@kevinushey then why there is infinite loader coming when we try to rename the directory. there must be some prompt window to show any message rather than blocking the complete screen with this infinite loader.
