### ISSUE TITLE
Select multiple variables from autocomplete box using key like Shift

### ISSUE THREAD

**Issue by luisvalenzuelar** [rstudio/rstudio#14866]
Say I want to populate a function with **several** of the suggested variables starting with letter `d`:

![image](https://github.com/rstudio/rstudio/assets/14203648/6cf2bb86-ef36-4d7b-8f9f-d4aed5e37ee9)

I can do this manually one by one. Another option would be to **select several using the mouse with a selector key like shift** (as one does in folders). The result would be the listed variables separated with commas.

**Comment by kevinushey** [comment]
Sorry, but this is not feasible.
