### ISSUE TITLE
RStudio modifying the PATH on MacOS

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#14861]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764 
    OS Version      : MacOS Sonoma 14.5 on M3
    R Version       :  4.4.0

### Steps to reproduce the problem

In RStudio: 
 - choose `New Project |  New Directory |  R Package | <choose any name, e.g. "testpkg">`.
 - In the console, print the PATH:  `Sys.getenv("PATH")`
 - choose `Build | Install` to build the package.
 - Print the PATH again:  `Sys.getenv("PATH")`

### Describe the problem in detail

I see a different PATH in the second print compared to the first.  In particular, it has added `/usr/local/bin:` at the start, and `:/Applications/RStudio.app/Contents/Resources/app/bin/postback` at the end.

If I build again, another copy of each of those directories is added to the path.

I notice that those two directories were on the PATH from the start of the session.  The main reason this is a problem is that my package `rgl` won't build properly if `/usr/local/bin` appears before `/opt/R/arm64/bin` on the PATH, because its configure script can't find X11 for the `arm64` architecture.

I've reproduced this on an Intel Mac with the same versions of RStudio and R. (In that case the changes are harmless.) I've been told it doesn't happen in Linux.

I mentioned this issue in https://forum.posit.co/t/how-does-rstudio-set-the-path-during-startup/188187/1 but didn't see any comments yet.

I've looked around for startup files that would have done this, but I don't think I have any.  In any case, there's no way I would have chosen the directory added at the end of the PATH; that's clearly something that RStudio is putting there.

### Describe the behavior you expected

The PATH should be unchanged across an Install.  It should never put `/usr/local/bin` first on an M3 Mac.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dmurdoch** [comment]
As mentioned in #14659, this is triggered by setting the "Automatically activate project-local Python environments" in the Python global options.  If that is not set, I still get the directory added at the end with each build, but nothing at the beginning.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+250 that the PATH isn't getting unexpectedly prepended, and that the `postback` directory doesn't keep getting added at the end. Checked on both MacOS 14 and Windows 11.
