### ISSUE TITLE
tab autocomplete slows down from dbplyr 2.3.4 -> 2.4.0+

### ISSUE THREAD

**Issue by shearerpmm** [rstudio/rstudio#14864]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764
    OS Version      : MacOS 14.3 (23D56)
    R Version       : 4.4.1 (2024-06-14) -- "Race for Your Life"

### Steps to reproduce the problem
Reference: [dbplyr issue](https://github.com/tidyverse/dbplyr/issues/1479)

```
# with dbplyr 2.3.4 --------------------------------------------------------------------------------------------


# NOTE: restart rstudio after install
devtools::install_version('dbplyr', '2.3.4')

library(dplyr)
library(dbplyr)

con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
dplyr::copy_to(con, mtcars, "mtcars")
test <- dplyr::tbl(con, "mtcars")

#' - typing `test$` and hitting tab in rstudio yields an immediate menu of autocomplete options
#' - typing `test %>% select(` does similarly


# with dbplyr 2.4.0 --------------------------------------------------------------------------------------------


# NOTE: restart rstudio after install
devtools::install_version('dbplyr', '2.4.0')

library(dplyr)
library(dbplyr)

# prepare DB and tbl_sql
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
dplyr::copy_to(con, mtcars, "mtcars")
test <- dplyr::tbl(con, "mtcars")

#' - typing `test$` and hitting tab in rstudio takes 1-2 seconds to bring up the autocomplete menu
#' - typing `test %>% select(` and hitting tab in rstudio is still pretty snappy
```

### Describe the problem in detail

Quick apology upfront: I don't know if my issue here is really RStudio's problem, because it's a feature of dbplyr that broke when dbplyr went from 2.3.4 to 2.4.0+ (see my original [dbplyr issue](https://github.com/tidyverse/dbplyr/issues/1479)). However, the issue pertains to autocomplete in RStudio, and I think RStudio expert engineers might be better-positioned to advise on where the root cause might be.

Now, the issue: Tab-autocomplete of table column names is slower when using dbplyr 2.4.0+ than 2.3.4. Autocomplete using $ is instantaneous on 2.3.4 but takes 1-2 seconds on 2.4.0. The issue also affects the current CRAN version of dbplyr (2.5.0).

While the delay in autocomplete here is only a couple seconds, I am finding that it is much worse with lazy tbls based on a JDBC connection (to my organization's Vertica database). In that case I see delays of 5-10 seconds, and they affect both $ and dplyr::select autocomplete. But it would be harder/maybe-impossible for me to provide a reprex of this, so I'm hoping that this one will suffice to diagnose the issue. 

Busted autocomplete is a huge friction in my development workflow, so I would really appreciate some ideas for how to chase this down, even if it's not a complete solution.

### Describe the behavior you expected

When I use tab autocomplete to show the list of columns in a dbplyr tbl, the names should show up instantaneously, rather than with multiple seconds of delay.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be resolved in the next daily builds via https://github.com/rstudio/rstudio/commit/95bdcf2abbb0284eff49ffd54f71837c7b200b31.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+240 on Windows 11. Checked with both `dbplyr` 2.4.0 and 2.5.0 (the current version).
