### ISSUE TITLE
Wrong diagnostic for `expect_*()` tests unexpected assignment in argument list; did you mean to use '='

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14870]
### System details

    RStudio Edition : Desktop
    RStudio Version : all?
    OS Version      : all
    R Version       : all

### Steps to reproduce the problem

1. Turn on R diagnostics

2. In a saved R file (because diagnostics don't show in unsaved files) put the following code

```r
library(testthat)
f <- function(x) {
 message("a message")
  x ^ 2
}

expect_message(res <- f(2))
```

### Describe the problem in detail

A diagnostic shows

![image](https://github.com/rstudio/rstudio/assets/52606734/51a009a6-8586-41ce-ba63-806950682c4e)

Which is incorrect 

### Describe the behavior you expected

Similar to https://github.com/r-lib/lintr/issues/2267, I would expect no diagnostic there. To avoid this lint, there are other alternatives https://www.tidyverse.org/blog/2021/10/testthat-3-1/#breaking-changes

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Removed in https://github.com/rstudio/rstudio/commit/157d569db075cc5230cb620f489fc6f111ccade1.
