### ISSUE TITLE
Dragging file into console/source pane inserts filepath

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#14878]
On macOS, clicking a file in Finder and dragging it into Terminal inserts the path to the file in Terminal. It'd be nice if the same happened in Rstudio. 

Cherry-on-top would be if the path RStudio inserted was *not* an absolute file path, but automatically resolved paths relative to the project directory, or inserted `~` for files outside the project but within the home directory.

**Comment by gtritchie** [comment]
Closing as a duplicate of #4037.
