### ISSUE TITLE
Headings not in outline anymore if "|" before text 

### ISSUE THREAD

**Issue by JakobMie** [rstudio/rstudio#14877]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2024.04.2
    OS Version      : Windows 10
    R Version       : 440 64 bit

### Steps to reproduce the problem

write

```
# | HEADINGS | ####
```

and check if it shows up in the outline

### Describe the problem in detail

all my

```
# +----------+
# | HEADINGS | ####
# +----------+
```

do not show up in the RStudio outline anymore because now they would need to be

```
# +----------+
# HEADINGS | ####
# +----------+
```

Is there a way to change this back or do I have to re-write every file I wrote in the last 10 years? And if they decide to change it to

```
# +----------+
# HEADINGS ####
# +----------+
```

In the next update, how can I make sure that doesn't affect me?

### Describe the behavior you expected

I expected to see my headings in the outline and no change in default that breaks years of files.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by JakobMie** [comment]
allright, didn't expect this to be markdown code. Assume everything in bold is commented out.

**Comment by JakobMie** [comment]
The Stackoverflow issue where we came to the conclusion that it is a bug is here: https://stackoverflow.com/questions/78521651/changing-the-rstudio-document-outline-defaults

**Comment by ronblum** [comment]
@JakobMie Thank you for raising this! I've tried reproducing it with RSTudio Desktop 2024.04.2+764 on Windows 11, but I'm unable to. Combining the examples you provided: With

```
---
title: "Headings"
output: html_document
date: "2024-06-21"
---

# | HEADINGS1 | ####

bobo

# +----------+
# | HEADINGS2 | ####
# +----------+

momo

# +----------+
# HEADINGS3 | ####
# +----------+

gogo

# +----------+
# HEADINGS4 ####
# +----------+

dodo
```

I get:
![outline](https://github.com/rstudio/rstudio/assets/31009952/29b57ca6-7914-4e3a-a1bb-23f7e3b6c4df)

That's the same as with an earlier versions, like 2022.12.0+353 and 2023.12.1+402. Can you grab a screenshot of what you get with this code?

**Comment by JakobMie** [comment]
Sure, here it is. Headings 3 and 4 show up in the outline, headings 1 and 2 do not.

R version: R-4.4.0
RStudio version: 2024.04.2 
![ScreenshotRstudio](https://github.com/rstudio/rstudio/assets/43111712/e04bec0b-4cdc-4c06-9352-5dbbf1f76de3)

**Comment by JakobMie** [comment]
If someone knows how to delete the "info needed" label, that would be great

**Comment by kevinushey** [comment]
This is likely resolved in the latest daily builds. The issue here was that `# |` was being recognized as a Quarto comment prefix; that is, we were accepting whitespace between `#` and `|`. That should now be tightened up.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11. I used both the original examples and the longer one that I created, in both R Markdown and Quarto.
