### ISSUE TITLE
Create Linux AMIs needed for IDE Certification 

### ISSUE THREAD

**Issue by jlang-311** [rstudio/rstudio#14888]
This is continued work to complete the work needed to have the automated tests for IDE certification in our CI pipeline. To start, we'll focus on Linux AMIs. We need AMIs for the following environments:

- [x] Desktop Open Source (Debian 11, Desktop Open Source, 3.6.3)
- [x] Desktop Open Source (Debian 12, Desktop Open Source, 4.2.3)
- [ ] Desktop Open Source (Fedora 39, Desktop Open Source, 4.3.3)
- [ ] Desktop Open Source (Fedora 40, Desktop Open Source, 4.41)
- [x] Desktop Open Source (openSUSE 15.5, Desktop Open Source, 4.2.3)
- [x] Desktop Open Source (RHEL 8, Desktop Open Source, 4.0.5)
- [x] Desktop Open Source (SLES 15 SP5, Desktop Open Source, 4.3.3)
- [x] Desktop Open Source (Ubuntu 20.04, Open Source Server, 3.6.3)
- [x] Desktop Open Source (Ubuntu 22.04, Desktop Open Source, 4.3.3)
- [x] Desktop Open Source (Ubuntu 24.04, Desktop Open Source, 4.4.1)

**Desktop Pro 3**
- [x] Desktop Pro (RHEL 9, Desktop Pro, 4.2.3)

**Open Source Server 4**
*(Note: These already exist and tests for it are run by the Workbench folks)*
- [x] Open Source Server (RHEL 8, Open Source Server, 4.3.3)
- [x] Open Source Server (SLES 15 SP5, Open Source Server, 4.2.3)
- [x] Open Source Server (Ubuntu 20.04, Open Source Server, 3.6.3)
- [x] Open Source Server (Ubuntu 22.04, Open Source Server, 4.1.3)
- [x] Open Source Server (Ubuntu 24.04, Open Source Server, 4.4.1)

**Comment by jlang-311** [comment]
@ronblum @dskard @kevinushey I created this issue to track the continued AMI creation work for IDE certification.

**Comment by ronblum** [comment]
I added Ubuntu 20 to the "Desktop Open Source" list to make sure that we don't overlook it, since the project is targeted for desktop.

**Comment by dskard** [comment]
@ronblum I noticed that `Desktop Open Source (RHEL 8, Desktop Open Source, 4.0.3)` is looking for R 4.0.3. There was a R 4.0.5 released as well. Should use 4.0.5 or stick with 4.0.3?

**Comment by dskard** [comment]
AMI Status:

| product | operating system | fuzzbucket alias | original ami | new ami | can connect via VNC ? |
| ------------ | ------------------------- | ----------------------- | ------------------- | -------------- |:--------------------------------:|
| Desktop | Debian 11              |                              |                         |                    |                                          |
| Desktop | Debian 12              |                              |                         |                    |                                          |
| Desktop | Fedora 39              |                              |                         |                    |                                          |
| Desktop | Fedora 40              |                              |                         |                    |                                          |
| Desktop | OpenSUSE 15.5    |                              |                         |                    |                                          |
| Desktop | RHEL 8                   | rhel8-ide-prereqs-ci           | ami-0718bb425ce918f8f |                    |     |
| Desktop | RHEL 9                   | rhel9-ide-prereqs-ci           | ami-061851c8a4d8d55fd |                    |    |
| Desktop | SLES 15 SP 5         | sles15.5-ide-prereqs-dev  | ami-03432f0949f209a11 |                    |     |
| Desktop | Ubuntu 20.04       |                              |                         |                    |                                          |
| Desktop | Ubuntu 22.04       | ubuntu22-ide-prereqs-ci  | ami-0fcd15a83b0ef2ac4 | ami-03301d64b7f61489f |   |
| Desktop | Ubuntu 24.04       | ubuntu24-ide-prereqs-ci  |                         |                    |                                          |
| Server    | RHEL 8                   | rhel8-ide-prereqs-ci           | ami-0718bb425ce918f8f  |                    | -- |
| Server    | SLES 15 SP 5         | sles15.5-pwb-prereqs-ci    | ami-08ba3e2ef637562ba |                    | -- |
| Server    | Ubuntu 20.04       | ubuntu20-pwb-prereqs-ci | ami-0072cc5985e0b818a |                    | -- |
| Server    | Ubuntu 22.04       | ubuntu22-pwb-prereqs-ci | ami-0c1e1aaf4dd58c4f6  |                    | -- |
| Server    | Ubuntu 24.04       | ubuntu24-pwb-prereqs-ci | ami-0aca154485ce3cbb4 |                    | -- |

**Comment by ronblum** [comment]
> @ronblum I noticed that `Desktop Open Source (RHEL 8, Desktop Open Source, 4.0.3)` is looking for R 4.0.3. There was a R 4.0.5 released as well. Should use 4.0.5 or stick with 4.0.3?

(Finally a reply) 4.0.5. I probably mistyped `.3` because all of the other versions end in `.3`.

**Comment by jlang-311** [comment]
@dskard I am closing this and have move the last two environments that were not completed to this [issue](https://github.com/rstudio/rstudio-ide-automation/issues/2275)
