### ISSUE TITLE
Include Quarto in list of registered trademarks in About dialog

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14886]
Quarto should be mentioned along with RStudio and Shiny in the highlighted region of the About dialog.

"RStudio, Quarto, and Shiny are registered trademarks of Posit Software, PBC..."

<img width="652" alt="trademarks-about" src="https://github.com/rstudio/rstudio/assets/10569626/560f51a9-99be-4c71-a306-99107ba19b8b">

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+257 on Windows 11.
