### ISSUE TITLE
Include released quarto 1.5 with IDE

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14884]
The IDE is currently using RC builds of Quarto 1.5.

This issue tracks making sure we update the final release build of Quarto 1.5.

**Comment by gtritchie** [comment]
The Quarto 1.5 release is v1.5.52. I was told there will be a patch one week from today (i.e. on July 8) so might be good to hold off for that one.

**Comment by gtritchie** [comment]
Moving back to in-progress, will likely take a couple more Quarto .x releases before we lock down.

**Comment by gtritchie** [comment]
Updated to quarto 1.5.54 via https://github.com/rstudio/rstudio/commit/6cc3777d4042609c45dea6525f4652d4ac3b9d6e.

**Comment by ronblum** [comment]
Verified 1.5.54 with `quarto::quarto_version` and <kbd>Help -> About RStudio</kbd> in RStudio Desktop 2024.07.0-daily+303 on Windows 11.

**Comment by olivroy** [comment]
Quarto 1.5.56 has been released fixing some regressions. Is it planned to bundle it with the next version?

**Comment by gtritchie** [comment]
> Quarto 1.5.56 has been released fixing some regressions. Is it planned to bundle it with the next version?

Yes, we will update Quarto for the next release, tracked via https://github.com/rstudio/rstudio/issues/15039.
