### ISSUE TITLE
Update node.js to pickup security fixes

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14898]
Per https://nodejs.org/en/blog/vulnerability/july-2024-security-releases there will be another v20.x node released in the first few days of July to pickup fixes to 1 high severity issue, 2 medium severity issues, and 3 low severity issues.

We should update to this once released (recently updated to node.js 20.15 via https://github.com/rstudio/rstudio/pull/14887).

**Comment by ronblum** [comment]
Verified that Copilot works in RStudio Desktop 2024.07.0-daily+306 on Ubuntu 24.04 and Window 11, and Posit Workbench 2024.07.0-daily+305.pro2 on RHEL 9.

Verified node version on Windows 11:
```
Welcome to Node.js v20.15.1.
```

Verified node version in RStudio Desktop (Ubuntu 24.04):
```
/usr/lib/rstudio$ resources/app/bin/node/bin/node --version
v20.15.1
```


Verified node version in Posit Workbench: (Red Hat 9)
```
[rstudio-server]# bin/node/bin/node --version
v20.15.1
[rstudio-server]# bin/pwb-code-server/node --version
v20.15.1
```
