### ISSUE TITLE
Upper case letter in project name for Quarto causes an error

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14894]
### System details

    RStudio Edition : Server and Server-Pro, Desktop and Desktop-Pro
    RStudio Version : 2024.07.0-244
    OS Version      : Linux
    R Version       : any

### Steps to reproduce the problem

Note: this was moved from the pro repo since it's a problem in both open-source and pro: https://github.com/rstudio/rstudio-pro/issues/6505

1. create a new quarto project
2. in the project name use an upper case letter (ex. testQuartoproj)
3. create the project

### Describe the problem in detail

![image](https://github.com/rstudio/rstudio/assets/10569626/69c09c88-5fac-4943-a1af-8a0a7259243e)

An error message with the title "Error while opening file" and the message "No such file or directory" appears and no file is opened (blank area in IDE).

The problem appears to be that the quarto source file created for the project is all lower-case (e.g. `testquartoproj.qmd` instead of the expected `testQuartoproj.qmd`)

This started with the upgrade to Quarto 1.5. If I use the qvm to have most recent IDE build use Quarto 1.4 the problem goes away, so it's in Quarto, not the IDE itself.

### Describe the behavior you expected

Quarto source file name's case matches project case.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
An example quarto command to repro this is:

`quarto create-project ~/myQuartoTest --type default --engine knitr --editor visual`

**Comment by gtritchie** [comment]
Tracked in quarto via: https://github.com/quarto-dev/quarto-cli/issues/10151

**Comment by cscheid** [comment]
Sorry, folks, this will be fixed soon. I'm glad we caught it before the release!
