### ISSUE TITLE
Ctrl-s unresponsive after cancelling the "Choose Encoding" window

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#14896]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2024.04.2 Build 764
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem
1. Open Rstudio, New File -> R Script
2. Copy the following text in the new file:
```
# Text with UTF-8 characters
# $ £ И ह € 한 𐍈
```
4. Use Crtl-s to save the file. The window "Choose Encoding" appears. Click "Cancel" to close the window.
5. Use Crtl-s again. Nothing happens.

### Describe the problem in detail
When the scripts contains UTF-8 characters, the cancellation of the choice of encoding makes the shortcut Ctrl-s unresponsive. 

### Describe the behavior you expected
Ctrl-s should trigger the "Choose Encoding" window even after a first cancellation.

(Edited because the boxes were not correctly formatted)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@pascaloettli Thank you for raising this! I can reproduce this on Ubuntu 22.04 and Windows 11, as well. It looks like this has been around for a long time--I can also reproduce this in RStudio Desktop 2022.12.0+353. 

Note: Using the <kbd>File -> Save</kbd> also fails, but "Save As" and "Save with Encoding" work.

**Comment by gtritchie** [comment]
Note to self: the bug, ultimately, is that we don't reset `isSaving_` back to `false` in this scenario. Thus, future save attempts become no-ops:

https://github.com/rstudio/rstudio/blob/9cc10f8c5ea6c29ec80324b6c34ba4286c439a8b/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L4061-L4066

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+66 by checking both with saving using <kbd>Ctrl-S</kbd> and with <kbd>File -> Save With Encoding</kbd>.

**Comment by pascaloettli** [comment]
Still does not work in 2024.09.0 Build 375

**Comment by gtritchie** [comment]
Correct, this is fixed in the next release, not 2024.09.

**Comment by pascaloettli** [comment]
> Correct, this is fixed in the next release, not 2024.09.

Oops, sorry for the mistake.
