### ISSUE TITLE
Support cursor motion ANSI control sequences in Console

### ISSUE THREAD

**Issue by jucor** [rstudio/rstudio#14942]
Dear Rstudio team, in particular @gtritchie who is the master of all things Console and ANSI characters

While using [pyMC](https://github.com/pymc-devs/pymc) with reticulate in Rstudio, I have discovered that the progress bars on long operations were severely misbehaving, generating so much output that it even brought Rstudio to its knees due to the load on the console and the Rmarkdown inline output. 
I filed bug-reports:
- in Reticulate https://github.com/rstudio/reticulate/issues/1632 
- in Rich https://github.com/Textualize/rich/issues/3416 
- and  commented in pyMC: https://github.com/pymc-devs/pymc/pull/7233#issuecomment-2212024118 

After diving deep into the source, I realise that this is down to cursor movement ANSI control sequences not being supported in the Console implementation (thanks @gtritchie for the comments):
https://github.com/rstudio/rstudio/blob/c03e95646f4031183cdf3c8b33c74f60e6ca07d1/src/gwt/src/org/rstudio/core/client/AnsiCode.java#L287

[Separately, while investigating this, I suspect there's also a bug there, see #14941  ]

Having the Console support Cursor motions would fix all 3 downstream bugs above, and, more importantly, would allow the proper in-Rstudio use of all tools that use the [Rich](https://github.com/Textualize/rich) library. 

I realise this is a shot in the dark, but that would be terrific. Thanks for considering!

**Comment by ronblum** [comment]
@jucor Thanks for the enhancement request! Agreed, it is a shot in the dark. But @gtritchie, the master as you say, could probably explain this far better than I could.

**Comment by ronblum** [comment]
Verified in RStudio Desktop Pro 2024.10.0-daily+131.pro1, similar to #14941.

**Comment by jucor** [comment]
Amazing, thank you very much @kevinushey and @ronblum !!
