### ISSUE TITLE
Something in the last few daily builds broke something on Windows

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14950]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.7.0.306
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem

@kevinushey I don't really know what happened.

This morning, I decided to upgrade from the +292 daily to +306 on Windows.

I updated packages with pak and `install.packages()`, restarted session as usual, but something went wrong.

I tried reverting back to +278, but the issue remains. Looks like a change in the last week or so triggered something on my machine.

Can no longer access help.

My Rprofile has (probably) too much stuff in it, but for example, I have a few `check_installed()` calls in it and it prompts me everytime to install them

I use `rlang::global_handle()`.

And now, it asks me everytime even though I have everything installed.

Something related to package installation / active bindings / unloading went wrong on my side.

```
Error in tools:::httpd(query, NULL, NULL) : 
  lazy-load database 'C:/PROGRA~1/R/R-43~1.2/library/tools/R/tools.rdb' is corrupt
```

### Describe the problem in detail

Nothing works, my R installation broke. I don't know how to debug things. I get warning when I type in console.

I will uninstall R and try again, but this is a bit inconvenient and I have no idea how to provide more details.

Appreciate any pointers 😞 .

I am afraid you won't be able to reproduce my issue.

I get these warnings on startup.

3: Dans as.list.environment(ns) : internal error -3 in R_decompress1
4: Dans as.list.environment(ns) :
  redémarrage de l'évaluation d'une promesse interrompue
5: Dans as.list.environment(ns) : internal error -3 in R_decompress1

**Comment by olivroy** [comment]
I managed to uninstall + reinstall R + installed something in between +293 daily and am running smoothly. I will be happy to do further testing as needed if you can think of something

**Comment by olivroy** [comment]
Glad you couldn't reproduce it! Maybe I am doing things I shouldn't be doing... I just installed the latest build +310.

**Comment by ronblum** [comment]
@olivroy Does closing the issue mean that things are working for you on build 310? 🤞

**Comment by olivroy** [comment]
Haven't got issues today! Let's hope for the best ☘️
