### ISSUE TITLE
Creating a new project on a UNC path stores it in the wrong location

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14964]
### System details

    RStudio Edition : Windows Desktop
    RStudio Version : Any Electron version (tried back to 2022.07.2-576)
    OS Version      : Windows-11
    R Version       : Any

### Steps to reproduce the problem

- ensure you have read/write access to a shared folder, e.g. `\\gary-pc\stuff`
- File / New Project / New Directory / New Project, click Browse to choose a folder
- type or browse to UNC folder, e.g. `\\gary-pc\stuff` and click Open
- give the project folder a name such as `yay` then click "Create Project"

### Describe the problem in detail

- instead of creating the project at `\\gary-pc\stuff` it creates it on the local system at `C:\gary-pc\stuff\yay` (it treats the computer name as a folder in the root directory, creating it if necessary)

### Describe the behavior you expected

- project gets created where I told it to be created

### Other Notes

- This Windows-specific scenario hasn't worked since the switch to Electron. It did work in the Qt-based 2022.07.2 release, and in a recent-ish Qt-based Desktop Pro build (2024.04.0+735.pro3)
- You can successfully browse to and open an existing document stored on a UNC path. Once opened you can edit and save without problems. The problem seems specific to saving a new file to a UNC path.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+216 on Windows 11. (First tested in 2024.09.0+375 to reproduce the issue.)
