### ISSUE TITLE
Cannot save new file to a UNC path on Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14963]
### System details

    RStudio Edition : Windows Desktop
    RStudio Version : Any Electron version (tried back to 2022.07.2-576)
    OS Version      : Windows-11
    R Version       : 3.6.3 (but doesn't matter)

### Steps to reproduce the problem

- ensure you have read/write access to a shared folder, e.g. `\\my-computer\stuff`
- create a new R script in RStudio, try to save it as (for example): `\\my-computer\stuff\test.R`

### Describe the problem in detail

Get an error dialog: "Error Saving File" - "Error saving /my-computer/stuff/test.R: The system cannot find the path specified".

### Describe the behavior you expected

Be able to save the file.

### Other Notes

- This Windows-specific scenario hasn't worked since the switch to Electron. It did work in the Qt-based 2022.07.2 release, and in a recent-ish Qt-based Desktop Pro build (2024.04.0+735.pro3)
- You can successfully browse to and open an existing document stored on a UNC path. Once opened you can edit and save without problems. The problem seems specific to saving a new file to a UNC path.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
See also #14964.

**Comment by kevinushey** [comment]
I'm kind of shocked we haven't heard more about this; I imagine there are a lot of Windows users working with shared files / folders. Or is everyone just using mapped network drives, a la https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d?

**Comment by gtritchie** [comment]
Drive letters are easier to remember so perhaps more common than raw UNC paths. Easiest way to map and understand-map them is with "net use" command. https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/gg651155(v=ws.11)

**Comment by ronblum** [comment]
I'm on the shocked side, too, because we've gotten bugs about UNC paths in the path. I remember this mostly because I've learned to ask if drive mapping works (which it almost always does).

Verified in RStudio Desktop Pro 2024.10.0-daily+131.pro1 on Windows 11.
