### ISSUE TITLE
Update to latest Electron point release  (30.2.0)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14968]
Cranberry H is currently using Electron 30.1.2, but 30.2.0 came out a few days ago with several fixes we should get into the release.

https://releases.electronjs.org/release/compare/v30.1.2/v30.2.0

While we're at it we should also bump up the version of the dev-dependency `lint-staged` from 15.2.2 to 15.2.4.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0+321 based on <kbd>Help -> About RStudio</kbd> identified Electron 3.20.0. Will also run test suite to try out different parts of the UI, but the correct version of Electron is installed.
