### ISSUE TITLE
Unable to display tidytables to console

### ISSUE THREAD

**Issue by braithwj** [rstudio/rstudio#14977]
### System details

    RStudio Edition : Both Desktop and Server
    RStudio Version : 2024.04.2+764
    OS Version      : RHEL 9, Windows Server 2019, and Windows 11
    R Version       : 4.3.x (Confirmed on 4.3.2 and 4.3.3)

### Steps to reproduce the problem
First open an Rmd file for editing, new R Markdown files also produce this behavior. Then in the RStudio Console window, type the following two lines
```
library(tidytable)
head(tidytable::as_tidytable(cars))
```
This behavior will remain until you close out the Rmd file, and restart the R session.
### Describe the problem in detail
The head command is accepted, but nothing is output in the console.
![image](https://github.com/user-attachments/assets/252bb225-eb4b-4b58-ab4b-0dfcc5676e7a)
The output displays fine if editing an Rmd file and chunking inline. It also displays fine if calling R from the terminal window. Additionally, I tested R 4.2.3 and it displays okay on that version of R. I was able to reproduce with a brand new install of R, RStudio, and tidytable.

### Describe the behavior you expected
Normally, this would show a few lines in the output afterwards:
![image](https://github.com/user-attachments/assets/7baf5220-bed0-4b88-9f08-b234eed205f2)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@braithwj Thank you for raising the issue! I can also reproduce this with RStudio Desktop 2022.12.0+353 and 2024.07.0+329 on Windows 11 using R 4.4.1, with both R Markdown and Quarto files. In addition, this works in the R Markdown file when sending output inline, but fails when sending to the console.

**Comment by braithwj** [comment]
@ronblum, looks like it was a tidytable issue. Weird since it worked on R 4.2.3 with 0.11.0 but good enough for me! https://github.com/markfairbanks/tidytable/pull/814
