### ISSUE TITLE
`Reformat code` inserting spaces around superscripts

### ISSUE THREAD

**Issue by d-morrison** [rstudio/rstudio#14973]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2 Build 764
    OS Version      :  Windows 11
    R Version       :  4.4.1

### Steps to reproduce the problem

1. Type `10^3` in Rstudio file editor
2.  "Reformat Code" (through either keyboard shortcut or dropdown menu)

### Describe the problem in detail

`10^3` gets reformatted to `10 ^ 3`, contrary to the [tidyverse style guide](https://style.tidyverse.org/syntax.html#infix-operators)

### Describe the behavior you expected

Reformatting should do nothing to this expression.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by d-morrison** [comment]
(also occurs on Posit Cloud)

**Comment by ronblum** [comment]
@d-morrison Thank you for raising this! I can also reproduce this in RStudio Desktop 2024.07.0+321 on Windows 11. I'll mark this for review.

As per the above, the Tidyverse style guide explicitly notes this as bad formatting. Some formatting works. From the guide:
```
sqrt(x^2 + y^2)
df$z
x <- 1:10
```

We're adhering to most of this. Reformatting this code returns:
```
sqrt(x ^ 2 + y ^ 2)
df$z
x <- 1:10
```

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+66 on Windows 11. Checked
* in and R script, and R Markdown and Quarto in both source and visual modes.
* that the original examples end up formatted correctly.
* that bad formatting is corrected correctly:

```
1+ 1
sqrt(x ^ 2 + y ^ 2)
df $ z
x <-1: 10
```

is reformatted as:
```
1 + 1
sqrt(x^2 + y^2)
df$z
x <- 1:10
```
