### ISSUE TITLE
Update to Electron 31

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#14982]
Update Kousa Dogwood to Electron 31.x, along with updates to other pinned packages.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+66 on Windows 11 by checking <kbd>Help -> About RStudio</kbd>: `Electron/31.3.0`.

**Comment by gtritchie** [comment]
Repurposing for minor Electron update from 31.5 to 31.6.

**Comment by gtritchie** [comment]
I backed out the upgrade to 31.6; it caused build breaks on opensuse15 and rhel8. Downgrading to unblock builds and will investigate.

**Comment by gtritchie** [comment]
Reopening, we want to take v31.7.1.

**Comment by gtritchie** [comment]
Reusing for 31.7.2.

**Comment by gtritchie** [comment]
Updating Kousa Dogwood to 31.7.4 via https://github.com/rstudio/rstudio/pull/15421.

**Comment by gtritchie** [comment]
Updating Kousa Dogwood to 31.7.5 via https://github.com/rstudio/rstudio/pull/15435.

**Comment by gtritchie** [comment]
Confirmed that builds are now using Electron 31.7.5 (I tested 2024.12.0+436 on macOS).
