### ISSUE TITLE
Support for OPENSSL 3

### ISSUE THREAD

**Issue by dshakey** [rstudio/rstudio#14993]
### System details

    RStudio Edition : Server
    RStudio Version : 2024.04.2-764
    OS Version      : redhat
    R Version       : 4.3

### Steps to reproduce the problem

Starting Rstudio
`/usr/lib/rstudio-server/bin/rserver: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

### Describe the problem in detail

there has been critical vulnerability with openssl 1 and vendors has just started push fixes and upgrading openssl to version 3.
but rstudio server is looking for openssl 1.1.1.

i have tried create symlink to newer version but still rstudio wants version 1.1.1

### Describe the behavior you expected

to support open ssl 3

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by lachlansimpson** [comment]
Hi,

Thanks for reporting this.

Can you please confirm you have downloaded the correct installation file for your Operating System?

This error is most often seen when the installer for the wrong OS has been used. 

You can check using the output of these two commands.

```
grep PRETTY_NAME /etc/os-release
rstudio-server version
```

Regards,
Posit Support

**Comment by dshakey** [comment]
The os is redhat 9.4, using the ubi9:latest image.

**Comment by ronblum** [comment]
@dshakey Thanks! I'm unable to reproduce the issues--build 2024.04.2-764 works for me on Red Hat 9.4. Can you check the SHA-256 hash of the install file? `sha256sum rstudio-server-rhel-2024.08.0-334-x86_64.rpm `

**Comment by ronblum** [comment]
Quick check that the system is using OpenSSL 3.0 (I hope that I'm not missing any old versions):
```
[root@localhost lib]# find /usr/lib*/ -name libssl\*
/usr/lib64/pkgconfig/libssl.pc
/usr/lib64/libssl.so.3
/usr/lib64/libssl.so
/usr/lib64/libssl3.so
/usr/lib64/libssl.so.3.0.7
[root@localhost lib]# openssl version
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
```

**Comment by dshakey** [comment]
Not my computer. I'll check that for you. But yes had same openssl version.
But when i ran rstudio-server it was looking for openssl 1.1.1

**Comment by StephDC** [comment]
@dshakey  I am suspecting that you downloaded the wrong rstudio rpm package from the rstudio.org download page.

Please do a quick sha256sum on your file to see if you downloaded the one compiled against rhel8 - openssl 1.1

# Extra Info

For RHEL 8 with rstudio-server compiled against rhel8 - openssl 1.1:

```
$ wget https://download2.rstudio.org/server/rhel8/x86_64/rstudio-server-rhel-2024.04.2-764-x86_64.rpm

$ sha256sum rstudio-server-rhel-2024.04.2-764-x86_64.rpm
2dee2a7a9003ca6258e6d5ead8a9d7e34c2653abbc71e5f4c0eb7bbe85cf08f6  rstudio-server-rhel-2024.04.2-764-x86_64.rpm

$ ldd /usr/lib/rstudio-server/bin/rserver
        linux-vdso.so.1 (0x00007ffea90c6000)
        libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007f4aa537d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4aa5179000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4aa4f59000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f4aa4d55000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f4aa4b4d000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f4aa4945000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f4aa472d000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f4aa4499000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f4aa3fae000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f4aa3d9e000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4aa3a09000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4aa3687000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4aa346e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4aa3098000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4aa5ecf000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f4aa2e67000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f4aa2c61000)
```

For RHEL 9 with rstudio-server compiled against rhel9 - openssl 3:
```
$ wget https://download2.rstudio.org/server/rhel9/x86_64/rstudio-server-rhel-2024.04.2-764-x86_64.rpm

$ sha256sum rstudio-server-rhel-2024.04.2-764-x86_64.rpm
dd9819fd3f0f7aef2078dbfb790002a49458aa8b12af846175374865f44becf7  rstudio-server-rhel-2024.04.2-764-x86_64.rpm

$ ldd /usr/lib/rstudio-server/bin/rserver
        linux-vdso.so.1 (0x00007ffc61593000)
        libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007f258ab03000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f258aaf9000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f258aadf000)
        libssl.so.3 => /lib64/libssl.so.3 (0x00007f258aa39000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f258a606000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f258a5f4000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f258a3c9000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f258a2ee000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f258a2d2000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f258a0c9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f258b2ca000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f258a09a000)
        libeconf.so.0 => /lib64/libeconf.so.0 (0x00007f258a08f000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f258a084000)
```

You may also realize that the downloaded file name is exactly the same, and the download url only differs by the tiny 1 digit of rhel8 -> rhel9, thus if you are only starting with the rpm file, you might never realize the issue till you try to start rstudio-server.

# Recommendation

To Rstudio RPM packager: in order to avoid such mix-up in the future, I would make the following two recommendations.

1. Rename the produced rpm package to include the RHEL version number, such as rstudio-server-rhel*9*-2024.04.2-764-x86_64.rpm
1. Add the libssl so file (`libssl.so.1.1` for rhel8 and `libssl.so.3` for rhel9) so the user would know the mistake in the form of unmet dependency when using rpm to install the package.

**Comment by dshakey** [comment]
My bad. I should have used rhel9 path. Our docker has been same for years .
But base image got upgrade to rhel9. Anyone happy to close this. Thanks for
time
