### ISSUE TITLE
Adding support for ppc64le  architecture

### ISSUE THREAD

**Issue by sid226** [rstudio/rstudio#15003]
Hi @ronblum 

I am exploring the possibility of making binary and CI available on ppc64le  architecture.

I am able to successfully build and run tests  for latest version of Rstudio  [v2024.04.2+764](https://github.com/rstudio/rstudio/releases/tag/v2024.04.2%2B764) on ppc64le  architecture 

I am ready to share the patches.

Any reference for adding binary and CI support , will be helpful. Thanks

**Comment by ronblum** [comment]
@sid226 Neat! I'll ask if we have anything that might help.

Also, a while back another RStudio user, @andresrcs, [built RStudio Server for Raspberry Pi](https://andresrcs.rbind.io/2022/09/05/shiny_rstudio_server/), so he might be able be able to provide advice.

**Comment by gtritchie** [comment]
We won't be supporting the ppc64le architecture, so am closing this issue.

**Comment by ghatwala** [comment]
hey @gtritchie  - we could help in setting/owning up CI job on power platform as well if this helps to offload the efforts from rstudio community - let us know your view on this?
