### ISSUE TITLE
Code Definition and Highlighting on Hover.

### ISSUE THREAD

**Issue by kramerrs** [rstudio/rstudio#15002]
I am working on a larger R project.  I feel like there are some things that I have used in other IDE's that would benefit RStudio users.

I would like to be able to hover or click on a variable in the editor and see all places a variable was used and where it was defined/modified last.

This is something like this in VS code.  On the right I can select a term, then it highlights all occurrences in the small window on the right.

On the left there is a place where I can search within all files in the folder including the active one and I can easily jump to any reference in the file or files.  

As it is in RStudio I spend a large amount of time scrolling and jump searching for terms, just to figure what changes I make will do to other parts of the code.  Just to be clear the VScode R plugin is pretty good, but it lacks the R oriented features like break points or interactive 

![image](https://github.com/user-attachments/assets/8937b85d-3923-494c-bd5e-2547c9c3baaa)

**Comment by ronblum** [comment]
@kramerrs Thank you for the enhancement requests and the reference screenshot! I'll mark this for review and consideration.

**Comment by jthomasmock** [comment]
Thanks @kramerrs for the request! There are a few ways you could do something similar:

- Go to Function definition: https://docs.posit.co/ide/user/ide/guide/code/code-navigation.html#go-to-function-definition
- Find in Files: https://docs.posit.co/ide/user/ide/guide/code/code-navigation.html#find-in-files

**Comment by kramerrs** [comment]
I think the request may be moot as Posit connect is moving towards Positron a VS Code based R environment anyway.

https://github.com/posit-dev/positron
