### ISSUE TITLE
rmarkdown tikz chunk breaks chunk execution

### ISSUE THREAD

**Issue by jjanmaat** [rstudio/rstudio#15019]
### System details

    RStudio Edition : server
    RStudio Version : 2024.04.2 build 764
    OS Version      :  windows 11
    R Version       :  4.4.1

### Steps to reproduce the problem

Inserted tikz chunk into default rmarkdown document.  Problem persists.

### Describe the problem in detail

When a tikz chunk is present, cannot run chunks below the tikz chunk.  Run arrow sometimes missing.  If present, does not execute chunks.  Run chunks above does not work from any button, nor from run menu.  knit works fine.

`````
---
title: "Test"
author: "John Janmaat"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Draw a Tikz Figure

```{tikz, Protest_Hybrid_Fig, echo=FALSE, fig.width=5,fig.height=5,fig.caption='Test tikz chun'}
%
% Draw a tikz figure representing the hybrid relationships
\usetikzlibrary{arrows,shapes}
\begin{tikzpicture}
\draw (0,0) grid(10,10);
\end{tikzpicture}

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
`````

Screenshot:
![RmdTikz](https://github.com/user-attachments/assets/95166eb6-491e-41f0-a1f7-9bb7d4f2e79e)

### Describe the behavior you expected

Expect to be able to run chunks either above or below tikz chunk.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjanmaat** [comment]
It looks similar.  When I remove the tikz chunks, everything seems to work.  As mentioned in #11955, this can really interfere with effective work.  In my case, I am exploring different statistical models, and therefore run chunks over multiple times.  It is very time consuming to have to render the document repeatedly.

**Comment by GuillaumeBiessy** [comment]
I have the same issue, it does not seem to be exactly the same as the one mentioned above but rather an RStudio issue.
Whenever I include a chunk starting with "tikz", all the chunks below the outline breaks and do not display anything below that chunk.
When I include anything else (tik, tikze, python css or whatever) the chunks reappear.

I am running R 4.4.0, RStudio Desktop 2024.04.1 an I updated Quarto to 1.5.55 but it did not solve the issue.

**Comment by gtritchie** [comment]
Verified with build 2024.10.0-182 on macOS. The chunk widgets now appear in the chunks below the tikz chunk, the outline is showing headings below the tikz chunk, and I'm able to run chunks above and below.
