### ISSUE TITLE
"C Stack setting ignored" revisited 

### ISSUE THREAD

**Issue by akhst7** [rstudio/rstudio#15012]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764 (2024.04.2+764)
    OS Version      : macOS 14.5 23F79 arm64
    R Version       : R version 4.4.1 (2024-06-14)

### Steps to reproduce the problem
As posted back in 2023, #13952, changing a system Cstack does not reset default Cstack in Rstudio as follows;
```
From my terminal ;
ulimit -s 65520
ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             65520
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       10666
-n: file descriptors                unlimited

R --slave -e 'Cstack_info()["size"]'
    size
63737856

Back in RStudio; 
> Cstack_info()
      size    current  direction eval_depth 
   7953612      19304          1          2

> system("ulimit -s")
8176

R from the terminal;
> Cstack_info()
      size    current  direction eval_depth
  63737856      15256          1          2

> system("ulimit -s")
65520
```
### Describe the behavior you expected
Value of Cstack in Rstudio should reflect the system Cstack value.  After changing the system Cstack to 65220, Cstack in Rstudio should be 65220.  This is not fixed yet in the current version of Rstudio. 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
> changing a system Cstack does not reset default Cstack in Rstudio as follows

But running `ulimit -s` in a Terminal only affects that Terminal session; it doesn't change it globally for the system (and so wouldn't affect the RStudio R session).

Instead, you likely need to set these via `launchtl`; for example, something like:

```
sudo launchctl limit stack 67108864
```

See the documentation in `man launchctl` for more details; there's probably a way to set this in an application-specific way but I'm not very familiar with the details.
