### ISSUE TITLE
"unexpected string constant" error in SessionAutomationRemote.R with R 3.6.3

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15021]
### System details

    RStudio Edition : Server and Desktop
    RStudio Version : 2024.08.0+341 "Cranberry Hibiscus"
    OS Version      : Ubuntu 22.04.4 (arm64)
    R Version       : 3.6.3 (built from source)

### Steps to reproduce the problem
- install RStudio Server or RStudio Desktop
- install R 3.6.3 and configure it as the version used by RStudio
- enable stderr logging via /etc/rstudio/logging.conf, for example:

```
[*]
logger-type=stderr
log-level=error
```

- start a session

### Describe the problem in detail

Error logged related to SessionAutomationRemote.R:

```
2024-07-30T21:44:01.370591Z [rsession-gary] ERROR r error 4 (Error in source("/usr/lib/rstudio-server/R/modules/SessionAutomationRemote.R",  : 
  /usr/lib/rstudio-server/R/modules/SessionAutomationRemote.R:206:27: unexpected string constant
209:       container.env.editor
210:    }'
                               ^
) [errormsg: Error in source("/usr/lib/rstudio-server/R/modules/SessionAutomationRemote.R",  : 
  /usr/lib/rstudio-server/R/modules/SessionAutomationRemote.R:206:27: unexpected string constant
209:       container.env.editor
210:    }'
                               ^
]; OCCURRED AT rstudio::core::Error rstudio::r::exec::evaluateString(const string&, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::EvalFlags) src/cpp/r/RExec.cpp:388; LOGGED FROM: rstudio::core::Error rstudio::session::modules::automation::initialize() src/cpp/session/modules/automation/SessionAutomation.cpp:67
```

### Describe the behavior you expected

Ideally no such warning.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Fredo-XVII** [comment]
Hello! Sorry to bother you over such a simple question.  I am currently using the Rstudio Arm64 daily builds.  Could you tell me which daily build has these changes for this issue?  

We are using 3.6.3 and ubunut 22 just like in this issue, and using this version of rstudio arm:
 - ENV RSTUDIO_VERSION=2024.08.0-341  

Thank you!

**Comment by gtritchie** [comment]
This change was made in the 2024.10 "Kousa Dogwood" branch. You can get daily builds of that from https://dailies.rstudio.com/rstudio/kousa-dogwood/.

**Comment by gtritchie** [comment]
@Fredo-XVII I'm curious if you encountered any problems other than the "unexpected string constant" errors being logged?

**Comment by gtritchie** [comment]
We've also backported the fix to the 2024.08 (Cranberry Hibiscus) branch, so it should appear in a daily build soon if it hasn't already.

**Comment by Fredo-XVII** [comment]
> @Fredo-XVII I'm curious if you encountered any problems other than the "unexpected string constant" errors being logged?

Hello! I moved to 2024_10 daily builds and that seems to resolve my issue.  Thanks!

**Comment by kevinushey** [comment]
@Fredo-XVII thank you for confirming!
