### ISSUE TITLE
Interactive quarto doc will not render via 'Run Document'

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#15027]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764
    OS Version      : Windows 10
    R Version       : 4.4.0

### Steps to reproduce the problem
* create file: File > New File > Quarto Document > Interactive > Shiny
* Run Document
```
---
title: "Untitled"
format: html
server: shiny
---
```

### Describe the problem in detail
The file does not render in RStudio although it runs fine in Positron via Preview and in RStudio from the terminal. When I hit ▶ **Run Document** in RStudio, the focus moves to the Render tab but all it does is show the message below and does not process the file. This was working fine a few weeks ago and then stopped and I cannot figure out why. I am running quarto 1.5.55 (the issue was also happening with 1.4.4 as well)

* ![image](https://github.com/user-attachments/assets/34bff6fb-b373-414b-9205-0669cf06d158)

### Describe the behavior you expected
The file should render and I should see steps similar to running `quarto serve`

* ![image](https://github.com/user-attachments/assets/08a46ce0-fe2f-43c8-8ead-2fba2885636c)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I was unable to reproduce using the same version of RStudio and R. @ronblum want to give it a try?

**Comment by ronblum** [comment]
I tried these combinations, but Quarto + Shiny work correctly:
* RStudio Desktop 2024.04.2+764 + Quarto 1.4.555 on Windows 11
* RStudio Desktop Pro 2024.08.0+342.pro2 + Quarto 1.5.54 on Windows 11

**Comment by rjake** [comment]
I thought this might be happen because it was working fine until recently. Is there a log I can look at our some other way to debug?

**Comment by ronblum** [comment]
@rjake There are log files in `C:\Users\UERNAME\AppData\Local\RStudio\log` which you can get to from RStudio Desktop at <kbd>Help-> Diagnostics -> Show Log Files</kbd>. I don't know how helpful they'll be, but hopefully!

**Comment by jthomasmock** [comment]
Interestingly, Push Button deploy _is_ failing for me consistently on Quarto + Shiny default template.

https://github.com/user-attachments/assets/3d1adb59-b1dc-4bd7-92c1-c531988afee7

**Comment by gtritchie** [comment]
> Interestingly, Push Button deploy is failing for me consistently on Quarto + Shiny default template.

Probably worth opening a separate issue on that (I didn't look to see if one already exists)?

**Comment by rjake** [comment]
And now, with no changes, ▶️ **Run Document** is magically working ¯\_(ツ)_/¯
