### ISSUE TITLE
Fig labelling breaks word output settings including indentation, line numbers and cross-referencing

### ISSUE THREAD

**Issue by hughgifford** [rstudio/rstudio#15022]
Hi and thanks for reading. I'm writing a document and making use of RStudio and Quarto to docx render. Whenever I try to label my figures for cross-referencing, I lose the formatting that I have established with the custom-reference-doc and I don't understand why.

### System details

RStudio Version 2024.04.2+764 (2024.04.2+764)
MacOS Ventura 13.4.1 (c) 
ImageMagick 6.9.12.93

$ quarto check
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/hughgifford/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: /Users/hughgifford/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.47
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

### Steps to reproduce the problem

The general settings that enable me to create a word document (which are fast and excellent) including indentation in every paragraph (using the "Body Text" style in the custom-reference-doc.docx) are made possible by my quarto yaml file, which looks like this:

```
project:
  type: book
book:
  title: My title
  author: Me
  chapters:
    - index.qmd
bibliography: bibliography.bib
format:
  docx:
    toc: false
    number-sections: false
    reference-doc: custom-reference-doc.docx
```

Then, within the document, I want to include images. Most of my images exist as pdfs. So, I have tried many ways of getting high quality input pdfs into the document, and I have found that the nicest looking way appears to be using magick:

````
```{r}
#| fig-cap: "My Caption"
image_read_pdf('figure.pdf')
```
````

And here's the necessary settings that I need to include before this, including a new style in the custom-reference-doc.docx file called "NoIndent" that didn't have a paragraph indent.

````
```{r Chunk-settings, echo=FALSE,message=FALSE}
knitr::opts_chunk$set(class.output = "NoIndent")
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
require(magick)
require(tidyverse)
```
````

### Describe the problem in detail

As soon as I try to add in the figure label, it becomes indented again. The image caption also loses the other features (such as line numbers, which are featured in the "Image Caption" style in the custom-reference-doc.docx). x

````
```{r}
#| label: fig-2
#| fig-cap: "My caption"
image_read_pdf('figure.pdf')
```
````

The fig-cap line is absolutely necessary for the chunk behaving properly with correct lack of indentation and line numbers as per the custom-reference-doc. I'm not sure what the code chunk outputs are thinking that the word doc outputs are, exactly. Does the code think it's a figure? As soon as I inlcude figure labelling, I lose my custom formatting.

This may also be linked, and I also need help with fixing this, but as soon as I include figure labels, the numbers do not start at 1, instead, they start at 11.1 since the figure section is in the 11th subheading section, or 1.1 if I move the levels down. 

### Describe the behavior you expected

I want to be able to import figures into a Quarto docx output that are high quality, preferrably pdf origin, and are not indented, and that I can cross-reference as figures, that appear in order of the figures as they appear starting from 1. 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hughgifford** [comment]
Thanks so much Ron - that's great. I've checked over and it's clearer. Thank you.

**Comment by ronblum** [comment]
@hughgifford I tried reproducing this, but I haven't been able to. Would you be willing to do a video screen capture so that I can see your steps and the incorrect behavior? I'm wondering if I'm not following your steps correctly.

**Comment by hughgifford** [comment]
Hi there. Thanks very much. After some experimentation, I have manage to fix the issue. Essentially, the figures and captions are assigned "Compact" and "Image caption" styles in word in the custom-reference-doc.docx. I have simply typed some text in Word, assigned these styles, removed the tab, clicked "Update to match selection" in the styles pane, and saved the custom-reference-doc.docx, and seen the changes made. What a relief. Thanks again for your input. I think it could be helpful to publish a series of word templates. I note others have made theirs available. https://andrewpwheeler.com/2024/06/21/my-word-template-for-quarto/ Thank you again.
