### ISSUE TITLE
RStudio Desktop for Ubuntu 24 (installer-less) (x86_64) dailies are missing

### ISSUE THREAD

**Issue by gdevenyi** [rstudio/rstudio#15023]
The files available at https://dailies.rstudio.com/rstudio/cranberry-hibiscus/electron/noble-amd64-xcopy/ which are supposed to be "installer-less" dailies are missing, instead they are installer dailies.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [NA] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [NA] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gdevenyi Thank you for raising this! I'll bring this up internally.

**Comment by ronblum** [comment]
All set, starting with rstudio-2024.08.0-343-amd64-debian.tar.gz.

**Comment by cm421** [comment]
FYI I've also gone back and fixed the metadata of previous uploads, so those should be corrected shortly once the dailies site rebuilds

**Comment by gdevenyi** [comment]
Thank you
