### ISSUE TITLE
[bug] Rmd file does not respect options(warn = ) across chunks during interactive use

### ISSUE THREAD

**Issue by ppoyk** [rstudio/rstudio#15030]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764 "Chocolate Cosmos"
    OS Version      :  Windows 11 Enterprise; 22H2; 22621.3880
    R Version       :  4.4.1 "Race for Your Life"

### Steps to reproduce the problem
Create an .Rmd file with the following contents:
````r
```{r}
options(dummy="I am global")
options(warn=2)
getOption("warn")
```
#>[1] 2
```{r ops-fail}
getOption("dummy")
getOption("warn")
```
#>[1] "I am global"
#>[1] 1
```{r ops-fail2}
getOption("dummy")
getOption("warn")
```
#>[1] "I am global"
#>[1] 1
````
Then, run the file inside RStudio interactively, either by "Run all" or one chunk at a time.

### Describe the problem in detail
The `R` option `warn`, which controls how generated warnings are handled, does not seem to be set or retained properly during interactive use of an .Rmd file.
Setting the option works properly only if the file is "knitted" or "rendered" using `rmarkdown`.

The problem is not caused by either [`knitr` or `rmarkdown`](https://github.com/yihui/knitr/issues/2357#issuecomment-2242480244) nor by [`evaluate`](https://github.com/r-lib/evaluate/issues/213#issuecomment-2236544623)

### Describe the behavior you expected
If a user supplies a line, such as `options(warn=2)`  at the beginning of a .Rmd file, the option is set and respected during interactive use for the rest of the file / session, even inside functions etc. 
Similar behaviour is expected also if the user sets the `warn` setting through the console, and then interactively runs the .Rmd file.

The response to warnings should change also if another instance of `options(warn=X)` is encountered during the script execution, which might change the prevailing setting.

The output of `getOption("warn")` and the accompanying `R` warning response should change only if user (or user-run script) executes a command (such as `options(warn=2)`) which changes the option.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Looks like this is probably a bug in how we attempt to apply a (potentially missing) "warn" chunk option.

https://github.com/rstudio/rstudio/blob/f46af4b9c6c03fa458ea18159fb1dcf38da1c962/src/cpp/session/modules/rmarkdown/NotebookExec.cpp#L271-L276

We should check if the `warning` chunk option exists, and apply that only if it really does.

**Comment by ronblum** [comment]
This is working correctly for positive and negative numbers. However, when set to 0, `warn` become 1 in the next chunk.

With
````
```{r}
options(warn=0)
getOption("warn")
```

```{r}
getOption("warn")
```
````

we end up with
```
> getOption("warn")
[1] 0
> getOption("warn")
[1] 1
```

(Note: option `warn` is 1 by default in R Markdown but 0 in R.)

This was the case before, so this isn't a regression. Is this expected behavior or another issues?

**Comment by kevinushey** [comment]
I think we can live with that. In any case users should be setting the chunk option `warning = FALSE` or `warning = TRUE` rather than relying on the global option here.
