### ISSUE TITLE
Change soft wrapping in non R/Rmd text files

### ISSUE THREAD

**Issue by RichardJActon** [rstudio/rstudio#15045]
In global options you can toggle soft wrapping on and off for R files in code > editing and for R markdown in R markdown > basic but there is no option to set this for other types of files.

My use case is that I have some wide text files that I'd like to be able to view unwrapped as it makes it easier to understand their format so I can write code to process them.

#2341 only addresses wrapping for R markdown-like files but not other types.

**Comment by ronblum** [comment]
@RichardJActon Thank you for the suggestion! We'll review it as part of our ongoing development of RStudio.

**Comment by jthomasmock** [comment]
Thanks for feedback!

We have this feature "Soft Wrap source files" in the Cranberry Hibiscus release, expected in next few weeks: https://github.com/rstudio/rstudio/pull/14758

**Comment by RichardJActon** [comment]
Awesome thanks @jthomasmock & @ronblum I didn't spot #10940 when I was searching for similar issues. Might want to add addresses #5110, #2341, and #15045 to the PR description for #14758 in case anyone else at my level of issue search competence comes along asking for this before they get shipped it Cranberry Hibiscus :sweat_smile:
