### ISSUE TITLE
Pressing Tab on text in .Rmd replaces it with a tab instead of indenting

### ISSUE THREAD

**Issue by timothee-bacri** [rstudio/rstudio#15046]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2 Build 764, "Chocolate Cosmos" (Release e4392fc9, 2024-06-05) for windows
    OS Version      : Windows 10 Enterprise version 22H2
    R Version       : 4.4.0

### Steps to reproduce the problem
- Create a R Markdown (.Rmd) file
- Type some text
- Select it
- Press Tab
- Text is replaced by a tabular space instead of being indented

### Describe the problem in detail
In .Rmd files, pressing Tab on selected text replaces the text by a tab instead of indenting.
Note that Shift+Tab removes indentation.

### Describe the behavior you expected
I would expect the text to be indented.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Internal note: it looks like this only occurs when selecting text outside of a code chunk; that is, in the "prose" section of a document. In that case, it's not totally clear to me what the right behavior is?

**Comment by timothee-bacri** [comment]
@kevinushey I had not noticed that code chunks could be indented, thanks for pointing it out.

My usecase is indenting an element in a markdown list
```tex
- text A
  - indented text B
- text C I would like to:
\begin{align*}
f(x)=2
\end{align*}
indent
```

If it helps determine the right behavior:
- Notepad++ does not seem to care about the type of text, it always indents. I expected the same in RStudio.
- Shift+Tab currently unindents even "prose" text, so shouldn't Tab to do the opposite and indent?

**Comment by ronblum** [comment]
Internal note: Double-check the behavior of `Tab` in Visual mode.

**Comment by ronblum** [comment]
I'm still seeing this behavior in RStudio Desktop 2024.10.0-daily+236 on Windows 11, and RStudio Server 2024.10.0-daily+250 on Ubuntu 22.04 via Chrome on Windows 11. 
- Tab moves spaces.
- Shift-Tab changes the list level.

**Comment by kevinushey** [comment]
Isn't that the intended behavior? The problematic behavior being described was the text selection being replaced with an inserted tab (or spaces equivalent).

**Comment by ronblum** [comment]
OK, I guess I was a little confused about the pairings. The pair is between
* Select text + <kbd>Tab</kbd> - sink item
* <kbb>Shift-Tab</kbd> - lift item

Not <kbd>Tab</kbd> and <kbd>Shift-Tab</kbd>.

Verified fixed!
