### ISSUE TITLE
Start Rstudio with a blank page

### ISSUE THREAD

**Issue by lexie-lee** [rstudio/rstudio#15059]
### System details

    RStudio Edition : <- Desktop ->
    RStudio Version : 2024.04.2+764
    OS Version      : MAC OS 14.5
    R Version       : 4.2.2

### Describe the problem in detail
My RStudio run normally yesterday, and my MacBook pro didn't shut down. But today when I try to open Rstudio, it did not work and only show a blank page. i tried to reinstall the rstudio and restart my Mac, but still not ok.
The field looks like below:
<img width="967" alt="image" src="https://github.com/user-attachments/assets/d0fae1ff-dd2b-41ee-a8d2-21eb50102115">

and it even cannot be shut down normally.

### Describe the behavior you expected

Fix the blank thing.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Also, it's possible that something got messed up with the configuration etc., and resetting RStudio state might resolve this: https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by ronblum** [comment]
@lexie-lee Great, glad that it works! 🥳
