### ISSUE TITLE
Problems with mouse clicking/selecting on Visual Editor in Chrome 127.0.6533.120

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15068]
### System details

    RStudio Edition : Server/Server-Pro
    RStudio Version : Any version I've tried (including 2023.12.1, 2024.04.2, latest builds of 2024.08 and dev build of `main`)
    OS Version      : Windows-11, macOS
    R Version       : any

### Steps to reproduce the problem
- using Chrome 127.0.6533.120 (the latest at the time of writing this)
- create an RMarkdown or Quarto document and switch into visual mode
- try clicking on text that isn't part of a code block to place the editor caret at that location

### Describe the problem in detail
- if you click near end of document it jumps to the start
- in any case the caret is NOT moved to where you clicked (it does work inside a code block)
- trying to select text is also not working

### Describe the behavior you expected
- clicking places the caret
- no jumping back to beginning

Note this appears to be very specific to this version of Chrome (127.0.6533.120). Happens in incognito mode as well.

Working fine with Safari (macOS), Firefox, Chromium v126, Edge on Windows (127.0.2651.105), and Chrome beta 128.0.6613.36.

Also fine on Linux Chrome version 127.0.6533.119.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Chrome updated to 128.0.6613.85, and the problem is still happening (only tried on macOS so far).

**Comment by gtritchie** [comment]
https://issues.chromium.org/issues/359834213?pli=1

**Comment by gtritchie** [comment]
Note: if you strip out the preamble and any code chunks from a .rmd or .qmd, leaving, essentially markdown, then the mouse selection starts working, so it's not a fundamental problem in Prosemirror.

**Comment by gtritchie** [comment]
A workaround is to turn off the "Always show focus outlines" option in Tools / Global Options / Accessibility:

<img width="660" alt="focus-visible-polyfill" src="https://github.com/user-attachments/assets/8767a40a-248a-45f0-bdfb-4e5195767f00">

**Comment by gtritchie** [comment]
This started working again and can no longer reproduce it (currently using Chrome 128.0.6613.85 which was failing 100% of the time yesterday).

**Comment by kevinushey** [comment]
Everything appears fine on my end as well. Chrome Version 128.0.6613.85 (Official Build) (arm64)

**Comment by ronblum** [comment]
Verified also on posit.cloud and Posit Workbench 2024.08.0+351.pro61, both with Chrome version 128.0.6613.85 on Windows 11.

**Comment by gtritchie** [comment]
Hearing reports that this is still happening for some, so reopening.

**Comment by ronblum** [comment]
The previous reports have subsided thanks to browser updates.
