### ISSUE TITLE
Debugging seems off by one frame and focuses on the parent frame

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15072]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.8.0.331
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.4.1 (2024-06-14 ucrt)

### Steps to reproduce the problem

Split from #15016 

1. In a package, have the following code under R

```r
f_user_facing <- function(x) {
  f_internal1(x)
}

f_internal1 <- function(y) {
  y
  for (i in seq_along(y)) {
    if (y == 1) {
      w <- f_internal2(y) ** 2
    } else {
      w <- y + 2
    }

  }

  w + 1
}
f_internal2 <- function(y) {
  w <- y ** 2

  w + 1
}
```

1. Set a breakpoint at the line of the `if() statement.

![image](https://github.com/user-attachments/assets/d6d5895e-f04f-4cb4-bc99-c6b7dfc7c1ca)

1. Call `devtools::load_all()` or `source()`.

1. Call `f_user_facing(2)` in the console.

If this can't be reproduced easily,

### Describe the problem in detail

It seems that the frame is off by one in this situation, and focuses on the parent function.

As you can see, the green arrow is not focused in the correct place.

![image](https://github.com/user-attachments/assets/87ab4b22-c221-4a0a-a967-2e49308bbd6e)

Additional things I noted while trying to access objects

```
Warning in pos > offsets[linepref] :
   size of a longer object is not a multiple of the size of a shorter object.
  la taille d'un objet plus long n'est pas multiple de la taille d'un objet plus court
Calls: .rs.simulateSourceRefs -> which
```

Which suggests the sourceRefs aren't properly counted?

Also, I just upgraded to R 4.4.1 and don't remember this being in issue in R 4.3.2, but I may be mistaken.

### Describe the behavior you expected

Note the correct functionality is working, it is just the editor focus that is not in the correct place. (i.e. 
I would expect the editor to be focused)
A workaround for now is to insert a `browser()` statement.

Note that this is a very minimal reprex, but the issue makes debugging near impossible in larger context (when the 2 functions are in 2 different files for example)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I think I can confirm what you saw -- the debugger works as expected with R 4.3.2, but this issue arises in R 4.4.1. Something must've changed in the R debugger internals that's tripping us up...

**Comment by olivroy** [comment]
I just saw the warning too on R 4.2.3 fwiw

```r
Warning in pos > offsets[linepref] :
   size of a longer object is not a multiple of the size of a shorter object.
Calls: .rs.simulateSourceRefs -> which
```

The problem is likely that something doesn't get passed on correctly here

https://github.com/rstudio/rstudio/blob/dc79f1ec54f6331fb6f5ce9e52a6568a24478d1a/src/cpp/session/modules/SessionEnvironment.R#L347-L379

Last modified in https://github.com/rstudio/rstudio/pull/14360

**Comment by kevinushey** [comment]
Some more investigation; it seems like the issue only occurs when attempting to debug within a braced expression; e.g. with

```
f <- function() {
   1 + 1
   {
      2 + 2
   }
}
```

Setting a breakpoint on `1 + 1` seems to work; `2+ 2` does not. I also see the warning noted by @olivroy in the second case.

**Comment by kevinushey** [comment]
This should be fixed in the latest daily builds, available at https://dailies.rstudio.com/rstudio/kousa-dogwood/. Testing would be appreciated!

**Comment by olivroy** [comment]
This seems resolved! Thanks
