### ISSUE TITLE
Missing library libasound when Rstudio starts up on Ubuntu 24.04

### ISSUE THREAD

**Issue by bshor** [rstudio/rstudio#15071]
### System details

    RStudio Edition : Desktop
    RStudio Version : rstudio-2024.04.2-764
    OS Version      : Ubuntu 24.04
    R Version       : R 4.4.1

### Steps to reproduce the problem

[Download](https://download1.rstudio.org/electron/jammy/amd64/rstudio-2024.04.2-764-amd64.deb) and install the Deb using dpkg -i on the command line.

### Describe the problem in detail

Package installs but when I run it, I get a complaint of 

`rstudio: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory`

It does not start up at all.

### Describe the behavior you expected

Rstudio to run as per normal.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bshor Thank you for raising this! RStudio Desktop 2024.04 isn't supported on Ubuntu 24.04. only 20.04 and 22.04. However, we're very close to release 2024.08 (Cranberry Hibiscus). If you'd like to try it out, the daily builds are available at https://dailies.rstudio.com/rstudio/cranberry-hibiscus/. Please note that while they're stable, they're not 100% complete and released, so they're meant for testing purposes right now.
