### ISSUE TITLE
Adding tidyverse dependencies to RStudio Linux .deb packages

### ISSUE THREAD

**Issue by renatovargas** [rstudio/rstudio#15087]
Dear Posit team. I have a shameless request. For every new Linux install of RStudio, I have to install the following libraries from the terminal in order to be able to run `install.packages("tidyverse")` within RStudio. 

```
libcurl4-openssl-dev 
libfontconfig1-dev 
libxml2-dev 
zlib1g-dev 
libharfbuzz-dev 
libfribidi-dev 
libfreetype6-dev 
libpng-dev 
libtiff5-dev 
libjpeg-dev
``` 
These in Debian/Ubuntu (both 22 and 24 from the dailies). Package names are slightly different for Fedora.

Finding out which were missing has been a painstaking process of reading the install errors, and since packages are compiled on download on Linux, that was a long elimination process. Seeing that both, RStudio and the Tidyverse are Posit supported, it would be nice if you could just add these as dependencies to the .deb files so that they get downloaded and installed when installing RStudio. Not even in the package, just as dependencies on install, just like there are a few already in the current packages. I know that not everybody will install the tidyverse, but I bet it's a big chunk of people who do and getting these 'just in case' will be fine for 99% of users.

And I guess people with this problem will complain on the tidyverse repos, but it would be so easy to fix upstream here. Thank you.

**Comment by ronblum** [comment]
@renatovargas Thank you for the suggestion! I'll mark the issue for review.

Though that said: We've had a few concerns raised in the past about including a package that will only be needed by some people, although that's been rare. But we also need to consider not only that the Tidyverse isn't used by everyone, but also that some people who use it only ever do so with one package. So they, too, would get unnecessary OS packages.

But--I'll mark it for review!

**Comment by renatovargas** [comment]
Thank you so much for considering it for review. These libs apply even if it's just a few of the most used packages, like dplyr and ggplot2, and not the whole metapackage, and I understand what you are saying, so it is highly appreciated that you'll look into it. If it helps in any way, here's the dnf names list for fedora/rhel too:
```
libcurl-devel
openssl-devel
harfbuzz-devel 
fribidi-devel 
freetype-devel 
libpng-devel 
libtiff-devel 
libjpeg-devel
```

**Comment by jthomasmock** [comment]
Hey @renatovargas -- to avoid the compilation step, I would recommend using our free Posit Package Manager which provides package binaries: https://packagemanager.posit.co/client/#/repos/cran/setup?distribution=ubuntu-24.04

There's also the `pak` tool which can help with discovering https://pak.r-lib.org/reference/pkg_sysreqs.html and checking/installing system requirements: https://pak.r-lib.org/reference/sysreqs_check_installed.html

**Comment by renatovargas** [comment]
Thank you @jthomasmock I was not aware of the Posit Package Manager. That is great. I will use it from now on!
