### ISSUE TITLE
"Outline" button for *.md files

### ISSUE THREAD

**Issue by jpcaveiro** [rstudio/rstudio#15101]
The button "outline" exists for *.Rmd files

![image](https://github.com/user-attachments/assets/17085de5-6a2e-4fed-9e35-74b8fe681bc8)

but it should exist for *.md files. Currently does not appear:

![image](https://github.com/user-attachments/assets/a3c57413-090b-4b33-8a20-744f28474979)

**Comment by olivroy** [comment]
this was requested before https://github.com/rstudio/rstudio/issues/13505
