### ISSUE TITLE
Indentation and order in quarto document outline wrong

### ISSUE THREAD

**Issue by riekeschaefer** [rstudio/rstudio#15119]
### System details

    RStudio Edition : RStudio Desktop for windows
    RStudio Version : RStudio 2024.04.2+764
    OS Version      : Windows 10
    R Version       : 4.4.1

### Steps to reproduce the problem

1. create empty quarto document in RStudio
2. copy in the code below
3. look at outline

MWE:
````
---
title: "Bug"
author: "auth"
format: html
date: "2024-09-05"
---

## H1

```{r}
1+1
```

### H1a

```{r}
#| eval: false
# random comment
```

### H1b

```{r}

testfunc <- function(a) {
  return(a+1)
}

```

## H2

## Last section
````

### Describe the problem in detail
The outline looks like this (note the indentation and order of sections):

![grafik](https://github.com/user-attachments/assets/87483cb7-9b14-4334-8981-aab97a54e473)

### Describe the behavior you expected
I'd expect it to look like this, as it does in visual mode and on RStudio Server 2022.07.2+576 (OpenSUSE15) with R 4.1.2:

![grafik](https://github.com/user-attachments/assets/6c6a2aa8-afb0-457e-b3f7-bbccd3b34f6f)

### More details

- If code cell 1 or 2 are removed, the indentation and order are correct.
- If an empty line is added in cell 2 above or below the comment, the indentation and order are correct.
- If code cell 3 is removed, the order of sections is correct but the indentation is still not working.

I suspect other factors to be at play as well as I can't get the outline to work correctly in my original file but this MWE was the best I could come up with.

I think it is a different bug from [this one](https://github.com/rstudio/rstudio/issues/11896) because the behaviour depends on code cell content and the order of sections is also messed up.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@riekeschaefer Thank you for raising this! This is fixed in the current release, in it's final stages.

Verified in RStudio Desktop 2024.09.0+357 on Windows 11.
