### ISSUE TITLE
`.DollarNames` S3 methods cause completion "type" guessing to turn off

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#15115]
Run

```r
x <- R6::R6Class("x", list(initialize = function() {}))$new()
```

Then `x$` should show _typed_ completions for 3 things, including a `clone()` function.

Now run:

```r
registerS3method(
  ".DollarNames",
  "R6",
  function(x, pattern) setdiff(names(x), c("initialize", ".__enclos_env__"))
)
```

That registers a `.DollarNames` method for R6 to remove 2 of those that dont belong

Now try `x$` again. It only shows `clone` (good) but its no longer typed as a function (bad)!

`.DollarNames` are used here if an S3 method for the object exists:
https://github.com/rstudio/rstudio/blob/078e21116b0e34aff92addf961699017adb62fc5/src/cpp/session/modules/SessionRCompletions.R#L1610-L1624

However, notice how that sets the type to either `FUNCTION` or `UNKNOWN`, which turns off downstream type guessing

**Comment by DavisVaughan** [comment]
Relevant because https://github.com/r-lib/R6/pull/289 is going to add a `.DollarNames` S3 argument for R6 classes, so R6 objects will no longer show typed completions, which kind of stinks because 99% of the time they are functions and would benefit from the `()` autocompletion

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+261.,
