### ISSUE TITLE
Please consider dropping Quarto as a dependency

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#15124]
Quarto doesn't support installation as a package under $PREFIX.
They only provide binary tarballs that users are supposed to download manually and they provide them only for a few OSes.

RStudio probably can't be nicely packaged because users would still need to download Quarto binaries on top of this.

This makes installation of RStudio an undue hassle for users.

I suggest to go back to using pandoc directly as this was a much more scalable and sustainable solution in the context of a system where everything is installed using a package manager.

**Comment by kevinushey** [comment]
You can configure RStudio with `-DQUARTO_ENABLED=0` to disable RStudio's bundling of Quarto. In this scenario, RStudio will rely on `quarto` being available on the PATH for any features which use Quarto. See also:

https://github.com/rstudio/rstudio/blob/f257bd280f6cd7cd388c7be5418d29684e8c76de/cmake/globals.cmake#L238-L245

Is that sufficient for your use case?

**Comment by yurivict** [comment]
@kevinushey 

I have a question: does RStudio expect the html capability from Quarto?

**Comment by kevinushey** [comment]
RStudio itself doesn't, but users probably would.

**Comment by yurivict** [comment]
@kevinushey 

> RStudio itself doesn't, but users probably would.

Do you mean RStudio users, or just Quarto users?
How can RStudio users need the html capability if RStudio doesn't need it?

**Comment by kevinushey** [comment]
Sorry, can you clarify what you mean by "html capability" in this context?

**Comment by yurivict** [comment]
No, it's ok.
We have Quarto running now on FreeBSD.

Thank you for your help.
