### ISSUE TITLE
Quarto bin not added to PATH by Windows installer

### ISSUE THREAD

**Issue by raffaem** [rstudio/rstudio#15127]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2
    OS Version      :  Windows 11
    R Version       : 4.4.1

### Steps to reproduce the problem

1. Download Windows installer from: https://posit.co/download/rstudio-desktop/
2. Install it
3. Try to compile a Quarto document
4. It will tell you

   > No TeX installation was detected.
   > Please run 'quarto install tinytex' to install TinyTex.
5. By opening a terminal, `quarto` is not a valid binary

### Describe the problem in detail

The RStudio provided quarto binary, located in `C:\Program Files\RStudio\resources\app\bin\quarto\bin`, is not added to PATH env var

### Describe the behavior you expected

Add quarto to PATH

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@raffaem Thank you for raising this! I'll mark this for consideration.

**Comment by kevinushey** [comment]
The embedded copy of Quarto should be added to the system path here:

https://github.com/rstudio/rstudio/blob/0420fbb9274b6e5d9894f145da1122e941b6d0c1/src/cpp/session/modules/quarto/SessionQuarto.cpp#L316-L336

so something must be missing. This is the only place we use `r::util::addToSystemPath()`, so maybe this isn't doing the right thing on Windows? (Perhaps related to the whole Windows static runtime + separate environ blocks thing?)

**Comment by raffaem** [comment]
I can confirm that , even after restarting the system, quarto is still "not recognized as an internal or external command,
operable program or batch file."

Moreover, I think it wouldn't be bad for the installer to be able to install R and TinyTex.

**Comment by kevinushey** [comment]
I'm not able to reproduce.

<img width="531" alt="Screenshot 2024-09-11 at 10 06 34 AM" src="https://github.com/user-attachments/assets/898df1f8-7a20-4629-809b-9ffac5ee010c">

And:

<img width="580" alt="Screenshot 2024-09-11 at 10 06 22 AM" src="https://github.com/user-attachments/assets/0a7bde26-7d12-4202-90c5-315d8b30f4a6">

If you're talking about Quarto being globally available, RStudio intentionally doesn't put it on the global system PATH -- you'd need to do that yourself, or perhaps use the installer from https://quarto.org/docs/download/index.html.

**Comment by raffaem** [comment]
@kevinushey sorry, have you tried the __native__ windows console, not the RStudio integrated one?

**Comment by kevinushey** [comment]
I did, but like I said above:

> If you're talking about Quarto being globally available, RStudio intentionally doesn't put it on the global system PATH -- you'd need to do that yourself, or perhaps use the installer from https://quarto.org/docs/download/index.html.
