### ISSUE TITLE
Prevent `.qmd` from loading R packages

### ISSUE THREAD

**Issue by jtlandis** [rstudio/rstudio#15148]
Hello developers! I was wondering if you could include an option to disable `.qmd`'s behavior of loading packages found within an the file upon opening?
I would personally like more control on when packages are attached to my environment than by accidentally opening a `.qmd` file which then loads a package that masks my current environment's functions.

This is also particularly annoying with large project files!

**Comment by kevinushey** [comment]
I believe this may be resolved in the latest daily builds of RStudio, but we should test and confirm.

**Comment by ronblum** [comment]
@jtlandis Thank you for raising this! Can you provide a simple reproducible example for this, to make sure that I can reproduce exactly what you're seeing?

**Comment by ronblum** [comment]
@jtlandis Have you by chance tried this out with [the latest dailies](https://dailies.rstudio.com/)? (Note that these are for development purposes only, not testing.)

**Comment by ronblum** [comment]
@jtlandis BTW it would be great to get an example, because I've tried a few different ways with several packages, but I haven't had luck reproducing the scenario. Thanks!

**Comment by ronblum** [comment]
Closing. If this is still an issue, please let us know.
