### ISSUE TITLE
Using comma after chunk engine confuses label parsing

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15156]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : All tried up to 2024.10.0+142
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

Create an RMarkdown document and insert a code chunk. Edit the code chunk to put a comma between the chunk type and the name, e.g.:

```
```{r, cars}```
```

Click on the chunk options gear and notice that the "Chunk Name" field is empty.

### Describe the problem in detail

RStudio prefers the form without that comma, but many examples of RMarkdown/knitr chunks show a comma, such as: https://yihui.org/knitr/options/.

### Describe the behavior you expected

The chunk options UI to recognize the chunk label, even if a comma is used.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Verified fixed in RStudio 2024.10.0 Build 192 on macOS.

<img width="534" alt="Screenshot 2024-09-19 at 10 15 12 AM" src="https://github.com/user-attachments/assets/afd83d18-5ee4-49d3-9606-bb7f4c52f334">
