### ISSUE TITLE
rstudio dailies for jammy and noble both point to jammy files

### ISSUE THREAD

**Issue by gdevenyi** [rstudio/rstudio#15151]
For both the `deb` and `.tar.gz` downloads, the links on the noble page point to the same downloads as the jammy page. It is not clear if this is intentional.

Ex:
https://dailies.rstudio.com/rstudio/cranberry-hibiscus/electron/jammy-amd64-xcopy/
https://dailies.rstudio.com/rstudio/cranberry-hibiscus/electron/noble-amd64-xcopy/

Both point to
https://s3.amazonaws.com/rstudio-ide-build/electron/jammy/amd64/rstudio-2024.09.0-368-amd64-debian.tar.gz

A "jammy" download.

**Comment by gtritchie** [comment]
This is intentional. We currently don't produce a separate build for noble, the jammy build is supported on both.

**Comment by gdevenyi** [comment]
> supported on both.

For some values of supported #14927

**Comment by ronblum** [comment]
* Issue #14927 refers to Chocolate Cosmos  2024.04.x, which is not supported on Ubuntu 24.04, although there appear to be unsupported workarounds. There is no claim that it's supported on Ubuntu 24.04.
* This issue refers to Chocolate Cosmos 2024.09.x which is supported on Ubuntu 24.04, and the same installer works on both Ubuntu 22.04 and 24.04.
