### ISSUE TITLE
Collapsed RMD Chunk label truncated when it contains hyphens

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15162]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2024.04.2+757
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- create new RMarkdown document
- in regular (non-Visual) mode edit the "cars" chunk so its label contains one or more hyphens, e.g.

<img width="215" alt="chunk with label cars-cost-less" src="https://github.com/user-attachments/assets/f4044f01-b57e-420b-a151-eff4f1ad0ae6">

- collapse the chunk, note the full label appears in the summary:

<img width="250" alt="collapsed chunk in source mode" src="https://github.com/user-attachments/assets/1c682174-4fd8-4fc1-be63-9c923f0bf187">

- switch to Visual Editor, then collapse the same chunk

<img width="223" alt="collapsed chunk in visual mode" src="https://github.com/user-attachments/assets/c408432c-a639-480c-9438-cc5a216f2fde">

### Describe the problem in detail

The label in the collapse chunk in Visual Mode is missing everything after the first hyphen.

### Describe the behavior you expected

Full label should appear in summary even if it contains hyphens.

Note that the knitr documentation recommends using hyphens as a separator in labels: https://yihui.org/knitr/options/#chunk-options

> Try to avoid spaces, periods (.), and underscores (_) in chunk labels and paths. If you need separators, you are recommended to use hyphens (-) instead. For example, setup-options is a good label, whereas setup.options and chunk 1 are bad...

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Verified fixed in RStudio 2024.10.0 Build 192 on macOS.

<img width="537" alt="Screenshot 2024-09-19 at 10 13 52 AM" src="https://github.com/user-attachments/assets/c93e54b1-a98c-444a-a859-3b8364b8e617">

<img width="542" alt="Screenshot 2024-09-19 at 10 13 49 AM" src="https://github.com/user-attachments/assets/14189906-93f2-4a07-bbcf-364688710c49">
