### ISSUE TITLE
Autocompleted column name incorrectly inserted with escaped backticks

### ISSUE THREAD

**Issue by mz8i** [rstudio/rstudio#15161]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for windows
    OS Version      :  Windows 11
    R Version       :  4.3.2

### Steps to reproduce the problem
The problem should manifest itself in the following code:
```r
library(tidyverse)

test <- tibble(
  X = c(1, 2, 3)
)

test %>% 
  rename(
    `Long Name With Spaces` = X
  ) %>% 
  select(
     # trigger autocomplete here
  )
```
### Describe the problem in detail

When auto-completing a column name that has been created inside a pipeline, for example using `dplyr::rename()`, and that contains spaces and is therefore wrapped in backticks (`) at the place where it's created, the autocompleted column name contains escaped backticks.

![image](https://github.com/user-attachments/assets/4d22c031-4d09-467c-8673-a61e7915a567)
![image](https://github.com/user-attachments/assets/b6bbf736-058f-4748-94f8-619382a3f556)

I haven't found other open issues describing this, but I believe it's similar to these closed issues: https://github.com/rstudio/rstudio/issues/8538, https://github.com/rstudio/rstudio/issues/4094
### Describe the behavior you expected
The text inserted after the autocomplete option is selected should be simply
```
`Long Name With Spaces`
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Reproduced the issue in build 2024.09.0-375, and verified the fix in 2024.10.0-hourly+191 on macOS.
