### ISSUE TITLE
Visual Editor loses raw HTML code blocks

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15189]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2024.09.0+375, Quarto 1.5.57
    OS Version      : macOS Sonoma 14.6.1
    R Version       : 4.4.1

Discovered while verifying fix for #14594; this wasn't caused by that fix, the problem already existed. This scenario was working in the prior release 2024.04.2.

### Steps to reproduce the problem

- Create a new Quarto document, edit in Visual Mode, add a new line at the end
- Type / to show "Insert anything"
- choose "Raw Block..." (you can type Raw Block to show it or scroll to end)
- choose html 
 
<img width="465" alt="insert-raw" src="https://github.com/user-attachments/assets/54b9e6dd-9cf7-4030-abfa-85cbb433e004">

- enter some HTML in the raw block, e.g. `Hello <i>World</i>, how are you?`
- save the file, close it
- now examine the file contents outside of RStudio, the code block should be:

````rmd
```{=html}
Hello <i>World</i>, how are you?
```
````
### Describe the problem in detail

The code block is gone, all that is left is the content, but not the surrounding backticks, etc. If you reopen the file in RStudio, you can also see that the code block is gone.

### Other ways to repro

Simply switching from Visual Mode to Source Mode and back will show this problem. Same if you start in source mode, enter the code block there, and switch to Visual Mode.

This also happens in Visual Studio Code using the Quarto extension: https://github.com/quarto-dev/quarto/issues/552.

### Describe the behavior you expected

Should be able to save and reload raw HTML code blocks. Some other raw block types I tried worked correctly.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Opened a pandoc issue: https://github.com/jgm/pandoc/issues/10213

**Comment by ronblum** [comment]
QA Note:
- Expected behavior
````
```{=html}
Hello <i>World</i>, how are you?
```
````
- Actual behavior
```
Hello <i>World</i>, how are you?
```

**Comment by yihui** [comment]
Is there a chance to fix it for `=tex` (and `=latex`) blocks, too? Or even better, for any raw blocks (e.g., `=openml`))? Thanks!

**Comment by gtritchie** [comment]
> Is there a chance to fix it for =tex (and =latex) blocks, too? Or even better, for any raw blocks (e.g., =openml))?

Can you open a separate issue on that? Thanks!

**Comment by yihui** [comment]
Sure. Done: https://github.com/rstudio/rstudio/issues/15253 Thanks a lot!

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.09.1+388 and 2024.11.0-daily+277.
- Checked in both R Markdown and Quarto
- Added a few extra lines to show that raw block is kept completely intact:
```
Hello <i>World</i>, how are you?
when
there
is
no
space
```
