### ISSUE TITLE
Source viewer contantly interrupts debugging feature, during debugging own functions.

### ISSUE THREAD

**Issue by KasperThystrup** [rstudio/rstudio#15188]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.06.2 Build 561 
    OS Version      :  Windows 10
    R Version       :  4.3.1 

### Steps to reproduce the problem
New Rscript > test.R;
my_function <- function(a, b){
  #browser()  #Uncommenting this line of code would yield same behavoir as if using trace 
  foo <- a - b
  bar <- sum(a, b)
}

trace(my_function, browser)

my_function(1, 2)

;

Now start to step through your function -> User redirected away from the source function into source viewer, which is immutable -> no debugging use there!
 

### Describe the problem in detail
Whenever I use browser() or trace(..., browser) to debug functions, I'm redirected away from the source file itself into a separate source viewer window. This redirection happens precicely the two first time I execute a chunk of code, for every new Debug session / step

BTW. Don't have admin rights of my laptop, so can't test on latest version, but expect it to be there as well, as this has annoyed me across various versions (don't know whether behavoir has been there always or was later introduced)

Very related to #9943

### Describe the behavior you expected
Source Viewer would only redirect traced functions from other packages e.g. trace(dplyr::tibble, browser) 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by KasperThystrup** [comment]
Related to this as well:  #6740

**Comment by KasperThystrup** [comment]
May be fixed with #13925 

Will return as soon as sys.admins have updated the software center ...

**Comment by kevinushey** [comment]
> BTW. Don't have admin rights of my laptop, so can't test on latest version, but expect it to be there as well, as this has annoyed me across various versions (don't know whether behavoir has been there always or was later introduced)

You might be able to user one of the installer-less builds of RStudio; these are builds of RStudio that you can unpack and run from any directory without an explicit installation step. The current daily build for Windows is https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2024.10.0-daily-188.zip.

**Comment by kevinushey** [comment]
Glad to hear it; thanks for testing and confirming!
