### ISSUE TITLE
Setting breakpoints forces function/package/etc. to be sources before breakpoint is activated

### ISSUE THREAD

**Issue by hdshea** [rstudio/rstudio#15201]
### System details

    RStudio Edition :  Workbench version
    RStudio Version : 2024.04.1+748.pro2
    OS Version      :  Ubuntu 22.04.4 LTS
    R Version       :  R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem
Use this simple function:
test_f <- function(x, y){
  x <- x + 1
  y <- y + 1
  x * y
}

Source the function within the RStudio IDE

Set a breakpoint somewhere in the code using the RStudio IDE

![image](https://github.com/user-attachments/assets/500e809b-4b08-44d1-b040-e735f25a3541)

### Describe the problem in detail
Setting breakpoints forces function/package/etc. to be sources before breakpoint is activated.  This seems to be a regression as it is different behavior from earlier versions.  (For complete transparency, Kevin Ushey and Jonathan McPherson confirmed the persistence and replicability of the issue on latest versions of the IDE).

### Describe the behavior you expected
Breakpoint should be accepted without requiring re-sourcing.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Reproduced the problem in 2024.04.2+764, tried again in 2024.11.0-279 and confirmed this is now working.
