### ISSUE TITLE
Copilot keyboard shortcut appears to invoke copilot, even when copilot is not enabled

### ISSUE THREAD

**Issue by cm421** [rstudio/rstudio#15213]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764.pro1 
    OS Version      : MacOS 14
    R Version       : 4.1.0

### Steps to reproduce the problem

With Copilot _disabled_ in the settings:

1. Open an R script
2. Use the shortcut `Cmd + \` to request a copilot suggestion

Even though copilot is disabled, the status bar shows that it is waiting for copilot completions
![Screenshot 2024-09-24 at 12 02 11 PM](https://github.com/user-attachments/assets/49c81b32-8c57-4f79-86df-63bbef483775)

### Describe the problem in detail

Checking the session logs shows that copilot is never actually invoked:

```
DEBUG - Handle foreground: /rpc/copilot_generate_completions after: 0.57
DEBUG [ensureAgentRunning]: Copilot is not enabled; not starting agent.
DEBUG Queued event: async_completion
DEBUG --- complete:        /rpc/copilot_generate_completions in: 0.00
```

But the status bar continues to show that it's waiting for completions. Additionally, this could be particularly alarming for someone working in an environment where copilot is intentionally not being used, as at first glance it appears copilot was activated and used from the status bar.

### Describe the behavior you expected

The shortcut shouldn't do anything if copilot is disabled.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/f5306131ae1b142cafaeaa1559e41cb57cca9554

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+298 on Windows 11.
