### ISSUE TITLE
clicking in editor gutter to toggle a breakpoint also selects the associated line

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#15226]
For example:

https://github.com/user-attachments/assets/341d8cfc-12cb-429d-b7c1-b1f6b63ef873

Ideally, we would only toggle the line selection if the user clicked on the line numbers themselves, or if breakpoints aren't enabled for that file type.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+236 on Windows 11. Also checked that nothing happens when a breakpoint can't be set.
