### ISSUE TITLE
rstudio-server: flooding system logs with "WARNING rConsoleRead called in forked process"

### ISSUE THREAD

**Issue by s-u** [rstudio/rstudio#15221]
### System details

    RStudio Edition : Server
    RStudio Version : 2024.04.2+764
    OS Version      : Ubuntu 20.04.1 LTS
    R Version       : 4.3.1

### Steps to reproduce the problem

```
parallel::mcparallel(menu(letters), mc.interactive=TRUE)
```

Floods the system log with many thousands of log entries per second, possibly killing the machine (DoS).

The code above merely illustrates the shortest way to replicate the problem. The actual code encountered in reality is typically buried in a some R package that calls ReadConsole expecting specific input in a parallel section so the user doesn't even know that the equivalent is happening.

### Describe the problem in detail

There is no rate-limiting of errors/warnings which means that RStudio can kill a machine with just simple (typically unintentional) code which will produce thousands of log lines per second. Real case here >20k messages per second:

```
$ journalctl --user  | uniq -c
  16411 Sep 24 20:10:51 stats04 rsession-xxx[1180657]: WARNING rConsoleRead called in forked process; LOGGED FROM: bool rstudio::session::console_input::rConsoleRead(const string&, bool, rstudio::r::session::RConsoleInput*) src/cpp/session/SessionConsoleInput.cpp:372
  26956 Sep 24 20:10:52 stats04 rsession-xxx[1180657]: WARNING rConsoleRead called in forked process; LOGGED FROM: bool rstudio::session::console_input::rConsoleRead(const string&, bool, rstudio::r::session::RConsoleInput*) src/cpp/session/SessionConsoleInput.cpp:372
  28281 Sep 24 20:10:53 stats04 rsession-xxx[1180657]: WARNING rConsoleRead called in forked process; LOGGED FROM: bool rstudio::session::console_input::rConsoleRead(const string&, bool, rstudio::r::session::RConsoleInput*) src/cpp/session/SessionConsoleInput.cpp:372
  27338 Sep 24 20:10:54 stats04 rsession-xxx[1180657]: WARNING rConsoleRead called in forked process; LOGGED FROM: bool rstudio::session::console_input::rConsoleRead(const string&, bool, rstudio::r::session::RConsoleInput*) src/cpp/session/SessionConsoleInput.cpp:372
  26493 Sep 24 20:10:55 stats04 rsession-xxx[1180657]: WARNING rConsoleRead called in forked process; LOGGED FROM: bool rstudio::session::console_input::rConsoleRead(const string&, bool, rstudio::r::session::RConsoleInput*) src/cpp/session/SessionConsoleInput.cpp:372
```

It may be argued that this is more of an admin problem, but, unfortunately, journald-based systems lack effective filtering tools and default rate limits are too high.

### Possible Solution

There are several possible solutions, partially independent:
- do not repeat the same WARNING indefinitely. Especially with the ReadConsole warning there is a good chance that the loop is infinite and tight, because the user has no way to provide the desired input, so especially that warning shouldn't be produced repeatedly (or possibly elevate it to an error when escalated?).
- rate-limit the service by adding `RateLimitIntervalSec=` and `LogRateLimitBurst=` to `rstudio-server.service`

### Describe the behavior you expected

Limit the log output to not flood the machine to the point of a DoS (the later occurs when it manages to fill up all log space).

---

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I first reproduced the problem with 2024.04.2-764 on Ubuntu 24 using the given example, which logged a massive number of the rConsoleRead warnings.

Then repeated with build 2024.11.0-277 and the ultra-verbose logging was fixed (gone).
