### ISSUE TITLE
.qmd file in a newly created quarto project is not opened in the source pane by default

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#15222]
### System details

    RStudio Edition : Server
    RStudio Version : 2024.10.0-143
    OS Version      : 
    R Version       : 
    Automation test: test_create_quarto_project

### Steps to reproduce the problem

1. Create a new quarto project.
2. Observe the source pane after creating the project.

**Note:**
2024.10.0-142 - worked (3b2f622, 2024-09-11)
2024.10.0-143 - failed (3cc2ba0, 2024-09-11)

### Describe the problem in detail
The .qmd file created in the quarto project is not open in the source pane by default after creating the project.

https://github.com/user-attachments/assets/49a565f7-30c0-471e-81c0-ce1b9f82598c

### Describe the behavior you expected
The .qmd file created in the quarto project should open in the source pane by default after creating the project.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: Also true in RStudio Desktop. (Checked in version 2024.10.0-daily+236 on Windows11.)

**Comment by ronblum** [comment]
This problem occurs with Shiny projects, as well--the `app.R` file is supposed to be open by default, but isn't.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+258 on Windows 11 that the Quarto default file shows up. However, the Shiny project's app.R file still doesn't. Should it stay as part of this issue or would you like me to open a new one?

**Comment by kevinushey** [comment]
Thanks -- can you open a separate issue for that one @ronblum?

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/40e3b0b4e20afb684c1ccdfa5cb6eed2f29435b7

**Comment by ronblum** [comment]
While at, verified all Quarto project types in RStudio Server 2024.11.0-daily+258:-
- Quarto Project
- Quarto Website
- Quarto Blog
- Quarto Book
- Quarto Manuscript
