### ISSUE TITLE
building any package fails when set to generate docs on build 

### ISSUE THREAD

**Issue by ergz** [rstudio/rstudio#15236]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2024.09.0+375 "Cranberry Hibiscus" Release (c8fc7aee6dc218d5687553f9041c6b1e5ea268ff, 2024-09-16) for Ubuntu JammyElectron/30.4.0 Safari/537.36, Quarto 1.5.57
    OS Version      :  Ubuntu 24.04
    R Version       :  4.4.1

### Steps to reproduce the problem

1. Start a new project and select package template. 
2. Go to build menu and configure build tools
3. Enable generate docs, and enable "Install and Restart"
4. Ctrl+Shift+B to build

the build will fail with the just the hello world package example with the following error:

```
==> roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace')

Error: unexpected '}' in "suppressPackageStartupMessages({ Sys.setlocale('LC_COLLATE', 'C'); roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace') }"
Execution halted

Exited with status 1.
```

### Describe the problem in detail

Roxygen fails when using build from rstudio, calling

`roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace')` 

directly appears to work

### Describe the behavior you expected

The build to work

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ergz Thank you for raising this! I'll mark this for review.
- I can reproduce the problem in RStudio Desktop 2024.09.0+375 on Ubuntu 24.
- It's also reproducible on MacOS 15

However
- It works correctly on Windows 11.
- It worked correctly in the last release, 2024.04.2+764, on MacOS 15.

There's a missing parens at the end of the `roxygenize` command on Ubuntu and MacOS:
```
roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace')
```

The closing parens is present in Windows and the previous release on MacOS.

Note: I removed `devtools` in order for `roxygen2` to take over.

**Comment by kevinushey** [comment]
Thanks for the bug report. As a workaround, I believe this will work if you make sure `[ ] Use devtools package functions if available` is checked, and ensure `devtools` is installed.

<img width="574" alt="Screenshot 2024-09-27 at 12 12 23 PM" src="https://github.com/user-attachments/assets/e49cf0a6-dcef-4f70-9aa5-b8af0d8cdda3">

**Comment by kevinushey** [comment]
Triage note: probably a candidate for bundling into a patch release (if we need to prepare one)

**Comment by ergz** [comment]
workaround worked for me, thanks!

**Comment by kevinushey** [comment]
Backported a fix to rel-cranberry-hibiscus with https://github.com/rstudio/rstudio/commit/e7dfb52f6182874bd947e64a591fd965952ba974.

**Comment by gtritchie** [comment]
Repro'd with 2024.09.0+375 on MacOS, confirmed working with 2024.09.1-389 and 2024.11.0-279.

**Comment by coatless** [comment]
To get this fix, the user needs nightlies still. Do you know when the stable version will be released? 

<img width="1156" alt="Screenshot of RStudio with the error in the build panel under 2024.09.0+375 on MacOS" src="https://github.com/user-attachments/assets/27dfe7e5-ef00-4b66-8489-5412e6ebbe65">

**Comment by kevinushey** [comment]
This fix will be part of an upcoming patch release (hopefully to be released soon, I believe)

**Comment by coatless** [comment]
Thanks @kevinushey !
