### ISSUE TITLE
the build pane no longer interrupt the current process if a new request is sent.

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15231]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.10.0+218
    OS Version      : Windows
    R Version       : 4.4.1

### Steps to reproduce the problem

In a package project, run testthat tests in the build pane.

Try running them again.

As reported in https://github.com/rstudio/rstudio/issues/15214#issuecomment-2374660651, it was possible to interrupt the build pane process by simply sending another request. This was broken in recent commits.

### Describe the problem in detail

The build pane doesn't respond to a new request.

### Describe the behavior you expected

I would expect that a new process would interrupt the current one in the build pane

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment]
I just noticed something unusual while reviewing snapshot tests results.

The build pane was running. I ran `testthat::snapshot_review()`. I wanted to exit that. I pressed Esc. And now both processes end: the shiny app + the tests process running in the Build Pane. Previously, only the Shiny App would end, as expected.

Pressing `Esc` never had any effect on the Build Pane before.

**Comment by ronblum** [comment]
Reproducible in RStudio Desktop 2024.09.0+375 and 2024.11.0-daily+302 on Windows 11. I can also reproduce this in older versions, though, like 2023.12.1+402. @olivroy what version have you seen this work in?

**Comment by olivroy** [comment]
I just reviewed. You are right. All of this was there before. Sorry for the mistake. I thought this was a new regression, but was mistaken.

**Comment by ronblum** [comment]
@olivroy No problem!
