### ISSUE TITLE
Autocomplete is active when R is prompting the user for input

### ISSUE THREAD

**Issue by homerhanumat** [rstudio/rstudio#15238]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.09.0+375
    OS Version      : MacOS Sonoma 14.6.1
    R Version       : 4.4.1

### Steps to reproduce the problem

* enter `readline("(gimme)")` at the console
* type characters until you see the autocomplete popup

### Describe the problem in detail

This is what I get after typing three characters (the default for activation of autocomplete):

<img width="204" alt="Screenshot 2024-09-27 at 1 27 28 PM" src="https://github.com/user-attachments/assets/3efffea6-aa9d-4780-b2d6-e3f9fbbf8434">

<br>

The behavior occurs when the `prompt` string contains a matching pair of parentheses, as above, or a matching pair of square brackets, as in `readline("[gimme]")`.

### Describe the behavior you expected

We don't expect autocomplete in this context.  The user is primed to press the Return key when done, with the effect of entering the suggestion provided by autocomplete instead of the desired input.  (The suggestion can be declined by clicking the cursor prior to entering, but it can take a while for users to figure this out.)

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

## Note

This report resurrects Issue [5738](https://github.com/rstudio/rstudio/issues/5738).

**Comment by kevinushey** [comment]
The intention here was to support auto-completion of choices in situations like:

<img width="487" alt="Screenshot 2024-09-27 at 12 15 39 PM" src="https://github.com/user-attachments/assets/c90e256a-8cdc-43b7-8971-e3be61f0bab0">

Perhaps we need to be more strict in when we try to do this.

**Comment by ronblum** [comment]
Note: <kbd>Esc</kbd> will also work to make the autocomplete menu disappear so that <kbd>Return</kbd> can be used.

**Comment by kevinushey** [comment]
I'm pretty sure we've had that behavior forever, and it's adjacent to the issue here. I think we can close the issue.

**Comment by homerhanumat** [comment]
Thanks everyone!  This should help with use cases like:

```
readline("Give me another item (or enter q to quit)")
```
