### ISSUE TITLE
Error installing RStudio Server for WSL Ubuntu 22.04

### ISSUE THREAD

**Issue by bschneidr** [rstudio/rstudio#15245]
### System details

    RStudio Edition : Server
    RStudio Version : v2024.09.0+375 
    OS Version      :  WSL Ubuntu 22.04.5 LTS
    R Version       :  4.4.1
    Platform        :  x86_64-pc-linux-gnu

### Steps to reproduce the problem

Attempt to install RStudio using the steps provided here: https://posit.co/download/rstudio-server/, under the section for Debian 12 / Ubuntu 22.

1. `sudo apt-get install gdebi-core`
2. `wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2024.09.0-375-amd64.deb`
3. `sudo gdebi rstudio-server-2024.09.0-375-amd64.deb`

```bash
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libssl1.0.0|libssl1.0.2|libssl1.1
```

### Describe the problem in detail

The problem is the error message I received `Dependency is not satisfiable: libssl1.0.0|libssl1.0.2|libssl1.1`.

### Describe the behavior you expected

I thought this installation error message wouldn't appear when trying to install this version of RStudio Server, based on the discussion in #10902 from a couple years ago. I thought that RStudio had updated to a more recent version of libssl as a requirement.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bschneidr Thank you for raising this! I'm unable to reproduce the issue, though: I can install RStudio Server and connect to it on WL 22.04.3. I'll see if updating to 22.04.5 makes a difference.

Please note that we don't support WSL, so I'm not sure of how far we'll get.

**Comment by bschneidr** [comment]
Good morning Ron, I appreciate your quick response and time even though WSL isn't supported.

I have no idea why the issue occurs for me and couldn't be reproduced outside my computer. I managed to sidestep the problem by updating to Ubuntu 24.04.1, and then following the provided [RStudio instructions for Ubuntu 24](https://posit.co/download/rstudio-server/), which worked fine.

I will go ahead and close this ticket, but maybe someone else will come along with this problem later. Hopefully it's a rare enough issue that you won't have to think about this problem again. Thanks, Ron.

**Comment by ronblum** [comment]
@bschneidr I'm glad that the upgrade to 24.0.4.1 worked--though sorry that you had to upgrade. And thank you for the update, of the benefit of others!
