### ISSUE TITLE
Renaming an unsaved file loses changes

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15242]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2024.09.0+375 (not a regression, repro'd back to 1.4, oldest I tried)
    OS Version      : Any
    R Version       : 4.4.1

> [!NOTE] 
> https://www.reddit.com/r/RStudio/comments/1fqz6mb/comments_disappeared_after_saving_file_and/

### Steps to reproduce the problem

- create a new R script, enter some text, e.g.:

```R
# one
```

- save file as `one.R`
- make noticeable edits to the file, e.g.

```R
# one
# two
```
- without saving the changes, do File / Rename and change the name to `two.R`
- note that the "unsaved" indicator next to the filename in the tab is gone
- close the file
- re-open the file

### Describe the problem in detail

The changes made before renaming are lost.

### Describe the behavior you expected

No data loss.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
This works correctly on Windows 11. Or at least, the file gets automatically saved when renaming--the unsaved indicator goes away, and when reopening the file, the correct contents are present.

**Comment by gtritchie** [comment]
I am able to repro 100% of the time on Windows-11 using the recent Cranberry Hibiscus release.

**Comment by ronblum** [comment]
I had <kbd>Tools -> Global Options -> Code -> Saving -> When editor is idle</kbd> set to "Save and write changes," and I was moving slowly and methodically. (TY @gtritchie for guidance)

**Comment by gtritchie** [comment]
Also repro's on Server, updated issue description.

**Comment by gtritchie** [comment]
Data point: this bug repro's with the default autosave/save on idle settings.

![Image](https://github.com/user-attachments/assets/81fe7f5c-6fe8-4558-8607-a5b067ee459c)

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2024.11.0-daily+258 on Windows 11
- RStudio Server 2024.11.0-daily+258 on Ubuntu 22.04 via Edge on Windows 11

Note: The save happens when opening the rename dialog, even if the file isn't renamed. However, this is a far better experience than the data loss of the previous behavior.
