### ISSUE TITLE
Visual Editor loses raw latex code blocks

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#15253]
This report is very similar to https://github.com/rstudio/rstudio/issues/15189 but the problem also applies raw tex blocks, e.g.,

````
```{=tex}
\LaTeX
```

```{=latex}
\LaTeX
```
````

Switching between visual and source modes will lose the backtick fences. In previous RStudio (and pandoc), the `latex` raw block would be preserved (but the `tex` one was lost).

This issue covers only the change in behaviour for `latex` raw blocks.

However, I discovered that other types of raw blocks would be preserved (not sure why), e.g.,

````
```{=openml}
<w:p>
  <w:r>
    <w:br w:type="page"/>
  </w:r>
</w:p>
```

```{=ms}
.MYMACRO
blah blah
```
````

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
> I discovered that other types of raw blocks would be preserved (not sure why)

That is expected, I think. The pandoc change that caused all of this specifically targeted raw tex and html:

Pandoc Issue: https://github.com/jgm/pandoc/issues/9677
Pandoc Change: https://github.com/jgm/pandoc/commit/f5c7d4dcf73d8259435ab44b072c719f52f00757

**Comment by gtritchie** [comment]
Older versions of RStudio before Cranberry Hibiscus (2024.09) also lost blocks using {=tex} when switching to Visual Editor mode.

````
```{=tex}
\LaTeX
```
````

became:

````
\LaTeX
````

But they did preserve {=latex}, so:

````
```{=latex}
\LaTeX
```
````

did survive round-trip through Visual Editor.

**Comment by gtritchie** [comment]
Opened same issue against VSCode Quarto extension: https://github.com/quarto-dev/quarto/issues/558

**Comment by gtritchie** [comment]
@yihui I'm using this issue just for the `latex` issue. The `tex` issue isn't a new problem, so not as urgent.

If you want, go ahead and open another issue on `{=tex}` for future consideration.

**Comment by yihui** [comment]
Fixing the regression for `latex` will be good enough. Thank you very much!

**Comment by gtritchie** [comment]
The fix should be in the next daily builds of both Cranberry Hibiscus (2024.09.1), and Kousa Dogwood (2024.11.0).

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+277 on Windows 11. However, it looks like the fix isn't in Cranberry Hibiscus (2024.09.1+388).

**Comment by gtritchie** [comment]
The Windows build failed to pull in the updated script, but Mac and Linux did.

**Comment by gtritchie** [comment]
Build 2024.09.1-389 does have the fix. Moving back to test. :-)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.09.1+390 and 2024.09.1+390 that code for raw latex blocks is maintained.
