### ISSUE TITLE
Strip trailing whitespace when saving no longer seems to work

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15254]
### System details

    RStudio Edition : Desktop
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1.Have the setting of trailing whitespace suppression turned on at project / user level
2. save a file and make sure you have a trailing whitespace.
3. Look if the trailing whitespace has disappeared

### Describe the problem in detail

The file still has trailing whitespace. the editor no longer seems to suppress trailing whitespace.

### Describe the behavior you expected

I would expect the setting to work. (It works properly with 2024.09) Seems it was broken with  #15147

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment]
Just tested the 2024.11.0+309 version and still having this issue

**Comment by kevinushey** [comment]
In what kind of file were you seeing this behavior? We don't trim trailing whitespace for certain file types, since that trailing whitespace can actually be significant in some scenarios.

Currently, we ignore the preference value for Markdown, Python, and DESCRIPTION files.

**Comment by olivroy** [comment]
In regular R files.. this is causing a spurious diff in one of my PRs. As a workaround, I have to call styler:::style_active_file() if I want to strip trailing whitespaces. https://github.com/r-lib/tidyselect/pull/361/files#diff-f4b96ac6aaff635a2ba26f0b7aaf6fdfcaadb16561dd7f15f057baa27bf953feR144

**Comment by kevinushey** [comment]
Thanks -- let me take a closer look.

**Comment by kevinushey** [comment]
Should be fixed up in the next daily builds -- thanks for catching that and reporting!

**Comment by olivroy** [comment]
Now fixed up! (2024.11.0+326) Thanks
