### ISSUE TITLE
app.r file in a newly created Shiny project is not opened in the source pane by default

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#15275]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 2024.11.0-daily+261
    OS Version      : N/A
    R Version       : N/A

### Steps to reproduce the problem

Create a new Shiny Application project.

### Describe the problem in detail

The default `app.R` file isn't automatically opening up.

### Describe the behavior you expected

The default `app.R` file should open up automatically. The file is created, just not shown.

See issue #15222 for Quarto projects, which spawned this issue.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be fixed as part of https://github.com/rstudio/rstudio/commit/40e3b0b4e20afb684c1ccdfa5cb6eed2f29435b7.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+269 on Windows 11.
