### ISSUE TITLE
Blurry colored output.

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#15282]
Encountered when testing `uv` with reticulate. Colored output appears blurry

![image](https://github.com/user-attachments/assets/e7c54796-8cfe-48e8-be23-e3ddd0b2ba7c)

The same output in Gnome Terminal
![image](https://github.com/user-attachments/assets/b1a0acc6-4b3a-4d92-81be-a71aec29522a)

To reproduce, in R:
```r
path <- path.expand("~/.virtualenvs/r-reticulate")
system(paste("uv venv --no-project --seed --no-config --python-preference only-managed --python 3.11 path"))
system(paste(
  "uv pip install --python", file.path(path, "/bin/python"), 
  "docutils pandas scipy matplotlib ipython tabulate plotly psutil kaleido wrapt"
))
```

**Comment by kevinushey** [comment]
It looks like this is because we implemented support for the ANSI escape `CSI 0 2`, which `uv` is emitting here, but did so via literally blurring the text. https://bugzilla.gnome.org/show_bug.cgi?id=791596 has:

```
ECMA-48 says:
  SGR 2   faint, decreased intensity or second colour

ITU-T Recommendation T.416 says:
  SGR 2   Faint or decreased intensity
```

We should update our theme definitions to do something more appropriate here.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+298 on Windows 11.

QA note: `uv` installed via `pip`.
