### ISSUE TITLE
Publishing doesn't occur when started from a rendered file previewed in a window

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#15289]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.11.0-daily+269
    OS Version      : Windows 11
    R Version       : 4.4.1

### Steps to reproduce the problem

1. Create an R Markdown file. The default will do.
2. Set knitting to "Preview in Window".
3. Knit the file
    - The rendered file opens in a new Window.
4. Click on the "Publish" button.
5. Go through the publishing wizard, until pressing the "Publish" button.

### Describe the problem in detail

After a brief moment, the dialog correctly closes. However, after the IDE is brought back into focus, nothing happens. There's no failure message--just nothing.

### Describe the behavior you expected

Deployment should occur, with the logs in the "Deploy" tab. 

This works correctly when publishing from the source file and for a document previewed in the View Pane.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Regression from https://github.com/rstudio/rstudio/pull/15131.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+336.pro2 on Windows 11, publishing to a Connect instance.
