### ISSUE TITLE
utils::savehistory() does not work on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#15292]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.11.0 Build 275
    OS Version      : Windows 11
    R Version       : 4.4.1; 3.6.3

### Steps to reproduce the problem

```
   tf <- tempfile()
  utils::savehistory(tf)
  file.exists(tf) # FALSE....?
```

The history file should exist after calling `savehistory()`.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+298 that file exists and that it contains the history.
