### ISSUE TITLE
Save As... + autosave prematurely saves

### ISSUE THREAD

**Issue by WilDoane** [rstudio/rstudio#15303]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.10.1
    OS Version      :  MacOS 15.0.1
    R Version       : 4.4.1

### Steps to reproduce the problem

- Tools > Global options > Code > Saving > Automatically save when editor loses focus: Checked
- Open a previously saved R script
- Make any change
- Click File > Save As...

File immediately saves to the previous filename, clobbering the unchanged version of the file (and making the save as... functionality somewhat useless).

### Describe the problem in detail

The editor loses focus when the Save As... dialog pops up, causing the changed file to clobber the existing file on-disk. That seems at odds with the purpose of Save As...

### Describe the behavior you expected

The existing file should remain unchanged, The new file should contain any changes made.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
This is still an issue in RStudio Desktop 2024.11.0-daily+298 on Windows 11. I have autosave turned on to "save and write changes" with a 3,000 ms idle period.

**Comment by ronblum** [comment]
Works correctly in RStudio Desktop 2024.11.0-daily+309 on Windows 11.

However, In Posit Workbench, it's not just `Save As`--clicking on the menus like `File`, `Edit`, `Plots`, etc., will trigger the autosave, even if it's set to "Do nothing," in Posit Workbench 2024.11.0-daily+309.pro1 on RHEL 8. I'm not sure if this was already an issue.

**Comment by kevinushey** [comment]
> However, In Posit Workbench, it's not just Save As--clicking on the menus like File, Edit, Plots, etc., will trigger the autosave, even if it's set to "Do nothing," in Posit Workbench 2024.11.0-daily+309.pro1 on RHEL 8. I'm not sure if this was already an issue.

Isn't this related to the "Automatically save when editor loses focus" preference? If you have that checked, then it sounds like this is working as intended.

<img width="674" alt="Screenshot 2024-10-29 at 9 57 09 AM" src="https://github.com/user-attachments/assets/bc429ddb-d554-4501-931f-27ca78809300">
 of the

**Comment by ronblum** [comment]
Shoot, I was focusing on the wrong preference, sorry about that. All set!
