### ISSUE TITLE
Add capability to label BRAT tests and select which label(s) to run

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15301]
It would be nifty and swell if the "Built in R Automation Tests" allowed labelling individual tests, and specifying which label(s) to match when choosing tests to run.

One idea is a convention such as:

`test_that("[editor] [smoke] do the thing", {})`

**Comment by kevinushey** [comment]
Another alternative, which might be appropriate if we wanted to use many markers:

```
markers[editor, smoke, too, many, labels]
test_that("we do the thing", { ... })
```

**Comment by gtritchie** [comment]
I've confirmed and used this functionality in recent KD builds, so closing.
