### ISSUE TITLE
RStudio UI hangs when switching a R Markdown or Quarto document to be a plain text file

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15313]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2024.07.0+178 (first build with the problem) up through current daily builds of 2024.11.x
    OS Version      : any
    R Version       : any

The commits between last-working build and the first-breaking build were:

- https://github.com/rstudio/rstudio/pull/14760
- https://github.com/rstudio/rstudio/pull/14761

### Steps to reproduce the problem

- File / New File / R Markdown... (or create a new Quarto document)
- accept defaults
- doesn't matter if using Visual Editor or Source editor
- click on the File Type widget in the lower-right of the editor and change the type to "Text file"

<img width="651" alt="screenshot showing changing file type to text" src="https://github.com/user-attachments/assets/1e45d6fe-7a71-42fd-931a-94dd7841fe80">

### Describe the problem in detail

- RStudio UI freezes and must be force-killed (or the browser tab closed if using Server)

### Describe the behavior you expected

- Document displays as plain text and app doesn't hang

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Conversion to some other file types like SQL, XML, and CSS leads to this, as well.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+302 on Windows 11. Checked multiple file types--the changes are correct, instantaneous, and the IDE works normally.
