### ISSUE TITLE
Find in Files stops working when there is an `_quarto.yml` file with a Quarto project

### ISSUE THREAD

**Issue by danielvartan** [rstudio/rstudio#15329]
### System details

    RStudio Edition: Desktop
    RStudio Version: 2024.09.0 Build 375
    OS Version: Windows 11 Home Single Language (Version 24H2)
    R Version: 4.4.1

### Steps to reproduce the problem

1. Create a new project in an empty directory (e.g., `test.Rproj`).
1. Create a Quarto `qmd` file and add the word `test` to it (e.g., `test.qmd`).
1. Create a file named `_quarto.yml`, add the code below, and save it.
1. Open `Find in Files` (`Edit` > `Find in Files...`) and search for the word `test`.
1. Restart R (`Session` > `Restart R`).
1. Open `Find in Files` (`Edit` > `Find in Files...`) and search for the word `test`. (**HERE IS THE ISSUE**)
1. Remove the `project` section from the `_quarto.yml` file and save it.
1. Restart R (`Session` > `Restart R`).
1. Open `Find in Files` (`Edit` > `Find in Files...`) and search for the word `test`.

```yml
editor: source

project:
  output-dir: "."
```

### Describe the problem in detail

The `Find in Files` functionality stops working when an `_quarto.yml` file contains a Quarto project.

A video demonstrating the issue can be found here: https://www.loom.com/share/d8e7cddf3f894412a82638d2208e16ec?sid=db985e0b-8894-457f-8eda-9821a6887dce

### Describe the behavior you expected

I expected the `Find in Files` feature to function correctly, even with a Quarto project configuration in the `_quarto.yml` file.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
QA note: Check older releases as well.

**Comment by kevinushey** [comment]
Thanks; we were able to reproduce. We'll take a look!

**Comment by kevinushey** [comment]
It looks like this is intentional. We explicitly screen content from the declared output directory from Find in Files here:

https://github.com/rstudio/rstudio/blob/078b340227981ae43ac4e4f56b2f0c84302aeb59/src/cpp/session/SessionModuleContext.cpp#L2932-L2936

and so everything within the output directory, including source files, are effectively ignored. Is there a particular reason why you want to use the project root directory as the output directory?

**Comment by danielvartan** [comment]
You're absolutely right — the project root directory is the default when rendering Quarto documents.

Now that you pointed it out, I realized this code is a leftover from other Quarto projects that used different output directories. I copied it without thinking, but it’s unnecessary here.

Thanks for your help, @kevinushey!

**Comment by kevinushey** [comment]
Thanks for following up!
