### ISSUE TITLE
autocomplete not working correctly for variables starting with digit

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#15343]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.09.1+394 "Cranberry Hibiscus" 
    OS Version      : Windows 11
    R Version       : 4.4.1

### Steps to reproduce the problem

Create a data.frame and try to access the information in the first column using tab completion after the $ sign.
```r
df <- data.frame("1" = 1:3, check.names = FALSE)
df$
```

### Describe the problem in detail

Autocomplete completes the line above as df$1 instead of the correct ``` df$`1` ```.

### Describe the behavior you expected

Correct auto completion.

This doesn't only happen when a column name consist of just a number. As long a a column name starts with a number this happens. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by igorvdw** [comment]
This looks similar to what was reported here about numeric variable names in lists objects: https://github.com/rstudio/rstudio/issues/13290
Just wanted to add that this issue sometimes tricks me as well, so any fix is appreciated.

**Comment by ronblum** [comment]
Thank you @BartJanvanRossum for raising this, and @igorvdw for pointing out the other issue, #13290! I'm going to close this as a duplicate but copy over the info as another example.
