### ISSUE TITLE
Multiline console previous entries no longer works properly

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15345]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.11.0.309
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.4.1 (2024-06-14 ucrt)

### Steps to reproduce the problem

1. In the console, type

```r
f(
  x
)
```

2. Execute the code
3. Press the up arrow to retrieve the previous selection

### Describe the problem in detail

We get only the last bracket when trying to retrieve the last command.

With the dev version:
![image](https://github.com/user-attachments/assets/1d1fd2a7-24af-43d6-993b-78b7659cbe08)

With Cranberry hibiscus
![image](https://github.com/user-attachments/assets/8c45bd8f-bdee-4e01-941a-763a1f1179f7)

### Describe the behavior you expected

This worked in previous versions of RStudio
I'd expect to be able to retrieve the full call, as it was before.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It looks like duplicate entries are entering the console history -- if you go back further, you'll see the full call.

**Comment by olivroy** [comment]
Oh, great! Yes, indeed. I can see it when going up a little. Although not very practical for a long ggplot2 or dplyr pipeline

**Comment by gtritchie** [comment]
Verified this is behaving again in build 2024.11.0-hourly+321.
