### ISSUE TITLE
The Install button from the Build Pane no longer properly installs packages

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15344]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.11.0.309
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.4.1 (2024-06-14 ucrt)

### Steps to reproduce the problem

It seems that the installation is not logged in.

1. For example, I have Cran tidyselect installed, but working on the package `usethis::create_from_github("r-lib/tidyselect")`

Note the version on Cran is currently 1.2.1 (dev is 1.2.1.9000)

2. In the Build Pane, click on the Install button to install the local version of the package.

### Describe the problem in detail

The package is not correctly installed.

![image](https://github.com/user-attachments/assets/b7c7494a-4622-4b3e-a4b0-29cf025ab41a)

When I call `packageVersion("tidyselect")` in the console, I still get 1.2.1. I would expect 1.2.1.9000

### Describe the behavior you expected

I would expect the Install button to remove a previous installation of the package.

I think this is a regression.

If it is useful, I have other active RStudio sessions opened, but I don't remember it being an issue before.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I'm not able to reproduce:

![image](https://github.com/user-attachments/assets/04b1f74b-c26b-416e-ad80-f3f1d70c17ba)

Can you please provide more information?

**Comment by olivroy** [comment]
Ok. Let me see. I can reproduce it.

My session info is here

``` r
1
#> [1] 1
```

<sup>Created on 2024-10-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.1 (2024-06-14 ucrt)
#>  os       Windows 10 x64 (build 19045)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  French_Canada.utf8
#>  ctype    French_Canada.utf8
#>  tz       America/Toronto
#>  date     2024-10-23
#>  pandoc   3.2 @ C:/Users/RoyO/AppData/Local/Programs/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.3   2024-06-21 [1] CRAN (R 4.4.1)
#>  digest        0.6.37  2024-08-19 [1] CRAN (R 4.4.1)
#>  evaluate      1.0.1   2024-10-10 [1] CRAN (R 4.4.1)
#>  fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.4.1)
#>  fs            1.6.4   2024-04-25 [1] CRAN (R 4.4.1)
#>  glue          1.8.0   2024-09-30 [1] CRAN (R 4.4.1)
#>  htmltools     0.5.8.1 2024-04-04 [1] CRAN (R 4.4.1)
#>  knitr         1.48    2024-07-07 [1] CRAN (R 4.4.1)
#>  lifecycle     1.0.4   2024-08-20 [1] Github (r-lib/lifecycle@9302cea)
#>  reprex        2.1.1   2024-07-06 [1] CRAN (R 4.4.1)
#>  rlang         1.1.4   2024-06-04 [1] CRAN (R 4.4.1)
#>  rmarkdown     2.28    2024-08-17 [1] CRAN (R 4.4.1)
#>  rstudioapi    0.17.0  2024-10-16 [1] CRAN (R 4.4.1)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.4.1)
#>  withr         3.0.1   2024-07-31 [1] CRAN (R 4.4.1)
#>  xfun          0.48    2024-10-03 [1] CRAN (R 4.4.1)
#>  yaml          2.3.10  2024-07-26 [1] CRAN (R 4.4.1)
#> 
#>  [1] C:/Users/RoyO/AppData/Local/R/win-library/4.4
#>  [2] C:/Program Files/R/R-4.4.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>


It works with the old version of RStudio (2024.09..)

**Comment by kevinushey** [comment]
> #>  lifecycle     1.0.4   2024-08-20 [1] Github (r-lib/lifecycle@9302cea)

Seems odd that the version here is 1.0.4 but the package is reported to be from GitHub?

**Comment by olivroy** [comment]
I use this beanch https://github.com/r-lib/lifecycle/pull/184. ans indeed version was not updated

**Comment by olivroy** [comment]
But if you have any idea on how I can debug this, please let me know.. Like  options in the build pane maybe ?

**Comment by kevinushey** [comment]
The version number for lifecycle is indeed 1.0.4, even for the development version.

https://github.com/r-lib/lifecycle/blob/77fce9b8e2e8c2a781ba95d181d497da62d0b80f/DESCRIPTION#L3

**Comment by kevinushey** [comment]
@olivroy, any chance you can share an update? Does this issue still reproduce for you with the latest daily builds? Does the issue occur for all packages, or only certain ones?

**Comment by olivroy** [comment]
@kevinushey I am unfortunately still having this issue on my Windows machine (2024.11.0+326), but not on my Mac.

I don't really know how to reproduce. I was able to reproduce for all packages I tried (at least 3)

FWIW, this seems to be the only commit that touched the Build Pane https://github.com/rstudio/rstudio/pull/14990, but it seems unrelated.

Is there an option to print extra diagnostics?

I have RStudio installed in a non-standard location if this helps..

**Comment by olivroy** [comment]
But if this is too hard to reproduce, don't bother! I now use the workaround `pak::local_install()` in the meantime. Maybe other users will find a better way to repro this. However, this was a bit sneaky and it occurred for a little while before I reported it as I didn't notice right away.

**Comment by kevinushey** [comment]
Do you see anything in your error logs that coincide with your package installations? Help -> Diagnostics -> Show Log Files; check the most recent rsession log file.

There's a new option that controls whether package builds happen in a sub-directory, 'Use alternate library path when building package':

![image](https://github.com/user-attachments/assets/e55d99bb-ff3f-437c-be94-b655889f778a)

I suspect disabling that option (second from the top) will resolve the issue for you.

**Comment by olivroy** [comment]
@kevinushey Thank you for the tip! That was it! Disabling the option worked. Here are my *new* preferences

![image](https://github.com/user-attachments/assets/15459ab9-4b34-4f3b-9ed0-7645af3554c9)

Note that I don't have the "Save and reload R workspace on Build" enabled.

I think I may have found the bug:

If "Use alternate library path when building package" is **on** and "Save and reload R workspace on Build" is **off**, the package doesn't get installed properly. All other combinations work properly.

i.e. this may not work as expected
![image](https://github.com/user-attachments/assets/6e1f0526-b0de-45f7-9851-0fd691559588)

I just reverted to my original settings and everything works as expected...


---

Nothing stands out in the log file..

Getting a lot of 

```
 ERROR connect ENOENT \\.\pipe\rstudio
```

Code was modified in #15235

**Comment by kevinushey** [comment]
Aha! Thank you, I can reproduce locally now as well. Thanks so much for following up; now I can properly investigate and fix this :-)

**Comment by kevinushey** [comment]
Okay, https://github.com/rstudio/rstudio/commit/7469d3bac47cce06cd9d2a4913aa523d48c67c55 should fix the issue you saw. Thanks again for helping us nail it down!

**Comment by olivroy** [comment]
Thanks so much! Will try this tomorrow

**Comment by ronblum** [comment]
@olivroy Thanks for agreeing to test! FWIW I can't reproduce the original problem, so I can't confirm that it's fixed. (It's possible that my settings were off.)

**Comment by jlang-311** [comment]
Thank you @olivroy!
