### ISSUE TITLE
Splash screen shouldn't have a scroll bar

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#15355]
### System details

    RStudio Edition : Desktop
    RStudio Version : Several
    OS Version      : Windows and Ubuntu
    R Version       : N/A

### Steps to reproduce the problem

Start up RStudio Desktop.

### Describe the problem in detail

The splash screen sometimes has a scrollbar.

### Describe the behavior you expected

The splash screen should never have a scrollbar.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Fixed in PR #15349.

**Comment by kevinushey** [comment]
Confirmed that the splash screen is scroll-bar-less.
