### ISSUE TITLE
Toggling zoom in popped-out source window reverts buffer state

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1536]
Via: https://support.rstudio.com/hc/en-us/community/posts/115007195528-Bug-Zooming-with-CTRL-resets-all-code-in-detached-source-editor-window?page=1#community_comment_115003227528

Toggling the zoom in a popped out source window reverts the Ace editor contents to that which was used when the editor was initially popped out.

I reproduced this with RStudio Desktop on both on Windows and Ubuntu 14.04; I wasn't able to repro on macOS.

--

This happens because on those platforms we reload the source window on zoom changes (on mac we can just redraw without a reload).

The reason that reload does this is that source windows replay the source docs from the session.

https://github.com/rstudio/rstudio/blob/7f2e7ddc6b0b3ecb79703196af9dc07fe528fc67/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java#L844-L848

The contents and state of these docs are in the SessionInfo object. We could take one of a few routes to fix this:

a) Update the contents/dirty state in real time so that they are always correct. This might be expensive. It's something we already have to do to make sure the path is correct if it changes:

https://github.com/rstudio/rstudio/blob/7f2e7ddc6b0b3ecb79703196af9dc07fe528fc67/src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java#L1243-L1253

b) For source windows (which don't have the benefit of re-initing on reload), have them request the latest doc state known to the server via e.g. get_document instead of relying on the cached list in session info.

c) When we detect that the source window is about to reload, update the contents/dirty state of each doc in the cache. This is probably the best approach if we can get the unload handler hooked up correctly.

**Comment by gtritchie** [comment]
Easy to repro with 1.1.463, but I am unable to repro with RStudio (Desktop Windows) 1.2.1565.
