### ISSUE TITLE
Custom Environment pane "Data" descriptions

### ISSUE THREAD

**Issue by jtlandis** [rstudio/rstudio#15369]
I am currently writing an R package and found that my Rstudio session was hanging when a fairly large S4 object needed to be displayed in the environment pane. I haven't verified, but I believe the culprit is `utils::object.size()` as it is reporting an absurd 230 GB (and takes several minutes to calculate this value) as opposed to `lobstr::obj_size()` reporting 322 MB (and taking upwards of 5-10 seconds to calculate).

Is there any method to control how a data structure (i.e. not a vector or function) is displayed in the environment pane within Rstudio?

**Comment by kevinushey** [comment]
Unfortunately no, there isn't any mechanism for this currently.

We could either try to define some contract for this, or (perhaps more simply) add some alternate generate `objectSize` method that packages could provide methods for, and RStudio would use that if available, falling back to `base::object.size()` if not.

**Comment by jtlandis** [comment]
I like the idea of an `objectSize` method for objects. This slowdown makes using RStudio interactively a bit unbearable. Running an RScript non-interactively is quite fine though.

**Comment by gtritchie** [comment]
Verified using 2024.12.0-daily+364.
