### ISSUE TITLE
UTF-8 text in YAML header is mangled when rendering as new document type

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1537]
Reproduced on RStudio v1.1.44 on a Windows VM -- see attached gif. It seems that the rewritten YAML is mangled (likely an encoding problem -- missing a 'mark as UTF-8' call somewhere?)

![image](https://user-images.githubusercontent.com/470418/31103518-32c9c0a8-a78c-11e7-94e4-5ab54781df18.png)

Associated support forum post: https://support.rstudio.com/hc/en-us/community/posts/115000368387-Problem-with-accented-characters-in-YAML-headings-in-notebooks?page=1#community_comment_115000438627

Also reported on rmarkdown github issues:

https://github.com/rstudio/rmarkdown/issues/998

**Comment by jmcphers** [comment]
I can't make this happen any more, 1.2.100. @dfalty or @ronblum, are either of you able to reproduce?

**Comment by ronblum** [comment]
In 1.1.383, I sometimes see the problem in Windows, but it's inconsistent: sometimes I can get the exact same code to work. Also, I have not been able to reproduce this on RStudio Desktop on Mac and RStudio Server on SUSE. 

BTW, the problem is only with the title. The rest of the document remains untouched and renders properly. Confirmed with Roman letters, Greek, Hebrew, Japanese, and Anglo-Saxon runes (among others).

**Comment by ronblum** [comment]
The issue still exists in Windows v1.2.91, and I am able to reliably reproduce it. I added some Anglo-Saxon runes to the title, and when the title is long enough, "Knit to HTML" works correctly. However,  once I remove enough characters for a string length of 48, the problem occurs, but only in the title; the body renders correctly.
![issue1537_utf8_yaml](https://user-images.githubusercontent.com/31009952/31516739-959d7368-af67-11e7-8a37-f21b28a75e76.gif)

**Comment by GegznaV** [comment]
Is there any news towards solving this issue? In RStudio desktop 1.2.1091 it still persists.

**Comment by gtritchie** [comment]
@ronblum Does this still repro with latest 1.2 and/or 1.3 builds? Quite a bit has been done in this space, and I can't repro (but sounds like it can be a bit finicky to repro and you said you were able to).

Also this is our oldest active issue, and always fun to get rid of the oldest active issue.

**Comment by kevinushey** [comment]
I'm fairly confident that this commit fixed the issue: https://github.com/rstudio/rstudio/commit/9716ff47f6035398e18d6f1a1c313cf56b6b01bd

I can no longer reproduce, as well.
