### ISSUE TITLE
Change file and message dialogs back to web-based on Linux Desktop

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15372]
We switched Linux Desktop to use native file and message dialogs in the Kousa Dogwood release, but a user has discovered that [there is an issue with mixed-case extensions](https://github.com/rstudio/rstudio/issues/15340), preventing the "Open Project" dialog from opening projects.

So, we should revert that and go back to the web-based dialogs and once again wait on a fix from Electron.

As part of that will reopen https://github.com/rstudio/rstudio/issues/14683.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+331 on Ubuntu 24. First cleared out all user preferences using <kbd>Help -> Diagnostics -> Clear User Prefs</kbd>.
