### ISSUE TITLE
Can't sign out from RStudio Server if "Stay signed in" is checked when first logging in

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1538]
If you've chosen to "Stay signed in" when first logging in to RStudio Server, you can never sign out again after the first time you close all browsers. (If you sign out before exiting the browser app, signout will be successful.)

To reproduce:
1) Make sure you're logged out of RStudio
2) Log in to RStudio with "Stay signed in" checked
3) Close all browser windows
4) Open a browser window and visit RStudio. You will be automatically logged in.
--> 5a) Click on the signout icon in the upper right hand corner
or
--> 5b) Click on the "R" logo on the upper right to get to the home page, then click on the signout icon in the upper right hand corner

This takes you to the page "auth-sign-out" with the error
  Missing or incorrect token.

The only way to sign out at this point is to clear cookies.

RSP 1.1.374 on Ubuntu (Xenial), CentOS, and openSUSE.

**Comment by ronblum** [comment]
Another method to sign out—in addition to clearing out cookies—is to point the browser at the “auth-sign-in” page:
	<RStudio_Server_URI:port>/auth-sign-in

**Comment by jmcphers** [comment]
I'm surprised no one's reported this since the issue also exists in 1.0 (and has ever since we added CSRF protection). Fix is pretty simple, and presuming it performs well it's a candidate for backporting.

**Comment by dfalty** [comment]
Verified fixed 1.2.152-3.

**Comment by jmcphers** [comment]
Backported to 1.1 patch here: https://github.com/rstudio/rstudio/commit/b12580988eb4ab7d840d542d5912b6c89badb850
