### ISSUE TITLE
The editor doesn't recognize the data type inside `mutate()` and doesn't dispatch to methods

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15392]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.11.0.341
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.4.1 (2024-06-14 ucrt)

### Steps to reproduce the problem

This is a bit of a strange one. Here is my best diagnostic attempt:

Relates to #13611
1. In the following document, attempt to autocomplete

```r
library(tidyverse)
x <- data.frame(y = c(1, 1.5, 2, 3.5))
# case 1
x |> mutate(
  x = cut(y,        )
)
```

2. Attempt to complete after the first argument of `cut()`, i.e. to add additional arguments to the call.

### Describe the problem in detail

The completions are incomplete for objects inside pipelines vs not in pipelines

![image](https://github.com/user-attachments/assets/04968885-5597-435e-bb38-002bc486c1c4)

### Describe the behavior you expected

I would love if it could show all arguments, like it would when not in a tidyverse pipeline.

```r
x <- data.frame(y = c(1, 1.5, 2, 3.5))
cut(x$y, )
```
![image](https://github.com/user-attachments/assets/afbb0abe-f9bf-4474-9676-421a0b527351)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Ironically, the first case works because a dataset called `mpg` is created when `tidyverse` is loaded, and that's getting picked up when we try to infer how `cut` is being invoked. Compare:

```
mtcars |>
  mutate(
    x = cut(mpg,    )
  )
```

but this doesn't:

```
mtcars |>
  mutate(
    x = cut(cyl,    )
  )
```

In other words, RStudio doesn't understand the data-masking rules used by dplyr when looking up `mpg`, and assumes it must just be available from the global environment. Fixing this might require some work to see if we can wire in details around whether evaluation is happening in a dplyr data-masked context.

**Comment by olivroy** [comment]
Omg! Beginner mistake! I knew something was wrong in my assessment as it defeated all common sense! I will correct my issue

**Comment by olivroy** [comment]
I rewrote the issue. My goal is still the same, but my reasoning is more exact now. I have been always inclined to think that somewhat, RStudio was able to do this.

Here is a screenshot from 2024.04.2+764

![image](https://github.com/user-attachments/assets/faa1f91b-7b0f-46b7-be98-854e38866d77)

But I was actually mistaken.

If we use the `as.data.frame()`, to try to see if is able to dispatch properly, we see the following in 2024.04.2

![image](https://github.com/user-attachments/assets/a88055cd-34a4-4d4b-975d-3a2db695600b)

In 2024.11.0+364, the bug has been fixed as RStudio no longer looks at the type of the data to dispatch method, but it means we lose some argument completions in some cases.

![image](https://github.com/user-attachments/assets/bd9abb9d-0210-4aa3-b923-388b11a094dd)


as opposed to this when RStudio actually derives the type (unchanged across recent versions, support added for this in 2022 or 2023).

![image](https://github.com/user-attachments/assets/3370ad2b-1dbd-48d3-a555-55be86b93490)

**Comment by olivroy** [comment]
My initial diagnostic was wrong. This doesn't occur that much.

This isn't supported in Positron. It is a pretty rare issue, (the function you want to use has to be an S3 method that omits most arguments in its generic)

Apologies for the noise!
