### ISSUE TITLE
Notebook preview: Duplicated chunk when using a comma in the setup chunk

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1540]
---
    title: "Untitled"
    output: html_notebook
    ---
    
    ```{r, setup}
    "Duplicated Code Chunk"
    ```
    
    ```{r}
    "Missing Code Chuck"
    ```

![image](https://user-images.githubusercontent.com/470418/31103924-a0795e40-a78e-11e7-9701-f7fddfabdd9c.png)

**Comment by kendonB** [comment]
This appears to be fixed on 1.2.1578 and Windows 10.

![image](https://user-images.githubusercontent.com/5327505/67425055-cb888e80-f633-11e9-9c31-51f8703ad1e7.png)

**Comment by kendonB** [comment]
@jmcphers bump

**Comment by kevinushey** [comment]
This still reproduces for me with the latest daily builds.

<img width="401" alt="Screen Shot 2020-07-27 at 10 01 08 AM" src="https://user-images.githubusercontent.com/1976582/88569968-19ca2400-cff0-11ea-8a0a-5bde83033327.png">

To reproduce, I needed to run both the setup chunk + second chunk.

**Comment by kendonB** [comment]
Interesting - perhaps this is system specific?

**Comment by ronblum** [comment]
#7464 is a duplicate of this, but it shows that there's a little more: text that should come after the first chunk is displayed between the first and second duplicate. https://github.com/rstudio/rstudio/issues/7464#issuecomment-665747875
