### ISSUE TITLE
Add overlay methods to handle session CRAN repo defaults

### ISSUE THREAD

**Issue by skyeturriff** [rstudio/rstudio#15403]
OS tracking issue for verification of https://github.com/rstudio/rstudio-pro/issues/5066 on Desktop, Desktop Pro, and open-source Server.

https://github.com/rstudio/rstudio/pull/15364 added overlay methods to allow Pro code to handle session CRAN repo default settings a bit differently.

Session CRAN repo default settings should be unchanged for Desktop, Desktop Pro, and open-source Server (i.e. they should continue to default to `https://cran.rstudio.com/`).

Will need to wait for an OS build that has https://github.com/rstudio/rstudio-pro/pull/6973, and a Pro build that has https://github.com/rstudio/rstudio-pro/pull/6973.

**Comment by gtritchie** [comment]
The associated PR has not been merged yet, moving back to In Progress.

**Comment by gtritchie** [comment]
Verified on 2024.12.0-daily+364 (Mac Desktop).

The default repository is still cran.rstudio.com (via `options("repos")`).

Also, checked that setting a different repo then quitting and restarting works (i.e. the selected repo is still selected).
