### ISSUE TITLE
Issue with editor not updating until file is saved

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15412]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.11.0.345
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.4.1 (2024-06-14 ucrt)

### Steps to reproduce the problem

1. Have this file.

```r



# rstudio/rstudio#10100



```

![image](https://github.com/user-attachments/assets/2f495939-c1db-489f-9975-fd3650356798)

2. Save it

2. Add a new line before 

![image](https://github.com/user-attachments/assets/09d9a916-3fe9-4e81-83c6-b45035c2b996)

### Describe the problem in detail

The link bar is no longer at the correct place. The editor doesn't place the link bar in the correct place until you save the file. This is also a problem with the spell checker.

### Describe the behavior you expected

I would expect the editor to take less time before reacting to this change. It seems that only saving the file fixes the issue. However, it can be distracting to have to save the file often.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment]
Here is another situation where I attempt to add a news bullet, and everything shifts

![image](https://github.com/user-attachments/assets/f9c766f6-9094-4b78-b549-9eaeae94982f)

It resolves itself if I save or scroll the file

**Comment by gtritchie** [comment]
So far I've been unable to repro this on Windows or Mac. I'm trying the most recent daily: 2024.12.0+368.

**Comment by gtritchie** [comment]
Also unable to repro with the version this was reported against: 2024.11.0-daily+345.

In case it matters, what theme are you using, and what are your save settings? I'm using the defaults in my testing:

![save-settings](https://github.com/user-attachments/assets/686c1fbf-8624-40df-952e-3927a39f3029)

**Comment by olivroy** [comment]
Hi! I also can't reproduce on mac. I set the same preferences as you but the issue still persists for me on Windows. I checked in an earlier version and instead of having markup not being in the wrong place, it just disappears till I save, and then reappears.

I checked with the latest daily (2024.12.0+375).

I'll see if I can figure what's causing this issue and will report back..

**Comment by ronblum** [comment]
Triage note: I'm unable to reproduce this in RStudio Desktop 2024.12.0+456 on Windows 11.

**Comment by ronblum** [comment]
@olivroy Oh good to hear! I made the note to discuss in triage what to look at next, but I guess there's no need anymore. :)
