### ISSUE TITLE
Blank IDE build-in browser when trying to authenticate Connect on Windows

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#1541]
Windows 10
1.1.379

Blank IDE build-in browser when trying to authenticate Connect on Windows. Same issue as this connect bug but looks to be on the IDE side.
https://github.com/rstudio/connect/issues/1759

1. Tools -> Global Options -> Publishing
2. Select Connect
3. Select RStudio Connect
4. Type in url and select Next
5. Observe blank IDE browser window
![image](https://user-images.githubusercontent.com/15237845/31137792-e2babbf2-a831-11e7-8824-bc957e391b83.png)

**Comment by jmcphers** [comment]
I suspect that the problem here is that the QtWebKit browser is using an out-of-date list of root CAs. @kevinushey is going to be working on the QtWebKit update in 1.2 which might solve this problem for us.

**Comment by jmcphers** [comment]
Note that this should be resolved when we switch to the system browser; see https://github.com/rstudio/rstudio/issues/3035.

**Comment by jmcphers** [comment]
Resolved with the changes in #3040; we no longer use a built-in browser for this.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
