### ISSUE TITLE
RStudio freezes for a long time when using dollar sign operator on large data frames

### ISSUE THREAD

**Issue by atakanekiz** [rstudio/rstudio#15422]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2024.9.0.375
    OS Version      : Windows 11 x64 Enterprise build 22631.4317
    R Version       : R version 4.4.0 (2024-04-24 ucrt)
    Machine        :  Lenovo Laptop Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.10 GHz

### Steps to reproduce the problem

- Import/generate large data frames
- Use dollar sign `$` to access one of the columns (takes very long and session freezes)
- Reproducible example below

```
rows <- 50
cols <- 300
n <- rows * cols

df <- as.data.frame(
  matrix(1:n, nrow = rows)
  )

# # Takes ~0.5 sec to suggest names
# df$V1



rows <- 500
cols <- 30000
n <- rows * cols

df <- as.data.frame(
  matrix(1:n, nrow = rows)
)

# # Takes ~59 secs to suggest names and unfreeze
# df$V1
```

### Describe the problem in detail,

When dealing with large data frames, the dollar sign `$` operator takes very long to suggest names causing R/RStudio to freeze

### Describe the behavior you expected

Variable name suggestion and autocomplete are nice features, but when using large data frame, they seem to create a bottleneck for interacting with the data. I don't remember this happening previously (older versions of R and RStudio). I am not sure whether it is specific to my computer but I suspect this behavior might be related to #14784, #12964, #14672. Maybe for large data sets autocomplete/name suggestion may be disabled or at least they start working after typing a few characters to populate variable names based on a string match. Thanks for the insights in advance!

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by atakanekiz** [comment]
@ronblum I tried the daily and it seems to resolve the problem. There is still a noticeable but insignificant lag with larger data frames, but it works now. Thanks!

Atakan

**Comment by kevinushey** [comment]
Great news, thanks for testing and reporting back!
