### ISSUE TITLE
Auto-start Python when sending to terminal

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1544]
Currently if you send Python code from the editor to the terminal, you are responsible for starting up a Python REPL beforehand. Be nice to have an option to start a Python session automatically.

**Comment by jmcphers** [comment]
I think @kevinushey is going to look at something like this in 1.2 as part of some Python improvements.

**Comment by gtritchie** [comment]
Closing, see https://rstudio.github.io/reticulate/ for using reticulate for python/R integration.

**Comment by tmcduff** [comment]
Version: Version 1.3.842
