### ISSUE TITLE
[feature request] show column type in data viewer

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#15466]
This is an old [issue](https://github.com/rstudio/rstudio/issues/4716) requested as early as Apr 26, 2019, but was unfortunately closed in 2021. After that, so many people asked for it.

It will be very helpful to show the column type in RStudio data viewer.

Sometimes it's not obvious. For example it's common to have a column of numbers actually are characters. I just spend some extra time because I didn't realize the columns are actually characters, not numbers.

**Comment by gtritchie** [comment]
We have reopened the old issue and will be looking at it in the next release.

**Comment by Sibojang9** [comment]
I do not see any changes in Rstudio version 2024.12.1+563
