### ISSUE TITLE
Triggering suggestions in RStudio while in debug mode changes debug environment

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#1548]
There's an annoying behavior that I think is related to RStudio, not R itself.

If I enter debug mode with `browser()` inside a user defined function and then trigger the suggestion system of RStudio on a namespaced variables (eg. pressing `$` while writing `dplyr::band_instruments$`), the environment get switched (eg from `Browse[1]>` to `Browse[3]>`). 

Since the environment is changed, I'm not able to reach the variables in my function anymore so I have to start over with the debugging.

Furthermore it's hard to leave the debug mode too; it's not immediate like during normal debugging, but it takes few tentatives, eventually exiting with an error.

Here's an example:

    #User dummy function to debug
    b <- function() {
         a = 'Hello'
         browser()
         print(a)
    }

    #Let's call the function and enter in debug mode
    > b()
    Called from: b()

    #Only "a" is in the environment
    Browse[1]> ls()
    [1] "a"
    
    #The "bug" is triggered when pressing the $, which causes RStudio to show suggestions
    Browse[1]>dplyr::band_instruments$
    
    debugging in: dplyr::band_instruments
    debug: {
        pkg <- as.character(substitute(pkg))
        name <- as.character(substitute(name))
        getExportedValue(pkg, name)
    }
    Browse[3]>
    #ls() shows that the environment has changed
    Browse[3]> ls()
    [1] "name" "pkg"
    #Trying to exit hangs R
    Browse[3]> Q
    #Pressing the stop button on RStudio once doesn't exit the debugging mode but make it print:
    Error: target context is not on the stack

    #You need to press stop few times to make it exit debug mode

If I use plain R I don't have this problem. Any solution? Is quite problematic during debugging.
Sorry if my terminology wasn't correct.

**Comment by dfalty** [comment]
What platform are you on and what version of RStudio are you using? I can't reproduce this in my environments. Thanks for the info!

**Comment by bakaburg1** [comment]
Version 1.0.143 on Mac OS X 10.12.6.

I think it can be due also to some changes I made in the error reporting maybe? How can I extract informations on that matter?

Thanks for the support!

**Comment by kevinushey** [comment]
I suspect what you're seeing would be caused by an attempt to debug an R function that RStudio itself is calling during a debug session. You can get into a weird state wherein RStudio begins to recursively debug itself.

Were you debugging any other R functions during that session?

**Comment by bakaburg1** [comment]
I debugged many custom function during the session, I was actually working on a project; but I thought that previous debugging in the same session are encapsulated.
I actually tried on a fresh new project and, at least with the dplyr example, I wasn't able to trigger the problem.

This is strange, I experienced the problem many times in the couple of years, but indeed I always run projects with many custom functions and I use browser() extensively with them.

So is it a sort of caching problem?

**Comment by jmcphers** [comment]
Is there any chance you used the debug "step into" (s) command? That command works by setting a global flag that causes the next function run to be debugged, and in some cases can catch the wrong function.

**Comment by bakaburg1** [comment]
I use the "step into" command when I am in debug mode and I do an error in the console which create a new nested debug session. Using s I go back to the original debug environment (I hope it's clear what I mean).

**Comment by bakaburg1** [comment]
Hello, is there news on this? It's quite bothersome. I'm lately using R on a fresh RStudio installation on a Windows machine and I'm not experiencing the problem. I don't know whether because it's fresh or because RStudio is implemented differently on Windows.

**Comment by kevinushey** [comment]
Would you be able to refine your example with extra details, so that we can reproduce it more easily? We were not able to reproduce the problem initially, so a more complete set of instructions will help us to understand the problem better.

**Comment by bakaburg1** [comment]
Do you have suggestions? Actually I have no idea how to reproduce it consistently. I just know that vocking hints while in browser trigger this... As I told before, I wasn't even able to reproduce it on a fresh windows machine. So could it be something stored somewhere by RStudio? I'll try to make a video of it happening.

**Comment by bakaburg1** [comment]
Ok, that was easier than expected. Sorry for the mouse being in the middle.
I used %D>% from the pipe library to get into browser between dplyr calls. Then I started writing a mapvalue (from plyr, but I actually overwrote that function, so it's in GlobalEnv). And the browser shift happened. 

[Registrazione schermo 2019-10-21 alle 21.22.19.mov.zip](https://github.com/rstudio/rstudio/files/3752544/Registrazione.schermo.2019-10-21.alle.21.22.19.mov.zip)

**Comment by ronblum** [comment]
@bakaburg1 Thank you for the information! Are you using the latest RStudio Desktop release, 1.2.5033? In addition, are you using more recent versions of MacOS and R?

Also, thank you for attaching the movie—it's very useful. Especially with some popcorn and a soda. ;)

**Comment by bakaburg1** [comment]
Hi! The problem spanned multiple versions or R, RStudio and Mac. I’ll check if my version of RStudio is up to date. 
Anyway, after a while the problem started to appear also on the not fresh anymore windows machine. A caching problem?
For repro, I think you could try but entering browsing, trigger errors and then exit using s many times, following the hint from @jmcphers. Maybe after a while the suggestions system will start triggering the bug. Very strange I’m the only one experiencing it though...

**Comment by bakaburg1** [comment]
News on this?

I can ass another piece of information.

Sending the Q command while the problem appears sometimes solves it momentarily, switching to an intermediate browsing level, but just until the next triggering. For example:
- I enter debug mode (browser level 1);
- I write some command and while I'm proposed suggestions (usually for function arguments) the problem triggers and I'm moved to browser level 3, in which I cannot access anymore the variables of the previous level,
- If I use the command Q I'm moved to browser level 2, in which I can access the variables from level 1.
- But also in level 2 I can trigger the problem anytime and sometimes Q doesn't solve it anymore but kicks me out of debug mode altogether (probably I reach the end of the block from which I called browser())

**Comment by bakaburg1** [comment]
Hello, any news on this? it's quite destructive while debugging...

**Comment by kevinushey** [comment]
As far as I can tell, we're still waiting for a reproducible example.

**Comment by bakaburg1** [comment]
I am not able to reproduce it consistently. I mean it happens consistently only once I use RStudio on a computer for a while. I'll see if something else comes to my mind. 
I hoped that the infos above would ring some bell for you since you know the code base. 

I can't understand how am I the only one experiencing this. 

BTW the "qa repro" label was added, what does qa stand for?

Thanks
