### ISSUE TITLE
Add a search bar to the connections tab

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#1549]
Some data sources (like Salesforce) have a very long list of tables. Users can navigate long lists of tables by clicking on "Show more" at the bottom. It would also be helpful if users could search for the table they wanted via a search box near the top of the connections tab.
<img width="577" alt="screen shot 2017-10-04 at 2 09 08 pm" src="https://user-images.githubusercontent.com/7519295/31193976-a645dfb6-a913-11e7-9e3a-d67dedf05fb0.png">

**Comment by javierluraschi** [comment]
+1. Feature requested for `sparklyr`: https://github.com/rstudio/sparklyr/issues/266

**Comment by jimhester** [comment]
This was requested **odbc** as well https://github.com/rstats-db/odbc/issues/104
