### ISSUE TITLE
Debugger highlights incorrect lines in nested functions

### ISSUE THREAD

**Issue by gcpoole** [rstudio/rstudio#15498]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.09.1 Build 394
    OS Version      : Linux Mint 20.3 Una
    R Version       :  R version 4.4.2 (2024-10-31) -- "Pile of Leaves"

### Steps to reproduce the problem

1) Create a new package:
    **New Project --> New Directory --> R Package** 
    leave "create git repo" checked and save in a folder called "testDebug."  (Not sure if git repo is necessary to reproduce example...)
2) Replace the default code in hello.R with the following:

```
# A comment
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line
tryHello <- function() {

  hello <- function() {
    test <- 1+1
    print("Hello, world!")
  }

  hello()
}
```
3) set a breakpoint on the line `print("Hello, world")`  (breakpoint marker should be hollow)
4) Build the package with `<crtl>+<shift>+B` key sequence. (breakpoint marker should turn solid)
5) In the console, type `tryHello()` and press enter.  Yellow highlight stops on `hello()` line.
![Image](https://github.com/user-attachments/assets/51820cc9-bfaf-468c-bbec-668705c1fae0)

Note in the environment that test has already executed, showing that the breakpoint actually stopped in the right place.  The problem is instead with the highlight.

6) Type anything in the console that will cause an error, like "xxxxxxxx" and press enter.  Yellow highlight will jump to comments. Note the width of the highlight is the same as `test <- 1 + 1` (more on that below)
![Image](https://github.com/user-attachments/assets/ff1fd43a-0f93-48ec-b197-27a0aa8deed7)

### Describe the problem in detail

About 6 months to a year ago, I stated to experience unreliable debugging behavior when building packages in R Studio.  For instance:

1) I would set a breakpoint and the breakpoint is immediately removed upon rebuilding the package.
2) Breakpoints are ignored
3) Breakpoints are respected, but the yellow highlight showing the current line doesn't appear.
4) Yellow highlight appears in wrong location (e.g., in comments at the top of a source file).  

These behaviors always seem to happen on complex packages and I was never able to create a minimal reproducible example.  Finally found this one that demonstrates behavior #4. In this case, the behavior is clearly related to having a nested function.  If you pull the `hello()` function outside of the `tryHello()` function, like this:
```
# A comment
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line
# Another comment line

tryHello <- function() {
  hello()
}

hello <- function() {
    test <- 1+1
    print("Hello, world!")
}
```
debugging works as expected.  (Highlight will stop on `print("Hello, world!") and will not move if code that causes an error is entered during debugging.)

Interestingly, if you remove all comments and blank lines from the code like this:
```
tryHello <- function() {
  hello <- function() {
      test <- 1+1
      print("Hello, world!")
  }
  hello()
}
```
the highlight jumps perfectly to `test <- 1+1` after entering an error-causing command in debug mode.  
![Image](https://github.com/user-attachments/assets/88812bee-8b86-4f49-8aea-fb0cf9c91af9)

Of course, this is not where the cursor actually is in the code.  Again, note that, in the environment, `test` has already been calculated.  If you press the "Next" button when the cursor is on `test <- 1 + 1`, instead of moving on to `print("Hello, world!")`, the function completes.

### Describe the behavior you expected

I would expect the highlight to stop at the breakpoint, rather than on the call to the function containing the breakpoint.  After typing code that causes an error into the console in debug mode, I would expect the yellow highlight to stay put, and certainly not to jump to a comment!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I was able to repro in 2024.09.1 (thanks for the excellent repro steps!).

However, it is working correctly for me in the upcoming 2024.12 release, likely due to the fix for https://github.com/rstudio/rstudio/issues/15072.

I'm closing this as a duplicate. If you want to confirm the fix, you can try a daily build from https://dailies.rstudio.com/. Note we're still doing final testing, but the latest builds are essentially identical to what will be released (unless we find any nasty last-minute bugs).
