### ISSUE TITLE
Enforce use of HTTPS throughout all pages & files

### ISSUE THREAD

**Issue by yungtravla** [rstudio/rstudio#1551]
Hi

Your website can be a victim of MiTM attacks when users' traffic on a public/compromised network gets intercepted and proxied.

I recommend that you use the **https** scheme in all references to your website.

For example: https://github.com/rstudio/rstudio
The introductory line currently has http scheme.

Peace!

**Comment by jmcphers** [comment]
Sorry, I think we need some more context. To which introductory line are you referring?

**Comment by yungtravla** [comment]
![screenshot_2017-10-06-22-56-04](https://user-images.githubusercontent.com/29265684/31279280-dbb2c55e-aaeb-11e7-97f9-777288e4384a.jpg)

**Comment by jjallaire** [comment]
Thanks, now fixed
