### ISSUE TITLE
RStudio crashes after update to Rdevel (R 4.5) - MacBookPro with M1, both Intel and Arm versions affected

### ISSUE THREAD

**Issue by federicomarini** [rstudio/rstudio#15523]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.09.1+394
    OS Version      : MacOS 14.7
    R Version       : R devel (builds taken from https://mac.r-project.org/)

### Steps to reproduce the problem

After updating R to the devel version from https://mac.r-project.org/ (tried both, intel and Arm64 versions), running R within RStudio crashes all the time - the same call runs with no issue in the terminal based R

<img width="1726" alt="Image" src="https://github.com/user-attachments/assets/36819cec-0842-4af4-b613-f79b950d4d19" />

### Describe the problem in detail

I just updated my previous version of R (4.4.2, release, Intel version), running on my MBP with M1 processor.
R devel version is taken from https://mac.r-project.org/, to enable me developing in the current Bioconductor devel cycle.
Calling any function in R while running within RStudio crashes the session (with the bomb sign), BUT the same command (like, any command probably) does not give any issue in R run from the terminal.
I tried with a slightly older version of RStudio too, but the problem is still there.

<img width="1016" alt="Image" src="https://github.com/user-attachments/assets/c6b2a7bb-cc6b-4994-9679-50aca1adc0a7" />

I did try to include the diagnostic report but that also fails if called within RStudio

### Describe the behavior you expected

I would simply expect R to normally run within RStudio, "as usual" - it works perfectly fine if I restore back (with RSwitch) the release version I was using earlier on. But to have Bioc3.21 I do need the Rdevel...

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by federicomarini** [comment]
I managed to run the diagnostics via the call on the Terminal, `/Applications/RStudio.app/Contents/MacOS/RStudio --run-diagnostics`

Attached to this is the [diagnostics-report.txt](https://github.com/user-attachments/files/18153753/diagnostics-report.txt) file.

Thank you in advance for the support on this!

Federico

**Comment by kevinushey** [comment]
Thanks for the bug report. I was able to reproduce the issue with RStudio 2024.09.1, but everything seems fine with the latest [daily builds](https://dailies.rstudio.com) of RStudio. (Tested with 2024.12.0 Build 465)

```r
> sessionInfo()
R Under development (unstable) (2024-12-13 r87441)
Platform: aarch64-apple-darwin20
Running under: macOS Sequoia 15.1.1
```

**Comment by federicomarini** [comment]
Well thank you a lot for the timely reply.
I'm gonna give a spin to the daily then!

About the reason: I tried a bit to troubleshoot that but could not really find too much out of that.
If you want to share some hints on the whole process, I am eager to learn a bit more!
Federico

**Comment by federicomarini** [comment]
Quick confirmation @kevinushey that the daily (build 470) works in my hands too (for both versions, so far all good in the hood)!

**Comment by federicomarini** [comment]
Got it!
Gave me quite a bit of headaches over the past weeks as I always thought it was a "general issue with R devel"...
I went down the way of simple things by using the terminal directly and spotted out it all was working as usual, which motivated me to file this report. 
Glad it could be figured out quickly, and I hope it helps more in the coming weeks!
F
