### ISSUE TITLE
Don't inherit project options from home directory

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1552]
It's possible to open the home directory as a project, thereby placing a `~.Rproj` file in the home directory. The inheritance of project options implies that, if this has been done and the user is not working within a project, these project options will be inherited regardless by e.g. untitled files open in the IDE.

We should either:

1. Disallow opening the home directory as an RStudio project, or
2. Explicitly avoid inheriting project options from this file.

**Comment by kevinushey** [comment]
@ronblum also suggested that we might want to explicitly unset the default value in the `New Project -> From Existing Directory` UI, to discourage users potentially opening the home directory as a project (which is currently the default).

**Comment by jmcphers** [comment]
Might be a candidate for backporting as IIRC the "open directory as a project" is new in 1.1.

**Comment by ronblum** [comment]
I'm seeing somewhat different behavior in v1.1.393 (both desktop and server). Projects aren't inheriting from the home directory. However, project options are taking effect immediately. The .Rproj is updated, but the changes don't take effect until the project is closed and reopened.

**Comment by kevinushey** [comment]
@ronblum Thanks for catching that! I've reproduced this and this is indeed a regression; I'll see if I can fix this up.

**Comment by kevinushey** [comment]
Moving this one out of v1.1-patch as it's not a particularly prevalent nor disarming issue.

**Comment by gtritchie** [comment]
On macOS Catalina, get a bunch of prompts like this if you open home folder as a project, (contacts, photos, desktop, etc):

<img width="422" alt="2019-12-16_16-10-08" src="https://user-images.githubusercontent.com/10569626/70954408-f4b91000-2021-11ea-8e71-63c7e5d07faa.png">
