### ISSUE TITLE
Help styling broken in latest release

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#15531]
### System details

 RStudio 2024.12.0+467 "Kousa Dogwood" Release (cf37a3e5488c937207f992226d255be71f5e3f41, 2024-12-11) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.12.0+467 Chrome/126.0.6478.234 Electron/31.7.6 Safari/537.36, Quarto 1.6.39 (/Applications/quarto/bin/quarto)

The left column padding now has a hard jump as the width of the window changes, and is generally a poor experience. This is new behavior introduced with just the last release. 

https://github.com/user-attachments/assets/2c23b612-7922-4e9c-84e7-bfbf149dd383

**Comment by gtritchie** [comment]
Thanks for the bug report. I have confirmed this issue, and it started in build 2024.11.0-269, and was caused by https://github.com/rstudio/rstudio/pull/15274.

**Comment by kevinushey** [comment]
As a workaround, use `options(help.htmltoc = FALSE)` in your R session.

**Comment by ronblum** [comment]
Verified the contents follow the display width instead of jumping to center, using RStudio Desktop 2024.12.1+521 on Windows 11.
