### ISSUE TITLE
Quarto yaml and code chunk option autocompletion and suggestion not working

### ISSUE THREAD

**Issue by inigourrestarazu** [rstudio/rstudio#15555]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2024.12.0+467
    OS Version  :  darwin20
    R Version  :  R version 4.4.2
    Quarto Version: 1.6.39

### Steps to reproduce the problem
Press tab in the YAML of a .qmd file or after a hash pipe in code chunks.

### Describe the problem in detail

I get the same problem reported here: https://github.com/rstudio/rstudio/issues/13804

Since the last update, I don't get yaml autosuggestions and autocompletions any longer in .qmd files. I get syntax highlighting, but I type and get no suggestions, and pressing tab does nothing at all, neither it inserts an indent. Neither are true/false suggestions displayed.

The documents I tried it with are saved and named, and I even tried with documents I know for sure I used this behavior with.

The documents render no problem, so it's not a yaml problem either.

I uninstalled, cleaned everything and installed all three: R, RStudio and Quarto

I believe it's an RStudio issue, because it works in Positron.

### Describe the behavior you expected
Suggestions of the different yaml fields or code chunk options after the '#|' pipe.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by bwelman** [comment]
I have the same problems on both Windows 10 and Windows 11 with Rstudio version: 2024.12.0+467 and Quarto: 1.6.39.
Uninstalling and reinstalling Rstudio and Quarto didn't solve the problems. With only uninstalling Quarto the problems are gone.
So I tried other versions of Quarto. With Quarto 1.6.38 the same problems. But with Quarto 1.6.37 and Quarto 1.7.5 no problems.

**Comment by inigourrestarazu** [comment]
This is great to know! I guess 1.7.5 is not the latest open release, but I will download 1.6.37 :)

**Comment by inigourrestarazu** [comment]
Well, I tried with the prelease of 1.7.5 and you're right! It works again :)

Thanks

**Comment by jeffkimbrel** [comment]
Updating Quarto to 1.7.5 fixes this for me as well. 

On MacOS, quarto v1.6.39 and Studio 2024.12.0+467, not only did the autocompletions not work, but chunk options I entered were straight up ignored when rendering, like `#| eval: false`. But, all works with 1.7.5. 

Thanks!

**Comment by inigourrestarazu** [comment]
I'm closing the issue because it seems to be fixed in 1.7.5.

**Comment by inigourrestarazu** [comment]
Yup! I recommend you download and install the 1.7.5 pre-lease ;)
