### ISSUE TITLE
Add support for custom log directory in RStudio Server

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1560]
From an open source user:

>According to the documentation, the server monitor logs are located at /var/lib/rstudio-server/monitor/log, but I'm unable to find them there. There is not monitor folder under /var/lib/rstudio-server folder, just body, conf and proxy subfolders, and there is not rstudio-server.log in the system. Maybe I missed something in the installation?

> I would like to try setting the log folder manually, but I haven't found any way to set this 

And another:

> By default, RStudio Logs everything to syslog under /var/log/messages. We would like to use a different log file, i.e. /var/log/rstudio to have a better overview what is application specific and what is real syslog.

>  I also found the config files under /etc/rstudio. But they are empty and do not have any reference how I could configure different log files.

And another:

> Separate log file for RStudio. "Not a big fan of non-system applications dumping logs in /var/log/messages"

Requests in the forum, too:

https://support.rstudio.com/hc/en-us/community/posts/115001062208-Location-of-Log-files

And from customers (see ticket 23428)

**Comment by jmcphers** [comment]
Also requested on StackOverflow:

https://stackoverflow.com/questions/40525722/configure-log-directory-for-rstudio-server-1-0-44

**Comment by jmcphers** [comment]
This is now implemented in RStudio 1.3. See here for example pre-release docs:

https://docs.rstudio.com/ide/server-pro/1.3.465-1/server-management.html#logging

**Comment by cderv** [comment]
Awesome. Thank you for the update !

**Comment by tblazina** [comment]
This is not implemented in open source RStudio, correct? We are running it in docker containers and are finding it troublesome to set up logging

**Comment by jmcphers** [comment]
Yes, it's implemented in the open source version, but not in the current stable release (1.2). You can try it out in 1.3 if you like:

https://dailies.rstudio.com/

**Comment by tblazina** [comment]
@jmcphers, that's great I'll check it out! thanks for the quick response.
