### ISSUE TITLE
Accessing http://hostname:8787/js/ results in 500 server error

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1561]
Title is the repro; accessing this URL after logging into RStudio Server results in HTTP 500 (Internal Server Error) with the body `Input/Output Error`. 

Some automated security scanning tools consider it a vulnerability if you can force a server to emit a 500. In this case, it seems like we should emit either 404 (nothing at this URL, which is true), or a 403 (forbidden, you can't list the JS files -- also true).

**Comment by dfalty** [comment]
Verified fixed 1.2.150-1
