### ISSUE TITLE
GWT symbols are obfuscated in devmode

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1562]
![screen shot 2017-10-06 at 11 17 16 am](https://user-images.githubusercontent.com/1976582/31292364-f964ef3c-aa87-11e7-9189-d31c5455852f.png)

Possibly a regression from the upgrade to GWT 2.8?

**Comment by kevinushey** [comment]
Thanks!

**Comment by jmcphers** [comment]
No problem, this was indeed a regression from the GWT upgrade. I've no idea why pretty code is no longer the default in dev mode!
