### ISSUE TITLE
consider adding 'New File' button to Files pane

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1564]
For quickly creating a file in a directory.

**Comment by rossholmberg** [comment]
Came here with this feature request, glad to find it here already. I think this would ideally be a drop-down similar to the File > `New File` menu, and would focus the file name to set that on creation.

**Comment by jmcphers** [comment]
Another vote in #7344.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 2021.12.0-daily+80
    OS Version      : ubuntu20
    R Version       : 4.0.3

Verified that the New Blank File button exists in the Files pane. All files listed under the new blank files can be created successfully. Verified this option cannot create two of the same file type with the exact same name. Verified this option cannot create files in directories with restricted permissions.

### Notes
As mentioned in the PR for this feature, R Documentation, R Presentation, and R Notebook are not file types expected to be created by the New Blank File button. If they do need to be added in the future, it would require additional overhead work.
