### ISSUE TITLE
Can't use toolbar icons in rightmost ~20px

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1565]
None of the toolbar icons on the right edge of RStudio are currently accepting clicks; for instance, the Refresh button on the Environment pane doesn't work, and neither does the same on the Viewer pane. 

Appears to be a result of https://github.com/rstudio/rstudio/commit/7f0eb89aa2354b28e11ef836a8dfa55cfb6f5c85; @javierluraschi can you take a look?

**Comment by dfalty** [comment]
Verified 1.2.158.
