### ISSUE TITLE
<Enter> commits to editor when Go To Functions opens new tab in RStudio Server

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#1568]
When I use `Go To Functions` in RStudio Server, typing a function name and hitting `Enter` will first create a new line in the editor and then open a new tab and go to the function I want if the source file of that function is not open yet. The same does not happen in RStudio Desktop.

My versions:

RStudio Server 1.1.375 (on Ubuntu)
RStudio Desktop 1.1.383 (on macOS)

Glad to notice that issues are enabled here. It is much easier to file and track issues for great RStudio now!

**Comment by dfalty** [comment]
Thanks for the report!

It looks like I can reproduce this but only at ~30% repro rate and only in Firefox. I can't reproduce this in Chrome for some reason.
1.1.383 (OS and RSP)
Ubuntu 16.04.3
Firefox 45.0b10

Steps:
1. Create a test function in an R script and source
a <- function(){}
2. Close the file and open a different file
3. Use the keyboard shortcut for "Go to file/function" Ctrl+. (I couldn't repro with the same menu bar item)
4. Type the function 'a' in the box and press enter when it pops up
5. ~30% of the time I will get a new line in the file currently open before opening the file with the function. 

@renkun-ken Does this fit your experience or is it different?

**Comment by renkun-ken** [comment]
@dfalty, thanks for more specific info on this. I'm using Firefox 57b6 and it's 100% repro.

**Comment by renkun-ken** [comment]
This problem is gone in the the latest release preview (v1.1.402).
