### ISSUE TITLE
Docker image for rstudio

### ISSUE THREAD

**Issue by vaibhavsood** [rstudio/rstudio#1570]
Hi,

Want to check if there is a docker image/Dockerfile for rstudio which is officially supported? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official rstudio image to dockerhub? https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by jmcphers** [comment]
No, we don't have one right now. Do the `rocker` images do what you need? They pair various versions of R with RStudio in a single container:

https://hub.docker.com/r/rocker/rstudio/

**Comment by vaibhavsood** [comment]
Thanks for the response!

My primary interest for now is to first understand if it makes sense to have rstudio as a docker official image (steps for doing the same are in the link posted in my previous comment, it also mentions the considerations for making an image official)

If that happens, the image comes under Docker's "official" image program, they then take over the daily builds etc, also it gets published under https://hub.docker.com/explore/ - however the maintainence is to be done by upstream

**Comment by jmcphers** [comment]
There's been no more interest shown in this for the last couple of years, and we don't have the bandwidth to maintain at this time, so closing. We do host Docker base images now for use with RStudio Server Pro:

https://hub.docker.com/u/rstudio
