### ISSUE TITLE
RStudio Server dark theme does not work on dataframe panel without clearing cache after upgrade to 1.1 from 1.0

### ISSUE THREAD

**Issue by likso** [rstudio/rstudio#1573]
Look like the dataframe panel always keep as light theme even when in dark theme mode. It makes the row name and col name unreadable.

Rstudio theme: Modern
Editor theme: Solarized Dark

![image](https://user-images.githubusercontent.com/13925196/31368516-df22523c-adb0-11e7-858e-901668b4a2d8.png)

**Comment by dfalty** [comment]
What platform and version of RStudio are you running?
This looks fine for me on 1.1.383 with Modern/Solarized Dark (Mac OS).
![image](https://user-images.githubusercontent.com/15237845/31384700-a1b9c5d6-ad85-11e7-860e-5779da6c1e1b.png)

**Comment by GSMCD** [comment]
We've been seeing this happening as well:

Version 60.0.3112.90 (Official Build) (64-bit)
Windows 7 x64
RStudio Server 1.1.383 with Redhat 6.6

**Comment by dfalty** [comment]
Thanks for the info!

@javierluraschi do you know what could cause the theme to fail within the data viewer like this? I'm unable to repro locally.

**Comment by javierluraschi** [comment]
@likso @GSMCD could you right-click over one of the cells with incorrect background and select `inspect`?

Then if you could share a screenshot like the one below it would be much appreciated.

Notice that I expanded the `<head>` tag a few lines above from the inspected element and then clicked on `<tr>` to get a view of the CSS styles being applied.

<img width="1440" alt="screen shot 2017-10-11 at 10 45 20 am" src="https://user-images.githubusercontent.com/3478847/31457500-cf1bee4a-ae71-11e7-864f-867b56fcb7a1.png">

**Comment by GSMCD** [comment]
@javierluraschi Hmm. I went to get a screenshot for you there, but I'm unable to reproduce it now! It's odd, as I had a handful of users reporting this.

@likso Are you able to reproduce this?

**Comment by javierluraschi** [comment]
@GSMCD @likso couple question that could help me debug this: Do you both have multiple RStudio windows open? Did you switch to use the dark-theme during or was this reproducing for you from a brand new RStudio window?

**Comment by GSMCD** [comment]
@javierluraschi I've tried a couple more things:

1. Start a new session with default color scheme and move to Solarized Dark, however the table changes color as expected.
2. I also tried with multiple windows open, and it's working as expected.

The only thing I can think of is something has been cached from the older RStudio Server version? As this happened immediately after the upgrade. The users that originally reported the issue to me have now said it's working as expected.

**Comment by likso** [comment]
@javierluraschi  I did not have multiple Rstudio windows opened. It happened straight after my upgrade from 1.0 to 1.1.

**Comment by jmcphers** [comment]
Reported here, too:

https://support.rstudio.com/hc/en-us/community/posts/115007898527-bug-report-View-and-dark-theme

**Comment by jmcphers** [comment]
Backported to 1.1 in 976735a6cbef64b52fdc15c32e971ca949220700.

**Comment by dfalty** [comment]
I can't reproduce this on the 1.1 patch build 1.1.393 so I'll mark this as verified. Let us know if you are able to reproduce.
