### ISSUE TITLE
Multiple sessions do not work: conflict with system Qt 5 libraries on linux

### ISSUE THREAD

**Issue by vh-d** [rstudio/rstudio#1574]
I click on Session -> New Session and nothing happens.

This is the output in the terminal (when running RStudio from a terminal) after clicking "New session":

 

    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5)
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5)
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5)
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5)
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5)
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5)
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5)
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5)                                                            
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Network.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5)                                                                    
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5)                                                                       
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5)                                                                         
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5)                                                             
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Network.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5)                                                                      
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5)                                                                
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5)                                                                  
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5)                                                      
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5)                                                                       
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5)                                                             
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5)                                                                         
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5)                                                                    
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5)                                                                      
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5)                                                          
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5)                                                                       
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5)                                                           
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Widgets.so.5: version `Qt_5_PRIVATE_API' not found (required by /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5)                                                       
    /usr/lib/rstudio/bin/rstudio: /usr/lib/rstudio/bin/libQt5Widgets.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5)

 

So I tried setting:

```
export LD_LIBRARY_PATH="/usr/lib/rstudio/bin"
```

in terminal before starting RStudio and it solves the issue! (But it comes with another issues later, so it is not a real solution)

Edit: I am on RStudio 1.1.374 64-bit Ubuntu 16.04 with Qt 5.9 installed.

**Comment by jmcphers** [comment]
This looks like a bug we fixed in the stable release of RStudio, 1.1.383. Can you try that version and let us know if it fixes the issue for you?

**Comment by vh-d** [comment]
Yep! What a coincidence! Thanks and sorry for opening an out-of-date issue.

**Comment by Vimos** [comment]
I am using rstudio-1.1.423, a newer version, but facing similar issue.
```

➜  Downloads rstudio 
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Sensors.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Sensors.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Sensors.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Positioning.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Positioning.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Positioning.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Network.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Quick.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Quick.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Quick.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Quick.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Quick.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Quick.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Network.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Qml.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Qml.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Qml.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Qml.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5WebChannel.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5WebChannel.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5WebChannel.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Sql.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Sql.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5Sql.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Widgets.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5OpenGL.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Widgets.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5OpenGL.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5OpenGL.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5OpenGL.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5OpenGL.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5OpenGL.so.5)
rstudio: /usr/lib/rstudio/bin/libQt5Core.so.5: version `Qt_5' not found (required by /opt/Qt/5.9.2/gcc_64/lib/libQt5OpenGL.so.5)

```

Here is my default LD_LIBRARY_PATH
```
➜  rstudio-1.1.423 echo ${LD_LIBRARY_PATH}
/usr/local/cuda/lib64::/opt/Qt/5.9.2/gcc_64/lib:/opt/Qt/5.9.2/gcc_64/plugins/platforms

```

The problem can be resolved by
`LD_LIBRARY_PATH= && rstudio`

**Comment by kevinushey** [comment]
The RStudio v1.2 branch will be more resilient against `LD_LIBRARY_PATH`s containing paths to Qt libraries that are incompatible with RStudio. In the meantime, I would recommend unsetting the `LD_LIBRARY_PATH` when launching RStudio as you're doing here, or perhaps scope the `LD_LIBRARY_PATH` setting to the applications that truly require it, rather than setting it globally.

**Comment by rbirkelbach** [comment]
I have the same issue on ubuntu 18.04 and it can be resolved by  `LD_LIBRARY_PATH= && rstudio`
