### ISSUE TITLE
Add Generate R code as index number in Object Viewer 

### ISSUE THREAD

**Issue by NathNx** [rstudio/rstudio#1575]
Generate R code that can be used to access a particular item within object in current Rstudio (1.1.383) is great. Would be very nice if it provides an option to change index name to index number.

Create an object:
`conn <- url("https://api.github.com/repos/hadley/dplyr/commits")`
`content <- readLines(conn, warn = FALSE)`
`close(conn)`
`data <- jsonlite::fromJSON(content, simplifyDataFrame = FALSE)`
`latest <- data[[1]]`
`View(latest)`

Get element address (current):
`latest[["committer"]][["html_url"]]`

Get element address (next update):
`latest[[8]][[6]]`

**Comment by kevinushey** [comment]
Can you provide some motivation for why you want indices rather than names?

**Comment by jmcphers** [comment]
Haven't heard back in a few years so closing.
