### ISSUE TITLE
ODBC do not show in New Connection even after installing odbc package and unixodbc on Mac

### ISSUE THREAD

**Issue by zhiruiwang** [rstudio/rstudio#1576]
I am using MacOs High Sierra, Rstudio 1.1.383, just brew install unixodbc and symlink it successfully. However, no matter which odbc package I install(1.12 on github or 1.13 on CRAN), the ODBC option will not show in the New Connection tab. I wonder whether there is a way to solve it? Thank you!

**Comment by jmcphers** [comment]
What do you mean by "the odbc option will not show"? You won't see anything in the tab until you create a connection with the package.

**Comment by zhiruiwang** [comment]
Sorry, I mean the  pop-up window after you click 'New Connection' button. Only Livy and Spark show up in the options.

**Comment by dfalty** [comment]
Hello Zhirui. There is not a default odbc connection in the New Connection wizard. What will show up there are specific ODBC drivers, ODBC DSNs, or Connections supplied by snippet files. Please see the following for more information and let us know if that answers your question.
http://db.rstudio.com/rstudio/connections#new-connection-interface
