### ISSUE TITLE
Detached plot window does not adjust resolution across multiple screens in RStudio Server

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#1578]
Steps to reproduce:

1. On a two-screen desktop environment with different resolutions, start a new session in RStudio Server. (e.g. a macbook pro with Retina screen and a non-Retina screen)
2. Drag the browser to the non-Retina screen with lower resolution
3. `plot(rnorm(1000))`
4. Detach the plot window and drag it to Retina screen
5. The plot does not adjust its resolution to fit Retina screen

The same problem does not occur in RStudio Desktop. 

I'm using the latest release (v1.1.383).

**Comment by dfalty** [comment]
I'm not able to reproduce this one on 1.1.383 or I'm not understanding the exact steps/expectation. When I drag the plot window from the low res screen to high res, the window is obviously small but I have no problem maximizing the window and the plot is updated. Do you mind giving us a little bit more information on the exact steps and expectation here?

**Comment by renkun-ken** [comment]
Apologies. I find it only reproducible in Firefox (v57b7). I test it with Safari and no such problem.

**Comment by dfalty** [comment]
Hmm, I still can't reproduce it in Firefox. Could you share exactly what you are doing or get a video/gif/screenshot of the issue?

**Comment by jmcphers** [comment]
We haven't heard back in a couple of years so closing this one.
