### ISSUE TITLE
RStudio sometimes creates multiple .Rproj files in same directory

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1581]
From @mine-cetinkaya-rundel:

> When creating a new project from git, if you change the project directory name from the default (which is the repo name), it created an additional Rproj file with that name. I understand why this happens, but I think it would be more natural to check to see if there is an Rproj file in the repo already, and if so, not create another (unless I’m missing a detail, in which case please let me know, I’m curious). Thoughts on this?

This sounds like a bug -- normally, we attempt to find a `.Rproj` file in the directory to be created, and then only create a new file if no existing one was found.

Here's a repro; opening "aaa" from github, but putting it in "a8b" folder. Ends up creating a8b.Rproj and opening it.
![2018-01-26_10-19-20](https://user-images.githubusercontent.com/10569626/35454403-c1263772-0282-11e8-9e93-4471cb4c67c4.png)
![2018-01-26_10-19-47](https://user-images.githubusercontent.com/10569626/35454420-d49e051e-0282-11e8-89e1-875b0122bf28.png)
![2018-01-26_10-21-30](https://user-images.githubusercontent.com/10569626/35454424-d71b3122-0282-11e8-8c2c-c9e65c953d1a.png)

**Comment by hadley** [comment]
This is causing problems when projects are cloned from rstudio.cloud.

**Comment by gtritchie** [comment]
Possible overlap with this Pro issue: https://github.com/rstudio/rstudio-pro/issues/280

**Comment by dfalty** [comment]
Verified fixed 1.2.302-3.
