### ISSUE TITLE
RStudio Modern Theme Help Pane "Find in Topic" highlight colour

### ISSUE THREAD

**Issue by dchiu911** [rstudio/rstudio#1582]
I find it hard to visually locate the next found word with the Modern Theme in the help pane. Perhaps there are other colours that can be used for highlighting? For example, I cannot immediately spot the "mile" below:
![image](https://user-images.githubusercontent.com/8665632/31454924-ea8dd3e2-ae6b-11e7-9b24-71b191ee4153.png)
I am using macOS High Sierra, RStudio 1.1.383

**Comment by dchiu911** [comment]
The contrast is more obvious in Classic:
![image](https://user-images.githubusercontent.com/8665632/31455465-7560d21c-ae6c-11e7-9752-168a5a60cf91.png)

**Comment by dfalty** [comment]
Verified fixed 1.2.150. There is a better contrast now.

**Comment by kevinushey** [comment]
I think this has since been resolved.

<img width="367" height="120" alt="Image" src="https://github.com/user-attachments/assets/0e45871a-a4eb-45e0-b221-956bf2ee24d1" />
