### ISSUE TITLE
new publishing account encounters timeouts against other servers

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#1583]
I have a number of test Connect servers configured in the IDE as "Publishing Accounts".

![screen shot 2017-10-11 at 1 56 49 pm](https://user-images.githubusercontent.com/362187/31457837-0f05d768-ae8c-11e7-87b2-692dbe3b987a.png)

Both the *.16 and *.19 host are down (Vagrant instances completely destroyed)

While adding the *.29 host (account john), I started experiencing timeouts when during the final stages of account-adding (the browser window had already closed after the token was accepted).

![screen shot 2017-10-11 at 1 39 35 pm](https://user-images.githubusercontent.com/362187/31457896-3d1ae404-ae8c-11e7-9169-0638a7ef7669.png)

The console showed timeouts against a DIFFERENT host:
![screen shot 2017-10-11 at 1 40 17 pm](https://user-images.githubusercontent.com/362187/31457907-463281f0-ae8c-11e7-8933-540fd06cbdf4.png)

The timeouts start showing up AFTER clicking the final "Connect Account" button (while the "Adding account" spinner displays).

Looks like there were three failed attempts before a final connection to *.29 happened.

```
*   Trying 192.168.42.19...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.42.19 port 3939 failed: Operation timed out
* Failed to connect to 192.168.42.19 port 3939: Operation timed out
* Closing connection 0
Timing stopped at: 0.021 0.018 75.316 
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to 192.168.42.19 port 3939: Operation timed out
*   Trying 192.168.42.19...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.42.19 port 3939 failed: Operation timed out
* Failed to connect to 192.168.42.19 port 3939: Operation timed out
* Closing connection 0
Timing stopped at: 0.02 0.017 75.36 
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to 192.168.42.19 port 3939: Operation timed out
*   Trying 192.168.42.29...
* TCP_NODELAY set
* Connected to 192.168.42.29 (192.168.42.29) port 3939 (#0)
> GET /__api__/users/current HTTP/1.1
..... not including successful request(s?) against *.29
```

Was using:

```
options(rsconnect.http.verbose = TRUE, rsconnect.http.trace = TRUE)
```

**Comment by aronatkins** [comment]
The account against *.29 was correctly created and can be used to publish.

**Comment by jmcphers** [comment]
The most baffling part about this is that the "Adding account..." indicator shows while we're doing an operation that doesn't contact any servers *at all*. It's supposed to just call `rsconnect:::registerUserToken`, which acts locally. 

A couple questions for anyone who can repro this:

1) Can you attach a request log? (available from Help -> Diagnostics; press E to export it and then copy/paste)

2) Do you ever see this in a fresh IDE instance, or does it start showing up after you've done some other actions? If the latter, any idea what those actions are?

**Comment by aronatkins** [comment]
@jmcphers and I chatted offline; the request log did not have any useful information. I have also removed my configuration against the dead servers to avoid these timeouts and am not currently able to reproduce the timeouts.

I'll update again if I get back to this broken state.

**Comment by dfalty** [comment]
Closing this out. Feel free to reopen if you run into this again.
