### ISSUE TITLE
Refresh icon overlaps with plot title text

### ISSUE THREAD

**Issue by dethmasque** [rstudio/rstudio#1585]
Screen Shot:

![image](https://user-images.githubusercontent.com/32644679/31464003-08f7e354-ae9e-11e7-8d29-5c3bce956180.png)

RStudio version 1.1.383 on OS X Sierra

Steps to Reproduce:

1) Execute `plot(cars)` within the Console in order to generate a plot.
2) Navigate to the Plots tab and select the Publish drop-down.
3) If the plot has not already been published (there are no previous plot titles listed below "Publish Plot") then publish it and select the Publish drop-down again.

Expected Results:

All previously published plots are displayed correctly.

Actual Results:

The refresh icon overlaps the previously published plots' titles.

**Comment by dfalty** [comment]
Verified fixed 1.2.150

**Comment by jmcphers** [comment]
Backported to 1.1 in ac5eab3e7793e1d06db29fa00d63b538d2aa1a1d.
