### ISSUE TITLE
File Open dialog slow on RStudio Desktop for Linux

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1587]
https://support.rstudio.com/hc/en-us/community/posts/115007856187-Dialog-file-slowness-under-Fecora-Core-26-rstudio-1-1-

> Since version 1.1, the file dialog is incredibly slow under my Fedora Core 26. Each time I have to "open" a file, the dialog freezes as soon as I try to type a few character or to change the path. Is this a known issue? How can I help?

https://community.rstudio.com/t/save-as-dialog-very-slow-in-rstudio-preview-on-ubuntu/1669

> When selecting “Save As…” from the “File” menu, the dialog opens immediately but it takes up to seconds until the window is filled with contents. Typing a file name also feels very sluggish. This does not occur in 1.0.153, only in 1.1.379 (and also the previously released preview version). I’m on Ubuntu 17.04.
... 
> I have the same problem here! Sometimes it completely blocks RStudio and I need to reopen

**Comment by DarioS** [comment]
It's the same for Windows 7. The drives also have missing icons.

![drives](https://user-images.githubusercontent.com/631218/31477080-b44afa40-af55-11e7-838f-6c30d8cddcf9.png)

**Comment by ogsj** [comment]
same issue on debian 9.2

**Comment by lepennec** [comment]
This seems to be somehow a Gnome issue as rstudio under KDE with the same computer works flawlessly.

Erwan

Fedora 26 - Gnome 3.24.2

**Comment by ogsj** [comment]
Gtk issue? I run xfce..

**Comment by ronblum** [comment]
Hi, this is Ron, QA engineer at RStudio. I have not been able to reproduce the issue with RStudio Desktop on the following combinations, which include Gnome, Unity, and KDE:

- Ubuntu Server 16.04: Unity 7.4.0
- Ubuntu Desktop 16.04: Gnome 3.20.5
- CentOS 7: Gnome 3.14.7
- openSUSE 42.3 (12.3): KDE 5.8.7

I'm also unable to reproduce on Windows 10 Enterprise (1607) and macOS Sierra 10.12.6.

1. Are these issues all with RStudio Desktop, as opposed to connecting to RStudio Server using a browser?
2. Is RStudio pointing to a local file system or a network drive?

Any additional information would be appreciated. Thank you!

**Comment by ogsj** [comment]
Hi Ron, I'm using Debian 9.2, xfce 4.12. Issue is with Rstudio Desktop for me, pointing to local file system. The only seem to be an issue when I open an existing file, change something, and press "Save As". When creating a New FIle, the "Save As" dialog acts normally.

**Comment by kevinushey** [comment]
Thanks for the extra information @ogsj -- I've now reproduced this on my Ubuntu 17.04 machine. In my case, I had to force the use of `gtk2` by launching RStudio from a terminal with:

    QT_QPA_PLATFORMTHEME=gtk2 rstudio

If I do this, it takes ~5 seconds before the dialog shows up for me.

**Comment by zachokeeffe** [comment]
I've been searching for a solution to this for weeks to no avail. I'm using Debian 9.2 stable and Gnome 3. Is anyone working on this? All dialogue boxes are slow, but Save As and Global Options are particularly bad (takes 10-20 seconds to open, 20 seconds to type something in). Removing ~/.RData, ~/.Rhistory, ~/.Rprofile, and ~/.rstudio-desktop does nothing. I made sure to install all the dependencies (https://github.com/rstudio/rstudio/wiki/Installing-RStudio-Dependencies), reinstalled R and rstudio multiple times, and tried modifying QT_QPA_PLATFORMTHEME.

**Comment by kevinushey** [comment]
Unfortunately, to the best of my knowledge, there isn't a workaround available for this issue with v1.1.383.

We do have a fix available in the daily build of RStudio (the v1.2 branch), at

https://dailies.rstudio.com/

But we hope to push the associated fixes as part of a v1.1 patch release.

**Comment by jmcphers** [comment]
Backported to 1.1 here: deefcd417a4ab64d004d241ebe98718588fcba66

**Comment by kevinushey** [comment]
@bvhest can you please try the preview release of RStudio? https://www.rstudio.com/products/rstudio/download/preview/

**Comment by bvhest** [comment]
confirmed: RStudio Version 1.1.414 Preview from the above link works fine (on Linux Mint 18.2 Cinnamon 64bit)!

**Comment by nmauri** [comment]
I tried with RStudio Version 1.1.414 but I get the same, the file-dialog is no working

**Comment by abelb0rges** [comment]
At home, I'm using Linux Mint 18.2 with Rstudio v1.1.383, and having the same issue. The freezing appears to be correlated with pressing the shift key. At work, I use the Fedora (GNOME) version and it works always fine.
