### ISSUE TITLE
Slowness when calling View()

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1593]
https://community.rstudio.com/t/rstudio-1-1-383-very-slow-to-open-view-tab-on-windows-7/1865

May be related to #1592 -- a number of users have reported that this occurs when RStudio, their R library, or some combination of both live on network shares.

**Comment by kevinushey** [comment]
One user has reported this on macOS: https://community.rstudio.com/t/rsstudio-1-1-perfomance-issues/1915; perhaps it's not Windows-only?

**Comment by ateucher** [comment]
I posted in the Community forum - reposting here:

I had this same issue and figured out a workaround that has been doing the job. It seems to happen when your `HOME` is on a network drive (as it often is in an enterprise environment). 

My workaround is here: https://gist.github.com/ateucher/f279abc1f7ba12f2763152c18810fb24 - essentially I just set the `HOME` env var to a location on my C: drive. As far as I can tell, `HOME` is generally unused (and unset by default) in Windows, so making this change didn't really change anything else on my system, except in the bash shell that comes with Git for Windows.

**Comment by kevinushey** [comment]
I have a suspicion that this issue may be resolved in the current preview release of RStudio (hopefully to be published in the near future as a patch release):

https://www.rstudio.com/products/rstudio/download/preview/

@ateucher, if you have a minute would you be willing to test the preview release (v1.1.393) and let us know if the issue is still present?

**Comment by ateucher** [comment]
@kevinushey I'm no longer on Windows, but my colleague @boshek said he can give it a whirl.

**Comment by boshek** [comment]
This indeed does appear to be fixed at least on my Windows 7 machine. I was able to replicate the error in v1.1.383 but not in v1.1.393 without using @ateucher's workaround. The View() popped up a pane very speedily.

**Comment by kevinushey** [comment]
That's excellent news! Thanks for taking the time to check.

**Comment by DuraQ** [comment]
v1.1.393 fixed the issue I had where R-Studio would not work whenever my home (network) drive was connected. I can finally stop using Eclipse and go back to R-Studio !

**Comment by JanOosting** [comment]
I also experienced slowness of view() with a home folder on a network drive

Installing the current preview (1.1.402) solved this issue.
