### ISSUE TITLE
Crash when using arrow keys to navigate Open File/Project... dialog box

### ISSUE THREAD

**Issue by bkkkk** [rstudio/rstudio#1595]
I'm finding that Rstudio crashes when I attempt to use any of the arrow keys to navigate through files in the Open File... dialog boxes (be it project or any other file). This has been happening for several version of Rstudio including stable and beta.

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1    yaml_2.1.14
```

**Comment by jmcphers** [comment]
Sorry, we couldn't reproduce this. :-/ What exact version of RStudio are you seeing this on? 

Can you share the crash report from `~/Library/Logs/DiagnosticReports/`?

**Comment by bkkkk** [comment]
@jimhester Rstudio Version 1.1.383

[RStudio_2017-10-13-MacBook-Pro.txt](https://github.com/rstudio/rstudio/files/1381142/RStudio_2017-10-13-MacBook-Pro.txt)

**Comment by kevinushey** [comment]
One slightly suspicious bit of output in those logs:

> 0x10056c000 -        0x10096fffb  com.apple.WebKit (12604 - 12604.1.38.1.7) <1453D9AA-E604-3625-9181-D869808644D7> /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/WebKit
> 0x100d81000 -        0x100f76fff  com.apple.WebKitLegacy (12604 - 12604.1.38.1.7) <3290D6D5-3410-3BCA-9878-38C1945AC447> /System/Library/StagedFrameworks/Safari/WebKitLegacy.framework/Versions/A/WebKitLegacy

I'm not exactly what this `StagedFrameworks` thing is -- are you, or were you, using a beta version of macOS at some point in time? Does upgrading Safari make a difference? (RStudio makes use of WebKit for rendering of web elements on the front-end)

**Comment by bkkkk** [comment]
@kevinushey no I have not. I am on the latest version of Safari which was released 10 days ago.

**Comment by kevinushey** [comment]
What is the output of

    locate */WebKit

when run from a terminal on your machine?

**Comment by bkkkk** [comment]
> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/PyObjC/WebKit
> /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/WebKit
> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
> /System/Library/Frameworks/WebKit.framework/WebKit
> /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/WebKit
> /System/Library/StagedFrameworks/Safari/WebKit.framework/WebKit

**Comment by bkkkk** [comment]
Just to add more information:

```
ermination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x40dedeadbec0:
    JS JIT generated code  000021800d801000-000021800d802000 [    4K] ---/rwx SM=NUL  
--> 
    MALLOC_NANO            0000600000000000-0000600000600000 [ 6144K] rw-/rwx SM=PRV  

Application Specific Information:
objc_msgSend() selector name: section


Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fffc049105d objc_msgSend + 29
1   com.apple.AppKit              	0x00007fffa9a81f2f -[NSCollectionView moveRight:] + 173
2   com.apple.AppKit              	0x00007fffa928be00 -[NSKeyBindingManager(NSKeyBindingManager_MultiClients) interpretEventAsCommand:forClient:] + 2218
3   com.apple.AppKit              	0x00007fffa943fde2 -[NSKeyBindingManager(NSKeyBindingManager_MultiClients) interpretKeyEvents:forClient:] + 201
4   com.apple.AppKit              	0x00007fffa928b2f0 -[NSView interpretKeyEvents:] + 333
5   com.apple.FinderKit           	0x00007fffb7fb1562 -[FI_TCollectionView keyDown:] + 111
6   com.apple.AppKit              	0x00007fffa99ed2cc -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 4086
7   com.apple.AppKit              	0x00007fffa99ebf0a -[NSWindow(NSEventRouting) sendEvent:] + 541
8   com.apple.AppKit              	0x00007fffa98714a8 -[NSApplication(NSEvent) sendEvent:] + 4768
9   com.apple.AppKit              	0x00007fffa934d0f8 -[NSApplication _doModalLoop:peek:] + 563
10  com.apple.AppKit              	0x00007fffa952d374 __35-[NSApplication runModalForWindow:]_block_invoke + 64
11  com.apple.AppKit              	0x00007fffa934ab98 -[NSApplication runModalForWindow:] + 137
12  com.apple.AppKit              	0x00007fffa97f9f48 -[NSSavePanel runModal] + 629
13  org.rstudio.RStudio           	0x0000000100008ac9 -[GwtCallbacks runFileDialog:] + 25
14  com.apple.CoreFoundation      	0x00007fffab5fab8c __invoking___ + 140
15  com.apple.CoreFoundation      	0x00007fffab5faa11 -[NSInvocation invoke] + 289
16  com.apple.WebCore             	0x0000000101e80291 JSC::Bindings::ObjcInstance::invokeObjcMethod(JSC::ExecState*, JSC::Bindings::ObjcMethod*) + 1057
```

**Comment by jmcphers** [comment]
We no longer use Safari as a rendering engine, so this should be an issue any more (starting with 1.2 we use QtWebEngine). Feel free to reopen if you're still seeing it!
