### ISSUE TITLE
Possibility to Get Rid of Environment Tab

### ISSUE THREAD

**Issue by DarioS** [rstudio/rstudio#1596]
In Global Options ...'s Panel Layout screen, the act of unticking the box in one panel automatically ticks the box in the other panel. There is no way to get rid of it. If there is a large matrix (e.g. 100 million rows and 30 columns) in memory, each time `browser()` is used and then exited with `Q`, the R console becomes unusable for a couple of minutes while the Environment tab has a spinning wheel in it.

**Comment by jmcphers** [comment]
It's not possible to get rid of it, but in RStudio 1.2 (currently under development) you can tell it not to refresh automatically, which should do what you want. 

![image](https://user-images.githubusercontent.com/470418/31507102-5c2f300a-af2e-11e7-9226-ed1a7a5b77ca.png)

**Comment by jmcphers** [comment]
Oh, and daily builds of RStudio are here if you want to try 1.2 out (note however that this is very much pre-release software):

https://dailies.rstudio.com/
