### ISSUE TITLE
When using Install and Restart with a package missing, RStudio asks to install Rtools

### ISSUE THREAD

**Issue by JoFAM** [rstudio/rstudio#1597]
With version 1.1.383 on Windows 7 and R 3.4.2

I have a package project and I try to "Install and Restart". Due to a recent update of R, I forgot to reinstall one of the dependent packages. So obviously the installation process gives an error. When that happens, RStudio asks me to install additional tools for package building (i.e. Rtools) even though that one is installed on my computer.

This behaviour happened with previous versions of RStudio as well btw. After I installed the missing package, everything works as expected.

Expected behaviour: When Rtools is already installed, failure to build and install the package should not trigger the question to install Rtools.

**Comment by JoFAM** [comment]
With version 1.1.423 , R 3.4.3 and Windows 7 the issue is still there. 

This happens every time the package can not be compiled correctly (eg due to a simple syntax error in one of the code files).

**Comment by JoFAM** [comment]
With version 1.1.442 R 3.5 Rtools 3.5 and Windows 10 I now get a warning that Rtools is required to build R packages when something fails. Also this warning makes no sense, as Rtools is perfectly installed on my computer. Problem arose by trying to install survival from a local fork of the github repo. When installing from source using install.packages(), it all succeeds.

**Comment by jmcphers** [comment]
We do not have a repro for this, haven't had any new info in 2 years, and don't support 1.1.442 any more. @JoFAM If you're still seeing this with the latest preview (https://www.rstudio.com/products/rstudio/download/preview/), feel free to open another issue.
