### ISSUE TITLE
Calling 'New Terminal' while console is minimized doesn't raise terminal

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1599]
Seems like this only reproduces in the following very specific case:

1. If you have RStudio open, close any open terminals,
2. Launch a new session of RStudio (so that there are no terminals visible when RStudio is launched). E.g. re-open whatever the active project is.
3. Minimize the Console pane,
4. Attempt to launch a terminal with `Tools -> Terminal -> New Terminal`.

Nothing appears to happen, as the Console pane is not raised and the Terminal tab does not get focused. However, clicking on the Console pane after shows a terminal was created; it was just not activated / focused.

In my case, repro'ed on RStudio v1.1.371 on macOS.

**Comment by gtritchie** [comment]
Also happens with the Jobs tab:
- close the Jobs tab if currently displayed (via the [x] on the tab)
- launch a new session per the terminal repro steps
- minimize the console pane
- View / Show Jobs

Nothing visibly happens, but if you re-expand the console pane, the Jobs pane is now visible and selected.

**Comment by gtritchie** [comment]
To repro with terminal (on 1.3) had to close the entire terminal tab via the tab's [x], then start a new instance of the UI, minimize the console tab, and then try to create a terminal.
