### ISSUE TITLE
Parse errors during Rcpp::compileAttributes() cause Build pane to 'freeze'

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1601]
To reproduce, try working on an R package that contains compiled C / C++ code. In my case, I reproduced this using the [reticulate](https://github.com/rstudio/reticulate) package. To reproduce, try doing the following:

    writeLines("x <-", "R/ouch.R")

then invoking a Install and Restart (Build and Reload) with Ctrl + Shift + B. You should see something like:

<img width="443" alt="screen shot 2017-10-12 at 4 05 50 pm" src="https://user-images.githubusercontent.com/1976582/31523252-3fec0b64-af67-11e7-83c7-550277e8e4dc.png">

and attempts to press the Stop button, or start new builds, will fail.

**Comment by kevinushey** [comment]
Relevant code likely lives here: https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/build/SessionBuild.cpp#L514-L550

**Comment by jmcphers** [comment]
Backported to 1.1 here: 881134bcca528764932db26a721051089cbe900f

**Comment by dfalty** [comment]
Verified fixed 1.1.392.
