### ISSUE TITLE
GitHub's file finder doesn't search within 'build' folders

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1602]
The GitHub file finder (invoked by e.g. `t` from the repositories main page) fails to index items in the `session/modules/build` folder, likely assuming that the folder contains build artefacts that we (normally) wouldn't care about.

We might consider renaming that folder (+ relevant usages) just to avoid this sort of minor nuisance.

**Comment by jmcphers** [comment]
This behavior is documented here: https://help.github.com/en/github/searching-for-information-on-github/finding-files-on-github

**Comment by kevinushey** [comment]
Hooray, thanks for doing this!

<img width="666" alt="Screenshot 2023-11-14 at 1 21 07 PM" src="https://github.com/rstudio/rstudio/assets/1976582/af31cee4-73eb-4375-8c7b-27dace1772f0">
