### ISSUE TITLE
Global Options Conflict with Zoom

### ISSUE THREAD

**Issue by tres-pitt** [rstudio/rstudio#1605]
I was really hoping this issue would have been solved with the new release, although admittedly I don't need to access global options with great frequency

Basically if you're zoomed in the text editor, and you access global options, you won't be able to see the whole global options dialogue/pane. So, if you need to access something toward the bottom of options, you must exit options, zoom out, open options (and then exit options and re-zoom in, to continue working). Don't expect a quick fix on this, but I do want to make sure devs are aware of it, as I find the default text size too small

**Comment by gtritchie** [comment]
Ability to zoom-in any part of the UI (and still use it!) is an essential accessibility requirement. Marking as such.

**Comment by kevinushey** [comment]
Also important because the default configuration for some machine configurations can get users into this state, even without any other configuration of RStudio.
