### ISSUE TITLE
Store RStudio user preferences in a user-accessible location

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1607]
We've often had requests to store user preferences in a user-accessible location, using a user-editable file format. The motivation is typically to make it possible to develop a set of personal settings which can be moved from machine to machine, stored on version control, etc.

We currently store most user preferences in a private file inside `~/.rstudio/monitored/user-settings` (or the platform equivalent), many of them in a JSON `uiPrefs` blob. Since RStudio's inception, several editing platforms (Sublime and Visual Studio Code) have exposed their preferences as user-editable JSON. We could do the same with a handful of changes:

1. Create a location for RStudio user preferences, probably following the [XDG configuration standard](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)
2. Separate the existing `user-settings` content into internal settings (including machine-specific settings such as `contextIdentifier`) and external settings.
3. Load and save external settings to the .json file instead of the `user-settings` file.

**Comment by jmcphers** [comment]
A natural extension of this work would be to allow for a "global defaults" settings file to be read from a shared location, for use by administrators who wish to set defaults for their users according to constraints/patterns in their environment.

**Comment by jmcphers** [comment]
A vote for this here: https://support.rstudio.com/hc/en-us/community/posts/115009277088-User-defined-folder-for-RStudio-settings

**Comment by haozhu233** [comment]
I second to this possible feature. 

When I wrote rmarkdown documents, I found it has been very useful to change chunk evaluation location from `document` to `project` so if your rmd file is buried in some sub-directory, you can make sure you start from the same space when you run code chunks in console & click the render button. However, after I moved my files to rstudio server and shared the folder with someone else, since they haven't enabled this feature, they usually run into trouble that R cannot find the file. As a team working on RStudio, it will be very useful to be able to setup a unified customizable default profile for cases like this.

**Comment by russellpierce** [comment]
Bump, as a user interested in this feature. ;)

**Comment by BrainStormCenter** [comment]
I too that this would be a great feature for RStudio. As an rstatsnewbie working on a couple of different machines (work & home), being able to sync packages and settings between them would be greatly appreciated!!!

**Comment by jmcphers** [comment]
@sellorm specifically suggested that we include pane and theme config in the files (see #3129)

**Comment by sellorm** [comment]
I guess anything/everything from 'Global Options' would be good

**Comment by coatless** [comment]
It would be great if it was possible to streamline retrieving and modifying the configuration ala the state information given at: https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

As it stands now, this is largely done through posting pictures. Unfortunately, this creates headaches for newer users...

**Comment by jdblischak** [comment]
It would also be convenient if local settings (e.g. in a directory containing an `.Rproj` file) would override any global settings, e.g. how a local `.gitconfig` combines with the settings in the global `~/.gitconfig` file.

**Comment by Zedseayou** [comment]
Not sure whether this is a common use case for others, but when my RStudio Server instances crash I often have to manually reset all options. Being able to import settings somehow would be great when creating new instances.

**Comment by jmcphers** [comment]
See here for another example of how configuration is shared in the absence of something like this:

https://drdoane.com/my-rstudio-configuration/

**Comment by JsizzleR** [comment]
RStudio Server Pro customer requested,  ticket 37036

**Comment by jdblischak** [comment]
Another useful option to include in a config file is how to filter the files that are displayed in the Files pane, as noted by @kevinushey in https://github.com/rstudio/rstudio/pull/3383#issuecomment-416648088

**Comment by jmcphers** [comment]
This change won't add any new options; it will only change the way we store existing ones.

**Comment by Robinlovelace** [comment]
Just to say, many thanks @jmcphers this will make lots of peoples lives lots easier when this is rolled-out. I'm planning on using it to create a custom docker image optimised for academic geographic research, with Rmd chunks evaluated in-line. One question: will we be able to set shortcuts through the plain text file?

Many thanks for this work in any case, looking forward to it being merged!

**Comment by jmcphers** [comment]
@Robinlovelace Good news, you don't need this change to set shortcuts; they are already customizable with plain text files. See this article for details: https://support.rstudio.com/hc/en-us/articles/206382178-Customizing-Keyboard-Shortcuts

**Comment by Robinlovelace** [comment]
Great, thanks @jmcphers ! I guess setting Rmd chunks to evaluate in the console (not inline is what I meant) still requires this change?

**Comment by jmcphers** [comment]
Yes, that's correct.

**Comment by Robinlovelace** [comment]
:tada: ! May be jumping the gun but, other than here, where is this new functionality documented?

**Comment by jmcphers** [comment]
There's an overview in the PR:

https://github.com/rstudio/rstudio/pull/5069

Later, this will be documented in more detail in the RStudio Server Administration Guide.

**Comment by AtomicNess123** [comment]
Any progress in this enhancement?

**Comment by dpprdan** [comment]
@AtomicNess123 It's documented for [RStudio Desktop Pro](https://docs.rstudio.com/ide/desktop-pro/settings.html) (works the same for the Open Source version) and [RStudio Workbench née Server Pro](https://docs.rstudio.com/ide/server-pro/r-sessions.html#customizing-session-settings).
