### ISSUE TITLE
Changing R Markdown output type can produced malformed YAML

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1609]
(originally reported via @kevinykuo on )

1. Create R Notebook. 
2. Save somewhere. 
3. Knit to HTML. 
4. Gear button -> output options -> change output type to Notebook.

Result:

    ---
    title: "R Notebook"
    output:html_notebook
    ---

This results in confusion due to the missing space:

![image](https://user-images.githubusercontent.com/470418/31569661-5a72f108-b031-11e7-829b-10a496cd8678.png)

**Comment by dfalty** [comment]
Verified fixed 1.2.150
