### ISSUE TITLE
diagnostics system hangs with certain code forms

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1613]
From https://stackoverflow.com/questions/46738732/rstudio-rsession-hangs-when-editing-file

Saving the following code in an R document with the diagnostics system active causes a hang:

```
repeat {}()
```

The diagnostic system views this (admittedly nonsensical) code as a function call, and attempts to evaluate the left-hand side (`repeat {}`) to determine the actual function definition. This causes the R session to hang. There are two issues here:

- `repeat {} ()` should be parsed as `repeat ({}())`, not `(repeat {})()`;

- We should perform some kind of 'safe' evaluation here, e.g. only accepting `$`, `@`, `[`, `[[` when trying to evaluate these calls.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/eba5ca4b3668701eb552e0b1e25eefa852e06dc0

**Comment by dfalty** [comment]
Verified fixed 1.2.158.
