### ISSUE TITLE
Dark theme text color applied to HTML widgets in notebooks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1615]
Example from @tareefk:

![image](https://user-images.githubusercontent.com/470418/31637586-2f6facda-b284-11e7-97c5-90a20f4608ae.png)

And from myself:

![image](https://user-images.githubusercontent.com/470418/31637614-592d1b34-b284-11e7-9434-e217fc43427e.png)

Everything is fine with a light theme:

![image](https://user-images.githubusercontent.com/470418/31637624-6f58a360-b284-11e7-8413-eef9b8bdaf4c.png)

I haven't investigated, but I suspect that the problem here is that the dark theme is changing the text color to make the HTML widget content readable, but it's doing it even for HTML widgets that supply their own background color. @javierluraschi could you take a look?

**Comment by javierluraschi** [comment]
@jmcphers This one reproes since RStudio 1.0, sending back to you as this is probably more notebook html-widgets related.

<img width="1278" alt="screen shot 2017-10-16 at 3 25 26 pm" src="https://user-images.githubusercontent.com/3478847/31638027-44d631aa-b286-11e7-842e-0808e2777eeb.png">

**Comment by jmcphers** [comment]
Should be fixed in https://github.com/rstudio/rstudio/commit/2918508873ea45343766974d25415c700a5e37fc.

**Comment by dfalty** [comment]
Verified fixed 1.2.158.
