### ISSUE TITLE
RStudio: Set parameters of a parameterized report for interactive use

### ISSUE THREAD

**Issue by sjackman** [rstudio/rstudio#1616]
A dialog box similar to `Knit with Parameters` that changes the parameters for the current session would be nice to have. Setting the parameter manually using `params$foo <- "bar"` doesn't work because it gets reset to the default value with each ⌘Enter.

**Comment by jmcphers** [comment]
There's been no other interest in this feature for a couple of years, and we don't foresee having time to work on it in the next year, so closing.

**Comment by sjackman** [comment]
My work around is to temporarily add `params$foo <- "bar"` to the `setup` chunk.
