### ISSUE TITLE
Rstudio Viewer color scheme using grey on white fonts

### ISSUE THREAD

**Issue by HanjoStudy** [rstudio/rstudio#1617]
Rstudio version 1.1.383: When using `modern` and `sky` theme, RStudio Viewer has a color scheme where you have light grey text on white background which makes the values difficult to see values and headings:

![capture](https://user-images.githubusercontent.com/12710800/31652425-5055b99e-b31f-11e7-819f-3028445da738.JPG)

**Comment by jmcphers** [comment]
I think this is the same issue as #1573 -- does that look like what you're seeing?

**Comment by HanjoStudy** [comment]
It is indeed! I will see if clearing the cache helps and see if anything strange pops up with different users on the server.
