### ISSUE TITLE
Unity integration for Rstudio menu

### ISSUE THREAD

**Issue by ghost** [rstudio/rstudio#1618]
Is there any way in version 1.1.383 to get a global menu integration for Ubuntu 16.04? 
There are many questions like this (couldn't find any issue on github): 
https://askubuntu.com/questions/588844/how-to-enable-global-application-menu-in-rstudio
https://askubuntu.com/questions/767827/how-do-i-enable-global-menu-for-rstudio-in-16-04
but no solution is working anymore.
It would be nice to point out how to get the integration or even better fix this issue in the deb package.
I can understand that unity has no priority after the decision to use GNOME 3.26 in Ubuntu 18.04. Anyway it would be cool to have this topic cleared. Thank you for reading and your effort.

**Comment by dfalty** [comment]
@jmcphers Looks like there were a couple of FogBugz tickets on this. (2684 and 3232).

**Comment by jmcphers** [comment]
Unity has been EOL'ed for a couple of years now, so we don't plan to do work to integrate it.
