### ISSUE TITLE
Extended functionality for 'most recently used' projects list

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1620]
Some potential things to consider for improving the project MRU list:

- Make it searchable (e.g. as addins are),
- Increase the number of MRU projects kept in history, and show them in a scrollable menu,
- Make it possible to easily move / remove projects from the MRU list.

Original request originates from https://support.rstudio.com/hc/en-us/community/posts/208260398-Increase-Size-of-Projects-MRU-List.

**Comment by ipofanes** [comment]
I would like to add that the place where this file be stored should be customizable. At my office installation, it resides in a directory that gets deleted every time I log out.

**Comment by AshesITR** [comment]
Good ideas. I want to add one:

* Allow Projects to be permanently pinned to the MRU lists top, regardless of how many projects were opened afterwards
