### ISSUE TITLE
On (arch) linux, system("xsel") and system2("xsel") hang in rstudio but not in terminal

### ISSUE THREAD

**Issue by potterzot** [rstudio/rstudio#1627]
I noticed this because it causes `reprex` to hang, which happens because `clipr` hangs, and in tracing why I finally came to this issue.

On linux running `R` version 3.4.2:

#### The issue
If run from `R` in the terminal, `system2("xsel")` I get:
    
    <blank line>
    \ No newline at end of selection

If run from the `rstudio` terminal, `system2("xsel")` prints a blank line like the above output but then hangs until I interrupt it.

#### Things I've checked:
* `R` and `rstudio` are both using the same version of `R` 3.4.2.
* Using a different command, for example `system2("ls", "-l")` there is no problem. I have not been able to find any other system command that causes this issue. I've tried "ls", "cat", "grep", and "echo", and "xclip".
* No matter what options I use with `xsel` the error is the same. I've tested with `-t 200` for a timeout but the hang still happens.

#### Work around
A work around is to just install "xclip" and use it as your clipboard manager instead, which has no problems with `rstudio` or `R` in the terminal.

**Comment by dfalty** [comment]
I don't have an arch linux box set up atm. @jmcphers do you know what could cause a hang like this? I'm not able to repro on other boxes.

**Comment by potterzot** [comment]
@dfalty thanks for looking into it! I have two Arch boxes (one laptop one desktop) both of which have this issue, no other linux box to test. I'll try to test on some docker images this weekend.

**Comment by jmcphers** [comment]
We haven't heard back in a couple of years so closing this one. @potterzot Feel free to reopen if you're still seeing this with recent RStudio builds.

**Comment by potterzot** [comment]
This is still happening and reproducible in my initial issue.

Just looking at it now, I should note that adding the `timeout` option prevents this, e.g.
 
```{r}
# No problem here:
system2("xsel", timeout = 100)

# This hangs and has to be interrupted by clicking on stop sign
system2("xsel")
```

**Comment by potterzot** [comment]
PS - I don't have permissions to reopen this.

**Comment by jmcphers** [comment]
Can you tell us more about your RStudio version (desktop? server? build?) and X environment?

**Comment by potterzot** [comment]
Here's some more information that may help. 

The issue originated for me when trying to use [reprex](https://github.com/tidyverse/reprex), which calls [clipr](https://github.com/mdlincoln/clipr) if no input is provided. The issue is in this bit from [these lines](https://github.com/mdlincoln/clipr/blob/84db7c9a07cf14b44cda46d59ee572b095c588a9/R/linux_clipboard.R#L45-L57) in `X11_read_clip()`, which (extracting the relevant bits) looks like:

```{r}
con <- pipe("xsel --clipboard")
content <- scan(con, with = character(), sep = "\n", blank.lines.skip = FALSE, quiet = TRUE)
```

Running that code in `R` in a terminal returns the contents of the clipboard. Running that same code in `Rstudio` causes a hang until I interrupt. It still returns the value though.

The issue is limited specifically to users who use `xsel` as their clipboard program instead of alternatives such as `xclip`. If I use `xclip` I do not have the same problem. Given that, it seems maybe it's somewhat obscure. I tried to set up a docker image to test on other linux distributions but I don't have time atm to get it all sorted. If no one else has this problem, then it may be that the number of people using `reprex` and `xsel` are exactly one ;).

#### System Details
```
Arch Linux using X11 and xsel
Rstudio: 1.2.5001
R: 3.6.1
```

**Comment by R-Hannibal** [comment]
@potterzot - Apologies you are experiencing this issue with Rstudio.

Closing this issue as Out of Scope as we do not officially support Arch Linux.
