### ISSUE TITLE
Feature request, quote multiple elements quickly.

### ISSUE THREAD

**Issue by skanskan** [rstudio/rstudio#1628]
Hello.
Quite often we need to create a list or vector of strings in R. 
Writing quotes around every single element is time consuming and prone to error.
It would be great to have an Rstudio quick way to transform this
`A, B, C, D, E, F`
to this
`"A", "B", "C", "D", "E", "F"`
by just pressing a key combination.

This has already been asked by other user at 
https://stackoverflow.com/questions/38047593/how-to-put-quotes-around-several-words-quickly-in-rstudio

But the solutions provided need the user to explicitly code with R every time, it's not a Rstudio solution.

**Comment by jmcphers** [comment]
You can build an RStudio add-in to do this if you want. Add-ins can read text, manipulate it, and replace it in the editor, and you can bind an add-in to a keyboard shortcut so that it works just like a built-in RStudio feature. More here:

https://rstudio.github.io/rstudioaddins/

**Comment by jmcphers** [comment]
There are now addins like datapasta that do this very well; it is unlikely we'll bring it into the IDE core.

https://cran.r-project.org/web/packages/datapasta/vignettes/how-to-datapasta.html
