### ISSUE TITLE
User and admin customizable default file templates

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1632]
Currently, RStudio ships with a set of templates for common file types; for example, *File -> New File -> R Notebook* gives you a notebook with introductory text and a few chunks to try running.

Many users who are already familiar with R Markdown (cc @jennybc) would prefer it if they could have RStudio use a template of their choosing to populate the initial contents of new documents. 

There's already a roundabout way to do this that involves some extra work and clicking; you can create an [R Markdown Document Template](http://rmarkdown.rstudio.com/developer_document_templates.html). However, it's not easy to do for average users, and even when set up invocation isn't frictionless. 

It might also be nice for administrators to be able to set up the default document templates, so that they e.g. meet corporate requirements for output.

**Comment by jmcphers** [comment]
See #3569; this shouldn't just be for R Markdown but for all new file templates.

**Comment by jmcphers** [comment]
We should do the work in https://github.com/rstudio/rstudio/issues/1607 before tackling this one. When #1607 is complete, we will have established a convention for where user and admin preference data is stored, and we should use those same locations for new file templates.

**Comment by jmcphers** [comment]
This is implemented now in RStudio 1.3.

**Comment by jmcphers** [comment]
Details here: https://github.com/rstudio/rstudio/pull/5144

**Comment by R-Hannibal** [comment]
Closing as Fixed.

This enhancement was tested earlier in the 1.3 cycle and then re-tested as part of QA's certification effort. If we have any new bugs crop up related to this we'll treat them as new bugs and not a failure of this enhancement being implemented.
