### ISSUE TITLE
Ctl-L in Terminal focuses browser address bar on RStudio server

### ISSUE THREAD

**Issue by nibrivia** [rstudio/rstudio#1636]
In the Terminal tab, clearing the output with Ctl-L gets caught by the web browser (Chrome) and focuses the address bar. This means that Ctl-L followed by return (a common pattern) ends up reloading the page...

The Console tab has the correct behavior of keeping the cursor in the Console tab.

**Comment by gtritchie** [comment]
What platform did you see this on? Windows, Mac, Linux?

**Comment by dfalty** [comment]
I was able to reproduce on Windows 10 + Chrome + RSP (1.1.414).

**Comment by gtritchie** [comment]
Also repro's on rstudio cloud, using Linux Chrome.

**Comment by nibrivia** [comment]
I'm on ChromeOS with Chrome 63.0.3239.140 (Official Build) (64-bit), and the server is on AWS, Ubuntu 16.04, and the latest RStudio from the repos (don't have access to it right now, was up-to-date on Friday).

**Comment by dfalty** [comment]
Verified fixed 1.2.353-2.
