### ISSUE TITLE
Poor spacing around publish account when username and servername are short

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1637]
When updating an existing deployment, the username and servername have too much space around them if both are very short. 

![image](https://user-images.githubusercontent.com/470418/31832931-aa7bd7b8-b57d-11e7-9fa5-cfb16fcebded.png)

**Comment by jmcphers** [comment]
Candidate for patch release since this UX is new in 1.1.

**Comment by jmcphers** [comment]
Backported to 1.1 here: 4173df74def12f82b6be5184e94b5cc8e32f7d21

**Comment by dfalty** [comment]
Verified 1.1.392.
