### ISSUE TITLE
provide autocompletion within `with`, `within`

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1639]
With code of the form:

```R
with(mtcars, {
    |
})
```

It would be helpful if we provided autocompletion results based on the names available in the `with()`-ed object. I also sometimes wish for a similar form for e.g.

```R
lapply(object, function(el) {
    el$<TAB>
})
```

where autocompletion results would be generated based on whatever `object[[1]]` might return (as often, elements of a list have similar structure when looping over in this form)

**Comment by therimalaya** [comment]
We have not seen any such feature implemented in Rstudio yet. I hope Rstudio can implement the autocompletion feature inside `with`, `within`, `eval` and `evalq`.
