### ISSUE TITLE
Cursor drifts to the right

### ISSUE THREAD

**Issue by wlandau** [rstudio/rstudio#1640]
The first line in each left panel looks like it has trailing whitespace, but this is all cursor misalignment. I am using fresh copies of RStudio 1.1.383, R 3.4.2, and KDE Neon User Edition 5.11 (built on Ubuntu 16.04).

![screenshot_20171020_202128](https://user-images.githubusercontent.com/1580860/31846188-24e3f0fa-b5d6-11e7-8ea5-599bb7b95fa8.png)

**Comment by wlandau** [comment]
I solved this one by uninstalling RStudio, installing some dependencies, and then reinstalling. I installed the dependencies by locating the [folder with Linux dependency scripts](https://github.com/rstudio/rstudio/tree/master/dependencies/linux) and running `sudo ./install-dependencies-debian`.

**Comment by jmcphers** [comment]
Glad you got that figured out, thanks for following up! The problem appears to be that your editor font wasn't fixed-width (RStudio's editing panel only works with monospace fonts).
