### ISSUE TITLE
Cant knit to HTML

### ISSUE THREAD

**Issue by hugeme** [rstudio/rstudio#1644]
After upgrading to 1.1.383 Im not able to initialize new `R - Markdowns`, even with the example code I receive:

    Error: 1:5: unexpected $end
    Execution halted

That is super strange since I can knit existing `.Rmd`. Furthermore, If copy & paste the example code of a fresh initialized  `R-Markdown` into an older `.Rmd` then it works.

![new_initialized](https://user-images.githubusercontent.com/18237090/31851440-fd92061e-b665-11e7-92cf-c9ebd37150d7.png)

**Comment by jmcphers** [comment]
Sorry, we haven't been able to reproduce this. It looks like the error's coming from the knitr or rmarkdown pacages, so you might try updating those to the latest versions.

Can you include your `sessionInfo()`?

**Comment by tmcduff** [comment]
Version: Version 1.3.842

*not* reproducible.
