### ISSUE TITLE
RStudio version control function configuration doesn't allow custom RSA key

### ISSUE THREAD

**Issue by JackieMium** [rstudio/rstudio#1645]
I am trying to use RStudio with Git to manager a project on GitHub. 

But when I configure in the *Git/SVN* tab, the *SSH RSA Key* option is locked to `~/.ssh/id_rsa`, but the key file is actually for another site with another account of mine. 

My RSA key for GitHub is not stored in this file. How can get I RStudio to using another RSA key file? So I think it's necessary that RStudio allow configurable RSA key file.

**Comment by rmflight** [comment]
have you tried just using the push and pull buttons after setting up the project on GitHub? Behind the scenes I believe RStudio is just calling `git`, so if you have an ID in another file that works with GitHub properly on the command line, using RStudio instead should just work.

**Comment by JackieMium** [comment]
@rmflight Great, it works. Sorry I didn't check for that earlier.

**Comment by rmflight** [comment]
That's good that it still works. 

But I agree, for those unfamiliar with the command line and git, it *might* be useful if RStudio allowed this field to be modified. But then it should also do some configuration behind the scenes as well, when I don't know if it does anything besides write the ssh key at the moment.

**Comment by JackieMium** [comment]
Yes, the configuration box shows `~/.ssh/id_rsa` will be used, it's really confusing.

**Comment by jmcphers** [comment]
See also notes in https://github.com/rstudio/rstudio/issues/1969.
