### ISSUE TITLE
file:// urls for CRAN repositories give spurious warning

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#1646]
From Kurt Hornik:

If one has a local CRAN or BioC mirror, e.g.

```
R> getOption("repos")["CRAN"]
                           CRAN
"file:///data/Repositories/CRAN"
```

  one gets

    WARNING: Your CRAN mirror is set to "file:///data/Repositories/CRAN"
    which has an insecure (non-HTTPS) URL. The repository was likely
    specified in .Rprofile or Rprofile.site so if you wish to change it
    you may need to edit one of those files. You should either switch to
    a repository that supports HTTPS or change your RStudio options to
    not require HTTPS downloads.

**Comment by dfalty** [comment]
Verified fixed 1.2.160.
