### ISSUE TITLE
Call to `q()` for quitting session should be namespace qualified

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#1647]
From Kurt Hornik:

If one does e.g.

```
 q <- function(x, y) x + y
```

at the prompt, things like

```
q(1, 2)
```

etc work fine, but "Quit Session" gives

```
Error in (function (x, y)  : unused argument (TRUE)
Error in (function (x, y)  : unused argument (TRUE)
```

I guess the quit session code ends up calling 'just' q() instead of
base::q()?

**Comment by jmcphers** [comment]
Fixed via https://github.com/rstudio/rstudio/commit/2981b04f6a2b5abf01aeb5a0b99a35c6eca31da4.

**Comment by dfalty** [comment]
Verified 1.2.150
