### ISSUE TITLE
Latest version of knitr persists python engine across chunks. Add this to RStudio eval

### ISSUE THREAD

**Issue by pjc42** [rstudio/rstudio#1651]
It would be great to be able to use python engine the same way we can use R engine where R process persists across chunks. Currently python engine does not persist process across chunks.

Persisting the python across chunks has recently been added to knitr. It would be great to see this added to RStudio evaluation of Rmd docs so python can be used in Rmd in the same way R can.

**Comment by dfalty** [comment]
Thanks for the request!

@jmcphers we had this in the FogBugz milestone 1.2 as ticket #6178.

**Comment by jmcphers** [comment]
@kevinushey is already working on this. :-)

**Comment by yutannihilation** [comment]
Nice feature! Can I expect this for Julia as well? Should I file a separate issue?

**Comment by jmcphers** [comment]
You're welcome to file a separate issue, but we don't currently have plans to support Julia in the same way.

**Comment by yutannihilation** [comment]
Thanks, I will :)

**Comment by pjc42** [comment]
hi guys, just checking in if you have a timeline for this enhancement yet?

**Comment by jmcphers** [comment]
It's now implemented in the daily builds of RStudio.

https://dailies.rstudio.com/

**Comment by kevinushey** [comment]
Yes, we're working hard to prepare v1.2 for release (hopefully by the end of this year)
