### ISSUE TITLE
Non-default window positioning leads to build menu appearing off-screen

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#1652]
Swapping the **Environment, History, Connection** tab with **Console** -- e.g. the panels on the Upper Right move to the Lower Left -- leads the build menu to appear off screen. See screenshot for example:

![Build Menu Off-Screen](https://user-images.githubusercontent.com/833642/31953866-a0afae7e-b8a9-11e7-8cff-6c37da03299d.png)

**Comment by dfalty** [comment]
I can't reproduce this on Mac version 1.2.134. What version of RStudio are you on? Also, do you have additional info to reproduce this?

**Comment by coatless** [comment]
@dfalty This problem exists in both the "stable" and "daily" variants of RStudio. When I referred to the "Build" menu, I meant to say: "Build book"

I've recorded the exact steps using a clean install of the daily version 1.2.140

![rstudio_debug_menu](https://user-images.githubusercontent.com/833642/32152350-9318ee50-bcf1-11e7-8c50-0fd2513418fe.gif)

**Comment by dfalty** [comment]
@coatless Thanks for the additional info! I'm also able to reproduce this on Mac 1.2.140.

**Comment by gtritchie** [comment]
Fixed in 1.3 via #5714

**Comment by tmcduff** [comment]
version: Version 1.3.842
