### ISSUE TITLE
Feature request: add button to open profiles in an external browser window

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#1657]
It's sometimes useful to open a profile in an external browser, but currently there's not a simple way to do this. There is a button to pop it out into a separate viewer window, but that doesn't provide all the same advantages as an external browser. Most importantly, the external browser can be faster than an RStudio viewer window, and any slowness in the browser won't interfere with the RStudio session.

![image](https://user-images.githubusercontent.com/86978/31969220-7100c46c-b8d9-11e7-9819-cced155789bd.png)

**Comment by dfalty** [comment]
Verified 1.2.150
