### ISSUE TITLE
Feature request: provide a way for users to see rmarkdown command

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#1658]
Currently, if a user clicks on the Knit or Run button, it's not clear what command is being run. Many users might not know that it's `rmarkdown::render()` or `rmarkdown::run()`, or which options are being passed to these commands. Making the call visible to the user would help educate users about what is going on, and it also help them if they want to run the commands in an interactive session that allows debugging.

I think it would also be useful to display the commands for running tests, documenting a package, and building packages

**Comment by jmcphers** [comment]
Sometimes the commands we actually run for these include internals that would just confuse people and clutter the output. However for people that do want to see what's going on, I've just added a new pref that will show the command. You can find it here:

*Options -> R Markdown -> Display render command in R Markdown tab*

We typically do show the commands for tests/doc (devtools::test, etc.)

**Comment by wch** [comment]
Awesome!

**Comment by dfalty** [comment]
Verified 1.2.150.
