### ISSUE TITLE
cursor positioning issue w/RStudio desktop on Ubuntu

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1659]
https://support.rstudio.com/hc/en-us/community/posts/115007909067-Cursor-jump-on-scroll-over-of-the-x-in-tabs-of-the-source-and-console-panes

The hand cursor is not positioned correctly in the desktop editions of RStudio on Ubuntu -- it is displayed offset to the bottom-right of the true / correct position.

![cursor-position](https://user-images.githubusercontent.com/1976582/31971371-67359c54-b8d0-11e7-934a-44592cf80c62.gif)

**Comment by BenoitLondon** [comment]
same issue on SLED (Suse)

**Comment by dfalty** [comment]
Verified fixed 1.2.158.

**Comment by jmcphers** [comment]
Backported to 1.1 here: 2562dbd6d78cd4cc8a2cb5a53c32894b3642bd5d

**Comment by rnahumaf** [comment]
I have the same issue on version 1.1.383. I'm running elementary OS 0.4.1 Loki.
