### ISSUE TITLE
search highlight is hard to see in some themes

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1660]
https://support.rstudio.com/hc/en-us/community/posts/115007907207-Can-t-see-text-highlighting

For example. with the Tomorrow Night theme:

![screen shot 2017-10-24 at 3 36 27 pm](https://user-images.githubusercontent.com/1976582/31971559-2e010f80-b8d1-11e7-92a7-1f7bee927bb7.png)

**Comment by rmflight** [comment]
Yes! I was doing a find today on some text and could *not* for the life of me find the highlighted text b/c it just doesn't stand out from the rest of the text.

**Comment by seasmith** [comment]
Highlight the row-number background for all rows with a match, and then use transparency/gradient to highlight the active row.
