### ISSUE TITLE
Consider using 'read_table2()' rather than 'read_table()' for readr Import Dataset

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1661]
https://support.rstudio.com/hc/en-us/community/posts/115007434827-No-way-to-import-data-using-RStudio-windows-1-1-364-and-readr-1-1-1?page=1#community_comment_115005232908

---

Note that, right now, it's not possible to read whitespace-delimited datasets through the readr Import Dataset dialog. Compare e.g.

```R
> input <- "a b c
A 1 2
B 3.0 4.0"

> readr::read_table(input)
Parsed with column specification:
cols(
  a = col_character(),
  `b c` = col_character()
)
# A tibble: 2 x 2
      a `b c`
  <chr> <chr>
1     A   1 2
2     B   3.0
```

and

```R
> readr::read_table2(input)
Parsed with column specification:
cols(
  a = col_character(),
  b = col_double(),
  c = col_double()
)
# A tibble: 2 x 3
      a     b     c
  <chr> <dbl> <dbl>
1     A     1     2
2     B     3     4
```

**Comment by dfalty** [comment]
On 1.1.393 (Mac 10.12.2) I don't get read_table2() when trying to use a space for the delimiter. 
![importdataset](https://user-images.githubusercontent.com/15237845/33616353-4bbd3304-d9a2-11e7-971b-c94988f85402.gif)

**Comment by jmcphers** [comment]
This has been fixed, but it hasn't been backported to 1.1-patch yet. @dfalty I'll backport it shortly; in the meantime, you can verify the fix in 1.2 if you'd prefer.

**Comment by jmcphers** [comment]
Backported to 1.1 in 119d868d45983f93f3dabe696c95de02948494fd.

**Comment by jmcphers** [comment]
@dfalty this should work in the next patch build (1.1.395 or newer).

**Comment by ronblum** [comment]
Confirmed in 1.1.399.
