### ISSUE TITLE
Notebooks do not handle custom knitr engines correctly

### ISSUE THREAD

**Issue by thk686** [rstudio/rstudio#1662]
I believe this is an issue with R Studio. The following code knits fine, but generates an error when run in R Studio (ie run-all in the notebook interface). It appears R Studio tries to pipe the code through a binary named after the custom engine. That makes no sense if the engine is not meant for calling an external program. Try the code below with knitr and in R Studio.

I am doing some teaching with Rcpp and it is really a problem that I cannot split code across separate chunks. Hope this will get some attention. Thanks.

````
---
title: "C++ Header Engine Demo"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r}
eng_cppheader = function(options)
{
  code = paste(options$code, collapse = "\n")
  if (is.null(options$file) || nzchar(options$file) == 0)
    stop("file is a required chunk options")
  if (is.null(options$path)) options$path = tempdir()
  cat(code, file = file.path(options$path, options$file))
  Sys.setenv(PKG_CPPFLAGS = paste0("-I\"", options$path, "\""))
  options$engine = 'cpp'
  knitr::engine_output(options, code, "")
}
knitr::knit_engines$set(cppheader=eng_cppheader)
```

```{r}
names(knitr::knit_engines$get())
```

```{r}
knitr::knit_engines$get()$cppheader(
  list(code="Hello world!",
       echo=T, prompt=T, highlight=T,
       file = "test.h"))
```

```{r}
system2('cat', file.path(tempdir(), "test.h"), stdout = TRUE)
```

```{r}
unlink(file.path(tempdir(), "test.h"))
```

```{cppheader, file="test.h"}
#ifndef __test_h__
#define __test_h__

#define test_string "Hello world!"

#include <string>

using std::string;

#endif // __test_h__
```

```{r}
header_file = file.path(tempdir(), "test.h")
ifelse(file.exists(header_file), "I found it!", "I did not find it!")
```

```{r}
Sys.getenv("PKG_CPPFLAGS")
```

```{Rcpp}
#include "test.h"

// [[Rcpp::export]]
string test_it()
{
  return test_string;
}
```

```{r}
print(try(test_it()))
```

````

**Comment by thk686** [comment]
[cpp_header_engine.txt](https://github.com/rstudio/rstudio/files/1413153/cpp_header_engine.txt)

**Comment by thk686** [comment]
This example also exposes a segfault in RStudio proper. Rcpp compile failures in notebooks can trigger a crash.

**Comment by dfalty** [comment]
I'm able to reproduce this on Mac with version 1.2.134.

**Comment by kevinushey** [comment]
I'm now tracking the segfault as a separate issue here: https://github.com/rstudio/rstudio/issues/1668

**Comment by jmcphers** [comment]
Fixed with https://github.com/rstudio/rstudio/issues/2401.
