### ISSUE TITLE
Running rserver without authentication 

### ISSUE THREAD

**Issue by riteshkukreja** [rstudio/rstudio#1663]
I wish to run `rserver` without authentication. So only one user will be connected to the rserver and no authentication will be made. 

I tried running rserver with `--auth-none 1`
```bash
rserver --www-port 9000 --auth-none 1 --auth-validate-users 0
```

but i am still unable to initialize the client 
```
curl -X POST --form method=client_init http://localhost:9000/rpc/client_init
```
Response
```json
{"error":{"code":3,"error":null,"message":"Client unauthorized"}}
```

I want to run rserver using only one user without authentication and without rstudio application. I want to build my own UI that communicate with rserver.
Thanks in advance.

**Comment by jmcphers** [comment]
If you don't need a UI and you don't want authentication then RStudio Server is probably not what you want to use (it isn't designed for this use case). If you're looking to build a web front end to some R code, you might be better served by something like Plumber:

https://github.com/trestletech/plumber

Hope this helps! If you want to discuss further we recommend the RStudio community forum:

https://community.rstudio.com/

**Comment by riteshkukreja** [comment]
But running the rserver with `--auth-none 1 --auth-validate-users 0` should allow me to execute R commands without authenticating user, right?
Let me trim my use case, I wish to execute R commands and get auto completion without authentication.
Is this possible?

**Comment by dinvlad** [comment]
@riteshkukreja if that helps still, turns out we also need to set system environmental variable `USER=rstudio`

**Comment by grisaitis** [comment]
> set system environmental variable `USER=rstudio` in order for `--auth-none 1` to work

good advice. 

to do this with the systemd service, i needed to modify a few things:

### make sure there's an `rstudio` user on the system:

```shell
sudo useradd rstudio
sudo passwd rstudio  # enter some password
sudo mkdir /home/rstudio
sudo chown -R rstudio /home/rstudio/
```

caution: creating this linux user might mess with RStudio. I have no idea. 

### add the env variable

```
sudo systemctl edit rstudio-server
```

add:
```shell
[Service]
Environment="USER=rstudio"
```

### edit the command for the systemd service

```shell
# here, add --auth-none 1 on the ExecStart line:
sudo vi /lib/systemd/system/rstudio-server.service
# load these changes
sudo systemctl daemon-reload
# restart rstudio server
sudo systemctl restart rstudio-server
# check logs, if there's an issue
sudo systemctl status rstudio-server
```
