### ISSUE TITLE
Add document tab context menu

### ISSUE THREAD

**Issue by flying-sheep** [rstudio/rstudio#1664]
Actions similar to <kbd>Close</kbd>, <kbd>Close All</kbd>, and <kbd>Close All Except Current</kbd> would make sense in a document tab’s context menu. I always find myself right-clicking tabs and expecting it.

Since <kbd>Close</kbd> and <kbd>Close All Except **This**</kbd> would refer to the right-clicked tab in the context menu, only <kbd>Close All</kbd> would reuse the `closeAllSourceDocs` action.

**Comment by kevinushey** [comment]
A similar request: https://support.rstudio.com/hc/en-us/community/posts/115007964793-Feature-suggestion-Copy-path-on-Source-tab-right-click-menu

---

I would like to suggest a feature to add to the right-click menu of the tabs in the Source panel, i.e. the list of opened scripts. This right-click menu currently only contains "Reload" and "Inspect" (like the right-click menu on the tabs of all the other panels). 

It would be nice to have the option to "Copy file name" and "Copy full path", so I could paste this into my code (for use in source() commands). Currently, I have to to navigate to the source file outside of R to copy long file names, which is a minor nuisance.

Thank you!

**Comment by kevinushey** [comment]
It would also be useful to have the ability to rename files within such a context menu. See also: https://github.com/rstudio/rstudio/issues/2199

**Comment by jmcphers** [comment]
It might be possible to do what we want by intercepting the right-click and drawing our own menu. If not (and/or we only want to do this for desktop), QtWebEngine supports custom context menus. We already do some customization here:

https://github.com/rstudio/rstudio/blob/98a8b90a7a7ebc6fbc5fd9f4260b383fddb8f0ad/src/cpp/desktop/DesktopWebView.cpp#L143-L165

**Comment by kevinushey** [comment]
We also do this for the Git pane, directly from GWT:

<img width="341" alt="screen shot 2018-02-14 at 6 23 50 pm" src="https://user-images.githubusercontent.com/1976582/36237975-45a91dee-11b4-11e8-89ec-c494a2d65a74.png">

It looks like we could likely just add a GWT ContextMenuHandler as required?

https://github.com/rstudio/rstudio/blob/03c7e55302581d3552eb68412ebf928f340abe88/src/gwt/src/org/rstudio/core/client/widget/MultiSelectCellTable.java#L119-L125

**Comment by kevinushey** [comment]
Also, from https://community.rstudio.com/t/sort-source-file-tabs-alphabetically-in-ide/5760, a request to sort document tabs (e.g. alphanumerically)

**Comment by gtritchie** [comment]
Implemented via #8375

**Comment by valerie-rstudio** [comment]
### Verify Failed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1522
    OS Version      :  mac OS 11.1
    R Version       :  4.0.2

### Failure Points / Repro Steps
Close All Others context menu option fails to function as expected for documents in Source Editor.
1. Open multiple documents in original Source Editor Pane.
2. Click View -> Panes -> Add Source Column, and open multiple documents in the secondary Source Editor Column.
3. Left-click on a document in the secondary column to bring it into focus.
4. Right-click on any of the document tabs in the original column and choose Close All Others
5. **Expected:** All documents except the one that you right-clicked on should close.
6. **Actual:** All documents close.

### Successful Verification Points
- Verified that the Close context menu option functions as expected for Terminal and Jobs tabs. Also functions as expected for various document types both in and out of focus and across multiple columns for the Source Editor.
- Verified the Close All context menu option functions as expected for various document types both in and out of focus and across multiple columns for the source editor.

**Comment by gtritchie** [comment]
Looking into it, thanks for the detailed notes.

**Comment by gtritchie** [comment]
Opened a new issue for the identified failure (#8855), closing this to mark the overall creation of context menu as completed.

**Comment by dmurdoch** [comment]
There was a pointer to this issue from https://community.rstudio.com/t/sort-source-file-tabs-alphabetically-in-ide/5760 a few years ago.  However, it seems that request for a way to sort the tabs never made it into the context menu.  Is there somewhere else where suggestions for this new context menu should be posted?

**Comment by jmcphers** [comment]
@dmurdoch Yup, just file them as a new issue.
