### ISSUE TITLE
bug: no header resizing when resizing column width in View in version 1.1.383

### ISSUE THREAD

**Issue by BenoitLondon** [rstudio/rstudio#1665]
when viewing a data.frame with long column names and short content, I try to resize columns witht he mouse but the headers do not get resized messing the all view as headers are not above the corresponding column anymore.

for example if you try to make columns 1 3 and 5 smaller in this view the rendering is messed up:

```
View(data.frame(
      a_quite_long_name = LETTERS, 
      b = LETTERS, 
      very_long_name = LETTERS, 
      c = LETTERS, 
      another_very_long_name = LETTERS,
      e = LETTERS))
```

![image](https://user-images.githubusercontent.com/7107193/32004358-7d863d3c-b999-11e7-83bc-8bb670f6a549.png)

**Comment by kevinushey** [comment]
For reference, here's the behavior I see:

![data-viewer-resize](https://user-images.githubusercontent.com/1976582/32024146-63cabcaa-b990-11e7-88bb-7e4304a42815.gif)
