### ISSUE TITLE
Discontinuous pointer behavior in RStudio IDE

### ISSUE THREAD

**Issue by adatum** [rstudio/rstudio#1666]
The pointer in RStudio is typically an arrow icon/symbol, but when it moves over an actionable item, such as the x to close a tab or an icon that is clickable, it turns into a hand icon/symbol. 

The problem is that, new to RStudio version 1.1.383, when the hand icon appears, it is positioned several pixels over from where the arrow pointers tip would be expected, making it seem the pointer has jumped.

Arrow pointer:
![pointer](https://user-images.githubusercontent.com/9773655/32010666-803cc3d4-b980-11e7-9585-55068cce7e10.png)
When the above arrow pointer is moved about one pixel to the right so that it would be positioned over the x to close the tab, it turns into a hand icon with the fingertip suddenly on the right side of the x.

**Comment by jmcphers** [comment]
This issue is currently being tracked here: https://github.com/rstudio/rstudio/issues/1659

**Comment by adatum** [comment]
Thanks. Didn't see that. Hope it gets fixed soon!

**Comment by dfalty** [comment]
Verified fixed 1.2.158.
