### ISSUE TITLE
segfault on 'Run All Chunks' w/Rcpp chunk that fails compilation

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1668]
Given this document:

````
```{Rcpp}
std::string x = 1;
```

```{r}
print(1)
```
````

If you try executing Run All, the IDE gets into a weird state where the Notebook execution engine believes that the following R chunks is ready and waiting to be executed. Attempting to do other stuff in the Notebook eventually triggers a segfault.

![screen shot 2017-10-25 at 12 00 08 pm](https://user-images.githubusercontent.com/1976582/32017622-206e2d98-b97c-11e7-8c1a-861825d9dfb1.png)

(repro'ed on macOS Desktop, v1.1.383)

**Comment by jmcphers** [comment]
I think there's an issue wherein certain kinds of errors can cause the chunk execution to abort, but in such a way that the cleanup doesn't happen. I'll take a look.

**Comment by jmcphers** [comment]
Backported to 1.1 here: 25f09e743ce2c0cb50356550369105a6d848e90d

**Comment by dfalty** [comment]
Verified fixed 1.1.393.
