### ISSUE TITLE
Add the Nord theme from @arcticicestudio

### ISSUE THREAD

**Issue by vabatta** [rstudio/rstudio#1671]
As the title says, I propose to add the theme present at https://github.com/arcticicestudio/nord to the catalogue.

**Comment by jmcphers** [comment]
You're welcome to submit a pull request for this; we have taken a number of user-contributed themes in the past. See here for examples:

Dracula - https://github.com/rstudio/rstudio/pull/1453

Material - https://github.com/rstudio/rstudio/pull/748

**Comment by jmcphers** [comment]
We won't ship this theme in the box, but it's now easy to install using the rsthemes package.

https://github.com/gadenbuie/rsthemes
