### ISSUE TITLE
[1.2.*, Linux] Build tools regression

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/rstudio#1674]
Several options disappeared a while back on the 1.2.* series:

![screenshot from 2017-10-26 11-44-27](https://user-images.githubusercontent.com/673121/32065862-9119c558-ba43-11e7-90ec-f3bf41b1c725.png)

![screenshot from 2017-10-26 11-44-54](https://user-images.githubusercontent.com/673121/32065872-9a5f0786-ba43-11e7-9ec2-22f95fc886a0.png)

Would be nice to get the easy 'check' option back...   

Ubuntu 17.04, using both server and desktop from the 'newer' options respectively.  Can provide details on the .deb packages used -- bug hit me on three different machines.

**Comment by dfalty** [comment]
Thanks for the bug report! I can reproduce this on the latest Mac build 1.2.137.

**Comment by eddelbuettel** [comment]
@jmcphers @kevinushey @dfalty Thank you -- just installed a new build, and the world is good again.  Or, at least this little corner...

**Comment by dfalty** [comment]
Verified fixed 1.2.150.
