### ISSUE TITLE
Cannot log out when using RStudio Server behind a reverse proxy

### ISSUE THREAD

**Issue by jstaf** [rstudio/rstudio#1675]
The latest version of RStudio Server (open source) cannot log out successfully when hosted behind a reverse proxy. 

When tested with the [recommended Apache config](https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy), attempting to log out takes the user to the `/auth-sign-out` page with nothing on it but `Missing or incorrect token.`. The user is unable to logout without clearing cookies or redirecting to the sign up page as described in: https://github.com/rstudio/rstudio/issues/1538

This is using the `rstudio-server-rhel-1.1.383-x86_64.rpm` on Centos 7.

**Comment by jmcphers** [comment]
This is fixed in #1538. We'll include it in a 1.1 patch release or the upcoming 1.2. Thanks for reporting!

**Comment by jstaf** [comment]
Good to hear! I tried building the newest RStudio Server from source just now with the fixes in it (I guess I just really wanted to try out the new terminal...), but kept running into the same issue. Is there a file that persists between RStudio Server upgrades that I need to delete/reset? (I just did a `yum remove rstudio-server`, built the package, then installed the .rpm built from source).

**Comment by jstaf** [comment]
Ok found the issue, got caused by this line in my Apache config:

`Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure`
