### ISSUE TITLE
Check Spelling throws error when using symbols in markdown

### ISSUE THREAD

**Issue by colinbrislawn** [rstudio/rstudio#1677]
While editing a markdown block inside of a .rmd file, running Check Spelling produces this error:
![screen shot 2017-10-26 at 1 58 29 pm](https://user-images.githubusercontent.com/10355152/32076811-1385b72e-ba56-11e7-8507-7e3e870b6e64.png)

This error can be dismissed (Rstudio does not crash), and the extra symbol removed.

Here is the text in question:
```
This text works fine: beta
This causes an error: β
```

Let me know if there is any other information I can provide. If this is a known issue, feel free to close it.

**Comment by jmcphers** [comment]
It's a known issue; we have fixed it in RStudio 1.2 (see the [release notes](https://github.com/rstudio/rstudio/blob/master/NEWS.md)).
