### ISSUE TITLE
Fold states are saved on file close and restored on file open

### ISSUE THREAD

**Issue by Ploulack** [rstudio/rstudio#1682]
As of Rstudio Version 1.1.383 this feature is not supported where a file is always loaded in the IDE with all fold states as expanded, unless it's the project itself that was closed / opened with the file opened.

@kevinushey was of the opinion that this was a worthy request [in this community thread](https://community.rstudio.com/t/wish-store-state-of-collapsible-code-tree/492/10).

**Comment by ajmcoqui** [comment]
Another vote for this: ticket 24350
