### ISSUE TITLE
[Feature request] Customize/Disable zooming keybindings

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#1683]
I found two hidden keybindings within Rstudio.    "Ctrl +  -  "  and  "Ctrl +  Shift  +   +  " to reset the zoom level.  Hope to be able to disable them or enable the end users to customize it. It could be very annoying when they are accidentally called.  E.g. the "Alt+ -" is my most frequent used keybinding, but  "Ctrl +  -  "  is so close to that and I hit it by accident sometimes.

**Comment by lpuettmann** [comment]
Is there any update to this? I'm having the same issue frequently.
