### ISSUE TITLE
Git branch information deleted

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#1689]
Using rstudio 1.1.383 on windows

I can't give too many reproducing details, so this may not be very useful.

Last night I was working from rstudio and before going to sleep I committed to git (using rstudio's git tab). Then I closed rstudio. This morning I opened rstudio and continued working and when I wanted to commit I noticed that I'm no longer on a branch and branch information has been deleted. I tried restarting rstudio and I still wasn't in a proper git repo for some reason. I haven't debugged any further, and I already re-made the repo so I can't give any more information. This has never happened to me before, so I just wanted to logged my issue in case it happens to others too with this version

**Comment by kevinushey** [comment]
Although it's possible, it seems very unlikely that this is an RStudio issue. By any chance does this project live within e.g. a Dropbox folder (or other auto-synchronizing cloud storage folder)?

**Comment by daattali** [comment]
No, it's in a regular vanilla folder. I wouldn't want any of you to dig
into it, if others experience the same then this can be the place to gather
info, otherwise you can close the issue if noone else reports it

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by jmcphers** [comment]
Hasn't been seen or reported by anyone else in a couple of years, and no more details here, so not much to go on here. Closing, but feel free to reopen if you seen this again.
