### ISSUE TITLE
crash when restarting R session while using network drive

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1690]
https://community.rstudio.com/t/new-rstudio-crashes-when-restarting-r-session-on-network-drive/2109

---

I’ve been using the new RStudio (Version 1.1.383) on a Mac (Sierra Version 10.12.6) for the last 2 days and it crashes when I try to restart the R session. Here is the sequence of events:

Mount a network drive
Open RStudio
Open RStudio Project from the network drive
Do work
Press shift-command-f10 to restart the R session
Crash…
Here is the error message:

    ERROR system error 45 (Operation not supported) [lock-file=/tmp/.Rproj.user/B6148186/sources/s-37259BA1/lock_file]; OCCURRED AT: virtual rstudio::core::Error rstudio::core::AdvisoryFileLock::acquire(const rstudio::core::FilePath &) /Users/rstudio/rstudio/src/cpp/core/file_lock/AdvisoryFileLock.cpp:137

It has something to do with being on a network drive because when I do the same thing on my local drive I have no problem with restarting R. I’ve been using the same workflow for a long time and never had this issue with prior RStudio versions.

---

The user also reported that an SMB network mount is being used in this case.

**Comment by kevinushey** [comment]
I've reproduced this by setting up an Amazon AWS instance with a Samba share, and mounting that directory locally. Working on an RStudio project in that directory and attempting to restart triggers a crash for me with RStudio v1.1.383, but not with v1.0.153.

![screen shot 2017-10-30 at 11 30 47 am](https://user-images.githubusercontent.com/1976582/32188731-dc3370aa-bd65-11e7-8bf7-2726e01d8a92.png)

It looks like the lockfile associated with the source database of the project is not properly cleaned up when the R session is closed:

```
kevin@cdrv:~/samba/.Rproj.user
$ find . -name "*lock*"
./878DCAD6/sources/s-3790cd6e/lock_file
```

This is also true on RStudio v1.0.153, but in that case, the IDE then creates a whole new session rather than bombing out early on. This implies that the 'sources' folder of the project starts bloating (as old sources are never cleaned out), but at least no crash occurs. For example, this is what I see after opening a project living on a Samba share, opening a couple documents, and then restarting it 5 times, using RStudio v1.0.153:

```
kevin@cdrv:~/samba/.Rproj.user
$ tree
.
├── 3B18B23A
│   ├── ctx
│   ├── pcs
│   │   ├── files-pane.pper
│   │   ├── source-pane.pper
│   │   ├── windowlayoutstate.pper
│   │   └── workbench-pane.pper
│   ├── persistent-state
│   ├── presentation
│   ├── profiles-cache
│   ├── rmd-outputs
│   ├── saved_source_markers
│   ├── sdb
│   │   ├── per
│   │   │   ├── t
│   │   │   └── u
│   │   ├── s-57767CB0
│   │   │   ├── 16B20655
│   │   │   ├── CB3ECB41
│   │   │   └── lock_file
│   │   ├── s-5F7F0F32
│   │   │   └── lock_file
│   │   ├── s-6ECE3A93
│   │   │   ├── CB3ECB41
│   │   │   └── lock_file
│   │   ├── s-96270160
│   │   │   ├── 16B20655
│   │   │   ├── CB3ECB41
│   │   │   └── lock_file
│   │   ├── s-CF64A67E
│   │   │   └── lock_file
│   │   └── s-E9F9C12D
│   │       ├── 16B20655
│   │       ├── CB3ECB41
│   │       └── lock_file
│   ├── session-persistent-state
│   ├── viewer-cache
│   └── viewer_history
└── shared
```

Not yet sure what would lead to RStudio failing to clean up these lock files + sources...

**Comment by kevinushey** [comment]
Also worth noting that mounting the folder from Finder (with <kbd>Cmd + K</kbd>) mounts files so that only the active user has write permissions; group and world permissions are unset.

**Comment by johnhowa** [comment]
Any progress on this front so far? I've got a similar problem, with rstudio crashing while opening and closing files. The [log](https://pastebin.com/AgPpvtuW) file shows plenty of similar errors. [Diagnostic](https://pastebin.com/vTqFXCP8)

**Comment by kevinushey** [comment]
Sorry; we haven't been able to tackle this one yet (but it's on our list for a v1.1 patch release). If you need to work with networked filesystems on macOS, you can switch back to RStudio v1.0 in the interim: https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio

**Comment by johnhowa** [comment]
Thanks; I've been able to avoid the issue by avoiding the use of Projects. I'm looking forward to the patch!

**Comment by jmcphers** [comment]
Backported to 1.1 in 0e808877de5747df89b691873c52968981a4a417.
