### ISSUE TITLE
Unable to establish connection with R session

### ISSUE THREAD

**Issue by weiyangtham** [rstudio/rstudio#1692]
![image](https://user-images.githubusercontent.com/15363607/32187980-e140a6be-bd7c-11e7-98c4-87e90e4dbfae.png)

I've been having the problem shown in the image with a particular Project. I can't tell what's triggering it. It happens before I even load a dataset or run any code beyond standard things like loading a package. The entire project just stalls and the dialog boxes much later (in about an hour)

Other projects on the same computer don't seem to have the same problem, even when they're open at the same time. I've attached a log file and a diagnostics report. Thanks!

[rsession-weiyangtham.log](https://github.com/rstudio/rstudio/files/1428292/rsession-weiyangtham.log)
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1428302/diagnostics-report.txt)

**Comment by dfalty** [comment]
Are you able to share the failing project for review? Or maybe a subset of the project that still fails?

**Comment by weiyangtham** [comment]
I can share the code [https://github.com/weiyangtham/spillovers_studysections/blob/master/scripts/author_general_cossim.R](https://github.com/weiyangtham/spillovers_studysections/blob/master/scripts/author_general_cossim.R)

The particular script I linked to was probably the last one I had made major changes to before the problem started. Not sure if it's relevant but I've been trying to do some parallelisation recently

**Comment by weiyangtham** [comment]
![screen shot 2017-10-30 at 5 19 11 pm](https://user-images.githubusercontent.com/15363607/32196320-9ab53c18-bd96-11e7-9c51-e49c62ff7ec2.png)

I've also just started getting a new type of error message (see image above). The project was open but I was not running anything on it

**Comment by kevinushey** [comment]
It's possible that the R session is crashing when attempting to run your code. Do you see any issues if you try running this code from an R session launched in a terminal, outside of RStudio?

**Comment by weiyangtham** [comment]
I can still work from terminal. In addition, the problem occurs even when I've just started a new RStudio session and haven't run any code.

**Comment by kevinushey** [comment]
Do you have the `data.table` package installed, or are you using it in your project? If so, you might want to try updating it with e.g. `install.packages("data.table")`. Some users have reported crashes when using a recent-ish version of the `data.table` package.

Otherwise, you might want to try [resetting your desktop state](https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State).

**Comment by weiyangtham** [comment]
updating `data.table` seems to have done the trick. Thank you!

**Comment by hoplit11** [comment]
In windows 10 go to security >firewall and network protection> allow an application thru the firewall >change configuration >Allow other aplication> put C:\ProgramFiles\RStudio\bin\rstudio.exe and select public and private necwork. >add >accept and restart the computer.

It work for me using RStudio-1.3.938.exe sorry for my bad english i hope it works for all of you.
