### ISSUE TITLE
Add Mercurial (Hg) support to RStudio version control interface

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1694]
Currently, the RStudio version control interface supports Subversion and Git. These are the most popular version control systems in R shops, but there are some teams which have standardized on [Mercurial](https://www.mercurial-scm.org/), which, like Git, is a distributed SCM.

**Comment by ignacio82** [comment]
Is this in the roadmap?

**Comment by jmcphers** [comment]
It is not on the roadmap for the near future.
