### ISSUE TITLE
Suppress session suspension when external pointers are present in the global environment

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1696]
R objects can include external pointers. When these are present in the global environment, RStudio should suppress the automatic session suspension which would ordinarily occur; the external pointers cannot be restored, so when the session resumes after suspension, those objects which contain them will not work, and may cause crashes or instability.

**Comment by jmcphers** [comment]
Backported to 1.1 here: b3279554312f713f97c1f818a27cf5caa4bec7a9

**Comment by dfalty** [comment]
Verified 1.1.393.

**Comment by dfalty** [comment]
Verified this again on 1.1.419.
