### ISSUE TITLE
[enhancement] Use SI or IEC binary units in environment pane

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#1704]
In the environment pane, object sizes are displayed using the "legacy" R standard.

For instance:
```r
a <- 1:1e6
```
![rstudio_environment_pane_bug](https://user-images.githubusercontent.com/22758616/32328728-2b7718a2-bfdb-11e7-98a5-82d3696762ae.PNG)

`3.8 Mb` is very misleading since `b` usually stands for bits, not bytes.

The latest R versions support SI units (since this commit: https://github.com/wch/r-source/commit/293426bff7113a642b501e9b8e08fcf97de1b8c8), it would be nice to use them. (or maybe IEC units)

**Comment by polmes** [comment]
Couldn't agree more! @Qjammer and I have created PR #4809 to address this issue. In the future, it would be nice if this was turned into a user setting, so that one can change between legacy, SI, and IEC standards for unit representation.

**Comment by jmcphers** [comment]
Closed in https://github.com/rstudio/rstudio/pull/4809.
