### ISSUE TITLE
Website:  Broken link

### ISSUE THREAD

**Issue by grabear** [rstudio/rstudio#1709]
There's is a broken link at https://www.rstudio.com/products/shiny/shiny-user-showcase/

The [rcharts gallery](http://rcharts.io/gallery/) link at the bottom has an expired domain.

**Comment by jmcphers** [comment]
Tracked here: https://github.com/ramnathv/rCharts/issues/619

This is for reporting issues with the IDE; to discuss the website we recommend the community forum (https://community.rstudio.com/).

**Comment by grabear** [comment]
Ok.  I'll post to the community and then, add a link here.  @ramnathv

**Comment by grabear** [comment]
Here's the link to the community topic:
https://community.rstudio.com/t/r-studio-website-broken-link-to-rcharts/2428
