### ISSUE TITLE
Plot export image resolution option

### ISSUE THREAD

**Issue by bmreilly** [rstudio/rstudio#1714]
The default resolution for plots exported as images in RStudio is too low for publication quality graphics.  I was wondering if it is possible currently (or if this feature could be added) to adjust the resolution of images during export from the Rstudio plot viewing window.  

I could see how allowing the plot to render in the viewing window at high resolution would be computationally unnecessary, but it would be extremely useful to have a resolution option for the final exported/saved file with the dimensions as sized in the export window.

**Comment by jmcphers** [comment]
Related to https://github.com/rstudio/rstudio/issues/4422, and could possibly be addressed with the same change.

**Comment by mikebessuille** [comment]
This should be retested, on Mac, Windows, and Linux.  Tim finds this to be working now.

**Comment by timtmok** [comment]
This is how the dialog looks today on Mac:

1000x1000
![image](https://user-images.githubusercontent.com/9591545/221646142-d44e8876-33bb-47ce-b768-95af601d640f.png)

200x200
![image](https://user-images.githubusercontent.com/9591545/221646283-84184bb1-5778-44e8-a69e-3a831064fc57.png)

2000x2000
![image](https://user-images.githubusercontent.com/9591545/221646361-1b9bb259-a33a-46b8-8d80-cd58f2f93e79.png)

It seems that the preview doesn't handle the image very well if it exceeds the IDE's window size. I had my window at half my screen width and the preview maxed out at 1820 (just under half my screen width). Maximizing the IDE allowed for a 2000px width and rendered a preview until exceeding 3740px.

**Comment by jonvanausdeln** [comment]
I am seeing similar behavior as @timtmok on Windows 11.  The max resolution for the previews is limited by the size of the IDE.  However, the image still exports correctly.  

You can change the resolution by the `Width` and `Height` values in the dialog, or by dragging the lower left corner to the desired size.

@bmreilly , does this satisfy what you were looking for as an enhancement?

**Comment by jonvanausdeln** [comment]
I'm closing this as I think the original ask is covered in current release.  IF not, we can re-open as needed.
