### ISSUE TITLE
Export button does not work after re-running code chunk

### ISSUE THREAD

**Issue by hdykiel** [rstudio/rstudio#1715]
Minimum viable example:
Run an RMarkdown script that exports a CSV file. In the files pane, select the CSV file and click export. The file exports, as it should. Re-run code chunk in RMarkdown document. CSV file is already selected in the files pane. Select the export option --> Nothing happens.

I have a screen recording that shows me going through each of these steps, message me if you'd like to see it.

Thanks,

Hadrien

**Comment by jmcphers** [comment]
Even more minimal:

1. `System("touch foo.csv")`
2. Select `foo.csv` in files pane
3. `System("touch foo.csv")`
4. Attempt to export `foo.csv`

Nothing happens.

**Comment by dfalty** [comment]
Verified fixed 1.2.153-3.
