### ISSUE TITLE
ansi bold text is too wide

### ISSUE THREAD

**Issue by patperry** [rstudio/rstudio#1721]
On the latest RStudio release, text in ANSI bold is wider than normal text:

<img width="358" alt="screen shot 2017-11-06 at 7 17 30 pm" src="https://user-images.githubusercontent.com/43450/32470653-31ca560c-c327-11e7-9308-679dec8b94b1.png">

This causes issues with alignment if, for example, you bold table headings like the following:
<img width="494" alt="screen shot 2017-11-06 at 7 19 39 pm" src="https://user-images.githubusercontent.com/43450/32470719-7f42f5ec-c327-11e7-9e6a-c8e966a13666.png">

On Mac OS, RStudio Version 1.1.38

**Comment by patperry** [comment]
Also ANSI Faint/Dim isn't supported :(

<img width="358" alt="screen shot 2017-11-06 at 7 31 59 pm" src="https://user-images.githubusercontent.com/43450/32471054-6bee9666-c329-11e7-9c32-1831336ba9bd.png">

**Comment by gtritchie** [comment]
Support for some ANSI sequences in the RStudio console is a new feature in version 1.1.

If the current issues you are reporting are causing problems, you can disable this for now: Tools / Global Options / Code / Display:
![2017-11-06_16-38-18](https://user-images.githubusercontent.com/10569626/32471213-fdd00696-c310-11e7-8e23-e1a7854b9aff.png)

**Comment by patperry** [comment]
Thanks for the quick response. This isn't causing me trouble *per se*, it just doesn't look as nice as iTerm2 or Mac OS terminal:

<img width="671" alt="screen shot 2017-11-06 at 7 52 35 pm" src="https://user-images.githubusercontent.com/43450/32471632-561bdec2-c32c-11e7-99ae-075f53ef0975.png">

**Comment by hadley** [comment]
The most likely explanation is that you're using different fonts in iTerm and RStudio, and in RStudio the font doesn't have a bold version with the same metrics as the unbold version.

**Comment by patperry** [comment]
Nope. Correct alignment with Monaco, Courier, and Source Code Pro in Terminal.

I think iTerm and Terminal override the font metrics. The do this so that, for example, emoji and Asian characters are exactly 2 spaces wide. (These characters are narrower in RStudio)

**Comment by hadley** [comment]
Ah so the bug is in the other terminals for not respecting font metrics 😉 I use a font with proper bold metrics and it looks fine. I suspect there’s unfortunately no way for RStudio to override the font metrics because the rendering is done by WebKit (although I wonder if there’s a way to create a webfont on the fly with forced metrics)

**Comment by patperry** [comment]
That's too bad. Probably should either change the default RStudio font or else not use bold to style tibble column headings then. CC @krlmlr 

<img width="560" alt="screen shot 2017-11-08 at 6 55 38 am" src="https://user-images.githubusercontent.com/43450/32547958-f4be5426-c451-11e7-9112-e5349a8ce6fc.png">

**Comment by krlmlr** [comment]
Things look well enough on my Ubuntu system, though.

**Comment by klmr** [comment]
How does VS Code (and presumably Atom) do this? It’s based on WebKit as well, and aligns bold fonts “correctly” (tested with Monaco).

That said, I’m not sure that it’s worth fixing “incorrect” font metrics.

**Comment by wch** [comment]
To make it easier to cut and paste, here's the code to reproduce the issue:

```R
cat("\033[1m1234567890\n\033[0m1234567890\n")
```

Here's what it looks like for me with Monaco (which I think is the default on Mac):

![image](https://user-images.githubusercontent.com/86978/34585531-b6490d30-f165-11e7-969c-1abb8e1689e7.png)


Alignment is correct when I use Menlo-regular:

![image](https://user-images.githubusercontent.com/86978/34585496-90b79a14-f165-11e7-958e-28161e8b327f.png)

**Comment by patperry** [comment]
If you want East Asian characters and emoji to have predictable widths, then you need to override the font metrics. Compare, e.g. the following output from Mac OS Terminal:

<img width="649" alt="screen shot 2018-01-04 at 5 01 56 pm" src="https://user-images.githubusercontent.com/43450/34586212-098be4c6-f171-11e7-86cb-b4e33384b679.png">

With the same command in RStudio:

<img width="570" alt="screen shot 2018-01-04 at 5 02 49 pm" src="https://user-images.githubusercontent.com/43450/34586238-266eb8b6-f171-11e7-97f0-7668e39052c0.png">

(Both using Menlo-Regular)

In RStudio, the characters have widths between 1 and 2 spaces each, so it's difficult (impossible?) to align the headers.

(Full code available at http://corpustext.com/articles/chinese.html )

**Comment by krlmlr** [comment]
@patperry: What would it need to support overriding font metrics in RStudio?

**Comment by patperry** [comment]
I'm not sure how Terminal.app and macvim do this. I'd think that part of the solution would be (a) determine which sequences of codepoints represent a single grapheme; and (b) determine the width of the grapheme. This is more difficult than it seems, especially with emoji:

```{r}
# how many graphemes? what width?
cat("\U1F469\U200D\U2764\UFE0F\U200D\U1F48B\U200D\U1F469")
```

There are some Unicode annexes that are useful here:

 + East Asian Width: http://unicode.org/reports/tr11/ 
 + Unicode Text Segmentation, "Grapheme Cluster Boundaries" http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries

I haven't found anything in the Unicode standard about emoji width, but it seems like most should have width 2.

I wrote some stand-alone C code that implements these procedures: https://github.com/patperry/utf8lite . This forms the basis for `utf8::utf8_width`.

**Comment by gtritchie** [comment]
The originally reported issue (bold text is too wide) is working in RStudio 1.2.5019 on Mac. Just tried and got this (with default Monaco font). Probably due to our upgrade from webkit to chromium in 1.2:

<img width="359" alt="2019-11-12_16-04-04" src="https://user-images.githubusercontent.com/10569626/68721146-50493700-0566-11ea-8a55-1a7cd5dd231d.png">

The other issue that got attached to this (width of East Asian characters) still exhibits the problem, so I'll leave this issue open due to that.

**Comment by gtritchie** [comment]
FYI, here's what I see in 1.3.599 on macOS desktop:

<img width="912" alt="2019-11-12_16-20-02" src="https://user-images.githubusercontent.com/10569626/68721759-5a6c3500-0568-11ea-8f01-e1ddfca7ef90.png">
