### ISSUE TITLE
"Copy To" problems

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#1722]
Two observations about “Copy To” in the Files Pane.

1. The extension, e.g., `.R` or `.yml`, of the file I am copying doesn’t show in the “Choose Destination” dialog. But I can tell that implicitly it is still included. Can that be made visible for clarity?
2. If I am copying onto an existing file, I get a pop-up that the file already exists. If I say “Replace”, I get an error “File exists” and the copy does not happen.

Version 1.1.383

**Comment by dfalty** [comment]
Hey @jennybc, you are on a Desktop version correct?

1. The extension shows up correctly on RStudio Server but on Desktop versions, there is no extension (tested on windows and mac). 
2. I get this as well on server and desktop versions and was able to reproduce on the latest 1.2.158.
![image](https://user-images.githubusercontent.com/15237845/32508319-8b2d0cc0-c3af-11e7-832e-2681cc8fc3ac.png)

**Comment by kevinushey** [comment]
Is this a regression relative to v1.0?

**Comment by jmcphers** [comment]
It isn't (Copy To is new in 1.1).

**Comment by jennybc** [comment]
Yes I am using a Desktop version.

**Comment by jmcphers** [comment]
I've just fixed the "File exists" error. Thanks for catching that!

Re: showing extensions for clarity, that's an OS-level preference. Open Finder and check the "Show all filename extensions" preference and you should start seeing them in RStudio's file dialogs.

![image](https://user-images.githubusercontent.com/470418/32524435-83d697fa-c3d4-11e7-95b4-3253007dad18.png)

**Comment by jennybc** [comment]
Hey thanks for the tip re: exposing file extensions on Mac OS!

**Comment by dfalty** [comment]
Verified fixed 1.2.160

**Comment by jmcphers** [comment]
Marking as a patch candidate since Copy To is a new 1.1 feature.

**Comment by jmcphers** [comment]
Backported to 1.1 here: 4975cda3387b3ec6600eca03d6a80b0e8356b4ec
