### ISSUE TITLE
Terminal not detecting full-screen mode correctly

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1725]
1.1.383, any platform, desktop or server

- Start a terminal in RStudio
- Run a full-screen program such as vim or tmux
- Tools -> Terminal -> Terminal Diagnostics

**Expect**
Full screen: 'client=**true**/server=false'

**Actual**
Full screen: 'client=**false**/server=false'

This is a regression from taking xterm.js 2.9.2: https://github.com/rstudio/rstudio/pull/1444 late in the 1.1 release. Problem not in xterm.js, but in a change in how RStudio code needed to detect alt-buffer. Easy one-line fix, coming shortly.

This has a several visible consequences, one of them is breaking https://github.com/rstudio/rstudio/pull/1437:

- Run tmux, open multiple panes within it
- Ctrl+L

**Expect**: terminal should recognize it is running a full-screen program, and pass the Ctrl+L to that program, so instead of clearing the entire terminal should clear just the active pane.

**Actual**: ctrl+L is treated as clear-entire-terminal, messing up tmux display

Another is that when running a full screen program, the Stop Sign and Clear icons are supposed to be hidden on the terminal toolbar, but they are still being shown.

**Comment by jmcphers** [comment]
Backported to 1.1 here: 59306a4098d6e4801497eecf871121b49278fde3

**Comment by ronblum** [comment]
Confirmed using vi, tmux, and hangman.
