### ISSUE TITLE
Linux Installation Force Restarts the System without Warning

### ISSUE THREAD

**Issue by chrisconlan** [rstudio/rstudio#1728]
This RPM download:
RStudio 1.1.383 - Fedora 19+/RedHat 7+/openSUSE 13.1+ (64-bit)

After running `sudo rpm -Uvh rstudio-1.1.383-x86_64.rpm`, on RHEL 7.4, very minimal installation output was shown, and the computer was force-restarted. The installation succeeded, but I was not notified of this.

**Comment by jmcphers** [comment]
Sorry this happened, but we have no idea what could have caused it and have never heard of it happening to anyone else (it's been > 2 years now). It's probable something else triggered the restart while RStudio was installing.
