### ISSUE TITLE
Horizontal lines over help pane

### ISSUE THREAD

**Issue by michaellevy** [rstudio/rstudio#1730]
I'm getting horizontal traces over my help pane in the latest version of R Studio. It's only the help pane, moves with the help pane if it's in a different position, and only appears when scrolling below what fits in the window originally. Happens reliably on both laptop display and external monitor.

<img width="802" alt="rstudio_issue" src="https://user-images.githubusercontent.com/4422055/32580519-ea5ef1c4-c4a2-11e7-88ed-4237b33c6cdf.png">

Version 1.1.383 on OSX 10.12.6 on 15" 2016 MBP. `sessionInfo()`:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2  rsconnect_0.8.5 tools_3.4.2     yaml_2.1.14  
```

**Comment by dfalty** [comment]
Hey @michaellevy I can't reproduce this on 1.1.383. Does this happen to you all the time? Also, can you share what options you have under Appearance? Tools -> Global Options -> Appearance

**Comment by michaellevy** [comment]
Hi @dfalty -- I'm on different external displays today than yesterday, and today it's less frequent but  still happens. Yesterday it was all the time. I can't find a pattern in when it's happening today. Appearance settings: Theme = modern, Font = Monaco, Font size = 10, Editor theme = Pastel on Dark

**Comment by jmcphers** [comment]
via @jennybc:

>  I get these horizontal stripes alot when viewing help in RStudio. Once they’re there, they persist. Reloading the page resolves it.

![image](https://user-images.githubusercontent.com/470418/32800731-fc7c785e-c92f-11e7-8f90-0e4327d89ac2.png)

**Comment by michaellevy** [comment]
Sadly refreshing doesn't get rid of the lines for me.

**Comment by jennybc** [comment]
I still get this multiple times per day. Currently on 1.1.446.

**Comment by michaellevy** [comment]
Interesting. I stopped getting this months ago. No idea why. Currently using 1.1.442

**Comment by gtritchie** [comment]
Be good to know if this is still an issue with RStudio daily builds 1.2.818 or newer, at least from the QtWebEngine angle. Most of the reports here were 1.1.x, which is pre QtWebEngine, so removing that tag from the issue.

**Comment by kevinushey** [comment]
@jmcphers fixed a similar bug with some DOM surgery in a recent commit (https://github.com/rstudio/rstudio/pull/3078). I wonder if that commit might alleviate the issue seen here, or if a similar technique could be used to fix up the scrollbars here too?

**Comment by jmcphers** [comment]
No reports of this since we did the QtWebEngine update, so presumably that resolved it!
