### ISSUE TITLE
Arch: Terminal not working

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#1731]
I'm on Arch Linux with KDE5 Desktop and every Rstudio build that I install from AUR has no working terminal for me. 
This means that the terminal does not start and is just empty. It makes no difference if I use `bash` or `zsh`.

I tested the following AUR packages, including one that builds directly from git:

* [rstudio-desktop-bin](https://aur.archlinux.org/packages/rstudio-desktop-bin/)
* [rstudio-desktop-git](https://aur.archlinux.org/packages/rstudio-desktop-git/)

Any idea what could be the problem here? I know that people using GNOME or MATE desktop have no issues. So I'm wondering if its related to KDE?

**Comment by gtritchie** [comment]
Don't know of a problem with KDE and the terminal; I will have to try it out and debug.

**Comment by stephensrmmartin** [comment]
I'm on the latest arch rev with rstudio-desktop-git, and it's working fine.
Although, it's using bash instead of zsh for some reason, and zsh is default everywhere else on my system.

**Comment by pat-s** [comment]
@stephensrmmartin are you also on KDE? so far this was the only difference to other users that I could see

**Comment by stephensrmmartin** [comment]
Yes sorry. I forgot to confirm that. I'm on kde/plasma.

**Comment by pat-s** [comment]
Alright. Well, hard to debug then for me. Happy to provide any logs that could help.

**Comment by pat-s** [comment]
I now tested it on another machine running Arch KDE and it works there. Strange...

**Comment by stephensrmmartin** [comment]
I am now having a similar problem, but with the server release.

I'm the maintainer of the AUR package for rstudio-server-git. For reasons unknown, the terminal no longer loads; it is blank.

What package(s) are used to show the terminal in rstudio? I am curious whether some arch update resulted in an incompatible version.

**Comment by stephensrmmartin** [comment]
Just tested an option. In global options -> terminal; disabling websockets fixes the terminal issue. If there's a general reason for why that is (e.g., a missing dependency), I'd be glad to fix it.

**Comment by gtritchie** [comment]
Websockets can be finicky on some systems. Try another scenario that uses Websockets in RStudio:

- File -> New Project -> New Directory -> Shiny Web Application
- Give it a name, click Create Project
- Click Run App in the editor toolbar
- You may have to install/update packages at this point

If it is working, you should see a second window with an interactive graph. If this is working then Websockets is generally working, so there's something terminal-specific for us to dig into. If not working, then it's a more general Websockets issue.

For the terminal, turning off WebSockets can increase typing lag significantly (especially on RStudio Server).

**Comment by stephensrmmartin** [comment]
Hm, my email reply didn't work. 

In sum - Shiny worked fine. It opened a new tab [since it's a server version] in firefox, and everything appeared to work as expected.

**Comment by stephensrmmartin** [comment]
Oddly enough; the desktop release is working for me (with websockets enabled for terminal); the server isn't. They are compiled essentially the same way though; build scripts linked below.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rstudio-server-git
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rstudio-desktop-git

**Comment by gtritchie** [comment]
There is a runtime difference between server and desktop terminal websockets; desktop always goes through ws://127.0.0.1, but on RStudio server the terminal websockets are proxied through the rserver process.

https://github.com/rstudio/rstudio/blob/69a22d1289046f0a11461b16e5c4065446a7797e/src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java#L214

**Comment by gtritchie** [comment]
Can you paste in contents of Tools/Terminal/Terminal Diagnostics **after** trying (and failing) to start a terminal with websockets turned on?

Also, is there anything in the JavaScript console after doing the same? E.g. in Chrome, the Developer Tools/Console tab.

**Comment by gtritchie** [comment]
Also, @stephensrmmartin, if you are willing, can you try rebuilding server with these lines of code commented out? This is just a hunch, but we've seen some terminal-failures with this IPV6 sniffing and are considering removing it altogether. If it turns out to be the issue you are seeing, too, that would be great to know.

https://github.com/rstudio/rstudio/blob/69a22d1289046f0a11461b16e5c4065446a7797e/src/cpp/session/SessionConsoleProcessSocket.cpp#L96-L104

**Comment by stephensrmmartin** [comment]
> Can you paste in contents of Tools/Terminal/Terminal Diagnostics after trying (and failing) to start a terminal with websockets turned on?
> 
> Also, is there anything in the JavaScript console after doing the same? E.g. in Chrome, the Developer Tools/Console tab or equivalent in other browsers.

## Terminal diagnostics

Global Terminal Information
---------------------------
Loaded TerminalSessions: 0

Terminal List Count: 0

## JS Debugger (firefox)
Firefox can’t establish a connection to the server at ws://hwkiller.dynet.com:7559/p/3084/terminal/E0BBD79E/.
hwkiller.dynet.com:7559:4678:28
WebSocket connect error, switching to RPC
hwkiller.dynet.com:7559:43:38
Unable to switch back to RPC mode

**Comment by gtritchie** [comment]
Interesting! RStudio terminal is supposed to automatically switch back to
the slower non-websocket-based RPC, but that isn't working either. I'll
have to look at why that might be, could be revealing about the problem in
general.

**Comment by stephensrmmartin** [comment]
Just an update: I commented out the section you mentioned, recompiled/reinstalled/restarted the daemon, etc. It had no effect. The terminal still didn't show.

**Comment by gtritchie** [comment]
Thanks for trying; it was a longshot. I'll try and investigate this soon and see if I can repro and figure out what's happening.

**Comment by pat-s** [comment]
Not facing the issue anymore, so closing.

**Comment by gtritchie** [comment]
Did you find a solution?

**Comment by pat-s** [comment]
Back then I had a different laptop, I did not face the issue on the new one. But ofc that does not help at all to track the problem down.

**Comment by gtritchie** [comment]
Fortunately we haven’t run out of other issues to investigate. Glad it’s working for you now.
