### ISSUE TITLE
Don't update file associations for non-R filetypes

### ISSUE THREAD

**Issue by wesinator** [rstudio/rstudio#1732]
**Version**: 1.1.383 Ubuntu 16.04+/Debian 9+ (64-bit)

After installing the deb package, `.c` and `.js` files were set to open in RStudio by default. This is an unexpected, astonishing behaviour for a user that does unrelated development outside R.

**Expected:** File associations for non-R file types are not to be changed upon installation.

**Comment by jmcphers** [comment]
On the other hand, this is very much expected behavior for some users who primarily use RStudio for development. We've had no more reports of frustration with the defaults so we're closing for now.

**Comment by wesinator** [comment]
> On the other hand, this is very much expected behavior for some users who primarily use RStudio for development. We've had no more reports of frustration with the defaults so we're closing for now.

Who woulds use RStudio for C or JS development ? 😜 😁
