### ISSUE TITLE
libGL issue only in RStudio

### ISSUE THREAD

**Issue by stephensrmmartin** [rstudio/rstudio#1734]
I have two machines, both with nvidia cards, both running the latest arch linux.

I am trying to use rgl.
On one machine (the desktop), rgl works fine in rstudio:
```
library(rgl)
open3d()
```
will open a blank window for drawing.

On the **laptop**, the above command results in:
```
R Session Aborted
R encountered a fatal error.
The session was terminated.
```
With errors:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
The kicker though: If I just open R in a terminal and run the above commands, it works just fine.

**Comment by jmcphers** [comment]
We've switched to a new rendering issue in RStudio 1.2+ which should resolved this issue (we've had no reports of it since).
