### ISSUE TITLE
R session abort on build for a project on a NAS

### ISSUE THREAD

**Issue by Pisca46** [rstudio/rstudio#1735]
When I create an new empty package project on my NAS and using build my R session will abort.
This doesn't happen for a project on hard disk.
A few week ago everything was working fine (maybe with older versions)
I am using:
- osMac High Sierra 10.13.1  (installed this week but the problem occurred also on 10.12)
- R 3.4.2
- RStudio 1.1.383 
- devtools 1.13.4
- a Synology NAS with DSM 6.1.4-15217 mounted with SMB (after having the same problem with AFP)

The error message is attached 
![20171109 - rstudio - abort](https://user-images.githubusercontent.com/8410718/32635143-48cc323c-c5af-11e7-9061-a17f3a9d6c8a.jpeg)

**Comment by kevinushey** [comment]
I believe this is the same issue discussed in https://github.com/rstudio/rstudio/issues/1690.

**Comment by Pisca46** [comment]
Sorry, this is the same problem as #1690.
