### ISSUE TITLE
rstudio version v1.1.383 identifies as version 99.9.9 after compilation from source

### ISSUE THREAD

**Issue by datamole** [rstudio/rstudio#1736]
Hello, I've downloaded the latest release as source archive from the github releases tab.

The tar.gz-file is correctly named for version 1.1.383, but after compilation it identifies as version 99.9.9 in the help window as well as in the version.txt file in the target folder.

Also I seem to have a couple of bugs with not being able to close files or plots (is just ignored).
As I understand it this is a known bug that should have been fixed in this version.

Could it just be that the wrong version of the sources has been bundled?

For completeness:
I have compiled on OpenSuseTumbleweed using gcc 7.2 against qt version 5.9.

**Comment by jmcphers** [comment]
Indeed, 99.9.9 is the default version number when you produce a non-official local build. If you want a local build to have an "official" version, set the `RSTUDIO_VERSION_MAJOR`, `RSTUDIO_VERSION_MINOR`, and `RSTUDIO_VERSION_PATCH` environment variables prior to building.

**Comment by datamole** [comment]
Thanks, for your input.

Actually I only had to build from the sources because the binary packages downloadable from the rstudio website for opensuse 13,1+ are built against gstreamer library version 0.1.

Given that I could compile a running program against gstreamer 1.0 in tumbleweed I was wondering why that is. I checked and actually already opensuse 13,1 had gstreamer 1.0 as prt of the distribution. 
So, an rpm built against version 1.0 should be working in all flavors of opensuse including tumbleweed. (For ubuntu however there is a separate package for ubuntu 16.04 using gstreamer 1.0)

For future updates it would be super awesome if the rpm downloadable from the website would be changed to gstreamer 1.0.

This is probably not the right place for the request, so perhaps this suggestion could be forwarded to the people in charge.

**Comment by jmcphers** [comment]
Yes, in the next version of RStudio we're hoping to do away with the gstreamer dependency entirely. Stay tuned. :-)

**Comment by datamole** [comment]
Awesome! I love to hear it. With next release you're referring to version 1.2? ... because in the daily builds that one is still dependent on gstreamer 0.1.

If getting rid of gstreamer is planned for a version in the more distant future I'd still like to suggest uploading an (alternative) build against gstreamer 1 for the meantime.

**Comment by jmcphers** [comment]
We're still working on excising gstreamer (it's on a branch and not even ready for the dailies yet). However we expect to have it done by the time 1.2 ships!

**Comment by datamole** [comment]
... thumbs up, that would be great !!!

**Comment by datamole** [comment]
Another thing I realized with my builds from the latest sources is that there is a regression of the performance and stability for the view for large data frames/matrices.

It used to be very robust even when opening large data frames. Now it has some delay every time I scroll and even hangs up the whole application when I try to open data frames with a large number of columns (that were OK in earlier versions).

I think the view was truncated in terms of rows that could be scrolled through in the past. While you couldn't view all rows that way it had the advantage that you could still scroll through all you columns to evaluate the type of data you had in there.
Now the application would just hang.

**Comment by jmcphers** [comment]
The slow data frame issue is tracked here:

https://github.com/rstudio/rstudio/issues/1771

I don't think this issue tracks anything meaningful now (we've changed topics a couple of times) so closing for now. Thanks for the feedback!
