### ISSUE TITLE
Please sign deb installation packages for increased security

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rstudio#1737]
"MD5 checksums aren't really sufficient -- they verify that the files aren't corrupted, but don't verify that they actually came from RStudio. For example, if someone breaks into the RStudio website, they could easily upload new packages and md5sums. Unfortunately, this isn't just a theoretical risk -- similar attacks have occurred on software distribution sites in the past.

With GPG keys, this isn't an issue as long as your private key is properly protected."

Support 20831, 24105

**Comment by jmcphers** [comment]
Tracked here (and fixed for 1.2): https://github.com/rstudio/rstudio/issues/1619
