### ISSUE TITLE
Error when restoring from suspended session

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#1740]
I've been seeing this error frequently in the latest release version (1.1.383) when restoring from a suspended session on RStudio Server:

`Error in loadNamespace(name) : there is no package called ‘.GlobalEnv’`

**Comment by dfalty** [comment]
I'm not able to reproduce this on 1.1.383. Do you have any additional info on the types of sessions this happens with?

**Comment by EmilBode** [comment]
I think I have a repro, on 1.1.453/Rstudio Desktop

The problem occurs when having an open tab with a function definition open (you see the source code, e.g. when debugging) and then quitting. It looks like this particular warning is generated if it is a function in your global environment, other functions generate slightly different warnings (most often "there is no package called 'unknown'", but I've also seen it about "debugging")
Interestingly, it doesn't matter if I restore .RData or not.
But anyway, it looks like if tab "myFun" is open, that RStudio tries to load .GlobalEnv::myFun or something similar, which fails.
This can also be seen when clicking the tab 'myFun', which simply shows:
````

# ERROR: Definition of function 'myfun' not found
# in namespace '.GlobalEnv'
````
My impression is that it's safe to ignore, you only won't see the source code. 
And to stop any messages from showing up, close all such tabs with functions before quitting.

**Comment by ronblum** [comment]
@EmilBode and @BaruchYoussin is this still an issue in the current release, 1.3.1056?https://rstudio.com/products/rstudio/download/#download
