### ISSUE TITLE
RStudio Desktop on Linux crashes when switching between monitors

### ISSUE THREAD

**Issue by vh-d** [rstudio/rstudio#1743]
## Issue
RStudio crashes every time I switch between monitors on a Linux machine.

I know this has been reported on RStudio community support web for a while but this seems to be a better place to track the issue.

## System info

    RStudio version: 1.1.383
    R version 3.4.2 (2017-09-28)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 16.04.3 LTS (4.10.0-38-generic)

## relevant part from RStudio log:

    ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1239

## console output dump:

    $ rstudio 
    load glyph failed err=6 face=0x1b68020, glyph=2797
    load glyph failed err=6 face=0x1b68020, glyph=2797

still ok, but switching monitors now yields:

    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::fillPath: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::brush: Painter not active
    QPainter::fillPath: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::end: Painter not active, aborted
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::setCompositionMode: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 1!
    QPaintDevice::metrics: Device has no metric information
    Unrecognised metric 2!
    QPaintDevice::metrics: Device has no metric information
    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::translate: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setWorldTransform: Painter not active
    QPainter::setFont: Painter not active
    QPainter::setOpacity: Painter not active
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::worldTransform: Painter not active
    QPainter::pen: Painter not active
    QPainter::setPen: Painter not active
    QPainter::setBrush: Painter not active
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::drawRects: Painter not active
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::setRenderHint: Painter must be active to set rendering hints
    QPainter::pen: Painter not active
    QPainter::setPen: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::save: Painter not active
    QPainter::setClipRect: Painter not active
    QPainter::restore: Unbalanced save/restore
    QPainter::end: Painter not active, aborted
    Segmentation fault

How can I build RStudio with debugging symbols?

**Comment by kevinushey** [comment]
We're hoping this issue will be fixed when we upgrade the version of Qt used in our desktop products (something we're currently actively working on, but is unfortunately a large effort so may take some more time).

**Comment by JonathanSeguin** [comment]
Having the same behavior when getting back to my computer after locking gnome session and closing both my monitors (centos7, Qt 5.4)

**Comment by rmflight** [comment]
As of v 1.2.315, I don't experience this behavior anymore, FYI. 

Now if only the resolution wasn't messed up by going from a 4K to 1080p monitor ....

**Comment by JonathanSeguin** [comment]
fwiw i'm also using a 4k + 1080p setup.

**Comment by dkincaid** [comment]
How did you get v1.2.315? The latest version I can find on the website is 1.1.142.This would make my year if they fixed this. It's the biggest pain in my a** since I frequently go from external monitors to laptop monitor.

**Comment by jmcphers** [comment]
@dkincaid It's on our daily build site: https://dailies.rstudio.com

Closing since we've had a few confirmations that it's fixed there; @vh-d feel free to reopen if it isn't fixed for you in 1.2.

**Comment by nergiszaim** [comment]
Hi, I am having the same issue recently since I updated to Catalina. I am running on R version 3.6.1 (2019-07-05)

**Comment by thimotei** [comment]
Hi, I know this is old, but I'm having the same issue. Rstudio works fine on my laptop screen, but as soon as I try anything in an existing or a new Rstudio on my 4K monitor, it completely crashes. I'm running Gnome in Arch Linux

**Comment by slodkog** [comment]
Just to add to the above two reports that this is still happening: I'm routinely getting crashes on macOS 10.15.7 and RStudio 1.4.1106. This issue should be re-opened.

**Comment by kevinushey** [comment]
Putting this in the "hopefully fixed via Electron" bucket.

**Comment by gtritchie** [comment]
@kevinushey Along those lines, adding to Electron milestone and "FixedByElectron" EPIC.

**Comment by anguswg-ucsb** [comment]
Just to bump this issue again, 
my RStudio on Windows 10 also crashes when trying to move RStudio to another monitor.

**Comment by ccheng11** [comment]
I am having exactly the same issue after I update my Mac OS.

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by ronblum** [comment]
Closing this as fixed by Electron. If anyone using builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) continues to run into this issue, please let us know!
