### ISSUE TITLE
Update "Build & Reload" in Roxygen options to "Install & Restart"

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#1746]
Now that the Build Pane says "Install & Restart", it seems like that should be reflected in the Roxygen options.
<img width="643" alt="screen shot 2017-11-11 at 10 04 48 pm" src="https://user-images.githubusercontent.com/599454/32711537-46e15f46-c7f4-11e7-9fec-eb7bdbedc541.png">

**Comment by coatless** [comment]
@jmcphers 

to piggy back on this issue, could we also change the name `Clean and Reload` under the "More" tab of build to `Clean and Reinstall` ? 

<img width="436" alt="clean_rebuild" src="https://user-images.githubusercontent.com/833642/32850719-8c573d92-c9f8-11e7-90de-41a83a6108ca.png">

**Comment by dfalty** [comment]
Reopening per the last comment.

**Comment by coatless** [comment]
@dfalty would it be better if I put this in a new issue?

**Comment by jmcphers** [comment]
Yes, this should be a new issue (if it's still a problem!)
