### ISSUE TITLE
Enhancement request: Reactivate an open project instead of opening in a new session

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#1753]
If a project is open in an RStudio session, and you double click on the Rproj file again, it opens in another session instead of bringing up the open one. It would be nice if re-opening the Rproj file would find and reactivate the existing session.

**Comment by hadley** [comment]
A somewhat related problem is that loading a project messes with the "alt-tab" order. i.e. if I open ggplot2, then tidyr, then dplyr, pressing alt+tab to switch back to the "previous" project opens ggplot2 (instead of tidyr)

**Comment by rmflight** [comment]
If this is done, could there be an option for desired behavior? I like having the project open again, as there are some places I've found it useful to do (especially on a multi-workspace system).

What I personally find annoying about current behavior is that all the open tabs in the project are lost in the newly opened one.
