### ISSUE TITLE
No timeout for testing a ODBC connection

### ISSUE THREAD

**Issue by silentstrikeFIN** [rstudio/rstudio#1754]
I have in memory a SQL ODBC connection to a database that does not exist anymore. If I try to use this connection trough the new Connections -> New Connection feature and use the 'test', RStudio will test the connection endlessly:
![image](https://user-images.githubusercontent.com/3607109/32822720-8d2baade-c9e2-11e7-96d2-56a8eb380ba2.png)

![image](https://user-images.githubusercontent.com/3607109/32822554-cc74e184-c9e1-11e7-9d62-5f8dda893293.png)

'New Connection' is not responding while this is happening, and the session cannot be terminated, because 'Quitting R Session' is also on a endless loop:
![image](https://user-images.githubusercontent.com/3607109/32822628-29ea3e9a-c9e2-11e7-99c9-8b18baf7c394.png)

There probably should be a timeout for testing the connection.

**Comment by dfalty** [comment]
I was able to reproduce this on 1.2.174-2. Thanks for the report!

**Comment by javierluraschi** [comment]
Fixed with https://github.com/rstudio/rstudio/pull/2954; however, this requires us to run:

```
devtools::install_github("r-dbi/odbc")
```

I opened https://github.com/rstudio/rstudio/issues/2956, to track the 1.2 work to update CRAN versions.
