### ISSUE TITLE
`cat` prints with a newline in the console

### ISSUE THREAD

**Issue by talgalili** [rstudio/rstudio#1755]
Running cat in the console in RStudio vs Rgui is different. In RStudio it prints and goes to the next line while Rgui doesn't:

In Rgui:
![image](https://user-images.githubusercontent.com/976006/32828703-93955ce2-c9f8-11e7-9e86-7fd34567bfd3.png)

In RStudio:
![image](https://user-images.githubusercontent.com/976006/32828691-8c392a8c-c9f8-11e7-84a8-f759b2b10ca4.png)

**Comment by talgalili** [comment]
(I'm not sure if this is a bug or a feature - so I'm making sure to bring this to your attention)

**Comment by hadley** [comment]
I think this is a feature.

**Comment by jmcphers** [comment]
Yes, we do this intentionally so that the prompt always starts on a clean line (it can be difficult to find the prompt and/or enter text midway through the line). Appreciate the report however!
