### ISSUE TITLE
Validate compatibility with Pandoc 2.0

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1756]
Pandoc 2.0 contains a [large number of changes](https://github.com/jgm/pandoc/releases/tag/2.0), some of which change behavior in important ways. While we don't bundle 2.0 yet, we do use the system version of Pandoc over our own in some configurations, so need to ensure compatibility with the new version. 

@jjallaire pointed out that we may need to adjust our self-contained HTML generation function here so that it works with both Pandoc 1 and Pandoc 2:

https://github.com/rstudio/rstudio/blob/b84eed57bf77ee795e37f50431d4908a0584b57a/src/cpp/session/modules/ModuleTools.R#L297

See also the comments on this issue:

https://github.com/ramnathv/htmlwidgets/issues/289

and this this PR from @jcheng5 which addresses it:

https://github.com/ramnathv/htmlwidgets/pull/292

**Comment by jmcphers** [comment]
Since Pandoc 2 already exists in the wild, we should actually make this change for 1.1 patch (changed milestone). The work that should happen in 1.2 is updating the internal copy of Pandoc to Pandoc 2, which is now tracked in https://github.com/rstudio/rstudio/issues/1807.

**Comment by jmcphers** [comment]
`pandocSelfContainedHtml` always uses `RSTUDIO_PANDOC` to determine the version of Pandoc to use.

https://github.com/rstudio/rstudio/blob/560aeb25f6634b3187082280e192d595ebc047be/src/cpp/session/modules/ModuleTools.R#L325-L327

It is possible to set `RSTUDIO_PANDOC` to Pandoc 2, even in RStudio 1.1, but it's probably not common. Compare with `find_pandoc` in the rmarkdown package, which will use a new pandoc in preference to `RSTUDIO_PANDOC` if it finds one.

https://github.com/rstudio/rmarkdown/blob/2b418a242af8a4eca1d3156614d25816d39e721a/R/pandoc.R#L513-L549

**Comment by jmcphers** [comment]
backported to 1.1 in 80e1cb947dd7239b9d82ef75276fc4d057efa6a7.

**Comment by ronblum** [comment]
Knit to HTML fails with RStudio 1.1.412 (both open source and Pro) on **OpenSUSE 12.3** with **Pandoc 2.0.6**, with the error message:

> /usr/bin/pandoc2.0.6/pandoc +RTS -K512m -RTS bobo.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output bobo.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /home/rstudio/R/x86_64-suse-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpYTAMGV/rmarkdown-str17687c71322e.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
Execution halted

Publishing is succeeds, though with the console message:

> --smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.

Knit to HTML works fine with RStudio 1.1.383 as well as other environments (Ubuntu 16.0.4, MacOS 10.12.6).

**Comment by jmcphers** [comment]
What version of the rmarkdown package are you using?

**Comment by ronblum** [comment]
1.6. It works fine with 1.8. Sorry about that. All good.
