### ISSUE TITLE
Allow installing package dependencies from repositories not named CRAN

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1762]
Today, we test to see if versions of needed packages are available in either:

1. a repository named "CRAN", if available, or
2. the first repository, if repositories are not named.

This logic lives here:

https://github.com/rstudio/rstudio/blob/b84eed57bf77ee795e37f50431d4908a0584b57a/src/cpp/session/modules/ModuleTools.R#L117-L151

However, we've found in the wild that it's possible that a CRAN-like repository may be named something other than CRAN. This is the motivation this Packrat change, which switches from a whitelist to a blacklist for identifying CRAN-like repos:

https://github.com/rstudio/packrat/commit/4b3e4025404f98d25fb73799e86c1762effe5d7e

We should be more permissive in RStudio, too. The proposal here is to change RStudio such that it looks for needed packages in:

1. a repository named "CRAN", if available, or
2. the first repository otherwise, *regardless of name*.

**Comment by jmcphers** [comment]
Backported to 1.1 in 3c99f0298014a1542fe321acb95faa8f7451f10c.

**Comment by ronblum** [comment]
Verified in RStudio server and desktop v1.1.393.
