### ISSUE TITLE
RStudio-server: slow file access on system with a lot of users

### ISSUE THREAD

**Issue by hgsommer** [rstudio/rstudio#1763]
Hi,
I have an rstudio-server installation on a server running Scientific Linux 7 and R version 3.4.1. After the upgrade to version 1.1.383 the server showed the following behavior: When one tried to open a file from the web frontend, the "Opening file..." message was shown for a while and then most of the time an 502 Error was displayed. I had a look at the apache log files (used as a proxy configured like in the [example](https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy)) and it showed a lot of timeout messages.
Another thing I noticed was, that the rsession process showed the 'D' state in `ps` output, so was probably waiting for I/O. I run `strace` on the rsession process and it showed that `stat()` was called on every home directory on the system (every item in the parent directory of the current `$HOME`).
Since there are a lot of user file systems mounted on that server via NFS (about 70k, although only a handfull uses rstudio actively), this takes some time obviously.
Our previous version (1.0.143) did not show this behavior.

If you need additional info, please let me know.

**Comment by jmcphers** [comment]
We believe that this is the same issue described here: https://github.com/rstudio/rstudio/issues/1592.

We're working on putting out a patch release to 1.1 which has the candidate fix; it should be ready sometime next week.

**Comment by jmcphers** [comment]
We have now released the aforementioned patch release; this issue should be taken care of.
