### ISSUE TITLE
Restarting R Session When Debugging a Function

### ISSUE THREAD

**Issue by drkarthi** [rstudio/rstudio#1764]
![debug_mode](https://user-images.githubusercontent.com/6463520/32954341-d2ff2cbc-cb80-11e7-8d63-56ab02b2f048.PNG)

Restarting the R session when in the process of debugging a function ( using debug(func_name) ), shows the debug mode text in the console (that says "Browse[2]"), though it is no longer in the debug mode.

**Comment by dfalty** [comment]
I can reproduce this on version 1.2.178 (Mac). Thanks for the report!
