### ISSUE TITLE
Can't copy text from terminal pane when using a Tmux session

### ISSUE THREAD

**Issue by rmflight** [rstudio/rstudio#1765]
Steps to reproduce:

* Open `Terminal` pane
* start `tmux`
* do a directory listing
* highlight a file name you would like to copy
* right click to bring up context menu, and see that `copy` is greyed out

Exit `tmux`, and then try to copy the text, it should work.

Running RStudio 1.2.178, Ubuntu 16.04 LTS.

**Comment by dfalty** [comment]
I was able to reproduce this as well. Thanks for the report!

**Comment by harryprince** [comment]
Same issue+1

**Comment by christiantillich** [comment]
I believe I'm having this issue as well.

One thing I've noticed is that I am copying and pasting something - the results of whatever section I've highlighted in the main shell window, not the tmux window. So:

- Open `Terminal` Pane. 
- Type `Test 1 2` into the console, press enter, get error. 
- `tmux new-session`
- Copy the whole first line into text editor. 

You should see that `Test 1 2` gets copied even when it doesn't appear in the tmux window. This seems to happen both with local tmux sessions as well as ssh connections to a server. 

Running macOS Mojave 10.14.3, RStudio Version 1.1.423. Upgrading RStudio to Version 1.2.1335 didn't seem to help either.
