### ISSUE TITLE
Multiple Deployment in Progress dialogs appear overlapping each other 

### ISSUE THREAD

**Issue by dethmasque** [rstudio/rstudio#1767]
Screen Shot: 

![image](https://user-images.githubusercontent.com/32644679/32965726-7ae606c0-cba5-11e7-81ff-2a113b50dd46.png)

This is hard to reproduce as it's timing-based.

RStudio Version 1.1.383

Steps to Reproduce:

1) Attempt to publish a Shiny application from the IDE by selecting the Publish icon.
2) Select within the Title field on the Publish to Server dialog and rapidly hit the Enter key multiple times.

Expected Results:

The dialog closes and the app is published.

Actual Results:

The dialog closes and multiple Deployment in Progress dialogs appear overlapping each other.

**Comment by dfalty** [comment]
I can reproduce this on the latest 1.2 build as well (1.2.178 Mac). This can also happen with the overwrite popup and is super annoying if you press enter a bunch of times. Thanks for the report!

![popups](https://user-images.githubusercontent.com/15237845/32966853-c9897e06-cba0-11e7-867a-825a4d866b8d.gif)

**Comment by jmcphers** [comment]
We have this problem in a lot of dialogs. I think the fundamental issue is addressable in the ongoing `QtWebEngine` port; namely, we need to avoid opening a native modal if one is already open (we don't know this at the call site, and don't check for it in the presentation layer).
