### ISSUE TITLE
Support for R markdown in .R scripts

### ISSUE THREAD

**Issue by kkmann** [rstudio/rstudio#1768]
Hi, 

there are good reasons for preferring .R files over .Rmd files for writing reports (most importantly, somebody without any knowledge of markdown knows what's going on). So, it would be extremely cool to have syntax support and support for parameter definitions in .R script files with markdown comments in RStudio. Would that be possible?

This was originally a post over at community.rstudio, cf. [original post](https://community.rstudio.com/t/support-for-markdown-syntax-highlighting-in-r-files/2612).

Best,

Kevin

**Comment by jmcphers** [comment]
This is a nice idea but hasn't gathered attention or votes in over two years, and we don't foresee being able to implement it anytime soon, so closing for now.
