### ISSUE TITLE
Show all hidden files in the Files Pane

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rstudio#1769]
There is no setting to show all hidden files in the Files tab; there are a handful of hidden files that are always shown, but the others are always hidden.  If you need to see all the files in a directory in R, you can use `list.files(getwd(), all.files=TRUE)`, but there is a request for a global setting to show all files, including hidden ones, in the Files Pane at all times.  Ticket 24112

**Comment by jmcphers** [comment]
You'll find this on More in the Files pane now:

![image](https://user-images.githubusercontent.com/470418/39076409-ece2f37c-44af-11e8-8dd9-f2cc46f6ce0d.png)

**Comment by jmcphers** [comment]
It's never been in RStudio 1.1 (it's a new feature in RStudio 1.2). You can get a preview release of RStudio 1.2 here:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by kenahoo** [comment]
Oh, I guess I misinterpreted your "now" to mean in a non-preview release.  Thanks, I'll check it out.

**Comment by stevekm** [comment]
How do you enable this in <1.2 versions? Our system admins installed Rstudio Server 99.99.9 (?) it seems, so its not like I can just upgrade...

**Comment by gtritchie** [comment]
This cannot be enabled in versions before 1.2; it is a new feature added in 1.2.

Version "99.9.9" means you are using RStudio compiled by (presumably) your system administrators, instead of using a pre-built RStudio release. They will need to either build again using newer source code, or install an official 1.2 build from https://www.rstudio.com/products/rstudio/download/

Hope this helps.

**Comment by sbgraves237** [comment]
I'm using RStudio Version 1.2.1564 and cannot find it.  "git push" in a Terminal returned:  

ERROR: Permission to joshuaulrich/tmp-ecfun.git denied to sbgraves237.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

** Meanwhile "git push" inside RStudio returned ">>> git push origin HEAD:refs/heads/master
Everything up-to-date".  

** "git status" in the Terminal says:  

On branch master
Your branch is ahead of 'tmp/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

[This is under macOS 10.14.6.]  

How do I fix this problem?  "https://stackoverflow.com/questions/6905862/git-has-forgotten-the-remote-repository-i-fetch-from-push-to" suggests I look at ".git/config".  I do not see how to do that in RStudio.  Thanks, Spencer Graves
