### ISSUE TITLE
Inline code diagnostics error: purrr anonymous function formula with if-else

### ISSUE THREAD

**Issue by treysp** [rstudio/rstudio#1773]
Rstudio is fantastic - thanks so much for a great product!

I'm getting an incorrect unmatched parentheses syntax error when I use the one line version of if-else in an anonymous formula function:

![image](https://user-images.githubusercontent.com/1831878/33086545-ddf8e45e-ceb5-11e7-9596-3fcbfc832b20.png)

If I wrap the expressions in curly braces or use standard anonymous function syntax everything looks good:

![image](https://user-images.githubusercontent.com/1831878/33086628-2301181e-ceb6-11e7-93b2-7c4037d6cc4d.png)

Thanks!

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2  rsconnect_0.8.5 tools_3.4.2 
```

**Comment by dfalty** [comment]
I'm able to reproduce this on the latest version 1.2.179-1. Thanks for the report!

**Comment by jmcphers** [comment]
Not a must for 1.3
