### ISSUE TITLE
Connections pane: library(DBI) turned into library(odbc)

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#1783]
When I create a new connection to a PostgreSQL DB via odbc:
1) I open the New Connection window
2) I click on `PostgreSQL Unicode(x64)`
3) I fill in the parameters and click `Test` (success). The following code is displayed in the lower field:
```r
library(DBI)
con <- dbConnect(odbc::odbc(), .connection_string = "Driver={PostgreSQL Unicode(x64)};database=xxx;
server=xxx;
uid=xxx;
pwd=xxx;
port=5432;")
```
4) I disconnect `con`. The following code is displayed in the Connections pane:
```r
library(odbc)
con <- dbConnect(odbc::odbc(), .connection_string = "Driver={PostgreSQL Unicode(x64)};database=xxx;\nserver=xxx;\nuid=xxx;\npwd=xxx;\nport=5432;")
```

Is there a reason why `library(DBI)` has turned into `library(odbc)`?

RStudio 1.1.383

**Comment by javierluraschi** [comment]
A fix would be requited in the `odbc` package, opened https://github.com/r-dbi/odbc/issues/192 and closing this one.
