### ISSUE TITLE
Showing incorrect row numbers in View

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#1784]
I'm using RStudio 1.2.183 under macOS High Sierra.

Steps to reproduce:

```r
data <- data.frame(id = 1:100)
View(data)
```

Then the row numbers in the View tab shows `1, 0, -1, -2, -3, ...` like the following:

<img width="171" alt="image" src="https://user-images.githubusercontent.com/4662568/33236698-a902066a-d296-11e7-8b95-f0ff80a2a8dd.png">

Using `rownames(data)` shows the correct result.

My session info:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    yaml_2.1.14   
```

**Comment by jmcphers** [comment]
This is a regression in 1.2 (it works correctly in 1.1). We've made a couple changes to rowname generation to improve performance, so probably one of them is responsible. Appreciate the report, we'll fix this soon!

**Comment by ronblum** [comment]
Confirmed in 1.2.338.
