### ISSUE TITLE
Dark mode not applied to pop-out Source Editor

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rstudio#1785]
![image](https://user-images.githubusercontent.com/4773225/33270774-710e3180-d385-11e7-8ea4-360c0e7664f9.png)

RStudio 1.1.383
macOS 10.13.2 Beta (17C79a)

When the source editor is embedded in the main RStudio window, it correctly adopts dark mode like the rest of the interface. But when the editor is popped out to its own window, it reverts to the standard light mode interface.

Potentially related to #1573

**Comment by dfalty** [comment]
I can reproduce on 1.1.383 and the latest 1.2.183 (Mac 10.12.2). This only happens if you have a popped out source editor when transitioning from light to dark. If you return the editor and pop it back out, it will display correctly. Thanks for the report!
