### ISSUE TITLE
Dialog box too small for text when creating new project from git repo

### ISSUE THREAD

**Issue by mccarthyryanc** [rstudio/rstudio#1787]
When creating a new project from a Git Repo, hosted on a private server, and it is the first time accessing this git server I get the following dialog:
![rstudio_dialog_before](https://user-images.githubusercontent.com/997120/33281692-f44da4fc-d35a-11e7-8fe7-85c58f928cde.png)

At first it looks like it is asking for a password, but once you move the dialog box it expands to show all the text:
![rstudio_dialog_after](https://user-images.githubusercontent.com/997120/33281739-2101409e-d35b-11e7-90f4-c6db573502ea.png)

and then it is obvious you need to type 'yes'. Can the dialog be increased to show all the text when it first opens?

**RStudio 1.1.383 on Windows 10**

**Comment by jmcphers** [comment]
We've had no other reports of this in over two years and have not been able to look at it, so unlikely that it'll get addressed soon.
