### ISSUE TITLE
knitr::opts_chunk$set(collapse = TRUE) does not work in Notebook mode

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#1788]
I want to collapse all my output into a single output chunk using `collapse=TRUE`. However, this function does not work in an R Notebook. The format makes my notebook look like a mess. I can hide my code, but I have to do that manually, and I can't share the specific format I want with other people. The workaround is to use an html_document instead of an html_notebook.

**Comment by jmcphers** [comment]
We still don't support this. I'm marking this as an enhancement since it's an unimplemented knitr feature.
