### ISSUE TITLE
System error 5 with strange absolute path C:\jenkins\workspace

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#1791]
Hi,

I saw this error today on 1.2.183

	ERROR system error 5 (Access is denied) [path=C:/Users/user007/Documents/.Rhistory]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::open_w(rstudio_boost::shared_ptr<std::basic_ostream<char> >*, bool) const C:\jenkins\workspace\IDE\windows\src\cpp\core\FilePath.cpp:1144; LOGGED FROM: void rstudio::r::session::{anonymous}::reportHistoryAccessError(const string&, const rstudio::core::FilePath&, const rstudio::core::Error&) C:\jenkins\workspace\IDE\windows\src\cpp\r\session\RSession.cpp:338  

diagnostics-report.txt

	R version 3.4.2 (2017-09-28)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows >= 8 x64 (build 9200)

	Matrix products: default

	locale:
	[1] LC_COLLATE=English_United States.1252 
	[2] LC_CTYPE=English_United States.1252   
	[3] LC_MONETARY=English_United States.1252
	[4] LC_NUMERIC=C                          
	[5] LC_TIME=English_United States.1252    

	attached base packages:
	[1] stats     graphics  grDevices utils    
	[5] datasets  methods   base     

	loaded via a namespace (and not attached):
	[1] compiler_3.4.2 tools_3.4.2   
	[3] yaml_2.1.14   

	SysInfo:
			sysname         release 
		  "Windows"      ">= 8 x64" 
			version        nodename 
	   "build 9200" "user007" 
			user007hine           login 
		   "x86-64"           "user007" 
			   user  effective_user 
			  "user007"           "user007" 

	R Version:
				   _                           
	platform       x86_64-w64-mingw32          
	arch           x86_64                      
	os             mingw32                     
	system         x86_64, mingw32             
	status                                     
	major          3                           
	minor          4.2                         
	year           2017                        
	month          09                          
	day            28                          
	svn rev        73368                       
	language       R                           
	version.string R version 3.4.2 (2017-09-28)
	nickname       Short Summer                

	$R_COMPILED_BY
	[1] "gcc 4.9.3"

	$R_DOC_DIR
	[1] "C:/PROGRA~1/R/R-34~1.2/doc"

	$R_HOME
	[1] "C:/PROGRA~1/R/R-34~1.2"

	$R_LIBS_USER
	[1] "C:/Users/user007/Documents/R/win-library/3.4"

	$R_USER
	[1] "C:/Users/user007/Documents"

	$RMARKDOWN_MATHJAX_PATH
	[1] "C:/Program Files/RStudio/resources/mathjax-26"

	$RS_LOCAL_PEER
	[1] "\\\\.\\pipe\\13562-rsession"

	$RS_RPOSTBACK_PATH
	[1] "C:/Program Files/RStudio/bin/rpostback"

	$windir
	[1] "C:\\WINDOWS"

	 [1] ".GlobalEnv"        "tools:rstudio"    
	 [3] "package:stats"     "package:graphics" 
	 [5] "package:grDevices" "package:utils"    
	 [7] "package:datasets"  "package:methods"  
	 [9] "Autoloads"         "package:base"     
	Log file: rdesktop.log

**Comment by jmcphers** [comment]
It sounds like there's a permissions problem with `C:/Users/user007/Documents/.Rhistory`. Do you have read access to that file? 

`C:\jenkins\workspace` is just the path where the source file existed when building RStudio in our build lab; it doesn't have anything to do with your local installation.

**Comment by tungmilan** [comment]
Thanks @jmcphers ! I have no idea why it happened as my account is the administrator. I also didn't activate "Controlled folder access" functionality in Windows 10 Defender

**Comment by jmcphers** [comment]
It's an `open_w` call so it's possible another program had the file locked. Feel free to reopen if you see this frequently and/or notice any downstream unpleasant behavior in the IDE!
