### ISSUE TITLE
RStudio versions 1.1.383 and 1.1.392 - poor performance on Ubuntu 16.04

### ISSUE THREAD

**Issue by fsdias** [rstudio/rstudio#1792]
Hi

Ubuntu 16.04 64 bits with Rstudio 1.1.392 and 1.1.383 

The cursor flickers a lot and keeps cycling between a hand and an arrow (it's worse on 1.1.383). The overall responsiveness is poor. For example it can take up to two seconds to open the "environment" tab or to cycle between .R scripts. Sometimes it freezes for 1/2 seconds.

Let me know if I need to add anything else to this report.

Thanks

**Comment by dfalty** [comment]
I'm not able to reproduce this on 1.1.392 or 1.1.383 with Ubuntu 16.04. Not sure what's going on, but the team might have ideas on how to diagnose.

**Comment by fsdias** [comment]
I deleted  ~/user/.rstudio-desktop and most problems disappeared. I am still noticing some small performance issues. These include lag after clicking on a tab and some occasional cursor flickering.

**Comment by fsdias** [comment]
I just test 1.393 and it is really laggy. In this video I am trying scroll down a data.frame. Next I try to click on the dropdown icon to see the the data.frame's columns. 

![video](https://user-images.githubusercontent.com/5689181/33683456-e0289274-dac2-11e7-837b-9b38e97e3214.gif)

**Comment by CassusVas** [comment]
I am also having this issue.  I actually have two issues- this one along with the issues described here: [https://github.com/rstudio/rstudio/issues/1587](https://github.com/rstudio/rstudio/issues/1587) including most dialog boxes (open file and save file).

My bug is described in more detail here, I'm posting as Dan:
[https://blog.rstudio.com/2017/10/09/rstudio-v1.1-released/#comment-3603536058](https://blog.rstudio.com/2017/10/09/rstudio-v1.1-released/#comment-3603536058)

I'm using Ubuntu 16.04 64-bit and RStudio Desktop.

**Comment by izk8** [comment]
Having exact same issue as fsdias. Thanks for taking screen shot. Should we just install an older version of r-studio?

**Comment by kevinushey** [comment]
Can you also test whether the performance is better in the latest daily builds of RStudio? These are available at https://dailies.rstudio.com/.

**Comment by fsdias** [comment]
Hi, 
As of version 1.2 I stopped having these problems.
