### ISSUE TITLE
Terminal menu with many instances triggers incorrect rendering

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#1794]
Create a lot of terminals such that they grow beyond the console height, hover over the menu:

Actual:

<img width="1414" alt="screen shot 2017-11-28 at 5 42 54 pm" src="https://user-images.githubusercontent.com/3478847/33353686-d454a7cc-d463-11e7-8f18-8203c9b5d049.png">

Expected: RStudio interface not to be pushed up nor reveal bottom background.

**Comment by jmcphers** [comment]
Compare with https://github.com/rstudio/rstudio/issues/1760. It'd be nice if we could fix this generically for GWT pop-up menus as any menu that can grow unbounded has this problem.

**Comment by mine-cetinkaya-rundel** [comment]
A long Global Environment dropdown also causes a similar look in the IDE:

<img width="1433" alt="screen shot 2018-10-08 at 8 51 55 pm" src="https://user-images.githubusercontent.com/5965649/46680970-3ba6ac80-cbb8-11e8-84d5-bd5a5d23c1b7.png">

**Comment by dfalty** [comment]
Verified fixed on the Global Environment and Terminal dropdowns on v1.3.822-1
