### ISSUE TITLE
[Bug] : OS X  Show Help Menu shortcut does not work when Console is in focus

### ISSUE THREAD

**Issue by Neko42** [rstudio/rstudio#1796]
![show help menu](https://user-images.githubusercontent.com/7159928/33374840-a825cbb2-d4ff-11e7-862a-b8bcc13b6430.png)
In Mac OS X, it is very common to be able to access the Help menu to find various functionalities.
As of RStudio version  1.1.383 This shortcut does not work properly.

Expected result : when I press ⬆+ ⌘ + / it should open the Help menu

**EDIT** : Looks like it's a bug.
It **does not work** when the console has focus
it **works** when other elements have focus

**Comment by ronblum** [comment]
This is true for other panes as well—source, files, plots, etc. ⬆+ ⌘ + / is being used as a keyboard shortcut for "Reflow Comment." Changing the shortcut to something else fixes this for most panes, but not for the console and source panes.

**Comment by jmcphers** [comment]
We decided to fix this by changing the binding. https://github.com/rstudio/rstudio/pull/5667
