### ISSUE TITLE
[Wishlist / Feature Request] Line end spaces in Markdown 

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/rstudio#1804]
Markdown takes two (or more) trailing spaces to be a newline (in the LaTeX sense).

Emacs, in markdown mode and with highlighting etc on, shows these two spaces in a very subtle way:

![screenshot](https://user-images.githubusercontent.com/673121/33519973-61e99096-d777-11e7-9000-5f948674ec88.png)

It would be nice if (R)Markdown mode in RStudio could do this too, maybe with an option to turn on/off.  I looked for an existing thinking it might be obvious, but found nothing.  (The underscore in column is the cursor in the format I use in that 'mode'.)

Build 1.2.190 on Linux

**Comment by jmcphers** [comment]
In Options -> Code -> Display, there's an option which enables the display of whitespace characters. Does that do what you want?

![image](https://user-images.githubusercontent.com/470418/33574291-6ea49976-d8ed-11e7-8eb5-fa1c2bcf2774.png)

**Comment by eddelbuettel** [comment]
Lemme check. I kinda knew it had to be there because a) my ailing mind remembers it from way back when and b) we had a discussion once about inserting different whitespaces and they were shown too.

Dang, and I had been in that very menu screen.  Just missed the line :-/

We can close this.  Seeing only whitespace and not cr would be nice, but close enough.
