### ISSUE TITLE
Upgrade to Pandoc 2

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1807]
Pandoc 2 was released in October. 

<https://pandoc.org/releases.html>

We will update the bundled copy of pandoc in RStudio with this new release. This is a prerequisite for out-of-the box Powerpoint support.

Note that this will require an R Markdown package version requirement bump as well (older versions of rmarkdown are not compatible with Pandoc 2).

**Comment by ronblum** [comment]
> pandoc_available()
[1] TRUE
> pandoc_version()
[1] ‘2.2.1’

**Comment by Courvoisier13** [comment]
@jmcphers , @ronblum 
As this dates from 2017, I'm a bit confused about which version of Rstudio has pandoc 2.2.1 bundled in it? I have RStudio-1.1.456 and pandoc --version in \bin\pandoc gives me 1.19.2.1

**Comment by jmcphers** [comment]
This applies to RStudio 1.2.

**Comment by Courvoisier13** [comment]
Ok. I'll try to update to pandoc 2.1 manually then. I need it for cross compatibility of tables (kable + kableextra) between pdf and word.

**Comment by Courvoisier13** [comment]
@jmcphers I got around to it and installed pandoc 2.3.1.

The pdf/word compatibility of kableextra didn't work and now I can't use my yaml style bibliography because of a pandoc-citeproc error 83 (https://stackoverflow.com/questions/36826916/pandoc-citeproc-error-83-with-rmarkdown-file).

Reverting to old pandoc and will give it another try when i have more time

**Comment by MattCowgill** [comment]
I also have the latest RStudio, but rmarkdown::pandoc_version() returns 1.19.2.1.

**Comment by BastiHz** [comment]
> I also have the latest RStudio, but rmarkdown::pandoc_version() returns 1.19.2.1.

This is about version 1.2. I'm on RStudio 1.2.1327 and have pandoc 2.6 and rmarkdown 1.12. You can get the previw version of RStudio [here](https://www.rstudio.com/products/rstudio/download/preview).

**Comment by ronblum** [comment]
@yuanqingye @MattCowgill Is there a version of a separately installed pandoc that is still in your PATH? Both user and system. If so, I suggest removing them entirely.

**Comment by ronblum** [comment]
Also:
1) What operating system are you running on
2) The example linked to above requires a package called `papaja`. Where is it located, or can you provide a reproducible example that isn't dependent on it? It's not a CRAN contributed package: https://cran.r-project.org/web/packages/available_packages_by_name.html#available-packages-P
