### ISSUE TITLE
support pandoc equation numbers in highlighter

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1808]
https://support.rstudio.com/hc/en-us/community/posts/115008288127-Syntax-highlighting-support-for-pandoc-eqnos-in-Rmd

---

![w7axqanaludlpfa_b6xfdq](https://user-images.githubusercontent.com/1976582/33624155-48753434-d9a8-11e7-81e3-d351ca0e9775.png)

We should allow for text following the `$$` in the background highlighter.

**Comment by masonlr** [comment]
Are there any updates on this old request? It's one reason stopping me from using RStudio at the moment. There is currently no way to simultaneously support both (i) equation numbering and (ii) inline mathjax previews.

In terms of minimal working examples, the following works as expected (with regards to cross referencing) but breaks the RStudio syntax highlighter (as explained in the issue description above):

```Rmarkdown
---
title: "mwe"
output: pdf_document
---

\begin{equation}
 a + b = c
 \label{eq:example}
\end{equation}

See Equation \ref{eq:example}.
```

The following works as expected but without the significant benefit of the inline mathjax preview:

```Rmarkdown
---
title: "mwe"
output:
  pdf_document:
    pandoc_args: ["--filter", "pandoc-crossref"]
---

$$
  a + b = c
$$ {#eq:example}

See @eq:example.
```
