### ISSUE TITLE
Unable to interact with SVN Checkout window to enter a password

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#1810]
1.1.393
RHEL 7.3

Unable to interact with SVN Checkout window to enter a password. I verified this is working correctly in 1.0.153 so something must have happened in the 1.1 release. 

![image](https://user-images.githubusercontent.com/15237845/33674351-da0fbeec-da74-11e7-9579-1cb53db12195.png)

**Comment by jmcphers** [comment]
I was able to reproduce this. We made a bunch of changes to the console code in 1.1 so probably something in the i/o is not working. I'll take a look.

**Comment by jmcphers** [comment]
Backported to 1.1 in https://github.com/rstudio/rstudio/commit/9ae05ab7f6810cd4d17d86fc34a19cd46528d4fd.

**Comment by dfalty** [comment]
Verified fixed 1.1.399.
