### ISSUE TITLE
Admin guide's Kerberos instructions are missing a link to PAM resources

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#1812]
Section 5.5.2 (Kerberos) of the _RStudio Server Professional Edition Administration Guide_ has the clause

> Please refer to the documentation linked to in [PAM Resources] 

"[PAM Resources]" should be replaced with the actual link. I think it should be section 5.4.1.3, "More Resources" (PAM).

**Comment by jmcphers** [comment]
Documentation bugs should go in the rstudio-pro tracker since that's where the documentation lives. I've fixed the bug over there.
