### ISSUE TITLE
Replace project folder location with project name on window title

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#1817]
Currently when working with a project in RStudio the window title in Windows 10 displays the location of the folder where the project is, for example "C:/Users/John/Dropbox/R/tom_cruise - RStudio". This is problematic when having several projects open concurrently and the title info gets cut off on the Windows taskbar. The most relevant part of the window title is least likely to be seen being at the end of the title.

Ideally, the folder location info would be removed leaving only the project name, for example "tom_cruise - RStudio".

**Comment by akersting** [comment]
This is not only an issue on Windows, but also on Linux. Please change this or even better: make it configurable.

**Comment by MiG-25Altfuns** [comment]
Configurable would be best, as people may only have one project and many filenames open or many projects with the same filename...

**Comment by SimonDedman** [comment]
Any update on this issue folks?

**Comment by Sibojang9** [comment]
Any update on this? It has been two years.
