### ISSUE TITLE
file:// in path prevents from reading

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#1820]
Steps to reproduce:

- Select a file in the Windows Explorer.
- Copy.
- Paste in RStudio.

A file path beginning with `file:///` (or `file://` when the file is on a network drive) is printed. This is very practical but the prefix actually prevents lots of functions from reading the file without editing the path by hand. For instance:

```r
test <- readRDS("file:///C:/Users/xxx/Documents/myfile.rds")
# Error in gzfile(file, "rb") : cannot open the connection
# In addition: Warning message:
# In gzfile(file, "rb") :
#   cannot open compressed file 'file:///C:/Users/xxx/Documents/myfile.rds', probable reason 'Invalid argument'

test <- readr::read_csv("file:///C:/Users/xxx/Documents/myfile.csv")
# Error: 'file:///C:/Users/xxx/Documents/myfile.csv' does not exist in current working directory ('C:/Users/xxx/Documents').

test <- readxl::read_xlsx("file:///C:/Users/xxx/Documents/myfile.xlsx")
# Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  :
#   Evaluation error: zip file 'file:///C:/Users/xxx/Documents/myfile.xlsx' cannot be opened.

test <- openxlsx::read.xlsx("file:///C:/Users/xxx/Documents/myfile.xlsx")
# Error in read.xlsx.default("file:///C:/Users/xxx/Documents/myfile.xlsx") :
#   File does not exist.
```

If I remove `file:///` the four above examples work fine. (OTOH, curiously, some other functions such as `read.csv` and `data.table::fread` have no problem with it)

Would it be possible to get rid of `file://`?

**Comment by kevinushey** [comment]
As an alternative, you and also try holding down the <kbd>Shift</kbd> key when you right-click a file name in Windows Explorer. You should then see a menu entry called `Copy as path`, which you can use to ensure the file is copied as a path without the `file://` prefix.

**Comment by etienne-s** [comment]
Yes I know that way but <kbd>Ctrl</kbd>+<kbd>C</kbd> is faster :)

**Comment by jmcphers** [comment]
This issue has been superseded by https://github.com/rstudio/rstudio/issues/4572.
