### ISSUE TITLE
html content width (ex: kable) in a Rstudio notebook is too small and can't be altered

### ISSUE THREAD

**Issue by devereaux** [rstudio/rstudio#1825]
text output respect the width option, head(cars) uses the full width, while html output doesn't respect the width option or use full width.

A minimal reproducible example is:

```{r}
library(car)
library(knitr)
library(dplyr)
kable(mtcars)
```
As compared to:

```{r}
htmltools::browsable(kable(mtcars, format="html"))
```

The problem seem linked to hmtltools, the html table width is limited as if full_width hadn't been set. It is not overridable by setting the chunk fig.width, or by using css table.attr options - which are still respected as we can see if we invert the color with:

```{r fig.width = 9}
opts_chunk$set(comment = "", warning = FALSE, message = FALSE, echo = TRUE, tidy = FALSE, fig.width=9)
kable(
  mtcars, format="html",table.attr = "style=\"width:100%!important; color:white; background-color: black;\""
)
```

Setting full_width=T has no effect, but setting kable_styling(full_width=F) has a respective effect:
```{r}
opts_chunk$set(comment = "", warning = FALSE, message = FALSE, echo = TRUE, tidy = FALSE, fig.width=9)
kable(
  mtcars, format="html",table.attr = "style=\"width:100%!important; max-width:none!important; color:white; background-color: black;\""
) %>% kable_styling(full_width=F) 
```

If we (improperly) use fillPage with the text output, we can see the problem is that the inclusion windows is limited in width by some margin:

```{r fig.width=9, results='asis'}
t = kable(mtcars, format="html")
tf=textConnection(t)
  shiny::fillPage(t)
```

The actual width limit seems close to 800px or 78 characters, as can be simply measured by character alignment with:

```{r}
print(rep(123456789,8))
```

The issue seems related to https://support.rstudio.com/hc/en-us/community/posts/213106048-Figure-size-in-R-Notebook-document 

Based on other reports: https://stackoverflow.com/questions/38906821/how-to-specify-figure-sizes-with-rmarkdown-html-notebooks: "figure dimensions specified in the YAML metadata (fig_height and fig_width) appear to control the container size for image (up to the page container, or something like), but the knitr chunk options (fig.height and fig.width) control the original image size. The original image is then resized to fit within the container. Further I believe that the html_notebook output format (*.nb.html) has a different stylesheet from the html output"

It is not possible to use full width by using a custom CSS header:  starting a notebook with "max-width: as in: none;" alters the html renditition of this notebook when loaded in a browser

```{text}
---
title: "Title"
output: html_notebook
---
<style>
.main-container {
  max-width: none;!important
  margin-left: auto;!important
  margin-right: auto;!important
}
</style>
```

However, it does not change the notebook chunk container size within rstudio. 

The only solution found has been a mitigation strategy: changing a default of (100% zoom,14pt font) to (110% zoom, 12pt font), which suggests a size may be hardcoded somewhere.

It causes another issue: the output of knitted files and notebook previews is inconsistent due to this hardcoded size for notebooks.

**Comment by ronblum** [comment]
Thank you @devereaux for the detailed examples and comparisons. We will take your request into consideration for future releases.
