### ISSUE TITLE
Accessing Rserver running on 8787 programmatically

### ISSUE THREAD

**Issue by apoorva007** [rstudio/rstudio#1826]
The Rserver which comes with R studio IDE runs on port 8787 and can be accessed via a web interface on the same port. The R commands or an R script can then be executed on the web interface. Wanted to know if there is a way to execute an R script over this server remotely say via a bash terminal.
One of the ways I found to execute R scripts remotely in batch mode was via remoter package(https://github.com/RBigData/remoter/blob/master/vignettes/remote_machines.Rnw) . But this demands that I open a remoter:server session on a port and then  connect via remoter:client . Seems to be bit of an overhead to start a remoter:server when Rserver is already running on 8787 and listening for remote clients.

**Comment by ronblum** [comment]
This is not currently on the roadmap for RStudio Server. However, in addition to remoter, take a look at plumber (https://www.rplumber.io/)—it's used for defining web APIs using R code, so perhaps it could be of use.
