### ISSUE TITLE
Consider an update of json_spirit library

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1830]
RStudio is using version 4.0.3 of this JSON parsing library. Latest release is several years newer, 4.0.8. Worth a peek to see if we should upgrade at some point early in a release cycle.

https://www.codeproject.com/Articles/20027/JSON-Spirit-A-C-JSON-Parser-Generator-Implemented

**Comment by jmcphers** [comment]
@kfeinauer has added RapidJson to RStudio Pro, which is (as the name implies) quite a lot faster. 1.2 will ship with both (using RapidJson only for new code), but for the next release I think that we should just flip the big switch and port everything to RapidJson. It's a huge change with significant compatibility risk so should be done very early in 1.3!

**Comment by kfeinauer** [comment]
RapidJSON has been in the 1.3 branch for some time now.
