### ISSUE TITLE
Make it possible to have multiple terminal tabs

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1831]
Several requests over the last few months to surface multiple terminals as tabs instead of (or possibly in addition to) having them in the dropdown under a single tab.

Most recent one:
https://twitter.com/briandconnelly/status/935566329368608768

**Comment by jmcphers** [comment]
Another common one is the ability to pop out the terminal into its own window (this came up in the webinar this week).

**Comment by iago-pssjd** [comment]
I was just going to open a new issue proposing either the ability to pop out the terminal into its own window as @jmcphers suggests or well having the option of changing the panel where placing the terminal, in order to be able to look simultaneously at the terminal and the console.

Thank you!
