### ISSUE TITLE
Allow editing in spreadsheet view

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#1841]
R has the `edit()` command that opens a simple spreadsheet for editing a dataframe.  On a Mac, this works reasonably well in R.app, but is quite slow and ugly in RStudio, because it falls back to an X11 spreadsheet.

RStudio has a nice dataframe viewer invoked by `View()`, or by viewing a table from the connections pane,  or clicking on a dataframe in the Environment tab.   It's quite a lot nicer than the `edit()` display, but it is read-only.  It would be nice if this display allowed editing of cell contents, and if `edit()` were connected to it.  For database connections this would need one additional callback (and perhaps the ability to scroll through more than the first 1000 rows).

**Comment by dfalty** [comment]
We haven't done this for philosophical reasons since hand editing data frames is a recipe to make work not reproducible. The request keeps showing up so I'll let the others decide if we want to keep this request open.

**Comment by gsgxnet** [comment]
True, hand editing a data.frame which contains data for analysis is not reproducible. Might become traceable and could be logged if the changes are in some way reported by an editing function.  
  
I have an other use case - in explorative analysis e.g. developing predictive models,  I have to try out different sets of predictors from many columns of the **data** `data.frame`. I do so by creating a colnames and colattributes etc **meta** `data.frame` with one preset entry column which can  be edited. Depending on the values in that **meta** `data.frame` after the manual edit for each column in the **data** `data.frame` the appropriate preprocessing is done: drop the column, convert categorial columns into several category yes/no columns, use the column after scale and center  etc.
