### ISSUE TITLE
Terminal disconnects when running server in Docker

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1844]
From community: https://community.rstudio.com/t/button-to-re-connect-to-terminal-in-rstudio-server-terminal-tab/3485

I have also repro'd this in a docker scenario. Needs further investigation to determine why the terminal isn't automatically reconnecting (the intended behavior).

**Comment by andresrcs** [comment]
It also happens when running rstudio server in AWS EC2 Ubuntu instance and it's really annoying

**Comment by gtritchie** [comment]
Investigation notes

In the repro I get on rstudio.cloud, here's the terminal diagnostics:

2017/12/15 9:16:45: WebSocket connected
2017/12/15 9:21:47: WebSocket closed
2017/12/15 9:43:03: Disconnected

In the second stage (websocket closed), which looks like it happens after five minutes of inactivity, the reported behavior takes place. Typing in terminal is a no-op, and the Javascript console shows: `Tried to send user input over null websocket`.

If I wait for the "disconnected" state to take place, then the terminal will reconnect the way it is supposed to.

**Comment by jmcphers** [comment]
Backported to 1.1 in d2bcc3b40777a5a2d451ee18adc9cf12cb2ca90b.

**Comment by ronblum** [comment]
@andresrcs, there’s a preview release at
&nbsp;   https://www.rstudio.com/products/rstudio/download/preview/
which is a patch for 1.1. It addresses this issue—would you be willing to try out it and see if the issue is resolved? You might still see a message in the console, but the terminal should reconnect.

**Comment by andresrcs** [comment]
@ronblum, I had some problems installing it, because installation fails with python 3.6 I had to change my python3 alternatives to 3.5 but... The terminal reconnects!

**Comment by ronblum** [comment]
Excellent @andresrcs, thank you!
