### ISSUE TITLE
Git "review changes" panel does not show files with Chinese names properly

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#1847]
See the following screenshot. The name of the first file is Chinese, and it can not be displayed.

![image](https://user-images.githubusercontent.com/13306020/33978126-111211d2-e0d9-11e7-9116-b2b39f2d58fa.png)

**Comment by dfalty** [comment]
I can reproduce this as well on the latest 1.2 Mac build (1.2.209). Thanks for the report!
![image](https://user-images.githubusercontent.com/15237845/34003399-d1a4483a-e0ba-11e7-9663-676b33a8e238.png)

**Comment by kevinushey** [comment]
Fixed with https://github.com/rstudio/rstudio/commit/c34c3b07423f5ba11b356826a70daa0f7d2c282f. Thanks for reporting!
