### ISSUE TITLE
Qt 4.8 vs. Qt 5

### ISSUE THREAD

**Issue by Mailaender** [rstudio/rstudio#1848]
Hi, I am currently trying to package R Studio for @openSUSE. The instructions say I need Qt 4.8 https://github.com/rstudio/rstudio/blob/master/dependencies/linux/README#L12 but cmake from current stable demands Qt 5 https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/CMakeLists.txt#L79 Are the instructions outdated? Do I need both?

**Comment by kevinushey** [comment]
Sorry, the instructions are indeed outdated. We currently build RStudio against Qt 5.4.2, and for our binaries we actually bundle the Qt components that we use. For what it's worth, the Qt installer script we use for Linux lives here:

https://github.com/rstudio/rstudio/blob/master/dependencies/linux/install-qt-sdk

We do plan on upgrading to Qt 5.9.2 (or perhaps Qt 5.9.3) with the next release of RStudio, hopefully coming sometime next year.
