### ISSUE TITLE
Cannot pop out the content from the Viewer or Preview Window to external browser

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#1851]
With the current release of RStudio (v1.1.383) and preview version v1.1.398, I can no longer open the page in the viewer or preview window in an external browser. It is only reproducible for me on macOS, and I wonder if others can reproduce it. Basically this fails for everything, no matter if it is the HTML output of an R Markdown document, or a Shiny app (e.g. `shiny::runExample('01_hello')`), or anything. When I click the icon ![image](https://user-images.githubusercontent.com/163582/34002017-27604728-e0b7-11e7-9d1f-a1be1b894472.png), it shows a blank page in a new browser window, and the address bar is empty.

**Comment by yihui** [comment]
I updated Xcode yesterday, and I'm not sure if that is relevant. I'm on macOS High Sierra 10.12.1 at the moment. I'll try to update to 10.13.2 and see if anything changes.

**Comment by yihui** [comment]
Upgraded to macOS 10.13.2, and problem solved.

**Comment by rafaveguim** [comment]
I'm currently experiencing this issue on High Sierra 10.13.3, RStudio Version 1.1.423.
