### ISSUE TITLE
Implement PowerPoint output format support for R Markdown presentations

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1852]
Pandoc 2.0.5 [adds support for PowerPoint output](https://pandoc.org/releases.html#pandoc-2.0.5-12-december-2017), and the rmarkdown package is adding a PowerPoint [output format](https://github.com/rstudio/rmarkdown/tree/feature/powerpoint). 

We should add PowerPoint output integration in the IDE, at roughly the same level of support we have today for R Markdown Word output. This means:

- [x] Advertising it as an available output type in the type switcher;
- [x] Surfacing its output options in the output option editor dialog; and
- [x] Performing some level of synchronization with PowerPoint on the desktop to make it easier to iterate (sync to slide after render, or remember position).

Depends on https://github.com/rstudio/rstudio/issues/1807.

**Comment by ronblum** [comment]
Verified on multiple version of MacOS, Windows, and Linux.
