### ISSUE TITLE
Bundled dependencies

### ISSUE THREAD

**Issue by Mailaender** [rstudio/rstudio#1853]
Another problem of my attempt to submit R Studio to @openSUSE are the bundled dependencies. The build machines don't have internet access for security reasons. Also Linux distributions like to review code only once to ease maintenance. So far I identified:

* core-dictionaries.zip (hunspell?)
* mathjax-26.zip
* pandoc-1.17.2.zip
* libclang
* Qt5 (seems to allow system Qt with `-DQT_QMAKE_EXECUTABLE=OFF`)

https://build.opensuse.org/package/show/home:Mailaender:branches:devel:languages:R:released/rstudio

Is it possible to make the build system scan the system instead of the `dependencies/common` folder?

**Comment by jmcphers** [comment]
This is indeed something we'd like to do. We're currently tracking the work in https://github.com/rstudio/rstudio/issues/1614.
