### ISSUE TITLE
Feature Request: Project Sharing Access Configuration

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#1854]
Greetings and Salutations,

I've recently been experimenting with the [Sharing Projects in RStudio Server Pro](https://support.rstudio.com/hc/en-us/articles/211659737-Sharing-Projects-in-RStudio-Server-Pro) feature in RStudio. The issue I am running into is I want to _share_ a project with students but I do **not** want them to be able to edit or add content to the document unless I explicitly give them permission. As it currently stands, if a project is shared with students, then they can modify and edit every aspect of it regardless of whether it is beneficial or negative.

I am requesting the ability to set fine grain access controls for users, e.g:

- Create
- Read
- Update
- Delete
- Admin

This would make having RStudio Server Pro a much better solution for a live coding environment as students will have direct access to instructor code within a familiar environment compared to the present status quo of using a dropbox refresh hack on the code text file.

Sincerely,

JJB

**Comment by jmcphers** [comment]
This issues page is specifically for the open source version of RStudio; for feature requests that are specific to RStudio Server Pro, we recommend you get in touch with our Pro support team. I'm closing this here, but I've filed your issue for Pro for consideration.

If you don't need ongoing sync (and just need your students to have a copy of your project to work with), you might consider using a feature we just added which allows you to set the "first project" that RStudio users get when they first access their account. You can read about it here:

http://docs.rstudio.com/ide/server-pro/r-sessions.html#first-project-template

Hope this helps, and do get in touch with our support team if it doesn't; I'm not sure what your dropbox refresh hack is but hopefully something more elegant is possible!

**Comment by coatless** [comment]
@jmcphers Apologies. I wasn't aware. Would it be possible to add the Pro server remark to https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md ?

**Comment by jmcphers** [comment]
That's a great idea. I've just done so: https://github.com/rstudio/rstudio/commit/7647e17567ae460c724d9362b02a16d97777503b

**Comment by coatless** [comment]
Thank you!
