### ISSUE TITLE
Focus stealing of RStudio dialog boxes on windows

### ISSUE THREAD

**Issue by jwhendy** [rstudio/rstudio#1859]
I haven't used RStudio in a while on Windows 7 (mostly run linux). I ran `update.packages()` and slogged through all the `y` entries to update maybe 50 of them. I couldn't do *anything* for a while after as the RStudio status dialog showing the download progress for each package continued to pop up in front of whatever I tried to use.

Is this known? If so, is this a Windows issue or is there some way that you can tell these windows to stay in the background and let me continue on with my work?

**Comment by kevinushey** [comment]
This is how R works on Windows (and unfortunately I don't think there's a simple way to opt out of this behavior; RStudio doesn't have any control here)

**Comment by jwhendy** [comment]
Understood, and thanks for the input. Mainly wanted to be sure this wasn't a fluke. It's pretty fringe I'd have so many popups, but wanted to mention it anyway.

Thanks!
