### ISSUE TITLE
Terminal websocket closed by proxy due to inactivity

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1860]
Running RStudio Server behind a proxy configured with a read-timout (for example, nginx with  proxy_read_timeout option). Start a terminal session using websockets. Now don't do anything in RStudio and wait for the timeout to expire.

Ideally, terminal should send occasional keepalive messages, but currently it does not. So, this may appear in the console, and websocket is closed.

```
[fatal] handle_write_frame error: websocketpp.transport:10 (A transport action was requested after shutdown)
```
Now, due to #1844, terminal cannot be used.

We should consider a websocket keepalive message to prevent websocket death, but don't want it to also keep the rsession alive.

We also have reports of this from containerized hosting of RStudio Server.

**Comment by gtritchie** [comment]
Bumping up priority. This shows up frequently in rstudio.cloud.

**Comment by dfalty** [comment]
Verified 1.2.451-1.
