### ISSUE TITLE
Feature request: Shortkey for the View() function

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#1861]
Hi,

Can we have a keyboard short-key for the View() function: It could work on dataframes/variables in the same way that F2 works on functions. When we are on a dataframe/variable and press that bottom, the View window shows the data frame/variable.

Because of the frequent use of the View() function, I think it would be a particularly helpful feature.

**Comment by jmcphers** [comment]
We do have this, and it's F2. :-) If you press F2 on the name of a data frame, and that data frame exists in your global environment, it should appear in the data viewer.

If you aren't seeing this, would you be willing to share the code you're pressing F2 on (and surround lines) along with the code that generated the data frame?

**Comment by hzarkoob** [comment]
It does not seem to work for me. I have tested both RStudio desktop and server.

A sample code I have tried:
sampleDataFrame = data.frame(matrix(1:12, 3, 4))

The F2 shortkey does work for functions though on both RStudio desktop and server.

**Comment by hzarkoob** [comment]
BTW, the documentation only refers to the applicability of the F2 shortkey for functions.
https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts

**Comment by ronblum** [comment]
F2 is working on data frames for me, but not for functions.

Windows:
- Data frame: PASS
- Function: FAIL - nothing

Mac
- Data Frame: PASS
- Function: FAIL - nothing

Server (Ubuntu)
- Data Frame: PASS
- Function: two errors
   Editor pane: `Error in loadNamespace(name) : there is no package called ‘.GlobalEnv’`
   Console: `# ERROR: Definition of function 'f1u' not found in namespace '.GlobalEnv’`

**Comment by etienne-s** [comment]
Is this issue solved? I've noticed that in 1.1.423 <kbd>F2</kbd> now works on both dataframes and functions. Tested on Linux and Windows but not on Mac.

(However it's still undocumented, and it does not work on other objects such as lists and vectors.)

**Comment by kevinushey** [comment]
Thanks for pointing that out -- now that we have the object explorer, we should try implementing <kbd>F2</kbd> for all R objects.

**Comment by hzarkoob** [comment]
I no longer see the issue in the new release. Thank the Studio team for the fix, and @etienne-s for pointing out to the fix.

Including this change in the documentation makes it perfect.

**Comment by BigTimeStats** [comment]
I have the F2 on function error in both RStudio 1.1.383 and 1.1.423:

https://stackoverflow.com/questions/49162316/error-when-trying-to-view-user-defined-function-using-f2-and-source

**Comment by kevinushey** [comment]
Can you please provide a reproducible example?

**Comment by BigTimeStats** [comment]
> Can you please provide a reproducible example?

I'm not quite sure how to reproduce clicking F2 on the keyboard. My link explains how to reproduce the results.

Anyway, try this:

Save in local directory:
https://github.com/BigTimeStats/Test/blob/master/some_function.r

```
source('some_function.r')
some_function # Click F2
```

**Comment by kevinushey** [comment]
I missed your explanation as to how the issue could be reproduced in the linked example, so thanks for providing it here.

I've reproduced the issue locally and will take a look.

**Comment by BigTimeStats** [comment]
> I missed your explanation as to how the issue could be reproduced in the linked example, so thanks for providing it here.
I've reproduced the issue locally and will take a look.

No worries, thanks for looking into it. 

Any update on this?

**Comment by S-UP** [comment]
Same here. A bit annoying since it is very helpful to look up how user-written functions are defined... Thanks a lot for looking into this!

**Comment by playmobilmeister** [comment]
> 
> 
> Same problem as the above commenters - using latest version (1.1.463)

same

**Comment by BastiHz** [comment]
> > Same problem as the above commenters - using latest version (1.1.463)
> 
> same

Version 1.2 ist out now. Have you tried it?
