### ISSUE TITLE
Changing zoom settings in Global Options freezes the app

### ISSUE THREAD

**Issue by FarzanT** [rstudio/rstudio#1862]
Hello, 
Even though I have tried reinstalling the application twice, whenever I change the zoom level in the appearance pane of global options, right after I click `apply` or `ok`, the app becomes unresponsive and the only way to continue is to kill it via the task manager. (This is taking place under Windows 10, the macOS version doesn't have a zoom option)
Furthermore, I have been unable to locate the zoom settings in the `user-settings` file under `Rstudio-desktop\monitored\`.
Any help would be greatly appreciated, as RStudio is unusable with its current zoom settings with a 4K monitor.

Thank you.

**Comment by angelo-pereira** [comment]
Hello

Same here on a Windows 8. After zooming to 130% for a call, I was never able to switch back to 100%, even after uninstalling, rebooting and re-installing (and even updating) RStudio.

**Comment by kevinushey** [comment]
On Windows, the zoom level is saved in a file located at:

```
%USERPROFILE%\AppData\Roaming\RStudio\desktop.ini
```

For example, on my machine, it's located at:

```
C:\Users\kevin\AppData\Roaming\RStudio
```

Is it possible that this file, or the directory containing the file, is not accessible by RStudio for some reason?

**Comment by angelo-pereira** [comment]
Hi Kevin,
Thanks a lot!

Apparently I had a "desktop.ini.lock" file that got stuck there and kept me from changing zoom (at least).
By changing the "desktop.ini" file I opened RStudio in the correct zoom and deleting "desktop.ini.lock" has reverted the behaviour.

All back to normal.

Thanks.

**Comment by kevinushey** [comment]
Awesome! Glad that this helped you get to the bottom of the issue.

RStudio should attempt to recover from this state a bit more gracefully, so perhaps we can leave this open as a bug report (+ a clue to any other users who bump into this issue)

**Comment by kevinushey** [comment]
Should be fixed in the latest daily builds via https://github.com/rstudio/rstudio/pull/2492.

**Comment by Christine-Conn** [comment]
I have a problem with settings. When I go into settings to test voice and video, settings just freeze. Why would that be and how can I fix it? Thank you in advance.
