### ISSUE TITLE
R presentation title slide does not support superscripting the date

### ISSUE THREAD

**Issue by taranraj123** [rstudio/rstudio#1863]
I'm attempting to superscript the date in the title slide of an R presentation but haven't been able to do so successfully.

I'm working on a macbook pro, running Sierra and RStudio Version 1.1.383.

i.e., doing this,

```{r}
author: Gordon Freeman
date: December 12^th 2017
autosize: true
```
knits like so,

```{r}
Taran Raj
December 12^th 2017
```

This isn't an issue on non-title slides.

**Comment by ronblum** [comment]
@taranraj123 It appears that the code is missing the closing caret in the sample code. Try changing `December 12^th 2017` to `December 12^th^ 2017`—that should take care of the problem.

**Comment by taranraj123** [comment]
@ronblum thanks for looking into this issue. 

Your proposed fix doesn't work. I attempted this but didn't explicitly mention it in my initial issue message.

**Comment by ronblum** [comment]
@taranraj123 I apologize—the solution I gave you is for R Markdown, not R Presentations. I'll reopen this as a bug to review.

**Comment by taranraj123** [comment]
Thanks @ronblum. The issue still appears closed to me.
