### ISSUE TITLE
Support signing of git commits

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1865]
cc: https://support.rstudio.com/hc/en-us/community/posts/115009819048-git-commit-add-extra-arguments

---

> Some open source projects required that each commit is signed off. This is done by the -s option of git commit. This is currently not available in the current IDE.
> 
> Maybe add the option to set extra arguments 1) in the "Commit" dialog 2) set defaults in Tools > Project Options and Tools > Global Options

**Comment by pat-s** [comment]
@kevinushey Is this still on the roadmap? Noticed this today after using signed commits in my daily workflow.

**Comment by maf654321** [comment]
Would also like to voice my interest in this feature.

**Comment by mpdougherty** [comment]
The git global setting commit.gpgsign works for me. 

`git config --global commit.gpgsign true`

**Comment by pat-s** [comment]
> The git global setting commit.gpgsign works for me.

Does it work in the GUI git editor? It always worked in the terminal.

**Comment by aja08379** [comment]
Full UI support for signing commits, without command-line interaction, requested by a pro customer in support request 73468

**Comment by kimjj93** [comment]
Hi,
Are there any updates on this?  Thank you.

**Comment by timtmok** [comment]
This change is now in the Desert Sunflower dailies. Although, looking at it now, it might make more sense to move the option to where the amend commit and commit buttons are located.

![Image](https://github.com/rstudio/rstudio/assets/9591545/a5aca2ef-c681-4519-ae15-007c71e14151)

**Comment by kevinushey** [comment]
> This change is now in the Desert Sunflower dailies. Although, looking at it now, it might make more sense to move the option to where the amend commit and commit buttons are located.

I think I agree with that. I'd also say we could name the option "Sign commit" instead of "Signed Commits".

**Comment by jonvanausdeln** [comment]
@timtmok was there going to be an option in Global options? Or just in the commit dialog?

**Comment by timtmok** [comment]
@jonvanausdeln it's just the commit dialog. The option is saved for the next time a commit is performed. It didn't make sense to add an option globally and it's likely to want to set it at commit time.

**Comment by jonvanausdeln** [comment]
Verified on [2023.09.0-daily+301](https://dailies.rstudio.com/version/2023.09.0-daily+301)
Windows 11

Git commit signing works as expected.

**Comment by kevinushey** [comment]
It's also available via the Command Palette, so users do have a way of accessing the option outside of the commit dialog if necessary.

<img width="626" alt="Screenshot 2023-08-07 at 10 36 04 AM" src="https://github.com/rstudio/rstudio/assets/1976582/8b4e8a2f-abfd-46d6-9689-fc9e6b7730a0">

**Comment by jeffkeller-einc** [comment]
Is there any documentation for how to use the new commit signing feature?

When pressing the Commit button with "Sign commit" checked, I expected a prompt to ask me to unlock my key, but instead I get an error:

```
error: gpg failed to sign the data
fatal: failed to write commit object
```

It works as expected if I first unlock my key from the terminal.

**Comment by timtmok** [comment]
@jeffkeller-einc that is certainly not a helpful error message. I'll open an issue for this.
