### ISSUE TITLE
Unnecessary lint message when Chinese characters are used in rmarkdown chunks

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#1866]
See the following screenshot

![image](https://user-images.githubusercontent.com/13306020/34113636-50b2b8b2-e44b-11e7-8895-10ecde63ef7e.png)

The code example is as follow:

````r
---
title: "Title"
subtitle: "Sub"
date: "2017年12月8日"
output:
  word_document:
    toc: true
    fig_caption: true
    reference_docx: docs/word-styles-reference-report.docx
---

```{r load packages and data, include=FALSE}
# load packages
library(tidyverse)
library(extrafont)
# configuration settings
data_folder <- "test"
ability_names <- c("执行功能", "记忆力")
meta_vars <- c("userId", "姓名", "性别", "学校", "年级", "班")
lesson_vars <- c("语文", "数学")
rnk_cutedges_ability <- qnorm(c(0, 0.3, 0.7, 0.9, 1)) * 15 + 100
# load data
user_data <- read_rds(file.path(data_folder, "user_data.rds")) %>%
  filter(!is.na(姓名)) %>% 
  gather("能力", "得分", 持续注意:自控力, na.rm = TRUE) %>%
  # score of 0 indicates missing data
  mutate(得分 = ifelse(得分 == 0, NA, 得分)) %>%
  # some users have more than one record
  group_by_at(vars(one_of(c(meta_vars, "能力")))) %>%
  mutate(rank = row_number(desc(得分))) %>% 
  ungroup() %>% 
  filter(rank == 1)
```
````

**Comment by cuttlefish44** [comment]
This problem happened on my Japanese env.
I uses Rstudio (ver. 1.1.383) on Windows OS (Vista_32bit and 7_64bit).

The code is below;

    ---
    output: 
      html_document:
        md_extensions: -ascii_identifiers
    ---
    
    ```{r}
    data <- data.frame(列 = c(1, 2))
    
    data
    sessionInfo()
    ```

Here is a window of Rstudio and the output (Knit runs correctly).
[https://i.imgur.com/fUSwSok.png](https://i.imgur.com/fUSwSok.png)

**Comment by cuttlefish44** [comment]
[Reflection of Rstudio support] [In .Rmd file, does Rstudio treat CP932 correctly at windows OS ?](https://support.rstudio.com/hc/en-us/community/posts/115007973813-In-Rmd-file-does-Rstudio-treat-CP932-correctly-at-windows-OS-)

Unfortunately, I still see the same issue with RStudio v1.1.408.

**Comment by jinlin82** [comment]
I have same problem with Chinese characters.
But Rstudio 0.99.903 does not have this problem.
However, Rstudio 0.99.903 does not have inline image and math preview ablity.

**Comment by jinlin82** [comment]
A Korean user may have the same problem, too.
https://stackoverflow.com/questions/43833096/r-warning-message-in-strsplitcode-n-fixed-true-input-string-1-is-i

**Comment by san-shiro** [comment]
The problem persists in the latest stable RStudio build if the locale is set to CP932. I would like to add that the problem occurs even if .rmd is encoded in UTF-8.

Windows version10.0.16299.214
RStudio 1.1.423
R 3.4.3

**Comment by dehuili** [comment]
try this way.

Sys.setlocale("LC_ALL","English_United States.1252")

**Comment by san-shiro** [comment]
Thank you duhuili. However, by doing so, the code stops at any lines that contain Japanese characters.

Error: \uxxxx sequences not supported inside backticks (line 2)

**Comment by psychelzh** [comment]
Is there any news about this? @kevinushey

**Comment by kevinushey** [comment]
Sorry, I haven't had a chance to tackle this yet.

**Comment by psychelzh** [comment]
Thanks! I do not know whether these issues #2998 #1847 are related, but they make me deem that "encoding character set" is just so troublesome so that non-ASCII characters tend to error in `RStudio`. Hopefully, these issues will be solved in future. 😃
