### ISSUE TITLE
Feature Request: Variable subset code generation for data.frame/tibbles

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#1867]
When working in _RStudio_, the `list` data structure has a convenient "helper" to generate the subset command for accessing a particular element in the list as shown in: 

![Screenshot courtesy of [Joyce Robbins](https://twitter.com/jtrnyc/status/938499055797329922)
](https://pbs.twimg.com/media/DQY317BWkAAeXYi.jpg:large)

However, the same cannot be said for `data.frame` or `tibble` structures. Only the ability to view the data matrix in completion is present.

As an example, we have:

```r
df_ex = data.frame(a = 1:5, 
                   b = letters[1:5],
                   stringsAsFactors = FALSE)

library("tibble")
df_ex_tibble = tibble(a = 1:5, 
                      b = letters[a])
```

<img width="714" alt="environment" src="https://user-images.githubusercontent.com/833642/34118175-a54573fa-e3e3-11e7-9d46-69697f418720.png">

Would it be possible to allow a button click to generate the variable subset command for `data.frame` and `tibble` classes? This would allow students to have additional support when working with 2D data.

**Comment by kevinushey** [comment]
One thing we might consider that could enable this: perhaps the environment pane could start using / sharing code from the object explorer, so the experience is effectively the same? (The environment pane is effectively just a somewhat more primitive object explorer for environments on the search path)

One main difficulty is that the object explorer doesn't attempt to preserve existing reference counts on the objects inspected -- ie, we currently use R-level APIs to inspect the objects, and those tend force a bump in the reference count.

**Comment by jmcphers** [comment]
The environment pane already has that problem for many object types; see https://github.com/rstudio/rstudio/issues/1842 for some discussion. So adding the object explorer isn't actually going to make things worse, as long as we import some of the filtering we do at the C level which makes sure we don't accidentally force promises, fire active bindings, evaluate calls, etc. 

I'd be a fan of moving to shared code for the object explorer/env pane; `View(.GlobalEnv)` is an example of what this could look like. We could then take on work separately to migrate that newly shared introspection code to C++ (a la https://github.com/hadley/lobstr). We'll need to prioritize against the rest of our backlog so no guarantees we'll have time to tackle it soon, but I do think it's worth doing.
