### ISSUE TITLE
Rstudio resets width option when running shiny app in Viewer + overflow

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#1870]
Not sure if this issue is best posted here or on the Rstudio community site (see https://community.rstudio.com/t/rstudio-resets-width-option-when-running-shiny-app-in-viewer/3661)

When I run a shiny app in the Rstudio Viewer `options(width = ...)` is reset by Rstudio when you change the width of the Viewer window. As an example, if you open the app below in Viewer and change the size of the Viewer window `getOption("width")` will not return 250

A somewhat related issue is that Viewer seems to ignore CSS for handling overflow (see below). The CSS does work in Chrome and Firefox.

```{r}
library(shiny)

options(width = 250)

# Define UI for application that draws a histogram
ui <- fluidPage(
  tags$head(tags$style(HTML("pre { overflow: auto; }"))),
  verbatimTextOutput("df")
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   output$df <- renderPrint({
     data.frame(matrix(1:60, ncol = 60))
   })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

The CSS overflow setting should ensure a wide data.frame or matrix will not be wrapped and the user can scroll to see the section that does not show on screen (see screenshot in Chrome)

![image](https://user-images.githubusercontent.com/2998956/34129052-97121cca-e3f7-11e7-9279-4b052d11fd42.png)

In the Rstudio Viewer the printed data.frame will be wrapped, even if the `options(width = ...)` setting is sufficient (i.e., the CSS overflow setting seems to be ignored) 

![image](https://user-images.githubusercontent.com/2998956/34129104-bd0e4462-e3f7-11e7-8cbf-9cad647f8aa0.png)

**Comment by ronblum** [comment]
I am able to reproduce this on Mac Desktop 1.1.399. And it works correctly on RStudio Server 1.1.399 running on Ubuntu, viewed on Chrome.

**Comment by vnijs** [comment]
Thanks for checking @ronblum! I upgraded Rstudio Server Pro to 1.1.402. The overflow issue does not occur when viewing Rstudio Server Pro in Chrome but still occurs when viewed in Safari.

On Rstudio Server and Rstudio Desktop the `options(width = ...)` change still occurs when the user changes the size of the Viewer window. I created a better example of the issue I'm below. If you run the app and then click on the `print` radio button you see "Width: 250". However, if you start the app, then change the width of the Viewer panel in Rstudio, and **then** click on the `print` radio button in the app you'll see that the width has changed. This occurs in Chrome as well as Safari when the app is run `external` and also when run in the Rstudio Viewer. Screenshot added.

```
options(width = 250)

ui = fluidPage(
  tags$head(tags$style(HTML("pre { overflow: auto; }"))),
  sidebarLayout(
    sidebarPanel(
      radioButtons("display", "Display:",
        c("str" = "str", "print" = "print"),
        selected = "str",
        inline = TRUE
      )
    ),
    uiOutput("mp")
    ## if we use the mainpanel specs below rather than 
    ## uiOutput("mp"), options(width = ...) is not changed
    # mainPanel(
    #   conditionalPanel("input.display == 'str'", 
    #     verbatimTextOutput("str")
    #   ),
    #   conditionalPanel("input.display == 'summary'", 
    #     verbatimTextOutput("print")
    #   )
    # )
  )
)

server = shinyServer(function(input, output, session) {

  output$str <- renderPrint({
    str(mtcars)
  })

  output$print <- renderPrint({
    cat(paste0("Width: ", getOption("width"), "\n\n"))
    print(data.frame(matrix(1:120, ncol = 60, nrow = 2)), row.names = FALSE)
  })

  output$mp <- renderUI({
    mainPanel(
      conditionalPanel("input.display == 'str'", 
        verbatimTextOutput("str")
      ),
      conditionalPanel("input.display == 'print'", 
        verbatimTextOutput("print")
      )
    )
  })
})

shinyApp(ui = ui, server = server)

```

![image](https://user-images.githubusercontent.com/2998956/34287569-ed2fcdc6-e69c-11e7-86af-1e8965914571.png)

**Comment by vnijs** [comment]
FYI I was able to address the overflow issue in safari and the Rstudio viewer using the CSS below:

`tags$head(tags$style(HTML("pre { overflow: auto; word-wrap: normal; }"))),`

However, Rstudio still adjusts `options(width = ...)` as shown in my previous comment

**Comment by jmcphers** [comment]
This is as designed; when you change the size of the R console, RStudio needs to update `width` appropriately. There's no way for us to ascertain that the behavior is not wanted in this case. The best solution here is to run your Shiny app in a separate R process so it isn't affected by the main R session's IDE integration. This issue is tracking that feature (and has workarounds): https://github.com/rstudio/rstudio/issues/5190
