### ISSUE TITLE
incorrect cursor position if zoomed in

### ISSUE THREAD

**Issue by Thermi** [rstudio/rstudio#1872]
When one zooms into rstudio using ctrl++, the displayed cursor position does not correspond to the cursor position in the text anymore. That makes it very difficult to work with rstudio
In the screenshot "createDataPartition" was selected using a double click with the left mouse button. rstudio obviously marks a different part of the line. It also behaves as if the cursor was offset.
For clarification: I'm talking about the _text_ cursor, not the _mouse_ cursor.
![bildschirmfoto_2017-12-19_18-47-24](https://user-images.githubusercontent.com/3606849/34170963-11fe5b1a-e4ed-11e7-9fab-57a5bdfd84e3.png)
.

**Comment by kevinushey** [comment]
It looks like you're using a non-monospace font. Currently, only monospaced fonts are supported / properly rendered in the RStudio source editors.

**Comment by Thermi** [comment]
That seems to have been a case of insane defaults. It works after selection another font in the options. I did not change that setting before.

**Comment by kevinushey** [comment]
Strange! It's hard to guess why, but one hypothesis might be that RStudio was set up to use a certain font on your system, but that font was removed, and so RStudio defaulted back to a non-monospace font for some reason.

I think we've had a couple reports of this sort of thing from users who recently updated Windows, or Microsoft Office. Could that be true in your case?

**Comment by Thermi** [comment]
I'm on (Arch) Linux, so this seems to be some sort of universal problem with rstudio.

**Comment by jmcphers** [comment]
@Thermi What font did you wind up selecting? Also, is the Lucida Sans font available on your system? That's our default on Linux, and I wonder if it might just be missing on Arch.

https://github.com/rstudio/rstudio/blob/54cd3abcfc58837b433464c793fe9b03a87f0bb4/src/cpp/desktop/DesktopOptions.cpp#L163-L167

**Comment by Thermi** [comment]
That font is available.

**Comment by jmcphers** [comment]
> Why permit selection a non-monospace font at all if it doesn't work properly?

We try not to! We query the system for only monospace fonts. For some reason this one's being considered monospace. 

We've revamped the font loading in 1.2, so this should now work properly. Please try with RStudio 1.2.5019 and the latest version of the `fontconfig` package for Arch Linux, and reopen if you're still seeing this.
