### ISSUE TITLE
report what RStudio is doing during initialization

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1873]
Motivated by https://community.rstudio.com/t/cant-open-rstudio/3611/11 + a number of other issues reported by users over the years.

RStudio can fail for a lot of reasons during initialization (before the IDE surface is brought up). Unfortunately, diagnosing these is often difficult as RStudio does not provide any indication as to what exactly it (or R) is doing during startup. It'd be nice if we could teach RStudio to report what it's doing during initialization -- especially for e.g. restoring a large R workspace.

**Comment by jmcphers** [comment]
We've made this dramatically better in 1.3 with the addition of cancelable R session restoration and detailed startup log failures in RStudio Desktop.
