### ISSUE TITLE
Build pane does not report DESCRIPTION file errors well

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1874]
https://support.rstudio.com/hc/en-us/community/posts/115009771468-Possible-Bug-Malformed-DESCRIPTION-file

---

I'm developing an R package that I plan to submit to CRAN. While creating my DESCRIPTION file, I accidentally forgot to indent one of the lines of the "Description:" field. 

 

When running devtools::check(), RStudio says:

 

ERROR: The build directory does not contain a DESCRIPTION
file so cannot be built as a package.
Which is not very clear as to the source of the problem.

 

When running devtools::check() directly via R command line, it provides a more helpful message:

    Error in read.dcf(path_desc) :
    Line starting 'classification syste ...' is malformed!

This seems like a bug - is it possible to have RStudio report a better error message?

**Comment by MichaelChirico** [comment]
Agreeing with this. This might also be a new issue, but I created a `DESCRIPTION` according to the specification here:

https://www.r-project.org/Licenses/MIT

But RStudio doesn't like having a space-separated DCF field:

```
COPYRIGHT HOLDER: Michael Chirico
```

Only by luck of noticing that _only_ this field was not blue-highlighted in the editor was I able to back out that this might be the source of RStudio `Build` not working.

**Comment by kevinushey** [comment]
You might be misunderstanding the instructions there: those fields need to be part of a separate file called `LICENSE`; they shouldn't be added to the `DESCRIPTION` file. (You should only add `License: MIT + file LICENSE` to the DESCRIPTION)

**Comment by MichaelChirico** [comment]
confusing formatting... must have read it 5 times without getting it but it's clear you're right now. thanks! still, a more helpful error in RStudio would have been great 😬
