### ISSUE TITLE
Terminal becomes terminally "busy" for multi-page man pages

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#1875]
If I browse a multi-page man page in an RStudio Terminal, I can neither advance through the pages, nor exit the man page. `man git rebase` will induce the behaviour. That terminal becomes terminally "busy" 🙂 and has to be closed.

**Comment by ronblum** [comment]
You can't even exit with <cmd>Ctrl-C</cmd> or stop with <cmd>Ctrl-Z</cmd>.

**Comment by gtritchie** [comment]
Worried this is a symptom of a bigger problem, so will look soon.

**Comment by rmflight** [comment]
This does **not** seem to affect me, RStudio 1.2.203, Unbuntu 14.04.

Is this a Mac issue? That would be disconcerting.

**Comment by gtritchie** [comment]
It is intermittent for me on Mac. Haven't figured out what triggers it (or fixes it). Haven't yet tried on the other platforms.

**Comment by ccg** [comment]
This problem struck me with `less`, and with `man`, which I believe uses `less` for paging. I'm on a Mac with RStudio 1.1.442. Basically, `less long_file` or `some_process | less` will result in a stuck terminal.

**Comment by gtritchie** [comment]
Anyone been able to repro with a 1.2 build? Curious if the more up-to-date Javascript engine helps. May very well be fixed via an xterm update. #1923

**Comment by ccg** [comment]
I'm seeing identical behavior on Version 1.2.411

**Comment by kevinushey** [comment]
This seems to reproduce reliably for me:

```
writeLines(as.character(1:1E3), "big.txt")
.rs.api.terminalExecute("less big.txt")
```

Then, type <kbd>Ctrl + G</kbd> to (attempt to) scroll to the bottom of the page. That attempt fails and seems to lock up the terminal. Actually, any attempt to scroll within `less` seems to trigger this (at least for me).

**Comment by kevinushey** [comment]
Some terminal diagnostics, in case it's helpful -- this is after attempting to scroll a bit, then pressing <kbd>Q</kbd> to quit `less`.

```
Global Terminal Information
---------------------------
Loaded TerminalSessions: 1
Handle: '227C0586' Caption: 'Terminal 1'

Terminal List Count: 1
Handle: '227C0586' Caption: 'Terminal 1' Session Created: true

Current Terminal Session Information
------------------------------------
Caption:     'Terminal 1'
Title:       'less big.txt'
Cols x Rows  '70 x 14'
Shell:       'User command'
Handle:      '227C0586'
Sequence:    '1'
Restarted:   'false
Busy:        'false'
Exit Code:   '0'
Full screen: 'client=true/server=true'
Zombie:      'true'
Track Env    'false'
Local-echo:  'true'
Working Dir: 'Default'
Interactive: 'Never'
WebSockets:  'true'
Typing lag:  '0ms'

System Information
------------------
Desktop:    'true'
Platform:   'Mac'

Connection Information
----------------------
2018/3/15 19:10:00: Connect WebSocket: 'ws://127.0.0.1:6637/terminal/227C0586/'
2018/3/15 19:10:00: WebSocket connected
2018/3/15 19:12:36: Permanently Disconnected
2018/3/15 19:12:36: WebSocket closed
2018/3/15 19:12:36: Disconnected

Local-echo Match Failures
-------------------------
<none>
```

**Comment by gtritchie** [comment]
Still won't repro for me (tried with 1.1.442). I **have** encountered this in the past, but still not sure what the variable is to trigger it.

I do consistently get a different problem (at least today) if I start a new terminal, and the first command I run is `less big.txt`--it doesn't use the full size of the terminal. If I start moving forward then backwards, it does correct itself, but I start seeing other visual issues such as large blank areas in the terminal.

![2018-03-16_11-06-44](https://user-images.githubusercontent.com/10569626/37537246-2cec9c8c-290a-11e8-8aa1-34fb906258e0.png)

![2018-03-16_11-06-09](https://user-images.githubusercontent.com/10569626/37537249-2f1b4af8-290a-11e8-9a33-9d4f47b8ffcd.png)

Other full-screen programs (e.g. vim) don't exhibit this when I run them as the first command in a new terminal. `less` does use the full size if I run it after another full-screen program.

@kevinushey if you start a terminal normally, run and exit `vim`, then do `less big.txt` does it still have the problems? Could be an issue with me not correctly sizing the pseudoterminal at startup based on how a command is using ncurses, perhaps.

**Comment by kevinushey** [comment]
@gtritchie I've noticed I can reproduce the issue more consistently when the terminal only has a small amount of vertical space -- e.g. try with the terminal sized to show only ~5 lines.

It also seems like scrolling / redrawing is really wonky even when the terminal is large enough.

**Comment by kevinushey** [comment]
Long shot: maybe the vertical size of the terminal screen is getting out-of-sync with what `less` believes the terminal size is?

**Comment by gtritchie** [comment]
Ah, I think the problem happens if the number of rows in the terminal (the pane size) is less than 25. For some reason `less` is using the original size set in the code (80x25).

There is code to inform the pseudoterminal of the actual available size, both when it changes at startup and if user resizes.

The size shown in terminal diagnostics is what the Javascript side believes the size to be (i.e. xterm.js). 

![2018-03-16_14-00-41](https://user-images.githubusercontent.com/10569626/37544515-78a493b0-2922-11e8-995f-a4a5c030c47d.png)

The size shown via the Terminal API is what the pseudoterminal (C++) believes the size to be, for example:

```
> term <- .Options$terminal.manager$terminalList()
> .Options$terminal.manager$terminalContext(term)[["rows"]]
[1] 38
![2018-03-16_14-00-41](https://user-images.githubusercontent.com/10569626/37544503-6e0434ce-2922-11e8-8f2e-75a9e7edb892.png)

> .Options$terminal.manager$terminalContext(term)[["cols"]]
[1] 96
```

In my case, right after starting the terminal and running `less`, the values shown in both places seem accurate (i.e. not 80x25), yet `less` still starts off using 80x25, and this is very upsetting to xterm.js or the pseudoterminal especially if the real size is smaller than 25 rows.

**Comment by gtritchie** [comment]
That gives me ideas on what's wrong and where to look. Thanks!

**Comment by gtritchie** [comment]
Note to self: https://github.com/xtermjs/xterm.js/issues/977
