### ISSUE TITLE
RStudio does not load PATH from .profile

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#1878]
In my `~/.profile`, I set `PATH` as follows:

```
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```

It is correctly loaded in an R session:

```
$ R
> Sys.getenv("PATH")
[1] "/home/renkun/bin:/home/renkun/local/bin:/usr/local/bin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home:bin/msys-ssh-1000-18"
```

However, in both RStudio Server and RStudio Desktop (both v1.1.402 and v1.2.209), neither `~/.profile` nor `/.bash_profile` is loaded. 

```
> Sys.getenv("PATH")
[1] "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

I notice this when I was trying @yihui's [https://yihui.name/tinytex](tinytex).

**Comment by yihui** [comment]
As I said at https://d.cosx.org/d/419672/102, all GUI tools will have this problem (not specific to RStudio). They won't read or parse `~/.profile` for your `PATH` changes. `PATH` is inherited only if you start an application from command-line: that is why you can see the expected `PATH` when you start R from the terminal. Similarly, if you start RStudio from the terminal, I think `PATH` will also be correctly inherited.

I'll provide a fix in the **tinytex** package for this specific issue. Thanks!

**Comment by renkun-ken** [comment]
I tested on macOS and tinytex works perfectly even without `PATH` loaded in RStudio but under Ubuntu it unfortunately does not work. But good to know it'll be fixed in tinytex. Thanks!

**Comment by yihui** [comment]
Should be fixed in **tinytex** now. You can test the development version via

```r
devtools::install_github('yihui/tinytex')
```

**Comment by kevinushey** [comment]
Thanks, @yihui!

**Comment by renkun-ken** [comment]
Thanks @yihui. Another walk-around is to specify `PATH` in `.Renviron`.

**Comment by yihui** [comment]
@renkun-ken That is correct, but not necessary with the current devel version of tinytex.

**Comment by shrektan** [comment]
A big thanks. First time to know that ~/.bash_profile doesn't work for all GUI applications on Mac.
