### ISSUE TITLE
adjust placement of RStudio logo?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1879]
With the new, flat icon, I feel like the RStudio icon feels a bit out of place with the current alignment:

![screen shot 2017-12-21 at 9 23 13 am](https://user-images.githubusercontent.com/1976582/34267174-c4864d26-e630-11e7-8fe1-948efa85d8f2.png)

IMHO That effect worked better with the old 'orb' due to the shadow. We could consider placing the icon directly within the space there:

![screen shot 2017-12-21 at 9 23 44 am](https://user-images.githubusercontent.com/1976582/34267215-ec5bf5d0-e630-11e7-9ee0-f77b783bb5fb.png)

**Comment by jmcphers** [comment]
@kevinushey Could you ping Paul and get his take? I think another tweak we might want to make is using a darker blue in dark themes; this new lighter blue really draws the eye more than it should for an icon that doesn't do anything, but we do risk going off brand with a different color.

**Comment by dfalty** [comment]
Verified 1.2.359-1.
