### ISSUE TITLE
Font color of project switcher not consistent with dark theme when toolbar is hidden

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#1882]
I'm using RStudio Server (v1.2.220) and the font color of the project switcher is inconsistent with the dark theme when toolbar is hidden. However, when no project is chosen, the font color is just right.

Steps to reproduce:

1. Choose a project in RStudio Server
2. Choose a dark theme and the project switcher on top-right is white as supposed
3. View -> Hide Toolbar and the project switcher on top-right becomes black (not good for the dark theme)

When toolbar is not hidden:

![image](https://user-images.githubusercontent.com/4662568/34318292-522efedc-e7ff-11e7-9da6-11ab91e5a580.png)

When toolbar is hidden:

![image](https://user-images.githubusercontent.com/4662568/34318293-5aaed23a-e7ff-11e7-8dcf-c502a5a95cf4.png)

**Comment by dfalty** [comment]
Verified this as well on 1.1.408. Thanks for the report!

**Comment by dfalty** [comment]
Fix not in 1.1.412 but will be in the next 1.1-patch build. (If we make one)

**Comment by dfalty** [comment]
Verified fixed 1.1.414. There are still some issues with Sessions and R version (RSP only) that I will put in the other repo.
