### ISSUE TITLE
How does RStudio embed plotting of ggplot2 

### ISSUE THREAD

**Issue by zjffdu** [rstudio/rstudio#1883]
First sorry for asking question here, I didn't find other places to ask this kind of question. I am just curious how does RStudio embed plotting of ggplot into itself. I guess people here can help me on this question. Thanks.

**Comment by jmcphers** [comment]
You should ask this question on our community forum: 

https://community.rstudio.com/c/rstudio-ide

(Short answer: it uses a graphics device. See <https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/Devices.html>).
