### ISSUE TITLE
Initialization Error on Raspbian Stretch

### ISSUE THREAD

**Issue by imkdoug** [rstudio/rstudio#1884]
Hi, 

 Recently, I installed Raspbian Stretch(9) on a raspberry pi 3.
I installed R 3.4.3 from source and also RStudio-server using git downloaded using code below.

      sudo git clone https://github.com/rstudio/rstudio.git

 
There were no matter in install process and all the process and script were just same as Raspbian Jessie(8) where rstudio-server worked successfully.
 
But when I launched rstudio-server using code below and accessed to it, an error occurred.

      sudo rstudio-server start

 I captured the error script popped-up. 
![image](https://user-images.githubusercontent.com/24679418/34343535-9981e056-ea16-11e7-98af-02808271fcf4.png)

I searched some reference using keyword 'transmission', but I couldn't find any answer. 
I looked up /var/log/syslog file and found some error logs like below.

> Dec 25 07:17:20 rp_RPy rsession-pi[1893]: ERROR r error 4 (R code execution error) [errormsg=Error in file(filename, "r", encoding = encoding) : ||| cannot open the connection|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::evaluateString(const string&, SEXPREC**, rstudio::r::sexp::Protect*) /home/pi/rstudio/src/cpp/r/RExec.cpp:302; LOGGED FROM: int rstudio::r::session::RReadConsole(const char*, CONSOLE_BUFFER_CHAR*, int, int) /home/pi/rstudio/src/cpp/r/session/RSession.cpp:719

> Dec 25 07:17:20 rp_RPy rsession-pi[1893]: ERROR R SUICIDE: ERROR r error 4 (R code execution error) [errormsg=Error in file(filename, "r", encoding = encoding) : ||| cannot open the connection|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::evaluateString(const string&, SEXPREC**, rstudio::r::sexp::Protect*) /home/pi/rstudio/src/cpp/r/RExec.cpp:302; LOGGED FROM: void {anonymous}::rSuicide(const string&) /home/pi/rstudio/src/cpp/session/SessionMain.cpp:1036**

 

Because I don't know much about linux systems, I don't know what to check and control.

Maybe there's no report like this on other OS, it's some defect on the OS Raspbian, 
but would you check the process why the error came out?

 

Thanks!

**Comment by kevinushey** [comment]
Those errors are generic R initialization errors -- "cannot open the connection" is emitted by R itself when it attempts to open a connection (e.g. to a file), but fails. This implies the error could be with the R installation itself, or otherwise with some of the R code that RStudio is attempting to execute during initialization.

Are you able to launch R successfully, independently of RStudio?

**Comment by imkdoug** [comment]
Thanks for your answers.

YES. standalone R is launched without any error.
(I installed R from source and made link, so I can launch R just typing "R" on console)

for some errors during install R and RStudio by source files, 
I tried 3 times of whole process(install raspbian - install R - install RStudio),
but the result was same as above. 

one interest thing was, when I install raspbian libraries using code below,

    cd /home/pi/rstudio/dependencies/linux/
    sudo ./install-dependencies-debian

**raspbian GUI is disabled**. I installed GUI version of Raspbian stretch and everything was fine.
but after run the code above, I couldn't get in to GUI desktop.

     startx

doesn't worked. I think some package/library installed by **install-dependencies-debian** making trouble, but not sure.

So I did the process using previous version of Raspbian, Raspbian Jessie, and there's no errors.
both R and RStudio are running well, also GUI desktop is still working.

cuz I know almost nothing about Debian and sources, but have some doubt I just said.

anyway, thanks again for your answer!

**Comment by kevinushey** [comment]
I think you're bumping into an issue where attempting to install the `libjpeg62` package on Raspberry Pi actually ends up uninstalling a whole host of other packages (for some reason). Sorry about that; we haven't tried building RStudio on a Raspberry Pi before so you're running on a rather untrodden path!

I think you might want to try instead installing:

    sudo apt install libjpeg8-dev

Or something similar. (We will likely update these dependency scripts once we've upgraded the version of Qt used by RStudio)

**Comment by imkdoug** [comment]
50% of success:D On the file ./dependencies/linux/install-dependencies-debian, 
I changed some script to install libjpeg8-dev instead of libjpeg62 as you said.

		# sudo apt-get -y install libjpeg62
		sudo apt-get -y install libjpeg8-dev

after installation, GUI is still working! this is the 50%. 

but, the error is still showing up. I don't know why.
so I just took JESSIE instead of STRETCH and everything is fine with me. 

I think it's minor error on Raspberry pi, but if you are interested in this situation or any reason, 
I can let you in via TEAMVIEWER or SSH. 

Anyway thanks again!!!

**Comment by jmcphers** [comment]
Very cool that you got it working on the Pi!
