### ISSUE TITLE
Data preview panel is kind of messy when use `Import Dataset...` option to import data

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#1885]
When I use GUI to `import datasets`

![image](https://user-images.githubusercontent.com/13306020/34856391-c6ddf1e0-f77f-11e7-90f9-f063c3df2be4.png)

See the following screenshot, the header and data do not align well:

![image](https://user-images.githubusercontent.com/13306020/34856404-da573510-f77f-11e7-84c1-ff32f45a39a3.png)

Here is one sample [test data](https://github.com/rstudio/rstudio/files/1599235/test.xlsx).

**Comment by jmcphers** [comment]
I think this might have more to do with the data itself than the source. Could you try the following?

1. Export your Excel data to CSV (from Excel)
2. Import the data into RStudio
3. If you still see the issue, paste the first 10 rows of the CSV file into this issue

**Comment by psychelzh** [comment]
Nope, it looks the seem. I upload a minimal dataset here.

[test.xlsx](https://github.com/rstudio/rstudio/files/1599235/test.xlsx)

**Comment by psychelzh** [comment]
What's more, it does not support files with Chinese name, either.

![image](https://user-images.githubusercontent.com/13306020/34507109-0bf0111e-f06e-11e7-8e8c-1b8dd343c297.png)

**Comment by psychelzh** [comment]
@jmcphers Will you have a test again? Look forward to updating now.

**Comment by dfalty** [comment]
The sample dataset looks fine on both Windows 10 and mac for me with version 1.1.412. What platform and RStudio version are you running?

![image](https://user-images.githubusercontent.com/15237845/34832923-cf846706-f6b3-11e7-8ab6-24fc921e95de.png)

**Comment by psychelzh** [comment]
@dfalty You misunderstood what I meant. I meant to use `import dataset` from `GUI`. I have edited my post for a clearer description, and you would know what I meant.

**Comment by javierluraschi** [comment]
Seems to import fine for me, downloaded the file in this issue followed by importing in RStudio as Excel. Am I missing something?

<img width="1256" alt="screen shot 2018-06-11 at 3 18 05 pm" src="https://user-images.githubusercontent.com/3478847/41237143-be8a5c1e-6d8a-11e8-9a38-5c20c7faa48e.png">

**Comment by psychelzh** [comment]
I have tested it again, and I confirmed that it is an issue that only occurs on a high-resolution screen on Windows 10. It might be because of the DPI zoom on Windows 10.

**Comment by jmcphers** [comment]
@psychelzh We have recently updated RStudio's rendering engine to one that plays much better with high DPI screens on Windows; it should resolve your issue. Let us know if you're still seeing it in recent builds (1.2.5019 or newer).
