### ISSUE TITLE
Renaming file changing only the case returns "The File Exists"

### ISSUE THREAD

**Issue by fsiola** [rstudio/rstudio#1886]
In Windows, if I use the rename utility to rename a file from "a.Rmd" to "A.Rmd" is gives an alert saying "The file exists" and don't rename, I must go to Windows Explorer to rename it.

**Comment by dfalty** [comment]
Verified this on 1.1.408. Thanks for the report!

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
