### ISSUE TITLE
Indent error with {} after pipe operator 

### ISSUE THREAD

**Issue by MajoroMask** [rstudio/rstudio#1887]
Package `magrittr` uses braces to overrule the placeholder `.`'s behavior. When using `{}`` together with the pipe operator `%>%` in the source code, it should be like this:

- x %>%
    + {fun_a(y, z, .)} %>%  # circle marks mean there should be an indent
    + fun_b(w)  # same indent like previous line

But in RStudio source window the auto indent `Ctrl+i` works like this:

- x %>%
- {fun_a1(y, z, .)} %>%  # first serevel continual braced functions' indent seems wrong
- {fun_a2(args1, args2, .)} %>%
    + fun_b1(w)  # normal functions with correct indent
    + {fun_b2(args3)}  # after a normal function, the indent of braced functions works well

I think I've cleared the problem, through it's not a big deal. And I'm a fan to your work, hope this would be of help.

**Comment by kevinushey** [comment]
Thanks for the bug report! This is actually true for any binary operator followed by a `{` on a newline, e.g. we indent:

```
x +
{
```

instead of 

```
x +
    {
```

We'll see if we can get this fixed up.

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
