### ISSUE TITLE
Suggestion: automatically cancel 'selection' after code-chunk submission (with Ctrl-enter)

### ISSUE THREAD

**Issue by JasonL68** [rstudio/rstudio#1893]
In Rstudio, it is very convenient to select/highlight a chunk of code and do 'Ctrl-Enter' to submit/run. One thing I noticed that the selection/highlight still stays on AFTER the submission (i.e. after hitting the 'Ctrl-Enter'). This sometimes can accidently delete the piece of code when one wants to continue editing (one has to first cancel the selection before typing). I know this is trival but it would be nice if Rstudio can automatically cancel the selection after the code has been submitted to console.

I has asked this on the Rstudio support: https://community.rstudio.com/t/cancel-selection-after-code-chunk-submission/3700
Thanks,
Jason

**Comment by kevinushey** [comment]
Thanks for the feature request! I'm not sure if we want to make this change as some users might be surprised by this behavior (some users may intentionally want to highlight and re-execute a piece of code multiple times; e.g. something that executes code that uses R's random number generator)

Newer versions of RStudio allow you to control how <kbd>Ctrl + Enter</kbd> behaves when there is no selection; it's possible the 'execute statement' or 'execute paragraph' behavior might be more in line with what you would like here? See `Tools -> Global Options... -> Code`:

![screen shot 2018-01-02 at 9 11 13 am](https://user-images.githubusercontent.com/1976582/34492539-ea3114d2-ef9c-11e7-96cc-17d9e3075684.png)

**Comment by JasonL68** [comment]
Thanks for looking into this. 
Sure I totally understand that people have different ways of doing things. Thanks for pointing out the execution options for 'Ctrl+enter'. It is relevant.  I still wish though an option could be added for this (similar to what you had with 'Focus console after executing from source'). I found an old thread discussing the exact same issue (https://support.rstudio.com/hc/en-us/community/posts/200657063-accidental-deletion-in-source-code). Thanks.

**Comment by jmcphers** [comment]
I think that focusing the R console after executing meets this need for most users. It'd be nice to add this feature but realistically it's had no support for almost two years and we're unlikely to work on it soon.
