### ISSUE TITLE
ignore trailing commas in diagnostic engine

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1896]
> hadley [7:22 AM] 
> also, an increasing number of tidyverse functions ignore trailing commas, so it would be great if we could figure out some way of conditionally suppressing this note

We might also want to just remove this diagnostic altogether -- I'm not sure how often users intentionally leave a trailing comma in an argument list; e.g. I think errors of the form:

    rnorm(n = 1, sd = 2,)

are relatively (?) rare (and are easy to diagnose when they do occur).

**Comment by dfalty** [comment]
Verified 1.2.359.
