### ISSUE TITLE
Compile PDF: allow users to control how many times 'pdflatex' is run

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1899]
https://support.rstudio.com/hc/en-us/community/posts/115007689093-Sweave-knitr

---

I've got a fairly complex document that needs to have pdflatex run multiple times in order to get the page numbering right. I don't see such an option in the Sweave menu. My workaround is to have a separate .R file that does the following:

knit(doc.Rnw)
system(pdflatex doc.tex)
system(pdflatex doc.tex)
system(pdflatex doc.tex)

It appears that when you click the "compile PDF" button that shows up in the menu bar of .Rnw files, Rstudio is just running the first two lines of the above code. It seems like it would be super easy for you guys to add an option to the Sweave menu that controls the number of times pdflatex is run whenever you click the "compile PDF" button. That is my feature request.

**Comment by kevinushey** [comment]
`pdflatex` is invoked here: https://github.com/rstudio/rstudio/blob/44ab55a57defce795bb6cba8f5dbc391f4054628/src/cpp/session/modules/tex/SessionCompilePdf.cpp#L705-L708

**Comment by jmcphers** [comment]
Nice idea but no requests or votes for about two years (original request was in Dec 2017), so closing.
