### ISSUE TITLE
Superfluous Uninstall shortcut and Start Menu folder

### ISSUE THREAD

**Issue by arencambre** [rstudio/rstudio#1900]
Please remove the **RStudio** folder and **Uninstall** shortcut from the Windows Start Menu. Neither add value, and they contravene Microsoft's UI design standards. All you need is a single **RStudio** shortcut in the base folder of the Start Menu.

Go to https://support.rstudio.com/hc/en-us/community/posts/115004025554-On-Windows-uninstall-shortcut-doesn-t-belong-in-Start-Menu?page=1#community_comment_115001120254 for more thorough discussion.

**Comment by arencambre** [comment]
Still an issue.

**Comment by arencambre** [comment]
@gtritchie they still appear. This is of a Windows 11 fresh install from a few days ago.

![image](https://github.com/rstudio/rstudio/assets/411495/a566c0d5-1cc9-4e3c-8789-b459672ca43e)

**Comment by gtritchie** [comment]
Interesting! We haven't fixed this in the actual installer, so was surprised when it didn't show up for me. Here's what I'm seeing. This is on Windows-11 23H2.

![Screenshot 2023-11-14 110727](https://github.com/rstudio/rstudio/assets/10569626/a5b6fbdc-472a-4718-a7c8-cdb59fd6a384)

**Comment by arencambre** [comment]
I am on Windows 11 23H2, too. The difference might be that I am on a domain-connected machine. I've previously reported where the installer works differently on domain-connected computers. Is this another case?

**Comment by gtritchie** [comment]
No, I've seen both behaviours on my (non-domain) machine today while playing with this.

Sometimes the Start menu shows the folder, sometimes it shows just the RStudio shortcut. This was while doing some uninstalls and reinstalls of the most recent release version of RStudio.

I haven't figured out the pattern, probably not worth further effort as this appears to be something in the Windows Start menu display logic. Mostly of interest if we do get around to actually fixing this (get rid of the folder and uninstall shortcut) so our QA people know how to test it (can't just look at the Start Menu as that can mask the underlying problem).

**Comment by arencambre** [comment]
I think RStudio supports both user-level and system installation (latter requires admin privileges). Is that the difference? I think I recall that my domain-connected computer caused RStudio to install in user-level rather than system-level.

**Comment by gtritchie** [comment]
Ah, you're thinking of this one: https://github.com/rstudio/rstudio/issues/8598

Not a factor in this issue.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+116 by first installing version 2023.06.2+561 and then installing on top of it.
