### ISSUE TITLE
RStudio crashed while reading a large number of text files

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#1904]
Hello,

RStudio 1.2.226 crashed and shut down while I was trying to read about 70,000 files (3 MB each, sample file attached). This is the error message from diagnostics-report (attached)

```
03 Jan 2018 18:06:14 [rsession-user007] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE/open-source-pipeline/master/src/cpp/session/SessionMain.cpp:1256
```

I had read about 10,000 files file before with 1.2.220 without any problem. 

Any idea what went wrong? Thanks!

-- Tung

**Code used**

```
library(data.table)

selected_fread <- function(fileName) {  
  print(paste("Processing file: ", basename(fileName), " ...", sep = ""))  
  # Choose only desired columns 
  tmpData <- data.table::fread(fileName, 
                               select = c("day", "month", "year", 
                                          "var_1", "var_3", "var_20", 
                                          "var_36", "var_45"),
                               na.strings = c("NA", "N/A", "MISSING", "-9999.0", "-999.0"))  
  return(tmpData)
}

dataDir <- "~/data"
setwd(dataDir)
filePattern <- "\\.txt$"
fileList <- gtools::mixedsort(list.files(path = dataDir, recursive = TRUE,
                                        pattern = filePattern, full.names = TRUE))
DT <- fileList %>%
  purrr::set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>%
  purrr::map_df(selected_fread, .id = "FileName") %>%
  setDT()
head(DT)
str(DT)
```

**System info**
```
System:    Host: user007 Kernel: 4.4.0-28-generic x86_64 (64 bit) Desktop: Cinnamon 2.8.8
           Distro: Linux Mint 17.3 Rosa
Machine:   System: Dell product: Precision T1700 v: 01
CPU:       Quad core Intel Core i5-4590 (-MCP-) cache: 6144 KB 
           clock speeds: max: 3700 MHz 1: 3319 MHz 2: 3306 MHz 3: 3307 MHz 4: 3300 MHz
Graphics:  Card: NVIDIA GM107GL [Quadro K620]
MemTotal:  24631604 kB
```

[data_00001.txt](https://github.com/rstudio/rstudio/files/1601457/data_00001.txt)
[diagnostics-report-1.2.226-user007.txt](https://github.com/rstudio/rstudio/files/1601461/diagnostics-report-1.2.226-user007.txt)

**Comment by kevinushey** [comment]
This issue is likely to be independent of RStudio itself, and may instead be related to the actual R session + R packages in use (although we have definitely seen issues that only occur when RStudio is the host environment for R!)

Are you able to provide a minimally reproducible example? If so, do you see the crash when running your script in an R session launched from the console, or only within RStudio?

**Comment by tungmilan** [comment]
Thanks @kevinushey ! I think you are right. Looks like R itself ran out of RAM. I was able to get the job done after modifying the code to be more efficient
