### ISSUE TITLE
Previewing a PDF plot export fails after restarting R

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#1905]
Previewing a PDF export of a plot after restarting an R session from within RStudio results fails with "R code execution error."

To reproduce:

1) Log in to RStudio Server/launch RStudio Desktop
2) Session --> Restart R (or Shift-Cmd-F10)
3) In the console: `plot(pressure)` (This results in a plot in the "Plots" pane)
4) Plots pane --> Export --> Save as PDF
5) Preview

The result is an error pop up that says, "Error / R code execution error" on Mac and "Error Saving Plot / R code execution error" on Ubuntu. If step 2 is omitted, the preview works. Note that the PDF can be saved and viewed with no problem.
![image](https://user-images.githubusercontent.com/31009952/34540418-7e585bf6-f0a2-11e7-9b79-604258e6a2b9.png)

Tested with MacOS Desktop 1.1.383 and 1.1.408 and RStudio Server Pro 1.1.383 on Ubuntu.

**Comment by jmcphers** [comment]
Surprisingly this is still a problem with the latest 1.3 builds -- it must be uncommon to preview these!

**Comment by Hanziness** [comment]
The issue still exists on version 1.3.1073 (Windows 10 x64; '"Giant Goldenrod" (718e6d75, 2020-07-29) for Windows') and it's getting a bit painful having to save my plots into some manually named temp files to preview if labels are legible, for example.

The underlying warning is:
```
Warning message:
In cairo_pdf(file = "C:/Users/****/AppData/Local/Temp/Rtmpu4lein/preview.pdf",  :
  cairo error 'error while writing to output stream'
```

**Note**. This happens regardless of whether using `cairo_pdf` or not.

Is it possible that the restarted R session gets a new temp folder but RStudio does not update that temp path (and keeps the old one for previewing)? I am working on a package project that needs the R session restarted when building the package ("Install and Restart" button) and I am unable to preview any PDF exports after the first build (and restart).

**Comment by kevinushey** [comment]
We read a cached version of the temporary directory here:

https://github.com/rstudio/rstudio/blob/a355947e2d35d08eedf40e0e3edbf864d8ea191d/src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java#L123-L127

Given that the temporary directory can change as sessions are restarted, we should probably avoid reading that from sessionInfo directly (or make sure we always have an up-to-date representation of that value)

**Comment by willgearty** [comment]
This is still an issue @jmcphers @kevinushey. I'm using RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Windows.

**Comment by ronblum** [comment]
This works in RStudio Desktop 2022.06.0-daily+482 on
- MacOS 12.5
- Red Hat 8.5
- Ubuntu 22.04
- Windows 11
