### ISSUE TITLE
allow projects to be renamed

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1909]
From https://support.rstudio.com/hc/en-us/community/posts/115008315647-Allow-to-rename-projects:

---

Would it be possible to add names for Rstudio projects. Currently the folder name is used. This is for many reasons not always a perfect solution.

Since 2013, many issues have been raised:

https://support.rstudio.com/hc/en-us/community/posts/200663977-Allow-projects-to-be-renamed-independently-of-the-project-folder-in-RStudio

https://support.rstudio.com/hc/en-us/community/posts/200664107-renaming-projects

https://support.rstudio.com/hc/en-us/community/posts/200854386-Naming-Renaming-projects

https://support.rstudio.com/hc/en-us/community/posts/202294727-rename-a-project

Some have been alleviated by adding the full folder name for ambiguous projects. However, I think that many problems can still be solved by just adding a custom name field. This can default to the folder but should be editable.

This would also allow for a quick renaming in Rstudio.

I'm not speaking about packages, since they already use the package name.

**Comment by philstraforelli** [comment]
Just stumbled onto this. This would be very useful for me, as in my work I have to put in my .rproj file within a project's subfolder, that is usually named "Data", and I can't keep track over which "Data" project is which project.

Is it possible to just manually rename the name of the .rproj file?

**Comment by benscarlson** [comment]
I have the same problem, the name in the task bar (OS X) is always "src", because that is where I always place my source code and is where I create the .Rproj file. It seems you can rename the .Rproj file (src.Rproj -> myproj.Rproj), but the name displayed in the task bar is still "src" because the name is taken from the folder. 

Perhaps an option to display the name in the taskbar based on the .Rproj file name instead?

**Comment by djhurio** [comment]
Same here. Thanks!

**Comment by alperyilmaz** [comment]
same here (Linux).. whatever the .Rproj filename is, the folder name is used as project name..

**Comment by DesiQuintans** [comment]
Just ran into this too, it would be nice if the .Rproj's name was inherited, not the parent folder's name.

**Comment by raubreywhite** [comment]
Same here. Project name is always "git" or "src"

**Comment by Avi-Kenny** [comment]
I'll upvote this as well. This would be very useful.

**Comment by wathnai** [comment]
+1, I have same folder structure for all my projects, so all my RStudio projects are "Code"

**Comment by rmflight** [comment]
+1, It would be nice if instead of matching the folder name, the file was named something like "project.Rproj", because it doesn't always get a nice logo on all systems, making it difficult to find, and the project "name" was an editable entry in the "project.Rproj" file ...

**Comment by skhiggins** [comment]
+1

**Comment by bteed** [comment]
+1

**Comment by GiovanniRomeo** [comment]
Please, definitely do this. +1

**Comment by JsizzleR** [comment]
Requested through support ticket, 51266.

**Comment by aosavi** [comment]
+1

**Comment by paulstillman** [comment]
+1 this would be very useful.

**Comment by ncalies** [comment]
Requested through support ticket, 60425.

**Comment by jjcurtin** [comment]
Agreed that this would be helpful too.   Just spent a while googling for solutions and arrived here, which suggests there isnt yet a solution.  Thanks for considering this.

**Comment by heseber** [comment]
I second that - I have the same problem, all my projects have the code in "Programs", so that's the name of all my projects. Renaming sessions helps a bit, but when working on several projects in parallel, the browser tab does not show the session name but the project name, so it is always an annoyance to find the right tab for a project.

**Comment by Schoder** [comment]
Another vote from me. For organizational reasons it would make sense to inherit the name from the .Rproj file. Hope this can be implemented

**Comment by astraetech** [comment]
Been having this problem for years. Makes juggling several projects very hard. My vote! 3.5 years after the first post

**Comment by JacobLightman** [comment]
Please implement this ASAP. My team and I have several research projects each which all use the same folder structure where our data analysis files are stored in Project Name/Data/Analysis, meaning that every project is just called Analysis. Seems pointless being able to select projects from a drop-down when the only identifier is an automatically-generated label that can't be changed.

**Comment by Asynchro-Epool** [comment]
+1

**Comment by kevinushey** [comment]
Given the amount of feedback received on this issue, I've marked this for re-triage (consider for an earlier milestone if appropriate)

**Comment by rmccombie** [comment]
Customer vote: 70181

**Comment by ashenkin** [comment]
+1 (been a nagging problem forever)

**Comment by stephteeple** [comment]
+1 would also be very helpful for my workflow and file/folder structure.

**Comment by Blosberg** [comment]
Forcing the name of the project to be the same as the directory it sits in creates needless ambiguity, headaches, and frustration.
It should absolutely be possible to set the name of the project manually. This is a classic example of "It gets done wrong automatically and you can't undo it"

**Comment by dancingfrog** [comment]
+1
... five years later

**Comment by daistarr** [comment]
YES!

**Comment by 711wolf** [comment]
+1. I have so many "r_data" projects, none of which I can rename to reflect something identifying about the higher folder structure to which those data belong.

**Comment by salim-b** [comment]
@711wolf @daistarr and everyone else posting meaningless "+1" comments: Please **stop and use [GitHub reactions](https://docs.github.com/en/rest/reactions)** on the [first post of this issue](https://github.com/rstudio/rstudio/issues/1909#issue-286051679) to express your support/desire for this feature. It annoys subscribers of this issue (me as well as RStudio staff included) to get notifications about your comments. Thank you.

**Comment by ronblum** [comment]
QA: Things to look for
- Changed directory name
- Files currently open
- Opening existing files
- Creating new files
- Closing and reopening the project
- Project name in the <kbd>Project</kbd> drop down list
- Selecting a project from the <kbd>Project</kbd> drop down list
- Project name in the <kbd>File -> Recent Projects</kbd> list
- Selecting a project from the <kbd>File -> Recent Projects</kbd> list
- Name of the `.Rproj` file
- Names of any default files that use the project name, such as with a Quarto project
- Shiny apps using multiple files
- Name of the project in the project-sharing list
- Project sharing while users are actively using a shared project
- Project names in the Posit Workbench home page
- Desktop and server

**Comment by ronblum** [comment]
Only a subset of the above was needed, since this the display name is cosmetic. Verified in
- RStudio Desktop 2024.04.0-daily+652 on Windows 11
- Posit Workbench 2024.04.0-daily+609.pro1 on Ubuntu 22.04 via Chrome on Windows 11

**Comment by nightwatch-analytics** [comment]
Any update on these 4 specific items?

- Project name in the Project drop down list
- Selecting a project from the Project drop down list
- Project name in the File -> Recent Projects list
- Selecting a project from the File -> Recent Projects list

**Comment by gtritchie** [comment]
> Any update on these 4 specific items?

This feature is in the upcoming release (2024.04), currently in the final stages of verification.

You can try it out via the daily builds. https://dailies.rstudio.com/rstudio/chocolate-cosmos/
