### ISSUE TITLE
non-ASCII paths mishandled in Import Dataset (base) dialog

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1910]
From https://support.rstudio.com/hc/en-us/community/posts/115004014074-Encoding-problems-after-upgrade.

Note that this only effects the `Import Dataset (base)` dialog; the dialog using `readr` works just fine. To reproduce:

1. Create a file called `鬼.csv` (or a similar pathname with non-ASCII characters),
2. Invoke the `Import Dataset (base)` dialog, and point it to the path of that file,
3. Press the Ok button to confirm the dialog,
4. Note the code generated uses a mis-encoded path -- `鬼` has been changed to `\xBC`.

![screen shot 2018-01-04 at 9 24 44 am](https://user-images.githubusercontent.com/1976582/34575911-1fd6422a-f131-11e7-9370-31eb7d3394b2.png)

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
