### ISSUE TITLE
add MSYS2 as an option to terminal

### ISSUE THREAD

**Issue by renejuan** [rstudio/rstudio#1911]
Not sure what will be the best development platform to have in Windows but I find myself getting out of RStudio (Windows) to complete some tasks that I would love to be able to do from RStudio. Two tasks I have found recurrently doing outside of RStudio are 1) copying files using rsync and 2) compiling source code (FORTRAN). When I saw RStudio added the terminal I loved it but I noticed soon it had some limitations. I definitely do not understand all the pros/cons/differences of cygwin vs msys vs mingw but I am starting to like MSYS2 since it allow installing tools using pacman and provide access to the MINGW environment.

**Comment by woodwards** [comment]
I have been compiling a Fortran model into an R package following the example of 

https://www.avrahamadler.com/2018/12/09/the-need-for-speed-part-1-building-an-r-package-with-fortran/

It's so easy thanks to RStudio and RTools!

I agree it would be great if RStudio had Fortran code colouring and development tools..

**Comment by renejuan** [comment]
I recently saw issue #6810. I think we can close this issue. In fact, since Rtools is now based on msys2 and RStudio support custom shells maybe the answer is to direct people to https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal. The information there was helpful to setup a custom shell.

**Comment by gtritchie** [comment]
Agreed, will go ahead and close. Thanks for the followup!
