### ISSUE TITLE
RStudio Freezes when making an initial commit with blogdown

### ISSUE THREAD

**Issue by PrincessTheDog** [rstudio/rstudio#1912]
I’m a relatively new useR and this is my first issue here. I posted my issue on an R slack channel as well as RStudio Community and I was directed here. I’ve mostly used R in the past for basic visualization. I recently updated to Rstudio 1.1.383 (R version 3.4.3), and I thought that making a personal website using blogdown would be an interesting project over winter break. Unfortunately, when I go to commit through RStudio it freezes before all of my files are staged. I tried to repeat the process several times, but RStudio continued to freeze (but at different points in the process of staging my files). I was able to commit, edit, and then push a smaller project to github without issue (although it took longer than I expected).  Thanks!

**Comment by ronblum** [comment]
@PrincessTheDog Would you be able to provide a reproducible example? And are you able to commit to GitHub outside of RStudio?

**Comment by PrincessTheDog** [comment]
I am able to commit to GitHub outside RStudio without issue. I performed a test commit using a small text file, and it worked fine but was slow. I ran into problem when committing my blogdown project. RStudio seemed to not like the number/size of my files. Please let me know if I am not completely or adequately answering your question as I am rather new here.

**Comment by ronblum** [comment]
@PrincessTheDog That's helpful. A little more info so I can try and reproduce the problem:
1) What platform are you on? 
2) About how many files are you trying to check in?
3) Would it be possible for me to access the repository so I can clone it and attempt to replicate your scenario?
Thanks!

**Comment by PrincessTheDog** [comment]
1. I'm using Windows 10 home (Version:  10.0.16299 Build 16299). 
2. I have tried to check in the blogdown files for the defaut (platinum) as well as academic. I tried to count the files using bash ("find . -type f | wc -l"). This turned up 696 files.
3. Sure! It's in my "Sowa" repository. However, I encountered the errors when trying to commit the demo sites from blogdown. 

Again, please let me know if there's anything else I can do to help this process along.

**Comment by ronblum** [comment]
@PrincessTheDog We're reviewing some of the older issues. Is this still an issue with the current version of RStudio, 1.2.5033, available at https://rstudio.com/products/rstudio/download/#download ? Thanks!

**Comment by jmcphers** [comment]
No response in several months, closing.
