### ISSUE TITLE
[Bugs]No "copy image" option for Rmarkdown output plot in a new window.

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#1915]
I can see the right-click "copy image" option within the Rmarkdown file. However, it disappears and I can see only "Reload" and "Inspect" after the plot shows in a new window. This is quite annoying when we want to copy the resized plots by adjusting plots in a new window.

![snap5](https://user-images.githubusercontent.com/11802171/34592068-8c65882a-f18f-11e7-98c4-92ca8f5dfbe4.jpg)
![snap6](https://user-images.githubusercontent.com/11802171/34592074-8f69c338-f18f-11e7-9500-8e75ee8a1d07.jpg)

**Comment by jmcphers** [comment]
Happens because this is a background image, not a real image.

https://github.com/rstudio/rstudio/blob/decbca5d59eb2863c56e679a1c9fb5ec6544ee09/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkPlotWidget.java#L105-L122

**Comment by blairj09** [comment]
Came across this today as well. It's interesting to note that if I create a plot in the Plots pane and then zoom on it (to open an external window), I am then able to select Copy from the external window. I would expect plots opened in an external window from an RMarkdown chunk to behave the same.
