### ISSUE TITLE
too many deployments cannot be fully scrolled

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#1917]
Given many deployment records, it is no longer possible to scroll to the "Other Destination" or "Manage Accounts" menu items. The IDE content scrolls a little, as seen in the following screenshot, but not far enough to show the bottom of the menu.

On macOS with IDE version 1.2.226

![screen shot 2018-01-05 at 10 33 37 am](https://user-images.githubusercontent.com/362187/34615797-183eb654-f204-11e7-99a7-14a484ccfa6b.png)

**Comment by aronatkins** [comment]
Workaround: Close tab editing the Shiny application, remove the `rsconnect` directory, re-open the application source, then publish.

**Comment by jmcphers** [comment]
This is currently tracked in #1760.
