### ISSUE TITLE
R session aborting only when building package via button or keyboard shortcuts

### ISSUE THREAD

**Issue by PeteHaitch** [rstudio/rstudio#1920]
My R session is aborting when building via **devtools** a package that depends on the **fst** package, but only when called via the buttons in the RStudio build pane or using the RStudio keyboard shortcuts (e.g., ⇧⌘E on a Mac). To reiterate, everything seems to work fine provided I type the relevant command in the console within RStudio (e.g., `devtools::document()`, `devtools::build()`, etc.). I have been tracking this bug down with the developer of **fst**, @MarcusKlik, in https://github.com/fstpackage/fst/issues/109

The **fst** package uses OpenMP and I am using the R LLVM on macOS. Based on my reading of https://github.com/rstudio/rstudio/issues/1598, I believe this is related to and could even be the same issue. The advice therein boils down to:

> I would recommend disabling OpenMP and using the system toolchain, rather than the LLVM toolchain distributed by R (https://github.com/rstudio/rstudio/issues/1598#issuecomment-337959353)

which I can certainly do. 

However, because the only way I can seem to trigger this is via the RStudio buttons and keyboard shortcuts, and not at the RStudio console nor from command line R, this feels like an issue with RStudio (albeit perhaps caused by gremlins lower down). And the bug is an outsized annoyance to me because my muscle memory loves using the RStudio keyboard shortcuts :) If there's anything I can do to help track down this, I'd be very happy to help. 

Here's how I can reproduce the issue on my machine:

1. Download and unzip a minimal package that depends on **fst** https://github.com/fstpackage/fst/files/1524331/fsttester.zip
2. Open the supplied RStudio project
3. Run `devtools::document()` in the RStudio console
4. Go to the 'Build' tab, 'More', and click 'Document'

This reliably produces the following on my machine

![image](https://user-images.githubusercontent.com/1049741/34645166-7ab75d6c-f39a-11e7-940c-a3dea9508f51.png)
 
and upon clicking 'OK'

![image](https://user-images.githubusercontent.com/1049741/34645171-91d64bca-f39a-11e7-9d7a-db5da654d952.png)

This is my session info from within RStudio, after loading/attaching **fst**:

<details>
<summary>Session info</summary>

``` r
> sessionInfo()
R Under development (unstable) (2017-12-12 r73903)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fst_0.8.2         colorout_1.1-3    repete_0.0.0.9010 devtools_1.13.4  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14           rstudioapi_0.7         whisker_0.3-2         
 [4] knitr_1.18             XVector_0.19.1         magrittr_1.5          
 [7] GenomicRanges_1.31.3   BiocGenerics_0.25.1    zlibbioc_1.25.0       
[10] IRanges_2.13.4         munsell_0.4.3          colorspace_1.3-2      
[13] stringr_1.2.0          GenomeInfoDb_1.15.1    plyr_1.8.4            
[16] tools_3.5.0            parallel_3.5.0         clipr_0.4.0           
[19] withr_2.1.1            htmltools_0.3.6        fortunes_1.5-4        
[22] rprojroot_1.3-2        yaml_2.1.16            digest_0.6.13         
[25] GenomeInfoDbData_1.1.0 callr_1.0.0            pryr_0.1.3            
[28] S4Vectors_0.17.16      bitops_1.0-6           codetools_0.2-15      
[31] RCurl_1.95-4.10        evaluate_0.10.1        memoise_1.1.0         
[34] rmarkdown_1.8          reprex_0.1.1           stringi_1.1.6         
[37] compiler_3.5.0         backports_1.1.2        scales_0.5.0          
[40] stats4_3.5.0   
```

</details>

And here is my R LLVM set up (I'm running R-devel, so all packages are built from source using this toolchain):

```sh
Peter@Peters-MBP-2 ~ $ cat ~/.R/Makevars
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib
Peter@Peters-MBP-2 ~ $ /usr/local/clang4/bin/clang++ --version
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/clang4/bin
```

And this is running RStudio Version 1.1.412

**Comment by kevinushey** [comment]
One thing worth noting -- Python resolves this issue by using a fork server:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378
https://bugs.python.org/issue8713

With documentation: https://docs.python.org/3/library/multiprocessing.html:

> forkserver
>   When the program starts and selects the forkserver start method, a server process is started. From then on, whenever a new process is needed, the parent process connects to the server and requests that it fork a new process. The fork server process is single threaded so it is safe for it to use os.fork(). No unnecessary resources are inherited.
> 
>   Available on Unix platforms which support passing file descriptors over Unix pipes.

However, this would be a relatively expensive architectural change for RStudio so I'm not sure if it's something we can pursue.

**Comment by ronblum** [comment]
@PeteHaitch You probably already saw that @kevinushey has joined the conversation at https://github.com/rstudio/rstudio/issues/1920. The problem should be addressed this in the fst package. Thanks for identifying it!

**Comment by ronblum** [comment]
Closing, as issue is being addressed in https://github.com/fstpackage/fst/issues/109.
