### ISSUE TITLE
self-contained-ness of local / temporary previews, esp. (only?) of READMEs

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#1922]
If I target a markdown output format from `.R` or `.Rmd`, clicking the "Knit" button causes the primary markdown output to be made and also an ephemeral html version for local preview. This is generally really helpful. But here's a recent example where that's frustrating.

`README.Rmd` (with lots of badges) --> `README.md` --> `some/long/temp/path/README.html`

If one or more badges can't be fetched in real-time, you can't get any html. It's also easy to think the whole effort failed, even though the `.md` is actually produced.

I've only noticed the awkwardness with READMEs FWIW. But I wish I could turn off `--self-contained` when making the html. I'd be happy with the question mark for balky badges.

Certain badges are unretrievable with specific versions of Pandoc (https://github.com/vincenthz/hs-tls/issues/152, https://github.com/jgm/pandoc/issues/3936). Also, sometimes you're just on a plane.

**Comment by kevinushey** [comment]
This is ultimately an `rmarkdown` issue -- I think the rest of the followup can occur at https://github.com/rstudio/rmarkdown/issues/1238.
