### ISSUE TITLE
Server name text is overflowing from 'Publish To Account' window

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rstudio#1925]
IDE Version 1.1.412

**Pre-requisite:** 
- Long Username 
- Long servername (example: dogcluster.rstudioconnect.com)

**Steps:**
1. Publish an app (Server name stays within the `Publish From Account`container )
2. Now,  re-publish the app to same destination

**Result:** Observer `Publish to Account` window
![screen shot 2018-01-08 at 2 32 43 pm](https://user-images.githubusercontent.com/17551950/34694867-3fa07e58-f48e-11e7-9230-73d12c0485dc.png)

**Comment by kevinushey** [comment]
It seems like this is rectified in the daily builds.

**Comment by dfalty** [comment]
I'm still seeing this on 1.2.1090 with mac. Reopening
![image](https://user-images.githubusercontent.com/15237845/48022896-f5366600-e101-11e8-9537-82a87b048b46.png)

**Comment by kevinushey** [comment]
For some context, the name does still overflow, but it can be horizontally scrolled within the box, and doesn't "leak" out (at least in my case):

![screen shot 2018-11-05 at 3 13 00 pm](https://user-images.githubusercontent.com/1976582/48032636-4f88f400-e10d-11e8-8ac8-9fe7d449fa19.png)

Not sure if we want to do something more aggressive like e.g. truncating account names.

**Comment by kevinushey** [comment]
Oops. The 'original' dialog is fine, but the 're-publish' dialog is not.

![screen shot 2018-11-05 at 3 17 05 pm](https://user-images.githubusercontent.com/1976582/48032798-e950a100-e10d-11e8-8e3d-915c74705ad5.png)

**Comment by kevinushey** [comment]
Should be resolved via https://github.com/rstudio/rstudio/pull/3829.
