### ISSUE TITLE
fatal: unable to create '~ / .got/index.lock': file exists.

### ISSUE THREAD

**Issue by ccatano** [rstudio/rstudio#1931]
I frequently get the following error when trying to make a commit using Rstudio. I've tried terminating all processes, rebooting my computer, and various other "solutions" I've read online. The only way I could fix this is to uninstall/reinstall git, then create a new R studio project. 

I've just started trying to use git so any help would be greatly appreciated!

fatal: Unable to create 'C:/Users/Chris/Desktop/Research/PhD/Ch3_stability_BBS/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by ccatano** [comment]
Solution:

In R studio click tools -> shell then in the command line type: rm -f .git/index.lock

**Comment by kevinushey** [comment]
Do you have any other Git clients running at the same time as RStudio (e.g. [SourceTree](https://www.sourcetreeapp.com/))? Or, is this within a folder that automatically synchronizes with an external cloud service (DropBox, Google Drive, or similar)?

**Comment by ccatano** [comment]
Rstudio is the only software I have running when this occurs. The folder is not synchronized with any cloud service, although I do have a repository for this work set up on github so I can push my commits.

I noticed this error occurs at least after every time I try to stage and commit a subfolder with various data outputs (.csv) and additional subfolders within. When I click to stage nothing happens, then if I try to stage/commit another file, such as an R file, I get the error. I also notice R studio stop responding at this point...

**Comment by kevinushey** [comment]
Interesting. It sounds like RStudio is trying to invoke `git`, but `git` is freezing up while attempting to add these subfolders. When you kill the RStudio / `git` process, an `index.lock` file is left behind and that causes the

    fatal: Unable to create 'C:/Users/Chris/Desktop/Research/PhD/Ch3_stability_BBS/.git/index.lock': File exists.

errors you're noting.

How large if this folder you're attempting to stage and commit? Does it contain a large number of files? Or, are the files themselves large in size?

**Comment by ccatano** [comment]
The folder is pretty large, 49.3 gigs. Perhaps this is the problem. Maybe its taking a while to stage it, and I'm not waiting long enough before I try to commit something else, this causing the error?

**Comment by kevinushey** [comment]
That's indeed quite large! That's almost certainly the case that `git` is getting stuck attempting to stage the file. Unfortunately, `git` does not (traditionally) work that well with very large files.

Do you absolutely need these files to be part of the `git` repository? You could consider ignoring those files with a `.gitignore` file, and manage those files separately. Or, you could look into other solutions like Git LFS (https://www.atlassian.com/git/tutorials/git-lfs), although I have heard that it can often be quirky to setup and use.

**Comment by ccatano** [comment]
These data files don't all need to be part of my git repository, just a handful of the smaller ones. 

Thank you for trouble shooting this with me!
