### ISSUE TITLE
Support SIGHUP to reload server configuration files

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1932]
Many RStudio Server configuration files are currently read only on startup. We've had a few requests to support an in-place reload of the configuration so that settings can be changed without taking down the server. 

The idiomatic way to do this on Linux is to have the daemon process listen to `SIGHUP` and respond by reloading its configuration. 

https://en.wikipedia.org/wiki/Signal_(IPC)#SIGHUP

http://perldoc.perl.org/perlipc.html#Handling-the-SIGHUP-Signal-in-Daemons

**Comment by jmcphers** [comment]
Some situations in which this has come up (mostly related to Pro):

- Adding an R version without restarting the server
- Activating or changing the license without restarting the server
- Changing the load-balancing configuration without restarting the server

**Comment by ougar** [comment]
We would REALLY appreciate the possibility of reloading the configuration on a running server. We would like to do things like add/remove user groups in rserver.conf or change user quotas, to let a user temporarily use more memory. Currently we need to plan this, and inform users, and schedule a server restart during the night (which still kills long running jobs)

**Comment by hansen-m** [comment]
What is the current (1.2.1335-1 (Professional)) behavior of sending a SIGHUP? Will users be disconnected?

It is mentioned in the docs here - https://docs.rstudio.com/ide/server-pro/r-versions.html#determining-available-versions

**Comment by kfeinauer** [comment]
Users will not be disconnected. Currently, you can modify the R versions that are available, as well as add an additional node to the node balancer pool with SIGHUP. This should be completely transparent to your users.

**Comment by hansen-m** [comment]
Just tested this and it doesn't seem to refresh the R versions that are available, which is bad but it also didn't disconnect users, which is good.

In my setup I specify R instances using the r-versions file and use the r-versions-scan=0 to disable scanning and rsession-which-r key in rserver.conf to specify the default version.

**Comment by jmcphers** [comment]
This is now implemented. @hansen-m If you're still seeing this behavior (SIGHUP does not refresh R versions) in the latest version (1.2.5019), please open a support ticket -- as a Pro customer you're entitled to email support!
