### ISSUE TITLE
Cannot cancel project switch

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1934]
This was introduced in October (1.2) via change 13e1f1c9.

Open a project.
Change the R environment, e.g. a <- "hello"
Switch to another project.
Get prompted to **Save workspace image to ...**

Expect: options are "Save", "Don't Save", and "Cancel"

Actual: the Cancel button is missing.

**Comment by ronblum** [comment]
Confirmed in 1.2.338.
