### ISSUE TITLE
attempting to publish an unsaved document warns and opens file dialog at same time

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1937]
This was with RStudio v1.1.412 on macOS Desktop.

![small](https://user-images.githubusercontent.com/1976582/34793416-21bf6282-f600-11e7-8716-bdf01c5cc195.gif)

We probably want to show just one or the other.

**Comment by jmcphers** [comment]
Patch candidate since probably downstream from https://github.com/rstudio/rstudio/issues/1821.

**Comment by jmcphers** [comment]
Backported to 1.1 in https://github.com/rstudio/rstudio/commit/2484a690ee9702db38bdd9b4424967fb690fa56e.

**Comment by ronblum** [comment]
Confirmed in RStudio MacOS Desktop 1.1.414.
