### ISSUE TITLE
can't publish to RPubs (document mis-identified as not self-contained)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1938]
Prompted by https://support.rstudio.com/hc/en-us/community/posts/115008283313-RPubs-not-showing-up-as-an-option-for-publishing.

When I attempt to publish an R Markdown document (after clearing out my previous rsconnect settings), I see the following:

<img width="718" alt="screen shot 2018-01-10 at 1 16 31 pm" src="https://user-images.githubusercontent.com/1976582/34795940-c8aa2fe8-f608-11e7-8acf-754fedd8a55a.png">

This does work fine in v1.0.

**Comment by jmcphers** [comment]
Did render the document first?

**Comment by kevinushey** [comment]
I did not, but that didn't appear to make a difference.

**Comment by kevinushey** [comment]
Note that I have other publishing options turned off, in case that's relevant:

<img width="599" alt="screen shot 2018-01-10 at 3 00 29 pm" src="https://user-images.githubusercontent.com/1976582/34800049-0ade3b30-f617-11e7-8ae3-55e243d79f0c.png">

**Comment by jmcphers** [comment]
Ahhh, that's helpful, thanks. Given that, the behavior here is correct even though the error message is wrong; in 1.1 you need to be more explicit about what you're publishing -- Publish in the editor toolbar always publishes the code, and Publish in the viewer pane/window publishes the rendered document. RPubs only supports rendered docs, so you can't publish there from the editor window. I'll add an error message to this effect.

**Comment by jmcphers** [comment]
Backported to 1.1 in https://github.com/rstudio/rstudio/commit/9ca4e0fd8fe82b4fc02a0926b01449aad87b5eed.

**Comment by ronblum** [comment]
Updated error message confirmed in RStudio 1.1.414.

**Comment by ronblum** [comment]
Note that this only works if "Knit to HTML" is chosen. Knitting to PDF or Word do not. We should consider modifying the error message to specifically state choosing "Knit to HTML."

**Comment by betsyrosalen** [comment]
Hi Guys, the original problem with publishing to RPubs that Kevin referred to was posted by me and although I think his error and my problem weren't exactly the same, the solution fixed my problem too!  It was the knitting to HTML thing.  I had it set to PDF, as soon as I switched it to HTML RPubs finally showed up on my list of options for publishing!  Duh!  Thank you so much!

**Comment by Pinak18** [comment]
![image](https://user-images.githubusercontent.com/45752997/50563523-96791b80-0d43-11e9-838f-e6d61b606e4e.png)

Why does this error come? What does this imply?

**Comment by pablobernabeu** [comment]
``` 
install.packages('rsconnect')
library(rsconnect)
```
solved it for me
