### ISSUE TITLE
turn off notification that new breakpoints will be activated when file sourced

### ISSUE THREAD

**Issue by rviger-usgs** [rstudio/rstudio#1939]
This is a (very) small issue, I know, but I find it distracting that when I insert a breakpoint during a debugging session, the Code Window pops up that notice about the breakpoint not being activated until file re-sourced, especially because it shifts the code down-screen. Could a feature to control this popup be added?

**Comment by ronblum** [comment]
Thank you for the suggestion—we'll consider it for future releases of RStudio.
