### ISSUE TITLE
Hold diagnostics until the line is finished

### ISSUE THREAD

**Issue by DaveTheMovie** [rstudio/rstudio#1940]
I would prefer it if code diagnostics are run after I leave the line I'm typing (either by hitting 'enter' or clicking away.  It distracts me to get feedback suggesting that I'm making a mistake.  I understand that increasing the time delay is a solution but that's clumsy because what I really want is feedback as soon as I complete the item of code.  Maybe the user could choose to have both?  E.g. min(timer-expire, line-change).

Just putting my vote out there in case others feel the same.

Thanks

**Comment by ronblum** [comment]
Thank you for the suggestion!
