### ISSUE TITLE
Support "Anchor" ANSI escape extension

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#1941]
https://www.iterm2.com/documentation-escape-codes.html

This would be extremely useful if it supported both remote urls and local files (a la traceback). For example, we could hyperlink testthat failures to the file and line where the failure occurred.

See also: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

**Comment by kevinushey** [comment]
We could also parse common formats for error messages. `testthat` output is typically of the form:

```
test-file.R:5: error: bad things happened
```

and it should be relatively easy to detect lines of that form. (hopefully the error formatting here isn't going to change any time soon)

**Comment by romainfrancois** [comment]
Very related to `cli::style_hyperlink()` which produces the right sequence. 

``` r
cli::style_hyperlink
#> function (text, url) 
#> {
#>     out <- if (ansi_has_hyperlink_support()) {
#>         paste0("\033]8;;", url, "\a", text, "\033]8;;\a")
#>     }
#>     else {
#>         text
#>     }
#>     class(out) <- c("ansi_string", "character")
#>     out
#> }
#> <bytecode: 0x7f87aa05cdc8>
#> <environment: namespace:cli>
txt <- withr::with_options(
  list(cli.hyperlink = TRUE), 
  cli::style_hyperlink("here", "https://github.com/rstudio/rstudio/issues/1941")
)
str(txt)
#>  'ansi_string' chr "\033]8;;https://github.com/rstudio/rstudio/issues/1941\ahere\033]8;;\a"
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by romainfrancois** [comment]
Move back to `in progress` until https://github.com/r-lib/cli/issues/414

**Comment by romainfrancois** [comment]
Moving this to test, but until https://github.com/r-lib/cli/issues/414 is dealt with, we need to set the `R_CLI_HYPERLINKS` environment variable, e.g. 

```r
Sys.setenv("R_CLI_HYPERLINKS" = "true")
cli::style_hyperlink("link", "http://www.example.org")
```

because we only set the `RSTUDIO_CLI_HYPERLINKS`.

**Comment by jgutman** [comment]
Verified using RStudio Desktop 2022.06.0-daily+208 and the latest CLI from Github 3.2.0.9000 2022-03-14 Github (r-lib/cli@476cf06)
On Mac or 12.2.1.

**Comment by jgutman** [comment]
Followup issue: #10803

**Comment by dhicks** [comment]
I'm wondering about the status of this?  Marked as closed nearly two years ago, but the followup issue is a bug about opening links in the Viewer pane?

**Comment by ronblum** [comment]
@dhicks Are you seeing this problem again? Or are asking about followup issue #10803?

**Comment by dhicks** [comment]
I ended up in this comment because I was wishing URLs in console output were clickable.  A web search took me to #2530 , which was closed in favor of this issue.

**Comment by hadley** [comment]
@dhicks it is implemented. As an R user, the easiest way to produce these links is with the cli package: https://cli.r-lib.org/reference/links.html

**Comment by dhicks** [comment]
Ahh okay, so it's not quite iTerm's "any URL anywhere is clickable."  Thanks for the clarification!
