### ISSUE TITLE
RStudio crashes after navigating external links

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1942]
Clicking certain links built into RStudio desktop IDE crashes the IDE.

Examples:
- About dialog -> click Affero General Public License
- Terminal -> echo https://rstudio.com, hover mouse over text and click the hyperlink

**Comment by gtritchie** [comment]
Related to the anchor triggering creation of a new RStudio browser window, which is then destroyed in a way that crashes. The actual requested page does load in the browser.

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
