### ISSUE TITLE
Unable to see the logs in /var/log/messages... 

### ISSUE THREAD

**Issue by AK-ayush** [rstudio/rstudio#1944]
Hi, 
I am running Rstudio-server inside a centos container. But I am not able to get the logs from the running container. I have already tried [RStudio Server - Application Logs](https://support.rstudio.com/hc/en-us/articles/200554766) as well as on [stackoverflow answer](https://stackoverflow.com/questions/40525722/configure-log-directory-for-rstudio-server-1-0-44), but they were not any help to me.

**Comment by jmcphers** [comment]
This issue tracker is for bugs in RStudio. I'd suggesting asking your question on the R Admins community forum we recently set up:

https://community.rstudio.com/c/r-admin

Hope you're able to find a solution!
