### ISSUE TITLE
Code works from console but from Rstudio IDE

### ISSUE THREAD

**Issue by dselivanov** [rstudio/rstudio#1950]
```r
sessionInfo()
#R version 3.4.2 (2017-09-28)
#Platform: x86_64-apple-darwin16.7.0 (64-bit)
#Running under: macOS High Sierra 10.13.2
#Matrix products: default
#BLAS: #/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#LAPACK: #/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
#locale:
#[1] en_US.UTF-8/UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     
#other attached packages:
#[1] float_0.1-2
#loaded via a namespace (and not attached):
#[1] compiler_3.4.2
```

```r
if(!("remotes" %in% installed.packages()[, 1]))
  install.packages("remotes", repos = "https://cloud.r-project.org/")

if(!("ulog" %in% installed.packages()[, 1]))
  remotes::install_github("s-u/ulog")
```
I have `rsyslog` running on local machine on 5515 port and receiving logs via UPD. The code below works from console (i see messages in log file), but not from IDE.
```r
library(ulog)
ulog.init(path = "udp://127.0.0.1:5514", application = "R")
ulog("hello from R - udp")
```
If I write to unix socket instead of UDP -  everything works fine:
```r
ulog.init(path = "/path/to/rsyslog.socket", application = "R")
ulog("hello from R - unix socket")
```

Let me know if you need more details.

**Comment by jmcphers** [comment]
Haven't had any other reports or info, so going to close this one. @dselivanov If you're still seeing this with recent IDE versions (1.2.5019), could you be more specific when you say the code "doesn't work"?

> The code below works from console (i see messages in log file), but not from IDE.

i.e. do you see an error? what does/doesn't happen, exactly? can you share relevant screenshots?

**Comment by dselivanov** [comment]
Steps to reproduce:

## Daemon

1. download ulog `git clone https://github.com/s-u/ulog.git`
1. make ulog daemon service `cd ulog/src/ulog && gcc ulogd.c -o ulogd && chmod +x ulogd`
1.  stard ulog daemon listenin UDP port `./ulogd -u 5514 > logs.txt`
1. watch logs in a separate terminal `tail -f logs.txt`

## Client

Install client
```r
remotes::install_github("s-u/ulog")
```

### Try to send messages from Rstudio:
```r
library(ulog)
ulog.init(path = "udp://127.0.0.1:5514", application = "R-Rstudio")
ulog("hello from Rstudio")
```
**RESULT**

**no messages added to `log.txt`**


### Try to send messages from R from terminal:
```r
library(ulog)
ulog.init(path = "udp://127.0.0.1:5514", application = "R-terminal")
ulog("hello from R-terminal")
```
**RESULT**

Following line was added to `logs.txt`:

> 1573624965.669|<30>1 2019-11-13T06:02:45Z Dmitriys-MBP-2 R-terminal 99398 501/20 - hello from R-terminal

**Comment by dselivanov** [comment]
@jmcphers please reopen

**Comment by dselivanov** [comment]
@jmcphers was you able to reproduce? I believe this is related to UPD connections within rstudio.
