### ISSUE TITLE
Cmd-Tab on OSX no longer displays project associated with IDE instance

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#1954]
When Cmd-Tabbing we used to overlay the IDE icon with the name of the project (if any) open within the IDE. This no longer occurs in the QtWebEngine version. The code for the Cocoa version of  this is here:

https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop-mac/DockTileView.mm

I think this is actually a P1 bug as for me and other users with many (5+) projects open concurrently it makes the QtWebEngine version close to unusable b/c I switch around so much. Let's see if we can get this resolved ASAP.

**Comment by ronblum** [comment]
Confirmed in 1.2.338.
