### ISSUE TITLE
Bring All to Front not working as expected on OS X

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#1955]
The Bring All to Front command in the QtWebEngine version doesn't work correctly:

1) It never seems to bring secondary windows (e.g. the Git Window) to the front

2) With 2 instances of the IDE open, in one of the instances Bring All to Front is a no-op and in the second instance it brings the first instance to the front.

**Comment by gtritchie** [comment]
Another variation of this:
1. Launch RStudio
2. Show Git window
3. Arrange windows so Git is next to Main window
4. Put something over the Git window, e.g. Chrome
5. Click on the Main window (Git remains behind Chrome)
6. On Window menu (example below), select the Git window ("RStudio: Review Changes" in this case")
7. Should bring that window forward, but it doesn't.

![2018-01-19_13-56-41](https://user-images.githubusercontent.com/10569626/35173575-be89f51a-fd20-11e7-957b-ad4200079859.png)

Interestingly, clicking the dock icon does the right thing, and both windows come forward.

Compare with behavior of a native Mac app such as TextEdit with multiple windows.

**Comment by kevinushey** [comment]
Interestingly, it does focus the window, it just doesn't bring it to front as well. Qt 5.10 has something that might be relevant:

https://doc.qt.io/qt-5/qwebenginesettings.html

QWebEngineSettings::AllowWindowActivationFromJavaScript | 24 | Allows activating windows by using the window.focus() JavaScript method. Disabled by default. (Added in Qt 5.10)
-- | -- | --

**Comment by gtritchie** [comment]
Tried building with that (AllowWindowActivationFromJavaScript = true) didn't change behavior, but seems like something we want on for other situations.

**Comment by gtritchie** [comment]
Gut feel is this is somehow related to #2005. Some attribute isn't being set to let the system know these are main windows vs. lesser windows.

**Comment by dfalty** [comment]
Verified 1.2.359.
