### ISSUE TITLE
Lockup of UI on Mac OS X

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#1957]
After using a file save dialog while the console was busy, the UI in the QtWebEngine version is extremely, extremely slow (i.e. it takes a few seconds for anything to register, including a mouse click or a keystroke). 

Am currently attempting to open the dev tools console to break within JS but that is hanging (or perhaps just didn't work at all)

**Comment by ronblum** [comment]
Verified in 1.2.342.
