### ISSUE TITLE
pressing the Project button skews RStudio UI

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1961]
RStudio v1.2.245, macOS:

![screen shot 2018-01-12 at 10 20 33 am](https://user-images.githubusercontent.com/1976582/34889269-41b628f4-f782-11e7-846b-8a6c0c3feaa0.png)

Note the grey bar on the right side. It appears to be a rendering error as even Chromium Devtools ends up drawing the bar around the DOM element in the wrong place. Before opening the project menu:

![screen shot 2018-01-12 at 10 24 16 am](https://user-images.githubusercontent.com/1976582/34889441-d6e476ba-f782-11e7-8077-3c556c41beeb.png)

After:

![screen shot 2018-01-12 at 10 24 19 am](https://user-images.githubusercontent.com/1976582/34889450-df1043be-f782-11e7-8c80-1ed6141740d2.png)

**Comment by kevinushey** [comment]
I don't see this issue when I built RStudio against Qt 5.10.0. I'll also test against Qt 5.9.3.

**Comment by kevinushey** [comment]
Fixed with move to Qt 5.10.0.

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
