### ISSUE TITLE
Internet Explorer complains/fails on viewing a variable with many columns

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#1962]
Internet Explorer has trouble with attempts to view a variable (matrix) with a large number of columns. 

To reproduce:
1. `mt <- matrix((1:50000), ncol = 500)`
2. `View(mt)`

Eventually, IE/Edge complains that it has stopped responding or the script is taking too long. After about 3-5 minutes, the process will complete. Sometimes the data will be displayed properly, but other times, the data isn't rendered.

It only takes a few seconds to succeed on Windows Desktop and MacOS Desktop 1.1.412. Also, compare this to Chrome: the data is successfully displayed quickly, with no complaint—after about 10 seconds with no other Chrome windows or 45 seconds while a Rick Astley video plays in another tab. 

RStudio: 1.1.412 (Professional)
Windows 10 Enterprise Edition with 8GB RAM
Microsoft Edge: 38.14393.1066.0
Microsoft EdgeHTML: 14.14393
or old school Internet Explorer: 11.00.14393.2007

Also reported separately with a data frame with 481 variables on (see support ticket 24958)
RStudio Server: 1.1.383 (Professional)
Windows: 10.0.14393
Internet Explorer: 11.0.49 (KB4052978)
Edge: 38.14393.1066.0

**Comment by jmcphers** [comment]
This has been fixed in 1.2, which only shows 50 variables at a time.
