### ISSUE TITLE
Consider to provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [rstudio/rstudio#1967]
Now that you are using `linuxdeployqt` you might consider to (also) provide an AppImage for download (e.g., on GitHub Releases).

https://github.com/rstudio/rstudio/blob/7bbb81720692a19eef58599dc42ceea0a415c9e5/src/cpp/desktop/install/LinuxInstallQt.sh.in#L13

`linuxdeployqt` has an `-appimage` option that would make this easy.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by jmcphers** [comment]
This is now tracked in https://github.com/rstudio/rstudio/issues/3079.

**Comment by probonopd** [comment]
Could we please reopen this since #3079 covers all sorts of different distribution methods and I'd like to unsubscribe from that one because most of the discussion in that other ticket is not relevant to AppImage. Thanks.

**Comment by adnion** [comment]
I would love to see an AppImage for RStudio. It runs on every linux distribution. Flatpak or snap need official support and root privileges to run.
Furthermore I don't think these two support apps on portable usb drives.

**Comment by adnion** [comment]
I created an appimage draft for RStudio.
It does not start yet. This is for development purposes only.

- [ ] fix startup
- [ ] sort out best folder layout for RStudio and R
- [ ] check if package installs work

https://github.com/adnion/AppImage/releases
