### ISSUE TITLE
Poor visibility around SSH key pairs named anything other than id_rsa and id_rsa.pub

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#1969]
In *Tools > Global Options... > Git/SVN*, the SSH support is very much hard-wired to `id_rsa` and `id_rsa.pub`, both for detection and creation. I acknowledge that this is truth in advertising, in some sense, given that section is indeed titled "SSH RSA Key".

But I've got a perfectly functional key pair right now named `id_ed25519` and `id_ed25519.pub` and RStudio suggests that I don't have an SSH key setup. Git push/pull works fine, so this doesn't keep me from *doing* anything. But others might get confused or discouraged.

I'd like to be able to recommend this method of checking for existing SSH keys. Could this be relaxed?

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/1645.
