### ISSUE TITLE
selectInput with size < 4 not shown correctly in viewer

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#1972]
```
library(shiny)

ui = fluidPage(
  selectInput('nrrows1', 'Size = 6', letters, size = 6, selectize = FALSE),
  selectInput('nrrows2', 'Size = 4', letters, size = 4, selectize = FALSE),
  selectInput('nrrows3', 'Size = 2', letters, size = 2, selectize = FALSE)
)

server = function(input, output, session) {
}

shinyApp(ui = ui, server = server, options = list(launch.browser = shiny::paneViewer()))
```

Viewer:

![image](https://user-images.githubusercontent.com/2998956/34924476-66d6837c-f958-11e7-9351-3f0c677224a4.png)

Chrome:

![image](https://user-images.githubusercontent.com/2998956/34924485-71136a12-f958-11e7-97ec-9988d4618de9.png)

Safari does display the `select` the same way as Rstudio viewer so perhaps this is not fixable in Rstudio

**Comment by jmcphers** [comment]
Fixed in RStudio 1.2 with QtWebEngine.

![image](https://user-images.githubusercontent.com/470418/69182786-905c6c80-0ac6-11ea-806d-c31612f8ed9f.png)
