### ISSUE TITLE
RStudio has stopped working

### ISSUE THREAD

**Issue by chingoduc** [rstudio/rstudio#1974]
Hi,

I tried to run an application of the library TraMineR. The application uses a function named seqefsub:
fsubseq <- seqefsub(mvad.seqe, pmin.support = min )
I have got the message: RStudio has stopped working.

**Comment by jmcphers** [comment]
Can you supply some more information?

1. What is your OS version, RStudio version, R version, and version of the TraMineR package?
2. Can you share a short snippet of R code which we can run to reproduce the problem?

Thanks!

**Comment by chingoduc** [comment]
Hi Jonathan,

RStudio 1.1.383
R 3.4.3
TraMineR 2.0.7

Also attached is the R source.

Thanks,
Chi Ngo

**Comment by dfalty** [comment]
@chingoduc It looks like the attached R code is not added to the ticket. Are you able to attach it within GitHub? Thanks!

**Comment by chingoduc** [comment]
Ok. I will.
Thanks,
Chi

**Comment by jmcphers** [comment]
The source is not attached and we haven't seen any other reports of this problem, so closing for now. @chingoduc please feel free to reopen if you're still seeing crashes with the latest RStudio (1.2.5019).
