### ISSUE TITLE
Text size issues with console command completion tips on Mac

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1975]
QtWebEngine, Mac, build 1.2.243. Haven't tried to repo on Linux or Windows.

In console, type "Sys.s", then backspace. As seen in video, resulting completions dropdown will sometimes have a bigger than expect font, sometimes smaller than expected.

![2018-01-14_20-45-28](https://user-images.githubusercontent.com/10569626/34927649-a3212242-f96c-11e7-8b66-a92e1e336bd6.gif)

![2018-01-14_20-34-33](https://user-images.githubusercontent.com/10569626/34927697-f3f23dc8-f96c-11e7-896b-969065d1a4b9.png)
![2018-01-14_19-18-04](https://user-images.githubusercontent.com/10569626/34927699-f5cc3f68-f96c-11e7-9438-eacb94b035bd.png)

**Comment by kevinushey** [comment]
Do you see the same thing if you build against Qt 5.10.0? I saw some weird rendering issues that seemed to get resolved with Qt 5.10.0, so we might want to bump up to that version if that's the case.

**Comment by gtritchie** [comment]
Today I can't repro on the same computer with the same build. Apparently only happens on Sundays? Yesterday it happened both with the actual 1.2.243 build and my local build, but not with a local server (in Chrome) or the latest 1.1 preview build.

**Comment by gtritchie** [comment]
Whoops, I forgot I was working on my laptop when I repro'd the bug. It still repros there (MacBook Pro 15") but not on my iMac 5K. Both running High Sierra 10.13.2. Haven't tried doing a 5.10 build yet.

**Comment by gtritchie** [comment]
Repro's on my MacBook Pro when built with Qt 5.9.3.

**Comment by gtritchie** [comment]
Does **not** repro when I build with Qt 5.10.0.

**Comment by gtritchie** [comment]
Resolved with Qt 5.10.0 build of RStudio (starting with 1.2.280). Here's more detail on the machine this happened on (may be specific to this graphics-card configuration).
![2018-01-23_14-08-20](https://user-images.githubusercontent.com/10569626/35303546-2ded98ca-0047-11e8-9353-6feea0fc5327.png)

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
