### ISSUE TITLE
Is Tools > Shell redundant now that we have Tools > Terminal?

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#1977]
This question is the conclusion of a discussion elsewhere with @gtritchie.

Do the cons of having both (mostly confusion, I think) outweigh the pros? Maybe this issue will attract more concrete examples of pros/cons or a rousing defence of *Tools > Shell*.

**Comment by rmflight** [comment]
My question would be:

Does the terminal **completely** replace a native shell yet?

I know there were issues using keyboard shortcuts to copy and paste from the shell (#1978), and copying and pasting from a Tmux session (#1765).

It is still nice to be able to open a shell in the project directory, IMO. 

But I also see where there could be confusion. Does the menu need to be better, to help avoid it? Or make the *shell* something enabled by users who know what they are doing, and not available in the default config?

**Comment by gtritchie** [comment]
I'm not planning on removing Tools / Shell, so closing this issue.
