### ISSUE TITLE
can't use keyboard shortcuts to copy / paste text in terminal

### ISSUE THREAD

**Issue by rmflight** [rstudio/rstudio#1978]
* Open a terminal
* Type a command
* Highlight, use keyboard shortcut to copy (Ubuntu should be Ctrl+Shift+C)
* Try to paste using keyboard (Ctrl+Shift+V)

Observe nothing being pasted into the terminal pane

**Comment by dfalty** [comment]
I can reproduce with 1.1.383 on Ubuntu 16. I can still middle click, but can't use Ctrl+Shift+V to paste. Thanks for the report!

**Comment by pitakakariki** [comment]
I'm using Git Bash on 1.1.442 on Windows 10. Ctrl+C and Ctrl+V don't work here.

**Comment by KiderDragon** [comment]
thank
