### ISSUE TITLE
Disable indexing of revdep directory in packages

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#1981]
I've noticed that RStudio becomes very laggy when running revdep checks with the revdepcheck package. I suspect that this is because all the checking happens in the `revdep/` directory where potential thousands of files are created, and RStudio is trying to index them all.

**Comment by jmcphers** [comment]
I think we'll add a general mechanism here rather than this specific exclusion, so closing in favor of https://github.com/rstudio/rstudio/issues/1984.
