### ISSUE TITLE
Return file pane to working directory if directory not found

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#1982]
1. Open a project
1. `dir.create("delete-me")`
1. Navigate to "delete-me" in the Files pane
1. `unlink("delete", recursive = TRUE)`
1. Refresh the file pane - get error dialog "Error navigating to"...
1. File pane set to home directory

I think it would be more useful to reset the active files pane directory to the current working directory

**Comment by jmcphers** [comment]
Agreed; currently tracked in https://github.com/rstudio/rstudio/issues/1630.
