### ISSUE TITLE
Cmd-C doesn't copy text

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#1987]
In 1.2.246 on Mac, selecting text (in the editor pane or console) and pressing Cmd-C doesn’t actually copy text.

With 1.2.242 (the most recent non-qtwebengine version), Cmd-C does copy text.

**Comment by kevinykuo** [comment]
+1

**Comment by kevinushey** [comment]
This is another issue that exists in Qt 5.9.2 but not Qt 5.10.0. We'll have to update (at least for macOS)

**Comment by kevinushey** [comment]
Resolved with upgrade to Qt 5.10.0.

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
