### ISSUE TITLE
Mac Desktop: keyboard shortcuts have web browser bindings instead of desktop bindings

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#1989]
For example, in 1.2.246 on Mac (QtWebEngine), the shortcut for creating a new file is Alt-Shift-Cmd-N; in 1.2.242 (pre QtWebEngine), the shortcut is Shift-Cmd-N.

The same discrepancy exists for other keyboard shortcuts as well.

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
