### ISSUE TITLE
poor rendering performance when resizing panes while packages tab visible

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1990]
When the packages pane is visible, attempts to resize the quadrants left-to-right is quite choppy:

![slow-resize](https://user-images.githubusercontent.com/1976582/35015356-e053c090-fac8-11e7-82f5-04dc77aa18c2.gif)

**Comment by jmcphers** [comment]
I can't reproduce this. Could be because you have lots of packages in your user library?

**Comment by kevinushey** [comment]
I have 98 packages installed in total; a large number but not that large? v1.1 is noticeably more responsive, though.

**Comment by dfalty** [comment]
I can't reproduce this as well on 1.2.246 (mac) with 235 packages. I wonder if something else is slowing things down.

**Comment by kevinushey** [comment]
Other things that my differentiate my environment from yours:

- Running macOS 10.13.2 on a late 2013 MBP, with all relevant OS patches
- Connected to two external monitors (both regular DPI)

Perhaps the Meltdown / Spectre patches are to blame ;-)

**Comment by kevinushey** [comment]
Spent some time debugging this, and it was indeed a local issue. It looks like RStudio and [Magnet](https://itunes.apple.com/us/app/magnet/id441258766?mt=12) do not play well together. If Magnet is running (and accessibility is enabled) before RStudio is launched, this somehow causes Chromium to get stuck rendering accessibility events (perhaps requested by Magnets?).

Here's an image of what the Instruments callstack looks like in QWebEngineProcess:

<img width="1440" alt="screen shot 2018-01-23 at 1 24 01 pm" src="https://user-images.githubusercontent.com/1976582/35301611-d1c0c654-0040-11e8-904e-0d2850c8b3c6.png">

That `AXTreeSerializer` actually keeps on going for another 30 calls (it's quite recursive!) and it looks like each call eats up another few hundred milliseconds of time.

On the other hand, if you start the applications in this order:

1. Close Magnet,
2. Start RStudio,
3. Restart RStudio,

Then RStudio is fine, and Magnet works as expected. I'm guessing that Magnet sets some kind of OS flags related to accessibility that Qt sees on startup, and then uses that to tell Chromium to handle accessibility elements during rendering.

We might be able to work around this by forcing accessibility features off at the Qt level, but we probably don't want to do that (at least by default).

**Comment by kevinushey** [comment]
For posterity, one can see the same issue when running RStudio within the Qt Nano Browser.
