### ISSUE TITLE
Live-update objects in the object explorer

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#1994]
RStudio 1.1.383 and 1.1.412

``` r
x <- list(a = c("aaa", "bbb"))
View(x)
## don't close the viewer here, just go back to console and execute:
x <- list(z = c("zzz", "yyy"))
View(x)
```

In between the first and second call of `View()`, the object `x` changes. But, as long as you don't actually close the viewer, when you revisit it the 2nd time, it shows the initial object, not the new one.

**Comment by jmcphers** [comment]
@kevinushey we might want to do something like what we do in the data viewer, where we automatically update when we detect that the object has changed (look for the `refreshData` method)

**Comment by jennybc** [comment]
I keep running into this. I'll inspect a list with `View()` (API payload). Then re-GET with new params, call `View()` again, and see the same old output. I assume my code is wrong and debug, re-read docs ... but eventually discover the call was correct, but that `View()` is not showing current value of the list 😢

**Comment by jennybc** [comment]
Things are improved but still problematic in 1.2.907.

Good news: An explicit (re-)call to `View(x)` does now re-load the list `x` in the Object Explorer and therefore reflects the new state. But it does not "live update" the way the data viewer does.

**Comment by jennybc** [comment]
I just re-ran my original reprex and now the second call to `View(x)` opens a second instance of `View()`ing `x`, both with the same contents.

<img width="168" alt="Screen Shot 2021-02-20 at 7 03 14 AM" src="https://user-images.githubusercontent.com/599454/108600072-ba47b300-7349-11eb-9047-d80e11aeae9e.png">

This does not happen for data.frames.

Also re-confirmed that the existing `View()` of a data. frame live updates, whereas that is not true for a `View()`ed list.

I'm on 1.4.1103.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.10.0-daily+64 on MacOS 12.5.

Leaving open for potential automated test.

**Comment by ronblum** [comment]
Actually, I don't think this is fully fixed.

1) Running `View()` a second time updates the original instance of the object explorer with the new values.
2) However, the original instance does automatically refresh. It still requires rerunning `View()` or clicking on the refresh button.

**Comment by romainfrancois** [comment]
I see, so this should auto refresh even without the `View()` call. I'll follow this up based on https://github.com/rstudio/rstudio/issues/1994#issuecomment-358409460

```r
x <- list(a = c("aaa", "bbb"))
View(x)
## don't close the viewer here, just go back to console and execute:
x <- list(z = c("zzz", "yyy"))
# View(x)
```

**Comment by kevinushey** [comment]
For testing, I think there are two facets to test:

First, when running this code:

```
x <- list(a = c("aaa", "bbb"))
View(x)

## don't close the viewer here, just go back to console and execute:
x <- list(z = c("zzz", "yyy"))
View(x)
```

The existing viewer tab for `x` should open and update. Previously, we were opening a separate viewer tab instead.

In addition, If you have an existing viewer tab open for `x`, and execute something like:

```
x <- list(a = list(b = 42))
```

you should see the existing tab update after executing that code in the console.

**Comment by ronblum** [comment]
This mostly works. However, if I assign something like `cars` to `x` and choose `View(x)` again, a new tab is opened.

```
x <- list(a = c("aaa", "bbb"))
View(x)
x <- list(z = c("zzz", "yyy"))
View(x)
x <- list(a = list(b = 42))
View(x)
x <- cars
View(x)
```

The original `x` tab is updated to reflect the `cars` content:
![Image](https://user-images.githubusercontent.com/31009952/187943519-18b5e634-cc13-42a8-bece-122b205ce5f2.png)

The final `View(x)` opens a new `x` tab showing the new data:
![Image](https://user-images.githubusercontent.com/31009952/187943546-b7920e28-66b0-40f8-bc18-ddd85b320628.png)

**Comment by romainfrancois** [comment]
It is also an issue the other direction, i.e. if you start by `View()`ing a data frame, and then you change `x` to not being a data frame: 

```r
x <- cars
View(x)
x <- list(a = list(b = 42, c = 1:10))
View(x)
```

The data frame `x` view is updated to : 

<img width="265" alt="image" src="https://user-images.githubusercontent.com/2625526/188419779-b7f7ab41-e8c9-4fdf-bc40-dd224409d68c.png">

And then another `x` to display non data frames shows: 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/2625526/188419855-da25206f-18b3-4177-bdcf-ed19cd4f55d1.png">

**Comment by ronblum** [comment]
Verified in RStudio Server on Ubuntu 20.04 via Chrome on MacOS 13. Testing using all of the examples above.

Consider this for an automated test.
