### ISSUE TITLE
Parallel job not starting on Mac with SOCK option

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#1996]
1.0.153
Mac OS X 10.12.2

Parallel job not starting on Mac with SOCK option. When I try on Mac it just freezes and doesn't continue. I tried in R outside of RStudio and it works fine. I also tried on RSP Ubuntu 16.04 and it also works.
https://rstudioide.zendesk.com/agent/tickets/22021

```
require(npsf) 
# Prepare data and matrices 
data(ccr81) 
head(ccr81) 

# Create some missing values 

ccr81 [64, "x4"] <- NA # just to create missing 
ccr81 [68, "y2"] <- NA # just to create missing 

Y2 <- as.matrix( ccr81[ , c("y1", "y2", "y3"), drop = FALSE] ) 
X2 <- as.matrix( ccr81[ , c("x1", "x2", "x3", "x4", "x5"), drop = FALSE] ) 

t3 <- nptestrts(y1 + y2 + y3 ~ x1 + x2 + x3 + x4 + x5, 
                        data = ccr81, homogeneous = FALSE, 
                        reps = 499, dots = TRUE, base = "o", 
                        core.count = 4, cl.type = "SOCK")
```

**Comment by kfeinauer** [comment]
The cause of the actual issue within R is that when the `R_wait_usec` global variable is set, all timeouts are constructed as tv_usec only (instead of having tv_sec and tv_usec for leftover microseconds). For example, a timeout of 60 would have the timeout struct set to tv_sec as 0 and t_usec as 60000000. This is acceptable on Linux but does not work on MacOS. We need to use `R_wait_usec` to make the UI responsive during blocking operations.

This appears to be a bug within R itself, but perhaps this could be worked around in some other way.

**Comment by jmcphers** [comment]
This would be nice to fix, but I don't think we have a realistic path forward here given that (a) this is very uncommon and (b) it's been demonstrated that fixes in this area are very risky.
