### ISSUE TITLE
'socketSelect(..., timeout = N)' does not work in RStudio

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#1997]
https://support.rstudio.com/hc/en-us/community/posts/115007977328-Problem-with-socketSelect-with-numerical-timeout.

```
library(parallel)
cl <- makeCluster(3)
socklist <- lapply(cl, function(x) x$con)
socketSelect(socklist, timeout=60)
```

Executed in a plain R session, R will wait the 60 seconds specified; however, when executed within RStudio, the socketSelect call returns immediately.

**Comment by kfeinauer** [comment]
The cause of the actual issue within R is that when the R_wait_usec global variable is set, all timeouts are constructed as tv_usec only (instead of having tv_sec and tv_usec for leftover microseconds). For example, a timeout of 60 would have the timeout struct set to tv_sec as 0 and t_usec as 60000000. This is acceptable on Linux but does not work on MacOS. We need to use R_wait_usec to make the UI responsive during blocking operations.

This appears to be a bug within R itself, but perhaps this could be worked around in some other way.

**Comment by jmcphers** [comment]
Note from the Pro side: we tried to fix this (in rstudio/rstudio-pro#155) but the fix made Interrupt R stop working.

**Comment by kevinushey** [comment]
This is where the timeout is set:

https://github.com/wch/r-source/blob/29f7e22a09c78fbb69b58f673f755c73c947509c/src/modules/internet/Rsock.c#L300-L314

Unfortunately, I don't see any nice way for us to hook in to disable the global timeout so that the user-requested timeout can be adhered to.

**Comment by jmcphers** [comment]
This would be nice to fix, but I don't think we have a realistic path forward here given that (a) this is very uncommon and (b) it's been demonstrated that fixes in this area are very risky.

**Comment by kevinushey** [comment]
Based on @jeroen's investigation, I've filed a bug with R: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=18119
