### ISSUE TITLE
Long document title makes Republish menu unreadable

### ISSUE THREAD

**Issue by ccg** [rstudio/rstudio#1998]
Here's how I ended up with this situation:

Create a static document with a short title (e.g., "hello").
Deploy to RStudio Connect.
Republish it with a very long title. ("hello this is a very long title for a very short document that contains no interesting content. hello world!")

After using the long title, most of the text on the Republish menu is not readable, because it is pushed off the left side of the window. It appears to be an issue regardless of the width of the Preview window:

<img width="683" alt="screen shot 2018-01-17 at 12 29 34 pm" src="https://user-images.githubusercontent.com/59996/35057195-31b8bd32-fb82-11e7-8fae-6d6c558c3916.png">

<img width="683" alt="screen shot 2018-01-17 at 12 29 44 pm" src="https://user-images.githubusercontent.com/59996/35057202-340849fe-fb82-11e7-8941-85062dfd0201.png">

<img width="1202" alt="screen shot 2018-01-17 at 12 30 01 pm" src="https://user-images.githubusercontent.com/59996/35057205-365a52ec-fb82-11e7-9386-6659aa5aed47.png">

**Comment by jmcphers** [comment]
No reports in almost two years, so closing. We have made this a lot better in 1.3 by making sure all of these panels do not overflow.
