### ISSUE TITLE
tab naming ambiguity

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#2001]
I have a number of different R Markdown reports and Shiny applications in subdirectories of a root project directory. All of these files are named `index.Rmd` and `app.R`.

The RStudio editor tabs should allow more path breadcrumbing. Hovering over the tab to figure out the path is too slow.

![screen shot 2018-01-17 at 1 51 33 pm](https://user-images.githubusercontent.com/362187/35060873-91e34b9a-fb8d-11e7-8d33-ebbbf185efd7.png)

Some editors compute a unique path breadcrumb and use that to help indicate the path when there are many same-named files in play. 

Something like either the "forward" or "post-forward" strategy from the emacs "uniquify" package could be appropriate. https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html

You can see examples of the various strategies here: https://github.com/emacs-mirror/emacs/blob/6e9f20b3ff49adfc05a7f4b49b1b92daa4fb1ca9/lisp/uniquify.el#L96-L119

 An `index.Rmd` file in directories `frodo` and `bilbo` would end up having a tab named `frodo/index.Rmd` (forward) or `index.Rmd|frodo` (post-forward). Path information would only be added when tab names are ambiguous.

**Comment by kevinushey** [comment]
We do attempt to generate unique paths if you click the 'More' button (see the chevron at the right side of the menu bar on the list of open tabs).

![screen shot 2018-01-22 at 9 15 58 am](https://user-images.githubusercontent.com/1976582/35234119-e0e0a628-ff54-11e7-92a3-fef3cfa15615.png)

You can also use <kbd>Ctrl+X B</kbd> (unconditionally on macOS; only when Emacs keybindings are active on other OS) to quickly open the 'buffer' list and navigate to the `index.Rmd` you're looking for. Or <kbd>Ctrl+Shift+.</kbd>. Is that sufficient in your case?

**Comment by aronatkins** [comment]
@kevinushey I didn't know about that! It's close. It's missing a quick visual indication of the path for the _current_ tab.

**Comment by kevinushey** [comment]
Now with oblique text, showing the currently selected tab:

![screen shot 2018-01-22 at 10 24 22 am](https://user-images.githubusercontent.com/1976582/35237106-6f285c2e-ff5e-11e7-89f5-1982fb3a222e.png)

**Comment by jmcphers** [comment]
See #5772 for another request to disambiguate directly in the tab name.
