### ISSUE TITLE
External Notebook Panes Appearance in RStudio Server v1.1.383

### ISSUE THREAD

**Issue by msummersgill** [rstudio/rstudio#2003]
After upgrading to Rstudio-server version 1.1.383 running on Ubuntu 14.04 some of the display behaviors have are not as expected.

Using RStudio "Classic" appearance theme with "Pastel on Dark", the appearance of Notebook Outputs is inconsistent, and unfortunately unusable in some cases.

Will this be patched in an upcoming release, and if not, are there any recommended appearance settings  that should work properly?

### After initially popping out pane

Pane is light gray (not ideal, previous version reflected in-editor white-on-black formatting) and readable.

![image](https://user-images.githubusercontent.com/19575728/35065149-f82c97e0-fb91-11e7-8566-a15b7116c612.png)

### After executing `View(mtcars)`
Background of popped-out pane switches to the (expected) dark formatting, but the text in the pane turns black and is no longer readable.

![image](https://user-images.githubusercontent.com/19575728/35065486-04707408-fb93-11e7-9072-cdd9a84d5103.png)

### Appearance options

![image](https://user-images.githubusercontent.com/19575728/35064772-bf268d80-fb90-11e7-96e6-e5a5fcb3941c.png)

### RStudio version:
![image](https://user-images.githubusercontent.com/19575728/35064802-d89dd6a6-fb90-11e7-8740-4f390e628ffc.png)

### Google chrome version:

![image](https://user-images.githubusercontent.com/19575728/35064878-0ca7d186-fb91-11e7-8957-c036d70b7d5c.png)

**Comment by dfalty** [comment]
@msummersgill Thanks for the report. You should be able to use the Modern theme until this is fixed.

**Comment by jmcphers** [comment]
Still an issue in 1.2.1335-1.
