### ISSUE TITLE
"New RStudio Window" command missing from dock menu

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2004]
On RStudio 1.1.x for Mac, right click on the dock menu and there's a command to launch a new window:

![2018-01-17_15-46-21](https://user-images.githubusercontent.com/10569626/35073430-95275160-fb9d-11e7-866a-3afa5e21f29c.png)

This is missing with the 1.2.243+ builds.
![2018-01-17_15-47-48](https://user-images.githubusercontent.com/10569626/35073473-cb49424e-fb9d-11e7-8804-16e84cffb314.png)

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
