### ISSUE TITLE
RStudio windows not shown in Dock menu

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2005]
On Mac, launch RStudio, open an R source file, and pop it into a separate window.

Right-click on the dock icon. With RStudio 1.1.414, the windows are listed. With RStudio 1.2.243+, they are not.

1.1.414
![2018-01-17_15-58-41](https://user-images.githubusercontent.com/10569626/35073849-c42f173e-fb9f-11e7-9d69-4de7d3b856e7.png)

1.2.243
![2018-01-17_16-00-20](https://user-images.githubusercontent.com/10569626/35073855-cde97512-fb9f-11e7-9723-24eded709e4c.png)

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
