### ISSUE TITLE
 Error showing while opening rstudio in terminal ubuntu 17.10

### ISSUE THREAD

**Issue by sandhaya4u** [rstudio/rstudio#2006]
Error showing ("TypeError: undefined is not an object (evaluating 'window.desktopHooks.notifyRCrashed')"
QIODevice::read: device not open
QIODevice::read: device not open ) while opening rstudio in terminal ubuntu17.10

**Comment by sandhaya4u** [comment]
Kindly suggest a effective solution as soon as possible as I unable to use it.Please look this problem.

**Comment by ronblum** [comment]
@sandhaya4u Can you please provide the version of RStudio that you are using, including both version number and server/desktop? Thanks!

**Comment by jmcphers** [comment]
Haven't heard back in over a year so closing.
