### ISSUE TITLE
Is non-root build of rstudio server supported or at least possible in principle?

### ISSUE THREAD

**Issue by adamryczkowski** [rstudio/rstudio#2008]
I am a user of several HPC. I would like to try using rstudio-server there. Unfortunately admins are not willing to install it for me, so I decided to try building one on my own.

I understand, that rstudio server run as non-root user will not be installed as a system service and it will have to listen to the high tcp port. But other than that I don't see any fundamental problems.

**Comment by jmcphers** [comment]
This issue tracker is for reporting bugs with RStudio. I'd suggest asking your question in the R Admins section of our community forum:

https://community.rstudio.com/c/r-admin
