### ISSUE TITLE
Commands on MacOS appear to be bound to Cmd instead of Ctrl

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2010]
## System details

    OS Version      : MacOS 10.13.2
    RStudio Version : 1.2.246
    R Version       : 3.4.2

### Steps to reproduce the problem

Press Ctrl + Tab to switch to the next tab.

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

Tab switches successfully. It looks like the command used to be bound to Ctrl + Tab on MacOS but is now incorrectly bound to Cmd + Tab.

**Comment by kevinushey** [comment]
Are we sure that this is the problem? I see in `commands.cmd.xml`, for example:

    <shortcut refid="nextTab" value="Ctrl+Alt+Right" if="!org.rstudio.core.client.BrowseCap.isLinux()"/>

and this works as expected on macOS Desktop. Despite that, this doesn't work:

    <shortcut refid="nextTab" value="Ctrl+Tab" if="org.rstudio.studio.client.application.Desktop.isDesktop()"/>

Is it possible that the shortcuts emitter is mis-detecting whether we're desktop, or something similar? (it relies on `window.desktop` being available and I believe that is no longer true at startup due to changes with QtWebEngine)

**Comment by jmcphers** [comment]
Yes, just looking at the menu you can see it's bound to Cmd+Tab rather than Ctrl+Tab:

![image](https://user-images.githubusercontent.com/470418/35119192-055c1596-fc49-11e7-8acb-3f340c79a60e.png)

**Comment by kevinushey** [comment]
I think the display is incorrect in the menu, then. Notice also that `Switch to Tab` is marked as:

![screen shot 2018-01-18 at 12 17 15 pm](https://user-images.githubusercontent.com/1976582/35119397-998244e8-fc49-11e7-892a-5d0c42ec6071.png)

But the command itself is invoked by <kbd>Ctrl + Shift + .</kbd> (and the variant using <kbd>Command</kbd> does not work).

**Comment by jmcphers** [comment]
Weird. I guess the display is just wrong, then, and we have two bugs: one is that they aren't being displayed correctly, and the other is that they aren't working. I'll use this bug to track the former.
