### ISSUE TITLE
Dragging a tab to pop out a source window does not work

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2012]
This seems to be because the way the final 'dragleave' event is passed to us has changed: now, it returns the last mouse position in the window before leaving the window surface, and this implies there is a drag target in the end: https://github.com/rstudio/rstudio/blob/e4e5c99990e267b281f9a7a4432a09d399888720/src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java#L926-L964

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/c297287b48bb6c532c6ef4ef0ab7fc4080867b54

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
