### ISSUE TITLE
openxlsx code fails with argument to 'findVar' is not an environment

### ISSUE THREAD

**Issue by GeraldCNelson** [rstudio/rstudio#2014]
### System details

    OS Version      : Mac 10.13.2
    RStudio Version :  1.1.414
    R Version       : 3.4.3

### Steps to reproduce the problem
Run the following code
`numStyle <- openxlsx::createStyle(numFmt = "0.00", halign = "right")`
### Describe the problem in detail
The response is 

> Error in (function (env, objName)  : 
>   argument to 'findVar' is not an environment

### Describe the behavior you expected
A style is assigned to the variable numStyle. this line of code works properly if run in a shell.

<!-- Depending on the problem, the following may also be helpful

1. The output of sessionInfo() 
2. The R code in question
3. A diagnostics report

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1644943/diagnostics-report.txt)

**Comment by kevinushey** [comment]
Thanks for reporting! This has already been reported at #1965.

**Comment by GeraldCNelson** [comment]
Where do I download RStudio 1.1.383 until you have fixed this bug?
 

 

 

Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by jmcphers** [comment]
@GeraldCNelson You can get 1.1.383 here: 

https://download1.rstudio.org/RStudio-1.1.383.dmg

**Comment by GeraldCNelson** [comment]
Thanks!

 

 

Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by jmcphers** [comment]
@GeraldCNelson We now have a fix; would you be willing to see if it addresses the problem for you?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by GeraldCNelson** [comment]
Seems to work fine. Thanks for the quick fix!

 

Jerry

 

 

Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d
