### ISSUE TITLE
Ctrl + Tab / Ctrl + Shift + Tab don't work in RStudio Desktop

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2015]
### System details

    OS Version      : MacOS 10.13.2
    RStudio Version : 1.2.254
    R Version       : 3.4

### Steps to reproduce the problem

1. Open several tabs.
2. Select the leftmost tab.
3. Press Ctrl+Tab.

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

The next tab to the right is selected.

This is a followup to issue #2010, in which the keyboard shortcuts to these commands were not displayed correctly. They are now displayed correctly, but they don't work.

Some light debugging suggests that the `ShortcutManager` is not receiving the Tab key (scancode 9) when Ctrl is held down (perhaps `QtWebEngine` is reserving the shortcut for its own tab switching?)

**Comment by jmcphers** [comment]
See `QKeySequence::NextChild` / `QKeySequence::PreviousChild`, which are bound on macOS to the shortcuts in question.

**Comment by kevinushey** [comment]
Finally found this in the Qt documentation (https://doc.qt.io/qt-5/qcoreapplication.html#notify):

> Reimplementing QObject::event() (as QWidget does). If you do this you get Tab key presses, and you get to see the events before any widget-specific event filters.

I think overriding `bool event(QEvent*)` on the `BrowserWindow` class will get us access to these keypresses.

**Comment by kevinushey** [comment]
And just because I was curious, here's the handling within QWidget (indeed hardcoded)

https://github.com/qt/qtbase/blob/5.10/src/widgets/kernel/qwidget.cpp#L8918-L8929

**Comment by kevinushey** [comment]
Ran around in circles on this, but looks like it may be a long-standing Qt bug: https://bugreports.qt.io/browse/QTBUG-8596

Unfortunately, the only fix proposed involves patching Qt's sources.

**Comment by jjallaire** [comment]
I have a sinking feeling that we may need to build Qt for OS X from source in able to get the product working the way we want to. I can recall now that one of the motivations for the Cocoa port (besides the performance bug we hit) was that Qt for OS X seemed like a 2nd class citizen and that many bugs went unfixed. I still like the idea of a common codebase but it could be that we just need to bite the bullet and be able to fix bugs in Qt if we need to.

**Comment by kevinushey** [comment]
I was finally able to find a workaround for this last night: https://github.com/rstudio/rstudio/commit/fedabf4fc6d9f7f6899af048684df1988208f661

We might still need to build Qt from sources just for the scrollbar bug, though...

**Comment by dfalty** [comment]
Verified fixed 1.2.359.
