### ISSUE TITLE
Rstudio fails to open or give error message. Hangs.

### ISSUE THREAD

**Issue by AMChalkie** [rstudio/rstudio#2018]
### System details

    OS Version      : OSX
    RStudio Version : 1.1.383
    R Version       :R version 3.4.2 (2017-09-28) -- "Short Summer"

### Steps to reproduce the problem
Add R_MAX_NUM_DLLS=256 to .Renviron
Start Rstudio.
(causes a hang)
more .Renviron
R_MAX_NUM_DLLS=256

### Describe the problem in detail
Max DLL causes an error. However RStudio hangs and does not give any information about the cause of the hang. Removing .Renviron caused the problem to cease so confident that is the env variable causing the problem.

[achalk@svi-4001 ~] 2018-01-19 16:21:57$ >/Applications/RStudio.app/Contents/MacOS/RStudio --run-diagnostics

Using R script: /Library/Frameworks/R.framework/Versions/3.4/Resources/bin/R

Attempting to launch R session...
  R_HOME=/Library/Frameworks/R.framework/Resources
  R_DOC_DIR=/Library/Frameworks/R.framework/Resources/doc
  R_INCLUDE_DIR=/Library/Frameworks/R.framework/Resources/include
  R_SHARE_DIR=/Library/Frameworks/R.framework/Resources/share
  PATH=/Users/achalk/.rvm/gems/ruby-2.4.2/bin:/Users/achalk/.rvm/gems/ruby-2.4.2@global/bin:/Users/achalk/.rvm/rubies/ruby-2.4.2/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/achalk/perl5/perlbrew/bin:/Users/achalk/perl5/perlbrew/perls/perl-5.24.0/bin:/opt/local/bin:/opt/local/sbin:/opt/IGVTools/:/opt/ViennaRNA/bin/bin/:/Volumes/SVI_STEMCELL_BIOINFO/src/bpipe-0.9.9/bin:/Users/achalk/Documents/software/kallisto:/Applications/bin:/opt/IGVTools/:/opt/./libgd-2.1.0/config:/opt/bin:/opt/lib:/Users/achalk/perl5:/opt/lib:/opt/bin:/opt/HTSeq-0.6.1/HTSeq/scripts:/opt/HTSeq-0.6.1/scripts:/opt/ngsplot/bin:/Users/achalk/Documents/software/STAR-2.5.3a/bin/MacOSX_x86_64:/Users/achalk/Documents/software/Anaquin_1.1.0/osx:/Users/achalk/Documents/software/bbmap:/Users/achalk/Documents/software/kallisto:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/munki:/Applications/RStudio.app/Contents/MacOS/pandoc:/Users/achalk/.rvm/bin
  HOME=/Users/achalk

19 Jan 2018 05:22:00 [rsession-achalk] ERROR R SUICIDE: MAX_NUM_DLLS bigger than 153 may exhaust open files limit; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

**Comment by kevinushey** [comment]
Thanks for the bug report! This also reproduces R.app, so strictly speaking the issue is not unique to RStudio. That said, I'm a little confused as to why this issue only reproduces when R is run with a GUI frontend and not within the terminal.

The value of 153 (== 256 * 0.6) suggests that, at startup, R / RStudio believes that the limit on the number of file descriptors at startup is 256; however, after RStudio has initialized the limit appears to be 2560.

FWIW I used this script to check that:

```
#include <Rcpp.h>
using namespace Rcpp;

extern "C" int R_GetFDLimit();

// [[Rcpp::export]]
int fdlimit() { return R_GetFDLimit(); }

/*** R
fdlimit()
*/
```

**Comment by plijnzaad** [comment]
Just to add a data point: I am getting the exact same error when running R (version 3.4.1) inside emacs using ESS. I don't get it when running on the command line (which I think emacs + ESS is trying to mimic)

**Comment by kevinushey** [comment]
I think RStudio may need to read the value of `R_MAX_NUM_DLLS` and set the FD limit early on in initialization to fix this.

**Comment by jmcphers** [comment]
Good news, R does this for us now!

https://developer.r-project.org/Blog/public/2018/03/23/maximum-number-of-dlls/

> To make this behavior more user-friendly, R 3.5.0 automatically aims at a higher DLL limit (currently 614) when R_MAX_NUM_DLLS is not set. When the OS limit on the number of open files is too small for this, R attempts to increase the limit via setrlimit() on POSIX systems (on Windows, no increase is necessary).

**Comment by jmcphers** [comment]
(realize this is just with the default and not with custom values, but I think that's reasonable given the frequency of incidence)
