### ISSUE TITLE
Enhancment Request - Spell Checker

### ISSUE THREAD

**Issue by ResourceX** [rstudio/rstudio#2019]
### System details

    OS Version      : Windows 10
    RStudio Version : 1.0.143
    R Version       : 3.4.1

### Steps to reproduce the problem
In shiny for example, text that will go to an end user is somehow identified when spelled wrong. h2('Hello Worl') would flag world as possibly misspell
### Describe the problem in detail
I use shiny and shinyserver Pro in a small business running a saas application. It is very embaressing for me when our end users point out mistakes. I am a horrible speller and thought if the IDE had some sort of spell checking options. I realize that is a challenge as it is also code, not text, but if the text is tagged maybe it could be checked. 

### Describe the behavior you expected
Standard spell checking you see in most applications where misspelled text is identified with red squigle underline

**Comment by rmflight** [comment]
There is spell checking functionality in RStudio, see the "Edit" menu, "Check Spelling" (near the bottom), or try the "F7" shortcut. Does that do what you want? 

I don't know that spell checking as you type would be appropriate for writing *mostly* code anyways.

**Comment by ResourceX** [comment]
Thanks for the reply. Sorry, I do not see that option in my version, I will have to update. I determined my version was 1.0.143 by finding the version file in the program files. 

Let me try to clarify. I get it, it is mostly code and it was a long shot request. This was an "enhancement" idea I had, I was encouraged to pass along, I don't need it. :)

My idea was it is somehow smart enough to check only the words within certain tags. Particularly, in the ways RStudio IDE is geared toward shiny app development. Like maybe when you runApp() the words in the viewer pain that are mispelled are tagged or highlighted in some way.

**Comment by jiho** [comment]
I feel your "viewer pain" ;-)

In TextMate (a "mostly code" editor) this is restricted to certain contexts:
- quoted strings in code (i.e. `.R`) files
- everything but code in code chunks in RMarkdown files
It works well enough.

**Comment by jmcphers** [comment]
Closing this since we do indeed have spell checking. :-)
