### ISSUE TITLE
Help Links Not Visible With Classic Theme and Dark Palatte 

### ISSUE THREAD

**Issue by iantperry** [rstudio/rstudio#2024]
### System details

    OS Version      : Linux, Windows
    RStudio Version : 1.1.383
    R Version       :  3.4.3

### Steps to reproduce the problem
Set theme to Classic
Set Palette to Material or Dracula
### Describe the problem in detail
Help links are rendered in white text on a white background making them invisible.
The these two palettes (Material and Dracula) cause the CSS styling for the help box to switch to the dark theme with white link text (I assume this is because a dark background is expected), but since Classic is always light and has a white background, you can't read the text.
### Describe the behavior you expected
When Classic theme is used dark mode always stays off so link text is legible.

**Comment by ronblum** [comment]
Confirmed with RStudio 1.1.414:
MacOS Desktop
Windows Desktop
RStudio Server on Ubuntu 16.04 using MacOS Chrome

**Comment by iantperry** [comment]
Thanks!

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
