### ISSUE TITLE
Disable the environment viewer?

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#2029]
I am finding RStudio increasingly sluggish to the point where I want to switch editors when working on my laptop.

One lightening feature might be to allow the user to switch off the environment pane.

**Comment by kevinushey** [comment]
For posterity, in v1.2 of RStudio we plan to introduce a feature that allows the user to disable automatic refresh of the environment pane. See the small down arrow next to the refresh button:

![screen shot 2018-01-22 at 8 53 22 am](https://user-images.githubusercontent.com/1976582/35232991-c81cb1e8-ff51-11e7-97e7-48cae79f4af2.png)
