### ISSUE TITLE
Option to delete terminal buffer on RStudio close

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#2030]
I'm often slowed down by a large (unwanted) buffer loading as RStudio restarts. This is usually caused by an RStudio crash caused by too much stuff being printed to the terminal at once.

Would be great to be able to automatically kill the terminal buffer when RStudio crashes or closes.

**Comment by ronblum** [comment]
@kendonB Thank you for the suggestion. In the meantime, what version of RStudio and OS are you running on, and can you provide an example of providing too much stuff in the terminal? I tried reproducing it with
`find / -exec ls -la {} \;`
which prints tens of thousand of files in environment (or more), but RStudio didn't crash.

**Comment by gtritchie** [comment]
Perhaps "terminal" here actually means the **R Console**? We don't reload the terminal buffers when R restarts (that is deferred until you actually open the terminal pane and switch to a given terminal). But we do reload the R Console.

**Comment by kendonB** [comment]
Apologies for the slow reply. I'm using the latest RStudio preview and Windows 10 x64.

I do mean the terminal and by "Rstudio restarts" I actually mean "Rstudio restarts and I navigate to the terminal".

An example action I take is to accidentally print a large ``data.frame`` in the R session on the server I ssh into via the terminal.

**Comment by kendonB** [comment]
Rstudio also doesn't exactly "crash"; it hangs and fails to respond.

**Comment by gtritchie** [comment]
@kendonB Thanks, that helps a lot in figuring out what's happening!

**Comment by kendonB** [comment]
The terminal is so fast to load (and print it's history) now that this problem is no longer much of an issue.
