### ISSUE TITLE
RStudio keep hanging when "Quit Session" or saving file

### ISSUE THREAD

**Issue by abbatidanilo** [rstudio/rstudio#2036]
Hello,
RStudio keeps on hanging when you try to quit or to save a file. In particular I am writing a RMarkdown note with nothing especial on it. 
The issue happens some time using RStudio-1.0.153 but much often when using the most recent RStudio-1.1.414. I tried with the most recent R compiler 3.4.2 but I also downgrade to 3.4.0 and 3.3.3 (which is the one I currently using). I cannot say if this depends on the R compiler or the RStudio version itself, but it seems the older, the better...
I opened the same issue last week but in that case I did not send any detail. Here at least I managed to have the diagnostics-report.
I cannot provide the sessioninfo() because when it hangs, the only way is to kill the process.
OS: Windows 10 pro on an Intel i5 2540M CPU  
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1655133/diagnostics-report.txt)

**Comment by ronblum** [comment]
[Note: this is a followup to #2007 ]
