### ISSUE TITLE
Allow user customization of highlight rules

### ISSUE THREAD

**Issue by HughParsonage** [rstudio/rstudio#2042]
I like the way editor themes in RStudio colours functions like `if`, `function`, and `stop`. This feature would extend this syntax highlighting so that certain user-supplied words (like, say, `abort`) can be coloured the same way.

**Comment by kevinushey** [comment]
I've modified the title of the post just to make it a bit more general (to reflect requests other users might have). Thanks for filing a request!

**Comment by HughParsonage** [comment]
I was actually hoping you'd edit the title!

**Comment by harrismcgehee** [comment]
Extending this: Would also like the ability to modify highlight rules for other file types. Specifically Tex files.

**Comment by Dries-B** [comment]
Allowing users to customize syntax highlighting and letting them build up community profiles would probably circumvent most of the following issues: https://github.com/rstudio/rstudio/issues?q=is:issue+label:enhancement+sort:reactions-%2B1-desc+is:open+syntax+highlight
