### ISSUE TITLE
RMD chunk execution fails - RStudio Server

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2047]
### System details

    OS Version      : RHEL 7.3
    RStudio Version : 1.2.278-4
    R Version       : 3.4.1

### Steps to reproduce the problem
1. Open RMD file 
2. Try to run any chunk
3. Observe chunk execution will freeze and not execute.

### Describe the problem in detail
RMD chunk execution fails on latest daily builds of RSP. This does not reproduce on 1.2.239-3. The following error is logged when trying to run chunk.

`24 Jan 2018 14:29:25 [rsession-jan24] ERROR system error 111 (Connection refused); OCCURRED AT: void rstudio::core::http::TcpIpAsyncConnector::handleConnect(const rstudio_boost::system::error_code&, rstudio_boost::asio::ip::basic_resolver<rstudio_boost::asio::ip::tcp>::iterator) /var/lib/jenkins/workspace/IDE/pro-pipeline/master/src/cpp/core/include/core/http/TcpIpAsyncConnector.hpp:135; LOGGED FROM: void rstudio::session::modules::rmarkdown::notebook::{anonymous}::NotebookQueue::consoleThreadMain() /var/lib/jenkins/workspace/IDE/pro-pipeline/master/src/cpp/session/modules/rmarkdown/NotebookQueue.cpp:488`

**Comment by kevinushey** [comment]
This sounds like it could be the first instance of using TCPIP rather than the Unix domain sockets causing issues for us. @jmcphers does that sound right?

**Comment by kevinushey** [comment]
Just realized this is RSP, not desktop, so whatever is going on should be unrelated to the WebEngine work.

**Comment by jmcphers** [comment]
Confirmed repo in open source RStudio Server, too.

**Comment by dfalty** [comment]
Verified fixed 1.2.302-3.
