### ISSUE TITLE
Version 1.2.288 doesn't work well with Scaling in Windows display settings

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#2051]
### System details

    OS Version      : Windows 10 Pro
    RStudio Version : 1.2.288
    R Version       : 3.4.3

### Steps to reproduce the problem

Using 1.2.288 on Surface Pro 3 with Display scaling set to 150% which is the best settings that work for all other softwares and apps

### Describe the problem in detail

RStudio windows and fonts become huge and not usable.

### Describe the behavior you expected

Used to be fine on version 1.2.240 and below. 

<img width="1029" alt="rstudio" src="https://user-images.githubusercontent.com/6590141/35352638-6c820d02-00f9-11e8-9fe9-da4324f7b68e.PNG">
<img width="716" alt="rstudio2" src="https://user-images.githubusercontent.com/6590141/35352639-6c9c775a-00f9-11e8-9f7e-48935df18c4e.PNG">
<img width="348" alt="rstudio3" src="https://user-images.githubusercontent.com/6590141/35352644-72b1a1e2-00f9-11e8-9367-d12ccdcabc66.PNG">

**Comment by tungmilan** [comment]
Just tried RStudio Preview 1.1.419 and things back to normal. There must be some commits that changed the zooming behaviour

<img width="1029" alt="rstudio4" src="https://user-images.githubusercontent.com/6590141/35353085-eaa0b1ce-00fa-11e8-9efb-1d24e67bcf0c.PNG">

**Comment by kevinushey** [comment]
Thanks for the bug report. We're doing a heavy architectural revamp of things in the daily builds of RStudio and there's a lot of fallout that still needs to be cleaned up. We'll be tackling these issues soon!

**Comment by gtritchie** [comment]
I just saw that, too. Try using RStudio's View/Zoom Out for now to get back
to something sane with 1.2. That may result in 1.1 becoming tiny, though.
Suspect we've got different scaling units being stored in our preferences.

**Comment by kevinushey** [comment]
It _seems_ as though the scaling is doubled on Windows: if the global UI scaling is set to 200%, but RStudio's zoom factor is set at 1, then the net effect is that RStudio is displayed 2x larger than expected.

We might need to scale the zoom factor (on Windows?) according to the system's global zoom level...

**Comment by kevinushey** [comment]
There's also a fix for oversized scrollbars coming for Qt 5.10.1 so we'll definitely need to pick that up when it's released (hopefully coming soon).

**Comment by scientistanton** [comment]
I'm having a similar set of issues.
## System Details
Computer : Surface Pro
External Monitor: U2715H
OS : Windows 10 Enterprise 64-bit
RStudio: Version 1.1.423
R version: 3.4.3

## Issue 1
When displayed on the external monitor at 100% (recommended) scaling (resolution 2560 x 1440 (Recommended)) the RStudio windows and fonts become huge. The menu font size is normal but the spacing is oversized. The RStudio view is fully zoomed out (100%)
![image](https://user-images.githubusercontent.com/8278116/36187837-1837eace-119c-11e8-9191-1c2e33c31c7e.png)

**Comment by scientistanton** [comment]
## Workaround
I found a solution in Windows, by finding rstudio.exe in "C:\Program Files\RStudio\bin", right clicking and opening "Properties" and on the "Compatibility" tab ticking **Override high DPI scaling behaviour.** and setting **Scaling performed by:** to "System".
![image](https://user-images.githubusercontent.com/8278116/36188449-33ad1f8c-11a0-11e8-837c-4424c03ccc23.png)

**Comment by tungmilan** [comment]
The latest 1.2.669 is better. But I still have to change the zoom level (to 75%) & font size (smaller) to make it look as good as v1.1.xxx

**Comment by JavOrraca** [comment]
@scientistanton - Your workaround worked like a charm for me. Thank you VERY much.

**Comment by tungmilan** [comment]
On the external monitor, RStudio 1.2.870 has a black bar on top of the menu selection. To select any menu, the mouse pointer needs to be place a little bit above the letter & in the black bar

![](https://i.imgur.com/0o2TQXp.png)

**Comment by tungmilan** [comment]
Actually it happens to every menu on all panels: mouse pointer needs to be higher than the menu name to select it

**Comment by kevinushey** [comment]
One user reported that changing the display color from True Color (32bit) to High Color (16bit) resolved a similar issue; does that make a difference in your case?

**Comment by tungmilan** [comment]
@kevinushey : thanks but it did not work for me. The trick by @scientistanton somehow eliminated that problem in the external screen.  However, the GUI & the text on the main screen of the Surface Pro 3 are a little bit blurry & not as crisp as before because of that change.

**Comment by tungmilan** [comment]
Another problem I've just found out today: when connecting to the external monitor, I could start another RStudio session just fine. But if I removed the external monitor and tried to start another session, the 2nd session wouldn't show up. When I clicked on the white windows or used Alt + Tab to select it, nothing happened

![](https://i.imgur.com/YHlzlxR.png)

**Comment by kevinushey** [comment]
@tungmilan just to confirm, is this the sequence of steps?

1. Ensure laptop is connected to external monitor;
2. Launch RStudio,
3. Remove external monitor,
4. Launch another RStudio session.

That is, does the issue _only_ occur if the display configuration changes while RStudio is active?

In other words, can you launch a second RStudio session if the external monitor is eliminated from the equation entirely?

**Comment by tungmilan** [comment]
@kevinushey : 
> is this the sequence of steps?
Yes
> does the issue only occur if the display configuration changes while RStudio is active?
Yes. If I need the 2nd session to work, I need to exit RStudio completely and start all over again
> In other words, can you launch a second RStudio session if the external monitor is eliminated from the equation entirely?
Yes

**Comment by tungmilan** [comment]
Looks like the problem when removing the external monitor I reported last month has been fixed in recent release. Thank you guys for the hard work

**Comment by janvanderende** [comment]
I just installed Rstudio 1.2.1335 with R 3.5.3 on windows 10 and unfortunately I eperienced the scaling problem with this version. In the latest Rstudio 1.1 everything worked well, but now the panels are way too large, that is with very large texts, while the menu is ok. I tried the work around by changing the properties of the Rstudio program, but it did not gave satisfactorily results. Although the panels changed a bit, there were still very large. It is actually very difficult to work with Rstudio now. Does someone has a different solution to the problem?

**Comment by janvanderende** [comment]
Rstudio 1.2 is now behaving properly! I changed the zoom factor in the appearance panel of the global options in Rstudio to 75%. The result was a much smaller text. I found it too small now, so I changed it in small steps back to 100% and now Rstudio appeared to "normal" again. It seems a bit weird because I ended up with the scaling factor and Rstudio's zoom factor I originally had. Perhaps did the work around after all!

**Comment by JianghuiDu** [comment]
still cannot solve this problem on my computer. Windows 10 + Rstudio 1.2.1335. I was able to reduce font size using zoom, but the menu bars etc were not affected at all. Still way to large, such that the drop down menu occupied the whole window.

**Comment by Avi-Kenny** [comment]
I'm also having this scaling issue after upgrading to 1.2.1335, and @scientistanton's solution did not work for me (everything appeared blurry). One simple fix would be to add additional zoom levels between 50% and 75%. The former is too small and the latter is too large.

Happy to provide hardware/OS details if needed.
