### ISSUE TITLE
Disable QtWebEngine developer tools by default

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2053]
### System details

    OS Version      : MacOS 10.13.3
    RStudio Version : 1.2.288
    R Version       : 3.4.2

### Steps to reproduce the problem

1. Start RStudio
2. Browse to http://127.0.0.1:59009

### Describe the problem in detail

A developer console opens. This is very helpful, but shouldn't be enabled by default for security reasons. See https://bugreports.qt.io/browse/QTBUG-50725 (h/t @kevinushey)

### Describe the behavior you expected

The developer console should not be enabled all the time due to the above security concerns. Ideally it'd be possible to turn it on at runtime for just-in-time analysis, but failing that we should gate it on a flag we can turn on only when needed for debugging.

**Comment by kevinushey** [comment]
Done with https://github.com/rstudio/rstudio/commit/c19d6ebb69edfdb875830bb4833ada325653305a. It can be re-enabled by setting the `RSTUDIO_USE_CHROMIUM_DEVTOOLS` environment variable to something non-empty. Note that debug builds will have the console enabled by default.

If we want to provide a simpler mechanism for re-enabling this I think we can pursue that in the future.
