### ISSUE TITLE
Bookdown project creation failure

### ISSUE THREAD

**Issue by espinielli** [rstudio/rstudio#2055]
### System details

    OS Version      : x86_64-w64-mingw32/x64 (64-bit)
    RStudio Version : Version 1.1.419 
    R Version       : 3.4.3 (2017-11-30)

### Steps to reproduce the problem

1. Select menu entry "File -> New Project..."
1. Select "New Directory"
1. Select "Book Project using bookdown"
1. Choose a Directory name, for example abc
1. Leave "Create Project as subdirectory of:" to C:/repos (my usual place for projects)

### Describe the problem in detail

I want to create a bookdown project in a new directory.
I get an error popup dialog saying 

> R code execution error

and the following in the console:

> Error in gsub(pattern, val, transformed, ignore.case = TRUE) : 
>  invalid regular expression '\$Sys.setenv(PATH\b', reason 'Missing ')''

Here is a screenshot

![bookdown_project_creation_failure](https://user-images.githubusercontent.com/891692/35385564-fb5691ea-01c8-11e8-8cf8-3556eb9c2f15.PNG)

### Describe the behavior you expected

I expect a new project with bookdown template.
If I create a normal project in a new directory it works.

> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.419)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Paris                
 date     2018-01-25                  

Packages ------------------------------------------------------------------------------------------------------------------
 package   * version    date       source                          
 base      * 3.4.3      2017-12-06 local                           
 bookdown    0.5        2017-08-20 CRAN (R 3.4.3)                  
 compiler    3.4.3      2017-12-06 local                           
 datasets  * 3.4.3      2017-12-06 local                           
 devtools  * 1.13.4     2017-11-09 CRAN (R 3.4.2)                  
 digest      0.6.14     2018-01-14 CRAN (R 3.4.2)                  
 graphics  * 3.4.3      2017-12-06 local                           
 grDevices * 3.4.3      2017-12-06 local                           
 knitr       1.18       2017-12-27 CRAN (R 3.4.3)                  
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.1)                  
 methods   * 3.4.3      2017-12-06 local                           
 stats     * 3.4.3      2017-12-06 local                           
 tools       3.4.3      2017-12-06 local                           
 utils     * 3.4.3      2017-12-06 local                           
 withr       2.1.1.9000 2018-01-19 Github (jimhester/withr@df18523)
 yaml        2.1.16     2017-12-12 CRAN (R 3.4.3)

**Comment by kevinushey** [comment]
I wasn't able to reproduce this with the latest version of bookdown (0.6). Can you try updating bookdown and see if the problem persists?

**Comment by espinielli** [comment]
Upgrading to newest bookdown (and all other pakages) does not solve the issue.
Retested in new session, see screenshot:

![bookdown_project_creation_failure_bookdown06](https://user-images.githubusercontent.com/891692/35434961-4649f140-0289-11e8-9b48-d9323f744e2e.PNG)

Here is the session info and output on console in text:

> ">" devtools::session_info()
> Session info -----------------------------------------------------------------------------------------------------------
>  setting  value                       
> version  R version 3.4.3 (2017-11-30)
> system   x86_64, mingw32             
> ui       RStudio (1.1.419)           
> language (EN)                        
> collate  English_United States.1252  
> tz       Europe/Paris                
> date     2018-01-26                  
>
>Packages ---------------------------------------------------------------------------------------------------------------
> package   * version date       source        
> backports   1.1.2   2017-12-13 CRAN (R 3.4.3)
> base      * 3.4.3   2017-12-06 local         
> bookdown    0.6     2018-01-25 CRAN (R 3.4.3)
> compiler    3.4.3   2017-12-06 local         
> datasets  * 3.4.3   2017-12-06 local         
> devtools  * 1.13.4  2017-11-09 CRAN (R 3.4.3)
> digest      0.6.14  2018-01-14 CRAN (R 3.4.3)
> evaluate    0.10.1  2017-06-24 CRAN (R 3.4.3)
> graphics  * 3.4.3   2017-12-06 local         
> grDevices * 3.4.3   2017-12-06 local         
> htmltools   0.3.6   2017-04-28 CRAN (R 3.4.3)
> knitr       1.18    2017-12-27 CRAN (R 3.4.3)
> magrittr    1.5     2014-11-22 CRAN (R 3.4.3)
> memoise     1.1.0   2017-04-21 CRAN (R 3.4.3)
> methods   * 3.4.3   2017-12-06 local         
> Rcpp        0.12.15 2018-01-20 CRAN (R 3.4.3)
> rmarkdown   1.8     2017-11-17 CRAN (R 3.4.3)
> rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.3)
> stats     * 3.4.3   2017-12-06 local         
> stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)
> stringr     1.2.0   2017-02-18 CRAN (R 3.4.3)
> tools       3.4.3   2017-12-06 local         
> utils     * 3.4.3   2017-12-06 local         
> withr       2.1.1   2017-12-19 CRAN (R 3.4.3)
> xfun        0.1     2018-01-22 CRAN (R 3.4.3)
> yaml        2.1.16  2017-12-12 CRAN (R 3.4.3)
>Error in gsub(pattern, val, transformed, ignore.case = TRUE) : 
>  invalid regular expression '\$Sys.setenv(PATH\b', reason 'Missing ')''
> "> "

A directory for the project is created with what looks like all the files from the bookdown template, but no project file, here is the content of the newly created directory:

> xxx@yyyy MINGW64 /c/repos/abc:
> $ ls -l
> total 19
> -rw-r--r-- 1 spi 1049089   96 Jan 26 11:05 _bookdown.yml
> -rw-r--r-- 1 spi 1049089  435 Jan 26 11:05 _output.yml
> -rw-r--r-- 1 spi 1049089 1026 Jan 26 11:05 01-intro.Rmd
> -rw-r--r-- 1 spi 1049089   52 Jan 26 11:05 02-literature.Rmd
> -rw-r--r-- 1 spi 1049089   52 Jan 26 11:05 03-method.Rmd
> -rw-r--r-- 1 spi 1049089  114 Jan 26 11:05 04-application.Rmd
> -rw-r--r-- 1 spi 1049089   45 Jan 26 11:05 05-summary.Rmd
> -rw-r--r-- 1 spi 1049089   55 Jan 26 11:05 06-references.Rmd
> -rw-r--r-- 1 spi 1049089  268 Jan 26 11:05 book.bib
> -rw-r--r-- 1 spi 1049089 1143 Jan 26 11:05 index.Rmd
> -rw-r--r-- 1 spi 1049089   22 Jan 26 11:05 preamble.tex
> -rw-r--r-- 1 spi 1049089  204 Jan 26 11:05 README.md
> -rw-r--r-- 1 spi 1049089  172 Jan 26 11:05 style.css


HTH
Thanks.

**Comment by SynergyLink** [comment]
Same problem here. Did I miss the solution?

**Comment by Courvoisier13** [comment]
any solution for this? i have the same issue

**Comment by yihui** [comment]
@Courvoisier13 If you know enough about debugging, you could `debug(.rs.expandEnvironmentVariables)`, then create a new project, and you might be able to figure out what is wrong in `gsub()`.

You may also provide the output of your `Sys.getenv()` (please exclude any env vars that contain sensitive data, such as secret tokens).

**Comment by Courvoisier13** [comment]
Thanks @yihui. I'll try.

**Comment by yihui** [comment]
Just received another similar report: https://stackoverflow.com/q/52666976/559676 I wonder if @Courvoisier13 had any success in figuring out the cause.

**Comment by kevinushey** [comment]
It would be useful to know the output of `Sys.getenv()` in your case.

**Comment by jmcphers** [comment]
Haven't had any more reports in > 1 year, or environment values to troubleshoot with, so closing. Both RStudio and Bookdown have seen a lot of improvement in the last year, so hopeful that this just isn't a problem any more; please let us know if you see it again!
