### ISSUE TITLE
Problems with Path and German "ü,ä,ö"

### ISSUE THREAD

**Issue by RemyZeno** [rstudio/rstudio#2056]
I'm suffering from an issue, probably related to an incorrect path, resulting from the "ü" in my name. Windows 10 put the "ü" in the folder-Name, but RStudio doesnt seem to cope with this...

► A workaround could be, if it would be possible to just change the AppData-Path to a custom directory.

### System details

    OS Version: Windows 10 x64 Pro
    RStudio Version: 1.1.419
    R Version: 3.4.3

### Steps to reproduce the problem
1. Install R
2. Install R-Studio
3. In R-Studio
3.1. data(cars)
3.2. plot(cars$speed,cars$dist)

### Describe the problem in detail
> plot(cars$speed,cars$dist) 
Error in gzfile(file, "wb") : cannot open the connection In addition: Warning message: In gzfile(file, "wb") :   cannot open compressed file 'C:/Users/Marcel H?nninghaus/AppData/Local/Temp/RtmpS0GHPX/rs-graphics-90327162-46ad-43fb-840e-3e1d4a62bd69/0feb0480-1385-43df-8863-a6c9477924f0.snapshot', probable reason 'Invalid argument' Graphics error: Plot rendering error

### Describe the behavior you expected
I expected a plot.

### Further Information
> Sys.getenv(c("USERPROFILE", "R_USER", "R_LIBS_USER"))
                                              USERPROFILE                                                    R_USER 
                          "C:\\Users\\Marcel Hünninghaus"                   "C:/Users/Marcel Hünninghaus/Documents" 
                                              R_LIBS_USER 
"C:/Users/Marcel Hünninghaus/Documents/R/win-library/3.4" 

Problem seems related to "ü" in Name

### 1. The output of sessionInfo() 
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3 

### 2. The R code in question
See above

### 3. A diagnostics report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1663804/diagnostics-report.txt)

**Comment by ronblum** [comment]
@RemyZeno I tried this out both using RStudio and just in R. I wasn't able to reproduce this, including with creating a Windows user with an identical name ("Marcel Hünninghaus") and locale ("German_Germany.1252"). What happens if you run this in R, outside of RStudio?

**Comment by RemyZeno** [comment]
In R, without R Studio, it works fine. 

There is another mystery... On my second computer (Windows 10 also), with the same user name (resulting from same live-login), I could reproduce the error either, RStudio works there.

Issue seems to stem from RStudio... But only on this mashine.

**Comment by jtiemer** [comment]
I have encountered this behaviour on different computers as well. The systems encompass Windows 7 Pro, Windows 7 Enterprise, Windows 10.
It seems to occur alongside a similar error that happens if you e.g. try to setwd() with the Windows path like this:
setwd("C:\users\username\Desktop\foo\")
It persists even if no Umlaut (äöü) is present in the path, but it vanishes if you just substitute the backslashes for normal forward slashes:
setwd("C:/users/username/Desktop/foo/")

**Comment by jmcphers** [comment]
We don't have a solid repro for this, we haven't had any reports or information in over a year, and we think #5577 is likely to have improved things. Please reopen if you're still having trouble with the daily builds:

https://dailies.rstudio.com/
