### ISSUE TITLE
Request for improved functionality of Editor Tabs.

### ISSUE THREAD

**Issue by woodwards** [rstudio/rstudio#2057]
I love RStudio but one thing I always miss compared with other tabbed software (e.g. Google Chrome, Notepad++) is advanced functionality of the Tabs in the Editor. For example the ability to, e.g., right click on a tab and choose "Close This Tab", "Close All Tabs Except This One", "Close All To the Right", "Close All to the Left", etc

Also, it would be nice to have the tabs the same width, as having different widths makes it harder to close several manually, since you have to keep moving the mouse to find the X. 

Thanks!

**Comment by ronblum** [comment]
@woodwards Thank you for the suggestions! We'll consider these for future releases.

**Comment by kevinushey** [comment]
We're currently tracking this in https://github.com/rstudio/rstudio/issues/1664 -- would you be willing to add a 👍  there so we can track the relative priority of that feature request? Thanks!
