### ISSUE TITLE
Can't start Rstudio after fresh install on RHEL

### ISSUE THREAD

**Issue by TroyHernandez** [rstudio/rstudio#2064]
### System details

    OS Version      : Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
    RStudio Version : rstudio-1.1.419-x86_64.rpm (also rstudio-1.1.414-x86_64.rpm)
    R Version       :  R version 3.4.3 (2017-11-30)

### Steps to reproduce the problem

`wget https://download1.rstudio.org/rstudio-1.1.419-x86_64.rpm`
`sudo yum install rstudio-1.1.419-x86_64.rpm`
> Examining rstudio-1.1.419-x86_64.rpm: rstudio-1.1.419-1.x86_64
> Marking rstudio-1.1.419-x86_64.rpm as an update to rstudio-1.1.414-1.x86_64
> Resolving Dependencies
> --> Running transaction check
> ---> Package rstudio.x86_64 0:1.1.414-1 will be updated
> ---> Package rstudio.x86_64 0:1.1.419-1 will be an update
> --> Finished Dependency Resolution

> Dependencies Resolved

>=========================================================================================================

>  Package             Arch               Version                Repository                           Size

>=========================================================================================================
> Updating:
>  rstudio             x86_64             1.1.419-1              /rstudio-1.1.419-x86_64             410 M

> Transaction Summary
>=========================================================================================================
> Upgrade  1 Package

> Total size: 410 M
> Is this ok [y/d/N]: y
> Downloading packages:
> Running transaction check
> Running transaction test
> Transaction test succeeded
> Running transaction
>   Updating   : rstudio-1.1.419-1.x86_64                                                              1/2 
>   Cleanup    : rstudio-1.1.414-1.x86_64                                                              2/2 
>   Verifying  : rstudio-1.1.419-1.x86_64                                                              1/2 
>   Verifying  : rstudio-1.1.414-1.x86_64                                                              2/2 

> Updated:
>   rstudio.x86_64 0:1.1.419-1                                                                             

> Complete!

`rstudio`

> rstudio: error while loading shared libraries: libgstreamer-0.10.so.0: cannot open shared object file: No such file or directory

`sudo yum install libgstreamer-0.10.so.0`

> Package gstreamer-0.10.36-7.el7.i686 already installed and latest version
> Nothing to do

### Describe the problem in detail

Can't seem to load/install the proper library (libgstreamer) that would enable me to start up rstudio.

### Describe the behavior you expected

I expected Rstudio to start.

**Comment by jmcphers** [comment]
gstreamer is a dependency of QtWebKit, which is the web rendering component that's used to draw much of RStudio's UI. It is very possible that the version of gstreamer provided by Maipo doesn't satisfy the version requirements of QtWebKit. 

To check this you could run `objdump -p` on both the `libgstreamer` library on your system and the `libQtWebKit` library which ships with RStudio (let us know what the output is if you do this).

We're currently working on a release of RStudio (1.2) which does not depend on gstreamer.

**Comment by TroyHernandez** [comment]
I'm not sure what the implications of two gstreamer libs would be:
`ls | grep gstreamer`
gstreamer-0.10
gstreamer-1.0
libgstreamer-0.10.so.0
libgstreamer-0.10.so.0.30.0
libgstreamer-1.0.so.0
libgstreamer-1.0.so.0.1004.0
############################################
`objdump -p libgstreamer-0.10.so.0`

libgstreamer-0.10.so.0:     file format elf32-i386

Program Header:
    LOAD off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**12
         filesz 0x000e41b0 memsz 0x000e41b0 flags r-x
    LOAD off    0x000e4b78 vaddr 0x000e5b78 paddr 0x000e5b78 align 2**12
         filesz 0x00003308 memsz 0x00004034 flags rw-
 DYNAMIC off    0x000e6db8 vaddr 0x000e7db8 paddr 0x000e7db8 align 2**2
         filesz 0x00000128 memsz 0x00000128 flags rw-
    NOTE off    0x00000114 vaddr 0x00000114 paddr 0x00000114 align 2**2
         filesz 0x00000024 memsz 0x00000024 flags r--
EH_FRAME off    0x000c3b8c vaddr 0x000c3b8c paddr 0x000c3b8c align 2**2
         filesz 0x00003bb4 memsz 0x00003bb4 flags r--
   STACK off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**4
         filesz 0x00000000 memsz 0x00000000 flags rw-
   RELRO off    0x000e4b78 vaddr 0x000e5b78 paddr 0x000e5b78 align 2**0
         filesz 0x00002488 memsz 0x00002488 flags r--

Dynamic Section:
  NEEDED               libgobject-2.0.so.0
  NEEDED               libgthread-2.0.so.0
  NEEDED               libgmodule-2.0.so.0
  NEEDED               libglib-2.0.so.0
  NEEDED               libxml2.so.2
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  SONAME               libgstreamer-0.10.so.0
  INIT                 0x00017f4c
  FINI                 0x000a2ec4
  INIT_ARRAY           0x000e5b78
  INIT_ARRAYSZ         0x00000004
  FINI_ARRAY           0x000e5b7c
  FINI_ARRAYSZ         0x00000004
  GNU_HASH             0x00000138
  STRTAB               0x000098b0
  SYMTAB               0x00002940
  STRSZ                0x00009f4e
  SYMENT               0x00000010
  PLTGOT               0x000e8000
  PLTRELSZ             0x00000f58
  PLTREL               0x00000011
  JMPREL               0x00016ff4
  REL                  0x0001472c
  RELSZ                0x000028c8
  RELENT               0x00000008
  VERNEED              0x000145ec
  VERNEEDNUM           0x00000005
  VERSYM               0x000137fe
  RELCOUNT             0x000004d8

Version References:
  required from libm.so.6:
    0x0d696910 0x00 16 GLIBC_2.0
  required from libdl.so.2:
    0x0d696910 0x00 14 GLIBC_2.0
  required from libxml2.so.2:
    0x0f4c8be0 0x00 05 LIBXML2_2.4.30
  required from libc.so.6:
    0x06969195 0x00 15 GLIBC_2.15
    0x09691f73 0x00 13 GLIBC_2.1.3
    0x0d696913 0x00 12 GLIBC_2.3
    0x0d696914 0x00 11 GLIBC_2.4
    0x0d696911 0x00 10 GLIBC_2.1
    0x0d696912 0x00 08 GLIBC_2.2
    0x09691974 0x00 07 GLIBC_2.3.4
    0x06969197 0x00 06 GLIBC_2.17
    0x06969190 0x00 04 GLIBC_2.10
    0x0d696910 0x00 03 GLIBC_2.0
  required from libpthread.so.0:
    0x0d696912 0x00 09 GLIBC_2.2
    0x0d696910 0x00 02 GLIBC_2.0
############################################
`objdump -p rstudio`

rstudio:     file format elf64-x86-64

Program Header:
    PHDR off    0x0000000000000040 vaddr 0x0000000000400040 paddr 0x0000000000400040 align 2**3
         filesz 0x0000000000000230 memsz 0x0000000000000230 flags r-x
  INTERP off    0x0000000000000270 vaddr 0x0000000000400270 paddr 0x0000000000400270 align 2**0
         filesz 0x000000000000001c memsz 0x000000000000001c flags r--
    LOAD off    0x0000000000000000 vaddr 0x0000000000400000 paddr 0x0000000000400000 align 2**21
         filesz 0x000000000044ef1f memsz 0x000000000044ef1f flags r-x
    LOAD off    0x000000000044f430 vaddr 0x0000000000a4f430 paddr 0x0000000000a4f430 align 2**21
         filesz 0x00000000000118f8 memsz 0x00000000000136b8 flags rw-
 DYNAMIC off    0x000000000045d898 vaddr 0x0000000000a5d898 paddr 0x0000000000a5d898 align 2**3
         filesz 0x00000000000003a0 memsz 0x00000000000003a0 flags rw-
    NOTE off    0x000000000000028c vaddr 0x000000000040028c paddr 0x000000000040028c align 2**2
         filesz 0x0000000000000044 memsz 0x0000000000000044 flags r--
     TLS off    0x000000000044f430 vaddr 0x0000000000a4f430 paddr 0x0000000000a4f430 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000008 flags r--
EH_FRAME off    0x00000000003df920 vaddr 0x00000000007df920 paddr 0x00000000007df920 align 2**2
         filesz 0x000000000000a5ac memsz 0x000000000000a5ac flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
   RELRO off    0x000000000044f430 vaddr 0x0000000000a4f430 paddr 0x0000000000a4f430 align 2**0
         filesz 0x0000000000010bd0 memsz 0x0000000000010bd0 flags r--

Dynamic Section:
  NEEDED               libQt5Core.so.5
  NEEDED               libQt5Widgets.so.5
  NEEDED               libQt5Gui.so.5
  NEEDED               libQt5Network.so.5
  NEEDED               libQt5WebChannel.so.5
  NEEDED               libQt5WebKit.so.5
  NEEDED               libQt5WebKitWidgets.so.5
  NEEDED               libQt5PrintSupport.so.5
  NEEDED               libQt5Quick.so.5
  NEEDED               libQt5Positioning.so.5
  NEEDED               libQt5Sensors.so.5
  NEEDED               libQt5Svg.so.5
  NEEDED               libQt5Xml.so.5
  NEEDED               libQt5XmlPatterns.so.5
  NEEDED               libQt5Qml.so.5
  NEEDED               libQt5Sql.so.5
  NEEDED               libQt5OpenGL.so.5
  NEEDED               libQt5DBus.so.5
  NEEDED               libpthread.so.0
  NEEDED               libutil.so.1
  NEEDED               libuuid.so.1
  NEEDED               librt.so.1
  NEEDED               libz.so.1
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  RPATH                $ORIGIN
  INIT                 0x0000000000597440
  FINI                 0x000000000075378c
  INIT_ARRAY           0x0000000000a4f430
  INIT_ARRAYSZ         0x0000000000000250
  FINI_ARRAY           0x0000000000a4f680
  FINI_ARRAYSZ         0x0000000000000008
  GNU_HASH             0x00000000004002d0
  STRTAB               0x0000000000440108
  SYMTAB               0x000000000040da80
  STRSZ                0x000000000014b7e2
  SYMENT               0x0000000000000018
  DEBUG                0x0000000000000000
  PLTGOT               0x0000000000a5dc38
  PLTRELSZ             0x0000000000006240
  PLTREL               0x0000000000000007
  JMPREL               0x0000000000591200
  RELA                 0x000000000058fdf0
  RELASZ               0x0000000000001410
  RELAENT              0x0000000000000018
  BIND_NOW             0x0000000000000000
  FLAGS_1              0x0000000000000001
  VERNEED              0x000000000058fc20
  VERNEEDNUM           0x0000000000000008
  VERSYM               0x000000000058b8ea

Version References:
  required from librt.so.1:
    0x09691a75 0x00 20 GLIBC_2.2.5
  required from libgcc_s.so.1:
    0x0b792650 0x00 19 GCC_3.0
  required from libm.so.6:
    0x09691a75 0x00 18 GLIBC_2.2.5
  required from libpthread.so.0:
    0x09691972 0x00 13 GLIBC_2.3.2
    0x09691a75 0x00 10 GLIBC_2.2.5
  required from libuuid.so.1:
    0x09da27b0 0x00 09 UUID_1.0
  required from libutil.so.1:
    0x09691a75 0x00 08 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696917 0x00 22 GLIBC_2.7
    0x0d696918 0x00 21 GLIBC_2.8
    0x0d696913 0x00 17 GLIBC_2.3
    0x0d696919 0x00 16 GLIBC_2.9
    0x09691974 0x00 14 GLIBC_2.3.4
    0x0d696914 0x00 12 GLIBC_2.4
    0x06969194 0x00 07 GLIBC_2.14
    0x09691a75 0x00 06 GLIBC_2.2.5
    0x09691972 0x00 04 GLIBC_2.3.2
  required from libstdc++.so.6:
    0x0297f861 0x00 15 GLIBCXX_3.4.11
    0x0297f865 0x00 11 GLIBCXX_3.4.15
    0x056bafd3 0x00 05 CXXABI_1.3
    0x02297f89 0x00 03 GLIBCXX_3.4.9
    0x08922974 0x00 02 GLIBCXX_3.4

**Comment by jmcphers** [comment]
You need to `objdump -p` on `libQt5WebKit.so.5` to see its dependencies.

Interesting however is that you have both gstreamer0.1 and gstreamer1.0 installed. We also have a build of RStudio for gstreamer1.0, but unfortunately we only produce a Debian package with it today (for Ubuntu Xenial which *only* ships with gstreamer1.0). If you're feeling ambitious you could extract the files from that package and put them on your system:

https://download1.rstudio.org/rstudio-xenial-1.1.419-amd64.deb

**Comment by TroyHernandez** [comment]
Kind of hit a wall.  What's the wait on a 1.2 release?
I might just use my Rstudio Server install until then.

I tried converting the xenial build using rpm, that gave the following:
`sudo alien --to-rpm --scripts rstudio-xenial-1.1.419-amd64.deb`
`rpm -Uvh rstudio-1.1.419-2.x86_64.rpm `
error: Failed dependencies:
	libedit.so.2()(64bit) is needed by rstudio-1.1.419-2.x86_64
	libstdc++.so.6(CXXABI_1.3.8)(64bit) is needed by rstudio-1.1.419-2.x86_64
	libstdc++.so.6(GLIBCXX_3.4.20)(64bit) is needed by rstudio-1.1.419-2.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by rstudio-1.1.419-2.x86_64

And then here's the libQt5WebKit:

`objdump -p /usr/lib/rstudio/bin/libQt5WebKit.so.5`

/usr/lib/rstudio/bin/libQt5WebKit.so.5:     file format elf64-x86-64

Program Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**21
         filesz 0x00000000021c470c memsz 0x00000000021c470c flags r-x
    LOAD off    0x00000000021c5008 vaddr 0x00000000023c5008 paddr 0x00000000023c5008 align 2**21
         filesz 0x00000000001d97dc memsz 0x00000000002083a0 flags rw-
 DYNAMIC off    0x000000000236ef10 vaddr 0x000000000256ef10 paddr 0x000000000256ef10 align 2**3
         filesz 0x00000000000003a0 memsz 0x00000000000003a0 flags rw-
    NOTE off    0x00000000000001c8 vaddr 0x00000000000001c8 paddr 0x00000000000001c8 align 2**2
         filesz 0x0000000000000024 memsz 0x0000000000000024 flags r--
EH_FRAME off    0x0000000001e3beb8 vaddr 0x0000000001e3beb8 paddr 0x0000000001e3beb8 align 2**2
         filesz 0x0000000000091464 memsz 0x0000000000091464 flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**3
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
   RELRO off    0x00000000021c5008 vaddr 0x00000000023c5008 paddr 0x00000000023c5008 align 2**0
         filesz 0x00000000001aeff8 memsz 0x00000000001aeff8 flags r--

Dynamic Section:
  NEEDED               librt.so.1
  NEEDED               libz.so.1
  NEEDED               libXrender.so.1
  NEEDED               libXcomposite.so.1
  NEEDED               libicui18n.so.53
  NEEDED               libicuuc.so.53
  NEEDED               libX11.so.6
  NEEDED               libxslt.so.1
  NEEDED               libxml2.so.2
  NEEDED               libglib-2.0.so.0
  NEEDED               libgobject-2.0.so.0
  NEEDED               libgstreamer-0.10.so.0
  NEEDED               libgstapp-0.10.so.0
  NEEDED               libgstbase-0.10.so.0
  NEEDED               libgstinterfaces-0.10.so.0
  NEEDED               libgstpbutils-0.10.so.0
  NEEDED               libgstvideo-0.10.so.0
  NEEDED               libQt5Sensors.so.5
  NEEDED               libQt5Core.so.5
  NEEDED               libpthread.so.0
  NEEDED               libQt5Positioning.so.5
  NEEDED               libQt5Quick.so.5
  NEEDED               libQt5Gui.so.5
  NEEDED               libQt5Qml.so.5
  NEEDED               libQt5Network.so.5
  NEEDED               libQt5WebChannel.so.5
  NEEDED               libQt5Sql.so.5
  NEEDED               libGL.so.1
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libc.so.6
  SONAME               libQt5WebKit.so.5
  RPATH                $ORIGIN
  INIT                 0x0000000000480e98
  FINI                 0x0000000001b5c8f8
  INIT_ARRAY           0x00000000023c5008
  INIT_ARRAYSZ         0x0000000000000050
  GNU_HASH             0x00000000000001f0
  STRTAB               0x0000000000027928
  SYMTAB               0x0000000000005830
  STRSZ                0x0000000000037a84
  SYMENT               0x0000000000000018
  PLTGOT               0x0000000002573fe8
  PLTRELSZ             0x000000000000bfb8
  PLTREL               0x0000000000000007
  JMPREL               0x0000000000474ee0
  RELA                 0x00000000000622d8
  RELASZ               0x0000000000412c08
  RELAENT              0x0000000000000018
  VERNEED              0x0000000000062118
  VERNEEDNUM           0x0000000000000008
  VERSYM               0x000000000005f3ac
  RELACOUNT            0x000000000002987a

Version References:
  required from libz.so.1:
    0x0827e5c0 0x00 21 ZLIB_1.2.0
  required from librt.so.1:
    0x09691a75 0x00 19 GLIBC_2.2.5
  required from libxml2.so.2:
    0x08f4cab6 0x00 17 LIBXML2_2.6.6
    0x08f4cab0 0x00 16 LIBXML2_2.6.0
    0x0f4c8be0 0x00 14 LIBXML2_2.4.30
  required from libxslt.so.1:
    0x0f5c4bd4 0x00 18 LIBXML2_1.0.24
    0x08f5c3b9 0x00 11 LIBXML2_1.1.9
    0x0f5c4bd2 0x00 09 LIBXML2_1.0.22
    0x0f5c4bc1 0x00 07 LIBXML2_1.0.11
  required from libstdc++.so.6:
    0x02297f89 0x00 15 GLIBCXX_3.4.9
    0x056bafd3 0x00 13 CXXABI_1.3
    0x0297f865 0x00 08 GLIBCXX_3.4.15
    0x08922974 0x00 05 GLIBCXX_3.4
  required from libm.so.6:
    0x09691a75 0x00 04 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696918 0x00 20 GLIBC_2.8
    0x0d696914 0x00 10 GLIBC_2.4
    0x09691a75 0x00 06 GLIBC_2.2.5
    0x09691974 0x00 03 GLIBC_2.3.4
  required from libpthread.so.0:
    0x09691972 0x00 12 GLIBC_2.3.2
    0x09691a75 0x00 02 GLIBC_2.2.5

**Comment by matt-wirtz** [comment]
Hi,

I ran into the same problem after installing Rstudio 1.1.463-1 on a Suse 15.0 Linux.

I think the problem is dating back quite a while. Rstudio is using its own QtWebKit which requires the libgstreamer-0.10.so.0. But the 0.1 version of libgstreamer has been marked depricated since quite a while and has now been removed completely. Only version 1.0 (1.12) is shipped.

So running Rstudio fails with: 
rstudio: error while loading shared libraries: libgstreamer-0.10.so.0: cannot open shared object file: No such file or directory

Why does R ship with it's own libQt5WebKit.so.5? The system provided version in /usr/lib64 needs libgstreamer-1.0.so.0 which is provided.

Is it possible to change to the system provided version of libgstreamer?

Thx.

**Comment by jmcphers** [comment]
> Rstudio is using its own QtWebKit which requires the libgstreamer-0.10.so.0.

We have RStudio builds that link against gstreamer1.0 (the Debian 9 build does this), but unfortunately we don't currently have them for Suse. You have a couple of options:

1. You can try getting RStudio to use your system copy of Qt, using `LD_LIBRARY_PATH`. As RStudio is linked against (and expects) a specific Qt version, this may lead to problems. 
2. You can try extracting the gstreamer1.0 based version of Qt in the Debian 9 version of RStudio desktop, and replacing it. 
3. You can use our [preview release](https://www.rstudio.com/products/rstudio/download/preview/), which does not require gstreamer at all.

**Comment by TroyHernandez** [comment]
For those struggling with Rstudio on Redhat, I just tried the preview release v1.2.1226-2 as @jmcphers suggested above and it installed and started up without a problem! Other than the font and window being oversized (Ctrl+ - solved this) everything looks to be in working order.

**Comment by TroyHernandez** [comment]
Another update... if there's a better place to put this, let me know.

Rstudio version 1.2.1335 worked intermittently.  Sometimes upon startup, the font and windows are oversized as above.  Ctrl + - doesn't work.  Sometimes it's possible to push alt and use the arrows to navigate.  Other times, any attempt to navigate to the File or View tabs causes Rstudio to crash.  This is one of those times.  Same issue for the preview version 1.2.1555.  When I start Rstudio from the command line this is the output upon crashing... still looks like a Qt issue:
```
[troy@oc3022162214 Downloads]$ rstudio
Received signal 8 FPE_INTDIV 7fbde90249e8
#0 0x7fbded00da4f <unknown>
#1 0x7fbded00de4b <unknown>
#2 0x7fbded00e4ce <unknown>
#3 0x7fbde7b9d5d0 <unknown>
#4 0x7fbde90249e8 qt_fusion_draw_arrow()
#5 0x7fbde902b8b0 QFusionStyle::drawPrimitive()
#6 0x7fbde8ff6f42 QStyleSheetStyle::drawPrimitive()
#7 0x7fbde901e98c QWindowsStyle::drawControl()
#8 0x7fbde9000299 QStyleSheetStyle::drawControl()
#9 0x7fbde90bde65 QMenu::paintEvent()
#10 0x7fbde8f93828 QWidget::event()
#11 0x7fbde90c530b QMenu::event()
#12 0x7fbde8f55b3c QApplicationPrivate::notify_helper()
#13 0x7fbde8f5cd30 QApplication::notify()
#14 0x7fbde801ce28 QCoreApplication::notifyInternal2()
#15 0x7fbde8f8c685 QWidgetPrivate::sendPaintEvent()
#16 0x7fbde8f8cd42 QWidgetPrivate::drawWidget()
#17 0x7fbde8f654e6 QWidgetBackingStore::doSync()
#18 0x7fbde8f65c42 QWidgetBackingStore::sync()
#19 0x7fbde8faf4d2 QWidgetWindow::handleExposeEvent()
#20 0x7fbde8faff4b QWidgetWindow::event()
#21 0x7fbde8f55b3c QApplicationPrivate::notify_helper()
#22 0x7fbde8f5cd30 QApplication::notify()
#23 0x7fbde801ce28 QCoreApplication::notifyInternal2()
#24 0x7fbde86c0b72 QGuiApplicationPrivate::processExposeEvent()
#25 0x7fbde86c0d9d QGuiApplicationPrivate::processWindowSystemEvent()
#26 0x7fbde869c9fb QWindowSystemInterface::sendWindowSystemEvents()
#27 0x7fbdd85d981a xcbSourceDispatch()
#28 0x7fbde2127049 g_main_context_dispatch
#29 0x7fbde21273a8 <unknown>
#30 0x7fbde212745c g_main_context_iteration
#31 0x7fbde80741ef QEventDispatcherGlib::processEvents()
#32 0x7fbde801b78a QEventLoop::exec()
#33 0x7fbde8024190 QCoreApplication::exec()
#34 0x5580875e91d5 main
#35 0x7fbde60ca495 __libc_start_main
#36 0x5580875ec98b <unknown>
  r8: 0000000000000000  r9: 0000000000000040 r10: 0000000000000005 r11: 00007fbde6234d00
 r12: 00007fffa4429420 r13: 00007fffa4428e10 r14: 00007fffa4428e30 r15: 0000000000000004
  di: 000055808e8a13e0  si: 00007fffa4428c50  bp: 00007fffa4428e50  bx: 00007fffa4428de0
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007fffa4428d50
  ip: 00007fbde90249e8 efl: 0000000000010206 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by kevinushey** [comment]
Do you see the same kind of crash with any other kinds of Qt applications on your system?

**Comment by TroyHernandez** [comment]
I'm using Spotify for Linux with no problem.

**Comment by TroyHernandez** [comment]
An update:
I work from home and recently started using my [network of big screens](https://www.amazon.com/dp/B0714N2JFZ/) and wireless keyboards for my work computer.  Yesterday I disconnected my laptop, used it by itself.  This morning I it booted up.   I have it set up to automatically start Firefox, Slack, and Rstudio.  Magically, Rstudio started with no problem! You see where this is going...

I plugged it into my big screen network (using mirrored screens), closed the lid (I have it set to not go to sleep when I close the lid so that I don't have the screen on for nothing), and Rstudio crashes; i.e. the Rstudio/Electron window is still open, but everything inside it is blank/black.  I close the window, open it up... same problem as before (zoomed in with huge font, clicking on File or View causes it to crash).

I've obviously written all this, so you know that I unplugged it, restarted Rstudio with no problem, plugged it back in, and then closed the lid and crashed Rstudio.  When I repeated this with Rstudio started from the command line, this is the message:

`
$ rstudio
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
qt.qpa.xcb: shmget() failed (22: Invalid argument) for size 4494458880
qt.qpa.xcb: QXcbConnection: XCB error: 11 (BadAlloc), sequence: 737, resource id: 450, major code: 53 (CreatePixmap), minor code: 0
`
I'll be leaving my lid up for now :)

**Comment by TroyHernandez** [comment]
I've reproduced the [above behavior](https://github.com/rstudio/rstudio/issues/2064#issuecomment-515702586) with Ubuntu.

**Comment by maurony** [comment]
Hi all,

I have a similar issue on my Ubuntu 19.10 machine; I am not sure if it is related to the OS though, as this is only an issue with my high-resolution monitor. 

Here the steps to reproduce the issue:
1.) install rstudio, e.g. `sudo gdebi ~/Downloads/rstudio-1.2.5033-amd64.deb`
2.) start on lower resolution; in my case 3840 * 1080 --> it works without any issues
3.) switch high resolution (5120 * 1440) --> following error message
```
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
[1:8:0301/151753.717540:FATAL:node_channel.cc(721)] Check failed: message->data_num_bytes() < GetConfiguration().max_message_num_bytes. 
#0 0x7f99195c1a4f <unknown>
#1 0x7f9919539fdc <unknown>
#2 0x7f9918340b1a <unknown>
#3 0x7f9918340f20 <unknown>
#4 0x7f9918345896 <unknown>
#5 0x7f9918345d3f <unknown>
#6 0x7f991a66f69a <unknown>
#7 0x7f991a66f710 <unknown>
#8 0x7f9918342a23 <unknown>
#9 0x7f991833f1ee <unknown>
#10 0x7f9918335c9e <unknown>
#11 0x7f99198400c9 <unknown>
#12 0x7f9918223874 <unknown>
#13 0x7f991a5802c5 <unknown>
#14 0x7f991a20ec12 <unknown>
#15 0x7f991a22b04a <unknown>
#16 0x7f991a22b0a7 <unknown>
#17 0x7f991a1b9f9f <unknown>
#18 0x7f991a1bafaa <unknown>
#19 0x7f991a1bc663 <unknown>
#20 0x7f991a1bcba8 <unknown>
#21 0x7f991a1bd01f <unknown>
#22 0x7f991a0ee683 <unknown>
#23 0x7f991a0ef5f0 <unknown>
#24 0x7f991a57fe98 <unknown>
#25 0x7f991822121a <unknown>
#26 0x7f99198439a9 <unknown>
#27 0x7f99198475dc <unknown>
#28 0x7f991984d1b4 <unknown>
#29 0x7f9919840cc1 <unknown>
#30 0x7f99198410a2 <unknown>
#31 0x7f991985f620 <unknown>
#32 0x7f99195243d7 <unknown>
#33 0x7f9919579656 <unknown>
#34 0x7f99195243d7 <unknown>
#35 0x7f991954acf7 <unknown>
#36 0x7f991954b35d <unknown>
#37 0x7f991954b49c <unknown>
#38 0x7f9919544c7c <unknown>
#39 0x7f991956502f <unknown>
#40 0x7f991959b684 <unknown>
#41 0x7f99195cea10 <unknown>
#42 0x7f991e772669 start_thread
#43 0x7f991583a323 clone

Received signal 6
#0 0x7f99195c1a4f <unknown>
#1 0x7f99195c1e4b <unknown>
#2 0x7f99195c24ce <unknown>
#3 0x7f991e77e540 <unknown>
#4 0x7f991575e3eb gsignal
#5 0x7f991573d899 abort
#6 0x7f99195c1a15 <unknown>
#7 0x7f991953a12f <unknown>
#8 0x7f9918340b1a <unknown>
#9 0x7f9918340f20 <unknown>
#10 0x7f9918345896 <unknown>
#11 0x7f9918345d3f <unknown>
#12 0x7f991a66f69a <unknown>
#13 0x7f991a66f710 <unknown>
#14 0x7f9918342a23 <unknown>
#15 0x7f991833f1ee <unknown>
#16 0x7f9918335c9e <unknown>
#17 0x7f99198400c9 <unknown>
#18 0x7f9918223874 <unknown>
#19 0x7f991a5802c5 <unknown>
#20 0x7f991a20ec12 <unknown>
#21 0x7f991a22b04a <unknown>
#22 0x7f991a22b0a7 <unknown>
#23 0x7f991a1b9f9f <unknown>
#24 0x7f991a1bafaa <unknown>
#25 0x7f991a1bc663 <unknown>
#26 0x7f991a1bcba8 <unknown>
#27 0x7f991a1bd01f <unknown>
#28 0x7f991a0ee683 <unknown>
#29 0x7f991a0ef5f0 <unknown>
#30 0x7f991a57fe98 <unknown>
#31 0x7f991822121a <unknown>
#32 0x7f99198439a9 <unknown>
#33 0x7f99198475dc <unknown>
#34 0x7f991984d1b4 <unknown>
#35 0x7f9919840cc1 <unknown>
#36 0x7f99198410a2 <unknown>
#37 0x7f991985f620 <unknown>
#38 0x7f99195243d7 <unknown>
#39 0x7f9919579656 <unknown>
#40 0x7f99195243d7 <unknown>
#41 0x7f991954acf7 <unknown>
#42 0x7f991954b35d <unknown>
#43 0x7f991954b49c <unknown>
#44 0x7f9919544c7c <unknown>
#45 0x7f991956502f <unknown>
#46 0x7f991959b684 <unknown>
#47 0x7f99195cea10 <unknown>
#48 0x7f991e772669 start_thread
#49 0x7f991583a323 clone
  r8: 0000000000000000  r9: 00007f990e006190 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007f9915c61300 r13: 00007f990e006620 r14: 0000000000000088 r15: 00007f990e006420
  di: 0000000000000002  si: 00007f990e006190  bp: 00007f990e0063e0  bx: 00007f990e009700
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f991575e3eb  sp: 00007f990e006190
  ip: 00007f991575e3eb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```
4.) When I switch back to 3840 * 1080, everything works fine again.

Hope this helps to resolve the issue.

Cheers.

**Comment by jmcphers** [comment]
We just released a new version of RStudio, 1.3.959. It includes a newer Qt which may resolve this issue. Can anyone confirm whether it's still happening in the new release?

**Comment by jmcphers** [comment]
Haven't heard back in a month, closing.

**Comment by Cybergenik** [comment]
I'm still having this issue on Debian 10 with a high resolution display.

System Specs :
```
OS: Debian GNU/Linux 10 (buster) x86_64
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce RTX 2070 Rev. A
Resolution: 5120x1440
```
After installing from https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2021.09.2-382-amd64.deb

When I run rstudio, I just get a white screen and this:
```
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
```

I just need to get it to work, if there's a way I could just change a config file and update the resolution rstudio uses. I'm ok with that, just need to get this working as fast as possible.

**Comment by TroyHernandez** [comment]
I moved to ubuntu budgie for my hi-res machine and have fewer issues.
You can try Rstudio Server if all else fails.
