### ISSUE TITLE
Autocompletion for cross-references when typing \@ref()

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#2065]
This is a feature request that I think would encourage reproducible research. A reproducible example illustrating what this would mean: create a new .Rmd document and paste the text below. Place your cursor between the `s` and the `)` on line 12. Hit tab. Would be great if a list of cross-references (s1 and s2 in this case) popped-up:

```
---
title: "Untitled"
output: bookdown::html_document2
---

## s1

See section \@ref(s)

## s2
```

[Here](https://www.sharelatex.com/blog/2017/06/15/auto-complete-ref-commands.html)'s a gif illustrating the kind of thing I'm after (although I'm more interested in the .md functionality that the .tex functionality): 

![image](https://user-images.githubusercontent.com/1825120/35428840-23e1e5ec-0269-11e8-996f-b7bf0a135e74.png)

Not sure if this is best done in core RStudio (I guess so, already has amazing auto-completion capabilities), as an addin or something else. Vested interest: I want open source software to be more intuitive and faster to use than proprietary software and this feature would make RStudio, used in combination with the `citr` package, a better plain text editor than anything else I know of on the market, without even considering its ability to be used to develop reproducible reports that embed code chunks.

@yihui may be interested in this one. Thanks for opening-up this issue tracker to a deluge from the masses!

**Comment by ronblum** [comment]
Thanks for the suggestion @Robinlovelace and for the comments!

**Comment by kevinushey** [comment]
Where exactly would we draw the completion candidates from? (What are all the possible things that `\ref{}` could point to?)

**Comment by Robinlovelace** [comment]
Good question. The things commonly referenced when writing .Rmd are figures, tables and section headings. These are well described here: https://bookdown.org/yihui/bookdown/cross-references.html

The main ones I use are:

- Section headings. `# Section heading` would be a completion candidate `section-heading`.
- Section headings with manually-set IDs. `# Section heading {#h1}` would be `h1`.
- Figures. `{r fig1, fig.caption="..."} would be `fig:fig1`.
- Tables. The chunk name of chunks containing calls to `kable()` with a caption.

From the previous link it seems there is support for equations and theorems also. Not sure if **bookdown** support cross-referencing specific code chunks, would be great it it did.

That is not a comprehensive or systematic list. **bookdown** developers and especially Yihui are better qualified than me to provide that and feedback about implementation. But happy to help test stuff and provide more input and ideas. Many thanks for taking an interest in this feature request in any case and hope that helps put something together (imagine overriding the normal behaviour of tab in prose could be tricky in itself though, thinking about it).

**Comment by yihui** [comment]
I certainly agree that this will be a very useful feature, but it will be quite tricky to implement. It is tricky because it is hard to know all possible completion candidates without actually rendering the book. The best way to go, as I can imagine, is that I generate a file that contains the completion candidates when rendering the book in **bookdown**, and RStudio can read this file for autocompletion.

**Comment by Robinlovelace** [comment]
Still think this would be useful. Thanks @stalebot for the nudge!

**Comment by yihui** [comment]
@Robinlovelace This has been implemented in RStudio's visual Markdown editor: https://rstudio.github.io/visual-markdown-editing/#/technical?id=cross-references Not sure if you are happy with using the visual editor, though.

**Comment by Robinlovelace** [comment]
> Not sure if you are happy with using the visual editor, though.

That is really great to see @yihui, many thanks! That is more than good enough for me, the fact it's demonstrated with Geocomputation with R as an example is a bonus. You guys rock :guitar: :rocket:

**Comment by Robinlovelace** [comment]
Belated confirmation, great to see this working.

![image](https://user-images.githubusercontent.com/1825120/130323492-a07458cf-b976-4f47-956f-9900b87df888.png)
