### ISSUE TITLE
Emacs keybindings aren't working as expected

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2071]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.419
    OS Version      : Windows 10 x64
    R Version       : 3.4.3

### Steps to reproduce the problem

Enable Emacs keybindings, and attempt to perform 'kill' or 'yank' commands, e.g.

- <kbd>C-k</kbd> to kill a line,
- <kbd>C-y</kbd> to yank the last kill,
- <kbd>C-Space</kbd> and <kbd>C-w</kbd> to mark a region and kill that region.

The commands do not operate as expected. Strangely, pressing <kbd>C-c</kbd> as a prefix enables these commands, e.g. <kbd>C-c C-k</kbd> and <kbd>C-c C-y</kbd> will successfully kill and then yank a line.

The issue appears to occur on Windows only. This appears to be a regression from v1.0.

**Comment by kevinushey** [comment]
Interestingly, I see the same issue in the RStudio v1.2 branch on macOS.

**Comment by plantarum** [comment]
This isn't strictly a Windows issue: I'm seeing a similar problem on Linux. C-k works, killing to end of line, but the text that is killed isn't available for yanking. C-y inserts a few blank lines, not the text killed by the previous C-k. C-c C-k and C-c C-y do appear to work, with the first killing and the second yanking.

RStudio Version 1.1.383

**Comment by adam-przepiorkowski** [comment]
As far as I can see, this is still an unsolved issue – it's a pity, as experienced Emacs users have C-k, C-y, etc., ingrained deep into their muscle memory, and it is not easy to remember to have to do C-c C-k, C-c C-y, etc., instead.
