### ISSUE TITLE
Request for possibility to remove templates from project wizard.

### ISSUE THREAD

**Issue by JoFAM** [rstudio/rstudio#2073]
Thank you for giving us the possibility to provide extra templates for projects. However, when adding a few project templates of my own, the list in the wizard is very quickly becoming very large. I would like to see a simple way to remove unused templates from the wizard. 

More noteably: all the package templates with Rcpp-related packages are very useful for R/C++ developers. None of my students is, and most will never be. So these templates clog the wizard and I would like to at least have the option to remove those. That way I don't have to scroll down every time I need another template. 

Screenshot : 

![rstudioprojectwizard](https://user-images.githubusercontent.com/809906/35474470-f37958e6-038e-11e8-812d-69dcc7b2d9be.png)

**Comment by jmcphers** [comment]
I don't know if we will support removing, but it might make more sense to sort installed templates over built-in Rcpp templates (as the former you've opted into in some way)

**Comment by JoFAM** [comment]
@jmcphers thanks for still considering this.
