### ISSUE TITLE
Column height wrong when columns do not have names

### ISSUE THREAD

**Issue by aalqasem** [rstudio/rstudio#2074]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.419
    OS Version      : macOS High Sierra (10.13.3)
    R Version       : 3.4.3

### Steps to reproduce the problem
it happens with any data frame that has column(s) name empty. There is no issue if the column name(s) is identified.

<img width="194" alt="screen shot 2018-01-27 at 8 07 10 pm" src="https://user-images.githubusercontent.com/32421036/35477944-ba11c1ba-039d-11e8-9189-b3cfc3c03338.png">

### Describe the problem in detail
If the column name is empty, the hight of the column name is reduced to less than the half which is look weird, as shown in the picture below !

<img width="204" alt="screen shot 2018-01-27 at 8 05 58 pm" src="https://user-images.githubusercontent.com/32421036/35477939-91062a7c-039d-11e8-97fc-76c50b8c9a35.png">

Best ,,

**Comment by kevinushey** [comment]
Reproducible example:

```R
m <- matrix(1:16, nrow = 4)
View(m)
```

Normally, one cannot create a `data.frame` without names, but it looks like we do when generating one from e.g. a matrix.

**Comment by adamconroy** [comment]
This no longer occurs as we now assign default column names if they are empty (as far as I can tell from the reprex).
