### ISSUE TITLE
Custom project template always creates git repo when starting from another git repo.

### ISSUE THREAD

**Issue by JoFAM** [rstudio/rstudio#2075]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.419
    OS Version      : Windows 10
    R Version       : 3.4.3

#### A. in New Project, on by default.
- enable git in Global options
- Open a project that is git enabled (i.e. has a git repo to it)
- Choose File > New Project > New Directory > New Project

#### B. Use your own template
- enable git in Global options
- create a project template (I have one here : https://github.com/JoFAM/daprojects )
- Open a project that has a git repo enabled
- Choose File > New Project > New Directory > Basic Project for Data Analysis
- Fill in directory and select "open in new session"
- Create Project

### Describe the problem in detail

A. The option "create git repository" is selected by default. I would like to be able to have it NOT selected by default.

B. The new project is always created as a git repo. I need to be able to prevent that from happening, but I can't see how.

### Describe the behavior you expected

I expected these options to be turned off by default. 

I attached a diagnostics report so you can check whether I have overlooked an option somewhere.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1671007/diagnostics-report.txt)

**Comment by JoFAM** [comment]
I've updated the reproduction as it turns out this only occurs when a git-enabled project is open.

Testing done by Christophe Dervieux : https://community.rstudio.com/t/turn-off-automatic-git-repo-creation-when-using-your-own-project-template/4584

**Comment by hadley** [comment]
I think this was fixed in #2072

**Comment by JoFAM** [comment]
@hadley Is there a dev build where I can test it already? Then I can see if I can confirm this as fixed.

**Comment by kevinushey** [comment]
Daily builds are available at https://dailies.rstudio.com.
