### ISSUE TITLE
If project doesn't use git, keyboard shortcut adds newline

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2077]
1. Create new project that doesn't use git
1. Open source pane
1. Press Cmd + Alt + M

A newline is added to the source pane

**Comment by kevinushey** [comment]
I can reproduce this with Ctrl+Alt+M, but not with Cmd+Alt+M. I see the same behavior in Safari, and also in other applications (e.g. Notes.app). I suspect there's something OS-specific going on that controls what Ctrl+Alt+M does.

FWIW this bug (feature?) is no longer present in RStudio v1.2.

**Comment by ronblum** [comment]
Confirmed that the newline with Ctrl-Alt-M is an issue in 1.1 but fixed in 1.2.
