### ISSUE TITLE
Not able to start RStudio, The error occurred while parsing the regular expression fragment

### ISSUE THREAD

**Issue by ZHANGneuro** [rstudio/rstudio#2079]
### System details

    RStudio Edition : 
    RStudio Version : RStudio-1.1.419
    OS Version     high sierra 10.13.2
    R Version     R version 3.4.3

### Steps to reproduce the problem & Describe the problem in detail

when I installed and clicked the Rstudio icon, Rstudio gives a blank window and a dialog box saying below:

"Unexpected exception: Invalid preceding regular expression prior to repetition operator.  The error occurred while parsing the regular expression fragment: '(^|:)**>>>HERE>>> python mo'."   

it just does not work at all.  I firstly try to search from internet with no helps. 

Thank you for taking the time to file an issue!  -->

**Comment by kevinushey** [comment]
What is the `PATH` on your system? That is, if you launch a plain R session from the terminal (outside of RStudio), what do you see in `Sys.getenv("PATH")`?

**Comment by kevinushey** [comment]
Also, what is the output of

    cat /etc/paths

**Comment by kevinushey** [comment]
![screen shot 2018-01-29 at 8 45 13 am](https://user-images.githubusercontent.com/1976582/35522284-c00b490e-04d0-11e8-969a-41c1c5a95f9e.png)

**Comment by ZHANGneuro** [comment]
Thanks for your reply, p

This is the output of Sys.getenv("PATH") in R
![snip20180130_2](https://user-images.githubusercontent.com/5019040/35549602-4a801f4c-05c1-11e8-80a8-2055b4859808.png)
![snip20180130_3](https://user-images.githubusercontent.com/5019040/35549606-4ced88dc-05c1-11e8-99cb-bf6bec1af928.png)


> Sys.getenv("PATH")
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
> 


This is the output of cat /etc/paths:

bos-MacBook:Applications boo$ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
bos-MacBook:Applications boo$

**Comment by ZHANGneuro** [comment]
I solved the problem!

The problem happens because that I installed a software named AFNI, which created a file named out.afni_system_check.txt in the path /etc/paths.d, removing this file solving the problem.
