### ISSUE TITLE
Surround selection with quotes

### ISSUE THREAD

**Issue by msrodrigues** [rstudio/rstudio#2081]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.419
    OS Version      : Mac OSx High Sierra
    R Version       : R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"

### Steps to reproduce the problem
Select text, type " (shift + ') and the text select wont be surrounded by ""

### Describe the problem in detail
I think it is important to mention that I revised RStudio > Preferences > Code and the option Surround selection on text insertion is set to "Quotes and brackets", also when I select some text and type shift+9 it does what I expected: (some text)

### Describe the behavior you expected
I expected the text that I have selected would be surrounded by ""

**Comment by kevinushey** [comment]
I wasn't able to reproduce this issue. Can you provide some more information? Can you reproduce this in all file types (`.R` vs. other types), or only certain ones?

**Comment by msrodrigues** [comment]
I have tried in different file types, same issue. Also found someone that seems to have the same issue, reported [here](https://support.rstudio.com/hc/en-us/community/posts/115009228428-Problem-with-Surround-selection-on-text-insertion-).

**Comment by kevinushey** [comment]
What keycode is reported when you press the <kbd>'</kbd> key on your keyboard? (try checking at http://keycode.info/). For me, I see 222. I wonder if your case is different or if you're using an international keyboard?

**Comment by msrodrigues** [comment]
Yes, I am using US - International PC, but I checked and the keycode is the same as yours (222). Also 222 when I hit shift+'. Isn't it suppose to be a different code?

**Comment by kevinushey** [comment]
The same keycode should be shown even when holding Shift; however, the key event received by the browser will also contain information about the modifier keys being held down. (The website in question doesn't show that, which can be a bit confusing)

That all said, I can reproduce this issue when using the U.S. International - PC keyboard layout. From what I can tell, with this layout, insertion of <kbd>"</kbd> is reserved by the operating system for the insertion of diacritics, and this behavior confuses our editor. I'm not sure if there's a simple way around this :-/

**Comment by ncasiraghi** [comment]
I am experiencing exactly the same issue. are there any updates about this?
