### ISSUE TITLE
Make it clear to not edit generated files

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2082]
e.g.

```R
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/complete.R
```

```cpp
// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
```

It would be great if the IDE exposed this very clearly so you don't accidentally edit generated files

**Comment by kevinushey** [comment]
What if the user really, truly does want to edit one of these files?

**Comment by jjallaire** [comment]
We could just use our standard warning band treatment here (and not actually make it impossible to edit the file)

**Comment by jmcphers** [comment]
Ideally I think we'd do the following:

1. Make the editor read-only

2. Show a warning bar over the top of the editor that says something like. "This file is generated and should not be edited hand.", with an action button on the right that says "Edit Anyway"

3. Clicking Edit Anyway removes the warning bar and enables the editor

That way you have to acknowledge the warning before editing, so it's very hard to change anything accidentally, but you still have an escape hatch if you really need to make a change.

**Comment by hadley** [comment]
I was thinking mostly of a warning bar, but @jmcphers' suggestion sounds perfect.

**Comment by jmcphers** [comment]
@kevinushey added a warning bar in #2085.

**Comment by ronblum** [comment]
Verified in 1.2.349.
