### ISSUE TITLE
Bug in code diagnostics:  false "defined but not used" report

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#2087]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      :  MacOS 10.13.2 
    R Version       : 3.4.3

### Steps to reproduce the problem

If I put the code below in a file in a package and run Code Diagnostics, I get told that 

    Line 14    no symbol named 'result' in scope
    Line 7  'i' is defined but not used

I don't see the same message if it's in a file that's not in a package.  It happens both for "Show Diagnostics" and "Show Diagnostics (Project)"

### Describe the problem in detail

Here's the content of the file:

```

f <- function() {
    ret <- function(time) {
    	data <- 1
    	data[i]
    }
    i <- 1
    ret
}

g <- function() {
  h <- function() {

    result <<- result + 1
  }
  result <- 0
  h()
  result
}

```

This is simplified from the report about the `animate.R` and `asy.R` files in the `rgl` package.

### Describe the behavior you expected

Since `i` is used in the function being returned by `f()`, it shouldn't be flagged as unused.

Since `result` is defined in the parent function `g()`, it shouldn't be flagged as not in scope in `h()`.

**Comment by kevinushey** [comment]
Thanks for the bug report! I think this bug report uncovers a few limitations of RStudio's diagnostic system.

Firstly, the diagnostics system parses code from start to end in a single pass, so every time a symbol is encountered, the diagnostics system asks whether it knows of a symbol in scope. This implies that e.g.

```R
g <- function() { print(i) }
i <- 1
g()
```

will (incorrectly) produce a diagnostic warning, while

```R
i <- 1
g <- function() { print(i) }
g()
```

will (correctly) not produce any diagnostic.

Secondly, it looks like RStudio gets confused by some variable names (e.g. `data`). This is odd, but note that:

```R
f <- function() {
    i <- 1
    function(time) { data[i] }
}
```

erroneously produces a diagnostic that `i` is not defined, but

```R
f <- function() {
    i <- 1
    function(time) { letters[i] }
}
```

These are definitely bugs but fortunately they do have workarounds. We'll try to take a closer look at these!

**Comment by dmurdoch** [comment]
Regarding the single pass issue, this function also triggers a false positive "no symbol named 'i' in scope", for pretty much the same reason as my `g()` example:

```
library(rlang)
k <- function() {
  q <- quo(i)
  i <- 10
  eval_tidy(q)
}
```

I'm just posting it here because if you fix one, it probably won't be hard to fix the other:  `quo()` is reasonably well-behaved in its non-standardness.
