### ISSUE TITLE
Windows 10: Markdown documents are slow to edit

### ISSUE THREAD

**Issue by Anastaziel** [rstudio/rstudio#2091]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio Desktop 1.1.419 Stable and RStudio-1.2.240.exe daily build
    OS Version      : Windows 10 Home
    R Version       : 3.4.3

### Steps to reproduce the problem
A new markdown document with as little as 10 lines in a chunk.

### Describe the problem in detail
Editing of any sort is sluggish.

### Edit
Actually, I just installed the latest daily build: 1.2.309 and there appears to be no lag. If in the next hour the lag does not come I will close the issue (but still it is there for the stable version).

**Comment by majorgreys** [comment]
This has long been a problem for me on Windows. I don't experience the same lag as badly on Linux.

**Comment by kevinushey** [comment]
We're actively working on improving rendering performance in the v1.2 builds of RStudio (but these won't become part of the v1.1 builds).

**Comment by Anastaziel** [comment]
My lag is gone with the 1.2.309. Completely. Try that build on Windows.

**Comment by dfalty** [comment]
It's good to see the latest build fixes the lag for you! Closing this out.

**Comment by majorgreys** [comment]
1.2.309 helped. Unfortunatelty the editor still has a good bit of lag for me, even with just an R script. Scrolling or even typing causes the Rstudio process to spike up to 30% of my cpu. The same is true on Linux (though I'm only trying it with 1.1).
Can someone point me to why v1.2 improves rendering or why this is a challenge for how Rstudio's editor is written?
