### ISSUE TITLE
Help pane rendering has changed in v1.2

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2092]
Left side is v1.2, right side is v1.1. Note that the fonts + font sizes appear to have changed.

<img width="1440" alt="screen shot 2018-01-30 at 2 14 07 pm" src="https://user-images.githubusercontent.com/1976582/35594441-0f766332-05c8-11e8-8018-46ebc16a702d.png">

Maybe we need to tweak a few things in `R.css`?

**Comment by jmcphers** [comment]
Fixed to the extent that we wanted to, e.g. https://github.com/rstudio/rstudio/commit/5da64832143ece212dafc91cffa85074b0845290.
