### ISSUE TITLE
random rendering glitch on macOS

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2093]
Saw this funky rendering glitch when using RStudio v1.2.245:

<img width="477" alt="screen shot 2018-01-30 at 6 33 04 pm" src="https://user-images.githubusercontent.com/1976582/35602386-e1e76806-05ec-11e8-90a9-ad9786a1f726.png">

Wasn't able to reproduce in v1.2.315 but going to keep this open in case anyone else bumps into rendering issues with the daily builds of RStudio on macOS.

**Comment by kevinushey** [comment]
More glitches. This occurred after stepping over a line in the debugger.

![screen shot 2018-03-02 at 1 55 21 pm](https://user-images.githubusercontent.com/1976582/36923902-972209d2-1e21-11e8-95ca-27f9c81ddac6.png)
![screen shot 2018-03-02 at 1 55 14 pm](https://user-images.githubusercontent.com/1976582/36923903-97391b9a-1e21-11e8-9f4d-6c1f2f0696d0.png)

The glitch went away after I resized the window.

**Comment by kevinushey** [comment]
And more.

<img width="684" alt="screen shot 2018-03-14 at 4 08 14 pm" src="https://user-images.githubusercontent.com/1976582/37435775-fcd0aafc-27a1-11e8-954d-fd78cf06a1af.png">

@jmcphers did you by any chance stumble upon a `--avoid-glitchy-rendering` Chromium flag while you were fixing the scrollbar bug? 😬

**Comment by jmcphers** [comment]
Are you using a dev build with the latest master? There's some chance that the flag we added (which reduces use of the compositor to draw layers) might improve this behavior.

**Comment by kevinushey** [comment]
I am in this case, unfortunately.

**Comment by jmcphers** [comment]
Shoot. Well, here's [all the flags](https://peter.sh/experiments/chromium-command-line-switches/). Maybe try with `--disable-gpu` as a first volley to see if this is related to hardware vs. software rendering?
