### ISSUE TITLE
RStudio doesn't highlight all instances of strings containing dots

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#2094]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Preview 1.1.421
    OS Version      : Windows 10 Pro
    R Version       : 3.4.3

### Steps to reproduce the problem
```
var.with.dot <- rnorm(10)
var.with.dot

var_without_dot <- rnorm(10)
var_without_dot
```

### Describe the problem in detail

Select `var.with.dot` (or double click), RStudio doesn't highlight all instances of that string 

![capture](https://user-images.githubusercontent.com/6590141/35604307-85e69edc-05f6-11e8-807b-6291db1dcf1d.PNG)

### Describe the behavior you expected

Highlight all instances of selected string e.g.  `var_without_dot`

**Comment by jmcphers** [comment]
This has [always been a bug in RStudio](https://support.rstudio.com/hc/en-us/community/posts/200634308-Variable-name-with-dot-notation-is-not-highlighted-in-the-rest-of-the-document), but now it does work correctly in the [Ace Kitchen Sink](https://ace.c9.io/build/kitchen-sink.html), in R mode:

![image](https://user-images.githubusercontent.com/470418/35651318-1aab6c6c-0694-11e8-9423-8edc6f2f33b5.png)

so probably is the result an upstream bugfix we haven't picked up yet.

**Comment by rbbernardino** [comment]
Hope you pick the bugfix... it's pretty annoying... Any news about this?
