### ISSUE TITLE
Session First Project Template broken by same-named folder

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#2095]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.383
    OS Version      :  Multiple... repros on Ubuntu 16.04 and Debian (rocker)
    R Version       : 3.4.2

### Steps to reproduce the problem

Use the following `Dockerfile`
```
FROM rocker/rstudio

# create project directory
RUN mkdir /tmp/testproj && \
	echo "one" >> /tmp/testproj/one.txt && \
	echo "two" >> /tmp/testproj/two.txt && \
	echo "Version: 1.0\nDefaultOpenDocs: one.txt:two.txt" >> /tmp/testproj/testproj.Rproj 

# this seems to break the functionality
RUN mkdir /tmp/testproj/testproj 

# set default
RUN echo "session-first-project-template-path=/tmp/testproj" >> /etc/rstudio/rsession.conf
```

Then execute
```bash
docker build --tag=proj_template .
docker run -d --rm -p 8787:8787 --name=run-proj-template proj_template
```

Then go to a browser (`localhost:8787` in this case, if testing on a desktop) and login to RStudio Server with user `rstudio:rstudio`

### Describe the problem in detail
The project does not open when the project has a folder in it with the same name as the parent folder / `.Rproj` file.  I expect that this is a rare occurrence, but did confuse me when it inadvertently happened.  

The project gets copied as expected, but does not get opened.

While thinking about this, perhaps it is worth thinking about whether *any* .Rproj file will do (or if the project template requires the same name as the parent folder, which is documented and seems to currently be the case).  I presume there is a reason for this restriction.

### Describe the behavior you expected

Expected the project template to be copied to the user's home folder and then opened.  The project was copied but not opened.

**Comment by kfeinauer** [comment]
@colearendt Just tested locally and with the given Dockerfile and everything works as expected. I believe what may have happened is you ran the template on the first time which opened successfully, then added the directory and tried to reopen. The second time around, the documents will not open automatically because this only occurs on the *very first time* that the user opens a project. After that, it is up to the recent files logic within the IDE itself to determine what files (if any) to open.

**Comment by kfeinauer** [comment]
Closing for now. @colearendt let me know if I am maybe missing something, but if you try this from a clean slate with a brand new image it should work fine.

**Comment by colearendt** [comment]
Thanks, @kfeinauer!  Not reproing for me either!
