### ISSUE TITLE
Feature Request: File type column

### ISSUE THREAD

**Issue by rsangole** [rstudio/rstudio#2099]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.364
    OS Version      : Sierra, 10.12.6
    R Version       : 3.4.0

### Feature request

Would it be possible to get a 'File Type' column in the Files tab? Very frequently, I'll have to deal with folders which hold  .R, .RData, .Rmd, .py files etc along with a large number of folders as well. It would really help if 'File Type' was an option for display & sorting so similar file types group together.

**Comment by gtritchie** [comment]
You can sort by file type, but it is hard to discover. Click on the little heading square above the icon column and it will sort by type. Click again to sort in the other order.

<img width="421" alt="2020-02-28_10-16-22" src="https://user-images.githubusercontent.com/10569626/75574844-de610480-5a13-11ea-8e88-11d13098d9d2.png">
