### ISSUE TITLE
terminal extremely laggy

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#2100]
I'm on Windows 10 x64,  RStudio 1.1.419

A good way to reproduce this is to SSH to your favorite Linux server and type ``htop``

**Comment by gtritchie** [comment]
Thanks for the report. The terminal on Windows RStudio is generally less responsive than on the other platforms, unfortunately. Hoping to make improvements in RStudio 1.2.

With the terminal running, could you do Tools->Terminal->Terminal Diagnostics and copy/paste the results here? That can be helpful for me in diagnosing what you might be seeing.

**Comment by kendonB** [comment]
```
Global Terminal Information
---------------------------
Loaded TerminalSessions: 1
Handle: 'DB2E51A1' Caption: 'Terminal 1'

Terminal List Count: 1
Handle: 'DB2E51A1' Caption: 'Terminal 1' Session Created: true

Current Terminal Session Information
------------------------------------
Caption:     'Terminal 1'
Title:       'mytitle'
Cols x Rows  '120 x 26'
Shell:       'Git Bash'
Handle:      'DB2E51A1'
Sequence:    '1'
Restarted:   'true
Busy:        'false'
Exit Code:   'null'
Full screen: 'client=false/server=false'
Zombie:      'false'
Track Env    'false'
Local-echo:  'false'
Working Dir: 'Default'
Interactive: 'Always'
WebSockets:  'true'
Typing lag:  '86ms'

System Information
------------------
Desktop:    'true'
Platform:   'Windows'

Connection Information
----------------------
2018/2/1 15:23:20: Connect WebSocket: 'ws://127.0.0.1:6309/terminal/DB2E51A1/'
2018/2/1 15:23:20: WebSocket connected

Local-echo Match Failures
-------------------------
<Not applicable>
```

**Comment by gtritchie** [comment]
Note to self: this will be a good case to benchmark after doing #1923. The newer xterm does much smarter redraw, and the terminal on Windows is essentially a screen-scraper (via WinPty) due to lack of pseudoterminal support on Windows.

**Comment by kendonB** [comment]
I have updated to today's daily and I no longer see the lags. It is a big change! Thanks!

**Comment by kendonB** [comment]
Input is still a bit laggy but retrieving the output from the terminal is very smooth.

**Comment by gtritchie** [comment]
Great! Should be some more improvements coming in 1.2 that will hopefully help with the laggy typing, too.

**Comment by carlosmag** [comment]
I have been experiencing similar issues in RStudio Desktop 1.3.959 but not in v1.2.5033.
Scrolling speed improves when disabling hardware acceleration in Global options -> Terminal, but it is not as fluid as in v1.2.5033.

**Comment by mjsteinbaugh** [comment]
I'm running into this issue as well with RStudio 1.4.1717 on macOS. Typing in the terminal is too laggy and results in typos.
