### ISSUE TITLE
"Export.." option in Files pane fails if file is over 4 GB

### ISSUE THREAD

**Issue by pyltime** [rstudio/rstudio#2103]
### System details

    RStudio Edition : RStudio Server
    RStudio Version :  1.1.419

### Steps to reproduce the problem

1. Create a file that's over 4 GB in size on RStudio Server
2. Attempt to download the file to your local system using the "Export" button in the file pane

### Describe the problem in detail

The file fails to download - in some cases, it gives a "End of file" error, in other cases it just creates a 0 B file.
The button does work with a smaller file.

This was reported by a customer in ticket 25333; it was tested and reproduced by @kevinushey

**Comment by benjoaquin** [comment]
For whatever it is worth, we saw this issue with files as small as 387.5 MB.

**Comment by iamkbpark** [comment]
I had the same issue. I need to Export 7.5g and 5.2g file to download but it keeps throwing "End of File". Is there any workaround to download to PC?

**Comment by kfeinauer** [comment]
This should be fixed in a82e3ea.

**Comment by ronblum** [comment]
Confirmed with files of multiple size, as high as 5GB.

**Comment by jmcphers** [comment]
Nice work, this deserves an entry in NEWS! (I've just added one.)
