### ISSUE TITLE
Error showing mathematical equations

### ISSUE THREAD

**Issue by calote** [rstudio/rstudio#2104]
**Error showing mathematical equations in RStudio v1.2.318**

![rstudio_errormaths_f20180201](https://user-images.githubusercontent.com/4060891/35698722-3660e2d4-078e-11e8-9cbb-771f1854b3c7.png)

**Comment by kevinushey** [comment]
Thanks for the bug report -- however, I wasn't able to reproduce on my macOS 10.13.2 machine.

<img width="302" alt="screen shot 2018-02-01 at 1 55 19 pm" src="https://user-images.githubusercontent.com/1976582/35705582-bb668a10-0757-11e8-9429-41501c9df6a3.png">


Can you provide any other context?

For testing:

````R
---
title: "R Notebook"
output: html_notebook
---

$$
f(x) = \frac{x^2}{3} + \int_0^x t^2 \ dt
$$
````

**Comment by calote** [comment]
My macOS 10.13.3 machine. Use RStudio v.1.2.319. The error occurs in RStudio v.1.2.319

![rstudio_errormaths_f20180201_03](https://user-images.githubusercontent.com/4060891/35707685-0969878c-07ab-11e8-9d1f-e5fd6afef912.png)

**Comment by ronblum** [comment]
I am unable to reproduce this on 10.13.3, either (with RStudio 1.2.331).

**Comment by calote** [comment]
The bug is still happening in the RStudio-1.2.359 version.
I have recorded a video in which it is seen how the error occurs with the version RStudio-1.2.359 and nevertheless it does not occur in the version RStudio-1.2.239.
The link to the video "RStudio_no_show_mathematical.mp4" (49.4MB) is as follows:

https://almadestio.us.es/share.cgi?ssid=04T2dU3 <https://almadestio.us.es/share.cgi?ssid=04T2dU3>

Sorry for the inconvenience and thank you very much for the great job you are doing with RStudio.

Pedro Luis Luque
calvo@us.es <mailto:calvo@us.es>
