### ISSUE TITLE
Make the window name for popout windows the file name not the working directory

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#2106]
I find that switching windows when I have a lot of popout windows is quite difficult on Windows 10. The Alt-Tab functionality does show the window label, which is currently the working directory. It would be more useful if this was the file name.

Hth

**Comment by jmcphers** [comment]
Do you typically only have one file open in each popout window?

**Comment by kendonB** [comment]
Yes. I didn't know you could have more than one!

**Comment by jmcphers** [comment]
We're now tracking this in https://github.com/rstudio/rstudio/issues/2427.
