### ISSUE TITLE
Files panel does not sort folders with the "Modified" field. 

### ISSUE THREAD

**Issue by dataRangler** [rstudio/rstudio#2113]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : 1.1.419
    OS Version      : Windows 7
    R Version       : 3.4.3

### Describe the problem in detail
Go to any folder on the "File" panel/Tab.  Only the files have modified time listed.   Sorting by "Modified" field only applies to files.  The sub-folders are not sorted.

### Describe the behavior you expected

Treat the folders the same as files --- display the modified time and allow sorting.

**Comment by ronblum** [comment]
@dataRangler Thanks raising this! We will take this into consideration with ongoing development.
