### ISSUE TITLE
file.edit() fails to open certain unrecognized filetypes

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2114]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.419
    OS Version      : macOS 10.13.2
    R Version       : 3.4.3

### Steps to reproduce the problem

Try to execute `file.edit("hello.ini")`.

### Describe the problem in detail

No file is opened.

### Describe the behavior you expected

The file should be opened in the IDE.

**Comment by kevinushey** [comment]
Fixed with https://github.com/rstudio/rstudio/commit/43df72c778fc861d3daa2672787c63d73b582487. This should also ensure that text files for which we haven't recorded a mime type, but do have a system-reported text mimetype, are openable in the future.

**Comment by ronblum** [comment]
Verified in 1.2.349.
