### ISSUE TITLE
Increase font size in popup help page

### ISSUE THREAD

**Issue by lcamus** [rstudio/rstudio#2118]
Hi,

When I open help pages in a new window, there's no feature to increase the font size. Should it be possible to implement it, since the content of the help page could be very tiny?

Actually I'm working in a multidisplays configuration but with different screen resolution (because different monitors, 27" and 17"): the higher for RStudio code and the  lower for RStudio help page.
Unfortunately it seems the help page displayed in the lower screen resolution inherits from the higher resolution of the other screen, giving a very tiny size as a result.
So to be able to increase the size font would be very useful.

Thank you.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 10
    R Version       : 3.4.3

### Steps to reproduce the problem
- open RStudio and display the IDE in a main monitor
- open a help page
- click on Show in a new window icon
- move the resulting window in a second monitor with a lower resolution than the main one

### Describe the problem in detail
Help page window opened in the second monitor display a content according to the resolution of the main monitor, giving tiny (or very tiny) font size as a result.

### Describe the behavior you expected
To be able to increase the font size.

**Comment by lcamus** [comment]
See also https://support.rstudio.com/hc/en-us/community/posts/202635586-How-to-increase-font-size-in-Help-window-

**Comment by ronblum** [comment]
@lcamus Thank you for the suggestion—this could be a useful feature, and we'll consider it for future releases.

**Comment by beibeijiang** [comment]
I have the same request. Too small to read on the second screen.

**Comment by blueskypie** [comment]
same request as well

**Comment by MichaelChirico** [comment]
👍  Big ups to this. I'm leaning in quite close to my monitor switching between the size 18 display font of my code & the comparatively tiny text in the documentation. Bad for my eyes 😅

**Comment by BruceChen2017** [comment]
In order to increase font size of help panel, you can open `rstudio\resources\R.css`, then change font size of body. It works fine in my _WIN10_ computer with single screen.

**Comment by MichaelChirico** [comment]
@BruceChen2017 cool! would make a neat RStudio extension in the interim, to just have a mini gui to edit that from within RStudio

**Comment by indynagpal** [comment]
It'd be great to have this feature. I have recently started using a 27 4k monitor and the help text is really small. It'd be great to have the ability to specify it in preferences.

Increasing magnification for the whole application is less than ideal.

**Comment by mckf111** [comment]
Before the Rstudioers implement a good solution, I found this solution works for me:
[How do I increase font size in RStudio Help pane?](https://stackoverflow.com/a/47834800/7927463)

**Comment by HFDave** [comment]
Any news on this?

Thanks for the link, mckf111. Unfortunately, it looks like I have to modify a system wide config file to change this on Linux as there is no user version of R.css.
