### ISSUE TITLE
repeated attempts to increase font size can lead to 'unsaved changed' popup

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2120]
To reproduce:

1. Zoom in the IDE (using e.g. <kbd>⌘-+</kbd>),
2. Once the IDE comes in, attempt to zoom again.

If you zoom quickly enough, you should see a pop-up dialog:

<img width="439" alt="screen shot 2018-02-03 at 9 38 09 am" src="https://user-images.githubusercontent.com/1976582/35769830-09bfea7a-08c6-11e8-81cb-007207c48b6c.png">

You'll see the same effect if you edit a document, and then very quickly attempt to zoom the IDE. Rather than showing this dialog, we should just perform an eager autosave and then honor the user's request.

(reported by @wch)

**Comment by kevinushey** [comment]
This issue should now be resolved -- we now avoid forcing an IDE reload when zooming, as Chromium allows us to do this across operating systems.

**Comment by ronblum** [comment]
Verified in 1.2.342.
