### ISSUE TITLE
"Actual Size" zoom option missing on macOS

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2122]
With RStudio v1.1, it's possible to set an 'actual size' zoom level with <kbd>Cmd+0</kbd>. This is now missing in the v1.2 branch.

In addition, performing a zoom forces a full reload of the RStudio UI; we should see if we can get by without performing a full reload with QtWebEngine.

**Comment by kevinushey** [comment]
Now implemented across all Qt platforms (and we now support zooming without reloading the whole UI on all systems)

**Comment by ronblum** [comment]
Verified in 1.2.331.
