### ISSUE TITLE
allow for non-range numeric filter in data viewer?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2124]
Some users have requested that we make it possible to filter a numeric column based on a value (or set of values) rather than using a range-based filter. It's possible to filter a numeric column based on a single value, but it is somewhat clunky.

<img width="237" alt="screen shot 2018-02-03 at 1 40 46 pm" src="https://user-images.githubusercontent.com/1976582/35771836-e20fc64a-08e7-11e8-8bc0-0714b27bb8e6.png">

(This is helpful for cases where a numeric column represents a discrete, often integer, set of values -- e.g. a database key, or a numeric ID, or something similar)

The space for this kind of UI is quite limited though, so it's difficult to figure where we could fit the UI for toggling this behavior.

**Comment by jmcphers** [comment]
Implemented in #2230.

**Comment by dfalty** [comment]
Verified on version 1.2.1090.
