### ISSUE TITLE
Zooming while certain panes focused (e.g. History) causes double/triple zoom

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2126]
To reproduce, with RStudio v1.2 series on macOS:

1. Open the History tab,
2. Click an entry in the History tab,
3. Zoom in using `Cmd-+`.

The IDE will zoom a few extra factors (rather than just one).

**Comment by ronblum** [comment]
This is fixed for the History tab, but still occurs for other tabs, e.g. Environment, Connections, and Help.

**Comment by kevinushey** [comment]
@ronblum I think this one should be fixed in the latest daily builds (there was an associated Qt bug that was fixed in Qt 5.11.1: https://bugreports.qt.io/browse/QTBUG-66207?jql=text%20~%20%22webengine%20zoom%22).

Are you still able to reproduce in the latest dailies?

**Comment by ronblum** [comment]
Confirmed, using an eyeball test with the source pane as the control, and checking the zoom level under Global Options -> Appearance.
