### ISSUE TITLE
Error on F1 over non-function entry in autocomplete list

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#2127]
### System details

    RStudio Edition : both Desktop and Server
    RStudio Version : 1.1.393 - 1.2.319
    OS Version      :  macOS High Sierra, Ubuntu 16.04
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Type `Math` and triggers the autocomplete list
2. On `Math` or `Math2`, or any other non-function entry, press F1 to view their documentation
3. An error occurs on the console, `Error in find.package(if (is.null(package)) loadedNamespaces() else package,  : there is no package called ‘package:methods’`

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be fixed in the latest daily builds; please re-open if you're still seeing some issues.

**Comment by ronblum** [comment]
Verified in 1.2.331.
