### ISSUE TITLE
RStudio Server Pro: Request option to open Rproj file in a new session

### ISSUE THREAD

**Issue by harrismcgehee** [rstudio/rstudio#2128]
When you open a `Rproj` project file from within the RStudio Server Pro environment from within an existing project, you are asked if you want to open the project, but you aren't asked if you want to open it in a new session.

![2018-02-01_18-19-29](https://user-images.githubusercontent.com/9814456/35774446-b657afee-093d-11e8-88b2-66902eca62bb.png)

In the Desktop IDE, these projects are automatically opened in a new session; it'd be nice to have the option to do the same thing in Server. This "open in new session" option has been integrated seemingly everywhere else in the server IDE.

![image](https://user-images.githubusercontent.com/9814456/35774455-1c671e32-093e-11e8-84d8-accf9c11b22c.png)

### System details

    RStudio Edition : Server
    RStudio Version : 1.1.353
    OS Version      :  RHEL 7

### Steps to reproduce the problem

- Open a Project. 
- Navigate in the files pane to another project file.
- Click on it. 
- It asks to open the project, but not if you want to open in a new session.

**Comment by jmcphers** [comment]
Thanks for the suggestion! I've moved it over to the RStudio Pro repo issue tracker.
