### ISSUE TITLE
Addins search should also filter by package

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2130]
For example, if I search for `blogdown`, that should display all addins that are part of the `blogdown` package.

We might want to allow something like `<package>:<addin>` for users looking for addins provided by a particular package.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/c4d2e0eb6b296a4ba65fc01cdaa53cd1d602bcc7

**Comment by ronblum** [comment]
Confirmed in 1.2.342.
