### ISSUE TITLE
Latest daily basically unusable on my Windows 10 laptop

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#2131]
The behavior I see is that RStudio will start off quite well-behaved for a few minutes. I will then notice the typing lag progressively increase to the point where RStudio becomes unusable after around 10 minutes.

I'm not using the most sluggish laptop in the world and I recently reinstalled Windows, though there may be something specific about my system. I have:

RStudio 1.2.324, Windows 10, i7 6700HQ, 32GB RAM, a PCI SSD for the main drive and a 500GB SSD where the project I'm working from lives.

I don't see such sluggish behavior using other apps. I have closed all other resource consuming apps and I still find RStudio input sluggish and eventually crawling to an effective halt.

**Comment by kevinushey** [comment]
Can you provide us with some more information?

- Do you see this in all RStudio projects, or only certain ones?
- Do you only see this when editing certain file types, or all kinds of files?
- What actions are you taking in the IDE? Can you correlate any of them with the slowness you're seeing?
- Are you using a high DPI display?
- Does turning off RStudio's diagnostics make a difference?

Any more specific information that you can provide will be immensely helpful.

**Comment by kendonB** [comment]
I'm currently only working on one project, so can't yet comment on that point.

I am editing .R files only.

I am typing in the editor and running commands using Ctrl-Enter. Nothing else.

I am using two monitors but only one with RStudio - they're both 1080p.

Trying to turn off diagnostics now and I will report back.

**Comment by kendonB** [comment]
There is still a healthy lag after turning off diagnostics. I'll see if it gets to the point where it becomes unusable.

**Comment by kendonB** [comment]
I am also generating plots in the RStudio plots pane.

**Comment by kendonB** [comment]
The only correlate with slowness is time spent in the IDE.

**Comment by kendonB** [comment]
Also could be related to browsing code using RStudio's tools.

**Comment by kendonB** [comment]
OK I've been using RStudio for 20 minutes since turning off diagnostics and that seemed to help. I still experience a substantial typing lag. Much more than I'm used to with RStudio.

I also closed a bunch of open .R tabs which may have helped.

**Comment by kevinushey** [comment]
Does the amount of console output make a difference? Does clearing the console output with <kbd>Ctrl + L</kbd> help?

**Comment by kmader** [comment]
Also experiencing this problem on a surface book (+ Are you using a high DPI display?), it crashes and locks up extremely often on windows. Should I remove everything and start fresh?

**Comment by kendonB** [comment]
Apologies for not replying to this sooner. Clearing the console does help. The problem was likely my machine which was stuck at a CPU clock speed of 0.8Ghz. I haven't extensively tested since I got the CPU back to full speed but I haven't experienced lags yet. I'm going to close this now. @kmader, I suggest you open a new issue with your more specific symptoms (mine wasn't crashing, just crawling and I was using a 24 inch 1080p display).
