### ISSUE TITLE
Command + Return shortcut does not work on RSP & desktop

### ISSUE THREAD

**Issue by hdykiel** [rstudio/rstudio#2132]
### System details

    RStudio Edition : Desktop (and server)
    RStudio Version : 1.1.383
    OS Version      : Mac "Darwin 17.3.0" (High Sierra)
    R Version       : "R version 3.4.2 (2017-09-28)"

### Steps to reproduce the problem
I have not been able to reproduce this problem on a different computer, it started as soon as I took my new mac out of the box.

### Describe the problem in detail
Keyboard shortcut command + return does not execute line of code and jump to next one. This occurs on both desktop IDE & RSP. Control + return works. 

### Describe the behavior you expected
RStudio executes line and jumps to next one.

**Comment by kevinushey** [comment]
Is it possible that the operating system already has a different key combination bound to Cmd + Enter? (Does that shortcut work in other applications?)

Or, have you modified keyboard shortcuts such that Cmd + Enter is no longer bound for execution in RStudio?

**Comment by ronblum** [comment]
Note: I'm running 

> RStudio Edition : Desktop 
> RStudio Version : 1.1.383
> OS Version      : Mac "Darwin 17.2.0" (High Sierra ,10.13.1)
> R Version       : "R version 3.4.3 (2017-11-30)"

and not getting this issue.

**Comment by jmcphers** [comment]
We haven't been able to reproduce this in two weeks or so. @hdykiel let us know if you still see it!

**Comment by hdykiel** [comment]
@jmcphers after several months of having to exclusively use Control + Return, the problem fixed itself and Command + Return now works in both RSP and the desktop IDE. I suspect an apple update resolved the issue.
