### ISSUE TITLE
Ensure RStudio handles multi-monitor, multi-DPI displays well

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2135]
Items we should verify and implement as needed (across all of Windows, Linux, macOS):

- [x] Ensure RStudio scales correctly for both regular DPI displays, high DPI displays (Windows, Linux, macOS)
- [x] RStudio should re-scale according to the display DPI when the monitor resolution is changed, or if e.g. it is dragged from a low-DPI display to a high-DPI display (and vice versa)

**Comment by kevinushey** [comment]
Evidently, a large number of users will use both a scaled laptop screen with an unscaled desktop monitor:

https://community.rstudio.com/t/rstudio-v1-2-has-problem-with-dpi-in-high-resolution-monitor/9354/10

(I've seen other community posts but haven't yet dug them up)

So this is a configuration that warrants some explicit testing.

**Comment by kevinushey** [comment]
It sounds like mixed-DPI and mixed-scale configurations are common enough that we're going to have to invest some time in properly handling this (need to adapt DPI scaling based on the screen RStudio is being shown on)

**Comment by kevinushey** [comment]
Thus far, it seems like RStudio does adapt to the DPI used based on the screen it's displayed on fairly well. The primary issues seen be users are in configurations where the display size differs greatly between displays; this is most common for users who plug their laptop into a large external display while also using the laptop's builtin display.

**Comment by jmcphers** [comment]
I don't think there's any more work we plan to do on this for 1.2 (@kevinushey please reopen/comment if there is!)

**Comment by bri-b-king** [comment]
I'm not sure if this will be helpful, but I figured out a solution that works for me with the scaling issue that I posted in reply to another thread: https://github.com/rstudio/rstudio/issues/2872#issuecomment-461118957

**Comment by maxim-h** [comment]
Also adding a [link](https://github.com/rstudio/rstudio/issues/2872#issuecomment-815752195) to my comment for a Linux solution.
Just in case anyone has the same problem
