### ISSUE TITLE
Connection tab refresh is incorrectly displaying all DBs as objects of the refreshed DB

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2136]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.419
    OS Version      : Ubuntu 16.04 (as an example)
    R Version       : 3.4.2

### Steps to reproduce the problem

Provided by customer in issue 25347 (revised):

- Create a connection.
- Click on the connection in the Connections pane.
- Expand one of the databases, e.g. airontime.
--> You will see objects/tables under it, e.g. dbo, test, etc. 
- Refresh the list using the refresh button.
--> You will see all of the databases—e.g. airontime, finance, etc.—under the refreshed DB (airontime).
- Collapse the DB (airontime) and uncollapse it
--> Now the proper values show up again, e.g. dbo, test, etc.

### Describe the problem in detail

In the connections pane, the refresh button is misbehaving for database connections. When a database is opened to reveal its contents (objects/tables), and the refresh button is clicked, the display doesn't get refreshed with the DB's objects. Instead, all the DB names show up underneath the refreshed DB's name, as if they were objects in the DB—including the DB itself. The DB's objects themselves are missing.

The workaround is to collapse the DB and uncollapse/reopen it. 

### Describe the behavior you expected

When the refresh button is clicked, (only) the list of objects/tables in the DB should be refreshed and displayed. 

Expected result:
<img width="651" alt="connection_refresh_expected" src="https://user-images.githubusercontent.com/31009952/35823492-93e5e8f4-0a64-11e8-80f5-0888c495af4f.png">

Actual result:
<img width="650" alt="connection_refresh_actual" src="https://user-images.githubusercontent.com/31009952/35823493-94023db0-0a64-11e8-9ec7-a22bd485ec15.png">

**Comment by saurfang** [comment]
This bug still exists in build 1.2.1312. Here is a minimal reproducible code:

```r
observer <- getOption("connectionObserver")
observer$connectionOpened(
  # connection type
  type = "fake",
  # name displayed in connection pane
  displayName = "fake",
  # host key
  host = "localhost",
  # connection code
  connectCode = "",
  # disconnection code
  disconnect = function() {
    observer$connectionClosed(type = "fake", host = "localhost")
  },
  listObjectTypes = function() {
    list(
      schema = list(contains = list(
        table = list(contains = "data")
      ))
    )
  },
  # table enumeration code
  listObjects = function(schema = NULL, ...) {
    message(deparse(match.call(expand.dots = TRUE)))
    
    if (is.null(schema)) {
      data.frame(
        name = c("schema1", "schema2"),
        type = "schema",
        stringsAsFactors = FALSE
      )
    } else {
      data.frame(
        name = c("table1", "table2"),
        type = "table",
        stringsAsFactors = FALSE
      )
    }
  },
  # column enumeration code
  listColumns = function(table) {
  },
  # table preview code
  previewObject = function(rowLimit, table) {
  },
  # raw connection object
  connectionObject = NULL
)
```
