### ISSUE TITLE
Attempts to quit while secondary window is open (e.g. zoomed plot) fail

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2137]
To reproduce:

1. Produce a plot with e.g. `plot(1)`,
2. Zoom the plot generated in the plots pane,
3. Attempt to quit the IDE with `Cmd + Q`.

The main window is closed, but the plot window persists and the application does not shut down.

**Comment by kevinushey** [comment]
The problem is this code path:

https://github.com/rstudio/rstudio/blob/691dfb9c087e863d342f16a13bf4bc5fa752e00a/src/cpp/desktop/DesktopMainWindow.cpp#L255-L261

While the main window does close, it seems like child windows are not also closed as a result of the close request. We could perhaps just force a quit with `QApplication::quit()`, or see if there's perhaps a Qt widget attribute we're missing that tells child windows to quite when the parent is closed.

**Comment by gtritchie** [comment]
Quits fine with other satellite windows I've tried (source editor, git). Are they closed programmatically somewhere, or do they have an attribute that is missing on plot window?

**Comment by gtritchie** [comment]
Hmm, getting this in the console when I ran the issue's scenario:

QObject::connect: No such slot rstudio::desktop::BrowserWindow::onCloseRequested() in /Users/gary/rstudio/rstudio/src/cpp/desktop/DesktopGwtCallback.cpp:639

**Comment by gtritchie** [comment]
When I close the zoomed plot window via the red-X button on Mac, with debug build, I see this application output (but the window does close):

`"Uncaught SyntaxError: Unexpected token )"`

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
