### ISSUE TITLE
R Studio Unusably Slow With Too Many Objects Displayed In Environment

### ISSUE THREAD

**Issue by spennihana** [rstudio/rstudio#2138]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 1.0.153
    OS Version      :  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko)
    R Version       : R version 3.4.3 (2017-11-30)

### Steps to reproduce the problem
for(i in 1:18000) { assign(paste0("x", i), i, .GlobalEnv)}
for(i in 1:18000) { assign(paste0("x", i), function(p) p, .GlobalEnv)}

### Describe the problem in detail
The environment pane displays way too many objects by default. Even just having 18K items in the namespace will make RStudio grind to a halt. Note that plane old R terminal is fine with many objects.

### Describe the behavior you expected

Possible solutions:
1. Don't display all objects, but make pages for >1000 items in an environment.
2. A button to disable environment pane completely
3. An option to limit the number of items displayed in the environment.

**Comment by ronblum** [comment]
@spennihana I was able to reproduce this, and I agree that the IDE slowing down this way is frustrating. Thank you for the suggestions for possible solutions—we'll consider them for future releases.

For what it's worth, although this doesn't solve the problem, the slowdown goes away after a few minutes and work can proceed normally. Also, you might consider upgrading to the latest release. Although it doesn't address the issue you've raised, there are new features and bug fixes you may be interested in.
* Current release: https://www.rstudio.com/products/rstudio/download/
* Imminent preview release: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by spennihana** [comment]
thanks!! I am also able to work around the issue now by hiding all of the objects in a different environment. :)
