### ISSUE TITLE
Shading of NA value in RMarkdown Preview In-line output

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#2140]
### System details

    RStudio Edition : Desktop + Server
    RStudio Version : 1.2.140
    OS Version : macOS High Sierra + Ubuntu 14.04 LTS
    R Version: 3.4.3

### Steps to reproduce the problem

Run:

```r
twtr_stock_prices = data.frame(
  time     = as.POSIXct(c("09:30 AM", NA, "09:50 AM", "10:00 AM"), format = "%I:%M %p"),
  price    = c(22.40, 22.38, 22.46, NA),
  tests = factor(c("a", NA, "b", "c"))
)

twtr_stock_prices
```

### Describe the problem in detail

Values for `NA` in time formats are not lightly shaded in the RMarkdown preview in-line output. Instead, they retain `<NA>`, which is default by _R_. This is unlike other augmented data output, e.g. `factor`, which does not retain the `<NA>` tag, but follows the more traditional output... 

See:

![screen shot 2018-02-05 at 5 38 36 pm](https://user-images.githubusercontent.com/833642/35834450-748fe7d4-0a9b-11e8-97ab-a033b5def50d.png)

### Describe the behavior you expected

The values should be lightly shaded as `NA` with `<>` removed. In a way similar to a factor statement.

**Comment by ronblum** [comment]
@coatless Thank you for the report. Added note: lightly shaded _NA_ is also used for logical and ordinal variables.
