### ISSUE TITLE
Viewer does not work properly with .deb v1.1.419

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#2143]
See https://github.com/yihui/xaringan/issues/108

When dynamically pulling the engine behind `xaringan` (`remark.js`) from the web and rendering it in the Viewer pane, the output is not valid (see the referenced issue for screenshots).

```r
---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
date: "2016/12/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# some text
```

However, when using a local copy of  [remark.js](https://remarkjs.com/downloads/remark-latest.min.js) everything is fine:

```r
---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
date: "2016/12/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    chakra: "remark.js"
---

# some text

```

This only applies to the RStudio browser and not to the system-default browser.

**Comment by kevinushey** [comment]
Do you see the same issue in the latest daily build of RStudio? (https://dailies.rstudio.com)

**Comment by pat-s** [comment]
Yes, same across v1.1.383, v1.1.421, v1.2.243

**Comment by N0rbert** [comment]
Confirmed on v1.1.414, v1.1.423.
But seems to fixed in [v1.2.350](https://s3.amazonaws.com/rstudio-ide-build/desktop/trusty/amd64/rstudio-1.2.350-amd64.deb).

**Comment by pat-s** [comment]
the general .deb version is not installable on 17.10 due to dependency issues - waiting for the xenial version which is not yet built for v1.2.350.

But sounds good!

**Comment by pat-s** [comment]
Confirm that it works in >= v1.2.350
