### ISSUE TITLE
Word page position lost after knit on MacOS

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2145]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.315
    OS Version      : macOS 10.13.3
    R Version       : 3.4.2

### Steps to reproduce the problem

1. Knit a longer R Markdown document to Word
2. In Word, scroll to a page other than the first
3. Knit the document again

### Describe the problem in detail

Your place in the document is lost when the freshly knit copy is opened.

### Describe the behavior you expected

The position should be restored after the document is reopened. The code that does this on macOS lived here:

https://github.com/rstudio/rstudio/blob/b4973a964c4b4482ae7e03b1be3c5c4c4eb51b45/src/cpp/desktop-mac/GwtCallbacks.mm#L431-L497

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
