### ISSUE TITLE
Symlink target, rather than symlink name, shown in files pane

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2147]
This appears to be a regression in the v1.2 branch.

<img width="623" alt="screen shot 2018-02-06 at 10 27 57 am" src="https://user-images.githubusercontent.com/1976582/35876843-70d00b78-0b28-11e8-8a16-cda10b66de63.png">

On the filesystem, we have a symlink called `symlink` pointing at `file`, but in the Files pane we see two instances of `file`.

Originally reported by @eddelbuettel.

**Comment by ronblum** [comment]
Looks like it's still an issue.

File system (via terminal): 
<img width="349" alt="issue_2147_terminal" src="https://user-images.githubusercontent.com/31009952/36212455-02233060-1172-11e8-9b4c-a336c001efdc.png">

RStudio files pane:
<img width="498" alt="issue_2147_filespane" src="https://user-images.githubusercontent.com/31009952/36212478-0dfd3610-1172-11e8-985b-97cd838225fd.png">

**Comment by kevinushey** [comment]
This _should_ be fixed in the latest daily builds. What system + RStudio version are you still seeing this on?

**Comment by eddelbuettel** [comment]
Confirming the fix for 1.2.344 -- where 1.2.342 appeared still affected by it.

Thanks for fixing it :1st_place_medal:

**Comment by ronblum** [comment]
Confirmed in 1.2.344.
