### ISSUE TITLE
Resize of IDE window is ugly, laggy

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2150]
Another issue in the pile for QtWebEngine on macOS...

Resizing of the IDE is quite laggy, and leaves ugly white boxes in the new space waiting to be drawn.

![laggy-resize](https://user-images.githubusercontent.com/1976582/35893768-5d844d18-0b64-11e8-9cdf-048ea7a98dc6.gif)

This is with a small IDE window, but the effect is more dramatic with a larger surface.

**Comment by kevinushey** [comment]
Looks like the issue is reported upstream at https://bugreports.qt.io/browse/QTBUG-58324.

**Comment by jmcphers** [comment]
This is not great, but we've observed the same behavior in Electron apps (for example on my machine Slack exhibits the same issue) so it is not super likely that we will be able to fix it on our end. Moving out of 1.2 for now.

**Comment by kevinushey** [comment]
One thing we could do that would at least make it less ugly -- I wonder if we can draw with a 'default' background, so at least the unfilled space gets the background color of the theme (ie, dark blue in this case)?

**Comment by jmcphers** [comment]
Yes, that'd be worth doing as a stopgap if it's straightforward!

**Comment by javierluraschi** [comment]
Somewhat related, I've seen this happening in chrome with very simple use cases that perform resizing based on javascript, not CSS. In my repro, I was working on `htmlwidgets` and a simple one that tries to sync a div size with it's parent using javascript, also shows this behavior:

![resize-js-chrome](https://user-images.githubusercontent.com/3478847/39098193-ee366444-461b-11e8-82c2-c178d60628a8.gif)

The `htmlwidget` code looks something like:

```js
HTMLWidgets.widget({

  name: 'sizingfill',

  type: 'output',

  factory: function(el, width, height) {

    // TODO: define shared variables for this instance
    
    var root = document.createElement("div");
    root.style.width = width + "px";
    root.style.height = height + "px";
    root.style.background = "steelblue";
    el.appendChild(root);

    return {

      renderValue: function(x) {

        // TODO: code to render the widget, e.g.
        root.innerText = x.message;
      },

      resize: function(width, height) {

        // TODO: code to re-render the widget with a new size
        root.style.width = width + "px";
        root.style.height = height + "px";
        root.style.background = "orange";
      }

    };
  }
});
```

```r
  # create widget
  htmlwidgets::createWidget(
    name = 'sizingfill',
    x,
    width = width,
    height = height,
    package = 'sizingfill',
    elementId = elementId,
    sizingPolicy = htmlwidgets::sizingPolicy(viewer.fill = TRUE, browser.fill = TRUE)
  )
```

**Comment by gtritchie** [comment]
Still happens with Qt 5.11.1 (not that we were expecting it to stop happening, but wanted to check).

**Comment by kevinushey** [comment]
Given that this appears to be an issue that affects other applications using Chromium / Electron, we might want to just punt on this one. One change I made that minimizes the jankiness is we now set the Qt widget background color to match the theme's background color, so the visual effect seen in resizing is a lot less jarring.

**Comment by gtritchie** [comment]
I agree, let's punt. Marking as external and closing.
