### ISSUE TITLE
Support git pull --rebase in git pane

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2151]
This is the primary reason I use git in the console (maybe as a dropdown button under pull?). It probably shouldn't be too obvious, as it is for more advanced users because it is more likely to get you into a state you can't easily back out of.

**Comment by kevinushey** [comment]
Maybe as a small dropdown menu (triggered by an inconspicuous down arrow) next to the Pull button?

**Comment by hadley** [comment]
Sounds perfect
