### ISSUE TITLE
Add 'all' to output format options for R markdown documents

### ISSUE THREAD

**Issue by 0tertra** [rstudio/rstudio#2152]
rendering multiple outputs that are defined in the header is already possible with
`render("file.Rmd", output_format = "all")`
see [rmarkdown/issues/25](https://github.com/rstudio/rmarkdown/issues/25)

it would be nice if this functionality would be available from within the IDE 
e.g. 'all' in the list for output formats in  R Markdown Document Options
![image](https://user-images.githubusercontent.com/2414512/35929360-9e52e716-0c2f-11e8-9e2b-fa16026f6488.png)

**Comment by jmcphers** [comment]
This dialog edits the YAML metadata (i.e. it makes changes which are persisted inside the document). If we did this we'd probably add it to the Knit menu instead, i.e.

     Knit
     ----
     Knit to HTML
     Knit to Word
     ---
     Knit All

Does that sound like it'd do what you want?

**Comment by 0tertra** [comment]
Changing the dialog can be used to add the formats 
but the rendering part would indeed make more sense in the Knit menu.
so yes, this sounds like it would do what I want.
