### ISSUE TITLE
debug assertion on Windows when sourcing C++ file

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2154]
<img width="1440" alt="screen shot 2018-02-07 at 10 24 06 am" src="https://user-images.githubusercontent.com/1976582/35934021-34f68702-0bf1-11e8-8ef6-e722ef7021d6.png">

MSVC is very strict about creating pointers to unallocated memory in debug mode so we should see if there's something genuine we need to tweak here.

**Comment by jmcphers** [comment]
@jcheng5 has started seeing this pattern flagged at compile time on newer versions of Fedora, so we may need to fix it just to compile at some point in the future.

**Comment by wch** [comment]
We've actually seen it happen only at runtime. There's a minimal example here: https://github.com/rstudio/httpuv/issues/133#issuecomment-387499519

**Comment by kevinushey** [comment]
Dang. It's a bit surprising to me since C++ typically allows one-past-the-end pointers, and one might extrapolate that to mean a pointer to the start of an empty vector would be permitted... but evidently not!

**Comment by jcheng5** [comment]
@kevinushey For what it's worth, I don't believe it's the `&` that's the problem, but the `[0]`--so it'd be retrieving a value past the end of the vector that would need to be permitted.

This code trips the assertion:

```cpp
#define _GLIBCXX_ASSERTIONS
#include <vector>

int main() {
  std::vector<char> buf;
  buf[0];
  return 0;
}
```

**Comment by kevinushey** [comment]
You're right. Perhaps using `buf.data()` is the right way to go here? (C++11 and above, but since we compile with that enabled that should be safe)

http://en.cppreference.com/w/cpp/container/vector/data
