### ISSUE TITLE
Functionality issue with connecting to GIT remote repository

### ISSUE THREAD

**Issue by gsubin** [rstudio/rstudio#2157]
1.	When I Click on Push or Pull button from RStudio IDE it opens up a window Git Push or Git Pull and the Popup window shows a title as Password and the field is to enter the username. And the username field is masked.
 
 
•	Is it possible to change the Title of the Window to Connecting to Git Repository instead of Password?
•	Is there any reason why the username is masked?
 
•	What is the option to show the user name in clear text instead of showing it as masked?

**Comment by ronblum** [comment]
@gsubin Thank you for raising this issue—I will mark it as a bug for review.

**Comment by hathawayj** [comment]
This semester something has changed in R-Studio or GitHub to make the username and password dialogue pop up every time we push.  It doesn't do it on everyone's machine but on many.  **Has there been a change in how you interact with remote repositories that would require typing in usernames and passwords every time we sync?**

**Comment by kevinushey** [comment]
@hathawayj you might find http://happygitwithr.com/credential-caching.html helpful. RStudio hasn't changed anything in particular here, but you might need to make sure Git is using `https://` for communication with the git remote.

**Comment by jmcphers** [comment]
This was fixed in https://github.com/rstudio/rstudio/pull/5721.
