### ISSUE TITLE
Unable to terminate active sessions in Rstudio server pro. 

### ISSUE THREAD

**Issue by mikkelbisgaard** [rstudio/rstudio#2160]
### System details

    RStudio Edition : Server Pro
    RStudio Version :  1.1.423-amd64
    OS Version      : Ubuntu 16.04
    R Version       : 3.4.3

### Steps to reproduce the problem
Terminate running session from Dashbord

### Describe the problem in detail
We have a couple of ubuntu servers, AD joined with PBIS, which runs RStudio Server (Pro license)
However we are unable to terminate other users sessions because since our users are presented as <<DOMAIN>>\<<USERNAME>> ie: USR\user 
So when RStudio tries to kill the session it throws the following error in the application logs:

08 Feb 2018 12:28:17 [rserver-admin] ERROR system error 2 (No such file or directory) **[path=/tmp/rstudio-rsession/ITSmbi-ds]**; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::childrenRecursive(rstudio::core::FilePath::RecursiveIterationFunction) const /home/ubuntu/rstudio-pro/src/cpp/core/FilePath.cpp:1025; LOGGED FROM: rstudio::core::r_util::SessionContext rstudio::session::sessionContextForPid(const string&, const string&) /home/ubuntu/rstudio-pro/src/cpp/session/include/session/SessionPidToContext.hpp:151

pay attention to the "path=/tmp/rstudio-rsession/ITSmbi-ds" it's not found on the server because our \ in the ITS\mbi is never escaped. 
however the "path=/tmp/rstudio-rsession/ITS\mbi-ds" is actually there.

### Describe the behavior you expected

I expected the session to be terminated.

**Comment by ronblum** [comment]
@mikkelbisgaard It looks like this was also filed as a support issue, so I'm closing it in this queue as it will be handled by our Support Team. Thanks!
