### ISSUE TITLE
Tcltk package error in Rstudio

### ISSUE THREAD

**Issue by GagoSalahed** [rstudio/rstudio#2161]
Hi,

I've read so many posts on different blogs and forums talking about the same problem I'm having, but unfortunately haven't found any conveniant solution.

I've installed the tcltk and the tcltk2 packages on Rstudio and managed to get a response from the program using the command "tk_select.list(c('1','2'))"a very basic function that displays a vector, in local it works, but couldn't do the same on Rstudio-Server installed in OS RHIEL 6.6 

and I've got this message : 

"Error in structure(.External(.C_dotTclObjv, objv), class = "tclObj") : [tcl] invalid command name "toplevel"."

The Rstudio online can't display well any data using shiny and tcltk, I've tried so many suggestions (installed shiny on every user account, checked all the paths were absolut and correct)

Any help would be very appreciated, and if any supplementary information is needed i'll be available.
![error rstudio2](https://user-images.githubusercontent.com/36270241/35978954-5801c602-0ce7-11e8-9fbe-c7053dcf7ecf.PNG)

**Comment by ronblum** [comment]
Hi @GagoSalahed—the code is attempting to open a new visualization window, which works on RStudio Desktop. However, X11 is not supported by RStudio Server, including tcl/tk.

**Comment by GagoSalahed** [comment]
@ronblum 
Thank you for your answer, but could you give me an alternative solution or a suggestion to resolve this problem please?

**Comment by ronblum** [comment]
Hi @GagoSalahed, what are you trying to accomplish? Are you trying to display data in a new, external window, or something else?
