### ISSUE TITLE
Tarfile still built on libgstreamer0.10

### ISSUE THREAD

**Issue by LyzardKing** [rstudio/rstudio#2162]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      :  Ubuntu 17.10
    R Version       :

### Steps to reproduce the problem
Download and extract the tarfile, try to run bin/rstudio

### Describe the problem in detail
Hi, I'm the maintainer for ubuntu-make, a cli tool to install ides from the upstream websites. (https://github.com/Ubuntu/ubuntu-make)
I download the tarfile, install the dependencies and run rstudio.
The issue is that there is no tafile built on libgstreamer1.0, so newer versions of ubuntu are cut out.

**Comment by LyzardKing** [comment]
I'd like to know if and when we'll have a new version available

**Comment by jmcphers** [comment]
We've resolved this in RStudio 1.2. You can try a pre-release here if you want to confirm:

https://dailies.rstudio.com/rstudio/oss/ubuntu/amd64/xcopy/

Let us know if that doesn't do the job for you!

**Comment by LyzardKing** [comment]
@jmcphers Great!
Is there an eta on when it'll hit stable?
(Is the only main difference the support for libgstreamer1.0?
If that's the case it should work on all currently supported ubuntu versions..)

**Comment by LyzardKing** [comment]
@jmcphers  Any eta on when this will be available as stable?

**Comment by LyzardKing** [comment]
Great! Thanks!
