### ISSUE TITLE
R graphics engine version 12 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 

### ISSUE THREAD

**Issue by frederikdensou** [rstudio/rstudio#2165]
Hi.

I've not found any new threads on this issue. I'm running current version of R:
$version.string
[1] "R version 3.4.3 (2017-11-30)"

$nickname
[1] "Kite-Eating Tree"

and RStudio Version 1.0.44 on an Ubuntu 16.04LTS machine.

As I've done a complete reinstallation without any solution, I'm asking here. Prior issues has been advised to upgrade to newest version of RStudio, which should support the version 12 of the graphics engine, but it doesnt seem to work here.

Any ideas?

Regards,
Frederik.

**Comment by ronblum** [comment]
@frederikdensou It looks like you're using an old version RStudio. What happens if you install the latest version, 1.1.423? https://www.rstudio.com/products/rstudio/download/#download

**Comment by jmcphers** [comment]
RStudio 1.0.44 does not support that version of R.
