### ISSUE TITLE
Vim command history missing

### ISSUE THREAD

**Issue by clairemcwhite** [rstudio/rstudio#2167]
### System details

    RStudio Edition :  Desktop or Server 
    RStudio Version :  3.4.1 (2017-06-30)
    OS Version      :  Windows 10
    R Version       :  1.2.332

### Steps to reproduce the problem

- Use Vim keybindings (Global Options/Code/keybindings/Vim)
- Press Esc to open vim command line and execute a Vim command
```
:%s/abc/xyz/g
```
- Press Esc to open vim command line again, and press up arrow key
```
:
```
- Nothing happens

### Describe the problem in detail
Pressing the up arrow key from the vim command line doesn't recall previous commands anymore. This seems to be a fairly new problem. 

### Describe the behavior you expected
I'd expect the up arrow key from the Vim command line to access previously executed commands, so you can rerun them or fix typos without retyping the full command.

**Comment by ronblum** [comment]
@clairemcwhite Thank you for bringing this to our attention!

**Comment by gtritchie** [comment]
This is now working in 1.3 builds; presumably came with the Ace update: https://github.com/rstudio/rstudio/pull/3522
