### ISSUE TITLE
"Error: Unable to establish connection with R session" When Running RStudio Server behind reverse proxy with recommended settings

### ISSUE THREAD

**Issue by minorsecond** [rstudio/rstudio#2173]
RStudio Edition : Server
    RStudio Version : 1.1.423
    OS Version      : Fedora 27 (Server) & Debian Stretch
    R Version       :  3.4.3 (2017-11-30)

Install RStudio Server. Use either the Apache or Nginx [recommended reverse proxy configurations](https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy).

When you open RStudio on local network, it works as expected. However, when you try to access it using the reverse proxy (rs.mydowmain.com) and log in, the interface loads but there is some latency. Pressing enter, for example, makes the cursor jump to a new line, but there is no ">" character at that new line. After a few seconds, "Unable to establish connection with R session" will appear, with the ">" character below it. 

Trying to browse the file system through the interface doesn't work - it loads indefinitely. I've tried it with both Fedora and Debian, with no change in behavior.

sessioninfo() returns "could not find function..."

**Comment by minorsecond** [comment]
![screen shot 2018-02-10 at 4 41 52 am](https://user-images.githubusercontent.com/2933789/36061223-f145e8b2-0e1c-11e8-92e7-69659c8aa220.png)

**Comment by jmcphers** [comment]
We have not been able to repro this and had no other reports in a year and a half, so closing.
