### ISSUE TITLE
Graphic glitch of UI on macOS with a sufficient window size

### ISSUE THREAD

**Issue by ukyoi** [rstudio/rstudio#2176]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 1.2.337
    OS Version      : macOS 10.13.3 (Macbook Pro 13 with Retina Display, Late 2015)
    R Version       : R 3.4.3

### Steps to reproduce the problem
1. Open RStudio
2. Maximize RStudio main window.

### Describe the problem in detail
Some decorations are displayed as solid black square if the window size is large enough. I can't tell the exact size to trigger the Bug but maximize on a 13 inch Retina display (2880 by 1800) is large enough. If I reduce the window size and restart RStudio, the glitches are gone untile I expand it again.

### Describe the behavior you expected
Display the UI properly.

    > sessionInfo()
    R version 3.4.3 (2017-11-30)
    Platform: x86_64-apple-darwin15.6.0 (64-bit)
    Running under: macOS High Sierra 10.13.3
    
    Matrix products: default
    BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
    
    locale:
    [1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets 
    [6] methods   base     
    
    loaded via a namespace (and not attached):
    [1] compiler_3.4.3  rsconnect_0.8.5 tools_3.4.3    
    [4] yaml_2.1.16 

Thanks for reading this report.

**Comment by gtritchie** [comment]
Can you attach a screenshot showing the problem? Thanks!

**Comment by ukyoi** [comment]
![rstudio_glitch](https://user-images.githubusercontent.com/617097/36190846-6aff4894-1195-11e8-9d9f-a7966f576667.jpeg)

@gtritchie Thanks for your reply. Here is the picture. The black blocks are not static. They may flicker when the corresponding area need to refresh (e.g. when scrolling, resizing, etc.).

**Comment by ukyoi** [comment]
With the newest R preview version. All semitransparent elementary rendered as solid black. It's a lot better but still definitely a problem.

**Comment by kevinushey** [comment]
Can you share some more information on your macOS machine? In particular, it'd be helpful to know what video card you have. E.g. I have:

![screen shot 2018-04-04 at 9 31 24 am](https://user-images.githubusercontent.com/1976582/38320969-fa34290a-37ea-11e8-8057-4a7a75fa4f8a.png)

**Comment by kevinushey** [comment]
Oops! Thanks for the heads up; I've removed the serial number.

**Comment by ramnathv** [comment]
@kevinushey I am encountering the same issue when I maximize the source window. The same UI glitches also persist when I am dealing with tables displayed inline in R notebooks.

**Comment by kevinushey** [comment]
@ramnathv can you provide some more information? A screen capture of your 'About This Mac' (making sure to remove the serial number) would be useful. It would also be useful to have the output of:

    /usr/sbin/system_profiler SPDisplaysDataType

**Comment by ukyoi** [comment]
@kevinushey Thanks for your reply.
Here is my result of system_profiler SPDisplayDataType:

```
Graphics/Displays:

    Intel Iris Graphics 6100:

      Chipset Model: Intel Iris Graphics 6100
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x162b
      Revision ID: 0x0009
      Metal: Supported, feature set macOS GPUFamily1 v3
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2560 x 1600 Retina
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
```

Since it's not everyone suffering the issue, maybe I should report upstream (to Qt or Apple)?

**Comment by ukyoi** [comment]
@kevinushey I got rid of this issue with GPU rasterization disabled. Seems this is a bug of Chromium that Qt is using, or Chromium just made a workaround in newer versions.

Thanks for your reply.

**Comment by gtritchie** [comment]
@ukyoi we have updated RStudio to use Qt 5.11.1. Could you install daily build 1.2.816 or newer and test if the issue still persists even without using the `--disable-gpu-rasterization`? That would be very helpful for us to know if Qt / Chromium has made a fix for this. Thank you!

**Comment by ukyoi** [comment]
@gtritchie The issue disappeared on the newest daily version even with `--enable-gpu-rasterization` on. Thanks for your great work!

While the scroll is laggier than the 1.1.x (Webkit) version. Sad……

**Comment by kevinushey** [comment]
The reduced scrolling performance (especially in the data viewer) has been quite disheartening for us as well. :-/ Nonetheless, we're doing our best to get things in shape for v1.2.

**Comment by gtritchie** [comment]
Sounds like this can be closed. One step forward, 0.75 steps back?
