### ISSUE TITLE
Option to clone without history from version control

### ISSUE THREAD

**Issue by draben** [rstudio/rstudio#2178]
### System details

    RStudio Edition : Server Pro 
    RStudio Version : v1.1.375
    OS Version      :  Redhat 7.4
    R Version       : 3.4.1

### Current procedure to clone from version control

Create new project -> Version Control -> Git

Presents a dialog box requesting the repository URL, new project directory name and location (and a repo username when SVN is used).

### Desired new feature

An additional check box that would allow the user to create a shallow clone of the repository. For git, the checkbox would supply --depth = 1 to the clone command.

### Why?

To avoid propagating the (large) git history of repositories that are used as project templates. 

We use project templates as the basis of all R projects so that we can update and deploy corporate branded templates, in-house helper libraries, common in-house data, etc. For our users and their use cases, we find this superior to deploying R packages.

Our project templates are under active development with frequent updates, and their Git history is quite large. We do not want to propagate the history of our R project template to all other projects.

### Can't we just clone from the command line?

Sure, of course we can. However, our user base is quite large and almost none of them have familiarity with git. The RStudio IDE is quite user-friendly and we believe adding a new checkbox would be less complicated than cloning through the terminal.

**Comment by jmcphers** [comment]
Thanks for the suggestion! If we add this, it will apply to all RStudio versions (desktop/server/pro) so I'm removing the Pro label. 

Are you aware of the Project Templates feature in RStudio Server? If your configuration includes a shared system package library, you can put your project templates there, and update them as often as you like. RStudio will show them when users create new projects.

https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html

**Comment by jmcphers** [comment]
This is a nice idea but has received no upvotes or attention for years and isn't realistically on our roadmap soon.
