### ISSUE TITLE
Mac Desktop Pro emits a license error, shuts down

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2179]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.333
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Install the daily build of RStudio MacOS Desktop.
2. Click on the application to open it.

### Describe the problem in detail

Starting up RStudio Mac Desktop Pro results in the pop up message ```"Unable to initialize license system."``` Clicking ```OK``` shuts down the application.

<img width="468" alt="desktop_license_error" src="https://user-images.githubusercontent.com/31009952/36104563-5cab87fa-0fe0-11e8-9c57-bed77cecfdbe.png">

### Describe the behavior you expected

RStudio will run.

**Comment by gtritchie** [comment]
Significant amount of desktop pro licensing code not yet merged into master (all the licensing UI, substantial bug-fixing on underlying logic). Should be merged into master later this week or next.

**Comment by ronblum** [comment]
Pro issue.

**Comment by ronblum** [comment]
Moving to pro.
