### ISSUE TITLE
Plot export captures wrong portion of screen in certain configurations

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2180]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.423
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3

### Steps to reproduce the problem

Create an HTML widget and show it in the Viewer pane; e.g.

```R
library(DT)
DT::datatable(mtcars)
```
Then click `Export -> Save as Image...`, and open the file after it's saved.

### Describe the problem in detail

The generated file captures part of the screen outside of the plot area.

### Describe the behavior you expected

Only the plot itself should be saved.

### Notes

This appears to only reproduce in certain multi-monitor configurations; e.g. when using a regular-DPI monitor in conjunction with a high-DPI monitor.

See: https://community.rstudio.com/t/r-studio-export-misses-the-plot-and-includes-window-and-background-of-work-area/5026

**Comment by neurogrok** [comment]
Same problem here. 
RStudio Desktop Version 1.1.442 on Windows 10 w/ R 3.4.3

Multi-monitor high-DPI  configuration. 

Example output (clearly not a readable table): 
![rplot04](https://user-images.githubusercontent.com/6096287/38105023-e93b9afc-3358-11e8-8e3a-a8e3cef4eff4.png)

**Comment by jmcphers** [comment]
No reports of this in well over a year, and possibly addressed by high DPI improvements in QtWebEngine, so closing (feel free to reopen if you feel this is in error!)
