### ISSUE TITLE
Reopening a currently open project is treated as switching projects

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2181]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.338
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Open a project, e.g. `my_little_project`
2. Change a variable: `my_little_variable <- "my little value"`
3. Reopen the project: `File -> Recent Projects -> my_little_project`

### Describe the problem in detail

Reopening a currently opened projects is treated as if the user is trying to switch to a different project. As a result, if any changes are made—environment variables set, or edit but unsaved files—a pop up prompts the user to save the changes, then switches to the project.

### Describe the behavior you expected

The project should remain in its current state as if the reopen was never attempted. This is the behavior when opening objects (files) in other cases, such as reopening a file in RStudio:

1. Open a file, e.g. `my_little_file.R`
2. Edit the file
3. Reopen the file: `File -> Recent Files -> my_little_file.R`

The same is in R, Word, Excel, etc. In this cases, the file is not reopened, with no prompts to save changes; the applications returns to its current state, including any changes made, without any prompting.

That said, projects are a different kind of thing from files, and maybe we intentionally want to keep this behavior. It's like asking, "Do you want to save your changes, or reject any changes and keep the project in its previous state?"

**Comment by kevinushey** [comment]
This is in some sense a feature: this is one mechanism through which a user could re-open the current project, and so get a clean IDE slate (new R session + reloading of the IDE surface). Perhaps we could preserve the current behavior, but augment the UI to make this a bit more clear?

**Comment by ronblum** [comment]
I tried out two IDEs as comparison points. If you try to reopen the same project ("solution") in Microsoft Visual Studio, nothing happens except for a message that appears at the top: 
<img width="225" alt="visual_studio_reopen" src="https://user-images.githubusercontent.com/31009952/36205761-d2f884b6-115d-11e8-845b-7115b58d5226.png">

If you reopen an open file in SmartGIT, it opens a new window with the file, letting you edit the same file twice, simultaneously. So, very different responses. I think then, there's no consistency, so we should do what we think makes the most sense—such as the current behavior —> it's a feature, not a bug. I don't think we need to change the UI—I think it's reasonable as is. (In retrospect, I should have compared to other IDEs first, not MS Word.)
