### ISSUE TITLE
readline() with no prompt is not interruptible

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2184]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.419
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3

### Steps to reproduce the problem

Try executing `readline()`. Attempt to interrupt the process by pressing Escape.

### Describe the problem in detail

The `readline()` invocation is not interrupted.

### Describe the behavior you expected

We should be able to interrupt a prompt-less `readline()` call.

### Notes

Attempts to interrupt a `readline()` invocation that includes a prompt, e.g. `readline(">>> ")`, succeed.

**Comment by jmcphers** [comment]
Still a problem in ~ 1.3.600.

**Comment by jimhester** [comment]
Another common case where this behavior occurs is with the update prompt when installing packages with remotes, e.g. if you have any out of date packages and you run `remotes::install_github("tidyverse/dplyr")` you will get a prompt, but there is no way to interrupt the process.

It would be great to fix this!

**Comment by kevinushey** [comment]
IIUC `remotes` is using `readLines()`, not `readline()`:

https://github.com/r-lib/remotes/blob/e8c60b42e089702c9a2dbfb2393cfb2bf5a0230b/install-github.R#L1145

So `remotes` could work around this by using `readLines("Enter a response: ")` or something.

**Comment by jimhester** [comment]
Oh, I see this issue is only for `readline()` without arguments, I will switch remotes to use `readline()` and see if that fixes things.
