### ISSUE TITLE
Add support for arrow keys in editor on the iPad

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2186]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.300
    OS Version      : iOS 11

### Steps to reproduce the problem

1. Set focus to the editor pane
2. Press the arrow keys a few times

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

The arrow keys should work on the iPad. The reason they don't is that -- for some reason -- Safari does not send arrow keycodes on iOS. 

There is a fix for this in newer versions of Ace, which @gtritchie discovered while researching the issue in xterm.js:

https://github.com/ajaxorg/ace/blob/eb2437badf4013893e15cb873057607c09cc95ae/lib/ace/keyboard/textinput_ios.js#L483-L526

We probably don't have the resources to pick up an entirely new Ace in this release, but the code above might be relatively easily inserted into our existing Ace installation to add support for arrow keys.

**Comment by gtritchie** [comment]
Finally I can justify owning an iPad Pro.

**Comment by bbjonz** [comment]
This fix would be wonderful.  It’s not clear to me, though, where to add the us code to RStudio Server.  Some help in that direction would be much appreciated.

**Comment by gtritchie** [comment]
I’m working on it now. :-)

**Comment by bbjonz** [comment]
Fantastic!  I really appreciate it.  Like you, I’m looking forward to justifying owning an iPad Pro!

**Comment by kkleinoros** [comment]
Has this problem been resolved yet?

**Comment by kevinushey** [comment]
You can give it a trial run in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by bbjonz** [comment]
I've been running preview releases for over a month and the problem seems to have been resolved.
