### ISSUE TITLE
Syntax error after closing a window in desktop developer mode

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2189]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.342
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Open a shell
2. `export RSTUDIO_USE_CHROMIUM_DEVTOOLS=yes`
3. `/Applications/RStudio.app/Contents/MacOS/RStudio`
4. Choose from menu: Help -> Diagnostics -> Open Developer Console
5. Click on “RStudio”
6. Close the window (red dot/X)

Also
1. Open a shell
2. `export RSTUDIO_USE_CHROMIUM_DEVTOOLS=yes`
3. `/Applications/RStudio.app/Contents/MacOS/RStudio`
4. Generate plot, e.g. `plot(cars)`
5. Click on “Zoom” in Plots pane
6. Close the window (red dot/X)

### Describe the problem in detail

In developer mode, two actions involving closing an external window—the developer console and a zoomed plot—result in a syntax error written out to the shell:

>    "Uncaught SyntaxError: Unexpected token )"

(I don't know if it's stderr or stdout.) The windows close successfully, though, and RStudio can be used without any problems.

### Describe the behavior you expected

No syntax error.

### Session Info

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16

**Comment by jmcphers** [comment]
No longer repros in 1.3.600.
