### ISSUE TITLE
system() function works when I use R from terminal but not from RStudio

### ISSUE THREAD

**Issue by sbalci** [rstudio/rstudio#2193]
system() function works when I use R from terminal but not from RStudio

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.419
    OS Version      : MacOS 10.13
    R Version       : 3.4.3

### Describe the problem in detail
I am using edirect API of National Library of Medicine https://dataguide.nlm.nih.gov/edirect/install.html
I can run the commands inside R with system() function when I am using R from terminal.
Same code cannot find command when I use R with RStudio.
Below is the screenshot from RStudio and Terminal.

![screenshot](https://support.rstudio.com/hc/user_images/4vgwf9Mrq_aQTk_tBYw68g.png)

### Describe the behavior you expected
RStudio should work similar to Terminal

### The R code in question
`system("esearch -db pubmed -query 'fentanyl abuse'")`

**Comment by dfalty** [comment]
It looks like you may need to set the PATH environment variable for EDirect within RStudio. What does the following give you inside R vs within RStudio? If it's missing the path to edirect, it won't work.
`Sys.getenv("PATH")`

**Comment by sbalci** [comment]
Thank you for your response. Following are what I get:
- Inside Terminal code gives:
"/Users/serdarbalciold/.rbenv/shims:/opt/local/bin:/opt/local/sbin:/Users/serdarbalciold/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/opt/X11/bin:/usr/local/git/bin:/Users/serdarbalciold/edirect"
- Inside R studio:
[1] "/Users/serdarbalciold/.rbenv/shims:/opt/local/bin:/opt/local/sbin:/Users/serdarbalciold/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/opt/X11/bin:/usr/local/git/bin:/Users/serdarbalciold/edirect:/Users/serdarbalciold/edirect:/Users/serdarbalciold/RepTemplates/pubmed/edirect"

I tried to install edirect under same project folder. It is seen from RStudio. (Users/serdarbalciold/RepTemplates/pubmed/edirect")

Do you have any suggestions?

**Comment by dfalty** [comment]
I tested this out (on 1.1.423 Mac) and I was able to call esearch after just installing and setting my ~/.Renviron file to the following
`PATH=${PATH}:${HOME}/edirect`
![image](https://user-images.githubusercontent.com/15237845/36319258-fac70534-1307-11e8-9d36-b6dc212f57fb.png)
Did you install edirect in multiple places? `/Users/serdarbalciold/edirect `
 &  `/Users/serdarbalciold/RepTemplates/pubmed/edirect`

I did see a concerning issue when trying to use the same code you gave. The following just hangs RStudio, but it works from CL and in the terminal. This might be a bug so I'll mark it as such.
`system("esearch -db pubmed -query 'fentanyl abuse'")`

**Comment by sbalci** [comment]
Thank you very much. I am able to run `"esearch -version"` after changing Rprofile as you have shown.
But as you sad the search code hangs RStudio.

**Comment by sbalci** [comment]
I think I have found a way to do this with `rstudioapi`

Following code works, in R script files as well as R chunks in R markdown.

```
myTerm <- rstudioapi::terminalCreate()
EdirectCall <- "esearch -db pubmed -query 'seasonal affective disorder' > myquery.txt \n"
rstudioapi::terminalSend(myTerm, EdirectCall)
rstudioapi::terminalKill(myTerm)
readLines("myquery.txt")
```
What do you think @dfalty ? Is this an appropriate way? The only problem is that I cannot programatically return to console, the terminal stays on the front even after `terminalKill`

Best wishes

**Comment by dfalty** [comment]
@sbalci that looks like a fine workaround. You should be able to avoid the terminal opening in the first place by using `rstudioapi::terminalCreate(show=FALSE)`.

In any case, RStudio shouldn't hang when trying to run the original system() command, so hopefully there is something we can do there. :)

**Comment by sbalci** [comment]
Thank you. Currently I am using following code. Please post here updates on `system()`.
Best wishes.

```
myTerm <- rstudioapi::terminalCreate(show = FALSE)
rstudioapi::terminalSend(myTerm, "esearch -db pubmed -query '(diabetes AND pregnancy) AND (\"2017/01/01\"[PDAT] : \"2017/12/31\"[PDAT])' | efetch -format xml | xtract -pattern Grant -element Agency | sort-uniq-count-rank | head -n 10 > myquery.txt \n")
Sys.sleep(1)
repeat{
    Sys.sleep(0.1)
    if(rstudioapi::terminalBusy(myTerm) == FALSE){
        print("Code Executed")
        break
    }
}
```

**Comment by jmcphers** [comment]
We haven't had any other reports of this in well over a year and can't meaningfully investigate further since we don't have `esearch` or any other program which reproduces the issue. Please reopen if you have an example we can try!

**Comment by dtenenba** [comment]
Can reproduce this issue with the `biolib` [command](https://pypi.org/project/pybiolib/). 

```
system("biolib run DTU/DeepTMHMM --help ")
```

RStudio 2024.04.1+748 (2024.04.1+748)
MacOS Sonoma 14.5 M1
R 4.4.0

**Comment by kevinushey** [comment]
@dtenenba could you please open a new issue with more details?
