### ISSUE TITLE
RStudio Desktop 1.1.383 issue with Git for Windows and special characters in working dir

### ISSUE THREAD

**Issue by AshesITR** [rstudio/rstudio#2194]
### NOTE

My git path is
$git
[1] "C:\\Users\\<--user-->\\AppData\\Local\\Programs\\Git\\cmd\\git.exe"

I'm not sure if this bug has been fixed in 1.1.423, since that version mentions something related to git being installed in the home directory (wich is "C:\\Users\\<--user-->\\Documents").

If that is the case, I'm sorry for not being able to test on that version at the moment - feel free to close the issue.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 7, 64-bit
    R Version       :  3.4.0

### Steps to reproduce the problem
Work in a git project in a path containing special characters, e.g. "C:/§".
Characters with issues discovered so far: §, ä, ö, ü, ß, Ä, Ö, Ü

### Describe the problem in detail
The git pane stays white, starting git shell from RStudio produces a bash.exe.stackdump and generally doesn't work.
Manually starting git-bash.exe and cd'ing to the directory works as usual.

### Describe the behavior you expected
Git should work in the same way as with normal paths.

**Comment by dfalty** [comment]
It looks like this wasn't fixed for 1.1.423 as I was able to reproduce on Win8. Thanks for the report!

**Comment by AshesITR** [comment]
Still reproducible for 1.1.442.

**Comment by EconKjetil** [comment]
Still have the same issue with version 1.2.1335. White pane if placed in folder with Ø

**Comment by R-Hannibal** [comment]
Verified Fixed on: Windows Desktop Version 1.3.938 (R version 4.0.0 alpha)

- The git pane now loads correctly and displays relevant information and fields. In addition, verified that the Diff window can be successfully opened (in RStudio 1.1 builds, opening the diff window resulted in an error 'The directory is invalid').
- As far as the opening a git shell from RStudio producing a bash.exe.stackdump, I haven't been able to reproduce this behavior in either RStudio version 1.2 or 1.3 builds. Seems like this may have been addressed in the 1.2 release.
