### ISSUE TITLE
Windows VC++ startup error when updating from 1.1 to 1.2

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2197]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.344
    OS Version      :  Win8.1 / Win10 Enterprise N / Win10 Enterprise / Win10 Pro

### Steps to reproduce the problem
1. Install version >= 1.2.246 over latest 1.1 build
2. Observe error on startup

Problem is fixed by installing VC++ manually. https://www.microsoft.com/en-us/download/details.aspx?id=48145

Win10 Enterprise N
![image](https://user-images.githubusercontent.com/15237845/36212114-c387b938-1168-11e8-9f96-0c7760fa5b64.png)

Win10 Enterprise
![image](https://user-images.githubusercontent.com/15237845/36212186-ee7e0d36-1168-11e8-9810-f2228ccd62d9.png)

Win8.1
![image](https://user-images.githubusercontent.com/15237845/36212218-001f9410-1169-11e8-9f18-7d95dd3f6a8e.png)

**Comment by gtritchie** [comment]
Confirmed same problem on Windows-10 Pro, clean install.

**Comment by jmcphers** [comment]
Unfortunately we're going to have to provide a way for users to install the Visual C++ runtime to get past this, and that probably means bundling the component so we can continue to have a fully self-contained offline installer. Thankfully it's not enormous but it will add ~15mb to our download and probably 4 hours of arm-wrestling with either CMake or NSIS. 

https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by gtritchie** [comment]
CMake has support for including the runtime:
```
      include(InstallRequiredSystemLibraries)
      INSTALL(FILES ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION bin COMPONENT Libraries)
```
It puts the DLL's directly into the RStudio installation directory (bin), it doesn't install the Microsoft standalone package. As shown, however, it only installs the 32-bit versions; we would also need to convince it to copy the 64-bit versions into the x64 subfolder.
