### ISSUE TITLE
Opening .Rproj file does not open correct project

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#2203]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.344
    OS Version      : macOS
    R Version       : 3.4.3

### Steps to reproduce the problem

* Start with no RStudio sessions running.
* In the Finder, open an .Rproj file to start RStudio with that project.
* In the Finder, open a different .Rprof file. A new RStudio window will open, but with the project opened in the previous step.

**Comment by aronatkins** [comment]
Workaround: Open a new session in the IDE first (Session -> New Session) and then open the second project (File -> Open Project...) instead of using the Finder to open the second session.

Might be the same as #2205.
