### ISSUE TITLE
Opening a project in a new session creates a fresh window with no project (Mac)

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2205]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.342
    OS Version      : MacOS 10.12.6
    R Version       : 3.4.3

### Steps to reproduce the problem

Open a project in a new session: File -> Open Project in New Session

### Describe the problem in detail

When a project is opened in a new session, a new icon/project window opens, as expected. However, the window that's opened is not a project—none of the project's open files, Project Options is grayed out, etc.—and its name, in the upper right-hand corner, is "Project: (None)". It's as if a fresh, new RStudio window were opened.

This appears to be a regression in 1.2, and is only on the Mac; it's fine on Windows and Ubuntu.

### Describe the behavior you expected

The new window should contain the opened project.

**Comment by aronatkins** [comment]
Workaround: Open a new session first (Session -> New Session) and then open the second project (File -> Open Project...)

Might be the same as #2203.
