### ISSUE TITLE
Terminal failing to automatically fall back to RPC when websockets fail

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2207]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.x
    OS Version      : Linux
    R Version       : Don't know

### Steps to reproduce the problem

With a proxy server that doesn't allow websockets, try to open the RStudio terminal.

### Describe the problem in detail

Terminal is blank, and stays busy per the dropdown menu.

### Describe the behavior you expected

When websockets fail to connect should be automatically falling back on RPC. The customer in this case (a Pro customer, actually, but issue is very likely not Pro-specific) ended up having to manually disable terminal websockets.

Don't have a clear repro, other than customer said their proxy did not allow websockets, and they saw the terminal issue described above. Turning off websockets fixed it, but should be happening automatically (ideally).

Not a huge issue, perhaps, but definitely adds a support burden and we'd like to understand what's happening here to see if it can be fixed.

**Comment by gtritchie** [comment]
Assigned to 1.2; really want to understand this and hopefully fix for that release.

**Comment by dirks** [comment]
Could reproduce the issue on a non pro version. Either [enabling websockets on the proxy](https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy) or disabling use of websockets in rstudio options for the terminal, results in a working terminal in the IDE.

**Comment by gtritchie** [comment]
Another report in #2465. Closing that as a duplicate of this.

Troubleshooting / data-gathering steps:

1. Uncheck `Tools / Global Options / Close terminal when shell exits`, then try to start a new terminal; is there any error output in the terminal pane
2. Turn off `Connect with WebSockets` then try to start a terminal. Does that work?

**Comment by dlukes** [comment]
> Another report in #2465. Closing that as a duplicate of this.

Sorry and thanks, I did search open issues prior to posting but I missed it :)

Re: 1 -- I get the same messages as with the option checked:

```
WebSocket connect error, switching to RPC
Unable to switch back to RPC mode
```

Re: 2 -- That works! Thanks so much for the workaround :) (The console shows no messages and it works irrespective of the *Close terminal when shell exits* setting, if that matters.)

**Comment by dlukes** [comment]
One additional detail: websockets don't work in my case in spite of the nginx proxy configuration following the [guidelines](https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy) linked by @dirks. The only difference is that I've specified a `server_name` and I'm serving RStudio over https, so I have

```
server {
  server_name example.com;
  listen 443 ssl default_server;
  listen [::]:443 ssl default_server;

  ssl_certificate /path/to/fullchain.pem;
  ssl_certificate_key /path/to/privkey.pem;

  ...
}
```

instead of

```
server {
  listen 80;

  ...
}
```

**Comment by gtritchie** [comment]
In general Terminal WebSockets _should_ work when RStudio being served over https (the websockets use wss: instead of ws:). I'm not aware of any extra nginx configuration needed to make that work (but there certainly might be some!).

**Comment by gtritchie** [comment]
Note to self: repro'd the failure to fall back to RPC: happened because the websocket connect timeout triggered OnError, which then starts the switch over to RPC (an async call back to the server), but then the websocket sends OnClose, which shuts down the terminal altogether. Hence the blank "no terminal" state.

**Comment by gtritchie** [comment]
Reopening; should get rid of the cryptic error message and possibly automatic switch off the WebSockets preference, instead.
