### ISSUE TITLE
Provide option to print all of current Rmd source pane: code and inline chunk output

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2208]
### System details

    RStudio Edition : Desktop (also Server)
    RStudio Version : 1.2.342
    OS Version      : MacOS 10.12.6 (also Ubuntu)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Create an R markdown document with code chunks and other elements to be previewed. Example:

```
---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
editor_options:
  chunk_output_type: inline
---

$$
f(x) = \frac{x^2}{3} + \int_0^x t^2 \ dt
$$


```{r}
plot(cars)
```
[Plus three more back ticks after the last line]

2. Get the function between the $$'s to render (you might need to move the cursor around or type a bit)
3. Run the last chunk (inline)
4. Print the source pane: File -> Print

### Describe the problem in detail

With an open R markdown file, the print option (File -> Print) brings up a print dialogue that will let me print the code in the source pane. I can also knit the file and get a rendered document, which I can print. However, let’s say I have chunk output set for inline and I’ve run some of the chunks, and even have a function displayed using $$. "Print" only returns the code:
<img width="259" alt="print_source" src="https://user-images.githubusercontent.com/31009952/36278049-98d13ce8-1260-11e8-9c0e-80c4275ecb8d.png">

### Describe the behavior you expected

What I’d like to print is what I see in the pane: source code + inline output:
<img width="636" alt="draft_rmd" src="https://user-images.githubusercontent.com/31009952/36278058-9d369c88-1260-11e8-9bb5-f5aa24e920f1.png">

Suggestion: provide two print options, one to print the source code, and one to print the source code with the currently displayed inline output.

**Comment by jmcphers** [comment]
What advantage does this have over printing the notebook's rendered HTML?
