### ISSUE TITLE
switch from boost::signals to boost::signals2

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2210]
`boost::signals` is deprecated and no longer maintained, as per:

http://www.boost.org/doc/libs/1_63_0/doc/html/signals.html

We should move to `signals2`, which (if I understand correctly) is mostly API compatible with `boost::signals`.

**Comment by theova** [comment]
Seems that this happened and that the ticket can be closed?

**Comment by kevinushey** [comment]
You are indeed correct!
