### ISSUE TITLE
Cache RStudio Windows build dependencies

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2212]
We have recently improved the RStudio builds on Linux so that it is not necessary for them to download dependencies every time the build runs (in a container); instead, dependencies are cached as part of the container; see #1614 for details.

However, this work applies only to Linux, where we are now able to read dependencies from `/opt/rstudio-tools/dependencies`. On Windows, dependency installation works differently, and we're still re-downloading every dependency (including very large ones like Boost and Pandoc) every time we build in the lab.

We need to make a change for Windows which is symmetric to the one we made on Linux; namely:

1. update the scripts in `rstudio/dependencies/windows` so that they can install dependencies outside the source tree,
2. update the CMake scripts to find the dependencies in the new location, and
3. update the Windows Dockerfile so that it downloads and installs the dependencies into the Docker image.

**Comment by timtmok** [comment]
I think this would be good to help speed up the builds.

**Comment by timtmok** [comment]
@GCRev I have changes from before the holidays that I've pushed to https://github.com/rstudio/rstudio/tree/feature/windows-dependencies-cache

It still needs some cleanup in the Jenkinsfile. I stopped because I didn't have a way to build the image locally.

**Comment by mikebessuille** [comment]
@timtmok Wasn't this just demoed?  So... it's done???

**Comment by timtmok** [comment]
> @timtmok Wasn't this just demoed? So... it's done???

Yes, this was demo'ed. Just forgot that moving it to done doesn't close it.
