### ISSUE TITLE
RMarkdown Notebooks and Knitr Cache

### ISSUE THREAD

**Issue by nviets** [rstudio/rstudio#2213]
Is there a way to make RMarkdown notebooks refresh knitr cache when runing code chunks?  I'd like to be able to retain the code chunk output within an html_notebook and merge it into an html_document using the child argument to set the cache path.

Thank you!

**Comment by jmcphers** [comment]
No, there isn't. R Markdown notebook chunks are rendered to an internal RStudio cache, which is unrelated to knitr's cache. You can see the cached chunk outputs in your project's `.Rproj.user` folder (or `.rstudio` if you don't use projects), but there is no straightforward way to migrate them into a knitr cache.

**Comment by nviets** [comment]
Thanks for clarifying Jonathan!
