### ISSUE TITLE
"Publish to Server" dialog says app name must be 3+ characters, but it only accepts 4+

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#2217]
RStudio Desktop 1.1.41, Windows 7

Trying to publish a shiny app:

- Click the publish circular blue button
- "Publish Application..."
- In the "Title" field, enter 3 characters
- An error shows up "The title must contain 3 - 64 alphanumeric characters." and the Publish button is disabled
- If you enter a 4th character, the error goes away

The message should say the title needs to be 4-64 chars

![image](https://user-images.githubusercontent.com/952340/36338027-a5e98346-1372-11e8-8311-1f677e7f502f.png)

**Comment by jmcphers** [comment]
Fixed; thanks for reporting this!

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
