### ISSUE TITLE
Zoom settings lost after closing RStudio

### ISSUE THREAD

**Issue by djbirke** [rstudio/rstudio#2218]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Ubuntu 17.10
    R Version       : 3.4.2

### Steps to reproduce the problem
1. Open RStudio.
2. Change Zoom level to 150%.
3. Close RStudio.
4. Open RStudio. Zoom levels are back at 100%.

### Describe the behavior you expected
Changes to zoom levels settings should persist after closing RStudio.

**Comment by ronblum** [comment]
@djbirke I am unable to reproduce this; zoom settings are persisting in my case. Any more information you can provide would be helpful. For example: have you used a previous release, in which it worked for you? Did you use Ubuntu 16.04 beforehand, and did it work there?

**Comment by djbirke** [comment]
@ronblum Thank you for the quick response!

- Yes, this has been a problem in previous releases as well (at least since 1.0)
- Yes, was also a problem under 16.04
- My partition is encrypted with encfs (might be relevant, but unsure)

**Comment by djbirke** [comment]
Is there any file the settings get written to? I could monitor that file and see what happens when I change my zoom levels.

**Comment by djbirke** [comment]
Thanks. The settings file was owned by `root` for some reason. Deleting it solved the problem.

**Comment by GilChrist19** [comment]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1335 & 1.3.180 (daily build)
    OS Version      :  Ubuntu 18.04.2
    R Version       :  3.6.0

### Description

This is still an issue. Potentially because of installation requirements? (ie, root permissions to install files).
Deleting the desktop.ini didn't fix it for me, but changing the folder owner did (```chown -R user ~/.config/RStudio```)
