### ISSUE TITLE
Restarting R (ctrl+shift+F10) kills ssh connections in terminal

### ISSUE THREAD

**Issue by BarkleyBG** [rstudio/rstudio#2226]
Hi there,

When I restart R, my open SSH/SFTP connections in the terminal are also killed. I describe this more below in the section on "further griping". 

### Restarting R:
- Either using hotkey Ctrl + Shift + F10
- Or, when using hotkeys to rebuild a package (Ctrl + shift + B)

### Terminal:
- I often connect via SSH (or SFTP) to a remote server. 
- I use MSYS/MinGW/git bash for the terminal

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 7
    R Version       : 3.3.0

### Further griping

This is pretty frustrating for my development workflow. When I've done some local development and I want to test my work on the remote server, I generally:
1. SFTP or rsync my package to the remote server (from RStudio's terminal)
2. SSH to the remote server. Open an interactive job. Run a script. (from RStudio's terminal)
3. If there's any issues with the package, I make changes locally, and rebuild locally. (in Rstudio)

The issue is that if I use the RStudio built-in hotkeys to build() or restart R in step 3., then I get logged out from my sessions in 1 and 2. It's not life-altering, but it's pretty frustrating to login to the remote again, cd to the correct directories again, etc. Moreover, I don't see why clearing the workspace and namespace in my local R session needs to kill my remote SSH connections.

Is there a way to avoid killing these remote connections? I didn't see anything in these community discussions. Thanks!

**Comment by jjallaire** [comment]
@gtritchie and @jmcphers I am also frequently frustrated by this (as often times your only choice is to just keep your R session alive until background terminal sessions complete).

**Comment by gtritchie** [comment]
Thanks for the report. We recognize this behavior is a problem with certain workflows. The [terminal is a child process of the R session](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal?version=1.2.319&mode=desktop#lifetime), so currently cannot keep running when you restart R. Issue #2059 tracks the possibility of changing this, so I will close this issue.

Doesn't help you on Windows, but for those using Mac/Linux/RStudio Server, you can look at using `tmux` or `screen` and then have the terminal auto-reconnect to those via some customization as described here: https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal#tmux
