### ISSUE TITLE
Feature Request: Saving .Rnw file when using knit() 

### ISSUE THREAD

**Issue by hannes101** [rstudio/rstudio#2227]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.423 
    OS Version      :  Windows 10 
    R Version       : 3.4.3

### Steps to reproduce the problem
1. Edit a .Rnw file
2. issue knit("file.Rnw")
3. changes are not applied until the .Rnw file is saved.

### Describe the problem in detail
I often run into the issue that I forget to save the document before I issue the knit command. Would it be possible to add something into RStudio , so that knit() also saves the document before knitting it? I am using RStudio to write the files and just issue the knit() command at the command line interface of RStudio.
### Describe the behavior you expected
I would expect the .Rnw file to be saved, which is the normal behaviour for example for in an LaTeX editor.
It would be great to add that feature to Rstudio.

Thanks a lot

**Comment by ronblum** [comment]
@hannes101 Thank you for the suggestion, and we'll review it as we work on future releases.
