### ISSUE TITLE
Diagnostics report includes warning about 'r-ldpath' file not found 

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2233]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.353
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

Run a diagnostics report
- Menu: Help -> Diagnostics -> Write Diagnostics Report
or
- Console: `rstudioDiagnosticsReport()`

### Describe the problem in detail

The diagnostics report contains the following warning (not error):
```
20 Feb 2018 14:10:49 [rdesktop] WARNING r-ldpath script not found at /Applications/RStudio.app/Contents/Resources/session/r-ldpath; LOGGED FROM: std::string rstudio::core::r_util::(anonymous namespace)::extraLibraryPaths(const rstudio::core::FilePath &, const std::string &) /Users/vagrant/workspace/IDE/macos/src/cpp/core/r_util/REnvironmentPosix.cpp:85
```

### Describe the behavior you expected

The warning should not be there. I believe that the file the application is looking for is `/Applications/RStudio.app/Contents/MacOS/r-ldpath`. Linking the files helps:
```
mkdir /Applications/RStudio.app/Contents/Resources/session
ln -s /Applications/RStudio.app/Contents/MacOS/r-ldpath /Applications/RStudio.app/Contents/Resources/session/r-ldpath
```
Restarting RStudio now runs without the diagnostics warning.

### Additional Information

**Diagnostics Report:**
_Note: I originally renamed the application "RStudio_1.2.353.app" but I reverted it back to "RStudio.app".)_

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1740463/diagnostics-report.txt)
[1] "1.2.353"

$R
[1] "/usr/local/bin/R"

$pdflatex
[1] "/Library/TeX/texbin/pdflatex"

$bibtex
[1] "/Library/TeX/texbin/bibtex"

$gcc
[1] "/usr/bin/gcc"

$git
[1] "/usr/bin/git"

$svn
[1] "/usr/bin/svn"

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16   

SysInfo:
                                                                                          sysname 
                                                                                         "Darwin" 
                                                                                          release 
                                                                                         "16.7.0" 
                                                                                          version 
"Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64" 
                                                                                         nodename 
                                                                         "Rons-MacBook-Pro.local" 
                                                                                          machine 
                                                                                         "x86_64" 
                                                                                            login 
                                                                                        "ronblum" 
                                                                                             user 
                                                                                        "ronblum" 
                                                                                   effective_user 
                                                                                        "ronblum" 

R Version:
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.3                         
year           2017                        
month          11                          
day            30                          
svn rev        73796                       
language       R                           
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree            
$`__CF_USER_TEXT_ENCODING`
[1] "0x1F5:0x0:0x0"

$Apple_PubSub_Socket_Render
[1] "/private/tmp/com.apple.launchd.uAj8jE50AW/Render"

$BOX_CLIENT_ID
[1] "wjyed0nfh33235882eagth81bkjf6rmw"

$BOX_CLIENT_SECRET
[1] "VmINFg8qBPq9znQyXY8m2D2ep6DXdyV4"

$CLICOLOR_FORCE
[1] "1"

$DISPLAY
[1] ":0"

$DYLD_FALLBACK_LIBRARY_PATH
[1] "/Library/Frameworks/R.framework/Resources/lib:/Users/ronblum/lib:/usr/local/lib:/usr/lib::"

$EDITOR
[1] "vi"

$GIT_ASKPASS
[1] "rpostback-askpass"

$HOME
[1] "/Users/ronblum"

$LANG
[1] "en_US.UTF-8"

$LC_CTYPE
[1] "en_US.UTF-8"

$LN_S
[1] "ln -s"

$LOGNAME
[1] "ronblum"

$MAKE
[1] "make"

$PAGER
[1] "/usr/bin/less"

$PATH
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin"

$R_BROWSER
[1] "/usr/bin/open"

$R_BZIPCMD
[1] "/usr/bin/bzip2"

$R_DOC_DIR
[1] "/Library/Frameworks/R.framework/Resources/doc"

$R_GZIPCMD
[1] "/usr/bin/gzip"

$R_HOME
[1] "/Library/Frameworks/R.framework/Resources"

$R_INCLUDE_DIR
[1] "/Library/Frameworks/R.framework/Resources/include"

$R_LIBS_SITE
[1] ""

$R_LIBS_USER
[1] "~/Library/R/3.4/library"

$R_PAPERSIZE
[1] "a4"

$R_PDFVIEWER
[1] "/usr/bin/open"

$R_PLATFORM
[1] "x86_64-apple-darwin15.6.0"

$R_PRINTCMD
[1] "lpr"

$R_QPDF
[1] "/Library/Frameworks/R.framework/Resources/bin/qpdf"

$R_RD4PDF
[1] "times,inconsolata,hyper"

$R_SESSION_TMPDIR
[1] "/var/folders/fx/m05t95913_q8x86417r0s6480000gn/T//Rtmp7ns1Jq"

$R_SHARE_DIR
[1] "/Library/Frameworks/R.framework/Resources/share"

$R_SYSTEM_ABI
[1] "osx,gcc,gxx,gfortran,?"

$R_TEXI2DVICMD
[1] "/usr/local/bin/texi2dvi"

$R_UNZIPCMD
[1] "/usr/bin/unzip"

$R_ZIPCMD
[1] "/usr/bin/zip"

$RMARKDOWN_MATHJAX_PATH
[1] "/Applications/RStudio.app/Contents/Resources/resources/mathjax-26"

$RS_PPM_FD_READ
[1] "14"

$RS_PPM_FD_WRITE
[1] "15"

$RS_RPOSTBACK_PATH
[1] "/Applications/RStudio.app/Contents/MacOS/rpostback"

$RS_SHARED_SECRET
[1] "168072824752491622650073"

$RSTUDIO
[1] "1"

$RSTUDIO_CONSOLE_COLOR
[1] "256"

$RSTUDIO_CONSOLE_WIDTH
[1] "103"

$RSTUDIO_PANDOC
[1] "/usr/local/bin/pandoc.2.0.6/"

$RSTUDIO_SESSION_PORT
[1] "41718"

$RSTUDIO_USER_IDENTITY
[1] "ronblum"

$RSTUDIO_WINUTILS
[1] "bin/winutils"

$SED
[1] "/usr/bin/sed"

$SHELL
[1] "/bin/bash"

$SSH_ASKPASS
[1] "rpostback-askpass"

$SSH_AUTH_SOCK
[1] "/private/tmp/com.apple.launchd.cwSQuWxkJN/Listeners"

$TAR
[1] "/usr/bin/tar"

$TERM
[1] "xterm-256color"

$TMPDIR
[1] "/var/folders/fx/m05t95913_q8x86417r0s6480000gn/T/"

$USER
[1] "ronblum"

$XPC_FLAGS
[1] "0x0"

$XPC_SERVICE_NAME
[1] "0"

 [1] ".GlobalEnv"        "tools:rstudio"     "package:stats"     "package:graphics" 
 [5] "package:grDevices" "package:utils"     "package:datasets"  "package:methods"  
 [9] "Autoloads"         "package:base"     
Log file: rdesktop.log
--------------------------------------------------

20 Feb 2018 14:05:00 [rdesktop] WARNING r-ldpath script not found at /Applications/RStudio_1.2.353.app/Contents/Resources/session/r-ldpath; LOGGED FROM: std::string rstudio::core::r_util::(anonymous namespace)::extraLibraryPaths(const rstudio::core::FilePath &, const std::string &) /Users/vagrant/workspace/IDE/macos/src/cpp/core/r_util/REnvironmentPosix.cpp:85
20 Feb 2018 14:09:52 [rdesktop] WARNING r-ldpath script not found at /Applications/RStudio.app/Contents/Resources/session/r-ldpath; LOGGED FROM: std::string rstudio::core::r_util::(anonymous namespace)::extraLibraryPaths(const rstudio::core::FilePath &, const std::string &) /Users/vagrant/workspace/IDE/macos/src/cpp/core/r_util/REnvironmentPosix.cpp:85
20 Feb 2018 14:10:49 [rdesktop] WARNING r-ldpath script not found at /Applications/RStudio.app/Contents/Resources/session/r-ldpath; LOGGED FROM: std::string rstudio::core::r_util::(anonymous namespace)::extraLibraryPaths(const rstudio::core::FilePath &, const std::string &) /Users/vagrant/workspace/IDE/macos/src/cpp/core/r_util/REnvironmentPosix.cpp:85
20 Feb 2018 14:30:03 [rdesktop] WARNING r-ldpath script not found at /Applications/RStudio.app/Contents/Resources/session/r-ldpath; LOGGED FROM: std::string rstudio::core::r_util::(anonymous namespace)::extraLibraryPaths(const rstudio::core::FilePath &, const std::string &) /Users/vagrant/workspace/IDE/macos/src/cpp/core/r_util/REnvironmentPosix.cpp:85
20 Feb 2018 14:45:46 [rdesktop] WARNING r-ldpath script not found at /Applications/RStudio.app/Contents/Resources/session/r-ldpath; LOGGED FROM: std::string rstudio::core::r_util::(anonymous namespace)::extraLibraryPaths(const rstudio::core::FilePath &, const std::string &) /Users/vagrant/workspace/IDE/macos/src/cpp/core/r_util/REnvironmentPosix.cpp:85

Log file: rsession-ronblum.log
--------------------------------------------------

(Empty)

**Session Info:**

[sessionInfo_output.txt](https://github.com/rstudio/rstudio/files/1740485/sessionInfo_output.txt)

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16

**Comment by ronblum** [comment]
Note: this is the case in 1.1.423, too.

**Comment by kevinushey** [comment]
Yikes! This would explain the issue a number of users have been reporting related to failures to load `rJava`. (We rely on the `ldpaths` script to update the library paths so that `libjvm.so` can be found)

**Comment by jmcphers** [comment]
Fixed by https://github.com/rstudio/rstudio/commit/0ec3d7c97eeee349d7a29d4937ca2157d3e12943.
