### ISSUE TITLE
more gracefully handle filesystem completions when directory contains many files

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2236]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.423
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3

### Steps to reproduce the problem

Navigate to a temporary directory, and create a large number of files (note that we're about to create a boatload of files so this will take a while to run!)

```R
dir <- tempfile()
dir.create(dir)
setwd(dir)
for (i in 1:1E5 - 1) {
    file <- sprintf("%05i", i)
    file.create(file)
}
```

Next, request file completions by typing `"<Tab>`.

### Describe the problem in detail

The RStudio session hangs in its attempt to request filesystem completions.

### Describe the behavior you expected

RStudio should more gracefully handle cases where a large number of files exist on the filesystem.

**Comment by kevinushey** [comment]
Looks like we might be constructing one of the completion vectors incorrectly.

![screen shot 2018-02-20 at 9 00 45 am](https://user-images.githubusercontent.com/1976582/36437726-a88b7814-161c-11e8-8ec7-45a98d94570d.png)

This routine's intention is to form a vector of length `n`, but actually ends up generating an `n * n` length vector. :-/

**Comment by ronblum** [comment]
Confirmed in Mac Desktop 1.2.405.
