### ISSUE TITLE
Syntax highlighting for Rnw treats % in string in R chunk as comment

### ISSUE THREAD

**Issue by rcragun** [rstudio/rstudio#2240]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Windows 10 Pro 1709
    R Version       : 3.4.3

### Steps to reproduce the problem

Start a new .Rnw script in RStudio. Place an R chunk that contains a string that contains a % symbol anywhere in the script. For instance, you could include `\Sexpr{sprintf(.671, fmt='%#.1f')}`. All characters in the same line after the % are incorrectly treated as comments for syntax highlighting. 

This occurs in an Rnw script when the string contains a % symbol but does not depend on the string containing a # symbol. This error does not occur for `sprintf(.671, fmt='%#.1f')` in a regular R script (i.e. the # is correctly parsed as part of the string rather than as indicating a comment).

### Describe the behavior you expected
The % symbol inside a string inside an R chunk should be interpreted as part of the string rather than as a LaTeX comment for syntax highlighting purposes.

### sessionInfo() output:

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reshape2_1.4.3 scales_0.5.0   ggplot2_2.2.1  stargazer_5.2  xtable_1.8-2  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     grid_3.4.3       plyr_1.8.4       gtable_0.2.0    
 [5] magrittr_1.5     pillar_1.0.1     stringi_1.1.6    rlang_0.1.6     
 [9] lazyeval_0.2.1   tools_3.4.3      stringr_1.2.0    munsell_0.4.3   
[13] compiler_3.4.3   colorspace_1.3-2 knitr_1.18       tibble_1.4.1

**Comment by ronblum** [comment]
Reproduced (on Mac Desktop 1.2.359).

@rcragun Can you confirm whether or not you're able to compile successfully? I'm able to generate a PDF document.

**Comment by rcragun** [comment]
I am able to compile.

**Comment by ronblum** [comment]
Formatting as a string, instead of a comment, is fixed as long as the closing quote (`'`) is there—say, when pasting the above code. However, the code is still formatted as a comment when there's no closing quote. For example, typing `'%#'` shows the problem: `%` and `#` are formatted as a comment until the second `'` is typed.

[Note: .Rnw isn't automatically including a closing quote. Cf. .R and .Rmd—is this intentional?]

**Comment by rcragun** [comment]
Cannot reproduce bug on newer RStudio 1.3.959 (on Windows 10):

![RnwSyntax](https://user-images.githubusercontent.com/5415664/107129628-4fe43c80-688c-11eb-9c0d-d63b39ad52e1.png)
