### ISSUE TITLE
Terminal in RStudio doesn't accept key input from Japanese Romaji input source (normally works like U.S. mode)

### ISSUE THREAD

**Issue by u-4** [rstudio/rstudio#2243]
### System details

    RStudio Edition : Desktop for macOS
    RStudio Version : Version 1.1.423
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3

### Steps to reproduce the problem
 1. (macOS) System Preferences -> Keyboard -> Input Sources
 2. Click the Add button, chose Japanese
 3. Input menu will appear in menu bar
 4. Select "Romaji" with icon "A" in input menu at menubar
 5. No key input occurs at terminal in RStudio
 6. Select "U.S." in input menu at menubar
 7. Key inputs are accepted normally

 8. Launch macOS Terminal or Console, source, and any input field other than terminal in RStuido
 9. Select "Romaji" with icon "A" in input menu at menubar
 10. Key inputs are accepted normally
 11. Select "U.S." in input menu at menubar
 12. Key inputs are accepted normally

### Describe the problem in detail
At Input Source "Japanese", "Hiragana" is used when we want to type Japanese characters (2-byte), "Romaji" is used when we want to type alphabet directly, and usually works like "U.S." mode. As shown above, even in macOS terminal or other programs I've got no problem to type alphabet directly in "Romaji" input source.

### Describe the behavior you expected
Accept key input from "Romaji" input method in "Japanese" input source at RStudio terminal window just like other RStudio windows.

### As a temporary measure
 1. (macOS) System Preferences -> Keyboard -> Input Sources
 2. Click the Add button, chose English -> U.S.
 3. Select "Japanese", uncheck "Romaji" in Input modes
 4. Now you can change "U.S." and "Hiragana" mode with "Eisu" and "Kana" keys or other Shortcuts for Select input source (like Cmd + Space)

**Comment by ronblum** [comment]
@u-4 Thank you for reporting this issue. I'm able to reproduce this in 1.1.423.

Note: it works in 1.2.353, which is a testing build of an upcoming release.
