### ISSUE TITLE
modal dialog gets stuck on screen in some cases

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2249]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.331
    OS Version      : macOS 10.13.3
    R Version       : R 3.4.3

### Steps to reproduce the problem

1. Open an existing file in the IDE,
2. Make some edits to that file (but do not save it),
3. Open that file with a separate editor,
4. Make some changes to that file in your other editor, and save it.

### Describe the problem in detail

RStudio pops up a message box indicating the file contents have changed on disk:

![screen shot 2018-02-21 at 10 44 48 am](https://user-images.githubusercontent.com/1976582/36498817-5bb76fe2-16f4-11e8-8611-50cee226ded6.png)

However, pressing `No` or `Yes` does not actually close the message box.

### Describe the behavior you expected

The message box should be dismissed after pressing `No` or `Yes`.

### Notes

The modal dialog pops up immediately after the file contents have changed on disk, even if RStudio does not yet have focus. That may be related to the observed behavior.

**Comment by gtritchie** [comment]
This no longer repro's with 1.2.804.
