### ISSUE TITLE
Error message about context mismatch occasionally

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2258]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.358
    OS Version      : Ubuntu 17.10
    R Version       : 3.4.2

### Steps to reproduce the problem

1. Run `rstudio` from the command line (in a terminal)
2. Use the console or the menu, or just wait. I haven't found a way to consistently reproduce it—it just seems to happen, even without any activity.

### Describe the problem in detail

There doesn't appear to be any impact on RStudio. The IDE performs fine, as expected. However, every so often, a message appears in the terminal:
```
context mismatch in svga_sampler_view_destroy
```

Also, on 16.04, the same message appears, but first, at startup, this message appears (once)L
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```

### Describe the behavior you expected

No error.

Note that in 1.1.423 and 1.0.353, there are different messages in the console.
In 1.0.353 and 1.1.423:
```
	load glyph failed err=6 face=0x182e660, glyph=2798
```
And 1.0.353 ended with
```
QApplication::qAppName: Please instantiate the QApplication object first
```
So we've replaced one set of notifications with another.

**Comment by kevinushey** [comment]
Some Googling for

    context mismatch in svga_sampler_view_destroy

suggests that it's related to the use of video acceleration within VMware virtual machines. Is that true in your case? As far as I can tell there aren't any other user-facing issues other than the noisy diagnostic message, but we might want to confirm whether this issue pops up on non-virtualized hardware as well.

FWIW on my Ubuntu 16.04 VM the `XDG_RUNTIME_DIR` appears to be set:

```
> Sys.getenv("XDG_RUNTIME_DIR")
[1] "/run/user/1000"
```

so I wonder why this is missing on your machine.

**Comment by ronblum** [comment]
@kevinushey Thanks you—turning off video acceleration works. I'll check this on a real Windows machine (not a VM) to see if the issue appears there.

**Comment by ronblum** [comment]
I don't know what I was thinking--this is a Linux issue, not Windows. Closing.
