### ISSUE TITLE
Unexpected code diagnostics error (unmatched argument)

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#2259]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Windows 7 x64
    R Version       : 3.4.3

### Steps to reproduce the problem

Paste the following line in a script:
```r
`+`(x = 2, y = 2)
```

### Describe the problem in detail

Code Diagnostics display an error: `unmatched argument: 'x', 'y'`

### Describe the behavior you expected

No error message, since the arguments of the `+` function are really named `x` and `y`.

**Comment by kevinushey** [comment]
`+` is a primitive, so doesn't behave like 'regular' R functions. The arguments are not really called `x` and `y`:

```R
> `+`
function (e1, e2)  .Primitive("+")
```

But, in fact, R accepts any names if you invoke the function in this way:

```R
> `+`(alpha = 1, omega = 42)
[1] 43
```

Perhaps the diagnostics system could / should catch this case, but IMHO calling `+` with named arguments is 'wrong' in that it doesn't _really_ handle named arguments.

**Comment by jmcphers** [comment]
Closing since we've had no other reports of this and there is not consensus on the desired behavior.
