### ISSUE TITLE
Using F1 on a highlighted function name points to 127.0.0.1

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2260]
### System details

    RStudio Edition : Server
    RStudio Version : Multiple 1.1.4xx & 1.2.3xx 
    OS Version      : Ubuntu 16.04.3, RedHat 7.4, Centos 7.4
    R Version       : 3.4.2 and 3.4.3

### Steps to reproduce the problem

1. Open a new session and do not load the library readr
2. Type the readr function name `read_delim` in the console
3. Highlight `read_delim` and click F1
4. Click on `readr`in the Help pane

or

1. Open a new session and do not load the library readr
2. Type the package name `readr` in the console
3. Highlight `readr` and click F1
4. Click on `readr`in the Help pane

### Describe the problem in detail

When F1 is used to get help on a function or package, and the package name is clicked in the Help pane, the link is pointing to 127.0.0.1. As a result, a page in the web browser opens pointing at "http://127.0.0.1:8787/library/readr/help/read_delim" and displays the message
```
127.0.0.1 refused to connect.
```

### Describe the behavior you expected

Highlighting the function or package name (read_delim or readr), clicking on F1, and then clicking on the package name (readr) in the Help pane should bring up the help page for the function name in the help pane. Note that the library is first loaded (`library(readr)`), it works.

_[Reported by user to Support Team, issue 25726.]_

**Comment by jmcphers** [comment]
Still a problem in 1.3.625. We have a filter which is supposed to fix these up, but it's not catching this one.

https://github.com/rstudio/rstudio/blob/2f43b5dc93323f1a8a7b66255a9a0da470ba5389/src/cpp/session/modules/SessionHelp.cpp#L319-L331

**Comment by kevinushey** [comment]
It looks like the issue here is that R's help system prepends the localhost URL for these links:

https://github.com/wch/r-source/blob/212951d85d10efe20905a8dd0450e639d30be62a/src/library/utils/R/help.R#L126-L127

but we never fix up those URLs in the filter (we only fix relative URLs).

The simplest fix would likely be to just substitute mentions of 127.0.0.1 with the baseUrl in that filter.
