### ISSUE TITLE
"Error in isNamespaceLoaded" when pressing F1 on help topic completions

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2261]
### System details

    RStudio Edition: all
    RStudio Version : 1.1.383, 1.1.423, 1.2.359
    OS Version      : macOS 10.13.3
    R Version       : 

### Steps to reproduce the problem

1. Type `?plot.` at the console, and wait for help topic autocompletions to appear.
2. Select an autocompletion with the arrow keys, e.g. `plot.acf`
3. Press F1 to see help on the function.

![image](https://user-images.githubusercontent.com/470418/36606390-6be2ee20-1878-11e8-9981-2ddda2547009.png)

### Describe the problem in detail

No help appears, and the following error message is displayed at the console:

    Error in isNamespaceLoaded(pkg) : 
      attempt to use zero-length variable name

**Comment by ronblum** [comment]
Still a problem in Mac Desktop 1.1.430. (Works in 1.2.379-1.)

**Comment by ronblum** [comment]
Remarking as closed—awaiting another build to pick up this fix.

**Comment by ronblum** [comment]
Verified on Mac Desktop 1.1.441 and RStudio Server 1.1.441 on CentOS 7.4
