### ISSUE TITLE
Double-clicking on a word does not work in the Console and Packages panes

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2264]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.359
    OS Version      : 10.12.6 (Sierra), Ubuntu 16.04 & 17.10, Windows 10
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Type anything in the console
2. Double-click on a single word

### Describe the problem in detail

Double-clicking on a word in some of the panes does not highlight the word, but it works in others.
- Doesn't work: Console and Packages panes
- Works: Source, Viewer, and Help panes; R Markdown, View, and Terminal tabs; Git's "Review Changes" window

### Describe the behavior you expected

Double-clicking should highlight selected words in all cases. Note: on the Desktop products (but not Server via a web browser), triple-clicking—which selects the entire line—followed by double-clicking works in the Console pane.

**Comment by ColeWunderlich** [comment]
In addition to this, word highlighting does not work for certain themes even in source.  Themes include material and solarized dark.

**Comment by kevinushey** [comment]
Possibly related: https://github.com/ajaxorg/ace/pull/2827

If an Ace update will fix this, we may want to defer to v1.3 (unless we feel comfortable backporting the Ace patch)

**Comment by kevinushey** [comment]
@ColeWunderlich word highlight looks fine for me with those themes, e.g. from Solarized Dark:

<img width="119" alt="screen shot 2018-03-23 at 1 36 52 pm" src="https://user-images.githubusercontent.com/1976582/37852293-4e2ac6fe-2e9f-11e8-855f-ac97f7cd51d6.png">

Is your concern that the highlight is not distinct enough from the background color, or are you truly not seeing any word highlighting in your case?

**Comment by jmcphers** [comment]
I don't think this is Ace related; it regressed in 1.2 and we haven't done much Ace work in 1.2. It's also not a Qt issue; it repros on Server 1.2 but not Server 1.1. My suspicion is that it's related to changes we've made to event handling in 1.2.

**Comment by jmcphers** [comment]
Note that this doesn't fix the Packages pane (feel free to open a separate issue on that but I don't think that people care about selecting words there nearly as much)

**Comment by ColeWunderlich** [comment]
Sorry for the late reply.  Word highlighting was not working for me at all for certain themes.  After making changing the colors for  .ace_selected-word to be different from that of .ace_marker-layer I was able to get word highlighting.  Might be worth checking the included themes to make sure they don't have this problem, as I believe several of them do.

To me indicates its a problem with the theme configuration and not ace itself

**Comment by ronblum** [comment]
1) The original bug is fixed in console.
2) OK with Packages pane behavior, especially since clicking on it takes you to the Help page which has the name—and highlighting + copy and paste works there.
3) I'll open a new issue for the Source pane double clicking theme problem.

**Comment by kevinushey** [comment]
FWIW the highlight is actually there, it's just way too faint:

![screen shot 2018-08-08 at 1 10 09 pm](https://user-images.githubusercontent.com/1976582/43861686-703ace68-9b0c-11e8-81d3-ffdbcad56f1f.png)

so this is more an issue with the highlight rules for Solarized Dark specifically.
