### ISSUE TITLE
Cursor Text Sync Issue in Console

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#2266]
### System details

    RStudio Edition : Desktop
    RStudio Version: 1.1.419
    OS Version: CentOS 7 
    R Version: v3.4.3 

### Steps to reproduce the problem

1. Open _RStudio_ on CentOS 7
2. Begin typing in the _Console_ portion of _RStudio_
3. Note that the cursor "lags" to a further point than where the text is. 

![rstudio-cursor-lag](https://user-images.githubusercontent.com/833642/36613821-440d28e8-18a0-11e8-9899-09220e2a4329.JPG)

Live:

![eo16e-ref12](https://user-images.githubusercontent.com/833642/36770707-78edd642-1c11-11e8-95ef-bab9aef19d26.gif)

### Describe the problem in detail

The cursor when typing in CentOS 7 unexpected becomes unsync'd with the text that is enabled. Switching the font away from `Courier` seems to resolve the issue.

### Describe the behavior you expected

The cursor should be in-line with the font. 

----------

Is there anyway to _set_ a font for multiple _RStudio_ instances? 

I've looked in:

```bash
~/.rstudio-desktop/monitored/user-settings/user-settings
```

But, there doesn't seem to be an `editor-font` option.

**Comment by ronblum** [comment]
I'm able to reproduce this with some fonts on CentOS 7.4 using RStudio Desktop 1.2.364, though not 1.1.423. These fonts have the problem: Clean, Courier, Cursor, and Fixed. Than you @coatless for the bug report!

**Comment by ronblum** [comment]
The issue just occurred for me on Mac using RStudio Desktop Pro 1.2.370-1. I haven't been able to find a specific reason for it.

**Comment by coatless** [comment]
One of our techs came up with an intermediary workaround for the font bug on CentOS 7. His fix was to set a font via a `desktop.ini` configuration and rolling it out to users in a `~/.bash_profile` as there wasn't an option in `~/.rstudio-desktop/monitored/user-settings/user-settings`.


1. Create:

```bash
touch ~/.config/Rstudio/desktop.ini
```

2. Enter into the file:

```bash
[General]
font.fixedWidth=Liberation Mono
```

**Comment by kevinushey** [comment]
Normally, RStudio should only allow you to select monospaced fonts (as the editor instances used by RStudio only support monospaced fonts). How did you end up with Courier as your editor font? (Was it available as a font selection choice that was explicitly chosen, or was it selected through some other means?)

**Comment by coatless** [comment]
@kevinushey the font was selected upon opening _RStudio_. It is still an _explicit_ font choice under Code appearances.  Here is the font list shown to the user:

![img_1042](https://user-images.githubusercontent.com/833642/36910876-87166926-1e07-11e8-8315-87ac39154472.JPG)

We've only now set a fixed font to Liberation Mono.

**Comment by coatless** [comment]
@kevinushey for the record, `Courier` _is_ monospaced. c.f.

https://en.wikipedia.org/wiki/Courier_(typeface)

**Comment by kevinushey** [comment]
With a plain installation of RStudio on a CentOS 7 box, I don't see this issue. In fact, I don't see the variants of Courier that you have installed, either:

![screen shot 2018-03-15 at 3 00 13 pm](https://user-images.githubusercontent.com/1976582/37493258-a22b0eb0-2861-11e8-855d-6c41767721dd.png)

The 10 pitch Courier font does seem to render correctly in my case. I think in the images you show the font is _not_ actually Courier; rather, RStudio is attempting to set that font but is perhaps failing to do so, and falling back to a non-monospace font.

**Comment by kevinushey** [comment]
If I change to a font that doesn't exist, for example, changing the contents of `~/.config/RStudio/desktop.ini` to contain the fictional font:

```
[General]
font.fixedWidth=Alien Samba
```

then the attempt to set a fixed-width font fails, and then the default serif font is used instead.

**Comment by coatless** [comment]
Is there anyway that I could quickly determine the font _RStudio_ is providing?

**Comment by kevinushey** [comment]
If you right click on some text in the RStudio console history and click `Inspect Element` in the context menu, you should get a web inspector that shows you what styles are being applied to that text. I imagine you're seeing a font being applied that doesn't actually exist on your system, and so that is failing.
