### ISSUE TITLE
Terminal duplicates prompt when prompt is complex (e.g., liquid_prompt)

### ISSUE THREAD

**Issue by ccg** [rstudio/rstudio#2267]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.365
    OS Version      : macOS X 10.12.67
    R Version       : `R version 3.4.1 (2017-06-30)`

### Steps to reproduce the problem

Install liquid_prompt (https://github.com/nojhan/liquidprompt). `cd` into a directory that is inside a Git repository. After approximately one second of time, a second/duplicate prompt appears.

### Describe the problem in detail

![screen shot 2018-02-23 at 5 35 57 pm](https://user-images.githubusercontent.com/59996/36621904-15c2649c-18c0-11e8-9ae8-3a55ecc66f45.png)

### Describe the behavior you expected

One prompt. :) I haven't observed this behavior in iTerm, Terminal.app, or the IntelliJ integrated terminal, so it appears to be specific to RStudio IDE's embedded terminal.

**Comment by gtritchie** [comment]
Go into Tools/Global Options/Terminal and try turning off `Local terminal echo`, and then close existing RStudio terminals. See if newly opened terminals still have the problem.

**Comment by ccg** [comment]
The behavior is the same with `Local terminal echo` disabled. I even restarted the IDE, but the duplicate-prompt issue remained.

**Comment by gtritchie** [comment]
Ok, try turning off "Save and Restore Environment Variables", instead. You can turn "Local terminal echo" back on. Again, close existing terminals (via closing the terminal tab with "x") and start a new terminal to see if this helps.

Some terminal settings are preserved in existing terminals even if you restart the IDE; don't recall offhand is this is one of them but best to be sure for the experiment.

**Comment by ccg** [comment]
Bingo! That fixed it. Thanks!

![screen shot 2018-02-24 at 10 52 44 pm](https://user-images.githubusercontent.com/59996/36638254-7c0e98e2-19b5-11e8-8d88-6459de28df27.png)

**Comment by gtritchie** [comment]
Be good to investigate why Save and Restore Environment Variables is having this issue.
