### ISSUE TITLE
RStudio browser did not render xaringan Markdown HTML output properly

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#2269]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      :  Windows 10 Pro
    R Version       :  3.4.3

### Steps to reproduce the problem

Download this file then Knit to HTML 
https://github.com/yihui/xaringan/blob/2506ae5bfe5f1f1a18a376342e8f9e02c8492227/inst/rmarkdown/templates/xaringan/skeleton/ghoul.Rmd

### Describe the problem in detail

On RStudio preview window

![rstudio_xaringan_01](https://user-images.githubusercontent.com/6590141/36636643-7928d236-197f-11e8-87b2-2e7cab3cb9f4.PNG)
![rstudio_xaringan_02](https://user-images.githubusercontent.com/6590141/36636644-79465f2c-197f-11e8-800b-0b1a8402c27f.PNG)

### Describe the behavior you expected

On Firefox browser 

![rstudio_xaringan_01_ff](https://user-images.githubusercontent.com/6590141/36636660-b4ef511e-197f-11e8-88fc-6f643050af7c.PNG)
![rstudio_xaringan_02_ff](https://user-images.githubusercontent.com/6590141/36636661-b50f4adc-197f-11e8-8444-d1bcf5fad566.PNG)

1. The output of sessionInfo() 

```
Packages ------------------------------------------------------------------------------------
 package    * version    date       source                             
 backports    1.1.2      2017-12-13 CRAN (R 3.4.3)                     
 base       * 3.4.3      2017-11-30 local                              
 compiler     3.4.3      2017-11-30 local                              
 curl         3.1        2017-12-12 CRAN (R 3.4.3)                     
 datasets   * 3.4.3      2017-11-30 local                              
 devtools     1.13.5     2018-02-18 CRAN (R 3.4.3)                     
 digest       0.6.15     2018-01-28 CRAN (R 3.4.3)                     
 evaluate     0.10.1     2017-06-24 CRAN (R 3.4.1)                     
 git2r        0.21.0     2018-01-04 CRAN (R 3.4.3)                     
 graphics   * 3.4.3      2017-11-30 local                              
 grDevices  * 3.4.3      2017-11-30 local                              
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)                     
 httr         1.3.1      2017-08-20 CRAN (R 3.4.1)                     
 jsonlite     1.5        2017-06-01 CRAN (R 3.4.1)                     
 knitr        1.20       2018-02-20 Github (yihui/knitr@1e9a4d5)       
 magrittr     1.5.0      2017-12-27 Github (tidyverse/magrittr@0a76de2)
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                     
 methods    * 3.4.3      2017-11-30 local                              
 R6           2.2.2      2017-06-17 CRAN (R 3.4.1)                     
 Rcpp         0.12.15    2018-01-20 CRAN (R 3.4.3)                     
 rmarkdown    1.8.10     2018-02-23 Github (rstudio/rmarkdown@1ccf6a0) 
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.4.3)                     
 rstudioapi   0.7        2017-09-07 CRAN (R 3.4.2)                     
 stats      * 3.4.3      2017-11-30 local                              
 stringi      1.1.6      2017-11-17 CRAN (R 3.4.2)                     
 stringr      1.3.0.9000 2018-02-20 Github (tidyverse/stringr@097c0c0) 
 tools        3.4.3      2017-11-30 local                              
 utils      * 3.4.3      2017-11-30 local                              
 withr        2.1.1.9000 2018-02-23 Github (jimhester/withr@5d05571)   
 xaringan     0.6        2018-02-25 Github (yihui/xaringan@6ebd932)    
 xfun         0.1        2018-01-22 CRAN (R 3.4.3)                     
 yaml         2.1.16     2017-12-12 CRAN (R 3.4.3)
```

**Comment by dfalty** [comment]
Thanks for the report! Are there any errors in the console when you encounter this? Right click -> Inspect -> Console

**Comment by jmcphers** [comment]
The released version of RStudio for Windows uses QtWebKit, which is an older web rendering engine that doesn't support newer Web standards. You might also try our daily build, which uses a much newer rendering engine:

https://dailies.rstudio.com/

**Comment by tungmilan** [comment]
Thank you guys!

@dfalty : here you go
![capture](https://user-images.githubusercontent.com/6590141/36918803-eccc4d3c-1e0f-11e8-8b91-37a0d68259ef.PNG)

@jmcphers : I stopped using daily build after the [scaling issue](https://github.com/rstudio/rstudio/issues/2051). Was it fixed already?

**Comment by kevinushey** [comment]
I'm seeing the same thing. I'll take a look.

**Comment by tungmilan** [comment]
Working now. Thanks @kevinushey !
