### ISSUE TITLE
Clean and Build Bug?

### ISSUE THREAD

**Issue by PJOssenbruggen** [rstudio/rstudio#2270]
I have filed the following request: https://support.rstudio.com/hc/en-us/requests/25806

Given the nature of my problem, I feel that there is a bug. 

### System details

    RStudio Edition : <Desktop>
    RStudio Version : 1.1.383
    OS Version      : 10.13.3
    R Version       : 3.4.3

**### Steps to reproduce the problem**: 
I execute a Clean and Rebuild command.

**#### Describe the problem in detail:** 
==> R CMD INSTALL --preclean --no-multiarch --with-keep.source CF.2.24

* installing to library ‘/Users/PJO/Library/R/3.4/library’
* installing *source* package ‘CF’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in aes(x = gdpPercap, y = lifeExp, size = pop, color = continent,  : 
  could not find function "aes"
Error : unable to load R code in package ‘CF’
ERROR: lazy loading failed for package ‘CF’
* removing ‘/Users/PJO/Library/R/3.4/library/CF’
* restoring previous ‘/Users/PJO/Library/R/3.4/library/CF’

Exited with status 1.

**### Describe the behavior you expected.** 

I have written a R package that has run successfully!  But now, it will not build and reload or pass the devtools::check() as it has in the past. Strangely, while my package fails to rebuild, it produces a vignette consisting of three animations with knitr. In addition, I can produce animations with R. In other words, I don't use Clean and Build. As you can see, it cannot find "aes." It is installed:

devtools::install_github("dgrtwo/gganimate")

<!-- Depending on the problem, the following may also be helpful

**1. The output of sessionInfo()** 
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] colorspace_1.3-2  scales_0.5.0.9000 compiler_3.4.3    lazyeval_0.2.1    plyr_1.8.4        tools_3.4.3      
 [7] pillar_1.1.0      gtable_0.2.0      yaml_2.1.16       tibble_1.4.2      Rcpp_0.12.15      ggplot2_2.2.1    
[13] grid_3.4.3        rlang_0.2.0.9000  munsell_0.4.3    
> 
 **2. The R code in question:**
animation 
ggplot2
gganimate
**3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report**
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1756332/diagnostics-report.txt)

Thank you,

Paul

**Comment by dfalty** [comment]
@PJOssenbruggen If this also happens from the command line then it's not an RStudio specific issue. This issue tracker is for reporting bugs in RStudio. You might try asking your question on our new community forum:

https://community.rstudio.com/

**Comment by PJOssenbruggen** [comment]
Thanks, I will try that.

On Feb 28, 2018, at 1:43 PM, Darby Hadley <notifications@github.com<mailto:notifications@github.com>> wrote:

Caution - External Email
________________________________

@PJOssenbruggen<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pjossenbruggen&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=t4y9-xOkKjSY-jkjmlPkNQ&m=1aUozwUxpMDCbWYkInQRnq0i2Rl5bU-qXighmNhQ-rA&s=Mh3MJsCLkywlXiuQvUDVzP6_ysqez8wxd3XOMrE4_Lg&e=> If this also happens from the command line then it's not an RStudio specific issue. This issue tracker is for reporting bugs in RStudio. You might try asking your question on our new community forum:

https://community.rstudio.com/<https://urldefense.proofpoint.com/v2/url?u=https-3A__community.rstudio.com_&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=t4y9-xOkKjSY-jkjmlPkNQ&m=1aUozwUxpMDCbWYkInQRnq0i2Rl5bU-qXighmNhQ-rA&s=d6TMQ_pY6r7HP5n6qTgSStnHVZCNr2I74VOr2yC9bWU&e=>
