### ISSUE TITLE
Auto-completion can not remove leading non-latin characters properly.

### ISSUE THREAD

**Issue by ukyoi** [rstudio/rstudio#2271]
Thanks for reading this issue report and please forgive my poor English. I found this issue with Chinese characters but I presume it is reproducible with all CJKV characters, even other non-latin characters.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.430 beta
    OS Version      : macOS High Sierra 10.13.3
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Create a variable called "一二三" (means "OneTwoThree" in Chinese) in console: `一二三 <- 123`
2. Insert "一二" ("OneTwo") in console.
3. Press Tab to trigger auto-completion.

### Describe the problem in detail
The insertion line becomes `一二一二三` ("OneTwoOneTwoThree").

### Describe the behavior you expected
The line is expected to be `一二三` (the leading "一二" should be removed).

**Comment by dfalty** [comment]
Thanks for the report! I can also reproduce this on 1.1.430 (Mac).
