### ISSUE TITLE
Unhelpful error when connecting to databases

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#2276]
### System details

    RStudio Edition : RSP
    RStudio Version : 1.1.143
    OS Version      : Linux
    R Version       : 3.4.0

### Steps to reproduce the problem
Connect to Teradata and click on a database for which you do not have permissions.

### Describe the problem in detail
The driver will return a helpful error in the console, but the IDE will return an unhelpful error in dialog.

### Describe the behavior you expected
I would expect either (1) nothing happens; or (2) you get a warning; or (3) the driver error is displayed in the console. I prefer (3).

<img width="544" alt="screen shot 2018-02-20 at 5 15 56 pm" src="https://user-images.githubusercontent.com/7519295/36697549-607c9960-1b15-11e8-92be-7b376d0ed2c7.png">

**Comment by jmcphers** [comment]
Do you have a self-contained example? (We don't have a Teradata database handy...)

**Comment by nwstephens** [comment]
Can no longer reproduce on current software stack. Updated versions of driver, DBI, odbc, and IDE no longer produce the problem. My suspicion was that either updated driver or the driver configuration fixed the issue. Closing the issue.
