### ISSUE TITLE
Please add an option to turn off --as-cran on checking packages

### ISSUE THREAD

**Issue by halpo** [rstudio/rstudio#2277]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      :  Windows Server 2012 R2
    R Version       :  3.4.3

### Steps to reproduce the problem

Check package without internet connectivity

### Describe the problem in detail

When operating in an environment without internet access, or limited internet, such as behind a firewall, checking a package takes an excessively long time as the check tries to contact CRAN and BioConductor multiple times, and each must timeout for the check to continue.

This would easily be fixable with passing `cran=FALSE` to the `devtools::check()` call however there is currently no way to do this.

The natural workaround would be to put `_R_CHECK_CRAN_INCOMING_=FALSE` in the `~/.R/check.Renviron` file however it appears that since `devtools::check` passes --no-environ to the check command these definitions are not loaded.

### Describe the behavior you expected

It would be fantastic if there were an option in the build tools to enable or disable the cran option of `devtools::check`.
Ideally all the arguments for check could be specified, as in my situation I also have a need to change the temp directory.

**Comment by stufield** [comment]
Any movement on this enhancement to `devtools::check`? I have a very similar issue, though in my case I simply do not need the rigor of "as-cran" in the check, yet I  would still like to use the RStudio `build` pane (and its convenient `Crtl+Shift+E` shortcut).

**Comment by kevinushey** [comment]
IIUC `devtools` now sets `_R_CHECK_CRAN_INCOMING_=FALSE` by default so this should no longer be an issue.

**Comment by cderv** [comment]
Hi, 
Sorry to jump on this issue but I wanted to share I still encounter this issue in RSP when clicking on the Check button in build panel. 

The printed output shows that `_R_CHECK_CRAN_INCOMING = FALSE` but it seems to still try to go online. 

```sh 
devtools::check()

(...)

── Checking ─────────────────────────────────────── poker.utils ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
● _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
● _R_CHECK_CRAN_INCOMING_           : FALSE
● _R_CHECK_FORCE_SUGGESTS_          : FALSE
── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/home/bureau.si.interne/dervieuxchr/devR/poker.utils.Rcheck’
* using R version 3.5.1 (2018-07-02)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘poker.utils/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘poker.utils’ version ‘0.1.3’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ...Warning: unable to access index for repository https://CRAN.R-project.org/src/contrib:

(...)

```

When running `devtools::check()` in console, it does not happen. 

In which version of RStudio does the fix appear ? we have 1.2.1335-1
Or is it directly in devtools ? Which library the Build panel is using ? is it the user lib ? 

Sorry if that was not the place to ask - I am not sure to understand why the difference between build pane and console and how to test it is ok. It seems fixed from the label but not sure to have the fix.

**Comment by kevinushey** [comment]
Doesn't this check always occur?

Maybe `devtools::check()` forces the R repositories off so that no internet access is tried in that case either?

**Comment by cderv** [comment]
I see what you mean now... 

I think `devtools::check` in my R console works and this package dependencies check is working because my `repos` option set in `Rprofile.site` on my offline servers is respected. 

This is not the case in the build pane I guess because RStudio execute the command in a R vanilla session, so no config file is load (user or site wide)
https://github.com/rstudio/rstudio/blob/d6a8a94530818442c03c3b3acaf38095dc16c394/src/cpp/session/modules/build/SessionBuild.cpp#L1005

it means also that the `r-cran-repos` configuration in RSP is not respected also as it is set to our internal CRAN
https://docs.rstudio.com/ide/server-pro/r-sessions.html#cran-repositories

I guess it is using the R default CRAN repos option. 

What do you think ? 
It may be interesting to open a new issue - I always thought the issue was linked to CRAN check, and I was mislead I think.

**Comment by kevinushey** [comment]
I think it would be worthwhile opening a new issue.
