### ISSUE TITLE
Compiling RStudio

### ISSUE THREAD

**Issue by ZarulSaurus** [rstudio/rstudio#2281]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : The latest one in Github (sorry, Im not sure)
    OS Version      : Ubuntu 16.04.3 LTS
    R Version       : 3.2.3 (Wooden Christmas-Tree)

Hello RStudio community,

I tried to compile RStudio desktop in a Linux permanent boot (Ubuntu 16.04.3 LTS, Xenial). I got the source code from Github. I followed the instructions in INSTALL; I ran all the relevant scripts for Linux dependencies (Qt, Boost and debian dependencies. Then I followed the rest of the commands; cmake, make install~.

From my previous usage of rstudio, I can just type in 'rstudio' in the command and RStudio would appear; it didn't here. The icon did appear in the the application list, but when I click, the icon would appear on the docker for a while, then it would disappear.

The rstudio software was stored in /usr/local/lib/rstudio/bin/rstudio, so I just typed it it the command line. It gave an error (libQt5WebEndigneWidgets.so.5: cannot open shared object file: No such file or directory). Strangely, I did notice that a Qt5.10.0 directory was created in my home directory. When I listed Qt5.10.0/5.10.0/gcc_64/lib, that missing file was there. I tried to append ~/Qt5.10.0/5.10.0/gcc_64 in my PATH, but /usr/local/lib/rstudio/bin/rstudio still gave me an error message.

I actually used the live boot on another Linux machine. When I mount the hard drive and used RStudio inside it, it worked.

Thank you.

**Comment by jmcphers** [comment]
This sounds like a path issue with QtWebEngine. It should be resolved in the latest master; let us know if you don't see it.

If you want to compile RStudio yourself, we recommend doing so using one of the Docker containers that we've set up. This should always work and will spare you the effort of trying to get your system set up. Instructions here:

https://github.com/rstudio/rstudio/wiki/Building-with-Docker
