### ISSUE TITLE
macOS display switching leaves blurred UI

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#2282]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.359
    OS Version      : 10.13.3 
    R Version       : 3.4.3

### Steps to reproduce the problem

Unclear. I saw this when transitioning from the office to home. I use external monitors in both environments, but they do not have the same resolutions.

I think I just made this happen in the following way:

1. Unplug external monitor. Start a new RStudio session on the main laptop screen.
2. Plug in external monitor; the RStudio session automatically transitioned to the external monitor.
3. On the external monitor, the fonts are blurred until a window resize is performed.

### Describe the problem in detail

The UI is blurred (not crisp). Command-+/-/0 are insufficient to reset. Things get crisp again upon an explicit resize of the window.

### Describe the behavior you expected

Here is an image showing a "good" UI on the right over a "blurred" UI on the left.
![screen shot 2018-02-27 at 8 41 20 am](https://user-images.githubusercontent.com/362187/36732125-d29b2680-1b9a-11e8-8e62-4ce9ebc2cf0f.png)

The "good" UI was blurred before performing a resize.

Here is that same shot after resizing the "blurred" window (dragging the window border just a pixel):
![screen shot 2018-02-27 at 8 53 53 am](https://user-images.githubusercontent.com/362187/36732453-dbb0f6b8-1b9b-11e8-9bc5-0f5abac742e0.png)

Here are the appearance preferences (defaults):
![screen shot 2018-02-27 at 8 48 04 am](https://user-images.githubusercontent.com/362187/36732174-f650e740-1b9a-11e8-8e0b-c1bee92ce827.png)

**Comment by ronblum** [comment]
Not a problem in 1.1.227, a pre-QtWebEngine build, so likely an issue with that.

**Comment by kevinushey** [comment]
We could probably work around this by forcing an explicit resize when the window regains focus.

**Comment by adamhospodka** [comment]
Hey guys 🖐 
I think I figured it out. I went to _Settings / Appearance_ and switched Zoom to 100 %, but resized back the font.
Hope it works for you too

**Comment by gregmacfarlane** [comment]
The @adamhospodka doesn't work for me; only solution I've identified is to quit and reopen.

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by aronatkins** [comment]
I just tried to test this from here, and the external monitor I'm currently using doesn't trigger the same problems that I originally reported. The laptop is also different than the one I was using when I filed this issue.

I've tried both the Electron and Qt builds and do not see any text blurring as the RStudio UI switches from the laptop to the external screen.

**Comment by ronblum** [comment]
Thanks @aronatkins! Closing this as fixed by Electron. If anyone else using builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) continues to run into this issue, please let us know!
