### ISSUE TITLE
Mercurial commands which launch external programs fail in Terminal

### ISSUE THREAD

**Issue by AB-Kent** [rstudio/rstudio#2286]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.423
    OS Version      :  Windows 10 Enterprise
    R Version       : 3.4.3

### Steps to reproduce the problem
In the Terminal tab, run a Mercurial command that itself runs an external program.

### Describe the problem in detail
The mercurial commands `hg ci` (without `-m`) and `hg vdiff` both open external programs (editor and visual diff program, respectively). Running either one in the Terminal tab gives the error
`abort: The system cannot find the file specified`

The programs are configured in Mercurial.ini as
cmd.vdiff = "C:\Program Files (x86)\Beyond Compare 4\BComp.exe"
editor = "C:\Program Files\Sublime Text 3\subl.exe" --wait

FWIW I have tried changing to short paths for both programs with no effect.

### Describe the behavior you expected
Mercurial runs the desired external program.

**Comment by gtritchie** [comment]
What RStudio terminal-type are you using? Command Prompt, PowerShell, Git-Bash, or Windows Services for Linux?
![2018-02-28_09-22-51](https://user-images.githubusercontent.com/10569626/36802155-025493a6-1c69-11e8-95da-55c9c1c79965.png)

**Comment by PKI-Kent** [comment]
It is Command Prompt (64-bit) with settings exactly as you show.

**Comment by PKI-Kent** [comment]
@gtritchie No. I'm running the latest Mercurial (4.5.2). Below is a traceback of the error; it is failing in subprocess.call().

```
>hg version
Mercurial Distributed SCM (version 4.5.2)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2018 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>hg ci --traceback
Traceback (most recent call last):
  File "mercurial\scmutil.pyc", line 154, in callcatch
  File "mercurial\dispatch.pyc", line 314, in _runcatchfunc
  File "mercurial\dispatch.pyc", line 918, in _dispatch
  File "mercurial\dispatch.pyc", line 673, in runcommand
  File "mercurial\dispatch.pyc", line 926, in _runcommand
  File "mercurial\dispatch.pyc", line 915, in <lambda>
  File "mercurial\util.pyc", line 1195, in check
  File "mercurial\util.pyc", line 1195, in check
  File "hgext\mq.pyc", line 3583, in mqcommand
  File "mercurial\util.pyc", line 1195, in check
  File "mercurial\commands.pyc", line 1525, in commit
  File "mercurial\commands.pyc", line 1602, in _docommit
  File "mercurial\cmdutil.pyc", line 3135, in commit
  File "mercurial\commands.pyc", line 1600, in commitfunc
  File "hgext\mq.pyc", line 3486, in commit
  File "mercurial\localrepo.pyc", line 142, in wrapper
  File "mercurial\localrepo.pyc", line 1859, in commit
  File "mercurial\cmdutil.pyc", line 897, in <lambda>
  File "mercurial\cmdutil.pyc", line 3346, in commiteditor
  File "mercurial\cmdutil.pyc", line 3377, in commitforceeditor
  File "mercurial\ui.pyc", line 1450, in edit
  File "mercurial\ui.pyc", line 1477, in system
  File "mercurial\ui.pyc", line 1489, in _runsystem
  File "mercurial\util.pyc", line 1178, in system
  File "subprocess.pyc", line 168, in call
  File "subprocess.pyc", line 390, in __init__
  File "subprocess.pyc", line 640, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
abort: The system cannot find the file specified
```

**Comment by gtritchie** [comment]
As a test, if you run notepad from the terminal, does it launch?

**Comment by PKI-Kent** [comment]
My configured editor is Sublime Text. I can run it from terminal using the same command configured in Mercurial.ini. For example the second command below opens Helpers.R in the editor.
```
>hg config ui
ui.editor="C:\Program Files\Sublime Text 3\subl.exe" --wait
ui.merge=kdiff3
ui.style=C:\hgext\styles\style.kent
ui.formatted=True
ui.interactive=False

>"C:\Program Files\Sublime Text 3\subl.exe" --wait Helpers.R
```

**Comment by gtritchie** [comment]
Ok, just wanted to see if there was a more general problem with running desktop apps from the terminal. Given you can launch Sublime Text from the RStudio terminal, I guess not.

**Comment by jmcphers** [comment]
Since the error was `abort: The system cannot find the file specified`, it seems very probable that this is an issue with the PATH environment variable. Can you share (a) the path as it's seen from a regular command shell, (b) the path as it's seen from R (i.e. `Sys.getenv("PATH")`), and (c) the path as it's seen from RStudio's Terminal?

**Comment by AB-Kent** [comment]
This is working for me now, with RStudio 1.2.5001 and R 3.6.3. The PATH variables are identical except RStudio prefixes multiple copies of `C:\Program Files\R\R-3.6.1\bin\x64` in both Console and Terminal, and suffixes `C:/Program Files/Git/bin;C:/Program Files/RStudio/bin/msys-ssh-1000-18` in Terminal.

Here are the complete PATH variables:

a) Windows Command shell
`C:\Program Files\R\R-3.6.1\bin\x64;C:\Program Files\R\R-3.6.1\bin\x64;C:\Program Files\Microsoft MPI\Bin\;C:\RTools\bin;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Project\(misc)\tiff-4.0.9\tools;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files (x86)\hgview;C:\Program Files (x86)\IronPython 2.7;C:\Program Files (x86)\RBTools\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Sublime Text 3;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Git LFS;C:\Program Files\Mercurial\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\PROGRA~2\Groovy\Groovy-2.5.8\bin;C:\Users\kjohnson\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Mercurial;C:\Users\kjohnson\AppData\Roaming\npm;C:\Users\kjohnson\AppData\Local\Pandoc\`

b) R Console
`"C:\\Program Files\\R\\R-3.6.1\\bin\\x64;C:\\Program Files\\R\\R-3.6.1\\bin\\x64;C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\RTools\\bin;C:\\Program Files\\Python37\\Scripts\\;C:\\Program Files\\Python37\\;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\PuTTY\\;C:\\Project\\(misc)\\tiff-4.0.9\\tools;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\bin;C:\\Program Files (x86)\\GnuWin32\\bin;C:\\Program Files (x86)\\Graphviz2.38\\bin;C:\\Program Files (x86)\\hgview;C:\\Program Files (x86)\\IronPython 2.7;C:\\Program Files (x86)\\RBTools\\bin;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files\\Sublime Text 3;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git LFS;C:\\Program Files\\Mercurial\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\PROGRA~2\\Groovy\\Groovy-2.5.8\\bin;C:\\Users\\kjohnson\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Mercurial;C:\\Users\\kjohnson\\AppData\\Roaming\\npm;C:\\Users\\kjohnson\\AppData\\Local\\Pandoc\\"`

c) RStudio Terminal
`C:\Program Files\R\R-3.6.1\bin\x64;C:\Program Files\R\R-3.6.1\bin\x64;C:\Program Files\R\R-3.6.1\bin\x64;C:\Program Files\Microsoft MPI\Bin\;C:\RTools\bin;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Project\(misc)\tiff-4.0.9\tools;C:\Program Files\dotnet\;C:\Program Files\MicrosoftSQL Server\130\Tools\Binn\;C:\Program Files (x86)\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files (x86)\hgview;C:\Program Files (x86)\IronPython 2.7;C:\Program Files (x86)\RBTools\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Sublime Text 3;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Git LFS;C:\Program Files\Mercurial\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\PROGRA~2\Groovy\Groovy-2.5.8\bin;C:\Users\kjohnson\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Mercurial;C:\Users\kjohnson\AppData\Roaming\npm;C:\Users\kjohnson\AppData\Local\Pandoc\;C:/Program Files/Git/bin;C:/Program Files/RStudio/bin/msys-ssh-1000-18`

**Comment by jmcphers** [comment]
Thanks for following up (and sharing $PATH)! If you can longer repro this (and we've never been able to), we will close it for now. Very unsatisfying, though.!
