### ISSUE TITLE
Cannot run shiny app externally in browser, but works in viewer pane and window options.

### ISSUE THREAD

**Issue by adamBirenbaum** [rstudio/rstudio#2287]
Unable to run a shiny app externally in the browser; an empty chrome (my default browser) window opens upon running.  The viewer pane and windows options work as expected.

Issue is identical to one posted in Dec. 2017 [https://github.com/rstudio/rstudio/issues/1851](https://github.com/rstudio/rstudio/issues/1851), but it was was closed after @yihui  fixed their issue by upgrading from MacOS 10.13.1 to 10.13.2.  We were forced to upgrade our machines to the latest 10.13.3 last week which is when I started to see the problem.

Issue persists even for basic test apps as tried by @yihui.

### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.383
    OS Version      :   MacOS 10.13.3
    R Version       :   3.4.1

**Comment by dfalty** [comment]
Thanks for the report. Will need someone with 10.13.3 to look into this.

**Comment by jmcphers** [comment]
We've overhauled the MacOS integration in 1.2; none of the Cocoa/WebKit code in this path exists any more. The latest stable build (1.2.5019) should resolve this problem; let us know if it doesn't!
