### ISSUE TITLE
RStudio hangs during RMarkdown check without internet access

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#2288]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.140
    OS Version      :  CentOS 7
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Disconnect from the internet for over a two weeks after installing _RStudio_ and `rmarkdown`.
2. Try creating a new _RMarkdown_ document using  File => New File => R Markdown
3. Watch it hang. 

![img_1544](https://user-images.githubusercontent.com/833642/36756807-b309a446-1bd5-11e8-934f-ec8a6bb59f82.JPG)

### Describe the problem in detail

The client crashes when trying to open a new _RMarkdown_ notebook when offline for a prolonged amount of time. 

### Describe the behavior you expected

If _RStudio_ is not able to connect to the internet, this check should not be run or it should not time out causing the client to crash.

**Comment by kevinushey** [comment]
I'm guessing you can trigger the same behavior with something like:

```
available.packages()
```

as that can hang when there is no internet connectivity. I'm not sure if there's a good way for us to handle this (or check if the system has internet connectivity altogether)

**Comment by coatless** [comment]
@kevinushey we're running into this issue in our computer-based testing facility (CBTF). The facility blocks outbound connections unless they fall in certain use cases. I'll test this out tomorrow and get back to you.

**Comment by coatless** [comment]
So, it seems like the `available.packages()` code bugs out on _first_ run. The subsequent run in the same session returns an error as expected. 

![img_8354](https://user-images.githubusercontent.com/833642/36859599-7e8804fe-1d44-11e8-84f1-eeb8b8b9a510.JPG)

If I use a different document type initially and then switch it to a `.Rmd`, e.g. `.R` to `.Rmd`, the inline code engine works. However, pressing `Knit` returns the hang issue.

After a prolonged time, I slowly start to get prompts from _RStudio_ about mirror issues:

![img_2057](https://user-images.githubusercontent.com/833642/36859829-433e0f46-1d45-11e8-9fc9-7a532617b640.JPG)

With this being said, it looks like some request managed to get through at some point because a prompt is being issued that packages are out-of-date? 

![img_9215](https://user-images.githubusercontent.com/833642/36859796-183562cc-1d45-11e8-9e47-f4aa6d9287e0.JPG)

**Comment by jmcphers** [comment]
> So, it seems like the available.packages() code bugs out on first run. The subsequent run in the same session returns an error as expected.

This is somewhat expected because of the way available.packages() works (it caches its results since it's such an expensive call). In the years since this issue was opened we've implemented caching on a lot of the parts of the IDE that handle this list, so hopefully most spots are better, but ultimately if your environment causes `available.packages()` to hang there's probably going to be a hang in spots in RStudio too.
