### ISSUE TITLE
R code execution error: there is no .Internal function 'strrep'

### ISSUE THREAD

**Issue by elgalu** [rstudio/rstudio#2291]
### System details

    RStudio Edition : Community
    RStudio Version : rstudio-server-1.1.423-amd64.deb
    OS Version      : Ubuntu 16.04 (in Dockerfile)
    R Version       : R version 3.4.2 (2017-09-28)

### Steps to reproduce the problem
1. Install the above versions in a Dockerfile
2. Install JupyterHub and https://github.com/Viasat/nbrsessionproxy
3. Start R Studio from the Jupyter Notebook

### Describe the problem
Got error:
```
(R code execution error) [errormsg=Error in .Internal(strrep(x, as.integer(times))) : 
there is no .Internal function 'strrep'

OCCURRED AT: rstudio::core::Error 
rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**,
 rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) 
/home/ubuntu/rstudio/src/cpp/r/RExec.cpp:159; LOGGED FROM: 
rstudio::core::Error rstudio::r::session::initialize() 
/home/ubuntu/rstudio/src/cpp/r/session/RSession.cpp:402
```

Maybe is a known issue with my version of R ? else I can provide more logs.

[sessionInfo.log](https://github.com/rstudio/rstudio/files/1767673/sessionInfo.log)

**Comment by elgalu** [comment]
It's worth noting that there is not such folder: `/home/ubuntu/`

**Comment by kevinushey** [comment]
In our experience, this kind of error occurs when there is some mismatch in the version of R used by RStudio -- e.g. for some reason, RStudio loads the `libR.so` associated with R 3.x, but tries to e.g. load an R package used by R 3.y (or restore an old session that uses R 3.y), and things blow up.

That said, the resources of the IDE team are quite limited, and we don't know how Jupyter is attempting to launch and communicate with the `rsession` process, so I'm not sure what we can do to try and help.
