### ISSUE TITLE
Whitelist .github/ directory, i.e. show it in the files pane

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#2293]
`.github/` is a standard location for files such as a code of conduct, contributing guidelines, issue templates, and the like:

https://help.github.com/articles/helping-people-contribute-to-your-project/

We just started keeping them there by convention for tidyverse and r-lib packages, as implemented in the `usethis::use_tidy_github()` function.

But now I realize that this directory is hidden by RStudio 😔. Could it be added to the whitelist?

**Comment by jjallaire** [comment]
The only issue I have with the practice of using `<.foo>` for metadata is that it will be hidden by default in the system shell (e.g. Finder on OS X) or in other editors/applications (save for on Windows where the `.` prefix has no meaning). 

So while it's great that we can one-off whitelist `.` files in RStudio, it seems to me that if we think it's important enough to be user-visible in RStudio then it probably should be user-visible in other applications/contexts (and therefore not have a `.` prefix but rather something like `_github`.

Just my 2 cents. There is already a lot of use of `.` prefixes in the R ecosystem which ends up working out well for RStudio users (when we whitelist) and Windows users, but not so well for other users.

**Comment by kevinushey** [comment]
In this particular case, `.github/` is explicitly endorsed as the directory to use for GitHub-related state: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

Since this convention has been adopted externally I think it's okay to accommodate it explicitly in RStudio.

**Comment by jjallaire** [comment]
Okay, agree 100%!
