### ISSUE TITLE
Can't select R version from Global Options on Windows daily build

### ISSUE THREAD

**Issue by imanuelcostigan** [rstudio/rstudio#2297]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.374
    OS Version      :  Windows 7
    R Version       :  3.4.3

### Steps to reproduce the problem

Tools > Global Options > R version selector is missing

### Describe the problem in detail

In 1.1, you could select which version of R to run from the same setting:

![image](https://user-images.githubusercontent.com/2107580/36884082-9d7a5422-1e32-11e8-9e70-59658b6ef06a.png)

### Describe the behavior you expected

Be able to select the setting from the same place in RStudio Desktop 1.2

**Comment by dfalty** [comment]
Also reproduced this on Windows 8 with version 1.2.375. Thanks for the report!

**Comment by ronblum** [comment]
Confirmed in 1.2.405 (switched between 3.4.3 and 3.4.1).
