### ISSUE TITLE
RStudio hangs during startup

### ISSUE THREAD

**Issue by BryanMaloney** [rstudio/rstudio#2300]
I now have the latest version of RStudio. I have it because I uninstalled it and installed it, three times. I also uninstalled and reinstalled R twice, just in case. Why?

RStudio now hangs on my machine (Windows 10 desktop). It starts to start but then loads nothing at all. I get no error messages, no windows show up in the RStudio GUI, none of the menus respond to a mouseover or click. I have let it wait for over an hour and still nothing.

**Comment by dfalty** [comment]
I'm sorry you are having this issue. Does it look like the following issue to you? https://github.com/rstudio/rstudio/issues/2302 Does resetting RStudio's state fix this for you? https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by BryanMaloney** [comment]
It didn't look like the other issue. Nevertheless, once I was able to find the directory in Windows 10, deleting the appropriate directory seems to have fixed it for me.
