### ISSUE TITLE
IDE freezes or turns black after Windows after reawakening Windows from sleep 

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2302]
### System details

    RStudio Edition : Windows Desktop
    RStudio Version : 1.2.370-1 (and other 1.2.x)
    OS Version      : Windows 10 Home (real), Windows 10 Enterprise & Pro (VM)
    R Version       : 3.4.x

### Steps to reproduce the problem

1. Launch RStudio Windows Desktop
2. Put Windows to sleep (including closing laptop)
3. Wake up Windows (including opening laptop)

### Describe the problem in detail

The IDE does one of two things:
1. In some cases, RStudio freezes—can't type, switch tabs, etc. The only thing that seems to work is the top menu bar, but clicking on items doesn't actually do anything.
2. In other cases, RStudio is entirely black. 
Exiting RStudio requires terminating it using the Task Manager. Right-clicking on the icon in the Taskbar and choosing "Close Window", or clicking on the X in the upper-right, don't work.

### Describe the behavior you expected

RStudio should not freeze or turn black.

**Comment by kevinushey** [comment]
Some other things worth testing:

- Does this reproduce in other QtWebEngine applications? (We can try running some of the sample applications provided with Qt)

- If so, is it by any chance fixed in Qt 5.10.1? Or does the issue exist in Qt 5.9.x as well?

**Comment by jmcphers** [comment]
Is this the same issue as https://github.com/rstudio/rstudio/issues/2060?

**Comment by ronblum** [comment]
Yes, it is, at least the black screen is. Should I close this as a duplicate, and copy over additional dialogue/info? Or still leave this open for the frozen screen problem?

**Comment by ronblum** [comment]
Duplicate of #2060.
