### ISSUE TITLE
Syntax highlighting examples in help pane

### ISSUE THREAD

**Issue by oloverm** [rstudio/rstudio#2303]
I find it really difficult to read examples in the help pane because they're such a big block of text. Syntax highlighting would make a huge difference.

E.g. this
![image](https://user-images.githubusercontent.com/26772530/36913084-af6bddb4-1e40-11e8-80ff-cfcae9a1bc61.png)

vs this 
![image](https://user-images.githubusercontent.com/26772530/36913102-bf20ed94-1e40-11e8-8212-b09dadb100d5.png)

**Comment by dfalty** [comment]
Thanks for the request!

**Comment by kiendang** [comment]
For anyone who's looking for this feature I've made a small package that provides it [here](https://github.com/kiendang/rdocsyntax). It's not without quirks though. Would love to see syntax highlighting for docs provided out of the box in RStudio.

**Comment by IndrajeetPatil** [comment]
@jmcphers Can this please be reopened? I think this will be a fantastic feature to have for RStudio IDE.
