### ISSUE TITLE
Terminal cursor gets lost and overwhelmed

### ISSUE THREAD

**Issue by BarkleyBG** [rstudio/rstudio#2306]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.424
    OS Version      : WIndows 7
    R Version       : 3.3.0

I use git bash for my terminal.

### Steps to reproduce the problem

In the terminal, when connected to a remote linux machine via SSH, my cursor can get "lost" when scrolling up to find previous commands. What then happens is that the terminal window then gets cluttered with old commands, and my current CLI is obscured by this clutter.

1.  Here I am on the terminal. All is well.
![1](https://user-images.githubusercontent.com/12898994/36920170-6a362152-1e25-11e8-83d8-87680520fd87.JPG)

2. I hit the up arrow to recall old commands. All is well.
![2](https://user-images.githubusercontent.com/12898994/36920164-69b2efee-1e25-11e8-9f15-e0dba50d5d20.JPG)

3. WHen I press and hold the up arrow, then too many old commands fly by, and then the terminal becomes cluttered. THis is an issue. As you can see, the cursor is no longer on the last line - it is on the 3rd to last line. The CLI has become overwhelmed with these old commands.

![3](https://user-images.githubusercontent.com/12898994/36920783-7c847cda-1e27-11e8-8b2b-a86278fa9fd4.JPG)

4. Trying to press different arrow keys to fix the issue instead makes it worse. Now the cursor has retreated farther, and is overwriting the visual output (which is worthless clutter anyways) with differnet worthless clutter. The cursor is very lost.
 
![4](https://user-images.githubusercontent.com/12898994/36920777-789e443e-1e27-11e8-839c-85142546735b.JPG)

5. Eventually I'm able to return everything to a workable state by hitting delete repeatedly, and then enter a few times, to clear the clutter on the terminal. 
 
![7](https://user-images.githubusercontent.com/12898994/36920772-72259d28-1e27-11e8-932b-5b7c8ccae4ea.JPG)

#### another example

Here you can see that I've reproduced the error by holding the up arrow again. I've greyed out some information, but you can see that there was a bunch of output that is now being overwritten by the strange cursor behavior.
![8](https://user-images.githubusercontent.com/12898994/36920642-f6cc5a86-1e26-11e8-8ef8-d63c84df9ae8.JPG)

Notably, attempting to clear the terminal output does not totally solve the issue, as I'm left with some remaining clutter.
![9](https://user-images.githubusercontent.com/12898994/36920514-890613f2-1e26-11e8-8c3a-02af702d6511.JPG)

**Comment by dfalty** [comment]
I can't reproduce this on Win7 1.1.430. @BarkleyBG can you add in your Terminal Diagnostics here? Tools->Terminal->Terminal Diagnostics

**Comment by BarkleyBG** [comment]
I'm obscuring (with ~foo~) some things that may or may not be identifying information. I can share if you need to know these values.

Global Terminal Information
---------------------------
Loaded TerminalSessions: 2
Handle: 'E2~foo~1' Caption: 'Terminal 7'
Handle: '5~foo~F8' Caption: 'Terminal 8'

Terminal List Count: 2
Handle: 'E2~foo~71' Caption: 'Terminal 7' Session Created: true
Handle: '5B~foo~8' Caption: 'Terminal 8' Session Created: true

Current Terminal Session Information
------------------------------------
Caption:     'Terminal 7'
Title:       '~my_dir~'
Cols x Rows  '61 x 31'
Shell:       'Git Bash'
Handle:      'E2~foo~71'
Sequence:    '7'
Restarted:   'false
Busy:        'false'
Exit Code:   'null'
Full screen: 'client=false/server=false'
Zombie:      'false'
Track Env    'false'
Local-echo:  'false'
Working Dir: 'Default'
Interactive: 'Always'
WebSockets:  'true'
Typing lag:  '110ms'

System Information
------------------
Desktop:    'true'
Platform:   'Windows'

Connection Information
----------------------
2018/3/5 15:20:32: Connect WebSocket: 'ws://12~foo~87/terminal/E~foo~71/'
2018/3/5 15:20:32: WebSocket connected

Local-echo Match Failures
-------------------------
<Not applicable>

**Comment by dfalty** [comment]
Thanks for the info! @gtritchie do you have any idea here?

**Comment by gtritchie** [comment]
Would be worth trying a daily build (1.2.x) just to see if it our upgraded rendering engine helps with this.

**Comment by jmcphers** [comment]
No further reports, so presumably this is addressed with our new rendering engine. @BarkleyBG feel free to reopen if you're still seeing this.
