### ISSUE TITLE
Saving RScript file dialog doesn't allow inputing a name

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2311]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.383
    OS Version      : Debian sid
    R Version       : Don't know

### Steps to reproduce the problem
Reported by a user through support channels:

Try to save an RScript file, not able to write a filename for it - i.e. click the file name field, type something, but nothing appears in the file name.  Happens regardless of whether clicking the save icon, keyboard shortcut, or toolbar option.

Can enter a name for a new folder and rename files from the files pane.

Have the 'Sky' theme, 'Clouds midnight' editor theme, and the layout configured to have the console at the top and source at the bottom. No browser plugins or addons installed.

### Describe the problem in detail
Using firefox 58.0.1; did not repro for user with Chrome.

### Describe the behavior you expected
Should be able to type a filename.

**Comment by pyltime** [comment]
User's R version is R 3.3.3

**Comment by jmcphers** [comment]
No other reports of this in years; cannot repro with latest Firefox locally w/ same theme. Suspect it's a Firefox-only issue that's long since been fixed.
