### ISSUE TITLE
Generic icon for RStudio's add/remove programs entry

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2314]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.378
    OS Version      : Win-10
    R Version       : any

### Steps to reproduce the problem
Install RStudio for Windows

### Describe the problem in detail
Go to Add Remove programs. Find the entry for RStudio. Has generic icon instead of the RStudio icon.

![2018-03-03_10-02-04](https://user-images.githubusercontent.com/10569626/36937650-75454662-1ecb-11e8-9eaa-6ab2e6b2617b.png)

### Describe the behavior you expected
RStudio icon.

**Comment by gtritchie** [comment]
Oops, I opened this issue twice. The other one is https://github.com/rstudio/rstudio/issues/2569. It was fixed a while ago with 2f330507.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
