### ISSUE TITLE
plain text help cannot be shown

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rstudio#2320]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      :  MacOS Sierra 10.12.6
    R Version       :  3.4.3

### Steps to reproduce the problem

`help(mean, help_type = "text")`
### Describe the problem in detail

A new tab is opened in the source pane, but nothing is visible in it.

### Describe the behavior you expected

The tab to be opened and show plain text help.
```

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] graphics  grDevices utils     datasets  stats     methods   base     

other attached packages:
[1] apicheck_0.1.0.9000 dplyr_0.7.4         lazyeval_0.2.1     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     digest_0.6.15    withr_2.1.1      zeallot_0.1.0    assertthat_0.2.0 R6_2.2.2        
 [7] magrittr_1.5     pillar_1.2.1     rlang_0.2.0      remotes_1.1.1    bindrcpp_0.2     tools_3.4.3     
[13] glue_1.2.0       yaml_2.1.17      compiler_3.4.3   versions_0.3     pkgconfig_2.0.1  memoise_1.1.0   
[19] bindr_0.1        tibble_1.4.2    
```

**Comment by ronblum** [comment]
Reproduced in RStudio Mac Desktop 1.1.430 and 1.2.370-1. Note that HTML and PDF (`help_type = "html"` and `help_type = "pdf")` work.

**Comment by jmcphers** [comment]
I think this is an enhancement request for plain text help, and I'm not 100% sure why it's useful. @hughjonesd Can you elaborate on situations where you'd want to see plain text instead of HTML help?

**Comment by hughjonesd** [comment]
I've forgotten by now. Rare use cases like checking what plain text help looks like, I guess. I wonder if "expected behaviour" ought to be "show plain text help in the console" rather than in a new tab. But I do think it is a bug - clearly opening a tab with nothing in it is not meaningful behaviour.

**Comment by mikebessuille** [comment]
@ronblum  
I expect we can call this as-designed and close this.  Even if this is inconsistent between platforms, we haven't seen many customers asking for this functionality and there's a clear workaround, so as a bug this would be lower priority than enough other issues to mean we won't look at it for a long time.  Better to close at this point, unfortunately.

**Comment by ronblum** [comment]
Sounds reasonable!
