### ISSUE TITLE
Executing Python chunk shows extended error

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2322]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.381
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3

### Steps to reproduce the problem

In an R Markdown document, create a chunk with the contents:

````
```{python}
x =
```
````

And then try to run it.

### Describe the problem in detail

Overly verbose error output is displayed, and no red 'error bar' treatment is shown in the gutter.

![screen shot 2018-03-05 at 1 03 45 pm](https://user-images.githubusercontent.com/1976582/36999753-fc23197e-2075-11e8-87f9-cf4252d4f7a0.png)

Compare with the display for an R chunk:

![screen shot 2018-03-05 at 1 06 33 pm](https://user-images.githubusercontent.com/1976582/36999771-0b823ada-2076-11e8-821b-8382e2c56a00.png)

### Describe the behavior you expected

Only the actual Python error should be displayed; the mechanics behind how the code was parsed + executed should be suppressed.

The red error bar should also show what line caused the error (if at all possible).

**Comment by kevinushey** [comment]
Fixed in the development version of `reticulate` (https://github.com/rstudio/reticulate/commit/0abad27db42241efd12f2ad0bcb4b8ea723c74ab):

![screen shot 2018-03-15 at 11 47 23 am](https://user-images.githubusercontent.com/1976582/37484741-a5c3f6ec-2846-11e8-954a-b33261d6c211.png)

```
devtools::install_github("rstudio/reticulate")
```

**Comment by ronblum** [comment]
Verified both with running chunk and knitting to HTML.
