### ISSUE TITLE
Feature Request: Change R version in OS X

### ISSUE THREAD

**Issue by pgensler** [rstudio/rstudio#2324]
It would be incredibly useful to have a toggle similar to Connect where you can toggle the different versions of R you have installed. That way, you could easily switch between the two if you wanted for different analysis.

**Comment by ronblum** [comment]
@pgensler Thank you for the suggestion. We'll consider it as we work development of future releases of RStudio.

**Comment by ronblum** [comment]
@pgensler It's also possible to change the R version you use on the command line. Instructions are at https://support.rstudio.com/hc/en-us/articles/200486138-Using-Different-Versions-of-R .

**Comment by kevinushey** [comment]
FWIW I have a helper function I use for this sort of thing:

```
kevin@cdrv:~
$ type r-switch
r-switch is a function
r-switch ()
{
    if test "$#" -ne 1; then
        echo "Usage: r-switch [version]";
        return;
    fi;
    local VERSIONS_PATH;
    VERSIONS_PATH=/Library/Frameworks/R.framework/Versions;
    if [ ! -e "${VERSIONS_PATH}/$1" ]; then
        echo "R $1 is not installed in '${VERSIONS_PATH}'";
        return 1;
    fi;
    if [ -e "${VERSIONS_PATH}/Current" ]; then
        sudo unlink "${VERSIONS_PATH}/Current";
    fi;
    sudo ln -fs "$1" "${VERSIONS_PATH}/Current";
    sudo ln -fs "/Library/Frameworks/R.framework/Resources/bin/R" "/usr/local/bin/R";
    local R_SESSION_INFO;
    R_SESSION_INFO="$(/usr/local/bin/R --vanilla --slave -e "utils::sessionInfo()")";
    echo "${R_SESSION_INFO}" | head -n 3
}
```

With this I can just execute e.g. `r-switch 3.3` to switch to the R 3.3.x installation I have on my machine.

**Comment by pgensler** [comment]
@kevinushey I actually tried to change it via the command line and I get this error: https://github.com/rstudio/rstudio/issues/2325#issuecomment-370835948
Now I can't even open RStudio to change what R to use.

**Comment by jpiaskowski** [comment]
Of their solutions, only the first one (a full reinstall works). The "Rswitch" package can only find incomplete installations of R versions that aren't active. This solution flat-out broke my installation: 'Update the R.framework/Versions/Current directory alias directly using ln -s'
