### ISSUE TITLE
 RSTUDIO_DISABLE_EXTERNAL_PUBLISH not working

### ISSUE THREAD

**Issue by jacp1** [rstudio/rstudio#2327]
![rstudio_screenshot](https://user-images.githubusercontent.com/16081158/37043530-beadaf44-2158-11e8-8647-3eebd377c3c7.png)

### System details

    RStudio Edition : Server
    RStudio Version : 1.1.423
    OS Version      : Centos 7
    R Version       : 3.4.3

### Steps to reproduce the problem
 RSTUDIO_DISABLE_EXTERNAL_PUBLISH=1 in /usr/lib64/R/etc/Renviron.site
Publish icon still appears on Markdown documents editor and plots tab.

### Describe the problem in detail
As above, attached screenshot shows presence of environment variable and icon.

### Describe the behavior you expected
Publish icons should no longer be present

**Comment by jmcphers** [comment]
The publish icon also allows you to publish internally to [RStudio Connect](https://www.rstudio.com/products/connect/), so disabling external publishing will not remove the button. Use `RSTUDIO_DISABLE_PUBLISH` if you want to disable *all* publishing. Let us know if that doesn't work for you!

**Comment by ronblum** [comment]
Confirmed that `RSTUDIO_DISABLE_PUBLISH` provides the desired behavior.
