### ISSUE TITLE
Too many open scripts to display in drop-down doesn't allow scrolling down to hidden tabs

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2330]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.383, 1.1.423, 1.2.380-1
    OS Version      : Ubuntu 16.04, Debian 8, MacOS 10.12.6
    R Version       : 3.4.0, 3.4.3

### Steps to reproduce the problem

1. Open many R scripts, creating many tabs—say, 33.
2. Right-click on the double arrows/greater-than signs (`>>`) next to the rightmost tab.

### Describe the problem in detail

There are too many open scripts for the vertical list to show them all—the bottom of the IDE would have to be extended, and the screen might not be big enough to handle it. In this example, there are 33 open scripts/tabs, but the vertical drop-down menu only has enough room to display 22. There is no scrolling mechanism to show the remaining 11. 

<img width="365" alt="too_many_files" src="https://user-images.githubusercontent.com/31009952/37058375-5555722a-2158-11e8-859f-742388226072.png">

Note that it is possible to mouse down all the way to 33, or mouse up from 1 so that it wraps around to 33 and on, and then select a script that's hidden. You can't see that the script/tab is selected, but you can choose it, and the focus will switch to that tab. That is, you'll move to another tab, but you won't know which one ahead of time.

### Describe the behavior you expected

It would be helpful to be able to scroll through a list that's longer than the UI allows.

**Comment by gtritchie** [comment]
See also #1794 and #1760
