### ISSUE TITLE
Terminal sometimes in bad state where mouse actions produces random characters

### ISSUE THREAD

**Issue by ccg** [rstudio/rstudio#2331]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.375
    OS Version      : macOS 10.12.6
    R Version       : R version 3.4.1 (2017-06-30)

### Steps to reproduce the problem

Leave the IDE running for a while. I don't notice the problem immediately after starting the IDE, but I tend to leave it running in the background for days at a time. Eventually, the terminal will act strangely to mouse interaction. Clicks and scroll produce random characters in the terminal rather than the expected mouse action.

I have observed this behavior in recent nightly builds and in the latest stable release.

### Describe the problem in detail

Once it's in this state, the rest of the IDE behaves normally, but clicking the left mouse button (whether or not the terminal window has the focus) inserts a few random characters into the terminal  (line breaks are where I pressed Ctrl-C):

![click](https://user-images.githubusercontent.com/59996/37057609-8dde271e-214d-11e8-9e6a-d80bf0f02469.png)

Using the scroll wheel does something similar. Here I'm scrolling up and down and getting different random characters:

![scroll](https://user-images.githubusercontent.com/59996/37058566-89a61fa0-2150-11e8-99a5-9de4a48941db.png)

I've also noticed that when I plug in an external mouse, the OS puts scrollbars in the scrollable regions of other software on the system, but the IDE does not show them. I don't know if that's related. Below is a screenshot where the foreground app has visible scrollbars, but the RStudio IDE does not (it's not just the Terminal panel; none of the scrollable panels have scrollbars in the IDE):

![missing-scrollbars](https://user-images.githubusercontent.com/59996/37058889-882facb2-2151-11e8-9347-8c111263d2c3.png)

### Describe the behavior you expected

Standard mouse behavior.

**Comment by gtritchie** [comment]
Missing scrollbars is a known issue, and work in progress. Tracked by #1953.

**Comment by ccg** [comment]
I'm sorry, I forgot to search for the scrollbar issue.

I'll see if I can reproduce the mouse/terminal issue in a more deterministic way.

**Comment by ccg** [comment]
I've noticed that if the IDE Terminal needs to restore a large amount of text from a previous session, then it immediately has the problem of the mouse inputs sending random characters into the terminal. If I open a new terminal, that new terminal does not have the problem. If I close the terminal with the large amount of text before quitting the IDE, then when I restart it, the terminal does not have the problem. If I quit the IDE while the terminal has a large amount of text in its scroll buffer, then when I restart the IDE, that terminal session will immediately have the mouse problem.

That might also explain why I don't always immediately see this problem in the terminal. It seems to be related to having a large amount of text in the buffer.

**Comment by jmcphers** [comment]
We haven't heard any other reports (or had a deterministic repro) in > 1 year, so closing this.

**Comment by Runekeon** [comment]
I can generate this behavior on demand should I open a new ticket for it?

1. ssh to linux server
2. Start htop
3. Wait for connection to drop or kill ssh from other terminal
4. terminal will be garbled 
5. doing stty sane; tput rs1; will fix most of the issues.
6. The mouse scroll wheel will generate random noise
I'm using git-bash in windows terminal to get this effect.
