### ISSUE TITLE
Git branches with long names cause window contents to shift left

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#2336]
Create a git branch that is long or reduce the git pane to partially show the branch name, click the branch name. Notice that the window contents shift to the left:

<img width="1440" alt="screen shot 2018-03-06 at 5 09 19 pm" src="https://user-images.githubusercontent.com/3478847/37068007-7e368496-2161-11e8-92a1-3beaac921c07.png">

**Comment by kevinushey** [comment]
What version of RStudio was this? We recently made a fix that would ensure the git branch dialog is right-aligned to the list dropped down:

https://github.com/rstudio/rstudio/commit/ec8ee619498ce8c1a7b8aa4adb285e15eec68cb5#diff-039e2d3d26dc7f4374618860f1838e37

Looks like that should be in the latest v1.1 releases so I'm surprised you're seeing this behavior. Any other information you can provide?

**Comment by kevinushey** [comment]
Sorry, nevermind. I can reproduce with a longer branch name.

**Comment by jmcphers** [comment]
Still repros on 1.3.625!

![image](https://user-images.githubusercontent.com/470418/70297649-cdea1680-17a3-11ea-9927-63477f1ba6a9.png)
