### ISSUE TITLE
RStudio git GUI does not support submodule

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#2337]
Will git GUI of RStudio support submodule in the future?

**Comment by ronblum** [comment]
@psychelzh Thanks for the suggestion about git submodule support. We'll consider it as we work on future updates to RStudio.

**Comment by ScaonE** [comment]
Any workaround ?

**Comment by ronblum** [comment]
@kevinushey Any thoughts on submodules in RStudio?

**Comment by kevinushey** [comment]
It's not clear to me what RStudio can / should do to support git submodules.

**Comment by MattBrauer** [comment]
Allowing `pull` to point to `git pull --recurse-submodules` would be useful.
