### ISSUE TITLE
Git revert only works after reverting twice

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#2338]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Windows 7, 64 bit
    R Version       : 3.4.3

### Steps to reproduce the problem
Try to revert a change you made by clicking more - revert in the git tab. The first time nothing happens, the second time the change is reverted. 

### Describe the problem in detail
When trying to revert a change in the way described above nothing happens at first, but the second time I try it works perfectly. I tried this for several files, for several projects and it seems to be the case all the time. There is no message (normal of error) the first time I click

### Describe the behavior you expected
I expected the change to revert the first time I clicked.

**Comment by dfalty** [comment]
I'm not able to reproduce the same OS (Win7) and version (1.1.423) so there might be something else going on. Do you get the revert changes pop up the second time you try to revert?

**Comment by BartJanvanRossum** [comment]
Yes, I do. 
I select an item in the git tab. Click on more - Revert... in the menu and nothing happens.
Then I click more - Revert... once again and the item is removed from the list in in the git tab.
Both times I do get the popup asking me whether I want to continue and both times I click "yes"

**Comment by dfalty** [comment]
Thanks for the additional information. Not sure what is going on so this will have to be looked into further.

**Comment by BartJanvanRossum** [comment]
A year further on the issue seems to have disappeared for me. However it is difficult to say what made this happen. I am now using RStudio 1.2.1326 but the hardware I'm using is a lot better now than it was last year. It might just have been some delay caused by using large files on a (relatively) slow pc.

**Comment by jmcphers** [comment]
Sorry we never got to the bottom of this, but glad it's working for you!
