### ISSUE TITLE
Using Terminal Rstudio and external Terminal deletes the whole working directory

### ISSUE THREAD

**Issue by ibarraespinosa** [rstudio/rstudio#2339]
### System details

    RStudio Edition : 
    RStudio Version : 1.1.383
    OS Version      :  Ubuntu 17.10 artful
    R Version       : 3.4.2

### Steps to reproduce the problem
Work under a directory and save files in there
Open the Rstudio  xterm (Terminal) and save some stuff in the same directory
Open an external xterm (Terminal) ans save/copy/delete files
**your whole directory is gone**

### Describe the problem in detail
Work under a directory and save files in there
Open the Rstudio  xterm (Terminal) and save some stuff in the same directory
Open an external xterm (Terminal) ans save/copy/delete files
**your whole directory is gone**

### Describe the behavior you expected
do not delete directory

**Comment by ronblum** [comment]
@ibarraespinosa Can you provide more detailed information about the steps you took that resulted in this issue? I tried to reproduce the problem with the steps below, but the directory I was using was unaffected.

Using a pre-existing empty directory called  `~/test`:

1. In the RStudio “Files” pane, click through to `Home > test`
2. Open a new R script
3. Save the script as `file_one.R` in `~/test`
4. Open the Terminal in RStudio using `Alt-Shift-R` or `Tools -> Terminal -> New Terminal`
5. `cd ~/test`
6. `touch file_two`
7. `cp file_two file_three`
8. Open XTerm
9. `cd ~/test`
10. `touch file_four`
11. `cp file_four file_five`
12. `rm file_two`
13. Exit Xterm, close RStudio Terminal, and change directory in Files pane to `Home`
14. Open XTerm
15. `cd ~/test`

The directory is still present

**Comment by jmcphers** [comment]
Haven't heard back in over a year; closing.
