### ISSUE TITLE
Disable text word-wrapping or soft-wrapping behavior

### ISSUE THREAD

**Issue by AnthonyFucci** [rstudio/rstudio#2341]
Is there any method for disabling word-wrapping in the RStudio file/text editor? While having the option is nice, I have never preferred to write code in an editor that wraps text onto multiple lines. It's unusual for IDE's and is one of my last soft grievances with RStudio. The closest official page discussing it I can find is here: https://support.rstudio.com/hc/en-us/community/posts/239157828-Disable-Soft-Wrap-in-Rmarkdown-documents

For example, is there an RStudio css file that I can modify to force this behavior off?

If no current method exists, may I request the feature: disable word-wrap/soft-wrapping for all files opened in the text editor, regardless of extension.

Thank you for your time,
Anthony

**Comment by ronblum** [comment]
@AnthonyFucci It's possible to turn soft-wrapping off for R scripts, at Tools -> Global Options -> Code -> Editing -> Soft-wrap R source files. However, this doesn't apply to R Markdown documents, which are designed to handle large blocks of text. However, I'll tag this as an enhancement, which we can review for future release of RStudio. Thanks!

**Comment by Matherion** [comment]
Just chiming in to let you know that @AnthonyFucci isn't the only one who'd really like this 😄

**Comment by Matherion** [comment]
... Also see these people: https://support.rstudio.com/hc/en-us/community/posts/239157828-Disable-Soft-Wrap-in-Rmarkdown-documents

**Comment by Matherion** [comment]
(Maybe we should start a club. I already started on the anthem: "It's my RmD and I'll wrap when I want to, wrap when I want to, wrap when I want to".)

**Comment by aushev** [comment]
@ronblum do you still consider enabling this for markdown documents? Would be really cool to have this option.

**Comment by arencambre** [comment]
This may evolve the issue a bit, but I would rather RStudio work like other editors I use: there's a word wrap selection in a menu--perhaps in RStudio's **View** menu--that enables or disables word wrap for all documents. It shouldn't be buried in the global options, and it should work consistently across all opened files.

**Comment by GeorgiaData** [comment]
Until this is resolved, I propose we start a movement wrap the editor's name onto two lines in all posts.

R
Studio

**Comment by romagnolid** [comment]
I stumbled on this issue just now. It would be a great improvement.

**Comment by ronblum** [comment]
We've left this enhancement in an open state, which means that it's still a candidate for a future release. However, I can't give you a timeframe or indication of whether or not we'll add it. But, in the meantime, please give it a thumbs up 👍 if you're interested in it—the thumbs tell us what features are really needed.
  
Also, another possibility are
[R
Studio
Addins](http://rstudio.github.io/rstudioaddins/).  We've provided [some examples](https://github.com/rstudio/addinexamples), and there are many written by users that are publicly available. If you're feeling adventurous, you can even write your own.

The [WrapRmd](https://github.com/tjmahr/WrapRmd) addin does something with wrapping in R Markdown files. I'm not endorsing it, and it does the opposite of what you're looking for, but if you want to write your own addin, this could be a good starting point. And if you do write one, please let us know!

**Comment by chernavsky** [comment]
Yes, this would be a very useful improvement to the editor.

**Comment by sgrubsmyon** [comment]
To me, it seems almost impossible to edit large Markdown tables in a Markdown file in RStudio due to the soft-wrapping that cannot be disabled.

**Comment by ronblum** [comment]
By the way, to clarify my note above: the 👍 should be applied to the original request at the top.

**Comment by mpettis** [comment]
I am able to do this in a buggy way -- I use Vim mode for editing, but there is a catch.  I can use the command `:set nowrap` while in, say, an Rmd file, and soft-wrap will be turned off.  However, when I save the file, it reverts to being soft-wrapped.  I cannot just re-isssue `:set nowrap` again, it won't work.  I have to issue `:set wrap`, which it is already doing, and then `:set nowrap`.  So apart from being a nice request, the way it currently functions is probably not optimal.  Was going to file a bug, but figured this issue was closest anyway.

**Comment by francisbarton** [comment]
I'm having the opposite problem in the Rmd file I'm editing in RStudio. I _want_ my text to wrap at the 80-char border, but it _isn't_ getting wrapped. How frustrating!

**Comment by natehall329** [comment]
It would be such a game changer if there was a keyboard shortcut to toggle soft-wrapping in the editor (.Rmd or otherwise). If I'm trying to leave some lengthy comments as reminders to myself for a later date it would be awesome to let code wrap and once I'm done let it disappear into the off-screen ether. I've done a bit of searching for this feature but have come up empty, have other folks looked into this?

**Comment by NilsEnevoldsen** [comment]
Extensionless temporary workaround

1. Have only one text/markdown editor open
2. Right click anywhere in RStudio and select Inspect Element from the context menu to open RStudio DevTools
3. Select the Console tab of the DevTools
4. Copy, paste, and run the following javascript command:
```javascript
ace.edit(document.getElementById("rstudio_source_text_editor")).getSession().setUseWrapMode(false)
```

To turn word wrap back on, either use `setUseWrapMode(true)` or just close and reopen the text/markdown editor.

**Comment by R-Hannibal** [comment]
@AnthonyFucci, thanks so much for pointing out this way to improve the RStudio experience! We have a fix in place in our latest daily build (available [HERE](https://dailies.rstudio.com/)). 

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by AnthonyFucci** [comment]
@R-Hannibal wooo! :)

Using the setting "Tools" -> "Global Options..." -> "R Markdown" -> "Soft-wrap R Markdown files" works for me in the latest build. 

Thanks everyone!
