### ISSUE TITLE
msys-ssh being added to path on non-Windows IDEs

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2352]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1.x
    OS Version      : Mac or Linux
    R Version       : 

### Steps to reproduce the problem
Configure terminal as follows then create a new terminal.
![2018-03-08_10-36-23](https://user-images.githubusercontent.com/10569626/37169453-c35105d6-22bc-11e8-9726-f030bc333098.png)

Look at the resulting PATH.

### Describe the problem in detail
  
The PATH ends with  bin/msys-ssh-1000-18

### Describe the behavior you expected

This is a window-only thing, should not be on the path for Linux or Mac.

**Comment by jmcphers** [comment]
I think it happens here:

https://github.com/rstudio/rstudio/blob/bc4831ccafa402891a442e587b2596f5753309f1/src/cpp/session/SessionConsoleProcess.cpp#L74-L76
