### ISSUE TITLE
R code execution error

### ISSUE THREAD

**Issue by statsandthings** [rstudio/rstudio#2354]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Windows 10
    R Version       : 3.4.3

I receive the following two errors, simply by typing in my R Studio source pane. The first error hovers over the source pane. The second error repeats itself over-and-over in my console window after each key press on my keyboard. 

> (1) R code execution error
> 
> (2) Error in rightData[completions] :    object of type 'closure' is not subsettable

***HowTo Reproduce this Error:*** You can enter the code below in your R Studio source pane and you **do not** have to execute it to get the errors that I am receiving. 

Once the code is pasted in your source pane go down to `row 15` and place your cursor directly after the "e" in "\`List name\`". In my source pane this happens to be position `15:26`. Now, if you start typing characters the console starts spitting out error #2 shown above, after each press of a key on your keyboard. If it doesn't work on the very first try, delete the characters you just entered with <kbd>backspace</kbd> and try again. It always works the second time around.

I never save my workspace to .RData and have confirmed this on a fresh, clean R Studio session. I also don't restore .RData into my worspace upon startup. This should duplicate if you're O/S and versioning setup is like mine.

    plants %>% 
      left_join(
        read_tsv("files/data_b.txt") %>% 
          select(
            `Date of Entry`, 
            IDnumber, 
            `Weight in kg`, 
            `Volume in ml`, 
            `List name`
          ) %>% 
          rename(
            DoE = `Date of Entry`,
            IDN = IDnumber,
            Wkg = `Weight in kg`,
            Name = `List name`
            ), 
        by = "type"
      ) %>% 
      left_join(
        read_tsv("files/data_c.txt"), 
        by = "date"
      )

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, because we don't have access to the `plants` dataset we can't reproduce this on our end.

However, this issue sounds a lot like https://github.com/rstudio/rstudio/issues/2144. Basically, RStudio's completion system barfs when it sees the pipe operator used within one of the arguments passed one of the `dplyr` join methods.

**Comment by ronblum** [comment]
Marking as a duplicate of https://github.com/rstudio/rstudio/issues/2144.
