### ISSUE TITLE
Better quote behaviour in R Markdown docs

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2355]
If there are an odd number of quotes to the left of the cursor in the current expression, pressing `"` should only insert a single quote mark.

The current behaviour is super frustrating because if you get into a state with an odd number of quotes it is hard to get out of it - if you press `"` you get two quotes, so you then press delete to get rid of them, but then both are deleted.

**Comment by kevinushey** [comment]
Can you provide an example where you're seeing this frustrating quoting behavior?

**Comment by kevinushey** [comment]
It looks like this issue exists in R Markdown documents, but not in plain R documents.

**Comment by hadley** [comment]
Oh indeed - I wondered why I had been finding it more annoying than usual, but it's just because I've been working more in `.Rmd`

**Comment by hadley** [comment]
Could you please also use smart quote insertion for `` ` `` in R (and if possible, in code blocks in Rmds)?
