### ISSUE TITLE
Knit ignores setting "Current Working Directory" and writes to document directory

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2357]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383, 1.1.442
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Create two directories, `dir1` and `dir2` in the home directory.
2. Create an R Markdown file and save it in `dir1` as `sample.Rmd`.
3. Change the current working directory to dir2: `setwd("~/dir2")`
4. Change the Knit directory: `Knit -> Knit Directory -> Current Working Directory`
5. Knit the file by clicking on `Knit`

### Describe the problem in detail

The resulting file is `~/dir1/sample.html`—in the same directory as the source `sample.Rmd`.

### Describe the behavior you expected

The output file should be at `~/dir2/sample.html`—in the current working directory.

### Additional Information

This is the command at the end of the "R Markdown" tab created on knitting:

>/usr/local/bin/pandoc.2.0.6//pandoc +RTS -K512m -RTS sample.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output sample.html --email-obfuscation none --self-contained --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /var/folders/fx/m05t95913_q8x86417r0s6480000gn/T//RtmpevbV56/rmarkdown-strd2964474fb66.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
output file: sample.knit.md
>
>Output created: sample.html
>

**Comment by jmcphers** [comment]
The knit directory is not the directory where the output is saved; it's the working directory used when executing chunks. Do you see the correct directory from `getwd()` inside a chunk?

**Comment by ronblum** [comment]
Ohhhh! Yes, that works, for all three—Document Directory, Project Directory, and Current Working Directory.

Closing as user error.
