### ISSUE TITLE
Feature Request: .Rmd file YAML option to close console window upon opening

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#2358]
I'd like to add a new YAML option to RMarkdown files that would cause the IDE to close the console window when the RMarkdown file is opened. This would reproduce the behavior of R Notebooks, but for all RMarkdown formats.

Motivation: I've found the notebook behavior to be a benefit when teaching. Nudging the console window closed helps students:

1.  Focus on one chunk at a time
2. Enter code in the correct place (students frequently use the console by mistake. It matters because the code chunks that I provide have scaffolded code for the exercise).

But I prefer to teach a workflow that uses the RMarkdown HTML document format, where students:

1. Open a .Rmd
1. Use the GUI icons or Command + Enter to run code in chunks. 
1. See results displayed inline
1. Use Cmd + Shift + K to knit the document in a fresh R session at the end of the day (to ensure reproducibility)

I estimate that this feature would save me about 5-20 minutes of explanation during a workshop, and increase student satisfaction.

**Comment by jmcphers** [comment]
This would probably go under the `editor_options` YAML key.
