### ISSUE TITLE
Not accessing system path variable

### ISSUE THREAD

**Issue by kjohnsen** [rstudio/rstudio#2360]
It seems that RStudio is accessing the system's PATH variable incorrectly: it seems to access a stored value rather than querying the system's current value. I'm running on Linux, and when I update the system path on the terminal, then run `echo $PATH`, I see the new location stored in the path. However, when I run `system("echo $PATH")`, I do not. The problem persists after restarting the session, and I can confirm that this is an RStudio problem, not an R problem, since calling `system("echo $PATH")` on the command line R interpreter produces the expected results.

This is not a new problem, either, as seen in this [old RStudio support thread](https://support.rstudio.com/hc/en-us/community/posts/200629578-system-call-from-RStudio-does-not-find-path-same-command-from-commandline-R-works-fine-) or [this one](https://support.rstudio.com/hc/en-us/community/posts/115000139987-RStudio-server-changes-system-PATH).

#### Example terminal (system) output:
```
echo $PATH
/usr/local/bin
PATH=$PATH:/home/username/path_test
echo $PATH
/usr/local/bin:/home/username/path_test
```

#### Example RStudio console output (after updating PATH on system terminal):
```
system("echo $PATH")
/usr/local/bin
```

### System details

RStudio Server, version 1.1.423
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

**Comment by kevinushey** [comment]
This is expected -- each running program inherits the environment variables (including `PATH`) of the process from which it was launched, but each has its own set of independent environment variables. Setting the `PATH` for one application will not affect the `PATH` in other applications.

If you want to update the `PATH` in a running RStudio session, you'll have to use e.g.

```R
Sys.setenv(PATH = "<...>")
```

**Comment by kjohnsen** [comment]
Ok, that worked. Thanks!
