### ISSUE TITLE
Switching projects can occasionally give 404 error

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2365]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.400
    OS Version      : macOS 10.13.3
    R Version       : r-devel

### Steps to reproduce the problem

Try switching to a different project.

### Describe the problem in detail

The attempt to switch projects fails, and you instead see a 404 error:

![screen shot 2018-03-09 at 10 13 31 am](https://user-images.githubusercontent.com/1976582/37222620-a59c85bc-2382-11e8-9947-d8cf18ac9c40.png)

### Describe the behavior you expected

RStudio should switch projects without error.

### Notes

I can reliably reproduce this with a locally-compiled development version of R, which has sanitizers etc. enabled (so it is a lot slower). I suspect the issue may be timing related; while it reliably reproduced with my development version of R I suspect it may be much more rare with CRAN versions of R.

**Comment by hrbrmstr** [comment]
@kevinushey I'm also experiencing issues where it won't open projects in a new session either from the command-line, File menu or the top-right project menu in the UI. I did a quick scan of the other issues with "project" in them and didn't see that noted anywhere (but I cld have missed it, too). Apologies if this is notification is a dup. If it's not a dup or even if it is and you need more logs/screen shots, lemme know. This is macOS 10.13.4 β4 & RStudio 1.2.402. It's not a show-stopper but it's def a workflow interruption.

(as an aside, I can def also reproduce some of the repaint "glitching" that you and others noted in the qt-tagged issues)

**Comment by ronblum** [comment]
I'm seeing a similar issue when creating a new project. First I get a message that 127.0.0.1 refused to connect. Clicking Reload successfully brings up the new project.

**Comment by jmcphers** [comment]
Re: previous reference, we think the way to resolve this is by implementing a retry mechanism. See https://github.com/rstudio/rstudio/issues/2898.

**Comment by hrbrmstr** [comment]
this got worse recently but I haven't updated dailies since Monday so I'll give it a go again tomorrow.

**Comment by kevinushey** [comment]
Should be resolved with https://github.com/rstudio/rstudio/pull/3039/commits/937165c83955e27359cbe28510ae76fc8ef480f7 -- please re-open if you're still seeing issues with the latest dailies.
