### ISSUE TITLE
Code formatting is not consistent

### ISSUE THREAD

**Issue by FireFighter1017** [rstudio/rstudio#2371]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 10 Pro 1607
    R Version       : 3.4.3

### Describe the problem in detail
While coding, closing parentheses will not reformat automatically.  Unless I code them fist then insert a carriage return before them.  Then they get formatted and aligned with the openning parenthesis.  But when I select the whole function code and use the "reformat code" option from the "Code" menu, everything gets refomatted using some simple indentation which makes no sense.  So I end up having no consistent tooling to reformat the code.

### Describe the behavior you expected
Have one consistent way to format the code either while typing it or reformat option.  And it should apply Google's R coding standards.

**Comment by ronblum** [comment]
@FireFighter1017 Thank you for the suggestion—we'll review it as we work on development of future versions of RStudio.

**Comment by jmcphers** [comment]
If you're interested in having a tool apply consistent R code formatting for you, you might like @yihui's FormatR package:

https://yihui.name/formatr/

**Comment by hadley** [comment]
Or styler: http://styler.r-lib.org — Google's coding style is dated and idiosyncratic.

**Comment by jmcphers** [comment]
>  But when I select the whole function code and use the "reformat code" option from the "Code" menu, everything gets refomatted using some simple indentation which makes no sense. 

This issue hasn't been touched in a year and half, probably because this is too vague to be actionable. I do agree that the indentation could use some work, and we will use #2563 to track the possibility of integrating styler (or similar) to help make it better.
