### ISSUE TITLE
Excessive memory usage when saving Rnotebooks

### ISSUE THREAD

**Issue by daniel-wells** [rstudio/rstudio#2374]
### System details
    RStudio Edition : Desktop
    RStudio Version : Version 1.1.423
    OS Version      : Intel Mac OS X 10_13_3
    R Version       : 3.4.0

### Steps to reproduce the problem

Create an R notebook test.Rmd :

    ---
    title: "R Notebook"
    output: html_notebook
    ---
    
    ```{r}
    for (i in 1:10){ print(ggplot2::qplot(rnorm(1000), rnorm(1000))) }
    ```

Run the code block, then click file save, or the Preview button, or run `.rs.createNotebookFromCache("test.Rmd")`

The problem also occurs when using `output: html_document` and clicking the Knit button.

### Describe the problem in detail

When following the steps above, Pandoc (as shown by the macOS activity monitor) uses ~600 MB of memory to create the 3.3 MB test.nb.html which is quite a lot for such a simple document. Furthermore when using `rmarkdown::render("test.Rmd")` only ~20 MB is used which makes me think it's an Rstudio bug rather than pandoc?

### Describe the behavior you expected

I would expect the preview button to have similar RAM usage to the rmarkdown::render() function and not 180x the size of the final document. For larger Rnotebooks (20 [more complicated] plots, 37 MB .nb.html) I'm using an extra 6GB of RAM every time I save the file.

**Comment by dfalty** [comment]
I don't get quite the difference you do but I do get ~140 MB vs ~30 MB. @jmcphers any idea why it would be that big of a difference?

**Comment by jmcphers** [comment]
Not offhand. Behind the scenes, saving a notebook does in fact invoke `rmarkdown::render()`; it just does so with a few extra parameters which read output from RStudio's output cache. 

https://github.com/rstudio/rstudio/blob/691dfb9c087e863d342f16a13bf4bc5fa752e00a/src/cpp/session/modules/SessionRmdNotebook.R#L454-L460

@daniel-wells, what versions of Pandoc and the rmarkdown do you have? You might try the latest versions of both (it may be that you're hitting a pathological leak somewhere in an older pandoc).

**Comment by daniel-wells** [comment]
Thanks for looking into this. I'm using rmarkdown 1.9 and pandoc 2.1.2 according to `rmarkdown::pandoc_version()`. The problem was also happening with the RStudio packaged pandoc version 1.19.2.1 before I updated to see if that helped. I think the peak memory by Activity Monitor or top can vary depending on the update frequency, not sure how to better monitor peak usage.

**Comment by jmcphers** [comment]
We've had no reports of this in well over a year, and even if this were still a problem it's likely a bug in Pandoc we can't do anything about. Please let us know if you're still seeing this in the latest dailies, which use a very new Pandoc (2.7); if you are, we can help you craft an issue report upstream for Pandoc.
