### ISSUE TITLE
[Bug] Rstudio freezes when first time creating new RMarkdown files when the computer is in a closed network

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/rstudio#2379]
Apologies for not following the issue tracking guideline but this is an issue filed by @madcarrot in rstudio/rmarkdown (https://github.com/rstudio/rmarkdown/issues/1279#issuecomment-372430953) concerning the R IDE freezing due to not being able to download R packages related to R Markdown. Here is the original issue:

---
Title: [Bug] Rstudio freezes when first time creating new RMarkdown files when the computer is in a closed network

Relates to: rstudio/rmarkdown #1279

I am working under company network which blocks the CRAN R mirrors. When I tried to create a new RMarkdown file, R freezes, because it needed to install two extra packages, and it cannot establish a link to any of the mirrors. However, even when the warning about connection pops up, it kept being frozen. It's only when I connected to external network did it finally installed the required packages and start.

I think this counts as a bug as it's really hard to understand what's going on for novice users. I would like to suggest putting all the required packages for Rstudio to create RMarkdown files in the requirement for installing the rmarkdown package, or stop Rstudio from attempting to connect to a CRAN R mirror when the connection times out.

**Comment by madcarrot** [comment]
Thanks for helping me move the issue to the right place!

**Comment by jmcphers** [comment]
This is now somewhat mitigated because we do the installation in a background job (so doesn't block the main R session). However I think the initial `available.packages()` hit still happens on the main thread.

**Comment by leepface** [comment]
It would be great to get this resolved!
