### ISSUE TITLE
IDE did not catch that I needed to agree to the XCode license

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#2380]
After updating to Mac OS 10.13 then updating R and RStudio IDE, `install.packages("stringi")` failed on my computer (both when called as `install.packages("stringi")` and `install.packages("tidyverse")`).

Parsing the error message I figured out that I needed to agree to the new XCode license, which I did in the terminal window. Then everything worked. But RStudio IDE did not catch this, which I've been told it should.

For reference,  there is a binary version available but the source version is later:

```
        binary source needs_compilation
stringi  1.1.6  1.1.7             FALSE
```
Also 
```r 
as.list(available.packages()["stringi", ])
## $Package
## [1] "stringi"
## 
## $Version
## [1] "1.1.7"
## 
## $Priority
## [1] NA
## 
## $Depends
## [1] "R (>= 2.14)"
## 
## $Imports
## [1] "tools, utils, stats"
## 
## $LinkingTo
## [1] NA
## 
## $Suggests
## [1] NA
## 
## $Enhances
## [1] NA
## 
## $License
## [1] "file LICENSE"
## 
## $License_is_FOSS
## [1] "yes"
## 
## $License_restricts_use
## [1] NA
## 
## $OS_type
## [1] NA
## 
## $Archs
## [1] NA
## 
## $MD5sum
## [1] NA
## 
## $NeedsCompilation
## [1] "yes"
## 
## $File
## [1] NA
## 
## $Repository
## [1] "https://cran.rstudio.com/src/contrib"
```

**Comment by jmcphers** [comment]
> install.packages("stringi") failed on my computer

What was the error message you saw?

The IDE does try to help you out with this when the Git commands RStudio issues on your behalf (specifically) stop working because you haven't agreed to the license, but AFAIK we don't currently have a mechanism that can intercede with ordinary R commands in a similar way.

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/pull/1527.

**Comment by hadley** [comment]
RStudio probably should add a trigger to check to its `install.packages()` shim — otherwise many mac uses will fail when they try to install a source package after an xcode update.

**Comment by jmcphers** [comment]
Improved for Git in https://github.com/rstudio/rstudio/pull/5494 (but AFAIK still not solved for this use case)

**Comment by kevinushey** [comment]
Note: the fix would likely entail inserting a call to `checkXcodeLicense()` at some appropriate point; see e.g.

https://github.com/rstudio/rstudio/blob/4f0955405e5f33f4d933818eda065d38b8c45e3a/src/cpp/session/modules/build/SessionBuild.cpp#L2268-L2272

for where we do it when testing if a package (for package projects) can be built.

**Comment by 0x3L1** [comment]
anyone who came up with the solution ?
