### ISSUE TITLE
Add R API function for knitting a document in the background

### ISSUE THREAD

**Issue by AshesITR** [rstudio/rstudio#2385]
It would be nice to programmatically be able to start a knit process in the "R Markdown" pane from R.
The call should be asynchronous (return immediately, possibly offer a callback)

This feature would be even better if you could schedule multiple Rmds to be run sequentially (or even in parallel?) in the pane / multiple panes.

Currently I run rmarkdown::render in a new.env() to not clutter globalenv, but this still outputs to console instead of a separate window.

**Comment by jjallaire** [comment]
@AshesITR There are a set of terminal API which should enable you to do what you are looking for (running your parallel renders in their own terminals): https://cran.r-project.org/web/packages/rstudioapi/vignettes/terminal.html

**Comment by hadley** [comment]
You can also use the callr package to do this.

**Comment by AshesITR** [comment]
@jjallaire Thanks for the tip, I'll try that.
Callr seems interesting but for this use case stdout should be visible asap so terminals look like the way to go.

**Comment by hadley** [comment]
callr allows you to show stdout.

**Comment by AshesITR** [comment]
@hadley How would this be done? NB I will need `callr::r_bg()` for non-blocking behaviour.

**Comment by jmcphers** [comment]
This is a lot easier with RStudio's Jobs but still nothing one-click. See also https://github.com/rstudio/rstudio/issues/5190.

**Comment by jmcphers** [comment]
Now that I read this FR more carefully, it is indeed possible programmatically with RStudio jobs. Check out `rstudioapi::jobRunScript`, which will let you run a background job consisting of arbitrary R code (including several R Markdown render calls if you wish).
