### ISSUE TITLE
scrollbar gone in daily builds at least since 1.2.4.0

### ISSUE THREAD

**Issue by dpastoor** [rstudio/rstudio#2386]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.4 - 1.2.407
    OS Version      :  OSX (multiple versions)
    R Version       : 3.4.3

### Steps to reproduce the problem
Open Rstudio

### Describe the problem in detail
Source editor does not have scroll bar

### Describe the behavior you expected
Scroll bar exists

**Comment by ronblum** [comment]
@dpastoor Thanks for raising this. This is a known issue which is being tracked at #1953 if you'd like to follow its progress.

**Comment by dpastoor** [comment]
Thanks Ron - I had searched issues for scroll instead of scrollbar 🤔 good to know it's being tracked, just subscribed thanks!

**Comment by ronblum** [comment]
@dpastoor Your timing is uncanny—the next build should include a fix!
