### ISSUE TITLE
Buggy \r behavior when ANSI colors are present

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/rstudio#2387]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.441
    OS Version      : macOS 10.12.6 (16G1114)
    R Version       :  3.4.3

### Steps to reproduce the problem

```r
cat(c(crayon::red("123"), "x \r", crayon::red("456"), "x \r", crayon::red("789")), sep = "")
#> 456789x 
```

### Describe the problem in detail

When `cat()`-ing only the first element:
```<span class="GNKRCKGCGSB xtermColor2">123</span>
<span class="GNKRCKGCGSB"> x</span>
<span> </span>
```

When `cat()`-ing the first three:
```<span class="GNKRCKGCGSB xtermColor2">456</span>
<span class="GNKRCKGCGSB xtermColor2"></span>
<span class="GNKRCKGCGSB"> x</span>
```

All:
```<span class="GNKRCKGCGSB xtermColor2">456</span>
<span class="GNKRCKGCGSB xtermColor2">789</span>
<span class="GNKRCKGCGSB xtermColor2"></span>
<span class="GNKRCKGCGSB"> x</span>```
```

### Describe the behavior you expected

```
#> 789x 
```

**Comment by gtritchie** [comment]
In straight R (in Terminal.app on Mac), I don't get the `x` at the end, with or without the crayon calls:
![2018-03-19_14-57-51](https://user-images.githubusercontent.com/10569626/37624618-fd47baf6-2b85-11e8-8264-dfa2cd320894.png)

**Comment by gaborcsardi** [comment]
It is overwritten by the prompt. In my session it is visible, because I have a multi-line prompt.

**Comment by gaborcsardi** [comment]
Or a task handler. Anyway, you are right, in a vanilla R session it is not visible.

**Comment by gaborcsardi** [comment]
But the problem is that the `456` part is not overwritten after the `\r`.
