### ISSUE TITLE
Renamed files on MacOS don't show up in file pane without refresh

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2388]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.405
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. In the terminal: `touch ~/bobo`
2. In RStudio: make sure the file `bobo` exists under `Home`
3. In RStudio: rename the file, only changing case, from `bobo` to `Bobo`
4. In RStudio: check the file pane -> no files named `bobo` or `Bobo` exist
5. In the terminal: `ls -l Bobo` -> `Bobo` exists
6. In RStudio: refresh the file pane -> `Bobo` should now appear, but not `bobo`

### Describe the problem in detail

The renamed file doesn't show up in the file pane when it's renamed. The file pane needs to be refreshed for it to appear.

### Describe the behavior you expected

The file is renamed  and shows up in the file pane even without refreshing. New files normally appear at the bottom; renamed files also appear at the bottom on Windows and Linux.

For what it's worth, MacOS is case insensitive by default, so it considers `bobo` and `Bobo` to be the same:
```
Rons-MacBook-Pro:~ ronblum$ ls  bobo Bobo
Bobo	bobo
Rons-MacBook-Pro:~ ronblum$ cp bobo Bobo
cp: Bobo and bobo are identical (not copied).
```

[This wasn't an issue In 1.1.442 because renaming a file by only changing case failed with a "File exists" error. Also note #1886.]

**Comment by jmcphers** [comment]
Is this only a problem with renames that only change case? Or does it affect all renames?

**Comment by ronblum** [comment]
Only changing case. If a file is renamed to anything else, the new name appears in the file pane immediately—but in the location of the original file, not in the correct alphabetical order, until a refresh.
