### ISSUE TITLE
Feature request: ability to collapse UI functions 

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#2390]
The ability to collapse functions in RStudio is great. I'm talking about this arrow beside the line number:

![image](https://user-images.githubusercontent.com/952340/37363033-4a7ed47a-26cd-11e8-80c6-710d1c9424d4.png)

I noticed that it only comes up when there is a code chunk (such as a function, an if statement, etc) that has a curly brace `{`. Whenever I open a curly brace, that arrow pops up in the side, and allows me to collapse/expand this code chunk. Great feature :)

It would be amazing if it also worked in Shiny UI. In Shiny UI functions, we often define very long functions that can be tens of even hundreds of lines long, but they don't have curly braces. For example:

```
tabPanel(
  "Tab1",
  "This is content",
  "Inside a tab",
  "It can be very very very long"
)
```

Often times I want to collapse a very long UI function so that I can see what comes immediately following it, but I can't, because there is no curly brace (and introducing a curly brace won't make sense). So what I have to do is place the cursor at the opening parenthesis, and scroll down until I see the matching closing parenthesis highlighted. Very slow method. It'd be great if these could be collapsible.

**Comment by ronblum** [comment]
Thanks @daattali for the feature suggestion—we'll review it as we work on development of future version of RStudio.

**Comment by smouksassi** [comment]
I keep hitting control p to know where the end of my opening bracket is  and I flag the end with something like:
) # end of tabpanel tab1 indeed this will be a great enhancement

**Comment by daattali** [comment]
I didn't know about ctrl+p shortcut, thanks Samer!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Want to improve your Shiny skills? Try my new interactive, online video
course *Shiny Case Studies*
<https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny-case-studies>

**Comment by lvalnegri** [comment]
Meanwhile, you can always wrap your chunk of code with two comments, both of them ending with at least four dashes, something like this:

```
# start of my beautiful tabpanel ----
tabPanel(
  "Tab1",
  "This is content",
  "Inside a tab",
  "It can be very very very long"
)
# end of tabpanel ----------------------------------
```

**Comment by tanho63** [comment]
@daattali I've had success wrapping the outside of the tabPanel argument in curly braces and collapsing it. This is in a renderUI function, but amounts to same syntax in the UI section as well. 

![image](https://user-images.githubusercontent.com/38083823/74842207-00fa6b80-52f8-11ea-8eac-f8f849874cdf.png)

![image](https://user-images.githubusercontent.com/38083823/74842308-30a97380-52f8-11ea-9f32-2fd4db1316a4.png)
