### ISSUE TITLE
Traceback is a tree, not a stack

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2393]
As revealed by `lobstr::cst()` the call "stack" is really a tree:

```R
library(lobstr)
f <- function(x) g(x)
g <- function(x) h(x)
h <- function(x) x
try(f(cst()))
#' ★
#' ├─try(f(cst()))
#' │ └─tryCatch(...)
#' │   └─tryCatchList(expr, classes, parentenv, handlers)
#' │     └─tryCatchOne(expr, names, parentenv, handlers[[1L]])
#' │       └─doTryCatch(return(expr), name, parentenv, handler)
#' ├─f(cst())
#' │ └─g(x)
#' │   └─h(x)
#' └─cst()
```

(The treeness comes from lazy/delayed evaluation - each branch represents some delay of execution)

This data can easily be constructed from `sys.calls()` + `sys.parents()` and I think makes understand the traceback substantially easier. In an ideal world, the traceback would become an interactive widget where you could expand branches as needed. Generally, user code only occurs in the right/bottom-most branch so all other branches could be collapsed by default. If making a fully expandable tree was too expensive, having two views (one fully expanded and one with only the bottom-most branch expanded) would be a good compromise.

I don't yet have a good explanation for how this works, but you can see my latest attempt at https://adv-r.hadley.nz/environments.html#frames-and-the-call-stack

**Comment by hadley** [comment]
I think this is still worthwhile. We’re happy to provide support from our end.

**Comment by jmcphers** [comment]
rlang's `last_trace` now shows a pretty nice ASCII visualization of the tree.

**Comment by mikebessuille** [comment]
High priority for Hadley - consider when we have a new R developer

**Comment by hadley** [comment]
In most programming languages, the call stack is linear, but in R it’s a tree because lazy evaluation means that the evaluation of an argument to kick off at different places in the call stack. 

For example, take this relatively simple sequece of calls which is made mildly more complex by introducing by some `tryCatch()`s:

``` r
library(rlang)

x1 <- function() x2()
x2 <- function() tryCatch(x3())
x3 <- function() tryCatch(x4())
x4 <- function() abort("Error")

x1()
#> Error: Error
```

The traceback is quite long:

``` r
traceback()
#> 11: stop(fallback)
#> 10: signal_abort(cnd, .file)
#> 9: abort("Error") at #1
#> 8: x4()
#> 7: tryCatchList(expr, classes, parentenv, handlers)
#> 6: tryCatch(x4()) at #1
#> 5: x3()
#> 4: tryCatchList(expr, classes, parentenv, handlers)
#> 3: tryCatch(x3()) at #1
#> 2: x2() at #1
#> 1: x1()
```

It’s more clear what’s going on if you consult rlang’s tree represention:

``` r
last_trace()
#> <error/rlang_error>
#> Error in `x4()`: Error
#> Backtrace:
#>     ▆
#>  1. └─global x1()
#>  2.   └─global x2()
#>  3.     ├─base::tryCatch(x3())
#>  4.     │ └─base tryCatchList(expr, classes, parentenv, handlers)
#>  5.     └─global x3()
#>  6.       ├─base::tryCatch(x4())
#>  7.       │ └─base tryCatchList(expr, classes, parentenv, handlers)
#>  8.       └─global x4()
```

The `tryCatch()`s aren’t really involved in the sequence of calls that
leads to the error, so rlang can automatially remove them:

``` r
last_error()
#> <error/rlang_error>
#> Error in `x4()`: Error
#> Backtrace:
#>  1. global x1()
#>  2. global x2()
#>  5. global x3()
#>  8. global x4()
#> Run `rlang::last_trace()` to see the full context.
```

As you can imagine, this leads to considerable simplification of the error in real code (particularly shiny apps). This makes it much easier to understand where the error is coming from and makes debugging a little easier. 

The example above uses `rlang::abort()`, but the same principle call tree can be captured from any base error by using the (new) [`global_entrace()`](https://rlang.r-lib.org/reference/global_entrace.html)

**Comment by mikebessuille** [comment]
@romainfrancois I think this would be a good one for you to tackle eventually -but this is certainly not a "good first issue".

**Comment by mikebessuille** [comment]
Per Jonathan: This will require some UX work because we will want to implement our own visualization of the tree in RStudio's error inspector (we can't just use rlang's since many people don't have that package installed)

**Comment by jmcphers** [comment]
We *could* borrow the rlang implementation as a copy in our own codebase, but it'd look a lot nicer if we rendered our own (collapsible?) tree since the error traceback widget is fully composed of custom HTML.

**Comment by romainfrancois** [comment]
Before I adopt this one, I want to better understand what it is about. So from code above (modified): 

```r
x1 <- function() x2()
x2 <- function() tryCatch(x3())
x3 <- function() tryCatch(x4())
x4 <- function() stop("Error")

x1()
```

we get: 

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/2625526/158194323-555e335f-1e55-4d94-a53f-290c82756b85.png">

and then we can expand the "Show Traceback" to get this: 

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/2625526/158194420-8d1f0ec0-8c61-40f1-ba91-d07c594c3a44.png">

and so we'd like it to be some sort of navigable tree widget thing ? For now, let me study how the ide ends up showing this: 

<img width="180" alt="image" src="https://user-images.githubusercontent.com/2625526/158195137-c7c6229d-2366-4efc-b508-b6c1171d1552.png">





Note that with current `rlang` we don't get invitation to show the traceback: 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/2625526/158194797-e79d26fe-786e-451b-bb6c-903ef15dbbbe.png">

**Comment by romainfrancois** [comment]
So let's close this for now, as it is being approached in `rlang` : https://github.com/r-lib/rlang/pull/1400 

We may, at a later time want to support [cli::boxx()](https://cli.r-lib.org/reference/boxx.html) or something, as a way to better style `rlang` errors.
