### ISSUE TITLE
update libclang

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2394]
The versions of `libclang` used by RStudio are a bit old now, and have incomplete support for the newer C++ standards. We should consider upgrading `libclang` to support modern C++.

**Comment by jjallaire** [comment]
Ping me if/when you do this as there are some additional headers we need to include (for each C++ compiler) in order to make completion work correctly and I can run you through how this was done previously.

**Comment by kevinushey** [comment]
After chatting with @jjallaire we want to investigate whether we can do this for RStudio v1.2, especially with a new Windows toolchain on the horizon that will bring C++14 and C++17 support (and so C++17 support will now effectively be available on all major platforms R is used on).

Some major items here:

- We want to stop embedding `libclang` on all platforms instead of Windows, and instead rely on the version of `libclang` available on the system. We need to update the paths here (https://github.com/rstudio/rstudio/blob/63961651886c6cacdd6d7f91bbbacf6da1457be3/src/cpp/core/libclang/LibClang.cpp#L47-L66) to accommodate new locations where we might discover `libclang`.

- On Windows, we should check to see if the official MSVC builds of `libclang` can be used instead of the third-party MinGW `libclang` build we currently have.

- We'll have to review `install-libclang` to make sure the necessary updated headers are packaged and installed with RStudio.

**Comment by jmcphers** [comment]
I think this is resolved by https://github.com/rstudio/rstudio/commit/f41a449f1f6067cd94820df6bdaad6a5ac99f94f (let me know if there's still work to do here!)
