### ISSUE TITLE
Indent in Rmarkdown stuck at 8 spaces (1.2)

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2395]
1. Create new rmarkdown file
2. Navigate to setup chunk and put cursor at start of line
3. Tab inserts 8 spaces, even though I have set 2 (and that is respected in `.R` files

**Comment by jjallaire** [comment]
I saw the same thing on v1.2 and it caused me to switch back to v1.1

**Comment by ronblum** [comment]
Note: this appears to affects Global Options. When Project Options are set, the issue goes away.

**Comment by kevinushey** [comment]
Will be fixed with https://github.com/rstudio/rstudio/commit/b96211052749fd7d00b1bcf8079de2249a63c17e.

**Comment by kevinushey** [comment]
In the meantime, you can work around this with e.g.

```
.rs.writeUiPref("auto_detect_indentation", FALSE)
```

**Comment by kevinushey** [comment]
Should be fixed with latest daily builds -- please re-open if you're still having trouble.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
