### ISSUE TITLE
Double-tapping with two fingers zooms in

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2396]
(Requires mac)

1. Perform a two-fingered double-tap anywhere on the RStudio UI
2. UI zooms in

This is useful in Safari, but seems like it should be disabled in RStudio.

**Comment by ronblum** [comment]
Note: this is not an issue (feature?) in 1.1, only in 1.2.

**Comment by gtritchie** [comment]
Doesn't repro for me on 1.3.380 daily (macOS desktop). It is supposed to do this (double-tap zoom-in for server builds), see https://github.com/rstudio/rstudio/pull/5034

**Comment by gtritchie** [comment]
Closing again, please reactivate if I'm missing something.
