### ISSUE TITLE
"Right"-click menu does nothing (1.2)

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2397]
1. Open editor and select some text
2. Right-click on selection
3. Neither "copy" nor "unselect" appears to do anything

**Comment by ronblum** [comment]
Note: `copy` (but not `unselect`) works in R Markdown documents, but not others (including plain R, Sweave, C++).

**Comment by ronblum** [comment]
Actually, there's a big regression here: in 1.1, there are many more options, which have disappeared in 1.2.

Right-click in Mac Desktop 1.1.442:
<img width="326" alt="old_right_click" src="https://user-images.githubusercontent.com/31009952/37412076-a39c9026-277a-11e8-9beb-09765df0a4b5.png">

Right-click in Mac Desktop 11.2.407:
<img width="165" alt="new_right_click" src="https://user-images.githubusercontent.com/31009952/37412146-bc9d0330-277a-11e8-892c-56b64f4cee5d.png">

**Comment by hadley** [comment]
Most of those options don't really apply to RStudio docs, so I wouldn't call it a big regression. (Although inspect element was occasionally useful)

**Comment by kevinushey** [comment]
Should be fixed in the next dailies (although I think the macOS builds are behind right now?)
