### ISSUE TITLE
Bash heredocs break .Rmd syntax highlighting

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2398]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.442
    OS Version      : Windows 10 x64
    R Version       : R 3.4.3

---

![capture](https://user-images.githubusercontent.com/1976582/37416512-31c0678e-276b-11e8-81f8-3519ebdbe657.PNG)

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
