### ISSUE TITLE
Improve R Notebook UI support for custom knitr engines

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2401]
In RStudio 1.2, we've improved the support for running code that uses custom knitr engines in the notebook. However, there aren't any affordances for running code that uses these engines. We could make the following enhancements:

### Show the Run button on all chunks

Today, we only show the Run button on chunks which the IDE deems to be "runnable", based on a hard-coded list of supported engines.

https://github.com/rstudio/rstudio/blob/938b3174615cedcaab08a2af0ff64f0487b80bd0/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetChunks.java#L273-L274

To better support custom knitr engines, we could show the Run button on every chunk, with the expectation that chunks will usually be runnable with an engine of some kind by the time they are executed. 

This means we'll sometimes show it on chunks which cannot be run with a custom engine, and may need to show an appropriate message when this happens. It'd be nice if we could only show Run when an custom engine is defined, but this is more expensive to plumb, and the engine can change at runtime (possibly even during the execution of other previous chunks as in the below example), so trying to be too dynamic is likely to lead to less predictable behavior.

### Show output for custom knitr engines

We don't currently show the output from chunks executed with custom engines; we should show the results of evaluating the chunk with the custom engine. 

### Example

Here's an example of a document which uses a custom knitr engine:

    ---
    title: Hello Text Data
    ---
    Register the engine.
    ```{r}
    knitr::knit_engines$set(data = function(options) {
      assign(options$output.var, read.table(text = options$code), envir = knitr::knit_global()
      )
      NULL
    })
    ```
    Input data to `x`.

    ```{data, output.var='x'}
    26 A L
    30 A L
    18 A M
    20 B H
    ```
    Print the data.
    ```{r}
    x
    ```

**Comment by kevinushey** [comment]
In fact, when support for `reticulate` was implemented we also added support for the execution of arbitrary user-defined engines, so we might be able to just remove the whitelisting of certain engines altogether.
