### ISSUE TITLE
Git revert changes dialog highlights both buttons

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2405]
1. Open a project that uses git
2. Make a change to a file
3. In the git dialog, select a file and click "revert"

<img width="474" alt="screen shot 2018-03-14 at 4 30 02 pm" src="https://user-images.githubusercontent.com/4196/37432015-f9809850-27a4-11e8-8180-0fb7ef3c56a4.png">

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
