### ISSUE TITLE
Need clarifications for installing Rstudio under Ubuntu 16.04

### ISSUE THREAD

**Issue by codingbutstillalive** [rstudio/rstudio#2408]
Dear All!

I know that you can find dozens of install instructions via Google. But I find them rather uninstructive and confusing after all. It would be much better if there were some install instructions provided directly by Rstudio on their website.

1.) I do not want to use some external package sources (ppa), where I cannot trust the creators. That seems to rule out solutions like this one: http://anglehit.com/install-r-and-rstudio-in-ubuntu-16-04-lts/

2.) I am not certain if simply installing the .deb packages from Rstudio's main webpage is enough. Some sources say that you have to install some additional Ubuntu packages (e.g. "libjpg62" mentioned here: https://askubuntu.com/questions/862403/install-the-lastest-version-of-rstudio). Others do not comment about that (e.g. this one here https://support.rstudio.com/hc/en-us/community/posts/209074748-Installing-RStudio-Desktop-on-Ubuntu-16-04-LTS).

Honestly, this confusing mess is frustrating and I don't understand why Rstudio webpage is not giving a clear description.

What's the right way of doing it?

In addition, I actually want to install an update of my Rstudio installation. So the question is also about updating. The last update I run resulted in a slow-downed Rstudio. So I now want to update to one of the latest builds.

**Comment by ronblum** [comment]
@codingbutstillalive Thanks for the suggestions—I'll mark it as an enhancement for us to review.

Regarding updates, what is your question? The latest update, 1.1.442, was just released and is available at the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download). If you're interested in trying out 1.2, there are [daily builds available](https://dailies.rstudio.com/), but keep in mind that these are still in the development process and meant for testing only.

**Comment by codingbutstillalive** [comment]
Well, the question is about how to install the updates. As I explained, there are ambigous descriptions, and I would like to know how to do it the right way.

Besides that, I think it's very good that you marked it as an enhancement. A proper description on the Rstudio website would be very helpful.

**Comment by ronblum** [comment]
That's a good point. For what it's worth, you can use `gdebi` for installation. After installing R, to install RStudio Ubuntu Desktop 1.1.442:

```
sudo apt-get install gdebi-core
wget https://download1.rstudio.org/rstudio-xenial-1.1.442-amd64.deb
sudo gdebi rstudio-xenial-1.1.442-amd64.deb
```

**Comment by codingbutstillalive** [comment]
Alright. Thanks! Will this also update the existing installation?

**Comment by ronblum** [comment]
Yes. You'll even get a message during the installation, similar to this:
```
Unpacking rstudio (1.1.442) over (1.1.383) ...
```

**Comment by codingbutstillalive** [comment]
Actually, that didn't work. Rstudio is not opening anymore after the re-install with gdebi.

**Comment by jmcphers** [comment]
Simply installing the .deb should be sufficient -- if more is required let us know and we'll update the right places. 

The daily build is indeed still in testing and we'd recommend you use the stable build for critical work for now!
