### ISSUE TITLE
Git and SVN executable path options set to home directory if programs are not installed

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2412]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.1.442 & 1.2.412-5
    OS Version      : CentOS 7.4 & Ubuntu 16.04
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Make sure `git` and `svn` are _not_ installed.
2. Remove the RStudio user settings file:
 - Desktop: `rm ~/.rstudio-desktop/monitored/user-settings/user-settings`
 - Server: `rm ~/.rstudio/monitored/user-settings/user-settings`
3. Start RStudio.
4. Go to `Tools -> Global Options -> Git/SVN`. Both the Git and SVN entries say "(Not Found)".
5. Click on `General`.
6. Click `OK`.
7. Go to `Tools -> Global Options -> Git/SVN`. 
- In some cases, Git still says "(Not Found)", but SVN has the home directory listed.
- In other cases, both entries have the home directory.

### Describe the problem in detail

If SVN (and in some cases, Git) is not installed and no value is provided for the executable option, then the first time global options are updated, the SVN (and Git) executable is set to the home directory—not even a file.  This is true even if no changes were made to any options.

In the user settings file, `vcsSvnExePath` will be set to the home directory. For example, when the SVN problem occurs on Desktop,
```
grep ExePath ~/.rstudio-desktop/monitored/user-settings/user-settings 
```
will return 
>vcsGitExePath=""
vcsSvnExePath="/home/ron"
>

Another example of both failing on Server:
```
grep ExePath ~/.rstudio/monitored/user-settings/user-settings
```
returns
>vcsGitExePath="/home/ron"
vcsSvnExePath="/home/ron"
>

If the programs are installed after the problem occurs, the paths will remain as the home directory until they're updated by the user.

### Describe the behavior you expected

SVN and Git executable options should remain unchanged, with the value "(Not found)", if the programs are not installed.

Note that when Git and SVN are installed (replace step 1 with "Make sure `git` and `svn` _are_ installed"), the end result is that both paths are set to blank, so that on Desktop
```
grep ExePath ~/.rstudio-desktop/monitored/user-settings/user-settings 
```
and on Server
```
grep ExePath ~/.rstudio/monitored/user-settings/user-settings 
```
return
>vcsGitExePath=""
vcsSvnExePath=""
>

The fields in the Global Options screen will be automatically filled with the locations of the executables that RStudio finds in the path, as long as these entries are blank.

Also, the problem always occurs with SVN. After testing several combinations of operating system and RStudio version, I'm not sure yet which have a Git problem. I'd need to do a much more exhaustive test—I only tested five so far. Let me know if you need me to get the exact combinations.

**Comment by balajiabcd** [comment]
For me git executable path is coming, But SVN executable path showing (Not Found). If it is because of "may be not installing the SVN", how to check whether SVN is installed or not if not how to install it in WINDOWS ????

**Comment by ronblum** [comment]
@balajiabcd There are SVN downloads available here: https://subversion.apache.org/packages.html#windows I don't know enough to recommend one or the other, but these are possible options.

**Comment by AndresPenaloza** [comment]
Thanks, Ronblum. I was stocked with the SVN path. It worked.

**Comment by ronblum** [comment]
@AndresPenaloza You're welcome!

**Comment by lminghao055** [comment]
@ronblum Can I ask that why my svn path said not found but I already downloaded svn and git
