### ISSUE TITLE
Dragging file "over" RStudio beachballs

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2413]
This is a weird one

1. Open RStudio
2. Drag a file (e.g. png) from the desktop over the application (don't drop)

I get ~10s of beachball

(Most likely 1.2 only)

**Comment by kevinushey** [comment]
I wasn't able to reproduce. Can you provide any more details? Does this consistently reproduce for you? Does it only occur for certain `.png`s or all kinds? Does the size of the `.png` make a difference?

**Comment by hadley** [comment]
Hmmm seems to be ok now 😬
