### ISSUE TITLE
Can't select bottom line of text in console if selection started above

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#2416]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.407
    OS Version      : macOS
    R Version       : 3.4.3

### Steps to reproduce the problem

If you select text in the console starting from somewhere above the last line (where the cursor is) and then move downward to select the last line, it won't actually select that line.

In this example, the console is above the Help panel, and it selects text in there. If you then copy and paste, you get a lot of unwanted IDE UI text.

![image](https://user-images.githubusercontent.com/86978/37499289-d738d694-2890-11e8-8f8c-7133346e1ddf.png)

It is also possible to first select the currently typed text and then also select previous text from the console:

![image](https://user-images.githubusercontent.com/86978/37499337-1495054e-2891-11e8-97d7-05d5461345a0.png)

**Comment by MariaSemple** [comment]
@wch Confirmed this is still an issue.

**Comment by mikebessuille** [comment]
We had a look at this and despite that it is a real issue, we don't see other upvotes or comments.  It's unlikely we will get to this in the next few releases and we feel the impact is low, so closing this.
