### ISSUE TITLE
[Small UI issue] When creating new project, the input fields are misaligned

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#2417]
Windows 7, RStudio 1.1.414

When creating a new project using the rstudio menu, the two text input fields are misaligned

![rstudio-create-project-fields-misaligned](https://user-images.githubusercontent.com/952340/37504440-bb633940-28b4-11e8-8216-671937e7fabe.PNG)

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
