### ISSUE TITLE
depend on reticulate 1.6 when it reaches CRAN

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2418]
Re: https://github.com/rstudio/rstudio/pull/2265

**Comment by kevinushey** [comment]
Fixed with https://github.com/rstudio/rstudio/commit/b81d4336bb1cab3251638186a52955d6c0d9aa76.

To test, first ensure the `reticulate` package is not installed:

```
remove.packages("reticulate")
```

Then, try opening a Python document, e.g.

```
file.edit("test.py")
```

Then enter the contents:

```
1 + 1
```

And then type <kbd>Ctrl + Enter</kbd> to execute it. You should get a dialog indicating that you need to install `reticulate` to execute Python code.

**Comment by ronblum** [comment]
Up to 1.10 now:

```
> packageVersion("reticulate")
[1] ‘1.10’
```
