### ISSUE TITLE
Add YAML reference guide to help menu

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#2421]
Add a YAML reference guide to the IDE help menu (similar to the Markdown reference guide).

![image](https://user-images.githubusercontent.com/7519295/37541988-f6437c2c-2932-11e8-95b6-537ad1e0a62b.png)

**Comment by jmcphers** [comment]
We don't really have a Markdown reference guide, just one for R Markdown (which is pretty much the place you do YAML in RStudio). It now includes some YAML help.

![image](https://user-images.githubusercontent.com/470418/70298682-50c0a080-17a7-11ea-96a2-cf8888c5c0d0.png)

**Comment by nwstephens** [comment]
Thanks to Malcolm, we now have an excellent guide: 

https://ymlthis.r-lib.org/articles/yaml-overview.html

There would also be several interesting ways to integrate ymlthis into the IDE (assuming the package is mature enough).

**Comment by nwstephens** [comment]
Thanks to Malcolm, we now have an excellent guide: 

https://ymlthis.r-lib.org/articles/yaml-overview.html

And you're correct, this isn't a cheatsheet, but would be a hyperlink or HTML:

![image](https://user-images.githubusercontent.com/7519295/72753903-38101c80-3b94-11ea-9858-fdf75f121730.png)

There would also be several interesting ways to integrate ymlthis into the IDE (assuming the package is mature enough).
