### ISSUE TITLE
Display full path of file being editited in window title

### ISSUE THREAD

**Issue by freestyle35** [rstudio/rstudio#2427]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 10
    R Version       : 3.4.1 64 bit
    Feature request or Bug: Feature request   

### Steps to reproduce the problem
Open file in Rstudio

### Describe the feature request
Display the fully path of the file being edited in the window title. Currently, the only way to know which file you are editing (fully qualified name) is to hover over the file name tab. This is tedious if you have several ui.R, server.R, app.R, etc... files open

How about displaying something like:
`<Project Name> - [<full path and name of file>] - RStudio 1.1.383 - R 3.4.1 64 `

thanks

**Comment by ronblum** [comment]
Thanks for the suggested enhancement. We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by freestyle35** [comment]
I'm using Version 1.1.456 of RStudio. How can I use this enhancement? I was expecting a checkbox similar to 'Display full path of current file in title bar' in Global Options -> Code -> Display 

thanks

**Comment by kevinushey** [comment]
Sorry; this feature has not yet been implemented.

**Comment by faridcher** [comment]
related to this issue:

https://stackoverflow.com/questions/45119432/more-meaningfull-window-title-for-rstudio
https://community.rstudio.com/t/can-i-get-rstudio-to-show-the-project-name-rather-than-the-folder-location-on-the-window-name/3361

My suggestion is the following pattern: 

"(ProjectName)"+ "space" + "basename of entire filename " + "Rstudio"

This is succinct to distinguish a project, file and application

E.g. compare my Sublime Text window title with Rstudio window title:
![clipboard05](https://user-images.githubusercontent.com/9982519/44903361-93ccd200-ad21-11e8-9f8e-9772c58e5d68.jpg)

**Comment by jmcphers** [comment]
Note: Window title would also need to adapt to non-file content; see https://github.com/rstudio/rstudio/issues/3664.

**Comment by bkmontgom** [comment]
I would like to see just enough of the path to differentiate filenames that are the same.  For example: "R/file.R" and "tests/file.R"

**Comment by gtritchie** [comment]
Keep this change in mind if implementing this more general approach: https://github.com/rstudio/rstudio/pull/5943

**Comment by nriley** [comment]
[Talon](https://talonvoice.com) uses the window title to determine which code language to activate, so you get voice commands for (e.g.) R or Python as appropriate. I'm currently working on improving the [RStudio support in our community configuration](https://github.com/talonhub/community/tree/main/apps/rstudio). Because RStudio only puts the project name/path in the window title, not the filename/extension, Talon can't detect the current code language in RStudio the way it can with other editors.

I also tried looking at what gets exposed (on Mac at least; Talon supports Mac/Windows/Linux) via accessibility. I could potentially get the focused element then parse the AXTitle of the parent selected tab to pull out something that looks like a file extension (e.g. "R Markdown filename.Rmd Close document tab") but (a) that's pretty ugly, particularly if this text is localized and (b) there's no way I could figure out how to detect when focus changes to a different tab, so I didn't pursue this further.

Until this is addressed, I'll default to the R language for now when RStudio is active, since it the most common.

Thanks for considering this!

**Comment by aushev** [comment]
any chance this could be addressed at some point? You already have exactly that thing for the projects, it should not be difficult to enable it for all files?

**Comment by ronblum** [comment]
@aushev I'll mark this for review (or re-review).

**Comment by gtritchie** [comment]
There's quite a lot to this (i.e. it sounds simple, but isn't):

- Handle both Visual Editor and regular editor
- What to show when a non-document tab is selected:
    - ProfilerEditingTarget (profiler results)
    - CodeBrowserEditingTarget (i.e. read-only code browser)
    - DataEditingTarget (e.g. `View(mtcars)`)
    - UrlContentEditingTarget (e.g. execute `data()` in console)
    - ObjectExplorerEditingTarget (e.g. make sure there's a terminal session then in console do `View(.rs.api.terminalContext(.rs.api.terminalVisible()))`)
    - maybe some others?
 - multiple source columns, and making sure the name we show in the title is for the most recently focused source column, even if the source column doesn't currently have focus (e.g. focus is in the console or elsewhere)
- multiple satellite windows with (potentially) multiple tabs in each
- updating the title when active tab switches via clicking on a tab (main window and satellites)
- updating the title when the active tab changes via keyboard shortcuts (next tab, previous tab), which can happen even when focus isn't in the source area (applies to main window and satellite windows)
- have to decide what configuration options we want (e.g. show project name, show branch name, show only the filename, show the full path, or enough of the path to distinguish from other opened files with the same name, etc.; do we reconcile uniqueness against all open files even in different windows or source columns, or only the current one, etc.)
- do we allow configuring what order this information is shown in?
- we currently have slightly different behaviour for Server/Workbench versus Desktop in some cases (e.g. we don't show the current branch in the main window title for Server/Workbench like we do on Desktop, but we do for satellite windows on both); need to reconcile this

Playing with the events currently available, I didn't find a tidy way to hook this in that covers all cases so likely need some new events or more consistent firing of existing events when dealing with source columns vs. satellite windows, etc.

It can be done, of course, but feels like several days of investigation and work, plus, ideally, automation.
