### ISSUE TITLE
Please create option that allows disable drag-and-drop in the RStudio IDE

### ISSUE THREAD

**Issue by freestyle35** [rstudio/rstudio#2428]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 10
    R Version       : 3.4.1 64 bit
    Feature request or Bug: Feature request   

### Steps to reproduce the problem
Open file in Rstudio

### Describe the feature request
Please create a global option that allows developers to disable drag-and-drop in the RStudio IDE. I don't know any developer ever that writes code by dragging and dropping. Cut-paste-tweak rules! Drag-and-drop just creates issues when navigating code in the IDE using the mouse.

thanks

**Comment by ronblum** [comment]
Thanks for the feature suggestion. We'll take a look at your suggested enhancement as we continue to develop new versions of RStudio.

**Comment by dfalty** [comment]
Verified on version 1.2.1090.
