### ISSUE TITLE
Unintended not undoable zoom on MacOS

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#2429]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.431
    OS Version      : 10.13.3 
    R Version       :  3.4.4

### Steps to reproduce the problem

I am getting annoying behavior on my Mac:
Some gesture on my touchpad seems to trigger it, but I have not found out exactly which one.
It happens that then the source pane enlarges to fill the whole RStudio frame. The font also gets larger, and al the other panes disappear. The keyboard shortcuts and the menu items to Show all Panes do not work. I have to close and restart RStudio to get the normal 4 pane layout again.
This is what it looks like when the problem surfaces.

This does not happen with the production release of RStudio.

![2018-03-17_15-05-46](https://user-images.githubusercontent.com/157619/37556382-6f21a0fc-29f5-11e8-8181-550a9d9f793c.png)

**Comment by kevinushey** [comment]
The source pane can be zoomed with e.g. <kbd>Ctrl + Shift + 1</kbd>, and pressing those keys again should un-zoom the pane. Does that help in your case?

**Comment by neuwirthe** [comment]
Problem solved. The situation is created by two-finger double-tap (which I did "unconsciously"),
and doing the two-finger double-tap restores the original pane configuration.

**Comment by jmcphers** [comment]
Thanks for following up! This is currently tracked in https://github.com/rstudio/rstudio/issues/2396.
