### ISSUE TITLE
More then 2 folds on one line not unfoldable

### ISSUE THREAD

**Issue by EmilBode** [rstudio/rstudio#2434]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : OSX 10.13.3 (High Sierra)
    R Version       : 3.4.3 (Kite-Eating tree)

### Steps to reproduce the problem
Write some code with multiple foldable sections, something like this:
```{R}
if(a==1) {
  print('one') 
} else if(a==2) {
  print('two')
} else  {
  print('many')
}
```
- Fold all sections
- Click the middle section (after (a==2))

### Describe the problem in detail
Nothing happens, i.e. the section does not unfold

### Describe the behavior you expected
I expect the section to unfold.
Behavior is as expected for the first and last section, and you can unfold by first unfolding first or last section.
With 4 sections the behaviour is comparable: first and last are unfoldable, middle two are not.

**Comment by ronblum** [comment]
Reproduced on Windows and Linux, as well. As soon as a line break is inserted and the collapsed code becomes the first or last collapsed block, it is expandable. `Expand` with the menu or shortcut doesn't work, either. Only `Expand All`works, which expands all of the collapsed blocks.

**Comment by kevinushey** [comment]
The R mode in Ace handles this by making sure multiple fold markers can't show up on the same line:

![screen shot 2018-03-19 at 9 13 47 am](https://user-images.githubusercontent.com/1976582/37607655-dd5fdbd6-2b55-11e8-9836-034cb20c12c3.png)

Perhaps we could, or should, be doing the same thing?
