### ISSUE TITLE
Attached packages at the top of package-pane

### ISSUE THREAD

**Issue by fjcarton** [rstudio/rstudio#2435]
Hi people from RStudio,

Recently I have come across a small irritation in your program, which I think would be very easy to fix, I think. The problem is that I would like to see in a quick glance of the Package-Pane (see screenshot) which packages are currently loaded in my project or session. It would be nice if a package is loaded in my session that it would come up in this screen such that all loaded packages are at the top.
![image](https://user-images.githubusercontent.com/26654808/37591741-be9358ec-2b6c-11e8-93e4-715ab5371444.png)

I hope that you can include this for me, since this would make my RStudio experience perfect ;)

With kind regards

**Comment by ronblum** [comment]
@fjcarton Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio. And thank you for the kind words about our product—it's our aim to provide you with the best experience possible!

**Comment by AshesITR** [comment]
NB that you can currently see this by clicking the "Global Environment" button in the Environment pane,
if you only want to see the information.

![2018-03-20 13_42_20-clipboard](https://user-images.githubusercontent.com/2363178/37655088-9359520c-2c44-11e8-84be-eda0032cf812.png)

Alternatively, search() or sessionInfo() provide this information in the console.

```
> search()
 [1] ".GlobalEnv"        "tools:rstudio"     "package:stats"     "package:graphics"  "package:grDevices"
 [6] "package:utils"     "package:datasets"  "package:methods"   "Autoloads"         "package:base"     
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0
```

**Comment by fjcarton** [comment]
@AshesITR Yes, that are also options, but with 'ctrl+7' shortcut you can quickly go to the packages pane, with which you quickly see all your packages (if implemented off-course). I use a lot shortcuts in rstudio ;)

**Comment by AshesITR** [comment]
@fjcarton If you really want a shortcut you could make an addin alias to search() or sessionInfo() and then bind a keyboard shortcut to it ;)
Using this myself for some frequently used code stubs for importing / exporting files.
