### ISSUE TITLE
SUSE Server installation requires ignoring public key for signature verification

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2436]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.432 (and 1.1)
    OS Version      : openSUSE 42.3 (12.3)
    R Version       : 3.4.3

### Steps to reproduce the problem

Install RStudio Server on SUSE/openSUSE, e.g.
`zypper install rstudio-server-suse-1.2.432-x86_64.rpm`
Installation can continue by choosing `i` for `ignore`.

### Describe the problem in detail

During installation, SUSE complains that signature verification failed due to missing public key:

```
Retrieving package rstudio-server-1.2.432-1.x86_64                                                  (1/1),  43.3 MiB (325.2 MiB unpacked)
rstudio-server-suse-1.2.432-x86_64.rpm:
    Header V4 RSA/SHA1 Signature, key ID e331692f: NOKEY
    V4 RSA/SHA1 Signature, key ID e331692f: NOKEY

rstudio-server-1.2.432-1.x86_64 (Plain RPM files cache): Signature verification failed [4-Signatures public key is not available]
Abort, retry, ignore? [a/r/i] (a): i
Checking for file conflicts: ......................................................................................................[done]
```

Using the option `--no-gpg-checks` will issue the warning but skip the need for `ignore`:
```
rstudio-server-suse-1.2.432-x86_64.rpm:
    Header V4 RSA/SHA1 Signature, key ID e331692f: NOKEY
    V4 RSA/SHA1 Signature, key ID e331692f: NOKEY
rstudio-server-1.2.432-1.x86_64 (Plain RPM files cache): Signature verification failed [4-Signatures public key is not available]
Accepting package despite the error. (--no-gpg-checks)

Checking for file conflicts: ......................................................................................................[done]
```

### Describe the behavior you expected

No warning about keys.

**Comment by ronblum** [comment]
YaST, the GUI installer, behaves similarly when it reaches this point: a dialog pops up saying that RStudio is broken. Details show that signature verification failed. Clicking on `Ignore` will bypass this and successfully complete installation. 

<img width="392" alt="open_suse_broken_initial" src="https://user-images.githubusercontent.com/31009952/38501048-0e0df79c-3bda-11e8-8036-d6ab6b7f6de2.png">
<img width="779" alt="open_suse_broken_details" src="https://user-images.githubusercontent.com/31009952/38501051-101643e6-3bda-11e8-8327-89bcef7b6ea7.png">

**Comment by jmcphers** [comment]
> signature verification failed due to missing public key

This is expected; you need to import RStudio's code-signing key before you can use it to validate signatures.

Did you follow the instructions here?

https://www.rstudio.com/code-signing/

(If so, we should amend the above to include SuSE specific instructions.)

**Comment by ronblum** [comment]
Thanks! No, I did not—it works once I follow the instructions. There's no link to this page on the SUSE tab of the download pages; we should add it, like we have for the other Linux environments.

**Comment by jmcphers** [comment]
I've added it (a little earlier than the others since it seems like SUSE is pickier about signatures).
