### ISSUE TITLE
clicking png files in the files pane does not show them in an external viewer

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#2440]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.430
    OS Version      :  OS X 10.12.6 (16G1212)
    R Version       :  3.4.2

### Steps to reproduce the problem

Click a PNG file in the files pane, e.g.

<img width="554" alt="screen shot 2018-03-19 at 9 10 10 am" src="https://user-images.githubusercontent.com/104391/37597281-5f0279ba-2b55-11e8-8c1d-ba045d32ab59.png">

### Describe the problem in detail

The file is not opened in an external viewer.

### Describe the behavior you expected

The file is opened in an external viewer (this is the behavior of pre-qtwebengine versions of the IDE).

**Comment by jjallaire** [comment]
On further experimentation, it seems as if images are shown in an external web browser (Chrome in my case), however the browser is not brought to the foreground so it appears as if nothing happened. Previously images were shown in Preview (which was brought to the foreground) and I think this should continue to be the default behavior.

**Comment by jjallaire** [comment]
PDF appears to no-op

HTML View in Web Browser also appears to no-op

HTML Open in Editor works as expected.

**Comment by kevinushey** [comment]
This might be a similar manifestation of https://github.com/rstudio/rstudio/issues/2191.

It looks like the attempts to open a new file go through here:

https://github.com/rstudio/rstudio/blob/d9e60252c337382382c055a709a044c3f3bd68f7/src/gwt/src/org/rstudio/studio/client/common/impl/WebWindowOpener.java#L195-L214

That call seems to be succeeding (a new window is successfully opened), but for some reason the window never actually seems to 'exist' on the screen. However, it seems like we might just be going through the wrong code path here -- should that only be used for RStudio Server?

**Comment by jjallaire** [comment]
Generally speaking on the desktop we should be going through the DesktopWindowOpener: https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/common/impl/DesktopWindowOpener.java

That said, it may be that for Cocoa we used the WebWindow Opener and that worked fine in that scenario (I don't recall).

**Comment by kevinushey** [comment]
Looks like DesktopWindowOpener delegates to WebWindowOpener (at least in the v1.2 builds)

![screen shot 2018-03-20 at 8 45 50 am](https://user-images.githubusercontent.com/1976582/37665710-1b3ff83a-2c1b-11e8-921a-5cf6c703252c.png)

**Comment by jjallaire** [comment]
This is what we did in Cocoa for browsing URLs: externally: https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop-mac/Utils.mm#L137-L150

Seems like we need to find a way to get this same code to execute for the Chromium version?

**Comment by kevinushey** [comment]
It looks like, in RStudio v1.1, links using the `file://` protocol were generated and used; however, in RStudio v1.2 (on macOS) they're using the 'files/' endpoint of the running server.

In other words, in RStudio v1.1, clicking on a PDF in the Files pane would navigate to:

- RStudio v1.1: `file:///Users/kevin/aaa.pdf`
- RStudio v1.2: `http://127.0.0.1:38593/files/kevin/aaa.pdf`

I'll see if I can figure out why that's the case.

**Comment by jjallaire** [comment]
It looks like in v1.2 RStudio thinks it's running in sever mode (as that's the traditional form of URL used in RStudio Server)

**Comment by kevinushey** [comment]
Here's the culprit: https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java#L1383-L1387

I'll see if I can fix this up.
