### ISSUE TITLE
default size of ide is too small

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#2441]
Here's the default I get for a new monitor configuration:

<img width="799" alt="screen shot 2018-03-19 at 9 42 21 am" src="https://user-images.githubusercontent.com/104391/37598955-f7a04a18-2b59-11e8-960d-c00e1ee7dbba.png">

This is the in the neighborhood of 800x600 pixels. I think we should attempt to occupy up to 1100 x 1000 on a new monitor if it's available.

**Comment by jmcphers** [comment]
I've increased the default size -- I found that 1100x1000 looked too tall and narrow after the window chrome was added so squashed it a little to 1200x900 (let me know what you think!)

Also discovered while working on this that it's actually very difficult to get Qt to forget previously cached geometries to get the true default size on launch. You need to remove `~/Library/Preferences/org.rstudio.RStudio.plist`, *and* kill your copy of `cfprefsd` (a daemon that caches the prefs even when they're not stored anywhere on disk).

**Comment by jjallaire** [comment]
Okay, that sounds like the right default!

**Comment by hugesingleton** [comment]
I am not sure what causes that, but only R Studio looks like on the attached screenshots. I can hardly see anything, really. All other programs display well readable fonts.

Zoom: 100%
![rstudio_font_size_normal](https://user-images.githubusercontent.com/47183766/57839595-4ddc6f00-77c7-11e9-9639-d65b1f13cabc.png)

When I set the zoom to, say, 140%, tabs and icons get larger, as expected,
![rstudio_font_larger](https://user-images.githubusercontent.com/47183766/57839628-5b91f480-77c7-11e9-80c2-42389e28119a.png)

but this resizes everything, all panes, so now my plots become unreadable...
![rstudio_font_larger_graphs](https://user-images.githubusercontent.com/47183766/57839660-677db680-77c7-11e9-897e-6f626af63381.png)

When I want to see the plots, I need to switch to 100%, but then I cannot see the tab names.

I can font size for the editor, but not for each pane. Now, after a 2-3 hours of work, my eyes are tired and suffer from that.

Please, allow setting the zoom per pane or increase the default sizes.
