### ISSUE TITLE
Feature suggestion: allow customized syntax highlighting

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#2445]
A lot of the pre-defined color schemes are 80-90% good, but have some aspect that doesn't work well.  It would be really nice to be able to define foreground and background colors, as well as bold/italic, for each type of syntax.

**Comment by jmcphers** [comment]
This is tracked in https://github.com/rstudio/rstudio/issues/1571. Add a thumbs-up to vote for it! :-)
