### ISSUE TITLE
system2('pdflatex', stdout = FALSE) fails on Windows (only with MiKTeX in RStudio)

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#2446]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Windows 7
    R Version       : 3.4.3

### Steps to reproduce the problem

Install MiKTeX: https://miktex.org/download Compile this minimal example `test.tex` in the R console in RStudio via `system2('pdflatex', 'test.tex', stdout = FALSE)`:

```tex
\documentclass{article}
\begin{document}
asdf
\end{document}
```

### Describe the problem in detail

Compilation fails, with a warning message `running command '"pdflatex test.tex"' had status 1`.

### Describe the behavior you expected

It should generate `test.pdf`.

Note that

1. `system2('pdflatex', 'test.tex')` succeeds (i.e. with the default `stdout = ""`).

2. In the default R GUI on Windows (not using RStudio), `system2('pdflatex', 'test.tex', stdout = FALSE)` succeeds, which indicates this issue is likely to be specific to the R console in RStudio (redirecting stdout fails in certain cases?). It also succeeds in the Terminal in RStudio.

3. Other LaTeX distribution such as TeX Live also fails with `stdout = FALSE` on Windows in RStudio. However, TeX Live succeeds with `system2('pdflatex', c('-halt-on-error', '-interaction=batchmode', 'test.tex'), stdout = FALSE)`, but MiKTeX still fails with these extra arguments.

This issue affects rendering R Markdown to PDF on Windows in the R console in RStudio. Several users have reported the issue over the past few days (e.g. https://github.com/rstudio/rmarkdown/issues/1285) and I just figured out the root reason (thanks to the hint by @shrektan https://github.com/yihui/tinytex/issues/28).

**Comment by kevinushey** [comment]
FWIW, this appears to only affect certain programs; that is, `stdout = FALSE` doesn't seem to be universally broken. On my Windows VM, this succeeds:

```
system2(R.home("bin/R"), c("-e", "message('Hello!')"), stdout = FALSE)
```

Surprisingly though, no output is shown on standard error. This does work as expected in Rterm, though:

```
> system2(R.home("bin/R"), c("-e", "message('Hello!')"), stdout = FALSE)
Hello!
```

**Comment by kevinushey** [comment]
@yihui, any chance you can test whether this reproduces using `system()` rather than `system2()`? That is, what happens with:

```
system('pdflatex test.tex >NUL') 
```

**Comment by yihui** [comment]
`system('pdflatex test.tex >NUL')` succeeds, but it does not suppress `stdout` (i.e. I still see the full `pdflatex` log messages). Same thing with `2>&1`.

**Comment by yihui** [comment]
BTW, `system('pdflatex test.tex', show.output.on.console = FALSE)` fails in the R console in RStudio but succeeds in R Gui (PDF is generated and the console output is suppressed).

**Comment by kevinushey** [comment]
As a workaround, does redirecting stdout to a temporary file help?

```
system2('pdflatex', 'test.tex', stdout = tempfile("stdout"))
```

**Comment by yihui** [comment]
Yes! I'll use that workaround for now. Thanks!

**Comment by kevinushey** [comment]
Phew! Glad we have a workaround, at least. Thanks for taking the time to dig in here! We'll see if we can get this fixed up on the RStudio side if possible, but I suspect this could be difficult to fix.

**Comment by yihui** [comment]
Not really a big deal. I'll provide a fix on my side and let users test it. If it works well for them, I'll just close this issue.
