### ISSUE TITLE
Enhanced code completion re:https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion

### ISSUE THREAD

**Issue by dkattimu** [rstudio/rstudio#2450]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423 and 1.1.419
    OS Version      : Windows 10
    R Version       : 3.4.3

### Steps to reproduce the problem
Attempt to type lines 1-4 in the snippet below from this [Rstudio announcement](https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion)

![image](https://user-images.githubusercontent.com/9774414/37617614-05e42830-2b8a-11e8-970f-463dea3c3445.png)

### Describe the problem in detail
Code completion doesn't work as advertised in the [Rstudio announcement](https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion) and shown in snippet above. In particular, after typing:
mat <- matrix(1:4, nrow = 2, ncol = 2)
rownames(mat) <- c("alpha", "beta")
colnames(mat) <- c("gamma", "delta")

Code completion fails to fire when for example you type 
mat["beta", g] 
Note: the gamma (function) may show up but it is obviously the function from .GlobalEnv and not the column name in mat. It may be that the functionality shipped with v.099 and has since been broken.
### Describe the behavior you expected
expected code completion to fire after typing g above just as explained in the link posted by Rstudio.
I would consider the behavior as a bug. 

In addition, is it feasible to support code completion similarly for R6 objects prior to their being loaded in .GlobalEnv?

**Comment by kevinushey** [comment]
This works for me with RStudio v1.1 and RStudio v1.2, but note that you do need to execute the associated lines of code first (the `mat` object needs to exist in the global environment).

![screen shot 2018-03-19 at 3 21 23 pm](https://user-images.githubusercontent.com/1976582/37625442-357b925a-2b89-11e8-85d5-a0a65200860b.png)

I'd recommend filing your other request re: R6 completion in a separate issue.

**Comment by dkattimu** [comment]
Thanks @kevinushey for your reply.

You mentioned that "the `mat` object needs to exist in the environment". My question is based on the premise that it isn't.  That premise is based (accurately or otherwise) on the the following from the [Rstudio announcement](https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion):
"
### SMARTER COMPLETION ENGINE

Previously RStudio only completed variables that already existed in the global environment, now completion is done based on source code analysis so is provided even for objects that haven’t been fully evaluated: 
"


So it boils down to whether not having to be in the global environment is applicable to the `mat` example (which shows up under the same "SMARTER COMPLETION ENGINE" section of the [announcement](https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion)) or not. Could you or anyone confirm whether that is or is not the case?

Thanks!

**Comment by kevinushey** [comment]
RStudio can provide completions for objects defined in a script, but not any smarter semantic analysis. As an example:

![screen shot 2018-03-20 at 9 20 16 am](https://user-images.githubusercontent.com/1976582/37667732-ec360138-2c1f-11e8-9f9c-564e1e21a31d.png)

The orange marker indicates those objects don't actually exist in the global environment, but they're provided as completion results because the completion engine detected that those variables will exist at that point in the script if it were run.

We do a bit of extra introspection for function definitions when possible as well; see e.g.

![screen shot 2018-03-20 at 9 21 24 am](https://user-images.githubusercontent.com/1976582/37667796-1b973a1e-2c20-11e8-92de-1557be376e5b.png)
