### ISSUE TITLE
RevoScaleR is not found when RStudio is used

### ISSUE THREAD

**Issue by axiomoixa** [rstudio/rstudio#2455]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.442
    OS Version      :  RHEL 7.4
    R Version       :  3.4.3 (MS R Client)

### Steps to reproduce the problem
Starting R in RStudio

### Describe the problem in detail
`RevoScaleR` is not found, cannot be loaded in RStudio. Otherwise it is loaded fine when R is launched from shell

### Describe the behavior you expected
Same behavior as launching R from shell

1. The output of sessionInfo() 
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS: /opt/microsoft/rclient/3.4.3/runtime/R/lib/libRblas.so
LAPACK: /opt/microsoft/rclient/3.4.3/runtime/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_10.0.7     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16   
```

### Details
I have installed Microsoft R Client. When I run R from shell, I get 

```
    Microsoft R Open 3.4.3
    The enhanced R distribution from Microsoft
    Microsoft packages Copyright (C) 2018 Microsoft
    
    Loading Microsoft R Client packages, version 3.4.3.0097. 
    Microsoft R Client limits some functions to available memory.
    See: https://go.microsoft.com/fwlink/?linkid=799476 for information
    about additional features.
    
    Type 'readme()' for release notes, privacy() for privacy policy, or
    'RevoLicense()' for licensing information.
    
    Using the Intel MKL for parallel mathematical computing (using 36 cores).
    Default CRAN mirror snapshot taken on 2018-01-01.
    See: https://mran.microsoft.com/.
```

However, when I run R from Rstudio-server, I get only

```
    Microsoft R Open 3.4.3
    The enhanced R distribution from Microsoft
    Microsoft packages Copyright (C) 2017 Microsoft Corporation
    
    Using the Intel MKL for parallel mathematical computing (using 36 cores).
    
    Default CRAN mirror snapshot taken on 2018-01-01.
    See: https://mran.microsoft.com/.
```
The system only has one copy of R, and it together with the library path are correctly specified in `rserver.conf`

```
    cat /etc/rstudio/rserver.conf 
    # Server Configuration File
    rsession-which-r=/usr/bin/Revo64
    rsession-ld-library-path=/opt/microsoft/rclient/3.4.3/libraries/RServer
```

Inside the Rstudio R environment, the library path and R.home look normal
```
> R.home()
[1] "/opt/microsoft/rclient/3.4.3/runtime/R"

    >.libPaths()
    [1] "/home/xyz/R/x86_64-pc-linux-gnu-library/3.4"   
    [2] "/opt/microsoft/rclient/3.4.3/runtime/R/library"
```
However, `RevoScaleR` does not load automatically. When I try to load it manually, I get

```
    > library(RevoScaleR)
    Fehler in library(RevoScaleR) : es gibt kein Paket namens ‘RevoScaleR’
```

**Comment by axiomoixa** [comment]
@ronblum 
Thanks for the tip. However, adding that line prevents rstudio-server from starting
`ERROR Error reading /etc/rstudio/rsession.conf: unrecognised option 'export R_LIBS'; LOGGED FROM: rstudio::core::ProgramStatus rstudio::core::program_options::read(const rstudio::core::program_options::OptionsDescription&, int, char* const*, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, bool*, bool) /root/rstudio/src/cpp/core/ProgramOptions.cpp:152`

**Comment by ronblum** [comment]
Hi @axiomoixa—it looks like you added the line to `rsession.conf`? It should actually be added to
```
/etc/rstudio/rsession-profile
```
which is likely a new file that you have to create yourself.

**Comment by axiomoixa** [comment]
@ronblum 
Apology for mis-reading.
Unfortunately the same result remains
```
> library(RevoScaleR)
Fehler in library(RevoScaleR) : es gibt kein Paket namens ‘RevoScaleR’
```

```
# cat rsession-profile 
export R_LIBS=/opt/microsoft/rclient/3.4.3/libraries/RServer
```

**Comment by ronblum** [comment]
Comparing to what you got before, what do you get for `R.home()` and `.libPaths()`? I believe my environment now has the same values for the properties and Microsoft R Client location, and I get:
```
> R.home() 
[1] "/opt/microsoft/rclient/3.4.3/runtime/R"
> .libPaths() 
[1] "/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4" 
[2] "/opt/microsoft/rclient/3.4.3/libraries/RServer"  
[3] "/opt/microsoft/rclient/3.4.3/runtime/R/library"
```
Also:
```
> packageVersion("RevoScaleR")
[1] ‘9.3.0’
> library(RevoScaleR)
> 
```
(I'm assuming you restarted R/RStudio after making the changing to rsession-profile).

**Comment by axiomoixa** [comment]
Unfortunately I get the same result as before.
```
> library(RevoScaleR)
Fehler in library(RevoScaleR) : es gibt kein Paket namens ‘RevoScaleR’
> R.home() 
[1] "/opt/microsoft/rclient/3.4.3/runtime/R"
> .libPaths()
[1] "/home/xyz/R/x86_64-pc-linux-gnu-library/3.4"   
[2] "/opt/microsoft/rclient/3.4.3/runtime/R/library"
```

```
-rw-r--r--. 1 root root  95 Mar 21 14:19 rsession-profile
[root@RM2USL00063 ~]# cat /etc/rstudio/rsession-profile 
export R_LIBS=/opt/microsoft/rclient/3.4.3/libraries/RServer
```

**Comment by axiomoixa** [comment]
When I launch R from shell, I get
```
> .libPaths()   
[1] "/home/lai/R/x86_64-pc-linux-gnu-library/3.4"   
[2] "/opt/microsoft/rclient/3.4.3/libraries/RServer"
[3] "/opt/microsoft/rclient/3.4.3/runtime/R/library"
```

**Comment by ronblum** [comment]
@axiomoixa There's information about [customizing session launches](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html) and the libPaths help page shows how to [set the location of the package library trees](https://www.rdocumentation.org/packages/base/versions/3.4.3/topics/libPaths). That said, add the following to `/opt/microsoft/rclient/3.4.3/runtime/R/etc/Renviron`:
```
R_LIBS_SITE=/opt/microsoft/rclient/3.4.3/libraries/RServer
```

**Comment by axiomoixa** [comment]
Magic!
it works...
Thanks


I wonder what's the difference between launching R from shell and from rstudio then.

**Comment by ronblum** [comment]
I'm glad it works! Now we can finally say, "RevoScaleR _is_ found when RStudio is used."

By the way, you can delete the `/etc/rstudio/rsession-profile` file.

**Comment by animesh** [comment]
> @axiomoixa There's information about [customizing session launches](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html) and the libPaths help page shows how to [set the location of the package library trees](https://www.rdocumentation.org/packages/base/versions/3.4.3/topics/libPaths). That said, add the following to `/opt/microsoft/rclient/3.4.3/runtime/R/etc/Renviron`:
> 
> ```
> R_LIBS_SITE=/opt/microsoft/rclient/3.4.3/libraries/RServer
> ```

Thanks, It works :+1:  steps followed:
open terminal and execute:
export R_LIBS_SITE=/opt/microsoft/rclient/3.4.3/libraries/RServer
rstudio
