### ISSUE TITLE
Ctrl + 1 doesn't move cursor to Source pane in 1.2.440.

### ISSUE THREAD

**Issue by batpigandme** [rstudio/rstudio#2456]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.440
    OS Version      :  10.12.6
    R Version       :  3.4.3

### Steps to reproduce the problem

If you're focused in any window that's _not_ Source (otherwise it's irrelevant) try to execute the keyboard shortcut for moving focus to Source <kbd>Ctrl</kbd> + <kbd>1</kbd>.

### Describe the problem in detail

The cursor/focus does not move to the source pane. All of the equivalent shortcuts (Console, Help, etc.) work fine. It's just the source one that doesn't.

I tested to check that it wasn't an overriding shortcut on my machine by switching to 1.1.442, and <kbd>Ctrl</kbd> + <kbd>1</kbd> works as expected.

Thanks for your help!

**Comment by ronblum** [comment]
Which window did it fail for you, or did it fail in from all windows? I could not reproduce the problem on MacOS Desktop, Windows Desktop, and Ubuntu server.

**Comment by batpigandme** [comment]
Oh, all of them…that is super weird! I'll close and re-open if it somehow creeps up again. Maybe my comp was just feeling surly this morning.
