### ISSUE TITLE
File Deleted dialog doesn't go away

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#2457]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.440
    OS Version      : Mac
    R Version       : 3.4.3

### Steps to reproduce the problem

* Open a file in the Editor.
* Delete the file
* The File Deleted dialog comes up. Clicking on No or Yes has no effect - as far as I can tell, it's impossible to make it go away without restarting RStudio.

**Comment by kevinushey** [comment]
This sounds like it may be a different manifestation of https://github.com/rstudio/rstudio/issues/2249.

**Comment by kevinushey** [comment]
Should hopefully be fixed in the next daily builds -- thanks for reporting!

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
