### ISSUE TITLE
Diagnostic tooltips are clipped, not wrapped

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2462]
<img width="475" alt="screen shot 2018-03-20 at 5 24 19 pm" src="https://user-images.githubusercontent.com/4196/37689670-97d8e36e-2c63-11e8-8ab6-f3fedf4ca972.png">

Likely a 1.2 issue

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/2323.
