### ISSUE TITLE
installing rstudio professional drivers

### ISSUE THREAD

**Issue by pachamaltese** [rstudio/rstudio#2463]
HI

The instructions say:

You will need to install the unixODBC driver manager if it is not already installed on your server and the odbc package in R.

`$ sudo apt-get install unixodbc unixodbc-dev`

What actually worked for me (RStudio Server Pro 1.1 + Ubuntu Server 16.04) was:

`$ sudo apt-get install unixodbc unixodbc-dev --install-suggests`

Otherwise it won't work since the optional step described at https://db.rstudio.com/best-practices/drivers/ :

`$ apt-get install libmyodbc`

tries to install a removed package so `unixodbc` suggests will setup odbc connector

**Comment by javierluraschi** [comment]
CC: @edgararuiz

**Comment by edgararuiz** [comment]
Thanks @javierluraschi , I just opened an issue in the site to see about updating that line
