### ISSUE TITLE
Hmsic package not taking up.

### ISSUE THREAD

**Issue by Pincleparashar** [rstudio/rstudio#2468]
When I try to install the package Hmisc, it seems to install fine, however when I library(Hmisc), the following error comes up:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
there is no package called ‘backports’
In addition: Warning message:
package ‘Hmisc’ was built under R version 3.2.5 
Error: package or namespace load failed for ‘Hmisc’

I attempted to install 'backports' but the same error persist and it seems to install fine, but then it says backports doesnt exist

Any ideas on how to rectify this?

**Comment by ronblum** [comment]
@Pincleparashar I'm unable to reproduce the issue. Can you please provide information about the version of RStudio you're using and your environment?

    RStudio Edition : Desktop or Server
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
