### ISSUE TITLE
RStudio crashes when trying to change font

### ISSUE THREAD

**Issue by mattansb** [rstudio/rstudio#2472]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Win 10 64bit
    R Version       : 3.4.3

### Steps to reproduce the problem
tools > global options > appearance > editor font (change) > OK / Apply 

### Describe the problem in detail
When trying to change the font type, RStudio freezes and crashes.

### Describe the behavior you expected
The font to change.

**Comment by kevinushey** [comment]
Do you have a file located at:

```
%APPDATA%\RStudio\desktop.ini.lock
```

See also: https://github.com/rstudio/rstudio/issues/1862

**Comment by mattansb** [comment]
Yup - deleting that file solved it.
Thanks!

**Comment by kevinushey** [comment]
Awesome! We'll try to make sure future releases of RStudio recover more gracefully from this state.
