### ISSUE TITLE
RStudio process does not end when closing RStudio on win-10

### ISSUE THREAD

**Issue by mattansb** [rstudio/rstudio#2473]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Win 10 64bit
    R Version       : 3.4.3

### Steps to reproduce the problem
Closing RStudio window, and then trying to open a `.R` file.

### Describe the problem in detail
After closing all RStudio sessions, trying to open `.R` files (which are setup to be opened by RStudio) does not open a new RStudio session (but directly opening RStudio, or opening a `.Rproj` file do open new RStudio sessions).
When opening the task manager, the previous RStudio session is still running, and each attempt at opening a `.R` file creates a new RStudio process (without opening a new RStudio window).
After force-ending all RStudio processes, opening a `.R` file does open a new RStudio window.

### Describe the behavior you expected
When no RStudio window is open, that opening a `.R` file will start a new session, open a new window, and the `.R` file in it.

**Comment by jmcphers** [comment]
We haven't had other reports or been able to repro for well over a year, so closing. Let us know if you're still seeing this.

**Comment by danielnowak-sa** [comment]
I do face the same issue currently. System specifications are
RStudio Edition : Desktop
RStudio Version : 1.3.1073
OS Version      : Win Server 2012 R2 Standard 64bit
R Version       : 4.0.2

**Comment by mattansb** [comment]
@danielnowak-sa Since updating to RStudio 1.4 I no longer suffer from this issue.
