### ISSUE TITLE
Wrong keyboard input in RStudio's text editor when working over RDP

### ISSUE THREAD

**Issue by mz8i** [rstudio/rstudio#2474]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Windows 10 Enterprise
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Connect to a Windows 10 machine through RDP (Remote Desktop Protocol)
2. Open RStudio on the remote machine
3. Start typing text quickly

### Describe the problem in detail

I am connecting to a Windows 10 PC over Remote Desktop Connection.
When using RStudio in that context, typing on a keyboard does not work properly if the typing is fast.
The precise problem is that with fast typing, when the time distance between two keypresses is small, the two keypresses are registered so that two characters are entered into the editor, but the second character is wrong - instead of having the value of the actually pressed key, it takes the value of the first character. An example sequence of characters pressed on a keyboard:
`this is a test to showcase the problem with fast typing in Rstudio over rdp`
resulted in my case in
`thhs is a test tt ssowcaae the prrblee witt faat typing in Rsttddo over rdd`

I assume this is a problem in how RStudio handles keyboard input since all other applications on the machine I'm accessing remotely don't have that issue.

### Describe the behavior you expected

Text input working correctly, like in all other applications I use over RDP.

**Comment by kevinushey** [comment]
By any chance do you also see this behavior here? https://ace.c9.io/build/kitchen-sink.html

You might also try the RStudio daily build to see if the situation is improved: https://dailies.rstudio.com

**Comment by mz8i** [comment]
Hi @kevinushey - thanks for getting back to me so quickly!
The issue is not present in the browser version of the Ace editor. Had the same thought that maybe it's something about the editor, but it seems to me now that this is more a problem with how the desktop app handles system-level keyboard input (as in, RStudio vs Chrome in the website case).
Unfortunately, I can also say that installing the latest version of RStudio from the link you provided (version 1.2.473) doesn't resolve the problem.

**Comment by slava-tsarev** [comment]
I am observing this issue, too, under windows 7 with all versions of RStudio Desktop, up to the latest (1.1.463)

**Comment by david6marsh** [comment]
I also see this problem consistently (our current version 1.1.456).
However, I now find that I have the same problem with Tableau Public (10.3.0).
It's never a problem with the Microsoft Office applications, or Chrome, for example.

**Comment by junio-AC** [comment]
Did anyone solved this problem?
Using unicode keyboard mode I can't write in RStudio (types just one letter, the first one inputed in the editor) but works fine in other app (like notepad).
 I'm using Microsoft Remote Desktop with Mac Os Catilina to connect RDP a WIndows Server 2016 machine with italian keyoboard.

Thanks to whom might help :)

**Comment by david6marsh** [comment]
Sorry to say I didn't find a solution.
Tableau investigated, but didn't find a solution. Increasingly believe that it's the 'guacamole' connection that doesn't work connecting remotely to RStudio and Tableau. 

It's a pain.

**Comment by junio-AC** [comment]
Thanks for the feedback @david6marsh! 
If helps: using Microsoft Remote Desktop it is possibile to switch keyboard Mode (Connection>Keyboard mode) to Scancode and that solves the main issues on Rstudio (aka letting me input letters) although that doesn't solve typing issues like # @ and other macos>windows mismatch.

Still a pain.
