### ISSUE TITLE
RStudio expands symlinks in preferences, breaking on upgrades/changes to target (e.g. git)

### ISSUE THREAD

**Issue by neverfox** [rstudio/rstudio#2476]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : OS X 10.13.3
    R Version       : 3.4.4

### Steps to reproduce the problem

Change Preferences->Git/SVN->Git executable to /usr/local/bin/git, which is a symlink to a homebrew-installed git at /usr/local/Cellar/git/[version]/bin/git

### Describe the problem in detail

When the change is made, RStudio expands the symlink to the real absolute path. Because this expanded path contains a version number, updates to new versions of git via brew break the RStudio<->git configuration. One is required to go into RStudio's preferences after every upgrade and fix the path.

### Describe the behavior you expected

Entering a symlink to the git executable (or anything) should not expand, so that RStudio is tolerant of changes to the symlink's target. Symlinks are use by homebrew to abstract away the underlying versioned installation and RStudio should use this abstraction. While this is an issue raised for homebrew in particular, it's probably a good idea to respect symlinks literally in any case.

**Comment by neverfox** [comment]
Thanks for such a quick solution!

**Comment by kevinushey** [comment]
Our pleasure. Thanks for the bug report!

**Comment by kevinushey** [comment]
I can reproduce this issue in v1.3 and v1.4; it looks like it may have re-regressed.
