### ISSUE TITLE
Test issues are all reported as failures

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#2483]
Any `testthat` warning, skip, etc, is reported as a failure which is not ideal...

<img width="471" alt="screen shot 2018-03-22 at 2 08 24 pm" src="https://user-images.githubusercontent.com/3478847/37800751-22ea507c-2de1-11e8-9225-aca29db30273.png">

**Comment by dfalty** [comment]
Verified fixed 1.2.1320. 
![image](https://user-images.githubusercontent.com/15237845/53897086-fd90a600-3ffa-11e9-9d4a-7e917883ff41.png)
