### ISSUE TITLE
Assignment operator shortcut not working

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#2486]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.468
    OS Version      : Windows 10
    R Version       : 3.4.4

Pressing Alt + - I would expect `<-` to be created in the editor, however after updating to 1.2.468, I only get a `-`. Looking around in the Modify Keyboard Shortcuts window, I think the shortcuts engine assumes an English(US?) keyboard, which is not what I'm using. For example if I assign Alt + + on my keyboard, I will display Alt + = in the little text box, but Alt + + will work in the editor. I can assign Alt + - to `<-` and it will display as Alt + - but won't work in the editor.

A similar issue happens in rstudio cloud, where, again, I can use my local keyboard layout just fine in the editor but shortcuts seem to want a different keyboard layout. The assignment operator shortcut is displayed as Alt + - there as well but it only works if I press Alt + +, I think because an US - is where I have + on my layout. The same thing does not work on desktop rstudio.

Shortcuts for other things than the assignment sign work fine but that's probably because most of the keys match up across different layouts e.g. Crtl + Shift + m to make the pipe.

I hope this is clear enough. Anyway, there seems to be _something_ wrong with the shortcuts while using a non-US layout.

**Comment by ronblum** [comment]
@martj42 What keyboard layout are you using?

**Comment by martj42** [comment]
I have the same experience in Estonian and Finnish layouts.

**Comment by ronblum** [comment]
Confirmed in Windows 10 (1.1.442 vs. 1.2.469-2). Note that <kbd>Alt -</kbd> functions correctly for Finnish and Estonian in Mac Desktop in both 1.1.442 and 1.2.472-1.

**Comment by FDouat** [comment]
RStudio Edition : Preview - Desktop
RStudio Version : 1.2.792
OS Version      : Windows 10
R Version       : 3.5.1

Hello,
I have a similar problem :
the shortcut for Insert Assignment  Operator is not working when using the “-“ on the numeric pad but working when using the “-“ on the regular keyboard (key 6 in French - AZERTY).

**Comment by jcvdav** [comment]
I updated to 1.2.1013 today (the `Jobs` tab is amazingly useful!), and have the same problem as @FDouat where I can insert the assignment operator with `Alt` + `-` on the text keybord, but not the one in the numeric keybord.

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Mexico.1252 
[2] LC_CTYPE=Spanish_Mexico.1252   
[3] LC_MONETARY=Spanish_Mexico.1252
[4] LC_NUMERIC=C                   
[5] LC_TIME=Spanish_Mexico.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1  tools_3.5.1     packrat_0.4.9-2
```

**Comment by kevinushey** [comment]
Great to hear -- thanks!

**Comment by martj42** [comment]
This is back for 1.3.270.

**Comment by davidizquierdogomez** [comment]
hello, I am getting the symbol = instead of <- when I use alt+- in my Macbook pro. when I code in mode "Rmarkdown" I get the aforementioned =,  but in mode "script" it works fine....I don´t know what to do.

**Comment by sbcalaff** [comment]
Pressing `Alt` + `-` I would expect `<-` to be created in the editor, however I only get a `-` (RStudio version 1.3.959, Spanish keyboard with number pad). It does work with `-` of text keybord, but not the `-` in the numeric pad.

**Comment by martj42** [comment]
This is back for me in 1.3 and 1.4 on Windows 10. Everything works as expected on Linux.

**Comment by ronblum** [comment]
@davidizquierdogomez In an R markdown document, do you by chance get `=` when composing text but `<-` within a code chunk? And what version of RStudio are  you using?

@sbcalaff Going by #5072, this might be working with the current development builds. If you're willing to try it out, 1.4 Wax Begonia dailies are at https://dailies.rstudio.com/ . Note that these are for testing purposes only.

**Comment by MzwaneleN** [comment]
Assignment operator shortcut (Alt + - ) not working in R interpreter in High Performance Computer/remote server.

**Comment by BmaninBay** [comment]
Try turning on your CapsLock!

**Comment by finalspy** [comment]
You can replace by shortcut Alt+6 on Azerty keyboards but this will disable the Alt+- on the numpad ... 
https://community.rstudio.com/t/shortcut-alt-6-key-on-french-azerty-keyboard-doesnt-work/128661
