### ISSUE TITLE
RStudio (1.2.432) cannot find files which exist in the computer

### ISSUE THREAD

**Issue by cimentadaj** [rstudio/rstudio#2488]
I'm using Windows 10 on a Dell XPS 15 9560 with RStudio (1.2.432). I'm using RStudio (1.2.432) because Rmarkdown was very laggy using the stable version of Rstudio (something documented here https://github.com/STAT545-UBC/Discussion/issues/354). I was using this version and everything was working fine until I found (what I think it might be) a bug. I clone a repo from my Github account and all files are present. However, when browsing the folder structure from Rstudio the file doesn't show up. In fact, when opening through File -> Open, I can see the file but when I open it it says it can't find the file. It's very weird. The example below reproduces in my computer, let me know if it does in your end.

```
git clone -b root https://github.com/cimentadaj/cimentadaj.github.io
cd cimentadaj.github.io/
ls content/blog/2016-09-19-obtaining-robust-standard-errors-and-odds-ratios-for-logistic-regression-in-r/
# Both .html and .Rmd files are there
```

Now open the `.Rproj` in the main directory and browse to `content/blog/2016-09-19-obtaining-robust-standard-errors-and-odds-ratios-for-logistic-regression-in-r/` in the file pane in the bottom right window. Both files don't appear to be there for some reason.  If you try the above through File -> Open file and search for the documents, both appear to be there but when I try opening the `.Rmd` file an error arises: `Error while opening file. The system cannot find the file specified.`

This reproduces in my computer after cloning the repo several times, rebooting and restarting R.

My session info

----

```
Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       RStudio (1.2.432)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Paris                
 date     2018-03-23                  

Packages ----------------------------------------------------------------------------------------------
 package   * version date       source                           
 backports   1.1.2   2017-12-13 CRAN (R 3.4.3)                   
 base      * 3.4.4   2018-03-15 local                            
 blogdown    0.5.11  2018-03-22 Github (rstudio/blogdown@a9e4167)
 bookdown    0.7     2018-02-18 CRAN (R 3.4.4)                   
 compiler    3.4.4   2018-03-15 local                            
 datasets  * 3.4.4   2018-03-15 local                            
 devtools    1.13.5  2018-02-18 CRAN (R 3.4.3)                   
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)                   
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.4)                   
 graphics  * 3.4.4   2018-03-15 local                            
 grDevices * 3.4.4   2018-03-15 local                            
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.4)                   
 knitr       1.20    2018-02-20 CRAN (R 3.4.4)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.4.4)                   
 memoise     1.1.0   2018-03-20 Github (hadley/memoise@06d16ec)  
 methods   * 3.4.4   2018-03-15 local                            
 Rcpp        0.12.16 2018-03-13 CRAN (R 3.4.4)                   
 rmarkdown   1.9     2018-03-01 CRAN (R 3.4.4)                   
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.4)                   
 stats     * 3.4.4   2018-03-15 local                            
 stringi     1.1.7   2018-03-12 CRAN (R 3.4.4)                   
 stringr     1.3.0   2018-02-19 CRAN (R 3.4.4)                   
 tools       3.4.4   2018-03-15 local                            
 utils     * 3.4.4   2018-03-15 local                            
 withr       2.1.2   2018-03-18 Github (r-lib/withr@79d7b0d)     
 xfun        0.1     2018-01-22 CRAN (R 3.4.4)                   
 yaml        2.1.18  2018-03-08 CRAN (R 3.4.4) 
```

**Comment by kevinushey** [comment]
I tried this out on my Windows 10 VM, and it worked fine on my machine. The files show up in the Files pane, and I can click on the file to open it successfully.

Can you provide us with a diagnostics report? https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

Is it possible something is going wrong because the path name is so long?

**Comment by cimentadaj** [comment]
You were right! It was a because the path name was too long. But shouldn't that be weird? It was working on preivous OSx no problem. Anyways, I can find both files now.

Thanks!
