### ISSUE TITLE
Dialog button position reversed from Interface Guidelines

### ISSUE THREAD

**Issue by tomhopper** [rstudio/rstudio#2489]
The button position for dialogs on macOS are reversed from the guidelines established by Apple, resulting in user mistakes when selecting options.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      :  macOS 10.13.3
    R Version       : 3.4.4

### Steps to reproduce the problem

Follow the steps to create a new project in a new directory. On the dialog where the "create project" button is enabled, stop and compare the design of the dialog to the Apple macOS Human Interface Guidelines.

### Describe the problem in detail

Because the buttons are reversed from the macOS standard, I frequently click on the wrong one—following muscle memory and deeply-ingrained expectations—and have to go back and re-do work. E.g. I will "cancel" when creating a new project when I mean to create the project. Even when getting it right, I need to stop and think about which button I need to click on, rather than just follow the faster muscle memory and click on what should be the right button without looking.

### Describe the behavior you expected

Apple's guidelines state (see the sections on [alerts][alert] and [dialogs][dialog]):

> In general, the button people are most likely to choose should be on the right. The default button should always be on the right. Cancel buttons are typically on the left.

and

> **Position buttons as expected**. Any buttons in the bottom right of a dialog should dismiss the dialog. An action button, which initiates the dialog’s primary action, should be farthest to the right. A Cancel button should be to the immediate left of the action button. 

For instance, when creating a new project, the buttons are reversed from this guidance. Users will most often intend to press is "Create Project," and this should be the default. According to Apple's HIGs, it should be in the bottom right of the dialog. In this dialog, the "cancel" button is in the lower right, and the default "Create Project" button—which people are most likely to choose—is to the left of the cancel button, in the position where users will expect the "cancel" button to be located.

[alert]: https://developer.apple.com/macos/human-interface-guidelines/windows-and-views/alerts/
[dialog]: https://developer.apple.com/macos/human-interface-guidelines/windows-and-views/dialogs/

**Comment by kevinushey** [comment]
If we wanted to resolve this, we could always display the <kbd>Create Project</kbd> and <kbd>Cancel</kbd> buttons, but only enable the <kbd>Create Project</kbd> button on the last page of the wizard dialog.

**Comment by ronblum** [comment]
If we make this change, do we  do so for all versions of the IDE—all OSs, Server and Desktop?

**Comment by tomhopper** [comment]
Bump
