### ISSUE TITLE
Portmapping does not work for IPv6 addresses 

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2493]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.442

### Steps to reproduce the problem

1. Run RStudio Server on an IPv6 enabled host
2. Start an HTTP service that listens on the host's IPv6 loopback interface (such as `::1`)
3. Attempt to view content from that service in the Viewer pane (or anywhere else)
4. Nothing happens; the browser is delivered a raw URL and can't connect.

### Describe the problem in detail

Only URLs that include `localhost` or `127.0.0.1` get rewritten using `/p/` URLs to use port mapping. This happens because we use the following regex to ascertain whether the URL should use port mapping:

https://github.com/rstudio/rstudio/blob/e9f2f4b911f14c335d2f0eee7244ca3f828b6a0e/src/cpp/session/SessionModuleContext.cpp#L1841

### Describe the behavior you expected

RStudio Server rewrites the URL, and routes `/p/` requests to the IPv6 service.

**Comment by jmcphers** [comment]
Another example that should work, but doesn't:

    withr::with_options(
        c('shiny.host'='::'),
        ggbrush(mtcars, "hp", "mpg")
    )

**Comment by kfeinauer** [comment]
Fixed by https://github.com/rstudio/rstudio/commit/415a39c1c7e7c03787d2b8d18fa36c73cd05dc53.
