### ISSUE TITLE
Error pop-up when using "?" and F1 simultaneously

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#2496]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Ubuntu 14.04.5 LTS (also Windows 7)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Type `?dplyr::filter` in a script.
2. Press <kbd>ESC</kbd> to dismiss autocompletions.
3. Press <kbd>F1</kbd>.

### Describe the problem in detail

- An error pop-up appears : `R code execution error`
- The following error message is displayed at the console:
```
Error in find.package(if (is.null(package)) loadedNamespaces() else package,  : 
  there is no package called ‘?dplyr’
```
- No help appears.

**Comment by ronblum** [comment]
Reproduced in 1.2.472-1. Note that `?` and <kbd>F1</kbd> work fine on their own.

**Comment by etienne-s** [comment]
Also, if you press <kbd>F2</kbd> instead of <kbd>F1</kbd>, the editor opens a new tab containing the single line:
```r
"C:/Program Files/R/R-3.4.4/library/dplyr/help/filter"
```
(instead of the source code of the `filter` function).
