### ISSUE TITLE
ENHANCEMENT: Add 'Time This Chunk' as Option for RStudio Chunk

### ISSUE THREAD

**Issue by jeff-mettel** [rstudio/rstudio#2497]
When working with a long RStudio Notebook, you will frequently have certain chunks taking more / less time to execute.  It would be a great enhancement to easily track which chunks take which amount of time.  Ideally, a default 'Time All Chunks' option would be available.  This is somewhat different from simply profiling the performance of your code, and would be a somewhat higher level insight as to which portions of your analysis are taking which duration of time.

**Comment by ronblum** [comment]
@digital-dharma This is an interesting suggestion, and we'll review and consider it as we work on future releases of RStudio. Thank you!

**Comment by digital-dharma** [comment]
@ronblum  - Great, thanks!
