### ISSUE TITLE
Global Snippets Definitions Not Supported in Rstudio Server Pro

### ISSUE THREAD

**Issue by ilima-nvps** [rstudio/rstudio#2503]
### System details

    RStudio Edition : Server Pro
    RStudio Version : 1.1.383
    OS Version      : Ubuntu 4.4.0-116-generic
    R Version       : 3.2.3

### Steps to reproduce the problem

The snippets definition file (r.snippets) is only searched for in a specific user's directory. 

### Describe the problem in detail

Our team would like to maintain global and user-specific snippet definitions - much like how environmental variables can be defined in both Renviron.site and a user's specific Renviron file.

Having server-wide snippet definitions will help our team maintain consistency in code and will assist in having a centrally managed snippet repository.

### Describe the behavior you expected

I would like to replicate the current experience for environmental variable file (rEnviron). With these files a predetermined hierarchy of directories are searched and if a file is found, definitions are loaded and/or overwritten. For my current workflow I would like to have a centrally managed r.snippets file in the /etc/R folder with additional user-specific snippets located in ~/.R/snippets/r.snippets.

**Comment by ronblum** [comment]
@ilima-nvps Thanks for the feature suggestion! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by jmcphers** [comment]
This is now implemented in RStudio Server 1.3. You can read about how to set it up here:

https://docs.rstudio.com/ide/server-pro/latest/r-sessions.html#snippets
