### ISSUE TITLE
Saving a Rmd file in server makes it too easy to overwrite project file

### ISSUE THREAD

**Issue by lahvak** [rstudio/rstudio#2507]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.383
    OS Version      : Debian 8.?
    R Version       : 3.3.3

### Steps to reproduce the problem

Obtain an undergraduate student with very little experience with computers, files, ... Teach them just enough so they barely understand the concept of a project, notebook, R-markdown, etc, because of time constraint in a typical intro stats course.

Make them create a new project in R-studio, make them call it Myproject or something.  In the project, tell them to create a new R notebook, do some work, and save the notebook.

### Describe the problem in detail

What will happen is that they will manage to open the "Save file" dialog.  In the list of files, there will be a single file `Myproject.Rproj`. They will click on it and click on the "Save" button.  Then they start to freak out because all their syntax highlighting and code chunk outputs will disappear from their notebook, and they will no longer be able to run code chunks.

They will try to fix it by ... (whatever they do, it will generally go downhill from there).

### Describe the behavior you expected

I suggest that in the file list of the "Save file" dialog, the `*.Rproj` files are not listed at all.  At that step, there is no reason whatsoever to manipulate them in any way, and listing them there can only lead to confusion. 

Ideally, when saving a R-markdown document, only files with extension `rmd` or `Rmd` would be listed.

**Comment by ronblum** [comment]
@lahvak 
Thanks for the interesting suggestion. We'll take a look at it as we continue to develop new versions of RStudio.

Note: the same is true for Windows Desktop. Compare this to Mac Desktop (1.1.442 and 1.2.472), in which clicking on an existing file sets the name to the same name but with the `.Rmd` extension.
