### ISSUE TITLE
Quotes typed in console on iPad get changed to smart quotes

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2509]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.x
    OS Version      : iOS 11.2.6
    R Version       : 

### Steps to reproduce the problem
On iPad, with a physical keyboard (I'm using a first-gen iPad Pro 9.7" with Apple smart keyboard), go to RStudio console and type `cat("Hello\n")` then enter.

Try again with `cat('hello\n')` (i.e single quotes).

Switch to RStudio terminal, and do `echo "Hello"` then `echo 'World'`.

### Describe the problem in detail
In terminal, it works as expected, but in RStudio Console the quotes are converted to smart quotes and gives an error (see screenshot):

![img_b421abab0e67-1](https://user-images.githubusercontent.com/10569626/37939200-514e157e-3116-11e8-953a-c468a58849a4.png)

### Describe the behavior you expected

The console should do whatever the terminal is doing to prevent smart-quotes from happening automatically.

**Comment by rensa** [comment]
It's a bit of a blunt workaround, but you can [disable smart punctuation on iOS entirely](https://www.howtogeek.com/344310/how-to-turn-off-smart-punctuation-on-your-iphone-and-ipad/) if need be.

**Comment by gtritchie** [comment]
No longer repros on iPadOS 13.1 with both RStudio Server 1.2.1335 and latest 1.3 build, due to the improvements made in Safari. Confirmed that "Smart Punctuation" was turned on in both cases. Double-checked that this does still repro in iOS 12.4.1 with both of those builds of RStudio.

**Comment by ronblum** [comment]
Verified on iPadOS 13.3.1 connected to RStudio Server 1.3.929 on Red Hat 7.8.
