### ISSUE TITLE
Duplicate selection cursor in iPad when using arrow keys

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2511]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem
In a build of RStudio Server with the fix applied for #2186, open a file and move around it with the arrow keys.

### Describe the problem in detail
As you move right and left, you will see a duplicate text selection cursor (the native iOS selection thingy) following along several lines above where the text editor cursor is showing. It doesn't seem to cause any problems, but is ugly and distracting.

![image](https://user-images.githubusercontent.com/10569626/37940003-1722de48-311b-11e8-8d24-7929746c6b1b.gif)

### Describe the behavior you expected
Don't see that duplicate cursor.

**Comment by gtritchie** [comment]
I can no longer reproduce this issue. I tried these combinations:

- iOS 12.4.1, external bluetooth keyboard, RStudio 1.2.1335 and a recent build of 1.3
- iPadOS 13.1, Apple Smart Keyboard, RStudio 1.2.1335 and a recent build of 1.3

**Comment by ronblum** [comment]
Verified on iPadOS 13.3.1 connected to RStudio Server 1.3.929 on Red Hat 7.8.
