### ISSUE TITLE
Ctrl-based keyboard shortcuts don't work on iPad

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2512]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.x
    OS Version      : iOS 11.2.6
    R Version       : 

### Steps to reproduce the problem
Load RStudio server on iPad (Safari), with a physical keyboard that has a Control key (e.g. Apple smart keyboard). Try to use keyboard shortcuts that involve Ctrl, such as clearing the R console (Ctrl+L) or many others.

### Describe the problem in detail
Doesn't work. The only Ctrl-based things that appear to work are ones baked into iOS such as Ctrl+F (cursor forward) and Ctrl+B (cursor back).

### Describe the behavior you expected
Be nice to use RStudio shortcuts that start with Ctrl.

**Comment by lboller** [comment]
It looks like RStudio interprets the "Ctrl" key as "Command" on the iOS keyboard. You can change the keyboard shortcuts in the menu to make many of these work, but it would nice if it could correctly interpret the key press so that the default settings would be enabled.

**Comment by raubreywhite** [comment]
@lboller The problem is that then I can't use the same shortcuts on my desktop and on my iPad. For me, I'd like to seamlessly work between the two of them (which is the whole point of the server).

**Comment by gtritchie** [comment]
This is now working with the improvements made to Safari in iPadOS 13.1. Tested with both RStudio Server 1.2.1335 and a recent 1.3 build.

**Comment by ronblum** [comment]
Verified on iPadOS 13.3.1 connected to RStudio Server 1.3.929 on Red Hat 7.8.
