### ISSUE TITLE
Using backticks in the editor

### ISSUE THREAD

**Issue by boshek** [rstudio/rstudio#2513]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Windows7
    R Version       : 3.4.3

### Steps to reproduce the problem
Type a string. Realize it needs to be surrounded by backticks. 

Type backtick at the beginning of the string, then type a backtick at the start of the string. Result:

`string``

### Describe the behavior you expected
Is it possible for backticks to mimic the behaviour of quotes such that when a character(s) is highlighted and one type's a backtick, the entire highlighted characters are surrounded by backticks?

**Comment by ronblum** [comment]
@boshek Thanks for the suggested enhancement. We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by ronblum** [comment]
Also, note that in 1.2, highlighting the word and adding backticks produces the same result as with quotes. But as you described above, typing a string and then adding a backtick at the start and at the end will produce the extra backtick. (1.2 builds are available at https://dailies.rstudio.com/, but keep in mind that they are for testing purposes.)
