### ISSUE TITLE
Arrow keys on iPad physical keyboard don't work in terminal

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2515]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.x
    OS Version      : iOS 11.x
    R Version       : 

### Steps to reproduce the problem
Load RStudio server in Safari on an iPad with a physical keyboard. Go to terminal, try to use arrow keys.

### Describe the problem in detail
Arrow keys don't do anything.

### Describe the behavior you expected
Arrow keys behave like they do on other platforms.

See #2186 for this issue in the Ace editor. Also, it's possible this is fixed by an upgrade to xterm.js 3.x, but that isn't confirmed (#1923).

**Comment by gtritchie** [comment]
Confirmed fixed in RStudio 1.3.464, using iPadOS 13.1 and Apple smart keyboard. May also work with iOS 12, but not confirmed.

Most likely fixed by the upgrade to xterm.js 3.

**Comment by ronblum** [comment]
Verified on iPadOS 13.3.1 connected to RStudio Server 1.3.929 on Red Hat 7.8.
