### ISSUE TITLE
Can't close zoomed plot window with with Cmd+W on Mac

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2519]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.482
    OS Version      : Mac
    R Version       : 

### Steps to reproduce the problem
In console, `plot(1)`, then click Zoom button in plot window to open separate window. With focus on that window, hit Cmd+W to close the window.

### Describe the problem in detail
Doesn't do anything. If you use a debug build of RStudio and run from terminal or in Qt Creator, you will see this error when the plot window is first shown.

```
Object::connect: No such slot rstudio::desktop::BrowserWindow::onCloseRequested() in /Users/gary/rstudio/rstudio/src/cpp/desktop/DesktopGwtCallback.cpp:639
```

### Describe the behavior you expected
Plot window should close.

See #2495 for some recent related work.

**Comment by ronblum** [comment]
Verified on MacOS 10.14 Mojave <kbd>cmd-W</kbd> and Windows 10 <kbd>ctrl-w</kbd>.
