### ISSUE TITLE
Feature request: allow git commit+git push in one button

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#2521]
It's great that a git client is so conveniently integrated into rstudio. Much more often than not, when I use the rstudio git client, it's because I'm doing very simple git workflows, and almost always after doing a commit I want to push immediately. Every time I do it I think "it'd be great if there was just one button to press instead of clicking commit, wait 3 seconds, then click push, then wait another 3 seconds".

Low priority :)

**Comment by ronblum** [comment]
@daattali Thanks for the suggestion! We'll take a look at it as we continue to develop new versions of RStudio.
