### ISSUE TITLE
Go to file/function not working for files without extension

### ISSUE THREAD

**Issue by christianhomberg** [rstudio/rstudio#2522]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Ubuntu 17.10
    R Version       : 3.5.2

### Steps to reproduce the problem
1) `Ctrl+.`  or `Code` -> `Go to File/Function`
2) search for file without extension, e.g. `Dockerfile`

### Describe the problem in detail
Files without extension is not listed in result list.

### Describe the behavior you expected
File without extension is listed in result list.

I am fairly sure that this used to work in the past. It still does work with certain files like the R package `DESCRIPTION`.

**Comment by kevinushey** [comment]
We actually whitelist a specific set of extension-less files; files that don't live within that whitelist don't get shown in the fuzzy finder. Perhaps we should add Dockerfile to that list?

**Comment by christianhomberg** [comment]
I think Dockerfile is common enough to be whitelisted. I have other config files though that I'd still like to go to which is not possible with the whitelist approach.

In the meantime: is there a way to adjust the whitelist or turn "Go To File" on for files without extensions?

**Comment by kevinushey** [comment]
Not currently (but that's something that we could potentially make user configurable).

**Comment by robitalec** [comment]
Along the same wavelength, wasn't sure it was worth a separate issue:
`.bib` files also don't seem to show up with the fuzzy finder. 
This could be particularly useful when working on an RMarkdown file with references.

**Comment by jmcphers** [comment]
`MLProject` files too: https://github.com/rstudio/rstudio/issues/5963

This really needs to be user extensible in some way since we can't cover the long tail of files people want to be able to find.

**Comment by olivroy** [comment]
It is also the case for DESCRIPTION and .gitignore on Windows.
