### ISSUE TITLE
App outputs error when closing plot window

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2526]
To reproduce, run debug build of RStudio desktop (I tried on Mac):

1. Produce a plot with e.g. `plot(1)`,
2. Zoom the plot generated in the plots pane,
3. Close the plot with via the red-x

Step 3 works, but this is written to the terminal or debugger console:

```
"Uncaught SyntaxError: Unexpected token )"
```

**Comment by kevinushey** [comment]
Perhaps this is the culprit?

https://github.com/rstudio/rstudio/blob/d8b98dc9bd91e6baced3a58dd07f26f3cf9a0e40/src/cpp/desktop/DesktopBrowserWindow.cpp#L67-L71

Looks like there's an extraneous closing parenthesis there.
