### ISSUE TITLE
Make the "clear console" broom icon colorful and easier to see (cf. Environment pane)

### ISSUE THREAD

**Issue by ghost** [rstudio/rstudio#2531]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.1.383
    OS Version      :  Windows 10
    R Version       :  3.4.3

### Steps to reproduce the problem
Using the Theme "Vibrant Ink"

### Describe the problem in detail
I noticed that the "Clear Console" button was not colored like the "Clear Workspace" button was.  In the default RStudio theme, my eyes had a really hard time seeing the button.  _**Question 1:**_  Would it be possible to use the colored icon?  It is most definitely much better now that I found the "Vibrant Ink" theme.  But, on the "Vibrant Ink" theme in the Help window, if you search for text, the highlighting color is very difficult to see.  _**Question 2:**_  Would it be possible to change the highlight color?  These seem like such insignificant issues that I hate to bother someone, but these would really help out, especially the highlighting color change.  I have attached a screenshot with inking that hopefully will help clarify.  Thankyou.

![rstudio gui markup](https://user-images.githubusercontent.com/25963099/38058829-d63098d6-32a9-11e8-81ab-0c1e1db8e483.jpg)

### Describe the behavior you expected
Question 1:  Colored Icon
Question 2:  A more distinct highlight color that stands out from the background.

**Comment by ronblum** [comment]
@SquareWaffles Thank you for the observations! You'll be glad to know that the highlighter contrast for Vibrant Ink is better in the upcoming 1.2 release. However, this did lead to further investigation—see #2540.

I will leave this open for the request to change the "clear console" icon, to be considered in the future.
