### ISSUE TITLE
Issue with indented code in R Markdown and R Notebook code chunks (Mac v1.2.407)

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/rstudio#2532]
I have been experiencing some indentation issues with a recent daily build (v1.2.407). With this, there is a difference in code indents between R Markdown documents and R Notebook documents. The indents are twice as big in R Notebook than R Markdown. Plus, neither of them match an indent of 2 spaces, which is what I specified.

In all cases, my global and project options for code indenting are the same (`Insert spaces for tab` is checked and `Tab width` is `2`).

Here are some screenshots...

Global options:

<img width="614" alt="code_indent_options" src="https://user-images.githubusercontent.com/5612024/38059335-eebd6d2a-329a-11e8-91a2-e9f0f484f63e.png">

Project options:

<img width="566" alt="code_indent_project_options" src="https://user-images.githubusercontent.com/5612024/38059644-1696ed48-329c-11e8-8445-6cdd20460ed1.png">

Indenting in an R Markdown chunk:

<img width="310" alt="rmd_indent" src="https://user-images.githubusercontent.com/5612024/38059372-07f253f0-329b-11e8-8c63-ff202b913543.png">

Indenting in an R Notebook chunk:

<img width="241" alt="rnotebook_indent" src="https://user-images.githubusercontent.com/5612024/38059373-08073662-329b-11e8-97f8-b4e6373671fb.png">

This is not an issue in .R script files.

Below is extra information to provide context: 

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.407
    OS Version      :  MacOS 10.13.3
    R Version       : 3.4.3

Session Info

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] testthat_2.0.0      tidyr_0.8.0         tibble_1.4.2       
 [4] stringr_1.3.0       rlang_0.2.0         purrr_0.2.4        
 [7] magrittr_1.5        knitr_1.20          htmltools_0.3.6    
[10] glue_1.2.0          dplyr_0.7.4.9001    bindrcpp_0.2.0.9000
[13] gt_0.0.0.9000      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     digest_0.6.15    assertthat_0.2.0 R6_2.2.2        
 [5] pillar_1.2.1     stringi_1.1.7    tools_3.4.3      yaml_2.1.18     
 [9] compiler_3.4.3   pkgconfig_2.0.1  bindr_0.1.1      tidyselect_0.2.4

**Comment by kevinushey** [comment]
v1.2.407 is already quite old in RStudio-daily-build years. Do you see the same issue with the latest daily build, v1.2.487?

FWIW, I can't reproduce this issue on my side with v1.2.487.

**Comment by rich-iannone** [comment]
Thanks! That works for me. Resolves #2532.
