### ISSUE TITLE
error creating notebook: path for html_dependency not found

### ISSUE THREAD

**Issue by ChristelSwift** [rstudio/rstudio#2535]
hi, i'm trying to use notebooks but i've now had the same issue happening several times:  when i re-open my project sometimes, and i make a change and try to save/preview, i get this error message: 

    Error creating notebook: path for html_dependency not found: /var/folders/h8/ <long_code>

The only way to get my notebook to work again has been to delete the project folder, create a new one and re-run everything from scratch.  As it's a fairly heavy notebook, this turns out to be very time consuming, and i haven't found any relevant answer to this issue anywhere...

is this a known issue or am i doing something wrong...?

here's my set up chunk:

      {r setup, include=FALSE}
       knitr::opts_chunk$set(
       cache=TRUE, warning=FALSE, 
       message=FALSE, cache.lazy=FALSE) 

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      :  OS X El Capitan
    R Version       :  3.4.3

### sessionInfo:

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RPostgreSQL_0.6-2 DBI_0.8          

loaded via a namespace (and not attached):
 [1] zoo_1.8-1         modeltools_0.2-21 coin_1.2-2        splines_3.4.3    
 [5] lattice_0.20-35   colorspace_1.3-2  htmltools_0.3.6   stats4_3.4.3     
 [9] yaml_2.1.17       base64enc_0.1-3   survival_2.41-3   rlang_0.2.0      
[13] R.oo_1.21.0       pillar_1.2.1      R.utils_2.6.0     gdtools_0.1.7    
[17] uuid_0.1-2        multcomp_1.4-8    plyr_1.8.4        stringr_1.3.0    
[21] munsell_0.4.3     gtable_0.2.0      R.methodsS3_1.7.1 zip_1.0.0        
[25] htmlwidgets_1.0   mvtnorm_1.0-7     codetools_0.2-15  evaluate_0.10.1  
[29] knitr_1.20        strucchange_1.5-1 TH.data_1.0-8     ggiraph_0.4.2    
[33] Rcpp_0.12.15      party_1.2-4       scales_0.5.0      backports_1.1.2  
[37] jsonlite_1.5      gridExtra_2.3     ggplot2_2.2.1     digest_0.6.15    
[41] stringi_1.1.6     grid_3.4.3        rprojroot_1.3-2   tools_3.4.3      
[45] sandwich_2.4-0    magrittr_1.5      lazyeval_0.2.1    tibble_1.4.2     
[49] MASS_7.3-49       Matrix_1.2-12     xml2_1.2.0        rvg_0.1.8        
[53] rmarkdown_1.9     officer_0.2.2     R6_2.2.2          rpart_4.1-13     
[57] compiler_3.4.3

**Comment by ronblum** [comment]
@ChristelSwift I'm unable to reproduce the problem, even with the set up chunk you've provided. Can you provide a reproducible sample notebook file?

**Comment by dbrookeUAB** [comment]
@ChristelSwift I had a similar error:
> `path for html_dependency not found:`, 

and I was able to fix it by deleting the cached folder.  I think the problem arises when you set `knitr::opts_chunk$set( cache = TRUE)` and then move the folder, which is probably why it happens intermittently for you.

**Comment by jmcphers** [comment]
We now provide a way to clear the cache to resolve this issue:

![image](https://user-images.githubusercontent.com/470418/69194909-34521200-0adf-11ea-8abf-e8ea7b891151.png)

**Comment by Leran10** [comment]
Hi, I'm trying to render a Rmarkdown file in linux and eventually I want it to generate a dynamic .html file for people to checkout. The command I'm using is
R -e "rmarkdown::render('./test_rshiny2.Rmd',output_file='./results/Diagnos_Plot.html')".
However I kept getting this error:
Error: path for html_dependency not provided.

Can anyone here provide some help?
Thanks so much!!

**Comment by dbrookeUAB** [comment]
I would submit this to StackOverflow as well. You'll likely get a faster response.

**Comment by Leran10** [comment]
Thank you @dbrookeUAB  for the advice! Posted.

**Comment by ronygolderku** [comment]
I'm having a persistent issue with rendering a bookdown project in RStudio. Building individual chapters (or two at a time) works fine, but when I render the entire book (9 chapters) it fails with this error:
Error: path for html_dependency not found: 
```
C:/Users/user/AppData/Local/Temp/RtmpUBxRLF/fileb4ec3c0a381  
Execution halted  
Error: bookdown::render_book() failed to render the output format 'bookdown::gitbook'.: Error: path for html_dependency not found: C:/Users/user/AppData/Local/Temp/RtmpUBxRLF/fileb4ec3c0a381  
Execution halted
```
Environment:

 - R: 4.5.1   
- RStudio: 2025.05.1 (Windows 11)  
- bookdown: 0.43  
- rmarkdown:2.29   
- Pandoc: 3.4  
- Rendering to: bookdown::gitbook (HTML)

I have tried toggling chunk cache on/off (knitr::opts_chunk$set(cache = TRUE) and cache = FALSE) and updating relevant packages (bookdown, rmarkdown, htmltools).Howver, Single or pairs of chapters build without error, but when the full set (9 .Rmd chapters plus index) is built the failure occurs.

I want to know: 
- What causes the “path for html_dependency not found” error in a full bookdown build when individual chapters succeed?

- How can I reliably force bookdown/rmarkdown to rebuild or retain required HTML dependencies so the gitbook build completes?
