### ISSUE TITLE
Let backquote autoquote text

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rstudio#2536]
In RStudio, highlighting text and hitting `"` surrounds the text with quotes; similarly for `'`. It would be nice if the same happened for the backquote  \`.

**Comment by etienne-s** [comment]
It works that way in 1.2. See #2513.

**Comment by ronblum** [comment]
Thank you @hughjonesd for raising this and @etienne-s for pointing to it working in 1.2!
