### ISSUE TITLE
Update citation year from 2016 to 2018

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2538]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.442 (MacOS), 1.2.483-1 (MacOS), 1.2.487-3 (Ubuntu)
    OS Version      : MacOS & Linux
    R Version       : 3.4.2 and 3.4.4

### Steps to reproduce the problem

In console: `RStudio.Version()`

### Describe the problem in detail

The "$citation" section includes:
```
    year = {2016},
```

### Describe the behavior you expected

The year should probably be updated to 2018, especially if this is taken as a copyright date:
```
    year = {2018},
```

**Comment by BastiHz** [comment]
As 1.2 will probably be released soon maybe the year should be updated again.
