### ISSUE TITLE
zoom actions fail on satellite windows (macOS)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2541]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.479
    OS Version      : macOS 10.13.3
    R Version       : 3.4.4

### Steps to reproduce the problem

Pop out a window, and then attempt to zoom it with e.g. <kbd>Cmd + =</kbd>.

### Describe the problem in detail

The main window is zoomed instead.

### Describe the behavior you expected

The currently focused window should be zoomed.

### Details

I suspect this is because pressing <kbd>Cmd + =</kbd> invokes the menu item `View -> Zoom In` callback, but because this is only wired to the main window, only the main window handles the event.

Related: https://github.com/rstudio/rstudio/issues/2542

**Comment by kevinushey** [comment]
A simple fix for this would to make these _not_ invoke menu callbacks but instead zoom directly.

**Comment by vnijs** [comment]
FYI Zoom out and (CMD + -) now works in daily 1.2.502 on macOS (sierra) but (Cmd + =) does not. CMD + 0 also works. Same result on Windows 10 with daily 1.2.502 (i.e., can zoom out but not in).

**Comment by kevinushey** [comment]
Doh. Thanks; we'll take a look!

**Comment by kevinushey** [comment]
On Windows / Linux, <kbd>Ctrl =</kbd> never actually worked for zooming in -- one would have to press <kbd>Ctrl +</kbd> instead. Is that what you're referring to?

**Comment by vnijs** [comment]
You are right @kevinushey! Ctrl + Shift + = works on Windows and in 1.2.502 it is also *much* faster as it doesn't refresh the app. Nice

FYI: I do notice that if I (1) start Rstudio, (2) start an app in an Rstudio window, and (3) maximize the window the window goes completely black. Report as an issue?

**Comment by kevinushey** [comment]
Yes, please report that as a separate issue. Thanks!

**Comment by ronblum** [comment]
Verified
