### ISSUE TITLE
Shiny download buttons fail to download

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2554]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.501
    OS Version      : macOS 10.13.3
    R Version       : R 3.4.4

### Steps to reproduce the problem

Run the Shiny download button example in the Viewer pane, with:

```
.rs.setShinyViewerType(2L)
shiny::runExample("10_download")
```

Then, attempt to click the big <kbd>Download</kbd> button.

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

The user should be presented with a save file dialog, requesting a location for the downloaded file.

**Comment by ronblum** [comment]
@kevinushey For what it's worth, I sometimes get the message
```
ERROR: [on_request_read] connection reset by peer
```

**Comment by kevinushey** [comment]
I think that particular issue is going to be resolved in `shiny` or `httpuv`:

https://github.com/rstudio/shiny/issues/1469
https://github.com/rstudio/httpuv/issues/75
