### ISSUE TITLE
quit file dialog changed in v1.2

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2556]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.491
    OS Version      : Ubuntu 16.04
    R Version       : R 3.4.4

### RStudio v1.1

![screen shot 2018-03-30 at 5 07 17 pm](https://user-images.githubusercontent.com/1976582/38157560-f82cba84-343c-11e8-962b-0ff451c4757f.png)

### RStudio v1.2

![screen shot 2018-03-30 at 5 10 38 pm](https://user-images.githubusercontent.com/1976582/38157591-484918be-343d-11e8-8c7f-e557cbd48994.png)

We should ensure the dialog text is preserved. (Note that the changing in the styling of the button is okay and seems consistent with other elements of the platform theme)

**Comment by gtritchie** [comment]
Haven't checkedthe code, but smells like it might be related to work I did with Pro desktop; so feel free to assign to me.
