### ISSUE TITLE
Zoom image in new tab does not auto-resize with full-screen browser window

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#2557]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.410 on Ubuntu 16.04
    OS Version      : macOS High Sierra 10.13.4
    R Version       : 3.4.4
    Browser         : Firefox 60b8

### Steps to reproduce the problem

1. Open an RStudio Server session in a maximized browser window that occupies a full screen
2. Run `plot(rnorm(100))`
3. Click Zoom in the Plot Pane and a new browser tab is open
4. The image in the new tab does not auto-resize to fit the maximized browser window

**Comment by ronblum** [comment]
@renkun-ken I am unable to to reproduce this problem. Do you have this issue in any other browsers? And what about in more recent builds? Ubuntu server is currently up to 1.2.502.

**Comment by jmcphers** [comment]
Haven't heard back in well over a year so closing.
