### ISSUE TITLE
macOS build fails

### ISSUE THREAD

**Issue by kiwiroy** [rstudio/rstudio#2558]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : master
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3
    cmake version   : 3.10.2
    openssl version : OpenSSL 1.0.2n  7 Dec 2017
    macports version: 2.4.2

### Steps to reproduce the problem

Following build instructions with macports openssl installed in the default `/opt/local` prefix, a build fails.

    cmake .. -DRSTUDIO_TARGET=Desktop -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Applications/RStudio-dev
or
 
    cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Applications/RStudio-dev

### Describe the problem in detail

Specifically `src/cpp/core/http/SocketProxy.cpp` fails to compile with the error message from `make rstudio-core VERBOSE=1`

```
[ 54%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/http/SocketProxy.cpp.o
cd /Users/kiwiroy/code/rstudio/compilation-dir/src/cpp/core && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DBOOST_ASIO_DISABLE_KQUEUE -DBOOST_ENABLE_ASSERT_HANDLER -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DRSTUDIO_BOOST_NAMESPACE=rstudio_boost -DWEBSOCKETPP_STRICT_MASKING -D_WEBSOCKETPP_NO_CPP11_MEMORY_=1 -isystem /opt/rstudio-tools/boost/boost_1_63_0/include -I/Users/kiwiroy/code/rstudio/src/cpp/core/include -I/Users/kiwiroy/code/rstudio/compilation-dir/src/cpp/core -I/Users/kiwiroy/code/rstudio/src/cpp/tests/cpp  -std=c++0x -std=c++11 -O3 -DNDEBUG -fPIC   -Wall -pthread -Wno-unknown-warning-option -Wsign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -o CMakeFiles/rstudio-core.dir/http/SocketProxy.cpp.o -c /Users/kiwiroy/code/rstudio/src/cpp/core/http/SocketProxy.cpp
In file included from /Users/kiwiroy/code/rstudio/src/cpp/core/http/SocketProxy.cpp:22:
In file included from /Users/kiwiroy/code/rstudio/src/cpp/core/include/core/http/BoostAsioSsl.hpp:24:
In file included from /opt/rstudio-tools/boost/boost_1_63_0/include/boost/asio/ssl/context.hpp:27:
In file included from /opt/rstudio-tools/boost/boost_1_63_0/include/boost/asio/ssl/context_base.hpp:19:
/opt/rstudio-tools/boost/boost_1_63_0/include/boost/asio/ssl/detail/openssl_types.hpp:19:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
```

### Describe the behavior you expected

Successful build.

**Comment by jmcphers** [comment]
Should be addressed now that your PR's been merged (let us know if it isn't!)

**Comment by kiwiroy** [comment]
All good thanks @jmcphers.
