### ISSUE TITLE
inconsistent browseURL behavior with terminal under Mac

### ISSUE THREAD

**Issue by lgeistlinger** [rstudio/rstudio#2560]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 1.1.383
    OS Version      :  macOS High Sierra 10.13.3
    R Version       : 3.4.4

### Steps to reproduce the problem / Describe the problem in detail / Describe the behavior you expected

https://github.com/r-lib/rappdirs/issues/24

**Comment by kevinushey** [comment]
This works as expected for me in v1.2:

```
dir.create("Path with Spaces")
writeLines("<p>Hello!</p>", "Path with Spaces/hello.html")
browseURL("Path with Spaces/hello.html")
```

Can you test yourself with the latest daily builds (https://dailies.rstudio.com) and let us know if the issue appears resolved for you as well?

**Comment by lgeistlinger** [comment]
Great, I can confirm that this works as expected with the daily build 1.2.502.
When will v1.2 approx. become available for download?

I see that latest version is 1.1.442 here:

https://www.rstudio.com/products/rstudio/download/

**Comment by kevinushey** [comment]
Our goal is to have a preview release ready this summer, and a full release available in autumn (but this is all tentative).

Thanks for the bug report and testing out v1.2!
