### ISSUE TITLE
checkboxInput and radioButton styling in Viewer on Windows

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#2562]
Styling is a bit odd for `checkboxInputs` and `radioButtons` when show in the Rstudio viewer on Windows. Reproducible example and screenshots below:

```
library(shiny)

ui <- fluidPage(
  checkboxInput("cbox", " Checkbox"),
  radioButtons("rbutton", "", c("value 1","value 2"), inline = TRUE)
)

server <- function(input, output) {}

# Run the application
shinyApp(ui = ui, server = server)
```

Screenshot from Rstudio viewer on Windows:

![image](https://user-images.githubusercontent.com/2998956/38178667-54499126-35cc-11e8-9444-14e4dfd49134.png)

Screenshot from Rstudio viewer on Mac:

![image](https://user-images.githubusercontent.com/2998956/38178647-20ecd9be-35cc-11e8-8e49-bedebbf26940.png)

**Comment by vnijs** [comment]
Just noticed `checkboxInput` and `radioButton` looks good in Viewer and Windows in daily 1.2.502. Nice!

**Comment by ronblum** [comment]
@vnijs I'm glad to hear it's working now!
