### ISSUE TITLE
RStudio Server fails to start on OpenSuse 42.2

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2564]
### System details

    RStudio Edition : Server and Server Pro
    RStudio Version : 1.2.493-2 through 1.2.502-1. Works fine on 1.2.493-1 and previous
    OS Version      :  OpenSuse 42.2

### Steps to reproduce the problem
1. Install RStudio Server on OpenSuse 42.2 with version 1.2.493-2 or greater.
2. Observe RStudio will fail to start

> ip-10-0-0-127:/1 # rpm -ivh rstudio-server-suse-pro-1.2.502-1-x86_64.rpm 
> warning: rstudio-server-suse-pro-1.2.502-1-x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID e331692f: NOKEY
> Preparing...                          ################################# [100%]
> Updating / installing...
>    1:rstudio-server-1.2.502_1-1       ################################# [100%]
> useradd: user 'rstudio-server' already exists
> groupadd: group 'rstudio-server' already exists
> rsession: no process found
> /usr/lib/rstudio-server/bin/license-manager: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
> Created symlink from /etc/systemd/system/multi-user.target.wants/rstudio-server.service to /etc/systemd/system/rstudio-server.service.
> Job for rstudio-server.service failed because the control process exited with error code. See "systemctl status rstudio-server.service" and "journalctl -xe" for details.
> ● rstudio-server.service - RStudio Server
>    Loaded: loaded (/etc/systemd/system/rstudio-server.service; enabled; vendor preset: disabled)
>    Active: activating (auto-restart) (Result: exit-code) since Mon 2018-04-02 14:34:24 UTC; 93ms ago
>   Process: 2527 ExecStart=/usr/lib/rstudio-server/bin/rserver (code=exited, status=127)
> 
> Apr 02 14:34:24 ip-10-0-0-127 systemd[1]: rstudio-server.service: Control process exited, code=exited status=127
> Apr 02 14:34:24 ip-10-0-0-127 systemd[1]: Failed to start RStudio Server.
> Apr 02 14:34:24 ip-10-0-0-127 systemd[1]: rstudio-server.service: Unit entered failed state.
> Apr 02 14:34:24 ip-10-0-0-127 systemd[1]: rstudio-server.service: Failed with result 'exit-code'.

> ip-10-0-0-127:/1 # rstudio-server restart
> /usr/lib/rstudio-server/bin/rserver: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
> /usr/sbin/rstudio-server: line 44: return: can only `return' from a function or sourced script
> Job for rstudio-server.service failed because the control process exited with error code. See "systemctl status rstudio-server.service" and "journalctl -xe" for details.
> rsession: no process found

### Describe the problem in detail
This happens with OS server as well as Pro. Maybe related to https://github.com/rstudio/rstudio/pull/2543?

**Comment by kevinushey** [comment]
It looks like the `libcrypto.so` and `libssl.so` symlinks aren't be created anymore. I'll see if I can figure out why.

**Comment by kevinushey** [comment]
Will hopefully be fixed with https://github.com/rstudio/rstudio/commit/8c5f3dca2d1c9fdfba452603321f56837ff2a1f7.
