### ISSUE TITLE
System processes do not stop when session running "system" is interrupted

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2565]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.487-3
    OS Version      : Ubuntu 16.04
    R Version       : 3.4.2

### Steps to reproduce the problem

Use `system()` or `system2()` to run a process that takes a while to complete, such as "sleep":
1. In the console: `system("sleep 1234")`
2. Click on the stop sign <img width="23" alt="stop_sign" src="https://user-images.githubusercontent.com/31009952/38202667-80ed78b6-366a-11e8-88e1-b7e0a3ffea7a.png"> multiple times until given the option to terminate R.
3. Click `Yes`

### Describe the problem in detail

The session is terminated and restarted. However, the processes are still running, as seen with `ps -ef | grep sleep`

````
rstudio@ip-172-30-1-69:~$ ps -ef | grep sleep
rstudio  12526     1  0 15:43 ?        00:00:00 sh -c sleep 1234
rstudio  12527 12526  0 15:43 ?        00:00:00 sleep 1234
rstudio  12574 12557  0 15:45 pts/0    00:00:00 grep --color=auto sleep
rstudio@ip-172-30-1-69:~$
````

### Describe the behavior you expected

The processes terminate—in this case, sleep no more.

**Comment by jmcphers** [comment]
Do you have `session-quit-child-processes-on-exit` set?

**Comment by HedvigS** [comment]
Any chance this setting will be made the default at some point?
