### ISSUE TITLE
RStudio server terminal not working on paperspace

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/rstudio#2567]
Terminal pane is blank and pressing "New Terminal" doesn't do anything. This is on Ubuntu 16.04.

To repro, follow the steps here https://tensorflow.rstudio.com/tools/cloud_desktop_gpu.html

**Comment by gtritchie** [comment]
I've applied for access (wouldn't let me create a machine without providing them more background on my use case).

In meantime, can you try the following:

## Turn off WebSockets
Tools -> Global Options -> Terminal

Uncheck "Connect with WebSockets"

Now try creating a new terminal (Tools -> Terminal -> New Terminal). Does that work?

**Comment by gtritchie** [comment]
Also see: #2207 

The terminal is supposed to automatically fall back to non-WebSockets but isn't in some cases. I'll be looking into this to see if I can figure out why and make it work as it is supposed to.

**Comment by kevinykuo** [comment]
@gtritchie turning off WebSockets did the trick. Turning it back causes terminal to break again.

**Comment by gtritchie** [comment]
@kevinykuo Cool. The terminal is sluggish (generally) without WebSockets, so if there's any way we can get them enabled in that environment it would be ideal.

**Comment by gtritchie** [comment]
I'm going to resolve this as a duplicate of #2207. RStudio should have fallen back to using RPC (i.e. disabled WebSockets) automatically in this case.

**Comment by jjallaire** [comment]
Would we ever expect Websockets to work over an SSH tunnel? (that's the config here)

Since the Paperspace template is created by just manipulating a regular instance I can go ahead and make that change by default.

**Comment by gtritchie** [comment]
Ah, didn’t realize it was a desktop IDE until I got on there. SSH tunnel, guessing not.

**Comment by gtritchie** [comment]
What's the architecture here, i.e. where's the SSH tunnel in this scenario?

**Comment by jjallaire** [comment]
Both RStudio Desktop and RStudio Server are installed on the instance. The SSH tunnel is used to access the server: https://tensorflow.rstudio.com/tools/cloud_desktop_gpu.html#rstudio-server

**Comment by jjallaire** [comment]
Note that the tunneling command we recommend is this:

```
ssh -N -L 8787:127.0.0.1:8787 paperspace@<public-ip>
```

Is there some other variation that would allow websockets to work correctly?

**Comment by gtritchie** [comment]
Not sure about tunneling and websockets, I'll have to look into that further.

Interestingly, terminal in desktop RStudio (in Paperspace) fails using websockets and doesn't fall back to RPC. If I turn off terminal websockets and restart RStudio, then terminal works.

**Comment by gtritchie** [comment]
Reopening this since it covers some new ground (both using websockets through ssh tunnel, and failure of websockets on desktop IDE).

**Comment by jjallaire** [comment]
I made a configuration change to disable use of websockets by default for both RStudio desktop and server (this might take a few days to roll out though). If there is a better workaround (e.g. some system-level config change that would enable websockets) let me know!

**Comment by gtritchie** [comment]
I've found one problem, a race condition that can prevent IDE from falling back to RPC automatically when a terminal fails to startup with WebSockets. So that's some progress.

The other problem in this environment (which I don't understand yet, but presumably a proxy config issue) is that it takes several minutes for the attempt to use websockets to fail/timeout.

**Comment by gtritchie** [comment]
So, I see the same problem with websockets when I run the rsession unit tests (websocket client cannot connect to server on localhost). Same thing happens when I try to use the echo client/echo server example from the latest version of `websocketpp` library, so doesn't appear to be a problem with our usage of websocketpp in RStudio.

**Comment by steadyfish** [comment]
I faced similar issue as well - Rstudio server on Ubuntu 14.04. The issue seems to happen only when I access the IDE from Firefox, it works fine when I use Chrome. 

Turning off WebSockets does help with the issue in Firefox.

**Comment by alaarab** [comment]
Also experiencing this
Turning off WebSockets works, slow as heck though.

**Comment by gtritchie** [comment]
Confirmed this is still happening, but also noticed that Paperspace's machine is using RStudio 1.1.
