### ISSUE TITLE
Rstudio Window goes black when maximizing window on Windows

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#2568]
If I (1) start Rstudio, (2) start an app in an Rstudio Window, and (3) maximize the Window it goes completely black. Seems to happen reliably for any shiny app, including the default in Rstudio available through "New  file > Shiny web app"

```
> devtools::session_info()
Session info -------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       RStudio (1.2.502)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2018-04-02                  

Packages -----------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.4   2018-03-15 local         
 compiler    3.4.4   2018-03-15 local         
 datasets  * 3.4.4   2018-03-15 local         
 devtools    1.13.5  2018-02-18 CRAN (R 3.4.3)
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)
 graphics  * 3.4.4   2018-03-15 local         
 grDevices * 3.4.4   2018-03-15 local         
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)
 httpuv      1.3.6.2 2018-03-02 CRAN (R 3.4.3)
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.4)
 methods   * 3.4.4   2018-03-15 local         
 mime        0.5     2016-07-07 CRAN (R 3.4.0)
 R6          2.2.2   2017-06-17 CRAN (R 3.4.1)
 Rcpp        0.12.16 2018-03-13 CRAN (R 3.4.4)
 shiny     * 1.0.5   2017-08-23 CRAN (R 3.4.4)
 stats     * 3.4.4   2018-03-15 local         
 tools       3.4.4   2018-03-15 local         
 utils     * 3.4.4   2018-03-15 local         
 withr       2.1.2   2018-03-15 CRAN (R 3.4.4)
 xtable      1.8-2   2016-02-05 CRAN (R 3.4.0)
 yaml        2.1.18  2018-03-08 CRAN (R 3.4.3)
```

**Comment by gtritchie** [comment]
What version of RStudio itself? You can use `Help -> Diagnostics -> Write Diagnostics Report` and submit that, or at least `Help -> About` and get the number from there. Thanks!

**Comment by gtritchie** [comment]
Oops, I see it now! 1.2.502, sorry about that.

**Comment by kevinushey** [comment]
I'm not able to reproduce this on my Windows VM, so I suspect this may be a system-specific issue. Can you share some more information on your system configuration (e.g. video card, version of drivers)?

One simple way to do this would be to run the `System Information` program, then use `File -> Save` to dump all that information to a text file that you could share with us.

**Comment by kevinushey** [comment]
It'd also be helpful to know what version of Windows you're running on. (surprised to see that devtools omits that information)

**Comment by vnijs** [comment]
I'm using Windows 10 in a VM as well. Here you go

[black-window-on-windows.nfo.zip](https://github.com/rstudio/rstudio/files/1877454/black-window-on-windows.nfo.zip)

**Comment by kevinushey** [comment]
It looks like you're using Parallels. Does it make a difference if you enable / disable video acceleration on that VM?

**Comment by vnijs** [comment]
The window goes black when 3D hardware acceleration is on (first screenshot) but *not* when it is off (second screenshot). Windows gets very slow without the 3D acceleration though.

<img width="673" alt="screen shot 2018-04-04 at 2 07 58 pm" src="https://user-images.githubusercontent.com/2998956/38335151-475b4f02-3812-11e8-859a-b90ac12dcb96.png">

<img width="679" alt="screen shot 2018-04-04 at 2 12 33 pm" src="https://user-images.githubusercontent.com/2998956/38335150-4741bd4e-3812-11e8-8ebe-c589164a70aa.png">

**Comment by jmcphers** [comment]
This is caused by virtual display drivers, and is a known issue in other virtual displays (see https://github.com/rstudio/rstudio/issues/2060). 

You can now enable software rendering just for RStudio, so you won't slow down Windows itself. See: https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
