### ISSUE TITLE
No RStudio icon in Add/Remove programs on Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2569]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.x
    OS Version      : Windows-10 (possibly also 8, didn't try)
    R Version       : 

### Steps to reproduce the problem
Install RStudio on Windows-10. Then go to Add/Remove programs and find RStudio in the list.

### Describe the problem in detail
Shown with a generic icon.

### Describe the behavior you expected
Expect it to have the RStudio icon.

Does not impact functionality in any way (and R itself also has a generic icon), but it would look better with the RStudio icon.

![2018-04-02_14-40-41](https://user-images.githubusercontent.com/10569626/38217670-1187e7bc-3684-11e8-95a2-10bfb53b5689.png)

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
