### ISSUE TITLE
Messageboxes on Windows desktop have inoperative context-help "?"

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2570]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.x
    OS Version      : Windows
    R Version       : 

### Steps to reproduce the problem
Do something in RStudio IDE for Windows to show a native Messagebox. For example, make changes to a source file then try to exit without saving:

![2018-04-02_16-08-57](https://user-images.githubusercontent.com/10569626/38220931-cb994f6c-3691-11e8-922a-16ca08fb6b9a.png)

### Describe the problem in detail
The title bar of the messagebox has a "?" control for context help, which will do nothing if you click it except turn the mouse pointer into a "do not" sign which remains until you click somewhere else.

### Describe the behavior you expected
No "?" on titlebars since we don't support context-help.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
