### ISSUE TITLE
RMarkdown notebooks ignore line returns

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2579]
Create the following Rmarkdown notebook:

````Rmd
---
title: "R Notebook"
output: html_notebook
---

```{r}
library(progress)
pb <- progress_bar$new(total = 100)
for (i in 1:100) {
  pb$tick()
  Sys.sleep(1 / 100)
}
```
````

Execute the chunk - you'll see a progress bar display, then go away. This is the expected behaviour.

Now knit the document - you'll see every intermediate line of the progress bar. This is undesirable.

**Comment by kevinushey** [comment]
What version of `progress` are you using? When I run that chunk using the development version of `progress`, I don't see any output (either in the IDE or in the generated HTML document).

**Comment by kevinushey** [comment]
Okay, I see the progress bar drawn with the CRAN release of `progress` but not the current development version.

**Comment by kevinushey** [comment]
The issue here is that we're not handling `\r` correctly in Notebook console output.

**Comment by ronblum** [comment]
[Note when verifying: an issue when previewing, but not when fully knitting.]

**Comment by hadley** [comment]
[But in notebooks, isn't previewing the same as knitting? (Which I don't like, but that's a separate issue)]

**Comment by kevinushey** [comment]
No, it's not -- a preview draws outputs from the RStudio cache of outputs; a full knit does the same thing as it would in an HTML document (it re-runs and re-generates all code and outputs).

Since these are different pipelines you occasionally get different outputs in the end, although we try our best to make the outputs concordant.

**Comment by hadley** [comment]
But command + shift + K just previews?
