### ISSUE TITLE
[FR] Find and replace in whole project

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/rstudio#2582]
From time to time I'm missing the ability to rename something not only in one file but the whole project. Are there plans to implement such a feature?

**Comment by ronblum** [comment]
@fabiangehring Are you looking for something similar to #2066, but defined by project instead of directory tree?

**Comment by fabiangehring** [comment]
Yes, exactly. Wasn‘t aware of this similar other issue.

**Comment by gorkang** [comment]
Should close this issue as it is a duplicate of  #2066 ?

**Comment by kevinushey** [comment]
Yes, let's -- thanks.
