### ISSUE TITLE
Icon in Ubuntu sidebar is the old 3-D marble instead of flat

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2584]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.510-1
    OS Version      : Ubuntu 17.10 (Gnome)
    R Version       : 3.4.3

### Steps to reproduce the problem

Start RStudio Desktop on Ubuntu 17.10.

### Describe the problem in detail

The icon in the sidebar is the old 1.1 3-D marble. The icon in the active applications list at the top is the correct 1.2 flat version.

<img width="197" alt="ubuhtu_icons" src="https://user-images.githubusercontent.com/31009952/38320327-4c2dc3f8-3802-11e8-9f7f-4f302a290935.png">

### Describe the behavior you expected

All icons should be flat. This is only an issue on Ubuntu 17.10. Ubuntu 16.04.3 (also Gnome) and other versions of Linux aren't exhibiting this issue—so this might also be an issue with Ubuntu 17.10, not RStudio, per se.

**Comment by gtritchie** [comment]
I saw this on Ubuntu 16.04 yesterday, so not just 17. Not sure what the variable is at the moment...

**Comment by ronblum** [comment]
Verified in Ubuntu 16.04.5 and 18.04.
