### ISSUE TITLE
Migrate from Qt WebKit to Qt WebEngine

### ISSUE THREAD

**Issue by paulmenzel** [rstudio/rstudio#2596]
RStudio depends on Qt WebKit (`libQt5WebKit.so.5`), which is no longer a “core” Qt component. Qt WebEngine is the successor, so it’d be great to use that.

**Comment by jjallaire** [comment]
We've made this transition in the development version of RStudio (it will roll out in RStudio v1.2). You can download a version of RStudio that uses QWebEngine here: https://dailies.rstudio.com/
