### ISSUE TITLE
Test pane is too aggressive at stealing focus

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2599]
When complete, the tests bring RStudio to the foreground.

Also if you are reading the tests (i.e. the build pane is not scrolled to the bottom), I don't think you should change focus to the issue tab.

**Comment by hadley** [comment]
(In fact, until the issues pane is a bit more useful, I'd actually prefer if you never changed focus to it)

**Comment by javierluraschi** [comment]
@hadley the issues tab is no longer opened by default with `testthat`, let me know if I missed anything!

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
