### ISSUE TITLE
E-mails to Administrators not putting %20 in link to Edit User

### ISSUE THREAD

**Issue by mattycarlson** [rstudio/rstudio#2600]
### System details
    RStudio Edition :  Server
    RStudio Version :  RStudio Connect 1.5.14
    OS Version      :  Red Hat Enterprise Linux Server release 7.2
    R Version       :  R version 3.4.3

### Steps to reproduce the problem
Have a user request a role promotion on the Content page.
### Describe the problem in detail
The e-mail Administrators receive does not include an accurate link to the Edit User page:
```
John Doe (JOHNDOE) has requested an account upgrade from "viewer" to "publisher" on your RStudio Connect server.

You can manage this user's permissions using the following link: https://rstudio-connect.company.com/connect/#/people/users/CN=John Doe,OU=Users,OU=Team,OU=Department,DC=company,DC=com/edit
```
So the link is only recognized as **https://rstudio-connect.company.com/connect/#/people/users/CN=John** because of the space.

### Describe the behavior you expected
The e-mail template should replace spaces with **%20**.
`https://rstudio-connect.company.com/connect/#/people/users/CN=John%20Doe,OU=Users,OU=Team,OU=Department,DC=company,DC=com/edit`

**Comment by ronblum** [comment]
Hi @mattycarlson—this repository is intended for questions about RStudio, the IDE (Server and Desktop). For issues with RStudio Connect, please contact the professional Support Team directly at support@rstudio.com. Thanks!
