### ISSUE TITLE
yaml gets eagerly loaded on IDE launch

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2602]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.508
    OS Version      : Windows 10 x64
    R Version       : R 3.4.4

### Steps to reproduce the problem

Launch RStudio, and open a project. Execute `loadedNamespaces()`.

### Describe the problem in detail

`yaml` is already loaded.

### Describe the behavior you expected

We should avoid eagerly loading packages on launch, and only do so in response to user gestures.

**Comment by jmcphers** [comment]
This was a fun one to track down. :-) It doesn't happen right on boot; it happens while we're doing the lazy indexing for R Markdown templates (which usually occurs very shortly thereafter). 

https://github.com/rstudio/rstudio/blob/1604ffc3f47fb656408cdb645b2d7b43baefb093/src/cpp/session/modules/SessionRMarkdown.R#L161-L162

I can think of three solutions:

1. Try to pretend that we didn't load the `yaml` package (i.e. unload it when we're done if we had to load it)
2. Refactor such that the work is done in a separate worker R process
3. Discover only the template YAML files themselves when indexing; delay the actual file parsing until we are asked for the list of templates

**Comment by dfalty** [comment]
Verified fixed 1.2.1312
