### ISSUE TITLE
small UI issues (positioning of icons, etc)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2603]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.508
    OS Version      : Windows 10 x64
    R Version       : R 3.4.4

### Details

<img width="410" alt="screen shot 2018-04-05 at 8 53 31 am" src="https://user-images.githubusercontent.com/1976582/38377115-086576e0-38af-11e8-8347-f2e51bc24ebb.png">

The icons here should be shifted down a single pixel.

<img width="283" alt="screen shot 2018-04-05 at 8 53 47 am" src="https://user-images.githubusercontent.com/1976582/38377129-14d359a6-38af-11e8-91aa-bf67ceff6c99.png">

The checkbox next to the Home icon is too close to the top-left of its 'space'.

**Comment by jjallaire** [comment]
There may be some global CSS that we are using for windows toolbar icons that we can change in one place to resolve this (not sure but it's definitely possible)

**Comment by jmcphers** [comment]
Here's what it looks like in 1.1: 

![image](https://user-images.githubusercontent.com/470418/39158832-112a2430-4717-11e8-829d-524c82ebd953.png)

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
