### ISSUE TITLE
Feature request: don't focus console following 'Install and Restart'

### ISSUE THREAD

**Issue by mkearney** [rstudio/rstudio#2604]
I don't believe this is a bug (though I wondered if maybe 'Focus console after executing from source' could be interpreted in a way that would extend to this).

When working on an .Rproj R package, clicking the 'Install and Restart' button inevitably (once it's done installing the pkg and restarting R) results in focus console. Would it be possible to change this behavior to not override the current focus? Or perhaps include an option similar to 'Focus console after executing from source'?

This is obviously a very minor feature, but it's something I wished was changed about Rstudio for a while now. Also, I'm not great at reading directions and, consequently, filled out the details to the prompts, so I included those below just in case.

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.423
    OS Version      : macOS High Sierra Version 10.13.4
    R Version       : 3.4.4

### Steps to reproduce the problem

    1. Create .Rproj R package
    2. Open new script file and focus cursor somewhere on script.
    3. Click 'Install and Restart'.
    4. Watch focus move to console.

### Describe the problem in detail

    The focus moves from the script file to the console.

### Describe the behavior you expected

    I would like the focus to stay on the script file.

**Comment by ronblum** [comment]
@mkearney Thank for the suggestion—we'll consider it as we work on development of future versions of RSTudio. And you followed the directions just fine: your responses to the guided prompts—especially the steps to reproduce—coupled with your narrative, made for a very clear request!
