### ISSUE TITLE
Failed installation at "Generating ui_DesktopInputDialog.h"

### ISSUE THREAD

**Issue by butcherq** [rstudio/rstudio#2611]
### System details

    RStudio Edition : Desktop
    RStudio Version : Release
    OS Version      :  Ubuntu xenial (crouton)
    R Version       :  3.2.3

### Steps to reproduce the problem

Following installation steps.

### Describe the problem in detail
I have followed the steps as they were in install instructions. Installed dependencies and proceeded with making a build and installation. After a while an error shown below occured and the installation stopped.
```
Scanning dependencies of target diagnostics
[ 41%] Building CXX object src/cpp/diagnostics/CMakeFiles/diagnostics.dir/DiagnosticsMain.cpp.o
[ 41%] Linking CXX executable diagnostics
[ 41%] Built target diagnostics
[ 41%] Generating ui_DesktopInputDialog.h
/home/butcherq/Qt5.10.1/5.10.1/gcc_64/bin/uic: 1: /home/butcherq/Qt5.10.1/5.10.1/gcc_64/bin/uic: Syntax error: "(" unexpected
src/cpp/desktop/CMakeFiles/rstudio.dir/build.make:183: recipe for target 'src/cpp/desktop/ui_DesktopInputDialog.h' failed
make[2]: *** [src/cpp/desktop/ui_DesktopInputDialog.h] Error 2
CMakeFiles/Makefile2:554: recipe for target 'src/cpp/desktop/CMakeFiles/rstudio.dir/all' failed
make[1]: *** [src/cpp/desktop/CMakeFiles/rstudio.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
``` 
Previously I have installed Server by a mistake and it came to an end with more or less no problems.

### Describe the behavior you expected

Finished installation.

**Comment by butcherq** [comment]
I should add that I am using Acer R13 which has arm processor.

**Comment by jmcphers** [comment]
Are you trying to cross compile to x86? It sounds like what you're experiencing is an issue with the Qt user interface compiler on your platform which we can't generally offer support for. If you just need a custom build of RStudio, you should be able to compile using one of our Docker images:

https://github.com/rstudio/rstudio/wiki/Building-with-Docker

Hope this helps!
