### ISSUE TITLE
Support for ultra wide screen and multiple monitors

### ISSUE THREAD

**Issue by Nekochef** [rstudio/rstudio#2612]
Currently I'm working on a laptop with an extended ultra wide screen (21:9), it might be more convenient to float some panes (e.g. the plot window) in the laptop screen and split the other panes in the ultra wide screen into 3 or more columns. 
I think a more flexible UI would improve R studio a lot, and bring users more inspirations. I googled a lot and found that those features were said to be in progress for years, did I miss something? Are we going to have those features in the future?

**Comment by jmcphers** [comment]
That's a good question. We've been slowly making things more friendly to multi-monitor displays over the last few years (for instance you can now have floating source windows, zoom the plots pane, etc.). 

However we aren't currently working on any wholesale improvements on this area, though we may do so in a future release. 

See also: https://github.com/rstudio/rstudio/issues/2135
