### ISSUE TITLE
The RStudio won't open in my Mac

### ISSUE THREAD

**Issue by brunopfischer** [rstudio/rstudio#2614]
RStudio Edition: Desktop
RStudio Version: 1.1.442
R Version: 3.4.4
My mac: OS X El Capitan 10.11.5

I have the R installed and it works fine. However, when I download RStudio desktop, the following message appears and the program doesn't open. I have already tried to deinstall and download again both programs and the problem continues. Can someone help me?

![message](https://user-images.githubusercontent.com/38222279/38510532-bcdb2b48-3bfb-11e8-9414-9a08015b2c04.png)

**Comment by jmcphers** [comment]
Sorry, we can't generally help with these kinds of issues on our Github issues page (this is for reporting bugs in RStudio). 

We usually see this error when R versions are mismatched or incompletely uninstalled. I'd recommend uninstalling all of the R versions you have, cleaning `Libraries` folder where it resided, and removing your user R package library. 

If none of that helps, you might try adding some detail and asking on our community forum:

https://community.rstudio.com/
