### ISSUE TITLE
syntax highlighting for #!/usr/bin/r #!/usr/bin/Rscript etc files

### ISSUE THREAD

**Issue by jackwasey** [rstudio/rstudio#2616]
### System details

    RStudio Edition :desktop
    RStudio Version :  Version 1.1.423 – © 2009-2018 RStudio, Inc.
    OS Version      :  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko)
    R Version       :  3.4.3

### Steps to reproduce the problem

1. take any R script
2. remove filename extension
3. insert first line: #!/usr/bin/env Rscript (or similiar as appropriate to platform, /usr/bin/r from @eddelbeuttel 's `littler` would be great, too)
4. open the file in RStudio preview v444
### Describe the problem in detail

Note that no syntax highlighting is performed.

If there is an .r or .R extension, there is indeed highlighting, but commonly scripts designed to run on command line have the #! header and no file extension.

### Describe the behavior you expected

syntax highlighting.

**Comment by ronblum** [comment]
@jackwasey Thank you for the suggested feature!

**Comment by MichaelChirico** [comment]
This would be a great way to get RStudio to do proper highlighting (and, hopefully, allow <kbd>Ctrl</kbd>+<kbd>Enter</kbd> execution to boot!) on, a file I'm using all the time: [`data.table`'s `tests.Rraw` file](https://github.com/Rdatatable/data.table/blob/master/inst/tests/tests.Rraw) which is `source`d by the `test.data.table` testing regime for that package.
