### ISSUE TITLE
roxygen comments are reflowed incorrectly in C++ code

### ISSUE THREAD

**Issue by jackwasey** [rstudio/rstudio#2617]
### System details

    RStudio Edition :desktop
    RStudio Version :  Version 1.1.423 – © 2009-2018 RStudio, Inc.
    OS Version      :  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko)
    R Version       :  3.4.3

### Steps to reproduce the problem

Create a new Rcpp C++ file from standard template using RStudio.
Insert a roxygen comment block with several lines before a function, e.g.
```
//' multiple by two
//' 
//' description is here
//' @export
// [[Rcpp::export]]
NumericVector timesTwo(NumericVector x) {
  return x * 2;
}
```

move caret into the comment block and reflow the comments.

### Describe the problem in detail

unlike with #' R comments, //' C++ comments are all reflowed onto one line, ignoring the roxygen-style comment formatting.

### Describe the behavior you expected

roxygen sections are maintained with or without roxygen keyword insertion, as for #' R comments.

**Comment by ronblum** [comment]
@jackwasey Thank you for raising this concern. We will review it as we work on development of future versions of RStudio.
