### ISSUE TITLE
Add a way to clear the application deployment cache from the IDE

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rstudio#2621]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.x
    OS Version      : all supported
    R Version       : all supported

### Steps to reproduce the problem
After deploying a Shiny application or Rmd file to shinyapps.io or Connect server, try to remove the deployment cache so that you can alter the deployment in some way.  For example, if you deploy an app to shinyapps.io then delete the app, you need to clear the deployment cache before you can redeploy an app with the same name.

### Describe the problem in detail
Currently, the only way to clear the deployment cache for an application is to delete the /rsconnect/shinyapps.io/your-username/your-project.dcf file. I've [filed an issue in the `rsconnect` repo](https://github.com/rstudio/rsconnect/issues/267) to add a function for to clear the cache, and after it is implemented, it would be great if the IDE had an affordance to call that function from a control in the UI.  One idea would be to add an option in the Publish menu below the deployments list to "Forget all deployments...", or add a little broom icon next to the individual deployments in the list for more fine-grained control.

**Comment by jmcphers** [comment]
Implemented in https://github.com/rstudio/rstudio/pull/3854.

**Comment by dfalty** [comment]
Verified functionality 1.2.1316-1
