### ISSUE TITLE
R diagnostics false-positives for magrittr and namespaced function calls

### ISSUE THREAD

**Issue by agwells** [rstudio/rstudio#2625]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Ubuntu Linux 16.04
    R Version       : 3.4.4

### Steps to reproduce the problem

1. Install the "magrittr" R package
2. Enable the "Check arguments to R function calls" setting for R diagnostics. (Tools -> Global Options -> Code -> Diagnostics)
3. Write an R script with these lines of code, and run RStudio's diagnostics on it:

```r
library(magrittr)

123 %>% rnorm() # no problem
123 %>% stats::rnorm() # Warning: argument 'n' is missing, with no default
```

### Describe the problem in detail

RStudio's diagnostics are smart enough to work with the magrittr pipe operator `%>%` for non-qualified function calls like `rnorm()`, recognizing that magrittr will supply the first argument to the function call. But when a namespaced function call like `stats::rnorm()` is used with magrittr, the diagnostics engine no longer recognizes that magrittr is providing the first argument to the function call, and marks it with the incorrect warning "argument 'n' is missing, with no default".

(Without knowing anything about the underlying code, my guess is that the presence of the `::` operator is making the diagnostics engine treat `stats::rnorm()` as a multi-part expression rather than a single function call.)

### Describe the behavior you expected

Because magrittr itself has no problem using namespaced function calls with the `%>%` operator, the diagnostics engine should recognize them as syntactically correct.

**Comment by agwells** [comment]
Fortunately there are some easy workarounds:

1. For single-argument function calls, magrittr lets you omit the parentheses: `123 %>% stats::rnorm`
2. For multi-argument function calls, you can use magrittr's `.` argument placeholder: `df %>% tidyr::spread(., key = col1, value = col2)`

**Comment by jackwasey** [comment]
This is a more general problem when a function is defined with a potentially missing parameter, and the function body uses `missing(maybe_missing_arg)`.
