### ISSUE TITLE
mousewheel event listener gets inserted into javascript code for htmlwidget in rmarkdown inline view

### ISSUE THREAD

**Issue by AliciaSchep** [rstudio/rstudio#2634]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.545 and 1.1.442
    OS Version      :  Ubuntu 
    R Version       : 3.4.3

### Steps to reproduce the problem

I have created a minimal example:

https://gist.github.com/AliciaSchep/ea472176ae9a75237be6a863af14f942

If you run the example rmarkdown (note: it downloads the vega-embed.js file) and then look at the console for the last chunk output, it shows an error.  If you look at the source of the error, you can see that rstudio's "mousewheel" event listener has been inserted into the vega-embed.js source.

### Describe the problem in detail

It appears that Rstudio adds a "mousewheel" event listener into the head of the iframe for an htmlwidgets chunk:
![javascript_added](https://user-images.githubusercontent.com/6809790/38656396-12526d46-3dcf-11e8-9db3-c840f64896b6.png)

However, it also adds that event listener into vega-embed.js when that is included as a dependency: 

![inserted_javascript_wrong_place](https://user-images.githubusercontent.com/6809790/38657295-3ae24c72-3dd4-11e8-9e0c-9a300f5ed5e5.png)

The source code where it added it:

![where_it_gets_inserted](https://user-images.githubusercontent.com/6809790/38657304-48fe9630-3dd4-11e8-876b-1ebe2bc4d329.png)

It appears that the "head" tags in the javascript are being incorrectly used to insert an extra copy of the event listener.  Editing the vega-embed.js source code to split up "head" into "he" + "ad" seems to be a hacky work-around that solves the issue.  Ideally, the event listener should not be inserted into any javascript dependency files though.

Note: this issue arose in a project for making vegalite visualizations using altair + reticulate.  The source issue: https://github.com/ijlyttle/altair/issues/11

### Describe the behavior you expected

The wheel event listener should not be inserted into javascript dependencies.  
With the above minimal example, the "SyntaxError: Expected an identifier but found 'text' instead" should not appear.

**Comment by jmcphers** [comment]
Thanks so much for taking the time to put together a reproducible example. Should be fixed in the next daily build. :-)

**Comment by AliciaSchep** [comment]
Thanks for the quick fix!!!
