### ISSUE TITLE
R command is run twice

### ISSUE THREAD

**Issue by sandbarTrue** [rstudio/rstudio#2635]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 0.99.893 
    OS Version      : win8
    R Version       : R-3.4.0

### Describe the problem in detail
I have been having an odd issue with RStudio.

When I use any command to run the script (so either Ctrl + R, Ctrl + Enter, or the actual Run command on RStudio) that command is run twice.

**Comment by jmcphers** [comment]
You're using a very old version of RStudio (0.99); could you try with the latest stable version to see if you still have the issue?

https://www.rstudio.com/products/rstudio/download/
