### ISSUE TITLE
Build tab to have 'New Window' option

### ISSUE THREAD

**Issue by CharlesCara** [rstudio/rstudio#2637]
Not a bug but a small suggested enhancement to the brilliant R-Studio.  It would be useful to be able to show the Build tab in a new window, just as the code tabs can be.

This would help reviewing the output of long testthat unittests.

**Comment by ronblum** [comment]
@CharlesCara Thanks for the suggestion—we'll review it as we work on future versions of RStudio. And thank you for the compliment!
