### ISSUE TITLE
Highlight Linux distribution buttons for daily builds

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2638]
### System details

    RStudio Edition : Desktop
    RStudio Version : Multiple versions of Linux—CentOS, Debian, Fedora, openSUSE, RedHat, and Ubuntu
    OS Version      : 1.2.x
    R Version       : 3.4.x (N/A)

### Steps to reproduce the problem

Go to the [RStudio daily builds](https://dailies.rstudio.com) page.

### Describe the problem in detail

The buttons for downloading the latest RStudio Desktop are not highlighted in blue for the Linux distributions.
<img width="748" alt="linux_no_pick" src="https://user-images.githubusercontent.com/31009952/38686433-4a1841d8-3e42-11e8-8cce-c6483d79fe1a.png">

### Describe the behavior you expected

Highlight the button for the appropriate distribution—Ubuntu for the different versions of Ubuntu, Fedora for the rest. This is what currently happens on MacOS and Windows.
<img width="743" alt="windows_yes_pick" src="https://user-images.githubusercontent.com/31009952/38686440-4eb9420a-3e42-11e8-8cdf-909c482d961e.png">

(This isn't quite a blocker, so I'm marking it _low_.)

**Comment by jmcphers** [comment]
This issue should be filed over here instead: https://github.com/rstudio/dailies

(It's not always possible to get exact Linux distribution details in the browser, so it's possible we just won't be able to do this, but worth checking UA strings to see!)
