### ISSUE TITLE
Cmd-Enter not workin in R Console (1.2.536, macOS 10.13.5 beta 1 Desktop)

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#2641]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.536  
    OS Version      :  10.13.5 beta 1
    R Version       :  3.4.4 (2018-03-15)

### Steps to reproduce the problem

type something in the R Console pane and hit cmd-enter

### Describe the problem in detail

cmd-enter, while the R console is in focus, executes lines in the active source pane

### Describe the behavior you expected

cmd-enter in R console should behave like always - execute the console line

gif below shows the behaviour

![cmd-enter](https://user-images.githubusercontent.com/509878/38695154-6b08d9a4-3e59-11e8-9e24-f7eb2dbe6ddd.gif)

**Comment by ronblum** [comment]
@hrbrmstr Thank you for raising this bug. We will review it as we work on development of RStudio.

**Comment by jmcphers** [comment]
Confirmed repro on 1.2.544. Interestingly enough it works just fine if you don't have the Source pane open (somehow it's always handling Cmd+Enter if present).

**Comment by jmcphers** [comment]
@hrbrmstr Was a recent regression; should be fixed in the next dailies. Thanks much for using daily builds and appreciate the report!

**Comment by ronblum** [comment]
You're welcome, @hrbrmstr!
