### ISSUE TITLE
Last column in Source pane (utils::View()) is impossible to resize

### ISSUE THREAD

**Issue by cheTesta** [rstudio/rstudio#2642]
### System details

    RStudio Edition : Desktop 
    RStudio Version :  1.1.442
    OS Version      :  Win7 Enterprise
    R Version       : 3.4.4 (2018-03-15) -- "Someone to Lean On"

### Steps to reproduce the problem

- Open object (tbl, data.frame...), via `utils::View()` comand in Console / clicking on the Obj logo in Global Environment
- In the object tab, try to resize last column (enlarge, restrict)

### Describe the problem in detail
`View() tab` opened in Source Window (Attached/Detached Source Editor) enables user to resize (+/-) _every column **but** the last one_. 

Issue happens both with "narrow" objects, [e.g. formed by just two columns] and with "wider" ones [e.g. object whose columns are by default wider than screen real estate/source pane dimension, actually requiring user to use horizontal scrolling].

Futhermore, expecially with narrow obj, the allineation between the title cell (first row containing column names) and the actual data cells gets crazy (both when enlarging or reducing column size).
With wider obj, this misallineation issue is less evident, but it is generally impossible to resize (**enlarge**) the whole column.

Issue seems content unrelated: I've been experiencing it both with obj containing textual data and with numerical, both in title and in content.

### Describe the behavior you expected

- Allineation between column header and actual content should be graphically stable and allined.
- Last column (righter one) should be resizable in the pane 
- Last box on title row (last column name), with wide objects, shoud stop in line with data column line.

**Comment by pascaloettli** [comment]
Is there any progress regarding this problem? It also exists in preview `1.2.1511-1` and in daily build `1.3.165`

**Comment by oliverroc** [comment]
Hi, I am not sure if I should open or not a new issue for these, but I think it's kind of related.

I found myself with the same problem right now (RStudio Version : 1.2.1335), but even you fix this, for large text data it would be also great to have the option of double clicking the column header and it automatically expands the column to it's maximum length.

Should I open a new Issue?
