### ISSUE TITLE
r2d3 repository not available

### ISSUE THREAD

**Issue by patrickr81** [rstudio/rstudio#2647]
### System details

    RStudio Edition : Desktop
    RStudio Version :  
    OS Version      :  Clear Linux
    R Version       : 

### Steps to reproduce the problem
run /dependencies/install-packages
fails to clone https://github.com/rstudio/r2d3

### Describe the problem in detail
repository /rstudio/r2d3 is not found
presents unhelpful login error message
 
### Describe the behavior you expected
installs r2d3

### Comments
likely problem is fact that r2d3 repository is no longer at /rstudio/r2d3

**Comment by jjallaire** [comment]
That repo is still private (it will be made public in about a week after the documentation is ready). For now I would just comment out the line in install-packages

**Comment by patrickr81** [comment]
I'll wait, ty.

**Comment by xrobin** [comment]
Unfortunately commenting the line makes it impossible to configure Rstudio with cmake:

CMake Error at src/cpp/session/CMakeLists.txt:41 (message):
  r2d3 package not found (re-run install-dependencies script to install)

**Comment by jmcphers** [comment]
Yes, you'll also need to comment lines 40-42 of that CMakeLists.txt file.

**Comment by jmcphers** [comment]
r2d3 is public now!

https://github.com/rstudio/r2d3

**Comment by ppaschos** [comment]
good... but you include it in the rstudio source distribution? or give us instructions on how to place it there before we build rstudio from source

**Comment by jjallaire** [comment]
The `install-packages` script in the dependencies folder (which is called by `install-dependencies`) takes care of this.

**Comment by ppaschos** [comment]
we install them one by one... so for the time being i have commented out the r2d3 in the CMakeList
