### ISSUE TITLE
View(data) long freezes on Linux

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#2648]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.444
    OS Version      : Xubuntu 17.10
    R Version       :  3.4.4
Anecdotal but to be clear: new gaming rig, 16gb memory, ryzen 7 1700 CPU, 1080Ti GPU. Basically the hardware isn't the issue. Or shouldn't be!

### Steps to reproduce the problem
Download a decent sized datasheet, mine is 7.4mb xlsx converted to 7mb csv. 49286 obvs of 39 variables [I've asked my colleague for the link as this is a free dataset but I've had this happen with lots of datasets].
Bring into RStudio with read.csv or using GUI.
Examine with view() or using GUI.
Trying to scroll around the sheet or sort by header.

### Describe the problem in detail
Causes lengthy freezes; often the cursor will flick between default (arrow), text bar, L-R expand double arrow, and 'black hand pointing'. RStudio is inactive during that time and registers no response to clicking on other tabs or menu items.

I presume this isn't happening for other people as otherwise a bug would have been filed...

**Comment by SimonDedman** [comment]
Dbase location: http://calcofi.org/downloads/database/195101-201607_Zoop.zip

**Comment by jmcphers** [comment]
Thanks for reporting! This is a known issue, and we're tracking it in https://github.com/rstudio/rstudio/issues/1771.
