### ISSUE TITLE
Inconsistent copy/paste behaviour between OS-X/Linux/Windows

### ISSUE THREAD

**Issue by pvermees** [rstudio/rstudio#2652]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Mac OS 10.10.5 (and higher)
    R Version       : 3.2.3

### Steps to reproduce the problem

#1. install IsoplotR and IsoplotRgui from GitHub (requires devtools and shiny):
install_github('pvermees/IsoplotR')
install_github('pvermees/IsoplotRgui')

#2. run the Shiny app:
library(IsoplotRgui)
IsoplotR()

### Describe the problem in detail

I cannot copy or paste data to-and-from the input window of the shiny app. This problem only occurs in the OS-X edition of RStudio. Copying and pasting works fine on my Linux box. I haven't tried Windows yet. When run inside a browser, the app works fine on any platform.

### Describe the behavior you expected

I would expect RStudio to work the same on Mac, PC and GNU/Linux.

**Comment by ronblum** [comment]
@pvermees I'm not able to reproduce this—I'm able to copy and paste the data when the Shiny app is run within RStudio. Do you see difference between running it in a window and running it in the viewer pane?

**Comment by pvermees** [comment]
@ronblum Are you using OS-X? 

> Do you see difference between running it in a window and running it in the viewer pane?

The viewer pane is empty, so I don't know what you mean with that. To make sure that we're talking about the same thing, an online version of the app can be accessed at:

[http://pieter-vermeesch.es.ucl.ac.uk/shiny/IsoplotRshiny/R/](http://pieter-vermeesch.es.ucl.ac.uk/shiny/IsoplotRshiny/R/)

Copying and pasting from/to the left hand panel works fine in a web browser, but not when the app is run offline in an RStudio window. Again, the problem only occurs in OS-X. Several users have informed me of this problem, and I've verified it myself.

**Comment by pvermees** [comment]
Perhaps this might help. When I run the app in RStudio, the following warning message appears at the console:

> Listening on http://127.0.0.1:4796
Warning in dir.create(configDir, recursive = TRUE) :
  cannot create dir '/Users/pieter/Library/Application Support/R/connect/servers', reason 'Permission denied'

Do I have to run RStudio as administrator?

**Comment by pvermees** [comment]
I updated the external javascript libraries in my app and copy-paste now works. Problem solved!
