### ISSUE TITLE
Syntax highlighting for Rmd headings (for some themes)

### ISSUE THREAD

**Issue by RichardJActon** [rstudio/rstudio#2654]
Headings in R markdown could do with some form of syntax highlighting, they are a bit hard to distinguish from the body of the text when skimming an Rmd file. Most Markdown syntax highlighters make headings pretty prominent in other editors.

**Comment by jmcphers** [comment]
Which theme are you using? In most themes they should have a very different color from body text. In the default theme, for example, they are bright blue.

![image](https://user-images.githubusercontent.com/470418/38949600-b25fc482-42f7-11e8-9291-0c377695b38e.png)

**Comment by RichardJActon** [comment]
i'm using the 'modern' theme

![image](https://user-images.githubusercontent.com/6893043/39042438-b8d8c674-4482-11e8-9f0e-a5277ce00b0b.png)

**Comment by ronblum** [comment]
This is true for some other themes, such as "Cloud," "Clouds Midnight," "Solarized", and "Solarized Dark," but others.

**Comment by harlecin** [comment]
Have the same problem with Monokai.

Currently I switch to Twilight when I want coloring of headings, but if you could fix it for Monokai, that would be huge for me:)

PS: Thx so much for all your amazing work at RStudio! This product is amazing!
