### ISSUE TITLE
https protocol fails to load within viewer pane on Linux and Windows 

### ISSUE THREAD

**Issue by schloerke** [rstudio/rstudio#2661]
#### Fails
    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : ubuntu 16.04
    R Version       : 3.4.4

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Windows 10 Enterprise Evaluation version 1709 build 16299.19
    R Version       : 3.4.4

#### Works
    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : 10.13.3
    R Version       : 3.4.4

### Steps to reproduce the problem
```r
library(htmltools)
print(browse=TRUE, tags$img(src="https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-125.png"))
```

#### Linux
Looking at the inspector, it states: `Failed to load resource: Protocol "https" is unknown`

![screen shot 2018-04-18 at 1 02 35 pm](https://user-images.githubusercontent.com/93231/38946871-ce8a3668-4308-11e8-8eb4-470bdaeb4efb.png)

#### Windows
Looking at the inspector, it states: `Failed to load resource: Unable to init SSL Context`

![screen shot 2018-04-18 at 1 15 53 pm](https://user-images.githubusercontent.com/93231/38947446-bf233d44-430a-11e8-9dd8-97a718cc2a27.png)

### Describe the behavior you expected

Should display this image in the viewer pane:
![rstudio-logo](https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-125.png)

@jcheng5

**Comment by jmcphers** [comment]
Do you also see this in the RStudio 1.2 dailies? 

https://dailies.rstudio.com/

RStudio 1.2 uses Chromium under the hood (1.1 has an older WebKit engine) so should have improved SSL support.

**Comment by jcheng5** [comment]
It works great on 1.2, yes.

**Comment by schloerke** [comment]
upgraded both boxes, works on both.

**Comment by jmcphers** [comment]
Okay, thanks for checking! Works for me on 1.2, too, so I don't think there's anything we can do here (we aren't planning to backport the rendering engine to 1.1 since it's a major architectural change).
