### ISSUE TITLE
Blank window left open after fullscreen in OSX

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#2663]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2 
    OS Version      :  macOS 10.13.4
    R Version       :  3.4.4

### Steps to reproduce the problem
1. Run the IDE in full screen.
2. On a second monitor, have a second IDE window open in full screen.
3. Reload the IDE UI.

### Describe the problem in detail
The second window unloads and a blank black screen is left behind on the second monitor. The second window reloads in full screen on the first montior (where the first window is located).

### Describe the behavior you expected
The second window reloads in place.

**Comment by MariaSemple** [comment]
This also happens if you close the last file in the secondary window. The following error is output at the same time:
`[34057:95323:0514/110325.175200:ERROR:mach_port_broker.mm(175)]` Unknown process 34127 is sending Mach IPC messages!
2018-05-14 11:14:24.063 RStudio[34057:29569830] IMKInputSession [0x7f87d29947f0 presentFunctionRowItemTextInputViewWithEndpoint:completionHandler:] : [self textInputContext]=0x7f87d141a2b0 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 0 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 0 was invalidated from this process.}, com.apple.inputmethod.EmojiFunctionRowItem`

**Comment by javierluraschi** [comment]
I have a simpler reprex:

1. Open R file as satellite window
2. Maximize satellite window
3. Close or restore satellite window

Looks like a QT issue (see https://bugreports.qt.io/browse/QTBUG-46701), currently with a patch in code review: https://codereview.qt-project.org/#/c/227275/ but not yet fixed in devel.

**Comment by javierluraschi** [comment]
Issue https://github.com/rstudio/rstudio/issues/2839 has a few more screenshots from @dfalty, coping here:

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.656
    OS Version      : Mac 10.12.6
    R Version       : 3.5.0

### Steps to reproduce the problem
1. Open RStudio in full-screen mode
2. Create the default shiny application
3. Record Test
4. Take at least one snapshot
5. Save script and exit test event recorder
6. Observe you now have an orphaned black window and you will get more if you do this over and over

### Describe the problem in detail
Orphaned windows after exiting shiny app (shinytest) when RStudio is fullscreen. 
![image](https://user-images.githubusercontent.com/15237845/40446610-644d3a7c-5e95-11e8-9aaa-7fcf77bfcb0d.png)

**Comment by kevinushey** [comment]
Still reproduces with Qt 5.12.

**Comment by RSchwinn** [comment]
Still reproducible today.

**Comment by kevinushey** [comment]
Workaround from https://bugreports.qt.io/browse/QTBUG-46701?focusedCommentId=451328&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-451328 we could try:

```
void NativeWindow::closeEvent(QCloseEvent* event)
{
	QMainWindow::closeEvent(event);
	
	NSView* view = reinterpret_cast<NSView*>(winId());
	if (view == nil)
		return;
	
	NSWindow* window = view.window;
	if (window == nil)
		return;
	
	[window close];
}
```

**Comment by aljrico** [comment]
This is still happenning to me.

```
RStudio Edition : Desktop
RStudio Version: 1.4.1717
OS Version: Mac 11.4
R Version: 4.1.0
```
