### ISSUE TITLE
Console rendering issue mixing \r and colors

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2665]
Reported by @hadley via Slack (quite a while ago).
```
f1 <- function() {
  cat("✔ xxx", crayon::blue("yyy"), "xxx")
  cat("\r")
  cat("✔xxx", crayon::red("yyy"), "zzz")
  cat("\n")
}
f2 <- function() {
  cat("✔ xxx", crayon::blue("yyy"), "xxx")
  cat("\r")
  cat("✔ xxx", crayon::red("yyy"), "zzz")
  cat("\n")
}


f1()
f2()
```
Expected output (as seen in standalone R via Terminal.app):
![2018-04-18_20-44-04](https://user-images.githubusercontent.com/10569626/38970257-5431e456-4349-11e8-95a4-a0ee3b0614a8.png)

Actual output (RStudio 1.2.565

![2018-04-18_20-45-59](https://user-images.githubusercontent.com/10569626/38970303-86b276c0-4349-11e8-8e93-ad0ac1e80d9d.png)

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
