### ISSUE TITLE
"Run Selected Line(s)" not backtracking pipes through newlines

### ISSUE THREAD

**Issue by lgaborini** [rstudio/rstudio#2667]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    Platform        : x86_64-w64-mingw32/x64 (64-bit)
    OS Version      : Windows >= 8 x64 (build 9200)
    R Version       : 3.4.4 (2018-03-15)

When I execute "Run selected line" on the following chunks, they are correctly executed if the cursor is in the first two lines of the pipe (starting from `mtcars`):

```r
library(dplyr)

# First chunk (breaks)
mtcars %>% 
   mutate(
      a = disp*2) %>% 
   select(mpg, cyl, disp)

# Second chunk (works)
mtcars %>% 
   mutate(
      a = disp*2
   ) %>% 
   select(mpg, cyl, disp)

# Third chunk (works)
mtcars %>% 
   mutate(a = disp*2
   ) %>% 
   select(mpg, cyl, disp)
```

In the first chunk, if the first command is ran when the cursor is in or after the line which starts with `a =`, the IDE only sends the last two lines to the console, thus breaking the pipe and generating a syntax error.

(I understand it is not a big issue, it actually helps in keeping a good indentation. Thank you.)

### Packages in `sessionInfo()`
```
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2 dplyr_0.7.4   

loaded via a namespace (and not attached):
 [1] compiler_3.4.4   magrittr_1.5     assertthat_0.2.0 R6_2.2.2         tools_3.4.4      pillar_1.2.1     glue_1.2.0       tibble_1.4.2     yaml_2.1.18     
[10] Rcpp_0.12.16     pkgconfig_2.0.1  rlang_0.2.0      bindr_0.1.1 
```

**Comment by ronblum** [comment]
@lgaborini Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.
