### ISSUE TITLE
The value in chunk options disappears

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#2673]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version :      Windows 10
    R Version :       3.4.4 (2018-03-15)

### Steps to reproduce the problem

1. Open R Markdown document.
2. Create a new chunk.
3. Write `{r fig.cap = CAPTION}` in the chunk options. Pay attention to spaces around `=`. When the spaces around equal sign are not present, the problem is not present too.
4. Change chunk options through chunk settings button as shown in the figure below.

![rs chunk opts bug1](https://user-images.githubusercontent.com/12725868/39059593-ac619da4-44c7-11e8-8a74-ec208e2a7687.gif)

### Describe the problem in detail

I have a chunk for a plot in an R Markdown document. The text in the chunk options: 
`{r fig.cap = CAPTION}`. When I try to change options by clicking on the chunk settings button, value `CAPTION` disappears. Please find an animated example in the figure above.

### Describe the behavior you expected

The spaces around `=` may or may not disappear but I expect value `CAPTION` to persist after changing the options.

**Comment by ronblum** [comment]
Thanks for reporting this, @GegznaV. We'll review this during ongoing RStudio development.

Confirmed in RStudio MacOS Desktop 1.2.573.

**Comment by GegznaV** [comment]
Still reproducible in RStudio 1.4.1103

**Comment by GegznaV** [comment]
Still reproducible in RStudio 2021.9.2.382

**Comment by GegznaV** [comment]
Did you try leaving spaces on both sides of = during the testing?

**Comment by gtritchie** [comment]
I made fixes specifically dealing with spaces on either side of equals signs.
