### ISSUE TITLE
Encoding related problem in "Import Dataset → From Text (base)"

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#2674]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version :      Windows 10
    R Version :       3.4.4 (2018-03-15)

### Steps to reproduce the problem

1. Create a text file that contains at least one non-English letter ("ą", "ž", etc.) in the path name or file name, lile "c:/užduotis-1/iris.txt". This code does this in Windows (in Mac and Linux the line for setting the locale should be changed appropriately):

```r
Sys.setlocale(locale = "Lithuanian")
data("iris")
dir.create("c:/užduotis-1", recursive = TRUE)
write.csv(iris, file = "c:/užduotis-1/iris.txt")
```

2. Choose the method to import data: 
	* RStudio → window "Environment"  → button "Import Dataset" → From Text (base)
![image](https://user-images.githubusercontent.com/12725868/39062266-b6765624-44cf-11e8-8cf3-a8d5d39441d0.png)

3. Trying to open the file "c:/užduotis-1/iris.txt" results in an error which is not informative and does not suggest any solution:

![image](https://user-images.githubusercontent.com/12725868/39061476-15cc23ea-44cd-11e8-929e-0b6ada593dfd.png)

### Describe the problem in detail

1. Impossible to open import a dataset from a text file through "*Import Dataset" → From Text (base)*", if the pathname or the filename contains non-English letter(s).
2. The error message is uninformative.

Note: when "c:/užduotis-1/iris.txt" is changed into "c:/uzduotis-1/iris.txt" (i.e., "ž" →"z," the file import menu works as expected"). But sometimes it is not convenient to change the letters, e.g., when people have to create a separate Windows username.

### Describe the behavior you expected

1. It should be possible to use the window to import data even if non-English letters exist.
2. If (1) cannot be implemented, an informative error message is needed, which explains for beginner RStudio users how to solve the problem.

**Comment by ronblum** [comment]
See #2675. (I'm guessing it's the same underlying issue, but I'll leave these open as separate issues—not duplicate—because the front-end behavior is different enough.)

**Comment by GegznaV** [comment]
Unfortunately, the issue still persists.

**Comment by GegznaV** [comment]
#2675 seems to be a different issue.

**Comment by GegznaV** [comment]
Cannot reproduce in:

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2021.9.2.382
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.2 (2021-11-01)
