### ISSUE TITLE
Allow for `session-timeout-minutes` to simply exit without suspend

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#2680]
The `session-timeout-minutes` feature should allow for the user to specify whether or not they want to actually suspend the sessions to disk. It is a legitimate use case to want to simply gracefully exit the session process when it is truly idle (no user input and no running processes) without actually suspending to disk. This would be a lighter option than the `session-timeout-kill-hours` feature we have available in RStudio Server Pro.

**Comment by dfalty** [comment]
Verified functionality 1.2.1317-1
