### ISSUE TITLE
FR: Add configuration option to show hidden files

### ISSUE THREAD

**Issue by gwarnes-mdsol** [rstudio/rstudio#2681]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Mac OS X 10.12.6
    R Version       :  3.4.4

### Steps to reproduce the problem

I'm working on a project where it is necessary to edit files in a 'hidden' directory starting with a period (e.g. `.dirname/`). 

It would be very helpful to have an RStudio configuration option to allow hidden files and directories to be displayed in the file viewer.

For illustration.  Running the following R script in a completely new RStudio directory & project:
```
dir.create("foo")
dir.create(".foo")
dir.create(".1foo")
dir.create(".12foo")

cat("bar", file="bar")
cat(".bar", file=".bar")
cat(".1bar", file=".1bar")
cat(".12bar", file=".12bar")

cat("test", file=".gitignore")
cat("test", file=".gittest")
```

Only displays the `.gitignore` file in the the file viewer window:
![image](https://user-images.githubusercontent.com/22243578/39086669-41597a58-4563-11e8-9548-6ba38740149f.png)

Even though they are clearly present when `ls` is run in the `Terminal` tab:
```
user_name@HOST_NAME:~/Google Drive/src/InvisibleDirectoryTest$ ls -la
total 56
drwxr-xr-x  14 user_name  DOMAIN\Domain Users   476 Apr 21 12:43 ./
drwxr-xr-x  42 user_name  DOMAIN\Domain Users  1428 Apr 21 12:39 ../
-rw-r--r--   1 user_name  DOMAIN\Domain Users     6 Apr 21 12:41 .12bar
drwxr-xr-x   2 user_name  DOMAIN\Domain Users    68 Apr 21 12:40 .12foo/
-rw-r--r--   1 user_name  DOMAIN\Domain Users     5 Apr 21 12:41 .1bar
drwxr-xr-x   2 user_name  DOMAIN\Domain Users    68 Apr 21 12:40 .1foo/
drwxr-xr-x   4 user_name  DOMAIN\Domain Users   136 Apr 21 12:39 .Rproj.user/
-rw-r--r--   1 user_name  DOMAIN\Domain Users     4 Apr 21 12:41 .bar
drwxr-xr-x   2 user_name  DOMAIN\Domain Users    68 Apr 21 12:40 .foo/
-rw-r--r--   1 user_name  DOMAIN\Domain Users     4 Apr 21 12:42 .gitignore
-rw-r--r--   1 user_name  DOMAIN\Domain Users     4 Apr 21 12:43 .gittest
-rw-r--r--   1 user_name  DOMAIN\Domain Users   258 Apr 21 12:39 InvisibleDirectoryTest.Rproj
-rw-r--r--   1 user_name  DOMAIN\Domain Users     3 Apr 21 12:41 bar
drwxr-xr-x   2 user_name  DOMAIN\Domain Users    68 Apr 21 12:40 foo/
```

It looks specific file names and extensions are explicitly whitelisted in `src/cpp/session/SessionModuleContext.cpp:fileListingFilter`.   

It should be straightforward to allow this to be controlled by the user by add this as option to the either the project or global preferences pane, with a corresponding field in userSettings().

**Comment by gtritchie** [comment]
Good timing, this was just implemented by @jmcphers via #1769.
