### ISSUE TITLE
Quotations and brackets autofilling wrong in Rnotebooks when Source pane separated (Daily build)

### ISSUE THREAD

**Issue by rossholmberg** [rstudio/rstudio#2682]
See below for an explanation, but I think it's easiest to show this problem in a video. If you just want to see the problem itself, just watch 10secs or so starting at the 1 minute mark:
[https://vimeo.com/266046093](https://vimeo.com/266046093)

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.576 (Daily)
    OS Version      :  Ubuntu 16.04.1 (64-bit)
    R Version       :  3.4.4 (2018-03-15)

### Steps to reproduce the problem
Open up an Rnotebook (this doesn't seem to happen in other file types), then break out the Source pane using the "Show in new window" button. Quotations, brackets, etc. start being auto-filled improperly.

### Describe the problem in detail
When inputting, for example, a quotation mark '"', a second (closing) one is usually inserted automatically to the right of the cursor, such that text is then put in between the two. In a separated window though (Source pane detached from the main RStudio window using "Show in new window"), the behaviour changes, such that the second quotation mark is only entered after another character is typed, and it's entered to the left of the cursor, rather than the right. This means that text is entered OUTSIDE the quotations (In the case of brackets, you get 2 opening brackets and no closing brackets.

### Describe the behavior you expected
Expected behaviour is what happens before separating the source pane. The auto-filled quotation/bracket should be to the right of the cursor, such that text is entered inside.

**Comment by ronblum** [comment]
Confirmed:
1) This occurs also using other OS versions, such as MacOS Desktop 1.2.570-2.
2) This only happens with R Markdown but none of the other files (R, C++, etc.).
3) This is a regression—it's not an issue with 1.1.442.

**Comment by kevinushey** [comment]
Often, things like this imply a JavaScript exception is being thrown from within Ace routines -- is it possible anything is popping up there?

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be fixed in the next daily builds of RStudio (v1.2.640 and above).

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
