### ISSUE TITLE
How do I track IP Address from where a user logged in to their account from into RStudio Server?

### ISSUE THREAD

**Issue by nikolayvoronchikhin** [rstudio/rstudio#2689]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.414
    OS Version: Red Hat Enterprise Linux Server release 7.3 (Maipo)
    R Version:  Microsoft R Open 3.4.2

**Comment by jmcphers** [comment]
This issue tracker is for bugs, not questions; try the R Admins community forum:

https://community.rstudio.com/c/r-admin

Short answer: You can do this with RStudio Server Pro (it has auditing built in), or with a PAM module. Hope you're able to find what you need!

**Comment by jmcphers** [comment]
You can get IP addresses with the `server-access-log` setting.

http://docs.rstudio.com/ide/server-pro/authenticating-users.html#proxied-authentication

Does that do what you want?

**Comment by nikolayvoronchikhin** [comment]
Yes, that works. Thanks!
