### ISSUE TITLE
RNotebook - Multi-statement python chunk output printed twice

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2690]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.576
    OS Version      : Mac OS 10.12.6

### Steps to reproduce the problem
1. Create the following python chunk in a Rmd file.
```{python}
print("123"); print("456")
```
2. Run the chunk and knit
3. Observe the output is printed twice

### Describe the problem in detail
![image](https://user-images.githubusercontent.com/15237845/39181542-9c75b334-477f-11e8-808c-f64ab5ce7b32.png)

### Describe the behavior you expected
Output to not be repeated.

**Comment by kevinushey** [comment]
This one is an issue in the `reticulate` package itself; I've pushed a fix here: https://github.com/rstudio/reticulate/commit/1f66d0905185bc3c19ca420d68498a8d01398366

Can you try testing again with the development version of `reticulate`?

```
devtools::install_github("rstudio/reticulate")
```

**Comment by ronblum** [comment]
This works with the latest production version of `reticulate` (1.10). Verified on MacOS and Windows both with running chunk and knitting to HTML.
