### ISSUE TITLE
shinytest integration - Consider saving file when selecting Run Tests

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2691]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.2.576
    OS Version      : Mac OSX 10.12.6

### Steps to reproduce the problem
1. Open shinytest R file
2. Make changes to the file but don't save
3. Click Run Tests
4. Observe file is not saved automatically like Knit or Run App

### Describe the problem in detail
![image](https://user-images.githubusercontent.com/15237845/39199567-65629dfa-47af-11e8-9df5-9ea1baab82bf.png)

### Describe the behavior you expected
When Run Tests is selected, the file is saved before running the tests

**Comment by jjallaire** [comment]
Yes, this is a P0 but as this is how all of our other run/execute commands work. @javierluraschi this is as simple as wrapping the command invocation in `saveThenExecute()`, e.g. see https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L5327-L5333
