### ISSUE TITLE
Hidden(/unintentional?) requirement for OSX 10.12 on mac (allowsAutomaticWindowTabbing)

### ISSUE THREAD

**Issue by gmbecker** [rstudio/rstudio#2693]
### System details

    RStudio Edition : Desktop Version
    RStudio Version : Trunk (commit be5b1f540dad2082b67fc855475432eb5efb7263)
    OS Version      :  OSX 10.11.6 El Capitan
    R Version       : 3.4.4 Patched

### Steps to reproduce the problem

Attempt to build the RStudio from source in the described environment

### Describe the problem in detail
Build from source fails with the error: 
```
<path-to-checkout>/src/cpp/desktop/DesktopUtilsMac.mm:54:16: error: property 'allowsAutomaticWindowTabbing' not found on object of type 'NSWindow'
      NSWindow.allowsAutomaticWindowTabbing = NO;

```
Investigation confirms that the Apple Documentation indicates this property was introduced in 10.12: https://developer.apple.com/documentation/appkit/nswindow/1646657-allowsautomaticwindowtabbing

### Describe the behavior you expected
Successful build from source without errors on OSX 10.11.6.

**Comment by mingwandroid** [comment]
`AD` 'fix' for this:

https://github.com/AnacondaRecipes/aggregateR/blob/master/rstudio-feedstock/recipe/0030-macOS-Fix-builds-on-macOSX-SDK-10.12.patch

**Comment by mingwandroid** [comment]
This fix may allow this to still do what it's supposed to on macOS > 10.12:

https://github.com/mpv-player/mpv/commit/3e2228b2a65b7e4c97ad23d73fdcb32400348e74

I'm not very familiar with Objective C++ though!

**Comment by gtritchie** [comment]
@mingwandroid Thanks! Yes, I need to do as you indicated (the patch with the #ifdef wrapper).

**Comment by mingwandroid** [comment]
I believe the mpv-player patch will allow this stuff to `allowsAutomaticWindowTabbing` enablement/disablement to work for people who use macOS 10.12 while not preventing users of <10.12 from running RStudio, so I *think* it's the better option here to be honest with you.

**Comment by gtritchie** [comment]
The problematic code in question may no longer be necessary at all, but I haven't yet done the experiment to confirm that. Otherwise, I understand what you're saying about the second approach and will look into that.

**Comment by gtritchie** [comment]
Also, just to be sure, is this OneDrive (consumer) we are talking about? The one that ships with Windows-10? Or is it OneDrive for Business (which is really SharePoint)?
