### ISSUE TITLE
File pane does not show correct default working directory set in RProfile.site

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2697]
### System details

    RStudio Edition : Server and Desktop
    RStudio Version : 1.2.589
    OS Version      : Ubuntu 16 desktop and server
    R Version       : 3.2.3

### Steps to reproduce the problem
1) Edit/create **Rprofile.site** (location varies, usually /usr/lib64/R/etc/ or /usr/lib/R/etc) and add the following:
```
HomeDir <- "/apps/rhome"
u <- Sys.getenv("USER")
dir.create(file.path(HomeDir, u), showWarnings = FALSE)
secureMe <- paste("chmod ", "700", " ", HomeDir, "/", u, sep = "")
system(secureMe)
setwd(paste(HomeDir, u, sep ="/"))
```
2) Manually create /apps/rhome, make sure permissions are such that RStudio can create folders here.

3) Start RStudio without a project

### Describe the problem in detail
The File pane does not reflect the current working directory as seen in the Console toolbar (and via `getwd()`)

### Describe the behavior you expected
File pane defaults to current working directory when no project is loaded

Note, slightly different behavior in RStudio Pro, see issue 436 in that repo.

**Comment by EmilBode** [comment]
I've just filed another issue (#3027), where RStudio finds .Rprofile in the wrong directory when not working in a project.
Could this be related?
