### ISSUE TITLE
Cannot zoom plots

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2699]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.588+ (problem started with this build, worked before this)
    OS Version      : 10.13.4
    R Version       : 3.4.3

### Steps to reproduce the problem
- Launch RStudio  on Mac, and generate a plot via `plot(1)`.
- Click on Zoom button in plots pane.

### Describe the problem in detail
The plots window opens like this:
![2018-04-24_21-06-25](https://user-images.githubusercontent.com/10569626/39225860-b6271db6-4803-11e8-8fea-2abca92c34d8.png)

### Describe the behavior you expected
Expect to see the plot. I confirmed that it was working in 1.2.587 and several builds before that, but broken in 1.2.588 and all subsequent builds. Only tried on Mac.

**Comment by jmcphers** [comment]
I'm guessing I broke this with 
 https://github.com/rstudio/rstudio/commit/77231f3199993716517e83e5c8eaff78cb7ae6ec; I'll take a look. That change causes us to be much more cautious about emitting the `X-Shared-Secret` header, it could be that the header isn't getting set for this pane for some reason.

**Comment by ronblum** [comment]
Verified with Desktop on Windows 10 and MacOS 10.14 Mojave and Server on Ubuntu 16.05.4 with Chrome 68.
