### ISSUE TITLE
Problem on clicking on 'Knit to PDF' : won't work

### ISSUE THREAD

**Issue by gmeurice** [rstudio/rstudio#2700]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version      : OSX High Sierra 10.13.1
    R Version       : 3.5.0

### Steps to reproduce the problem

click on "Knit to PDF"

### Describe the problem in detail

I want to knit to PDF an Rmarkdown document.
it works using the 'render' function from the console :

`render("TP_DIU_MMO_2018.Rmd")
/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS TP_DIU_MMO_2018.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output TP_DIU_MMO_2018.tex --template /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' 
You are recommended to install the tinytex package to build PDF.FALSE
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.`

while clicking on 'Knit to PDF', or the shift+cmd + K give an error :

`/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS TP_DIU_MMO_2018.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output TP_DIU_MMO_2018.tex --template /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' 
output file: TP_DIU_MMO_2018.knit.md

You are recommended to install the tinytex package to build PDF.FALSE
sh: pdflatex: command not found
Error: Failed to compile TP_DIU_MMO_2018.tex.
In addition: Warning messages:
1: In system2(..., stdout = FALSE, stderr = FALSE) :
  error in running command
2: In system2(...) : error in running command
Execution halted`

### Describe the behavior you expected

1. The output of sessionInfo() 

`> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_1.9

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.0     yaml_2.1.18     Rcpp_0.12.16    stringi_1.1.7  
[10] knitr_1.20      stringr_1.3.0   digest_0.6.15   evaluate_0.10.1
`

**Comment by yihui** [comment]
You need to install LaTeX. Try TinyTeX if you have not used LaTeX before: https://bookdown.org/yihui/rmarkdown/installation.html
