### ISSUE TITLE
Double-Click Word Highlighting Fails in Dark Themes

### ISSUE THREAD

**Issue by GrimTrigger88** [rstudio/rstudio#2702]
I just did a fresh install of RStudio Desktop (4/25/2018), and I'm a big fan of the Material Editor Theme. However, I'm also a fan of the double-click word highlighting feature, which doesn't work in the theme.

It would be awesome to get this working.

Pictures of the glitch and RStudio Info:

![lightthemeworks](https://user-images.githubusercontent.com/20579293/39258022-eb8b3e92-4880-11e8-88ed-5cdcf2fc53af.PNG)
![darkthemefails](https://user-images.githubusercontent.com/20579293/39258026-ee795dfa-4880-11e8-9bdf-a28c030d4bd7.PNG)
![rstudio info](https://user-images.githubusercontent.com/20579293/39258031-f0cf0078-4880-11e8-9168-ee7a0f7ce178.PNG)

**Comment by dfalty** [comment]
I'm also able to reproduce this on the latest daily build 1.2.594.

**Comment by hermidalc** [comment]
I'm able to reproduce this in latest version 1.2.1335

**Comment by tungmilan** [comment]
Happens to me on Windows 10 too. Double click on word in the Console did nothing

RStudio Desktop: 1.2.1511

Theme: [Night Owl by @batpigandme](https://github.com/batpigandme/night-owlish)

**Comment by markschat** [comment]
For posterity:
Word highlighting can be achieved by editing/ adding this lines in your theme-file (e.g. my_theme.rstheme):
```
.ace_marker-layer .ace_selected-word {
  background: #3D4350;
  border: 1px solid #3D4350;
}
```
This adds a background color and border to the highlighted words:

![image](https://user-images.githubusercontent.com/43857618/159703956-5eb10f6e-6b8a-47dd-a75c-9a977baaffbe.png)
