### ISSUE TITLE
New Rstudio build error:  ‘isPausedChanged’ is not a member of ‘QWebEngineDownloadItem’

### ISSUE THREAD

**Issue by ppaschos** [rstudio/rstudio#2703]
During the build from source for version 1.1.447 we receive the following error:

Scanning dependencies of target rstudio
[ 47%] Building CXX object src/cpp/desktop/CMakeFiles/rstudio.dir/DesktopActivationOverlay.cpp.o
[ 47%] Building CXX object src/cpp/desktop/CMakeFiles/rstudio.dir/DesktopBrowserWindow.cpp.o
[ 48%] Building CXX object src/cpp/desktop/CMakeFiles/rstudio.dir/DesktopDownloadItemHelper.cpp.o
/software/sources/builds/rstudio/src/cpp/desktop/DesktopDownloadItemHelper.cpp: In constructor ‘rstudio::desktop::DownloadHelper::DownloadHelper(QWebEngineDownloadItem*)’:
/software/sources/builds/rstudio/src/cpp/desktop/DesktopDownloadItemHelper.cpp:41:19: error: ‘isPausedChanged’ is not a member of ‘QWebEngineDownloadItem’
    connect(item, &QWebEngineDownloadItem::isPausedChanged,
                   ^
make[2]: *** [src/cpp/desktop/CMakeFiles/rstudio.dir/DesktopDownloadItemHelper.cpp.o] Error 1
make[1]: *** [src/cpp/desktop/CMakeFiles/rstudio.dir/all] Error 2
make: *** [all] Error 2

We did not install the qt-sdk in the dependencies. We have a separate installation of qt ver 5.9.1 provided as a module. Any insight on this, please let me know. 

Thank you

**Comment by dimitry-ishenko** [comment]
According to https://doc.qt.io/qt-5.10/qwebenginedownloaditem.html#isPausedChanged:

> This function was introduced in Qt 5.10.

**Comment by ppaschos** [comment]
I ended up installing Qt 5.10.1 as a module in our cluster and this is now addressed.
