### ISSUE TITLE
Studio does not start on Ubuntu 16.04

### ISSUE THREAD

**Issue by hvb4096** [rstudio/rstudio#2704]
### System details

    RStudio Edition :  Desktop
    RStudio Version : rstudio-1.0.44-amd64.deb
    OS Version      : Ubuntu 16.04
    R Version       : 3.2.3 "Wooden Christmas Tree"

### Steps to reproduce the problem
sudo rstudio
### Describe the problem in detail
RStudio IDE is not launching please kindly peruse the attached terminal screenshot.
### Describe the behavior you expected
RStudio IDE would launch successfully

**Comment by ronblum** [comment]
@hvb4096 Have you tried downloading the current version of RStudio, 1.1.447? It's available at https://www.rstudio.com/products/rstudio/download/

**Comment by hvb4096** [comment]
@ronblum After I read your response, I downloaded the Ubuntu 16.04/Debian 9.x .deb package and installed it. Now RStudio IDE is launching and disappearing from screen as soon as I point my mouse to any GUI components. I am running a virtual linux desktop (Ubuntu 16.04) though AWS/EC2 so rebooting the virtual desktop to see if anything improves.
Will keep you posted.

**Comment by hvb4096** [comment]
@ronblum I rebooted my virtual linux desktop but same behavior continues. RStudio IDE is launching but disappearing from screen (RStudio IDE crashes)  as soon as I point my mouse to any GUI components. For example if I hover or click my mouse around top menu bar <File, Edit, Code etc> or anywhere on the IDE - it crashes abruptly.  Essentially not being able to consume RStudio post install.

**Comment by hvb4096** [comment]
This time I launched it from a terminal window to see some log re: launch. Here is what the term is displayed.
dauser@ip-172-31-18-202:~$ sudo rstudio
[sudo] password for dauser: 
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
Unsupported screen format: depth: 24, red_mask: ff, blue_mask: ff0000
Using RGB32 fallback, if this works your X11 server is reporting a bad screen format.
Unsupported screen format: depth: 24, red_mask: ff, blue_mask: ff0000
Using RGB32 fallback, if this works your X11 server is reporting a bad screen format.
Unsupported screen format: depth: 24, red_mask: ff, blue_mask: ff0000
Using RGB32 fallback, if this works your X11 server is reporting a bad screen format.
load glyph failed err=6 face=0x25a61d0, glyph=2797
load glyph failed err=6 face=0x25a61d0, glyph=2797
qt_xcb_createCursorXRender: query_pict_formats failed
Segmentation fault (core dumped)
dauser@ip-172-31-18-202:~$

**Comment by hvb4096** [comment]
I found a thread that covers although not sure what I can try to solve my issue 
https://github.com/spyder-ide/spyder/issues/3713

**Comment by hvb4096** [comment]
Ok. I tried launching the virtual linux desktop (Ubuntu 16.04) from Windows 10 and OS X El Capitan to see if there was any OS specific issue for input/output. No difference across OS or hardware. RStudio crashes right after launch within 5 seconds. We can rule out any causation to my mouse hover/click movements. Even without doing anything RStudio crashes with the above errors.
I was able to reproduce this issue in both Windows and OS X instances.  Running Windows 10 from a Lenovo and  OS X from a Macbook air.

**Comment by hvb4096** [comment]
Switched to Windows virtual desktop. Sorry Linux.

**Comment by LeZhengThu** [comment]
Hello, I'm facing the same issue. Did you find a solution?

**Comment by jmcphers** [comment]
This is caused in part by trying to run RStudio using "sudo" (it should be run using the same user account as the X windows environment). We've also made some significant improvements to Qt and our rendering canvas in 1.2 which should resolve this; feel free to reopen if you're still seeing it with RStudio >= 1.2.5019.
