### ISSUE TITLE
Problem with RStudio installation with Mac OS Sierra

### ISSUE THREAD

**Issue by dacoba2005** [rstudio/rstudio#2706]
### System details

    RStudio Edition : 
    RStudio Version : Version 1.1.447 
    OS Version      : Mac OS Sierra 10.12.6
    R Version       : R version 3.4.4 (2018-03-15)

### Steps to reproduce the problem
1 - I installed last version of R in MAC
2 - I installed last version of RStudio in MAC

However, I can't find RStudio in LaunchPad neither in Application folder after restarting the laptop

It seems that RStudio is installed and configured as Image or Device (as a USB Device or any other external hardware) rather than a Software Application in the Mac OS

Furthermore, after restarting the computer I have to download again the installation file and once I open it is activated again as new Device and I can use RStudio, although I guess it should be a direct way to access it

### Describe the behavior you expected

What I would expect it would be to find RStudio as the rest of application in the MAC, and not as Device/Image (as a new hardware or USB device)

<img width="1440" alt="screen shot 2018-04-26 at 09 28 29" src="https://user-images.githubusercontent.com/38748507/39291745-4d9ab136-4934-11e8-9399-96af59bb1ddf.png">

**Comment by ronblum** [comment]
@dacoba2005 After open the DMG file, did you copy RStudio to the Applications folder?

**Comment by dacoba2005** [comment]
Hi Ron

Thanks for your quick response. That was the problem. I didn't know that I have to copy on Application folders. Sorry, I am quite new in MacOS.

By doing that the problem is solved. Thanks a lot
