### ISSUE TITLE
Ability to paste into Save As dialog

### ISSUE THREAD

**Issue by miguelmorin** [rstudio/rstudio#2707]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : 10.13.3 (17D102)
    R Version       : 3.4.4 (2018-03-15)

### Steps to reproduce the problem

I often refactor code into functions, one in each file, with the same name to navigate easily. I cut a piece of code from one file, start a new file (Cmd-Shift-N), paste the code, then copy the function name, and save. A dialog opens (it looks like it's from the OS) and I would like to paste the name of the function, but I cannot. Instead, I save as the default "Untitled.R", close the file, then go to Finder and edit the file's name there.

### Describe the problem in detail

See above.

### Describe the behavior you expected

I expected to be able to copy into the OS dialog box, as I can with other applications, for example TextEdit.

This is a enhancement request and I could not find how to add that label.

Output of `sessionInfo()`:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4   
```

**Comment by ronblum** [comment]
Thanks for reporting this, @miguelmorin. We'll review this as we work on future development of RStudio.

**Comment by jmcphers** [comment]
Possibly applicable:

> Other standard menu items such as Cut, Copy, Paste and Select All are applicable both in your application and in some native dialogs such as QFileDialog. It's important that you create these menu items with the standard shortcuts so that the corresponding editing features will be enabled in the dialogs. At this time there are no MenuRole identifiers for them, but they will be auto-detected just like the application menu items when the QAction has the default TextHeuristicRole.

http://doc.qt.io/qt-5/osx-issues.html
