### ISSUE TITLE
Actions selected in message boxes are ignored

### ISSUE THREAD

**Issue by datamole** [rstudio/rstudio#2708]
This error persists for ages now - on every version of rstudio I compiled from sources in the last year: Message boxes asking the user for confirmation are not working.

Example:
When I close rstudio with some changes to a file not yet stored the message box asking to "store", "not store" or "cancel" isn't working. Only "cancel" works as expected, "store" or "not store" do the same as cancel.

The same behavior is encountered with all message boxes pretty much, so also for example when I am asked if I really want to clear my plots in the graph area.

Due to this error I can often only close rstudio by typing in q() on the command line because the message box is cancelling the action no matter what I choose.

I am compiling rstudio using QT 5.10 and boost version 66 on opensuse tumbleweed, but the error also occurs using the bundled versions of QT and boost installed via the dependenciy scripts.

**Comment by jmcphers** [comment]
Sorry, we've had no other reports of this in well over a year and can't offer support for unofficial builds.
