### ISSUE TITLE
(Linux) Resizing column in view mode resets when cursor moves outside name box

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#2709]
In the linux version (debian, using KDE), when examining data in View mode (e.g. `View(df)`), if the first column is of character type, when one tries to resize the width of some column but drags the mouse outside of the space box in which the name of the column appears, the size resets to where it was before dragging it.

Steps to reproduce:
-Create an R object having the first column being of character type
-Show the object in view mode (e.g. `View(data.frame(col1=rep('this is a long text here', 100), col2=rnorm(100)))`)
-Try to resize the first column
-While dragging it (to resize), drop the mouse above or below the space in which the column title appears

Reproducible: always

![resizing_problem](https://user-images.githubusercontent.com/11860098/39321176-970e6d74-4986-11e8-8aa9-b4fe6b038bf3.png)

**Comment by dfalty** [comment]
I can reproduce this as well on Mac Desktop build 1.2.594. Thanks for the report!

**Comment by jmcphers** [comment]
This is totally fixed.

**Comment by david-cortes** [comment]
Still reproducible in 1.3.938.

**Comment by kevinushey** [comment]
I believe this is only fixed in the v1.4 [daily builds](https://dailies.rstudio.com).
