### ISSUE TITLE
(Linux) Invisible underscores in console

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#2710]
In the linux version (debian, using KDE), when typing something with an underscore in the console, the underscore is invisible. Underscores are still visible in the editor and in the console output though.

Steps to reproduce:
-Set a dark theme in RStudio (e.g. Tools -> Global Options -> Appearance -> Clouds Midnight).
-Type something in the console line containing an underscore ("_").
Reproducible: always
![underscore1](https://user-images.githubusercontent.com/11860098/39321550-a264825c-4987-11e8-8ebf-3aa7e5f0d418.png)
![underscore2](https://user-images.githubusercontent.com/11860098/39321559-a5a8e570-4987-11e8-8b8e-bb68fae0dbac.png)

**Comment by tungmilan** [comment]
This is the problem on Windows 10 as well (Theme: Sky, Font: DejaVu Sans Mono, Editor theme: Cobalt)

In this example, the underscore didn't show up while typing. After press Enter, it appeared. However, it was gone again when retrieving `par_1` value

![capture](https://user-images.githubusercontent.com/6590141/40555306-7e6abd08-5ffd-11e8-855f-4d87dc9b6c1d.PNG)


    RStudio Edition : Desktop 
    RStudio Version : 1.2.637
    OS Version      : Windows >= 8 x64 (build 9200)
    R Version       : 3.5.0 (2018-04-23)

**Comment by tungmilan** [comment]
Problem still there on v1.2.666

**Comment by tungmilan** [comment]
@kevinushey : the issue goes away if I use different font. So it was the DejaVu Sans Mono font that caused the trouble

**Comment by david-cortes** [comment]
Can confirm also that changing from the DejaVu Sans Mono font that comes by default makes those underscores visible.

**Comment by david-cortes** [comment]
The problem seems to be gone in the preview version 1.2.747.

**Comment by tungmilan** [comment]
Still there in 1.2.768. I think it's the font that caused the problem

**Comment by david-cortes** [comment]
Another update: the underscores are also invisible in the editor's search bar, even when they are visible in the console.

**Comment by jmcphers** [comment]
Looks like this was just a problem with the font (and we haven't had other reports in well over a year), so closing.

**Comment by SimonDedman** [comment]
Any chance this could be reopened and reviewed? I'm using Fira Code font which works fine otherwise, no problems with underscores in the console, but they're invisible in the search bar. I can open a new bug if this is unrelated.

![image](https://github.com/rstudio/rstudio/assets/4599748/86737071-fad6-463d-a71d-409bada67644)

This says "df_i df i". The horizontal extent of an underscore is wider than a spacebar it seems.

Thanks
