### ISSUE TITLE
Tab completion on list of lists doesn't properly work when names are in non-Latin alphabet

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#2711]
Hello,

Please find below the description of an issue regarding the access of different levels of a list of lists using the tab completion. Example provided creates two lists, one (`L.EN`) with names written in Latin alphabet and one (`L.JP`) with names written in non-Latin alphabet (Japanese).

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Ubuntu 16.04.4 LTS
    R Version       : 3.4.4

### Creating list of lists with names in Latin alphabet
    M.EN <- matrix(1:3, 1, 3)
    D.EN <- setNames(as.data.frame(M.EN), letters[1:3])
    L.EN <- setNames(rep(apply(D.EN, 1, function(x) as.list(D.EN)), 5), LETTERS[1:5])

    ### Creating list of lists with names in non-Latin alphabet
    M.JP <- matrix(1:3, 1, 3)
    D.JP <- setNames(as.data.frame(M.JP), c("一号", "二号", "三号"))
    L.JP <- setNames(rep(apply(D.JP, 1, function(x) as.list(D.JP)), 5), c("一番", "二番", "三番", "四番", "五番"))

### Describe the problem in detail

When running `R` on any system Terminal (), it is possible to access any level of the list simply using the tab completion, i.e.

    R> L.EN$
    L.EN$A  L.EN$B  L.EN$C  L.EN$D  L.EN$E  
    R> L.EN$A$
    L.EN$A$a  L.EN$A$b  L.EN$A$c  
    R> L.EN$A$a
    [1] 1
    R>
    R> L.JP$
    L.JP$一番  L.JP$二番  L.JP$三番  L.JP$四番  L.JP$五番  
    R> L.JP$一番$
    L.JP$一番$一号  L.JP$一番$二号  L.JP$一番$三号  
    R> L.JP$一番$一号
    [1] 1

When running on `RStudio`, the tab completion in Console is working as expected on Latin alphabet, i.e.

    L.EN$A$a
    [1] 1

But fails to reach the second level, as the tab completion returns `(No matches)`, i.e.

    L.JP$一番$ (No matches)

### Describe the behavior you expected

It is expected the tab completion in `RStudio` to work the same way it is working in `R` running on terminal.

**Comment by ronblum** [comment]
@pascaloettli Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

Reproduced in RStudio MacOS Desktop 1.2.583-1.

**Comment by ronblum** [comment]
There is a difference in R: the completion occurs in the R terminal on Ubuntu and MacOS. However, it does not occur on the MacOS R Console app—the behavior is the same as in RStudio.

**Comment by pascaloettli** [comment]
@ronblum  Right, it does not occur on MacOS, with `Terminal` (v 2.8.2) and `iTerm2` (3.1.6). And it also does not occur on `Rgui 64-bit` (3.5.0) running on Windows XP Pro. So the behavior on Unix-alikes (except MacOS) is an exception. And likely related to `readline`?
