### ISSUE TITLE
script file is not saved, "invalid argument" pop-up appears.

### ISSUE THREAD

**Issue by balwierz** [rstudio/rstudio#2717]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.446 (it was true with previous versions as well)
    OS Version      :  Debian Buster (where Rstudio runs), Arch Linux (where X11 is displayed)
    R Version       :  3.4.4

### Steps to reproduce the problem
** This problem never occurs immediately. Usually after some hours of working in Rstudio. But I observed it long time ago and many versions ago already.

Upon resaving a file (R script) a popup window appears: "Invalid argument".
The file is NOT saved. "Save as..." does not work either.

### Describe the problem in detail
The console output is:
"5: Error occurred while executing method
22: [system] Invalid argument"

I can create new files and save them in the same directory without problems.
I always work over X11 connection (from Arch Linux). My colleagues work over X11 (on the same machine) from Mac OS and none of them encounters this problem. But it seems unlikely it has anything to do with the X11 display.

When the problem occurs I have to copy-paste the script content to another editor to save the changes.
Then I restart Rstudio and can work some minutes or some hours before the problem reappears.

### Describe the behavior you expected
File is saved.

**Comment by albhasan** [comment]
I have the same problem here:

Ubuntu 18.04.1 LTS
R version 3.5.1 (2018-07-02)
Rstudio (desktop) Version 1.1.463 

I'm working on files over a sshfs  connection, but I'm the only user of those files.

**Comment by ronblum** [comment]
@balwierz Is this problem still occurring? If so, do you see the issue on a stable version of Debian as well? And are you able to try out the 1.2 preview at https://www.rstudio.com/products/rstudio/download/preview/ and see if the problem reproduces or is resolved with it?

**Comment by balwierz** [comment]
@ronblum I am running version 1.2.1099 now. The problem still occurs, but nowhere as often as previously. Once for a couple of weeks of work.

It came to my mind that I might have something to do with filesystem being an NFS.

**Comment by munrosa** [comment]
I'm having a similar problem. I'm using Google Drive File Stream to access my files, so perhaps that the trigger. I'm still on 1.1.463.

**Comment by xgirouxb** [comment]
I'm currently experiencing the exact same issue, only happens after a few hours with project open. I wiped everything R from my system and reinstalled from scratch, yet the issue persists under the following environment:

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.2
Rstudio (desktop): Version 1.2.5033

I'm also using a cloud service to sync the project's folder, but I've been doing this for years and I'm only experiencing this issue now.
