### ISSUE TITLE
Lists not refreshed when using `View()`

### ISSUE THREAD

**Issue by WillemSleegers** [rstudio/rstudio#2721]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      :  10.13.4 (17E199)
    R Version       : 3.4.4

### Steps to reproduce the problem

```
list <- list(1)
View(list)
list <- list(1, 2)
View(list) # This should show the updated list, but will show the old one.
```

### Describe the problem in detail

When a list is viewed with View(), then changes values, the view will not be refreshed when calling View() again.

### Describe the behavior you expected

I expected the list to be (automatically) refreshed, showing the new values in the list when calling View().

**Comment by dfalty** [comment]
I can reproduce this on the latest daily 1.2.611. Thanks for the report!

**Comment by WillemSleegers** [comment]
I just tested it in RStudio Version 1.4.1103 and it looks like it is fixed now.
