### ISSUE TITLE
Rstudio server issue with graphics device

### ISSUE THREAD

**Issue by ppaschos** [rstudio/rstudio#2723]
Hi all,

Your feedback is appreciated in the following issue we are having:
We upgraded to rstudio server 1.1.447 using the rpms for RedHat7 and we are getting this error: 

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> housing <- read.csv("Rgraphics/dataSets/landdata-states.csv")
> hist(housing$Home.Value)
Error in RStudioGD() : 
  Shadow graphics device error: r error 4 (R code execution error)
In addition: Warning message:
In grDevices:::png("/tmp/RtmpS6tUTP/ddcf62453f3b44218972bae78a757b00.png",  :
  unable to open connection to X11 display ''
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE       FALSE        TRUE        TRUE        TRUE 

If we call R (3.4.4) in the command line on the server itself or load the rstudio-desktop:
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE       FALSE        TRUE        TRUE        TRUE

**Comment by dfalty** [comment]
I'm not able to reproduce this. Just to make sure, can you verify you are loading running the exact same R installation even if they are the same version within RStudio vs R from the command line? You said this happen after an upgrade from RStudio. Does this work in a previous version? Thanks for the info!
