### ISSUE TITLE
R Markdown: Insert Bash does not show up on Windows 10

### ISSUE THREAD

**Issue by MichaelBeyeler** [rstudio/rstudio#2727]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Windows 10 64bit, April 2018 Update
    R Version       :  3.4.3 (Microsoft R Open, but that shouldn't matter)

As can be seen here: http://genviz.org/module%202/0002/03/01/introToRmarkdown/

RStudio on Mac has the option to create bash chunks. RStudio on Windows 10 does not have this option, even though I have WSL installed. Maybe this is related to my issue of not being able to run bash chunks: https://github.com/rstudio/rstudio/issues/2724

Is this a known issue, and is there a fix?

**Comment by Michael-Beyeler** [comment]
Sorry for being annoying, but does the closing of this issue mean that this is supposed to be working now?

I just updated my RStudio, and still no Bash button showing up.

**Comment by kevinushey** [comment]
We generally close issues when the fix appears within a daily build, which are published at https://dailies.rstudio.com.

**Comment by ronblum** [comment]
Verified on Windows 10.
