### ISSUE TITLE
Multi-letter remap of Esc key with Vim keybindings

### ISSUE THREAD

**Issue by calebbraun** [rstudio/rstudio#2728]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Windows 7 64-bit
    R Version       : 3.4.4

Using the Vim keybindings, there's the nice feature of being able to remap `Esc` to `jk` by doing `:imap jk <Esc>`. The problem I'm having is that with this remap, macros and other command using insert history add an extra `j`.

For example, typing `iRStudiojk` gives the following as expected:

    RStudio

If I move down a line and press `.` (repeat last change), the editor now looks like this:

    RStudio
    RStudioj

Note the extra `j`. This also occurs when replaying macros. The expected behavior would be for the editor to remove the `j` from the working history as soon as it is followed by a `k`.

**Comment by dfalty** [comment]
I can reproduce this on the latest daily build as well 1.2.604. Thanks for the report!

**Comment by brandones** [comment]
Sorry, I know this is not helpful but -- how did you configure remaps in RStudio's vim? I can't find any sort of documentation about vimrc support, other than an old post saying that it doesn't exist.

**Comment by calebbraun** [comment]
As far as I found, you can't use a vimrc, but you can configure remaps for each session using [keymapping commands](http://vim.wikia.com/wiki/Mapping_keys_in_Vim_-_Tutorial_(Part_1)).

**Comment by gtritchie** [comment]
This is fixed in latest RStudio 1.3 builds, presumably via the Ace update we took.
