### ISSUE TITLE
Vim mode treats international characters as word boundaries

### ISSUE THREAD

**Issue by torfason** [rstudio/rstudio#2730]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.442
    OS Version      : OSX
    R Version       : 3.4.4

### Steps to reproduce the problem

  * Create new source file (*.R)
  * Type out a word containing international characters (for example, "Encyclopædia Britannica")
  * Go to the start of the word and enter a command that is "word-aware", such as 'w', 'vw' or 'dw' (fo

### Expected behavior

When typing 'dw' the whole word should be deleted, only "Britannica" should remain

### Actual behavior

When typing 'dw', only "Encyclop" is deleted, but "ædia Britannica" remains

### Notes

The incorrect behavior occurs regardless of whether the source file is new or if it has already been saved in UTF-8 encoding. I did not check other encodings.

**Comment by kevinushey** [comment]
This will likely be resolved when we next update Ace.

**Comment by torfason** [comment]
When I saw this being marked as stale, I thought that this had not bothered me in a while, so I decided to test (with the reproducible example and some others), and confirmed that the issue seems to be resolved :-)

So it can be marked as closed instead of stale.
