### ISSUE TITLE
Pane layout changes are not occuring

### ISSUE THREAD

**Issue by imanuelcostigan** [rstudio/rstudio#2731]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : 1.2.604
    OS Version      :  Windows 7
    R Version       :  3.5.0

### Steps to reproduce the problem

- Tools > Global Options > Pane Layout
- Change right quadrant to display Console
- Click Apply and see "Saving" dialog that doesn't go away
- Click OK button but not pane layout changes are made

### Describe the problem in detail

See above. I have removed the `%LOCALAPPDATA%\RStudio-Desktop` folder but this has not resolved the issue.

### Describe the behavior you expected

Pane layout changes per request

**Comment by jjallaire** [comment]
@jmcphers I am seeing this as well. My guess is that it's related to the new tab you just put in. Definitely need to fix this one before Preview.

**Comment by dfalty** [comment]
I'm also able to reproduce this on Mac with the latest version 1.2.607. I agree we want to fix this before promoting the preview.

**Comment by dfalty** [comment]
Verified fixed 1.2.611.
