### ISSUE TITLE
ggsave() does not work when called from mclapply() in RStudio (fine from command line)

### ISSUE THREAD

**Issue by JDMcIninch** [rstudio/rstudio#2732]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.419
    OS Version      : Darwin farmac.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
    R Version       : 3.4.4 (2018-03-15) -- "Someone to Lean On"

### Steps to reproduce the problem

The following code will not run in RStudio but works fine in R (command line), RShiny (outside of RStudio), etc.. Simply run the script from within RStudio, then in R from the command line.

```r
library(ggplot2)
library(parallel)

mclapply(
    0:4,
    function(n) {
        df <- data.frame(x = runif(10), y = runif(10))
        p  <- ggplot(df, aes(x, y)) + geom_point()

        ggsave(
            paste0('mclapply-', n, '.png'),
            plot   = p,
            device = 'png',
            width  = 4,
            height = 4
        )

        return(n)
    }
)
```
### Describe the problem in detail

The script should produce 5 plots in parallel processes using the parallel library and ggplot2 library, but if executed in the R Studio environment, the R session either hangs or mclapply returns all nulls without creating the PNG files containing plots. This is very problematic in that it is therefore impossible to create or use a library that generates plots in parallel.

### Describe the behavior you expected

The code snippet above should fork several processes to create the 5 plots, write the plot to disk as a PNG file, and return the integer value of the index value (0-4). This is the behavior observed when the code is run in an R session at the command line.

In RStudio, the behavior is much different. Sometimes the session freezes, and sometimes the code runs. If the code runs, no PNG files are created, and NULL values are returned instead of the job index values. This suggests that ggsave() fails and the function passed to mclapply() exits prematurely, however, there are no warnings or errors to suggest a cause. I suspect that RStudio is doing something improper regarding graphics contexts or something similar, but I can't pin down the cause.

The same behavior is seen if you use png()/dev.off() instead of ggsave().

1. The output of sessionInfo()

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] ggplot2_2.2.1

loaded via a namespace (and not attached):
 [1] colorspace_1.3-2 scales_0.5.0     compiler_3.4.4   lazyeval_0.2.1
 [5] plyr_1.8.4       pillar_1.2.1     gtable_0.2.0     tibble_1.4.2
 [9] Rcpp_0.12.16     grid_3.4.4       rlang_0.2.0      munsell_0.4.3
```

2. The R code in question

```
see above
```

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

```
see attachment for diagnostics report
```
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1969491/diagnostics-report.txt)

**Comment by JDMcIninch** [comment]
Please note, I've been able to confirm that the problem also exists in RStudio running on Linux.

**Comment by EDiLD** [comment]
I see this also by using plain `ggsave` without mclappy. 
However, I couldn't track it down when it happens :(

For me the cpu usage of rsession goes up and keeps high. Does not happen in terminal (maybe it's how the ression is started from rstudio?). I am on ubuntu 16.04 LTS.

**Comment by JDMcIninch** [comment]
I seem to be able to use ggsave() inside of an lapply() loop just fine within RStudio. Also, you can switch from using ggsave() to png()/dev.off() instead. I didn't check, but I think it also fails for all plotting methods (e.g., plot()), not just ggplot().
