### ISSUE TITLE
Change colors for prints, messages, warnings, errors in console in RStudio

### ISSUE THREAD

**Issue by chrisvwn** [rstudio/rstudio#2733]
This seems to be an old issue and I copy verbatim a previous thread that turned up in my search since it articulates the issue/request well. I personally advocate for different default colors for each message type possibly with the ability to configure them.

The deprecated thread is here: [https://support.rstudio.com/hc/en-us/community/posts/207326198-Change-colors-for-prints-messages-warnings-errors-in-console-in-RStudio](https://support.rstudio.com/hc/en-us/community/posts/207326198-Change-colors-for-prints-messages-warnings-errors-in-console-in-RStudio).

> Currently messages, warnings and errors all have a red color in the console. This makes it difficult to spot errors if a lot of text is output. A simple solution would be to have different colors for the types of output.
>
> I note that print output already has its own color (black) and so does code (blue).
>
> The best solution would be to make the colors customizable via the Options→Appearance menu. If not, then at least choose some sensible colors. For instance:
>
>    Prints: black (current)
    Messages: grey
    Warnings: orange
    Errors: red (current)
>
> Emil Kirkegaard January 23, 2016 14:04

**Comment by steveharoz** [comment]
I'll add a confirmation that I routinely see beginners panic when they see a red message as innocuous as confirming that a library loaded. Please use red text for errors only. My only comment on the colors suggested is that orange may be hard to distinguish from red, so maybe make warnings purple.

**Comment by tungmilan** [comment]
I had the same experience as @steveharoz mentioned. Undergrads who tried `R` for the first time all freaked out when seeing the red text and thought library installation went wrong :D. 

Regarding color schemes, [`MobaXTerm`](https://mobaxterm.mobatek.net/) has really nice looking one that `RStudio` can adapt at least for dark themes

 
![snap_001](https://user-images.githubusercontent.com/6590141/39730819-b1f59e92-5218-11e8-8da9-fa61edc5896e.png)

**Comment by jmcphers** [comment]
Yes, this is effectively the same issues as #2574; we'll track that one.
