### ISSUE TITLE
Rstudio startup (runtime) error except if started as administrator

### ISSUE THREAD

**Issue by Overlytic** [rstudio/rstudio#2734]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.447
    OS Version      :  Windows10 Pro 64 bit
    R Version       : 3.4.1 (2017-06-30)

### Steps to reproduce the problem
Unsure how to reproduce on another system

### Describe the problem in detail
If I open rstudio it immediately gives a runtime error, see the screenshot:

![image](https://user-images.githubusercontent.com/12955213/39578897-bbc880b4-4ee5-11e8-8859-64822b0c1c4a.png)

However if I open Rstudio as an administrator it open correctly.

Alternatively if I uninstall (or re-install) Git LFS installation (2.4.0), then Rstudio also opens correctly - at least until I restart my machine again.

I have tried reinstalling git-lfs, rstudio, R, clearing the cache. Nothing seems to work so far.

#### sessionInfo() 

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252    LC_MONETARY=English_South Africa.1252
[4] LC_NUMERIC=C                          LC_TIME=English_South Africa.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
[1] compiler_3.4.1   RevoUtils_10.0.6 tools_3.4.1      yaml_2.1.14 

#### A diagnostics report:

[diagnostics-report-20180503.txt](https://github.com/rstudio/rstudio/files/1971039/diagnostics-report-20180503.txt)

**Comment by stst6561** [comment]
Happend to me after installing Rtools 3.4. However, deinstalling Rtools (and RStudio + git) did not help.

**Comment by Overlytic** [comment]
I also have Rtools 3.4 installed. Don't have Rstan though. Take it you did not find a way to resolve it?

**Comment by stst6561** [comment]
No, I'm stuck on reinstalling everything after restarting my machine

**Comment by jmcphers** [comment]
We have never been able to reproduce this and haven't received any other reports in a year and a half, so closing. If you're still seeing it with the latest builds, please let us know.
