### ISSUE TITLE
ctrl-I in a whole Rmarkdown document corrupts YAML header

### ISSUE THREAD

**Issue by jackwasey** [rstudio/rstudio#2739]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.447
    OS Version      :  Ubuntu 18.04
    R Version       :  3.4.4

### Describe the problem in detail

Open Rmarkdown document with a YAML header.
Add:
```
vignette: >
  %\VignetteIndexEntry{title}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
```
select whole document and press ctrl-I
note the loss of the indentation of added lines

### Describe the behavior you expected

YAML indentation is not changed, since this is meaningful in the format.

**Comment by dfalty** [comment]
I was able to reproduce this on 1.2.611 as well. Thanks for the report!
