### ISSUE TITLE
cut/paste does not work in ubuntu 16.04 with emacs keybindings

### ISSUE THREAD

**Issue by carolinecolijn** [rstudio/rstudio#2740]
### System details

    RStudio Edition :desktop_computer: 
    RStudio Version : 1.1.447
    OS Version      :  Ubuntu 16.04
    R Version       : 3.4.2 

### Steps to reproduce the problem
Place text in R script in the Rstudio editor. 
Select text and cut with ctrl-w (emacs keybindings). 
Type ctrl-y. No text is copied.

### Describe the problem in detail
As above, no copying in emacs mode; manually modifying the 'paste last yank' in keyboard shortcuts doesn't help. Also, on my system, using ctrl-x and ctrl-v (default) only sometimes gives cut/paste; restarting Rstudio can help but is not always convenient.

### Describe the behavior you expected
I expected the text to paste on ctrl-y

**Comment by eossiander** [comment]
I have the same problem in Windows with Rstudio desktop version 1.1.453.

**Comment by teichert** [comment]
This [related issue](https://github.com/rstudio/rstudio/issues/2071) points out (and I have verified on my Ubuntu system) that prefixing standard emacs kill commands (like `C-k` and  `C-y`) with `C-c` allows cut and paste to work; e.g. `C-c C-k` to cut and `C-c C-y` to paste.  (This is still not the expected/desired behavior, but I am happy that I can paste again.)

**Comment by davismcc** [comment]
Same for me on Ubuntu 18.04, RStudio 1.1.463

**Comment by kevinushey** [comment]
IMHO this is worth fixing for v1.2.

**Comment by dfalty** [comment]
Verified fixed 1.2.1318.
