### ISSUE TITLE
Icons sometimes randomly appear to be other icons on mouse move

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#2743]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.610
    OS Version      : macOS 10.13.4
    R Version       : 3.5

The icons on the GUI sometimes flash back and forth on mouse move in to or out out the pane.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/4662568/39650275-1926dde8-501a-11e8-925b-1bfc90c40be5.png">

**Comment by dfalty** [comment]
This is a strange one I haven't seen before and can't reproduce! Maybe someone else on the team can explain what's going on here. Thanks for the report.

**Comment by renkun-ken** [comment]
This no longer appears with recent daily builds.

**Comment by rich-rstudio** [comment]
cannot reproduce
