### ISSUE TITLE
The cursor is not in the currect place after input of blanks(spaces) with custom fonts

### ISSUE THREAD

**Issue by TTTPOB** [rstudio/rstudio#2749]
### System details

    RStudio Edition : Desktop
    RStudio Version : Latest(1.1.447)
    OS Version      : Windows 10 1803(17134.5)
    R Version       : Latest Stable(3.5.0)
    Custom Font     :  Sarasa Mono SC 
[Project link](https://github.com/be5invis/Sarasa-Gothic/)

### Steps to reproduce the problem
    Use this font and input some spaces and you will see.(more spaces, more drift)
### Describe the problem in detail
    like this screenshot
![Screenshot](https://s1.ax1x.com/2018/05/06/CU1MrQ.png)

### Describe the behavior you expected
The cursor is expected to present right after the "l"

### P.S.
As this is more like a font bug, I've reported to the font project too.

**Comment by HaroldYu** [comment]
Sarasa's TTC combines many subfonts and RStudio is reported to "hate" it.
It is a software issue since all the TTCs pass OTS, which means that they are conformal to the OTSpec.


this is the comment from the font developer.

**Comment by jmcphers** [comment]
Sorry, we can't offer support for every font. This issue hasn't been reported in well over a year so is not a problem with virtually all fonts (and is likely to due to an issue with this specific font, even if it is technically OTS compliant).
