### ISSUE TITLE
Cannot use Java 10 on MacOS High Sierra with RStudio

### ISSUE THREAD

**Issue by edent** [rstudio/rstudio#2750]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.0.153 
    OS Version      :  10.13.4
    R Version       :  3.5.0 (2018-04-23)

### Steps to reproduce the problem

`library(rJava)`

This is similar to #2254 - although running `sudo R CMD javareconf` in the console does **not** fix rstudio.

### Describe the problem in detail
I have version 10 of Java installed.

```
$ /usr/libexec/java_home 
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    10.0.1, x86_64:	"Java SE 10.0.1"	/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
```

If I try to load rJava in RStudio I get an error about jdk-9 - which has *never* been installed on my system.

```
> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found
```

### Describe the behavior you expected

I expect it to work :-)

I think there may be a problem in the library paths.  In RStudio I have:
```
$DYLD_FALLBACK_LIBRARY_PATH
[1] "/Library/Frameworks/R.framework/Resources/lib:/Users/terenceeden/lib:/usr/local/lib:/usr/lib::"

$DYLD_LIBRARY_PATH
[1] "/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/lib/server"
```

Whereas in R (console) which does work, I have:

```
> Sys.getenv("DYLD_FALLBACK_LIBRARY_PATH")
[1] "/Library/Frameworks/R.framework/Resources/lib:/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/lib/server"
> Sys.getenv("DYLD_LIBRARY_PATH")
[1] ""
```

Trying to set those variables in RStudio doesn't fix anything.

I've also tried installing rJava from source, with similar failures.

Further  from  `sessionInfo()`

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0   
```

**Comment by gregleleu** [comment]
Had the same issue, I think. 
I found a solution [here](https://github.com/MTFA/CohortEx/wiki/Run-rJava-with-RStudio-under-OSX-10.10,-10.11-(El-Capitan)-or-10.12-(Sierra))

Running in the terminal:

     sudo ln -s $(/usr/libexec/java_home)/lib/server/libjvm.dylib /usr/local/lib

(I had to cut out the `/jre/` in the java path compared to the link above for it to work on my computer.)
Basically creating a symlink to the jvm library in the usr library folder. You need to do it after each update...

Hope it helps

**Comment by jmcphers** [comment]
Do you also get this error in the R Gui?

**Comment by jmcphers** [comment]
If that worked then this isn't an RStudio issue -- the situation is caused by the fact that desktop apps started from `launchd` launch with a different set of environment variables than you get in the Terminal. We can't do much about this, but you can change the environment yourself if needed for R packages to work the way you expect. More here:

https://stackoverflow.com/questions/603785/environment-variables-in-mac-os-x

**Comment by shodhak** [comment]
I spent hours on this and thanks to @gregleleu for providing the solution.

**Comment by egriff92** [comment]
@gregleleu I have been after this for days... you are the GOAT! Made an account just to say thank you!

**Comment by PeterNSteinmetz** [comment]
Where is RStudio picking up the DYLD_FALLBACK_LIBRARY_PATH variable from ? It is set on my system to the wrong value relative to the current version of Java being used. 

I have been looking all over for where this coming from in order to change it. None of the sources for launchd mentioned in the above link contain it and neither does the .Rprofile .

**Comment by kevinushey** [comment]
See the file at `file.path(R.home("etc"), "ldpaths")`, and note that this file is updated by `sudo R CMD javareconf` (and that needs to be called any time you want to update the version of Java used by R)

**Comment by PeterNSteinmetz** [comment]
That is good to know. I have no idea how this got changed, but it is now changed and is working.

**Comment by MelissaPerez** [comment]
> Had the same issue, I think.
> I found a solution [here](https://github.com/MTFA/CohortEx/wiki/Run-rJava-with-RStudio-under-OSX-10.10,-10.11-(El-Capitan)-or-10.12-(Sierra))
> 
> Running in the terminal:
> 
> ```
>  sudo ln -s $(/usr/libexec/java_home)/lib/server/libjvm.dylib /usr/local/lib
> ```
> 
> (I had to cut out the `/jre/` in the java path compared to the link above for it to work on my computer.)
> Basically creating a symlink to the jvm library in the usr library folder. You need to do it after each update...
> 
> Hope it helps

I worked! Thank you!
