### ISSUE TITLE
Persistent folding - Feature request

### ISSUE THREAD

**Issue by LunarLanding** [rstudio/rstudio#2751]
I would like folding to be persistent, and to be able to run chunks without triggering expansion.
This has been brought up here too: https://community.rstudio.com/t/wish-store-state-of-collapsible-code-tree/492

**Comment by dfalty** [comment]
Thanks for the enhancement request. To be clear, the two requests are
1. Code folding state saved when a document is closed and opened again.
2. An option to be able to run chunks without expanding. 

We'll consider it as we work development of future releases of RStudio.
