### ISSUE TITLE
Recognize double precision binary notation

### ISSUE THREAD

**Issue by xrobin** [rstudio/rstudio#2752]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : CentOS Linux 7 x86_64-pc-linux-gnu (64-bit) 
    R Version       : 3.4.2 (2017-09-28)

### Steps to reproduce the problem
Open an R file in the Rstudio Editor and add the following line:

    a <- c(0x0p+0, -0X1.3333333333333P-2, 0x09f2a1ced6b78p-528)

Save the file.

### Describe the problem in detail
This is a valid R expression with 3 double precision floating point values given in binary notation. This representation is very useful as it conveys the exact internal representation of the double precision value. Values in this format can be obtained from `sprintf` with the `%a` or `%A` formats

```
> a <- c(0x0p+0, -0X1.3333333333333P-2, 0x09f2a1ced6b78p-528)
> a
[1]   0.000000e+00  -3.000000e-01  1.991629e-145
> sprintf("%a", a)
[1] "0x0p+0"                "-0x1.3333333333333p-2" "0x1.3e5439dad6fp-481" 
> sprintf("%A", a)
[1] "0X0P+0"                "-0X1.3333333333333P-2" "0X1.3E5439DAD6FP-481" 
```

This valid R syntax is detected as an error by Rstudio. After saving the file, part of the line is underlined with red, and an error appears on the left with the following message:

> Unexpected token 'p'
> Unexpected token X1.3333333333333P

![rstudio_binary_double](https://user-images.githubusercontent.com/1047170/39699390-4ae8e2b4-51f9-11e8-9169-38604b148e2d.png)

Some more details about this format are given in the [base::sprintf man file](https://www.rdocumentation.org/packages/base/versions/3.5.0/topics/sprintf), although this is only about the output format, and says nothing about what input R would accept. I couldn't find any reference about what is an acceptable input in the "The R language definition" and "R internals" 

### Describe the behavior you expected

Rstudio should not display a syntax error for this line.

### Session information

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /unibas/lcs-software/software/OpenBLAS/0.2.13-GCC-4.8.4-LAPACK-3.5.0/lib/libopenblas_prescottp-r0.2.13.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_CH.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_CH.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=fr_CH.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fortunes_1.5-4 Cairo_1.5-9   

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    yaml_2.1.14   

```

**Comment by kevinushey** [comment]
For future reference, here's how R parses numbers:

https://github.com/wch/r-source/blob/20064ba38814926f4a93d4c453ff6209da6ec6bb/src/main/gram.y#L2069-L2191

**Comment by kevinushey** [comment]
As a curiosity:

```
> 0x.0ep0
[1] 0.0546875
```
