### ISSUE TITLE
IFrames with external URLs pop up in separate windows

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2756]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.616
    OS Version      : macOS 10.13

### Steps to reproduce the problem

Run these two commands:

    > library(htmltools)
    > print(browse = TRUE, tags$iframe(src="https://www.rstudio.com/"))

### Describe the problem in detail

The `iframe` displays in the Viewer pane, but it's empty, and the RStudio.com website opens in a new browser window.

### Describe the behavior you expected

No external windows should be opened.

This regression occurred because QtWebEngine does not tell us what kind of `NavigationType` is being requested; we cannot distinguish between link clicks (which should indeed open external windows) and IFrame loads (which should not). 

https://github.com/rstudio/rstudio/blob/71ff50d204963610b4c338f912600e44d0ca3c0d/src/cpp/desktop/DesktopWebPage.cpp#L244-L252

We will need to distinguish between these cases in some other way.

**Comment by kevinushey** [comment]
One possibility: we could use our request interceptor to discover the type of resource being requested, and use that to decide whether we can handle the link locally. For example:

https://doc.qt.io/qt-5.10/qwebengineurlrequestinfo.html#resourceType

This does seem to report when an `iframe` is being loaded. FWIW the enum values are:

```
    enum ResourceType {
        ResourceTypeMainFrame = 0,  // top level page
        ResourceTypeSubFrame,       // frame or iframe
        ResourceTypeStylesheet,     // a CSS stylesheet
        ResourceTypeScript,         // an external script
        ResourceTypeImage,          // an image (jpg/gif/png/etc)
        ResourceTypeFontResource,   // a font
        ResourceTypeSubResource,    // an "other" subresource.
        ResourceTypeObject,         // an object (or embed) tag for a plugin,
                                    // or a resource that a plugin requested.
        ResourceTypeMedia,          // a media resource.
        ResourceTypeWorker,         // the main resource of a dedicated worker.
        ResourceTypeSharedWorker,   // the main resource of a shared worker.
        ResourceTypePrefetch,       // an explicitly requested prefetch
        ResourceTypeFavicon,        // a favicon
        ResourceTypeXhr,            // a XMLHttpRequest
        ResourceTypePing,           // a ping request for <a ping>
        ResourceTypeServiceWorker,  // the main resource of a service worker.
        ResourceTypeCspReport,      // Content Security Policy (CSP) violation report
        ResourceTypePluginResource, // A resource requested by a plugin
#ifndef Q_QDOC
        ResourceTypeLast,
#endif
        ResourceTypeUnknown = 255
    };
```

**Comment by jmcphers** [comment]
Reopening since fix was reverted. https://github.com/rstudio/rstudio/commit/5068a03f059928c3fb6b5ef26443ac0771ac3ba7

**Comment by jjallaire** [comment]
I am still seeing disqus comment iframes being loaded in an external browser window (this with RStudio v1.2.748). You can repro by building one of the Rmds here: https://github.com/radixpub/radix-r/tree/master/examples/websites/reproducible-finance-with-r/_posts (you'll need to `devtools::install_github("radixpub/radix-r")` first.

**Comment by kevinushey** [comment]
@jjallaire were you viewing the document within the Viewer pane or a secondary RStudio window?

**Comment by jjallaire** [comment]
I saw the behavior in both contexts.

**Comment by kevinushey** [comment]
Thanks -- that's surprising to me since I didn't see that in the Viewer but did see it when rendered in a secondary window. I'll see if I can learn more.

**Comment by kevinushey** [comment]
I think we should finally have a handle on this -- hopefully all will be well in the next daily builds.

**Comment by jjallaire** [comment]
Indeed, I'm no longer seeing it in today's daily! :-)

**Comment by kevinushey** [comment]
Great! Glad we finally got a handle on this.
