### ISSUE TITLE
R Markdown Evaluate chunks in directory option disappears (on R update?)

### ISSUE THREAD

**Issue by ceagland** [rstudio/rstudio#2761]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.1.447
    OS Version      :  Windows 7/10 (2 systems)
    R Version       :  3.5.0

### Steps to reproduce the problem
Installation of R 3.5.0 (Not 100% sure this is the trigger, but it did happen twice on two different computers)

### Describe the problem in detail
Installed new version of R (3.5.0), and in RStudio Global Options/R Markdown, the **Evaluate chunks in directory** option is missing. Closing and opening RStudio did not fix the issue, but after a reinstall the option has returned.

Same experience on a Windows 7 and a Windows 10 system. I first noticed when I ran a chunk in an R Notebook and it didn't work when it had been fine immediately prior to updating to R 3.5.0. On the Windows 7 system, I checked that the option was present immediately prior to updating R (yes, it was), and then disappeared after the update.

I installed R using installr::updater(), and did so using Rgui, not RStudio.

**Comment by dfalty** [comment]
Did you happen to not have rmarkdown installed yet after the upgrade to 3.5? This option won't appear until that package is installed it seems.
