### ISSUE TITLE
Session First Project Template regression in 1.1.447

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#2765]
The dockerfile in #2095 reproduces a regression in 1.1.447.  The dockerfile worked great off of a version of `rocker/rstudio` pointed at 1.1.383 (unfortunately, they do not tag the rstudio version in the builds) and then failed on 1.1.447 (`rocker/rstudio:latest`).

Is it worth adding such a test to our test suite?  It might be a lot of work for such a simple feature, but it would help protect against this feature getting broken again in the future!

**Comment by jmcphers** [comment]
Can you describe what kind of failure you're seeing, and when you're seeing it? (An error? The project template not loading? Something else?)

**Comment by jmcphers** [comment]
@kfeinauer are you able to reproduce this?

**Comment by kfeinauer** [comment]
There's no bug here. The new rocker image ships with the folder `/home/rstudio/.rstudio` which signals to the session template code that the `rstudio` user is **not** a new user. Therefore, the first template project is not copied and run.

If you want this to work, in your Dockerfile mentioned in #2095 you can explicitly delete this directory at the bottom of the file:

```
# delete rstudio user's .rstudio folder so he is marked as a new user
RUN rm -rf /home/rstudio/.rstudio
```

This does not cause any harm, and should allow you to test this particular feature for regression purposes.

**Comment by colearendt** [comment]
@kfeinauer That makes a ton of sense, and also helps with understanding how the templating works and the workaround.  Thanks so much!
