### ISSUE TITLE
Can't Disable AutoComplete via Tab

### ISSUE THREAD

**Issue by statsandthings** [rstudio/rstudio#2766]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Windows 7 Pro
    R Version       : 3.4.4

### Steps to reproduce the problem

```
library(tidyverse)
treatment <- tribble(
  ~ person,           ~ treatment, ~response,
  "Derrick Whitmore", 1,           7,
  NA,                 2,           10,
  NA,                 3,           9,
  "Katherine Burke",  1,           4
)

```
Enter text above into console. Place cursor in between `NA` and `2`. Press <kbd>Tab</kbd> key. Autocomplete is triggered no matter the settings that I've chosen in `> Settings > Code > Completion`. 

### Describe the problem in detail
I'd like autocomplete disabled. When I enter a <kbd>Tab</kbd> I'd like a <kbd>Tab</kbd> entered, instead of receiving an autocomplete dialog. I have a vague recollection that it's bad to use tabs in R code. Maybe this is intentional?

**Comment by tmcduff** [comment]
Verified: Version 1.3.743
