### ISSUE TITLE
Right Click -> Open Link in New Window opens blank window

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2767]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.622
    OS Version      : macOS 10.13.4
    R Version       : 3.5.0

### Steps to reproduce the problem

Try rendering this document:

`````
---
title: "Untitled"
output: html_document
---

<https://www.rstudio.com>
`````

Then, in the preview of the rendered document (reproduces both in Viewer pane and when opened in separate window), try right clicking on the link and clicking <kbd>Open Link in New Window</kbd>:

<img width="309" alt="screen shot 2018-05-11 at 11 37 22 am" src="https://user-images.githubusercontent.com/1976582/39940918-b8fe65ee-550f-11e8-96d6-94782a2ca0d6.png">

### Describe the problem in detail

A blank, minimal RStudio window is opened, and then the content is finally opened in an external browser.

<img width="316" alt="screen shot 2018-05-11 at 11 38 32 am" src="https://user-images.githubusercontent.com/1976582/39940976-ee69e5be-550f-11e8-9faa-7d6c7cc55fb2.png">

### Describe the behavior you expected

We should either open the page directly in the RStudio window, or avoid generating a new window and just open directly in the browser.

**Comment by yihui** [comment]
With exactly the same example, RStudio simply crashes if I (left-)click the link. I just tested the very latest daily build, and it is still reproducible (on macOS).

**Comment by kevinushey** [comment]
Doh, I can reproduce as well. I'll get this fixed up in the next builds.

**Comment by yihui** [comment]
It no longer crashes with the latest daily build, although your original issue (the blank RStudio window) is still there.
