### ISSUE TITLE
restore Back, Forward buttons in right click menu

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2768]
From @yihui:

> There used to be a menu item Back (like the Back button in web browsers) in the viewer, which is also something I used frequently when writing blogs. It will be great if it could be brought back, too.

We should bring this back.

**Comment by kevinushey** [comment]
Fixed in the latest daily builds.

**Comment by grawil** [comment]
Could you please also restore the 'Inspect' option? Really handy for customising themes...

**Comment by yihui** [comment]
@grawil See #2133.

**Comment by grawil** [comment]
ah, I see...thanks @yihui

**Comment by yihui** [comment]
The regression happened again in `Version 2022.12.0+353`. The `Forward` and `Back` buttons disappeared in the context menu of the Viewer again.

**Comment by ronblum** [comment]
Thanks! I'll open a new issue for this, because it's probably due to the migration to Electron.

**Comment by yihui** [comment]
Thanks @ronblum!

**Comment by ronblum** [comment]
Filed as issues #12491 and #12493 (ignore #12492).
