### ISSUE TITLE
Pop-out / pop-in source window discards saved changes

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#2770]
I have found on several occasions now that if I have a source window popped out and all changes saved, and then return it to the main window, the file will lose many changes and show up instantly with a "*" indicating that it is different from on-disk.  Closing the file and re-opening will open the correct, most recently saved version with all changes.

I cannot replicate this reliably but it has happened at least 10 times in the last month.

This has resulted in lots of lost work before I discovered what was happening.

**Comment by ronblum** [comment]
@jzadra Can you please provide more information to help us diagnose the the problem? Specifically, what version of RStudio are you using and which OS?

**Comment by jmcphers** [comment]
We don't have reproducible steps or any other reports, so closing this. We have also made a number of improvements to pop-out behavior in 1.2, so it's very possible this doesn't repro any more (feel free to reopen if it does!)
