### ISSUE TITLE
Rstudio crashes frequently in xubuntu 18.04

### ISSUE THREAD

**Issue by ngagun** [rstudio/rstudio#2772]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version      : xubuntu 18.04
    R Version       : 3.4.4

### Steps to reproduce the problem
Close the lid to put the laptop to sleep. Open it again.

### Describe the problem in detail
Rstudio will crash (>90% of the time). I believe it may have crashed one other time not in the context of sleep/wake.

### Describe the behavior you expected
R studio to continue running.

1. The output of sessionInfo() 

R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4  

2. The R code in question

N/A

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-

Please see attached.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1998844/diagnostics-report.txt)

**Comment by kevinushey** [comment]
You might try the latest daily builds of RStudio, available at https://dailies.rstudio.com. We're hoping to promote a build to a preview release soon and I believe many of these sorts of issues will be fixed in the v1.2 branch.

**Comment by ngagun** [comment]
Thank you. I installed 1.2.625, no crashes so far. I'll post again if it crashes again.
