### ISSUE TITLE
Commands after magrittr pipes should be indented

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/rstudio#2773]
When long variable or function names is combined with magrittrs pipe operators, the command following the operator may have a completely different indentation.

Example:
```
years_gone_by_since_today <- difftime(time1 = Sys.Date(),
                                      time2 = data$date,
                                      units = "days") %>% 
    as.numeric() %>% 
    divide_by(365)
```
 
I would instead propose the following indentation:
```
years_gone_by_since_today <- difftime(time1 = Sys.Date(),
                                      time2 = data$date,
                                      units = "days") %>% 
                             as.numeric() %>% 
                             divide_by(365)
```

**Comment by kevinushey** [comment]
FYI, you can enclose your text in <kbd>```</kbd> to use a fixed-width font to easier show indentation, e.g.:

`````
```
foo %>%
  bar() %>%
  baz()
```
`````

**Comment by kevinushey** [comment]
If I understand your proposal, you would prefer indentation to be relative to the position of the `=` or `<-` operator, e.g. you want:

```
my_variable <- foo() %>%
                 bar() %>%
                 baz()
```

Is that correct?

**Comment by mac-pfa** [comment]
Thank you for the hint, I have fixed the examples.
But you are exactly right, that is my proposal.
