### ISSUE TITLE
allow users to toggle cursor position save / load behavior

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2778]
Re: https://github.com/rstudio/rstudio/blob/879050091490857ef38db71137b7c2c7748d2a4f/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L1573-L1599

It seems like this can be slow in some environments (mainly Windows + NFS), e.g.

https://community.rstudio.com/t/rstudio-suddenly-slow-processing/4959/24

We should add a UI toggle for enabling / disabling this behavior.

**Comment by jmcphers** [comment]
Closing via https://github.com/rstudio/rstudio/commit/5ee6596ccf72275cc9905da42c7b1c0e40a46274.

**Comment by dfalty** [comment]
Verified on version 1.2.1090.
