### ISSUE TITLE
enhancement: Add A3 paper format  to selectlist in "Save Plot as PDF" dialog box

### ISSUE THREAD

**Issue by knbknb** [rstudio/rstudio#2786]
I wished printing/saving a plot in A3 paper format would be easier. 

I often plot data frames with long lineplots. Often I save them as PDF and then print them out. For example,  to discuss the plot with colleagues who do not have large monitors (and cannot view the lineplot in its entirety, or only with low resolution).  I like to put several printed plots (on A3 sheets) side-by-side on my desk, later on. 

Especially faceted plots look much better on  large canvases.  A3 paper format is a reasonable choice for a larger canvas. Many office printers (in Europe at least) have an A3 tray these days. 

I know that plots can be saved with `ggsave()` for instance, and I often use that command and it's very convenient and works very well. But here's another argument for why A3 dimensions should be included in the selection list of the  "Save Plot as PDF" dialog box of RStudio.

Sometimes when I go through a list of older plots inside the Rstudio "Plots" pane, I discover some older plots that are worth saving/printing for some reason. In this case often the codechunk containing the `ggsave` call has been changed in places, and undoing the changes is not really possible, or would be distracting. Then I use the Export.../Save as PDF... GUI feature to save the older plot, but I have to add custom device sizes each time. So can a persistent A3 device size added to the options in the select list?

It should be easy to add the dimensions for A3 to the appropriate [.java file](https://github.com/rstudio/rstudio/blob/54cd3abcfc58837b433464c793fe9b03a87f0bb4/src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java)

**Comment by ronblum** [comment]
@knbknb  Thanks for the suggested enhancement! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by knbknb** [comment]
Another late idea: At this time, there exists the option to print in "A6" paper format. A6 is the size of a postcard. 

I don' t know any use case for this. Who might want to print a plot on a sheet this small?  Anyway, your GUI designers probably know what they are doing, and had their reasons to include A6.

If not - maybe A6 can be replaced with A3 if the selection list must not grow any longer.
