### ISSUE TITLE
Upgrade Pandoc to 2.2.1 in RStudio 1.2

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#2787]
Pandoc 2.2.1 has been released a few days ago: https://github.com/jgm/pandoc/releases/tag/2.2.1 (cc @jmcphers).

**Comment by nwstephens** [comment]
@yihui Pandoc 2.2.0 is sufficient for our use cases. Are there features in 2.2.1 that we need or are you suggesting we upgrade in order to keep up with the latest software?

**Comment by yihui** [comment]
There is an ugly bug in 2.2.0: https://github.com/jgm/pandoc/issues/4639

**Comment by ronblum** [comment]
> pandoc_version()
[1] ‘2.2.1’
