### ISSUE TITLE
Fedora Daily Build Desktop 1.2.631-1-x86_64 libEGL & libGLESv2 not exist

### ISSUE THREAD

**Issue by andys0975** [rstudio/rstudio#2789]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.631-1-x86_64
    OS Version      : Fedora 28
    R Version       : 3.4.4

### Steps to reproduce the problem

install rpm from https://dailies.rstudio.com/rstudio/oss/fedora/x86_64/ without reported error
but start rstudio with error

### Describe the problem in detail

libEGL warning: DRI2: failed to authenticate
[0516/005718.900642:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/tiger/#8649212 (deleted)
  Error: 沒有此一檔案或目錄
[10017:10124:0516/005718.960890:ERROR:gl_implementation.cc(246)] Failed to load /usr/lib/rstudio/bin/libGLESv2.so: /usr/lib/rstudio/bin/libGLESv2.so: 無法開啟共用目的檔: 沒有此一檔案或目錄
[10017:10124:0516/005719.161440:ERROR:gl_surface_qt.cpp(701)] Requested OpenGL implementation is not supported. Implementation: 0
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f9a8f9060a5 <unknown>
#1 0x7f9a8e647141 <unknown>
#2 0x7f9a8f90643d <unknown>
#3 0x7f9a8dd2dfb0 <unknown>
#4 0x7f9a8e6886d1 <unknown>
#5 0x7f9a8e689565 <unknown>
#6 0x7f9a903de674 <unknown>
#7 0x7f9a903e99d4 <unknown>
#8 0x7f9a903ec563 <unknown>
#9 0x7f9a903ed74f <unknown>
#10 0x7f9a903e241e <unknown>
#11 0x7f9a903e777c <unknown>
#12 0x7f9a903e6b8d <unknown>
#13 0x7f9a903e8ca5 <unknown>
#14 0x7f9a8f989319 <unknown>
#15 0x7f9a8f922648 <unknown>
#16 0x7f9a8f923d6f <unknown>
#17 0x7f9a8f9242c0 <unknown>
#18 0x7f9a8f925169 <unknown>
#19 0x7f9a8f942e5a <unknown>
#20 0x7f9a8f95de47 <unknown>
#21 0x7f9a8f9594ad <unknown>
#22 0x7f9a8dd23564 start_thread
#23 0x7f9a8c22031f __GI___clone
  r8: 0000000000000003  r9: 0000000000000000 r10: 00007f99d40008d0 r11: 0000000000000000
 r12: 0000000000000000 r13: 00007f99f5ff9d50 r14: 00007f99f5ff9d00 r15: 00007f99d400fd40
  di: 0000000000000000  si: 0000000000000000  bp: 00007f99f5ff9b40  bx: 00007f99d400fd40
  dx: 0000000000000000  ax: 00007f9a944ea568  cx: 00007f99f5ff9970  sp: 00007f99f5ff9970
  ip: 00007f9a8e6886d1 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

### Describe the behavior you expected
I expect it start normally

**Comment by kevinushey** [comment]
We might need to set some flag in Chromium to ensure that OpenGL rather than GLES is used.

**Comment by andys0975** [comment]
I've tried both you suggested, but it still reporting the same error.
I have libEGL & libGLESv2 in /usr/lib64 but not in /usr/lib
Is this a problem?

**Comment by kevinushey** [comment]
The problem is the version of Qt we use with RStudio doesn't come with the necessary EGL / GLES plugins, so desktop OpenGL is required for now.

**Comment by jmcphers** [comment]
No work for us to do here; this is upstream with Qt.
