### ISSUE TITLE
Feature Request: add copy feature to history tab

### ISSUE THREAD

**Issue by hdykiel** [rstudio/rstudio#2798]
### Describe the problem in detail
Feature idea from customer:
"It would be great if copy (by right click and cmd-c) could be added to the History tab.  Right now, it is just send to console or send to source with a button.  If you want to move something to a different RStudio session, you need to use one of those buttons and then copy-paste. "

### Describe the behavior you expected
In history pane, highlighted command can be copied to clipboard via keyboard shortcut cmd + C.

**Comment by TigerZhao007** [comment]
YES, This is exactly what i want!!!!
Please make history tab just MATLAB 
Make it copiable!!!!
