### ISSUE TITLE
Rework drag-and-drop file path into console

### ISSUE THREAD

**Issue by dkyleward** [rstudio/rstudio#2800]
It would make things easier if a file could be dropped anywhere in the Console window and still insert the file path at the cursor. Currently, I have to drop the file right on the cursor (with a few pixels for margin of error). Missing the mark with a large file is painful.

I don't know if this second bit is possible, but many apps change appearance when you drag a file onto them (google drive, asana, github). It would be great if this was the case for Rstudio. In addition, it could actually be put to good use: the majority of the screen is masked with a message saying "drop to open file", but the console window is masked with the message "drop to insert path".

That last part would be great for a number of reasons. One of which is it took me over a year of using Rstudio to even realize I could insert the path under the current system.

Thank you!

**Comment by ronblum** [comment]
@dkyleward Thank you for the suggestion! We'll take a look at it as we continue development of RStudio.

**Comment by wasdoff** [comment]
My apologies if I'm in the wrong place for this, but seeing how the issue has gone 'stale' I'd like to express my interest in this potential feature as well!
