### ISSUE TITLE
When zoomed in list viewer shows scroll bar in wrong place

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2808]
![screen shot 2018-05-17 at 4 47 57 pm](https://user-images.githubusercontent.com/4196/40209050-11fd2f2c-59f2-11e8-8253-2283d5f48a1d.png)

1. Use Cmd + + to zoom in a bunch
2. `View(repurrrsive::gh_repos)`

**Comment by ronblum** [comment]
@hadley Are you still seeing the problem? I haven't been able to reproduce exactly that, but I do see the scrollbar briefly appear higher up—say, in the middle of the list—before it settles where it belongs.

**Comment by hadley** [comment]
Yeah, it gets to the right place eventually, but it takes a noticeable amount of time for me.
