### ISSUE TITLE
Use UTF-8 characters for cli::symbol on Windows

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rstudio#2809]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.642
    OS Version      :  Windows 10
    R Version       : 3.5.0

### Describe the problem in detail

RStudio supports displaying UTF-8 characters, even on Windows. However, `cli::symbol` is still loaded using the less-appealing Windows fallback symbols. Is it possible for RStudio to set `options(cli.unicode = TRUE)` so that `cli::symbol` is loaded correctly out-of-the-box?

That said, it seems like `.onLoad()` messages are restricted to ASCII (when packages are loaded, cli::symbol$tick shows as a `v` rather than even as `√`; loading tidyverse with `options(cli.unicode = TRUE)` displays the unicode values, rather than the characters. Is that addressable?

**Comment by jmcphers** [comment]
> Is it possible for RStudio to set options(cli.unicode = TRUE) so that cli::symbol is loaded correctly out-of-the-box?

It is possible, but we generally try to avoid hardcoding package options in the IDE; the decision to use Unicode should be made in the cli package itself. I'd encourage you to open an issue over there instead. This is where the Unicode switch lives:

https://github.com/r-lib/cli/blob/0209175036f6f5c5a99139e80b0b05046143527b/R/utf8.R#L18

If it is always appropriate to show Unicode in RStudio, then that test could be updated to check to see whether it's running in RStudio (which is very straightforward).
