### ISSUE TITLE
Cannot login RStudio Server when user is recreated

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#2810]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.453
    OS Version      : Ubuntu 16.04.4
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Create a user `test_user`
2. Login `test_user` in RStudio Server and log out session
3. Delete the user and recreate it (optionally with ecryptfs using `adduser --encrypt-home test_user`)
4. Login `test_user` again in RStudio Server and error occurs

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/4662568/40214818-7ed9ca40-5a8f-11e8-9f45-8f7575b9f88f.png)

I use `rstudio-server kill-all` but it still does not work.

**Comment by jmcphers** [comment]
Did the newly created user get the same user ID?

Are they able to access the contents of their home directory?

**Comment by renkun-ken** [comment]
Yes, the same user. The user is able to access the home directory.

**Comment by renkun-ken** [comment]
Reinstalling the latest dev version solves the problem. But if it couldn't be reinstalled, I'm not sure how it can be fixed.

**Comment by renkun-ken** [comment]
This is actually a one-time issue which happened once when I did those and is no longer occurring. I only tried `adduser --encrypt-home test_user` since all our users are supposed to be created this way.
