### ISSUE TITLE
Keyring fails to return value when password changed with Windows Credentials Manager

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2811]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.637
    OS Version      : Windows 10
    R Version       : 3.4.4, 3.5.0

### Steps to reproduce the problem

1. Set a username/password: `key_set_with_value("bobo", username = "bobo_username", password = "bobo_password")`
2. Retrieve the password: `key_get("bobo", "bobo_username")`
    - Result: password
    > [1] "bobo_password"
3. Update the password using the Credential Manager in the Control Panel
4. Retrieve the password: `key_get("bobo", "bobo_username")`
   - Result: error
    > Error in b_wincred_get(self, private, service, username, keyring) : 
    >  Key contains embedded null bytes, use get_raw()

### Describe the problem in detail

When a `keyring` password is updated in Windows, `key_get()` returns an error instead of the password.

### Describe the behavior you expected

The updated password would be returned. `key_get_raw()` doesn't help, as it returns a different error:
> \> key_get_raw("bobo", "bobo_username")
> Error in b_wincred_get_raw(self, private, service, username = NULL, keyring = NULL) : 
>  could not find function "b_wincred_get_raw"

**Comment by jmcphers** [comment]
This is an issue with the keyring package; you should open it on that repo:

https://github.com/r-lib/keyring

**Comment by ronblum** [comment]
Filed: https://github.com/r-lib/keyring/issues/56

Note that the problem is in `keyring`, but it affects `rstudioapi::askForSecret`
```
> rstudioapi::askForSecret(name = "bobo_username", title = "Request For Password", message = "What is the password?")
[1] "bobo_pw"
```
Then, update the password using credential manager. After that, ask for the password again but don't update it—just accept what was already provided by `keyring` in the dialog by clicking on `OK`:
```
> rstudioapi::askForSecret(name = "bobo_username", title = "Request For Password", message = "What is the password?")
Error in b_wincred_get(self, private, service, username, keyring) : 
  Key contains embedded null bytes, use get_raw()
Error in .rs.askForSecret(name, title, prompt) : 
  Ask for secret operation was cancelled.
```
