### ISSUE TITLE
Plumber dependencies don't install automatically

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2812]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.648
    OS Version      : Windows-10 (probably other platforms, too)
    R Version       : 3.4.3

### Steps to reproduce the problem
- Clean RStudio install on Windows-10
- File / New File / Plumber API...
- Get asked to install required packages (as expected); click Yes

![2018-05-18_10-24-33](https://user-images.githubusercontent.com/10569626/40248728-b44d4350-5a85-11e8-891c-cfe4dd9847a9.png)

### Describe the problem in detail
The package install starts happening but quickly dismisses. I captured the output and it was an error involving missing dependencies of Plumber:

![img_0977](https://user-images.githubusercontent.com/10569626/40248790-e5692602-5a85-11e8-8078-f092ae23d7dc.jpg)

### Describe the behavior you expected
Plumber package installed, then new Plumber source file created.

**Comment by jmcphers** [comment]
You need to capture Plumber's dependencies in the DependencyManager; see r2d3 for an example:

https://github.com/rstudio/rstudio/blob/6bfa65d851d25f7a541fe1febfd8d999db5fb67a/src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java#L136-L138

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
