### ISSUE TITLE
RStudio launches with installed folder as working directory

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2813]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.648
    OS Version      : Windows 10 x64
    R Version       : R 3.5.0

### Steps to reproduce the problem

Delete the folder at `%LOCALAPPDATA%\RStudio-Desktop`, and launch RStudio. Make sure RStudio is launching with no project open.

### Describe the problem in detail

The initial working directory is the RStudio installation folder, rather than the user home directory. In addition, quitting RStudio prints an error on the attempt to save `.Rhistory` in that same folder.

<img width="181" alt="screen shot 2018-05-18 at 12 08 36 pm" src="https://user-images.githubusercontent.com/1976582/40253390-655ae5c2-5a94-11e8-90e6-aca7b84a8234.png">

<img width="370" alt="screen shot 2018-05-18 at 12 11 17 pm" src="https://user-images.githubusercontent.com/1976582/40253443-9d5ee392-5a94-11e8-90ca-06e582e9f1bf.png">

### Describe the behavior you expected

RStudio should use the user home directory on startup.

**Comment by cimentadaj** [comment]
Happens to me as well.

**Comment by gtritchie** [comment]
Fixed via: 82d8ed85fc33ac2b89a130ec27159a20f1e4640c
