### ISSUE TITLE
Change MD5 to SHA256

### ISSUE THREAD

**Issue by einsteinsfool** [rstudio/rstudio#2814]
## Description
On the [download page](https://www.rstudio.com/products/rstudio/download/#download) MD5 sums are provided.
Provide SHA256 (and hopefully SHA512) checksums instead for all files both on the [download page](https://www.rstudio.com/products/rstudio/download/#download) and GitHub in the `releases` section. All in plaintext so users don't need to download the checksum which would defeat the whole purpose of them.

Both [MD5](https://en.wikipedia.org/wiki/MD5#Security) and [SHA1](https://en.wikipedia.org/wiki/SHA-1#SHAttered_%E2%80%93_first_public_collision) are breaked and shouldn't be provided because they give a false sense of security.

## Expected Behavior
After downloading the file I should be able to verify if the file I have is the same as the one uploaded by the maintainers.

## Current Behavior
Users can't verify the downloaded files.

## Steps to Reproduce
1. Download an installer.
2. An attacker intercepts the file and swaps it with a modified malicious one.
3. Don't verify the file because there are no checksums.
4. Get ~~f...~~ hacked. (couldn't resist)

**Comment by jmcphers** [comment]
If you want to additional assurance that the file is authentic, we recommend [checking its signature](https://www.rstudio.com/code-signing/) rather than relying on a checksum posted on our website.

**Comment by einsteinsfool** [comment]
Thank you. This is indeed a safer way but adding SHA256 as well would be welcome. Checking it is a bit faster and since you already have MD5 you can just change it to SHA256.

**Comment by AndreMikulec** [comment]
One should not use MD5.
```
Historically, MD5 has been used to store a one-way hash of a password, 
often with key stretching.[45][46] Due to the weaknesses described in the Security section, 
NIST does not include MD5 in their list of recommended hashes for password storage.
```
https://en.wikipedia.org/wiki/MD5

**Comment by jmcphers** [comment]
We have now switched to SHA-256 on the website.
