### ISSUE TITLE
Allow publishing rendered content from the Source pane

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2816]
In RStudio 1.0, it was possible to publish rendered documents to RPubs, and RStudio Connect, by clicking on the Publish button in the Source pane. 

This created a lot of ambiguity, confusion, and frustration for RStudio Connect users:

* publishing required going through a confusing "publish code" or "publish document" disambiguation phase;
* some documents could only render on Connect, so we broke workflows by requiring a local render;
* rendering requires re-execution of all the R code so often made publish very slow; and, most importantly;
* users were very confused about why publishing their Rmd caused *two* renders (a local render in the R Markdown tab followed immediately by a remote render in the Deploy tab), and didn't understand where to look for the source of failures

In RStudio 1.1, we attempted to solve this problem by making the Publish button act *only* on what you clicked on. In other words, if you clicked on the code in the Source pane, it was assumed that you wanted to publish the code. And if you clicked the Publish button on e.g. a rendered R Markdown document, it was assumed you wanted to publish just the output, not the code.

It turns out however that people find that the Publish button in the Source pane is the most natural place to initiate a publish, and that removing the ability to use it to publish rendered artifacts wasn't well-received. For example, many people thought that we'd taken away the ability to publish to RPubs entirely:

https://community.rstudio.com/t/suggestion-bring-back-the-publish-to-rpubs-option/5098

We need to fix this in 1.2; specifically:
- it should be possible, once more, to publish rendered content to both RPubs and RStudio Connect from the Source pane, and
- we need to integrate the local render more carefully, such that it is possible to have RStudio perform a just-in-time local render, but also (a) only if necessary, and (b) optional when publishing to RStudio Connect (sidestepping as many of the original issues as possible).

**Comment by nwstephens** [comment]
I want to publish ANY static assets more naturally, not just HTML that shows in the viewer. I’m working on PowerPoint and I’ve noticed that if I want to publish the static asset (*.ppt) I have to use the `deployDoc` function. I would rather be able to publish with the push of a button through the viewer like I do with static HTML assets. Obviously, ppt doesn’t render in the viewer, but it would be nice if there were an easier way to publish rendered ppt files.

**Comment by gtritchie** [comment]
Opened #3265 to track the request for publishing any static assets more naturally. This current issue will just track putting back ability to publish rendered content from the editor publish button.
