### ISSUE TITLE
terminal pane fails to launch any terminals on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2817]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.650
    OS Version      : Windows 10 x64
    R Version       : R 3.5.0

### Steps to reproduce the problem

Attempt to open a terminal.

### Describe the problem in detail

No terminal is opened.

### Describe the behavior you expected

A terminal should be opened.

Unfortunately, the Terminal Diagnostics window doesn't contain any useful information; just:

```
Global Terminal Information
---------------------------
Loaded TerminalSessions: 0

Terminal List Count: 0
```

**Comment by gtritchie** [comment]
Repro'd as described on clean Win-10 machine (no dev tools, no previous RStudio install). Was using R 3.4.3, but unlikely R is a factor for terminal. On first try to bring up a terminal, I got this, and accepted the default:

![2018-05-19_11-58-26](https://user-images.githubusercontent.com/10569626/40272079-3615d29a-5b5c-11e8-88ac-353b4f7055da.png)

**Comment by kevinushey** [comment]
The terminal seems to work on my Windows 7 VM, so it may be that something changed on Windows 10 that's breaking us. Perhaps something in the April update?

**Comment by gtritchie** [comment]
On Win-10, 1.2.650 terminal is working with 32-bit R, but not 64-bit R.
