### ISSUE TITLE
rstudio daily build fails to launch on Windows 7

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2820]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.650
    OS Version      : Windows 7 x64
    R Version       : R 3.5.0

---

Perhaps something else we need to bundle with RStudio?

<img width="363" alt="screen shot 2018-05-19 at 1 54 17 pm" src="https://user-images.githubusercontent.com/1976582/40272957-3a91c134-5b6c-11e8-8a1f-907ab4e6cb90.png">

---

Installing the Visual C++ 2015 redistributable from https://www.microsoft.com/en-us/download/details.aspx?id=52685 fixes the issue for me. I feel like we tried to tackle this issue before; perhaps we need to explicitly bundle and attempt installation of this when installing on Windows systems?

**Comment by jmcphers** [comment]
Yes, we fixed something very similar here: https://github.com/rstudio/rstudio/issues/2197

**Comment by jmcphers** [comment]
Maybe we just need `CMAKE_INSTALL_UCRT_LIBRARIES`? https://cmake.org/cmake/help/v3.9/module/InstallRequiredSystemLibraries.html

**Comment by jmcphers** [comment]
I can't reproduce this on a clean Win7 (I'm using a VM w/ IE10 from modern.ie). Perhaps it already has the requisite libraries? 

@kevinushey where did you get your Win7 image from?

**Comment by kevinushey** [comment]
I believe I downloaded it from https://www.microsoft.com/en-us/software-download/windows7 a while ago.

FWIW Windows declares its version as 6.1.7601 SP1 Build 7601.

Somewhat surprisingly, after rebooting this VM and trying to launch the latest daily build everything works. Given that the issue seems to have magically resolved itself I'll close this but let's keep our ears open in case we hear / see anything else from users running Windows 7.
