### ISSUE TITLE
right-click editor menu is outside primary window

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#2822]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.650
    OS Version      : macOS 10.13.4
    R Version       : 3.4.3

### Steps to reproduce the problem

Control-click on text in the editor window. The cut/copy/paste/select-all window is at the top of the display and outside the RStudio window

### Describe the problem in detail

The  problem happens with and without a text selection.

![screen shot 2018-05-21 at 1 23 10 pm](https://user-images.githubusercontent.com/362187/40320677-79b42408-5cfa-11e8-81d7-e157443fd996.png)
![screen shot 2018-05-21 at 1 23 20 pm](https://user-images.githubusercontent.com/362187/40320678-79c86792-5cfa-11e8-9e97-3f9e89420469.png)

### Describe the behavior you expected

Expected the menu item at the cursor location.

**Comment by ronblum** [comment]
@aronatkins I'm unable to reproduce this on both Sierra and High Sierra. Stab in the dark: Does it make a difference if you view the IDE on an external screen vs. the laptop?

**Comment by aronatkins** [comment]
I'm not seeing this any more with 1.2.680.
