### ISSUE TITLE
One-line R Chunk with No Assignment Causes Client Exception

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#2823]
### System details

    RStudio Edition : Server Pro
    RStudio Version : 1.2.x (latest master)
    OS Version: Linux (Ubuntu 14.04) 
    R Version: 3.4 

### Steps to reproduce the problem
In an `Rmd` file, create an R chunk with one line that does not assign any variables, such as:

```
```{r}
5+5
.```
```

Press the button to execute the thunk, and observe the error logs. You will see the following exception, and the chunk output will not be displayed:

```
May 21 15:57:11 ubuntu rserver[94201]: CLIENT EXCEPTION (rsession-kfeinauer): (TypeError) : Cannot read property 'row' of null;|||org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetScopeHelper.java#105::getSweaveChunkInnerRange|||org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#4856::execute|||org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#4845::executeSweaveChunk|||org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#4621::executeChunk|||org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUi.java#118::runChunk|||org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextToolbar.java#142::onBrowserEvent|||com/google/gwt/user/client/DOM.java#1415::dispatchEvent|||com/google/gwt/user/client/impl/DOMImplStandard.java#312::dispatchEvent|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||Client-ID: fd17fd9d-b2d6-4e5e-857e-8904580b73dd|||User-Agent: Mozilla/5.0 (X11  Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
```

If you modify the chunk as follows, it will work correctly:

```
```{r}
x <- 5+5
.```
```

Stranger yet, when you now modify the working chunk to remove the assignment to get the chunk equal to what you started with, it works, and will render correctly with no exception!

```
```{r}
5+5
.```
```

### Describe the behavior you expected

The original one-line chunk should execute and render properly, and there should be no exception.

**Comment by jmcphers** [comment]
Does not repro any more in RStudio 1.3.700.

![image](https://user-images.githubusercontent.com/470418/71700307-79bd5c80-2d78-11ea-8dbb-ed12aecd88e6.png)
