### ISSUE TITLE
Terminal extremely slow to accept key entries

### ISSUE THREAD

**Issue by sudevschiz** [rstudio/rstudio#2826]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.383
    OS Version      : RHEL 3.10.0-514.26.2.el7.x86_64
    R Version       : R 3.4.1

### Steps to reproduce the problem
Start a new terminal.
Just start entering comments into it.
There is a significant delay for key entries to show up in the UI.

### Describe the problem in detail
Delay is experienced in both Firefox and Chrome. It's slightly more severe in Firefox. 

Terminal diagnostics below : 

### Describe the behavior you expected

1. The output of sessionInfo() 

> > sessionInfo()
> R version 3.4.1 (2017-06-30)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
>  [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
>  [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
>  [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
>  [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
> [11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] wordcloud_2.5          qdap_2.2.5             RColorBrewer_1.1-2    
>  [4] qdapTools_1.3.3        qdapRegex_0.7.2        qdapDictionaries_1.0.6
>  [7] tm_0.7-1               NLP_0.1-10             textstem_0.1.2        
> [10] dplyr_0.7.2            data.table_1.10.4      coreNLP_0.4-2         
> [13] -----------        readxl_1.0.0          
> 
> loaded via a namespace (and not attached):
>  [1] gtools_3.5.0        venneuler_1.1-0     slam_0.1-40        
>  [4] reshape2_1.4.2      rJava_0.9-8         ROAuth_0.9.6       
>  [7] lattice_0.20-35     reports_0.1.4       colorspace_1.3-2   
> [10] yaml_2.1.14         chron_2.3-50        XML_3.98-1.9       
> [13] rlang_0.2.0         glue_1.1.1          bindrcpp_0.2       
> [16] bindr_0.1           plyr_1.8.4          stringr_1.3.0      
> [19] munsell_0.4.3       gtable_0.2.0        cellranger_1.1.0   
> [22] gender_0.5.1        parallel_3.4.1      xlsxjars_0.6.1     
> [25] Rcpp_0.12.12        scales_0.4.1        gdata_2.18.0       
> [28] plotrix_3.6-5       xlsx_0.5.7          openNLPdata_1.5.3-2
> [31] gridExtra_2.2.1     ggplot2_2.2.1       digest_0.6.12      
> [34] stringi_1.1.6       grid_3.4.1          tools_3.4.1        
> [37] bitops_1.0-6        magrittr_1.5        arules_1.5-2       
> [40] RCurl_1.95-4.8      lazyeval_0.2.0      tibble_1.3.3       
> [43] pkgconfig_2.0.1     Matrix_1.2-10       assertthat_0.2.0   
> [46] openNLP_0.2-6       R6_2.2.2            igraph_1.1.2       
> [49] compiler_3.4.1

2. The R code in question
3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

> 
> Global Terminal Information
> ---------------------------
> Loaded TerminalSessions: 1
> Handle: '21CE2ACA' Caption: 'Terminal 1'
> 
> Terminal List Count: 3
> Handle: '21CE2ACA' Caption: 'Terminal 1' Session Created: true
> Handle: 'D3DF45E9' Caption: 'Terminal 2' Session Created: false
> Handle: 'EE2D3A31' Caption: 'Terminal 3' Session Created: false
> 
> Current Terminal Session Information
> ------------------------------------
> Caption:     'Terminal 1'
> Title:       '/home'
> Cols x Rows  '82 x 8'
> Shell:       'Bash'
> Handle:      '21CE2ACA'
> Sequence:    '1'
> Restarted:   'false
> Busy:        'true'
> Exit Code:   'null'
> Full screen: 'client=false/server=false'
> Zombie:      'false'
> Track Env    'true'
> Local-echo:  'true'
> Working Dir: '/home'
> Interactive: 'Always'
> WebSockets:  'true'
> Typing lag:  '477ms'
> 
> System Information
> ------------------
> Desktop:    'false'
> Platform:   'Windows'
> Browser:    'Firefox'
> 
> Connection Information
> ----------------------
> 2018/5/22 11:52:22: Connected with RPC
> 
> Local-echo Match Failures
> -------------------------
> <none>
>

**Comment by gtritchie** [comment]
The likely reason is that the terminal is not using websockets (this is shown by the final bit of the Terminal diagnostics: `Connected with RPC`.

WebSockets can be turned on via Tools / Global Options / Terminal. You must close existing terminals and start new ones. WebSockets are on by default, so they have been turned off for some reason; it is _possible_ they do not work in your environment.

![2018-05-22_09-38-21](https://user-images.githubusercontent.com/10569626/40376798-260e99be-5da4-11e8-8a86-14fbcb58c3cf.png)

**Comment by sudevschiz** [comment]
Thanks for looking into this.

I checked, but the WebSockets option seems to be turned on in my machine. It's also visible in the diagnostics.

```
Interactive: 'Always'
WebSockets: 'true'
Typing lag: '477ms'
```

Any clue as to why it would still use RPC for connection?

**Comment by jmcphers** [comment]
Haven't heard back from you in over a year, so closing.
