### ISSUE TITLE
Update to Qt 5.11

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2830]
Qt 5.11 was released today.

http://blog.qt.io/blog/2018/05/22/qt-5-11-released/

There are a number of issues in 5.10.1 (our current release) which we know or suspect will be fixed in 5.11. (5.12 is the next LTS release, but won't come out until November.)

Also useful:

>  we now support embedded DevTools without requiring the use of a separate browser

**Comment by mingwandroid** [comment]
Will you still support Qt 5.9 LTS in the source here?

**Comment by jmcphers** [comment]
No, we don't plan to. 5.9 has a number of bugs that affect RStudio's use case (copy/paste doesn't work reliably on macOS with QtWebEngine, etc.), which is what motivated the update to 5.10.

**Comment by mingwandroid** [comment]
Ok thanks for the heads up. A backporting patches I shall go!
