### ISSUE TITLE
Use openssl R package to generate RSA keypairs

### ISSUE THREAD

**Issue by jeroen** [rstudio/rstudio#2832]
A windows rstudio user complained that the `Create RSA key` button (under Git/SVN in global options)  gives an error that the `ssh-keygen` executable was not found. 

Alternatively you can generate an RSA keypair in R. Perhaps that is easier than the 

```r
library(openssl)
key <- rsa_keygen()
write_pem(key, "~/../.ssh/id_rsa")
write_ssh(key$pubkey, "~/../.ssh/id_rsa.pub")
```

This does not require any command line tools.

**Comment by jeroen** [comment]
I think it was @maurolepore who showed me this problem.

**Comment by maurolepore** [comment]
I'm using RStudio Desktop Version 1.1.447

**Comment by ronblum** [comment]
Is Git's `bin` directory in the path, so that `ssh-keygen` can  be found? See https://stackoverflow.com/questions/11771378/ssh-keygen-is-not-recognized-as-an-internal-or-external-command

**Comment by maurolepore** [comment]
Thanks @ronblum for loooking into this!

I don't fully understand what "setting a path" means (Where should I set it? How? What path?). I seem to lack a mental model that makes me see blurry something you see clearly. The key I have now works, but I fail to create a new one from rstudio:

![image](https://user-images.githubusercontent.com/5856545/49700557-31039600-fbae-11e8-88b9-ecc1a32296af.png)

Here is some info that I hope will help you understand my context:

* RStudio Version 1.1.456
* Windows 10 Enterprise
* The keys are stored in C:\Users\LeporeM\.ssh

![image](https://user-images.githubusercontent.com/5856545/49700483-3f04e700-fbad-11e8-92ae-461e7b9f4c06.png)

* Git is installed in C:\Users\LeporeM\AppData\Local\Programs\Git\bin

![image](https://user-images.githubusercontent.com/5856545/49700515-9c993380-fbad-11e8-93df-7797cfc4da65.png)

* .Renviron has this line:
```
PATH="C:\Rtools\bin;${PATH}"
```
