### ISSUE TITLE
Rstudio redirects to localhost/auth-sign-in

### ISSUE THREAD

**Issue by Rayv1** [rstudio/rstudio#2834]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.447
    OS Version      : Ubuntu 16.04.4 LTS
    R Version       :  3.4.4

We using the rstudio-server with a nginx proxy-server. The Problem is, when calling the url of rstudio e.g. https://example.com/rstudio/ i will be redirected to https://localhost:8787/auth-sign-in. If if call the url e.g. https://example.com/rstudio/auth-sign-in i get the login page and are able to login. After submitting the Credentials, i will be redirected to https://localhost:8787/auth-sign-in again. But now when iam calling the URL https://example.com/rstudio, iam logged in and everything works fine.
The logout shows the same behavior and redirects to https://localhost:8787/auth-sign-in.

Our vhost Configuration File looks like the example here https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name  xxxx;
    root         /usr/share/nginx/vhosts/xxxx/html;

    include /etc/nginx/default.d/*.conf;

    access_log  /var/log/nginx/sxxxx/access.log  main;

    ssl_certificate /etc/nginx/ssl/appsrv.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

### Timeouts:###
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
###
### HARDENING: Try if requested file exists, if not try if requested directory
###            exists, if not serve index.html
    location / {
     try_files $uri $uri/ /index.html;
    }
    location /shiny/ {
      # Basic Authorization
      #auth_basic           "Login required";
      #auth_basic_user_file /etc/nginx/vhost.d/htpasswd;

      proxy_pass http://127.0.0.1:3838/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      # Make your Shiny apps work with and without trailing slashes
      rewrite ^(/shiny/[^/]+)$ $1/ permanent;
    }
    location /rstudio/ {
      rewrite ^/rstudio/(.*)$ /$1 break;
      proxy_pass http://localhost:8787;
      proxy_redirect http://localhost:8787/ $scheme://$host/rstudio/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 20d;
    }
}

server {
    listen 80;
    server_name xxxx;
    include /etc/nginx/default.d/*.conf;

### HARDENING: Alwys send the user to the https site.
    return 302 https://xxxx$request_uri;
}
```
Any Ideas?

**Comment by jmcphers** [comment]
This forum is for RStudio product bugs; for help configuring RStudio Server, you should post a question on the community forum:

https://community.rstudio.com/c/r-admin

Briefly however I suspect that you may need to `proxy_pass` the Host header.

https://serverfault.com/questions/598202/make-nginx-to-pass-hostname-of-the-upstream-when-reverseproxying

**Comment by 724399396** [comment]
@Rayv1 i have same issue, how would you solve this.

**Comment by Rayv1** [comment]
Hi,
it was a Problem with our Loadbalancer. We configured our Loadbalancer to use HTTP(S) Mode, but then it didnt work with Websockets.

We configured our Loadbalancer to use TCP instead and then in worked fine!

**Comment by gregoster** [comment]
I think the bug here is that the redirects to/from auth-sign-in/auth-sign-out don't go to where one would expect.  People use HTTP_REFERER and url rewrites in apache to get it to work, but I couldn't get that to work in nginx.  What did work for me was the following in the 'server' section of the nginx config:

 `       rewrite ^/auth-sign-in(.*) "$scheme://$server_name/rstudio/auth-sign-in$1?appUri=%2Frstudio";
        rewrite ^/auth-sign-out(.*) "$scheme://$server_name/rstudio/auth-sign-out$1?appUri=%2Frstudio";
`
Took only a few minutes of source-code sleuthing to hit upon appUri, and once that was set to what I needed, it worked flawlessly.  I too have RStudio living at /rstudio , but also have JupyterLab at /jupyterlab , etc. 

Just adding this for the next person who struggles with trying to configure RStudio with nginx and using custom URLs.

**Comment by labkey-jony** [comment]
@Rayv1 What kind of load balancer do you have? I'm having this same problem on AWS using EC2 running Tomcat and my EC2 instance is setup with a VPC and also using an Application Load Balancer.

**Comment by alasdairtran** [comment]
I had the same issue using HTTPS mode and fixed it by changing

```
proxy_redirect http://localhost:8787/ $scheme://$host/rstudio/;
```

to

```
proxy_redirect https://localhost:8787/ $scheme://$host/rstudio/;
```

**Comment by nikhilwbhatia** [comment]
@alasdairtran This was the fix I needed as well, the internal Rstudio redirect that needs to be proxied is https not http. Thanks for posting!

**Comment by GitHunter0** [comment]
> 
> 
> I think the bug here is that the redirects to/from auth-sign-in/auth-sign-out don't go to where one would expect. People use HTTP_REFERER and url rewrites in apache to get it to work, but I couldn't get that to work in nginx. What did work for me was the following in the 'server' section of the nginx config:
> 
> ` rewrite ^/auth-sign-in(.*) "$scheme://$server_name/rstudio/auth-sign-in$1?appUri=%2Frstudio"; rewrite ^/auth-sign-out(.*) "$scheme://$server_name/rstudio/auth-sign-out$1?appUri=%2Frstudio";`
> Took only a few minutes of source-code sleuthing to hit upon appUri, and once that was set to what I needed, it worked flawlessly. I too have RStudio living at /rstudio , but also have JupyterLab at /jupyterlab , etc.
> 
> Just adding this for the next person who struggles with trying to configure RStudio with nginx and using custom URLs.

@gregoster , You are a hero. I could not find this information anywhere, it was driving me insane!

No matter what I did, I was getting "forbidden" or "Error 404 - Not Found". 

That should definitively be on the official page.

Thanks a lot for sharing

**Comment by GitHunter0** [comment]
@gregoster , I'm just having problem with Firefox (in Chrome and Brave it works fine). It appears:
```
 Error 521 Ray ID: 61f994e88885f5e7 • 2021-02-10 23:24:06 UTC
Web server is down
Host Error
```
Do you have an idea why it happens just in Firefox and how to solve it?
