### ISSUE TITLE
[Linux] Slow to switch to RStudio from another application

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#2835]
In the linux version (running KDE 5.12 on debian sid), there is a delay when switching from another application to rstudio, i.e. as soon as the rstudio window comes to focus, it freezes for a second or so before starting to work.

Steps to reproduce:
-Launch Rstudio and have its window on focus
-Launch some other application (e.g. go to the applications menu and click anything there)
-Switch to that other application (e.g. click its icon in the task manager)
-Switch back to Rstudio.

Expected behavior:
-Should switch to Rstudio window and the UI should be responsive instantly. Hovering the mouse around icons or toolbars while the application window is not active should also change the mouse shape.

Actual behavior:
-Application freezes for like a second before becoming responsive again. Hovering the mouse through icons such as the close button on tabs doesn't change the cursor shape when the Rstudio window is not on focus.

Rstudio version: 1.1.447

**Comment by ronblum** [comment]
@david-cortes Is this still an issue? Are you able to try out the latest development dailies at https://dailies.rstudio.com/ and see if the problem still occurs?

**Comment by david-cortes** [comment]
For the moment, I unfortunately don't have the same setup, nor the opportunity to use RStudio daily, so I won't be able to tell if it's fixed until a couple months. I guess you can close the issue and I will reopen it if it persists.

In terms of how to reproduce it, it happens mostly after the console is full of history and/or there is something that would make RStudio (not only rsession) use more resources than in a blank start.
