### ISSUE TITLE
Enhancement: Display <filename> - <filepath> in "Show in new window" source editor

### ISSUE THREAD

**Issue by avila** [rstudio/rstudio#2840]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Linux Ubuntu 18.04 LTS
    R Version       : 3.4.4 (2018-03-15)

### Steps to reproduce the problem

Open multiple windows as in "Show in new window".

### Describe the problem in detail

It is not possible to see the actual filename of the source file, only the filepath (if this is long enough)

![image](https://user-images.githubusercontent.com/31955632/40449322-8dd1244e-5eae-11e8-9d43-d662a0bc1429.png)

### Describe the behavior you expected

It would be nice to see the filename first, as in 

`<filename> - <filepath> - RStudio Source Editor`

**Comment by jmcphers** [comment]
This is currently tracked in https://github.com/rstudio/rstudio/issues/2427.
