### ISSUE TITLE
.rs.api.restartSession() should allow for restart with 'clean' session

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2841]
Currently, this API function restarts R through the suspend/resume code path, which implies things like the global environment + search path are saved and restored. We should extend this to allow for restarting R and getting a 'clean' session.

cc: https://github.com/rstudio/rstudioapi/issues/95

**Comment by vnijs** [comment]
Any updates on this @kevinushey? I noticed a few related issues on this topic as well (e.g., https://github.com/rstudio/rstudioapi/issues/111)

**Comment by pdeffebach** [comment]
This was also unexpected behavior for me. I thought it would be a good alternative to `rm(list = ls())`, I just want to clear everything out and restart a new session with no persistent variables.

**Comment by buchgr** [comment]
We would also be very interested in this feature. Is there a workaround available?

**Comment by pdeffebach** [comment]
yes I figured this out two days ago actually. The key is that `restartSession()` simply uses the default parameters that come from the `R` command when opening. So if you have the following in your `.bash_profile` 

```
alias R='R --no-save --no-restore-data'
```

then it will all work. 

I think a problem is a misreading of [this blog post](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/). Changing the `bash_profile` and using the restart button are connected. You need the alias for it to work properly.

**Comment by vnijs** [comment]
It doesn't seem like this is resolved and I think it would be very useful to keep the issue open. Thanks

**Comment by colearendt** [comment]
Hi stale bot! I missed you!

**Comment by ronblum** [comment]
@kevinushey I don't think that the state is getting reset.

```
> x <- 1
> .rs.api.restartSession(clean = TRUE)
> x
[1] 1
> 
> rstudioapi::restartSession(clean = TRUE)
> x
[1] 1
```

The Environment Pane does a quick refresh and the little "Restarting R" message appears, though.

**Comment by kevinushey** [comment]
It looks like you're right! I'll see what's going on and fix this up.

**Comment by kevinushey** [comment]
Should be fixed up in the next builds. For testing, here's some examples:

```
library(dplyr)
isNamespaceLoaded("dplyr")
.rs.api.restartSession(clean = FALSE)
isNamespaceLoaded("dplyr")
```

After restart, you should see:

```
> isNamespaceLoaded("dplyr")
[1] TRUE
```

Compare with a clean restart:

```
library(dplyr)
isNamespaceLoaded("dplyr")
.rs.api.restartSession(clean = TRUE)
isNamespaceLoaded("dplyr")
```

You should see:

```
> isNamespaceLoaded("dplyr")
[1] FALSE
```

**Comment by ronblum** [comment]
Success! Verified in RStudio Desktop 2024.04.0-daily+663 on Windows 11. Also checked that both the Environment Pane (values) and Packages Pane (checkmarks) are refreshed.
