### ISSUE TITLE
Blank, non-functional terminal

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rstudio#2849]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.650
    OS Version      :  x86_64-w64-mingw32/x64 (64-bit)
    R Version       :  3.5.0 (2018-04-23)

### Describe the problem in detail
My Rstudio terminal keeps in blank and does not react to any operation. I do see a "terminal 2" comes out, though if I create a new terminal by Tool > Terminal > New Terminal rather than clicking options in the terminal tab or shortcut). Originally I set it to show the git bash, and now the git function works from the "Git" tab but terminal shows nothing.

Terminal diagnosis:
```r
Global Terminal Information
---------------------------
Loaded TerminalSessions: 0

Terminal List Count: 2
Handle: 'EF4D24C9' Caption: 'Terminal 1' Session Created: true
Handle: 'BCE06995' Caption: 'Terminal 2' Session Created: true
```

Session Information:

```r
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0
```

**Comment by jmcphers** [comment]
This sounds quite a lot like https://github.com/rstudio/rstudio/issues/2817. Does the daily build (658) work for you?

https://dailies.rstudio.com/

**Comment by sammo3182** [comment]
I tried 1.2.660. The problem is gone. Thanks a lot!
