### ISSUE TITLE
Save image from Plot zoom window didn't work 

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#2850]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.1.453
    OS Version      : Windows >= 8 x64 (build 9200)
    R Version       : 3.5.0 (2018-04-23)

### Steps to reproduce the problem

* Run this code (or any code that generates plot)

```
library(magrittr)
library(ggplot2)

iris %>% ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species)) + 
  geom_point()

```

* Click on Zoom button on the plot window  

* Right click then Save image

![snap_001](https://user-images.githubusercontent.com/6590141/40497427-fec70876-5f30-11e8-89c3-6297695b9dea.PNG)

* Save 

![snap_002](https://user-images.githubusercontent.com/6590141/40497444-0cd1ac3c-5f31-11e8-8b28-8ee0e0a9835f.PNG)

### Describe the problem in detail

The suggested file name didn't have an extension plus there isn't any file generated after clicking on `Save`

### Describe the behavior you expected

The file should be generated in the chosen folder with `.png` extension.

**Comment by jmcphers** [comment]
This is fixed in the RStudio preview:

https://www.rstudio.com/products/rstudio/download/preview/

And by "fixed" I mean only that "save image" has been removed (use the Export menu to save an image).

**Comment by tungmilan** [comment]
Thanks!
