### ISSUE TITLE
RStudio 1.2.637 not compatible with libssl from Debian Buster (10)

### ISSUE THREAD

**Issue by balwierz** [rstudio/rstudio#2853]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.637
    OS Version      :  Debian Buster
    R Version       : 3.4.4

### Steps to reproduce the problem
execute rstudio

### Describe the problem in detail
Rstudio on Debian Buster (rstudio-1.2.637-amd64.deb) displays a standard chromium "connection refused" message.

```
This site can’t be reached

127.0.0.1 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

Console output:
```
"Uncaught TypeError: Cannot read property 'notifyRCrashed' of undefined"
```

/usr/bin/rstudio --run-diagnostics
```
R session launched, attempting to connect on port 36065...
/usr/lib/rstudio/bin/rsession: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Connected to R session, attempting to initialize...
```

**Comment by jmcphers** [comment]
We don't currently support the development releases of Debian; Buster includes a libssl that is not ABI compatible with the one RStudio is built against.

**Comment by balwierz** [comment]
That's a pity. We are running Debian testing in our lab to conveniently stay up to date with many bioinformatics tools without the need of either compiling and updating manually, or staying behind a couple of months with an old version.
Debian follows a 3-step stable/testing/unstable system. We are running the mid one on our cluster.(not web servers) as a compromise between stability and update lag.

**Comment by jmcphers** [comment]
I don't have a VM with Buster handy, but we do have a new Stretch-based desktop build that will become available in the next preview release (ETA next week), which may work for you.

**Comment by jmcphers** [comment]
And if you don't want to wait for the preview, here's the first daily build from Stretch:

https://dailies.rstudio.com/rstudio/oss/debian9/x86_64/

**Comment by balwierz** [comment]
Thanks. This one works. All Stretch builds used to work for me before.

I think the confusion is that the download page for 1.2.637 says simply Ubuntu/Debian (64-bit) what implicitly means any Ubuntu or Debian version should work.
