### ISSUE TITLE
Default working directory option not setting working directory correctly

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2861]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.637, 1.2.637-1, and 1.1.447
    OS Version      : RHEL 7.3

### Steps to reproduce the problem
Open Source Server:
1. Log in with user and default settings where home directory is listed as default working directory
2. Tools -> Options -> General -> Default working directory (when not in a project). Set to another directory where the user has access. (used /test directory)
3. Session -> Quit Session...
4. Start New Session
5. Observe Files Pane is in the correct directory but getwd() returns the user's home directory

RStudio Server Pro:
1. Log in with user and default settings where home directory is listed as default working directory
2. Tools -> Options -> General -> Default working directory (when not in a project). Set to another directory where the user has access. (used /test directory)
3. Session -> Quit Session...
4. On home page select New Session
5. Observe Files Pane is in home directory and getwd() returns home directory
Note: If I open and close a project, the Files pane will update with the correct directory.

### Describe the behavior you expected
After changing Default working directory and creating a new session, the working directory would be changed to the selected directory and the Files pane would also be changed to that directory.

**Comment by kfeinauer** [comment]
@dfalty I am investigating this now, but I am getting different results (wrong results, but not quite the same as you). Can you reproduce this issue on your machine and then when opening the new session with the new working dir, include the `client_init` RPC response (captured from the network tools wtihin Chrome)? This will let me see what initial state your session is being populated with.

**Comment by dfalty** [comment]
@kfeinauer I retested on a different "clean" box and I'm seeing a little bit different results. On this RSP instance, I get the correct working directory in the console but the Files pane is in Home still. Is this what you are seeing? I'll try to find the old box I was working on to see what could be different. Tested on 1.2.666-2 RHEL 7.3

**Comment by kfeinauer** [comment]
That is the behavior I am seeing. I believe I have a fix, so you can hold off on the output for now.

**Comment by dfalty** [comment]
Verified fixed 1.2.1310-1
