### ISSUE TITLE
RStudio only displays a menu that doesn't work

### ISSUE THREAD

**Issue by PetersK20** [rstudio/rstudio#2863]
### System details

    RStudio Edition : desktop
    RStudio Version : RStudio-1.1.453 windows
    R Version      : R 3.5.0

### Steps to reproduce the problem
    I just downloaded R and RStudio, and this problem occurred the first time I used the program.  I have not written any R code.
### Describe the problem in detail
    RStudio will run, but it only display a menu that does not work.  The rest of the screen is a white panel that is below the menu.
![image](https://user-images.githubusercontent.com/39628566/40553624-21d251be-5ff8-11e8-88c2-b83d6d5a11a8.png)

**This is the log output:**

Attempting to launch R session...
  R_HOME=C:\PROGRA~1\R
  PATH=C:\Program Files\R\bin\x64;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_131\bin\java.exe;C:\Users\Kyle Peters\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Sophos\Sophos SSL VPN Client\bin
  HOME=C:\Program Files\Java\jre1.8.0_131\bin\javaw.exe

R session launched, attempting to connect on port 35065...
25 May 2018 15:29:36 [rsession-Kyle Peters] ERROR system error 267 (The directory name is invalid) [path=C:/Program Files/Java/jre1.8.0_131/bin/javaw.exe]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::makeCurrentPath(bool) const C:\Users\Administrator\rstudio\src\cpp\core\FilePath.cpp:1070; LOGGED FROM: int main(int, char* const*) C:\Users\Administrator\rstudio\src\cpp\session\SessionMain.cpp:1737

Connected to R session, attempting to initialize...

**A more concise version of the error:** 

ERROR system error 267 (The directory name is invalid) [path=C:/Program Files/Java/jre1.8.0_131/bin/javaw.exe]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::makeCurrentPath(bool) const C:\Users\Administrator\rstudio\src\cpp\core\FilePath.cpp:1070; LOGGED FROM: int main(int, char* const*) C:\Users\Administrator\rstudio\src\cpp\session\SessionMain.cpp:1737
 

Thank you for your help

**Comment by ronblum** [comment]
@PetersK20 Which version of Windows are you using?

**Comment by jmcphers** [comment]
The problem is probably here:

    HOME=C:\Program Files\Java\jre1.8.0_131\bin\javaw.exe

You shouldn't set HOME to a file. You need to edit your system and/or user environment variables to remove this value for HOME.

**Comment by PetersK20** [comment]
Thanks for the tip.  This solved it.
