### ISSUE TITLE
Clear Knitr Cache button not working when changing cache.path

### ISSUE THREAD

**Issue by BodoBurger** [rstudio/rstudio#2869]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Ubuntu 18.04 x64
    R Version       : 3.4.4

### Steps to reproduce the problem

Code for RMarkdown-file to reproduce the problem:

<pre>
---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, cache.path = "custom_folder/")
```

```{r}
set.seed(123)
x1 = runif(20)
head(x1)
```
</pre>

### Describe the problem in detail

The "Clear Knitr Cache" button does not work when you change **cache.path**.

R console output indicates that it tries to delete the default cache path ("file_name_cache/") that does not exist if you change **cache.path**.

**Comment by ronblum** [comment]
Reproduced on Windows Desktop 1.2.672.

**Comment by kevinushey** [comment]
dev node: the associated routine lives here.

https://github.com/rstudio/rstudio/blob/acbe4fc56a0a8bb6840cf46d359fdc5da0ae5d96/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L5984-L6026

We could try parsing the chunk options to infer the cache path, using e.g. the RMarkdownChunkHeaderParser.

**Comment by ronblum** [comment]
Reopening, as this is still and issue in
- RStudio Desktop 1.4.1103 on MacOS 11.2.1
- RStudio Desktop 1.4.1639 on MacOS 11.3
- RStudio Server 1.4.1639 on Ubuntu 20.04 using Chrome on MacOS 11.3
