### ISSUE TITLE
Dual-screen scaling problem

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#2872]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.669
    OS Version      : Windows 10 Pro
    R Version       : 3.5.0

### Steps to reproduce the problem

Use RStudio 1.2.669 on a dual-monitor setup: HP Pavilion x360 laptop + DELL ST2410 24" monitor. 

### Describe the problem in detail

RStudio GUI became way too big on my laptop screen

- On laptop (too big)
![snap_004](https://user-images.githubusercontent.com/6590141/40625834-8e8b590e-6269-11e8-8d78-e60ea3b33aac.PNG)
![snap_006](https://user-images.githubusercontent.com/6590141/40625835-8efcb2d4-6269-11e8-8079-cfcbad89633e.PNG)

- On Dell monitor (ok)
![snap_003](https://user-images.githubusercontent.com/6590141/40625844-a0258f40-6269-11e8-9268-e80dcbb6dbff.PNG)

- Windows display settings
![snap_005](https://user-images.githubusercontent.com/6590141/40625849-acf748f8-6269-11e8-9d9b-76fbc0c1dfa1.PNG)

### Describe the behavior you expected

Should scale nicely depending on screen size. I didn't have this problem on v1.1.xxx

Thanks!

**Comment by bri-b-king** [comment]
I believe I just found a workaround to this issue:
- Open Rstudio
- Right click on Rstudio icon in desktop tray, then right click again on Rstudio in the popup menu, and click on Properties
![image](https://user-images.githubusercontent.com/47395964/52361644-28331300-29eb-11e9-9737-996bd4d0d2f8.png)
- Go to the Compatibility tab, and click on Change high DPI settings
![image](https://user-images.githubusercontent.com/47395964/52361723-5ca6cf00-29eb-11e9-8f9a-2d389e3a6f20.png)
- Click on Change high DPI settings in the new menu
![image](https://user-images.githubusercontent.com/47395964/52361776-7cd68e00-29eb-11e9-92da-6d17c233c0a0.png)
- Toggle the High DPI scaling override, and select System from the drop down menu:
![image](https://user-images.githubusercontent.com/47395964/52361837-a1cb0100-29eb-11e9-94b6-e11fa59be865.png)
- Click ok, Apply, Ok, OK, then close Rstudio and restart.

This worked for me, I hope it works for you! I now have similar sized text on both my Lenovo Yoga and my Samsung tv monitor. Makes it so much better for dual monitor usage.

**Comment by poweroftheweakness** [comment]
Oh man, thank you very much for your solution!!! Works perfectly.

**Comment by gferrsilva** [comment]
Thank you! It has fixed the problem here!
Cheers

**Comment by ShengdiWang** [comment]
Thanks for the solution, works perfect!

**Comment by maxim-h** [comment]
I had a similar issue on Linux where Rstudio would be the only app that did not scale properly between the HiDPI laptop monitor and a secondary one. 
Following the advice from https://wiki.archlinux.org/index.php/HiDPI#Qt_5 setting this variable helped me 
`export QT_SCREEN_SCALE_FACTORS="1;2"`

just posting it here because I would always end up in this thread while googling the problem)

**Comment by brewkeeper909** [comment]
This is great! Only issue I have here now is if I drag the window from the higher resolution external monitor into the lower resolution main laptop screen, it isn't as crisp - its a tad blurry. Is this something you have to just deal with, or is that also fixable?
