### ISSUE TITLE
Enabling function keys on MacBook touch bar for RStudio does not work

### ISSUE THREAD

**Issue by uhkeller** [rstudio/rstudio#2874]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.637
    OS Version      : MacOS 10.13.4
    R Version       : 3.5.0

### Steps to reproduce the problem
On a MacBook with a touch bar, in the MacOS system preferences, under "Keyboard", click "Shortcuts", then "Function Keys", and add RStudio to the list of applications. Then open RStudio.

### Describe the problem in detail
When an RStudio window is in the foreground, the touch bar continues to show the default (virtual) keys, instead of the function keys (F1-F12). With other applications, this works as expected.

**Comment by ronblum** [comment]
Reproduced in 1.2.679-1 and 1.1.453 (and others). However, when switching to another application and then switching back to RStudio, the function keys show up as expected.

**Comment by uhkeller** [comment]
Thanks for checking!

> However, when switching to another application and then switching back to RStudio, the function keys show up as expected.

This is not true on my machine. The function keys never show up, even if I switch to another application that shows the function keys and then back to RStudio.

**Comment by ateucher** [comment]
FWIW this is working fine for me on the daily builds, though I am still on Sierra, so that may make a difference?

    RStudio Edition : Desktop
    RStudio Version : 1.2.688
    OS Version      :  MacOS 10.12.6
    R Version       :  3.4.4

**Comment by uhkeller** [comment]
It works for me now with macOS 10.14.1 and RStudio 1.2.1114. Not sure which update (macOS or RStudio) fixed it.

**Comment by gtritchie** [comment]
I am no longer able to repro this, works fine with RStudio 1.2.1555 on macOS 10.14.5.
