### ISSUE TITLE
askForSecret fails on Linux server if keyring package is installed

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2876]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.666-2
    OS Version      : Ubuntu 16.04, RedHat 7.4
    R Version       : 3.5.0

### Steps to reproduce the problem

1. First make sure that the `keyring` package is installed
2. `rstudioapi::askForSecret(name = "my_password")`

### Describe the problem in detail

Returns an error instead of prompting for a password. This is before even attempting to save a password in a keyring.
> Error in default_backend()$list(service, keyring = keyring) :
    Backend does not implement 'list' 
In addition: Warning message: 
In default_backend_auto() :   
Selecting ‘env’ backend. Secrets are stored in environment variables

### Describe the behavior you expected

The user should be prompted for a password. If the `keyring` package is not installed, the secret dialog prompt pops up correctly (although the option to store in a keyring is grayed out). 

This is only a problem on Linux server: on Linux desktop—as well as MacOS and Windows desktop—this works fine.

**Comment by javierluraschi** [comment]
Fixed with https://github.com/r-lib/keyring/pull/58, to verify, use `devtools` to install `keyring`:

```
devtools::install_github("r-lib/keyring")
```
