### ISSUE TITLE
fails to stage with Git project

### ISSUE THREAD

**Issue by mgei** [rstudio/rstudio#2877]
### System details

    RStudio Edition : Desktop
    RStudio Version :   1.1.453
    OS Version      :  Windows 7
    R Version       :  3.4.1

### Problem
When working with Git projects on my Windows machine, I am often unable to stage changed files (unable to make the tick, trying with space-key or with mouse). I consequently cannot exit RStudio and I have to kill the process.

Workaround is to (after reopened RStudio) do it in the terminal with `git add -A` (as described here https://stackoverflow.com/questions/46246506/blogdown-git-and-rstudio-unable-to-stage-public-folder). Then it works again for some time. I cannot say when exactly it fails again, but it will.

### Other people having the same problem
I found similar issues until back from to 2013.
https://support.rstudio.com/hc/en-us/community/posts/200656917-Cannot-tick-the-stage-checkbox-of-modified-files-in-the-git-pane
https://support.rstudio.com/hc/en-us/community/posts/204728487--Stage-selection-does-not-work-

**Comment by HughParsonage** [comment]
I can reproduce:

1. Clone an git repository, empty but for a README.
2. Create a lot of files `for (i in 1:1e4) file.create(paste0(i, ".txt"))`
3. RStudio immediately runs very slowly if the Git tab is open
4. After clicking commit in the Git tab, RStudio takes a long time to reach the panel. (at least 10 mins, possibly never)

**Comment by jmcphers** [comment]
We've made a number of improvements to the way we call Git, so we're hopeful that this is addressed in a recent build. Please let us know if you're still seeing it in RStudio 1.2.5019 or newer!
