### ISSUE TITLE
default user interface font

### ISSUE THREAD

**Issue by p-neves** [rstudio/rstudio#2880]
Hi:

I think I'm missing a font on my system (please see attached screenshot), as the UI font is not what it used to be...

Which is the default font that rStudio uses on its UI?

![screenshot_20180529_210253_2](https://user-images.githubusercontent.com/16014958/40682697-68b3edba-6384-11e8-8fd9-6018ef06fc36.png)

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version      :  Linux
    R Version       :  3.5.0

Thanks in advance.

Pedro

**Comment by jmcphers** [comment]
Lucida Sans or DejaVu Sans.

https://github.com/rstudio/rstudio/blob/05d2b92184f61ce8d07239ca7995adfd3ba59342/src/cpp/desktop/DesktopOptions.cpp#L163

Does that help?

**Comment by jmcphers** [comment]
Does the preview release work for you?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by p-neves** [comment]
I've managed to fix it. There were some conflicts on the installed fonts on my system. I've sorted it out and all is good now.
Thanks for the attention.

Cheers:
Pedro

**Comment by jmcphers** [comment]
Great, thanks for updating and glad to hear it all worked out!

**Comment by ShurliAgati** [comment]
Hi,
I am having an issue with the dataviewer font. It's just stuck and only shows Greek letters. I am trying to get it sorted but no luck so far. Please see the following two posts:
[https://stackoverflow.com/questions/61765442/rstudio-font-family-stuck-on-deja-vu-sans/62886804#62886804](url)
[https://stackoverflow.com/questions/62791304/rstudio-data-viewer-showing-greek-characters-instead-of-english/62793081?noredirect=1#comment111070321_62793081](url)

Will appreciate your help!

Cheers,
