### ISSUE TITLE
Show data frame and list values in the data viewer

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2881]
## List columns today

Create a data frame with a column that itself contains data frames:

    df <- data.frame(x = 1:3)
    df$y <- list(data.frame(z = 1), data.frame(z = 3:1), data.frame(z = 1:10))
    
    View(df)
    View(df$y)

This results in the following display:

![image](https://user-images.githubusercontent.com/470418/40688123-c8c3eefe-6351-11e8-88b7-b95335b51798.png)

It's not possible to see what the actual values are using the data viewer (you need to manually invoke the object viewer). These kinds of list columns are increasingly produced by e.g. `tidyr::nest()` and other systems which generate structured data.

## Proposal

1. When processing a data frame for display, detect when a cell value is a non-scalar that would be best viewed in the data viewer or object viewer.
2. When displaying a data frame, draw the spreadsheet (data viewer) or magnifier (object explorer) icon next to these non-scalar cell values. 
3. When one of these icons is clicked, invoke the data viewer or object explorer on the value in the cell.

In an ideal world we'd have a more fluid tree-like explorer which could allow for easy composition of data/list views and other rich values, but the above will make a big difference. 

(Originally via conversation with @hadley)

**Comment by dfalty** [comment]
Verified on version 1.2.1090.
