### ISSUE TITLE
White scrollbars in dark theme on MacOS

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#2882]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.666-2
    OS Version      : MacOS 10.13.4
    R Version       : 3.5.0

### Steps to reproduce the problem
Use the RStudio IDE on an external monitor.

### Describe the problem in detail
When using the IDE with the dark theme on an external monitor the scroll bars _sometimes_ turn white. When this happens, text can become obscured if it is right against the scrollbar:

![scroll-bars-words-clipped](https://user-images.githubusercontent.com/10444878/40688647-1bfc0b60-635c-11e8-9322-901dbcd30c93.gif)

I've noticed this happen several times, although interestingly enough it doesn't happen every time. I'll add more information if I find specific steps that cause this to manifest itself.

**Comment by kevinushey** [comment]
I think this can happen if you scroll using a mousewheel while over the area where the scrollbar can appear. That is, attempting to scroll while the mouse cursor is positioned on the right edge of the editor surface can cause this.

Does that ring true in your case?

**Comment by blairj09** [comment]
I've upgraded to 1.2.672-1 and so far today I haven't noticed an issue. Scrolling with a mouse-wheel while directly over the scrollbar as described above did not cause any changes.

**Comment by kevinushey** [comment]
Glad to hear it, but I suspect the issue may pop up again in the future since we haven't tried to explicitly fix this recently. Let us know if you learn about anything else that seems to trigger this.

**Comment by blairj09** [comment]
Noticed this again today on RStudio Desktop Pro Version 1.2.1157.2. Interestingly enough, in this case the white scrollbars are persistent in every pane except the editor pane. In the editor pane, the scroll bar matches the dark editor theme until I mouse over it, at which point it turns white.

**Comment by jmcphers** [comment]
We haven't been able to repro this, and haven't had a report in over a year, so closing.

**Comment by mike-stn** [comment]
This issue still exists. Seems to appear sporadically but most of the time @kevinushey's repo works.
It would be really cool if you could tackle this again, as it's really annoying!

**Comment by MichaelJStein** [comment]
This happened for the first time without using an external monitor. 

RStudio Version:  2022.02.0
OS Version: macOS 12.2.1
R Version: 4.1.2

<img width="780" alt="Bildschirmfoto 2022-03-16 um 16 03 53" src="https://user-images.githubusercontent.com/77588215/158621399-3ffa9b99-f936-4bf0-9a5d-95f519223b5e.png">
