### ISSUE TITLE
RStudio is blank upon start, It is broken.

### ISSUE THREAD

**Issue by irshad001** [rstudio/rstudio#2885]
### System details

    RStudio Edition : 
    RStudio Version : rstudio-xenial-1.1.453-amd64
    OS Version      : Ubuntu 16.04 LTS
    R Version       : R version 3.4.4 (2018-03-15)

### Describe the problem in detail
RStudio was working fine in the morning. However, it has suddenly hung. And when I try to kill the process and reopened it. But it did not open. It is completely blank. I can see other windows in the transparent screen of Rstudio. My R is working fine. It never occured to me before. I uninstalled and re-installed both R and Rstudio as well but problem still persists. 

I have ran the diagnostics on my system, it produced a file and and output.

Using R script: /usr/bin/R

Attempting to launch R session...
  R_HOME=/usr/lib/R
  R_DOC_DIR=/usr/share/R/doc
  R_INCLUDE_DIR=/usr/share/R/include
  R_SHARE_DIR=/usr/share/R/share
  LD_LIBRARY_PATH=/usr/lib/R/lib:/usr/local/oracle/instantclient_11_2/::::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server:/usr/local/oracle/instantclient_11_2/:
  PATH=/home/irshad/bin:/home/irshad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
  HOME=/home/irshad

R session launched, attempting to connect on port 29984...

Connected to R session, attempting to initialize...

Successfully initialized R session.

Diagnostics report written to: /home/irshad/rstudio-diagnostics/diagnostics-report.txt

(nautilus:8246): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:8246): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:8246): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(nautilus:8246): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(nautilus:8246): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
QApplication::qAppName: Please instantiate the QApplication object first

file I am attaching here:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2053714/diagnostics-report.txt)

**Comment by jmcphers** [comment]
We haven't been able to reproduce this. Does resetting RStudio's state help?

https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
