### ISSUE TITLE
Generating a plot with "device = quartz" opens a little app that crashes R when closed

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2890]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.666, 1.1.453
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.5.0

### Steps to reproduce the problem

Take 1:
1. `options(device = "quartz")`
2. `plot(cars)`
    - Plot appears in its own window
    - Window has its own icon in the dock
    - Mini menu bar appears at top, including a mini version of the Apple icon
<img width="518" alt="mini_menu" src="https://user-images.githubusercontent.com/31009952/40745777-64decac8-6426-11e8-90e2-66c978e40a4c.png">

3. Close the dedicated plot window by clicking on the red X in the corner or `cmd-W`
    - Plot window goes away
    - Mini menu bar remains, including the mini Apple icon
    - Icon remains in dock
4. Right-click on icon in menu bar and choose `Quit`
    - Mini menu and dock icon correctly go away
    - R session crashes with "R Session Aborted" dialog box
5. Click `Start New Session`
   - Sometimes, message appears that "The site can't be reached" and "127.0.0.1 refused to connect." Clicking `Reload` is required.

### Describe the problem in detail

1. The plot opens as separate program with an extra Apple icon in the menu bar.
2. R crashes when the plot's stub app is fully quit.
3. The IDE sometimes has to be reloaded after a "127.0.0.1 refused" error.

### Describe the behavior you expected

When the mini-quartz app is quit, it shouldn't cause R to crash. In addition, it would be nice if the plot opened up as a window in RStudio instead of a mini quartz app, but even if it opens as a separate app, it shouldn't create a small Apple icon next to the larger Apple icon. 

Cf. Windows and Linux desktop which, when device is set to "windows" and "X11", open a separate window which can be closed successfully without a crash.

**Comment by jjallaire** [comment]
I think these are unfortunately day 1 bugs which we've never figured out how to fix.
