### ISSUE TITLE
Break points not working for alias due to copy-on-modify

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#2895]
It's nice that the debugging experience in RStudio (both Server and Desktop) are largely improved over the years. This issue addresses a small problem where the break points inside a function are not hit when its alias is called.

The steps to reproduce:

Create a new R source file with the following function

```r
p1 <- function(x, y) {
  a <- x + y
  b <- x - y
  a * b
}

p2 <- p1
```

Calling `debug(p1)` will make `p1` and `p2` both under debug mode, which is expected.

However, creating a breakpoint in RStudio editor inside `p1` (e.g. the first line of code of `p1`) will only modify `p1`'s body rather than both `p1` and `p2`. 

Now take a look at them:

```
> p1
Object with tracing code, class "functionWithTrace"
Original definition: 
function(x, y) {
  a <- x + y
  b <- x - y
  a * b
}

## (to see the tracing code, look at body(object))
> p2
function(x, y) {
  a <- x + y
  b <- x - y
  a * b
}
```

It seems that the injection of break points in function body is subject to copy-on-modify behavior, which is not so expected here and may cause some debugging hard to do.

For example, a series of functions are defined in a package but they are also registered into an environment. Only the functions in the environment will be actually called by package functions. If user create breakpoints in the original function, nothing will happen when the line of code is hit because their alias in the environment are not modified when breakpoints are created.

**Comment by ronblum** [comment]
@renkun-ken Thank you for noting this. We'll take a look at it as we continue development of RStudio.

**Comment by jmcphers** [comment]
There is no way for us to know what copies have been made of an object (that's all R internal state); in other words, given `p1`, there is no way for us to somehow figure out that `p2` exists and also needs a breakpoint set. 

I also think that it could confusing for some users to have breakpoints set on multiple copies of functions when they only acted on one copy. Of course, the behavior you describe is confusing for other reasons, but given the tradeoffs I don't think there's a reasonable path towards addressing this.
