### ISSUE TITLE
Connection Refused error page when trying to create a new project

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2896]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.666-1.2.675
    OS Version      : Mac 10.12.6
    R Version       : 3.5.0

### Steps to reproduce the problem
1. File -> New Project -> New Directory -> New Project (Also reproduced with R Package and New Plumber API Project)
2. Name project and select Create Project
3. Observe error page
Note: It's not 100% repro so you may have to try and create several projects.

### Describe the problem in detail
Connection Refused error page "The site can't be reached" shows up when trying to create a new project. After selecting reload, the project loads fine. I was able to narrow it down to being introduced in the 1.2.666 build. I couldn't reproduce on 1.2.664 and earlier. FYI @kfeinauer https://github.com/rstudio/rstudio/commits/6333eb2b7b4d23561b762723a3f11c84f7775bce

![image](https://user-images.githubusercontent.com/15237845/40769388-7cb81da0-647d-11e8-9352-18437078601b.png)

**Comment by kevinushey** [comment]
This might be the same issue as https://github.com/rstudio/rstudio/issues/2365.

**Comment by kfeinauer** [comment]
That's correct, @kevinushey. This should affect all desktop platforms. The issue to track the fix for this is #2898. The Desktop launcher mechanism has no means to retry connecting to the session.
