### ISSUE TITLE
Add retry logic to desktop session launch mechanism

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#2898]
### System details
```
RStudio Edition : Desktop 
```
There is no session launch retry mechanism for the Desktop code path, meaning that if the session takes longer than 100 milliseconds to start listening for connections, the session launch will fail and the user will see a blank white screen.

In the past, on Mac, we had a retry mechanism here: https://github.com/rstudio/rstudio/blob/b4973a964c4b4482ae7e03b1be3c5c4c4eb51b45/src/cpp/desktop-mac/SessionLauncher.mm#L395-L396

However, there is no retry in the new codepath (older desktop code that was unified): https://github.com/rstudio/rstudio/blob/be412422fb4c28d734fb765efc285faafe854aa6/src/cpp/desktop/DesktopSessionLauncher.cpp#L298-L305

### Steps to reproduce the problem
Insert a `sleep(100)` call somewhere in the `rsession` executable to easily reproduce this.

**Comment by kevinushey** [comment]
Marking this as v1.2 milestone as the associated issue (#2365) depends on this.

**Comment by cbrueffer** [comment]
I recently updated to version 1.2.1335 from 1.1.X (not sure which exactly) on Ubuntu 18.04.3 and have started seeing the "website can't be reached" error on project load.

My projects are on a sshfs mount over the internet, so there's a bit of latency. Never saw this problem with the previous version though.
