### ISSUE TITLE
On Windows, when installing a package that needs compilation, the dialog box shows behind RStudio window

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#2901]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.667
    OS Version      : Windows
    R Version       :  3.5.0

### Steps to reproduce the problem

As of right now, doing the following will cause the problem. First make sure the purrr package is not installed. Then run:

```R
install.packages('plotly')
```

It will try to install purrr, because plotly imports it. The dialog will appear behind the RStudio window, and unless the user knows that it's there, they will probably end up killing the RStudio process.

Note that if you install purrr directly, the problem does not happen; the dialog appears in front, as it should.

```R
install.packages('purrr')  # OK
```

This happens right now because purrr does not have the latest binary package on CRAN. Once it's there, these instructions won't cause the problem, but I'm guessing it will happen with other packages.

**Comment by wch** [comment]
After installing some more packages, I've seen the dialog pop up behind the window when installing a package directly. Here's a screenshot:

![image](https://user-images.githubusercontent.com/86978/40807696-a41a977a-64ea-11e8-83a1-8306827bc9cc.png)

**Comment by ronblum** [comment]
Reproduced in 1.2.672-1. The shy dialog:
<img width="405" alt="dialog" src="https://user-images.githubusercontent.com/31009952/40809424-7229f1f8-64f8-11e8-93be-1aaa7485aaa0.png">

**Comment by kevinushey** [comment]
Simpler reprex:

```
utils:::askYesNo("Is this a shy dialog?")
```

Curiously, this is only an issue the _first_ time the dialog is shown -- subsequent calls to `askYesNo()` will show the dialog on top of the RStudio window.

**Comment by kevinushey** [comment]
This PR also fixes the long-standing issue with tcltk dialogs showing up behind the RStudio window :-)

**Comment by jmcphers** [comment]
Very cool!
