### ISSUE TITLE
menu bar text too small (1.2.637 with dual monitors)

### ISSUE THREAD

**Issue by rgayler** [rstudio/rstudio#2905]
I use a laptop with an external 4K monitor as a second display and just upgraded to  RStudio 1.2.637-1. Now the menu bar and menu text is very small (~ 1/2 the height of all the other text) when RStudio is on the external 4K monitor. It is too small to read comfortably and the characters are fuzzy, suggesting that they are too small relative to the pixel resolution to be displayed accurately. **This behaviour was not present in RStudio 1.1.453.**

RStudio 1.2.637 on 4K monitor

![image](https://user-images.githubusercontent.com/5409051/40810946-b8aa9ba8-6572-11e8-98c7-0e7a3d23874b.png)

RStudio 1.1.453 on 4K monitor

![image](https://user-images.githubusercontent.com/5409051/40811825-312c1e32-6576-11e8-97ff-c4e05dc8660b.png)

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.637
    OS Version      : Ubuntu 18.04 LTS 
    R Version       : 3.4.4

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_AU.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8   
 [6] LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4  rsconnect_0.8.8 tools_3.4.4    
> 
```
### Steps to reproduce the problem

Laptop has 14" 2560 x 1440 builtin display and external 43" 3840 x 2160 monitor.
Set builtin display to primary monitor (contains dock and indicators).

Install RStudio 1.2.637

Display RStudio on the external monitor (either by opening on the external monitor or opening on the builtin display and dragging RStudio to the external monitor)

Menu bar text and menu text are tiny and fuzzy on secondary 43" 3840 x 2160 monitor. Good clarity on the primary 14" 2560 x 1440 laptop screen.

### Describe the problem in detail

This problem does *not* occur for RStudio 1.1.453

This problem does *not* occur for if the 4K monitor is set as the primary display

Given that the 1.2.637 release notes say that the rendering engine has changed I presume the new rendering engine is doing something different in autoscaling the menu text relative to the resolution/size of the monitors.

**Comment by kevinushey** [comment]
@rgayler Sorry it took so long for us to respond. Are you still seeing this with the latest [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio?

Do you have UI scaling active in your case (e.g. 200% scaling)?

**Comment by rgayler** [comment]
Hi Kevin,

> Are you still seeing this with the latest preview release
<https://www.rstudio.com/products/rstudio/download/preview/> of RStudio?

Yes - I am still seeing it with RStudio 1.2.830

After getting your email I have spent half a day, futzing around with a
ruler measuring the sizes of visual features on my screens.
I *think* I have a reasonable explanation of what is happening.

First some context:
RStudio = 1.2.830
OS = Ubuntu 18.04 64-bit
Primary display = laptop, 2560 x 1440 (16:9), width ~305mm, resolution
~8.4px/mm
Secondary display = 43" 4k monitor, 3840 x 2160 (16:9), width ~940mm,
resolution ~4.1px/mm

Some possibly relevant secondary/primary ratios:
x-pixels = 1.5
x-width = ~3.1
resolution = ~0.5

One interesting point here is that the secondary screen is roughly 3 times
the width of the primary whereas the resolution is a factor of 2 in the
other direction. I think this very large difference between the two
displays is what makes the effect obvious to me. For other people with more
similar displays the effect I am seeing is probably smaller, so they don't
notice it.

The other very relevant point is the factor of resolution difference. This
means that an object of a fixed size in pixels will double in linear
dimension when moved from the primary to secondary display.


Screenshot of the primary display OS settings:
[image: image.png]


Screenshot of the secondary display OS settings:
[image: image.png]

So the OS scaling is 100% for both displays.

Now here is a screenshot of the two displays (secondary above primary). The
pixels are scaled to the same size in both displays in this screenshot. In
real life, the secondary display is even larger relative to the primary
display.
This shot shows two windows open on the primary display: gedit text editor
on the left, RStudio on the right. Both windows have been snapped to fill
exactly half the display. In both windows I have text with line numbering
so you can see how many lines fit.
I have the global optians | appearance dialog open in the RStudio window.
You can see I have 100% zoom and 10 point font.
*The thing to note* is that the RStudio 10 point font at 100% zoom is
**really** large relative to the size of the window in the primary display.
There are only 30 lines visible in the editor pane. The font sizes and UI
settings aren't comparable between RStudio and gedit, but the default in
gedit fits ~70 lines in the same space at a size that's very comfortable to
work with.
When working with RStudio on the primary display I typically zoom out to
75% (which  makes 43 lines visible in the editor pane)
**I have just noticed another weird thing** If I zoom out with ctl+- the
menu bar text stays constant and all the other text resizes. If I try to
set the zoom in tools | global options | appearance, the size of the
example text in the dialog changes, but when I apply the changes the
RStudio UI does not change. **That has to be a bug.**

OK - now I drag both windows to the secondary display. I have just moved
them, not resized them. Here's the screenshot:

Measuring the size of the windows on the primary and secondary screens and
knowing the resolution ratio I determined that the windows were the same
size in pixels on both displays. (This means that the same window is twice
the physical size on the secondary display because the resolution has
halved.)
You can see that the gedit window is still displaying the same number of
lines, so the font size (in pixels) is unchanged). Whereas the RStudio edit
pane is now displaying 73.5 lines instead of 30. This means that the size
of the characters (in pixels) has more than halved. It is possible that the
UI is trying to maintain constant physical size of characters. My
measurements aren't accurate enough to determine whether that is the case.
So it looks like the RStudio UI is trying to maintain constant physical
character size, while the OS UI is trying to maintain constant pixel window
size. This means that when RStudio is moved from the primary to secondary
display the number of pixels per character is about halved.

Now the font for the RStudio menu bar is smaller than the text font. If I
take RStudios word for it when it says it is using 7 point font, then the
file menu font might be 5 point. That's legible on the primary display, but
when I move it to the secondary display the number of pixels per character
is halved, which is presumably too few pixels to crisply display the
characters when the font was small to begin with.

For my display setup, I think it would be better to maintain constant
character size in pixels, and that is also consistent with what other
programs appear to do.

I hope that helps.

Cheers

Ross

**Comment by rgayler** [comment]
Hi Kevin,

> Are you still seeing this with the latest preview release of RStudio?

Yes - I am still seeing it with RStudio 1.2.830

After getting your email I have spent half a day, futzing around with a
ruler measuring the sizes of visual features on my screens.
I *think* I have a reasonable explanation of what is happening.

First some context:
RStudio = 1.2.830
OS = Ubuntu 18.04 64-bit
Primary display = laptop, 2560 x 1440 (16:9), width ~305mm, resolution
~8.4px/mm
Secondary display = 43" 4k monitor, 3840 x 2160 (16:9), width ~940mm,
resolution ~4.1px/mm

Some possibly relevant secondary/primary ratios:
x-pixels = 1.5
x-width = ~3.1
resolution = ~0.5

One interesting point here is that the secondary screen is roughly 3 times
the width of the primary whereas the resolution is a factor of 2 in the
other direction. I think this very large difference between the two
displays is what makes the effect obvious to me. For other people with more
similar displays the effect I am seeing is probably smaller, so they don't
notice it.

The other very relevant point is the factor of resolution difference. This
means that an object of a fixed size in pixels will double in linear
dimension when moved from the primary to secondary display.


Screenshot of the primary display OS settings:
![image](https://user-images.githubusercontent.com/5409051/43880864-7bb4410c-9bed-11e8-9304-989ad73fcf93.png)

Screenshot of the secondary display OS settings:
![image](https://user-images.githubusercontent.com/5409051/43880876-8d360906-9bed-11e8-9361-7a24c0525497.png)

So the OS scaling is 100% for both displays.

Now here is a screenshot of the two displays (secondary above primary). The
pixels are scaled to the same size in both displays in this screenshot. In
real life, the secondary display is even larger relative to the primary
display.
![image](https://user-images.githubusercontent.com/5409051/43881050-42def6aa-9bee-11e8-9484-bb222604b1bb.png)

This shot shows two windows open on the primary display: gedit text editor
on the left, RStudio on the right. Both windows have been snapped to fill
exactly half the display. In both windows I have text with line numbering
so you can see how many lines fit.

I have the global optins | appearance dialog open in the RStudio window.
You can see I have 100% zoom and 10 point font.

*The thing to note* is that the RStudio 10 point font at 100% zoom is
**really** large relative to the size of the window in the primary display.
There are only 30 lines visible in the editor pane. The font sizes and UI
settings aren't comparable between RStudio and gedit, but the default in
gedit fits ~70 lines in the same space at a size that's very comfortable to
work with.

When working with RStudio on the primary display I typically zoom out to
75% (which  makes 43 lines visible in the editor pane).

**I have just noticed another weird thing** If I zoom out with ctl+- the
menu bar text stays constant and all the other text resizes. If I try to
set the zoom in tools | global options | appearance, the size of the
example text in the dialog changes, but when I apply the changes the
RStudio UI does not change. **That has to be a bug.**


OK - now I drag both windows to the secondary display. I have just moved
them, not resized them. Here's the screenshot:
![image](https://user-images.githubusercontent.com/5409051/43881071-52f3532e-9bee-11e8-9d70-f446cb8a2828.png)

Measuring the size of the windows on the primary and secondary screens and
knowing the resolution ratio I determined that the windows were the same
size in pixels on both displays. (This means that the same window is twice
the physical size on the secondary display because the resolution has
halved.)

You can see that the gedit window is still displaying the same number of
lines, so the font size (in pixels) is unchanged). Whereas the RStudio edit
pane is now displaying 73.5 lines instead of 30. This means that the size
of the characters (in pixels) has more than halved. It is possible that the
UI is trying to maintain constant physical size of characters. My
measurements aren't accurate enough to determine whether that is the case.

So it looks like the RStudio UI is trying to maintain constant physical
character size, while the OS UI is trying to maintain constant pixel window
size. This means that when RStudio is moved from the primary to secondary
display the number of pixels per character is about halved.

The font for the RStudio menu bar is smaller than the text font. If I
take RStudio's word for it when it says it is using 7 point font, then the
file menu font might be 5 point. That's legible on the primary display, but
when I move it to the secondary display the number of pixels per character
is halved, which is presumably too few pixels to crisply display the
characters when the font was small to begin with.

For my display setup, I think it would be better to maintain constant
character size in pixels, and that is also consistent with what other
programs appear to do.

I hope that helps.

Cheers

Ross

**Comment by kevinushey** [comment]
Hi Ross,

Thank you for the thorough response! This will be very helpful and we'll try to test with a similar setup in-house just to confirm that we're seeing the same issue.

> I have just noticed another weird thing If I zoom out with ctl+- the
> menu bar text stays constant and all the other text resizes. If I try to
> set the zoom in tools | global options | appearance, the size of the
> example text in the dialog changes, but when I apply the changes the
> RStudio UI does not change. That has to be a bug.

This does indeed feel like an oversight -- we'll see if we can unify the sizing here.

**Comment by rgayler** [comment]
That reminds me - all the stuff in that comment was based on laptop=primary
and 4K=secondary display. I just tried setting the 4K monitor as primary
and the file menu text was much larger - so the initial scaling of the file
menu text looks like it depends on looking up the characteristics of the
primary display.

**Comment by KunzstLD** [comment]
Hello,
I'm still having the same issue as rgayler with a similar setup. I tried rstudio-1.2.5019 and the latest rstudio daily build (1.3.580). On my laptop screen, I can't resize the menu bar (it still is readable, so no big deal). Using the external screen the menu bar is way too small and not resizeable and also the fonts look very fuzzy. 

On rstudio - 1.1.463 I also couldn't resize the menu bar, but it already had a readable size and the fonts were not fuzzy (increasing font size in Linux settings didn't have an effect on the menu bar in any rstudio version I used so far). 
It might be a hardware problem - still I'm curious, has there any progress been made on this issue? 

OS: Linux Mint 19 Cinnamon
Display Laptop resolution 2560 x 1440 (16:9)
Display LG External Monitor resolution 1920 x 1080 (16:9)
(tried different resolutions but didn't achieve any improvement)

**Comment by KunzstLD** [comment]
Hi there,
the problem disappeared for me after updating RStudio to version 1.4.904 (as preview available)
https://rstudio.com/products/rstudio/download/preview/

Good luck,
Stefan

**Comment by OlivierH71** [comment]
Same on Win10, issue was solved by installing the 1.4.1087 preview.
Note that for odd reason, my previous installation of R 1.3, installed in a different folder, so, still available on my machine, has also been solved by installing version 1.4. Probably a shared dll somewhere.

**Comment by DannyQuah** [comment]
Same problem as OP (01 Jun 2018) and KunzstLD (06 Nov 2019):  RStudio menubar fonts tiny (I'm on Gallium OS/Ubuntu 18.04/ RStudio v1.3.1093).  Fontsize fails to change with adjusting System Settings, although the latter successfully varies menubar fontsizes on other open windows.  
Upgraded to RStudio v1.4.1100-3 Preview; problem remains.  
Successfully resolved by changing Primary Display to External Monitor: menubar fonts now legible but still invariant to System Settings.  

Laptop (Google Pixelbook) Sharp Corp 12" 2400x1600  
External display Dell Inc. 23" 1920x1080

**Comment by mhjackson1** [comment]
Making the external monitor the primary display solved this problem for me as well. running 2021.09.0 Build 351 on Windows 10 Enterprise version 1909.

The other solutions (zooming, changing system settings, etc.) did not work. 


> 
> Same problem as OP (01 Jun 2018) and KunzstLD (06 Nov 2019): RStudio menubar fonts tiny (I'm on Gallium OS/Ubuntu 18.04/ RStudio v1.3.1093). Fontsize fails to change with adjusting System Settings, although the latter successfully varies menubar fontsizes on other open windows. Upgraded to RStudio v1.4.1100-3 Preview; problem remains. Successfully resolved by changing Primary Display to External Monitor: menubar fonts now legible but still invariant to System Settings.
> 
> Laptop (Google Pixelbook) Sharp Corp 12" 2400x1600 External display Dell Inc. 23" 1920x1080

**Comment by gtritchie** [comment]
We need to try this again once we have preview builds of Electron.

**Comment by sbudoff** [comment]
Similar issue for me as well, rstudio menu is invariant to zoom in/out and is much larger than that of any other software I have tested on my secondary monitor. At font = 10 and zoom = 0.5 in global settings, I see 46 lines of code on my 15.6" laptop monitor and 42 lines on my 31.5" secondary monitor; both are set to 1920x1080 with scale  = 100%. inch. Oddly, unlike others in this thread I get a slight decrease in menu size when my laptop is set as my primary monitor. 

RStudio: 2022.2.1.461, 
R: 3.6.3, 
OS: Ubuntu 20.04.4 LTS, 
Laptop: Lenovo Thinkpad P15 Gen 2 15" 3840x2160, 
External Display: Acer EB321HQU Cbidpx 32" 2560x1440.

**Comment by rborder** [comment]
Here is a solution that doesn't involve changing system-wide settings (e.g., changing which monitor is primary).

Set the `QT_SCALE_FACTOR` env variable when launching rstudio.
E.g., `QT_SCALE_FACTOR=2 rstudio`

To make this working when opening rstudio via a launcher, modify the `Exec` line in `/usr/share/applications/rstudio.desktop` to be something like `Exec=env QT_SCALE_FACTOR=2 /usr/lib/rstudio/bin/rstudio %F`. Paths might vary based on your OS, this works for me in Ubuntu 20.04.

For some reason, rstudio is the only qt program I use that requires this. It also doesn't pay any attention to the global qt theme options, but that at least doesn't effect usability...

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by rgayler** [comment]
I am already using 2022.07.0+548 and the scaling problem doesn't occur.

**However**, this provides no information relevant to [your request](https://github.com/rstudio/rstudio/issues/2905#issuecomment-1184479733), because this issue ceased to occur for me a few years ago. I had assumed RStudio fixed it, but I see from the issue thread that other people were still encountering it long after it ceased to be an issue for me. I guess something changed in my Ubuntu set-up.

Maybe @sbudoff or @rborder are better placed to reproduce the issue.

**Comment by ronblum** [comment]
@rgayler Interesting—I appreciate your checking this and providing this info!

**Comment by ronblum** [comment]
I'm closing this as fixed by Electron. If anyone tries out these builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) without any of the workarounds and the issue persists, please let us know!

**Comment by brianstamper** [comment]
> Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.
> 
> To try out Electron:
> 
> * Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
> * For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B).
> 
> Please note that these are meant for testing and development purposes, not production.

Sorry if I'm naive, but was it only the _preview_ version of Wakerobin that runs on Electron? I just got around to upgrading to that and I still have the small window font problem.

RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

FWIW my DE is KDE/Plasma. I tried the modification to /usr/share/applications/rstudio.desktop but it had no effect.

If it is the case that I just need to wait for the next release I'm fine with that.

**Comment by ronblum** [comment]
@brianstamper That's correct—only the preview and dailies had an experimental Electron version of RStudio Desktop. The current preview builds (available [at the dailies page](https://dailies.rstudio.com/)) of the open source version is entirely in Electron.
