### ISSUE TITLE
Chunk output mangled if function signals warning and error

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2907]
Create the following chunk in an Rmarkdown document then execute it.

````
```{r}
read.csv("blah.csv")
```
````

The chunk output contains only the error (`Error in file(file, "rt") : cannot open the connection)`) and the console shows the error and warning without intermediate new line:

```
> read.csv("blah.csv")
cannot open file 'blah.csv': No such file or directoryError in file(file, "rt") : cannot open the connection
``` 

Running the code directly in the console gives correct output:

```
> read.csv("blah.csv")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'blah.csv': No such file or directory
```

**Comment by ronblum** [comment]
Reproduced in 1.1.453 and 1.2.679-1 on MacOS 10.12.6 and Windows 10.
