### ISSUE TITLE
.RMD CTRL+C/CTRL+V does not work  in Editor RS 1.1.453 (Windows 10).  

### ISSUE THREAD

**Issue by smeme** [rstudio/rstudio#2910]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      :  Windows 10
    R Version       :  3.4.0 (2017-04-21)

### Steps to reproduce the problem
  *  copy text using shortcut "ctrl+C" or using the menu "Edit> Copy"
  *  paste using shortcut "ctrl+V" or using the menu "Edit> Paste"
  *  Problem occurs only for .Rmd files already saved on the drive

### Describe the problem in detail
  * copy-paste does not work when editing .Rmd files. 
  *  ** Issue does not occur with a new (unsaved) "untitled.Rmd" file.** 
  * copy-paste works within the console and when editing .R files.

**Comment by jmcphers** [comment]
Haven't heard back in years, so closing.
