### ISSUE TITLE
clicking in the document outline always scrolls it to the top

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2912]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.669
    OS Version      : macOS 10.13.5
    R Version       : R 3.5.0

### Details

They say a picture is worth a thousand words, so here's a `.gif`:

![document-outline](https://user-images.githubusercontent.com/1976582/40932620-ce593f5e-67e3-11e8-97f1-657a635064fb.gif)

Note how, after clicking `Section 40` in the document outline, the editor scrolls to that section, but the document outline returns to the top.

This is a regression relative to v1.1, so filing for v1.2.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
