### ISSUE TITLE
Users can modify their default CRAN when "allow-r-cran-repos-edit" is disabled

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rstudio#2915]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.680
    OS Version      : SUSE 12
    R Version       : 3.4.3

### Steps to reproduce the problem

- Start from a clean user environment
- In this file: `/etc/rstudio/rsession.conf` add the following line:

`allow-r-cran-repos-edit=0`

- Restart rstudio server
- Access and login
- Restart R session
- Open Tools -> Global Options -> Packages -> Management
- Change the Primary CRAN repo, Apply or OK
- This change is saved and takes effect (even after server and R session restart)

### Describe the behavior you expected

The configuration setting is supposed to disallow users from changing their default CRAN, but doesn't seem to do that.

**Comment by fereshtehRS** [comment]
Talked to @javierluraschi. This setting applies to pro version only, and it is working as expected.

**Comment by m20l22** [comment]
Please update the documentation with adding label "Workbench" to this setting. Otherwise it is missleading.
https://docs.posit.co/ide/server-pro/reference/rsession_conf.html#allow-r-cran-repos-edit
