### ISSUE TITLE
UI Packages page does not show the default repos defined in the repos.conf file

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rstudio#2917]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.680
    OS Version      : SUSE 12
    R Version       : 3.4.3

### Steps to reproduce the problem

- Start from a clean user environment
- Create this file: `/etc/rstudio/repos.conf` and add the following lines:

```
CRAN=http://solo.rstudiopm.com/companyRepo/latest
bleedingEdge=http://solo.rstudiopm.com/bleedingEdgeRepo/latest
```

- Restart rstudio server
- Access and login
- Restart R session
- In the console, run `getOption("repos")` command; this correctly shows the 2 options mentioned above.

```
getOption("repos")
$CRAN
[1] "http://solo.rstudiopm.com/companyRepo/latest"

$bleedingEdge
[1] "http://solo.rstudiopm.com/bleedingEdgeRepo/latest"

attr(,"RStudio")
[1] TRUE
```

- Open Tools -> Global Options -> Packages -> Management
- This page does not show the repos defined in the `/etc/rstudio/repos.conf` file.

### Describe the problem in detail

The UI settings are purely user settings; without UI actions they do not get updated. This might be fine. But there is some inconsistency between configuration and UI.

### Describe the behavior you expected

It would be cleaner if UI reflects the configuration settings.

**Comment by javierluraschi** [comment]
I believe we fixed this a couple months ago by passing through the config settings to the preferences UI. Feel free to reopen if there is something missing to reconsider.
