### ISSUE TITLE
[Linux] Switch from and back Rstudio window causes console to scroll to the end

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#2918]
In KDE (DE for Linux), when switching to and from the Rstudio application window, the console automatically scrolls down to the end, instead of remaining on focus in the part at which it was.

Steps to reproduce:
-Launch Rstudio.
-Do something on it that would produce a console log that would be scrollable up and down.
-Switch to a different application, then back to Rstudio.

Expected behavior:
-When switching back, the console should be at the same part of the scrollbar as it was before switching.

Actual behavior:
-The console scrolls down to the end, showing the most recent console history.

Reproducible: sometimes (don't know how exactly to make it reproducible)
Rstudio version: 1.1.453
DE versions: KDE Plasma 5.12.5, KDE frameworks 5.46, QT 5.10.1

**Comment by ronblum** [comment]
@david-cortes Thanks for raising the issue. In order to try to reproduce, what flavor and version of Linux are you running on?

**Comment by david-cortes** [comment]
I'm running Debian buster/sid (unstable), with kernel 4.16.0-1, 64-bit version. Happens in two different computers with the same setup.

**Comment by david-cortes** [comment]
Indeed, that causes it to scroll down to the end when switching back, and I guess that's what was causing this behavior I experienced. Is there any way to disable it?

**Comment by david-cortes** [comment]
Still reproducible and now reproducible even if something is written in the console line but not yet executed.
