### ISSUE TITLE
file dialogs open in main window, behind Shiny application

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2921]
### System details

    RStudio Edition : Server
    RStudio Version : v1.2.669
    OS Version      : macOS 10.13.5
    R Version       : 3.5.0

### Steps to reproduce the problem

Run the following Shiny application, and click the associated File dialog button:

```
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(
  actionButton("sf", "Select file")
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  observeEvent(input$sf, {
    rstudioapi::selectFile()
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

### Describe the problem in detail

The file dialog opens in the main window, behind the Shiny application window.

<img width="719" alt="screen shot 2018-06-05 at 12 57 32 pm" src="https://user-images.githubusercontent.com/1976582/41000062-a8f4094a-68c1-11e8-9d2e-35a493d536b8.png">

### Describe the behavior you expected

Either:

1. The file dialog should show on top of the Shiny application window, or
2. The main window should be raised to the front when the dialog is opened, and then focus returned to the Shiny application when all is done.

### References

https://github.com/rstudio/rstudioapi/issues/91

**Comment by vnijs** [comment]
Perhaps a silly idea but ... could the file browser be embedded in a modal when `rstudioapi::selectFile` is called from a shiny app to select files on the server? Similar to `https://github.com/thomasp85/shinyFiles`? Unfortunately, shinyFiles is no longer maintained and doesn't support `renderUI`.

cc-ing @jcheng5 and @wch in case they have any suggestions.

**Comment by kevinushey** [comment]
It looks like we could use `window.open()` to resolve this, e.g.

```js
window.open("javascript:void(0)", "rstudio")
```

assuming that the RStudio main window has name `"rstudio"`. From what I can see, the main RStudio window is currently not named, so that's one change we'd need to make (and that would need to be communicated to satellite windows in some way).

Presumedly, this could work as a system for transferring focus between parent + child windows, so that `rstudioapi` requests could focus the main window for modals, and then transfer focus back to the child window when done.

Alternatively, we could just allow our modal file dialogs to open in satellite windows as well -- I don't think there's any technical reason why this isn't possible, but it could be worth investigating.

**Comment by kevinushey** [comment]
Sorry, what do you mean by "External"?

**Comment by vnijs** [comment]
Sorry about that. I meant, in an external browser.

![image](https://user-images.githubusercontent.com/2998956/41734789-db5b0c4e-753c-11e8-9c22-3af9d0481f93.png)

**Comment by kevinushey** [comment]
With this PR (https://github.com/rstudio/rstudio/pull/3047), here's an example application that works well with RStudio Server + RStudio Desktop:

```r
library(shiny)

JS <- "
$(document).ready(function() {
   $('#sf').click(function() {
      window.open('javascript:void(0)', window.parent.opener.name);
   });
});
"

# Define UI for application that draws a histogram
ui <- fluidPage(
   tags$script(JS),
   actionButton("sf", "Select file")
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   observeEvent(input$sf, {
      rstudioapi::selectFile()
   })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

This likely won't work for cases where RStudio Desktop is using an external browser, but at least this would be a step forward for your case.

**Comment by vnijs** [comment]
@kevinushey I tried the code example in 1.2.771 for Desktop on macOS High Sierra. When running in Viewer, Window, or External clicking the action button does not show new window or file browser. You mentioned you had this working with Rstudio server + desktop so perhaps the PR isn't included in this daily build yet?

Interestingly, if I comment out the `tags$script(JS),` line, run in External browser, and click `Cancel` when the file browser opens, Rstudio consistently crashes. Let me know if you want me to file an issue about that.

**Comment by kevinushey** [comment]
It looks like we're not allowed to access `window.parent` or `window.opener` in the release builds of RStudio Desktop, so these code examples break. :-/

We'll have to think about a cleaner way to handle this. I think RStudio should endeavor to handle this on its own without any explicit user code, but we'll have to think a bit more.

**Comment by vnijs** [comment]
Too bad. "without any explicit user code" sounds great though. So ... this should still work with Rstudio server?

**Comment by kevinushey** [comment]
Yes, it should work with RStudio Server. That said, on RStudio Desktop one should typically just be using RStudio windows and in that case the system modal file dialog is used and so this shouldn't be an issue.

**Comment by vnijs** [comment]
@kevinushey I tried your example with Rstudio server 1.2.771. After clicking the action button the main Rstudio window is shown and the Window running the app is pushed behind the browser. I can now see the file browser *but* after selecting a file (or clicking cancel) the Window running the app is still hidden behind the main Rstudio window. Is that intended?

Ideally the file browser would show in front of the Window running the app but if that is not possible how would you bring the app Window back to the front after using the file browser?

**Comment by kevinushey** [comment]
@vnijs no, I haven't wired that up yet. RStudio will need to take care of that (we'll try to flesh out something more realistic when we next tackle this one)

**Comment by vnijs** [comment]
Thanks @kevinushey. I appreciate you looking in to this. Any guesses on a time-line? I'm planning classes for summer and fall and I'd prefer to use Rstudio server (or Cloud). However, without a functional server-side file browser accessible from shiny it is not practical for me and I'll (unfortunately) have to revert to local install on student laptops.

**Comment by jmcphers** [comment]
One possible solution would be to have the rstudioapi detect that there's a satellite window open and focused, and show the dialog in that window instead of the main window.
