### ISSUE TITLE
Icons don't render

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rstudio#2926]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.694 (issue also occurs on the preview release 1.2.679-1)
    OS Version      :  Mac OS X 10.13.3
    R Version       :  3.5.0

### Steps to reproduce the problem

Open a RStudio with a modern theme:

![screen shot 2018-06-06 at 9 50 24 am](https://user-images.githubusercontent.com/1365941/41046168-83f3c33e-696f-11e8-8c86-43ebfb80dc99.png)

### Describe the problem in detail

Things looks a bit better with classic theme, but some of the icons are dimmed

![screen shot 2018-06-06 at 9 53 11 am](https://user-images.githubusercontent.com/1365941/41046232-a5dce3f4-696f-11e8-884d-723feab442d2.png)

**Comment by kevinushey** [comment]
Can you provide more information about your system? Macbook, iMac, or otherwise? What kind of video card does it have?

**Comment by cpsievert** [comment]
![screen shot 2018-06-06 at 10 05 15 am](https://user-images.githubusercontent.com/1365941/41046986-25318622-6971-11e8-9d8a-068f7093facb.png)

**Comment by cpsievert** [comment]
![screen shot 2018-06-06 at 10 05 15 am](https://user-images.githubusercontent.com/1365941/41047152-8560add4-6971-11e8-9756-9e73067ae5fa.png)

**Comment by kevinushey** [comment]
Does it make any difference if you launch RStudio from the command line with:

```
RSTUDIO_CHROMIUM_ARGUMENTS="--disable-gpu-rasterization" \
    /Applications/RStudio.app/Contents/MacOS/RStudio
```

**Comment by cpsievert** [comment]
That fixes it! Thanks, you're amazing @kevinushey 👍

**Comment by kevinushey** [comment]
Nice, glad to hear it!
