### ISSUE TITLE
No longer able to reorder source tabs

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rstudio#2927]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.694 (issue also occurs on the preview release 1.2.679-1)
    OS Version      :  Mac OS X 10.13.3
    R Version       :  3.5.0

![tabs](https://user-images.githubusercontent.com/1365941/41053592-a41bb2fe-6981-11e8-8919-87db54ef11e9.gif)

**Comment by jmcphers** [comment]
We haven't been able to reproduce this. :-/ Does it happen in a new project? What zoom/appearance settings do you use?

**Comment by cpsievert** [comment]
Yea, I was actually just about to come back here and say it's now working and now I can't reproduce 🤷‍♂️ 

Will reopen if it happens again
