### ISSUE TITLE
List expanded the first time in data viewer and collapsed on subsequent views

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2932]
### System details

    RStudio Edition : Desktop (fine on Server)
    RStudio Version : 1.2.695
    OS Version      : MacOS & Ubuntu
    R Version       : 3.5.0

### Steps to reproduce the problem

`View(repurrrsive::gh_repos)`
`View(repurrrsive::gh_repos)`
`View(repurrrsive::gh_repos)`

Also, if the `rwars` package is installed:

`planets <- get_all_planets()`
`View(planets)`
`View(planets)`
`View(planets)`

### Describe the problem in detail

The first time a list is is viewed with the data viewer, it's fully displayed. However, on subsequent views, it's collapsed. This is true even if the tab is closed and the list is viewed again. You can actually briefly see the expanded list before it gets collapsed.

The issue is on desktop only. Tested on MacOS 10.12.6 (Sierra) and Ubuntu 18.04 Desktop, and Ubuntu 16.04 and SUSE 12.3 Server.

### Describe the behavior you expected

The list should not be collapsed on subsequent views, or it should be collapsed the first time. Maybe the view should keep the last state, e.g. if the list was previously collapsed, it should stay collapsed. Either way, it seems odd that the list is only expanded on the first viewing.

This is a regression from 1.1, in which the list is always initially expanded.

**Comment by kevinushey** [comment]
For me, the display alternates between expanded and unexpanded.

**Comment by kevinushey** [comment]
@ronblum just to confirm one thing -- you were executing the associated code with <kbd>Ctrl + Enter</kbd> (or <kbd>Cmd + Enter</kbd> on macOS); is that correct?

If so, I think I've identified the issue and it should be fixed in the next builds.

**Comment by ronblum** [comment]
Verified on MacOS Desktop 1.2.873-1.
