### ISSUE TITLE
Make it easier to "Find in Files ..." in R/ vs. tests/

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#2934]
I use "Find in Files ..." a lot in package development. So: I'm in RStudio, in a Project, that is a package.

<img width="482" alt="screen shot 2018-06-06 at 2 40 24 pm" src="https://user-images.githubusercontent.com/599454/41066774-f7e9f51a-6997-11e8-98dd-8d4df532085c.png">

The thing I toggle the most, *by far*, is whether I want to restrict the search to `R/` or `tests/` or not at all (search whole Project/package). I don't think I've ever used the extension-oriented filters in the "Search these files:" drop down. But I dutifully click-click-click through the file finding screens available via "Browse"  for "Search in" frequently, even though it feels very cumbersome.

Could "Search these files:" gain entries for searching in the `R/` directory or the `tests/` directory? It would be so handy.

**Comment by ronblum** [comment]
Linking to #2066, another search request.

**Comment by jmcphers** [comment]
Proposal:

1. remember the last directory you searched and make it the default the next time you search;

2. have the last ~5 directories searched show up in an MRU-style drop list you can choose from -- *Search in:* would become a combo box; and 

3. in a package project, pre-populate the MRU with R/ and tests/.

**Comment by HughParsonage** [comment]
(Aside: [`hutils::find_pattern_in("slug", "tests")`](https://hughparsonage.github.io/hutils/reference/find_pattern_in.html) might be a useful alternative.)

**Comment by jackwasey** [comment]
How about offering multiple paths, and/or shortcut to search `R/`, `src/` and `tests/` and default NOT to include `man/`?

**Comment by jennybc** [comment]
Of @jmcphers's three bullet points, the third is by far the most important to me (no surprise!). It really comes down to wanting an easy way to "search package source" and/or to exclude derived files (e.g. `man/`, `pkgdown/`, etc.).

**Comment by andrie** [comment]
I really like the way this is done in VS-code, where you can explicitly add `include` and `exclude` wild cards.

![image](https://user-images.githubusercontent.com/479998/71958411-27e95c00-31e8-11ea-97ef-b8daf7c9a3d3.png)
