### ISSUE TITLE
Make it possible to run an R script from the command line in R Studio Cloud?

### ISSUE THREAD

**Issue by jrosen48** [rstudio/rstudio#2943]
Apologies if this is not the right place to post about an R Studio Cloud-related issue; I couldn't find a better place and the Community page for this topic didn't seem like a good fit.

I was curious about whether it would be possible to run an R script from the Terminal in R Studio Cloud, in part because I'm interested in *others* using R Studio Cloud to learn how to run a script from the command line.

When I first tried running `Rscript myfile.R` in Terminal, an error was returned: `Rscript: command not found`. 

It seems like the Rscript executable lives in a folder that is not in the PATH environmental variable. But, I think I found the location of an executable at `/opt/R/3.4.4/bin/Rscript`.

I recognize this may be a pretty unusual thing to (want to) do in R Studio Cloud, but nevertheless wanted to bring this to your attention in case other folks may want to be able to do this. I was working on this with @a-rosenberg.

**Comment by jjallaire** [comment]
AFAIK the R bin directory should always be on the PATH. Perhaps this is somehow not getting forwarded to the terminal. @gtritchie Any thoughts?

**Comment by a-rosenberg** [comment]
In case it is useful, here are the pieces of information we came across.  The `PATH` variable without the location of any Rscript executable, then the locations where they were found in the `/opt` folder.  

```
rstudio-user@856541a814b5:~$ echo $PATH
/home/rstudio-user/bin:/home/rstudio-user/.local/bin:/home/rstudio-user/bin:/home/rstudio-user/.local/bin:/home/rstudio-user/bin:/home/rstudio-user/.local/bin:/home/rstudio-user/bin:/home/rstudio-user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

We were able to find a few executables: 

```
rstudio-user@856541a814b5:~$ cd /
rstudio-user@856541a814b5:/$ find -type f -name Rscript
...
./opt/R/3.4.2/bin/Rscript
./opt/R/3.4.2/lib/R/bin/Rscript
./opt/R/3.4.4/bin/Rscript
./opt/R/3.4.4/lib/R/bin/Rscript
./opt/R/3.3.3/bin/Rscript
./opt/R/3.3.3/lib/R/bin/Rscript
./opt/R/3.2.5/bin/Rscript
./opt/R/3.2.5/lib/R/bin/Rscript
./opt/R/3.1.3/bin/Rscript
./opt/R/3.1.3/lib/R/bin/Rscript
./opt/R/3.4.3/bin/Rscript
./opt/R/3.4.3/lib/R/bin/Rscript
...
```

**Comment by gtritchie** [comment]
On cloud, they don't install R in the traditional sense, so there are none of the expected symbolic links that normally get R and Rscript on the path. They are considering whether they can add the latest installed version of R to the path by default, but in the meantime you could modify the path for the terminal by editing one of the bash config files (.profile, etc.) to add R to the path.

**Comment by jmcphers** [comment]
@jrosen48 I'm closing this since it's not an issue with the IDE, but we're happy to continue the conversation. 

I think the workaround @gtritchie suggested will do the job for you; if it doesn't, I do think the community forum would be a good starting point: https://community.rstudio.com/c/rstudio-cloud

**Comment by jspiewak** [comment]
FYI, `$R_HOME/bin` is now added to the `PATH` in the terminal on rstudio.cloud, i.e. this should be working now...
