### ISSUE TITLE
only show panels in full screen view

### ISSUE THREAD

**Issue by skyencc860715** [rstudio/rstudio#2946]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 1.1.453 
    OS Version      : Mac OsX High Sierra 10.13.4
    R Version       :  3.5.0 

### Steps to reproduce the problem
step 1: open application list
step 2: double click on rstudio desktop icon 

### Describe the problem in detail
all the panels only show in full screen view, and missing when toggle back to non full screen view.

### Describe the behavior you expected
all the panels normally show in full screen view and full screen view.

**Comment by gp1d** [comment]
in my case yes, it does. i'm on mohave 10.14.3
the backup-rstudio-desktop.zip is too big to attach. 
I rely heavily on Rstudio for teaching, all help appreciated

**Comment by gp1d** [comment]
things got worse today. I am still only in full screen mode, but I am only able to see the left pane. yesterday I could use the mouse to make both visible, but today I need to use the pane preferences.

**Comment by kevinushey** [comment]
If you press <kbd>Ctrl + Shift + 1</kbd>, that will toggle zoom of the Source pane. Pressing it once or twice should be enough to get you back to non-fullscreen mode. Does that make a difference?

You might also try pressing <kbd>Cmd + 0</kbd> to reset to the default zoom level.

Finally, if all else fails, you can try installing the [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by gp1d** [comment]
MANY THANKS!

details below:

> 
> If you press Ctrl + Shift + 1, that will toggle zoom of the Source pane. Pressing it once or twice should be enough to get you back to non-fullscreen mode. Does that make a difference?
> 
> 

your suggestion did resurrect the left pane which I could not access via mouse, but did not get me back in non-fullscreen mode.

it looked as though the screen size was no longer fully understood by RStudio

> You might also try pressing Cmd + 0 to reset to the default zoom level.
> 
> 

this did not affect things
> Finally, if all else fails, you can try installing the preview release <https://www.rstudio.com/products/rstudio/download/preview/>.
> 
> 

I install it and things are back to normal. much appreciated!

**Comment by kevinushey** [comment]
Phew! I'm glad to hear it :-)

The preview release is currently quite close to becoming a release candidate, beyond one more infrastructure change coming down the line soon. We're hoping to promote this to a full release within the next couple months, so if you encounter any other issues we'd appreciate it if you could let us know.

**Comment by gp1d** [comment]
> On Feb 21, 2019, at 12:43 AM, Kevin Ushey <notifications@github.com> wrote:
> 
> Phew! I'm glad to hear it :-)
> 
> The preview release is currently quite close to becoming a release candidate, beyond one more infrastructure change coming down the line soon. We're hoping to promote this to a full release within the next couple months, so if you encounter any other issues we'd appreciate it if you could let us know.
> 
> 


great to hear. 

so far just a couple of crashes on “Command + S” but in both cases the content was saved before the crash.

**Comment by kevinushey** [comment]
> so far just a couple of crashes on “Command + S” but in both cases the content was saved before the crash.

Let me know if you're able to reproduce these crashes consistently; we'd love to be able to reproduce and fix issues like these before release!
