### ISSUE TITLE
Unable to open standard files on Unix with fresh installation

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2950]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.707
    OS Version      : Linux
    R Version       : 3.4.4 and 3.5.0

### Steps to reproduce the problem

File -> Open File
or
Files Pane -> Click on file

### Describe the problem in detail

Files that would be opened in the source pane—R, Rmd, Rpres, etc.—don't open. Files that are opened by an external browser—e.g pdf and pptx—open.

### Describe the behavior you expected

All files should open.

Fails in 1.2.699 and 1.2.707. Worked in 1.2.679.

Workaround: This seems to be worse on a fresh install, when there was no previous RStudio version installed. A sometimes-workaround is to first install an earlier version which worked, such as 1.2.679, and then update to 1.2.707. I tried this several times: it worked on Red Hat and SUSE, but failed after several tries on Ubuntu.

**Comment by jmcphers** [comment]
I haven't been able to reproduce this. :-/ Is there anything interesting in the server logs? Can you share your request log?

**Comment by ronblum** [comment]
From `/var/log/syslog`:

> Jun  8 18:57:08 ip-172-30-1-69 rserver[10661]: CLIENT EXCEPTION (rsession-rstudio): (TypeError) : Cannot read property 'properties' of null;|||org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java#117::getProperties|||org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java#139::getSourceWindowId|||org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java#335::getWindowIdOfDocPath|||org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java#1207::navigateToPath|||org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java#476::navigateToFile|||org/rstudio/studio/client/workbench/views/source/Source.java#2719::doOpenSourceFile|||org/rstudio/studio/client/workbench/views/source/Source.java#2678::onOpenSourceFile|||org/rstudio/studio/client/workbench/views/source/SourceShim_AsyncSource__Impl.java#226::onSuccess2|||org/rstudio/studio/client/workbench/views/source/SourceShim_AsyncSource__Impl.java#221::execute|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#256::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#252::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#248::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#244::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#240::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/SourceShim.java#155::preInstantiationHook|||org/rstudio/studio/client/workbench/views/source/SourceShim_AsyncSource__Impl.java#219::onSuccess|||com/google/gwt/core/client/impl/OnSuccessExecutor.java#33::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 2143313b-3584-491d-ba1c-32f85de8f3b9|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Similarly in `/var/lib/rstudio-server/monitor/log/rstudio-server.log`:

> 08 Jun 2018 18:57:08 [rserver] CLIENT EXCEPTION (rsession-rstudio): (TypeError) : Cannot read property 'properties' of null;|||org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java#117::getProperties|||org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java#139::getSourceWindowId|||org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java#335::getWindowIdOfDocPath|||org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java#1207::navigateToPath|||org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java#476::navigateToFile|||org/rstudio/studio/client/workbench/views/source/Source.java#2719::doOpenSourceFile|||org/rstudio/studio/client/workbench/views/source/Source.java#2678::onOpenSourceFile|||org/rstudio/studio/client/workbench/views/source/SourceShim_AsyncSource__Impl.java#226::onSuccess2|||org/rstudio/studio/client/workbench/views/source/SourceShim_AsyncSource__Impl.java#221::execute|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#256::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#252::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#248::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#244::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#240::onLoaded|||org/rstudio/core/client/ExternalJavaScriptLoader.java#72::addCallback|||org/rstudio/studio/client/workbench/views/source/SourceShim.java#155::preInstantiationHook|||org/rstudio/studio/client/workbench/views/source/SourceShim_AsyncSource__Impl.java#219::onSuccess|||com/google/gwt/core/client/impl/OnSuccessExecutor.java#33::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 2143313b-3584-491d-ba1c-32f85de8f3b9|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Also, I can't reproduce the issue on SUSE.

**Comment by jmcphers** [comment]
Ah, I know what this is. I'm pretty sure this problem is fixed in 707, and that the only reason you're still seeing it is that your browser is caching some scripts. Can you reproduce on 707 with a clean browser session and cache?

**Comment by ronblum** [comment]
All better. Thank you!
