### ISSUE TITLE
Scrolling tabs (don't focus, just scroll)

### ISSUE THREAD

**Issue by StefanBrand** [rstudio/rstudio#2968]
Hi everybody, 🙂 

I often get stuck in my workflow because scrolling the tabs actually focuses the neighbouring tab. This is annoying when there are many dataset `View()`s that take a long time to load. In Firefox, for example, scrolling scrolls the tabs and only focuses when I _click_ on one of them.

Maybe there is already a switch somewhere that lets me alter this behaviour? If not, what are the chances that tabs scrolling is implemented like in Firefox?

Best, Stefan

PS.: I see that the scrolling featuree was discussed [here in the old support forum](https://support.rstudio.com/hc/en-us/community/posts/213649347-Allow-scrolling-through-tabs-using-mouse-wheel).

**Comment by jmcphers** [comment]
No, there's not currently a switch that does this. Appreciate the suggestion!

**Comment by akiledal** [comment]
This would be really nice! Maybe it should be a separate issue, but horizontal scrolling would be really nice, especially on a touchpad, too.

**Comment by johnhowa** [comment]
Probably related, so I'll leave it here; I've seen this feature request before.

There should be way to turn off the behavior of mouse scrolling while hovering over tabs in the Source pane. While using the Magic Mouse, it scrolls so quickly that misclicking and losing your place becomes commonplace.
