### ISSUE TITLE
Focus is not on new viewer window for PDF knitted from R markdown file

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2970]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.707
    OS Version      : MacOS 12.10.6 (Sierra)
    R Version       : 3.5.0

### Steps to reproduce the problem

1. File -> New File -> R Markdown
2. Presentation -> PDF (Beamer) 
3. Enter "Tile" and "Author" -> OK
4. Knit -> Enter file name -> Save
   - PDF file is displayed in new viewer window
5. Click on arrows—up, down, left, right
   - Nothing happens
6. Click on a slide
7. Click on arrows—up, down, left, right
   - Works as expected
8. Click on Source pane (do not close PDF viewer)
9. Knit
   - PDF file is displayed in existing viewer window
10. Click on arrows—up, down, left, right
    - Works as expected

### Describe the problem in detail

When PDF presentation is knitted using Beamer, it opens up in a viewer window. However, the focus isn't on the viewer, so clicking on the arrows to moves through the slides or <kbd>cmd-w</kbd> to close the window don't work until the window is clicked. However, if the window is left open and then an Rmd file is again knitted using Beamer, the focus successfully remains on the existing window which now contains now the new PDF.

### Describe the behavior you expected

The focus should be on the PDF viewer from the start. This is the behavior of HTML slides (ioslides and Slidy), and was the behavior in 1.1.

**Comment by kevinushey** [comment]
Try as I might, I can't get focus working on window open as expected here. The DOM even reports the active element as the `viewerContainer` and yet scrolling fails.

Pressing <kbd>Tab</kbd> to shift the focused element, and then attempting to scroll, _does_ work though.

**Comment by kevinushey** [comment]
I don't think this one quite meets the bar for v1.2, so I'm going to punt.
