### ISSUE TITLE
Searching the history pane does not work

### ISSUE THREAD

**Issue by martinschmelzer** [rstudio/rstudio#2972]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.679
    OS Version      : Mac OS 10.13.4
    R Version       : 3.5.0

### Steps to reproduce the problem
Execute some code to fill the command history and then try searching for a certain line entered.

### Describe the problem in detail
I can input words to search for, but hitting the return key does not seem to work anymore.

### Describe the behavior you expected

Show me the lines of code where the command searched for was used.

**Comment by kevinushey** [comment]
Thanks for the bug report! Should be fixed in the next daily builds.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
