### ISSUE TITLE
Question: RStudio Server - Maximum Number of Concurrent Users

### ISSUE THREAD

**Issue by kmishra9** [rstudio/rstudio#2981]
Hey there,

I’m working on infrastructure for a Berkeley course for 300 students and was looking into potentially using RStudio server on a server w/ 512 GB of RAM and 24C/48T Xeon CPU. We would want the server to be able to handle at least 200 concurrent logins at once for assignments that would not be very computationally intensive (i.e. fitting lightweight linear models and manipulating up to 10 MB CSV files) and were wondering whether anyone has tried this?

Is there a rough estimate of how many concurrent users this server could handle? If we’re way off base, what would we need to handle that many students?

**Comment by jjallaire** [comment]
We used to run a beta server for courses like the one you describe which regularly had ~ 70 concurrent users on a 64GB machine with 8C and had no problems whatsoever. Others can speak for >= 200 concurrent users but there is nothing about the core server architecture that should be limiting here.

**Comment by kmishra9** [comment]
Thanks! That’s really helpful. 

I’m sure you’re also familiar with RStudio Cloud — in your opinion, do you think it would be a better/more straightforward solution for courses like these? Of course, its still in beta, but do you think its far enough along (from both a testing + support perspective) that it could accommodate something like the same 300 concurrent user use case? Much of our entire Biostatistics & Epidemiology department is shifting to R & RStudio this coming year for courses and building/maintaining our own server architecture w/ RStudio Server running on top would cost a pretty penny (roughly $30k amortized over 4-5 years). 

I’ve been investigating the merits of both approaches and I’m leaning towards RStudio Cloud but w/out a final word on what pricing will look like, knowing that building our own servers could be a viable solution moving forward is valuable.

**Comment by dfalty** [comment]
The cloud team should be reaching out to you regarding your question. If you have any others about cloud, a good place would be our community site. https://community.rstudio.com/c/rstudio-cloud
