### ISSUE TITLE
RStudio CRASHES on Start-up on Mac-------URGENT

### ISSUE THREAD

**Issue by BoKaiL** [rstudio/rstudio#2982]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453 - Mac OS X 10.6+ (64-bit)
    OS Version      : macOS High Sierra 10.13.2
    R Version       : 3.5.0

### Describe the problem in detail
A day before I run a long code on Rstudio and it caused forced-quit due to not enough memory. Then today I started it again, it just hung there forever. I tried to reinstall both Rstudio and R but it didn't work. and I tried the two lines I found on the previous community: "mv~/.rstudio-desktop~/backup-rstudio-desktop" and "open~/.rstudio-desktop". They all told me that there is no file or directory called rstudio-desktop. And all the issues reported online are not similar to my problem cause in my report most of the number starts with 0Xfffffff..... here is my report below:
[report.txt](https://github.com/rstudio/rstudio/files/2092367/report.txt)

Plz someone help me out of this misery. My project (life) depends on it. lol

Regards

**Comment by BoKaiL** [comment]
It is solved, kind of... I moved the very large .R file to another path and then when I open rstudio it asked that file is no longer in the current directory do I want to close it, then I closed it and it doesn't crash anymore. I mean, is this just due to lacking memory of my laptop? Is there any way to stop Rstudio from trying to run everything when it is started?

**Comment by jmcphers** [comment]
RStudio does restore all your working files by default so that you can pick up your work right where you left off. If you get into a state where your working set causes a problem, you can reset RStudio's state as described here:

https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
