### ISSUE TITLE
macOS 10.14 beta 1 "Dark Mode" dialogue text (+ a general "Appearance" thing)

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#2983]
Hey folks,

This is a "when macOS 10.14 gets closer to RC" thing since you need to focus on 1.2 for the folks who aren't insane.

Using the 1.2.730 daily in macOS Dark Mode and dealing with modals (like in rename file):

![image](https://user-images.githubusercontent.com/509878/41288318-e440b26c-6e13-11e8-9bce-83223fcb22ea.png)

That really says:

![image](https://user-images.githubusercontent.com/509878/41288329-ed1681be-6e13-11e8-990b-c8e95af69103.png)

As you can see the button text is also not visible.

And, apps are supposed to receive an event from the Appearance switcher in System Preferences and have things like dialogues have the proper light/dark appearance but this is also not happening.

I realize this is a Qt problem and not your problem, per-se, but just wanted to make you aware of it for your macOS 10.14 testing later this year and so you know you'll likely need to keep tabs on Qt.

-boB

**Comment by ronblum** [comment]
@hrbrmstr Thank you for the heads up!

**Comment by jmcphers** [comment]
This appears to be fixed in the latest RStudio dailies with the latest MacOS beta (18A384a). 

![image](https://user-images.githubusercontent.com/470418/45173017-d5df9300-b1bb-11e8-9954-951aab8ac53a.png)

@hrbrmstr can you confirm?

It looks like apps built against older SDKs (as we do) don't get dark mode support by default.

https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app

> Apps linked against macOS 10.14 or later should support both light and dark appearances. If you build your app against an earlier SDK, you can still enable Dark Mode support by including the NSRequiresAquaSystemAppearance key (with a value of false) in your app's Info.plist file. Do so only if your app's appearance looks correct when running in macOS 10.14 and later with Dark Mode enabled.

It'd be nice to add support (and I'll open a separate issue to do so), but we'll at least be legible until we do!

**Comment by hrbrmstr** [comment]
aye. Apple seems to have realized the world isn't going to just stop for them (many, many apps had this issue) and RStudio is looking 👍.

As an aside, since y'all're not listing the build system in the `Info.plist` I think you'll be able to skirt a few of the permissions issues I've been having with other apps. However, I have put RStudio.app (man ually) into the "Full Disk Access" bucket under the Privacy tab for good measure and will likely blog about suggesting other macOS folks do that once both 1.2 and 10.14 are out. (I realize we macOS folk are in the tiny minority of RStudio & R users but if I can relieve some frustration from even one other user it's cool).

**Comment by kevinushey** [comment]
I'm still seeing this issue with Mojave + the OS-level dark theme active:

<img width="406" alt="screen shot 2018-09-24 at 12 04 26 pm" src="https://user-images.githubusercontent.com/1976582/45972976-04e66900-bff2-11e8-83bc-e3e0d00edab4.png">

**Comment by hrbrmstr** [comment]
which dialogues? i use it daily and no text has been readable.

**Comment by ronblum** [comment]
I just tried a few on MacOS Mojave 10.14 public beta (18A389) using dark theme, yet the dialogs I've tried still show up as gray with readable text. Is there a setting I'm missing?

Here are some examples:

New file name:
<img width="398" alt="new_file_name" src="https://user-images.githubusercontent.com/31009952/46015472-5f3e0300-c0a0-11e8-8bfc-540349e5df0e.png">

Create new project
<img width="520" alt="new_project" src="https://user-images.githubusercontent.com/31009952/46015468-5f3e0300-c0a0-11e8-9f2a-972e442fb2c5.png">

Change terminal name:
<img width="392" alt="terminal_name" src="https://user-images.githubusercontent.com/31009952/46015469-5f3e0300-c0a0-11e8-9849-270402f60a1e.png">

Save file:
<img width="343" alt="save_as" src="https://user-images.githubusercontent.com/31009952/46015470-5f3e0300-c0a0-11e8-8988-13edf8fb0e9e.png">

**Comment by hrbrmstr** [comment]
I just ran through those and a few more and they're all 👍 on my Mojave RC.

**Comment by kevinushey** [comment]
Suddenly it's all working fine on my machine as well. I don't recall installing any OS updates or doing anything wonky; only real change was playing with the AppleFontSmoothing setting a bit.

For the record, I was running:

    .rs.api.showPrompt("Title", "Message")

**Comment by kevinushey** [comment]
I'm seeing it again now! For the record, I'm running with my MBP hooked up to a regular DPI display, not a high DPI display. Maybe that's the main difference?

**Comment by kevinushey** [comment]
One other data point: I'm using locally-built copies of RStudio; built against the system macOS SDK (and so 10.14 for Mojave). I suspect Apple turns on dark mode theming options when built against this SDK, but turns it off for applications built against older SDKs.

So this issue should (hopefully) not show its head in the wild.

**Comment by jmcphers** [comment]
> One other data point: I'm using locally-built copies of RStudio; built against the system macOS SDK (and so 10.14 for Mojave). I suspect Apple turns on dark mode theming options when built against this SDK, but turns it off for applications built against older SDKs.

That's exactly correct. :-)

https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app

**Comment by kevinushey** [comment]
I think we can close this. If we want to support dark themes for UI elements with Mojave, we're also going to have to take a Qt update, and I think we're still skittish about doing that so close to the RStudio release. (I don't think Qt 5.12.0 even has support for Mojave dark themes baked in quite yet either)
