### ISSUE TITLE
Can not scroll in editor on ipad pro

### ISSUE THREAD

**Issue by kkleinoros** [rstudio/rstudio#2984]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem
Tap editor can not scroll up or down

### Describe the problem in detail
In the other panes I am able to scroll up and down except the editor pane

**Comment by gtritchie** [comment]
This is now working in Safari on iOS12 and iPadOS 13.1, with RStudio 1.3.464. Likely due to our Ace upgrade.

**Comment by ronblum** [comment]
Verified with iPadOS 13.3.1 connected to RStudio Server 1.3.929 on Red Hat 7.8.

**Comment by raubreywhite** [comment]
@gtritchie This is broken again.

iPadOS 13.4 connected to RStudio Server 1.3.959 on Ubuntu 20.

**Comment by gtritchie** [comment]
Not able to reproduce with RStudio 1.3.1054 using iPadOS 13.5.1. I am able to scroll in the editor using touch.

**Comment by raubreywhite** [comment]
@gtritchie I just updated my iPad to 13.5.1.

You are correct that it works using *touch*, but it doesn't work using my Magic Keyboard trackpad.

**Comment by gtritchie** [comment]
Ah, I see. This issue is specific to touch scrolling (I will update the title to make that clearer).

Mousewheel/trackpad scrolling issue is #6581
