### ISSUE TITLE
Jobs: Consider `show` parameter in `addJob` API to avoid opening jobs panel.

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#2985]
Repro:

```
job <- .rs.api.addJob("sparklyr", running = TRUE, progressUnits = 100L)
.rs.api.addJobProgress(job, 20)
```

Actual: Focus moves away from console
Expected: Focus to stay in console or allow override with `show = FALSE` or alike parameter.

For packages considering using the Jobs API, like `sparklyr`, it would be too distracting to show progress since by default we take focus out of the console. Some jobs in `sparklyr` take a few milliseconds while others might last hors. For the short ones, it would be too annoying to see the focus moving to the jobs panel.

Should we add a `show = TRUE` parameter to customize if tho jobs pane should be shown?

**Comment by kevinushey** [comment]
If we choose `show = FALSE`, it'd be nice if we had some minimal UI to indicate that there was 'activity' in a tab (e.g. giving the tab a light highlight, to be removed the next time the tab is activated)

**Comment by jmcphers** [comment]
> it'd be nice if we had some minimal UI to indicate that there was 'activity'

This already kind of exists, in the form of a progress bar that is drawn on the R console as soon as the job starts running. It'd be nice to draw something on the tab, too (I've got a note in my backlog).
