### ISSUE TITLE
Install packages pop up window just vanishes away without giving enough time to see the errors

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/rstudio#2989]
rstudio-server  version 1.1.453 (Professional)

Was trying to publish the app and then it asked to install Rcurl,pki and reconnect package. Clicked on yes and then it started to install the packages and before I could see the errors those were generated the window vanished. 

This is not a good user experience as it doesn't lets the user see the errors.

**Comment by jmcphers** [comment]
Tracked in https://github.com/rstudio/rstudio/issues/5584 (and soon to be fixed!)
