### ISSUE TITLE
Standalone VCS (git or svn) gui

### ISSUE THREAD

**Issue by tbrugz** [rstudio/rstudio#3000]
Rstudio currently has "views" to interact with git and svn repos inside the ide. Rstudio vcs gui is very good and it would be really nice to use it on non-R git (or svn) projects. Maybe a good approach could be
to create a new standalone executable to lauch only the VCS/SCM views (without the need for a `.Rproj` file)

Previous rstudio community topic: https://community.rstudio.com/t/rstudio-standalone-vcs-gui/8942

**Comment by jmcphers** [comment]
This is a neat idea but probably not something we will do. There are already a lot of standalone VCS GUIs that have feature sets outside the scope of what we could provide. Try SourceTree, GitKraken, or Sublime Merge!
