### ISSUE TITLE
website publish button not tracking to website for knit of single website page

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#3001]
Currently, if you execute **Build Website** you get a Publish button that uses index.Rmd as it's deployment document.

However, there are a couple of other scenarios where the Publish button doesn't have the right behavior:

1) If you perform a Knit of a document at the top level of the website (e.g. about.Rmd), you still get a Publish Website button but the IDE thinks it's a brand new website (i.e. it doesn't see `rsconnect/documents/index.Rmd` as a publish of the same website.

2) If you perform a Knit of an Rmd file in a subdirectory (e.g. a blog post) then the IDE doesn't see the document as part of a website but rather an individual .html file to be published (this isn't entirely surprising b/c the notion of Rmd files in subdirectories is a new one for R Markdown websites).

Here's a website project you can see both of these behaviors exhibited within: https://github.com/radixpub/radix-r/tree/master/examples/websites/reproducible-finance-with-r (the `_posts` directory has a few subdirectories which have individual documents).

**Comment by gtritchie** [comment]
While investigating, saw some other quirky behavior that may be related: https://github.com/rstudio/rstudio/issues/3345
