### ISSUE TITLE
"Run all chunks above" doesn't work for RMarkdown

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#3004]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.2.679, Build 680 (415a39c1)
    OS Version      : MacOS 10.12.6
    R Version       : 3.5

### Steps to reproduce the problem
1. open a RMarkdown document with code chunks
2. locate cursor to middle of document, click the toolbar button "Run all chunks above" from toolbar Run drop down list.
3. nothing happens.
4. the toolbar icon "run all chunks above" inside the code chunk did work.

**Comment by kevinushey** [comment]
This works as expected on my machine, with the latest RStudio daily + macOS 10.13.5. For example, with the document:

`````
---
title: "R Notebook"
output: html_notebook
---

```{r}
print("1")
```

```{r}
print("2")
```

```{r}
print("3")
```

```{r}
print("4")
```

```{r}
print("5")
```
`````

If I place the cursor in the third chunk and press <kbd>Command + Option + P</kbd> to run the chunks above, it runs the two chunks successfully. Does that example work in your case?

**Comment by dracodoc** [comment]
No, it didn't work, either through keyboard shortcut, toolbar button in toolbar or even the button in chunk.

I checked the log of rstudio:
<img width="420" alt="screen shot 2018-06-14 at 1 26 56 pm" src="https://user-images.githubusercontent.com/1730496/41428021-ca9cc67e-6fd6-11e8-828c-799a6f315ec1.png">

The left side events were caused by clicking "run current chunk", which did execute and generated events. 

The right side exception was caused by clicking "run all chunks above", and nothing happened. This is the content of that exception (I cannot copy it, have to take screen shot)

<img width="379" alt="screen shot 2018-06-14 at 1 32 05 pm" src="https://user-images.githubusercontent.com/1730496/41428231-66b6192a-6fd7-11e8-9dfd-7de99aa72ce8.png">
<img width="377" alt="screen shot 2018-06-14 at 1 32 19 pm" src="https://user-images.githubusercontent.com/1730496/41428237-68e7cebe-6fd7-11e8-97de-f42020587503.png">

**Comment by rmflight** [comment]
I'm having the same issue on v 1.2.711, Ubuntu 16.04.

**Comment by kevinushey** [comment]
What does the gear menu show in your case? E.g. I have:

<img width="269" alt="screen shot 2018-06-14 at 12 38 35 pm" src="https://user-images.githubusercontent.com/1976582/41434234-e89f50f8-6fcf-11e8-9fc7-1054af1c655e.png">

**Comment by rmflight** [comment]
This is mine:

![rstudio_gear](https://user-images.githubusercontent.com/1509626/41434434-b8d4c398-6fe9-11e8-8845-c77a79ad82bc.png)

Looks like I am missing:

* Expand / Collapse All Output

* Clear / Clear All

**Comment by kevinushey** [comment]
Thanks! It looks like this specifically affected Notebooks where the `Chunk Output in Console` preference was set; things work as expected with `Chunk Output Inline`.

I've just pushed a fix and this will become part of the next daily builds. Thanks for reporting!

**Comment by jmcphers** [comment]
Fixed by @kevinushey in https://github.com/rstudio/rstudio/commit/5a8fcc2bb825cc6dd4384a94ae0da1615f5704ef.

**Comment by kelsimp** [comment]
> No, it didn't work, either through keyboard shortcut, toolbar button in toolbar or even the button in chunk.
> 
> I checked the log of rstudio:
> <img alt="screen shot 2018-06-14 at 1 26 56 pm" width="420" src="https://user-images.githubusercontent.com/1730496/41428021-ca9cc67e-6fd6-11e8-828c-799a6f315ec1.png">
> 
> The left side events were caused by clicking "run current chunk", which did execute and generated events.
> 
> The right side exception was caused by clicking "run all chunks above", and nothing happened. This is the content of that exception (I cannot copy it, have to take screen shot)
> 
> <img alt="screen shot 2018-06-14 at 1 32 05 pm" width="379" src="https://user-images.githubusercontent.com/1730496/41428231-66b6192a-6fd7-11e8-9dfd-7de99aa72ce8.png">
> 
> <img alt="screen shot 2018-06-14 at 1 32 19 pm" width="377" src="https://user-images.githubusercontent.com/1730496/41428237-68e7cebe-6fd7-11e8-97de-f42020587503.png">

I'm having this same problem. how did you resolve it?

**Comment by dkStevensNZed** [comment]
I'm having the same problem. I can execute the entire doc using Ctrl-Shift-k but within a chunk neither Ctrl-Enter, the buttons at the upper right (execute above, execute current), nor Ctrl-Alt-P (run all chunks above) do anything - no response at the console or R markdown tab. Ctrl-Enter works normally in a 'normal' R session.

**Comment by kasheehy** [comment]
I also was having this issue. Realized that one of the last code chunks in my rmd didn't have the three closing ticks ```. Adding those instantly let me run all chunks above. Was inspired to go through all my code looking for non-r chunks and caught the missing ticks thanks to this post: https://github.com/rstudio/rstudio/issues/11995
