### ISSUE TITLE
options("error") ignored by RStudio 

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#3007]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.679
    OS Version      :  Ubuntu 16:04
    R Version       :  3.4.4

### Steps to reproduce the problem

1. In your `.Rprofile` set an option for the error, e.g.

```
options(error = function(i) message("Bad luck"))
```

2. Open RStudio, and Debug, set "On error -> message only"
3. Restart RStudio
4. In the R console
```
options("error")
```
gives NULL

### Describe the problem in detail

`options("error")` returns NULL

### Describe the behaviour you expected

`options("error")` should return the function set in the .Rprofile (try it in a vanilla R terminal).

----
Originally discussed at https://github.com/HenrikBengtsson/startup/issues/59

**Comment by kevinushey** [comment]
This is the expected behavior -- the `On Error` options intentionally set (or unset, in the case of `Message only`) the error handler.

**Comment by jmcphers** [comment]
Yes, this is by design. We could probably improve the UI a little, though -- maybe if we had a "custom handler" entry in the error handler menu, it'd be clearer that selecting one of RStudio's error handlers switches the handler away from a custom handler if one is set.

**Comment by csgillespie** [comment]
I now understand that it's expect but a

**Comment by csgillespie** [comment]
@jmcphers @ke*vinushey After I select a debug option via RStudio,  I can't unselect it. What this means is, 

 * When I initially launch RStudio for the first time, error in `.Rprofile` is respected.
  * When I select a debug option in RStudio, the error option is ignored by RStudio, and this selection can't be reversed, so I can never retrieve the error option. 

This sounds like a bug?
