### ISSUE TITLE
Improve experience when starting sessions with large data

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3013]
Today, when starting a session that contains a lot of data--for example when resuming a large suspended session, or starting a session in a project directory with a large .Rdata file--the R session can take a very long time to start. If the data is on a slow or overworked NFS mount, it can take many minutes. 

This is somewhat surmountable in Server Pro, where's it's possible to go to `/home/` and get work done on a different session. However it's less so in open source; if you have a session that effectively hangs on load, your only recourse is to go to the file system directly and remove the data (which might be somewhat deep in `~/.rstudio`). 

### Cancellable session load

One possible mitigation which wouldn't be too difficult would be to do the following:

1. On the loading-spinner page, show the size of the session that's being loaded. R doesn't give us any progress hooks that I can find, but seeing that e.g. 2GB of data is being read might help users realize why things are taking so long.
2. On that same page, add buttons that make it possible to (a) skip the loading the data (which would result in restarting the session with an option that bypasses it), and/or (b) abandon the session and replace it with a fresh one.

### Async and progress

Ideally, of course, we wouldn't block on load at all--we'd start the UI immediately and allow users to begin working while we load the data in the background, showing progress as objects are read. This is not likely to be achievable without considerable effort however (for example we'd probably need to take much finer grained control over serialization) and whether it'd be more useful is an open question (if you need the data to work, you can't do anything until it's all loaded anyway).

**Comment by jmcphers** [comment]
Note from earlier conversation with @m--; this behavior needs to be controllable via the query string (i.e. you should be able to pass some query params and have the session load in safe mode as a result)

**Comment by jmcphers** [comment]
This was fixed in https://github.com/rstudio/rstudio/pull/4338. I have opened https://github.com/rstudio/rstudio/issues/4345 to track the async work.

**Comment by tmcduff** [comment]
Verified in: Version 1.3.743
