### ISSUE TITLE
Add tutorial overlay / workflow videos

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#3018]
With _RStudio_ continually adding new options with every 1.x build, it would be nice to have a tutorial overlay for new users. For instance, one part of the UI would be highlighted while a transparent black background would obfuscate the other elements. A brief snippet of text could describe the area.

Example: Photoshop CC 2018

![screen shot 2018-06-16 at 4 12 54 pm](https://user-images.githubusercontent.com/833642/41502475-4389197a-7180-11e8-8c71-02996d56336f.png)

Alternatively, consider adding workflow tutorial videos related to RMarkdown, connections, and VCS.

**Comment by jmcphers** [comment]
The IDE's getting a Tutorial pane and related features in RStudio 1.3 (which we are tracking separately). See https://github.com/rstudio/rstudio/pull/5774.
