### ISSUE TITLE
RStudio input focus doesn't follow mouse

### ISSUE THREAD

**Issue by JamesFrew** [rstudio/rstudio#3020]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : OS X 10.11.6
    R Version       : 3.5.0

### Steps to reproduce the problem

1. click in an RStudio editor tab and type something
2. click in/on another Mac app (i.e. switch input focus away from RStudio)
3. click in an RStudio console tab and start typing
4. oops. you're actually typing at the last cursor position in the editor tab

### Describe the problem in detail

(see above)

### Describe the behavior you expected

When I click in a tab, I expect the input focus to switch to that tab, not to some other tab that I was previously typing in.

**Comment by kevinushey** [comment]
It looks like this will be resolved in the next release of RStudio. If you have time, can you try testing our latest daily builds and let us know if the issue seems resolved for you there as well?

https://dailies.rstudio.com/

**Comment by dfalty** [comment]
I see this as fixed on the latest 1.2 release. Let us know if you see otherwise!

**Comment by JamesFrew** [comment]
The 1.2.xxx dailies require OS X 10.12 or higher; I'm running 10.11. Will the 1.2 release require 10.12? (If so, why?)
