### ISSUE TITLE
Support for Jupyter notebooks in RStudio

### ISSUE THREAD

**Issue by mwouts** [rstudio/rstudio#3021]
Hello, I just coded a [converter](https://github.com/mwouts/nbrmd) between R markdown notebooks and Jupyter notebooks. While doing this I realized that it could be worth offering support for both formats on the two platforms. 

May I get your feedback on this question, here or at https://github.com/mwouts/nbrmd/issues/1 ?
Thanks

**Comment by jmcphers** [comment]
Will reply over there, thanks.

**Comment by mwouts** [comment]
Thanks @jmcphers for your interesting answer. I was not aware that the `.nb.html` format was so well documented ! I agree that nb html format is a good complement to simpler (and so much efficient) R markdown.

I also understand that jupyter notebooks seem a bit far away from rstudio. 

For now I will thus continue to get more experience with the converters. I found a few more of them, so I give references below if they can be of use to anyone interested in switching between Jupyter and R markdown
- https://github.com/grst/ipymd converts between `.Rmd`, `.nb.html` and `.ipynb`. It allows loading of `.Rmd` files in the jupyter interface with no conversion required.
- https://github.com/aaren/notedown converts `.md` and `.Rmd` to  `.ipynb`, and also allows `.Rmd` files to be loaded/saved from jupyter
- https://github.com/chronitis/ipyrmd

Regards,
