### ISSUE TITLE
Updating packages breaks all active sessions 

### ISSUE THREAD

**Issue by andzandz11** [rstudio/rstudio#3022]
### System details
Desktop Win10
Version 1.1.453 – © 2009-2018 RStudio, Inc.
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1

### Steps to reproduce the problem
try to install a package that is in use in another session (instance of RStudio.exe)

### Describe the problem in detail
if I try to update a package that is used in another instance of RStudio.exe RStudio wipes the package folder but hangs at certian .dll files so it throws an error that the install could not be completed
meanwhile: the other active sessions can not library(x) the package any more because the package folder is empty, this breaks all other running scripts

### Describe the behavior you expected
i expect RStudio to check if the .dll package files are locked BEFORE all other package files are deleted to enable compatibility to running sessions

**Comment by ronblum** [comment]
@andzandz11 Thanks for reporting the issue. Can you please provide a reproducible example?

**Comment by andzandz11** [comment]
1) packge zoo works and is loaded in another R-Studio instance
2) I try to install zoo and it works (kinda)

Installing 1 package: zoo
package ‘zoo’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘zoo’

3) now zoo is broken and there is only the .dll file left in the zoo package folder

**Comment by ronblum** [comment]
@andzandz11 Thank you for the reproducible steps. What happens if you try to do the same with multiple instances of standalone R, outside of RStudio?

**Comment by jmcphers** [comment]
No response in many months, closing.

**Comment by andzandz11** [comment]
This has been fixed in the meantime. A failed package install now triggers a rollback.

**Comment by kevinushey** [comment]
More specifically, this is fixed via R's staged installs with newer versions of R. R now only overwrites a pre-existing package if installation fully completes successfully.
