### ISSUE TITLE
Re-enable browser developer tools

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3023]
We currently disable browser developer tools in release builds because of security concerns. 

https://github.com/rstudio/rstudio/blob/3d76fd0bb4b4d40f6fea6f5cc57e5122c691751b/src/cpp/desktop/DesktopMain.cpp#L241-L250

However, in Qt 5.11, these concerns are less relevant, because it's possible to run the devtools embedded, without opening up a separate browser/port.

> Embedded DevTools without using a port and separate browser.

https://wiki.qt.io/New_Features_in_Qt_5.11

Many people find the devtools very useful for debugging web content inside RStudio, so we should at least make it possible to turn them on (if not outright enable them by default).

**Comment by kevinushey** [comment]
For a bit more context, from the change log (https://code.qt.io/cgit/qt/qtwebengine.git/tree/dist/changes-5.11.0):

```
- [QTBUG-47899, QTBUG-50725, QTBUG-50766] QWebEnginePage::setInspectedPage(),
  QWebEnginePage::setDevToolsPage() can be set to programmatically set up
  a devtools page.
```

**Comment by kevinushey** [comment]
Implemented with https://github.com/rstudio/rstudio/commit/07d7bad993c361c45380089e83b9bed87b95b3ac.
