### ISSUE TITLE
It would throw an encoding error when debugging certain scripts with 'non-ASCII' characters in RStudio

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#3026]
### System details

    RStudio Edition : Desktop
    RStudio Version : `1.1.453`
    OS Version      : `x86_64-w64-mingw32/x64 (64-bit)`
    R Version       : `3.5.0`

### Steps to reproduce the problem

Debugging the following script will result in an error (save as `testscript.R` with `UTF-8` encoding):

```r
ability_components <- list(
  blai = c("注意力", "记忆力", "反应力", "自控力", "思维力"),
  math = c("数字加工", "数学推理", "空间几何", "数量加工", "数学计算")
)
```

```r
debugSource('~/test/testscript.R', encoding = 'UTF-8', echo=TRUE)
#> Error in parse(filename, encoding = encoding) : 
#>  invalid multibyte character in parser at line 2
```

<details>
<summary> `sessionInfo()`: </summary>

```r
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_11.0.0     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.19
```
</details>

**Comment by psychelzh** [comment]
But when the script is simple enough, e.g., just one line of `test <- "测试"`, there will be no error when debugging.

**Comment by psychelzh** [comment]
Here list all the `non-ASCII` encoding problems: #2998 #1866 #1847

**Comment by ronblum** [comment]
Thanks @psychelzh for reporting the issue. I am able to reproduce the issue on Windows 10, both in RStudio 1.1.453 and 1.2.750, However, it only occurs when setting the locale/language to Chinese (simplified). It t is not a problem when the locale is English (United States).

**Comment by jmcphers** [comment]
@psychelzh What does this return for you?

    parse('~/test/testscript.R', encoding = 'UTF-8')

This is effectively what RStudio's doing internally.

**Comment by psychelzh** [comment]
Confirmed this is a bug with the function `debugSource()`. There is no error for base function `source()`.

**Comment by ekatko1** [comment]
FYI, as a workaround, you can use `browse()` instead of RStudio's breakpoints.

**Comment by Mojert** [comment]
I'd like to add to what @psychelzh already said and answer @jmcphers's question.

### System details
```
RStudio Edition : Desktop
RStudio Version : `1.4.1717`
OS Version      : `x86_64-w64-mingw32/x64 (64-bit)`
R Version       : `4.1.1`
```

<details>
<summary>sessionInfo()</summary>

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=French_Switzerland.1252  LC_CTYPE=French_Switzerland.1252    LC_MONETARY=French_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=French_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testit_0.13    stringi_1.7.5  stringr_1.4.0  openxlsx_4.2.4

loaded via a namespace (and not attached):
[1] compiler_4.1.1 magrittr_2.0.1 tools_4.1.1    Rcpp_1.0.7     vctrs_0.3.8    zip_2.2.0      rlang_0.4.12  
```
</details>

### Steps to reproduce the problem
The following script (saved in `reproducible_error.r` with UTF-8)
``` r
variable.bogué <- ":("
```
run with
``` r
debugSource("reprodusible_error.r", encoding = 'UTF-8')
```
result in an error
```
Error in parse(filename, encoding = encoding) : 
 reprodusible_error.r:1:14: unexpected input
1: variable.boguÃ©
                 ^
```
while running it with
``` r
source("reprodusible_error.r", encoding = 'UTF-8')
```
does not.

Interestingly enough, not all Unicode character seem to make `debugSource()` bug in the same way.
The following script
``` r
µ <- "bug"
```
will run but assign `"bug"` to a variable named `Âµ` instead of `µ`.

### Answer to @jmcphers 
Running `parse()` with @psychelzh's original script, my first and second scripts respectively prints the following:

```
expression(ability_components <- list(
  blai = c("<U+6CE8><U+610F><U+529B>", "<U+8BB0><U+5FC6><U+529B>", "<U+53CD><U+5E94><U+529B>", "<U+81EA><U+63A7><U+529B>", "<U+601D><U+7EF4><U+529B>"),
  math = c("<U+6570><U+5B57><U+52A0><U+5DE5>", "<U+6570><U+5B66><U+63A8><U+7406>", "<U+7A7A><U+95F4><U+51E0><U+4F55>", "<U+6570><U+91CF><U+52A0><U+5DE5>", "<U+6570><U+5B66><U+8BA1><U+7B97>")
))
```
```
Error in parse("reprodusible_error.r", encoding = "UTF-8") : 
  reprodusible_error.r:1:14: unexpected input
1: variable.boguÃ©
                 ^
```
```
expression(µ <- "bug")
```

However note that for me, @psychelzh's script runs flawlessly when using `debugSource()` but not when using `source()`.

**Comment by kevinushey** [comment]
If we're lucky, this will probably work fine with the next release of R, which will use Windows UCRT for UTF-8 support (and the next releases of RStudio should have support for this as well).

**Comment by Mojert** [comment]
Let's hope then 🤞

**Comment by psychelzh** [comment]
Currently, R 4.2.0 is shipping with UCRT for UTF-8 support for windows, so this issue is out of the question.
