### ISSUE TITLE
.Rprofile found in project-directory while not working in project

### ISSUE THREAD

**Issue by EmilBode** [rstudio/rstudio#3027]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : 10.13.5
    R Version       : 3.5.0

### Steps to reproduce the problem
1. Create a new project (from existing directory seperate from standard working-directory, not sure if this matters), with a custom .Rprofile in this directory (bug is most noticeable if the code in it generates an error)
2. Close this project
3. Restart the R session (Session --> Restart R)

### Describe the problem in detail
At Step 3, the custom .Rprofile from the project is run, instead of (my regular) .Rprofile in my home-directory/working directory

### Describe the behavior you expected
The .Rprofile from my home-directory should be run. This does happen at step 2, when the (None)-project is correctly initialized.

### SessionInfo at different steps

sessionInfo() from project/step1:
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] roxygen2_6.0.1  devtools_1.13.5

loaded via a namespace (and not attached):
 [1] compiler_3.5.0 R6_2.2.2       magrittr_1.5   tools_3.5.0    withr_2.1.2    Rcpp_0.12.17   memoise_1.1.0  xml2_1.2.0    
 [9] stringi_1.2.2  stringr_1.3.1  digest_0.6.15  commonmark_1.5

sessionInfo at step 2:
Lines up to locale identical

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0

sessionInfo at step 3:
first lines again identical

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] roxygen2_6.0.1  devtools_1.13.5

loaded via a namespace (and not attached):
 [1] compiler_3.5.0 R6_2.2.2       magrittr_1.5   tools_3.5.0    withr_2.1.2    Rcpp_0.12.17   memoise_1.1.0  xml2_1.2.0    
 [9] stringi_1.2.2  stringr_1.3.1  digest_0.6.15  commonmark_1.5

### Relevant other information:

Environment variables are consistent along the steps:
HOME = /users/emilbode
R_HOME = /Library/Frameworks/R.framework/Resources
R.home(): /Library/Frameworks/R.framework/Resources
R_ENVIRON, R_ENVIRON_USER, R_PROFILE and  R_PROFILE_USER are unset

getwd() gives results as expected: /path/to/project at step 1, /users/emilbode at steps 2 and 3

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2115553/diagnostics-report.txt)

**Comment by kevinushey** [comment]
Thanks for the bug report!

I think the underlying issue here is that, when closing a project, RStudio preserves the last-used working directory (in this case, the project directory) and so launches R in that directory. When that is done, R loads the associated `.Rprofile` in that directory, as opposed to the (expected) home directory `.Rprofile`.

Normally, when RStudio opens a project, the working directory is changed to match the project directory. It seems that this doesn't happen when closing a project, while it probably should.

**Comment by EmilBode** [comment]
Something like that seems to happen, yes.
But I'm not sure if maybe R/Rstudio has multiple related concept of "working directory"/"launch-directory", because it does show the right working directory at both step 2 and 3 (before and after restarting) with getwd().

**Comment by EmilBode** [comment]
I've experimented some more, and it's interesting to see what happens if I add "print(getwd())" to .Rprofile (both versions):
In project as expected:
_Startup messages..._

[1] "/path/to/project"
> getwd()
[1] "/path/to/project"

When closing project, running getwd(), restart and getwd() again:
_Startup messages..._

[1] "/Users/emilbode"
> getwd()
[1] "/Users/emilbode"

Restarting R session...

[1] "/path/to/project"
> getwd()
[1] "/Users/emilbode"

Also interesting in this context to note is that when restarting a session, the working directory is kept, but when switching projects back and forth, it is discarded.

So what I guess that happens:
When closing/switching a project, RStudio initializes a new session:
- getwd() is run, its value is stored in some hidden variable, let's call it WD_INITIAL. This is ironically done to make sure that when restarting, the same startup-sequence is used, as R thinks it's being called from this directory.
- RStudio realises that when switching to (None)-project, it also needs to alter the working directory, so the right startup sequence is used. So it sets the working directory to USER_HOME
- .Rprofile is found in the working-directory, and loaded/executed.

When restarting:
- RStudio stores the current working directory 
- RStudio looks if WD_INITIAL is set. In this case, it is. So it thinks it should switch to this directory, to use the same startup sequence as before. So setwd(WD_INITIAL) is run. The working directory is now the project-path (_BUG_)
- There is no closing of a project, so RStudio does NOT set the working directory to USER_HOME
- Also there is no project to work in, so there is no need to specifically set a working directory.
- .Rprofile is found in the wrong working-directory (project-dir), and loaded/executed
- The working directory from the first step is restored.

So I guess the solution would be to switch the first 2 stept in the closing-project-process, so WD_INITIAL gets set to USER_HOME when closing a project. And when restarting, .Rprofile is run in USER_HOME
