### ISSUE TITLE
always ensure .Rprofile ends with trailing newline

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3029]
The last line of a `.Rprofile` is silently discarded if there is no trailing newline. To reproduce, from the command line:

```r
cd $TMPDIR
printf "%s\n%s\n%s" "print(1)" "print(2)" "print(3)" > .Rprofile
R
```

When run, R will print:

```r
[1] 1
[1] 2
```

omitting the final line. This can be quite confusing, especially if you have a `.Rprofile` with the contents:

```r
.First <- function() {
    # do the things
}
```

If there is no trailing newline, the definition of `.First` is never parsed and nothing happens.

**Comment by dfalty** [comment]
Verified fixed 1.2.1317-1
