### ISSUE TITLE
Unintentional requirement for macOS 10.12

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3031]
As discussed in #2693 some unintentional and unnecessary requirements for macOS 10.12 have crept in to 1.2. The goal is to support 10.11, which is the minimum version supported by Qt 5.10+.

This bug tracks tweaking our build system to correctly build binaries targeting 10.11; they are currently producing 10.12-specific binaries.

**Comment by jmcphers** [comment]
Qt 5.10 and 5.11 do support 10.11. Apple doesn't offer a specific support lifecycle anywhere I can find, and our OS support policy is to end support when the vendor does. Given that 10.11 is a 3-year-old desktop OS and that Apple offers no tools to help us support it (not even an installation ISO we could use to create a VM for testing), I think we should just drop support for 1.2.

**Comment by ronblum** [comment]
Verified.
