### ISSUE TITLE
Text with non-uniform spacing loses spaces when pasting in RStudio server's editor

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#3036]
In RStudio server accessed through Vivaldi browser (chromium-based), when attempting to copy-paste some long multi-line text with non-uniform spacing (e.g. some lines start with more tab-spaces or spaces than others) into the editor, they all lose their spacing at the start of each line. This behavior does not occur when the text to copy-paste is small though, and I'm not sure what characteristics or length does it need to have in order for it to be automatically reformated

**Steps to reproduce:**
* Write some multi-line text in RStudio local or some text edit.
* Copy it to the clipboard.
* Paste it into the RStudio editor in RStudio server accessed from Vivaldi browser.

**Expected behavior:**
* Text should copy-paste as it is.

**Actual behavior:**
* All spacing at the beginning of lines is set to one tab-space.*

**Reproducible:** with some inputs only.

**Setup:** RStudio server version 1.1.383, R version 3.3.3, running on Debian oldstable (Jessie), accessed from Vivaldi running chromium 67, in a linux system (Debian buster/sid) running KDE 5.12.5.

The following text produces this problem:
``` R
text <- "
  This line here starts with a tab
  This line also starts with a tab
  This line also starts with a tab
  This line also starts with a tab
  This line also starts with a tab
  This line also starts with a tab (
  	This line starts with two tabs
           This line has irregular spacing
  	This line starts with two tabs
  	This line starts with two tabs
  	This line starts with two tabs
  	JThis line starts with two tabs
  	This line starts with two tabs
         This line has irregular spacing
  	This line starts with two tabs
          This line has irregular spacing
  	This line starts with two tabs
  ) This line also starts with a tab
       This line has irregular spacing
  This line also starts with a tab NULL
        This line has irregular spacing
  "
```

**Comment by ronblum** [comment]
@david-cortes I was able to reproduce this on a different configuration, although in my case, the spacing disappeared entirely—no tabs or spaces. This with RStudio Server 1.2.747 on MacOS 12.10.6 (Sierra), using Google Chrome and Safari, both when copying directly or first copying to Word or Notepad (where it pasted fine) and then into RStudio. Note that removing the (needed) quotes makes the problem go away.

**Comment by ronblum** [comment]
And @david-cortes thank you for reporting the issue! We'll review it as we work on continued development of RStudio.

**Comment by kevinushey** [comment]
I can confirm with RStudio Desktop v1.1.453 on macOS that this seems to occur at random: if I copy and paste the text in the OPs post multiple times, about 10% of the time the indentation is preserved, and the other 90% of the time the indentation is lost.

I'll see if I can learn anything more -- thanks for reporting!
