### ISSUE TITLE
Black lines appearing at random in editor within code chunks

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#3043]
When viewing code chunks of a .Rmd file in the RStudio editor, oftentimes there appear some thin black lines inbetween code lines at seemingly random points. Their position changes as one scrolls through the editor, and sometimes they dissappear with every second scrolling roll - e.g. roll the mouse scrolling wheel, they appear, roll it again, they dissappear, roll it once more and they are back, etc.

Attached is a screenshot.
![glitches_rstudio](https://user-images.githubusercontent.com/11860098/41711719-0cfb48ac-7549-11e8-9852-7ec8ca3b9aa6.png)

**Steps to reproduce:**
* Create an rmarkdown file.
* Write something in there, create some code chunks.

**Expected behavior:**
* Code chunks should be displayed in a uniform background with no glitches.

**Actual behavior:**
* Some black lines appear separating sections of the code at seemingly random intervals.

**Reproducible:** sometimes depending on scrolling position.

**Setup:** RStudio preview version 1.2.747, R version 3.5.0, running on linux (debian buster/sid) with KDE 5.12.5.

**Comment by kevinushey** [comment]
Are you using a high DPI monitor, or do you have the IDE zoomed in / out at all?

**Comment by david-cortes** [comment]
@kevinushey : both actually (high DPI and zoomed in).

**Comment by ronblum** [comment]
@david-cortes Is this still an issue in the latest version of the 1.2 dailies, or is it resolved? There were a series of changes/fixes in the past few months, so hopefully this is resolved, as well.

**Comment by david-cortes** [comment]
Unfortunately, I no longer have access to a high DPI screen and will not able to tell if it's solved.

**Comment by jmcphers** [comment]
We haven't had any reports of this in well over a year, so hopefully it's solved. If you still see it, try switching to software rendering.

https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
