### ISSUE TITLE
Using tab to autocomplete with Google Drive File Stream causes RStudio to hang

### ISSUE THREAD

**Issue by mcooper** [rstudio/rstudio#3044]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.447
    OS Version      :  Windows 10
    R Version       :  3.4.4 (2018-03-15) -- "Someone to Lean On"

### Steps to reproduce the problem

Create a string representing a file path on Google Drive File Stream (for example when using `setwd()`).  Use tab to complete the file path and RStudio will hang for quite a long time.

### Describe the problem in detail

When using tab to autocomplete file paths that are in Google Drive File Stream (for example after typing `setwd("G://My Drive/`, RStudio hangs.  When using the basic R console (outside of RStudio), R is able to autocomplete quickly.  Similarly, using `list.files()` in RStudio returns all of the possible folders in a directory quickly.  But when using tab to autocomplete a file path in GDFS, RStudio will hang for several minutes.

As Google transitions from Drive to Drive File Stream, this is likely to become more of an issues for RStudio users in the future.

### Describe the behavior you expected

I expected RStudio to autocomplete quickly, as R does and as RStudio does for file paths on other drives.

1. The output of sessionInfo() 
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4    yaml_2.1.19  
```

2. The R code in question
`setwd("G://My Drive/")`

3. A diagnostics report;
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2123654/diagnostics-report.txt)

**Comment by kevinushey** [comment]
It might be useful if you could provide a profile of what's going on. Try following these steps:

First, run

```
Rprof("rstudio-profile.Rprof")
```

Then, try invoking the R completion code. After that finishes, run:

```
Rprof(NULL)
```

and please share the `rstudio-profile.Rprof` file with us.

**Comment by mcooper** [comment]
Here it is (as a txt file so Github would accept it).
[rstudio-profile.txt](https://github.com/rstudio/rstudio/files/2124658/rstudio-profile.txt)

**Comment by kevinushey** [comment]
The profile makes it clear that the slowness is in calling `file.info()`. (We use this to differentiate between files and directories)

Do you have a large number of files in this directory? Is an equivalent call of the form:

```r
file.info(list.files())
```

also slow?

**Comment by mcooper** [comment]
There are 440 files in the directory.  RStudio also hangs with fewer files but the duration of how long it hangs is proportional to the number in the directory.  However, the R Gui can instantly autocomplete in that same directory.

Both RStudio and the R Console hang when calling `file.info(list.files())`.  I'm not sure how easy it would be but if RStudio could autocomplete without calling `file.info()` that seems like it would solve it.  Or, if there could be an option to autocomplete using the R console and not RStudio.

Also, when using tab to autocomplete in RStudio, there is no "stop" button on the console indicating that something is running.  Typing `file.info(list.files())` on the other hand does create a "stop" button.  Because there is no "stop" button indicating that something is running, this bug is more confusing.
