### ISSUE TITLE
drag drop editor tabs no longer work

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#3045]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.2.747 Build 748 (2f330507)
    OS Version      : Macintosh; Intel Mac OS X 10_12_6
    R Version       : 3.5.0

### Steps to reproduce the problem
Until last preview version, tabs in editor can be rearranged by drag and drop. This doesn't work in this version.

**Comment by jmcphers** [comment]
We haven't been able to reproduce this on MacOS. :-/ Does it happen in all projects? A new session? Can you share a diagnostics report?

**Comment by dracodoc** [comment]
Interestingly, I no longer see this problem now. The difference between now and earlier when I found the problem is:
- after the upgrade to preview version, loading my current project will try to load a package then the console is like this:

```r
library(ctmm)
?
```
I also witnessed the problem with the dragging tabs at that time.

I cleaned my rstudio desktop folder and the package loading problem no longer appear, so I didn't report issue for that. 

It seemed that cleaning the desktop folder also solved the problem above.

**Comment by DanChaltiel** [comment]
I have a similar problem, I cannot rearrange tabs in editor by drag and drop. 

Drag and drop in the code editor is very buggy too and can only move the code one step away (a step being a mouse move, usually a single line with little to no control on the horizontal position).

Deleting the desktop folder (as in [here](https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State)) did not solve this.

Here is my session info:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base  
```
