### ISSUE TITLE
Win 7 mouse offset and toolbar overlay graphics problem

### ISSUE THREAD

**Issue by stephenll** [rstudio/rstudio#3054]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.769
    OS Version      : Win 7
    R Version       : 3.4.3

### Steps to reproduce the problem
Install the windows daily build: 1.2.769 (actually any version of 1.2 that is listed under dailies)
### Describe the problem in detail

To click on a tab I must click far below the tab to activate it.  There seems to be some sort of offset between the location of the mouse on the screen and where RStudio thinks it is.

![2018-06-22_13-26-45](https://user-images.githubusercontent.com/2936757/41790284-8bdfe076-7641-11e8-82e1-08faf36614e0.png)

So to click on the Terminal tab, I need to click where the mouse is in the pic.

Also, the chrome of windows 7 is overlapping with the RStudio Toolbar.

![2018-06-22_13-24-33](https://user-images.githubusercontent.com/2936757/41790218-54afd53e-7641-11e8-96c8-991add45670d.png)

This problem does not happen under Version 1.1. 

Please let me know if you need any additional info to diagnose.

**Comment by ronblum** [comment]
@stephenll Are you still running into this issue with the latest daily builds? There were a number of changes/fixes recently, so hopefully this is resolved.

**Comment by ronblum** [comment]
@stephenll Great—glad to hear it's all set!
