### ISSUE TITLE
RStudio Daily Build Never Loads

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#3063]
With daily builds (e.g., 1.2.771 but also Rstudio preview) on macOS (High Sierra) Rstudio often doesn't load. The 'spinner' just keeps spinning indefinitely. If I close Rstudio and then reopen it generally works. This happens with all Rstudio project directories and I do not use I do not use "Restore .RData" (see screenshot). I didn't see a response to post linked below on Rstudio Community and didn't see an issue so I thought it might be worthwhile to post this issue.

https://community.rstudio.com/t/rstudio-daily-build-never-loads/7972/3

![image](https://user-images.githubusercontent.com/2998956/41812468-34728108-76d8-11e8-8749-af80677e31d0.png)

**Comment by ronblum** [comment]
@vnijs Thank you for reporting this issue. It looks like there's now activity on the RStudio Community thread, so you might want to continue the conversation on there. Or, on here. In either case, can you upload your diagnostics report? Also, what version of R are you using, and have you had any issue with RStudio Desktop 1.1.453?

**Comment by vnijs** [comment]
See attached diagnostic report. No problems with 1.1.* release versions. Starting with 1.2 this issue came up. I try out the preview and daily builds regularly but keep reverting to 1.1.* 

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2138401/diagnostics-report.txt)

**Comment by vnijs** [comment]
FYI I just installed the daily build (1.2.832) and it seems Rstudio now starts up fine. Was something changed to address this issue?

**Comment by kevinushey** [comment]
@vnijs we recently fixed an issue that affected users with Mac Pros and AMD FirePro GPUs. Is that true in your case?

**Comment by vnijs** [comment]
Nope (see below). But Rstudio seems to start up just fine after installing the daily build and hour ago.

![image](https://user-images.githubusercontent.com/2998956/42861242-0b39038a-8a0f-11e8-9cf4-fb482ee6a648.png)

**Comment by gtritchie** [comment]
Sounds like this was resolved.
