### ISSUE TITLE
Files pane doesn't open non-rstudio associated files on click

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#3064]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.773
    OS Version      : Windows 10.0.17134 Build 17134
    R Version       : 3.5.0

In 1.1 when I click on any file that isn't openable in rstudio e.g. a .png, .pdf or .zip, it will open in whatever program it's associated with in Windows. But in 1.2 when I click on those files, nothing happens. On occasions it seems there is a slight stutter and something should be happening but it doesn't.

All files rstudio knows(.R, .txt, .gitignore etc) open as expected.

**Comment by ronblum** [comment]
Confirmed on Windows 7 and 10.

**Comment by sanjmeh** [comment]
Am not sure if there is another bug created by resolving this bug. I am on a MAC and clicking on any file in the file pane (.R or .csv) does not appear to have any effect. Normally the file should open up on the top left pane that is usually the editor or view pane.

**Comment by kevinushey** [comment]
Sounds like a different issue -- if you're willing, feel free to file a new bug report.
