### ISSUE TITLE
 Can't launch browser through RStudio's taskscheduleR

### ISSUE THREAD

**Issue by akalamoyo** [rstudio/rstudio#3067]
I'm trying to crawl data from a website using RSelenium. The script below runs perfectly in RStudio (R version 3.5.0 and RStudio Version 1.1.453) with no issues.

**Code**
library(RSelenium)
library(rvest)
library(xlsx)
library(XML)
library(RODBC)
library(taskscheduleR)
library(DBI)
library(odbc)

con <- dbConnect(odbc::odbc(), .connection_string = "Driver={ODBC Driver 11 for SQL Server};server=HG-SOS-MI;database=Data_Testing;trusted_connection=yes")

driver<- rsDriver()
browser <- driver[["client"]]
browser$navigate("www.nigerianstat.gov.ng/elibrary")
browser$maxWindowSize()

However, when I schedule it (for a routine task) using the built-in taskScheduleR addin, I get the following in the error log:

**Error Log**
Loading required package: methods Warning message: package 'DBI' was built under R version 3.4.4 Loading required package: xml2 Loading required package: rJava Loading required package: xlsxjars Warning messages: 1: package 'xlsx' was built under R version 3.4.3 2: package 'rJava' was built under R version 3.4.3

Attaching package: 'XML'

The following object is masked from 'package:rvest':

xml

Warning message: package 'taskscheduleR' was built under R version 3.4.3 checking Selenium Server versions: BEGIN: PREDOWNLOAD BEGIN: DOWNLOAD BEGIN: POSTDOWNLOAD checking chromedriver versions: BEGIN: PREDOWNLOAD BEGIN: DOWNLOAD BEGIN: POSTDOWNLOAD checking geckodriver versions: BEGIN: PREDOWNLOAD BEGIN: DOWNLOAD BEGIN: POSTDOWNLOAD checking phantomjs versions: BEGIN: PREDOWNLOAD BEGIN: DOWNLOAD BEGIN: POSTDOWNLOAD

**Error in subprocess::spawn_process(tfile, ...) : could not create process: Access is denied Calls: rsDriver ... spawn_tofile -> windows_spawn_tofile -> -> .Call Execution halted**

**Comment by ronblum** [comment]
@akalamoyo Are you able to run this in R, outside of RStudio?

**Comment by akalamoyo** [comment]
@ronblum Apologies for the delayed response. I'm able to run it in R. It works in RStudio too. However, when using the taskScheduler, I just get a blank prompt that flashes for a sec and disappears.

**Comment by jmcphers** [comment]
If it works in RStudio but not in taskscheduler, it is an issue with taskscheduler. We suggest opening an issue over there instead:

https://github.com/bnosac/taskscheduleR
