### ISSUE TITLE
Add SUSE to list of signature validation instructions

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3070]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.1.x and 1.2.x
    OS Version      : SUSE
    R Version       : N/A

### Steps to reproduce the problem

Go to https://www.rstudio.com/code-signing/

### Describe the problem in detail

Instructions aren't provided for validating signatures on SUSE.

### Describe the behavior you expected

OK, they are provided—they're just not labeled. They're the same as Red Hat and CentOS. So just change
```RedHat/CentOS```
to
```RedHat/CentOS/SUSE```

**Comment by jmcphers** [comment]
Fixed.
