### ISSUE TITLE
copy to recursion

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#3071]
If I select a directory, then click "copy to", the destination directory is under the directory to be copied. The result is that I can easily create recursive directories. I think the destination directory should be at the same level as the directory itself, so as to avoid the mistake of recursively copying a directory inside itself. (version 442)

![image](https://user-images.githubusercontent.com/7519295/41868952-81b9ee84-7885-11e8-9286-b4d70b3dbf28.png)

![image](https://user-images.githubusercontent.com/7519295/41868895-593628ba-7885-11e8-831e-fc3e01a7438d.png)

**Comment by ronblum** [comment]
Reproducible. And every time the copied subfolder is clicked, it's copied again as subfolder, and so on. Just clicking navigating down through (copied) subfolders—without choosing "Copy To"—shouldn't create new copies of itself.

**Comment by dfalty** [comment]
Verified fixed 1.2.1317-1
