### ISSUE TITLE
Can't open a Notebook's generated HTML file on Windows

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3072]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.774
    OS Version      : Windows 10
    R Version       : 3.5.0

### Steps to reproduce the problem

Generate an R Notebook file in Windows and try to view the resulting .nb.html file:

1. `File` -> `New File` -> `R Notebook`
2. `Preview`
3. Choose a file name, e.g. `my_little_file`
4. `Save`
5. Close the window that just opened which contains the Notebook output
6. In Files pane: click on .nb.html file, e.g. `my_little_file.nb.html`
7. In resulting drop-down menu: `View in Web Browser`
8. Wait a bit until the drop-down goes away
9. Click on the file name again
10. In resulting drop-down menu: `View in Web Browser`

### Describe the problem in detail

The first time around, clicking on "View in Web Browser" will keep the menu around for a few seconds and do nothing. The second time, the menu will disappear immediately but still do nothing.

### Describe the behavior you expected

The HTML file should open in a web browser. This works elsewhere: MacOS Desktop (Sierra 10.12.6), Linux Desktop (openSUSE 15.0), and Server (Ubuntu 16.04.4 from Windows using IE and Chrome).

This is a regression—it works in 1.1.453.

**Comment by jmcphers** [comment]
Should be fixed by Kevin's changes in #3074.

**Comment by ronblum** [comment]
Verified with RStudio Desktop 1.2.882 on Windows 7 and 10.
