### ISSUE TITLE
Add new-line source-editing shortcut

### ISSUE THREAD

**Issue by kjohnsen** [rstudio/rstudio#3075]
A typical thing I want to do when coding is begin a new line below or above where the cursor currently is, just like Vim does with [Shift]+O or Visual Studio Code does with Ctrl+[Shift]+Enter. This is so much easier than going up/down, then pressing End, then Enter.

**Comment by ronblum** [comment]
@kjohnsen Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.
