### ISSUE TITLE
Debugger mode for debugging C++ code

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3080]
Request from @hadley:

"With the terminal, I wonder if there's someway we could now have a debugger "mode" i.e. when I'm debugging C/C++ code, I launch `R --debugger=lldb` and then send everything using `cmd + alt + enter` instead of `cmd + shift + enter`.

I wonder if we could have a specialised mode that supported that somehow. Could use when debugging R code that seg-faults because of buggy C code.

**Comment by kevinushey** [comment]
This would be especially useful on Windows, although some extra magic would be required as R doesn't recognize the `-d` or `--debugger` arguments on Windows. (One can still launch `gdb.exe` as included in Rtools and use it to attach to an R process, though!)
