### ISSUE TITLE
Package Updater NEWS links broken

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#3082]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1 and 1.2
    OS Version      :  Windows 10
    R Version       :  3.5.0

In the Update Packages window, the NEWS icon will link to, for example, https://cran.rstudio.com/web/packages/nycflights13/news.html, instead of https://cran.rstudio.com/web/packages/nycflights13/news/news.html, which is the correct page for the NEWS file.

**Comment by ronblum** [comment]
@martj42 Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio. This is a known issue; unfortunately, the location of the "news" files is inconsistent. In some cases, they are located at `.../packages/news.html`, and in others `.../packages/news/news.html`. For example, the callr, sp, and survival follow the first format, while fs, pillar, and reticulate use the second format. Still a third set, such as bit, we have to pick one or the other of these. It's definitely frustrating.

**Comment by ronblum** [comment]
Verified with a bunch of packages.
