### ISSUE TITLE
Automatically deselect executed code section

### ISSUE THREAD

**Issue by mapinas** [rstudio/rstudio#3083]
After a piece of code has been selected and executed it would be great if the code was automatically deselected. It happens to me frequently that I believe the cursor is in the console or another window, only to then find that a large chunk of my code has been accidentally erased. There should not be many situations where it is desired to execute exactly the same piece of code twice anyways.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Debian
    R Version       :

**Comment by ronblum** [comment]
@mapinas Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.
