### ISSUE TITLE
Viewer should contain forward and back buttons

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#3087]
When previewing multiple page sites (e.g. with bookdown or blogdown), it would be very useful if the viewer pane had some basic navigation buttons (i.e. back and forward). It seems like this should be simple to expose since you can already navigate by right-clicking within the viewer.

**Comment by jjallaire** [comment]
One thing that makes this not simple is that we already have a back/forward mechanism that works with static HTML output. This is effectively a different stack which we’d have to merge with the browser stack.

As you point out we could easily just forward to the browser but the stacks wouldn’t be reconciled —- this would lead to surprising behavior on occasion but perhaps it’s worth this downside?

**Comment by hadley** [comment]
My feeling is that it's unlikely to cause too many surprises as in a given project, you're typically either working with one big site with multiple links, or many independent documents.
