### ISSUE TITLE
Cannot preview Rmd files under subdirectories in bookdown or blogdown projects

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#3089]
### System details

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.5, RStudio 1.2.679
```

### Steps to reproduce the problem

Reproducible example: [bookdown-minimal.zip](https://github.com/rstudio/rstudio/files/2146077/bookdown-minimal.zip)

Open the project. Open `sub/test.Rmd`, and click `Knit` button. In the viewer, there is only an error message:

```
/rmd_output/sub/test.html not found
```

### Describe the behavior you expected

Should preview the actual HTML output.

It also fails to preview PDF output.

**Comment by jjallaire** [comment]
This may have been fixed by a commit I made earlier today: https://github.com/rstudio/rstudio/commit/cf917504454926b13eaa93b127517a4aa7dd8321

Could you try the latest daily?

**Comment by yihui** [comment]
Just tested the latest daily. It seems to have been fixed. Thanks!
