### ISSUE TITLE
Suggest new pane at top right listing open editor/variable tabs

### ISSUE THREAD

**Issue by woodwards** [rstudio/rstudio#3092]
Suggested enhancement.

I am frequently running into problems when I have a lot of editor tabs (source files) and environment variable viewer tabs open. It's possible to see the list of open tabs by clicking the little ">>" button at the top right of the editor, but I suggest listing this information in a separate, persistent pane that I can have open at the top right (like the Environment or Files pane).

**Comment by ronblum** [comment]
@woodwards Thank you for the neat suggestion. We'll take a look at it as we work on future releases of RStudio.

**Comment by jmcphers** [comment]
This is a cool idea but hasn't received any upvotes or support in a year and a half, so not likely we'll get to it anytime soon; closing as out of scope.
