### ISSUE TITLE
Setting primary CRAN repository cause the option to disappear

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3097]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.778 and 1.2.789
    OS Version      : MacOS 10.12.6 and Windows 10
    R Version       : 3.5.0

### Steps to reproduce the problem

1. Tools -> Packages -> Change
2. Choose your favorite CRAN mirror
3. OK -> OK
4. `options("repos")`
   - Maybe the new repository will be listed, or maybe it'll show up as `"@CRAN@" `
5. Close RStudio
6. Open RStudio
   - Maybe everything will be fine, or maybe one of the problems below

### Describe the problem in detail

Sometimes, this happens when RStudio is restarted. The behavior is inconsistent, or at least I haven't been able to consistently reproduce it in the same environment at different times. [An animated GIF showing the problem occurring]( https://drive.google.com/open?id=1B-U7awcvZm1f7_MCiB98F2Nakk71ETtZ) is also available.

a. The following message will appear in the console:
```
WARNING: Your CRAN mirror is set to "@CRAN@" which has an insecure (non-HTTPS) URL. The repository was likely specified in .Rprofile or Rprofile.site so if you wish to change it you may need to edit one of those files. You should either switch to a repository that supports HTTPS or change your RStudio options to not require HTTPS downloads.

To learn more and/or disable this warning message see the "Use secure download method for HTTP" option in Tools -> Global Options -> Packages.
```
b. `Tools -> Packages -> Change` will show no repository at all (not even `-`)
c. `.../.rstudio-desktop/monitored/user-settings/user-settings` (and its Windows variant) will contain blank CRAN repo entries:
```
cranMirrorChanged="1"
cranMirrorCountry=""
cranMirrorHost=""
cranMirrorName=""
cranMirrorRepos=""
cranMirrorUrl="" 
```
d. When installing a package, R will ask for a CRAN mirror to be chosen, sometimes multiple times. For example, `install.packages("dpylr")` requests a CRAN mirror four times.

### Describe the behavior you expected

The currently defined primary repository should always be reflected in user-settings, even when changed, RStudio restarted, etc. It should be the default repository R points to.

**Comment by jmcphers** [comment]
Should be fixed by https://github.com/rstudio/rstudio/commit/63faefaf96fa7e677a04e06c4dbdd7557ec8eec2.
