### ISSUE TITLE
Copying markdown code into a new file reformats the code

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#3101]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1 and 1.2
    OS Version      :  Windows 10
    R Version       :  3.5.0

### Steps to reproduce the problem
1. Copy code from a .md or .Rmd file
2. Create new file in RStudio, don't save it
3. Paste the code into the new file 

### Describe the problem in detail
The code will get reformated, most notably some lines will get tab spaces in the beginning, which will break the code.

For example,

````
---
title: "Magma Demo"
output: html_document
---
```
{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
````
will turn into

````
---
  title: "Magma Demo"
output: html_document
---
  
  ```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```` 

and

```
---
__Advertisement :)__

- __[pica](https://nodeca.github.io/pica/demo/)__ - high quality and fast image
  resize in browser.
- __[babelfish](https://github.com/nodeca/babelfish/)__ - developer friendly
  i18n with plurals support and easy syntax.

You will like those projects!

---

# h1 Heading 8-)
## h2 Heading
### h3 Heading
#### h4 Heading
##### h5 Heading
###### h6 Heading
```

into

```
---
  __Advertisement :)__

- __[pica](https://nodeca.github.io/pica/demo/)__ - high quality and fast image
resize in browser.
- __[babelfish](https://github.com/nodeca/babelfish/)__ - developer friendly
i18n with plurals support and easy syntax.

You will like those projects!
  
  ---
  
  # h1 Heading 8-)
  ## h2 Heading
  ### h3 Heading
  #### h4 Heading
  ##### h5 Heading
  ###### h6 Heading
```
### Describe the behavior you expected
I would hope for the formatting to not change at all. Not a huge deal - a workaround is to first save the new file in the preferred format and then paste - but maybe this is something worth looking in to.

**Comment by martj42** [comment]
Eh, I just thought about it a little and, this isn't an issue. I'm just used to creating new files via the keyboard shortcuts, which defaults into an .R, which messes it up but I can just as well create the new file via the file menu where I can choose the type.

Disregard, please. 😄

**Comment by ronblum** [comment]
@martj42 No problem—glad this works for you. But you can also create a keyboard shortcut for creating R Notebooks, if that will make things easier for you: Tools -> Modify Keyboard Shortcuts -> New R Notebook. Hopefully this makes things a little easier for you!
