### ISSUE TITLE
Field names cover input fields in R task scheduler

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3103]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453 & 1.2.789
    OS Version      : Windows 10
    R Version       : 3.5.0

### Steps to reproduce the problem

1. `install.packages("taskscheduleR")`
2. Addins -> Schedule R scripts on Windows

### Describe the problem in detail

The names of the fields in the R task scheduler overlap with the input fields above them:

![taskschedulr_windows](https://user-images.githubusercontent.com/31009952/42172975-9e25279e-7deb-11e8-9ab0-6ed5e871b8d2.png)

### Describe the behavior you expected

Field names and the input fields should be separate.

This is not a regression, as it occurs in RStudio Desktop 1.1.453.

**Comment by kevinushey** [comment]
Looks fine for me:

![screen shot 2018-07-02 at 10 43 09 am](https://user-images.githubusercontent.com/1976582/42178321-c7bbb16a-7de4-11e8-9d45-7ff29b64ea89.png)

Any idea what might be different on your system?

**Comment by ronblum** [comment]
I had retina display turned off. I'm using VMWare 8.5.10. If I turn on full resolution
- Virtual Machine -> Settings -> Display -> Use full resolution for Retina Display

then it works if fine.

**Comment by ronblum** [comment]
One more, though: here's what it looks like if I turn on full Retina resolution but adjust the scaling to 150%:

<img width="520" alt="scheduling" src="https://user-images.githubusercontent.com/31009952/42328765-234c9864-803d-11e8-8131-af099e77eff3.png">

<img width="370" alt="scaling" src="https://user-images.githubusercontent.com/31009952/42328772-2569fe52-803d-11e8-9911-1c88f006a124.png">

**Comment by kevinushey** [comment]
For what it's worth, when testing this I was working with VMware Fusion on a regular DPI monitor.

I can reproduce the issue you're describing if I set the scale to 150%, so it may be an issue specifically caused by differences in scaling. (I originally had it at 100%, which is what Windows recommended for my setup)

**Comment by jmcphers** [comment]
This UI is wholly owned by the taskscheduler package and/or miniui.
