### ISSUE TITLE
Git in RStudio does not recognize path in UNC format when creating new "Version Control" project

### ISSUE THREAD

**Issue by johngoldin** [rstudio/rstudio#3105]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.423
    OS Version      : Windows 7 Enterprise Service Pack 1
    R Version       : 2.4.1

### Steps to reproduce the problem
Create a repo in Github. In Repo, click on the green clone or download button and copy the URL to the clipboard. 
Next, in RStudio, select New Project and select to create project from version control. Next select to clone a project from a Git Repository. 
Dialog appears. Paste in the repository URL copied via the green clone button.
Create the the project directory as folder in a Windows Server director structure.
For example: //yaleoir/OIR General/Datasets/Faculty-Staff Snapshots
Create the project.
The RStudio project gets created, but there is no Git tab so the IDE Git tools are not available.

### Describe the problem in detail
The problem is described in more technical detail than I can in [this RStudio Community post](https://community.rstudio.com/t/git-in-rstudio-does-not-recognize-path-in-unc-format/4414).

I am able to work around the problem by mapping a drive letter to the server folder.

Based on Jenny Bryan Happy Git suggestion, tried the following in RStudio terminal session:
 
git remote -v
response:
origin  https://git.yale.edu/goldin/test_poject.git (fetch)
origin  https://git.yale.edu/goldin/test_poject.git (push)

I take this to mean that Git knows something about my repository. But I don't see a Git tab in RStudio.
Although this example was done with git.yale.edu, I have had the exact same experience with github.com.

### Describe the behavior you expected

I am looking to be able to use the Git tab in the IDE. If I map my network drive to a drive letter, I am able to do that. But I am not able to do that if use the original path.
I am a novice Git user trying to encourage my co-workers who are even more novices than I am to use Git. Introducing the need to map the network folder to a drive letter makes an already intimidating process even trickier. I am looking to smooth out this bump.

**Comment by poppy-miller** [comment]
I'm facing the same issue. I've mapped by UNC path to a drive letter, but I need to remember to open via the drive letter every time I open something in RStudio. It is very frustrating opening a project (accidentally clicking on the UNC path to the project), working for a while, then realizing I need to reopen it using the drive letter path to commit to git. I am also trying to encourage my coworkers to use git, and agree that this issue will significantly reduce motivation to learn and use git.

**Comment by ronblum** [comment]
Reproduced in 1.1.463 and 1.2.1255 on Windows 10.

**Comment by msolgapavlova** [comment]
Reproduces in 1.4.1013 on Windows 10.

**Comment by burgerga** [comment]
Still an issude with RStudio 1.4, please reopen

**Comment by JsizzleR** [comment]
Support for UNC paths requested by Pro customer.
Ref No.  64063
