### ISSUE TITLE
Autocompletion of overridden function repeatedly generates errors

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3108]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.453 and 1.2.792
    OS Version      : MacOS 10.12.6 and Ubuntu 16.04.4
    R Version       : 3.5.0

### Steps to reproduce the problem

1. `quote <- function() { "WHAT"}`
2. `pri` <kbd>Delete</kbd> `i` <kbd>Delete</kbd> `i` <kbd>Delete</kbd> `i`
3. Clear the input
4. `abc` (pause) `defghi`
5. Clear the input
5. `quote()` <kbd>Return</kbd>

### Describe the problem in detail

An error message repeatedly gets displayed, along with the message "R code execution error":

```
Error in quote(.rs.normalizePath(filePath)) : 
  unused argument (.rs.normalizePath(filePath))
```

Step 6 results in `"WHAT"`, which I think means that the function got overridden successfully.

### Describe the behavior you expected

The error message shouldn't appear and keep repeating with every attempt at autocompletion. Redefining `quote()` may not be a good idea, but it shouldn't keep generating errors, especially on success.

-----

This is not a regression, as it occurs in 1.1.453, as well.

[See also Support issue 28445.]

**Comment by kevinushey** [comment]
This seems like an issue in R itself: R appears to discover the definition of `quote()` from the global environment when handling a warning, e.g.

```r
quote <- function(...) {
   print("I'm in yer quote, stealing yer expressions")
   base::quote(...)
}

warning("oops!")
```

Giving as output:

```r
> quote <- function(...) {
+    print("I'm in yer quote, stealing yer expressions")
+    base::quote(...)
+ }
> 
> warning("oops!")
[1] "I'm in yer quote, stealing yer expressions"
Warning in ... : oops!
```

We could work around this, but it is pretty surprising.
