### ISSUE TITLE
cannot add secondary CRAN repository if no primary CRAN repository

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3109]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.798
    OS Version      : macOS 10.13.5
    R Version       : 3.5.0

### Steps to reproduce the problem

From the main menu, `Tools -> Global Options... -> Packages -> Management`. Ensure that no primary CRAN repository is selected, and then attempt to press the <kbd>Add...</kbd> button for the secondary repos select box.

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

I think these are mainly around the state of the primary field in a brand new RStudio install. Some potential options:

1. Display a warning (you must define a primary CRAN repository before a secondary repository can be defined),

2. Toggle whether the buttons are enabled / disabled based on that field,

3. Populate the primary CRAN repository by default with the RStudio repository.

### Notes

Picture of the state of the pane with a brand new RStudio session.

![screen shot 2018-07-03 at 1 00 55 pm](https://user-images.githubusercontent.com/1976582/42241955-308db846-7ec1-11e8-94a7-d3675134bbf0.png)

**Comment by javierluraschi** [comment]
This is a duplicate of https://github.com/rstudio/rstudio/pull/3096, should be fixed now.

**Comment by kevinushey** [comment]
Sorry, but the issue as reported still exists in the current dailies.

**Comment by kevinushey** [comment]
Sorry, it looks like the issue is alleviated if the `~/.rstudio-desktop` folder is deleted now as you said. There's a chance some existing installs will still have the issue but it's probably not worth papering over since I imagine only a small subset of users are affected.

**Comment by ronblum** [comment]
Verified by first manipulating user settings to force no primary repository.
