### ISSUE TITLE
Snippets with R code changes special characters

### ISSUE THREAD

**Issue by charlycito** [rstudio/rstudio#3111]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.1.383
    OS Version      :  Windows 7
    R Version       :   3.4.2

### Steps to reproduce the problem
Snippets with that contains r code create encoding issues for special characters.

Consider this:
```
snippet new_script
	###############################################
	#  New script
	###############################################
        # Created by Örjan.
```

Results in:

```
###############################################
#  New script
###############################################
# Created by Örjan.
```

But if I want the snippet to add todays date the Ö disappears.
```
snippet new_script2
	###############################################
	#  New script
	###############################################
        # Created: `r paste(format(Sys.Date(), "%B %Y"))`  by Örjan

```

This results in:
Results in:
```
###############################################
#  New script
###############################################
# Created: juli 2018 by Ã–rjan.
```

### Describe the problem in detail
It is probably an encoding issue. My script is using ISO-8859-1.

### Describe the behavior you expected
That running r code in snippets do not affect other parts of the snippet.

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be fixed in the next daily builds of RStudio -- you can give them a try at https://dailies.rstudio.com.

Note that the builds are currently failing; we'll be investigating and trying to get the builds live again soon this week.

**Comment by ronblum** [comment]
Verified on MacOS 10.14 Mojave and Windows 7.
