### ISSUE TITLE
Crash when trying to use cronR add-in

### ISSUE THREAD

**Issue by alankjackson** [rstudio/rstudio#3112]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453 
    OS Version      : Ubuntu 18.04 LTS
    R Version       : 3.4.4 (2018-03-15)

### Steps to reproduce the problem
Add the add-in cronR
Open RStudio
Open add-in "Schedule R Scripts on Linux"
Click "Select File"
Crash!!

### Describe the problem in detail
Unable to run cronR from RStudio. Immediate crash with "floating point exception" when trying to select the input script.
cron_rstudioaddin() from the command line opens a browser tab in Chrome, and everything works fine from there.
In fact, all the cronR commands work fine from the R command line. 

### Describe the behavior you expected
I think that is obvious! 8-)

**Comment by pascaloettli** [comment]
Using development Version 1.2.679 on Ubuntu 18.04 LTS, I don't encounter a crash. If you can, you could try with the [development version](https://www.rstudio.com/products/rstudio/download/preview/) and report if you also get a crash.

**Comment by jmcphers** [comment]
No further reports and we haven't been able to repro, so closing. @alankjackson feel free to reopen if you're still seeing this on RStudio 1.2.5019 or newer.
