### ISSUE TITLE
Compiling rstudio on Centos 6 compatible server. Boost does not compile 

### ISSUE THREAD

**Issue by sacourtney** [rstudio/rstudio#3113]
RStudio Edition : Desktop
RStudio Version : 1.1.453
OS Version      : Scientific Linux release 6.8 (Carbon) (Centos 6 basically)
R Version       :  3.5.0

Downloaded rstudio-master.zip source code
unzipped it
cd /dependencies/common
./install-common

Build fails creating boost, with errors such as -
 :--------------------------------------------:
cc1plus: error: unrecognized command line option "-std=c++11"

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -fPIC -std=c++11 -DBOOST_ALL_NO_LIB=1 -DBOOST_ATOMIC_SOURCE -DBOOST_ATOMIC_STATIC_LINK=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/atomic/build/gcc-4.4.7/release/link-static/threading-multi/lockpool.o" "libs/atomic/src/lockpool.cpp"
 :--------------------------------------------:

Looking at it, its using the system wide gcc compiler (4.4.7) although I've tried to force it to use a newer compiler  (gcc/g++ version 4.8.1) using the exported variables for CC and CXX. 

The R install seems to ignore the CC and CXX variables so I cant build a compatible version.

Any suggestions to get around this ?

Cheers - Simon.

**Comment by kfeinauer** [comment]
This is what we do to get this to work on the CentOS 6 build:

```
# update gcc for C++11 support
wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
yum install -y devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++

# update environment to use new compiler
export PATH="/opt/rh/devtoolset-2/root/usr/bin:${PATH}"
export CC="/opt/rh/devtoolset-2/root/usr/bin/gcc"
export CXX="/opt/rh/devtoolset-2/root/usr/bin/c++"
export CPP="/opt/rh/devtoolset-2/root/usr/bin/cpp"
```

So, try ensuring the PATH and CPP variables are updated.

**Comment by jmcphers** [comment]
We can't generally offer support for compiling RStudio on this forum (it's specifically for RStudio product bugs). If @kfeinauer's suggestions don't help, you might try asking on our community forum:

https://community.rstudio.com/c/rstudio-ide
