### ISSUE TITLE
Python documentation not showing on the help pane

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#3114]
When running python interactively with `reticulate` (e.g. reticulate::repl_python()), trying to access the documentation for some object thorugh `?object` will not display anything, while doing `help(object)` will print it as a string in the console.

If, however, I point the current selection in the editor over the same object and press F1, it displays it in the help pane, and under some circumstances which I haven't been able to identify, will afterwards start displaying the help from `help(object)` in the help pane too.

Would be nice if doing `?object` and `help(object)` would always display the help in the help pane.

**Comment by ronblum** [comment]
This is working on MacOS Desktop. However, on RStudio Server 1.2.915 (Ubuntu 16.04.5), neither `?object` nor `help(object)` work, and state "The requested page was not found."

<img width="510" alt="reticulate_object" src="https://user-images.githubusercontent.com/31009952/44605897-16e9a780-a7b9-11e8-8ab2-46fedb05f2ca.png">

**Comment by kevinushey** [comment]
This seems to work for me in the latest daily builds of RStudio Server (tested with v1.2.955) so we should be good to go here.

**Comment by ronblum** [comment]
Confirmed in RStudio Server 1.2.957.
