### ISSUE TITLE
Startup crash on Windows 10

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rstudio#3115]
If you're here to report a bug in RStudio, please take the time to fill out as much of the below as you're able so that we can reproduce the problem you're seeing.  -->

### System details

    RStudio Edition : Desktop or Server
    RStudio Version : RStudio 1.2.792 
    OS Version      : Windows 10 64-bit
    R Version       : CRAN R 3.5.0, Microsoft R Open 3.5.0

### Describe the problem in detail
When I install the RStudio 1.2.792 preview, the program takes several second to load (normally it is nearly instantaneous). No UI elements load (all I see are the window title bar and a white screen). Then, before any UI elements load, the program crashes (quits and the process terminates). I am working on a Surface Book 2 laptop with a HiDPI screen. The last daily buildthat does not have this crashing problem is 1.2.736.

A diagnostics report is attached.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2167101/diagnostics-report.txt)

**Comment by gtritchie** [comment]
There are several possibilities. First, we've seen some issues with older drivers for certain graphics cards. Can you run Device Manager, open Display adapters, and right-click on the adapter and bring up properties, then let us know which graphics card you have, and the driver version? Also, you can click "Update Driver" and see if a new driver is available to see if that helps the problem. CAVEAT: installing new drivers is always slightly perilous on Windows, so don't do that unless you are comfortable with such things.

![2018-07-06_11-58-14](https://user-images.githubusercontent.com/10569626/42395792-00f2c68a-8114-11e8-8708-d3477ff26fab.png)

![2018-07-06_11-59-56](https://user-images.githubusercontent.com/10569626/42395839-225c9eea-8114-11e8-96e5-1a0570e6668c.png)

If this doesn't help or reveal anything, we'll try some other steps.

**Comment by bwiernik** [comment]
I have two display drivers on my machine:
- Intel(R) UHD Graphics 620 (version 22.20.16.4840) for the Surface Book 2 integrated graphics card
- NVIDIA GeForce GTX 1050 (version 23.21.13.8808) for the discrete GPU

If I used the NVIDIA graphics card, RStudio started fine. But if I used the Intel card with this driver, RStudio crashed as described. This is the current version of the driver for the Surface Book 2. I re-installed the same version of the driver from [here](https://www.microsoft.com/en-us/download/details.aspx?id=56261), the problem went away. Thanks for the tip, not sure what was going on here.

**Comment by gtritchie** [comment]
Huh, that's very weird, but glad it fixed the problem for you.

**Comment by nhirschey** [comment]
For somebody that may find this same issue, I ran into it today. It looks like if you follow instructions here for assigning Rstudio to the Nvidia gpu the issue goes away, as @bwiernik  mentioned.

https://recombu.com/mobile/article/how-to-force-microsoft-surface-book-use-nvidia-gpu-graphics-card
