### ISSUE TITLE
Packrat does not load when updating R to 3.5.04 from 3.4.4

### ISSUE THREAD

**Issue by UTexas80** [rstudio/rstudio#3116]
### System details
    RStudio Edition : 
    RStudio Version : Version 1.1.453
    OS Version      :  Windows 10
    R Version       :  R.3.5.0

### Steps to reproduce the problem
1. Updated R to Microsoft R Open 3.5.0 from 3.4.4
2. Opened RStudio Project
3. Opened Project Options-Packrat-> looks locked and loaded.
4. Entered packrat::snapshot() in the console
5. In the 'Files, Plots, Packages, Help, Viewer console - Packrat dropdown arrow is not functioning 

### Describe the problem in detail
Unable to port Packrat from R.3.4.4 to R.3.5.0. The error log is as follows:

Packrat is not installed in the local library -- attempting to bootstrap an installation...
> Installing packrat into project private library:
- "packrat/lib/x86_64-w64-mingw32/3.5.0"
'"C:\PROGRA~1\MIE74D~1\ROPEN~1\R-35~1.0/bin/x64/Rterm.exe"' is not recognized as an internal or external command,
operable program or batch file.
> packrat::restore(prompt = TRUE)... 
Error in hash(descFile) : 
  No DESCRIPTION file at path 'S:/ScholarshipsProject/R/ScholarshipProject/packrat/lib/x86_64-w64-mingw32/3.5.0/ProjectTemplate/DESCRIPTION'!
In addition: Warning messages:
1: In file(con, "r") :
  cannot open file 'packrat/lib/x86_64-w64-mingw32/3.5.0/packrat/DESCRIPTION': No such file or directory
2: In packrat::restore(prompt = TRUE) :
  The most recent snapshot was generated using R version 3.4.4
> packrat::snapshot(ignore.stale = TRUE,prompt = TRUE)
Error: Unable to retrieve package records for the following packages:
- "file462c5db36d66", "file472c195c3679", "file53c87f523428", "file692417d036eb", "file82904e29c99", "ProjectTemplate"
In addition: Warning message:
In fileDependencies.R(file) :
  Failed to parse S:/ScholarshipsProject/R/ScholarshipProject/tests/testCode.R ; dependencies in this file will not be discovered.

**Comment by kevinushey** [comment]
What version of Packrat are you using? I was able to successfully initialize a new Packrat project using MRO 3.5.0 with the latest CRAN version of Packrat (v0.4.9-2) so I'm curious what might be different in your case.

Can you confirm that `Rterm.exe` exists on your machine?

```r
path <- file.path(R.home("bin"), "Rterm.exe")
print(path)
file.exists(path)
```

E.g. I see:

```r
[1] "C:/PROGRA~1/MICROS~2/ROPEN~1/R-35~1.0/bin/x64"
> path <- file.path(R.home("bin"), "Rterm.exe")
> print(path)
[1] "C:/PROGRA~1/MICROS~2/ROPEN~1/R-35~1.0/bin/x64/Rterm.exe"
> file.exists(path)
[1] TRUE
```

**Comment by jmcphers** [comment]
Haven't heard back in well over a year so closing.
