### ISSUE TITLE
Attempting to cycle through plots in R Studio in the second run attempt causes plot rendering error

### ISSUE THREAD

**Issue by nav9** [rstudio/rstudio#3117]
### System details

    RStudio Edition : Desktop or Server 
    RStudio Version : 1.1.453
    OS Version      : Ubuntu 16.04, x86_64-pc-linux-gnu
    R Version       : 3.4.4

### Steps to reproduce the problem
1. Run the following code:
```
library(datasets)
library(tseries)
library(zoo)
library(expsmooth)
require(graphics)
if(!is.null(dev.list())) dev.off()
cat("\f")
d = datasets::AirPassengers
es <- exponential.smooth(d, .1)
plot(d, lty=c(3), col=c("red"))
plot(diff(es), lty=c(2), col=c("black"))
acf(diff(es))

```
2. Cycle through the plots using the arrow buttons at the top left corner of the plot window. No problem happens.
3. Run the program again and try cycling through the plots in the plot window and you'll see the error:
_

> Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
> In addition: Warning message:
> In readChar(con, 5L, useBytes = TRUE) :
>   cannot open compressed file '/tmp/RtmpAmvFU1/rs-graphics-c14a4a06-067f-42c2-b2f2-c552496016e9/.snapshot', probable reason 'No such file or directory'
> Graphics error: Plot rendering error

_

### Describe the problem in detail
The problem appears to happen due to this line of code `if(!is.null(dev.list())) dev.off()`,  which is listed on the internet as a method of automatically removing all plots. 

### Describe the behavior you expected
Clearing all the plots at the start of the program shouldn't have caused an error when cycling through the plots. If anything, R Studio should have automatically cleared the plots when the program is run or sourced or at least R should've provided a function which the user could have used to clear the plots and the console. Examples of such functions in Matlab are clf(), clear all; close all; clear;

**Comment by kevinushey** [comment]
Unfortunately, your example is not reproducible as none of the loaded packages provide a definition for the `exponential.smooth()` function. Is there some other R package that should be providing this, or am I misunderstanding something?

**Comment by nav9** [comment]
Sorry about that, and thanks for checking, but it's not `the exponential.smooth()` function that's important. I've mentioned in the bug report that the bug happens because of the `if(!is.null(dev.list())) dev.off()` code (from the solution given here: https://stackoverflow.com/a/44931159/453673). You could simply plot a few plots like in the code below. You'll be able to cycle through the plots using the arrow button. Then run the program again, and this time when you try to cycle through the plots, you'll see the error in the console. Remember to run the program more than once.

```
library(datasets)
library(tseries)
require(graphics)
if(!is.null(dev.list())) dev.off()
cat("\f")
d = datasets::AirPassengers
plot(d, lty=c(3), col=c("red"))
plot(d, lty=c(3), col=c("green"))
plot(d, lty=c(3), col=c("blue"))
plot(d, lty=c(3), col=c("yellow"))
```

**Comment by kevinushey** [comment]
Thanks! I figured that wasn't the important piece but it's helpful just to reduce the amount of friction in getting these examples reproducible so the development team can tackle the issue.

Here's an example that reproduces the issue for me directly -- try sourcing this script within RStudio:

```r
d <- AirPassengers
plot(d, lty = c(3), col = c("red"))
plot(d, lty = c(3), col = c("green"))
dev.off()
plot(d, lty = c(3), col = c("red"))
plot(d, lty = c(3), col = c("green"))
```

After running this code, pressing the back button in the Plots pane gives the following R error:

```
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'C:/Users/kevin/AppData/Local/Temp/RtmpU9caeC/rs-graphics-786fcb71-c121-4bed-8558-80975e07e89d/.snapshot', probable reason 'No such file or directory'
Graphics error: Plot rendering error
```

**Comment by kevinushey** [comment]
Note that the issue doesn't occur if you run the script line-by-line, one at a time, so there may be some kind of timing-related issue here.
