### ISSUE TITLE
R Studio does not select the project directory as current working directory on start

### ISSUE THREAD

**Issue by nav9** [rstudio/rstudio#3118]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Ubuntu 16.04. x86_64-pc-linux-gnu
    R Version       : 3.4.4

### Steps to reproduce the problem
1. Create an R Studio project with an R file/script in the project.
2. Try to open a CSV file (which should open without a problem) in the script
f = "monthly-water-usage-mlday-london.csv"
d<-read.csv(f, header=T, sep=",")
3. Save and close the project
4. Start R Studio again after restarting the computer or without restarting.
5. The script should already be open in R Studio
6. Run the script or source the script, and it shows an error:

> Error in file(file, "rt") : cannot open the connection
> In addition: Warning message:
> In file(file, "rt") :
>   cannot open file 'monthly-water-usage-mlday-london.csv': No such file or directory

### Describe the problem in detail
R Studio when started, automatically opens the project that was previously opened when the user had last closed the R Studio session. But a getwd() command shows that the current working directory is still the home directory. This happens inspite of setting the working directory in Tools > global options > General, as a specific directory. Although it does say that the directory would be considered only if not in a project, shouldn't the project directory be considered as the default directory when a project is opened?

### Describe the behavior you expected
Look at the number of people who are unsuccessfully trying to find awkward solutions to this simple problem: https://stackoverflow.com/questions/13672720/r-command-for-setting-working-directory-to-source-file-location-in-rstudio
Whether it is a simple script or a project that's open in R Studio, when a user clicks on a script's tab, R Studio should automatically switch the current working directory to the directory of that script. It'll save us so much of pain!
There are so many such questions on stackoverflow and crossvalidated.stackexchange, where users try to find solutions to problems that an IDE should have provided solutions for, right from the beginning. It would help if R developers view those problems posted.

**Comment by kfeinauer** [comment]
Some improvements have been made in this area in the 1.2 release which is currently in preview. Could you try the latest preview build and see if that works any better for this issue? You can find our preview builds at https://www.rstudio.com/products/rstudio/download/preview/.

**Comment by nav9** [comment]
Tried 1.2. It works. Thanks. But there's the other thing I mentioned too, about switching to the correct working directory when clicking on the tab of a source file. 
Eg: I have an R Studio project open with file "main.R" open in one tab. I also have another R script "s2.R" open in R Studio in another tab. This s2.R script is not in the same directory and is not part of any project. It's a standalone script which opens a CSV file that's located in the same directory as the script. 
Although the working directory of main.R is used correctly, when I click on s2.R's tab and try to run the program, it says it cannot find the CSV file. 

So I hope y'all could implement the automatic changing of working directory for whichever file is currently in focus in R Studio. It'd be a bit help. Thanks.

**Comment by kfeinauer** [comment]
It might be confusing to change the working directory when switching between script files, as that would change the console's working directory as well. 

For your particular use case, could you start the `s2.R` script with a call to save the current working directory via `getwd`, change it via `setwd`, then restore the original working directory and the end of the script? You could also consider fetching the actual directory of the executing script via the mechanism indicated here: https://stackoverflow.com/questions/1815606/rscript-determine-path-of-the-executing-script

**Comment by nav9** [comment]
Ok, you have the bigger picture of R Studio in mind, so there's nothing I can say to that.
From my smaller perspective I'd assume I'd be ok with the console's working directory changing, because I'm switching to another script and I want the directory to change. Of course, there might be bigger problems associated with it that you see which I can't yet see, so I'll close this. Thanks.
