### ISSUE TITLE
Request: Use Rstudio icons for R package?

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#3122]
@jmcphers Not sure if this is the correct place to ask but ... would it be ok to include the icons linked below in an R-package? The package is [shinyFiles](https://github.com/thomasp85/shinyFiles). The package generates a server-side file browser that can be used in a shiny app. With correct attribution, would this be acceptable?

https://github.com/rstudio/rstudio/tree/master/src/cpp/desktop/resources/freedesktop/icons

**Comment by jmcphers** [comment]
It depends on how you're using them! We have logo usage guidelines here:

https://www.rstudio.com/about/logos/
