### ISSUE TITLE
failed cmake make step

### ISSUE THREAD

**Issue by kemin711** [rstudio/rstudio#3126]
### System details

    RStudio Edition :  Server 
    RStudio Version :  latest from this repository
    OS Version      :   ubuntu
    R Version       :  3.5.1

### Steps to reproduce the problem
install-dependencies
make dir build
cd build
cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release
make

### Describe the problem in detail
Encountered java issue

### Describe the behavior you expected
make should complete

[ 34%] Building C object src/cpp/core/CMakeFiles/rstudio-core.dir/markdown/sundown/houdini_html_e.c.o
[ 34%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/r_util/RSessionLaunchProfile.cpp.o
    [javac] Compiling 2174 source files to /home/kzhou/Downloads/rstudio/src/gwt/bin
/home/kzhou/Downloads/rstudio/src/cpp/core/system/PosixParentProcessMonitor.cpp: In function ‘void rstudio::core::parent_process_monitor::{anonymous}::exitHandler()’:
/home/kzhou/Downloads/rstudio/src/cpp/core/system/PosixParentProcessMonitor.cpp:56:7: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
       (void)::write(s_writeOnExit.at(i), "done", 4);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kzhou/Downloads/rstudio/src/cpp/core/system/file_monitor/LinuxFileMonitor.cpp: In function ‘rstudio::core::system::file_monitor::Handle rstudio::core::system::file_monitor::detail::registerMonitor(const rstudio::core::FilePath&, bool, const rstudio_boost::function<bool(const rstudio::core::FileInfo&)>&, const rstudio::core::system::file_monitor::Callbacks&)’:
/home/kzhou/Downloads/rstudio/src/cpp/core/system/file_monitor/LinuxFileMonitor.cpp:450:9: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
    std::auto_ptr<FileEventContext> autoPtrContext(pContext);
         ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /opt/rstudio-tools/boost/boost_1_63_0/include/boost/function/function_base.hpp:16,
                 from /opt/rstudio-tools/boost/boost_1_63_0/include/boost/function/detail/prologue.hpp:17,
                 from /opt/rstudio-tools/boost/boost_1_63_0/include/boost/function.hpp:24,
                 from /home/kzhou/Downloads/rstudio/src/cpp/core/include/core/system/FileMonitor.hpp:23,
                 from /home/kzhou/Downloads/rstudio/src/cpp/core/system/file_monitor/LinuxFileMonitor.cpp:16:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/kzhou/Downloads/rstudio/src/cpp/core/system/file_monitor/LinuxFileMonitor.cpp: In function ‘void rstudio::core::system::file_monitor::detail::run(const rstudio_boost::function<void()>&)’:
/home/kzhou/Downloads/rstudio/src/cpp/core/system/file_monitor/LinuxFileMonitor.cpp:570:36: warning: logical ‘or’ of equal expressions [-Wlogical-op]
                if (errno == EAGAIN || errno == EWOULDBLOCK)
                                    ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java:116: warning: [deprecation] Double(double) in Double has been deprecated
    [javac]       Double lastModified = new Double(getLastModifiedNative());
    [javac]                             ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/history/model/HistoryEntry.java:37: warning: [deprecation] Double(double) in Double has been deprecated
    [javac]       return new Double(getIndexNative()).longValue();
    [javac]              ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/history/model/HistoryEntry.java:42: warning: [deprecation] Double(double) in Double has been deprecated
    [javac]       Double lastModified = new Double(getTimestampNative());
    [javac]                             ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java:3506: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       tabOrder_.remove(new Integer(idx));
    [javac]                        ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java:3561: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       tabOrder_.remove(new Integer(idx));  // force type box 
    [javac]                        ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java:196: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       setValue(new Integer(value).toString());
    [javac]                ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/StringUtil.java:81: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]       return formatFileSize(new Long(size).intValue());
    [javac]                             ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/resources/ImageResource2x.java:103: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]          sb.appendHtmlConstant(new Integer(getWidth()).toString());
    [javac]                                ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/resources/ImageResource2x.java:105: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]          sb.appendHtmlConstant(new Integer(getHeight()).toString());
    [javac]                                ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/resources/ImageResourceUrl.java:62: warning: [deprecation] getURL() in ImageResource has been deprecated
    [javac]    public String getURL()
    [javac]                  ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/resources/ImageResourceUrl.java:86: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       sb.appendHtmlConstant(new Integer(getWidth()).toString());
    [javac]                             ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/core/client/resources/ImageResourceUrl.java:88: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       sb.appendHtmlConstant(new Integer(getHeight()).toString());
    [javac]                             ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/model/QuotaStatus.java:71: warning: [deprecation] Double(double) in Double has been deprecated
    [javac]       return new Double(getValueNative(value)).longValue();
    [javac]              ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java:70: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                   new Integer(RmdOutput.RMD_VIEWER_TYPE_WINDOW).toString(),
    [javac]                   ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java:71: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                   new Integer(RmdOutput.RMD_VIEWER_TYPE_PANE).toString(),
    [javac]                   ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java:72: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                   new Integer(RmdOutput.RMD_VIEWER_TYPE_NONE).toString()
    [javac]                   ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/application/model/HttpLogEntry.java:64: warning: [deprecation] Double(double) in Double has been deprecated
    [javac]       Double timestamp = new Double(getTimestampNative());
    [javac]                          ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleErrorFrame.java:56: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       frameNumber.setText((new Integer(number)).toString() + ".");
    [javac]                            ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java:41: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       super(caption, new Integer(maxHeight));  
    [javac]                      ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/projects/model/ProjectTemplateIconImageResource.java:53: warning: [deprecation] getURL() in ImageResource has been deprecated
    [javac]    public String getURL()
    [javac]                  ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerAuth.java:192: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                                  new Integer(CREDENTIALS_UPDATE_UNSUPPORTED));
    [javac]                                  ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerAuth.java:205: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                                  new Integer(CREDENTIALS_UPDATE_SUCCESS)); 
    [javac]                                  ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerAuth.java:210: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                                  new Integer(CREDENTIALS_UPDATE_FAILURE)); 
    [javac]                                  ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java:298: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]       deferredObjectDisplayType_ = new Integer(type);
    [javac]                                    ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java:739: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]    private Integer deferredObjectDisplayType_ = new Integer(OBJECT_LIST_VIEW);
    [javac]                                                 ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/RObjectEntrySort.java:94: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]                               .compareTo(new Long(second.rObject.getLength()));
    [javac]                                          ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/RObjectEntrySort.java:93: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]             result = new Long(first.rObject.getLength())
    [javac]                      ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/RObjectEntrySort.java:98: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]                               .compareTo(new Long(second.rObject.getSize()));
    [javac]                                          ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/RObjectEntrySort.java:97: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]             result = new Long(first.rObject.getSize())
    [javac]                      ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.java:197: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                      return (new Integer(object.rObject.getLength())).toString();
    [javac]                              ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.java:312: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]                new Integer(columns_.get(i).getWidth()).toString() + "%");
    [javac]                ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java:236: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]                                              new Long(arg1.getLength()));
    [javac]                                              ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java:235: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]             return new Long(arg0.getLength()).compareTo(
    [javac]                    ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/history/History.java:241: warning: [deprecation] Long(long) in Long has been deprecated
    [javac]                   startIndex = new Long(historyPosition_).intValue();
    [javac]                                ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/plots/Plots.java:165: warning: [deprecation] Double(double) in Double has been deprecated
    [javac]                int x = new Double(event.getX()).intValue();
    [javac]                        ^
    [javac] /home/kzhou/Downloads/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/plots/Plots.java:166: warning: [deprecation] Double(double) in Double has been deprecated
    [javac]                int y = new Double(event.getY()).intValue();
    [javac]                        ^
    [javac] 36 warnings
     [copy] Copying 1479 files to /home/kzhou/Downloads/rstudio/src/gwt/bin

gwtc:
     [java] Compiling module org.rstudio.studio.RStudio
     [java]    [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')

BUILD FAILED
/home/kzhou/Downloads/rstudio/src/gwt/build.xml:110: Java returned: 1

Total time: 34 seconds
src/gwt/CMakeFiles/gwt_build.dir/build.make:57: recipe for target 'gwt_build' failed
make[2]: *** [gwt_build] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/gwt/CMakeFiles/gwt_build.dir/all' failed
make[1]: *** [src/gwt/CMakeFiles/gwt_build.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Linking CXX static library librstudio-core.a
[ 35%] Built target rstudio-core
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jmcphers** [comment]
We can't generally offer support for compiling RStudio (this issue tracker is for RStudio product bugs).

However I can tell you that the problem you're facing is probably caused by using a new version of Java (9+). RStudio uses GWT 2.8 which is only compatible with Java 8. You need to adjust your `PATH` and/or `update-alternatives`. 

See our Dockerfiles for an example of how to do this on Ubuntu, or use our docker-compile script to produce binaries without installing dependencies.

https://github.com/rstudio/rstudio/tree/master/docker
