### ISSUE TITLE
Reticulate not working on Windows 10 64 bit

### ISSUE THREAD

**Issue by hsm207** [rstudio/rstudio#3127]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Windows 10 64 bit
    R Version       : 3.5.0 (2018-04-23)

### Steps to reproduce the problem

1. Create an R notebook
2. Insert the following chunks:

```{r setup, include = FALSE}
library(reticulate)
use_python("C:\\Users\\user\\Anaconda3\\python.exe", required=T)
```

```{python}
print('hello world')
```

### Describe the problem in detail

Executing the second chunk gives the following error:

```
'python' is not recognized as an internal or external command,
operable program or batch file.

```
### Describe the behavior you expected

According to this [vignette](https://cran.r-project.org/web/packages/reticulate/vignettes/r_markdown.html),   I should expect the chunk to output 'hello world'.

Other information:

1. The output of sessionInfo() 

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.7

loaded via a namespace (and not attached):
[1] compiler_3.5.0  Matrix_1.2-14   tools_3.5.0     yaml_2.1.18     Rcpp_0.12.16    grid_3.5.0      knitr_1.20      jsonlite_1.5    lattice_0.20-35
```

2. A diagnostics report; 

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2172406/diagnostics-report.txt)

**Comment by jjallaire** [comment]
IDE support for reticulate requires the RStudio v1.2 preview release. See https://rstudio.github.io/reticulate/articles/rstudio_ide.html
