### ISSUE TITLE
don't use aliased library paths when forming library calls

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3130]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.800
    OS Version      : Windows 10 x64
    R Version       : 3.5.0

### Steps to reproduce the problem

```r
library("tidyverse", lib.loc="~/R/win-library/3.5")
file <- tempfile()
writeLines("a,b,c\n1,2,3\n", con = file)
read_csv(file)
```

### Describe the problem in detail

```
> read_csv(file)
Error in date_names_lang(date_names) : 
  cannot open file '~/R/win-library/3.5/readr/R/sysdata.rdb': No such file or directory
```

### Describe the behavior you expected

No error.

### Notes

Originally reported at https://github.com/tidyverse/tidyverse/issues/46.

Note that while this is really a problem in base R, it's only encountered in RStudio as we generate code of this form when one requests a package be loaded using the Packages pane (as we explicitly set the library path without expanding a tilde prefix)

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
