### ISSUE TITLE
Rstudio (development version) crashes when saving to clipboard

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#3136]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.792
    OS Version      : Ubuntu 18.04 LTS
    R Version       : 3.5.1

After successfully plotting a simple map of the world with `ggplot2`, RStudio instantly crashes when trying to copy the plot to clipboard. 

### Steps to reproduce the problem

    libs <- c("rgdal", "raster", "rgeos", "ggplot2")
    lapply(libs, library, character.only = TRUE)

    download.file("https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_land.zip", destfile = "/tmp/ne_10m_land.zip")
    unzip("/tmp/ne_10m_land.zip", exdir = "/tmp")

    area <- extent(c(0, 360, -50, 50))
    area <- as(area, "SpatialPolygons")
    crs(area) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

    msk <- readOGR("/tmp/","ne_10m_land")
    CP1 <- as(extent(xmin(area),180,ymin(area),ymax(area)), "SpatialPolygons")
    proj4string(CP1) <- CRS(proj4string(msk))
    CP2 <- as(extent(-180,xmax(area)-360,ymin(area),ymax(area)), "SpatialPolygons")
    proj4string(CP2) <- CRS(proj4string(msk))
    ne_10m_land1 <- gIntersection(msk, CP1, byid=TRUE)
    ne_10m_land2 <- gIntersection(msk, CP2, byid=TRUE)
    ne_10m_land2 <- shift(ne_10m_land2, x = 360)

    gpl <- 
      ggplot() +
      geom_polygon(data = ne_10m_land1,
        aes(x = long, y = lat, group = group),
        color = "transparent",
        fill = "black"
      ) +
      geom_polygon(data = ne_10m_land2,
        aes(x = long, y = lat, group = group),
        color = "transparent",
        fill = "black"
      ) +
      scale_x_continuous(name = "", breaks = pretty(xmin(area):xmax(area), 3), labels = parse(text=degreeLabelsEW(pretty(xmin(area):xmax(area), 3)))) +
      scale_y_continuous(name = "", breaks = pretty(ymin(area):ymax(area), 5), labels = parse(text=degreeLabelsNS(pretty(ymin(area):ymax(area), 5)))) +
      coord_cartesian(xlim = c(xmin(area), xmax(area)), ylim = c(ymin(area), ymax(area)), expand = FALSE)
    print(gpl)

### Describe the problem in detail
After plotting, trying to copy the plot to the clipboard, without changing the default width and height : `Export` --> `Copy to Clipboard` --> `Copy Plot`
There is no problem when saving the plot to an image file (any available format) or to a pdf file.

### Describe the behavior you expected
No crash is expected when trying to save to clipboard

### Session Info and Diagnostic Report
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_GB.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] ggplot2_3.0.0 rgeos_0.3-28  raster_2.6-7  rgdal_1.3-3   sp_1.3-1      sos_2.0-0     brew_1.0-6   
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.17     bindr_0.1.1      magrittr_1.5     tidyselect_0.2.4 munsell_0.5.0    colorspace_1.3-2 lattice_0.20-35  R6_2.2.2        
>  [9] rlang_0.2.1      plyr_1.8.4       dplyr_0.7.6      tools_3.5.1      grid_3.5.1       gtable_0.2.0     withr_2.1.2      lazyeval_0.2.1  
> [17] assertthat_0.2.0 tibble_1.4.2     bindrcpp_0.2.2   purrr_0.2.5      glue_1.2.0       compiler_3.5.1   pillar_1.2.3     scales_0.5.0    
> [25] pkgconfig_2.0.1 

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2180018/diagnostics-report.txt)

**Comment by ronblum** [comment]
Reproduced on Ubuntu 18.04 and Debian 9.4. Works fine on MacOS 10.12.6.

Here are the errors in the log on Debian 9.4 when running from the console:

````
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f07936a90a5 <unknown>
#1 0x7f07923ea141 <unknown>
#2 0x7f07936a943d <unknown>
#3 0x7f078ece40c0 <unknown>
#4 0x7f079bf363a0 QWebEnginePage::triggerAction()
#5 0x5645259f3260 <unknown>
#6 0x7f078f17b256 QMetaMethod::invoke()
#7 0x7f0791ac6fe3 QMetaObjectPublisher::invokeMethod()
#8 0x7f0791accb87 QMetaObjectPublisher::handleMessage()
#9 0x7f078f19a556 QMetaObject::activate()
#10 0x7f0791ad2544 QWebChannelAbstractTransport::messageReceived()
#11 0x7f079244c813 <unknown>
#12 0x7f079244cadc <unknown>
#13 0x7f0792ceb8ab <unknown>
#14 0x7f0792c00340 <unknown>
#15 0x7f0792c0e80e <unknown>
#16 0x7f0792bf4552 <unknown>
#17 0x7f079406c8e6 <unknown>
#18 0x7f079372c319 <unknown>
#19 0x7f07936c5648 <unknown>
#20 0x7f07936c6d6f <unknown>
#21 0x7f07936c72c0 <unknown>
#22 0x7f079240b445 <unknown>
#23 0x7f078f19b13b QObject::event()
#24 0x7f079000f63c QApplicationPrivate::notify_helper()
#25 0x7f0790016987 QApplication::notify()
#26 0x7f078f16f028 QCoreApplication::notifyInternal2()
#27 0x7f078f171abb QCoreApplicationPrivate::sendPostedEvents()
#28 0x7f078f1c3b63 <unknown>
#29 0x7f0788ff37f7 g_main_context_dispatch
#30 0x7f0788ff3a60 <unknown>
#31 0x7f0788ff3b0c g_main_context_iteration
#32 0x7f078f1c31af QEventDispatcherGlib::processEvents()
#33 0x7f0785621b81 <unknown>
#34 0x7f078f16d89a QEventLoop::exec()
#35 0x7f078f176424 QCoreApplication::exec()
#36 0x56452598547d <unknown>
#37 0x7f078d1c02e1 __libc_start_main
#38 0x56452598897a <unknown>
  r8: 000000000000012e  r9: 0000000000000000 r10: 00007f079c524250 r11: 0000000000000000
 r12: 0000000000000000 r13: 0000000000000005 r14: 0000564526c29dc8 r15: 0000000000000024
  di: 0000564526c073c0  si: 0000000000000011  bp: 0000564526f65f30  bx: 0000564526c073c0
  dx: ffffffffffff2550  ax: 00007f079bf363a0  cx: 00005645259b44c0  sp: 00007ffeb2d8af90
  ip: 00007f079bf363a0 efl: 0000000000010207 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
````

**Comment by jmcphers** [comment]
We're currently tracking this in https://github.com/rstudio/rstudio/issues/2831.
