### ISSUE TITLE
consider backing out dependency on libclang-dev

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3139]
Too many users having issues during install: https://community.rstudio.com/t/preview-1-2-747-doesnt-install-in-ubuntu-16-04/10005/7

**Comment by jjallaire** [comment]
Would we go back to bundling a libclang for Ubuntu as we used to do? (we could bundle an older one that works on >= 16.04)

**Comment by kevinushey** [comment]
I think so. Would we not want to support Ubuntu 14.04 as well?

**Comment by jjallaire** [comment]
I thought we were ditching 14.04 for this release? (since it will be at the end of it's lifetime in April 2019)

**Comment by jmcphers** [comment]
Our official platform deprecation policy is that we support platforms that haven't EOL'ed yet (and hopefully we'll release 1.2 before April '19): https://www.rstudio.com/about/platform-deprecation-strategy/. 

It'd certainly be nice to only support 16+ as Qt 5.11 doesn't support 14 either (so we use 5.10 there), but I think that especially with the Linux release of Desktop Pro for enterprise customers we'll be glad for the support of the "almost dead" release. 

Because of the Qt 5.11/5.10 split, we're going to have separate releases for Ubuntu 14 and Ubuntu 16 (in fact we already do now that @gtritchie's change has landed). Does this enable us sidestep the problem by being more specific about the version of libclang?

**Comment by jjallaire** [comment]
Okay, that makes. In some cases though it's extremely difficult for us to support some desktop OS's  (especially as we are vulnerable to Qt). I might suggest amending our desktop policy to carve out when the latest release of Qt stops supporting a platform we do as well.

**Comment by jmcphers** [comment]
Taking out of 1.2 unless we hear of more reports that this is a painful dependency -- so far we've only had 2 people mention a problem despite 1.2 usage eclipsing 1.1, and reverting to bundling creates a whole different set of problems (which is what motivated the system-level dependency work).

**Comment by jdblischak** [comment]
Quick update. There have been two new issues opened on RStudio Community related to libclang-dev installation problems:

* 2019-06-27: [Can't install Rstudio on Debian 9](https://community.rstudio.com/t/cant-install-rstudio-on-debian-9/34114)
* 2019-06-24: [Installation of RStudio impossible in Ubuntu 19.04 - Dependency issue](https://community.rstudio.com/t/installation-of-rstudio-impossible-in-ubuntu-19-04-dependency-issue/33812)

I confirmed I could install libclang-dev (and RStudio 1.2) in a Ubuntu 19.04 Docker container, so I'm having difficulty troubleshooting the issue.

**Comment by kevinushey** [comment]
Sounds like this is indeed still causing some trouble. It feels like there are a few options:

1. Continue with things as-is, but try to document some ways of users to get un-stuck if `libclang-dev` cannot be installed for some reason;

2. Start bundling libclang directly again,

3. Don't depend on `libclang-dev`, but prompt the user (one-time notice) when a C++ file is opened if `libclang` cannot be found, and give installation instructions.

@jmcphers, what do you think?

**Comment by kevinushey** [comment]
I think part of the problem is that most of the instructions online for installing `.deb` packages 'by hand' can get the user into a bad state; e.g.

https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt

seems to promote using `dpkg -i` to install a package, and invoking `dpkg` directly will _not_ install other required apt dependencies.

```
sudo gdebi -i package.deb
```

Alternatively, you can install directly using apt, e.g.

```
sudo apt install ./package.deb
```

Given this, I think we're okay to continue bundling `libclang-dev` and we just need to ensure users are installing the RStudio debian package properly.

**Comment by TomTheGeek** [comment]
I would just like to say thank you for making my life as an IT Admin Extra Difficult. I'm not the only one with this issue either. Guess free-version users can go screw themselves right? 

First of all gdebi doesn't support the -i flag anymore. 

> I believe we usually recommend using gdebi; 

Second of all why isn't this information on the downloads page?  I wouldn't have know without the Google search, so thanks for that. 

Debian 9 is no longer receiving security updates, but you won't support Debian 10. In 10 we get "Error while loading shared libraries: libssl.so.1.0.0". Doesn't matter if it's compiled from source same error. 

Any response or or you going to make excuses why your package isn't in official Deb repositories some more?

**Comment by jmcphers** [comment]
Sorry you're having trouble! You can find official builds of RStudio Server for Debian 10 here:

https://rstudio.com/products/rstudio/download-server/debian-ubuntu/

Or RStudio Desktop here:

https://rstudio.com/products/rstudio/download/

We know many people prefer to install products using official repositories, and have a pilot project running to add one.

**Comment by TomTheGeek** [comment]
> 
> 
> Sorry you're having trouble! You can find official builds of RStudio Server for Debian 10 here:
> 
> https://rstudio.com/products/rstudio/download-server/debian-ubuntu/
> 
> Or RStudio Desktop here:
> 
> https://rstudio.com/products/rstudio/download/
> 
> We know many people prefer to install products using official repositories, and have a pilot project running to add one.

Hopefully the server version will work for my users. The Desktop version files you linked DO NOT WORK on Debian 10.8.

**Comment by ronblum** [comment]
Hi @TomTheGeek! I just tried out the installer on Debian 10.6 and Debian 10.8, but I could not reproduce the problem—the installation was successful. A couple of things that might help:
* The direct link to the latest release, RStudio Desktop 1.4.1103 for Debian 10, is located at https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.4.1103-amd64.deb
(Note the "bionic" in the path—Debian 9 and Debian 10 have different installers.)
* `apt install` requires the relative path or fully qualified path (unlike `gdebi`). So in this case, the installation would be something like
`apt install ./rstudio-1.4.1103-amd64.deb`
or
`apt install /path/to/directory/rstudio-1.4.1103-amd64.deb`

Hopefully this works—please let us know if the installation is successful or if there are still issues with it. Thanks!

**Comment by TomTheGeek** [comment]
It installs just fine, but it won't run. Throws the libssl.so error.

**Comment by nachti** [comment]
Using Debian 10.8:
```
gdebi rstudio-server-1.4.1106-amd64.deb 
  Reading package lists... Done
  Building dependency tree        
  Reading state information... Done
  Reading state information... Done
  Dieses Paket kann nicht installiert werden
  Cannot install 'libclang-dev'
```

Trying to install `libclang-dev` says `libclang-7-dev` depends on `libobjc-6-dev` which is not installable.

**Comment by TomTheGeek** [comment]
> Trying to install `libclang-dev` says `libclang-7-dev` depends on `libobjc-6-dev` which is not installable.
> Would be really fine to put rstudio to the official debian/ubuntu/... repositories, otherwise updating is quite painful.

I was able to get around this issue using gdebi -

> sudo gdebi -i packagename.deb

But it is useless, the program still won't launch. Gives a "Error while loading shared libraries: libssl.so.1.0.0" message and nothing. 

As you can see the devs don't really care. Apparently it's good enough if it installs. Who runs software anyway?

**Comment by kevinushey** [comment]
Are you sure you downloaded the correct version of RStudio for your system?

### Debian 10 / Ubuntu 18.04 / Ubuntu 20.04
https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.4.1106-amd64.deb

### Debian 9 / Ubuntu 16.04
https://download1.rstudio.org/desktop/debian9/x86_64/rstudio-1.4.1106-amd64.deb

**Comment by kevinushey** [comment]
And you can confirm the version of OpenSSL that RStudio links to with e.g.

```
$ ldd /usr/lib/rstudio/bin/rsession  | grep ssl
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f60e3bb8000)
```

**Comment by TomTheGeek** [comment]
I tried all the versions. I don't have the system available anymore to test. But it was a brand new Debian 10.8 install.
