### ISSUE TITLE
Cannot switch to 32 bit R using Preview Release and Daily

### ISSUE THREAD

**Issue by imanuelcostigan** [rstudio/rstudio#3150]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.792 (Preview) / 1.2.822 (Daily)
    OS Version      :  Windows 7 x64
    R Version       :  3.5.1

### Steps to reproduce the problem

1. Tools > Global Options 
2, Click "Change" button in "R version"
3. 32 bit versions of R are not shown (but are installed)
4. Selecting "Choose a specific version of R" > Browse (to R_HOME/bin/i386) and selecting OK does NOT add this to the list of options

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/2107580/42670524-c2574550-869e-11e8-8723-208f24d40c7a.png)

### Describe the behavior you expected

Be able to switch to 32 bit R. I can do this with the latest stable release of RStudio (v1.1)

**Comment by gtritchie** [comment]
RStudio 1.2 has dropped support for 32-bit Windows, and 32-bit R on 64-bit Windows.  See #2993 for details.

Any feedback on this is greatly appreciated; does the loss of 32-bit R cause a problem for you that can't be addressed using 64-bit R?

**Comment by imanuelcostigan** [comment]
Yes absolutely - big problem! We are still using 32 bit versions of the Microsoft Office suite on 64 bit Windows and cannot read data from 32 bit Access DBs using 64 bit R

At some point in the next 12 months we will migrate to newer (probably 64 bit versions) of Office apps, but there is still a bit of work between now and then!

**Comment by jmcphers** [comment]
We apologize for the inconvenience. Unfortunately, our hand was more or less forced due to 32-bit support being dropped by a framework we depend on heavily. 

If you want to work with your 32 bit Office apps, we'd suggest using the stable release of RStudio, 1.1, which we've continued to patch so that it's compatible with the newest versions of R.

**Comment by imanuelcostigan** [comment]
is it possible to run both 1.1 and 1.2 in parallel?

**Comment by jmcphers** [comment]
Only one can be the primary version on your system (that is, the one with file associations, etc.) but you can indeed run both at once if you want by using an installer-less version of RStudio. You can get a zipfile with a self-contained installation under "Zip/Tarballs" on the download page.

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by imanuelcostigan** [comment]
FYI - the feedback I received form our corporate tech team is that 32 bit Office is here to stay and that MSFT still recommend 32-bit for general use.

**Comment by woodwards** [comment]
It also means Fortran DLLs will no longer run via `.Fortran` since this only works with 32-bit R. I'm not sure if there is a workaround.

**Comment by gtritchie** [comment]
Reopening to serve as the place for additional comments/votes.

**Comment by gtritchie** [comment]
Microsoft has switched to recommending 64-bit Office by default, but only on the latest versions, which I think is their Office-365 subscription model. I recognize that many users don't have the choice or desire to upgrade or switch.

https://support.office.com/en-gb/article/choose-between-the-64-bit-or-32-bit-version-of-office-2dee7807-8f95-4d0c-b5fe-6c6f49b8d261

**Comment by imanuelcostigan** [comment]
Until such time as MSFT deprecates support for 32 bit versions of Office, I don’t think you can expect wide spread adoption of this in organisations with widely established user developed Office based applications which may or may not support 32 bit. The migration strategy for this is horrendous. Lucky for me, the key application that is based on a 32 bit version of Access is being migrated to an IT managed platform so this is going to become less of an issue for me in a 6-12 months time

**Comment by gtritchie** [comment]
Fixed by https://github.com/rstudio/rstudio/commit/e2c3f845cfd254f4cf971f01291f1cd0e7fee34c

**Comment by gtritchie** [comment]
Fixed in upcoming 1.2 patch release and in 1.3.

**Comment by imanuelcostigan** [comment]
@gtritchie - when is the 1.2 patch release likely to land?

**Comment by gtritchie** [comment]
I can't speak to when the official release of 1.2 patch will take place, but a preview release should be out very soon.

If you are eager to try it, here a "preview of a preview release" with the 32-bit support: https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.2.1522.exe

**Comment by imanuelcostigan** [comment]
Sorry, i downloaded the wrong file :(
