### ISSUE TITLE
Revisit FirePro workaround

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3151]
https://github.com/rstudio/rstudio/issues/3148
https://github.com/rstudio/rstudio/commit/ce252d4c48db72826285421d09e2c8179981698c

We currently disable the GPU entirely for Mac Pro machines to workaround an issue where RStudio fails to initialize. However, this leads to severely degraded performance in the IDE. We should try and find a more targeted fix or workaround if possible.

**Comment by hrbrmstr** [comment]
(this is tangential)

Even on a 2016 MacBook Pro, the following sandbox error occurs:

```
2018-07-14 21:04:35.562 QtWebEngineProcess[68618:658686] unable to obtain configuration from file:///Library/Preferences/com.apple.ViewBridge.plist due to Error Domain=NSCocoaErrorDomain Code=257 "The file “com.apple.ViewBridge.plist” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Library/Preferences/com.apple.ViewBridge.plist, NSUnderlyingError=0x7f8b50d2aac0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```

While I don't _think_ it causes any real harm it might be a good idea to add a sandbox profile to the macOS targeted Desktop builds.

**Comment by gtritchie** [comment]
I broke out the sandbox error / sandbox profile topic to a new issue: #3161

**Comment by hrbrmstr** [comment]
Just a quick note after trying 1.2.850 Build 852 (71c00b4d) that it in no way feels "sluggish" :-)

Typing is responsive; system dialogs like file ops don't feel like there's a delay at all and i'm using custom fonts, have lots of files open, etc.

👍 for a very welcome workaround!

**Comment by hrbrmstr** [comment]
Hey folks.

Yep, it's me again. 

Mojave updated again today and the build looks final (there is no beta # associated with it).

Grabbed 1.2.983 and the "empty window" is back with the following message if I start it by hand in a shell:

    les2_command_buffer_stub.cc(263)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.

I was previously on 959 (I've had a major project going and couldn't risk updating from a stable experience) and it starts up fine.

968 is the most recent version that still runs fine.

Latest Mojave is also on my 2016 13" MBPro and the latest RStudio daily works fine there.

**Comment by kevinushey** [comment]
Can you remind us what graphics card you have on your MBP?

**Comment by hrbrmstr** [comment]
Dual these:

```
AMD FirePro D700:

  Chipset Model:	AMD FirePro D700
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-1
  PCIe Lane Width:	x16
  VRAM (Dynamic, Max):	6144 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x6798
  Revision ID:	0x0000
  ROM Revision:	113-C3861J-687
  VBIOS Version:	113-C3861XA-028
  EFI Driver Version:	01.0D.687
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.11 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily2 v1
```

**Comment by hrbrmstr** [comment]
@kevinushey I don't suppose qt 5.11.2 fixes this? vis-a-vis https://bugreports.qt.io/browse/QTBUG-69491?focusedCommentId=412301&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-412301 ?

**Comment by kevinushey** [comment]
It might help with the warning, but we'd really like to avoid taking yet another Qt update so close to release (especially since the past few Qt releases have had loads of regressions we've had to discover and work around)

**Comment by kevinushey** [comment]
Looks like this will be fixed in the next Qt releases and so we can remove our FirePro workarounds 🎉 

https://bugreports.qt.io/browse/QTBUG-70062

**Comment by hrbrmstr** [comment]
😻 THIS IS AWESOME (not that RStudio performs badly on the Pros in current state — I have no issues and I use it ~9-12hrs a day)

**Comment by kevinushey** [comment]
This is now indeed handled in the v1.2 builds.
