### ISSUE TITLE
Review Changes panel not themed correctly with dark themes

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3153]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.821
    OS Version      : Windows 10 x64, macOS 10.13.5
    R Version       : 3.5.1

### Steps to reproduce the problem

Activate a dark theme, and then open the Review Changes panel (e.g. click <kbd>Diff</kbd> in the <kbd>Git</kbd> pane).

### Describe the problem in detail

Portions of the window are not properly dark themed.

### Describe the behavior you expected

Theming should be consistent.

![screen shot 2018-07-13 at 1 28 09 pm](https://user-images.githubusercontent.com/1976582/42712516-da381a8a-86a0-11e8-9ed4-f33744ea2411.png)

Note that in RStudio v1.1 theming is not applied at all to this panel, so perhaps the simplest change is just making sure we don't attempt to dark-theme the review changes panel.

**Comment by ronblum** [comment]
Verified with RStudio Server 1.2.915 (Ubuntu 16.0.5) and Desktop 1.2.921 (MacOS 10.14 Mojave) that the Review Changes panel is now safe from Dracula and Twilight.
