### ISSUE TITLE
Update built-in SumatraPDF to 3.1.2

### ISSUE THREAD

**Issue by ksint** [rstudio/rstudio#3155]
On Windows 10, purple icons appear in the built-in SumatraPDF on Rstudio 1.1.453. The built-in SumatraPDF is 3.1.1. According to <https://www.sumatrapdfreader.org/news.html>, "3.1.2 (2016-08-14) ... fixed issue with icons being purple in latest Windows 10 update."

![chrome_2018-07-14_12-03-55](https://user-images.githubusercontent.com/5727992/42726760-4ee2f5bc-875f-11e8-949c-0375ae0cd9f8.png)

**Comment by ronblum** [comment]
@ksint Thanks for informing us!

**Comment by ksint** [comment]
I replaced the SumatraPDF.exe in the bin folder with the 3.1.2 SumatraPDF.exe from https://www.sumatrapdfreader.org/dl/SumatraPDF-3.1.2.zip. So far, it's working well.

![image](https://user-images.githubusercontent.com/5727992/42844015-6105312c-89d7-11e8-9c74-6001deb15bfb.png)

**Comment by ksint** [comment]
Hi @ronblum, any update on this? The most recent stable and preview versions of Rstudio are still packaged with SumatraPDF 3.1.1. Thanks!
