### ISSUE TITLE
Microsoft Visual C++ Runtime Error

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3156]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Windows-10 (1703 15063.1155)
    R Version       : 3.3.3

### Steps to reproduce the problem
Opening based on [community post](https://community.rstudio.com/t/microsoft-visual-c-runtime-error/9682/3). Trying to run RStudio on Windows-10 is leading to the following:

![rstudiovc](https://user-images.githubusercontent.com/10569626/42743929-3ee86f74-887d-11e8-8b18-6a96127585e6.PNG)

### Describe the problem in detail
Originally reported on RStudio 1.0.153. Also reported after upgrade to 1.1.442.

### Describe the behavior you expected
RStudio runs as usual.

This seems to have started after some recent Windows-10 update.

**Comment by gtritchie** [comment]
Note, it is curious that RStudio is reported under `C:\Program Files (x86)\RStudio\bin\rstudio.exe`; pretty sure (but need to confirm) we normally install RStudio under `Program Files`, not `Program Files (x86)`.

**Comment by gtritchie** [comment]
So far I cannot reproduce this issue. I can install RStudio 1.0.153, 1.1.453, and 1.2.826 onto my clean Windows-10 machine (64-bit Pro 1803, build 17134.165) and run them successfully.

**Comment by gtritchie** [comment]
Also see #2734 for something with very similar symptoms.

**Comment by gtritchie** [comment]
Customer also mentioned they are using nlmixr, and that on at least one machine they were able to fix the problem by making some adjustments to it (did ascertain what was actually done).

**Comment by gtritchie** [comment]
Reports of this issue seem to have stopped. Though unclear if through anything we did or additional tweaks in subsequent Windows updates. Closing; can be reactivated if someone can supply a current repro.

**Comment by jaganadhg** [comment]
Hi
I am getting the same issue. But it was coming from a library import error and error in the code.
