### ISSUE TITLE
Packrat project stops using its installed packages directory if disabled then reenabled

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3158]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.453 and 1.2.816-1
    OS Version      : MacOS 10.12.6 (Sierra) and Ubuntu 16.04.4
    R Version       : 3.4.4

### Steps to reproduce the problem

Part I
1. Create a new project
2. Tools -> Project Options -> Packrat 
3. Check "Use packrat with this project"
4. Select Packages pane
5. In console, install a project that's not currently installed, say, "rwars": `install.packages("rwars")`
    - "rwars" and a number of other packages should now appear in the Packages pane under "Packrat Library", followed by "System Library"
6. `packrat::lib_dir()`
    - Should show the R packages location under the project's `packrat` subdirectory
7. `.libPaths()`
    - Should include the packrat subdirectory in the previous step
8. Close the project

<hr/>

Part II
9. Reopen the project
10. Select the Packages pane
   - The "rwars" package, etc., should be under "Packrat Library", followed by "System Library"
11. `packrat::lib_dir()`
   - Same as above: packages location under project's `packrat` subdirectory
12. `.libPaths()`
   - Same as above: includes the packrat subdirectory in the previous step

<hr/>

Part III
13. Tools -> Project Options -> Packrat 
14. Uncheck "Use packrat with this project"
15. Select the Packages pane
   - The "rwars" package, etc., and the "Packrat Library" section are gone
   - "System Library" remains, and may be preceded by "User Packages"
16. `packrat::lib_dir()`
   - Same as above: packages location under project's `packrat` subdirectory
17. `.libPaths()`
   - Now this should reflect the R library paths that are normally used by new sessions and non-packrat packages

<hr/>

Part IV
18. Tools -> Project Options -> Packrat 
   - "Use packrat with this project" is checked again
19. Uncheck, then recheck, "Use packrat with this project"
20. `.libPaths()`
   - This still reflects the "normal" R library paths, not the packrat path
21. Select the Packages pane
   - The "rwars" package, etc., and the "Packrat Library" section are missing
   - "System Library" is still there, and may be preceded by "User Packages"
22. Close the project
23. Reopen the project
24. `.libPaths()`
   - This still reflects the "normal" R library paths, not the packrat path
25. Select the Packages pane
   - The "rwars" package, etc., and the "Packrat Library" section are still missing
   - "System Library" is still there, and may be preceded by "User Packages"
26. `packrat::lib_dir()`
   - Same as above: the project still recognizes that the packages' location should be under project's `packrat` subdirectory
27. Tools -> Project Options -> Packrat 
   - Just confirming that "Use packrat with this project" is checked

<hr/>

Part V
28. In console: `packrat::on()`
29. Select Packages pane
   - "rwars", etc.,  have returned under "Packrat Library", followed by "System Library", and "User Library" is gone
30. `packrat::lib_dir()`
   - Should continue to show the R packages location under project's `packrat` subdirectory
31. `.libPaths()`
   - Now includes the packrat subdirectory in the previous step again

<hr/>

Part VI
32. Close the project
33. Reopen the project
34. Select the Packages pane
   - The "rwars" package, etc., and the "Packrat Library" section are gone
   - "System Library" remains, and may be preceded by "User Packages"
35. `packrat::lib_dir()`
   - Same as above: packages location under project's `packrat` subdirectory
36. `.libPaths()`
   - Now this should again reflect the R library paths that are normally used by new sessions and non-packrat packages

### Describe the problem in detail

For a packrat directory, if the packrat project option is ever unchecked:
1. Returning to the project options, it is always checked, no matter how many times it gets unchecked.
2. The installed packages' library paths returned by `libPaths()` are not the packrat paths.

### Describe the behavior you expected

1) Unchecking the packrat option should persist.
2) Re-enabling packrat should return to using the packrat packages' paths.

Workaround: `packrat::on()`, but this has to be called every time the package is reopened.

[Initially reported in Support issue 28678.]

**Comment by kevinushey** [comment]
This will be fixed with both of:

https://github.com/rstudio/rstudio/commit/93831f11b39079faa14846b96548f0f48992b4ca
https://github.com/rstudio/packrat/pull/483

There were two bugs here:

1. RStudio was mis-detecting whether a project truly had Packrat enabled; it was missing the case where a Packrat lockfile did exist but it was not 'active' (the project .Rprofile either did not exist or did not attempt to initialize Packrat on startup). This is why the checkbox in the Packrat project options always appeared checked.

2. Packrat itself always attempted to re-snapshot and restore on `packrat::init()`, but this is not appropriate for projects that already have a lockfile. Rather, we should just re-write the Packrat autoloader into the `.Rprofile`.

**Comment by jmcphers** [comment]
Closing since both fixes are in (let me know if there's a reason this should still be open!)

**Comment by ronblum** [comment]
This is still an issue—reproduced with Desktop 1.2.872 and Server 1.2.872-1.

**Comment by kevinushey** [comment]
@ronblum did you have the development version of Packrat installed?

**Comment by ronblum** [comment]
@kevinushey Ah, it works with the development version, 0.4.9-10 from GitHub, thanks! It's only failing only with the current production version, 0.4.9-3.

I'll return this to closed, but I'll wait for verification when the working version is pushed to production.

**Comment by ronblum** [comment]
Confirmed fixed with packrat version 0.5.0.
