### ISSUE TITLE
malformed paged table output with R 3.5.1 on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3163]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.453; v1.2.821
    OS Version      : Windows 10 x64
    R Version       : 3.5.1

### Steps to reproduce the problem

Execute the following chunk in an R Notebook with inline output:

`````
```{r}
head(iris)
```
`````

### Describe the problem in detail

Text is malformed, e.g.

![screen shot 2018-07-16 at 10 49 57 am](https://user-images.githubusercontent.com/1976582/42774246-17073ca6-88e6-11e8-9352-4881a15f2093.png)
ed, e.g.

### Describe the behavior you expected

Normal output.

**Comment by kevinushey** [comment]
Note that this doesn't seem to reproduce consistently for me -- sometimes it happens, sometimes it doesn't.

**Comment by kevinushey** [comment]
The issue reproduces more reliably with:

`````
```{r}
list()
head(iris)
```
`````

**Comment by kevinushey** [comment]
Agh! Whatever is going on actually leaks out to other bits of rendered text. See for example in the signature tooltip:

![screen shot 2018-07-16 at 11 57 59 am](https://user-images.githubusercontent.com/1976582/42777699-b5741702-88ef-11e8-8257-a4c66103ca63.png)

And yet the issue seems to go away after we execute some separate R code. It seems like our Notebook execution code is tripping ... something, somewhere, that is injecting these BOMs.

**Comment by kevinushey** [comment]
This particular incantation of the issue should be worked around with https://github.com/rstudio/rstudio/commit/9e545543166b4d6139dd6ed4e3cc185db9415c47.

**Comment by ronblum** [comment]
This issue still appears on Windows 10 with the following:
````
```{r}
list(head(iris))
```
````

**Comment by kevinushey** [comment]
This appears to be a bug in R: I've filed an issue here. https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17567

```
> object <- "hello"
   > class(object) <- "foo"
   > print.foo <- function(x, ...) {
   +    print(encodeString(x))
   + }
   > list(object)
   [[1]]
   [1] "\002ÿþhello\003ÿþ"
```
