### ISSUE TITLE
BUG: calling invokeRestartInteractively causes to RStudio to abort session (encounter fatal error)

### ISSUE THREAD

**Issue by drtjc** [rstudio/rstudio#3165]
CODE THAT CAUSES RSTUDIO TO ENCOUNTER FATAL ERROR
```
f <- function() {
  withRestarts(
    stop("error"),
    rst = function(x) print(x^2)
  )
}


withCallingHandlers(
  condition = function(c) invokeRestartInteractively("rst"),
  f()
)
```
When run, the console requests the value of `x`. When a value, say `5`, is entered, RStudio encounters a fatal error and aborts.

EXPECTED BEHAVIOUR
When `5` is entered, `25` is printed to the screen. This works in R itself.

RSTUDIO
Version 1.1.453 
Desktop

SESSION INFO
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.1.19

**Comment by kevinushey** [comment]
This all comes down to RStudio not handling interactive parse attempts correctly on Windows, e.g.

```R
parse(prompt = "Enter an R Expression: ")
```

This crashes with RStudio v1.1, and always returns `NULL` with RStudio v1.2.

**Comment by ronblum** [comment]
[Just leaving a note for verification]

- Interactive: Entering `1` as the response to prompt fails
- Not interactive: `parse(text = "1")` succeeds

**Comment by kevinushey** [comment]
Also worth noting that other interactive methods for reading user input (e.g. `readline("Enter a number: ")`) work fine so it's unique to this single case.

**Comment by jmcphers** [comment]
This no longer crashes in recent versions of RStudio (instead an error is generated):

```
 Error in parse(prompt = prompt) : 
  invalid multibyte character in parser at line 1 
```

I don't think this scenario is in scope (especially considering that we've had no reports of this in well over a year and a half).
