### ISSUE TITLE
Can't re-deploy content from directories with very short names

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3168]
### System details

    RStudio Edition : Both
    RStudio Version : 1.1.453

### Steps to reproduce the problem

1. Create a Shiny application in a folder called `R`
2. Publish it to shinyapps.io
3. Restart RStudio
4. Attempt to re-publish it

### Describe the problem in detail

You can't re-publish; the Publish button is disabled. This happens because the default application name (which is derived from the folder) is too short, and we're incorrectly checking it even though the content has previously been deployed.

**Comment by ronblum** [comment]
Verified in 1.1.456.
