### ISSUE TITLE
Problems with saving plots on a Windows PC with 4k monitor - wrong picture size

### ISSUE THREAD

**Issue by victorn1** [rstudio/rstudio#3173]
RStudio Edition : Desktop
    RStudio Version : 1.1.453  
    OS Version      : Windows 7 x64
    R Version       : 3.5.0     32 bit

Steps to reproduce the problem:

```
win.metafile("myplot.wmf" ,height=3,width=5)
plot(1:9)
dev.off()
```

Details: 
When I try to save plots as WMF or EMF pictures specifying small picture size, e.g.., 3x5 inches, I get a wrong size of the WMF/EMF picture. The plot itself resides in the left upper corner of the picture.
Running the same code from RGui produces a correct result.

I use a 4k monitor, there were no problems with 1920x1080 monitors.

**Comment by kevinushey** [comment]
I believe this issue is fixed in the v1.2 branch. If you have time, can you try testing with the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by kevinushey** [comment]
Looks like you're right; the issue still exists there.

However, I note that this issue seems to be independent of RStudio -- I see the same problem when running R with e.g. RGui on Windows, or even with R from the Windows command shell.

Since this appears to be an issue with `win.metafile()` itself, I'm not sure if this can be fixed on the RStudio side.

**Comment by victorn1** [comment]
@kevinushey  I have no such issues on RGui. I use RGui to make correct pictures. 

May be the issue is somehow connected with your configuration of R? May be you load additional packages that corrupt pictures output?

**Comment by victorn1** [comment]
@kevinushey It seems that there are some required packages pointed out in your default .RData file, which is automatically loaded. The packages break the WMF pictures output. Please try exiting all R consoles, deleting ~/.RData file (in Windows it may be located in "Documents" or "Documents/R" folder in the user home folder), and then starting RGui.

**Comment by victorn1** [comment]
@kevinushey At last I fished out the bug.
One must turn off "display scaling for higher DPI settings" for RGui to make it work correctly:

"Right-click the R shortcut on your desktop, then select Properties from the menu.
 Once the Properties window is up, go to the Compatibility tab.
 You will see a 'Disable display scaling on high DPI' option.
"

**Comment by victorn1** [comment]
@kevinushey This definitely a bug in R. I am not able to register at https://bugs.r-project.org/
Could you submit them this bug?

**Comment by victorn1** [comment]
I think there is also a connected bug in Rstudio. The plots are blured in Rstutio on a 4k monitor. That means that some wrong scaling is used for the plot window, just as for default scaling in RGui.

**Comment by lxhao1** [comment]
I running into same assue, and I have turned off "display scaling for higher DPI settings" for RGui and RStudio. I can get nomal picture in 'win.metafile'. But click “export”  then 'Copy to clipboard', then on the popup, the ‘height’ only reach to 571，So, I'm sure that some wrong scaling is used for the plot window,

**Comment by lxhao1** [comment]
@kevinushey   I running into same assue, and I have turned off "display scaling for higher DPI settings" for RGui and RStudio. I can get nomal picture in 'win.metafile'. But click “export” then 'Copy to clipboard', then on the popup, the ‘height’ only reach to 571，So, I'm sure that some wrong scaling is used for the plot window,

**Comment by Boson518** [comment]
- i fixed this problem by directly setting the Rstudio. Right click and set like this
![Screenshot 2022-01-08 174351](https://user-images.githubusercontent.com/43240568/148639728-3a6d1273-283c-4b72-a9c7-1b6430cb1d43.jpg)
![Screenshot 2022-01-08 174450](https://user-images.githubusercontent.com/43240568/148639729-6857cdc5-d1ce-4e74-934b-ea02cd20fa8d.jpg)
.
