### ISSUE TITLE
Keep the order of RStudio addins as in addins.dcf

### ISSUE THREAD

**Issue by riccardoporreca** [rstudio/rstudio#3174]
The order in which RStudio displays addins for a given package in the _Addins_ toolbar menu seems to be the alphabetical order of the binding functions. It seems more reasonable to keep the same order as in the registration file inst/rstudio/addins.dcf, thus giving package developers full control of the order in which their addins appear in the toolbar.

-----
RStudio
Version 1.1.453 – © 2009-2018 RStudio, Inc.
Mozilla/5.0 (X11; N; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) RStudio Safari/538.1 Qt/5.4.2

**Comment by ronblum** [comment]
@riccardoporreca Thanks for the suggestion—we'll take a look at it as we continue development of RStudio.
