### ISSUE TITLE
Vignette HTML rendering issues

### ISSUE THREAD

**Issue by slowkow** [rstudio/rstudio#3175]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.774
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

To see the incorrect rendering, run this in RStudio:

```r
vignette("ggrepel")
```

To see the correct rendering, visit this URL in your web browser:

https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html

### Describe the problem in detail

The text in the vignette is invisible:

![image](https://user-images.githubusercontent.com/209714/42886795-768502a2-8a72-11e8-98a0-591a4a6e9751.png)

### Describe the behavior you expected

The text should be visible:

![image](https://user-images.githubusercontent.com/209714/42886782-6c69749c-8a72-11e8-9eb9-136a0f935f65.png)

**Comment by slowkow** [comment]
I can solve the problem by changing the **Editor theme** from `Solarized Dark` to `Solarized Light`.

Indeed, all of the dark themes have the invisible text problem, and all of the light themes seem to render the text correctly.

![image](https://user-images.githubusercontent.com/209714/42887178-5552c2d0-8a73-11e8-92eb-98de3248db79.png)


Here is what the vignette looks like with `Solarized Light`:

![image](https://user-images.githubusercontent.com/209714/42887129-3b458cb0-8a73-11e8-96d2-e1dff2ec1c0d.png)

**Comment by ronblum** [comment]
@slowkow Thank you for raising this concern. We will review it as we work on development of future versions of RStudio.

Reproduced on MacOS 10.12.6 (Sierra) with RStudio Desktop 1.2.830 and Ubuntu 16.04.4 with RStudio Server 1.1.453.

**Comment by jmcphers** [comment]
I'm somewhat concerned that we'll be chasing down edge cases for this for some time as there are lots of different ways someone could inject HTML that defeats our styling. 

We might want to just stop trying to muck with the styling of vignettes entirely -- they won't get dark themed, but they'll also always be readable no matter what, and that's more important. What do you think?

**Comment by slowkow** [comment]
I think the simplest solution is to leave vignette HTML untouched. The downside is that people have already become accustomed to the automatic transformations applied by RStudio, and they'll miss this feature when it's gone.

Alternatively, if RStudio automatically transforms the HTML, it would be nice to publish an explicit documentation of all the transformations applied. Then the authors of vignette HTML styles can plan accordingly if they want to make a theme compatible with RStudio. I like this option.

**Comment by kevinushey** [comment]
I think I agree that we should eschew injection of dark styling for vignettes.

**Comment by kevinushey** [comment]
For what it's worth, I think that if we wanted to bring back support for dark theming of vignettes, we should push the responsibility for theming onto the vignette builder.

One option: RStudio could inject a single CSS class e.g. `dark` onto the document body, and the vignette itself could then supply its own styling for the `dark` case.

**Comment by kevinushey** [comment]
I decided to go with the 'simple' fix here of just screening vignettes that contain an `<article>` tag for now: https://github.com/rstudio/rstudio/commit/71c00b4dfe0354e0c7c8378e76be00721852f41f

If we stumble across more vignette styles that cause us trouble then I'll fully back out styling of vignettes, but for now since the workaround is simple and low-risk I think it's worth making the simple fix for now and deferring the heavier work to later.

**Comment by kevinushey** [comment]
I think this is now suitably handled.
