### ISSUE TITLE
Publishing from server is possible with allow-external-publish set to 0

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3176]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.453, 1.2.817
    OS Version      : Ubuntu 16.04.4, SUSE 12.3
    R Version       : 3.4.4, 3.5.1

### Steps to reproduce the problem

Disable publishing but try to publish something anyway—in this example, a plot:

1) Terminal: add to `/etc/rstudio/rsession.conf` the line
```
allow-external-publish=0
```
2) Terminal: `rstudio-server restart`

3) Console: `plot(cars)`
4) Plots pane: Try to publish the plot by clicking on the blue publish icon

### Describe the problem in detail

Publishing is possible.

### Describe the behavior you expected

Publishing should be disabled in the IDE—the publish icon should not be visible, and the dialog providing publishing options should be inaccessible. 

Note that `allow-publish=0` is working.

Also, I'm doing this based on "Disabling Access to Features" in the administration guide, http://docs.rstudio.com/ide/server-pro/r-sessions.html#feature-limits, and it's possible I'm misreading it.

**Comment by jmcphers** [comment]
`allow-external-publish` only applies to external services such as shinyapps.io or RPubs. You can still see the publish button, and can still publish to services that are run internally (i.e. RStudio Connect). 

To disable publishing altogether, you have to use `allow-publish=0`. 

Does that sound like what you're seeing.

**Comment by ronblum** [comment]
In that case, `allow-external-publish` is working in some cases—including with the steps above—but not in others.

With `allow-external-publish=0`, the RPbus is correctly removed as an option for
- the Plots pane (so the reprex above is not a bug)
- the upper-right button on the Source pane (but see below)
- a running Shiny app

However, RPubs still remains as an option for
- an external HTML viewer for knitted Rmd
- the Viewer pane
- the upper-right button on the Source pane for a file that was previously published using RPubs
   - such as an Rmd that was first published before external publishing was turned off, or the document was published using the external HTML viewer
   - although I think the document getting published is empty in this case
