### ISSUE TITLE
Problems with inability to running rstudio version 1.2.792 (bug 0xc000007b)

### ISSUE THREAD

**Issue by Handy-R** [rstudio/rstudio#3177]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.792
    OS Version      : Windows 7 Ultimate
    R Version       : 3.5.1 (64 bit)

### Steps to reproduce the problem
When opening Rstudio by clicking on the icon, the program failed to start and returned an error message saying "The application was unable to start correctly (0xc000007b)"
### Describe the problem in detail
 I could use the previous version (1.1) without problems. Upon uninstalling 1.1 and installing 1.2, I encountered many messages telling me I missed many .dll files. I used website "dll-sites.com" to download all the missing .dll files (64 bit version .dll files). After that, I started Rstudio 1.2.791 again and got the error message I mentioned above. I tried all the tricks I could find on the Internet to fix this (update Windows .NET, Java, etc.) but to no avail. 
### Describe the behavior you expected
Version 1.2.791 should started without problems like version 1.1.

**Comment by jmcphers** [comment]
We weren't able to reproduce this issue using Windows 7 and the latest daily build, 1.2.834. Does that version work for you?

https://dailies.rstudio.com/

If not, does installing the Visual C++ 2017 Redistributable help? You can get it here:

https://go.microsoft.com/fwlink/?LinkId=746572

**Comment by Handy-R** [comment]
After installing both Rstudio version 1.2.834 and Visual C++ 2017 with  the links you provided, I am still encountering the same bug "The application was unable to start correctly (0xc000007b)". Any further information I need to provide for better inspection ?

**Comment by fortunewalla** [comment]
Just another data point, but the above solution worked for me.

I too faced the same problem when running RStudio-1.2.1114 (preview version). Same Error as above.

I then tried RStudio-1.1.463. It installed and launched properly (Perhaps due to the fact that I had vc++ 2010 Redistributable already installed prior) . 

Then coming across this page, I installed the VC++2017 Redistributable & I was able to run RStudio-1.2.1114

RStudio Edition : Desktop
RStudio Version : Version 1.2.1114
OS Name	Microsoft Windows 7 Home Premium
OS Version      :  Version	6.1.7601 Service Pack 1 Build 7601
R version 3.5.1 (2018-07-02) -- "Feather Spray"

**Comment by fortunewalla** [comment]
> 
> 
> Is your copy of Windows 7 otherwise up-to-date? Have you been installing updates from Windows Update?

Clean Install of w7 HP SP1. No windows/system updates at all. Disabled auto updates. Never did manual window updates (except microsoft office).

**Comment by ChileWonderful** [comment]
Hola, al instalar RStudio y luego abrirlo envía error Loadlibrary Failed 1114 relacionado a un DLL que no específica

**Comment by assissh** [comment]
Install .NET and DirectX to resolve the error

**Comment by ronblum** [comment]
Is this still an issue in [the current RStudio release, 1.2.5019:](https://www.rstudio.com/products/rstudio/download/)? Also, there is [a preview version available](https://www.rstudio.com/products/rstudio/download/preview/), though note that preview builds are intended for testing purposes only.
