### ISSUE TITLE
Syntax highlighting not working and problems with dark themes

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#3179]
RStudio Edition : Server
    RStudio Version : 1.2.832
    OS Version      : Ubuntu Sever 16.04.4 LTS
    R Version       : 3.4.4

### Steps to reproduce the problem
Update rstudio server from 1.2.795 to 1.2.832

    sudo apt-get remove --purge rstudio-server
    sudo apt autoremove
    sudo apt autoclean
    wget https://s3.amazonaws.com/rstudio-ide-build/server/trusty/amd64/rstudio-server-1.2.832-amd64.deb
    sudo gdebi rstudio-server-1.2.832-amd64.deb

### Describe the problem in detail
Syntax highlighting is not working in the source and console panels and there are some problems with dark themes, also theme selection and preview is not working.

![image](https://user-images.githubusercontent.com/14981085/42903575-e4ac748e-8a97-11e8-8bf3-0107da0b3679.png)

![image](https://user-images.githubusercontent.com/14981085/42903665-35ca60ce-8a98-11e8-85cd-cbf8617af4ea.png)

### Describe the behavior you expected
This is the appearance that I get when I downgrade to rstudio server 1.2.795

![image](https://user-images.githubusercontent.com/14981085/42903786-9214943a-8a98-11e8-8ade-28d2c88b0b69.png)

![image](https://user-images.githubusercontent.com/14981085/42903839-b5f65654-8a98-11e8-8139-8c984db9695e.png)

**Comment by jmcphers** [comment]
We're taking a look at this. Thanks for reporting!

**Comment by kevinushey** [comment]
I was able to reproduce this by attempting to upgrade an RStudio Server Pro installation from v1.1 to v1.2. After the upgrade, none of the theme styles seemed to be applied; I saw the same 'black on grey' text as @andresrcs.

FWIW I saw these JavaScript errors:

![screen shot 2018-07-24 at 8 36 25 am](https://user-images.githubusercontent.com/1976582/43149605-aec7a04e-8f1c-11e8-8a1d-4a41faba3507.png)

Although the themes do appear to be installed:

![screen shot 2018-07-24 at 8 37 56 am](https://user-images.githubusercontent.com/1976582/43149669-e1263366-8f1c-11e8-94b2-fd106107e9a7.png)

**Comment by MariaSemple** [comment]
If you've experienced the bug described in this issue, you may have to reset your theme from the Appearance Preferences Pane after updating RStudio to resolve the problem.

**Comment by dfalty** [comment]
Verified fixed on 1.2.872-1.

**Comment by captaincaed** [comment]
I'm having similar issues to this day
RStudio
Version 1.4.1103
© 2009-2021 RStudio, PBC
"Wax Begonia" (458706c3, 2021-01-07) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
