### ISSUE TITLE
Unexpected behaviour of "jump to word" shortcut key

### ISSUE THREAD

**Issue by lyijin** [rstudio/rstudio#3181]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.1.453 
    OS Version      : Windows 10, 1803
    R Version       : 3.5.0

### Steps to reproduce the problem

1. Type any line of text.
2. Ctrl+Left/Right on any lines of text in both the editor and console has the same unexpected behaviour.

### Describe the problem in detail & expected behaviour

In most other applications on Windows, e.g. Word, Notepad++, or even URL bars in any browser, Ctrl+Left/Right jumps to the start of the previous/next word respectively.

In RStudio, Ctrl+Left/Right alternates between jumping to the start of the word, and end of the word (i.e. it takes two Ctrl+Right presses to jump to the next word).

It _might_ be because spaces are considered "words" in RStudio--but this is pure speculation.

(Nitpicky, I know, but it's much more pleasant working in RStudio when it behaves the same way as other text editors. Thanks!)

**Comment by ronblum** [comment]
@lyijin Thanks for pointing this out! We'll take a look at this as we continue future development of RStudio.

Reproduced on Windows 10 with RStudio Desktop 1.1.456 and MacOS (using <kdb>Option-Left/Right</kbd>) both with RStudio Desktop 1.2.830 and a Chrome browser directed at RStudio Server.
