### ISSUE TITLE
Package "car" doesnt work in R 3.5.1

### ISSUE THREAD

**Issue by gabku** [rstudio/rstudio#3184]
Dear everyone,
since yesterday the  package "car" doesnt work anymore. R tells me that it was designed under R Version 3.5.1. which I am using and recomends me to use carData but this package doesnt have the recode function it seems to me.

Does somebodey have a similiar problem? does car really not work vor R 3.5.1? which alternatives do I have?
This is the syntax I was using:

final.data$AE02_07r <- car::recode(final.data$AE02_07,'1=0;2=1;3=2;4=3;5=4;6=5;')

Thank so much!

**Comment by gabku** [comment]
Problem solved. Had to install another package called "haven". The reason for that is still not clear to me^^

**Comment by ronblum** [comment]
@gabku Glad to hear you resolved the issue!
