### ISSUE TITLE
Interface is too slow or crashes with X11 forwarding

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rstudio#3185]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.x
    OS Version      : Fedora 28
    R Version       : 3.5.0

### Steps to reproduce the problem

```
ssh -Y some_machine_with_rstudio
rstudio &
```

### Describe the problem in detail

If the local machine is a Linux box, the interface experiences a **huge** lag, regardless of the connection speed, that is not experienced by other GUI applications, and sometimes it crashes. If the local machine is a Windows box with some X11 server (e.g., `VcXsrv`), the interface is a black screen, and there's the following output in the console:

```
QQuickWidget: Failed to make context current
QQuickWidget::resizeEvent() no OpenGL context
QQuickWidget: Failed to make context current
QQuickWidget: Attempted to render scene with no context
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
QQuickWidget: Attempted to render scene with no context
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
"Pane config is not valid"
QQuickWidget: Attempted to render scene with no context
QQuickWidget::invalidateRenderControl could not make context current
```

### Describe the behavior you expected

X11 forwarding worked just fine with RStudio <1.2, both from Linux and Windows.

**Comment by bscipio** [comment]
For what is worth, there are very similar issues with the Spyder IDE:
https://github.com/spyder-ide/spyder/issues/7447

Which were determined to be more of an issue with the dependencies Qt/PyQt 5 and usage of OpenGL over ssh w/X11 forwarding.   No long term solution is in sight, so we might have to look into VNC, [etc](https://en.wikipedia.org/wiki/Comparison_of_remote_desktop_software).

Also read these Qt bugs, especially the comments:
- https://bugreports.qt.io/browse/QTBUG-50599
- https://bugreports.qt.io/browse/QTCREATORBUG-11173

**Comment by kevinushey** [comment]
If you're using the latest daily builds of RStudio, you could try disabling OpenGL:

<img width="613" alt="screen shot 2018-08-13 at 9 15 23 am" src="https://user-images.githubusercontent.com/1976582/44044108-6f8a74de-9ed9-11e8-8057-dc1e6f08b613.png">

**Comment by Enchufa2** [comment]
If the local machine is a Windows box, then I don't have even the chance to open the menu to apply this workaround, because I get a black screen. It would be very helpful if this could be applied with a command-line flag, i.e., `rstudio --disable-opengl` or something like that.

**Comment by kevinushey** [comment]
You can try setting the environment variable `RSTUDIO_CHROMIUM_ARGUMENTS` to e.g. `--use-angle=warp`. For example:

    set "RSTUDIO_CHROMIUM_ARGUMENTS=--use-angle=warp"
    C:\Program Files\RStudio\bin\rstudio.exe

You can also try editing the file located at:

    %APPDATA%\RStudio\desktop.ini

For example, I have for Software rendering:

```
[General]
font.fixedWidth=DejaVu Sans Mono
RBinDir=C:/R/R-3.5.1/bin/x64
desktop.renderingEngine=software
general.ignoreGpuBlacklist=false
general.disableGpuDriverBugWorkarounds=false
```

(we should re-organize and document some of these options to make it more clear that they can be user-modified in some cases)

**Comment by Enchufa2** [comment]
Sorry, I was probably unclear: RStudio is installed in a remote Linux machine, and I access it through Bash on Linux and VcXsrv from a Windows machine. Do these options apply to Linux too?

**Comment by kevinushey** [comment]
Yes, they apply on all platforms. On Linux the file is located in `~/.config/RStudio/desktop.ini` if I recall correctly.

**Comment by bscipio** [comment]
@Enchufa2 
Did the .ini solution work with VcXsrv?
If so, what version of VcXsrv was used?

FYI: The most recent 1.20.0.1 version has issues with other apps:
https://sourceforge.net/p/vcxsrv/bugs/81/

**Comment by Enchufa2** [comment]
I've just updated RStudio to the latest daily build (1.2.907) and tried the `.ini` workaround. I confirm it works. VcXsrv version is 1.19.6.2.
