### ISSUE TITLE
dplyr::select on list()

### ISSUE THREAD

**Issue by grayskripko** [rstudio/rstudio#3186]
### Steps to reproduce the problem
```r
library(dplyr)
list(a=1, b=2) %>% dplyr::select(a)
```
### Describe the problem in detail

![image](https://user-images.githubusercontent.com/10427026/42955914-e818cf2c-8b7e-11e8-9bc0-286a0491b4d4.png)

### Describe the behavior you expected

An error like in R GUI

![image](https://user-images.githubusercontent.com/10427026/42955960-f9f8431c-8b7e-11e8-80d5-69c34a41401d.png)

### System details
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.5

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.4 compiler_3.5.0   magrittr_1.5     assertthat_0.2.0 R6_2.2.2         tools_3.5.0      pillar_1.2.3     bindrcpp_0.2.2  
 [9] glue_1.2.0       tibble_1.4.2     yaml_2.1.19      Rcpp_0.12.17     pkgconfig_2.0.1  rlang_0.2.1      purrr_0.2.5      bindr_0.1.1

**Comment by kevinushey** [comment]
I'm not exactly sure what's causing the error here, beyond the fact that the version of `select()` you expect to be called, isn't:

```r
> library(dplyr); list(a=1, b=2) %>% dplyr::select(a)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in select.list(., a) :
  select.list() cannot be used non-interactively
Calls: %>% ... withVisible -> <Anonymous> -> <Anonymous> -> select.list
Execution halted
```

That said, `dplyr` works with `data.frame`s, not `list`s, so I don't think this is an RStudio issue.

**Comment by grayskripko** [comment]
the problem has been reproduced by two persons on their machines when I've posted the description on opendatascience.slack.com
I'm sure that while this strange behavior is in RStudio and not in RGui it is an RStudio bug.

An hour ago I called very similar command in RStudio shell, calling "select" on a list of tibbles. That resulted in an RStudio crash. I was able to reproduce it 3 times until realized the fact that there was a list in my variable, not single tibble.

Please check it one more time.

**Comment by kevinushey** [comment]
The behavior of `utils::select.list()`, which is being called by the `dplyr::select()` S3 generic, is controlled by the `menu.graphics` R option. In RStudio, we explicitly disable that in general the user experience provided by the base R dialogs is not great.

If you want the same behavior between RStudio and RGui here you can set

```r
options(menu.graphics = TRUE)
```

although there's no guarantee still that this will work as expected.

It's still not clear to me why you're attempting to use `dplyr` APIs on R lists as opposed to data.frames.

**Comment by grayskripko** [comment]
it was occasionally, by mistake. I stored a list of tibbles in a variable but forgot about it and used it as one tibble.
I strongly believe this is a bug of a wrong behavior on an error. I expect an appropriate error here not RStudio selection without any fixes of options. 
Btw, ```options(menu.graphics = TRUE)``` have helped but it doesn't make big sense for this problem.
I understand that this is not a big issue but I'm sure it a minor bug.
