### ISSUE TITLE
vignettes opened in secondary window get ugly menubar

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3187]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.835
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Open a vignette, and then click the <kbd>Show in new window</kbd>.

### Describe the problem in detail

The main menu bar has a black background, and there is no Print icon. The scrollbar is also tiny.

![screen shot 2018-07-19 at 10 17 28 am](https://user-images.githubusercontent.com/1976582/42959494-e3ef1690-8b3d-11e8-916a-fcdc6f5c5218.png)

### Describe the behavior you expected

Something on par with the v1.1 window.

![screen shot 2018-07-19 at 10 18 14 am](https://user-images.githubusercontent.com/1976582/42959503-eaa84d08-8b3d-11e8-8c99-c58f63fe7b3c.png)

**Comment by dfalty** [comment]
Verified fixed 1.2.1312
