### ISSUE TITLE
ODBC connection not being displayed in the RStudio Connections Pane

### ISSUE THREAD

**Issue by edwardsdm** [rstudio/rstudio#3193]
This code results in the ODBC connection being displayed in the RStudio Connections Pane (as expected)

```
con <- dbConnect(drv = odbc(), driver = s$Driver, host = s$Host,
                 httppath = s$Httppath, port = s$Port,
                 pwd = s$Pwd, schema = "cdl_psoc_dev",
                 sparkservertype = s$Sparkservertype, ssl = s$Ssl,
                 thrifttransport = s$Thrifttransport, uid = s$Uid,
                 authmech = s$Authmech)
```

However, this code does not

```
con <- do.call(dbConnect, c(drv = odbc(), schema = 'cdl_psoc_dev', s))
```

Nor does this code

```
con <- rlang::eval_tidy(quo(dbConnect(drv = odbc(), schema = 'cdl_psoc_dev' !!!s)))
```

Issues seen in:
* RStudio version 1.1.447 & 1.2.679-1
* R v3.4.4
*  Packages odbc_1.1.6 & rlang_0.2.1

**Comment by jmcphers** [comment]
This is an issue in the odbc package, not RStudio. It currently only sends direct calls to `dbConnect` to the Connections pane; if you invoke `dbConnect` indirectly, it intentionally does not trigger the IDE integration. You can see the relevant code here:

https://github.com/r-dbi/odbc/blob/2255001e6d58e523e37a7705595e7293d68ea4d9/R/Driver.R#L115-L133
