### ISSUE TITLE
Replace and Find: repeated replacements via highlighting and key combination

### ISSUE THREAD

**Issue by Pokku3** [rstudio/rstudio#3197]
### System details

    RStudio Edition : 
    RStudio Version : 1.1.453
    OS Version      : Windows 10 (1709)
    R Version       : 3.5.1

### Steps to reproduce the problem
1. Write some text into the editor:
```
Line one
Line two
Line three
```
2. Select some text, such as `three` on line 3.
3. Press Ctrl-Shift-J (or whatever key combination has been associated to _Replace and Find_).
4. Observe how `three` is automatically filled into the _Find_ text field.
5. Select some other text, such as `one` on line 1.
6. Press Ctrl-Shift-J (or whatever key combination has been associated to _Replace and Find_).
7. Observe how the selection moves back to `three`, and text in the _Find_ field remains unchanged instead of being replaced with the just-highlighted `one`.

### Describe the problem in detail
Currently, the _Replace and Find_ bar needs to be initially closed for the highlight + key combination = autofill to work. In case there is nothing in the _Find_ field but the _Replace and Find_ bar is open, nothing happens when pressing the key combination with highlighted text. This is because the key combination first summons the _Replace and Find_ bar, and afterwards triggers replacement as if clicked on the _Replace_ button.

### Describe the behavior you expected
My suggestion is that **the key combination would always replace text in the _Find_ field by what has been highlighted** unless no text has been highlighted. The actual replacement (as if clicked on the _Replace_ button) could still be achieved by pressing Enter in the _Replace_ field as it works currently. This change would align the _Replace and Find_ feature with that of Texmaker's, which I find more intuitive.

In the current state, the only ways to change the text in the _Find_ field are:
- Closing the _Replace and Find_ bar, and then reopening it with the key combination after highlighting the new text.
- Copying and pasting the new text into the field.
- Typing the new text into the field.

None of these ways are as convenient as simply selecting text and pressing a single key combination.
However, I can see that this change could harm some people's workflows (if they rely on the key combination for the actual replacement), which is why I am inviting discussion on this matter.

**Comment by ronblum** [comment]
@Pokku3 Thanks for the suggestion and the reasoning behind it. We'll take a look at it as we continue to develop new versions of RStudio.
