### ISSUE TITLE
Compile fails on Raspberrypi with Raspbian Stretch

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#3204]
### System details

    RStudio Edition : Server
    RStudio Version : 
    OS Version      :  Raspbian Strech
    R Version       :  3.5.1

### Describe the problem in detail
I am trying to compile Rstudio Server on a Raspberry Pi 3
Compile breaks with this error message:

```
/usr/bin/ld: /opt/rstudio-tools/boost/boost_1_63_0/lib/libboost_regex.a(icu.o): undefined reference to symbol 'u_digit_52'
//usr/lib/arm-linux-gnueabihf/libicuuc.so.52: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/cpp/session/CMakeFiles/rsession.dir/build.make:4674: recipe for target 'src/cpp/session/rsession' failed
make[2]: *** [src/cpp/session/rsession] Error 1
CMakeFiles/Makefile2:564: recipe for target 'src/cpp/session/CMakeFiles/rsession.dir/all' failed
make[1]: *** [src/cpp/session/CMakeFiles/rsession.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
```

I installed all the necessary tools including boost 1.63.
Is there a way to get over this?

**Comment by kevinushey** [comment]
We haven't tried compiling RStudio on a Raspberry Pi yet, so we'll struggle to provide accurate advice. 

Perhaps Boost doesn't work with the version of ICU installed on your machine? If so, you might need to build Boost without ICU explicitly.

**Comment by neuwirthe** [comment]
It turns out ICU on Raspbian is at version 57.1, and the current version is 62.1.
This might be the reason for the compile fail.

**Comment by ronblum** [comment]
@neuwirthe I'll mark this closed since it appears to be an issue with Raspbian. If you have any more information, especially if you've gotten it to work, you can still update the ticket—it would be helpful to others who run into the same issue. Thanks!
