### ISSUE TITLE
'Run Tests' fails when attempting to run unexported functions

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3208]
See associated community post: https://community.rstudio.com/t/run-tests-feature-could-not-find-non-exported-function/11333

![tests](https://user-images.githubusercontent.com/1976582/43090816-4e5cf714-8e5d-11e8-8f24-863628ac80fd.gif)

We likely need to invoke `devtools::load_all()` before running the test code.

**Comment by jmcphers** [comment]
@javierluraschi could you take a look?
