### ISSUE TITLE
main window quits before satellite has confirmed file saves

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3210]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.830
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Open RStudio, tear out a source file into a satellite window, and change the contents so it's "dirty" (has a red label with the asterisk). Then, attempt to quit with <kbd>Cmd + Q</kbd>.

### Describe the problem in detail

The main window closes before the associated prompt on the satellite window has been acted upon by the user.

### Describe the behavior you expected

RStudio shouldn't close until saves of open files in all satellite windows have been reconciled.

![save-synchronization](https://user-images.githubusercontent.com/1976582/43156608-7c964414-8f2f-11e8-9040-85de5cdf83c5.gif)

**Comment by kevinushey** [comment]
Also curious: in RStudio v1.1, we don't receive any prompt when attempting to close a satellite window containing only an unsaved, untitled document; yet here we are receiving one.

**Comment by kevinushey** [comment]
Note that RStudio does correctly wait for the user to act on the dialog if the file is titled / named, so perhaps the issue here is simply that we're erroneously showing this dialog even for untitled files.

**Comment by kevinushey** [comment]
One other data point. With RStudio v1.1, attempting to close a satellite window that contains only an untitled file by clicking the window's close button _does_ prompt you to save it, which is in line with the RStudio v1.2 behavior.

So the issue is scoped to Quit Application: with RStudio v1.1, this skips untitled files; with RStudio v1.2, it does not (and this seems to also lead to an early exit of the main window).

**Comment by kevinushey** [comment]
@jmcphers I think you're best equipped to tackle this one but let me know if you'd prefer I try and dig in more.

**Comment by jmcphers** [comment]
Yes, we shouldn't be prompting here. We ignore untitled files; they'll autosaved and will return RStudio is opened again. I'll take a look.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
