### ISSUE TITLE
Global Options does not fit on screen in default display configuration for some laptops

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3215]
With a Yoga 2 Pro Ultrabook, 3200 x 1800 screen resolution, the Global Options page does not fit on the screen:

![scale](https://user-images.githubusercontent.com/1976582/43167032-40705a92-8f4d-11e8-8fbe-e7e79d0ee60f.JPG)

Note that on this system, Windows has set the recommended scaling at 250%, which is part of the reason why this oversized UI happens:

![scaling](https://user-images.githubusercontent.com/1976582/43167115-71028784-8f4d-11e8-8f56-2b7180654786.PNG)

I suspect that perhaps Windows uses higher UI scaling by default for laptops with touch displays, reflecting the fact that larger UI is usually required for touch actions.

We should consider whether we could improve the default user experience for users with laptops / convertible tablets in this configuration, although I'm unsure what the best solution would be beyond attempting to detect the system scaling and under-zooming in response to a high scale.

**Comment by jmcphers** [comment]
Possible solution:

- Wrap options dialog in a container with max height - 100% of viewport
- Ensure that the interior of each page of options is wrapped in a ScrollPanel

**Comment by kevinushey** [comment]
Also saw an example of this on an Acer Swift 7 (14" display; 1920 x 1080 resolution).

The Windows default display scaling was set at 150%; when RStudio was launched, it was as though the UI had been double-zoomed (an extra 150%) and so UI elements were too large.

Using `Ctrl + -` to unzoom the IDE was a workaround.

As an aside, by monkeying around with the Windows compatibility settings, if we disabled the scaling performed by the application, then the zoom factor looked correct again — but now, the whole IDE was blurry.

**Comment by kevinushey** [comment]
Marking as v1.3 so we at least think about this. Even some mitigation to help prevent the option dialogs from overflowing the IDE viewport would be worthwhile.

**Comment by gtritchie** [comment]
This is also a potential accessibility issue, since low-vision users may use the product at a high-level of scaling instead of (or in addition to) using a magnification program.

**Comment by gtritchie** [comment]
Ah, thought this sounded familiar. See also https://github.com/rstudio/rstudio/issues/1605.

**Comment by gtritchie** [comment]
Marked #1605 as v1.3, closing this as a duplicate.
