### ISSUE TITLE
Auto-complete function arguments on new line

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#3216]
Auto-complete of function arguments (slash the function help tooltip) within `(` of a function call fails on a new line -- a `tab` is inserted instead:

Auto-complete works fine on the same line:

![screen shot 2018-07-25 at 10 13 22 am](https://user-images.githubusercontent.com/7606389/43175800-7c957c54-8ff3-11e8-8ee8-458170f2d3ba.png)

But if we go to the next line (where auto-indent smartly brings us just to the right of the preceding `(`, so RStudio knows we're "inside" the function call):

_\<before tab\>_
![screen shot 2018-07-25 at 10 13 49 am](https://user-images.githubusercontent.com/7606389/43175826-95b34a54-8ff3-11e8-9325-d30cea9d7b84.png)

_\<after tab\>_
![screen shot 2018-07-25 at 10 13 57 am](https://user-images.githubusercontent.com/7606389/43175833-9aa8befe-8ff3-11e8-93e6-9fdf2e5f9feb.png)

As long as we're inside of `(`, I don't see a need for inserting indentation when pressing tab; perhaps I'm missing something, but it seems unambiguous that I'm trying to get function argument auto-complete there.

**Comment by kevinushey** [comment]
You can toggle this in Tools -> Global Options; see the 'Use tab for multiline autocompletions' option:

![screen shot 2018-07-25 at 10 44 16 am](https://user-images.githubusercontent.com/1976582/43217892-bdcef87c-8ff7-11e8-8e30-de8cd8bef581.png)

**Comment by MichaelChirico** [comment]
Indeed I was missing something! Thanks
