### ISSUE TITLE
Menu bar with black text on dark background in Kubuntu with dark desktop theme

### ISSUE THREAD

**Issue by asalarian** [rstudio/rstudio#3217]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Kubuntu 18.04 LTS
    R Version       : MS R Open 3.5.0

### Describe the problem in detail
I am using a dark theme on Kubuntu so I have also selected a dark theme for the editor (Pastel on Dark). The issue as you can see in the picture below is that the menu bar is rendered with black text on dark background! 

![image](https://user-images.githubusercontent.com/10533408/43204378-f230be42-9020-11e8-8c86-7883d13463ab.png)

Also, the dialog boxes such as the "About RStudio" or "Global options" do no show up correctly as the dialog box is rendered using light theme but some widget are dark with black text:

![image](https://user-images.githubusercontent.com/10533408/43204625-b1051598-9021-11e8-9461-a2d81decf9f6.png)

If I switch to a light theme for the editor while keep using a dark theme for my Kubuntu desktop, in RStudio everything changes to light but the menu bar remains the same (i.e. black text on dark background).

### Describe the behavior you expected
The menu bar should use white for text and when using a dark desktop theme, the dialog boxes should use a dark theme as well.

**Comment by kevinushey** [comment]
What styling is used for other applications on your machine (for menu text and input select boxes)?

**Comment by asalarian** [comment]
I am using the "Modern" desktop theme. The behavior is the same when I use the out of the box "Breeze Dark" theme.
Currently, RStudio is the only application that has this problem. Everywhere else the dark theme is working correctly with the menu text, etc.

**Comment by sebastian-de** [comment]
I have this problem, too, when using the "Breeze Dark" theme in Kubuntu.
The menu bar text always stays black, but the colors of menus look fine:
![screenshot_20181013_204200](https://user-images.githubusercontent.com/7430495/46908821-de4c8b80-cf28-11e8-9c42-350ca5c327cb.png)
The palette for Breeze Dark can be found here:
https://cgit.kde.org/breeze.git/tree/colors/BreezeDark.colors

As a quick fix, I currently start RStudio with the default theme:
`QT_QPA_PLATFORMTHEME=“” rstudio`

**Comment by kevinushey** [comment]
I see the same thing in some other applications (e.g. FireFox) so it seems like elements of the system theme are leaking inappropriately into applications. Fixing this likely implies rolling our own versions of all the 'default' UI elements so that system themes don't get in the way.

**Comment by jtatria** [comment]
I can confirm that this problem still affects RStudio 1.1.463 on KDE using the built-in Dark Breeze plasma theme, but it does not affect Firefox at all.
![image](https://user-images.githubusercontent.com/3020384/56691421-eb9fbb00-66ad-11e9-94d7-80fd09466d54.png)

![image](https://user-images.githubusercontent.com/3020384/56691442-fc503100-66ad-11e9-8710-878a063e4087.png)
