### ISSUE TITLE
Feature request: don't show any hidden files until user asks for them

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#3221]
The IDE will display a hidden file in the file browser if it's name falls on a short list of important hidden files used by R. For example, the IDE shows .Rhistory in the image below:

<img width="236" alt="screen shot 2018-07-25 at 10 49 34 am" src="https://user-images.githubusercontent.com/85014/43219885-2dd7327c-900e-11e8-8819-df0835a4954d.png">

I think this is a bad idea for the following reasons:

1. The files distract students. I'd like students to be able to zero in on the files that _I_ place in their working directory, but the hidden files appear at the top of the list.
1. The files intimidate students; it seems like there is a lot going on that the student does not understand and is not in control of.
1. The files give students the opportunity to accidentally mess up something that they won't know how to fix. (There are good reasons to learn how to work with hidden files before you edit .Rprofile and .Rhistory) 

These considerations are especially important in RStudio Cloud where the behavior bleeds into the classroom. However, there are also non-student related reasons to end the behavior:

1. RStudio now has a More > Show Hidden Files option in the files pane. This makes it unnecessary to always show some hidden files.
1. Users who do not wish to see the hidden files will uncheck More > Show Hidden Files to make them go away. However, these files will not go away, which is unsatisfactory and may seem like a bug.

**Comment by ronblum** [comment]
This is addressed by #8895.

**Comment by R-Hannibal** [comment]
@ronblum - assigning this your way as the PR which addresses this ticket is also the fix for: https://github.com/rstudio/rstudio/issues/8658.

**Comment by ronblum** [comment]
@garrettgman This would now be handled by setting these fields in `.config/rstudio/rstudio-prefs.json` (taken from #8895). Does take care of what you're looking for?

```
{
  "always_shown_extensions": [],
  "always_shown_files": []
}
```

**Comment by garrettgman** [comment]
@ronblum Thanks. What a blast from the past. Two pieces of feedback:

1. **This solution will not be helpful if the student needs to edit a file before it takes effect (or if I need to edit it for them).** If the behavior propagates when a student copies an RStudio Cloud project, that will be a win, so long as we are using RStudio Cloud projects. The goal of the behavior is to focus student attention when they first view the files pane.

1. **The solution should be a GUI method in the IDE.** I'd have to start experimenting to figure out which `.config` file you are talking about and where it lives before I could use it. It is not obvious to me. I think a large fraction of R users and R teachers will not attempt to use your solution. Adoption would be larger if we provided a GUI method to alter the `.config` file.

If we truly care about this problem (I'm not sure that I still do), the ideal solution would be to hide hidden files by default and to provide a prominent, easily discoverable button to unhide them. I suspect the practical needs of R users outweigh the attention needs of R students here—and I am 100% OK with that. If there are any plans to build a "student" mode for the IDE, let's add this feature to that.

**Comment by ronblum** [comment]
@jmcphers What are your thoughts regarding @garrettgman's points?

**Comment by jmcphers** [comment]
Garrett is right that we should not expect students to configure this. The change is designed to make it possible for admins setting up RStudio Server for student use to give those students a simpler Files Pane. We could easily, for example, make it the default behavior on rstudio.cloud if we wanted since that's primarily a learning platform.

**Comment by ronblum** [comment]
@jmcphers and @garrettgman Thank you!
