### ISSUE TITLE
Scrollbars overpower modals

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#3222]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.837
    OS Version      :  OSX, 10.13.6, 
    R Version       : 3.4.0
    Hardware: 2016 15" MBP

### Steps to reproduce the problem

<img width="1527" alt="screen shot 2018-07-25 at 2 32 45 pm" src="https://user-images.githubusercontent.com/1593639/43223192-f1e10568-9017-11e8-9296-f08ee385db5b.png">

Open a modal like "About" or "Global settings"

### Describe the problem in detail

Overly aggressive scrollbars!

### Describe the behavior you expected

Less aggressive scrollbars.

**Comment by trestletech** [comment]
A couple of other notes: Firefox just had a glitchy presentation in the tab bar which I haven't seen before today. Can't repro there, though. Could imply system instability, though.

One other data point: I shared my screen using GoToMeeting this morning for a webinar, which is unusual.

**Comment by kevinushey** [comment]
FWIW I can't reproduce locally on a similar setup (late 2013 MBP, macOS 10.13.6).

Does toggling when scrollbars are shown by the OS make a difference?

![screen shot 2018-07-25 at 12 55 24 pm](https://user-images.githubusercontent.com/1976582/43224126-12bf2f02-900a-11e8-9264-8fc6e59c9993.png)

Does the issue persist after a system restart?

**Comment by trestletech** [comment]
Can't repro after a reboot. Also had trouble rebooting based on whether or not scrollbars were showing. I think you're safe to close this one unless anybody else encounters it.

We can blame GoToMeeting and/or my laptop being overdue for a nap.
