### ISSUE TITLE
CRAN repository mirror sticking to cloud.r-project.org

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3224]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.850-1
    OS Version      : Ubuntu 16.04.4
    R Version       : 3.4.4

### Steps to reproduce the problem

Choose the CRAN repository mirror in one of the following ways:
1. Do nothing and rely on the default (RStudio).
2. Change the mirror using the GUI.
   - Tools -> Global Options -> Packages
3. Change the `r-cran-repos` setting in `/etc/rstudio/rsession.conf`, e.g.
   - `r-cran-repos=http://ftp.eenet.ee/pub/cran/`
4. Add records to the `/etc/rstudio/repos.conf` config file.

### Describe the problem in detail

No matter what, the repository is always "https://cloud.r-project.org" .

### Describe the behavior you expected

1. Choice 1: The default should be "https://cran.rstudio.com/".
2. Choices 2–4: The locations should change.

**Comment by jmcphers** [comment]
@javierluraschi can you take a look?

**Comment by ronblum** [comment]
It looks like this is an across the aboard Unix issue: I see the same issue on Ubuntu Desktop when changing the mirror using Tools -> Global Options -> Packages.

**Comment by ronblum** [comment]
It turns out that Ubuntu and Debian have an Rprofile file that sets the repository to "https://cloud.r-project.org". If it's commented out, the problem goes away

`/usr/lib/R/etc/Rprofile.site` with offending line commented out:
```
local({
    r <- getOption("repos")
    # r["CRAN"] <- "https://cloud.r-project.org"
    options(repos = r)
})
```

**Comment by ronblum** [comment]
Confirmed. Changing the mirror using Global Options sticks in RStudio Server 1.2.872 on Red Hat and RStudio Server Pro 1.2.872-1 on SUSE 12.3. So, verified that the works, and it's an issue with Ubuntu's default configuration.

**Comment by kevinushey** [comment]
If we're potentially running afoul of profile settings in the system profile, should we consider altering the precedence of these settings? I think lots of users are going to get confused by this.

It seems to me that the settings here should probably override global profiles. (and maybe user profiles too?)

I could be wrong but I think it's worth discussing. Even if we take no action I think this needs to be documented somewhere.

**Comment by jmcphers** [comment]
> If we're potentially running afoul of profile settings in the system profile, should we consider altering the precedence of these settings? I think lots of users are going to get confused by this.

Let's open a separate issue for this.

**Comment by kevinushey** [comment]
E-mail correspondence with @javierluraschi indicates that the current behavior is documented + expected.

**Comment by markleeds2** [comment]
Hi All: I saw thi thread  and I think it's very relevant to my current problem. I used Ubuntu 16.04 and  I commented out the setting of the cloud repository in my Rprofile.site as described.  But, still, I'm going through a tutorial from the internet step by step and  when I click on Install and Restart ( which is one of the steps ), I get below.

=> devtools::document(roclets = c('rd', 'collate', 'namespace'))

Updating rpkg documentation
Loading rpkg
Installing package into ‘/home/markleeds/research/R/Rlibs/library’
(as ‘lib’ is unspecified)
Error in contrib.url(repos, type) :
  trying to use CRAN without setting a mirror
Calls: suppressPackageStartupMessages ... eval -> install.packages -> startsWith -> contrib.url
Execution halted

Exited with status 1.

#========================================================================

I could include the contents of  the rpkg directory but I'm thinking that maybe someone knows the fix without needing to reproduce it. I have a feeling that it only happens on Ubuntu but I'm not certain about that. Thanks.

**Comment by markleeds2** [comment]
I forget to mention that, when I check the value of options()$repos, it is cran.rstudio.com so the environment where install and re-start runs must not know about the value of the repository.
