### ISSUE TITLE
RStudio.Version() should report "Open Source" edition for open source

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3226]
Currently, we just return `NULL` and so the `edition` field is never populated: https://github.com/rstudio/rstudio/blob/96d9d31baadecda623f7bf9ff0c15a3d562f071a/src/cpp/session/SessionModuleContext.cpp#L309-L313

**Comment by jmcphers** [comment]
Is there a reason we need to change this historical behavior? `RStudio.Version()` already returns `Professional` as the edition in RStudio Server/Desktop Pro. I think "Open Source" is clearer than NULL but no reason to change any code that might rely on it unless it's breaking things.

**Comment by jmcphers** [comment]
Closing since we haven't had any more evidence of people being confused by this  -- and, of course, we now have a 4 year precedent that we incur risk by reversing. :-)
