### ISSUE TITLE
"Jumpy" scrolling behaviour on Ubuntu 16.04 LTS when editing RMarkdown files

### ISSUE THREAD

**Issue by grssnbchr** [rstudio/rstudio#3227]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.453 (actually>1.0.0)
    OS Version      :  Ubuntu 16.04 LTS
    R Version       :  3.4.4

### Steps to reproduce the problem

Open up RStudio on this operating system and scroll around in the Editor pane, ideally in an RMarkdown file.

### Describe the problem in detail

While scrolling (with the mousewheel) an RMarkdown file in the Editor pane (don't know if it's called that, just the big window where you edit files), from time to time, the viewiport will jump several "pages" and end up several code chunks above or below its previous position. 

I've been having this problem since RStudio version 1.0, both on my VirtualBox VM and on my native Ubuntu on my Lenovo laptop (where the problem also appears while touch-scrolling on the touchpad).

### Describe the behavior you expected

I expect to see "a linear mapping" between how much I scroll and how much the viewport changes.

**Comment by ronblum** [comment]
@grssnbchr I am unable to reproduce the problem with the same environment and version, although I'm currently using the touchpad on a MacBook Pro.

A few things that might help:
1) Which desktop are you using? I am on GNOME 3.18.5
2) Can you provide the code your using? I created a multi-page R Markdown file in the Editor pane (you've got the name right!), but trying out your Rmd would be helpful.

**Comment by grssnbchr** [comment]
1. Since Ubuntu 16.04 shipped with Unity, I guess I'm on `unity --version` = `7.4.5`. `gnome-terminal` gives `GNOME Terminal 3.18.3` though. I could also try out installing the Gnome shell and test it with that - or update to Ubuntu 18.04 if needed.
2. Well basically any RMarkdown file I've worked with so far, for example https://github.com/srfdata/2018-01-roger-federer/blob/master/analysis/main.Rmd . Be aware though that this uses [checkpoint](https://github.com/grssnbchr/rddj-template.git) to load packages for full reproducibility, although I think that doesn't make a difference.

Lastly, it's important to mention that the jumpy scrolling doesn't *always* occur, it appears rather randomly, not during every scroll.

**Comment by ronblum** [comment]
@grssnbchr Thanks! I switched to Unity 7.4.5, used your R Markdown file, and tried scrolling a bunch of times at different speeds, but still couldn't reproduce the problem. If you're willing to try out Gnome, that would be cool so that we can see if that at least makes a difference. But in the meantime, I'll stick to Unity and keep an out eye on whether the problem at least occasionally.

**Comment by grssnbchr** [comment]
Okay, thanks, I'll do that asap. Btw: Maybe clicking on the outline on the right side a few times, as well as clicking on various chunk outputs might trigger it?

**Comment by ArtPoon** [comment]
I'm also encounting this issue editing Rmarkdown with RStudio 1.1.456 on Ubuntu 16.04 with LightDM verison 1.18.3.

**Comment by statnmap** [comment]
I also encountered this problem on Ubuntu 16.04 and previous versions of Rstudio desktop. 
Now, with Ubuntu 18.04 and latest Rstudio desktop versions (dailies.rstudio.com), this did not appear for a while.
Maybe this issue can be closed ?

**Comment by ronblum** [comment]
Thanks for the update! So it seems like the issue might be limited to Ubuntu 16.04 and earlier versions of RStudio. If anyone still sees this issue using the latest version of RStudio Desktop, 1.2.5033 available at https://rstudio.com/products/rstudio/download/#download, please update the ticket.
