### ISSUE TITLE
dark system themes play poorly with RStudio, RStudio Server (Firefox)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3229]
### System details

    RStudio Edition : Both
    RStudio Version : v1.2.856-2
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.1

### Steps to reproduce the problem

Apply a dark system theme; for example, Adwaita-dark. (I did this with the GNOME tweak tool; installed with `sudo apt install gnome-tweak-tool`).

### Describe the problem in detail

'Default' themes for web elements (checkboxes, etc) are dark, and do not play well with the IDE.

![screen shot 2018-07-26 at 12 12 07 pm](https://user-images.githubusercontent.com/1976582/43283429-b3035e84-90cd-11e8-94e2-02856abeb10d.png)

### Describe the behavior you expected

Cohesion between the system theme and the IDE.

I think there's two possible resolutions here:

1. We take the time to implement a 'dark' modal theme;
2. We make the styling for default UI elements (e.g. checkboxes) explicit, to avoid clashing with decisions made by the system theme that don't play well with RStudio.

@jmcphers: do you think one of these resolutions is worth exploring for v1.2?

**Comment by kevinushey** [comment]
Worth noting that the issue is not entirely cosmetic; some do impact usability of the IDE: the larger checkboxes + selectboxes are enough to push some UI elements out of view; e.g. note that the **Other** element near the bottom of the modal above is no longer visible.

**Comment by ronblum** [comment]
Is this related to #3217?

**Comment by kevinushey** [comment]
Yes, I believe so.

**Comment by kevinushey** [comment]
> And we do typically draw our own checkboxes specifically to avoid these kinds of issues; see #3190. I'm not sure why our own checkboxes aren't working here. I'd suggest investigating why that isn't happening as a first run.

Looks like the answer here is simple: we suppress the default system styling for these input elements here:

https://github.com/rstudio/rstudio/blob/a44de313f545d37645296f766d29dec295e0d896/src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css#L1838

but Firefox doesn't understand `-webkit-appearance`, while it does understand `-moz-appearance`. (Surprisingly, it didn't seem to support plain old `appearance`; at least in the version of Firefox I had installed; 61.0.1)

**Comment by kevinushey** [comment]
FWIW, enterprising users appear to work around this by defining specific styles within Firefox: https://askubuntu.com/questions/1037517/how-to-fix-dark-theme-issues-with-firefox

**Comment by kevinushey** [comment]
Given that this is a Firefox-specific behavior that can be worked around (and it does not affect other browsers) I'm going to punt the rest of this.

**Comment by jmcphers** [comment]
Closing since we've punted on this scenario.

**Comment by joh4nd** [comment]
Added feature request: https://github.com/rstudio/rstudio/issues/13120
