### ISSUE TITLE
rstudio crashes on close if file no longer exists

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3231]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.846
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Open a file in the IDE, then delete that file from the disk. You'll get a **File Deleted** prompt:

<img width="427" alt="screen shot 2018-07-26 at 6 37 36 pm" src="https://user-images.githubusercontent.com/1976582/43296895-ff4424ec-9102-11e8-8080-3c0ddcd27d7e.png">

Click <kbd>No</kbd>. The file remains open in the IDE, but 'dirty'. Then, attempt to quit the IDE (with <kbd>Cmd + Q</kbd>). You'll be prompted to save changes:

<img width="461" alt="screen shot 2018-07-26 at 6 38 27 pm" src="https://user-images.githubusercontent.com/1976582/43296923-1d7af878-9103-11e8-9534-78cc0abb7725.png">

Click <kbd>Don't Save</kbd>.

### Describe the problem in detail

A **Save File** error displays:

<img width="432" alt="screen shot 2018-07-26 at 6 38 52 pm" src="https://user-images.githubusercontent.com/1976582/43296950-34bdc902-9103-11e8-9c50-89eb295cc2f6.png">

After clicking <kbd>OK</kbd>, the session 'aborts' and the bomb is shown. (In reality, the process has already exited; the display of the dialog obscures that fact)

### Describe the behavior you expected

RStudio shouldn't crash on close.

**Comment by ronblum** [comment]
Reproduced on MacOS 10.14 (Mojave). Note that going through the process a second time (after restarting R from the bomb's button), quitting is successful. But when reopening, the tab is still there.

**Comment by jmcphers** [comment]
There's no real crash here; `base:::q()` is being called and the session is exiting normally. The problem is that we're shutting down the R session prematurely, before we've finished dealing with unsaved content.

**Comment by kevinushey** [comment]
The issue here is that RStudio is attempting to revert the contents of the unsaved document before save. The two main components here:

1. The document is file-backed, and
2. The document is 'dirty'.

Because of this, on exit, when we request "Don't Save", the IDE attempts to revert the file contents in the source database to that of the associated file on the filesystem. This fails and gives the "No such file or directory" error, as the associated file on disk has been deleted.

RStudio does track whether the associated file has been deleted here:

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L6353

so we can probably make use of that flag when deciding whether to show an error message to the user if a revert fails.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
