### ISSUE TITLE
NAs produced by integer overflow after a data frame containing many large integers is viewed

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#3232]
### System details

    RStudio Edition : 1.2.691
    RStudio Version : Server
    OS Version      : Ubuntu 18.04
    R Version       : 3.4.4

### Steps to reproduce the problem

Create a data frame of large integers and `View` it.

```r
data <- data.frame(id = 12345678:13456789)
View(data)
```

Close the viewer and run any command such as `x <- 1`.

Then a warning message appears:

```
Warning message:
In n * h : NAs produced by integer overflow
```

It seems that the integers must be large enough and lie in a wide range to cause this warning.

```r
data <- data.frame(id = 20180101:20180720)
```

will not cause any problem while

```r
data <- data.frame(id = 10180101:20180720)
```

causes exactly the same problem.

**Comment by ronblum** [comment]
@renkun-ken Thank you for reporting this issue. I was able to reproduce it on RStudio Desktop 1.2.858 on MacOS 10.14 (Mojave), but not on 1.1.456. We'll take a look at as we continue development of 1.2.

**Comment by kevinushey** [comment]
This is caused by us attempting to call `hist()` on the numeric data:

```R
> data <- data.frame(id = 12345678:13456789)
> hist(data$id)
Warning in n * h : NAs produced by integer overflow
```

The error is emitted here: https://github.com/wch/r-source/blob/trunk/src/library/graphics/R/hist.R#L131

We should just suppress the warning as it does not affect anything RStudio uses or needs here.

**Comment by kevinushey** [comment]
I've reported this upstream since I think it might be sensible for R itself to convert the values here with `as.numeric()` before computing the product: https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17450

Nonetheless I think we can safely just suppress the warning here.

**Comment by renkun-ken** [comment]
Thanks for the nice work!

**Comment by amorrissey-veho** [comment]
I was able to get mine to run with as.numeric(), but then the output is numeric rather than integer
