### ISSUE TITLE
Package build tools call to roxygen2 in devtools loses the .libPath

### ISSUE THREAD

**Issue by dpolhamus** [rstudio/rstudio#3235]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.830 (preview), but also on current stable release
    OS Version      : MacOSX-Sierra
    R Version       : 3.4.1

### Steps to reproduce the problem

* Create a project to build a package.  
* This package has a set of dependencies set in a library that are not on the default library PATH.  E.g., `../lib`  
* In the build options:
  * Use devtools package function if available
  * Tell Rstudio to "Generate documentation with Roxygen"
  * Automatically roxygenize on install and restart
4. Clicking "install and restart" gives an error because we can't find the dependencies necessary to build the documentation

### Describe the problem in detail

While calling devtools::document from the R session appears to work as intended (i.e., it picks up the .libPaths of the calling R session), Rstudio's issuing of the `devtools::document` command does not.

* This can be remedied by adding the library containing the dependencies for the build to `~/.Renviron`, but that's undesirable as this is a library of dependencies specific to this package. 
* Extending the `.libPaths` via Rprofile in the working directory does not fix the issue

This is the exact error I get:

![document_error](https://user-images.githubusercontent.com/707490/43332502-9c05f5e2-9196-11e8-8425-20b41f60771c.png)

### Describe the behavior you expected

As `devtools::document` works as expected (recognizes the libPaths for the session), I'd expect the Rstudio build process (based upon devtools) to also do so.

**Comment by kevinushey** [comment]
Thanks for the bug report! I can reproduce this. In fact, we do appropriately propagate the library build paths for e.g. `R CMD INSTALL` but not for `devtools::document()`.

For example, if I create a new R package and add a file `R/aaa.R` with the contents `writeLines(.libPaths())`, then set up the project to use devtools and document on package build, I see the following after building the package:

```
==> devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))

Updating libpaths documentation
Loading libpaths
/Users/kevin/Library/R/3.5/library
/Library/Frameworks/R.framework/Versions/3.5/Resources/library
First time using roxygen2. Upgrading automatically...
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
Documentation completed

==> R CMD INSTALL --no-multiarch --with-keep.source libpaths

* installing to library ‘/private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/RtmpjaUsDQ’
* installing *source* package ‘libpaths’ ...
/private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/RtmpjaUsDQ
/Library/Frameworks/R.framework/Versions/3.5/Resources/library
/Users/kevin/Library/R/3.5/library
No man pages found in package  ‘libpaths’ 
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (libpaths)
```

Two things to note:

1. The custom library path is not overlaid for `devtools::document()`,
2. It is overlaid (and first) for `R CMD INSTALL` but the default library paths still tag along as the last library path entry (even though that doesn't exist in `.libPaths()`).

We'll take a look!

**Comment by grosscol** [comment]
I've run into this exact issue.  Details of what I tried and what I used to solve it on Ubuntu are [here](https://community.rstudio.com/t/rstudio-build-source-package-not-picking-up-user-libpath/40221/7).  In short, setting `R_LIBS_USER` to `/path/to/your/library` **for the Rstudio process** solved this issue for me.

**Comment by kevinushey** [comment]
Fixed in the daily builds via https://github.com/rstudio/rstudio/pull/5853.
