### ISSUE TITLE
Feature request) Refresh Find in Files

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#3240]
I often use Find in Files to remove or alter instances where I use a function across my package. It would be neat if there was a Refresh button in the Find in Files pane rather than having to Edit->Find in Files->Find over and over (the shortcut helps too). 

That way I could remove a few of them, refresh, see what I have left, and iteratively do this until I change them all.

**Comment by ronblum** [comment]
@DavisVaughan Thank you for the suggestion! I see what you mean. On the plus side, at least when you go back to Find in Files—through the shortcut or menu—the search term is still in the input field. But still, we'll take a look at this as we work on continuing development of RStudio.

**Comment by DavisVaughan** [comment]
Yes! The persistence of the input field is really helpful.

These are just musings of a Find in Files power user :+1: 

Thanks for your hard work!

**Comment by kevinushey** [comment]
FWIW I agree adding a little refresh icon to the top-right corner of that pane (to just re-run whatever query was last run) would be useful.

**Comment by DavisVaughan** [comment]
That is exactly what I am asking for :+1:

**Comment by DavisVaughan** [comment]
Keep alive

**Comment by DavisVaughan** [comment]
Keep alive

**Comment by mikebessuille** [comment]
A refresh button is probably a nice short term solution.  Longer term, would be nicer if this just refreshed automatically as the file changes.

**Comment by mikebessuille** [comment]
@jgutman is this something we could easily do in Spotted Wakerobin, while you're touching that code?

**Comment by jgutman** [comment]
> Longer term, would be nicer if this just refreshed automatically as the file changes.
I'm actually not sure of the value of that yet -- "refreshing automatically" here would probably just mean re-running the search at some discrete interval, and depending on the size of the directory being searched, the search could take a long time, possibly even longer than the length of the refresh interval. There's also no guarantee that the files which the user is searching and replacing are even open in the editor. Therefore I think the refresh button is actually probably a reasonable long-term solution, not just in the short term

**Comment by ronblum** [comment]
Suggestions for QA: The equivalent of a partial regression of "Find in Files" 
- File content changed: so text that didn't match now matches
- File content changed: test that matched no longer matches
- File permissions changed: previously writeable no longer no read-only
- File permissions changed: previously read-only file now writeable permissions
- File permissions changed: previously inaccessible file now read/writeable
- File permissions changed: previously read/writable file now inaccessible.
In all cases, check that both "Find" and "Replace" are updated correctly.

**Comment by romainfrancois** [comment]
When on the "Replace" tab: 

<img width="930" alt="image" src="https://user-images.githubusercontent.com/2625526/160613632-208d5ed2-8397-4acc-bae6-89bdd78b321d.png">

and then hitting the refresh button, this goes back to the Find tab:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/2625526/160613800-969a5c0c-9ed0-4d22-952b-508b5b9a2703.png">

Could that stay on the "Replace" when hitting refresh ?

**Comment by jgutman** [comment]
@DavisVaughan As a super-user and requester of this feature, do you have thoughts on this? 

I found the previous situation, where even without the refresh button, if you had previously run a Find in Files search, and you ran a new search from Cmd + Shift + F,  the new search would reopen with the Replace toolbar visible (even though replace mode was partially disabled), to be quite confusing and buggy, but I'm open to more feedback

**Comment by DavisVaughan** [comment]
I think switching back to the Find pane is probably fine? I don't think either choice would bother me much.

The Replace pane does an "all or nothing" replace, right? So if I actually use the Replace pane to perform a replacement, then it doesn't really make sense to do a refresh (because it changed everything to the replacement already).

I think I will use this refresh feature more from the Find tab. I'll do a search, manually update a few cases where it found results (i.e. probably not a simple replace), run a refresh, and continue along

**Comment by jgutman** [comment]
Yes -- at this moment, Find in Files does not have a replace one option -- it's only replace all

**Comment by DavisVaughan** [comment]
If it has a "replace one" option then I _feel_ like staying on the Replace tab and possibly clearing the Replace With box when you hit Refresh seems right

**Comment by jgutman** [comment]
We don't have that, nor do I think we have an issue currently tracking a replace one option, but feel free to open one if you think it could be helpful

**Comment by romainfrancois** [comment]
verified that the refresh button works on build 

```
RStudio 2022.06.0-daily+343 "Spotted Wakerobin" Daily (67bce36c3d3293080e9f1a174749111da4f58fe6, 2022-04-29) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```

The same query runs again and:  
 - find files that previously did not match and now do
 - no longer find files that previously match and now don't. 

Leaving open so that it can be tested on other OS if needed.
