### ISSUE TITLE
F11 Fullscreen Mode Windows

### ISSUE THREAD

**Issue by Pf4rR3R** [rstudio/rstudio#3243]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.456
    OS Version      : Windows 10 Education 1803
    R Version       : 3.4.2

I want to suggest a Fullscreen Mode for the Windows 10 (and older versions) Operating System, similar to what is available for MacOS. What I mean by this is that not the Panes within the RStudio Window get maximized, but the RStudio Window itself gets maximized, not showing the Task- and Menubar. This feature is frequently available in other Programs for Windows via the F11 Shortcut. This feature would maximize the usage of screen estate and allow for deeper immersion into RStudio.

**Comment by ronblum** [comment]
@Pf4rR3R Thank you for the practical suggestion! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by pietrodito** [comment]
It will be appreciated !

**Comment by 392781** [comment]
Any work done on this?  

At the very least is it possible to implement menu bar hiding?

**Comment by kevinushey** [comment]
This should, in theory, not be too challenging to implement -- we can make use of the Qt showFullScreen helper: https://doc.qt.io/qt-5/qwindow.html#showFullScreen

The auxiliary challenges are making sure users know how to exit full screen, and ensuring that window state is properly saved / restored when RStudio is closed and re-opened as well.

**Comment by rotemgb** [comment]
I might able to help. Can anyone tell me where can I find the right repo to update?

**Comment by mirh** [comment]
Isn't this a cakewalk to implement, even more now with electron?

**Comment by gtritchie** [comment]
> Isn't this a cakewalk to implement, even more now with electron?

Yes. There are some quirks (see the pull request https://github.com/rstudio/rstudio/pull/14216) but this will be in the next release (2024.04) along with already-added ability to autohide main menu (https://github.com/rstudio/rstudio/pull/13978).

**Comment by gtritchie** [comment]
> I further suggest, very kindly, that this feature also be available for separate windows. For example, when you detach the source editor from the main window. Thanks for the wonderful software.

Opened new issue to track this: https://github.com/rstudio/rstudio/issues/14218

**Comment by jonvanausdeln** [comment]
Verified on [2024.04.0-daily+456](https://dailies.rstudio.com/version/2024.04.0-daily+456)
Windows 11 & Ubuntu 22

Command palette and `F11` both work as expected, as does remapping a custom keyboard shortcut.  The notes in the PR are also valid in regards to autohiding the menu bar.
