### ISSUE TITLE
Occasional double title bar on MacOS desktop

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3244]
We don't have a repro steps, but @jjallaire has seen this a couple of times on the daily builds (~1.2.870).

![image](https://user-images.githubusercontent.com/470418/43479997-cee0f6c4-94b6-11e8-8420-b8f6009d9428.png)

![image](https://user-images.githubusercontent.com/470418/43480005-d3d76f64-94b6-11e8-994b-1a7922b33513.png)

**Comment by kevinushey** [comment]
I can reproduce by opening the latest daily build and clicking <kbd>View -> Show Tab Bar</kbd>.

Not sure where that entry is coming from -- maybe some default option inserted by Qt / the OS?

**Comment by kevinushey** [comment]
Another day, another Qt bug: https://bugreports.qt.io/browse/QTBUG-61707
