### ISSUE TITLE
Unable to add themes.

### ISSUE THREAD

**Issue by Vivek-Prakash-US** [rstudio/rstudio#3247]
### System details

    RStudio Edition : Desktop (install from zip)
    RStudio Version : 1.2.872
    OS Version      : windows 7 enterprise
    R Version       : 3.5.1

### Steps to reproduce the problem
I was trying to test out the Add Editor theme option. I download the amy.tmheme from here:
https://github.com/JetBrains/colorSchemeTool/tree/master/tmThemes
### Describe the problem in detail
I'll click the Add... button for the Options -> Appearance menu and then get a dialog box titled 'Failed to Add Theme'.

Text inside of box:
"Unable to add the theme 'C:/Users/myusername/Downloads/Amy.thTheme'. The following error occurred: cannot open the connection
Also, warnings: cannot open file 'C:/Users/myusername/programs/rstudio/resources/themes/compile-themes.R': No such file of directory"

**Comment by ronblum** [comment]
@Vivek-Prakash-US Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

Reproduced on MacOS 10.14 (Mojave).

**Comment by jmcphers** [comment]
@MariaSemple can you take a look?

**Comment by Ademord** [comment]
I just installed Rstudio on MacOS and I dont have the "new themes" nor the options to add themes. Help?

**Comment by ronblum** [comment]
@Ademord Just to confirm: what build are you using, and do you mean that you're missing the "Add" button at the bottom? Anything else missing or different?
<img width="579" alt="themes_windows7" src="https://user-images.githubusercontent.com/31009952/53101658-352a2900-34f8-11e9-8d7a-8752c1c3969e.png">

(I added the Yule theme at the bottom.)

**Comment by Ademord** [comment]
@ronblum it looks like this; and all the "new themes" mentioned [here](https://support.rstudio.com/hc/en-us/articles/115011846747-Using-RStudio-Themes#modern-theme), i dont have them.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/4501464/53250969-d6ada800-36bb-11e9-8677-54e33434bdcf.png">

**Comment by shmuhammad2004** [comment]
@ronblum I have the same problem. I install it yesterday on mac and cannot the add

**Comment by BastiHz** [comment]
@Ademord @shmuhammad2004  The ability to add new themes is a feature of RStudio version 1.2, which is already available as a preview from [here](https://www.rstudio.com/products/rstudio/download/preview).
