### ISSUE TITLE
Feature Request: Open Directory

### ISSUE THREAD

**Issue by hack-r** [rstudio/rstudio#3248]
### System details

    RStudio Edition : Desktop
    RStudio Version : All
    OS Version      : All
    R Version       : All

### Feature Request

It would be very useful to be able to open all files (and/or all by extension, e.g. R) in a directory. I use this feature in GitHub's Atom programming text editor often. It not only saves time when opening many files, it can also be used for powerful time savings with Find in Files.

I think that usefulness stands on its own, but it's an even bigger time saver if you consider many common issues that lead to .Rproj projects not properly reopening .R files in RStudio.

**Comment by kevinushey** [comment]
You can accomplish something similar programmatically with e.g.

```
files <- list.files("R", full.names = TRUE)
file.edit(files)
```

and so in theory could build an [RStudio Addin](https://rstudio.github.io/rstudioaddins/) to handle this. Would that be sufficient for you?

**Comment by hack-r** [comment]
I think so, yes!

⁣Sent from Blue ​
