### ISSUE TITLE
Python plots crash terminal

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#3250]
### System details

    RStudio Edition : Desktop and Server 
    RStudio Version : 1.1.456 
    OS Version      :  Ubuntu 16.04 and Debian (rocker/rstudio)
    R Version       :  3.5.1

### Steps to reproduce the problem

In RStudio server (apologies it's a giant 8 GB image thanks to the Python stack):

```bash
docker run -d -p 8787:8787 -v $(pwd):/home/rstudio/data robinlovelace/tds  
docker ps

# navigate to http://localhost:8787
# log-in with username and password rstudio
# then press Alt+Shift+T to go into the shell and enter the following
# can also be run from .sh script from the command line:
conda activate base
python

# now in python shell
import osmnx as ox
ox.config(use_cache=True)
G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
ox.plot_graph(ox.project_graph(G))
```

Ouput including crash:

```
rstudio@204a4173089c:~/data$ conda activate base
(base) rstudio@204a4173089c:~/data$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import osmnx as ox
ox.config(use_cache=True)
>>> ox.config(use_cache=True)
>>> G = ox.graph_from_place('Piedmont, CA, USA', network_type='drive')
>>> ox.plot_graph(ox.project_graph(G))
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-rstudio'
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
(base) rstudio@204a4173089c:~/data$
```

In RStudio Desktop on my Ubuntu laptop, building on previous reprex (assumes you have osmnx installed locally):

```
>>> ox.plot_graph(ox.project_graph(G))
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
[1]    17337 abort (core dumped)  python
```

### Describe the problem in detail

The Python shell crashes when plotting. 

You can get around this by running the following lines before plotting (see https://github.com/gboeing/osmnx/issues/194 ):

```python
import matplotlib as mpl
mpl.use('Agg')
```

### Describe the behavior you expected

The python shell would not crash, as in other terminals.

**Comment by kevinushey** [comment]
Thanks for the bug report! Perhaps `reticulate` needs to take over the matplotlib backend for plotting.

Note to self:

https://matplotlib.org/api/index_backend_api.html

**Comment by Robinlovelace** [comment]
Great to hear of the potential solution, sounds like doing it via a matlib plot backend may help if there's no simpler (short term) fix to stop the crash, even if no plot were produced that would be a major improvement.

**Comment by kevinushey** [comment]
We've now incorporated the patch you suggested into `reticulate`, so this issue should no longer show up in the future. Thanks for reporting! Please let us know if you encounter any more issues.

**Comment by ronblum** [comment]
@Robinlovelace How does the patch seem—have you found that the problem is resolved?

**Comment by Robinlovelace** [comment]
I've not tried it. I used it on rocker - will the fix be on the latest version of RStudio there?

**Comment by ronblum** [comment]
@kevinushey Do you know the answer to this?

**Comment by kevinushey** [comment]
The fix here is independent of RStudio, so as long as the latest development version of `reticulate` is installed all should be well.

**Comment by Robinlovelace** [comment]
Looks good to me. See below what I tried - no crashes. Thanks!

```r
library(reticulate)
packageVersion("reticulate")
reticulate::vers
reticulate::repl_python()
# python3
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
exit
```

![peek 2018-08-26 08-12](https://user-images.githubusercontent.com/1825120/44630441-adeb6680-a955-11e8-978a-62ddf94eb5c7.gif)

**Comment by Robinlovelace** [comment]
That test was with:
``` r
packageVersion("reticulate")
#> [1] '1.10'
```

Created on 2018-08-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
