### ISSUE TITLE
RStudio crashes when using leaflet `addLayersControl(baseGroups = ...))` and clicking on a radio button

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#3251]
When using the `baseGroups` option in `addLayerControl()`, radio buttons appear to select a layer. Inside RStudio Viewer, clicking on the labels of the radio buttons is fine, but clicking on the actual circles of the radio buttons crashes RStudio. This does not happen in a browser or with `overlayGroups` (checkboxes vs radio).

Windows 7
latest stable version of leaflet (2.0.1), htmlwidgets (1.2), and rstudio (1.1.456)

Code to reproduce (taken from https://rstudio.github.io/leaflet/showhide.html and modified to be as minimal as possible):

```r
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addCircles(data = quakes, ~long, ~lat, group = "Quakes") %>%
  addPolygons(data = quakes[chull(quakes$long, quakes$lat),], lng = ~long, lat = ~lat,
              group = "Outline") %>%
  addLayersControl(
    baseGroups = c("Quakes", "Outline")
  )
```

GIF of crash:

![leafletbug](https://user-images.githubusercontent.com/952340/43584831-2e31a450-966c-11e8-9885-770b078c3d65.gif)

[cross posted on [leaflet repo](https://github.com/rstudio/leaflet/issues/573), please close one and leave it open on the relevant repo]

**Comment by schloerke** [comment]
Tested in a windows 7 vm. Crashes with rstudio v1.1.456.  Works with rstudio daily v1.2.x

Works as expected on mac v1.1.456. 

I do not believe this is a https error that leaflet was experience earlier. https calls only caused a console error, not an application crash.

**Comment by daattali** [comment]
With the daily build it does not crash.

**Comment by kevinushey** [comment]
If it works in the dailies then I think there is no action to be taken here (we're working hard to prepare a v1.2 release by the end of this year)
