### ISSUE TITLE
Extend Files 'Copy To...'

### ISSUE THREAD

**Issue by hsselman** [rstudio/rstudio#3252]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453 
    OS Version      : MacOS High Sierra 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Click the checkbox for more than one file in `Files` pane.
2. Use `More` to use `Copy To...`.
3. Get error `Multiple Items Selected`: 'Please select a single file or folder to copy'.

### Describe the problem in detail

I want to be able to copy a series of files or folders to a new location using RStudio. I really like RStudio, but found this behaviour rather annoying.

### Describe the behaviour you expected

In this scenario, I don't want to be able to change the individual names of these files or folders. It is enough to be able to place a copy of the selected files in another folder. It is too bad that this is not possible right now. Hopefully this is something for a future version or RStudio. Thanks in advance!

**Comment by ronblum** [comment]
@hsselman Thank you for the suggestion—we'll take a look at it as we continue development of RStudio. And I'm glad to hear you like RStudio!
