### ISSUE TITLE
Switching conda environments with rstudio[server]?

### ISSUE THREAD

**Issue by abalter** [rstudio/rstudio#3255]
Suppose I have conda environments such as _renv1_ and _renv2_. I have set rstuido to look for `R` in `/home/me/conda/bin`. Now, how do tell rstudio to use one of my conda environments?

**Comment by jmcphers** [comment]
This forum is for RStudio bugs; if you have questions, use the RStudio community forum.

https://community.rstudio.com/

I think the answer to your question is probably here:

https://rstudio.github.io/reticulate/articles/versions.html
