### ISSUE TITLE
Tomorrow Night Blue broken in 1.2.872

### ISSUE THREAD

**Issue by skeydan** [rstudio/rstudio#3258]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.872
    OS Version      :  Fedora 28
    R Version       : 3.5

### Describe the problem in detail

Help pane text colors are broken. See screenshot.

![screenshot from 2018-08-03 18-15-35](https://user-images.githubusercontent.com/469371/43653879-bf716486-9749-11e8-9329-1bb7ce35bc43.png)

**Comment by javierluraschi** [comment]
@skeydan mentioned "1.1.465 is totally fine"

@MariaSemple I think this might be closer to your changes, but do assign this back to me if you feel it's not, happy to take a look as well.

**Comment by MariaSemple** [comment]
I'm able to reproduce this. @javierluraschi I can look into it for now, it definitely wasn't like this before so it was probably my changes.

**Comment by ronblum** [comment]
Verified on Desktop and Server.
