### ISSUE TITLE
Error raised when saving valid Rmd files that include SQL chunk with connection option

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3259]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.453 and 1.2.872
    OS Version      : MacOS and Ubuntu
    R Version       : 3.4.4 and 3.5.1

### Steps to reproduce the problem
1. Create a new R Markdown file with the following code:
````
---
title: "Simple SQL Sample"
output: html_notebook
---

```{r setup}
library(odbc)
con <- dbConnect(odbc(), dsn = "MYDSN")
```

```{sql connection = con}
SELECT 1
```
````
2. Save the file.
3. Run the `r setup` chunk.
4. Save the file.
5. Rename the two occurrences of `con` to `diffcon`.
6. Save the file.
7. Knit the file
8. Close the file
9. Open the file
10. Knit the file

### Describe the problem in detail

Two errors appear when the file is saved the first time (step 2), the connection object renamed (step 6), and the file knitted (step 7).

1) An error message at the top of the Editor pane that says 
> Error creating notebook: object 'con' not found. See line 11.

(with "diffcon" instead of "con" the second time.)
<img width="352" alt="error_con" src="https://user-images.githubusercontent.com/31009952/43658510-19e8dcdc-9727-11e8-9fee-540047aaeca9.png">

2. An error message in the console that says
> Quitting from lines 12-13 (my_little_file.Rmd) 

### Describe the behavior you expected

The SQL chunk is correctly defined and the file will knit correctly, but the error message suggests that there's a bug in the code; this is especially confusing when the error pops up even though the knitting is successful. It looks like things are getting tripped up because the connection object doesn't exist yet before it's run. Once the chunk that defines it has run—creating the object—the file saves with no problem. But if the connection object is cleared, or in this case the name is changed, the error on saving returns. 

Three possible alternatives:
1. No error occurs.
2. The message is downgraded to a diagnostic/warning message.
3. Check whether or not the connection object is defined in a previous chunk and only raise a message if it's not.

Note that this isn't a problem if the `connection` option isn't specified because it uses a default. That is, if the setup chunk includes `knitr::opts_chunk$set(connection = "con")`, then the SQL chunk can begin with  ```` ```{sql}``` ````, making the symptom go away—but only for any chunk that uses the default.

[See also Support ticket 29101.]

**Comment by ronblum** [comment]
This also doesn't appear to be an issue if the connection name is in quotes.  That is,

````
```{sql connection = "con"}
SELECT 1
```
````

Also, the issue seems limited to notebook. Changing to knitting to an HTML document
```
output: html_document
```
works fine.

**Comment by kevinushey** [comment]
I think this should be fixed in the latest dailies -- @ronblum let me know if you're still seeing this issue.
