### ISSUE TITLE
R session crashes when its subprocesses are killed

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/rstudio#3261]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.441
    OS Version      : macOS  10.12.6 (16G1510
    R Version       : 3.5.0

### Steps to reproduce the problem

```
  p <- NULL
  px <- processx:::get_tool("px")
  for (i in 1:100) {
   ps:::with_process_cleanup({
     p <- lapply(1:3, function(x) {
       processx::process$new(px, c("sleep", "10"))
     })
     testthat::expect_equal(length(p), 3)
     lapply(p, function(pp) testthat::expect_true(pp$is_alive()))
    })
  }
```

### Describe the problem in detail

R session crashes when its child processes are killed.

### Describe the behavior you expected

I am not sure if this can be considered as a bug, but maybe RStudio could handle this more gracefully. 

The motivation for cleaning up child processes is this: https://github.com/r-lib/ps/pull/35
Most often we do this in `R  CMD check`, which runs the tests in a subprocess, so everything is fine.

**Comment by kevinushey** [comment]
Can you please provide a more minimal example? Other similar examples work fine:

```R
repeat {
    ps:::with_process_cleanup({
        processx::process$new("sleep", "10")
    })
}
```

so there must be something more subtle going on. (Note that the bug in your example doesn't reproduce when I attach a debugger)

**Comment by kevinushey** [comment]
This doesn't reproduce:

```R
px <- processx:::get_tool("px")
repeat {
    ps:::with_process_cleanup({
        processx::process$new(px, c("sleep", "10"))
    })
}
```

But this does:

```R
px <- processx:::get_tool("px")

repeat {
    ps:::with_process_cleanup({
        lapply(1:3, function(i) {
            processx::process$new(px, c("sleep", "10"))
        })
    })
}
```

so there must be something more subtle going on (timing related?)

**Comment by gaborcsardi** [comment]
Yeah, for me the second one does not reproduce, either. I don't have a better example. The ps test suite (the test cases  that  are currently  in `skip_in_rstudio()`) crashes almost every time. But that's  not simpler of course.

I printed out the names of the child processes that are being killed, and there seem to be no RStudio child processes among them, so maybe the reason for the crash is sg else.

**Comment by kevinushey** [comment]
Here's the stack trace I get from a coredump:

```R
(lldb) bt
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x000000010dd24cd4 libR.dylib`R_ExternalPtrAddr(s=0x0000000000000000) at memory.c:3344 [opt]
    frame #1: 0x0000000110709c47 processx.so`processx__sigchld_callback + 167
    frame #2: 0x00007fff63ef1f5a libsystem_platform.dylib`_sigtramp + 26
    frame #3: 0x00007fff63c33237 libsystem_c.dylib`strlen + 23
    frame #4: 0x000000010dda59f3 libR.dylib`R_subset3_dflt(x=0x00007facd5bc3c88, input=<unavailable>, call=0x00007facd08040e0) at subset.c:1229 [opt]
< ... >
```

Does that ring any bells?

**Comment by gaborcsardi** [comment]
Maybe this is a processx issue then. Thanks, I'll take a look.
