### ISSUE TITLE
Republishing R Markdown output from editor to RPubs gives blank result

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3262]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456 (also repro with 1.2.874)
    OS Version      : macOS 10.13.6
    R Version       : 3.4.3

### Steps to reproduce the problem
- Start a new project
- Create an R Markdown file and save it
- Knit to HTML
- In the viewer pane or window, click Publish button and publish to RPubs; see it on the site
- In the editor with the .Rmd file, click the Publish button
- Get the "This document has already been published on RPubs" dialog
- Click "Update Existing"

### Describe the problem in detail
- The document on RPubs is now blank

### Describe the behavior you expected
- The document on RPubs should not be blank, and should be the same as before since we didn't modify the .Rmd source file or re-knit it.
- NOTE: if you click republish in the viewer pane or preview window, it works correctly; it is only happening with the editor publish button

**Comment by ronblum** [comment]
Verified on MacOS 10.14 Mojave and Ubuntu 18.04.
