### ISSUE TITLE
Feature Request: To include an Uninstall Packages option in the Tools menu in RStudio IDE

### ISSUE THREAD

**Issue by duttashi** [rstudio/rstudio#3264]
Dear Team,
Good day.
I have written a customized script to uninstall packages and their related dependencies.  I have to execute this script each time, I need to uninstall a package. So I was thinking, unlike the `Install Packages` option in the `Tools` menu, it will be good to have an `Uninstall Packages` option too in `RStudio IDE`?

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version      :  Windows 7 Home Premium 64 bit
    R Version       : 3.5.0

Thank you

**Comment by ronblum** [comment]
@duttashi Thank you for the suggestion! We'll review and consider it as we work on future releases of RStudio.

**Comment by ronblum** [comment]
@duttashi Just to clarify, you're specifically looking for an uninstall package option that will not only remove the package, but its dependencies as well? Because uninstalling packages is available by click on the "X" to the right of the package names in the "Packages" pane.

**Comment by duttashi** [comment]
@ronblum Thank you for the response.  Yes, its correct that I'm specifically looking for an uninstall package option that should remove the package as well as the related dependencies too. However, it should be noted, its possible for some dependencies to be affiliated to other packages. Therefore, it will be wise if such affiliated dependencies are shown in a summary form to the user, and is cautioned not to remove those affiliated dependencies.

Example: Suppose package `X` has dependencies `a`, `b`, `c`, `d`. Suppose package `Y` is dependent on `c`,  `d`. I want to remove package `X`.  The system should prompt me something like, `Caution: Package Y is dependent on c, d. Removing them may cause package Y to behave unexpectedly. Do you want to remove the other dependencies a,b or all. Press 1 for only a,b. Press 2 for removing package Y and all dependencies.`  

If the user can see a summary message like shown in the example above, it will help in following;
- the user will know the dependencies of package `X` are either standalone or they are required by other packages like `Y`.
- If accidentally the user removes the affiliated dependencies, it can reinstall them easily by simply looking at the previous summary statement.

**Comment by ronblum** [comment]
@duttashi Great, thank you for the descriptive suggestion! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by duttashi** [comment]
@ronblum you are welcome and thank you to the RStudio team members for all their hard work :clap:
