### ISSUE TITLE
Feature request: improved syntax highlighting for interpolated strings

### ISSUE THREAD

**Issue by edavidaja** [rstudio/rstudio#3268]
This is fairly minor, but it would be nice to have some visual differentiation between the literals and expressions in sprintf/glue/str_interp, etc.

### System details

    RStudio Edition : 
    RStudio Version : 1.1.447
    OS Version      : Windows 7 x64 (build 7601) Service Pack 1
    R Version       :  3.5.0 (2018-04-23)

**Comment by ronblum** [comment]
@edavidaja Can you give an example of what you're looking for? I'm trying to get an idea by looking at some examples of `sprintf` at the bottom of https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/sprintf and comparing them to an RStudio theme—it looks similar to Crimson Editor. I'm trying to tie it in to your suggestion. Thanks!

**Comment by edavidaja** [comment]
[Current behavior](https://repl.it/@Enyinnaya_David/RealisticDarkCables):
![image](https://user-images.githubusercontent.com/12927842/43782828-31187304-9a2e-11e8-9038-a7365610774b.png)

Desired behavior ([Javascript example](https://repl.it/@Enyinnaya_David/DungeonsAndDragons))
![image](https://user-images.githubusercontent.com/12927842/43782926-6f31afc0-9a2e-11e8-940b-92dc8eb250b6.png)

**Comment by ronblum** [comment]
@edavidaja Great, thank you! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by jmcphers** [comment]
This is effectively a mini language-inside-a-language mode, and is tracked in https://github.com/rstudio/rstudio/issues/2232.
