### ISSUE TITLE
Cannot preview PDF output under a subdirectory (e.g., PDF generated with bookdown)

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#3270]
This issue may be similar to #3089.

### System details

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6, RStudio 1.2.877
```

### Steps to reproduce the problem

Minimal repro: [bookdown-minimal.zip](https://github.com/rstudio/rstudio/files/2263488/bookdown-minimal.zip)

### Describe the problem in detail

Click Build Book. The PDF output cannot be previewed with either the RStudio Viewer (PDF.js) or the System Viewer (no-op):

![image](https://user-images.githubusercontent.com/163582/43731493-4c3ae6e0-9974-11e8-958e-480f3cbf25e8.png)

![image](https://user-images.githubusercontent.com/163582/43731398-fd4e6318-9973-11e8-8af8-43cf5c300218.png)

**Comment by ronblum** [comment]
This is a regression, as it works in 1.1.456.

Note that this works in Window 10's Sumatra and Red Hat 7.5's Evince viewers.

**Comment by kevinushey** [comment]
@jjallaire I think you were working on this most recently -- do you have any extra insight?

**Comment by ronblum** [comment]
Confirmed in RStudio Desktop 1.2.1287.
