### ISSUE TITLE
New SQL files should conditionally show the SQL results tab

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#3273]
_This is an issue discussed with @kevinushey that may or may not be worth pursuing. He mentioned it would likely be incorporated after the 1.2 release, which is fine._

Running RStudio daily 1.2.872 on Windows 7 Enterprise.

This issue involves RStudio always showing a SQL Results tab after every query in a SQL file. If the SQL script is used for side effects, I propose that it should not open a SQL results tab. Below is an example.

I am updating a database process that runs through R and want to work with cheap copies of SQL tables that I can throw away once I've gotten the new process right.

I have 1 SQL file that runs:

```sql
-- !preview conn=con

SELECT * INTO temp_R3000
FROM R3000;

SELECT * INTO temp_R3000_Fin
FROM R3000_Fin;

SELECT * INTO temp_R3000_NonFin
FROM R3000_NonFin;
```

And another that I can run to do:

```sql
-- !preview conn=con

DROP TABLE temp_R3000;
DROP TABLE temp_R3000_Fin;
DROP TABLE temp_R3000_NonFin;
```

Works great!

__I'm not too keen on it always showing a SQL Results menu right after. If there is no data returned from the statements, and I just use them for their side effects, do I really need to have the focus taken away from the Console just for it to tell me there is no data available?__

**Comment by ronblum** [comment]
@DavisVaughan Thanks for filing this!

What would you look for if it were a SELECT statement, not a SELECT INTO, that returns no records? E.g.:

```sql
-- !preview conn=con

SELECT * FROM R3000
WHERE 1 = 0;
```

No records get returned, but in this case, I would argue for the SQL Results tab because it is meaningful.

**Comment by DavisVaughan** [comment]
Great (difficult) question. With `DBI`, If I do:

```r
DBI::dbGetQuery(con, "SELECT * INTO ##temp_tbl FROM real_table")
```

A data frame with 0 rows and 0 cols is returned. But for:

```r
DBI::dbGetQuery(con, "SELECT * FROM ##temp_tbl WHERE 1 = 0")
```

A data frame with 0 rows and N columns is returned (with column names and everything).

Could you use that?

Also, I'm on SQL Server
