### ISSUE TITLE
Cannot start RStudio - Rgraphapp.dll is missing

### ISSUE THREAD

**Issue by NathenHarp** [rstudio/rstudio#3275]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Windows 7 64
    R Version       : 3.5.0

### Steps to reproduce the problem
Have reinstalled RStudio and R; confirmed Rgraphapp.dll is installed in the correct folders; renamed C:\Users\nharp\AppData\Local\RStudio-Desktop
 

### Describe the problem in detail
I changed R versions in RStudio/Tools/Global Options...selected one of the previous versions.  Now RStudio throws an error referencing "Rgraphapp.dll is missing" and to reinstall RStudio.

I cannot run a diagnostics report because RStudio cannot reinitialize with R.
![untitled3](https://user-images.githubusercontent.com/41922530/43781318-9f30a9b4-9a2a-11e8-8979-f013ab4a838c.jpg)

### Describe the behavior you expected
RStudio should start up correctly.

**Comment by NathenHarp** [comment]
I resolved the issue to change back to default R version by using Crl() and opening rstudio.exe

RStudio now launches correctly to previous state.

**Comment by kevinushey** [comment]
Where did you install R from? My best guess is that you somehow got a broken / incomplete R installation missing some of the required .DLLs.
