### ISSUE TITLE
"Unexpected exception: Mutex creation failed"

### ISSUE THREAD

**Issue by greenisagoodcolor** [rstudio/rstudio#3280]
Hey, I upgraded to latest bin version (1.1.456-1) and upgraded all my packages using R-studio -> tools -> check for package updates. I can only get a few commands in (e.g. loading libraries, read.csv) before the R session aborts with the error:

"The R session had a fatal error. Unexpected exception: Mutex creation failed"

It seems to not be correlated to any particular command and can occur with or without user input to the command line. My rstudio IDE is completely unusable. Does anyone have any thoughts on why this is occurring? 

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : x86_64-pc-linux-gnu (64-bit) running under archlinux
    R Version       :  3.5.1

# session info
sessionInfo() R version 3.5.1 (2018-07-02) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Arch Linux

Matrix products: default BLAS: /usr/lib/libblas.so.3.8.0 LAPACK: /usr/lib/liblapack.so.3.8.0

locale: [1] LC_CTYPE=en_US.UTF-8 
[2] LC_NUMERIC=C 
[3] LC_TIME=en_US.UTF-8 
[4] LC_COLLATE=en_US.UTF-8 
[5] LC_MONETARY=en_US.UTF-8 
[6] LC_MESSAGES=en_US.UTF-8 
[7] LC_PAPER=en_US.UTF-8 
[8] LC_NAME=C 
[9] LC_ADDRESS=C 
[10] LC_TELEPHONE=C 
[11] LC_MEASUREMENT=en_US.UTF-8 [12] LC_IDENTIFICATION=C

attached base packages: [1] stats graphics grDevices utils datasets [6] methods base

loaded via a namespace (and not attached): [1] compiler_3.5.1 tools_3.5.1 yaml_2.2.0

**Comment by kevinushey** [comment]
Any chance you can get a stack trace?

**Comment by MalditoBarbudo** [comment]
Hi! Sorry for jumping here. I found myself the same problem after updating rstudio, but looking at the aur discussion here https://aur.archlinux.org/packages/rstudio-desktop-bin/?O=0&PP=10
the problem seem related to the `later` r package now solved (https://github.com/r-lib/later/issues/63)
Installing the latest git version of `later` worked for me.
