### ISSUE TITLE
allow customization of Help pane font size

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3282]
Feature request from https://community.rstudio.com/t/how-can-i-increase-the-font-size-in-the-help-tab-in-rstudio-server/12252, but this has been requested in other places in the past as well.

**Comment by hszest** [comment]
Any news about this? 
The first time I used RStudio I tried to find this feature, and years has passed... 
Now I use a 125% zoom on every computer I used just to see the help panel clearly but I'd rather other contents just stay the regular size

**Comment by jjchern** [comment]
Would like to see some update on the issue as well.

For other users who are also unsatisfied with font size in the help panel: one option is to use the Viewer panel to read help documentation. 

Here is a quick hack: get the rd file, turn it into an HTML file, and open it via the Viewer panel. Below are two examples:

```R
library(magrittr)

help("bibentry") %>% 
    utils:::.getHelpFile() %>% 
    tools::Rd2HTML(out = tempfile(fileext = ".html"),
                   stylesheet = "https://pandoc.org/demo/pandoc.css") %>%  
    rstudioapi::viewer()

help("geom_point", "ggplot2") %>% 
    utils:::.getHelpFile() %>% 
    tools::Rd2HTML(out = tempfile(fileext = ".html"),
                   stylesheet = "https://pandoc.org/demo/pandoc.css") %>%  
    rstudioapi::viewer()
```

**Comment by dfalty** [comment]
Verified 1.3.867

**Comment by raffaem** [comment]
I feel the option should be in "Appearance" rather than in General->Advanced, but that is a very minor point

**Comment by AndrewLuyt** [comment]
This option does not seem to affect the font size of vignettes that appear in the help window. e.g.
`vignette("pivot", package="tidyr")`

RStudio 2023.03.1+446 "Cherry Blossom" Release (6e31ffc3ef2a1f81d377eeccab71ddc11cfbd29e, 2023-05-09) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.1+446 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
