### ISSUE TITLE
Git Pane - Cannot stage deletion of directories in UI

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#3284]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.879
    OS Version      : RHEL 7.3

### Steps to reproduce the problem
1. Create a new RStudio project and select "Create a git repository"
2. Create a folder in the project directory
3. Create a script in that folder and save
4. Stage and commit the changes
5. Delete the folder using the Files pane
6. Go to the Git pane and try to select the checkbox to stage the change
7. Observe you cannot select it

![image](https://user-images.githubusercontent.com/15237845/43813870-429cf2bc-9a8d-11e8-89af-e27034a507b7.png)

Notes: 
-I can stage the change from the command line with `git rm <name>` and then commit without issue. 
-I run into a similar issue when deleting just the file. After staging this change, I can't unstage.
-I can't reproduce this on Mac Desktop version.

### Describe the problem in detail
I am unable to stage the deletion of directories with all files in the UI. It only seems to happen in RStudio Server. I am able to reproduce on 1.1 and I even went back to 1.0.136 and I can still reproduce.

**Comment by kevinushey** [comment]
Surprised that this only reproduced in RStudio Server as the Git integration should be identical between desktop + server here. I'll take a look.

**Comment by kevinushey** [comment]
Is there any chance that it works, but it's just very slow? Your example seems to work fine on my Ubuntu 18.04 VM with RSP v1.1.456.

**Comment by kevinushey** [comment]
See also: https://community.rstudio.com/t/version-1-1-456-is-extremely-slow-on-ubuntu-lts-18-04/12072/8

Not sure if it's related, but some users have reported Git slowness with v1.1 (but not in v1.2).

**Comment by dfalty** [comment]
@kevinushey Weird, I can reproduce this on RSP 1.1.456 in my env (RHEL 7.3). It's on an EC2 instance I can give you access to if that helps. It doesn't seem to be related to the slowness reported as it's only isolated to the staging of the deleted folder/files and the rest of the pane works fine (I'm able to keep staging/committing other files). Also, it doesn't matter how long I wait, it never stages that specific change.

**Comment by p0bs** [comment]
Speaking entirely selfishly (!), it is a shame that this has been removed from v1.2, as it is a real pain point for me when using WidgetFrame within a blogdown site on Windows. (I realise that I might be a minority, though!)
