### ISSUE TITLE
Margin column disappearing

### ISSUE THREAD

**Issue by sfr** [rstudio/rstudio#3285]
When the _margin column_ is set to 80, as soon as the file hits 99 lines in length, margin will disappear. When it's below 99 lines it is OK.

But when the  _margin column_ is set to different value than 80, I tried 79, 81, 120, then it is OK.

Also this issue is not present in _Classic_ RStudio theme. Only in _Modern_ or _Sky_. It looks like changing _Editor theme_ doesn't make a difference - I tried few.

### System details
    RStudio Edition: Desktop
    RStudio Version:  1.2.882
    OS Version:  Windows 7 x64
    R Version: 3.5.1, 3.2.5

### Steps to reproduce the problem
1. Set _margin column_ to 80.
2. Set _RStudio theme_ to _Modern_ or _Sky_.
3. open file longer than 98 lines, or alternatively create file with 99 lines

**Comment by kevinushey** [comment]
I'm not able to reproduce on my Windows VM:

<img width="817" alt="screen shot 2018-08-13 at 1 39 47 pm" src="https://user-images.githubusercontent.com/1976582/44056931-9e15cd60-9efe-11e8-8d31-d5cf0d6f0dd4.png">

Can you provide any other details?

**Comment by sfr** [comment]
This is from the 1.2.900 release.
If you notice, the left gutter is wider with 99 rows. Which is one row too early. 

Also this issue doesn't happen when you pull out Editor into the new window. It is really an isolated case when it happens. Only for margin = 80. But I can replicate it any time.

![line98](https://user-images.githubusercontent.com/2040557/44134657-2415853c-a066-11e8-8ac7-340136b978bb.png)
![line99](https://user-images.githubusercontent.com/2040557/44134707-5b646fc6-a066-11e8-90f5-d2ff67a3e0a0.png)

**Comment by ronblum** [comment]
@sfr Does this problem still occur on the latest daily builds? I've tried on multiple environments, but I'm unable to reproduce the issue.
