### ISSUE TITLE
Change split lines on Mac Mojave to ctrl+J

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3286]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.873-1
    OS Version      : MacOS Mojave (10.14)
    R Version       : 3.5.1

### Steps to reproduce the problem

With Mac Desktop:
1. Switch to the Editor pane and type a few words.
2. Place the cursor in the middle of the line.
3. Enter <kbd>ctrl+J</kbd>.
4. Enter <kbd>ctrl+O</kbd>.

### Describe the problem in detail

Neither <kbd>ctrl+J</kbd> nor <kbd>ctrl+O</kbd> split lines.

### Describe the behavior you expected

<kbd>ctrl+J</kbd> should split lines, as it does on Windows Desktop, Linux Desktop, and RStudio Server. Also, the entry for "Split Lines" in the keyboard shortcuts menu says "Ctrl+O", but it should be changed to "Ctrl+J".

<kbd>ctrl+O</kbd> is correctly opening the file.

See also #3076.

**Comment by pkq** [comment]
FWIW, Ctrl-J seems to split lines as expected on desktop version 1.2.883 under MacOS Sierra 10.12.6.

**Comment by ronblum** [comment]
@pkq Interesting. What do you see for the "Split Lines" entry under Tools -> Modify Keyboard Shortcuts?

**Comment by ronblum** [comment]
And there it is in High Sierra 10.13.6. It looks like Mojave 10.14 is not being recognized.

**Comment by jmcphers** [comment]
Ctrl+J once again splits lines on MacOS Catalina.
