### ISSUE TITLE
Notebook preview doesn't preview if first used for a new, unsaved file

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3288]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.882
    OS Version      : Mac 10.14 & Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

Generate an R Notebook file on Desktop and preview it.

First File
1. Shut down and restart RStudio
2. `File` -> `New File` -> `R Notebook`
3. `Preview`
4. Choose a file name, e.g. `my_first_file`
5. `Save`
6. `Preview`

Second File
7. `File` -> `New File` -> `R Notebook`
8. `Preview`
9. Choose a file name, e.g. `my_second_file`
10. `Save`

Restart
11. Shut down and restart RStudio
12. The file `my_second_file.Rmd` should still be open
13. `Preview`

Restart
14. Shut down and restart RStudio
15. `File` -> `New File` -> `R Notebook`
16. `File` -> `Save`
17. Choose a file name, e.g. `my_third_file`
18. `Save`
19. `Preview`

### Describe the problem in detail

If the first time `Preview` is used it's with a new file that has not yet been saved (steps 3–5), the file is generated but the preview isn't shown, whether directed to the Viewer pane or window. All subsequent previews of the same or other files work (steps 6, 8-10, 13), and if the new file is saved before previewing (steps 16–19).

### Describe the behavior you expected

The preview should always appear.

**Comment by VectorPosse** [comment]
This is a problem for me as well, and I can reproduce the problem a lot more simply than the above. If I open a `.Rmd` file for the first time with type `html_notebook`, the Preview button does nothing. Once I've run one or more code chunks, then the `.nb.html` file will be generated and the preview window will open.

This is a problem on both desktop versions and RStudio Server.

**Comment by mvuko** [comment]
I have the same problem. After some time (and saving the file multiple times), the Preview just stops responding.
The only solution I found so far is to open a new R Notebook file and copy paste the whole script.

**Comment by kevinushey** [comment]
I cannot reproduce any of the reported issues with a recent daily build (v1.3.581). (See [daily builds](https://dailies.rstudio.com) for daily test builds of RStudio)

**Comment by VectorPosse** [comment]
If it helps, it happens most often (but not consistently) in RStudio Server.

**Comment by rama100** [comment]
> The only solution I found so far is to open a new R Notebook file and copy-paste the whole script.

I have found that modifying the Notebook even slightly (e.g adding a **single** space) and saving it triggers the creation of the nb.html file.

**Comment by daniellga** [comment]
I have the same problem.

**Comment by jctourtellotte** [comment]
I have been having the same issue under the same circumstances.
