### ISSUE TITLE
Double-clicking on a word in Source pane doesn't solidly highlight all occurrences in some themes

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3292]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.1.456 & 1.2.883
    OS Version      : 10.14 (Mojave), Ubuntu 16.04
    R Version       : 3.4.4 & 3.5.1

### Steps to reproduce the problem

1. In the Source pane, type the same word multiple times.
2. Double-click on one of the words.

### Describe the problem in detail

Double-clicking on a word highlights it, but it only highlights its other occurrences in some themes. In other themes, there's just a thin square rectangle around them, which is very hard to see in some cases.

### Describe the behavior you expected

Double-clicking should highlight all occurrences of a word as a solid rectangle.

This is not a regression, as it occurs in 1.1.456 as well.

This is an offshoot of #2264. Here are conversation snippets from there (I hope I included everything relevant):

-----

@ColeWunderlich said:
In addition to this, word highlighting does not work for certain themes even in source.  Themes include material and solarized dark.

This is due to the color of `.ace_marker-layer .ace_selected-word` being set to the same color as the background (Eg. for material `#263238`)

-----

Then @kevinushey said:
@ColeWunderlich word highlight looks fine for me with those themes, e.g. from Solarized Dark:

<img width="119" alt="screen shot 2018-03-23 at 1 36 52 pm" src="https://user-images.githubusercontent.com/1976582/37852293-4e2ac6fe-2e9f-11e8-855f-ac97f7cd51d6.png">

Is your concern that the highlight is not distinct enough from the background color, or are you truly not seeing any word highlighting in your case?

-----

To which @ColeWunderlich replied:
Sorry for the late reply.  Word highlighting was not working for me at all for certain themes.  After making changing the colors for  `.ace_selected-word`to be different from that of `.ace_marker-layer `I was able to get word highlighting.  Might be worth checking the included themes to make sure they don't have this problem, as I believe several of them do.

To me indicates its a problem with the theme configuration and not ace itself.

Also, don't know if it matters, but I am on Mac.

-----

And quickly followed up with:
Also, @kevinushey the problem is not highlighting, but the 'double click to highlight all instances of a word' feature.

Example from solarized dark (not working)
![image](https://user-images.githubusercontent.com/7573337/39225977-87fd8f3c-481d-11e8-8329-011fb9f9f47f.png)

Expected behaviour (ambiance) 
![image](https://user-images.githubusercontent.com/7573337/39226029-dfc2b0a8-481d-11e8-8ad0-81acadb3ce19.png)

-----

@kevinushey then noted:

FWIW the highlight is actually there, it's just way too faint:

![screen shot 2018-08-08 at 1 10 09 pm](https://user-images.githubusercontent.com/1976582/43861686-703ace68-9b0c-11e8-81d3-ffdbcad56f1f.png)

so this is more an issue with the highlight rules for Solarized Dark specifically.

**Comment by kevinushey** [comment]
Related: https://github.com/rstudio/rstudio/issues/2702

**Comment by markschat** [comment]
For posterity:
Word highlighting can be achieved by editing/ adding this lines in your theme-file (e.g. my_theme.rstheme):
```
.ace_marker-layer .ace_selected-word {
  background: #3D4350;
  border: 1px solid #3D4350;
}
```
This adds a background color and border to the highlighted words:

![image](https://user-images.githubusercontent.com/43857618/159703956-5eb10f6e-6b8a-47dd-a75c-9a977baaffbe.png)
