### ISSUE TITLE
Rstudio malfunction 

### ISSUE THREAD

**Issue by ThePhenomenal01** [rstudio/rstudio#3294]
I have issues with my Rstudio loading packages, a problem that just showed up just of recent though I'm a new R user. There has always been an error message loading a package on Rstudio after installation. For example, I just installed tidyverse afresh now and I tried loading it, the message from R was error: package or namespace load failed for tidyverse... Same thing applicable to some other packages I've been trying to work with. I really need help, please.

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
