### ISSUE TITLE
data viewer no longer inherits dark themes

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3295]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.888
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Try opening the Data Viewer with e.g.

```R
data <- as.data.frame(matrix(1:16, nrow = 4))
View(data)
```

### Describe the problem in detail

The data viewer elements are not styled.

### Describe the behavior you expected

The data viewer should adapt to dark themes.

Compare:

### RStudio v1.1

<img width="304" alt="screen shot 2018-08-08 at 4 35 01 pm" src="https://user-images.githubusercontent.com/1976582/43869796-41e6f75e-9b29-11e8-814a-817b7100a42f.png">

### RStudio v1.2

<img width="303" alt="screen shot 2018-08-08 at 4 34 07 pm" src="https://user-images.githubusercontent.com/1976582/43869803-49f657aa-9b29-11e8-9549-a03aaa1dc3af.png">

(for reference, I'm using Tomorrow Night Bright as the current theme)

### Notes

There is a JavaScript error indicating that we were unable to retrieve the associated `.rstheme` file in the gridviewer:

<img width="1012" alt="screen shot 2018-08-08 at 4 38 01 pm" src="https://user-images.githubusercontent.com/1976582/43869846-81e39c90-9b29-11e8-9b52-12ba0eddfd43.png">

**Comment by ronblum** [comment]
Verified on Desktop with MacOS 10.14 Mojave and Server with Ubuntu 18.04 with several dark themes.

**Comment by dfalty** [comment]
Looks like I'm getting this again on 1.2.1326-1. 
![image](https://user-images.githubusercontent.com/15237845/54296702-650e9e80-4583-11e9-96ef-18edc62bc801.png)
![image](https://user-images.githubusercontent.com/15237845/54296741-73f55100-4583-11e9-9b58-9045b28d7ee3.png)

**Comment by ronblum** [comment]
Confirmed fixed in 1.2.1335 on MacOS 10.14 (Desktop), Windows 10 (Desktop), and Red Hat 7.6 (Server) using Firefox on MacOS.
