### ISSUE TITLE
Upload (Server) - Error when uploading large files

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#3299]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.891-1 and 1.1.442
    OS Version      : RHEL 7.3

### Steps to reproduce the problem
1. In the Files pane, try uploading a large file. In my case it was 4.69GB.
2. Observe Error message and error in the logs
```10 Aug 2018 20:38:01 [rserver] ERROR Unexpected exception: bad lexical cast: source type value could not be interpreted as target; LOGGED FROM: void rstudio::core::http::AsyncConnectionImpl<ProtocolType>::handleRead(const rstudio_boost::system::error_code&, size_t) [with ProtocolType = rstudio_boost::asio::local::stream_protocol] /root/rstudio-pro/src/cpp/core/include/core/http/AsyncConnectionImpl.hpp:235```

### Describe the problem in detail
Error when trying to upload a large file. I was able to upload a 1.59GB file with no problem, but when I try to upload a larger file (4.69GB) I get an error.

![image](https://user-images.githubusercontent.com/15237845/43982671-a52862e6-9cbc-11e8-9be3-5a40df96d414.png)

**Comment by kohlkopf** [comment]
Having the same issue on RStudio cloud, whose projects have a memory limit of 1GB. I am having issues with smaller files in that environment.

**Comment by mannau** [comment]
Seems that I'm having the same issue - just posted it on https://community.rstudio.com/t/file-upload-1gb-unexpected-response-from-server/32483.

**Comment by JsizzleR** [comment]
issue reported by Pro customer with the same error in logs, 37954

**Comment by kfeinauer** [comment]
Testing notes: test multiple browsers, verify file contents are correct on upload, and long upload requests do not timeout.
