### ISSUE TITLE
Debugger highlighting does not adjust for theme

### ISSUE THREAD

**Issue by camroberts** [rstudio/rstudio#3303]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 10
    R Version       : 3.4.1

### Steps to reproduce the problem
Set a breakpoint in a function and call that function.

### Describe the problem in detail
The currently executing line is highlighted in yellow.  This works fine in standard (or even lighter) themes, but makes code very difficult to see when using a dark theme such as Solarized Dark.

### Describe the behavior you expected
The debugger highlighting should use a colour from the theme in use.

![image](https://user-images.githubusercontent.com/8814667/44011051-8e8ccfa6-9ef9-11e8-9c97-f6683b688fcb.png)

**Comment by kevinushey** [comment]
@MariaSemple do you think this is something we could accommodate with the new theming work?

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
