### ISSUE TITLE
Problem in displaying column named "x"

### ISSUE THREAD

**Issue by shahronak47** [rstudio/rstudio#3304]
I tried to find if this has already been reported but couldn't find it. The issue is basically from here - https://stackoverflow.com/questions/41917021/interesting-array-of-letters 

I went ahead and did 

    test <- array(0,dim = c(1,5))
    colnames(test)  <- c("a", "b", "c", "d", "x")

and it still has problem displaying "x" as column name.

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.383 
    OS Version      :  Mac OS High Sierra Version 10.13.6
    R Version       : 3.4.0

**Comment by ronblum** [comment]
@shahronak47 Thanks for reporting this. We'll check it out as we work on future development of RStudio.

**Comment by kevinushey** [comment]
This is caused by the code here:

https://github.com/rstudio/rstudio/blob/1bfb11f4757d8b2220bd029a5b94cc2d9a0a54c0/src/cpp/session/modules/SessionDataViewer.R#L265-L269

We likely need to be more careful when restoring the names here.
