### ISSUE TITLE
Add search to build output text

### ISSUE THREAD

**Issue by nuest** [rstudio/rstudio#3306]
### System details

    RStudio Edition : Desktop
    RStudio Version : `1.1.383`

### Steps to reproduce the problem

Test a package with many tests and several failures. Find the failing tests by manually scrolling through the build output.

### Describe the problem in detail

I often use the Ctrl+Alt+T shortcut to test the package, and think it's great I can do that in a specific area of the IDE, that lets me continue to work on the console and see the test code side by side to the test output. However, it's kind of tricky to find the failed tests in the log log output, so it would be great if a search functionality similar to the Help viewer ("Find in Topic") could be added to the build output.

Even better would be clickable links for files mentioned in the output, but I guess search is a good and simpler start, as it also usable for other workflows.

### Describe the behavior you expected

- I can search the text of the build output.
- A click on file names included in the build output opens the file in the editor.

### Other

I'm a developer, but have not worked on RStudio and don't want to get lost working on this feature myself. I you thinks this a relevant feature, I'd be happy to give it a try if someone could give some guidance.

**Comment by ronblum** [comment]
@nuest Thank you for the feature suggestion and the offer to help with its development! We'll take a look at it as we continue to develop new versions of RStudio. If we decide that it would be a good feature to add, we'll follow up with you further about whether we'll develop it ourselves or use your help.
