### ISSUE TITLE
Cannot open the connection when RStudio Server is left idle

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#3310]
When RStudio Server is left idle for a while, some errors may occur:

```
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/tmp/RtmpPoWtv9/rstudio-available-packages-210d435e5ac6/packages.rds', probable reason 'No such file or directory'
Error in readRDS(rds) : error reading from connection
Error in readRDS(rds) : error reading from connection
Error in gzfile(file, "rb") : invalid 'description' argument
Error in gzfile(file, "rb") : invalid 'description' argument
```

### System details

    RStudio Edition : RStudio Server
    RStudio Version : 1.2.897
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.1

**Comment by kevinushey** [comment]
I think this should be fixed in the latest daily builds, which should now be live -- would you be willing to test once more?

Thanks again for testing and sorry about the frustration!

**Comment by kevinushey** [comment]
Pushed one more fix -- should hopefully be gone with v1.2.906.

**Comment by renkun-ken** [comment]
I'm testing against v1.2.907, the error seems to be completely gone. Thanks!

**Comment by ronblum** [comment]
Confirmed—I don't see the error anymore in 1.2.907 with RStudio Server on Ubuntu 16.04.5, nor with RStudio Desktop on Windows 10 and MacOS 10.14 Mojave.

**Comment by gabrielburcea** [comment]
Hello, I do also have an issue with this error. This is on MacOS 10.14 Mojave. R Studio version is Version 1.2.1335

Error in gzfile(file, "rb") : invalid 'description' argument

**Comment by kevinushey** [comment]
Any chance you can provide a reproducible example?
