### ISSUE TITLE
'Tools -> Shell...' creates two terminal windows on macOS

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3313]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.900
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Execute <kbd>Tools -> Shell...</kbd>.

### Describe the problem in detail

Two terminal windows are opened.

### Describe the behavior you expected

Only one terminal window should be opened.

### Notes

The same behavior exists in RStudio v1.1, so it appears this is not a regression.

**Comment by gtritchie** [comment]
There was a prior issue opened on this (but might have been in fogbugz and not migrated). There was some other non-obvious aspect to this, I thought, that I can't quite remember. I'll search and see if I can find anything in my notes.

**Comment by gtritchie** [comment]
Might remove this command altogether, or just have it launch the integrated terminal pane, see #1977.

**Comment by gtritchie** [comment]
Removing 1.2 milestone, whether or not we remove the command, this issue has been around a long time and doesn't need to be addressed for 1.2.

**Comment by jmcphers** [comment]
Still a problem on 1.3.

**Comment by gtritchie** [comment]
Not _really_ a terminal issue, but kinda falls in that bucket.
