### ISSUE TITLE
Request: help search box should be case-insensitive

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#3316]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.877
    OS Version      : Mac
    R Version       : 3.5.1

The search box in the help panel is case-sensitive, but it would be better if it were case-insensitive.

For example, suppose I'm interested in the help for `readChar`.

If I type "read", here's what I see:

![image](https://user-images.githubusercontent.com/86978/44109711-53e75f90-9fc3-11e8-9850-cd88287bcfd7.png)

But if I type "readc", then nothing shows up:

![image](https://user-images.githubusercontent.com/86978/44109755-6cb474fe-9fc3-11e8-9ebe-21475b1c0a04.png)

**Comment by kevinushey** [comment]
Would be nice to have the generic 'fuzzy matching' behavior here.

**Comment by dfalty** [comment]
Verified 1.3.867
