### ISSUE TITLE
prompt user to restart when changing Advanced preferences

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3318]
In the Advanced preferences pane:

![screen shot 2018-08-14 at 12 22 16 pm](https://user-images.githubusercontent.com/1976582/44113373-b7146074-9fbc-11e8-8c97-d5cded06867b.png)

We use the label 'quit required', but we should enforce an IDE restart when attempting to change these options.

From @gtritchie:

> gary [21 minutes ago]
> We have some existing "must restart" cases, such as https://github.com/rstudio/rstudio/blob/679b5070a7f024b9b1deb7e419c865ba9fb16da1/src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesPane.java#L46-L50
> 
> 
> gary [21 minutes ago]
> https://github.com/rstudio/rstudio/blob/679b5070a7f024b9b1deb7e419c865ba9fb16da1/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SourceControlPreferencesPane.java#L72-L75

We can probably follow in these footsteps.

**Comment by rich-rstudio** [comment]
@kevinushey 

I noticed if the user changes some settings in the advanced pane, then hits cancel without saving, then reopens the advanced settings, it shows the unsaved changes still. Is this intended? As a user it would make more sense to show the original settings
