### ISSUE TITLE
RStudio window disapears when laptop wakes from sleep

### ISSUE THREAD

**Issue by JackieMium** [rstudio/rstudio#3321]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456 
    OS Version      :  Debian sid
    R Version       :  Microsoft R Open 3.5.0

### Steps to reproduce the problem

1. open a fresh new instance of RStudio
2. close laptop lid and wait till laptop goes to sleep.
3. Open lid and login

### Describe the problem in detail

After the above steps, you'll see that RStudio disappears from all the windows and applications you just launched as if it was never there. However, `ps aux |grep rstudio` shows it's still running in background.

```
➜  ~ ps aux |grep rstu
adam      2819  1.3  1.7 2568212 209916 ?      Sl   16:33   2:06 /usr/lib/rstudio/bin/rstudio
adam      2888  0.1  0.7 659896 96588 ?        Sl   16:33   0:16 /usr/lib/rstudio/bin/rsession --config-file none --program-mode desktop --www-port 22580 --launcher-token 704D7E7C --show-help-home 1
adam      7897  0.0  0.0  10700   928 pts/0    S+   19:11   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn rstu
```

Then if I open another instance of Rstudio, `ps aux |grep rstudio` shows two of them in background tasks:

```
➜  ~ ps aux |grep rstu
adam      2819  1.3  1.7 2569328 210600 ?      Sl   16:33   2:07 /usr/lib/rstudio/bin/rstudio
adam      2888  0.1  0.7 659896 96588 ?        Sl   16:33   0:17 /usr/lib/rstudio/bin/rsession --config-file none --program-mode desktop --www-port 22580 --launcher-token 704D7E7C --show-help-home 1
adam      7905 19.1  1.8 2480956 223052 ?      Sl   19:12   0:01 /usr/lib/rstudio/bin/rstudio
adam      7959 10.4  0.8 659896 98080 ?        Sl   19:12   0:00 /usr/lib/rstudio/bin/rsession --config-file none --program-mode desktop --www-port 11086 --launcher-token A95F5541 --show-help-home 1
adam      8016  0.0  0.0  10700   864 pts/0    S+   19:12   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn rstu
```

### sessionInfo()

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /opt/microsoft/ropen/3.5.0/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.5.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_11.0.0     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.2.0 
```

**Comment by ronblum** [comment]
@JackieMium Unfortunately we don't support the Debian sid, the unstable version. We only supported the stable releases. Have you tried this by chance on one of those?

**Comment by JackieMium** [comment]
@ronblum well I only have a box running Debian sid. Unable to test this on Stable. Hope it only haopens in sid version then.

_Sent from my ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ronblum** [comment]
@JackieMium I mimicked sleeping with Debian 9.5 using VMWare, and RStudio stayed up when I woke it up, so I'll close the ticket. However, it's useful regardless to have this information up here in case others run into the issue, so thank you!

**Comment by kevinushey** [comment]
@JackieMium I'd also recommend trying the RStudio v1.2 [preview release](https://www.rstudio.com/products/rstudio/download/preview/) as we've done a fairly large infrastructure update that should help with these sorts of issues.

**Comment by rfaelens** [comment]
This may be due to a Qt bug:
https://bugreports.qt.io/browse/QTBUG-42985

Try to distinguish whether it is the suspend (sleep) or the screen disappearing that is the problem.
