### ISSUE TITLE
Creating a connection to Connect server complains that the server is invalid

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3322]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.906
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Tools -> Global -> Publishing -> Connect
2. Choose "Rstudio Connect"
3. Enter the URL without the port and click "Next"
4. Assuming this fails, click "Back", then try again, but with the port (e.g. 3939)

### Describe the problem in detail

The following occur. The first is without the port, the second with the port (3939):

<img width="330" alt="radix_failure" src="https://user-images.githubusercontent.com/31009952/44161874-9a561b00-a08c-11e8-812b-3f61672f9111.png">
<img width="303" alt="radix3939_failure" src="https://user-images.githubusercontent.com/31009952/44161881-9de9a200-a08c-11e8-9911-b6e452b2f19e.png">

### Describe the behavior you expected

The connection should be made successfully.

This is only a problem on Windows. It worked successfully on MacOS and Ubuntu, and with version 1.1.442.

**Comment by kevinushey** [comment]
The server URL validation is failing within `rsconnect`:

```
> rsconnect:::validateServerUrl("rsc.radixu.com")
Timing stopped at: 0.03 0.02 5.55
Timing stopped at: 0.54 0.32 1.34
$`valid`
[1] FALSE

$message
[1] "error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version"
```

I'll investigate a bit more, but since this issue is independent of RStudio I think we can move it out of v1.2-preview.

**Comment by kevinushey** [comment]
This will indeed require changes on the `rsconnect` side: see https://github.com/rstudio/rsconnect/issues/286.

**Comment by ronblum** [comment]
Got it. I'm leaving this as is, though, as a reminder to retest here once the fix is made in `rsconnect`.

**Comment by kevinushey** [comment]
I'm going to re-open this as I think getting this resolved is a blocker for the v1.2 release (we need to make sure deployments from Windows work as expected)

**Comment by jmcphers** [comment]
@ronblum:

> It worked successfully on MacOS and Ubuntu, and with version 1.1.442.

If @kevinushey's notes are correct (and the underlying problem is RCurl), then it would also reproduce on 1.1. Can you confirm that it repros on 1.1.442 on Windows?

**Comment by kevinushey** [comment]
I can reproduce with v1.1 as well. I suspect that the updated RStudio Connect servers no longer accept connections on the older protocol version requested by RCurl.

**Comment by jmcphers** [comment]
We're now bundling the dev version of rsconnect, so we should have this fix now. @ronblum, please reopen if you find that this is not the case!
