### ISSUE TITLE
No syntax highlighting in script editor, and no highlighting text in script with mouse or keyboard shortcuts

### ISSUE THREAD

**Issue by MirandaTilton** [rstudio/rstudio#3324]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.830
    OS Version      :  Ubuntu 16.04.5 LTS
    R Version       : 3.4.4

### Steps to reproduce the problem

Unknown

### Describe the problem in detail

1. Neither the mouse nor keyboard shortcuts will highlight text in the script editor window. This means that text cannot be copied from a script, although text can be pasted into a script when copied elsewhere. (Text in the console may be highlighted, so this issue is only in the script pane)

2. There is no syntax highlighting in the script pane. (E.g., comments, strings are not a different color from other text)

![image](https://user-images.githubusercontent.com/35343189/44167764-b362ca00-a094-11e8-91fd-ea2303b21d6c.png)

### Describe the behavior you expected

I expect text to be colored to correspond with its function/syntax and to be able to highlight lines of code using my mouse and/or keyboard shortcuts.

###The output of sessionInfo() 
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4  tools_3.4.4     packrat_0.4.9-3

**Comment by ronblum** [comment]
@MirandaTilton This looks like an issue, #3179, that has been resolved. The latest builds at https://dailies.rstudio.com/ should behave correctly. You might need to reset your current theme in order for the fix to take. Let us know if you're still running into issues.
