### ISSUE TITLE
Dropdowns and radio buttons don't display on MacOS Mojave—known Chromium issue

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3327]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.x
    OS Version      : MacOS 10.14 Mojave (only)
    R Version       : 3.4.4 & 3.5.1

### Steps to reproduce the problem

Go to any dialog that has a radio button or dropdown menu, e.g.
- Tools -> Global Options -> Sweave
- File -> New File -> R Markdown

and more.

### Describe the problem in detail

Dropdown menus and radio buttons are missing. They work, but the radio buttons are invisible and dropdown menus look like plain text. Checkboxes work, though, even though they're misbehaving in other products.

<img width="532" alt="rmd_radio" src="https://user-images.githubusercontent.com/31009952/44224947-123e4700-a15a-11e8-9d3d-d1f2a81304e2.png">
<img width="587" alt="sweave_dropdown_checkbox" src="https://user-images.githubusercontent.com/31009952/44224952-15393780-a15a-11e8-9b17-ed8f07dd58cc.png">

### Describe the behavior you expected

Dropdown menus and radio buttons should be seen.

This is a known issue on Mojave: some form input elements don’t render correctly in Chromium-based products. It affects other products, such as Chrome and Firefox, and is being worked on by Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=850021. I'm filing it here for tracking purposes, to check when Chromium states that the issues is resolved.

Note: zooming to less than or more than 100% makes everything work.

[I'm not closing it myself just in case there is something we need to do.]

**Comment by kevinushey** [comment]
This is indeed still an issue with the public release of Mojave. I think we should fix this for the next preview as it affects _all_ of the default UI elements for dropdowns + radios (which we have many of in our option preference panes)

**Comment by ronblum** [comment]
Confirmed fixed in RStudio Desktop 1.2.1009 on MacOS Mojave 10.14.
