### ISSUE TITLE
Find in Files should ignore Packrat folders

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3330]
https://community.rstudio.com/t/find-in-files-gums-up-the-result-with-hits-in-the-packrat-folder/12666

**Comment by daattali** [comment]
And nowadays, `renv/library` should be ignored too. This would save a ton of development time (going from <1 second to 10+ seconds for every search is exhausting)

**Comment by kevinushey** [comment]
This is implemented in the v1.3 preview release. In particular, using "Standard Git Exclusions" (for projects using Git) should be quite a bit faster.

<img width="413" alt="Screen Shot 2020-05-03 at 12 24 46 PM" src="https://user-images.githubusercontent.com/1976582/80923510-1567d500-8d39-11ea-90f9-d8a1a747a639.png">

**Comment by daattali** [comment]
Oh that's awesome!
