### ISSUE TITLE
fix up working directory when launching in development configurations

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3337]
One mistake I often make when priming a new environment for developing in RStudio is remembering to change the working directory to work from the root of the RStudio directory rather than the `desktop` directory hosting the `rstudio.exe` executable.

It'd be nice if we could detect this in development builds and just automatically fix up the working directory so that launch can succeed without issue.

**Comment by jmcphers** [comment]
We now launch this via `rstudio.bat` instead.
