### ISSUE TITLE
over-eager population of git branch menu when RStudio is focused

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3338]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.907
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Open a project containing a large number of Git branches (e.g. RStudio itself), and ensure the Git pane is open. Then, try unfocusing and refocusing the IDE window.

### Describe the problem in detail

On each focus, RStudio re-populates the Git Branch menu, and this operation is expensive when many branches exist.

### Describe the behavior you expected

The menu should be populated on-demand, when clicking on the branch menu.

### Notes

![screen shot 2018-08-17 at 11 23 21 am](https://user-images.githubusercontent.com/1976582/44282574-5855e200-a210-11e8-991f-a1a87a588909.png)

Note that in this case, we were stuck waiting for ~3s while the menu was populated.

**Comment by jmcphers** [comment]
Performance regression (keeping in 1.2)
