### ISSUE TITLE
sublime text  style keybinds

### ISSUE THREAD

**Issue by randy3k** [rstudio/rstudio#3341]
Although the upstream [ACE editor](https://github.com/ajaxorg/ace/issues/1287) doesn't support sublime mode directly, the [cloud 9 editor](https://github.com/c9/c9.ide.ace.keymaps/tree/39cbe25d2ec8280249840d82a285bc9d82658628) has a plugin to enable Sublime Text mode and the corresponding keybinds are posted [on github](https://github.com/c9/c9.ide.ace.keymaps/blob/39cbe25d2ec8280249840d82a285bc9d82658628/sublime/keymap.js).

It will be great if RStudio is able to make use of it and enable the Sublime Text style keybinds.

**Comment by ronblum** [comment]
As noted by pull request https://github.com/rstudio/rstudio/pull/3344, this is being addressed between @randy3k and @kevinushey.
