### ISSUE TITLE
Feature request: vim-surround & other vim-plugins

### ISSUE THREAD

**Issue by marskar** [rstudio/rstudio#3342]
RStudio's vim mode is great. It'd be even better with functionality from vim-plugins!
The most useful plugin, in my opinion, is Tim Pope's [vim-surround](https://github.com/tpope/vim-surround), which is already emulated by
[VS code](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim#-emulated-plugins) and [JetBrains' IDEs](https://stackoverflow.com/questions/33907396/how-can-i-use-vim-plugins-with-ideavim).

**Comment by ronblum** [comment]
@marskar Thanks for raising this—we'll take a look at this as we continue development of RStudio. And I'm glad to hear you like the vim mode!

**Comment by sbbmu** [comment]
Any update on this request?
