### ISSUE TITLE
Paste from Edit menu does not work.

### ISSUE THREAD

**Issue by randy3k** [rstudio/rstudio#3347]
### System details

    RStudio Edition : Desktop
    RStudio Version : both 1.2.907 and current master
    OS Version      : macOS 10.13.4
    R Version       : 3.5.1

### Steps to reproduce the problem

Click on the menu: `Edit -> Paste`

<img width="330" alt="screen shot 2018-08-21 at 12 49 27 am" src="https://user-images.githubusercontent.com/1690993/44380945-12cd3980-a4dc-11e8-8f95-8c603da10834.png">

### Describe the problem in detail

Nothing happens after `Paste` from the Edit Menu is clicked. However, both `cmd+v` and paste from mouse context menu works.

<img width="262" alt="screen shot 2018-08-21 at 12 49 52 am" src="https://user-images.githubusercontent.com/1690993/44380952-21b3ec00-a4dc-11e8-94ed-e94f8ca97cd0.png">

### Describe the behavior you expected

The content of the clipboard should be pasted.

**Comment by randy3k** [comment]
Not sure if #1667 is related. I discovered that the command `pasteDummy` is malfunction when I am working on #3344

**Comment by randy3k** [comment]
The Paste item works fine on 1.1.456.

**Comment by pascaloettli** [comment]
I reproduce on macOS `10.13.6` with RStudio `1.2.911` and R `3.5.1`

**Comment by ronblum** [comment]
Reproduced on MacOS 10.14 Mojave with RStudio Desktop 1.2.909-1, but not on Windows 10.

In addition, connecting to RStudio Server (1.2.907 on Ubuntu 16.04.5) using a web browser (Chrome and Firefox on Windows and MacOS) also doesn't work and results in the following dialog:
![paste](https://user-images.githubusercontent.com/31009952/44404223-6d8a8380-a524-11e8-8796-8254585456be.png)

**Comment by randy3k** [comment]
I did more experiments, the `Paste` from the Edit menu

does not paste to
- Editor
- Console
- Terminal

but it pastes to
- the search field of the History pane
- the search field of the Help pane

**Comment by kevinushey** [comment]
Seems like Copy doesn't work, either. (Surprisingly cut does?)

**Comment by randy3k** [comment]
`Copy` does work for me in both Editor and Console.

**Comment by kevinushey** [comment]
Should hopefully be fixed with https://github.com/rstudio/rstudio/commit/54caf1f66b724680091623b6eca157870e3a3e6c.

**Comment by randy3k** [comment]
Thanks. It works.

**Comment by ronblum** [comment]
@kevinushey I tested with 1.2.915. Confirmed that this is now working on Desktop (MacOS 10.14 Mojave and Windows 10), but Server issue (Ubuntu 16.04.5) is still there. Do you consider this the same issue, or should I file it separately?

**Comment by kevinushey** [comment]
Use of Cut / Copy / Paste menu items with RStudio Server has always shown that dialog as web applications indeed cannot access the user's clipboard arbitrarily in a web browser.

**Comment by ronblum** [comment]
Gotcha. In that case, closed and verified it is!
