### ISSUE TITLE
Incomplete font list in daily builds (Windows)

### ISSUE THREAD

**Issue by jacob-long** [rstudio/rstudio#3348]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.911
    OS Version      : Windows 10 (up to date as of 8/21/18)
    R Version       : 3.5.1

### Steps to reproduce the problem

Go to the "Appearance" submenu, look at the dropdown list of fonts.

### Describe the problem in detail

The selection of fonts is incomplete; that is, there a number of fixed-width fonts installed on the system that are not shown here. I should note that the ones I notice as missing are *user-installed* fonts, though I'm not sure one way or another if all the missing ones are. One example is [Monoid](https://larsenwork.com/monoid/). In my setup, there are probably 10+ fewer fonts 
showing here than I expect. The problem was still present in the oldest daily build available (1.2.882), so it's been a little while since the change occurred.

As a note, this issue is not present on macOS.

### Describe the behavior you expected

I would expect to see the same set of fonts that show in the current RStudio stable build (1.1.456).

**Comment by kevinushey** [comment]
Thanks for the bug report! I've reproduced this; I'll see if I can learn what's going on.

**Comment by kevinushey** [comment]
This should now be fixed in the latest daily builds (https://github.com/rstudio/rstudio/commit/07a7f85614df30f96811270eb2623b35399df84d#diff-10bab5c80fc04bc3d5def12a4089651c).
