### ISSUE TITLE
Bug: Changing "Evaluate chunks in directory" global option doesn't persist

### ISSUE THREAD

**Issue by bschneidr** [rstudio/rstudio#3356]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.907
    OS Version      :  Windows
    R Version       : 3.5.1

### Steps to reproduce the problem
1. Navigate to the "Global Options..."  window available in 'Tools'
![image](https://user-images.githubusercontent.com/19809917/44530501-85950b00-a6bc-11e8-9e77-42f96aaf19eb.png)

2. Set the 'Evaluate chunks in directory:" option to "Project" and click 'Apply' and 'OK'.

![image](https://user-images.githubusercontent.com/19809917/44530547-a4939d00-a6bc-11e8-8c1c-afb1cfec2e75.png)

3. Repeat step 1. Note that the "Evaluate chunks in directory" option is still set to "Document", and not "Project".

![image](https://user-images.githubusercontent.com/19809917/44530614-cb51d380-a6bc-11e8-84f2-2f73fd8662ae.png)

### Description of the problem in detail
When I set the "Evaluate chunks in directory" global option, my choice does not persist. In other words, if I set the option to "Project" instead of its default value of "Document", this has no impact on my session or on future sessions. And when I return to the options tab, the selected option remains the default "Document" rather than what I selected, which is "Project".

### Describe the behavior you expected
I expected that when I set "Evaluate chunks in directory" to "Project", that two things would happen.

1. When I return to the options page, the selected option would be "Project" rather than the default, "Document".
2. Either this would influence my current RStudio session (i.e. change where RMarkdown chunks are evaluated) or my RStudio session next time I started the program.

### Additional info

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1  rsconnect_0.8.8 tools_3.5.1     packrat_0.4.9-3

**Comment by kevinushey** [comment]
Thanks for the bug report! I've reproduced this and will take a look.

**Comment by reliscu** [comment]
This is happenig to me -- using Rstudio Version 1.1.463.

**Comment by ronblum** [comment]
@reliscu We are no longer making updates to 1.1.463 and earlier. The fix was in 1.2, so the IDE should also behave correctly in [the current release, 1.3.1056](https://rstudio.com/products/rstudio/download/). (Note that we are also getting ready to release an update, which is [currently available as a preview](https://rstudio.com/products/rstudio/download/preview/) meant for testing purposes.)
