### ISSUE TITLE
Clicking on hyperlinks does nothing in R markdown knitted to HTML from Desktop

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3359]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.914
    OS Version      : MacOS 10.14 Mojave & Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create an R Markdown file with the following.
2. Knit it to HTML, either in Viewer Pane or Window.
3. Click on the links.

```
---
title: "Example.com"
output: html_document
---

http://example.com

<http://example.com>

[linked phrase](http://example.com)
```

### Describe the problem in detail

Clicking on the links does nothing.

### Describe the behavior you expected

Clicking on the links should open the page `http://example.com` in the web browser.

Note: this works in
- Right clicking "Open Link in Browser"
- RStudio Server on Ubuntu 16.04.5 using Chrome 68 on MacOS 10.14 Mojave
- In PDF and Word knitted docs

**Comment by ronblum** [comment]
Verified on MacOS Desktop, Ubuntu Desktop, Red Hat Desktop, and Ubuntu Server.

**Comment by AleksandraMaa** [comment]
Hi, I also ran into that issue with local files. I'm working on Windows OS, and clicking the hyperlink linked to an URL works but nothing happens when it's linked to a local file. Everything works fine if I right click and do "Open in the Browser". Any help/guidance would be much appreciated!
