### ISSUE TITLE
Pressing Ctrl causes leading whitespace to disappear

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#3363]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.916
    OS Version      : Mac
    R Version       : 3.5.1

### Steps to reproduce the problem

* Create a new .R file.
* Enter text with leading spaces, like so:

![image](https://user-images.githubusercontent.com/86978/44552763-e50d0e00-a6f0-11e8-8d15-11bc2d54d344.png)

* With cursor anywhere on that line, press Ctrl.
* 2 leading spaces will disappear. That's my tab width, so I'm guessing that it's removing one tab's worth of leading whitespace.

![image](https://user-images.githubusercontent.com/86978/44552825-256c8c00-a6f1-11e8-815e-b41b05d8e63a.png)

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
