### ISSUE TITLE
Add a "never ask again" option to the save workspace dialogue 

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rstudio#3367]
Per [this](https://twitter.com/hadleywickham/status/1032665959734108160) discussion, it would be great that the save workspace dialogue had an option to "never ask again" or a "yes, always" and "no, never" buttons.

**Comment by ronblum** [comment]
@eliocamp Thanks for the suggestion, and kudos for being the discussion participant who took the initiative to file the request!

Imprecise verbosity: the request would (sort of) replicate what's in Tools -> Global Options -> General -> "Save workspace to .RData on exit" in the save workspace dialog.
