### ISSUE TITLE
Re-building a website deletes prior Connect publish record

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3371]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : macOS 10.13.6
    R Version       : 3.4.3

### Steps to reproduce the problem
- Open an R Markdown website project, such as https://github.com/gtritchie/MyWebsite
- Build Website on Build tab
- Publish from Viewer, Publish finished website only
- In 1.1.456, change title to MyWebsite to work around #3357 (fixed in 1.2.915)
- Wait for publish to Connect to complete
- Click Build Website again (e.g. after making a change to one of the files)

### Describe the problem in detail
Expect to be able to republish the site with the changes.

### Describe the behavior you expected
The Build Website deletes the `rsconnect` folder from _site, so IDE doesn't see this as a republish, but a new publish, and causes a failure because it already exists on Connect

See also: #3361

**Comment by jjallaire** [comment]
The `rsconnect` folder should AFAIC never by copied to the `_site` directory in the first place (it should be a standard exclusion). This code should already be performing that function: https://github.com/rstudio/rmarkdown/blob/master/R/render_site.R#L383-L384 so I'm not sure what is going on here.

**Comment by gtritchie** [comment]
The `rsconnect::deployApp` invocation creates the `rsconnect` folder in `_site` when publishing the static site to Connect.

If you deploy with source code, the `rsconnect` folder is created at same level as the `index.Rmd`, etc., but deploying just the output puts it in _site.

IDE behaves the same way in this regard back to 0.99, but perhaps a regression in rsconnect package (or this has never quite worked).

**Comment by gtritchie** [comment]
I could change RStudio to construct the deployApp command such that for static deployments the `rsconnect` folder goes at the root of the website project instead of in the _site directory. This would also fix #3361. Not sure what other side effects this might have, though.
