### ISSUE TITLE
allow adjustment of editor line height

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3372]
With some smaller fonts (e.g. the [proggy fonts](https://proggyfonts.net/)), the editor line height can often appear to be too big:

<img width="438" alt="screen shot 2018-08-25 at 2 55 18 pm" src="https://user-images.githubusercontent.com/1976582/44622892-ebc58d80-a876-11e8-8b2e-a5b496242c21.png">

We should allow users to adjust the editor line height to better accommodate fonts like this. (It may also be helpful for users who prefer more or less spacing between lines with other fonts as well.)

**Comment by leok31** [comment]
@kevinushey How did you get that font into RStudio? I can't see any of the proggy fonts in my Editor Font options?
Thanks

**Comment by kevinushey** [comment]
The proggy fonts can be installed from https://proggyfonts.net. They need to be installed like any other system font; after you've installed the font, you can restart RStudio and you should then see them in the font list.

**Comment by nkarres** [comment]
In 1.2.5033, the following seems to work in the active .rstheme:
`#rstudio_source_text_editor div {
  line-height: 1.3 !important;
}
`

**Comment by AndreSeb** [comment]
> In 1.2.5033, the following seems to work in the active .rstheme:
> `#rstudio_source_text_editor div { line-height: 1.3 !important; } `

It does work! Why the # instead of a . ?

**Comment by devynne07** [comment]
> In 1.2.5033, the following seems to work in the active .rstheme:
> `#rstudio_source_text_editor div { line-height: 1.3 !important; } `

Hi can someone help me figure out how to do this?  i found the rstheme file but i dont know where to put the line.  thanks!

**Comment by lincj1994** [comment]
> > In 1.2.5033, the following seems to work in the active .rstheme:
> > `#rstudio_source_text_editor div { line-height: 1.3 !important; } `
> 
> Hi can someone help me figure out how to do this? i found the rstheme file but i dont know where to put the line. thanks!

Hello. Did you find the solution??

**Comment by devynne07** [comment]
> > > In 1.2.5033, the following seems to work in the active .rstheme:
> > > `#rstudio_source_text_editor div { line-height: 1.3 !important; } `
> > 
> > 
> > Hi can someone help me figure out how to do this? i found the rstheme file but i dont know where to put the line. thanks!
> 
> Hello. Did you find the solution??

Hi sorry I took so long to reply, and im not sure if u figured it out already, but i added a line to: 

.ace_editor, .rstudio-themes-flat.ace_editor_theme .profvis-flamegraph, .rstudio-themes-flat.ace_editor_theme, .rstudio-themes-flat .ace_editor_theme {
  background-color: #121210;
  color: #F8F8F2;
  line-height: 1.85 !important;
}

it changed the height in source but not console, but that was all i was looking for so i was happy with that.  Have a great day!

**Comment by ronblum** [comment]
Verified that new option in <kbd>Tools -> Global Options -> Appearance -> Line Height (%)</kbd> adjusts the line height. Checked in RStudio Desktop 2024.12.1+522 on Windows 11.
