### ISSUE TITLE
Terminal prompt not visible at the beginning of a new rstudio session on Ubuntu Server 16 LTS

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#3373]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.930
    OS Version      : Ubuntu Server 16.04.5 LTS
    R Version       : 3.4.4

### Steps to reproduce the problem

- Open a fresh session of R Studio Server on a terminal running Windows 10 Pro and Google Chrome.
- Go to the terminal pane.

### Describe the problem in detail

When I just open a R Studio session and go to the terminal pane, the terminal prompt appears briefly and then disappears until I enter the first command.

![image](https://user-images.githubusercontent.com/14981085/44629408-9dff6280-a914-11e8-8dce-7e07c4937736.png)

### Describe the behavior you expected

I expect to see the terminal prompt at the beginning.

![image](https://user-images.githubusercontent.com/14981085/44629424-d1da8800-a914-11e8-9979-e9c8893b20f9.png)

**Comment by jmcphers** [comment]
We haven't been able to reproduce this. Have you customized your `$PROMPT` in any way?

**Comment by andresrcs** [comment]
No, I haven't.

**Comment by andresrcs** [comment]
This has stopped happening at some point, I don't know exactly when, but its not happening at least since build 1.2.1133.
