### ISSUE TITLE
Command gets duplicated in terminal when sended with Ctrl + Enter from a .sh file

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#3374]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.930
    OS Version      : Ubuntu Server 16.04.5 LTS
    R Version       : 3.4.4

### Steps to reproduce the problem

- Open a new R Studio session
- Open a .sh file
- Send a command to terminal using Ctrl + Enter

### Describe the problem in detail

When I send a command to terminal using Ctrl + Enter from a .sh file, the first command gets duplicated in terminal.

![image](https://user-images.githubusercontent.com/14981085/44629510-1dd9fc80-a916-11e8-85e9-78e49fd03a74.png)

### Describe the behavior you expected

I expect to see just the command that I have just sent

![image](https://user-images.githubusercontent.com/14981085/44629540-8923ce80-a916-11e8-8c7b-f9014a815c90.png)

**Comment by kevinushey** [comment]
I wasn't able to reproduce this in the latest daily build (1.2.1009). Can you provide any other information?

**Comment by andresrcs** [comment]
Just that I still get the same behaviour with build 1.2.1009 and that I'm using it on a virtual server from AWS

``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 16.04.5 LTS
#> 
#> Matrix products: default
#> BLAS: /usr/lib/libblas/libblas.so.3.6.0
#> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
#> 
#> locale:
#>  [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=es_ES.UTF-8        LC_COLLATE=es_ES.UTF-8    
#>  [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=es_ES.UTF-8   
#>  [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
#>  [5] tools_3.5.1     htmltools_0.3.6 yaml_2.2.0      Rcpp_0.12.18   
#>  [9] stringi_1.2.4   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
#> [13] digest_0.6.17   evaluate_0.11
```
![image](https://user-images.githubusercontent.com/14981085/46102855-f1bfce80-c194-11e8-9432-6aa82c8e8d02.png)

**Comment by gtritchie** [comment]
This sounds familiar; I believe this was previously logged in our old bug tracking system during 1.1 development, but never ported to being a github issue.

Is it purely an echoing issue? You see the first command twice, but it is only executing once?

**Comment by andresrcs** [comment]
Yes, that's exactly what's happening

**Comment by gtritchie** [comment]
You can try to mitigate it by turning off a couple of terminal options (Tools / Global Options / Terminal). You'll want to start a new terminal after changing these.

The "Local terminal echo" is the more likely candidate, but you may notice a significant slowdown when typing in the terminal with it off (so have to decide if it's worth it). The other one "Save and restore environment variables" is more of a longshot, but worth a try.

![2018-09-26_12-38-56](https://user-images.githubusercontent.com/10569626/46104851-48bfa680-c189-11e8-95cd-27a1692552fb.png)

**Comment by gtritchie** [comment]
Although annoying, this is purely an issue of duplicate echoing when sending text to a terminal as it is starting up or resuming. Fixing in a way that would cover all cases without impacting general terminal performance is quite tricky and has high regression risk, so I am closing as a "won't fix".
