### ISSUE TITLE
Select the RStudio instance in which to view a file in a Project-aware way

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#3378]
*from Slack*

When someone has RStudio open (either in no project or in project A) and, in the Finder, double clicks on an Rmd that lives in RStudio Project B, it leads to the Rmd opening in the existing instance of RStudio. And if that Rmd has paths built relative to Project B, maybe using here or rprojroot, executing those chunks in the IDE isn’t necessarily going to go well. (Knitting the whole file is still fine.) Should this launch a new instance of RStudio, in Project B? Or offer to?

Usage context: user says “I’m starting to use Projects and `here::here()` and life is awesome! But my colleagues still click on individual Rmd’s and aren’t necessarily working inside the correct RStudio Project when they start to explore or further develop the code in the chunks.”

Also, if you have multiple instances of RStudio open and you double click on an `.Rmd` in project A in the Finder, there seems to be no effort to open it in project A, even if it's open and available.

Proposal: when opening single files associated with RStudio, consider the host Project of that file when selecting (or launching) the host instance.

Note: @ajmcoqui reports this would not suit her workflow very well, as she often just wants to take a quick look at an `.Rmd` and *not* open a new instance in the associated Project.

**Comment by ajmcoqui** [comment]
To be completely transparent, I spend a lot of time looking at other people's `.Rmd`s for problems in the context of support tickets.  I am certainly not the majority case, but I do like that opening an `.Rmd` does not open a full project, since I'm usually just in there to look for a quick problem with the code, rather than run the R snippets.

**Comment by jennybc** [comment]
If this ever came to pass, perhaps the Project-aware behaviour would be the default, but configurable.

**Comment by jennybc** [comment]
This seems to be part of #2076
