### ISSUE TITLE
Emoji in Rmd file causes RStudio to core dump repeatedly

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#3379]
This seems like a serious issue. Something that sounded like the same thing was reported to me by a participant at the GEOSTAT18 conference where I was lecturing based on these slides: https://github.com/geocompr/geostats_18/blob/master/spatial-tidyverse.Rmd

I've just got a fresh install of R/RStudio on Ubuntu 18.04 and when I try to edit the file it crashes R. The reason I think this is serious is that when RStudio is next started, it instantly crashes. You can start RStudio in specific projects with `rstudio myproject` but if it starts in a project where the crash happens, it just crashes again, which could lead to some users uninstalling R. 

The solution I found was to delete the contents of `~/.rstudio-desktop/`. I think the person who mentioned the issue also did this.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Ubuntu 18.04
    R Version       :  3.5.1

### Steps to reproduce the problem

```bash
# in bash
wget https://github.com/geocompr/geostats_18/raw/master/spatial-tidyverse.Rmd
 # --2018-08-27 21:23:35--...
# Length: 16956 (17K) [text/plain]
# Saving to: ‘spatial-tidyverse.Rmd’
# ...
# 2018-08-27 21:23:36 (840 KB/s) - ‘spatial-tidyverse.Rmd’ saved [16956/16956]
rstudio spatial-tidyverse.Rmd 
# load glyph failed err=6 face=0x1efefe0, glyph=2798
# load glyph failed err=6 face=0x1efefe0, glyph=2798
# [1]    32296 floating point exception (core dumped)  rstudio spatial-tidyverse.Rmd
rstudio 
# load glyph failed err=6 face=0xf15020, glyph=2798
# load glyph failed err=6 face=0xf15020, glyph=2798
# [1]    32437 floating point exception (core dumped)  rstudio
```

### Describe the problem in detail

See above.

### Describe the behavior you expected

1. RStudio should not crash
2. RStudio should at least be able to start next time it's launched

I tried various things to enable me to open the file. I tried installing **xaringan**. I tried installing **emojifont**. No luck. I guess there's something in the file that makes RStudio die. 

...

## Update

I've found the cause: it's the emoji in line 3 of the file - when the offending line was removed it fixes it. I have also submitted a PR that fixes it in our repo: https://github.com/geocompr/geostats_18/pull/2/files

I've not merged that change because I think it may be useful as a reproducible example for others to test on.

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, I wasn't able to reproduce this with the provided example -- RStudio opens for me without issue (on my Ubuntu 18.04 VM). Can you provide any other information?

**Comment by Robinlovelace** [comment]
Sure. I even managed to make the crash happen when the file was already open this time. This is the output from the bash console after following those instructions:

```
gdb rstudio
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rstudio...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/rstudio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe83df700 (LWP 5908)]
[New Thread 0x7fffe7727700 (LWP 5935)]
[New Thread 0x7fffe6f26700 (LWP 5937)]
[New Thread 0x7fffe6356700 (LWP 5941)]
[New Thread 0x7fffe5b55700 (LWP 5942)]
[New Thread 0x7fff95a05700 (LWP 5951)]
[New Thread 0x7fff95204700 (LWP 5952)]
[New Thread 0x7fff94a03700 (LWP 5953)]
[New Thread 0x7fff87fff700 (LWP 5954)]
load glyph failed err=6 face=0xdafd20, glyph=2798
load glyph failed err=6 face=0xdafd20, glyph=2798

Thread 1 "rstudio" received signal SIGFPE, Arithmetic exception.
0x00007fffe985f104 in QFontEngineFT::averageCharWidth() const () from /usr/lib/rstudio/bin/plugins/platforms/libqxcb.so
(gdb) 
(gdb) bt
#0  0x00007fffe985f104 in QFontEngineFT::averageCharWidth() const () at /usr/lib/rstudio/bin/plugins/platforms/libqxcb.so
#1  0x00007ffff6e92f78 in QRawFont::averageCharWidth() const () at /usr/lib/rstudio/bin/libQt5Gui.so.5
#2  0x00007ffff50f178c in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#3  0x00007ffff4f8ea27 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#4  0x00007ffff50f0c6c in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#5  0x00007ffff4f75095 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#6  0x00007ffff4fc4836 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#7  0x00007ffff4fc4f96 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#8  0x00007ffff4fcb51b in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#9  0x00007ffff4f8fef4 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#10 0x00007ffff4f89f45 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#11 0x00007ffff5cb6108 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#12 0x00007ffff5d1d646 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#13 0x00007ffff5d1f552 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#14 0x00007ffff5d2b2d9 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#15 0x00007ffff5d2cf59 in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
#16 0x00007ffff5d2d9df in  () at /usr/lib/rstudio/bin/libQt5WebKit.so.5
---Type <return> to continue, or q <return> to quit---

```

**Comment by kevinushey** [comment]
Interesting that it's crashing within what appears to be some Qt font metric computation. Which font are you using in RStudio?

**Comment by kevinushey** [comment]
It may be also worth testing whether you can reproduce this issue in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio.

**Comment by Robinlovelace** [comment]
Ubuntu mono, the default one:

![image](https://user-images.githubusercontent.com/1825120/44690706-b1fdae00-aa53-11e8-8765-a22fec1fbe97.png)

**Comment by kevinushey** [comment]
This Qt bug report also suggests that this is a bug that should be fixed in the latest releases of Qt, which RStudio v1.2 does build against: https://bugreports.qt.io/browse/QTBUG-45963?jql=text%20~%20%22averageCharWidth%22

**Comment by Robinlovelace** [comment]
Good detective work. I'm downloading the preview release now.

**Comment by Robinlovelace** [comment]
Update: the preview version fixes it. RStudio seems way faster and more responsive, thanks for the awesome work, fixed in the latest edition it seems:

![image](https://user-images.githubusercontent.com/1825120/44690965-a2cb3000-aa54-11e8-8711-32fda73700be.png)


Will leave this issue open in case others hit this issue in the production version but feel free to close.

**Comment by kevinushey** [comment]
Awesome! I'm very glad to hear it 😄 

I think we can close this issue -- it should remain searchable for other users who happen to stumble upon this error. We're hoping that v1.2 will be ready for release by the end of the year, and we're working hard to get RStudio to that point ASAP!

**Comment by ronblum** [comment]
Verified both with RStudio Desktop (Ubuntu 18.04 and MacOS 10.14 Mojave) and RStudio Server (Ubuntu 16.04).
