### ISSUE TITLE
warning Error in `Encoding<-`

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#3381]
### System details

    RStudio Edition :  desktop
    RStudio Version : 1.2.907 build 910 (2067fd1d)
    OS Version      : 
    R Version       : 
```r
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
```

### Steps to reproduce the problem
From time to time, there will be this warning in console, when there is nothing active from user. This is random and doesn't seem to specific to anything I'm doing.

```r
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected
```

**Comment by kevinushey** [comment]
Thanks for the bug report! I've seen this issue as well in the current preview release, but I think we've resolved it in the latest [daily builds](https://dailies.rstudio.com/). We'll try to prepare a new preview release for testing soon, but if you have time you might try testing one of the new daily builds as well.

**Comment by jmcphers** [comment]
I do think this is resolved in the dailies, so closing for now. @dracodoc please feel free to reopen if you can reproduce in a very recent build (> 950).
