### ISSUE TITLE
provide some form of UI for selecting a Python executable

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3385]
If one is using RStudio to edit a Python script, there currently doesn't exist any mechanism for requesting a particular version of Python (e.g. before `reticulate` has actually been loaded). It'd be nice if we had some way to allow users to make this request.

Having to switch to the R console and call the associate `reticulate` APIs feels a bit cumbersome. However, advertising the `RETICULATE_PYTHON` environment variable might be sufficient.

**Comment by koverholt** [comment]
IMO, the `RETICULATE_PYTHON` env var was a holdover as something that could be used by `reticulate` and `rsconnect` for users publishing reticulated content to Connect.

So +1 to having a mechanism in the UI to select the Python binary to use.

**Comment by jmcphers** [comment]
This is done now!
