### ISSUE TITLE
Cannot publish to rpubs with any file, even the starter rmarkdown file

### ISSUE THREAD

**Issue by jgivensdoyle** [rstudio/rstudio#3389]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456 (I was experiencing this issue with 1.1.453 and updated to see if that would fix things)
    OS Version      : Windows 10 (64 Bit)
    R Version       : 3.5.1

### Steps to reproduce the problem
Use knitr on any rmarkdown file, render as HTML, click publish, the option to use Rpubs does not appear
This is occurring with the default rmarkdown template, along with all other rmarkdown files I have created.  

### Describe the problem in detail
I am not seeing Rpubs as a publishing option in either the publish menu from the knitted HTML documents or from the Tools -> Global Options -> Publishing -> Connect

All of the previous tickets I could find had issues with knitting to PDF documents or the file not being self-contained.  Neither of these is the case here.

### Describe the behavior you expected
I am hoping to be able to link this copy of RStudio to my Rpubs account

**Comment by gtritchie** [comment]
This has been a cause of confusion in RStudio 1.1, and will get better in RStudio 1.2.

The option to use RPubs only appears if you Knit to HTML, then click the **Publish button in the Viewer pane or window**. The publish button above the editor will not give RPubs as an option. It did in RStudio 1.0, and will again in 1.2.

I knitted an R Markdown file in 1.1.456, then in the Viewer pane clicked Publish, and get RPubs as an option:

![2018-08-28_17-32-53](https://user-images.githubusercontent.com/10569626/44758285-6f39e580-aae8-11e8-9ae2-1d0a196b993e.png)

![2018-08-28_17-34-18](https://user-images.githubusercontent.com/10569626/44758321-9d1f2a00-aae8-11e8-83ad-20755d886439.png)

After you have published once to RPubs for a given document, THEN the publish button in the editor will work with RPubs, giving this message:

![2018-08-28_17-36-38](https://user-images.githubusercontent.com/10569626/44758382-ed968780-aae8-11e8-85c4-2bc78ffc9c8d.png)


Also, you cannot add an RPubs account from Tools -> Global Options -> Publishing -> Connect. That is only used for Shinyapps.io and RStudio Connect accounts. RPubs never shows up there.

Let me know if this helps!

**Comment by jgivensdoyle** [comment]
Hi Gary,

The viewer pane is empty after I choose knit.  I get the popup HTML document, which on a previous computer is where I clicked to publish to rpubs.  Should I be seeing the HTML document in the viewer pane?  I have attached two screenshots to show the viewer pane and to show what I get when I click publish on the HTML document popup.  Please let me know if additional information or diagnostics is required.

![empty viewer](https://user-images.githubusercontent.com/41029327/44790561-a4d4e200-ab6d-11e8-9d50-f63763cef425.JPG)


![publishing options](https://user-images.githubusercontent.com/41029327/44790354-29733080-ab6d-11e8-9679-e9321b565578.JPG)

**Comment by gtritchie** [comment]
The popup HTML document window is fine. There's an option to have Knit show in the viewer, instead, but either way accomplishes the same thing.

Your screenshot of clicking Publish in the popup HTML window shows RPubs as an option. Is that option not working for you? That is how you publish to RPubs (and will let you login to RPubs if you haven't yet on this computer).

**Comment by gtritchie** [comment]
Did this work for you? I'm going to assume it did; if you are still unable to publish to RPubs please reopen and let me know what's happening. Thanks!

**Comment by pablobernabeu** [comment]
``` 
install.packages('rsconnect')
library(rsconnect)
```
solved it for me

**Comment by joseph-allen** [comment]
This is still an issue, When clicking RPubs it fails.

![image](https://user-images.githubusercontent.com/7880824/121191754-2b14cb80-c864-11eb-9826-033230e551e2.png)

![image](https://user-images.githubusercontent.com/7880824/121191822-3e279b80-c864-11eb-8d8c-f6f2cfc341f4.png)

To not ignore @pablobernabeu , annoyingly the rsconnect package was the fix! Thank you so much, I've been googling this for hours!

After installing this my publish prompts took me to account creation on RPubs
