### ISSUE TITLE
Ubuntu 18.04 32 bit

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#3390]
RStudio Edition : Desktop
    RStudio Version : 1.2.xxx
    OS Version      :  Ubuntu 18.04 (32bit)
    R Version       : 3.5.1

I tried to compile RStudio Desktop on 32bit Ubuntu 18.04.
It was impossible.
The main problem was that RStudio needs Qt 5.11 and there is not open source release for that version of Qt (5.5 is the latest open source version)
Will a version of RStudio of 32bit Ubuntu 18.04 be available in the future or will RStudio only be available for 64bit Linuxes?

**Comment by gtritchie** [comment]
Sorry, we no longer support build RStudio for 32-bit OS on any platform.
