### ISSUE TITLE
Adding chunk using command

### ISSUE THREAD

**Issue by balthasars** [rstudio/rstudio#3391]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 1.1.423
    OS Version      : macOS 10.13.1 
    R Version       : 3.5.1 

### Steps to reproduce the problem
Selecting code and pressing `cmd`+ `alt` + `I`

### Describe the problem in detail
When using the command for inserting a chunk, the inserted chunk does not wrap around the selected code. 

### Describe the behavior you expected
Code is inserted into chunk wrapper.

**Comment by jmcphers** [comment]
Thanks for the suggestion! We're currently tracking this in https://github.com/rstudio/rstudio/issues/2444.
