### ISSUE TITLE
bookdown "build book" drop-down not rendered properly

### ISSUE THREAD

**Issue by sellorm** [rstudio/rstudio#3395]
The bookdown "build book" drop-down on the "build" tab hangs over the side of the window when the environment pane is moved to the left. This results in the dropdown being truncated on the left side.

see attached...

<img width="343" alt="build-bookdown" src="https://user-images.githubusercontent.com/2036487/44818008-58c28580-abdf-11e8-9c91-e8e586ab293f.png">

### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.906
    OS Version      :  macOS 10.13.6
    R Version       :  3.5.1

### Steps to reproduce the problem

* Move the environment pane to the left side
* open a bookdown project (r4ds will do)
* open the build tab
* click the "build book" drop-down button

### Describe the problem in detail

the drop down menu extends beyond the window boundary and is therefore not rendered in its entirety.

### Describe the behavior you expected

drop down not hanging off the side of the window

**Comment by sellorm** [comment]
It's the same in RStudio 1.2.937 too

**Comment by jmcphers** [comment]
I've confirmed that this reproduces on the latest daily (1.2.952). Thanks for filing this!

**Comment by gtritchie** [comment]
This was a duplicate of #1652
