### ISSUE TITLE
Improve visibility of '...' menu in Files pane

### ISSUE THREAD

**Issue by crossxwill** [rstudio/rstudio#3398]
I’ve been using RStudio Server Pro for 5 years. This issue comes up about 5 times per year from new users.
 
The “…” button used to navigate to folder is almost impossible to notice.
 
I suggest using a button that says “Browse…”.

![image](https://user-images.githubusercontent.com/4138594/44822532-7a584880-abb0-11e8-8e0d-43e6838f490a.png)

**Comment by gtritchie** [comment]
Note: on RStudio Server, this button doesn't bring up an operating-system browse dialog, but a simple "type a path" dialog. Not sure "Browse..." makes sense in that context, but might be over-thinking it.

<img width="322" alt="RStudio go-to-folder dialog screenshot" src="https://user-images.githubusercontent.com/10569626/73293197-47a4ec00-41b8-11ea-9a1e-cfa52bfe63bd.png">
