### ISSUE TITLE
Rmarkdown inline code highlight is displace when another accent is present in the line

### ISSUE THREAD

**Issue by Narciandi** [rstudio/rstudio#3399]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.0.143
    OS Version      :  Windows 10 Home 64 bits (10.0, compilation 17134)
    R Version       :  3.5.1

### Steps to reproduce the problem

I am currently writing a report in Spanish using a rmd file,, with output as a pdf file. I am using LaTeX syntax for opening question mark (?` -> ¿), and I'm including an inline call to R in the same line. The IDE is confusing what text to highlight as inline code, highlighting from the question mark to the start of the inline code chunk. 

```
Finalmente, respecto a la pregunta \textit{?`Recomendaría usted este centro?} el  `r ProporcionRecomienda(codigoCentro, datosAlumnos)`\% de las familias que respondieron lo hicieron afirmativamente
```

![imagen](https://user-images.githubusercontent.com/19656549/44839443-12047800-ac3f-11e8-84f3-ed582abcef30.png)

The issue is limited to RStudio IDE, since the pdf output is just as expected:

![imagen](https://user-images.githubusercontent.com/19656549/44839531-53952300-ac3f-11e8-83c4-03c27286174d.png)

### Describe the behavior you expected

I would expect the IDE would recognize and highlight the inline code instead the LaTeX code.

**Comment by ronblum** [comment]
Verified in RStudio Desktop (MacOS 10.14 Mojave) and RStudio Server (SUSE 12.3) version 1.2.957.
