### ISSUE TITLE
Not sending command to console from python scripts (ctrl+Enter)

### ISSUE THREAD

**Issue by IuiuCalella** [rstudio/rstudio#3402]
I'm running python scripts in Rstudio with the 'reticulate' library, 
The issue is that I can't send commands from my 'script.py' file to the console with the 'ctrl+Enter' shortcut.

This only works when changing the name 'script.py' to 'script.py.R' which is a problem when you want to use straightforward repositories or upload the code in production, etc.

**Comment by ronblum** [comment]
@IuiuCalella I assume you closed this since this is working? I wasn't able to reproduce the issue; I tried it with RStudio Desktop on MacOS and RStudio Server on SUSE, and both worked as expected.
