### ISSUE TITLE
Use RStudio's viewer to display HTML plots from the terminal (python)

### ISSUE THREAD

**Issue by jiho** [rstudio/rstudio#3404]
With the current support for python syntax in the editor, a terminal that can run `python` or `ipython` and a keyboard shortcut to send code from the editor to the terminal easily, RStudio is actually a decent python development environment (and projects, RStudio server, etc. are advantages that are difficult to find in *actual* python IDEs!).

A main roadblock I am hitting now is how to display plots from python. Locally, python can open plotting windows for `matplotlib` or browser windows for HTML-based plotting libraries (`plotly`, `bokeh`). But the later, opening them in RStudio's viewer would be nicer.

In addition, when running remotely, using RStudio server, the terminal there cannot easily open a window on a server and send it to the client, while displaying HTML-based plot in RStudio's viewer would be perfect.

Is there anyway to declare RStudio's viewer as the default browser in RStudio's terminal? Would there be another workaround? I'd be glad to test anything!

PS: I know about reticulate but I need to stay full python in this case, for collaboration purposes.

A bit of bokeh code as a test:

```
# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# import bokeh
from bokeh.plotting import figure, show, output_notebook, output_file

# output to static HTML file
output_file("foo.html")
# output_notebook() # for jupyter notebooks

# create a new plot
p = figure()
# add a line renderer with legend and line thickness
p.line(x, y, legend="Bar", line_width=2)
# show the results
show(p)
```

Thanks in advance!

**Comment by jfulponi** [comment]
Hi, I'm having this issue 5 years later :) Any update on html outputs from a .py script in RStudio? Thanks!

**Comment by helenmiller16** [comment]
I'm also interested in this feature!

**Comment by jfulponi** [comment]
> I'm also interested in this feature!

@helenmiller16 I made a snippet of code to "render" the map/plot as a quarto document with the Jupyter engine, but it seems very rough to me because I can't interact with the html widget from the code directly. This needs to be simple as executing a line of code and having the output rendered on the Viewer Panel, like a Jupyter Notebook with iPy or any leaflet map with R.
