### ISSUE TITLE
Feature request: an option to turn off the diagnostics of <- in function arguments

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#3405]
This is a follow-up of #3289 (cc @kevinushey). As I mentioned in that Twitter thread (https://twitter.com/xieyihui/status/1027237210771386369), I just happen to have the habit of assigning values in function arguments and this is the only occasion on which I use the left arrow, e.g.,

![image](https://user-images.githubusercontent.com/163582/44872756-ff4c6c00-ac5b-11e8-854e-6f4ee3df1332.png)

I hope we could provide an option to skip the linting of this particular case (i.e., I clearly know what I'm doing). I guess for most users, using `<-` in a function argument is probably an unintentional mistake, so I don't mind if this option is somewhat purely "internal", e.g., I'd be totally happy with something like `options(rstudio.linting.arrow = FALSE)`. Thanks!

**Comment by kevinushey** [comment]
I think you're right -- there are a number of valid + intentional ways for this idiom to be used, so warning by default is probably not the right choice here. I will take a look!

**Comment by ronblum** [comment]
Verified that new "Check usage of '<-' in function call"" property/diagnostics checkbox works, using RStudio Desktop 1.2.957 on MacOS 10.14 Mojave and RStudio Server 1.2.957 on SUSE 12.3.
