### ISSUE TITLE
Theme - 404 on default theme on a fresh user that hasn't selected another theme.

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#3406]
### System details
    RStudio Edition : Server
    RStudio Version : 1.2.937-1
    OS Version      : Ubuntu 14

### Steps to reproduce the problem
1. Log into RStudio Server with a new user that hasn't selected a theme.
2. Observe text highlighting is missing and 404 in Console
3. Change theme and observe theme seems to work as expected
4. Change theme back to default (Textmate) and observe text highlighting is back to working

### Describe the problem in detail
404 on default theme on a fresh user that hasn't selected another theme. There seems to be a difference between the default theme when nothing has been selected and when Textmate is specifically selected.
![image](https://user-images.githubusercontent.com/15237845/44874094-b5fe1b80-ac5f-11e8-9ae2-56259c8b79ee.png)

**Comment by kevinushey** [comment]
@MariaSemple was this fixed by https://github.com/rstudio/rstudio/commit/8c7a38fbaf00aec5e249569d1d31fbe4289dd805?

**Comment by MariaSemple** [comment]
Yes, it should be fixed now.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.937-3.
