### ISSUE TITLE
ANSI Color Escape Codes

### ISSUE THREAD

**Issue by chris-prener** [rstudio/rstudio#3408]
Thanks in advance for your help with this Issue! I really appreciate all the time that goes into RStudio and its a joy to use an teach with. I'm happy to provide other info if you need it.

### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.456
    OS Version      :  macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem
Execute a function like `devtools::test()` or `blogdown::serve_site()` that includes some color output in the console.

### Describe the problem in detail
If I execute a function like `devtools::test()` or `blogdown::serve_site()` that includes some color output in the console in RStudio, I get what [appear to be ANSI escape codes](https://community.rstudio.com/t/output-issues-with-rstudio-1-1-453/10588) in RStudio:

```r
> test()
Loading qualmap
Testing qualmap
✔ | OK [31mF[39m [35mW[39m [34mS[39m | Context
[32m✔[39m |  2       | test cluster define
[32m✔[39m | 10       | test cluster validate
[32m✔[39m |  6       | test cluster create

══ [1mResults[22m ══════════════════════════════════════════════════════════════════════════════════════════════════════════════
OK:       [32m18[39m
Failed:   [32m0[39m
Warnings: [32m0[39m
Skipped:  [32m0[39m
```

This behavior began on 1.1.453 and has persisted over the summer with several attempts to re-install RStudio and the upgrade to 1.1.456.

### Describe the behavior you expected
When I use `test()` on the same package in the console that comes bundled with `R`, I get the expected output without any escape codes:

```r
> test()
Loading qualmap
Testing qualmap
✔ | OK F W S | Context
✔ |  6       | test cluster create

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════════════
OK:       18
Failed:   0
Warnings: 0
Skipped:  0
```

The expected behavior in RStudio would be similar output but with color characters in the console.

### Session Info 

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] qualmap_0.1.0.9000 devtools_1.13.6    testthat_2.0.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     pillar_1.3.0     compiler_3.5.1   later_0.7.3      bindr_0.1.1      class_7.3-14    
 [7] tools_3.5.1      digest_0.6.16    tibble_1.4.2     memoise_1.1.0    pkgconfig_2.0.2  rlang_0.2.2     
[13] cli_1.0.0        rstudioapi_0.7   shiny_1.1.0      DBI_1.0.0        commonmark_1.5   crosstalk_1.0.0 
[19] yaml_2.2.0       bindrcpp_0.2.2   spData_0.2.9.3   e1071_1.7-0      withr_2.1.2      stringr_1.3.1   
[25] dplyr_0.7.6      roxygen2_6.1.0   xml2_1.2.0       htmlwidgets_1.2  tidyselect_0.2.4 classInt_0.2-3  
[31] leaflet_2.0.2    grid_3.5.1       glue_1.3.0       sf_0.6-3         R6_2.2.2         purrr_0.2.5     
[37] magrittr_1.5     promises_1.0.1   htmltools_0.3.6  units_0.6-0      assertthat_0.2.0 mime_0.5        
[43] xtable_1.8-3     httpuv_1.4.5     stringi_1.2.4    crayon_1.3.4    
```
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2338109/diagnostics-report.txt)

**Comment by gtritchie** [comment]
RStudio 1.1 does support ANSI color codes in the console.

What is your setting under Tools / Global Options / Code / Display, for ANSI Escape Codes?

![2018-08-30_16-35-53](https://user-images.githubusercontent.com/10569626/44884931-fe730480-ac72-11e8-8b08-bd76394015ec.png)

**Comment by chris-prener** [comment]
The solution you presented @gtritchie worked perfectly - thanks so much!
