### ISSUE TITLE
theme warning when opening help

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3410]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.943
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Activate a dark theme, run the reticulate Python REPL, and try to request help:

```R
reticulate::repl_python()
?dict
```

### Describe the problem in detail

A theme-related warning is emitted, and the help document is not readable:

```
>>> ?dict
Warning: No Python documentation found for 'theme/default/tomorrow_night_bright.rstheme?dark=1'.
```

![screen shot 2018-08-31 at 9 13 22 am](https://user-images.githubusercontent.com/1976582/44923930-8eaa5b80-acfe-11e8-91dc-50d0d2d2b953.png)
![screen shot 2018-08-31 at 9 16 25 am](https://user-images.githubusercontent.com/1976582/44923931-8eaa5b80-acfe-11e8-81a4-a17abcc87c71.png)

### Describe the behavior you expected

Python help should open without issue.

### Notes

We probably need the URI handler for themes on the Python endpoint as well:

![screen shot 2018-08-31 at 9 17 39 am](https://user-images.githubusercontent.com/1976582/44923994-cc0ee900-acfe-11e8-8d20-fc3812155d11.png)

**Comment by ronblum** [comment]
Verified on RStudio Desktop (MacOS 10.14 Mojave & Ubuntu 18.04) and RStudio Server (SUSE 12.3).
