### ISSUE TITLE
Preserving Tab Order

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#3412]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.907
    OS Version      : MacOS
    R Version       : 3.5.1

### Steps to reproduce the problem

- Open RStudio
- Create an RMarkdown Document
- Watch the "Jobs" tab in the lower-right corner move to the end and "R Markdown" added before.

### Describe the problem in detail

Shift from:

```
 "Console", "Terminal", "Jobs"
```

<img width="367" alt="screen shot 2018-08-31 at 12 19 05 pm" src="https://user-images.githubusercontent.com/833642/44926779-16e92a80-ad18-11e8-97bf-8fe16447ed06.png">

To: 

```
 "Console", "Terminal", "RMarkdown" , "Jobs"
```

<img width="545" alt="screen shot 2018-08-31 at 12 15 29 pm" src="https://user-images.githubusercontent.com/833642/44926726-0933a500-ad18-11e8-9881-39cbaaf1a3b3.png">

### Describe the behavior you expected

RMarkdown should be added at the end. 

```
 "Console", "Terminal" , "Jobs", "RMarkdown"
````

**Comment by jmcphers** [comment]
These tabs aren't like editor tabs -- they have a stable order. For instance, "Terminal" is always right after "Console", no matter which order the tabs were open in. There are pros to this approach (tab location is more predictable) and cons (as you've pointed out), but we're not planning to change it soon.
