### ISSUE TITLE
Rendered chunk output disappears after using search/replace in RNotebook.

### ISSUE THREAD

**Issue by kohlkopf** [rstudio/rstudio#3422]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.453
    OS Version      : CentOS 7  
    R Version       : 3.5.0

### Steps to reproduce the problem

1. Run a chunk which produces output (a plot, table, or anything) in an RNotebook.
2. Search and replace a word anywhere in the document.
3. Observes the absence of previously rendered output.

### Describe the problem in detail

Rendered chunk output disappears after using search/replace in RNotebook.

### Describe the behavior you expected

I'd expect the output to remain.

**Comment by ronblum** [comment]
@kohlkopf I can reproduce this, but only when clicking on <kbd>All</kbd>. Is this the only time you see this, or do you see also see the problem when you replace individual words by clicking on the <kbd>Replace</kbd> button?

**Comment by kohlkopf** [comment]
@ronblum You've got it Ron, only when replacing a word using `All` do I see the behavior.

**Comment by jmcphers** [comment]
This happens because All works by removing all the content from the editor and replacing it with the corrected content. Because removing a chunk removes its output, this has the side effect of removing all the output.
