### ISSUE TITLE
readline with newline(\n) in prompt shows cursor at wrong line

### ISSUE THREAD

**Issue by EmilBode** [rstudio/rstudio#3426]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem
```
readline("BlahBlahBlah...\nAre you sure? ")
```

### Describe the problem in detail
My cursor appears directly after "BlahBlahBlah..."
After I press \<Return\>, my input is moved to the final line, after "are you sure?"

### Describe the behavior you expected
I expect my cursor to appear after "are you sure?" right away, just as happens when I run R from a terminal, or standalone R console

### Notes
- There is no difference between running or sourcing the code
- I've included sessionInfo(), but setup is quite vanilla
- I've compared with terminal and R Console, but no other environments/setups
- My input is read as expected

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1 
```

**Comment by EmilBode** [comment]
Of course writing
```
cat('BlahBlahBlah...\n')
readline('Are you sure? ')
```
is a workaround, but I don't think it's possible to specify the colours, right?

**Comment by ronblum** [comment]
@EmilBode Thank you for reporting this issue! We'll review it as we work on ongoing development of RStudio.

Reproduced on with RStudio Desktop 1.2.957 on MacOS 10.14 Mojave and RStudio Server 1.2.957 on SUSE 12.3.

**Comment by jmcphers** [comment]
I believe this is the same issue as https://github.com/rstudio/rstudio/issues/2947.
