### ISSUE TITLE
Feature request: show trailing spaces in data viewer

### ISSUE THREAD

**Issue by isteves** [rstudio/rstudio#3428]
In my original [community.rstudio post](https://community.rstudio.com/t/display-leading-trailing-whitespaces-in-rstudio-data-viewer/13658), Jonathan mentioned that leading white spaces are visible in the data viewer in RStudio 1.2.  🎉 

It would be great if **trailing** spaces could be shown/highlighted, too.  

Two possibilities that come to mind are (a) highlighting them tibble-style:

```r
aa <- tibble::tibble(abc = c("one", "two ", " three"))
aa
#> # A tibble: 3 x 1
#>   abc
#>   <chr>   
#> 1 one     
#> 2 "two "  
#> 3 " three"
```

or (b) marking with dots as in MS Word:

![image](https://user-images.githubusercontent.com/25118334/45116897-cc730e00-b15c-11e8-81ca-78468b2c316f.png)

**Comment by jameshowison** [comment]
+1 for marking whitespace both in the Data Viewer and in tables formatted in Rmarkdown output sections.  

In the meantime I'm finding the `verify` function from `assertr` to be useful (and I guess a case could be made for avoiding visual inspection, but nonetheless).
