### ISSUE TITLE
RStudio tries to open an incredibly long file name (QtProject.lock.rmlock.rmlock.rmlock...)

### ISSUE THREAD

**Issue by SarenT** [rstudio/rstudio#3431]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.383 – © 2009-2017 RStudio, Inc.
    OS Version      :  Ubuntu LTS 16.04
    R Version       :  R version 3.4.4

### Steps to reproduce the problem

1. Opening RStudio
2. Trying to save script file

### Describe the problem in detail
When trying to save R script file, file dialog gets frozen.

### Describe the behavior you expected
File dialog shouldn't freeze and allow user to save the file.

I tried to find the underlying cause. Due to network issues some shares may not be accessible and causing processes to freeze in D state. I was suspecting that. Therefore, I ran RStudio via command line with strace. strace shows system calls.
**strace rstudio**
It revealed this:
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2237, ...}) = 0
stat("/home/username/.config/QtProject.conf.lock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2237, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2237, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2237, ...}) = 0
uname({sysname="Linux", nodename="lngrad031", ...}) = 0
**open("/home/username/.config/QtProject.conf.lock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock.rmlock", O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 ENAMETOOLONG (File name too long)
nanosleep({6, 400000000}, {4, 460672645}) = ?** 

I think RStudio somehow got to generate too many of these files and froze itself. Restarting doesn't solve the issue as these files remain.

Deleting those lock files stopped the freezing.

**Comment by kevinushey** [comment]
See also: https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1576989

I suspect this is fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) -- can you give that an install and try?

**Comment by SarenT** [comment]
Sadly, I won't be able to test it in near future. Also, I don't know how to reproduce the initial problem. Those files were created a month ago (checked with ls -lah). I don't know what caused it.

**Comment by jmcphers** [comment]
Since we don't have a repro or any other reports, and you haven't been able to test in your environment, we're closing this. Feel free to reopen if you still see the problem with the stable build, 1.2.5019.
