### ISSUE TITLE
SQL script preview results in "parameter type mismatch" error

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3436]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.956
    OS Version      : Windows 10, MacOS 10.14 Mojave, Ubuntu 18.04
    R Version       : 3.5.1 and 3.4.4

### Steps to reproduce the problem

1. File -> New File -> SQL Script
2. Preview

### Describe the problem in detail

Previewing the SQL script results in an error pop-up dialog with the message, "Parameter type mismatch."
<img width="209" alt="sql_mismatch" src="https://user-images.githubusercontent.com/31009952/45179526-c6297400-b1e6-11e8-9b49-997e7d51fc57.png">

### Describe the behavior you expected

The SQL script should run, and a SQL Results tab should be created with the following results:
<img width="178" alt="sql_results" src="https://user-images.githubusercontent.com/31009952/45179522-c164c000-b1e6-11e8-9457-5e3e6ae93c7b.png">

**Comment by kevinushey** [comment]
Can you confirm what contents you have in the new SQL script (are you getting the default template)?

**Comment by ronblum** [comment]
It's the default template.

```
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

SELECT 1
```

Also:
```
> packageVersion("DBI")
[1] ‘1.0.0’
> packageVersion("RSQLite")
[1] ‘2.1.1’
```

**Comment by kevinushey** [comment]
Thanks!

I think the issue here is caused by attempts to preview an unsaved file -- we should open a Save Dialog in that case and then run the preview only after a successful save rather than showing the bogus error.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.2.961.
