### ISSUE TITLE
rstudio server won't correctly recognise Git in ~/.usr/bin 

### ISSUE THREAD

**Issue by cmhh** [rstudio/rstudio#3437]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.453
    OS Version      :  Debian GNU/Linux 9 (stretch)
    R Version       : 3.4.4

### Steps to reproduce the problem
Attempt to create a new project via 'version control' -> Git.  Am told there is not git installation.

### Describe the problem in detail
I am in an enterprise environment and git is not globally available.  I installed it from source into ~/.usr/bin since that folder was already in use for other applications.  

When I try and create a new project using 'version control'->Git I am told git is not installed.  When I try and set version control for an already existing project the dropdown box doesn't have Git as an option.  

Git is clearly present, however--I have manually set the location in the global options, `system("which git")` returns the correct result, and I can run git from a terminal inside rstudio.  

If I make a symbolic link from `~/.usr` to `~/usr`, and add `~/usr` to my path variable, all works fine.  So, it seems rstudio doesn't like git installed in a hidden folder?

### Describe the behavior you expected

I expect rstudio to recognise a git installation in `~/.usr/bin`.

Cheers

**Comment by jmcphers** [comment]
RStudio uses this to detect the location of your Git binary:

    Sys.which("git")

Does that return the correct path for you when git is in ~/.usr?

**Comment by cmhh** [comment]
Yes, I get:

```bash
> Sys.which("git")
                                  git 
"/home/STATSNZ/cxhansen/.usr/bin/git"
```

**Comment by ronblum** [comment]
@cmhh Is this still an issue? Our [current production release is 1.2.5033](https://www.rstudio.com/products/rstudio/download/) and there is a [1.3 preview release available](https://rstudio.com/products/rstudio/download/preview/), so hopefully the issue has been resolved. (Note that preview builds are intended for testing purposes only.)

**Comment by cmhh** [comment]
When this issue popped up, our servers didn't have git installed globally.  Since then, our admins have installed git, so I'm not quite sure how I'd be able to test this.  I'll look into it, though.

**Comment by jmcphers** [comment]
We have no way to test this either, so closing.
