### ISSUE TITLE
Some buttons become unclickable after failure to create an R package missing required package

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3438]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.956
    OS Version      : Windows 10, MacOS 10.14 Mojave, Ubuntu 18.04, Red Hat 7.5
    R Version       : 3.4.4 and 3.5.1

### Steps to reproduce the problem

1. Check if the `RcppArmadillo` package is installed. If it is, remove it
```
packageVersion("RcppArmadillo")
remove.packages("RcppArmadillo")
```
2. Create a new project using `RcppArmadillo`
    - File -> New Project -> New Directory -> R Package using RcppArmadillo
    - Enter directory name -> Create Project
        - An error dialog pops up, along with the console message "Error in loadNamespace(name) : there is no package called ‘RcppArmadillo’"
<img width="187" alt="no_armadillo" src="https://user-images.githubusercontent.com/31009952/45185778-5f618600-b1f9-11e8-8be0-65e94306d501.png">

3. Dismiss the error by clicking "OK"
4. Click on any IDE top row icons, and any of the tabs and icons in the top two panes
   - Unclickable and unresponsive
<img width="463" alt="icons" src="https://user-images.githubusercontent.com/31009952/45185599-b74bbd00-b1f8-11e8-9f70-59a7d5157203.png">

5. Click on any of the menu bar options and any of the tabs and icons in the bottom two panes
   - Clickable and responsive
<img width="192" alt="menubar" src="https://user-images.githubusercontent.com/31009952/45185608-bca90780-b1f8-11e8-81ad-ed20565dedb8.png">

### Describe the problem in detail

The icons, etc., in step 4 are unresponsive.

### Describe the behavior you expected

All of the features of the IDE should continue to work.

The same occurs with `Rcpp`, `RcppEigen`, and `devtools`. It's not an issue with `bookdown` and `blogdown` because if these packages are not installed, they don't show up as options, so maybe the solution is to hide `Rcpp`, etc., if they're not installed; or, instead of an error, give the option to install the necessary package (a separate enhancement request).

This is a regression, as it worked in 1.1.456 (at least on MacOS Desktop).

**Comment by ronblum** [comment]
Confirmed that it works if you install the package. However, if you choose not to install the package (click "No" at the pop up), then the message "Creating project" gets stuck on top and the buttons are still unclickable.

<img width="168" alt="create" src="https://user-images.githubusercontent.com/31009952/45649922-b4738680-ba9a-11e8-88ae-2b1f9368751a.png">

**Comment by kevinushey** [comment]
I'm going to punt this (not worth investigating or fixing for v1.2 since there's no reason a user would want to open such a project and then _not_ install the package)
