### ISSUE TITLE
Can multiple clients access the same server process?

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#3441]
Is it possible to access a server process from difference clients concurrently?
E.G. one process might fetch data and the other client doing analysis of the data?

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
