### ISSUE TITLE
Provide way to edit or view secondary CRAN repositories

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3442]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.956
    OS Version      : MacOS, Windows 10, Ubuntu
    R Version       : 3.4.4 & 3.5.1

### Steps to reproduce the problem

Add a secondary repository under "Package Management" in Global Options.

### Describe the problem in detail

There is no option to edit or view an existing repository.

### Describe the behavior you expected

The ability to move the order of the repositories is great. It would be helpful to also be able to edit an existing secondary repository, though, or to at least see its current value, as is the case with custom primary repositories.

**Comment by jmcphers** [comment]
This is implemented now.
