### ISSUE TITLE
Warning after inserting a snippet with multiple code chunks

### ISSUE THREAD

**Issue by strboul** [rstudio/rstudio#3446]
I use the snippet below to paste a kind of header looking-like comment with the intent of visually differentiating the sections I want to see in my code:
```
snippet header
	`r paste("###", paste(rep("-", 69), collapse = ""))`
	`r paste("###")` ${1:TITLE}:
	`r paste("###", paste(rep("-", 69), collapse = ""))`
	${0}
```

However, after successfully applying this snippet in a file, I get the following warning - shows up when running a command such as `print("a")` after then:
```
Warning message:
In if (matches == -1) return(snippet) :
  the condition has length > 1 and only the first element will be used
```

Using RStudio Desktop version `1.1.453`.

**Comment by ronblum** [comment]
@strboul Thanks for reporting this! We'll review it as we continue to work on development of RStudio. I am also able to reproduce this in a recent daily build (1.2.961) using an even simpler example:
```
snippet prints
	`r print(1)`
	`r print(2)`
```

**Comment by strboul** [comment]
I don't reproduce this bug anymore on version `1.2.1335`. Could we say that it is resolved?

**Comment by ronblum** [comment]
@strboul Thank you for following up, and I've verified this. Thanks!
