### ISSUE TITLE
Cannot Exit readLines(file("stdin")) in Windows

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#3448]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423 
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

Run the following in the console:

``` r
readLines(file("stdin"))
```

### Describe the problem in detail

I cannot exit this.  `Ctrl+Z` appears to be bound to undo, so I cannot send an end file that way, and I found no other way to exit the readLines prompt.

### Describe the behavior you expected

Either return `character(0)` as occurs in RGui or have some way to exit.

**Comment by kevinushey** [comment]
Reading from stdin is not currently supported.

What do you want access to `stdin` for? If you need to read user input, you should be able to use `readline()`.

**Comment by billdenney** [comment]
@kevinushey, I was running an example that I found online.  I don't actually need to read `stdin` in general.

The issue is that when I ran `readLines(file("stdin"))` I could not do anything in the Rstudio console.  I had to restart the R session.  The issue that I'd like to have fixed is that the command above should not block the console.  Could `stdin` handling be updated so that `readLines(file("stdin"))` just returns `character(0)` like Rgui does?

**Comment by ronblum** [comment]
Marking as a bug—even though it's unsupported, there is no way to get out of this.

**Comment by chasemc** [comment]
I ran into this today. 

Accidentally typed something like `lapply(zz, readLines()) ` instead of `lapply(zz, readLines) `. Only option was to restart R. Could be annoying to some as there is no error or warning; R just hangs.  This behavior is not consistent with RGui.exe or Rscript.exe, but is consistent with R.exe.

**Comment by zerweck** [comment]
Is this on anyone's radar? I just killed a huge session with many objects in the RAM just because I accidentally used the wrong autocomplete option (just like @chasemc) . Very annoying and absolutely unclear from the user perspective when it happens.

**Comment by krzyklo** [comment]
Run into this trap as well = Restart R

**Comment by billdenney** [comment]
Thanks!

**Comment by krzyklo** [comment]
superb! Thank you
