### ISSUE TITLE
Middle wheel scrolls through open editor tabs in incorrect order after manually changing tab order (by dragging)

### ISSUE THREAD

**Issue by iron0012** [rstudio/rstudio#3449]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      :  macOS 10.12.6 
    R Version       : 3.5.1

### Steps to reproduce the problem
Open multiple editor tabs in Rstudio. Use the mouse to click-drag the tabs into a different order (different relative horizontal position in the tabs bar). Using the middle wheel to cycle through the tabs will now cycle through the tabs in the old (incorrect, imo) order rather than the new order.

### Describe the problem in detail
Normally, when scrolling with the mouse wheel while holding the mouse pointer over the tabs bar at the top of the Rstudio editor section, the tabs will be "brought to the front" in the order that they appear in the tabs bar--that is, left to right (if scrolling down with wheel) or right to left (if scrolling up with wheel). I believe that this is the desired and correct behavior. 

However, if I manually click and drag my tabs into a new order (that is, changing their relative positioning in the tabs bar) and then scroll with the mouse wheel, the tabs are cycled through and "brought to the front" in the _order that they had previously been in, before they were manually dragged into a new order._  This is confusing to me, and I don't think that it is the desired and expected behavior. Rather, I would have thought that scrolling tabs with the mouse wheel should cycle through the tabs in the new order in which they appear in the tabs bar, rather than the old order.

### Describe the behavior you expected
The mouse wheel should scroll through tabs in their new order of visual appearance in the Rstudio editor's tabs bar.

**Comment by lotard** [comment]
I can confirm this happens.

I use a keyboard shortcut to cycle through the tabs and get the same problem - they cycle in the original order, not the order assigned manually by dragging-and-dropping.

**Comment by gtritchie** [comment]
Also a potential accessibility issue. DOM order should match visible layout.
