### ISSUE TITLE
Unable to open R scripts return with a error: no such file or directory

### ISSUE THREAD

**Issue by khanuzair680** [rstudio/rstudio#3453]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Ubuntu 18.04 LTE
    R Version       : 3.4.4

### Describe the problem in detail
Today I opened R studio to work on my project but opening the previously saved R script return with an error saying no such file or directry. Moreover I tried to open new script but the Edit area is greyed out with no response. Sonsole is working fine as expected but I can not write R scripts

### Describe the behavior you expected
R scripts to open and editable

**Comment by kevinushey** [comment]
Was the underlying file on the filesystem deleted? (E.g. you were working on a network filesystem but that NFS is no longer mounted)

**Comment by khanuzair680** [comment]
No. I was still able to retrieve data from the console but was unable to open the R Script to run from there. However, I had to create a new project which was opened the R script wondering what might be the problem.
