### ISSUE TITLE
RStudio Desktop reparses a Stan file each time the editor comes into focus

### ISSUE THREAD

**Issue by bgoodri** [rstudio/rstudio#3454]
### System details

    RStudio Edition : Desktop
    RStudio Version : **Daily**
    OS Version      :  Debian Stable
    R Version       :  3.5.1

### Steps to reproduce the problem

1. Click File -> New File -> Stan Script
2. Make an edit that triggers a parser warning, such as writing `# THE END` at the end of the file
3. Save the Stan program to the disk
4. Click in the editor window, click in the console, click in the editor window, click in the console, ...

The output in the console looks like
```
DIAGNOSTIC(S) FROM PARSER:
Warning (non-fatal): Comments beginning with # are deprecated.  Please use // in place of # for line comments.

DIAGNOSTIC(S) FROM PARSER:
Warning (non-fatal): Comments beginning with # are deprecated.  Please use // in place of # for line comments.

DIAGNOSTIC(S) FROM PARSER:
Warning (non-fatal): Comments beginning with # are deprecated.  Please use // in place of # for line comments.

...
```

### Describe the problem in detail

It appears as if RStudio is reparsing the Stan file every time the focus comes back to the editor, which results in duplicative messages being sent to the console.

### Describe the behavior you expected

RStudio should only parse the Stan program when the Check button is triggered.

**Comment by kevinushey** [comment]
The eager re-parsing of Stan files is intentional -- this is how we flag and note errors on the editor surface; the intention here is to provide diagnostic notes as-you-type so the user can know relatively quickly if the Stan code they're writing has errors (e.g. they have a mis-spelling somewhere).

That said, we should be capturing these messages so that they don't pollute the R console itself.

**Comment by kevinushey** [comment]
The console pollution should now be fixed -- thanks for testing @bgoodri!

**Comment by kevinushey** [comment]
Can you please file this separately with a reproducible example?
