### ISSUE TITLE
Extra whitespace in editor after some rmd chunks

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3456]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1.x, 1.2.969
    OS Version      : macOS 10.13.6
    R Version       : 3.4.3

### Steps to reproduce the problem
- Create a new R Markdown file
- Insert an R chunk someone in the middle of the document, as shown below, and run it:

![2018-09-11_10-22-30](https://user-images.githubusercontent.com/10569626/45376429-a0b4b580-b5ac-11e8-9f94-e078f09ab1c0.png)

### Describe the problem in detail
Lots of whitespace below the output, but only in the editor. If you then knit it, the output does not have this extra whitespace.

![2018-09-11_10-25-12](https://user-images.githubusercontent.com/10569626/45376606-191b7680-b5ad-11e8-8f4d-89ccdba85964.png)

### Describe the behavior you expected
No extra whitespace in editor.

Note: This concern was raised in Pro support ticket 29678

**Comment by jjallaire** [comment]
I think the problem here is that we don't know how high DT is going to be (it typically has flowing height rather than fixed height).
