### ISSUE TITLE
Feature: Protect against displaying large items in Viewer

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#3459]
### Describe the problem in detail

At present, typing `View(my_massive_object)` will send the IDE into struggle-land trying to visualize the enormous object that I just passed it. (Large matrices, data.frames, etc.)

### Describe the behavior you expected

Instead, it would be nice to protect against such a mistake by offering a pop-up modal that says "Are you sure?" (And probably with a default of "No" that cancels the operation). On the server products, it might even be worth disabling the Viewer at a certain size (since you are in a multi-tenant environment) or allowing the administrator to customize this value.

You might imagine `if (size > x); modal()`

The other discussion here was about plotting massive objects... not sure if that would be something the IDE has hooks into or if that would belong in `ggplot2` or some other package, etc. Worth keeping on the radar though!

Credit for the FR goes to twitter:
https://twitter.com/michael_chirico/status/1038340227167703041

And @MichaelChirico! Thanks for the idea!

**Comment by bakaburg1** [comment]
The problem occurs only for large data sets (many columns) not for long (many rows). Because rows are loaded as you scroll down while columns get all loaded at once. So a solution could be implementing lazy loading for columns in addition to rows (I guess it would be a little pain with filters and sorting though).

**Comment by jmcphers** [comment]
We now limit a kind of lazy loading for columns (though it's manual); by default only the first 50 columns will be displayed, and you can page in more if needed.
