### ISSUE TITLE
RStudio Editor underlines the last argument to non-existent functions

### ISSUE THREAD

**Issue by bgoodri** [rstudio/rstudio#3474]
### System details

    RStudio Edition : Desktop
    RStudio Version : **Daily**
    OS Version      :  Debian Unstable
    R Version       :  3.3

### Steps to reproduce the problem

Click File -> New File -> Stan Script

After line 28, write something like

```
real z = foo(mu, sigma);
```

### Describe the problem in detail

The RStudio Editor correctly flags the line number and if you hover over the red x, it says "No matches for: Function foo not found". But the red underline goes under the last argument to this non-existent function, initially suggesting there is something wrong with the sigma argument. It looks like
```
real z = foo(mu, sigma);
                 ------
```

### Describe the behavior you expected

In my opinion, the red underline should go under the function name if either the function does not exist or is not being called with appropriate arguments, like
```
real z = foo(mu, sigma);
         ---
```

**Comment by kevinushey** [comment]
This is basically because that's what the Stan parser tells us:

`````
> rstan::stanc("~/scratch/Untitled.stan")
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

No matches for: 

  foo(real, real)

Function foo not found.
  error in 'model182524029287f_Untitled' at line 26, column 26
  -------------------------------------------------
    24: 
    25: transformed parameters {
    26:   real z = foo(mu, sigma);
                                 ^
    27: }
  -------------------------------------------------

Error in rstan::stanc("~/scratch/Untitled.stan") : 
  failed to parse Stan model 'Untitled' due to the above error.
`````

We could manually fix this on the RStudio side but perhaps the Stan diagnostic should point directly at the function name `foo` here?

**Comment by bgoodri** [comment]
OK, so basically the RStudio underline goes up to the `^`? I will see if we can do something about that on the Stan side. Thanks.

**Comment by kevinushey** [comment]
We actually parse the position from this text:

      error in 'model182524029287f_Untitled' at line 26, column 26

The primary bit we'd need is for that to change to the position of the `foo` name.
