### ISSUE TITLE
Incorrect column name displayed in RStudio View of a matrix object

### ISSUE THREAD

**Issue by David-Howe** [rstudio/rstudio#3481]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.383, 1.0.143
    OS Version      :  Windows 7, CentOS
    R Version       :  3.5.1, 3,3,3

### Steps to reproduce the problem
1. Create a key vector, an Id vector with "x" as one of the values and a numerical vector of the same length
2. Represent the 3 vectors as a sparse matrix by first converting the key and Id vectors to factors
3. Convert to a dense matrix
4. View the dense matrix and observe if the "x" column has been renamed with the name of the dense matrix object.

Reproduce using the following code:
```{r}
sparseMatrixCategoricalWrapper <- function(id_col, key_col, value_col=NULL)
{
  library(Matrix)
  
  i <- as.factor(id_col)
  j <- as.factor(key_col)
  
  if(is.null(value_col)) {
    sm <- sparseMatrix(i=as.integer(i), j=as.integer(j), dimnames=list(levels(i), levels(j)))
  } else {
    sm <- sparseMatrix(i=as.integer(i), j=as.integer(j), x=value_col, dimnames=list(levels(i), levels(j)))
  }
  return (sm)
}

dc <- c("a","b","c","a","b","c","a","b","c","a")
dr <- c("w","x","y","z","w","x","y","z","w","x")
dv <- c(1,2,1,2,1,2,1,2,1,2)

sm <- sparseMatrixCategoricalWrapper(dc, dr, dv)
msm <- as.matrix(sm)

sm
msm
colnames(msm)
View(msm)

# Is the heading for the second column in the View "x" or "msm"?
# In RGui the column in the View is "x"
```

### Describe the problem in detail
RStudio appears to be replacing a dense matrix column name of "x" with the object name of the dense matrix.

### Describe the behavior you expected
For the code example above, I expected to see "x" as the column name of column 2.  RGui displays this column name correctly.
[matrix_bug_test.R.txt](https://github.com/rstudio/rstudio/files/2383876/matrix_bug_test.R.txt)

**Comment by jmcphers** [comment]
This is a result of a quirk in the way value substitution is done when building the data viewer. It's currently being tracked in https://github.com/rstudio/rstudio/issues/3304.
