### ISSUE TITLE
File download extension lost with integrated browser on Windows

### ISSUE THREAD

**Issue by alandipert** [rstudio/rstudio#3483]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

Run the following Shiny app and look at it in the RStudio browser:

```R
library(shiny)

ui <- downloadLink('downloadData', 'Download')

server <- function(input, output) {
  output$downloadData <- downloadHandler(
    filename = function() {
      paste('data-', Sys.Date(), '.csv', sep='')
    },
    content = function(con) {
      write.csv(mtcars, con)
    }
  )
}

shinyApp(ui = ui, server = server)
```
Then click on `Download` and notice that the file name in the Windows save dialog is `downloadData` and not a `.csv` file.

### Describe the problem in detail

Shiny's `downloadHandler` function accepts a `filename` function that can be used to specify the name of the file once downloaded. Most browsers seem to respect this, while RStudio's builtin browser on Windows does not.

This problem was originally reported on Shiny at https://github.com/rstudio/shiny/issues/1562

### Describe the behavior you expected

I expected the file name to be something like `data-2018-09-14.csv` but it was `downloadData` instead.

**Comment by ronblum** [comment]
In 1.2, the file suggested file name is now correct (`data-2018-09-17`). However, it is still missing the `.csv` extension.
