### ISSUE TITLE
Unexpected behavior when adding a theme with same name as existing theme

### ISSUE THREAD

**Issue by jacob-long** [rstudio/rstudio#3485]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.992
    OS Version      :  Windows 10 (latest stable)
    R Version       : 3.5.1

### Steps to reproduce the problem

Add a theme (let's say it's called `foo` and from file `foo.tmTheme`). Make some arbitrary change to `foo.tmTheme` and save as `foo(1).tmTheme`. Add `foo(1).tmTheme` to RStudio through global options.

### Describe the problem in detail

Basically, the changes to `foo` do not propagate. What seems to be happening is RStudio saves both  theme files and continues to use the first one. When you remove the theme, to get it to leave the list of  available themes you will have to use the remove button as many times as you have added themes of the same name. 

*Side note*: I don't know the selection logic for the multiple files. It might select the first added, the first/last modified, the first alphabetical filename, or something else. I didn't tinker very much with the filenames and so on to figure this out, but it wouldn't surprise me if there might be some case where a re-added theme would have its changes propagate.

### Describe the behavior you expected

I expect either some change to the list that reflects the existence of duplicated themes or for the most recently added theme to overwrite any existing theme by that name. Maybe an "are you sure?" type prompt would be appropriate in those cases.

**Comment by ronblum** [comment]
@jacob-long Thank you for raising this issue!

**Comment by kevinushey** [comment]
Should be fixed up with https://github.com/rstudio/rstudio/pull/3547 -- thanks for reporting!
