### ISSUE TITLE
Equation Previews in Rmd Overlap and Inconsistency in Equation Inline Viewing

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#3486]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423 
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

1. In the global options/Rmarkdown choose "Show equation and image previews" "Inline"
2. Create an Rmarkdown document that has moderate complexity (just pasting a lot of equations into a simple template document doesn't work)
3. Add many equations in a row.

### Describe the problem in detail

The equation previews overlap the code and make the code unreadable.

![image](https://user-images.githubusercontent.com/10359931/45589737-ffee2f00-b8f8-11e8-986f-2eb686c529fe.png)

Note that in this example:
* the equations from lines 350-351 have no preview (one issue),
* 352-353 look good,
* the equation from line 354 overlaps the text of 355 (major issue),
* line 355 is invisible (major issue), and
* The equation from line 355 is visible.

### Describe the behavior you expected

The equations show between lines of code or text.

**Comment by kevinushey** [comment]
Can you please provide the contents of your .Rmd file (or a similar one that exhibits a similar issue), so that we might easily attempt to test the issue locally as well?

**Comment by jmcphers** [comment]
Sorry, we'll need a reproducible example to fix this -- please feel free to reopen if you have one!
