### ISSUE TITLE
rJava loads in Terminal, not in Console (RServer/Ubuntu)

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#3491]
I'm on RStudio server.

`library(rJava)` fails on the `Console` tab:

![screen shot 2018-09-17 at 12 33 15 pm](https://user-images.githubusercontent.com/7606389/45606294-94ca6700-ba76-11e8-80f6-c4349eba273d.png)

but succeeds in the `Terminal` tab:

![screen shot 2018-09-17 at 12 33 32 pm](https://user-images.githubusercontent.com/7606389/45606301-9bf17500-ba76-11e8-9e96-98b108033092.png)

`sessionInfo()` & `JAVA_HOME` in both are identical:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1 
```

I've tried running `sudo R CMD javareconf` in both tabs to no apparent effect.

**Comment by MichaelChirico** [comment]
I think this is related some staleness....

This is created as part of a `Docker` image that is run with some mounted persistent memory. This memory is re-persisted on shutdown of the image.

I have a feeling there may be some leftover files being copied back and forth that are interfering with the session in `Console` being able to load correctly.... not sure how to confirm this suspicion though...

**Comment by jmcphers** [comment]
This is probably an issue with `LD_LIBRARY_PATH` or similar, but we can't generally offer support for rJava and friends here (this issue tracker is for bugs in RStudio itself). I'd suggest asking on our community site:

https://community.rstudio.com/c/rstudio-ide

**Comment by MichaelChirico** [comment]
@jmcphers I don't think so, as simply `rstudio-server stop` and then `rstudio-server start` solves the problem.

I don't think this is a problem with `rJava` per se, and I do think it's entirely an RStudio issue... however I agree at this point it's not much of a _bug_ 🐛 on RStudio's part as much as it's my own fault. 

[Redirected here](https://community.rstudio.com/t/erasing-stale-files-to-get-rjava-working-on-docker/14485)
