### ISSUE TITLE
`Show output inline for all R Markdown documents` needs more granularity

### ISSUE THREAD

**Issue by statsandthings** [rstudio/rstudio#3492]
New feature request. `Show output inline for all R Markdown documents` needs more granularity

### Steps to reproduce the problem
In the `R Markdown` section of the R Studio `Tools -> Global Options` there is a selection *'Show output inline for all R Markdown documents'*. I'd like to see more granularity. In particular I'd like to see two options

`Show CONSOLE output inline for all R Markdown documents` toggle on/off
`Show IMAGE output inline for all R Markdown documents` with separate toggle on/off

### Describe the behavior you expected
If I highlight a selection `mtcars` and <kbd>Ctrl+Enter</kbd> I want the data frame to be output to the console. But, at the same time if I highlight `plot(mtcars)` and <kbd>Ctrl+Enter</kbd> I want the image plot to stay inline on the R Markdown document. Right now I can only pick one or the other.

I don't like the data frame style that is currently inline on my R Markdown document if I elect to `Show output inline for all R Markdown documents`. I have to scroll left/right to see all variables, when I just want the list like my console shows. I also don't want to scroll up and down in my source pane to see my code and it's output. I prefer my source pane in one window. And a separate console window beside the source with it's output.

**Comment by ronblum** [comment]
@statsandthings Thanks for the suggested enhancement. We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by skranz** [comment]
I also think more granularity would be a great enhancement. I also like plots inline but no other lengthy output. With the new visual markdown mode it would also be great if one could specify inline output for the visual mode but turn it off for the source edit mode.
