### ISSUE TITLE
knit fails with variable quoted

### ISSUE THREAD

**Issue by JsizzleR** [rstudio/rstudio#3493]
The following works for knitr/rmarkdown but not R notebook:

`knitr::opts_chunk$set(connection = db)`

This works for R notebook but not knitr/rmarkdown:

`knitr::opts_chunk$set(connection = "db")`

![image](https://user-images.githubusercontent.com/27960665/45632880-68a9e880-ba6c-11e8-95cd-757d4041b07c.png)

**Comment by ronblum** [comment]
I'm noticing somewhat different behavior in #3259.

**Comment by kevinushey** [comment]
Worth noting that the documented way is without quotes: https://bookdown.org/yihui/rmarkdown/language-engines.html#sql

We should try to align with that behavior.
