### ISSUE TITLE
Local images are broken in documentation preview tooltips

### ISSUE THREAD

**Issue by lionel-** [rstudio/rstudio#3494]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : macOS 10.13.4
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Use auto-completion with a function whose documentation contains local figures. For instance `rlang::invoke()` with the current development version of rlang installed from github.

2. Wait for the documentation tooltip to appear. The local images are broken.

### Describe the problem in detail

The local images are not shown and I see this in the web log:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:14897/figures/lifecycle-soft-deprecated.svg
```

![screen shot 2018-09-17 at 17 17 28](https://user-images.githubusercontent.com/4465050/45633116-467d8e00-ba9f-11e8-83b7-a1d2a1aef791.png)

### Describe the behavior you expected

I expected to see the local images as in the documentation pane.

**Comment by kevinushey** [comment]
In the daily builds of RStudio, it looks like we sanitize HTML altogether and so the icon doesn't show up at all:

![screen shot 2018-09-18 at 10 45 33 am](https://user-images.githubusercontent.com/1976582/45706010-fdc1e580-bb2f-11e8-99bd-d3965b13f4f5.png)

**Comment by lionel-** [comment]
Ah too bad, @hadley liked the badges in the tooltips. There is an alternative that I set with `\\ifelse{html}{}{}` for when html is disabled, would it be possible to display it instead? That probably requires generating the documentation as text.

**Comment by kevinushey** [comment]
The current help pipeline we have depends pretty heavily on HTML output (we parse and extract pieces of the HTML output as appropriate) so it's unlikely that we'll make that change.

I think the better fix for us is simply to appropriately parse image references and display them appropriately for local images.
