### ISSUE TITLE
Sequences not supported inside backticks

### ISSUE THREAD

**Issue by marciz** [rstudio/rstudio#3496]
### System details

    RStudio Edition : Desktop
    RStudio Version :1.2.981 
    OS Version      : Windows Server 2012 x64 & Windows 7 x64
    R Version       : 3.5.1

### Steps to reproduce the problem
\`ā\` <- 1
### Describe the problem in detail
Error: \uxxxx sequences not supported inside backticks (line 1)

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1

**Comment by ronblum** [comment]
@marciz Thank you for reporting this issue! We'll review it as we work on ongoing development of RStudio.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.

**Comment by MislavSag** [comment]
I am having this problem in latest Rstudio version. It return error:
`Error: \uxxxx sequences not supported inside backticks (line 1)`
when I have UTF-8 (Croatian) characters in variable names.

**Comment by ronblum** [comment]
@MislavSag Before possibly reopening this issue, can you please provide the following? Thanks!
1) Sample code that results in the error, so that we can attempt to reproduce it; and
2) The configuration you are running:

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by MislavSag** [comment]
I have just installed new version or R (3.6.0).

Right now it is working properly. Not sure what was the problem. I will send session_info if the error will appear again.

RStudio Edition : ?
RStudio Version : 1.2.1335
OS Version : Windows 7 x64
R Version : 3.6.0.

**Comment by ronblum** [comment]
@MislavSag Good to hear that it's working now! And yes, session info would be great if it returns. Thanks!

**Comment by YiRongZhuang** [comment]
![image](https://user-images.githubusercontent.com/49897997/71509291-ca8b0c00-28c5-11ea-96d9-e5910d7b51f3.png)
RStudio Version : 1.2.1335
OS Version : Windows 10 x64
R Version : 3.6.2.

tell me why?and Compile to pdf without problems！

**Comment by eleprocha** [comment]
Hey guys unexpected error that i face for the 1st time , any help?
Error: \uxxxx sequences not supported inside backticks (line 1)

**Comment by kevinushey** [comment]
Reproducible example:

```
> Sys.setlocale(locale = "English")
> data.frame(`行业分类` = 1)
Error: \uxxxx sequences not supported inside backticks (line 1)
```

Note that this reproduces in both RGui and RStudio. This works if you use a Chinese locale, however.
