### ISSUE TITLE
Add command to clear (forget) deployments

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3497]
The development version of the `rsconnect` package includes a method which can be used to erase knowledge of prior deployment(s) of an application or file.

https://github.com/rstudio/rsconnect/issues/267

This can be useful to clear out stale or irrelevant past deployments, if e.g. the content has been long since deleted on the server (currently there's no mechanism which can automatically clean up client knowledge in this case). 

We should add a small affordance for invoking this method from RStudio, so that it's not necessary to issue R commands to clean up stale deployment records.

**Comment by kevinushey** [comment]
@jmcphers do you have an idea of where this UI affordance would best live?

**Comment by jmcphers** [comment]
The `RSConnectPublishButton` has a menu of past content deployments -- I think we could just add an entry to that menu.
