### ISSUE TITLE
Full screen project restored to incorrect location

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#3498]
(At least on the mac)

1. Open a project
2. Make it full screen by double clicking the title bar
3. Close the project
4. Re-open the project

The the project window is offset 25 pixels from the left, instead of 0 pixels (and the overall width is 25 pixels less than it should be)

(Version 1.2.921; installing daily to check now, but internet is slow here)

**Comment by hadley** [comment]
Still happens in 1.2.992

**Comment by kevinushey** [comment]
This issue was caused by the fix we made in https://github.com/rstudio/rstudio/issues/3159. Will need to revisit and think of a better fix.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
