### ISSUE TITLE
Depend on CRAN version of rsconnect package

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3499]
We're currently embedding the development version of the rsconnect R package in order to pick up a few features (see recent [publishing issues](https://github.com/rstudio/rstudio/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Apublishing). 

Prior to the release of 1.2, we need to ensure that the new rsconnect package (0.8.9) goes to CRAN, and that we depend on the CRAN version instead of the local embedded copy.

**Comment by dfalty** [comment]
Verified fixed 1.2.1312.
