### ISSUE TITLE
some Help text is not visible with dark themes

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3500]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.993
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Try viewing the documentation for the `options()` function with `?options`.

### Describe the problem in detail

Some text (particularly, those describing options) is not visible. I selected one 'header' that is not visible here:

![screen shot 2018-09-18 at 11 24 44 am](https://user-images.githubusercontent.com/1976582/45708139-855e2300-bb35-11e8-8bf5-29315970eb0a.png)

### Describe the behavior you expected

Text should remain visible and appropriately styled in dark themes.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.

**Comment by rdinter-usda** [comment]
I'm running into a similar issue with chunk previews on darker themes. Using Tomorrow Night Bright it looks like no output:
![6c9e6706-1d7e-4cb7-83b9-cf8c2b2aa19e](https://github.com/rstudio/rstudio/assets/82044401/570131c9-38b1-4f93-b43f-1ceea83a87b9)
While if I switch over to the Tomorrow theme the preview is visible:
![2fac63bf-6b6b-4113-a41e-bbbdf0ca12f5](https://github.com/rstudio/rstudio/assets/82044401/4f0668c6-a295-4722-a32a-d80ef395446d)
