### ISSUE TITLE
Reformat Current Selection (Ctrl + Shift + A) doesn't work in rmarkdown chunk

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#3502]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      :  Fedora 27
    R Version       :  3.5.1

### Describe the problem in detail
Selecting a block of code and hitting Ctrl + Shift + A results in different formatting depending on if the block of code in a rmarkdown chunk vs a regular R script. Unfortunatly, in a rmarkdown chunk, the code losses all indentation. Screenshots attached

### Describe the behavior you expected
Identical reformatting applied in a knitr chunk as in a plain R script

Using a dplyr README example:
After hitting Ctrl+shift+A in a plain .R file
![image](https://user-images.githubusercontent.com/8462255/45769595-1bfe1300-bc0e-11e8-9641-ef7372e78ab4.png)

Copy and pasting that code into a .Rmd and indentation is preserved:
![image](https://user-images.githubusercontent.com/8462255/45769624-2d471f80-bc0e-11e8-84fd-1857bad0a75c.png)

Highlighting that code in an Rmd and pressing Ctrl+Shift+A losses the indentation. Ideally it would result in the same indentation as when the reformatter is applied in an R file.
![image](https://user-images.githubusercontent.com/8462255/45769692-5bc4fa80-bc0e-11e8-9043-1cdd0eeabda0.png)

**Comment by kevinushey** [comment]
Can you reproduce the issue in the latest [daily builds](https://dailies.rstudio.com/) of RStudio?

**Comment by t-kalinowski** [comment]
Nope, it works in the daily! Thanks!
