### ISSUE TITLE
Request Log Hotkey can't be unbound

### ISSUE THREAD

**Issue by plynch-chwy** [rstudio/rstudio#3503]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.453 
    OS Version      : macOS High Sierra 10.13.6 (17G65)
    R Version       : 

### Describe the problem in detail
I rebound ``Ctrl+` `` macOS shortcut to navigate through active windows. RStudio uses this shortcut for "Request Log", which can't be unbound through "Modify Keyboard Shortcuts...".

### Describe the behavior you expected
The keyboard shortcut for "Request Log" is available to be re/unbound in the "Modify Keyboard Shortcuts..." editor.

**Comment by ronblum** [comment]
@plynch-chewy Thanks for raising this; I've marked this as an enhancement for us to review as we continue to develop RStudio.
