### ISSUE TITLE
signature tooltip is 'sticky'

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3504]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.998
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Try typing the following:

```R
identity(identity())
```

### Describe the problem in detail

The signature tooltip pops up, but is 'sticky' and does not go away even after navigating the cursor outside of the inner `identity()`'s parentheses:

![screen shot 2018-09-19 at 11 06 55 am](https://user-images.githubusercontent.com/1976582/45772311-24e5e900-bbfc-11e8-8d7b-4e919536746f.png)

### Describe the behavior you expected

The tooltip should be dismissed after the cursor leaves the associated function's parentheses.

Marking as v1.2 milestone as this issue is supremely annoying when it occurs.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
