### ISSUE TITLE
deploying plot causes rsconnect uninstall

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3508]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.997
    OS Version      : macOS High Sierra 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Start with an empty R library, such as can happen when upgrading R. The `rsconnect` package is not installed for this version of R but had been used with previous versions of R. There are pre-existing deployment accounts and deployment records.

View a simple plot in the *Plots* pane.
```r
plot(sin, -pi, 2*pi)
```

Leave the plot in the *Plots* pane. Go to the Console and install `rsconnect` with `install.packages`. After installing `rsconnect`, the Console was used to successfully deploy a number of pieces of content. Now, back to the plot...

Attempt to deploy this plot by selecting the "Publish" dropdown the "Publish Plot...". Target this plot to an RStudio Connect instance, name it, then attempt to publish the content.

### Describe the problem in detail

Deploying the plot produce the following error in the *Deploy* pane:

```
Error in loadNamespace(name) : there is no package called ‘rsconnect’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

Attempting to re-plot the data does not resolve the problem.

After trying to reproduce this issue, I realized that going through the publication flow produce the following output to the *Console*:

```
Error installing package: ERROR: dependency ‘openssl’ is not available for package ‘rsconnect’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rsconnect’
```

I'm also seeing the "install missing packages" button in the publishing UI.
<img width="451" alt="screen shot 2018-09-19 at 9 32 24 pm" src="https://user-images.githubusercontent.com/362187/45790596-943af780-bc53-11e8-94d0-1a4dcee93fde.png">
All my previously connected accounts show up but I'm told that things are not right.

Clicking that button performs no work but causes it to immediately disappear. Closing then reopening the preferences window shows the "missing packages" state again.

This last bit is likely because the R session was not restart after rsconnect was removed (??!!).

Restart the R session and revisit the publishing settings and we see:
<img width="461" alt="screen shot 2018-09-19 at 9 34 54 pm" src="https://user-images.githubusercontent.com/362187/45790678-014e8d00-bc54-11e8-9042-49cb1dce7aa4.png">

Ok. Click the button!
<img width="453" alt="screen shot 2018-09-19 at 9 35 05 pm" src="https://user-images.githubusercontent.com/362187/45790682-07446e00-bc54-11e8-8325-81bfe5d167a0.png">

Oy. Drop back to the console, install the package with `install.packages("rsconnect")`, restart the R session, and the publishing pane is fine again.

Go back, plot, and try to publish the plot. `rsconnect` is removed!

### Describe the behavior you expected

Plots should deploy without uninstalling `rsconnect`.

I can successfully deploy content using the `rsconnect::deploy*` functions.

**Comment by aronatkins** [comment]
I should note that this is _almost_ a pristine R 3.5.1 install with the latest RStudio daily. I've installed `shiny`, `rmarkdown`, and `plumber` from CRAN (testing different content deploys) but otherwise have very little installed.

**Comment by aronatkins** [comment]
Trying to better understand this...

`remove.packages("rsconnect")`
restart RStudio
open the publishing preferences pane

observe that no deployment records are shown; click the "install missing packages" button.
<img width="461" alt="screen shot 2018-09-19 at 9 34 54 pm" src="https://user-images.githubusercontent.com/362187/45790955-6bb3fd00-bc55-11e8-9dbe-2e7c216a7ac1.png">

Confirm that these packages should be installed.
<img width="611" alt="screen shot 2018-09-19 at 9 45 29 pm" src="https://user-images.githubusercontent.com/362187/45790950-65be1c00-bc55-11e8-81d4-efaab5aa77f2.png">

The installing window briefly pops up then disappears. I was unable to capture its output. The publishing pane is left in a "install missing packages" state and lists no connected accounts.

It feels like the automatic installation of `rsconnect` by the IDE isn't happening and if I install from CRAN things like plot deploys do not work. I'm going to leave my environment in this state through tomorrow in case that will help folks diagnose what's going on.

**Comment by jmcphers** [comment]
I think this is a regression from https://github.com/rstudio/rsconnect/pull/116, as we're bundling the dev version of rsconnect now and probably need to sync the IDE with the new dependency list. I should have a fix shortly.

**Comment by ronblum** [comment]
@aronatkins Are you able to confirm that it works? It works for me in 1.2.1007, but then I wasn't able to get it to properly fail in 1.2.997.

**Comment by aronatkins** [comment]
I manually installed `openssl` and confirmed that it resolved my plot-deploy issue. I have not wiped my R library to confirm a new build.
