### ISSUE TITLE
RStudio freezes when saving files into a VirtualBox mount

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rstudio#3512]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.981
    OS Version      : Fedora 28
    R Version       : 3.5.0

### Steps to reproduce the problem

RStudio is installed in a VirtualBox guest (Fedora 28). The host is Windows 10, and there are some shared folders mounted into the guest.

- Open a new file.
- Write more than 1024 characters (up to 1024, there seems to be no problem).
- Save the file into a vboxsf filesystem (a VBox shared folder).

Then RStudio freezes with a high CPU consumption, and the file is never completely written.

**Comment by jmcphers** [comment]
Are you able to save files from other applications (e.g. nano)?

**Comment by Enchufa2** [comment]
Yes: vim, atom, others... without any problem.

**Comment by ronblum** [comment]
@Enchufa2 Does this still occur in the latest dailies?

**Comment by Enchufa2** [comment]
Never tried again, because it was annoying. :) I'll check later today with the latest one and report back.

**Comment by Enchufa2** [comment]
Build 1106, same issue.

**Comment by jmcphers** [comment]
We've not been able to reproduce this (or had any other reports) in over a year, so closing.
