### ISSUE TITLE
auto-detect dependencies for package development

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3513]
We recently implemented some tooling for automatic discovery of packages used within R scripts, and prompt users to install those as required. It would be useful to implement something similar for R packages, to automatically install any R packages that are imported or suggested by the current package.

This was prompted by some frustration in attempting to build a package on a newly installed machine: each attempt to build the package would fail, with one package out of each in the set of dependencies failing to load during e.g. vignette build.

We could even use the same UI, but perform the parsing when opening the `DESCRIPTION` file. Also, rather than installing packages from CRAN, we might instead use `devtools::install_dev_deps()` to ensure that remotes are so on are respected.

**Comment by jjallaire** [comment]
I usually handle this via `devtools::install_deps()` --- I think that once package developers know about this then IDE tooling might be overkill (as it's very easy to execute this command).

**Comment by jmcphers** [comment]
As @jjallaire noted there's already very usable tooling for this so it's not likely to be implemented in the next couple of years (compared to the long list of other enhancements we'd like to make!)
