### ISSUE TITLE
nit: GPU driver workarounds wording

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3516]
Per @jmcphers:
> have it say "Enable GPU driver bug workarounds" and default to true.

    RStudio Edition : Desktop
    RStudio Version : 1.2.1004

**Comment by kevinushey** [comment]
I'm still on the fence on this one as the default behavior is to have GPU driver workarounds enabled, and the text here also matches the underlying Chromium flag (`--disable-gpu-driver-bug-workarounds`).
