### ISSUE TITLE
Rendering Engine selector can appear off-screen

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3517]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1004
    OS Version      : macOS 10.13.6 High Sierra
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Launch the IDE while attached to external monitor.
2. Open the Options window.
3. Browse to General -> Advanced.
4. Disconnect from external monitor.
5. Reconnect external monitor.
6. Attempt to select an alternate rendering engine.

### Describe the problem in detail

The rendering engine selector can appear outside the RStudio UI. Depending on the position of the IDE before disconnecting/reattaching the external monitor, the selector may be off-screen.

![screen shot 2018-09-20 at 5 15 41 pm](https://user-images.githubusercontent.com/362187/45847375-d9fdcb80-bcf8-11e8-80d5-2a98255332e4.png)

Resize/moving the RStudio IDE lets the selector be rooted to its expected location.

### Describe the behavior you expected

The selector drop-down should appear in the Options window connected to the rendering engine label.

**Comment by aronatkins** [comment]
Displays:
![screen shot 2018-09-20 at 5 17 37 pm](https://user-images.githubusercontent.com/362187/45847454-1b8e7680-bcf9-11e8-85d3-cec4ff2b25ac.png)

More HW information:
![screen shot 2018-09-20 at 5 18 01 pm](https://user-images.githubusercontent.com/362187/45847475-2f39dd00-bcf9-11e8-8f75-56e024bae192.png)

**Comment by aronatkins** [comment]
GPU diagnostics:

Data exported | 2018-09-20T21:19:00.074Z
-- | --
Chrome version | RStudio/1.2.1004
Operating system | Mac OS X 10.13.6
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/65 35ee3617fcb08e0d79e6b9e6c05db23cc9416d4f-
Command Line | /Applications/RStudio.app/Contents/MacOS/RStudio --enable-webgl-software-rendering --enable-viewport --disable-renderer-accessibility --disable-prefer-compositing-to-lcd-text --browser-subprocess-path=/Applications/RStudio.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess --enable-threaded-compositing --disable-zero-copy --disable-gpu-memory-buffer-compositor-resources --disable-gpu-memory-buffer-video-frames --disable-mojo-local-storage --disable-accelerated-video-decode --disable-pepper-3d-image-chromium --disable-native-gpu-memory-buffers --enable-features=AllowContentInitiatedDataUrlNavigations --disable-features=SurfaceSynchronization --disable-features=SurfaceSynchronization,TouchpadAndWheelScrollLatching --disable-gpu

**Comment by kevinushey** [comment]
I've seen this issue in other applications (especially Qt application) when the monitor configuration changes; especially in cases where a window that was originally on a high DPI monitor is moved to a regular DPI monitor as a result of plugging in (or unplugging) a monitor.

I don't think it's worth chasing this one down for RStudio v1.2; I'm moving this to v1.3.
