### ISSUE TITLE
Undo after find&replace

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#3525]
Original bug report Dec 2013 [here](https://support.rstudio.com/hc/en-us/community/posts/200633278-Undo-after-replace-all),
It's easy to find&replace the whole script rather than just the selection (and indeed a separate bug would be that the 'in selection' option deselects itself), and undo doesn't work. Apparently there's a workaround but I've only just found this and have lost loads of time to this as have many others. Please can this be fixed?

Cheers

**Comment by jmcphers** [comment]
I've confirmed that this reproduces on our latest build (1.2.1007), so is still an issue. Thanks for the report!

**Comment by jmcphers** [comment]
This is now being tracked in https://github.com/rstudio/rstudio/issues/3422; it's the same underlying issue (namely that replace in the whole script causes the whole editor contents to mutate at once)
