### ISSUE TITLE
RStudio Preview fails to parse multibyte characters on non-UTF-8 MBCS Windows

### ISSUE THREAD

**Issue by yutannihilation** [rstudio/rstudio#3526]
The stable version of RStudio is fine, but with the preview version, I got following errors related to multibyte strings. Note that, `source()`ing and `reprex::reprex()` works fine with the very same code. So, I suspect something is wrong in the preview version of RStudio.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.981
    OS Version      :  Windows 10
    R Version       :  3.5.1
    Locale          : Japanese_Japan.932

### Steps to reproduce the problem

```r
# this works, so multibyte characters are basically OK
data.frame("Φ" = 1)

# But this won't
data.frame(Φ = 1)

# This won't work, too
data.frame(`Φ` = 1)

# Hmm...?
data.frame(`ç`` = 1)

# Hmmmm...??
data.frame(`ç` = 1)
```

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/1978793/45916130-df474b80-be9b-11e8-9fd6-da7eb9252409.png)

### Describe the behavior you expected

- First three should work
- Forth should be treated as incomplete `` ` ``
- Fifth should work (But I guess I can't stop `ç` is transtated into `c`)

**Comment by marciz** [comment]
#3496

**Comment by yutannihilation** [comment]
Ah, sorry, I didn't notice the issue. May I close this?

From the errors, it seems multibyte characters are all escaped into `\uxxxx` form before being passed to th R session. I mean, this:

``` r
data.frame("Φ" = 1)
data.frame(Φ = 1)
data.frame(`Φ` = 1)
```

is recoginzed as this:

``` r
data.frame("\u03a6" = 1)
data.frame(\u03a6 = 1)
data.frame(`\u03a6` = 1)
```

**Comment by kevinushey** [comment]
The issue here is a bit more complicated than I expected. Compare, for example:

### RStudio v1.1

```R
> "Φ"
[1] "F"
> "ā"
[1] "a"
```

### RStudio v1.2

```R
> "Φ"
[1] "Φ"
> "ā"
[1] "ā"
```

So it looks like RStudio v1.2 is no longer performing transliteration in some contexts. Note that this isn't true in general; e.g.

```R
> data.frame("Φ" = 1)
  F
1 1
```

and AFAIK this is because R always enforces that symbols must be represented in the native encoding, and so attempts to use them in that context will force their conversion.

I guess we want to preserve v1.1 behavior for now, and force transliteration of text where possible?

**Comment by yutannihilation** [comment]
Oh, I didn't notice inputing foreign characters is so tough on latin1 locale... This is what I see on RStudio v1.1:

![image](https://user-images.githubusercontent.com/1978793/46044321-6410be80-c155-11e8-93a2-84f769530c7f.png)

**Comment by kevinushey** [comment]
Indeed; I was surprised to learn that many APIs for converting characters will transliterate by default (for transliterations defined in the active locale), even though it's a lossy conversion.

**Comment by yutannihilation** [comment]
Thanks! I confirmed v1.2.1013-1 works as before.

![image](https://user-images.githubusercontent.com/1978793/46238913-5153ef00-c3cc-11e8-8eb4-ff912909d056.png)
