### ISSUE TITLE
Cursor position suddenly wrong

### ISSUE THREAD

**Issue by ozika** [rstudio/rstudio#3530]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.456
    OS Version      :  Linux Mint 18.3
    R Version       : 3.5.1

### Steps to reproduce the problem
Turn on, type anything in the editor.

### Describe the problem in detail
I installed RStudio ~2 months ago and until today it worked fine. Now all of a sudden the cursor is consistently offset to the right of the text I am editing. If I start a new editor window and just type the same letter it seems that the cursor moves by a small position to the right with each entry and is therefore increasingly offset the longer the text gets. 

1. The output of sessionInfo() 
2. The R code in question
3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

Thank you for taking the time to file an issue!  -->

**Comment by kevinushey** [comment]
Best guess -- the original monospace font you were using is no longer installed, and RStudio has defaulted to a non-monospace font. Unfortunately, non-monospace fonts are not supported by the RStudio editor.

Can you confirm whether changing the font back to a monospace font in RStudio makes a difference?

**Comment by wlandau** [comment]
I am seeing a similar issue when I open Emacs in a terminal window. As far as I know, I am using Emacs' default monospace font. Should I set a different font in `~/.emacs`? Any particular fonts likely to work?

![reprex](https://user-images.githubusercontent.com/1580860/53259587-6db73780-369d-11e9-9dcc-7ee627fd590b.gif)

**Comment by kevinushey** [comment]
@wlandau I suspect yours is a separate issue since this is specifically with Emacs in an RStudio terminal. Can you please file it as a separate issue (with details about your version of RStudio, OS, and so on)?

**Comment by wlandau** [comment]
Sure. Just posted #4349.

**Comment by jmcphers** [comment]
We never heard back from the original poster, so closing this issue.

**Comment by kmshort** [comment]
In Rstudio linux, latest version, my cursor has to be above and to the to click or select text, click a menu item, or drag bar. It makes Rstudio impossible to use. If I can select a menu item, drop down menus are fine, and I can hover the mouse directly over them.

**Comment by ronblum** [comment]
@kmshort What operating system are you using?
