### ISSUE TITLE
Start Rstudio 1.2.1004 shows nothing. 

### ISSUE THREAD

**Issue by maikol-solis** [rstudio/rstudio#3531]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1004 
    OS Version      :  openSUSE Leap 15.0
    R Version       :  3.5.0 (2018-04-23)

### Steps to reproduce the problem
- Install Rstudio 1.2 in OpenSUSE 15. 
- Open Rstudio

### Describe the problem in detail
In a XPS 13 9360, with OpenSUSE 15 and KDE 5, a fresh installation of Rstudio doesn't show anything unless I press 
Help -> Diagnostics -> Reload UI. 

This behavior happens when I close and start Rstudio (every time). 

The diagnostics-report shows this 

```
24 Sep 2018 16:15:36 [rsession-maikol] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE/open-source-pipeline/master/src/cpp/session/SessionMain.cpp:1328
24 Sep 2018 16:22:38 [rsession-maikol] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE/open-source-pipeline/master/src/cpp/session/SessionMain.cpp:1328
```

### Describe the behavior you expected
Show the initial dashboard of rstudio.

**Comment by jmcphers** [comment]
@ronblum can you reproduce this?

**Comment by kevinushey** [comment]
FWIW I was able to get RStudio up and running on a VM running openSUSE Leap 15.1 without any issue.

![screen shot 2018-09-26 at 3 57 19 pm](https://user-images.githubusercontent.com/1976582/46113851-e5437200-c1a4-11e8-8803-f9d22977b83b.png)

**Comment by ronblum** [comment]
Same as @kevinushey, on openSUSE 15.0 with R 3.5.0, both with the original image and latest updates.

**Comment by jmcphers** [comment]
We're closing this since we haven't heard back in a few months and weren't able to reproduce (feel free to reopen if you're still having trouble or have more details!)
