### ISSUE TITLE
External plot zoom window scaling issue

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#3533]
RStudio version: (all the dailies have had this for a while)
Platform: my cranky mac that hates GPUs

I've been hesitating to post this since every time I try to record a screencast of it in-action it doesn't do it, but when i (not on purpose) use the corner-drag on a popped-out plot window and manage to only move it perfectly (not any mouse jitter in the orthogonal direction) horizontally or vertically the graphic skews vs resizes. When I resize it again (via corner) and ensure it is in both directions it rescales fine. 

I'm posting this in the event its happening to others (a quick search didn't show me anything similar but it was a quick search).

This is also a super low priority issue, but it may be indicative of other Qt issues that that window is inheriting.

**Comment by pascaloettli** [comment]
Do you mean something like this?

![screenshot from 2018-09-26 09-52-38](https://user-images.githubusercontent.com/6613954/46050976-f2933900-c171-11e8-83cf-6c3243292be8.png)

**Comment by hrbrmstr** [comment]
that certainly looks like the skewing i get (tho i can't reproduce it at-will)

**Comment by ronblum** [comment]
@hrbrmstr and @pascaloettli Does this issue still occur in the latest dailies?

**Comment by pascaloettli** [comment]
@ronblum Yes

**Comment by hrbrmstr** [comment]
aye

**Comment by ronblum** [comment]
@hrbrmstr and @pascaloettli is this still an issue in the current 1.2 release? And, since you've used the dailies, in 1.3? Thanks!

**Comment by pascaloettli** [comment]
> @hrbrmstr and @pascaloettli is this still an issue in the current 1.2 release? And, since you've used the dailies, in 1.3? Thanks!

Sorry for the late reply. Here is what I noticed on my computer:

Using a simple `plot(1,1)`
`1.2.5034`: still an issue
`1.2.5036`: still an issue
`1.3.723`: not an issue

I will come back if I notice an issue in `1.3` with more complex plots

**Comment by ronblum** [comment]
@pascaloettli Thank you! Since it appears to be fixed in 1.3, which we're actively working on,  I'll close the issue. But if you do run into it again, please let us know!
