### ISSUE TITLE
RStudio notebook fails to print all output without warning that something is missing (v1.2.1004) 

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#3536]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1004
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Open new notebook document;
2. Delete everything;
3. make editor window small enough to fit only one string per row;
4. Create new chunk with code `data.frame(x = rep("a--------------------------a", 1000))$x`
5. Notice that some output is missing.

### Describe the problem in detail

Only a fraction of output is printed in output window:
![image](https://user-images.githubusercontent.com/12725868/46011737-895ae980-c0cf-11e8-8749-de9ef291d690.png)

![image](https://user-images.githubusercontent.com/12725868/46011752-937ce800-c0cf-11e8-829c-eb47df6feb26.png)

### Describe the behavior you expected

I expect `[1000] a--------------------------a` as one of the last lines, e.g. print-screen from console:

![image](https://user-images.githubusercontent.com/12725868/46011950-43525580-c0d0-11e8-8a86-bf8bd780bd63.png)

I.e. **All output is expected** (maybie a scrolling bar should appear?).
Otherwise error message should appear announcing that all output couldn't be printed in the notebook and you should look for it in console.

**Comment by GegznaV** [comment]
I installed v1.1. It prints all the lines as expected.

**Comment by ronblum** [comment]
Confirmed in comparison between RStudio Desktop 1.2.1004-1 and 1.1.456 on MacOS Mojave 10.14.

**Comment by kevinushey** [comment]
Note that all the text _is_ there; it's just that the content is not scrollable. IIRC, this was an explicit decision because the overall feel when attempting to scroll in the editor surface vs. within an HTML widget was awkward.

cc: @jmcphers

**Comment by GegznaV** [comment]
>  this was an explicit decision because the overall feel when attempting to scroll in the editor surface vs. within an HTML widget was awkward.

I still can't understand, why avoiding "awkward feeling while scrolling" is superior to having ability to see all the output. Why is it better to have some output hidden without warning and pretend as if all the output was displayed? It can lead to possibly incorrect real life decisions made on incomplete information when one thought that one had complete information.

Any ideas, how this issue could be solved? I.e., is there any progress towards solving the issue?

**Comment by jmcphers** [comment]
In 1.1, we didn't implement two scrolling regions; instead, we just let the content get arbitrarily long.

![image](https://user-images.githubusercontent.com/470418/48450563-90ab8480-e75b-11e8-8792-c3cc099c581d.png)

However, letting content get arbitrarily long has downsides; see https://github.com/rstudio/rstudio/issues/2174. To fix that issue, in 1.2, we cap the height of the output at 650px, even if the content itself is longer.

https://github.com/rstudio/rstudio/commit/ba227cc38024f16f3e098a52056b94e58871b3d9#diff-5ec5e068ab7ed519e5573e7fd0b7ac08

See here for discussion:

https://github.com/rstudio/rstudio/pull/2533

I think it's pretty clear that we don't want dual scrollbars here as they're a UX nightmare. I wonder if this needs to be more contextual; that is, *only* clamp the height when the content has an HTML widget, as HTML widgets introduce iframes and scrolling behavior that doesn't play nicely when it takes over the editor.
