### ISSUE TITLE
Tomorrow night bright theme makes <dt> tags in help files invisible

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#3537]
* RStudio preview 1.2.981
* Modern theme
* Tomorrow night bright editor theme

If you look at `?strptime`, you'll notice that the abbreviations in the `Details` section are not shown on the left hand side unless you highlight over them. This happens in a number of other packages too.

I don't know if this affects all dark themes.

How it looks with this theme:

![screen shot 2018-09-25 at 10 34 01 am](https://user-images.githubusercontent.com/19150088/46021391-96b3ac00-c0ae-11e8-998a-7f84b1704f1a.png)

When you highlight over it:

![screen shot 2018-09-25 at 10 34 06 am](https://user-images.githubusercontent.com/19150088/46021404-9e735080-c0ae-11e8-8407-3c27049752ed.png)

**Comment by pascaloettli** [comment]
Which OS? And which editor font? Did you try using another font? I am on Ubuntu 18.04 with `RStudio v. 1.2.1008` and I cannot reproduce.

```
RStudio theme:    Modern
Zoom:             100%
Editor font:      Ubuntu Mono
Editor font size: 9
Editor theme:     Tomorrow Night Bright

```

**Comment by jmcphers** [comment]
I think this is the same as https://github.com/rstudio/rstudio/issues/3500. Can you try the preview release and confirm that it's fixed there?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by DavisVaughan** [comment]
You're right! Sorry for not researching the past issues enough.
