### ISSUE TITLE
stuck "searching for definition"

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3543]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.2.1008
    OS Version      : macOS Mojave 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Not really sure. I selected some code in an editor pane and went to copy it to the clipboard.

### Describe the problem in detail

The IDE UI is stuck with:

<img width="203" alt="screen shot 2018-09-26 at 9 53 46 am" src="https://user-images.githubusercontent.com/362187/46084622-18204280-c172-11e8-9dfb-441ea3e09124.png">

Editor panes and the console _appear_ functional but as soon as you take some operation that needs to run R code, everything hangs.

Attempting to restart R gives:

<img width="207" alt="screen shot 2018-09-26 at 9 56 14 am" src="https://user-images.githubusercontent.com/362187/46084770-70efdb00-c172-11e8-9681-e63f81392b40.png">

Attempting to terminate R also fails.

### Describe the behavior you expected

I was trying to copy text, so may have been an error on my part, but I did not expect a long-running definition lookup.

**Comment by aronatkins** [comment]
Quitting (triggered either from the File menu or right-clicking the Dock icon) also does not work; needed to force-quit.

**Comment by aronatkins** [comment]
It's possible that there was a leftover `rsession` consuming oodles of CPU after force-quitting the IDE itself. I have not been able to reproduce this issue yet, so I cannot confirm.

**Comment by kevinushey** [comment]
Normally, definition lookup is triggered by pressing <kbd>F2</kbd>. Do you have a sense for what kind of R objects you had in your environment, or where the cursor was, when that dialog popped up?

**Comment by aronatkins** [comment]
I doubt that I hit `F2`.

Almost nothing in the environment.

The code (that I had just selected for copy/paste):

```r
connect$fixupPackageHashes("packrat")
```

The `connect` object _may_ have been in the environment but cannot be sure. I was mostly using the IDE for editing and then running the code from a separate terminal using `Rscript`. I was debugging a `packrat` interaction with my code and wanted untainted R sessions.

The `connect` object was created by: `source("../path/to/connect.R")` and inside there, we:

```r
connect_buildHelpers <- function() { 
    fixupPackageHashes <- function(packratDir) { ... }
    # ...
    return (list(
        # ...
        fixupPackageHashes = fixupPackageHashes,
        # ...
    ))
}
connect <- connect_buildHelpers()
```

**Comment by ronblum** [comment]
@aronatkins Is this still a problem with the current or preview release?

**Comment by aronatkins** [comment]
Have not seen this problem since originally filing the issue, including the most recent daily - 1.3.338.

**Comment by ronblum** [comment]
@aronatkins Thanks!

**Comment by abalter** [comment]
This is still a problem. Happens to me all the time in rstudio server.
