### ISSUE TITLE
"Find in Files" not finding anything.

### ISSUE THREAD

**Issue by ProfFancyPants** [rstudio/rstudio#3548]
### System details
Restarting R session...
>  str(sessionInfo())
List of 9
 $ R.version :List of 14
  ..$ platform      : chr "x86_64-w64-mingw32"
  ..$ arch          : chr "x86_64"
  ..$ os            : chr "mingw32"
  ..$ system        : chr "x86_64, mingw32"
  ..$ status        : chr ""
  ..$ major         : chr "3"
  ..$ minor         : chr "5.1"
  ..$ year          : chr "2018"
  ..$ month         : chr "07"
  ..$ day           : chr "02"
  ..$ svn rev       : chr "74947"
  ..$ language      : chr "R"
  ..$ version.string: chr "R version 3.5.1 (2018-07-02)"
  ..$ nickname      : chr "Feather Spray"
 $ platform  : chr "x86_64-w64-mingw32/x64 (64-bit)"
 $ locale    : chr "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.125"| __truncated__
 $ running   : chr "Windows >= 8 x64 (build 9200)"
 $ basePkgs  : chr [1:7] "stats" "graphics" "grDevices" "utils" ...
 $ loadedOnly:List of 2
  ..$ compiler:List of 9
  .. ..$ Package    : chr "compiler"
  .. ..$ Version    : chr "3.5.1"
  .. ..$ Priority   : chr "base"
  .. ..$ Title      : chr "The R Compiler Package"
  .. ..$ Author     : chr "Luke Tierney <luke-tierney@uiowa.edu>"
  .. ..$ Maintainer : chr "R Core Team <R-core@r-project.org>"
  .. ..$ Description: chr "Byte code compiler for R."
  .. ..$ License    : chr "Part of R 3.5.1"
  .. ..$ Built      : chr "R 3.5.1; ; 2018-07-02 09:08:53 UTC; windows"
  .. ..- attr(*, "class")= chr "packageDescription"
  .. ..- attr(*, "file")= chr "C:/Program Files/R/R-3.5.1/library/compiler/Meta/package.rds"
  ..$ tools   :List of 11
  .. ..$ Package         : chr "tools"
  .. ..$ Version         : chr "3.5.1"
  .. ..$ Priority        : chr "base"
  .. ..$ Title           : chr "Tools for Package Development"
  .. ..$ Author          : chr "R Core Team"
  .. ..$ Maintainer      : chr "R Core Team <R-core@r-project.org>"
  .. ..$ Description     : chr "Tools for package development, administration and documentation."
  .. ..$ License         : chr "Part of R 3.5.1"
  .. ..$ Suggests        : chr "codetools, methods, xml2, curl"
  .. ..$ NeedsCompilation: chr "yes"
  .. ..$ Built           : chr "R 3.5.1; x86_64-w64-mingw32; 2018-07-02 09:08:52 UTC; windows"
  .. ..- attr(*, "class")= chr "packageDescription"
  .. ..- attr(*, "file")= chr "C:/Program Files/R/R-3.5.1/library/tools/Meta/package.rds"
 $ matprod   : chr "default"
 $ BLAS      : chr ""
 $ LAPACK    : chr ""
 > attr(*, "class")= chr "sessionInfo"
>   str(R.Version())
List of 14
 $ platform      : chr "x86_64-w64-mingw32"
 $ arch          : chr "x86_64"
 $ os            : chr "mingw32"
 $ system        : chr "x86_64, mingw32"
 $ status        : chr ""
 $ major         : chr "3"
 $ minor         : chr "5.1"
 $ year          : chr "2018"
 $ month         : chr "07"
 $ day           : chr "02"
 $ svn rev       : chr "74947"
 $ language      : chr "R"
 $ version.string: chr "R version 3.5.1 (2018-07-02)"
 $ nickname      : chr "Feather Spray"
>   RStudio.Version()$version
[1] ‘1.2.1010’

### Steps to reproduce the problem
Using Ctrl+Shift+F to find text in any folder.
![image](https://user-images.githubusercontent.com/7212413/46111389-d2389e00-c1b4-11e8-8524-311b4e36d664.png)

Result:
![image](https://user-images.githubusercontent.com/7212413/46111589-93efae80-c1b5-11e8-9d15-a798c4f506c9.png)

From the log it is saying that grep is having an error. I assume it is because the 'C:/Program" path was not quoted.

> 26 Sep 2018 21:44:00 [rsession-DefaultUser-WS] ERROR grep: 'C:/Program' is not recognized as an internal or external command,
> |||operable program or batch file.
> |||; LOGGED FROM: void __cdecl rstudio::session::modules::find::`anonymous-namespace'::GrepOperation::onStderr(const class rstudio::core::system::ProcessOperations &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) c:\jenkins\workspace\ide\windows\src\cpp\session\modules\sessionfind.cpp:411

### Describe the problem in detail
Adding diagnostic report:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2421696/diagnostics-report.txt)

**Comment by ProfFancyPants** [comment]
This happened after version "RStudio-1.2.1007.exe
I just downgraded and it is working again.

**Comment by kevinushey** [comment]
This might be an unintended side-effect of the locale change we made :-/

**Comment by ProfFancyPants** [comment]
No worries. I have made the same mistake myself a bunch of times we calling from the command line. The path to the grep file being called just needs to be quoted.

**Comment by dfalty** [comment]
I was able to reproduce this on Win10 with version 1.2.1009. Does not reproduce with RStudio Server (Ubuntu 16) or Mac.

**Comment by dfalty** [comment]
Verified fixed in 1.2.1013.
