### ISSUE TITLE
Multiple/stacked audio calls crash RStudio (win & linux)

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#3549]
Finally realised that my code was crashing not because of the complexity of my analyses, but because I was looping functions which contain audio notifications for stage progress, and it was going so quickly that the notification are crashing RStudio. Possibly something like a queue of commands being unable to clear fast enough, overrunning a buffer / memory allocation and crashing? IDK enough about programming so this is me talking out of my arse but hopefully it helps.

To reproduce:

```
install.packages("beepr")
require(beepr)

c(rep(beep(2),10), beep(8))

Error in rep(beep(2), 10): attempt to replicate an object of type 'externalptr'
This might be irrelevant but also might be the hidden root of the problem? Anyway:

for(i in 1:10){
  for(i in 1:10){
    beep(2)
    beep(2)
    beep(2)
    beep(2)
    beep(2)
    beep(2)
    beep(2)
    beep(2)
    beep(2)
    beep(2)
    beep(8)
  }
}
```

**Comment by kevinushey** [comment]
I can reproduce this in a plain R session:

```R
kevin@zordon:~/scratch
$ R --vanilla --slave -e 'rep(beepr::beep(2), 10)'
Error in rep(beepr::beep(2), 10) :
  attempt to replicate an object of type 'externalptr'
Execution halted
```

So I believe that whatever is going on is independent of RStudio.
