### ISSUE TITLE
Git for Projects not working after updating to MacOS Mojave

### ISSUE THREAD

**Issue by jimmyday12** [rstudio/rstudio#3550]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : MacOS Mojave 10.14
    R Version       : 3.4.4

### Steps to reproduce the problem
After updating to MacOS Mojave, the Git pane has disappeared from all my projects that previously were under version control and had a working Git pane. 

Also new projects can no longer be started under version control.

#### New Projects

1. File > New Project
2. Version Control
3. Git

This produces the following error. 

![rstudio](https://user-images.githubusercontent.com/17557361/46119087-dadcb300-c24c-11e8-9890-830d87c98837.jpg)

When I go to the preferences pane, the Git Exectuable path is `/usr/bin/git` which seems correct (I'm not sure how to check this?). I can click on Browse and select git from the finder window and it doesn't make a difference.  

![rstudio](https://user-images.githubusercontent.com/17557361/46126113-564f5c00-c26f-11e8-889f-e613eea11acf.jpg)

#### Existing Projects
If I go to an existing project that was under version control previously, the Git pane no longer exists. If I check it in the project setup following these steps

1. Tools > Version Control > Project Setup

Then the Version Control System dropdown only has 'None' as an option

![__documents_r_scripts_fitzroy_-_rstudio](https://user-images.githubusercontent.com/17557361/46119253-7d953180-c24d-11e8-81b3-cff00bc9b43c.jpg)

#### Git with Console
For existing projects that were previously under version control, I can use Git with the console perfectly fine. It can push, pull, commit and stage and it all works as expected. It is just the Git UI panel and the UI for setting up new projects that isn't working. 

### Describe the behavior you expected
My previously setup projects worked with Git and had the Git UI pane in R Studio. I could set Git up in the Project Setup section. Updating to MacOS Mojave seems to have broken this setup somehow.

**Comment by ronblum** [comment]
@jimmyday12 I'm unable to reproduce the issue on Mojave, both with R 3.4.4 and 3.5.1. What version of Xcode are you using? `/usr/bin/xcodebuild -version`

@kevinushey Any thoughts?

**Comment by kevinushey** [comment]
After installing Mojave, you likely been to reinstall command line tools (and friends). Try running:

```
xcode-select --install
```

from the command line. You can also try running:

```
/usr/bin/git --version
```

as I believe that will also prompt to install if command line tools aren't available.

**Comment by jimmyday12** [comment]
Ah yes - it did seem that xcode was the issue! 

Running `xcode-select --install` worked for me.

Thanks for the help

**Comment by Ifeanyi-Owah** [comment]
Running xcode-select --install worked for me too.

Thanks

**Comment by RosanneScholl** [comment]
This worked for me too. (I had to restart R Studio before seeing the Git tab come back.)
