### ISSUE TITLE
Shadow graphics device error: r error 3 (Expression parsing error)

### ISSUE THREAD

**Issue by venpopov** [rstudio/rstudio#3553]
### System details

    RStudio Edition : 
    RStudio Version : 1.2.1009
    OS Version      :  x86_64-w64-mingw32/x64 (64-bit) Windows >= 8 x64 (build 9200)
    R Version       : 3.5.1 (2018-07-02)

### Steps to reproduce the problem

Open Rstudio and type `plot(cars)` in the console

### Describe the problem in detail

After updating Rstudio to the 1.2.1009 version, now suddenly I get the following error when trying to plot anything:

> Error in RStudioGD() : 
>   Shadow graphics device error: r error 3 (Expression parsing error)

After running debug(plot), I found that this happens when trying to open a new plotting device. The same error message occurs when running `dev.new()`

This is not a problem with R itself. Plotting works fine in the R.exe console.

I can't reproduce it on another computer, however. When I updated Rstudio on my laptop, which has the same Windows & R versions, it works fine. The previous Rstudio version (1.1.456) works fine on both machines. Downgrading to that previous version fixes the issue.

The main difference between the two machines is that the one with the problem doesn't have a dedicated GPU. I'm attaching the GPU diagnostics report from the machine in which the problem occurs. I suspect, though am not sure, that this might be the key issue: 

> GPU process was unable to boot: GPU access is disabled through commandline switch --disable-gpu.

...

> Graphics Feature Status
> Canvas: Software only. Hardware acceleration disabled
> CheckerImaging: Disabled
> Flash: Software only. Hardware acceleration disabled
> Flash Stage3D: Software only. Hardware acceleration disabled
> Flash Stage3D Baseline profile: Software only. Hardware acceleration disabled
> Compositing: Software only. Hardware acceleration disabled
> Multiple Raster Threads: Disabled
> Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
> Rasterization: Software only. Hardware acceleration disabled
> Video Decode: Software only. Hardware acceleration disabled
> WebGL: Disabled
> WebGL2: Disabled
> Problems Detected
> GPU process was unable to boot: GPU access is disabled through commandline switch --disable-gpu.
> Disabled Features: all
> Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
> Disabled Features: native_gpu_memory_buffers
> Checker-imaging has been disabled via finch trial or the command line.
> Disabled Features: checker_imaging
> Version Information
> Data exported	2018-09-27T16:39:26.446Z
> Chrome version	rstudio/1.2.1009.0
> Operating system	Windows NT 6.2.9200
> Software rendering list URL	https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/software_rendering_list.json
> Driver bug list URL	https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/gpu_driver_bug_list.json
> ANGLE commit id	unknown hash
> 2D graphics backend	Skia/65 35ee3617fcb08e0d79e6b9e6c05db23cc9416d4f-
> Command Line	"C:\Program Files\RStudio\bin\rstudio.exe" --enable-viewport --disable-renderer-accessibility --browser-subprocess-path="C:\Program Files\RStudio\bin\QtWebEngineProcess.exe" --no-sandbox --enable-threaded-compositing --disable-zero-copy --disable-gpu-memory-buffer-compositor-resources --disable-gpu-memory-buffer-video-frames --disable-mojo-local-storage --disable-es3-gl-context --enable-features=AllowContentInitiatedDataUrlNavigations --disable-features=SurfaceSynchronization --disable-features=SurfaceSynchronization,TouchpadAndWheelScrollLatching --disable-gpu
> Driver Information
> Initialization time	0
> In-process GPU	true
> Passthrough Command Decoder	false
> Direct Composition	false
> Supports overlays	false
> Sandboxed	false
> GPU0	VENDOR = 0x8086, DEVICE= 0x0102
> Optimus	false
> Optimus	false
> AMD switchable	false
> Desktop compositing	Aero Glass
> Diagonal Monitor Size of \\.\DISPLAY2	23.5"
> Diagonal Monitor Size of \\.\DISPLAY1	23.7"
> Driver vendor	Intel Corporation
> Driver version	9.17.10.4459
> Driver date	5-19-2016
> Pixel shader version	
> Vertex shader version	
> Max. MSAA samples	
> Machine model name	
> Machine model version	
> GL_VENDOR	
> GL_RENDERER	
> GL_VERSION	
> GL_EXTENSIONS	
> Disabled Extensions	
> Disabled WebGL Extensions	
> Window system binding vendor	
> Window system binding version	
> Window system binding extensions	
> Direct rendering	Yes
> Reset notification strategy	0x0000
> GPU process crash count	0
> Compositor Information
> Tile Update Mode	One-copy
> Partial Raster	Enabled
> GpuMemoryBuffers Status
> ATC	Software only
> ATCIA	Software only
> DXT1	Software only
> DXT5	Software only
> ETC1	Software only
> R_8	Software only
> R_16	Software only
> RG_88	Software only
> BGR_565	Software only
> RGBA_4444	Software only
> RGBX_8888	GPU_READ, SCANOUT
> RGBA_8888	GPU_READ, SCANOUT
> BGRX_8888	Software only
> BGRX_1010102	Software only
> BGRA_8888	Software only
> RGBA_F16	Software only
> YVU_420	Software only
> YUV_420_BIPLANAR	Software only
> UYVY_422	Software only
> Display(s) Information
> Info	Display[2528732444] bounds=0,0 1920x1080, workarea=0,0 1920x1040, scale=1, external
> Color space information	{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}
> Bits per color component	8
> Bits per pixel	24
> Info	Display[2779098405] bounds=1920,0 1920x1080, workarea=1920,0 1920x1040, scale=1, external
> Color space information	{primaries:[[0.4012,0.4026,0.1604,],[0.2042,0.7198,0.0760,],[0.0095,0.0486,0.7667,],], transfer:0.0000*x + 0.0000 if x < 0.0000 else (1.0000*x + 0.0000)**2.2000 + 0.0000, matrix:RGB, range:FULL}
> Bits per color component	8
> Bits per pixel	24
> Video Acceleration Information
> Diagnostics
> ... loading ...

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2424980/diagnostics-report.txt)

**Comment by kevinushey** [comment]
This should also be fixed in the latest [preview release](https://www.rstudio.com/products/rstudio/download/preview/) -- please update and let us know if you're still encountering issues.

**Comment by venpopov** [comment]
Yes - works fine in the latest release. Thanks!
