### ISSUE TITLE
"File changed" dialog prompts once per observed edit

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3554]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1009
    OS Version      : macOS Mojave 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

* Open a file in an IDE editor pane.
* Make an edit to that file but do not save.
* In your favorite non-RStudio editor, open that same file.
* Within that alternate editor, repeatedly make changes to the file then save your changes.
* Switch back to the IDE.

### Describe the problem in detail

The "File changed" dialog appears, allowing the user to optionally discard the edits in the IDE, as the file on-disk has changed. Choose to reload and discard.

<img width="428" alt="screen shot 2018-09-27 at 10 16 35 pm" src="https://user-images.githubusercontent.com/362187/46184466-c37ce480-c2a3-11e8-8343-7d6a5d724579.png">

The file-changed dialog appears multiple times - once per save operation by the other editor?

### Describe the behavior you expected

Only one "File Changed" dialog; multiple saves do not demand multiple dialog displays.

**Comment by kevinushey** [comment]
I can replicate this, but note that there is one more requirement -- you must be editing a file contained within the current active project; it does not reproduce if you follow these steps with a file that lives outside the current project.

**Comment by ronblum** [comment]
Is this the same as #3489?

**Comment by kevinushey** [comment]
Yes, I believe so.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
