### ISSUE TITLE
 Different Font Sizes in Editor and Output Window 

### ISSUE THREAD

**Issue by fabeit** [rstudio/rstudio#3555]
Feature request. 

I would like to have the font size in the editor and the R output windows to be different? I like larger font for coding and smaller font for the console.

**Comment by ronblum** [comment]
@fabeit Thanks for the suggested enhancement! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by jmcphers** [comment]
There's be no votes or support for this idea in over a year, so unlikely we'll get to it in the next couple of years.
