### ISSUE TITLE
Complete Python docstring delimiters

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#3557]
**Steps to reproduce:**
* Create a new Python file.
* Type a single quote character in the editor.

**Expected behavior:**
* Should insert closing quote resulting in `''`, just like it does when typing double quote or when doing the same thing in a .R file.

**Actual behavior:**
* Does not insert closing quote.

**Comment by kevinushey** [comment]
This is partially intentional -- auto-quoting for `'` would make Python multi-line strings annoying, e.g. typing `'''` (three single quotes) would insert `''''` (four single quotes).

**Comment by david-cortes** [comment]
> This is partially intentional -- auto-quoting for `'` would make Python multi-line strings annoying, e.g. typing `'''` (three single quotes) would insert `''''` (four single quotes).

I think it would also be better if typing `'''` would result in `'''<focus here>'''` like in jupyter with its auto-inserted closing quotes.
