### ISSUE TITLE
Documentation search not working for Python

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#3559]
**Steps to reproduce:**
* Enter Python interactive mode.
* Look for the documentation of something by typing two question marks, e.g. `??list`

**Expected behavior:**
* Should look up documented functions/classes/methods containing `list`.

**Actual behavior:**
* Displays `/python/%3Flist.html not found`

**Comment by kevinushey** [comment]
Where does this proposed behavior come from? We chose to model `?foo` to work similar to what users see with R; e.g. that opens the associated help documentation in the Help pane.

Is there a difference between what `?list` and `??list` should do?

**Comment by david-cortes** [comment]
> Where does this proposed behavior come from? We chose to model `?foo` to work similar to what users see with R; e.g. that opens the associated help documentation in the Help pane.
> 
> Is there a difference between what `?list` and `??list` should do?

Yes: in R, `?ggplot` will show the documentation for the function `ggplot`, provided that the package is loaded, while `??ggplot` will search the documentations of all the packages installed for matches with `ggplot`, regardless of whether the packages have been loaded or not.
