### ISSUE TITLE
Feature - close all terminals

### ISSUE THREAD

**Issue by hsselman** [rstudio/rstudio#3564]
### Feature description
First of all, I love the terminal integration in RStudio IDE. Thanks for that! I use it quite often lately. When I started scripting commando's to send to terminal windows, I came up with this feature. 
`Close Terminal` is already an option, but I would really appreciate a `Close all terminals` option. Now I have to close them by hand, or restart.

**Comment by hsselman** [comment]
Love the workaround to close the Terminal tab itself. That would work! 

I am using `rstudioapi` to launch commando's to the terminal. Love to see what you mean by creating an add-in.

**Comment by gtritchie** [comment]
Ok, here's an RStudio addin that provides a new command `Close All Terminals`. This command kills any processes running in the terminals without prompting, so use with caution. A fancier version could be created to only kill terminals that aren't busy, etc., but for now just did this.

Install from github via the devtools package.

```
devtools::install_github("rstudio/terminaltools")
```
There will be a new section on the Addins dropdown on the toolbar:

![2018-10-01_12-23-56](https://user-images.githubusercontent.com/10569626/46310698-f14c7c80-c574-11e8-8ea8-a906477df0a7.png)

You can add a keyboard shortcut via Tools / Modify Keyboard Shortcuts. Type "Close All Terminals" in the search box, then click on blank area under Shortcut to enter keysequence.

![2018-10-01_12-26-38](https://user-images.githubusercontent.com/10569626/46310823-42f50700-c575-11e8-9ebf-6c7c49fc17d1.png)

For more on creating addins, see https://rstudio.github.io/rstudioaddins/.
