### ISSUE TITLE
Occasional spurious warnings about column names being undefined symbols

### ISSUE THREAD

**Issue by gvwilson** [rstudio/rstudio#3567]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1013
    OS Version      :  MacOS High Sierra (10.13.6)
    R Version       :  3.5.1

### Steps to reproduce the problem

1. Clone <https://github.com/gvwilson/tidynomicon>.
2. Open the project.
3. Open `cleanup.Rmd`.
4. Edit any of the `r` blocks that use unquoted column names in called to `filter`.

Warnings about "no symbol named 'X' in scope" will intermittently appear, even though 'X' is a column name for the tibble being operated on. For example, in the example screenshotted below, `data` has a column called `lo`.

![screen shot 2018-10-01 at 9 14 48 am](https://user-images.githubusercontent.com/911566/46296982-9b260c00-c569-11e8-8ad9-23cf6bea628a.png)

### Describe the problem in detail

1.  The warnings appear intermittently, and continued editing of other blocks will occasionally make them disappear.
2.  Closing and reloading the file may also make them disappear. 

Note that I am occasionally turning triple-backquoted blocks without a language type into triple-backquoted blocks *with* the `{r}` specification, i.e., converting:

    ```
    ...some code goes here
    ```

into:

    ```{r}
    ...exactly the same code without modification
    ```

### Describe the behavior you expected

I did not expect warnings.

**Comment by gvwilson** [comment]
Another incidence of the above.  Code is:

```
find_empty_rows <- function(source) {
  read_csv(source) %>%
    pmap_lgl(function(...) {
      args <- list(...)
      all(is.na(args) | (args == ""))
    }) %>%
    tibble(empty = .) %>%
    mutate(id = row_number()) %>%
    filter(empty) %>%
    pull(id)
}
```

(nothing else in file) and warnings are:

![screen shot 2018-10-31 at 10 08 11 am](https://user-images.githubusercontent.com/911566/47793619-16a7e400-dcf5-11e8-9b15-377f9ff3e0d3.png)

The warning on line 8 is `argument 'x' is missing, with no defaults` and on line 9, `no symbol named 'empty' in scope`.  I have `library(tidyverse)`'d in my R session before writing this code, and it seems to run as expected.

**Comment by klmr** [comment]
It would be great if, in order to fix this, the RStudio static analyser became pluggable rather than hard-coding a workaround for dplyr/tidyeval, since the same problem affects other packages that rely on NSE in their API. I have no obvious solution in mind but maybe something along the same lines as `utils::rcompgen` might serve as inspiration.

**Comment by dvanic** [comment]
Are there any workarounds for this? I'm encountering it left, right and center in my machine learning teaching :cry:

**Comment by kevinushey** [comment]
It's not the nicest solution, but you can tell the diagnostics system to ignore certain variables as described in https://support.rstudio.com/hc/en-us/articles/205753617-Code-Diagnostics:

```
# !diagnostics suppress=<comma-separated list of variables>
```

**Comment by ivan-paleo** [comment]
I believe this is related, but let me know if this is not and I should rather create a new issue.

In my code, I have this warning at every line where I use a function that is not part of base R, e.g. tools::md5sum() (even though tools is loaded automatically via a namespace), reshape2::melt(), ggplot2::ggplot() and so on. In my script, the commands to load all the required packages via library() are located before, and it does not matter whether I have run these commands already or not.

I have the impression this is a rather new "bug".

I am using RStudio 1.3.959 on Win10.

**Comment by kevinushey** [comment]
@ivan-paleo: could you please file a new issue, and also share a screenshot of what exactly you're seeing in the IDE for clarity?

**Comment by ivan-paleo** [comment]
I thought a new issue would be better when I noticed that it behaves differently in a renv project.

**Comment by ivan-paleo** [comment]
I had forgotten back then to refer to the new issue I've created: https://github.com/rstudio/rstudio/issues/7318

**Comment by ivan-paleo** [comment]
It hasn't been solved yet even in the latest version. Inactivity doesn't mean solved :)

**Comment by aadler** [comment]
Issue still exists.

**Comment by jucor** [comment]
@gvwilson Is that really completed? I'm still seeing it in the Daily:  2023.08.0-daily+46 (2023.08.0-daily+46) . Is there an option I'm missing, please?
