### ISSUE TITLE
Feature request: SQL script default customization

### ISSUE THREAD

**Issue by boshek** [rstudio/rstudio#3569]
I am really appreciating the effort you folks are putting into SQL integration in rstudio. One small feature request.

Currently File -> New File -> SQL Script produces a script with a default connection like this:

```
-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

SELECT 1
```

This is a feature request to add the ability to change the defaults so that opening a script would connect to other databases a la:

```
-- !preview conn=DBI::dbConnect(RPostgres::Postgres())

SELECT 1
```

As per [this discussion](https://community.rstudio.com/t/default-connection-when-opening-a-sql-file/15244/3) the default is set here:

https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/cpp/session/resources/templates/query.sql#L1-L3

However path the customize via modifying that file is probably not the best approach.

**Comment by jmcphers** [comment]
Thanks for the request! We're tracking this holistically here:

https://github.com/rstudio/rstudio/issues/1632
