### ISSUE TITLE
Upgrade GNU Grep binary for Windows

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#3572]
GNU Grep 2.5.4. and OpenSSL 1.0.2 are being used in Windows but RStudio could consider upgrading the binaries to more recent equivalents.

**Comment by javierluraschi** [comment]
From @kevinushey: We could consider upgrade to something like ripgrep in the future: https://blog.burntsushi.net/ripgrep/

**Comment by javierluraschi** [comment]
If someone wants to grab this one off my plate, please do!

I'm just assigning it to me since I think this is something we need to fix in 1.3 as soon as we get the 1.3 builds going, this to give it some time to bake and catch regressions.

**Comment by kevinushey** [comment]
We specifically bundle grep on Windows since it's not available there by default, whereas on other systems we can just make use of the system-installed `grep` program. We use `grep` to power the Find in Files functionality.

We currently don't have any plans to upgrade the bundled version of OpenSSL on Windows for v1.2 (we're currently bundling v1.0.2m).

**Comment by jmcphers** [comment]
Since OpenSSL was updated in #3606, this is now just tracking updating Grep.

**Comment by jmcphers** [comment]
I strongly suspect that gnugrep was taken from here:

http://gnuwin32.sourceforge.net/packages/grep.htm

where 2.5.4 is, surprisingly, _still_ the latest version available. GnuWin hasn't released anything in 10 years. 

This is a problem since pcre3 is old enough to be considered a security problem by some scanners.

**Comment by melissa-barca** [comment]
This outdated version doesn't support several basic regexes see #7012

**Comment by melissa-barca** [comment]
I took some time to research this and it doesn't seem like there's a good option at this time. Surprisingly GnuWin seems to be the most popular option for grep for Windows even with its pitfalls. The only option I could find was using Cygwin's grep which would require shipping an additional 5 MB. 

Windows has its own command `Select-String` that has similar capabilities to `grep` and would fix the regex issues, but the command is fairly different and writing the code to support that doesn't make sense for 1.4. The command is also only available on machines with Powershell 7 (released in March). 

The best option is probably to follow Kevin's suggestion of using ripgrep (or something similar) and updating both the find and replace functionality to use the same command.

**Comment by kevinushey** [comment]
> The only option I could find was using Cygwin's grep which would require shipping an additional 5 MB.

FWIW, I would be okay with that -- RStudio is already pretty large as it is (and most of that is just source maps: https://github.com/rstudio/rstudio/issues/7157).

I'd be a bit concerned about issues that could arise with conflicting versions of cygwin getting loaded by RStudio in unexpected ways, though. (not sure if or how it could happen, but it seems like something that could)

**Comment by Ferretaa** [comment]
There is a GNU grep Version 3.0 here: 
http://adoxa.altervista.org/grep/

**Comment by mitchcapper** [comment]
@Ferretaa  good find! While that grep is fairly dated it fixes several of the issues. It does not have the recursive search bug in some of the other 3.x series where it would fail.  Coloring works, wildcard matching works, PCRE seems to work well too.  I have tried several binaries so this is the first one with all those features.

**Comment by kevinushey** [comment]
Is bundling the version of `grep.exe` from Rtools an option?

**Comment by jgutman** [comment]
I'm not super familiar with windows or with Rtools, but I just checked in Rtools4 and it has GNU grep 3.0, including the -E and -P flag. So I think that should work

**Comment by jgutman** [comment]
Can verify by installing on Windows (2022.06.0+22 or later), running Find in Files (Ctrl + Shift + F) and confirming that it finds or doesn't find matches as before. Also checked the installation directory (C:\Program Files\RStudio), navigating to C:\Program Files\RStudio\bin\gnugrep\3.0, and running `grep.exe --version` to confirm that grep is installed in the appropriate directory and is running version 3.0
