### ISSUE TITLE
WebGL does not work with some older Intel graphics cards

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3573]
https://community.rstudio.com/t/webgl-is-not-supported-by-your-browser-plotly/13962/20

---

### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1013-1
    OS Version      : macOS Sierra
    R Version       : 3.5.1

### Steps to reproduce the problem

Attempt to create a plotly plot, with e.g.

```R
library(plotly)
plot_ly(z = ~volcano) %>% add_surface()
```

### Describe the problem in detail

A message is shown:

> WebGL is not supported by your browser - visit https://get.webgl.org 4 for more info

### Describe the behavior you expected

WebGL graphics should work.

### Notes

The user in this case was running with a 2012 MacBook Air; with Intel Graphics 3000. WebGL graphics worked in RStudio v1.1, and also work in a regular browser (e.g. Chrome).

**Comment by kevinushey** [comment]
See also: https://bugreports.qt.io/browse/QTBUG-55604

**Comment by kevinushey** [comment]
Marking as v1.2 milestone but unless we hear of more reports we may just have to close as wontfix (since odds are we could only fix this with a Qt / Chromium update and that might not even be the panacea we need).

**Comment by cpsievert** [comment]
I was able to reproduce on a 2018 Macbook Pro with Radeon Pro 560X 4096 MB, Intel UHD Graphics 630 1536 MB. Here is the GPU diagnostics, let me know if there is any other way I can help!


Data exported | 2018-10-22T19:47:53.205Z
-- | --
Chrome version | RStudio/1.2.1040
Operating system | Mac OS X 10.13.6
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/65 35ee3617fcb08e0d79e6b9e6c05db23cc9416d4f-
Command Line | /Applications/RStudio.app/Contents/MacOS/RStudio --enable-webgl-software-rendering --enable-viewport --disable-renderer-accessibility --disable-prefer-compositing-to-lcd-text --disable-gpu-rasterization --browser-subprocess-path=/Applications/RStudio.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess --enable-threaded-compositing --disable-zero-copy --disable-gpu-memory-buffer-compositor-resources --disable-gpu-memory-buffer-video-frames --disable-mojo-local-storage --disable-accelerated-video-decode --disable-pepper-3d-image-chromium --disable-native-gpu-memory-buffers --enable-features=AllowContentInitiatedDataUrlNavigations --disable-features=SurfaceSynchronization --disable-features=SurfaceSynchronization,TouchpadAndWheelScrollLatching --disable-gpu

**Comment by kevinushey** [comment]
Can you please try the latest daily build (1.2.1040 is old now)

**Comment by cpsievert** [comment]
Working with 1.2.1069 🎉 

Any idea which version may have fixed it? I can track it down if you think it'd be helpful

**Comment by kevinushey** [comment]
I'm fairly sure it was fixed by https://github.com/rstudio/rstudio/commit/aa467b2c4773e583c0a06c6013d343a9c37491bc. (This assumes that you're using your laptop with an external display as well)

**Comment by brainprint** [comment]
It also works for me with the configuration shown in the images below.

![screen shot 2018-10-23 at 07 55 25](https://user-images.githubusercontent.com/17748369/47341617-69e8b980-d699-11e8-91b8-90e726005368.png)

![screen shot 2018-10-23 at 08 00 15](https://user-images.githubusercontent.com/17748369/47341768-cea41400-d699-11e8-825a-615d5f267c8e.png)

**Comment by kevinushey** [comment]
I'm going to close this -- to the best of my knowledge, only old Macbook Airs are affected, and users can work around the issue by opening the widget in the browser.

**Comment by GalenLee** [comment]
I have windows RStudio Version 1.2.5001.  I am sesing the same issue: not showing in RStudio, but saving as Web Page, it shows in browser.

**Comment by maenpaa24** [comment]
I am in the exact same situation as @GalenLee

**Comment by mirh** [comment]
https://github.com/pal1000/save-legacy-intel-graphics
The problem is likely this. 
It should have been worked around with qt webengine starting to use ANGLE, but for the moment the entire RS stack is stuck <5.13.

**Comment by zx8754** [comment]
Same issue with 1.2.5042, but setting `Tools>Global Options>Advanced>Rendering engine` to "Desktop OpenGL" fixes the issue.

Related SO post:
 - [Plotly error “WebGL is not supported by your browser”](https://stackoverflow.com/q/61241340/680068)

**Comment by dmeloso76** [comment]
I had the same problem on Windows machine with a newish release of R-Studio. The problem was not only with the Viewer in RStudio but persisted in the html produced from an RMarkdown. It was solved by replacing RStudio with an older version (1.1.463). Thus, the problem only appears with the release I had before (newest release about 6 months ago), and not with the older release I use now.
