### ISSUE TITLE
New color scheme compatible to ace editor

### ISSUE THREAD

**Issue by zib0** [rstudio/rstudio#3578]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.456
    OS Version      :  Mac OS X 10.12.6
    R Version       : 3.5.1

### Describe the problem in detail
Just wondering if RStudio could incluede this nice ayu theme, which compatible to the ace editor, at here: https://github.com/ayu-theme/ayu-ace
Thanks!

**Comment by jmcphers** [comment]
We'll consider this. In the meantime, though, you might try the [RStudio 1.2 preview](https://www.rstudio.com/products/rstudio/download/preview/), where you can add your own themes. Here's RStudio in Ayu Mirage!

![image](https://user-images.githubusercontent.com/470418/46364091-9d4f9f80-c629-11e8-84e5-6fd680c5f024.png)

You will need a .tmtheme to import to RStudio; you can find Ayu tmthemes here:

https://github.com/dempfi/ayu
