### ISSUE TITLE
Feature request: Enhanced Folding / Outline functionality

### ISSUE THREAD

**Issue by haakonstorm** [rstudio/rstudio#3581]
**Use case**
General use of Rstudio for longer R source files and specifically writing documents with Rmarkdown.

**Problem**
With longer documents, you can use the Fold Region functionality to collapse the document.
However, this is rendered as:

\```{r setup, results='hide', include=FALSE} :frog:```

The frog (:frog:) is a placeholder for the Folded text icon in the IDE.

**Solution**
I made a small video to show how I envision the IDE to function, courtesy of the mac app OmniOutliner. This would make the IDE really great for longer documents, and open up for a lot of other very user friendly additions:

https://www.youtube.com/watch?v=a-6Or-Et8SY&feature=youtu.be

When R code chunks are Folded, the first line in the chunk could be a comment, and that text would end up as the text for the line with the Folded chunk. If there are no comment on the first line, the name of the R chunk is used instead. If the chunk is unnamed, just "unnamed chunk 1".

I realize there is a lot of work to code something like this. It would nonetheless be a very useful change to how one could work within the IDE. 

*A faster way to the same end would be to extend the functionality of the Document Outline feature already impemented. The Document Outline could itself be a collapsable tree, and double-clicking elements here would Fold or Unfold the respective part of the source. Dragging elements up and down in the tree would reorder the source accordingly. Very useful for documents.*

Input?

(I first submitted this in the Rstudio community forum, here:
https://community.rstudio.com/t/descriptive-text-for-collapsed-regions/15366 )

*RStudio Desktop Version 1.1.456 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko)*

**Comment by brian-law-rstudio** [comment]
Hello. Another client made a similar and somewhat simpler request yesterday (hierarchical code folding) and so I am adding this note as a "seconded". 

Thank you.

**Comment by haakonstorm** [comment]
Hey, thanks a lot for remembering this feature request! I'm sure if it get smoothly implemented in the Rstudio editor it would become a very useful stand-out feature. Especially since Rstudio can be used as an awesome replacement for Microsoft Word, for instance. Add in an inline Tibble editor when writing Rmarkdown and you have something of a smart version of OneNote.
