### ISSUE TITLE
add multiple cursors should skip wrapped lines

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3586]
From Tareef:

> This is a long standing issue I have had with the IDE whenever I try to copy and paste a set of long lines, and then I multi-select, I would expect that the cursor would only type at the beginning of the line.  Instead, I find it adding the '*' at the beginning of the wrapped line.  I don't know if that is an issue with the paste function losing the fact that each line is too long and therefor it wraps, or whether it is the multi-cursor functionality that isn't quite right.   This bug is the reason you will sometimes see random asterisk signs in the middle of a bulleted list of items.

Specifically, when creating multiple cursors using <kbd>Ctrl + Alt + Up</kbd> and <kbd>Ctrl + Alt + Down</kbd>, we should skip wrapped lines (since the most typical intention is to e.g. edit multiple lines, all at the start of the line -- ignoring however it might be currently wrapped)

**Comment by ronblum** [comment]
@pascaloettli It's a little different, but a good point—would you be willing to open a new issue report for this?

**Comment by DesiQuintans** [comment]
Yes, only allowing multiple cursors on physical lines would be a huge improvement. The current behaviour is not hugely useful.

![multiple cursors](https://user-images.githubusercontent.com/3200601/56420732-81200100-62e2-11e9-9b16-5cb3b69742af.gif)
