### ISSUE TITLE
Bash chunks in rmarkdown documents on windows using WSL do not behave as expected

### ISSUE THREAD

**Issue by akiledal** [rstudio/rstudio#3589]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1015
    OS Version      :  Windows 10
    R Version       :  3.5.1

### Steps to reproduce the problem
1. Make a bash chunk in an rmarkdown document, which runs using the windows subsystem for linux (Ubuntu 18.04)
2. Run the chunk

### Describe the problem in detail
Executes properly, however output is shown in a WSL terminal that opens while running, and closes automatically when complete. This has happened in several of the latest versions of rstudio. Switched back to RStudio-1.2.901 because it is the last version I know to behave as expected.

![bug](https://user-images.githubusercontent.com/31629269/46430634-9737ec80-c717-11e8-8667-08852e07b466.png)

### Describe the behavior you expected

In previous versions, the output would be properly formatted in the rmarkdown document. 

![expected](https://user-images.githubusercontent.com/31629269/46430633-9737ec80-c717-11e8-87bf-0c65d4ac9f8e.png)

**Comment by kevinushey** [comment]
This is probably related to some of the changes I made around how processes are launched -- I'll take a look. Thanks for reporting!

**Comment by kevinushey** [comment]
Thanks again for reporting! This should be fixed in the next daily builds of RStudio and we'll continue to release new preview releases as fixes for these issues come in.

**Comment by akiledal** [comment]
Great, thanks for looking into this.
