### ISSUE TITLE
RStudio Preview rendering glitches

### ISSUE THREAD

**Issue by imanuelcostigan** [rstudio/rstudio#3594]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1015
    OS Version      :  Windows 10
    R Version       :  3.5.1

### Steps to reproduce the problem

1. Open Rmd document and edit. 
2. Squares on the application glitch

This doesn't occur with R files as far as I can tell.

### Describe the problem in detail

See above.

### Describe the behavior you expected

No glitching

**Comment by jmcphers** [comment]
Sorry you're having trouble! Can you tell us a little more about your video card and display setup? And does forcing software rendering mode resolve your issue? (Tools -> Options -> General -> Advanced -> Rendering Engine)

**Comment by kevinushey** [comment]
A screenshot would also be helpful, so we can understand just what exactly you're seeing.

**Comment by imanuelcostigan** [comment]
@jmcphers  
* video card: integrated Intel HD Graphics 520. 
* displays: connecting to two external monitors through a Targus docking station. 
* rendering engine: software...seems to prevent glitching

@kevinushey 

the glitching isn't constant, but occurs sporadically, and only affects a recentagle that is something like 1/32 of the window.

**Comment by kevinushey** [comment]
We should be screening those cards out:

https://github.com/rstudio/rstudio/blob/a68995142c66fdbc5d53876a786072e4124c0035/src/cpp/desktop/DesktopMain.cpp#L315-L321

Perhaps those checks are failing because the video card name is reported slightly differently. I'll see if we can relax those checks.

**Comment by kevinushey** [comment]
Looks like we might be getting the name wrong -- the reported name includes `(R)` after Intel's name, e.g.

![615e41bf-8e1f-4256-a309-db21e8b68cad](https://user-images.githubusercontent.com/1976582/46543539-f744a500-c875-11e8-9eed-2f5083faf322.png)

so we probably need to augment this check.

**Comment by imanuelcostigan** [comment]
This seems to have been fixed in the latest Preview Release.

**Comment by kevinushey** [comment]
But you just said:

> This seems to have been fixed in the latest Preview Release.

What has changed on your machine?

Also worth asking: does your laptop have a dedicated graphics card? Does it make a difference whether your laptop is plugged into a power source when you start RStudio? (since Windows laptops normally switch between dedicated + on board graphics based on whether it's currently plugged in)
