### ISSUE TITLE
Theme not properly handled in "new window" for notebook outputs

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#3595]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1023 (but it's been like that for a while)
    OS Version      : OS X 10.13
    R Version       : 3.5.1

### Steps to reproduce the problem
    data("HairEyeColor")
    dplyr::glimpse(HairEyeColor)

### Describe the problem in detail
When I click the button to open a chunk's output in a new window (<img width="44" alt="screen shot 2018-10-04 at 18 52 54" src="https://user-images.githubusercontent.com/33321678/46489884-d6913680-c806-11e8-8836-64c29a52fcb2.png">), the theme is not respected in the new window. 

First time I get:
<img width="1312" alt="screen shot 2018-10-04 at 18 51 45" src="https://user-images.githubusercontent.com/33321678/46489937-edd02400-c806-11e8-91ea-a161a2d3cb22.png">

When I close, and try again, I get:
<img width="1312" alt="screen shot 2018-10-04 at 18 51 51" src="https://user-images.githubusercontent.com/33321678/46489946-f7598c00-c806-11e8-9d66-7ba2ad29f70b.png">

My current theme:

    > rstudioapi::getThemeInfo()
    $editor
    [1] "Cobalt"
    
    $global
    [1] "Modern"

    $dark
    [1] TRUE
    
    $background
    [1] "#002240"
    
    $color
    [1] "#FFFFFF"

**Comment by kevinushey** [comment]
IIUC this should be fixed in the latest daily builds of RStudio -- is that correct @MariaSemple?

**Comment by MariaSemple** [comment]
Yes, I believe this was fixed via #3598.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.

**Comment by gregleleu** [comment]
It's back in version 1.2.1114...

**Comment by kevinushey** [comment]
@gregleleu sorry for the trouble -- this should be fixed in the latest daily build (1.2.1115).
