### ISSUE TITLE
RStudio Preview uses the wrong icon for the Windows 7 taskbar

### ISSUE THREAD

**Issue by svraka** [rstudio/rstudio#3600]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1015
    OS Version      : Windows 7
    R Version       : 3.5.1

### Steps to reproduce the problem

Pin the RStudio launcher to the Taskbar or in the Start menu

### Describe the problem in detail

A scaled-up version of a smaller icon is used in the Taskbar and in Start Menu. You can see it on the right, while in an Explorer window on the left, or on the desktop in the middle the correct icons are used. 

![rstudio_icons](https://user-images.githubusercontent.com/2940845/46526312-34b52c80-c88e-11e8-8121-f5e05dc71af2.png)

**Comment by kevinushey** [comment]
FWIW I'm not able to reproduce on Windows 10 -- the correct icon appears to be selected there.
