### ISSUE TITLE
Upgrading to Pandoc 2.3.1?

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#3601]
Originally reported at https://github.com/rstudio/bookdown/issues/643.

Pandoc 2.2.1 as shipped in the current preview version of RStudio has a syntax highlighting bug at least for R (it fails to recognize `##` as comment):

![image](https://user-images.githubusercontent.com/163582/46542155-56f57d00-c883-11e8-9dd7-b31f8fda7a9b.png)

which has been fixed in 2.3.1 (the current latest version of Pandoc):

![image](https://user-images.githubusercontent.com/163582/46542118-480eca80-c883-11e8-9b55-14f8b63623ab.png)

Repro:

````
---
title: "Syntax Highlighting"
output: 
  html_document: 
    highlight: tango
---

```{r}
rmarkdown::pandoc_version()
```

```r
# single hash
## double hash
```
````

I wonder if it is worth upgrading to Pandoc 2.3.1 in the near future.

**Comment by vnijs** [comment]
FYI Upgrading to 2.3.1 would also address an issue with pandoc and docker. See https://github.com/rocker-org/rocker-versioned/issues/103
