### ISSUE TITLE
addin UI elements not visible

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3602]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1026
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Try running an addin, e.g. the reprex addin.

### Describe the problem in detail

UI elements are invisible:

![screen shot 2018-10-05 at 8 58 25 am](https://user-images.githubusercontent.com/1976582/46546072-f3685100-c87c-11e8-8c24-855b15cf54a3.png)

### Describe the behavior you expected

UI elements should render without issue.

**Comment by rich-rstudio** [comment]
verified on 1.2.1090
