### ISSUE TITLE
macOS installer appears to require macOS 10.12

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3605]
From https://community.rstudio.com/t/preview-version-for-mac-10-11-or-10-12/15771.

IIRC, our goal was to support back to El Capitan (10.11). Qt 5.11 should support macOS 10.11, so I wonder if we just need to tweak something in our build system to get this working.

**Comment by jmcphers** [comment]
I've updated the release page (will go live the next time we update the preview)
