### ISSUE TITLE
Connections -> SQL always quotes table name

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3607]
After creating a new SQL script with the SQL button in the connections pane, I see:

![screen shot 2018-10-05 at 11 26 13 am](https://user-images.githubusercontent.com/1976582/46553111-814e3700-c891-11e8-8030-781a8320b808.png)

I think the experience here would be nicer if we left the schema + table names unquoted, and only quoted if they were truly non-syntactic names.

(I'm not sure, but as a matter of style it might be nice to omit the name `public` if that were the active schema name -- but perhaps it's best practice to be explicit in general)

Marking as v1.2 milestone just so we consider this issue explicitly (but can definitely punt if we feel no change is warranted, or not warranted for v1.2)

**Comment by javierluraschi** [comment]
Might be tricky to figure out exactly what needs quoting and what not since it would need to be supported by all SQL providers and even tools like Spark. However, is probably safe to assume that if it only contains `[a-Z]+` letters, it's safe to not quote.

**Comment by andresrcs** [comment]
It might be worth to point out that for postgresql, if there are upper case letters, the name must be quoted, since postgresql is not case sensitive

**Comment by kevinushey** [comment]
Is it common to use uppercase letters for table names? It seems like normally table names will match `[a-z_]+`.

**Comment by ronblum** [comment]
@kevinushey Oracle can be case-sensitive. Without quotes, Oracle is not case-sensitive and will convert table lowercase names to uppercase. But with quotes, it is case-sensitive, so you can have objects with the same name with different case, such as "employees", "Employees", "EMPLOYEES" as en example here: https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements008.htm

MySQL is case-sensitive on Unix: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

**Comment by kevinushey** [comment]
I would propose that we only quote the table name if it does not match `^[a-z_]+$`.

I tried diving into the connections code but couldn't find where this template gets generated.

**Comment by kevinushey** [comment]
Punting from v1.2.
