### ISSUE TITLE
creating a new SQL script from connection forces preview, which could be expensive

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3611]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1029
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

In the Connections pane, click the SQL button and create a new script.

### Describe the problem in detail

A new script is created. After accepting the prompt to save the file, the query is run. The default query is e.g.

```
SELECT * FROM "public"."mtcars"
```

### Describe the behavior you expected

We should avoid running the query as it could be expensive if a very large table is chosen from the database.

**Comment by jmcphers** [comment]
Worth considering, accidentally opening giant data is a consistent theme! @javierluraschi what do you think?

**Comment by kevinushey** [comment]
Where does the sample query get generated for new SQL documents created through this API? I tried diving in myself but couldn't discover the right place.

**Comment by kevinushey** [comment]
@javierluraschi will you still have some time to tackle this? If not let me know and I'll take a look.

**Comment by kevinushey** [comment]
Thanks @javierluraschi!

**Comment by ronblum** [comment]
I tried this out on both RStudio Server (Red Hat 7.6) and Desktop (MacOS 10.14), with a few databases, and the SQL preview is getting executed as soon as the file is saved

**Comment by kevinushey** [comment]
@ronblum did you test with the latest (development) versions of `odbc` and `sparklyr`? IIUC the fixes were made in those packages as opposed to RStudio itself.

**Comment by ronblum** [comment]
Thank you! Confirmed on several desktop and server installations.

I'm leaving this with the "verifying" tag for now, as a reminder to validate when the updated package is live.
