### ISSUE TITLE
Feature Request - New Empty Session

### ISSUE THREAD

**Issue by baderstine** [rstudio/rstudio#3612]
Use Case:
Working on a particular Project in a Session.  Want to open a brand new instance of RStudio while leaving my current Session open, and not having to navigate to a different Project file. I cannot find a way to do this on Mac OS X!  

I would imagine this happening one of three ways:
1. File -> New Project in New Session...
2. Session -> New Empty Session... 
TBH: I was surprised and a little confused that "Session -> New Session" really acts more like "Session -> Duplicate Session"
3. Other menu shortcut that just runs: "open -n /Applications/RStudio.app" (thanks: [SO](https://stackoverflow.com/questions/19747536/multiple-independent-r-sessions-in-mac-os-x))

What I've tried, and why it doesn't work:
1. File -> New Project... : this takes over the current session.
2. File -> Open Project in New Session... : this requires a second Project to already exist.
3. Session -> New Session... : this duplicates everything in the current session and there is a bug #3521

**Comment by kevinushey** [comment]
One solution using the [rstudioapi](https://github.com/rstudio/rstudioapi) package is to run:

```R
rstudioapi::openProject(newSession = TRUE)
```

Does this indeed accomplish what you need?

**Comment by baderstine** [comment]
No sorry. This is equivalent to Session -> New Session, 3. above.  It opens a new session of the same project in a new window. 

This is closer:

`rstudioapi::terminalExecute("open -n /Applications/RStudio.app")`

**Comment by amarquard** [comment]
Yes I agree with @baderstine, I need this on a daily basis. My entire reason for opening a new session is to get away from the current project and do something else elsewhere... Would be fantastic to have this feature

**Comment by baderstine** [comment]
For those who might be interested, here's my workaround.  I wrote a function in my own helper package that I load all the time. I've only tested it on Mac and Windows (caveat emptor):

```r
new_empty_session = function() {
  require(rstudioapi)
  
  if(.Platform$OS.type == "unix") {
    rstudioapi::terminalExecute("open -n /Applications/RStudio.app", show=F)
  } else if(.Platform$OS.type == "windows") {
    rstudioapi::terminalExecute('open -n "C:\\Program Files\\RStudio\\bin\\rstudio.exe" ')
  } else {
    print(paste0(.Platform$OS.type, " not yet supported"))
  }
}
```
