### ISSUE TITLE
Ubuntu 16.04+ (WLS): bash: /usr/bin/rstudio: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by dorianps** [rstudio/rstudio#3615]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1031
    OS Version      :  Ubuntu 16.04 or Ubuntu 18.04 (both Windows Linux Subsystem)
    R Version       :  3.4.4

### Steps to reproduce the problem
Install Rstudio 1.2.1031 on Ubuntu 16+ in Windows Linux Subsystem.
```
dp@CFIWKLMP04Y690A:~$ sudo gdebi rstudio-1.2.1031-amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done

RStudio
 RStudio is a set of integrated tools designed to help you be more productive with R. It include
s a console, syntax-highlighting editor that supports direct code execution, as well as tools fo
r plotting, history, and workspace management.
Do you want to install the software package? [y/N]:y
Selecting previously unselected package rstudio.
(Reading database ... 155862 files and directories currently installed.)
Preparing to unpack rstudio-1.2.1031-amd64.deb ...
Unpacking rstudio (1.2.1031) ...
Setting up rstudio (1.2.1031) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
dp@CFIWKLMP04Y690A:~$ rstudio
bash: /usr/bin/rstudio: cannot execute binary file: Exec format error
```

### Describe the problem in detail
Installing the new Rstudio v1.2 seems to work, but the executable does not work any more. I have tried installing older versions down to 1.2.1002, and also tried the Debian release. Same result.
I got the .deb installers from here: https://www.rstudio.com/products/rstudio/download/preview/
or here https://dailies.rstudio.com/rstudio/oss/xenial/x86_64/

Tried also checking the files for version 1.1.456 which works and the new 1.2 version:
```
# v1.2
/usr/lib/rstudio/bin/rstudio: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynam
ically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=3253
88ce0621ee0b955a533095f06d933d795e7f, not stripped
# v1.1
/usr/lib/rstudio/bin/rstudio: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamica
lly linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=3e2059e
b8f364397da8f29cad3261df68575d44f, not stripped
```

### Describe the behavior you expected
For it to run.

Failed diagnostic report:
```
dp@CFIWKLMP04Y690A:~$ rstudio --run-diagnostics
bash: /usr/bin/rstudio: cannot execute binary file: Exec format error
```

**Comment by kevinushey** [comment]
Sorry, but RStudio in WSL is not something we intend to support, and if it did work in the past that would've been just dumb luck. That said, RStudio works just fine in a regular Ubuntu installation so whatever is wrong here must be the glue between Windows and Linux.

**Comment by abalter** [comment]
@kevinushey. I don't know why you would say it is dumb luck. I've installed it in WSL successfully multiple times over the last year.

**Comment by dorianps** [comment]
@abalter 
I have used RSTudio 1.1 in WSL since the time WSL came out in Oct 2016. But they have changed a number of things in v1.2 which breaks that compatibility. The question is whether is worth for them to look into that and maybe find a solution. @kevinushey thinks is not worth, I think differently as a user knowing that the world is going towards easier cross-talk between OS-es. Yet, I recently gave up WSL completely and am using HYPER-V virtualized linux when needed.

**Comment by kfeinauer** [comment]
@abalter I believe Kevin means that it is purely by coincidence that RStudio worked in WSL purely by chance in the past - we do not currently test RStudio in WSL and do not actively attempt to make the product work with it, at least at this time.

**Comment by abalter** [comment]
@dorianps your are right! v1.2 doesn't work on WSL! Although, I'm going to give a try building from source. I guess I'll have to go back to v1.1.

'Cmon rstudio folks. Are you aware of how many people are running rstudio under WSL?

**Comment by kongdd** [comment]
@dorianps `rstudio-server-1.2.1335-amd64.deb` works under WSL ubuntu 18.04
https://www.rstudio.com/products/rstudio/download-server/

**Comment by dorianps** [comment]
Thanks for letting me know. I've eliminated wsl since.

**Comment by abalter** [comment]
@kongdd I'm running 18.10. But I'll try a full update and try again to see if it will build.

**Comment by black-snow** [comment]
`rstudio-server-1.2.1335-amd64.deb` does **not** work for me on Ubuntu 18.04 inside WSL 1 with xface4 and VcXsrv.
See: https://superuser.com/questions/1465891/run-rstudio-in-wsl-error-in-program-format?noredirect=1#comment2212395_1465891

**Comment by kongdd** [comment]
> `rstudio-server-1.2.1335-amd64.deb` does **not** work for me on Ubuntu 18.04 inside WSL 1 with xface4 and VcXsrv.
> See: https://superuser.com/questions/1465891/run-rstudio-in-wsl-error-in-program-format?noredirect=1#comment2212395_1465891

`rstudio-server` works, but not rstudio. In your question, it's `rstudio`.

**Comment by black-snow** [comment]
@kongdd you are right, I overlooked that

**Comment by abalter** [comment]
Any hope?

**Comment by Kalaschnik** [comment]
This warning happens in WSL 1. RStudio in WSL 2 works.

**Comment by dorianps** [comment]
👍 I think I will give it a try soon. I was avoiding fast tracks of Windows
10, they always created problems in the past.

**Comment by Kalaschnik** [comment]
2004 (20H1) is actually done since December 2019, and MS is delivering updates since. No problems since January, and WSL 2 is really really fast.

**Comment by abalter** [comment]
Supposedly release in April. We will see...

**Comment by Kalaschnik** [comment]
I was referring to:

> Even though the RTM build for Windows 10 20H1, or version 2004, was released back in December, it's still not going to ship until the spring. Between when that build was released and when it ships to the public, there will be several cumulative updates, with the idea that it when it's generally available, it should be as stable as a feature update that's been serviced for a few months.

**Comment by dorianps** [comment]
Steven, can you provide some more info on your steps/installation? I
switched to 20H1, went for WSL2 with Ubuntu 18.04, installed everything and
tried running rstudio. The window shows briefly and then crashes with this
error:

~$ rstudio
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-dp'
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "
172.27.64.1:0"
      after 548 requests (548 known processed) with 0 events remaining.

P.s. xeyes works ok.

**Comment by Kalaschnik** [comment]
Hey Dorian,

I updated my gist here.
https://gist.github.com/Kalaschnik/177a30bd02c9438fee1a93686fe60735

I was also not able to run it using Ubuntu 18.04. In Pengwin you can install a package called GUILIB, as described in step 6, which seems to do the trick. I would suggest to analyze what selecting GUILIB is doing:
https://github.com/WhitewaterFoundry/pengwin-setup/blob/master/pengwin-setup.d/gui.sh

In line 40 it triggers guilib.sh, which is here:
https://github.com/WhitewaterFoundry/pengwin-setup/blob/613a415304a189a4f6ddd303fc7c738ec19ba703/pengwin-setup.d/guilib.sh

Could you run the shell file, and see if that makes a change?
What X server are you using?

**Comment by dorianps** [comment]
I found the culprit in my case. I use MobaXterm. The trick was to disable
OpenGL acceleration completely. That did the trick in full and now I can
work and install things in Rstudio:
[image: image.png]

[image: image.png]

**Comment by Kalaschnik** [comment]
Hey @dorianps, could elaborate how you actually did that? I want to test the installation in Ubuntu.

**Comment by dorianps** [comment]
As I mentioned, I use MobaXterm, which comes with an Xserver.
https://mobaxterm.mobatek.net/

I made a couple of mistakes during the installation, like installing
Rstudio-server and installing a non-bionic package first. Then I manually
installed some libraries mid-way. I am pasting below the whole history of
my commands if that helps. The final issue is that the Xserver in MobaXterm
uses OpenGL acceleration by default. I don't know for what reason (my
computer or what else) but switching off that acceleration made Rstudio
open ok. Note, during all the time xeyes (the test gui app) worked ok, only
Rstudio was failing until I switched acceleration off.

I also ran yesterday a comparison with docker, and finally, WSL2 has
similar performance as a docker container, which is impressive.
https://github.com/dorianps/docker/wiki/Windows:-Docker-vs.-WSL-speed-test#update-2020-03-23

You also need to set MobaXterm X11 remote access to "full"
[image: image.png]

---------------------------------------------

    9  lsb_release -a
   10  apt info r-base
   11  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys
E298A3A825C0D65DFD57CBB651716619E084DAB9
   12  sudo add-apt-repository 'deb
https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
   13  sudo apt update
   14  apt how r-base
   15  apt show r-base
   16  sudo apt install r-base
   17  R
   18  sudo apt install r-base-dev
   19  sudo apt-get install gdebi-core
   20  wget
https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.5033-amd64.deb
   21  sudo gdebi rstudio-server-1.2.5033-amd64.deb
   22  wget
https://download1.rstudio.org/desktop/debian9/x86_64/rstudio-1.2.5033-amd64.deb
   23  sudo apt-get remove rstudio-server
   24  sudo gdebi rstudio-1.2.5033-amd64.deb
   25  rstudio
   26  sudo apt install libssl
   27  sudo apt-get install libssl1.0.0 libssl-dev
   28  rstudio
   29  sudo apt install libcurl4-openssl-dev
   30  rstudio
   31  sudo apt install openssl1.0.2
   32  sudo apt install libssl-dev
   33  sudo apt install openssl-dev
   34  sudo locate libcrypto.so
   35  sudo apt install libcrypto
   36  sudo apt install libcrypto1.0.2
   37  sudo apt-get install libssl1.0.0 libssl-dev
   38  sudo apt install libssl1.0-dev
   39  sudo apt-get install libssl1.0.0 libssl-dev
   40  sudo apt install libcrypto1.0.2
   41  rstudio
   42  sudo apt install libcurl4-openssl-dev
   43  sudo apt install libxml2-dev
   44  sudo apt-get install gdebi-core
   45  rstudio
   46  wget
http://security.debian.org/debian-security/pool/updates/main/o/openssl1.0/libssl1.0.2_1.0.2r-1~deb9u1_amd64.deb
   47  sudo apt-get install libssl1.0.2
   48  sudo apt remove rstudio
   49  wget
https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5033-amd64.deb
   50  ll
   51  sudo gdebi rstudio-1.2.5033-amd64.deb
   52  rstudio
   53  rm rstudio-*
   54  sudo apt remove rstudio
   55  wget
https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5033-amd64.deb
   56  sudo gdebi rstudio-1.2.5033-amd64.deb
   57  rstudio
   58  sudo apt install libnss3
   59  rstudio
   60  sudo apt install apt-file
   61  sudo apt-file search libasound.so.2:
   62  sudo apt-file search libasound.so.2
   63  sudo apt update
   64  sudo apt-file search libasound.so.2
   65  rstudio
   66  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/
   67  rstudio
   68  ll /usr/lib/x86_64-linux-gnu/libasound.so.2
   69  sudo apt install libasound2
   70  rstudio
   71  sudo apt-file search libEGL.so.1
   72  sudo apt install libegl1
   73  rstudio
   74  cat /etc/resolv.conf
   75  xeyes
   76  sudo apt install x11-apps
   77  xeyes
   78  exit
   79  xeyes
   80  exit
   81  xeyes
   82  exit
   83  xeyes
   84  rstudio
   85  exit
   86  rstudio
   87  sudo apt install libegl1-mesa
   88  rstudio
   89  sudo apt update
   90  sudo apt list --upgradable
   91  sudo apt upgrade
   92  rstudio
   93  xeyes
   94  exit
   95  R
   96  rstudio
   97  ll /etc/x2go/
   98  ll /etc/rstudio/
   99  cd /etc/rstudio/
  100  ll
  101  cat rsession.conf
  102  cat rserver.conf
  103  ll themes/
  104  cat themes/README.md
  105  exit
  106  r
  107  lsb_release -a
  108  xeyes
  109  rstudio
  110  exit
  111  xeyes
  112  exit
  113  xeyes
  114  rstudio
  115  exit
  116  xeyes
  117  exit
  118  xeyes
  119  rstudio
  120  xeyes
  121  rstudio
  122  exit
  123  echo $DIPLSAY
  124  echo $DISPLAY
  125  export DISPLAY=192.168.0.80:0.0
  126  xeyes
  127  rstudio

**Comment by Kalaschnik** [comment]
Thanks Dorian, I’ll dig through you log if I find some time. And thanks for the comparison! Performance of WSL 2 is game changing, indeed. However, if you operate in /mnt/ the performance might actually suck; see https://github.com/microsoft/WSL/issues/4197

**Comment by dorianps** [comment]
Thanks for the heads up. I didn't think of comparing docker and WSL with
external mounts, might be worth trying later.

Dorian
