### ISSUE TITLE
LaTeX inline preview for md files

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#3616]
### System details

```
    RStudio Edition : Desktop
    RStudio Version : 1.2.1018
    OS Version      :  MacOS 10.13.6
    R Version       :  3.5.1
```

RStudio does an nice preview of LaTeX formulas inline in Rmd files.
Can this be enabled in pure md files also?
RStudio is a nice editor for md files!

**Comment by ronblum** [comment]
@neuwirthe Thanks as always for the suggestions!
