### ISSUE TITLE
backport locale fix for Mojave

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3619]
cc: https://github.com/rstudio/rstudio/issues/3587

One user has reported this fixes the issue successfully, but we should let the fix live in v1.2 preview for a bit just to confirm it does indeed do the trick for everyone and then consider backporting.

**Comment by ronblum** [comment]
Confirmed fixed in RStudio MacOS Desktop 1.1.463. Test details are in #3587.

**Comment by kevinushey** [comment]
This is now live in the v1.1 preview, so we can close this.
