### ISSUE TITLE
Removed secondary repositories require session restart to be cleared out

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3621]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.015 & 1.2.130
    OS Version      : MacOS High Sierra 10.13.6 & Ubuntu 16.04.5
    R Version       : 3.4.4 & 3.5.1

### Steps to reproduce the problem

Start with just a primary repository, such as "Global (CDN) - RStudio". Remove any secondary repositories and restart the R session if you first need to remove any secondary repositories.

1. In console: `getOption("repos")`
2. Tools -> Global Options -> Packages -> Add
3. Enter a valid repository name and URL pair, such `Canadia` and `https://mirror.its.sfu.ca/mirror/CRAN/`
4. OK -> Add
5. Enter another valid repository name and URL pair, such `Gaul` and `https://cran.biotools.fr/`
6. OK
7. In console: `getOption("repos")`
8. Tools -> Global Options -> Packages -> Remove -> Gaul -> Yes -> Remove -> Canadia -> Yes -> OK
9. In console: `getOption("repos")`
10. Session -> Restart R
11. In console: `getOption("repos”)`

### Describe the problem in detail

Even though the secondary repositories are removed in step 8, step 9 shows that they are still being used. The session has to be restarted in order to clear them out.

Note that I've also seen cases in which most secondary repositories are successfully removed in the same session except for the one at the top of the list. I'm haven't been able to determine what causes the difference in behavior.

### Describe the behavior you expected

Any secondary repositories that has been removed in the UI should be removed in the current session.

**Comment by kevinushey** [comment]
I thought the intention was always that these were settings to be applied only at startup, and so changing them would necessitate a restart to have them applied in the current session?

(Perhaps we need to prompt for restart in that case?)

**Comment by ronblum** [comment]
Ah, I thought it was the reverse. Yes, we should have a restart prompt if that's the case.

@javierluraschi Are the secondary repositories supposed update `repos` during the current session? Either way, we should be consistent—either they should both be added and removed in the same session, or they should both require a restart.

**Comment by slopp** [comment]
I find it most intuitive to see these settings applied immediately, akin to the other changes in the Global Options dialog

**Comment by javierluraschi** [comment]
@ronblum Yes, it should apply to the current session as well. This used to be the case right? Would be helpful to identify which build introduced this change to understand the motivation of the change.

I don't remember changing this myself, does this sound familiar @kevinushey?

**Comment by ronblum** [comment]
Got it: if the secondary repositories are created and removed in the same session, the last one still remains until restart.

If the secondary repositories were added and the session restarted, so that they were there when the session was created, then all of those won't go away until restart.

**Comment by kevinushey** [comment]
Sorry, nothing here sounds familiar to me.

**Comment by javierluraschi** [comment]
Yeah, I'll take a look, this has been like this for a while... the problem is that if all secondaries are removed, the update code does not trigger.
