### ISSUE TITLE
Indicate R/RStudio is busy when installing through GUI using secondary repositories

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3622]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.1015 & 1.0.1030
    OS Version      : MacOS High Sierra 10.13.6 & Ubuntu 16.04.5
    R Version       : 3.4.4 & 3.5.5

### Steps to reproduce the problem

Start with just a primary repository, such as "Global (CDN) - RStudio". Remove any secondary repositories and restart the R session if you first need to remove any secondary repositories.

1. In console: `getOption("repos")`
2. Tools -> Global Options -> Packages -> Add
3. Add a secondary repository with a valid name/URL pair, such as `Thracia` and `https://ftp.cc.uoc.gr/mirrors/CRAN/`
4. OK
5. In console: `getOption("repos”)`
6. Tools -> Install Packages
7. Enter a valid package to install, such as `dplyr`and click "Install"
8. In console: `x <- 1`
9. In console: `x`

### Describe the problem in detail

Step 10 results in the following output:
```
> x <- 1
> x
[1] 1
> install.packages("dplyr")
also installing the dependencies ‘fansi’, ‘utf8’, ‘bindr’, ‘cli’, ‘crayon’, ‘pillar’, ‘purrr’, ‘assertthat’, ‘bindrcpp’, ‘glue’, ‘magrittr’, ‘pkgconfig’, ‘R6’, ‘Rcpp’, ‘rlang’, ‘tibble’, ‘tidyselect’, ‘BH’, ‘plogr’

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/fansi_0.4.0.tgz'
Content type 'application/x-gzip' length 207507 bytes (202 KB)
==================================================
downloaded 202 KB

<snip>
```

However, there is a delay between the time the second line  appears to be accepted, and then `install.packages("dplyr")` seems to appear out of nowhere, even though it's legitimately what's going on.
 
After clicking on "Install" in step 9, the modal closes and it looks like nothing happened. But then, in step 10, after typing something in the console, it looks like the R session is stuck, until finally `install.packages("dplyr")` etc. pops up and the installation starts. What's happening is that if R has multiple repositories, it compares the packages in them, which takes a long time. The user may not know this, and the UI isn't giving any indication of it, so at first it might look like things aren't working. It gets worse if more than one secondary repository is added because it will take even longer.

See #3349, which provides details about when we thought the time lag was a bug.  

### Describe the behavior you expected

We should indicate that the installation is in progress while R is busy comparing the packages, such as part of installation in the "Install" option but also when we offer to update packages like `odbc`, `shiny`, etc. in different parts of the UI. Otherwise, it seems like RStudio is unresponsive due to a problem.

**Comment by jmcphers** [comment]
It might be better to install the packages in a Job; then RStudio won't hang at all.
