### ISSUE TITLE
Git executable symbolic link

### ISSUE THREAD

**Issue by avsmith** [rstudio/rstudio#3627]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.907
    OS Version      :  macOS 10.14
    R Version       :  3.5.1

### Steps to reproduce the problem

1. Update Homebrew git
2. Source code tracking doesn't work until re-point at /usr/local/bin/git symbolic link

### Describe the problem in detail

If using git as a symbolic link, rstudio expands to the exact path (for example /usr/local/bin/git symbolic link expands to /usr/local/Cellar/git/2.19.1/bin/git). When updating the git binary, having the same underlying symbolic link, then source code tracking doesn't work until re-choosing the /usr/local/bin/git symbolic link. This problem happens with annoying frequency when using git from HomeBrew (http://brew.sh). 

Might not file under bug, but definitely file under annoying.

**Comment by kevinushey** [comment]
Thanks for the bug report. This should be fixed up in the next iteration of the preview release.

**Comment by ronblum** [comment]
Confirmed with RStudio Desktop 1.2.1287-1. @avsmith if you still see the issue occurring, please let us know.
