### ISSUE TITLE
Trackpad scrolling with long code in console doens't work on RStudio 1.2.1031 on Mac

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#3640]
If there's a long chunk of code in the console, two-finger trackpad scrolling doesn't work but click and moving the scrollbar works.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1031 (daily)
    OS Version      : MacOs 14.0
    R Version       : 3.5.1

**Comment by kevinushey** [comment]
Can you please give an example where scrolling doesn't work for you? Scrolling works without issue for me with console history on macOS Mojave 10.14 (running on a 2013 MBP)

**Comment by bakaburg1** [comment]
Any long chunk of code in the console would do. I notice that scrolling when hovering on the scroll bar works too, so I think that the scroll event is not catched in the console panel.

I attached a video showing that I can't scroll if the mouse is not on the scrollbar.

Here's also some random long chunk of code to try out:
```
[Registrazione schermo 2018-10-11 alle 10.36.13.mov.zip](https://github.com/rstudio/rstudio/files/2468075/Registrazione.schermo.2018-10-11.alle.10.36.13.mov.zip)


grid.arrange(
    Hosp.Data %>% dplyr::select(matches('Struttura')) %>% 
        cbind(Hosp.Data %>% dplyr::select(Zone) %>% mutate(rn = row_number()) %>% spread(Zone, Zone) %>% dplyr::select(-rn) %>% mutate_all(funs(is.na(.) %>% factor(labels = c('Si', 'No'))))) %>% 
        mutate('All' = 'All') %>% 
        gather('Key', 'Value') %>%
        filter(Value != 'No') %>% 
        mutate(
            Value = case_when(str_detect(Key, 'Strut') ~ 'Struttura', T ~ Key) %>% factor(levels =  c('All', 'Struttura', 'Nord-Est', 'Nord-Ovest', 'Centro', 'Sud', 'Isole')),
            Key = factor(Key, levels = c('All', 'Struttura.ASL', 'Struttura.privata', 'Struttura.ricerca',  'Struttura.AO', 'Struttura.universitaria', 'Struttura.religiosa', 'Nord-Est', 'Nord-Ovest', 'Centro', 'Sud', 'Isole'), labels = c('All hospitals', hosp.characteristics$Struttura.ASL, hosp.characteristics$Struttura.privata, hosp.characteristics$Struttura.ricerca, hosp.characteristics$Struttura.AO, hosp.characteristics$Struttura.universitaria, hosp.characteristics$Struttura.religiosa, 'North-East', 'North-West', 'Center', 'South', 'Islands')),
            Zone = factor(Key %in% c('North-East', 'North-West', 'Center', 'South', 'Islands'), labels = c('Hospital type', 'Geographic zone'))
        ) %>%
        group_by(Key) %>% 
        summarise(N = n(), Perc = N / nrow(Hosp.Data), Value = Value[1], Zone = Zone[1]) %>% 
        ggplot(aes(Key, N)) +
        geom_col(aes(fill = Value), position = position_dodge2(width = .5), width = .5) +
        geom_label(aes(label = sprintf('%g\n(%s)', N, percent(Perc))), alpha = .7, nudge_y = .08 * nrow(Hosp.Data), size = 3) +
        scale_fill_manual(breaks = c('North-East', 'North-West', 'Center', 'South', 'Islands'), values = c(hue_pal()(3)[2:3], brewer_pal()(9)[5:9])) +
        scale_y_continuous(breaks = pretty_breaks(5), expand = c(.1, .1)) +
        facet_wrap( ~ Zone, scales = 'free_x', ncol = 2) +
        theme(
            axis.text.x = element_text(angle = 45, hjust = 1),
            #strip.text = element_blank(),
            plot.title = element_text(hjust = .5),
            plot.margin = unit(c(3, .5, 3, .5), 'cm')
        ) +
        labs(x = NULL, y = 'N. of hospitals', title = 'A. Hospital distribution'), 
    
    arrangeGrob(
        rbind(
            data.frame(
                Key = factor(c('Has a site^{a}', 'Has a SN^{b}'), levels = c('Has a site^{a}', 'Has a SN^{b}')),
                Perc = c(mean(Hosp.Data$Match == 'Yes'), mean(Site.Data$Have.social == 'Yes')),
                N = c(sum(Hosp.Data$Match == 'Yes'), sum(Site.Data$Have.social == 'Yes')),
                Color = c('steelblue', 'lightgreen')
            ),
            Site.Data %>% filter(Have.social == 'Yes') %>% dplyr::select(matches('url$')) %>% mutate_all(function(x) !is.na(x)) %>% gather('Key', 'Value') %>% group_by(Key) %>% summarise(Perc = mean(Value), N = sum(Value)) %>% mutate(Color = 'violet') %>% arrange(desc(Perc)) %>% mutate(Key = plyr::mapvalues(Key, c('yt.url', 'fb.url', 'tw.url', 'lin.url', 'gp.url', 'inst.url', 'pin.url'), c('Youtube', 'Facebook', 'Twitter', 'LinkedIn', 'Google+', 'Instagram', 'Pinterest') %>% paste0('^{c}')))
        ) %>% 
            ggplot(aes(Key, Perc)) +
            geom_col(aes(fill = Color), show.legend = F, width = .5) +
            geom_label(aes(label = sprintf('%g\n(%s)', N, percent(Perc))), alpha = .7, nudge_y = .08, size = 3) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            scale_x_discrete(labels = TeX) +
            scale_y_continuous(labels = percent) +
            theme(plot.title = element_text(hjust = .5)) +
            labs(x = NULL, y = NULL, title = 'B. Web presence'),
        
        Site.Data %>%
            group_by(GRank) %>% 
            summarise(Value = mean(.$GRank == GRank[1]), N = sum(.$GRank == GRank[1])) %>%
            ggplot(aes(factor(GRank), N)) +
            geom_col(aes(fill = GRank), show.legend = F, width = .5) +
            geom_label(aes(label = sprintf('%g\n(%s)', N, percent(Value))), alpha = .7, nudge_y = .08 * nrow(Site.Data), size = 3) +
            scale_fill_gradient(low = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[1], high = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[5]) +
            scale_y_continuous(labels = function(x) sprintf('%d (%s)', x, percent(x/nrow(Site.Data))), breaks = pretty_breaks(10)) +
            theme(plot.title = element_text(hjust = .5)) +
            labs(x = 'Rank', y = 'N. of sites (%)', title = 'C. Google Rank'),
        
        Social.Data %>% transmute(FB.fan.1000 = FB.fan.1000 * 1000, FB.y.post, TW.followers.100 = TW.followers.100 * 100, TW.y.tweets) %>% 
            gather('Key', 'Value') %>% 
            mutate(
                Type = plyr::mapvalues(Key, c('FB.fan.1000', 'FB.y.post', 'TW.followers.100', 'TW.y.tweets'), c('Number of followers', 'Number of posts\nin the last year', 'Number of followers', 'Number of posts\nin the last year')),
                Key = plyr::mapvalues(Key, c('FB.fan.1000', 'FB.y.post', 'TW.followers.100', 'TW.y.tweets'), c('Facebook fans', 'Facebook posts', 'Twitter followers', 'Tweets'))
            ) %>%
            na.omit %>%
            mutate(Value = case_when(Value == 0 ~ 1, T ~ Value)) %>%
            ggplot(aes(Key, Value)) +
            geom_boxplot(fill = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[1]) +
            stat_summary(geom = 'point', fun.y = mean, size = 6, alpha = .7) +
            scale_y_continuous(trans = 'log', labels = round.to.tens.scale) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            facet_wrap(~ Type, nrow = 1, scales = 'free') +
            theme(plot.title = element_text(hjust = .5)) +
            labs(y = 'Volumes of followers/posts (log scale)', x = NULL, title = 'D. SN activity'),
        
        rbind(
            FB.Data %>% dplyr::select(likes.summary.total_count, shares.count) %>% 
                set_colnames(c('FB likes per post', 'FB shares per post')) %>% 
                gather('Key', 'Value') %>% mutate(SN = 'Facebook'),
            TW.Data %>% dplyr::select(favorite_count, retweet_count) %>% 
                set_colnames(c('Tw like per tweet', 'Tw retweet per tweet')) %>% 
                gather('Key', 'Value') %>% mutate(SN = 'Twitter')
        ) %>% 
            mutate(Value = case_when(Value == 0 ~ 1, T ~ Value)) %>%
            ggplot(aes(Key, Value)) +
            geom_boxplot(fill = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[1]) +
            stat_summary(geom = 'point', fun.y = mean, size = 6, alpha = .7) +
            scale_y_continuous(trans = 'log', labels = round.to.tens.scale) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            #facet_wrap(~ SN, nrow = 1, scales = 'free') +
            theme(plot.title = element_text(hjust = .5)) +
            labs(y = 'Volume of interactions (log scale)', x = NULL, title = 'E. SN virality')
    ),
    nrow = 2,
    heights = c(1,2)
)

```
grid.arrange(
    Hosp.Data %>% dplyr::select(matches('Struttura')) %>% 
        cbind(Hosp.Data %>% dplyr::select(Zone) %>% mutate(rn = row_number()) %>% spread(Zone, Zone) %>% dplyr::select(-rn) %>% mutate_all(funs(is.na(.) %>% factor(labels = c('Si', 'No'))))) %>% 
        mutate('All' = 'All') %>% 
        gather('Key', 'Value') %>%
        filter(Value != 'No') %>% 
        mutate(
            Value = case_when(str_detect(Key, 'Strut') ~ 'Struttura', T ~ Key) %>% factor(levels =  c('All', 'Struttura', 'Nord-Est', 'Nord-Ovest', 'Centro', 'Sud', 'Isole')),
            Key = factor(Key, levels = c('All', 'Struttura.ASL', 'Struttura.privata', 'Struttura.ricerca',  'Struttura.AO', 'Struttura.universitaria', 'Struttura.religiosa', 'Nord-Est', 'Nord-Ovest', 'Centro', 'Sud', 'Isole'), labels = c('All hospitals', hosp.characteristics$Struttura.ASL, hosp.characteristics$Struttura.privata, hosp.characteristics$Struttura.ricerca, hosp.characteristics$Struttura.AO, hosp.characteristics$Struttura.universitaria, hosp.characteristics$Struttura.religiosa, 'North-East', 'North-West', 'Center', 'South', 'Islands')),
            Zone = factor(Key %in% c('North-East', 'North-West', 'Center', 'South', 'Islands'), labels = c('Hospital type', 'Geographic zone'))
        ) %>%
        group_by(Key) %>% 
        summarise(N = n(), Perc = N / nrow(Hosp.Data), Value = Value[1], Zone = Zone[1]) %>% 
        ggplot(aes(Key, N)) +
        geom_col(aes(fill = Value), position = position_dodge2(width = .5), width = .5) +
        geom_label(aes(label = sprintf('%g\n(%s)', N, percent(Perc))), alpha = .7, nudge_y = .08 * nrow(Hosp.Data), size = 3) +
        scale_fill_manual(breaks = c('North-East', 'North-West', 'Center', 'South', 'Islands'), values = c(hue_pal()(3)[2:3], brewer_pal()(9)[5:9])) +
        scale_y_continuous(breaks = pretty_breaks(5), expand = c(.1, .1)) +
        facet_wrap( ~ Zone, scales = 'free_x', ncol = 2) +
        theme(
            axis.text.x = element_text(angle = 45, hjust = 1),
            #strip.text = element_blank(),
            plot.title = element_text(hjust = .5),
            plot.margin = unit(c(3, .5, 3, .5), 'cm')
        ) +
        labs(x = NULL, y = 'N. of hospitals', title = 'A. Hospital distribution'), 
    
    arrangeGrob(
        rbind(
            data.frame(
                Key = factor(c('Has a site^{a}', 'Has a SN^{b}'), levels = c('Has a site^{a}', 'Has a SN^{b}')),
                Perc = c(mean(Hosp.Data$Match == 'Yes'), mean(Site.Data$Have.social == 'Yes')),
                N = c(sum(Hosp.Data$Match == 'Yes'), sum(Site.Data$Have.social == 'Yes')),
                Color = c('steelblue', 'lightgreen')
            ),
            Site.Data %>% filter(Have.social == 'Yes') %>% dplyr::select(matches('url$')) %>% mutate_all(function(x) !is.na(x)) %>% gather('Key', 'Value') %>% group_by(Key) %>% summarise(Perc = mean(Value), N = sum(Value)) %>% mutate(Color = 'violet') %>% arrange(desc(Perc)) %>% mutate(Key = plyr::mapvalues(Key, c('yt.url', 'fb.url', 'tw.url', 'lin.url', 'gp.url', 'inst.url', 'pin.url'), c('Youtube', 'Facebook', 'Twitter', 'LinkedIn', 'Google+', 'Instagram', 'Pinterest') %>% paste0('^{c}')))
        ) %>% 
            ggplot(aes(Key, Perc)) +
            geom_col(aes(fill = Color), show.legend = F, width = .5) +
            geom_label(aes(label = sprintf('%g\n(%s)', N, percent(Perc))), alpha = .7, nudge_y = .08, size = 3) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            scale_x_discrete(labels = TeX) +
            scale_y_continuous(labels = percent) +
            theme(plot.title = element_text(hjust = .5)) +
            labs(x = NULL, y = NULL, title = 'B. Web presence'),
        
        Site.Data %>%
            group_by(GRank) %>% 
            summarise(Value = mean(.$GRank == GRank[1]), N = sum(.$GRank == GRank[1])) %>%
            ggplot(aes(factor(GRank), N)) +
            geom_col(aes(fill = GRank), show.legend = F, width = .5) +
            geom_label(aes(label = sprintf('%g\n(%s)', N, percent(Value))), alpha = .7, nudge_y = .08 * nrow(Site.Data), size = 3) +
            scale_fill_gradient(low = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[1], high = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[5]) +
            scale_y_continuous(labels = function(x) sprintf('%d (%s)', x, percent(x/nrow(Site.Data))), breaks = pretty_breaks(10)) +
            theme(plot.title = element_text(hjust = .5)) +
            labs(x = 'Rank', y = 'N. of sites (%)', title = 'C. Google Rank'),
        
        Social.Data %>% transmute(FB.fan.1000 = FB.fan.1000 * 1000, FB.y.post, TW.followers.100 = TW.followers.100 * 100, TW.y.tweets) %>% 
            gather('Key', 'Value') %>% 
            mutate(
                Type = plyr::mapvalues(Key, c('FB.fan.1000', 'FB.y.post', 'TW.followers.100', 'TW.y.tweets'), c('Number of followers', 'Number of posts\nin the last year', 'Number of followers', 'Number of posts\nin the last year')),
                Key = plyr::mapvalues(Key, c('FB.fan.1000', 'FB.y.post', 'TW.followers.100', 'TW.y.tweets'), c('Facebook fans', 'Facebook posts', 'Twitter followers', 'Tweets'))
            ) %>%
            na.omit %>%
            mutate(Value = case_when(Value == 0 ~ 1, T ~ Value)) %>%
            ggplot(aes(Key, Value)) +
            geom_boxplot(fill = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[1]) +
            stat_summary(geom = 'point', fun.y = mean, size = 6, alpha = .7) +
            scale_y_continuous(trans = 'log', labels = round.to.tens.scale) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            facet_wrap(~ Type, nrow = 1, scales = 'free') +
            theme(plot.title = element_text(hjust = .5)) +
            labs(y = 'Volumes of followers/posts (log scale)', x = NULL, title = 'D. SN activity'),
        
        rbind(
            FB.Data %>% dplyr::select(likes.summary.total_count, shares.count) %>% 
                set_colnames(c('FB likes per post', 'FB shares per post')) %>% 
                gather('Key', 'Value') %>% mutate(SN = 'Facebook'),
            TW.Data %>% dplyr::select(favorite_count, retweet_count) %>% 
                set_colnames(c('Tw like per tweet', 'Tw retweet per tweet')) %>% 
                gather('Key', 'Value') %>% mutate(SN = 'Twitter')
        ) %>% 
            mutate(Value = case_when(Value == 0 ~ 1, T ~ Value)) %>%
            ggplot(aes(Key, Value)) +
            geom_boxplot(fill = wesanderson::wes_palette('Zissou1', 5, type = 'discrete')[1]) +
            stat_summary(geom = 'point', fun.y = mean, size = 6, alpha = .7) +
            scale_y_continuous(trans = 'log', labels = round.to.tens.scale) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            #facet_wrap(~ SN, nrow = 1, scales = 'free') +
            theme(plot.title = element_text(hjust = .5)) +
            labs(y = 'Volume of interactions (log scale)', x = NULL, title = 'E. SN virality')
    ),
    nrow = 2,
    heights = c(1,2)
)
```

**Comment by kevinushey** [comment]
Thanks for providing the video -- it makes it clear that you're not attempting to scroll the console history, but rather a large multi-line console input. I can reproduce in that case.
