### ISSUE TITLE
Package 

### ISSUE THREAD

**Issue by md0u80c9** [rstudio/rstudio#3642]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1030
    OS Version      : OS X Mojave 10.14.1 Beta (18B57c)
    R Version       :  3.5.1

### Steps to reproduce the problem

Clicking on the package tab, or Tools -> Check for Package Updates.

### Describe the problem in detail

In the 1.2 RStudio previews, whenever I try to access Package data, I am seeing a warning in the console regarding a differing number of rows:

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 210, 209

In 1.1 versions this has not happened. I've tested it on both my MacBook Pro and my iMac and the same error appears to be present on both occasions.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2464046/diagnostics-report.txt)

All the code and packages run as expected.

**Comment by jmcphers** [comment]
Thanks for reporting this. I wasn't able to repro, but I did see this error quite a lot in your logs.

    09 Oct 2018 10:33:31 [rsession-andrewhill] ERROR r error 4 (R code execution error) [errormsg=Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : |||  arguments imply differing number of rows: 210, 209|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) /Users/vagrant/workspace/IDE/macos/src/cpp/r/RExec.cpp:171; LOGGED FROM: rstudio::core::Error rstudio::session::modules::packages::(anonymous namespace)::getPackageState(const json::JsonRpcRequest &, json::JsonRpcResponse *) /Users/vagrant/workspace/IDE/macos/src/cpp/session/modules/SessionPackages.cpp:540

Some followups to help us reproduce this:

Do you use Packrat?

Does running this command in your R console also reproduce the error?

    > .rs.listInstalledPackages()

If it does, can you provide a traceback of the error? (using `traceback()` after it occurs)

**Comment by md0u80c9** [comment]
Hi,

No - I'm not using Packrat. Yes - listInstalledPackages reproduces the error and I've produced a traceback. I've done this from my iMac (which shows exactly the same issue) rather than the MacBook Pro so if there is a slight discrepancy between the first report and the second that will be why.

[Traceback.txt](https://github.com/rstudio/rstudio/files/2466207/Traceback.txt)

**Comment by jmcphers** [comment]
Thanks, that's very helpful!

@kevinushey can you take a look? It looks like this happens while rbinding the parts of the installed package list:

    5: do.call(data.frame, c(x, alis))
    4: as.data.frame.list(result, stringsAsFactors = FALSE)
    3: as.data.frame(result, stringsAsFactors = FALSE)
    2: .rs.rbindList(parts)
    1: .rs.listInstalledPackages()

which was changed in https://github.com/rstudio/rstudio/commit/1eddb65bf66bebf95c10f9245470a05510f4cf15

**Comment by kevinushey** [comment]
I can reproduce by creating an R package that doesn't declare a `Title` field in its `DESCRIPTION` file (I assumed all installed R packages would have this by default). I assume this is true in @md0u80c9's case as well, although it could be another similarly missing field.

@md0u80c9 could you try running this snippet of code and let me know what you see?

```R
pkgs <- list.files(.libPaths(), full.names = TRUE)
desc <- file.path(pkgs, "DESCRIPTION")
for (file in desc) {
  dcf <- read.dcf(file, all = TRUE)
  if (is.null(dcf$Title)) {
    fmt <- "Package '%s' is missing a 'Title:' field in its DESCRIPTION file"
    msg <- sprintf(fmt, dcf$Package)
    message(msg)
  }
}
```

**Comment by md0u80c9** [comment]
Yup - that does it; and it's actually one of my own packages that have triggered the error (a very early one that hasn't been let loose on GitHub let alone CRAN). Interesting that this doesn't trigger on the previous release of RStudio.

**Comment by md0u80c9** [comment]
As an extra suggestion - could the build tool reject the build of a package without critical fields (such as the Title field)? In this case it looks like what happened was a copy-paste of the rest of the package description data from another package and the Title field got omitted from the copying over.

**Comment by kevinushey** [comment]
Glad to hear this fixes the issue!

In this case I'm not sure if we want to reject the build outright since R would successfully build and load a package missing the Title field regardless, but such a tool might be useful as part of a separate 'audit' / 'diagnostic' feature for R packages.

**Comment by md0u80c9** [comment]
To be fair it almost certainly will fail CMD Check. However as it was a really early package I doubt CMD check got run. So I guess it’s a difference between whether the Title is ‘recommended’ (fails check) or ‘essential’ (fails the build).
