### ISSUE TITLE
Cannot uncomment RMarkdown code chunk from keyboard

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#3644]
**Steps to reproduce:**
* Create an RMarkdown document.
* Create a code chunk, e.g.
````
```{r}
a = 1
```
````
* Select the code chunk.
* Press Ctrl + Shift + C (will comment out the code under the default keyboard settings)
* Deselect the code chunk.
* Select the code chunk again.
* Press Ctrl + Shift + C

**Expected behavior:**
* The code chunk that was previously commented out should be uncommented.

**Actual behavior:**
* The code chunk gets these marks: `<!-- `, ` -->`, in addition to the `#` marks that were placed with the first Ctrl + Shift + C.

**Setup:** RStudio 1.2.1013, R 3.5.1, running on linux (debian buster/sid).

**Comment by kevinushey** [comment]
I'm not able to reproduce -- this is the behavior I see:

![comment](https://user-images.githubusercontent.com/1976582/46779235-be6c5c00-cccb-11e8-9588-d8d43ea7ed47.gif)

**Comment by david-cortes** [comment]
Update: it seems the bug is solved (but only for some specific lines) IF I manually select the code chunk that I just commented out, and manually remove the comment signs. I'm attaching a gif with what I get from Ctrl + Shift + C:
![rchunk_bug](https://user-images.githubusercontent.com/11860098/46788076-b4814200-cd39-11e8-85da-a137ad90a68b.gif)

**Comment by kevinushey** [comment]
Thanks for providing more information. I can reproduce in that case (where you have a reverse selection starting from the end of the chunk moving to the beginning of the chunk). Very strange that it depends on the selection direction but I guess we've seen weirder things!

**Comment by david-cortes** [comment]
Another funny thing: if I select the code chunk from the top, starting right at the line that has the backticks, then Ctrl + Shift + C will not do anything on it, but if I select it from one line above the backticks, it works as expected.

**Comment by shmuhammad2004** [comment]
I have the same problem here.

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.
