### ISSUE TITLE
Help-link to ":" opens in new screen (instead of in help-pane)

### ISSUE THREAD

**Issue by EmilBode** [rstudio/rstudio#3648]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem
In the console type ?base::seq
Scroll down to the "See also" section
Click the ":" - link

### Describe the problem in detail
A help screen opens in a new screen.

### Describe the behavior you expected
A help screen should open in the help-pane (as it does when clicking on one of the other links)

## Other information:
- When using the standalone R console, the help screen already has its own pane (which is reused normally)
- Running R from Terminal/Bash outputs help as raw text only - there is no link to click on
- The html of the link looks like this:
```` <code><a href="../../base/help/:">:</a></code> ````
- Opening the html in Safari works as expected
- I'm not sure if this is a bug in the way Rstudio handles these links, or that the links should point to someplace else (/help/colon or something like that).

Other similar instances:
- In the base package there is one other link to ":", from ?interaction
- From ?help, there is a link marked "?" pointing to "/Question". (which therefore works fine)
- When I naively implement links to special characters in my own code, the same problem comes up with "::", but "-", "!" and "%in%" work fine. OTOH, "?". "/" and "+" also break in R console and Safari

**Comment by ronblum** [comment]
@kevinushey I don't know if the code change will fix this, but in 1.2.1049 and earlier, such as 1.2.1013. clicking `:` does nothing. The other links work, though.

**Comment by jmcphers** [comment]
>  A help screen opens in a new screen.

This still repros in 1.3. Presumably the regex we use to fix Help pane links does not catch a link to `:`.
