### ISSUE TITLE
Unsaved files in between saved files hop to the end of the list a saved file is instead selected

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3653]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.1034
    OS Version      : MacOS High Sierra 10.13.6 and Red Hat 7.5
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Open a new project.

**Hopping Files I**

2. Create five R files and save each one after it's created. Call them `a1.R`, `b2.R`, `c3.R`, `d4.R`, and `e5.R`.
3. Click on the tab for `b2.R`.
4. Create a new file but don't save it—leave it as `Untitled1`.
5. Click on the tab for `b2.R`.
6. Create another new file but don't save it—leave it as `Untitled2`.
7. Click on the tab for `Untitled1`. The order of the tabs should now be
     - `a1`, `b2`, `Untitled2`, `Untitled1`, `c3`, `d4`, `e5`
     - with `Untitled1` selected.
8. Close the project
9. Reopen the project. The new order is:
     - `a1`, `b2`, `c3`, `d4`, `e5`, `Untitled1`, `Untitled2` 
     - with `d4` selected   

   
**Stable Files**

10. Click on the tab for `b2.R`.
11. Create another new file but don't save it—leave it as `Untitled3`.
12. Move tab `a1.R` between `b2.R` and `Untitled3`.
13. Click on the tab for `Untitled3`. The order of the tabs should now be
    - `b2`, `a1`, `Untitled3`, `c3`, `d4`, `e5`, `Untitled1`, `Untitled2` 
    - with `Untitled3` selected
14. Close the project
15. Reopen the project. The order is unchanged.

**Hopping Files II**

16. Click on the tab for `Untitled3.R`.
17. Create another new file but don't save it—leave it as `Untitled4`. The order of the tabs should now be
    - `b2`, `a1`, `Untitled3`, `Untitled4`, `c3`, `d4`, `e5`, `Untitled1`, `Untitled2` 
    - with `Untitled4` selected
18. Close the project
19. Reopen the project. The new order is:
    - `b2`, `a1`, `Untitled3`, `c3`, `d4`, `e5`, `Untitled1`, `Untitled2`, `Untitled4`
    - with `c3` selected

### Describe the problem in detail

The unsaved files are jumping to the end of the list, in the order they were created. The file selection changes to one of the saved files, based on the position of the hopping unsaved files. If one of the saved files is moved after an unsaved file was created, the unsaved file stays in place and the tab selection is unchanged.

### Describe the behavior you expected

The tab order and selection should remain unchanged when the project is closed and reopened.

**Comment by kevinushey** [comment]
I can reproduce this in RStudio v1.1 and v1.0, so at least this isn't a regression (seems like we've lived with this bug for a while). It would be nice to fix, though.
