### ISSUE TITLE
Feature Request: Option for default directory when opening projects

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/rstudio#3656]
Currently `File -> Open Project` defaults to `~`. Users may have different places where they keep R projects, e.g. `~/path/to/projects` and it would be helpful to expose this as an option.

**Comment by jmcphers** [comment]
Is this for RStudio Desktop? We already have this option for RStudio Server:

http://docs.rstudio.com/ide/server-pro/r-sessions.html (see `session-default-new-project-dir`)

**Comment by jmcphers** [comment]
This is a neat idea but it's been well over a year and it hasn't received any upvotes, support, or interest -- it isn't realistically on our roadmap for the next couple of years, so closing.
