### ISSUE TITLE
Sort on multiple columns in View()

### ISSUE THREAD

**Issue by guiastrennec** [rstudio/rstudio#3659]
### System details
    RStudio Edition :  Desktop
    RStudio Version :  1.1.456
    OS Version      :  Win 10 Pro
    R Version       :  3.5.1

### Steps to reproduce the problem
1) `View(mtcars)`
2) Click on the down arrow of the cyl column
3) Hold SHIFT and click on the down arrow of the  disp column
4) You should see that for the cyl and disp columns the sorting arrows are highlighted as follows:
![image](https://user-images.githubusercontent.com/7304883/46857526-6e93af00-ce09-11e8-98fa-e2da63e58e7a.png)

### Describe the problem in detail
Rstudio is only able to sort data.frames based on a single column. Despite that, the little highlighted sorting arrows seem to indicate that sorting could be applied to multiple columns. In the example mentioned above the column disp should have been sorted by ascending order.

### Describe the behavior you expected
Rstudio would sort a data.frame based on all the selected columns and in the order they have been selected.

**Comment by hammer** [comment]
Dupe of https://github.com/rstudio/rstudio/issues/1691?

**Comment by guiastrennec** [comment]
@hammer you are correct, my apologies this. I will leave the discussion to the original post and close this one.
