### ISSUE TITLE
Improve filters in View()

### ISSUE THREAD

**Issue by guiastrennec** [rstudio/rstudio#3660]
### System details
    RStudio Edition :  Desktop
    RStudio Version :  1.1.456
    OS Version      :  Win 10 Pro
    R Version       :  3.5.1

### Steps to reproduce the problem
1) `View(mtcars)`
2) Click on the filter button
3) Click on the cyl column filter box

![image](https://user-images.githubusercontent.com/7304883/46859217-7ce3ca00-ce0d-11e8-986b-d6a5324193e8.png)

### Describe the problem in detail
On numeric columns only the range slider is available, and on character columns only a search box

### Describe the behavior you expected
It would be nice if R code could be provided as a filter, e.g. `is.na(.)`, `. %in% c(4, 8)`, `. > 1`
It would make the View() option much more powerful

**Comment by kevinushey** [comment]
In the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio, we now provide a histogram for filtering (and allow the user to explicitly provide a value / range as well):

<img width="139" alt="screen shot 2018-10-12 at 10 37 34 am" src="https://user-images.githubusercontent.com/1976582/46884776-e1515a00-ce0a-11e8-9e55-b864bdd061ca.png">

Give it a try and let us know what you think.

**Comment by kevinushey** [comment]
Right, the filter is still just a range-inclusive filter -- more general rules around exclusion of rows based on some criterion are not yet possible.

**Comment by kerry-ja** [comment]
I think the ability to directly type in a number or range of numbers is great in the filter.  The ability to filter for `NA` or not `NA` would be another great addition.

**Comment by jmcphers** [comment]
We don't plan to make these filters any more powerful than they are; if you want more advanced filtering we suggest using R itself to filter the data set!

**Comment by karlmakepeace** [comment]
It would significantly improve the data exploration experience with RStudio if more powerful Data Viewer filters (e.g. RegEx or functions suggested above) were implemented.
