### ISSUE TITLE
Feature Request - Allow keyboard assignments for new files off of installed R Markdown templates

### ISSUE THREAD

**Issue by davidski** [rstudio/rstudio#3662]
Following up on the conversation on the RStudio Community - https://community.rstudio.com/t/assigning-a-keyboard-shortcut-for-a-rmarkdown-template

For users (both individuals and organizations) that regularly use one or more RMarkdown templates, the current workflow of going to `File:New File...` then having to select `From Template` and scrolling through the list of installed templates is very cumbersome and discourages users from using what may be standard templates for their organization. It would be wonderful to assign keyboard shortcuts to directly open a specific installed template.

Currently, this behavior can be partially implemented via creating an Add-In, though that's a bit cumbersome (and still requires users to setup a keyboard shortcut to the Add-In) and doesn't 100% replicate the default new file experience of creating an unsaved `Untitled` document.

**Comment by jmcphers** [comment]
Would customizing the New File template do what you want? Or do you often see >1 standardized R Markdown template in use?

https://github.com/rstudio/rstudio/issues/1632

**Comment by davidski** [comment]
Darm. I didn't see that issue! 😛 

Being able to choose the default New File template would be a minimum viable solution. More robustly, being able to specify keyboard shortcuts for different templates (corporate RMarkdown notebook, a Flexdashboard template, etc.) would be even better though. :)

**Comment by jmcphers** [comment]
We have implemented #1632 now and I think it does most of what's wanted here; a custom keyboard shortcut, if you really want one, is pretty easy to do with an add-in if needed!
