### ISSUE TITLE
'Tools -> Shell...' reports incorrect HOME on subsequent launches

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3663]
https://community.rstudio.com/t/problem-with-shell-in-rstudio-ide-1-1-456-windows/16212

---

### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1050
    OS Version      : Windows 10 x64
    R Version       : 3.5.1

### Steps to reproduce the problem

Run <kbd>Tools -> Shell...</kbd>, and then execute `echo $HOME`. You should see something like:

```sh
$ echo $HOME
/c/Users/kevin
```

All is well. Now, close and re-open the shell window, and try running `echo $HOME` again. I see:

```sh
$ echo $HOME
/c/Users/kevin/scratch/v11/=
```

Note that this is the active project directory; also note that a trailing `=` has been appended to the directory. We should preserve the original, 'true' `HOME` environment variable.

This reproduces in v1.1 and v1.0 so this is either a relatively old bug or perhaps something has changed in recent versions of Git for Windows.

**Comment by kevinushey** [comment]
(This may ultimately just be more evidence that we should get rid of this and use the Terminal pane exclusively?)

**Comment by lfmcmillan** [comment]
I'm having the same issue on my Windows 10 machine, and it's breaking all attempts to sync my Github project page with my local git repository, because git keeps looking in the wrong place for the SSH keys

**Comment by rich-rstudio** [comment]
verified on win 10 version 1.3.926
