### ISSUE TITLE
View() in RStudio Server needs better browser window title

### ISSUE THREAD

**Issue by igoldin2u** [rstudio/rstudio#3664]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.430
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

`View(mtcars)`, then pop out the viewer into a separate window

### Describe the problem in detail

The window title does not show the name of the dataset "mtcars". If you have multiple datasets popped out, it's hard to select the right browser window from Chrome's Window menu.

### Describe the behavior you expected

The browser window attribute should contain the name of the dataset.

**Comment by ronblum** [comment]
@igoldin2u Thank you for the suggestion. We'll consider it as we work on future versions of RStudio.

**Comment by jmcphers** [comment]
Yes, this is a general issue with pop-out windows. We're currently tracking this in https://github.com/rstudio/rstudio/issues/2427 (please comment/upvote there!). As pop-outs can contain multiple files we'd need to have a more complicated heuristic for updating the window title as the set of tabs changes, but it's certainly not undoable.
