### ISSUE TITLE
Source panel marking non-ASCII characters in Rmd file as "unexpected token"

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#3667]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1050
    OS Version      : Windows 10 Pro
    R Version       : 3.5.1

### Steps to reproduce the problem

- Open Rmd file
- Define variables with non-ASCII characters
- Reference those variables

### Describe the problem in detail

The source pane is marking all non-ASCII characters in my Rmd files as "unexpected token" but the code runs normally.

![image](https://user-images.githubusercontent.com/14981085/46896658-d6ff8200-ce43-11e8-9236-f75a7ce8ce37.png)

**Comment by kevinushey** [comment]
Can you share the actual content of the document / chunk just so we can easily copy + paste for testing?

**Comment by andresrcs** [comment]
Ok, this is the notebook [defensa_personal.zip](https://github.com/rstudio/rstudio/files/2480699/defensa_personal.zip)

**Comment by andresrcs** [comment]
Uninstalling / Reinstalling RStudio 1.2.1071 solved the problem
