### ISSUE TITLE
Slow scrolling and selecting in RStudio 1.2.1047 and previous preview version

### ISSUE THREAD

**Issue by jsgolub** [rstudio/rstudio#3668]
Hello,

I am forced to use the preview RStudio 1.2 because with my MacBook Pro hooked up to the LG UltraFine 27" Retina display, the Console has lagging text display in RStudio 1.1 (I type a letter, and there is a lag before it appears on the screen). This is a known problem. RStudio 1.2 Preview has fixed this.

Now there is a problem (the reason for this post) with laggy scrolling in the SOURCE window in RStudio 1.2.1047 and at least the previous version as well. When I scroll with the Magic Mouse or with the Mac's touchpad, there is a lag before the scrolling happens. There is also a lag in selecting text in the source window. When I click/drag to highlight text, there is a lag. This seems to be worse with a big external monitor (which I always use). This did not occur in previous preview versions of RStudio 1.2. For example, I have 1.2.752 on my computer and it does not have this laggy behavior.

I am not an experienced programmer, I am simply one researcher who relies on using RStudio! Help.

Thanks.

### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 1.2.1047 
    OS Version      :  macOS Mojave 10.14
    R Version       : 3.5.1

**Comment by jmcphers** [comment]
Sorry you're having trouble! 

What graphics settings do you see in Tools -> Global Options -> General -> Advanced?

Does forcing the the system to use OpenGL (not software) rendering and disabling the GPU backlist help? Note that you'll need to restart RStudio to see any difference.

(RStudio drops into software rendering for some known problematic hardware, and software rendering is much slower; the problem could be that RStudio thinks it has to use software rendering on your system.)

**Comment by jsgolub** [comment]
I think you are on to it:
1) It was set to auto detect.
2) Switching to OpenGL makes it much better
3) Switching to software makes it terrible again
4) Disabling GPU backlist doesn't seen to matter as much for both OpenGL and software. Hard to tell.

So it was not doing autodetect correctly. 

In RStudio Preview 1.2.752 where I did not have this problem, there is no option to switch these items around.

Another observation is the larger the window, the slower the scrolling and selecting in the source window. It's not the monitor, per se. It's the size of the window. A larger monitor allows a larger window. I am using a 5K monitor; that is going to be graphics intensive.

Note: I have a 1.5 year old 13" MacBook Pro, top specs

**Comment by kevinushey** [comment]
What graphics card(s) do you have on your system? (That is, what graphics card is reported in the 'About This Mac' dialog?)

**Comment by jsgolub** [comment]
Intel Iris Plus Graphics 650 1536 MB
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
3.5 GHz Intel Core i7
16 GB 2133 MHz LPDDR3

**Comment by kevinushey** [comment]
Thanks! One more question: are you by any chance using an external display with your laptop? (For example, are you using your laptop's builtin display while also hooked up to an external display?)

**Comment by jsgolub** [comment]
Yes. I use together. Laptop plus 27” external display. The bigger the window of RStudio the greater the lag. If I use a small sized window in my 27” display then it is fast. If I used a big sized window then it is slow. 

Also this is a 5K resolution 27” display: extremely high resolution! It’s the LG UltraFine 27” display. 

--

**Comment by kevinushey** [comment]
Gotcha. Thanks! I have an idea as to why we're incorrectly choosing software rendering in the auto-detect mode; we'll have to look a little more closely.

**Comment by kevinushey** [comment]
I suspect this was the commit that erroneously put RStudio into software rendering: https://github.com/rstudio/rstudio/commit/0b007ebd8975cff76a059f0c7d5849c55cb9669e

We'll have to see if we can find a safer fix for this particular issue.

**Comment by jsgolub** [comment]
Thank you very much.

**Comment by kevinushey** [comment]
Re-tracking in https://github.com/rstudio/rstudio/issues/3479.

**Comment by Ale-g-g** [comment]
After fighting for two days with lag in Rstudio, this thread solved my problem!!
  -Switched rendering engine to OpenGL
  -Forced Rstudio to use the Nvidia GPU (in Nvidia Control Panel)

I was struggling a lot with R markdown files with over only 190 lines.


I am using:
  -Lenovo Y580 Notebook, with an Intel i7 3630QM (4 cores, 2400MHz/3400MHz), Nvidia GTX 660m, 8gb Ram. 
  -Windows 10 Home

It is waaaaay better now

Thank you a lot guys!!!
