### ISSUE TITLE
Possible conflict between RStudio and Ubuntu 18.04 keyboard shortcuts

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#3672]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1050
    OS Version      : Ubuntu 18.04.1 LTS
    R Version       : 3.5.1

### Steps to reproduce the problem

1. In Rstudio running on Ubuntu 18.04, trying to add a cursor below the current cursor using the combination of keys <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>,
2. The result of this command is the switch of the workspace.

### Describe the problem in detail
As per the Rstudio Keyboard Shortcuts Help, the following shortcuts are available:

- Add Cursor Above Current Cursor: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>,
- Add Cursor Below Current Cursor: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>,
- Move Active Cursor Up: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Up</kbd>,
- Move Active Cursor Down: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Down</kbd>.

Since `Ubuntu 18.04`, the direction to switch between workspaces has been changed from horizontal to vertical. As a consequence, new keyboard shortcuts have been introduced for the following combinations of keys:

- Switch to above workspace: <kbd>Super</kbd>+<kbd>Page Up</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>, 
- Switch to below workspace: <kbd>Super</kbd>+<kbd>Page Down</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>,
- Move the current window to the above workspace: <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>Page Up</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>,
- Move the current window to the below workspace: <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>Page Down</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>.

Therefore, the operating system has priority, disabling RStudio shortcuts.
### Describe the behavior you expected
Expectation is RStudio shortcuts to work inside RStudio.

**Comment by ronblum** [comment]
@pascaloettli Thanks for opening the issue, following up from the earlier request!

**Comment by kevinushey** [comment]
We'd need to find alternate keybindings that users could use for this, but unfortunately most of the prime keyboard real-estate is already taken. :-/

**Comment by pascaloettli** [comment]
**======================= Disclaimer =======================**
**The following approach modifies the system default key binding** 
**This quick guide is intended for advanced users ONLY**
**Please read throughout the guide FIRST**
**========================================================**

One way would be for **an advanced user** working on `Ubuntu 18.04` to reassign the default key binding, following solution provided in [this thread on StackExchange](https://unix.stackexchange.com/q/394143).

### 1. Default system key binding

By default, as said in the first post, **gnome** on `Ubuntu 18.04` is using:

- Switch to above workspace: <kbd>Super</kbd>+<kbd>Page Up</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>,
- Switch to below workspace: <kbd>Super</kbd>+<kbd>Page Down</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>,
- Move the current window to the above workspace: <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>Page Up</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>,
- Move the current window to the below workspace: <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>Page Down</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>.

This can be checked using:
`gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-up`
which returns `['<Super>Page_Up', '<Control><Alt>Up']`

`gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-down`
which returns `['<Super>Page_Down', '<Control><Alt>Down']`

`gsettings get org.gnome.desktop.wm.keybindings move-to-workspace-up`
which returns `['<Super><Shift>Page_Up', '<Control><Shift><Alt>Up']`

`gsettings get org.gnome.desktop.wm.keybindings move-to-workspace-down`
which returns `['<Super><Shift>Page_Down', '<Control><Shift><Alt>Down']`

### 2. Reassignment (a.k.a please think twice before trying)
So from here, the solution is to reassign only using the <kbd>Super</kbd> key (a.k.a the _Windows_ key):

```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>Page_Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>Page_Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Super><Shift>Page_Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Super><Shift>Page_Down']"

```
This disables the <kbd>Ctrl</kbd>+<kbd>Alt</kbd> combination in gnome and allows RStudio to use it.


### 3. Return to default
To return to the default binding, use:
```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>Page_Up', '<Control><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>Page_Down', '<Control><Alt>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Super><Shift>Page_Up', '<Control><Shift><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Super><Shift>Page_Down', '<Control><Shift><Alt>Down']"
```

**Comment by pascaloettli** [comment]
**======================= Disclaimer =======================**
**The following approach modifies the system default key binding** 
**This quick guide is intended for advanced users ONLY**
**Please read throughout the guide FIRST**
**========================================================**

One way would be for **an advanced user** working on `Ubuntu 18.04` to reassign the default key binding, following solution provided in [this thread on StackExchange](https://unix.stackexchange.com/q/394143).

### 1. Default system key binding

By default, as said in the first post, **gnome** on `Ubuntu 18.04` is using:

- Switch to above workspace: <kbd>Super</kbd>+<kbd>Page Up</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>,
- Switch to below workspace: <kbd>Super</kbd>+<kbd>Page Down</kbd> or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>,
- Move the current window to the above workspace: <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>Page Up</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>,
- Move the current window to the below workspace: <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>Page Down</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>.

This can be checked using:
`gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-up`
which returns `['<Super>Page_Up', '<Control><Alt>Up']`

`gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-down`
which returns `['<Super>Page_Down', '<Control><Alt>Down']`

`gsettings get org.gnome.desktop.wm.keybindings move-to-workspace-up`
which returns `['<Super><Shift>Page_Up', '<Control><Shift><Alt>Up']`

`gsettings get org.gnome.desktop.wm.keybindings move-to-workspace-down`
which returns `['<Super><Shift>Page_Down', '<Control><Shift><Alt>Down']`

### 2. Reassignment (a.k.a please think twice before trying)
So from here, the solution is to reassign only using the <kbd>Super</kbd> key (a.k.a the _Windows_ key):

```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>Page_Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>Page_Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Super><Shift>Page_Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Super><Shift>Page_Down']"

```
This disables the <kbd>Ctrl</kbd>+<kbd>Alt</kbd> combination in gnome and allows RStudio to use it.


### 3. Return to default
To return to the default binding, use:
```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>Page_Up', '<Control><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>Page_Down', '<Control><Alt>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Super><Shift>Page_Up', '<Control><Shift><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Super><Shift>Page_Down', '<Control><Shift><Alt>Down']"
```

**Comment by kevinushey** [comment]
Ultimately I think it's okay to let this one pass by v1.2. If users need to, they can remap the associated commands as preferred (either remapping the OS's workspace management shortcuts, or remapping the RStudio commands to something new)

**Comment by jmcphers** [comment]
I don't think there's anything for us to fix here -- there's no other keybinding that we could reasonably use, and even on Ubuntu there are a variety of windowing environments, so trying to detect whether we're running under the one that has this issue would be very labor-intensive. Users with this specific combination will need to move either RStudio or their windowing environment's key bindings to resolve the conflict.

**Comment by gtritchie** [comment]
@ThomasSoeiro You had opened an issue entitled "Multiline edit does not work in RStudio Pro" a while back, and I moved it from the open-source rstudio repo to the rstudio-pro repo (which, unfortunately, isn't open to the public).

For RStudio Pro, support is done via the Posit Support team. So you'd want to open a ticket, e.g. you could start here: https://support.posit.co/hc/en-us/requests/new.

I haven't been able to reproduce the problem you reported when using Server or Server Pro 2022.12.0 with Chrome on Windows or Mac, but it does repro if running Chrome itself on at least some Linux platforms (e.g. this issue we're chatting in now).

Were you using Chrome from Linux, or on Windows or Mac?

**Comment by ThomasSoeiro** [comment]
@gtritchie 
Thanks for your feedback.

I'm not admin on the server, but according to `sessionInfo()` and the about dialog, I'm using Chromium on Linux:

```r
sessionInfo()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Red Hat Enterprise Linux Server 7.8 (Maipo)
# 
# Matrix products: default
# BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so
# 
# locale:
#  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8   
#  [6] LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices datasets  utils     methods   base     
# 
# loaded via a namespace (and not attached):
# [1] compiler_4.1.2 tools_4.1.2   
```

![image](https://github.com/rstudio/rstudio/assets/124079058/f4fe2f6c-19cd-44ca-8dde-e4174961fd79)
