### ISSUE TITLE
Keep "resize" event handler on even if mouse is not on the header of a table in the View pane.

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#3674]
If you want to resize a column inspecting a table in the View() pane, you need to be very careful keeping the mouse in the header otherwise the resizing action gets aborted (video 1). 
This gets even more troublesome when you want to enlarge the last column; you need to do it veeeeeery slowly to keep it from aborting (video 2).

Expected behavior: the resizing should continue from mousedown to mouseup, wherever the cursor is on the screen.

[Registrazione schermo 2018-10-15 alle 16.03.29.mov.zip](https://github.com/rstudio/rstudio/files/2479087/Registrazione.schermo.2018-10-15.alle.16.03.29.mov.zip)

[Registrazione schermo 2018-10-15 alle 16.16.48.mov.zip](https://github.com/rstudio/rstudio/files/2479093/Registrazione.schermo.2018-10-15.alle.16.16.48.mov.zip)

### System details

RStudio Edition : Desktop
RStudio Version : 1.2.1031 (daily)
OS Version : MacOs 14.0
R Version : 3.5.1

**Comment by ronblum** [comment]
@bakaburg1 Thank you for filing this issue. We will review it as we work on development of RStudio.

Reproduced with RStudio Desktop 1.1.463 and 1.2.1184-1 on MacOS 10.14.2, as well as RStudio Server 1.2.1186-1 on Ubuntu 16.04.5 using Google Chrome on MacOS 10.14.2. Compare to Excel, which behaves as desired.

**Comment by bakaburg1** [comment]
Uhm, the problem is still there
