### ISSUE TITLE
Allow non-fixed width fonts for plain text in rmarkdown documents

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rstudio#3679]
This is a feature request for the Rstudio interface to Rmarkdown documents. I use Rmarkdown and/or knitr to edit academic papers. These are 90% English text with some R code. 

Rstudio is a great R editor, but it has some weaknesses as a word processor. (So sometimes I go back to LyX, which has the opposite problem :-) .)

It would help a lot if I could use a different font to display plain text and for R code. Then code could still be in fixed width, but my plain paragraphs would be easier to read and edit. This would help make Rstudio into a paper-writing environment, as well as a programming environment.

**Comment by jmcphers** [comment]
We will not implement this, but there will be another way to do what you want in RStudio 1.4. Stay tuned!
