### ISSUE TITLE
Special characters removed when saving images in pdf using RStudio interface

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#3680]
I have an image with the `≤` special character. The character is visible in the RStudio image panel, but once I produce a pdf the character gets replaced by a `...`.

Possibly related to this problem: https://github.com/rstudio/rstudio/issues/3587

<img width="1075" alt="schermata 2018-10-16 alle 12 42 14" src="https://user-images.githubusercontent.com/777560/47013335-1e895500-d147-11e8-9926-355c15d71c44.png">
<img width="1174" alt="schermata 2018-10-16 alle 12 42 30" src="https://user-images.githubusercontent.com/777560/47013336-20531880-d147-11e8-8593-cdcdb8c607dc.png">

### System details

RStudio Edition : Desktop
RStudio Version : 1.2.1031 (daily)
OS Version : MacOs 14.0
R Version : 3.5.1

**Comment by kevinushey** [comment]
Can you please provide a reproducible example (a standalone bit of code that generates the plot we could try to render to PDF and reproduce the issue with)?

**Comment by bakaburg1** [comment]
Here's the code:

`ggplot(NULL, aes(x = 1, y = 1, label = '≤ foo bar')) + geom_label()`

The missing character will be there whether you save the pdf from the RStudio dialog or with `ggsave()`

**Comment by bakaburg1** [comment]
UPDATE:
using ggsave I get these warning:
```
Warning messages:
1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <e2>
2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <89>
3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <a4>
4: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <e2>
5: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <89>
6: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <a4>
7: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <e2>
8: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <89>
9: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <a4>
10: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <e2>
11: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <89>
12: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <a4>
```
I don't get them if I don't put the special characters.

**Comment by kevinushey** [comment]
``` r
library(ggplot2)
p <- ggplot(NULL, aes(x = 1, y = 1, label = '≤ foo bar')) + geom_label()
ggsave(p, filename = tempfile(fileext = ".pdf"))
#> Saving 7 x 5 in image
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <e2>
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <89>
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <a4>
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <e2>
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <89>
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted for <a4>
#> Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x,
#> x$y, : conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted
#> for <e2>
#> Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x,
#> x$y, : conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted
#> for <89>
#> Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x,
#> x$y, : conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted
#> for <a4>
#> Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x,
#> x$y, : conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted
#> for <e2>
#> Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x,
#> x$y, : conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted
#> for <89>
#> Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x,
#> x$y, : conversion failure on '≤ foo bar' in 'mbcsToSbcs': dot substituted
#> for <a4>
```

<sup>Created on 2018-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Given that this reproduces in plain R as well as RStudio, I think this should be filed elsewhere (e.g. on the ggplot2 repository)

**Comment by kevinushey** [comment]
(really, this is occurring in the `grid` package so it's either an issue there or perhaps the graphics device simply doesn't support it)

**Comment by YichaoCaiDBS** [comment]
Hi,

I am facing the same issue. 
Using `sprintf("A %s B", stringi::stri_unescape_unicode('\\u2192')` as the text in ggplot2 is fine when previewed in rstudio. However, the same error appears when `ggsave()` is called to save the plot as pdf and the arrow is replaced with `...`.
Saving as svg works fine.

Is there a fix to this?

**Comment by ronblum** [comment]
@YichaoCaiDBS Thanks for the notice.
1) Does the problem occur with R, outside of RStudio?
2) Can you provide the full list of steps so that we can try to reproduce?
As mentioned above, if the problem occurs in R, outside of RStudio, then the issue should be reported elsewhere, as this issue repository is intended for RStudio-specific issues. Thanks!

**Comment by Salma-Mouchi** [comment]
try the function "cairo_pdf" from package "grDevices"

grDevices::cairo_pdf("example.pdf")
plot(1, 1, type = "n")
text(1, 1, "Δ")
dev.off()


I found this solution here:
https://stackoverflow.com/questions/55340751/special-characters-not-appearing-in-pdf
