### ISSUE TITLE
attempts to preview .Rmd currently fail

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3681]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1050+
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Attempt to Knit an R Markdown document (by clicking the Knit button).

### Describe the problem in detail

A new preview window is opened, but nothing happens (the spinner keeps spinning)

![screen shot 2018-10-16 at 9 24 10 am](https://user-images.githubusercontent.com/1976582/47031696-41a30d00-d125-11e8-8478-a3781be8e2d3.png)

### Describe the behavior you expected

Document should be opened and previewed as normal.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
