### ISSUE TITLE
Feature request: git push & pull keyboard shortcuts

### ISSUE THREAD

**Issue by marskar** [rstudio/rstudio#3685]
The RStudio keyboard shortcut I would like most is git push, but it's not in Tools > Modify Keyboard Shortcuts... or Tools > Keyboard Shortcuts Help.
I believe this be a feature request.
It's the one thing missing from my git workflow in RStudio:
- Ctrl+Alt+M opens up the Review Changes window, then I press
- Space or Enter to stage,
- Tab to edit the commit message, &
- Ctrl/Command+Enter to commit

Ideally, I would want to set git pull and git push to Ctrl+Alt+< and Ctrl+Alt+>, respectively.
Would I need to edit ~/.R/rstudio/keybindings/rstudio_commands.json
or
~/.R/rstudio/keybindings/editor_commands.json
?
If so, please let me know and feel free to close this issue. Thanks!

**Comment by kevinushey** [comment]
Thanks for the feature request!

Indeed, the commands are not currently rebindable -- this is something we should consider making possible.

**Comment by jmcphers** [comment]
QA, can you ensure that this is now possible using a German keyboard?

**Comment by marskar** [comment]
I don't have a German keyboard, but I can confirm that this works now with a US keyboard. I will close the issue.
![image](https://user-images.githubusercontent.com/12806339/107268216-d710ec00-6a15-11eb-957a-1aeead65d133.gif)
