### ISSUE TITLE
Error Installing xml2 and highlight packages on Windows

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#3686]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1061
    OS Version      :  Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem
Without having the xml2 and highlight packages installed, attempt to add a new tmTheme.

### Describe the problem in detail
An error occurs during package installation.

![error-installing-packages](https://user-images.githubusercontent.com/37987486/47068998-b1a3a880-d1a2-11e8-96a2-cd7428a4e226.png)

### Describe the behavior you expected
Packages install

**Comment by kevinushey** [comment]
I'll take a look.
