### ISSUE TITLE
Additional source windows cannot save files in RStudio 1.2.1060 

### ISSUE THREAD

**Issue by martinmodrak** [rstudio/rstudio#3688]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1060
    OS Version      :  Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

1) Open a file
2) Move the file to a new source Window (pop out)
3) Make a change to the file
4) Save the file

### Describe the problem in detail

When editing a file in a separate source window, the file cannot be saved (both by pressing Ctrl+S and clicking the Save icon). Moving the source windows back to the main Window results in changes being discarded. Attempting to close the window with changes shows the Save/Don't save dialog, but clicking any of the options results in no action and the source window remains open.

If the file being edited happens to be an RStudio notebook, the "R Notebook" status message at the top stays visible indefinitely after popping out the window.

### Describe the behavior you expected

The file is saved.

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1090.
