### ISSUE TITLE
Git GUI not working in desktop and server versions

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#3689]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.1061
    OS Version      : Windows 10 Pro and Ubuntu Server 16.04.5 LTS
    R Version       : 3.5.1

### Steps to reproduce the problem

- Commit staged changes

### Describe the problem in detail

When I try to commit staged changes the GUI stays loading for ever, I have this issue in windows desktop and linux server versions and with any git enabled project

![image](https://user-images.githubusercontent.com/14981085/47089251-ff8dd000-d1e5-11e8-8fd0-7f6a1033ae64.png)

**Comment by kevinushey** [comment]
Very likely same cause at #3688.

**Comment by andresrcs** [comment]
It's working again since build 1.2.1062
