### ISSUE TITLE
Add sort, filter, collapse/expand to data viewer for trees

### ISSUE THREAD

**Issue by hammer** [rstudio/rstudio#3690]
I prefer `listviewer::jsonedit` to `View` for nested/tree data (e.g. JSON) because it has the ability to sort, filter, and collapse/expand the data. It would be nice if these features were present in RStudio's data viewer.

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding what you're asking for, but the object explorer in RStudio does allow you to filter + expand/collapse data (although no sorting).

https://blog.rstudio.com/2017/08/22/rstudio-v1-1-preview-object-explorer/

![screen shot 2018-10-17 at 9 52 34 am](https://user-images.githubusercontent.com/1976582/47102754-63b69100-d1f2-11e8-8010-684483ccf614.png)

Can you be more specific as to which features you'd like to see?

**Comment by hammer** [comment]
Have you tried `listviewer::jsonedit`? A few things it does that RStudio's data viewer does not:

- Text search searches within collapsed elements
- Filter button runs a JMESPath query over data
- Collapse/expand all

**Comment by hammer** [comment]
If I were to change the title of this issue to be "Improve data viewer for trees", I'd add another feature request:

- Generate a `purrr::pluck` command for a selected element (as an alternative to the `[[` syntax currently generated)

**Comment by jmcphers** [comment]
This hasn't garnered any upvotes or attention in well over a year, so closing. If you'd still like to see these features, we recommend:

a) filing individual issues for specific improvements (e.g. for just expand/collapse all rather than an "improve lots of things" omnibus), and 

b) collecting some community support
