### ISSUE TITLE
Inherit system configuration for an integrated look and feel

### ISSUE THREAD

**Issue by kupiqu** [rstudio/rstudio#3691]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      :  KDE neon User Edition on top of Ubuntu 18.04 LTS (x86_64, linux-gnu)
    R Version       :  3.4.4

### Steps to reproduce the problem

RStudio look and feel is different from the rest of applications in KDE Plasma:  no global menubar, different color theme and icons.

### Describe the problem in detail

Other applications like Scribus also use their own Qt libs, yet they support exporting the Qt menubar, as well as are able to use the system color theme and icons.

### Describe the behavior you expected

An integrated RStudio desktop experience that respects the system configuration, specifically in what to globalmenu, color theme and icons refers. I understand this is not easy with the Server version, but should be plausible for the Desktop version, similarly to what Scribus does.

**Comment by kupiqu** [comment]
Also open/save dialogs are at odds with native KDE dialogs

**Comment by kupiqu** [comment]
One thing that got fixed in current preview release is the global menu, which is now correctly displayed according to KDE settings.

**Comment by kevinushey** [comment]
Do you see any platform-related warnings if you launch RStudio from the terminal? Normally Qt should automagically detect what type of UI is appropriate for the application at startup for us, but I wonder if that's not the case here for some reason.

Does setting `QT_QPA_PLATFORMTHEME` appropriately make a difference in your case? re: https://wiki.archlinux.org/index.php/qt

**Comment by kupiqu** [comment]
Unfortunately no option helped. It seems like icons and themes (classic, modern and sky) are Rstudio specific.

I guess the easiest for having native theme and dialogs would be to add a system theme to the list, which 
 relied on system Qt libs. Not sure how easy this is, but other Qt applications have specific themes and icons, yet are able to add system look and feel as an additional option, and use KDE native dialogs, although I guess they rely on system Qt libs.

Is there a reason why Rstudio cannot use system Qt libs if present?

**Comment by kupiqu** [comment]
If at least I could use open/save KDE dialogs I'd be very happy. If someone knows of a workaround, please share :)
