### ISSUE TITLE
Object Explorer instances from RStudio v1.1 can cause frozen '?' session/prompt in v1.2

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3692]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1061
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

With RStudio v1.1, open the object explorer with e.g.

```R
View(list())
```

Then, close RStudio. Next, try opening RStudio v1.2.

### Describe the problem in detail

RStudio opens, but fails to populate the tab with the object explorer, and the console prompt is stuck on a `?`.

### Describe the behavior you expected

The object explorer tab should restore without issue.

**Comment by dfalty** [comment]
Verified fixed from 1.1.458 to 1.2.1090.
