### ISSUE TITLE
cursor is offset when using unicode text with combining characters

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3698]
### System details

    RStudio Edition : All
    RStudio Version : v1.2.1061
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Copy + paste the following text into RStudio:

    åååååå

and move the cursor to the end of the line.

### Describe the problem in detail

The cursor goes too far:

![screen shot 2018-10-17 at 11 20 01 am](https://user-images.githubusercontent.com/1976582/47108615-f9f1b380-d200-11e8-8cf2-355efc3e2d83.png)

### Describe the behavior you expected

The cursor should be placed at the end of the line, following the last character.

**Comment by kevinushey** [comment]
We could potentially handle this by using the `String.prototype.normalize()` function on text insertion: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

**Comment by rcragun** [comment]
This bug does not only apply to combining characters. It also occurs with the script/italic characters (e.g. 𝜎). But the bug does not manifest for σ.

Use case where this is important: using italic Greek characters in Shiny input labels (so that they match the characters printed by MathJax).

**Comment by traversc** [comment]
The issue also affects the horizontal scroll bar and incorrectly soft-wraps text.  In general, I think code point normalization isn't going to help.  In the extreme case, you have zero-width characters (e.g. TAG characters e0001 - e007e) which don't have a normalization but still do offset the cursor position.  

Example:
```
x <- "Start󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡󠀡End"
nchar(x)
[1] 28 #incorrect width
nchar(x, type = "width")
[1] 8 #correct width
```

**Comment by jeanlain** [comment]
I can still reproduce this issue on recent versions of RStudio Desktop on macOS.
The problem affects autocompleted file paths that contained accented characters, in particular. 
This is quite annoying and this has not been fixed for years.
