### ISSUE TITLE
Display Python objects in the Environment pane 

### ISSUE THREAD

**Issue by khouakhi** [rstudio/rstudio#3702]
The defined objects using Python script are not displayed in the Environment pane of the IDE as in R script.

**Comment by subhomoyghosh** [comment]
It would be awesome to have this feature in Rstudio's Environment pane. Looking forward to reticulate's future version.

**Comment by markderry** [comment]
This one change would drive the adoption of Rstudio across our organization! Looking forward to this feature and would love to help.

**Comment by jtelleriar** [comment]
Could this still be implemented in RStudio v1.3?

**Comment by kevinushey** [comment]
Sorry, but we won't be able to get this in time for RStudio v1.3. We are however planning to have a much shorter release cycle for v1.4 and plan to implement this by then.

**Comment by BrunoIllipronti** [comment]
No other IDE apparently is close to having an environment panel implemented for Python (the same way it works in RStudio for R). Please, go for it and I am sure many people will stick with RStudio for multiple purposes (R / Pandas / Markdown / Notebooks)

**Comment by hugokoopmans** [comment]
We at [DIKW Intelligence](https://www.dikw.com)  also look forward to this feature so we can even better make use of RStudio in our data science classes

**Comment by mdancho84** [comment]
This would be huge! Would love to see this as it will help big time in having multilingual data scientists using Rstudio IDE (best DS IDE out there).

**Comment by jmcphers** [comment]
This has been implemented in https://github.com/rstudio/rstudio/pull/6862.

**Comment by subhomoyghosh** [comment]
Wow! Thank you all the developers and the entire community for making this happen. I am a big time Rstudio fan, can’t wait to use it!

**Comment by jtelleriar** [comment]
Yes. Thank you!

**Comment by R-Hannibal** [comment]
Closing this issue as Fixed.

This enhancement has been added to the 1.4 release, currently available for download on our [Daily builds](https://dailies.rstudio.com/) page. Users have started using and [enjoying it](https://github.com/rstudio/rstudio/pull/6862#issuecomment-637217741)!

**Comment by millermc38** [comment]
THIS. IS. AMAZING. Great work people--for me, this greatly improves my experience of working with python. I would be nice if you could just click on objects in the code as for R (I just use "View()" or click on the object in the environment for now), but such a small qualm in light of this awesome development.

**Comment by ronblum** [comment]
@millermc38 Thank you for the kind words! And I believe what you're looking for is in the [1.4 Wax Begonia dailies](https://dailies.rstudio.com). The request is at https://github.com/rstudio/rstudio/pull/6862. 

Note: the dailies are for testing purposes only.
