### ISSUE TITLE
Flashing scrollbar in Modify Keyboard Shortcuts

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3707]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1059
    OS Version      : MacOS 10.14 Mojave (probably all Mac)

### Steps to reproduce the problem

I believe it's necessary to enable automatic scrollbars (i.e. only show scrollbars when necessary) in System Preferences in order to reproduce this.

1. Tools -> Modify Keyboard Shortcuts
2. Type in a filter, such as `create` or `editor`; wait for the filter to be applied
3. Click the `(x)` in the filter textbox to clear the filter

### Describe the problem in detail

A vertical scrollbar appears in an unexpected (and completely useless) location.

<img width="613" alt="screen shot 2018-10-18 at 9 26 08 pm" src="https://user-images.githubusercontent.com/470418/47197665-7dec8e00-d31c-11e8-94ed-e676151602d3.png">

### Describe the behavior you expected

No scrollbar.

We have fixed this for a few other grids in RStudio, so this may be a matter of either porting those fixes to this grid or extending them. See https://github.com/rstudio/rstudio/pull/3078.

**Comment by pascaloettli** [comment]
I reproduce on MacOS `10.13.6 High Sierra` with RStudio `1.2.1065`. The scrollbar appears at the exact location of the vertical separation between panes (more precisely to the left of the separation.) You can see it if you first move the Keyboard Shortcuts widow to the left/right of its default position, before clearing filter. HTH
