### ISSUE TITLE
Plot in data.table by group is inconsistent with in terminal

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#3708]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.1061
    OS Version      : macOS 10.14, Ubuntu 16.04
    R Version       : 3.5.1

### Steps to reproduce the problem

The graphics produced by calling `plot` in data.table by group is inconsistent with that produced in terminal.

```r
library(data.table)
dt <- data.table(group = rep(c("A", "B", "C"), each = 10), x = 1:30)

par(mfrow = c(1, 3))
dt[, plot(x, main = group), keyby = group]
```

The resulted graphics in RStudio Plots pane is as follows:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/4662568/47216412-7342ff00-d3d7-11e8-8953-0e32cb7ed76f.png">

The graphics produced in terminal is correct:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/4662568/47216489-aab1ab80-d3d7-11e8-9d99-bca4c58cbf59.png">

However, if the plot window created from R terminal is resized, the plot title becomes incorrect, same with RStudio Server.

One walk around is always copy the symbol used in `by=`:

```r
library(data.table)
dt <- data.table(group = rep(c("A", "B", "C"), each = 10), x = 1:30)

par(mfrow = c(1, 3))
dt[, plot(x, main = group[]), keyby = group]
```

This issue is related to how data.table modifies group symbols in place. I'm not sure if RStudio could do anything about it or if an issue should be raised at R or data.table.

**Comment by kevinushey** [comment]
The issue is perhaps more clear with this code:

``` r
library(data.table)
dt <- data.table(group = rep(c("A", "B", "C"), each = 1), x = 1:3)
dt[, .Internal(inspect(group)), keyby = group]
#> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
#>   @7ffb18587eb8 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "A"
#> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
#>   @7ffb18174920 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "B"
#> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
#>   @7ffb149946b8 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "C"
#>    group V1
#> 1:     A  A
#> 2:     B  B
#> 3:     C  C
```

<sup>Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note that each STRSXP has the same address. I'm guessing that STRSXP is being stored and used as a reference for the plot title, but by the time it's referenced for plot generation, it points to the CHARSXP containing "C".

Given that, there is a simple workaround:

``` r
library(data.table)
dt <- data.table(group = rep(c("A", "B", "C"), each = 1), x = 1:3)

par(mfrow = c(1, 3))
dt[, plot(x, main = copy(group)), keyby = group]
```

ie, just use `copy()` to ensure that a copy is made as needed.

**Comment by kevinushey** [comment]
I think that this is ultimately something that needs to be fixed either on the data.table side, or in user code, so I don't think there is anything RStudio can (or should) do here (especially since the issue reproduces after resizing a plot outside of RStudio as well)
