### ISSUE TITLE
Killing a session with an open project does not restore project on relaunch

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#3709]
Occurs in RStudio Server:

**Repro Steps**
- Start a session
- Open project
- Kill rsession process (sudo kill -9 $(pidof rsession))
- Refresh browser window

When you return to the session, you will note that you are no longer in the project you were in before the crash.

**Comment by jmcphers** [comment]
This behavior is intentional (it keeps you from getting stuck in a crash loop). However, we could do better! Currently tracked in https://github.com/rstudio/rstudio/issues/3220.

**Comment by andresrcs** [comment]
Not restoring the default working directory afterwards, is also intentional for any reason?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by kfeinauer** [comment]
Agreed @andresrcs that we could restore the working dir - will tackle this in #3220
