### ISSUE TITLE
Respect OS input method (Ubuntu)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3714]
See: https://community.rstudio.com/t/cant-enter-special-characters-via-unicode-character-code-in-ubuntu-ctrl-shift-u/16642

We might want to set the `QT_IM_MODULE` environment variable on startup to match whatever is currently set by the system.

**Comment by pascaloettli** [comment]
(comment not visible)

**Comment by pascaloettli** [comment]
(comment not visible)

**Comment by pascaloettli** [comment]
(comment not visible)

**Comment by jmcphers** [comment]
Closed since we don't have any other reports or evidence that it repros in > 1.1.
