### ISSUE TITLE
dark theme not available on Mojave

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#3716]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1061
    OS Version      :  OSX 10.14
    R Version       : 3.5.1

I changed the editor theme to Vibrant Ink, a dark theme.
Accordung to the docs, then the overall theme of RStudio should switch to 
Dark theme. 
This does not happen, and there also is no Dark theme available in the dropdown list.

![2018-10-20_15-48-48](https://user-images.githubusercontent.com/157619/47256389-f7e95800-d47f-11e8-9c07-89188f9a6223.png)

**Comment by neuwirthe** [comment]
I upgraded to RStudio 1.2.1061 and the problem persists.
In fact, it only surfaces on my Desktop iMac, but not on my MacBook Pro.

**Comment by neuwirthe** [comment]
It turns out something was broken in the configuration files.
Removing ~/.rstudio-desktop solved the problem.

**Comment by kevinushey** [comment]
Note that dark themes only activate when using the Modern theme -- from your screenshots, it looks like you were using a dark editor theme with the Classic IDE theme in which case I would expect the behavior you saw.
