### ISSUE TITLE
Rstudio parsing/knitting rmds on startup causing slowness

### ISSUE THREAD

**Issue by dpastoor** [rstudio/rstudio#3720]
### System details

    RStudio Edition : Desktop - nightlies over last couple months + Oct 16th preview
    RStudio Version : 
    OS Version      : OSX
    R Version       : 3.5.1

### Steps to reproduce the problem

When starting Rstudio, the git gui clearly shows a number of Rmarkdowns in a packrat project flashing up on the change as being knit. (see screenshot below) Furthermore, when then doing a sessionInfo() immediately after starting, can see dependencies related to knitting have already been attached. 

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6
 [6] tools_3.5.1     yaml_2.2.0      tinytex_0.6     Rcpp_0.12.18    stringi_1.2.4  
[11] rmarkdown_1.10  knitr_1.20      xfun_0.3        stringr_1.3.1   digest_0.6.15  
[16] packrat_0.4.9-3 evaluate_0.10.1
```

![image](https://user-images.githubusercontent.com/3196313/47267534-25cbac80-d513-11e8-9c59-234f239667ca.png)

When starting from the terminal (either Rstudio terminal or iterm2, git does not notice any changes, and the expected sessionInfo characteristics are seen (only packrat attached)

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.1  tools_3.5.1     packrat_0.4.9-3
```

This leads me to believe Rstudio is doing some scanning on session initiation. When there are malformed Rmarkdowns or many in a project, it causes noticeable delays in the startup time and/or errors.

**Comment by ronblum** [comment]
@dpastoor Thanks for letting us know about the issue. Would you mind checking if this is still an issue in [the most recent daily builds](https://dailies.rstudio.com) or [the current preview](https://www.rstudio.com/products/rstudio/download/preview)?

**Comment by dpastoor** [comment]
@ronblum I can confirm it is still present in the preview version. I can check on the daily version (I stopped using daily a couple weeks ago as the hi-res was having rendering problems on OSX). 

I can also 'confirm' this is related to packrat's interactions with the files, as by ignoring virtually all the project folders the performance degradation goes away.

I can see if I can work up a reproducible fake repo if that would help.

**Comment by kevinushey** [comment]
This is an issue caused by Packrat rendering R Markdown documents behind the scenes in an effort to discover dependencies. See also: https://github.com/rstudio/packrat/pull/513

**Comment by dpastoor** [comment]
@kevinushey yes I assumed as much - in looking at 513 one thing that was unclear to me is there a way to set Rstudio to not perform this itself, and rather only happen if an explicit packrat::snapshot() call is run.

I care 'less' about the slow snapshot when I have run it myself, more-so when the project is basically frozen for the first minute or so after booting up because of that going on in the background.

**Comment by jmcphers** [comment]
We have disabled auto-snapshotting from RStudio, so this shouldn't be an issue any more.
