### ISSUE TITLE
segfault immediately ends session - could an abort facility be added?

### ISSUE THREAD

**Issue by wdkrnls** [rstudio/rstudio#3722]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1015
    OS Version      : Manjaro 
    R Version       : 3.5.1

### Steps to reproduce the problem

Tried to optimize an objective function which includes the besselK function with nlm.

### Describe the problem in detail

RStudio immediately ended the session, forcing me to reopen the project.

From Emacs/ESS I saw this output:

 *** caught segfault ***
address 0x563dfef2ac98, cause 'memory not mapped'

Traceback:
 1: besselK(d, nu)
 2: Matern(distance, range = beta, smoothness = nu)

### Describe the behavior you expected

When executing the code in Emacs/ESS the code also caused a serious exception. However, ESS gave me the option to abort the command and continue on with the same R session. This is much less mysterious behavior.

**Comment by ronblum** [comment]
@wdkrnls I had marked this as an enhancement, based on the request for an abort option. However, are you still experiencing the segfault with the [latest daily builds](https://dailies.rstudio.com/) or the [preview distribution](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by jmcphers** [comment]
No response in over a year; closing.
