### ISSUE TITLE
Choosing "Preview" in the image save dialog will prompt an error

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#3723]
Choosing "Preview" in the image save dialog will prompt an error:
<img width="482" alt="schermata 2018-10-22 alle 17 34 10" src="https://user-images.githubusercontent.com/777560/47302051-cbb90d00-d620-11e8-84d7-de433e1ef528.png">

Any plot would do.

# System details
RStudio Edition : Desktop
RStudio Version : 1.2.1031 (daily)
OS Version : MacOs 14.0
R Version : 3.5.1

**Comment by kevinushey** [comment]
Works fine for me with the latest daily build of RStudio. Can you provide more information?

Does it work outside of your Google Drive folder?

**Comment by jmcphers** [comment]
Haven't heard back in well over a year and no other reports; closing.

**Comment by bakaburg1** [comment]
Sorry I totally forgot!
I solved it BTW. The error happened when a previous pdf preview window was already opened. You need to close it before doing a new preview. I guess it’s something about temporary file naming?
