### ISSUE TITLE
Citation highlight in cobalt theme barely visible

### ISSUE THREAD

**Issue by daijiang** [rstudio/rstudio#3724]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.969
    OS Version      : Mac osx
    R Version       : 3.5.1

### Describe the problem in detail

When writing an RMarkdown file with the cobalt theme, highlight of citations is barely visible. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/1696911/47308924-0b6ffc80-d601-11e8-9329-721a65b36ae0.png">

### Steps to reproduce the problem

Creat a new RMarkdown file in RStudio, then insert a citation, e.g. `[@citation]`. I see the darker background color behind it, but it is barely seen. 

### Describe the behavior you expected

It would be great to have a background color that contrasts more with the cobalt background color. Also, it would be great to change the color of citation keys too.

**Comment by daijiang** [comment]
Another small issue: when using "_" to make italic text within parenthesis, it won't work without a heading space.

![image](https://user-images.githubusercontent.com/1696911/47370851-9827c280-d6b4-11e8-9942-d6124ce7663f.png)

Thanks!

**Comment by diegotrindade** [comment]
Hi @daijiang,

Perhaps I'm a bit late. I was also wondering how to tackle this issue and just found out that if you add: 
```
.ace_list, .ace_markup.ace_list, .ace_storage {
color: #66db80;
  }
```
to any .rstheme file, you can choose the color of your preference.

Cheers
