### ISSUE TITLE
Package checking failure reported as success

### ISSUE THREAD

**Issue by md0u80c9** [rstudio/rstudio#3726]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1030
    OS Version      : Mac OS Mojave 10.14.1 Beta 4
    R Version       : 3.5.1

### Steps to reproduce the problem

Attempted to update packages on my MacBook Pro whilst forgetting to enable mobile tethering (so no internet access).

Clicked on Tools... -> Check for package updates...

### Describe the problem in detail

The dialog box reports that all packages are up to date.

However the console (correctly) reports:

Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'

### Describe the behavior you expected

The dialog box should reflect the console message by providing an error that the CRAN repository could not be accessed.

**Comment by ronblum** [comment]
@md0u80c9  Thank you for raising this concern. We will review it as we work on development of future versions of RStudio.

Confirmed on both MacOS Mojave 10.14 and Window 10.
