### ISSUE TITLE
Error when execute an indented python code chunk in R markdown

### ISSUE THREAD

**Issue by yimingli** [rstudio/rstudio#3731]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1060
    OS Version      : macOS 10.13.6 High Sierra
    R Version       : 3.5.1

### Steps to reproduce the problem

Put the following code in an R Markdown document:

<pre><code>
```{r}
library(reticulate)
```

* a bullet point

```{python}
print("""this unindented python code chunk works when knitting
    and when executed as a single chunk in RStudio""")
```

* second bullet point

    ```{python}
    print("""this indented python code chunk works when knitting,
        but raises error 'Error: unexpected indent (<string>, line 1)' 
        when executed as a single chunk in RStudio""")
    ```
</code></pre>

### Describe the problem in detail

An indented python code chunk does not execute interactively in RStudio, but worked fine when the whole document is knitted. R code chunks do not have this problem.

The reason I wanted to indent the code chunk is that the code chunk is nested under a markdown bullet point. If you knit the above code in a new R markdown document, you'll see the second bullet point's rendered result is desired.

### Describe the behavior you expected

It would be great if I could work interactively with an indented python code chunk.

**Comment by ronblum** [comment]
@yimingli Thanks for reporting this. We'll check it out as we work on future development of RStudio.

**Comment by jmcphers** [comment]
I think @hadley has asked about this in the past, too.

**Comment by kevinushey** [comment]
This fixes the issue:

```
trace(.rs.runUserDefinedEngine, quote({
   code <- .rs.trimCommonIndent(code)
}))
```

so we should probably just make a similar fix in `.rs.runUserDefinedEngine()`.

**Comment by R-Hannibal** [comment]
@yimingli, thanks again for finding and reporting this issue. We have a fix in place in our latest daily build (available [HERE](https://dailies.rstudio.com/)). 

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by yimingli** [comment]
@R-Hannibal thanks for the great work! I tested the reproducible example in my initial bug report; it works now!

**Comment by bob-ortiz** [comment]
Had this same problem, 

### System details
R version:
RStudio 2022.07.0+548 "Spotted Wakerobin" Release (34ea3031089fa4e38738a9256d6fa6d70629c822, 2022-07-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem

put the following code in markdown document:

```
---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(reticulate)
```


```{python, include=FALSE}
# Load one library
import re
```

```{python}
def limpieza_txt(lista):
    """Recibe una lista de textos, y retorna una nueva lista con cada item de la lista limpio."""
    list_clean = []
    for item in lista:
        list_clean.append(re.sub("[^a-z\sA-ZÀ-ž]", "", item.lower() ))
    return list_clean
```


```{python}
T1 = "Hola, ¿cómo están? Les parece si iniciamos la clase, es para alcanzar a ver todo. Les parece mejor si vamos rápido, ¿o mejor no?"
T2 = "El día es bonito. El perro va a casa. Hoy iremos a clase"
T3 = "Hoy veremos todo. No alcanzaremos a hacer todo. El día es feo. No quiero ir rápido"
texto = [T1, T2, T3]
texto
```

```{python}
limpieza_txt(texto)
```

### Describe problem

When interactively running each of the chunks in RMarkdown, the function "limpieza_txt" isn't created, it returns:
```
IndentationError: expected an indented block (<string>, line 4)
IndentationError: unexpected indent (<string>, line 1)
SyntaxError: 'return' outside function (<string>, line 1)
```

But it worked fine (returns the cleaned text, which is what the simple `limpieza_txt()` function does) when the whole document is knitted.
