### ISSUE TITLE
Review changes window hanging (git)

### ISSUE THREAD

**Issue by webbedfeet** [rstudio/rstudio#3733]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1060
    OS Version      : Mac OS X 10.13.6
    R Version       : 3.5

### Steps to reproduce the problem
Go to the CVS pane and press the Commit button. The "Changes" pane hangs without showing the files to commit
### Describe the problem in detail
When trying to commit on git, the "Changes" pane in the "Review Changes" popup window hangs, with the "spiral of death". Hence I cannot commit or push via RStudio and have to go down to the terminal.

![image](https://user-images.githubusercontent.com/370335/47430350-07f68580-d767-11e8-87ca-aedb3b898005.png)

### Describe the behavior you expected
Changes would show, and I could see the diffs in the pane below

**Comment by kfeinauer** [comment]
This should be fixed in the latest preview release. Could you try the new version and let us know if that fixes your issue?

**Comment by jmcphers** [comment]
Haven't heard back in over a year; closing. @webbedfeet, feel free to reopen if you're still seeing this.
