### ISSUE TITLE
Syntax highlighting for links doesn't work on first item in an indented list

### ISSUE THREAD

**Issue by isteves** [rstudio/rstudio#3735]
Hi there!  I noticed that when I have an indented list, links in the first item of the indented list are not highlighted.  Indentation does _not_ seem to affect syntax highlighting for italicized/bolded words.

![image](https://user-images.githubusercontent.com/25118334/47437206-bbd03300-d7b0-11e8-8d14-f52d42ef94d5.png)

I'm using Windows 10, RStudio 1.1.456.

**Comment by kevinushey** [comment]
Thanks for the bug report! I've reproduced this and we've actually regressed this behavior a bit in RStudio v1.2:

![screen shot 2018-10-24 at 9 15 28 am](https://user-images.githubusercontent.com/1976582/47445259-61fa4980-d76d-11e8-8de9-5f7800af1571.png)

I'll see if we can fix this cleanly.

**Comment by kevinushey** [comment]
Likely related to this commit:

https://github.com/rstudio/rstudio/commit/aa8476345fdf319c1059c75c6021711c9e2d84e7

IIUC the intention was to fix a highlighting issue with inline notes, e.g.

    This is some prose^[with an inline note](and some parentheses).

**Comment by isteves** [comment]
Glad it was reproducible!  I didn't realize there was so much regex behind syntax highlighting (though in retrospect it makes sense).

**Comment by kevinushey** [comment]
Indeed :-) Highlighting Markdown in particular is surprisingly challenging to get right!

**Comment by jmcphers** [comment]
@kevinushey Was this fixed by https://github.com/rstudio/rstudio/commit/f0e3e32576b9ead9ff035f8c99cc35e0b55a3cc9?

**Comment by kevinushey** [comment]
Indeed, this is now fixed.
