### ISSUE TITLE
title text is illegible when RStudio window is not focused

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3748]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1071
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Open an RStudio window, and then de-activate it.

### Describe the problem in detail

The 'RStudio' text in the title bar is very hard to read / ugly.

![screen shot 2018-10-25 at 3 44 10 pm](https://user-images.githubusercontent.com/1976582/47534643-f5667400-d86c-11e8-8a62-216ae3e11320.png)

### Describe the behavior you expected

Legible text.

**Comment by jmcphers** [comment]
No longer an issue now that we don't try to draw over the title bar.
