### ISSUE TITLE
RStudio (notebooks) not using custom knitr engines

### ISSUE THREAD

**Issue by dereksz** [rstudio/rstudio#3749]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.447 & 1.1.453
    OS Version      :  Windows Server & Windows 10 Pro (respectively)
    R Version       :  3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

### Steps to reproduce the problem

Create an RNotebook with a custom sql engine (`knitr::knit_engines$set(sql = silly_sql_engine)`). 

### Describe the problem in detail

RStudio continues to use the original knitr engine.

### Describe the behavior you expected

RSudio should use the new engine I have defined

### Reproducible example

Save this as an Rmd file.  Knit it to html and you see the engine being used.  Run all steps in RSudio and you can see the original engine is used even after being overridden.

````
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(dplyr)
con <- DBI::dbConnect(RSQLite::SQLite(), path = ":memory:")
seq <- 1:20
test_df <- data.frame(name=LETTERS[seq], value=seq)
copy_to(con, test_df)
```

```{sql connection='con'}
SELECT *
FROM test_df
```


Now override sql engine

```{r}
knitr::knit_engines$get()$sql
```

```{r}
silly_sql_engine <- function(options) {
  knitr:::engine_output(options, "no real query", "silly output")
}
```

```{r}
knitr::knit_engines$set(sql = silly_sql_engine)
```

```{sql connection='con'}
SELECT *
FROM test_df
```

# `sessionInfo()`

```{r}
sessionInfo()
```
````

**Comment by daslu** [comment]
@ronblum setting knit engines seems to be one of the new features of Rstudio 1.2.
https://blog.rstudio.com/2018/11/19/rstudio-1-2-preview-the-little-things/

For me, upgrading to 1.2 solved that.

**Comment by kevinushey** [comment]
That is indeed correct. This is why we include this blurb in the issue placeholder text:

> RStudio v1.2 is currently available as a preview release, from https://www.rstudio.com/products/rstudio/download/preview/. If you are reporting a bug with RStudio v1.1, it would be greatly appreciated if you could check if the issue also reproduces in the preview release before reporting an issue.

**Comment by dereksz** [comment]
I still have the same issue.  Setting a _new_ engine works, overriding an existing one does not.

**Comment by kevinushey** [comment]
Sorry, you are correct -- we indeed hard-code the behavior for SQL engines, even when an alternate has been registered. Sorry for closing the issue prematurely.

**Comment by dereksz** [comment]
Thanks for acknowldging that.  And I can at least register `sql2` now, so I'd be cool with a complete override being given a lower priority in the backlog now.

**Comment by daslu** [comment]
Interesting. 

Pasting here what I got -- redefining seems to work at my environment with (no need for `sql2`).



    library(dplyr)

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

    con <- DBI::dbConnect(RSQLite::SQLite(), path = ":memory:")
    seq <- 1:20
    test_df <- data.frame(name=LETTERS[seq], value=seq)
    copy_to(con, test_df)

    SELECT *
    FROM test_df

<table>
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">J</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>

Now override sql engine

    knitr::knit_engines$get()$sql

    ## function (options) 
    ## {
    ##     if (isFALSE(options$eval) && !isTRUE(options$sql.show_interpolated)) {
    ##         return(engine_output(options, options$code, ""))
    ##     }
    ##     varnames_from_sql = function(conn, sql) {
    ##         varPos = DBI::sqlParseVariables(conn, sql)
    ##         if (length(varPos$start) > 0) {
    ##             varNames = substring(sql, varPos$start, varPos$end)
    ##             sub("^\\?", "", varNames)
    ##         }
    ##     }
    ##     mexists = function(x, env = knit_global(), inherits = TRUE) {
    ##         vapply(x, exists, logical(1), where = env, inherits = inherits)
    ##     }
    ##     interpolate_from_env = function(conn, sql, env = knit_global(), 
    ##         inherits = TRUE) {
    ##         names = unique(varnames_from_sql(conn, sql))
    ##         names_missing = names[!mexists(names, env, inherits)]
    ##         if (length(names_missing) > 0) {
    ##             stop("Object(s) not found: ", paste("\"", names_missing, 
    ##                 "\"", collapse = ", "))
    ##         }
    ##         args = if (length(names) > 0) 
    ##             setNames(mget(names, envir = env, inherits = inherits), 
    ##                 names)
    ##         do.call(DBI::sqlInterpolate, c(list(conn, sql), args))
    ##     }
    ##     conn = options$connection
    ##     if (is.character(conn)) 
    ##         conn = get(conn, envir = knit_global())
    ##     if (is.null(conn)) 
    ##         stop2("The 'connection' option (DBI connection) is required for sql chunks.")
    ##     varname = options$output.var
    ##     max.print = options$max.print %n% (opts_knit$get("sql.max.print") %n% 
    ##         10)
    ##     if (is.na(max.print) || is.null(max.print)) 
    ##         max.print = -1
    ##     sql = paste(options$code, collapse = "\n")
    ##     query = interpolate_from_env(conn, sql)
    ##     if (isFALSE(options$eval)) 
    ##         return(engine_output(options, query, ""))
    ##     if (is.null(varname) && max.print > 0 && !is_sql_update_query(query)) {
    ##         res = DBI::dbSendQuery(conn, query)
    ##         data = DBI::dbFetch(res, n = max.print)
    ##         DBI::dbClearResult(res)
    ##     }
    ##     else {
    ##         data = DBI::dbGetQuery(conn, query)
    ##     }
    ##     output = if (!is.null(data) && ncol(data) > 0 && is.null(varname)) 
    ##         capture.output({
    ##             display_data = if (max.print == -1) 
    ##                 data
    ##             else head(data, n = max.print)
    ##             sql.print = opts_knit$get("sql.print")
    ##             if (!is.null(sql.print)) {
    ##                 options$results = "asis"
    ##                 cat(sql.print(data))
    ##             }
    ##             else if (out_format("markdown")) {
    ##                 options$results = "asis"
    ##                 first_column = display_data[[1]]
    ##                 if (is.numeric(first_column) && all(diff(first_column) == 
    ##                   1)) 
    ##                   display_data[[1]] = as.character(first_column)
    ##                 if (is_html_output()) 
    ##                   cat("<div class=\"knitsql-table\">\n")
    ##                 caption = options$tab.cap
    ##                 if (is.null(caption)) {
    ##                   rows = nrow(data)
    ##                   rows_formatted = formatC(rows, format = "d", 
    ##                     big.mark = ",")
    ##                   caption = if (max.print == -1 || rows < max.print) {
    ##                     paste(rows_formatted, "records")
    ##                   }
    ##                   else {
    ##                     paste("Displaying records 1 -", rows_formatted)
    ##                   }
    ##                 }
    ##                 if (identical(caption, NA)) 
    ##                   caption = NULL
    ##                 print(kable(display_data, caption = caption))
    ##                 if (is_html_output()) 
    ##                   cat("\n</div>\n")
    ##             }
    ##             else if (loadable("tibble")) {
    ##                 print(tibble::as_tibble(display_data), n = max.print)
    ##             }
    ##             else print(display_data)
    ##         })
    ##     if (options$results == "hide") 
    ##         output = NULL
    ##     if (!is.null(varname)) 
    ##         assign(varname, data, envir = knit_global())
    ##     if (!isTRUE(options$sql.show_interpolated)) 
    ##         query <- options$code
    ##     engine_output(options, query, output)
    ## }
    ## <environment: namespace:knitr>

    silly_sql_engine <- function(options) {
      knitr:::engine_output(options, "no real query", "silly output")
    }

    knitr::knit_engines$set(sql = silly_sql_engine)

    no real query

    ## silly output

    another_silly_sql_engine <- function(options) {
      knitr:::engine_output(options, "again, no real query", "magnificently silly output")
    }

    knitr::knit_engines$set(sql = another_silly_sql_engine)

    again, no real query

    ## magnificently silly output

`sessionInfo()`
===============

    sessionInfo()

    ## R version 3.5.3 (2019-03-11)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Manjaro Linux
    ## 
    ## Matrix products: default
    ## BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.3.so
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_IL.UTF-8    LC_NUMERIC=C           
    ##  [3] LC_TIME=en_IL           LC_COLLATE=en_IL.UTF-8 
    ##  [5] LC_MONETARY=en_IL       LC_MESSAGES=en_IL.UTF-8
    ##  [7] LC_PAPER=en_IL          LC_NAME=C              
    ##  [9] LC_ADDRESS=C            LC_TELEPHONE=C         
    ## [11] LC_MEASUREMENT=en_IL    LC_IDENTIFICATION=C    
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] dplyr_0.8.0.1
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.0        knitr_1.20        magrittr_1.5     
    ##  [4] htmldeps_0.1.1    tidyselect_0.2.5  bit_1.1-14       
    ##  [7] R6_2.4.0          rlang_0.3.1.9000  highr_0.6        
    ## [10] stringr_1.4.0     blob_1.1.1        tools_3.5.3      
    ## [13] DBI_1.0.0         dbplyr_1.3.0      htmltools_0.3.6  
    ## [16] yaml_2.2.0        bit64_0.9-7       assertthat_0.2.0 
    ## [19] digest_0.6.18     tibble_2.0.1      crayon_1.3.4     
    ## [22] purrr_0.3.1       memoise_1.1.0     glue_1.3.0       
    ## [25] evaluate_0.11     RSQLite_2.1.1     rmarkdown_1.10.12
    ## [28] stringi_1.3.1     compiler_3.5.3    pillar_1.3.1     
    ## [31] pkgconfig_2.0.2
