### ISSUE TITLE
ticked "Files" become invisible

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3751]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1074
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Check one of the boxes to the left of a filename in  "Files" pane. The checkbox disappears.

### Describe the problem in detail

<img width="142" alt="image" src="https://user-images.githubusercontent.com/362187/47571802-6b1f1e00-d907-11e8-9348-a730706b5f01.png">

### Describe the behavior you expected

I expected to see a ticked box.

**Comment by aronatkins** [comment]
Operations like "Delete" are still successful; this appears to just be a UI issue.

**Comment by ronblum** [comment]
Confirmed with "Classic" theme, as identified by @kevinushey.

[Testing note: Works with "Modern" and "Sky" theme, and only an issue on Desktop, not Server.]

**Comment by kevinushey** [comment]
Reported upstream to Qt: https://bugreports.qt.io/browse/QTBUG-70715. There are Chromium patches that will hopefully make it in for the Qt 5.12 release, although it may be too late.

There are two workarounds:

- Disable Chromium sandboxing with `QTWEBENGINE_DISABLE_SANDBOX=1`;
- Use the `zoom: 1.000001` trick (as was done in https://github.com/rstudio/rstudio/commit/6953071c56fc54522d0659051aca3b9231fcb8a7).
