### ISSUE TITLE
"rendered" publishing without rendering has UI issues

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3752]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1074
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create a directory. Let's call it "static".
2. Create a simple Rmd in that directory. Even just a title in the YAML plus one paragraph is sufficient.
3. Click the publish button in the editor pane.
4. Choose to publish the rendered document (NOT the source).

### Describe the problem in detail

An error message is displayed noting that "Only rendered documents can be published to RStudio Connect.". This statement is incorrect, as both source and rendered documents can be deploy to Connect. Instead, we should say something like, "You chose to publish a rendered document to RStudio Connect but a rendering is not available."

The second issue is with the publishing window. Given the error message, we should not be showing the window. It is left in an unfortunate state, with both "Publish From" and "Publish To" appearing, the "Publish To" input being squat and empty, and the "Title" being blank (not inherited from the directory name, as is expected).

<img width="644" alt="image" src="https://user-images.githubusercontent.com/362187/47572454-01077880-d909-11e8-9d23-4636b45a6075.png">

### Describe the behavior you expected

Given the expectation of a rendering, I expected a clear error explaining why I cannot publish my content and no publishing window.

**Comment by aronatkins** [comment]
Note: When the error dialog is dismissed, the publishing window also disappears.

**Comment by aronatkins** [comment]
Update: There is slightly different behavior after a successful deployment.

1. Render the Rmd to HTML.
2. Publish the rendered HTML content.
3. Remove the rendered HTML content.
4. Click the "Publish" button from the Rmd editor pane.

The following error is displayed:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/362187/47579890-564c8580-d91b-11e8-9636-4903a14cb48d.png">

AFTER this error is dismissed, the publishing dialog is shown:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/362187/47579910-65cbce80-d91b-11e8-8ccc-df260932a8c1.png">

Clicking "Publish" (because who wouldn't!) gives the following output in the Deploy pane:

```
Error in rsconnect::deployApp(appDir = "", account = "admin", server = "192.168.52.51",  : 
   does not exist
Execution halted
```

**Comment by gtritchie** [comment]
Agree the message in the dialog is misleading; I'm going to change to something like: "To publish the finished document to RStudio Connect, you must first render it. Dismiss this message, click Knit to render the document, then click the Publish button again."

**Comment by gtritchie** [comment]
The fact the publish dialog is showing as the same time, or after, this message, is definitely a bug. I didn't repro on my dev server build (behaved correctly), but am able to repro on the 1.2.1074 Mac desktop build.

**Comment by lsempe77** [comment]
I've got the same message but with RPubs. If I dismiss it, it doesn't allow publishing.
