### ISSUE TITLE
"rendered site" publishing without rendering has unexpected error/UI issues

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3754]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1074
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create a simple Rmd site. This can be as simple as trivial `index.Rmd` and `other.Rmd` files and an empty `_site.yml`. Do NOT render the site.
2. Open `index.Rmd` in the IDE for editing.
3. Click the publish icon in the editor pane.
4. Choose to publish the rendered site (NOT the source).

### Describe the problem in detail

An error message is displayed noting that the IDE "Could not find files to deploy" and "Error occurred while executing method". The "Publish" window is also displayed and has the same issues as described in #3752.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/362187/47574870-a53fee00-d90e-11e8-84d6-ddeff2756f9e.png">

### Describe the behavior you expected

Given the expectation of a rendering, I expected a clear error explaining why I cannot publish my content and no publishing window.

Filing this separately from #3752 since the error behavior is different.

**Comment by aronatkins** [comment]
Update: This error appears to happen for any static site deploy.

1. Create a new directory for your site.
2. Create two Rmd and a `_site.yml` file inside that directory.
3. Run `rmarkdown::render_site()` within that directory.
4. Open the `index.Rmd` and attempt to publish.

The "Could not find files to deploy" error is shown.

**Comment by aronatkins** [comment]
Update: The Console has the following:
```
Error in rle(toplevel) : 'x' must be a vector of an atomic type
```

**Comment by aronatkins** [comment]
Update: Attempting to publish an unrendered site from the UI after performing `rsconnect::deploySite` from the Console is also doing the wrong thing.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/362187/47580593-459d0f00-d91d-11e8-98e4-71ffc5a41e9f.png">

Note that we are attempting to deploy the source content of this site even though the previous deployment was of the rendered content.

Letting this deployment proceed errs (as expected) with the "Deploy" pane showing:

```
Preparing to deploy document...DONE
Uploading bundle for document: 7...DONE
Deploying bundle: 24 for document: 7 ...
Error: HTTP 403
POST http://192.168.52.51:3939/__api__/applications/7/deploy
You cannot change the type of application once deployed. Try deploying this as a new application instead of updating an existing one.
Execution halted
```

**Comment by aronatkins** [comment]
Update: Attempting to use push-button re-deployment after rendering the content with `rmarkdown::render_site` is also incorrect.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/362187/47580750-a7f60f80-d91d-11e8-9eb7-329fde26fd2d.png">

Note that we are still including all of the source content as well as the rendered `_site` directory.

The "Deploy" pane error also shows that we are attempting to deploy a "source" view of the site rather than a "rendered" view:

```
Preparing to deploy document...DONE
Uploading bundle for document: 7...DONE
Deploying bundle: 25 for document: 7 ...
Error: HTTP 403
POST http://192.168.52.51:3939/__api__/applications/7/deploy
You cannot change the type of application once deployed. Try deploying this as a new application instead of updating an existing one.
Execution halted
```

**Comment by gtritchie** [comment]
When I added ability to publish static (rendered) R Markdown websites from the editor publish button, I only considered scenario of an RStudio project set to build websites, such that site rendering is being done with the Build tab.

https://github.com/rstudio/rstudio/pull/3636

Scenarios involving a standalone folder containing an RMarkdown website, but no RStudio website project, lead to the issues described here.

**Comment by davebulaval** [comment]
I had the same issue with a file path with UTF-8 characters like `é`, `ê`, `è`.

The workaround i found si the use an file path without UTF-8 characters.

**Comment by agenis** [comment]
I had the same error: came from a special character in the path of the directory

**Comment by ronblum** [comment]
@agenis Thank you for raising this. Since it's an issue tied to a special character, can you please open a new issue for it? By the way, we have had some issue with special characters, for example #2035 with gi problems using ó and ü.

**Comment by csanchez1971** [comment]
> I had the same error: came from a special character in the path of the directory

Same here. It was driving me crazy and thanks to this answer I realized that my path had a "ä" on it, so I moved the files into another directory and it worked fine.
Thanks
