### ISSUE TITLE
feature request: whole-site push-button knitting

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#3756]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1074
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Inner hopes and dreams

I would love to have a way of triggering push-button rendering of a whole site. Maybe this is a "knit" button that shows up when editing the `_site.yml` or `_bookdown.yml` file. Maybe this is a "knit" menu option against each Rmd in the site.

Workaround is to drop to the console and:
```r
rmarkdown::render_site()
```

Encountered when testing site deployments (when I also hit #3752).

The single-file knit button can easily leave you in a state where some files have been rendered and others not, or only a subset of files have up-to-date renderings.

**Comment by jjallaire** [comment]
The Build tab has a "Build Website" button that should appear when you are in a website project:

<img width="501" alt="screen shot 2018-10-26 at 12 06 00 pm" src="https://user-images.githubusercontent.com/104391/47578496-8e51c980-d917-11e8-8580-319752af9d5b.png">

Does that do what you are looking for?

**Comment by aronatkins** [comment]
Interesting. The "Build" tab and "Build Website" don't show up for me, but maybe that's just because I've got N different types of content within an RStudio project.

For example:

```
regression-content/ # the project root
    shiny/
    plumber/
    rmd-site/
    static-site/
    # ... you get the idea
```

**Comment by kevinushey** [comment]
Does it come back up if you restart the IDE? Most of that detection happens during initialization so if you were to e.g. open an empty project and then add `_site.yml` and friends it wouldn't be used until the next time the whole IDE was restarted.

**Comment by jjallaire** [comment]
The project root needs to be the website root. That said, you can actually change this within Project Build settings (i.e. explicitly force the project to be a website project and specify which subdirectory your website lives within).

**Comment by aronatkins** [comment]
Ah. That doesn't really work for me, since I've got more than one site in this project.. I'm OK with this issue being closed if you guys think that a mixed-content project is uncommon.

**Comment by jmcphers** [comment]
>  I'm OK with this issue being closed if you guys think that a mixed-content project is uncommon.

I don't think it's common (we haven't had any other reports or queries along these lines in well over a year).
