### ISSUE TITLE
The `Run the Plumber API` button should start a fresh session to ensure reproducibility

### ISSUE THREAD

**Issue by shizidushu** [rstudio/rstudio#3758]
### System details

    RStudio Edition : Server 
    RStudio Version : 1.2.1060
    OS Version      : Debian GNU/Linux 9 (stretch)
    R Version       : R version 3.5.1 (2018-07-02)

### Steps to reproduce the problem
Assign a variable name `out_var` to 5 in R console.

Click Run API to test the following code

```r
#* testing
#* @serializer unboxedJSON
#* @get /testing
test <- function() {
  print(out_var)
}
```

It returns 5. But it should be an error. This behavior makes it hard to test the API. Please fix it. Thanks.

**Comment by ronblum** [comment]
@shizidushu Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.

**Comment by jmcphers** [comment]
This needs to be an option (sometimes you _do_ want to run the API in the current session). We're now tracking the work needed to run Plumber APIs as background sessions in https://github.com/rstudio/rstudio/issues/5190.
