### ISSUE TITLE
Add support for generating elliptic SSH keys for Git

### ISSUE THREAD

**Issue by matthewberryman** [rstudio/rstudio#3763]
### System details

    RStudio Edition : Community
    RStudio Version : 1.1.456
    OS Version      : 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

R Studio menu -> preferences -> Git/SVN

### Describe the problem in detail

No support for elliptic curve ssh keys.

### Describe the behaviour you expected

Support for ECDSA ssh keys

**Comment by ronblum** [comment]
@matthewberryman Thanks for the feature suggestion! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by jmcphers** [comment]
Would also be nice to add support for all the algorithms exposed by `ssh-keygen` (e.g. also `ed25519`) as well as setting the bit size for both RSA and elliptic keys.
