### ISSUE TITLE
Appearance Zoom change crashes Rstudio

### ISSUE THREAD

**Issue by jphelps13** [rstudio/rstudio#3765]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Windows 10 Pro, version 1803
    R Version       : 3.5.0

### Steps to reproduce the problem
try to change my Zoom (Tools; Global Options; Appearances) from my current value (110%) to any other and click apply

### Describe the problem in detail
Icon becomes spinning blue wheel; (Not Responding) at the top; Goes grey when I click; Doesn't start responding again.

### Describe the behavior you expected

Diagnostics-Report:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2521721/diagnostics-report.txt)

Cheers, Jonny

**Comment by kevinushey** [comment]
Do you have any better luck with the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio?

**Comment by jphelps13** [comment]
Thanks for the link, I've installed the preview version and it works fine. Cheers :)
