### ISSUE TITLE
Permit custom keybindings in the **console**

### ISSUE THREAD

**Issue by MichaelTuchman** [rstudio/rstudio#3767]
This is a feature request.

Some time ago, somebody requested in a feature in the old R support forums about being able to bind the previous command in the console to something besides the up arrow.  I tried to find this issue by filtering in the git, but nothing turned up.  But I would like to request the feature that the console support the same keybindings as the editor,  As one consequence among many, this means CTRL-E moves the cursor to the end of the line ***in both console and editor*** when I have emacs bindings active.  Additionally, the keybinding for previous **line** in the _editor_ would become the keybinding for previous **command** in the _console_, etc.

Please feel free to merge with existing issues.  I have made a good faith effort to find existing issues and add to them,but my searches came up null.

To the best of my knowledge, this feature is needed on both the Linux and Windows platforms.  I don't know anything about Macs, so I will refrain from speculation.

https://support.rstudio.com/hc/en-us/community/posts/212143467-Allow-re-mapping-of-previous-command-from-UP-to-something-else

**Comment by ronblum** [comment]
@MichaelTuchman This appears to be the same request, #3556. For what it's worth, it took me a few moments to find it, too, and I remembered seeing it come through! Feel free to add to it, as well.
