### ISSUE TITLE
[javac] error: Source option 5 is no longer supported. Use 6 or later.

### ISSUE THREAD

**Issue by Mailaender** [rstudio/rstudio#3769]
The bundled GWT currently won't compile on openSUSE Tumbleweed due to this:

```
[  134s] javac:
[  134s]     [mkdir] Created dir: /home/abuild/rpmbuild/BUILD/rstudio-1.1.456/src/gwt/bin
[  134s]     [javac] Compiling 10 source files to /home/abuild/rpmbuild/BUILD/rstudio-1.1.456/src/gwt/bin
[  134s]     [javac] error: Source option 5 is no longer supported. Use 6 or later.
[  134s]     [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.
```

Is it possible to update it? Java 5 seems rather ancient.

**Comment by kevinushey** [comment]
We're currently preparing RStudio v1.2 for release (hopefully early next year), and this release will build against Java 8. If you really need to build RStudio v1.1 still, you can patch `src/gwt/build.xml` and try setting the Java version to something newer.

Here's where we currently set it to 1.8:

https://github.com/rstudio/rstudio/blob/master/src/gwt/build.xml#L87
https://github.com/rstudio/rstudio/blob/master/src/gwt/build.xml#L95

Not sure if there are other required patches to get v1.1 to compile against newer Java standards though (there may well be)

**Comment by jmcphers** [comment]
We can't help compiling 1.1 against Tumbleweed, but indeed 1.2 should work.
