### ISSUE TITLE
Knitting website source file other than index.Rmd shows index.Rmd output in Viewer

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3772]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.1074
    OS Version      : macOS, probably any
    R Version       : 3.5.1

### Steps to reproduce the problem
Create a simple R markdown website project with at least one page other than index.Rmd. For example, use https://github.com/gtritchie/MyWebsite.

Open a page source file other than index.Rmd in the editor. Make sure there is no rendered website via Build tab/More/Clean All. Now click Knit (to HTML) in the editor. The page is rendered (as seen in the RMarkdown tab) but result of index.Rmd (which doesn't exist) tries to load in the viewer.

### Describe the problem in detail

![2018-10-28_14-03-11](https://user-images.githubusercontent.com/10569626/47621794-3e5f3800-daba-11e8-84c3-57e5b714b97f.png)

### Describe the behavior you expected
Ideally, we'd do something to let user know they need to knit the entire site via the build tab, or do it for them, before making incremental edits and knits.

**Comment by ronblum** [comment]
Confirmed that this also occurs elsewhere, e.g. RStudio Server on Red Hat 7.5. However, this works in MacOS Desktop 1.1.456, so I'm marking this as a regression.
