### ISSUE TITLE
[feature request] RStudio to automatically save file as Rmd when given extension

### ISSUE THREAD

**Issue by petyaracz** [rstudio/rstudio#3775]
### System details

    RStudio Edition : Desktip
    RStudio Version : 1.1.456
    OS Version      : osx 10.13.2
    R Version       :  3.5.1

### Steps to reproduce the problem

1. Open RStudio
2. Open a new tab w/ cmd+shift+n
3. Save tab w/ cmd+s as "tab.Rmd"

### Describe the problem in detail

File is saved as "tab.R.Rmd".

### Describe the behavior you expected

File is saved as "tab.Rmd"

**Comment by nteetor** [comment]
I see the file saved as `tab.Rmd.R`. I would love for the IDE to not append ".R" to an assortment of other file types.

**Comment by kevinushey** [comment]
As an alternative, you can explicitly change the file type of the open file:

<img width="296" alt="Screen Shot 2019-05-20 at 2 13 44 PM" src="https://user-images.githubusercontent.com/1976582/58052378-8652b480-7b09-11e9-8864-444f1aa6a917.png">

Then, the default extension associated with that file type will be used.

**Comment by nteetor** [comment]
Good to know. Thank you for the alternative.
