### ISSUE TITLE
rsconnect deployment success not signaled in Deploy tab on Windows w/curl

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3778]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1074
    OS Version      : Windows 10 x64
    R Version       : 3.5.1

### Steps to reproduce the problem

Try to deploy a document to RStudio Connect.

### Describe the problem in detail

The 'Deploy' tab gets stuck, and just spins. 

![screen shot 2018-10-29 at 10 53 22 am](https://user-images.githubusercontent.com/1976582/47669771-df0c3100-db68-11e8-8a84-31691511eb40.png)

(Note that the output seen here may be different depending on timing; my guess is the last set of buffered output is never delivered after deployment finishes successfully)

### Describe the behavior you expected

RStudio successfully acknowledges the successful deployment.

Note that the deployment _does_ succeed (I can see the deployed document on Connect) it's just the IDE gets stuck thinking the deployment never finished.

**Comment by jmcphers** [comment]
I think this might actually be a bug in the rsconnect package. The IDE supplies a callback function to be invoked when deployment is complete; if that isn't invoked then it things deployment never finishes (which looks like what's happening here)

**Comment by kevinushey** [comment]
Also filed on the rsconnect side by a user at https://github.com/rstudio/rsconnect/issues/310.

Let's keep both issues opened (and linked) and resolve them together once we find where the appropriate fix should lie.

**Comment by kevinushey** [comment]
FWIW if I rebuild `rsconnect` to use the `curl` HTTP method by default on macOS then deployment fails:

``` r
> rsconnect:::defaultHttpFunction()
[1] "curl"
> rsconnect::deployDoc("~/scratch/abc.Rmd")
Discovering document dependencies... OK
Preparing to deploy document...
Error: HTTP -1
GET https://beta.rstudioconnect.com/__api__/applications?filter=account_id:40&filter=name:abc&count=100&offset=0
Unexpected json response: {"applications":[],"count":0,"total":0,"continuation":"SdixEv5"} 
```

No idea if it's related but it'd be nice to have that working on macOS.

**Comment by jmcphers** [comment]
@ronblum has seen this too; it's definitely an issue with the rsconnect package rather than the IDE. I'm going to close this and track the issue over at https://github.com/rstudio/rsconnect/issues/310. Once we've gotten to the bottom of this I think we can do a CRAN release of rsconnect and stop bundling rsconnect in the IDE.
