### ISSUE TITLE
[Feature enhancement] Stitch syntax awarenes defining a section for the Document outline

### ISSUE THREAD

**Issue by holgerman** [rstudio/rstudio#3783]
Hi, 

I love the pure and easy way of writing reports in RStudio based on R-files applying stitch syntax as described in https://support.rstudio.com/hc/en-us/articles/200552276-Creating-Notebooks-from-R-Scripts. This is often much quicker for me than using Rmd files.
Thereby, I need to structure the document while writing code (using the great document outline function of RStudio) and I need structure (headings and table of content) in the compiled document.

However, there does not seem a way that a section heading is recognized by both, the document outline and - after compliling in a html - as markdown heading. The reason is that the document outline is unaware that  `#' # Any Section Title ---------------` means in stitch that this will become a markdown heading after compiling (see also code example below)

 It would be great if the document outline would be aware of stitch-like headings and recognize  `#' # Anytext ---------------`  as start of a section.

### Steps to reproduce the problem
Create following R file and open the Document Outline and Compile the Report:
```
#' ---
#' output:
#'   html_document:
#'     toc: yes
#'     toc_float: true
#' ---
#'

#' # The heading recognized as markdown in compiled report -----------------------------------------------------------------

# The heading recognized by the document outline -------------------------------------------------------
```

### System details

    RStudio Edition : <Desktop>
    RStudio Version : 1.1.442
    OS Version      : Windows 7 Professional
    R Version       :  3.4.2 (2017-09-28)

### output of sessionInfo() 
```
sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_10.0.6     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] compiler_3.4.2  backports_1.1.2 magrittr_1.5    rsconnect_0.8.8 rprojroot_1.3-2 htmltools_0.3.6 tools_3.4.2     yaml_2.1.18     Rcpp_0.12.13    stringi_1.1.5  
[11] rmarkdown_1.9   knitr_1.20      stringr_1.2.0   digest_0.6.12   evaluate_0.10.1
```

**Comment by ronblum** [comment]
@holgerman Thank you for the suggestion! We'll take a look at it as we continue development of RStudio.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/3647.
