### ISSUE TITLE
Feature Request: open two files Together and get a visual difference

### ISSUE THREAD

**Issue by verajosemanuel** [rstudio/rstudio#3788]
Here a capture from Notepad++, an editor I use sometimes just for this feature when I need to compare two files and get a glimpse of the differences

![compare-results](https://user-images.githubusercontent.com/15836677/47776753-6d142300-dcf3-11e8-8619-699ae7b387a0.png)

**Comment by ronblum** [comment]
@verajosemanuel Thank you for the suggestion! We'll take a look at it as we continue development of RStudio.

(Note: I use Diff Compare myself; this is very useful.)

**Comment by verajosemanuel** [comment]
thanks a lot

**Comment by jmcphers** [comment]
This is a neat idea but hasn't received much attention in years and as it's outside the core IDE scope probably won't realistically be on our roadmap.
