### ISSUE TITLE
snippets are duplicated when inserted with Shift+Tab

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3790]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1079
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

In an R document, on a blank line, try typing:

    ts<Tab>

### Describe the problem in detail

The timestamp snippet is executed twice, such that output in the document is e.g.

```
# Wed Oct 31 09:32:28 2018 -----------------------------# Wed Oct 31 09:32:28 2018 ------------------------------
```

### Describe the behavior you expected

The snippet should only be inserted once.

**Comment by rich-rstudio** [comment]
verified on build 1.2.1090
