### ISSUE TITLE
"Check for updates" doesn't offer an update

### ISSUE THREAD

**Issue by kenahoo** [rstudio/rstudio#3801]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Mac OS X 10_13_6
    R Version       : 3.5.1 (2018-07-02)

### Steps to reproduce the problem

Using an out-of-date version of RStudio, do "Help" -> "Check for Updates".

### Describe the problem in detail

I'm running RStudio 1.1.456, and as of this writing the latest version of RStudio is 1.1.463:

<img width="928" alt="screen shot 2018-11-01 at 11 43 45 am" src="https://user-images.githubusercontent.com/111939/47865904-72dd3780-ddcb-11e8-887a-36f3b72cc3d7.png">

However, when I do "Help" -> "Check for Updates" in the RStudio app, it says "You're using the newest version of RStudio":

<img width="656" alt="screen shot 2018-11-01 at 11 31 48 am" src="https://user-images.githubusercontent.com/111939/47865478-51c81700-ddca-11e8-95c5-fb865ae38807.png">

Any way to get information about what it thinks is the latest available version, what URL it's checking for that information, what network/parsing errors might have been encountered, etc.?

### Describe the behavior you expected

Latest version should be offered for download.

Note: because of the nature of this problem, I have to use an outdated version of RStudio to check it, so I can't tell if it's been fixed in the latest version.

**Comment by jmcphers** [comment]
This is expected. The website and the "check for updates" version aren't always the same -- we usually wait a few weeks (or more) after updating the website so we have a chance to pull back the build if there are problems with it (once it's in Check for Updates many, many people are going to get it!).

**Comment by kevinushey** [comment]
We could perhaps provide a bit more granularity in the behavior here. There's two times the user gets notified that an update is available:

1. On application startup,
2. When explicitly requested / checked.

We should let users know an update is available when asked explicitly, but avoid automatically notifying all users until some separate flag has been set.

**Comment by kenahoo** [comment]
Yes, I agree with Kevin - if I explicitly go to the menu and ask whether an
update is available, and it says there isn't one, that just feels false.

Additionally, most of the time when I check whether an update is available,
it's because I'm seeing a bug or missing feature in RStudio, and in those
cases, it would behoove you to give me the update so I can actually do the
early version checking you want.

 -Ken

**Comment by jmcphers** [comment]
> We could perhaps provide a bit more granularity in the behavior here. There's two times the user gets notified that an update is available:

We do indeed have separate versions for this -- the "active" version (what you get if you manually check for updates) and the "passive" version (what you get just by starting RStudio). 

I've just promoted 1.1.463 to the "active" version, so you'll get it if you manually request an update.
