### ISSUE TITLE
insertion of space during autocompletion session mangles inserted result

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3802]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1084
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

Open a blank R document, and try typing:

    base::r

and wait for the autocompletion list to pop up. `base::range()` should appear as the first completion candidate. Then, insert a single space, and then press Enter to accept the completion.

### Describe the problem in detail

The completion entry is completed as `base::rrange()`. Note that the `r` is duplicated.

### Describe the behavior you expected

We should instead complete as `base::range()`.

This is a regression from v1.1 behavior, so filing for v1.2.

**Comment by rich-rstudio** [comment]
verified on build 1.2.1090
