### ISSUE TITLE
attempts to run `system("git")` can fail due to rpostback-askpass

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3805]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1087
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

Within an RStudio session, try executing in the R console:

``` r
system('printf "protocol=https\nhost=something.com\n" | git credential fill')
```

### Describe the problem in detail

The command fails to run, citing a missing `rpostback-askpass`:

```
> system('printf "protocol=https\nhost=something.com\n" | git credential fill')
fatal: cannot run rpostback-askpass: No such file or directory
fatal: could not read Username for 'https://something.com': Device not configured
```

### Describe the behavior you expected

Commands requiring the use of `rpostback-askpass` should work.

### Notes

The issue here occurs because we only put the `rpostback` utilities on the PATH when required for the subprocesses we launch, e.g.

https://github.com/rstudio/rstudio/blob/c07885367a26032da3270012b8056ae1c8192676/src/cpp/session/modules/SessionGit.cpp#L124-L126

But we set `SSH_ASKPASS` and `GIT_ASKPASS` unconditionally:

https://github.com/rstudio/rstudio/blob/c07885367a26032da3270012b8056ae1c8192676/src/cpp/session/modules/SessionGit.cpp#L3352-L3359

Some options:

1. Only set `SSH_ASKPASS` and `GIT_ASKPASS` during the lifetime of our own calls to `git` and friends;

2. Ensure that the `rpostback` directory is on the PATH by default as well.

Also worth evaluating: we could we just set these environment variables to the full paths to these executables, so they work regardless?

**Comment by kevinushey** [comment]
There's also this old support thread, but we haven't heard much grief since v1.0 about this: https://support.rstudio.com/hc/en-us/community/posts/200694007-rpostback-askpass

**Comment by ronblum** [comment]
@kevinushey I just got this error on Ubuntu 16.04.5 using RSP 1.2.1115-1.

**Comment by jeroen** [comment]
Here is a better example. To reproduce this you need to make sure your ssh key has a passphrase.

Then try to add it to ssh-agent in R: `system("ssh-add")`. If your key has a passhprase, ssh will call back to `SSH_ASKPASS` for the password entry dialog. You need to put that on the path to make it work:

```r
  # Try to put 'rpostback-askpass' on the path in RStudio
  rs_path <- Sys.getenv('RS_RPOSTBACK_PATH')
  git_askpass <- Sys.getenv('GIT_ASKPASS')
  if(nchar(rs_path) && !nchar(Sys.which(git_askpass))){
    PATH <- Sys.getenv("PATH")
    rs_path <- unique(c(rs_path, sub("rpostback", 'postback', rs_path)))
    Sys.setenv(PATH = paste(c(PATH, rs_path), collapse = .Platform$path.sep))
  }
```

**Comment by jmcphers** [comment]
Reported by a customer in ticket 40427.

**Comment by kippandrew** [comment]
Got a report of this issue from RStudio cloud:

https://community.rstudio.com/t/problems-with-pushing-to-github/42503

**Comment by weli-sci** [comment]
I was having the same problem, and it was fixed simply by tranging the visibility of my repo from 'private' to 'public'.
