### ISSUE TITLE
Incorrect syntax warning shown with `%>%`

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/rstudio#3806]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1074
    OS Version      : macos 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Open a script, enter

```
iris %>%
  `[`(, "Species")
```

and save. A warning pops up and says "missing argument to function call" even though the syntax is valid.

**Comment by ronblum** [comment]
Reproducible on RStudio Desktop 1.1.456 as well.

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/2625.
