### ISSUE TITLE
Rstudio adding ".." to rproj paths resulting in projects not working

### ISSUE THREAD

**Issue by humanfactors** [rstudio/rstudio#3807]
### System details

    RStudio Edition : Desktop Version
    RStudio Version :  Version 1.2.1086
    OS Version      :  Windows 10 Enterprise (10.0.17134 Build 17134)
    R Version       :  3.5.1 (2018-07-02) -- "Feather Spray"

```
R version 3.5.1 (2018-07-02) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 17134)  Matrix products: default  locale: [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       [5] LC_TIME=English_Australia.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       loaded via a namespace (and not attached): [1] compiler_3.5.1  tools_3.5.1     packrat_0.4.9-3
```

### Steps to reproduce the problem

1. Install Rstudio 1.2 Preview Release
2. Open or create a project under Windows

### Describe the problem in detail

Under the preview release of Rstudio (and all daily builds from the last month), Rprojects do not open and you cannot create new projects. The cause of the issue appears to be that Rstudio adds a `..` to the path after `~/`. As you can see below this is the error message I get when opening an existing project.

![image](https://user-images.githubusercontent.com/16096044/47893992-2e20d180-de9b-11e8-88a1-d04724a861c7.png)

After selecting a folder to create a project in new project menu, Rstudio adds a `..` to the directory. I cannot remove this

![image](https://user-images.githubusercontent.com/16096044/47894020-54467180-de9b-11e8-8399-3e8c2f77ca2b.png)

This issue does not happen on stable builds.

### Describe the behavior you expected

I expected Rstudio Projects to open and not include the `..`

**Comment by ronblum** [comment]
@humanfactors I'm unable to reproduce this, using Windows 10 build 17134 and RStudio Desktop 1.2.1086. That said, what happens if you use the canonical path, `C:/Users/<username>/Code`, e.g.
<img width="527" alt="windows_home_3807" src="https://user-images.githubusercontent.com/31009952/47917163-fb68e000-de7e-11e8-9a0d-7ebb769a3759.png">

**Comment by humanfactors** [comment]
@ronblum I have a feeling that this issue may be specific to Windows Enterprise. The critical issue is that it's not possible for me to add the canonical path. I did not type the `..` and this is not in my user path. The `..` comes up after directory selection (from browse). It's perplexing.

**Comment by humanfactors** [comment]
Ok I've worked out the cause of the bug. My path variable for `HOME` included a trailing `\`, e.g., `C:\Users\12891839A\`. Consequently, Rstudio was trying to make all paths relative to that invisible directory (i.e., `%HOME%\..\project`. I'm not sure if this bug is catchable, but regardless I appreciate your help in looking into this issue.
