### ISSUE TITLE
Ctrl-W doesn't close the preview window in Windows

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3809]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463 and 1.2.1086
    OS Version      : Windows 7 and 10
    R Version       : 3.4.4 and 3.5.1

### Steps to reproduce the problem

1. Create a trivial Rmd. Just a title in the YAML and a single paragraph is sufficient (or the default Rmd).
2. Make sure that "Preview in Window" is selected.
3. Knit.
4. Ctrl-w (expecting to close the window). This doesn't work.
5. Click within the document (giving it focus).
6. Command-w still doesn't close the preview window.

### Describe the problem in detail

Ctrl-w does not close the preview window.

### Describe the behavior you expected

Ctrl-w should close the preview window. Note that it successfully closes tabs in the Editor pane.

This is an existing issue in 1.1.463.

[Also, I more-or-less copied the nice repro from #3753.]

**Comment by dfalty** [comment]
Verified fixed on version 1.2.1099.
