### ISSUE TITLE
publish dialogs still use old RStudio orb

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3811]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1087
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

Create a Shiny web application (File -> New File -> Shiny Web App...; name it 'hello'; click Create) and then try to publish it.

### Describe the problem in detail

The old RStudio orb is used in the publish dialog.

![screen shot 2018-11-02 at 12 08 32 pm](https://user-images.githubusercontent.com/1976582/47935573-0e3bde80-de98-11e8-9065-3a0334e46c3d.png)

### Describe the behavior you expected

We should use the v1.2 RStudio orb throughout the product.

**Comment by jmcphers** [comment]
We need to use the 3D orb in some places in order to preserve our trademark.
