### ISSUE TITLE
Check For Updates reports No Update Available

### ISSUE THREAD

**Issue by davidsgrogan** [rstudio/rstudio#3813]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1013
    OS Version      :  Mac 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem
Help -> Check For Updates

### Describe the problem in detail
I get No Update Available You're using the newest version of RStudio.

### Describe the behavior you expected
Update to a newer Preview. My preview release is like 3 months old.

**Comment by jmcphers** [comment]
Fixed now; let us know if you don't see a prompt next time. 

Note that we don't advertise preview releases frequently in-product since we release them frequently (~1x a week right now) and don't want to wear out our welcome.

**Comment by davidsgrogan** [comment]
I'm now on 1.2.1086. I did Check for Updates the other day -- it told me there was a new preview release, which I suppose was 1.2.1114-1. I did not upgrade.

Today when I do Check for Updates, it says "No Updates Available You're using the latest version..." which is in accurate.

To your second point, I'm not concerned with in-product notifications. Just that Check for Updates shouldn't lie :)
