### ISSUE TITLE
R Markdown session aborts when controlling code chunk options using yaml parameters

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#3816]
I am trying to set markdown code chunk options from the parameters in the rmarkdown header. The R Notebook causes the R session to abort under the following conditions (I am able to repeat this):

1. Set `params: eval: FALSE` in the header
2. Set `{r, eval=params$eval}` in the first code chunk
3. Do not save the html_notebook/html_document!
4. Select `Run All` from the drop down menu

The notebook will crash on RSP 1.2.750-1. I would rather the session not abort (or issue a warning) when I try to programmatically control code chunk options.

![image](https://user-images.githubusercontent.com/7519295/47947393-11fc4f00-def2-11e8-8218-1fba55b59868.png)

**Comment by kevinushey** [comment]
Have you tried with the latest preview release? I cannot reproduce with RStudio Desktop v1.2.1087 on macOS 10.14.1 (although it's possible this only reproduces on other platforms). I instead see the error:

```
Error in eval(ele) : object 'params' not found
```

**Comment by kevinushey** [comment]
Document for easy copy-pasting:

`````
---
output: html_notebook
params:
  eval: FALSE
---

```{r, eval=params$eval}
x <- pi
```


```{r}
x
```
`````

I can reproduce on Ubuntu 18.04 with the latest preview release of RStudio (v1.2.1086-1).

**Comment by jmcphers** [comment]
I'll take a look at this one. I can repro on MacOS -- though, curiously, I have to run it twice to do so (the first time it runs it works correctly).

**Comment by kevinushey** [comment]
I feel like I've seen this sort of thing occur before when an R error occurs and that somehow messes up state in the notebook queue. I guess ultimately the fix would be to make sure the `params` element is made available when evaluating the chunk options, though (assuming that is indeed the issue)

**Comment by dfalty** [comment]
I can't reproduce on version 1.2.1099. Marking as verified.
