### ISSUE TITLE
Some Chinese words can not display normally in R Studio Console

### ISSUE THREAD

**Issue by CHN-STUDENT** [rstudio/rstudio#3817]
### System details

    RStudio Edition :  Desktop
    RStudio Version : RStudio 1.1.463
    OS Version      :  Windows10 1809
    R Version       :  R version 3.5.1 (2018-07-02)

### Steps to reproduce the problem

Today I try to write a spider script by R , and I want to craw Chinese website (code:UTF-8) .I use RCurl 's function `getURL` save it as a variable , it can display normally on R Studio Console, but when i use XML 's function `htmlParse` to parse it, it can not display normally on R Studio Console.I do not know why.

### Describe the problem in detail

Here are my code:
```
wkDir = "D:/LEARNSTATION/datastroage/pm25";   
setwd(wkDir)

library(RCurl);   library(XML); library(httr);
URL = "http://pm25.in/rank"
X = getURL(URL, .encoding="utf-8"); 
htmlParse(X)
```

### Describe the behavior you expected

![image](https://user-images.githubusercontent.com/21209416/47962616-5c004480-e05a-11e8-84c8-4804c29faed8.png)

![image](https://user-images.githubusercontent.com/21209416/47962635-910c9700-e05a-11e8-88d4-bca3506a737e.png)

![image](https://user-images.githubusercontent.com/21209416/47962736-2b210f00-e05c-11e8-8c0a-925f71a35988.png)

Also,i try to see how to solve on Internet https://support.rstudio.com/hc/en-us/community/posts/203434818-Messy-characters-in-console-under-Chinese-locale , but it does not work for me.

Here are my sessionInfo():
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.3.1      XML_3.98-1.16   RCurl_1.95-4.11 bitops_1.0-6   

loaded via a namespace (and not attached):
[1] compiler_3.5.1 R6_2.3.0       tools_3.5.1 
```
Hope you can help me! Thank you!

**Comment by pascaloettli** [comment]
You could give [RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/) a try.

**Comment by kevinushey** [comment]
I suspect this is a bug in the XML package itself. I see the same behavior in RGui as well. You might have better luck using `xml2::read_html()` here.

Since this doesn't seem to be an RStudio-related bug, I'm going to close this, but feel free to follow up on the [community forums](https://community.rstudio.com).

**Comment by CHN-STUDENT** [comment]
@kevinushey Thank you! Also i can see the R package XML now does not have any maintainer, So may i use xml2 instead of this. Glad to get your suggestion!
