### ISSUE TITLE
SQL Results preview pane header is missaligned relatively to data columns

### ISSUE THREAD

**Issue by yanlesin** [rstudio/rstudio#3818]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1070
    OS Version      :  Windows 7
    R Version       :  3.5.1

### Steps to reproduce the problem

Preview SQL code in RStudio

### Describe the problem in detail

SQL Results Header is shifted by the width of scroll bar to the right and columns and headers are misaligned.

### Describe the behavior you expected

Header and columns are alligned
![image](https://user-images.githubusercontent.com/5117961/48015326-c1494980-e0dd-11e8-8286-8ced329452ea.png)

**Comment by yanlesin** [comment]
If SQL output length does not require scroll bar on the right, columns are aligned properly
![image](https://user-images.githubusercontent.com/5117961/48016006-4e40d280-e0df-11e8-9a9d-a97cda9b9df7.png)

**Comment by kevinushey** [comment]
I'm not able to reproduce -- for example, this renders fine for me:

#### wide.R

``` r
library(RSQLite)
library(DBI)

wide <- as.data.frame(matrix(1:1E4, ncol = 1E2))

conn <- DBI::dbConnect(RSQLite::SQLite())
dbWriteTable(conn, "wide", wide)
```

#### wide.sql

``` sql
select * from wide
```

Can you provide a reproducible example?

**Comment by yanlesin** [comment]
@kevinushey, your example for both wide0 and wide1 produces exactly the same shift in header. I doubt it is related to database... My initial thought that this is related to cases where column name is longer than actual data inside column, but it is not the case - both wide0 and wide1 are displayed with shift...
`
library(tidyverse)
library(odbc)
wide0 <- as.data.frame(matrix(1:1E4, ncol = 1E2))
wide1 <- wide %>% 
  rename(LONGER_NAME_FOR_V1=V1, LONGER_NAME_FOR_V2=V2)

conn <- dbConnect(odbc::odbc(),"EDM_DEV")

dbWriteTable(conn, "wide0", wide0)
dbWriteTable(conn, "wide1", wide1)

`
![image](https://user-images.githubusercontent.com/5117961/48589622-2af10100-e8f1-11e8-97df-4bb0d8b82254.png)

**Comment by yanlesin** [comment]
I don't have local RSQLite on work windows PC - I am only using odbc with MS SQL database behind it...

**Comment by yanlesin** [comment]
@kevinushey, I confirm, on a Mac with SQLite there is no issues with grid in SQL Results preview:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/5117961/48596696-0e63c180-e90f-11e8-9cbb-e217ad4d5e4f.png">

**Comment by ronblum** [comment]
It appears to be working on Windows. If this is still an issue, please reopen.
