### ISSUE TITLE
execute code chunk (Rmarkdown) in a background terminal

### ISSUE THREAD

**Issue by vrodriguezf** [rstudio/rstudio#3827]
Hi,

Is it possible to execute a code chunk in a background RStudio terminal while developing a .Rmd file?

Thanks!

**Comment by jmcphers** [comment]
No, not today. We're working on a background jobs feature which might do what you want when 1.2 is released. You can watch a demo here: https://rud.is/b/2018/06/09/running-rstudio-1-2-background-jobs/

**Comment by vrodriguezf** [comment]
Ok thanks!

**Comment by pydupont** [comment]
Hi,

The background job feature is now present in RStudio but I can't find it for Rmd files. Is it possible to run chunks in the background or is it limited to R scripts?

Kindly,

Pierre
