### ISSUE TITLE
Encoding UTF8 on Rstudio Server Pro login page

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#3830]
I contacted the support (ticket #31595) that sent me here.

Sorry I did not have the possibility to test if this feature request is already present in the preview release or not. 

### System details

    RStudio Edition : Server
    RStudio Version : 1.1.456
    OS Version      : Centos7
    R Version       : 3.5.1

### Describe the behavior you expected

I customized our login page following the support article. https://support.rstudio.com/hc/en-us/articles/231327847?input_string=uf-encoding+in+login+page
However, I have difficulties with encoding as I want to add some text in French with accentuated character. 

Is it possible to add in your html header login page <meta charset="utf-8" /> ? 

It seems to me that a good practice to have UTF8 html page. 
I would then be able to add content a custom page to be printing correctly. 

What do you think ?

**Comment by jmcphers** [comment]
You're right, we should fix this. In the meantime, it's easy to work around:

1. Open `/usr/lib/rstudio-server/www/templates/encrypted-sign-in.htm` in your favorite text editor
2. Add the line `<meta charset="UTF-8" />` right after the `<head>` tag
3. Save, close, then restart RStudio Server

You can now use UTF-8 in the login page HTML. Does that do what you want?

**Comment by cderv** [comment]
> You're right, we should fix this.
Thanks! 

The workaround I use currently is to add `<meta charset="UTF-8" />` in my custom `/etc/rstudio/login.html`, in a `<head>` that disappear when `login.html` is included. Firefox browser is clever enough to find this and reload the page in UTF-8. (with a warning in F12  console for JS). It is not clean at all but it works.
In fact, I did not want to modify one of your files, believing it could be erased during an upgrade. Am I right about that ? Modifying `/usr/lib/rstudio-server/www/templates/encrypted-sign-in.htm` would mean to do it for each upgrade ?

**Comment by jmcphers** [comment]
> In fact, I did not want to modify one of your files, believing it could be erased during an upgrade. Am I right about that ? 

Yes, you're right about that. If you modify anything in `/usr/lib/rstudio-server`, you'll need to put it back after an upgrade. 

Glad you got things sorted out!
