### ISSUE TITLE
Reticulate works in R console but fails in Rstudio to import pyspark related modules 

### ISSUE THREAD

**Issue by ashishmenkudale** [rstudio/rstudio#3832]
I am working in Azure HDInsight environment on a combined process flow in R + Python. The flow is, **1. use python (pyspark) script for data ETL, read/write and prepare dataframe. 2. use R for algorithm on this dataframe. 3. pass results to python(pyspark) script for writing ops.** The point of this workflow is to take the advantage of speedy data transfer thro’ pyspark. 
Python script is something similar to,

```
#reticulate1.py
import pandas as pd
print("pandas success")

from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql import HiveContext
spark = SparkSession.builder.appName("myAppName").enableHiveSupport().getOrCreate()

df_rdd = spark.sql("SELECT * FROM specto.telematics_status_t")

df = df_rdd.toPandas()
print(df.shape[0])
```

In R, something similar to,

```
#algorithm.R
reticulate::use_python("/usr/bin/anaconda/envs/py35/bin/python")
reticulate::py_run_file("~/reticulate1.py")
#get df_rdd and do calculations
```

**The code in algorithm.R works well in R console of azure**. But fails in Rstudio when python script tries to call pyspark module.
```
> py_run_file("/home/mv792/egt/reticulate1.py")
pandas success
Error in py_run_file_impl(file, local, convert) : 
  ImportError: No module named pyspark.sql

Detailed traceback: 
  File "<string>", line 4, in <module>
```
I went through environment variables being used by R console and Rstudio to find the difference. To the best of my knowledge, I reconfigured the system environment variables being referred by Rstudio (variables related to python, Hadoop and spark). But I couldn’t make python script work.

can you please help which system environment variables I should reconfigure properly?

```
> Revo.version
               _                                                              
platform       x86_64-pc-linux-gnu                                            
arch           x86_64                                                         
os             linux-gnu                                                      
system         x86_64, linux-gnu                                              
status                                                                        
major          9                                                              
minor          1.1                                                            
year           2017                                                           
month          05                                                             
day            23                                                             
language       R                                                              
version.string Microsoft R Server version 9.1.1.0024 (2017-05-23 18:47:22 UTC)
```

```
> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.3                         
year           2017                        
month          03                          
day            06                          
svn rev        72310                       
language       R                           
version.string R version 3.3.3 (2017-03-06)
nickname       Another Canoe 
```

Thanks.

**Comment by kevinushey** [comment]
Is this not the same as https://github.com/rstudio/reticulate/issues/377?

**Comment by ashishmenkudale** [comment]
> Is this not the same as [rstudio/reticulate#377](https://github.com/rstudio/reticulate/issues/377)?

Yes and no, this originated from the referenced issue/377. Later, I was able to figure out that the Reticulate does not have any problem with pyspark related modules as the same code worked from R console. This problem is now default system environment variables setup in Rstudio compared to that R console. What Rstudio does differently than Rconsole in terms of spark connections or references to pyspark. Maybe the answer lies there? or something else.

**Comment by jmcphers** [comment]
> This problem is now default system environment variables setup in Rstudio compared to that R console. 

We probably cannot fix this in the IDE itself. We recommend that you run Sys.getenv() in both places and check the origin of the values that differ.
