### ISSUE TITLE
compound operator (`%<>%`) and too many arguments in call to `foo`

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#3835]
When the magrittr compound assignment pipe-operator (`%<>%`) is used in `RStudio` (1.2), it gives a warning message that is incorrect.  

For example-

![image](https://user-images.githubusercontent.com/11330453/48105776-c9e96f00-e206-11e8-8248-e8b2f75f955b.png)

But this code works just fine, as shown in the `reprex` below:

``` r
library(magrittr)

# defining the function
foo <- function(df) {
  df %<>%
    tibble::as.tibble(x = .)
}

# using the function in piped chain
(iris %<>%
  foo(df = .) %>%
  tibble::rowid_to_column(df = ., var = "id"))
#> # A tibble: 150 x 6
#>       id Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>    <int>        <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1     1          5.1         3.5          1.4         0.2 setosa 
#>  2     2          4.9         3            1.4         0.2 setosa 
#>  3     3          4.7         3.2          1.3         0.2 setosa 
#>  4     4          4.6         3.1          1.5         0.2 setosa 
#>  5     5          5           3.6          1.4         0.2 setosa 
#>  6     6          5.4         3.9          1.7         0.4 setosa 
#>  7     7          4.6         3.4          1.4         0.3 setosa 
#>  8     8          5           3.4          1.5         0.2 setosa 
#>  9     9          4.4         2.9          1.4         0.2 setosa 
#> 10    10          4.9         3.1          1.5         0.1 setosa 
#> # ... with 140 more rows
```

<sup>Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pascaloettli** [comment]
Maybe I miss the point, but I cannot reproduce this warning in version `1.2.1090` of RStudio.

**Comment by IndrajeetPatil** [comment]
Huh, interesting. I was working with the stable version of RStudio but I am not getting this issue with the development version (`1.2.1099`).

**Comment by pascaloettli** [comment]
Still cannot reproduce neither in version `1.2.1090` on `Ubuntu 18.04` nor in version `1.2.1099` on `MacOS 10.14.1`. You said you didn't get the warning with the preview version, then again. What happened in-between?

**Comment by IndrajeetPatil** [comment]
I am using a Windows machine. 

I wasn't getting the error because I hadn't saved the file yet. As soon as I saved it, the warning returned.

**Comment by kevinushey** [comment]
This is a more general problem with RStudio's diagnostic system not understanding the use of `.` within magrittr expressions; e.g.

``` r
library(magrittr)
iris %>% identity(x = .)
```

<img width="343" alt="screen shot 2018-11-07 at 2 09 58 pm" src="https://user-images.githubusercontent.com/1976582/48164261-d7e6d080-e296-11e8-95fa-2754b7e93671.png">

**Comment by pascaloettli** [comment]
I still don't understand why I cannot reproduce.

**Comment by pascaloettli** [comment]
Makes sense. So I will keep them off, as it is the default. It should have been clearly stated first, I wouldn't have been lost my time and yours
