### ISSUE TITLE
Feature request: Include selection of R-version in project settings

### ISSUE THREAD

**Issue by TillF** [rstudio/rstudio#3836]
I often work with problems that require specific R-versions or 32/64-versions. 
Currently, I can globally select the R-Version to use in the "Global Options". It would be very helpful to have a similar selection option in "Project Options", that would override the global settings, if used. Thus, I could conveniently configure the required R-version for each project.

**Comment by jmcphers** [comment]
For what it's worth, this is already a feature in RStudio Server Pro; you can change the version of R while in a project, and it will be remembered as the project's R version.

![image](https://user-images.githubusercontent.com/470418/48147931-69414d00-e26d-11e8-8735-115725917a25.png)

![image](https://user-images.githubusercontent.com/470418/48147970-8118d100-e26d-11e8-943f-ceacedae6450.png)

We'll keep this issue open as a feature request to do the same for RStudio Desktop.
