### ISSUE TITLE
Auto-save feature conflicts with cloud storage (Dropbox etc)

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#3837]
This is a known issue that has been raised in the past ([1](https://support.rstudio.com/hc/en-us/community/posts/211694187-RStudio-Google-Drive-autosave-clash) and [2](https://support.rstudio.com/hc/en-us/community/posts/200658286-disable-autosave) among others), but it doesn't seem to exist on this Issues tracker.

If you are editing a Rmd file that is stored in a cloud storage folder like Dropbox, RStudio's auto-save feature raises this error popup:

> Save File: The process cannot access the file because it is being used by another process

This popup shows itself frequently and is _very_ annoying because it takes focus away from the editor.

**Please provide an option to edit the auto-save frequency and to disable auto-save entirely.** Thanks!

**Comment by kevinushey** [comment]
Presumedly telling Dropbox to ignore the `.Rproj.user` folder would work as well. Is that an option?

**Comment by DesiQuintans** [comment]
Unfortunately, there’s no such thing as a `.dropboxignore` file. Dropbox syncs all files that are inside it, even symlinked files. Dropbox has [explicitly said it won’t add this](
https://www.dropboxforum.com/t5/Manage-account/Ignore-folder-without-selective-sync/td-p/5926/page/63), so giving RStudio users control over auto-saving is the way forward.

**Comment by jackbrookes** [comment]
This basically makes RStudio unusable for me. VSCode doesn't have this issue. Just give us an option to disable the annoying popup

**Comment by DesiQuintans** [comment]
Just wanting to bring this up again because I have gotten this popup 5-10 times in the last half hour and it's driving me mental! I have temporarily disabled Dropbox for now, but that is not a long-term solution. Please let me just turn off auto-saving.

**Comment by jwijffels** [comment]
This is indeed really annoying. I'm considering swithing to VSCode. Can you tell me how to switch off in the Rstudio Options > Code > Saving tab? I'm using version 1.3.776. Saving an .R file still gives me a lot of these popups `Save File: The process cannot access the file because it is being used by another process`

**Comment by DesiQuintans** [comment]
Yes, I work entirely inside my Dropbox folder for nearly everything I do, and RStudio is the only software package that finds it necessary to remove focus from me to give me the dreaded `file being used by another process` error popup whenever I save.

The new Preview release with the auto-save options does **a lot** to minimise this, but not entirely. Whenever I hit Save, I would say that there is a 1-in-3 chance that I will get the `file being used by another process` popup. Sometimes I have to try to save 2 or 3 times before it actually takes: Save → Popup → Spacebar → Save → Popup → Spacebar → Save.

Perhaps RStudio can do all of this silently in the background? Say, automatically and silently retry saving a few times *before* giving me a (now justified) error popup?

**Comment by tmcduff** [comment]
Verified Version: 1.3.957-4with Dropbox. Autosave using the 3 Idle options and 500,1500 & 5000ms options.

**Comment by arencambre** [comment]
This did not resolve the issue for Google Drive. I opened #7131.

**Comment by Syrph** [comment]
Did anyone manage to solve this? I have exactly the same error, only when using Rstudio on windows as well. Ubuntu works fine and doesn't give me this annoying pop up.

**Comment by Syrph** [comment]
Looks like it's because I was using R studio 1.4 for Ubuntu, and 1.2 for windows. Just happened to be around the release of 1.4 that i started using projects!
