### ISSUE TITLE
Feature request: Help pane bookmarks

### ISSUE THREAD

**Issue by MokeEire** [rstudio/rstudio#3838]
It would be very nice to be able to bookmark help pages.  I don't believe this is possible at the moment. A simple implementation might be a star/bookmark icon next to the home or print icons in the Help pane and an additional pane for bookmarked help pages.

Perhaps it is laziness, but being able to access vignettes/function reference pages that I regularly use to verify actions/arguments of functions etc. would be tremendously useful.

**Comment by ronblum** [comment]
@MokeEire Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio. And I wouldn't consider it laziness at all—it's a desire for efficiency.
