### ISSUE TITLE
compatibility with libssl-dev

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3839]
Currently, RStudio is not compatible with libssl 1.1, as noted here:

https://github.com/rstudio/rstudio/blob/09316fd734f410742e31bd0f4e90445e8bd011da/dependencies/linux/install-dependencies-debian#L29-L39

This is a little bit problematic, as the `libssl1.0-dev` package won't co-exist with e.g. `libcurl4-openssl-dev`, which is required for other software (perhaps notably the R `curl` package), e.g.

```
$ sudo apt install libcurl4-openssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libssl-doc
Use 'sudo apt autoremove' to remove it.
Suggested packages:
  libcurl4-doc libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev libssl-dev
The following packages will be REMOVED:
  libssl1.0-dev
The following NEW packages will be installed:
  libcurl4-openssl-dev
0 upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 294 kB of archives.
After this operation, 5,847 kB disk space will be freed.
```

Note in the above log that the `libssl1.0-dev` package will be removed in response to the attempt to install `libcurl4-openssl-dev`.

Ultimately this is just an annoyance for development work but it would be nice if we supported both variants.

**Comment by kevinushey** [comment]
Closed via https://github.com/rstudio/rstudio/commit/1aa89a458e723536d4531a5c09c9201cb9211afc.

**Comment by ronblum** [comment]
Verified on Ubuntu 18.04.
