### ISSUE TITLE
JavaScript console warning about missing theme file on startup

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3844]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1102
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem
* Launch RStudio
* Right-click on blank area of toolbar, "Inspect Element" to bring up Chrome debugger
* Switch to Console view

### Describe the problem in detail
* Warning about a missing file associated with the currently selected editor theme:

![2018-11-07_14-28-12](https://user-images.githubusercontent.com/10569626/48165138-7e33d580-e299-11e8-9387-19030e730033.png)

### Describe the behavior you expected
* No warning

Haven't seen any obvious problems as a result of this.

### Other notes
I had been clearing out my desktop settings just before I noticed this; doesn't seem related, but in case you want to try:
```
defaults delete com.rstudio.desktop
defaults delete com.rstudio.desktopPro
defaults delete org.rstudio.RStudio
rm -rf ~/.rstudio-desktop
```

**Comment by kevinushey** [comment]
I can reproduce this now. To reproduce, the Help pane must be open and visible (note this is required as panes are otherwise lazy-loaded). In other words, to reproduce:

1. Open the Help pane,
2. Open the Home page in the Help pane,
3. Close RStudio,
4. Re-open RStudio.

You should then see the theme-related warning in the JavaScript console.

**Comment by kevinushey** [comment]
![screen shot 2018-11-08 at 10 14 39 am](https://user-images.githubusercontent.com/1976582/48218613-1fc13280-e33f-11e8-90ba-122327cb18ac.png)

This might be yet another one of those "we need themes in a URI handler sub-path" issue.
