### ISSUE TITLE
Creating R Markdown documents requires updated versions of the following packages: error message, followed by Do you want to install these packages now

### ISSUE THREAD

**Issue by rmac1205** [rstudio/rstudio#3851]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by rmac1205** [comment]
Adding error message 21 Oct 2018 17:59:56 [rsession-JAKE5824] ERROR r error 4 (R code execution error) [errormsg=Error: invalid version specification ‘NA’|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) C:\Users\Administrator\rstudio\src\cpp\r\RExec.cpp:159; LOGGED FROM: rstudio::core::json::Object rstudio::session::modules::html_preview::capabilitiesAsJson() C:\Users\Administrator\rstudio\src\cpp\session\modules\SessionHTMLPreview.cpp:1126

**Comment by ronblum** [comment]
@rmac1205 Can you please provide the requested information to help understand the issue?

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

Also, were there no packages listed, just the error message?

**Comment by rmac1205** [comment]
Hello @ronblum 
Thank you for your reply
Desktop 
Version 1.0.153 
Win7
R-3.5.1

Hope this helps Thanks!

**Comment by jmcphers** [comment]
Closing since we don't have any more details or clues. @rmac1205 feel free to re-open if you're still seeing this!
