### ISSUE TITLE
Copy to clipboard won't copy entirely the plot (daily build)

### ISSUE THREAD

**Issue by PMassicotte** [rstudio/rstudio#3853]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1105
    OS Version      : Linux Mint 19 Tara
    R Version       : 3.5.1

### Steps to reproduce the problem

Make a plot and use the "Export -> Copy to Clipboard" button.

### Describe the problem in detail

The plot is not entirely copied in the clipboard.

![image](https://user-images.githubusercontent.com/4519221/48221784-f913f380-e360-11e8-90db-7846223594ff.png)

**Comment by kevinushey** [comment]
Thanks; I can reproduce this. It looks like this occurs if the IDE is currently zoomed in -- is that true in your case? If you reset the zoom to actual size (View -> Actual Size) does the issue go away?

**Comment by PMassicotte** [comment]
Fantastic will try tomorrow 👍

**Comment by PMassicotte** [comment]
I just tried Version 1.2.1112 and when I click "copy to clipboard" the window closes but there is nothing in the clipboard.

**Comment by kevinushey** [comment]
I'm seeing that too. It was working on a local development copy of RStudio. :-/

**Comment by kevinushey** [comment]
As a workaround, you can also right click on the image and use the Copy Plot to Clipboard context item in that dialog.

**Comment by tjmahr** [comment]
Just chiming in that I ran into this problem today. I'm using 1.2.1114 on Windows 10.
