### ISSUE TITLE
Import dataset dialog has misaligned header relatively to columns when scroling is required

### ISSUE THREAD

**Issue by yanlesin** [rstudio/rstudio#3857]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1091
    OS Version      : Windows 7
    R Version       :  3.5.1

### Steps to reproduce the problem

Import data set with readr from csv (or from Excel) with row count greater than 7 (or higher depending on resolution and font size) and columns header is shifted to the right by the width of scroll bar.

### Describe the behavior you expected

Expected aligned header and columns
![image](https://user-images.githubusercontent.com/5117961/48234299-eb189f80-e36d-11e8-8d20-9a2f919d537a.png)

**Comment by ronblum** [comment]
@kevinushey Could this be a duplicated of #3670?

**Comment by yanlesin** [comment]
This is a different place - data viewer vs data importer

**Comment by kevinushey** [comment]
I agree this isn't a duplicate (although it may be a manifestation of the same underlying issue)

**Comment by yanlesin** [comment]
This seems to be resolved in most recent preview on Windows

**Comment by ronblum** [comment]
@yanlesin Thank you for the update!
