### ISSUE TITLE
Data viewer values not horizontally clamped

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3858]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1091

### Steps to reproduce the problem

Run the following R command:

    View(data.frame(a = "Truth", b = "A falsehood which has the sound of truth, and is expressed with vehemence and passion, but is not true in any meaningful way."))

### Describe the problem in detail

The content runs off the screen.

![image](https://user-images.githubusercontent.com/470418/48235402-96c3ee80-e372-11e8-8a66-285e37261aee.png)

### Describe the behavior you expected

The content should be limited to ~300px by default. This is what happens in RStudio 1.1:

![image](https://user-images.githubusercontent.com/470418/48235431-ad6a4580-e372-11e8-981d-57db0cb3ebda.png)

This makes it difficult to use things like list columns, as the list content can totally fill the screen. Here's an example from the purrr "API of Ice and Fire" tutorial, in which a couple of long list-values have more or less created empty scrolling-wastelands:

![image](https://user-images.githubusercontent.com/470418/48235475-e4d8f200-e372-11e8-873c-53a200e208fe.png)

I think this is a result of this change: https://github.com/rstudio/rstudio/commit/8dbb24b6c45906333e0db4b0011fbfd73d80e0ad#diff-aeb6776f4939faf9c18fb4370e1dc570

**Comment by kevinushey** [comment]
You're correct that this was fallout from my commit. I've reverted this on master now.

Is @adamconroy's upcoming PR going to help out with performance here? (If so, then perhaps we don't need to worry about optimization here anymore)

**Comment by adamconroy** [comment]
@kevinushey I don't think that my change will do much to help here, unfortunately. I'm only limited the number of columns returned and not much else. That said, I'm pretty comfortable in this code at the moment and if there are still severe performance issues in cases like this after my change gets merged I could take a look at this issue.

**Comment by jmcphers** [comment]
@kevinushey fixed this in https://github.com/rstudio/rstudio/commit/488298426f340e3b2bc4283486e095d12a8e3b95. We could consider opening another 1.2 bug if we think there's a way to clamp the values without using as much expensive layout.
