### ISSUE TITLE
Auto-completion did not work after typing code snippet 'lib'

### ISSUE THREAD

**Issue by shangzhi-hong** [rstudio/rstudio#3859]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1112
    OS Version      :  Windows 10 1809
    R Version       :  3.5.1

### Steps to reproduce the problem
type `lib`, hit 'Tab' and then type something like `mag` waiting for 'magrittr' to pop out (but it will not)

### Describe the problem in detail
Using the full code `library(mag`, the auto-completion works

### Describe the behavior you expected
Show the list of candidate libraries

**Comment by ronblum** [comment]
@hszest Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

Reproduced on MacOS 10.14 Mojave Desktop and Ubuntu 16.04.5 Server. This was an issue in 1.1.463, as well.
