### ISSUE TITLE
SQL Results preview pane shows only the results of the very first SQL statement

### ISSUE THREAD

**Issue by gregkvas** [rstudio/rstudio#3860]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1091
    OS Version      :  Windows 7 Prof. / Windows 10 Home
    R Version       :  3.5.1 Feather Spray

### Steps to reproduce the problem

1. Connecting to SQLServer Express 2014 (or also 2017) via Connection pane in RStudio
2. Using the SQL button in RStudio to generate a new SQL file with the open connection
3. Defining two simple SQL SELECT statements within the SQL file and using "Preview" button in RStudio

### Describe the problem in detail

When defining multiple SQL statements within a generated SQL file in RStudio only the results of the
very first SQL statement is shown when using the preview button "Preview" (Ctrl+Shift+Enter). As can be seen in the screenshot, only the first selection of the top 5 cases of the specific table is previewed and no results for the second SQL statement, where all cases of the specific table are selected.

![rstudio_sql_preview](https://user-images.githubusercontent.com/43455762/48266509-db618f80-e42f-11e8-9e8b-90a0e8adf476.PNG)

I have also described this behaviour in RStudio Community: https://community.rstudio.com/t/rstudio-1-2-preview-sql-integration-preview-multiple-sql-statements/17839?u=gregkvas

### Describe the behavior you expected

I expected that the results of each SQL statement would be shown in different SQL preview
panes and/or the SQL statements could be invoked to be previewed one by one.

Thank you for any help!
Best, Gregor

**Comment by ronblum** [comment]
@gregkvas This is the expected behavior. DBI only accepts one statement, and therefore only the first statement in the SQL preview is getting exectured. One option would be to make an enhancement request that DBI accept multiple statements at once.

**Comment by gregkvas** [comment]
@ronblum Thank you Ron for the explanation! So the SQL integration preview in RStudio 1.2 works like a DBI::dbSendQuery() function and therefore does not behave like a SQL batch script as i mistakenly thought of. With an enhancement for DBI to act more like a SQL batch script RStudio would really become an alternative SQL IDE.

**Comment by genghiskhanofnz** [comment]
Hi all, I am using RStudio SQL button to preview my query results before plotting or summarising in RStudio and hoping that evaluating and producing results at least 2 active sql sets would be necessary for me.  But, I am not sure what the priorities are for the RStudio dev team.
As a heavy-user of RStudio, this suggestion will serve a 'giant step' for a RStudio-mankind.
Thanks.

**Comment by genghiskhanofnz** [comment]
@ronblum = thanks for your time and effort to comment on this topic.

**Comment by TonyFly3000** [comment]
I think its will be great if we can execute the SQL code line by line on Rstudio IDE

**Comment by ronblum** [comment]
@TonyFly3000 That sounds like a good suggestion. Can you please file a new enhancement in this repository? This will have the added benefit of other users being able to vote and comment on the request.
