### ISSUE TITLE
Problem with computer not going to hibernation/sleep

### ISSUE THREAD

**Issue by WolfgangRolke** [rstudio/rstudio#3861]
I have recently updated RStudio to Ver 1.2.1030 and I have noticed a strange behavior: it seems RStudio is preventing my computer from going into sleep mode even though I don't have any programs running. I have verified that it is indeed RStudio:  it happens when RStudio is the only program running on the computer and it does not happen if RStudio is closed. Also, this never happened before the update to Ver 1.2.

Wolfgang

    RStudio Edition : 
    RStudio Version : 1.2.1030
    OS Version      :  Win 10
    R Version       :  3.5.1

**Comment by ronblum** [comment]
@WolfgangRolke 
Thank you for raising this concern. Do you have this issue with either [the preview](https://www.rstudio.com/products/rstudio/download/preview/) or the [most recent dailies](https://dailies.rstudio.com/rstudio/oss/windows/)?

**Comment by WolfgangRolke** [comment]
Not sure. I downloaded only one version a few weeks ago.Enviado desde mi Samsung Mobile de Claro
-------- Original message --------From: Ron Blum <notifications@github.com> Date: 11/9/18  3:10 PM  (GMT-04:00) To: rstudio/rstudio <rstudio@noreply.github.com> Cc: WolfgangRolke <wolfgang.rolke@upr.edu>, Mention <mention@noreply.github.com> Subject: Re: [rstudio/rstudio] Problem with computer not going to hibernation/sleep (#3861) @WolfgangRolke
Thank you for raising this concern. Do you have this issue with either the preview or the most recent dailies?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rstudio/rstudio","title":"rstudio/rstudio","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rstudio/rstudio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ronblum in #3861: @WolfgangRolke \r\nThank you for raising this concern. Do you have this issue with either [the preview](https://www.rstudio.com/products/rstudio/download/preview/) or the [most recent dailies](https://dailies.rstudio.com/rstudio/oss/windows/)?"}],"action":{"name":"View Issue","url":"https://github.com/rstudio/rstudio/issues/3861#issuecomment-437463627"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rstudio/rstudio/issues/3861#issuecomment-437463627",
"url": "https://github.com/rstudio/rstudio/issues/3861#issuecomment-437463627",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [rstudio/rstudio] Problem with computer not going to hibernation/sleep (#3861)",
"sections": [
{
"text": "",
"activityTitle": "**Ron Blum**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ronblum",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"rstudio/rstudio\",\n\"issueId\": 3861,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"rstudio/rstudio\",\n\"issueId\": 3861\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/rstudio/rstudio/issues/3861#issuecomment-437463627"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408589205\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by WolfgangRolke** [comment]
I just upgraded to the latest version (1.2.1114) but the problem persists

**Comment by mkiang** [comment]
Same issue for me — RStudio appears to have a power assertion on macOS that prevents normal sleep operations. I'm on Rstudio 1.1.453 and macOS 10.14.1.

See screenshot (the "Yes" in the "Preventing Sleep" column): https://www.dropbox.com/s/h1lyspuppq7psnr/Screen%20Shot%202018-12-06%20at%208.33.38%20AM.png?dl=0

**Comment by kevinushey** [comment]
@mkiang do you see the same thing with the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)? (worth trying since OP is running Windows but you're running macOS)

FWIW I can't reproduce.

**Comment by mkiang** [comment]
@kevinushey the latest preview seems to have fixed that (thanks!) but now RStudio is requesting the discrete graphics card — is that intentional?

**Comment by kevinushey** [comment]
Yes, the rendering engine underneath the IDE uses hardware accelerated rendering when possible and also uses the GPU if available. If you'd prefer software rendering, that can be enforced here:

![screen shot 2018-12-06 at 2 18 22 pm](https://user-images.githubusercontent.com/1976582/49615251-ce1dbf00-f961-11e8-81dd-e92ad6fe0596.png)
