### ISSUE TITLE
Suggestion: Print option to include line numbers

### ISSUE THREAD

**Issue by md0u80c9** [rstudio/rstudio#3864]
Hi,

Hopefully a relatively simple suggestion: I can't seem to find a way to set up printing code files to include line numbers. This is of course exceptionally useful if you're also printing and comparing console debug or output. Apologies if there is a way but I've just missed it!

**Comment by ronblum** [comment]
@md0u80c9 Thanks for the feature suggestion! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by jmcphers** [comment]
This would be nice, but hasn't received any upvotes or attention in over a year, so closing.

**Comment by mikebessuille** [comment]
Another customer request: "Also being able to print with code color highlights (as seen on screen) and to tune the font size to save paper, currently printing quite large in my case" (8183)

**Comment by indojoe** [comment]
The POS Rstudio should minimally allow user to print out code with line numbers.
