### ISSUE TITLE
Check in Build pane is using stale files?

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#3868]
For some reason, the `Check` button in the `Build` pane continues to carp about bugs in my package code that have been fixed for weeks.

I see an error like this (and several others):

![screen shot 2018-11-12 at 12 14 05 pm](https://user-images.githubusercontent.com/7606389/48326698-a21a6100-e675-11e8-973e-24f1359e9046.png)

Even though this is clearly in my `NAMESPACE` and the package has been saved/rebuilt, my computer restarted, etc. etc.

![screen shot 2018-11-12 at 12 14 17 pm](https://user-images.githubusercontent.com/7606389/48326711-b9594e80-e675-11e8-8a8a-5586e8f4e5c6.png)

If I run `devtools::check(document = FALSE)` from the console, I don't have this issue, so it can't be something wrong with `devtools` (`R CMD build .` `R CMD check ...` also has no issue).

I've tried deleting the `tar.gz.` and `Rcheck` files/folders from the package directory (I shouldn't have to), but nothing.

Where is RStudio pulling the files from when it runs Check that it's so out of sync? `Build` button appears to be working just fine, so I'm especially surprised it seems to be limited to `Check` functionality.

**Comment by MichaelChirico** [comment]
Fixed by updating `devtools` and descendants to dev; h/t @jennybc for the idea.

https://twitter.com/JennyBryan/status/1061850238644740096

Feel free to close this unless there's something deeper to be learned/fixed here

**Comment by jmcphers** [comment]
Glad you got it figured out, thanks for following up!
