### ISSUE TITLE
ubuntu rstudio packages install

### ISSUE THREAD

**Issue by Victorfy** [rstudio/rstudio#3869]
### System details

    RStudio Edition :  Desktop  
    RStudio Version : 1.1.456
    OS Version      : ubuntu 18.04
    R Version       : 3.4.4

### Steps to reproduce the problem
change cran mirror in packages, but it didn't work. It still download package from cran rather than I choose

### Describe the problem in detail
 I need to use options("repos" = c(CRAN = " ")) every time started a new r session to solve that

**Comment by ronblum** [comment]
@Victorfy This is because Rprofile on Ubuntu has a setting for the CRAN repository, which is taking precedence: http://docs.rstudio.com/rspm/admin/rstudio-server.html#precedence-of-settings
There's a discussion of this at #3224, as well.
