### ISSUE TITLE
intermittent warning message `Unknown or uninitialised column: 'date'` for no reason

### ISSUE THREAD

**Issue by statsandthings** [rstudio/rstudio#3870]
I randomly receive the warning message `Unknown or uninitialised column: 'date'`.

This even happens if I'm in a fresh start of R with no data frames, no data at all. I might be using R strictly as a calculator and enter something like `(4*27)^3` and I'll get the warning. If I enter the exact same command again there's no warning. I don't save any history upon exit when shutting down R Studio.

This happens across my Windows and Linux systems, which use R Studio 1.1.463. I'm running R 3.5.1. Don't know what to do at this point. Been happening for months intermittently.

My .Rprofile

    local({
      r = getOption("repos")             
      r["CRAN"] = "https://cran.cnr.berkeley.edu/"
      options(repos = r)
    })

My .Renviron

    R_LIBS=C:/Users/stackinator/Documents/R-libraries

**Comment by kevinushey** [comment]
Have you tried the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by statsandthings** [comment]
Sometimes it only shows up every several weeks. Let me try to repro it with the preview release. Might need to wait until December for my response.

**Comment by jmcphers** [comment]
Been over a year and haven't heard back -- presumably this is solved? Let us know if you see it again.
