### ISSUE TITLE
R Studio can't enter certain key combos as modified shortcuts

### ISSUE THREAD

**Issue by statsandthings** [rstudio/rstudio#3871]
I want to modify the following R Studio keyboard shortcuts

    Tools > Modify Keyboard Shortcuts > Open Next Tab > [Ctrl]-[PageDown]
    Tools > Modify Keyboard Shortcuts > Open Prev Tab > [Ctrl]-[PageUp]

but the screen that captures your keyboard input won't let me input `[Ctrl]-[PageDown]` or `[Ctrl]-[PageUp]`. I can do other keyboard combos. Just not those two (possibly others). I looked at what these two combos are assigned to and cleared them,

    Tools > Modify Keyboard Shortcuts > Go to Next Section > [Ctrl]-[PageDown] > Clear
    Tools > Modify Keyboard Shortcuts > Go to Previous Section > [Ctrl]-[PageUp] > Clear

Then I tried again to reassign `Open Next Tab` to `[Ctrl]-[PageDown]` but again it didn't let me put in this key combo. But I could put in `[Ctrl]-[A]` or `[Ctrl]-[B]` for example.

Why is the `[Ctrl]-[PageDown]` and `[Ctrl]-[Up]` locked out of use? I was able to use them like this a year ago. The default behavior of `[Ctrl]-[PageDown]` and `[Ctrl]-[Up]` moving to the most recently used tab, instead of sequential order (like Chrome, Office, everything else) is not preferred.

**Comment by pascaloettli** [comment]
Please don't delete the template, it is useful to know your unknown RStudio version, RStudio edition, OS and R version.
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by ronblum** [comment]
@statsandthings I'm unable to reproduce this on MacOs 10.14 Mojave with RStudio Desktop 1.2.1150-1. so as mentioned above, the system details would be useful.
