### ISSUE TITLE
View() panel in dark theme is half dark-half bright in Rstudio 1.2.1114

### ISSUE THREAD

**Issue by tcgriffith** [rstudio/rstudio#3874]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.2.1114
    OS Version      :  Ubuntu 18.04
    R Version       :  3.5.1

### Steps to reproduce the problem
View(mtcars)

### Describe the problem in detail
In Rstudio 1.2.837, the View panel is consistently dark, but in 1.2.1114 it's not, see the following screenshot:

1.2.1114:
![](https://i.imgur.com/Vi3iY3N.png)

1.2.837:
![](https://i.imgur.com/oW6uWEh.png)

By the way, here is my theme info:
```
> rstudioapi::getThemeInfo()
$editor
[1] "Vibrant Ink"

$global
[1] "Modern"

$dark
[1] TRUE
```

### Describe the behavior you expected

View panel should be dark( dark background and white text colour)

**Comment by kevinushey** [comment]
I'm not able to reproduce.

If I change the editor theme while the Data Viewer is open, I do see the table contents flash white briefly, so it does lead me to believe that this could potentially be a timing issue.

For posterity, can you consistently reproduce this issue -- does it happen all the time, and with all kinds of data?

**Comment by tcgriffith** [comment]
Well, after completely uninstall+reinstall rstudio, The problem no longer exists. perhaps some old css styles get cached and are not completely reloaded?

Thanks for your time, closing.
