### ISSUE TITLE
Feature request: "List directories first" option in files panel

### ISSUE THREAD

**Issue by shangzhi-hong** [rstudio/rstudio#3875]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Describe the behavior you expected
Adding a "list directories first" option in the files panel

**Comment by ronblum** [comment]
@hszest Thanks for the feature suggestion. We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by gtritchie** [comment]
You can sort by type, including folders, to get the folders first, but as you say, that impacts sorting of all files, not just folders.

<img width="421" alt="screenshort of files pane showing where to click to sort by file type" src="https://user-images.githubusercontent.com/10569626/75574639-888c5c80-5a13-11ea-9702-522df8c53ac9.png">

**Comment by cjyetman** [comment]
- also suggested here https://forum.posit.co/t/folders-on-top-in-rstudio-files-window/36209
- would match macOS "Keep folders on top" option
- would match GitHub's file viewer
