### ISSUE TITLE
strange layout on macOS 1.2.1114

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#3877]
Just upgraded and the view is a bit odd :)

![image](https://user-images.githubusercontent.com/2998956/48393554-ed0f9500-e6c4-11e8-836d-ac47b83a8490.png)

**Comment by vnijs** [comment]
Is there a convenient way to downgrade? I don't see a "previously releases" folder or something like that. This version isn't workable on High Sierra (R 3.5.1) unfortunately

**Comment by hszest** [comment]
> Is there a convenient way to downgrade? I don't see a "previously releases" folder or something like that. This version isn't workable on High Sierra (R 3.5.1) unfortunately

Here are the previous builds for mac: https://dailies.rstudio.com/rstudio/oss/mac/

**Comment by vnijs** [comment]
Thanks @hszest! I think this issue has something to do with differences in resolution between my main laptop display and the external (apple) display. When Rstudio 1.2.1114 starts up on the external display it looks like the screen shot posted earlier. If I then move the Rstudio window to my laptop display Rstudio windows resize appropriately. If I then move the Rstudio window back to the external display windows sizes remain fine.

**Comment by jmcphers** [comment]
This will probably repro on most 1.2 builds, so if you're affected you have two choices: downgrade, or turn on software rendering (in Options -> General -> Advanced). 

We're tracking this issue here: https://github.com/rstudio/rstudio/issues/3479
