### ISSUE TITLE
Incorrect syntax warning

### ISSUE THREAD

**Issue by uhkeller** [rstudio/rstudio#3879]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.1114
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem
Paste the following (nonsensical, but valid) code into a new R file and save it:
```r
something %>% 
  mutate_at(vars(var1), funs(map_int(., ~ if(TRUE) 1 else 2)))
```
Observe the spurious syntax warning for the second line complaining about unmatched brackets.

**Comment by ronblum** [comment]
Confirmed on MacOS Desktop and Ubuntu Server. With less code:
```
map_int(., ~ if(TRUE) 1 else 2)
```
Note that adding parentheses around the if/else clause gets rid of the errors.
```
map_int(., ~ (if(TRUE) 1 else 2))
```
<img width="296" alt="parens_error" src="https://user-images.githubusercontent.com/31009952/48565903-99b96480-e8c7-11e8-86b7-e4cf586aa7b8.png">

**Comment by jmcphers** [comment]
This is already tracked in https://github.com/rstudio/rstudio/issues/1773.
