### ISSUE TITLE
chunk output theme lost after document mutation

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3882]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1115
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

First, make sure you're using a dark editor theme. Then, with the following document:

`````
---
title: "Table options"
output: html_document
---

Several packages support making beautiful tables with R, such as

* [xtable](https://cran.r-project.org/web/packages/xtable/)
* [stargazer](https://cran.r-project.org/web/packages/stargazer/)
* [pander](http://rapporter.github.io/pander/)
* [tables](https://cran.r-project.org/web/packages/tables/)
* [ascii](http://eusebe.github.io/ascii/)
* etc.

It is also very easy to make tables with knitr's `kable` function:

```{r echo = FALSE, results = 'asis'}
library(knitr)
kable(mtcars[1:5, ], caption = "A knitr kable.")
```
`````

Run the R chunk, then place the cursor on the line after the chunk output, and insert a newline.

### Describe the problem in detail

The chunk text color switches from white to black.

![theme](https://user-images.githubusercontent.com/1976582/48428902-d39c3680-e720-11e8-94ae-ea159c305bfb.gif)

### Describe the behavior you expected

Document mutation shouldn't change the chunk output theming.

**Comment by ronblum** [comment]
Just noting: It also happens with RStudio Desktop 1.1.463 (MacOS 10.14.1) and RStudio Server 1.2.1115-2 (Ubuntu 14.04.5).

**Comment by kevinushey** [comment]
It looks like the chunk output is getting briefly detached and then immediately reattached, but styles set on the body of the inner document are not being refreshed as well.

Not sure why this detach is happening in the first place; I'll dig a bit more.

**Comment by kevinushey** [comment]
It's caused by the logic we have for ensuring line widgets stay attached to their associated chunk:

https://github.com/rstudio/rstudio/blob/01030e76bcab6212c6deed6c29393264753aa9ea/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/PinnedLineWidget.java#L203-L222

I believe the issue here is that styles on the document are somehow lost when the widget is detached then reattached. I'll see if I can find a solution.

**Comment by kevinushey** [comment]
@jmcphers I think you're best equipped to fix this (or punt as well since this was an issue in v1.1)

**Comment by jmcphers** [comment]
The theme is typically sync'ed after the chunk is attached, here:

https://github.com/rstudio/rstudio/blob/a698544a9bad2aafd14613b35c103ca3ee50e771/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java#L259-L266
