### ISSUE TITLE
Incorrect error message when using 'question' in learnr

### ISSUE THREAD

**Issue by gvwilson** [rstudio/rstudio#3883]
I have the following code block in a `.Rmd` file that uses `learnr`:

    ```{r machine-epsilon, echo=FALSE}
    question("What is the sign of .Machine$double.eps?",
      answer("0"),
      answer("1", correct = TRUE),
      answer("Inf"),
      answer("NA"))
    ```

When I "Run Document" in RStudio, I get the following error message for the chunk:

    Error in embedded[[1]][[2]]$attribs : $ operator is invalid for atomic vectors

"Show Traceback" gives me only:

    2. print.htmlwidget(x)
    1. function (x, ...) UseMethod("print")(x)

However, the rendered version shows up correctly in a pop-up window, and I can go ahead and answer the question.

Source file can be found at <https://github.com/gvwilson/primers/blob/testing/testing/basics/basics.Rmd>; YAML header in the file (if that matters) is:

    ---
    title: "Basic Concepts"
    output: learnr::tutorial
    runtime: shiny_prerendered
    ---

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1114
    OS Version      :  MacOS 10.13.6
    R Version       :  3.5.1
    learnr version : 0.9.2.1
    shiny version: 1.2.0

**Comment by gvwilson** [comment]
Note: I originally had ".Machine$double.eps" in back quotes inside the string so that it would render as fixed-width text; removing the back quotes made no difference.

**Comment by jmcphers** [comment]
Probably barfing here:

https://github.com/rstudio/rstudio/blob/33f6eae8b01608ef29ca0ead766f3e9577147e1c/src/cpp/session/modules/NotebookHtmlWidgets.R#L229-L233

This code hasn't changed in years, though, so surprised to see it having trouble now. Perhaps something's changed upstream; @gvwilson what version of the htmlwidgets package are you using?

**Comment by gvwilson** [comment]
htmlwidgets 1.3

**Comment by jmcphers** [comment]
I'm glad to say this is working fine now! (1.3.625)

![image](https://user-images.githubusercontent.com/470418/70179198-790aab00-1692-11ea-88e5-789a0d50edb5.png)
