### ISSUE TITLE
Tarball rstudio returns blank screen, with only a non-functional menu at the top.

### ISSUE THREAD

**Issue by dunctonsteel** [rstudio/rstudio#3885]
### System details

    RStudio Edition : Windows
    RStudio Version : 1.1.463.0
    OS Version      : Windows 10 pro, 10.0.16299
    R Version       : 3.5.1

### Steps to reproduce the problem

Install R, run Studio tarball

### Describe the problem in detail
R studio opens to a blank page, with only the menu at the top. Neither the menu items, nor rstudio seems to work at all.

### Describe the behavior you expected
I expected rstudio to behave as though it were installed on the computer.

**Comment by kevinushey** [comment]
Sorry, but I'm not able to reproduce -- the tarball built for RStudio v1.1.463 runs without issue on my Windows 10 VM. Can you provide any other information?

If you hold the Ctrl key down while launching RStudio, you should be presented with a dialog to select a version of R to use when launching RStudio. Does selecting a different version of R make a difference?
