### ISSUE TITLE
attempting to shrink a data viewer column can also trigger a sort

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3888]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1119
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

Open the data viewer with e.g.

``` r
View(mtcars)
```

Then, try to 'shrink' a column, e.g. the `qsec` column. Click the resizer on the right side of the header cell, move the mouse to the left, and then release.

### Describe the problem in detail

The view is then sorted by the associated cell.

![scroll](https://user-images.githubusercontent.com/1976582/48447598-36a5c180-e751-11e8-876d-be0512444087.gif)

### Describe the behavior you expected

Resize operations shouldn't also trigger a sort.

**Comment by dfalty** [comment]
Verified fixed 1.4.484
