### ISSUE TITLE
Running jobs killed without warning when Restart R is invoked

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3893]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.1122
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- Start a long-running script job via the Jobs pane
- While script is running, invoke **Session / Restart R** menu OR **Install and Restart** in a package project.

### Describe the problem in detail
The running job(s) are killed without warning.

### Describe the behavior you expected
There should be a warning, similar to what you see when other parts of the application are busy (e.g. run "sleep 1000" in a terminal and do these steps).

**Comment by dfalty** [comment]
Verified fixed 1.2.1310-1.
