### ISSUE TITLE
Run controls not displayed for code snippets inside blockquotes

### ISSUE THREAD

**Issue by gvwilson** [rstudio/rstudio#3899]
If a backquoted code block is inside a blockquote demarcated with `>` indents, RStudio Desktop does not display the run controls for the snippet, but the snippet is executed correctly when the document is knit.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1114
    OS Version      : 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Create a `.Rmd` document that contains only the following:

~~~
---
title: "R Chunks in Blockquotes"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
```

Regular code snippets:

```{r}
1 + 2 + 3
```

> Blockquote code snippets:
>
> ```{r}
> 4 * 5 * 6
> ```
~~~

View the document in RStudio Desktop - run controls are displayed for the un-blockquoted code snippet, but are *not* displayed for the code snippet in blockquotes.

![screen shot 2018-11-15 at 9 24 33 am](https://user-images.githubusercontent.com/911566/48559043-c3b75a80-e8b8-11e8-8ce3-8196e9fbff55.png)

Knit the document with "Knit to HTML" - the code snippet in the blockquotes is executed as it should be:

![screen shot 2018-11-15 at 9 24 13 am](https://user-images.githubusercontent.com/911566/48559099-e6e20a00-e8b8-11e8-909e-3531eb284e91.png)

### Describe the behavior you expected

I expected run controls to show up for code snippets in blockquotes.

**Comment by ronblum** [comment]
Thanks @gvwilson. I'll mark this as a bug, so that we can review whether or not this is the intended behavior.

**Comment by kevinushey** [comment]
I didn't know knitr supported code chunks within block-quotes. We could in theory support this in Notebooks as well but this is the first time I've seen this used.

**Comment by jmcphers** [comment]
I didn't know that either! It'd be nice to support but in > 1 year we've never heard of anyone else trying this so possibly not worth the risk of trying to parse them out.
