### ISSUE TITLE
Feature request: blockquote/unblockquote a region (like comment/uncomment)

### ISSUE THREAD

**Issue by gvwilson** [rstudio/rstudio#3900]
I would like to be able to select a region of text in a `.Rmd` file and indent it with `> ` markers in the same way that I can indent it with `# ` markers to comment it. This would make it easy for me to move chunks of lessons into side notes, or to move them back into the main text.

**Comment by kevinushey** [comment]
You might find the [Remedy Addin](https://github.com/ThinkR-open/remedy) useful.

**Comment by gvwilson** [comment]
Thanks!

**Comment by ateucher** [comment]
You can also select the block of text, split into multiple cursors (`Ctrl+Alt+a`), then left-arrow to put the cursors at the beginnings of the lines, and type `>`. (Apologies for likely teaching my grandmother to suck eggs).

**Comment by jmcphers** [comment]
As @kevinushey and @ateucher noted there are already reasonable mechanisms for accomplishing this, and it's had no support or upvotes for over a year, so closing.
