### ISSUE TITLE
Cannot associate R(.r) files to Rstudio in Windows 10 Entreprise

### ISSUE THREAD

**Issue by stat1** [rstudio/rstudio#3910]
System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 1.1.463
    OS Version      : Windows 10 Entreprise
    R Version       : R 3.5.1

I have installed Rstudio and i cannot associate R(.r) files to Rstudio in Windows 10 Entreprise.

I fixed my problem doing this command in CMD with admin rights

Assoc .r=rfile

Then

Ftype rfile="C:\Program Files\RStudio\bin\rstudio.exe" %1

Then i installed R on another Windows 10 Entreprise machine, and same problem.

**Comment by ronblum** [comment]
@stat1 What happens when you first try to associate the file? If the problem that associating the files with the desktop fails, but works from the command line?

**Comment by stat1** [comment]
Im not sure i undersand the question.

When i installed RStudio : The R files where not associated with RStudio, and i tried to associate it with a right click.

But the OS did not knew what was a .r file.

so i had to do the command above.

**Comment by stat1** [comment]
I think one of my users put us in error.

his files of R had the extension .r and as i can see R extensions are .rdata?

that why i had to manually associate rstudio to .r files

**Comment by jmcphers** [comment]
Typically RStudio should associate .R with itself; it's likely that you have a group policy setting in Enterprise that is prohibiting applications from messing with file type registrations as a security precaution. Please reopen if you find that isn't the case and you're still having trouble with RStudio 1.2.5019 or newer!
