### ISSUE TITLE
Suggestion: Keyboard control of pane sizes

### ISSUE THREAD

**Issue by Peder2911** [rstudio/rstudio#3916]
I would love to be able to change the size of panes using the keyboard (this is one of the only things i reach for my mouse to do). Currently, when changing Rstudio from half-screen to full-screen, the right pane column sometimes takes over most of the screen, which is not helpful. 

To be specific, i would like to be able to change the position of the horizontal pane-delimiter.

**Comment by jmcphers** [comment]
This is a nice idea but hasn't had any upvotes or attention in well over a year, so we're closing it. We will consider implementing as part of https://github.com/rstudio/rstudio/issues/2879.
