### ISSUE TITLE
Ctrl+Shift+K

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rstudio#3917]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.2.1114
    OS Version      :  Windows 10
    R Version       :  3.5.1

### Steps to reproduce the problem
* Use <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>K</kbd>
* Check the shortcut list under "Source Editor"

### Describe the problem in detail

The used shortcut for compiling the rmarkdown file now is set as for deleting lines. 

### Describe the behavior you expected

Hope the default setting can be overwritten or showing the new shortcut for rmarkdown compiling in somewhere easy to be found.

**Comment by jmcphers** [comment]
I wasn't able to reproduce this; Ctrl+Shift+K compiles R Markdown on Windows 1.2.1114 for me. 

What keybindings are you using, and which shortcut list are you referring to?

**Comment by sammo3182** [comment]
@jmcphers, I'm referring to the keyboard shortcut quick reference provided by Rstudio, as seen following:
![image](https://user-images.githubusercontent.com/6463211/48741368-d0abc380-ec95-11e8-9eb4-d65a1d9434dd.png)

It seems overwriting the original shortcut for compiling the Rmarkdown document.

**Comment by jmcphers** [comment]
Are you using the new Sublime Text keybindings? (Options -> Code -> Editing -> Keybindings)

**Comment by sammo3182** [comment]
Damn it! I did. Never notice such an option. Sorry for bothering. Everything works well once I changed to "default" of the Keybindings.
