### ISSUE TITLE
Data Viewer pager's icons don't render correctly on macOS

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3918]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1135
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

Open the data viewer with a 'wide' dataset, e.g.

``` r
View(matrix(1, ncol = 100, nrow = 10))
```

### Describe the problem in detail

The icons for the pager show as white boxes:

![screen shot 2018-11-16 at 9 34 05 am](https://user-images.githubusercontent.com/1976582/48637587-ff1e5b80-e982-11e8-9318-ceda26658a26.png)

### Describe the behavior you expected

Nicely-rendered arrows / icons.

**Comment by kevinushey** [comment]
For what it's worth, these ones render fine in Chrome on my system:

http://graphemica.com/⇥
http://graphemica.com/→

**Comment by adamconroy** [comment]
@kevinushey can you inspect the icons in rstudio and tell me exactly what font it is for you? I don't have Mojave set up on my laptop and would like to avoid doing that for just this bug fix if I can. My current guess is those arrows are just not in the font that OS X is using in that header.

**Comment by kevinushey** [comment]
The web inspector says it's the "system-ui" font, whatever that might be on macOS:

![screen shot 2018-11-16 at 10 05 12 am](https://user-images.githubusercontent.com/1976582/48639020-26772780-e987-11e8-967f-6129eae6e4d6.png)
