### ISSUE TITLE
Data Viewer cells are no longer being classed

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3919]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1135 (dev)
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

Try running:

``` r
View(mtcars)
```

And then Right Click -> Inspect Element to view a cell.

### Describe the problem in detail

The cell contents are no longer classed, which means things like overflow will not be handled as expected.

![screen shot 2018-11-16 at 10 29 54 am](https://user-images.githubusercontent.com/1976582/48640155-a357d080-e98a-11e8-8e4a-25318209e7c5.png)

### Describe the behavior you expected

Cells should be classed:

![screen shot 2018-11-16 at 10 32 26 am](https://user-images.githubusercontent.com/1976582/48640241-f0d43d80-e98a-11e8-9989-b0eee3acbba9.png)

**Comment by kevinushey** [comment]
@adamconroy it looks like this is caused by the patches made to DataTables in https://github.com/rstudio/rstudio/pull/3878. Can you take a look?

**Comment by adamconroy** [comment]
Fixed in commit https://github.com/rstudio/rstudio/commit/e718a29c23d03150c3dafa0266853867a67d7e9f
