### ISSUE TITLE
Reflow comment keyboard shortcut not shown in menu

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#3920]
It looks like Cmd-Shift-/ on Mac reflows comments again (see #2443 and #3107), but the keyboard shortcut isn't shown in the menu.

![image](https://user-images.githubusercontent.com/86978/48642366-5253d680-e9a2-11e8-9ee2-1f14eafc86a0.png)

**Comment by jmcphers** [comment]
Fixed in the dailies.

![image](https://user-images.githubusercontent.com/470418/70178095-7909ab80-1690-11ea-8a92-4ac4d1056545.png)
