### ISSUE TITLE
WISH: rstudio --version

### ISSUE THREAD

**Issue by HenrikBengtsson** [rstudio/rstudio#3922]
Please consider adding support for querying the RStudio version from the command line, .e.g.

```sh
$ rstudio --version
1.1.453

$ 
```

Migrated from https://community.rstudio.com/t/wish-rstudio-version/18322

**Comment by philmikejones** [comment]
If you're on Ubuntu/Debian you can use:

```
dpkg -s rstudio | grep "Version"
```

**Comment by jmcphers** [comment]
Can you tell us a little more about why you want to do this? (realize it's a common convention!)

**Comment by HenrikBengtsson** [comment]
Convenience - not having to open a GUI click through menus to find it (kudos for making the About dialog cut'n'pastable). It will help sysadms orchestrating 100-1000's of software tools.

**Comment by kevinushey** [comment]
It's worth saying that RStudio will install a VERSION file that can be queried as well:

```
$ cat /usr/lib/rstudio/VERSION 
1.3.568
```
