### ISSUE TITLE
DESIGN: Option 'menu.graphics' overridden to avoid GUI whereas 'askYesNo' doesn't

### ISSUE THREAD

**Issue by HenrikBengtsson** [rstudio/rstudio#3923]
I noticed that the [RStudio Console overrides option `menu.graphics` to be `FALSE`](https://github.com/rstudio/rstudio/blob/v1.2.679/src/cpp/r/R/Options.R#L102-L103) (which otherwise defaults to `TRUE`), e.g.

RStudio Console:
```r
> getOption("menu.graphics")
[1] FALSE
```

Plain R (e.g. RStudio Terminal):
```r
> getOption("menu.graphics")
[1] TRUE
```

That seems to be a deliberate design choice to avoid GUI dialogs.

Yet, when running R on Windows in a GUI (including RStudio Console), we have:

```r
> getOption("askYesNo")
function (msg, ...) 
{
    flush.console()
    ans <- winDialog("yesnocancel", msg)
    switch(ans, YES = TRUE, NO = FALSE, NA)
}
```

This causes for instance `update.packages()` to query the user via a GUI dialog.

In line with `menu.graphics`, have you consider overriding this to `options(askYesNo = NULL)`?

# Related
 * Issue #2901

**Comment by jmcphers** [comment]
We do allow this intentionally on Windows. See e.g.:

https://github.com/rstudio/rstudio/blob/e36e87c9445b6c768154fca967d5d24544224532/src/cpp/desktop/DesktopMainWindow.cpp#L358-L376

Can you tell us more about why you'd prefer it to be disabled?

**Comment by jmcphers** [comment]
Yes, it is. `menu.graphics` doesn't work smoothly with the IDE, but `askYesNo` does (or at least, can be made to do so as we do above). Ideally perhaps we'd have our own implementations of both. :-)
