### ISSUE TITLE
update NOTICE re: fontawesome icons

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3933]
Now that we're bundling a couple fontawesome icons, we should update NOTICE to reflect that:

https://fontawesome.com/license/free
https://github.com/rstudio/rstudio/blob/master/NOTICE

**Comment by kevinushey** [comment]
FWIW the license does explicitly state:

> Attribution is required by MIT, SIL OLF, and CC BY licenses. Downloaded Font Awesome Free files already contain embedded comments with sufficient attribution, so you shouldn't need to do anything additional when using these files normally.

but I think it's worth stating this up-front in NOTICE (let me know if you disagree)

**Comment by adamconroy** [comment]
On it!

**Comment by adamconroy** [comment]
https://github.com/rstudio/rstudio/commit/18e1924de7f2c62b1d16d01e64d128deaad45641
