### ISSUE TITLE
Code diagnostics incorrectly flags argument mismatches for functions in a list

### ISSUE THREAD

**Issue by WerthPADOH** [rstudio/rstudio#3934]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

When the "Check arguments to R function calls" option (Tools > Global Options > Code > Diagnostics) is checked, if a function is created in a list and named after another function, diagnostics will use the function in the list to check subsequent calls.

Example:

```
a <- list(
  paste = function(x) paste(x, collapse = ""),
  x     = paste(letters, collapse = "")
)

y <- paste(letters, collapse = "")
```

### Describe the problem in detail

In the above code, each call to `paste()` will be flagged with a red "X" by the IDE's diagnostics. The tooltips for each "problem" read:

> too many arguments in call to 'paste'

Of course, the above code will run just fine.

### Describe the behavior you expected

Functions defined in the list shouldn't affect how diagnostics judges calls to other functions.

**Comment by ronblum** [comment]
@WerthPADOH Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

Reproduced on MacOS 10.14 Mojave with RStudio Desktop 1.2.1150-1.
