### ISSUE TITLE
Visual glitches (blocks) when scrolling.

### ISSUE THREAD

**Issue by chriswiduta** [rstudio/rstudio#3936]
### System details
    RStudio Edition : Desktop
    RStudio Version : RStudio Version 1.2.1114
    OS Version      :  Win10 1803 build 17134.407 (high resolution display)
    R Version       :  R version 3.5.0 (2018-04-23)
    GPU : Intel(R) UHD Graphics 620

### Steps to reproduce the problem
Scrolling up or down in in any workspace (files, environment, code, console)

### Describe the problem in detail
When scrolling, a visual glitch will occur, usually flickering boxes. The glitch will cause block to be moved to other places only for a brief second, but sometimes lingering.

![](https://i.imgur.com/v6B4zCG.jpg)

**Comment by kevinushey** [comment]
Is the situation any better if you switch to software rendering?

![image](https://user-images.githubusercontent.com/1976582/48803359-91e23180-ecc6-11e8-9453-36fcfdb94acb.png)

Can you also share the output of the <kbd>Help -> Diagnostics -> Show GPU Diagnostics</kbd> page?

**Comment by chriswiduta** [comment]
> 
> 
> Is the situation any better if you switch to software rendering?
> 
> 
> Can you also share the output of the Help -> Diagnostics -> Show GPU Diagnostics page?

Yes it seems to have fixed the issue.  I tired scrolling multiple R files and could not reproduce the issue.

GPU output after switching to Software rendering.
Data exported | 2018-11-20T21:27:47.219Z
-- | --
Chrome version | rstudio/1.2.1114.0
Operating system | Windows NT 10.0.17134
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/65 35ee3617fcb08e0d79e6b9e6c05db23cc9416d4f-
Command Line | "C:\Program Files\RStudio\bin\rstudio.exe" --enable-viewport --disable-renderer-accessibility --browser-subprocess-path="C:\Program Files\RStudio\bin\QtWebEngineProcess.exe" --no-sandbox --enable-threaded-compositing --disable-zero-copy --disable-gpu-memory-buffer-compositor-resources --disable-gpu-memory-buffer-video-frames --disable-mojo-local-storage --disable-es3-gl-context --enable-features=AllowContentInitiatedDataUrlNavigations --disable-features=SurfaceSynchronization --disable-features=SurfaceSynchronization,TouchpadAndWheelScrollLatching --disable-gpu "C:\Users\Carbon\Documents\EL Single Projects\******\**********.RData"

**Comment by kevinushey** [comment]
Great! Let us know if you observe any performance degradation while using software rendering.

The other thing worth double-checking is that your video card's drivers are all up to date.
