### ISSUE TITLE
Feature Request: autocompletion for new lines

### ISSUE THREAD

**Issue by verajosemanuel** [rstudio/rstudio#3939]
When coding and pressing comma inside a parenthesis, a tooltip informs about parameters and such,
Try this: 

`ggplot(data = x, #press tab here            )`

The issue is that this is not working when coding taking into account align and new lines for every parameter as good practices recommend

Try this

```
ggplot( data = x,
             # press tab here
            )

```
Would be cool to hace autocompletion no matter if whe are in a new line or not.

**Comment by kevinushey** [comment]
You can use <kbd>Ctrl + Space</kbd> instead, or explicitly enable the preference to allow for autocompletion in that context (see `[ ] Use tab for multiline autocompletions`):

![screen shot 2018-11-26 at 9 04 24 am](https://user-images.githubusercontent.com/1976582/49029767-51693480-f15a-11e8-908d-36f4322ae092.png)
