### ISSUE TITLE
Feature Request: keyboard shortcut for 'Set Working Directory to Source File Location'

### ISSUE THREAD

**Issue by lbp91** [rstudio/rstudio#3944]
I use this all the time, so a keyboard shortcut would be appreciated. Thanks!

**Comment by kevinushey** [comment]
You could likely implement this yourself with an [RStudio Addin](https://rstudio.github.io/rstudioaddins/).

**Comment by jmcphers** [comment]
No votes or attention for well over a year (plus you can make an addin to do it pretty trivially) so closing.
