### ISSUE TITLE
Use fixed-width font for Find and Replace fields

### ISSUE THREAD

**Issue by HughParsonage** [rstudio/rstudio#3945]
I find it difficult to read the Find and Replace fields, especially when using a regular expression. I'd like these fields to use a fixed-width font (preferably the same font as used in the panes) to make it easier to parse. In particular, brackets `(` `[`, `{` etc are quite difficult to see.

![image](https://user-images.githubusercontent.com/8111628/48977035-5e4c4080-f0e6-11e8-8d65-bfa33f0ce333.png)

Sublime Text's Find and Replace is essentially what I'm after. They allocate more horizontal space (which I think is also an improvement), but it's mainly the typeface and font size that make it easier to read.

![image](https://user-images.githubusercontent.com/8111628/48977033-4f658e00-f0e6-11e8-9ab6-ac1a21092987.png)

I searched for `font` in the `[Enhancements]` tag, but could not see a related issue. I actually think RStudio's Find and Replace has better 'mechanics' than does Sublime Text (notably the 'in selection' option seems to be more predictable). Only the presentation could use enhancement.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1139
    OS Version      : Windows
    R Version       : 3.5.1

**Comment by jmcphers** [comment]
Sublime's regex syntax highlighting is a nice touch, too.
