### ISSUE TITLE
RStudio settings lost on Windows because they are in Local and not in Roaming

### ISSUE THREAD

**Issue by jogrue** [rstudio/rstudio#3950]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Windows 7 Enterprise 6.1.7601
    R Version       : 3.5.1

### Steps to reproduce the problem

RStudio keeps its settings in the AppData/Local folder of Windows (7/10). At my university I have a roaming user profile, everything in local is lost each time I log out. Most software uses AppData/Roaming to store its settings.

I only found these two descriptions of the same issue:

https://community.rstudio.com/t/ms-windows-roaming-profiles/1418
https://support.rstudio.com/hc/en-us/community/posts/200650543-File-history-and-project-history-stored-in-LOCALAPPDATA

### Describe the behavior you expected

I would expect that RStudio keeps its settings in the Roaming folder (then my settings would be kept on every computer I log on to. If there is a good workaround or there happened a mistake in how the university set up RStudio, I would be thankful for a pointer in the right direction.

**Comment by ronblum** [comment]
@jogrue Thank you for raising this issue. We will review it as we work on development of future versions of RStudio.

Also adding an updated link to a page referenced by one of the pages above: https://support.rstudio.com/hc/en-us/community/posts/200664223-R-Studio-in-Classroom-Saving-History-on-Network-drive-

**Comment by gtritchie** [comment]
See also: https://github.com/rstudio/rstudio/pull/698

**Comment by jmcphers** [comment]
> I would expect that RStudio keeps its settings in the Roaming folder

The reason this doesn't happen today is that RStudio doesn't separate state that should move between machines (such as your tab settings) from state that needs to be machine-local (such as your machine's unique identifier). These settings are often mixed into the same file.

We're tracking this issue in #1607, where we'll put user-settings in AppData\Roaming and others in AppData\Local; feel free to follow that issue (and comment/upvote) for updates.
