### ISSUE TITLE
Import from Excel: options in "Data Preview" window reset

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#3955]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1143
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Open  "Import Dataset... → From Excel..." menu.
2. Chose any Excel file to import data from.
3. Select to skip any column.
4. Change any option in "Import Options" panel, e.g., uncheck box "Open Data Viewer".
5. Option in "Data Preview" window resets, but in "Code Preview" does not.

### Describe the problem in detail

Problems are that:

1.  the options in "Data Preview" window reset and
2. the code in "Code Preview" and the options in "Data Preview" window do not match.

![pav 158](https://user-images.githubusercontent.com/12725868/49103656-a2754780-f284-11e8-87ea-f55a8665f403.jpg)

![pav 160](https://user-images.githubusercontent.com/12725868/49104568-f719c200-f286-11e8-9fc5-bf9ee2f485a6.jpg)

### Describe the behavior you expected

Options in "Data Preview" should not reset.

Maybe related to #3953

**Comment by GegznaV** [comment]
I can still reproduce this in RStudio 1.4.1103

**Comment by GegznaV** [comment]
...

**Comment by romainfrancois** [comment]
I believe this is related to this: 

https://github.com/rstudio/rstudio/blob/7597b79eb0fdbbe57b1cac5b8c9787d24dead21e/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java#L134-L137

We can probably only refresh when the sheet or the range changes

**Comment by jgutman** [comment]
Verified in 2023.3.0.84.
