### ISSUE TITLE
trailing newline not created by RStudio

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#3961]
I find this issue occasionally in RStudio, and am not sure how much it is a function of the editor used inside RStudio. There are various cases where this happens and a newline is not present in a file after it is saved, but the incantation to get it to happen can be very tricky. 

Opening this issue to hopefully tag enough examples that it starts to narrow down the cases where this can happen.

- Unsure of the steps I took to get here - editing a README file that ended up not having a newline. Happened on Mac RDP.
![image](https://user-images.githubusercontent.com/23075542/49130295-30f7c200-f2a1-11e8-8b2e-18641afdb253.png)

- Typing this value on RStudio Server Pro, using the autocomplete of `{` to `{|}` followed by a return, which gives no trailing newline after saving the file.
![image](https://user-images.githubusercontent.com/23075542/49130378-9cda2a80-f2a1-11e8-86e9-348aea3a0515.png)

**Comment by kevinushey** [comment]
We have a UI preference to control whether RStudio ensures a trailing newline is added on save:

<img width="605" alt="screen shot 2018-11-28 at 7 32 00 am" src="https://user-images.githubusercontent.com/1976582/49162424-b732f900-f2df-11e8-8dfd-7722a33cb0d5.png">

Does that do what you need?

**Comment by colearendt** [comment]
Awesome! I think so! Definitely very glad to learn about that, thanks! Just one more question - any reason that is not a default behavior? Backwards compatibility / least surprise / no file editing and the like? It was definitely surprising to me that the newline was not added, since most editors take care of it.

**Comment by kevinushey** [comment]
I'm not sure -- there might be some rare cases where a trailing newline is not desired but I think it is desired in 99% of cases.

**Comment by ronblum** [comment]
@colearendt I'm marking it as an enhancement but leaving it open, as an indicator to review if we should change the behavior.

**Comment by colearendt** [comment]
Just FWIW, it seems that `Source files` has some type of spec associated with it (only `.R` or something?), or the option is broken in some circumstances. Even with the option is enabled, this `.yml` file did not gain a terminating newline upon saving the file:

![image](https://user-images.githubusercontent.com/23075542/49267971-ea35d380-f42a-11e8-907c-21acb952fbdf.png)

**Comment by kevinushey** [comment]
Do you have a project-specific setting overriding the global setting?

**Comment by colearendt** [comment]
:scream: There is a project level setting that inherited my previous default. 😭  So old projects will need to be migrated one-by-one. I confirmed that new projects do inherit the global setting. Thanks for clarifying that!

**Comment by jmcphers** [comment]
This bug just tracks changing the default, and we don't plan to do that -- just as many people will be surprised at RStudio randomly adding newlines as are currently surprised that it doesn't, especially since it's been the behavior for years now.
