### ISSUE TITLE
RStudio view displays NA as 0

### ISSUE THREAD

**Issue by PMassicotte** [rstudio/rstudio#3964]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1147
    OS Version      : Running under: Linux Mint 19
    R Version       : R version 3.5.1 (2018-07-02)

### Describe the problem in detail

RStudio view displays NA as 0, see the attached screenshot.

![image](https://user-images.githubusercontent.com/4519221/49173650-4953f500-f312-11e8-9c43-52c8fe69d75b.png)

**Comment by jmcphers** [comment]
Might be the same underlying cause as https://github.com/rstudio/rstudio/issues/3940.

**Comment by adamconroy** [comment]
Same as https://github.com/rstudio/rstudio/issues/3940 and should be all set now.
