### ISSUE TITLE
RStudio: scaling on second monitor

### ISSUE THREAD

**Issue by RobertZimbardo** [rstudio/rstudio#3966]
### System details

    RStudio Edition : <Desktop>
    RStudio Version : 1.2.1153
    OS Version      : Linux Mint 19
    R Version       : 3.5.1

This is reporting again on these bugs that seem to have been closed

https://support.rstudio.com/hc/en-us/community/posts/115008457328-windows-10-scalling-issue-with-external-monitor
https://github.com/rstudio/rstudio/issues/3228

but the color selection solution doesn't work on my laptop: I have come across an RStudio problem which arises on a laptop when a VGA cable is plugged in to use a projection screen at my university. While RStudio has always worked fine with both just a second monitor plugged in (VGA or HDMI) or a projection system (VGA or HDMI), now something has changed and in my classroom what happens is that when I drag an RStudio instance to the screen that is used for projecting things, then the content of the window gets maximized so much that it can only show

File >>

at the top. See attached screenshots. This only happens in this classroom and only with RStudio, no where else, but it's new. Any idea what this might be? I'm using R 3.5.1 and tested this with RStudio 1.2.1114 and 1.2.1153 on Linux Mint 19.
![screenshot from 2018-11-28 09-52-34](https://user-images.githubusercontent.com/45435973/49176945-d8581180-f300-11e8-8b7d-d26504bd789f.png)
![screenshot from 2018-11-28 09-53-06](https://user-images.githubusercontent.com/45435973/49176947-d8581180-f300-11e8-8b3b-76f2abc27c0c.png)

**Comment by kevinushey** [comment]
Did you try switching to software rendering? See e.g. the prescriptions offered in https://github.com/rstudio/rstudio/issues/3228#issuecomment-411546167.

**Comment by RobertZimbardo** [comment]
Oh, I hadn't seen that possibility, I will check it when I'm in the room
for my next class, thanks!

**Comment by RobertZimbardo** [comment]
I have now tried all rendering options: they either do not change the display or they make the RStudio instance disappear when the window is dragged to that second screen (although the System Monitor shows something's still running in the background).

**Comment by kevinushey** [comment]
Any chance you can tell us what model of projector you're using?

**Comment by RobertZimbardo** [comment]
All I can say at this point is that this is a wall-mounted system that says "Extron MLC 226 IP" and the second screen then is a big (I wanna say at least 55inches Sharp monitor) mounted on the opposite wall. I'd need to speak to IT ppl here to get more info if you think that'd help.

**Comment by ActuarialAnalyst** [comment]
Same issue here.

**Comment by ozzeusz** [comment]
Same here

**Comment by ronblum** [comment]
@ozzeusz and @Coshibu Is this still an issue:
- In the current version of RStudio Desktop, 1.2.5033? https://rstudio.com/products/rstudio/download/#download
- If you change to software rendering? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
If it's still an issue with these two, please let us know!

**Comment by Coshibu** [comment]
The problem still exists with RStudio Desktop, 1.2.5033.

I assume that the problem for me is a DisplayPort to HDMI adapter. I have an ASUS GeForce GT1030-2G-BRK with one HDMI and one DisplayPort exit (Pressed the wrong button when purchased). I use HDMI cables and the DisplayPort is connected via an adapter to an HDMI cable. For some reason, GTK understands the scaling I am using, but QT doesn't. I hope that sheds some light on it. I know the setup is stupid, I should have never bought a graphics card with DisplayPort.

I have currently qt5.9 installed:
qmake --version
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

See also for example this:
https://www.reddit.com/r/Surface/comments/3elp8e/psa_why_automatic_display_scaling_doesnt_always/

**Comment by kguidonimartins** [comment]
```
RStudio Edition : <Desktop>
RStudio Version : 1.3.958
OS Version      : Arch Linux
R Version       : 4.0.0
```

I have the same problem in the preview version 1.3.958. I'm in a Dell Vostro 5480. Here is my `xrandr` result:

```
Screen 0: minimum 320 x 200, current 3286 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 309mm x 173mm
   1366x768      60.00*+  48.01
   1280x720      60.00    59.99    59.86    59.74
   1024x768      60.04    60.00
   960x720       60.00
   928x696       60.05
   896x672       60.01
   1024x576      59.95    59.96    59.90    59.82
   960x600       59.93    60.00
   960x540       59.96    59.99    59.63    59.82
   800x600       60.00    60.32    56.25
   840x525       60.01    59.88
   864x486       59.92    59.57
   700x525       59.98
   800x450       59.95    59.82
   640x512       60.02
   700x450       59.96    59.88
   640x480       60.00    59.94
   720x405       59.51    58.99
   684x384       59.88    59.85
   640x400       59.88    59.98
   640x360       59.86    59.83    59.84    59.32
   512x384       60.00
   512x288       60.00    59.92
   480x270       59.63    59.82
   400x300       60.32    56.34
   432x243       59.92    59.57
   320x240       60.05
   360x202       59.51    59.13
   320x180       59.84    59.32
HDMI-1 connected 1920x1080+1366+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1920x1080     60.00*+  50.00    59.94
   1920x1080i    60.00    50.00    59.94
   1600x1200     60.00
   1680x1050     59.88
   1280x1024     60.02
   1440x900      59.90
   1280x960      60.00
   1280x800      59.91
   1280x720      60.00    50.00    59.94
   1024x768      60.00
   800x600       60.32    56.25
   720x576       50.00
   720x480       60.00    59.94
   640x480       60.00    59.94
```

My second screen, on the right side, looks like this:

![pic-full-200521-0909-00](https://user-images.githubusercontent.com/8163542/82562152-11b2bb80-9b4b-11ea-8b3c-82680a1a9249.png)

I did follow this [guide](https://wiki.archlinux.org/index.php/HiDPI#Zoom) to launch Qt applications with a different scale factor. This solution was suggested for the Zoom application, which in my machine does not have the scaling problem. I have to run this in terminal:

```
QT_SCALE_FACTOR=0.6 rstudio-bin
```

**Comment by netique** [comment]
I have a similar issue. Tried all available rendering engines, graphics card (internal Intel) driver update from OEM and even that "pure" Intel one. I have also tried to run RStudio from CMD with various "magic" invocations described in other relevant issues here on GH. Tried every combination from [this URL](https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors), but nothing worked for me. I have also looked for True Color vs. High Color options, but these are not available to me.

My main monitor is 2560x1440, 16:9, and my secondary is FHD internal monitor in Dell XPS 13 2020 (aspect ration 16:10). I use Windows recommended 125% and 150% scaling, respectively. Every other app (see Edge in screenshots below) runs just OK. I have not tried any other Qt apps yet, but RStudio is way too bigger on my internal monitor. I manage this annoying issue with zooming out (respectively zooming in if RStudio is launched on my internal monitor and then dragged to the other one). However, the toolbar and popups are not affected by any zooming and are hardly reachable.

In these screenshots, I demonstrate the process of dragging RStudio from primary to secondary (internal) monitor. At some point, the window is resized, gets bigger and his "magnification" persist (this may be visible in other apps, but they resize back according to expectation). Last screenshot depicts my Appearance setting in RStudio.

![Snímek obrazovky (9)](https://user-images.githubusercontent.com/34926852/89319214-1b46bc80-d680-11ea-8839-03ece84547c7.png)

![Snímek obrazovky (10)](https://user-images.githubusercontent.com/34926852/89319238-213c9d80-d680-11ea-8033-990a3229c874.png)

![Snímek obrazovky (12)](https://user-images.githubusercontent.com/34926852/89319280-30235000-d680-11ea-9b34-0438b3b22093.png)

**Comment by netique** [comment]
May be helpful: https://bugreports.qt.io/browse/QTBUG-48242

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.
