### ISSUE TITLE
Rstudio server (preview also) fails to accept Korean characters in windows 10 edge.

### ISSUE THREAD

**Issue by parkyongjoo** [rstudio/rstudio#3971]
### System details

    RStudio Edition : Server 
    RStudio Version :  1.2.1153
    OS Version      : Windows 10
    R Version       : 3.3.3

### Steps to reproduce the problem
In Windows 10 Edge browser, just input korean characters at the console or source or terminal  tab. 

### Describe the problem in detail
Korean characters are just ignored at console and source tab. After that, the inputted line stucks with weird characters. At terminal tab, korean characters are splitted down as element by element, but the cmd line does not stuck.  (Server version 1.1 has same problem with Edge browser. In FireFox and Chome browser, there is no problem.)

### Describe the behavior you expected
Korean characters would be correctly inputted.

**Comment by ronblum** [comment]
@parkyongjoo Similar to #3972, would it be possible for you to provide the following to help with reproducing the issue? Thanks!
1) sample code (even just a line or two) as an example
2) a screenshot showing the behavior you're seeing in 1.2? A comparison screenshot of the expected behavior you're seeing in Chrome of Firefox would be helpful, too.

**Comment by kevinushey** [comment]
Do you see the same issue in the [Ace Kitchen Sink](https://ace.c9.io/build/kitchen-sink.html)?

**Comment by jmcphers** [comment]
The Edge browser engine that has this problem is being discontinued in favor of a new Chromium-based version, so we're very hopeful this will resolve the issue. Please let us know if it doesn't.

https://support.microsoft.com/en-us/help/4501095/download-microsoft-edge-based-on-chromium
