### ISSUE TITLE
Rstudio server preview fails to accept Korean characters in iOS safari browser.

### ISSUE THREAD

**Issue by parkyongjoo** [rstudio/rstudio#3972]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1153
    OS Version      : iOS 12
    R Version       : 3.3.3

### Steps to reproduce the problem
When inputting Korean characters in iOS safari at console, source, terminal tab.

### Describe the problem in detail
At console and source tab, the inputted Korean chracters are preceded by sequencial uncompleted characters, these uncompleted characters must be temporarily showed by the input method.  At terminal tab, Korean characters are splitted down as element by element. Server version 1.1 has no problem.

### Describe the behavior you expected
Korean characters would be appreaed properly.

**Comment by aalvero** [comment]
It was actually a problem of Windows and can be resolved with the new update.

![image](https://user-images.githubusercontent.com/17221589/49233115-49f89400-f3c3-11e8-971b-79be6c7020a5.png)

And the new update that resolves it:

[November 27, 2018—KB4467682 (OS Build 17134.441)](https://support.microsoft.com/en-us/help/4467682/windows-10-update-kb4467682)

**Comment by ronblum** [comment]
@parkyongjoo Would it be possible for you to provide the following? This would help with trying to reproduce the problem. Thank you!
1) sample code (even just a line or two) as an example
2) a screenshot showing the behavior you're seeing in 1.2? A comparison screenshot of the expected behavior you're seeing in 1.1 would be helpful, too.

**Comment by parkyongjoo** [comment]
Thank you for your interest of these Korean issue.

1. [Server 1.2 preview with iOS 12 safari](https://youtu.be/_22ZYLRTXrQ)
Inputted Korean characters are preceded by sequencial uncompleted characters. 

2. [Server 1.1 with IOS 12 safari](https://youtu.be/_7fSa3x8yEI)
I found, server 1.1 has another weird phenomenan. Sometimes OK. Somtimes the character is splited by the character's last element. It seems to be influenced by preceding the character(spaces, alphabets or Korean)

I hope this is helpful to find the clue!

**Comment by ronblum** [comment]
@parkyongjoo Is this still an issue? I can't reproduce it using the current versions of Safari (13.0) and Chrome (79.0) on MacOS 10.15 with the current version of RStudio Server, 1.2.5033.

However, I can reproduce it in the Editor and Terminal (but not Console) panes in RStudio Desktop 1.2.5033 on MacOS 10.15, so I'm marking this as a bug.

**Comment by ronblum** [comment]
The original issue was about iOS, and I can reproduce this in iOS 13.3 with both Safari and Chrome.
