### ISSUE TITLE
'Switch Focus between Source/Console' Keyboard Shortcut with 2 key presses does not work correctly.

### ISSUE THREAD

**Issue by gileshd** [rstudio/rstudio#3977]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.463
    OS Version      :  macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem
Set custom keyboard shortcut for "Switch Focus between Source/Console" to a shortcut with multiple key presses, e.g. `Ctrl+A Ctrl+A`.

### Describe the problem in detail
This shortcut will successfully switch focus from the Source --> Console, but will **not** switch focus from Console --> Source.

### Describe the behavior you expected
Expect the focus to switch Console --> Source, a single press shortcut (e.g. `Ctrl+A`) produces the expected behaviour.

**Comment by ronblum** [comment]
@gileshd A single click of `Ctrl+A` is by default assigned to go to the start of the line. What happens if you use a sequence, such as `Ctrl+J Ctrl+J`, that doesn't start with other bound keys?

**Comment by gileshd** [comment]
@ronblum `Ctrl+J Ctrl+J` et al. work great!
Even if I remove `Ctrl+A` from 'Go to Start of Line' `Ctrl+A Ctrl+A` doesn't work, but not the end of the world.
Some key presses produce a conflict warning, however `Ctrl+A` isn't one of them, neither is `Ctrl+N` which conflicts with 'Move Downwards one Line'.

**Comment by jmcphers** [comment]
We haven't had any other reports of this in about a year, and don't realistically think it will be fixed in the near future.
