### ISSUE TITLE
Random JS error when opening a file

### ISSUE THREAD

**Issue by dirkschumacher** [rstudio/rstudio#3980]
I have an R package as an rstudio project. Now within the project, whenever I *open* an .R file, this error comes up immediatly. Saving also does not work anymore. After reopening the project, the error was gone. I haven't seen this before, but I thought it might be helpful to report it.

<img width="423" alt="screen shot 2018-12-01 at 18 10 27" src="https://user-images.githubusercontent.com/1569647/49330828-7a435c80-f594-11e8-95bc-a2cec9f9a4ca.png">

### System details

RStudio Edition : Desktop
RStudio Version :  Version 1.1.453
OS Version      :  MacOS 10.13.6
R Version       : 3.5.1

### Steps to reproduce the problem

I couldn't, after I reopened the project everything was working normal again.
The only thing I remember having done before this error came up was `usethis::use_news_md()`. I also edited the `NEWS.md` file.

**Comment by kevinushey** [comment]
Please fill out the template requesting your system information.

Is the issue still reproducible? Can you share your package sources publicly?

**Comment by jmcphers** [comment]
Since neither you or us can reproduce this any more and we haven't had any reports in over a year, we don't really have anything to go on.
