### ISSUE TITLE
Flickering of Scroll Bar in Environment Pane (server)

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#3982]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1163
    OS Version      : MacOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Open Safari and connect to `rstudio-server` through a vpn;
2. Create some objects to populate the `Environment` pane, enough to make the vertical scroll bar to appear;
3. Move the mouse over the scrolling bar (either from the left or the right), it will disappear then reappear within a second or so.

### Describe the problem in detail
The vertical scroll bar in the `Environment` pane has some flickering in Safari, temporarily disappearing when the mouse is moved over it (and the cursor changes its appearance.) In Firefox, the scroll bar doesn't disappear, but the background color changes together with the foreground color. This doesn't affect the other panes.
The quick disappearance in Safari also tends to modify the size of the `Environment` and `Help` panes, which is quite annoying.

**Comment by jmcphers** [comment]
I can reproduce the flickering issue, but not the size change. What scrollbar settings are you using in MacOS? (System Preferences -> General -> Show scroll bars)

**Comment by pascaloettli** [comment]
Right, I forgot to mention this information. I use "Always".

**Comment by jmcphers** [comment]
Still reproduces on 1.3.625, unfortunately, with macOS 15 (Catalina) and Safari 13.0.3
