### ISSUE TITLE
Unable to install R packages updates after migration to new computer

### ISSUE THREAD

**Issue by EricGoldsmith** [rstudio/rstudio#3983]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1.463
    OS Version      : MacOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem
After migrating (using Mac’s Migration Assistant) to a new computer, every time I would try to check for package updates in RStudio (`Tools -> Check for package updates`), I get the message “All packages up to date”. But, I know that wasn’t true. 

From the RStudio console, I tried manually and got:
```
> update.packages(ask = FALSE)
Warning in install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  'lib = "/Library/Frameworks/R.framework/Versions/3.5/Resources/library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) 
```
A clue!

Then I fired up my old computer and discovered that all the files from the `R.framework/` directory were in the group `admin`, whereas on my new computer they were not. 

Doing this (from a console window) fixed the issue:
```
cd /Library/Frameworks/
$ sudo chown -R :admin R.framework/
```

But, a more helpful message from RStudio would have gotten me there quicker.

**Comment by kevinushey** [comment]
FWIW I would recommend installing your R packages into a user library rather than the system library to avoid issues like this.
