### ISSUE TITLE
Add navigate in history of "Find in files" searches

### ISSUE THREAD

**Issue by eaurele** [rstudio/rstudio#3987]
This is a feature request for the "Find in files" feature.

I use "Find in files" a lot, especially when exploring large-ish code bases written by others or myself. I often find myself searching for a term, then another one, then another one, and wanting to come back, but having lost my train of thoughts.

Would be great if I could navigate in the history of my "Find in files" searches.

Thanks for a great product!

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463
    OS Version      : applicable to all I guess (me: Windows 10 or Ubuntu 18.10)
    R Version       : applicable to all I guess (me: 3.5)

#

**Comment by ronblum** [comment]
@eaurele Thank you for the suggestion! We'll take a look at it as we continue development of RStudio.

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/2934 (requesting history for the directory searched, whereas this is history for the term searched)
