### ISSUE TITLE
Publish button is very laggy

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#3994]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1165
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

* Open a Shiny application. 
* Click publishing icon
* Click Publish button

![image](https://user-images.githubusercontent.com/86978/49529345-6db45200-f87b-11e8-8a56-ba3babaf88d4.png)

Nothing happens for a few seconds, so I often click the button again. But then after a few more seconds it says it can't deploy because another deployment is happening. Right after that, I can see the deployment happening in the Deploy tab.

**Comment by kevinushey** [comment]
Does any indicator show up to indicate that 'stuff is happening' after the initial Publish button press?

**Comment by wch** [comment]
Nope. Here's a recording:

![shiny-deploy 2018-12-05 11_30_22](https://user-images.githubusercontent.com/86978/49532015-3ba5ee80-f881-11e8-8112-ed4850a6c9e3.gif)

This seems to happen only for the first deployment of the app. If I redeploy, then everything happens quickly.

**Comment by wch** [comment]
Here's a screenshot of the RStudio request log after the slow publishing:
![image](https://user-images.githubusercontent.com/86978/49535847-c17a6780-f88a-11e8-9597-b50e1c4c97eb.png)

**Comment by jmcphers** [comment]
Should be resolved by https://github.com/rstudio/rstudio/commit/533b5fa947672c80990c45fd4dac419cada23b4d.
