### ISSUE TITLE
Themes unit test failures related to .ace_invisible

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#4009]
In an RStudio dev environment, run ` ./rstudio-tests --filter themes`.

Get a bunch of failure, first batch of the form:

```
Theme: Tomorrow
CSS has more elements than exepected. Actual: 38, Expected: 37 

Theme: Tomorrow
CSS had 1 unexepected elements with names: 
   ".ace-tomorrow .ace_invisible" 
```

Then another batch like this:

```
test-themes.R:960: failure: convertTmTheme works correctly with parseTmTheme
compareCss(...) isn't true.
Theme: Active4D
```

**Comment by jmcphers** [comment]
Let's fix this in 1.2 if it's simple, or turn of this test in 1.2 (we will want to get a clean unit test pass when we validate 1.2 patch releases).
