### ISSUE TITLE
"SQL" autocomplete errored

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#4011]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : 1.2.1163
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : R version 3.5.1 (2018-07-02)

### Steps to reproduce the problem

In a `SQL` chunk, hit <kbd>Tab</kbd> to autocomplete my input.

### Describe the problem in detail

The autocompletion won't succeed. And the following error message appeared in console:

```r
## Error in ctx$schemas[[match(table, ctx$tables)]] : 
##  subscript out of bounds
```

**Comment by kevinushey** [comment]
Thank you for taking the time to provide a reproducible example! I've reproduced this locally; we'll try to get this fixed up soon.
