### ISSUE TITLE
Autosave loses data when RStudio crashes

### ISSUE THREAD

**Issue by MarcoPortmann** [rstudio/rstudio#4012]
I’ve worked with RStudio for 3 months and in this short period I had about four app crashes in which I lost several unsaved scripts. I really don’t understand how RStudio loses data when it has an autosave function. It is nice, that you can close/restart RStudio and it doesn’t bother you with save dialogs. However, it seems that autosave is pretty worthless when it comes to app crashes.

I work with desktop version 1.1.453 on windows 10. I think that most crashes were related to R code that produced graphical output and used the viewer pane (ggplot, manipulateWidget). I don’t remember, how to reproduce these crashes. Anyway, I think the causes of the crashes are not relevant, this issue is rather about the implementation of autosave.

**Comment by kevinushey** [comment]
Sorry to hear you're having so much trouble :-/

We're aware of issues around crash recovery in RStudio, and hope to have improved here with RStudio v1.2, which is currently available as a [preview release](https://www.rstudio.com/products/rstudio/download/preview/). If you're willing, you can give it a download and let us know if the situation does indeed appear to be improved.

**Comment by ronblum** [comment]
@MarcoPortmann Were you able to try out the [preview release](https://www.rstudio.com/products/rstudio/download/preview/), and if so, what was the outcome?

**Comment by MarcoPortmann** [comment]
Unfortunately, I cannot currently install on the machine where the data with the corresponding R project is located (security policies of the organization).
I haven't had any data loss since December, but I've hardly used the widgets that caused the crash.
However, I noticed that R-Studio often doesn't respond to commands like ctrl+s when an R session is busy. I find this very surprising, since the GUI and the R session run in different processes. But this may be another issue. Feel free to close this issue if you think the problems will be solved with the next update.

**Comment by jmcphers** [comment]
No other reports of this in over a year, so closing. If you ever lose autosaved content like this again, you might try the rsrecovr package to get it back: 

https://github.com/jmcphers/rsrecovr
