### ISSUE TITLE
Window cannot be resized

### ISSUE THREAD

**Issue by RobertZimbardo** [rstudio/rstudio#4013]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1153
    OS Version      : Linux Mint 19
    R Version       : 3.5.1

### Steps to reproduce the problem
I have RStudio set up with the following Panel Layout:

- top left: Console
- top right: Source
- bottom left: Environment/...
- bottom right: Files/...

As  a result of issue <RStudio: scaling on second monitor #3966>, at some point the Files/... pane got maximized and now I can only have it maximal (so that the Source window is completely minimized) or minimized (so that the Files/... window is completely minimized). Clicking on the buttons doesn't do anything other than make the top row of that window visible (the pane title, to so speak), but mouse-overing over teh whole vertical range at no point leads to a hand that allows me to split the right side up into two equally large panes.

**Comment by kevinushey** [comment]
Does using e.g. <kbd>Ctrl + Shift + 1</kbd> to toggle zoom of the Source pane help?
