### ISSUE TITLE
Rstudio Desktop Windows doesn't display .mp4 files

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#4019]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1184
    OS Version      : Windows 10 Pro Build 17134.407
    R Version       : 3.5.1

### Steps to reproduce the problem
Having ffmpeg installed, run this code
```
library(ggplot2)
library(gganimate)
p <- ggplot(airquality, aes(Day, Temp)) +
    geom_line(size = 2, colour = 'steelblue') +
    transition_states(Month, 4, 1) +
    shadow_mark(size = 1, colour = 'grey')
animate(p, renderer = ffmpeg_renderer())
```
### Describe the problem in detail
Rstudio doesn't display .mp4 files rendered by gganimate using ffmpeg, apparently this has nothing to do with gganimate anymore (see this [issue](https://github.com/thomasp85/gganimate/issues/201))

![image](https://user-images.githubusercontent.com/14981085/49690168-3ef7df00-fafa-11e8-84e7-f21f3a5c9bbf.png)

### Describe the behavior you expected
I expected to see the mp4 file displayed in the viewer pane or in a rmarkdown notebook.

**Comment by ronblum** [comment]
@andresrcs Thanks for reporting this. Reproduced on MacOS 10.14 Mojave, as well, and confirmed that it works with standalone R.

**Comment by kevinushey** [comment]
I see this in the terminal (from where I launched RStudio):

> [28981:32315:1210/090045.594301:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
> [28981:775:1210/090045.594360:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS


From https://doc.qt.io/qt-5.11/qtwebengine-features.html:

> Qt WebEngine supports the MPEG-4 Part 14 (MP4) file format only if the required proprietary audio and video codecs, such as H.264 and MPEG layer-3 (MP3), have been enabled. Proprietary codecs can be enabled by passing the following option to the configure tool when configuring Qt:
> 
> -webengine-proprietary-codecs
> For example, the following option could be passed when configuring Qt for building it at the top level:
> 
> configure -webengine-proprietary-codecs
> For more information, see Qt Configure Options.
> 
> When using qmake to build just the Qt WebEngine module, the following command can be used (in this example, the Qt WebEngine source code is located in C:\qt\qtwebengine):
> 
> qmake C:\qt\qtwebengine -- -webengine-proprietary-codecs
> Warning: When distributing proprietary codec libraries, you must acquire licenses for them.
> 
> FFmpeg is a cross-platform solution to record, convert, and stream audio and video. It can be configured for use with several codecs, which rises licensing issues during distribution with the codec libraries. For some codecs, open source implementations, such as OpenH264, are available.

I'm guessing that QtWebEngine does not bundle the proprietary codecs used by default with `ffmpeg`. Does enforcing the use of OpenH264 help here?

**Comment by kevinushey** [comment]
I also see that the `renderer` argument / function is ignored when passed to `gganimate()`. @thomasp85 do you have any insight?

**Comment by thomasp85** [comment]
In what way is it ignored?

**Comment by kevinushey** [comment]
Sorry, I was wrong -- the render function is being called. (I was under the impression that it was the function being called while the Rendering progress bar is shown)

**Comment by kevinushey** [comment]
IIUC, the only way for us to fix this may be to build our own copies of Qt that allow use of the proprietary codecs...

**Comment by thomasp85** [comment]
Is there a default ffmpeg setting I can add to gganimate that will result in an RStudio compliant output?

**Comment by kevinushey** [comment]
I hope so, but I'm not sure...

FWIW I can reproduce outside of RStudio; e.g. if I try to use Chromium as my browser (since it doesn't come with proprietary h264 codecs). In that case, I just get a blank, non-playing video.

**Comment by thomasp85** [comment]
I'll try to look for something - if you stumble on anything, let me know...

Last solution will be to detect that RStudio is running and open it up in a browser instead, but that would really be a usability downer

**Comment by kevinushey** [comment]
Alternatively, a different video format could be used altogether (e.g. `webm`)? That works without issue in RStudio.

**Comment by thomasp85** [comment]
I *thought* `mp4` was generally HTML5 compliant...

**Comment by kevinushey** [comment]
It is, but the codecs for encoding / decoding MP4 files are proprietary, and so aren't available in all browsers. (IIUC the "big" browsers just license and bundle them)

In theory OpenH264 is an alternate open-source encoder that could be used here, but unfortunately builds of `ffmpeg` don't seem to come with that enabled / supported by default (from what I can see).

**Comment by thomasp85** [comment]
What upstream change in RStudio resulted in loosing these codecs?

**Comment by kevinushey** [comment]
We switched from using QtWebKit (the very old, Safari-based rendering engine) to QtWebEngine (which is based on Chromium).

**Comment by thomasp85** [comment]
Ah... well, and this might sound like I'm lazy, I think it would be good to add the codecs if possible... This will probably also rear its head up in other places such as previewing blogdown pages, etc.

**Comment by thomasp85** [comment]
I guess you stumbled upon this as well: https://stackoverflow.com/questions/50971187/can-i-build-chromium-with-ffmpeg-to-support-all-video-formats

**Comment by kevinushey** [comment]
Yes, in theory we could do the work to build Qt ourselves to bundle + use these proprietary codecs. This would not be a small undertaking; we gain a lot by using the official Qt binaries since we have at least some guarantee that these are well-tested across platforms (especially the different flavors of Linux).

However, there are almost certainly legal issues due to licensing requirements around the bundling of these codecs in RStudio. If we wanted to bundle these codecs, we'd likely have to pay a licensing fee, and I can guess it's not cheap (both in the actual cost; and the extra time required to make sure we're adhering to the terms of the license).

**Comment by thomasp85** [comment]
Fair enough, I won’t press the matter🙂 I’ll probably switch defaults to webs as most people are likely to use it through rstudio

**Comment by kevinushey** [comment]
I think you might want to make the default depend on the environment R is being run in, e.g.

    if (.Platform$GUI == "RStudio") "webm" else "mp4"

just because the reality is that `.mp4` is a more widely supported standard, despite being less 'open' than `.webm`.

https://caniuse.com/#search=mp4
https://caniuse.com/#search=webm

**Comment by andresrcs** [comment]
> The legal situation around `.mp4` and the proprietary codecs required to decode such files makes this a hairy problem for us to solve.
> 
> @andresrcs I would recommend just using `renderer = ffmpeg_renderer(format = "webm")` for now.

I just wanted to embed animations in rmarkdown notebooks, so this walk around solution is ok for me, thanks.

**Comment by thomasp85** [comment]
hmm... this is even more problematic to handle gracefully as webm support is not supported by default by ffmpeg (you have to compile it with `--enable-libvpx` to get it)

**Comment by kevinushey** [comment]
😭 

Now I understand why `.gif`s are still so widespread...

**Comment by kevinushey** [comment]
At least the default version of `ffmpeg` from Homebrew (the bottle) is compiled with support built-in...

```
$ ffmpeg -buildconf
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gpl --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-opencl --enable-videotoolbox
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

  configuration:
    --prefix=/usr/local/Cellar/ffmpeg/4.1
    --enable-shared
    --enable-pthreads
    --enable-version3
    --enable-hardcoded-tables
    --enable-avresample
    --cc=clang
    --host-cflags=
    --host-ldflags=
    --enable-ffplay
    --enable-gpl
    --enable-libmp3lame
    --enable-libopus
    --enable-libsnappy
    --enable-libtheora
    --enable-libvorbis
    --enable-libvpx
    --enable-libx264
    --enable-libx265
    --enable-libxvid
    --enable-lzma
    --enable-opencl
    --enable-videotoolbox
```

**Comment by thomasp85** [comment]
But the build machines have an old version without support, so more or less everyone not on Linux will get an av version without support...

Another sad reality is that encoding is orders of magnitude slower compared to mp4 H.264

**Comment by kevinushey** [comment]
Ultimately this isn't something we'll be able to fix in RStudio v1.2, so I'm going to punt (it's still worth consideration).

I think 'best practice' for websites still mandates that users provide multiple video formats for a particular video, so the browser can pick the one it best supports.

**Comment by kevinushey** [comment]
It looks like gganimate works around this issue now by preferring `webm` when supported by the version of `ffmpeg` in use, and by opening in an external window when not. Thanks @thomasp85! Sorry there wasn't something better we could do in RStudio.

**Comment by jmcphers** [comment]
We should see if the Electron port fixes this (i.e. if it ships those codecs out of the box)

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by andresrcs** [comment]
I tested with version 2022.07.1+554 and it is working now.

**Comment by ronblum** [comment]
@andresrcs Thank you for verifying!
