### ISSUE TITLE
Adjust column width in Global Environment

### ISSUE THREAD

**Issue by scottprevost** [rstudio/rstudio#4020]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1139, v1.1.463
    OS Version      :  Windows 7
    R Version       :  3.5.1

### Steps to reproduce the problem

This problem can be reproduced by installing RStudio and attempting to adjust the column widths displaying variable (data.frames, lists, etc.) in the Global Environment pane, in either Grid or List mode. 

### Describe the problem in detail

When viewing variables in the Global Environment pane of RStudio, the column widths cannot be adjusted in either List or Grid view. This would be helpful to adjust the column widths to better inspect the variable (data.frames, lists, etc.) names, especially when working on larger projects where there are many variables. Only the first X number of letters of the variable name are shown and when some variable names are similar to others or have a common naming theme, they cannot be differentiated in the Global Environment pane without hovering your mouse over the names. You can adjust the entire pane width, but then you lose space to write your R code and also ALL the columns in the Global Environment scale, so you still have the same problem.

### Describe the behavior you expected

Would like to be able to individually adjust the column widths in the Global Environment to better inspect and view variable names.

**Comment by ronblum** [comment]
@scottprevost  Thank you for the observations and suggestion. We'll consider them as we work on future versions of RStudio.

**Comment by acvelozo** [comment]
Hi @jmcphers , taking into account this commit from May 2019, I would imagine that the latest RStudio version would allow for resizing the columns in the Environment pane, should this be the case? This would be very useful for me, since I am working with long variable names. Maybe I am interpreting incorrectly the subject of this commit?

I am using RStudio 1.2.5033 on Windows. Here is a screenshot of the Environment pane columns, which I am currently not able to resize:
![image](https://user-images.githubusercontent.com/16723411/72395650-19dc9380-3732-11ea-8846-9b78a918c09d.png)

Thank you for this tool, it has a huge impact on my work.

**Comment by jmcphers** [comment]
This feature is currently only available in the daily builds of RStudio:

https://dailies.rstudio.com/

**Comment by scottprevost** [comment]
I downloaded RStudio from the daily builds link above and am able to resize the columns. Thanks so much!

**Comment by catalytic-ca** [comment]
RStudio Environment pane columns are resizable, but only for the List view. The Grid view column widths do not seem to be adjustable. Would it be possible to extend the adjustable column widths to the Grid view too?

**Comment by bjcresswell** [comment]
> RStudio Environment pane columns are resizable, but only for the List view. The Grid view column widths do not seem to be adjustable. Would it be possible to extend the adjustable column widths to the Grid view too?

I would second this addition!!  But if that isn't possible, I'd also highlight the following related issue: after resizing columns (List view only obviously as it doesn't work in Grid view), if you add another item to the Environment pane, it resizes back to the original column width!

Thanks for all you do.

**Comment by andrewjunlee** [comment]
Figure it's been a year since the last person made a request, so I'm here to echo the voices of other people who dream of someday being able to resize the columns in the global environment's grid view. Similarly, thanks for all the work y'all do!
