### ISSUE TITLE
Interruption of reticulate'd function call causes RStudio bomb

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#4021]
It's me so always latest dailies and it's been happening for a few weeks now so I thought it time to post.

I wrote some reticulated wrappers to `boto3` libraries (the `roto3.abc…` packages in `cloudry`, this one would be `roto.s3`: `https://github.com/cloudyr/roto.s3`).

If, say, I start a large file transfer operation but try to kill it (ESC in RStudio console) I consistently get:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/509878/49738833-5e0f8180-fc5e-11e8-9fcc-9f5d12ec8ba7.png">

and RStudio pops up the "bomb" dialog.

This never used to happen and I can't say exactly when this started to happen dailies-wise, but it does it on all my Macs (all the ones I do active dev on for this are on 10.14.2).

I'll be glad to post detailed debug info if this sounds like it belongs here or if you think it'd be better over in reticulate-land. 

reticulate version is 

```
 reticulate         1.10       2018-08-05 [1] CRAN (R 3.5.0)                       
```

**Comment by kevinushey** [comment]
Do you see the same issue when running this code in a plain R console, as opposed to RStudio?

We did indeed change how interrupts are handled in RStudio recently, but in theory RStudio now behaves _more_ like R in the terminal, not less :-)

It'd also be helpful if you could provide a reproducible example.

**Comment by hrbrmstr** [comment]
this was ultimately an rJava issue which has been fixed with the recent update to rJava on CRAN
