### ISSUE TITLE
Rstudio v1.2 preview does not apply installed system fonts

### ISSUE THREAD

**Issue by sdhutchins** [rstudio/rstudio#4024]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1181
    OS Version      :  Windows 7
    R Version       : 3.5.1

### Steps to reproduce the problem
Try to select an installed font such as `Code New Roman`

### Describe the problem in detail
The font is not successfully applied -- instead, the default monospace font is used.

### Describe the behavior you expected
Before upgrading to the v1.2 preview, I could use fonts that I installed. Now, I can't.

### Session Information

```console
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.1.1

loaded via a namespace (and not attached):
 [1] compiler_3.5.1   backports_1.1.2  rsconnect_0.8.11 rprojroot_1.3-2  tools_3.5.1      htmltools_0.3.6  Rcpp_1.0.0       xml2_1.2.0      
 [9] rmarkdown_1.10   knitr_1.20       digest_0.6.18    packrat_0.5.0    evaluate_0.12   
```

**Comment by kevinushey** [comment]
> The font is not successfully applied -- instead, the default monospace font is used.

Just to elaborate -- are you saying the font shows up in the font list, but attempting to select it fails? Or does the font not show up in the font list at all?

I tried installing Code New Roman (as from https://www.dafont.com/code-new-roman.font) but it doesn't show up at all in the font list for me (both with RStudio v1.1 and RStudio v1.2).

**Comment by sdhutchins** [comment]
> Just to elaborate -- are you saying the font shows up in the font list, but attempting to select it fails? Or does the font not show up in the font list at all?
> 
> I tried installing Code New Roman (as from https://www.dafont.com/code-new-roman.font) but it doesn't show up at all in the font list for me (both with RStudio v1.1 and RStudio v1.2).

Yes, it shows up in the font list for me, but selecting it shows the default monospace font.

**Comment by kevinushey** [comment]
Thanks. It looks like RStudio is excluding this font out because it is not a true monospace font -- only monospaced fonts are supported in the RStudio IDE. In particular, the `l` and `i` characters in that font are smaller in width than other characters.

You can confirm this by trying to type e.g. 10 `l` characters using that font, and comparing it to a long set of 10 `w` characters. The line with the `w`s is longer than the line with `l`s.

**Comment by sdhutchins** [comment]
That's interesting. Even the ones I downloaded via google fonts (`Inconsolata`, `Source Code Pro`) aren't working. I'll try to find a font to test.

**Comment by jmcphers** [comment]
Haven't heard back in over a year so closing. Please open a new issue if you find that the monospace fonts you tested aren't showing up in the latest build (1.2.5033).
