### ISSUE TITLE
random rendering issue with Windows 10 in preview

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4025]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1181
    OS Version      : Windows 10.0.17134 (64-bit)
    R Version       : 3.5.1

### Steps to reproduce the problem

Open the Appearances pane in the Global Options menu, and try clicking the Editor font dropdown multiple times.

### Describe the problem in detail

Occasionally, a rendering error occurs where the IDE itself is rendered in the dropdown. :wat:

<img width="190" alt="screen shot 2018-12-10 at 1 33 34 pm" src="https://user-images.githubusercontent.com/1976582/49763083-8ad49080-fc80-11e8-8a40-7fad5923df58.png">

### Describe the behavior you expected

Just the fonts...

### Notes

This was run within a virtual machine, with a macOS host (2018 MBP, Mojave 10.14.1, Parallels)

**Comment by gtritchie** [comment]
I think you found a portal to another dimension. Do you dare click the dropdown again?...

**Comment by jmcphers** [comment]
Is this fixed in Qt 5.12?

**Comment by kevinushey** [comment]
Unfortunately no -- I can reproduce in both the current preview (1.2.1206; using Qt 5.11.1) and the current daily (1.2.1223; using Qt 5.12.0).

Still, this feels like a new-ish issue (I haven't seen it before) so it may be unique to my particular environment. We should see if it reproduces on a real physical machine. If not, we can probably just close this.

**Comment by kevinushey** [comment]
I can't reproduce on our in-house Windows laptop so I'm going to push out of v1.2.
