### ISSUE TITLE
R studio doesn't have good Hindi support for typing and reading

### ISSUE THREAD

**Issue by vikram-rawat** [rstudio/rstudio#4027]
I opened an issue of community.rstudio.com and they asked me to open an issue here.

https://community.rstudio.com/t/r-studio-doesnt-have-good-hindi-support/19721/4

I have been using r studio for many years and I never noticed it until recently. When I wanted to write my book in R studio through bookdown I chose Hindi as my language.

It turns out that when I type Hindi the curser moves ahead of the words and it becomes very hard to understand which word are you on. Especially when you want to delete something.

Then I switched to vscode and I found it had no such problem writing Hindi Unicode. So did atom. Somehow rstudio have such problem.

Just find any text in Hindi from Google and try to delete it and you will understand what I mean. Let me find some random text for you.

```
मोहनदास करमचन्द गांधी (२ अक्टूबर १८६९ - ३० जनवरी १९४८) भारत एवं भारतीय स्वतंत्रता आंदोलन के एक प्रमुख राजनैतिक एवं आध्यात्मिक नेता थे। वे सत्याग्रह (व्यापक सविनय अवज्ञा) के माध्यम से अत्याचार के प्रतिकार के अग्रणी नेता थे, उनकी इस अवधारणा की नींव सम्पूर्ण अहिंसा के सिद्धान्त पर रखी गयी थी जिसने भारत को आजादी दिलाकर पूरी दुनिया में जनता के नागरिक अधिकारों एवं स्वतन्त्रता के प्रति आन्दोलन के लिये प्रेरित किया। उन्हें दुनिया में आम जनता महात्मा गांधी के नाम से जानती है। संस्कृत भाषा में महात्मा अथवा महान आत्मा एक सम्मान सूचक शब्द है। गांधी को महात्मा के नाम से सबसे पहले १९१५ में राजवैद्य जीवराम कालिदास ने संबोधित किया था।[1]। उन्हें बापू (गुजराती भाषा में બાપુ बापू यानी पिता) के नाम से भी याद किया जाता है। सुभाष चन्द्र बोस ने ६ जुलाई १९४४ को रंगून रेडियो से गांधी जी के नाम जारी प्रसारण में उन्हें राष्ट्रपिता कहकर सम्बोधित करते हुए आज़ाद हिन्द फौज़ के सैनिकों के लिये उनका आशीर्वाद और शुभकामनाएँ माँगीं थीं।[2] प्रति वर्ष २ अक्टूबर को उनका जन्म दिन भारत में गांधी जयंती के रूप में और पूरे विश्व में अन्तर्राष्ट्रीय अहिंसा दिवस के नाम से मनाया जाता है।
```
 Please fix this if possible.

And there is a problem with viewing a data frame which has a column written in Hindi.

**Comment by kevinushey** [comment]
I think it's different, since the font here isn't monospace, as opposed to being a monospace font with unicode connecting characters.

**Comment by vikram-rawat** [comment]
I tried to read an image file in R today and it turns out to be that I could read it fine when it's in text format but not when it is in a data.frame

```
text<-ocr(image = "image/CMB0760301.PDF_1.png",engine = 'hin')
```
this command produces this output
![image](https://user-images.githubusercontent.com/22342596/50537619-2bcfb080-0b88-11e9-8f8c-5b942523840d.png)

but if I use it with dataframe output

```
text_dt<-ocr_data(image = "image/CMB0760301.PDF_1.png",engine = 'hin')
```

![image](https://user-images.githubusercontent.com/22342596/50537647-75200000-0b88-11e9-9dae-97dac5d7803c.png)


Please help me out if possible.

This is the image

![cmb0760301 pdf_1](https://user-images.githubusercontent.com/22342596/50537658-984aaf80-0b88-11e9-8f00-ab0589ab0b9e.png)

Please let me know how to fix it

**Comment by SandeepShaw2017** [comment]
I am facing similar issue when writing from hindi to a text file ..... the output is like: 

U+0968><U+096C>; <U+0916><U+0940> <U+0939> _ 3" -“/ <U+0967>-<U+096B>. > 9 

my suggest ho to write a file in hindi in R

**Comment by KapilKhanal** [comment]
was this resolved in the new Rstudio release?

**Comment by jmcphers** [comment]
It was not, sorry. Does it work as you expect in the Ace Kitchen Sink?

https://ace.c9.io/build/kitchen-sink.html

**Comment by KapilKhanal** [comment]
I am having same problems. Thank you for the link. I did not knew about this service before.

**Comment by kulbhushanchand** [comment]
Commenting to keep this issue open. 
I'm facing the same problem i.e. incorrect display of Hindi font in RStudio, which makes `.Rmd` files difficult to edit. 
For example, in screenshot below, the appearance of non-editable markup represented by yellow lines. 

![image](https://user-images.githubusercontent.com/17742733/108689803-8cb46280-751f-11eb-9a72-8bcd73915dd7.png)

**Comment by aartimalik** [comment]
Same issue. Please resolve this.
