### ISSUE TITLE
Default R Markdown files to UTF-8 encoding on Windows

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4028]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1186
    OS Version      : Windows 10

### Steps to reproduce the problem

1. File -> New R Markdown Document
2. Add non-ASCII text to the document (e.g. a Unicode character)
3. Save the document

### Describe the problem in detail

The R markdown document is saved in the Windows system encoding (ISO-8859-1) by default. 

### Describe the behavior you expected

knitr and rmarkdown are slowly transitioning to UTF-8 only (@yihui lists [supporting other encodings as his biggest knitr regret](https://yihui.name/en/2018/11/biggest-regret-knitr/)); the IDE should start defaulting new R Markdown content to UTF-8 for compatibility with these packages (and other tooling).

**Comment by kevinushey** [comment]
Don't we normally show the "select an encoding" dialog if the character isn't representable in the system locale? E.g.

![screen shot 2018-12-11 at 11 20 08 am](https://user-images.githubusercontent.com/1976582/49824346-bd40c500-fd36-11e8-9179-fbfbdbf08499.png)

Is the plan to eschew this dialog altogether and always save as UTF-8, or default to selecting UTF-8 in such circumstances?

**Comment by jmcphers** [comment]
We do. I think we should eschew the dialog altogether for R Markdown documents and just save in UTF-8; the planned changes to knitr mean that eventually nothing else is going to work. If you *really* need another encoding, you can always Save With Encoding to pick a different one.

For other file types, we might consider making UTF-8 the default instead of the system encoding, although as I don't really understand why the system encoding is the default in the first place [caution is warranted](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence).

**Comment by yihui** [comment]
We only have control over the file formats read and processed by our own packages, such as Rmd/Rnw files. For other files, we shouldn't force UTF-8. For example, `source()` runs R scripts with the system native encoding by default.
