### ISSUE TITLE
Show memory usage in environment pane

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4033]
The Environment pane shows the size of all of the objects in the environment, but does not show either (a) the total size of the objects, or (b) the amount of memory available for use. 

This information would be very helpful in resource-constrained environments; for example, it'd be easier to see what you have to work with and avoid expensive computations when there may not be sufficient room for the result.

**Comment by coatless** [comment]
I was _just_ about to write an issue for this. 

It would be great to see the size of the data set or overall amount of memory being used by the _R_ environment / session in the data viewer.

As it stands now, when loading data, users are not shown any indication of memory size of the objects. This causes problems if there are imposed memory conditions (e.g. RStudio Cloud's 1 GB limitation).

<img width="797" alt="screen shot 2019-02-01 at 10 27 12 am" src="https://user-images.githubusercontent.com/833642/52135970-a323b480-260c-11e9-9525-64feff7daa2a.png">

To get around this, I'm deploying:

```r
mem_usage = function(active_env = .GlobalEnv) {
  sort(sapply(ls(active_env), function(x) {
    object.size(get(x))
  }), decreasing = TRUE)
}
```

```r
# Some data
my_cars = mtcars
the_matrix = matrix(rnorm(10000), nrow = 100)
the_list = list(the_matrix, my_cars)

# Determine size.
mem_usage()
#  the_list the_matrix  mem_usage    my_cars 
#     87488      80216       9944       7208 
```

**Comment by tareefk** [comment]
I just wanted to make sure I put the comment in here as well.  The ask from the DaVinci team in Novartis is to be able to see the CPU utilization of the slurm sessions they have IN the IDE.  In an ideal world you would see that you are 90% of memory requested, so that you could take actions.  
Extra credit if there is a way to configure RSP to force a GC at a certain threshold.  The team requesting this is led by a very smart, humble and pragmatic person and I think he would be a great design partner to bounce ideas off of. His name is Michael Mayer.  Jason and Andrie can provide contact info if that is wanted/needed.

**Comment by jmcphers** [comment]
> Extra credit if there is a way to configure RSP to force a GC at a certain threshold.

This is really outside the purview of the IDE itself, and would be hard to get right without creating the possibility of a negative feedback loop at a low level. R itself has a garbage collection trigger threshold that can be adjusted using environment variables which would be a great place to start: https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Memory

We should absolutely show the utilization in the IDE; I've got a PR for that and will be submitting early next week.

**Comment by valerie-rstudio** [comment]
### Verify Failed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1546
    OS Versions     : mac OS 11.1

### Failure Points
 Free Unused R Memory does not result in a reduction of the memory usage displayed .
1. Open a brand new R project. Take note of the memory usage.
2. Open a new R Script. Run code that will generate some data that will appear in the Environment pane. `library(dplyr)` `tib_wNA <- as_tibble(data.frame(replicate(100,sample(c(NA,NA,0:1),10000,rep=TRUE))))`
3. Take note of the memory usage listed.
4. Click the broom icon in the Environment Pane to clear objects from the workspace. Check the Include Hidden Objects box and click yes.
5. Click Free Unused R Memory (once or multiple times, it does not make a diference. Also attempted waiting several minutes after clicking).
6. **Expected**: The memory usage displayed should go back down to roughly what it was whenever the project was first created.
7. **Actual**: The memory usage displayed remains the same.

### Notes
- If you follow all the failure point steps and then close out of and reopen RStudio, the listed amount of memory is reduced back down to the expected amount.

**Comment by jmcphers** [comment]
> The memory usage displayed remains the same.

Does the memory usage displayed by RStudio disagree with the memory usage of the `rsession` process as reported by the operating system?

**Comment by jmcphers** [comment]
In particular I don't think this test case causes R to actually consume very much memory. You can see this going from 40.6 => 40.7 mb (too small to affect the memory usage value). 

```
> gc()
          used (Mb) gc trigger (Mb) limit (Mb) max used (Mb)
Ncells  759873 40.6    1365431   73         NA  1365431 73.0
Vcells 2690445 20.6    8388608   64      32768  6111360 46.7
> tib_wNA <- as_tibble(data.frame(replicate(100,sample(c(NA,NA,0:1),10000,rep=TRUE))))
> gc()
          used (Mb) gc trigger (Mb) limit (Mb) max used (Mb)
Ncells  761543 40.7    1365431   73         NA  1365431 73.0
Vcells 3192811 24.4    8388608   64      32768  6111360 46.7
```

You might try with larger data that R can't store compactly, such as `bigval <- runif(1e8)`.

**Comment by astayleraz** [comment]
Verified new memory usage feature on Mac, Win 10, and various Linux Oses. Also added an automated test for this. Closing issue.
