### ISSUE TITLE
Installing hangs -- killed after 24 hours.

### ISSUE THREAD

**Issue by abalter** [rstudio/rstudio#4035]
### Steps to reproduce the problem
```
[previously conda create -n rstudio]
[conda activate rstudio]

(rstudio) balter@exanode-1-32:~/teamMB$ conda install rstudio -y
Solving environment: \ srun: Force Terminated job 7166428                                                                                                                 | srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
Terminated

```
### Describe the problem in detail
I tried installing rstudio with conda on a compute node  on my cluster requested for 24 hours. The solving environment step never  completed before the timeout. I have no trouble installing other conda packages.

### Describe the behavior you expected
Conda would solve the install requirements and give me the option to continue.

### Additional information:

```
(rstudio) balter@exahead1:~/teamMB/projects$ conda config --show-sources
==> /home/users/balter/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by kevinushey** [comment]
Sorry, but we don't maintain the RStudio package distributed through Conda and cannot provide support there -- you should get in touch with the Conda team.

(In general, we recommend using the official RStudio binaries available from https://RStudio.com/products/rstudio/download/)
