### ISSUE TITLE
Paste images in (R) Markdown documents

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4038]
Currently, adding an image to an R Markdown document from the clipboard is remarkably cumbersome. Even the easiest way requires a lot of steps:

1. paste the image into an image editor (such as Preview.app),
2. save it into your R project,
3. type the magic incantation for Markdown images `![](img/..)`, and
4. navigate autocomplete to the filename.

In some Markdown editors, including the one on which I'm writing this, it's possible to just paste images right into the editor. The image is uploaded, saved with a unique name, and the code to reference it is generated and inserted at the cursor. This would be very convenient for writing R Markdown documents that use a lot of external images!

Aside from technical hurdles, we'd want to be sure that this didn't do too much to encourage users to have images with meaningless names and no alt-text. Towards this end, we might e.g. display a dialog on paste -- which could always be instantly dismissed with <kbd>Enter</kbd> -- offering a just-in-time opportunity to supply a meaningful filename, location (saved as default for the doc), and alt text.

It'd also be useful to insert images via drag-and-drop of the files themselves; see #4037.

**Comment by Timag** [comment]
I ran into the same issue and gave it a try.

See here: https://stackoverflow.com/questions/55541345/copy-and-paste-an-image-from-clipboard-to-rmarkdown-rmd-code/55541381#55541381 and
here: https://github.com/Timag/imageclipr.

It is still a workaround as i call Python code in the backend, but maybe it already saves some coders some time :).

**Comment by christopherball** [comment]
I'm confused, the act of pasting an image from the clipboard into R notebooks (markdown) works perfectly, with the extremely helpful option of resizing the images.  Is this issue simply mislabeled as still open?

**Comment by mikebessuille** [comment]
From above comments, this may already work (perhaps for awhile!).   Need to make sure it works in all situations.

**Comment by gtritchie** [comment]
We do support copy/paste images when editing in the new Visual Mode. In the regular mode, pasting an image will typically just insert the filename (at least in the case I tried).

So this issue _could_ be used to track supporting the same in non-visual mode.

**Comment by gtritchie** [comment]
Marking as verified and closing, since this is supported by Visual Editor. If there is a desire for similar functionality in the regular non-visual editor mode, recommend opening as a new feature request.

**Comment by MariaSemple** [comment]
This issue isn't marked as visual editor, and trying it locally, weird things happen when I try and drag-and-drop an image into a markdown document (no visual editor). The IDE reloads and is more zoomed out.

**Comment by gtritchie** [comment]
> This issue isn't marked as visual editor, and trying it locally, weird things happen when I try and drag-and-drop an image into a markdown document (no visual editor). The IDE reloads and is more zoomed out.

True, when this was opened Visual Editor didn't exist yet.

Drag and drop isn't covered by this issue, that's in #4037.
