### ISSUE TITLE
Add git issues pane

### ISSUE THREAD

**Issue by jhollway** [rstudio/rstudio#4042]
I regularly use RStudio to attend to issues raised by users or collaborators on git repositories hosted by Github, Gitlab, or Bitbucket. At the moment, I need to switch back and forth between RStudio and the issues page of the repository website to see which issues I can/should treat next. I'd like to be able to see issues (all, or filtered by tag, assigned to me, etc) in an RStudio pane so that I have a more integrated process. 

A read-only pane may be sufficient as a first step, as I can close/fix/resolve issues with smart commits. Filtering would be a very useful second step. And then ultimately being able to retag, reassign, or create new issues would be very useful extensions.

**Comment by jmcphers** [comment]
This would indeed be very convenient, but this hasn't attracted any attention in over a year and we don't typically invest in deep integration with third party services (we recommend using add-ins, etc. for this kind of thing).
