### ISSUE TITLE
Hotkeys not working as expected on server

### ISSUE THREAD

**Issue by psalveson** [rstudio/rstudio#4043]
### System details

    RStudio Edition : Server
    RStudio Version :  1.2.1194
    OS Version      :  Ubuntu 18.04
    R Version       :  3.5.1

Note that I am accessing RStudio Server using the Chrome browser [Version 71.0.3578.98 (Official Build) (64-bit)] on Windows 10 x64 (all updates) 

### Steps to reproduce the problem
I prefer to have the source pane in another window so I can arrange RStudio like [this](https://filedn.com/l5TNJKkCSE9hEoGrDpVSpBJ/rstudioserverscreen.png). If the focus is on the source pane and  I attempt to switch focus to the the console (which is in a separate window from source) using the default shortcut (ctrl+2), nothing happens. If I am in the console pane and I want to switch to the source pane using the shortcut (ctrl+1), then a new source pane with a new (blank) R file is opened in the same window as the console pane and focus is moved to this new source pane.

### Describe the problem in detail
It appears that the keyboard shortcuts for switching between panes do not work correctly when the panes are in different chrome windows. I have tried changing the default shortcuts, but the problem persists. 

I do not experience this issue when I use desktop RStudio.

### Describe the behavior you expected
When I use a keyboard shortcut to move focus to a particular pane, I expect focus to be moved to that pane.

Thank you,

Peter

**Comment by jmcphers** [comment]
> It appears that the keyboard shortcuts for switching between panes do not work correctly when the panes are in different chrome windows.

This is a known issue, and unfortunately we can't do a lot better than we do today. Web browsers do not generally allow web pages to raise/lower windows and change focus, so there is no way RStudio Server can get the browser to switch focus as you expect. (I'm sure you could imagine the horrors that would be visited upon us by advertisers if they were allowed to do this!) 

The easiest way to get the workflow you want is to use your windowing system's shortcut for cycling through windows owned by the same application. This will usually let you switch between separate windows (source and console) just as easily as Ctrl+1 / Ctrl+2.
