### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [rstudio/rstudio#4044]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [initializeLog](https://github.com/rstudio/rstudio/blob/e6dbc8e405200f97d916f11c93f7a30e46c79300/src/cpp/core/system/Win32System.cpp#L197 "initializeLog function")
- [initializeSystemLog](https://github.com/rstudio/rstudio/blob/e6dbc8e405200f97d916f11c93f7a30e46c79300/src/cpp/core/system/PosixSystem.cpp#L202 "initializeSystemLog function")

**Comment by jmcphers** [comment]
This is a good idea but not currently mandated by our coding standards.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by jmcphers** [comment]
A good idea, but not a project we're going to undertake right now!
