### ISSUE TITLE
cmd + fn + 3 does not open reactlog in shiny apps (v1.2)

### ISSUE THREAD

**Issue by schloerke** [rstudio/rstudio#4045]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1194
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

```r
install.packages("shiny"); 
library(shiny); 
options(shiny.reactlog = TRUE); 
runExample("01_hello")
```

Click a couple times to populate the reactlog. Hit the key combo `CMD + F3` (really `CMD + fn + F3`).  This should open the shiny reactlog.  This works in IDE v1.1.

### Describe the problem in detail

The extra viewer of shiny reactlog is not being displayed after hitting the key combination to open a new viewer.

### Describe the behavior you expected

After hitting the key combo, the extra viewer should be opened.  Either in the browser or RStudio... just somewhere.

It works as expected when the shiny application is in the browser.

**Comment by ronblum** [comment]
Reproduced with RStudio Desktop 1.2.1206-6 on MacOS 10.14.2. This works fine with RStudio Server running on Ubuntu 18.04.1 using Google Chrome on the same Mac. Also, works fine in 1.1.463.

**Comment by kevinushey** [comment]
How does Shiny register the key handler for showing the react log?

**Comment by kevinushey** [comment]
Looks like it's nothing related to that -- it's just RStudio not responding to the `window.open()` request from Shiny.

**Comment by kevinushey** [comment]
Looks like the culprit is this commit: https://github.com/rstudio/rstudio/commit/d31073efb86e0d0a1377871607fc11705fd07de5

RStudio has a workaround that avoids a crash when attempting to open certain kinds of links from the main IDE window; this workaround is 'leaking' into the Shiny window and preventing it from opening windows in the regular way from Javascript.
