### ISSUE TITLE
Projects are not listed while opening project

### ISSUE THREAD

**Issue by pavol-rebros** [rstudio/rstudio#4052]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1
    OS Version      : RHEL Server release 7.2 (Maipo)
    R Version       : 3.2.5

### Steps to reproduce the problem

Menu / File / Open project

### Describe the problem in detail

When clicking "Open Project" the projects are not shown when opening the window.
Every time a series of clicks between "Shared with Me" and "My Projects" needs to be done in order to show the projects.

### Describe the behaviour you expected

List of existing projects appears to choose from.

**Comment by pavol-rebros** [comment]
![rstudioprojectsissue](https://user-images.githubusercontent.com/45941767/50136751-0e9e0680-0299-11e9-88e6-79dc2a84b739.png)

**Comment by jmcphers** [comment]
This issue is fixed in RStudio 1.2. You can try a preview here, if you like:

https://www.rstudio.com/products/rstudio/download/preview/
