### ISSUE TITLE
Rstudio session doesn't start...

### ISSUE THREAD

**Issue by Khkgit** [rstudio/rstudio#4061]
RStudio Edition : Desktop 
    RStudio Version : 1.1.463

    OS Version      : windows7 32bit
    R Version       : 3.5.1

   **Rstudio crashes unexpectedly.....****
   When I try to open Rstudio, it crashes enexpectedly.
   Don't know the reason..
   
**![rstudio](https://user-images.githubusercontent.com/45990561/50206769-72f0c100-0392-11e9-8ecd-d122ec74c81f.JPG)**

**Comment by jmcphers** [comment]
Can you include a diagnostics report?

Can you confirm that you're using the 32 bit version of R? (Hold down Ctrl while launching to pick your R binary.)

**Comment by Khkgit** [comment]
I'm using 32 bit version of windows 7.
BY holding Ctlr Key also ,Im not able to start Rstudio session...session doesn't start.
It is showing the blank screen...
![capture1](https://user-images.githubusercontent.com/45990561/50272218-0db5d200-045d-11e9-932c-64f575c89485.JPG)

**Comment by jmcphers** [comment]
Sorry, without a diagnostic report or other system information we can't make any progress on this one. Please open a new issue and include a diagnostic report if you're still having this issue.
