### ISSUE TITLE
R Markdown deletes multiple lines when pressing backspace

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/rstudio#4064]
Pressing backspace in an R Markdown document sometimes deletes 2 lines. I've restarted R Studio and my computer. 

This issue has been reported in the R Markdown repo https://github.com/rstudio/rmarkdown/issues/1031.

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 bookdown_0.7    rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.1    
 [7] yaml_2.2.0      Rcpp_1.0.0      rmarkdown_1.10  knitr_1.20      xfun_0.4        digest_0.6.18  
[13] evaluate_0.12  
```
I am running into this problem on  a mid 2015 macbook pro.

**Comment by GegznaV** [comment]
I can confirm a similar issue on Windows, just in my case exactly one row and one character were deleted instead of just one character.

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)
RStudio: 1.2.1194 (desktop)
```
Red line indicates cursor's possition before pressing backspace:
![image](https://user-images.githubusercontent.com/12725868/50312902-78ddc380-04b2-11e9-9098-c2e6eb014f44.png)

After pressing backspace:
![image](https://user-images.githubusercontent.com/12725868/50313244-5c8e5680-04b3-11e9-9015-b1ee48349585.png)


After redoing the deletion (<kbd>Ctrl</kbd>+<kbd>z</kbd>), the previously deleted characters get selected:
![image](https://user-images.githubusercontent.com/12725868/50313083-f99cbf80-04b2-11e9-8bfa-8fe2e10a5001.png)

The text I used:

```
Pirmieji du komponentai paaiškina apie 83% duomenų dispersijos.
Iš *biplot* grafiko aiškiai nesimato, kad kažkuris požymis būtų ypatingai reikšmingas.
Galima įžvelgti, kad žuvo labai maži (žiūrėkite į kintamąjį `tot_length`, paukščio dydis, reprezentuojančią rodyklę) ir labai dideli paukščiai. Taip pat, kad `tot_length`, `alar_length`, `beak_head_length` ir
```

**Comment by GegznaV** [comment]
I noticed that the deleted text is in the same row 104 which is wrapped.

**Comment by ronblum** [comment]
@JosiahParry Thank you for copying over the issue!

**Comment by kevinushey** [comment]
I'm unfortunately not able to reproduce. Other information that might be helpful:

- What is the default system locale? Is it something other than English?
- Is there any other text in the document before those 3 lines you shared?
- What is the default locale on your system?
- What keyboard layout are you using?
- Does it depend on how you move the cursor? E.g. if you click on the appropriate location vs. moving the caret with the arrow keys or similar.

**Comment by GegznaV** [comment]
Unfortunately, I cannot reproduce the problem using the same example anymore.
At that moment I was working on a document inside a `Bookdown` project.

>What is the default system locale? Is it something other than English?
> What is the default locale on your system?
> What keyboard layout are you using?
![image](https://user-images.githubusercontent.com/12725868/50939094-14e06680-1484-11e9-8b8b-eb14481f7420.png)

I use both English and Lithuanian keyboard layouts (are more details needed?)

> Is there any other text in the document before those 3 lines you shared?

Yes. There was more text and before, and after. Unfortunately, I do not have the exact version of it.

> Does it depend on how you move the cursor? E.g., if you click on the appropriate location vs. moving the caret with the arrow keys or similar.

It depended on the text in other places in the document. At that moment I copied the most minimal example in which the problem existed. Most probably, there were more things.

I think, the side of RStudio window also matters, as exactly one row and one symbol were deleted.

**Comment by ctgrubb** [comment]
I just experienced this issue. I run Ubuntu 16.04, and I was also editing a R Markdown file. I noticed some additional strange behavior, in addition to the exact behavior that GegznaV experienced. When I am inside of the wrapped line of text that is displaying this strange behavior, the up arrow will take me up to the next line up (even if there is another "line" of text that is part of the same line that is should go up to). The down arrow will completely not function, and does not move the cursor at all, despite not only having lines of wrapped text below the cursor, but also other lines of text as well.

Restarting Rstudio did not fix this issue, so I saved a version of the file in this state. Then I tried deleting the entire paragraph that is experiencing this issue, and Rstudio was still acting very strange. Specifically, the up arrow was skipping line 195 when I hit up from line 196 (all lines were blank). The up arrow worked just fine from other lines of text, for some reason line 195 just was getting skipped (this was the same line that experienced the issue originally, but it was now blank).

What actually fixed this issue and stopped it from happening was closing all of the image chunks that appear under code chunks when you run a chunk of code in R Markdown. Those image chunks were getting saved with the file, so closing Rstudio and reloading did not fix anything. I went back to the original broken file, and closed the images there as well, and the problem also resolved itself in that file as well.

When I recreated those same images by running the exact same code again, the problem did not reappear.

**Comment by kevinushey** [comment]
Just to be clear, reproducing this issue appears to require wrapped text as well as an inline image displaying within an R Markdown file?

**Comment by ctgrubb** [comment]
I believe so, but I was unable to reproduce the issue since deleting the original offending inline image. I haven't experienced the same issue since, though I did speak with numerous other students/faculty at my university that claimed to have experienced the same issue. None of them went as deep as I did with trying to figure out what exactly caused it though, so they didn't have any info to add.

**Comment by solartex** [comment]
I am having exactly the same issue on : 

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

It happened on Rmarkdown in a very comparable way to @GegznaV . Normal line : 

![Capture d’écran 2019-04-18 à 11 09 38](https://user-images.githubusercontent.com/49749166/56350193-812cdd80-61ca-11e9-9493-4239f952bc64.png)

Clicking backspace cause to delete the whole line : 

![Capture d’écran 2019-04-18 à 11 10 35](https://user-images.githubusercontent.com/49749166/56350281-ac173180-61ca-11e9-874e-88aab960cd5b.png)

and cmd+z to restaure the whole : 

![Capture d’écran 2019-04-18 à 11 11 41](https://user-images.githubusercontent.com/49749166/56350307-c3eeb580-61ca-11e9-8fd4-6c10feb50a2e.png)


Neither restarting the IDE nor restarting the computer helped... If anyone got an idea...

**Comment by kevinushey** [comment]
If you could share the document in which this issue is reproducible, that would be helpful.

**Comment by JosiahParry** [comment]
Just encountered this issue again. A work around was to copy the text over to a new .Rmd file. I took a short [screen recording](https://drive.google.com/open?id=1inEnhQPo-pTFNzCVTwdD7GHLgB20spKC) of the issue. The .Rmd file that I'm using is [here](https://drive.google.com/file/d/1MKWRJFF3d5ktACUneX6nQ-ZtSwERmyLF/view)

**Comment by jbintz** [comment]
Encountering the same issue. I use a 2017 MacBook Pro.

**Comment by antaldaniel** [comment]
I have this issue on an English (default), multi-language Windows 10, and had it on a previous similar system.  Frankly, I have no idea what triggers this state, and cannot think about reproducing it.  In some cases, closing the system, and rebooting the system makes it go away, in some cases not. 

The problem seems to be specific to some hidden character or key combination.  In my recent instance, in the same text, I have a paragraph where the backspace is working as expected, then a paragraph where it is not, and then a new paragraph where again, it works as it should.

If it helps, I can send an Rmd file where I saved this problem.  Maybe opening in a different sytem or with a different software shows something irregular in the paragraph where the text behavior is unexpected.  It appears as a part of the paragraph was treated as a single character.

**Comment by kevinushey** [comment]
Do you see this issue in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)? We fixed a similar issue recently, with https://github.com/rstudio/rstudio/commit/4e2e7a8acf1c84b114668a22a4a4bd31c62e8649.

**Comment by ries9112** [comment]
I am still running into this issue on RStudio 1.2.5033 and R 3.6.2

Here's a screenshot with some information about my computer:
![image](https://user-images.githubusercontent.com/32306488/73779227-a5ea4580-4749-11ea-81b8-2ab9fc493ffa.png)

Not really sure what information to provide here, let me know what other information may be useful and I can send it over.

Also let me know if this is the wrong place to be adding to this issue, there is a more recent issue from 27 days ago, but it's around Ubuntu specifically so I added to this one instead.

**Comment by kevinushey** [comment]
Thanks, but unfortunately the only thing that will help us make progress here is a reproducible example.

**Comment by ries9112** [comment]
I can't reproduce it, it doesn't seem to consistently be a problem that has been coming and going for about 6 months on my computer and it seems to be pretty rare, no clue what triggers it. I don't think my document would help here at all and it uses a private db connection throughout so it would be really tough to make a reprex and I don't think you would be able to recreate the issue. I can't re-create the issue after downloading the preview release version of 1.3.776 using the exact same document and doing exactly what I was just doing.

**Comment by JosiahParry** [comment]
Just encountered this yet again. I don't think there is a way to reproduce the issue. The only thing different that occurred in this session than other Rmd files in recent past is that I've updated packages in use while editing the Rmarkdown. The funny thing is that it doesn't appear to be the text itself. You can copy the Rmd line by line to a new one (my unfortunate work around) and the problem entirely disappears—I diffed to check that there weren't any sneaky characters. 

This feels like ghost hunting. 

sessionInfo fwiw:
RStudio Version 1.2.5001
macOS Mojave 10.14.6
MacBook Pro 15-inch, 2017

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.3   tibble_2.1.3  ggplot2_3.2.1

loaded via a namespace (and not attached):
 [1] tidyselect_1.0.0  xfun_0.10         remotes_2.1.0     purrr_0.3.3      
 [5] testthat_2.3.0    colorspace_1.4-1  vctrs_0.2.2       usethis_1.5.1    
 [9] htmltools_0.4.0   yaml_2.2.0        utf8_1.1.4        rlang_0.4.4      
[13] pkgbuild_1.0.6    pillar_1.4.3      later_1.0.0       glue_1.3.1       
[17] withr_2.1.2       rsthemes_0.0.5    sessioninfo_1.1.1 lifecycle_0.1.0  
[21] stringr_1.4.0     munsell_0.5.0     gtable_0.3.0      devtools_2.2.1   
[25] evaluate_0.14     memoise_1.1.0     knitr_1.25        callr_3.3.2      
[29] httpuv_1.5.2      ps_1.3.0          curl_4.3          fansi_0.4.1      
[33] Rcpp_1.0.3        scales_1.1.0      promises_1.1.0    backports_1.1.4  
[37] desc_1.2.0        pkgload_1.0.2     jsonlite_1.6      fs_1.3.1         
[41] mime_0.7          servr_0.15        packrat_0.5.0     digest_0.6.24    
[45] stringi_1.4.5     bookdown_0.17     processx_3.4.1    grid_3.6.1       
[49] rprojroot_1.3-2   cli_2.0.1         tools_3.6.1       magrittr_1.5     
[53] lazyeval_0.2.2    crayon_1.3.4      pkgconfig_2.0.3   ellipsis_0.3.0   
[57] rsconnect_0.8.15  prettyunits_1.1.1 assertthat_0.2.1  rmarkdown_1.16   
[61] rstudioapi_0.11   R6_2.4.1          compiler_3.6.1   
```

**Comment by kevinushey** [comment]
Just to re-iterate, the thing that would help us most here would be a reproducible example. Thus far it seems like the main required element is that:

1. An R Markdown document is open in the editor;
2. The user is editing one or more lines that are wrapped.

Another thing that could be useful -- next time you observe this issue, try right clicking somewhere in the IDE surface, and clicking Inspect Element. This will open an RStudio Devtools window. Click the console tab. Are any errors emitted in the console?

Finally, it might be worth trying the v1.3 [preview release](https://www.rstudio.com/products/rstudio/download/preview/), to see if the error reproduces there.

**Comment by parkerholzer** [comment]
The easiest fix that I've found is to close any plots or tables printed below the code chunks in the .Rmd file that you are editing. They don't all need to be closed for this to be fixed though. I guess you just need to not have too many plots and tables shown at the same time as previews.

**Comment by sklayn** [comment]
I also just encountered this; I haven't seen it before. In my case, it's only one particular wrapped line in the Rmd file, and it happens when the wrapped part becomes 3 "lines" or longer.
This is the only place in the file that this occurs - I have other, longer blocks of text before and after with no such issues.
Copying the entire contents of the file to a new Rmd file fixes it for me.  

> Another thing that could be useful -- next time you observe this issue, try right clicking somewhere in the IDE surface, and clicking Inspect Element. This will open an RStudio Devtools window. Click the console tab. Are any errors emitted in the console?

Tried this, and there are no errors in the console. 

I'm using RStudio v.1.2.5033 on Linux Mint 19. 
Session info: 
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C            LC_TIME=en_US.UTF-8     LC_COLLATE=en_US.UTF-8 
 [5] LC_MONETARY=bg_BG       LC_MESSAGES=en_US.UTF-8 LC_PAPER=bg_BG          LC_NAME=C              
 [9] LC_ADDRESS=C            LC_TELEPHONE=C          LC_MEASUREMENT=bg_BG    LC_IDENTIFICATION=C    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] viridis_0.5.1     viridisLite_0.3.0 unpivotr_0.5.1    tidyxl_1.0.4      readxl_1.3.1     
 [6] forcats_0.5.0     stringr_1.4.0     dplyr_0.8.5       purrr_0.3.3       readr_1.3.1      
[11] tidyr_1.0.2       tibble_2.1.3      ggplot2_3.3.0     tidyverse_1.3.0   here_0.1         

loaded via a namespace (and not attached):
 [1] tidyselect_1.0.0 xfun_0.12        janitor_1.2.1    haven_2.2.0      lattice_0.20-40 
 [6] colorspace_1.4-1 vctrs_0.2.4      generics_0.0.2   htmltools_0.4.0  base64enc_0.1-3 
[11] yaml_2.2.1       rlang_0.4.5      pillar_1.4.3     glue_1.3.2       withr_2.1.2     
[16] DBI_1.1.0        dbplyr_1.4.2     modelr_0.1.6     lifecycle_0.2.0  munsell_0.5.0   
[21] gtable_0.3.0     cellranger_1.1.0 rvest_0.3.5      evaluate_0.14    knitr_1.28      
[26] fansi_0.4.1      broom_0.5.5      Rcpp_1.0.4       scales_1.1.0     backports_1.1.5 
[31] jsonlite_1.6.1   fs_1.3.2         gridExtra_2.3    digest_0.6.25    hms_0.5.3       
[36] packrat_0.5.0    stringi_1.4.6    grid_3.6.3       rprojroot_1.3-2  cli_2.0.2       
[41] tools_3.6.3      magrittr_1.5     crayon_1.3.4     pkgconfig_2.0.3  xml2_1.2.5      
[46] reprex_0.3.0     lubridate_1.7.4  rmarkdown_2.1    assertthat_0.2.1 httr_1.4.1      
[51] rstudioapi_0.11  R6_2.4.1         nlme_3.1-145     compiler_3.6.3  
```

**Comment by MauroCE** [comment]
I have the same problem, it happens quite often actually. Possibly has to do with some keyboard combination pressed by accident? I restarted R completely and didn't solve the problem. Here is my R studio session info.

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=it_IT.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    packrat_0.5.0 
```


# Solution
The solution for me was to do what somebody said above: close all the little images in the Rmarkdown that appear under equations or plots.

**Comment by alextolkin** [comment]
I just had the exact same issue - markdown document with word wrap. Restarting R did not help, but removing the preview images under my tables resolved the problem.

I have not been able to reproduce though, even after running code chunks to generate the previews again.

**Comment by meur2019** [comment]
Having the same issue as everyone else. Running Windows 10 Version 10.0.17134 Build 17134. While the text Is unhighlighted, as soon as I backspace a character, the entre line and line above it are deleted. Attempted to restart but the issue actually became worse, deleting more characters. 

However, the fix of closing all inserted .png's has resolved the issue.

**Comment by JosiahParry** [comment]
I haven't seen this issue in a while. Perhaps accidentally solved in v1.3 or 1.4

**Comment by icaruso21** [comment]
@JosiahParry I don't believe it has been solved as I just had the same issue on mac-os.

**Comment by JosiahParry** [comment]
@icaruso21 I've not had the issue for quite some time now. Have you updated to 1.4?

**Comment by icaruso21** [comment]
@JosiahParry I have 1.2.5, I'll try updating now. Many thanks!
