### ISSUE TITLE
Cannot preview file in browser when directory contains +

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#4065]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1189
    OS Version      : Ubuntu 16.04
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create and open an R project in a folder
2. Create a subfolder whose name contains `+` (e.g. `a+b`)
3. Product a pdf plot in the subfolder (e.g. `pdf("a+b/test.pdf"); plot(rnorm(100)); dev.off()`)
4. Click the subfolder and then the pdf file in the Files pane in RStudio Server.
5. A new webpage pops out and says 

> /files/project-folder/a+b/test.pdf not found

I'm not sure if this happens with other characters that are valid in file names. I tested with dots (`a.b/test.pdf`) and it works perfectly. It looks like an URL encoding problem. 

A folder can be named like this by formatting numeric values such as `test_20181220_0.01_1e+08`. Therefore it would be nice to get this fixed so that it works as long as the path is valid for filesystem.

**Comment by ronblum** [comment]
Reproduced with RStudio Server on Ubuntu 18.04 and Red Hat 7.5. Not an issue with RStudio Desktop on MacOS 10.14.2 Mojave.

This seems to be an issue with any file opened externally. For example, knit an Rmd file to HTML or PDF. The newly-rendered file will pop up correctly. However, then clicking on the file in the Files pane will result in the error above. (For HTML, choose "View in Web Browser" as the files open fine in the Editor.)

**Comment by kevinushey** [comment]
@ronblum for completeness, which browsers did this issue reproduce in?

**Comment by renkun-ken** [comment]
I'm using Firefox 64.
