### ISSUE TITLE
Error creating notebook: pandoc document conversion failed with error 11

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#4072]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1206
    OS Version      : Windows 10 Pro
    R Version       : 3.5.1

### Steps to reproduce the problem
- Save a Rmd notebook

### Describe the problem in detail
Since you update to pandoc 2.5 64bit I'm getting this error again, is exactly the same error of this closed issue #3661 

``` 
Access violation in generated code when executing data at 0x49f9259

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x561daf0	0x49f9259 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f9259
 * 0x561daf8	0x7ffc358300f0 C:\WINDOWS\System32\IMM32.DLL+0xf0
 * 0x561db00	0x561de60
 * 0x561db70	0x7ffc35afbaa1 C:\WINDOWS\SYSTEM32\ntdll.dll+0x3baa1
 * 0x561db78	0x7974b61
 * 0x561db80	0x1
 * 0x561db88	0x43
 * 0x561db90	0x79513d0
 * 0x561db98	0x33
 * 0x561dba0	0x7977318
 * 0x561dba8	0x79eda49
 * 0x561dbb0	0x79d70d0
 * 0x561dbb8	0x79d70ea
 * 0x561dbc0	0x7bc5220
 * 0x561dbc8	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dbd0	0x40e5b88 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3ce5b88
 * 0x561dbd8	0x7929670
 * 0x561dbe0	0x7929639
 * 0x561dbe8	0x488920a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448920a
 * 0x561dbf0	0x488920a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448920a
 * 0x561dbf8	0x40e5b68 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3ce5b68
 * 0x561dc00	0x488920a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448920a
 * 0x561dc08	0x79297b8
 * 0x561dc10	0x7925fbb
 * 0x561dc18	0x79122a0
 * 0x561dc20	0x79122b8
 * 0x561dc28	0x79122d0
 * 0x561dc30	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc38	0x40d800a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3cd800a
 * 0x561dc40	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc48	0x4904359 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x4504359
 * 0x561dc50	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc58	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc60	0x40536d3 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3c536d3
 * 0x561dc68	0x4126b69 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3d26b69

   ... (maximum recursion depth reached.) 
```

### Describe the behavior you expected

I spect to get a html preview when I save the file

**Comment by jmcphers** [comment]
Unfortunately, the 32-bit version of Pandoc 2.5 on Windows has a hanging issue, which is why we switched to the 64-bit version (see https://github.com/rstudio/rstudio/issues/3965). It seems like we may need to choose between these two, until a fix is made upstream on Pandoc's end, or we can find a suitable workaround.

Are you able to extract the Markdown content being sent to pandoc for your notebook? (we can help with this if needed.) If so, you could re-open this Pandoc issue with your repo:

https://github.com/jgm/pandoc/issues/5037

**Comment by andresrcs** [comment]
I don't know how to do that, but I can share a small Rmd file that triggers the error in my system, have in mind that, like the last one, this error also happens randomly.

[test.zip](https://github.com/rstudio/rstudio/files/2701008/test.zip)

**Comment by helix123** [comment]
I also get this. In my vignette it is in the part where the `texreg` package is loaded.

```
Error in re-building vignettes:
  ...
Version:  1.36.23
Date:     2017-03-03
Author:   Philip Leifeld (University of Glasgow)

Please cite the JSS article in your publications -- see citation("texreg").
Loading required package: Formula

Access violation in generated code when executing data at 0x49f92a9

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x22daf0	0x49f92a9 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f92a9
 * 0x22daf8	0x8c000101

...
pandoc document conversion failed with error 11
```

**Comment by rensa** [comment]
Also intermittently (only _occasionally_) getting similar errors when working with a notebook on RStudio 1.2.1206 on Windows 10 1809. When saving a notebook, I'll occasionally get in the console:

    Access violation in generated code when reading 0x9157f00
    
     Attempting to reconstruct a stack trace...
    
       Frame	Code address
     * 0x561dac0	0x4018450 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3c18450

Will try to create a repro! (Difficult with my current notebook due to the data I'm working with, but I'll see if I can come up with something synthetic.)

**Comment by helix123** [comment]
For some vignettes the error seems to be reproducible every time and for some it errors (seemingly) at random.

**Comment by kevinushey** [comment]
Given that you're evidently running into a bug in the Haskell runtime / compiler itself our only hope is likely to wait for a new Pandoc release built with a newer version of GHC.

**Comment by andresrcs** [comment]
I have installed latest build `1.0.3317` on this path `C:\Program Files\RStudio\bin\pandoc` but I still have the same problem.
![image](https://user-images.githubusercontent.com/14981085/50808737-ee78ca80-12cd-11e9-9ce5-7681dcde10ea.png)
I dont think the content of the .rmd file is what triggers the error because this really basic .md file does it.
[test_md.zip](https://github.com/rstudio/rstudio/files/2735151/test_md.zip)

````
---
title: "R Notebook"
output: 
  html_document: 
    keep_md: yes
---


```r
library(ggplot2)
library(extrafont)
loadfonts(device = "win")
ggplot(cars, aes(speed, dist)) +
    geom_line() +
    geom_smooth(method = 'lm')
```

![](test_files/figure-html/unnamed-chunk-1-1.png)<!-- -->
````

**Comment by kevinushey** [comment]
Can you copy + paste the Pandoc invocation used by RStudio when rendering the document? E.g. I see:

```
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output test.html --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\kevin\R\win-library\3.5\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable "theme:bootstrap" --include-in-header "C:\Users\kevin\AppData\Local\Temp\Rtmp8wvsGn\rmarkdown-str1d34b657d1f.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
```

**Comment by andresrcs** [comment]
I see this
```
==> rmarkdown::render('C:/Users/andre/Documents/R/test.Rmd',  encoding = 'UTF-8');


processing file: test.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1 (with options) 
List of 1
 $ message: logi FALSE


"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output test.html --email-obfuscation none --self-contained --standalone --section-divs --template "C:\PROGRA~1\R\R-35~1.2\library\RMARKD~1\rmd\h\DEFAUL~1.HTM" --no-highlight --variable highlightjs=1 --variable "theme:bootstrap" --include-in-header "C:\Users\andre\AppData\Local\Temp\RtmpsnOD8t\rmarkdown-str2b1043c06830.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
output file: test.knit.md


Output created: test.html
```

**Comment by kevinushey** [comment]
But that run succeeded. Are you saying that this specific invocation sometimes does not work?

**Comment by kevinushey** [comment]
Also worth saying that `IMM32.dll` is apparently a DLL used by Windows for input method management, so it's surprising to see it on the call stack in your crash. Do you have one or more custom input methods installed on your machine? How are they set up?

Where is this `IMM32.dll` installed on your machine? (You can use a program like [Everything](https://www.voidtools.com/) to quickly search the entire filesystem for a file by name)

**Comment by rensa** [comment]
To be fair, @kevinushey, this would match my experience: the errors I've seen aren't just intermittent to the _content_ I try to knit, they also appear intermittently even with the same content. Whenever I've hit it, often just hitting Knit again immediately causes everything to work.

**Comment by andresrcs** [comment]
Yes, most of the time works, but sometimes troughs an error in console.

**Comment by andresrcs** [comment]
About the custom input methods, I'm not sure because I have never configured one manually, but maybe it has some because my machine is a "surface pro" (laptop tablet hybrid) and uses on screen touch keyboard as well as a fisical type cover keyboard.

**Comment by kevinushey** [comment]
Interesting. It's _possible_ that's somehow related (weirder things have happened in software) but since I've only tested on desktop machines perhaps that's why I haven't seen it.

**Comment by kevinushey** [comment]
Still can't reproduce on an in-house Yoga 2 Pro laptop (which can also function as a tablet, similar to the Surface laptops -- of course, it's not a Surface though)

That said, I _still_ don't have a full minimally reproducible example. The example you shared references a figure that I don't have, and it's entirely possible that the repro depends on some quality of the image used (e.g. the size, resolution, and so on)

Please share a self-contained R Markdown document that, when rendered, reproduces the issue. Preferably as something I can easily copy + paste to reproduce.

**Comment by kevinushey** [comment]
Is your Windows display language in English? (Are the native UI menu items using English or a different language for the labels?)

**Comment by andresrcs** [comment]
This is the whole content of the .Rmd file, its just a minimal reprex, but at least in my case, if I run + save the files enough times, the error happens regardless of the content of the files.

````
---
title: "R Notebook"
output: html_document
---

```{r, message=FALSE}

library(ggplot2)
ggplot(cars, aes(speed, dist)) +
    geom_line() +
    geom_smooth(method = 'lm')
```
````
[test.zip](https://github.com/rstudio/rstudio/files/2738209/test.zip)

**Comment by andresrcs** [comment]
Also my windows installation is in Spanish-latin america but I use both input methods, Spanish and English  since my keyboard layout is in English.

**Comment by kevinushey** [comment]
Thanks. Still no luck reproducing on my desktop machine nor our in-house laptop...

**Comment by egorananyev** [comment]
In my case, I get a virtually identical issue as @andresrcs when I am trying to selectively convert NA in a data set to zeros in a .Rmd document I'm trying to knitr.

My case is very similar to @imanuelcostigan's post in #3661 that he got this issue with 'select'. The knitting took a long time but completed consistently before I introduced a line similar to the following:
dataset$var[is.na(dataset$var)] = 0

After that, no attempts to knitr the same code were successful. I tried about 10 times.

> RStudio Edition : Desktop
> RStudio Version 1.2.1229
> OS Version: Windows 10 64x
> R Version: 3.5.1

**Comment by kevinushey** [comment]
@egorananyev A reproducible example would be helpful (something I can try to run on my machine to see if I can reproduce locally)

**Comment by rensa** [comment]
Sorry for my lack of reply on this issue; it turns out I'd foolishly installed Pandoc via Chocolatey quite a while ago, and despite removing that version, it's continuing to pollute my path:

> Warning messages:
1: In system(paste(shQuote(pandoc_path), "--version"), intern = TRUE) :
  running command '"C:/PROGRA~3/CHOCOL~1/bin/pandoc.exe" --version' had status 65535
2: In system(paste(shQuote(pandoc_path), "--version"), intern = TRUE) :
  running command '"C:/PROGRA~3/CHOCOL~1/bin/pandoc.exe" --version' had status 65535

I'll circle 'round once I'm rid of it!

That said, I should mention that I also have two keyboard layouts, [despite my best efforts to get rid of one of them](https://discussions.agilebits.com/discussion/95521/show-1password-mini-shortcut-ctrl-alt-doesnt-always-work#Comment_460541).

**Comment by dpprdan** [comment]
I've had similar issues like the one mentioned here. The following Rmd reproducibly gives an error for me with RStudio v1.2.1256-3, the current preview version.

````r
---
title: "HTML Document"
output: 
  html_document: 
    self_contained: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# "Apparently need a pound sign and a double quote to fail"

knitr::kable(iris)

library(ggplot2)
library(extrafont)
loadfonts(device = "win")
ggplot(cars, aes(speed, dist)) +
    geom_line() +
    geom_smooth(method = 'lm')

```

````

All parts are crucial here, even the comment with the double quotes. If I set `self_contained` to  `FALSE` the document is rendered successfully (`TRUE` is the default). If I add `keep_md: TRUE` the document is rendered successfully. If I remove the `self_contained` line (and leave `keep_md: TRUE` in), I get an error. 

The otherwise same file with this header

```yaml
---
title: "HTML Document"
output: 
  html_document: 
    df_print: paged
---
``` 

renders fine, but all other `df_print` options throw an error. 

Anyway, this is the error, I usually get:

```
Access violation in generated code when reading 0x8a7b7b0

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x561daf0	0x4018450 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3c18450
 * 0x561daf8	0x7ff8f4aa00f0 C:\WINDOWS\System32\IMM32.DLL+0xf0
 * 0x561db00	0x561de60
 * 0x561db70	0x7ff8f75abaa1 C:\WINDOWS\SYSTEM32\ntdll.dll+0x3baa1
 * 0x561db78	0x79ebd79
 * 0x561db80	0x1
 * 0x561db88	0x52
 * 0x561db90	0x790ec40
 * 0x561db98	0x4c
 * 0x561dba0	0x7998288
 * 0x561dba8	0x7997359
 * 0x561dbb0	0x49f8691 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8691
 * 0x561dbb8	0x488920a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448920a
 * 0x561dbc0	0x488b332 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448b332
 * 0x561dbc8	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dbd0	0x40e5b88 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3ce5b88
 * 0x561dbd8	0x798ce60
 * 0x561dbe0	0x798ce29
 * 0x561dbe8	0x488920a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448920a
 * 0x561dbf0	0x488920a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448920a
 * 0x561dbf8	0x40e5b68 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3ce5b68
 * 0x561dc00	0x488920a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x448920a
 * 0x561dc08	0x798d128
 * 0x561dc10	0x79873b3
 * 0x561dc18	0x79fa2a0
 * 0x561dc20	0x79fa2b8
 * 0x561dc28	0x79fa2d0
 * 0x561dc30	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc38	0x40d800a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3cd800a
 * 0x561dc40	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc48	0x4904359 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x4504359
 * 0x561dc50	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc58	0x49f8661 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f8661
 * 0x561dc60	0x40536d3 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3c536d3
 * 0x561dc68	0x4126b69 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3d26b69

   ... (maximum recursion depth reached.)

Error: pandoc document conversion failed with error 11
```

I've also gotten this error, however, I cannot vouch for the reprex having been exactly the same as the one above.

```
pandoc.exe: internal error: evacuate: strange closure type 129194914
    (GHC version 8.6.1 for x86_64_unknown_mingw32)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
Error: pandoc document conversion failed with error 3
```

The pandoc conversion is called like this

```
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output test.html --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\daniel\Documents\.R\win-library\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable "theme:bootstrap" --include-in-header "C:\Temp\R\RtmpExX75B\rmarkdown-str63cc143612de.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
```

**Comment by jmcphers** [comment]
@dpprdan Thanks so much for the thorough repro steps. Unfortunately even with the document you have above (and an identical pandoc conversion command), I can't reproduce the crash. I think there's probably some other condition to which this issue is sensitive. 

Glad to see that it almost certainly doesn't reproduce in 2.6 -- we will plan to upgrade to 2.6 when it has a non-provisional release.

**Comment by dpprdan** [comment]
I've tried to reproduce my own example on my laptop at home and it did not. However, I get an error with the same document body and this yaml:

```yaml
---
title: "HTML Document"
output: 
  html_document: 
    self_contained: TRUE
    keep_md: TRUE
    df_print: paged
---
```

FWIW I think I have never gotten an error in all my tests with `self_contained: FALSE`.

@jmcphers 
> Glad to see that it almost certainly doesn't reproduce in 2.6 -- we will plan to upgrade to 2.6 when it has a non-provisional release.

"Almost" being the operative word here 😉 , see https://github.com/jgm/pandoc/issues/5037#issuecomment-459322394

**Comment by dpprdan** [comment]
Pandoc v2.6 does not yet fix this. A slightly modified example still gives me an error. This is with the v1.2.1275 daily. See https://github.com/jgm/pandoc/issues/5037 for the issue in pandoc.

<details>

````r
---
title: "HTML Document"
output: 
  html_document: 
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# "Apparently need a pound sign and a double quote to fail"

DT::datatable(iris)

library(ggplot2)
library(extrafont)
loadfonts(device = "win")
ggplot(cars, aes(speed, dist)) +
    geom_line() +
    geom_smooth(method = 'lm')

# print('Hello World')

```
````

```
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output test.html --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\daniel\Documents\.R\win-library\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable "theme:bootstrap" --include-in-header "C:\Temp\R\RtmpUN8J53\rmarkdown-str472835a23931.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
output file: test.knit.md


Access violation in generated code when executing data at 0x8a6b381

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x57adaf0	0x8a6b381
 * 0x57adaf8	0x7ff8f4aa00f0 C:\WINDOWS\System32\IMM32.DLL+0xf0
 * 0x57adb00	0x57ade60
 * 0x57adb70	0x7ff8f75abaa1 C:\WINDOWS\SYSTEM32\ntdll.dll+0x3baa1
 * 0x57adb78	0x7d6ac79
 * 0x57adb80	0x1
 * 0x57adb88	0x4b
 * 0x57adb90	0x7b5b0c0
 * 0x57adb98	0x49
 * 0x57adba0	0x7b46340
 * 0x57adba8	0x7b45359
 * 0x57adbb0	0x4b61721 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x4761721
 * 0x57adbb8	0x49f2be2 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f2be2
 * 0x57adbc0	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adbc8	0x423fbc8 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e3fbc8
 * 0x57adbd0	0x7b39540
 * 0x57adbd8	0x7b39509
 * 0x57adbe0	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adbe8	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adbf0	0x423fba8 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e3fba8
 * 0x57adbf8	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adc00	0x7b39680
 * 0x57adc08	0x7b32edb
 * 0x57adc10	0x7cd6020
 * 0x57adc18	0x7cd32a0
 * 0x57adc20	0x7cd32b8
 * 0x57adc28	0x7cd32d0
 * 0x57adc30	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc38	0x4231e2a C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e31e2a
 * 0x57adc40	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc48	0x4a6d3e9 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x466d3e9
 * 0x57adc50	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc58	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adc60	0x41a98d3 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3da98d3
 * 0x57adc68	0x4280a19 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e80a19

   ... (maximum recursion depth reached.)

Error: pandoc document conversion failed with error 11
```

```
"C:/Program Files/RStudio/bin/pandoc/pandoc" --version
pandoc.exe 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5
Default user data directory: C:\Users\daniel\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

</details>

**Comment by mofferpoffer** [comment]
I have the same problem with Pandoc v2.6. I noticed two things:
- if I rerun the same pandoc command generated by rmarkdown using my default windows pandoc (v2.6 as well), it works just fine.
- if I remove the setting "--email-obfuscation none" in the rmarkdown generated pandoc command, it works as well

**Comment by aphalo** [comment]
Could this error be indirectly triggered by a file-access problem?
The User Guide of 'ggpmisc' (user-guide.Rmd) consistently triggers the same Pandoc Error 11 and the access violation, but very occasionally I receive instead locked file error for user-guide.R
Further more, if I delete user-guide.R before the rebuilding documentation, knitting seems to consistently succeed and if I do not delete it, it seems to consistently fail.

@mofferpoffer @dpprdan Could you please check if you can see any connection in the apparent randomness of the errors you see to the presence or not of the .R file from the previous knitting?

I am on Windows 10 Academic in a laptop with FI, UK and ESP keyboard layouts installed.

**Comment by aphalo** [comment]
I have three keyboard layouts installed: Finnish, United Kingdom, and Latin American. I normally use the Finnish layout. Only when using Build > Documentation, the error disappears if I switch to the UK or the LA (Spanish) keyboard layouts. Furthermore in both cases Build > Documentation succeeds even after switching back to the FI layout. If I close and restart RStudio the problem reappears until I switch back to the UK layout for at least one build of the documentation.
(The Finnish layout is the same as the Swedish layout.)

In contrast, Build > Check, Build > Build Source Package, and building the vignette in Pkgdown always fail irrespective of the keyboard layout that is active.
 
I can also confirm that setting `self_contained: FALSE` solves the problem in all these cases.

Hopefully this helps shed some light on this problem.

I am on Windows 10 Academic in a laptop with FI, UK and ESP keyboard layouts installed. RStudio 1.2.1326.

**Comment by kevinushey** [comment]
I've put together a version of Pandoc 2.7.1 built with the latest version of GHC (8.6.4). You can download and test it by running this R script. The script will download and unpack Pandoc at `~/rstudio-pandoc`, and then write a `~/.Renviron` file that will instruct R / RStudio to use this version of Pandoc at runtime.

```r

# Download pandoc 2.7.1 built with ghc-8.6.4, and instruct
# RStudio + rmarkdown to use it.

local({
	
	# The directory where Pandoc will be extracted. Feel free
	# to adjust this path as appropriate.
	dir <- "~/rstudio-pandoc"
	
	# The version of Pandoc to be installed.
	version <- "2.7.1"
	
	# Create and move to the requested directory.
	dir.create(dir, showWarnings = FALSE, recursive = TRUE)
	owd <- setwd(dir)
	on.exit(setwd(owd), add = TRUE)
	
	# Construct path to pandoc.
	root <- "https://s3.amazonaws.com/rstudio-buildtools"
	suffix <- sprintf("pandoc-%s-windows-x86_64.zip", version)
	url <- file.path(root, "pandoc-rstudio", version, suffix)
	
	# Download and extract pandoc.
	file <- basename(url)
	utils::download.file(url, destfile = file)
	utils::unzip(file)
	unlink(file)
	
	# Write .Renviron to update the version of Pandoc used.
	entry <- paste("RSTUDIO_PANDOC", shQuote(path.expand(dir)), sep = " = ")
	contents <- if (file.exists("~/.Renviron")) readLines("~/.Renviron")
	filtered <- grep("^RSTUDIO_PANDOC", contents, value = TRUE, invert = TRUE)
	amended <- union(filtered, entry)
	writeLines(amended, "~/.Renviron")
	
	# Report change to the user.
	writeLines("Updated .Renviron:\n")
	writeLines(amended)
	writeLines("\nPlease restart RStudio for these changes to take effect.")
	
})
```

If you have the time, I'd appreciate it if you could test this version of Pandoc to see if the crashes still occur. (From a bit of testing on my side, everything looked good)

**Comment by aphalo** [comment]
@kevinushey Works for me. Yes!! Before running your scrip to update pandoc the User Guide for 'ggpmisc' failed consistently. After the update the problem is solved (tested several times). I also tested about 10 other vignettes which had earlier at least some of them  triggered the same error. They all could be built without problem. I tested all of them with build > more > documentation, build > more > source package, build > check and by building the documentation web sites with pkgdown. 
So for me the problem seems to be over. Great!

**Comment by strengejacke** [comment]
I had similar issues, updated Pandoc from its website to 2.7 (still erros), but using your code snippet that updates pandoc inside RStudio works for me! Thanks!

**Comment by FelixErnst** [comment]
@kevinushey works for me as well. Thanks.

**Comment by gueyenono** [comment]
The fix provided by @kevinushey also worked for me. Thank you very much.

**Comment by jmcphers** [comment]
If anyone's still having trouble, we have a preview release available which bundles a newer Pandoc that doesn't have this problem. 1.2.1502 or newer:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by mmorenozam** [comment]
thank you very much, I had the same problem. It worked perfectly

**Comment by tomicapretto** [comment]
I've been struggling with this problem all the morning and now it works! Thanks for the update.

**Comment by lindeloev** [comment]
@kevinushey Thanks! I needed to set `dir` to a subdirectory of one of `.libPaths()`. For me, I used

`dir <- "C:/Users/jonas/R/rstudio-pandoc"`

**Comment by s-conner** [comment]
Thank you for this!! I was struggling to knit an R Markdown file on network drive, this + mapping the drive finally worked for me.

**Comment by kalenkovich** [comment]
Worked as is. Thank you @kevinushey!

**Comment by ericntay** [comment]
@kevinushey . Worked like magic !!! This pandoc thing was driving me crazy. Thank you!!

**Comment by etzkorn** [comment]
Still not working. If you could clarify what "dir" is supposed to be, I think that would be really helpful. Is it the directory where the markdown document to be knitted exists? Or some other folder? Thanks!

**Comment by kevinushey** [comment]
`dir` in that script is just the directory where this updated version of Pandoc will be installed.

**Comment by etzkorn** [comment]
Correct, but where SHOULD that be?

**Comment by dpprdan** [comment]
From https://github.com/rstudio/rstudio/issues/4072#issuecomment-484934105: 

> If anyone's still having trouble, we have a preview release available which bundles a newer Pandoc that doesn't have this problem. 1.2.1502 or newer:
> 
> [rstudio.com/products/rstudio/download/preview](https://www.rstudio.com/products/rstudio/download/preview/)

Since that preview release has become a stable release in the meantime, the easiest fix is to update to the current stable release (v1.2.5001 at the time of writing): https://rstudio.com/products/rstudio/download/#download

@etzkorn If you cannot update RStudio, maybe [this comment](https://github.com/rstudio/rstudio/issues/4072#issuecomment-492169457) helps?

**Comment by 001rnsnnsns** [comment]
hi, 
I am having a major issue .please help ..i dont use much R and very weak as such in understanding the above script.

I was facing the issue earlier yesterday .

I ran the script posted on 16th Mar above  and now i am getting

Error in system(paste(shQuote(path), "--version"), intern = TRUE) : 
  'CreateProcess' failed to run 'C:\Users\ram bablani\DOCUME~1\rstudio-pandoc\pandoc.exe --version'
Calls: <Anonymous> ... get_pandoc_version -> with_pandoc_safe_environment -> force -> system
Execution halted



I have resinstalled R studio twice and even run as admin but no change 

also, i ran the below commands 

> rmarkdown::pandoc_available()

Error in system(paste(shQuote(path), "--version"), intern = TRUE) : 
  'CreateProcess' failed to run 'C:\Users\ram bablani\DOCUME~1\rstudio-pandoc\pandoc.exe --version'
 
> pandoc -v
Error: object 'pandoc' not found

 
> Sys.getenv("RSTUDIO_PANDOC")
[1] "C:/Users/ram bablani/Documents/rstudio-pandoc"





Please help me here as I am doing a college assignment

**Comment by kevinushey** [comment]
> 'CreateProcess' failed to run 'C:\Users\ram bablani\DOCUME~1\rstudio-pandoc\pandoc.exe --version'

Sorry, but I do not know why this would fail on your system.

**Comment by Jingciii** [comment]
I also found if I don't set message = FALSE at any chunk, this error won't appear

**Comment by aegerton** [comment]
I tried running the script to solve this rendering problem and received the following error message in response to the particular line of code;-
```
utils::download.file(url, destfile = file)
Error in utils::download.file(url, destfile = file) : 
  cannot open destfile 'pandoc-2.7.1-windows-x86_64.zip', reason 'Permission denied'
```
What am I doing wrong, please?

**Comment by acircleda** [comment]
This worked for me! I copied and pasted the code above verbatim.

**Comment by DiegoJArg** [comment]
Hi.
I found this thread because I was having this issue.
I solved/workarounded it be replacing `output: html_notebook` with `output: html_document`


My full error message was:
`Error creating notebook: 'CreateProcess' failed to run 'D:\PERSONAL_2021_~~~~~~~~\R\~~~~~~\pandoc.exe --version'. `
I don't know why is trying to run pandoc in that location, where my files are placed.



RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
