### ISSUE TITLE
rJava fails to load

### ISSUE THREAD

**Issue by manuelmorgado94** [rstudio/rstudio#4074]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : OS High Sierra: 10.13.3 (17D47)
    R Version       : R version 3.5.1

### Describe the behavior you expected

rJava fails to load. 
Error is below: 

> _Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found_

I've tried `sudo R CMD javareconf` in terminal with the following output:

> Java interpreter : /usr/bin/java
Java version     : 1.8.0_191
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on macOS

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
/usr/local/Cellar/gcc/8.2.0/bin/gcc-7 -I"/anaconda3/lib/R/include" -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/../include/darwin  -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/anaconda3/include   -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix  -c conftest.c -o conftest.o
/bin/sh: /usr/local/Cellar/gcc/8.2.0/bin/gcc-7: No such file or directory
make: *** [/anaconda3/lib/R/etc/Makeconf:160: conftest.o] Error 127
Unable to compile a JNI program, ignoring this though as you may not want to compile anything here
.. this is an Anaconda Distribution and conda-forge customization whereby env activation causes us
.. to call R CMD javareconf in order to dynamically detect a JDK that may be in that env. The fact
.. that we prohibit setting LD_LIBRARY_PATH is also somewhat responsible for us needing to do this
.. because ${R_HOME}/etc/ldpaths is the normal way that R dynamically finds shared libraries. This
.. is what would, in upstream R, set LD_LIBRARY_PATH. AD cannot set this as it causes all sorts of
.. issues with DT_RUNPATH / DT_RPATH on various distributions.

JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /anaconda3/lib/R
Done.

But then i try to load the library (rJava) and still get the same error as before. Looking for Java 9. 

Any help would be highly appreciated.
Thanks

**Comment by manuelmorgado94** [comment]
@s-u

**Comment by kevinushey** [comment]
From your output log:

> /bin/sh: /usr/local/Cellar/gcc/8.2.0/bin/gcc-7: No such file or directory

Apparently you've configured R to use a compiler that no longer exists.

We don't provide general R support on our GitHub issue tracker; you could consider asking your question on the [community forums](https://community.rstudio.com) instead.

**Comment by manuelmorgado94** [comment]
I'm getting this now:

Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found

**Comment by manuelmorgado94** [comment]
@kevinushey

**Comment by s-u** [comment]
You're missing Java runtime. See the error - make sure you install JDK 11.0.1.
