### ISSUE TITLE
Clear list does not clear the list

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#4080]
I am not able to clear my publish list even after getting a success message in the dialog. See video for details:

https://vimeo.com/307858838

![image](https://user-images.githubusercontent.com/7519295/50375838-0e23a980-05d2-11e9-89f7-7143fbebc2d4.png)

**Comment by kevinushey** [comment]
What kind of project are you trying to deploy here? Is this a bookdown project?
