### ISSUE TITLE
Character corruption in RStudio code editor and debugger preventing correct string manipulation

### ISSUE THREAD

**Issue by SamoPP** [rstudio/rstudio#4082]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1206
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.2

### Describe the problem in detail
Code with unicode characters like `catapultsString.delm <- gsub("–", "", gsub(" – ", "", gsub(" –", "", gsub("– ", "", catapultsString.delm))))` is not interpreted correctly. Those characters are transformed either to "???" (in code editor of RStudio: `catapultsString.delm <- gsub("???", "", gsub(" ??? ", "", gsub(" ???", "", gsub("??? ", "", catapultsString.delm))))`) or to `catapultsString.delm <- gsub("<e2><80><93>", "", gsub(" <e2><80><93> ", "", gsub(" <e2><80><93>", "", gsub("<e2><80><93> ", "", catapultsString.delm))))` in RStudio debugger. Also, cursors and line starts are off in debugger. Please see attached screenshots. This works perfectly in Eclipse StatET. This prohibits string manipulation in R in RStudio when characters are unicode...

Eclipse StatET code editor:
![image](https://user-images.githubusercontent.com/4817398/50387147-4656e500-06c3-11e9-8518-4619a3de2311.png)

RStudio code editor screenshot:
![image](https://user-images.githubusercontent.com/4817398/50387123-f841e180-06c2-11e9-9a68-db7aea2589cc.png)

RStudio debugger screenshot:
![image](https://user-images.githubusercontent.com/4817398/50387108-b0bb5580-06c2-11e9-86d7-0c4010eedcc1.png)

**Comment by ronblum** [comment]
@SamoPP Thank you for letting us know about the issue. Can you please provide a reproducible example? The code above is dependent on `catapultsString.delm` first being defined.

**Comment by SamoPP** [comment]
This is not conditional on the` catapultsString.delm`. It can be whatever. Just make it `catapultsString.delm <- "foobar"`. The problem is the "interpreter" in R/Rstudio or, maybe, Shiny, actually...

**Comment by SamoPP** [comment]
> @SamoPP Thank you for letting us know about the issue. Can you please provide a reproducible example? The code above is dependent on `catapultsString.delm` first being defined.

So, here is the reproducible code, if my previous answer was not sufficient:

```
catapultsString.delm <- "AsdfgTHZUkJIZMJLassadkjdhiuekldsfhvskgorioireoi"
catapultsString.delm <- gsub("–", "", gsub(" – ", "", gsub(" –", "", gsub("– ", "", catapultsString.delm))))
```

Is this sufficient for you to reproduce the issue?

**Comment by ronblum** [comment]
@SamoPP What encoding are you using when saving the file? I can reproduce this on Ubuntu 18 if I save in ASCII but not when using UTF-8 (default).

**Comment by kevinushey** [comment]
It would be helpful to know what your `sessionInfo()` is -- it looks like you're not working with a UTF-8 locale, which would be fairly rare for a Linux system nowadays.

**Comment by SamoPP** [comment]
Accidentally closed the issue... :)

**Comment by kevinushey** [comment]
You are in a UTF-8 locale, so best guess is (as @ronblum guessed) you saved the file in ASCII (or some other non-UTF-8) format and conversion generated `?` from those characters not representable in the requested locale.

**Comment by jmcphers** [comment]
This has been pending a repro for over a year and hasn't garnered any additional reports or info, so not likely we'll make any further progress.
