### ISSUE TITLE
Opening a large Rprofvis file cause UI hanging

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#4084]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1204
    OS Version      : Ubuntu 16.4
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Write a script of heavy computing (a lot of R calls that consumes a lot of CPU and RAM)
2. Profile the script and save the resulting Rprofvis file.
3. Open the profiling file, and then the UI hangs. It may also cause other web pages in the same browser to hang, or cause the whole browser to be unresponsive.

**Comment by ronblum** [comment]
@renkun-ken Thank you for reporting this. Can you provide a sample script so that we can reproduce this?

**Comment by renkun-ken** [comment]
Try the following steps:

1. Start profiling
2. Source the following script:

```r
library(data.table)

n <- 5000000
ft <- data.table(id = seq_len(n))
ft[, group := seq_len(.N), by = .(g = id %% 1000)]
ft[, x0 := rnorm(.N)]
# copy and paste the following line many times (e.g. 2000 times)
for (i in 1:10) ft[, paste0("x", i) := filter(x0, runif(i), method = "c", sides = 1), by = group]
```

3. End profiling
4. A very large Rprofvis is produced. 
5. RStudio Server should hang for a long time. 
6. If RStudio Server is able to show it, save the Rprofvis file and reopen it.
7. Copy-paste as many lines of the `for-loop` so that the profiling get large enough to cause the web browser hang.

**Comment by ronblum** [comment]
I got a core dump:
> \> source('~/.active-rstudio-document')
data.table 1.12.0  Latest news: r-datatable.com
pandoc: internal error: Unable to commit 1048576 bytes of memory
    (GHC version 8.4.3 for x86_64_alpine_linux)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
Aborted (core dumped)

It's possible I don't have enough RAM or drive space allocated. However, I would hope that a single user's large profiling wouldn't bring down the machine.

**Comment by ronblum** [comment]
A way to handle this is to limit how much a session can consume. In `/etc/rstudio/profiles`, set
```
[*]
max-memory-mb = 2048
```
Pandoc may run out of memory, but the session and RStudio Server will be safe.
https://docs.rstudio.com/ide/server-pro/r-sessions.html#resource-limits

**Comment by jmcphers** [comment]
There is no way we can fix this in RStudio; all of the complex HTML responsible is generated by the profvis package. That package would need to fix this by implementing some kind of virtualized viewing surface (that e.g. stored the profile in JSON and rendered only a portion of it to the DOM).
