### ISSUE TITLE
R banner duplicated when opening project

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#4085]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1210
    OS Version      : Windows 7, 64 bit
    R Version       : 3.5.2

### Steps to reproduce the problem

Start RStudio 
Open a project

### Describe the problem in detail

When opening a project within the daily build of RStudio the R startup message is displayed twice in the console window. The problem doesn't occur when opening RStudio without a project loaded. 
![image](https://user-images.githubusercontent.com/28725410/50394852-9b950400-0760-11e9-946d-f8c66b21e0e5.png)

The behavior seems to be the same as in #3439 but that issue is closed. For me it happens consistently when opening a project (either from within are RStudio or by starting RStudio by double clicking a project) but I haven't seen it outside of projects.

### Describe the behavior you expected

A single startup message being displayed.

```
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2    packrat_0.5.0 
```

**Comment by ronblum** [comment]
@BartJanvanRossum Thank you for reporting this! I'm closing it as a duplicate and reopening the original issue.
