### ISSUE TITLE
Markdown images won't show a preview in RMarkdown

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#4087]
### System details

    RStudio Edition : Desktop
    OS Version      : Mac
    R Version       : 3.5.1

### Steps to reproduce the problem

Open an RMarkdown document with the lines:

````
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

![](https://www.random.org/analysis/dilbert.jpg)
````

### Describe the problem in detail

On the current release of RStudio, 1.1.463, the image will automatically show a preview:

<img width="1009" alt="screen shot 2018-12-24 at 7 01 36 am" src="https://user-images.githubusercontent.com/19150088/50399050-74333c80-074a-11e9-9b26-b58f3fabc48c.png">

On the preview release of RStudio, 1.2.1206, the image no longer shows a preview:

<img width="1004" alt="screen shot 2018-12-24 at 7 03 37 am" src="https://user-images.githubusercontent.com/19150088/50399057-844b1c00-074a-11e9-9b04-6266102fead0.png">

This happens on local files and urls.

### Describe the behavior you expected

I expect a preview to show up.

### Additional

I think Tareef also noted that autocomplete in the form of `![](path/<autocomplete_here>)` was broken, and I could confirm that on an older version of the preview release, but the newest preview release seems to have fixed that.

**Comment by ronblum** [comment]
Reproduced on MacOS 10.14.2 Mojave and Windows 10 with RStudio Desktop, and Ubuntu 18.04 with RStudio Server.

**Comment by jmcphers** [comment]
See related: https://github.com/rstudio/rstudio/issues/3996.

**Comment by Timag** [comment]
I am not sure whether to add it here:

I noticed that the image preview only shows up if you type in the code, not if you copy&paste the code.
RStudio 1.1.453, R 3.4.3, Windows 10.
