### ISSUE TITLE
Plumber download is broken

### ISSUE THREAD

**Issue by Mailaender** [rstudio/rstudio#4088]
https://s3.amazonaws.com/rstudio-buildtools/plumber-0.4.6.zip is access denied. Though https://github.com/rstudio/rstudio/pull/2933 I still get:

```
plumber package not found (re-run install-dependencies script to install)
```

Do you support the usage of a system provided plumber or does it have to be installed somehow.

PS: This happened on version 1.2.679 under Linux.

**Comment by gtritchie** [comment]
To clarify, you are attempting to build RStudio from source? If so, you need to sync to a much more recent 1.2 commit than 1.2.679; that is quite old and RStudio 1.2 is still under active development.
