### ISSUE TITLE
At startup: "there is no package called 'rmarkdown'"

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#4092]
On a completely fresh Windows 10 VM, fresh installation of R 3.5.2, fresh installation of RStudio Preview v1.2.1206-2, I see this upon first launch:

``` r
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
...
Error in loadNamespace(name) : there is no package called 'rmarkdown'
Error in loadNamespace(name) : there is no package called 'rmarkdown'
```

**Comment by jmcphers** [comment]
I couldn't reproduce this. :-/ @ronblum did you see it?

**Comment by ronblum** [comment]
I don't see this, using the same versions, but I'm not using a fresh install. I'll set one up. @jennybc Can you check the Windows 10 build number, under System Information? It's likely 10.0.17763 or 10.0.18267.

**Comment by jennybc** [comment]
I am still seeing the phenomenon btw upon every start up.

Windows 10 build number 10.0.17134

**Comment by kevinushey** [comment]
Do you have any luck adding some debugging to your `.Rprofile`; e.g. something like:

``` r
.First <- function() {
  trace(base:::loadNamespace, quote({
    if (package == "rmarkdown")
      utils::str(sys.calls())
  }), print = FALSE)
})
```

(replacing `utils::str()` with a better call-stack printer if available)

**Comment by jennybc** [comment]
I see

``` r
Tracing function "loadNamespace" in package "base (not-exported)"
Dotted pair list of 14
 $ : language (function (input_dir, encoding)  { ...
 $ : language rmarkdown:::enumerate_output_formats
 $ : language get(name, envir = asNamespace(pkg), inherits = FALSE)
 $ : language asNamespace(pkg)
 $ : language getNamespace(ns)
 $ : language tryCatch(loadNamespace(name), error = function(e) stop(e))
 $ : language tryCatchList(expr, classes, parentenv, handlers)
 $ : language tryCatchOne(expr, names, parentenv, handlers[[1L]])
 $ : language doTryCatch(return(expr), name, parentenv, handler)
 $ : language loadNamespace(name)
 $ : language .doTrace({     if (package == "rmarkdown")  ...
 $ : language eval.parent(exprObj)
 $ : language eval(expr, p)
 $ : language eval(expr, p)
```

**Comment by ronblum** [comment]
I wasn't able to reproduce this after resetting the Windows 10 VM to build 10.0.17134, installing R 3.5.2, and installing and activating RStudio Desktop Pro 1.2.1206-2. Also, `installed.packages()` doesn't include `rmarkdown` (as expected).

**Comment by kevinushey** [comment]
Do you have an R Markdown document open in the IDE?

**Comment by kevinushey** [comment]
(or, files of any kind?)

**Comment by jmcphers** [comment]
> the project I'm opening is a bookdown site.

Interesting! Do you see it at startup when no project is open (e.g. after closing the project, then restarting RStudio)?

**Comment by kevinushey** [comment]
Given this:

```
 $ : language (function (input_dir, encoding)  { ...
```

the two methods being called were likely these:

https://github.com/rstudio/rstudio/blob/47e80c65c243f85c2ff8c08228d6c8f89457582c/src/cpp/session/modules/SessionRMarkdown.R#L438-L459

So this was likely run in some kind of website-y project (bookdown, blogdown, and so on).

**Comment by kevinushey** [comment]
To reproduce:

1. Create and open a bookdown project;
2. `remove.packages("rmarkdown")`,
3. Restart RStudio.

Should we do something a bit more user-friendly here? E.g. some kind of UI like:

> The project you have opened requires the 'rmarkdown' package, but it is not currently installed. Would you like to install it?

**Comment by mirh** [comment]
I quite think that pop-up would be useful. 
Otherwise, for proper neatness every notepad and snippet should include whatever your [dependencies check](https://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them) of choice for *rmarkdown*.
