### ISSUE TITLE
Rmarkdown; dynamic title does not render in the last update

### ISSUE THREAD

**Issue by djouallah** [rstudio/rstudio#4093]
RStudio
Version 1.2.1206
© 2009-2018 RStudio, Inc.
Build 1245 (96fb791d)
windows 10, 64 bits

I have being using the code to render a dynamic title in flexdashboard for the last couple of  months with no problem, after updating to the last preview, the title does not show up instead i get this

summary.utf8.md ( summary is the rmd file name)

my RMDcode is 

```
---
output:
  flexdashboard::flex_dashboard: default
  html_document: default
---

   ``'{r}
     r code to get the values of title_Var
     title_Var <- paste("Numurkah", format(max(Data$`Cutt Off daily`), "%d %b %Y"))
   ``'
 ---
title:  `r title_Var`
 ---

```

now the only to show a title is by writing the title at the top of the rmd file.

**Comment by jmcphers** [comment]
This is a flexdashboard issue, not an RStudio issue. You can open an issue over there if you think there's a bug:

https://github.com/rstudio/flexdashboard

That said, I think you just need to put your expression in the title directly, e.g.:

     ---
     output:
       flexdashboard::flex_dashboard: default
       html_document: default
     title: `r paste("Numurkah", format(max(Data$`Cutt Off daily`), "%d %b %Y"))`
     ---

**Comment by audyavar** [comment]
This is not just a flexdashboard issue unfortunately. I am having a similar issue with Rmd in RStudio. 

-----
params: 
  dynamictitle: !r test_title
author: ""
date: "`r date()`" 
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r code}
pt_id <- "123"
test_title <- paste0(pt_id, ": Biomarker Summary Report")
test_title
```

---
title: "`r params$dynamictitle`"
---
