### ISSUE TITLE
Error using tinytex in portable mode, with tinytex::use_tinytex(). Can't knit to PDF.

### ISSUE THREAD

**Issue by matacarlos01** [rstudio/rstudio#4096]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      :  Windows 10
    R Version       :  3.5.1

### Steps to reproduce the problem
I used  tinytex::copy_tinytex() to create a copy of tinytex, then used tinytex::use_tinytex() to set up my R Studio to create PDFs.

### Describe the problem in detail
I get this error:

> tinytex::use_tinytex()
warning: kpathsea: //QSR-FP23.YWH.LOCAL/home-mqo-1$/User/My Documents: Unrecognized variable construct `$/'.
Use of uninitialized value in bitwise or (|) at S:\Applications\SUBSUR~1\Useful Software\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 1482.

Restart R and your editor and check if tinytex::tinytex_root() points to S:/Applications/Subsurface_Tools/Useful Software/TinyTeX

The tinytex::tinytex_root() command shows the right folder. But Rstudio doesn't create the PDF.

When I attempt to knit my R Markdown to PDF, I keep getting the same error all the time:
"No TeX installation detected (TeX is required to create PDF output). You should install a recommended TeX distribution for your platform: ........"

### Describe the behavior you expected

I expected to be able to knit my R Markdown document to PDF.

Output of sessionInfo():
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    rstudioapi_0.8 yaml_2.2.0     tinytex_0.9    xfun_0.4

**Comment by jmcphers** [comment]
The error is from `tinytex::use_tinytex()`, not RStudio, so you'll need to file an issue over there. 

https://github.com/yihui/tinytex
