### ISSUE TITLE
Error when uploading new theme - Windows 10

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#4097]
### System details

    RStudio Edition : Windows Desktop 
    RStudio Version : 1.2.1216
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem
1. create a new tmTheme or rstheme file
2. Go to Global Options -> Appearance -> Add 
3. Upload the new theme file
### Describe the problem in detail
Error message is displayed
![image](https://user-images.githubusercontent.com/43964690/50654853-0f929180-0f43-11e9-89a7-a980bb6c2f8b.png)

### Describe the behavior you expected
Theme is uploaded without issue

**Comment by jmcphers** [comment]
@rich-rstudio I was not able to reproduce this on 1.2.1225. How did you create your .tmtheme file? Can you link to it, or paste its contents?

**Comment by jmcphers** [comment]
Moving out of 1.2 until we get repro steps.

**Comment by jmcphers** [comment]
Literally an empty file (0 bytes)?

**Comment by rich-rstudio** [comment]
yeah a blank doc, 0 bytes

**Comment by MariaSemple** [comment]
This behaviour should be improved in 1.3 by d7c3950. Empty files should not be able to be added.
