### ISSUE TITLE
Using sm package causes RStudio session to stop working when building package

### ISSUE THREAD

**Issue by rabutler-usbr** [rstudio/rstudio#4098]
The RStudio R Session stops working when building a package in RStudio that uses the sm package. 

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1153 and 1.2.1206
    OS Version      :  Windows 10 x64 (build 16299)
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create a new package in RStudio
2. add sm to Imports
3. Add in the following function or similar:
```
sm_fail <- function() {
  print("try call to sm...")
  xx <- rnorm(100)
  band <- sm::hnorm(xx)
  # nothing
}
```
4. Build the package - this will cause the error 
5. Build the package - there will not be an error
6. If you wish to get the error again, edit the code, e.g., delete the `# nothing` line, and rebuild. This will result in an error.

### Describe the problem in detail

I've encountered this error in a package that imports multiple packages, but I've repeated the error using a "clean" skeleton package which only includes the provided `hello()` function, and a `sm_fail()` function which calls `sm::hnorm()` (see below). The following error occurs after adding in the call to `sm::hnorm()` and building the package (Ctrl + Shift + B) in RStudio:

![fail](https://user-images.githubusercontent.com/37666411/50656033-2c34c680-0f4f-11e9-9265-4164e55679f9.png)

A couple items worth noting:
- This does not seem to occur with other packages, ggplot2, dplyr, stats. 
- If you  build the package again, everything seems to work ok. However, then modifying the code even slightly, e.g., deleting the "nothing" comment below, and rebuilding will cause the error again.
- There must be a call to some function in the sm package, i.e., only importing the sm package does not result in the error
- The error occurs if calling other functions, e.g., `sm::sm.density()` instead of `sm::hnorm()`

### Describe the behavior you expected

I would expect the package to build with out causing an RStudio session error. 

The output of `sessionInfo()`:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testsm_0.1.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1   tools_3.5.1      withr_2.1.2      memoise_1.1.0    digest_0.6.17    packrat_0.4.9-11
[7] devtools_1.13.6 
```

A diagnostic report is available at [diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2725005/diagnostics-report.txt)

Thanks for any help you can provide.

**Comment by rabutler-usbr** [comment]
Thanks for taking a look @kevinushey . 

Here is the sm package and my test package if it helps at all: [sm-packages.zip](https://github.com/rstudio/rstudio/files/2746314/sm-packages.zip)

Also, when testing again, the first build would succeed. Then after editing the `sm_fail()` function, the error occurred on the next build.

**Comment by ronblum** [comment]
Appears to be working in Windows with [the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/) Please reopen if it's still an issue.
