### ISSUE TITLE
`devtools` not found using GUI package buttons even though installed and available via console

### ISSUE THREAD

**Issue by rsangole** [rstudio/rstudio#4100]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.453
    OS Version      : x86_64-pc-linux-gnu, Azure HDInsights Cluster
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Create a new R Package
2. Try to run "Document" or "Build Source Package" using the GUI interface

### Describe the problem in detail

1. Although `devtools` is correctly installed and available on the console, the GUI driven buttons cannot find it, giving an error shown below.

**`devtools` correctly available in system installation** in `/opt/microsoft/mlserver/9.3.0/libraries/RServer`
![image](https://user-images.githubusercontent.com/6344050/50665761-efcd8e80-0f7f-11e9-9b71-b0b200742081.png)

**`devtools` can correctly load using the console**
![image](https://user-images.githubusercontent.com/6344050/50665801-12f83e00-0f80-11e9-99ff-479245a9d960.png)

**Yet, error when using the GUI buttons**
![image](https://user-images.githubusercontent.com/6344050/50665844-358a5700-0f80-11e9-926c-211dac9f6019.png)

**Comment by ronblum** [comment]
@rsangole I can reproduce this only if `devtools` is installed as a packrat library but not as a user library. Can you confirm?

**Comment by rsangole** [comment]
@ronblum Nope, I'm not using `packrat`. If you're familiar with Azure HDInsights, all the packages were installed using "action scripts" which installs the packages on the head, edge and worker nodes when the cluster is created.

**Comment by kevinushey** [comment]
What is the output of:

``` r
Sys.getenv("R_LIBS")
Sys.getenv("R_LIBS_USER")
```

How are the library paths initialized for an RStudio session on your machine?

**Comment by rsangole** [comment]
```
> Sys.getenv("R_LIBS") 
[1] "" 
> Sys.getenv("R_LIBS_USER") 
[1] "~/R/x86_64-pc-linux-gnu-library/3.3" 
> .libPaths() 
[1] "/home/hw831/R/x86_64-pc-linux-gnu-library/3.3"   "/opt/microsoft/mlserver/9.3.0/libraries/RServer" 
[3] "/opt/microsoft/mlserver/9.3.0/runtime/R/library"
```

> How are the library paths initialized for an RStudio session on your machine?

I'm not sure how to find out the answer to this question, tbh. Does the answer lie in the `.RProfile.site`?

**Comment by martinschmelzer** [comment]
Having a similar issue. when using Cmd + Shift + D to document using roxygen2, I get the error 

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: suppressPackageStartupMessages ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Exited with status 1.
```

`devtools` is installed in a custom user library. All packages installed there are loaded and shown in the Packages pane.

**Comment by kevinushey** [comment]
RStudio runs the moral equivalent of:

```
R --vanilla --slave -e 'devtools::document()'
```

The `R_LIBS` environment variable is forwarded to the child process, so unless that variable has been updated the child R process won't know about your custom library.

**Comment by martinschmelzer** [comment]
Thank you. I will check on that. Interestingly, it worked flawlessly until yesterday and I did not change anything around my Rprofile.site, Renviron, the custom lib and so on ....
