### ISSUE TITLE
Update package form contains incorrect URL's for the NEWS links

### ISSUE THREAD

**Issue by scubastevew** [rstudio/rstudio#4105]
The update packages form does re-direct to the correct URL's. In this particular case, with the codetools, it goes to a 404.  

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463
    OS Version      : Mac OS 10.14.2
    R Version       : 3.5.2

### Steps to reproduce the problem
**Pre-req - have an older version of the codetools package installed (I have v0.2-15 installed)

1) Open RStudio desktop
2) Click Tools -> Check for Updates
3) In the codetools row, click the icon in the NEWS column

### Describe the problem in detail

URL goes to https://cran.rstudio.com/web/packages/codetools/news.html which just 404's. 

### Describe the behavior you expected

The URL should probably go to: https://cran.rstudio.com/web/packages/blogdown/news/news.html

It looks like it's missing /news/ in the URL path. 

### Other Information

RStudio version 1.1.463 Screen Recording: http://recordit.co/mcLaZ0nMns

I did find a similar logged issue with: https://github.com/rstudio/rstudio/issues/3766 and on that advice, I did try the preview version of 1.2.1206 and it's not resolved there either. It doesn't 404 but it also doesn't open anything in the browser. 

RStudio version 1.2.1206 Screen recording: http://recordit.co/gh0NS2BPJC

**Comment by kevinushey** [comment]
The behavior in v1.1.463 doesn't seem right -- you're getting the NEWS URL for the wrong package in that case.

In theory you're getting the correct behavior in v1.2.1206 since the `codetools` package does not actually have a NEWS URL. You should see in the R console:

```
Warning in (function (packageName, libraryPath)  :
  Failed to infer appropriate NEWS URL: using 'news/news.html' as best-guess candidate
```

Perhaps we should just open the CRAN landing page when we can't figure out the NEWS URL.

**Comment by ronblum** [comment]
1) @scubastevew I think there's a cut-and-paste issue in the description above: the URL in the recording goes to the `codetools` URL, https://cran.rstudio.com/web/packages/codetools/news.html, not `blogdown`. (And it also 404s.) Can you confirm?
2) 👍 for going to the CRAN landing page. Should I open a separate issue or just mark this one as an enhancement?

**Comment by scubastevew** [comment]
@ronblum You're right! I updated it. Thanks!
