### ISSUE TITLE
Stopping package install does not remove lock

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4108]
**Steps to reproduce:**
* Create an R project for a package
* Add some compiled code in `/src`
* Change the name of the folder where the package is
* In the panel with the `Build` tab, click `Install and restart`
* Before it finishes compiling source code, click the stop button in the top-right of that same panel

**Expected behavior:**
* Package should not be locked after it's stopped and no longer compiling.

**Actual behavior:**
* Package lock is not removed (e.g. `/home/user/R/x86_64-pc-linux-gnu-library/3.5/00package`), this clicking again `Install and restart` will fail due to the lock.

**Setup:** RStudio 1.2.1060, R 3.5.1, running on debian linux.

**Comment by kevinushey** [comment]
I'm not able to reproduce. The associated lockfile is removed for me after an unsuccessful build.

**Comment by kevinushey** [comment]
Yes, it still works.

What is the actual lockfile called in your case? It should be either:

```
/home/user/R/x86_64-pc-linux-gnu-library/3.5/00LOCK
```

or

```
/home/user/R/x86_64-pc-linux-gnu-library/3.5/00LOCK-<package>
```

Are you doing anything like customizing your library paths in a startup profile?

**Comment by david-cortes** [comment]
It's like the 2nd one (`/home/user/R/x86_64-pc-linux-gnu-library/3.5/00LOCK-<package>`). I'm not doing any such customization and the computer where this happens doesn't even have an `.Rprofile`.

**Comment by kevinushey** [comment]
Are you sure you're using RStudio v1.2 on this system? We explicitly added support for cleaning up these lockfiles recently:

https://github.com/rstudio/rstudio/blob/f502da1fd510ea1ba7a440bb2d8728e61f7da79b/src/cpp/session/modules/build/SessionBuild.cpp#L1625-L1632

Otherwise, it's possible that RStudio is getting the wrong path to the lockfile somehow. Does the package name differ from the folder name? Did you change the package name?

**Comment by kevinushey** [comment]
Okay, I can reproduce specifically in the case where the folder name does not match the package name.

**Comment by david-cortes** [comment]
> Okay, I can reproduce specifically in the case where the folder name does not match the package name.

I changed the name actually, so perhaps that's where it came from.

**Comment by kevinushey** [comment]
This is why it's important to provide a fully reproducible example (the renaming of your package was a vital step in reproducing the issue and it was not included in your initial report)

**Comment by kevinushey** [comment]
I should have noticed that you did explicitly mention that:

> Change the name of the folder where the package is

Apparently I need to work on my reading comprehension. Thanks for reporting!

**Comment by kevinushey** [comment]
Thanks for reporting -- it would have helped if that piece was included in your initial report (I see it's now been edited) since that was the vital piece of information missing in reproducing this issue.
