### ISSUE TITLE
Commenting not working for .c files

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4109]
**Steps to reproduce:**
* Open some `.c` file in RStudio
* Select some piece of text
* Press Ctrl + Shift + c

**Expected behavior:**
* Should comment it out with `//` just like in a `.cpp` file

**Actual behavior:**
* Nothing happens

**Comment by ronblum** [comment]
@david-cortes Thanks for reporting this! We'll take a look at it as we continue development.

Confirmed with RStudio Desktop 1.2.1225-1. Marking as a bug, though it might really be an enhancement.

**Comment by MichaelChirico** [comment]
I would also be fine with <kbd> Ctrl </kbd> <kbd> / </kbd> working since that's the command in Jupyter/Atom & makes more visual/intuitive sense in the case of actually adding `/` to comment

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.

**Comment by ronblum** [comment]
This is working in
- RStudio Server 1.4.1620 on Red Hat 8.3 via Firefox on MacOS 11.3
- RStudio Server 1.4.1620 on SLES 15 SP2 via Safari on MacOS 11.3
- RStudio Desktop 1.4.1620 on MacOS 11.3
