### ISSUE TITLE
clicking find in files result didn't go to the file

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#4112]
When clicking a row in the `Find in files` result, the selected file should be opened at the selected position. With the `v1.2.1206-2` version clicking did nothing, but `v1.2.1194` is working fine on this.

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
```

**Comment by kevinushey** [comment]
Seems to work fine in the latest daily build (1.2.1223). If you're still having trouble please re-open and provide a reproducible example.
