### ISSUE TITLE
Data viewer row-names column sorts by row number

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4116]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.463, 1.2.1219-3
    OS Version      : MacOS 10.14, Red Hat 7.6
    R Version       : 3.5.1, 3.5.2

### Steps to reproduce the problem

1. `View(mtcars)`
   - Note the order of first column—row names—which is unlabelled, starting with "Mazda RX4," "Mazda RX4 Wag," and "Datsun 710."
2. Click on `mpg` to sort
   - The unlabelled row-names column now starts with "Cadillac Fleetwood," "Lincoln Continental," and "Camaro Z28."
3. Click on the first, unlabelled column
   - The column returns to the original order, starting with "Mazda RX4," "Mazda RX4 Wag," and "Datsun 710."

### Describe the problem in detail

Sorting by the first column is by the row number, not the row name. The values displayed, though, are row names, not numbers, so sorting by what looks like row names makes it seem as if the data viewer isn't sorting correctly.

<img width="225" alt="rstudio_view_mtcars" src="https://user-images.githubusercontent.com/31009952/50794502-4ea14980-1299-11e9-9946-57b8886ad1f0.png">

### Describe the behavior you expected

In R, `View(mtcars)` separates the row name and row names column, and the row name is displayed in a named column, "row.names":

<img width="269" alt="r_view_mtcars" src="https://user-images.githubusercontent.com/31009952/50794559-70023580-1299-11e9-8aec-2c1305c88765.png">

1) The RStudio data viewer should mimic this, and both the "row.names" and unlabelled row-number column should be sortable.
2) If "row.names" can't be sorted alphabetically, sort should be disabled for it (similar to #3886).

**Comment by BartJanvanRossum** [comment]
Not sure if I should add here or file a new issue, but it seems close enough.

It seems that sorting on the row names is always sorting ascending. Following the example above:
![image](https://user-images.githubusercontent.com/28725410/61861998-65be2680-aecd-11e9-82b5-145d8b2148cc.png)
![image](https://user-images.githubusercontent.com/28725410/61861964-4cb57580-aecd-11e9-8aeb-9e1917a30d43.png)

Despite the blue arrow pointing in the other direction the result of the sorting is exactly the same.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1555
    OS Version      : Windows 10
    R Version       : 6.1

**Comment by kevinushey** [comment]
@BartJanvanRossum could you please file a separate issue?
