### ISSUE TITLE
View(x) doesn't update window when x is changed. 

### ISSUE THREAD

**Issue by glilienthal** [rstudio/rstudio#4121]
Sorry, not a great bug report. No time. 

But I thought I'd give you a note anyway. 

I do 

cd <- content(response)
View(cd)

Different get
and
cd <- content(response)
View(cd)
Shows the old view. (I didn't close the tab.) 
If I change the var name or close the tab, I see the new view. 

Using Rstudio 1.1 on win, R 3.5.2

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by kevinushey** [comment]
Fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/).
