### ISSUE TITLE
Cannot run chunk by pressing green triangle after an error occurred

### ISSUE THREAD

**Issue by mjherold** [rstudio/rstudio#4129]
### System details

    RStudio Edition : 
    RStudio Version : 1.1.463
    OS Version      : Mac OS X 10_14_2
    R Version       : 3.5.2

### Steps to reproduce the problem

Have a rather long Rmd file, choose "inline output", and are left with chunk execution hanging if an error occurs in the chunk. Only way to run a chunk again is to restart R at that point. 

### Describe the problem in detail

With an error condition the chunk execution appears to be left hanging. Sometimes the red square appears and I can interrupt the chunk execution and re-run the chunk. But this only works once. After that the only way to run chunks again is to restart R. "Run current chunk" or "Run all" produce nothing.

But if I change the chunk output from "inline" to "output in console", then I do not have this problem running the same chunk. Even with an error I can run the same chunk again without requiring a restart of R.

The problem does not appear to be particular to a specific Rmd file. But it seems to occur only if you have larger files with many chunks.

### Describe the behavior you expected

I would expect an error message, but should still be able to re-run the chunk after that.

**Comment by jmcphers** [comment]
We haven't been able to reproduce this; generally chunk errors should not cause the execution to hang. Can you create an example that we can run that has the problem? 

Do you still see the problem in our preview release?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by mjherold** [comment]
Hi Jonathan: I will try to create a Rmd file to reproduce the problem and will upload to the #4129 report

thanks,

Michael

**Comment by mjherold** [comment]
The problem also persists with the preview release.

**Comment by ronblum** [comment]
I am able to reproduce this in RStudio Desktop 1.2.1287 on MacOS 10.14. In addition, after step (7), before restarting: clicking on the green arrow in another chunk marks it as scheduled (the green arrow is replaced by the clock), but it never runs because it's stuck on the last chunk.

**Comment by kevinushey** [comment]
MRE:

`````
---
output: html_document
---

```{r, error=T}
print(apple)
```
`````

Try running the chunk. It will fail, and then the user will be unable to run any subsequent chunks.

**Comment by kevinushey** [comment]
Perhaps worth saying that the similarly-constructed chunk here works:

`````
---
output: html_document
---

```{r, error=TRUE}
print(apple)
1 + 1
```
`````

It appears that specifically the usage of `error=T` rather than `error=TRUE` is causing the issue.

**Comment by kevinushey** [comment]
It seems that setting `error=<xyz>` to anything other than `TRUE` or `FALSE` is sufficient to trigger this bug. Marking for v1.2 milestone since lots of users will use `T` and `F` shorthands.

**Comment by danieltomasz** [comment]
I have similar problem with  Rstudio 2024.04 and 2024.08, the next chunk cannot run if there was an error related to  reading from file, using `{r, error=TRUE}` seemingly help with my problem

**Comment by ronblum** [comment]
@danieltomasz Can you open a new issue for this? Thanks!
