### ISSUE TITLE
matplotlib plots not cleared between chunks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4131]
### System details

    RStudio Edition : All
    RStudio Version : 1.2.1226-2

### Steps to reproduce the problem

Create a notebook with the following Python chunk.

    ```{python}
    import matplotlib.pyplot as plt
    import random as random
    list = [1,2,3,4,5,6,7,8,9,10]
    plt.plot(random.sample(list, 10), random.sample(list, 10))
    plt.show()
    ```
Then:

1. Run the chunk.
2. Run the chunk again.
3. Run the chunk again.

### Describe the problem in detail

Every time the chunk is run, a new set of random lines appears on the plot. 

![image](https://user-images.githubusercontent.com/470418/50927041-6d275200-140b-11e9-8040-6b12d8af5232.png)

### Describe the behavior you expected

Just like plots in R chunks, plot state should not persist between chunk executions. When it does, it makes it very difficult to iterate on plotting code, since re-running the code doesn't actually re-create the plot (instead it mashes together your old plot with your new one).

Proposed fix is to clear matplotlib plot state after a chunk is running (which is similar to what we do for R code chunks and the R graphics device). (We might also want to see what Jupyter does here.)

**Comment by kevinushey** [comment]
Looks like Jupyter also clears the graphics device state before (or after) each cell is run.

I've fixed this on the reticulate side (https://github.com/rstudio/reticulate/commit/8b44e13d7f9cf5f37ef31d25706dd11085e75204) and will also do the same with RStudio just so things work as expected for users running the CRAN version of reticulate.
