### ISSUE TITLE
Something wrong in the connection between R and github

### ISSUE THREAD

**Issue by pseudoscienc** [rstudio/rstudio#4136]
I am the first time to use github, so I do not know much about what I should do to connect R and my github. The followings are my problems.

When I type the code "git pull origin master" in the shell of Rstudio, I got the following errors:

Could not create directory '/f/szh/githubML/=/.ssh'.
The authenticity of host 'github.com (192.30.255.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/f/szh/githubML/=/.ssh/known_hosts).
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

and by the way when I type the code "ssh -T git@github.com", I got the following messages.

Hi pseudoscienc! You've successfully authenticated, but GitHub does not provide shell access.

Is there anyone can help me to solve the problems? Thank you!!

**Comment by jmcphers** [comment]
Sorry, we can't help with your question here. The Github Issues page is for tracking bugs in RStudio itself, not a help forum. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
