### ISSUE TITLE
Enabling Git for projects in UNC-formatted directories results in errors and no Git tab

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4137]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463 and 1.2.1228-2
    OS Version      : Windows 10
    R Version       : 3.5.2

### Steps to reproduce the problem

1. New Project -> New Directory -> New Project
2. Enter a directory name
3. Check "Create a git repository" if it's not already checked
4. Click on "Browse"
5. For "Folder," enter a directory name in UNC format
6. Open -> Create Project
    - R crashes with "R Session Aborted" modal
7. Start New Session -> Tools -> Project Options -> Git/SVN
8. Under "Version control system," choose "Git"
9. Click on "Yes"
    - "Incorrect function" message

Example of directory name in UNC format:
<img width="541" alt="git_01" src="https://user-images.githubusercontent.com/31009952/50976869-07949d80-14bf-11e9-8dd6-f6e984b81d81.png">

### Describe the problem in detail

Creating a new project with a Git repository and a directory in UNC format results in R crashing and an "R Session Aborted" modal popping up.
<img width="579" alt="git_02" src="https://user-images.githubusercontent.com/31009952/50976908-1f6c2180-14bf-11e9-9c40-9b05252c0f2f.png">

However, the project does get created but without a Git tab.
<img width="439" alt="git_03" src="https://user-images.githubusercontent.com/31009952/50976980-41fe3a80-14bf-11e9-90ca-111e0f41bb21.png">

In addition, choosing Git under project options fails, and a model pops up stating "Incorrect function."
<img width="399" alt="git_04" src="https://user-images.githubusercontent.com/31009952/50976995-475b8500-14bf-11e9-9ca4-cd0d0032f28d.png">

### Describe the behavior you expected

Creating a project in a UNC-formatted directory path should not result in errors, and the Git tab should appear. Also, Git should already be selected under Project Options.
<img width="384" alt="git_05" src="https://user-images.githubusercontent.com/31009952/50977048-6528ea00-14bf-11e9-9b06-731cd9207cd6.png">

[See Support ticket 32580]

**Comment by philipgladwin** [comment]
Would be great if this problem could be fixed.....Phil,

**Comment by kevinushey** [comment]
```
Request ID: -1610198446

== REQUEST ======
{
  "method": "git_init_repo",
  "params": [
    "~/scratch/unc"
  ],
  "clientId": "33e600bb-c1b1-46bf-b562-ab5cba070b0e",
  "clientVersion": ""
}

== RESPONSE ======
{
  "error": {
    "code": 100,
    "message": "Error occurred while executing method",
    "error": {
      "code": 1,
      "category": "system",
      "message": "Incorrect function",
      "location": "class rstudio::core::Error __cdecl rstudio::session::modules::git::`anonymous-namespace'::vcsInitRepo(const struct rstudio::core::json::JsonRpcRequest &,class rstudio::core::json::JsonRpcResponse *) src/cpp/session/modules/SessionGit.cpp:2513"
    }
  }
}
```

**Comment by kevinushey** [comment]
An easy way to test locally is to set your `R_USER` environment variable to as e.g.

```
R_USER = \\LOCALHOST\c$\%USERPROFILE%
```

**Comment by JsizzleR** [comment]
Support for UNC paths requested by Pro customer.
Ref No.  64063

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2021-08.0.302 on Windows 10. Also made sure that a new file will gets saved correctly and shows up in the Git pane and Diff window.
