### ISSUE TITLE
Preview in data import tools fail (from Excel, from Text: readr)

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#4138]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1226
    OS Version      : Windows 10
    R Version       : 3.5.2

### Steps to reproduce the problem

Use RStudio tool to import Excel file. File is attached:

[iris.xlsx](https://github.com/rstudio/rstudio/files/2746783/iris.xlsx)

![image](https://user-images.githubusercontent.com/12725868/50991733-1494a980-151e-11e9-8344-c012f51e3529.png)

The same situation is with import from text tool:
![image](https://user-images.githubusercontent.com/12725868/50992142-085d1c00-151f-11e9-9a91-4ff856b59926.png)

### Describe the problem in detail

Preview of dataset fails (see print screen), but file is imported successfully.

![image](https://user-images.githubusercontent.com/12725868/50991704-05156080-151e-11e9-8613-c59a48917daa.png)

### Describe the behavior you expected

Correct preview of the dataset.

**Comment by kevinushey** [comment]
I can reproduce this as well, but it also seems to reproduce in RStudio v1.1. Perhaps something has changed in `readxl` that affects some of the assumptions made by RStudio?

**Comment by ronblum** [comment]
For what it's worth, it works on MacOS Mojave Desktop and Red Hat 7.6 Server, so this appears to be a Windows-only issue.

**Comment by kevinushey** [comment]
It didn't work for me on macOS Mojave. @ronblum what version of `readxl` do you have? I see:

```
> packageVersion("readxl")
[1] '1.2.0'
```

**Comment by kevinushey** [comment]
It appears the underlying issue may be caused by the latest version of `tibble`.

**Comment by ronblum** [comment]
Confirmed. It works with `tibble` 1.4.2 but not 2.0.0. (And regarding `readxl`, I tried both 1.1.0 and 1.2.0.)

**Comment by krlmlr** [comment]
Workaround added to _tibble_ 2.0.1, on CRAN now.

**Comment by kevinushey** [comment]
Thanks!
