### ISSUE TITLE
R chunk error: Error in tempfile(pattern = "_rs_rdf_", tmpdir = outputFolder, fileext = ".rdf") :    temporary name too long

### ISSUE THREAD

**Issue by Fredo-XVII** [rstudio/rstudio#4140]
### Intro
Hello, I searched for this error and no issues came up...if this is a duplicate, sorry about that, please point 
me to the correct issue.  I have been getting this error lately, I think since I updated to the 1.1.456 release.  I did as instructed below. I installed the preview version of RStudio 1.2, and I also upgraded my RStudio to 1.1463.  But all the versions produce the same error.

### System details

    RStudio Edition : 
    RStudio Version : 1.1.456, 1.1.463, 1.2 preview.
    OS Version      : Windows 10
    R Version       :  3.5.1

### Reproduce the Problem
This post on StackOverFlow created an example and posted the error just as I have it, including the traceback.  He was using tidy and broom packages, I am using the psych::describeBy() in the R chunk that is creating the dataframe.  I can't share my code from work unfortunately. 

[StackOverFlow](https://stackoverflow.com/questions/47847275/temporary-name-too-long-error-that-appears-unexpectedly-using-rnotebook)

### Describe the problem in detail
I am creating a data frame with ```psych::describeBy(var, group = list(), mat = TRUE)  %>% as.matrix() %>% tibble::as.tibble()```.   In the next R chunk I am coding ```df %>% head()``` so that I can display it in my Rnotebook html document.  I also tried ```as.data.frame()```, but didn't work.   Instead, I get the error below:

Error in tempfile(pattern = "_rs_rdf_", tmpdir = outputFolder, fileext = ".rdf") : 
  temporary name too long

```
tempdir()
[1] "C:\\Users\\XXX\\AppData\\Local\\Temp\\1\\Rtmpi0h2fG"
```
I tried changing my temp directory with the code below, and that didn't work either:
```
#Sys.setenv(TMP = "C:\\Users\\XXXXX\\AppData\\Local\\Temp\\rtemp")
#Sys.setenv(TEMP = "C:\\Users\\XXXXX\\AppData\\Local\\Temp\\rtemp")
#Sys.setenv(TMPDIR="C:\\Users\\XXXXX\\AppData\\Local\\Temp\\rtemp")
#tempfile(tmpdir=Sys.getenv("TMPDIR")) 
```

### Describe the behavior you expected
I expected that I would get the first 6 rows of the data frame displayed below the R chunk. If I use ```str(df)``` Rstudio displays the structure of the df, so the data frame is being created.  If I type ```df``` into the console I get the tibble displayed for all 14 rows of the summary data. 

```str(df)
> str(df)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	14 obs. of  16 variables:
 $ item    : chr  "1" "2" "3" "4" ...
 $ group1  : chr  "1" "2" "3" "4" ...
 $ group2  : chr  "GRP "GRP " "GRP " "GRP " ...
 $ vars    : chr  "1" "1" "1" "1" ...
 $ n       : chr  "208" "201" "197" "196" ...
 $ mean    : chr  "28.97525" "28.30702" "28.30330" "28.34809" ...
 $ sd      : chr  " 5.170037" " 6.464696" " 7.620389" " 7.499603" ...
 $ median  : chr  "29.62583" "29.83972" "29.46500" "29.43264" ...
 $ trimmed : chr  "29.77938" "29.59771" "29.44402" "29.39012" ...
 $ mad     : chr  "3.3786807" "2.7650490" "2.7844052" "2.5412176" ...
 $ min     : chr  "  5.756944" "-14.648056" "-39.825556" "-41.616944" ...
 $ max     : chr  "35.74694" "35.81333" "35.91167" "35.51806" ...
 $ range   : chr  " 29.99000" " 50.46139" " 75.73722" " 77.13500" ...
 $ skew    : chr  "-2.534145" "-3.269931" "-5.687959" "-6.441486" ...
 $ kurtosis: chr  " 7.700241" "12.938048" "41.171007" "49.616440" ...
 $ se      : chr  "0.3584776" "0.4559845" "0.5429302" "0.5356859" ...
```

# Extra Output

1. The output of sessionInfo() 
```
> sessionInfo() 
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tidyquant_0.5.5            quantmod_0.4-13            TTR_0.23-4                 PerformanceAnalytics_1.5.2 xts_0.11-2                
 [6] zoo_1.8-4                  sqldf_0.4-11               RSQLite_2.1.1              gsubfn_0.7                 proto_1.0.0               
[11] odbc_1.1.6                 RODBC_1.3-15               colorRamps_2.3             plotly_4.8.0               RColorBrewer_1.1-2        
[16] data.table_1.11.8          forcats_0.3.0              purrr_0.2.5                readr_1.1.1                tidyr_0.8.2               
[21] tibble_1.4.2               ggplot2_3.1.0              tidyverse_1.2.1            feather_0.3.1              reshape2_1.4.3            
[26] dtplyr_0.0.2               stringr_1.3.1              lubridate_1.7.4            dbplyr_1.2.2               dplyr_0.7.8               
[31] RPostgres_1.1.1           

loaded via a namespace (and not attached):
 [1] httr_1.3.1        bit64_0.9-7       jsonlite_1.5      viridisLite_0.3.0 modelr_0.1.2      assertthat_0.2.0  blob_1.1.1       
 [8] cellranger_1.1.0  yaml_2.2.0        pillar_1.3.0      backports_1.1.2   lattice_0.20-38   quadprog_1.5-5    glue_1.3.0       
[15] chron_2.3-53      digest_0.6.18     rvest_0.3.2       colorspace_1.3-2  htmltools_0.3.6   plyr_1.8.4        psych_1.8.10     
[22] pkgconfig_2.0.2   broom_0.5.0       haven_1.1.2       scales_1.0.0      withr_2.1.2       lazyeval_0.2.1    cli_1.0.1        
[29] mnormt_1.5-5      magrittr_1.5      crayon_1.3.4      readxl_1.1.0      memoise_1.1.0     nlme_3.1-137      xml2_1.2.0       
[36] foreign_0.8-71    tools_3.5.1       hms_0.4.2         munsell_0.5.0     bindrcpp_0.2.2    compiler_3.5.1    rlang_0.3.0.1    
[43] grid_3.5.1        rstudioapi_0.8    htmlwidgets_1.3   tcltk_3.5.1       gtable_0.2.0      curl_3.2          DBI_1.0.0        
[50] R6_2.3.0          knitr_1.20        bit_1.1-14        bindr_0.1.1       Quandl_2.9.1      stringi_1.2.4     parallel_3.5.1   
[57] Rcpp_1.0.0        tidyselect_0.2.5 
```

2. The R code in question
```{r}
df
df %>% head()
```

3. A diagnostics report:

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2747070/diagnostics-report.txt)

# Conclusion
Thank you!!!

**Comment by kevinushey** [comment]
Do you have a very long Windows username?

If you want to change your temporary directory, it will have to be done my modifying Windows environment variables:

https://www.computerhope.com/issues/ch000549.htm

You could also try setting it in a `.Renviron` file, e.g.

``` r
dir.create("C:\\tmp")
writeLines("TMPDIR = 'C:\\tmp'", con = "~/.Renviron")
```

which would then ensure the temporary directory is set for future R sessions.

**Comment by kevinushey** [comment]
Sorry. The temporary directory might've been a red herring, since the path is generated by:

```
Error in tempfile(pattern = "rs_rdf", tmpdir = outputFolder, fileext = ".rdf") :
```

Note that we're trying to create a temporary file in `outputFolder`, whatever that might be. I believe it's for a path within the project's `.Rproj.user` folder, so if your project name happened to be very long or in a very nested path you might see this error.

What is the output of `getwd()` in your project?

**Comment by Fredo-XVII** [comment]
You might be on to something.  Because of one drive, we do have a ridiculously long path/folder name.  I will get back to you when I get back to my computer on getwd().

**Comment by Fredo-XVII** [comment]
@kevinushey So I ran `nchar(getwd())` and I got 138 characters.  In the cache folder name had a character count up to 197 characters.  Still, I thought I had like 256 characters on a windows machine.  In any case, the length is a combination of onedrive and github.  

One other thing, I was able to get the result that I was expecting once I filtered down the dataset to 1 specific group.  In other words, `df %>% filter(group == 1) %>% head()`.  Which seems weird, should it have given me an error as well?  Why does the size of the data frame matter? I also turned the cache option off, and I deleted all the items in the folder named cache.

Let me know if you want me to close this issue, or you are interested in researching it. Thanks!

@ronblum I am sorry that I can't give you a better example, but since it involves work stuff, i can't give you a more concrete example.

**Comment by Fredo-XVII** [comment]
So I found one of the temporary files that are being created with "_rs_rdf_" pattern and the file path had 239 characters in it.  You are correct, they are located in the .Rproj.user folder under /shared/.....

Is there a way to change this limitation?  Is there a work around?

**Comment by kevinushey** [comment]
There aren't any clean workarounds, but there are a few things you could try:

1. Enable 'long paths' in Windows, as per https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/;

2. Try creating a [junction point](https://en.wikipedia.org/wiki/NTFS_junction_point) to your OneDrive project, with that junction living in some local drive with a smaller name, and then open the project from that directory.

**Comment by Fredo-XVII** [comment]
I confirmed that I had the long path set to 1 before I wrote this issue.  And I am not confident enough to build another drive on my work computer.  I think I am going to try to use as small project titles and file names going forward to try to avoid this issue.  

Thanks all for you help!

Alfredo
