### ISSUE TITLE
RStudio freezes when installing package from source

### ISSUE THREAD

**Issue by leungi** [rstudio/rstudio#4141]
This only happens when install packages that require building from source.

All is fine right up to `** testing if installed package can be loaded`, where RStudio will freeze, and the only way is to close RStudio and reopen. Stopping or pressing `Esc` key will uninstall package, but shutting down RStudio will not.

```
> install.packages("genderdata", repos = "http://packages.ropensci.org")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
installing the source package ‘genderdata’

trying URL 'http://packages.ropensci.org/src/contrib/genderdata_0.5.0.tar.gz'
Content type 'application/gzip' length 16311525 bytes (15.6 MB)
downloaded 15.6 MB

* installing *source* package 'genderdata' ...
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'genderdata'
    finding HTML links ... done
    ipums_usa                               html  
    kantrowitz                              html  
    napp                                    html  
    ssa_national                            html  
    ssa_state                               html  
** building package indices
** testing if installed package can be loaded
*** arch - i386

## RStudio will get stuck here, BUT the package did install successfully
```

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1206
    OS Version      : Windows 10 x64 (build 17134)
    R Version       : 3.5.1

**Comment by kevinushey** [comment]
Does this occur for _all_ packages you attempt to install from source, or just this particular one?

Did you try installing Rtools as recommended in the install output?

> WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
> https://cran.rstudio.com/bin/windows/Rtools/

**Comment by kevinushey** [comment]
I just tried installing that package on my Windows VM and it installed without issue.

**Comment by leungi** [comment]
Thanks for prompt reply @kevinushey; this happens to all packages that need compilation from source.

I did install a suitable Rtools for R version.

Any other way to debug?

```
> pkgbuild::find_rtools()
[1] TRUE
```

**Comment by kevinushey** [comment]
My best guess is that you have something in a startup profile (e.g. `~/.Rprofile`) that's somehow impeding package installation when in RStudio.

**Comment by leungi** [comment]
@kevinushey: tried your suggestion and it solved the problem.

My `~/.Rprofile` had a line to source a script, and uncommenting this line in the script solves the issue:
`pacman::p_load(ROracle, DBI, RJDBC, odbc, dbplyr, tictoc)`.

I suspect one of the them is the troublemaker, but we'll leave the investigation for now.

Thanks again!
