### ISSUE TITLE
Suggestion: don't change line indentation when pasting at the start of a line

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4145]
I some times find myself in a situation in which I need to change some lines in order to refer to elements in a list rather than to variable names, which I do by copy-pastying `list[["` in front of them. However, doing this in a row will insert extra spaces whenever I put it at the beginning of a line if the previous statement hasn't yet received the closing brackets. The following gift illustrates why this behavior is annoying:
![autoinserted_space](https://user-images.githubusercontent.com/11860098/51042933-216cd800-15c6-11e9-9efd-79a93d4b02de.gif)

Would be nice if it wouldn't move the line indentation when pasting at the beginning of it.

**Comment by jmcphers** [comment]
The best way to do this is to use multiple cursors. Position the cursor at the beginning of the line, then press Alt+Shift+Down to create another cursor. Keep going to the bottom of your block, then just type `out[[` once and it will appear on every line. Does that do what you want?

We will also have separate paste/paste with indent commands in RStudio 1.3 (see https://github.com/rstudio/rstudio/issues/4145).
