### ISSUE TITLE
Multi-line R statements in Rnw code chunks are skipped when running line by line

### ISSUE THREAD

**Issue by basilrabi** [rstudio/rstudio#4148]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1233
    OS Version      :  Fedora 29
    R Version       :  3.5.1

### Steps to reproduce the problem

Put this code in a code chunk in an Rnw file:
```R
library(dplyr)
data(iris)
a <- lapply(iris,
            function(x) {as.character(x)})
cat("Hello")
```
Put the cursor on the first line then run line-by-line either using `Ctlr+Enter` or clicking `Run Selected Line(s)`

### Describe the problem in detail

The line:
```
            function(x) {as.character(x)})
```
is skipped by `Ctrl+Enter` or `Run Selected Line(s)`

The console output when running line-by-line is:
```
> library(dplyr)
> data(iris)
> a <- lapply(iris,
+ cat("Hello")
+
```

### Describe the behavior you expected

The expected behaviour is similar to `.R` and `.Rmd` files. The console output must be:
```
> library(dplyr)
> data(iris)
> a <- lapply(iris,
+             function(x) {as.character(x)})
> cat("Hello")
Hello
>
```

**Comment by kevinushey** [comment]
Looks like this is a regression in v1.2.
