### ISSUE TITLE
autocompletion error in console for empty string

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4149]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1223
    OS Version      : macOS 10.14.2
    R Version       : 3.5.2

### Steps to reproduce the problem

In an R document, execute the code:

``` r
empty <- ""
```

Then, try typing:

``` r
empty()
```

### Describe the problem in detail

An error is emitted to the console:

> Error in args(obj) : attempt to use zero-length variable name

### Describe the behavior you expected

No error.

**Comment by ronblum** [comment]
@kevinushey For what it's worth, I'm unable to reproduce this on MacOS (though I'm on 10.14.3 beta) or Windows 10.
