### ISSUE TITLE
Files saved as UTF-8 are not sourced correctly

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4156]
**Steps to reproduce:**
* Create a `.R` file with non-latin characters
* Save file as UTF-8 through `File` → `Save with Encoding...`
* Source file from the button at the top-right of the editor

**Expected behavior:**
File should be sourced without encoding errors

**Actual behavior:**
Always get an error like the following:
```r
Error in source(<file_name>, encoding = "UTF-8") : 
  <file_name>:1:25: unexpected INCOMPLETE_STRING
4:         fdgf
5:         
                           ^
In addition: Warning message:
In readLines(file, warn = FALSE) :
  invalid input found on input connection '<file_name>'
```

Which does not happen when  manually running `source(file)` **without** the `encoding = "UTF-8"` part.

**Setup:** Rstudio 1.2.1139, R 3.5.1, running on windows 10

Example file that will create a problem:
```r
this_is_unicode_text <- "
gfdfgdfgdfggf 
    fddfg
        fdgf
        павапвапвапап
        фацуацуауца
"
```

**Comment by ronblum** [comment]
@david-cortes As always, thank you for reporting the issue!

Confirmed on Windows 10 using RStudio Desktop 1.2.1228-2. In addition, when the file is closed and reopened, the contents are garbled:
```
this_is_unicode_text <- "
gfdfgdfgdfggf 
    fddfg
        fdgf
        Ð¿Ð°Ð²Ð°Ð¿Ð²Ð°Ð¿Ð²Ð°Ð¿Ð°Ð¿
        ÑÐ°ÑÑÐ°ÑÑÐ°ÑÑÐ°
"
```

This is not an issue on MacOS 10.14 Mojave.

**Comment by kevinushey** [comment]
Thanks for the bug report!

The problem here is that `source(..., encoding = "UTF-8")` does _not_ mean "source this file, assuming the encoding is UTF-8"; rather, it means "source this file, assume it's in the system native encoding, but convert to UTF-8 post-hoc."

In other words, RStudio is emitting the wrong command here. Instead, we need to do something like:

``` r
eval(parse("~/scratch/oni.R", encoding = "UTF-8"))
```

**Comment by kevinushey** [comment]
For your own use case, if you truly need multibyte characters in your document, they should either be:

1. Characters that can be expressed in the current system encoding, or
2. Unicode-escaped; e.g. in the source document as `\uabcd` with the appropriate hex code for each character.

**Comment by jmcphers** [comment]
Not too long after this issue was opened, it became possible to use UTF-8 as the system code page in Windows 10. 

https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.

**Comment by kevinushey** [comment]
Some examples:

```
code <- 'print("ф")'
writeLines(enc2utf8(code), con = "script.R", useBytes = TRUE)

source("script.R")
source("script.R", encoding = "UTF-8")
eval(parse("script.R", encoding = "UTF-8"))
```

giving

```
> code <- 'print("ф")'
> writeLines(enc2utf8(code), con = "script.R", useBytes = TRUE)
> 
> source("script.R")
[1] "Ñ„"
> source("script.R", encoding = "UTF-8")
Error in source("script.R", encoding = "UTF-8") : 
  script.R:1:7: unexpected INCOMPLETE_STRING
1: print("
          ^
In addition: Warning message:
In readLines(file, warn = FALSE) :
  invalid input found on input connection 'script.R'
> eval(parse("script.R", encoding = "UTF-8"))
[1] "ф"
```

It's sort of ugly that the "right" solution involves avoiding `source()` altogether though.

**Comment by mikebessuille** [comment]
it's not clear whether we should fix this in RStudio (with a hack to workaround the issue in R), or if it should be logged as a bug in R.

**Comment by kevinushey** [comment]
In general, the unfortunate truth right now for R on Windows is that you should restrict yourself to the characters representable in your native locale. Hopefully this will change when (if) R switches to the UCRT, which will imply native support for UTF-8 in R itself.

**Comment by david-cortes** [comment]
@mikebessuille I don't currently have any setup in which I could try it, sorry.

**Comment by david-cortes** [comment]
@mikebessuille : actually, I realized that I did have an option marked as beta to set UTF-8 encoding in the windows control panel. However, the file still didn't source correctly, and the last example from Kevin also printed a spanish N instead of "fi".

**Comment by kevinushey** [comment]
This issue is likely resolved in R 4.2.

**Comment by mikebessuille** [comment]
@david-cortes would you mind testing this with R4.2 and the latest daily for Spotted Wakerobin?

**Comment by david-cortes** [comment]
Working correctly now.
