### ISSUE TITLE
Only one RStudio graphics device is permitted

### ISSUE THREAD

**Issue by jiajiaybyb** [rstudio/rstudio#4157]
Hi, I am trying to use R package "survminer" tp draw survival plot. The example I am trying is this: 

``` r
# Fit survival curves
require("survival")
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# List of ggsurvplots
require("survminer")
splots <- list()
splots[[1]] <- ggsurvplot(fit, data = lung, risk.table = TRUE, ggtheme = theme_minimal())
splots[[2]] <- ggsurvplot(fit, data = lung, risk.table = TRUE, ggtheme = theme_grey())

# Arrange multiple ggsurvplots and print the output
arrange_ggsurvplots(splots, print = TRUE,
  ncol = 2, nrow = 1, risk.table.height = 0.4)
```

The output shows two identical sub panels which they should not. The warning msg was:

> 'Warning message: In (function ()  : Only one RStudio graphics device is permitted' 

I think this warning msg was b/c RStudio does not allow more than one graphic device. Just wonder is there any way we could have the correct plot shows on the right panel? Thanks a lot.

**Comment by jmcphers** [comment]
No response in over a year so closing.
