### ISSUE TITLE
R Studio crashing when opening dataframe (Ubuntu)

### ISSUE THREAD

**Issue by boemboem161** [rstudio/rstudio#4158]
Hej,

i'm trying to analyze twitter data with the packages rtweet. When I collect twitter data and put it in dataframe (e.g 100 obersavtion in 87 variables, which is not that much) and then try to open the dataframe my r studio is crashing. Does anybody has an idea to solve the problem

I have 16gb of memory and I am using ubuntu 18.4 (on a Mac) 

That's the information from the log lines from rsession-username.log
```
14 Jan 2019 15:28:44 [rsession-boemboem] ERROR system error 2 (No such file or directory) [path=]; OCCURRED AT: rstudio::core::Error rstudio::r::session::discoverR(rstudio::r::session::RLocations*) /home/ubuntu/rstudio/src/cpp/r/session/RDiscovery.cpp:62; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1841
14 Jan 2019 15:37:51 [rsession-boemboem] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1239
```
Thats the logines from rdesktop.log 

`14 Jan 2019 14:28:33 [rdesktop] ERROR system error 104 (Die Verbindung wurde vom Kommunikationspartner zurückgesetzt); OCCURRED AT: void rstudio::core::http::AsyncClient<SocketService>::handleReadStatusLine(const rstudio_boost::system::error_code&) [with SocketService = rstudio_boost::asio::basic_stream_socket<rstudio_boost::asio::local::stream_protocol>] /home/ubuntu/rstudio/src/cpp/core/include/core/http/AsyncClient.hpp:375; LOGGED FROM: void rstudio::desktop::NetworkReply::onError(const rstudio::core::Error&) /home/ubuntu/rstudio/src/cpp/desktop/DesktopNetworkReply.cpp:288`

**Comment by ronblum** [comment]
@boemboem161 Thanks for reporting this. A few questions:
1) Can you provide the product and environment you're working with?
    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 
2) Have you tried this in R, outside of RStudio?

Thanks!

**Comment by boemboem161** [comment]
1)    RStudio Version: 3.5.2
    OS Version: Ubuntu 18.04.1 LTS

```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu
```  
2) Good point with r, I put my synthax in r and it works well with r
3) yes by opening i mean View

**Comment by ronblum** [comment]
@boemboem161 I tried replicating this by creating a simple 87 x 100 data frame:
```
m <- data.frame(matrix("12345678901234567890123456789012345678901234567890", ncol = 87, nrow = 100))
View(m)
```
I couldn't reproduce the issue, though—the data viewer displayed correctly. (With RStudio 1.2.1287 running on Ubuntu 18.04 in a MacOS VM). 

A few more questions:
1) Does the problem occur with fewer columns? For example, `View(mtcars)` or `View(iris3)`.
2) Just to check—are you using the [current RStudio Preview](https://www.rstudio.com/products/rstudio/download/preview/) or one of the [latest 1.2 daily development builds](https://dailies.rstudio.com/), or 1.1?

**Comment by jmcphers** [comment]
No response in over a year, so closing.
