### ISSUE TITLE
SQL preview errors after clearing environment

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4160]
### System details

    RStudio Edition : All
    RStudio Version : 1.2.1226 

### Steps to reproduce the problem

1. Create a connection to a database named e.g. `con`
2. Open the list of tables in the database
3. Clear the global environment (removing the `con` object)
4. Click the SQL button and provide a name for the script

### Describe the problem in detail

The following error appears:

*An unknown error occurred: argument "statement" is missing, with no default*

![image](https://user-images.githubusercontent.com/470418/51136276-ee5a5c80-17f0-11e9-8bec-4994bc6cdaf8.png)

It's not at all clear to the user where this error is coming from or why they're seeing it. 

It may be due to the missing `conn` argument here:

![image](https://user-images.githubusercontent.com/470418/51136366-282b6300-17f1-11e9-95d9-cec13a087a82.png)

### Describe the behavior you expected

There are a few ways we could ensure this error doesn't happen. 

- Detect that there's no connection object, and disable the button, or
- Show a more meaningful error, or
- Create a .sql file which does not include the `-- !preview` magic comment at all, or
- Treat connections as disconnected when their associated environment object is removed.

**Comment by kevinushey** [comment]
The `-- !preview conn=` bit is indeed the issue, and the error is thrown from the `.rs.rpc.preview_sql()` R RPC function. We could further validate that we have a valid chunk of code here:

https://github.com/rstudio/rstudio/blob/81fea19f1588dcaba78dd997948da64dd42a4ea7/src/cpp/session/modules/SessionDataPreview.R#L16-L26

**Comment by kevinushey** [comment]
The error message is a little more clear now:

<img width="434" alt="screen shot 2019-01-23 at 4 32 31 pm" src="https://user-images.githubusercontent.com/1976582/51646225-8c0a0600-1f2c-11e9-90cc-78b2c99ee5da.png">

Should we consider anything more here?

**Comment by jmcphers** [comment]
No, I think that's sufficient. Thanks for knocking that out!
