### ISSUE TITLE
Commenting out doing the opposite when selecting extra empty line

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4163]
**Steps to reproduce:**
* Select some multi-line text with comment lines, having empty lines separating the selected text from what’s next
* Comment it out (Ctrl + Shift + C)
* Select the text again, but add one empty line at the bottom
* Try to uncomment it with Ctrl + Shift + C

**Expected behavior:**
Should uncomment the selected text, leaving it as it was before commenting it out

**Actual behavior:**
As long as the empty line at the end is selected, text is commented twice.

**Setup:** Rstudio 1.2.1139, R 3.5.1, running on windows 10

Example gift showing the undesired behavior:
![not_uncommented](https://user-images.githubusercontent.com/11860098/51175884-31d1cb00-18c4-11e9-8dcc-e30004912701.gif)

**Comment by dfalty** [comment]
Verified fixed 1.3.673
