### ISSUE TITLE
New Project:Package output not the same as usethis::create_project()

### ISSUE THREAD

**Issue by davidski** [rstudio/rstudio#4164]
Under RStudio version 1.2.1206, the GUI New Project::Package output does not create a default `.gitignore` file, though the `usethis::create_project()` function does. The `usethis` version is my preference and should probably be leveraged by RStudio as well.

**Comment by ronblum** [comment]
@davidski Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.

**Comment by davidski** [comment]
RStudio 1.4 looks to create a .gitignore file now (and it looks more complete than the usethis version now 😆 ). Closing this out.
