### ISSUE TITLE
[Windows] Mouse pointer becomes invisible when new tabs open in top-right pane

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4168]
**Steps to reproduce:**
* Do something that would trigger a new tab being inserted in the top-right pane that contains e.g. `Environment` and `History`, such as creating a new SQL connection (when none is present), or a new R presentation
* Wait until pane is created

**Expected behavior:**
Mouse should work as normal

**Actual behavior:**
In windows 10 (but not in linux), mouse pointer disappears in the screen in which RStudio was showing, but is visible when moving it to another screen, remaining invisible until the moment one presses `Esc` (then it reappears)

**Setup:** RStudio 1.2.1237, R 3.5.1, running on windows 10

**Comment by ronblum** [comment]
@david-cortes Is this still an issue in the most recent builds? I'm unable to reproduce it, using RStudio Desktop on 1.2.1275, R 3.5.2, Windows 10.

**Comment by david-cortes** [comment]
@ronblum : seems to have been somehow fixed in the latest builds.

**Comment by ronblum** [comment]
Thanks, @david-cortes! I'm glad it's working now. But if the behavior returns, please let us know.
