### ISSUE TITLE
Font substitution in editor breaks cursor positioning

### ISSUE THREAD

**Issue by gdevenyi** [rstudio/rstudio#4170]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Ubuntu 14.04.5
    R Version       : 3.5

### Steps to reproduce the problem
1. Choose a font for the editor
2. Close rstudio and make the font unavailable (uninstall etc)
3. Reopen rstudio

### Describe the problem in detail
The font set for rstudio is no longer available, so a substitution is done either by fontconfig or rstudio (not sure which).

Cursor positioning is now broken in the editor: clicking to a specific position does not place the cursor in the right place.

### Describe the behavior you expected

Correct positioning

**Comment by jmcphers** [comment]
Is the substituted font monospace? (this is a known issue with variable width fonts)

We hope to address this by bundling a failsafe font inside RStudio in a future release. The issue's being tracked here:

https://github.com/rstudio/rstudio/issues/4134

**Comment by kevinushey** [comment]
Also note that this particular manifestation of the issue should be fixed in the v1.2 preview.

**Comment by gdevenyi** [comment]
I don't know whether or not the substitution was monospace, since I didn't have control of that. The original set font was monospace
