### ISSUE TITLE
Cannot view list that contains vector of length zero

### ISSUE THREAD

**Issue by beckni** [rstudio/rstudio#4173]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.1.463
    OS Version      : Windows 7
    R Version       : 3.5.2

### Steps to reproduce the problem
When I enter
`View(list(a = vector(mode = 'numeric', length = 0), b = c(1,2)))`
the result is
`Error in if (more || nchar(output) > 80) { : 
  missing value where TRUE/FALSE needed`

**Comment by kevinushey** [comment]
Thanks! This will be fixed in the next [daily builds](https://dailies.rstudio.com).

**Comment by dfalty** [comment]
Verified fixed 1.2.1312
