### ISSUE TITLE
Refresh button in Viewer has no effect

### ISSUE THREAD

**Issue by beckni** [rstudio/rstudio#4174]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.463
    OS Version      : Windows 7
    R Version       : 3.5.2

### Steps to reproduce the problem
Enter
```
test <- list(1,2,3)
View(test)
test <- list(1,2,3,4)
```
Now, hit the refresh button in the viewer.

### Describe the problem in detail
The viewer doen't show the new values when the refresh button is clicked.

### Describe the behavior you expected
I expected the viewer to reload the data.

**Comment by kevinushey** [comment]
Fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/).
