### ISSUE TITLE
invalid version check by installBuildTools on Mac OS

### ISSUE THREAD

**Issue by bhogan-mitre** [rstudio/rstudio#4175]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.2.1237
    OS Version      :  macOS Mojave 10.14.2
    R Version       :  3.5.2

### Steps to reproduce the problem

```
> getOption("buildtools.check", NULL)("Building R package from source")
[1] FALSE
```

### Describe the problem in detail

I believe that I have build tools installed, with XCode and the command line interface.  
```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

However, `rstudioapi::buildToolsCheck()` returns `FALSE`, and I am unable to use devtools to install a package that needs compiling.

`checkBuildTools` is [testing](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/SessionBuild.R#L40) for `identical(.Platform$pkgType, "mac.binary.mavericks")`

However, `mac.binary.mavericks` is not a value that is ever obtained.

```
> .Platform$pkgType
[1] "mac.binary.el-capitan"
```

My real issue is with [`installBuildTools`](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/build/SessionBuild.cpp#L2021:L2045) always just showing the [CNET page](https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/).  Since this is testing `isOSXMavericks()`, I suspect the trouble may be related to the bug mentioned above.

I have followed the suggestions from @jimhester and @kevinushey here: https://github.com/r-lib/devtools/issues/1879, and still had no luck.

Is there a way to test the values returned by `module_context::isOSXMavericks()` and `module_context::hasOSXMavericksDeveloperTools()`?

### Describe the behavior you expected

I expect to be able to use `devtools::install_github`, and install packages that need compiling.

**Comment by bhogan-mitre** [comment]
Clarifying that the bug is visible in an RStudio session:

```
> getOption("buildtools.check")
function (action) 
{
    if (identical(.Platform$pkgType, "mac.binary.mavericks")) {
        .Call("rs_canBuildCpp")
    }
    else {
        if (!.Call("rs_canBuildCpp")) {
            .rs.installBuildTools(action)
            FALSE
        }
        else {
            TRUE
        }
    }
}
```

**Comment by kevinushey** [comment]
This works on my Mojave machine:

```
> getOption("buildtools.check", NULL)("Building R package from source")
[1] TRUE
```

Have you installed the system headers for Mojave? https://stackoverflow.com/questions/53169970/where-are-the-c-headers-in-macos-mojave

**Comment by kevinushey** [comment]
(I saw that was recommended on the linked discussion in `devtools` but wanted to confirm)

**Comment by bhogan-mitre** [comment]
As noted in https://github.com/r-lib/pkgbuild/issues/63, the culprit for me was a lingering `~/.R/Makevars` file from an old Xcode install.  This [SO post](https://stackoverflow.com/a/49268991/4425601) had the very simple suggestion to delete that file.

So now I get:
```
> rstudioapi::buildToolsCheck()
[1] TRUE
```

I'll leave this issue open for now, as I still think it is bizarre to be checking `identical(.Platform$pkgType, "mac.binary.mavericks")` when there is no chance that could be true.

**Comment by hrbrmstr** [comment]
I have full Xcode 12.0 beta installed and this has been happening consistently for me:

```shell
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ sw_vers -productVersion
11.0
```

```r
RStudio.Version()$version
## [1] ‘1.4.687’
```

If in RStudio and I, say, try to do:

```r
install_github("r-lib/vctrs")
```

I get:

![image](https://user-images.githubusercontent.com/509878/89713924-02345900-d969-11ea-8e4b-b6f039ffeafe.png)

plus:

```r
rstudioapi::buildToolsCheck()
## [1] FALSE
```

If I drop to iTerm and startup R the install works fine:

```r
install_github("r-lib/vctrs")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo r-lib/vctrs@master
   checking for file ‘/private/var/folders/r_/8gkkj9d57739wtr_wn1gv_hm0000gn/T/Rtmp34UCc4/remotes26b54402cc64/r-lib-vctrs-1b3cd7c/DESCRIPTION’ ✔  checking for file ‘/private/var/folders/r_/8gkkj9d57739wtr_wn1gv_hm0000gn/T/Rtmp34UCc4/remotes26b54402cc64/r-lib-vctrs-1b3cd7c/DESCRIPTION’
─  preparing ‘vctrs’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
…
```

And, `Makevars` is:

```shell
cat ~/.R/Makevars
CC=clang
CXX=clang++
```

Of note (and, unsurprisingly?):

```
pkgbuild::check_build_tools(debug = TRUE)
```

fails miserably as well (and doesn't debug anything).

but (surprisingly?)

```r
pkgbuild::has_compiler(debug = TRUE)
## Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB \
  foo.c
## clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c foo.c -o foo.o
## clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o foo.so foo.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
##  
## [1] TRUE
```

so it _kinda_ looks like some sort of "perhaps RStudio should really dig into this and fix it universally" effort might be needed.

If I can carve out any time I'll see what `src/cpp/session/modules/build/SessionBuild.cpp` is doing to come up with the errant assertion about no build tools.

**Comment by kevinushey** [comment]
This is where RStudio detects if macOS command line tools are installed:

https://github.com/rstudio/rstudio/blob/ece340b7ce3e40d7376053b567c98001165ed3ad/src/cpp/session/SessionModuleContext.cpp#L2735-L2742

Does this need to change to accommodate macOS Big Sur? (Maybe we need to be running `xcode-select -p` to allow the use of "any" set of macOS developer tools?)

Does `xcode-select --install` help here?

**Comment by hrbrmstr** [comment]
It should probably check for either the straight command line tools or the ones that come along for the ride with Xcode 12, now (for the first few months of Big Sur there was no separate command line tools install and the ones that come with Xcode, now, are the same, so no need for another installation if one has full Xcode).

**Comment by contefranz** [comment]
The problem is still here. I am experiencing what @hrbrmstr did. My C++ code has no problems and I can install other packages. For some reason, I cannot build my own package. I have everything installed in terms of both Xcode and Command Line Tools. Can you suggest or hint what is wrong? 

This is my current R session info. 

``` r
sessionInfo()
#> R version 4.0.4 (2021-02-15)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.7
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.27     assertthat_0.2.1  magrittr_2.0.1    reprex_1.0.0     
#>  [5] evaluate_0.14     highr_0.8         stringi_1.5.3     rlang_0.4.10     
#>  [9] cli_2.3.1         rstudioapi_0.13   fs_1.5.0          rmarkdown_2.7    
#> [13] tools_4.0.4       stringr_1.4.0     glue_1.4.2        xfun_0.22        
#> [17] yaml_2.2.1        compiler_4.0.4    htmltools_0.5.1.1 knitr_1.31
```

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
