### ISSUE TITLE
[Windows] Double-clicking on single-letter variable selects whole statement

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4177]
**Steps to reproduce:**
* Write some text in which there is a single-letter variable separated by a space from the following symbol
* Double-click that variable

**Expected behavior:**
Should select the single-variable letter

**Actual behavior:** on windows 10 (but not on linux), selects the whole statement.

Example:
```r
problem.function <- function(x){
    a = another.function(h = 1)
}
```
If I double-click on `h` in linux, it will select `h`, but on windows, it will select `h = 1`

**Comment by ronblum** [comment]
Reproduced on MacOS 10.14.3 Mojave. Also:
1) The problem only occurs if the cursor precedes the variable. If it comes after, only the variable is highlighted.
2) If there is a space between the open parens and the variable, only the double-clicked variable is highlighted.
```
a = another.function( h = 1)
```
3) The statement is highlighted even if there are multiple input variables, e.g.
```
a <- function(h = 1, j)
```
4) For a function with multiple variables, the problem only occurs with the first variable, which like (1) touches the opening parens. Double-clicking on other variables, such as `j` in the code in (3), is not a problem.

**Comment by david-cortes** [comment]
Small update: this also happens with two-letter variables.

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.
