### ISSUE TITLE
Prompts for Git Username and Email

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#4179]
### System details

    RStudio Edition : Desktop/Server/Cloud
    RStudio Version : 1.2.1114
    OS Version      : macOS/Ubuntu 16.04 LTS
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Have unset `git` credentials for `user.name` and `user.email`
1. Create a new RStudio Project backed by a git repo.
1. Attempt to commit the skeleton files (e.g. stage and then write commit message)
1. Receive notice that `git` credentials are not present.

### Describe the problem in detail

Those unfamiliar with `git` immediately attempt to write commits without identifying themselves. _RStudio_'s git client is problematic as it doesn't easily provide a means to identify themselves within _RStudio_. Furthermore, with `terminal` being disabled on RStudio Cloud, it's difficult to establish credentials. 

![screen shot 2019-01-18 at 9 20 21 am](https://user-images.githubusercontent.com/833642/51395406-6337da00-1b02-11e9-8f67-99dae283f8e1.png)

### Describe the behavior you expected

It would be nice to provide an option away from the traditional prompt. In particular, if possible, could there be separate prompts or direction to a new screen on the `git` client for registration. 

> *** Please tell me who you are.
> 
> Run
> 
> ```bash
> git config --global user.email "you@example.com"
> git config --global user.name "Your Name"
> ```
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: empty ident name (for <rstudio-user@a54136f278c2.(none)>) not allowed

**Comment by ronblum** [comment]
@coatless Thanks for the suggestion. At times, I've ended up in the same situation when starting with a new OS instance. We'll review this as we continue development of RStudio.

**Comment by jennybc** [comment]
I know RStudio cannot rely on an external package for this, but re: workarounds for cloud, note that usethis does provide support for setting git config in the R Console:

https://usethis.r-lib.org/reference/use_git_config.html

``` r
use_git_config(user.name = "Jane", user.email = "jane@example.org")
```

**Comment by coatless** [comment]
@jennybc `usethis`  is a bit of a high dependency cost for a wrapper around `git2r::config()`. Though, the wrapper significantly improves UX and I'm a huge fan of it for package creation. Having said this, I felt the tradeoff, especially for the introductory sections, is a bit too high.

I brainstormed a few alternative here: 

- RStudio Cloud Project: https://rstudio.cloud/project/179177 
- Image examples: https://twitter.com/axiomsofxyz/status/1086455524235927554

(Notably, writing the `~/.gitconfig`, using `git2r::config()`, `system()`, and the `bash` engine in _R_ Markdown.)

Regarding the tradeoff, the deployment of the `git` fix on the RStudio Cloud for courses involves modifying the Workspace template / base to have `usethis`. Ideally, the base template should provide the right mix of utility and learning opportunities. Placing `usethis` in there isn't ideal in the beginning of a course because:

1. Increases spinup time of subsequent images for students (until we reach packages); 
1. Takes away from students learning about `install.packages()`; and,
1. Overloads RStudio's "package tab" when they are just starting out. 

I'm happy to hear that @ronblum has also experienced the joys of the "Introduce Yourself" dilemma. I also appreciate that RStudio realizes folks using `git` may be newcomers without the traditional CS background. So, any UX improvement would be welcomed with open arms.

**Comment by nordicgit70** [comment]
Issue for git commit with new RStudio server installation: rocker/rstudio-stable:latest.
Updating git (--global) configuration does not resolve the problem.
