### ISSUE TITLE
zoom in and global options

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#4183]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1242
    OS Version      : MacOS 10.14.2 
    R Version       :  3.5.2

### Describe the problem in detail

In class, in need to zoom in to make text legible when it is projected.
The Global Options window then also is compliant with the zoom level.
But when the zoom level is hight, it does not display fully any more, and the bottom part is invisible.
Can RStudio detect this situation and add a scroll bar once the dialog box is too large to be displayed fully?

**Comment by jmcphers** [comment]
Yes, this is a known issue! Currently tracked in https://github.com/rstudio/rstudio/issues/1605 (feel free to comment/upvote)
