### ISSUE TITLE
Option + Delete treats spaces as words

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#4184]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1226
    OS Version      : Mac OSX
    R Version       : 3.5.2

### Steps to reproduce the problem

Enter text in an RMD, press `option + delete`. Note that spaces between words are treated as words or steps as you're deleting words.

### Describe the problem in detail

In most text editors on Mac, when you press option backspace at the end of text like `word |` (where `|` signifies the cursor position, it would delete the prior space and the prior word. In RStudio it only deletes the space. You have to press that key combination again in order to delete `word`.

![option-back](https://user-images.githubusercontent.com/1593639/51430660-6ae8a300-1c16-11e9-8c57-133f69bd279b.gif)

### Describe the behavior you expected

It should have deleted the space AND the previous word.

**Comment by ronblum** [comment]
@trestletech Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

Reproduced on RStudio Desktop 1.2.1242-3 on MacOS Mojave, and compared to a couple of other applications which have the expected behavior.

**Comment by ottadini** [comment]
Same behaviour with RStudio Version 1.1.463 on Win 10, using Ctrl + backspace, or Ctrl + arrows.
