### ISSUE TITLE
Add option to minimize Traceback pane by default

### ISSUE THREAD

**Issue by judytlewis** [rstudio/rstudio#4185]
When a browser() function is executed in my R code, I most often want to view the values of the variables in current environment, but most of the Environment pane is blocked by the automatically expanded Traceback pane. Instead of minimizing the Traceback pane each time, it would be convenient if an option existed in Global Options to minimize this pane by default. The Traceback pane isn't mentioned at all in Global Options --> Pane Layout; the Traceback pane exists, expanded, without any option to choose differently.

**Comment by jmcphers** [comment]
Thanks for writing this up (and showing it to us at the conference!).
