### ISSUE TITLE
RStudio should have official APT repository for Debian and Ubuntu systems

### ISSUE THREAD

**Issue by N0rbert** [rstudio/rstudio#4186]
As a long time RStudio user I have noticed that I should manually download the latest version of RStudio deb-package from [official web-page](https://www.rstudio.com/products/rstudio/download/#download) every time. It occurs on fresh clean installation and on upgrade. This method is convenient for Microsoft Windows, but not for Debian and Ubuntu Linux distributions.

So please really consider to create public repository(ies) for Debian and Ubuntu systems.
It is expected that installation process will be simplified to adding the repository with `sudo add-apt-repository ...` to the `/etc/apt/sources.list` (or specific file in `/etc/apt/sources.list.d/`) and then running `sudo apt update` followed by `sudo apt install rstudio`.

This will save a lot of time and efforts - the packages will be automatically upgraded with next `apt upgrade`. Moreover - the end users will be able to write RStudio installation script for installation on their systems or Dockers.

**Comment by jmcphers** [comment]
This is on our backlog, but as it's not part of RStudio itself it isn't tracked as an RStudio issue (so we'll close it here). 

If you just want to install RStudio inside Docker, you can do that by downloading the .deb inside the container, as is done in the Rocker project:

https://github.com/rocker-org/rocker

**Comment by N0rbert** [comment]
This issue is still actual. Please create APT/deb repository and GPG key for it.

**Comment by N0rbert** [comment]
This issue is still actual. Please create APT/deb repository and GPG key for it.

**Comment by allefeld** [comment]
Pretty please?

**Comment by MatthieuStigler** [comment]
I agree, a ppa for rstudio would be great!

**Comment by raffaem** [comment]
Definitively need an APT repository for RStudio

**Comment by raffaem** [comment]
Related: team is tracking flatpak / snap / AppImage in #3079. It has been two years of thinking and we still don't have neither of APT/Flatpak/Snap. You have to go to RStudio website and download manually.

**Comment by philsf** [comment]
> This is on our backlog, but as it's not part of RStudio itself it isn't tracked as an RStudio issue (so we'll close it here).
> 

Could you please tell where this is being tracked?

**Comment by iago-pssjd** [comment]
> > This is on our backlog, but as it's not part of RStudio itself it isn't tracked as an RStudio issue (so we'll close it here).
> 
> Could you please tell where this is being tracked?

@jmcphers I also would like to know where is this tracked if not as an RStudio issue?

**Comment by N0rbert** [comment]
Currently I install RStudio using 

```
cd /tmp
wget -c https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb
sudo apt-get install -y r-base-dev ./rstudio-latest-amd64.deb
```

but this is a trick. 

Official APT repositories for Debian based systems is still needed to ease `sudo apt update && sudo apt upgrade` procedure for RStudio package.

**Comment by arnaud-feldmann** [comment]
This would definetly be cool and cleaner

**Comment by N0rbert** [comment]
Still needed. Especially with such great tricks like https://github.com/rstudio/rstudio/issues/10026 .

**Comment by mwt** [comment]
I'm creating a new supplementary repo that includes RStudio and other apps that aren't in the repos (like zoom). It's experimental right now, but I'd love to have more testers and feedback before I publicize it. Please send me an email if you're willing to test (email on profile).

**Comment by philsf** [comment]
> I'm creating a new supplementary repo that includes RStudio and other apps that aren't in the repos (like zoom). It's experimental right now, but I'd love to have more testers and feedback before I publicize it. Please send me an email if you're willing to test (email on profile).

@mwt I don't recommend you do this on your own, as you might stumble into licensing issues. This has given major headaches for Java maintainers in the past, and in that particular case the only solution for distributing the software was to create scripts to download + auto-create package + install. You can look it up and see if that situation is similar to the problem you are trying to solve (I am not an expert in licenses and this comment is not legal advice).

Make sure you are allowed to distribute any package you include in your repos before making it public.

**Comment by mwt** [comment]
> @mwt I don't recommend you do this on your own, as you might stumble into licensing issues...

I've contacted the companies that make the proprietary software. The smaller teams have been helpful and supportive.

Companies I can't contact the higher levels of (eg. Zoom) have other unofficial flatpaks and repos (eg. AUR, linuxlite). Customer support at the companies said it was ok too.

I don't understand these laws either, but I think I should be ok.

If you have any other thoughts and concerns, I'd love to hear them, but I don't want to derail this topic with conversation that is not relevant to RStudio. So, I think it might be best to make an issue (or discussion) on mwt/Academic-Repo or email me.

**Comment by KasperThystrup** [comment]
RStudio is such a wonderfull tool, yet ... 6 yrs later and still no official channel?

Could you at the very least give a reason for not wanting to provide Unix users a native approach to installing you software?

**Comment by allefeld** [comment]
Let me upgrade this request and say:

Please create a Debian repository for all Posit software!

Didn't look into the details, but apparently this can be done using GH actions: https://github.com/rpatterson/github-apt-repos
