### ISSUE TITLE
Add Tab for Warnings and Errors from Console

### ISSUE THREAD

**Issue by marianschmidt** [rstudio/rstudio#4187]
When running large chunks of R codes I find it a bit troublesome to either scroll through the R Console output to find where the warning occurred or to use the warnings function to recall recent warnings.

In order to also help new users with their R code I could imagine to add another Tab next to the "History" tab that is called "Errors" or "Warnings" and that collects all the warnings and errors produced in the console. 

Maybe it can be designed similar to the existing "History" tab and when clicking on one entry some help could be shown for the used function where the warning/error occurred and a double click could mean jumping to the R script line where RStudio estimates the error was. Maybe this might feature might be mostly useful to novice R users or users changing from other statistical programming software that are not familiar with advanced debugging features.

**Comment by jmcphers** [comment]
This is a nice idea but has not generated any upvotes or interest in well over a year, so not likely we'll get to it soon.
