### ISSUE TITLE
Hook to control console info

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#4192]
It would be awesome to be able to control the info message at the top of the console:

<img width="239" alt="screenshot 2019-01-22 at 7 49 32 am" src="https://user-images.githubusercontent.com/4196/51539717-5117ad80-1e1a-11e9-84e9-75b2911b8c36.png">

Currently it always shows the working directory, but I'd love to be able to customise it with R code.

**Comment by jmcphers** [comment]
What kinds of things do you want to display there? (wondering if we should have a separate status/state label somewhere or if the things you're thinking of should obscure the working directory by nature)

**Comment by hadley** [comment]
Specifically, I'm most interested in the git branch (which I know is exposed elsewhere, but I never noticed it). In general, much of the stuff exposed by https://github.com/gaborcsardi/prompt would be more usefully displayed in a status bar
