### ISSUE TITLE
Viewer encoding issues

### ISSUE THREAD

**Issue by isteves** [rstudio/rstudio#4193]
Hello, I wasn't able to find a prior issue about this, so my apologies if this is a duplicate...

I've noticed a mismatch between the console output and the Viewer. For example, when Hebrew characters are stored in a tibble, the tibble output looks perfect in the console but jumbled in the Viewer.

<img width="400" alt="encoding" src="https://user-images.githubusercontent.com/25118334/51546108-1e96a080-1e6c-11e9-9ff7-fe91ec3dc2f8.PNG">

Here, I've changed my Windows language settings from English to Hebrew, and it looks a bit different. I guess this means that there's some native encoding interception somewhere along the way.

<img width="250" alt="encoding2" src="https://user-images.githubusercontent.com/25118334/51546517-f8253500-1e6c-11e9-940e-d46125be0a34.PNG">

Is this something that can be easily solved?

    RStudio Edition : Desktop
    RStudio Version : 1.2.1237
    OS Version      : Windows 10
    R Version       : 3.5.1

**Comment by ronblum** [comment]
@isteves Thank you for raising this. The screenshots are very helpful. Would you mind pasting in the code you used to create `df` and `tbl` so I can try to quickly reproduce? Thanks!

**Comment by isteves** [comment]
Oops, my bad!  Here it is:

```r
tbl <- tibble::tibble(food = c("Crêpe", "Spätzle", "Smørrebrød", "חומוס"))

df <- data.frame(food = c("Crêpe", "Spätzle", "Smørrebrød", "חומוס"))
```

**Comment by kevinushey** [comment]
The problem occurs because we call `format()` here:

https://github.com/rstudio/rstudio/blob/b5cb3c30ec590dd0657290f9e40dfca35ee94a25/src/cpp/session/modules/SessionDataViewer.R#L40-L42

and `format()` mangles the encoding of UTF-8 content that's not representable in the current locale:

```
> value <- 'חומוס'
> format(value)
[1] "<U+05D7><U+05D5><U+05DE><U+05D5><U+05E1>"
```

Perhaps we could avoid calling `format()` here for character vectors.

**Comment by ronblum** [comment]
FWIW, everything works fine on RStudio Desktop on MacOS 10.14.3 and Server Pro running on Red Hat 7.6. And now I'm hungry in four languages.

**Comment by kevinushey** [comment]
I think this would only reproduce in non-UTF-8 locales (ie, primarily on Windows)

**Comment by isteves** [comment]
Not sure if you're able to add dependencies, but `utf8::utf8_format()` seems to have the same functionality + UTF-8 support: https://github.com/patperry/r-utf8/blob/master/R/utf8_format.R

**Comment by adisarid** [comment]
Hi, +1 on this one (note that encoding issues appear in viewer and also in console).
I'm seeing a lot of Hebrew encoding issues in the RStudio preview 1.2 version, which were ok on the 1.1.x version. Here is an example file (header duplicates intended to show internal comments errors).

The excel file looks like this:

משתנה|משתנה
---|---
שלום|רב

Download [here](https://drive.google.com/file/d/14V8v5MBW0_lumMX_pYN4BpdkyMRsREWx/view?usp=sharing) (google drive).

There is a default error message which appears when a duplicate name is found but it is not encoded as should be (UTF-8).

```
> bugs <- readxl::read_excel("rstudio_bugs.xlsx")
New names:
* `<U+05DE><U+05E9><U+05EA><U+05E0><U+05D4>` -> `<U+05DE><U+05E9><U+05EA><U+05E0><U+05D4>..1`
* `<U+05DE><U+05E9><U+05EA><U+05E0><U+05D4>` -> `<U+05DE><U+05E9><U+05EA><U+05E0><U+05D4>..2`
```

The console output should be:

```
* `משתנה` -> `משתנה..1`
* `משתנה` -> `משתנה..2`
```

By the way, the encoding issues are inconsistent, e.g. just looking at the tibble in console or `glimpse` works fine:

```
> bugs
# A tibble: 1 x 2
  `משתנה..1` `משתנה..2`
  <chr>      <chr>     
1 שלום       רב        
> glimpse(bugs)
Observations: 1
Variables: 2
$ `משתנה..1` <chr> "שלום"
$ `משתנה..2` <chr> "רב"
```

Another bug is the one @isteves noted with the `View`.

```
View(bugs)
```

![image](https://user-images.githubusercontent.com/19262838/51968101-c833ee00-2479-11e9-9d68-d505820845db.png)

The viewer header is fine, but the cell content is not properly encoded.

**Comment by adisarid** [comment]
Following up on my last post here, for a combination of Hebrew and English (without additional languages) you can change the locale from within R `Sys.setlocale("LC_ALL", locale = "Hebrew_Israel.1255")`. This "ruins" the other non-English encoding (e.g., German, French). 

Anybody knows if there a "universal utf8 joker" for windows that can be used within the `Sys.setlocale` and would capture both Hebrew and other latin combinations other than English?

**Comment by kevinushey** [comment]
Unfortunately no -- UTF-8 locales are not yet supported on Windows, although in theory there is work coming to support this in a later release of Windows 10 (IIUC the feature is currently in beta)

**Comment by jmcphers** [comment]
The use of `format()` for the data viewer goes all the way back to the first commit.

https://github.com/rstudio/rstudio/blame/b33f1d51728ebbd6bbbe06c3d61c5799228b7607/src/cpp/session/modules/SessionDataViewer.R#L22-L24

Interestingly enough R's own data frame printer has the same problem as the data viewer:

![image](https://user-images.githubusercontent.com/470418/53452143-5f3a8a00-39d5-11e9-9368-4ab92f692414.png)
