### ISSUE TITLE
Allow R session to suspend when using the connections panel

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#4194]
RStudio Server reprex:

```
sc <- spark_connect(master = "local")
```

Then wait until session should suspend.

**Actual:** Session does not suspend.
**Expected:** There is nothing wrong with the default behavior regarding RStudio Server preventing connections from suspending when a connection is active. We can simply not know if the remote connection supports getting suspended or how to reconnect to a database or Spark and leave the connection in the same state.

However, we should allow users to opt-out of this behavior with an option, say by setting `options(connectionSuspend = TRUE)`, or:

```r
library(sparklyr)
# Optional spark_install() on first run.

withr::with_options(
    list(connectionSuspend = TRUE), {
    sc <- spark_connect(master = "local")
})
```

Which should allow the session to suspend even when the connection is active.

See: https://community.rstudio.com/t/how-to-disconnect-spark-when-idle/22130

**Comment by jmcphers** [comment]
>  We can simply not know if the remote connection supports getting suspended

How would you feel about having the remote connection tell us this, via a new part of the connections contract?

**Comment by javierluraschi** [comment]
That works for me as well!
