### ISSUE TITLE
rstudioapi::sendToConsole bug?

### ISSUE THREAD

**Issue by AndriSignorell** [rstudio/rstudio#4195]
### System details

    RStudio Edition :   Desktop 
    RStudio Version :  Version 1.2.1237
    OS Version      :     Windows10
                                 platform       x86_64-w64-mingw32          
    R Version       :       R version 3.5.2 (2018-12-20)

### Describe the problem in detail
I have assigned the add-in DescToolsAddIns::Str() to a keyboard shortcut Ctrl+s. When I select a variable name and press Ctrl+s the add-in is executed as expected, but rstudioapi::sendToConsole seems to place the cursor in the console since version 1.2.1237.

### Describe the behavior you expected
The cursor should remain on the script pane.

**Comment by kevinushey** [comment]
Thanks for the bug report! This will be fixed in the development version of the `rstudioapi` package with:

https://github.com/rstudio/rstudioapi/commit/41f415bc4a0c85ea43bfc34f04339c93d2a79319

You should now be able to execute (for example) `rstudioapi::sendToConsole("1 + 1", focus = FALSE)`.
