### ISSUE TITLE
rstudio still linking against libssl1.0.2?

### ISSUE THREAD

**Issue by h-vetinari** [rstudio/rstudio#4196]
I'm trying to install RStudio on bionic, and it seems the hard SSL-links have not been fixed yet, xref #2853

I went through all the releases, from [standard](https://www.rstudio.com/products/rstudio/download/#download) to [preview](https://www.rstudio.com/products/rstudio/download/preview/) to [dailies](https://dailies.rstudio.com/), all with essentially the same error:

```
Preparing to unpack rstudio.deb ...
Unpacking rstudio (<version>) ...
dpkg: dependency problems prevent configuration of rstudio:
 rstudio depends on libssl1.0.0 | libssl1.0.2; however:
  Package libssl1.0.0 is not installed.
  Package libssl1.0.2 is not installed.

dpkg: error processing package rstudio (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 rstudio
```

I also tried the debian9+ image, which is supposedly compiled against a newer OpenSSL, but this also fails with the above.

To be honest, I'm quite surprised this does not work out of the box for such an important part of the landscape like an ubuntu LTS (and OpenSSL 1.1.0 is ~2.5 years old now; good encryption should not be a side-issue IMO).

Here's a short dockerfile that makes it reproducible on the newest available `ubuntu:bionic` (call it `Dockerfile`), modified slightly from: https://askubuntu.com/a/862520

```
FROM ubuntu:bionic
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y --no-install-recommends \
        curl \
        libssl-dev \
        r-base-dev \
        # rstudio build dependencies
        libedit2 \
        libjpeg62 \
        libgstreamer1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        # extra dependency for rstudio 1.2
        libclang-dev

RUN \
    ## https://www.rstudio.com/products/rstudio/download/#download
    curl https://download1.rstudio.org/rstudio-xenial-1.1.463-amd64.deb > rstudio.deb \
    ## https://www.rstudio.com/products/rstudio/download/preview/
    # curl https://s3.amazonaws.com/rstudio-ide-build/desktop/trusty/amd64/rstudio-1.2.1237-amd64.deb > rstudio.deb \
    ## https://dailies.rstudio.com/rstudio/oss/xenial/x86_64/
    # curl https://s3.amazonaws.com/rstudio-ide-build/desktop/xenial/amd64/rstudio-1.2.1243-amd64.deb > rstudio.deb \
    ## try debian9 image with supposedly newer openssl
    # curl https://s3.amazonaws.com/rstudio-ide-build/desktop/debian9/x86_64/rstudio-1.2.1237-amd64.deb > rstudio.deb \
    && dpkg -i rstudio.deb \
    && rm rstudio.deb
```
Then 
```
sudo docker pull ubuntu:bionic
sudo docker build -t some_tag -f Dockerfile .
```

leads to the above error, in all variants or the `.deb`-source.

**Comment by kevinushey** [comment]
This is actually quite an issue because some commonly-used packages on Ubuntu 18.04 will remove the old version of OpenSSL when installed; for example:

```
$ sudo apt install libcurl4-openssl-dev
[sudo] password for kevin:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  libcurl4-doc libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev libssl-dev
The following packages will be REMOVED:
  libssl1.0-dev
The following NEW packages will be installed:
  libcurl4-openssl-dev
```

This means that an RStudio depending on OpenSSL 1.0 can't coexist with libcurl4, which is fairly commonly used (and I'm sure there are many other examples).

**Comment by h-vetinari** [comment]
Thanks for the quick response to this! Are these new ubuntu bionic builds published somewhere in a `.deb`? The dailies on https://dailies.rstudio.com (after merging #4220) do not work (neither ubuntu16.04+, nor debian9+).

**Comment by jmcphers** [comment]
They're already up, but the dailies page doesn't list them yet (it will early next week). You can try one here: 

https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.2.1255-amd64.deb

**Comment by h-vetinari** [comment]
@jmcphers 
Cool, thanks! I actually looked if the link existed on the dailies side of things, but didn't check the aws side.

However, I'm thinking there's still a metadata issue, i.e. something that gets picked up by `dpkg -i`, because I still get the same error...

**Comment by jmcphers** [comment]
Hmm. I'm now able to install RStudio on a clean Ubuntu 18.04 VM:

![image](https://user-images.githubusercontent.com/470418/51856884-b1f52900-22e5-11e9-88a6-316611a8db3c.png)

What's the exact Ubuntu release you're working with, i.e. `lsb_release -a`?

**Comment by h-vetinari** [comment]
As described in the OP, it's from the latest `ubuntu:bionic`, i.e.:
```
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

I'm not installing through a gui though, but building with docker. The result I get (after installing all the necessary build-dependencies)
```
Step 4/4 : RUN     curl https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.2.1256-amd64.deb > rstudio.deb     && dpkg -i rstudio.deb     && rm rstudio.deb
 ---> Running in c865cbf068bf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  111M  100  111M    0     0  22.7M      0  0:00:04  0:00:04 --:--:-- 23.1M
Selecting previously unselected package rstudio.
(Reading database ... 21253 files and directories currently installed.)
Preparing to unpack rstudio.deb ...
Unpacking rstudio (1.2.1256) ...
dpkg: dependency problems prevent configuration of rstudio:
 rstudio depends on libssl1.0.0 | libssl1.0.2; however:
  Package libssl1.0.0 is not installed.
  Package libssl1.0.2 is not installed.

dpkg: error processing package rstudio (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 rstudio
The command '/bin/sh -c curl https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.2.1256-amd64.deb > rstudio.deb     && dpkg -i rstudio.deb     && rm rstudio.deb' returned a non-zero code: 1
```

**Comment by h-vetinari** [comment]
@jmcphers I saw your commit https://github.com/rstudio/rstudio/commit/7dcb7d838a82d4e4f63aaef9a9f37b4b928290b5, now it works, thanks!

Any ETA when this (resp. the bionic tag) will land in the previews? Installing from dailies is not the most ideal. :)

**Comment by h-vetinari** [comment]
@jmcphers 
Starting from an image with nothing but the build dependencies (see OP), the build now succeeds, but still fails at runtime.

There are missing dependencies, namely `qt5.11` and `libxrandr2`. The problem is that `bionic` only contains `qt5.9` by default, and so installing `qt5.11` needs some extra effort like https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.11.3-bionic. Would it be possible to "package" those libraries in the `.deb`?

PS. More than just `qt5-default`, what is actually needed (from a minimal image), is to install:
```
apt-get install qt5-default libqt5webengine5 libqt5webenginewidgets5 libxrandr2
```
This works in `ubuntu:cosmic` without adding any PPAs, because cosmic already has `qt5.11` by default. The situation there will be similar however, if you end up requiring `qt5.12` to solve some of the other resolution issues.

**Comment by jmcphers** [comment]
Qt 5.11 ought to already be packaged in the .deb -- what are you seeing that suggests it isn't?

**Comment by h-vetinari** [comment]
Without the installs mentioned above, this is the result after starting the container I built and checking what `rstudio` does, and then inspecting the linked libraries:
```
root@eb4ab2ee7ed5:/# rstudio
rstudio: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
root@eb4ab2ee7ed5:/# ldd usr/bin/rstudio
        linux-vdso.so.1 (0x00007ffc60de5000)
        libQt5WebEngineWidgets.so.5 => not found
        libQt5PrintSupport.so.5 => not found
        libQt5DBus.so.5 => not found
        libQt5WebEngineCore.so.5 => not found
        libQt5WebChannel.so.5 => not found
        libQt5Positioning.so.5 => not found
        libQt5Quick.so.5 => not found
        libQt5Network.so.5 => not found
        libQt5Widgets.so.5 => not found
        libQt5Gui.so.5 => not found
        libQt5Core.so.5 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fed14e69000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fed14c66000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fed14a5f000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fed14857000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fed1463a000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fed143d0000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fed13f58000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fed13bcf000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fed13831000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fed13619000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fed13228000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fed15901000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fed13024000)
```

Fixing the rstudio-call (while also inspecting the `ldd` output) lead me to also install the libraries above, with which things then work (i.e. the `rstudio`-call succeeds, and it starts complaining about missing X11, which is fine for a REPL-call).

**Comment by h-vetinari** [comment]
Any news on this? BTW, the server version *does* have the `qt` dependencies for some reason.
