### ISSUE TITLE
Git push doesn't work if local branch and (non-origin) remote branch have different names

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#4201]
I can return with a very specific reprex if desired but I want to record this observation now.

Consider a repo with a branch where upstream tracking branch is NOT on `origin` and the local branch name != remote branch name. This happens when you add a contributor's fork as remote and they have made a PR from their `master` branch (you will be forced to pull the PR into a local branch with a name other than `master`).

Using the Big Green Button to push in RStudio's Git pane results in a git command of this form in this case:

```
git push REMOTE refs/heads/REMOTE-BRANCH-NAME
```

but I think this should be

```
git push REMOTE HEAD:refs/heads/REMOTE-BRANCH-NAME
```

You can actually set up the refspec for `remote.REMOTE.push` in git config so that `git push` "just works" in this case. But RStudio unfortunately still issues the command above. So it's being a bit clever but not quite clever enough.

**Comment by hadley** [comment]
It would be really helpful to get this fixed otherwise 😄

**Comment by kevinushey** [comment]
This is where the code for the Git Push action lives:

https://github.com/rstudio/rstudio/blob/f95fae71031075dc24ef6a00d1d819a772fafa28/src/cpp/session/modules/SessionGit.cpp#L995-L1011

Should we just include a `HEAD:` prefix by default here?

**Comment by jennybc** [comment]
> Should we just include a HEAD: prefix by default here?

Yes, that's what I'm proposing. So if a refspec is given at all, it should always be of the form HEAD:TARGET_REF.

A bigger change and probably a non-starter is to be more conservative and just do `git push` and lean more on user/repo config. The problem with the current push situation is that even if I have the repo config set up to do something special for a certain branch, this RStudio command clobbers it. I would like RStudio to either do more (prepend `HEAD:`) or less (rely on my config).

**Comment by jennybc** [comment]
Here's the key bit of the [`git push` docs](https://git-scm.com/docs/git-push) describing a command of this form (bold is mine):

``` bash
git push <repository> <src>:<dst>
                      \_________/ <-- "refspec"
```

> The `<dst>` tells which ref on the remote side is updated with this push. Arbitrary expressions cannot be used here, an actual ref must be named. If `git push [<repository>]` without any `<refspec>` argument is set to update some ref at the destination with `<src>` with `remote.<repository>.push` configuration variable, `:<dst>` part can be omitted—​such a push will update a ref that `<src>` normally updates without any `<refspec>` on the command line. **Otherwise, missing `:<dst>` means to update the same ref as the `<src>`.**

This explains why the command RStudio is currently forming doesn't account for the case where local and remote branches have a different name. RStudio is executing:

``` bash
git push <repository> <src>
```

**Comment by jennybc** [comment]
And the solution we're implementing corresponds to one of the official examples:

https://git-scm.com/docs/git-push#git-push-codegitpushoriginHEADmastercode

```
git push origin HEAD:master
```

> Push the current branch to the remote ref matching `master` in the `origin` repository. **This form is convenient to push the current branch without thinking about its local name.**
