### ISSUE TITLE
Python auto-complete file path uses absolute path

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#4204]
When using the auto-complete for file paths inside `reticulate::repl_python` or a python file / code chunk, you get the same file path autocomplete you do in R:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/23075542/51617947-4aad3280-1efb-11e9-8fac-b314e7abec65.png">

However, when accepting the autocomplete, an absolute path is created. Is there a reason for this? It feels like a bug to me!

<img width="502" alt="image" src="https://user-images.githubusercontent.com/23075542/51617986-5e589900-1efb-11e9-8b42-457a65a69da4.png">

**Comment by kevinushey** [comment]
That is indeed a bug -- thanks for reporting!
