### ISSUE TITLE
Execute python code indentation behavior

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#4205]
Let's say I have a python file:
```python
if True:
  print("hello")
 

```

If I execute this line by line with `CTRL + ENTER`, things work as expected:
```python
>>> if True:
...   print("hello")
... 
hello
```

However, if I just execute `print("hello")`, I get an indentation error:
```python
>>>   print("hello")
IndentationError: unexpected indent (<string>, line 1)
```

Is it possible to remedy this in some fashion by using (1) the context in the `repl_python` (i.e. the `...<tab>` indicates that `repl_python` knows we should be executing something that is indented) and (2) the code line under my cursor in the IDE. The only change would be to have logic in which the "indentation" is stripped off of the selected code to some extent. I'm sure more complex examples could be formulated.

The problem I see is the _terminating_ chunk. You can see my third `CTRL + ENTER` terminates the `if` block by not being indented. If there is a way that we can remedy this (or even another shortcut / configuration option that tweaks this behavior), I think it would be desirable. It is often the case that I want to interactively execute lines in an `if` block or a `function` while testing without executing the full block / without including the indentation.

**Comment by kevinushey** [comment]
Should be resolved with https://github.com/rstudio/reticulate/commit/31765acedd65ebd9d40d12eb71a5d22b0cc85395: we now allow leading whitespace in top-level Python statements in the REPL.
