### ISSUE TITLE
shiny: closing the run-in window prevents app re-launching

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#4207]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1246
    OS Version      : macOS 10.14.2
    R Version       : 3.5.1

### Steps to reproduce the problem

1. File>New File>Shiny Web App...
2. Select "Run in Window" from the "Run App" drop down.
3. Click "Run App".
4. Close the window containing the Shiny application (either with Command-w or the red (X) control).

### Describe the problem in detail

The Console continues running the Shiny application. The editor pane shows "Reload App".

Clicking "Reload App" does nothing. There is no obvious reloading of the content

Clicking the Console "Stop" button gives the Console prompt but the editor pane still shows "Reload App". Clicking "Reload App" does nothing.

You can get the IDE to behave again by clicking the Console "Stop" button and then using up-arrow to re-execute the (UI injected) `shiny::runApp` call. The window will re-launch. Both the Console "Stop" and "Reload App" buttons again work as expected.

It appears that we are not recognizing that the launched application window has been closed and prohibiting some actions as a result.

### Describe the behavior you expected

Closing the Shiny application window used to automatically halt the running Shiny application. It would be nice if that behavior were restored. Alternatively, let the Shiny application be fully torn down with "Stop" or relaunched with "Reload App" regardless of the state of the application window.

**Comment by kevinushey** [comment]
Looks like a regression from https://github.com/rstudio/rstudio/commit/4d79bfebdb28bad4a7bfa931b1282c5b528aaa60, which purportedly fixed the same issue with RStudio Server.

**Comment by kevinushey** [comment]
See also: https://github.com/rstudio/rstudio/issues/4128

**Comment by dracodoc** [comment]
I'm seeing this on RStudio Cloud too. My project: https://rstudio.cloud/project/196548
