### ISSUE TITLE
Job info event triggers twice when clicking icon

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#4213]
```r
.rs.api.addJob("test", actions = list(
  info = function(id) {
    message("start")
  },
  stop = function(id) {
    message("stop")
    .rs.api.removeJob(id)
  }
))
```

Click on the world (job info) icon for the new job.

Actual: `start` is printed twice.

<img width="877" alt="screen shot 2019-01-23 at 9 37 43 pm" src="https://user-images.githubusercontent.com/3478847/51656988-d0f76200-1f57-11e9-8f93-67eed7fd9a8c.png">

Expected: Start event to be triggered only once.

**Comment by jmcphers** [comment]
Fixed with #4124.
