### ISSUE TITLE
IDE fails to load on Chrome Canary after signing in

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#4217]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1251
    OS Version      : Ubuntu 18.04
    R Version       :  3.4.4

### Steps to reproduce the problem
1. Download Google Canary
https://www.google.com/chrome/canary/
2. Access a RStudio Server instance (pro or regular)
3. Login 
### Describe the problem in detail
The login page for Rstudio server is displayed properly and the user can enter in credentials. But after signing in the user sees the loading icon and nothing happens. The IDE fails to display
### Describe the behavior you expected
IDE and other components are displayed

**Comment by jmcphers** [comment]
@gtritchie found this, too. There's a P1 Chromium bug to address this:

https://bugs.chromium.org/p/chromium/issues/detail?id=924317

GWT thread: https://groups.google.com/forum/#!topic/google-web-toolkit/74VR8KT4WgY

If this makes it into mainline releases of Chromium, we might need to update to GWT 2.8.2 sooner than we'd planned. See https://github.com/rstudio/rstudio/issues/4142.

**Comment by gtritchie** [comment]
The Chromium bug was closed as a dup, now being discussed in this one: https://bugs.chromium.org/p/chromium/issues/detail?id=923585

**Comment by gtritchie** [comment]
Fixed in Canary 74.0.3686.0. See https://bugs.chromium.org/p/chromium/issues/detail?id=923585

**Comment by jmcphers** [comment]
Whew!
