### ISSUE TITLE
Projects deleted from Project list when not connected to remote drive

### ISSUE THREAD

**Issue by fostvedt** [rstudio/rstudio#4218]
There is an annoying feature to RStudio relating to the recent project list. Sometimes I work remotely from home and the remote drive that all my work is stored on (ie H:/ drive) doesn’t always connect automatically. My problem is that if I try to open a project and the connection with this H:/ drive is not detected, the project gets deleted from the RStudio project list. Since I clicked on the project, I think that shows that I still want to work with that project. So having it deleted from the list is very annoying.  I then need to go find the project in the remote drive and reopen it.

I really wish there was at least a prompt to the user regarding removing the project from the list of recent projects as sometimes it can be challenging to find the location of the project I was working on. 

Does this make sense?

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.383
    OS Version      :  Windows 10
    R Version       :

**Comment by ronblum** [comment]
@fostvedt Thank you for raising this issue. We will review it as we work on development of future versions of RStudio.

**Comment by jmcphers** [comment]
We're now tracking this feature request in https://github.com/rstudio/rstudio/issues/4235.
