### ISSUE TITLE
Too many error dialogs under poor network condition

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#4222]
I'm using RStudio Server and when the network condition is poor (e.g. on a train in tunnel over 4G hotspot), the connection is unstable and the "Error saving file" dialog will pop out as many as possible. It almost takes a minute to close all those overlapping dialogs before getting started to work again as the wifi signal gets better.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/4662568/51724670-60f0f500-2099-11e9-9054-71f393b44b6a.png">

It would be much nicer if only one dialog appears, or if an status indicator (not modal) rather than a dialog shows.

**Comment by ronblum** [comment]
@renkun-ken Thanks for reporting the issue. What environment is the server running on—RStudio version, OS, and R version?

**Comment by renkun-ken** [comment]
My environments:
RStudio Server 1.2.1189 under Ubuntu 16.04.5, R 3.4.4
RStudio Server 1.2.1255 under Ubuntu 16.04.5, R 3.5.2
