### ISSUE TITLE
Queue bash chunk while another is running

### ISSUE THREAD

**Issue by akiledal** [rstudio/rstudio#4224]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1226
    OS Version      :  Windows 10
    R Version       : 3.5.2

### Steps to reproduce the problem
Have a bash chunk running and try to queue another.

### Describe the problem in detail
Currently you can't queue a bash chunk for execution if there is already one running like you can with R chunks.

### Describe the behavior you expected
With a bash chunk running, be able to queue another for execution upon completion of the first.

**Comment by ronblum** [comment]
@akiledal Thank you for raising. I'm not seeing exactly this, but I see something similar: chunks can only be queued if they've already been run and the output is still available. If a chunk has not been run, or it has been run and the output was cleared, it cannot be queued.

What do you get if you try to queue up a bash chunk that has already has completed output?

**Comment by akiledal** [comment]
@ronblum I'm seeing the same thing you are, previously run & not cleared chunks can be queued, while not previously run chunks & run but cleared can't be queued.

**Comment by ronblum** [comment]
Great—at least we're both seeing the same issue. Thanks for checking.
I'm closing this issue, and opened a new one,  #4238, to reflect the behavior we're seeing.
