### ISSUE TITLE
Saving from "new window" doesn't work

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#4227]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1255.1 (Professional)
    OS Version      : MacOS 10.14.2
    R Version       : R 3.5.2

### Steps to reproduce the problem
- Open a file in a "new window"
- Make changes to the file
- Try to save changes (either with keyboard shortcut or with save icon)
- File doesn't save
- Trying to "Return to main window" doesn't work with unsaved changes
- Closing the file and trying to save changes doesn't work

### Describe the problem in detail
![broken-save](https://user-images.githubusercontent.com/10444878/51780568-c01c2d00-20cc-11e9-97d2-1e4f5dff869c.gif)

### Describe the behavior you expected
Saving should work from an external window

**Comment by jmcphers** [comment]
This turned out to be the same issue as #4223, and is fixed in https://github.com/rstudio/rstudio/commit/d5eaed876c46ebcf1dd55d7f4e06955fe53e4f54.
