### ISSUE TITLE
Standalone VCS window shows nothing

### ISSUE THREAD

**Issue by jcheng5** [rstudio/rstudio#4228]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1251
    OS Version      : 10.12.6
    R Version       : 3.5.1

### Steps to reproduce the problem

In a project that uses git, make a change to a file, then hit the Diff button in the Git toolbar to launch the standalone VCS window.

### Describe the problem in detail

The Git pane shows status correctly, but the standalone VCS window shows nothing. Also, entering a message and pressing Commit appeared to do nothing (even if there are staged changes waiting to be committed) (the commit message didn't even disappear). I reproduced this in two different projects, and restarting the IDE didn't help.

I noticed in the network trace there was a log_exception call with "(ReferenceError) : resultFieldName is not defined".

![image](https://user-images.githubusercontent.com/129551/51780515-1042c180-20c4-11e9-9f16-f61f55eddc10.png)

### Describe the behavior you expected

VCS window should show the same results as the Git pane.

**Comment by jmcphers** [comment]
Yes, this is https://github.com/rstudio/rstudio/issues/4223. It's a bug in the dailies and will be fixed before we cut another preview.

**Comment by dfalty** [comment]
Verified fixed 1.2.1320.
