### ISSUE TITLE
Reformat code inconvenience

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#4229]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1255
    OS Version      : MacOS 10.14.3
    R Version       : 3.5.1

When reformatting code in a code chunk one has to be very careful which selection.
Selecting part of the code or the or all the code in a chunk works as expected.
But selecting "a little bit too much", namely the ```{r} and/or ```

**Comment by jmcphers** [comment]
Closing this since it looks like it was completed in #4230. :-)
