### ISSUE TITLE
Reformat selection - possible improvement

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#4230]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1255
    OS Version      : MacOS 10.14.3
    R Version       : 3.5.1

When reformatting code in a code chunk one has to be very careful which selection.
Selecting part of the code or the or all the code in a chunk works as expected.
But selecting "a little bit too much", namely the lines with the 3 backquotes before and after the code
produces an error messages.
it would be convenient if RStudio would recognise these situations and reformat the selected code.

**Comment by ronblum** [comment]
@neuwirthe As always, thank you for the suggested improvement!
