### ISSUE TITLE
Python reticulate auto-complete issue when writing an invalid R name

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#4231]
In latest daily and dev version of reticulate:

![image](https://user-images.githubusercontent.com/23075542/51814544-c4417980-2289-11e9-9643-eaf54d8e51bd.png)

Autocomplete `__class__` ends up being 
```
obj.`__class__`
```

Which gives a syntax error:
![image](https://user-images.githubusercontent.com/23075542/51814571-eb984680-2289-11e9-8433-68a9aae1196f.png)

This error seems only to happen in `repl_python` (i.e. not in a `.py` script), which is perhaps a bit more understandable since it _is_ an R interpreter. Not sure if there is any better way to handle the syntax differences between the two languages wrt "what is a legitimate name"

**Comment by colearendt** [comment]
Please keep

**Comment by colearendt** [comment]
Did you know you can "unstale" crackers in a dehydrator? Or so I have heard.

GitHub issues just need a comment

**Comment by ronblum** [comment]
This has been fixed! Thanks to a recent refiling...
