### ISSUE TITLE
Syntax highlighter for Makefile should be useable for secondary makefiles

### ISSUE THREAD

**Issue by brendanf** [rstudio/rstudio#4232]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.1.442 
    OS Version      :  Ubuntu 16.04
    R Version       :  3.5.0

### Steps to reproduce the problem
Open a makefile in the editor which is not named "Makefile".  For example, "include_this.make"

### Describe the problem in detail
The syntax highlighter does not recognize that the file is a Makefile.  "Makefile" is not one of the options which can be chosen in the syntax highlighting dropdown menu at the lower right corner of the editor pane.

### Describe the behavior you expected
At the least, I would like to be able to manually choose "Makefile" as the language in the syntax highlighting dropdown list.  It would also be nice if the ".make" extension were automatically detected as a makefile.

**Comment by ronblum** [comment]
Thank you for raising this issue. We will review it as we work continue development of RStudio.

Reproduced on MacOS 10.14 Mojave using RStudio Desktop 1.2.1256-1.
