### ISSUE TITLE
CTRL-Shift-2 doesn't zoom in/out in by default or show up when modifying shortcuts

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4233]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1256
    OS Version      : Windows 10
    R Version       : 3.5.2

### Steps to reproduce the problem

In Windows, go to RStudio Server using Google Chrome.
1. Click on CTRL-SHIFT-2.
2. Tools -> Modify Keyboard Shortcuts
3. Pick any shortcut and click on CTRL-SHIFT-2

### Describe the problem in detail

Nothing happens in both steps (1) and (3).

### Describe the behavior you expected

In step (1), the console pane should zoom in and out with each click. Note that the related ones (CTRL-SHIFT-1 and 3–9) correctly zoom different panes.
In step (3), the displayed shortcut value should be updated to "CTRL+Shift+2".

This works fine with Edge and Firefox, and on both Chrome and Firefox on MacOS 10.14.

**Comment by gtritchie** [comment]
I cannot repro this. On Windows-10 with Chrome 80 Ctrl+Shift+2 is working properly for me.

Suggests you might have something installed that is grabbing this keyboard sequence before it reaches RStudio's shortcut handling.

Another thing to try:
* Help / Diagnostics / Show Keyboard Shortcut Commands
* An infobar appears at bottom of window
* Now type Ctrl+Shift+2

On my machine I see "layoutZoomConsole : Zoom Console" which is the expected command for this. Note that shortcuts won't resume working until you close this infobar via [x].
