### ISSUE TITLE
Unable to publish R Notebook Preview to RPubs. Unsupported Document Format

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#4234]
### System details
    RStudio Edition : RSP & Mac Desktop
    RStudio Version : 1.2.1206-2 & 1.2.1256 
    OS Version      : RHEL 7.3 & Mac 

### Steps to reproduce the problem
1. Create R Notebook file
2. Preview Notebook
3. Select Publish -> RPubs
4. Observe error message

### Describe the problem in detail
Unable to publish R Notebook Preview to RPubs. Note, this seemed to work fine in 1.1.463.
"Unsupported Document Format
Only documents rendered to HTML can be published to RPubs. To publish this document, click Knit or Preview to render it to HTML, then click the Publish button above the rendered document."
![image](https://user-images.githubusercontent.com/15237845/51856117-7dd53480-22f4-11e9-9e15-747a38db2421.png)

**Comment by jspiewak** [comment]
Update [Community topic](https://community.rstudio.com/t/not-publishing-from-preview-in-rstudio-cloud/22551/4) when this fix is rolled out.
