### ISSUE TITLE
Publishing to RStudio Connect when time sync error message

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#4239]
When publishing from the RStudio IDE to a RStudio Connect server with a significantly different time difference, there is an error message displayed that could use a bit of love. It looks like the HTML is getting masked / not rendered properly

![image](https://user-images.githubusercontent.com/23075542/51940581-6d01ed00-23e0-11e9-8a69-7c96b31c0f08.png)

I have also noticed some funny errors that happen in this workflow when trying to activate the token that the IDE relies upon for publishing, if the token has never been created before (and the time sync is off). Nothing reproducible there, unfortunately, but thought I would mention it since it is related.

**Comment by jmcphers** [comment]
We don't render HTML here for security reasons. It'd be nice to detect this and do something nicer, but since this error is very rare it's not likely we'll spend time on it.
