### ISSUE TITLE
Add diagnostics and notebook support for <<references>> to external chunks

### ISSUE THREAD

**Issue by hugesingleton** [rstudio/rstudio#4242]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1163
    OS Version      : Windows 10
    R Version       : 3.4.3

### Steps to reproduce the problem
1. Make a simple chunk file, **test.r**

```
## @knitr test
print("Hello")
```

2. Make a simple RMD file, **test.rmd**, read the chunk into it, refer to the "test" label

```
---
output: html_document
---
\```{r read chunks}
knitr::read_chunk("test.r")
\```
\```{r refer to the chunk}
<<test>>
\```
```

RStudio source editor highlights the line with << as syntax error. This confuses a lot when searching for errors in a longer script. Please find a screenshot below.

![rstudio_chunk_ref_syntax_error](https://user-images.githubusercontent.com/47183766/51990087-98e8a580-24a8-11e9-9abd-bd1db0aa4b30.png)

This notation if very useful, when one needs to refer to various parts of an R file (which needs to be separated from the RMD for certain reasons) within a single chunk (to avoid unnecessary multiplying them), like this:
```
\```{r refer the chunk}
<<testA>>
... do something ...
<<test B>>
... do something
<<testC>>
\```
```

**Comment by jmcphers** [comment]
The IDE doesn't currently support this syntax, but you can do the same thing using chunk labels alone, and that won't result in syntax errors. See "alternative syntax" in this blog post for help:

http://zevross.com/blog/2014/07/09/making-use-of-external-r-code-in-knitr-and-r-markdown/

Does that do what you want?

**Comment by hugesingleton** [comment]
Thank you for your answer. I know this page. Unfortunately, this is exactly what I want to avoid. In my post I mentioned, that I really want to avoid multiplication of the chunk sections.

For organizational reasons (highly controlled and structured working environment), my analyses are split into pairs of R scripts for perfect separation of concerns: data read/analysis and presentation.

1.  **dataXX.r** file (XX stands for chapter of the analysis), reads data from a database, analyses it and writes the result to RDATA file. The RDATA file is then used in an extensive validation process. This dataXX.r file may be called from many external processes, including a specialized program automatizing the process of numerical validation. The "dataXX.r" file must not contain anything but the pure analysis (no printing, no document generation, etc.), and it must be a pure R code (no RMD chunk). The only I can use is a commented knitr "header", telling the engine that this piece of code is "labelled" and can be used within RMD code as an ordinary chunk (## @knitr Table1).  That's why it's R, not RMD.

2. dataXX_print.r file, which is responsible for storing the results in a process documentation. It reads the previously saved RDATA file and prints the data frame into a complex MS Word document (via officer + flextable packages) and Excel (via openxlsx). For consistency, this is also stored in R file rather than RMD. Only labelled in the first line (## @knitr TableXX_print).

Now, there is a formal requirement that the entire analysis is recorded, step by step, code by code, in a sort of "LOG" (like SAS does) with both executed code and dumped results. 

Everything is driven manually from a global RMarkdown document with chapters. Let's say:
```
Chapter 1
call data1.r
call data1_print.r

Chapter 2
call data2.r
call data_print.r
etc.
```
There are tens of chapters. Now you see, why I want to avoid the multiplication of RMD code chunks and organize the calls into a single chunk. The < <  chunk_name > > notation allows me to do that exactly the way I want.

I'm sorry for this long explanation, but I wanted to justify the importance of this operator.

**Comment by kevinushey** [comment]
If we wanted to support this, we could augment the R highlight rules with something like `<<.*>>` in https://github.com/rstudio/rstudio/blob/master/src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js.
