### ISSUE TITLE
Rstudio relaunches on second monitor with strange scaling 

### ISSUE THREAD

**Issue by patr1ckm** [rstudio/rstudio#4243]
After dragging Rstudio to a second monitor, restarting Rstudio launches Rstudio in the monitor in a strange windowed form.

### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1237
    OS Version      : Mac OS 10.12.6
    R Version       : 3.5.1
    
 
External monitor model: [HP 25F](https://express.google.com/u/0/product/9391779978769601228_4330064171675239515_125181302?utm_source=google_shopping&utm_medium=tu_cu&utm_content=eid-lsjeuxoeqt&gtim=CP2s-s6h28WxIRDwpIThmoe4sGoY8LzVbSIDVVNEKICN8-IFMPa62Ds&utm_campaign=125181302&gclid=EAIaIQobChMIu8722_GV4AIVBBgMCh1qKQ4CEAQYASABEgJrlvD_BwE)
Laptop model: Macbook Pro 13" 2018 

### Steps to reproduce the problem

1. Launch Rstudio
2. Drag Rstudio to second monitor (works fine)
3. Quit Rstudio
4. Re-launch Rstudio

Rstudio should now appear in a strange mini windowed form (see screenshots below).

### Describe the problem in detail

On my system, when re-launching Rstudio on a second monitor it sometimes launches in a strange, mini windowed form. I've replicated the behavior on two external monitors, including the one linked above (I don't have the details on the second one right now, but can add later).

When initially launched, dragging Rstudio to the external monitor works fine, and looks like this:
![screen shot 2019-01-30 at 9 58 22 am](https://user-images.githubusercontent.com/427445/51994604-c4529c80-2476-11e9-9cd3-b2e8f434e17b.png)

However, when restarting Rstudio it launches like this in the external monitor:

![screen shot 2019-01-30 at 9 58 38 am](https://user-images.githubusercontent.com/427445/51994613-c87eba00-2476-11e9-976d-80aa7d103e9a.png)

It can be corrected by dragging Rstudio to the laptop screen, and then back to the external monitor.

### Describe the behavior you expected

Restarting Rstudio launches Rstudio in the second monitor not in the strange windowed form.

### Related

This problem may be related to https://github.com/rstudio/rstudio/issues/2135, however I didn't see other issues reporting this exact behavior.

I'm guessing the most likely explanation is that I am unlucky with my external monitor / laptop pairing, but did want to file the issue because it wasn't present in Rstudio 1.1.

**Comment by jmcphers** [comment]
Thanks for reporting! This is indeed an issue with RStudio 1.2's new rendering engine. It's being tracked in https://github.com/rstudio/rstudio/issues/3479.
