### ISSUE TITLE
Unable to read a shape file.

### ISSUE THREAD

**Issue by Vipulagarwal89** [rstudio/rstudio#4245]
Hi,

I am new to R studio. I am trying to read a shapefile from my current directory and I am getting error in OGRInfo. Please help. Below attached is the screen shot of my code with error,

![capture](https://user-images.githubusercontent.com/47199058/52024460-e5df7280-24ce-11e9-94ec-0870f38a54a7.PNG)

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
