### ISSUE TITLE
[Windows] Multi-line statements appear too slowly on the console

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4246]
**Steps to reproduce:**
* Write some multi-line code in the editor
* Select the code
* Run the selected code (e.g. Ctrl + Enter)

**Expected behavior:**
* Code should quickly appear in the console and execute.

**Actual behavior:**
* On windows, all the statements start slowly appearing in the console line by line, with a noticeable lag between each line, taking a lot longer to execute the statement than in linux.

**Setup:** RStudio 1.2.1237, R 3.5.1, running on windows 10.

**Comment by kevinushey** [comment]
How slow is slow? Can you provide a screencast of what you're seeing?

At least in my case, multi-line code appears to run fast and without issue.

Can you provide any other information? Does this occur in all projects, or just certain ones? Are you working on a networked filesystem or anything like that?

**Comment by david-cortes** [comment]
@kevinushey : I am working with files on a networked system, but that doesn’t seem to make a difference. I finally nailed it down to printing in the console some things before running statements (I unfortunately cannot provide the code). Oddly enough, if I then run a single-line statement while the multi-line ones are showing line-by-line, the multi-line ones will sometimes execute all at once without slowly printing them line by line. Cannot pinpoint what exactly makes them do it though.

**Comment by kevinushey** [comment]
Unfortunately unless we can reproduce the problem locally it's unlikely we'll ever be able to fix it.

**Comment by jmcphers** [comment]
We have not been able to reproduce this, or gotten any other reports, in over a year. Closing.
