### ISSUE TITLE
Simplified user interface for beginners

### ISSUE THREAD

**Issue by ute** [rstudio/rstudio#4252]
### Using RStudio in teaching
I love RStudio, and have been using it for a long while now. Features and possibilities are ever growing, and accordingly, the interface has become more and more complex.

I am teaching statistics for young undergraduates in mathematics and related subjects, and asked students to install and use RStudio. I noticed that many of them got overwhelmed with the complexity of the interface, although I compiled a document showing which buttons, panes etc are relevant for them.

I would like to encourage students to use RStudio right from the start. In particular, the environment view is a real asset, because it shows them "what is going on" inside R. R Markdown is a plus, too, giving a simplified access to LaTeX.
### Option to select a simplified interface
For a beginner, it is not necessary to be able to debug, build, profile code, or to build shiny apps and use C++. A simplified interface would omit many options in the menu, for example, as a new file type it would be sufficient to have R Script and R Markdown. The View menu could contain a button to toggle between  simplified and full view.

**Comment by jmcphers** [comment]
This is a nice idea but hasn't received any upvotes or support in over a year, so it's not likely we'll get to it soon.
