### ISSUE TITLE
Warning for long first line commit messages

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#4255]
I sometimes write long (descriptive?) message on the commit message. However, sometimes I don't know when should I use a "title" on the message and then a body of the commit. 

A warning when I go above 80 characters it would help me to decide when should I cut the "title". Alternatively a solution like the grey line of the code panel would also work well for this panel. 

Thanks for your great work!

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio/pull/5207.

**Comment by llrs** [comment]
Great!! That will do
