### ISSUE TITLE
Add ability to search for preferences/global options

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4256]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1.463 & 1.2.1256
    OS Version      : All
    R Version       : 3.5.2

### Describe the problem in detail

There is no way to search Preferences/Global Options.

### Describe the behavior you expected

Provide a way to search preferences/options, as in MacOS System Preferences, IntelliJ, etc.

**Comment by jmcphers** [comment]
You can now do this using the Command Palette.
