### ISSUE TITLE
Strange behavior when running chunks

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#4257]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.37
    OS Version      :  MacOS 10.14.3
    R Version       :  3.5.2

When runnin a chunk with (CMD-Shft-Return) the column to the left (with the line numbers) behaves very strangely. See attached image.
![2019-02-03_13-21-40](https://user-images.githubusercontent.com/157619/52176738-1ec16500-27b7-11e9-9588-d7c55740a9c3.png)

**Comment by jmcphers** [comment]
We haven't been able to reproduce this. What's the version of RStudio you're using? (1.37 isn't a version... :-))

**Comment by neuwirthe** [comment]
Sorry. it was 1.3.7
![2019-02-05_00-18-40](https://user-images.githubusercontent.com/157619/52243970-c768e500-28db-11e9-9cbb-cf55576c3842.png)

**Comment by jmcphers** [comment]
We'll take a look, but we do not recommend using the dailies for your work (especially not 1.3!). We update the preview release regularly if you're looking to use the latest 1.2 bits.

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by neuwirthe** [comment]
Just wanted to confirm that this still happens ins 1.3.11.
BTW: I am running the latest devel version on one of my machines, but not on my "production" machine ;-)
