### ISSUE TITLE
Ctrl + Shift + C in console comments out lines in the editor

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4261]
**Steps to reproduce:**
* Write some code in the editor pane
* Leave the current selection at some non-empty line in the editor
* Switch to the console
* Write some multi-line statement there
* Select one or more lines from what you’re writing in the console
* Press Ctrl + Shift + C

**Expected behavior:**
Should comment out the selected lines in the console.

**Actual behavior:**
Comments out the line(s) that were last selected or pointed at in the editor.

**Setup:** RStudio 1.2.1237, R 3.5.1, running on Windows 10.

**Comment by ronblum** [comment]
@david-cortes Thanks for raising this. Ctrl-Shift-C is Editor scoped, so I'm marking this is an enhancement to enable this for the Console, as well. Thanks!

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.
