### ISSUE TITLE
Cannot set variable rsession-ld-library-path in /etc/rstudio/rsession.conf

### ISSUE THREAD

**Issue by nugulus** [rstudio/rstudio#4262]
### System details

    RStudio Edition :  Server
    RStudio Version : 1.1.463
    OS Version      : RHEL 6
    R Version       : 3.5.2

### Steps to reproduce the problem
Add the line
rsession-ld-library-path=/opt1/opt.LOCAL/gcc-7.2.0/lib64:/opt2/software/hdf5/1.10.4/lib
in /etc/rstudio/rsession.conf
# rstudio-server verify-installation
rstudio-server stop/waiting
Error reading /etc/rstudio/rsession.conf: unrecognised option 'rsession-ld-library-path'
rstudio-server start/running
At this point, no user can open rstudio server:8787 at a browser.

### Describe the problem in detail
Some R packages are compiled from source, using different version of gcc than when compile/installing R.
LD_LIBRARY_PATH can be set for R, say, through Environment Module at the shell, so there is no external library access issue in loading any R packages.
Tried to use rsession-ld-library-path in /etc/rstudio/rsession.conf according to official document, but cannot be verified by the server which is freely downloaded and installed.

### Describe the behavior you expected
Refer to the doc
https://support.rstudio.com/hc/en-us/articles/200552316-Configuring-the-Server
see External Libraries session. Follow the instruction, I should be able to load R packages that require external libraries.

> sessionInfo() 
R version 3.5.2 (2018-12-20) 
Platform: x86_64-pc-linux-gnu (64-bit) 
Running under: Red Hat Enterprise Linux Workstation release 6.8 (Santiago)  
Matrix products: default BLAS: /opt2/software/R/3.5.2/lib64/R/lib/libRblas.so LAPACK: /opt2/software/R/3.5.2/lib64/R/lib/libRlapack.so  
locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         
attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       loaded via a namespace (and not attached):  [1] Rcpp_1.0.0          matrixStats_0.54.0  IRanges_2.16.0      plyr_1.8.4          grid_3.5.2          gtable_0.2.0         [7] stats4_3.5.2        scales_1.0.0        lazyeval_0.2.1      S4Vectors_0.20.1    Rhdf5lib_1.4.2      BiocParallel_1.16.5 [13] tools_3.5.2         munsell_0.5.0       DelayedArray_0.8.0  HDF5Array_1.10.1    yaml_2.2.0          parallel_3.5.2      [19] compiler_3.5.2      colorspace_1.4-0    BiocGenerics_0.28.0 rhdf5_2.26.2
--
 
> | >
>

**Comment by dfalty** [comment]
`rsession-ld-library-path` should be set in `rserver.conf` and not in `rsession.conf`. Let us know if that works for you!
