### ISSUE TITLE
Windows Key Shortcuts make keyboard event not work in browser

### ISSUE THREAD

**Issue by chigix** [rstudio/rstudio#4263]
### System details

    RStudio Edition : Server 
    RStudio Version : 1.1 1.2
    OS Version      :  Debian 9.6
    R Version       :  3.5.2

### Steps to reproduce the problem

This problem is reproducible in both version 1.1 and 1.2 of Rstudio Server Edition.

Since Windows 8, switching IME is through the shortcut of `Win + space`, which would make the browser only receive the event from `Win` key without the event of `space` key because the browser would be out of focus when IME switching is triggered.

After I switched IME in windows system, IME works in browser but arrows key not work in the R studio editor panel. It could work again only when I switch to another window from browser and then focus back on the browser again.

### Describe the behavior you expected

After I've switched IME in windows system, arrows key could still work in Editor Panel in Rstudio server edition.

**Comment by ronblum** [comment]
@chigix Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

**Comment by DrRZ** [comment]
I've experienced the same bug on several of my systems:
Windows 10 ver 1809
RStudio preview version 1.2.1268 (Desktop version)

I was able to reproduce chigix's Win+space issue.
Previously, I had noticed that using the new Windows 10 saved clipboard feature, accessible through the Win+V shortcut, produces the same behaviour: after using the shortcut none of the navigation keys (arrows, home, end, pageup, pagedown) on the keyboard work in Rstudio. 

So this appears to occur with a number of Win+ shortcuts.

Switching focus to a different window (or opening the Start menu) then switching focus back to RStudio's window resolves the problem.

**Comment by DrRZ** [comment]
Still present on 1.2.1502. But I discovered a couple of things.

1. At least on one computer, when this happends the Delete key functions like the Backspace key.
2. Another workaround. Pressing the Alt key (to bring up the menu) then pressing it again (to close the menu) restores normal keyboard behaviour. Interestingly, after doing this, you can then repeatedly use Win+V or other Win+ shortcuts without any keyboard issues, but only so long as the Rstudio window retains focus. If you switch to another window the same problem will occur when you re-focus Rstudio's window, requiring the double-Alt press again.

**Comment by rtaseen** [comment]
I experience this on both my Windows 10 devices (I use windows+space to switch keyboard layouts). Thank you for the alt key workaround, it's faster than the window's key double-tap workaround I was using.

BTW this is probably the same bug that was reported 3 years ago [here](https://support.rstudio.com/hc/en-us/community/posts/211644927-Bug-report-vim-bindings-conflict-with-changing-keyboard-language-Windows-10-).

**Comment by DrRZ** [comment]
They seem to have fixed this bug in the 1.3 daily builds. The last 1.2 preview release I tried didn't have the fix. I've been using 1.3 daily builds simply because of this bug fix. I haven't encountered any new issues with 1.3 yet.
