### ISSUE TITLE
Can't start RStudio since 1.3.xxx development version

### ISSUE THREAD

**Issue by brainprint** [rstudio/rstudio#4266]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by brainprint** [comment]
RStudio Desktop
Version 1.3.11 (but any since 1.3.xx)
macOS High Sierra on MacBook Air Mid 2011
R 3.5.2

To reproduce the problem, just start the program. The attached pictures show my initial screen and even trying to reload it won't work (second picture). 

Everything is fine with version 1.2.1266 or below.

![screen shot 2019-02-05 at 01 45 31](https://user-images.githubusercontent.com/17748369/52249041-07829480-28e9-11e9-8538-9b53ac764971.png)

![screen shot 2019-02-05 at 01 58 27](https://user-images.githubusercontent.com/17748369/52249180-998a9d00-28e9-11e9-9bbf-918cdfdb9173.png)

**Comment by jmcphers** [comment]
1.3 isn't a beta (it's a very early development build). If you need stable builds, please use our preview release:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by brainprint** [comment]
@jmcphers Despite my mistake regarding beta, instead development build, I just would like to report the error. I am aware I am using an unstable version and I hope I am contributing to RStudio development.

**Comment by kevinykuo** [comment]
FYI I hit this every time when attempting to open a project, but works fine the second try. Running 56a8641b.

**Comment by jmcphers** [comment]
This is now fixed in 1.3 (see https://dailies.rstudio.com/). See also https://github.com/rstudio/rstudio/issues/4520.

**Comment by Saranya0721** [comment]
I have installed RStudio 1.2.1555 stable version in windows 10. I'm getting the same error( The site can't be reached). Please help on this.
