### ISSUE TITLE
Breakpoints show in editor but are not added to function

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4268]
I’m not sure how to reproduce it, but oftentimes when I put breakpoints (red circles next to the line numbers) in a function at a line where it would normally throw an error, source it (`debugSource`), and then run it, **when the breakpoint is past line 251 (e.g. at line 249 it works fine, but not at line 252)**, RStudio will fail to insert the breakpoint, i.e. the function does not show a red dot in the environment pane, and running it will give me a traceback pointing to the same line that has the breakpoint.

Putting a print statement before the line will successfully print whatever is there, and switching the breakpoint to the print statement instead will still not make it stop upon reaching it.

Only happens with large functions. I unfortunately cannot provide a reproducible example due to code being proprietary.

Setup: RStudio 1.2.1237, R 3.5.1, running on windows 10.

**Comment by david-cortes** [comment]
Small update: this also happens when trying to debug functions inside a package.

**Comment by jmcphers** [comment]
Sorry, we haven't been able to reproduce this and can't help without a reproducible example -- please feel free to reopen if you find one!
