### ISSUE TITLE
Can only set breakpoint inside one instance of multiple function assignments to the same object

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4269]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.1.4643 and 1.2.1228
    OS Version      : MacOS, Windows, Red Hat, etc.
    R Version       : 3.5.2

### Steps to reproduce the problem

1. In the Source pane, create the following R script:
```
a <- function(x){
  return(x + 2)
}
a <- function(x){
  return(x * 3)
}
a <- function(x){
  return(x^4)
}
```
2. Save it as `myfile.R`
3. In the console: `debugSource(fileName = "myfile.R")`
4. Set toggle points in the middle of each function, that is, the `return` lines: 2, 5, and 8

### Describe the problem in detail

After a file is debugged once, if an object in it is defined as a function multiple times, a breakbpoint can be set in the body of only one of the functions. The rest of the attempts will result in the warning, "Breakpoints can only be set inside the body of a function."

<img width="361" alt="toggle" src="https://user-images.githubusercontent.com/31009952/52282026-5e11c200-292d-11e9-8b2a-616846bdf14e.png">

### Describe the behavior you expected

Breakpoints should be settable in the bodies of all the functions.

**Comment by jmcphers** [comment]
You can't set breakpoints on the first two `a` functions because they don't exist (after this script is run there is only one function named `a` and it's the last one). What were you expecting here?

**Comment by ronblum** [comment]
I believe this falls under "user error."
