### ISSUE TITLE
RStudio Server corrupts tar.gz file on download

### ISSUE THREAD

**Issue by edonnachie** [rstudio/rstudio#4270]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1268
    OS Version      : Ubuntu 14.04
    R Version       : R 2.4.4

### Steps to reproduce the problem

- Build a package tar.gz
- Download tar.gz using the RStudio Server files panel
- Try to extract/list the downloaded archive using the tar command

### Describe the problem in detail

Package tar.gz files are corrupted when downloading via the RStudio server. It is possible to open the downloaded file in 7zip, but tar (and CRAN submission page) return an error.

Example files can be provided on request.

### Describe the behavior you expected

Downloading a tar.gz file from RStudio Server does not corrupt the archive.

**Comment by kfeinauer** [comment]
I am unable to reproduce this. My steps:

- I created a 70 MB .tar.gz file by running `tar -cvzf test.tar.gz <folder>` 
- Verified its contents via `tar -tvf test.tar.gz`.
- Downloaded the file locally via Chrome browser by browsing to the file and clicking `Export`
- Verified download tar via `tar -tvf ~/Downloads/test.tar.gz`

The above worked for all browsers, except I ran into the error while using Firefox! Did you happen to also be using Firefox? I will take a look to see what's going on.

**Comment by edonnachie** [comment]
Yes, I'm using current versions of Firefox on Windows.

**Comment by kfeinauer** [comment]
Interestingly enough, it appears that if you change the source file `.tar.gz` on the server, when you download the file and rename it on the client it will work correctly.

**Comment by dfalty** [comment]
Verified fixed 1.2.1317-1.
