### ISSUE TITLE
Add use of the "Export" button to an audit log

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rstudio#4273]
### System details

    RStudio Edition : RStudio Server (Pro)
    RStudio Version : 1.1.442 
    OS Version      : any
    R Version       : any

### Describe the problem in detail
Customers working with sensitive data need to be able to tell when someone downloads data files using the Export button in the Files pane of the IDE. When working with financial or personal information, in particular, it is necessary to monitor the transfer of data to people's individual machines. GDPR guidelines often require strict control on data flow, so it would be helpful to have audit capability on this button.

**Comment by jmcphers** [comment]
Auditing and monitoring is a Pro feature, so we'll track this over there. Thanks for filing!
