### ISSUE TITLE
RStudio 1.1.463 cannot build new projects

### ISSUE THREAD

**Issue by qswangstat** [rstudio/rstudio#4281]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.463
    OS Version      :  Windows 10 (Surface pro 6)
    R Version       :  3.5.2

### Describe the problem in detail

When I tried to create a new project, the RStudio does nothing. Then I wanted to exit, but the RStudio said "quitting R session..." and cannot be closed.

**Comment by jmcphers** [comment]
Sorry you're having trouble! You haven't provided a reproducible example or any diagnostics, though, so we don't know how to help you. Please consider adding more details and asking on our community forum: https://community.rstudio.com/c/rstudio-ide
