### ISSUE TITLE
Add --preclean to the default Install&Restart config?

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#4282]
Rising from issue filed here:

https://github.com/Rdatatable/data.table/issues/3366

I was hitting an issue with my package development routine of using `Install & Restart` before trying `test.data.table()`; not always but sometimes this creates a failed install where using the package at all segfaults.

As Matt noted there, adding `--preclean` to the build options seems to have fixed things; is there any reason not to include this by default? A speed implication I guess, but seems to be worth it as the bug is quite crippling.

On the command line my routine is to run `R CMD build . && R CMD INSTALL data.table_1.12.1.tar.gz` which works fine.

**Comment by kevinushey** [comment]
You can use <kbd>More -> Clean and Rebuild</kbd> to enforce the use of `--preclean`. Does that help?

**Comment by MichaelChirico** [comment]
Awesome, TIL!
