### ISSUE TITLE
Unable to open RStudio on macOS

### ISSUE THREAD

**Issue by wlq762** [rstudio/rstudio#4283]
### System details

    RStudio Edition : RStudio Desktop
    RStudio Version : 1.1.463, 1.1.456, 1.1.423, 1.1.383, 1.0.153 (I have tried many Rstudio versions.)
    OS Version : macOS Mojave 10.14.3
    R Version : 3.5.2

### Steps to reproduce the problem

I cannot open Rstudio on my MacBook Pro (15-inch, 2018) for a long time. When I try to open Rstudio, it appears a window saying:

Unexpected exception: Unmatched [ or [^ in character class declaration.  The error occurred while parsing the regular expression fragment: 'yd

### Describe the problem in detail

The diagnostics log is attached as follows:

Last login: Sat Feb 9 11:08:36 on ttys000

/Applications/RStudio.app/Contents/MacOS/diagnostics ; exit;

(base) wanglequndeMacBook-Pro:~ lequn$ /Applications/RStudio.app/Contents/MacOS/diagnostics ; exit;

Log file: rdesktop.log

(Empty)

Log file: rsession-lequn.log

20 Jan 2019 03:19:13 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

20 Jan 2019 03:19:13 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

20 Jan 2019 03:33:39 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

20 Jan 2019 03:33:39 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

20 Jan 2019 03:38:12 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

20 Jan 2019 03:38:12 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

22 Jan 2019 12:05:39 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

22 Jan 2019 12:05:39 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

23 Jan 2019 02:31:47 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

23 Jan 2019 02:31:47 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

25 Jan 2019 07:59:11 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

25 Jan 2019 07:59:11 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

25 Jan 2019 12:36:25 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

25 Jan 2019 12:36:25 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

27 Jan 2019 12:04:03 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

27 Jan 2019 12:04:03 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

27 Jan 2019 12:04:37 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

27 Jan 2019 12:04:37 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

27 Jan 2019 12:17:17 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/builder/rsbuild/work/src/cpp/r/session/RSession.cpp:812

27 Jan 2019 12:17:17 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/builder/rsbuild/work/src/cpp/session/SessionMain.cpp:2488

27 Jan 2019 12:17:34 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/builder/rsbuild/work/src/cpp/r/session/RSession.cpp:812

27 Jan 2019 12:17:34 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/builder/rsbuild/work/src/cpp/session/SessionMain.cpp:2488

27 Jan 2019 12:17:47 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/builder/rsbuild/work/src/cpp/r/session/RSession.cpp:812

27 Jan 2019 12:17:47 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/builder/rsbuild/work/src/cpp/session/SessionMain.cpp:2488

27 Jan 2019 12:21:01 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/builder/rsbuild/work/src/cpp/r/session/RSession.cpp:812

27 Jan 2019 12:21:01 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/builder/rsbuild/work/src/cpp/session/SessionMain.cpp:2488

27 Jan 2019 12:28:38 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/builder/rsbuild/work/src/cpp/r/session/RSession.cpp:812

27 Jan 2019 12:28:38 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/builder/rsbuild/work/src/cpp/session/SessionMain.cpp:2488

27 Jan 2019 12:31:42 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/builder/rsbuild/work/src/cpp/r/session/RSession.cpp:812

27 Jan 2019 12:31:42 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/builder/rsbuild/work/src/cpp/session/SessionMain.cpp:2488

27 Jan 2019 12:34:57 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /opt/conda/conda-bld/rstudio_1533220822756/work/src/cpp/r/session/RSession.cpp:813

27 Jan 2019 12:34:57 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void (anonymous namespace)::rSuicide(const std::string &) /opt/conda/conda-bld/rstudio_1533220822756/work/src/cpp/session/SessionMain.cpp:1023

27 Jan 2019 12:35:09 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /opt/conda/conda-bld/rstudio_1533220822756/work/src/cpp/r/session/RSession.cpp:813

27 Jan 2019 12:35:09 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void (anonymous namespace)::rSuicide(const std::string &) /opt/conda/conda-bld/rstudio_1533220822756/work/src/cpp/session/SessionMain.cpp:1023

27 Jan 2019 12:35:50 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /opt/conda/conda-bld/rstudio_1533220822756/work/src/cpp/r/session/RSession.cpp:813

27 Jan 2019 12:35:50 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void (anonymous namespace)::rSuicide(const std::string &) /opt/conda/conda-bld/rstudio_1533220822756/work/src/cpp/session/SessionMain.cpp:1023

27 Jan 2019 12:40:11 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

27 Jan 2019 12:40:11 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

09 Feb 2019 02:30:03 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

09 Feb 2019 02:30:03 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

09 Feb 2019 02:30:27 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

09 Feb 2019 02:30:27 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

09 Feb 2019 02:40:04 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

09 Feb 2019 02:40:04 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

09 Feb 2019 02:42:01 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

09 Feb 2019 02:42:01 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

09 Feb 2019 02:45:36 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:756

09 Feb 2019 02:45:36 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:2179

09 Feb 2019 02:57:24 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

09 Feb 2019 02:57:24 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

09 Feb 2019 03:10:57 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

09 Feb 2019 03:10:57 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

09 Feb 2019 03:25:37 [rsession-lequn] ERROR Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: int rstudio::r::session::RReadConsole(const char *, CONSOLE_BUFFER_CHAR *, int, int) /Users/rstudio/rstudio/src/cpp/r/session/RSession.cpp:813

09 Feb 2019 03:25:37 [rsession-lequn] ERROR R SUICIDE: Unexpected exception: Unmatched [ or [^ in character class declaration. The error occurred while parsing the regular expression fragment: 'yd; LOGGED FROM: void <anonymous namespace>::rSuicide(const std::string &) /Users/rstudio/rstudio/src/cpp/session/SessionMain.cpp:1023

logout

Saving session...

...copying shared history...

...saving history...truncating history files...

...completed.

Deleting expired sessions...10 completed.

### Describe the behavior you expected

Could someone help me fix this problem? Thanks a lot!

**Comment by jmcphers** [comment]
This problem is usually caused by pathological characters in the `PATH` environment variable. What does `echo $PATH` return for you in the Terminal?

**Comment by wlq762** [comment]
Last login: Tue Feb 12 09:21:25 on ttys000
(base) wanglequndeMacBook-Pro:~ lequn$ `echo $PATH`
`/Users/lequn/anaconda3/bin:/Users/lequn/anaconda3/condabin:/Applications/Aspera Connect.app/Contents/Resources:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:b0VIM 8.0:/opt/X11/bin:`

**Comment by jmcphers** [comment]
Glad you're up and running! It's a known issue that some characters in $PATH cause startup to fail (we're treating them as a regex but shouldn't). It's being tracked here:

https://github.com/rstudio/rstudio/issues/2079
