### ISSUE TITLE
RStudio API Function to get the current directory of the "Files" pane

### ISSUE THREAD

**Issue by HFDave** [rstudio/rstudio#4284]
Hello,

There are already similar API functions like: .rs.getProjectDirectory(), .rs.api.getActiveDocumentContext(), .rs.api.getSourceEditorContext().

I think it would be really great to have a function e.g. .rs.api.getFilesPaneDirectory() which will return current "working" directory of the "Files" pane. This would facilitate running scripts in the Files pane directory context, traverse directory trees while converting and/or fixing data easily. I believe there would be a lot of use for this function and RStudio should offer this feature as a part of basic level of connectivity between the IDE and scripts.

In fact, I was quite surprised that there is no such "basic" function seeing there are more complex ones already. I spent some serious time looking for it so I hope I have not overlooked something.

Thank you for all the great work and consideration of this feature request.

**Comment by jmcphers** [comment]
No, we don't have this yet. Appreciate the suggestion!

**Comment by HFDave** [comment]
Jonathan, thank you very much for your interest and quick reply. If you will be working on this one day, a logical step would be to implement .rs.api.setFilesPaneDirectory() as well.

I haven't been thinking about this functionality as I did not need it but someone else would and it sounds logical after all. The more I am thinking about it, the more benefits I can think of.

Once again, thank you.

**Comment by Buedenbender** [comment]
Hi, I was just looking for exactly this function setFilesPaneDirectory.
Is it available in the meantime?
