### ISSUE TITLE
How to use RStudio as Multi-Threading and multi-tenancy programing?

### ISSUE THREAD

**Issue by Sanjaysaini24** [rstudio/rstudio#4285]
Hi All,

I have created a program using R-Studio and converted it into Rest API to access from the web.
I use Plumber to receive the API calls. 
I am facing the following challenge:
When I make multiple requests from the different resources it makes a queue of the calls and then works on them.
Is it possible for RStudio to handle all the requests at the same time as java does in multithreading?

Is there any way to use RStudio as multi-tenancy and multi-threading?

**Comment by david-cortes** [comment]
This is not the kind of place to ask such question - for starters, that's something to do with `plumber`, which is separate from `RStudio`. I'd suggest you to try other sites such as stackexchange.

**Comment by jmcphers** [comment]
Our community forum is also good place to ask this. I'd suggest trying the R Admins group:

https://community.rstudio.com/c/r-admin
