### ISSUE TITLE
Clicking “Replace All” takes focus to the end of file

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4287]
**Steps to reproduce:**
1. Open some R file that would be long-enough to be scrollable.
2. Choose some word repeated multiple times.
3. Adjust section in scrollbar to focus on the last times the word occurs in the document, while leaving something else beneath.
4. Double click word to replace.
5. Press `Ctrl` + `F`.
6. Write something to replace it with on the pop-up.
7. Click `All`.

**Expected behavior:**
Should leave the focus just where it was before doing replacements.

**Actual behavior:**
Under some situations which I haven’t been able to identify, shifts focus to the end of the file after doing the replacements.

**Setup:** RStudio 1.2.1237, R 3.5.1, running on Windows 10.

**Comment by ronblum** [comment]
For what it's worth, I can reproduce this on the MacOS with requiring scrolling in steps (1) and (3) using RStudio Desktop 1.2.1268 on MacOS 10.14, and RStudio Server 1.2.1268 on Red Hat.

**Comment by sgrote** [comment]
Just to upvote and maybe reopen this issue: I would also very much prefer the focus to stay where it was and not jump to the end of the file upon "Replace All". Thanks a lot!
