### ISSUE TITLE
More consistent wording for gestures that say "install my package"

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#4289]
Capturing a conversation from Slack.

For a package that doesn't have a Makefile, *Build > Install and Restart* and *Build > More > Clean and Rebuild* seem to be equivalent. But the difference in wording makes one wonder if there's more to the story.

It would be nice if the wording made the similarity more obvious. Of the two, "Install and Restart" is the more favoured wording.

**Comment by kevinushey** [comment]
My understanding here:

- "Install and Restart" -> `R CMD INSTALL`
- "Clean and Rebuild" -> `R CMD INSTALL --preclean`

I'm not sure what the best language to separate these options is. Maybe:

- "Install Package" -> `R CMD INSTALL`
- "Clean and Install" -> `R CMD INSTALL --preclean`

I think the "Restart" bit is superfluous since at this point it's well-understood that package-related actions will necessitate a session restart.

**Comment by DesiQuintans** [comment]
Could it be simplified by removing one of the options? Is there a reason *not* to `--preclean`?

**Comment by kevinushey** [comment]
Perhaps instead we should have a checkbox like:

```r
[ ] Clean before install
```

that toggles whether the `Install Package` action runs with `--preclean` or not (since I figure normally if you want to preclean during install for a package you always want to do so).

**Comment by DataStrategist** [comment]
Considering `preclean` does this: `--preclean remove files created during a previous run`... I also don't see any incentive to not doing this by default. And yes, I'd also like this fixed, in fact, if Jenny hadn't opened an issue I would have done so now :)

**Comment by kieran-mace** [comment]
spent quite a while trying to find this answer as someone who has recently started building packages.

**Comment by DataStrategist** [comment]
Well,  if this won't be built into Rstudio, then I'll leave here the solution I built and put into my convenience package, hopefully it's useful to someone down the line. :)

```
#' @rdname pleaseForTheLoveOfGodLetMeBuild
#' @export
#' @importFrom purrr map
#' @importFrom dplyr %>%
pleaseForTheLoveOfGodLetMeBuild <- function(paff = ".."){
  ## Remove Rcheck and *.tar.gz
  list.files(paff, pattern = "Rcheck", full.names = TRUE) %>% purrr::map(~unlink(., recursive = TRUE))
  list.files(paff, pattern = "tar.gz", full.names = TRUE) %>% purrr::map(~file.remove(.))

  ## Remove those 00LOCK jerk folders
  .libPaths() %>% purrr::map(~list.files(path = ., pattern = "00LOCK", full.names = TRUE)) %>% unlist %>%
    purrr::map(~unlink(., recursive = TRUE))
}
```

**Comment by kevinushey** [comment]
Revisiting this again, my marginal preference would be to stick with a single `Install and Restart` button, but have `--preclean` turned on by default. (So, we'd remove `Clean and Rebuild`).

We could provide a preference to disable the use of `--preclean` if required.

**Comment by mikebessuille** [comment]
Related: https://github.com/rstudio/rstudio/issues/1766

**Comment by jgutman** [comment]
Verified on RStudio Desktop 2022.06.0-daily+89 with MacOS Monterey 12.2, running R x86_64 4.2 under development.
