### ISSUE TITLE
Unfolding a heading should keep subheadings folded

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#4290]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.463
    OS Version      :  Windows 7 64-bit
    R Version       :  3.5.1

### Steps to reproduce the problem

Create an Rmarkdown file with this text in it:

```
# Heading 1
Lorem ipsum dolor sit amet
## Heading 2
consectetur adipiscing elit
## Heading 2b
sed do eiusmod tempor incididunt
### Heading 3
ut labore et dolore magna aliqua.
```

Fold Heading 1 to hide all of its children, and then unfold it. All of the children of Heading 1 will be unfolded completely.

### Describe the behavior you expected

The headings should be unfolded down to the next heirarchical level only, so unfolding Heading 1 should only show:

```
# Heading 1
Lorem ipsum dolor sit amet
## Heading 2
## Heading 2b
```

Which is to say, the content under the second-level headings won't be shown until they are specifically unfolded. This is how things work in Emacs' org-mode and this, together with _toggling_ folding ([another Issue in this repo](https://github.com/rstudio/rstudio/issues/2033)) makes navigating a complex document very fast.

Thanks!

**Comment by ronblum** [comment]
@DesiQuintans The current behavior matches vi's. Should the default match vi's method or emacs when in org mode? I'll mark this as an enhancement to review as continue development of RStudio.

**Comment by DesiQuintans** [comment]
@ronblum Thanks, Ron. Microsoft Word's Outline View also deserves a mention. `Alt+Shift+-` will fold all Level 6s, then all Level 5s, etc. under the heading that's currently under the caret, working backwards until there's nothing left to fold. `Alt+Shift+=` will start unfolding in reverse. Body text will not be unfolded until all headings are unfolded.

This is probably one of the best and least-used features of MS Word, it shows me the heading structure of the document while delaying the display of the body text for as long as possible. It'd be great in RMarkdown.
