### ISSUE TITLE
Extract variable produces invalid R code

### ISSUE THREAD

**Issue by pstern** [rstudio/rstudio#4296]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1268
    OS Version      : Win 10
    R Version       : 3.5.2

### Steps to reproduce the problem

Given some code (requires dplyr): 

```r
iris %>% 
  mutate(new = Petal.Length - 123)
```

Select '123' and execute the 'Extract Variable' function. 
Name the variable (e.g. 'amount').

This generates this output:

```r
iris %>% 
  amount <- 123
  mutate(new = Petal.Length - amount)
```

### Describe the problem in detail

The code generated by the refactoring is no longer valid R code. 

### Describe the behavior you expected

Refactorings should generate valid code with the same logical result as the original code.

A valid, logically equivalent alternative which could be generated in this case is:

```r
amount <- 123
iris %>% 
  mutate(new = Petal.Length - amount)
```

**Comment by ronblum** [comment]
@pstern Thank you for the suggestion. We'll take a look at it as we continue development of RStudio.

**Comment by pstern** [comment]
@ronblum Thank you. I have encountered similar problems with Extract Function and there are likely synergies in any improvements. 

Here is a similar example of that feature failing in a similar case:

```r
iris %>% 
  mutate(new = Petal.Length - 123)
```

Select 'Petal.Length - 123' and execute the 'Extract Function' function. 
Name the function (e.g. 'sub_fun').

This generates this output:

```r
iris %>% 
  mutate(new = 
sub_fun <- function(Petal.Length) {
  Petal.Length - 123
})
```

**Comment by ronblum** [comment]
@pstern Thanks for checking! Can you confirm that the correct code is being generated, just not where you would expect it to be?

**Comment by pstern** [comment]
@ronblum In the case of the variable extraction that appears to be correct. However, in the case of the function extraction it doesn't appear that a valid call to the newly created function is added. Moving the function would result in this code: 

```r
sub_fun <- function(Petal.Length) {
  Petal.Length - 123
}
iris %>% 
  mutate(new = )
```


When something more like this is actually expected:

```r
sub_fun <- function(x) {
  x - 123
}
iris %>% 
  mutate(new = sub_fun(Petal.Length))
```

**Comment by ronblum** [comment]
@pstern Ah, got it. Thank you! I'll mark this as a bug, since it appears to also be providing incorrect code.

**Comment by pstern** [comment]
@ronblum Thank you. To the degree it matters, I think that is a more accurate characterization.
