### ISSUE TITLE
rstudio 1.2 has runtime dependency on homebrew dynlib

### ISSUE THREAD

**Issue by jeroen** [rstudio/rstudio#4297]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1268
    OS Version      :  MacOS
    R Version       : latest

### Summary

The rstudio callback executable used for `git` and `ssh` password entry seems to have been linked to openssl dynamic libraries from homebrew. Therefore the password prompt will not work if the user does not have homebrew installed:

```
otool -L /Applications/RStudio.app/Contents/MacOS/rpostback
```

Gives

```
/Applications/RStudio.app/Contents/MacOS/rpostback:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 775.19.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
```

Note the stuff under `/usr/local/opt` is homebrew specific and won't be installed on most machines. I think the intention is to link to openssl in`/Applications/RStudio.app/Contents/Frameworks` ? You can use `install_name_tool` to change the path:

```
install_name_tool -change \
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib \
  /Applications/RStudio.app/Contents/Frameworks/libssl.1.0.0.dylib \
  /Applications/RStudio.app/Contents/MacOS/rpostback

install_name_tool -change \
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib \
  /Applications/RStudio.app/Contents/Frameworks/libcrypto.1.0.0.dylib \
  /Applications/RStudio.app/Contents/MacOS/rpostback
  
```

### Steps to reproduce the problem

If you have homebrew, first makes sure openssl is not installed:

```
brew remove openssl --ignore-dependencies
```

And then for example:

```r
processx::run("/Applications/RStudio.app/Contents/MacOS/postback/rpostback-askpass", "test")
```

**Comment by jmcphers** [comment]
We bundle OpenSSL on MacOS, but I think the actual link path is to Homebrew's OpenSSL (which we compile against at build time). We probably just need to fix up `rpostback-askpass` in the same way that we fix up `diagnostics` here.

https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/cpp/diagnostics/CMakeLists.txt#L68-L76
