### ISSUE TITLE
Run the next chunk shortcut

### ISSUE THREAD

**Issue by pslacerda** [rstudio/rstudio#4298]
I'm looking for the <kbd>Ctrl+Alt+P</kbd> equivalent for the next chunk. 

<kbd>Ctrl+Alt+N</kbd> runs the next chunk but also advances the cursor.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.243
    OS Version      : Ubuntu

**Comment by jmcphers** [comment]
We have not had any other votes or requests for this in over a year, so closing for now.
