### ISSUE TITLE
Cannot change the theme color for comments and chunk options

### ISSUE THREAD

**Issue by egonulates** [rstudio/rstudio#4299]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1268
    OS Version      :  Windows 10
    R Version       : 3.5.2

### Describe the problem in detail
I could not find an option to change chunk color in editor. I can change the color of comments as I wish but Chunk color also changes. 

[Here is a snapshot](https://imgur.com/a/injV8pu)

### Describe the behavior you expected
Ability to separately change the color for comment and chunk options.

**Comment by ronblum** [comment]
@gonulate I believe this is an enhancement request, so I'll mark it as one. That said: @kevinushey is the current expected behavior? Thank you both!

**Comment by kevinushey** [comment]
Sorry for taking so long to follow up. In Sweave documents, chunk headers / footers are giving comment styles, e.g.

![Screen Shot 2019-03-22 at 10 20 49 AM](https://user-images.githubusercontent.com/1976582/54841299-4055ad80-4c8c-11e9-9a89-794c327cdcba.png)
![Screen Shot 2019-03-22 at 10 20 44 AM](https://user-images.githubusercontent.com/1976582/54841300-4055ad80-4c8c-11e9-804a-1300f7102e07.png)

so a workaround would be to provide explicit styles for `.comment.codebegin` and `.comment.codeend`.
