### ISSUE TITLE
PDF preview in fullscreen mode - SumatraPDF

### ISSUE THREAD

**Issue by gk-crop** [rstudio/rstudio#4301]
When knitting a rmarkdown document to pdf, the bundled SumatraPDF viewer is started. Unfortunately fullscreeen mode is disabled, as the file `bin/sumatra/sumatrapdfrestrict.ini` is missing the setting
`FullscreenAccess = 1`
Adding this option by default would be very helpful, especially when working with pdf beamer presentations.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1268
    OS Version      : Win7
    R Version       : 3.52

### Steps to reproduce the problem

Knit RMarkdown (beamer presentation) to PDF, view the file in bundled SumatraPDF, hit F5 (or CTRL+L) to switch to fullscreen mode.

### Describe the problem in detail

SumatraPDF does not allow fullscreen mode as it uses `bin/sumatra/sumatrapdfrestrict.ini`, where fullscreen mode has to be explicitely enabled via `FullscreenAccess = 1`

### Describe the behavior you expected

SumatraPDF switches to fullscreen when hitting F5

**Comment by kevinushey** [comment]
Perhaps worth comparing what we have with the default version at https://github.com/sumatrapdfreader/sumatrapdf/blob/master/docs/sumatrapdfrestrict.ini now.

**Comment by shangeconnew** [comment]
Excuse me, I have another question: my RStudio does not have the boundled sumatraPDF viewer, I wonder if there is any way I could install it. thanks!
