### ISSUE TITLE
Feature Request: Shortcuts to run in terminal, equivalence with consol

### ISSUE THREAD

**Issue by griffinevo** [rstudio/rstudio#4304]
Currently there are some keyboard shortcuts in RStudio which allow us to run code into the console from the beginning of a script to the current line ('command + option + B') or run the entire script ('command + shift + return').

It would be nice if we could have a terminal equivalent of these like we do for run current line (which is 'command + return' to send to the console and 'command + option + return' to send to the terminal). Is it possible to add these two shortcuts (and any other relevant equivalents such as from current line to end)?

**Comment by maxheld83** [comment]
I'm not sure I 100% understand, but I think this currently *does* exist in Version 1.2.1303 (preview release):

<img width="293" alt="screenshot" src="https://user-images.githubusercontent.com/5372770/53887214-1b253600-4022-11e9-92ae-59c5d1655bb8.png">

Works like a charm for REPLing something from a `script.sh` inside RStudio.

**Comment by kendonB** [comment]
These are all the commands I see for the terminal in the latest preview:

![image](https://user-images.githubusercontent.com/5327505/55923397-88e40380-5c59-11e9-9b19-d6b4dd9c703a.png)

Still just Ctrl+Alt+Enter for the terminal. OP is asking for terminal equivalents for all execute commands.

Perhaps Ctrl-Alt-Shift B for "Send From Beginning To Line to Terminal" etc.

I would also add that if the source file is a .R, that "Send to Terminal" behaves just like "Run Selected Line(s)", where it will run the full command if the command is separated over multiple lines.

**Comment by griffinevo** [comment]
@maxheld83 those send the script to the _console_, I would like something that offers the same versatility for the _terminal_ (not _just_ 'send to terminal', but features like 'Run from beginning to line **in terminal**' as @kendonB suggests).
