### ISSUE TITLE
Feature request: Open multiple files

### ISSUE THREAD

**Issue by zx8754** [rstudio/rstudio#4306]
### System details
    RStudio Edition : Desktop
    RStudio Version : Version 1.1.453
    OS Version      : Windows 7 x64 (build 7601) Service Pack 1
    R Version       : R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"

Similar to #3248 , but I want to select multiple files from the menu:
File > Open File... > "select multiple files" > "click open"

This is useful when developing ShinyApps. Usually we have `global.R`, `ui.R`, and `server.R` files, and I would want to open all of them at once.

Or feature request could be that if selected item is a shiny file then open other related files, too?

**Comment by ronblum** [comment]
@zx8754 Thank you for the suggestion! We'll take a look at it as we continue development of RStudio.

**Comment by red-swan** [comment]
I second this feature request.

**Comment by zx8754** [comment]
Related SO post:

- [How to open multiple R scripts at once?](https://stackoverflow.com/q/76001557/680068)
