### ISSUE TITLE
Feature request: when the source pane is zoomed, do not show console when sourcing file

### ISSUE THREAD

**Issue by JazzyPierrot** [rstudio/rstudio#4307]
RStudio Edition : Desktop  
    Rstudio Version : 1.1.463
    OS Version      :  Ubuntu 18.04
    R Version       :  3.5.2

I sometimes want to do some long (understand: at least a couple of minutes) edits on a source file, and to do this without being bothered by the cluttered panes, I zoom on the source pane (Ctrl + Shift + 1). 
However, if the "source on save" box is checked, each time I want to save my file, the zoomed full-screen console pops-up. 

I would greatly appreciate to be able to edit and save files, including with "source on save" option, without the console popping up. 
Regards.

**Comment by ronblum** [comment]
@JazzyPierrot Thanks for the feature request. We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by jmcphers** [comment]
No other votes for this in well over a year, so closing.
