### ISSUE TITLE
RStudio installation on AIX

### ISSUE THREAD

**Issue by J-Z-C** [rstudio/rstudio#4308]
Is there any information available regarding the installation of RStudio (open source) on AIX?  I understand AIX is not a supported OS for RStudio, but I have unused capacity on AIX servers and would like to use RStudio there.

I have the link to RStudio dependencies on Linux, and will review them in detail, but would like to hear from anyone who can identify specific issues with regard to an AIX installation.

Thanks;
- John

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions. You might try the R Admins section for this question.

https://community.rstudio.com/c/r-admin

Hope you're able to find what you're looking for!

**Comment by J-Z-C** [comment]
Thanks - that is the information I was looking for.

- JC
