### ISSUE TITLE
Rendering of htmlwidget correct in browser and incorrect in RStudio

### ISSUE THREAD

**Issue by ifellows** [rstudio/rstudio#4311]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1268 
    OS Version      :  Mac OS 10.4.3
    R Version       :  3.5.2

### Steps to reproduce the problem
Create a markdown chunk with the following code
```{r}
library(threejs)
z <- seq(-10, 10, 0.1)
x <- cos(z)
y <- sin(z)
scatterplot3js(x, y, z, color=rainbow(length(z)))
```
knit it and view it in 
1. the popout viewer
2. chrome
3. the pane viewer (when run in console)

### Describe the problem in detail

Points are not rendered in the RStudio viewers, but chrome, firefox and safari render them fine.

![screen shot 2019-02-13 at 1 46 19 pm](https://user-images.githubusercontent.com/562061/52746623-cba99800-2f96-11e9-8bfb-daca42dfb713.png)

**Comment by ifellows** [comment]
Looks like this is related to #3573 as I get the same error they were encountering. I guess my 2013 Mac Pro is considered "Old," but it is still a powerhouse. I can confirm that the error does not occur on my 2017 macbook pro.


also potentially related (though not helpful): https://forum.qt.io/topic/78319/qwebengineview-has-error-webgl-pages-on-mac-pro

**Comment by kevinushey** [comment]
Does it make a difference if you adjust any of the rendering-related options here?

![screen shot 2019-02-13 at 3 03 45 pm](https://user-images.githubusercontent.com/1976582/52750247-986c0680-2fa0-11e9-85c0-1b9523babfa7.png)

We are still planning an update for RStudio v1.2 which may yet resolve these sorts of issues but unfortunately cannot make any promises yet.

**Comment by ifellows** [comment]
no, I tried all the permutations, and no difference. Is that update in master, or on your private branch? If it is public I can check it out.

**Comment by kevinushey** [comment]
Sorry, we don't have a public build with this fix yet. We're working to make that happen soon.

**Comment by kevinushey** [comment]
Can you also share the output of <kbd>Help -> Diagnostics -> Show GPU Diagnostics</kbd>?

I just recalled that we had to screen out FirePro GPUs because of rendering issues we saw in the past:

https://github.com/rstudio/rstudio/blob/90bdf8cb569026e93aa792a71bcc3e08a03d8b9a/src/cpp/desktop/DesktopMain.cpp#L523-L525

Perhaps we can take that out with the update to Qt 5.12.1. (will mark this as a v1.2 issue so we consider that option)

**Comment by ifellows** [comment]
Output is below. I seem to remember that the FirePro's made for apple at that time were slightly custom. Could be wrong though.

If the blacklist was the problem, wouldn't that be taken care of when I uncheck the "Use GPU blacklist" option?

-------------

Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
CheckerImaging: Disabled
Flash: Software only. Hardware acceleration disabled
Flash Stage3D: Software only. Hardware acceleration disabled
Flash Stage3D Baseline profile: Software only. Hardware acceleration disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Software only. Hardware acceleration disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable
Problems Detected
Accelerated video decode has been disabled, either via blacklist, about:flags or the command line.
Disabled Features: video_decode
Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
Disabled Features: native_gpu_memory_buffers
Checker-imaging has been disabled via finch trial or the command line.
Disabled Features: checker_imaging


Data exported | 2019-02-15T17:37:34.963Z
-- | --
Chrome version | RStudio/1.2.1268
Operating system | Mac OS X 10.14.3
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/926d27280b919a1aeb0091392d56f63a38d2bc0b/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/65 35ee3617fcb08e0d79e6b9e6c05db23cc9416d4f-
Command Line | /Applications/RStudio.app/Contents/MacOS/RStudio --enable-viewport --disable-renderer-accessibility --disable-prefer-compositing-to-lcd-text --disable-gpu --browser-subprocess-path=/Applications/RStudio.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess --enable-threaded-compositing --disable-zero-copy --disable-gpu-memory-buffer-compositor-resources --disable-gpu-memory-buffer-video-frames --disable-mojo-local-storage --disable-accelerated-video-decode --disable-pepper-3d-image-chromium --disable-native-gpu-memory-buffers --enable-features=AllowContentInitiatedDataUrlNavigations --disable-features=SurfaceSynchronization --disable-features=SurfaceSynchronization,TouchpadAndWheelScrollLatching --use-gl=desktop --in-process-gpu --gpu-preferences=KAAAAAAAAAAmAQAAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAHAAAAANAAAAaAAAAAAAAABwAAAAAAAAAHgAAAAAAAAAgAAAAAAAAACIAAAAAAAAAJAAAAAAAAAAmAAAAAAAAACgAAAAAAAAAKgAAAAAAAAAsAAAAAAAAAC4AAAAAAAAAMAAAAAAAAAAyAAAAAAAAAAQAAAAAAAAAAAAAAALAAAAEAAAAAAAAAAAAAAADAAAABAAAAAAAAAAAAAAAA4AAAAQAAAAAAAAAAAAAAARAAAAEAAAAAAAAAAAAAAAEgAAABAAAAAAAAAAAQAAAAsAAAAQAAAAAAAAAAEAAAAMAAAAEAAAAAAAAAABAAAADgAAABAAAAAAAAAAAQAAABEAAAAQAAAAAAAAAAEAAAASAAAAEAAAAAAAAAADAAAACwAAABAAAAAAAAAAAwAAAAwAAAAQAAAAAAAAAAMAAAAOAAAA --use-gl=swiftshader-webgl --gpu-vendor-id=0x1002 --gpu-device-id=0x6810 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x1002 --gpu-secondary-device-ids=0x6810 --gpu-active-vendor-id=0x1002 --gpu-active-device-id=0x6810


Initialization time | 55
-- | --
In-process GPU | true
Passthrough Command Decoder | false
Direct Composition | false
Supports overlays | false
Sandboxed | false
GPU0 | VENDOR = 0x1002, DEVICE= 0x6810 *ACTIVE*
GPU1 | VENDOR = 0x1002, DEVICE= 0x6810
Optimus | false
Optimus | false
AMD switchable | false
Driver vendor |  
Driver version |  
Driver date |  
Pixel shader version |  
Vertex shader version |  
Max. MSAA samples |  
Machine model name | MacPro
Machine model version | 6.1
GL_VENDOR |  
GL_RENDERER |  
GL_VERSION |  
GL_EXTENSIONS |  
Disabled Extensions |  
Disabled WebGL Extensions |  
Window system binding vendor |  
Window system binding version |  
Window system binding extensions |  
Direct rendering | Yes
Reset notification strategy | 0x0000
GPU process crash count | 0


Tile Update Mode | One-copy
-- | --
Partial Raster | Enabled




ATC | Software only
-- | --
ATCIA | Software only
DXT1 | Software only
DXT5 | Software only
ETC1 | Software only
R_8 | Software only
R_16 | Software only
RG_88 | Software only
BGR_565 | Software only
RGBA_4444 | Software only
RGBX_8888 | Software only
RGBA_8888 | GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE
BGRX_8888 | GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE
BGRX_1010102 | Software only
BGRA_8888 | GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE
RGBA_F16 | Software only
YVU_420 | Software only
YUV_420_BIPLANAR | GPU_READ, SCANOUT
UYVY_422 | GPU_READ, SCANOUT

**Comment by kevinushey** [comment]
No, because that particular bit of code overrides any user-requested options (we always force software rendering in that particular configuration). I think we can back out that change for Qt 5.12.1.

**Comment by kevinushey** [comment]
(the 'blacklist' referred to in that option is a Chromium-internal GPU blacklist; the one I'm referring to and linked to in the code is RStudio's own blacklist. Sorry for the confusion.)

**Comment by kevinushey** [comment]
I think this should be fixed in the latest preview release as we've now removed AMD FirePro from the blacklist:

https://github.com/rstudio/rstudio/blob/5d0b58cd10738cc8cc7a536aff446079791cda34/src/cpp/desktop/DesktopMain.cpp#L524-L526

**Comment by ifellows** [comment]
I can confirm that the issue is resolved on my machine.
