### ISSUE TITLE
Error in if (diff > 120) return("STALE") :  missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by peter-fm** [rstudio/rstudio#4312]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.2.1256
    OS Version      : Windows 10
    R Version       : 3.4.0 (2017-04-21) 

### Steps to reproduce the problem
When I open a saved project it prints to the console:
```
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
```
### Describe the problem in detail
Googling for solutions shows the relevant line in `SessionPackages.R` where it does:
```
 info <- file.info(dir)
   diff <- difftime(Sys.time(), info$mtime, units = "secs")
   if (diff > 120)
      return("STALE")

```
when I run `file.info(getwd())` it returns:
```
                   size isdir mode mtime ctime atime exe
D:/users/me/R/test    0  TRUE  777  <NA>  <NA>  <NA>  no
```
so maybe an `NA` values in `info$mtime` are messing it up?
### Describe the behavior you expected
Doesn't appear to have any effect other than being a bit annoying.

Session info
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0  tools_3.4.0     packrat_0.4.8-1

**Comment by kevinushey** [comment]
That seems likely to me. Do you also see an `NA` mtime for regular files, as opposed to directories?
