### ISSUE TITLE
Small freeze after typing … + ) + right arrow in function definition

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4320]
**Steps to reproduce:**
* Declare some function with `...` as last argument
* Insert closing parenthesis right after typing that
* Press right arrow

**Expected behavior:**
Nothing special should happen.

**Actual behavior:**
RStudio freezes for a moment. It’s especially noticeable in low-end laptops without SSD.

**Reproducible:** always

**Setup:** RStudio 1.2.1237 or 1.2.1268, R 3.5.0 or 3.5.1, running on either windows 10 or linux.

I’m not entirely sure about it, but I recall this didn’t happen in version 1.1

Example:
```r
fun = function(x, ...
```
(complete with parenthesis and right arrow)

**Comment by kevinushey** [comment]
Sorry, but I'm not able to reproduce. Are you attempting to type this into an empty R document? Or is there other code in the document that needs to exist before the issue is triggered?

**Comment by david-cortes** [comment]
> Sorry, but I'm not able to reproduce. Are you attempting to type this into an empty R document? Or is there other code in the document that needs to exist before the issue is triggered?

Happens in both empty documents and filled-in documents, and in different computers too. Do you have a powerful cpu? Perhaps if you leave something that uses all cpu running in the background you'll then notice the difference between ending the function in `...` or something else and then pressing right arrow.

**Comment by david-cortes** [comment]
@kevinushey : I think I found how to reproduce it: it happens when the source pane is at the bottom-left and the console pane at the top-left, but not with the default layout.

**Comment by kevinushey** [comment]
Interesting. By any chance does the issue still occur if you disable automatic completions?

![Screen Shot 2019-03-12 at 11 38 47 AM](https://user-images.githubusercontent.com/1976582/54226602-6b394800-44bb-11e9-8273-fbe2d3bcad3a.png)

I _think_ I'm seeing something like what you're reporting but just want to confirm.

**Comment by david-cortes** [comment]
> Interesting. By any chance does the issue still occur if you disable automatic completions?
> 
> ![Screen Shot 2019-03-12 at 11 38 47 AM](https://user-images.githubusercontent.com/1976582/54226602-6b394800-44bb-11e9-8273-fbe2d3bcad3a.png)
> 
> I _think_ I'm seeing something like what you're reporting but just want to confirm.

Seems it doesn't occur anymore if I set the code completion with manually.

**Comment by kevinushey** [comment]
Note to self: suspect issue is because we automatically provide completions after typing `...`, which brings in a very large list of completion options.
