### ISSUE TITLE
rsconnect deployment errs with custom repos option

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#4324]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1286
    OS Version      : macOS 10.14.3
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create a Shiny application (anything)
2. In the console: `options(repos='https://cran.rstudio.com/')`
3. Deploy the Shiny application either to shinyapps.io or RStudio Connect

### Describe the problem in detail

The *Deploy* pane errs with:

```
Error: unexpected '=' in "{ options(repos = c( ="
Execution halted
```

### Describe the behavior you expected

Expected deployment to succeed. 

Workarounds:
* Use a named `repos` option: `options(repos=list(CRAN='https://cran.rstudio.com/'))`
* Use `rsconnect::deployApp` rather than push-button deploy.

I removed `rsconnect` and let the IDE re-install the "proper" version of the package to rule out a custom `rsconnect` build.

Output from `packageVersion("rsconnect")`:

```
Package: rsconnect
Type: Package
Title: Deployment Interface for R Markdown Documents and Shiny
       Applications
Version: 0.8.13
Author: JJ Allaire
Maintainer: Jonathan McPherson <jonathan@rstudio.com>
Description: Programmatic deployment interface for 'RPubs',
       'shinyapps.io', and 'RStudio Connect'. Supported content
       types include R Markdown documents, Shiny applications,
       Plumber APIs, plots, and static web content.
Depends: R (>= 3.0.0)
Imports: openssl, RCurl, jsonlite, packrat (>= 0.4.8-1), yaml (>=
       2.1.5), rstudioapi (>= 0.5)
Suggests: knitr, testthat, rmarkdown (>= 1.1), plumber (>= 0.3.2),
       reticulate, shiny, sourcetools, xtable
License: GPL-2
RoxygenNote: 6.1.1
NeedsCompilation: no
Packaged: 2019-01-10 19:15:46 UTC; jmcphers
Repository: CRAN
Date/Publication: 2019-01-10 19:50:03 UTC
Built: R 3.5.2; ; 2019-01-11 05:35:49 UTC; unix
```

**Comment by dfalty** [comment]
Verified fixed 1.2.1312.
