### ISSUE TITLE
Add "JavaScript Script" option to new file button/menu

### ISSUE THREAD

**Issue by cbeers** [rstudio/rstudio#4328]
My workflow includes working with JavaScript files all day. I use the RStudio IDE to edit the .js files that are part of our company's product. This allows me to use a single IDE for all my work due to RStudio's incredible wealth of features. And it makes documentation a breeze as RMarkdown is right at my finger tips.

It would be fantastic if I could open a true JS file type and cut and paste code into it and *have it immediately apply syntax coloring*. I can basically do this using the Text File option, but it takes and extra step of setting the file to JavaScript using the menu at the bottom of the window, or saving the file using a .js suffix. It's a *really* small thing, but it would be a huge boon for my workflow.

**Comment by jmcphers** [comment]
Implemented in RStudio 1.3.

![image](https://user-images.githubusercontent.com/470418/75219786-9eb7c580-5752-11ea-85d1-d02d8e8081ea.png)
