### ISSUE TITLE
Tables in notebooks are often displayed with dark font color in dark scheme

### ISSUE THREAD

**Issue by heseber** [rstudio/rstudio#4329]
When using the dark Rstudio scheme and a dark editor color theme, the content of tables that is shown as the output of a code chunk is quite often displayed with a dark font color that is unreadable, especially for the Cobalt editor theme. Calling the chunk several times sometimes results in a white font color, it seems to be more or less random whether the table content is displayed with light or dark font colors. 

### System details

    RStudio Edition : Server
    RStudio Version : 1.1.463
    OS Version      :  Red Hat Enterprise Linux Server release 7.4 (Maipo)
    R Version       :  3.5.1

### Steps to reproduce the problem

Use dark scheme for RStudio. Use a dark editor scheme (e.g., Cobalt). Create a notebook with a chunk that displays a table. Run the chunk several times. 

### Problem in detail

The font color in the output below the chunk is not always in a light color, but often (most of the time) in dark font color which is not readable.

### Expected behaviour

The output of tables should always be displayed with light font color for dark RStudio scheme and dark editor scheme.

**Comment by kevinushey** [comment]
When you opened this issue, did you see this comment in the preamble?

```
RStudio v1.2 is currently available as a preview release, from https://www.rstudio.com/products/rstudio/download/preview/. If you are reporting a bug with RStudio v1.1, it would be greatly appreciated if you could check if the issue also reproduces in the preview release before reporting an issue.
```

**Comment by heseber** [comment]
Yes, I saw this comment, but this was not an option for me because our RStudio Pro server is centrally administered and it is not justifiable to request time from our IT colleagues for installing a preview release just to check if a minor nuissance still exists. The issue I reported has been existing probably since the dark scheme was introduced, and I did not find any previous ticket reporting this issue here, and I also did not see anything in the change log of the preview release that would tell me that this has been fixed. 
Why were you asking? Is this something that has been fixed in the pre-release and is just not mentioned in the change logs?

**Comment by ronblum** [comment]
@heseber I wasn't able to reproduce the issue on either RStudio Server 1.2.1320 as well as RStudio Desktop 1.1.363 and 1.2.1310 on MacOS 10.14. Hence, wondering if you still see the issue on one of the preview builds.

Can you provide the exact code you're using? It might not make a difference, but I'd like to make sure that my tests are comparable to yours when reproducing. Thanks!

**Comment by heseber** [comment]
@ronblum This seems to be an issue for knitr::kable output only.
![Screenshot](https://user-images.githubusercontent.com/22882929/54208847-f414ab80-44dc-11e9-9473-da4e5537d8ed.png)

Here is the Notebook:

[kable.Rmd](https://github.com/rstudio/rstudio/files/2957308/kable.Rmd.txt)

Here is the sessionInfo:
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.4 (Maipo)

Matrix products: default
BLAS: /gpfs01/sw/eb20171218-rh7/software/R/3.5.1-foss-2016b/lib64/R/lib/libRblas.so
LAPACK: /gpfs01/sw/eb20171218-rh7/software/R/3.5.1-foss-2016b/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.0

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  magrittr_1.5    htmltools_0.3.6 tools_3.5.1     base64enc_0.1-3 yaml_2.1.19     Rcpp_1.0.0     
 [8] rmarkdown_1.11  stringi_1.3.1   highr_0.7       knitr_1.21      jsonlite_1.6    digest_0.6.18   stringr_1.4.0  
[15] xfun_0.4        evaluate_0.10.1
```
RStudio Server Pro version is 1.1.463

**Comment by heseber** [comment]
I should add that the character foreground is sometimes white, i.e. readable, sometimes not. Running the table generating chunk several times should sometimes give readable output, sometimes not.

**Comment by heseber** [comment]
And another addendum - this seems to be specific for `data.table`, it does not occur for `data.frame`.

**Comment by kevinushey** [comment]
This is fixed in the preview release.

**Comment by ThierryO** [comment]
This issue is present again in 2022.12.0 Build 354 on Ubuntu 22.04

- modern theme
- quatro book to HTML
- `knitr::kable()` uses a transparent background and black font. Making the output very hard to read. Either use a white font or a white background.
