### ISSUE TITLE
Restart after segfault does not open project

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4331]
**Steps to reproduce:**
* Create a project for an R package
* Open the project in RStudio
* Write some C/C++ code that would segfault (e.g. access an array out of bounds)
* Build and install the package
* Run the code that segfaults
* On the error message, click “start new session”

**Expected behavior:** the new session should open with the project already open, just like it was before crashing.

**Actual behavior:** the new session does not open with the same project.

**Comment by jmcphers** [comment]
We do this on purpose to avoid crash loops; improvements currently tracked here: https://github.com/rstudio/rstudio/issues/3220 (comments/upvotes welcome!)
