### ISSUE TITLE
Parallel dataframe view on View pane

### ISSUE THREAD

**Issue by arlugones** [rstudio/rstudio#4332]
Hi!

I would like to congrat all of you guys who work at improving the RStudio IDE.
It ain't a question but a feature that could improve the RStudio View pane. Wouldn't be useful to 'inspect' two (or more) data structures (data frames, tibbles, lists, etc) on the View pane? Maybe fixing the structure view at the same time...

**Comment by david-cortes** [comment]
Each `View` call opens a different tab actually. If you want to view two structures at the same time, you can merge them into one before calling `View` (e.g. `cbind`, `append`, `dplyr::full_join`, etc.)

**Comment by arlugones** [comment]
Ain't talking about merging dataframes to view them. I'm actually talking about visually comparing two dataframes, a sort of quick look to data on two dataframes at the same time which is sometimes useful. There is a **compare** library to do that, but nothing visual.

**Comment by arlugones** [comment]
Ain't talking about merging dataframes to view them. I'm actually talking about visually comparing two dataframes, a sort of quick look to data on two dataframes at the same time which is sometimes useful. There is a **compare** library to do that, but nothing visual.

**Comment by jmcphers** [comment]
This is now being tracked in https://github.com/rstudio/rstudio/issues/2854 (which involves the work to create multiple source panes, after which you will be able to open two dataframes side by side)
