### ISSUE TITLE
Enhancement: Per-project margin column

### ISSUE THREAD

**Issue by vankesteren** [rstudio/rstudio#4335]
It would be great if the margin in the editor is set on a per-project basis. I work in projects where the codebase uses long names so I would use a margin of 120, and elsewhere I prefer to use a margin of 80.

### System details

    RStudio Edition :  Desktop
    RStudio Version :  Version 1.2.1114
    OS Version      :  Windows 10
    R Version       :  3.5.2

**Comment by jmcphers** [comment]
See related: https://github.com/rstudio/rstudio/issues/1711
