### ISSUE TITLE
Improve accessibility of Global Environment pane

### ISSUE THREAD

**Issue by skoestlmeier** [rstudio/rstudio#4339]
**Introduction:**

I have to deal with several hundreds of variables and data structures.

**Problem:**

The RStudio environment pane in its default configuration is grouped by the sections Data , Values and Functions in alphabetic ascending order. With hundreds of variables, this presentation gets very inconvenient. Furthermore, the default sections do not fit my need for easily finding cohesive results of my calculations, e.g. a full regression statement will be placed in the Data section and the matching regression coefficient (if separately stored) within the Values section.

Currently i work with conventions for properly naming my variables and store a detailed variable description in a separate text file.

**Question:**

Is there a way to define own sections within the Global Environment pane and specifically assign variables or data structures into these custom sections?

**Comment by jmcphers** [comment]
No, there's no way to do this now. How exactly do you imagine the assignment working? Do you want to manually put objects into sections after they are created? Or do you want objects to self-sort into sections based on rules/metadata?

**Comment by skoestlmeier** [comment]
In the current version of RStudio, there are the two default sections "Data" and "Functions" in the environment pane and new objects are automatically assigned to both of them.

I would suggest that users can create own subsections based on setting a certain delimiter for variables. Per default, new objects should still automatically be assigned into the two main sections "Data" and "Functions" with the current rules, but further be placed into subsections by manually rules (described below).

E.g. i have to deal with an international dataset. New variables are assigned to the section "Data". I would like to create subsections for each country, so

    Data
       |----> CountryA
       |--------> Variable B
       |----> CountryC
       |--------> Variable B

This would be a far more clearly view of my dataset. Currently, i have to assign properly prefixes, so my variables above are named `CountryA_B` and `CountryC_B`.

The user should be able to define a certain delimiter for the assignment of objects to subsections to avoid name conflicts. If e.g. the user defines the delimiter `_` in the settings for this enhancement, then the creation of a variable `XY_A` would create the subsection `XY` (if not yet exists) and display simply the name `A` for this variable. The technical name of this object still should remain `XY_A`.

If you see a valuable contribution for this enhancement, i would start and provide a pull request. Anyway, i would be pleased for any comments or remarks on the above procedure and how it can be implemented in the best way.
