### ISSUE TITLE
Add Services sub menu to Application menu on Mac OSX

### ISSUE THREAD

**Issue by the-x-at** [rstudio/rstudio#4340]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Mac OSX 10.11.6
    R Version       : 3.5.1

### Introduction

I am frequently using global hotkeys to perform actions independently of the application being currently in focus (e.g. open a terminal, lock the screen). On Mac OSX, this is usually achieved by registering services, which are attached to key bindings. These services are then automatically integrated into any application's "Application" menu as a "[Services](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/services)" sub menu.

![finder-services](https://user-images.githubusercontent.com/22655921/53166442-31b4a180-35cd-11e9-8332-344581850abf.png)

### Steps to reproduce the problem
This Services sub menu however is currently not available in RStudio's Application menu:

![rstudio-wo-services](https://user-images.githubusercontent.com/22655921/53166479-42651780-35cd-11e9-84eb-23d7e26d14c1.png)

### Describe the behavior you expected

As a start, it would be great to enable the Services sub menu in OSX, even if RStudio does not provide any additional functionality through it. General Services would then be automatically added and could be accessed from within RStudio.

### Acknowledgements
Thanks for taking this into consideration.

**Comment by jmcphers** [comment]
This is a good idea but hasn't received any attention in over a year, so it's not likely we'll get to it soon.
