### ISSUE TITLE
Cannot open files form Files Tab after trying to open a .txt file larger than 5mb.

### ISSUE THREAD

**Issue by robiRagan** [rstudio/rstudio#4341]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.463
    OS Version      : macOS Mojave 10.14.3
    R Version       : R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"

### Steps to reproduce the problem

1. Try to open a .txt file form the Files Tab that is larger than 5mb. 
2. After getting the error dialog box click OK. 
3. Then try to open another file form the Files Tab. 

### Describe the problem in detail

If you try to open a .txt file larger than 5mb from the Files Tab within Rstudio you get an error:

`The file 'fileName.txt' is too large to open in the source editor (the file is 20.4 MB and the maximum file size is 5 MB)`

Then after hitting "OK" any attempt to open other files form the Files Tab will not work and Rstudio has to be restarted to return the normal behavior. 

### Describe the behavior you expected

I expected to be able to open other files after clearing the error dialog box.

**Comment by kevinushey** [comment]
I can reproduce this in the v1.2 preview release as well.

**Comment by dfalty** [comment]
Verified fixed 1.2.1318.
