### ISSUE TITLE
Viewer pane doesn't respond to some shortcuts

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#4342]
1. Open the viewer with (e.g.) `View(mtcars)`
2. Attempt to close it by pressing `Cmd + W` — nothing happens

Many other keyboard shortcuts also fail to work (e.g. `Ctrl + .`, `Cmd + N`, `Cmd + Shift + F`).

**Comment by kevinushey** [comment]
IIUC this is because Viewer content lives in an iframe and once that iframe has focus all browser events are effectively captured and sheltered from the main IDE frame (except for keybindings that we explicitly handle / forward).

**Comment by hadley** [comment]
If that's the case, just handling `Cmd + W` would be an improvement to my quality of life.

**Comment by ronblum** [comment]
#5754 reported by @AdamSadowski mentions `Ctrl-1` and `Ctrl-2`.
