### ISSUE TITLE
Publishing preferences pane overflows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4346]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1280
    OS Version      : macOS 10.14.3
    R Version       : 3.5.2

---

![screen shot 2019-02-21 at 12 31 49 pm](https://user-images.githubusercontent.com/1976582/53199761-c8389100-35d4-11e9-986a-718e45df07e6.png)

**Comment by jmcphers** [comment]
The SSL options are new, and didn't account for the "missing packages" UI which rarely shows. I think we should fix this by reducing the height of the Publishing Accounts list (it's very rare that more than two accounts will exist there)

**Comment by dfalty** [comment]
Verified fixed 1.2.1312.
