### ISSUE TITLE
RStudio View mode does not display length of logical vectors

### ISSUE THREAD

**Issue by shahronak47** [rstudio/rstudio#4347]
Taken from [this StackOverflow post ](https://stackoverflow.com/questions/54785814/why-do-logical-vectors-in-rstudio-view-mode-not-show-length) why does R Studio View mode does not display length of logical vectors?

    View(list(1:10, rep(TRUE, 10), rep(1.0, 10), rep('x', 10))) 

![image](https://user-images.githubusercontent.com/10164875/53233298-0c588e00-36c8-11e9-9f6f-cb2c0555214e.png)

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.383
    OS Version      : MacOS Mojave 10.14.3
    R Version       : 3.4.0

**Comment by kevinushey** [comment]
Looks like it may just be a bug.

**Comment by dfalty** [comment]
Verified fixed 1.2.1312.
