### ISSUE TITLE
ensure we will be compatible w/Rtools in R 3.6.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4350]
A reminder to make sure that we update the Rtools information we have here as appropriate for R 3.6.0. (R major releases typically happen around April, and since we plan to release before then we should make sure to be compatible.)

See e.g. https://github.com/rstudio/rstudio/blob/6e377089aec92585b312ddfcc70a5755251e6687/src/cpp/core/r_util/RToolsInfo.cpp#L153

I don't think there are any toolchain updates planned for R 3.6.0 so it may well be as simple as adding a check for R 3.6 there.

**Comment by jmcphers** [comment]
@kevinushey discovered that the next release of RTools is 4.0, so we'll continue to presume that RTools 3.5 is what we should use for R 3.6.
