### ISSUE TITLE
No preview for equations written on multiple lines using single '$'

### ISSUE THREAD

**Issue by psalveson** [rstudio/rstudio#4352]
### System details

    RStudio Edition : Server 
    RStudio Version : 1.2.1299
    OS Version      :  Ubuntu 18.04.2
    R Version       : 3.5.2

### Steps to reproduce the problem
Open a new R Markdown file. Contents of file:

```
---
title: "Bug"
author: "PS"
output: pdf_document
---

$\begin{aligned} a_1 &= \beta_0 \\ b_1 &= \beta_1 \\ c_1 &= \beta_2 \\ d_1 &= \beta_3 \end{aligned}$
```
A preview of the equation pops up if you hover your cursor over the equation syntax (as expected). However, if the equation syntax is broken up onto multiple lines:

```
---
title: "Bug"
author: "PS"
output: pdf_document
---

$\begin{aligned} 
a_1 &= \beta_0 \\ 
b_1 &= \beta_1 \\ 
c_1 &= \beta_2 \\ 
d_1 &= \beta_3 
\end{aligned}$
```
There is no preview for the equation (although knitting a pdf produces the expected output). Note that a preview is produced when the equation syntax is surrounded by '$$' instead of '$', but this produces centered equations in the pdf output. 

### Describe the problem in detail
Rstudio does not produce previews for LaTeX equations where the syntax is on multiple lines and the syntax is surrounded by '$'. I have noticed this issue on multiple platforms (Ubuntu server/desktop and windows desktop).

Also, the syntax highlighting for the equation syntax on multiple lines using '$' is not consistent with equations written on a single line using '$' or equations written on multiple lines using '$$'

### Describe the behavior you expected

A preview of the equation should be produced regardless of whether the syntax is on one line, or multiple lines.

**Comment by kevinushey** [comment]
Is there any reason to prefer `$ ... \\ .. $` over multi-line equations using `$$`? The bug is real but does not appear particularly high priority unless there's some real semantic difference between the two.

**Comment by psalveson** [comment]
> Is there any reason to prefer `$ ... \\ ... $` over multi-line equations using `$$`? 

 `$ ... \\ ... $` is used for inline equations and equations aligned with the left margin. `$$ ... \\ ... $$` produces equations that are centered horizontally on the page (with added whitespace above and below? I'm not 100% sure)
