### ISSUE TITLE
SQL completion does not parse table with shema in JOIN

### ISSUE THREAD

**Issue by saurfang** [rstudio/rstudio#4354]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.2.1301
    OS Version      :  Mac 10.14.3
    R Version       :  3.5.2

### Steps to reproduce the problem

Apologize for the wonky setup as I'm not familiar with RSQLite and the problem I'm having is with presto, which cannot be locally setup easily.

This sets up two databses in SQLite.

```r
library(RSQLite)
con <- dbConnect(RSQLite::SQLite(), "database1.db")
dbWriteTable(con, "mtcars", mtcars)
dbDisconnect(con)


con <- dbConnect(RSQLite::SQLite(), "database2.db")
dbWriteTable(con, "mtcars", mtcars)
dbDisconnect(con)
```

Open SQL file

```sql
-- !preview conn=eval(parse(text = 'local({con <- DBI::dbConnect(RSQLite::SQLite(), "database1.db");DBI::dbSendStatement(con, "attach \'database2.db\' as db2;"); con})'))

SELECT
-- invoke compeltion here
from db2.mtcars
```
![image](https://user-images.githubusercontent.com/4317392/53308165-c7f9f900-3853-11e9-8956-c965d4b9ecb4.png)

vs

```sql
-- !preview conn=eval(parse(text = 'local({con <- DBI::dbConnect(RSQLite::SQLite(), "database1.db");DBI::dbSendStatement(con, "attach \'database2.db\' as db2;"); con})'))

SELECT
-- invoke compeltion here
from (select 1)
left join db2.mtcars
```
![image](https://user-images.githubusercontent.com/4317392/53308150-b153a200-3853-11e9-826b-85fe1f355060.png)

### Describe the problem in detail

SQL completion does not understand join cross databases and assume the next token is table instead of possible `schema.table`.
https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionManager.java#L240

### Describe the behavior you expected

Completion should tokenize the table being joined correctly. In theory, `join` keyword semantics is very much close to `from` keyword sematics, where we should parse `[schema.]table [alias]` correctly.

p.s. I have a few other related questions. Let me know if any of these are worth opening separate issues:

1. Currently, the compeltion suggestion put table list on the top. However, I rarely find this useful. In production setting, databse can easily have hundreds of tables. Having this in `SELECT column1, <compeltion cursor> FROM <table>` clutters the compeltion for little benefits. I can't imagine a scenario one could use list of all tables other than `FROM` and `JOIN`.
1. The metadata retrival (table schema) can often be slow (100ms+) There was this `withCache` function in the SQL compeltion PR https://github.com/rstudio/rstudio/pull/3429/files#diff-ea4f7eb5e03c62527c281b922d8ea4e4R2304 but I don't believe the schema is cached during completion.
1. Will there be a hook package can implement to provide additional information on the completion? such as column type, and comments.

**Comment by kevinushey** [comment]
> Currently, the compeltion suggestion put table list on the top. However, I rarely find this useful. In production setting, databse can easily have hundreds of tables. Having this in `SELECT column1, <compeltion cursor> FROM <table>` clutters the compeltion for little benefits. I can't imagine a scenario one could use list of all tables other than `FROM` and `JOIN`.

I think this is worth changing. Would you mind filing a separate issue?

> The metadata retrival (table schema) can often be slow (100ms+) There was this `withCache` function in the SQL compeltion PR https://github.com/rstudio/rstudio/pull/3429/files#diff-ea4f7eb5e03c62527c281b922d8ea4e4R2304 but I don't believe the schema is cached during completion.

Which call in particular is slow? These are the places where we make calls through DBI:

```
session/modules/sql/SessionSql.R
226:      if (!DBI::dbIsValid(.rs.sql.connectionBlacklist[[key]]))
242:   time <- system.time(tables <- .rs.tryCatch(DBI::dbListTables(conn)))
331:      return(DBI::dbListFields(conn, DBI::Id(schema = schema, table = table)))
335:   DBI::dbListFields(conn, table)
341:   # of DBI::dbListObjects()
348:   objects <- DBI::dbListObjects(conn)
360:   objects <- DBI::dbListObjects(conn, DBI::Id(schema = schema))
```

> Will there be a hook package can implement to provide additional information on the completion? such as column type, and comments.

We've discussed this before and there's been some package work in this space (e.g. https://github.com/jimhester/completeme) but we haven't taken the time to evaluate IDE integration or what that might entail.

**Comment by saurfang** [comment]
Both can be slow for a database in a production setting, considering people accessing behind a VPN and database may have hundreds or thousands of tables.

```r
> system.time({dbListObjects(conn)})
   user  system elapsed 
  0.406   0.001   0.408 
> system.time({dbListFields(conn, SQL("usertables.forestfang_mtcars"))})
   user  system elapsed 
  0.009   0.001   0.154 
```

The actual backend here is presto. I didn't include a reprex since this is difficult to replicate in a local machine. If you want to do some testing, I imagine bigquery would be a better proximation than sqlite since it is also remote.
These are not terribly slow but adds up quickly when your query accesses multiple tables and UI just doesn't feel snappy.

I think it makes sense to cache both table list and table's schema in each R session for autocompletion purpose. It would be nice to have an API function that let user clear the cache. I know this is kind of separate from the connection viewer but I think a reasonable UX would be clicking the "refresh data" button in connection pane would either clear the completion cache and refetch the completion data.

**Comment by kevinushey** [comment]
Thanks for taking the time to illuminate a bit more! I agree a reprex isn't necessary here since the problem is at least easy to understand.

I'll have to think about caching here. My main worry is that if the user is attempting to mutate the database from within RStudio, or if the database were mutated while working within RStudio, they may be surprised that these new tables / fields are not visible in the autocompletion list.

On the balance I think caching is the right solution, but I wonder if there's some way we could (cheaply) ask the database if things have changed and we should invalidate our local cache.

**Comment by kevinushey** [comment]
I'm going to move this to v1.2 so at least we think about handling of caching (not sure if anything will make it in soon since we're closing the v1.2 window shortly but I think this meets the bar)

**Comment by saurfang** [comment]
I agree with your concern and appreciate your consideration re 1.2 v 1.3. 

I wonder if you can serve the suggestion with cache first, fire the request in the background, and update the UI once you get the up-to-date info and if the info turns out to have changed. In reality, I think the database info is slower changing than the rate people write queries. So I imagine the occasion flickering would be okay. 

Or cache for the duraction of a "focus" session. That is, if I start working in `.sql` file, the metadata is cached as long as the editor doesn't lose focus. Same goes for a chunk. While this is not perfect as user will likely poke around to look things up, I imagine it is still an improvement than the current state. 

I realize either option is not trivial to implement and get it right.

**Comment by kevinushey** [comment]
For the original issue re: completion of schemas, perhaps I'm misunderstanding something but this connection object doesn't report any schemas:

```r
library(RSQLite)
library(DBI)
con <- dbConnect(RSQLite::SQLite(), "database1.db")
dbWriteTable(con, "mtcars", mtcars)
dbDisconnect(con)


con <- dbConnect(RSQLite::SQLite(), "database2.db")
dbWriteTable(con, "mtcars", mtcars)
dbDisconnect(con)


conn=eval(parse(text = 'local({con <- DBI::dbConnect(RSQLite::SQLite(), "database1.db");DBI::dbSendStatement(con, "attach \'database2.db\' as db2;"); con})'))
dbListObjects(conn)
```

gives

```
> dbListObjects(conn)
                table is_prefix
1 <Id> table = mtcars     FALSE
```

Is there some DBI / RSQLite API that will give the name of the databases here?

**Comment by kevinushey** [comment]
Looks like this would work:

```r
DBI::dbGetQuery(conn, "PRAGMA database_list;")
```

**Comment by faccinig** [comment]
This issue is the principal reason i don't use Rstudio to write queries.
If matters, i vote to be resolved.

**Comment by kevinushey** [comment]
@faccinig, this particular issue should have been resolved via https://github.com/rstudio/rstudio/commit/78b5b43892661a61b12c235da948f75c5e9ccb67; if you're still having trouble, please file a new issue. Thanks!
