### ISSUE TITLE
Unable to accept SQL completion

### ISSUE THREAD

**Issue by saurfang** [rstudio/rstudio#4355]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1301
    OS Version      :  Mac 10.14.3
    R Version       :  3.5.2

### Steps to reproduce the problem

![2019-02-24 17-00-39 2019-02-24 17_00_58](https://user-images.githubusercontent.com/4317392/53308403-ca5d5280-3855-11e9-9f04-69f0a83a45b5.gif)

### Describe the problem in detail

Unable to accept completion by either press `<tab>` or `<enter>`. Completion acceptance works just fine in R code.

### Describe the behavior you expected

Selected completion should be inserted.

**Comment by jmcphers** [comment]
I can reproduce this in server mode, too; clicking on the completion doesn't seem to work, either.

**Comment by kevinushey** [comment]
Fixed in latest dailies via https://github.com/rstudio/rstudio/commit/0befc1f6ac03b3ce66f1e3d250ddaa48041b75f1. (Note that this issue only effects SQL chunks without a declared connection)
