### ISSUE TITLE
Console pane not mouse-scrollable when input line is scrollable

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4356]
**Steps to reproduce:**
* Write something in the console input prompt that would be long-enough to not fit in the screen and need scrolling.
* Focus on the console, at any part of the multi-line statement.
* Move the mouse wheel.

**Expected result:** should scroll through the console.

**Actual result:** does not scroll.

**Setup**: RStudio 1.2.1268 and 1.2.1293 (desktop), R 3.5.1, running on windows 10.

**Comment by pascaloettli** [comment]
Please use the template.

> 
> RStudio v1.2 is currently available as a preview release, from https://www.rstudio.com/products/rstudio/download/preview/. If you are reporting a bug with RStudio v1.1, it would be greatly appreciated if you could check if the issue also reproduces in the preview release before reporting an issue.
> 
> This issue tracker is for bugs and feature requests in the RStudio IDE. If you're having trouble with R itself or an R package, see https://www.r-project.org/help.html, and if you want to ask a question rather than report a bug, go to https://community.rstudio.com/. Finally, if you use RStudio Server Pro, get in touch with our Pro support team at support@rstudio.com.
> 
> See our guide to writing good bug reports for more details: https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports
> -->
> 
> ### System details
> 
>     RStudio Edition : 
>     RStudio Version : 
>     OS Version      : 
>     R Version       : 
>

**Comment by david-cortes** [comment]
Added missing info as requested.

**Comment by kevinushey** [comment]
In general, if mouse focus lies over the line(s) used for console input, then attempts to scroll with the scroll wheel will fail.
