### ISSUE TITLE
CRAN release of rstudioapi

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4358]
RStudio 1.2 adds some new functionality accessible via rstudioapi; we should release a new version of rstudioapi to CRAN in concert with the RStudio 1.2 release, so that it isn't necessary to get the development version of rstudioapi to work with the stable version of RStudio. 

See also: 

https://github.com/rstudio/rstudio/blob/a698544a9bad2aafd14613b35c103ca3ee50e771/src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java#L222

https://github.com/rstudio/rstudio/blob/a698544a9bad2aafd14613b35c103ca3ee50e771/src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java#L368

**Comment by kevinushey** [comment]
rstudioapi is on CRAN, but we need to bump the requested version in the dependency manager still.

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio/pull/4546.

**Comment by ronblum** [comment]
Verified in RStudio Server 1.2.1528 on Red Hat 7.6 using sample Shiny addin `tidyshiny`.
