### ISSUE TITLE
Prompt for shiny installation in connections wizard

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#4359]
Install `sparklyr`, uninstall `shiny`, launch Spark connection from connection pane.

Actual: Error triggers in console.
Expected: RStudio to prompt for `shiny` to be installed.

`sparklyr` makes use of [rstudio-connections.html#shiny-application](https://rstudio.github.io/rstudio-extensions/rstudio-connections.html#shiny-application) which the dependency could be enforced in `sparklyr`, but there are other packages interesting in building connection extensions; therefore, rather than enforcing each package to depend on `shiny`, we should prompt when shiny connections are used ion the connections Wizard.

**Comment by cderv** [comment]
FWIW, as I passed through there because searching for something, it seems that this is fixed but not closed.
