### ISSUE TITLE
open a blank R document by default in new RStudio sessions?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4362]
From https://community.rstudio.com/t/my-file-wont-save/24660. Some new users find it confusing that only an R console is visible on first launch, expecting instead that this is a file that can be saved etc.

**Comment by jmcphers** [comment]
The converse might be true, too. It's just as easy to mistake the script for a console. Imagine an alternate universe where we start with a script and users file issues saying "I'm typing R code into RStudio, but it doesn't run when I press Enter." :-) 

Perhaps we could start with an R script that has embedded execution instructions (just like we do for R Markdown documents).

**Comment by hrbrmstr** [comment]
Tossing in a vote to make this a user-selectable option in RStudio prefs.
