### ISSUE TITLE
[FR] Be able to control how often the git scan takes place

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#4368]
Hi,

I'm currently maintaining a large project with multiple git submodules inside. However, when using RStudio on this project, the git and file control panels respond very slow. 

I suspect it's because RStudio is somehow running git re-scan whenever a file gets touched. After I closed the version control function, RStudio works in "normal" speed now on this project.

It's a pain to tolerate the slow respond. So I'm asking if __RStudio can add an option regarding to the git scan frequencies__ . To my case, I will be happy even if I have to trigger the git scan manually (that's what the native git GUI does). Otherwise, I have to turn off RStudio version control and run the git GUI there... I prefer stays everything inside of RStudio...

Thanks!

**Comment by kevinushey** [comment]
Are you using a preview release of RStudio? If so, you can execute:

```
Sys.setenv(RSTUDIO_GIT_LOG = "1")
```

to have RStudio dump all the git-related actions it's taking into the console. Do you see the lag occurring with any action in particular?

Note that RStudio doesn't poll the filesystem for changes; it registers file monitors to request a refresh when files within the project change, and also when the RStudio window gains focus.

**Comment by shrektan** [comment]
@kevinushey Thanks for the help. 

Yes, I can see the the action log of git, when I modify the file, click the folder, click the git history... And whenever RStudio GUI gets the focus...

After a few trials, `C:/app/Git/bin/git.exe status -z --porcelain -- C:/my-work-directory`  seems quite slow. It gets called a lot and every time it takes about 3 seconds, even if I hasn't touched any file. 

Maybe it's due to the multiple submodules because `git status` runs quite slow on the terminal as well...

**Comment by shrektan** [comment]
Actually, it runs very fast on my Mac. Highly probably due to the anti-virus software on the computer in the office (the Windows 10 OS may also be the cause). Anyway, since I cannot turn off the anti-virus, being able to close the Git auto-scan will help a lot on my case... Thanks.

**Comment by kevinushey** [comment]
https://community.rstudio.com/t/rstudio-suddenly-slow-processing/4959/9 might be relevant: some users found that adding certain processes to the set of Windows Defender Exclusions helps.

**Comment by shrektan** [comment]
Thanks for the tips but it doesn't help. I bet my antivirus (TrendMicro) is still scanning those processes. Unluckily, I don't have the authorization to add processes into the TrendMicro's white lists so can't test that...

**Comment by kevinushey** [comment]
I realize this is a heavy hammer to use, but does disabling the RStudio git integration altogether make a difference?

<img width="604" alt="screen shot 2019-03-01 at 10 24 36 am" src="https://user-images.githubusercontent.com/1976582/53657882-3b14be00-3c0c-11e9-8171-723bb4c8c805.png">

**Comment by kevinushey** [comment]
Or, if the problem only occurs with one particular project, you can disable it for that project only:

<img width="559" alt="screen shot 2019-03-01 at 10 25 21 am" src="https://user-images.githubusercontent.com/1976582/53657929-5aabe680-3c0c-11e9-906d-f35066814774.png">

**Comment by shrektan** [comment]
Thanks for the help.  

I’ve tried that before and I can confirm that RStudio speed goes back to normal. The thing is it will better if there’s could be an option... so that I can enjoy the nice Git GUI RStudio provides...

It’s not only for this project... Even on small projects, it’s not very smooth because of (probably) Git being monitored by antivirus and frequently called by RStudio IDE...

That’s why I submit this FR... to see if there’s a chance to have the option that disable Git auto-scan globally or on single project...

**Comment by kevinushey** [comment]
Gotcha. Unfortunately we're trying to wrap up the v1.2 release but we'll try to make sure this happens for v1.3 (we're planning that v1.3 will be a quicker release than v1.2 was)

**Comment by shrektan** [comment]
Thanks! Looking forward to that.

**Comment by kevinushey** [comment]
A class of fixes that could fit for v1.3:

1. Allow users to disable automatic "refresh" for the Git pane (as we do for the Environment pane).
2. Perform background "refresh" in a separate thread. AFAICS we don't require the operation to actually be synchronous.
3. Figure out if there's a way we could dodge some of the slowness we're seeing when invoking `git`. (In theory sub-modules should already be ignored by default but maybe we need to enforce that?)

**Comment by shrektan** [comment]
@kevinushey I have tried the daily builds version for a few days. I can confirm that this version experiences few hangs on my computer in the office now, as long as *Git Auto-Scan* is disabled. 

Thanks a lot!

**Comment by kevinushey** [comment]
Very glad to hear it :-)

**Comment by rich-rstudio** [comment]
verified on win 10 1.3.938 preview
