### ISSUE TITLE
Feature request - Display "label"-attribute as tooltip

### ISSUE THREAD

**Issue by AndriSignorell** [rstudio/rstudio#4370]
Wouldn’t it be nice to have labels (defined as “label” attribute) of variables of a data.frame available as quicktip, while selecting them?
 
```r
library(DescTools)
Label(d.pizza$temperature) <- "The temperature of the pizza at delivery time"
d.pizza$|
```

![tooltip](https://user-images.githubusercontent.com/6578660/53510269-d5b2b700-3abd-11e9-8b7c-ce7d5623fae3.jpg)

**Comment by jmcphers** [comment]
Tagging with `autocompletion` as this is where we'd need to make that change.

**Comment by AndriSignorell** [comment]
any news on that issue?

**Comment by AndriSignorell** [comment]
any news on that issue?

**Comment by romainfrancois** [comment]
Perhaps it can show the label (if present), some type information, and a glimpse of the first few values ?
