### ISSUE TITLE
Cannot preview "Pebble-Safe" theme

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4372]
### System details

    RStudio Edition : Both
    RStudio Version : 1.2.1303
    OS Version      : MacOS 10.14

### Steps to reproduce the problem

Install the [Pebble-Safe](https://github.com/DesiQuintans/Pebble-safe) dark and light themes:

    rstudioapi::addTheme("https://raw.githubusercontent.com/DesiQuintans/Pebble-safe/master/Pebble-Safe%20Dark.rstheme")
    rstudioapi::addTheme("https://raw.githubusercontent.com/DesiQuintans/Pebble-safe/master/Pebble-Safe%20Light.rstheme")

Next, go to the Appearances panel and attempt to preview the Pebble-Safe Dark theme.

### Describe the problem in detail

The default theme is previewed instead.

![image](https://user-images.githubusercontent.com/470418/53528987-22879500-3aa0-11e9-963c-b0025881b46c.png)

This error also appears in the logs:

    27 Feb 2019 22:53:02 [rsession-jmcphers] WARNING "dark" parameter for request is missing or not a true or false value: ; LOGGED FROM: rstudio::core::FilePath rstudio::session::modules::themes::(anonymous namespace)::getDefaultTheme(const http::Request &) /Users/jmcphers/git/rstudio/src/cpp/session/modules/SessionThemes.cpp:355

The theme has the requisite `rs-theme-is-dark` metadata:

https://github.com/DesiQuintans/Pebble-safe/blob/824377bd952f32bd89176cc44bae24f9b4f97d33/Pebble-Safe%20Dark.rstheme#L1-L2

### Describe the behavior you expected

Preview of Pebble-safe.

**Comment by jmcphers** [comment]
We should see what's going on here -- if it turns out to be that e.g. themes can't have hyphens we might need to fix for 1.2.

**Comment by jmcphers** [comment]
`rstudioapi::addTheme` saves the file as "Pebble-Safe%20Dark.rstheme". Manually renaming it to the URL decoded version fixes things, so at a minimum we should fix rstudioapi.

**Comment by jmcphers** [comment]
Using a name without "%20" makes preview possible -- the second time.

**Comment by dfalty** [comment]
Verified fixed 1.2.1312.
