### ISSUE TITLE
Bug Report: Life-Cycle badge does not show up in auto-complete tool-tip

### ISSUE THREAD

**Issue by dylanjm** [rstudio/rstudio#4373]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1303
    OS Version      : macOS 10.12.6
    R Version       : 3.5.2

### Steps to reproduce the problem

Load a library that now have life-cycle badges in documentation and begin typing a function until the auto-complete tool-tip shows up.

### Describe the problem in detail

The life cycle badge appears as a broken link in the tool tip. 

![image](https://user-images.githubusercontent.com/15963026/53529972-94191080-3aab-11e9-88c4-ce113925970a.png)

### Describe the behavior you expected

Show the life-cycle badge.

**Comment by jmcphers** [comment]
This is a nice idea but these are apparently quite rare (we've not heard any other reports in over a year). It is unfortunately not likely we'll get to this soon.
