### ISSUE TITLE
SQL completion does not parse table without alias

### ISSUE THREAD

**Issue by saurfang** [rstudio/rstudio#4376]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1309
    OS Version      : Mac 10.14.3
    R Version       : 3.5.2

### Steps to reproduce the problem

Cannot trigger completion:

![image](https://user-images.githubusercontent.com/4317392/53537919-7a35f880-3ac0-11e9-960d-2329ae3728ec.png)

Triggers completion:

![image](https://user-images.githubusercontent.com/4317392/53537940-95086d00-3ac0-11e9-9a57-cffbb930353c.png)

![image](https://user-images.githubusercontent.com/4317392/53538004-d13bcd80-3ac0-11e9-89a8-797dc3ab8c30.png)

### Describe the problem in detail

Select a table in from clause without aliasing and try triggering auto completion

### Describe the behavior you expected

SQL completion should work whether the table is aliased or not in the from clause

**Comment by kevinushey** [comment]
I realize you had instructions for creating the associated database in a separate issue but please keep the issues self-contained so we don't have to hunt around for instructions to reproduce and test things.

**Comment by saurfang** [comment]
my bad, sorry for not attaching the code to create the database.

**Comment by kevinushey** [comment]
No worries. I should say, we appreciate your taking the time to test and report these issues in the first place as well :-)
