### ISSUE TITLE
Improve SQL completion order and entries

### ISSUE THREAD

**Issue by saurfang** [rstudio/rstudio#4377]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1301
    OS Version      :  Mac 10.14.3
    R Version       : 3.5.2

### Steps to reproduce the problem

```{r}
library(DBI)
library(tidyverse)
conn <- dbConnect(RSQLite::SQLite(), "database1.db")
seq(100) %>% walk(~ dbWriteTable(conn, basename(tempfile("table_")), mtcars))
dbWriteTable(conn, "mtcars", mtcars)
dbWriteTable(conn, "iris", iris)
```

![image](https://user-images.githubusercontent.com/4317392/53538525-e74a8d80-3ac2-11e9-8514-e753d29047d0.png)

### Describe the problem in detail

Currently for non-aliased completion, i.e. not trigger from `<alias>.`, we populate the completion with:

1. List of all tables
1. List of all fields from tables referenced in the query
1. Local keywords

This is rarely useful aside from the place where "a new table" is expected, namely, `FROM`, `JOIN`, `(INSERT) INTO`, `(DROP) TABLE` and etc. In 90% of query writing use case, one would prefer:

1. List of all fields from tables referenced in the query
1. tables aliases in the query
1. other unaliased tables in the query
1. local keywords (such as aliased selected columns [would be great if we can parse them eventually])

This is true in `SELECT`, `WHERE`, `JOIN ... ON/USING`, and `GROUP/ORDER BY`. 

The entire list of all tables can be distracting especially when production databases often have hundreds if not thousands of table.

### Describe the behavior you expected

The completion list order should be more intuitive. For fields of tables, it would brilliant if we can provide contextual information on which table they belong to and data types (I'm not sure DBI provides an interface for this.)

**Comment by kevinushey** [comment]
Should be better handled in next daily builds -- let me know how things look!
