### ISSUE TITLE
Connection filter should search entire list instead of visible ones

### ISSUE THREAD

**Issue by saurfang** [rstudio/rstudio#4378]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1309
    OS Version      : Mac 10.14.3
    R Version       : 3.5.2

### Steps to reproduce the problem

R Code to setup SQLite db
```r
library(DBI)
library(tidyverse)
conn <- dbConnect(RSQLite::SQLite(), "database1.db")
seq(1000) %>% walk(~ dbWriteTable(conn, basename(tempfile("table_")), mtcars))
dbWriteTable(conn, "z_mtcars", mtcars)

observer <- getOption("connectionObserver")
observer$connectionOpened(
  # connection type
  type = "rsqlite",
  # name displayed in connection pane
  displayName = "RSQLite",
  # host key
  host = "localhost",
  # connection code
  connectCode = "dbConnect(RSQLite::SQLite(), 'database1.db')",
  # disconnection code
  disconnect = function() {
    dbDisconnect(conn)
    observer$connectionClosed(type = "rsqlite", host = "localhost")
  },
  listObjectTypes = function() {
    return(list(table = list(contains = "data")))
  },
  # table enumeration code
  listObjects = function(type = "table") {
    tables <- dbListTables(conn)
    
    data.frame(
      name = tables,
      type = rep_len("table", length(tables)),
      stringsAsFactors = FALSE
    )
  },
  # column enumeration code
  listColumns = function(table) {
  },
  # table preview code
  previewObject = function(rowLimit, table) {
  },
  # raw connection object
  connectionObject = conn
)
```

In connection pane:

![2019-02-27 20-07-11 2019-02-27 20_07_45](https://user-images.githubusercontent.com/4317392/53540728-8d01fa80-3acb-11e9-8e29-a317f9ffacbf.gif)

### Describe the problem in detail

While `listObjects` returns the full list of tables, RStudio only renders the first few hundreds of tables, which is an understandable performance optimization. However, when using the filter to find a table, RStudio appears to search the visible list of tables instead of the full list of tables. This creates a weird UX that user need to click on `load more` a few times before finding the table.

This also includes a separate bug that clicking `load more` should either clear the filter textbox or re-apply filter on the newly loaded results.

### Describe the behavior you expected

Filter box should be intuitive and returns a list of matching tables up to the rendering limit instead of applying the rendering limit first then search.

**Comment by jmcphers** [comment]
We did this for performance reasons; enumerating every object can take a very long time on some backends. You're right, however, that the experience could be improved! We'll think about ways to address this.
