### ISSUE TITLE
Timestamp of the directory of the edited file is not updated

### ISSUE THREAD

**Issue by basilrabi** [rstudio/rstudio#4384]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1312
    OS Version      : Fedora 29
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Set-up a working directory like this:
```
.
├── test.Rproj
├── testdir
│   └── child1.Rnw
└── test.Rnw
```
1.  Check the modify time stamp of `testdir` via `stat testdir`
1. Edit the file `testdir/child1.Rnw` and save
1. Check the modify time stamp of `testdir/child1.Rnw` and you will see it is updated
1. Check the modify time stamp of `testdir` again (The time stamp did not change even after editing `testdir/child1.Rnw`)

### Describe the problem in detail

After editing and saving `testdir/child1.Rnw`, the time stamp of its directory: `testdir`, is not updated. This might be related to #2113.

### Describe the behavior you expected

After editing and saving `testdir/child1.Rnw`, the time stamp of its directory: `testdir`, should change.

**Comment by jmcphers** [comment]
Directories are only "modified" when entries are added and removed (i.e. files are added or deleted from the directory). Their modify time stamp doesn't represent the latest time any file in the directory had its content changed.
