### ISSUE TITLE
Unable to install rgdal package in Rstudio

### ISSUE THREAD

**Issue by AniketKul** [rstudio/rstudio#4395]
I am trying to install `rgdal` package in Rstudio.

**OS:** Ubuntu 16.04

**Command:** `R --vanilla -e "install.packages('rgdal', repos = 'https://cran.rstudio.com')"`

**Expected Output:** 

`rgdal` should be installed. 

**Current Output:**

![rgdal_issue](https://user-images.githubusercontent.com/21697139/53768653-4d059380-3e8e-11e9-807a-3b9862ec57fc.png)

Any help is appreciated. Thanks!

**Comment by kevinushey** [comment]
This appears to be an issue in (Anaconda) R as opposed to something in RStudio. The configure error suggests that the version of `libgdal` installed in your environment is not the version expected by the `rgdal` package.

I would suggest asking on the [community forums](https://community.rstudio.com).
