### ISSUE TITLE
Grey window, no panes on MacOS

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#4399]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1318
    OS Version      :  MacOS 10.14.3
    R Version       :   3.5.2

The problem with a grey only screen with no panes after starting reappeared again.
Resizing the main RStudio window helps, then the panes appear.

**Comment by hrbrmstr** [comment]
Can confirm issue but it's also unusable after doing so:

![image](https://user-images.githubusercontent.com/509878/53811540-a4a40d80-3f27-11e9-9c5e-bc7b048cb8cb.png)

This is likely related to the other Qt/macOS webkit display issues so might need to be ref'd and closed.

**Comment by ronblum** [comment]
@hrbrmstr What MacOS are you using? I've been able to reproduce on Mojave (10.14.4 beta), but it's working fine on a colleague's Sierra (10.12).

**Comment by kevinushey** [comment]
Yes, the latest macOS daily is broken. Long story. We're fixing it.

**Comment by ronblum** [comment]
Thanks @kevinushey! @dfalty just figured out that the OS isn't the issue; it works when software rendering is turned on.

**Comment by kevinushey** [comment]
The issue is that this build was produced on the old macOS builder (Sierra) by accident, which has known incompatibilities with the new version of Qt we're trying to update to. Once we update the builder to properly use Mojave, the issue should go away.

**Comment by kevinushey** [comment]
New version of v1.2.1318 is up and should be working as expected. Thanks for taking the time to test!

(sorry, it's been a frustrating endeavour getting to the bottom of these Qt issues)

**Comment by hrbrmstr** [comment]
@ronblum 10.14.4 Beta (18E184e) (I'm one rev behind since I had $DAYJOB production work to get done)

@kevinushey totes not frustrating. RStudio dailies are like a box of chocolates! Most are yummy but some make you 😝

btw i saw there's Qt support for touchbar so someone _may_ be playing with that in his not-so-spare time.

:-)
