### ISSUE TITLE
C++ support seems buggy in the preview version

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#4403]
I'm using RStudio Desktop Version 1.2.1139.

It looks like I cannot jump to the definition of the cpp function by Command + Click anymore. 

Moreover, since I'm using cpp11, whenever I use `auto`, the code auto-completion shows nothing.

And it displays errors for correct codes (I can compile it and in version 1.1.xxx it doesn't say this error). e.g.,

<img width="546" alt="image" src="https://user-images.githubusercontent.com/8368933/53899361-01610e80-4075-11e9-99d1-c5f0fc65a7dd.png">

**Comment by kevinushey** [comment]
The current preview release version is v1.2.1320-1. Do you still see the issue there? https://www.rstudio.com/products/rstudio/download/preview/

**Comment by shrektan** [comment]
@kevinushey Just tried, the problem still exists.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/8368933/53899728-d4f9c200-4075-11e9-933d-edff8e08e71c.png">

**Comment by kevinushey** [comment]
Thanks. Can you provide some extra context?

- Do you have Xcode command line tools installed? Did you also install the headers to `/usr/include`? This can be done with:

```
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```

- Are you currently working within an RStudio project? Is it a package project or no?

- Does the file that you're editing live within that project (e.g. in the `src/` folder)?

**Comment by shrektan** [comment]
> Thanks. Can you provide some extra context?
> 
> * Do you have Xcode command line tools installed? Did you also install the headers to `/usr/include`? This can be done with:
> 
> ```
> sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
> ```

Thanks for the prompt help. After executing this command, the error is gone now. `auto` can be recognized, although I don't remember it was required in the early versions.

However,  I still cannot jump to the definitions by Command + Click.  In addition, I noticed similar cases (can't jump) on my Windows machine today, whether in a package or just a project. 

> * Are you currently working within an RStudio project? Is it a package project or no?

Yes, an RStudio project. Not a package project.

> * Does the file that you're editing live within that project (e.g. in the `src/` folder)?

Yes, it's in a sub-folder of that project.

**Comment by kevinushey** [comment]
Thanks. As an aside, could you share the output of:

```sh
locate execinfo.h
```

when executed in the terminal? For example, I see:

```
kevin@zordon:~/rstudio [master]
$ locate execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/execinfo.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/execinfo.h
/Library/Developer/CommandLineTools.old/SDKs/MacOSX.sdk/usr/include/execinfo.h
/Users/kevin/.cache/cquery/@@Users@kevin@rstudio@src@cpp/@usr@include@execinfo.h
/Users/kevin/.cache/cquery/@@Users@kevin@rstudio@src@cpp/@usr@include@execinfo.h.json
/Users/kevin/projects/Libc/gen/execinfo.h
/Users/kevin/projects/chromium/src/native_client/toolchain/mac_x86/nacl_x86_glibc/x86_64-nacl/include/execinfo.h
/usr/include/execinfo.h
```

**Comment by shrektan** [comment]
Hi, here's the output:

```
shrektandeMacBook-Pro:routine-scripts Flynn$ locate execinfo.h

WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.
```

I've tried  `sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist` but it says `service already loaded` (see below). The output  of ` locate execinfo.h` stays the same after that (tried to quite RStudio and reopen, no change).

```
shrektandeMacBook-Pro:routine-scripts Flynn$   sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
Password:
/System/Library/LaunchDaemons/com.apple.locate.plist: service already loaded
```

**Comment by kevinushey** [comment]
Thanks. I _think_ that if the service is running, then the locate database will (eventually) be up-to-date and things should work as expected. Might be worth trying once more in an hour or so.

**Comment by shrektan** [comment]
Yes, now there's more output... Still cannot jump. Not sure if finished. I will check tomorrow.

BTW, any ideas why it has issues on Windows? Similar to this? Because I've run into the antivirus conflicts before, I thought it may relate to that... 

Thanks for your help.

```
shrektandeMacBook-Pro:routine-scripts Flynn$ locate execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/execinfo.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/execinfo.h
/usr/include/execinfo.h
```

**Comment by ronblum** [comment]
@shrektan Did you have a chance to try again, and if so, what was the result?

**Comment by shrektan** [comment]
@ronblum No, I still can't jump to the definition of the C++ functions. What should I try?

```
shrektandeMacBook-Pro:routine-scripts Flynn$ locate execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/execinfo.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/execinfo.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/execinfo.h
/usr/include/execinfo.h
```

**Comment by shrektan** [comment]
I reinstalled RStudio-1.1.463 and surprisingly found it doesn't work, either. I'm using R3.5.2.

I doubted it was caused by the default compiler so I installed the Clang6, which is the R3.5.2's compiler. However, as long as I add `PATH=/usr/local/clang6/bin` to `~/.Renviron`, not only the definition jump stays no response, but also [the diagnose error for correct codes](
https://github.com/rstudio/rstudio/issues/4403#issue-417914158) shows up again.  I thought RStudio used the bundled clang compiler and I'm wrong...

**Comment by kevinushey** [comment]
RStudio does indeed attempt to find and use the bundled version of libclang for diagnostics, so I'm surprised if that appears not to be true in your case.

**Comment by shrektan** [comment]
@kevinushey I've spent hours trying to find the cause for this issue about two weeks ago and find no luck. 

Right now, I'm pretty sure the setting in `~/.Renviron` will affect RStudio IDE, as I've mentioned, if I changed the PATH there, correct codes might be highlighted as errors. However, no matter what version of clang I use in `~/.Renviron`, the code definition jump still can't work.

In addition, pure C codes seem fine but not C++ codes. With the old version of RStudio (v1.0.153, v1.1.463), it still doesn't work (when I first raised this issue in Mar, v1.xxx showed no problem)

I still doubt the cause is the version of the compiler that RStudio is trying to use... The problem is I don't know how RStudio IDE decides the path of the C++ compiler to be used. I've tried to read the source code but not sure I understand it correctly.

What's strange is, I can't even make it work on my wife's Mac now, which only installed R & RStudio once one or two years ago... I'm totally confused.

Would you mind to share me your thoughts on this... and what's your `echo $PATH` look like (below is mine)? 

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/Flynn/instantclient_12_2
```

Thanks.

**Comment by shrektan** [comment]
BTW, another strange issue for me is that, since `data.table` requires `-fopenmp`, which is not supported by the default clang compiler of macOS. So I had to change the PATH in `~/.Renviron` in the past. But now, I can build `data.table` without that. From the log I know `/usr/local/opt/llvm/bin/clang` is used to build the package but it's not in my `PATH`,  isn't it? How RStudio IDE knows to use the clang in this PATH?

**Comment by shrektan** [comment]
@kevinushey Sorry. After I posted the above comment, I re-read [the doc for `data.table`](https://github.com/Rdatatable/data.table/wiki/Installation) again and realized that I should have edited `~/.R/Makevars` (my unreliable memory).

So I opened `~/.R/Makevars` and found that I've included the below lines for months... After I deleted those line, my RStudio IDE works great again for C++ codes now! It seems RStudio IDE will use the flag there somehow.

Anyway since the issue was resolved, I'll close this.

Many many thanks for your help! 

### The lines that I put in `~/.R/Makevars` which leads to this issue

```
# if you downloaded llvm manually above, replace with your chosen NEW_PATH/clang
LLVM_LOC = /usr/local/opt/llvm
CC=$(LLVM_LOC)/bin/clang -fopenmp
CXX=$(LLVM_LOC)/bin/clang++ -fopenmp
# -O3 should be faster than -O2 (default) level optimisation ..
CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/opt/gettext/lib -L$(LLVM_LOC)/lib -Wl,-rpath,$(LLVM_LOC)/lib
CPPFLAGS=-I/usr/local/opt/gettext/include -I$(LLVM_LOC)/include
```

**Comment by kevinushey** [comment]
:D Glad you were able to get to the bottom of this!

**Comment by shrektan** [comment]
I need to reopen this because I still have problems in RStudio IDE about C++ definition jumps, for one of the below cases:

1. When the CPP script is in a simple RStudio project instead of an R package. I mean I have no issues in R package project but for a normal project, the CPP definition jump can' t work.

1. When the R package enables C++14. It's fine if only C++11 gets enabled but not C++14. It should support C++14 on macOS, shouldn't it?

**Comment by kevinushey** [comment]
Is this with the latest preview release of RStudio as well? Can you share a package where you're seeing this issue?

I think we only enable C++ jump-to-definition specifically for package projects, though.

**Comment by kevinushey** [comment]
Thanks! I've marked this with a v1.3 milestone to remind myself to take a look before we prepare the v1.3 release.

**Comment by kevinushey** [comment]
I think this may be fixed via https://github.com/rstudio/rstudio/commit/2e6e6cd8f8df6c9591f3f7090e8d13aa0eacaf45. Can you let me know if you're still observing this issue in the latest daily builds of RStudio?

At least, it appears to be fixed for me with the latest dailies.

**Comment by shrektan** [comment]
Great news for me. I’ll verify this and get back to you. Thanks for this fix.

**Comment by kevinushey** [comment]
Awesome! Thanks for reporting back :-)
