### ISSUE TITLE
RStudio Version 1.1.463 on Mac OS 10.14.3 Fails upon Startup

### ISSUE THREAD

**Issue by susered** [rstudio/rstudio#4407]
### System details

RStudio Edition: Desktop
RStudio Version: 1.1.463
OS Version: Mac OS 10.14.3
R Version: 3.5.2

I have attached screenshots, the detailed report, and console application logging.

[https://gist.github.com/susered/135cba1bb57914922922b37179b98277](url)

### Steps to reproduce the problem

Just click on the RStudio icon or start the application from an Xterm.

### Describe the problem in detail

When start the RStudio application there are several pop-ups and error dialogs boxes that cause the application not to load at all. 

### Describe the behavior you expected

I expect the RStudio to work like the previous version.

**Comment by jmcphers** [comment]
Sorry, that attachment didn't work. Can you try pasting the diagnostic report as text?

**Comment by susered** [comment]
Hmm ... I have updated the link above. However, here it is again: https://gist.github.com/susered/135cba1bb57914922922b37179b98277

**Comment by susered** [comment]
Did the update link work for you?

**Comment by susered** [comment]
I also have a crash report as well: https://gist.github.com/susered/2ffe25e0c6d1d2d0d03b2d5ab0eac8f6

**Comment by kevinushey** [comment]
The crash report suggests that R is crashing while attempting to load the `yaml` package:

```
0   libR.dylib                    	0x000000010c151f6c Rf_install + 73
1   yaml.so                       	0x000000010c0642ad R_init_yaml + 22
2 libR.dylib 0x000000010118fdc8 AddDLL + 680 (Rdynload.c:634)
< ... >
```

Try reinstalling that package.

**Comment by susered** [comment]
Sure enough!

The Mac port installed version of R was the cause of the problem - did not reinstall, but just removed. However, the dynamically shared library, yaml.so, is installed in my local library:

/Users/username/Library/R/3.5/library/yaml/libs/yaml.so

Very odd, because the previous version of RStudio worked just fine.

Anyway! Much thanks!
