### ISSUE TITLE
Rendering issues on MacOS prior to Mojave

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4409]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1320
    OS Version      : MacOS prior to Mojave

### Steps to reproduce the problem

Launch RStudio.

### Describe the problem in detail

Scattered reports of scaling issues:

![image](https://user-images.githubusercontent.com/470418/53913041-33d82080-400f-11e9-8cda-f3fef17efbce.png)

https://community.rstudio.com/t/rstudio-preview-1-2-1320-not-displaying-well-on-macos-10-13-6/25472

https://twitter.com/davidmeza1/status/1103391320947806211

**Comment by davidmeza1** [comment]
I have been experiencing this for a while. I am on MAC 10.13.6 and RStudio 1.2.114. I have dual screens and by moving RStudio from one screen to the other, it corrects itself. I posted a short video on my twitter @davidmeza1

**Comment by jmcphers** [comment]
Also some reports (on Sierra) of fully white screens caused by the same issue. Via @jjallaire:

![image](https://user-images.githubusercontent.com/470418/53978800-f3d17600-40c0-11e9-8ce2-fa64c8a1767e.png)

**Comment by jmcphers** [comment]
We seem to be in a situation in which whatever version of MacOS is used to build RStudio is the only one on which it will work correctly, no matter how we set the associated target MacOS SDK versions and related variables (such as `MACOSX_DEPLOYMENT_TARGET`). We recently updated the RStudio build image to Mojave, which fixed everything for people running Mojave (see e.g. https://github.com/rstudio/rstudio/issues/3479, https://github.com/rstudio/rstudio/issues/4399) but appears to have broken things for those running older releases.

We're actively working on a fix and are hopeful we can find a combination of Qt/MacOS/SDK that produces a build that works on all MacOS versions. In the meantime, if you're affected by this issue, you can use [build 1.2.1312 or older from our dailies page](https://dailies.rstudio.com/rstudio/oss/mac/), or you can enable software rendering as follows:

1. Open Terminal.app and run: `open $HOME/Library/Preferences/com.rstudio.desktop.plist`

2. In the dialog that appears, change your rendering engine to `software`:

![image](https://user-images.githubusercontent.com/470418/53979558-0d73bd00-40c3-11e9-95f7-fc55946ba0de.png)

Apologies for the inconvenience, hopefully we'll have this straightened out soon!
