### ISSUE TITLE
Feature Request: Python autocomplete support for variables haven't defined yet.

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#4417]
For the example below, after entering "car." in print function, there is no autocomplete or function suggestions for the first time I type the code. It only shows up the second time after I run the codes.

```python
cars = ["bmw", "audi", "benz"]

for car in cars:
    print(car.title())
```

As I understand, RStudio's autocompletion only auto-completes based on variables already defined in the Python 'main' module. Could RStudio implement some sort of semantic analysis for the autocompletion working on variables first appear as in the example?

**Comment by ntluong95** [comment]
Should we bring this feature to R in next builds?
