### ISSUE TITLE
i3 tiling manager - rstudio doesn't run

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#4420]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 1.2.1321 - Ubuntu 14/Debian 8 (64-bit)
    OS Version      : Ubuntu 18.04.2 LTS
    R Version       :  3.52

### Steps to reproduce the problem

 * Download the tarball
 * Open rstudio via command line

### Describe the problem in detail

 * What works:
   * tar/zip RStudio   under unity or gnome
   * debian version under [i3](https://i3wm.org/) window manager
 * What doesn't work
  * tar/zip RStudio  under i3. The RStudio window launches, but it remains completely black. No panes are loaded.
 * RStudio doesn't crash. It's just a black box.

**Comment by gtritchie** [comment]
Please try the Ubuntu 18 build:

![2019-03-08_09-39-16](https://user-images.githubusercontent.com/10569626/54045319-22fdeb00-4186-11e9-9419-58abd2aaebca.png)

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by ronblum** [comment]
@csgillespie I'm closing the issue, since it appears to be using wrong build. If you're still having issues, please reopen and let us know. Thanks!

**Comment by csgillespie** [comment]
@ronblum This doesn't solve the issue.

Your screen shot points to the binary. This is fine if you have sudo access. As an aside, this works on my laptop with the same setup.

On my desktop, I don't have sudo access, so I can't install the binary. For years, I've been using the tarball. The tarball method works under Unity/gnome. But not under i3.

**Comment by gtritchie** [comment]
Apologies on that, didn't notice you were using the tarball. I'll follow up and see why we don't have links to the other tarballs on the preview page.

Can you give https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.2.1321-amd64-debian.tar.gz a try and see if it makes any difference?

**Comment by csgillespie** [comment]
That works. Thanks

**Comment by gtritchie** [comment]
Great! I've opened #4429 to make sure we get links to all flavors on our download pages.
