### ISSUE TITLE
Unable to launch RStudio when compiled from source

### ISSUE THREAD

**Issue by skoestlmeier** [rstudio/rstudio#4421]
### Problem

RStudio fails to launch when the application is built from source with the current master-branch. Trying to start the application from a terminal results in the error:

    ./rstudio: error while loading shared libraries:
    libQt5WebEngine.so.5: cannot open shared object file: no such file or directory

### System details

    RStudio Edition : Desktop
    RStudio Version : current master-branch
    OS Version      : Debian 9.8 (x86_64), kernel: 4.9.0-8-amd64
    R Version       : 3.3.3 (Another Canoe), x86_64-pc-linux-gnu (64-bit)

### Steps to reproduce the problem

1.  Download and unzip current master-branch in home directory
2.  Switch directory and install dependencies:
    `$ cd /home/user/rstudio-master/dependencies/linux/`
    `$ ./install-dependencies-debian`

3. `$ cd ../../`
    `$ mkdir build`
    `$ cd build`
4. `$ cmake .. -DRSTUDIO_TARGET=Desktop -DCMAKE_BUILD_TYPE=Release`
5. `$ sudo make install`

These steps exactly follow the INSTALL documentary in top of the RStudio master-branch.

**Comment by jmcphers** [comment]
Try replacing step 4 with this:

    cd rstudio-master/package/linux
    make-package Desktop DEB

Does that work?

**Comment by skoestlmeier** [comment]
> ```
> cd rstudio-master/package/linux
> make-package Desktop DEB
> ```
> Does that work?

I just tested this in a fresh Debian installation (with same settings as initially) and RStudio still fails to launch. Starting in the terminal, i also receive the same error with your suggested installation procedure:

    `./rstudio: error while loading shared libraries:
    libQt5WebEngine.so.5: cannot open shared object file: no such file or directory`

**Comment by skoestlmeier** [comment]
Seems to be related with the (still open) issue #3061. I have tried the suggested solutions above and the ones described in #3061, but none could resolve the issue. @jmcphers, i consider this to be a very important issue for developers - i need to build RStudio from source because i would like to implement some contributions and therefore help improving this project. However, it is frustrating to not getting started with work due to a broken installation mechanism.

**Comment by gtritchie** [comment]
I have been updating our dependency scripts to make it easier to get an RStudio dev environment up and running. Windows, Mac, and Ubuntu 18 Bionic are what I've focused on so far, but I will take a look at Debian.

**Comment by gtritchie** [comment]
The main problem here was that we weren't installing "patchelf" via our scripts. We do in our dockerfiles but that requirement wasn't included in these scripts. Needed only for desktop, not when building RStudio server.

With that installed, then "make-package" will produce a working DEB or RPM.

For "make install" to work, it is also required to include -DRSTUDIO_PACKAGE_BUILD=1 when running cmake.
