### ISSUE TITLE
Job progress bars don't span the width of the pane

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4423]
## Repro

In RStudio 1.2.1322, start a job with ranged output. The progress bars should span the width of the Jobs pane, but are much too short.

![image](https://user-images.githubusercontent.com/470418/54062911-ee0d8a80-41bd-11e9-9965-b9aea0ec44fe.png)

**Comment by jmcphers** [comment]
@gtritchie fixed this in #930.

**Comment by dfalty** [comment]
Verified fixed 1.2.1330-2.
