### ISSUE TITLE
Huge font size on Windows 7 in Retina Display

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#4424]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1322
    OS Version      : Windows 7 (in a virtual machine in a MacBook Pro)
    R Version       : 3.5.2

### Steps to reproduce the problem

Running the preview version of RStudio in Windows 7 running in a virtual machine (Parallels Desktop ) in an MBP.

### Describe the problem in detail

The font size is extremely big. I simply can't use the preview version of RStudio on it.

**Using  RStudio 1.1.463**

<img width="523" alt="屏幕快照 2019-03-09 下午11 21 20" src="https://user-images.githubusercontent.com/8368933/54073537-4ed2bb00-42c3-11e9-922c-e4bba03ad0bd.png">

**Using RStudio 1.2.1322**

<img width="554" alt="屏幕快照 2019-03-09 下午11 22 32" src="https://user-images.githubusercontent.com/8368933/54073539-54300580-42c3-11e9-955d-552ac99687c4.png">

The MBP uses Retina displays... and this is the root cause I believe.

### Describe the behavior you expected

It displays the same font size as before.

[The diagnose report](
https://gist.github.com/shrektan/f8a63335f20ea294bd38f175d5e58fef/841e365dfc1713165d92e38c606c02f2d766a87f#file-win7-retina-display-rstudio-desktop-1-2-1322-diagnostics-report-txt)

**Comment by kevinushey** [comment]
Not to be a downer, but Windows 7 is now a nearly 10 year old operating system, and Microsoft will be [ending support](https://www.microsoft.com/en-us/windowsforbusiness/end-of-windows-7-support) early next year. If the issue occurs with Windows 7 but not Windows 10, it's unlikely we'll take the time to fix it.

**Comment by kevinushey** [comment]
Not to be a downer, but Windows 7 is now a nearly 10 year old operating system, and Microsoft will be [ending support](https://www.microsoft.com/en-us/windowsforbusiness/end-of-windows-7-support) early next year. If the issue occurs with Windows 7 but not Windows 10, it's unlikely we'll take the time to fix it.

**Comment by ronblum** [comment]
@shrektan Using Windows 7 in VMWare on a Mac with a retina display,  I'm only able to reproduce the larger fonts by increasing the zoom level (Tools -> Global Options -> Appearance -> Zoom). This should be the same for 1.1 and 1.2, though. Still, it might be worth trying out a different zoom level to see if that helps.

**Comment by shrektan** [comment]
@ronblum Thanks for the test. I'm using Parallels Desktop with Win7, which may be different from VMWare. Anyway, I'm preparing an updating to Win10. If similair issues happened, I will reply it here.

**Comment by shrektan** [comment]
Close it because it works fine on VMWare with Win10. Maybe it's just because of my previous installed Parallels Desktop version was too old but who cares... Thanks!

**Comment by kevinushey** [comment]
Interesting. I had switches from VMware to Parallels for basically the same reason a while back :-)

**Comment by gtritchie** [comment]
I went from VirtualBox to VMWare for similar reasons. There was a particularly bad version of VMWare Fusion at one point a couple years ago but last few rev’s have been well behaved for me.

**Comment by ronblum** [comment]
@shrektan Thank you for the update!
