### ISSUE TITLE
ssh works in git bash but fails in git bash within RStudio

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4425]
I get this behavior with both RStudio standard release and RStudio preview.

I am on Windows 10. The most obvious difference is that RStudio ends up using `OpenSSH_for_Windows_7.7p1` (and failing) and Git Bash by itself uses `OpenSSH_7.9p1`.

```bash
# Fails
$ ssh -vvv mahuika
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\kmbel/.ssh/config
debug1: C:\\Users\\kmbel/.ssh/config line 7: Applying options for mahuika
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec ssh -W login.mahuika.nesi.org.nz:22 lander
debug3: spawning "C:\\WINDOWS\\System32\\OpenSSH\\ssh -W login.mahuika.nesi.org.nz:22 lander"
CreateProcessW failed error:2
posix_spawn: No such file or directory
```

Expected behavior using Git Bash outside of RStudio:
```
kmbel@DESKTOP-VUFG094 MINGW64 ~
$ ssh -vvv mahuika
OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018
debug1: Reading configuration data /c/Users/kmbel/.ssh/config
debug1: /c/Users/kmbel/.ssh/config line 7: Applying options for mahuika
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec ssh -W login.mahuika.nesi.org.nz:22 lander
debug1: identity file /c/Users/kmbel/.ssh/id_rsa type -1
debug1: identity file /c/Users/kmbel/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/kmbel/.ssh/id_dsa type -1
debug1: identity file /c/Users/kmbel/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/kmbel/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/kmbel/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/kmbel/.ssh/id_ed25519 type -1
debug1: identity file /c/Users/kmbel/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/kmbel/.ssh/id_xmss type -1
debug1: identity file /c/Users/kmbel/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
First Factor:
```

**Comment by kendonB** [comment]
So this is working fine on my other Windows computer which is *also* running RStudio 1.1.463. So it's definitely something environmental - any help in working out what's going on would be helpful.

I am quite concerned that RStudio is switching the ssh program from the default in Git Bash as security updates come through automatic updates to Git Bash.

**Comment by jmcphers** [comment]
What does `echo $PATH` show you in both cases? More than likely there's an environment var in play (and that's the most likely culprit).

**Comment by serpico7456** [comment]
@kendonB I was having the same problem. Does it work if you use this explicit ssh path? 
`$ /usr/bin/ssh mahuika`

**Comment by kendonB** [comment]
@serpico7456, yes that does work. Thanks!

**Comment by serpico7456** [comment]
I suspect you are using Windows 10 1803 or later.  That's when Microsoft began bundling OpenSSH.  RStudio's terminal uses that version by default (`/c/WINDOWS/System32/OpenSSH/ssh`) instead of the bundled ssh version (`/usr/bin/ssh`).

**Comment by kendonB** [comment]
This one would be solved by solving https://github.com/rstudio/rstudio/issues/4623. Closing here
