### ISSUE TITLE
keep_md, fig.cap, and blank lines

### ISSUE THREAD

**Issue by krcoombes** [rstudio/rstudio#4427]
There appears to be a strange interaction between the YAML option "keep_md: true", the use of the "fig.cap" option in an R markdown file, and whether or not the code chunk containing the figure caption is immediately followed by a blank line.

With "keep_md: true", figure captions in code chunks _without_ a following blank line are converted to "alt" text and not displayed as captions.  Figure captions in code chunks _with_ a following blank line appear as actual captions, as expected.

Without "keep_md: true", figure captions appear correctly regardless of whether you put a blank line immediately after the code chunk.

The attached zip file contains a minimal reproducible example, along with the outputs.

[bugReport.zip](https://github.com/rstudio/rstudio/files/2952652/bugReport.zip)

**Comment by ronblum** [comment]
@krcoombes Thank you for reporting this issue. I've reproduced this on RStudio Desktop 1.2.1322 on MacOS 10.14. We'll review it as we work on ongoing development of RStudio.
