### ISSUE TITLE
pass arguments to job works

### ISSUE THREAD

**Issue by Iuiu1234** [rstudio/rstudio#4428]
Jobs panel allows you to choose script & working directory.
But there's no option to define which arguments you pass to the script.

Is this is a bug?
Or is it supposed to work this way?

Rstudio  1.2.1289

thanks

**Comment by gtritchie** [comment]
This is the current design. Marking this as an enhancement request.

Currently to pass information into a job you must set it in the global environment and use the "Run job with copy of global environment" option. 

![2019-03-11_09-19-01](https://user-images.githubusercontent.com/10569626/54139531-fd1f5300-43de-11e9-8de0-234facb0fdaf.png)

**Comment by jmcphers** [comment]
Yes, we haven't made these parameterizable yet. We're tracking that in this feature request (feel free to comment/upvote!)

https://github.com/rstudio/rstudio/issues/4176

If you're looking for a more scriptable way to invoke asynchronous R jobs with parameters, try callr: https://github.com/r-lib/callr

**Comment by nxskok** [comment]
One way to have parameters is to put them in a list, use saveRDS to save them in a file, and then use readRDS at the start of the script to retrieve them.
