### ISSUE TITLE
Add download links for all platform/version installers

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#4429]
https://www.rstudio.com/products/rstudio/download/preview/

The download preview page only shows the `Ubuntu 14/Debian 8 (64-bit)` tarball, but we produce them for several different platforms and platform-versions.

Similarly, it is missing some downloads for Server and Server Pro, and does not show Desktop Pro at all (the latter might be by-design).

Also need to make sure the download release page includes them all when 1.2 is released.

**Comment by ronblum** [comment]
SLES/openSUSE 15+ is also missing under RSP.

**Comment by jmcphers** [comment]
Should be fixed up now. https://www.rstudio.com/products/rstudio/download/preview/
