### ISSUE TITLE
Cobalt theme's markdown header background color is black

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4430]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.1332
    OS Version      : Any (based on MacOS & Ubuntu)
    R Version       : 3.x

### Steps to reproduce the problem

In a Notebook/R Markdown file, create a a header outside of a chunk:
`# Header`

### Describe the problem in detail

When the Cobalt is theme applied, the background color is black, inconsistent with the rest (maybe \#000000?):
<img width="282" alt="cobalt" src="https://user-images.githubusercontent.com/31009952/54140286-a8d59c80-43f9-11e9-9be2-1d8cd3bae626.png">

### Describe the behavior you expected

The background color should be consistent with the rest (002240, I believe).

(This is not a regression—it's the same in 1.1.)

**Comment by jmcphers** [comment]
It does look kinda weird -- but it appears to be the intent of the theme creator.
