### ISSUE TITLE
Notebook and remote table: kable forces a collect

### ISSUE THREAD

**Issue by lepennec** [rstudio/rstudio#4433]
Dear all,

I've stumbled on a small issue when using a notebook (or more generally the Chunk Output Inline option) and a DBI connection. The default choice is to use kable to display the tables. This works as expected for local table but has the unfortunate side effect to collect the tables if they were not local. This is different from the usual behavior which collect only a few line from the remote database.
This behavior is consistent with any DBI connexion. For instance, using RSQLite:

    title: "R Notebook"
    output: html_notebook
    ---
    ```{r}
    library(RSQLite)
    library(dplyr)
    con <- dbConnect(SQLite(), "iris")
    copy_to(con, iris, "iris")
    tbl(con, "iris")
    ```
There is a global option setting to modify this behavior

options(paged.print = FALSE)

but it disables the nice kable display for all the tables whereas they are local or not.

I feel a better option would be to have a different behavior for local and remote tables so that we can keep the nice kable display even when some tables are not local.

Thank you and let me know how I can help.

**Comment by ronblum** [comment]
@lepennec I believe I've reproduced what you mean; I added one line at the end,
```
iris
```
just as a comparison between the two. Would you mind confirming that when you knit the file, you get what you expect?

**Comment by lepennec** [comment]
I think so. If you don't specify the page.print option, `tbl(con, "iris")` and `iris` yield the same results. If it is specified to `false`, you should obtain two different results.
