### ISSUE TITLE
Add option for number of files tracked in Recent Files 

### ISSUE THREAD

**Issue by geebioso** [rstudio/rstudio#4434]
I would like to request a feature that exposes a parameter for the number of recent files tracked (number tracked is currently limited to 15). 

At work I routinely touch 20-30 different R scripts over any given week. These scripts are related to individual projects and are stored in project specific directories on a shared server. The directories are  organized hierarchically in a way that requires clicking through many subdirectories to access each script. Due to the iterative nature of these projects, I often have to alter a script after I have touched at least 15 other scripts. This functionality would help me quickly access a given file without having to trace through each project directory. 

Cheers!

**Comment by ronblum** [comment]
@geebioso That's an interesting suggesting. Thank you for it, and we'll review it as we continue development of the RStudio IDE.

**Comment by geebioso** [comment]
You bet. Thank you!
