### ISSUE TITLE
Feature request: notebook with keyboard shortcut to run selected text or current line in console

### ISSUE THREAD

**Issue by hauselin** [rstudio/rstudio#4440]
When using R Notebooks (with setting Chunk Output Inline), I sometimes prefer to print a selected section or line in the console rather than inline. Rather than change the global setting to "Chunk Output in Console", is it possible to let users define their own keyboard shortcuts to run selected text or current line in console? 

That is, the global setting is still "Chunk Output Inline", but I can choose to run selected text or current line in the console whenever I want to, without having to change the global setting. JupyterLab has this feature (https://github.com/jupyterlab/jupyterlab/issues/4206) and it's really useful, especially when doing exploratory stuff that shouldn't be included in the notebook inline output. 

Thanks!

**Comment by ronblum** [comment]
@hauselin Thank you for the suggestion! We'll consider it as we continue development of RStudio.
