### ISSUE TITLE
debug statements in .Rprofile cause IDE to hang

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4443]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1322
    OS Version      : macOS 10.14.3
    R Version       : 3.5.2

### Steps to reproduce the problem

Try creating a `.Rprofile` with a browser statement, e.g.

```r
local({
  browser()
})
```

Then, attempt to launch RStudio.

### Describe the problem in detail

RStudio gets stuck displaying only a loading indicator.

### Describe the behavior you expected

RStudio should load the UI and present the debugger, or disable the debugger so the user doesn't get stuck in this state.

This is a regression from v1.1, but not really a blocker, so filing for v1.2-patch.

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio/pull/4550.

**Comment by ronblum** [comment]
Verified in RStudio 1.2.1522 on MacOS 10.14.6.
