### ISSUE TITLE
RStudio preview fails to render window on Mac OS Mojave 10.14.4 Beta 18E215a 

### ISSUE THREAD

**Issue by md0u80c9** [rstudio/rstudio#4445]
Hi,

I've been using RStudio 1.2 Preview with Mac OS Mojave preview builds and not had any problems to date.

I updated with yesterday's preview (Beta 5) and since then RStudio fails to open the IDE window. Replicated on both an iMac and a MacBook Pro.

I've checked with the latest version of RStudio preview and seen the same results.

Clearly not sure if this is a bug with the Mojave beta, or an issue with the way RStudio renders.

![Screenshot 2019-03-13 at 07 36 07](https://user-images.githubusercontent.com/3925834/54261125-dc800600-4562-11e9-8ee5-39146e3edf38.png)

**Comment by jmcphers** [comment]
What's the exact version of RStudio you're using?

**Comment by md0u80c9** [comment]
1.2.1206 Exhibited this although I subsequently downloaded the latest version from the RStudio Preview website and this also did this too (don't have the exact version to hand but the one from the website yesterday).

**Comment by kevinushey** [comment]
If you resize the window a tiny bit, does the UI become visible?

If it does, can you please take a screenshot of the <kbd>Help -> About RStudio</kbd> dialog?

**Comment by md0u80c9** [comment]
No - in fact the screenshot was resized.

I can’t pull up the About RStudio dialog - the menus work but no windows open.

Best wishes,

Andrew

**Comment by jmcphers** [comment]
I just updated to 18E215a and I can now reproduce this as well.

**Comment by kevinushey** [comment]
@jmcphers can you test:

- Can you reproduce with a local build?
- Does the Nano Browser example exhibit the same issue?
- Does removing the `wantsLayer = YES` flag fix things? https://github.com/rstudio/rstudio/blob/19fe1822d6817e7557bf9ebb14cbadd1000d0de3/src/cpp/desktop/DesktopGwtCallbackMac.mm#L482

**Comment by jmcphers** [comment]
- I can reproduce with a local build. 
- I can't check Nano Browser because Qt Creator seems completely busted (the interface draws but is unresponsive). 
- Removing that line doesn't change the behavior.

It's clear that the interface is actually loading; for example if I move my cursor over it it will change to a hand in some spots. Also, triggering a repaint by right-clicking and choosing Reload, or opening the dev tools, fixes everything.

Unlike the wantsLayer issue, however, this affects every RStudio window -- even the devtools show up blank.

![image](https://user-images.githubusercontent.com/470418/54301628-9041bf80-457c-11e9-8d4f-59c402560cbb.png)

**Comment by kevinushey** [comment]
Dear lord...

Can we reproduce this in any other Chromium-using application? What about [qutebrowser](https://www.qutebrowser.org/)? (Use `brew cask install qutebrowser` to install)

**Comment by jmcphers** [comment]
Other chromium-based apps work fine (qutebrowser, VS Code, and Slack). Qt Creator is pretty busted, so I wonder if 12.1 has some compatibility issues to work out... 

![image](https://user-images.githubusercontent.com/470418/54302516-478b0600-457e-11e9-84e3-39e236557f8c.png)

**Comment by jmcphers** [comment]
Opened a Qt Creator bug here: https://bugreports.qt.io/browse/QTCREATORBUG-22131

It looks like this is an issue with QtWebEngine from Qt 5.12.1, not just with RStudio (appears to reproduce with nanobrowser). Once I've done some more verification I'll open up a QTBUG.

**Comment by ukyoi** [comment]
Maybe it's a bug of macOS since it seems only happens on 10.14.4 beta 18E215A. As everyone knows the OpenGL support on macOS is just a mess.

**Comment by jmcphers** [comment]
Also reported on Twitter. https://twitter.com/DSmilti/status/1106270572676374529

**Comment by kevinushey** [comment]
The issue appears to affect all applications using Qt Quick with Qt 5.12.x: https://bugreports.qt.io/browse/QTBUG-74452

Hopefully this is an issue that will just go away in the next iteration of the Mojave preview release...

**Comment by md0u80c9** [comment]
Indeed. I have reported it on bugreport.apple.com and have linked to this issue.

**Comment by hemip** [comment]
Can confirm this bug running Rstudio preview (v1.2.1326-1 Preview) and was affected when I upgraded my Mac to Mojave 10.14.4 beta today. However, the stable version of Rstudio (1.1.463) is not affected.

**Comment by carloscinelli** [comment]
I can also confirm the bug for RStudio v1.2.1327-1 - Preview.

**Comment by kevinushey** [comment]
Can you file a bug report with Apple?

**Comment by hrbrmstr** [comment]
I submitted as well. Problem ID 48962598 for ref (if needed)

**Comment by tyluRp** [comment]
RStudio 1.2.1326 now works for me on the latest MacOS Mojave Beta 18E220a. Was previously not working on 18E215a.

**Comment by hrbrmstr** [comment]
ah! I see that macOS beta update just dropped. 

I'm now hesitating since a "console output stalling" issue that I was attributing to my system seems to not be "A Thing" in 1.1.x RStudio and I have no way of even beginning to diagnose/triage/report except to record an animated gif.

**Comment by md0u80c9** [comment]
I can confirm the latest beta resolves this issue: I'd suggest closing the issue if everyone in agreement.

**Comment by hrbrmstr** [comment]
same. Apple reverted whatever they broke.

**Comment by kevinushey** [comment]
That sound you hear is me and the rest of the IDE breathing a heavy sigh of relief. Thanks everyone for testing and verifying!

**Comment by jmcphers** [comment]
Can also confirm this. Whew!

**Comment by ronblum** [comment]
Joyously verified.
