### ISSUE TITLE
Spaces per tab option not applied to .Rmd files

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4448]
**Steps to reproduce:**
* Set the spaces per tab to something different from 2, e.g. `Tools` → `Global options` → `Code` → `Tab width = 4`.
* Uncheck `Insert spaces for tab`.
* Create some .Rmd document through Rstudio’s menu (Button below file that shows a blank page with a green plus sign → `R Markdown...` → `Ok`.
* Start writing something there that would automatically add tabs, e.g. this (but write it from scratch without copy-pastying):
```r
df = data.frame(
	coldata = c(1, 2)
)
```

**Expected behavior:** should use the number of spaces per tab that is configured in the global options (in this case 4), just like in `.R` files.

**Actual behavior:** keeps using the default spaces per tab (2).

**Setup:** RStudio 1.2.1322, R 3.5.1, running on windows 10.

**Comment by ronblum** [comment]
@david-cortes Are you in a project, per chance? If so, the project setting will over the global setting: Tools -> Project Optios -> Code Editing

**Comment by david-cortes** [comment]
@ronblum : happens in a project which also has a non-default setting for spaces per tab. The project's setting is not applied either.

**Comment by kevinushey** [comment]
I'm not able to reproduce. For new documents, the requested indentation style (as provided either by global settings or project settings) is properly respected.

**Comment by kevinushey** [comment]
You might also want to check whether (for existing files) the option:

- [x] Auto-detect code indentation

is affecting the behavior you're seeing. See:

<img width="595" alt="Screen Shot 2019-03-14 at 9 29 07 AM" src="https://user-images.githubusercontent.com/1976582/54374116-b0848380-463b-11e9-83d5-e7463983482c.png">

**Comment by david-cortes** [comment]
@kevinushey : I have that setting ticket in (Auto-detect code indentation), but his happens with newly created documents. For me, the indentation type is applied, i.e. it uses tabs instead of spaces, but the tab width is not - that is, one tab is still the same width as two characters rather than 4.

**Comment by kevinushey** [comment]
Perhaps this is what you're seeing... Reproduction steps:

1. Create a new RStudio project.
2. Open the project options. Uncheck 'Insert spaces for tab', and set the tab width to 8.
3. Create a new file (<kbd>Ctrl + Shift + N</kbd>) and insert a tab. It should be 8 spaces, as expected.
4. Try running this R code:

```r
text <- rep("  indent", 10)
writeLines(text, con = "file.R")
file.edit("file.R")
```

Go to the bottom of the file, and try inserting a tab. It will be of size 2 rather than 8.

**Comment by kevinushey** [comment]
The issue goes away if I turn off the aforementioned auto-indentation preference.

**Comment by david-cortes** [comment]
@kevinushey : it would work if I follow those steps, but the thing is, the problem is only with `.Rmd` files, not with regular `.R` files. Now I also realize, **a)** this problem only happens in some situations when I create the `.Rmd` after switching projects through the button at the top-right corner (that is, switching to a project with tabs and 4-width will then creating a new doc), **b)** the problem dissappears if I close RStudio and open it again (that is, the same file opens showing tabs as 4 spaces).

**Comment by kevinushey** [comment]
Are you opening files cross-project? Note that RStudio tries to be smart and respect the project settings of the project hosting the file, not the current active project.

**Comment by david-cortes** [comment]
@kevinushey : no, I'm not opening files from another project. Even if that were the case, I have the same settings for all projects + the global settings.

**Comment by kevinushey** [comment]
Okay, ultimately I cannot reproduce with your original reproduction steps so if you can ascertain what might be different or what specific steps are needed that would be useful.

**Comment by L-S-M** [comment]
I am also seeing this issue.

It has to do with the code in .Rmd code blocks, eg:
`
\`\`\`{r}
compute_s_n <- function(n) {
  x <- 1:n
  sum(x)
}
\`\`\`
`
No matter what the global or project settings, the tab/indentation is _always_ set at 2 spaces and cannot be changed.

**Ubuntu, RStudio Version 1.3.1093**
