### ISSUE TITLE
Bug in "multi-line R statement execution" (using Ctrl+Enter) when certain characters are in a string in the last line on their own

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#4452]
I apologize for the very badly titled bug report.

Windows 7 RStudio 1.1.463

I found that when I try to run a function with Ctrl+Enter and that function contains a string with certain characters, the execution breaks.

I initially wanted to post this bug, which is an actual realistic example, of including CSS:

```
foo <- function() {
  bar <- "
.green {
  color: green;
}
"
}
```

That's a simplified example of something I sometimes do - define some short CSS as a variable in a string. If you copy that into RStudio, RStudio will re-indent the CSS lines, but if you de-indent so that it looks exactly like above, and try to ctrl+enter the `foo` function, you get this:

```
> foo <- function() {
+   bar <- "
+ .green {
+   color: green;
+ }
+   "
+ 
```

The console doesn't realize that the CSS string was closed. The same is true if you have more code after defining that string.

Note that the following does not have any problems (moving the closing quotations `"`" to the same line as the closing bracket `}`):

```
foo <- function() {
  bar <- "
.green {
  color: green;
}"
}
```

And having the closing bracket indented by one space also doesn't cause a problem. 

After experimenting with this some more, I noticed that the smallest code that still results in this error is simply having a closing bracket inside a string on its own line. For example

```
function() {
"
}
"
}
```

This still results in the same error. The same if true for other characters, for example replace the `}` with `[` in the string also has the same effect. If you add a few lines with text before and after the `}`, you will still see this problem, as long as somewhere inside the string there is a line that only consists of `}`. Also note that ctrl+enter when the cursor is on the string itself will correctly execute the string, so the problems only happens when trying to execute a larger context around the string.

**Comment by pascaloettli** [comment]
Do you get the same result with the [preview version](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by david-cortes** [comment]
I can reproduce it with the preview version 1.2.1233.

**Comment by pascaloettli** [comment]
I don't reproduce on Ubuntu. Specific to Windows?

**Comment by david-cortes** [comment]
I can also reproduce it on Linux (Debian stretch, running KDE 5.12), with the non-preview version.

**Comment by kevinushey** [comment]
Thanks for the bug report. I've reproduced this and have a PR incoming.

**Comment by daattali** [comment]
For the record, this seems to have been resolved at some point (likely with @kevinushey 's PR that he mentioned)
