### ISSUE TITLE
Tab style not applied to multi-lines inside parentheses

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4454]
**Steps to reproduce:**
* Set tab style to width 4 and no spaces (`Tools` → `Global Options` → `Code` → `Tab width` = 4 and uncheck `Insert spaces for tab`).
* Write some multi-line statement that would generate tabs in lines that are within parentheses, e.g. this (but write it from scratch instead of copy-pastying):
```r
df1 %>%
	mutate(some_col = 1) %>%
	rbind(other_df %>%
		  	select(col1, col2))
```
(Note the spacing before the `select`)

**Expected behavior:** tabs inserted in the second and further line between the parentheses should follow configured tab style.

**Actual behavior:** tabs inserted inserted in the second and further lines right before the text start have two spaces (the default style). These double spaces are also preserved as an extra tab when writing more lines that use more tab spaces.

**Setup:** R 3.5.1, RStudio 1.2.1322, running on windows 10.

**Comment by kevinushey** [comment]
Screenshot with visible whitespace characters for posterity:

![Screen Shot 2019-03-15 at 9 42 05 AM](https://user-images.githubusercontent.com/1976582/54447413-9bc0f200-4706-11e9-91b5-f99d5ffe5bef.png)

**Comment by kevinushey** [comment]
I was able to reproduce all the way back to v0.99 so this bug has existed for quite some time.

**Comment by david-cortes** [comment]
Funny thing: when this other bug is affecting the document: https://github.com/rstudio/rstudio/issues/4448
then these tabs are actually inserted as tabs :).

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.
