### ISSUE TITLE
Edit Documentation on RStudio Support

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#4461]
Is there a way to edit documentation found on <https://support.rstudio.com>?

For instance, I'd like to change the ["Secure Package Downloads for R"](https://support.rstudio.com/hc/en-us/articles/206827897-Secure-Package-Downloads-for-R) to emphasize that the variable `RSTUDIO_DISABLE_SECURE_DOWNLOAD_WARNING` should be set in `.Renviron` and not `.Rprofile` as is stressed on the page.

**Comment by pyltime** [comment]
Thanks for the feedback - we'll look into it and see if we can make any improvements to our documentation here.

**Comment by coatless** [comment]
@pyltime would it be possible to get an RStudio IDE desktop manual shown with the other manuals? c.f. https://docs.rstudio.com/products.html
