### ISSUE TITLE
pandoc document conversion failed with error 11

### ISSUE THREAD

**Issue by jrminter** [rstudio/rstudio#4462]
This error has been seen before but all reports are CLOSED

### System details

    RStudio Edition : Desktop Version 1.2.1327
    RStudio Version : 3.5.2
    OS Version      : Windows 7 x64 build 7601, Service Pack 1
    R Version       : 3.5.2

### Steps to reproduce the problem

Knit the R-tips.Rmd file (long...)

### Describe the problem in detail
it crashes the 'Access violation in generated code when reading 0x86879d8'
on the first or second knit

### Describe the behavior you expected
I expect it to knit.

Note a workaround: it will reprodcuiby knit if I substitute te RStudio Pandoc with 
pandoc-2.5-win32

**Comment by kevinushey** [comment]
You are likely seeing the same issue as https://github.com/rstudio/rstudio/issues/4072. If you're willing, we have a copy of Pandoc 2.7.1 built against GHC 8.6.4 that you may have better luck with:

```
# Download pandoc 2.7.1 built with ghc-8.6.4, and instruct
# RStudio + rmarkdown to use it.

local({
	
	# The directory where Pandoc will be extracted. Feel free
	# to adjust this path as appropriate.
	dir <- "~/rstudio-pandoc"
	
	# The version of Pandoc to be installed.
	version <- "2.7.1"
	
	# Create and move to the requested directory.
	dir.create(dir, showWarnings = FALSE, recursive = TRUE)
	owd <- setwd(dir)
	on.exit(setwd(owd), add = TRUE)
	
	# Construct path to pandoc.
	root <- "https://s3.amazonaws.com/rstudio-buildtools"
	suffix <- sprintf("pandoc-%s-windows-x86_64.zip", version)
	url <- file.path(root, "pandoc-rstudio", version, suffix)
	
	# Download and extract pandoc.
	file <- basename(url)
	utils::download.file(url, destfile = file)
	utils::unzip(file)
	unlink(file)
	
	# Write .Renviron to update the version of Pandoc used.
	entry <- paste("RSTUDIO_PANDOC", shQuote(path.expand(dir)), sep = " = ")
	contents <- if (file.exists("~/.Renviron")) readLines("~/.Renviron")
	filtered <- grep("^RSTUDIO_PANDOC", contents, value = TRUE, invert = TRUE)
	amended <- union(filtered, entry)
	writeLines(amended, "~/.Renviron")
	
	# Report change to the user.
	writeLines("Updated .Renviron:\n")
	writeLines(amended)
	writeLines("\nPlease restart RStudio for these changes to take effect.")
	
})
```

**Comment by jrminter** [comment]
Thank you. The script worked well, both on my Win7 x64 box and on my Win10 x64 Parallels VM. I did need to run RStudio as an Administrator on the Win 10 VM because the directory permissions were stricter. This version of pandoc is great. I've always been been perplexed about the cause of these access errors...

**Comment by statneutrino** [comment]
This version of pandox seems to be faster as well!

**Comment by npmldabook** [comment]
Thanks.  I tried to knit it to slidy slides and got lots of error messages. This script fixed my problem.

**Comment by sjmonkley** [comment]
The URL for the updated version of pandoc for Rstudio no longer exists

**Comment by alexandrerodrigues34** [comment]
Me ajudou. Estava com o seguinte problema - pandoc document conversion failed with error 1033
