### ISSUE TITLE
Order of operations when knitting

### ISSUE THREAD

**Issue by krcoombes** [rstudio/rstudio#4463]
**Background:** I often have problems when using the "knit" button on complex Rmarkdown documents. Everything goes well until the final step, when I get an "Error: pandoc conversion failed with error 11."

Sometimes, adding `keep_md: true` fixes the problem. Sometimes, if `keep_md: true` is already there, then _removing_ it fixes the problem. Sometimes changing the theme or the highlight setting fixes the problem. Sometimes manually running `knitr::knit` and `rmarkdown::render` from the console works, even when pushing the "knit" button fails. Because I only run into this issue with large files (that depend on even larger data sets), I don't have a reproducible example to go along with a bug report.  So, I'm not currently reporting **that** bug (which may actually be in pandoc). Instead, here's the

**_Immediate Issue:_ If I add the line `keep_md: true` to the YAML header of an Rmarkdown file and pandoc fails, then the intermediate markdown file is not saved.**

Because of this (unexpected and undesirable)  behavior, it is impossible to use the intermediate markdown file to figure out which part of it might be triggering a pandoc error.

It appears that the order of operations behind the "knit" button is

1. Create a temp directory
2. Use knitr: knit to create the markdown file (and auxiliary files) in the temp directory.
3. Run pandoc via rmarkdown::render.
4. **If it succeeds**, copy everything back to the working directory.
5. Delete the temp directory and its contents.

Note that nothing gets saved if pandoc fails at step 4.  It should be easy to save the markdown file (either before or after trying to run pandoc) whenever "keep_md: true" is present. It is particularly irritating to first get a message that the markdown output file was successfully created, then see that pandoc failed, and then find no markdown file in the working directory.

**Comment by kevinushey** [comment]
You are likely seeing the same issue as https://github.com/rstudio/rstudio/issues/4072. If you're willing, we have a copy of Pandoc 2.7.1 built against GHC 8.6.4 that you may have better luck with:

```
# Download pandoc 2.7.1 built with ghc-8.6.4, and instruct
# RStudio + rmarkdown to use it.

local({
	
  # The directory where Pandoc will be extracted. Feel free
  # to adjust this path as appropriate.
  dir <- "~/rstudio-pandoc"
  
  # The version of Pandoc to be installed.
  version <- "2.7.1"
  
  # Create and move to the requested directory.
  dir.create(dir, showWarnings = FALSE, recursive = TRUE)
  owd <- setwd(dir)
  on.exit(setwd(owd), add = TRUE)
  
  # Construct path to pandoc.
  root <- "https://s3.amazonaws.com/rstudio-buildtools"
  suffix <- sprintf("pandoc-%s-windows-x86_64.zip", version)
  url <- file.path(root, "pandoc-rstudio", version, suffix)
  
  # Download and extract pandoc.
  file <- basename(url)
  utils::download.file(url, destfile = file)
  utils::unzip(file)
  unlink(file)
  
  # Write .Renviron to update the version of Pandoc used.
  entry <- paste("RSTUDIO_PANDOC", shQuote(path.expand(dir)), sep = " = ")
  contents <- if (file.exists("~/.Renviron")) readLines("~/.Renviron")
  filtered <- grep("^RSTUDIO_PANDOC", contents, value = TRUE, invert = TRUE)
  amended <- union(filtered, entry)
  writeLines(amended, "~/.Renviron")
  
  # Report change to the user.
  writeLines("Updated .Renviron:\n")
  writeLines(amended)
  writeLines("\nPlease restart RStudio for these changes to take effect.")
	
})
```

**Comment by krcoombes** [comment]
That may indeed be the root problem, and I'll try this fix; thanks. 
(Also unclear why searching the bug list failed to find this for me; 
sorry about that.)

But it still seems to me to be the case that  not saving an MD file that 
you have already produced, when the user asked for it, is a separate bug....
