### ISSUE TITLE
Filenames with non-ASCII characters get duplicated in tab list

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#4469]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1328
    OS Version      : Windows 10
    R Version       : 3.5.2

I have two files starting with "q" in my working directory: "qääääää.csv" and "q诶 ēi B 比 bǐ C 西.txt". When I try to link to them in my code via typing out the letter q and then pressing tab I get this:
![](https://i.imgur.com/XPcpgjp.png)

I guess this is two bugs in one:
1. Both filenames are duplicated
2. The Chinese one is displayed incorrectly both times.

Out of the 4 only "qääääää.csv" will be read, the other 3 "do not exist in the working directory". 

For what it's worth if I straight up run "read_csv("q诶 ēi B 比 bǐ C 西.txt")", I will get "Error: 'q<U+8BF6> ei B <U+6BD4> bi C <U+897F>.txt' does not exist in current working directory". But that and the second "bug" are probably(maybe) incorrect locale setting on my end?

**Comment by kevinushey** [comment]
Part of the issue here is simply that `list.files()` doesn't understand how to list files that contain multibyte characters, and we still use this in some places within the R completion engine.
