### ISSUE TITLE
'Unexpected format for source refs' error on finishing profiling

### ISSUE THREAD

**Issue by md0u80c9** [rstudio/rstudio#4474]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1327
    OS Version      :  10.14.4 Mac OS Mojave, Beta 6
    R Version       :  3.5.3
(profvis package version 0.3.5 from CRAN; also tested with latest version of profvis 0.3.5.9000 from RStudio/profvis with no change).

### Steps to reproduce the problem

Selected 'Start Profiling' from menu bar.
Profiled my code.
Clicked Stop.

### Describe the problem in detail

"Unexpected format for source refs" error appears in a dialog box at the top of the screen; a tab labelled 'profile1' is created but nothing rendered within it. Clicking OK on the error closes the tab.

### Describe the behavior you expected

Profiling diagram to display within Profile1.

**Comment by kevinushey** [comment]
Can you please provide a reproducible example?

**Comment by md0u80c9** [comment]
Hi,

How would I get a reproducible sample? I can reproduce it on my machine - do I need to make a file from the profiling instead?

**Comment by kevinushey** [comment]
Can you provide a bit of R code that, when profiled, gives the error you're describing? (Note that I wasn't able to reproduce with some simple testing)

Are you able to reproduce with a plain old `profvis::profvis(<your code here>)`?

**Comment by jmcphers** [comment]
Closing since we haven't heard from you in a couple of weeks (feel free to reopen if you have a reproducible example!)
