### ISSUE TITLE
Unicode symbols are not printed correctly in Build pane (on Windows with locale set other than EN)

### ISSUE THREAD

**Issue by vh-d** [rstudio/rstudio#4476]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1322
    OS Version      : Windows Server 2008 R2 x64 SP 1
    R Version       : 3.5.2

```
> sessioninfo::session_info()
- Session info ---------------------------------------------------------------------------------------
 setting  value                          
 version  R version 3.5.2 (2018-12-20)   
 os       Windows Server 2008 R2 x64 SP 1
 system   x86_64, mingw32                
 ui       RStudio                        
 language (EN)                           
 collate  Czech_Czech Republic.1250      
 ctype    Czech_Czech Republic.1250      
 tz       Europe/Prague                  
 date     2019-03-19   
```

I don't see this behaviour on my Linux machines.
### Steps to reproduce the problem
Build pane -> Build Source Package

### Describe the problem in detail

I get something like this

```
<U+221A>  checking for file 'C:\somepackage/DESCRIPTION' (2.6s)
<U+221A>  checking DESCRIPTION meta-information
```

### Describe the behavior you expected

I expect unicode 'square root' U+221A character printed as “√”.

**Comment by ronblum** [comment]
@vh-d Thank you for reporting this issue. Can you please provide a reproducible example so that we can try to replicate the issue?

**Comment by vh-d** [comment]
I experimented with changing locale and realized that changing windows settings to en-US solves the issue.

It's interesting that the issues only applies to Build-pane "console". The main R console does not have this problem, i.e. handles the locale settings correctly.

I have updated issue name and added more specific example how to reproduce the issue.

**Comment by ronblum** [comment]
@vh-d Thank you for doing the research and providing the details! I'll mark this as a bug.

**Comment by sfr** [comment]
@vh-d could you provide settings which works for you? Cause I have EN locale, and I tried few changes but unsuccessfully. _Console_ shows correct unicode characters, but _Build pane_ not.

```
> Sys.getlocale()
[1] "LC_COLLATE=English_Ireland.1252;LC_CTYPE=English_Ireland.1252;LC_MONETARY=English_Ireland.1252;LC_NUMERIC=C;LC_TIME=English_Ireland.1252"

> sessioninfo::session_info()
─ Session info ───────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Ireland.1252        
 ctype    English_Ireland.1252        
 tz       Europe/Prague               
 date     2019-12-12   
```

### Console output
```
✓  checking whether the namespace can be unloaded cleanly (720ms)
✓  checking loading without being on the library search path (678ms)
```

### Build pane output
```
<U+2713>  checking whether the namespace can be unloaded cleanly (718ms)
<U+2713>  checking loading without being on the library search path (686ms)
```

**Comment by vh-d** [comment]
@sfr  that's insteresting, switching my Windows session to EN/US before starting RStudio works for me as a workaround. I don't see why Irish locale should be different but maybe try US? I am on pretty old machine with Windows 2008 R2, haven't tested this on Win10 yet.

**Comment by jmcphers** [comment]
See https://github.com/rstudio/rstudio/issues/4567 for another likely instance of this issue.

**Comment by vh-d** [comment]
I have just checked RStusdio daily build (Version 1.4.1548) and the issue is still present.

**Comment by kevinushey** [comment]
I can reproduce as well if I force R to use a non-English locale during package build.

<img width="943" alt="Screen Shot 2021-02-05 at 3 38 31 PM" src="https://user-images.githubusercontent.com/1976582/107100100-35488f80-67c8-11eb-8d5d-cad0be56eb09.png">

**Comment by gaborcsardi** [comment]
Hmmm, I can't reproduce this, actually. For me cli does not use Unicode characters on the build pane on Windows. I tried cli 2.2.0 and 2.3.0.

**Comment by mbojan** [comment]
See also tidyverse/tidyverse#87 which was, I think, closed prematurely.

**Comment by gaborcsardi** [comment]
@mbojan That issue is about the console, this one is about the build pane.

**Comment by mbojan** [comment]
Ah, indeed. Sorry!

Still, perhaps there is a common mechanism? In the build pane, e.g. in `testthat` output, I'm seeing some symbols OK, but some other, including the mentioned tick mark as not OK, e.g. green `<U+221A>` but no tick mark, so identically as in the console.

**Comment by gaborcsardi** [comment]
OK, I could reproduce this finally. It should be fixed in cli, to be released soon: https://github.com/r-lib/cli/issues/216

**Comment by kevinushey** [comment]
Thanks @gaborcsardi!
