### ISSUE TITLE
Unable to scroll in help tab in rstudo.cloud

### ISSUE THREAD

**Issue by panchalpratik** [rstudio/rstudio#4477]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jmcphers** [comment]
Sorry, we'd need a lot more detail to help, and this bug tracker is not for rstudio.cloud issues. I'd suggest starting a thread describing your problem on the RStudio Cloud forum:

https://community.rstudio.com/c/rstudio-cloud
