### ISSUE TITLE
JavaScript exception thrown from Find in Files dialog

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#4478]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.1327-1
    OS Version      : macOS 10.14.3
    R Version       : 3.5.1

### Steps to reproduce the problem
- load a project into RStudio (required to repro the bug)
- bring up dev tools, sources, pause on caught exceptions
- Edit -> Find in Files...
- dialog displays, wait a few seconds

### Describe the problem in detail
- JavaScript exception thrown; happens every few seconds
- Keeps happening after you dismiss the Find in Files dialog

### Describe the behavior you expected
- No exceptions, without exception

Note, I also repro'd on 1.3 (where I first noticed it).

**Comment by gtritchie** [comment]
Looks like introduced via https://github.com/rstudio/rstudio/commit/468c41cd36431b16ae0c6b3b155e94243145d51c#diff-fd534b720e83ffa9ff478c434ab1c039

**Comment by kevinushey** [comment]
@gtritchie let me know if you want me to take a look since it looks like this is my code that regressed here.

**Comment by dfalty** [comment]
Verified fixed 1.2.1330-2
