### ISSUE TITLE
autocompletion error in Shiny application using `[[`, `$`

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4480]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1325
    OS Version      : macOS 10.14.3
    R Version       : 3.5.3

### Steps to reproduce the problem

Create a new Shiny web application with `ui.R` / `server.R` pairs. Within the `server.R`, insert the code:

```
`[[`()
```

Then, return to `ui.R`, and request completions somewhere.

### Describe the problem in detail

The following error is emitted in the console:

```
Error in object[[2]] : subscript out of bounds
```

### Describe the behavior you expected

No error.

**Comment by jmcphers** [comment]
This should have been auto-closed when #4481 hit master, but wasn't!
