### ISSUE TITLE
"Run Tests" should add to rather than replace the standard "Run", "Source" buttons

### ISSUE THREAD

**Issue by gorcha** [rstudio/rstudio#4483]
With the introduction of the "Run Tests" shortcuts, RStudio now replaces the standard "Run selection", "Run code region" and "Source" shortcuts in the top right of the source pane as soon as it picks up a `test_that()` call in a source file.

![image](https://user-images.githubusercontent.com/1212964/54657429-88a28d80-4b1d-11e9-95e9-abcaedb6840c.png)

![image](https://user-images.githubusercontent.com/1212964/54657404-6c065580-4b1d-11e9-81fa-773a79bc0056.png)

I and others I work with often use testing snippets in ad-hoc R scripts as a form of checking, so it would be great if the "Run Tests" shortcut was an addition to the run options instead of a replacement (particularly so the new "job" sourcing options are still available).

Thanks!

**Comment by jmcphers** [comment]
Realize this doesn't totally solve your problem, but if you open the *Jobs* tab and click "Start Local Job" it will default to running the currently open R script (so is functionally equivalent to "Source as Local Job)
