### ISSUE TITLE
Diagnostics message disappears under console

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#4484]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1327
    OS Version      : Windows 7
    R Version       : 3.5.3

### Steps to reproduce the problem
Create a script triggering a diagnostics message, e.g.
```a=0```
Save the script and resize the RStudio windows in such a way that the line triggering the message is the last visible line in the script.
Hover over the icon on the left of the screen before the code triggering the message.

### Describe the problem in detail
The diagnostics message is displayed below the console and only half visible.
![image](https://user-images.githubusercontent.com/28725410/54689684-4fb7e800-4b20-11e9-940b-9e8bc631be68.png)

### Describe the behavior you expected
A fully visible message.

**Comment by kevinushey** [comment]
Thank you for the reproducible example + screenshot illustrating the issue!
