### ISSUE TITLE
Safari - Installing Packages popup formatting incorrectly

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#4485]
### System details
    RStudio Edition : Server
    RStudio Version : 1.2.1329
    OS Version      : Mac / Safari 12.0.3
    R Version       : 3.3.3

### Steps to reproduce the problem
1. Use Safari browser to connect to RStudio Server 
2. Uninstall rmarkdown package if you have it installed
3. Create Rmd. File->New File->R Markdown
4. Select Yes at Install Required Packages pop up
5. Observe Stop button and loading bar are pushed to the right and causing blank space

### Describe the problem in detail
![image](https://user-images.githubusercontent.com/15237845/54692983-defad680-4af3-11e9-8832-885f0a195fca.png)

**Comment by gtritchie** [comment]
Same dialog (ConsoleProcessDialog) is still used in other places such as changing branches in Git. So yes still repros and is fixed by the PR.
