### ISSUE TITLE
Allow rstudioapi to work inside child R sessions

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4490]
Currently, rstudioapi does not work inside child R sessions -- jobs, R markdown renders, etc. This is because all of the functions it calls exist only in the parent R session.

It would be very useful to be able to invoke rstudioapi functions inside child R sessions. For example, we could use them:

- for knitr to report knit progress from its child R session
- for RStudio jobs to orchestrate actions in the parent R session (e.g. open a tab with results when complete)
- for [learnr](https://rstudio.github.io/learnr/) and other Shiny-based apps to drive the IDE without blocking the R console 
- and probably lots of other scenarios

This could take the form of exposing the whole API generically with some kind of mechanism that marshals function arguments and return values, or creating a subset of the API specifically intended for child processes with different signatures/semantics.

**Comment by garrettgman** [comment]
This feature request is an important component of the plan we came up with on 5/22/19 to make an IDE friendly tutorial format.

**Comment by kevinushey** [comment]
This has now been implemented -- `rstudioapi` functions, when executed within R child processes launched by RStudio, should now work and communicate back through the main RStudio session.

**Comment by schloerke** [comment]
Wow! Thank you!

**Comment by tmcduff** [comment]
Version 1.3.749

**Comment by AshesITR** [comment]
Is there any way to use this within a `future`?
Apparently, those processes aren't spawned as child processes.

Setting up a different future plan which does spawn child processes would be fine with me as well.

``` r
library(future)
plan(multisession)
value(future(rstudioapi::isAvailable()))
#> [1] FALSE
value(future(rstudioapi::isAvailable(child_ok = TRUE)))
#> [1] FALSE
```

(running on windows)

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kevinushey** [comment]
No, unfortunately this isn't yet possible -- this is only for child processes normally launched by RStudio, not arbitrary child processes from R or R packages.
