### ISSUE TITLE
Cursor disappears from one terminal when some processes are killed in another terminal

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4492]
\### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1329-3
    OS Version      : SLES 12 SP3 and Red Hat 7.6
    R Version       : 3.5.3

### Steps to reproduce the problem

1. Open a new terminal: Tools -> Terminal -> New Terminal
2. Run `top`
3. Open another terminal: Tools -> Terminal -> New Terminal
4. `ps -ef | grep top`
    - The process should be listed for `top`, which contains the process id for the steps below.
5. Kill the `top` commands, e.g. if the process id is 1138, `kill -9 1138`.
6. `ps -ef | grep top`
    - The `top` process should be gone.
7. Go back to the first terminal
    - The `top` process should be done running, showing the last iteration and the command line.
    - The flashing cursor is gone, but commands can still be issued.

### Describe the problem in detail

The cursor disappears from the command line.

### Describe the behavior you expected

The cursor should remain on the command line. This works with no problem with, say, `sleep` and `tmux`.

**Comment by gtritchie** [comment]
Still repros with xterm3, build 1.3.429.
