### ISSUE TITLE
Missing libssl dependency on debian

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4493]
RStudio seems to depend on `libssl.so.1.0.2` (or at least fails to start because of it), but this specific version (which is a separate package in debian) is not a requirement in the `.deb` file from the preview release for debian.

**Comment by jmcphers** [comment]
Sorry, we can't reproduce this. Can you be more specific?

- What exact version of RStudio did you see this on?
- What exact version of Debian are you using?
- What is the output of `ldd` on the `rstudio` binary you are invoking?

**Comment by david-cortes** [comment]
Hmm, it seems it does depend on `libssl1.0.2` (at least the latest preview, according to `dpkg -I` on the deb file and `ldd` on the executable), but somehow `apt-get` failed to install it when I installed the RStudio deb file.
