### ISSUE TITLE
Rstudio kills terminals when using Session -> Terminate R

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4494]
I expected the terminals to be left alone after "Terminate R" runs. I only expect the R session in the console to get terminated.

**Comment by jmcphers** [comment]
This happens because the the terminals are child processes of the R session, not child processes of RStudio. We're hoping to change this in a future release, and are tracking the issue in https://github.com/rstudio/rstudio/issues/2059 (feel free to comment/upvote!)
