### ISSUE TITLE
Display folders & subfolders at once in Files-tab

### ISSUE THREAD

**Issue by Iuiu1234** [rstudio/rstudio#4495]
In RSudio's Files tab,
Is there the option to display folders & subfolders at once like (almost all) other ID's? (like [pycharm](https://d3nmt5vlzunoa1.cloudfront.net/pycharm/files/2015/03/flask1.png) )
So files show in the following way

\> Folder 1
.. File 1
.. File 2
..\> SubFolder 1
.... File 1.1
.... File 1.2
\> Folder 2

And you can expand or compress the  Folders with the '>' button.

thx

Rstudio 1.2

**Comment by jmcphers** [comment]
No, you can't do this right now. We're tracking the request in https://github.com/rstudio/rstudio/issues/2552 (feel free to comment/upvote!)
