### ISSUE TITLE
Injection Point to Override RStudio Hooks

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#4498]
I would like to be able to add a custom hook within [hooking architecture /  `"tools:rstudio"`](https://github.com/rstudio/rstudio/blob/1d7e3466cc70416c68dca93a363811e222a4acfe/src/cpp/r/R/Tools.R#L412-L477)  that RStudio sets. I'm specifically making this request to obtain access to the `install.packages()` hook established after the R session was fully established. c.f.

https://github.com/rstudio/rstudio/blob/6c72909b58ca175be18c55214c22fcc04b64a1eb/src/cpp/session/modules/SessionPackages.R#L120-L124

The present hook produces: 

```r
get('install.packages', 'package:utils')
# function (...) 
# .rs.callAs(name, hook, original, ...)
# <environment: 0x7f92d7069ce8>
```

After testing different options, all of RStudio's hooks seem to be established after _R_'s own startup procedure that runs through  `.Renviron`, `.Rprofile`, and `.Rhistory`. As a result, there isn't a way to mask code or load a package automatically that won't be overridden by _RStudio_ claimed functions.

It would be helpful to have an injection point after the initial delayed registration.

https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/cpp/r/session/RInit.cpp#L318-L321

The use case for the injection is:

- Disabling communication with CRAN/Global CDNs for secure environments
- Better user feedback as it now silently errors or triggers a full error when a bogus CRAN path is specified.
- Similar behavior to launching _R_ from Terminal or  GUI.
- Some kind of environmental [disable package installation feature option](https://support.rstudio.com/hc/en-us/articles/210990438-Disabling-RStudio-Features) (instead of removing the package panel).

_Desired behavior_
![r-build-fine](https://user-images.githubusercontent.com/833642/54857189-f8ef1180-4ccb-11e9-8989-04ffa467f0ac.png)

_Slient error without overriding CRAN mirror_

![rstudio-hook-install-pkg-delay](https://user-images.githubusercontent.com/833642/54856941-d6a8c400-4cca-11e9-933d-ae1c7ac76369.gif)

_Noisy error without masked function call when overriding with a bogus CRAN mirror_

![bogus-cran-mirror](https://user-images.githubusercontent.com/833642/54857142-cc3afa00-4ccb-11e9-8ec9-51c82c9a1717.png)

To recreate the mask shown desired, I've created a **`.Rprofile`** file that contains:

```r
.First = function() {
    ## Place package on search path
    library("utils")
    
    ## Unlock environment where the function/variable is found.
    unlockBinding("install.packages", as.environment("package:utils"))
    
    ## Intercept install packages with a custom function.
    base::assign("install.packages",
                 value = function(...) { cat("Done!\n")},
                 envir = as.environment("package:utils"))
    
    ## Close the environment
    lockBinding("install.packages", as.environment("package:utils"))
}
```

**Comment by jmcphers** [comment]
> It would be helpful to have an injection point after the initial delayed registration.

We agree. We're tracking the enhancement here:

https://github.com/rstudio/rstudio/issues/1579

I think what we're proposing there will address your use case, so I'm closing this one for now.
