### ISSUE TITLE
An empty console window with crashpad_handler.com opens with RStudio

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#4499]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.66
    OS Version      : Windows 10
    R Version       : 3.5.3

This is what it looks like:
![](https://i.imgur.com/McX8gog.png)

Not much more to say really. The window appears right away when opening RStudio. Actually it appears a tick before the RStudio window.

**Comment by ronblum** [comment]
@martj42 Thank you for reporting the issue. As you know, RStudio 1.3 is in the early stages of development and meant only for testing purposes, so we appreciate you taking the time to both try it out and provide feedback on issues you run into!

Note: the 1.2 preview candidate is available here: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by kfeinauer** [comment]
@ronblum are you able to reproduce?

This crashpad handler that is popping up is the automated crash dump collection service that is new in 1.3, but you shouldn't actually see a window for the process (it should be invisible). Will try to see if we can reproduce on our side, but so far I have not run into this.

**Comment by ronblum** [comment]
@kfeinauer I haven't tried it yet since I'm working on the last stages of 1.2 testing. I'll try it out once that's complete. On the plus side, it's not an issue in 1.2!

**Comment by byzheng** [comment]
I have the same issue with the the system above.

**Comment by ronblum** [comment]
@byzheng Do you mean that you're seeing the problem with the RStudio 1.2 preview?

**Comment by byzheng** [comment]
@ronblum NO

This is my system information
RStudio Edition : Desktop
RStudio Version : 1.3.66
OS Version      : Windows 10
R Version       : 3.5.3

**Comment by kfeinauer** [comment]
@ronblum The Crashpad integration feature is new in 1.3.
