### ISSUE TITLE
Global option "Editor Font" is not saved, on Linux Mint 19 Xfce

### ISSUE THREAD

**Issue by oscardelama** [rstudio/rstudio#4500]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1330
    OS Version      :  Linux Mint 19.1 Tessa, Xfce
    R Version       :  3.5.3 (2019-03-11) -- "Great Truth"

### Steps to reproduce the problem

After a fresh installation go to menu Tools/Global Options and there change "Editor font" (from the default "Ubuntu Mono") to "DejaVu Sans Mono" then you see the editor font has in fact changed as desired. Restart Rstudio and you will get the original default font "Ubuntu Mono" in the editor. This happens with any font you choose and happens also in RStudio 1.1.

**Comment by ronblum** [comment]
@oscardelama Thank you for reporting the issue! I'm unable to reproduce this on Ubuntu 18.04 (Bionic) from which Mint 19.1 is derived. However, I'll mark this as a bug to be reviewed as we continue development of RStudio.

**Comment by oscardelama** [comment]
Hi, thanks for the fast response.

I work with RStudio on a daily basis in a fresh installation of Linux (feb 4) and I can see this issue every day. I thing this issue is related to having the Xfce type of interface. 

Another issue is that the very first change in Editor font or its size (after just starting the app), pops up a confirmation window about "Restart Required... Do you want to do this now?" and it doesn't matter if you answer yes or no. The change is made anyway.

As changing the font name every single time I start RStudio is becoming annoying. I have taken a look to "/home/oscar/.rstudio-desktop/monitored/user-settings/user-settings"  and there I can see an entry uiPrefs containing "font_size_points\" : 10, which -as expected- changes whenever I change the editor font size, but there is no entry holding the font name. Indeed "font_size_points" is the only item with the "font" word in its name in the whole file. If you can tell me which one is the entry name for the editor font name (to set it manually) I will thank you a lot.

**Comment by hattesoul** [comment]
### System details

```
RStudio edition: Desktop
RStudio version: 1.2.5033
OS version     : Ubuntu 18.04.4 LTS Bioinc Beaver
R version      : 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
```

Now, I have the same problem. _Everything_ worked just fine for months: all settings -- including the editor font -- were saved properly...
**UNTIL**
I once executed

> sudo rstudio

to update a package, that threw an error otherwise. Since then, the editor font resets to the default font every time I restart RStudio (with or without sudo), the font size or editor theme does not reset. Also the window position (maximized) is not saved anymore.

**Comment by kevinushey** [comment]
@hattesoul thanks for the extra information. I've filed a separate bug based on this. You should be able to recover if you reset permissions on the `~/.rstudio-desktop` folder; e.g.

```
sudo chown "$(whoami)" -R ~/.rstudio-desktop
```

**Comment by hattesoul** [comment]
Thank you @kevinushey for the instructions. I already restored my permissions and unfortunately, it did not fix the problem: the editor font (and window position) resets to default on every `rstudio` start.
Right now, it is just an inconvenience, no big deal.
