### ISSUE TITLE
RMarkdown function definitions execute line-by-line

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#4503]
Latest preview (1.2.1330-2):

- Define the following function in an Rmd chunk:
```r
function(){
  "blahblahblah1"
  "blahblahblah2"
  "blahblahblah3"
  "blahblahblah4"
  "blahblahblah5"
  "blahblahblah6"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah"
  "blahblahblah2"
  "blahblahblah4"
  "blahblahblah6"
}
```
- `CTRL + Enter` to execute it
- scroll through the history buffer to recognize it was executed line-by-line
- if you copy and paste into the R console, R treats it as a "chunk"

I think the "chunk" behavior is preferable. The line-by-line approach is slow and destroys your history buffer for long objects.

**Comment by ronblum** [comment]
@colearendt I think this was discussed a while back, but I can't find an issue or other conversation about it, so I'll mark it as an enhancement for now.

**Comment by jmcphers** [comment]
We are tracking this in https://github.com/rstudio/rstudio/issues/3520.

**Comment by pqmatagi** [comment]
Any update on this "enhancement" (it's just a bug to me)? As the OP notes, this is a PITA when working in the console with code fragments from a .Rmd doc. I can't imagine any user actually preferring this behavior in the history, and to me it's a huge usability problem, much as I like the literate programming benefits of R Markdown.

**Comment by kevinushey** [comment]
@pqmatagi I've re-opened the associated issue at https://github.com/rstudio/rstudio/issues/3520.
