### ISSUE TITLE
404 loading theme-textmate.js when opening Options dialog

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#4504]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.75-1 (Redhat build)
    OS Version      : CentOS 7
    R Version       : 3.5.2

### Steps to reproduce the problem

- reset settings via `rm -rf ~/.rstudio`
- install RStudio server
- show dev console in Chrome then load RStudio
- Tools / Global Options

### Describe the problem in detail
- Error in JavaScript console:
```
GET http://localhost:8787/ace/theme-textmate.js net::ERR_ABORTED 404 (Not Found)
```

### Describe the behavior you expected
- No error in console

### Other Info
- Also happens with dev server build

**Comment by jmcphers** [comment]
Not for 1.3 since this is pretty harmless.
