### ISSUE TITLE
better handle case where user lacks read/write permissions in ~/.rstudio

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4505]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1330
    OS Version      : macOS 10.14.3
    R Version       : 3.5.3

### Steps to reproduce the problem

Run the following in your shell:

```sh
sudo chown -R root ~/.rstudio-desktop
```

Then, try launching RStudio.

### Describe the problem in detail

Depending on what files / folders within are inaccessible, different errors can occur. In this particular case, RStudio can (if no project is opened) fail to launch, or (if a project is open) fail to close that project.

### Describe the behavior you expected

Some possibilities:

1. RStudio could attempt to repair permissions on these folders during launch if possible;
2. RStudio could notify the user if it lacks read / write permissions into the state folder.

### Notes

Prompted by https://github.com/rstudio/rstudio/issues/4501, but other incantations of this issue have been reported in the past. I think this occurs most commonly when e.g. the user's home directory is mounted as a networked filesystem (especially on Windows) but mapping of Windows <-> Unix permissions is incomplete.

**Comment by kevinushey** [comment]
Note: similar arguments can be made for permissions on the `.Rproj.user `folder.

**Comment by kevinushey** [comment]
https://community.rstudio.com/t/starting-r-studio-after-installation-on-macos/27036/2

**Comment by kevinushey** [comment]
Marking v1.4 as questions related to "why aren't my preferences being saved?" remains a common question. Note that this often happens when one runs `rstudio` as root; e.g.

```
sudo rstudio
```

as the config files are still written to the user's file location, but are then written with root permissions (and so cannot be updated by the regular user's account)

**Comment by kfeinauer** [comment]
@MariaSemple Added testing notes to PR (by accident): https://github.com/rstudio/rstudio/pull/7742#issuecomment-713659830

Are you seeing the same behavior?

**Comment by kfeinauer** [comment]
After Maria's latest fixes, this appears to be fixed as expected on 1.4.990
