### ISSUE TITLE
No color in editor/console panes

### ISSUE THREAD

**Issue by lepennec** [rstudio/rstudio#4509]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1330
    OS Version      :  Fedora 29
    R Version       :  3.5.3

### Steps to reproduce the problem

Open RStudio open a file or use the console

### Describe the problem in detail

Since the latest RSudio preview (1.2.1330), I do not have any color in the editor or in the console as shown in the screenshot
![Screenshot from 2019-03-26 08-35-16](https://user-images.githubusercontent.com/7868905/54979141-ae5ae700-4fa2-11e9-932e-c4bae1e32930.png)

### Describe the behavior you expected

The colors were there in the previous versions.

Here is my diagnostics-report:
[diagnostics-report.txt.gz](https://github.com/rstudio/rstudio/files/3006990/diagnostics-report.txt.gz)
 attached.

Thanks!

**Comment by kevinushey** [comment]
Thanks; this is a known issue: https://github.com/rstudio/rstudio/issues/4488

You can fix this by changing the editor theme and then changing back to the desired theme.
