### ISSUE TITLE
window.location is undefined in viewer

### ISSUE THREAD

**Issue by vetedde** [rstudio/rstudio#4510]
I need get query parameter in viewer pane, but when i try console.log(window.location), I get next
`
Location: {`
` ancestorOrigins: undefined, `
 `constructor: undefined,`
` hash: undefined,`
 `host: undefined,`
 `hostname: undefined,`
 `href: undefined,`
 `origin: undefined,`
` pathname: undefined,`
` port: undefined,`
 `protocol: undefined,`
` search: undefined,`
` __proto__: LocationPrototype`
`}`
 

How get url inside viewer pane?

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!

**Comment by vetedde** [comment]
> Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself.
> 
> Please visit our community site to ask questions:
> 
> https://community.rstudio.com/
> 
> Hope you're able to find what you're looking for!

Thank you for your answer, but I think, that it's bug, because viewer pane does not normally work
