### ISSUE TITLE
update pandoc

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4512]
Placeholder issue for us to consider updating Pandoc across the board for the v1.3 release.

**Comment by dfalty** [comment]
Looks like to `flextable` requires >=2.4 for the ability to knit powerpoint. https://cran.r-project.org/web/packages/flextable/vignettes/overview.html#pandoc-versions

Came from a community post regarding rstudio.cloud.
https://community.rstudio.com/t/updating-pandoc-version-using-webshot-to-render-to-ppt-in-rstudio-cloud/42690/2
