### ISSUE TITLE
UI freezes when restarting R or clicking on the stop sign when reticulating raw_input

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4513]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : RStudio Desktop & Server 1.2.1330
    OS Version      : MacOS 10.4.4 beta, RedHat 7.6, SLES 12 SP3
    R Version       : 3.5.x

### Steps to reproduce the problem

In the console, with `reticulate` installed:
1. `reticulate::repl_python()`
2. `name = raw_input('What is your name?\n')`

### Describe the problem in detail

The output begins correctly, leading up to the request for user input. However, entering text and clicking Return/Enter does nothing, except for creating a new line. Click Return/Enter on with no text does not exit.

In addition, the code or R session can't be killed from the stop sign, "Restart R," and quit-session button on the upper right, and if attempted, it will be impossible to use the UI. In this scenario, the only way out is to use go to `.../home` in RStudio Server or kill and restart RStudio Desktop. (Note: "Terminate R" works.)

```
> reticulate::repl_python() 
Python 2.7.5 (/usr/bin/python) 
Reticulate 1.10 REPL -- A Python interpreter in R. 
>>> name = raw_input('What is your name?\n') 
What is your name?
Ron
Ron
Really, Ron
```

### Describe the behavior you expected

Input via Python is not currently supported. However, it would be better if R could be safely terminated via these options, similar to the behavior of "Terminate R."

**Comment by kevinushey** [comment]
Looks like this technically works when with R + reticulate in a terminal, which surprised me a little. So this would need to be fixed specifically in the RStudio bindings to reticulate.

I think the simplest fix would be to override the `raw_input()` and `input()` functions to instead use R's own `readline()` implementation.

**Comment by ronblum** [comment]
Note: this is only an issue on Linux and MacOS. On Windows, an error is thrown instead,
```EOFError: EOF when reading a line```
and both Python/reticulate and RStudio continue to run.
