### ISSUE TITLE
RStudio 1.2.1330 - Fails to render screen on Mojave 10.14 with external GPU

### ISSUE THREAD

**Issue by Technophobe01** [rstudio/rstudio#4515]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : 10.14.4 Beta (18E220a)
    R Version       : R version 3.5.3 (2019-03-11) -- "Great Truth"

### Steps to reproduce the problem
Enable External ([supported](https://support.apple.com/en-us/HT208544)) EGPU 
Download Preview version and Install
Invoke Rstudio 1.2.1330

### Describe the problem in detail
When running with Mojave with an external EGPU Rstudio 1.2.1330 fails to render the screen components. RStudio Version 1.1.463 works as expected.

This may be associated with the QT version being used? Why? If I run RStudio with 

`RSTUDIO_CHROMIUM_ARGUMENTS="--disable-gpu" open ./RStudio.app`

the application launches and display windows.

Note: This may potentially be related to a closed bug: https://github.com/rstudio/rstudio/issues/4445

### Describe the behaviour you expected
I would expect RStudio to display the appropriate windows.

#### Error Case:
Rstudio 1.2.1330 with EGPU AMD Radeon WX 1900 in EGX EGPU Case
![image](https://user-images.githubusercontent.com/749230/55013690-dcdac100-4fa6-11e9-8ed6-19ac6d7f0f5d.png)

#### Normal Behavior:
Rstudio 1.1.463
![image](https://user-images.githubusercontent.com/749230/55013786-11e71380-4fa7-11e9-8bc3-ce487e792956.png)

**Comment by kevinushey** [comment]
Can you also share the output of running:

```
/usr/sbin/system_profiler SPDisplaysDataType
```

in the console?

**Comment by Technophobe01** [comment]
/usr/sbin/system_profiler SPDisplaysDataType                              [2.6.0]
Graphics/Displays:

    Intel UHD Graphics 630:

      Chipset Model: Intel UHD Graphics 630
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x3e9b
      Revision ID: 0x0000
      Automatic Graphics Switching: Supported
      gMux Version: 5.0.0
      Metal: Supported, feature set macOS GPUFamily2 v1

    Radeon Pro 560X:

      Chipset Model: Radeon Pro 560X
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x8
      VRAM (Total): 4 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67ef
      Revision ID: 0x00c2
      ROM Revision: 113-C980AL-075
      VBIOS Version: 113-C97501U-005
      EFI Driver Version: 01.01.075
      Automatic Graphics Switching: Supported
      gMux Version: 5.0.0
      Metal: Supported, feature set macOS GPUFamily2 v1

    Radeon Pro WX 9100:

      Chipset Model: Radeon Pro WX 9100
      Type: External GPU
      Bus: PCIe
      PCIe Lane Width: x16
      VRAM (Total): 16 GB
      Vendor: AMD (0x1002)
      Device ID: 0x6861
      Revision ID: 0x0000
      Automatic Graphics Switching: Supported
      gMux Version: 5.0.0
      Metal: Supported, feature set macOS GPUFamily2 v1
      Displays:
        LED Cinema Display:
          Display Type: LCD
          Resolution: 2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
          UI Looks like: 2560 x 1440
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Display Serial Number: 2A0372DX6JL
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
          Connection Type: DisplayPort
        LED Cinema Display:
          Display Type: LCD
          Resolution: 2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
          UI Looks like: 2560 x 1440
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Display Serial Number: 2A0353GG6JL
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
          Connection Type: DisplayPort

**Comment by dyerlab** [comment]
I am also experiencing this bug.  On laptop, RStudio works just fine, when plugged into eGPU, it gives me the blank window.  

`
eGPU: Blackmagic Design eGPU
RStudio Version: 1.2.1335 (Desktop)
MacOS Version: 10.14.5 beta (18F108f)
`

And the system profiler output is:

`
Rodneys-MacBook-Pro-2:~ rodney$ /usr/sbin/system_profiler SPDisplaysDataType
Graphics/Displays:

    Intel HD Graphics 630:

      Chipset Model: Intel HD Graphics 630
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x591b
      Revision ID: 0x0004
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.29 [3.2.8]
      Metal: Supported, feature set macOS GPUFamily2 v1

    Radeon Pro 560:

      Chipset Model: Radeon Pro 560
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x8
      VRAM (Total): 4 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67ef
      Revision ID: 0x00c0
      ROM Revision: 113-C980AJ-927
      VBIOS Version: 113-C9801AU-A02
      EFI Driver Version: 01.A0.927
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.29 [3.2.8]
      Metal: Supported, feature set macOS GPUFamily2 v1

    Radeon Pro 580:

      Chipset Model: Radeon Pro 580
      Type: External GPU
      Bus: PCIe
      PCIe Lane Width: x4
      VRAM (Total): 8 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67df
      Revision ID: 0x00c0
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.29 [3.2.8]
      Metal: Supported, feature set macOS GPUFamily2 v1
      Displays:
        DELL U3415W:
          Resolution: 3440 x 1440 (UWQHD - Ultra-Wide Quad HD)
          UI Looks like: 3440 x 1440 @ 60 Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Display Serial Number: PXF797CN0UDL
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
`

**Comment by dyerlab** [comment]
OK, there is apparently a work around for this.  I have a 15" powerbook connected through a Blackmagic eGPU (specs above) connected to a 32" monitor.  If you start RStudio and it opens on the monitor (e.g., through the eGPU), you get the blank screen as above.  However, if you have the laptop display open, you can launch RStudio to start on that display and it will work properly.  You can then drag it over to the monitor and even shut the laptop and everything works fine.  

Hope this helps.

**Comment by Technophobe01** [comment]
> OK, there is apparently a work around for this. I have a 15" powerbook connected through a Blackmagic eGPU (specs above) connected to a 32" monitor. If you start RStudio and it opens on the monitor (e.g., through the eGPU), you get the blank screen as above. However, if you have the laptop display open, you can launch RStudio to start on that display and it will work properly. You can then drag it over to the monitor and even shut the laptop and everything works fine.
> 
> Hope this helps.

Unfortunately, I do not have the MacBook Pro display open. I use two external Monitors.

**Comment by ktaranov** [comment]
Same issue on Windows 7 Desktop machine:

![image](https://user-images.githubusercontent.com/6460726/60027834-e60f2300-96a6-11e9-8c10-11d5af498c38.png)

Version `RStudio-1.1.463` works fine. 2 monitors installed but this issue repeats on workspaces with one monitor too.

**Comment by Technophobe01** [comment]
Workaround: Max OS X Mojave / RStudio Version 1.2.1555

I was able to work around the issue of a blank screen by setting RStudio to "Prefer the EGU" using the following steps.

1. Select "Get Info" on the RStudio.app file
2. Select "Prefer the EGU"
3. Start application

![image](https://user-images.githubusercontent.com/749230/60400316-e6843f80-9b26-11e9-986f-66dbc4806fa2.png)

Result: RStudio correctly displays on external Monitors.

Configuration
Mac Book Pro 2018 connected via external WX 9100 to two Apple Displays via display port connectors.

**Comment by Technophobe01** [comment]
> Same issue on Windows 7 Desktop machine:
> 
> ![image](https://user-images.githubusercontent.com/6460726/60027834-e60f2300-96a6-11e9-8c10-11d5af498c38.png)
> 
> Version `RStudio-1.1.463` works fine. 2 monitors installed but this issue repeats on workspaces with one monitor too.
