### ISSUE TITLE
RStudio release binaries for Linux have "-relwithdebinfo" filenames

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4516]
All of the Linux releases for RStudio 1.3 have an unnecessary `-relwithdebinfo` as part of their filenames. See e.g. dailies.rstudio.com:

![image](https://user-images.githubusercontent.com/470418/55021515-19fa7f80-4fb6-11e9-92be-3948e6a0e6a0.png)
...

![image](https://user-images.githubusercontent.com/470418/55021501-1109ae00-4fb6-11e9-870d-1b2772b7404d.png)

This changed in https://github.com/rstudio/rstudio/commit/2dadca3899344072160a2e62c2762adec6f68daf; the fix may be as simple as renaming the file after CMake produces it (unless there is a mechanism by which we can tell CMake not to add the extension).

**Comment by kfeinauer** [comment]
Fixed in https://github.com/rstudio/rstudio/commit/caa4cb3d07b8764e3108b7768c73da7a7d4b2a89 and https://github.com/rstudio/rstudio/commit/1d8e57799ee04e3080ec7af1990c309599b35f9a
