### ISSUE TITLE
consider upgrade to latest Qt 5.12.x release

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4519]
Qt 5.12.2 is now available, and there will likely be another LTS release by the time we want to release v1.3.

Upgrading Qt is usually a headache but filing this so we at least weigh the decision -- although it's unlikely we'll want to do anything unless we find a bug that is indeed fixed in a newer patch release.

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio/pull/5399.
