### ISSUE TITLE
Bugged Shiny Viewer State after Viewpoint Switch

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#4522]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1206
    OS Version      : Ubuntu 16.04.5 LTS
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Launch a Shiny Application
1. Switch viewer mode while application is running
1. Reload the application.
1. Stop the application from either the console or viewer panel.
1. Enter state when "Reload App" doesn't switch to "Run App"
1. Press "Reload App" several times to no avail.

![shiny-state-bug-clicks](https://user-images.githubusercontent.com/833642/55054866-3d154580-502f-11e9-9168-1c99b616b309.gif)

### Describe the problem in detail

When a Shiny app is running, we will see a `Reload App` in place of `Run App` complete with a `Stop` button on the console and in the Viewer window.

<img width="500" alt="shiny-okay-run-state" src="https://user-images.githubusercontent.com/833642/55053770-3c7ab000-502b-11e9-9868-0153f1f5df81.png">

When exiting the Shiny app, we want the state to return to:

<img width="480" alt="shiny-okay-initial-state" src="https://user-images.githubusercontent.com/833642/55054026-45b84c80-502c-11e9-8946-a7f36af1985c.png">

If a Shiny app doesn't exit the state correctly, then the `Reload App` button sticks around without the `Stop` buttons.

<img width="512" alt="shiny-restart-state-bugged" src="https://user-images.githubusercontent.com/833642/55053785-4b616280-502b-11e9-8aa0-b66af1cc69a2.png">

To fix the mode, we'll need to change where the Shiny app is being viewed.

<img width="278" alt="shiny-switch-viewer-state" src="https://user-images.githubusercontent.com/833642/55054151-bbbcb380-502c-11e9-9172-152f2065f890.png">

Note, when we switch to the new mode, notice there is a "Connection Refused" portion.

<img width="577" alt="shiny-switch-run-type-state" src="https://user-images.githubusercontent.com/833642/55053964-11dd2700-502c-11e9-9f79-cb191ca91cd2.png">

In the Viewer panel, select the "Remove current viewer item" given by the red X on the document to reset the state.

<img width="292" alt="shiny-remove-last-viewed-state" src="https://user-images.githubusercontent.com/833642/55054254-308fed80-502d-11e9-9802-8e1f5b0aed60.png">

This should reset the state back to:

<img width="480" alt="shiny-okay-initial-state" src="https://user-images.githubusercontent.com/833642/55054026-45b84c80-502c-11e9-8946-a7f36af1985c.png">

### Describe the behavior you expected

The "Reload App" button switching back to "Run App" regardless of whether the viewer window changed.

**Comment by ronblum** [comment]
@coatless I'm unable to reproduce this issue, but I ran into #4527 while trying to reproduce it on the most recent preview release. Would you be willing to try out [the latest preview](https://www.rstudio.com/products/rstudio/download/preview/) and see if the issue you've run into goes away—though, at the risk of getting replaced by the new one?

**Comment by jmcphers** [comment]
We haven't heard from you and can't reproduce the issue, so we're closing this for now. 

If you're able to reproduce consistently, could you reopen with more details here:

> If a Shiny app doesn't exit the state correctly

Specifically, can you provide an example of an app that does not exit the state correctly?

**Comment by sanjmeh** [comment]
The issue still exists. And I think it was well explained by @coatless.
It happens every single time on my ubuntu server on aws. 
I always get `Connection refused` when I go the route of `reload app`. And everytime I use a `run in a new window` and kill the app the `reload app` button comes. It is a repeatable thing.

**Comment by kevinushey** [comment]
The issue here is likely browser-dependent, and may be fixed in the latest [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

Can you confirm that the issue reproduces there? If so, can you also share what browser you're using?
