### ISSUE TITLE
erratic screen behavior in 1.3.74 o Mac

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#4523]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.74
    OS Version      : n 10.14.4
    R Version       : 3.5.3

### Describe the problem in detail

When running a code chunk interactively (Alt-Cmd-C or Shft-Cmr-Ret) ,
the line numbers to the left of the code and the green bars indicating which code is being run
have interspersed spaces.
Catching a screenshot ist hard, but the same pattern occurrs when the code has a error, and then the red bars to the left of the code have a similar pattern.

![2019-03-27_00-10-19](https://user-images.githubusercontent.com/157619/55074289-34a12700-5090-11e9-94cf-00f901a41dfd.png)

**Comment by jmcphers** [comment]
This is already being tracked in https://github.com/rstudio/rstudio/issues/4257. We don't recommend the 1.3 builds for daily work; please use the previews for that: https://www.rstudio.com/products/rstudio/download/preview/
