### ISSUE TITLE
start path autocompletion from project root or working directory

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rstudio#4526]
I love using the path autocomplete feature in RStudio; makes life much easier.

I sometimes run into an issue, where I am working in a file that is *not* at the project root or the working directory (usually the same), but some subdirectory (say `project/scripts`).
If I source these scripts from the working directory (~ project root), as I usually would, I'd like any paths in `project/scripts/foo.r` to be *relative* from the working directory (or project root).

Currently, AFAIK, RStudio path autocompletion always begins from the path of the currently opened *file*, though this isn't what I usually want.

<img width="377" alt="Screenshot 2019-03-27 at 18 47 12" src="https://user-images.githubusercontent.com/5372770/55100246-b5c4e200-50c1-11e9-83cf-f503935e3fba.png">

**So I was wondering whether always starting path autocompletion from the current working directory would make sense.**
This appears to be the current behavior for path autocompletion in the console already.

**Comment by maxheld83** [comment]
I understand that this can get complicated quickly, because sometimes paths *have* to be from other roots for specific kinds of files (for example `pkg/vignettes`), so "working directory" may not be such a great default for all use cases.

**Comment by kevinushey** [comment]
RStudio's autocompletion in R Markdown document attempts to respect the Knit Directory preference:

![Screen Shot 2019-03-27 at 10 55 57 AM](https://user-images.githubusercontent.com/1976582/55100359-ef282e00-507e-11e9-81e8-2d10bc653898.png)

It defaults to the project directory, but you can change it as appropriate.

**Comment by ronblum** [comment]
@maxheld83 I'm closing this in the spirit of "working as expected," but please feel free to reopen if either you're seeing a bug, or you'd like to expand this into an enhancement request. Thanks!

**Comment by dleopold** [comment]
This feature does not work as described for me. If I am editing a R Markdown document located in a project subfolder (eg, `project/code/`) the Rstudio autocomplete for file paths is always relative to the folder where the markdown document is saved, not the project directory. This behavior does not change when I set the knit directory to the project directory (though it will knit as expected), making it incredibly difficult to edit Markdown documents that do not reside the the project folder. 

 I am currently using RStudio v1.2.5019.

**Comment by kevinushey** [comment]
Looks like we're monitoring this in https://github.com/rstudio/rstudio/issues/5412.
