### ISSUE TITLE
ERROR system error 13 Fedora Workstaion 29

### ISSUE THREAD

**Issue by jpearl01** [rstudio/rstudio#4528]
### System details

    RStudio Edition : Server
    RStudio Version : rstudio-server-rhel-1.1.463-x86_64.rpm
    OS Version      :  Fedora 29 Workstation
    R Version       :  3.5.3

### Steps to reproduce the problem
Fresh installation of Fedora workstation 29, RPM installs fine, R installs fine.  after loading rstudio-server with `rstudio-server start` I can open the gui in my browser remotely, but when I try to log in, I get an error

### Describe the problem in detail
In the logs after an attempted login:
```
Mar 27 15:43:30 localhost.localdomain audit[1570]: AVC avc:  denied  { setpgid } for  pid=1570 comm="rserver" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=process permissive=0
Mar 27 15:43:30 localhost.localdomain rserver[1570]: ERROR system error 13 (Permission denied); OCCURRED AT: rstudio::core::Error rstudio::core::system::launchChildProcess(std::__cxx11::string, std::__cxx11::st>

```
Not sure what is wrong, but after some googling I thought it might be some kind of PAM issue.  I copied /etc/pam.d/login to /etc/pam.d/rstudio-server and the user I was trying to log in as /etc/pam.d/josh

Still gives the same error.  Some additional info:
```
$ rstudio-server status
● rstudio-server.service - RStudio Server
   Loaded: loaded (/etc/systemd/system/rstudio-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-02-20 11:11:42 EST; 1 months 4 days ago
  Process: 969 ExecStart=/usr/local/lib/rstudio-server/bin/rserver (code=exited, status=0/SUCCESS)
 Main PID: 991 (rserver)
    Tasks: 3 (limit: 4915)
   Memory: 32.1M
   CGroup: /system.slice/rstudio-server.service
           └─991 /usr/local/lib/rstudio-server/bin/rserver

Feb 20 11:11:41 localhost.localdomain systemd[1]: Starting RStudio Server...
Feb 20 11:11:42 localhost.localdomain systemd[1]: Started RStudio Server.
Mar 27 15:43:30 localhost.localdomain rserver[1570]: ERROR system error 13 (Permission denied); OCCURRED AT: rstudio::core::Error rstudio::core::system::launchChildProcess(std::__cxx11::string, std::__cxx11::st>
```

And then:
```
$ rstudio-server verify-installation
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to stop 'rstudio-server.service'.
Authenticating as: Josh blah (josh)
Password: 
==== AUTHENTICATION COMPLETE ====
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to start 'rstudio-server.service'.
Authenticating as: Josh blah (josh)
Password: 
==== AUTHENTICATION COMPLETE ====

```

**Comment by jmcphers** [comment]
Sorry, we can't generally help with system configuration issues on this bug tracker. We'd recommend describing your issue on the R Admins section of our community forum:

https://community.rstudio.com/c/r-admin

**Comment by liaoshengyou** [comment]
> 抱歉，我们通常无法帮助解决此错误跟踪器上的系统配置问题。我们建议您在我们社区论坛的 R 管理员部分描述您的问题：
> 
> https://community.rstudio.com/c/r-admin

http://yangl.net/2021/04/19/rstudio-server-unable-to-connect-to-service/
