### ISSUE TITLE
Horizontal scrollbar persists and hovers over modals

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4529]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : MacOS 10.14.4
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Close RStudio (so that we start fresh)
2. System Preferences -> General -> Show Scroll Bars -> Automatically (or When Scrolling etc.)
3. Open RStudio
4. Switch to Environment pane
5. Hover mouse over bottom of quadrant, right above the border
    - Horizontal scroll bar should appear
6. Click on another pane in the same quadrant
7. Click on Environment pane
    - Horizontal scroll bar is still gone

The kicker:

8. Hover mouse over bottom of Environment quadrant again, right above the border
    - Horizontal scroll bar should appear
9. Start opening an R Markdown file: File -> New File -> R Markdown
10. Make sure that the modal is at least somewhat over the environment pane; move it over if needed.
    - The scrollbar appears over the modal.

Follow that up with:

11. Click "Cancel."
12. Hover over the bottom of the pane, so that the scrollbar returns
13. System Preferences -> General -> Show Scroll Bars -> Always
     - Horizontal scroll is still there
14. Mouse over the Environment pane
     - Horizontal scroll bar may or may not go away
15. Switch to another pane in the same quadrant
16. Switch to Environment pane
     - Horizontal scroll bar may go away or be replaced by a lighter-gray scrollbar

Next:

17. Close RStudio
18. Reopen RStudio
19. Hover over bottom of Environment pane
     - No horizontal scroll bar

### Describe the problem in detail

The scrollbar in the Environment and Source panes (maybe more) sticks around when it shouldn't. It happens when you mouse over the area at the bottom of the pane, when System Preferences -> General -> Show Scroll Bars is set to "Automatically" or "When scrolling," but not "Always." 

![more_scrolling](https://user-images.githubusercontent.com/31009952/54157880-9ec69480-441f-11e9-858d-9edb47cba0e0.gif)

### Describe the behavior you expected

The scrollbar should go away, or at least it shouldn't appear over the modals.

**Comment by kevinushey** [comment]
I'm going to move this to v1.2-patch as I don't think this should be a blocker for the v1.2 release.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.2.1539 on MacOS 10.14.6.
