### ISSUE TITLE
can't upload multiple files in rstudio 

### ISSUE THREAD

**Issue by jasonzhao0307** [rstudio/rstudio#4531]
Hi there,

I've been using Rstudio and Rshiny for a long time, and there is a bug that never fixed: if we open a shiny app in rstudio brower, it won't allow multiple file upload, I have to click the button "open in browser" to do that. Could you help me with this? Thanks a lot!!

**Comment by wch** [comment]
FWIW, multiple file upload works fine for me with RStudio 1.2.1268 on Mac. If you want help from the IDE team, I suggest providing information about your platform and a reproducible example -- basically, fill out the template when filing the issue.

**Comment by jmcphers** [comment]
Are you using RStudio 1.1, perchance?

**Comment by jmcphers** [comment]
Closing this since we haven't heard from you -- please reopen if the preview version doesn't fix your problem!

https://www.rstudio.com/products/rstudio/download/preview/
