### ISSUE TITLE
Issue with line numbers (and run progress color bars) + pointer calibration

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#4534]
In version 1.3.74, when running chunks, line numbers get distorted , along with progress color bars. 

It stays distorted when the chunk produces and error:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/33321678/55181147-5fbc7100-518b-11e9-9aa0-3960653507f6.png">

But the same happens with chunks that are ok.

Also, the mouse pointer behavior has changed when in "type" mode, it selects the line where the top of the pointer lies, not the middle like in other applications.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.74
    OS Version      : OS X 10.14.4
    R Version       : 3.5.3

### Steps to reproduce the problem
Running any Rmd file

**Comment by jmcphers** [comment]
Currently being tracked in https://github.com/rstudio/rstudio/issues/4257 (comment/upvote welcome!)

We also don't recommend the 1.3 builds for daily use yet. The 1.2 preview is ready, however:

https://www.rstudio.com/products/rstudio/download/preview/
