### ISSUE TITLE
Wrong indentation in document outline when using code sections

### ISSUE THREAD

**Issue by vh-d** [rstudio/rstudio#4538]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1335
    OS Version      : x86_64, linux-gnu 
    R Version       : 3.5.3 (2019-03-11)
              

### Steps to reproduce the problem

Put this code into a new script window

    # foo --------------------------------------------------------------------
    
    f <- function(x) {
      sum(x)
    }
    
    
    ff <- function(x) {
      mean(x)
    }
    
    
    # bar ---------------------------------------------------------------------

Toggle the document outline and get:

![sections_bug](https://user-images.githubusercontent.com/8167061/55260503-e4c98800-5268-11e9-9f3e-a1cbcae88ec4.png)

### Describe the problem in detail

Functions in the same sections should be indented equally, on the same level in the outline (right side of the screenshot).

**Comment by kevinushey** [comment]
Thanks for the bug report. Unfortunately, I'm not able to reproduce. Can you provide any other details?

**Comment by vh-d** [comment]
I experimented with various versions of RStudio and machines without any reasonable outcome.

- RStudio 1.1.463 works fine.
- Removing all the user settings does not help.
- Using RStudio install from tar ball does not help.
- I couldn't reproduce the issue on another linux machine with the same OS and very similar settings.

I would like to try some earlier version of RStudio 1.2 as I haven't noticed the issue until around 1.2.1300 versions but I do not know where to find older builds.

Could some shared libraries on my OS be blamed for interfering with RStudio?

**Comment by ronblum** [comment]
I wasn't able to reproduce it either, on Red Hat 7.6 in my case.

@vh-d Thank you for offering to test an earlier version! What OS are you using?

**Comment by vh-d** [comment]
I am on KDE Neon (Ubuntu 18.04 64-bit derivative). The other machine has the same OS yet it is not affected by this issue so believe it can be some QT5 libraries version incompatibility or something.

**Comment by vh-d** [comment]
The earliest RStudio 1.2 version I tried was 1.2.1322

**Comment by vh-d** [comment]
For some reason the issue is gone. I did not install updates and to my knowledge I did not change any settings so its difficult to make any reasonable conclusion. 

Until I see it again I am closing this issue now.

Thank you for your help.

**Comment by kevinushey** [comment]
Thanks! It's still possible this is some kind of (rare) timing issue so please let us know if the issue comes around again.

**Comment by tongyaop** [comment]
Not sure if this was intended by rstudio, but having a for loop wrapping around might change the way I would like the section to display. 

```r
# heading 1 ####
## heading 1.1 ####
## heading 1.2 ####
for (i in 1:5) {
  print(i)
### heading 1.2.1 ####
### heading 1.2.2 ####
}
```

would resulting in 1.2.1 and 1.2.2 not lining up.
![Capture](https://github.com/rstudio/rstudio/assets/132369756/383a453c-9381-4ada-94fd-9158b48ee799)
