### ISSUE TITLE
Add a task scheduler to JOBs

### ISSUE THREAD

**Issue by georgevbsantiago** [rstudio/rstudio#4544]
The JOBs feature is fantastic!

To get even better, it would be great to add a task scheduler.

As an example, it could indicate the packages cronR and taskscheduleR that has functionalities with that objective.

It would be interesting to have a native functionality of RStudio that did not depend on an operating system program.

![taskscheduleR ](https://github.com/bnosac/taskscheduleR/blob/master/vignettes/taskscheduleR-rstudioaddin.png)

![cronR ](https://github.com/bnosac/cronR/blob/master/vignettes/cronR-rstudioaddin.png)

**Comment by jmcphers** [comment]
In order to run tasks, RStudio would have to itself be running all the time so it could start scheduled tasks. This is not something we currently plan to do; the operating system task schedulers are the best tools for that.

**Comment by georgevbsantiago** [comment]
Hello, @jmcphers 

Exactly. I have an RStudio on a Digital Ocean VPS (droplet) that has been running for more than 2 years without stopping. I use it to run a Web Scraping. I currently use the 'cronR' package to run Web Scraping. But the JOB faction of RStudio 1.2 is fantastic and very user friendly. Therefore, a task scheduler to execute the scripts in JOB will be very useful.

**Comment by georgevbsantiago** [comment]
Another example: The Task Scheduler would help in the RStudio Cloud, being able to schedule and execute script, since the users can not use the CRON of Linux. For example, you could schedule a Web Scraping to run.
