### ISSUE TITLE
history + R autocompletion popups shown at same time

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4551]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1332
    OS Version      : macOS 10.14.3
    R Version       : 3.5.3

### Steps to reproduce the problem

Type some text in the R console to trigger automatic autocompletion; e.g.

```
sta
```

Then, just before the completion popup is displayed, try pressing <kbd>Cmd + Up</kbd> to request history items.

### Describe the problem in detail

Both the command history and the autocompletion popup are shown.

![Screen Shot 2019-04-01 at 1 45 16 PM](https://user-images.githubusercontent.com/1976582/55358503-68ab8c00-5484-11e9-8444-cf5f18708c51.png)

### Describe the behavior you expected

Only the command history should be shown.

**Comment by ronblum** [comment]
@kevinushey For what it's worth, I can't reproduce this. The only difference is that I'm using version 1.2.1335 with R 3.5.2.

**Comment by kevinushey** [comment]
@ronblum it requires some pretty specific timing, and also requires automatic code completion after 3 characters. E.g. my settings:

<img width="600" alt="Screen Shot 2019-04-04 at 9 02 59 AM" src="https://user-images.githubusercontent.com/1976582/55570537-7a757500-56b8-11e9-8699-4225e9e984d4.png">
