### ISSUE TITLE
Timing issue related to using saveRDS in RStudio

### ISSUE THREAD

**Issue by eayrapetian** [rstudio/rstudio#4558]
Calling saveRDS before executing a loop results in inconsistent loop timing. This is only evident when using RStudio; the issue does not exist when running the same script from the command line using Rscript. This may be a result of a delayed I/O flush in RStudio.

Using RStudio 1.1.463, R 3.5.2, on Ubuntu 18.04LTS 64-bit.

I eliminated the garbage collector as the issue by calling gc() before the code execution and enabling gc messages with gcinfo to make sure gc is not being triggered. I also tried to pre-compile the function with cmpfun; this does not help either.

The following code can be used to reproduce the issue.

```R
loop.test <- function() {
  t <- c()
  t0 <- Sys.time()
  for (i in 1:10) {
    t <- c(t, Sys.time() - t0)
    Sys.sleep(0.01)
  }

  dt <- round(1000 * diff(t), 1)
  print(dt)
  print(summary(dt))
}

saveRDS(1:10, 'garb.rds')

loop.test()
```
The code will produce the following output (loop times in ms):

```
[1]  10.1  10.1  10.2  10.2 275.4  10.2  10.1  10.2  10.2

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.10   10.10   10.20   39.63   10.20  275.40
```

Note that the large delay will not always appear at the same iteration.

Removing the saveRDS call in the code will always produce consistent (close to 10ms) loop timing.

Running the code from command line via Rscript will work with and without the saveRDS line.

I verified that the issue exists in RStudio v1.2, but to a much lesser extent; instead of a ~275ms long iteration, there is a ~24ms outlier iteration.

**Comment by pascaloettli** [comment]
RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : Ubuntu 18.04.2 LTS
    R Version       : 3.5.3


Using your code ran 1000 times I get in terminal:

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.20   10.30   10.30   10.29   10.30   13.50 
```

And with RStudio:

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.20   10.30   10.30   10.29   10.30   15.40 
```

Is there really a problem?

**Comment by eayrapetian** [comment]
Thanks for the quick response. Interesting result, this differs from what I see. Running for 1000 iterations, in RStudio I get:

```
 Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.10   10.20   10.20   11.25   10.20   28.50 
```
And from command line:
```
  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.10   10.10   10.10   10.13   10.10   11.20 
```
The only difference in my setup is that I'm using R 3.5.2 vs your 3.5.3. 

Also, as I noted before, the problem exists to a much larger extent in RStudio 1.1.463, can you reproduce what I'm seeing with that version?

**Comment by pascaloettli** [comment]
After a fresh start of RStudio `1.1.463` (5000 iterations):

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.10   10.30   10.30   10.31   10.30   67.40 
```

After a restart of R inside RStudio, without restarting the latter (5000 iterations)
```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.10   10.20   10.30   10.26   10.30   15.80 
```

So I can see an increase in the delay for some iteration, but not as large as yours. Please note, if it may be important, I have a customized installation of R, i.e. with optimization for my CPU. Not sure it might play a role or not.

**Comment by eayrapetian** [comment]
It's possible the customized R install plays a role. But my theory is that this is an I/O operation delay, likely flushing the saveRDS write to disk. So could also be that you have a faster I/O system. I should note that I am running in a VM, but this is on top of an ESXi server, so the overhead should be minimal. The VM is on a Samsung 840 Pro SSD, maybe you have a newer/faster drive?

Note also that you shouldn't have to run for many iterations to see the outlier. It should happen very quickly, so running for around 30 iterations is usually enough, at least on my system. Is this what you're seeing also?

So you're able to see a greater effect of this issue on the previous RStudio release, as I am. Any idea what changed in the RStudio implementation that would make this work differently?

Another interesting data point would be to check if this behavior can be replicated on Windows or OSX. If it doesn't happen there, then it's likely something specific to Linux. I don't have a Windows or OSX setup unfortunately though.

**Comment by kevinushey** [comment]
One possibility: RStudio does some background work during R "idle" (ie: when R calls `R_ProcessEvents`), and I think project file indexing is one of those things. RStudio registers file monitors for these tasks, so the creation of a file might cause RStudio to do some re-indexing work behind the scenes.

One way to test this hypothesis would be to compare the results of this test when a project containing a very large number of files is open, versus an empty / bare project.

**Comment by kevinushey** [comment]
It would also explain why the issue might reproduce more readily in new RStudio sessions, as opposed to long-running sessions, as the indexer will run and iterate over all files in the project at session launch.

**Comment by eayrapetian** [comment]
I think you got it! Based on what you said, I figured if I tried saving the file in a directory outside the project, then the issue would not appear. And it does appear to be so. I just changed the call to saveRDS to save to "~/garb.rds" instead of "garb.rds". The loop timing is consistent now. Would be good to verify on  your end that you can duplicate this result. So there must be something different with the new RStudio release in regard to indexing then?

**Comment by jmcphers** [comment]
I don't think there's work left to do here; if this is causing a problem in your usage you can turn off project indexing via Project Options -> Code Editing -> Index Source Files.
