### ISSUE TITLE
macOS: Toggle for 'High Performance GPU' to save battery life for laptops

### ISSUE THREAD

**Issue by TheBrightlyProject** [rstudio/rstudio#4559]
**Issue:** 
RStudio signals macOS that it requires High Performance GPU, which turns on the discrete graphics chip in a laptop.
When not plugged into power source, requiring High Perf. GPU drains the battery *much* faster than using the integrated GPU.
If I am just typing code, even running some analysis, the integrated GPU should be sufficient.

_Additional info:_
I can't seem to tell why RStudio requires High Performance graphics, as my partner who has a similar MacBook Pro without the discrete graphics chip seems to run RStudio and our analysis at similar speeds.

**System:**
macOS Mojave 10.14.4, MacBook Pro 2014 15" with Integrated Intel GPU + Nvidia GPU

**RStudio version:**
Build 1351 (f1ac3452)

**Question / Suggestion:**
Is High Perf. graphics necessary by default? Could it be a toggle for those who need the performance can turn it on?

**Comment by jmcphers** [comment]
No, you can turn it off. Does it help to use the software rendering engine?

Tools -> Options -> General -> Advanced -> change Rendering Engine to Software, then close and re-open RStudio.

**Comment by kevinushey** [comment]
There is also the [NSSupportsAutomaticGraphicsSwitching](https://developer.apple.com/documentation/bundleresources/information_property_list/nssupportsautomaticgraphicsswitching) flag, which we could try setting.

**Comment by TheBrightlyProject** [comment]
Thank you both for responding. I had already tried the Rendering Engine options previously, as well as the options for GPU Blacklist, and GPU Driver Bugs (in the hope that some combination would prevent the discrete graphics from being required).

As I type this, I did try once more the 'Software' rendering option, however it still forces the discrete GPU to come on (confirmed by looking at both Activity Monitor and seeing RStudio having the 'High Perf.' to Yes, and also under the About This Mac showing both graphics cards active.

Also, I would expect that dropping down to software rendering may not be the most optimal as that may entirely bypass any benefits provided by the integrated GPU.

@kevinushey is that a flag that I could try setting somewhere myself?

**Comment by TheBrightlyProject** [comment]
Also, there was a time when Apple introduced their 2016 MacBook Pros and people were complaining about poor battery life. What was happening was that too many apps were unnecessarily requiring the discrete graphics (e.g. Chrome, certain sites viewed in Safari, even the built-in Photos app).

Over time most apps have become more conservative about requiring the discrete graphics, thus improving battery life - because even the integrated graphics are fine for most graphics processing use-cases.

It makes sense that e.g. Adobe Photoshop enables the discrete GPU if available, but I'm not sure if RStudio really needs it...
