### ISSUE TITLE
Multiline R prompt causes cursor to not start in the correct position

### ISSUE THREAD

**Issue by schloerke** [rstudio/rstudio#4560]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : 10.14.3
    R Version       : 3.5.2

### Steps to reproduce the problem

```r
remotes::install_github("gaborcsardi/prompt")

prompt::set_prompt(function(...) { 
  paste0(
    "line1\n", 
    crayon::red("line2line2"), "\n", 
    crayon::green("line3line3line3"), 
    "\n> "
  ) 
})
```

### Describe the problem in detail

The cursor is starting at the far right of the prompt's rectangular area.  It is not on the last line of the prompt.  

Also, prompt colors are not rendered until the R line is submitted.  They are all blue until code submission.  After submission, the colored prompt appears.

![Screen Shot 2019-04-02 at 9 45 27 AM](https://user-images.githubusercontent.com/93231/55407517-17ef6e00-552c-11e9-9071-b6faee4d0d9d.png)

### Describe the behavior you expected

I believe it should be at the end of the prompt text, inside the rectangular area. It should be on _line 4_ just after `> `.

**Comment by ronblum** [comment]
@schloerke Thank you for reporting the issue. I can reproduce it with both 
- RStudio Desktop 1.2.1335 on MacOS 10.14 using R 3.5.2
- RStudio Server 1.2.1335 on Red Hat 7.6 using R 3.5.1 from Firefox on MacOS 10.14
