### ISSUE TITLE
Multiple memory consuming root rserver processes

### ISSUE THREAD

**Issue by ktdevemu** [rstudio/rstudio#4564]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.456-1
    OS Version      :  Red Hat Enterprise Linux 7
    R Version       : 3.5.1

### Describe the problem in detail
The initial rstudio process is spawning multiple root owned processes when server-user is set to a regular user

root       6670  82217  0 Apr01 ?        00:00:00 /usr/lib/rstudio-server/bin/rserver
root      65472  82217  0 Mar29 ?        00:00:00 /usr/lib/rstudio-server/bin/rserver
rstudio+  82217      1  0 Mar28 ?        00:01:10 /usr/lib/rstudio-server/bin/rserver
root      82564  82217  0 Mar29 ?        00:00:00 /usr/lib/rstudio-server/bin/rserver

### Describe the behavior you expected

Only rserver processes owned by the rstudio-server user

**Comment by kevinushey** [comment]
Do you see the same behavior with the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by ktdevemu** [comment]
Haven't been able to test on the preview release.  I had seen a previous post on older forums showing a similar issue.  I have the developers using Rstudio server looking at what they did at the timestamps of the spawned rserver processes at the moment to see if it's anything in any of their libraries.

**Comment by jmcphers** [comment]
No reports of this or other repro steps in over a year, so closing.
