### ISSUE TITLE
Depend on Shinytest > 1.3.0

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4565]
We currently depend on Shinytest 1.2.

https://github.com/rstudio/rstudio/blob/b997d8ce8bd87b36955f5f796d64d2636f43d47c/src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java#L823-L826

However, Shinytest 1.2 does not work with RStudio Server; see https://github.com/rstudio/rstudio/issues/4555 and linked issue for a discussion of why this is the case. It is therefore necessary to use the development version of Shinytest with RStudio Server, which is not ideal.

For RStudio Server compatibility, we need a newer version of Shinytest than is currently on CRAN; specifically greater than 1.3.0. The Shinytest team is preparing a CRAN release; when they do, we should add a dependency on it. We expect this to happen in the 1.2-patch timeframe.

**Comment by cpsievert** [comment]
Just FYI, shinytest was submitted to CRAN yesterday

**Comment by jmcphers** [comment]
@cpsievert Thanks, we'll update the dependency shortly!

**Comment by ronblum** [comment]
If `shinytest` 1.3.0 is installed, RStudio doesn't prompt for an update to 1.3.1 when recording a test.

**Comment by kevinushey** [comment]
Now backported to v1.2-patch -- should be fixed in the next builds.

**Comment by ronblum** [comment]
Where `shinytest` works properly, this works properly. However, I'm investigating issue #4555, about `shinytest::recordTest` failing, so I'm holding off on marking this as full verified.

**Comment by ronblum** [comment]
#4555 is not an RStudio issue, so done verifying.
