### ISSUE TITLE
Reduce cost of tracking current-working-directory in terminals (macOS)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#4570]
In the RStudio terminal, on macOS, we poll every two seconds to obtain the current-working-directory of each terminal, by executing lsof:

`lsof -a -p PID -d cwd -Fn`

There are reports of lsof being extremely slow on macOS (and getting slower with time). On Linux we use procfs, instead, and on Windows we don't even preserve CWD.

https://apple.stackexchange.com/questions/81140/why-is-lsof-on-os-x-so-ridiculously-slow

We haven't proven it yet, but suspect some users are encountering overall slowdowns as a result of slow lsof calls.

Possible mitigations:

- provide option to disable this functionality and/or change the polling time (hardcoded to every two seconds)
- add the `-n`, `-P`, and `-l` options to the lsof call; it is possible lsof is loading more info than we need then filtering down to what we asked for, so these options might help despite not being directly related to what we're querying
- suppress cwd tracking when terminal session is not visible
- find a faster way to obtain this info (e.g. can we use the same underlying Mach/BSD calls as `lsof` itself)

**Comment by kevinushey** [comment]
It looks like the `proc_pidinfo()` API makes it pretty easy to obtain this. I put together a PR here: https://github.com/rstudio/rstudio/pull/4571

**Comment by gtritchie** [comment]
Fixed with 98f588ff
