### ISSUE TITLE
`Check Package` in RStudio fails while succeeds on trevor-ci and manually

### ISSUE THREAD

**Issue by rkrug** [rstudio/rstudio#4573]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1330
    OS Version      :  High Sierra 10.13.6
    R Version       : 3.5.3

### Steps to reproduce the problem
clone [https://github.com/Exp-Micro-Ecol-Hub/emeScheme/commit/9bbd10c5779419140fbb56d2f827456899b65f1c](https://github.com/Exp-Micro-Ecol-Hub/emeScheme/commit/9bbd10c5779419140fbb56d2f827456899b65f1c)

Run Build - Check package

### Describe the problem in detail
`Check Package` in RStudio fails:
```
> test_check("emeScheme")
── 1. Failure: validata_raw() returns correct value when correct (@test-validate.R#10)  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
validate(x = x, errorIfStructFalse = TRUE) has changed from known value recorded in 'validate.CORRECT.rda'.
Component "Measurement": Component "variableInMappinColumn": Component "details": Component "variable": Attributes: < Component "levels": 3 string mismatches >
Component "DataFileMetaData": Component "mappingColumnInNameOrParameter": Component "details": Component "mappingColumn": Attributes: < Component "levels": 2 string mismatches >
Component "DataFileMetaData": Component "columnNameInDataFileColumn": Component "details": Component "columnName": Attributes: < Component "levels": 9 string mismatches >
Component "DataFileMetaData": Component "dataFileColumnInColumnNamen": Component "details": Component "dissolved_oxygen_measures.csv": Component "columnNameInDataFileName": Attributes: < Component "levels": 2 string mismatches >
Component "DataFileMetaData": Component "dataFileColumnInColumnNamen": Component "details": Component "abundances.csv": Component "columnNameInDataFileName": Attributes: < Component "levels": 5 string mismatches >

Names: 1 string mismatch
══ testthat results  ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
OK: 30 SKIPPED: 0 FAILED: 1
1. Failure: validata_raw() returns correct value when correct (@test-validate.R#10) 

Error: testthat unit tests failed
Execution halted

1 error ✖ | 0 warnings ✔ | 0 notes ✔
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.
```

While running in the terminal

```
R CMD build .
R CMD check ./emeScheme_0.9.0.2.tar.gz
R CMD check --as-cran ./emeScheme_0.9.0.2.tar.gz
```

both succeed.

Also: it succeeds on Trevor-ci [https://travis-ci.com/Exp-Micro-Ecol-Hub/emeScheme/builds/107038251](https://travis-ci.com/Exp-Micro-Ecol-Hub/emeScheme/builds/107038251)

### Describe the behavior you expected

`Check Package` in RStudio should also pass.

**Comment by ronblum** [comment]
@rkrug I tried this out after cloning the above repository on RStudio Desktop 1.2.1335 on MacOS 10.14 using R 3.5.3. A couple of questions:
1) One of the package dependencies is `plantuml`, which is not published on CRAN. Can you confirm that the correct package is `rkrug/plantuml` at GitHub?
2) What do you get with `devtools::check()` or clicking on the "Check" button in the Build pane?

**Comment by rkrug** [comment]
OK - here is the additional info:

> 1. One of the package dependencies is plantuml, which is not published on CRAN. Can you confirm that the correct package is rkrug/plantuml at GitHub?

It is in the **Suggests** and only needed in creating a vignette if a svg graph is missing.

Correct - on github at [https://github.com/rkrug/plantuml](https://github.com/rkrug/plantuml)

> 2. What do you get with devtools::check() or clicking on the "Check" button in the Build pane?

`devtools::check()` gives the same error.

**Comment by jmcphers** [comment]
If you can see the error with `devtools::check()` then it isn't a bug in RStudio. You might try raising this on the community forum if you're still having trouble:

https://community.rstudio.com/c/rstudio-ide
