### ISSUE TITLE
Feature Request: Add clipboard copy button to dataframe view

### ISSUE THREAD

**Issue by petesherick** [rstudio/rstudio#4574]
Essentially a button to do:
write.table(df, file='clipboard', sep='\t', row.names=FALSE)
and/or a save as excel/csv button

**Comment by jmcphers** [comment]
This would be useful! Thanks for the idea. There are a few R packages which you might be interested in until we can do this: 

https://github.com/mdlincoln/clipr

https://github.com/MilesMcBain/datapasta
