### ISSUE TITLE
Unrecognized initial character when using dead keys in RStudio Server

### ISSUE THREAD

**Issue by arcruz0** [rstudio/rstudio#4575]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.463 (also happening in RStudio Cloud, 1.2.1206-2)
    OS Version      : Ubuntu 18.10
    R Version       : 3.5.3 (3.5.2 in RStudio Cloud)

### Steps to reproduce the problem

Attempt to insert an accented letter using dead keys.

### Describe the problem in detail

![rstudio-server-dead-keys](https://user-images.githubusercontent.com/28851411/55560198-1eb1e880-56c6-11e9-9c1f-64f53446c1f4.gif)

### Describe the behavior you expected

In RStudio Desktop, after pressing a dead key the initial (underlined) symbol is simply not shown, but it works anyway (pressing it again inserts the symbol, while pressing a letter afterwards inserts its modified version).

--

Thank you!

**Comment by ronblum** [comment]
Thank you @arcruz0 for reporting this issue. Can you try out the latest RStudio 1.2 preview, available at https://www.rstudio.com/products/rstudio/download/preview/, and let us know what happens?

**Comment by arcruz0** [comment]
Thank you! I just installed RStudio Server 1.2.1335 and the issue is still there.

**Comment by kevinushey** [comment]
What browser are you using to connect to RStudio?

**Comment by arcruz0** [comment]
Firefox, but the problem happens in Chromium too:

![Screenshot from 2019-04-04 14-29-59](https://user-images.githubusercontent.com/28851411/55575850-4153f980-56e6-11e9-9eeb-f54b6f945ebb.png)

**Comment by ronblum** [comment]
@arcruz0 What keyboard layout and dead keys are you using?

**Comment by arcruz0** [comment]
Just a regular one: "Spanish (Latin America)"

**Comment by ronblum** [comment]
(Going through old issues) @arcruz0 Does this problem still occur?
