### ISSUE TITLE
Clicking selection between parentheses in console takes random focus and selection

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4576]
**Steps to reproduce:**
* Print some output to fill the console.
* Write some multi-line statement in the console that would include lines with parentheses that would have comma-separated arguments.
* Scroll a bit up so that the console statement being written is not shown entirely (if it's already scrolled to the end the bug usually doesn't happen).
* Select some text between the parentheses in the console statement.
* Click the same selection between the parentheses.

**Expected behavior:** should de-select what was selected and focus on where it was clicked.

**Actual behavior:** selects everything from the start of the variable where the click fell, to either the end of the statement or some other random part below the click, and shifts the focus to the end of where the new selection is.

**Setup:** RStudio 1.2.1335, R 3.5.1, running on windows 10 and linux.

**Comment by jmcphers** [comment]
Sorry, this bit isn't 100% clear -- could you give an example?

> Write some multi-line statement in the console that would include lines with parentheses that would have comma-separated arguments.

**Comment by david-cortes** [comment]
Bug in action:
![click_console_sel](https://user-images.githubusercontent.com/11860098/79282519-1639e380-7ebe-11ea-823f-57e7103def32.gif)

**Comment by kevinushey** [comment]
You might want to check if this had been fixed for you in the preview release: https://rstudio.com/products/rstudio/download/preview/

**Comment by david-cortes** [comment]
Problem is no longer present in 1.3.938.
