### ISSUE TITLE
Debugger behaves strangely with package breakpoint on rmardown::render call

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4578]
**Steps to reproduce:**
* Create some package containing a .Rmd file in `/inst` containin snippets like the following:
````
`r if(condition) {"\\begin{comment}"}`
```{r}
code_that_is_not_executed
```
`r if(condition) {"\\end{comment}"}`
````
and a function that would render it through `rmarkdown::render`.
* Build and install package.
* Put a line break in the line that calls `rmarkdown::render` for the debugger.
* Run function, wait until in reaches line break.
* Try to execute the `rmarkdown::render` call from the console while inside the debugger.

**Expected behavior:** should work the same as when debugging any other function.

**Actual behavior:** it's very hard to describe. It seems to pause at the end of some chunks and every time it reaches one of those `` `r` `` snippets, despite the `.Rmd` not being debugged and not having any "step into" in the debugging of the function that calls `rmarkdown::render`. After that, anything that is written in the console will not execute (until the next "continue"), or might open random parts of the package files in debugger mode with approximate debug location. Clicking the button "next" will not do anything either (will just get an `n` in the console, which does not execute), but clicking "Continue" will continue to the next chunk or up until the next break, and along with it open some random file and line with approximate debug location (despite them not being  called within the `.Rmd`). The rendered document will also be different compared to executing the call without debugger.

**Comment by jmcphers** [comment]
No other reports of this in a year so closing. This very advanced usage is probably out of scope for the debugger.
