### ISSUE TITLE
xtabs() is detecting a non-existent syntax/subset error

### ISSUE THREAD

**Issue by leecreighton** [rstudio/rstudio#4585]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463 
    OS Version      : Macintosh 10.14.3
    R Version       : 3.5.2 (2018-12-20) -- "Eggshell Igloo"

I have the following code entered into an R Script:
```r
require(mosaicData)
require(vcd)
require(datasets)

#### Look at some data ####
levels(Whickham$outcome)
levels(Whickham$smoker)
str(Whickham$outcome)
str(Whickham$smoker)
table(Whickham$smoker, Whickham$outcome)
with(Whickham, table(outcome, smoker))
xtabs(~ outcome + smoker, data = Whickham)

#### Graphical Methods ####
WhickTable = table(Whickham$smoker, Whickham$outcome)
mosaicplot(WhickTable)

mosaicplot(WhickTable, color = c("#F66733", "#522D80"), main = "Whickham Data", xlab = "Smoker?", ylab = "outcome")
mosaic(~ outcome + smoker, data = Whickham)
```

### Describe the problem in detail
Beside the xtab() function on line 12, a yellow inverted triangle caution sign appears, saying "argument 'subset' is missing, with no default"

### Describe the behavior you expected

![2019-04-05_14-22-10](https://user-images.githubusercontent.com/19454134/55648426-47151200-57ae-11e9-9394-7d2706c4c8f6.png)

**Comment by ronblum** [comment]
@leecreighton Thank you for raising this issue. We will review it as we work on development of future versions of RStudio.

**Comment by jackwasey** [comment]
See also https://github.com/rstudio/rstudio/issues/2625

This is a more general problem when a function is defined with a potentially missing parameter, and the function body uses `missing(maybe_missing_arg)`.
