### ISSUE TITLE
Allow for Windows hosts to use pwsh (PowerShell Core) as a terminal type

### ISSUE THREAD

**Issue by davidski** [rstudio/rstudio#4592]
Windows Powershell (powershell.exe) is slowly going away (Powershell 7 will be what is today Powershell Core). The current 1.2 preview releases of RStudio Desktop do not allow the user to specify custom executables as is possible under Mac/Linux. A potential intermediate solution to allowing full customization is support for the user to choose pwsh.exe (PowerShell Core) for their terminal type.

**Comment by gtritchie** [comment]
Note to self, the PR that added custom terminals for macOS and Linux is https://github.com/rstudio/rstudio/pull/1271
