### ISSUE TITLE
Private CRAN proxys not working with Rstudio Server 1.2?

### ISSUE THREAD

**Issue by h-vetinari** [rstudio/rstudio#4595]
I'm setting up an RStudio Server instance on a machine that only has access to a CRAN proxy (on a Sonatype Nexus), and RStudio Server (1.2.1335) will not accept attempts to set up the proxy correctly through the GUI:

![proxy1](https://user-images.githubusercontent.com/33685575/55728213-f0a90d00-5a13-11e9-95e8-ecea112cc06c.png)
![proxy2](https://user-images.githubusercontent.com/33685575/55728253-061e3700-5a14-11e9-9795-b2192fd3efe7.png)

The proxy has an address that is roughly: `http://where.nexus.is.running:8081/repository/cran.raw.proxy/`. The check behind this GUI needs to be much more permissive IMO - private repos can have essentially arbitrary paths. I'm fine with a warning, but currently, the hard error makes interaction impossible. Removing the port number (`:8081`) also does not solve the issue.

The proxy definitely *does* work, as setting it correctly in `Rprofile.site` allows me to to install things in vanilla `R`, but then yields the following error in RStudio (aside from a warning in the "Packages" dialogue that `CRAN repositories modified outside package preferences.`):
```
Warning in install packages :
  unable to access index for repository http://where.nexus.is.running:8081/repository/cran.raw.proxy/src/contrib:
```

The error persists also when disabling "Use secure download method for HTTP".

**Comment by kevinushey** [comment]
RStudio checks that a valid CRAN repository has been provided by attempting to download a file at `src/contrib/PACKAGES.gz`. Does that exist on your CRAN repository?

I would agree that this check could be refined, and moreover that we should still permit the setting of a CRAN repository that fails this check (with a warning rather than an error).

**Comment by h-vetinari** [comment]
@kevinushey 

Thanks for explaining the check. I checked, and made sure `src/contrib/PACKAGES.gz` is available through the proxy. I still get the error "The given URL does not appear to be a valid CRAN repository" (side note: I did for the first time see a brief flicker of "Validating CRAN repository", but this does not appear always - I'm assuming it's cached somewhere).

Are there any other aspects of the check for the repository?

**Comment by h-vetinari** [comment]
Update: it's something that's influenced (at least) by `download.file.method`. If I set this option to `"curl"` or `"wget"`, I manage to downlad the packages.

**Comment by kevinushey** [comment]
You should check both of:

```
getOption("download.file.method")
getOption("download.file.extra")
```

Also, if you have the `http_proxy` environment variable set, that will be used by `curl` when downloading files.

**Comment by h-vetinari** [comment]
@kevinushey 
> You should check both of: [...]

Default is `"libcurl"` and `NULL` - what should I do with this information?

Installation from vanilla R is working as I mentioned (and does not have these options), and curl is on the PATH [here within RStudio]:
```
> Sys.getenv("PATH")
[1] "/sbin:/usr/sbin:/bin:/usr/bin"
> system("curl")
curl: try 'curl --help' or 'curl --manual' for more information
```

So, at least (IMO), there should be a more informative error message than a malformed html.

**Comment by kevinushey** [comment]
Your CRAN repository is serving you that HTML (likely, it's serving something like an "unauthorized" or "error" HTML page), whereas R is expecting the contents to be an actual package.

If the `libcurl` downloader is not working for you, I'd recommend just overriding the options e.g. in your `.Rprofile`:

```
options(
    download.file.method = "curl",
    download.file.extra = "-L -f"  # follow redirects; fail on error
)
```

**Comment by h-vetinari** [comment]
@kevinushey 
Thanks for taking the time. The redirect is what was necessary.

> [...] but this is R running under the hood as opposed to RStudio-specific code.

This is what I didn't understand - plain R worked. Maybe it uses different defaults for `(lib)curl` under the hood and can deal with redirects, while RStudio does not?

In any case, while it was very hard for me to debug and find that I had to fiddle with `download.file.method` (while plain R worked), I'm gonna close this issue. I do think however that the errors could/should be improved.

**Comment by kevinushey** [comment]
Out of curiosity, what version of R are you using? My understanding is that when using `libcurl` R will follow redirects:

https://github.com/wch/r-source/blob/f4c671ce497094fb1e86879c1f7708e33614536b/src/modules/internet/libcurl.c#L273

but there was a bugfix related to this behavior:

https://github.com/wch/r-source/commit/fbd85de44fe77549848e2587dec32c31c849089f

so older versions of R (< 3.5) might unsuccessfully follow redirects in some cases.

**Comment by h-vetinari** [comment]
@kevinushey 

It's R 3.5.1 on Ubuntu 18.04.

> so older versions of R (< 3.5) might unsuccessfully follow redirects in some cases.

As I keep saying, the default setup of vanilla R was *successfully* following redirects.
