### ISSUE TITLE
DevTools window does not close using keyboard (cmd + w)

### ISSUE THREAD

**Issue by schloerke** [rstudio/rstudio#4599]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : macOS 10.14.4
    R Version       : 3.5.3

### Steps to reproduce the problem

```
shiny::runExample("01_hello")
```

1. Right click on window. 
2. Select "Inspect Element". 
3. Try to close window using `cmd + w`

### Describe the problem in detail

The window does not close.

### Describe the behavior you expected

The window should close.

**Comment by ronblum** [comment]
@schloerke Thank you for reporting the issue, which I was able to reproduce on MacOS RStudio Desktop. (Note: not an issue on RStudio Server via a web browser.)

**Comment by schloerke** [comment]
Not stale. Still a bug.
