### ISSUE TITLE
Ctrl-1 should return to popout window

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4608]
I often use the keyboard shortcut Ctrl-1 to return to the source script. However, even if I have just come from a source script within a popout window, RStudio will return me to the source script within the main window. It would be fantastic if the behavior could be modified such that Ctrl-1 returns you to the source script that was most recently active.

**Comment by pascaloettli** [comment]
_RStudio v1.2 is currently available as a preview release, from https://www.rstudio.com/products/rstudio/download/preview/. If you are reporting a bug with RStudio v1.1, it would be greatly appreciated if you could check if the issue also reproduces in the preview release before reporting an issue._

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by elgabbas** [comment]
I noticed the same issue with the new version of RStudio. It seems that all shortcut keys to move focus to ** and show ** do not work (in View menu).
![RStudio](https://user-images.githubusercontent.com/7375051/55876287-92a53280-5b97-11e9-88b2-36f56a4b51de.jpg)

**Comment by dfalty** [comment]
Thanks @kendonB for your suggestion. It might be confusing if this works with last used source editor, but I think it would be nice to be able to switch to the pop out source editor with a shortcut somehow even if it's not Ctrl+1.

@elgabbas are you saying that these options don't work at all? If that's the case that sounds like a bug and different from this enhancement request to add functionality to work with the pop out source window. If that's the case, do you mind creating a different issue saying that these shortcuts don't work at all for you and include your specific version of RStudio + operating system?

**Comment by elgabbas** [comment]
I created another issue: https://github.com/rstudio/rstudio/issues/4613

**Comment by kendonB** [comment]
Wasn't able to verify that this problem persists on RStudio preview as it crashes instantly on Windows 7 virtualbox within my Ubuntu machine.

**Comment by kendonB** [comment]
This appears to be solved in the latest RStudio preview 1.3.842. Great!!

**Comment by kendonB** [comment]
However, what is the current method to return focus to the source pane in the main window? I had not anticipated that there would be no way to do this if Ctrl-1 went back to a popped out window
