### ISSUE TITLE
libssl version is wrong on Fedora 30 beta

### ISSUE THREAD

**Issue by znmeb** [rstudio/rstudio#4612]
### System details

    RStudio Edition : Desktop
    RStudio Version : https://s3.amazonaws.com/rstudio-ide-build/desktop/centos7/x86_64/rstudio-1.2.1335-x86_64.rpm
    OS Version      : Fedora 30 Beta
    R Version       : R version 3.5.3 (2019-03-11) -- "Great Truth"

### Steps to reproduce the problem
1. Upgrade Fedora 29 to Fedora 30 or install the Fedora 30 beta
2. Download the RPM listed above
3. `sudo dnf install rstudio-1.2.1335-x86_64.rpm`
4. Start `rstudio` at the command line

### Describe the problem in detail
```
$ rstudio
rstudio: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
```

### Describe the behavior you expected
RStudio Desktop starting

**Comment by yulijia** [comment]
Hi, I have met the same problem yesterday on my new Fedora 29 laptop. If my memory serves me right, the problem will go away after installing `compat-openssl10`

**Comment by znmeb** [comment]
I have it working in 29 - it was the upgrade to 30 that broke it. I'll try `compatopenssl10` - where is it documented as a requirement for RStudio Desktop?

**Comment by yulijia** [comment]
This is not a ideal solution, `compat-openssl10` provide `libssl.so.10`, please see this post [libssl 1.0.0 in Fedora 28
](https://ask.fedoraproject.org/en/question/127935/libssl-100-in-fedora-28/)

**Comment by znmeb** [comment]
Ah - thanks! I have it working on Fedora 30 with compat-openssl10. The RStudio "Red Hat" RPM supports RHEL7+ and Fedora 19+, but Fedora only supports the last three stable releases - 27, 28 and 29 - plus 30 which is in beta. So an ideal solution would be for RStudio to provide RPMs for RHEL7, the upcoming RHEL8 and and Fedora 28 through 30 - 27 is going end-of life shortly after 30 goes stable.

**Comment by kevinushey** [comment]
@jmcphers do you think this implies we need to expand the build matrix for newer versions of Fedora / RHEL / CentOS? IIUC these versions will be using OpenSSL 1.1.1.

**Comment by jmcphers** [comment]
Yes, unfortunately. We already build on Ubuntu 18 and OpenSuSE 15 specifically because those platforms have upgraded to OpenSSL 1.1.

**Comment by znmeb** [comment]
RHEL 8 too, I think - there's a beta if you want to test now.

**Comment by jmcphers** [comment]
We will probably wait for the official CentOS 8 (due soon after RHEL 8) Docker image, and build from there; building from CentOS gives us a binary that works on CentOS, RHEL, and Fedora.

**Comment by nilesh-iiita** [comment]
Just install 64 bit version of compat-openssl
`dnf install compat-openssl10.x86_64`

**Comment by jmcphers** [comment]
CentOS 8 status here: https://wiki.centos.org/About/Building_8

**Comment by imanuelcostigan** [comment]
I have the same problem on Debian 9. Updated to 1.1.0 and breaks installing RStudio Server 1.2.1511

**Comment by jmcphers** [comment]
@imanuelcostigan Are you using the version of RStudio Server built specifically for Debian 9?

https://download2.rstudio.org/server/debian9/x86_64/rstudio-server-1.2.1335-amd64.deb

**Comment by dmhowcroft** [comment]
For the time being, could you modify the download page to mention the requirement that we install `compat-openssl10.x86_64` for modern Fedora?

**Comment by manikandanappuv9** [comment]
Thank you so much, it worked. But i really dont understand how you people understand nook and corner of errors and problems. When i see the error, i feel weird. I really request you to provide the path to become expert like you. 
Thanks again

**Comment by manikandanappuv9** [comment]
> @imanuelcostigan Are you using the version of RStudio Server built specifically for Debian 9?
> 
> https://download2.rstudio.org/server/debian9/x86_64/rstudio-server-1.2.1335-amd64.deb



> Yes, unfortunately. We already build on Ubuntu 18 and OpenSuSE 15 specifically because those platforms have upgraded to OpenSSL 1.1.

Thank you so much, it worked. But i really dont understand how you people understand nook and corner of errors and problems. When i see the error, i feel weird. I really request you to provide the path to become expert like you. 
Thanks again

**Comment by manikandanappuv9** [comment]
> For the time being, could you modify the download page to mention the requirement that we install `compat-openssl10.x86_64` for modern Fedora?

Thank you so much, it worked. But i really dont understand how you people understand nook and corner of errors and problems. When i see the error, i feel weird. I really request you to provide the path to become expert like you. 
Thanks again

**Comment by jmcphers** [comment]
@znmeb @yulijia et al., we now have a Fedora 28 build that may work for you. Can you try it and let us know how it goes?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by manikandanappuv9** [comment]
Sure😊🤗🤗, but may I know how do you know that I work on Linux fedora

**Comment by yulijia** [comment]
@jmcphers  I installed the preview version RStudio `v1.2.1555-1` and removed `compat-openssl10` from my OS, the new version of Rstudio works well in Fedora 29. 
Thanks!

**Comment by manikandanappuv9** [comment]
Ok

**Comment by h-vetinari** [comment]
Happy to report that also the Ubuntu 18.04 build now can handle openssl 1.1.1

**Comment by jmcphers** [comment]
From @ronblum:

```
Aug 15 10:43:13 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=rstudio-server comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 15 10:43:13 localhost.localdomain audit[53357]: AVC avc:  denied  { create } for  pid=53357 comm="rserver" name="rserver.socket" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=sock_file permissive=0
Aug 15 10:43:13 localhost.localdomain rserver[53357]: ERROR system error 13 (Permission denied) [stream=/tmp/rstudio-rserver/rserver.socket]; OCCURRED AT: rstudio::core::Error rstudio::core::http::initLocalStreamAcceptor(rstudio::core::http::SocketAcceptorService<rstudio_boost::asio::local::stream_protocol>&, const rstudio::core::FilePath&, rstudio::core::system::FileMode) /var/lib/jenkins/workspace/IDE/pro-pipeline/v1.2-patch/src/cpp/core/include/core/http/LocalStreamSocketUtils.hpp:76; LOGGED FROM: int main(int, char* const*) /var/lib/jenkins/workspace/IDE/pro-pipeline/v1.2-patch/src/cpp/server/ServerMain.cpp:506
```

**Comment by jmcphers** [comment]
Fixed in our preview release:

https://www.rstudio.com/products/rstudio/download/preview/

The RedHat 8 build is suitable for Fedora 30. Note that you will need to adjust or disable the default SELinux configuration so RStudio can create its domain sockets (see above for errors that will result otherwise).

**Comment by ronblum** [comment]
Verified on Fedora 30 with RSP 1.2.1568 and SELinux turned off, without the `compat-openssl10` workaround.

**Comment by areelillmind** [comment]
> Just install 64 bit version of compat-openssl
> `dnf install compat-openssl10.x86_64`
This nailed it!
