### ISSUE TITLE
Files pane 'follows' R working directory

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4615]
It could be useful if the Files pane followed the R working directory -- e.g. if the user requested

```
setwd("~/scratch")
```

then the Files pane would also immediately navigate to that directory as well.

**Comment by jmcphers** [comment]
We have a button that does this:

![image](https://user-images.githubusercontent.com/470418/55908342-03dfe800-5b8e-11e9-976e-00cea2e746b1.png)

but an opt-in option might be nice too. Maybe under More -> a checkable option to track the R working directory?

![image](https://user-images.githubusercontent.com/470418/55908392-31c52c80-5b8e-11e9-8e35-7f75283e41b8.png)

**Comment by jmcphers** [comment]
Still think this is a good idea; adding `files pane` label
