### ISSUE TITLE
RStudio autocompletion adds parentheses around control flow

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4617]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS Mojave 10.14.4
    R Version       : R version 3.5.3 Patched (2019-03-11 r76245)

### Steps to reproduce the problem

Type e.g. `ne<TAB>`, and then select `next` from the set of autocompletion results.

### Describe the problem in detail

RStudio adds parentheses to the completed item, as though `next()` were a function.

### Describe the behavior you expected

No parentheses should be appended.

### Notes

RStudio is likely confused because "technically" break is a function handled specially by the R interpreter; e.g.

```
> is.function(`break`)
[1] TRUE
```

We should avoid adding parentheses around all of `repeat`, `next`, and `break`.

**Comment by dfalty** [comment]
Verified fixed 1.3.867
