### ISSUE TITLE
Update pandoc to 2.7.2 or newer

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4618]
https://pandoc.org/releases.html - 2.7.2

> appveyor.yml - use ghc 8.6.4. Fixes segfault issues on Windows (#5037).

Some RStudio users on Windows are still experiencing the segfault described the aforementioned bug; we should update to 2.7.2 in the patch release.

**Comment by ronblum** [comment]
Verified Pandoc versio 2.7.2 on Window 10 using RStudio Desktop 1.2.1526.
