### ISSUE TITLE
Extract from data viewer produces incorrect code when objects contain spaces

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#4620]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1335
    OS Version      : Windows 7
    R Version       : 3.5.3

### Steps to reproduce the problem
Run the following lines of code:
```r
`a 1` <- list(a = 1)
View(`a 1`)

`a 2` <- new.env()
assign("a", 1, envir = `a 2`)
View(`a 2`)
```
From the data viewer for either of the objects click the extract icon on the right. This gives in the console:
```r
a 1
a 2
a 2[["a"]]
```
Running any of these commands produces an error.

### Describe the problem in detail
Using the extract icon from the data viewer doesn't add back ticks around object containing spaces thus creating incorrect code. The example above is quite artificial but I ran into this when running a background job from a file containing spaces and saving the results to a results object in the global environment. 

### Describe the behavior you expected

Back ticks in the extracted code so it runs correctly.

**Comment by rich-rstudio** [comment]
verified in Version 1.3.897
