### ISSUE TITLE
Support for "Login with Azure Active Directory" for RStudio Server Pro instance in Azure

### ISSUE THREAD

**Issue by samssann** [rstudio/rstudio#4621]
Support for "Login with Azure Active Directory" for RStudio Server Pro instance in Azure.

Two enchancements are required:
1. Support "Login with Azure Active Directory" in the Azure Portral "Create a virtual machine" wizard
2. The output (the device login code) from pam_aad.so should be forwarded to RStudio web login page

# Wizard
Currently the wizard looks like this: 
![image](https://user-images.githubusercontent.com/19807339/55939189-d2c2ee80-5c45-11e9-9a41-8635a7b9e2e1.png)

The with Ubuntu 18.04 LTS image the wizard looks like this:
![image](https://user-images.githubusercontent.com/19807339/55939225-ebcb9f80-5c45-11e9-866e-322e60a89ab7.png)

# PAM
The authentication (`ssh`, `su` and `sudo`) is done via Azure AD and looks like this:
![image](https://user-images.githubusercontent.com/19807339/55939364-3a793980-5c46-11e9-8fcb-948dcd8c4a80.png)

When you try to login with your (Azure AD) user account in the RStudio web login the device code gets sent to some output(?) which the user has no access to. The login hangs for 15 minutes (the exact same time it gives you to authenticate after using e.g. su in bash terminal) after which is displays the "could not authenticate" error message. The devide code should be captured and displayed on the RStudio login page. This way the user could just go https://microsoft.com/devicelogin, insert the captured code and login.

**Comment by jmcphers** [comment]
Thanks for this suggestion! This repo however is for issues in the RStudio IDE itself. For feedback on the Azure instance, get in touch with <azure-feedback@rstudio.com> (we'e also passed it along to our team)
