### ISSUE TITLE
RStudio declares un-needed dependency on rprojroot for rmarkdown

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4628]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS Mojave 10.14.4
    R Version       : R version 3.5.3 Patched (2019-03-11 r76245)

### Steps to reproduce the problem

Remove the package `rprojroot`:

```
remove.packages("rprojroot")
```

and then try opening an R Notebook.

### Describe the problem in detail

RStudio prompts for installation of `rprojroot`:

![Screen Shot 2019-04-11 at 4 04 10 PM](https://user-images.githubusercontent.com/1976582/55998528-75de2d00-5c73-11e9-9369-958325e28e3d.png)

### Describe the behavior you expected

No prompting for `rprojroot` as it does not appear to be an `rmarkdown` dependency.

### Notes

```
> sort(tools::package_dependencies("rmarkdown", recursive = TRUE)$rmarkdown)
 [1] "base64enc" "digest"    "evaluate"  "glue"      "highr"    
 [6] "htmltools" "jsonlite"  "knitr"     "magrittr"  "markdown" 
[11] "methods"   "mime"      "Rcpp"      "stats"     "stringi"  
[16] "stringr"   "tinytex"   "tools"     "utils"     "xfun"     
[21] "yaml"  
```

**Comment by kevinushey** [comment]
There's also a couple packages missing from the dependency list that we might consider adding explicitly:

- glue
- magrittr
- stringi
- tinytex
- xfun

I believe these packages normally get auto-installed when e.g. `rmarkdown` is installed / updated, which is why we get away with not checking these. However, if someone were to somehow install `rmarkdown` but later remove one of these required packages, RStudio would fail to detect it.

**Comment by ronblum** [comment]
Confirmed that dependency on `rprojroot` is removed using RStudio Desktop 1.2.1522 on MacOS 10.14.6. 

Note: per discussion in #4658, the other dependencies will be in 1.3, using that ticket.
