### ISSUE TITLE
Cannot run RStudio as root user after updating to version 1.2.1335, ERROR:zygote_host_impl_linux.cc(89)] 

### ISSUE THREAD

**Issue by yulijia** [rstudio/rstudio#4631]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1335
    OS Version      :  Fedora 29
    R Version       :  3.5.3

### Steps to reproduce the problem
1. download the latest Rstudio for Fedora OS
2. install the rpm package
3. when I click the icon, it doesn't work. So I try to start RStudio at the command line.

### Describe the problem in detail

```
[root@localhost ~]$ rstudio
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[14257:14257:0412/093945.193417:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```
I need to run RStudio via root user on my laptop. There is no problem under the version 1.1.463

I check the difference between these two versions and think the problem may due to the new version use Chrome as the default browser. So I change my default browser to Firefox, however, the problem never goes away. 

![RStudio new version](https://imgur.com/uQEzguM.png)

![RStudio old version](https://imgur.com/7JWMHrl.png)

diagnostics report:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3071291/diagnostics-report.txt)

### Describe the behavior you expected

Hope I can start RStudio Desktop use root user and Firefox browser as usual

**Comment by pascaloettli** [comment]
It is clearly written: 

> Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

(apart, really not a good idea to work with root privileges)

**Comment by yulijia** [comment]
I guess the reason that RStudio 1.2.1335 doesn't work under root privileges without --no-sandbox parameter is that it uses Chrome as the browser (software interface),  I expected there is a function that I could change the default software interface to Firefox. I am not familiar with the RStudio source code but I know that I can downgrade the software to an older version to solve the problem (or add --no-sandbox in terminal command). But I really hope I could use the latest version of RStudio as usual and without typing the command line in the terminal.

**Comment by jmcphers** [comment]
You can set `--no-sandbox` in the `RSTUDIO_CHROMIUM_ARGUMENTS` environment variable. Does that do what you want?

**Comment by yulijia** [comment]
Hi @jmcphers ,

Thank you for the solution. Is there any way that I can set an environment variable in `.config/RStudio/desktop.ini` or other places, which could allow me to click the icon to start RStudio?

I add  the variable `export RSTUDIO_CHROMIUM_ARGUMENTS="--no-sandbox" in `.bashrc`. however, it only allows me to start RStudio via terminal.

Many thanks.

**Comment by kevinushey** [comment]
I think there are a relatively large number of users who do want to run RStudio as root, so we might want to consider automatically supporting this (ie: add `--no-sandbox` is the user is root).

Marking as v1.2-patch.

**Comment by hermidalc** [comment]
As a side note, and sorry to mention it here but this is the only issue I found that even mentions it... I was wondering what is this warning we constantly get when launching rstudio (as regular user or root doesn't matter):
```bash
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```
Should I open a separate issue about that?  I have ```qt5-qtwayland``` installed but when I set ```QT_QPA_PLATFORM=wayland``` I get a coredump :-/

**Comment by yulijia** [comment]
Hi @hermidalc, I am not sure how to fix it, but I know if I switch to Xorg as default gnome session, the warning message will disappear.
https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/

I suggest you open a new issue.

**Comment by hermidalc** [comment]
> Hi @hermidalc, I am not sure how to fix it, but I know if I switch to Xorg as default gnome session, the warning message will disappear.
> https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/
> 
> I suggest you open a new issue.

I did here #4686 and @kevinushey helped to figure it out. RStudio needs to bundle Qt5Wayland libraries along with the already bundled Qt5 since Linux distro Qt5Wayland libs might not be the right version. He’s opened a pull request #4687

**Comment by ronblum** [comment]
Verified using RStudio Desktop 1.2.1539 on Red Hat 7.6 and Ubuntu 18.04.2.
