### ISSUE TITLE
Adhere to the xdg specification for the configuration file

### ISSUE THREAD

**Issue by piegamesde** [rstudio/rstudio#4634]
Rstudio creates the folders `~/.rstudio` and `~/.rstudio-desktop` (actually there are some more, but I cannot safely say if rstudio or r created them, like `~/.R/rstudio`) in my home directory. This behavior is outdated and should not be done anymore. Instead, rstudio should use the respective folders for its data according to the [XDG base directory specifiaction](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

A first step in the right direction would be to move `.rstudio` to `$XDG_DATA_HOME/rstudio`. But ultimately, cache and configuration content will have to be split into the correct XDG folders.

**Comment by jmcphers** [comment]
Thanks for this suggestion! We are planning to do this in an upcoming release. You can track the issue here: https://github.com/rstudio/rstudio/issues/1607

**Comment by piegamesde** [comment]
Sorry for duplicating the issue. I only looked after something containing "XDG" in its title.

**Comment by jmcphers** [comment]
No worries, good to have another vote! Feel free to add upvotes/notes to the original. :-)
