### ISSUE TITLE
Tab width in console output doesn't follow settings

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4635]
**Steps to reproduce:**
* Set a custom tab width in RStudio options (Tools -> Global Options -> Code -> Editing -> General -> Tab width).
* Print some character string with tabs in the console, e.g.
```r
cat("1234567890\n\there")
```

**Expected behavior:** should print with the tab width that is configured.

**Actual behavior:** prints with 8 spaces per tab regardless of setting (on the plus side, the text is copied as tab and not as spaces).

**Comment by pascaloettli** [comment]
I might be wrong, but this option only applies to the "Source" pane, not the "Console" pane.

**Comment by jatkins23** [comment]
Has anyone found a solution to this? Just slightly annoying when writing error messages

**Comment by danielvartan** [comment]
I find this very annoying also. The console should follow the global/project tab setting.
