### ISSUE TITLE
[Windows] Whole-word selection picks extra spaces

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4638]
**Steps to reproduce:**
* Print something to the console that would have widely-spaced entries, e.g.
```r
data.frame(c1 = c(111, 222), c2 = c("this is meant to be a long line over here", "short line"))
```
* Try to select a whole word  (I'm not 100% sure how this is activated, I think double-click does it in some cases, but in others it needs kind of like a dragged click), for a word that is followed by spaces (e.g. try to select "222" after the command above is printed in console).

**Expected behavior:** should select "222" like in other OSes.

**Actual behavior:** on windows, selects "222" plus all the spacing before the next word.

**Comment by kevinushey** [comment]
I see the same behavior in the Chrome browser so this is apparently a Chromium behavior (bug?)

**Comment by kevinushey** [comment]
I also see this behavior in Notepad so I believe this is just how Windows highlights selections on double-click.
