### ISSUE TITLE
Consider support for customizing project names in .Rproj file

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#4641]
With the new cross-language integration features introduces in RStudio 1.2, it is becoming more likely to work in projects that support multiple languages, specially R and Python. I've worked on two projects that have a structure like:

```
/R/myproj.Rproj
/python/
```

For instance, https://github.com/apache/arrow/tree/master/r

However, RStudio shows as the project name the parent path, which for these projects would be `R`:

<img width="401" alt="Screen Shot 2019-04-12 at 12 32 21 PM" src="https://user-images.githubusercontent.com/3478847/56062023-f78b9480-5d1f-11e9-96ab-455a5cad3b48.png">

Could we consider adding support for setting an explicit project name in the `.Rproj` file instead of the parent folder? Maybe something like:

```
Version: 1.0

ProjectName: arrow
```

**Comment by salim-b** [comment]
Seems to be kind of a duplicate of https://github.com/rstudio/rstudio/issues/1909.

**Comment by jmcphers** [comment]
It *is* a duplicate of #1909.
