### ISSUE TITLE
.Call("printf") crashes RStudio

### ISSUE THREAD

**Issue by alandipert** [rstudio/rstudio#4643]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : macOS 10.13.6
    R Version       : 3.5.3

### Steps to reproduce the problem

Run `.Call("printf")` in the console.

### Describe the problem in detail

When I run `.Call("printf")` in the RStudio console, RStudio crashes. Running the same code in a "normal" R console at the command line does not crash the process, but instead reports an error:

```
> .Call("printf")
Error in .Call("printf") : C symbol name "printf" not in load table
```

**Comment by kevinushey** [comment]
Here's what I see in an R session:

```
> .Call("printf")
UHH
 *** caught segfault ***
address 0x8, cause 'memory not mapped'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

Note that the symbol can be found depending on what packages are loaded (`.Call("printf")` basically says to R, "try to find a symbol called `printf` and call it". E.g.

```
> getNativeSymbolInfo("printf")
$name
[1] "printf"

$address
<pointer: 0x7fff63449ec4>
attr(,"class")
[1] "NativeSymbol"

$package
DLL name: Rcpp
Filename: /Users/kevin/Library/R/3.5/library/Rcpp/libs/Rcpp.so
Dynamic lookup: TRUE

attr(,"class")
[1] "NativeSymbolInfo"
```

**Comment by alandipert** [comment]
Thanks for the additional information. Do I understand correctly that this is not a bug in either RStudio or R because it's expected behavior for `.Call` to crash R under various circumstances? (symbol not found, found symbol but called with bad arguments)

In case it's interesting, for me in RStudio `getNativeSymbolInfo("printf")` yields the following:

```
$name
[1] "printf"

$address
<pointer: 0x7fff65bac710>
attr(,"class")
[1] "NativeSymbol"

$package
DLL name: internet
Filename: /Library/Frameworks/R.framework/Resources/modules//internet.so
Dynamic lookup: TRUE

attr(,"class")
[1] "NativeSymbolInfo"
```

And in the terminal:
```
> getNativeSymbolInfo("printf")
Error in FUN(X[[i]], ...) : no such symbol printf
```
