### ISSUE TITLE
Sending many lines to terminal fails on Ubuntu

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4655]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1502
    OS Version      :  Ubuntu 18.04
    R Version       :  3.5.3

### Steps to reproduce the problem
 - Start a terminal inside RStudio.
 - Start R inside the terminal.
 - Send a 500 lines of code using Ctrl-C / Shift-Insert or Ctrl-Alt-Enter
 - For me, it tries to send them really fast but fails - i.e. the R code shows an error like some of it didn't make it through.
 - If I run the code 80 or so lines at a time, it works fine.

**Comment by pascaloettli** [comment]
And it will also fail in R running in terminal, outside of RStudio, right?

**Comment by kendonB** [comment]
I'm not 100% sure and I'm now travelling away from that machine. I don't believe there's any issue running large amounts of R code into vanilla Ubuntu terminals.

**Comment by pascaloettli** [comment]
I was facing this many times in R running in vanilla terminals. So to me it is a limitation in R, not RStudio

**Comment by kevinushey** [comment]
Here's a reproducible example -- write the code generating a large numeric vector to the clipboard with:

```
if (!requireNamespace("clipr")) install.packages("clipr")
output <- deparse(as.numeric(1:1E4))
clipr::write_clip(output)
```

Then, try to paste the clipboard text into a terminal running R. You should see an error like:

![Screen Shot 2019-04-17 at 9 01 57 AM](https://user-images.githubusercontent.com/1976582/56303020-e2cc4980-60ef-11e9-923b-d06d9e91e359.png)

Interestingly, on macOS, I can reproduce the issue if I'm running R within `iterm2` but not within the default `Terminal` application. The regular R terminal on Ubuntu seems okay as well.

**Comment by kendonB** [comment]
Can confirm this is still an issue in 1.3.842

**Comment by aahrens1** [comment]
Same issue with RStudio 1.3.1056 and MacOS Catalina 10.15.5
