### ISSUE TITLE
[Request] Throw file name and line on unexecutable build error

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4656]
Oftentimes, when I try to build a package through the button `Install and Restart` in the build pane, if the source code contains unparsable errors, I would get the error displayed right in the build pane, but it does not tell me which file is producing the error, e.g.
```
==> Rcmd.exe INSTALL --no-multiarch --with-keep.source <folder name>

* installing to library '<some_folder>'
* installing *source* package '<package name>' ...
** R
Error : '\s' is an unrecognized escape in character string starting ""\s"
ERROR: unable to collate and parse R files for package '<package name>'
* removing '<some_folder>/<package name>'
* restoring previous '<some_folder>/<package name>'
In R CMD INSTALL

Exited with status 1.
```

(This is from a line like `gsub("\s", "", "has space"`)

Would be nice if it would tell the exact file and line like in other types of build errors too.

**Comment by kevinushey** [comment]
IIUC this would be a request for R core since this is code being run in R itself rather than something that RStudio has control over.
