### ISSUE TITLE
No 'escape' key on iPad Pro keyboard for RStudio Server

### ISSUE THREAD

**Issue by raubreywhite** [rstudio/rstudio#4663]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.x
    OS Version      : iOS13
    R Version       : 

### Steps to reproduce the problem

Load RStudio server on iPad (Safari), with a physical keyboard that does not have an ESC key (e.g. Apple smart keyboard). Cannot use ESC key, because it doesn't exist.

### Describe the problem in detail

Cannot use the ESC key like we normally would in RStudio. This affects:

- VI mode
- Cancelling long running code
- Breaking out of code that has unmatched "

### Describe the behavior you expected

It would be nice to have some way to use ESC on a keyboard that doesn't have this button.

**Comment by gtritchie** [comment]
Still a problem with iPadOS 13.1. You can use Ctrl+[ as ESC when using (for example) VIM in the terminal, but that doesn't work anywhere else that I tried.

**Comment by gtritchie** [comment]
Opened an issue on Ace, this behavior repros on the Ace kitchen sink so not RStudio specific.
https://github.com/ajaxorg/ace/issues/4077

**Comment by ronblum** [comment]
Verified using iPad 13.3.1  connecting to RStudio Server 1.3.929, both with the <kbd>Esc</kbd> key and <kbd>Ctrl+[</kbd>.
