### ISSUE TITLE
error gutter annotations persist in R Markdown documents

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4668]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS Mojave 10.14.4
    R Version       : R version 3.5.3 Patched (2019-03-11 r76245)

### Steps to reproduce the problem

Create an R Markdown document containing the chunk:

`````
```{r}
Sys.sleep(10)
```
`````

Then, try to run the chunk by pressing the green Run button, then click the Stop button immediately after.

### Describe the problem in detail

The error gutter annotation is shown, but is never cleared after the document is edited later.

![Screen Shot 2019-04-18 at 4 34 35 PM](https://user-images.githubusercontent.com/1976582/56397287-e64af800-61f7-11e9-8746-50486dacea11.png)

![Screen Shot 2019-04-18 at 4 34 47 PM](https://user-images.githubusercontent.com/1976582/56397286-e64af800-61f7-11e9-8c31-6d8714aa1d82.png)

### Describe the behavior you expected

The gutter annotation should be cleared as soon as the associated line is edited.

**Comment by dfalty** [comment]
Verified fixed 1.3.673
