### ISSUE TITLE
pandoc missing in v1.2 preview builds for Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4669]
Ref: https://community.rstudio.com/t/rstudio-win-installer-for-rstudio-v1-2-1502-1-preview-does-not-install-pandoc-binaries/28874

**Comment by kevinushey** [comment]
Should be fixed with https://github.com/rstudio/rstudio/commit/7dbd41324ea206b3a2e5065f9e886680f3297db7 -- also cherry-picked to master.

**Comment by ronblum** [comment]
Verified with RStudio Desktop 1.2.1522-1 and 1.2.1539 on Windows 10.
