### ISSUE TITLE
Multiple cursors: Create a cursor at the next/prev matching text region

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#4671]
The [`multiple-cursors` package for Emacs](https://github.com/magnars/multiple-cursors.el) has an excellent feature where if you highlight a region of text and create a cursor, the new cursor will be created at the next identical block. Like in this animation, I've highlight `, `, and now all new cursors are made at each new instance of `, `.

![mc region](https://user-images.githubusercontent.com/3200601/56420886-3c489a00-62e3-11e9-904f-45bef82c18cb.gif)

Notice that this is not limited to recognising a name or other syntatic element, it's just a text search. There are also keyboard shortcuts to skip a match and proceed to the next one. If no text region is selected, then a cursor will be created above/below the current cursor location.

This is a very very handy feature that RStudio would benefit from.

**Comment by hyiltiz** [comment]
Even more simplistic approach of VSCode that simply presses Alt to duplicate a cursor into a direction indicated by the arrow key press should suffice; this is very helpful in creating csv files, list of content, and templates like that, and is also useful to change one format into another (like csv to yaml) without having to go through some external tools.
