### ISSUE TITLE
enhancement: colorize/highlight/gather all TODO, FIXME or IMPORTANT comments

### ISSUE THREAD

**Issue by verajosemanuel** [rstudio/rstudio#4673]
Usually, for smaller projects the common behaviour is to use a lot of comments in the code. Not every project needs complex issue tracking and big code control software. Besides, sometimes is quicker to look at the code.

Keywords as TODO, FIXME, or IMPORTANT are very useful to remember some days after you wrote a lot of code what to do next or as a guide for the coming days in the same project.

The feature should highlight specific words (TODO and such) in a way that can be easily detected looking at code with no need of using the integrated search. 

Take ¨Better-comments¨  VScode Addin as an example of this feature:

[https://github.com/aaron-bond/better-comments](https://github.com/aaron-bond/better-comments)

In a step further, all TODOs could be gathered in a table or document to have global view of pending work. Take ¨TODO-SHOW¨ Atom Addin as an example of this feature:

[https://atom.io/packages/todo-show](https://atom.io/packages/todo-show)

**Comment by GegznaV** [comment]
If keywords TODO and FIXME are written as the first word after the comment symbol `#` in R code, they are highlighted.
At the moment, R package ["todor"](https://github.com/dokato/todor) finds TODO, etc. comments and collects to "Markers" tab.
Does the package fit your needs?

**Comment by verajosemanuel** [comment]
Yes, package TODOr is ok, but this feature is a good one to be included out-of-the-box
Thanks

**Comment by theendlessriver13** [comment]
> If keywords TODO and FIXME are written as the first word after the comment symbol `#` in R code, they are highlighted.


I think this is already quite useful but I am trying to customize this in my theme.
I am trying to changes the `.rstheme` file so the `# TODO` has a yellow background and can be found much easier while scrolling to the code.
The code highlighting regex already has the keywords `TODO|FIXME` so this should be fine. The Problem is the `TODO` belongs to the object`.ace_keyword.ace_operator`. This object also includes `(`, `)`, `$`, `=`, `*`, `+`, `~`, `/` and `<-`.
Obviously I don't want to change those. I seems that there has to be a new object just for those two. But I don't know how to implement this.
Also it is hard for me to understand why `TODO` is classified as an operator?

**Comment by v-vieira** [comment]
> 
> 
> > If keywords TODO and FIXME are written as the first word after the comment symbol `#` in R code, they are highlighted.
> 
> I think this is already quite useful but I am trying to customize this in my theme.
> I am trying to changes the `.rstheme` file so the `# TODO` has a yellow background and can be found much easier while scrolling to the code.
> The code highlighting regex already has the keywords `TODO|FIXME` so this should be fine. The Problem is the `TODO` belongs to the object `.ace_keyword.ace_operator`. This object also includes `(`, `)`, `$`, `=`, `*`, `+`, `~`, `/` and `<-`.
> Obviously I don't want to change those. I seems that there has to be a new object just for those two. But I don't know how to implement this.
> Also it is hard for me to understand why `TODO` is classified as an operator?

I find it!
To change only the words "TODO" and "FIXME" in comments you must add the lines below to CSS of your theme:
```
.ace_comment.ace_keyword.ace_operator {
  color: #FF0000 !important;
  background:#FFFD00;
}
```
In the example above the background is yellow and text is red, just change to your preference.
Actually, I don't know if the '!import' is necessary. To work you should not delete the `.ace_keyword.ace_operator`, just add the code above.

**Comment by jzadra** [comment]
@v-vieira's solution works great!

Is there any way to add additional keywords besides just `TODO|FIXME`? Is there a file with the regex for the keywords somewhere?
