### ISSUE TITLE
Printing to printer

### ISSUE THREAD

**Issue by therobmeister** [rstudio/rstudio#4678]
Hi

Why is there no option to print scripts directly to printer?   The only option I have (1.1.419 on Windows 10) allows printing to pdf only.   I realise scripts are just text files so there are other ways to do this but not within RStudio.

I've seen in various places that this issues has been requested before but not sure what the latest on it it.    

Thanks

**Comment by pascaloettli** [comment]
I can directly print out either from Linux or MacOS, with either version `1.1.463` or `1.2.1502`. I don't have a Windows machine to test whether it is Windows-related or your computer-related.

**Comment by therobmeister** [comment]
That's fixed it at home - thanks.   No upgrade of R required - just Rstudio.   Now to see if I can convince people at work to upgrade to latest.

**Comment by jmcphers** [comment]
Glad it's better with the new version!
