### ISSUE TITLE
RStudio v 1.2.1335 does not run

### ISSUE THREAD

**Issue by kleanthisk10** [rstudio/rstudio#4679]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1335 
    OS Version      : Windows 10
    R Version       : 3.5.0
    Processor: Intel(R) Atom(TM) CPU Z3735F
    System Type: 32-bit operating system, x64-based processor

The following error appears after installing the new version of RStudio.

![εικόνα](https://user-images.githubusercontent.com/14178387/56460119-4e3f4100-63a6-11e9-842f-6b1fa8fec576.png)

I had no problem with previous versions of RStudio.

**Comment by gtritchie** [comment]
RStudio 1.2 requires 64-bit Windows, but unfortunately our installer doesn't warn you. See #3167 

You can continue using RStudio 1.1.463 on 32-bit Windows. It can be installed from https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio.
