### ISSUE TITLE
Rstudio Server 1.2.1335 libssl version error in Ubuntu 19.04

### ISSUE THREAD

**Issue by dongzhuoer** [rstudio/rstudio#4681]
Rstudio Server wants `libssl.so.1.0.0`, which is not available in Ubuntu 19.04

I use a Docker of Ubuntu 18.04, install libssl1.0.0, then copy `libssl.so.1.0.0` and `libcrypto.so.1.0.0` to my system. Finally it works.

**Comment by jmcphers** [comment]
Which version of RStudio Server did you install? There is a version specifically built for Ubuntu Bionic which should also work on Ubuntu 19 (it uses OpenSSL 1.1).

**Comment by dongzhuoer** [comment]
1.2.1335

**Comment by pascaloettli** [comment]
@dongzhuoer Which version did you install? For [Debian 8 / Ubuntu](https://download2.rstudio.org/server/trusty/amd64/rstudio-server-1.2.1335-amd64.deb) or for [Debian 9+](https://download2.rstudio.org/server/debian9/x86_64/rstudio-server-1.2.1335-amd64.deb)?
I am on Ubuntu 18.04, I get the same error than yours with the latter, but not with the former. Please try with the former.

**Comment by dongzhuoer** [comment]
I tried both just now. The former said `error while loading shared libraries: libssl.so.1.0.0` and the latter said `error while loading shared libraries: libssl.so.1.0.2`.

By the way, Ubuntu 19.04 is Debian 10, `buster/sid`.

**Comment by pascaloettli** [comment]
I see. As `rstudio 1.2.1502` is linked against `libssl.so.1.1` in my computer, I mistakenly thought it was the same for `rstudio-server 1.2.1335`, but I was wrong:

> ldd /usr/lib/rstudio-server/bin/rserver
> 	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f794b42f000)

**Comment by jmcphers** [comment]
@dongzhuoer I think what you need is the Ubuntu Bionic build. Does that do what you want?

https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.1335-amd64.deb

**Comment by pascaloettli** [comment]
I missed this version. Sorry for my useless remarks above.

**Comment by dongzhuoer** [comment]
Yes, it does solve the problem. Thank you so much!

**Comment by dongzhuoer** [comment]
Yes, it does solve the problem. Thank you so much!
