### ISSUE TITLE
Most recently opened project not restored at startup

### ISSUE THREAD

**Issue by hermidalc** [rstudio/rstudio#4684]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Linux (Fedora 29)
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Check Global Options -> "Restore most recently opened project at startup"
2. Open a project
3. Close and then restart RStudio

The most recently opened project isn't restored.

### Describe the problem in detail

RStudio doesn't restore your most recently opened project even though you have the option checked in Global Options

### Describe the behavior you expected

The most recently opened project to be restored.

**Comment by kevinushey** [comment]
Can you double-check that your user account has read + write permissions on all folders within `~/.rstudio-desktop`? (RStudio attempts to save user state into this folder and some of these issues come down to an inability to read / write into this directory)

**Comment by hermidalc** [comment]
> Can you double-check that your user account has read + write permissions on all folders within `~/.rstudio-desktop`? (RStudio attempts to save user state into this folder and some of these issues come down to an inability to read / write into this directory)

I have rw access to everything under ~/.rstudio-desktop:
```bash
$ la ~ | grep rstudio
drwxr-xr-x. 19 hermidalc hermidalc    4096 Apr 22 12:38 .rstudio-desktop

$ la ~/.rstudio-desktop
total 1216
drwxr-xr-x. 19 hermidalc hermidalc   4096 Apr 22 12:38 .
drwx------. 35 hermidalc hermidalc   4096 Apr 21 17:17 ..
-rw-r--r--.  1 hermidalc hermidalc   1233 Apr 22 12:38 addin_registry
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 22 12:38 client-state
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 20 08:59 ctx
drwxr-xr-x.  4 hermidalc hermidalc   4096 Apr 10 14:32 dictionaries
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 10 14:32 explorer-cache
-rw-r--r--.  1 hermidalc hermidalc 371202 Apr 22 12:41 history_database
-rw-r--r--.  1 hermidalc hermidalc 768035 Apr 22 11:02 history_database.1
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 10 14:32 log
drwxr-xr-x.  6 hermidalc hermidalc   4096 Apr 10 14:32 monitored
drwxr-xr-x.  5 hermidalc hermidalc   4096 Apr 20 15:34 notebooks
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 22 12:38 pcs
-rw-r--r--.  1 hermidalc hermidalc    486 Apr 20 08:59 persistent-state
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 10 14:32 presentation
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 10 14:32 profiles-cache
drwxr-xr-x.  5 hermidalc hermidalc   4096 Apr 15 15:59 projects
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 15 15:59 projects_settings
-rw-r--r--.  1 hermidalc hermidalc    425 Apr 22 12:38 rmd-outputs
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 10 14:32 rversion-settings
-rw-r--r--.  1 hermidalc hermidalc     27 Apr 22 12:38 saved_source_markers
drwxr-xr-x.  3 hermidalc hermidalc   4096 Apr 10 14:32 sessions
drwxr-xr-x.  4 hermidalc hermidalc   4096 Apr 22 12:38 sources
drwx------.  2 hermidalc hermidalc   4096 Apr 10 14:32 viewer-cache
drwxr-xr-x.  2 hermidalc hermidalc   4096 Apr 20 08:59 viewer_history
```
One thing I found that might help is the file ```~/.rstudio-desktop/projects_settings/last-project-path``` is empty even though the "Restore most recently opened project at startup" is setting is checked:
```bash
$ la ~/.rstudio-desktop/projects_settings
total 16
drwxr-xr-x.  2 hermidalc hermidalc 4096 Apr 15 15:59 .
drwxr-xr-x. 19 hermidalc hermidalc 4096 Apr 22 12:38 ..
-rw-r--r--.  1 hermidalc hermidalc    0 Apr 22 12:38 last-project-path
-rw-r--r--.  1 hermidalc hermidalc    0 Apr 22 11:53 next-session-project
-rw-------.  1 hermidalc hermidalc  132 Apr 15 15:59 project-id-mappings
-rw-r--r--.  1 hermidalc hermidalc    0 Apr 22 12:38 switch-to-project
-rw-r--r--.  1 hermidalc hermidalc    1 Apr 15 15:55 update-pkg-install-default
```

**Comment by kevinushey** [comment]
Thanks for checking. For me, that directory gets refreshed each time RStudio is closed, with the last-used project (+ the other settings).

Can you also share a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report)? In particular, I wonder if there's anything relevant in the error logs.

**Comment by hermidalc** [comment]
> Thanks for checking. For me, that directory gets refreshed each time RStudio is closed, with the last-used project (+ the other settings).
> 
> Can you also share a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report)? In particular, I wonder if there's anything relevant in the error logs.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3104311/diagnostics-report.txt)

Are you using Linux?  And Fedora?

**Comment by kevinushey** [comment]
I was testing on Ubuntu 18.04 rather than Fedora, but I don't think the platform should make a difference here. (I could, of course, be wrong)

It looks like you're using Anaconda R -- does it make any difference if you use the default version of R as provided by your package manager?

**Comment by hermidalc** [comment]
> I was testing on Ubuntu 18.04 rather than Fedora, but I don't think the platform should make a difference here. (I could, of course, be wrong)
> 
> It looks like you're using Anaconda R -- does it make any difference if you use the default version of R as provided by your package manager?

Installed the system R (and dependencies) on Fedora and yep now it works.  You also see that ```~/.rstudio-desktop/projects_settings/last-project-path``` is populated.  

What's very interesting is if I go back to using my Anaconda environment and R, launch RStudio and create a new project and then close and re-launch it restores this last project and works as expected.  So it could be something RStudio was depending on in the system R dependencies that Anaconda wasn't providing it it's R dependencies.

Maybe I should've used the Anaconda RStudio distribution,  but they don't have the latest RStudio and if I remember correctly when I tried it it was missing a lot of fonts etc so the interface looked different.
