### ISSUE TITLE
Non-R rmarkdown chunks execute upon opening of project

### ISSUE THREAD

**Issue by ndiquattro** [rstudio/rstudio#4688]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1502
    OS Version      : 10.14.4
    R Version       : 3.5.2

### Steps to reproduce the problem
1. Have a non-R chunk in an rmakdown file somewhere in a project
2. Open project in RStudio
3. Sometimes the code is just executed, sometimes when trying to `install.packages()` or refresh the package pane in R studio

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/7445920/56528286-c3745880-6503-11e9-90fe-68f0be514e71.png)

It also occurs with STAN chunks where Rstudio tries to compile / quit the model a bunch.

### Describe the behavior you expected

I would expect code chunks to not execute on their own :)

**Comment by kevinushey** [comment]
Are you using Packrat with this project?

**Comment by ndiquattro** [comment]
@kevinushey yes!
