### ISSUE TITLE
Sending Python to Console Always Expands History Pane

### ISSUE THREAD

**Issue by dylanjm** [rstudio/rstudio#4692]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1502
    OS Version      : macOS Sierra Version 10.12.6
    R Version       : 3.5.2

### Steps to reproduce the problem

* Open Rstudio
* Ensure `library(reticulate)` is installed on your machine
* Open a `.py` file in Rstudio
* Highlight a portion of python code you'd like to run
* Hit `cmd + ENTER` to launch python REPL and send it to the REPL
* History pane automatically opens up from minimized position
* Minimize history pane again
* Run another line of python
* History pane automatically opens up again

### Describe the problem in detail

As mentioned above, whenever I run a python command using `cmd + ENTER` it will automatically open the history pane. It doesn't matter if the REPL is already open or the REPL is launched on command. 

### Describe the behavior you expected

Same behavior as sending R to the console. History pane remains closed. 

### Session Info

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2    Matrix_1.2-16     tools_3.5.2       Rcpp_1.0.0        reticulate_1.11.1 grid_3.5.2       
[7] jsonlite_1.6      png_0.1-7         lattice_0.20-38 
```

**Comment by melissa-barca** [comment]
Verified this has been fixed in the 1.4 dailies.
