### ISSUE TITLE
Environmental variable "QT_PLUGIN_PATH" conflict for RStudio 1.2 on Win10

### ISSUE THREAD

**Issue by madlogos** [rstudio/rstudio#4694]
### System details

    RStudio Edition : Desktop (Open source)
    RStudio Version : 1.2.1335 stable
    OS Version      : Windows 10 x64
    R Version       : 3.5.3

### Steps to reproduce the problem

1. You have some applications (e.g., Anaconda) that registered the variable `QT_PLUGIN_PATH` in environment beforehand.
2. Install RStudio 1.2, either unzipping the tarball or installing the .exe.
3. The RStudio.exe won't launch and pops an error "This application failed to start because no Qt platform plugin could be initialized".

### Describe the problem in detail

Refer to [this thread](https://community.rstudio.com/t/rstudio-1-2-zip-version-fails-to-launch-for-no-qt-platform-plugin-could-be-initialized-on-win10-x64/29131) on RStudio Community.

### Describe the behavior you expected

It is now mitigated by resetting the environmental variable. But I expect a more elegant solution to minimize the impacts to other softwares.

**Comment by jmcphers** [comment]
Thanks for filing this! I'm removing the bug label because I think respecting `QT_PLUGIN_PATH` is, technically the right thing for RStudio to do -- it is expected behavior for Qt based applications. Not respecting this variable will break some usage, even if it fixes the usage described above. 

Do you have a proposal for a more elegant approach? (One I thought of was trying to rename this variable for our use, e.g. `RSTUDIO_QT_PLUGIN_PATH`, so it would still be possible to point at a different Qt plugin path for RStudio even if we stopped respecting the standard env var.)

**Comment by madlogos** [comment]
I tried appending RStudio plugin directory to `QT_PLUGIN_PATH` but it did not work. Only putting it as the first entry could make RStudio run. But in Win 10, by design, multiple entries for env var is allowed anyway.

I don't know how `QT_PLUGIN_PATH` typically works. Is it possible for RStudio to accept multiple entries in the var and automatically recognize the correct match? If this brings in new issues, perhaps a new var is a better choice.

**Comment by kevinushey** [comment]
IMHO setting QT_PLUGIN_PATH globally as you have is a bit of an anti-pattern, as it means _all_ applications on your system will now look in that path for Qt plugins (regardless of what version of Qt that particular application is using). I can understand it's a required workaround for some cases, but if possible I'd recommend only setting that environment variable as required and not globally.

If required, you could create your own shortcut / batch script that launched RStudio with QT_PLUGIN_PATH set, e.g.

https://superuser.com/questions/424001/launch-windows-program-with-custom-environment-variable

**Comment by Ghostkeeper** [comment]
It's a bit of a security issue too, isn't it? Running into the same problem with an application I'm developing...

**Comment by munkey01** [comment]
This issue should be reopened as it is unresolved. Currently, I am dealing with the same issue; is it possible to implement @jmcphers suggestion of using a less generic env variable name? That way we can avoid conflicts?
