### ISSUE TITLE
RStudio Desktop, Server & Cloud - ".q" file extensions cause big slow down if 'Index Source Files' turned on.

### ISSUE THREAD

**Issue by antspengy** [rstudio/rstudio#4696]
Hi

### System details
    RStudio Edition : Server (Open source) and Desktop and also Rstudio.Cloud
    RStudio Version : 1.1463, and 1.2.1335 and current preview (v1.2.1511-1)
    OS Version      : Ubuntu 16.04 (on 3 different servers) and Windows 10 and whichever OS that RStudio Cloud uses
    R Version       : 3.5.2 and 3.5.3

### Steps to reproduce the problem
1. Create a new project.  
2. Create a file of a reasonable size (say 50-100MB of random data) and save it to the project folder with the extension ".q".  (see reproducible code at bottom for an example).
3. Run some simple code (e.g. 1+1) and you may already notice a multi-second delay in getting a laggy response from RStudio.
3. Close the project and reopen it.  You'll probably experience a significant slowdown in R studio server as it loads the project, particularly in the loading of the 'Files' and 'Environment' tabs.  The bigger the size of the file with a .q extension, , the bigger the slowdown.
4. The slowness persists whenever you open this project until you either:
- rename the file extension to something other than '.q', or
- turn off 'Index Source Files' in Tools > Project Options > Code Editing.  

The slowness doesn't exist in any other projects that don't contain a '.q' file.

### Describe the problem in detail
I've encountered this problem multiple times over the past month when I started saving files with a ".q" extension in a particular project.  The reason I'm using that file extension is because I'm using the new 'qs' package (https://github.com/traversc/qs).  Some of the files are several hundred MBs, and the issue seems to get worse as the files get bigger.

It took lots of trial and error to work out what the cause was (including deleting .Rproj.user folders and pretty much every other R setting file or folder I could find) until I finally narrowed it down to the ".q" extension.    It goes away instantly if you change the file to a different extension or you turn off 'Index Source Files'.  

I've replicated the issue on R  Studio Cloud, R Studio Desktop, and R Studio Server.  It seems to spawn a rogue rstudio process that I've had to kill manually in both linux and windows, so I'm guessing it's just something about the ".q" extension that is maybe messing up some C++ code.  I can't even reopen the project with the code below in Rstudio.cloud (it just never finishes loading).

Here's some R code to replicate the issue after you start a new project:
```
library(readr);

problem_file <- as.data.frame(rnorm(5e6))
write_csv(problem_file, "this_file_is_a_problem.q")
1+1
```

### Describe the behavior you expected
Ideally R Studio should behave normally for a project even if it has a big file with a ".q" file extension in it :) 

### Log and Diagnostic Data
Here's the output of sessionInfo() from my RStudio Server on Ubuntu 16.04:

> R version 3.5.3 (2019-03-11)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.6 LTS
> 
> Matrix products: default
> BLAS: /usr/lib/libblas/libblas.so.3.6.0
> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] readr_1.3.1
> 
> loaded via a namespace (and not attached):
>  [1] compiler_3.5.3  R6_2.4.0        hms_0.4.2       tools_3.5.3     pillar_1.3.1    rstudioapi_0.8  tibble_2.1.1    Rcpp_1.0.1      crayon_1.3.4   
> [10] packrat_0.4.9-3 pkgconfig_2.0.2 rlang_0.3.4 

When I look at the log files generated by R studio, i see a lot of processes with long wait times, usually named something like "get_events" and that have a response of "undefined".

I couldn't see anything particularly relevant in the Diagnostics reports except possibly for this line, which I believe was logged when I think I tried to open one of the .q files in R Studio while it was lagging really slowly:

> 24 Apr 2019 06:56:16 [rsession-XXXXX] ERROR system error 32 (The process cannot access the file because it is being used by another process) [path=D:/XXXXXXXXX/R/home_projects/test_of_q_files/big_file.q, src-file=D:/XXXXXXXXXs/R/home_projects/test_of_q_files/big_file.q]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::open_r(rstudio_boost::shared_ptr<std::basic_istream<char> >*) const C:\Users\Administrator\rstudio\src\cpp\core\FilePath.cpp:1092; LOGGED FROM: void rstudio::session::modules::code_search::{anonymous}::SourceFileIndex::updateIndexEntry(const rstudio::core::FileInfo&) C:\Users\Administrator\rstudio\src\cpp\session\modules\SessionCodeSearch.cpp:867

Hope this makes sense, thanks for your help!

**Comment by kevinushey** [comment]
This is because RStudio treats `.q` files as though they were regular R files:

https://github.com/rstudio/rstudio/blob/7d4e88dfde4305c228caadc1ed80a8ed5c95d286/src/cpp/session/modules/SessionCodeSearch.cpp#L938-L952

For context: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#DOCF13

> Extensions .S and .s arise from code originally written for S(-PLUS), but are commonly used for assembler code. Extension .q was used for S, which at one time was tentatively called QPE.

That said, I don't think there's any reason to continue assuming `.q` files are files containing R code as this point.

**Comment by kevinushey** [comment]
Unfortunately for now the only workaround is to rename the file extension to something else :-/
