### ISSUE TITLE
Scalling issues (v. 1.2.1335) in Windows 10

### ISSUE THREAD

**Issue by LuisLauM** [rstudio/rstudio#4697]
I have installed the last version (1.2.1335). However, it seems like some scalling problem: Blurred view and icons out of place. 

I tried unistalling, deleting temporal files and reinstalling, but the problems continue.

Mi PC: Dell 5510. Windows 10 1809 64 bits. R 3.5.3. RStudio 1.2.1335.

**Comment by rich-rstudio** [comment]
Hi @LuisLauM , thank you for reporting this issue. I was not able to reproduce the issues you are describing. 

Are you using an external monitor?

**Comment by kevinushey** [comment]
This support article may also be helpful: https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by LuisLauM** [comment]
@kevinushey Yes! I have had to use the Options --> General tab--> Advanced tab --> OS integration --> Rendering engine --> Software. That works!

**Comment by kevinushey** [comment]
Great! Glad to hear it :-)

It's unfortunate, but the latest version of RStudio does have some of these kinds of issues on permutations of hardware. If you need hardware rendering, you can try double-checking that your display drivers are all up-to-date; on occasion that does fix things.
