### ISSUE TITLE
Download pages for RStudio Windows IDE should specify 64-bit requirement

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#4703]
Download pages for 1.2+ IDE describe Windows download as being for "Windows 7+". We've had some cases of users download and trying to run on 32-bit Windows.

It would be more accurate and helpful if following pages said something like "Windows 7+ 64-bit".

https://www.rstudio.com/products/rstudio/download
https://www.rstudio.com/products/rstudio/download/preview/

Could also mention need for 64-bit R, but not sure where that would be most appropriate.

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio-com/commit/64cc0b3ee698d6784320771de5dc6f6d5a7137aa
