### ISSUE TITLE
RStudio Server on Ubuntu/Debian shall have zip and unzip as a depencency

### ISSUE THREAD

**Issue by pachamaltese** [rstudio/rstudio#4708]
otherwise when you try to download two or more zip files it returns

```
Error in system(createZipCommand, intern = TRUE) :error in running command
```

Running `sudo apt install zip` install both `zip` and `unzip` and resolves the problem.

**Comment by jmcphers** [comment]
This is a dependency of R, not RStudio; Debian policy does not suggest adding transitive dependencies.
