### ISSUE TITLE
"rendered site" publishing without rendering has unexpected error/UI issues

### ISSUE THREAD

**Issue by davebulaval** [rstudio/rstudio#4713]
> Exact error message as the closed issue #3754 but with a file path with UTF-8 characters like `é`, `ê`, ̀è`.

### System details
```
RStudio Edition : Desktop
RStudio Version : 1.2.1074
OS Version      : macOS 10.14
R Version       : 3.5.1
```

### Steps to reproduce the problem

1. Create a shiny project in a directory with UTF-8 character
2. Try to publish

### Describe the problem in detail
An error message is displayed noting that the IDE "Could not find files to deploy" and "Error occurred while executing method". The "Publish" window is also displayed and has the same issues as described in #3752 and #3754.

![image](https://user-images.githubusercontent.com/24845694/56814395-1eac9080-680d-11e9-9f00-1e6ec952d847.png)

### Describe the behavior you expected
Given the expectation of a rendering, I expected a clear error explaining why I cannot publish my content and no publishing window.

Filing this separately from #3754 since the error behavior is different.

> The workaround I found is to use an file path without UTF-8 characters.

**Comment by ronblum** [comment]
@davebulaval Thank you for reporting this issue. I haven't been able to reproduce this, but there's a good chance it's due to my setup. I'll elevate this to a bug, as we've seen other issues—including the one you referenced—with directories and files with UTF-8 characters.

**Comment by davebulaval** [comment]
@ronblum this was also my hypothesis.
