### ISSUE TITLE
shiny::fileInput doesn't respect accept MIME type

### ISSUE THREAD

**Issue by alandipert** [rstudio/rstudio#4718]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS 10.14.4
    R Version       : 3.5.2

### Steps to reproduce the problem

The following Shiny application displays a file chooser:

```R
library(shiny)

ui <- fluidPage(
  fileInput("fileChooser", "Upload a Processed File", accept = "text/plain") 
)

server <- function(input, output, session) {
}

shinyApp(ui, server)
```
In the RStudio browser file chooser dialog, files of every type can be chosen. In the other browsers I've tested (Firefox 66 macOS, Chrome 73 macOS) only `text/plain` files can be chosen.

### Describe the problem in detail

The RStudio browser's file chooser dialog does not appear to respect the `accept` MIME type, as other browsers appear to.

### Describe the behavior you expected

I would expect the RStudio browser to behave the same way as Firefox and Chrome.

Note that this issue was originally reported by @DarioS at https://github.com/rstudio/shiny/issues/951

**Comment by cderv** [comment]
For reference, community question related to this 
https://community.rstudio.com/t/r-markdown-param-input-file-type-filter/86816

**Comment by DarioS** [comment]
It's tagged with _bug_ and _reproducible_, so I'll add some activity to it to keep it opened.
