### ISSUE TITLE
RStudio Desktop crashes with "Parent terminated" error

### ISSUE THREAD

**Issue by yanglinsensjtu** [rstudio/rstudio#4722]
### System details

    RStudio Edition : 
    RStudio Version : Version 1.2.1335
    OS Version      : 4.19.36-1-MANJARO
    R Version       : R version 3.6.0

### Describe the problem in detail
the R works well, however after I update the Rstudio for last version, the rstudio became abnormal. the rstudio frequently crash down, and the log file show "29 Apr 2019 06:27:28 [rsession-lsyang] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333
29 Apr 2019 06:27:44 [rsession-lsyang] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333
29 Apr 2019 06:27:50 [rsession-lsyang] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333
29 Apr 2019 06:28:36 [rsession-lsyang] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333
29 Apr 2019 06:28:47 [rsession-lsyang] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333
29 Apr 2019 06:28:57 [rsession-lsyang] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333
29 Apr 2019 06:33:01 [rsession-lsyang] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/session/SessionMain.cpp:1333" 
### Describe the behavior you expected
I hope to install the version before RStudio
Version 1.2.1335, I think the last version is more stable.

**Comment by yanglinsensjtu** [comment]
> sessionInfo() 
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.5.so

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0

**Comment by eustin** [comment]
This is occurring with me, too!

> > sessionInfo()
> R version 3.5.2 (2018-12-20)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 19.04
> 
> Matrix products: default
> BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0
> 
> locale:
>  [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8       
>  [4] LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
>  [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.5.2 tools_3.5.2

**Comment by ronblum** [comment]
@yanglinsensjtu Thanks for reporting this. We don't currently support Majaro; the[ list of supported platforms](https://www.rstudio.com/about/platform-support/) is available at https://www.rstudio.com/about/platform-support/. We'll check this out as we work on future development of RStudio.

**Comment by Wheresmytowel** [comment]
The same seems to be happening to me as well with RStudio Desktop version 1.2.1335 Build 4 flac 3432 on Ubuntu 18.04.2 LTS:

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0  
```

**Comment by kevinushey** [comment]
Do things work better if you switch to software rendering? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by Wheresmytowel** [comment]
Update: switching to software rendering as suggested [here](https://community.rstudio.com/t/rstudio-crash-on-ubuntu-while-updating-packages-something-to-do-with-jenkins-which-i-dont-use/29888) and described [here](https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors) seems to have solved the problem for me.

**Comment by SteveBronder** [comment]
Oh nvm it looks like there is something more similar to my error in progress below

https://github.com/rstudio/rstudio/issues/9854

**Comment by aocalderon** [comment]
Same here...

`> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0
`

**Comment by ronblum** [comment]
We now have daily builds for Ubuntu 22.04. These haven't been released yet, and are meant for testing and development purposes, but they're available for:
- [Future Prairie Trillium 2022.02 patch](https://dailies.rstudio.com/rstudio/prairie-trillium/desktop/jammy/): https://dailies.rstudio.com/rstudio/prairie-trillium/desktop/jammy/
- [Upcoming Spotted Wakerobin 2022.06 release](https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/jammy/): https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/jammy/
