### ISSUE TITLE
R 3.6.0 - Fatal error with .Rprofile

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#4723]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : Mac OS
    R Version       : 3.6.0

### Steps to reproduce the problem

Place the following in your `.Rprofile` with `usethis::edit_r_profile()`:

```
if(interactive()) {
  library(prompt)

  set_prompt(function(...){
    paste0(
      "[", git_branch(), "]> "
    )
  })
}
```

then restart RStudio.

### Describe the problem in detail

Immediately upon opening, I get this screen:

![Screen Shot 2019-04-29 at 9 03 43 AM](https://user-images.githubusercontent.com/19150088/56897916-bc969a00-6a5d-11e9-85d3-e2feda4bd67f.png)

![Screen Shot 2019-04-29 at 9 04 29 AM](https://user-images.githubusercontent.com/19150088/56897933-d0da9700-6a5d-11e9-9f9f-951aceee14cd.png)

I think the key here is `Error: option error has NULL value`

This shows up in other places as well, like knitr. I don't have an easily reproduce example for that quite yet, but you can see this twitter thread for a few complaints: https://twitter.com/romain_francois/status/1122782045653164034

Also cc @romainfrancois since it happened to him too.

**Comment by DavisVaughan** [comment]
Perhaps this has to do with: https://github.com/gaborcsardi/prompt/blob/e5248b5b498958a3cfad5308eac505ebbcc3d16a/R/package.R#L22

**Comment by DavisVaughan** [comment]
You can also trigger this with an .Rprofile of:

```
if(interactive()) {
  options(error = utils::recover)
}
```

**Comment by romainfrancois** [comment]
Thanks @DavisVaughan for reporting this here. I think you're right and `prompt` is just an innocent bystander, and `options(error=)` is the problem. I can reproduce the same problem with `options(error = utils::recover)` or `options(error = rlang::entrace)`

**Comment by DavisVaughan** [comment]
Ah, I found the commit in R 3.6 that changed things:
https://github.com/wch/r-source/commit/96bf99047580040fb4771510ba6d07ee690ca90b#diff-178a6fb02209db6ee641b179edce6eff

**Comment by mjsteinbaugh** [comment]
+1 that I'm seeing this error pop up with my [`.Rprofile`](https://github.com/mjsteinbaugh/dotfiles/blob/master/Rprofile)

**Comment by jmcphers** [comment]
A temporary workaround is to set `rstudio.errors.suppressed` to `FALSE` in your `.Rprofile` as well.

**Comment by Lornebradia** [comment]
I am still getting this error. 

Essentially, running the default rmarkdown document with the following chunk: 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

will lead RStudio to crash, printing _repeatedly_ on the console the error message: 

```
Error: option error has NULL value
Error: option error has NULL value
Error: option error has NULL value
Error: option error has NULL value
```
(repeat ad nauseam)

So, my google fu returned this issue, which is similar to mine. At least, if I set `options(error = utils::recover` as suggested above, I get the same issue. 

The solution offered above, that a line `options(error = )` is causing trouble on `.Rprofile`, and deleting that line fixes the problem, doesn't really help me, as  my `.Rprofile` is empty, I don't have one in my project, nor in my home directory, nor in R HOME. So I can't delete what doesn't exist. 

If I _add_ a line with some error handling option sure thing, I get the same error as referenced in the GitHub issue. Not very helpful. 

The solution suggested, 
> A temporary workaround is to set  `rstudio.errors.suppressed`  to  `FALSE`  in your  `.Rprofile`  as well.

doesn't work for me either, unless this involves something different than a line like

```
options(rstudio.errors.suppressed = FALSE)
``` 
on `.Rprofile`. 

So I am at a loss on what to do, other than revert to R 3.5.3 and wait for patch 3.6.1. 




```
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       macOS Sierra 10.12.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Warsaw               
 date     2019-05-14                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
```

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.2.1522 on MacOS 10.14.6 with R 3.6.0.

@Lornebradia The symptoms you're describing look like issue #4759. If you're still experiencing the problem, can you please include the information in that ticket, along with the version of RStudio you're using. Thanks!

**Comment by Ayeshasaeedhaq** [comment]
I tried the very first fix. usethis::edit_r_profile()

```
if(interactive()) {
  library(prompt)
  
  set_prompt(function(...){
    paste0(
      "[", git_branch(), "]> "
    )
  })
}
```

and got the following error: Error in library(prompt) : there is no package called ‘prompt’

**Comment by mgagliol** [comment]
@Ayeshasaeedhaq you need to install the library first with `install.packages("prompt")`

**Comment by Ayeshasaeedhaq** [comment]
Will try, thanks
