### ISSUE TITLE
RStudio v1.2: keyboard shortcut does not close R script it its own window

### ISSUE THREAD

**Issue by dschlaep** [rstudio/rstudio#4727]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1335 (Build 1351 (f1ac345))
    OS Version      : macOS X10.13.6
    R Version       : R version 3.5.3 (2019-03-11)

### Steps to reproduce the problem

Open a R script; Show in New Window; attempt to close it with keyboard shortcut `cmd-w`.

### Describe the problem in detail

In previous versions of RStudio, I was able to use the keyboard shortcut `cmd-w` to close a R script in its own "RStudio Source Editor" window  -- this no longer works, the window/file is not closed; nothing happens.
If the file is inside the main RStudio window, then I can successfully close the file with the keyboard shortcut. I can also "return to main window", then the keyboard shortcut works as normal.

Any other method of closing the file works correctly (clicking on the red-cross; choosing the menu File->Close) whether the file is in the main window or in its own. 

### Describe the behavior you expected

Consistent behavior that the standard keyboard shortcut `cmd-w` closes the file whether it is in the main window or in its own.

**Comment by kevinushey** [comment]
Interestingly, <kbd>Ctrl + W</kbd> works fine; only <kbd>Cmd + W</kbd> is affected.

**Comment by ronblum** [comment]
@kevinushey This is still an issue in RStudio Desktop 1.2.1539 on MacOS 10.14.6.

**Comment by kevinushey** [comment]
Looks like the associated fix did not make it back to v1.2-patch. I've now backported the fix and it should become part of the new preview builds (>= 1.2.1543)

**Comment by ronblum** [comment]
Verified on MacOS 10.14.6 using RStudio Desktop 1.2.1547.
