### ISSUE TITLE
Deployment destination disappeared from Rstudio. How do I put it back?

### ISSUE THREAD

**Issue by kambanane** [rstudio/rstudio#4728]
I deply shiny apps often to the same destinations. My usual destination has disappeared from my list in Rstudio. 

How can I put it back? "Other Destination" only allows me to create NEW slots, not to replace OLD slots. 

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by kambanane** [comment]
Seems related to this problem from 2016 but no indication that there is a work around or that it has been fixed.

https://github.com/rstudio/rsconnect/issues/118

**Comment by kambanane** [comment]
I end up with multiple slots on my shiny server and have to add the same people every time. With this many people it is getting incredibly inconvenient.

**Comment by jmcphers** [comment]
Sorry you're having trouble! This isn't related to RStudio proper, but the rsconnect package as you guessed. It stores deployment records in a folder called `rsconnect` alongside your app. My guess is that those records (and possibly the folder itself) are getting deleted somehow. If you can reproduce the behavior, would recommend that you file an issue on the rsconnect repo.
