### ISSUE TITLE
Filter in text fields highlights only the first occurrence in a row

### ISSUE THREAD

**Issue by drkarthi** [rstudio/rstudio#4730]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442 
    OS Version      : 10.13.6
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Load a dataframe with a text field that has multiple occurrences of the same word in one or more rows. For example, "This row contains highlight multiple times to reproduce the issue of no highlight beyond the first occurrence" contains the word "highlight" twice. 
2. View it using View().
3. Filter by the word that has multiple occurrences on the text field.

### Describe the problem in detail

1. Only the first occurrence of the word gets highlighted.

### Describe the behavior you expected

1. I would expect all occurrences to be highlighted. It is not a blocker but would be helpful to spot all the occurences.

**Comment by ronblum** [comment]
@drkarthi Thank you for reporting this. I'm unable to reproduce this with either 1.1.463 or 1.2.1335. What happens if you [try out the most recent released version of RStudio, 1.2.1335](https://www.rstudio.com/products/rstudio/download/#download)?

**Comment by kevinushey** [comment]
I can reproduce with v1.2.1522 on macOS:

```r
df <- data.frame(text = "Text Text Text")
View(df)
```

<img width="185" alt="Screen Shot 2019-05-20 at 8 53 33 AM" src="https://user-images.githubusercontent.com/1976582/58035058-cbacbd00-7adc-11e9-8ca8-ed7df81b756b.png">
