### ISSUE TITLE
Bug in 1.2.1335: blinking dot where the cursor previously was 

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#4732]
Windows 7, RStudio 1.2.1335

In the script editor pane, my cursor seems to have made a buddy that won't leave him alone. A blinking dot appears wherever my cursor last was. GIF below to show behaviour.

![rstudiobug](https://user-images.githubusercontent.com/952340/57005021-320b8300-6ba2-11e9-8cfc-a8feebd1714a.gif)

**Comment by jmcphers** [comment]
This is a known issue on Windows 7. See https://github.com/rstudio/rstudio/issues/4390.
