### ISSUE TITLE
Regression bug: in the git commit window, no longer able to highlight/select text

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#4734]
Windows 7 RStudio 1.2.1335

In the git commit window, I was previously (RStudio 1.1.463) able to drag my cursor along text in the diff window, and that text would highlight. This is useful when I look at my changes and I want to copy a certain line that was removed during my work. In the new RStudio, I'm not able to select text.

**Comment by gustavdelius** [comment]
I have the same problem with RStudio 1.2.1511 for Ubuntu 18.

**Comment by ronblum** [comment]
@daattali and @gustavdelius Thank you for filing this issue and providing multiple examples! I'm also able to reproduce this in RStudio Desktop 1.2.1335 on MacOS 10.14. We will review it as we work on development of future versions of RStudio.

**Comment by dfalty** [comment]
Verified fixed 1.3.867
