### ISSUE TITLE
Annoying JavaScript pop-up seen in Firefox

### ISSUE THREAD

**Issue by mjsteinbaugh** [rstudio/rstudio#4736]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.133
    OS Version      : RedHat 7
    R Version       : 3.6.0

### Steps to reproduce the problem

Open RStudio Server in Firefox. Type code in console. Eventually this pop-up happens and persists. I see this in multiple R sessions, and it doesn't happen in Chrome.

### Describe the problem in detail

RStudio Server will eventually result in a persistent `javascript:;` pop up in the bottom left part of the browser.

**Comment by gtritchie** [comment]
A screenshot showing the problem would be very helpful. Thanks!

**Comment by mjsteinbaugh** [comment]
Sure thing, here's a screenshot: http://share.steinbaugh.com/rstudio-server-javascript-popup.jpg

**Comment by ronblum** [comment]
@mjsteinbaugh Does the problem still occur with [the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/)? (Note that preview builds are intended for testing purposes only.)

**Comment by Patrick330** [comment]
Anecdotally, this seems to be resolved by opening and closing the "developer tools" in Firefox (F12). 

I will also add that this is annoying primarily because it overlaps the cursor on the console.

**Comment by jmcphers** [comment]
What version of Firefox is in play here? We have a fair number of people on Firefox so there must be something besides just "use firefox" that makes this happen...

**Comment by Patrick330** [comment]
Most recently it occurred on version 76.0 on Windows 10.

**Comment by mjsteinbaugh** [comment]
@jmcphers I was seeing it on Windows 10 when I originally filed the issue, up to at least Firefox 75. I've since switched back to only using macOS, and I'll have to double check if the latest version of Firefox still has the issue with RStudio Server. I don't think it was related to any extensions running in the browser.
