### ISSUE TITLE
Please mention Ubuntu 16 explicitly on the RStudio Server download page

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rstudio#4739]
The [RStudio Server download page](https://www.rstudio.com/products/rstudio/download-server/) mentions Ubuntu 14 and 18 explicitly, but does not mention 16. It is not clear that the download commands for Ubuntu 14 will work for Ubuntu 16; I think we should include this version clearly.

**Comment by jmcphers** [comment]
Updated.
