### ISSUE TITLE
Unable to load 32-bit version of R

### ISSUE THREAD

**Issue by wgrundlingh** [rstudio/rstudio#4742]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 7
    R Version       : 3.6.0

### Steps to reproduce the problem

1. Open up R Studio.
2. Confirm it's running a 64-bit version of R.
3. Tools > Global Options...
4. Identify/change to a 32-bit version.
5. Restart R Studio and it'll still be on 64-bit

![stack_exchange](https://user-images.githubusercontent.com/1776164/57098079-1ac9b400-6cce-11e9-9b45-de59dcaf27d9.gif)

**Comment by gtritchie** [comment]
RStudio 1.2 does not support 32-bit R, see #3150 for more details.

You can continue to use 32-bit R via RStudio 1.1.

https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio
