### ISSUE TITLE
No warning on MacOS if user defined addin keyboard shortcut conflicts with RStudio (or OS)

### ISSUE THREAD

**Issue by jackwasey** [rstudio/rstudio#4750]
Version 1.2.1511, MacOS Mojave, R 3.6

TO reproduce:
install.packages("devtools") # just so we have a package with addins
Menu Bar -> Tools -> Addins -> Browse Addins...
Click "Keyboard Shortcuts..."
Click in shortcut column of row "Run a test file"
Press CMD-S
Apply (which seems to close the window, not just apply)
Re-open Keyboard Shortcuts
Note that the shortcut is not struck out as described in the (Windows-oriented) article https://support.rstudio.com/hc/en-us/articles/206382178?version=1.2.1511&mode=desktop

May be a new feature request, but avoiding OS and conflicts with other applications would be highly desirable, although I've no idea if any platform has an API to query this information.

**Comment by jackwasey** [comment]
Workaround is to open Menu bar -> Tools -> Modify Keyboard Shortcuts...
Then sort by shortcut, then scan manually to find duplicates.

**Comment by ronblum** [comment]
@jackwasey Thank you for reporting this. I'm able to reproduce this in RStudio Desktop 1.2.1335. It works properly in 1.1.463, so this is a regression. Thanks!
