### ISSUE TITLE
Why tests package (CTRL+SHIFT+T) and check package (CTRL+SHIFT+E) don't provide same results on tests ? 

### ISSUE THREAD

**Issue by neonira** [rstudio/rstudio#4753]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 1.1.463
    OS Version      : windows 10 PRO version 10.0.17134--  x86_64-w64-mingw32/x64 (64-bit)
    R Version       :  R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"

### Steps to reproduce the problem
create a R function 
create an associate R test under tests/testthat
run test package (CTRL + SHIFT + T)
run package checks (CTRL + SHIFT + E)

### Describe the problem in detail
In the test function use a file.path('../../inst/testdata') to get access to a file in this folder.

Tests packages runs fine. 
Check package complains. Output of the tests are different. I guess that the file.path() does not point to the same file system place ... and so it fails. 

### Describe the behavior you expected

I expect the behavior to be same for tests. If it works with test package, it should work automatically for check package. 

### code sample

context("getFileSize")

rd <- '../..'

test_that("getFileSize", {
  expect_equal(getFileSize(file.path(rd, 'wyz.filesystem.ops.Rproj')), 352)
  expect_true(is.na(getFileSize(file.path(rd, '/R'))))
})

### output extract of test package 
==> devtools::test()

Loading wyz.filesystem.ops
Testing wyz.filesystem.ops
v | OK F W S | Context
v |  3       | cleanFilename
v | 14       | ensureFilenameExtension
v |  1       | getFileModificationTime
v |  2       | getFileSize
v |  1       | getLeastRecentEntry
v |  1       | getMostRecentEntry
v |  3       | isBinaryFile
v |  4       | isPureFile
v |  2       | normalizeFilename
v |  2       | normalizeFileSize
v |  2       | normalizeFrenchFilename
v |  9       | removeFilenameExtension
v |  2       | removeFolder

== Results ==================================================
Duration: 0.2 s

OK:       46
Failed:   0
Warnings: 0
Skipped:  0

### output extract of check package 
...
-- R CMD check results ------------------------ wyz.filesystem.ops 2.01.007 ----
Duration: 1m 0.9s

> checking tests ...
  See below...

> checking for missing documentation entries ... WARNING
  Undocumented code objects:
    'cleanFilename' 'ensureFilenameExtension' 'ensureFolderExistence'
    'getFileModificationTime' 'getFileSize' 'getLeastRecentEntry'
    'getMostRecentEntry' 'isBinaryFile' 'isNewerThan' 'isPureFile'
    'normalizeFileSize' 'normalizeFilename' 'normalizeFrenchFilename'
    'removeFile' 'removeFilenameExtension' 'removeFolder'
  All user-level objects in a package should have documentation entries.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.

-- Test failures ------------------------------------------------- testthat ----

> library(testthat)
> library(wyz.filesystem.ops)
> 
> test_check("wyz.filesystem.ops")

-- 1. Failure: getFileSize (@test_getFileSize.R#6)  --------------------------------
getFileSize(file.path(rd, "wyz.filesystem.ops.Rproj")) not equal to 352.
Modes: logical, numeric
target is logical, current is numeric

-- 2. Failure: getLeastRecentEntry (@test_getLeastRecentEntry.R#10)  ---------------
getLeastRecentEntry(lf) not equal to file.path(tp, "file-system/text-format/d.java").
Lengths differ: 0 is not 1

-- 3. Failure: getMostRecentEntry (@test_getMostRecentEntry.R#11)  -----------------
getMostRecentEntry(lf) not equal to "../../inst/testdata/file-system/data-format/cvBook.zip".
Lengths differ: 0 is not 1

-- 4. Error: isBinaryFile (@test_isBinaryFile.R#4)  --------------------------------
missing value where TRUE/FALSE needed
1: expect_false(isBinaryFile("../../wyz.filesystem.ops.Rproj")) at testthat/test_isBinaryFile.R:4
2: quasi_label(enquo(object), label)
3: eval_bare(get_expr(quo), get_env(quo))
4: isBinaryFile("../../wyz.filesystem.ops.Rproj")
5: checkBinary(filename_s)

-- 5. Failure: isPureFile (@test_isPureFile.R#4)  ----------------------------------
isPureFile("../../wyz.filesystem.ops.Rproj") isn't true.

-- 6. Failure: isPureFile (@test_isPureFile.R#5)  ----------------------------------
isPureFile("../../R") isn't false.

-- 7. Failure: normalizeFileSize (@test_normalizeFileSize.R#4)  --------------------
==... isn't true.

-- 8. Failure: normalizeFileSize (@test_normalizeFileSize.R#5)  --------------------
==... isn't true.

== testthat results  ==============================================
OK: 36 SKIPPED: 0 FAILED: 8
1. Failure: getFileSize (@test_getFileSize.R#6) 
2. Failure: getLeastRecentEntry (@test_getLeastRecentEntry.R#10) 
3. Failure: getMostRecentEntry (@test_getMostRecentEntry.R#11) 
4. Error: isBinaryFile (@test_isBinaryFile.R#4) 
5. Failure: isPureFile (@test_isPureFile.R#4) 
6. Failure: isPureFile (@test_isPureFile.R#5) 
7. Failure: normalizeFileSize (@test_normalizeFileSize.R#4) 
8. Failure: normalizeFileSize (@test_normalizeFileSize.R#5) 

Error: testthat unit tests failed
Execution halted

1 error x | 1 warning x | 0 notes v
Erreur : R CMD check found ERRORs
Ex�cution arr�t�e

Exited with status 1.

**Comment by ronblum** [comment]
@neonira Thank you for reporting this issue. Do you run into the same issue with [RStudio Desktop 1.2.1335](https://www.rstudio.com/products/rstudio/download/#download), the latest released version?

**Comment by neonira** [comment]
I do not know.  As suggested issue comes from file structure difference
between package in dev or at run. To solve this issue I had to use the same
folder whatever the source.

Hope this helps.
Regards
