### ISSUE TITLE
 S3 overridden method notice crashes rstudio

### ISSUE THREAD

**Issue by jackwasey** [rstudio/rstudio#4754]
### System details

    RStudio Edition :desktop
    RStudio Version :  1.2.1551 preview
    OS Version      : ubuntu disco
    R Version       :  3.6 

### Steps to reproduce the problem

install.packages(c("crul", "httr"))
# go to a package root directory
codemetar::write_codemeta()

### Describe the problem in detail

rstudio crashes before displaying error. running same commands in console (in Rstudio or not) shows the S3 method overridden notice due to conflict between httr and crul

### Describe the behavior you expected

no crash, and s3 error displayed

**Comment by kevinushey** [comment]
Seems to work fine for me. Without more context I'm guessing there's something wrong with one or more installed R packages on your system (if I recall from previous issues you typically use `gcc` to compile packages locally and I wouldn't be surprised if you're running into issues with ABI compatibility)
