### ISSUE TITLE
Rstudio crash or freeze

### ISSUE THREAD

**Issue by aureliendejode** [rstudio/rstudio#4756]
My R version is 3.6.0 and I am working on ubuntu 18.04
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3148788/diagnostics-report.txt)

**Comment by jmcphers** [comment]
Thank you for including a diagnostics report, but we would need a lot more information about what you're seeing and how to reproduce the crash in order to help! Please feel free to describe in more detail on our community forum:

https://community.rstudio.com/c/rstudio-ide
