### ISSUE TITLE
Rstudio 1.2 crash on any rmd in windws (ERROR: option error has NULL value)

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/rstudio#4759]
### System details

    RStudio Edition : Desktop
    RStudio Versions :  1.2.1335/1511
    OS Version      :  win 10 pro
    R Version       :  3.6

### Steps to reproduce the problem
File --> New file --> R Markdown... --> OK
click on the "play" button of the first chunk (i.e. setup)

### Describe the problem in detail
The console starts to show `ERROR: option error has NULL value` and repeat infinitely to show it again and again (every time in a new line). RStudio is blocked, you can type something on the console but nothing happens if you run it. Menus are shown but nothing happens if you select any option. CPU fun twists very fast, the RStudio processes consume high ammount of RAM and CPU (QtWebEngineProcess.exe QtWebEngineProcess.exe ~30% CPU, 100MB RAM, RStudio R Session ~30% CPU, 4.7GB RAM (after one minute, and constantly increasing)). I can switch off RStuio only by killing the entire processes' group by Task Manager.

### Additional info

1. The output of sessionInfo() 
```
> devtools::session_info()
- Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Europe/Berlin               
 date     2019-05-06                  

- Packages ----------------------------------------------------------------------
 package     * version    date       lib source                      
 assertthat    0.2.1      2019-03-21 [2] CRAN (R 3.6.0)              
 backports     1.1.4      2019-04-10 [2] CRAN (R 3.6.0)              
 callr         3.2.0      2019-03-15 [2] CRAN (R 3.6.0)              
 cli           1.1.0      2019-03-19 [2] CRAN (R 3.6.0)              
 crayon        1.3.4      2017-09-16 [2] CRAN (R 3.6.0)              
 desc          1.2.0      2018-05-01 [2] CRAN (R 3.6.0)              
 devtools      2.0.2      2019-04-08 [2] CRAN (R 3.6.0)              
 digest        0.6.18     2018-10-10 [2] CRAN (R 3.6.0)              
 fs            1.2.7      2019-03-19 [2] CRAN (R 3.6.0)              
 glue          1.3.1      2019-03-12 [2] CRAN (R 3.6.0)              
 magrittr      1.5        2014-11-22 [2] CRAN (R 3.6.0)              
 memoise       1.1.0      2017-04-21 [2] CRAN (R 3.6.0)              
 pkgbuild      1.0.3      2019-03-20 [2] CRAN (R 3.6.0)              
 pkgload       1.0.2      2018-10-29 [2] CRAN (R 3.6.0)              
 prettyunits   1.0.2      2015-07-13 [2] CRAN (R 3.6.0)              
 processx      3.3.0      2019-03-10 [2] CRAN (R 3.6.0)              
 ps            1.3.0      2018-12-21 [2] CRAN (R 3.6.0)              
 R6            2.4.0      2019-02-14 [2] CRAN (R 3.6.0)              
 Rcpp          1.0.1      2019-03-17 [2] CRAN (R 3.6.0)              
 remotes       2.0.4      2019-04-10 [2] CRAN (R 3.6.0)              
 rlang         0.3.4.9003 2019-04-30 [2] Github (r-lib/rlang@09989a3)
 rprojroot     1.3-2      2018-01-03 [2] CRAN (R 3.6.0)              
 rstudioapi    0.10       2019-03-19 [2] CRAN (R 3.6.0)              
 sessioninfo   1.1.1      2018-11-05 [2] CRAN (R 3.6.0)              
 testthat      2.1.1      2019-04-23 [2] CRAN (R 3.6.0)              
 usethis       1.5.0      2019-04-07 [2] CRAN (R 3.6.0)              
 withr         2.1.2      2018-03-15 [2] CRAN (R 3.6.0)              

[1] C:/Users/corra/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.0/library
```

This can be related with #4752 but my .RProfile is empty.
I have tried to add to it `rstudio.errors.suppressed=FALSE` as suggested in #4723 but it did not fix the issue.

3. A diagnostics report:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3149096/diagnostics-report.txt)

**Comment by jmcphers** [comment]
We have a fix for #4723 available; would you be willing to try a build and let us know if it fixes the problem for you?

https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.2.1518.exe

**Comment by CorradoLanera** [comment]
Wonderfull. Solved for me!

**Comment by jmcvw** [comment]
Hey, I have been suffering the same problem all day. This worked for me too.

**Comment by anjesh** [comment]
Do you have build for MacOS with this fix? I found the build https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.2.1511.dmg by hit and trial but it also has the same problem `ERROR: option error has NULL value` when executing chunks in Rmd

**Comment by datadavidz** [comment]
I had same issue on Windows and this build fixed it.

**Comment by jmcphers** [comment]
@anjesh No, we're working on getting a MacOS build out!

**Comment by chelauk** [comment]
Hi, I am encountering the same problem, linux ubuntu 14.04 rstudio Version 1.2.1335 R3.6

**Comment by kornl** [comment]
Same here with Linux Ubuntu 18.04.2 LTS an old RStudio version and also the new 1.2.1335.

**Comment by chasemc** [comment]
Fixed the problem for me on Windows

> We have a fix for #4723 available; would you be willing to try a build and let us know if it fixes the problem for you?
> 
> https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.2.1518.exe

**Comment by kornl** [comment]
Same for Ubuntu and the Linux build https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.2.1518-amd64.deb that can be found at the same adress.

**Comment by ramnathv** [comment]
@jmcphers Any updates on when the Mac OS build will be out?

**Comment by jmcphers** [comment]
Today! Give it a try:

**Comment by jmcphers** [comment]
https://www.rstudio.com/products/rstudio/download/preview/

**Comment by anjesh** [comment]
Still getting the same issue `ERROR: option error has NULL value` when executing chunks in Rmd. I am using the following

```
> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree          
```

```
> RStudio.Version()
$mode
[1] "desktop"

$version
[1] ‘1.2.1511’
```

**Comment by ramnathv** [comment]
Mmmm. For some reason the preview page has reverted back to the older preview version. When I visited that page earlier today, I was pointed to [v 1.2.1522](https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.2.1522.dmg) which resolves the issue.

**Comment by gtritchie** [comment]
Yes, we hit an issue with the 1.2.1522 and had to revert to the previous build until we sort it out. Sorry about that!

**Comment by ramnathv** [comment]
@gtritchie Thanks! I am using 1.2.1522 and have not run into any issues so far. But I will wait for a better build. Thanks again!

**Comment by gtritchie** [comment]
The issue under investigation appears to be Mac-only, so probably fine to keep using 1.2.1522 on Windows if you've already got it installed.

**Comment by ramnathv** [comment]
Oh. I am actually using the Mac version of 1.2.1522. Would you recommend that I downgrade to 1.2.1511?

**Comment by gtritchie** [comment]
If it’s working should be fine. The issue is that on some systems (i.e. mine) it won’t start.

**Comment by anjesh** [comment]
https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.2.1522.dmg works without error in my mac. Thanks.

**Comment by xrobin** [comment]
1.2.1522 is working fine on my mac with Mojave 10.14.4. 

@gtritchie It should be noted that v. 1.2.1511 and the current stable do *not* work either, as per this bug they crash with Rmd files, and other stuff like option(error= ... ). So I don't see the point to revert to an other broken version. But anyways thanks @anjesh for the direct link.

**Comment by gtritchie** [comment]
On some machines 1.2.1522 would not start at all, which was deemed worse. An updated preview build is in progress.

**Comment by gtritchie** [comment]
The updated 1.2.1522 preview build is up at https://www.rstudio.com/products/rstudio/download/preview/

**Comment by chienc1** [comment]
> https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.2.1522.dmg works without error in my mac. Thanks.

This also worked for me on MacOS with Mojave 10.14.5!

**Comment by ronblum** [comment]
Verified problem is resolved based on feedback above.

**Comment by Walt3r1** [comment]
Was getting the same error "ERROR: option error has NULL value", and same behavior. The release of RStudio v1.2.1541-1 _**solved**_  the problem. Thanks.

**Comment by ThierryO** [comment]
One of my co-workers has the same problem with an older version of RStudio (1.1.463). He can't upgrade because he needs a 32-bit R version.

The solution was to upgrade all packages to R 3.6.1 with `update.packages(ask = FALSE, checkbuil = TRUE)`. Then install the development version of  the rstudioapi package from GitHub instead of the CRAN version `remotes::install_github("rstudio/rstudioapi")`

**Comment by axelpuri** [comment]
> We have a fix for #4723 available; would you be willing to try a build and let us know if it fixes the problem for you?
> 
> https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.2.1518.exe

Hi the download isnt working !

**Comment by axelpuri** [comment]
> @axelpuri The current released version is 1.2.5001 at https://rstudio.com/products/rstudio/download/#download . There's also a preview of the upcoming update https://rstudio.com/products/rstudio/download/preview/ , if you are interested.

Hi ronblum 
thanks for your reply

I'm getting another error while working in ggplot something I havent seen before 
Error in fetch(key) : 
  lazy-load database 'C:/Users/axelp/OneDrive/Documents/R/win-library/3.6/ggplot2/help/ggplot2.rdb' is corrupt

I switched to Rscript from markdown yet the agony persists ! :/

**Comment by kevinushey** [comment]
This is a known issue -- this can occur when you reinstall an already-installed package. Restarting the R session will fix it.

**Comment by Ayeshasaeedhaq** [comment]
I have restarted and reinstalled R and that didnt fix this error. Do you have any tips?

**Comment by msmith01** [comment]
What fixed this issue for me was adding the file location to Python to the PATH in windows.

Search "PATH" in the windows search bar, then select "Internal Variables", then go to "Path" in the "System Variables" and click "Edit" and add the PATH ( "C:/Users/myUSERt/Anaconda3/python.exe" ) to Python here.

Then in R just run:

```{r}
reticulate::use_python("C:/Users/myUSERt/Anaconda3/python.exe")
```

Where the `use_python()` contains the Python version you added to the PATH.
