### ISSUE TITLE
R studio is slower rather crashes for large datasets(.csv file)

### ISSUE THREAD

**Issue by apoorvajain7** [rstudio/rstudio#4760]
### System details

    RStudio Edition : 
    RStudio Version : 1.2.1335
    OS Version      : 
    R Version       : 3.6.0

### Describe the problem in detail
I was trying to perform decision tree and logistic regression, it never take so long but from past 4 days its not even aborting and is slow, even i tried to reinstall it and restart it again and again . 
It show error; R session did'nt establish connection.
My dataset is almost 80,000 variables.
 R code
data=read.csv("datafile1.csv")
str(data)
na.omit(data)
install.packages("rpart")
install.packages("Catools")
instll.packages("rpart.plot")
library(rpart)
library(rpart.plot)
library(caTools)
str(data)
spl=sample.split(data$rating.internal.credit,SplitRatio=0.65)
datatest=subset(data,spl==FALSE)
datatrain=subset(data,spl==TRUE)
#2 nd question validating the model
model=glm(Paid ~ Id..de.la.oportunidad+Gasto.Fuente.de.Iluminacion+amount.received+payment.date+amount.received+payment.amount,data=datatrain,family="binomial")
summary(model)
*credittree=rpart(rating.internal.credit ~ bank.account+ age + sex + Id..de.la.oportunidad , method="class",data=datatrain)
prp(credittree)
rpart.plot(credittree)

**Comment by ronblum** [comment]
@apoorvajain7 Thank you for raising the issue. 
1) What happens when you run this in R, outside of RStudio?
2) Can you provide a CSV file so that we can try to reproduce the issue?

**Comment by jmcphers** [comment]
We need more information to diagnose this and haven't heard back, so closing.
