### ISSUE TITLE
Distraction Free / Zen Mode

### ISSUE THREAD

**Issue by MikeJohnPage** [rstudio/rstudio#4766]
I often find myself writing and testing scripts in Sublime Text due to the clean interface I can achieve: an open script occupying the left side of the screen, with a console/REPL on the right hand side of the screen. See below:

![Screenshot from 2019-05-07 16-26-58](https://user-images.githubusercontent.com/38110953/57271795-07ab4f80-70e5-11e9-98ed-b88a8c6a86c5.png)

This type of 'distraction free' setup is achievable in other code editors such as [Microsoft Visual Studio Code](https://code.visualstudio.com/docs/getstarted/tips-and-tricks) (called Zen Mode). 

I propose a shortcut be created in RStudio to achieve a similar 'distraction free' mode. The 'Show in new window' button achieves a similar goal, however lacks the ability to run a console side-by-side.

**Comment by ronblum** [comment]
@MikeJohnPage Thanks for the suggested enhancement. We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by jmcphers** [comment]
Currently being tracked in https://github.com/rstudio/rstudio/issues/1685.
