### ISSUE TITLE
RStudio has laggy responsiveness under Ubuntu guest with VirtualBox in Windows 10

### ISSUE THREAD

**Issue by kaybenleroll** [rstudio/rstudio#4770]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1511
    OS Version      : Ubuntu 19.04 (cosmic)
    R Version       : 3.6.0

### Steps to reproduce the problem
Build an Ubuntu virtual machine on a Windows 10 host system in VirtualBox and run RStudio within that.

### Describe the problem in detail
RStudio is laggy in its responsiveness - perhaps a half second delay between typing a key and the character appearing on the screen. It is more than enough to make using RStudio quite difficult within the environment and I have noticed this to be an issue for perhaps a year at this point and seems to last across versions of RStudio, Ubuntu and VirtualBox.

Strangely, changing the rendering engine to software seems to help with the lagginess but I then have issues with the whole RStudio client freezing up and needing to kill the process and restart it.

I have included the sessionInfo() and the diagnostic report below, but I am happy to provide more assistance with this if required.

### Describe the behavior you expected

The client to be much more responsive to inputs.

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    packrat_0.5.0  fortunes_1.5-4

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3156318/diagnostics-report.txt)

**Comment by ronblum** [comment]
@kaybenleroll Thanks for reporting the issue! We don't support Ubuntu 18.10 and 19.04, since they're short-term release. [The most recent version of Ubuntu that we support](https://www.rstudio.com/about/platform-support/) is 18.04. However, it's useful to have this issue around if other people run into the issue, as well as in case we run into it when the next long-term release—Ubuntu 20?—comes out.
