### ISSUE TITLE
Console drag selection above toolbar selects help pane

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4771]
**Steps to reproduce:**
* Configure a layout to put the console on the top row (by default it's on the bottom row).
* Print something to console.
* Select something on the console by clicking and dragging.
* While dragging, move the mouse above the RStudio toolbar.

**Expected behavior:** should select everything from where it was dragged up until the beginning of the console output.

**Actual behavior:** selects the whole help pane once the mouse pointer gets into the toolbar.

**Setup:** RStudio 1.2.1502, R 3.5.1, running on windows 10.

**Comment by pascaloettli** [comment]
Not reproducible neither on Ubuntu nor MacOS with version `1.2.1511`

**Comment by david-cortes** [comment]
> Not reproducible neither on Ubuntu nor MacOS with version `1.2.1511`

Can also confirm that the problem doesn't affect the linux version.

**Comment by ronblum** [comment]
@david-cortes and @pascaloettli Thank you for both reporting this and checking it on other environments. I'm unable to reproduce this on Windows 10. Does updating to 1.2.1511 make a difference? Also, where is the Help pane positioned, relative to the Console, and is it possible to get an animated GIF of the issue?  Thanks!

**Comment by david-cortes** [comment]
I'm attaching a screen capture under RStudio 1.2.1511, but I tried in other computers with the same OS and RStudio version and did not experience the problem. Moreover, if I open a new RStudio window, the second window doesn't suffer from this problem either. For more context, this happens inside a project, with many tabs open in the editor, but these conditions alone don't seem to cause the issue either.

![selects_another_pane](https://user-images.githubusercontent.com/11860098/57755901-b578b880-76fa-11e9-891a-247dfecab161.gif)

**Comment by kevinushey** [comment]
This one seems a bit tricky to fix. AFAIK the browser doesn't really give much in the ways of tooling as far as placing bounds on where a text selection can go in an HTML web page. The closest thing I've discovered is the use of `contenteditable="true"`, which then limits text selection within the editable element. Of course, the element is then editable -- something we typically _don't_ want.

There's also `user-select: contain`, but that's only proposed currently and hasn't been implemented by any browser outside of Internet Explorer / Edge.

https://jsfiddle.net/8v53kryL/ demonstrates one strategy for doing this (toggling `contenteditable` between true and false immediately between parent / child)

**Comment by david-cortes** [comment]
@kevinushey : this is actually RStudio desktop.

**Comment by david-cortes** [comment]
Funny thing, I'm now able to reproduce this in Linux too, but instead of selecting the help pane, it selects the build pane.

**Comment by pascaloettli** [comment]
Why did you downgrade?

**Comment by david-cortes** [comment]
> Why did you downgrade?

Didn't downgrade, just used a different computer that already had another version installed.

Another update: the bug only happens after having clicked the button "Install and Restart" in the build pane. And still happens in 1.2.1522.

**Comment by ronblum** [comment]
@david-cortes I'm able to reproduce this on Ubuntu 18.04 in RStudio Desktop 1.2.1335 and 1.2.1565, in the Build pane using your latest instructions. Thanks!
