### ISSUE TITLE
R-studio crashes while running selected lines [ctrl+enter].

### ISSUE THREAD

**Issue by toolbox1972** [rstudio/rstudio#4772]
### System details

    RStudio Edition : Desktp 
    RStudio Version : 1.2.1335
    OS Version      :  Ubuntu 18.04 LTE
    R Version       :  3.6.0

### Steps to reproduce the problem
Open Rstudio. Run following code, line by line, by pressing [ctrl + return].
a <- 1
b <- 2
c <- 3
d <- 4
e <- 5
f <- 6
g <- 7
h <- 8

### Describe the problem in detail
The problem is that R-studio crashes, the IDE disappears
as one would have closed it.

### Describe the behavior you expected
I expect that the R-studio IDE is stable enough to handle 
some few code entries, run line-by-line.

**Comment by pascaloettli** [comment]
RStudio Edition : Desktop 
    RStudio Version : 1.2.1335
    OS Version      : Ubuntu 18.04.2 LTS
    R Version       : 3.6.0

Not reproducible
