### ISSUE TITLE
R-studio crashes while adjusting the height of pane layout.

### ISSUE THREAD

**Issue by toolbox1972** [rstudio/rstudio#4773]
### System details

    RStudio Edition : Desktp 
    RStudio Version : 1.2.1335
    OS Version      :  Ubuntu 18.04 LTE
    R Version       :  3.6.0

### Steps to reproduce the problem
Open Rstudio. Adjust the height of pane layout.

### Describe the problem in detail
The problem is that R-studio crashes, the IDE disappears
as one would have closed it. This is observed when 
you adjust the height of pane layout.

### Describe the behavior you expected
I expect that the R-studio IDE is stable enough to handle 
adjusting the height of the pane layout.

<!-- Depending on the problem, the following may also be helpful

1. The output of sessionInfo() 

[sessionInfo.txt](https://github.com/rstudio/rstudio/files/3157178/sessionInfo.txt)

2. The R code in question
None, the problem is related to adjusting the IDE graphic view.

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3157176/diagnostics-report.txt)

**Comment by pascaloettli** [comment]
RStudio Edition : Desktop 
    RStudio Version : 1.2.1335
    OS Version      : Ubuntu 18.04.2 LTS
    R Version       : 3.6.0

Not reproducible

**Comment by kevinushey** [comment]
Based on the described symptoms, this is most likely an issue with your graphics card -- see e.g. https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors. I'd recommend:

1. Trying software rendering,
2. Updating or switching your graphics card drivers

to see if that helps.
