### ISSUE TITLE
Using "Select all" on a tab selects content in different pane

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#4776]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.511
    OS Version      : Windows 10
    R Version       : 3.6

This might be related to #4613 but since I'm not sure I'll fill a separate issue.

### Steps to reproduce the problem
Open R Studio. Right click on any of the tabs and click "Select all". 

### Describe the problem in detail
Following the steps above the content of some panes is highlighted. E.g. when I clicked "Select all" on the file tab, the console and help content were highlighted:
![image](https://user-images.githubusercontent.com/28725410/57432261-a5159900-7235-11e9-9638-70bd9cde0e89.png)

There doesn't seem to be much logic on what pane is highlighted, but I might miss something there. Sometimes the content of a single pane highlighted and sometimes even the content of a hidden pane or (at least seamingly) nothing.

### Describe the behavior you expected
The content of the selected pane to be highlighted

**Comment by pascaloettli** [comment]
RStudio Edition : Server
    RStudio Version : 1.2.511
    OS Version      : MacOS 10.14.4 (client), Ubuntu 18.04.2 (server)
    R Version       : 3.6
    Browser         : Firefox 66.0.5
Not reproducible
