### ISSUE TITLE
RStudio blocks setting graphics card to 'Integrated Only'

### ISSUE THREAD

**Issue by NathanSkene** [rstudio/rstudio#4778]
I have a late 2016 macbook pro. It's useful to be able to set this to 'Integrated Only' graphics using gfxCardStatus (to avoid using up the battery rapidly when not connected to charger). Some programs block this from happening by setting that they need to use the discrete graphics card. It appears that the latest version of RStudio (1.2.1335) has now been set to require the discrete graphics card (if I now try setting to integrated only while RStudio is open then gfxCardStatus says it's not possible while RStudio is open). Would be great if this setting could be altered. Thanks.

**Comment by jmcphers** [comment]
This was fixed in https://github.com/rstudio/rstudio/issues/4672; we hope to have a preview out with the fix soon!
