### ISSUE TITLE
Scan R Markdown YAML header for package dependencies

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4779]
Currently, when we discover R package dependencies in R Markdown documents, we only read the R code itself. 

https://github.com/rstudio/rstudio/blob/96accd67b32947fc08fe9c6978dc5a18e15cad75/src/cpp/session/modules/SessionCodeTools.R#L2107-L2110

For R Markdown documents, we should also introspect the YAML header to discover dependencies. There are at least three dependencies we should be able to discover in the YAML header:

- R Markdown documents with `runtime: shiny` or `runtime: shiny_prerendered` require the Shiny package.
- R Markdown documents with parameters also require the Shiny package. (This has been a source of Connect deployment errors when attempts are made to publish these when Shiny is not installed).
- The `output:` key can name a method from a package; for example, `output: revealjs::revealjs_presentation` indicates a dependency on the `revealjs` package.

**Comment by colearendt** [comment]
A potential context / use case here:

We are banking on this functionality in the IDE to drive some simple "guided" content deployment demos to RStudio Connect.

A newer R user who is unfamiliar with package dependencies gains a lot from IDE functionality that guides them to making things "just work," and is especially helpful in these types of guided demos. One of our demos happens to be a flexdashboard, and the implicit `flexdashboard` dependency is not picked up by the IDE.

**Comment by jmcphers** [comment]
I'll take this one.

**Comment by R-Hannibal** [comment]
Verified Fixed on:
-Windows Desktop: Version 1.3.926
-Server: Version 1.3.929-1
YAML header dependencies are now being read in RMarkdown documents on Save. Verified that when saving the document with one of the outlined dependencies a Yellow notification bar is displayed highlighting the packages which are required but not installed and giving the user the option to install them. 
Tested the 3 dependencies listed by @jmcphers on this ticket as well as the flexdashboard dependency highlighted by @colearendt and all are functioning as expected.
