### ISSUE TITLE
Rstudio doesn't send CR (or maybe CRLF) character to python in terminal 

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4780]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1335
    OS Version      :  Windows 10
    R Version       :  3.6.0

### Steps to reproduce the problem
 - Press Alt-Shift-T to open a terminal
 - type `python` and ENTER to start python
 - in a source file type `import os`
 - Press Ctrl-Alt-Enter to source the command
### Describe the problem in detail
The command doesn't get run because no return character seems to get sent.
### Describe the behavior you expected
The python command to be run

**Comment by ronblum** [comment]
@kendonB Thanks for reporting this. I'm unable to reproduce this—how are you sourcing the file? Also, is there a CR or CRLF at the end of the line?

**Comment by kendonB** [comment]
Apologies, I missed a step: I'm using Ctrl-Alt-Enter to source a single line. I have have even tried highlighting several lines (with return chars) and it also doesn't work

**Comment by kendonB** [comment]
This looks fixed in 1.3.842. Thanks!
