### ISSUE TITLE
Keep the visible range of lines constant when using "go to line"

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4781]
I'm using a voice coding toolbox (https://github.com/dictation-toolbox/caster) With functionality for RStudio. I find when using the "go to line" capability (Alt-Shift-G), RStudio imposes that the cursor will end up seven lines down from the top of the visible range of lines, meaning that not only does the cursor move, but the code shifts up or down as well. This make jumping lines within the screen tougher.

The request is to disable this shifting in the case where the new line is visible.

**Comment by ronblum** [comment]
@kendonB I see what you mean—thank you for the suggestion. I'll add it to the list of things to review as continue development of RStudio. Thanks!

**Comment by kendonB** [comment]
This appears to be fixed in 1.3.842. Thanks!
