### ISSUE TITLE
Stuck "Creating Project..." message when trying to create a new project in a directory without write access.

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#4784]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1335-1
    OS Version      : Ubuntu 16.04

### Steps to reproduce the problem
1. Create a directory without write access to a user
2. File -> New Project -> New Directory -> New Project -> and select directory without write access
3. Create project
4. Observe permission denied error and then a stuck "Creating Project..." message at the top that doesn't go away unless you refresh

### Describe the problem in detail
Stuck "Creating Project..." message when trying to create a new project in a directory without write access. Note, this is server only it seems. I wasn't able to reproduce on Mac 1.2.1335.

![image](https://user-images.githubusercontent.com/15237845/57545954-5f35ff00-7321-11e9-95c4-c5b13fe636bf.png)

**Comment by ronblum** [comment]
I'm still seeing this issue in RStudio Server 1.2.1522 on Red Hat 7.6 with R 3.6.0.

**Comment by kfeinauer** [comment]
@ronblum I believe this change is only available starting in `1.2.1523` and beyond. Could you try a more recent build, preferably the latest 1.2 daily?

**Comment by ronblum** [comment]
@kfeinauer I still see the issue in 1.2.1528.

**Comment by kfeinauer** [comment]
@ronblum thanks for catching this - I had only committed the fix to the `master` branch. I just ported the change to v1.2-patch, so it should show up in the dailies soon.

**Comment by ronblum** [comment]
Verified in RStudio Server 1.2.1539 on Red Hat 7.6.
