### ISSUE TITLE
Pane element color flickers after waking system up from sleep

### ISSUE THREAD

**Issue by tilltnet** [rstudio/rstudio#4786]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.1335
    OS Version      : macOS 10.14.4
    R Version       : 3.5.3

### Steps to reproduce the problem

Wake up system from sleep while running RStudio.

### Describe the problem in detail

After waking up from sleep some of the pane's colors change in shade in sync with the cursor blinking in the editor or in the console, resulting in a constant flicker. When I resize the RStudio window it stops. The issue started after updating to the 1.2 release. The issue persistet after changing RStudio and editor themes.

![rstyudioflicker2](https://user-images.githubusercontent.com/8319636/57555613-c7e1a380-7342-11e9-9bdb-be19e66f588c.gif)

### Describe the behavior you expected

No Flickering ;)

**Comment by ronblum** [comment]
@tilltnet Thank you for reporting this issue. We'll review it as we continue our ongoing work on RStudio.

**Comment by MariaSemple** [comment]
Hi @tilltnet, thanks for reporting this issue. Unfortunately I haven't been able to reproduce it yet. Here are some questions that might help us start to track down the source of the issue:
* Are you able to reproduce by waking up your computer right after it goes to sleep, or do you need to let it sleep for a while to reproduce? 
* Does RStudio need to be in focus when the computer falls asleep?
* Which theme are you using? Does the issue occur with other themes? What about light themes?
* Does the issue still occur if you switch the RStudio theme from Modern to Classic or Sky? (This can be changed using the top drop down box of the Appearance tab in Preferences)

**Comment by tilltnet** [comment]
>     * Are you able to reproduce by waking up your computer right after it goes to sleep, or do you need to let it sleep for a while to reproduce?

the issue occurs at any amount of time spent sleeping

>     * Does RStudio need to be in focus when the computer falls asleep?

Yes, I just tested this. It does only occur when Rstudio is focussed before sleeping.

>     * Which theme are you using? Does the issue occur with other themes? What about light themes?

I tested a few themes light and dark, it occured with all i tried and is more visible with dark themes.

>     * Does the issue still occur if you switch the RStudio theme from Modern to Classic or Sky? (This can be changed using the top drop down box of the Appearance tab in Preferences)

Yes.

**Comment by MariaSemple** [comment]
Thanks for getting back to me. In that case, I'm still not able to reproduce the issue. Here's another list of questions that could possibly impact the behaviour of this bug:
* Does the issue happen when you have a project open (or when you don't have a project open)? 
* Do the types of open files change the behaviour (e.g. all .R files, some .Rmd, etc.)? 
* Have you installed any custom themes?
* I've just noticed you are able to reproduce it with both Desktop and Server. What operating system is RStudio Server hosted on, and which browser are you using to access it?
* Are you using any external monitors? If yes, does the display used for RStudio impact the behaviour?

**Comment by tilltnet** [comment]
>     * Does the issue happen when you have a project open (or when you don't have a project open)?

Yes, it occurs with and without a project opened.

>     * Do the types of open files change the behaviour (e.g. all .R files, some .Rmd, etc.)?

Whenever anything is focused within RStudio that has a blinking cursor, the flickering occurs: Editor all files, Console, Console, Search Field in help or dataframe viewer.

>     * Have you installed any custom themes?

No, I don't.
 
>     * I've just noticed you are able to reproduce it with both Desktop and Server. What operating system is RStudio Server hosted on, and which browser are you using to access it?

I only have access to Desktop.

>     * Are you using any external monitors? If yes, does the display used for RStudio impact the behaviour?

Yes, and I am so far only able to reproduce this on the external monitor!! When I disconnect the monitor and use only the macboock screen it doesn't occur. It also only occurs if I have all my RStudio sessions on the external monitor, when I place one of the Sessions on the macbook screen, it doesn't happen.

**Comment by MariaSemple** [comment]
Hi @tilltnet, unfortunately I am still unable to reproduce this even with external monitors on the same operating system. For the time being, you could try to avoid the issue by switching the focus from RStudio before your laptop goes to sleep.

**Comment by MariaSemple** [comment]
As an additional thought, could you try switching to software rendering and see if that resolves the issue? This can be done by opening `RStudio > Preferences > General` and switching to the `Advanced` tab. Under `OS Integration` you should see a drop-down list labelled `Rendering engine:`. Change it's value to `Software Rendering`. Let me know if that helps!

**Comment by cszang** [comment]
I am seeing the same bug under the same circumstances as reported by @tilltnet, and to make things even more funny: I see it only when I connect the external monitor via HDMI, not when connecting via DVI.

**Comment by MariaSemple** [comment]
That's very interesting I have USB-C to HDMI cables and I'm unable to reproduce the issue. Out of curiosity, are you using any adapters with either of the cables? Does changing to software rendering resolve the issue for you, @cszang?

**Comment by kevinushey** [comment]
What kind of external monitor? Is it a regular DPI monitor, or high DPI monitor?

Have you configured font smoothing in any way? What do you see if you run the following in a terminal?

```
defaults read -g CGFontRenderingFontSmoothingDisabled
```

**Comment by MichaelChirico** [comment]
I also have this problem. It only occurs when I'm _not_ connected to my external monitor. It flickers when I'm clicked in to either the Console or the Source panes. Clicking the environment or Plotting panes stops it. It doesn't occur for RStudio Server.

<img width="349" alt="Screenshot 2019-06-19 at 8 38 18 PM" src="https://user-images.githubusercontent.com/7606389/59766185-30bd2380-92d2-11e9-9b3f-163dfbd72883.png">

<img width="432" alt="Screenshot 2019-06-19 at 8 38 46 PM" src="https://user-images.githubusercontent.com/7606389/59766215-43cff380-92d2-11e9-8458-84714e3a5874.png">

<img width="556" alt="Screenshot 2019-06-19 at 8 39 13 PM" src="https://user-images.githubusercontent.com/7606389/59766242-51857900-92d2-11e9-8893-97e7243d70f4.png">

**Comment by kevinushey** [comment]
Still no luck reproducing this issue :-/

**Comment by jmcphers** [comment]
Moving out of 1.2 since we don't have a repro.

**Comment by hrbrmstr** [comment]
I've been getting this on the dailies (and I'm mobile at the mo so it's plain ol latest macOS Mojave) for abt a week now.

**Comment by ronblum** [comment]
@hrbrmstr Is this still occurring with the dailies?

Others: Does this still occur with [the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/)? The original issue was with 1.2.1335. (Note that preview builds are intended for testing purposes only.)

**Comment by hrbrmstr** [comment]
I'll grab the preview after I crank through some things today and test it (I generally run new intra-day dailies in production b/c I'm insane). If not today then def tomorrow as I'm mobile and will def be on the laptop.

**Comment by MichaelChirico** [comment]
Hadn't noticed it for a while but I'm back to flickering just now. One of the more recent builds: Version 1.3.449, Build 418 (ba5ed1d0, 2019-09-16).

Also noticed just now:

Highlighting the version info in the `About RStudio` popup caused rapidfire flickering -- each new character highlighted triggered a flicker.

Lastly, I have 3 RStudio projects open right now. Only one is flickering.

**Comment by MichaelChirico** [comment]
[screen_recording.txt](https://github.com/rstudio/rstudio/files/3643147/screen_recording.txt)

^ here is a screen recording of it happening on my machine. I renamed the `.mov` file to `.txt` to get around the GitHub upload "blocker" 😏

**Comment by ronblum** [comment]
Thanks for the added information! I'll mark it as an issue to review. If by chance it's no longer occurring in the current version of RStudio (1.2.5033), please let us know.

**Comment by ronblum** [comment]
We still haven't been able to reproduce this internally. For any of y'all for whom this is still happening (if it is): 
1. What happens if you switch to software rendering? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
2. What are your energy saver settings? These are mine. 
<img width="658" alt="power adapter" src="https://user-images.githubusercontent.com/31009952/71934140-cb4b5a00-3171-11ea-9cdb-81ada34cce31.png">
<img width="663" alt="battery" src="https://user-images.githubusercontent.com/31009952/71934156-d7371c00-3171-11ea-9c3f-a1ba318641c5.png">

**Comment by MichaelChirico** [comment]
Just happened again on `Version 1.3.730` for me. Currently on adapter, it's flickering on the external monitor

![Screenshot 2020-01-17 at 2 57 56 PM](https://user-images.githubusercontent.com/7606389/72590890-cf2d6800-3939-11ea-9788-6a2caeb52f37.png)
