### ISSUE TITLE
Cannot change options(error=) in RStudio when used interactively

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/rstudio#4787]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1518 
    OS Version      :  win 10 pro
    R Version       :  3.6.0

### Steps to reproduce the problem
# runing the following line by line on RStudio: the error option is not set!
option(error = browser)
getOption("error")

# runing the following alltogether on RStudio: the error option seems set, i.e., it show the correct results... but if you, after that, re-run getOption("error") it return NULL again!
options(error = browser)
getOption("error")

### Describe the problem in detail
It seems that RStudio force the option error to return NULL at the end of every whatever interactive execution. I have switched to RStudio desktop 1.2.1518 after # 4759.
Note: on RStudio server pro-1.2.1335-1 the issue doesn't happen.

### Describe the behavior you expected
I want to be able to change the option error at the beginning of an R session (maybe setting the option .onAttach() of a package) and use my option during the entire (interactive) session. E.g.,

```
options(error = browser)
```

It works in R.exe! (it also works during an RMarkdown execution, even if RStudio is rendering it), it works in RStudio server pro-1.2.1335-1 used interactively. It does not work only when I use RStudio desktop 1.2.1518 interactively.

1. The output of sessionInfo()

```
> session_info()
- Session info ----------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Europe/Berlin               
 date     2019-05-10                  

- Packages --------------------------------------------------------------------
 package     * version    date       lib source                      
 assertthat    0.2.1      2019-03-21 [2] CRAN (R 3.6.0)              
 backports     1.1.4      2019-04-10 [2] CRAN (R 3.6.0)              
 callr         3.2.0      2019-03-15 [2] CRAN (R 3.6.0)              
 cli           1.1.0      2019-03-19 [2] CRAN (R 3.6.0)              
 covr        * 3.2.1      2018-10-18 [2] CRAN (R 3.6.0)              
 crayon        1.3.4      2017-09-16 [2] CRAN (R 3.6.0)              
 desc          1.2.0      2018-05-01 [2] CRAN (R 3.6.0)              
 devtools    * 2.0.2      2019-04-08 [2] CRAN (R 3.6.0)              
 digest        0.6.18     2018-10-10 [2] CRAN (R 3.6.0)              
 fortunes      1.5-4      2016-12-29 [2] CRAN (R 3.6.0)              
 fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)              
 glue          1.3.1      2019-03-12 [2] CRAN (R 3.6.0)              
 lazyeval      0.2.2      2019-03-15 [2] CRAN (R 3.6.0)              
 magrittr      1.5        2014-11-22 [2] CRAN (R 3.6.0)              
 memoise       1.1.0      2017-04-21 [2] CRAN (R 3.6.0)              
 packrat       0.5.0      2018-11-14 [2] CRAN (R 3.6.0)              
 pkgbuild      1.0.3      2019-03-20 [2] CRAN (R 3.6.0)              
 pkgload       1.0.2      2018-10-29 [2] CRAN (R 3.6.0)              
 prettyunits   1.0.2      2015-07-13 [2] CRAN (R 3.6.0)              
 processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)              
 ps            1.3.0      2018-12-21 [2] CRAN (R 3.6.0)              
 R6            2.4.0      2019-02-14 [2] CRAN (R 3.6.0)              
 Rcpp          1.0.1      2019-03-17 [2] CRAN (R 3.6.0)              
 remotes       2.0.4      2019-04-10 [2] CRAN (R 3.6.0)              
 rex           1.1.2      2017-10-19 [2] CRAN (R 3.6.0)              
 rlang         0.3.4.9003 2019-05-10 [1] Github (r-lib/rlang@6a232c0)
 rprojroot     1.3-2      2018-01-03 [2] CRAN (R 3.6.0)              
 rstudioapi    0.10       2019-03-19 [2] CRAN (R 3.6.0)              
 sessioninfo   1.1.1      2018-11-05 [2] CRAN (R 3.6.0)              
 testthat    * 2.1.1      2019-04-23 [2] CRAN (R 3.6.0)              
 usethis     * 1.5.0      2019-04-07 [2] CRAN (R 3.6.0)              
 withr         2.1.2      2018-03-15 [2] CRAN (R 3.6.0)              

[1] C:/Users/corra/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.0/library
```
 
2. The R code in question
```
{# to be run from a script in RStudio (interactively!)
    options(error = browser)
    getOption("error")
}
#> .Primitive("browser")()
getOption("error") # to be run after the previous separately
                              # (i.e., with a different hit of CTRL/cmd+RETURN
                              # from the previous lines)

#> NULL
```

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3168109/diagnostics-report.txt)

**Comment by pascaloettli** [comment]
Reproducible on Ubuntu 18.04.2 with Rstudio Desktop version `1.2.1518`. But not reproducible with version `1.2.1511`.

**Comment by jmcphers** [comment]
Probably a regression from https://github.com/rstudio/rstudio/commit/78e10db4675bad47b5e0c8cc4da3b164e4d4b1cb; R 3.6 changed some rules around `NULL` options, and we probably don't have the right solution yet. Thanks for reporting, we'll look at this soon!

**Comment by kevinushey** [comment]
Not sure if this is directly related, but we should probably avoid modifying the `.Options` object directly and use the `options()` API, since R does some special handling for option values in that API. See e.g.

https://github.com/wch/r-source/blob/c81060ae57a75d84bfe90ec3e96894af56bf871d/src/main/options.c#L622-L628

**Comment by jmcphers** [comment]
I think we're using the raw objects because this is part of the code that's used as a layup to our string eval/function calling code so can't trivially itself include R function calls or string evaluation. Probably surmountable.
