### ISSUE TITLE
RStudio not getting re launch after crash

### ISSUE THREAD

**Issue by aarshrishi** [rstudio/rstudio#4788]
R Studio after getting crash while running unable to getting re launch.

Below is the diagnostic error

ERROR system error 5 (Access is denied) [path=C:/WINDOWS/system32/.Rhistory]; OCCURRED AT: auto __cdecl rstudio::core::FilePath::open_w::<lambda_7b908e48c5a8d510922ad1534398f5b0>::operator ()(void) const c:\jenkins\workspace\ide\windows-v1.2\src\cpp\core\filepath.cpp:1144; LOGGED FROM: void __cdecl rstudio::r::session::reportHistoryAccessError(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const class rstudio::core::FilePath &,const class rstudio::core::Error &) c:\jenkins\workspace\ide\windows-v1.2\src\cpp\r\session\rinit.cpp:391

**Comment by ronblum** [comment]
@aarshrishi Thank you for reporting this. Can you please provide the full details of your environment? Thanks!

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jmcphers** [comment]
We need more information to diagnose this and have not heard back, so closing.
