### ISSUE TITLE
Identical objects not treated identically in RStudio's Environment tab

### ISSUE THREAD

**Issue by benz0li** [rstudio/rstudio#4791]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1335
    OS Version      : Debian GNU/Linux 9 (stretch)
    R Version       : 3.6.0

### Steps to reproduce the problem
_Source_
```R
sessionInfo()
RStudio.Version()$version

library(dplyr)

tbl1 <- tibble(x = c(1L, 2L))
tbl2 <- tibble(x = 1:2)
tbl3 <- tibble(x = 1:2) %>%
  bind_rows(NULL)

# Pickily test for exact equality
identical(tbl2, tbl1, FALSE, FALSE, FALSE, FALSE)
identical(tbl3, tbl1, FALSE, FALSE, FALSE, FALSE)
```

_Source with Echo_
```R
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   

> RStudio.Version()$version
[1] ‘1.2.1335’

> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


> tbl1 <- tibble(x = c(1L, 2L))

> tbl2 <- tibble(x = 1:2)

> tbl3 <- tibble(x = 1:2) %>%
+   bind_rows(NULL)

> # Pickily test for exact equality
> identical(tbl2, tbl1, FALSE, FALSE, FALSE, FALSE)
[1] TRUE

> identical(tbl3, tbl1, FALSE, FALSE, FALSE, FALSE)
[1] TRUE
```

### Describe the problem in detail
Although objects `tbl2` and `tbl1` are identical, the column preview is not available for `tbl2`. Only after applying an additional dummy operation (i.e. `bind_rows(NULL)`), the column preview option is shown:

![RStudio_Environment](https://user-images.githubusercontent.com/20233085/57601367-9f34f600-755c-11e9-8fe3-2a325bac73e3.png)

### Describe the behavior you expected
I expect identical objects to be treated identically in RStudio's Environment tab.

**Comment by pascaloettli** [comment]
Reproducible with the **desktop** version `1.2.1511`, but not with the **desktop** version `1.3.172`:

![Screenshot from 2019-05-13 16-12-37](https://user-images.githubusercontent.com/6613954/57602397-f0afa600-7599-11e9-9961-966b48f88b8e.png)

**Comment by ronblum** [comment]
@benz0li This looks like a duplicated of #4758. If you feel this is different, please reopen. Thanks!

**Comment by pascaloettli** [comment]
Please note there is no issue with 1.3

**Comment by benz0li** [comment]
Agreed.

```R
> .rs.hasAltrep(tbl1)
[1] FALSE

> .rs.hasAltrep(tbl2)
[1] TRUE

> .rs.hasAltrep(tbl3)
[1] FALSE
```
