### ISSUE TITLE
Documentation: Provide a configuration file reference for RStudio Server

### ISSUE THREAD

**Issue by fthommen** [rstudio/rstudio#4794]
Dear RStudio Server makers,

I really appreciate the complete and mostly well written RStudio Server manual at https://docs.rstudio.com/ide/server-pro/.  However the manual is mostly task/goal oriented.  When trying to get an overview of what can be configured and how, a more configuration (file) oriented approach would be helpul.  I have always appreciated when I was able to combine both perspectives when configuring a service: Use the task oriented approach for specific questions and from there use the file oriented reference to find out, what other "things" could be configured.  Maybe even jumping back to the task oriented documentation. IBM Spectrum LSF being an excellent example of a software which is documented this way.  This combined procedure leads to a far more complete insight of the possibilities of a software than the task-oriented procedure alone could.

_This said I suggest that the current manual be complemented by a configuration file reference._

**Comment by ronblum** [comment]
@fthommen Thanks for the suggested enhancement to the documentation. We'll take a look at it as we continue to develop new versions of RStudio. In the meantime, do you have a link for the sample documentation you suggest as a comparison point? Thanks!

**Comment by fthommen** [comment]
IBM Spectrum LSF:

-  per-file configuration reference: https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_config_ref/part_files.html
- per-command reference: https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_welcome/lsf_kc_cmd_ref.html
- task/goal oriented administration manual: https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_welcome/lsf_kc_managing.html

These contents are also provided as PDF files together with the - paid/licensed - software downloads

**Comment by jmcphers** [comment]
We are tracking this idea over on the private repo for our professional version (where this documentation is built). Agree that it'd be a good move!
