### ISSUE TITLE
Allow user to set default values for number of columns to show in View

### ISSUE THREAD

**Issue by sysilviakim** [rstudio/rstudio#4797]
## System details

RStudio Edition : Desktop
RStudio Version : 1.2.1335
OS Version      : Windows 10
R Version       : 3.6.0

## Steps to reproduce the problem

    View(do.call(cbind, rep(list(mtcars), 5)))

## Describe the problem in detail

If the data is wide enough, the `View` defaults to showing the first 50 columns. I can manually alter it from `1 - 50` to `1 - 55` or similarly. This is all good, except that I can't set the default values to how many columns I want `View` to show. I have to go back to the data viewer to set values manually every time I want the full width dataframe. 

## Describe the behavior you expected

Have Global Options to define default behavior of `View`, or have arguments available in `View` such as `View(df, full = TRUE)` or `View(df, cols = seq(50))`.

**Comment by ronblum** [comment]
@sysilviakim Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.

**Comment by jmcphers** [comment]
I've implemented this in https://github.com/rstudio/rstudio/pull/5262. There is no UI for the preference currently, but you can set it as follows (using the dev version of rstudioapi):

    rstudioapi::writeRStudioPreference("data_viewer_max_columns", 75)
