### ISSUE TITLE
PDF fails to display in RStudio's HTML viewer

### ISSUE THREAD

**Issue by nilsbw** [rstudio/rstudio#4798]
The HTML viewer no longer shows external PDF graphics, it displays a 'broken image link' icon instead. This used to work with earlier versions of RStudio. 

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : OS X Mojave
    R Version       : 3.6.0

### Steps to reproduce the problem

Use the attached minimal example:
[PDF_Document_Example.zip](https://github.com/rstudio/rstudio/files/3181092/PDF_Document_Example.zip)

1. Open index.Rmd in RStudio
2. Click “Knit”
3. The RStudio preview of the HTML document does not show the included PDF graphics (the symbol makes it look like it’s a broken link, which is incorrect)
4. Open the compiled HTML document (_book/index.html) with an external browser, for example Safari - the PDF graphics is displayed without problems. 

### Describe the problem in detail

The PDF graphics is not shown in the viewer. 

### Describe the behavior you expected

The PDF graphics should be displayed in the viewer.

**Comment by ronblum** [comment]
@nilsbw Thank you for reporting this issue. We'll review it as we continue our ongoing work on RStudio.

Reproducible using both RStudio Desktop 1.2.1335 on MacOS 10.14 and RStudio Server 1.2.1335 on Red Hat 7.6. It works with 1.1.463, so this is a regression.

**Comment by kevinushey** [comment]
I can also replicate this in the Qt Nanobrowser:

![Screen Shot 2019-05-23 at 3 11 30 PM](https://user-images.githubusercontent.com/1976582/58290208-c2864f00-7d6d-11e9-8132-6ec76099fd16.png)

Looks like some extra plugin is required in order to be able to view PDF images.

**Comment by kevinushey** [comment]
IIUC this will be supported in Qt 5.13+. I don't think this is a change we can make for RStudio 1.2.

**Comment by jmcphers** [comment]
We already ship PDF.js, so we could try a workaround there, but agree that we don't have to do this for 1.2-patch.
