### ISSUE TITLE
RStudio Desktop 1.2.1335 .Rprofile repos are not recognized

### ISSUE THREAD

**Issue by flohump** [rstudio/rstudio#4800]
.Rprofile is loaded but the repos defined there are not showed by getOption("repos").
This happens with RStudio Desktop 1.2.1335 on Mac OS as well as with RStudio v1.2.1511 beta.
With Version 1.1.463 it works fine.

**Comment by pascaloettli** [comment]
RStudio Edition : Desktop
    RStudio Version : 1.2.1511
    OS Version      : macOS Mojave
    R Version       : 3.6.0
Not reproducible. I have a CRAN repository defined in the `.Rprofile` and `getOption("repos")` correctly shows it.

**Comment by flohump** [comment]
For reproducability, my .Rprofile has the following content:

`
cat("Global .Rprofile loaded!!!\n\n")

# add PIK repository to known repositories
options(repos = c(CRAN = "@CRAN@", rd3mod_repo = "https://rse.pik-potsdam.de/r/packages/"))
`

**Comment by pascaloettli** [comment]
OK, I now reproduce. RStudio is stuck with @CRAN@ 

> getOption("repos")
                      CRAN 
"http://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE

R in termimal:

> getOption("repos")
                                    CRAN
                                "@CRAN@"
                             rd3mod_repo
"https://rse.pik-potsdam.de/r/packages/"

**Comment by ronblum** [comment]
@flohump Thank you for reporting this issue—I am able to reproduce it. What do you get for `getOption("repos")` in standalone R and in RStudio if you switch the order? I.e.,
```
options(repos = c(rd3mod_repo = "https://rse.pik-potsdam.de/r/packages/", CRAN = "@CRAN@"))
```
That appears to work in both R and RStudio:

1. Standalone R
>>>
> getOption("repos")
                             rd3mod_repo                                     CRAN 
"https://rse.pik-potsdam.de/r/packages/"                                 "@CRAN@" 

2. RStudio
>>>
> getOption("repos")
                             rd3mod_repo                                     CRAN 
"https://rse.pik-potsdam.de/r/packages/"                                 "@CRAN@"

**Comment by gwd999** [comment]
Currently my solution (workaround to the options('repos' = c('file:X:/…", …)) not doing the trick problem is including the following in my "~/.Rprofile" 

`.First <- function() {library(base); options('repos' = c(myCRAN='file:///X:/PathToLocal/R/CRAN')); print(options('repos'))}` 
The final print command in there just to check if I succeeded …
