### ISSUE TITLE
Allow auto-complete for shiny modules server arguments

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#4803]
When calling a function in RStudio, it's very useful to have auto-complete to see what parameters are available.

It would be great to have this work for calling shiny modules as well, if it's possible at all. Unfortunately shiny modules are called in a different way, so it wouldn't be as straight forward.

Example:

```
library(shiny)

testUI <- function(id, param1) {}
test <- function(input, output, session, param2) {}

ui <- fluidPage(
    testUI("id", param1 = "foo")
)

server <- function(input, output, session) {
    callModule(test, "id", param2 = "foo")
}

shinyApp(ui = ui, server = server)
```

When calling the module's UI function, `testUI()`, auto complete works to show you the parameters, since it works like any regular function. But when writing the server portion, because we have to use `callModule()`, it doesn't recognize the module function and doesn't show us the potential arguments. It would be nice to see `param2` suggested after writing out `callModule(test, "id", `

**Comment by ronblum** [comment]
@daattali Thank you for the suggestion. We'll review and consider it as we continue work on future releases of RStudio. (Also, confirmed this on RStudio Desktop 1.2.1335 on MacOS 10.14.)
