### ISSUE TITLE
RMarkdown PDF export has cropped images

### ISSUE THREAD

**Issue by arno-h** [rstudio/rstudio#4806]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Linux Debian 9+ (using testing release, i.e. currently close to Debian 10)
    R Version       : 3.5.2

### Steps to reproduce the problem

Create a rmarkdown file with simple content like this:

```
---
title: "Test"
author: "Me"
output: pdf_document
---
```{r}
library(knitr)
` ``
This worked fine, just an update ago, but now it doesn't:

```{r}
plot(x <- 0:100, dbinom(x, size=100, prob=0.6), type='l',
     main="Cut off at the top", xlab="Looks good", ylab="Nok")
` ``
```

### Describe the problem in detail

Main title and ylab are cut off (cropped); xlab is ok.

### Describe the behavior you expected

Title and ylab not cropped / cut off...

### Additional system info

* rmarkdown (R package): 1.12
* knitr (R package): 1.22
* graphics (R package): 3.5.2
* texlive-base (Debian package):  2018.20190227-2
* texlive-binaries (Debian package):  2018.20181218.49446-1
* texlive-extra-utils (Debian package): 2018.20190227-2
* pandoc (Debian package): 2.2.1-3+b2

### Possible cause

I tracked down the error using knitr's hooks. Using `hook_plot_tex()` I verified that the generated PDF for the image is correct (i.e. labels not cropped and readable). Using `hook_pdfcrop()` I can see that the PDF chunk is mangled in that step (i.e. labels get cut off).

I'm not sure who is to blame: whether it's an error in RStudio, knitr, or pdfcrop.

### Workaround

```r
knitr::knit_hooks$set(crop = function(before, options, envir) {})
```

**Comment by pascaloettli** [comment]
RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Ubuntu 18.04.2
    R Version       : 3.6.0
    
It seems to work for me:

    

![Screenshot from 2019-05-20 13-43-35](https://user-images.githubusercontent.com/6613954/57996964-4ee20900-7b05-11e9-8337-f12fdc2e9770.png)

    rmarkdown version : 1.12  
    knitr version     : 1.23
    texlive-base      : 2017.20180305-1
    texlive-bin       : 2017.20170613.44572-8ubuntu0.1

**Comment by arno-h** [comment]
Well, it worked for me too, until the latest update I made :(
Here are my pandoc versions:

```
> rmarkdown::pandoc_available()
[1] TRUE
> rmarkdown::pandoc_exec()
[1] "/usr/lib/rstudio/bin/pandoc/pandoc"
> rmarkdown::pandoc_version()
[1] ‘2.3.1’
```

Other versions (knitr etc.) see above. With my versions, the resulting image looks like:

![Screenshot_2019-05-21_08-56-24](https://user-images.githubusercontent.com/6217381/58074816-6d4c1100-7ba6-11e9-83f9-6d31430d057b.png)

The odd thing is: if I run the following steps manually, the resulting diagram is ok'ish (although not all TeX styles are applied):

```
R> knitr::knit('test.Rmd', 'test.knit.md')
shell> # running same command as shown in markdown log window
shell> /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS test.knit.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.tex --template /home/arno/R/x86_64-pc-linux-gnu-library/3.5/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --pdf-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' --variable 'compact-title:yes'
shell> pdflatex test.tex
```

Resulting PDF is 2 pages long:

Page 1:
![image](https://user-images.githubusercontent.com/6217381/58075123-2ca0c780-7ba7-11e9-9c6b-da3e79b73ff1.png)

Page 2: 
![image](https://user-images.githubusercontent.com/6217381/58075159-44784b80-7ba7-11e9-9a1c-ba3053387849.png)

**Comment by pascaloettli** [comment]
I switched for `pandoc` provided by `rstudio` and for `texlive` version 2018, and I still get the correctly formatted file.

**Comment by arno-h** [comment]
@pascaloettli Thanks for looking into this. As this seems to exclude texlive, I digged deeper: it looks like Ghostscript is the culprit (unless an invalid/slightly malformed PDF was produced by knitr or so...)

Here's what I did:

I captured the intermediate PDF that is created for the diagram. As pointed out above, the diagram is intact, labels are visible.

I ran `pdfcrop diagram.pdf cropped.pdf` as this is the way `knitr/rmarkdown` calls pdfcrop. Result: labels are cut off. Next I ran pdfcrop with `--debug`. With Ghostscript 9.27 (Debian: 9.27~dfsg-1) here's the bounding box I get:

```
Loading NimbusSans-Regular font from /usr/share/ghostscript/9.27/Resource/Font/NimbusSans-Regular... 4377152 2884143 5563840 4228395 5 done.
Loading NimbusSans-Bold font from /usr/share/ghostscript/9.27/Resource/Font/NimbusSans-Bold... 4463464 3070252 5604240 4267359 5 done.
%%BoundingBox: 12 11 439 293
* Page 1: 12 11 439 293
%%HiResBoundingBox: 12.708000 11.412000 438.135034 292.031991
```

Downgrading to Ghostscript 9.26 (Debian package: 9.26a~dfsg-0+deb9u3) the diagram is cropped properly. Here's the output from Ghostscript:

```
Loading NimbusSans-Regular font from /usr/share/ghostscript/9.26/Resource/Font/NimbusSans-Regular... 4598228 2996812 5563840 4228489 5 done.
Loading NimbusSans-Bold font from /usr/share/ghostscript/9.26/Resource/Font/NimbusSans-Bold... 4664340 3179385 5604240 4268355 5 done.
%%BoundingBox: 4 15 439 300
* Page 1: 4 15 439 300
%%HiResBoundingBox: 4.212000 15.102000 438.135034 299.825991
```

Quite a different bounding box...

So unless the PDF itself has a flaw (I don't think so), this seems to be a bug in Ghostscript (or how pdfcrop uses Ghostscript). So I guess it's ok to close this issue.

**Comment by pascaloettli** [comment]
Yes, there was a bug in version [9.27~dfsg-1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927429), which should be fixed with version 9.27~dfsg-2. Definitively not a Rstudio issue.

**Comment by arno-h** [comment]
Thank you for your help & guidance.

**Comment by baderstine** [comment]
I was experiencing the same problem, all my plot margins were set so that they cutoff the y-axis labels and titles when I compiled .Rmd files to PDF on my Mac.  I had Mactext 2019 installed.  Based on this conversation, I uninstalled 2019 and installed Mactext 2020 (which has a newer version of ghoscript)... problem solved.  But man that was hard to track down.
