### ISSUE TITLE
Commented line without trailing whitespace breaks uncommenting

### ISSUE THREAD

**Issue by JanMarvin** [rstudio/rstudio#4808]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335 (latest github master branch version at that time)
    OS Version      :  Arch Linux
    R Version       :  3.6.0

### Steps to reproduce the problem

Open a new R script. Add the comment char "#". Try to uncomment it using Ctrl+Shift+C. 

### Describe the problem in detail

Since release 1.2 it is not possible to uncomment a single char `#` or a region containing such line. It seems as if the uncomment function checks for `# ` (comment char followed by a trailing whitespace) in all lines and does nothing otherwise. I see the same behavior with C++ comments.

### Describe the behavior you expected

Any comment char should be removed, if a trailing whitespace is added, this should be removed either.

**Comment by JanMarvin** [comment]
I can add that I can not reproduce this on windows 10 pro with the rstudio.com binaries, so it might be my build.

**Comment by pascaloettli** [comment]
Interesting

     RStudio Edition : Desktop
     RStudio Version : 1.2.1335, 1.2.1511
     OS Version      : Ubuntu 18.04.2
     R Version       : 3.6.0

Not reproducible

     RStudio Edition : Desktop
     RStudio Version : 1.3.180 
     OS Version      : Ubuntu 18.04.2
     R Version       : 3.6.0

Partly reproducible:
with `#`, <kbd>Ctrl+Shift+C</kbd> only highlight `#`, 
with `# `, <kbd>Ctrl+Shift+C</kbd> comments/uncomments the line,

**Comment by kevinushey** [comment]
Thanks @pascaloettli -- I can confirm that the presence of a space (e.g. `#` vs. `# `) affects the behavior here.

**Comment by JanMarvin** [comment]
works again in build 8bf99466 (I do not build regularly anymore so no clue which commit fixed it)
