### ISSUE TITLE
Syntax highlighting for Critic Markup in R Markdown and Markdown files

### ISSUE THREAD

**Issue by noamross** [rstudio/rstudio#4811]
I would like to see syntax highlighting for [Critic Markup](http://criticmarkup.com/spec.php) syntax (editing syntax for insert/delete/substitute/comment) in the RStudio text editor. 

My understanding is that this requires adding the regex-based rules for CriticMarkup to this Ace syntax highlighting file: https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/gwt/acesupport/acemode/markdown_highlight_rules.js

The syntax highlighting would not have to be activated by default, but by capturing this text then custom themes could highlight it if desired.

Would you accept a PR for this?

**Comment by ronblum** [comment]
@noamross Thank you for the suggestion!

@jmcphers Thoughts regarding accepting a PR?

**Comment by jmcphers** [comment]
Yes, we'd take a PR for this.

**Comment by sorenoneill** [comment]
+1 

This would be a great addition to RStudio ... especially so, if it was possible to automatically generate a CriticMarkup highlighted version of a document on the basis of previous (git) versions. 

That way, git could be used to track version changes and CriticMarkup to highlight those changes in the output format (pdf, odt etc) for collaborators not using R or markdown.
