### ISSUE TITLE
`To Source File Location` is unavailable after returning source file to main window

### ISSUE THREAD

**Issue by dennismalandro** [rstudio/rstudio#4814]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.x & 1.3.x
    OS Version      : Windows 10
    R Version       : 

### Steps to reproduce the problem

1. Have >1 source file tabs open in main window
2. Show a source file in new window
3. Return the source file to main window
4. Select `Session -> Set Working Directory`

### Describe the problem in detail

`To Source File Location` is unavailable (_i.e._, is "grayed out")

### Describe the behavior you expected

`To Source File Location` to be available

**Comment by ronblum** [comment]
@dennismalandro Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

The graying-out applies to all tabs, not just for the source file that was popped out. Not an issue on RStudio Desktop on MacOS 10.14.
