### ISSUE TITLE
Printing code on Ubuntu loses lines

### ISSUE THREAD

**Issue by mkvasnicka** [rstudio/rstudio#4815]
Hi!

When I print my code in RStudio Version 1.2.1335 on Ubuntu 18.10 with Java1.8.0_201, some lines of code are lost at edges of pages. It is visible even in the Print Preview. A possible reason might be that the bottom margin is too high and it covers some lines of code. I'm printing on A4 and leave all settings to defaults.

As far as I know, this problem appeared in this version of RStudio---printing was ok in earlier versions.

Best wishes,
Michal Kvasnička

**Comment by pascaloettli** [comment]
Are you printing in landscape or in portrait? I do see a problem in landscape mode but not in portrait.

**Comment by mkvasnicka** [comment]
In the portrait mode. R version 3.6.0 (2019-04-26).

**Comment by ronblum** [comment]
@mkvasnicka and @pascaloettli Thank you for raising the issue. I can reproduce it on Ubuntu 18.04 using RStudio Desktop 1.2.1335. We'll review it as we continue ongoing development of RStudio.

**Comment by baderstine** [comment]
same problem in Mac OS.  Landscape mode.

**Comment by kevinushey** [comment]
I wonder if this Qt bug is related? https://bugreports.qt.io/browse/QTBUG-71600?jql=text%20~%20%22QPrintPreviewDialog%22%20ORDER%20BY%20created%20DESC

**Comment by kevinushey** [comment]
A reproducible example would also be helpful.

**Comment by ronblum** [comment]
Printing the default Rmd file (File -> New File -> R Markdown) reproduces the error on MacOS 10.14.6 with RStudio Desktop 1.2.1522.

**Comment by kevinushey** [comment]
Thanks! I can reproduce as well.

**Comment by ronblum** [comment]
Verified using RStudio Desktop 1.2.1539 on MacOS 10.14.6 and Ubuntu 18.04.2.
