### ISSUE TITLE
"Collapse All" (Alt+O) not working when section preceded by five hash symbols

### ISSUE THREAD

**Issue by RemPsyc** [rstudio/rstudio#4816]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem

Minimal reproducible example:

```
# Section 1 ####
# This will collapse with Alt+O

#####
# Section 2 ####
# This will not collapse with Alt+O
```

### Describe the problem in detail

Folding won't work if section is preceded by another line of at least five hash symbols. Is this a bug or feature? I often add lines of hash symbols before large sections when I have very long scripts for readability, but then we lose this precious folding feature.

### Describe the behavior you expected
I expect all sections to fold if the heading contains at least 5 hash symbols (like for Section 1 in the example above).

Note: I mistakenly posted this bug in the forums at first: https://community.rstudio.com/t/collapse-all-alt-o-not-working-when-section-preceded-by-four-dashes/31061.

**Comment by ronblum** [comment]
Thank you for raising this issue. We will review it as we work on development of future versions of RStudio.

Reproduced using RStudio Desktop 1.2.1335 on MacOS 10.14 and Windows 10, and RStudio Server on Red Hat 7.6. This was also an issue in 1.1.463, so this is not a regression.

Note a correction: this is an issue with at least five hash symbols.
