### ISSUE TITLE
re-check available packages for install on document focus

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4818]
https://community.rstudio.com/t/packages-required-but-not-installed-re-check-on-tab-focus/29798

> RStudio's "packages [x,y,z] required but not installed" prompt is lovely. One small tweak - could it be made to refresh/recheck when script tabs are re-focused? It seems these checks are all performed at startup, so if one fires up RStudio with (e.g.) the same script loaded 5 times, the prompt will suggest users install those same packages 5 times, i.e. it doesn't check to see whether they're already installed.

**Comment by jmcphers** [comment]
Would be helpful but not a must have for 1.3.
