### ISSUE TITLE
help.search() no longer works with R 3.6.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4819]
https://community.rstudio.com/t/help-search-not-working/29920

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.2.1335
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : R version 3.6.0 (2019-04-26)

### Steps to reproduce the problem

Try to invoke e.g. `help.search("linear models")`.

### Describe the problem in detail

No search results are found.

### Describe the behavior you expected

We should be able to search for the query without issue.

**Comment by jmcphers** [comment]
Other R 3.6 issues (all really the same deal): https://github.com/rstudio/rstudio/issues/4441, https://github.com/rstudio/rstudio/issues/4752, https://github.com/rstudio/rstudio/issues/4723, https://github.com/rstudio/rstudio/issues/4787. We may need to do a 1.2 service release (from the 1.2 branch) prior to 1.2-patch.

**Comment by kevinushey** [comment]
I believe this is caused by this change in R:

https://github.com/wch/r-source/commit/6704899aacb42e3a9098a4b30403c73e91e8bbee

The problem here is that the port reported and used differs when R attempts to store the results of the search, and later retrieve them when building the Help page. This code helps trace what's going on:

```
debugonce(tools:::httpd)
debug(tools:::.httpd_objects)
help.search("linear models")
```

When `help.search()` is called, a set of topics are found and then are 'saved' using the `.httpd_objects()` function. This gets saved with some port, which is the output of `tools::startDynamicHelp(NA)`. However, later on, `httpd()` is invoked with a different port. Because of the mismatch in ports, R doesn't discover the previously-saved help objects and just reports a 'No results found' page.

More concretely, from what I'm seeing, R asks us to browse to this URL:

```
http://127.0.0.1:22580/doc/html/Search?objects=1&port=22580
```

But the actual URL that the Help pane page points to is:

```
http://127.0.0.1:31077/help/doc/html/Search?objects=1&port=31077
```

I'm guessing we have a filter or something similar that transforms the port in the URL; we likely only want to transform the first instance of that port.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.2.1526 on Windows 10.

**Comment by Adam-Origamiiris** [comment]
System details

```
RStudio Edition : Desktop [Open Source]
RStudio Version : 1.2.1335
OS Version      : macOS Mojave (version 10.14.5)
R Version       : R version 3.6.0 (2019-04-26)
Steps to reproduce the problem

```
Try to invoke e.g. help.search("linear models"), in Rstudio console.

Describe the problem in detail

No search results are found.
Searching in R run from Terminal produces results.

Describe the behavior you expected

We should be able to search for the query without issue.

**Comment by ronblum** [comment]
@Adam-Origamiiris This appears to be the same issue as described above. Have you tried [the latest preview release](https://www.rstudio.com/products/rstudio/download/preview/)? It contains a fix for this.

**Comment by Adam-Origamiiris** [comment]
@ronblum The fix works, Thanks

**Comment by ronblum** [comment]
@Adam-Origamiiris Good to know—thanks for checking!
