### ISSUE TITLE
provide improved error page when connection failure occurs

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4820]
Currently, we show the default Chromium error page, e.g.

![55041183-53f17300-5002-11e9-842e-167d389db448](https://user-images.githubusercontent.com/1976582/58138353-8bd3fb80-7bea-11e9-9ab3-6ba937e12028.png)

We should think about whether we could show something a bit more descriptive.

**Comment by jmcphers** [comment]
I have implemented this in https://github.com/rstudio/rstudio/pull/5509.
