### ISSUE TITLE
Unexpected syntax highlighting in Rmd chunks

### ISSUE THREAD

**Issue by atusy** [rstudio/rstudio#4821]
### System details

    RStudio Edition : Server (rocker/verse:latest and devel)
    RStudio Version : 1.2.1335
    OS Version      : Manjaro Linux
    R Version       : 3.5.3 (rocker/verse:latest)
                      3.7.0 (rocker/verse:devel)

### Steps to reproduce the problem

1. Create new Rmd file
2. Create `asis` chunk (or `css`)
3. Write some R code

### Describe the problem in detail

Although `asis` and `css` chunks are intended to be text and CSS scripts, respectively,
they are highlighted as if they are R code.
If I create some original knitr engines, they will also be highlighted as if they are R code.

![image](https://user-images.githubusercontent.com/30277794/58140777-85419480-7c7b-11e9-827b-13ea3ecb798b.png)

### Describe the behavior you expected

Chunks with `asis` or original engines should not be highlighted
(`asis` can be highlighted as if `markdown` script)

Chunks with `css` engine should be highlighted by the syntax of `CSS`.

**There may be some more chunks with unexpected syntax highlights.**
I haven't checked all.

**Comment by atusy** [comment]
I wish this issue be solved.

**Comment by joelnitta** [comment]
This is especially problematic with CSS where `#` is valid code (id selector) and not a comment. +1 for re-opening and resolving this issue. Thanks!
<img width="363" alt="css_example" src="https://user-images.githubusercontent.com/13459362/125543974-1ddac3df-0633-463f-8501-16303c290a9a.png">

**Comment by ronblum** [comment]
Confirmed that CSS chunks appear to be using CSS highlighting, and ASIS chunks don't use any. Verified in:
- RStudio Desktop 1.5.232 on MacOS 12 beta
- RStudio Server 1.5.233 on Ubuntu 20.04.2 via Safari on MacOS 12 beta

Note: Used the following code, transcribed from the screenshots above.

````
```{asis}
aaa
#bbb
library(ggplot)
```

```{css}
h1.test {
	font-size: 10px;
}
library(ggplot)
```

```{css, style, echo = FALSE}
#title code {
  color: inherit;
  font-size: inherit;
  background-color: transparent;
}
```
````
