### ISSUE TITLE
do not close shell windows after closing RStudio

### ISSUE THREAD

**Issue by omstats** [rstudio/rstudio#4823]
I often use R (on Windows) to start many independent shell processes in external windows; e.g.:
shell("start cmd /K [run batch script]")

Once I close R the shell windows stay open and keep running. If I do this from within RStudio and then close RStudio it will close all shell windows.

While this might be a desirable behaviour for some users I would prefer to have the option that those windows are not closed when RStudio is closed. This since it is standard procedure (at least for pure R and other CMD instances) that a process called with "start" is not closed if the program from which it was launched is closed.

**Comment by ronblum** [comment]
@omstats Thank you for the suggestion! We'll take a look at it as we continue development of RStudio.
