### ISSUE TITLE
Set the HTTPUserAgent Header Option to Include the R Version 

### ISSUE THREAD

**Issue by slopp** [rstudio/rstudio#4826]
Beginning in R 3.6, there are a number of cases where the http user agent header no longer includes the R version. 

https://github.com/wch/r-source/commit/def075db88ae87104c38437a57e9327b078bb804#diff-b499547952f75d41253bb11901257375R252

Instead, R recommends setting the header through the `HTTPUserAgent` option. 

It would (re)-enable quite a few use cases if RStudio were to set this option by default, including access to RStudio Package Manager package binaries.

RStudio could allow users to disable this behavior to prevent the case that motivated R to remove the header.

**Comment by kevinushey** [comment]
Any proposal on what the user agent should look like? The default format is something like:

```
> getOption("HTTPUserAgent")
[1] "R (3.5.3 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)"
```

Should that just be `RStudio` instead of `R`?

**Comment by slopp** [comment]
Yea, the specific form could vary, we're primarily interested in the R version. OS information is also interesting, but otherwise I don't have a strong opinion on the format. RStudio feels safer than R! 

JJ had also suggested that in the case a user agent header already exists we could concatenate with ours (altogether these two moves, IMO, make it feel less of a "reversal" of R behavior).

**Comment by ronblum** [comment]
Verified using RStudio Desktop and Server:

```
> getOption("HTTPUserAgent")
[1] "RStudio Server (1.2.1539); R (3.6.0 x86_64-redhat-linux-gnu x86_64 linux-gnu)"
```
```
> getOption("HTTPUserAgent")
[1] "RStudio Desktop (1.2.1539); R (3.5.2 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)"
```
```
> getOption("HTTPUserAgent")
[1] "RStudio Desktop (1.2.1539); R (3.6.0 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)"
```
