### ISSUE TITLE
No help found for topic graphical%20parameters in any package.

### ISSUE THREAD

**Issue by BastiHz** [rstudio/rstudio#4829]
### System details

    RStudio Edition: Desktop
    RStudio Version: 1.2.1335 and 1.2.1522
    OS Version: Windows 10 and Kubuntu 18.04.2
    R Version: 3.6.0

### Steps to reproduce the problem
1. Open the help for "box" (from the graphics package) in the help pane.
2. In the "Arguments" section click on the link to "graphical parameters".

alternative:
1. Open the help for "InternalMethods" in the help pane.
2. Click on the link to "group generic".

### Describe the problem in detail
An error is displayed:
`No help found for topic graphical%20parameters in any package.`

or with the alternative:
`No help found for topic group%20generic in any package.`

### Describe the behavior you expected
The links should work. Other links work fine so this may have something to do with the withespace in the middle?

**Comment by kevinushey** [comment]
Thanks for the bug report! I can reproduce this on Windows as well, but not on macOS or Linux. It looks like the URL is getting double-encoded by accident.

Internal note:

![Screen Shot 2019-05-23 at 2 38 56 PM](https://user-images.githubusercontent.com/1976582/58288470-88667e80-7d68-11e9-8b08-eba182030e85.png)

**Comment by ronblum** [comment]
Confirmed in RStudio Desktop 1.2.1551 on Windows 10.
