### ISSUE TITLE
Download R prompt not opening download page in Windows EC2 Machine

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#4833]
Not sure if this is specific to Windows Server or Amazon EC2 instances, but the prompt to download R and redirect to the R download page does not seem to be working:

<img width="504" alt="Screen Shot 2019-05-23 at 5 35 45 PM" src="https://user-images.githubusercontent.com/3478847/58295016-d63bb080-7d81-11e9-8e87-f02d3ef2ed2f.png">

<img width="582" alt="Screen Shot 2019-05-23 at 5 35 50 PM" src="https://user-images.githubusercontent.com/3478847/58295017-d63bb080-7d81-11e9-9102-d3e8fb938d33.png">

Accepting prompt closes the dialog but no browser is launched.

**Comment by gtritchie** [comment]
Dup of #3068
