### ISSUE TITLE
RStudio Desktop 1.2.1335 on 4K dell laptop screen issue

### ISSUE THREAD

**Issue by papageorgiou** [rstudio/rstudio#4834]
https://photos.app.goo.gl/oxbnb5TdyfeLZkeu9

this happens when I scroll down and at times there is rectangle on the lower part of the screen that displays something unexpected which should be somewhere else in the window. 
Minor issue, it might last for fractions of a second and slightly moving the mouse up or down will fix it, but FYI

**Comment by pascaloettli** [comment]
Please provide requested information:
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

Also, did you try to change the rendering engine?

**Comment by papageorgiou** [comment]
RStudio Edition : <Desktop >
RStudio Version : 1.2.1335
OS Version      :  Windows 10
R Version       :  3.5.2  

Will try toggling the rendering engine once I am on the laptop

**Comment by dschneiderch** [comment]
same here.

R 3.5.3
Windows 10
Dell XPS 15 with HP 227n running 3840x2160
I have not noticed the issue directly ont he labtop (although not extensively tested)

RStudio
Version 1.2.1335
© 2009-2019 RStudio, Inc.
Build 1379 (f1ac3452)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

**Comment by gtritchie** [comment]
Retry once we have Electron builds.

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by ronblum** [comment]
Closing this as fixed by Electron. If anyone using builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) continues to run into this issue, please let us know!
