### ISSUE TITLE
Flashing Interface on RStudio 1.2

### ISSUE THREAD

**Issue by tiaradwiputri** [rstudio/rstudio#4835]
### System details

    RStudio Edition : Rstudio Desktop
    RStudio Version : Version 1.2.1335
    OS Version      :  Windows 10
    R Version       :   R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
    Platform: x86_64-w64-mingw32/x64 (64-bit)

My machine is Dell XPS 13 4K, FYI, I encountered a similar issue report but has no response yet.

### Steps to reproduce the problem

Basically I just purchased a new laptop and installed a brand new R and R Studio version in my machine. I've tried installing and reinstalling the software but the problem seems to persist.

### Describe the problem in detail

Here's the screenshot of the flickering screen:

![rbugs](https://user-images.githubusercontent.com/8868527/58312095-36f1da00-7dd0-11e9-87bb-f0d0e5adfe57.png)

It happens every time I scroll across RMarkdown files, the image starts to flicker and shows a random screen position from different places. I've attached a diagnostic report from my machine.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3215791/diagnostics-report.txt)

**Comment by pascaloettli** [comment]
Does it happen if you switch the Rendering engine to `Software`?

**Comment by tiaradwiputri** [comment]
I've tried to change it and it works! Thank you!

For those that encountered similar issue go to Tools > General > Advanced > Rendering engine:
Pick `software`, click apply, the RStudio will restart and you should be good to go.

**Comment by hilary-rose** [comment]
Thank you for this--I was having the same issue!

**Comment by daxiagithub** [comment]
Similar issue with the latest Rstudio on Windows 10.  The change fixed the issue.  Thanks!

**Comment by rafaeljjd** [comment]
Same issue, very annoying, got fixed. Thanks!

**Comment by sandyplus** [comment]
Same issue, very annoying. Finally, it got fixed. Thanks!

**Comment by NatiaJ** [comment]
same issue! Thanks, fixed!
