### ISSUE TITLE
Rstudio slow on git projects (w/ Windows + enterprise security software)

### ISSUE THREAD

**Issue by brshallo** [rstudio/rstudio#4837]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335

``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
#>  [5] tools_3.5.1     htmltools_0.3.6 yaml_2.2.0      Rcpp_1.0.0     
#>  [9] stringi_1.2.4   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
#> [13] digest_0.6.18   evaluate_0.11
```

<sup>Created on 2019-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### Steps to reproduce the problem
Render .Rmd file in Rstudio in a repository with git set-up on Windows machine with enterprise security software Avecto Defendpoint.

### Describe the problem in detail

On my Windows work computer, in Rstudio Desktop, after knitting documents, projects with git are EXTREMELY slow to open the Rstudio preview browser. Rstudio seems to be affected more than the underlying R process. For example, when I check the folder (with Windows File Explorer), I will see the files have successfully rendered and I can open them with Chrome, etc. even though the RStudio preview browser will still not successfully display the rendered file for a few minutes.  Rstudio performance, in general, often becomes significantly degraded (e.g. "Files" pane is slow updating and I'll find saving files, opening new files, etc. becomes unresponse or highly delayed).

When encountring this I've also noticed our enterprise security software [Avecto Defendpoint](https://www.nuvias.com/vendors/avecto/) becomes hyperactive in its CPU usage (I checked this using "task manager").

These issues do not show-up when knitting identical files on non-git respositories. *For repositories that do have git, if I disable Rstudio's git interface (but keep git on the respoitory) the issue also goes away* ("Tools" --> "Global Options" --> "git/svn" --> deselect "Enable verson control for Rstudio projects"; disabling on just the project also fixes the problem).

Here is an example [file](https://gist.github.com/brshallo/9c1d199d2956466d64427c24a377d329) I've used to test this behavior. If I knit this file in a repo with git, Rstudio is extremely slow whereas if I run it in a repo without git (or disable Rstudio's git interface) it seems to run normally.

I first referenced this on this [thread](https://github.com/STAT545-UBC/Discussion/issues/354#issuecomment-409009389) (sorry to @kevinushey for the slowness in creating a new issue as recommended). I've seen some threads on Rstudio community and elsewhere that I thought might be a related problem (e.g. [here](https://community.rstudio.com/t/script-runs-nearly-20-times-slower-in-a-different-project/29864)). Though, outside of localizing this to some kind of git-Avecto-Rstudio interaction, I'm not sure what is going on. 

Let me know if there is other information I should provide, or things you recommend I try (my current action has been to usually disable Rstudio's git interface). I've also opened a ticket with our IT and they've opened a ticket with Avecto (so if there are notes/actions I should forward their way -- and require admin access -- please let me know).

**Comment by kevinushey** [comment]
One other thing worth confirming: is the `.git` folder in your project directories hidden or not? (I recall that a previous version of this issue was resolved if the user made sure to re-hide the `.git` folder, as it had somehow lost that attribute)

**Comment by brshallo** [comment]
Yes, verified that `.git` folder is hidden.
![check-hidden](https://user-images.githubusercontent.com/30487784/58349403-27ef4400-7e31-11e9-8b75-a7061644cc8d.JPG)

**Comment by brshallo** [comment]
I had also logged a ticket with our internal IT support team who forwarded the issue to BeyondTrust.  They ultimately came back with the following response:

> BeyondTrust support has exhausted all options to improve the CPU utilization of the Defendpoint service, the company policy and Git/RStudio. The improvements we worked on with them are active in the production policy today.
>  
> The Rstudio/Git combination sends hundreds or thousands of processes into the Defendpoint service, which unfortunately cannot process that much that rapidly. This is why we still see the delay in rendering the R documents even with a blank policy.
>  
> At this point we have no next steps as far as troubleshooting. I'd like to resolve the ticket as...

Note that the issue is more with the RStudio browser not opening and RStudio becoming slow / unresponsive (the file itself may render -- and could be opened from Chrome etc. -- but will not display in the Rstudio browser for maybe a couple minutes and other RStudio functionality also seems to slow down).

**Comment by jmcphers** [comment]
We are now tracking this in https://github.com/rstudio/rstudio/issues/4368.
