### ISSUE TITLE
Source Pane Doesn't Work Anymore

### ISSUE THREAD

**Issue by soarsapien** [rstudio/rstudio#4851]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.2.1335
    OS Version      : Linux Mint 19
    R Version       : 3.6.0 (2019-04-26)

### Describe the problem in detail

Actually what I had done was update by using sudo apt-get update && sudo apt-get upgrade todey (10:00 GMT+8)
And when I restart rstudio, source pane didn't work anymore..
![rs](https://user-images.githubusercontent.com/21299118/58394907-37ac9980-8078-11e9-9ad6-fea96adba702.png)

I cannot create any new script/File and also cannot open any script

I try to remove them (r-base-core, rstudio) and reinstall again, 
but still didn't work

Any information I need to provide to diagnosis this...problem?

( By the Way, I have same problem with issue #4500 )

Thank You

**Comment by pascaloettli** [comment]
What do you get if your change the Rendering engine to "Software"?

**Comment by soarsapien** [comment]
Thank You for Your Kindly Rescue~

First
Second Method Didn't work, I cannot change this setting...( Similar situation when I try to change Editor Font, same with #4500 , but I can change Rstudio theme, and font size )
![rs3](https://user-images.githubusercontent.com/21299118/58397229-9bd45b00-8082-11e9-9245-3b340efc45ec.png)

After I use first method, move rstudio desktop to backup , source pane is back
![rs2](https://user-images.githubusercontent.com/21299118/58397218-924af300-8082-11e9-8230-b6d4eb603184.png)

Is there any helpful information I can provide? or information I should know?

Thank You Very Much

**Comment by pascaloettli** [comment]
You can now change the theme and font size. And continue using RStudio.
