### ISSUE TITLE
Copying a plot to clipboard has extra border and resizing triangle

### ISSUE THREAD

**Issue by douglaswhitaker** [rstudio/rstudio#4864]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      :  Windows 10 (Microsoft Windows [Version 10.0.17134.765])
    R Version       :  R version 3.6.0 (2019-04-26) -- "Planting of a Tree" 64-bit

### Steps to reproduce the problem
1. Create a plot
`plot(iris$Sepal.Length~iris$Sepal.Width)
`
2. Copy to clipboard
In the side window, click: Export -> Copy to Clipboard... -> Copy Plot
3. Paste the plot (for example, in Microsoft Word)

### Describe the problem in detail
![2019-05-30 09_50_02-Document10 - Word](https://user-images.githubusercontent.com/11415345/58633975-7339a480-82c0-11e9-8c50-12849fc84f85.png)

The red arrows indicate a partial border in the image. The red circle is also part of the image (the sizing triangle from the Copy to Clipboard... dialog box). 

This does NOT occur when saving the image to file using the same dialog box. 
### Describe the behavior you expected
I expect the image from the Copy Plot button to match the image saved using the dialog box. That is, I do not expect a border or sizing triangle to appear.

It looks like the same issue was reported [on the RStudio Community forum](https://community.rstudio.com/t/exporting-plot-into-word-via-clipboard-pastes-unexpected-outline-or-borders/28491) but I could not find an issue on GitHub for it. Sorry if it is a duplicate.

Edits: two minor typos

**Comment by ronblum** [comment]
@douglaswhitaker Thank you for reporting the issue. We'll review this as we continue development of RStudio.

Reproducible on Ubuntu 18.04 and Windows 10. See also #3353.

**Comment by kevinushey** [comment]
This is something that we intended to fix for v1.2, so going to mark as v1.2-patch.

**Comment by kevinushey** [comment]
@douglaswhitaker can you also confirm whether you're using a high DPI or regular DPI monitor?

**Comment by douglaswhitaker** [comment]
@kevinushey I'm using a laptop (standard DPI) with a monitor (also standard DPI). The behavior occurs if RStudio is on either display. 

![image](https://user-images.githubusercontent.com/11415345/58763618-74bed300-8533-11e9-948b-7b2e9928770d.png)

**Comment by ronblum** [comment]
Verified using RStudio Desktop 1.2.1539 using MacOS 10.14.6, Ubuntu 18.04.2, and Windows 10.

**Comment by winsonyeap94** [comment]
May I know what is the status for this and if we're waiting for a new update? Just updated my RStudio version to 1.2.1335 yesterday and have started to experience this similar issue as well.

`RStudio Edition: Desktop
RStudio Version: 1.2.1335
OS Version: Windows 10 Enterprise 2015 LTSB
R Version:  R version 3.6.0 (2019-04-26) -- "Planting of a Tree" 64-bit`

**Comment by kevinushey** [comment]
This should be fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/), if you want to give that a try.

**Comment by winsonyeap94** [comment]
@kevinushey Thanks for the reply, I have tested the 1.2.1541 preview release and it is working. Glad that it's fixed!

**Comment by kevinushey** [comment]
Great! Glad to hear it :-)

**Comment by hmeeks** [comment]
Hi, I have Rstudio Desktop version 1.2.5042 and I'm running into the same problem. I'm using Windows 10 Enterprise. Thanks!

**Comment by Radibor** [comment]
Same problem here. Using Version 1.3.1093. Sometimes 2 borders appear, sometimes 1.

**Comment by rtguth** [comment]
I have RStudio 2021.09.0+351.   In addition to the extra borders the resolution is quite poor for me when copying using bitmap.  For pasting into PPT the following works: copy as a metafile (not bitmap) and paste.  If you don't like the appearance (thin fonts) then re-copy in PPT and paste as a picture.  Not ideal but it removes the borders and keeps the original appearance of the bitmap.
