### ISSUE TITLE
Code chunk execution and history whitespace issues in reticulate / python

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#4865]
Related to https://github.com/rstudio/rstudio/issues/4215

While executing multi-line, indented sections line-by-line (with `CTRL` + `ENTER`) in reticulate / `repl_python` work:

- Executing multi-line, indented sections as a chunk (with `CTRL` + `ENTER`) in reticulate / `repl_python` does _NOT_ work
-  Copying / pasting multi-line, indented sections as a chunk (with `CTRL` + `ENTER`) from a python script to the `repl_python` console does _NOT_ work

These latter issues may be `reticulate` problems, but I'm not sure where the demarcation of responsibility is between RStudio / `reticulate`.

As an example, use the following Python script:

```python
def myfunc(arg = 'test', arg2 = 'blah'):
  print(arg + ' ' + arg2)

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def myfunc(self):
    print("Hello my name is " + self.name)
  def test(self, add, another = 0):
    total = int(self.age) + int(add) + int(another)
    print("Hello my add age is " + str(total))

p1 = Person('cole', 4)
p1.test(4,5)
```

Highlighting and executing the "Person" chunk fails, as does copying / pasting it into the `repl_python` console. Executing it line by line works.

In each case, the history is set up line-by-line (not in code chunk form), which is less than ideal when defining functions / etc. 

Related on the line-by-line versus code-chunk history. https://github.com/rstudio/rstudio/issues/4503

**Comment by kevinushey** [comment]
To be clear, are you talking about a Python chunk within an R Markdown document, or just a standalone Python document? I don't think it's actually possible to execute Python chunks line-by-line in R Markdown -- the entire chunk is always submitted.

**Comment by colearendt** [comment]
Sorry for not clarifying, this is just a standalone Python document

**Comment by kevinushey** [comment]
Strange -- it works fine for me, then.

```
> reticulate::repl_python()
Python 3.7.3 (/Users/kevin/.virtualenvs/r-reticulate/bin/python)
Reticulate 1.12.0.9000 REPL -- A Python interpreter in R.
>>> class Person:
...   def __init__(self, name, age):
...     self.name = name
...     self.age = age
...   def myfunc(self):
...     print("Hello my name is " + self.name)
...   def test(self, add, another = 0):
...     total = int(self.age) + int(add) + int(another)
...     print("Hello my add age is " + str(total))
... 
>>>
```

**Comment by ronblum** [comment]
@colearendt I couldn't reproduce this, either, using
- RStudio Desktop 1.2.1335 on MacOS 10.14 with Python 2.7.10 and reticulate 1.12
- RStudio Server 1.2.1335 on Red Hat 7.6 with Python 2.7.5 and reticulate 1.12 (via Google Chrome on MacOS)

**Comment by colearendt** [comment]
Sorry for the waste of time, y'all. I didn't realize I was not on the latest 1.2 locally (1.2.1330-2).

**Comment by ronblum** [comment]
@colearendt What do you see when you copy and paste? Is that working for you? Because I believe I'm still seeing an issue with the `class Person` block of code:

```
>>> class Person:
...     def __init__(self, name, age):
...     self.name = name
IndentationError: expected an indented block (<string>, line 2)
IndentationError: unexpected indent (<string>, line 1)
>>>     self.age = age
NameError: name 'age' is not defined
>>>     def myfunc(self):
...         print("Hello my name is " + self.name)
...     def test(self, add, another = 0):
IndentationError: unexpected indent (<string>, line 1)
>>>         total = int(self.age) + int(add) + int(another)
NameError: name 'self' is not defined
>>>     print("Hello my add age is " + str(total))
NameError: name 'total' is not defined
>>> 
```

**Comment by kevinushey** [comment]
@ronblum the indentation in the code you've copy + pasted is screwed up, though. Did you try copy + pasting that code snippet into an R file? (That could lead to the code being re-indented as though it were R code, and thus 'breaking' the Python code)

**Comment by ronblum** [comment]
@kevinushey Ah, I was pasting using <kbd>Cmd</kbd>+<kbd>V</kbd>. It works with <kbd>Ctrl</kbd>+<kbd>Enter</kbd>. So, ignore me.

```
>>> class Person:
...   def __init__(self, name, age):
...     self.name = name
...     self.age = age
...   def myfunc(self):
...     print("Hello my name is " + self.name)
...   def test(self, add, another = 0):
...     total = int(self.age) + int(add) + int(another)
...     print("Hello my add age is " + str(total))
... 
>>>
```
