### ISSUE TITLE
Spell check includes R strings

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#4869]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.192
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

Include a misspelled word in a string in R code. 

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/470418/58650241-ff4ccb80-82c2-11e9-8ee7-8526c959864a.png)

**Comment by johnfrombluff** [comment]
I find spell-checking of strings to be useful when the string is intended to be read by a human, e.g. in an error or informational message, or other output. And it never hurts to have one's own code spelled correctly. So perhaps this could be made an user-settable option?

**Comment by ronblum** [comment]
@johnfrombluff Thank you for the suggestion! Can you open a new issue for it? This way we can track it separately from this bug.
