### ISSUE TITLE
rsession unit tests don't run on Linux

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#4877]
- On Linux, sync to master (as of 2019/05/31) and build
- Use `rstudio-tests` script to run cpp unit tests
- There is a "running rsession tests..." message, but the rsession tests don't actually run
- Can confirm by intentionally breaking a test
- Also happens if you do `rstudio-tests --scope rsession`

Other observations: rsession tests do run on Mac and Windows, and the other categories of tests (core, R) do run as expected on Linux.

**Comment by jmcphers** [comment]
When I tried this I got an error message re: crash handling, so I've fixed that, but I don't think that was actually the issue. After resolving it, the tests still didn't do anything (exactly as you describe). 

Strace revealed that that for some reason `~/.rstudio-desktop` was owned by root, and the tests couldn't write to them. Once I removed that folder, they ran correctly. If you're still able to reproduce, could you reopen?

**Comment by gtritchie** [comment]
Huh, I had the same situation on my machine (~/.rstudio-desktop owned by root). Sure enough, after blowing that away the unit tests run fine.

**Comment by kevinushey** [comment]
See also: https://github.com/rstudio/rstudio/issues/4505 (since "~/rstudio-desktop owned by root" is the root cause of a set of not-completely-uncommon of user issues)

**Comment by jmcphers** [comment]
Another question might be how me and @gtritchie both wound up with `~/.rstudio-desktop` owned by root in the first place... it's probably not a coincidence. Is there something in our dev tooling that makes this happen?
