### ISSUE TITLE
[gnome-wayland] switching to a work space with a wine app focused adds white spaces in text file

### ISSUE THREAD

**Issue by basilrabi** [rstudio/rstudio#4884]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1522/1.3.212
    OS Version      : Fedora 30
    R Version       : 3.6.0

### Steps to reproduce the problem
1. Log-in in a gnome-wayland session
1. Open rstudio and create new text file (*e.g.* Makefile, .Rnw)
1. Open a wine app in a different workspace above/below the Rstudio session
1. Click the window of the wine app to ensure that it is focused when switching to that work space
1. Switch to Rstudio work space
1. Place the cursor in the text editor pane in a non-R portion (this can't be reproduced when cursor is in R code chunks)
1. Switch to wine app work space
1. Switch to Rstudio work space with a white space now added.

See [screen.zip](https://github.com/rstudio/rstudio/files/3245672/screen.zip).

### Describe the problem in detail
For Rnw files, the white space is added only if cursor is located in non-code portion (*e.g.* latex portions). White space is not added in .R and .sql files.

### Describe the behavior you expected
White space is not added when switching work space.

**Comment by ronblum** [comment]
@basilrabi I notice that you are using Wayland. We don't currently support Wayland, but the request to support it is available: #5333.

**Comment by jmcphers** [comment]
No other reports or detail in over a year, so closing.
