### ISSUE TITLE
Make R code diagnostics work with zeallot

### ISSUE THREAD

**Issue by jolars** [rstudio/rstudio#4885]
Please consider making R code diagnostics work properly with the multiple assignment operator from **zeallot**. 

The following code (in the screenshot) works perfectly fine, but rstudio's diagnostics checker returns the following warning if "Warn if variable used has no definition in scope" is enabled in the settings.

![image](https://user-images.githubusercontent.com/13087841/58782237-51049700-85de-11e9-8cb3-6f0a79f0e2cf.png)

**Comment by ronblum** [comment]
@jolars This is an interesting idea—thank you for the suggestion! We'll review it during our ongoing development of RStudio.
