### ISSUE TITLE
Default keyboard shortcuts tend to mask each other

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#4897]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1522-1
    OS Version      : Windows 7
    R Version       : 3.6.0

### Describe the problem in detail

Many keyboard shortcuts are double-bound. Sometimes this means that the shortcuts are inaccessible.

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/3200601/58935681-49491c00-87b1-11e9-8800-dec15db427e5.png)

By default, [Ctrl+Shift+Up] is bound to both 'Expand selection' and 'Increment number at cursor', and this means that 'Increment number at cursor' is never actually triggered because 'Expand selection' has precedence.

1. Make a new file and type some numbers in.
```
1
2
3
4
```
2. Press [Ctrl+Shift+Up] on the second line. The selection will move upwards and the numbers will not increment.
3. Change the 'Increment number at cursor' shortcut to something else, like [Ctrl+Shift+Alt+Up].
4. Press the new shortcut, and the numbers will increment.

### Describe the behavior you expected

RStudio should not double-bind shortcuts in a way that makes functions inaccessible.

**Comment by pascaloettli** [comment]
RStudio Edition : Desktop
    RStudio Version : 1.2.1522-1
    OS Version      : Ubuntu 18.04.2
    R Version       : 3.6.0

Strange. By default I have:

- _Expand selection_: <kbd>Ctrl+Shift+Up</kbd>
- _Increment number at cursor_: <kbd>Shift+Alt+Up</kbd>

Did you customized? If not, does a reset shows a difference?

**Comment by DesiQuintans** [comment]
> Did you customized? If not, does a reset shows a difference?

No, I didn't change anything. On Windows, it highlights edited keybindings in the list with a different colour. I have it like this on 3 different Windows machines. I notice that you're on Ubuntu, I wonder if that's the difference.

**Comment by pascaloettli** [comment]
It shouldn't make a difference, that's why I am asking about the customization. Let's wait for a RStudio guru to shed some light on this.

**Comment by gtritchie** [comment]
I haven't looked into these yet, but in general, default RStudio keyboard shortcuts can vary both by platform (WIndows, Mac, Linux) and in some cases by which editor keyboard binding (emacs, vim, etc.) you are using.

**Comment by gtritchie** [comment]
You can see where this is done starting here. It's a bit ugly, but not too hard to make sense of.

https://github.com/rstudio/rstudio/blob/42de22e97e09465a278ba6a378f7f552dd11c1f4/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L555-L558

**Comment by pascaloettli** [comment]
I see. Thank you for the clarification.

**Comment by ronblum** [comment]
@DesiQuintans Thank you for raising this. Some of the double-binding is tied to the context. For example, <kbd>Shift+Ctrl+Enter</kbd> on Windows and <kbd>Shift+Cmd+Enter</kbd> on Mac have multiple bindings, but they behave differently—as expected—if in the console, or an R Markdown file, etc.

<img width="652" alt="shift_command_enter" src="https://user-images.githubusercontent.com/31009952/59054937-c08ab880-8862-11e9-9358-cdc55125c28d.png">
However, the example you've provided—<kbd>Shift+Ctrl+Up</kbd>—isn't working as expected, so thank you for bringing this up!
