### ISSUE TITLE
Add section invisible text

### ISSUE THREAD

**Issue by maislind** [rstudio/rstudio#4898]
After updating RStudio, the text in the Section label' (Command + Shift + R) is invisible. Uninstalling and reinstalling did not help, neither did changing the layout. Here is the issue and my RStudio details:

<img width="457" alt="Screen Shot 2019-06-05 at 8 03 33 AM" src="https://user-images.githubusercontent.com/24191490/58955055-e764c400-8768-11e9-9fb8-6c336ddfc10f.png">

<img width="454" alt="Screen Shot 2019-06-05 at 8 07 56 AM" src="https://user-images.githubusercontent.com/24191490/58955118-09f6dd00-8769-11e9-932d-c46a9b6bd7a3.png">

**Comment by kevinushey** [comment]
This should be resolved in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) -- please re-open if you're still seeing the issue there.
