### ISSUE TITLE
Numpad Keys and Shortcuts in Ubuntu (Summary)

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#4903]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463, 1.2.1335, 1.2.1522, 1.3.225
    OS Version      : Ubuntu 18.04.2
    R Version       : 3.6.0

### Preamble
Trying to """help""" in #4886 and #4897, I realized there was a general regression in Ubuntu regarding the keyboard shortcuts. I tried here to summarize the situation, with the help of few examples.  

### I. Rstudio Desktop 1.1.463
Name | Shortcut | Main Keypad | Numeric Keypad
|---|---|---|---|
_Go to File/Function_ | <kbd>Ctrl+.</kbd> | OK | OK
_Move Focus to Source_ | <kbd>Ctrl+1</kbd> | OK | OK
_Move Focus to Console_ | <kbd>Ctrl+2</kbd> | OK | OK

In the _Modify Keyboard Shortcuts..._ window, for _Move Focus to Source_ shortcut, main keypad <kbd>1</kbd> and numeric keypad <kbd>1</kbd> are both mapped into _1_.

![Screenshot from 2019-06-06 12-06-16](https://user-images.githubusercontent.com/6613954/59004201-da70cf00-8853-11e9-9370-f83661242d01.png)

### II. Rstudio Desktop 1.2.1335
Name | Shortcut | Main Keypad | Numeric Keypad
|---|---|---|---|
_Go to File/Function_ | <kbd>Ctrl+.</kbd> | OK | NG
_Move Focus to Source_ | <kbd>Ctrl+1</kbd> | OK | NG
_Move Focus to Console_ | <kbd>Ctrl+2</kbd> | OK | NG

In the _Modify Keyboard Shortcuts..._ window, main keypad <kbd>1</kbd> is mapped into _1_, but numeric keypad <kbd>1</kbd> is mapped into _NumPad1_.

![Screenshot from 2019-06-06 12-11-34](https://user-images.githubusercontent.com/6613954/59004341-45220a80-8854-11e9-9970-4538ba25dec8.png)

Name | Shortcut | Main Keypad | Numeric Keypad
|---|---|---|---|
_Go to File/Function_ | <kbd>Ctrl+.</kbd> | OK | NG
_Move Focus to Source_ | <kbd>Ctrl+NumPad1</kbd> | NG | OK
_Move Focus to Console_ | <kbd>Ctrl+NumPad2</kbd> | NG | OK

After modification, the main keypad <kbd>1</kbd>, <kbd>2</kbd>... keys no longer work.

### III. Rstudio Desktop 1.2.1522
Name | Shortcut | Main Keypad | Numeric Keypad
|---|---|---|---|
_Go to File/Function_ | <kbd>Ctrl+.</kbd> | OK | NG
_Move Focus to Source_ | <kbd>Ctrl+1</kbd> | OK | NG
_Move Focus to Console_ | <kbd>Ctrl+2</kbd> | OK | NG

Same remarks apply

### IV. Rstudio Desktop 1.3.225
Name | Shortcut | Main Keypad | Numeric Keypad
|---|---|---|---|
_Go to File/Function_ | <kbd>Ctrl+.</kbd> | OK | NG
_Move Focus to Source_ | <kbd>Ctrl+1</kbd> | OK | NG
_Move Focus to Console_ | <kbd>Ctrl+2</kbd> | OK | NG

In this version, assignement to numeric keypad keys totally stopped to work, making the numpad pointless.

Hope this helps.

**Comment by kevinushey** [comment]
Thanks for taking the time to dig in @pascaloettli. We'll have to think about whether we want to preserve the old behavior, or allow for the NumPad number keys to act as distinct keys.
