### ISSUE TITLE
Error in tools::startDynamicHelp() : internet routines cannot be loaded

### ISSUE THREAD

**Issue by edelbende** [rstudio/rstudio#4904]
### System details
    RStudio Edition :  Desktop
    RStudio Version : Version 1.2.1335 (latest,  2019-04-08)
    OS Version      :  Ubuntu 18.04.2 LTS
    R Version       :  3.5.1

### Steps to the problem
After installing RStudio Desktop with corresponding .deb file ( from https://www.rstudio.com/products/rstudio/download/#download), 
1. I can launch RStudio perfectly from Ubuntu Applications Menu, 
2. Though when I type "rstudio" in terminal (bash), it opens correctly, but with an error :   

          " Error in tools::startDynamicHelp() : 
            internet routines cannot be loaded "

And therefore install a new package would give : 

```
> install.packages("x")
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  les routines internet ne peuvent pas être chargées
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  les routines internet ne peuvent pas être chargées
Warning in install.packages :
  package ‘x’ is not available (for R version 3.5.1)

```
I would have expected the launch of Rstudio being independant of Terminal or Menu launch.

If useful : 
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3260725/diagnostics-report.txt)

**Comment by pascaloettli** [comment]
Does `install.packages("x")` works in R running in terminal? Looks like you have some network trouble. You can also try to change the primary CRAN repo in Rstudio, to see if these warning still occur.

**Comment by edelbende** [comment]
Before any remark, I checked [https://github.com/ContinuumIO/anaconda-issues/issues/4421], but this is related to Anaconda installed version of Rstudio. In my case, I just installed the .deb file :-)

**Comment by edelbende** [comment]
> Does `install.packages("x")` works in R running in terminal? Looks like you have some network trouble. You can also try to change the primary CRAN repo in Rstudio, to see if these warning still occur.

"install.packages("rmarkdown") works fine running R in terminal.
I changed the primary CRAN repo from GLOBAL to France (Lyon2), restarted : same problem ("Error in tools::startDynamicHelp() ...")

**Comment by pascaloettli** [comment]
Does `help.start()` works in R running in terminal? Also, do you see the loopback interface (lo) running `ip link` in a terminal? If yes to both, I have no clue what happens, sorry

**Comment by ronblum** [comment]
@edelbende Thanks for raising the issue. I'm unable to reproduce it, also on Ubuntu 18.0.4.2 LTS.
1) Do you just have the one instance of R—`/home/manudelb/anaconda3/bin/R`—or do you have more than one instance of R installed? 
2) It might be useful to get the diagnostics report for the instance that's working.
Thanks!

**Comment by edelbende** [comment]
Right ! I actually have two R versions, which is logical as I installed  Rstudio .deb file, so R came along with at at /usr/bin/R...thank you ! :smile: 
As written in the diagnostics report from the working instance, R version used is /usr/bin/R, which was not the case for the instances launched from terminal...
[diagnostics-report-workinginstance.txt](https://github.com/rstudio/rstudio/files/3265142/diagnostics-report.txt)

One question now, how do I force rstudio command to use /usr/bin/R ?

**Comment by pascaloettli** [comment]
[Changing R versions for RStudio desktop](https://support.rstudio.com/hc/en-us/articles/200486138-Changing-R-versions-for-RStudio-desktop)

**Comment by edelbende** [comment]
Thanks,

**Comment by ronblum** [comment]
@edelbende Glad it worked out!

**Comment by grabear** [comment]
Any idea what might be going on over in spack/spack#19051

**Comment by tingjhenjiang** [comment]
I got the same issue.
My env is in Miniconda.
conda info
```
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __cuda=11.0
                          __glibc=2.17
```

R sessionInfo()
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /home/username/miniconda3/envs/newr/lib/libopenblasp-r0.3.10.so
```
Executing R directly (e.g. by command line) would not produce "Error in tools::startDynamicHelp() :internet routines cannot be loaded" errors.

However executing R by Rstudio would produce such errors.
Rstudio is downloaded from Rstudio website in [installer-less (Zip/Tarballs)](https://rstudio.com/products/rstudio/download/#download) and [daily build](https://dailies.rstudio.com/) format.

**Comment by abalter** [comment]
I'm having this problem as well. I have only one version of R. In fact, I linked `/usr/bin/R` to conda.

**Comment by martin-jeremy** [comment]
> I'm having this problem as well. I have only one version of R. In fact, I linked `/usr/bin/R` to conda.

Doing this didn't install R Package in system library path instead of $CONDA_PREFIX/lib/R/library ? For instance, some packages aren't available in conda repo and I have to install directly from bioconductor manager in R/RStudio, if I do a `BiocManager::install("package"), it will be installed in my `~/R/x86_64-pc-linux-library/4.0/ folder` ? If it didn't, how do you linked `/usr/bin/R` to conda ?

**Comment by wonitawowowo** [comment]
Hi,I have two R version in my PC, one is in /usr/bin/R and the other is R4.0.3 ln  to /usr/bin/R4. When I want to use R4.0.3,I export RSTUDIO_WHICH_R=/usr/bin/R4, the rise the error 'Error in tools::startDynamicHelp()'.
Can I achieve the  switching between the raw R-3.4.4 and R4.0.3 in Rstudio？Could you give me some suggest？Thanks a lot.

**Comment by estatistics** [comment]
I fixed that by simply running [each time]:

options(download.file.method="wget")

**Comment by jdblischak** [comment]
>  I'm unable to reproduce it, also on Ubuntu 18.0.4.2 LTS.

FWIW I was able to reproduce this bug with both my personal computer running Ubuntu 18.04 and also in Virtual Box running Ubuntu 18.04. This bug only affects RStudio 1.3. Both RStudio 1.2 and 1.4 work fine with conda-installed R.

Since the bug is no longer present in 1.4, I doubt there is much interest in diagnosing the error present in 1.3. But if the error is re-introduced in a future ersion, I can provide more detailed instructions on reproducing the bug with Virtual Box.
