### ISSUE TITLE
All dark themes have isDark = FALSE

### ISSUE THREAD

**Issue by joniok** [rstudio/rstudio#4914]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335 (build 1379)
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : 3.6.0

```
> rstudioapi::getThemeInfo()
$editor
[1] "Dracula"

$global
[1] "Modern"

$dark
[1] FALSE

$foreground
[1] "rgb(248, 248, 242)"

$background
[1] "rgb(40, 42, 54)"

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Finland.65001    LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_Finland.65001   LC_NUMERIC=C                       
[5] LC_TIME=English_Finland.65001      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0  tools_3.6.0     rstudioapi_0.10
```

### Steps to reproduce the problem
I have a fresh install of RStudio 1.2  and I tried changing to a dark theme after installation. IDE theme remains light Modern instead of dark Modern for every theme.

### Describe the problem in detail

I have the exact problem as [4850](https://github.com/rstudio/rstudio/issues/4850). It seems that every theme has `isDark` value set as `FALSE`. I have checked this from the output of `rstudioapi::getThemes()`. Unfortunately I don't know how to reproduce the problem since this is the first time I have had problems with themes in RStudio 1.2.

I have tried reinstalling RStudio and also reinstalling after deleting RStudio caching files from AppData and AppData/Local folders of Windows.

**Comment by ronblum** [comment]
@joniok Thank you for reporting to this. I'm closing this as a duplicate but reopening #4850 and copying this information over there.
