### ISSUE TITLE
boxplot / bxp don't add to existing plot

### ISSUE THREAD

**Issue by thelatemail** [rstudio/rstudio#4920]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Ubuntu 18.04.2 
    R Version       : 3.6.0

### Steps to reproduce the problem

See here for reference code where issue found originally - https://stackoverflow.com/questions/56487589/how-to-create-a-boxplot-with-customized-quantiles-in-r/56489177#56489177

Basically, it can be boiled down to something like this code, 

    bp <- boxplot(1:10)
    bp$stats[3] <- 7 
    bxp(bp, boxcol="red", add=TRUE)

which only shows the second plot in the 'Plots' viewer, instead of `add=`ing it to the existing plot as happens in RGui or via Emacs/ESS.

### Describe the behavior you expected

I would expect that `add=TRUE` should mean adding to the current plotting device to show 2 lines in the boxplot for the original median value (5.5) and the updated one (7).

**Comment by pascaloettli** [comment]
I am able to reproduce on MacOS Mojave with Rstudio `1.2.1522` and `1.3.235`, with R `3.6.0`

**Comment by ronblum** [comment]
Thank you @thelatemail for reporting the issue and @pascaloettli for reproducing it. We'll review this as we continue development of RStudio.

Reproduced with
- RStudio Desktop 1.2.1539 on MacOS 10.14.6
- RStudio Server 1.2.1335 on Red Hat 7.6
- RStudio Desktop 1.1.463 on MacOS 10.14.6 (so this is not a regression).

RStudio plot:
<img width="559" alt="rstudio" src="https://user-images.githubusercontent.com/31009952/59226182-6c544100-8ba0-11e9-8a9c-081635fb7b2d.png">

R gui plot:
<img width="562" alt="rgui" src="https://user-images.githubusercontent.com/31009952/59226188-6f4f3180-8ba0-11e9-9d7d-8de2193fb9ab.png">
