### ISSUE TITLE
Searching for documentation in unattached packages results in blank Help pane

### ISSUE THREAD

**Issue by psalveson** [rstudio/rstudio#4922]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1522
    OS Version      :  Ubuntu 18.04 LTS
    R Version       :  3.6.0

### Steps to reproduce the problem

Search for help on a function who's package has not been attached. For example:

```
?c                       # Displays documentation normally
?nortest::ad.test        # Displays blank page
?c                       # No longer displays documentation (blank page)
```

### Describe the problem in detail

The `Help` pane displays a blank page when searching for help on a function who's package is not attached. Additionally, the `Help` pane will no longer display documentation for attached packages after attempting to view help from packages that are not attached. Help displays normally if I run R from the command line (sans RStudio).

Restarting R does not remedy the problem. Quitting the current R session does remedy the problem (until I search for help in an unattached package).

**Comment by pascaloettli** [comment]
RStudio Edition : Server
    RStudio Version : 1.2.1522
    OS Version      : Ubuntu 18.04.2 LTS (server), MacOS Mojave 10.14.5 (client)
    R Version       : 3.6.0
    Client          : Firefox 67.0

Partly reproducible on my computer, i.e. there is neither the help page for `nortest::ad.test` nor a blank page. And running `?c` after works.
And when the package is loaded, `?ad.test` doesn't work either.

**Comment by ronblum** [comment]
@psalveson I'm unable to reproduce this. Are you running into this issue with all/other unattached packages or just `nortest`?

**Comment by psalveson** [comment]
@ronblum I thought that it was for all unattached packages, but I must have been confused. It appears that it is a specific issue for the ad.test documentation within the nortest package. I can't reproduce the issue with other documentation within nortest, nor other packages.
