### ISSUE TITLE
Order of installed R Markdown templates in window for creating a new R Markdown document

### ISSUE THREAD

**Issue by sarahvanhala** [rstudio/rstudio#4929]
I have a couple of my own R packages that contain a large number of R Markdown templates. When I go to open a new document from a template by clicking "File -> New File -> R Markdown -> From Template", the list of installed R Markdown templates is displayed in a seemingly random order, making it difficult to locate a specific template among the large number of installed templates.

I remember that in older versions of RStudio, templates were sorted alphabetically by name. I went back and tested older releases, and I found that in release v1.0.153, installed R Markdown templates were sorted alphabetically by package name, then within each package they were sorted alphabetically by template name.

Starting with release v1.1.383 (and up to the current release v1.2.1335), installed R Markdown templates are ordered by package name (but the order of packages is not alphabetical or in any other obvious order), and also, the installed templates within a given package are in a seemingly random order.

Is there some way to make installed R Markdown templates be sorted in a way similar to the behavior from v1.0.153, where the installed templates are sorted alphabetically, first by the package name, then alphabetically by template name within each package?

**Comment by ronblum** [comment]
@sarahvanhala Thank you for filing this issue. We will review it as we work on development of future versions of RStudio.

Confirmed that the list is alphabetical in 1.0.153 but not in 1.1.463 and several version of 1.2 of RStudio Desktop on MacOS 10.14.6 and RStudio Server on Ubuntu 18.04.2 and Red Hat 7.6.

**Comment by p-phillips** [comment]
Confirmed on RStudio 1.2.1335 under Ubuntu 18.04.2
