### ISSUE TITLE
Request: add option to copy default .Rprofile to new project

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4930]
Would be nice when creating a project through the `File` -> `New Project` button if the dialog there could offer the option to copy the `.Rprofile` file from the default folder to the new project being created.

**Comment by pascaloettli** [comment]
Pardon me for the question, but if it is just a copy, what would be the benefit?

**Comment by david-cortes** [comment]
> Pardon me for the question, but if it is just a copy, what would be the benefit?

Convenience. I find myself constantly having to manually copy a `.Rprofile` with paths and credentials into every (business) project I create.

**Comment by ronblum** [comment]
@david-cortes Thanks for the suggestion! We'll take a look at it as we continue to develop new versions of RStudio.

**Comment by kevinushey** [comment]
Perhaps I don't understand, but if you had your credentials stored in a user profile (e.g. at `~/.Rprofile`) then that could be used + shared for all projects. Is there a reason why that isn't sufficient in your case?

**Comment by david-cortes** [comment]
> Perhaps I don't understand, but if you had your credentials stored in a user profile (e.g. at `~/.Rprofile`) then that could be used + shared for all projects. Is there a reason why that isn't sufficient in your case?

But that doesn't get loaded when opening a project.

**Comment by kevinushey** [comment]
Yes it does? Unless that project already has its own project-local `.Rprofile`.

**Comment by david-cortes** [comment]
> Yes it does? Unless that project already has its own project-local `.Rprofile`.

Nope, loads it from the user directory, not from the default working directory that can be specified in the RStudio settings. In a typical enterprise setup in windows, this would be a network folder where I wouldn't want to put a `.Rprofile` with that kind of info.

**Comment by jmcphers** [comment]
I wonder if this would be better implemented as a kind of project skeleton, wherein you designate a folder that is copied recursively when RStudio creates a "blank" project -- similar in spirit to the first project template we have today. 

https://docs.rstudio.com/ide/server-pro/r-sessions.html#first-project-template
