### ISSUE TITLE
Request: Manage Search Path Conflicts when Packages are attached from RStudio IDE

### ISSUE THREAD

**Issue by jtelleria** [rstudio/rstudio#4931]
Based on:
* Conflicts.policy Options: https://developer.r-project.org/Blog/public/2019/03/19/managing-search-path-conflicts/index.html
* Or Conflicted R Package: https://cran.r-project.org/web/packages/conflicted/index.html

It would be nice that RStudio IDE itself allows to manage these different Conflict Resolution Strategies, mostly for educative purposes, in order that R Users take care on managing conflicts appropriately.

Thank you! :)
Juan

**Comment by ronblum** [comment]
@jtelleria Thank you for the suggestion. I'll tag it as an enhancement for review as we continue development of RStudio.

**Comment by jtelleriar** [comment]
Any advancements in this issue?

It would be nice that @hadley 's conflicted package, or Luke Tierney's library() conflict management options, could be handled in an easy way directly from the IDE, in a visual and interactive way,
