### ISSUE TITLE
Option to disable arrow navigation skipping spaces

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4934]
Currently, RStudio:

- moves the cursor two spaces if the user performs a single press of an arrow key to move through a space character.
- removes two spaces if the user hits backspace or delete to remove a space character

Is it possible to provide an option to disable this behavior? It is causing bugs in a text accessibility system I am helping to develop for the voice coding platform Caster: https://github.com/dictation-toolbox/Caster/pull/485

**Comment by kevinushey** [comment]
Looks like Ace provides an option controlling this behavior:

https://github.com/ajaxorg/ace/blob/41ac47ec9e26f65fe0ffedeedf14b525a22f5462/lib/ace/edit_session.js#L468-L481

**Comment by ronblum** [comment]
[Testing note: this is based on the width of a soft tab.]
