### ISSUE TITLE
provide tools for linking to code on GitHub

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4939]
E.g. if one is working within a Git-managed project whose sources are also on GitHub, it'd be nice if the user could execute some command and get the URL referencing the file / current selection. This is especially helpful when one needs to share a reference to some code.

(ie: the moral equivalent of `:Gbrowse`)

**Comment by jmcphers** [comment]
Does this do what you want?

![image](https://user-images.githubusercontent.com/470418/59383654-37b5c600-8d15-11e9-9410-a9d800610f99.png)

(I don't think it respects the current selection, though).

**Comment by kevinushey** [comment]
It _does_! And it even respects the current selection.

Well, how about that :-)
