### ISSUE TITLE
View(data.frame()) triggers JavaScript exception

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4945]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : v1.3.x
    OS Version      : macOS Mojave 10.14.5
    R Version       : R version 3.6.0 Patched (2019-05-29 r76623)

### Steps to reproduce the problem

```r
View(data.frame())
```

### Describe the problem in detail

```
Uncaught TypeError: Cannot read property 'nTh' of undefined
    at O (jquery.dataTables.min.js:1)
    at jquery.dataTables.min.js:1
    at k (jquery.dataTables.min.js:1)
    at HTMLTableElement.<anonymous> (jquery.dataTables.min.js:1)
    at Function.each (jquery.js:2)
    at k.fn.init.each (jquery.js:2)
    at k.fn.init.F [as dataTable] (jquery.dataTables.min.js:1)
    at initDataTable (dtviewer.js:1133)
    at dtviewer.js:1388
    at dtviewer.js:385
```

### Describe the behavior you expected

No exception.

NOTE: this is a regression (worked in v1.1); regressed in v1.2 but not sure if it's worth trying to fix for v1.2-patch. Previously, we displayed a placeholder table:

![Screen Shot 2019-06-13 at 10 20 22 AM](https://user-images.githubusercontent.com/1976582/59453492-df3e0180-8dc4-11e9-9ba7-b2398b3a2fa9.png)

**Comment by jmcphers** [comment]
We should fix this but it isn't vital for 1.3
