### ISSUE TITLE
Invoke the Save as Image command programmatically

### ISSUE THREAD

**Issue by hmhensen** [rstudio/rstudio#4946]
It seems strange that this feature isn't already included.

I created an interactive object that is viewed in the RStudio Viewer, such as chart in `plotly` or `highcharter` or a map in `leaflet`. I would like to save that object as a png. There are a number of ways to do this, such as with `webshot`, `orca` and other methods. The problem with all of these is that the output image is slightly different than the version seen in the Viewer. This is a problem for me because I need both the interactive version of the chart as well as a static version and I don't want to have to create two versions and write all the code associated with producing both to make sure each one comes out just as needed.

However, RStudio has a built-in method for exporting interactive objects that can be accessed by clicking "Export -> Save as Image" in the Viewer pane. I would like to use this method because it preserves the layout exactly as seen in the Viewer.

I tried using R's built-in Plots saving method of `png` -> `plot` -> `devoff`, but that appears to only work for Plots objects, not Viewer objects.

I'm surprised there's no way to reproduce the physical steps of saving as an image in RStudio programmatically, considering the functionality is already there. Doing it manually is really time-consuming and not feasible after a certain point.

Here's a sample chart using `plotly` that shows up in the Viewer.

`plot_ly(z = ~volcano, type = "surface")`

**Comment by ronblum** [comment]
@hmhensen Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.

**Comment by jmcphers** [comment]
This would probably need an rstudioapi binding.

**Comment by enbishop** [comment]
Commenting in hopes of re-opening this issue. This would be super helpful in exporting rendered html or plotly outputs to PNG or image files, as the webshot package reduce the image quality significantly more than RStudio's export to PNG.
