### ISSUE TITLE
Differentiate rstheme text colors between text and code blocks for Rmarkdown

### ISSUE THREAD

**Issue by Copepoda** [rstudio/rstudio#4950]
Currently, for custom themes in RStudio, you can't assign one color to the text in a text block and another color for the text in a code chunk within an RMarkdown file. Visually I think it would help too quickly differentiate between the two when there is a lot of text in the text chunks, plus look neat.
I asked if this was possible in the RStudio Community boards, [here](https://community.rstudio.com/t/change-theme-color-of-text-blocks-in-rmarkdown/33005), but learned it might take some work to make it happen.

**Comment by ronblum** [comment]
@Copepoda Thank you for the suggestion, and for filing it here as a followup to the Community post! We'll review it as we continue development of RStudio.
