### ISSUE TITLE
Importing data with readr

### ISSUE THREAD

**Issue by brianperlman** [rstudio/rstudio#4951]
When I click on Import Dataset using readr, I designate each column data type in the Data Preview box. But for really wide data sets, it makes it difficult to set many columns because the Data Preview box resets itself to the first column after each time you designate a column type. Is it possible to leave the horizontal slider position where it is after you designate each column data type? Thanks!

**Comment by ronblum** [comment]
@brianperlman Thank you for filing this issue! We address it as we work on development of future versions of RStudio.
