### ISSUE TITLE
Last line of code can't be seen because of the horizontal slider

### ISSUE THREAD

**Issue by laresbernardo** [rstudio/rstudio#4957]
The last line of code is totally covered by the horizontal slider in RStudio 1.2. Attached image of a screenshot.

### System details

    RStudio Version : 1.2.1335
    OS Version      :  macOS Mojave (10.14.5)
    R Version       : 3.6.0

<img width="348" alt="Captura de Pantalla 2019-06-14 a la(s) 6 25 41 p  m" src="https://user-images.githubusercontent.com/25909073/59539052-3aa9e580-8ed2-11e9-8377-0d6c72d2be4f.png">

Any possibility to fix this soon? Thanks!

**Comment by kevinushey** [comment]
You can use the [ ] Allow scroll past end of document preference:

![Screen Shot 2019-06-14 at 2 59 52 PM](https://user-images.githubusercontent.com/1976582/59541205-1d1a5300-8eb5-11e9-9df1-d959266f7c7c.png)

(or, of course, add a blank line or two at the end of the document)
