### ISSUE TITLE
"Rename in Scope" across chunks in R Markdown 

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#4961]
The "Rename in Scope" operation in the Code menu is really handy in R scripts, but not quite as nice in R Markdown documents.  It appears to work only within a chunk, whereas the scoping model in R Markdown is that all "r" chunks that are evaluated act like a single script.  

For example,

    Here I define a variable:
    ```{r}
    bad.var.name <- runif(1)
    # [close chunk]
   ```
   And here I print its value:

   ```{r}
   bad.var.name
   # [close chunk]
   ```

(where `# [close chunk]` is supposed to be the three backticks to close the chunk).  If I put this in an R Markdown document, then try to Rename in Scope the `bad.var.name`, only the one in the same chunk gets changed.

**Comment by ronblum** [comment]
@dmurdoch Thank you for bringing this up! We'll target this for the next major release of RStudio.

**Comment by domwoolf** [comment]
same problem in R scripts when comments separating sections look like chunk headers
For example:

```
#----section_1--------
rename_this =1
print(rename_this)

#----section_2--------
print(rename_this)
```

Ends up like this

```
#----section_1--------
newname =1
print(newname)

#----section_2--------
print(rename_this)
```

**Comment by dmurdoch** [comment]
This is still present in RStudio 1.4.1103.

**Comment by danmyles** [comment]
It would be useful to have the option to either rename a variable across the whole document, or only within a chunk. I find myself frequently wanted to to both of these operations.

**Comment by danmyles** [comment]
Another option might be to add more options to the Cmd+F menu, for instance:  within scope and within chunk?

**Comment by NewGraphEnvironment** [comment]
Does anyone have any workarounds that they can share to rename in scope over an entire rmd doc?

**Comment by viktorpm** [comment]
Is there an update on this?

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.11.0-daily+258 on Windows 11. 
- Tested in both R Markdown and Quarto.
- Confirmed for source mode.

Opened two related issues: #15262 for visual mode, and #15263 for sections in an R script.
