### ISSUE TITLE
search field

### ISSUE THREAD

**Issue by msgoussi** [rstudio/rstudio#4962]
what do you think of adding a search field in the Files Tab (same as in the Packages Tab), it will really help.
Thanks

**Comment by ronblum** [comment]
@msgoussi Thank you for the suggestion—we'll review it as we continue development of RStudio. In the meantime, in RStudio Desktop, clicking on the ellipsis in the upper right corner of the Files tab will pull up the system Finder/Explorer, which allows to search for files.

**Comment by nxc1303** [comment]
The workaround suggested doesn't appear to work in RStudio Pro Server edition. It would be really helpful to have a search field to find files.
