### ISSUE TITLE
Find/replace fails to find strings starting with !

### ISSUE THREAD

**Issue by AMChalkie** [rstudio/rstudio#4967]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1335
    OS Version      : 
    R Version       : 
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

### Steps to reproduce the problem

Self explanatory: in find bar, !string

### Describe the problem in detail
Trying to find "!string", as in the actual exclamation point followed by string.

**Comment by ronblum** [comment]
@AMChalkie Thank you for raising. I'm unable to reproduce any problems, both with R 3.5.2 and 3.6.0. Can you describe what is happening? Are they findable if the exclamation mark is within or at the end of a string?

**Comment by AMChalkie** [comment]
With coffee, I cannot reproduce the error.

**Comment by ronblum** [comment]
@AMChalkie Thanks for the update. I wonder if tea will work, as well?
