### ISSUE TITLE
"invalid width" in rstudio-server zoomed plot

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#4968]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.463
    OS Version      : Ubuntu 16.04.5 LTS
    R Version       : 3.4.4

### Steps to reproduce the problem

Zoom plot on `sp::SpatialPolygons`

### Describe the problem in detail

Apparently a long-standing issue, as seen here from 5 years ago:

https://support.rstudio.com/hc/en-us/community/posts/200640338-Zoom-of-graphics-window-doesn-t-work-

I plot some polygons:

![Screenshot 2019-06-18 at 7 30 38 PM](https://user-images.githubusercontent.com/7606389/59678669-9c828c00-91ff-11e9-8dc5-d4e9185a1848.png)

And when I click Zoom, it crashes with the error "Invalid Width"

![Screenshot 2019-06-18 at 7 30 47 PM](https://user-images.githubusercontent.com/7606389/59678693-a7d5b780-91ff-11e9-86f2-8b6069d529b3.png)

Is there any way around this? It seems to be related to monitor resolution...

**Comment by kevinushey** [comment]
A reproducible example would be helpful (a snippet of R code we can copy + paste to generate the associated plot)

**Comment by MichaelChirico** [comment]
sadly not polygons I can share... FWIW I was able to get around the problem by zooming in (<kbd>Ctrl</kbd> + <kbd> + </kbd> several times)

**Comment by pascaloettli** [comment]
On my side, this is only reproducible (on desktop and sever) if the width of zoom window is manually changed by dragging the border to reach a width of 3200. This works with a simple plot such as `plot(1,1)`.
The question is, as previously mentioned, what might cause the zoom window to automatically expand to 3000? I tried on different display (Linux and MacOS), and on extended desktop (MacBook Air + second display), and even moving the zoom window between displays doesn't prevent the window to automatically resize.

**Comment by ronblum** [comment]
@MichaelChirico A couple of things:
1) Do you run into this issue with RStudio Desktop, either [the current RStudio release](https://www.rstudio.com/products/rstudio/download/) or
[the latest RStudio Preview](https://www.rstudio.com/products/rstudio/download/preview/)?
2) Are you able to reproduce the example with resizing `plot(1,1)` that @pascaloettli encountered?

**Comment by jonathanzhang53** [comment]
I also had this error. Like @pascaloettli said, this also occurs by simply running `plot(1,1)` and using the zoom button.

1. > `plot(1,1)`
2. Click Zoom button.
3. Maximize Zoom window.
4. Invalid width shown.

**Comment by davidtl** [comment]
I'm having an issue, code/data below.  It appears to have somehting to do with the monitor size/resolution or graphics hardware.  On my laptop I don't have this issue but on an external monitor both on a 34" 3440x1440 and a 23" 1920x1080.  **As it has a potential hardware component i
've linked to a screencapture of the issue**
[https://youtu.be/8Q5gpkECrks](url)

`b <- structure(list(Frequency_Hz = c(1e+05, 79432.8203125, 63095.73046875, 
                                50118.71875, 39810.71875, 31622.779296875), Phase = c(0.92015399556211, 
                                                                                      0.941823190842747, 0.873846333310971, 0.672277945556997, 0.654976227432723, 
                                                                                      0.536680756600807), FileName = c("N600_Cu_Block_1_Potentiostatic EIS_4.par", 
                                                                                                                      "N600_Cu_Block_1_Potentiostatic EIS_4.par", "N600_Cu_Block_1_Potentiostatic EIS_4.par", 
                                                                                                                       "N600_Cu_Block_1_Potentiostatic EIS_4.par", "N600_Cu_Block_1_Potentiostatic EIS_4.par", 
                                                                                                                       "N600_Cu_Block_1_Potentiostatic EIS_4.par"), Chemistry = structure(c(1L, 
                                                                                                                                                                                            1L, 1L, 1L, 1L, 1L), .Label = "N600", class = "factor")), row.names = c(NA, 
                                                                                                                                                                                                                                                                    -6L), class = c("tbl_df", "tbl", "data.frame"))
`

`ggplot(b, aes(x=Frequency_Hz, y=Phase, group=FileName, color=Chemistry))+
    geom_line()`
