### ISSUE TITLE
C++ diagnostics fail if Makevars has custom OBJECTS target

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4972]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.3.241
    OS Version      : macOS Mojave 10.14.5
    R Version       : R version 3.6.0 Patched (2019-05-29 r76623)

### Steps to reproduce the problem

Initialize a project with something like:

```
devtools::create("projcpp")
dir.create("projcpp/src")
writeLines("void test() {}", "projcpp/src/test.cpp")
writeLines("OBJECTS: test.o", "projcpp/src/Makevars")
```

Then, open the project `projcpp` in RStudio, and use `.rs.setClangDiagnostics(2)`. You should see something like:

### Describe the problem in detail

RStudio emits:

> CLANG SKIP INDEXING: /Users/kevin/scratch/projcpp/src/test.cpp

indicating that it's unable to index `test.cpp`.

### Describe the behavior you expected

No issue indexing.

### Notes

The issue here is with how RStudio triggers `R CMD SHLIB --dry-run` behind the scenes. We create a temporary C++ file with an arbitrary name, here:

https://github.com/rstudio/rstudio/blob/acf70f45aeb67504776a6bd9f7826641ef24f13d/src/cpp/session/modules/clang/RCompilationDatabase.cpp#L1066-L1070

However, by doing so, we break the automatic mapping of sources to objects. Since `Makevars` declares the objects by name directly, when we use a different filename, the link is lost and R no longer knows how to compile the file.

I suspect we could fix this issue by preserving the file name, rather than generating a unique name (but need to confirm)

**Comment by jmcphers** [comment]
Moving out of 1.3 since mitigation was done in #5022. @kevinushey What work remains to be done here?

**Comment by kevinushey** [comment]
Right now, we try to cache compilation configurations on a per-package basis, whereas it may be more appropriate to do it on a per-translation-unit basis (since packages with custom Makevars might require different flags for each object to be compiled).

That's definitely out-of-scope for v1.3, and I'm not yet convinced this is a common enough pattern that we should try to handle it whole-sale. But worth leaving this issue alive for a while in case more users report a similar issue.
