### ISSUE TITLE
null requests in spellcheck system

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#4974]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3

### Steps to reproduce the problem
Start the app

### Describe the problem in detail
We are seeing `null` requests trying to get dictionaries

### Describe the behavior you expected
No null requests

![YtmksSj](https://user-images.githubusercontent.com/136863/59725566-07ca5f00-91fc-11e9-917c-a37170f0565e.png)

![xnTIXwg](https://user-images.githubusercontent.com/136863/59725544-fb460680-91fb-11e9-8dfc-0ced8b074bef.png)

**Comment by kevinushey** [comment]
Fixed via https://github.com/rstudio/rstudio/commit/e0817783df91d3977cd333a651aa82d9ae391e0c.
