### ISSUE TITLE
Include xoria colour theme

### ISSUE THREAD

**Issue by x1o** [rstudio/rstudio#4975]
Please consider including "xoria" colour theme.

Basically, it's a modified version of "Tomorrow Night Bright" colour scheme, but softer and somewhat more pale. Just in case, I'll attach the patch below.

![Screenshot from 2019-06-18 16-08-10](https://user-images.githubusercontent.com/3007504/59749647-21b08400-9286-11e9-849d-2bc4b7695fe2.png)

**Comment by x1o** [comment]
```diff
--- tomorrow_night_bright.rstheme	2019-03-28 08:16:44.000000000 +0300
+++ xoria.rstheme	2019-06-18 11:28:26.946971656 +0300
@@ -1,4 +1,4 @@
-/* rs-theme-name: Tomorrow Night Bright */
+/* rs-theme-name: xoria */
 /* rs-theme-is-dark: TRUE */
 .ace_gutter {
   background: #1a1a1a;
@@ -13,7 +13,7 @@
   color: #DEDEDE
 }
 .ace_cursor {
-  color: #9F9F9F
+  color: #FFAF00
 }
 .ace_marker-layer .ace_selection {
   background: #424242
@@ -56,10 +56,13 @@
 .ace_storage,
 .ace_storage.ace_type,
 .ace_support.ace_type {
-  color: #C397D8
+  color: #DFAFDF	/* purple */
 }
 .ace_keyword.ace_operator {
-  color: #70C0B1
+  /* color: #5FAFAF	[> sea <] */
+  /* color: #87AF87	[> sea <] */
+  color: #87d7d7	/* sea */
+  /* color: #87d7af	[> sea <] */
 }
 .ace_constant.ace_character,
 .ace_constant.ace_language,
@@ -67,7 +70,7 @@
 .ace_keyword.ace_other.ace_unit,
 .ace_support.ace_constant,
 .ace_variable.ace_parameter {
-  color: #E78C45
+  color: #DFAF87	/* orange */
 }
 .ace_constant.ace_other {
   color: #EEEEEE
@@ -87,23 +90,23 @@
 .ace_entity.ace_name.ace_function,
 .ace_support.ace_function,
 .ace_variable {
-  color: #7AA6DA
+  color: #87AFDF  /* blue */
 }
 .ace_support.ace_class,
 .ace_support.ace_type {
-  color: #E7C547
+  color: #AFDF87  /* ooze -> green */
 }
 .ace_heading,
 .ace_markup.ace_heading,
 .ace_string {
-  color: #B9CA4A
+  color: #FFFFAF /* yellow */
 }
 .ace_entity.ace_name.ace_tag,
 .ace_entity.ace_other.ace_attribute-name,
 .ace_meta.ace_tag,
 .ace_string.ace_regexp,
 .ace_variable {
-  color: #D54E53
+  color: #DF8787 /* red */
 }
 .ace_comment {
   color: #969896
```

**Comment by BastiHz** [comment]
In version 1.2 of RStudio you can import your own color themes. See [here](https://blog.rstudio.com/2018/10/29/rstudio-ide-custom-theme-support) and [here](https://rstudio.github.io/rstudio-extensions/rstudio-theme-creation.html).

**Comment by x1o** [comment]
Did that, thanks.

I was wondering, who decides which colour schemes get into the official distribution? Perhaps there should be a way to push custom themes into the mainstream, maybe through some sort of voting. I guess I'm not the only one who thinks their themes are at least as good the official ones, or even marginally better... 🙃

**Comment by ronblum** [comment]
@x1o This is a good place for it. Upvoting the issue with 👍 gives us an indication of how interested people are in certain issues, which helps us prioritize both which enhancement requests and bug fixes to prioritize.
