### ISSUE TITLE
Cannot sign out from Rstudio Server 1.3.260

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#4976]
RStudio Edition : Server
    RStudio Version : 1.3.260
    OS Version      : Ubuntu 18.04.2 (server), macOS 10.14.5 (client) 
    R Version       : 3.6.0
    Interface       : Firefox 67.0.3, Safari 12.1.1

Rstudio server `1.3.260` doesn't sign out.

Message on Firefox:
> The connection was reset

Message on Safari:
> Safari can't open the page

After closing and restarting Safari, the Rstudio session is closed (sign in window is visible). But even after closing and restarting Firefox, the Rstudio session is still active.

**Comment by kfeinauer** [comment]
Should be fixed in the next daily build, but you'll need to delete the `/var/run/rstudio-server` to ensure everything works fully (though regardless you should no longer see a crash).

**Comment by rich-rstudio** [comment]
verified on Version 1.3.857-3
