### ISSUE TITLE
QT error when plotting Python from R

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4978]
**Steps to reproduce:**
* Try to show a `matplotlib` plot through `reticulate` in a non-repl session, e.g.
```r
library(reticulate)
plt <- reticulate::import("matplotlib.pyplot")
plt$hist(1:100)
```

**Expected behavior:** should render the plot like in an interactive Python session.

**Actual behavior:** throws the following error:
![qt_plot_error](https://user-images.githubusercontent.com/11860098/59775928-a3220980-92ba-11e9-92fb-75201dec4c21.png)

(after that, the R session crashes)

**Setup:** R 3.5.3, RStudio 1.2.1541, running on windows 10.

**Comment by pascaloettli** [comment]
Related #4965

**Comment by kevinushey** [comment]
You might need to specify a different matplotlib backend:

```
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("tkAgg")
plt <- reticulate::import("matplotlib.pyplot")
plt$hist(1:100)
```

**Comment by kevinushey** [comment]
Perhaps we should just set this as the default backend when using reticulate in RStudio as well.

**Comment by david-cortes** [comment]
> You might need to specify a different matplotlib backend:
> 
> ```
> library(reticulate)
> matplotlib <- import("matplotlib")
> matplotlib$use("tkAgg")
> plt <- reticulate::import("matplotlib.pyplot")
> plt$hist(1:100)
> ```

But that wouldn't make the plot show either (tried in windows 10 and debian buster).

**Comment by kevinushey** [comment]
Does it show if you call `plt$show()` after? (my understanding is, in general, you need to call `plt.show()` to show a plot, except in some augmented Python environments e.g. IPython Notebooks)

**Comment by david-cortes** [comment]
> Does it show if you call `plt$show()` after? (my understanding is, in general, you need to call `plt.show()` to show a plot, except in some augmented Python environments e.g. IPython Notebooks)

That makes it show, thanks. But it opens in a new window rather than showing in the plot pane.
