### ISSUE TITLE
macOS Catalina & RStudio Dailies help-backticks

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#4983]
Fire up RStudio macOS dailies on macOS Catalina. Fresh session. Nothing loaded.

In Console tab hit `?` then a package name and tab for autocomplete (e.g. `?ggforce::<TAB>ggforce-package<TAB>`).

Previous RStudio's wld auto-backtick quote `ggforce-package`. The current ones do not. I can test on non-Catalina systems later today.

**Comment by kevinushey** [comment]
Looks like this is a regression in v1.3 (I can't reproduce in v1.2).

**Comment by DavisVaughan** [comment]
FWIW I see this and am not on Catalina but am on 1.3

**Comment by dfalty** [comment]
Verified fixed 1.3.867
