### ISSUE TITLE
Catalina: Qt file dialogs on macOS Catalina & RStudio Dailies

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#4984]
This is likely going to be "wait for Qt to produce something for Catalina to fix all the Qt—Catalina bugs" thing but FYI…

For especially Save dialogs:

- dialogs take ~2x longer to come up (likely something to do with Apple's new weird volume stuff & Qt not groking something)
- focus is not set to the file name
- cannot <TAB> to any field or control
- <ESC> out takes ~2x longer to do if no other interaction occurred in the dialog

But all (ok, _most_ since I likely haven't hit all possible scenarios) file dialogs take ~2x longer to come up and I don't think it's macOS Catalina debugging bits being flipped (they do that with betas sometimes) causing it and I have no SSD issues (double checked that before posting).

**Comment by kevinushey** [comment]
I see the same kind of slowness in other applications -- e.g. even in R.app, trying to open a new document using <kbd>Cmd + O</kbd> takes a good couple seconds before the dialog pops up. So I think this is a Catalina-wide issue rather than something scoped to RStudio specifically.

**Comment by hrbrmstr** [comment]
Aye. When I got back from holiday I was going to note that I believe I saw the same thing esp with the second beta.

**Comment by ronblum** [comment]
@hrbrmstr and @kevinushey are you still seeing this? Assuming you've been steadily updating Catalina betas.

**Comment by kevinushey** [comment]
I haven't been running Catalina recently, so I'm not sure.

**Comment by hrbrmstr** [comment]
thx for the re-up. the latest beta sped many things up. filesystem dialog access is better but it's not a "RStudio" thing, per se. The delay is nowhere near as bad in notarized, 100% macOS API apps, but is still bad in anything else due to the new on-the-fly "sandboxing" (best term I can come up with) Apple is doing. I'll close this b/c I suspect you can't really do anything about it. There was a side-issue here of focus not going on the filename in the file dialogs but that also isn't your problem.
