### ISSUE TITLE
Scrolling not working on Desktop Windows version

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#4991]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1541
    OS Version      : Windows 10 Pro
    R Version       : 3.6.0

### Steps to reproduce the problem
Try to use center wheel or trackpad to scroll on any panel

### Describe the problem in detail
Scrolling is not working in Desktop Windows version but it works in Server version (Ubuntu 18, Chrome Browser client).
![scroll](https://user-images.githubusercontent.com/14981085/59941996-3a56a080-9424-11e9-8671-b4342ea82b40.gif)

**Comment by kevinushey** [comment]
I wonder if this is an unintended consequence of https://github.com/rstudio/rstudio/pull/4935? :-/

**Comment by kevinushey** [comment]
I just tried to reproduce on our in-house Windows laptop and was unsuccessful.

Can you provide any other information about your machine? Are you using your laptop's built-in trackpad, or an external one? Do you also have a mouse plugged in while testing?

**Comment by gtritchie** [comment]
I was also unable to repro on my Windows laptop with an external mouse with scroll wheel or with the trackpad.

**Comment by andresrcs** [comment]
I'm using a surface pro 4 (hybrid laptop/tablet), I have tried with just the trackpad in the removable keyboard, with the touch screen and with an external mouse, same behavior with all of them.

**Comment by gtritchie** [comment]
I tried on a Surface Pro 6 and scrolling worked fine with touch screen and keyboard trackpad. It had two input methods (English and Japanese). Tried both 1.2.1335 and 1.2.1541.

**Comment by andresrcs** [comment]
I figure out what the problem was, I had bad setting for high ppp, this is the config that works, after changing this, scrolling is working as expected.

![image](https://user-images.githubusercontent.com/14981085/59982005-9874b680-95d1-11e9-994e-2fc51d827f6b.png)

**Comment by kevinushey** [comment]
If I understand correctly, PPP -> Display DPI? So, for some reason, overriding the DPI settings broke scrolling with the trackpad?

**Comment by andresrcs** [comment]
Yeah, sorry I forgot that PPP (Puntos Por Pulgada) needs to be translated to DPI (Dots Per Inch), if I choose this option for RStudio, scrolling stops working with the trackpad and with external mouse

![image](https://user-images.githubusercontent.com/14981085/60037887-72562180-9678-11e9-9821-a9f35929f89c.png)

**Comment by kevinushey** [comment]
I think this issue can be closed then. (In theory we could try and discover and fix the underlying issue but I suspect that will be very challenging)

**Comment by JoachimP1** [comment]
I use a 13" laptop and it is impossible to use the application without setting "override high DPI scaling behavior. Scaling performed by:" on "system", because the default rescaling of RStudio makes everything huge and doesn't work.
But setting this setting on "system" causes the scroll function to fail. So it would be good if the DPI scaling is optimised or the scroll problem or both can be solved.
