### ISSUE TITLE
High CPU usage when scrolling on macOS

### ISSUE THREAD

**Issue by bouli80** [rstudio/rstudio#4998]
It seems to me that RStudio 1.2.1335 for MacOS uses too much CPU for simple GUI interactions that should not be that demanding, e.g. scrolling. When scrolling through my RScript, the RStudio process often uses 60% of CPU and the QtWebEngineProcess 100%. I noticed because fans often started spinning audibly when I was scrolling through scripts. I tried forcing the OpenGL option in the settings, as well as unchecking the Use GPU blacklist and driver workarounds options. I also tried forcing software rendering. I did not notice much difference with either of those settings. Using the default Textmate theme. It happens even with empty global environment and no packages loaded, and with relatively short scripts (less than 100 lines).

I tried also the preview (1.2.1541) version, but the problem persists.

My configuration:
MacBook Pro (Retina, 13-inch, Mid 2014)
2,6 GHz Intel Core i5
8 GB 1600 MHz DDR3
Intel Iris 1536 MB
MacOS 10.14.5

**Comment by ronblum** [comment]
@bouli80 Thank you for reporting this. We'll check it out as we work on future development of RStudio.

**Comment by MarkErik** [comment]
I am also seeing the same behaviour. If I just slowly scroll, click, scroll, click:

The QtWebEngineProcess will use about ~135% CPU
RStudio will use 35%

RStudio: 1.2.1541
macOS: 10.14.4
iMac 2015 - Retina 27"
Quad-core 3.2Ghz i5
24GB Ram

**Comment by nehera** [comment]
I am having the same problem with RStudio @MarkErik or @bouli80 did you find a solution?

**Comment by FrancoisR95** [comment]
I have a similar problem with RStudio 1.3.1056 on Windows 10 (64 bit), I don't know if it's the same root issue or not:
While doing nothing else than very simple GUI interactions (e.g. moving the cursor while editing a script, or scrolling), the CPU spikes for a few seconds up to almost 100% once or twice per minutes, making the ventilator ventilate (noisy). The process rsession.exe is the one taking ressources.
I experienced the same issue with RStudio 1.3.959, but I didn't notice such thing when I was working with RStudio 1.2.5042.

If I scroll using the "up" or "down" arrows, the CPU gets much higher than if I scroll with the "Page UP"/"Page DOWN" arrows.

When, in the "R general->Advanced" options, I change "Rendering engine" from "Auto-detect" to "Software", it might improve a little but it does not seem to change much.

My system has got 16 GB RAM and an Intel Core i3-3220 CPU @ 3.30 GHz..

**Comment by bouli80** [comment]
@nehera: No solution for me. I suspect it may be connected to qt, because other qt apps (such as lyx) exhibit similar behavior.

**Comment by nehera** [comment]
@FrancoisR95 @bouli80 I found the cause of the problem on my end. 

I was running a model with a large number of output files (in the 5000 range) and the RStudio was experiencing problems rendering the large number of changes into the GUI. When I hovered over the Git box in RStudio, QtWebEngineProcess spiked in CPU %. I have since reduced the number of output files in the syncing directory and experienced no problems. 

I have the following device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports); 2.3 GHz Quad-Core Intel Core i7; 16 GB 3733 MHz LPDDR4X; Intel Iris Plus Graphics 1536 MB

All the best, 
A

**Comment by jonaski** [comment]
We see the same behavior in strawberry (https://github.com/strawberrymusicplayer/strawberry/issues/542), I've reported this to Qt here: https://bugreports.qt.io/browse/QTBUG-123343
Please help fill in more information on the Qt issue if you have any.
