### ISSUE TITLE
Get job states with rstudioapi

### ISSUE THREAD

**Issue by noamross** [rstudio/rstudio#5006]
Currently, one can set job states, status, etc., with function luke `rstudioapi::setJobState()`.  However, one can not retrieve them as far as I can tell.  I would like a `getJob()` or `getJobs()` function akin to those functions for launcher jobs.  My use-case is writing some wrappers to alert me to the status of jobs running on my server (with **RPushbullet**).

**Comment by noamross** [comment]
Possibly better would be to add a hook to `jobRunScript()` and/or `jobAdd()`(perhaps as an action), for a function to run after a script fails/completes.

**Comment by ronblum** [comment]
@noamross Thank you for the suggestion! This repository is for the RStudio IDE, though (Desktop and Server). The [rstudioapi repository](https://github.com/rstudio/rstudioapi/issues) is located at https://github.com/rstudio/rstudioapi/issues, so this request should be filed there.
