### ISSUE TITLE
Highlight function parameters + separate styling for operators

### ISSUE THREAD

**Issue by Mashin6** [rstudio/rstudio#5008]
I found that this has been requested a while ago here: https://support.rstudio.com/hc/en-us/community/posts/211643088-syntax-highlighting-for-known-function-names-parameter-names
But I couldn't find any news about adding possibility to add highlighting of parameters.

A second suggestion is to allow separate styling option for (), <-, %>%, =, etc.

**Comment by ronblum** [comment]
@Mashin6 Thank you for the suggestion. We'll review this as we continue development of RStudio.

It's possible to create custom themes, uploaded using Tools -> Global Options -> Appearance -> Add. However, @MariaSemple—is it possible to make themes that have different styling for parameters and each operator?

**Comment by MariaSemple** [comment]
It is possible to do some custom styling for operators. Unfortunately, it is not currently possible to have separate styling for parameters. We are tracking this enhancement request here: https://github.com/rstudio/rstudio/issues/3717.

To apply a style for all operators, you can use the CSS selector `.ace_keyword.ace_operator`. To apply a style for `()`, `{}`, and `[]`, you can use the CSS selector `.ace_keyword.ace_operator.ace_paren`. To apply a style for custom user operators (anything within `%%`, including `%>%` and `%/%`), you can use the CSS selector `.ace_keyword.ace_operator.ace_infix`.

**Comment by Mashin6** [comment]
Thank you `.ace_keyword.ace_operator.ace_paren` already helped.

It's great that you already thought about the parameter styling. I think everybody would benefit if we could improve the readability of R code as it is in Sublime.

<img width="514" alt="Screen Shot 2019-06-26 at 12 52 03 " src="https://user-images.githubusercontent.com/5265707/60152214-a4b56b00-97ad-11e9-8668-029075c2d74c.png">
