### ISSUE TITLE
chunks outputs restored within folds can 'float'

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5010]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.2.1522
    OS Version      : macOS Mojave 10.14.5
    R Version       : R version 3.6.0 Patched (2019-05-29 r76623)

---

![floating-chunks](https://user-images.githubusercontent.com/1976582/60135833-76a53c00-9757-11e9-8d09-92cf4a43b744.gif)

---

Seems like there are two issues:

1. We shouldn't try to restore chunks within folds.
2. Chunks restored within folds appear to have a higher likelihood of becoming 'floating' chunks.

Note that it is challenging to reproduce this consistently.

For good measure, the document I was using to reproduce with:

`````
---
title: "Untitled"
output: html_document
---

```{r}
print("Some text.")
```

```{r}
print("Some other text.")
```
`````

**Comment by kevinushey** [comment]
@jmcphers do you think this meets the bar for v1.2-patch? I could see this happening more often in larger R Markdown documents where users fold sections that contain chunk outputs. This issue then could arise if they were to close and re-open the IDE.

**Comment by jmcphers** [comment]
This doesn't have a super consistent repro nor many reports in the wild (I'm guessing that most people don't fold chunks in notebooks very often!). Moving out of 1.3.

**Comment by kevinushey** [comment]
A fix worth exploring (if we want to take a look in the future) would be to try to ensure that folds are applied only after chunk outputs are restored within a document.
