### ISSUE TITLE
Voluntarily save RStudio session

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#5018]
Upon closing, RStudio asks you to save the session. Why isn't there a UI command to replicate the saving process that happens on RStudio closing? Eg. a command in the File menu (on Mac). This would protect from session information loss (history, data) before trying operations that are at risk of crash or hand (like multicore procedures).

At the moment I have to force this behavior by fake creating a new project, which prompts me to save the current one.

Thanks

**Comment by pascaloettli** [comment]
Isn't `Session --> Save Workspace As...` already doing this?

**Comment by bakaburg1** [comment]
> Isn't `Session --> Save Workspace As...` already doing this?

No, that is a "Save as" function, to create a copy of the workspace as a different file. I want to update the status of the .Rproj file, like when you close RStudio.

**Comment by pascaloettli** [comment]
So please edit your question, it is not clear what you want.

**Comment by bakaburg1** [comment]
> So please edit your question, it is not clear what you want. To me, saving the session means saving the workspace.

I thought it was clear since I specified in the first sentence that I'm referring to the saving that happens on RStudio closing. I specified it more clearly. If you have suggestions on how to make it clearer please do suggest.

**Comment by pascaloettli** [comment]
So you want to save script and workspace at once from the UI?

**Comment by bakaburg1** [comment]
Yes, the exact procedure that RStudio does on closing, only that I would like to fire it manually. Like it happens in any productivity program (Excel, Photoshop, etc)

**Comment by ronblum** [comment]
@bakaburg1 No sweat, your description is clear. I'll mark it as an enhancement to review as we continue to develop RStudio. Thank you for the suggestion!

**Comment by jmcphers** [comment]
You can do this pretty simply with `save.image()`. 

> save.image() is just a short-cut for ‘save my current workspace’, i.e., save(list = ls(all.names = TRUE), file = ".RData", envir = .GlobalEnv). It is also what happens with q("yes").

https://stat.ethz.ch/R-manual/R-devel/library/base/html/save.html

**Comment by bakaburg1** [comment]
> @bakaburg1 No sweat, your description is clear. I'll mark it as an enhancement to review as we continue to develop RStudio. Thank you for the suggestion!

Thank you!

> You can do this pretty simply with `save.image()`.
> 
> > save.image() is just a short-cut for ‘save my current workspace’, i.e., save(list = ls(all.names = TRUE), file = ".RData", envir = .GlobalEnv). It is also what happens with q("yes").
> 
> https://stat.ethz.ch/R-manual/R-devel/library/base/html/save.html

Ok thank you I didn't know! But is there any reason not to have it as UI (just a cmd+shift+S away), it's a standard feature in practically every software I know of.

**Comment by jmcphers** [comment]
That's a good question. One major difference between an R session and e.g. a Word document is that saving the latter can usually be done in less than a second, but many R sessions have objects that take considerable time and space to save. Of course, you can mitigate this by doing extra work to create optimized save formats, differential saves, etc., but that's obviously a good deal more work than adding a button that calls `save.image` for you. :-) 

If you'd like you can make an add-in that binds `save.image` to a hotkey for you in a few lines of code:

https://rstudio.github.io/rstudioaddins/
