### ISSUE TITLE
Catalina: running Shiny apps turn windows gray/black and make the IDE inoperable

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5026]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335 and 1.2.1555
    OS Version      : MacOS 10.15 Catalina
    R Version       : 3.6.0

### Steps to reproduce the problem

1. On MacOS, upgrade to Catalina
2. Open RStudio Desktop 1.2
3. Skip the requests to install Kaiti fonts
4. File -> New File -> Shiny Web App
5. Provide an application name, then click Create
6. Run App

### Describe the problem in detail

A new window will pop up, as expected. Then both windows will turn black or gray, depending on the MacOS light or dark theme, and the IDE will become inoperable. The only way to exit is by using Force Quit.

### Describe the behavior you expected

The IDE should continue to work.

This is not an issue in 1.1.463—it works as expected.

**Comment by jmcphers** [comment]
Can confirm. 

![image](https://user-images.githubusercontent.com/470418/60300253-720d8e80-98e3-11e9-813e-b61f62360d24.png)

**Comment by abhics93** [comment]
+ 1

**Comment by ronblum** [comment]
@jmcphers and @abhics93 This is working with MacOS 10.15 Catalina public beta 3.
