### ISSUE TITLE
optionally respect .gitignore and .RBuildignore in find in files search

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rstudio#5031]
When I search (and replace) strings in a project (say, some variable name), I'm often *only* interested in the *real* source, and not a bunch of the derivative folders that are in my project at any given time (`/man`, pkgdown stuff, ...).
This is already documented in `.gitignore` and/or `.Rbuildignore`. 

It'd be nice to optionally respect these files in the find in files search menu.

**Comment by ronblum** [comment]
@maxheld83 Thank you for the suggestion. Just to make sure I understand correctly, you're suggesting that if a directory or file is in `.gitignore` or `.Rbuildignore`, "Find in Files` should ignore it?

**Comment by maxheld83** [comment]
yes that's what I thought (optionally, maybe with a little checkbox to globally respect all `.gitignore` and `.Rbuildignore`s.
If figure these files are (already) the canonical space to document "derivative" files.

**Comment by ronblum** [comment]
@maxheld83 Great, thanks! Clearly, I asked for a clarification of something that was already clear from the start. :) I've marked your suggestion as an enhancement to review as continue development of RStudio.
