### ISSUE TITLE
Please consider releasing a .deb for Debian 10

### ISSUE THREAD

**Issue by highvoltage** [rstudio/rstudio#5037]
Debian 10 will be released towards the end of this week. The Debian 9+ .deb file from the downloads page doesn't work on Debian 10 due to a newer openssl version. Please consider building a Debian 10 deb for the download page as well.

**Comment by ronblum** [comment]
@highvoltage Thank you for the request. Do either the [released version](https://www.rstudio.com/products/rstudio/download/)
or [latest Preview](https://www.rstudio.com/products/rstudio/download/preview/) of the Ubuntu 18 distribution work on your Debian 10 RC environment? Also, are you referring to RStudio Desktop or Server?

**Comment by ronblum** [comment]
In addition, are you using Debian 10 RC 1 or RC 2?

**Comment by pipedream** [comment]
@ronblum 

The released version from Ubuntu 18.04 at https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb works (well, installs and opens, we've not tried more) since it depends on a newer openssl.

We are referring to Rstudio Desktop.

We are using Debian Buster RC2

**Comment by ronblum** [comment]
@pipedream Thank you for checking! That's in line with what I'm seeing using RStudio Server. We'll discuss internally how to manage this.

**Comment by jmcphers** [comment]
I've just updated our downloads page with a link for Debian 10 explicitly (and we no longer say "Debian 9+").

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by highvoltage** [comment]
Thanks!

**Comment by dirks** [comment]
The problem seems to persist with rstudio server on Debian 10. Unsure if this issue should be reopened or a new one should be created.

**Comment by paulmenzel** [comment]
Please create a new issue.

**Comment by ronblum** [comment]
@dirks Which link are you using for downloading RStudio Server?
