### ISSUE TITLE
verify-installation does not work in RStudio Open Source

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5040]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3
    OS Version      : Linux (any)

### Steps to reproduce the problem

Stop RStudio Server, then run:

    rstudio-server verify-installation

### Describe the problem in detail

The script claims that RStudio Server is still running, even though it isn't.

    Server is running and must be stopped before running verify-installation

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio/commit/56be15e741a0199fb3087735e6f2c060fb9487db

**Comment by ronblum** [comment]
@jmcphers This is identified for the 1.2 patch, but I can't reproduce this in version of 1.2. Is there a version/OS of 1.2 in which this happens?

**Comment by kfeinauer** [comment]
This should reproduce on RStudio Server Open Source v1.2.1335

**Comment by ronblum** [comment]
@kfeinauer I can't. This is RStudio Server Open Source 1.2.1335 on Red Hat 7.6:

```
[root@ip-172-30-1-245 ec2-user]# rstudio-server verify-installation
Server is running and must be stopped before running verify-installation
[root@ip-172-30-1-245 ec2-user]# rstudio-server stop
rsession: no process found
[root@ip-172-30-1-245 ec2-user]# rstudio-server verify-installation
[root@ip-172-30-1-245 ec2-user]# echo admin-enabled=1 >> /etc/rstudio/rserver.conf
[root@ip-172-30-1-245 ec2-user]# rstudio-server verify-installation
Error reading /etc/rstudio/rserver.conf: unrecognised option 'admin-enabled'
[root@ip-172-30-1-245 ec2-user]# rstudio-server version
1.2.1335
[root@ip-172-30-1-245 ec2-user]# 
```

**Comment by kfeinauer** [comment]
Try running on Ubuntu 16.

**Comment by ronblum** [comment]
Thanks! I can reproduce the issue and confirm the fix.
