### ISSUE TITLE
Run Chunks does not work on RStudio Server

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5041]
### System details

    RStudio Edition : Server (only)
    RStudio Version : 1.3.291

### Steps to reproduce the problem

1. Create a new R Markdown document (File -> New -> R Markdown)
2. Run the first chunk

### Describe the problem in detail

The chunk starts running, but never finishes.

### Describe the behavior you expected

The chunk should finish running.

**Comment by kfeinauer** [comment]
Is the version correct? `RStudio Version : 1.2.329`

**Comment by jmcphers** [comment]
Nope, will fix!
