### ISSUE TITLE
Positioning of cursor after Malayalam strings

### ISSUE THREAD

**Issue by ajithramayyan** [rstudio/rstudio#5048]
While learning R and R studio, I noticed a possible bug in the display of Malayalam strings.

If you type "കഖഗഘ" at the R studio console, the cursor is seen after  "കഖഗ (to be exact, the cursor is seen blinking a bit after the start of ഘ). But, the cursor functions as if it is at the end of the string. For example, if you press backspace, the ending quote is deleted, not ഗ. Selecting the entire string will show only the first three letters and the opening quote as selected though in reality the entire string is selected.

This appears like a problem of calculating the width of Malayalam characters (may be other languages too). If you look carefully, the cursor is not placed correctly even after 1 Malayalam character and the distance at which the cursor is placed from the end of the string increases as the length of the string increases.

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.463
    OS Version      : Windows 7 Professional
    R Version       : 3.5.3

**Comment by pascaloettli** [comment]
You are using a quite old version of RStudio. Do you see the same behaviour either with the [current version](https://download1.rstudio.org/desktop/windows/RStudio-1.2.1335.exe) or the [preview version](https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.2.1555.exe)?

**Comment by pascaloettli** [comment]
True in current, preview and daily build RStudio versions, on Ubuntu.

**Comment by ronblum** [comment]
@ajithramayyan Thank you for reporting this, and @pascaloettli for reproducing in Ubuntu. I can also reproduce this in RStudio Desktop 1.2.1555 on MacOS 10.15 Catalina. This is true both in the Console and Source panes. It's OK when putting in the search fields in both panes, but the results in the Console are highlighted with the error. We'll review this as we continue development of RStudio.
