### ISSUE TITLE
Feature: Add scroll bar for (long) file list

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#5050]
The file list (if lots of files are open) does not scroll when it otherwise should. In the image below, I have many more files than will fit on the screen, so the bottom of the list is just unreachable.

![image](https://user-images.githubusercontent.com/23075542/60532408-3d2a7e80-9ccb-11e9-9d8d-b4ffd7b75271.png)

**Comment by gtritchie** [comment]
See also: #1760, #1794, #2330, #3635

**Comment by colearendt** [comment]
Oops. Duplicate of #2330. Thanks! Sorry for the trouble!
