### ISSUE TITLE
content search in console

### ISSUE THREAD

**Issue by twangxxx** [rstudio/rstudio#5056]
Hi, I was developing an R package with RStudio (version 1.1.463). When I ran `devtools::check() ` to check the package, it returned a lot of results apparently. Then I found it was difficult to find a result of a specific check (e.g. `Checking installed package size`) unless by scrolling the siders manually. I was somehow surprised there is no such an option to search in the full content in console (not only the command history in the console) as we have in other three panels.

So I was thinking it might be great to have a new feature to search in the console of RStudio in order to help users who would like to search for something in the massive output.

**Comment by ronblum** [comment]
@twangxxx Thank you for the suggestion—we will review it as we continue development of RStudio.

**Comment by aronatkins** [comment]
Search in console and terminal would be really helpful when a command generates a sizable amount of output.

**Comment by gtritchie** [comment]
Note, our terminal library (xterm.js) does now have functionality for performing search that could be used (terminal only, console is a separate thing). https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-search
