### ISSUE TITLE
Primary Vagrant Environment fails

### ISSUE THREAD

**Issue by aforsythe** [rstudio/rstudio#5057]
The primary vagrant environment fails to load due to multiple issues

- Missing `cmake` as noted in #4712 
- Missing gpg key
- Multiple ` dpkg-preconfigure: unable to re-open stdin: No such file or directory` errors

**Comment by ronblum** [comment]
@aforsythe Thank you for raising this, and for including the existing issue in your list. We will review it.

**Comment by jmcphers** [comment]
- I have fixed #4712. 
- I'm not sure which GPG key you're referring to (but happy to help if you can be more specific!)
- The `dpkg-reconfigure` errors are normal when using Vagrant; they happen because Vagrant doesn't hook up standard file descriptors during vagrant up.
