### ISSUE TITLE
Using "#" comment BASH code chunks

### ISSUE THREAD

**Issue by Yiguan** [rstudio/rstudio#5060]
For Rmarkdown:

When I use shortcut cmd+shift+c for bash chunks, it comments code lines with:
`<!-- some code -->`

Why not "#", like in R code chunks? 

`<!-- some code -->` is still executed in terminal, doesn't actually comment out the code.

**Comment by ronblum** [comment]
@Yiguan That's a good question. However, in the code, the first and second examples are identical. Did you mean to have a different second example, using `#`?

**Comment by Yiguan** [comment]
> @Yiguan That's a good question. However, in the code, the first and second examples are identical. Did you mean to have a different second example, using `#`?

Yes. I wish I can comment bash code with "#"  rather than "" in Rmarkdown.

**Comment by ronblum** [comment]
@Yiguan Thank you. This could be something like overriding the existing shortcut to use `#` within bash chunks, or create a new bash-specific shortcut. We'll review this as we continue to develop RStudio.
