### ISSUE TITLE
RStudio hangs at starting initial session due to umlauts in username

### ISSUE THREAD

**Issue by axrhart** [rstudio/rstudio#5062]
### System details
```
RStudio Edition : Desktop
OS Version: Windows 10 x64 Pro
RStudio Version: RStudio 1.2.1335 - Windows 7+ (64-bit)
R Version: 3.6.0
```
### Steps to reproduce the problem
With an admin user account, that has the *umlaut ö* in its name/home path:
1.  Install R 
2.  Install RStudio
3. Open RStudio

### Describe the problem in detail
The outer window frame appeared, but before the session got initialized RStudio shows an error message similar to https://github.com/rstudio/rstudio/issues/2056. However, it did not mention `core` but rather some jarvis folder in AppData. 

Unfortunately, I cannot provide screenshots or reproduce on the same machine, since this happend to a participant during a workshop.

Reinstalling did not sove the problem.

### Describe the behavior you expected
RStudio starting a new session, with no open documents/objects in the global.env.

### Further Information
Our only ad hoc workaround was to create a new user without an umlaut in its username, which worked fine from the start. However, a dual user setup (or a migration to the new user) is not what I would consider a satisfying solution.

**Comment by ronblum** [comment]
@axrhart Thank you for raising this issue! We have run into a few issues with non-ASCII characters, such as the one you referenced, and another one having to with git, #2035. I'm including it as a reference as we review the issues during ongoing development of RStudio.

**Comment by petrbouchal** [comment]
This also manifests when other non-ASCII characters are in the path to the project directory.

Version 2023.03.0-daily+3 (2023.03.0-daily+3)
R version: 4.2.1

**Comment by ronblum** [comment]
Hello again, @petrbouchal! Also for this issue, did the problem occur in previous versions of RStudio?

**Comment by petrbouchal** [comment]
Yes, this happens on the current stable version as well as Cherry Blosson, and probably a slightly (~3 mos?) older version which I now cannot track down specifically.
