### ISSUE TITLE
Help pane defaults to serif (ugh)

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#5066]
Me again.

Latest Catalina beta. RStudio daily 1.3.299

QtWebEngine is not displaying Lucida Grande. 

![image](https://user-images.githubusercontent.com/509878/60679209-d8029480-9e54-11e9-8b8d-db872166f71f.png)

No messages in inspector Console for the help pane. Even when I try to set `sans-serif` for virtually every element in the pane it still defaults to serif.

There were a cpl QtWebEngineProcess errors in the macOS Console, both related to trying to read values from a sandboxed area. 

What's strange is that the RStudio "Home" HTML page in the help pane is normal:

![image](https://user-images.githubusercontent.com/509878/60679337-4182a300-9e55-11e9-8d06-8a1576df5203.png)

I've given RStudio Full Disk Access as well so that shouldn't be part of the problem.

As usu…lemme know how I can assist.

**Comment by ronblum** [comment]
@hrbrmstr Thanks—as always—for letting us know. I can reproduce this in RStudio Desktop 1.2.1335 and 1.2.1555, but it works fine in 1.1.463. So this is a regression.

**Comment by jmcphers** [comment]
I can also reproduce this on Catalina. It's ugly, and the font is too small. Interestingly enough the computed style shows as `sans-serif`! So somehow QtWebEngine is resolving that to a serif font in Catalina.

![image](https://user-images.githubusercontent.com/470418/63626016-58708680-c5b6-11e9-8824-c034bdf31a0d.png)

**Comment by hrbrmstr** [comment]
Aye. I'm abt ready to switch to Python & PyCharm ;-)

**Comment by dfalty** [comment]
Those pesky serifs look gone for me on 1.3.867 :)

**Comment by hrbrmstr** [comment]
Yep! Looks gd!

1.3.866 just has some RStudio graphics device issues ;-)

**Comment by kevinushey** [comment]
@hrbrmstr can you elaborate? There aren't any (new) graphics device issues as far as we know.
