### ISSUE TITLE
Resizing source pane with soft wrap loses position

### ISSUE THREAD

**Issue by rcragun** [rstudio/rstudio#5070]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      :  Windows 10 1809
    R Version       :  3.5.1

### Steps to reproduce the problem

- Open a long Rmd source file with many long R chunks. Alternatively, open any long R script and set the soft-wrap option on in the global options.
- Scroll down in the source pane (a little more than halfway through the file should be sufficient).
- Change the horizontal size of the source pane.

### Describe the problem in detail
The source viewer will not show the same lines that were visible before the resize.

### Describe the behavior you expected
I expect that the first line visible in the source pane before the resize will be the first line visible after the resize (or maybe some hybrid between this and keeping the line with the cursor on the screen if it is currently on screen, but that sounds difficult).

**Comment by ronblum** [comment]
@rcragun Thank you for reporting this. Can you provide an example of long enough code to reproduce this? Thanks!

**Comment by rcragun** [comment]
An example Rmd file that is long enough:

[MultipleRegExample.txt](https://github.com/rstudio/rstudio/files/3374654/MultipleRegExample.txt)

**Comment by ronblum** [comment]
@rcragun Thank you! I'm able to reproduce this on RStudio Desktop 1.1.463 and 1.2.1555 on MacOS 10.15 Catalina. Without literally counting, with moving moving horizontally increasing and shrinking the lines, I suspect the display is using the number of characters rather than current line position. 

I'll mark this as a bug—existing in earlier versions of RStudio—although it may turn out that this is actually expected behavior for soft wrapping. However, other programs—for example, Notepad—keep the top line fixed and the displayed characters are all relative to that.

**Comment by rcragun** [comment]
I cannot think of a use case where having the number of vertical characters before the viewing window held fixed would be useful with text wrapping. The value of keeping the top line fixed seems evident: users will always have something close to what they were working on on screen after a resize.

**Comment by raphael-lorenzdelaigue** [comment]
I have what I think might be a similar problem.

I made a video screen capture of the behavior. Look at how the line number changes on the left side of the source pane. It goes from ~300 to ~500.

In other words, if I am at line 300, and I want a wider source pane, I need to:

- Widen the source pane
- scroll 200 lines back up

To me, it would be user-friendlier if I wouldn't need to scroll the 200 lines back up.

https://user-images.githubusercontent.com/58738728/135642025-6e71e97b-2d0e-4bde-be00-abeba611b71b.mp4

There is a workaround mentioned [here](https://community.rstudio.com/t/losing-position-when-resizing-script-window/36116) that is working fine, but maybe there is a way to make this even easier? E.g. by simply keeping the line number on the left side fixed, independently of the pane width?
