### ISSUE TITLE
Assignment operator shortcut not working on certain keyboard configurations

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#5072]
Looks like https://github.com/rstudio/rstudio/issues/2486 is back in RStudio 1.3.300 (and at least a couple of earlier versions) and RStudio Cloud.

**Comment by ronblum** [comment]
@martj42 Thank you for reporting this! Sorry that issue has resurfaced—we'll review it as we continue development.

**Comment by martj42** [comment]
This works as expected again as of 1.4.553. 👍🏼
