### ISSUE TITLE
This repository is mis-tagged: the master branch is identified as v1.2.1330-927-gd8144c5b59, but there is also 1.2.1335 available

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#5074]
```1.2.1335``` is be more outdated than ```v1.2.1330-927```.

Could you please make sure that the latest release number also corresponds to the most recent code?

Could you please also tag the version with the boost problem fixed?

**Comment by ronblum** [comment]
@yurivict Can you confirm that this is the case when pulling the master? I'm getting `v1.2.1335` but we might be looking at it differently.

**Comment by yurivict** [comment]
I use this script:
```
#!/bin/sh

REPO=$1
REV=$2

DIR=$(echo $1 | sed -e 's|.*/|| ; s|\.git$||')

(
  git clone $REPO &&
  (cd $DIR && git describe --tags $2) &&
  rm -rf $DIR
)
```
with the argument:
```https://github.com/rstudio/rstudio.git```

It returns ```v1.2.1330-1277-ged04690585``` while your ```Releases``` page lists ```1.2.1335``` as the latest release.

**Comment by ronblum** [comment]
@yurivict Got it—thanks for the script! I'll mark it as a bug to be reviewed.

**Comment by jmcphers** [comment]
Should be resolved now; `git describe` returns the most recent tag, 1.2.1578. 

    $ git describe --tags master
    v1.2.1578-1277-g353692f69f

We don't currently tag pre-release versions.
