### ISSUE TITLE
.Rtex files not compiling 

### ISSUE THREAD

**Issue by daynefiler** [rstudio/rstudio#5076]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : MacOS 10.4.5
    R Version       : 3.6.0

### Steps to reproduce the problem

Create the file `test.Rtex` with the following contents:

    \documentclass{article}
    \begin{document}
    <<>>=
    print("hello")
    @
    \end{document}  

Compile with `knitr` then compile with `Sweave`. 

### Describe the problem in detail

Due to an annoyance with how Overleaf names R-containing tex files, I have to use the .Rtex extension. .Rtex files are recognized (see #653) but are not compilable. The file will compile using knitr as the backend with the following output

    ¡¡¿¿= print(”hello”) @

and will fail completely using Sweave because the `\SweaveOpts{concordance=TRUE}` is not recognized. It seems like some weave trigger is not happening for the .Rtex files -- they jump directly to `pdflatex` without evaluating any code chunks. 

### Describe the behavior you expected

It would be great if RStudio would compile (whether using knitr or Sweave) .Rtex files as it does .Rnw files.

**Comment by daynefiler** [comment]
(I have also contacted Overleaf to request they recognize .Rnw files as knitr files)

**Comment by daynefiler** [comment]
@ronblum Hi, have you been able to reproduce this bug?

**Comment by ronblum** [comment]
@daynefiler I'm running into a separate issue, and I'm not familiar enough with Rtex and Overleaf, so I've asked internally for help.

**Comment by daynefiler** [comment]
Thanks! .Rtex is another file extension used by knitr ([see pg 29](https://cran.r-project.org/web/packages/knitr/knitr.pdf)). The .Rtex extension was added to the file type registry as `SWEAVE` in #653. For me, .Rtex files look like .Rnw (Sweave) files in RStudio (i.e. same icon and highlighting), but when the pdf compilation occurs the R-parsing and evaluation step (weaving) is skipped. Thanks, again, for looking into this.

**Comment by ronblum** [comment]
@daynefiler OK, I can reproduce this. I get the same results when knitting. For Sweave, I get the error `Undefined control sequence`—is that what you're getting? In any case, I'll mark this as a bug.

**Comment by daynefiler** [comment]
Yes, I get the same `Undefined control sequence` due to the `\SweaveOpts{concordance=TRUE}` added by RStudio when compiling using Sweave.

**Comment by ronblum** [comment]
@daynefiler Oh, good—at least our results are consistent. We'll review this as we continue RStudio development.
