### ISSUE TITLE
Bracket highlighting

### ISSUE THREAD

**Issue by Mashin6** [rstudio/rstudio#5078]
![Rstudio_brackets](https://user-images.githubusercontent.com/5265707/60854578-c7dd1300-a1ce-11e9-8923-ca5b64ab8873.gif)

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1335
    OS Version      : macOS 10.14.5 
    R Version       : 3.6.0

### Steps to reproduce the problem
1. Have multiple brackets next to each other
2. Place cursor next to one bracket
3. Move cursor left or right with arrow keys

### Describe the problem in detail
After moving the cursor with arrow key, the paired-bracket highlighting does not work for the second (neighbor) bracket.

### Describe the behavior you expected
Highlight the paired bracket.

**Comment by ronblum** [comment]
@Mashin6 Thank you for reporting this. We've tried it with RStudio Desktop 1.2.x on MacOS 10.14 Mojave and 10.15 Catalina, but are unable to reproduce this. Would you mind trying out the [current RStudio Preview of the upcoming update](https://www.rstudio.com/products/rstudio/download/preview/) to see if you're still seeing the issue?

**Comment by Mashin6** [comment]
I tried and it happens even with the preview version.
So it seems it's my machine specific. Oh well, maybe it will get fixed with a future macOS update...
