### ISSUE TITLE
Preview output of notebook with multi-line chunks

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#5084]
- If I have a chunk with two lines of code, e.g.

```
iris[1:5,]

iris[5:10,]
```

and I run the entire chunk (green arrow) and then preview, I see the code and the output for each line, as expected.

- If instead I run these two lines one by one, and then preview, I only see the output for the last line, and also not the code for either line.

**Comment by ronblum** [comment]
Hi @mine-cetinkaya-rundel This is actually correct behavior: Preview shows exactly what's been run—how the current results and text look. So to get everything to run you have to knit the file.

**Comment by ronblum** [comment]
@kevinushey This animated gif the original notebook and the preview. Each chunk behaves differently, even though the code is identical. Should they all do the same thing?
![notebook_run_preview_redux](https://user-images.githubusercontent.com/31009952/61539532-b8996900-aa09-11e9-99b9-b4913274a773.gif)

**Comment by kevinushey** [comment]
What's weird to me is that your R Notebook seems to have no output chunks displayed, and yet they show up in the preview.

**Comment by ronblum** [comment]
Ah! It shouldn't be running any chunks and only show what I've actually already run, right?

**Comment by kevinushey** [comment]
Right :) Which is why I'm surprised. Either stale outputs are getting shown in the preview, or for some reason the chunks are getting run at preview time. I'm not sure which exactly.

**Comment by ronblum** [comment]
Ah! I think you're right. Here's a simple reproducible example:
1) Create a Notebook with this code:

````
---
title: "R Notebook"
output: html_notebook
---

```{r}
iris[1:5,]
```
````

2) Run the chunk
3) Preview
4) Run -> Restart R and Clear Output
5) Preview

From now, we're stuck.
