### ISSUE TITLE
Include rscodeio file menu themes as a theme

### ISSUE THREAD

**Issue by rmflight** [rstudio/rstudio#5085]
The [`rscodeio`](https://github.com/anthonynorth/rscodeio) file menu's are so nice, and it's a really, truly dark theme, it would be so great if the full theme was available in RStudio proper, instead of how the code right now just clobbers the settings in the rstudio files themselves.

**Comment by ronblum** [comment]
@rmflight Thank you for the suggestion. However, can you elaborate on what you mean by clobbering the settings?

**Comment by MilesMcBain** [comment]
`rscodeio` replaces the Qt menu dark theme .qss files in the user's RStudio installation. It keeps backups and restores them sensibly, but it's not an ideal situation. Especially given the RStudio installation area is commonly a space where the user needs elevated privileges to make changes.

**Comment by rmflight** [comment]
Oh my gosh yes. I actually ran into a bunch of issues on Linux with the
.rstudio-desktop directory that I ended up doing

chmod 777

On the directory so that Rstudio settings changes would stick.

Yes, rscodeio is really messing with the base theme elements of Rstudio,
but it's soooo pretty.

**Comment by jmcphers** [comment]
Right now "themes" are just CSS files loaded into the RStudio window, so we would have to rethink the theme format to make it possible for it to specify non-HTML menu colors in them. Perhaps a better approach would be to pick up some color values from the CSS and "promote" them to menu elements (via e.g. dummy selectors if there's no repurposable color)

**Comment by jmcphers** [comment]
This theme ultimately messes with RStudio's internals too much to consider formally supporting it by shipping it in the box; we don't have the resources to ensure that everything is themed properly with it as we add and improve UI.
