### ISSUE TITLE
Tab completion for file paths in Rnotebook YAML headers

### ISSUE THREAD

**Issue by RichardJActon** [rstudio/rstudio#5088]
When typing a file path in quotes within a chunk of an Rnotebook you can hit tab a pane pops up with possible filenames from which you can select to autocomplete. It would be nice to have this feature also work within the YAML header, at present hitting tab within a quoted string in the YAML header just inserts a literal tab. 

I find myself expecting this to work in the header quite often as it does elsewhere like in the console and it interrupts my flow as I use this autocomplete feature quite a lot and frequently define file paths in YAML params so I can change them within `rmarkdown::render()`

**Comment by ronblum** [comment]
@RichardJActon Thanks for raising this. As part of reviewing this suggestion, can you provide the environment you are currently working with? Thanks!

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by RichardJActon** [comment]
RStudio Edition : Desktop
RStudio Version : 1.2.1335
OS Version      : Linux Mint 19 (x86_64-pc-linux-gnu (64-bit))
R Version       :  3.6.0 (2019-04-26)

I also checked on my windows machine and got the same behavior:

RStudio Edition : Desktop
RStudio Version : 1.0.153
OS Version      :  windows >= 8 x64 (build 9200) (x86_64_w64-mingw32/x64 (64bit))
R Version       :  3.4.1 (2017-06-30)

And also see it on an Rstudio Server:

RStudio Edition : Server
RStudio Version : 1.1.456
OS Version      :  Red Hat Enterprise Linux (x86_64-redhat-linux-gnu (64-bit))
R Version       :  3.5.2 (2018-12-20)
