### ISSUE TITLE
Encoding issue in Help tab

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#5090]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1555
    OS Version      : Windows 10
    R Version       : 3.6.0

### Steps to reproduce the problem

I typed `diabetes`  (a name of a dataset), parked in with a mouse and pressed <kbd>F1</kbd>.
Then saw the answer in Help tab.

### Describe the problem in detail

A pair of symbols � appeared around `diabetes`. 

![image](https://user-images.githubusercontent.com/12725868/61057978-0a853200-a3ff-11e9-9a74-384e6f3ccd73.png)

### Describe the behavior you expected

Instead of � I expect either a backtick or quotation mark (or nothing at all).

```
- Session info --------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Lithuanian_Lithuania.1257   
 ctype    Lithuanian_Lithuania.1257   
 tz       Europe/Helsinki             
 date     2019-07-11    
```

**Comment by ronblum** [comment]
@GegznaV Thank you for reporting this. Where is the `diabetes` dataset located, so I can try to reproduce the problem? Thanks!

**Comment by GegznaV** [comment]
No package with `diabetes` was loaded. And the dataset I was interested in was in package `mclust`.
But you can try <kbd>F1</kbd> with any other object which is in a package which is installed but not loaded.
E.g., function `tidy`:
![image](https://user-images.githubusercontent.com/12725868/61072343-bf2d4c80-a41b-11e9-87fb-767dc75e2525.png)

If `tidyverse` is loaded, the problem is not present:
![image](https://user-images.githubusercontent.com/12725868/61072434-f56acc00-a41b-11e9-8d4f-f5291dcbc912.png)

**Comment by kevinushey** [comment]
I can reproduce this as well. Setting `options(useFancyQuotes = FALSE)` fixes it. I suspect there's some sort of encoding issue here.

**Comment by GegznaV** [comment]
Still reproducible in RStudio 1.4.1103:
![image](https://user-images.githubusercontent.com/12725868/107271606-275b6e80-6a55-11eb-901f-b97cbbc32f20.png)

**Comment by GegznaV** [comment]
What is the progress towards solving this issue?

**Comment by GegznaV** [comment]
I cannot reproduce the issue with:

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.7.2.576
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)
