### ISSUE TITLE
Independent process for each panel

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#5097]
During long operations, the R session gets stuck. Therefore in addition to the console being blocked, you cannot even browse your plot or your data view panels.

Would it be possible to have a different R process for each panel, in order to be able to use the rest of RStudio even if the console process is stuck?

**Comment by slhck** [comment]
I think this is a general problem with asynchronous handling of UI and code execution. Another example of this is that the UI seems to block saving or manipulating of files when a command is hanging. So, for example, I program on this file, execute a command that results in an unwanted long computation, and I haven't saved — what now? Do I wait forever for the command to finish? Sometimes, clicking the 🛑button doesn't work either and asks me to terminate everything.

**Comment by bakaburg1** [comment]
Yep it's a problem I've had plenty of time too. Maybe Rstudio could have
its own R process separated from console, but this of course it's not easy
to implement. Having the possibility of saving etc while running processes
requires to have a duplicate of the working space in memory or find some
voodoo method around it. But having a process only for UI, without access
to the working space to manage plots, tables, etc can probably be done.

Il giorno lun 15 lug 2019 alle 14:20 Werner Robitza <
notifications@github.com> ha scritto:

**Comment by jmcphers** [comment]
Yes, there are a number of systemic issues caused by the fact that many UI operations have to wait for R. We're tracking this in https://github.com/rstudio/rstudio/issues/2038.
