### ISSUE TITLE
High DPI scaling and font issues in Version 1.2.1335

### ISSUE THREAD

**Issue by ReveStobinson** [rstudio/rstudio#5098]
I have a laptop with a High-DPI screen (3840x2160 13in. display) and I'm experiencing a couple of issues that I believe are related to how RStudio deals with High-DPI scaling. I have the Windows "fix scaling" turned on, as well as having my applications zoomed in to 300%, the recommended for my display. 

The first issue has to do with scrolling in the editor and console. I have my mouse settings currently set to scroll 3 lines at a time, but changing this setting has no effect on how fast I can scroll in the console. RStudio scrolls ~11 lines at a time, which is almost a full window in the editor. This makes navigating my scripts very challenging and frustrating. Zooming in or out on RStudio (from the View dropdown menu) does not change this, but changing the font size does. When I lower the font size, it scrolls more lines, and if I increase the font size it scrolls far fewer lines. Important to note also is that this slightly different when viewing dataframe or tables in the view window. It scrolls 3-4 lines at a time, like I would expect, but this does not change when I change my system settings, so it seems to be some fixed setting there as well. I suspect this is somehow related to font scaling settings. 

The other issue is that when in the view window, viewing a dataframe or table, the horizontal scroll bar is very thin, almost invisible. Here's a screenshot so you can see what I mean.
![image](https://user-images.githubusercontent.com/21211494/61137824-d86de180-a48b-11e9-9720-babd627b1fde.png)

I've tried running the app in various compatibility modes, as well as overriding the scaling settings in every combination possible. Either the app is very blurry and both issues are resolved, or the app looks fine but both issues are still present. I should also note that when I connect my lower-resolution wireless display (1366x768) and drag the RStudio window over to it, the problems are not present while it is on that screen. That does suggest that multi-DPI functionality is not necessarily an issue (referenced in https://github.com/rstudio/rstudio/issues/2135), just High-DPI scaling.

**Comment by kevinushey** [comment]
For extra information?

1. What kind of laptop do you have? (so that we could try and reproduce the issue in-house)
2. Does switching to software rendering make a difference? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by ReveStobinson** [comment]
1. I have an HP Spectre x360 13t running Windows 10 1903, though this issue has always occurred, even before 1903. Specs are as here: 
![image](https://user-images.githubusercontent.com/21211494/61143022-bf1e6280-a496-11e9-90dc-4c9b79da11fa.png) I think I heard HP makes their own display drivers or something like that, instead of using the Windows ones, so that could very well be part of the problem too.

2. Switching to software rendering didn't change anything. Nor did switching to OpenGL.

**Comment by kevinushey** [comment]
Thanks -- I was able to reproduce this on my Windows VM as well. Looks like it reproduces only when using a dark theme, and it does reproduce for any UI scaling other than 100%.

**Comment by ReveStobinson** [comment]
Interesting--never thought to change themes! Yes, I switched to a light theme and the horizontal scroll bar in the data view window looked normal! Still had the issue of scrolling ~11 lines at a time in the editor with different themes, but good to know I can scroll through data a bit easier now! Thanks.

**Comment by kevinushey** [comment]
Thanks! That's helpful. I can confirm something similar -- I have my Windows mouse settings to scroll 3 lines at a time, but I see ~9 lines scrolled on every 'tick' of the mouse scrollwheel. I only see this in the Source pane; not in the Console pane.

Since the problems here seem to be fairly well-understood I'm going to try and target this for v1.3.

**Comment by kevinushey** [comment]
Implementation notes:

- Listen for Window move event / resize event, and check screen number after move complete.

https://doc.qt.io/qt-5/qwidget.html#moveEvent
https://doc.qt.io/qt-5/qwidget.html#resizeEvent

- Check screen number; see if it's changed.

https://doc.qt.io/qt-5/qguiapplication.html#screenAt

- If it has, check the scaling factor set for that screen.

https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor

- Notify client when scale factor has changed.

**Comment by kevinushey** [comment]
This can be solved much more simply: just monitor `window.devicePixelRatio` and update the scroll speed as that changes. Phew!

**Comment by aja08379** [comment]
Customer asking whether this can be changed to a user configurable value?
