### ISSUE TITLE
Fold/Collapsing (Alt+O) removing whitespace. RStudio v1.0 and on

### ISSUE THREAD

**Issue by bnkakey** [rstudio/rstudio#5099]
I finally updated to the new version of RStudio from an 0.99v. I noticed that RStudio (using Alt+O) automatically 1) fold/collapses whitespaces and 2) does not collapse comment chunks within larger code sections. Apparently I was not the only one to notice this. https://support.rstudio.com/hc/en-us/community/posts/245333367-RStudio-v1-0-44-Fold-removing-white-space

To shed more detail I wish to  retain white space when collapsing so that my code can once again look like the screenshot below. 

![image](https://user-images.githubusercontent.com/40832091/61154448-213d8e80-a4bc-11e9-96e1-f20400652908.png)

I posted this question/request to the RStudio community and was told to post this here as a request as to not lose sight of it. https://community.rstudio.com/t/fold-collapse-removing-white-space-rstudio-v1-0-and-on/34344

**Comment by ronblum** [comment]
@bnkakey Thank you for reposting the suggestion/request here! We'll review it as we continue development of RStudio.

**Comment by kylebutts** [comment]
Just wanted to see if this enhancement was added or not. I also would like white space after collapsing my section :-)

**Comment by estroger34** [comment]
This behaviour has been annoying me for years. I really whish whitespaces at the end of a section/chunk would not be folded, it would make understanding the structure of long scripts so much easier!
