### ISSUE TITLE
View() weirdness with a tibble that has a list-column

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#5100]
Apologies for not making an even smaller reprex. I have `View()` overprinting problems and, perhaps, overall session sluggishness after `View()`ing a tibble that has a list-column, in which the `as.character()` representation is very large.

``` r
library(tidyverse)
library(gh)

x <- tribble(
  ~owner, ~repo,
  "r-dbi", "RMySQL",
  "r-dbi", "bigrquery",
  "r-dbi", "RSQLite"
)

get_pull_requests <- function(owner, repo) {
  prs <- gh("GET /repos/:owner/:repo/pulls",
            owner = owner, repo = repo,
            state = "all", .limit = Inf
  )
}

# this takes a few seconds
y <- x %>%
  mutate(pr = pmap(., get_pull_requests))

# and so does this
# View(y)

# it seems related to the number of characters in the
# as.character() representation of the list-col cells
y$pr %>% 
  map(as.character) %>% 
  map(nchar) %>% 
  map_int(sum)
#> [1]  626219 1572581  632677
```

<sup>Created on 2019-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Here's what I see in the object viewer:

<img width="743" alt="Screen Shot 2019-07-12 at 8 51 07 AM" src="https://user-images.githubusercontent.com/599454/61160294-38ea3680-a4ff-11e9-8e01-835627333df7.png">

**Comment by ronblum** [comment]
I can reproduce this in RStudio Desktop 1.2.1558 on MacOS 10.15 Catalina. However,`View(y)` displays correctly with 1.1.463, so this is a regression.

**Comment by ronblum** [comment]
`View(y)` works fine with Google Chrome on MacOS 10.15 (Catalina) pointing to RStudio Server 1.2.1558 on Ubuntu 18.04. So this is probably specific to MacOS.

**Comment by jennybc** [comment]
I just reproduced all of this in 1.4.1103.

**Comment by kevinushey** [comment]
The fix for this is to find a better way of showing the contents of (very large) list columns. The behavior seen here is a browser-specific weirdness that collapses overly-long text entries.

**Comment by romainfrancois** [comment]
For QA, there is code here in addition to the original example: https://github.com/rstudio/rstudio/pull/10398#issuecomment-1035015384

**Comment by jgutman** [comment]
Verified in RStudio Desktop 2022.06.0+116 on Mac OS 12.2 and 2022.06.0+128 on Windows 11.

@romainfrancois -- should you add something to the NEWS about the user preference and setting it via the Command Palette or rstudioapi?
