### ISSUE TITLE
Code Completion Tooltip Behaviour

### ISSUE THREAD

**Issue by omnomz** [rstudio/rstudio#5101]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS Mojave 10.14.5
    R Version       : 3.6.1

### Steps to reproduce the problem
Type any function.

### Describe the problem in detail
1. **Overlapping tooltips**
Check "Show help tooltip after function completions"- Hovering over any function displays two overlapping tooltips: the longer tooltip with arguments is displayed behind the tooltip of the function name.

Are the tooltips supposed to overlap?

2. What should the behaviour of "Show help tooltip on cursor idle" be like?  Checking only this option behaves the same as when both this and "Show help tooltip after function completions" are unchecked. Hope the gif shows what I mean.

![tooltip](https://user-images.githubusercontent.com/49024928/61170093-2d4a4e80-a597-11e9-99e0-d6d7b611ff86.gif)

**Comment by ronblum** [comment]
@omnomz Thank you for raising this issue. I can reproduce it in RStudio Desktop 1.2.1558 on MacOS 10.15 Catalina. My responses:

1) The messages should not overlap. Whenever tooltips are displayed, the information should be legible.
2) I can reproduce this. In my case, I used `ggplot()`. It seems that an idol cursor only results in the tooltip if and only if "... after function completes" is checked: checking it results in both behaviors, and checking "... on idle" doesn't have any impact. Meanwhile, tooltip on autocompletion behaves as expected.

Note that this is not a regression. The behavior described in (2) is similar in RStudio Desktop 1.1.463, but not exactly the same: checking both is required for the tooltip on idle; only checking either one, but not together, doesn't result in a tooltip on cursor idle.

We'll review this as we continue development of RStudio.
