### ISSUE TITLE
Mac OS X is macOS

### ISSUE THREAD

**Issue by msberends** [rstudio/rstudio#5106]
On the download page it still shows "Mac OS X", although the OS that was meant here has been named "macOS" by their developers since version 10.12 (Sierra), released in 2016. The last "Mac OS X" was OS X 10.11 El Capitan.

So the reference here on the downloads page:

![image](https://user-images.githubusercontent.com/31037261/61287541-65cf6f80-a7c5-11e9-9990-a93de5a21534.png)

... doesn't even exist technically. Should be "RStudio 1.2.1555 - macOS 10.12+ (64-bit)". Small thing, but it should just be named right.

**Comment by ronblum** [comment]
@msberends True, it's called "macOS" in most places. How it's called "Mac OS X" in a few. 

```
Rons-MBP:~ ronblum$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15 (19A501i)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
<snip>

Rons-MBP:~ ronblum$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A501i
```

But it's "macOS" almost everywhere, so I'd agree.

**Comment by jmcphers** [comment]
I've updated the website.

**Comment by ronblum** [comment]
Confirmed.
