### ISSUE TITLE
Soft-wrap not applied to C/C++ files

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5110]
**Steps to reproduce:**
* Go to `Tools` -> `Global Options...` -> `Code` -> `Editing`.
* Tick `Soft-wrap R source files` and press `Ok`.
* Optionally, restart RStudio.
* Open some C/C++ file with long lines inside RStudio.

**Expected behavior:** should also soft-wrap those.

**Actual behavior:** does not soft-wrap C/C++ files.

**Comment by ronblum** [comment]
Reproduced with
* RStudio Desktop 1.2.1558 on MacOS 10.15 (Catalina)
* RStudio Server 1.2.1558 on Ubuntu 18.04 using Google Chrome from MacOS 10.15

**Comment by kevinushey** [comment]
Strictly speaking, the preference only applies to R source files -- but we should probably expand that to other file types. (I can't think of a reason why someone would want their R code wrapped but not code in other languages)

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.
