### ISSUE TITLE
Unable to run unit tests that depend on libraries in /usr/local/lib

### ISSUE THREAD

**Issue by dlindelof** [rstudio/rstudio#5114]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Mac
    R Version       : 3.6.0

### Steps to reproduce the problem

I have installed the SQLite ODBC drivers in /usr/local/lib. My code creates a connection to a SQLite database using those drivers (NOT the DBI driver provided by `RSQLite`):

    DBI::dbConnect(odbc::odbc(), driver = "SQLite", ...)

This works fine from the command line and when calling `devtools::test()`, but when I run the tests from the menu (or from Cmd-Shift-T) I get the following error:

    nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libsqlite3odbc.dylib' : file not found

1. The output of sessionInfo() 

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.3.1  plumber_0.4.6   compiler_3.6.0  magrittr_1.5    R6_2.4.0        promises_1.0.1 
 [7] later_0.8.0     tools_3.6.0     rstudioapi_0.10 Rcpp_1.0.1      crayon_1.3.4    stringi_1.4.3  
[13] callr_3.2.0     jsonlite_1.6    ps_1.3.0        httpuv_1.5.1   
```

See also https://stackoverflow.com/questions/57059506/unable-to-run-unit-tests-in-rstudio-that-depend-on-native-libraries-in-usr-loca

2. The R code in question

See above

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3400761/diagnostics-report.txt)

**Comment by ronblum** [comment]
@dlindelof Thanks for reporting this. I'm unable to reproduce the problem, though.

What are you settings for SQLite in the `odbc.ini` and `odbcinst.ini` files? You can find their location using `odbcinst -j`. Also, if possible, can you provide a minimal example of a test file that causes the failure? I want to make sure I'm doing the same thing as you.  Thanks!

Note: I installed the SQLite driver using the directions at https://db.rstudio.com/best-practices/drivers/

**Comment by dlindelof** [comment]
Hi @ronblum ,

Thanks for taking a look at this. Here are the contents of my `odbcinst.ini` file (I don't declare anything in `odbc.ini`:

```
[ODBC Drivers]
SQLite                               = Installed

[SQLite]
Driver = /usr/local/lib/libsqlite3odbc.dylib
```

My SQLite driver came from http://www.ch-werner.de/sqliteodbc/, I haven't tried the one that comes via homebrew. I'll test and come back to you.

Here's a minimal test file that works when stepping through in the editor, but fails when run via `Cmd-Shift-T`:

```
test_that("I can connect to SQLite", {
  src <- DBI::dbConnect(odbc::odbc(), driver = "SQLite")
})

```

which results in this:


```
==> devtools::test()

Loading testodbc
Testing testodbc
✔ |  OK F W S | Context
✖ |   0 1     | odbc [0.2 s]
────────────────────────────────────────────────────────────────────────────
test-odbc.R:2: error: I can connect to SQLite
nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libsqlite3odbc.dylib' : file not found 
1: DBI::dbConnect(odbc::odbc(), driver = "SQLite") at /Users/dlindelof/Work/testodbc/tests/testthat/test-odbc.R:2
2: DBI::dbConnect(odbc::odbc(), driver = "SQLite")
3: .local(drv, ...)
4: OdbcConnection(dsn = dsn, ..., timezone = timezone, encoding = encoding, bigint = bigint, 
       timeout = timeout, driver = driver, server = server, database = database, 
       uid = uid, pwd = pwd, dbms.name = dbms.name, .connection_string = .connection_string)
5: odbc_connect(connection_string, timezone = timezone, encoding = encoding, bigint = bigint, 
       timeout = timeout)
────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════
Duration: 0.2 s

OK:       0
Failed:   1
Warnings: 0
Skipped:  0
```

**Comment by dlindelof** [comment]
Hi again,

Using the driver that comes via Homebrew solves the issue. That is, running

```
brew install sqliteodbc 
```

And fixing any symbolic link errors that may show up.

It's weird, but I can live with that.

**Comment by ronblum** [comment]
@dlindelof Excellent! And you managed to figure out on your own the process we recommend on your own at https://db.rstudio.com/best-practices/drivers/ 💯
