### ISSUE TITLE
List projects, instead of .R files, in Windows jump lists

### ISSUE THREAD

**Issue by themeo** [rstudio/rstudio#5117]
When using Windows 10, I often use "jump lists" when opening documents, e.g. in MS Office. Jump lists are the lists that open after a right-click on the program's icon. In RStudio and e.g. MS Office they contain the list of recently opened files. However, in RStudio, the listed files contain various single files open (e.g. .R files), but it would be way more useful if they contained recently opened projects instead of files. 

![image](https://user-images.githubusercontent.com/2484158/61394773-8c56de80-a889-11e9-9267-4defa1d837d9.png)

**Comment by ronblum** [comment]
@themeo Thank you for the useful suggestion. We'll review it as we continue development of RStudio.

Note: if the project is opened by double-clicking or right-clicking on the .Rproj file, it gets added to the jump list, probably because it's being treated by Windows as if it's just another file.

**Comment by themeo** [comment]
Thanks for taking a look at my suggestion! Just one note: On my system neither double-clicking nor right-clicking on the .Rproj file adds it to the jump list. Only "Open project..." does.
