### ISSUE TITLE
Shortcut for new code line after roxygen comment

### ISSUE THREAD

**Issue by BenjaminWolfe** [rstudio/rstudio#5121]
I often use a knitr::spin workflow, writing and documenting my code in an R script, setting the markdown apart using roxygen-style comments (hashtag then apostrophe). I learned it from the rstats Twitter community; I think it's not uncommon:

- https://twitter.com/kwbroman/status/370217903448014849
- https://twitter.com/apreshill/status/1085571405704515585
- https://twitter.com/thomas_mock/status/1085570338765852674
- https://twitter.com/daattali/status/580596838044160000

I love how, when I'm typing comments, I can just hit Enter and RStudio will continue the comment—that is, the next line automatically starts with the same hashtag-apostrophe combo.

But when I switch from comments to code, I have to hit Enter and then Backspace 3 times to get a clean new line. It would be ultra fluid if I could have **a single shortcut—maybe Shift+Enter—to finish my comment line and start a code line**.

I understand the `kate` editor used by https://twitter.com/RKWardNet does something much like this, but reverses it (Shift+Enter to start a new comment line, Enter to start a line of code).

A recent Twitter thread on this with notes from Jenny Bryan and Kevin Ushey:

- https://twitter.com/BenjaminWolfe/status/1151618914574462976

This is my first feature request; I hope it is detailed enough without being too long-winded.

**Comment by ronblum** [comment]
@BenjaminWolfe Thank you for filing the enhancement request. It's not long-winded at all—the detail is very helpful, including the links to the Twitter threads. The only thing missing is the animated gifs, bud-dy.
