### ISSUE TITLE
R Studio will not open after restarting Windows

### ISSUE THREAD

**Issue by dmklotz** [rstudio/rstudio#5125]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1335, 1.3.180, 1.3.322
    OS Version      :  Windows 10
    R Version       :  6.0

Every single time I restart Windows 10, R Studio fails to open on relaunch.  I've tried all the articles and recommendations (deleting old R data files, temporary renaming the Rstudio folders, holding Control while opening, trying to run as administrator, etc.).  The only method that works is a complete uninstall of R Studio, followed by reinstalling either the official release or a daily release.  And this doesn't always work -- I have to try multiple reinstalls, resets, etc.

The regular R GUI works just fine; as does MS Visual Studio.  This is just an issue with R Studio, and one that never affected my old computer (Windows 7).

I assume it has something to do with file directory permissions, that those might change by default each time Windows restarts, but I really don't know where to start.

### Update

The only way I could resolve this was by installing the unsupported, older version of R Studio, as suggested here.  This worked perfectly (1.1.463):
https://community.rstudio.com/t/rstudio-does-not-start/29541/5

**Comment by kevinushey** [comment]
Do you see anything noteworthy in the RStudio logs? A [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report) may be helpful.

**Comment by dmklotz** [comment]
The diagnostics report didn't work either.  No folder was created within My Documents folder, and the terminal just came up with an empty prompt:

![image](https://user-images.githubusercontent.com/14988804/62293111-d9b07f80-b435-11e9-8625-6d234776bf99.png)

**Comment by jmcphers** [comment]
Sorry, we don't really have anything to go on here! The best general advice we can suggest is to look into permissions (as you noted) as well as antivirus software, which can interact poorly with RStudio (including locking the network ports it uses to communicate between the GUI and the R session, which is new in 1.2). 

You might also try disabling 1.2's software rendering: https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
