### ISSUE TITLE
Build pane randomly interleaves stdout and stderr

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#5126]
1. Download and open https://github.com/hadley/hello (e.g. with `usethis::create_from_github("hadley/hello")`

2. Run `devtools::test()` multiple times.

The output should look like:

```
Loading hello
Testing hello
HELLO
✔ |  OK F W S | Context
✔ |   1       | test
```

But sometimes it looks like

```
Loading hello
Testing hello
✔ |  OK F W S | Context
⠏ |   0       | testHELLO
✔ |   1       | test
```

or 

```
Loading hello
Testing hello
✔ |  OK F W S | Context
HELLO
✔ |   1       | test
```

`HELLO` is printed to stderr; everything else is printed to stdout. The problem only occurs in the build pane, not in the console.

**Comment by jmcphers** [comment]
As @kevin pointed out, this is because we use a polling-based implementation for reading stdout/stderr. We have shortened the poll interval in the past to reduce interleaving, but rapidly interleaved output can still appear in an unpredictable order. 

https://github.com/rstudio/rstudio/blob/847a61ab27b109849b5e5b2a47c808e769ec150d/src/cpp/core/system/PosixChildProcess.cpp#L1038-L1083

**Comment by kevinushey** [comment]
@jmcphers: do you think there's any reasonable way we could handle this?

**Comment by jmcphers** [comment]
If memory serves @kfeinauer already effectively solved this in `AsioAsyncChildProcess`, which uses async read/writes via Boost ASIO to eliminate polling. So perhaps that's not engaging as we think or this process isn't using the new async child model.

**Comment by kevinushey** [comment]
It looks like we still use the 'old' process supervisor for things in SessionModuleContext; e.g.

https://github.com/rstudio/rstudio/blob/9c946fad5604f0dd3cae800e965d9d416ef2eea6/src/cpp/session/SessionModuleContext.cpp#L2089-L2093

We could consider switching this to AsioProcessSupervisor?

**Comment by hadley** [comment]
This is still causing confusion, especially during conversion to testthat 3e. In testthat 3e, messages are now shown (rather than suppressed), and because the order isn't correct in the build pane, it can be hard to narrow down exactly where they're coming from.

**Comment by gaborcsardi** [comment]
We did have a similar problem in some packages that use sub-processes, e.g. rcmdcheck.

In general, when running a sub-process and capturing output from stdout and stderr you might want to have two features:
1. you might want to know if the output went to stdout or stderr,
2. you might want to keep stdout and stderr "correctly" interleaved.

The catch is, (AFAIK) you can only achieve one of these. I would think that for most (all?) build pane output the second one is more important. The second one is also what you get on a real tty.

One way to achieve 2. is to use the same pipe file descriptor / handle for both the stdout and stderr of the sub-process.

**Comment by astayleraz** [comment]
Verified in version 1.5.58-1 the output is consistent and showing as expected. I also added an automation test for this. Closing issue.
