### ISSUE TITLE
Show the interesting source code when click + Ctrl on a function created with purrr::partial()

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/rstudio#5132]
When clickling on a bare function in the editor pane and hitting `Ctrl` (or `cmd` on macOs), RStudio brings me to that function declaration. However, the linking for functions created with `purrr::partial()` brings me somewhere else. Assume this code in the editor pane:

![Screen Shot 2019-07-21 at 15 46 49](https://user-images.githubusercontent.com/10477073/61592099-c51aee80-abce-11e9-9c1a-dc5731e50ed4.png)

Executing the code, pressing `Ctrl` and clicking on `sum_` and at the same time, then releasing `Ctrl`, RStudio opens a new file and shows me this:
![Screen Shot 2019-07-21 at 15 47 31](https://user-images.githubusercontent.com/10477073/61592104-dd8b0900-abce-11e9-8877-6da438e08a7d.png)

It might be technically consistent to show this, but it isn't of any use. It appears to be the same whenever the function of interest is created with `purrr::partial()`.

Can we change the linking to display the call where the function was declared?
```r
purrr::partial(
  sum, na.rm = TRUE
)
```

**Comment by ronblum** [comment]
@lorenzwalthert Thank you for raising this. However, I can't reproduce the issue. On both Windows 7 and MacOS 10.15 using RStudio Desktop 1.2.1335, as well as RStudio Server on Ubuntu 18.04, all with R 3.6, I get the following:

In the Editor pane enter this code:
```
sum_ <- purrr::partial(
  sum, na.rm = TRUE
)
sum_
```
After executing the first line, clicking on CTRL and `sum_` results in the following in the Console:

```
> sum_
<partialised>
function (...) 
sum(na.rm = TRUE, ...)
``` 

What environment are you using? 

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by kevinushey** [comment]
How can we retrieve the 'real' body of these functions generated by `purrr::partial`?

**Comment by kevinushey** [comment]
More generally, the problem here is that the source indexer avoids evaluating R code and only looks for bits of code of the form:

```
f <- function(x) { ... }
```

and so does not understand 'other' mechanisms by which R functions could be generated.

**Comment by lorenzwalthert** [comment]
Thanks. Strange @ronblum. Sorry to not give more details about the environment. Here you go:
```
RStudio Edition : Desktop, free version
RStudio Version : 1.2.1335
OS Version      : macOS 10.14.3
R Version       : 3.6.0
```
@kevinushey the 'real' body of the function seems like something more ambitious to achieve and I believe it's also not necessarily more helpful because there is no point in editing this body, rather, I'd want to edit the call that created the function. As far as the printing method of functions created with `purrr::partial()` goes, there was some discussion about that in https://github.com/tidyverse/purrr/issues/681.
