### ISSUE TITLE
Update to rsconnect 0.8.15

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5136]
The `rsconnect` package on CRAN is now 0.8.15:

https://cran.r-project.org/web/packages/rsconnect/index.html

This new version of the package uses a much improved default HTTP transport, which should help with a variety of SSL issues on Windows (and generally be more robust). We should install it when necessary.

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio/pull/5138.

**Comment by ronblum** [comment]
Verified on RStudio Server 1.2.1568 on Ubuntu 18.04 and RStudio Desktop on MacOS 10.15 (Catalina).
