### ISSUE TITLE
Request: autocomplete for `%$%` operator

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5140]
**Steps to reproduce:**
* Install `magrittr` (from which `dplyr` takes its typical operators).
* Write some code with `%$%` operator (selects a column from a dataframe, used in a similar fashion to `%>%`).
* Try to autocomplete with tab.

**Expected behavior:** should show a drop-down with the available column names.

**Actual behavior:** no autocomplete.

```r
library(magrittr)
df = data.frame(somecol = c(1,2,3), anothercol = c(4,5,6))
df %$% somec<type tab once you reach this part>
```

**Comment by ronblum** [comment]
@david-cortes Thank you for the suggestion. I played around a bit with %>% vs. %$% and it could be valuable, and we'll review it as we continue development of RStudio.

**Comment by david-cortes** [comment]
Still relevant.
