### ISSUE TITLE
support Dockerfiles syntax + go to file

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rstudio#5141]
Currently `Dockerfile`s don't seem to have syntax highlighting in RStudio.

`Go To File / Function` also does not offer `Dockerfile`s.

Rationale: I'm guessing more R projects rely on Docker images, and it'd be nice to stay in RStudio for a quick edit.

**Comment by ronblum** [comment]
@maxheld83 Thank you for the observation. We'll review it as we continue development of RStudio.

**Comment by jmcphers** [comment]
Fixed by #8025.
