### ISSUE TITLE
Apply "Reformat Code" to pipe chains

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#5142]
Reformat code (Code > Reformat Code) does not currently act on pipe chains.

`mtcars %>% filter(cyl == 4) %>% count(mpg)`

should end up like:

```
mtcars %>% 
   filter(cyl == 4) %>% 
   count(mpg)
```

**Comment by ronblum** [comment]
@jzadra Thank you for the suggestion. According to [the Tidyverse Style Guide](https://style.tidyverse.org/pipes.html#whitespace), pipes should usually be followed by a new line, so the request makes sense. We'll review this feature as we continue to develop RStudio.

**Comment by lorenzwalthert** [comment]
Until then, you can also use the R package [styler](https://github.com/r-lib/styler) that comes with an Addin for formatting, it implements this feature in its latest release, see also a discussion for it [here](https://github.com/r-lib/styler/issues/523).

**Comment by ronblum** [comment]
@lorenzwalthert Thank you for pointing this out!
