### ISSUE TITLE
Apply "Reformat Code" to ggplot() chains

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#5143]
Reformat code (Code > Reformat Code) does not currently act on ggplot chains.

`ggplot(mtcars, aes(wt, mpg)) + geom_point() + scale_x_continuous(limits=c(0,20)) + labs(x="Label")`

should end up like (both spread over multiple lines, and indented):

```
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  scale_x_continuous(limits=c(0,20)) +
  labs(x="Label")
```

**Comment by ronblum** [comment]
@jzadra I can't find a reference to this in [the Tidyverse Style Guide](https://style.tidyverse.org/), as in #5142, but this is the convention used starting in [the first appearance of ggplot in _R For Data Science_](https://r4ds.had.co.nz/data-visualisation.html#creating-a-ggplot)). We'll review this as we continue ongoing work on RStudio.
