### ISSUE TITLE
Bug: Scrollbar overlaps code editor and dialog windows

### ISSUE THREAD

**Issue by MarkErik** [rstudio/rstudio#5145]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1541
    OS Version      :  10.14.5
    R Version       :  3.6.0

### Describe the problem in detail

In the image below, there are two problems:
1. (The less obvious one, but actually quite troublesome when working on code). The last line of the file gets covered by the horizontal scroll bar, and there is no way to scroll past this. The only solution is to add blank lines after your last line of code, so that it pushes the actual code above the scroll bar.
2. The horizontal scroll bar covers dialog windows. (It seems to have a much higher Z-order than it likely should)

<img width="1271" alt="Screenshot 2019-07-26 at 1 14 55 PM" src="https://user-images.githubusercontent.com/23254168/61927691-4f38cd80-afa8-11e9-9bd9-f29a9924d5f1.png">

### Steps to reproduce the problem

Using Mouse on MacOS. Have also seen this issue on my laptop when I have enabled the setting in System Preferences - General - Show scroll bars - Always

### Describe the behavior you expected

Scroll bar doesn't overlap elements.

**Comment by BastiHz** [comment]
Regarding your first point: Did you try enabling the option "Allow scroll past end of document" in
Tools -> Global Options -> Code -> Display?

**Comment by MarkErik** [comment]
@BastiHz Thank you very much for your suggestion! I wasn't aware of that option, it lets me get around the first issue I reported - but I still think that it is a bit of a bug that the code is obscured by the scroll bar.

**Comment by kevinushey** [comment]
This appears to be fixed in v1.3; likely as a consequence of updating Qt. Unfortunately, not something we can backport.

**Comment by MarkErik** [comment]
Hi @dfalty not sure if this is to be fixed in the v1.2 patch you are referencing, I just wanted to share that I still encounter this in the latest 1.2 version.

I'm understand that it won't be fixed until 1.3 based on Kevins comment, however then I saw the v1.2 comment as well, and just wanted to share the issue from the most recent 1.2 version.

<img width="657" alt="Screenshot 2019-11-15 at 2 05 11 PM" src="https://user-images.githubusercontent.com/23254168/68920821-7dd5f080-07b1-11ea-9bcc-a9129bd11573.png">

**Comment by dfalty** [comment]
Hey @MarkErik sorry for the confusion. I just moved the milestone from 1.2 to 1.3 as this won't be fixed in 1.2 but is already fixed in the 1.3 builds. When or if you move over to 1.3 let us know if this is still occurring for you!

**Comment by rich-rstudio** [comment]
verified fixed in 1.3
