### ISSUE TITLE
Data viewer row-names column always sorts ascending

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#5146]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1555
    OS Version      : Windows 10
    R Version       : 6.1

### Steps to reproduce the problem

1. `View(mtcars)`
2. Click on the column with row names to sort them in descending order
3. Click on the column again to sort them in ascending order

### Describe the problem in detail

Nothing happens. The data remain sorted in an ascending order (by row number)

![image](https://user-images.githubusercontent.com/28725410/61861998-65be2680-aecd-11e9-82b5-145d8b2148cc.png)
![image](https://user-images.githubusercontent.com/28725410/61861964-4cb57580-aecd-11e9-8aeb-9e1917a30d43.png)

### Describe the behavior you expected

Sorting of the data based on the row number

**Comment by pascaloettli** [comment]
Related to #4468

**Comment by jmcphers** [comment]
And https://github.com/rstudio/rstudio/issues/4116.

**Comment by ronblum** [comment]
@BartJanvanRossum Thank for opening this issue, following from your original addition to #4116!
