### ISSUE TITLE
Keyboard shortcuts assigned to addins don't appear in the Show Customized panel

### ISSUE THREAD

**Issue by WilDoane** [rstudio/rstudio#5151]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.198
    OS Version      : MacOS 10.14.6
    R Version       : NA

### Steps to reproduce the problem
* Open the Modify Keyboard Shortcuts... dialog.
* Find an Addin item and assign a keyboard shortcut keystroke to it.
* Select the Show Customized panel. [Addin keystroke is listed]
* Close the Modify Keyboard Shortcuts... dialog.
* Open the Modify Keyboard Shortcuts... dialog.
* Select the Show Customized panel. [Addin keystroke is NOT listed]

### Describe the problem in detail
Once a keyboard shortcut key has been assigned to an addin item, revisiting the keyboard short cuts still lists the shortcut, but not on the Show Customized panel.`

### Describe the behavior you expected
All user-assigned keyboard shortcuts should always appear on the Show Customized panel.

**Comment by ronblum** [comment]
Reproduced in RStudio Desktop 1.2.1558 on MacOS 10.15. Note that workbench-scoped works, and if both workbench- and addin-scoped shortcuts are add, only the workbench one shows up in "Show Customized."
