### ISSUE TITLE
Since version 1.3.327, RStudio doesn't respect the pane layout and the appearance  

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#5153]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.327 and above
    OS Version      : Ubuntu 18.04.2
    R Version       : 3.6.1

**Preamble**: I understand RStudio v.1.3.z is intended for testing purposes

**1.3.326**
![Screenshot from 2019-07-29 16-59-12](https://user-images.githubusercontent.com/6613954/62031595-b6fa4d00-b222-11e9-90ec-38fbb1f0e797.png)

**1.3.327**
![Screenshot from 2019-07-29 16-56-20](https://user-images.githubusercontent.com/6613954/62031615-c1b4e200-b222-11e9-9a78-3f65da6c169b.png)

**Comment by jmcphers** [comment]
This is a known issue introduced by #5069; there's a new preference system and currently no migration.
