### ISSUE TITLE
Rstudio's version of install.packages doesn't deal with missing pkg arg as documented

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#5154]
The help for `?install.packages` decribes, in the `pkg` argument description : 

> If this is missing, a listbox of available packages is presented where possible in an interactive R session.

In fact running it with a missing argument triggers an error : 

    install.packages()
> Error in install.packages : argument "pkgs" is missing, with no default

What however doesn't trigger an error is calling install.packages on a zero length character : 

    install.packages(character(0))

With my rstudio version 1.1.463 with R 3.6.0 it just marks a pause and does nothing, with my colleague's same R studio but R 3.5.1 it triggers the behavior I would have expected with a missing argument, but not with a length zero argument (both installations are windows).

A character vector of length zero is what you get when you compute an empty `setdiff` or `intersection`, so it was very surprising to us to see something popup where we were expecting a vector of missing packages to be installed (or none if there was no missing package).

`utils::install.packages()` works as advertised.

I would prefer the Rstudio version to be consistent. If this is not acceptable, I believe a relevant help file should be shown.

**Comment by ronblum** [comment]
@moodymudskipper What environment are you running on? I definitely see failures, but not all of the successes and some different outputs, using RStudio Desktop, Server, and standalone R on MacOS and a couple of Linux environments. So I want to try and reproduce in the same configuration as you. Thanks!

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by moodymudskipper** [comment]
@ronblum Here is all of my info, copied from the console : 

```
> R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "3"

$minor
[1] "6.0"

$year
[1] "2019"

$month
[1] "04"

$day
[1] "26"

$`svn rev`
[1] "76424"

$language
[1] "R"

$version.string
[1] "R version 3.6.0 (2019-04-26)"

$nickname
[1] "Planting of a Tree"

> Sys.info()
       sysname        release        version       nodename        machine          login 
     "Windows"       "10 x64"  "build 17134" "BEZAV0L01105"       "x86-64"       "afabri" 
          user effective_user 
      "afabri"       "afabri" 
> RStudio.Version()
$citation

To cite RStudio in publications use:

  RStudio Team (2018). RStudio: Integrated Development for R. RStudio, Inc., Boston,
  MA URL http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, Inc.},
    address = {Boston, MA},
    year = {2018},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.2.1335’

> install.packages()
Error in install.packages : argument "pkgs" is missing, with no default
> system.time(install.packages(character(0)))
   user  system elapsed 
   2.07    0.58    2.68 
```

And with the last command no popup is shown

**Comment by ronblum** [comment]
@moodymudskipper Thank you for the info! We can use all this as we review the issue as part of our ongoing development of RStudio.

**Comment by moodymudskipper** [comment]
Thanks for the good work
