### ISSUE TITLE
jsonrpc errors related to terminal metadata

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5157]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.336
    OS Version      : macOS 10.14.6
    R Version       : 3.5.3

### Steps to reproduce the problem
Start IDE, create one or more terminals in the terminal tab. Switch back to Console.

### Describe the problem in detail
See one or more of these error messages:
```
29 Jul 2019 23:41:26 [rsession-gary] ERROR jsonrpc error 9 (Parameter type mismatch) [description=Invalid type for optional param shell_type]; OCCURRED AT: core::Error rstudio::core::json::getOptionalParam(const rstudio::core::json::Object &, const std::string &, const T &, T *) [T = int] /Users/admin/workspace/IDE/macos-v1.3/src/cpp/core/include/core/json/JsonRpc.hpp:422; LOGGED FROM: static boost::shared_ptr<ConsoleProcessInfo> rstudio::session::console_process::ConsoleProcessInfo::fromJson(const core::json::Object &) /Users/admin/workspace/IDE/macos-v1.3/src/cpp/session/SessionConsoleProcessInfo.cpp:299
```
### Describe the behavior you expected
No error messages. Presumably related to the new prefs switchover?

**Comment by jmcphers** [comment]
I can't repro this. :-/ However the error's pretty helpful (may be able to figure out what's going on based on that alone)

**Comment by gtritchie** [comment]
Not at computer at the moment but wonder if changing terminal shell to custom (and maybe back) is involved in repro.
