### ISSUE TITLE
JavaScript exception w/ error_handler_changed event

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5165]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.dev
    OS Version      : macOS 10.14.6
    R Version       : 3.6.1

---

Looks like `event.getData()` returns a JavaScript object of the form `{ type: "traceback" }` but the client-side code expects a simple String.

<img width="701" alt="Screen Shot 2019-07-31 at 10 50 55 AM" src="https://user-images.githubusercontent.com/1976582/62235121-18383280-b381-11e9-935b-734df560a50b.png">
<img width="233" alt="Screen Shot 2019-07-31 at 10 50 47 AM" src="https://user-images.githubusercontent.com/1976582/62235122-18383280-b381-11e9-9a50-f653aea5b39d.png">

**Comment by jmcphers** [comment]
I can't repro this locally -- do you have steps that trigger it?

**Comment by jmcphers** [comment]
(just for QA, really; it's clear enough what's going on here!)

**Comment by kevinushey** [comment]
In my case, I saw this when launching a dev. build of RStudio whenever the IDE was initialized -- I'm not sure what the specific repro steps are as I can't reproduce with the latest daily builds.
