### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/rstudio#5168]
This feature request appeared originally in this RStudio community thread: https://community.rstudio.com/t/ide-feature-request-rfc-command-palette/4402

I really love addins but you only have to install a handful before the 'Addins' drop down menu becomes a over-long and a drag to use. (:drum:)

A user's only option around this is to assign an addin to a key combination directly, but if we look in Tools -> Modify Keyboard Shortcuts we observe that RStudio already has many more commands than are featured in the default keymap. Key-bindings in R-Studio are a scarce commodity.

The way that other editors (E.g. Atom, Sublime, VSCode) deal with this situation is the 'Command Palette' -
A kind of command search box. VSCode's amazing extension ecosystem is facilitated in no small by part by its slick command palette, see: [Visual Studio Code Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette). I would really love to see this feature in RStudio.

Related to #3447 in that it may make that enhancement obsolete.

**Comment by njtierney** [comment]
I would LOVE this - this would feel so slick and make Rstudio feel even more awesome.

**Comment by hlynurhallgrims** [comment]
This would be so welcome. I just wanted to voice my support for this!

**Comment by ronblum** [comment]
@MilesMcBain Thank you for filing this Community request. Looks like it's pretty popular—30 minutes and already 9 thumbs up! I'll mark it as an enhancement, and the 👍s are noted.

Note: when reviewing, we should review the original [Community thread](https://community.rstudio.com/t/ide-feature-request-rfc-command-palette/4402).

**Comment by humanfactors** [comment]
This is a must. I frequently forget there isn't one and search for the binding for a command palette.

Further, Emacs mode bindings is simply just not Emacs if we don't have `M-x` also.

**Comment by jannikbuhr** [comment]
This would also be great for new users, as it allows the discovery of new features and shortcuts.

Currently I have the hotkey for the command palette in VS code bound to RStudios addin browser, which works great but only for anything made by other people, not RStudio itself.

**Comment by verajosemanuel** [comment]
This is a killer feature any IDE should offer and solves a lot of usability issues.
In my opinion: deficient emacs mode support  and accessibility issues with addins

**Comment by dcomtois** [comment]
That would be really really neat. As more and more RStudio functionalities are added, I too often find myself searching for the right menu entry or keyboard shortcut. Having a small textbox similar to the one for "Go to file/function", for instance, which would bring up the searched-for menu entry would boost productivity!
