### ISSUE TITLE
RStudio View() only displays 50 columns

### ISSUE THREAD

**Issue by balmajos** [rstudio/rstudio#5170]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.1335-1 Build 6 (7b3e38af)
    OS Version      :  

Desktop - Windows 10 Enterprise; 
Server -                                                            
sysname   "Linux"               
release: "3.10.0-514.el7.x86_64" 
version: "#1 SMP Wed Oct 19 11:24:13 EDT 2016"

R Version       :  Tested on R 3.5.1 and R 3.6.1

### Steps to reproduce the problem
View(matrix(rnorm(52),nrow=52,ncol=52))

### Describe the problem in detail
View(your_data_frame) only displays first 50 columns of a data.frame
Still displays all rows. Did not see anything in release notes regarding this being intended behavior.

### Describe the behavior you expected
Display all data from data.frame

**Comment by ronblum** [comment]
@balmajos Thank you for filing the issue. The data viewer only displays up to 50 columns at a time. However, you can view columns higher than 50 by clicking on the arrows that appear next to "Filter":

<img width="206" alt="col_nums" src="https://user-images.githubusercontent.com/31009952/62311726-6ec56f80-b45a-11e9-9163-bc0053723787.png">

You can then scroll to the right to see the higher-numbered columns.

I'll close the issue for now, but if there's still a problem, please let us know!

**Comment by alecloudenback** [comment]
Hello,

I think this might be an issue for the way we normally explore data. For example, we'll often be looking at a ~200 column dataset. We'll filter on a column and then want to go over and view the data that's on another page, but the filter gets wiped. Is there a way to do this or another suggested workflow?

**Comment by moodymudskipper** [comment]
I agree with the above tha filters should not be removed.

I also find the option to display more columns hard to find (and I hadn't even looked, because it really felt it displayed all there was, so I was surprised not to find my columns), could we maybe have an arrow next to the rightmost column name ? Or an evocative label ?

**Comment by astraetech** [comment]
I have 1.3 - 18 mln obs and 400+ columns. Navigating with 50 columns at a time is a huge pain especially when the rows reset to 1 with every new 50 column set. SAS Enterprise Guide browser is much much much faster and without 50 col limitations. Strange as it sounds but RStudio is a hard sell in my department because of these issues. I have to save the data to csv and import into SAS to do any meaningful visual data analysis.

**Comment by amw208** [comment]
Like above commenters, I find the navigation to columns after 50 challenging and inefficient. An older version of R Studio I had (Version 1.1.456) let me freely scroll to all columns in the data set. Would it be possible to add this as a Global Option so people can choose?

**Comment by morganBaCT** [comment]
I also need to be able to see all at once, and the > arrows do nothing for me. THe way I view/visually check for things means I need to see everything at once. Can you add an option to allow for everything to be viewed? At this rate I'll have to switch back to the old version of RStudio, which is not a good solution as until this is fixed I'll never be able to upgrade

**Comment by morganBaCT** [comment]
@jmcphers you are the best! Do I need to run that each time I open R? Or just once?

**Comment by jmcphers** [comment]
Just once. It's saved to your settings file so it should be the new default in every subsequent R session.

**Comment by erzakiev** [comment]
@jmcphers Awesome solution, thanks! 

Can I have now the column name to be always displayed on the left of the viewer pane when I scroll right through the columns?

**Comment by jmcphers** [comment]
No, but that's a common feature request (feel free to find and upvote!)

**Comment by ronblum** [comment]
@erzakiev and @jmcphers Just to clarify—this is actually to freeze the column with the row names, is this correct? Is this the same as request #3463?

**Comment by jmcphers** [comment]
@ronblum Yes that's the one!

**Comment by avay-risal** [comment]
I had the same problem, When I tried to set max column to 1000 with your code it gave following error:

Error in loadNamespace(x) : there is no package called ‘rstudioapi’

**Comment by kkwoo** [comment]
@avay-risal , I needed to install the rstudioapi package before I could run ```rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)```. Issue either ```install.packages("rstudioapi")``` or ```renv::install("rstudioapi")``` if you have an renv-based project.

**Comment by jxu** [comment]
@jmcphers Your solution still works on RStudio 2024.04.0.

It's a wonder that this option isn't exposed to users, because clearly there is demand for it. It could even have a warning about slowing down or crashing the user has to accept before modifying.
