### ISSUE TITLE
Javascript exceptions showing package:base in Environment pane

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5181]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.1565 (and 1.2.1555 and 1.3 builds, but not 1.1.463)
    OS Version      : macOS
    R Version       : 3.6.0

### Steps to reproduce the problem
- IDE, with Environment pane selected, and package:base selected
- close and reopen session, or just Session / Restart R

### Describe the problem in detail
Bunch of Javascript exceptions thrown by Environment pane. Haven't noticed any specific problems as a result.

Marking as 1.2-patch because I couldn't repro in 1.1. Not sure it's serious enough to warrant a 1.2-patch fix.

In a server dev build, easy to see this at the console where running rserver-dev. In desktop build, may show up in IDE Console (at least for a 1.3 build). You can also Inspect dev tools and tell it to pause on caught exceptions to see these happening.

### Describe the behavior you expected
No exceptions.

Here's snippet of output copied from 1.3.346 desktop Console pane (same pattern repeats dozens maybe hundreds of times for various Row indexes (but not all of them).

```
05 Aug 2019 21:12:08 [rsession-gary] CLIENT EXCEPTION (rsession-gary): Row index: 1184, Row size: 1229;
rstudio-0.js#-1::new Dld
com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds
com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement
com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement
org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#156::lambda$0
org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#156::execute
com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks
com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands
com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute
com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute
com/google/gwt/core/client/impl/Impl.java#306::apply
com/google/gwt/core/client/impl/Impl.java#345::entry0
rstudio-0.js#-1::eval
com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap
Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e
User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
```

**Comment by jmcphers** [comment]
It'd be nice to fix these but I've seen them intermittently for a long time and we don't have any evidence of actual misbehavior, so doesn't warrant churning 1.2-patch. (If we fix it in 1.3 and it turns out to be very safe, backporting might be worthwhile).

**Comment by kevinushey** [comment]
See also: https://github.com/rstudio/rstudio/issues/3056

**Comment by rich-rstudio** [comment]
@kevinushey not sure if this is related but when trying to produce this issue I get a bunch of errors in the dev console after restarting the R session (MacOS open source, Version 1.3.910)
<img width="1165" alt="Screen Shot 2020-03-13 at 4 16 32 PM" src="https://user-images.githubusercontent.com/43964690/76660113-291b6a00-6546-11ea-910c-a43419cffeec.png">

**Comment by kevinushey** [comment]
Those are expected -- they're typically seen after restarting an R session, and it just indicates that the browser was briefly unable to connect to the R session for that duration.

**Comment by rich-rstudio** [comment]
sounds good!
