### ISSUE TITLE
getpeereid - not found

### ISSUE THREAD

**Issue by skoestlmeier** [rstudio/rstudio#5185]
### Problem

I try to build RStudio Desktop from source and `cmake` reports the error:

    -- Looking for getpeereid
    -- Looking for getpeereid - not found

### System details
Tried on both

    RStudio Edition : Desktop
    RStudio Version : current master-branch
    OS Version      : Debian 9.8 (x86_64), kernel: 4.9.0-8-amd64
    R Version       : 3.6.0 (Planting of a Tree), x86_64-redhat-linux-gnu (64-bit)

and

    RStudio Edition : Desktop
    RStudio Version : current master-branch
    OS Version      : Fedora 30, kernel: 5.1.20-300.fc30.x86_64
    R Version       : 3.6.0 (Planting of a Tree), x86_64-redhat-linux-gnu (64-bit)

### Steps to reproduce the problem

1.  Download and unzip current master-branch in home directory
2.  Switch directory and install dependencies:
    `$ cd /home/user/rstudio-master/dependencies/linux/`
    `$ ./install-dependencies-debian` (Fedora: `$ ./install-dependencies-yum`)

3. `$ cd ../../`
    `$ mkdir build`
    `$ cd build`
4. `$ cmake .. -DRSTUDIO_TARGET=Desktop -DCMAKE_BUILD_TYPE=Release` or `$ ~/rstudio-master/package/linux/make-package Desktop DEB`

These steps exactly follow the INSTALL documentary in top of the RStudio master-branch or are described [here](https://github.com/rstudio/rstudio/issues/4421#issuecomment-470984287).

**Comment by ronblum** [comment]
@skoestlmeier Thank you for reporting this issue. I found some old similar discussions, regarding building from source that results in the same errors (among others). At the risk of sending you on a wild goose chase, perhaps one of them provides useful information?
- https://support.rstudio.com/hc/en-us/community/posts/200665427-CMake-Error 
- https://support.rstudio.com/hc/en-us/community/posts/200924493-cmake-hangs-after-Looking-for-setresuid-found-
- https://support.rstudio.com/hc/en-us/community/posts/205875498-cmake-error-with-Rstudio-0-99-486

**Comment by jmcphers** [comment]
We haven't been able to reproduce this and haven't had an update in a few months, so closing. You might want to try compiling in one of our Docker images:

https://github.com/rstudio/rstudio/wiki/Building-with-Docker

**Comment by bergen288** [comment]
@ronblum 
I got the same ```Looking for getpeereid - not found``` error.  I registered https://support.rstudio.com/hc/en-us website, but I can't access to any of your 3 links.   Would you mind to post them here?

Thanks.
