### ISSUE TITLE
RStudio keeps changing code in my RMarkdown document

### ISSUE THREAD

**Issue by bearloga** [rstudio/rstudio#5191]
I first noticed it when the document wasn't knitting due to problems with the chunk specification. I'd see parts of the chunk options shifted around (left right, up down) even though I remember writing everything correctly! I couldn't believe what I was seeing, it's like the IDE was *haunted*. I've quit and restarted RStudio several times and it keeps picking random chunks to mess with, and now it's messing with the R code inside those chunks

I finally managed to screen capture this cyberdemonic possession in action: https://youtu.be/iniaUcTyTNM

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1335
    OS Version      : macOS Mojave 10.14.6 (18G87)
    R Version       : 3.6.0

### Steps to reproduce the problem

I'm attaching the self-contained RMarkdown file because maybe there's something about it specifically that brighter minds than mine will be able to notice.

Dependencies used in document (for knitting):

```R
install.packages(c(
  "distill", "zeallot", "purrr", "tidyr", "dplyr",
  "ggplot2", "remotes", "hrbrthemes",
  "brms", "bridgesampling"
))
remotes::install_github("thomasp85/patchwork")
```

The R code in question: [index.Rmd.gz](https://github.com/rstudio/rstudio/files/3482093/index.Rmd.gz)

A diagnostics report: [diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3482147/diagnostics-report.txt)

I fully accept that this may be happening exclusively on my machine and that others won't have any problems opening and knitting the attached Rmd doc multiple times.

**Comment by bearloga** [comment]
I restarted my computer and the problem seems to have disappeared??? This is wild. Okay, I'll close for now but might re-open if it re-appears. ¯\_(ツ)_/¯

**Comment by bearloga** [comment]
Nope, it's back to picking random lines to mangle whenever I save:

<pre>
```{r p1}
p1 <- ggplot(simulated_test_statistics, aes(x = p)) +
  geom_histogram(aes(fill = model), bins = 30) +
  geom_vline(xintercept = mean(y), size = 1.1) +
  facet_wrap(~ model, scales = "free_y", ncol = 2)
```

```{r plot1, echo=FALSE, layout="l-body-outset", fig.width=14, fig.height=14}
p1 +
  hrbrthemes::theme_ipsum(base_size = 14, base_family = "Source Sans Pro") +
  scale_fill_brewer(palette = "Set1") +
  theme(legend.position = "bottom") +
  labs(x = "Test statistic: proportion of y=1", y = "# of simulations", fill = "Model",
       title = "Posterior predictive check histograms")
```
</pre>

became

<pre>
```{r p1}
p1 <- ggplot(simulated_test_statistics, aes(x = p)) +
  geom_histogram(aes(fill = model), bins = 30) +
  geom_vline(xintercept = mean(y), size = 1.1) +
  facet_wrap(~ model, scales = "free_y"), ncol = 2
```

```{r plot1, echo=FALSE, layout="l-body-outset", fig.width=14, fig.height=714
p1 +
  hrbrthemes::theme_ipsum(base_size = 14, base_family = "Source Sans Pro") +
  scale_fill_brewer(palette = "Set1") +
  theme(legend.position = "bottom") +
  labs(x = "Test statistic: proportion of y=1", y = "# of simulations", fill = "Model",
       title = "Posterior predictive check histograms")
```
</pre>

That's not even the worst I've seen. I've seen

<pre>
```{r plot1, echo=FALSE}
</pre>

become

<pre>
```{r eplot1 cho=FALSE
}
</pre>

**Comment by kevinushey** [comment]
One hypothesis: certain multibyte characters (e.g. emojis) can confuse RStudio in weird ways. Do you have something like that in the document? If so, does the issue still reproduce if you remove it?

**Comment by ronblum** [comment]
@kevinushey Ah! You're correct.

@bearloga Line 140, "For more information" etc., has one in it.

**Comment by bearloga** [comment]
@kevinushey Yup, removing the emoji from that line seemed to have fixed it! Thank you, that's so interesting that it would have such an effect.

**Comment by ronblum** [comment]
This is also being tracked in issue #1701, so I'm marking it as a duplicate.
