### ISSUE TITLE
Add indication of character count to git commit message box

### ISSUE THREAD

**Issue by k-doering-NOAA** [rstudio/rstudio#5192]
I often use the git pane and git "review changes" window  within the Rstudio IDE to stage code, type a commit message, and commit. I try to keep my commit message title to under 80 characters so it is easy to view, therefore, I would like to see some indication of character count while typing (perhaps like the line number and character count in line in the bottom left hand corner of an open script in the Rstudio IDE) to ensure that my commit message title is not over 80 characters.

**Comment by ronblum** [comment]
@k-doering-NOAA That's a neat idea—thank you for suggesting it! We'll review it as we continue development of RStudio.

**Comment by k-doering-NOAA** [comment]
Thanks for considering this!
