### ISSUE TITLE
Old output file shouldn't be opened if knitting fails

### ISSUE THREAD

**Issue by mirh** [rstudio/rstudio#5197]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 7
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Open a R markdown document
2. Make sure to have set "preview in window" setting
3. Write some proper code, have it rendering once
4. Break it somehow, run the thing again
(I can at least confirm this for when pdflatex fails, not sure about other sub-components or if it might not be more general)

### Describe the problem in detail
Log may be red and all, and clearly show there was a problem.. Still, if there's an older output you are shown it. 
And this is a total killer for an absent-minded user, which may instead think his changes aren't having any effect at all. 

### Describe the behavior you expected
Not saying Rstudio should clean old outputs before every re-run (even though, I don't know, I don't exclude it could make sense at least in some situations), but at least make sure preview doesn't run if there was an error.

**Comment by ronblum** [comment]
@mirh Thank you for the suggestion! Comparable behavior is if "Preview in Viewer Pane" is set, and the Rmd file is knitted to HTML: the displayed output is for the most recent document that was successfully generated, so a more recent failure isn't reflected there. We'll review this proposed change as we continue development of RStudio.

**Comment by mirh** [comment]
With HTML I didn't have this problem with "preview in window" either. 
This might be because: 
* I hardly can think of a way that I would manage to break pandoc-html, but not R/markdown itself to begin with
* this issue is just strictly about the "latex layer"

In both cases anyway, it seems like something requires attention.

**Comment by ronblum** [comment]
@mirh I'm thinking of something trivial, like adding an object that hasn't been defined. For example, after opening a new file, in the default document change
````
```{r cars}
summary(cars)
````
to
````
```{r cars}
summary(cars)
x
```
````
which will cause execution to halt with
````
Error in eval(expr, envir, enclos) : object 'x' not found
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
````
On the one hand, you know that the knitting failed because this error is displayed, which is sufficient to let us know about the failure. At the same time though, the window still has the previously rendered document.

**Comment by mirh** [comment]
Yes, that exception happens on the rmarkdown layer though. 
And it doesn't cause problems in both pdf and html output. 

....
I just did some further test then, and "break it somehow" doesn't cut it seemingly. 
So, what always work badly is:
```
    ---
    output: pdf_document
    header-includes:
       - \usepackage{svg}
    ---
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    options(tinytex.engine_args = '-shell-escape')
    ```
    ![](void.svg)
```
If there's a pdf already sitting in the project folder, it will be opened (it's not important for the image to exist at all, but have the right package installed at least)

Otherwise, you can get another glimpse of the problem with
```
![hello](actually_existing_image_but_with_some_àccènts.png)
```
Html will come out of course (because as I was saying, I'm not sure what are its limitations compared to markdown), but latex will burn in fire. And there actually will be a pdf generated in this scenario, but it's gonna be corrupted.. And even though it's definitively not gonna confuse people, it still shouldn't get to be opened automatically.

**Comment by mirh** [comment]
Alternatively, for the first of the two scenarios, even just specifying a ~~unsupported~~ "wrong" fontsize (e.g. 14 pt with KOMA classes) should do it.
