### ISSUE TITLE
User can be logged out while in the middle of a file upload

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#5202]
Repro steps:

1. Set a low auth timeout in rserver.conf: `auth-timeout-minutes=1`
2. Upload a very large file in a session
3. Notice that during the file upload, you will be redirected to the sign in page, and your file upload will be aborted.

Expected behavior:

You should not be logged out while actively uploading a file.

**Comment by rich-rstudio** [comment]
verified on Version 1.3.926
