### ISSUE TITLE
Feature request: Remove default source file keyboard shortcut

### ISSUE THREAD

**Issue by ABWerks** [rstudio/rstudio#5212]
Hi all, would you consider removing the default CMD/CTRL+Shift+Enter keyboard shortcut to source the current script? I realize this can be changed in the Tools menu, but whenever I have to rebuild my RStudio profile and forget to change this setting It causes much grief. Best, AJB

**Comment by ronblum** [comment]
@ABWerks Thank you for filing the request—I'm sorry for the grief that this is causing! However, keyboard shortcuts are a key component of accessibility. This allows users to do the majority of their work without relying on the mouse by default. It's especially important, then, to include keyboard shortcuts for the most common critical tasks, such as executing code.
