### ISSUE TITLE
Support autocompletion for inline chunks in Rmd files

### ISSUE THREAD

**Issue by atusy** [rstudio/rstudio#5213]
Currently, autocompletion works in chunks but not in inline-chunks for Rmd files.
It would be helpful if RStudio supports autocompletions for nline-chunks.

Thanks.

**Comment by ronblum** [comment]
@atusy Thank you for reporting this. Could you please provide sample code so that we can try to reproduce the scenario you're describing?

**Comment by atusy** [comment]
When I want `paste` function in an inline chunk, I start to type like

```
`r pas`
```

and then, I press tab to call suggested functions and select one to complete following:

```
`r paste()`
```

However, it is not working.

If it is within normal chunk typing

````
```{r}
pas
```
````

and pressing tab shows `paste` and  `paste0` as candidates, and I can select one to complete

````
```{r}
paste()
```
