### ISSUE TITLE
jobs and View() with name parameter

### ISSUE THREAD

**Issue by ahcyip** [rstudio/rstudio#5214]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 10 Home
    R Version       : 3.5.1

### Steps to reproduce the problem
When I run a job with a script that contains View(df, "data frame x"), the job fails, saying View doesn't accept extra arguments.

### Describe the problem in detail
I think this is because RStudio uses its own version of View that allows us to give View a name for the new window, but Jobs is doing something different. 

### Describe the behavior you expected
Can RStudio look out for this (RStudio-specific functions/commands?) and prevent the job from running?

**Comment by ronblum** [comment]
@ahcyip Thank you for raising the issue. I'm trying to reproduce the error you're seeing, but I haven't been able to. Can you please provide the following information?
1. The full details about the environment you are working in:

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

2. An example of code that could be used to reproduce the problem?

**Comment by ahcyip** [comment]
Hi, I'm now unable to reproduce this so I'll close this for now.
