### ISSUE TITLE
YAML argument to make set output_format = 'all'

### ISSUE THREAD

**Issue by RichardJActon** [rstudio/rstudio#5215]
Would it be possible to add a YAML argument to set `output_format = 'all'` for `rmarkdown::render()` when you click knit or press Ctrl + Shift + k

Instead of adding something like this to your YAML: 

```
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "output", output_format = "all") })
```

From: https://stackoverflow.com/a/53280491/1870254

---

I initially opened this in `knitr` it was suggested it belonged here: https://github.com/yihui/knitr/issues/1736

issue #2152 Is related but seems to be about a dialogue box to do this, as I understand it that dialogue just edits the YAML anyway however there does not seem to be a YAML option to do this yet.

---

See also: https://stackoverflow.com/questions/44685485/specifying-multiple-simultaneous-output-formats-in-knitr-new and issue https://github.com/yihui/knitr/issues/1051

**Comment by ronblum** [comment]
@RichardJActon Thank you for the suggestion! We'll review it as we continue development of RStudio.

**Comment by mafw** [comment]
Any progress on this?
