### ISSUE TITLE
[Feature Request] Separate subject from body in git window

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#5219]
The current `git` window does not allow for a clean separation of the subject and body. As an added benefit, it would be nice to have a count of what is 50 characters / 72 character blocks. Potentially, this could be done by greying out text exceeding these character limits.

The use case is to improve the `git` commits being made using de facto standards adopted by the open source community, c.f. <https://chris.beams.io/posts/git-commit>.

Current implementation:

<img width="398" alt="Screen Shot 2019-08-12 at 10 50 28 AM" src="https://user-images.githubusercontent.com/833642/62878609-05ade980-bcef-11e9-8910-6a0d192d0c9e.png">

Desired (from GitHub Desktop):

<img width="338" alt="Screen Shot 2019-08-12 at 10 44 44 AM" src="https://user-images.githubusercontent.com/833642/62878610-05ade980-bcef-11e9-9640-b612900edff6.png">

**Comment by jmcphers** [comment]
Will be partially addressed by https://github.com/rstudio/rstudio/pull/5207.
