### ISSUE TITLE
Add SQL style comment with `comment line` command in SQL code chunk 

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#5226]
As of RStudio 1.2, comment line feature doesn't work in SQL code chunk of RMarkdown or R notebook.

It'll be better to have the comment line(ctrl_shift_C) apply/unapply SQL comments in SQL code.

**Comment by ronblum** [comment]
@dracodoc Thank you for filing the enhancement request first raised in the original issue!

**Comment by abalter** [comment]
@ronblum -- has this been addressed? It's pretty annoying, and makes me not want to use SQL chunks.

**Comment by abalter** [comment]
@ronblum, for the record, other than MongoDB, which uses "$", ALL of the other major SQL flavors support

- Single line comments with `--`
- Multi-line comments with `/*....*/`


[Add SQL style comment with `comment line` command in SQL code chunk · Issue #5226 · rstudio/rstudio](https://github.com/rstudio/rstudio/issues/5226)

[Comments](https://docs.oracle.com/cd/B13789_01/server.101/b10759/sql_elements006.htm)

[SQL Comment Syntax](https://www.sqlite.org/lang_comment.html)

[$comment — MongoDB Manual](https://www.mongodb.com/docs/v5.0/reference/operator/meta/comment/)

[MySQL :: MySQL 8.0 Reference Manual :: 9.7 Comments](https://dev.mysql.com/doc/refman/8.0/en/comments.html)

[Transact-SQL Syntax Conventions (Transact-SQL) - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?view=sql-server-ver16)

[-- (Comment) (Transact-SQL) - SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/comment-transact-sql?view=sql-server-ver16)

[PostgreSQL: Documentation: 8.0: SQL Syntax](https://www.postgresql.org/docs/8.0/sql-syntax.html#SQL-SYNTAX-COMMENTS)

**Comment by kevinushey** [comment]
For reference, the requisite code changes would be around here: https://github.com/rstudio/rstudio/blob/13fb29fd72fef81466661137f5e31b194c9b6082/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L4310-L4324

**Comment by mgastner** [comment]
I agree that it would be highly useful if the keyboard shortcut for commenting (Shift + C + Command on Mac or Control on Windows and Linux) were available for SQL scripts or Quarto SQL code chunks. Is there a way for users to add this functionality on their own, for example, using the 'Modify Keyboard Shortcuts' menu?

**Comment by abalter** [comment]
@kevinushey --- Imma take a shot at adding a clause for `else if (fileType_.isSql())` and building. I'll submit a pull request if it works.
