### ISSUE TITLE
Environment pane does not show dataframe structure

### ISSUE THREAD

**Issue by phubers** [rstudio/rstudio#5235]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 10
    R Version       : 3.6.1

### Steps to reproduce the problem

I cannot consistently reproduce the problem, although large dataframes (several 100k rows) exhibit the problem frequently.

### Describe the problem in detail

Some dataframes do not show the "details" arrow in the environment pane. Usually this happens with larger dataframe. It can happen when loading a large csv file, in other cases it happens after some manipulation of the dataframe.

Hovering the mouse over the area where the unfold arrow should be visible will change the mouse pointer to a hand, indicating that a link should be there. However, clicking does not do anything. 
The dataframe can be normally viewed in the viewer by clicking on the object name, but the structure of the columns (identified variable types etc) will not be visible.

Attached is a screen shot of the pane with three dataframes, of which two have no "unfold arrow" to reveal the structure, but the smaller dataframe can be inspected in the usual way.

### Describe the behavior you expected

I expected the pane to show the blue arrow button for all loaded dataframes.

![rstudio_bugreport_environment_pane](https://user-images.githubusercontent.com/604688/63008539-1b541800-be83-11e9-9fcb-7208e99b3854.png)
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3500585/diagnostics-report.txt)

**Comment by jmcphers** [comment]
This has been fixed in our preview release (see https://github.com/rstudio/rstudio/issues/4758). You can pick up a build here:

https://www.rstudio.com/products/rstudio/download/preview/
