### ISSUE TITLE
macOS: Multiple R versions installed can lead to library errors

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5238]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.371-1
    OS Version      : MacOS 10.14.6
    R Version       : 3.6

### Steps to reproduce the problem

(speculative)

1. Install R 3.5
2. Install some R packages
3. Install R 3.6
4. Load some packages

### Describe the problem in detail

`libR.dylib` is not loaded correctly.

```
> library(tidyverse)
Error: package or namespace load failed for 'tidyverse' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/glue/libs/glue.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/glue/libs/glue.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/glue/libs/glue.so
  Reason: image not found
```

### Describe the behavior you expected

Package library and R versions should match.

This is very likely a regression from this commit:

https://github.com/rstudio/rstudio/commit/898be825dcafba039c1df4d7253d413e311e2047

Which in turn derives from this one:

https://github.com/rstudio/rstudio/commit/2350236246dde5e43cec33513c4cba88c2e9b7ef

We have a difficult situation here:

1. If we do not use `install_name_tool`, and leave the `libR.dylib` file path intact, then RStudio will load the version of R it was built against if present, even if it's not the current version of R. See https://github.com/rstudio/rstudio/issues/2313 for results.
2. If we change the path to `@executable_path/libR.dylib`, then the R session will crash on start with the hardened runtime enabled (which is required for notarization), as it considers a failure to load a library a critical issue.
3. If we change the path to `Versions/Current` (as we currently do), we have the bug described above.

**Comment by blairj09** [comment]
I'm still seeing this error with RStudio Pro Version 1.3.425-1 and R 3.6.1

**Comment by ronblum** [comment]
@blairj09 just kindly tried it out on RStudio Desktop 1.2.1578-2 and the issue occurs there, as well.

**Comment by kevinushey** [comment]
Can we confirm that the issue does not occur in the current v1.2 release? I'm very surprised the issue is still occurring.

**Comment by blairj09** [comment]
Confirmed. This does not occur in the current 1.2 release (1.2.1335)

**Comment by ronblum** [comment]
Reopening, as @tobiasgerstenberg has run into this issue with RStudio Desktop 1.2.5001 on Mojave.

**Comment by ronblum** [comment]
@tobiasgerstenberg How did you install the different versions of R? E.g., using the `.pkg` installers, compiled from source, etc.? Any information will be helpful in trying to reliably reproduce this.

**Comment by tobiasgerstenberg** [comment]
I installed the different versions via `.pkg` installers. I may have installed some earlier versions of R via homebrew. I have the following versions in `/Library/Frameworks/R.framework/Versions/`

```
3.1
3.2
3.3
3.5
3.6
```

**Comment by tobiasgerstenberg** [comment]
In my case, the error seems to have been caused by packages having been compiled with different versions of R.

I had a set my library path library path in `~/.Renviron` as

```
R_LIBS=/usr/local/lib/R/site-library 
```

and didn't update this between different versions of R, resulting in a mix in which some packages were compiled under 3.5 whereas others were compiled under 3.6 

Removing the library path in `~/.Renviron` and re-installing all packages resolved the issue.

**Comment by nahorp** [comment]
Hello, I'm having a similar problem (not with `libR.dylib` but `libgfortran.5.dylib`)

I'm having trouble loading `lme4` (as well as some other packages such as `glmmTMB`, all with the same error messages). The error message is as below,

    Loading required package: Matrix
    Error: package or namespace load failed for ‘lme4’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/statmod/libs/statmod.so':
      dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/statmod/libs/statmod.so, 6): Library not loaded: /usr/local/gfortran/lib/libgfortran.5.dylib
      Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/statmod/libs/statmod.so
      Reason: image not found

My `sessionInfo()` is as below as well,

    R version 3.6.2 (2019-12-12)
    Platform: x86_64-apple-darwin15.6.0 (64-bit)
    Running under: macOS Catalina 10.15.3
    
    Matrix products: default
    BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
    
    locale:
    [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] Matrix_1.2-18
    
    loaded via a namespace (and not attached):
    [1] compiler_3.6.2  tools_3.6.2     splines_3.6.2   grid_3.6.2      packrat_0.5.0   lattice_0.20-40

It was all working fine and then all of sudden this happened, I'm not even sure why or how. Would really appreciate any help!
