### ISSUE TITLE
Spelling: URLs in code comments are being spelled-checked

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#5242]
Create an Rmd with the following code:

``````
```{r}
pin("http://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_master.csv")
```
``````

Run spell-check, the URL seems to be being spelled checked in multiple keywords, is this expected?

<img width="744" alt="Screen Shot 2019-08-15 at 11 06 50 AM" src="https://user-images.githubusercontent.com/3478847/63115801-e3b1a280-bf4c-11e9-81c0-5b9638b3ce76.png">

**Comment by rich-rstudio** [comment]
@adamconroy I was able to reproduce this on Server Open Source Version 1.3.888 (Ubuntu)
<img width="920" alt="Screen Shot 2020-03-12 at 10 08 28 AM" src="https://user-images.githubusercontent.com/43964690/76535809-79f96880-6449-11ea-891d-aa1925223f97.png">

**Comment by rich-rstudio** [comment]
verified on Server Version 1.3.938
