### ISSUE TITLE
Connections pane toolbar is missing in recent daily builds

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#5244]
Open RStudio and the connections pane... toolbar is missing:

<img width="1156" alt="Screen Shot 2019-08-15 at 11 52 53 AM" src="https://user-images.githubusercontent.com/3478847/63118866-9b49b300-bf53-11e9-93de-d87103977bab.png">

**Comment by kfeinauer** [comment]
@jmcphers Maybe more fallout from the prefs commit?
