### ISSUE TITLE
Do not spell check non-prose parts of markdown files

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#5255]
Portions of Rmd files that are currently being spellchecked that shouldn't be:

- Code chunks (comments are ok, this may not be possible to split due to how parsing works)
- Headers
- anything in `\ref{*}` -- references
- anything of the form `@*` and `[@*]` -- citations
- filepaths in `![alt text](*)` -- figures, alt text should be checked but the path shouldn’t be

Currently the tokenizer is fairly naive in regards to only grabbing items that are given the "text" attribute. Some of these items may be a bit tricky with the current tokenizer so we will have to see what is viable.

**Comment by ronblum** [comment]
Verified with the following. 
````
---
title: "Spelly"
output: html_document
---

# Body
I am missspelled and should be checked

# Ignore code in code chunks
```{r}
# I am missspelled and should be checked
x <- "I am missspelled and should by ignored"
```

# Ignore headers
## I am missspelled and should be ignored

# Ignore anything in \ref{*}
\ref{I am missspelled and should be ignored}

# Ignore anything of the form @* and [@*]
@missspelled{I am missspelled and should be ignored}
[@missspelled{I am missspelled and should be ignored}]

# Ignore filepaths in ![alt text](*)
![I am missspelled and should be ignored](http://I.am.missspelled.and.should.be.ignored)
![I am missspelled and should be ignored](/I/am/also/missspelled/and/should/be/ignored)


# Note: Some of currently-ignored text might be checked in the future
````
