### ISSUE TITLE
Missed syntax error:  assignment to nothing

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#5257]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1565
    OS Version      : MacOS 10.13.6
    R Version       : 3.6.1

### Steps to reproduce the problem

Enter this code in the source pane for an R file:

```
x <- -1
for (i in 1:10) {
  x
  <- i
}
```

### Describe the problem in detail

Note that the 4th line, which is a syntax error, is not flagged as one.

### Describe the behavior you expected

It should have been flagged as a syntax error with a red X in the gutter.

**Comment by kevinushey** [comment]
Patch would likely be required here:

https://github.com/rstudio/rstudio/blob/32e64f2f3d8be8b9c333f82099af3aa21d507de1/src/cpp/session/modules/SessionRParser.cpp#L2354-L2380

The `<-` is treated as a binary operator (e.g. as though `x <- 1` was written); the end-of-statement following the standalone `x` is not properly detected.
