### ISSUE TITLE
SQL preview throws error with more than 99 columns

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5265]
**Steps to reproduce:**
* Add some SQL connection.
* Open an SQL preview tab on that connection (through the "SQL" button in the `Connections` pane).
* Write a query that would throw 100 or more columns, e.g.
```sql
select * from the_table
select col1, col2, ..., col100 from the_table
etc.
```
* Click the "Preview" button in the SQL preview tab where this query is being written.

**Expected results:** should show the usual data viewer with the first 99 columns on the "SQL Results" tab.

**Actual results:** throws an error with title bar `Error Previewing SQL` and message `missing value where TRUE/FALSE needed`.

**Setup:** RStudio 1.2.1568, R 3.5.3, running on windows 10, trying to connect to PostgreSQL.

The problem is not present when previewing some table with 100+ columns by clicking the table icon next to them in the `Connections` pane (in that case it's shown as a regular data viewer tab in the same pane as the source files, instead of in an `SQL Results` tab in the same pane as the console).

**Comment by ronblum** [comment]
@david-cortes Thank you as always for raising the issue. I am able to reproduce this with RStudio Server 1.2.1568 on Red Hat 8 with R 3.5.3.

For QA purposes: sample test data with
`x <- data.frame(t(1:101))`

**Comment by rich-rstudio** [comment]
verified in Server 1.3.888
