### ISSUE TITLE
Embed R studio iframe

### ISSUE THREAD

**Issue by sundar1195** [rstudio/rstudio#5272]
While Embed R studio in an iframe i am getting some error in firebug **(Invalid 'X-Frame-Options' header encountered when loading 'http://rstudio-local.com:60018/auth-sign-in': 'ALLOW-FROM http://172.17.1.59/xyz/' is not a recognized directive. The header will be ignored.)** but iframe loads without any problem.
x-frame-option: deny which was changed to  x-frame-option: ALLOW-FROM http://172.17.1.59/xyz/

by including www-frame-origin=http://172.17.1.59/xyz/ to /etc/rstudio/rserver.conf.

I want to why i am getting the error in firebug.

**Comment by ronblum** [comment]
@sundar1195 Unfortunately, we do not support Firebug, which is discontinued. The list of supported browsers is listed at the bottom of https://www.rstudio.com/about/platform-support. Are you able to try it out with one of those? Some sources, such as https://www.ostraining.com/blog/general/firebug-has-been-discontinued, suggest Firefox DevTools as an option. How does that, or one of the other supported browser, work out?

**Comment by jmcphers** [comment]
Your version of Firefox would also be helpful. I'm guessing you are using an older version; `X-Frame-Options: ALLOW-FROM` was added in Firefox 18.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
