### ISSUE TITLE
Recent Windows update / "R Studio" will not launch

### ISSUE THREAD

**Issue by KirkMSaylor** [rstudio/rstudio#5275]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by KirkMSaylor** [comment]
Microsoft Windows just recently pushed out a major update (within last week). Since that update, it appears that "R Studio" will not launch / run. Have attempted uninstalling and reinstalling both "R" and "R Studio" (most recent version) and attempting to launch by using the "run as administrator" option. Nothing happens. I would appreciate any direction from the community on troubleshooting.

**Comment by gtritchie** [comment]
Hi, sorry to hear about this problem. 

Please fill in the information requested in the issue template, including the RStudio Version, R Version, and the specific version of Windows. For Windows-10, please include the version and build numbers, as there are many different "versions" of Windows-10. Get this via Windows Key+R, type `winver` in the Open box, the click Ok.

For example, my laptop has Windows-10 version 1903, build 18362.295.

I'm not aware of a widespread problem running RStudio after the latest round of Windows-updates, so you might want to post a question in the RStudio community, instead: https://community.rstudio.com/c/rstudio-ide

**Comment by jmcphers** [comment]
Closing since we don't have a repro or more info (and it's been a few months). @KirkMSaylor Feel free to reopen with the details @gtritchie describes if you're still having trouble!
