### ISSUE TITLE
Error running r studio with source code from github 

### ISSUE THREAD

**Issue by sundar1195** [rstudio/rstudio#5278]
Hi folks,
I am getting the below error while trying to run rstudio locally.

administrator@administrator-desktop:~/Documents/rstudio/v6rstudio/rstudio/build$ cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=ReleaseCMake Error at /usr/local/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  src/cpp/CMakeLists.txt:240 (find_package)

CMake Error at /usr/local/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  src/cpp/CMakeLists.txt:244 (find_package)

-- Using Boost.Signals version 2
-- No Crashpad libraries found under /opt/rstudio-tools/crashpad/crashpad/out/Default/obj. Crashpad integration disabled.
CMake Error at cmake/modules/FindPAM.cmake:72 (message):
  PAM was not found
Call Stack (most recent call first):
  src/cpp/core/CMakeLists.txt:224 (find_package)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/ext
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/ext
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/ext
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/ext
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/ext
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/ext
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/spelling/hunspell
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/spelling/hunspell
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/spelling/hunspell
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/spelling/hunspell
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/spelling/hunspell
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/spelling/hunspell
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/spelling/hunspell
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/tex/synctex
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/tex/synctex
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/tex/synctex
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/tex/synctex
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/tex/synctex
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/tex/synctex
   used as include directory in directory /home/administrator/Documents/rstudio/v6rstudio/rstudio/src/cpp/core/tex/synctex

-- Configuring incomplete, errors occurred!
See also "/home/administrator/Documents/rstudio/v6rstudio/rstudio/build/CMakeFiles/CMakeOutput.log".
See also "/home/administrator/Documents/rstudio/v6rstudio/rstudio/build/CMakeFiles/CMakeError.log".

**Comment by ronblum** [comment]
This looks like it's part of the same process/issue as in #5277.
