### ISSUE TITLE
Request: recover multi-line statements from history in one piece

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5281]
If I write a command in the console breaking it into several lines through `Shift` + `Enter`, execute it (by pressing `Enter`), and then execute some other command, then when I go to the `History` pane and try to retrieve the multi-line statement by double-clicking it on the history, it will only re-create the exact line that was double-clicked, even though it was executed as a single statement.

It's still possible to recover it by selecting all the lines corresponding to the statement (in the history) and then clicking the button `To Console`, but would be nice if it could recover whole multi-line commands as one line.

**Comment by ronblum** [comment]
@david-cortes If I recall from a previous conversation (which I can't find, alas), there's a reason for this. However, I'll mark it as an enhancement for now.
