### ISSUE TITLE
Packages pane filter: show only loaded packages

### ISSUE THREAD

**Issue by francisbarton** [rstudio/rstudio#5287]
Hi
Couldn't find an existing feature request for this: #2435 is close, and a resolution to that would satisfy me! But anyway...

I would like a way of filtering the package list in the Packages pane so that it would just show the packages currently loaded. Just a tick box would do, or a kind of code to enter in the search box like ":loaded" or something like that.

It's helpful to me to look and see what is currently loaded.

[`(.packages())`](https://tolstoy.newcastle.edu.au/R/help/03a/4444.html) does the same thing from the console but a filter in the Packages pane would be more useful as an simple, ongoing way of looking to see what is loaded.

Thanks!

**Comment by ronblum** [comment]
@francisbarton  Thank you for the suggestion! We'll review it as we continue to develop RStudio.

Currently:
<img width="705" alt="all_packages" src="https://user-images.githubusercontent.com/31009952/63601683-eb4bf980-c593-11e9-9faf-0bc5ef3e591b.png">

It would be useful to also have something like:
<img width="692" alt="loaded_packages" src="https://user-images.githubusercontent.com/31009952/63601691-eedf8080-c593-11e9-9944-f5166fa12a83.png">

**Comment by francisbarton** [comment]
Hmmm, I still feel like this would be a really useful feature. Going to comment here now to just to keep it alive for a second chance at inclusion.
