### ISSUE TITLE
Rmd chunk output moves "inside" chunk when using `cc` in Vim mode

### ISSUE THREAD

**Issue by jmberros** [rstudio/rstudio#5288]
Editing an Rmd chunk with a plot output, if you use `cc` in Vim mode to edit _the last line of the chunk_, then the plot moves "inside" the chunk, i.e. it moves above the three backticks.

Before editing the last line:

![Screenshot from 2019-08-23 14-23-22](https://user-images.githubusercontent.com/1233486/63611143-9a4afe00-c5b1-11e9-9e11-d5760bfab995.png)

After editing the last line with `cc` in Vim mode, the plot is "inside" the chunk (notice the three bottom backticks):

![Screenshot from 2019-08-23 14-23-07](https://user-images.githubusercontent.com/1233486/63611141-9919d100-c5b1-11e9-9951-05880d48aecd.png)

**Comment by ronblum** [comment]
@jmberros Thank you for raising the issue.  We will review it as we continue development of RStudio.

Reproduced this in RStudio Desktop 1.1.463 and 1.2.1571 on MacOS 10.15 (Catalina) and RStudio Server 1.2.1568 on Red Hat 8 using Google Chrome.

**Comment by jmcphers** [comment]
There's a bug in the implementation of `cc` in the vim keybindings, which I think is addressed in the daily builds (which have a newer version of the Ace editor). Would you be willing to see if the problem reproduces there?

https://dailies.rstudio.com/

**Comment by ronblum** [comment]
It's still an issue in 1.3.397.
