### ISSUE TITLE
Open recent project in new session

### ISSUE THREAD

**Issue by iqis** [rstudio/rstudio#5289]
It is desirable to be able to directly open a recent project in a new session. 

Currently the use must do: 
  - File => Open Project in New Session => use the file explorer to select the desired project, or 
  - Session => New Session => Recent Projects

**Comment by jmcphers** [comment]
If you click the project switcher in the upper right, it should do what you want:

![image](https://user-images.githubusercontent.com/470418/63621588-2efd2e00-c5a9-11e9-8ee7-4c0e6b08e670.png)

**Comment by iqis** [comment]
@jmcphers Thanks!! Spending 10+ hours daily facing the UI of RStudio, I didn't even realize this thing was there!
