### ISSUE TITLE
Clean all Viewer items with R restart

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#5299]
Would it be possible to automatically clean all the items in the Viewer pane when restarting R inside RStudio?

**Comment by jmcphers** [comment]
Can you provide some more background re: why this would be useful?

**Comment by pascaloettli** [comment]
@jmcphers Well, because it makes sense, at least to me, to clean everything when I restart a session. Why would the Plot pane be cleaned and not the Viewer pane?

**Comment by ronblum** [comment]
I just tried this out by sending the output of a few Rmd files to the Viewer, then restarting R, and the Viewer pane gets cleared out. @pascaloettli Can you provide information about how to get it to not clear out?

Tested with RStudio Desktop 1.2.5001 on MacOS 10.15 and RStudio Server 1.2.5001 on Ubuntu 18.04.

**Comment by pascaloettli** [comment]
@ronblum  Sure. Here it is (from `formattable` help)

```
library(formattable)
formattable(mtcars,
            list(mpg = formatter("span", style = "color:red")))
```

Then <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F10</kbd> to restart R

**Comment by ronblum** [comment]
@pascaloettli Thanks! I can reproduce this with the `formattable`. Yet knitting an R Markdown file works fine.

**Comment by ronblum** [comment]
@pascaloettli Thanks! I can reproduce this with the formattable. Yet knitting an R Markdown file works fine.

@jmcphers I imagine that the behavior should be consistent in the Viewer pane, regardless of what's in it?

**Comment by jmcphers** [comment]
No, this behavior is by design. Some things in the viewer pane are specific to the R session (i.e. they refer to content in the R session's temp folder), so they have to go away when the session restarts. However, when the viewer pane contains durable content (i.e. a file created by knitting that isn't bound to a specific session), it persists after a restart.
