### ISSUE TITLE
Detect when roxygen2 isn't installed and install it when "Build->Document" is pressed

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/rstudio#5300]
Problem: If `roxygen2` isn't installed, and the "Document" button is pressed in the Build panel, it drops an error message to the build console.

Suggestion: RStudio IDE knows `roxygen2` is a required package for the "Document" button, similar to how it knows `rmarkdown` is a requirement for RMarkdown documents, `shiny` is a requirement for Shiny applications, etc. The package installation interface used for these packages is helpful for new users who may not be accustomed to `install.packages()`.

Therefore, I suggest RStudio IDE takes the user to a dialog that asks them if they'd like to install `roxygen2`, and if so, pulls up the package installation dialog.

**Comment by dfalty** [comment]
Verified fixed 1.3.867
