### ISSUE TITLE
R Markdown - Select text and convert to chunk with ctrl-alt-i

### ISSUE THREAD

**Issue by Emmanuel-R8** [rstudio/rstudio#5304]
After selecting some text, typing for example " or ( will surround the text accordingly.

The same behaviour with ctrl-alt-i would be efficient.

Current behaviour: ctrl-alt-i inserts an empty chunk below selected text. 

Proposed behaviour: ctrl-alt-i creates a new chunk surrounding the selected text.

**Comment by GegznaV** [comment]
You can achieve this by using RStudio add-ins and assigning the desired keyboard shortcut :

1) package `addins.rmd`: https://gegznav.github.io/addins.rmd/#create-r-code-chunks
2) package `remedy`: https://github.com/ThinkR-open/remedy#chunk

**Comment by Emmanuel-R8** [comment]
Thanks. ThinkR/remedy with a few dedicated keyboard shortcuts is perfect.
