### ISSUE TITLE
Surround selection not fully disabled for rmarkdown files

### ISSUE THREAD

**Issue by pitakakariki** [rstudio/rstudio#5305]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 10
    R Version       : 3.6.0

### Describe the problem in detail

I have "Surround selection on text insertion" set to "Never". When editing an .Rmd file this works as intended for quotes and brackets, but still surrounds my selection when I use an asterisk or an underscore.

**Comment by dfalty** [comment]
Verified fixed 1.3.867
