### ISSUE TITLE
openSUSE tumbleweed wayland session

### ISSUE THREAD

**Issue by gerhardriener** [rstudio/rstudio#5317]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1527
    OS Version      :  opensuse tumbleweed
    R Version       :  3.6.1

### Steps to reproduce the problem

Download Rstudio rpm from rstudio.com
install
start rstudio

### Describe the problem in detail
Apprarently rstudio tries to call a method that is not allowed on wayland:
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

### Describe the behavior you expected
rstudio opening
<!-- Depending on the problem, the following may also be helpful

output when calling rstudio
/usr/lib/rstudio/bin/rstudio
Failed to load client buffer integration: wayland-egl

WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")
Could not create a shell surface object.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

**Comment by ronblum** [comment]
@gerhardriener Thank you for raising this. We don't support openSUSE Tumbleweed, unfortunately, only Leap. In addition we don't currently support Wayland. However, I've opened up issue #5333 to support Wayland in the future.
