### ISSUE TITLE
Logic for detecting headings in document outline could be streamlined/generalized?

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#5318]
<img width="121" alt="Screenshot 2019-08-30 at 12 45 52 AM" src="https://user-images.githubusercontent.com/7606389/63959850-bb36b600-cabf-11e9-9972-439cb5f7485a.png">

In [`data.table/R/data.table`](https://github.com/Rdatatable/data.table/blob/master/R/data.table.R), the Document Outline pane looks a bit wonky (see screenshot)

Two things:

```
          if (length(allbyvars)) {    ###############  TO DO  TO DO  TO DO  ###############
```

A section heading is detected based on consecutive `###` even though it's a line-end comment (regex could be anchored with `^#`? or `^\s*#`?)

``` ###########################################################################
  # Grouping ...
  ###########################################################################
```

This is detected as two Untitled section headings, instead of one section titled `Grouping...`. It's clear at a glance what's going on but it may be complicated to amend the logic here since it requires processing 3 lines at once instead of line-by-line. But FWIW I do often mark sections out like this.

Thanks as always!

**Comment by kevinushey** [comment]
> A section heading is detected based on consecutive ### even though it's a line-end comment (regex could be anchored with ^#? or ^\s*#?)

This seems sensible to me. There is still some worry that some users do indeed rely on section headers of this form; e.g. someone might have something like:

```
if (case.1) {   # Case One ----
```

and expect that section header to be rendered.

> This is detected as two Untitled section headings, instead of one section titled Grouping.... It's clear at a glance what's going on but it may be complicated to amend the logic here since it requires processing 3 lines at once instead of line-by-line. But FWIW I do often mark sections out like this.

The main challenge here is that some users do want unnamed / empty sections, and use a long comment string to accomplish exactly that.

**Comment by MichaelChirico** [comment]
> There is still some worry that some users do indeed rely on section headers of this form; e.g. someone might have something like:

Fair. Of course easily changed to

```
# Case One ----
if (case.1) {
```

But any breaking change needs to be considered more carefully.

> The main challenge here is that some users do want unnamed / empty sections, and use a long comment string to accomplish exactly that.

Understood, and that can continue to be valid -- my hope is for the detector to be more "contextually aware"

```
##########
f = function(...)
````

vs

```
#############
# UTILITIES #
#############
```

`#############` alone is untitled, but `#############` in the local context of being near other `#############` can be "smarter"

**Comment by kevinushey** [comment]
> Understood, and that can continue to be valid -- my hope is for the detector to be more "contextually aware"

This part is challenging as the tokenizer used in RStudio runs line-by-line, and so doing look-ahead or look-behind in this form is more challenging to tool for.

**Comment by MichaelChirico** [comment]
I figured as much... worth having in mind anyway!
