### ISSUE TITLE
Roxygen2 keywords are marked as spelling errors

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5319]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.399
    OS Version      : macOS

### Steps to reproduce the problem

Picture says it all:

![image](https://user-images.githubusercontent.com/470418/63961007-9b15e100-ca44-11e9-9c62-6d9f5a78a9d3.png)

### Describe the problem in detail

The R package roxygen2 has special keywords like `@seealso` which shouldn't be marked as spelling errors. Almost all R package code (and some robustly commented R code) uses this standard for documentation. 

### Describe the behavior you expected

No spelling errors.

There are three ways we could fix this:

1. Remove any word beginning with `@` from the list of words to be checked, or
2. Whitelist roxygen2's keywords, which are all listed (in various places) in https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html, in our auxiliary dictionary.

**Comment by adamconroy** [comment]
Since we are marking these tokens with ace keywords this was just a quick fix. https://github.com/rstudio/rstudio/commit/842f66f853950db222dedf39e5b65ec060975799
