### ISSUE TITLE
Terminal buffer grows when moving console left / right

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5320]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1572
    OS Version      : macOS 10.14.6
    R Version       : 3.6.0

### Steps to reproduce the problem
- create a new terminal
- `seq 1 5`
- move console pane to opposite location, e.g. View / Panes / Console on Right

### Describe the problem in detail
Contents of terminal buffer are duplicated. If move back again, grows even more.

![2019-08-29_10-37-52](https://user-images.githubusercontent.com/10569626/63963285-8c7df880-ca49-11e9-9071-7bcfea89bbba.png)

![2019-08-29_10-38-13](https://user-images.githubusercontent.com/10569626/63963295-91db4300-ca49-11e9-8018-eb3211d89233.png)

### Describe the behavior you expected

Shouldn't do that.

Couldn't repro in 1.1.463, so a regression in 1.2.

**Comment by ronblum** [comment]
@gtritchie FWIW, I can't reproduce this on RStudio Server 1.2.1568 on Red Hat 8 via Chrome. (I haven't tried Desktop on Windows or Linux.)

**Comment by gtritchie** [comment]
Fixed by https://github.com/rstudio/rstudio/pull/5341
