### ISSUE TITLE
File can't be named using directory path when importing dataset with "text (base)"

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5323]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.1568
    OS Version      : Linux
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Save a delimited text file—CSV, tab delimited, etc.—on the user's file system
2. In the IDE: File -> Import Dataset -> From text (base)
3. In  the "File name" field, enter the full path of the file, including the file name, e.g. `/home/rstudio/cars.csv`
4. Click on "Open"

### Describe the problem in detail

Three things happen:
1) A model pops up, stating "R code execution error"
2) Clicking "OK" on the modal takes you to the "Import Dataset" window, but it has the relative directory name when the file name belongs, e.g. `rstudio` instead of `cars.csv`
3) In the console, the following errors appear:
```
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In file(con, "r") :
  'raw = FALSE' but '/home/rstudio' is not a regular file
2: In file(con, "r") : cannot open file '/home/rstudio': it is a directory
> 
```

### Describe the behavior you expected

Two options:
1) The correct file should be prepared for import; or
2) The "File Name" field in step (3) above should not be editable, and the file can only be chosen using the file explorer. However, I don't think this is a good solution, because if the current working directory is under the user's home directory, the topmost directory that can be reached is the home directory. Going to the rest of the file system—say, `/tmp`—requires setting the working directory to something outside of the user's home directory.

[Ref. Support ticket 39248.]

**Comment by kevinushey** [comment]
IIUC this is server only, since the desktop file dialog doesn't give a way to select a file by path.

**Comment by kevinushey** [comment]
Did this work with v1.1 or v1.0?

**Comment by aaichsmn** [comment]
Works for 1.0.153 but the 'From text' options are not in that version.
