### ISSUE TITLE
Every other word in R source code is getting identified as misspelled

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5324]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.400
    OS Version      : MacOS 10.15 (Catalina)
    R Version       : 3.6.1

### Steps to reproduce the problem

In an R source file, enter the following:
```
Dear Johnn hii thhere and then some more and then some more
# Dear Johnn hii thhere
summary(cars) # Dear Johnn hii thhere
```

### Describe the problem in detail

Every other word in code is identified as misspelled.

<img width="525" alt="spellcheck_R" src="https://user-images.githubusercontent.com/31009952/63974905-ccf66a00-ca7b-11e9-8eec-4b564c75bcd3.png">

### Describe the behavior you expected

Code should not be evaluated for spelling.

Note that the comments are correctly getting identified, including proper names.

**Comment by adamconroy** [comment]
The red underlines are not the spell checker. ;)

**Comment by ronblum** [comment]
Oh right, that's what I get for writing really bad code.
