### ISSUE TITLE
Comments in chunks of R Markdown files are not getting spellchecked

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5325]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.400
    OS Version      : MacOS 10.15 (Catalina)
    R Version       : 3.6.1

### Steps to reproduce the problem

In an Rmd file, enter the following:
````
Dear Johnn hii thhere

```{r}
Dear Johnn hii thhere
```

```{bash}
Dear Johnn hii thhere
```

# Dear Johnn hii thhere

```{r}
# Dear Johnn hii thhere
summary(cars) # Dear Johnn hii thhere
```
````

### Describe the problem in detail

The comments in chunks are not getting spellchecked.

<img width="342" alt="spellcheck_Rmd" src="https://user-images.githubusercontent.com/31009952/63975355-d6cc9d00-ca7c-11e9-8e0b-dcc9cefadc5e.png">

### Describe the behavior you expected

All comments should be spellchecked.

Note that unlike #5324, code within the chunks is not getting checked (correct) and text outside of chunks is getting checked (correct).

**Comment by adamconroy** [comment]
https://github.com/rstudio/rstudio/commit/7ea18fc05ba2e203980d470e72ccb86e57104475
