### ISSUE TITLE
Turning off code diagnostics also disabled real time spellcheck

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5327]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.400
    OS Version      : MacOS 10.15 (Catalina)
    R Version       : 3.6.1

### Steps to reproduce the problem

1) Turn on real time spellcheck.
2) Tools -> Global Options -> Code -> Diagnostics
3) Uncheck the "Show Diagnostics" options.
4) In an R source file, enter the following:
```
Dear Johnn hii thhere and then some more and then some more
# Dear Johnn hii thhere
summary(cars) # Dear Johnn hii thhere
```
5) Save the file.

### Describe the problem in detail

None of the spelling errors in the comments get underlined.

### Describe the behavior you expected

If real time spellcheck is turned on, misspelled words should be underlined even if code diagnostics is turned off.

**Comment by jmcphers** [comment]
Nice find!

**Comment by adamconroy** [comment]
https://github.com/rstudio/rstudio/commit/ff5744ed0b007e39d940c688308e0e2b2ebfdeda luckily was a very simple fix!
