### ISSUE TITLE
Syntax highlighting for roxygen @field tag should be same as @param and @slot

### ISSUE THREAD

**Issue by dchiu911** [rstudio/rstudio#5330]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS High Sierra 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

![Screen Shot 2019-08-29 at 4 56 56 PM](https://user-images.githubusercontent.com/8665632/63984158-b0a7fc80-ca7e-11e9-94da-f68211d7d25c.png)

### Describe the problem in detail

The syntax highlighting for the Vibrant Ink theme does not differentiate between the `@field` name and its description.

### Describe the behavior you expected

The colours should be different as is for `@param` and `@slot`.

**Comment by ronblum** [comment]
@dchiu911 Thank you for raising the issue. I'll tag it as a bug for review as we continue to develop RStudio. And as reference point, according to https://cran.r-project.org/web/packages/roxygen2/news/news.html, `"@field` ... works the same way as `@slot` for S4 classes." So presumably, the behavior should be the same as with the `@slot` example you've provided. Thanks!

**Comment by kevinushey** [comment]
Here's where the relevant highlight rule lives:

https://github.com/rstudio/rstudio/blob/0df2ec80482d8450bd6516c726ed45296bf598f7/src/gwt/acesupport/acemode/r_highlight_rules.js#L59-L65

Adding `field` here might be sufficient.
