### ISSUE TITLE
Cursor over where I'm typing causes overwrite

### ISSUE THREAD

**Issue by RobertMyles** [rstudio/rstudio#5332]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1335 (Build 1351 (f1ac3452))
    OS Version      : Mac OS Mojave 10.14.6
    R Version       : R version 3.6.1 (2019-07-05)

### Steps to reproduce the problem
Place the cursor right over where you're about to type in the RStudio editor
### Describe the problem in detail
Instead of each new key being typed, the latest keystroke overwrites the previous. For example, if I'm on column 30 and I start typing "today", 'o' will overwrite 't', 'd' will overwrite 'o' and so on, and I will only see 'y' at the end. This is hard to reproduce but happens regularly, and only when then cursor has been placed right on top of where I'm about to type.
### Describe the behavior you expected
Normal typing.

**Comment by kevinushey** [comment]
I believe this has been fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) -- if you have time, would you mind downloading it and confirming if all appears well there?

**Comment by RobertMyles** [comment]
Will do, thanks.

**Comment by RobertMyles** [comment]
Can confirm that this no longer occurs after installing preview release.
