### ISSUE TITLE
Support RStudio on Wayland

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5333]
Support RStudio on Wayland for Linux desktop environments.

**Comment by mikebessuille** [comment]
This comes "for free" from the update we're doing to QT.  However, this will be considered "experimental support" for 1.4

**Comment by gtritchie** [comment]
Due to significant issues we've been hitting with our Qt 5.15 experiments, we're likely not doing this for 1.4 on Linux.

**Comment by the42** [comment]
Is this issue assumed to be solved by moving away from Qt Webengine to Electron? #8439

**Comment by mikebessuille** [comment]
Wayland should be supported "soon" by Electron:  https://www.reddit.com/r/linux/comments/iuerlb/electron_will_support_wayland_soon/

**Comment by rspreafico** [comment]
I see that Electron support is ~50% complete as of today with a target due date of Sept 30, 2021. Do you have a sense of whether RStudio will be ready to support Wayland thru Electron by the end of October, when Ubuntu 21.10 (defaulting to Wayland) will be released?

**Comment by MavropaliasG** [comment]
I get the following when trying to launch the package rstudio-bin (AUR) in Manjaro KDE (wayland 1.20.0)

```rstudio-bin 
Failed to load client buffer integration: wayland-egl

WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

```

My system

```
System:
  Host: alpha-nitroan51543 Kernel: 5.15.19-1-MANJARO x86_64 bits: 64
    compiler: gcc v: 11.1.0 Desktop: KDE Plasma 5.23.5 tk: Qt 5.15.2
    wm: kwin_wayland vt: 2 dm: SDDM Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Laptop System: Acer product: Nitro AN515-43 v: V1.08
    serial: <superuser required>
  Mobo: PK model: Octavia_PKS v: V1.08 serial: <superuser required>
    UEFI: Insyde v: 1.08 date: 12/24/2019
Battery:
  ID-1: BAT1 charge: 39.5 Wh (100.0%) condition: 39.5/58.8 Wh (67.3%)
    volts: 16.5 min: 15.4 model: Simplo 0x41,0x50,0x31,0x38,0x45,0x37,0x000E
    type: Li-ion serial: 000E status: Full
CPU:
  Info: quad core model: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    bits: 64 type: MT MCP smt: enabled arch: Zen/Zen+ note: check rev: 1 cache:
    L1: 384 KiB L2: 2 MiB L3: 4 MiB
  Speed (MHz): avg: 1895 high: 2306 min/max: 1400/2100 boost: enabled
    cores: 1: 1238 2: 1237 3: 2267 4: 1763 5: 2297 6: 2306 7: 1922 8: 2133
    bogomips: 33550
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Baffin [Radeon RX 460/560D / Pro
  450/455/460/555/555X/560/560X]
    vendor: Acer Incorporated ALI RX560X 4GB driver: amdgpu v: kernel
    bus-ID: 01:00.0 chip-ID: 1002:67ef class-ID: 0380
  Device-2: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile
  Series]
    vendor: Acer Incorporated ALI driver: amdgpu v: kernel bus-ID: 05:00.0
    chip-ID: 1002:15d8 class-ID: 0300
  Device-3: Quanta HD User Facing type: USB driver: uvcvideo bus-ID: 1-1:2
    chip-ID: 0408:a061 class-ID: 0e02
  Display: wayland server: X.Org 1.21.1.4 compositor: kwin_wayland driver:
    loaded: amdgpu,ati unloaded: modesetting alternate: fbdev,vesa resolution:
    1: 1920x1080~60Hz 2: 1920x1080~75Hz s-dpi: 96
  Message: Unable to show advanced data. Required tool glxinfo missing.
Audio:
  Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio
    vendor: Acer Incorporated ALI driver: snd_hda_intel v: kernel
    bus-ID: 05:00.1 chip-ID: 1002:15de class-ID: 0403
  Device-2: AMD Family 17h HD Audio vendor: Acer Incorporated ALI
    driver: snd_hda_intel v: kernel bus-ID: 05:00.6 chip-ID: 1022:15e3
    class-ID: 0403
  Sound Server-1: ALSA v: k5.15.19-1-MANJARO running: yes
  Sound Server-2: PulseAudio v: 15.0 running: no
  Sound Server-3: PipeWire v: 0.3.45 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Acer Incorporated ALI driver: r8169 v: kernel port: 2000
    bus-ID: 03:00.0 chip-ID: 10ec:8168 class-ID: 0200
  IF: enp3s0 state: down mac: 08:97:98:76:12:ef
  Device-2: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter
    vendor: Lite-On driver: ath10k_pci v: kernel bus-ID: 04:00.0
    chip-ID: 168c:003e class-ID: 0280
  IF: wlp4s0 state: up mac: e8:d0:fc:8a:ac:f1
Bluetooth:
  Device-1: Lite-On type: USB driver: btusb v: 0.8 bus-ID: 3-2:2
    chip-ID: 04ca:3016 class-ID: e001
  Report: rfkill ID: hci0 rfk-id: 2 state: up address: see --recommends
Drives:
  Local Storage: total: 476.94 GiB used: 430.94 GiB (90.4%)
  ID-1: /dev/nvme0n1 vendor: Western Digital
    model: PC SN520 SDAPNUW-512G-1114 size: 476.94 GiB speed: 15.8 Gb/s
    lanes: 2 type: SSD serial: 192534800789 rev: 20180000 temp: 44.9 C
    scheme: GPT
Partition:
  ID-1: / size: 468.16 GiB used: 430.94 GiB (92.1%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 299.4 MiB used: 280 KiB (0.1%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 14 GiB used: 0 KiB (0.0%) priority: -2
    file: /swapfile
Sensors:
  System Temperatures: cpu: N/A mobo: N/A
  Fan Speeds (RPM): N/A
  GPU: device: amdgpu temp: 58.0 C watts: 7.06 device: amdgpu temp: 75.0 C
Info:
  Processes: 321 Uptime: 14m wakeups: 1 Memory: 13.66 GiB
  used: 4.54 GiB (33.2%) Init: systemd v: 250 Compilers: gcc: 11.1.0
  clang: 13.0.0 Packages: 1907 pacman: 1898 flatpak: 9 Shell: Bash v: 5.1.16
  running-in: konsole inxi: 3.3.12

```

**Comment by sorenoneill** [comment]
Same issue on Kubuntu 21.10 with Wayland session

**Comment by kundex** [comment]
Same here on Arch/Manjaro with Wayland/Sway.

**Comment by ronblum** [comment]
A note on Electron: We are actively (very actively!) working on the Electron version of RStudio Desktop, which is targeted for June. This isn't a firm date, but we're working with this timeframe. We don't have preview versions of it yet, though.

**Comment by ishaanbhimwal** [comment]
> I get the following when trying to launch the package rstudio-bin (AUR) in Manjaro KDE (wayland 1.20.0)
> 
> ```
> Failed to load client buffer integration: wayland-egl
> 
> WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
> qt.qpa.wayland: No shell integration named "xdg-shell" found
> qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
> qt.qpa.wayland: No shell integration named "wl-shell" found
> qt.qpa.wayland: No shell integration named "ivi-shell" found
> qt.qpa.wayland: Loading shell integration failed.
> qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")
> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
> ```

Anyone getting this error can try the following:

```
export QT_QPA_PLATFORM=xcb
rstudio #if you are on arch or derivative then include "--no-sandbox" flag
```

**Comment by ODAncona** [comment]
I run ubuntu jammy jellyfish 22.04. And Rstudio freeze when launched:

![image](https://user-images.githubusercontent.com/71207824/165893930-8d833084-f877-473a-81af-daeae7ad6d95.png)

The only option so far is to run it from command line `rstudio --no-sandbox` with the flag or add `export RSTUDIO_CHROMIUM_ARGUMENTS="--no-sandbox"
`
to your .bashrc

After the application is launched I get

```
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/xdg/xdg-ubuntu:/etc/xdg/rstudio/logging.conf'. Logging to '/home/olivier/.local/share/rstudio/log/rdesktop.log'.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

Will rstudio support wayland via electron in June  @mikebessuille ?

**Comment by mikebessuille** [comment]
We're delivering a preview of our Electron build soon, by June.   You can try it out here: 
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/windows/
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/macos/
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/debian10/
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/rhel8/
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/bionic/
etc...

I would love to know if this resolves the problem for Wayland.  Please keep in mind, this is not yet in preview and we don't recommend you use it for real development , only for testing.  It's close, though.  Let me know how it goes.

**Comment by rcragun** [comment]
> I would love to know if this resolves the problem for Wayland. Please keep in mind, this is not yet in preview and we don't recommend you use it for real development , only for testing. It's close, though. Let me know how it goes.

What information do you want reported? Whether it runs on Wayland?

**Comment by rcragun** [comment]
An Electron build runs for me. System:

```
RStudio Edition : Desktop or Server
RStudio Version : 2022.07.0-preview+537
OS Version      : Ubuntu 22.04 (Gnome 42 on Wayland)
R Version       : 4.2.0
```

Not sure if either is relevant, but 

1. The text and icons are extremely blurry on my system with resolution 3840 x 2160 and fractional scaling at 250% (which is also true of every recent production release I have tried).
2. When running from the terminal, I get 
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[19529:0622/184015.800849:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is
```

**Comment by gtritchie** [comment]
@adamryczkowski

> I used rstudio-2022.07.0-preview-544-amd64.deb.

The messages above suggest you tried the Qt build, which is known not to support Wayland. Do you mind trying the Electron build? It should be considered experimental (it will eventually replace the Qt build, but not until a future release), but is getting close to fully functional.

Try downloading from https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/jammy/ (for Ubuntu 22).

**Comment by adamryczkowski** [comment]
I confirm data-studio seems to be working now. I was able to change the theme and set up a Fira Code font with working ligatures.

**Comment by mikebessuille** [comment]
Thanks for testing!

**Comment by Bulwagga** [comment]
I have the same problem running rstudio on Ubuntu 22.04 with Wayland.  The electron build works for me as well.  Thank you!

**Comment by MavropaliasG** [comment]
When can we get the electron build as a flatpack in Linux please?

**Comment by the42** [comment]
Reading https://github.com/rstudio/rstudio/wiki/Electron-Desktop

> RStudio Server/Workbench is used via a web browser pointed at the server; RStudio Desktop is displayed in what is essentially a custom Chromium-based web browser and local server in one. Currently this is built using QtWebEngine (the sources live in src/cpp/desktop).

> The Electron desktop (under development) replaces QtWebEngine with Electron. The sources live in src/node/desktop; it is written primarily in TypeScript.

So it's not yet there?

**Comment by MavropaliasG** [comment]
> > So it's not yet there?
> 
> RStudio Desktop has been using Electron starting with version 2022.12 (and newer). Not sure that's what you were asking, or if you meant Wayland support specifically.
> 
> FYI: RStudio Desktop Pro is still on QtWebEngine but the Electron version should be out this summer.

Is there a flatpak for Linux with the electron version? All I can find in the arch repositories and AUR are Qt builds

**Comment by the42** [comment]
@gtritchie I was specifically referring to Wayland support.

**Comment by gtritchie** [comment]
Yes, RStudio Desktop 2022.12 and newer support Wayland.

No, we don't produce a flatpack (see [#3079](https://github.com/rstudio/rstudio/issues/3079) for more on that saga).

As far as I'm aware, we (Posit) don't have anything to do with the RStudio IDE appearing in any package repositories. At this time the only thing Posit produces are the installable packages you can download from the website. Anything else out there was created by someone else (again, as far as I'm aware, I could be out of date on that knowledge).

**Comment by GerryT11** [comment]
I am running RStudio 2023.09.1 Build 494 on Ubuntu/.deb and noticed that RStudio is not running on Wayland, but rather XWayland. Are there any blocker issues to enable Wayland by default?
