### ISSUE TITLE
shiny app css will not refresh unless restart R session

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#5334]
I have a `styles.css` in `www` folder included in my shiny app. Sometimes after edits to the css file, the shiny app doesn't get the update. If I inspect the app html source and open the `styles.css`, an older version will be opened.

Restart R session will have this fixed. This can be super annoying as I thought my css rules was wrong and not taking effect.

R: 3.6.1
Windows 7
RStudio 1.2.1335

**Comment by ronblum** [comment]
@dracodoc Thank you for raising the issue. To help replicate the problem, can you please provide a reproducible example, such the Shiny app code with the `styles.css` you're using, or even a minimal example? Thanks!

**Comment by xhdong-umd** [comment]
Yes, I even wrote a rstudio addin to start shiny app in a new job which supposedly is independent and fresh, but that still is using same old version css.

It seem to be a low level cache not relevant to R session.

**Comment by jmcphers** [comment]
This is an issue with Shiny rather than RStudio. We could work around it in some circumstances but it's probably better to wait for the Shiny team to address it at the source. See: https://github.com/rstudio/shiny/issues/1142, https://github.com/rstudio/shiny/issues/2389.

**Comment by shahreyar-abeer** [comment]
Yes, I'm having the same issue.

**Comment by helgasoft** [comment]
This one has not gone away. And was **not** related to Shiny in my case.
I was using library [Echarts4r](https://github.com/JohnCoene/echarts4r) and my code has the following line:
```r
  dep <- htmltools::htmlDependency(name="echarts-renderers", version = "1.0.1", 
               src = c(href = 'http://localhost/TEST/js/'), script = "renderers2.js")
```
Happened in RStudio after updating the Javascript (_renderers2.js_) file. 
Viewer > Inspect Element > rstudio devtools > Source > .js file was showing older version.
Funny - tiny button "_show in new window_" opened same view in Chrome and displayed correctly.
Restarting R session fixes it and .js file shows latest version.
Using &nbsp; Win:10 &nbsp; &nbsp; R:v.4.0.3 &nbsp; &nbsp; RStudio: v.1.3.1093

**Comment by ChrKoenig** [comment]
I got confused many times by this issue. One workaround is to open the app in the browser and then force reload the page, e.g. with CTRL+F5 (Firefox & Chrome).

**Comment by GitHunter0** [comment]
> I got confused many times by this issue. One workaround is to open the app in the browser and then force reload the page, e.g. with CTRL+F5 (Firefox & Chrome).

You saved my life @ChrKoenig , thank you for the hint.

**Comment by thhaase** [comment]
add this on top while ur customizing and remove or comment it out when deploying

```{r}
library(renv)
refresh()
```
