### ISSUE TITLE
RStudio 1.2.X hangs occasionally (with anti-virus Trendmicro) 

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#5335]
I'm using the latest preview version RStudio in my office where the PCs must install an anti-virus software "Trendmicro". 

The issue is my RStudio IDE will consistently hang for 10-20 seconds. The frequency of the hanging is about every 10 - 20 minutes. Most of the hanging happens when the RStudio IDE is trying to make code completion (I think). 

I doubt it's because RStudio is somehow writing temporary (caches?) to the local disk. The anti-virus software will scan the new/modified file...

Not sure if there's anything you can do but I'm pretty sure this issue only happens in RStudio 1.2.X. There's no such issue for RStudio version 1.1.X or previous version.

(I'm confident that it's not specific to a sub-version of 1.2.X. Instead, all the 1.2.X version has this issue. I'm saying so because I've tried to use the preview version of RStudio every one or two months this year. Unluckily, I experienced the hanging in all the trials)

Thanks.

**Comment by ronblum** [comment]
@shrektan Thank you for raising this. Folks have run into issues before with other antivirus software, some of which is referenced at https://github.com/rstudio/rstudio/issues/5030#issuecomment-506733760 and one specific to Trendmicro: https://support.rstudio.com/hc/en-us/community/posts/208171047-rsession-exe-flagged-as-virus. I also found ticket #4368, which is currently targeted as a potential enhancement RStudio 1.3. Two things:
1) If I understand correctly, the issue is occurs despite the Git-related workaround in #4368, so likely unrelated to it?
2) Though you might not be able to control Trendmicro, is it possible for an administrator to add RStudio to an exclusion list?

Thanks!

**Comment by shrektan** [comment]
Thanks for your reply. 

1. I'm not sure if it's related to Git since it's a small project (no sub-modules) and it doesn't occur in 1.1.X version of RStudio. Anyway, I think I can turn-off Git and test to see if the issue will occur or not.

1. I tried one or two years ago when I had the issue similar to [this post you mention](https://support.rstudio.com/hc/en-us/community/posts/208171047-rsession-exe-flagged-as-virus). It's difficult and I solved that issue by using the signed version of RStudio instead of the previewed version at that time.

Anyway, if RStudio/Git needs to touch many files frequently, the anti-virsus is the No1 suspect. It's because in that case, the anti-virsus might treat the behavior as potential ransomware attacks...

So I will use RStudio 1.2.X without Git for a while to see if the issue solved or not and report back here.

**Comment by kevinushey** [comment]
One possibility is that the RStudio file monitor and antivirus are fighting over access to files in the project -- e.g. `.git/index.lock`, hence why we think removing or disabling Git might make a difference. (Of course, we'd like a more permanent solution than that but it'd be good to confirm if it is indeed caused by this mixture of git + an antivirus)

**Comment by shrektan** [comment]
I tried to turn off Git and found no hanging occurs so far. In addition, I just found my Windows Defender was somehow enabled. After I disabled the Windows Defender, the handing still occurs but only lasts one or two seconds, which was totally tolerable.

So seems Git & anti-virus is the cause. It seems if the frequency of Git's auto scan can be configured in RStudio, the hanging may be resolved even if the Windows Defender was enabled.

I'll try to use it for more days and report back to you then. 

Thanks for your kind help.

**Comment by ronblum** [comment]
@shrektan Thank you for doing the further investigation, and we look forward to hearing your report!

**Comment by shrektan** [comment]
Have tested "running RStudio 1.2.X with Git disabled" for a while on "the Windows 7 computer in the office with anti-virus software installed" :

1. Good: Yes, it's generally much faster, the hang doesn't occur that much and lasts only 1 ~ 2 secs if any. At least it's tolerable.

1. Bad: RStudio 1.2.X still hangs occasionally and it's somewhat slower than RStudio 1.1.X.

1. Bad: If the package contains C++ codes, it's awful. Basically, I need to restart the session every time after I change the source code. Or I can't save the file. This happens when the C++ source code is a little complicated, like containing template.    
     I need to mention that it happens on RStudio 1.1.X, too. However, it's not that much. I have disabled diagnose and changed the code completion to "manually" but the issue still happens.

My guess is that both Git and the code detecting/analyzing in RStudio leads to this issue. I think it should help on this issue if we can:

1. Trigger Git scan manually instead of automatically,

1. Trigger the underlying code analyzing manually (I think even with "manually trigger code completion + turn off dignose" there's some stuff running in the background automatically) or "don't let the background stuff *lock* the file".

**Comment by kevinushey** [comment]
> 1. Trigger Git scan manually instead of automatically,
>
> 2. Trigger the underlying code analyzing manually (I think even with "manually trigger code completion + turn off dignose" there's some stuff running in the background automatically) or "don't let the background stuff lock the file".

These both sound like reasonable feature requests to me.

**Comment by jmcphers** [comment]
The git scan issue is tracked in https://github.com/rstudio/rstudio/issues/4368. Code analysis would be helpful too, but I'm moving that out of 1.3.

**Comment by boshek** [comment]
Thank you for working on this! Curious - did anyone submit this to Trend Micro whitelist? For those of us operating on machine without full admin privileges, this appears to be a persistent issue. The particular bind is for those are us experiencing this _and_ #5888 means we can't update to R 4.0.0 _if_ we want to use RStudio. Just trying to a chart a path forward.

**Comment by shrektan** [comment]
It's interesting that I just upgrade to R 4.0.0 with Windows 10 together (finally).  It seems no issue so far with Trend Micro and RStudio IDE is actually a little bit faster than before (3.6.3 + Windows 7)....

**Comment by shrektan** [comment]
Actually, I've been using RStudio 1.4.X + MicroTrend + Win10 for almost three weeks. Surprisingly, I find that the occasional hanging disappears, even when I set the Git Scan *automatically*. I don't know if any recent commits should take the credit for this. But the good news is, it's OK now.

So I'm going to close this issue.

Thanks for all your help!
