### ISSUE TITLE
"Suspend R Session" command showing up in desktop builds

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5337]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1577 (and 1.3 builds)
    OS Version      : Mac / Windows / Linux
    R Version       : Any

### Steps to reproduce the problem
* start desktop IDE, open Session menu

### Describe the problem in detail
* session menu includes the "Suspend R Session" command

### Describe the behavior you expected
* this command was only intended to appear in dev builds in RStudio 1.1, so unless we intentionally changed this in 1.2, it has mistakenly made its way into regular builds
* it doesn't seem to do anything
* doesn't appear in server builds, as expected

**Comment by dfalty** [comment]
Verified fixed 1.2.1578.
