### ISSUE TITLE
Ability to hide or move "Source on Save"

### ISSUE THREAD

**Issue by donboyd5** [rstudio/rstudio#5338]
Hi. Occasionally I accidentally click "Source on Save" when I am intending to click Save. RStudio then saves and sources the file I was working on, which I did not intend. If it happens in the middle of work that involved creating extensive data sets that took a lot of time, I may have to rerun all of those steps, which can be very time consuming.

It would be great to have the ability to customize the toolbar to hide this button or to move it elsewhere where I am unlikely to click it accidentally, so that people like me are able to protect themselves from this mistake.

Thanks for considering this.

**Comment by ronblum** [comment]
@donboyd5 Thank you for the suggestion! I suppose ultimately this could be a more generic request to customize the whole toolbar, but for now let's leave this request limited to "Source on save," which we'll review as we continue development of RStudio.

**Comment by ahcyip** [comment]
Was the source on save button removed in a recent version of RStudio? I'm not seeing it anymore (but I want it for some files)

**Comment by jmcphers** [comment]
It was not removed, but if you have any auto-save options turned on, then Source on Save gets disabled to avoid ambiguous/confusing mixes between the two. What do you have set under Options -> Code -> Saving?

**Comment by ahcyip** [comment]
thanks - yes, I did turn on auto-save. I guess I just like saving all the time.
