### ISSUE TITLE
Error message when knitting .Rmd document with matlib plot outputs

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#5342]
RStudio Edition : Desktop or Server 
    RStudio Version : 1.2.1335
    OS Version      : Ubuntu 18.04.3
    R Version       : 3.6.1

### Steps to reproduce the problem

```r
u = "https://github.com/Robinlovelace/movingpandas/raw/rmarkdown/0_getting_started.Rmd"
download.file(u, "py.Rmd")
file.edit("py.Rmd") # then click 'knit'
```

### Describe the problem in detail

Following the reproducible example above fails with the following error in the RMarkdown console:

```
Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50b02)
```

### Describe the behavior you expected

I would expect it to work. The following works (assuming you have the Python pre-requisites set-up):

```r
rmarkdown::render("py.Rmd", output_format = "github_document")
```

```
Preview created: py-test.html

Output created: py-test.md
```

I've not tried on the preview edition. Report in case others find this issue and in case it's of use/interest. Btw overall RStudio works really well with Python code, thanks guys!

**Comment by ronblum** [comment]
@Robinlovelace Thank you for raising this. However, I'm having trouble reproducing it, because `pip install` is returning errors for several packads:
```
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/movingpandas/
```
The packages not found are `movingpandas`, `os`, `urllib`, and `warnings`. Can you provide instructions for installing them? Thanks!

**Comment by Robinlovelace** [comment]
Good point.

Try this:

```
u = "https://github.com/anitagraser/movingpandas/archive/master.zip"
download.file(u, "py.zip")
unzip("py.zip")
setwd("movingpandas-master")
file.edit("0_getting_started.Rmd") # then click 'knit'
```

The Python modules that need to be installed are in [environment.yml](https://github.com/anitagraser/movingpandas/blob/master/environment.yml):

```
  - python=3.7
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - geopandas
  - contextily
  - descartes
```

**Comment by Robinlovelace** [comment]
+ heads-up @anitagraser, more crossover!

**Comment by Robinlovelace** [comment]
Good news, this is fixed!

Thanks Stale bot for nudging on this. This works:

```
---
title: "Untitled"
author: "Robin Lovelace"
date: "06/02/2021"
output: html_document
---

```{r, engine='python'}
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()  # Create a figure containing a single axes.
ax.plot([1, 2, 3, 4], [1, 4, 2, 3])  # Plot some data on the axes.

```

```
