### ISSUE TITLE
Rmd publish button within site deploys as single Rmd

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#5343]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.418
    OS Version      : macOS 10.14.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Create a directory containing an `index.Rmd`, `second.Rmd`, and `_site.yml`. The content of these files doesn't really matter; any minimal R Markdown site is fine.

Open the `index.Rmd` in the RStudio IDE. Click the publish icon. The "Publish to server" appears immediately. I am not prompted for a publishing destination (rpubs / Connect). I am not prompted if I want to publish the source or rendered result.

I choose the target server and give a title for the content. The deployment begins.

```
Preparing to deploy document...DONE
```

### Describe the problem in detail

A single-document deployment is  happening rather than a site-deployment. This is probably because the wrong rsconnect functions are being called.

The `manifest.json` we deploy has:

```json
  "metadata": {
    "appmode": "rmd-static",
    "primary_rmd": "index.Rmd",
    "primary_html": null,
    "content_category": null,
    "has_parameters": false
  },
```

We expect:

```json
  "metadata": {
    "appmode": "rmd-static",
    "primary_rmd": "index.Rmd",
    "primary_html": null,
    "content_category": "site",
    "has_parameters": false
  },
```

### Describe the behavior you expected

1. The `rsconnect::deployDoc` function is being called rather than the `rsconnect::deploySite`. We should be seeing the output:

   ```
   Preparing to deploy site...DONE
   ```

2. We should be asked if the source or locally-rendered output should be deployed, which informs the value for the `render` argument to `deploySite`.

3. The RPubs / RStudio Connect workflow step is probably fine to skip.

This may be a regression, as https://github.com/rstudio/rstudio/issues/3754 talks about the publishing button supporting sites.
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2           bookdown_0.13        packrat_0.5.0-14    
 [4] digest_0.6.18        jsonlite_1.6         magrittr_1.5        
 [7] evaluate_0.13        BiocInstaller_1.30.0 stringi_1.4.3       
[10] curl_3.3             rstudioapi_0.10      rmarkdown_1.15      
[13] tools_3.5.1          stringr_1.4.0        tinytex_0.15        
[16] xfun_0.9             yaml_2.2.0           rsconnect_0.8.15    
[19] compiler_3.5.1       askpass_1.1          htmltools_0.3.6     
[22] openssl_1.4.1        knitr_1.23          
```

**Comment by aronatkins** [comment]
In case the site content matters:

The `_site.yml`
```yaml
output:
  html_document:
  pdf_document:
```

The `index.Rmd`
```markdown
# R Markdown site

This is the index page. It has a link to [article](article.html) and [another](another.html).
```

The `article.Rmd`
```markdown
# Article

This is an article. It has a link to [index](index.html) and [another](another.html).
```

The `another.Rmd`
```markdown
# Another

Here is another page. It links to [index](index.html) and [article](article.html).
```

**Comment by ronblum** [comment]
Note: the default `bookdown` project successfully deployed as a site:
1) In console: `install.packages("bookdown")`
2) In IDE: File -> New Project -> New Directory -> Book Project using bookdown
3) Choose directory name and parent directory, then "Create Project"
4) Click on the publish button ![image](https://user-images.githubusercontent.com/31009952/64202899-41f0e780-ce60-11e9-88b6-709f23a99dce.png)
5) Choose account, then click on "Publish"
