### ISSUE TITLE
Keyboard shortcut to add #' for multiple lines of code

### ISSUE THREAD

**Issue by k-doering-NOAA** [rstudio/rstudio#5344]
In Rstudio (on windows 10, using Version 1.2.1335), I can use ctl+shift+c to add or remove commenting for multiple lines of code. I also realized I can use the same keyboard shortcut to remove the documentation indicator `#'` , but there is no shortcut that I could find to add it back in ( pressing ctl+shift+c predictably adds `#`)

If it doesn't already exist, a shortcut key for adding `#'` to the start of all highlighted lines would be helpful.  In particular, I want to use this so I can remove `#'` for the start of each line for some examples for an R function to see the syntax highlighting while editing, and then add the `#'` back in after I am done. I am sure there are other cases when editing documentation (or creating new documentation) that this shortcut could be useful.

**Comment by ronblum** [comment]
@k-doering-NOAA Thank you for raising the issue. I'm unable to reproduce it, though. Can you please provide sample code with which you are seeing this, in case that's the difference between what we're each trying?

**Comment by k-doering-NOAA** [comment]
@ronblum In the course of trying to document this I realized my mistake! It seems if you have a  tag included in the highlighted text that Rstudio can recognize as documentation (like `@example` or `@param` or even `@` by itself), then using ctl+shift+c will result in `#'` inserted instead of `#` - could you confirm this is true? Or am I still missing some nuances in how the shortcut works?

I didn't see this behavior documented when looking at the rstudio IDE cheatsheet, but perhaps I missed it? I had assumed initally when I posted the issue that there would be a separate shortcut to add #' to lines of code instead of #, which was incorrect.

I think this implementation is logical and no feature request is needed. Feel free to close issue.

To make this clearer to others who may see this, this is the behavior I have discovered. If I have 3 lines in an r script opened within Rstudio: 
```
#' @examples
#' sum <- 1+2
#' sum
```
If I highlight those lines and hit the shortcut ctl+shift+c, I now see:
```
@examples
sum <- 1+2
sum
```
which is helpful because I can now see syntax highlighting for the example in rstudio. Maybe I want to edit the example to : 
```
@examples
sum <- 1+2+3 #add in 3 as well
sum
```
Now, if I highlight all 3 lines, and hit the shortcut ctl+shift+c again, I get back #' in front of each line
```
 #' @examples
 #' sum <- 1+2+3 #add in 3 as well
 #' sum
```
but if I only highlight the 2nd and 3rd lines and hit the shortcut (so the tag @examples is not included, I would get:
```
@examples
# sum <- 1+2+3 #add in 3 as well
# sum
```
So plain comment symbols (`#`) were inserted instead of documentation symbols (`#'`). This last chunk was what I was trying originally, which lead to my misconception.

**Comment by tallguyjenks** [comment]
In R Markdown documents the following occurs:

if I have this is a code chunk and use the hotkey
```r
@data 
x <- 7
x * 7
```

it turns into this:
```r
# @data 
# x <- 7
# x * 7
```
if I have it outside a code chunk and just in the markdown space the following occurs:

```r
<!-- @data  -->
<!-- x <- 7 -->
<!-- x * 7 -->
```

**BUT** 

if I have the same text inside an R _**SCRIPT**_ then this is what I get:

```r
#' @data 
#' x <- 7
#' x * 7
```

**Comment by ronblum** [comment]
I'm raising this to a bug in order to review the discrepancy between the behavior above within a chunk vs. an R script.

Reproduced with RStudio 1.2.1578 on MacOS 10.15 (Desktop) and Ubuntu 18 (Server).
