### ISSUE TITLE
Spellcheck: uninformative tooltip is shown

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5348]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : v1.3.dev
    OS Version      : macOS Mojave 10.14.6
    R Version       : R version 3.6.1 Patched (2019-08-15 r77002)

### Steps to reproduce the problem

Create an R Markdown document with a spelling error, and then hover the mouse cursor over the misspelled word.

### Describe the problem in detail

A plain 'Spellcheck' tooltip is shown.

![Screen Shot 2019-09-03 at 3 35 51 PM](https://user-images.githubusercontent.com/1976582/64213142-b166d700-ce60-11e9-9e52-86602971928f.png)

### Describe the behavior you expected

A more evocative tooltip could be shown.

**Comment by jmcphers** [comment]
Not for 1.3
