### ISSUE TITLE
Markdown collapsed chunk overlaps chunk below

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#5351]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1577
    OS Version      : Windows 10
    R Version       : 3.6.1

### Steps to reproduce the problem

Create a markdown document with the following content:

````
```{r cars}
summary(cars)
```
```{r cars2}
summary(cars)
```
````

Run the first chunk to expand its output.
Collapse the output.

### Describe the problem in detail

The top of the second chuck disappears behind the bar with options for closing and expanding.
Probably clearer in a print screen:
![image](https://user-images.githubusercontent.com/28725410/64246057-61dde500-cf0c-11e9-8ed6-8aad806dce7f.png)

### Describe the behavior you expected

The chunk intact

**Comment by ronblum** [comment]
@BartJanvanRossum Thank you for raising this (subtle) issue! We'll review it as we continue to develop RStudio.

I am able to reproduce this using RStudio Desktop 1.2.1578 and 1.1.463 on Windows 10. It is not issue with RStudio Desktop on MacOS or RStudio Server on Red Hat 8.
