### ISSUE TITLE
Enhancement request: There should be no need to click on the "Update" button in the "Import Text Data" window when it is activated from the "File Panel"

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5357]
When clicking on a .csv file in the file panel and subsequently selecting the **Import Dataset...** option, the **Import Text Data** window pops up, which is great. However, it will then be needed to click on the **Update** button at the top right corner of the window to have the **Code Preview** section completed and have a preview of the data shown. The last click on the **Update** button seems to be redundant in the above scenario. 

PS. I think in the previous versions of RStudio there was no need to click the **Update** button in the above scenario.

Thank you for looking into this!

**Comment by gtritchie** [comment]
What version of RStudio, and what platform?

**Comment by hzarkoob** [comment]
Here is the info:

Version:     1.2.1335
Platform:   Server 

Thank you!

**Comment by ronblum** [comment]
@hzarkoob and @gtritchie I just checked 1.1.463, 1.2.1335, and 1.2.1578. This appears to be a regression in 1.2.1335, but it's working in the latest version. @hzarkoob how does it appear to you in [the current RStudio preview?](https://www.rstudio.com/products/rstudio/download/preview/) (Note that preview builds are intended for testing purposes only.)

**Comment by hzarkoob** [comment]
@ronblum I verified that it is fixed in the latest RStudio Preview, 1.2.1578.

**Comment by ronblum** [comment]
@hzarkoob Thank you for the update, and I'm glad it's working for you!
