### ISSUE TITLE
.rs.onAvailablePackagesStale throws error when more than one repo and _R_CHECK_LENGTH_1_LOGIC2_ is TRUE

### ISSUE THREAD

**Issue by ateucher** [rstudio/rstudio#5363]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  Version 1.3.422
    OS Version      :  macOS Mojave 10.14.5
    R Version       :  3.6.1 (2019-07-05)

### Steps to reproduce the problem
In RStudio: 

```r
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_"=TRUE)
.rs.onAvailablePackagesStale("c(CRAN = \"https://cran.rstudio.com\", bcgov = \"https://bcgov.github.io/drat/\" )")
#> Error in !repeated && grepl("%[[:xdigit:]]{2}", URL, useBytes = TRUE) : 
#>   'length(x) = 2 > 1' in coercion to 'logical(1)'

traceback()
#> 3: URLencode(contrib.url(repos), TRUE)
#> 2: sprintf("%s/repos_%s.rds", tempdir(), URLencode(contrib.url(repos), TRUE))
#> 1: .rs.onAvailablePackagesStale("c(CRAN = \"https://cran.rstudio.com\", bcgov = \"https://bcgov.github.io/drat/\" )")
```

### Describe the problem in detail
When RStudio starts I am getting the error: `Error in !repeated && grepl("%[[:xdigit:]]{2}", URL, useBytes = TRUE) : 'length(x) = 2 > 1' in coercion to 'logical(1)'`. This seems to occur when `.rs.availablePackages()` is called by the IDE. Here is the traceback:

```r
5: URLencode(contrib.url(repos), TRUE)
4: sprintf("%s/repos_%s.rds", tempdir(), URLencode(contrib.url(repos), 
       TRUE))
3: .rs.onAvailablePackagesStale(reposString)
2: .rs.availablePackages()
1: (function (docId, fileType) 
   {
       available <- .rs.availablePackages()
       ready <- !is.null(available$value)
       packages <- .rs.discoverPackageDependencies(docId, fileType)
       list(ready = .rs.scalar(ready), packages = packages)
   })("B5396695", ".R")
```

I have an additional repository set up in my `.Rprofile` (`bcgov = "https://bcgov.github.io/drat/"`), which is apparently stale and thus `.rs.onAvailablePackageStale()` gets called, which I'm guessing probably doesn't happen much in your testing.

This is occurring in `URLencode` (called from `.rs.onAvailablePackagesStale()`). I believe it can be fixed by replacing these lines: https://github.com/rstudio/rstudio/blob/332ebeb9b75764335988179b33f6c9dda0ba493f/src/cpp/session/modules/SessionPackages.R#L1481-L1485

with something like: 
```r
paths <- vapply(repos, function(x) {
  sprintf("%s/repos_%s.rds", 
          tempdir(), 
          URLencode(contrib.url(x), TRUE)
  )
}, FUN.VALUE = character(1))
```

### Describe the behavior you expected

This error does not occur.

**Comment by kevinushey** [comment]
Thanks for the bug report! Note that your example does not reproduce on its own; the repositories need to be explicitly set as well:

```r
repos <- c(
  CRAN = "https://cran.rstudio.com",
  bcgov = "https://bcgov.github.io/drat"
)

options(repos = repos)
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = TRUE)
.rs.onAvailablePackagesStale(.rs.deparse(repos))
```

**Comment by ateucher** [comment]
Ah, I didn’t realize that - sorry about that!
