### ISSUE TITLE
Spell check annoying issue avoidance 

### ISSUE THREAD

**Issue by neonira** [rstudio/rstudio#5364]
When **using spell check** on manual pages **while working in a package context**, the package name might appear as a spell check issue. This should not. 

It would really be nice **to not report issues about package names in such a context**, especially when standard R patterns are used as 

<pre>
\author{
\packageAuthor{wyz.code.metaTesting}

Maintainer: \packageMaintainer{wyz.code.metaTesting}
}.
</pre>

I believe that in RStudio, the project context is known and so should be dynamically added to the spell check exceptions.

**Comment by ronblum** [comment]
@neonira We've made significant changes to spell checking in our upcoming 1.3 release. I just checked with the code above, and it appears to be working as you describe. How does it perform in [the latest RStudio daily development build](https://dailies.rstudio.com/)? Note that the dailies are meant for testing purposes only.

**Comment by neonira** [comment]
Good. Indeed, not able to test on a latest dev build, as  my current environment setup is required to stay stable for a while. 
Indeed, will  check it as soon I'll be able to upgrade my rstudio environment.
