### ISSUE TITLE
folder navigation shortcuts

### ISSUE THREAD

**Issue by neonira** [rstudio/rstudio#5365]
One thing I dislike when working with RSTUDIO, is **the need to navigate through various folder**. This is very repetitive and time consuming. 

Won't it be nice and productive to have some very usefull shortcuts? One already exists, that is the hexagon icon R that brings you back to the RSTUDIO root folder. 

I wish to have a few more nearby this icon. **One for R source subfolder, one for testthat subfolder if exists, and one for manual pages subfolders**. This will be pleasant and productive to use.

**Comment by ronblum** [comment]
@neonira Thank you for the suggestion. We'll review it during out ongoing development of RStudio.
