### ISSUE TITLE
Blinking lines on RStudio IDE

### ISSUE THREAD

**Issue by hhekim** [rstudio/rstudio#5366]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1335
    OS Version      : macOS High Sierra Version 10.13.6
    R Version       : R version 3.6.0 (2019-04-26) -- "Planting of a Tree"

### Steps to reproduce the problem
I couldn't reproduce the problem. 

### Describe the problem in detail
Sometimes a dotted black line begin to blink on the screen. It occurs at the top and bottom of the screen and sometimes at the intersections of panes. It shrinks or stretches as I change the size of the panes, but it doesn't go away unless I restart the app.

### Describe the behavior you expected
-

Thanks,
Hakan

**Comment by ronblum** [comment]
@hhekim Thank you for reporting the issue. RStudio 1.2 comes with a new rendering engine which could be the cause. Can you try changing it, following the instructions at https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors? Thanks!

**Comment by hhekim** [comment]
I changed rendering engine to "software" as recommended in the article. It looks ok now. Thanks...

**Comment by ronblum** [comment]
@hhekim Excellent—thank you for checking and letting us know!
