### ISSUE TITLE
Error: Rstudio unable to establish connection with r session

### ISSUE THREAD

**Issue by kravitz-eli** [rstudio/rstudio#5367]
Hello,

I have been getting the following error message several times a day: rstudio unable to establish connection with r session

I am  using Rstudio version 1.2.1335 in desktop mode. I use R version 3.6.1/

I can recreate this problem. When I am working with files saved in One Drive and I log off, I get this error message when I sign back in. There is generally a 10ish second delay between logging into my computer and connecting to the WiFi.  It _seems_ like this delay is causing Rstudio to get out of sync with R. Sorry, I can't give a more technical description.

**Comment by jmcphers** [comment]
Are you still having this problem? We would need a lot more details to figure out what is specific to your configuration (most people do not have this problem with RStudio and OneDrive).

If you're willing, you might have luck with a daily build:

https://dailies.rstudio.com/

Notably there's a new preference under Options -> Code -> Saving which will cause fewer conflicts between RStudio and OneDrive. Does that help or mitigate the issue?

**Comment by kravitz-eli** [comment]
I am no longer having this issue. I wish I could give you more information.

**Comment by kevinushey** [comment]
Unfortunate that we were never able to ascertain a root cause but I'm glad you're no longer bumping into this issue!

**Comment by SubhodeepSinha** [comment]
Hello. Today(11/9/2020) I have installed Rstudio 4.0.2. And I am facing this problem. This dialogue box appears when I am changing my working directory. I made this Run as admin but the problem still occurs. What should I do? Please help!
