### ISSUE TITLE
Code completion of dyplr function like select, mutate etc.

### ISSUE THREAD

**Issue by NanisTe** [rstudio/rstudio#5368]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    R version: 3.6.1 (2019-07-05)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 17763)

### Describe the problem in detail

Generally there could be an issue of "overloading" functions from other packages depending on order of package loading.
We therefore always add package info to the function like

```
df <- data.frame(data = c(1,2,3,4),name=c("a","b","c","d"))
df %>%
dplyr::select(data, name)
```

Unfortunatelly Rstudio does code completion for the column names (here: ```data``` and ```name``` only if we use:

```
df <- data.frame(data = c(1,2,3,4),name=c("a","b","c","d"))
df %>%
select(data, name)
```
instead.
### Describe the behaviour you expected

We would expect Rstudio to also recognise the corresponding dplyr functions if ```dplyr::``` is used. This is espacially important for reproducibility of code behaviour in conditions where you are not having control over the order of package loading.

**Comment by ronblum** [comment]
@NanisTe Thank you for  raising this. I've also confirmed this in RStudio 1.2.1578, both Desktop on MacOS 10.15 (Catalina) and Server on Red Hat 8. We'll review this as we continue development on RStudio.

Note: in terminal R, the completion for these doesn't occur in either case.
