### ISSUE TITLE
RStudio HTTP user agent not used in the Install Required Packages prompt

### ISSUE THREAD

**Issue by glin** [rstudio/rstudio#5369]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.424 (also in 1.2-patch)
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.1

### Steps to reproduce the problem
1. Trigger the "Install Required Packages" prompt by creating a new R Markdown document (File -> New File -> R Markdown) without having some of `rmarkdown` or its dependencies installed.

![image](https://user-images.githubusercontent.com/20401866/64300188-8607e900-cf41-11e9-95d5-7fbe9047e205.png)

2. Click yes to install package dependencies. When installing packages, the default user agent will always be the R default (e.g. `libcurl/7.47.0`), rather than the RStudio default (e.g. `RStudio Desktop (1.3.424); R (3.6.1 x86_64-pc-linux-gnu x86_64 linux-gnu)`) or a custom `HTTPUserAgent` option.
This means that R 3.6 users won't be able to install Linux binary packages from RStudio Package Manager through this prompt (see #4826 for the original issue).

![image](https://user-images.githubusercontent.com/20401866/64300198-915b1480-cf41-11e9-8d65-970f305633c0.png)

Note: you can also reproduce this by creating a new Shiny app or Plumber API, publishing to Connect, etc., without having all the required package dependencies installed. R Markdown was just one example.

### Describe the problem in detail
This was originally discovered in RStudio Cloud here: https://community.rstudio.com/t/rmarkdown-package-install-dependencies-not-detected-via-file-popup/37972

According to @jmcphers, the RStudio HTTP user agent is only set in the main R session, not the slave R sessions that run those package installations. Also, those slave R sessions are run with `--vanilla`, so any `HTTPUserAgent` setting changes in an Rprofile.site or .Rprofile are ignored.

The original issue about user agents: #4826 

### Describe the behavior you expected

When installing package dependencies through the IDE prompt, we should be able to install binary packages from RSPM and Cloud in R 3.6. I was expecting that either the default RStudio user agent or a custom `HTTPUserAgent` setting would be used.

(cc @stevenolen)

**Comment by kevinushey** [comment]
@jmcphers does this meet the bar for v1.2? It seems borderline but I can imagine RStudio Cloud users getting frustrated if binary package installs seem to not work in contexts like these.

**Comment by jmcphers** [comment]
No, release certification is underway and I don't think we want to reset the clock (we want to release 1.2-patch in less than two weeks). I think we should do the following:

1. Fix this holistically. This is at least the 3rd "bug" we've had that could have been worked around if there were a user hook to run code in our `--vanilla` R processes. (The same thing has happened a bunch for `rsconnect`). I'm imagining some mechanism whereby `AsyncRProcess` takes a job name of some kind, and then we check for a user hook with that name and/or a hook to run for RStudio vanilla R processes.
2. Put the fix on 1.3 and let it bake a week or two.
3. Backport to 1.2 and release a post-1.2 release for RStudio cloud.

**Comment by kevinushey** [comment]
It also sounds like it's fortunately possible to work around this on the RSC side so I definitely agree we don't need to take any action for v1.2.
