### ISSUE TITLE
Pop up interrupts opening a project in a new session

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5373]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1578
    OS Version      : Red Hat 8.0
    R Version       : 3.6.1

### Steps to reproduce the problem

1) File -> Open Project
2) Choose a project
3) Check "Open project in new session"
4) Click on "Open Project"

### Describe the problem in detail

A modal pops up with the message "Open Session/Loading..." and the buttons "Open Session" and "Cancel." Click on "Open Session" successfully opens the session in a new window.

<img width="370" alt="open_project" src="https://user-images.githubusercontent.com/10569626/64443666-49dea080-d087-11e9-8564-338e84f879da.png">

### Describe the behavior you expected

The session should be opened without the interrupt. It is meant for launcher, only.

**Comment by kfeinauer** [comment]
Since this is a regression, should we take this for the patch release?

**Comment by ronblum** [comment]
I say no, since it works when you click on "Open Session," but I'm amenable.
