### ISSUE TITLE
Rnotebook does not create snapshot for all plots in a scope inside a chunk. 

### ISSUE THREAD

**Issue by mathieutiret** [rstudio/rstudio#5374]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.3.1335
    OS Version      :  Ubuntu 2018
    R Version       : 3.5.2 (2018-12-20)

### Steps to reproduce the problem

Write the following code in a Rmarkdown or Rnotebook chunk (with the braces).
```
{
  plot(cars, t='l')
  plot(cars)
}
```

### Describe the problem in detail

Only the last plot generates a .snapshot file in the notebook cache as described in "Implement display list-based plot resizing for notebooks #700". Therefore, only the last plot could be resized when showed in a new window. 

This behaviour only occurs in a scope (braces, if, loop) : the problem does not occur in the following code :  
```
%{
  plot(cars, t='l')
  plot(cars)
%}
```

### Describe the behavior you expected

That all plots generate a .snapshot file, so that plot in a scope (if or loop) can also be resized accordingly.

**Comment by ronblum** [comment]
@mathieutiret Thank you filing the issue. From #700, 
> Display lists are persisted as `.snapshot` files

_Files_ is plural, so presumably they should all be saved. I'll mark this as a bug to review as we continue development of RStudio.

**Comment by kevinushey** [comment]
I believe this is already fixed in the daily builds, and was fixed as a byproduct of https://github.com/rstudio/rstudio/pull/5359.
