### ISSUE TITLE
Desktop can hang with RDP/RSP 1.3 integration

### ISSUE THREAD

**Issue by tmcduff** [rstudio/rstudio#5375]
RStudio Edition : Desktop and Server
    RStudio Version :  1.3 
    OS Version      : RHEL 7.6 / Mac 10.14.6
    R Version       : 3.6.0

### Steps to reproduce the problem
1. Setup Launch Server sessions with viable RSP servers that pass the prelaunch diagnostics tests. Set one of the servers on the list as the default. 
2. Introduce some fault in the default server that disallows communication back to the desktop.
3. Close the desktop.
4. Reopen the desktop.
5. The prelaunch diagnostic will try to verify the viability of the server before opening. This seems unsettling at first and you see the pinwheel. 
6. My first attempt at this caused my Mac RDP desktop to hang until I had to kill the process. Subsequent attempts under the same workflow the RDP launch fails to open immediately and then you see the Icon bounce and then the expected error message about the diagnostic failure.

Overall, the issue may be minor at this point as the desktop does seem to recover better after subsequent attempts. 

![Screen Shot 2019-09-06 at 9 53 04 AM](https://user-images.githubusercontent.com/7966616/64458994-abb10180-d0ab-11e9-81e2-e6084a35ff33.png)

**Comment by kfeinauer** [comment]
The hang should be caused by the connection not going anywhere, the hang caused by the connection taking a long time to timeout (default machine timeout can be many minutes long). Need to switch the connection to have a more aggressive timeout, say 3 seconds.
