### ISSUE TITLE
Export to clipboard of a plot fails

### ISSUE THREAD

**Issue by mbenhamo** [rstudio/rstudio#5377]
Hello,

Whenever I try to export a plot (copy to clipboard) it captures the script and some of the plot window, which is open instead of capturing the plot window solely. 

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by kevinushey** [comment]
Do you also see this with the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio?

**Comment by ronblum** [comment]
@mbenhamo In addition, what environment are you using ? 

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by mbenhamo** [comment]
R version: R x64 3.5.1
OS version: Microsoft Windows 10 Pro - 10.0.17134 Build 17134
RStudio: Version 1.1.456

**Comment by mbenhamo** [comment]
The preview release of RStudio solved the issue - Thank you!

**Comment by ronblum** [comment]
@mbenhamo I'm glad to hear the preview release solves the problem—and thank you for letting us know!
