### ISSUE TITLE
Request: add option to clear all breakpoints in file and project

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5379]
Would be nice if there could be an option to clear all the debugging breakpoints that are set in a file and/or in a project. I oftentimes find myself setting multiple breakpoints in multiple large files, and once I'm done debugging, have to manually eyeball the whole file for all breakpoints and remember which files had them.

**Comment by ronblum** [comment]
@david-cortes Thank you for the suggestion!

**Comment by jmcphers** [comment]
We already have this. :-)

![image](https://user-images.githubusercontent.com/470418/66684229-69408e80-ec2e-11e9-913f-3ca16576d3ca.png)

**Comment by professorbeautiful** [comment]
This doesn't work when the breakpoint is in a loop. The red dot disappears, but it keeps stopping anyway.
