### ISSUE TITLE
Turn on real-time spell check by default

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5382]
The new real-time spell checking engine is currently off by default; you need to turn it on explicitly in Global Options to use it.

Our first 1.3 preview release should ship with this feature enabled by default.

**Comment by jmcphers** [comment]
@adamconroy Yours to turn on when you're ready. All that's needed is to flip this bit:

https://github.com/rstudio/rstudio/blob/c33abdbe7b4ec5bd1a5793f0b56377e28baa1952/src/cpp/session/resources/schema/user-prefs-schema.json#L563-L567

**Comment by adamconroy** [comment]
https://github.com/rstudio/rstudio/commit/54a3af8ad4da7269da94f1a2199e515c4c9c89d4 it is done!

**Comment by jmcphers** [comment]
🎉
