### ISSUE TITLE
Error message when reloading shiny app without saving first

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#5386]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1578-2, 1.2.1335-1
    OS Version      : Ubuntu
    R Version       : 3.4.4

### Steps to reproduce the problem
1. Create a new shiny app
2. Run the app
3. reload the app
4. make some change to the file like adding a comment
5. try to reload the app again

### Describe the problem in detail
After making a change to the app and then clicking reload, the user is prompted to save or dont save the changes. The user can click either one and then a error popup appears. See screenshot

<img width="1571" alt="Screen Shot 2019-09-09 at 1 38 53 PM" src="https://user-images.githubusercontent.com/43964690/64626080-dc967c80-d3b2-11e9-86cc-1c306964bcc9.png">

### Describe the behavior you expected
No error message

**Comment by ronblum** [comment]
This is reproducible in Red Hat 8 and SUSE 12 SP4, as well. Note that
- If the file is first saved between steps (4) and (5), there's no error.
- Similarly, when going through similar steps with Plumber API—running without first saving—the window won't get launched, though no error occurs.

This is not a regression, as it occurs in RStudio Server 1.1.463, as well.
