### ISSUE TITLE
Tab key not inserting tab (or spaces), tried to auto complete when not needed

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#5387]
This seem to be a long standing issue.

[2013](https://support.rstudio.com/hc/en-us/community/posts/200658573-Tab-behaviour-in-script-window)

[2016 and 2017](https://support.rstudio.com/hc/en-us/community/posts/115008079068-Cannot-type-TAB-or-reassign-autocomplete-shortcut-key-in-RStudio-Editor)

2018: #2766. My problem is more than the issue described in #2766, so I'm raising new issue and included reference to that one.

My current environment:
RStudio 1.2.1335
```r
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

1. In R script, console code chunk of RMarkdown. Pressing `Tab` after ending of code (or other empty places) will first generate a warning tool top "no matches", then next press take effect.
2. In RMarkdown text, **pressing Tab have no effect whatsoever**. This is very annoying when user try to indent something or align text. Interestingly, RStudio server 1.1.453 don't have this problem (but still have problem 1 in R script).

**Comment by ronblum** [comment]
@dracodoc Thank you for raising this. For (2), I can reproduce it; in addition, continuing to click on <kbd>Tab</> repeatedly goes through the same process, despite it now being preceded blank text. 

Also: I checked a couple of other file types. The same problem occurs with Stan files, but not C++.

**Comment by kevinushey** [comment]
How can I reproduce (2)?

**Comment by dracodoc** [comment]
Just input text in RMarkdown, pressing tab don't have effect for me, either at a new line or after some text(or it don't have effect anywhere).

**Comment by kevinushey** [comment]
Thanks -- I can reproduce only if the `[ ] Use tab for multiline autocompletions` completion preference is checked. (Tools -> Global Options... -> Code -> Completion).

You can try disabling that to fix the issue. I'll see if we can figure out what's going on.

**Comment by dracodoc** [comment]
Yes, problem #2 no longer appears once that option was disabled. Thanks for verifying!

**Comment by dracodoc** [comment]
Update:
I found even with the tab for multiline option disabled, tab still only have effect in a new line. With some text, either right after text, or after inserted some space after text, the tab still doesn't take effect.

**Comment by tmcduff** [comment]
Verified: 1.3.749

**Comment by raffaem** [comment]
I still have this issue. Can we reopen it?

**Comment by raffaem** [comment]
For those ending up here from Google, check that Help / Accessibility / Focus / Tab Key Always Moves Focus is disabled.
