### ISSUE TITLE
Ability to copy the Traceback log while in debug mode

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/rstudio#5388]
As a RStudio IDE user or QA, I want to copy the Traceback log (similar to console) when running my apps in debug mode so that I can share the info to my team.

Currently, I am not able to copy the traceback log at all (after trying several ways) and I had to take a screenshot to save the log.

System details:
1. RStudio IDE: Version 1.2.1335
2. MAC OS: Mojave (10.14.5)

Steps to reproduce:

1. Open a app of your choice using RStudio IDE (In my case, its shiny app)
2. Set a breakpoint in the code to enable debug mode
3. Run the app
 You will see a Traceback window
4. Try to copy the log from traceback

Expected: Should be able to 
Actual: can not

screenshot attached
![RStudio_IDE_Traceback_log](https://user-images.githubusercontent.com/5369655/64654953-9b689180-d3df-11e9-97d4-a34fbed0a6dd.png)

**Comment by ronblum** [comment]
@MadhulikaTanuboddi Thank you for filing this. I can reproduce this behavior both in RStudio Desktop on MacOS 10.15 (Catalina) and RStudio Server 1.2.1578 on Ubuntu 18.04.2 with Google Chrome. I'll mark this as an enhancement to review as we continue development of RStudio.

**Comment by MadhulikaTanuboddi** [comment]
@ronblum : Great. Thank you.
