### ISSUE TITLE
The default directy of the file pane should be the working directory

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5392]
### System details

RStudio Edition : Server
RStudio Version : 1.2.1335
OS Version      :  Ubuntu
R Version       : 3.6.0

The default directory of the file pane is currently the _Project Directory_. It might be a matter of opinion, but I think it would be more useful it it defaults to the _Working Directory_. That is because at any point of time, the users are probably focused on a certain folder within the Project root directory, i.e., the working directory. I have used .Rprofile to make sure that RStudio working directory is set to my folder of interest when it gets loaded.

An pragmatic way to think about it is as follows: The File Pane is a friendly environment to both _navigate_ through the files and _open_ them. So it offers the same functionality as the "Open a New File" operation and much more, like copying/moving files, etc. Because of that it can/should replace the "Open a New File" operation for all practical uses. If the RStudio users begin to use the File Pane for opening files (I have already started), it would make sense for its default directory to be the working directory for the same reason that the default directory of the "Open a New File" is the working directory.

Thank you for looking into this!

**Comment by ronblum** [comment]
@hzarkoob Thank you for the suggestion! We'll consider it as we continue development of RStudio.

**Comment by jmcphers** [comment]
Would an option to track the working directory in the pane do what you want?

See https://github.com/rstudio/rstudio/issues/4615.

**Comment by hzarkoob** [comment]
@jmcphers I noticed there are several inaccuracies in the answer I provided above. Please disregard it and kindly consider the following answer:

The solution in #4615 works, but I am not a fan of it. That is because it may deviate from the purpose of the file pane which is displaying the latest directory visited by the user. Instead the following set of suggestions may work better:

- There should be a global option that determines the default directory of the file pane, with the following two options: Project Directory and Working Directory.

- For those like me who like to use the file pane in the full-screen (zoomed) mode, it would be helpful to have a shortcut for "Go To Working Directory" on the top of the File Pane _without_ the need to use the "More" tab. This shortcut can be placed next to the shortcut for "Go to project directory" or even replace it. I think people are more interested in the Working Directory than the Project Directory when the two differ.

- It would be nice to have the following keyboard shortcuts:
    - Zoom files (Currently exists)
    - Zoom files and set the directory to the working directory (Does not currently exist)

I think the second shortcut above will be liked very much by people over time and will replace the "Open file..." operation at some point.

**Comment by hzarkoob** [comment]
I noticed the suggestion provided in the second bullet above is not related to the topic of this issue. So I've created a separate issue for it.  #5408 Thank you for the consideration!
