### ISSUE TITLE
R Studio Shuts Down when trying to save project

### ISSUE THREAD

**Issue by toconnor5** [rstudio/rstudio#5394]
I am new to R Studio and must use it for one of my classes. I have a Windows computer and just downloaded the most recent version of R and R Studio. When I try to save a project, the file browser will open, but then R studio will freeze and shut down. I deleted and reinstalled R and R Studio but am still dealing with the same issue. Any help would be greatly appreciated. I am also used the desktop free version.

**Comment by kevinushey** [comment]
Are you using a Dell laptop? Some users have reported crashes of this form when Dell Backup and Recovery software is installed and running on their machine:

https://community.rstudio.com/t/rstudio-v1-2-1335-crashes-on-file-open-or-file-save-windows-7-pro/32046/16

**Comment by jmcphers** [comment]
Closed since we don't have a repro. @toconnor5 feel free to reopen if the issue resurfaces.
