### ISSUE TITLE
Marking the chunk with error when an R Notebook is run using "Run All"

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5395]
When running an R Notebook with numerous chunks using the "Run All" option, if an error occurs, it is not straightforward to determine which exact chunk caused the error. To this end, one needs to either check the console and perhaps search for a few phrases of the line in which the error occurred, or scroll the document all the way from top to bottom to identify the error text in the red font.

To help facilitate the above process, it would be helpful if a marker will be shown in one or both of the following places:

* In the **Document Outline**, if any section/subsections had been created by the user.
* In the **Jump to Chunk/Function** section at the bottom of the window where a list of all chunks is presented upon a click.

A suggestion. Currently, a green marker is displayed in the Document Outline next to the section which was last clicked on. The marker requested above can be very similar to this marker just with a different color.

PS. This issue was first reported in the R Markdown page, but then was transferred here because it seemed to be more related to RStudio IDE than R Markdown. https://github.com/rstudio/rmarkdown/issues/1643

**Comment by ronblum** [comment]
@hzarkoob This is a neat idea, especially piggybacking on the existing markers. I'm tagging it as an enhancement to review as we continue development of RStudio. Thanks!

**Comment by hzarkoob** [comment]
Thank you for the consideration!

**Comment by PStaus** [comment]
Hi, I would really appreciate a solution as suggested by @hzarkoob. Has there been any other solutions yet I am not aware of?
Thanks!
