### ISSUE TITLE
Terminal does not source .bashrc on Ubuntu

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#5396]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1578 
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.1

### Steps to reproduce the problem
1. Create a file `~/.bashrc` containing e.g. `alias does_it_work='echo YES'`
2. Open RStudio
3. Open New Terminal with `Alt-Shift-R`
4. Type `does_it_work`

### Describe the problem in detail/Describe the behavior you expected
The terminal should show `YES` indicating that the `.bashrc` file got sourced and (on my machine) it does not.

**Comment by kendonB** [comment]
I managed to patch this by adding a file `~/.profile` containing:
```bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
```

**Comment by pascaloettli** [comment]
`~/.profile` is created by default for each user in Ubuntu. You perhaps deleted the file long time ago without remembering it.

**Comment by kendonB** [comment]
Possibly yes.

**Comment by kendonB** [comment]
I am now finding that RStudio is again not running `source ~/.profile` at start up for terminals on my machine. Can you help troubleshoot this?

**Comment by kendonB** [comment]
As a workaround, I added `source ~/.bashrc` to `/etc/bash.bashrc` and that seems to work. However, I think RStudio should be sourcing the user files as well as the site files?

**Comment by gtritchie** [comment]
All RStudio does when launching a terminal is execute this command:

`/usr/bin/env bash -l`

See https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal#lifetime for more on that.

**Comment by pascaloettli** [comment]
Do you have the same issue on a newly created account? I have the same configuration than yours and I cannot reproduce.

**Comment by ronblum** [comment]
There are instructions in the link above for changing to a custom shell. Changing to just the `bash` executable, e.g. `/bin/bash`, results in `.bashrc` getting  sourced. Although I should note that I can't reproduce the issue above on Ubuntu, only on MacOS—on Ubuntu 18.04, even `env bash -l` sources `.bashrc` in my case.

**Comment by kendonB** [comment]
Changing to a custom terminal `/bin/bash` works great. Thanks!

**Comment by julianstanley** [comment]
> Changing to a custom terminal `/bin/bash` works great. Thanks!

I had a similar problem that this also fixed.

Instructions to save others a few seconds:

Tools-->Terminal-->Terminal Options-->"New terminals open with:" set to custom -->"Custom shell binary:" Browse to /bin/bash (or your favorite shell)--> Save and be merry.
