### ISSUE TITLE
Solving Environment Failures

### ISSUE THREAD

**Issue by wxprofessor** [rstudio/rstudio#5403]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Describe the behavior you expected

Hello :)  

While installing Rstudio via anaconda on two boxes, the following happened:

box 1: Fresh(er) conda install, everything completed in about an hour with a few environment issues that worked their way through flexible solves.. and it works great! Yay! :)

box 2: My main beefie box, has been running conda since new.. around a year or so... about midnight last night I began the install before going to bed around midnight or so, with the knowledge of how long it took to install on my test box (always install things there first).. around 8am this morning the install was still running with the following shellshot:
![image](https://user-images.githubusercontent.com/5704029/64824080-17e9a480-d587-11e9-935d-35938767c61c.png)

So now it's nearly 6pm, time to go home, and it's still 'installing'.. which means it's been running for about 18 hours... I can only assume something is amiss, so I'm about to dump the install, but thought you guys should know :)  I've moved the shell around a few times, so it doesn't look pretty, but here is where it is at now.. figured I should let someone know! This is my first time running rstudio in jupyter lab, but I must say, it's quite handy to keep the books all in the same folder :)

![image](https://user-images.githubusercontent.com/5704029/64824245-79117800-d587-11e9-9ce2-a33c49f292e3.png)

**Comment by ronblum** [comment]
@wxprofessor Thank you for raising the issue, which we'll review as we continue development. However, since this is a problem with Anaconda installation, as opposed to the RStudio standalone installer, there is a good likelihood that the problem is with Anaconda. I suggest also filing the issue and/or searching their knowledge base for any know issues.
