### ISSUE TITLE
"Show help tooltip after function completions" option has no effect

### ISSUE THREAD

**Issue by khvorov45** [rstudio/rstudio#5405]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.2.1335
    OS Version      :  Windows 10
    R Version       :  3.6.1

### Steps to reproduce the problem

1. Uncheck "show help tooltip after function completions" in Tools-Global Options...-Code-Completion.

2. See if the help tooltip actually does not appear after function completion.

### Describe the problem in detail

The help tooltip always appears after function completions regardless of the state of the option ("show help tooltip after function completions") that is supposed to control it as far as I understand it.

### Describe the behavior you expected

I expected the brightly colored distracting tooltip to not be shown after function completions upon unchecking "show help tooltip after function completions".

![Imgur Image](https://imgur.com/bSr7Uuc.gif)

**Comment by ronblum** [comment]
@khvorov45 Thank you for raising this issue. I am able to reproduce it. We'll review it as we continue to develop RStudio.

Reproduced using RStudio Desktop 1.2.1578 on Windows 10 and MacOS 10.15 (Catalina), and RStudio Server 1.2.1578 on Red Hat 8. Also reproduced using RStudio 1.1.463.

**Comment by rich-rstudio** [comment]
@kevinushey, I was able to reproduce this on 1.3.857 Desktop and Server open source

**Comment by rich-rstudio** [comment]
verified in Version 1.3.885
