### ISSUE TITLE
Keras crashes R session with fatal error

### ISSUE THREAD

**Issue by MikeRoven** [rstudio/rstudio#5406]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.1.456
    OS Version      :  windows 7
    R Version       : 3.6.1

### Steps to reproduce the problem
I'm using rstudio in anaconda. I installed keras with

```
install.packages("keras")
library(keras)
install_keras()
```

Then i tried to run the example code from https://keras.rstudio.com/
```
library(keras)
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y

# reshape
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))
# rescale
x_train <- x_train / 255
x_test <- x_test / 255

y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)

model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')
```

### Describe the problem in detail
When it gets to the `model <- keras_model_sequential()` line, it runs for a few seconds before R crashes with the "r session aborted. R encountered a fatal error".

One thing i noticed that was strange in anaconda, there are two "r-reticulate" environments after installing keras. I tried deleting one but both disappeared. I'm new to anaconda so i'm not sure if that's weird behaviour or not.

### Describe the behavior you expected
I expect it to run without issue.

**Comment by ronblum** [comment]
@MikeRoven Thank you for filing the issue. A few things:
1) Does the problem occur in standalone R, or only in RStudio?
2) Does the problem occur with the [latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/)? (Note that preview builds are intended for testing purposes only; and if you're relying on Anaconda, this might not be an option, as Anaconda only installs RStudio as late as 1.1.456.)

**Comment by MikeRoven** [comment]
I was under the impression that keras for r on windows required anaconda

**Comment by koverholt** [comment]
It sounds like you are mixing R and Python packages in your Anaconda environment. We recommend using standard R tooling for R packages and standard Python tooling such as Anaconda for Python packages.

You could try the following to keep the R and Python environments/packages separate:

* Install Anaconda for Python packages
* Install R from https://www.r-project.org for R packages
* Install `keras` in R and run `install_keras()` as you did before, but from the R environment and not the Anaconda environment

Note that the `keras` R package should still detect and use Anaconda for the Python dependencies.

That will keep the R and Python environments/packages separate and help us determine if that fixes the problem.

**Comment by harryprince** [comment]
@ronblum same issue +1;
In my experience, tensorflow and keras are easy to crash without any error information in the R session. Could we make some logs in the Python sub session or in the R main session?

Currently, I  am using Window10 + Cuda10.1.

```
> library(tensorflow)
> library(keras)
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.2.4.1     tensorflow_1.14.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1      lattice_0.20-38 zeallot_0.1.0   grid_3.6.1      R6_2.4.0        jsonlite_1.6    magrittr_1.5    tfruns_1.4      whisker_0.4    
[10] Matrix_1.2-17   reticulate_1.13 generics_0.0.2  tools_3.6.1     yaml_2.2.0      compiler_3.6.1  base64enc_0.1-3
```

**Comment by harryprince** [comment]
@ronblum 
currently, using lastest RStudio 1.2+ is pretty hard for Anaconda too, wish to see a better solution for entire deep learning model training on Windows.

**Comment by ronblum** [comment]
@harryprince Have you tried running the code outside of RStudio, using standalone R outside of RStudio? This is to help figure out if this is an issue with RStudio or with R/`keras`.

**Comment by MikeRoven** [comment]
Sorry forgot about this, I ended up solving it. Using standalone rstudio, updating it and updating R, and then fixing PATH to remove old python installations so i could install_keras() successfully worked.

**Comment by ronblum** [comment]
@MikeRoven Thank you for the update and I'm glad it all worked out!

**Comment by chaosssss123** [comment]
i have the same issuw. r studio crashes after a whle, after running tensorflow::install_tensorflow()
