### ISSUE TITLE
One-click shortcut for "Go to working directory" in the File Pane

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5408]
When a user is in the File Pane, they can _go to the working directory_ using the **More/Go to working directory** button. This is a great feature, but a problem is that it is a "two-click" operation. Because of the frequent need to go to the working directory while in the File Pane, I think it would be helpful to make the above operation one-click. 

One practical way to make this happen is to give the user the flexibility to decide which exact operations they want to see a direct button for, and which operations they want to see under the "More" tab. Ideally, this will be a drag and drop operation. 

Note . There is already a shortcut for "View the current directory" on the top of the console (a small arrow). But it cannot be seen/accessed when a user is working in the zoomed Source Pane, which I think is expected to be the common mode when one programs in RStudio for an extended amount of time.

Thank you for looking into this!

**Comment by ronblum** [comment]
@hzarkoob Thank you for creating a separate enhancement request!
