### ISSUE TITLE
Ctrl-Tab Doesn't Switch Files in the Correct Order

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#5410]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 10 (current updates)
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Load multiple files in the following order `1.R`, `2.R`, `3.R`
2. Drag the tabs of the file viewers so that they are now in the order `2.R`, `1.R`, `3.R`
3. While in the tab viewing `2.R` (the first tab in order), press Ctrl-Tab to switch to the next tab.

Note that the same issue is present for Ctrl-Shift-Tab going between tabs in reverse.

### Describe the problem in detail

What does occur is it switches to the file tab for `3.R` apparently because that was the load order.

### Describe the behavior you expected

What it should do is switch to the next file tab in the current viewing order, `1.R`.

**Comment by ronblum** [comment]
@billdenney I'm unable to reproduce the problem, both on Windows 10 and MacOS 10.15 (Catalina). Do you still see the issue in [the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/)? (Note that preview builds are intended for testing purposes only.)

**Comment by billdenney** [comment]
Unfortunately, it is now happening more sporadically.  I'll reopen the issue when I can figure out the reproducible steps.
