### ISSUE TITLE
In RMarkdown code chunk, make code complete for folder start from project folder instead of document folder

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#5412]
In code chunk of RMarkdown, inside a quote, tab can bring code complete for folder and files, which is very useful in input file/folder/path.

When using relative path, this seemed always start from document folder of the Rmd, not the project folder. This is understandable as knitting a Rmd usually take document folder as working folder. 

However there are also other usage of Rmd which require different patterns. Myself use Rmd to organize code/notes/old code/various attempts/design ideas, basically everything relate to a topic are in a Rmd. This kind of Rmd never get knitted as the code chunks are holding places of various code sections, not a part of a report. If I organize these Rmd into different folder for sub projects, the document folder will change and I cannot use the auto complete for folder anymore as it doesn't start from project folder -- and to run the code chunk individually, the working directory is always project folder.

Both options are valid use cases. I'm wondering what's the best approach. One option is to have a switch for two selections in UI. There is a similar option in Knit -> Knit directory, but I'm not sure if this is the right place to apply to this aspect.

Or there could be a per Rmd configuration entry, like an option inserted in header, respond to some UI options.

**Comment by ronblum** [comment]
@dracodoc Thank you for bringing this up. Could you provide an example of what you do, with some sample code and steps? It would be helpful to get an idea of what the issue is that you're running into and the improvement suggestion. Thanks! Also, I believe that the autocompletion is based on the working directory (which is initially the project directory).

**Comment by dracodoc** [comment]
Sorry I didn't explain it better.

Let's say the current project directory is `Project`, and there is a Rmd in a subfolder `module`

```
Project
    ├─module
           └─xx.Rmd
```

In code chunk of Rmd, if you input a "" and start to press tab inside the "", RStudio will provide list of folder and files with auto complete as relative path. When using in console or .R script, this is from working directory, but in a Rmd that in a subfolder, it start from the Rmd document folder. This is understandable as knitting will run them from Rmd document folder.

However I'm using code chunk to hold some code and often run them interactively, never knitting the whole document in some cases. Then I'll need the path to start from working directory.

**Comment by ronblum** [comment]
@dracodoc Ah! Thank you. I'll mark this option as an enhancement to review as we continue developmet of RStudio.

**Comment by fernandovmacedo** [comment]
I have the same issue. Is there any chance to be fixed in version 1.3?

**Comment by kevinushey** [comment]
Looks like this was implemented for Markdown links (e.g. `[](path/to/file)`) but not regular file autocompletion.

Here's where we handle that preference for completion of Markdown links:

https://github.com/rstudio/rstudio/blob/3b6d10e1db509c00f57f8f7f47162cc969bf6711/src/cpp/session/modules/SessionRMarkdown.R#L36-L43

The autocompletion code for files in R Markdown documents lives here:

https://github.com/rstudio/rstudio/blob/3b6d10e1db509c00f57f8f7f47162cc969bf6711/src/cpp/session/modules/SessionRCompletions.R#L2190-L2221

So we'd need to do a similar treatment for finding the "base" when completing relative paths.
