### ISSUE TITLE
File pane directory should not change when the browser gets refreshed

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5414]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1578 (latest RStudio preview)
    OS Version      :  Ubuntu
    R Version       : 3.6.0

When the browser gets refreshed, the directory of the file pane gets reset to its default value (i.e. Project directory). I think the directory of the file pane should not change by browser refreshes, because such refreshes may happen randomly or be used by the user just to resolve an unexpected behavior or something.

**Comment by ronblum** [comment]
@hzarkoob Thank you for filing the issue. However, I can't reproduce the problem. What is the operating system and browser from which you're connecting to the server? And which version of Ubuntu is the server on?

**Comment by kfeinauer** [comment]
IIUC correctly, this is intentional behavior. @jmcphers might have some insight into this one.

**Comment by hzarkoob** [comment]
@kfeinauer Thank you for the information. I think you are referring to #4615. Please note that the above suggestion is different from the suggestion made in #4615 on the requirement for the file pane tracking the working directory. The current suggestion just asks for the file pane maintaining its _current directory_ if the browser gets refreshed. Of note, upon refreshing the browser, all the following items remains unchanged:

- Variables in the environments
- Content of the the console
- Currently selected pane(s) and their _zoom_ status

I think it is GREAT that the above items do not change. It would be helpful/expected that the file pane directory does not change upon refreshing the browser either.

Thank you for looking into this!

**Comment by hzarkoob** [comment]
@ronblum I noticed the issue is marked with the label "repo needed". Please let me know if I need to provide more system details.

**Comment by ronblum** [comment]
@hzarkoob No, that's a holdover from a question I asked that off the mark and not useful.

**Comment by hzarkoob** [comment]
@ronblum Thank you for the clarification.

**Comment by jmcphers** [comment]
It looks like this only works in projects right now.

https://github.com/rstudio/rstudio/blob/17e7aefbd45fdae316f47fc40cedf88148a5b765/src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java#L262-L265

@hzarkoob Does it work for you inside a project?

**Comment by hzarkoob** [comment]
@jmcphers Not sure if I fully understood your question. If you are asking whether I faced the above issue while I am working in a _Project_, the answer is "yes". I work almost always use RStudio while working in a _Project_ because it allows to sync files with Github.
