### ISSUE TITLE
You website download file sizes don't match is this a corrupt file?

### ISSUE THREAD

**Issue by stillpointx** [rstudio/rstudio#5416]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Describe the behavior you expected

https://www.rstudio.com/products/rstudio/download/#download
RStudio 1.2.1335 - Ubuntu 18/Debian 10 (64-bit) 	100.4 MB 	2019-04-08 	71a8d1990c0d97939804b46cfb0aea75

When I downloaded your RStudio 1.2.1335 - Ubuntu 18/Debian 10 (64-bit) package the file size says 105.2 MB which doesn't match what's on your website is this a typo?  Or has someone added something to your package and changed the HASH?

Thanks

**Comment by ronblum** [comment]
@stillpointx The download is correct. The different is due to the discrepancy between calculating file size in binary (1024 x 1024 bytes per MB) and decimal (1000 x 1000 bytes per MB). You can see the discrepancy even when using `wget`, which recognizes `Length: 105239800 (100M)` and final file size of `100.36M`:

```
root@ip-10-0-0-215:/home/rstudio# wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb
--2019-09-17 15:00:31--  https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb
Resolving download1.rstudio.org (download1.rstudio.org)... 13.224.2.28, 13.224.2.52, 13.224.2.62, ...
Connecting to download1.rstudio.org (download1.rstudio.org)|13.224.2.28|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 105239800 (100M) [application/x-deb]
Saving to: ‘rstudio-1.2.1335-amd64.deb’

rstudio-1.2.1335-amd64.deb         100%[=============================================================>] 100.36M  81.6MB/s    in 1.2s    

2019-09-17 15:00:33 (81.6 MB/s) - ‘rstudio-1.2.1335-amd64.deb’ saved [105239800/105239800]
```

Also when using `du`:
```
root@ip-10-0-0-215:/home/rstudio# du -sb rstudio-1.2.1335-amd64.deb; du -sk rstudio-1.2.1335-amd64.deb; du -sm rstudio-1.2.1335-amd64.deb 
105239800	rstudio-1.2.1335-amd64.deb
102776	rstudio-1.2.1335-amd64.deb
101	rstudio-1.2.1335-amd64.deb
```
