### ISSUE TITLE
restrict keyword not recognized as valid C

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#5418]
Have started doing more coding in `src` of projects with RStudio -- the auto-complete for `VECSXP` etc are great!

As I use it more I notice some room for improvement, e.g. there is a fair amount of valid code that gets flagged.

e.g. in `data.table/src/cj.c`, I get the following:

![Screenshot 2019-09-17 at 4 40 12 PM](https://user-images.githubusercontent.com/7606389/65025745-d895cc00-d969-11e9-9b7a-bb26b8853df4.png)

All seems to stem from not recognizing the `* restrict` declarations... e.g. on L21:

![Screenshot 2019-09-17 at 4 40 59 PM](https://user-images.githubusercontent.com/7606389/65025805-f6633100-d969-11e9-9186-42028968133c.png)

`restrict` is ANSI standard:

https://en.cppreference.com/w/c/language/restrict

But it appears the RS linter thinks the command is creating a (pointer to a) variable _named_ `restrict`, as evidenced by the "error" on the next line:

![Screenshot 2019-09-17 at 4 42 32 PM](https://user-images.githubusercontent.com/7606389/65025952-2f9ba100-d96a-11e9-9924-311d4d6ec975.png)

And the next reference to the `sourceP` declared there:

![Screenshot 2019-09-17 at 4 43 46 PM](https://user-images.githubusercontent.com/7606389/65026051-56f26e00-d96a-11e9-8c3e-5879f3284107.png)

**Comment by kevinushey** [comment]
I suspect the problem is that we're parsing the code as C++ rather than C, and `restrict` is not part of any of the C++ standards.
