### ISSUE TITLE
uint8_t not recognized as valid type

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#5419]
A brother issue to #5418 about issues with the code linter for C code

It appears `uint8_t` is not recognized as a valid type in C:

![Screenshot 2019-09-17 at 4 49 21 PM](https://user-images.githubusercontent.com/7606389/65026429-1fd08c80-d96b-11e9-844a-e13636a8ad6a.png)

(this is in `data.table/src/fread.h`)

As near as I can tell this is a standard C type, e.g.:

https://en.wikipedia.org/wiki/C_data_types#Fixed-width_integer_types
https://www.badprog.com/c-type-what-are-uint8-t-uint16-t-uint32-t-and-uint64-t

I see it defined with an alias to `unsigned char` here:

```
grep -Enr "^typedef.*uint8_t;" /usr/include
/usr/include/_types/_uint8_t.h:typedef unsigned char uint8_t;
```

Since the code compiles, I'd expect RStudio to recognize the valid types...

The same applies to `uint_fast{8,64}_t`... in `data.table/src/fread.c`, these are used but flagged:

![Screenshot 2019-09-17 at 4 49 21 PM](https://user-images.githubusercontent.com/7606389/65029228-f6662f80-d96f-11e9-8bbd-42182f8b123c.png)

These are also standard -- I see a definition in `<stdint.h>` which is included via `#include "fread.h"`-->`#include <stdint.h>`

**Comment by kevinushey** [comment]
Likely same underlying cause as https://github.com/rstudio/rstudio/issues/5418 (parsing as C++ instead of C; and using default C++98 standard in this case)
