### ISSUE TITLE
Base R plot titles cutoff during inline rmarkdown rendering

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#5421]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Open `rmarkdown` document
2.  Create an _R_ code chunk with:

````
Sublines
```{r}
plot(1:10, 20:11)
title(line=2, cex=1, 'main title')
mtext(line=1, cex=0.85, 'subtitle')
mtext(line=0, cex=0.7, 'subsubtitle')
```

New line issue when creating a subplot
```{r}
plot(1:10, 20:11)
title('main title \n\n subtitle')
```
````

3. Watch the main title get cutoff.

### Describe the problem in detail

The RMarkdown rendering engine displays:

![Screen Shot 2019-09-17 at 12 21 13 PM](https://user-images.githubusercontent.com/833642/65064447-1680f900-d946-11e9-814a-f513cb2a0685.png)

While the viewer displays:

![Screen Shot 2019-09-17 at 12 24 02 PM](https://user-images.githubusercontent.com/833642/65064446-1680f900-d946-11e9-83af-1b94cc9c090c.png)

The latter is the preferred graph. 

Similarly for the next example, we have:

![Screen Shot 2019-09-17 at 2 04 24 PM](https://user-images.githubusercontent.com/833642/65071291-1ab41300-d954-11e9-8cda-906438be8590.png)

Where the preferred graph should be: 

![Screen Shot 2019-09-17 at 2 04 18 PM](https://user-images.githubusercontent.com/833642/65071292-1ab41300-d954-11e9-8b91-5aa167617fa4.png)

**Comment by ronblum** [comment]
Thank you @coatless for filing this! I can reproduce this in RStudio Desktop 1.2.1578 on MacOS 10.15 and RStudio Server 1.2.1578 on Red Hat 8.

**Comment by coatless** [comment]
@ronblum thanks. Could I also get the reproducible flag?

**Comment by ronblum** [comment]
@coatless Of course—thank you for reminding me. :)

**Comment by coatless** [comment]
@ronblum I added one more example to this issue ticket as I tried to hack around the limitation by using `\n` within the default `title()` function placement. The results were also problematic inline.

**Comment by ronblum** [comment]
@coatless Thanks! I also went back and checked, and this was an issue in 1.1.463, as well.

**Comment by kongjames** [comment]
@coatless @ronblum, I got the same cutoff as well. I've tried 4 different RStudio versions (1.2.5019 (newest), 1.1.463, 1.0.153). I'm using RStudio 3.6 framework. How do I get the knit to pdf work regularly without getting cut off on plot title?

<img width="735" alt="Screen Shot 2019-11-19 at 6 52 00 PM" src="https://user-images.githubusercontent.com/14840912/69196904-dd0f6a00-0afd-11ea-9078-c70d55d6383d.png">

**Comment by baderstine** [comment]
I recently switched from 3.5.3 to 3.6.3, upgraded RStudio as well.  I am also now finding that .Rmd documents that previously knitted to PDF fine are now having issues with cutoff plot titles and axis labels in the margins without newlines in them.  The default .Rmd document created in RStudio by File > New file > R Markdown... produces a base R plot whose y-axis label is cutoff in the PDF output.  `ggplot` titles are cutoff as well.  
[test.pdf](https://github.com/rstudio/rstudio/files/4651235/test.pdf)

R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.4
Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     yaml_2.2.1      Rcpp_1.0.4.6    rmarkdown_2.1  
 [7] knitr_1.28      xfun_0.13       digest_0.6.25   rlang_0.4.5     evaluate_0.14  

RStudio 1.2.5042

**Comment by danmaxis** [comment]
Hello there,
I'm still getting this issue, but came across some palliative solution

```
```{r }
par(mar=c(3,3,3,0)) ##This margin command should do the trick
ccf(x = df$C, y = df$P,lag.max = 10, main="foo") 
```

```
It was originally posted [here ](https://stackoverflow.com/questions/54119606/graphs-generated-in-r-markdown-are-too-big-and-getting-cut-off).

**Comment by baderstine** [comment]
I tracked down the bug to an older version of ghoscript.  Try updating ghoscript to a newer version.

**Comment by Kevrudd94** [comment]
> Hello there,
> I'm still getting this issue, but came across some palliative solution
> 
> ```
> par(mar=c(3,3,3,0)) ##This margin command should do the trick
> ccf(x = df$C, y = df$P,lag.max = 10, main="foo") 
> ```
> 
> It was originally posted [here ](https://stackoverflow.com/questions/54119606/graphs-generated-in-r-markdown-are-too-big-and-getting-cut-off).

Genius

**Comment by lursel** [comment]
> 
> 
> Hello there,
> I'm still getting this issue, but came across some palliative solution
> 
> ```
> par(mar=c(3,3,3,0)) ##This margin command should do the trick
> ccf(x = df$C, y = df$P,lag.max = 10, main="foo") 
> ```
> 
> It was originally posted [here ](https://stackoverflow.com/questions/54119606/graphs-generated-in-r-markdown-are-too-big-and-getting-cut-off).

Some notes for those who tried copy&pasting it didn't work:

1. `par` must come before the plotting commands, not after.
2. the third value is the margin-top value, the one relevant for this issue.
3. the default values are c(5,4,4,2) so start with those and try increasing
4. you might find that just setting the `par` command with the default fixes the issue without having to change values.
5. and lastly, only `par` is the fix, `ccf` isn't (should be clear but I thought I'd mention this)
