### ISSUE TITLE
“Tab to complete” switches between windows instead of completing paths - iPad

### ISSUE THREAD

**Issue by speio** [rstudio/rstudio#5426]
When attempting to autocomplete something (like a path of function), hitting tab switches between windows (ie, from the editor to the console for me in my current window setup). The same behavior results from Chrome for iOS on the iPad Pro and with Safari. 

Perhaps there is something hidden that already exists, but having a way to autocomplete would be great; autocompleting paths is rather integral to my normal coding routine.

**Comment by ronblum** [comment]
@speio Thank you for letting us know about this. Although we currently don't support the iPad, we hope to do so in the future. In fact, if you search for [current iOS requests and bugs](https://github.com/rstudio/rstudio/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aios), most of them were filed by one of our developers. So we'll definitely keep this issue mind as strive toward supporting iPads!

**Comment by gtritchie** [comment]
Just did a quick experiment and this seems to now be working with iPadOS (iOS 13.1) on my iPad Pro. If you are able to upgrade to iPadOS, please give it a try and let us know if this is solving this particular problem for you, too.

iPadOS includes a much improved Safari which is supposed to be closer in behavior to desktop Safari.

**Comment by gtritchie** [comment]
I'm going to resolve this as fixed by the improvements in Safari on iPadOS 13.1. I tried with both RStudio Server 1.2.1335 and a recent 1.3 build.

**Comment by ronblum** [comment]
Verified with iOS 13.3.1.
