### ISSUE TITLE
Container support for projects

### ISSUE THREAD

**Issue by kkmann** [rstudio/rstudio#5431]
# Rationale/Use-case

With increasing  complexity of analysis pipelines, reproducibility is becoming an issue. I found the most principled way to resolve this (even for R) to be a (singularity) container. It would be great to have the option of specifying a container (either remote resource or local file) to use with a particular rstudio project and run R sessions within that container. 

# Implementation 

Singularity is only fully supported on Windows via WSL 2 and Linux, so the installation of the container software would have to be managed by the user (presumably). Otherwise it should be pretty straight-forward since caching of remote resources (rocker/verse:latest) is handled by singularity itself. 

# Notes

This would integrate nicely with the new slurm workload integration for server pro since jobs could be run in the same container.

**Comment by ronblum** [comment]
@kkmann Thank you for the suggestion! We'll review it as part of our ongoing development of RStudio.

**Comment by jmcphers** [comment]
We are tracking this as a request over in our pro repo (which is private), so closing on the open source side.
