### ISSUE TITLE
IDE hang / laggy typing line containing lots of "**"

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5439]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.456
    OS Version      : macOS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

Create an R Markdown document, with the contents:

```
---
title: "Untitled"
output: html_document
---

** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** |
```

with `|` denoting the cursor position. Then, try typing a letter (e.g. `a`).

### Describe the problem in detail

The IDE briefly hangs before inserting the `a`

### Describe the behavior you expected

No hang.

### Notes

It looks like the problem lies within the tokenizer:

![Screen Shot 2019-09-19 at 3 08 26 PM](https://user-images.githubusercontent.com/1976582/65284742-5c2cf580-daef-11e9-8d40-7dc90b45b377.png)

This specific document structure is probably tripping some bad behavior in the regex tokenizer.

**Comment by kevinushey** [comment]
This is caused by our regular expression(s) here:

https://github.com/rstudio/rstudio/blob/9019818caee726bb8eeac9ecd45040fc920ec59f/src/gwt/acesupport/acemode/markdown_highlight_rules.js#L229-L237

In particular:

```
^[ ]{0,2}(?:[ ]?\*[ ]?){3,}\s*$
```

leads to catastrophic backtracking during the match.

**Comment by pascaloettli** [comment]
RStudio Edition : Desktop
    RStudio Version : 1.3.457
    OS Version      : Ubuntu 18.04.3 LTS
    R Version       : 3.6.1

Funnily on my computer, besides this, the cursor position is incorrect:

![Peek 2019-09-20 08-59](https://user-images.githubusercontent.com/6613954/65289341-36523000-db85-11e9-8154-966930ade713.gif)
