### ISSUE TITLE
Rpres non-local mathjax linking

### ISSUE THREAD

**Issue by cgrudz** [rstudio/rstudio#5446]
By default, when a ```template.rpres``` doc is compiled to an HTML presentation it creates the ```template_files``` directory with a local copy of Mathjax.  This is a reasonable choice given the need to make presentations offline, but it would be preferable if there was an option to link to to mathjax via the web as with
```{html}
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```
with some settings within the yaml frontmatter.  This kind of option appears to exist within RMarkdown document yaml, yet I cannot find a way to compile .rpres docs in a similar manner.  Please consider adding this feature as especially for web-hosted presentations, it would cut out the need to manually edit the HTML output to link externally, or otherwise to keep a local copy of Mathjax in the host page.

One additional note, it appears that the built-in .rpres Mathjax is in an older version (2.6.1?) while the current Mathjax is 3.x.  It would be nice to include the option to link to the web version of Mathjax while developing in Rstudio, also because of the differences in rendering between the older version and the current version.  I have found that the "live" slide layout can look very different due to differences in rendering in the old version locally and then linking to the current version in the output HTML for hosting the presentation online.

**Comment by ronblum** [comment]
@cgrudz Without knowing much about it, does the YAML option `mathjax` do what you're trying to accomplish? The example at https://bookdown.org/yihui/rmarkdown/html-document.html#mathjax-equations is
```
---
title: "Habits"
output:
  html_document:
    mathjax: "http://example.com/MathJax.js"
---
```

**Comment by cgrudz** [comment]
I'm not sure the exact difference between the .rpres file format, but by default it doesn't seem to accept ```output``` as a field in the yaml frontmatter.  If this is included in a default .rpres file, on the splash screen you get the output
```
Unrecognized slide field: output
```
I haven't  found another way yet of linking Mathjax like you can withing an RMarkdown doc.

Thanks for the  suggestion

**Comment by ronblum** [comment]
@cgrudz Perhaps it would help if I didn't try to provide you with syntax for `.rmd` when you're asking about `.rpres`. Sorry about that. :-/  I'll mark this as an enhancement to review as part of our ongoing development of RStudio.

Separately, regarding the MathJax version: we should open a separate ticket to update the version we're including. It looks like the latest general release version is 2.7.6, while 3 is still in beta, according to [the MathJax news page](https://www.mathjax.org/news/). Does that sound right?

**Comment by cgrudz** [comment]
Ah OK, that might explain some of the formatting differences I've experienced XD.  Thanks for the heads up.

**Comment by jmcphers** [comment]
We'd generally recommend using .rmd over .rpres as the latter works only inside RStudio and hasn't been actively developed for some time. .rpres uses RevealJS; you can get a very similar look and feel with the RevealJS R Markdown package.

https://github.com/rstudio/revealjs

**Comment by cgrudz** [comment]
OK, cool thanks for the heads up.  I'll test out converting more of my .rpres docs to .rmd with reveal.js options.

**Comment by ronblum** [comment]
Closing since due to inactivity. If this is still an issue, please let us know!
