### ISSUE TITLE
Customized keyboard shortcuts occasionally fail to work when a new R session starts

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5448]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1578 (latest RStudio preview), But I used to see this in 1.2.1335, as well.
    OS Version      : Server, Ubuntu 16.04.6 LTS, Xenial
    R Version       : 3.6.0

Sometimes when I start a new R session the customized keyboard shortcuts fail to work. In those cases, refreshing the browser will always make them work again.

I was not able to identify a definite set of steps to reproduce this issue; it happens only occasionally. I will keep an eye on it to hopefully find a definite reproduction path. But I thought I would post is for now, for the RStudio team to be aware of this possible issue, and for the rest of the community to second if they encounter a similar scenario.

**Comment by ronblum** [comment]
@hzarkoob Thank you for raising the issue. Perfectly reproducible examples are great to have, but we like to know about intermittent issues as well, so thanks!

What browser are you using, and does this happen with all customized shortcuts or just certain ones?

**Comment by hzarkoob** [comment]
@ronblum Thank you!

I am using Firefox 69.0 (64 bit). It seems like all customized shortcuts fail to work.

**Comment by ronblum** [comment]
@hzarkoob I tried two combinations: connecting Firefox to RStudio Server 1.2.5001, both from MacOS Catalina 10.15 to RStudio Server Ubuntu 18.04.3 and from Ubuntu 16.04.6 to RStudio Server on Ubuntu 16.04.6. I wasn't able to reproduce the problem. I can't reproduce the problem, although I did see an issue with having to enter the keyboard shortcut twice the first time, on lines with code.

I'll mark this as a bug to review.

**Comment by hzarkoob** [comment]
@ronblum I used Firefox 69.0 (64 bit) on both mac (Mojave, 10.14.6) and Windows 10 to connect to RStudio Server on a remote server with OS Ubuntu 16.04.6 LTS, Xenial. 

Even I do not always see the issue. Maybe once in every 20 instances. But, according to my experience, there is always a small chance that the customized keyboard shortcuts fail to work when a new R session starts. Happily, refreshing the browser always makes them work again.

PS. I guess I've also seen the issue of having to press the keyboard shortcuts twice the first time, on lines with code.

**Comment by hzarkoob** [comment]
@ronblum I typically store the workspace variables and load them when a new R session starts. I've noticed the issue mentioned above is more likely to happen when the workspace variables are large, in gigabits, for example, as compared to the case where there are no saved workspace variables to be loaded, and thus the R session starts very lightly.
