### ISSUE TITLE
RStudio Server: "Stay signed in" has no effect

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#5449]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.404-2
    OS Version      : CentOS
    R Version       : 3.6.1

### Steps to reproduce the problem

Log in, let the session timeout or log in after a reboot -> Log in window comes up again even though "stay signed in" was checked

### Describe the problem in detail

This applies across machines (always using the same browser) if the session has not been used within a few hours.
This also applies if the timeout for a session has been set to Inf.

### Describe the behavior you expected

Skipping the log in window as the browser remembers the login credentials.

**Comment by ronblum** [comment]
@pat-s Thank you for letting us know. We'll review the issue as we continue development of RStudio.

**Comment by kfeinauer** [comment]
In RStudio v1.3, I made the auth timeout more aggressive to address security concerns that sessions could be hijacked due to users being able to stay signed in for so long.

By default, a new auth parameter is in effect in `/etc/rstudio/rserver.conf`:

```
auth-timeout-minutes=60
```

This will cause users to be automatically signed out if they have been `idle` (have not interacted with the IDE) for 60 minutes. You can raise this value to something you see fit, or you can use the legacy behavior from v1.2 and before via the following in `/etc/rstudio/rserver.conf`:

```
# use legacy auth behavior
auth-timeout-minutes=0
auth-stay-signed-in-days=30
```

The legacy behavior will not force users to sign in again when going idle, and will allow them to stay signed in to the product for many days.

**Comment by jmcphers** [comment]
Given the new behavior, I think that the *Stay signed in* checkbox is somewhat confusing. I think we should do one of two things:

1. Remove the checkbox unless `auth-timeout-minutes` is 0 (in other words, only show it when when we're in legacy mode), or:
2. Reword the checkbox to be clearer. We could for example have it read "Sign out automatically when browser closes". This would, of course, invert the current behavior, but I think it'd be clearer.

**Comment by kfeinauer** [comment]
I think we could do 1) above. I think 2) is confusing as well because it breaks the user preconception of what a check box on login would normally do.

Do you think we should persist the auth when the browser closes for 1) above? Since the `auth-timeout-minutes` option is very strict with expiration time, I think this is fine, and I see value in being able to automatically return to your session if your cookie has not yet expired.

**Comment by jmcphers** [comment]
After thinking it through I'm not sure whether we can justifiably remove the box. Without it the only way to sign out is to click the "sign out" button. That's *probably* okay but if you're using a public computer and/or your admin has a less strict expiration time (easily configured into the hours) you might want a way to make sure session cookies are used.

Maybe a more subtle wording change, along with a note letting users know the timeout interval?

     Your will be automatically signed out after 60 minutes of inactivity.
     [ ] Stay signed in when browser closes

What do you think?

**Comment by kfeinauer** [comment]
> After thinking it through I'm not sure whether we can justifiably remove the box. Without it the only way to sign out is to click the "sign out" button. That's _probably_ okay but if you're using a public computer and/or your admin has a less strict expiration time (easily configured into the hours) you might want a way to make sure session cookies are used.
> 
> Maybe a more subtle wording change, along with a note letting users know the timeout interval?
> 
> ```
>  Your will be automatically signed out after 60 minutes of inactivity.
>  [ ] Stay signed in when browser closes
> ```
> 
> What do you think?

I think that makes sense. I'll make that change.

**Comment by pat-s** [comment]
I had no idea what that issue would trigger - thanks guys 🚀

**Comment by AltfunsMA** [comment]
Hi, 
I was just confronted with this issue after finally upgrading to RStudio Server 1.3.959; I'd be keen to retain the old behaviour. Is the rserver.conf a permanent workaround? I couldn't find any confirmation elsewhere (notably [here](https://docs.rstudio.com/ide/server-pro/server-management.html)).

**Comment by kfeinauer** [comment]
@AltfunsMA This section explains it a little more: https://docs.rstudio.com/ide/server-pro/authenticating-users.html

Basically, if you want the old auth timeout behavior, set the following in `/etc/rstudio/rserver.conf`:

```
auth-timeout-minutes=0
auth-stay-signed-in-days=30
```

**Comment by zxy1555847** [comment]
@kfeinauer hello！
I had write my /etc/rstudio/rserver.conf as you said，and now my /etc/rstudio/rserver.conf is as follows：

www-address=0.0.0.0
rsession-which-r=/usr/bin/R
www-port=8787
auth-timeout-minutes=0
auth-stay-signed-in-days=30

however，i still see this sentence：
You will automatically be signed out after 60 minutes of inactivity.


so，can you help me to avoid outline and Skipping the log in window as the browser remembers the login credentials？？

**Comment by kfeinauer** [comment]
@zxy1555847 Once you update the configuration file, you need to restart rstudio-server:

`sudo rstudio-server restart`

Then, once you go back to the sign in page, you should see the notice disappear:

![Screen Shot 2020-07-21 at 9 56 55 AM](https://user-images.githubusercontent.com/28230621/88070656-89e03200-cb38-11ea-9181-17a733409f38.png)

If you check the box to stay signed in, you should no longer be booted out until 30 days after your sign in.

**Comment by zxy1555847** [comment]
ok，
thank you very much！i have restart and it works！！

**Comment by mirekphd** [comment]
> you can use the legacy behavior from v1.2 and before via the following in `/etc/rstudio/rserver.conf`:
> 
> ```
> # use legacy auth behavior
> auth-timeout-minutes=0
> auth-stay-signed-in-days=30
> ```
> 
> The legacy behavior will not force users to sign in again when going idle, and will allow them to stay signed in to the product for many days.

And I can confirm that it is possible to perform such "rollback" of this well-intentioned feature in the Open Source edition too.

**Comment by zxy1555847** [comment]
yeah
I had solved this problem last time also in this method，
thank you very much for your attention

**Comment by cdriveraus** [comment]
The 60 minute warning message could be more informative, had quite a headache with my work shutting down even though from my perspective the system was not 'idle'...
