### ISSUE TITLE
`r in-line expression evaluated even in `` quoted context

### ISSUE THREAD

**Issue by kortschak** [rstudio/rstudio#5450]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : linux (ubuntu)
    R Version       : 3.6.1

### Steps to reproduce the problem
knit the following Rmd
```
---
title: "backticks inside your backticks..."
output: html_document
---

This shows that the in-line code mark is evaluated at a higher preference than the wrapping backticks:
this `` `r nrow(c())` `` should be rendered as `<code>` looking something like this `` ` r nrow(c())` ``
(without the space needed to break the `` `r`` token).
```

### Describe the problem in detail
The internal `` `r expression` `` is evaluated before the enclosing double backticks. This makes it impossible to express an inline R expression as quoted code (the whole point of the double backticks in Markdown).

### Describe the behavior you expected
I expect that the enclosing double backticks should take priority over the in-line expression evaluation. This is the more likely intention behind writing this sequence of bytes in a file and there is no other way to obtain knitted output. If a user did want generated `<code>`-wrapped in-line expressions, this can be obtained exactly that way, by ``<code>`r expression`</code>``.

**Comment by ronblum** [comment]
@kortschak Thank you for reporting the issue. I can reproduce this in RStudio Desktop 1.2.5001 on MacOS Catalina 10.15. This might be an issue with R Markdown, not RStudio, but I'll mark it as a bug for now.

Reference: https://bookdown.org/yihui/rmarkdown/markdown-syntax.html#inline-formatting

**Comment by kevinushey** [comment]
I'm fairly sure this is an issue with `rmarkdown` -- you can reproduce the issue independent of RStudio. For example, with the document:

`````
---
title: "backticks inside your backticks..."
output:
  html_document:
    keep_md: true
---

Don't render me: `` `r 123456` ``
`````

I see the following after render:

`````
$ cat test.md
---
title: "backticks inside your backticks..."
output:
  html_document:
    keep_md: true
---

Don't render me: `` 1.23456\times 10^{5} ``
`````

No idea where the `\times 10^{5}` is coming from, though...

**Comment by kortschak** [comment]
You all are aware that issue can be moved between repos?
