### ISSUE TITLE
options(max.print = <large>) can hang IDE when printing large data.frames in Notebook chunks

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5451]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.455
    OS Version      : macOS 10.14.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Try executing the following chunk in an R Notebook:

`````
---
title: "Untitled"
output: html_notebook
---

```{r}
library(nycflights13)
options(max.print = 1E6)
nycflights13::flights
```
`````

Then, try saving the document.

### Describe the problem in detail

The IDE hangs.

### Describe the behavior you expected

No hang.

### Notes

Likely due to the fact that we attempt to persist the number of rows as requested by `max.print` here:

https://github.com/rstudio/rstudio/blob/17e7aefbd45fdae316f47fc40cedf88148a5b765/src/cpp/session/modules/NotebookData.R#L81

I think we should enforce a maximum of 1000 rows.

**Comment by ronblum** [comment]
Note: This is also an issue with RStudio Desktop 1.1.463, 1.2.1335, and 1.2.5001 (MacOS Catalina 10.15 with R 3.5.3). On RStudio Server 1.2.5001, running the chunk aborts after several minutes (Ubuntu 18 with R 3.6.1).
