### ISSUE TITLE
periodic set_client_state method called when IDE is idle after Find in Files call

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5455]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.455
    OS Version      : macOS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

Open the IDE, then execute a Find in Files search. Leave the IDE idle for a while (~30 seconds) and then open the request log (<kbd>Ctrl + `</kbd>).

### Describe the problem in detail

The IDE has been repeatedly calling back with the same method to set client state regarding the Find in Files state.

![Screen Shot 2019-09-24 at 9 34 23 AM](https://user-images.githubusercontent.com/1976582/65531507-e938cb80-deae-11e9-97c5-e4557459b68f.png)

![Screen Shot 2019-09-24 at 9 35 00 AM](https://user-images.githubusercontent.com/1976582/65531512-eb9b2580-deae-11e9-8735-cd63006f9470.png)

### Describe the behavior you expected

It should be unnecessary for the session to ping the client repeatedly when the Find in Files state has not changed.

Note that there is no real observable problem with this behavior; however, it would be nice to avoid unnecessary RPC requests.

**Comment by jmcphers** [comment]
@melissa-barca Worth looking at when you start getting into the find-in-files code.

**Comment by melissa-barca** [comment]
Fixed with #5832
