### ISSUE TITLE
Strange styling of main menu when using keyboard

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5456]
### System details

    RStudio Edition : Server
    RStudio Version : anything after https://github.com/rstudio/rstudio/pull/5452
    OS Version      : Web Browser (using Chrome but probably any)
    R Version       : any

### Steps to reproduce the problem
- load RStudio server
-  use keyboard shortcuts to navigate main menu, e.g. Ctrl+Alt+F to open File menu, then left / right arrows to select different top-level menus
- use down-arrow to go into a popped-up menu

### Describe the problem in detail
- get unnecessary and incorrect focus highlights on entire menu bar, and entire popup

### Describe the behavior you expected
- existing menu styling already indicates where focus is by virtue of the selected menu highlight

![2019-09-24_10-48-08](https://user-images.githubusercontent.com/10569626/65536899-1c805800-deb9-11e9-96fb-52697a88a2da.png)

![2019-09-24_10-50-46](https://user-images.githubusercontent.com/10569626/65536953-31f58200-deb9-11e9-81ef-4509d39d323c.png)

**Comment by adamconroy** [comment]
https://github.com/rstudio/rstudio/commit/10f948ce64db62e7a09e16cfdb255c7286d50f60

**Comment by gtritchie** [comment]
Somewhat improved, but still not ideal. Now you get a focus rectangle around the entire menubar or dropdown menu when using the keyboard. No need to show focus rectangles on the menus at all, since they already give sufficient visual indication when used via keyboard.

![2019-10-09_19-51-11](https://user-images.githubusercontent.com/10569626/66535394-4ac38180-eace-11e9-8b89-04faa63c441a.png)
![2019-10-09_19-50-51](https://user-images.githubusercontent.com/10569626/66535399-4d25db80-eace-11e9-89a8-b49815dad82f.png)
