### ISSUE TITLE
Package build warning should be fatal error

### ISSUE THREAD

**Issue by ModellingDairyNZ** [rstudio/rstudio#5459]
I am building a package in one session of RStudio, which is loaded and used in another session. The build log gives an unobtrusive warning, but I think it would be better if this was highlighted or an error. I wasted half a day before realising that my package was not updating. Thanks.

```
installing to C:/R/R-3.5.3/library/BASGRA/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\BASGRA.dll to C:\R\R-3.5.3\library\BASGRA\libs\x64\BASGRA.dll: Permission denied
```

```
R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

```
RStudio
Version 1.2.1335
```

**Comment by woodwards** [comment]
Oops it was actually me who raised this issue. I was logged in to the wrong Github account.

**Comment by ronblum** [comment]
@woodwards No sweat! And thank you for raising this. I'll mark this as enhancement—upgrading the warning to an error—to review as we continue development of RStudio.
