### ISSUE TITLE
Reformat code does not handle tidyeval `{{ }}` operator correctly

### ISSUE THREAD

**Issue by JiaxiangBU** [rstudio/rstudio#5461]
I come up with this feature on the [community](https://community.rstudio.com/t/reformat-code-does-not-handle-tidyeval-operator-correctly/39076). [kevinushey](https://community.rstudio.com/u/kevinushey ), one of the RStudio Employee, suggests me I file a feature request here. I post it here again.

Here is my customized function.

```r
calc_x <- function(df, word, beta) {
    df %>%
        mutate(sql_text = map2_chr(
            {{word}}, {{beta}},
            ~ paste(word, beta)
        ))
}
```

When I use the <button>reformat code</button> feature, the functon is reformatted in this way.

```r
calc_x <- function(df, word, beta) {
    df %>%
        mutate(sql_text = map2_chr({
            {
                word
            }
        }, {
            {
                beta
            }
        },
        ~ paste(word, beta)))
}
```

How to maintain the `{{}}` unchanged?

I know there are some packages to deal with it and simply write an add-in with the shortcut is a choice. However, I think it is a fundamental feature for this button `Reformat code` in RStudio software.

**Comment by ronblum** [comment]
@JiaxiangBU Thank you for filing the request here! We'll review your suggestion as we continue development of RStudio.
