### ISSUE TITLE
Should be able to use git-bash terminal when using portable git

### ISSUE THREAD

**Issue by WilDoane** [rstudio/rstudio#5462]
There doesn't appear to be a way to specify a custom location for the git-bash command for cases such as needing to use portable git.

Even when the portable git executable has been selected in the Git/SVN options tab, git-bash is still not available for use as a terminal.

(Windows 10, limited user account, RStudio Desktop 1.2.1335)

**Comment by ronblum** [comment]
@WilDoane Thank you for raising this issue. Does changing the Terminal executable and then opening up a new terminal do what you're looking for?
- Tools -> Global Options -> Terminal -> Custom shell binary

**Comment by WilDoane** [comment]
Using windows 64bit RStudio 1.2.5001 tar.gz, running from the uncompressed archive, Custom shell binary isn’t an option. (Powershell and command prompt only)
  
  
  

      
  

  
  
>

**Comment by ronblum** [comment]
@WilDoane I apologize—I was using the MacOS instructions. On Windows, under Terminal -> Shell, I have Git Bash as an option, but I'm likely using a different version Git. Can you direct me to what you're using?

**Comment by WilDoane** [comment]
Git portable for windows, available from https://git-scm.com/download/win (64 bit portable link)
  
  
  

  
Used on a system with no other git installation and no admin privileges.   
  
  
  
  

  
  
>

**Comment by edavidaja** [comment]
I have a similar issue--I've installed R, RStudio, and Git with [Scoop](https://scoop.sh/). Rstudio finds PowerShell and WSL, but not git bash.

The [Terminal help page](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal#appendixa) indicates that there's no support for setting a custom shell in the Windows Desktop.

**Comment by gtritchie** [comment]
The ability to specify a custom shell on Windows was added in v1.3. You can try a daily build if you want to give it a try. https://dailies.rstudio.com/rstudio/oss/windows/

Standard disclaimer: "Daily builds are intended for testing purposes, and are not recommended for general use. For stable builds, please visit rstudio.com."

**Comment by edavidaja** [comment]
This can definitely be closed now.
