### ISSUE TITLE
User rstudio-server not added to rstudio-server group during install on OpenSUSE

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#5464]
```
RStudio Edition : Server 
RStudio Version : 1.3.456-6 (Professional)
OS Version      :  SUSE Linux Enterprise Server 12 SP4 
R Version       : 3.2.5 and 3.6.1
```

From @tmcduff:

### Steps to reproduce the problem

This is observed pretty much right after the install and is reproducible. I don't think I have a configuration issue, but have included a diagnostic report just in case.

### Describe the problem in detail
Console:

Command:
sudo id rstudio-server
uid=491(rstudio-server) gid=100(users) groups=100(users)

ec2-user@ip-10-0-0-124:~> sudo rstudio-server verify-installation
23 Sep 2019 22:22:08 [rserver] ERROR system error 13 (Permission denied) [description=Program user rstudio-server does not belong to group rstudio-server.

from var/log/messages:
ERROR system error 13 (Permission denied) [description=Program user rstudio-server does not belong to group rstudio-server.|||Please ensure user and group mappings are correct.]; OCCURRED AT: rstudio::core::Error rstudio::server::session_proxy::overlay::runVerifyInstallationSession(rstudio::core::system::user::User&, bool*) /var/lib/jenkins/workspace/IDE_pro-pipeline_master/src/cpp/server/ServerSessionProxyOverlay.cpp:1326; LOGGED FROM: int main(int, char* const*) /var/lib/jenkins/workspace/IDE_pro-pipeline_master/src/cpp/server/ServerMain.cpp:631

### Describe the behavior you expected

The `server-verification` should not error after install. The `rstudio-server` user should be in the `rstudio-server` group.

**Comment by tmcduff** [comment]
Verified: 1.3.731-1
