### ISSUE TITLE
Tab width in global settings not followed in .Rmd files

### ISSUE THREAD

**Issue by shirewoman2** [rstudio/rstudio#5468]
I'm seeing odd behavior when setting the tab width, but only in R markdown documents. This may be related to issue #4454 and maybe issue #5454. 

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.5001
    OS Version      :  Windows 10
    R Version       :  3.6.0

### Steps to reproduce the problem

In RStudio, go to Tools --> Global Options --> Code --> Editing --> Tab width
Don't change anything here (I'm starting with a tab width that I'd set previously to 6). Click apply or ok. 

Inside a .Rmd file, attempt to indent code automatically using Ctrl + i or just by typing with a line of code going to the next line. Indentation will be 3 spaces regardless of the number that was listed. Inside a .R file, indentation will be the number listed in the setting, so 6 in my case. 

For a second time, go to Tools --> Global Options --> Code --> Editing --> Tab width
Set the tab width to some other number. Click ok. 

In both .R and .Rmd files, the tab width will be this new number you've just set. 

### Describe the problem in detail

The tab width is followed in .R documents fine, but it's not followed in .Rmd files unless you change it in global settings every time you open a new session of RStudio. Based on comments I've read elsewhere, this could be a conflict between project options and global options, but I'm not *in* a project when I observe this behavior. Also, I opened my most recent project, and, there, I also had the tab width set to 6 spaces rather than 3.  

### Describe the behavior you expected

I expected the tab settings to be followed regardless of which type of R file it was. 

1. The output of sessionInfo() 
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 plyr_1.8.4     tools_3.6.0    Rcpp_1.0.1    

2. The R code in question 
Irrelevant, really, but here's a simple example: 
x <- 5 +
   6

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
Attached

Thank you for taking
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3654365/diagnostics-report.txt)
 the time to file an issue!  -->

**Comment by kevinushey** [comment]
Does it make a difference if you disable auto-detection of code indentation, as described here?

https://github.com/rstudio/rstudio/issues/5454#issuecomment-534660929

**Comment by shirewoman2** [comment]
Ah, yes! If I disable that, then it works without having to change the number for tab width; it reads the tab width number that's already there.

**Comment by ronblum** [comment]
Enhancement: make it clear in the UI what indentation settings are being set and used for a particular file.

**Comment by dongzhuoer** [comment]
The same issue on Ubuntu 20.10, unless I disable "auto-detection of code indentation", `.Rmd` file would ignore the "Insert spaces for tab" option
