### ISSUE TITLE
./install-dependencies-debian --exclude-qt-sdk doesn't actually exclude Qt installation

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#5471]
### System details

    RStudio Edition : Server
    RStudio Version : Compiled
    OS Version      : Debian Stretch
    R Version       : 3.6.1

### Steps to reproduce the problem
* Run `./install-dependencies-debian --exclude-qt-sdk` on terminal

### Describe the problem in detail
--exclude-qt-sdk flag is not being passed to install-dependencies-stretch

### Describe the behavior you expected
Qt not being installed

**Comment by ronblum** [comment]
@andresrcs Thank you for raising this. I'm marking this as a bug to review during ongoing development of RStudio.
