### ISSUE TITLE
Incorrect position of the cursor when line contains lots of "**"

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#5474]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.469
    OS Version      : Ubuntu 18.04.3 LTS
    R Version       : 3.6.1

### Steps to reproduce the problem
Follow up of #5439, with exactly the same steps by @kevinushey (I take the liberty to reproduce a verbatim copy, as it perfectly describes the problem)

Create an R Markdown document, with the contents:

```
---
title: "Untitled"
output: html_document
---

** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** |

```
with | denoting the cursor position. Then, try typing a letter (e.g. a).

### Describe the problem in detail
The position of the cursor is incorrect, leading to some unexpected behaviour:

![Peek 2019-09-27 11-39](https://user-images.githubusercontent.com/6613954/65738042-7e3ffc80-e11b-11e9-8c90-e28c5e546d98.gif)

### Describe the behavior you expected
Correct position of the cursor

**Comment by kevinushey** [comment]
What font are you using? If you're using FiraCode, can you also try installing the latest release from https://github.com/tonsky/FiraCode?

**Comment by pascaloettli** [comment]
Yes, it was related to the font. I forgot I wasn't using the default one. Problem solved.
