### ISSUE TITLE
Huge R logo in documentation (v 1.3)

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#5475]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.469
    OS Version      : Ubuntu 18.04.3 LTS
    R Version       : 3.6.1

The R logo embedded in documentation is exaggeratedly huge in the help pane.

### Steps to reproduce the problem
Start the HTML version of R's online documentation:

    help.start()

![bitmap](https://user-images.githubusercontent.com/6613954/65748747-94f84a80-e13f-11e9-9b21-12afaf5abd69.png)

**Comment by pascaloettli** [comment]
Update: it started with version `1.3.468`

**Comment by jmcphers** [comment]
This is because the new filter that allows us to adjust the help font size is replacing (rather than amending) the font size to the R.css file.

![image](https://user-images.githubusercontent.com/470418/66528770-f8766680-eab5-11e9-9f98-4a84b142c91f.png)
