### ISSUE TITLE
add --vanilla flag to default build command

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#5477]
Despite the prevailing commentariat admonishments to not use a `.Rprofile` for much of anything, some of us do use it, because we use R as an interactive tool too and a .Rprofile makes that easier. It would be nice if we could pass some additional flags to rstudio's package build commands to help enable us to use R as both an interactive tool and a development environment.

For example, the default build command looks like this:
![image](https://user-images.githubusercontent.com/8462255/65779057-07a00080-e115-11e9-85bb-2827990d97ca.png)

Meanwhile adding a `--vanilla` flag makes it work:
![image](https://user-images.githubusercontent.com/8462255/65779330-8c8b1a00-e115-11e9-85c1-7e2800510fd3.png)

Unfortunately, the current package build options does not allow us to add any flags that go between `R` and `CMD INSTALL`

![image](https://user-images.githubusercontent.com/8462255/65779404-b04e6000-e115-11e9-81f0-9cfa03b4f7fa.png)

It would be nice if the default build command added a `--vanilla` flag by default. Probably adding `R_DEFAULT_PACKAGES=NULL` as an argument also makes sense. Or, at least, an option to add these flags to ensure that build & install actions are with 'clean' R session.

**Comment by kevinushey** [comment]
Newer versions of R allow you to pass `--use-vanilla` to request `--vanilla` be passed down to child processes during build / install. Is that sufficient in your case?

**Comment by t-kalinowski** [comment]
@kevinushey Thank you! I did not know about the `--use-vanilla` flag. That's sufficient for my needs.

(I still think it should probably be a default...)

**Comment by kevinushey** [comment]
Lots of users do things like adjust library paths in their .Rprofile, so it wouldn't be a good idea to change this behavior.

If you aren't aware, you can guard code in your .Rprofile with something like:

```
if (interactive()) { ... }
```

if you have some code you'd like to only run in interactive R sessions.
