### ISSUE TITLE
Ongoing issues with "the file XXX has changed on disk" using cloud storage

### ISSUE THREAD

**Issue by ConalMonaghan** [rstudio/rstudio#5483]
There is ongoing issues with the error: "the file XXX has changed on disk. Do you want to reload the file from disk and discard your unsaved changes". There have been several solutions prompted for this error, however, it still occurs often: [#3554](https://github.com/rstudio/rstudio/issues/3554)  [#3489](https://github.com/rstudio/rstudio/issues/3489). 

Specifically, the error occurs when the rstudio/R files are stored on an cloud platform, e.g., Google Drive or Dropbox. When I move the file to the local hard-drive. This error stops. 

The error is often instantly re-prompted. ie. as soon as you close the error dialogue box, it reappears forcing hard closing (control + Alt + delete). 

Is there a workaround or do we need developer adjustments to the Rstudio code?
Cheers,
        Conal

**Comment by kevinushey** [comment]
The issue here normally is that RStudio + cloud storage solutions are fighting over access over files within the `.Rproj.user` folder. If you can find a way to force your cloud storage provider to ignore that folder, issues should go away.

**Comment by pnojai** [comment]
There are two open duplicates of this issue. I am game to give the suggestion from @kevinushey a try, but I don't understand the meaning of "forc[ing] your cloud storage provider to ignore that folder."

My own storage is not in the cloud, but it is remote. It is a Synology NAS on my network.

**Comment by aaelony-aeg** [comment]
what is the status of this issue?  I am seeing the same issue via Azure with Databricks RStudio.

**Comment by przemo** [comment]
> My own storage is not in the cloud, but it is remote. It is a Synology NAS on my network.
Same issue with Synology.
