### ISSUE TITLE
[Server Pro] Getting signed out when switchting between sessions

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#5485]
### System details

    RStudio Edition : Server Pro
    RStudio Version : Version 1.3.465-2
    OS Version      : centOS 7
    R Version       : 

### Steps to reproduce the problem

1. Log into a session
2. Switch browser tab
3. Log into 2nd session
4. Getting logged out from first session in the moment of logging in to the second one

### Describe the behavior you expected

Staying logged in in both session

`server-multiple-sessions=1` is set in `rserver.conf`.

**Comment by kfeinauer** [comment]
I cannot reproduce this behavior. Could you create a video of the behavior so we can see what's going on here?

**Comment by pat-s** [comment]
It's on the list :)

**Comment by jmcphers** [comment]
I am closing this since it's > 2 weeks old and we don't have a repro.

@pat-s, as a Pro customer you're entitled to customer support! If you're still having trouble with this, please email <support@rstudio.com> and we'll investigate/troubleshoot.

**Comment by pat-s** [comment]
@jmcphers Yes, sorry I couldn't get to it. But also I realized that the issue does not apply anymore after I've updated some days ago to the latest daily. Before I was also on a daily which might have had some issues. 

Sorry again for being late here.

**Comment by jmcphers** [comment]
No worries, thank you for supporting our work!
