### ISSUE TITLE
Problem with starting RStudio by clicking on a link to an R-file.

### ISSUE THREAD

**Issue by namarkus** [rstudio/rstudio#5492]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 1.2.1335, Build 1379 (f1ac3452)
    OS Version      :  Windows 10 x64 (build 15063)
    Platform         :   x86_64-w64-mingw32/x64 (64-bit)
    R Version       :    R version 3.6.1 (2019-07-05)

### Steps to reproduce the problem
Open link to an R-file on a fileserver. The adress of this link (eg. in an e-mail or Word document) represents the absoulte path to the file on a fileserver.

To easier reproduce this problem, the problem can be inducted by starting RStudio from Windows Commandline with path to R-file as parameter:

**case A** (path to fileserver and share is mapped to a windows drive letter (eg P):
`C:\Program Files\RStudio\bin> rstudio.exe P:\MyRscripts\MyRfile.R`

**case B** (using absolut path to R-file):
`C:\Program Files\RStudio\bin> rstudio.exe \\ServerName\Share\MyRscripts\MyRfile.R`

### Describe the behavior you expected
RStudio should start up and open the R-script file.

### Describe the problem in detail
**case A works:**
RStudio starts up an the file "MyRfile.R" ist opened in a tab.

**case B doesn't work:**
Error message box says:

> R Message
> Fatal error: Unexpected exception: rstudio_boost::filesystem::status:Access is denied: "//ServerName/Share"
> 

after clicking "OK" button a second error box appears:

> RStudio
> The R session had a fatal error.
> Unexpected exception: rstudio_boost::filesystem::status:Access is denied: "//ServerName/Share"
> 

after that a error message box with a little bomb-icon appears:

> R Session Aborted
> 
> R encountered a fatal error, The session was terminated 
> 

The main problem is, that RStudio somehow remembers that file as already opened. When I close RStudio and reopen it, the same error messages as above appear again.

The only solution I have so far is to delete "RStudio-Desktop" Folder in user appdata directory.

**Comment by kevinushey** [comment]
I'm not able to reproduce -- I can successfully open a file on a network share as in your **case B** example.

Is it possible that access to this network share is restricted in such a way that RStudio is not allowed to directly access it?

**Comment by jmcphers** [comment]
Haven't heard back in a couple months and we can't repro, so closing. Feel free to reopen if you're still seeing this with the latest version of RStudio (1.2.5019).
