### ISSUE TITLE
Keyboard shortcut for exclusively showing "Source" and "Console" panes

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5498]
While working with RStudio, one would frequently need to work with a pane structure including only "Source" and "Console" panes. That will be used, for example, when sourcing different parts of the source file step by step and examining the outputs of each step in the console.

Because of the frequent use of the above pane structure, I think it would be helpful to have a keyboard shortcut that always forces the pane structure to follow this structure regardless of the currently displayed pane structure.

**Comment by ronblum** [comment]
@hzarkoob Thank you for the suggestion. Are you looking for something that combines "Zoom Source" (<kbd>CTRL-SHIFT-1</kbd>) and "Zoom Console" (<kbd>CTRL-SHIFT-2</kbd>) , into something like "Zoom Source and Console"?

**Comment by hzarkoob** [comment]
@ronblum That is right!

A side note. One can get the above pane structure if they manually hide the two panes on the left side (I assume we are working with the default pane structure) and keep only the Source and Console panes. Then, if they keep pressing <kbd>CTRL-SHIFT-1</kbd> (or <kbd>CTRL-SHIFT-2</kbd>), the pane structure keeps alternating between "Source only" (or "Console only") and "Source and Console together." This is a good thing and already works in many situations. But it still will be very helpful to have a keyboard shortcut that helps to display the suggested pane structure (as you mentioned, it can be called "Zoom Source and Console") _regardless_ of the current pane structure and the pane structure immediately before the current pane structure.

**Comment by ronblum** [comment]
@hzarkoob Clever workaround!

**Comment by maciejmotyka** [comment]
Yes, please! I'm also constantly closing the right-hand side panels by dragging the divider. It's (almost) the only thing that forces me to use a mouse when working in Rstudio. Many people don't like or have trouble using a mouse.

**Comment by morrowcj** [comment]
I would like to suggest that, in the same way `ctrl+shift+1` toggles between focus source and return focus to previous layout (as @hzarkoob points out), it would be useful if `ctrl+shift+alt+0`  would toggle between show all windows (as it currently does) and back to the previous layout (source and console, for example).

**Comment by jmcphers** [comment]
Good news, this is now part of RStudio!

![image](https://user-images.githubusercontent.com/470418/107568989-a27b6c80-6b9c-11eb-990c-ff25d518f2c2.png)

**Comment by morrowcj** [comment]
Wow, this is great! Thanks for the update. I'll check it out.
