### ISSUE TITLE
Global shortcut/icon to run Shiny app when Shiny .Rproj open

### ISSUE THREAD

**Issue by charliejhadley** [rstudio/rstudio#5501]
I regularly find myself building Shiny apps with code split across multiple script files. It's inconvenient having to switch to the `ui.R` or `server.R` file to run the app.

I would like the "Run App" icon to show under the following conditions:

1. User is in an RStudio project
2. The project contains `server.R` and `ui.R` file
3. The user has a script file selected

I would not expect the "Run app" icon to show if:

A) The project contains only an app.R file, as it is less likely that the project is exclusively for a Shiny app
B) The user has an .Rmd file selected within a project containing `ui.R` and `server.R` file
C) The user is building a Shiny app with `{golem}`, as this is a beast with its own shortcuts and opinionated workflow.

Thanks for building RStudio, it's so much more than an IDE 🔥

**Comment by jmcphers** [comment]
Thanks for taking time to file this; agree that it'd be helpful. I don't think we have an issue tracking this, but you're certainly not the first to suggest it (a few folks at RStudio have suggested the same).

**Comment by martinjhnhadley** [comment]
Glad to hear internal folks have suggested it, I couldn’t see an existing
issue for it.

There are a lot of corner cases, including running a different app from
what the user is expecting to run. Which isn’t an acceptable outcome. So
I’m happy if this ends up being rejected as not beneficial to users.

Cheers,

Martin
