### ISSUE TITLE
A question when I am running my chunk in r markdown. The result will not be shown below but can be shown in the console

### ISSUE THREAD

**Issue by leowu97** [rstudio/rstudio#5502]
![1570102143759](https://user-images.githubusercontent.com/47913901/66123229-1a826b80-e614-11e9-9907-9f2348efd1b8.jpg)

A question when I am running my chunk in r markdown. The result will not be shown below but can be shown in the console

As an example, when I run my chunk, usually all my results will be output below the chunk. But commands such as print(), head(), tail(), simply any command to manifest data will turn out to nothing. However, if I run it in the console, it does give me a proper outcome.
 
I had tried various ways to reset the output style in the "global options", but all approaches seem invalid. Does anyone know how to solve it?
BTW, I don't want my result to be shown in the console, but just let it be shown below my chunks.

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
