### ISSUE TITLE
RStudio view window defected when using two monitors with different resolution

### ISSUE THREAD

**Issue by JustMohsen** [rstudio/rstudio#5503]
Hello,

I have a TOSHIBA Satellite P55W-C laptop with a 2160p screen resolution. when I connect my laptop to an external monitor with a 1080p resolution, RStudio doesn't work properly on the monitor. It shows a black space at the top (image ). The problem is not just the appearance, but everything is shifted the same distance to the bottom, every mouse movement or click takes action some distance below.

Thank you.

![image](https://user-images.githubusercontent.com/53262801/66150353-f9555700-e5e2-11e9-9126-59f95f4bd818.png)

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by kevinushey** [comment]
Do things work better if you switch to software rendering? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by JustMohsen** [comment]
Just tried it and it worked, thanks a lot. Problem solved
