### ISSUE TITLE
Find in Files deletes pattern if Regular Expression is checked

### ISSUE THREAD

**Issue by CGMossa** [rstudio/rstudio#5504]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.474
    OS Version      :  Windows 10 x64 (build 17134)
    R Version       : "R version 3.6.1 (2019-07-05)"

### Steps to reproduce the problem
Open `Find in Files` menu. Enter a normal pattern, and then the menu remembers the last
pattern entered. If you enter a regular expression, and if you check the `Regular Expression`
tick, then Find in Files does not remember the pattern (reg.ex.) last used.

**Comment by tmcduff** [comment]
Version: 1.3.618-2

I tried to reproduce this issue, but was not successful. I was able to search a regular expression, find it within the file, re-enter Find in Files and the last regex is the same cached pattern.

**Comment by CGMossa** [comment]
I am no longer experiencing this issue. I think it was fixed somehow. But I am unable to use `\w` in the pattern, but that's a different issue, and it is reported by someone else #7012. Closing this.
