### ISSUE TITLE
RStudio not responding when using Alt+Shift+1 

### ISSUE THREAD

**Issue by dariomics** [rstudio/rstudio#5510]
### System details

    RStudio Edition : 
    RStudio Version : 1.2.1335 and 1.2.5001
    OS Version      : Windows 7 x64 (build 7601) Service Pack 1
    R Version       : 3.6.1 (2019-07-05)

Platform: x86_64-w64-mingw32/x64 (64-bit)

### Steps to reproduce the problem
RStudio IDE stops responding when using Alt  + Shift + 1 (not assigned to any Keyboard shortcut in RStudio but to change keyboard language in Windows).

### Describe the problem in detail
RStudio stops responding in Version 1.2.1335, and also now after updating to 1.2.5001. 
Previous RStudio version without problem 1.1.456 (then updated to version 1.2.1335).

### Describe the behavior you expected
I expected to change the keyboard language

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3692848/diagnostics-report.txt)
[Request Log.txt](https://github.com/rstudio/rstudio/files/3692849/Request.Log.txt)
[Environment variables.txt](https://github.com/rstudio/rstudio/files/3692850/Environment.variables.txt)

**Comment by ronblum** [comment]
@dariomics Thank you for raising the issue. However, we're unable to reproduce it, both in Windows 7 and 10.  Two things:
1) What happens with just <kbd>alt-shift</kbd>, without the <kbd>1</kbd>? When we tried it, <kbd>alt-shift</kbd> changes the languages and <kbd>alt-shift-1</kbd> inserts a `!`.
2) Had you used 1.1463 in the past, by chance, and if so, was there an issue there?

**Comment by dariomics** [comment]
@ronblum Thanks for your response, here 

1. When just alt-shift, without the 1 --> it changes the language. When  alt-shift-1  --> RStudio stops responding
2. I updated from 1.1.456 to 1.2.1335 and then 1.2.5001, so I missed the 1.1463 version

**Comment by dariomics** [comment]
I've noticed that when using only alt+shift in RStudio the language is changed so the same key would be ie. either ";" or "ñ". 
So if I'm already in the "ñ" keyboard, if I try alt+shif+1 RStudio does not stops working, this only happens when being in the ";" keyboard and pressing alt+shift+1 (Windows keyboard shortcut to change to the "ñ" keyboard that worked in the same way in previous RStudio versions, at least 1.1.456)

**Comment by Empusa23** [comment]
I have the same issue. 
My system (Win 7 x64) has 4 keyboard layouts, switched by Alt+Shift+1 (International English), Alt+Shift+2 (Russian), Alt+Shift+3 (Polish), Alt+Shift+4 (Chinese Simplified). I have no cycling through the layouts with Alt-Shift or any other shortcut. The system language is Russian, so on RStudio start-up it is the language of the application. I may change my keyboard layout to Chinese by Alt-Shift-4 and use Alt-Shift-5 without any problems, Alt-Shift-7 tried to start screen reading ok, However, pressing Alt-Shift- 1 through 3 freezes RStudio (Version 1.3.1093, R version 3.2.3). Previously used 0.9.something without any issues. If I change the keyboard layout through the Windows Panel, everything works fine.

**Comment by jmcphers** [comment]
We don't formally support Windows 7 as it's reached vendor end of life.

**Comment by bzzrak** [comment]
Sorry for the bump but I run into this issue a lot. I have the Alt+Shift+n hotkeys mapped to switching between keyboard layouts (it's a built-in windows feature) and often when I press it, Rstudio will just hang. Like the interface completely stops responding.

I'm running Windows 11. RStudio version is 2021.09.1 build 372 but this also happens on the previous one (1.4.something).

Is there a crash log of some sort that I can send?
