### ISSUE TITLE
Console, Terminal and History tabs aggressively steal focus

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#5515]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.461
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- Select a tab adjacent to Console, Terminal or History by Tab/Arrow keying to it like:
![VyEb0QF](https://user-images.githubusercontent.com/136863/66347252-e82d8280-e921-11e9-87c3-3ec321222602.png)

- Press the left/right arrow keys to select Console, History or Terminal
- Observe that focus is taken by the selected window

### Describe the problem in detail
Console, Terminal and History aggressively steal focus as soon as they are selected. This makes sense in a mouse-centric world because you want to type in there immediately upon clicking on the tab. However, if keyboard-only navigating this can be very jarring and disruptive.

### Describe the behavior you expected
- When keyboard navigating I expect focus to never be stolen from me

**Comment by adamconroy** [comment]
@gtritchie let me know if you agree with this.

**Comment by adamconroy** [comment]
Might be worth tossing a quick glance at https://github.com/rstudio/rstudio/issues/3977 while working on this just in case it's more related than it seems.

**Comment by gtritchie** [comment]
Yes, focus should stay in the tablist when using arrow keys to move between tabs, and hitting the Tab key should move to the first control in the currently activated tabpane.

https://www.w3.org/TR/wai-aria-practices/#tabpanel

**Comment by gtritchie** [comment]
History tab also has this problem, the filter textbox grabs focus.

**Comment by jmcphers** [comment]
@adamconroy will confirm whether this is already fixed (suspects it is from previous changes by @gtritchie )
