### ISSUE TITLE
1.2 and 1.3 Installation issues on Redhat 8.0 

### ISSUE THREAD

**Issue by tmcduff** [rstudio/rstudio#5519]
RStudio Edition : Server
    RStudio Versions : 1.2.1578-2 and 1.3.489-1
    OS Version      : Red Hat Enterprise Linux release 8.0 / ami-087c2c50437d0b80d
    R Version       : 3.6.1

Description: The attached diagnostics file contains the output for both my 1.2 and 1.3 installations. I have done multiple ground up installs.  What's common to both installs is the inability to find a viable R install at /opt/R/3.6.1/bin. Neither rstudio servers succeeds to come up cleanly. The R install seems to be fine as I have set a systems path to execute R from anywhere on the system. I have automation for RHEL 6, 7 and 8 that use essentially the same create process. I used make from source for 3.6.1 on this RHEL8 install which is a delta. I don'y clearly know if this is a bug or user config error. 

** The attached document also will contain the workflow for my R install (at the bottom). I can provide connection information and the .pem if needed. 

[rhel8_bug_report.txt](https://github.com/rstudio/rstudio/files/3703752/rhel8_bug_report.txt)

**Comment by tmcduff** [comment]
I'm closing this for now. 

Solution appears to be this: https://howto.lintel.in/enable-disable-selinux-centos/

**Comment by ronblum** [comment]
Note: see also related SELimux discussion at #4937.
