### ISSUE TITLE
Wrong document outline font after macOS Catalina update

### ISSUE THREAD

**Issue by msaltieri** [rstudio/rstudio#5525]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      : macOS 10.15 (Catalina)
    R Version       : 3.6.1

### Describe the problem in detail

After updating to macOS 10.15 (Catalina) there is a very ugly font in the document outline applied to every custom separator of this kind:
```
# SECTION #1 ----
```
Instead, the font applied to the functions is the same as always.

### Describe the behavior you expected

It would be great if the font in the document outline would be the same for both separators and functions.

**Comment by ronblum** [comment]
@msaltieri Thank you for filing this issue. Can you please provide a screenshot so that we can compare the output?

**Comment by msaltieri** [comment]
Hello @ronblum! Thank you for the very quick feedback.

Here is the screenshot of how the document outline appear on my IDE:
<img width="242" alt="Schermata 2019-10-09 alle 16 13 42" src="https://user-images.githubusercontent.com/26568338/66489628-37a1b900-eab0-11e9-9617-8e467a68b2d9.png">

**Comment by ronblum** [comment]
@msaltieri You're welcome! Do you mean the switch between the serifed and non-serifed fonts (which are two different fonts altogether? I'm unable to reproduce this—where the functions appear, I get the serifed font but italicized. Would you mind providing the code for the above, or at least a small subset, so that I can try to reproduce exactly the same results?

**Comment by msaltieri** [comment]
Exactly @ronblum, there is an inexplicable switch between Serif/Sans-serif fonts that has never existed before the os update.

You can try yourself with this chunk of code:
```
Schedule <- R6Class(

    # Class Schedule ----
    classname = 'Schedule',

    # * Public Members ----
    public = list(

        # * * Basic Methods ----

        initialize = function(config_file) {
            private$config <- config_file
            private$tab <- NULL
            private$is_refine <- FALSE
            invisible(self)
        }

    ),

    # * Private Members ----
    private = list(

        tab = NULL,
        config = NULL,
        is_refine = NULL

    )

)
```

The document outline appears like this:
<img width="229" alt="Schermata 2019-10-09 alle 16 57 03" src="https://user-images.githubusercontent.com/26568338/66493190-e5639680-eab5-11e9-84b9-323ed4d03825.png">

I'm working with `R6` classes, but the same Serif font appears every time I try to insert a section separator like:
```
# This is a new section ----
```

**Comment by kevinushey** [comment]
I'm seeing this as well. I believe it's related to an issue that @jmchers fixed recently where the wrong fonts were used in the Help pane:

https://github.com/rstudio/rstudio/issues/5066

**Comment by kevinushey** [comment]
The bad CSS in question:

https://github.com/rstudio/rstudio/blob/58d38478a17d4ae09ea3904a0abb4a10bb45294f/src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.css#L63

(for whatever reason, `sans-serif` is not properly recognized with Catalina in RStudio)

**Comment by msaltieri** [comment]
Okay @ronblum. Let me just add that I found this weird behavior even with a previous version of RStudio Desktop on Catalina (it could be a 1.1 and something...). Then I though it was due to the outdated RStudio version and I upgraded to v1.2.5001, but the issue was still there.

**Comment by ronblum** [comment]
I see the problem in the first 1.2 release,  1.2.1335. But, in any case, it's definitely a bug, as @kevinushey notes.

Also: in an R Markdown document, all the text is serifed., using the default file as an example.

**Comment by kevinushey** [comment]
I've filed a Qt bug: https://bugreports.qt.io/browse/QTBUG-79120

The issue is actually a bit worse than initially thought: on Catalina, _all_ generic font families will fail to render as requested, and will just fall back to `serif`. So we'll need to audit all usages of default fonts.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.2.5013.
