### ISSUE TITLE
Files pane not refreshed when adding or deleting files in a project

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5530]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001 and 1.1.463
    OS Version      : MacOS Catalina (10.15)
    R Version       : 3.6.1

### Steps to reproduce the problem

1) Open or create a project
2) Switch to the Files pane
3) Either
    b. save a new file; or
    a. delete a file using the Files pane

Optionally:
4) Switch to a different pane (say, Plots) then back to Files

### Describe the problem in detail

The Files pane does not get refreshed, so new files don't get listed and deleted files don't go away. A manual refresh is needed to change the file list.

### Describe the behavior you expected

The Files pane should get refreshed so that new files appear and deleted files disappear. 

However, this works correctly when:
- not in a project
- renaming a file
- moving to a different directory, then back
 - using RStudio Server

Note that this is a problem in 1.1.463, as well. (I feel like this is a duplicate, but I can't find a similar issue.)

**Comment by jmcphers** [comment]
Probably related to https://github.com/rstudio/rstudio/issues/4755.

**Comment by jmcphers** [comment]
This is fixed now on 1.2.623 (probably as a side effect of one of our fixes to #4755 or Apple fixing inotify bugs in Catalina).
