### ISSUE TITLE
(Mac) Plots being very slow after upgrade to Catalina

### ISSUE THREAD

**Issue by jkidd20** [rstudio/rstudio#5531]
I just upgraded to Catalina this morning, and I'm finding that reviewing plots has become unbearably slow. If I plot more than one plot, and then try to browse through them (or even clear them), it can take over a minute to respond, meanwhile nothing else works. I do have a high number of points on some of these plots, but prior to today, the time to wait was a second at most for the same density of plots.

**Comment by kevinushey** [comment]
Can you provide a reproducible example?

**Comment by jkidd20** [comment]
The code below runs on my machine in 0.65 and 1.60 second segments, but switching back to the first graph from the second took approximately 20 seconds (counting in my head), and took approx. 75 seconds going from the first back to the second. 

`start = Sys.time()
plot(x = 0, y = 0, xlim = c(-1, 1), ylim = c(-1, 1), cex = 1e-16)
for(i in 1:10000){
  points(x = runif(1, -1, 1), y = runif(1, -1, 1), cex = .3, pch = 15)
}
Sys.time() - start

start = Sys.time()
plot(x = 0, y = 0, xlim = c(-1, 1), ylim = c(-1, 1), cex = 1e-16)
for(i in 1:20000){
  points(x = runif(1, -1, 1), y = runif(1, -1, 1), cex = .3, pch = 15)
}
Sys.time() - start

`

MacBook Pro (15", Mid 2018)
2.6 GHz 6-Core Intel Core i7
16 GM RAM

**Comment by kevinushey** [comment]
I can reproduce the slowness on my Windows VM as well -- it appears to be independent of the Catalina upgrade.

**Comment by kevinushey** [comment]
We've merged a fix for this that should become part of the next [daily builds](https://dailies.rstudio.com).

**Comment by kevinushey** [comment]
It would also be helpful to see some of the error windows you saw.

**Comment by jkidd20** [comment]
I can confirm using the example above that I did not get any error message. However, the graphs corresponding to my research that I have been playing with (which caused the initial post) did seem to cause the crash when going between both of them. I can't share the program for those, but they do have multiple colors as well as points plotted on top of other points (if that would make a difference). Additionally I've added the error messages. 

This was with build 3.497.
<img width="422" alt="Screen Shot 2019-10-10 at 12 50 33 PM" src="https://user-images.githubusercontent.com/31283273/66590167-27e0ae00-eb5e-11e9-9c07-dc689c15ea26.png">
<img width="1134" alt="Screen Shot 2019-10-10 at 12 50 45 PM" src="https://user-images.githubusercontent.com/31283273/66590175-2c0ccb80-eb5e-11e9-8e85-2bda1ec4f2fc.png">
<img width="1134" alt="Screen Shot 2019-10-10 at 12 50 45 PM" src="https://user-images.githubusercontent.com/31283273/66590179-2e6f2580-eb5e-11e9-8632-7613888e8299.png">

**Comment by kevinushey** [comment]
If you're able to provide a reproducible example, that would be very helpful.

**Comment by kevinushey** [comment]
It may help to know if you're using any add-on R packages to produce the plots, or just built-in base graphics facilities.

**Comment by jmcphers** [comment]
Haven't heard back in a couple of months, so closing. @jkidd20 please feel free to reopen if you have a reproducible example.
