### ISSUE TITLE
RStudio hangs on rpart after upgrading to macOS Catalina 

### ISSUE THREAD

**Issue by DigiDonJ** [rstudio/rstudio#5537]
RStudio Edition : 
    RStudio Version : Version 1.2.5001
    OS Version      : Mac Os Catalina 
    R Version       : 

### Steps to reproduce the problem

```
library(readxl)
library(rpart)
setwd("/Users/donjayasekara/Pred")
histIM<-read_excel("hist.xlsx", sheet=1, col_names =TRUE)

hist <- subset(histIM,Country=="ENGLAND")

n <- nrow(hist)
shuffled <- hist[sample(n),]

accs1 <- rep(0,6)
accs2 <- rep(0,6)
accs3 <- rep(0,6)
accs4 <- rep(0,6)
accs5 <- rep(0,6)
accs6 <- rep(0,6)

for (i in 1:6) {
  # These indices indicate the interval of the test set
  indices <- (((i-1) * round((1/6)*nrow(shuffled))) + 1):((i*round((1/6) * nrow(shuffled))))
  
  
  # Exclude them from the train set
  train <- shuffled[-indices,]
  
  # Include them in the test set
  test <- shuffled[indices,]
  
  #levels(test$Plc)<-levels(train$Plc)
  #levels(test$Time)<-levels(train$Time)
  #levels(test$Day)<-levels(train$Day)

  dtree1 <- rpart(O1P~total+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd5+odd6, data=train, method="class")
  #dtree1 <- rpart(O1P~total+Day+Plc+Time+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd2+odd3+odd5+odd4+odd6, data=train, method="class",parms = list(split = "information"))
  mlp1 <- predict(dtree1,test, type="class")
  conf1a<- table(test$O1P, mlp1)
  conf1b<-apply(conf1a,2,rev)
  conf1<-conf1b[,order(ncol(conf1b):1)]
  accs1[i] <- sum(diag(conf1))/sum(conf1)
  
  dtree2 <- rpart(O2P~total+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd5+odd6, data=train, method="class",parms = list(split = "information"))
  #dtree2 <- rpart(O2P~total+Day+Plc+Time+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd3+odd4+odd5+odd6, data=train, method="class",parms = list(split = "information"))
  
  mlp2 <- predict(dtree2,test, type="class")
  conf2a <- table(test$O2P, mlp2)
  conf2b<-apply(conf2a,2,rev)
  conf2<-conf2b[,order(ncol(conf2b):1)]
  accs2[i] <- sum(diag(conf2))/sum(conf2)
  
  dtree3 <- rpart(O3P~total+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd5+odd6, data=train, method="class",parms = list(split = "information"))
  #dtree3 <- rpart(O3P~total+Day+Plc+Time+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd4+odd5+odd6, data=train, method="class",parms = list(split = "information"))
  mlp3 <- predict(dtree3,test, type="class")
  conf3a <- table(test$O3P, mlp3)
  conf3b<-apply(conf3a,2,rev)
  conf3<-conf3b[,order(ncol(conf3b):1)]
  accs3[i] <- sum(diag(conf3))/sum(conf3)
  
  dtree4 <- rpart(O4P~total+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd5+odd6, data=train, method="class",parms = list(split = "information"))
  #dtree4 <- rpart(O4P~total+Day+Plc+Time+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd5+odd6, data=train, method="class",parms = list(split = "information"))
  mlp4 <- predict(dtree4,test, type="class")
  conf4a <- table(test$O4P, mlp4)
  conf4b<-apply(conf4a,2,rev)
  conf4<-conf4b[,order(ncol(conf4b):1)]
  accs4[i] <- sum(diag(conf4))/sum(conf4)
  
  
  dtree5 <- rpart(O5P~total+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd5+odd6, data=train, method="class",parms = list(split = "information"))
  #dtree5 <- rpart(O5P~total+Day+Plc+Time+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd6, data=train, method="class",parms = list(split = "information"))
  mlp5 <- predict(dtree5,test, type="class")
  conf5a <- table(test$O5P, mlp5)
  conf5b<-apply(conf5a,2,rev)
  conf5<-conf5b[,order(ncol(conf5b):1)]
  accs5[i] <- sum(diag(conf5))/sum(conf5)
  
  dtree6 <- rpart(O6P~total+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd5, data=train, method="class",parms = list(split = "information"))
  #dtree6 <- rpart(O6P~total+Day+Plc+oin+Fin+Sin+Tin+Frin+Ffin+Siin+odd1+odd2+odd3+odd4+odd5, data=train, method="class",parms = list(split = "information"))
  mlp6 <- predict(dtree6,test, type="class")
  conf6a <- table(test$O6P, mlp6)
  conf6b<-apply(conf6a,2,rev)
  conf6<-conf6b[,order(ncol(conf6b):1)]
  accs6[i] <- sum(diag(conf6))/sum(conf6)
}

accs1
mean(accs1)
accs2
mean(accs2)
accs3
mean(accs3)
accs4
mean(accs4)
accs5
mean(accs5)
accs6
mean(accs6)
```

**Comment by ronblum** [comment]
@DigiDonJ Thank you for raising the issue. In order to reproduce:
1) What version of R are you using?
2) Can you please provide a sample data file—the `hist.xlsx` referenced in the code?

**Comment by DigiDonJ** [comment]
> @DigiDonJ Thank you for raising the issue. In order to reproduce:
> 
> 1. What version of R are you using? 
RStudio
Version 1.2.5001
© 2009-2019 RStudio, Inc.
Build 1440 (7b3fe265, 2019-09-18)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

> 2. Can you please provide a sample data file—the `hist.xlsx` referenced in the code?

total | oin | Fin | Sin | Tin | Frin | Ffin | Siin | odd1 | odd2 | odd3 | odd4 | odd5 | odd6 | O1P | O2P | O3P | O4P | O5P | O6P
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0% | 5.4 | 1.85 | -0.4 | 0.4 | 2.033333333 | #N/A | #N/A |   |   |   |   |   |   | C | C | C | C | C | C
3% | 5.849173554 | 1.685950413 | -0.090909091 | 0.818181818 | 3.884297521 | 0.303030303 | 4.151515152 |   |   | 16 |   |   | 16 | C | C | A | C | C | A
0% | 5.076388889 | 1.722222222 | 0.333333333 | 2 | 2.5 | 0.555555556 | 2.638888889 | 6 |   |   | 6 |   |   | B | C | C | B | C | C
2% | 5.189236111 | 1.486111111 | 0.924242424 | 1.007575758 | 4.143518519 | 0.833333333 | 4.391203704 |   |   |   |   |   |   | C | C | C | C | C | C
48% | 9.954861111 | 3.069444444 | 1.833333333 | 2.75 | 3.958333333 | 1.111111111 | 4.076388889 | 1 |   |   | 1 |   |   | B | C | C | B | C | C
12% | 1.842757937 | 0.579365079 | 0.222222222 | 0.301587302 | 3.16872428 | #N/A | 3.374485597 |   | 1.2 |   | 1.2 |   |   | C | B | C | B | C | C
0% | 5.033163265 | 1.12755102 | -0.071428571 | 0.714285714 | 4.25170068 | 0.714285714 | 4.486394558 |   |   |   |   |   |   | C | C | C | C | C | C
4% | 6.653061224 | 2.295918367 | 1.285714286 | 1.142857143 | 3.265306122 | #N/A | 3.496598639 | 1.75 |   |   |   |   |   | A | C | C | A | C | C
3% | 16.21930804 | 4.252232143 | 1.625 | 3.125 | 4.270833333 | 1.666666667 | 4.447916667 | 0.33 | 5 |   | 0.33 | 5 |   | A | B | C | A | B | C
0% | 9.62 | 2.81 | 0 | -0.2 | 3.733333333 | 1 | 3.906666667 |   |   |   |   |   |   | C | C | C | C | C | C
0% | 4.793333333 | 1.146666667 | 0.266666667 | 0.733333333 | 4.518518519 | 0.666666667 | 4.859259259 |   |   |   |   |   |   | C | C | C | C | C | C
7% | 7.845424107 | 1.857142857 | 1.107142857 | 0.375 | 3.854166667 | 1.25 | 4.03125 |   |   | 25 |   |   | 25 | C | C | B | C | C | B
2% | 5.745738636 | 2.107954545 | 0.583333333 | 0.75 | 3.541666667 | 0.555555556 | 3.729166667 | 7.5 | 4 |   | 4 | 7.5 | 11 | B | A | C | A | B | B
4% | 4.039202009 | 1.501674107 | 0.4375 | 0.4375 | 3.528645833 | 0.416666667 | 3.819010417 |   |   |   |   |   |   | C | C | C | C | C | C
0% | 8.18877551 | 2.897959184 | 1.428571429 | 1.571428571 | 3.265306122 | 0.476190476 | 3.448979592 |   | 10 | 2.1 | 10 |   |   | C | B | B | B | C | C


> 3. Where in the script is RStudio hanging?
it's hanging at Rpart

**Comment by zhanglab2008** [comment]
I came across the same issue today...

**Comment by DigiDonJ** [comment]
Help needed, I have ran out of ideas? 😓

**Comment by kevinushey** [comment]
Sorry, but without a minimally reproducible example we cannot help.

**Comment by DigiDonJ** [comment]
> Sorry, but without a minimally reproducible example we cannot help.

Hi Both the code and sample of data can be found above. What else do you need to be able to help pls?

**Comment by ronblum** [comment]
@DigiDonJ Two things:

1) It would be helpful to attach the original Excel file to the ticket, since as is, it requires copying over the data into Excel and performing a conversion from pipe-delimited text to Excel data. 
2) I tried the above, but the code failed at
```
> histIM<-read_excel("hist.xlsx", sheet=1, col_names =TRUE)                                                                          
> hist <- subset(histIM,Country=="ENGLAND")
Error in eval(e, x, parent.frame()) : object 'Country' not found
```
since there's no field named "Country".
