### ISSUE TITLE
Cycle through tabs with next/prior tab keyboard shortcuts

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#5539]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1578
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.1

### Steps to reproduce the problem
1. Open two tabs
2. Press the "Next Tab" shortcut several times

### Describe the problem in detail
The editor gets stuck on the second tab.

### Describe the behavior you expected
The editor continues to cycle back and forth through the tabs. Not sure if this is a bug report or a feature request but Chrome, Atom, and Firefox all have the cycling behavior.

**Comment by jmcphers** [comment]
Good news, we implemented it already! It's just off by default since many people don't like it. You can enable it in *Tools -> Global Options -> General ->  Wrap around when navigating to previous/next tab.*
