### ISSUE TITLE
Keyboard shortcut Alt + Enter  not working

### ISSUE THREAD

**Issue by sudheer596** [rstudio/rstudio#5540]
Hi All, 
         Keyboard shortcut for running a line of code and retaining the cursor in the same line is not working.

**Comment by pascaloettli** [comment]
Please follow the guide on how to write a [good bug report](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports). This starts by providing the system details (as requested when you opened this issue):

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by dfalty** [comment]
I can't reproduce this. Feel free to open back up with additional information like @pascaloettli noted.
