### ISSUE TITLE
R console becomes unusably slow

### ISSUE THREAD

**Issue by cawthm** [rstudio/rstudio#5544]
Using rstudio version 1.2.5001 under Ubuntu 18.04.3 LTS and am running into a situation where the console window becomes intolerably slow (minutes to get a cursor return/ newline).

It's not present on app start-up, but seems to *possibly* be related to times after I've loaded a large object (~25+gb DB pull) into memory.  My machine should be up to the task- it has 128gb of RAM and often handles the pull just fine.

I've observed this problem for a while, including  my previous rstudio version install (1.2.1335).

Here's some pseudo-ish code I'm running (again, not sure it's related):
```r
library(dplyr)

con <- RPostgreSQL::dbConnect("PostgreSQL", dbname="my_data", user = "not_root")

raw_db <- tbl(con, "some_table")

data_pull <- raw_db %>%
    filter(14mm_rows_of_35_vars_data) %>%
    collect()
#fwiw the above takes about 75 secs on my machine
```

``` r
"Linux" 
#> [1] "Linux"
"4.15.0-65-generic" 
#> [1] "4.15.0-65-generic"
version 
#>                _                           
#> platform       x86_64-pc-linux-gnu         
#> arch           x86_64                      
#> os             linux-gnu                   
#> system         x86_64, linux-gnu           
#> status                                     
#> major          3                           
#> minor          6.1                         
#> year           2019                        
#> month          07                          
#> day            05                          
#> svn rev        76782                       
#> language       R                           
#> version.string R version 3.6.1 (2019-07-05)
#> nickname       Action of the Toes
"#74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019" 
#> [1] "#74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019"
"x86_64" 
#> [1] "x86_64"
login 
```

<sup>Created on 2019-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kevinushey** [comment]
It's possible some of the slowness is caused by R code that RStudio is running behind the scenes. Can you try running an R profile? You can start the R profiler with:

```r
utils::Rprof("~/rstudio-trace.Rprof")
```

After this, try running RStudio and wait for the hang / slowness to occur. Once that happens, you can execute:

```r
utils::Rprof(NULL)
```

to stop the profiler. Then, find the file at "~/rstudio-trace.Rprof", and share it with us.

You can also try sharing the printed output of

```r
utils::summaryRprof("~/rstudio-trace.Rprof")
```

directly, as that may point us towards what we need to know.

**Comment by cawthm** [comment]
Alright, I tried to do what you asked. 

First, I ran the utils::Rprof("~/rstudio-trace.Rprof") command from WITHIN Rstudio, and then ran my code in the same session.  This is what you meant?

But the profiler itself seems to hang the machine.  Is that possible? 

Under htop, I see one cpu thread spike to 100%, and moreover, I'm pretty sure it's not the main R thread being used by the Rstudio session.

Eventually (~15 mins), I can neither Stop Profiling nor Stop from the console window in Rstudio, so I killed the process from a shell.  

And btw, I made the data pull much smaller for this exercise --about 1/3 of the usual.

In any case, attached is the rstudio-trace.Rprof file. 
[rstudio-trace.Rprof.zip](https://github.com/rstudio/rstudio/files/3719325/rstudio-trace.Rprof.zip)

**Comment by kevinushey** [comment]
Thanks! The RStudio trace shows the following:

```
> summaryRprof("rstudio-trace.Rprof")
Warning in readLines(con, n = chunksize) :
  incomplete final line found on 'rstudio-trace.Rprof'
$by.self
                          self.time self.pct total.time total.pct
"initialize"                 173.98    96.94     173.98     96.94
"postgresqlExecStatement"      4.66     2.60     178.62     99.52
```

So it looks like it captured the time spent loading the data from the database into R, but nothing else.

> But the profiler itself seems to hang the machine. Is that possible?

That seems unlikely -- more likely perhaps is that the R session was already frozen or hanging by the time you tried to execute the call. Is that possible?

Are you able to see which process is using all of the CPU? Is it the `rsession` process, or something else?

**Comment by cawthm** [comment]
Attached is some output from htop.

you can see that the process is /usr/lib/rstudio/bin/rsession

![htop_output](https://user-images.githubusercontent.com/1149250/66685053-07d5eb00-ec41-11e9-99e5-517ede28cac8.png)

**Comment by cawthm** [comment]
And now, having just killed the spiking process, here is an updated .Rprof file from the most recent session.

[rstudio-trace2.Rprof.zip](https://github.com/rstudio/rstudio/files/3719617/rstudio-trace2.Rprof.zip)

**Comment by kevinushey** [comment]
Thanks! This looks a bit more interesting. Here's a snippet of the profile:

```
> summaryRprof("rstudio-trace2.Rprof")
Warning in readLines(con, n = chunksize) :
  incomplete final line found on 'rstudio-trace2.Rprof'
$by.self
                          self.time self.pct total.time total.pct
"system"                     125.90    88.49     125.90     88.49
< ... >

$by.total
                                       total.time total.pct self.time self.pct
"tryCatch"                                 136.80     96.15      0.00     0.00
"tryCatchList"                             136.62     96.02      0.00     0.00
"doTryCatch"                               127.04     89.29      0.00     0.00
"tryCatchOne"                              127.04     89.29      0.00     0.00
"loadNamespace"                            126.58     88.97      0.00     0.00
"<Anonymous>"                              126.36     88.81      0.00     0.00
"fun"                                      126.16     88.67      0.00     0.00
"runHook"                                  126.12     88.64      0.00     0.00
"withCallingHandlers"                      126.02     88.57      0.00     0.00
"suppressWarnings"                         125.92     88.50      0.00     0.00
"system"                                   125.90     88.49    125.90    88.49
"parallel::detectCores"                    125.90     88.49      0.00     0.00
< ... >
```

So, if I understand correctly, it seems like an R package is being loaded, calling `system()`, and then hanging during that call.

You could try using:

```
trace(system, quote(writeLines(paste("TRACE:", shQuote(command))), print = FALSE)
```

to see what is getting executed. FWIW, `parallel::detectCores()` _does_ make a system call; e.g.

```
> parallel::detectCores()
TRACE: '/usr/sbin/sysctl -n hw.logicalcpu 2>/dev/null'
[1] 12
```

but that shouldn't be slow.

**Comment by cawthm** [comment]
Thank you so much for the guidance

So, 

TRACE: "/usr/bin/which 'svn'" 

is the output of your suggested debug command

My linux fu is not so good, but this seems to be saying there's a system call to `which`, which looks for executables for something called svn.  The only svn I know if the Apache version control, and I've never used it.

might it me an R/studio thing?

**Comment by MWRR** [comment]
@cawthm I am experiencing the same issue. How did you fix it?
