### ISSUE TITLE
Multiple files selection

### ISSUE THREAD

**Issue by evgeny-vlasov** [rstudio/rstudio#5545]
I am trying to run my script on headless server - Ubuntu 18 without X11 or any GUI. There is a part when I need user to choose a bunch of files. RStudio Server GUI works fine with `file.choose()`, which is great for an IDE running on instance without any graphic manager. But it can choose only single file. It would be so cool if you guys implement the multiple files choice somehow. I understand that this is a tricky task and more about R itself than RStudio but if you do you will be my heroes forever!

**Comment by dfalty** [comment]
Out of curiosity, does `tcltk::tk_choose.files()` work for you in this scenario?

**Comment by evgeny-vlasov** [comment]
Good question, sorry I did not elaborate.
I tried tcltk and rChoiceDialog. Both require a graphic system. 
```
> library(rChoiceDialogs)
Warning message:
In fun(libname, pkgname) : couldn't connect to display ":0"
```
```
> jchoose.files()
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "newInstance", .jfindClass(class),  : 
  java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
```
```
> tk_choose.files()
Error in structure(.External(.C_dotTclObjv, objv), class = "tclObj") : 
  [tcl] invalid command name "tk_getOpenFile".
```
I even installed Xfce but it does not help.

**Comment by dfalty** [comment]
Thanks for the info! I'm not sure if we can do anything here but I'll mark it as an enhancement and see if others have ideas on if this is accomplishable.

**Comment by kevinushey** [comment]
IMHO this is a reasonable feature request and (in theory) shouldn't be too hard to implement. Unfortunately, we do have to balance its priority against other higher-priority bugs and feature requests we have in the pipeline already.

**Comment by royfrancis** [comment]
Just commenting to show support.
