### ISSUE TITLE
Enhancement: button to rerun an already defined job in the job tab

### ISSUE THREAD

**Issue by calote** [rstudio/rstudio#5548]
Enhancement: **button to rerun an already defined job in the job tab**.

Very useful when I am working on a project that runs a very complex R script (calls other R code files) and needs a lot of execution time. With the jobs window open, you could quickly execute it again if there was a button to repeat the execution of a previous job already defined.

**Comment by jmcphers** [comment]
Thanks for the suggestion; that's a great idea!

**Comment by jmcphers** [comment]
via @blairj09:

> The use case for this may not be very wide, but for certain background jobs (Shiny and Plumber come to mind) it would be nice to have a way of restarting the job directly from the jobs pane after it's been stopped. Maybe an icon next to completed jobs that would start the job again with the same settings.

**Comment by gtritchie** [comment]
Frequently requested

**Comment by astayleraz** [comment]
Verified in Version 1.5.139-1 the reply button works as described and added an automation test for this as well. Closing issue.
