### ISSUE TITLE
Bold comments in .cpp source files

### ISSUE THREAD

**Issue by tomjamesprior** [rstudio/rstudio#5550]
![image](https://user-images.githubusercontent.com/11546834/66767338-2bd24000-ee7e-11e9-8736-a1dca0ec2792.png)

In a .R file, when editing it in RStudio, putting #### A comment that looks like this #### makes a special bold separator when you click the lower left button in RStudio pictured above. Can we please have the same thing to make this kind of bold style comment/separator when editing a .cpp file in RStudio? I want to use it to put section headings on my code to make it easier to browse for the reader.  It could be like //// A cpp bolded comment //// or something like that.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/2349.
