### ISSUE TITLE
"Bookmark" feature for the File pane

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5552]
It would be very helpful to have a bookmarking feature in the File pane such as the one in WinSCP. 

I noticed this feature was requested by another user a few years ago:

https://support.rstudio.com/hc/en-us/community/posts/200638108-Feature-Request-Bookmark-folder-function-for-the-files-window

**Comment by ronblum** [comment]
@hzarkoob Thank you for the request, and for including the long-ago support ticket! We'll review this as we continue development of RStudio.

**Comment by Jollywatt** [comment]
This shouldn't be closed. It remains a helpful missing feature.

**Comment by simon-smart88** [comment]
@ronblum Are you able to reopen this? As an example of why it would be useful, I'm developing a shiny app as a package and frequently need to navigate between R/ and inst/shiny/modules/ and there doesn't seem to be an easy way to do this.
