### ISSUE TITLE
libxkbcommon-x11 dependency installed but not detected by the rpm + zypper

### ISSUE THREAD

**Issue by fReschAnalytics** [rstudio/rstudio#5554]
trying to install rstudio on OpenSUSE Tumbleweed and am having issues with the installer detecting this dependency even though it is clearly installed: libxkbcommon-x11

**Comment by dfalty** [comment]
What version of RStudio are you trying to install and what is the error you are seeing? Does this happen on the latest [RStudio preview](https://rstudio.com/products/rstudio/download/preview/)?

**Comment by fReschAnalytics** [comment]
The version of Rstudio is the one from the main desktop download section linked here: 
https://download1.rstudio.org/desktop/opensuse15/x86_64/rstudio-1.2.5001-x86_64.rpm 

I believe it is 1.2.5001;

The error on executing ```sudo zypper install rstudio-1.2.5001-x86_64.rpm``` is:
> Problem: nothing provides libxkbcommon-x11 needed by rstudio-1.2.5001-1.x86_64

Which is not true; i clearly have the following in /usr/lib64:
```libxkbcommon-x11.so
libxkbcommon-x11.so.0
libxkbcommon-x11.so.0.0.0```

What's particularly wild is, if at the error prompt, if I choose to ignore dependencies and install anyways, RStudio launches and seems to work - the main problem any time I subsequently do a ```zypper dup``` command, it flags RStudio as broken and wants to remove it.

 
![image](https://user-images.githubusercontent.com/56571941/66978164-fee08180-f065-11e9-98e1-9b0a99318bcc.png)

**Comment by kevinushey** [comment]
Hmm, I see the same thing for OpenSUSE Leap:

```
14ec1eca6299:/ # zypper search libxkbcommon
Loading repository data...
Reading installed packages...

S | Name                         | Summary                                             | Type
--+------------------------------+-----------------------------------------------------+--------
  | libxkbcommon-devel           | Development files for the libxkbcommon library      | package
  | libxkbcommon-devel-32bit     | Development files for the libxkbcommon library      | package
  | libxkbcommon-x11-0           | Library for handling xkb descriptions using XKB-X11 | package
  | libxkbcommon-x11-0-32bit     | Library for handling xkb descriptions using XKB-X11 | package
  | libxkbcommon-x11-devel       | Development files for the libxkbcommon-x11 library  | package
  | libxkbcommon-x11-devel-32bit | Development files for the libxkbcommon-x11 library  | package
  | libxkbcommon0                | Library for handling xkb descriptions               | package
  | libxkbcommon0-32bit          | Library for handling xkb descriptions               | package
```

**Comment by deelaka** [comment]
@fReschAnalytics 

> What's particularly wild is, if at the error prompt, if I choose to ignore dependencies and install anyways, RStudio launches and seems to work - the main problem any time I subsequently do a `zypper dup` command, it flags RStudio as broken and wants to remove it.

This can be resolved by adding a zypper lock:

```
➜  ~ sudo zypper addlock rstudio
Specified lock has been successfully added.
```
System locks can be listed by:
```
➜  ~ sudo zypper locks 

# | Name                 | Type    | Repository
--+----------------------+---------+-----------
1 | rstudio              | package | (any)     
```

You should ideally keep locks for the few `rpm` packages you download from the net and install since Tumbleweed is a rolling distro. Hope this helps.

**Comment by fReschAnalytics** [comment]
Thanks for that recommendation; I ended up uninstalling the rpm versions and cloned the github repo source code and built from source; everything is fine from what I can tell in the version I built from source after hunting down a few undocumented dependencies (python-virtualenv for example) and then specifying an LD_LIBRARY_PATH in my .bashrc to where the scripts install the Qt5.12.5 sdk so it new where to look for a few libraries. All that to say that the dependency libxkbcommon-x11 is definitely available to RStudio and working when I built from source, not sure what is going on with the rpm installer. Thanks again for checking on this and for the zypper recommendation.

**Comment by fReschAnalytics** [comment]
> Thanks for that recommendation; I ended up uninstalling the rpm versions and cloned the github repo source code and built from source; everything is fine from what I can tell in the version I built from source after hunting down a few undocumented dependencies (python-virtualenv for example) and then specifying an LD_LIBRARY_PATH in my .bashrc to where the scripts install the Qt5.12.5 sdk so it new where to look for a few libraries. All that to say that the dependency libxkbcommon-x11 is definitely available to RStudio and working when I built from source, not sure what is going on with the rpm installer. Thanks again for checking on this and for the zypper recommendation.

Edit: Using a sytem wide LD_LIBRARY_PATH declaration broke the Plasma desktop upon reboot; ultimately what worked was to copy the contents of the qt sdk lib directory to rstudio's bin directory (and also the rstudio lib directory for redundancy), and then similarly, copied the resources and translations directiories to rstudios libexec directory. 

Now it works without a system wide LD_LIBRARY_PATH declaration or having to find a different way to getting the necessary qt components...

**Comment by tmcduff** [comment]
I don't appear to have the permissions to re-open this issue, but I wanted to verify we are satisfied with a solution. I did not implement the "sudo zypper addlock rstudio" work around at this point. 

Testing RStudio v1.2.5033-1 Preview
openSUSE Leap 15.1:

What I'm seeing on install:

linux-c9ev:/etc # sudo zypper install rstudio-1.2.5033-x86_64.rpm 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libxkbcommon-x11 needed by rstudio-1.2.5033-1.x86_64
 Solution 1: do not install rstudio-1.2.5033-1.x86_64
 Solution 2: break rstudio-1.2.5033-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): c
linux-c9ev:/etc # **zypper search libxkbcommon**
Loading repository data...
Reading installed packages...

S | Name                               | Summary                                             | Type      
--+------------------------------------+-----------------------------------------------------+-----------
  | libxkbcommon                       | Library for handling xkb descriptions               | srcpackage
  | libxkbcommon-debugsource           | Debug sources for package libxkbcommon              | package   
  | libxkbcommon-devel                 | Development files for the libxkbcommon library      | package   
  | libxkbcommon-devel-32bit           | Development files for the libxkbcommon library      | package   
i | libxkbcommon-x11-0                 | Library for handling xkb descriptions using XKB-X11 | package   
  | libxkbcommon-x11-0-32bit           | Library for handling xkb descriptions using XKB-X11 | package   
  | libxkbcommon-x11-0-32bit-debuginfo | Debug information for package libxkbcommon-x11-0    | package   
  | libxkbcommon-x11-0-debuginfo       | Debug information for package libxkbcommon-x11-0    | package   
  | libxkbcommon-x11-devel             | Development files for the libxkbcommon-x11 library  | package   
  | libxkbcommon-x11-devel-32bit       | Development files for the libxkbcommon-x11 library  | package   
i | libxkbcommon0                      | Library for handling xkb descriptions               | package   
  | libxkbcommon0-32bit                | Library for handling xkb descriptions               | package   
  | libxkbcommon0-32bit-debuginfo      | Debug information for package libxkbcommon0         | package   
  | libxkbcommon0-debuginfo            | Debug information for package libxkbcommon0         | package   
linux-c9ev:/etc # cd /usr/lib64
linux-c9ev:/usr/lib64 # ls /usr/lib | grep xkbcommon*                                                                
linux-c9ev:/usr/lib64 # ls /usr/lib | grep *xkb*                                                               
Binary file libxcb-xkb.so.1.0.0 matches
Binary file libxkbcommon-x11.so.0 matches
Binary file libxkbcommon-x11.so.0.0.0 matches

**Comment by ronblum** [comment]
[From #5746]

1) It's been working fine if I skip over it, but I'm concerned that I haven't yet hit something that will require it and fail.
2) It's not an issue with RStudio Server.
3) I haven't found a package or installation path that takes care of `libxkbcommon-x11`.
