### ISSUE TITLE
Non-UTF-8 Characters displayed as ?? 

### ISSUE THREAD

**Issue by DanyEle** [rstudio/rstudio#5555]
### System details

    RStudio Edition : Client
    RStudio Version : 1.2.1335
    OS Version      :  Windows 10
    R Version       :  3.6.1

### Steps to reproduce the problem
1. Create a file containing non-UTF-8 characters, for example ä, ü, ß, è, ò
2. Open R Studio
3. Open the file created in R studio
4. Create a new project
5. View the file created in R Studio having "??" in place of the actual non-UTF-characters
6. If you close and re-open R Studio and display that file, the problem still occurs. 

### Describe the problem in detail
Basically, when creating a new project and opening a file containing non-UTF-8 characters, R Studio fails to parse them and displays a "??" in their place. This is particularly bad for programs containing variables having non-UTF-8 characters.

### Describe the behavior you expected

I would expect that files containing non-UTF-8 Characters are actually parsed when having an open project. 

**Temporary solution:** This buggy behaviour does not occur when not having any project open. So, my temporary fix consists of just not having any open project.

**Comment by kevinushey** [comment]
You might need to re-open the file with UTF-8 encoding, as otherwise RStudio will attempt to interpret bytes in the document in the system-native encoding.

**Comment by DanyEle** [comment]
> You might need to re-open the file with UTF-8 encoding, as otherwise RStudio will attempt to interpret bytes in the document in the system-native encoding.

Already tried it, didn't work. The same error still happens.

**Comment by dfalty** [comment]
Hmm, with the same steps, if I open with UTF-8 I get the `?` but if I open with `ISO-8859-1`, I get the correct characters. @kevinushey anything we can do here?

**Comment by kevinushey** [comment]
I think I may have misunderstood the issue at first.

First, there are two separate default encodings that can be set:

1. A global encoding, which is used when no RStudio project is open. By default, the system-native encoding is used. See Tools -> Global Options... -> Code -> Saving.

2. A project-specific encoding, used when a project is open. By default, this is UTF-8. See Tools -> Project Options... -> Code Editing.

I believe we prefer UTF-8 documents within projects as that helps ensure documents can be more easily read on other systems when so required.

However, this does imply that if you created a document while having no project open (hence using system-native encoding), and later try to open that document while a project is open (likely using UTF-8), then the document will not be decoded correctly.

I'm not sure what the right fix is -- perhaps we could try to infer the correct encoding based on whether a file lives within an RStudio project?

**Comment by DanyEle** [comment]
> Maybe we could check for errors when decoding from UTF-8, and infer that the system-default encoding should be used instead in that case?

This sounds like a pretty good solution. Something like a try - catch statement in case errors arise when parsing the file could be a good solution.
