### ISSUE TITLE
RStudio 1.2 cannot find files in home directory but 1.1 can

### ISSUE THREAD

**Issue by jdrnevich** [rstudio/rstudio#5556]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001 and 1.1.463
    OS Version      : x86_64-w64-mingw32/x64 (64-bit)
    R Version       : 3.6.1

### Steps to reproduce the problem
Not sure how to reproduce

### Describe the problem in detail
I have been using R & RStudio for > 5 years and never had any sort of problem upgrading. Earlier this year, I upgraded RStudio from 1.1.463 to 1.2.1335 and anytime I tried to access any .R file in my home directory or sub-directories, I got the "The system cannot find the file specified".  I was able to access files that were elsewhere on my computer. I googled a bit an found issue (https://github.com/rstudio/rstudio/issues/2488) and https://support.rstudio.com/hc/en-us/community/posts/115000552627-Getting-The-system-cannot-find-the-file-specified-message and others, but none of them was causing my problem. So I uninstalled 1.2.1335 and reinstalled 1.1.463, and I was back to being able to read/write to my home directory. So I just stayed with 1.1.463 because I have work that needed to be done. I just tried again to upgrade to RStudio 1.2.5001 and the same thing happened. So I am back to 1.1.463. What could be causing this? What should I check? I have attached diagnostics reports from 1.1.463 and 1.2.5001

[diagnostics-report-1.1.463.txt](https://github.com/rstudio/rstudio/files/3730351/diagnostics-report-1.1.463.txt)
[diagnostics-report-1.2.5001.txt](https://github.com/rstudio/rstudio/files/3730352/diagnostics-report-1.2.5001.txt)

Thanks

**Comment by kevinushey** [comment]
The problem is that your R_USER environment variable (and hence, your HOME environment variable) has a trailing slash:

```
$HOME
[1] "C:/Users/drnevich/"

$R_USER
[1] "C:/Users/drnevich/"
```

Unfortunately, RStudio v1.2 has a bug where this case is not properly handled. At this point, the simplest workaround is to update your environment variables to remove the trailing slash.

**Comment by jdrnevich** [comment]
Thank you! I removed the trailing slash from $HOME and $R_USER and now 1.2.5001 can access my files.
