### ISSUE TITLE
RStudio generates an error if unicode character in TEMP/TMP environment variable path

### ISSUE THREAD

**Issue by FrancoisKr** [rstudio/rstudio#5560]
Windows 10, V.1.2.5001

If environment varaible path contains a unicode character, RStudio will fail to load properly:
- Fatal error: system error 5 (access denied) _path to environment variable_
- Menus are inactive, main windows is empty or displays "the site cannot be accessed"

Example:
C:\Users\Fran**ç**ois\AppData\Local\Temp
This path in the environment variables TEMP/TMP will cause an error.

Change to C:\TEMP and the RStudio runs perfectly.

**Comment by kevinushey** [comment]
To be clear, did you modify your environment variable explicitly to include this? Or are these just the default settings picked up on your machine?

**Comment by FrancoisKr** [comment]
C:\Users\François\AppData\Local\Temp is the default path for both my TEMP and TMP environtment variables.

It looks like it's a unicode issue because the error message displays the path, and in the error message the "ç" is not displayed correctly.

Changing to C:\TEMP is a workaround.

**Comment by kevinushey** [comment]
Do you have any other user accounts on your system?

I tried creating an account called `鬼`, and in my case Windows used a short path name instead (sidestepping encoding issues):

IIRC, Windows only generates short path names for files in a directory if there happens to be more than one path, and one or more of the paths requires that representation to be disambiguated.
