### ISSUE TITLE
Crashing caused by crayon

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#5561]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001 (fresh install) (also tried preview)
    OS Version      :  Ubuntu 18.04
    R Version       :  3.6.1 (fresh install)

### Steps to reproduce the problem
```
options("crayon.enabled" = TRUE)
```

### Describe the problem in detail

1. After running the options above, the help tooltip when autocompleting functions didn't work (full of Unicode characters)

2. RStudio crashed (every 5-10 minutes)

### Describe the behaviour you expected

Not crashing ;)

### Details

Onscreen error:
```
R Session aborted
R encountered a fatal error
The session was terminated
```
From logs
```
16 Oct 2019 09:27:19 [rsession-ncsg3] ERROR r error 4 (R code execution error) [errormsg=Error in parse(text = capture.output(x)) : <text>:1:1: unexpected input|||1: |||    ^|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) /var/lib/jenkins/workspace/IDE/open-source-pipeline/v1.2-patch/src/cpp/r/RExec.cpp:171; LOGGED FROM: SEXPREC* rstudio::r::sexp::PrimitiveWrappers::operator[](SEXP) /var/lib/jenkins/workspace/IDE/open-source-pipeline/v1.2-patch/src/cpp/r/RSexp.cpp:1633
```

**Comment by kevinushey** [comment]
Sorry, I wasn't able to reproduce. Are there any other steps that I might be missing?

**Comment by csgillespie** [comment]
My Rprofile! I've narrowed it down to running:

```
options("crayon.enabled" = TRUE)
prettycode::prettycode()
```
In the screenshot, notice the odd Unicode in the help

![2019-10-16-1571246521_screenshot_1920x1080](https://user-images.githubusercontent.com/1267747/66942940-16a60e80-f042-11e9-83cb-104ab0c2fc7d.jpg)

**Comment by kevinushey** [comment]
Thanks! I can reproduce now.
