### ISSUE TITLE
Different colour of inline code chunks for RMarkdown

### ISSUE THREAD

**Issue by JAQuent** [rstudio/rstudio#5562]
Is there a way to add that inline code chunks `r mean(x)`  are highlighted in a different colour than the main text? For certain things, this is already done (e.g. *italic*). I think it grealty increases the readability of the text, into which code is inserted, in text editor.

**Comment by ronblum** [comment]
@JAQuent Which theme were you using when you saw an issue? I'd like to try it out and see if I can reproduce, as it might be an issue with specific themes.

**Comment by JAQuent** [comment]
I find this with RStudio theme: Classic and Editor theme: Merbivore Sorft.
