### ISSUE TITLE
1.2.5001 exits with the status code 1 without printing any error messages

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#5563]
I'm trying to update the FreeBSD port to 1.2.5001 but the resulting executable/usr/local/lib/rstudio/bin/rstudio  just exists without any error messages.

Every failure should be accompanies with the error message describing what went wrong.

FreeBSD 12 amd64.

The previous version 1.2.1335 worked fine.

**Comment by kevinushey** [comment]
Can you elaborate on a few things?

1. Is the process simply exiting, or is it crashing? Is it exiting with some exit code?
2. Are you able to use `gdb` or something similar to get a stack trace seeing where RStudio is deciding to exit?
3. Are you able to run a diagnostics report? You should be able to do so with e.g. `rstudio --run-diagnostics`.

**Comment by yurivict** [comment]
I found the reason, it doesn't print the error message when ```/proc/self``` is missing, and fails silently.

**Comment by yurivict** [comment]
ping
