### ISSUE TITLE
Keyboard focus contrast user controllable

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#5567]
Currently the focus-visible style displays a prominent gold border, this may be distracting for users that don't need such a high contrast UI. 

Make the display of keyboard focus indicators subtle (but visible) by default and give the user control over making it high contrast in the Accessibility Options.

**Comment by gtritchie** [comment]
Focus rectangle has been changed from gold to a less jarring blue. Making it user-configuration isn't critical for 1.3, so moving out of that milestone.
