### ISSUE TITLE
Replacing the "Project" shortcut icon with the "Current Directory" shortcut icnon in the File pane

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5569]
I would like to make a bold suggestion. It might be too much of a change, but I think it can be a notable improvement.

I think it would be a good idea to replace the "Project" shortcut icon on the top of the File pane with the "Current Directory" shortcut icon (expected to be an "arrow" to match the icon on the top of the console). This also applies to the "Project" directory shortcut icon that is shown on the top of the "Open a File" window.

The rationale is that if the "Project" and "Current" directories are the same, then we will not lose anything by displaying the "Current" directory shortcut icon. On the other hand, if the "Project" directory is different from the "Current" directory, then users will probably be more interested in the "Current" directory than the "Project" directory. So we will be better off to show the "Current" directory shortcut icon.

Please see the two pictures below.

Picture 1:
![File pane](https://user-images.githubusercontent.com/7562230/66964855-a50f9580-f02c-11e9-9318-a5f7da19a569.png)

Picture 2:
![Open a File Window](https://user-images.githubusercontent.com/7562230/66967922-72b76580-f037-11e9-8a04-dec1c740a2b4.png)

=============================

PS. This suggestion is closely related to #5408.

**Comment by hzarkoob** [comment]
One might argue that RStduio is often used in a mode where all the four panes are shown. In that case, a similar current directory shortcut already exists on the top of the console, and displaying another one on the top of the File pane would seem redundant to the user. I think this is a fair comment. But, this can be solved by removing the shortcut on the top of the console, and creating one on the top of the File pane, as suggested above. If all the four panes are shown, then the user can use the shortcut symbol on the top of the File pane to go to the current directory instead of the one on the top of the console.

**Comment by kevinushey** [comment]
For context, the motivation behind having the Project icon: many users often use the File pane to explore directories and sub-directories outside of the project, and then later want to return back to the project root. The shortcut here was simply a quick way to accomplish that.

At least with the Files pane, the More button gives an opportunity to change the Files pane to match the current directory:

<img width="236" alt="Screen Shot 2019-10-16 at 9 52 58 PM" src="https://user-images.githubusercontent.com/1976582/66978579-56c7ba00-f05f-11e9-9e1a-21e0c47bf738.png">

But I could see both being useful.

**Comment by hzarkoob** [comment]
@kevinushey Thank you for your comment. It might be personal, but if I have to choose between the Project and Working directories, I would go for the Working directory. The following example may help illustrate this. Suppose an individual is originally from city A but lives and works in city B. The changes that they be found in city B is pretty high (maybe on a daily basis); they will visit city A only once in a while.
