### ISSUE TITLE
Files always open in last-launched RStudio window

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5575]
**Steps to reproduce:**
* Open two or more RStudio windows/sessions.
* Switch focus to the first-launched window.
* Open some `.R` file with RStudio through the file explorer (e.g. double-clicking it).

**Expected behavior:** file should open in the RStudio window that was last active.

**Actual behavior:** file opens in the RStudio window that was launched last.

**Setup:** RStudio 1.2.5005, running on windows 10.

**Comment by dfalty** [comment]
Looks like this functionality works fine on Mac (10.12.6) but not on Windows (10) for me.

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build on windows, but not on linux.

**Comment by mikebessuille** [comment]
Another example of an issue that was marked stale, then commented on, but the stale bot closed it anyway :(
