### ISSUE TITLE
Terminal should offer zsh as a choice now that it's preferred shell on macOS Catalina

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5587]
On macOS 10.15 Catalina the preferred shell has changed to `zsh`. Launching an RStudio terminal shows this (even if user has already used `chsh` to select `zsh`).

RStudio terminal should offer `zsh` as an option if it is available.

![2019-10-19_14-17-12](https://user-images.githubusercontent.com/10569626/67151479-abe01780-f27b-11e9-91db-897338a36687.png)

See also:
- https://github.com/rstudio/rstudio/issues/4699
- https://support.apple.com/en-us/HT208050
- suppress message: export BASH_SILENCE_DEPRECATION_WARNING=1 (this was done separately via #6182)

**Comment by issalezami** [comment]
how to solve it?

**Comment by luispuerto** [comment]
#6186 hasn't fixed this for me… on my dropdown menu only appears bash and custom

**Comment by gtritchie** [comment]
> #6186 hasn't fixed this for me… on my dropdown menu only appears bash and custom

What version of RStudio are you trying?

**Comment by luispuerto** [comment]
Hey! 

The preview of course. 1.3 https://imgur.com/FgpRyuu

**Comment by gtritchie** [comment]
The change to add `zsh` was made after 1.3.820 and will be in the next preview release, or you can try a daily build from https://dailies.rstudio.com/

**Comment by luispuerto** [comment]
@gtritchie OKIDOKI! 

I don't think I'll install the daily build, but good to know that is coming!

**Comment by gtritchie** [comment]
Actually we released a new preview build today, and it has it (1.3.842).

**Comment by luispuerto** [comment]
Great!! 

I just tried and it work! 

But you need to set your path correctly so RStudio pick homebrew `usr/local/bin` location instead of the system one.

**Comment by gtritchie** [comment]
RStudio is determining path to zsh from /etc/shells

**Comment by luispuerto** [comment]
ummm I'm don't know if this is totally true. I have on my `etc/shells` `/usr/local/bin/zsh` and I have to put on my zsh config the `usr/local/bin/` first so RStudio picked the correct shell and git.

**Comment by j450h1** [comment]
Anyone successfully configured this on Windows with zsh installed as per? (https://www.maketecheasier.com/install-zsh-and-oh-my-zsh-windows10/)

Trying to determine if I should open new terminals with **Custom** or **Bash(Windows Subsystem for Linux).**
