### ISSUE TITLE
Bottom line of RMD file is cut off

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#5591]
### System details

    RStudio Edition : RStudio Desktop Pro
    RStudio Version : 1.3.525.1
    OS Version      : MacOS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem
Consider the following RMD file:

````
---
title: "R Notebook"
output: html_notebook
---

```{r}
mtcars
```

```{r}
mtcars
```

Now this line is cutoff
````

If the output for both `mtcars` is rendered, the bottom line is cutoff when you scroll to the bottom of the document:
![image](https://user-images.githubusercontent.com/10444878/67240341-7f103980-f40e-11e9-86c5-7a6ff6b7b1d9.png)

I am using a font with ligatures (Iosevka) if that may be part of the problem.

**Comment by kevinushey** [comment]
I can reproduce this as well. The issue appears to be independent of the font chosen.

One workaround is to use:

```
Tools -> Global Options... -> Display
[ ] Allow scroll past end of document
```

so you can scroll past the final line to see everything.

**Comment by kevinushey** [comment]
Now tracking in https://github.com/rstudio/rstudio/issues/6261.
