### ISSUE TITLE
Error: C stack usage errors on startup in latest 1.3.x dailies

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#5594]
Catalina 10.15.1 beta 2, last couple 1.3.x RStudio Dailies (526 and 528 for sure).

Even if I remove my ~/.Rprofile, the ~/.rstudio-desktop dir and ensure no R history or data files are anywhere near the current directory, right upon starting RStudio shows a slew of

> Error: C stack usage  ##### is too close to the limit

errors and then is pretty much useless after that. Reverting to 506 fixes this.

**Comment by HanOostdijk** [comment]
528 also unworkable for me with same messages on
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18362)

**Comment by kevinushey** [comment]
Unfortunately, I'm not able to reproduce.

@hrbrmstr any chance you'd be brave enough to try using `lldb` to attach to the `rsession` process and break on `R_SignalCStackOverflow`? Hopefully we can get a glimpse of what the stack looks like -- most likely there's some runaway recursion somewhere.

**Comment by hrbrmstr** [comment]
aye. it did it again with today's most recent daily so lemme re-install that and give it a go

**Comment by hrbrmstr** [comment]
Hrm…

How do you get around `lldb` giving an "Error 1" after it tries to attach after

```
process attach --name rsession --waitfor
```

Everything I've read says "disable SIP" but that can't be the only option on Catalina.

When I tried to run it with Instruments there was more output in the console. Lots lines like this after each close to the limit message:

```
2019-10-23 10:29:04.757926-0400 rsession[47263:1491832] ERROR r error 4 (R code execution error) [errormsg: Error: C stack usage  7969376 is too close to the limit|||] at rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) /Users/admin/workspace/IDE/macos-v1.3/src/cpp/r/RExec.cpp:171; LOGGED FROM: void rstudio::session::prefs::(anonymous namespace)::setCRANReposOption(const std::string &, const std::string &) /Users/admin/workspace/IDE/macos-v1.3/src/cpp/session/prefs/UserPrefValuesNative.cpp:38|||
```

**Comment by kevinushey** [comment]
```
void rstudio::session::prefs::(anonymous namespace)::setCRANReposOption(const std::string &, const std::string &) 
/Users/admin/workspace/IDE/macos-v1.3/src/cpp/session/prefs/UserPrefValuesNative.cpp:38|||
```

At least now we know where to look! @jmchers, since this the error is being logged from the user preferences code, would you be able to take a look?

**Comment by kevinushey** [comment]
@hrbrmstr: could you also share the contents of your user preferences file? Does removing that file fix the underlying issue? See e.g. https://docs.rstudio.com/ide/server-pro/latest/r-sessions.html#customizing-session-settings for documentation for more information.

**Comment by hrbrmstr** [comment]
That link is for server (this is macOS desktop).

So, I've removed  all these dirs/files:

```
.R
~/.rstudio-desktop
Library/Application\ Support/RStudio
Library/Saved\ Application\ State/org.rstudio.RStudio.savedState
Library/Preferences/com.rstudio.desktop.plist
Library/Caches/RStudio
Library/Application Support/CrashReporter/RStudio_3A087DAC-6414-5FA9-9E10-42EE9CED7C25.plist
Library/Safari/LocalStorage/https_www.rstudio.com_0.localstorage-wal
Library/Safari/LocalStorage/https_www.rstudio.com_0.localstorage
Library/Safari/LocalStorage/https_www.rstudio.com_0.localstorage-shm
Library/Application\ Support/RStudio/QtWebEngine/rstudio-desktop
Library/Caches/RStudio/QtWebEngine/rstudio-desktop
```
and also removed `~/.Rprofile` and `~/.Renviron`

When I startup today's RStudio-1.3.546 I get this, still:

![image](https://user-images.githubusercontent.com/509878/67579514-a159ce00-f712-11e9-9d74-1f017715cd8a.png)

but…where is it picking up that custom theme setting from?

**Comment by jmcphers** [comment]
> where is it picking up that custom theme setting from?

`~/.config/rstudio`

**Comment by hrbrmstr** [comment]
ah! going there now.

**Comment by hrbrmstr** [comment]
ok, first I just move the dir aside and re-installed 1.3.546 and it started fine w/o the stack traces. 

lemme zip up the dir and get it to you.

**Comment by hrbrmstr** [comment]
Moving just this back into that dir re-introduces the stack issues: 

[rstudio-prefs.json.zip](https://github.com/rstudio/rstudio/files/3773745/rstudio-prefs.json.zip)

**Comment by hrbrmstr** [comment]
Looks like it's the "use secure cran" setting that causes it. When I uncheck it (to get rid of the warning msg) — b/c CRAN is literally 6 inches from me :-) — it causes the stack usage messages.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.3.370.
