### ISSUE TITLE
Invalid rectangle passed

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#5596]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.1

### Steps to reproduce the problem

I can't, it seems like a state of the computer or related to some updates I ran. I installed the latest packages with `sudo apt update && sudo apt upgrade`:

```
  bluez bluez-cups bluez-obexd libbluetooth3 libxkbcommon-dev libxkbcommon-x11-0 libxkbcommon0
  linux-generic linux-generic-hwe-16.04 linux-headers-generic linux-image-generic linux-libc-dev
  r-cran-kernsmooth
  linux-headers-4.15.0-66 linux-headers-4.15.0-66-generic linux-image-4.15.0-66-generic
  linux-modules-4.15.0-66-generic linux-modules-extra-4.15.0-66-generic
```

### Describe the problem in detail

I got this message on the R terminal in red

```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

### Describe the behavior you expected

I didn't expect to have this error appear on the R terminal...

Feel free to close this report as not reproducible, but I leave it here to document it might happen.

**Comment by dfalty** [comment]
How often does this message appear, or was it just once after the upgrade?

**Comment by llrs** [comment]
It appeared just once, but I haven't seen it since then, even if I updated some other (ubuntu) packages while having RStudio open. I provided the list of updated packages in case they are somehow related to RStudio internals

**Comment by ronblum** [comment]
@llrs Thank you for the info! I'm closing this since it only appeared the one time, but if you run into this issue again, please update the ticket to let us know. Thanks!

**Comment by llrs** [comment]
Great @ronblum ! I hope I don't need to update the issue!!
