### ISSUE TITLE
Unable to build new project in Rstudio desktop using Subversion repository after updating Windows 10 to build 1809

### ISSUE THREAD

**Issue by enaughten** [rstudio/rstudio#5601]
### System details

    RStudio Edition : Desktop 
    RStudio Version :  1.2.5001 (Build 1468)
    OS Version      :  Windows 10 version 1809
    R Version       :  MRO 3.5.3

### Steps to reproduce the problem
Install Rstudio Desktop and Collabnet Subversion Client on Windows 10 Build 1809 system

### Describe the problem in detail

After upgrading my Windows 10 build to version 1809 (OS Build 17763.740), I now get an error when trying to build a new project in Rstudio using Version Control>SVN (checkout a project from a Subversion repository). When I select "Create Project" it opens a window with the following error: "Error calling capture_console_output: 87."

I have other desktops with the exact same applications installed that are on Windows 10 version 1709 and 1803 and the issue does not exist there. Something associated with the Windows 10 1809 update triggers the problem. I have tried running Rstudio and svn.exe in Windows compatibility mode, but the error persists.  Also I have tried several other desktops with Windows 10 Build 1809 and they all exhibit the same problem.

### Describe the behavior you expected

Ability to build project by connecting to my Subversion repository.

Thank you for taking the time to file an issue!  -->

**Comment by enaughten** [comment]
Update>After updating Windows build from 1809 to 1903, the issue was resolved. I also tested build 1909 with the same result. This appears to be a bug specific to running Rstudio/Subversion on Windows 10 build 1809.

**Comment by kevinushey** [comment]
Glad to hear things are fixed -- thanks for reporting back!
