### ISSUE TITLE
`rstudio-prefs.json`: Some settings require unboxed notation of values

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#5606]
Some setting values in `rstudio-prefs.json` require to be unboxed, otherwise unwanted consequences are triggered (e.g. the source pane being greyed out).

- `highlight_selected_line`
- `syntax_color_console`
- `show_invisibles`
- `highlight_r_function_calls`

There may be more. I suspect that it might apply to all boolean values?

To be more clear, `key: [value]` triggers the error described above. `key: value` is fine.

**Comment by jmcphers** [comment]
Yes, you can't put these values in an array -- only scalars are accepted. You can see the formal JSON schema here:

https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/schema/user-prefs-schema.json

Right now we just warn if the values don't conform to schema, but we should probably do something more drastic as the invalid values can indeed cause trouble downstream. I'll use this issue to track that work.

**Comment by pat-s** [comment]
Thanks! I meanwhile accounted for this by simply using `auto_unbox = TRUE` in `jsonlite::write_json()`. A more robust solution upstream is however always preferred :)
