### ISSUE TITLE
Ctrl+= for Zoom In not working but Ctrl+- for zoom out is working

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#5612]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1578
    OS Version      : Windows 10
    R Version       :  3.6.1

### Steps to reproduce the problem
Press `Ctrl+=` then `Ctrl+-`

### Describe the problem in detail
Zoom out works but zoom in doesn't work

### Describe the behavior you expected
Both zoom out and in work. I was able to assign zoom in to Ctrl+= in the modify keyboard shortcuts dialog to get the behavior I'm after. However, neither `Ctrl+-` nor `Ctrl+=` were assigned and yet `Ctrl+-` worked to zoom out.

This is the current setup and they both are active and working.
![image](https://user-images.githubusercontent.com/5327505/67426075-d17f6f00-f635-11e9-9579-8d0fca817055.png)

The behavior I'd expect out of the box is that these are both explicitly assigned `Ctrl+=` to Zoom In and `Ctrl+-` to Zoom Out.

**Comment by AukeSchaap** [comment]
The correct keyboard shortcut for 'Zoom In' is Ctrl++ or in other words, Ctrl+Shift+=. This is probably intended as under 'View' you can see the shortcut for 'Zoom In' being mentioned.

**Comment by kendonB** [comment]
I see. The lack of symmetry between the two commands is a bit weird then with one requiring the shift and the other not. A few other programs default behavior on my machine:

Chrome: Ctrl+=, Ctrl+Shift+=, Ctrl+-, and Ctrl+Shift+- all work.
VSCode: Ctrl+=, Ctrl+Shift+=, Ctrl+-, and Ctrl+Shift+- all work.
Notepad: Ctrl+=, Ctrl+- work.
Notepad++: None of these work on this laptop but they appear to be mapped to Ctrl+NUMPAD+ and Ctrl+NUMPAD-.
Git bash: Ctrl+=, Ctrl+Shift+=, Ctrl+- work.

I quite like the Chrome/VSCode behavior where they just all work.

**Comment by kevinushey** [comment]
I agree it would be useful (for symmetry) to have all of these work, or at least have all of the variants using Shift (or not Shift) to work.

**Comment by gtritchie** [comment]
Somewhat related: #1683
