### ISSUE TITLE
Slow .libPaths refresh in RStudio 

### ISSUE THREAD

**Issue by narayanana** [rstudio/rstudio#5627]
### System details

    RStudio Edition :  (on AWS platform)
    RStudio Version : 1.0.153 
    OS Version      :  Linux, Gnu 
    R Version       : 3.3.3

### Steps to reproduce the problem
step 1: on RStudio console prompt: type (without quotes) .libPaths() # this would display the default setting 

step 2: Change the default of .libPaths() to another path (on network)
 .libPaths("<new_path on enterprise network fileshare>")

step3: repeat step 1 #to display updated settings
After the update, .libPaths() and the window panes take several minutes to display updated information.

### Describe the problem in detail
While on AWS and using browser based RStudio, it takes a long time to refresh information on the screen, when the default .libPaths() settings are changed to enterprise network fileshare location. When it's busy (to update Rstudio window panes), RStudio appears to be frozen, i.e one can't work on text editor or browse files, packages etc...  

### Describe the behavior you expected
.libPaths() update takes long time under browser based RStudio on AWS if default is pointing to enterprise network fileshare. The refresh/update is almost instantaneous when it is set to an ephemeral fileshare associated with an EC2 instance or when executed at Linux shell mode using RCMD.
 
If a script is "sourced" (click on "Source" button); the script gets executed immediately; however, RStudio window panes don't get updated immediately due to busy background processes.

**Comment by jmcphers** [comment]
Thank you for reporting this! We are currently tracking the issue in https://github.com/rstudio/rstudio/issues/2038.

**Comment by kevinushey** [comment]
When library paths are changed, RStudio re-indexes all of the installed packages. This implies e.g. reading DESCRIPTION files and other package metadata to populate the Packages pane, which may be slow when your R library lives on a NFS.

**Comment by narayanana** [comment]
Thanks for your response. However, .libPaths() update was much faster (almost instantaneous) when executed in Linux shell mode and currently working directory being the "ephemeral" home directory associated with the EC2 instance.  For this reason, the workaround for the time being has been to run scripts in batch mode on Linux shell.

**Comment by kevinushey** [comment]
Yes, that is expected.
