### ISSUE TITLE
Access Upload feature of RStudio IDE 

### ISSUE THREAD

**Issue by pitla1** [rstudio/rstudio#5628]
The issue tracker is not for questions. If you have a question, please feel free to ask it on our community site, at https://community.rstudio.com/c/rstudio-ide.

Is it possible to access the feature of "Upload file to server" option remotely or via a script? If so, would highly appreciate your assistance! I would like write a script/function to utilize the "upload" feature of IDE for sending a zip file to a target location and unzip automatically.   

Many thanks!

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
