### ISSUE TITLE
Request: remember scrollbar position in panes

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5629]
If I browse for the help of some function (e.g. `help(heat.colors)`), check the documentation in the Help pane, scroll down on it, and then switch to a different pane in the same space (say, the Plots pane), then when I return to the Help pane, the scrolling will be reset to the top.

Would be nice if the scrolling position at which it was would be remembered, as sometimes one wants to check some plot against the documentation of the function that produced it, or look up some file from where the documentation came as the documentation is being read.

**Comment by kevinushey** [comment]
This appears to be a regression: it works as expected for me with RStudio v1.1.463 on macOS.
