### ISSUE TITLE
Reopen with encoding discards changes

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/rstudio#5630]
I'm working on different workstations and sometimes have to change encoding.

However, when you want to reopen a file with a different encoding, RStudio discards all your previous changes, with no warning or confirmation popup.

I'm somehow pretty sure that this was not the case before and that my changes were kept in memory.

### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.1335
    OS Version      : Win-10
    R Version       : 3.6.1 (2019-07-05)

### Steps to reproduce the problem

- Open a file
- Make some changes
- Hit File > reopen with encoding > any encoding
- Sit in the corner and cry for the loss of your work

EDIT: I just realized I could just Ctrl-Z the whole thing and get my work back. Still, a confirmation of saving before reencoding would be great.

**Comment by kevinushey** [comment]
I agree that we should save, or prompt to save, before re-opening the document with a new encoding.
