### ISSUE TITLE
Git commit fails when temp folder has been deleted

### ISSUE THREAD

**Issue by mirh** [rstudio/rstudio#5633]
So.. I don't know how or why my R temp folder got removed (after a month of uptime windows decided to clean it? I wiped it manually or with some tool?), long story short though, every time I tried to commit from the GUI the ide was throwing a `The system cannot find the path specified` error. 

After some tinkering with ProcMon I found out [this](https://github.com/rstudio/rstudio/blob/v1.2.1335/src/cpp/session/modules/SessionGit.cpp#L879L885) should be the call that fails badly. It seems to query the folder, then just write into it blindly but you can't into an unexisting path. 

It would be nice if the system was more robust. 
I also got an error in the console (on saving iirc) similar to #4188, but at the end of the day there didn't seem to be any ill effect from that.

**Comment by kevinushey** [comment]
We could in theory try to re-create the R session temporary directory if it were to vanish underneath us, but R and RStudio both in general take the view that the session temporary directory will live as long as the session itself does.

We have seen in some cases that tools will try to auto-clean the machine's temporary directory; however, it also comes with the downside that folders currently in use get deleted as well.

You could also try setting the environment variable `TMPDIR` to instruct R to use a different temporary directory (you will need to restart R + RStudio after making that change).

**Comment by mirh** [comment]
I guess like not caring about every corner case and the kitchen sink is still kinda fair. 

Though I'd like at least a \*way\* more informative warning message. 
Or don't write blindly, or assume every time is the first time, or... I'm not really sure what the other files in there are for.
