### ISSUE TITLE
styling issues w/ dark theme on Edge

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5637]
### System details

    RStudio Edition : Server (devmode)
    RStudio Version : v1.3.546
    OS Version      : macOS 10.15.0
    R Version       : 3.6.1

### Steps to reproduce the problem

Run a devmode server (in my case, from a macOS host) and then connect from a Windows box.

### Describe the problem in detail

Some UI elements are not styled as expected.

![Screen Shot 2019-10-25 at 3 01 11 PM](https://user-images.githubusercontent.com/1976582/67607192-7b472480-f738-11e9-9c94-c4bd4cc62cd1.png)

In particular:

- There are white bars in the tab bars where the regular dark background color would be expected;
- The placeholder text in the search bars is too dark.

### Describe the behavior you expected

Consistent styling.

![Screen Shot 2019-10-25 at 3 03 06 PM](https://user-images.githubusercontent.com/1976582/67607209-9154e500-f738-11e9-8662-42aafd147706.png)

### Note

It's possible that this works as expected with a real, production version of RStudio Server -- but that's worth validating before the v1.3 release.

**Comment by gtritchie** [comment]
We'll have to decide how much we care about current Edge versus soon-to-be-Chromium-based Edge (assuming this was logged against "current Edge").

**Comment by gtritchie** [comment]
https://www.theverge.com/2019/8/20/20813510/microsoft-chromium-edge-beta-download-release-macos-windows

**Comment by jmcphers** [comment]
I don't think we want to invest in a fix for this given that the non-Chromium Edge is going away.
