### ISSUE TITLE
Feature request: Document outline default options

### ISSUE THREAD

**Issue by mik3y64** [rstudio/rstudio#5638]
I use **document outlines** in both R and RMD scripts all the time. Whenever I close and reopen any files, the document outline is gone, regardless of the previous states. My current solution is to manually toggle document outline with hotkey, and obviously that's not ideal for every single newly opened files and it becomes annoying because I use it all the time.

Feature request: Please allow a global option for users to enable **document outline** on/off by default, including newly opened files. 

Thank you for creating the best IDE for R.

**Comment by kevinushey** [comment]
There is an option for this -- in Tools -> Global Options... -> R Markdown, see:

- [ ] Show document outline by default

<img width="601" alt="Screen Shot 2019-10-28 at 8 54 19 AM" src="https://user-images.githubusercontent.com/1976582/67694463-9ac09600-f960-11e9-9cc9-265b346c3ff9.png">

I think this should accomplish what you need -- please feel free to re-open if this is insufficient in some way.

**Comment by clemenskuehn** [comment]
I use document outline a lot in R source code (as [mik3y64](https://github.com/mik3y64) also seems to do), but your solution only applies to R Markdown. 

Accordingly, in RStudio 2022.02.2 Build 485, your solution does not solve my problem of having the document outline turned on by default in R source code.

**Comment by edwardhealey** [comment]
+ 1 would benefit from this being a global option

**Comment by joshua-theisen** [comment]
+1

**Comment by Sibojang9** [comment]
+1 please solve this old issue.
