### ISSUE TITLE
RStudio does not clear workspace when doing a package “Install and Restart”

### ISSUE THREAD

**Issue by aryoda** [rstudio/rstudio#5639]
I have an open project (a package) in RStudio and my workspace contains variables, eg.

`a <- 1`

When I choose the menu item *Build > Install and Restart* I can see (in the console) that the R session is restarted, but the workspace is **not** cleared (I can still see that `a` is `1`):

[![enter image description here][1]][1]

    Restarting R session...
    
    > library(tryCatchLog)

[![enter image description here][2]][2]

I would have expected to get a clear workspace after the restart (as *Session > Restart R* does).

Is this possibly only a "misnomer" (the menu item was called *Build and Reload* in older RStudio versions AFAIKR)?

In the project options I can still find the old name in the *Build tools** section: 
*Build and Reload -- R CMD INSTALL additional options*

PS: I am using RStudio 1.1.463 on Ubuntu with R 3.4.4 and can also reproduce this on Windows with RStudio 1.2.x and R 3.6.1

The *Restore .RData* option is not the reason for that:

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/kanM7.png
  [2]: https://i.stack.imgur.com/LFd58.png
  [3]: https://i.stack.imgur.com/ZthKX.png

See also the related SO question:
https://stackoverflow.com/questions/58546336/rstudio-does-not-clear-the-workspace-of-a-package-project-when-doing-install-an

Maybe related:
#2841

**Comment by dfalty** [comment]
I can reproduce that Install and Restart doesn't clear environment like Session > Restart R does when you have `save workspace to .RData on exit` set to `never`. Thanks for the report!

**Comment by MichaelChirico** [comment]
Also have this. It's extremely painful when you've got several GB of objects loaded in the session & RStudio backs up & reloads this env, adds to dev cycling by several orders of magnitude.
