### ISSUE TITLE
The following error occurred when installing any R package(1.clang: error: unsupported option '-fopenmp';2.ERROR: compilation failed for package ‘mgcv’)

### ISSUE THREAD

**Issue by CK-X** [rstudio/rstudio#5640]
Rstudio.        MacOS Catalina 10.15
-----------------------------------------------------------------------------------------

> install.packages("mgcv")

  There is a binary version available but the source version is later:
     binary source needs_compilation
mgcv 1.8-29 1.8-30              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source package ‘mgcv’

试开URL’https://cran.rstudio.com/src/contrib/mgcv_1.8-30.tar.gz'
Content type 'application/x-gzip' length 936510 bytes (914 KB)
==================================================
downloaded 914 KB

* installing *source* package ‘mgcv’ ...
** 成功将‘mgcv’程序包解包并MD5和检查
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c coxph.c -o coxph.o
clang: error: unsupported option '-fopenmp'
make: *** [coxph.o] Error 1
ERROR: compilation failed for package ‘mgcv’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/mgcv’
Warning in install.packages :
  installation of package ‘mgcv’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/n2/zvt2c8dn257f9dh_fq4d3xmr0000gn/T/RtmpYJhH2H/downloaded_packages’

**Comment by pascaloettli** [comment]
To me, it looks like more a problem with Catalina and the changes introduced in the Command Line Tools. Do you get the same error in a terminal?

**Comment by CK-X** [comment]
Yes!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pascal Oettli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 下午2:01
收件人:&nbsp;"rstudio/rstudio"<rstudio@noreply.github.com&gt;;
抄送:&nbsp;" Li Geng"<2716581852@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rstudio/rstudio] The following error occurred when installing any R package(1.clang: error: unsupported option '-fopenmp';2.ERROR: compilation failed for package ‘mgcv’) (#5640)




To me, it looks like more a problem with Catalina and the changes introduced in the Command Line Tools. Do you get the same error in a terminal?

**Comment by kevinushey** [comment]
Please see https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/.

**Comment by jayden199012** [comment]
@CK-X Did you manage to resolve it in the end?
