### ISSUE TITLE
Please add FreeBSD to the list of supported platforms

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#5641]
In these places:
* On your website: https://rstudio.com/products/rstudio/
* In the README file  ```Runs on all major platforms (Windows, Mac, and Linux)```: https://github.com/rstudio/rstudio/blob/master/README.md

Thank you,
Yuri

**Comment by jmcphers** [comment]
Since we don't formally support or maintain the FreeBSD port, we can't take responsibility for it in our materials. We would however be happy to link to your FreeBSD port in our README. What URL should we point people to?

**Comment by yurivict** [comment]
The URL of the port: https://www.freshports.org/devel/RStudio/

Instructions to install: run the command 'pkg install RStudio' as root.

Thank you,
Yuri

**Comment by oddodaoddo** [comment]
The FreeBSD port is marked broken and there is no matching package.

**Comment by yurivict** [comment]
> The FreeBSD port is marked broken and there is no matching package.

The port is fixed now.
