### ISSUE TITLE
Support to install package from github downloaded zip

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#5642]
Sometimes user may have to download the package bundle then install them manually (network limit, proxy, cooperate firewall,...). With CRAN source .tar.gz we can use `install packages` from RStudio menu directly, but this doesn't work with zip file downloaded from github. And many users have tried to download github repo as zip then install it (there are quite several questions in stackoverflow).

Using `install packages` from RStudio on this kind of zip will recognize it as win-binary and fail. Using devtools::install_local can solve this problem, but it'll be more user friendly if `install package` menu can support it directly.

**Comment by dracodoc** [comment]
Yes I knew the difference. `devtools::install_local` can handle this zip directly. 

I actually wrote some utility function to do this because our cooperate R server don't have most recent version of devtools. Simply util::unzip the zip to temp folder, then `devtools::install` from the unziped folder.

**Comment by GreenEric** [comment]
Thanks. It does help me with my issue.
When trying devtools::install_github, there is no exception that msg "Failed to connect to api.github.com port 443: Connection refused", while github webpage is OK.
Been trying so long to figure out how to direct download tar.gz format from github, now you solved my issue, many thanks!
