### ISSUE TITLE
automatically detect file type from shebang #! if no file extension

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#5643]
Currently, it appears that when opening a text file Rstudio inspects the file extension to determine the type of file, and when a file extension is missing, Rstudio defaults the file type to "Text File".

Frequently, executable shebang scripts do not end with a file extension.
In those cases, it would be nice if Rstudio inspected the first line of the file, and if it's a shebang, then it would mark it appropriately so that the correct syntax highlighting and auto-completion is applied. 
e.g, 
if the first line is `#!/usr/bin/Rscript` then set the file type to "R Script"
if the first line is `#!/usr/bin/python`, then set the file type to "Python"
If the first line is `#!/bin/bash` then set the file type to "Shell"

Ideally this guessing would also be robust to other usage like
`#!/usr/bin/env Rscript` 
and 
`#!/usr/bin/Rscript --vanilla --default-packages=utils`

And also other locations of where the interpreters might have been installed, such as  under `/opt` or `/usr/local` or `/home/username/.local`

**Comment by R-Hannibal** [comment]
@t-kalinowski , thanks so much for finding and reporting this issue. 

We have a fix in place in our latest daily build of the 1.4 release (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by t-kalinowski** [comment]
Hi @R-Hannibal,

I'm happy to hear this feature is being worked on.
I downloaded the daily and tried to launch it but encountered an error:
```
tomasz@tower:~$ rstudio
rstudio: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

running locate:
```
(base) tomasz@tower:~$ locate libssl.so
/home/tomasz/anaconda3/lib/libssl.so
/home/tomasz/anaconda3/lib/libssl.so.1.1
/home/tomasz/anaconda3/pkgs/openssl-1.1.1g-h7b6447c_0/lib/libssl.so
/home/tomasz/anaconda3/pkgs/openssl-1.1.1g-h7b6447c_0/lib/libssl.so.1.1
/opt/nvidia/nsight-compute/2020.1.2/host/linux-desktop-glibc_2_11_3-x64/libssl.so
/opt/nvidia/nsight-compute/2020.1.2/host/linux-desktop-glibc_2_11_3-x64/libssl.so.1.1
/opt/nvidia/nsight-systems/2020.3.2/host-linux-x64/libssl.so
/opt/nvidia/nsight-systems/2020.3.2/host-linux-x64/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

I'm on Ubuntu 20.04.1 LTS

**Comment by jmcphers** [comment]
Those errors are a result of downloading the Xenial build of RStudio of Rstudio Desktop. You need the Bionic build: 

https://dailies.rstudio.com/rstudio/oss/bionic/x86_64/

**Comment by t-kalinowski** [comment]
Thanks! Just tried the daily and the new shebang filetype auto detection works great!
