### ISSUE TITLE
Add LSApplicationCategoryType to Info.plist on macOS build

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#5645]
If y'all are open to it I can file a PR this week to https://github.com/rstudio/rstudio/blob/d37fa226047c8203ab3af6e5d1979220da831e4f/src/cpp/desktop/Info.plist.in that adds an app category; perhaps this one:

```
<key>LSApplicationCategoryType</key>
<string>public.app-category.developer-tools</string>
```

**Comment by kevinushey** [comment]
Sounds like a good idea to me -- a PR would be welcomed.
