### ISSUE TITLE
git history pane does not show moved files

### ISSUE THREAD

**Issue by antoine-sachet** [rstudio/rstudio#5649]
## Expected behaviour

The git history pane in Rstudio should show the full git history including moving/renaming of files.

## Actual behaviour

The git history pane in Rstudio does **not** show anything for moved/renamed files.

## Steps to reproduce

- open a project under git version control
- move a file using `git mv`
   (or simply move it and stage both the new and deleted files)
- commit
- open the git history pane and select this last commit: it does not show any changes

## Why it is a big deal

One of our shiny apps "inexplicably" broke after a what _looked like_ a very minor update, according to the git history in Rstudio. The issue was that a folder had been renamed but this only became apparent using the command line (`git whatchanged`, etc).

This was observed on both Rstudio desktop for Windows (version unknown) and Rstudio server on Ubuntu (Version 1.2.1335).

**Comment by dfalty** [comment]
Thanks for the bug report! I can reproduce on Mac with version 1.2.5018 as well as 1.1.463 so it looks like it's been this way for a while unfortunately. The history doesn't show anything if there is just a move without additional changes.
