### ISSUE TITLE
Prompt to install packages from R Markdown YAML header

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#5654]
In RStudio 1.2, the IDE began inferring package dependencies from the code.

However, it does not infer package dependencies from the YAML header in R Markdown documents.

For example,
```
---
title: "Portolio Report"
...
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---
```
https://github.com/sol-eng/stockportfolio/blob/86c5bfb156601fd8fe824d07578257703f44bdb4/report-portfolio/portfolio.Rmd#L36

I would have expected the IDE to prompt me to install `flexdashboard` in this context.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/4779.
