### ISSUE TITLE
Zeroes display differently before & after decimal point

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#5664]
Using modern theme, ubuntu modern font, but that shouldn't matter necessarily;
Zeroes before decimal point are tall. After the point are fat. SessionInfo follows.

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1 
```
RStudio preview version 1.2.5013

![RStudio_Bug_Zeroes](https://user-images.githubusercontent.com/4599748/67817207-dbf09d00-fa69-11e9-8b6c-c9bdde2fd83e.png)

**Comment by dfalty** [comment]
I can't reproduce this on Mac 1.2.5018. Not sure what's going on.

**Comment by SimonDedman** [comment]
FWIW editor font is ubuntu mono 10, but I feel that shouldn't matter since the character prints 'correctly' left of the decimal, so it seems as if a different character is being called to the right? Maybe different font sets assign both what's being called on the left, and what's being called on the right, to the same character, whereas other font sets have separate characters? Spitballing here.

**Comment by SimonDedman** [comment]
To add: same before & after colons in times
![Rstudio zeroes bug 2](https://user-images.githubusercontent.com/4599748/67972486-00fd2100-fbcc-11e9-84ff-d47f1dfd1fb3.png)

**Comment by kevinushey** [comment]
I can reproduce this on Ubuntu, but I doubt there's much we can do (it's probably some kind of quirk of Qt / QtWebEngine).

**Comment by mikebessuille** [comment]
Jon, we're not sure if this is fixed or not (just by the move to Electron)

**Comment by romainfrancois** [comment]
What is this a screenshot of ?

![RStudio_Bug_Zeroes](https://user-images.githubusercontent.com/4599748/67817207-dbf09d00-fa69-11e9-8b6c-c9bdde2fd83e.png)

**Comment by kevinushey** [comment]
This is a screenshot of the data viewer; e.g. `View(data.frame(x = 20.01))` should suffice to try and reproduce.

I don't think we need to fix this necessarily; just check whether the switch to Electron did indeed resolve this issue.

**Comment by romainfrancois** [comment]
I don't see it in the server: 

<img width="336" alt="image" src="https://user-images.githubusercontent.com/2625526/194115062-29093a57-9b77-4818-9547-279514618d68.png">

or in a recent electron build: 

<img width="459" alt="image" src="https://user-images.githubusercontent.com/2625526/194115177-ad64b976-0eff-4e28-bd4d-022225665457.png">

The cell has these css classes, I don't think any of them does this: 

<img width="304" alt="image" src="https://user-images.githubusercontent.com/2625526/194115739-e7510fbb-0f05-4a0d-ad51-80a0a4c3c8ea.png">

Maybe this is a feature of the ubuntu modern font ?

**Comment by jonvanausdeln** [comment]
I also can't reproduce this on the most recent electron build.

Version 2022.11.0-daily+244 on Ubuntu 22.04

@SimonDedman can you confirm this is no longer an issue?

**Comment by SimonDedman** [comment]
@jonvanausdeln No longer the case on RStudio v 2022.07.1
