### ISSUE TITLE
RStudio daily: Broken on Ubuntu 19.10

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#5672]
The latest daily (1.3.556) does not open on Ubuntu 19.10 due to

```sh
libssl.so.1.0.0: Cannot open shared object file: No such file or directory
```

v1.3.533 still works.

Haven't tested the ones in between the two mentioned versions.

**Comment by kevinushey** [comment]
Does Ubuntu 19.10 still provide libssl 1.0.0?

**Comment by pat-s** [comment]
Taking a quick look at `libssl` in the ubuntu package universe it seems that `libssl-dev` is at v1.1.1 since 18.04 already.

I am not sure if there was just a renaming of the linker or similar - I just tried this in a VM as some students of mine had issues with the latest daily there.

Interesting is that 1.3.533 still works. So somewhere on the way there was maybe a change in RStudio regarding libssl query? 

Just wanted to let you know about this issue - it is not of utmost importance for me. And its about the dailies anyways on a non LTS release, so...

**Comment by jmcphers** [comment]
Is it possible that you downloaded the Ubuntu 16 instead of the Ubuntu 18 version? The Ubuntu 18 version should be linked against the newer libssl.

**Comment by pat-s** [comment]
Nope, def. on 19.10 :) And some other people confirmed the same issue on separate machines.

**Comment by kevinushey** [comment]
Are you sure you installed this:

https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.3.568-amd64.deb

and not this:

https://s3.amazonaws.com/rstudio-ide-build/desktop/xenial/amd64/rstudio-1.3.568-amd64.deb

Note that the daily builds page will advertise the Xenial build by default (that is, the big Ubuntu 64-bit button displayed at the top of https://dailies.rstudio.com).

**Comment by pat-s** [comment]
Oh... 🤦‍♂ of the week.

I really think that happened. Can't really verify as the downloaded files look the same namewise. Also I can't exactly recall which button I clicked last time.
Just installed the latest "Ubuntu 18" daily and it starts just fine.

So I assume the error was just on my side. Sorry for stealing your time on this.

@jmcphers I initially misunderstood your comment - I thought you were referring to the OS in this case and not the rstudio.deb 🤦‍♂

**Comment by jmcphers** [comment]
No worries, this is a common point of confusion! We used to have the OS name in the .deb filenames. Might be worth doing that again.

**Comment by mayeulk** [comment]
Hi, for those reading this: Could you please clarify which Rstudio version (URL) it is advised to use on Ubuntu 19.10? Is it stable? (I run Ubuntu 19.04 and I'm considering upgrading to 19.10). Thank you!

**Comment by pat-s** [comment]
The one based on Ubuntu 18.04 (bionic).
