### ISSUE TITLE
Running chunks in RMarkdown messes up screen

### ISSUE THREAD

**Issue by JoFAM** [rstudio/rstudio#5673]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      : Windows 10
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Start a Rmd script using `output: templatesUGent::ugent_notes` from https://github.com/JoFAM/templatesUGent (for exact reproducing the picture)
2. Add a few R chunks and a few blocks to be interpreted by latex, eg:
```{block, type = "exercise"}```
3. Add a latex equation somewhere (not sure it's needed, but it's in the files where I spotted the problem)
3. Render to PDF
4. Run all chunks using the little arrow down in the last chunk
5. scroll up and down in the file

### Describe the problem in detail

There's a ton of errors generated because RStudio tries to run the block chunks as R code, which obviously doesn't work at all. From that moment on, scrolling through the file gives strange displaced squares (see screenshot). This only stops after restarting RStudio, and starts again the moment the chunks are run again.

The behaviour is stopped after turning off all R Markdown options in global options safe for "Show inline toolbar for R code chunks". 

### Describe the behavior you expected

Not seeing this.

![Screenshot - 10_30_2019 , 2_58_56 PM](https://user-images.githubusercontent.com/809906/67934079-67337500-fbc7-11e9-8cd5-9b4b4a8559f3.png)

1. The output of sessionInfo() 

```
> sessionInfo()
R version 3.6.1 RC (2019-07-03 r76779)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.24

loaded via a namespace (and not attached):
 [1] zip_2.0.3          Rcpp_1.0.2         cellranger_1.1.0  
 [4] pillar_1.4.2       compiler_3.6.1     RColorBrewer_1.1-2
 [7] plyr_1.8.4         prettyunits_1.0.2  progress_1.2.2    
[10] forcats_0.4.0      tools_3.6.1        packrat_0.5.0     
[13] tibble_2.1.3       gtable_0.3.0       pkgconfig_2.0.2   
[16] rlang_0.4.0        openxlsx_4.1.0.1   GGally_1.4.0      
[19] rstudioapi_0.10    curl_3.3           haven_2.1.0       
[22] xfun_0.9           rio_0.5.16         stringr_1.4.0     
[25] dplyr_0.8.2        hms_0.4.2          rprojroot_1.3-2   
[28] grid_3.6.1         tidyselect_0.2.5   reshape_0.8.8     
[31] glue_1.3.1         data.table_1.12.2  R6_2.4.0          
[34] readxl_1.3.1       foreign_0.8-71     carData_3.0-2     
[37] reshape2_1.4.3     ggplot2_3.2.0      purrr_0.3.2       
[40] car_3.0-3          magrittr_1.5       backports_1.1.4   
[43] scales_1.0.0       abind_1.4-5        assertthat_0.2.1  
[46] colorspace_1.4-1   labeling_0.3       stringi_1.4.3     
[49] lazyeval_0.2.2     munsell_0.5.0      crayon_1.3.4
```

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3793004/diagnostics-report.txt)

**Comment by kevinushey** [comment]
Does the issue still reproduce if you switch to software rendering? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by kevinushey** [comment]
It may also be helpful to see a GPU diagnostics report, as from Help -> Diagnostics -> Show GPU Diagnostics. In particular, the `GL_*` fields close to the end of the report; e.g. mine reports:

```
GL_VENDOR | ATI Technologies Inc.
GL_RENDERER | AMD Radeon Pro 560X OpenGL Engine
GL_VERSION | 2.1 ATI-3.0.68
```

**Comment by JoFAM** [comment]
@kevinushey The report I sent above is from work. I've seen it on my personal PC as well, but can't reproduce right now. I'll send the extra required information on monday.

**Comment by JoFAM** [comment]
@kevinushey 

Here the report for the GPU diagnostics:

KEY | VALUE
-- | --
GL_VENDOR | ATI Technologies Inc.
GL_RENDERER | ATI Radeon HD 4300/4500 Series
GL_VERSION | 3.3.11672 Compatibility Profile Context

I currently don't see any weird things, so I can't dig deeper into the software rendering. I'll update once it returns.

Cheers
Joris

**Comment by JoFAM** [comment]
Problem appeared random again, after opening another Rmd file. The problem appeared after the screen went into screensaving mode and woke up again. Closing the Rmd file didn't change a thing. Restarting RStudio didn't help either. After changing the rendering engine from auto to software the problem went away. 

I'll keep it at this setting and report if it goes haywire again.

**Comment by kevinushey** [comment]
This is probably more fallout from Qt WebEngine and it's unlikely there's much we can do barring a switch to an alternate technology / hoping for the best in a future Qt update. 😞

**Comment by rmarconzini** [comment]
> Problem appeared random again, after opening another Rmd file. The problem appeared after the screen went into screensaving mode and woke up again. Closing the Rmd file didn't change a thing. Restarting RStudio didn't help either. After changing the rendering engine from auto to software the problem went away.
> 
> I'll keep it at this setting and report if it goes haywire again.

Hi,  confirm that even today the only way to solve the problem is to change the rendering engine
