### ISSUE TITLE
Custom themes not loaded on macOS with v1.3.555+

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#5674]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.555
    OS Version      : macOS Catalina 10.15 x86_64-apple-darwin15.6.0 (64-bit)
                      macOS Mojave 10.14.6 x86_64-apple-darwin15.6.0 (64-bit)
    R Version       : 3.6.1

Note: I also tested on a rocker/verse image where this issue did not reproduce. I was able to rule out this being an issue specific to Catalina by reproducing on Mojave as well.

Thanks to [detailed testing](https://github.com/gadenbuie/rsthemes/issues/3#issuecomment-548264955) by @pat-s, I'm fairly certain the change occurred in 053e6813c8990ea55f75f54dc6a4c87d1293ae90 (v.1.3.555).

### Steps to reproduce the problem

Install a custom theme, e.g. from [rsthemes](https://github.com/gadenbuie/rsthemes) or [Night Owl](https://github.com/batpigandme/night-owlish). The theme displays in the appearance menu but is not loaded correctly.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/5420529/67949940-13bd2900-fbbf-11e9-98ed-069480bddd5e.png">

### Describe the problem in detail

Through Chrome dev tools it seems that the rstheme CSS file isn't being loaded.

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/5420529/67950026-436c3100-fbbf-11e9-9d7d-db5b490bee54.png">

### Describe the behavior you expected

But the theme is correctly applied if the source is pasted into the empty rstheme file in the dev tools.

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/5420529/67950113-76162980-fbbf-11e9-9fdf-27d4e091e1ae.png">

**Comment by gtritchie** [comment]
Thanks for the report, I'll take a look.

**Comment by gtritchie** [comment]
Repro'd with 1.3.566 (macOS). Saw this in console when I selected an rstheme in the options dialog (immediately, before I dismissed the dialog):
```
31 Oct 2019 17:19:09 [rsession-gary] ERROR system error 2 (No such file or directory) [path: /Users/gary/.R/rstudio/themes/, path: rsthemes_fairyfloss.rstheme] at rstudio::core::Error rstudio::core::FilePath::completeChildPath(const std::string &, rstudio::core::FilePath &) const /Users/admin/workspace/IDE/macos-v1.3/src/cpp/shared_core/FilePath.cpp:565
```

**Comment by jmcphers** [comment]
.R/rstudio is the old path; it should be looking in .config/rstudio/themes.

I think this broke with either:

https://github.com/rstudio/rstudio/commit/2b6631a1a2c3f51feb6c6a1c70e7448d148d5dad or orhttps://github.com/rstudio/rstudio/commit/5a417926ed6b8928d3353b80d53eb84e0f860b93

**Comment by gtritchie** [comment]
> .R/rstudio is the old path; it should be looking in .config/rstudio/themes.

Looks like we (intend) to try both?

https://github.com/rstudio/rstudio/blob/6c921abf12fbfed0d736c71bdb7767205c87bc74/src/cpp/session/modules/SessionThemes.cpp#L293-L297

**Comment by jmcphers** [comment]
Yes, that way the themes installed in 1.2 should still load in 1.3.

**Comment by gtritchie** [comment]
@MariaSemple said she'll take this bug. Also, confirmed the scenario works if I moved the installed themes to the new location in `.config/rstudio/themes`.
