### ISSUE TITLE
Warning messages when installing pro drivers using RStudio recommandations

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#5676]
Hi, 

With the announcement of the new drivers, we started to work on the update for our production servers by following the documentation 
https://docs.rstudio.com/pro-drivers/installation/

We used the bundled tar to get a custom installation but used the recommended template for `odbcinst.ini` (which you called `odbcinst.ini.sample`
```
[Oracle]
Driver = /opt/rstudio-drivers/oracle/bin/lib/liboracleodbc_sb64.so
Version = 1.6.0
Installer = RStudio
```

That means we added `Installer=RStudio` in our file for all drivers. 

This had the benefits of hiding the drivers option in the connection menu but add the drawback to create a warning in R console while connexion clicking on new connection and connecting to a DB
```
Warning message:
In value[[3L]](cond) : argument 'description' incorrect
```

This happens only with RStudio and not if we connect using R code directly with DBI. 

This warnings happens when reading odbc drivers `.rs.connectionReadOdbc()`
because it will try to read some entries and while discovering `Installer=RStudio` it will try to read a file that does not exist
https://github.com/rstudio/rstudio/blob/a830604efc72a1a284c96cf6280ec22ff1ea2760/src/cpp/session/modules/SessionConnections.R#L441-L442

https://github.com/rstudio/rstudio/blob/a830604efc72a1a284c96cf6280ec22ff1ea2760/src/cpp/session/modules/SessionConnections.R#L264-L273

I believe all this exists for RStudio Desktop Pro drivers and not RStudio servers. on my session I have 
```
> .rs.connectionOdbcInstallerPath()
[1] "/home/bureau.si.interne/dervieuxchr/.rstudio/odbc/installers"
```

and the odbc installers does not exists in the home of each users. 

This happens only because we add what was in `odbcinst.ini.sample` in your tar bundle
```
[Oracle]
Driver = /opt/rstudio-drivers/oracle/bin/lib/liboracleodbc_sb64.so
Version = 1.6.0
Installer = RStudio
```

The warning disappears if we don't add `Installer=RStudio` to our `odbcinst.ini` entries. 

However, I can say that I liked the fact that if we add this to each entry, the driver is hidden in the New Connection menu

So I report this because if a RSP user add `Installer=RStudio` in its `odbcinst.ini`, the same issue will be encounter. 

## To reproduce

* RSP server 1.2.1335-1
* Configure drivers adding `Installer=RStudio` field in one of the entries
* run `.rs.connectionReadOdbc()` => You should get a warning message and the driver does not appear in the menu after New Connection
* Delete the `Installer=RStudio` field in the `odbcinst.ini`
* run  `.rs.connectionReadOdbc()` => No Warning and the driver appears now in the menu 

Thanks.

**Comment by scubastevew** [comment]
Customer reported this in ZD: https://rstudioide.zendesk.com/agent/tickets/41253

**Comment by gtritchie** [comment]
This should be opened in the rstudio-pro repo, not the open-source repro. Closing it here, please reopen there. Thanks!

**Comment by cderv** [comment]
> 
> 
> This should be opened in the rstudio-pro repo, not the open-source repro. Closing it here, please reopen there. Thanks!

Just to be sure : I can't open this elsewhere than the open source repo, right ? You mention this to @scubastevew ? 

For issues like that, should I send the detailed report I posted here to pro support directly and only or still open in accessible open source repo and you'll move it ?

**Comment by gtritchie** [comment]
Yes, @scubastevew is reopening in Pro. Correct, you don't have access to that, so generally, for Pro customers (and pro-specific issues), better to report via the ticketing system and have Support open an issue for you.

**Comment by cderv** [comment]
> better to report via the ticketing system and have Support open an issue for you.

Now I'll know and do that, it's noted. Thanks !
