### ISSUE TITLE
Pandoc : Issue :error 11

### ISSUE THREAD

**Issue by 001rnsnnsns** [rstudio/rstudio#5681]
hi,
I am having a major issue .please help ..i dont use much R and very weak as such in understanding the above script.

I was facing the issue earlier yesterday .

I ran the script posted on 16th Mar  https://github.com/rstudio/rstudio/issues/4072 and now i am getting below error when i again press Knit on R studio post the installation and restart of R session

Error in system(paste(shQuote(path), "--version"), intern = TRUE) :
'CreateProcess' failed to run 'C:\Users\ram bablani\DOCUME~1\rstudio-pandoc\pandoc.exe --version'
Calls: ... get_pandoc_version -> with_pandoc_safe_environment -> force -> system
Execution halted

I have resinstalled R studio twice and even run as admin but no change

also, i ran the below commands

rmarkdown::pandoc_available()

Error in system(paste(shQuote(path), "--version"), intern = TRUE) :
'CreateProcess' failed to run 'C:\Users\ram bablani\DOCUME~1\rstudio-pandoc\pandoc.exe --version'

pandoc -v
Error: object 'pandoc' not found

Sys.getenv("RSTUDIO_PANDOC")
[1] "C:/Users/ram bablani/Documents/rstudio-pandoc"

Please help me here as I am doing a college assignment

**Comment by pascaloettli** [comment]
Naive question. Did you install [Pandoc for windows](https://pandoc.org/installing.html#windows) before trying to use it?

**Comment by 001rnsnnsns** [comment]
when i ran that script , a version gets installed in my drive in my documents.When I press knit,
below message is seen

Error in system(paste(shQuote(path), "--version"), intern = TRUE) : 
  'CreateProcess' failed to run 'C:\Users\ram bablani\DOCUME~1\rstudio-pandoc\pandoc.exe --version'
Calls: <Anonymous> ... get_pandoc_version -> with_pandoc_safe_environment -> force -> system
Execution halted

There is a also a version in Rstudio/bin .I guess this installed by default with rstudio

But i have removed the version  downloaded and saved in my documents and saved via the script
I get this message 

Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted

**Comment by kevinushey** [comment]
Best guess: the presence of a space in your username is causing problems?

You could try running this code in R:

```
	dir <- utils::shortFileName(path.expand("~/rstudio-pandoc"))
	entry <- paste("RSTUDIO_PANDOC", shQuote(dir), sep = " = ")
	contents <- if (file.exists("~/.Renviron")) readLines("~/.Renviron")
	filtered <- grep("^RSTUDIO_PANDOC", contents, value = TRUE, invert = TRUE)
	amended <- union(filtered, entry)
	writeLines(amended, "~/.Renviron")
```

and then restarting R + RStudio to see if using a short path name makes a difference.

**Comment by ronblum** [comment]
I'm closing the issue since there's been no update for more than a month. You may update the ticket, though, if there is still an issue.

**Comment by dkStevensNZed** [comment]
I'm having the same problem and in fact all of the rmarkdown code I have generates the error so I'm dead in the water. After trying many remedies from this and other forums, I'm convinced this is a windows 10 update issue, since they all worked a couple of weeks ago and I've done nothing to change my setup except reinstalling RStudio, R, and RTools. I too have a blank space in my users/... name. I don't know where to go next.
