### ISSUE TITLE
Building from source on Arch: "Could not find libR shared library"

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#5683]
The AUR package for building RStudio from source is broken since some weeks.
Nobody seems to be able to apply a quick fix currently so I thought that it is time to reach out to you guys.

Essentially, `cmake` complains about not being able to find `libR`:

```
-- Looking for inotify_init1 - found
-- Looking for getpeereid
-- Looking for getpeereid - not found
-- Looking for setresuid
-- Looking for setresuid - found
-- Configured to build DESKTOP
-- Could not find libR shared library.
CMake Error at /usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibR (missing: LIBR_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibR.cmake:207 (find_package_handle_standap
```

The cmake call is as follows:

```sh
cmake -DRSTUDIO_TARGET=Desktop \
 -DCMAKE_BUILD_TYPE=Release \
 -DCMAKE_INSTALL_PREFIX=/usr/lib/rstudio \
 -DRSTUDIO_USE_SYSTEM_BOOST=yes \
 -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake \
 -DBoost_NO_BOOST_CMAKE=ON \
 -DRSTUDIO_BUNDLE_QT=FALSE ..
```

I suspected that the latest revisions in [FindLibR.cmake](https://github.com/rstudio/rstudio/blob/master/cmake/modules/FindLibR.cmake) could have triggered this because it would match the time when there was roughly the last working build. However, rolling back to the revision from May did not help.

[PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rstudio-desktop-git)

**Comment by kevinushey** [comment]
Can you confirm that R was indeed configured and built with a shared library (i.e. with `--enable-R-shlib`)?

**Comment by pat-s** [comment]
> Can you confirm that R was indeed configured and built with a shared library (i.e. with --enable-R-shlib)?

Yes, you can see the R build options [here](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/r#n45).

**Comment by JanMarvin** [comment]
for a working rstudio-desktop PKGBUILD have a look [here](https://github.com/janMarvin/rstudio-archlinuxpkg)

**Comment by pat-s** [comment]
Thanks. Errors with the same error as the AUR pkg for me.
I start to wonder if something with my local setup is wrong. :thinking: 

Are you able to build the official AUR pkg?

**Comment by kevinushey** [comment]
Can you confirm where you've installed R?

You might need to set some CMake definition to help CMake find R if it's not in a standard location.

**Comment by pat-s** [comment]
`R_HOME` is in `/usr/lib64/R`. I am not using any custom R install, just the official `r` build for Arch Linux which is used by many people. Really wondering what is going on.

**Comment by pat-s** [comment]
Oh, I do not yet know what but - something changed my R_HOME in a normal shell session. It was not set to `/usr/lib64/R` and hence RStudio could not find it.
Now it works.

Strange enough, my R toolchain was not affected by this yet. Thanks for all the advices!
