### ISSUE TITLE
Terminal (in daily builds) does not receive Ctrl+X, Ctrl+C, others on macOS

### ISSUE THREAD

**Issue by ateucher** [rstudio/rstudio#5696]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.575
    OS Version      : macOS Mojave (10.14.6)
    R Version       :  3.6.1

### Steps to reproduce the problem
1. In terminal, type `nano` (nano opens)
2. Typing works fine...
2. Press `Ctrl+X` to try to exit. Nothing happens.
3. Try other shortcuts: `Ctrl+G` (help) does not work, `Ctrl+T` (spell check) does work, as does `Ctrl+R` (read file)
4. The only way to exit is to close the terminal

OR:

1. In terminal at a blank promt, press `Ctrl+C`. Nothing happens (normally would get a new prompt)

### Describe the problem in detail

There are several (though not all) keyboard shortcuts that are not working in the terminal (E.g., `Ctrl+X`, `Ctrl+C`, `Ctrl+G`). It seems like the ones that do not work are either bound as shortcuts in RStudio (e.g., `Ctrl+G` is "Select or Find Next") or globally by the OS (`Ctrl+X`, `Ctrl+C`).

### Describe the behavior you expected

Common keyboard shortcuts work in the terminal as expected

**Comment by gtritchie** [comment]
Not directly related, but see also: https://github.com/rstudio/rstudio/issues/1978
