### ISSUE TITLE
Shinytest "Run Tests" w/ failing test brings up "Error while opening file".

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#5703]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.423
    OS Version      : Mac OSX
    R Version       : 3.5.1

### Steps to reproduce the problem

 - Install the latest shinytest from GitHub: `remotes::install_github("rstudio/shinytest")`. This version stores tests in `tests/shinytest/*.R` instead of `tests/*.R`
 - Start with a Shiny app that has no `tests/` dir
 - Record a shinytest via `shinytests::recordTest()`
 - It will bring up the test script at the end. Break one of your test expectations either by changing the app source or by going into the `-expected` directory and change some value so that the expectations are now wrong
 - Now click "Run Tests" in the script that was opened.
 - Observe this error.

<img width="978" alt="Screen Shot 2019-11-04 at 3 05 04 PM" src="https://user-images.githubusercontent.com/1593639/68159637-14044e00-ff4a-11e9-8e1b-cd99cad7df3d.png">

### Describe the problem in detail

I think [this](https://github.com/rstudio/rstudio/blob/7626365859391743fd5f947f45ae654360eff31a/src/cpp/session/modules/build/SessionBuildErrors.cpp#L341) is where the IDE is going wrong. Appending `tests/` to the app path and looking in there. As noted in #293, the IDE is already pointing to the wrong appdir path; now appending another invalid path to that one.

From the IDE diagnostics, we're getting that butchered path which didn't go up far enough (i.e. the appdir is `___/tests/`) and now we're assuming that the terminal dir is inevitably called `tests` which gets appended. Thus we're looking for `app/tests/tests/mytest.R` which, of course, doesn't exist.

<img width="460" alt="Screen Shot 2019-11-04 at 3 31 18 PM" src="https://user-images.githubusercontent.com/1593639/68159850-7cebc600-ff4a-11e9-9ae6-656496840d13.png">

Related to #5677. Associated shinytest issue is [here](https://github.com/rstudio/shinytest/issues/295), though we can't think up a viable workaround that could go into the package itself this time.

### Describe the behavior you expected

shinytest tests with failing expectations would continue to work with the doubly-nested test directories as they used to with the singly-nested test dirs.

**Comment by jmcphers** [comment]
This blocks work the shinytest team wants to demo at the conference, so it'd be great to get it into Orange Blossom (which should be GA by then).

**Comment by dfalty** [comment]
Verified fixed 1.2.5031-1
