### ISSUE TITLE
linting: identify different-case filenames on case-preserving, case-insensitive systems

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#5705]
Would it be possible to offer feedback when using a case-preserving, case-insensitive file system and referencing on-disk files using different-case names? For example, we may have an on-disk file named `images/RStudio.svg` and then use it from an R Markdown document with:

```markdown
![](images/rstudio.svg)
```

This renders fine on a macOS system, for example, but will probably err if that same content is rendered on a Linux system. The image reference is non-portable.

File-system differences will cause problems when migrating code from RStudio desktop to RStudio server, for example, or when deploying code to shinyapps.io or RStudio Connect.

Could we attempt to identify these situations?

Note: We sometimes avoid this problem when deploying content, as the filename for detected dependencies uses the case from the Rmd source - and that case is preserved in the deployment bundle.
![image](https://user-images.githubusercontent.com/362187/68310104-727e1900-007d-11ea-8da6-eb8e65399903.png)

The on-disk case is used when dependencies are manually included in a deployment.

CC @tareefk

**Comment by kevinushey** [comment]
Note: IIUC, it would be a matter of extending the linter defined here to R Markdown images (that is, paths within `[]`):

https://github.com/rstudio/rsconnect/blob/ae203f870f241e7b1e5de35230b635be754785ee/R/linters.R#L39-L138

Right now, we only look at paths in quotes.

**Comment by jmcphers** [comment]
This linting happens in the rsconnect package as @kevinushey noted so should be tracked over there.

**Comment by jmcphers** [comment]
Reopened on rsconnect: https://github.com/rstudio/rsconnect/issues/388
