### ISSUE TITLE
Command for cleaning knitr cache and then knitting

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5706]
We have a command for cleaning the Knitr cache.

![image](https://user-images.githubusercontent.com/470418/68318642-f29e8180-0071-11ea-85e2-9700d66bda9e.png)

Since knitting with a clean cache is a common operation, we should have a command for that too, or perhaps some gesture that indicates that a knit should be run after the clean command. 

>  it feels like the workflow is currently supoptimal because the only reason I clear the cache is to immediately re-knit
> I use the cache to speed up iteration as I'm developing a doc. But before I finish for the day or check in results, I always want to run it from a fresh slate

-- @hadley

**Comment by hadley** [comment]
This would be analogous to `make clean && make`
