### ISSUE TITLE
Peculiarly differential handling of decimal places

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#5710]
I read in a csv file with a depth column with 1dp precision (76.2) and a temperature column with 2dp (76.25). I performed the same calculations on both (change in value / change in time = value 'velocity'), and the result from depth has 0dp precision (76) while the result for temperature has 5dp (76.12345).
Indexing specific cells in each, zero in the first column and the second both return 0, both classes are numeric, but the first looks like "0" in the datasheet view whereas the other is "0.00000".
The second format is intuitively the bug but the discrepancy between how both are handled is also peculiar.
I did some searching and failed to find any command which would return the formatting currently applied to the cells (rather than applying formatting to them). Session info follows, then cobbled-together screenshot.
Cheers.

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1 

RStudio preview version 1.2.5013
```
![RStudioPrecisionBug](https://user-images.githubusercontent.com/4599748/68346128-2eecd480-00a8-11ea-8d0f-d2d7dcc310b1.png)

**Comment by dfalty** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. It looks like this is displayed the same way in R outside of RStudio.
Example:
```

Please visit our community site to ask questions:

https://community.rstudio.com/

I hope you're able to find what you're looking for!

**Comment by dfalty** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. Looks like the data frame is displayed the same in R outside of RStudio.

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!

**Comment by SimonDedman** [comment]
Hi Darby, sorry to bother you with this, just not 100% I'm understanding you / we're understanding each other. My contention is that this is a bug in RStudio, though - as always - I'm fully prepared to find out I'm wrong!

So from my tests as pictured above (RStudio datasheet view and console, I've never used R directly), two columns of data display what seem to be the same data (0, as queried by a cell index call df_i$TempVelo[13] and VertVelo[13]) display with 2 different levels of precision, despite options(scipen = 5) presumedly acting upon the way both are displayed in RStudio's datasheet view.

So yeah, I feel like this is a bug in RStudio, however if there's a property that cells/vectors/dataframes can have that would allow this difference that I'm just unaware of, maybe it's that. But as I say, I've tried class() on both, direct indexing both, and they're both numeric, zeroes.

Cheers

Simon

**Comment by kevinushey** [comment]
```
> format(c(0, 1.4999995))
[1] "0.000000" "1.499999"
```

It's ultimately a consequence of how R formats numeric output. We could try to do something smarter, but this does reflect what R does itself as well.

**Comment by SimonDedman** [comment]
Ok, so learning about `format` led me to `print.default` and `options(digits)`; it seems that `options(digits)` defaults to 7 which is called by `print.default` and then modified by `format(digits)` which says

> if all the elements then have trailing zeroes, the number of decimal places is reduced until `nsmall` is reached or at least one element has a non-zero final digit

So above, I guess VertVelo's highest precision is 1 / single unit / integer, whereas TempVelo's - for the whole vector - is 5dp, so even though zeroes might be the same in both, all TempVelo's values are given the same formatting.

Ok, fair play to close this, and make sense how y'all have approached it. This seems to be a common enough thing with R / Rstudio  and the package stack - what may seem initially unintuitive can be completely logical once you see how the whole stack is connected and thus what  requirements need to be satisfied for each step.

And then for future reference for myself/others stumbling onto this, the conclusion is, nothing's broken. If you want to see lower precision (without changing the underlying data), use `format(x, digits = y)`.

Cheers chaps, have a good one.

**Comment by kevinushey** [comment]
Indeed, that is typically the case with R :-) Many behaviors which might appear strange or surprising at first glance have some underlying rationale. We may not always agree with the rationale, but it's helpful to know that it exists.
