### ISSUE TITLE
Rstudio server renders font different in Safari and Chrome

### ISSUE THREAD

**Issue by minor6th** [rstudio/rstudio#5711]
I‘m using macOS Catalina with a 4K monitor,
the font of code editor has obvious thinner strokes in Safari then in Chrome.

![image](https://user-images.githubusercontent.com/2927861/68370482-8d34b880-0177-11ea-8fa7-0b6baddef682.png)
![image](https://user-images.githubusercontent.com/2927861/68370534-ad647780-0177-11ea-8818-705627cb2773.png)

**Comment by kevinushey** [comment]
Sorry, but this doesn't seem to be something that would be easily actionable by us. You can instead try configuring your macOS font smoothing options globally through some other means.

**Comment by ronammar** [comment]
I have also experienced this on RStudio desktop when switching from 1.1.463 to any newer version.

**Comment by ronammar** [comment]
FYI I've resolved the issue by switch fonts from Droid Sans Mono to Robot Mono Bold, which looks very similar:

1.2.5033:
![image](https://user-images.githubusercontent.com/5419280/72452587-d0209700-378b-11ea-855c-247ef3a638ed.png)

**Comment by minor6th** [comment]
@ronammar 
If you are using macOS, the desktop version font problem may be caused by the system upgrade.
You could execute the following command in the console:

> defaults write -g CGFontRenderingFontSmoothingDisabled -bool FALSE

ref: https://ahmadawais.com/fix-macos-mojave-font-rendering-issue/

**Comment by ronammar** [comment]
@minor6th thanks for the input. Wouldn't this smoothing issue affect both old and new versions of RStudio in the same way?

**Comment by minor6th** [comment]
@ronammar I think it would, although I haven't tested different versions.
The 'defaults' command solves the problem on the latest version for me.

**Comment by gtritchie** [comment]
> I have also experienced this on RStudio desktop when switching from 1.1.463 to any newer version.

One factor is that Mac RStudio desktop 1.1 used WebKit (like Safari) for rendering, whereas on 1.2 we switched to Chromium.

**Comment by ronammar** [comment]
Issue persists in Big Sur with RStudio Desktop. Turning on system wide font smoothing (via terminal) doesn't seem to resolve this issue. For now, switching to a heavier weighting helps. Currently using Roboto Mono Medium (https://fonts.google.com/specimen/Roboto+Mono?category=Monospace)
