### ISSUE TITLE
Cannot Copy Image from R Notebook

### ISSUE THREAD

**Issue by minor6th** [rstudio/rstudio#5712]
In RStudio Desktop, if I right click on the graph produced by ggplot and select "copy image",
I cannot paste the image in another app.

The same issue occurs when I use RStudio Server in Chrome, 
but I Can copy and paste image in Safari on the same RStudio Server.

**Comment by jmcphers** [comment]
What version of MacOS and RStudio are you using? (Please fully fill out the issue template.)

Note: I didn't get the Copy Image menu item at all. This happens because the element for the manipulator covers the plot (so you can, of course, manipulate it). Since the element under the cursor is not an `<img>`, Chrome does not show the Copy Image context entry.

![image](https://user-images.githubusercontent.com/470418/68424694-61a2d580-0159-11ea-969a-5b07015cef96.png)

**Comment by minor6th** [comment]
My environment:

macOS Catalina: 10.15.1 (19B88)
Safari: Version 13.0.3 (15608.3.10.1.4)
Chrome: Version 78.0.3904.97 (Official Build) (64-bit)
RStudio Server: 1.2.5019

<img width="970" alt="image" src="https://user-images.githubusercontent.com/2927861/68447565-5dd78780-021b-11ea-91ad-3dba9455906d.png">
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/2927861/68447695-d8080c00-021b-11ea-9a75-165ad6b5a652.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/2927861/68447786-22898880-021c-11ea-8857-a380f5afa64e.png">
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/2927861/68447866-7eeca800-021c-11ea-9306-60ce144f5205.png">

PS: I also notice that the copied image on clipboard has slightly different properties

Copied From Safari:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/2927861/68448017-14883780-021d-11ea-87c1-0a9f2fe24b71.png">

Copied From Chrome:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/2927861/68447903-9cba0d00-021c-11ea-8271-60e8023c18e9.png">

**Comment by ronblum** [comment]
Using RStudio Desktop 1.2.5033 on MacOS 10.15.2 Catalina and RStudio Server 1.2.5033 on Red Hat 7.8 using Chrome 79.0:
- I get the right-click "Copy Image" option
- It shows up in the clipboard
- I can paste into Pages and Numbers
- I cannot paste into Word and Excel; in them, I get:
![image](https://user-images.githubusercontent.com/31009952/71278379-6dbbae80-2325-11ea-8ef8-b1fd616cb8b8.png)

QA note: using code at (The Complete ggplot2 Tutorial )[http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html#How%20to%20Change%20the%20Color%20To%20Reflect%20Categories%20in%20Another%20Column]

**Comment by kevinushey** [comment]
@ronblum are you able to copy + paste images from other applications (say, from Chrome) into Word / Excel?

**Comment by jmcphers** [comment]
No response or other reports in a long time, closing.

**Comment by Inserm-CRI-LBI** [comment]
too bad, same thing is happening to me right now...
