### ISSUE TITLE
Cannot add secondary file repository

### ISSUE THREAD

**Issue by matthijsvanderloos** [rstudio/rstudio#5724]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      :  Windows 10 Enterprise x64
    R Version       :  3.6.1

### Steps to reproduce the problem
Adding a secondary package repository that is hosted on a local Windows fileshare fails.

### Describe the problem in detail
In the Packages pane under the RStudio options I am trying to add a secondary package repository that is hosted on a local Windows fileshare. The url has the form `file://server/local-cran`. This fails, however, with the error "The given URL does not appear to be a valid CRAN repository". The file `src\contrib\PACKAGES.gz` does however exist on the share.

### Describe the behavior you expected
The secondary repository to be added successfully.

**Comment by kevinushey** [comment]
Does:

```
available.packages(repos = "file://server/local-cran", type = "source")
```

work as expected? This is effectively what RStudio will try to run behind the scenes.

**Comment by matthijsvanderloos** [comment]
Yes, that command completes succesfully.

**Comment by kevinushey** [comment]
I think this is a problem with our routine:

https://github.com/rstudio/rstudio/blob/3f16dbd2a633a74d08447b495e0c621b79a6bc02/src/cpp/session/modules/SessionPackages.R#L1704-L1718

We only check for a `PACKAGES.gz` file, but CRAN repositories can contain any of:

- `PACKAGES.rds`
- `PACKAGES.gz`
- `PACKAGES`

and we should check for each of these.

**Comment by kevinushey** [comment]
@matthijsvanderloos, as a workaround, you can ensure that your local repository has a `PACKAGES.gz` file -- I'm guessing it has one of the other `PACKAGES` database files, but not that one.

**Comment by matthijsvanderloos** [comment]
Our local repository actually contains all three of those files already?

**Comment by kevinushey** [comment]
Well, that's surprising! (and it looks like you made that clear in your initial post; sorry for missing that.) Can you try running:

```
trace(download.file, quote(print(url)))
```

and then attempting to add your secondary repository once more? If we're lucky, the URL being used will be printed to the console and we can see if RStudio is indeed constructing the right URL.

**Comment by matthijsvanderloos** [comment]
Sure, this produces:

```R
Tracing download.file(.rs.completeUrl(.rs.appendSlashIfNeeded(url), "src/contrib/PACKAGES.gz"),  .... on entry 
[1] "file:/server/local-cran/src/contrib/PACKAGES.gz"
```
Seems like there are a couple of slashes missing in the url because the following does work:

```R
download.file("file:////server/local-cran/src/contrib/PACKAGES.gz"
```

**Comment by kevinushey** [comment]
It looks like the issue is with `.rs.completeUrl()`:

```
.rs.completeUrl("file://base", "path")
```

which returns:

```
> .rs.completeUrl("file://base", "path")
[1] "file:/path"
```

**Comment by matthijsvanderloos** [comment]
Yes, this seems to be it:

```R
> .rs.completeUrl("file://local-server/", "local-cran/src/contrib/PACKAGES.gz")
[1] "file:/local-server/local-cran/src/contrib/PACKAGES.gz"
```
