### ISSUE TITLE
Screen tearing while scrolling in source pane

### ISSUE THREAD

**Issue by ashley-williams** [rstudio/rstudio#5727]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.2.5019
    OS Version      : Windows 10
    R Version       : 3.5.3

I'm not sure how to reproduce, maybe hardware related.

I am running Rstudio on a Lenovo X1 Extreme Gen 1, and am experiencing screen tearing in the upper left source pane while scrolling and typing. I have attached a screenshot.
![wierdR](https://user-images.githubusercontent.com/47582093/68529834-bb79db80-02d0-11ea-9843-e767db6e1fad.PNG)

I am experiencing this issue with all file types. I have only seen this in RStudio and not other programs.

**Comment by jmcphers** [comment]
Does switching to software rendering fix the problem?

https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by ashley-williams** [comment]
That worked! Thanks

**Comment by jmcphers** [comment]
Great, glad to hear it!
