### ISSUE TITLE
Problems trying to animate graphics

### ISSUE THREAD

**Issue by inub** [rstudio/rstudio#5729]
Hi!

I have been learning R for two days now and I have some serious doubts. I was following the following web examples to animate a graphic:
https://www.r-graph-gallery.com/271-ggplot2-animated-gif-chart-with-gganimate.html
and
https://www.datanovia.com/en/blog/gganimate-how-to-create-plots-with-beautiful-animation-in-r/

However, eventhough I follow the code, i get the follwing error:
`Error: The png package is required to use gifski_renderer`

I try to insatall gifski_render but i get this:
```
Warning in install.packages :
  package ‘gifski_render’ is not available (for R version 3.6.1) 
```
I have used ggplot2 and gganimate, should i install a previous version of R?

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
