### ISSUE TITLE
RStudio viewer not working with blogdown

### ISSUE THREAD

**Issue by nickarnosti** [rstudio/rstudio#5730]
I am trying to use blogdown in RStudio to create a new blog. 

I created a new project and ran blogdown::new_site(theme="yihui/hugo-xmin"). Everything seemed to work as expected. 

However, if I change projects and then change back to the original project, Viewer is blank. It remains blank if I type blogdown::build_site(), with no opportunity to hit refresh. 

The blank viewer happens even if I create a new project, make no modifications, and switch away and back to the original project directory. Thus, the problem is not with the code for the site. Am I somehow switching directories incorrectly?

For what it's worth, I am familiar with R but new to RStudio so I am not familiar with "viewer" outside the context of RStudio. However, if I generate a plot in RStudio, it does show up in viewer.

**Comment by dfalty** [comment]
If you change projects or restart the R session you will have to serve the site again for you to make edits and see them.
`blogdown::serve_site()`
Does that do what you want? This is outside of the IDE itself so you may want to ask the community if you additional questions. https://community.rstudio.com/

**Comment by nickarnosti** [comment]
That works -- thank you!
