### ISSUE TITLE
Plot preview when saving as PNG fails for larger widths

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#5731]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : Version 1.2.5019
    OS Version      : Mac OS 10.14.6 
    R Version       : 3.6.1

### Steps to reproduce the problem

Make a plot, click on Export > Save as Image... > Check box for Maintain aspect ratio, change the width to 760.

Sample code to produce a plot:

```
plot(iris$Sepal.Length, iris$Sepal.Width)
```

### Describe the problem in detail

Plot preview disappears.

<img width="616" alt="Screenshot 2019-11-11 at 20 46 02" src="https://user-images.githubusercontent.com/5965649/68619932-4ec73280-04c4-11ea-9430-6712c6a9c8cc.png">

### Describe the behavior you expected

Expected the plot preview to not disappear and show a preview like it does when the width is set to 750.

### Note

I can't figure out if it consistently fails for widths above a certain value or when the proportional increase in width is high. I suspect the latter because if I increase the width by one at a time (start at 750 and go up by one) the preview works. Similarly, if I go up to 800 first the preview disappears but works again if I go down to 760.

**Comment by kevinushey** [comment]
I can reproduce this if I drag the preview to close to the RStudio window boundary -- e.g. to the bottom-right corner.

This is the problematic code:

https://github.com/rstudio/rstudio/blob/4f0955405e5f33f4d933818eda065d38b8c45e3a/src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotSizeEditor.java#L464

If the preview panel is dragged beyond these limits, then the panel is hidden. I suspect this is done to avoid allowing the user to display an overly-large image (e.g. if someone wanted to set `width=10000`) but we likely want to avoid triggering this code when the user is using the resizer.

**Comment by kevinushey** [comment]
Marking as v1.3 because the problem (and hopefully solution) is well-understood.

**Comment by mine-cetinkaya-rundel** [comment]
FWIW I can't reproduce this original error on 1.4.1577, so maybe it's been fixed already.
