### ISSUE TITLE
incorrect C diagnostics

### ISSUE THREAD

**Issue by tjtnew** [rstudio/rstudio#5733]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      :  Debian GNU/Linux 10 (buster)
    R Version       : 3.6.1 Patched (2019-11-10 r77400)

### Steps to reproduce the problem
create a C file test.c containing the following:
```
#include <stdlib.h>

int main(void) {
    int *p = malloc(sizeof(*p));
    free(p);
    return 0;
}
```
### Describe the problem in detail
diagnostics at side comes up with a cross and says `cannot initialise a variable of type 'int *' with an rvalue of type 'void *'`
### Describe the behaviour you expected
I would not expect any error to show for C code (disclaimer: pretty new to C coding so could be wrong).

**Comment by jmcphers** [comment]
This is a real problem; malloc returns a void pointer. You need to cast it explicitly. Try this:

     int *p = static_cast<int*>(malloc(sizeof(*p)));
