### ISSUE TITLE
VoiceOver reads "misspelled" on words that don't show a squiggly, even when real-time is off

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5734]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.600
    OS Version      : Safari, macOS 10.15.1
    R Version       : any

### Steps to reproduce the problem
Must use Safari on macOS to repro this. Safari is the browser we'll be recommending for using RStudio server on Mac with VoiceOver due to a Chromium bug that causes the editor (Ace) to read the wrong line. https://bugs.chromium.org/p/chromium/issues/detail?id=912689

Ensure real-time spell-checking is turned on. Ensure screen-reader support is turned on.

Put this in an R file in the RStudio editor and save it
```R
# zoopy dog cat mouse
# once up a time

zoopy <- function() {
  cat("mouse")
  floopy("day")
}
```
At that point you'll see (if you have really good/young eyesight) the squiggly line under "zoopy" in the comment, but not under the zoopy or floopy in the code.

Use the arrow key to navigate into comment "zoopy" and pause. You'll get the "Spellcheck" tooltip (not desired, tracked by #5348.

Now turn on VoiceOver, and move the cursor into the "comment" zoopy, then into the code "floopy" and "zoopy"

### Describe the problem in detail
Misspelled is read when cursor is in the code.

Video example with sound:
https://drive.google.com/file/d/1gqyjTk0jDD5vJzd3R53oRecLezrDb3v0/view?usp=sharing

Even if you turn off real-time spellchecking, "misspelled" continues to be announced both in places where it was before, both comments and code.

### Describe the behavior you expected
We don't do spell checking on code (hence, no squiggly or tooltip), so there shouldn't be a "misspelled" announcement. This makes navigating real source code virtually impossible with a screen reader on the Mac using Safari. Again, we don't currently support Chrome on the Mac with VoiceOver, so making Safari usable is important.

Can't mitigate by turning off real-time spellchecking, since the announcements continue to happen.

**Comment by gtritchie** [comment]
This is a behavior specific to VoiceOver and Safari on macOS and can be repro'd on a trivial HTML example. Also repros with the Ace Kitchen Sink.

The work-around is to go to the VoiceOver utility (VO+F8 while using VoiceOver), go to Verbosity, Text tab, and change "When encountering a misspelled word" to "Do Nothing".

<img width="756" alt="Screenshot of VoiceOver utility showing location of the setting to modify behavior  when encountering a misspelled word, with it changed to Do Nothing." src="https://user-images.githubusercontent.com/10569626/71923602-3846fb80-3142-11ea-8088-18b68e71603d.png">

**Comment by rich-rstudio** [comment]
verified on 1.3.888
