### ISSUE TITLE
RStudio Server: Support K&R indentation

### ISSUE THREAD

**Issue by BenCarlsen** [rstudio/rstudio#5735]
This is a feature request.

**Use Case**

My employer's R styleguide requires indentation where closing braces and parens to align with the indentation level of the opening line. 

```
function_1 <- function(...){
  list(...)
}
```

RStudio Server indents this way:
```
function_1 <- function(...){
  list(...)
  }
```
I would love to see a user option to close braces at the indentation level of the _line_ on which the braces are opened.

**Comment by pascaloettli** [comment]
First, please keep and use the dedicated template. 
Second, I cannot reproduce on Rstudio Server Version `1.2.5001`. And <kbd>Ctrl</kbd>+<kbd>I</kbd> reindent lines correctly.

**Comment by ronblum** [comment]
I checked with RStudio 1.2.5033-1 on MacOS 10.15.2 Catalina, and it works correctly. I'm closing the issue since it's been inactive for more than a month. If this is still a problem, please let us know!
