### ISSUE TITLE
Autocomplete should stand down when R is prompting user for input

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#5738]
When I am answering this question in the Console in the IDE, it really wants to autocomplete to something like `yesno::yesno`. Which obviously does not end well.

``` r
  There are binary versions available but the source versions are later:
              binary source needs_compilation
roxygen2 6.1.99.9001  7.0.0              TRUE
R6             2.4.0  2.4.1             FALSE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
```

It feels like the IDE should not be attempting auto-complete in this context, where I believe this means whenever the user is responding to `readline()`.

**Comment by rossellhayes** [comment]
In the meantime, I've been using this redefinition for `readline()` in my own code:

```
input <- function(prompt = "") {
  if (Sys.getenv("RSTUDIO") == "1") {
    old_pref <- rstudioapi::readRStudioPreference("console_code_completion")

    on.exit(rstudioapi::writeRStudioPreference("console_code_completion", old_pref))

    rstudioapi::writeRStudioPreference("console_code_completion", FALSE)
  }

  readline(prompt = prompt)
}
```

**Comment by jennybc** [comment]
I still think this is worth fixing.

**Comment by homerhanumat** [comment]
The issue arises selectively in later versions of RStudio.  I'm seeing it in Version 2024.04.2+764 (2024.04.2+764) on MacOS on my desktop, and on 2024.04.2 Build 764.pro1 on Linux ("Chocolate Cosmos" Release (65361150, 2024-06-05) for Ubuntu Focal).  In the attached screenshot, the first call is fine, but in the second call, where there are parentheses around `or type q to quit"`, the code completion appears when the third character of "532" is typed.
<img width="588" alt="readline_issue" src="https://github.com/user-attachments/assets/38743fbf-d981-4352-80be-a3b2d8656e45">
