### ISSUE TITLE
jobs: clicking progress bar UI has no action

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5739]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.3.581
    OS Version      : macOS Catalina 10.15.1
    R Version       : R version 3.6.1 Patched (2019-09-23 r77210)

### Steps to reproduce the problem

Run an RStudio job, then in the Jobs tab, click the back button to get the list of jobs. Then, try to click on the progress bar area for the job description (to get back to the job output).

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

Clicking on the progress bar section of the description should still open the job output.

![Screen Recording 2019-11-13 at 3 15 51 PM](https://user-images.githubusercontent.com/1976582/68813045-771c7180-0629-11ea-9509-24cdfd82ea5d.gif)

**Comment by kevinushey** [comment]
Perhaps also worth saying: when there has been no progress output, no bar is drawn and so there's just an empty space (making this behavior perhaps more surprising?)

It might be worth giving the progress bar some sort of background to differentiate it from the other UI components.

**Comment by melissa-barca** [comment]
@jmcphers I thought this would be an easy fix, but noticed you have a comment and code in JobItem.java explicitly stating we are ignoring clicks occurring in the progress area.  Did you intentionally not allow users to select the progress bar? If so, is there an argument against it?
