### ISSUE TITLE
Make code-chunk headers breakable

### ISSUE THREAD

**Issue by topialla** [rstudio/rstudio#5741]
When using .Rmd I often run into the issue that the code-chunk header, i.e. the line with all the options, becomes long, especially, when using `fig.cap=` This text runs then into the control icons on the right of the editor, which makes it hard to read and/or edit. Also when using multiple options these become hard to manage and it would be easier maintainable, if I could have line breaks at specific points. 
Just everything between the curly braces starting at the beginning of a code chunk should be considered as chunk options. Tracking of braces for functions or loops works already, so I guess this might be relatively simple to do.
Thanks for all your great work!

**Comment by dfalty** [comment]
Hi @topialla, this is actually a knitr requirement. https://yihui.org/knitr/options/ `Chunk options must be written in one line; no line breaks are allowed inside chunk options`. If a change were to be made, it would have to be on the knitr side.

Here's a possible solution for you to clean things up though. https://stackoverflow.com/questions/33628318/split-r-chunk-header-across-lines-in-knitr

**Comment by topialla** [comment]
Thanks! The solution already helps a lot! Didn't know about `eval.after` :-)
