### ISSUE TITLE
Section labels, outline, and navigation menu could adhere to markdown heading levels

### ISSUE THREAD

**Issue by WilDoane** [rstudio/rstudio#5744]
Given section labels with multiple leading hash marks, these could be used to inform indentation in the outline panel and the navigation popup menu. For example, 

```
# abc ---------------------------------------------------------------------

## def --------------------------------------------------------------------

# ghi ---------------------------------------------------------------------
```

could produce an indented outline:
```
abc
  def
ghi
```
but currently does not.

**Comment by dfalty** [comment]
Similar to https://github.com/rstudio/rstudio/issues/4124 @kevinushey response here https://github.com/rstudio/rstudio/issues/4124#issuecomment-452467340 would do exactly your request it seems. Feel free to comment/upvote!
