### ISSUE TITLE
Latest release seems unable to find some system libraries.

### ISSUE THREAD

**Issue by SHuang-Broad** [rstudio/rstudio#5745]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2.5019
    OS Version      : OSX 10.14.6
    R Version       : 3.6.0

### Steps to reproduce the problem

In stall RStudio.

### Describe the problem in detail

```R
> library(ggplot2)
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/shuang/RLib/colorspace/libs/colorspace.so':
  dlopen(/Users/shuang/RLib/colorspace/libs/colorspace.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib
  Referenced from: /Users/shuang/RLib/colorspace/libs/colorspace.so
  Reason: image not found
```

### Describe the behavior you expected

It should just load the library.
I've tested that the same command run without issue in plain R console.
Reinstalling RStudio doesn't solve the problem.

```R
> sessionInfo() 
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    gtable_0.3.0   Rcpp_1.0.3    
[5] grid_3.6.0     rlang_0.4.1
```

**Comment by kevinushey** [comment]
You are running R 3.6.0, but attempting to load a package compiled for R 3.5.0. You'll have to reinstall your R packages.

Note that it is not a good idea to try to use the same library directory across multiple versions of R.

**Comment by SHuang-Broad** [comment]
So you are suggesting reinstalling all R packages every time R is updated on a machine?
How do you explain that the same command works under R console?

**Comment by kevinushey** [comment]
> So you are suggesting reinstalling all R packages every time R is updated on a machine?

Yes, I am.

> How do you explain that the same command works under R console?

Ultimately? You got lucky. In general, R does not maintain binary compatibility across minor releases -- e.g. you normally cannot expect packages built for R 3.x to work with R 3.y.

Note also that this change was forced upon us by Apple due to notarization requirements for applications on Catalina. See:

https://github.com/rstudio/rstudio/issues/5238
https://github.com/rstudio/rstudio/issues/5286

for more details.

**Comment by SHuang-Broad** [comment]
Thanks for the explanations!

I've been installing R libraries to a custom dir to avoid having to re-install everything.
It has worked at least 3 years.
This is the first time I experience this.

**Comment by kevinushey** [comment]
I promise you that we are just as frustrated as you are about this change. :-)

We try quite hard to ensure that RStudio "just works" in a multitude of environments, but sometimes changes forced upon us by the operating system make this very challenging.
