### ISSUE TITLE
Ace scroll tracks mouse after clicking and dragging off screen

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5758]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.581
    OS Version      : macOS 10.15.1
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Open a long document (such that the vertical scrollbar appears),
2. Click on the scrollbar and keep the mouse button pressed down,
3. Move the mouse cursor outside of the RStudio window,
4. Release the mouse button,
5. Move the mouse button back over the scroller.

### Describe the problem in detail

The scroller continues to track the mouse position, as though the mouse button were still down.

### Describe the behavior you expected

The scroller should not track the mouse position in this case.

### Notes

This may be the culprit in some of the "jumpy scroll bar" bug reports we have seen before.

It appears that this only affects the Ace scrollbar, and does not affect other scrollers.

**Comment by brettmelbourne** [comment]
This appears to be the same or similar to 
* #4691
