### ISSUE TITLE
breakpoints cannot be set within quoted functions

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5760]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.2.5001
    OS Version      : macOS  10.15.1
    R Version       : R version 3.5.3 (2019-03-11)

### Steps to reproduce the problem

Create an R source document with a function as so:

```
"myfun" <- function() {
    1 + 1
    2 + 2
}
```

Save the file. Then, try to click in the left gutter to add a breakpoint on one of the lines. Finally, source the file to activate the breakpoints.

### Describe the problem in detail

A warning is emitted, and the breakpoint is not activated:

```
> debugSource('~/scratch/abc.R')
Warning in body(fun) : argument is not a function
```

### Describe the behavior you expected

The breakpoint should be activated without issue.

**Comment by dfalty** [comment]
@kevinushey I'm still getting this on 1.3.867 Mac.
```
> debugSource('~/newproj/files.R')
Warning message:
In body(fun) : argument is not a function
```

**Comment by jmcphers** [comment]
This is not a regression or a common scenario, so does not meet the bar for 1.3 any more.
