### ISSUE TITLE
data viewer header extends beyond column bounds

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5763]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.3.581
    OS Version      : macOS  10.15.1
    R Version       : R version 3.5.3 (2019-03-11)

### Steps to reproduce the problem

```
View(data.frame(t(1:101)))
```

### Describe the problem in detail

![Screen Shot 2019-11-19 at 3 18 23 PM](https://user-images.githubusercontent.com/1976582/69195242-f73a4f80-0adf-11ea-8390-2e879798ccbc.png)

### Describe the behavior you expected

The column limits [1-50] should be respected by both the table header and body.

**Comment by kevinushey** [comment]
Seems to have regressed between RStudio v1.3.385 and RStudio v1.3.387.

RStudio v1.3.385: https://github.com/rstudio/rstudio/commits/82b0e8f0
RStudio v1.3.387: https://github.com/rstudio/rstudio/commits/3060213b

**Comment by kevinushey** [comment]
Perhaps related to https://github.com/rstudio/rstudio/commit/5d5560b50e88f6787bc2a5518a70395463f59fa8?

**Comment by dfalty** [comment]
Verified fixed 1.3.867
