### ISSUE TITLE
Use natural ordering instead of lexicographic sort in the Files pane

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#5766]
I regularly use RStudio projects that contain a sequence of numbered documents (slides for a series of lectures, chapters in a book, etc.). Mac Finder uses natural sorting while the RStudio Files Pane sorts these files lexicographically. I realize one solution is to prepend the numbers with 0s, but sometimes you don't know before you get started whether you'll have more than 9 of such files in a directory. It would be great if the RStudio sorting matched that of Mac's.

<img width="718" alt="Screen Shot 2019-11-20 at 9 15 10 AM" src="https://user-images.githubusercontent.com/5965649/69225498-6e222780-0b76-11ea-9bf8-81a6aab5a882.png">

**Comment by jmcphers** [comment]
Cf. https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/ and  https://en.wikipedia.org/wiki/Natural_sort_order

**Comment by kevinushey** [comment]
See also:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
https://caniuse.com/#feat=localecompare

**Comment by BastiHz** [comment]
If you change this please consider making it a configurable setting. I prefer lexicographical sorting, I use it in my operating system's file manager and would prefer to see the same ordering in RStudio.

**Comment by jmcphers** [comment]
@BastiHz (et al.), the natural ordering is going to be the default, but we did make it configurable. Run this to turn it off:

    rstudioapi::writePreference("sort_file_names_naturally", FALSE)
