### ISSUE TITLE
Rstudio adds closing brackets after `%` sign, not consistent with behavior after `"`, `'`

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#5767]
The current behavior is not to add closing brackets after `{`, `(`, `[` in strings, i.e. after `"` or `'`, which makes sense because strings don't contain code (or shouldn't :) ).

The names of infix operators don't contain code either but closing brackets are added nonetheless, for instance typing `%[` autocompletes with `%[]`.

I believe it's inconsistent, and is a minor annoyance when typing operator names such as `%[in(]%` defined in the package *inops*.

Note : the behavior is also seen after `#` but as comments often contain code I think it should stay this way.

**Comment by kevinushey** [comment]
Perhaps we should auto-pair the closing `%` as well? This would also have the side effect of fixing this issue (since `{` in with `%%` is not auto-paired)

**Comment by moodymudskipper** [comment]
Right, the autopairing doesn't happen if we are between `"` too, but still happens after only one, I had missed that.

Then yes this makes a lot of sense to just autopair `%`
