### ISSUE TITLE
Secondary package repository from default .Rprofile ignored

### ISSUE THREAD

**Issue by abhimishr** [rstudio/rstudio#5768]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      : Win 7 professional SP1
    R Version       : 3.6.1

### Steps to reproduce the problem
RStudio ignores a secondary package repository hosted on our public website.

### Describe the problem in detail

There seems to be a bug in Rstudio starting from version 1.2. A secondary repository specified in the default .Rprofile is being ignored.  The way we added this secondary repo is by adding the following snippet in .Rprofile:

`options(repos = c(CRAN = "@CRAN@", our_repo = "https://link_to_our_repo/r/packages"))`

Using `getOption("repos”)` from within RStudio does not display "our_repo" and instead shows just the CRAN repo

```
getOption("repos")
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE
```

As a result, if we check for package updates in RStudio by `tools `- `Check for package updates`, we do not get updates for the R libraries hosted in `our_repo`.

For the moment, it looks like accessing R from the console doesn't cause this issue. 

Output from accessing R via console:

```
getOption("repos")

                                    CRAN 
                                "@CRAN@" 
                                     our_repo 
 "https://link_to_our_repo/r/packages"
```

The difference here is that the CRAN repo appears as `@CRAN@` but I reckon this is parsed as `https://cran.rstudio.com/`

Also, we were unable to reproduce this issue with an older RStudio version.

(This issue could also be related to issue #5724)

### Describe the behavior you expected

Updated packages from the secondary repository to be updated from within RStudio.

**Comment by kevinushey** [comment]
This is because of the code here:

https://github.com/rstudio/rstudio/blob/4f0955405e5f33f4d933818eda065d38b8c45e3a/src/cpp/r/R/Tools.R#L546-L555

RStudio decides that if any repository has value `@CRAN@`, then it should override the repositories with its own, built-in repositories.

A simple workaround would be to explicitly set the primary repository. Is that suitable for your case?

**Comment by abhimishr** [comment]
This fixes our issue indeed. Now I can see that the updated packages from our own repo show up correctly for an update. Thank you!
