### ISSUE TITLE
Ignore View() when Knitting

### ISSUE THREAD

**Issue by wiedenhoeft** [rstudio/rstudio#5771]
I use View() a lot when developing code on our server. However, every time I hit the "Knit" button, I have to comment out every occurrence of of View(), since otherwise I get an error (Error in .Extrenal2(C_dataviewer, x, title) : unable to start data viewer). It would be great to have an option to have RStudio/knitr ignore the View() command.

**Comment by WilDoane** [comment]
In the meantime, consider ```if (interactive()) View(mtcars)``` --- which would restrict the invocation of View() for when you're sourcing lines of code in an interactive session.

**Comment by wiedenhoeft** [comment]
Thanks, that's great! Using `Show <- function(x){if(interactive()){View(x)}}` emulates the behaviour I want for now.
