### ISSUE TITLE
More comprehensive names than app/ui/server in tabs for shiny applications

### ISSUE THREAD

**Issue by damienjacques** [rstudio/rstudio#5772]
Due to the standard names of shiny applications (`app.R`, `ui.R`, `server.R`), I often find myself in a situation where it is difficult to quickly identify which file corresponds to which app when several of them are open at once in Rstudio.

That type of situation:

![image](https://user-images.githubusercontent.com/16836709/69332986-165bed00-0c58-11ea-885e-3621ba9a1b33.png)

Would it be possible to have an option to view the folder name alongside the file name on the tabs?

Something like: `mygreatshinyapp/app.R` 

Thanks for great IDE!

**Comment by jmcphers** [comment]
Agree that this is a good idea! We're tracking it in https://github.com/rstudio/rstudio/issues/2001.
