### ISSUE TITLE
Unit test failure (test-environment.R)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5776]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : master, dev build
    OS Version      : macOS 10.15.1
    R Version       : 3.6.0

### Steps to reproduce the problem
Build debug, then run unit tests (`rstudio-tests`)

### Describe the problem in detail
One failure:
```
✖ |   9 1     | environment
────────────────────────────────
test-environment.R:29: failure: environment object listings are correct
length(contents) not equal to 3.
1/1 mismatches
[1] 4 - 3 == 1
```
### Describe the behavior you expected
No unit test failures. Not sure when this started happening.

**Comment by gtritchie** [comment]
Not seeing this any more, tests are running successfully.

**Comment by gtritchie** [comment]
Oops, user-error. Is still failing for me.

**Comment by MariaSemple** [comment]
This is indeed failing on my machine.
