### ISSUE TITLE
devtools check in build pane does not respect the repos options

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#5793]
Following a discussion in #2277 , I think this a new issue

### System details

    RStudio Edition : RStudio server Pro
    RStudio Version : 1.2.1335-1
    OS Version      : Centos 7.4
    R Version       :  3.5.3

### Steps to reproduce the problem

On an offline server, connecting to an internal repository, inside a package project, run a devtool check using the build pane clicking on the button. It will try to connect to external cran https://CRAN.R-project.org

This is what I get in the build pane
```sh 
devtools::check()

(...)

── Checking ─────────────────────────────────────── poker.utils ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
● _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
● _R_CHECK_CRAN_INCOMING_           : FALSE
● _R_CHECK_FORCE_SUGGESTS_          : FALSE
── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/home/bureau.si.interne/dervieuxchr/devR/poker.utils.Rcheck’
* using R version 3.5.1 (2018-07-02)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘poker.utils/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘poker.utils’ version ‘0.1.3’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ...Warning: unable to access index for repository https://CRAN.R-project.org/src/contrib:

(...)

```

From my understanding of this issue I would expect the problem to be reproduce by

* Configuring a specific repository for R installation (like RSPM)
* Repository is used by `devtools::check()` in R console
* Repository is not used by devtools checks in build pane

Without offline server, I am not sure to see how to observe the change in repository used. 

### Describe the problem in detail

Offline RStudio servers are configured with `options(repos = < internal cran>)` in the `Rprofile.site` (and also `r-cran-repos` set in `rsession.conf` ). 

`devtools::check()` in R console works as expected,using the internal repos

Running devtools check in Build pane throws an error. I get the message above: The check tries to connect to cran.project.org instead of internal cran. 

### Describe the behavior you expected

I would expect check in build pane to behave like in R console and to respect the CRAN configuration. 

Devtools command in run by RStudio in a vanilla session
https://github.com/rstudio/rstudio/blob/d6a8a94530818442c03c3b3acaf38095dc16c394/src/cpp/session/modules/build/SessionBuild.cpp#L1005
I think that is why my `repos` options in `Rprofile.site` is not taken into account. I would expect at least the configuration from RStudio server to be.  

However, using the default repository configure in site wide profile in the servers would be the best. I am not sure to see why devtools check must be run in a vanilla session - It could happen to configure some options and environment variables useful to `devtools::check()`

**Comment by ronblum** [comment]
@cderv Thank you for raising the issue! I'll mark label it for triage. Thanks!

**Comment by trangdata** [comment]
Thank you for raising this issue @cderv. I'm struggling through the exact same issue and it would be *really* nice to have it fixed!

**Comment by daniepi** [comment]
Hi. Having the same issue here. We are using offline RStudio Server with custom `repos` set in `Rprofile.site`.

**Comment by alessap** [comment]
Hello,

AFAIK this is still an issue. In our isolated platform, running RStudio Pro, we also get into trouble having no network access to either https://CRAN.R-project.org/ or https://bioconductor.org/. The `devtools::check()` in console seems to query our private CRAN running on our platform. However, the Check button in the Build pane tries to contact both CRAN.R-project.org and bioconductor.org.  Specifically, we get the following message:

```
....
─  checking package dependencies ...Warning: unable to access index for repository https://CRAN.R-project.org/src/contrib: (3m 0.3s)
     cannot open URL 'https://CRAN.R-project.org/src/contrib/PACKAGES'
   Warning: unable to access index for repository https://bioconductor.org/packages/3.16/bioc/src/contrib:
     cannot open URL 'https://bioconductor.org/packages/3.16/bioc/src/contrib/PACKAGES'
   Warning: unable to access index for repository https://bioconductor.org/packages/3.16/data/annotation/src/contrib:
     cannot open URL 'https://bioconductor.org/packages/3.16/data/annotation/src/contrib/PACKAGES'
   Warning: unable to access index for repository https://bioconductor.org/packages/3.16/data/experiment/src/contrib:
     cannot open URL 'https://bioconductor.org/packages/3.16/data/experiment/src/contrib/PACKAGES'
    OK
...
❯ checking dependencies in R code ... WARNING
  renv was unable to query available packages from the following repositories:
  - # https://cloud.r-project.org/src/contrib ------------------------------------
  error downloading 'https://cloud.r-project.org/src/contrib/PACKAGES.rds' [error code 28]
  error downloading 'https://cloud.r-project.org/src/contrib/PACKAGES.gz' [error code 28]
  error downloading 'https://cloud.r-project.org/src/contrib/PACKAGES' [error code 28]
...

```

Note that we have set our internal CRAN in the renv.lock and running `getOptions("repos")` in our consoleconfirms that. Moreover, we have set the `renv` environment variable RENV_CONFIG_REPOS_OVERRIDE to our internal CRAN.

I can see that `renv` has https://cloud.r-project.org written in two different lines, so I wonder whether that might be the issue.

Best regards,
Alessandro

**Comment by alessap** [comment]
P.S. it is activate.R that has the hardcoded CRAN URL in its code.

**Comment by alessap** [comment]
Any idea when will this fix be available on a RStudio release?

**Comment by kevinushey** [comment]
Unfortunately not in the imminently-coming RStudio release, but it should be part of the following release (currently targeted for 2024.10).

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+223 on Windows 11. 

I tried some complicated attempts using RStudio Server. But instead, the same problem occurred in Desktop, as well, so relying on it.

Verification steps:
1. Create a new project for an R package
2. <kbd>Tools -> Global Options -> Packages</kbd>
3. Change the repo to `https://bioconductor.org/packages/3.16/bioc` (this one easily shows the issue--thanks, @alessap )
4. Check that the repo was changed
```
getOption("repos")
                                          CRAN 
"https://bioconductor.org/packages/3.16/bioc/" 
attr(,"RStudio")
[1] TRUE
```
5. Turn off network access on the machine
6. In the Build Pane, click on <kbd>check</kbd>
    - The log will show the results of `devtools::check(document = FALSE)`
    - The failure to connect to the repository will now only include a reference to the Bioconductor repository 
```
─  checking package dependencies ...Warning: unable to access index for repository https://bioconductor.org/packages/3.16/bioc/src/contrib:
     cannot open URL 'https://bioconductor.org/packages/3.16/bioc/src/contrib/PACKAGES'
```
