### ISSUE TITLE
provide UI for interrupting job within job output display?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#5794]
E.g.

![Screen Shot 2019-11-26 at 2 21 02 PM](https://user-images.githubusercontent.com/1976582/69677557-0d07c180-1058-11ea-8d7a-aa316fa7486f.png)

It'd be nice if there were a Stop button here (at the top right) that I could use to interrupt the job. Right now, one needs to return to the job list to get access to UI for controlling jobs.

**Comment by jmcphers** [comment]
Fixed in #6170.
