### ISSUE TITLE
Making rstudioapi work in non-interactive settings for script

### ISSUE THREAD

**Issue by rappster** [rstudio/rstudio#5796]
Thanks a lot for giving us `{rstudioapi}`! 

Based on this wonderful [blog post](https://irene.rbind.io/post/iterative-testing-plumber/) by @isteves) I usually test my plumber APIs interactively relying on `{rstudioapi} (actual approach explained in more detail below). 

While I learned from #1738 that this is currently not supported, I would kindly ask you to consider making it also possible to use `{rstudioapi}` in non-interactive/separate R sessions such as those created when knitting an Rmd file to leverage the same/an identical API testing workflow.

-----
# A script-based API testing approach

## Define helper functions

```R
start_plumber <- function(path, host, port, sleep = 3) {
  trml <- rstudioapi::terminalCreate(show = FALSE)
  rstudioapi::terminalSend(trml, "R\n")
  Sys.sleep(sleep)

  cmd_1 <- 'devtools::load_all()'
  cmd_2 <- stringr::str_glue(
      "plumber::plumb(\"{path}\")$run(host = \"{host}\", port = {port})\n"
    )
  cmd <- stringr::str_glue("
    {cmd_1}
    {cmd_2}\n
  ")

  rstudioapi::terminalSend(trml, cmd)

  .state[["trml"]] <- trml 
  invisible(trml)
}

kill_plumber <- function() {
  rstudioapi::terminalKill(.state[["trml"]]) #access terminal name
}

check_output <- function(trml) {
  cmd_snippet <- "Starting server to listen on port"

  result <- rstudioapi::terminalBuffer(trml)
  line_cmd <- grep(cmd_snippet, result)

  count <- 0
  while(length(line_cmd) == 0 && count < 10){
    Sys.sleep(2)
    result <- rstudioapi::terminalBuffer(trml)
    line_cmd <- grep(cmd_snippet, result)
    count <- count + 1
  }
  if(length(line_cmd) == 0) stop("Check terminal")

  msg <- result[seq(utils::tail(line_cmd, 1), length(result))]
  message(paste(msg, collapse = "\n"))
  invisible(msg)
}
```

## Define demo plumber API (say this lives in `<project>/plumber.R`)

```R
#' @get /hello-world
function(){
  "hello world"
}
```

## Actual testing based on `{rstudioapi}`

Start terminal that runs/serves the plumber API:

```R
trml <- start_plumber()
check_output(trml)
# Starting server to listen on port 8000
# Running the swagger UI at http://127.0.0.1:8000/__swagger__/
```

Call an API endpoint:

```R
library(magrittr)
res <- httr::GET("http://127.0.0.1:8000/hello-world")
httr::content(res) %>% head()
# [[1]]
# [1] "hello world"
```

Kill the terminal

```R
kill_plumber()
try(check_output(trml))
# Error in f(...) : Unknown terminal identifier '86F24207'
```

# More sophisticated approach via [{plumbplumb}](https://github.com/isteves/plumbplumb) by @isteves

```R
# remotes::install_github("isteves/plumbplumb")

plumber_path <- system.file("plumber.R", package = "plumbplumb")
port <- 8484
plumbplumb::start_plumber(plumber_path, port)

bar <- httr::GET(glue::glue("http://127.0.0.1:{port}/random_praise?seed=2"))
httr::content(bar)

foo <- httr::GET(glue::glue("http://127.0.0.1:{port}/random_praise?seed=3"))
httr::content(foo)
```

**Comment by jmcphers** [comment]
Good news, this is possible on the development branches of RStudio and rstudioapi.

See: https://github.com/rstudio/rstudioapi/pull/155, https://github.com/rstudio/rstudio/issues/4490.

**Comment by rappster** [comment]
Thanks a lot for the pointer!

**Comment by tmcduff** [comment]
> Good news, this is possible on the development branches of RStudio and rstudioapi.
> 
> See: [rstudio/rstudioapi#155](https://github.com/rstudio/rstudioapi/pull/155), #4490.

Jonathan, could you prescribe some handy QA verification steps for this enhancement.

**Comment by jmcphers** [comment]
Absolutely. Try running this R script (a) via the Source command, and (b) in a Job.

```
print(rstudioapi::isAvailable())
print(rstudioapi::isAvailable(child_ok = TRUE))
```

When run via source, you should see TRUE twice. In a job, the first should be FALSE (the API is not available) but the second should be TRUE (the API is available as a child).
