### ISSUE TITLE
arrow keys disabled after changing keyboard back and forth

### ISSUE THREAD

**Issue by rooholaminr** [rstudio/rstudio#5797]
hello guys
I have this problem since I've changed from linux to windows.
this is my version info:
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

by reading the issues I just found out that this problem is related to changing keyboard language.

**Comment by rooholaminr** [comment]
I also found the hack to it. 
you need to use the arrow keys with English keyboard in another environment. it will work in rstudio again surprisingly.
I think it's about keyboard buffers and the arrow buffers are full when changing the keyboard.

**Comment by jmcphers** [comment]
Sorry, we'd need more information to help you with this. Please fill out the issue template completely and include a reproducible example.
