### ISSUE TITLE
SQL autocomplete fails in RMD when the header includes whitespace

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#5799]
With a valid connection to an external data source, the following code chunk will not offer autocomplete suggestions:
~~~
```{sql, connection = con}
SELECT * FROM table;
```
~~~

While this chunk will offer autocomplete suggestions:
~~~
```{sql, connection=con}
SELECT * FROM table;
```
~~~

The difference is the whitespace around `=` in the header.

**Comment by kevinushey** [comment]
Also worth fixing:

![Screen Shot 2019-12-05 at 2 58 13 PM](https://user-images.githubusercontent.com/1976582/70281347-b002be80-176f-11ea-858f-d1c05d19c7f8.png)
