### ISSUE TITLE
community.rstudio.com: HTTPS errors

### ISSUE THREAD

**Issue by paulmenzel** [rstudio/rstudio#5803]
[No idea where to report these issues to.]

Accessing https://community.rstudio.com/t/font-is-giant-in-latest-update-1-2-5001/42017 Firefox 70.0 warns about HTTPS errors.

1.  Loading failed for the <script> with source “https://community.rstudio.com/extra-locales/overrides?v=efd024cbe208d32cc29d80b6d07a7ccd”.

2.  Loading mixed (insecure) display content “http://www.rstudio.com/wp-content/uploads/2019/01/favIcon57.png” on a secure page

**Comment by jmcphers** [comment]
These should be reported on community.rstudio.com itself, using the `meta` tag.
