### ISSUE TITLE
C++ autocompletion doesn't work when Makevars file uses debug options (error: stack protector mode differs in PCH files vs. current file))

### ISSUE THREAD

**Issue by aryoda** [rstudio/rstudio#5806]
I am using
- RStudio Desktop 1.2.5019
- R version 3.4.4 (2018-03-15)
  - Platform: x86_64-pc-linux-gnu (64-bit)
  - Running under: Ubuntu 18.04.3 LTS
- Linux i3770u180402 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I have changed my `~/.R/Makevars` (via `usethis::edit_r_makevars()`) to debug a package using

    CXXFLAGS = -g3 -O0 -Wall

and and recompiled my package.

Autocomplete does no longer work in C++ files.

To diagnose I have enabled diagnostics via `.rs.setClangDiagnostics(2)`.

The output contained the

> error: stack protector mode differs in PCH files vs. current file

Once I cleared my `.Makevars` file and restarted the R session in RStudio again all worked as expected.

PS: You can disable diagnostics in RStudio again via `.rs.setClangDiagnostics(0)`

PS2: I have created this issue after posting my problem in https://github.com/rstudio/rstudio/issues/4685#issuecomment-552249758 and **reproducing it using the daily build (RStudio 1.3.631)...**

**Comment by kevinushey** [comment]
Note to self: we need some way to invalidate the cached PCH when the user's `Makevars` changes.
