### ISSUE TITLE
RStudio build error, if further java versions >=9 installed beside Java 8

### ISSUE THREAD

**Issue by rhurlin** [rstudio/rstudio#5807]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5019
    OS Version      : FreeBSD 13.0-CURRENT amd64 r355223
    Compiler        : clang version 9.0.0
    R Version       : 3.6.1

### Steps to reproduce the problem
On FreeBSD, install openJDK8 and openJDK11 or 12, then build RStudio with clang:
```
cd /usr/ports/java/openjdk8
make install
cd /usr/ports/java/openjdk11
make install
cd /usr/ports/devel/RStudio
make
```
### Describe the problem in detail
FreeBSD has a port for RStudio [1]. This port needs Java as a dependency for build and at runtime. If Java is not installed before the build of RStudio, the port installs openJDK8. Otherwise, it uses the installed version. Afterwards, the build process of RStudio itself works fine on FreeBSD.

```
The problem occurs, if more than one Java version is already installed[2]. In this case, the build also went fine, then the staging process breaks with  
/usr/local/bin/cmake -S/usr/ports/devel/RStudio/work/rstudio-1.2.5019 -B/usr/ports/devel/RStudio/work/.build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /usr/ports/devel/RStudio/work/.build/CMakeFiles /usr/ports/devel/RStudio/work/.build/CMakeFiles/progress.marks
/usr/bin/make -f CMakeFiles/Makefile2 all
/usr/bin/make -f src/gwt/CMakeFiles/gwt_build.dir/build.make src/gwt/CMakeFiles/gwt_build.dir/depend
cd /usr/ports/devel/RStudio/work/.build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /usr/ports/devel/RStudio/work/rstudio-1.2.5019 /usr/ports/devel/RStudio/work/rstudio-1.2.5019/src/gwt /usr/ports/devel/RStudio/work/.build /usr/ports/devel/RStudio/work/.build/src/gwt /usr/ports/devel/RStudio/work/.build/src/gwt/CMakeFiles/gwt_build.dir/DependInfo.cmake --color=
/usr/bin/make -f src/gwt/CMakeFiles/gwt_build.dir/build.make src/gwt/CMakeFiles/gwt_build.dir/build
cd /usr/ports/devel/RStudio/work/rstudio-1.2.5019/src/gwt && ant -Dbuild.dir="bin" -Dwww.dir="www" -Dextras.dir="extras" -Dlib.dir="lib"
Buildfile: /usr/ports/devel/RStudio/work/rstudio-1.2.5019/src/gwt/build.xml

ext:
   [jscomp] None of the files changed. Compilation skipped.

javac:
    [javac] Compiling 1 source file to /usr/ports/devel/RStudio/work/rstudio-1.2.5019/src/gwt/bin

gwtc:
     [java] Compiling module org.rstudio.studio.RStudio
     [java]    [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')

BUILD FAILED
/usr/ports/devel/RStudio/work/rstudio-1.2.5019/src/gwt/build.xml:110: Java returned: 1
```

As far as I understand, something in the gwt build went wrong and therefore does not work in the staging process, if beside openjdk8 another Java version is installed. Unfortunately I have no clue, what to do next.

[1] https://www.freshports.org/devel/RStudio
[2] In my case, versions openjdk11-11.0.5+10.1 and openjdk8-8.232.09.1_1

### Describe the behavior you expected
RStudio should also build correct, if another Java version (>=9) is found beside installed version 8.

The error description is somewhat similar to #3157, but there, only a Java version > 8 is installed.

If needed, I can give more details or a full build.log or I can test something.

**Comment by jmcphers** [comment]
GWT does not support the newer versions of Java. Have you tried setting `JAVA_HOME` to the OpenJDK 8 path prior to building?

**Comment by rhurlin** [comment]
You are right. Setting JAVA_HOME before the build starts, lets RStudio complete the build without a breakage. Now I will have to look for a way, to standardize this in the FreeBSD port ...

Many thanks for your helpful suggestion.

**Comment by jmcphers** [comment]
No problem. Thanks for helping maintain the FreeBSD port!
