### ISSUE TITLE
Closing RStudio occasionally results in a crash message on Windows 7

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5825]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1509
    OS Version      : Windows 7
    R Version       : 3.6.1

### Steps to reproduce the problem

Close RStudio. I can't reproduce this consistently, though.

### Describe the problem in detail

Sometimes, when closing RStudio—at least, by clicking on the "X" button—RStudio crashes. It closes, but after a moment a message pops up informing that RStudio didn't close properly.

### Describe the behavior you expected

RStudio should not crash.

I can't reproduce this consistently, but when it happens next, I'll provide a screenshot and logs.

**Comment by ronblum** [comment]
Here is the error message that Windows provides:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	rstudio.exe
  Application Version:	1.2.5019.0
  Application Timestamp:	5db8d489
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.24520
  Fault Module Timestamp:	5d673de3
  Exception Code:	c0000005
  Exception Offset:	0000000000032b04
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	d8d3
  Additional Information 2:	d8d393a00246294c9750ea4ca68b5efd
  Additional Information 3:	7888
  Additional Information 4:	7888bb57897d5a3acd7c27d847b80fc0

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by kevinushey** [comment]
Windows 7 will be EOL very soon (14 January 2020) so unless this reproduces on a newer version of Windows it's unlikely that we'll be able to investigate.
