### ISSUE TITLE
Keyring package not installing correctly from Ask Secret dialog

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5840]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : macOS
    R Version       : 3.6.0

### Steps to reproduce the problem
- uninstall `keyring` and `sodium` packages
- in RStudio console, execute `rstudioapi::askForSecret("SSN")`
- dialog appears, click on Keyring link

<img width="353" alt="2019-12-05_11-07-30" src="https://user-images.githubusercontent.com/10569626/70266102-b7ff3600-1750-11ea-8d0b-35cc2ca29066.png">

Click Install

<img width="386" alt="2019-12-05_11-10-21" src="https://user-images.githubusercontent.com/10569626/70266208-e4b34d80-1750-11ea-8396-191d0303ee6b.png">

Click Yes

<img width="420" alt="2019-12-05_11-18-16" src="https://user-images.githubusercontent.com/10569626/70266249-f694f080-1750-11ea-85a8-22b3fd60c8ac.png">

Package installation proceeds

### Describe the problem in detail

When done, I still can't use the keyring package in the dialog (the keyring package has not been installed):

<img width="351" alt="2019-12-05_11-19-28" src="https://user-images.githubusercontent.com/10569626/70266364-2f34ca00-1751-11ea-900b-af620f8de1e1.png">

### Describe the behavior you expected

When done, I should be able to use the keyring. If I click the link again, I get the same sequence of packing installation dialogs as before, with the same broken result.

If I install keyring via the Packages pane, then it works.

<img width="352" alt="2019-12-05_11-22-13" src="https://user-images.githubusercontent.com/10569626/70266541-88046280-1751-11ea-8cb3-bcbc9fb01b96.png">

**Comment by jmcphers** [comment]
It's a bummer we can't examine the installation log here. See https://github.com/rstudio/rstudio/issues/5584.

**Comment by kevinushey** [comment]
Just to confirm: is the issue here that the package is not installing correctly, or that the dialog is not responding to a successful package installation?

Are you able to load the `keyring` package after going through these steps, even if the dialog remains disabled?

**Comment by gtritchie** [comment]
It is not installing successfully. An error flashes by in the dialog.

**Comment by javierluraschi** [comment]
Might fail for multiple reasons, in my VM, I have not `TZ` configured...

<img width="1440" alt="Screen Shot 2019-12-05 at 11 34 13 AM" src="https://user-images.githubusercontent.com/3478847/70267435-4f658880-1753-11ea-9186-9f77f57a3e7b.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 11 34 14 AM" src="https://user-images.githubusercontent.com/3478847/70267436-4f658880-1753-11ea-9301-b0edab31e7ea.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 11 34 15 AM" src="https://user-images.githubusercontent.com/3478847/70267439-4f658880-1753-11ea-82bd-d56eff8921f9.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 11 34 17 AM" src="https://user-images.githubusercontent.com/3478847/70267440-4f658880-1753-11ea-8b3a-459fd20c5a1a.png">

**Comment by kevinushey** [comment]
It looks like in this case, it's attempting to install from sources but failing because libsodium is not available or cannot be found:

![Screen Shot 2019-12-05 at 11 36 41 AM](https://user-images.githubusercontent.com/1976582/70267602-9fdce600-1753-11ea-9062-7031a1618255.png)

Perhaps we should just be installing the binary package?

https://github.com/rstudio/rstudio/blob/4ba7236f1949319c0bc99de81f4834dacdba58e3/src/cpp/session/resources/dependencies/r-packages.json#L98-L102

**Comment by javierluraschi** [comment]
Ah! Yes! At some point, Keyring was being developed but we don't need `source: true` anymore.
