### ISSUE TITLE
Multiple broken links on Rstudio Server help tab 

### ISSUE THREAD

**Issue by tmcduff** [rstudio/rstudio#5852]
RStudio Edition : Server and Server Pro
RStudio Version : Orange Blossom - 1.2.5033-1
OS Version : All

Bug description: Multiple broken links on the Rstudio Server Help tab screen. Should be an easy fix, but doesn't look so good to see the errors. 
![Screen Shot 2019-12-05 at 9 16 47 AM](https://user-images.githubusercontent.com/7966616/70344594-e9d6d200-180e-11ea-82b2-340bc39b29c7.png)
![Screen Shot 2019-12-05 at 9 11 12 AM](https://user-images.githubusercontent.com/7966616/70344595-e9d6d200-180e-11ea-9df4-c69649ba0178.png)

![Screen Shot 2019-12-06 at 9 58 45 AM](https://user-images.githubusercontent.com/7966616/70344653-08d56400-180f-11ea-900f-955d47e77c1c.png)

**Comment by gtritchie** [comment]
See also #5081

**Comment by jmcphers** [comment]
These are link redirects, so I have fixed them to point at the correct URLs.

https://github.com/rstudio/rstudio-web/commit/1170508f78436ba978644603d29ae0008ec2bc6b
