### ISSUE TITLE
Functionality to specify R_LIBS_USER from GUI.

### ISSUE THREAD

**Issue by grosscol** [rstudio/rstudio#5860]
## Problem Synopsis
When performing Build>Document, location for R libraries is not picked up from .Rprofile nor shell environment.  Solving that problem is likely difficult for users to track down.

- Problem inspiring issue described [for Ubuntu](https://community.rstudio.com/t/rstudio-build-source-package-not-picking-up-user-libpath/40221/5).
- Corresponding issue described [for macOS](https://github.com/rstudio/rstudio/issues/3235)

## Solution Synopsis
Provide place to set the value of environment variable `R_LIBS-USER` for the Rstudio process.  This will allow child R processes such as `Rscript --vanilla` to use the library location specified, as the system wide default Rprofile should pick it up.

The system default Rprofile by the R-core-team (e.g. `/usr/lib/R/library/base/R/Rprofile`) expands `R_LIBS_USER` from the environment, and subsequently appends those locations to the libPaths.
```
Sys.setenv(R_LIBS_USER =
           .expand_R_libs_env_var(Sys.getenv("R_LIBS_USER"))) #line 55
# ...
invisible(.libPaths(c(unlist(strsplit(Sys.getenv("R_LIBS"), ":")), #line 109
                      unlist(strsplit(Sys.getenv("R_LIBS_USER"), ":")
                      ))))

```

### Testing
The problem is apparent when using Build>Document on a package where one of the dependencies is in a non-default location.  Consider two dummy packages "needed' and "reliant", where the package reliant has a roxygen annotation `@import needed`.
- with R_LIBS_USER unset
  - Rstudio>Build>Document of package "reliant"  should fail if package "needed" is not in a default library location.
  - Rstudio>Build>Document of package "reliant" should succeed if package "needed" is in a default library location.
- with R_LIBS_USER set to non-default location containing "needed" package
  - Rstudio>Build>Document of package "reliant" should succeed if package "needed" is **not** a default library location.

*Shelling out may give an incorrect result if the shell sets the environment variable, or is done in a way where a user's Rprofile is invoked that sets the libPaths.

**Comment by ronblum** [comment]
@grosscol Thank you for raising this suggestion and porting it over from the RStudio Community! We'll review it as we continue development of RStudio.

**Comment by kevinushey** [comment]
Thanks!

I recently made a PR that should help alleviate this issue: now, the active library paths are forwarded during the `devtools::document()` call, so that the library paths in the current session (and so initialized by `.Rprofile` / `.Renviron`) are used during build.

If you want to give this a test, you can do so with the [daily builds](https://dailies.rstudio.com).
