### ISSUE TITLE
Report Linux host platform in rstudio-server version and About

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5862]
A common problem on Linux platforms is that users download a binary for the wrong platform, which results in a binary that will install, but doesn't run, or doesn't run correctly. 

For example, the Ubuntu 14 binary can be installed on Ubuntu 18, but will incur some issues with OpenSSL since it uses OpenSSL 1.0, and won't support e.g. TLS 1.3. 

However, we currently have no way to introspect an installed binary to see which platform it was targeting. So if a customer is having trouble on Ubuntu 18, we have literally no way to tell if they installed the Ubuntu 14 binary or the Ubuntu 18  binary (without some very convoluted forensics). We are thus often obligated to advise that they reinstall the correct version just in case. 

It feels too heavy handed (and error prone) to try to filter this in our pre-installation script by blocking known-problematic installs entirely, but we could dramatically improve our ability to troubleshoot these kinds of issues by including the build host OS in:

1. The output of `rstudio-server version`,
2. The diagnostics report, and 
3. The Help/About dialog.

**Comment by rich-rstudio** [comment]
Verified in Version 1.3.857-3
