### ISSUE TITLE
broken link in shiny cheat sheet

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#5865]
In this cheat sheet : https://github.com/rstudio/cheatsheets/raw/master/shiny.pdf

The given link on the bottom left of first page is : https://rstudio.com/products/shiny-server/ , which is broken.

The correct link is https://rstudio.com/products/shiny/shiny-server/ (added "shiny/" after "products/")

**Comment by ronblum** [comment]
@moodymudskipper Thank you for letting us know!

**Comment by garrettgman** [comment]
Thanks! I moved this over to the cheatsheets issue tracker, https://github.com/rstudio/cheatsheets/issues/118
