### ISSUE TITLE
Error when View()ing gtables

### ISSUE THREAD

**Issue by jarauh** [rstudio/rstudio#5866]
The function View() seems to have problems when applied to objects of class "gtable".

Example:

```r
g <- ggplot2::ggplotGrob(
  ggplot2::ggplot(mtcars) + ggplot2::geom_point(ggplot2::aes(cyl, disp)))
View(g)
```

Error message: Error in names[[i]] : subscript out of bounds

Potentially, this is related to the fact that the class `gtable` has overwritten the length-function:

```r
length(g)  # gives 18
length(unclass(g)) # gives 12
```

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      : Windows 8
    R Version       : 3.6.1

**Comment by ronblum** [comment]
@jarauh Thank you for raising the issue! We'll review it as we continue working on RStudio.

Reproducible with  RStudio Desktop 1.2.5001 on MacOS 10.15.2 and RStudio Server  1.2.5033-1 on Ubuntu 18.04.

**Comment by ronblum** [comment]
Actually, I think this might be an issue in R. @jarauh What do you get if you run this in R, outside of RStudio?

```
> g <- ggplot2::ggplotGrob(
+   ggplot2::ggplot(mtcars) + ggplot2::geom_point(ggplot2::aes(cyl, disp)))
> View(g)
Error in as.data.frame.default(x) : 
  cannot coerce class ‘c("gtable", "gTree", "grob", "gDesc")’ to a data.frame
> length(g)  # gives 18
[1] 18
> length(unclass(g)) # gives 12
[1] 12
```

**Comment by kevinushey** [comment]
The RStudio object explorer should in theory be able to handle these objects (ie: with our own customized `View()` behavior).

However, because ggplot2 grob objects override the `length` method (+ lots of other stuff) this doesn't work as expected.

We likely need to unclass these objects before inspecting them.

**Comment by jarauh** [comment]
Even if it does not work in R itself, it does not mean that it should not work in RStudio.  `View()` behaves really different in R and in RStudio.  In RStudio, `View` is defined as `function(...) .rs.callAs(name, hook, original, ...)`.
