### ISSUE TITLE
alphabet jump in packages tab

### ISSUE THREAD

**Issue by Maschette** [rstudio/rstudio#5877]
when looking in help of a package there is an alphabet in the top to jump to a specific letter in the functions. It would be great if you could have the same in the packages tab to jump to packages of a certain letter.

**Comment by ronblum** [comment]
@Maschette Thank you for the enhancement request. Can you provide the name of a package with this behavior? I'd like to go through the steps. Thanks!

**Comment by Maschette** [comment]
Hi @ronblum, 
I'm not sure it is package specific or just part of the Rstudio help section but I have attached an example of what i mean from the broom  package. 
![image](https://user-images.githubusercontent.com/14663215/70759592-0472f300-1d9b-11ea-8dc9-2b763236acb0.png)

**Comment by gtritchie** [comment]
I believe they are referring to the common desktop app behavior where you can jump to items in a list by typing letters. Marking as an accessibility feature since in general we _should_ do this for all our lists.

**Comment by Maschette** [comment]
Hi Gary, not by typing (although that would be handy) just by having a list of letters at the top that you can click on to jump to that letter in the list.

**Comment by ronblum** [comment]
@Maschette Thanks! Got it—the comparison point is the index of help pages in the Help pane.

**Comment by ronblum** [comment]
@Maschette Thanks! Got it—the comparison point is the index of help pages in the Help pane.
