### ISSUE TITLE
git fetch+merge upstream master. 

### ISSUE THREAD

**Issue by Maschette** [rstudio/rstudio#5878]
Something done somewhat frequently is syncing a fork when the origin has continued to develop as outlined by github: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

it would be awesome to have a button or dropdown option to do this on the git tab.

**Comment by ronblum** [comment]
@Maschette Thank you for the suggestion! We'll review the enhancement as we continue development of RStudio.

**Comment by yonicd** [comment]
has anything happened with this? 

it would still be a great feature to be able to be able to synch upstream or rebase to upstream, or switch into a defined remote that is defined in the git config eg `git remote add upstream` and pull into the local master.
