### ISSUE TITLE
Rstudio create PFA

### ISSUE THREAD

**Issue by addarnr** [rstudio/rstudio#5883]
Hello,
I need to write a PFA for an R code that I wrote.  The R code does not contain any classic machine learning algorithms like trees, or Neurals.  I wrote own functions for noise removals and other calculations.  How do I write the PFA for this code? Please share any examples that you may have. I already have 'aurelius' installed.  The examples that I found are all for classic machine learning algorithms like trees, or Neurals (https://stevenmortimer.com/pfa-with-the-r-package-aurelius/).

Thank you!

**Comment by kevinushey** [comment]
Sorry, but this issue tracker is for issues in the RStudio IDE -- if you have questions about R itself, we recommend you ask your question on the [RStudio community forums](https://community.rstudio.com).

**Comment by addarnr** [comment]
Hello,  I am sorry for not being clear.  The code that I am trying to convert to a PFA is actually written in Rstudio, not R.  

Thank you!
