### ISSUE TITLE
Reflow comment adds 1 extra newline for every "overfull" line

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#5886]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.5033
    OS Version      : macOS Mojave 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

In a package, store this function definition + roxygen comment in a `.R` file below `R/`, presumably `R/foofy.R`.

``` r
#' An amazing function
#'
#' This function does amazing things.
#'
#' @param x Bacon ipsum dolor amet burgdoggen jerky capicola, ribeye cupim pig
#'   cow landjaeger. Now let's talk about the [`CellData`
#'   schema](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#CellData).
#'
#' @seealso Wraps the `spreadsheets.get` endpoint:
#'   * <https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get>
foofy <- function(x) {
  x
}
```

Put your cursor inside the roxygen comment.

Do *Code > Reflow comment*.

The "whitespace" below each "overfull" line (due to incredibly long links that are beyond my control and roxygen2 does not allow reference style links https://github.com/r-lib/roxygen2/issues/849) grows by 1 newline for every execution of *Code > Reflow comment*.

After 3 reflows, I have:

``` r
#' An amazing function
#'
#' This function does amazing things.
#'
#' @param x Bacon ipsum dolor amet burgdoggen jerky capicola, ribeye cupim pig
#'   cow landjaeger. Now let's talk about the [`CellData`
#'   schema](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#CellData).
#'
#'
#'
#'
#' @seealso Wraps the `spreadsheets.get` endpoint: *
#'   <https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get>
#'
#'
#'   
foofy <- function(x) {
  x
}
```

### Describe the behavior you expected

I expect the blank buffer lines between sections of the roxygen comment to NOT expand every time I reflow the comment.

**Comment by jennybc** [comment]
Actually something slightly weirder (but also undesirable) is going on with the `@seealso` directive. Related to a pre-existing thread re: Reflow comment not disturbing bullet lists: https://github.com/rstudio/rstudio/issues/2701#issuecomment-384694914

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/3989

**Comment by jennybc** [comment]
Just coming back to say I'm still experiencing this on 1.4.869.

**Comment by jennybc** [comment]
Still happening in RStudio 1.4.1103

**Comment by jonvanausdeln** [comment]
Verified on 2022.10.0-59

Windows 11 and MacOS

Verified against several different comments.
