### ISSUE TITLE
R console ignores or gobbles '\n' in prompt string

### ISSUE THREAD

**Issue by dgabbe** [rstudio/rstudio#5889]
# Intro

On MacOS 10.13.6, RStudio appears to ignore or gobble `\n` in a prompt string. R.app handles this case correctly.   Unfortunately, I wasn't able to use `reprex` to capture what I was seeing in the console pane so screen shots are used instead.

I like to have my IDE prompts be as close to my bash prompt for consistency.  I've run into cases my working directory is incorrect and the prompt is a quick check.

# Code:

```{r echo=FALSE}

# First, turn off wdprompt package if it is running.  See https://github.com/dgabbe/wdprompt
if (length(find.package("wdprompt", quiet = TRUE)) > 0 ) {
  wdprompt::stop_wd()
}

# You should now see the default R prompt.

options(prompt = "example 1>\n")
TRUE

# You should see "example 1>" followed by a new line.  Your R console command will appear underneath the prompt string.

options(prompt = "example 2\n> ")
TRUE

# You should see "example 2" followed by a new line.  Your R console command will appear after the "> " under the prompt string.
```
# Console Displays

I typed `TRUE` after the prompt is changed each time to show a command and the result.

## RStudio

The behavior of the cursor is not accurately displayed in the screen capture.  

<img width="852" alt="RStudio-console" src="https://user-images.githubusercontent.com/13322029/70825210-e9f84400-1db1-11ea-93ab-9297c1d1fc5e.png">

## R.app 

<img width="664" alt="R app-console" src="https://user-images.githubusercontent.com/13322029/70825283-114f1100-1db2-11ea-8f39-9a893ad13e99.png">

**Comment by ronblum** [comment]
@dgabbe Thank you for filing this! We'll review this as we continue work on RStudio.

Reproduced in RStudio Desktop 1.2.5033-1 on MacOS 10.15.2 Catalina with R 3.6.1.
