### ISSUE TITLE
macbook pro touch bar flashes when typing

### ISSUE THREAD

**Issue by nharrisanalyst** [rstudio/rstudio#5892]
It seems that when using R studio with a macbook pro (the one I use is a MacBook Pro (15-inch, 2017 using Mojave)  that has a touch-bar that when I type in an R file  using R studio the bar flashes. It seems that it is flashing predictive text just as in any other text file as the button is pressed but then disappears creating an annoying flash.

**Comment by gtritchie** [comment]
Please specify what version of RStudio you are using, thanks.

**Comment by nharrisanalyst** [comment]
Version 1.1.463

**Comment by ronblum** [comment]
@nharrisanalyst Thank you for filing the issue! Note that a more recent version of the product is available at https://rstudio.com/products/rstudio/download/#download . In addition, a preview version of 1.2 is available at https://rstudio.com/products/rstudio/download/preview/ .

**Comment by kevinushey** [comment]
I would also strongly recommend updating to the latest version of macOS (Mojave is fairly old at this point).

**Comment by jmcphers** [comment]
@nharrisanalyst  We have not been able to reproduce using the latest version. Are you still seeing this on 1.2.5033?

**Comment by nharrisanalyst** [comment]
I just upgraded and it seems that the bug is now gone thanks for the help.
