### ISSUE TITLE
Live regions not being announced on Windows Desktop IDE

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5895]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.673
    OS Version      : Windows-10
    R Version       : 3.5.0

### Steps to reproduce the problem
- turn on NVDA screen reader
- ensure screen reader support enabled in Tools/Global/Options/Accessibility
- Note, if you have no addins installed, first install some via
```
devtools::install_github("rstudio/addinexamples", type = "source")
```
- Tools / Addins / Browse Addins
- Type a couple letters in the filter field to narrow the results, wait a couple seconds

### Describe the problem in detail
- Nothing is announced. This is true of any aria-live regions in the IDE.

### Describe the behavior you expected
- In Chrome or Firefox with RStudio Server, screen reader will announce something like: "Found 10 addins matching a".

This is a Qt issue. I have opened: https://bugreports.qt.io/browse/QTBUG-80832

**Comment by gtritchie** [comment]
Confirmed this works as expected on Electron / RStudio.

**Comment by mikebessuille** [comment]
closing per gary's test
