### ISSUE TITLE
Python parsing issue

### ISSUE THREAD

**Issue by 2er0** [rstudio/rstudio#5904]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1335
    OS Version : Fedora 31  
    R Version : 3.6.1 

### Steps to reproduce the problem

RUN:
```
def foo():
    width = "foo"
    print(width)
    
    height = "bar"
    print(height)

    print(f'{width} -> {height}')
```
OUTPUT:
```
> reticulate::repl_python()
Python 3.7.5 (venv/bin/python)
Reticulate 1.13 REPL -- A Python interpreter in R.
>>> def foo():
...     width = "foo"
...     print(width)
...     
...     height = "bar"
...     print(height)
... 
>>>     print(f'{width} -> {height}')
NameError: name 'width' is not defined
```

### Describe the problem in detail

```
def foo():
    width = "foo"
    print(width)
    !!! <- this line has white whitespace intend
    height = "bar"
    print(height)
!!! <- this line has no whitespace intend and breaks the parsing of the function
    print(f'{width} -> {height}')
```
Our Git automatically removes whitespace which leads to this issue.

### Describe the behavior you expected

If a section contains an empty line and then a code line with the same intend then this belongs to the same section as before.

**Comment by 2er0** [comment]
Is there any update?
In which version of RStudio or Package will this be fixed?

**Comment by kevinushey** [comment]
We're planning to spend some more time on Python IDE integration in v1.4 and so hopefully will be able to take a look at this then. However, IDE input is fundamentally newline-delimited so adding support for this may be challenging.

**Comment by 2er0** [comment]
Ok
Thanks for the Information - would be nice to have this feature ;)

**Comment by dfalty** [comment]
Hey @kevinushey I'm still seeing the issue with the same repex on 1.4.484.

**Comment by R-Hannibal** [comment]
@2er0, thanks so much for finding and reporting this issue. 

We have a fix in place in our latest daily build of the upcoming 1.4 release (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by melissa-barca** [comment]
Verified in 1.14.1017

**Comment by BradWebb101** [comment]
I have observed this issue again with reticulate v1.20 

> reticulate::repl_python()
Python 3.6.13 
Reticulate 1.20 REPL -- A Python interpreter in R.

R studio output:
>>> time_start = time()
>>> for row in df.iterrows():
...   print(row['numbers])
SyntaxError: unexpected EOF while parsing (<string>, line 1)
IndentationError: unexpected indent (<string>, line 1)
>>> time_end = time()
>>> print(f'This process took {round(time_end - time_start,4)} seconds')
This process took 0.0284 seconds

There is a syntax error in the for loop, it errors out but still runs the code after the for loop. Leading me to believe that reticulate is sending the code line by line again and not as a chunk.
