### ISSUE TITLE
Setting error option in .Rprofile makes RStudio crash in a MS terminal server

### ISSUE THREAD

**Issue by tomtom** [rstudio/rstudio#5905]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463
    OS Version      : Windows 2008 R2 SP1
    R Version       : 3.6.2.

### Steps to reproduce the problem

1. Set error option in .Rprofile: `options(error = function () {utils::dump.frames(); traceback()})`
2. Run Rstudio

### Describe the problem in detail

R Message: Fatal error: ERROR r error 4 ... OCCURED AT rstudio::core::Error rstudio::r::exec::executeSafely

### Describe the behavior you expected

Start RStudio

The same line of code works on Win 10 with RStudio 1.2.5019. Was it fixed in the meantime? I cannot change the installation in the VM.

**Comment by kevinushey** [comment]
This was indeed fixed in v1.2, and unfortunately the only workaround for older versions of RStudio is to either:

1. Use an older version of RStudio (IIRC this incompatibility was introduced with R 3.5 or R 3.6), or
2. Upgrade RStudio to v1.2.
