### ISSUE TITLE
Date and time format settings for files pane

### ISSUE THREAD

**Issue by francisbarton** [rstudio/rstudio#5908]
This is a tiny thing but I would prefer to be able to see the time in the Modified column in 24h format, rather than like "5:00 PM".
Could there be a setting exposed somewhere in Global Options to be able to customise this, and potentially customise the whole datetime format? Would be nice to have.

**Comment by styrrellOU** [comment]
I would like to have this - I can't see any way of changing the format. 95% of the world uses day-month-year and a 24 hour clock. It is really annoying - and at times confusing - to see the (frankly just wrong) US formats being forced on us defaults. Could you please re-open or point me at a solution? Thanks

**Comment by gtritchie** [comment]
When we investigate this be sure to consider Server/Workbench (i.e. the sessions are running on a server that could have different date/time settings, be in a different timezone, etc.).
