### ISSUE TITLE
help users learn keyboard shortcuts

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rstudio#5911]
Using keyboard shortcuts extensively in RStudio is a boon for productivity (and may help avoid RSI from excessive mousing).
RStudio has great keyboard support (with more to come in the current accessibility push).

However, I've found it hard to really drill the shortcuts into my brain.
When working on any given project, I usually don't have the mental bandwidth to learn new shortcuts.

So I've frontloaded learning them in RStudio, as well as other applications.
While looking for ways to learn shortcuts, I came across this (proprietary, macOS-only) app: http://mouseless.app.

![mouseless](https://user-images.githubusercontent.com/5372770/71247630-655d7680-2319-11ea-9b55-1dbbfb868795.gif)

Using this training app has helped me tremendously, though it does not yet support RStudio. (I have asked the devs to add RStudio, not sure how likely that is).

That made me wonder whether/how such keyboard shortcut learning app could be build for RStudio.

I've thought about doing this as a shiny app (mainly because it's the only thing I know how to), but this would cause the problem of overloading keybindings: If used inside RStudio *or* a browser, *learning* a keyboard shortcut would also trigger some behavior in RStudio or the browser.

A shortcoming of the http://mouseless.app-approach is that you just learn the shortcuts by their title ("cycle through tabs"), but you don't see / associate it with the change in the GUI.
That means you still have to connect the dots between what you'd like the GUI to do and the associated shortcut title.
I've wondered whether an [intro.js](https://introjs.com)-like overlay to RStudio (since it *is* just using web tech) might further assist users in learning keyboard shortcuts.

I'm considering building something in this vein myself (a shiny app), but wanted to hear what the rstudio dev team has to say about this.

1. What are your **thoughts/recommendations** on learning keyboard shortcuts for RStudio, and a possible app/UI to help with that?
2. If there was a shiny app (or perhaps better, a shiny gadget) for learning keyboard shortcuts, would it be possible / would you consider **disabling keyboard shortcuts in RStudio** while that app is in focus, so as to avoid **overloading keybindings**?
3. Would you consider adding an intro.js-like **overlay to RStudio to learn shortcuts**? (I haven't thought this through).

----

Ps.: This might also be a good issue for community.rstudio.com, but I take it that [you prefer feature requests on github](https://community.rstudio.com/t/ide-wish-list-collation/689/10).
Let me know if you'd rather have this discussed on community first.

Pps: This is also tangentially related to adding a command palette in #5168; in editors such as sublime, atom and vscode I think a lot of people use the command palette to learn keyboard shortcuts.

**Comment by ronblum** [comment]
@maxheld83 Neat idea! This is best place to raise this kind of feature request. Not only does posting here make us aware of ideas for new features, etc., but there might be other users who would find them useful—and if that's the case, folks can mark tickets with 👍 at the top, which tells us how popular the enhancements are. And we also always encourage the user community to come up with stuff*, too, such as addins.  So, thank you for the suggestion, and especially all the details and links!


*_stuff_ is a precise a technical term.

**Comment by gtritchie** [comment]
Only slightly related, but I recently added a feature in 1.3 that lets you switch on a mode where hitting shortcuts will tell you what command they are bound to (without invoking the command), or if they are not bound at all.

https://github.com/rstudio/rstudio/pull/6133

**Comment by txbrown** [comment]
I saw this issue while googling about the mouseless app and I wanted to let you know that the creators made the app open source - https://github.com/ueberdosis/mouseless
