### ISSUE TITLE
Packages installed on demand do not use renv shim

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5914]
### System details

    RStudio Edition : Both
    RStudio Version : 1.3.670

### Steps to reproduce the problem

1. Uninstall the rmarkdown packagte
2. Start a new project, and check "Use renv with this project"
3. Create a new rmarkdown document
4. Install rmarkdown when prompted

### Describe the problem in detail

The package is not installed using the renv `install.packages` shim.

### Describe the behavior you expected

The package should be installed using renv. It isn't, because we use a vanilla R process to perform the installation, and that process doesn't run startup scripts so doesn't get the shim.

https://github.com/rstudio/rstudio/blob/c675ccde38bf0a9d635d57e475d5ac0ac706a283/src/cpp/session/modules/SessionDependencies.cpp#L411-L414

The fix is probably just to get an renvContext and update the above so we don't use a vanilla R session to do on-demand installations inside renv projects.

**Comment by dfalty** [comment]
Verified fixed 1.3.926-2
