### ISSUE TITLE
Shiny viewer type change on Run App does not work

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#5920]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.670

### Steps to reproduce the problem

1. Create a new single-file Shiny application (File -> New -> Shiny ...)
2. With app.R open in the editor, pull down the Run App menu
3. If Run in Viewer is selected, select Run in Window, and vice versa
4. Pull down the Run App menu again

### Describe the problem in detail

The preference does not change; the viewer type selected in (3) remains unchecked.

### Describe the behavior you expected

The preference should change.

**Comment by jmcphers** [comment]
Noticed this while I was testing https://github.com/rstudio/rstudio/pull/5909, but the problem predates this, and was probably introduced in the original user preferences overhaul.

**Comment by dfalty** [comment]
Verified fixed 1.3.822-1
