### ISSUE TITLE
Cursor is in my way when I type in console or source windows

### ISSUE THREAD

**Issue by braunsb** [rstudio/rstudio#5926]
I want my cursor to disappear while I type and reappear when I move it again. I find it distracting that I put it right where I want to type something, then it blocks my view of what I'm typing. Can anything be done about that? Thanks!

**Comment by ronblum** [comment]
@braunsb Thank you for raising the issue. Can you provide the environment you're working in so that we can try to reproduce it?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by braunsb** [comment]
Thanks for the response. I've looked into it a little further. It isn't you guys—it's Mac OS.

**Comment by ronblum** [comment]
@braunsb Thank you for the update! If you find that the issue does end up being RStudio-specific, or if you find a way around the MacOS issue, please feel free to update the ticket. Thanks!
