### ISSUE TITLE
Using setMKLthreads() in MRO 3.5.3 in combination with RStudio crashes R

### ISSUE THREAD

**Issue by tomwenseleers** [rstudio/rstudio#5933]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.2.5033 
    OS Version      :  Windows 10
    R Version       :  MRO 3.5.3

### Steps to reproduce the problem & problem description & description of expected behavior

Installing Microsoft R Open 3.5.3 from https://mran.microsoft.com/documents/rro/installation
and then calling RevoUtilsMath::setMKLthreads(4) to set the number of threads to use in the Intel MKL BLAS crashes R & RStudio. Doing the same in the console (Rgui.exe), however, works as expected, so I presume the problem must be due to some interaction with RStudio.

**Comment by jmcphers** [comment]
Do you have a call stack or mini dump for the crash?

**Comment by tomwenseleers** [comment]
Well problem is that it crashes the R session in RStudio before I can ask for a traceback() - so it just gives me a window "R Session Aborted"... But the problem should be easy enough for you to reproduce...

**Comment by kevinushey** [comment]
A Windows minidump suggests the crash is happening in Rlapack.dll, but without symbols it's hard to say anything more.

Odds are this needs to be resolved on Microsoft's side.
