### ISSUE TITLE
Keyboard shortcuts in separate source windows

### ISSUE THREAD

**Issue by stgries** [rstudio/rstudio#5936]
With RStudio 1.3.599 on Linux Mint 19.3 (running R version 3.6.2 (2019-12-12)), keyboard shortcuts do not work if one works with code in a separate source window. In particular,

- copy and paste do not work with CTRL-C and CTRL-V: nothing gets copied into the clipboard;
- CTRL-2 creates two new Untitled source files Untitled1 and Untitled2.

**Comment by stgries** [comment]
Oops, forgot to mention: in the separate source window, one CAN copy something into the clipboard with right-click>copy - but not with CTRL-C or with C (being underlined in the context menu that pops up upon right-click).

**Comment by ronblum** [comment]
@stgries Thank you for reporting the issue! I can reproduce the first example on Ubuntu 18.04 with build 1.3.690 and MacOS 10.15 Catalina with build 1.3.606 (using CMD-C and CMD-V), so I'm marking this is a bug. I can't 

Note: this is not a regression, as it works in RStudio Desktop 1.2.5033. I also can't reproduce the issue with CTRL-1 and CTRL-2.

**Comment by stgries** [comment]
Glad you replicate the CTRL-C/CTRL-V thing. Re the CTRL-1 thing, let me give a clearer step-by-step:

- I start RStudio and press CTRL-N to create a new code file;
- I click "Show in new window", which moves Untitled1 to a new window and focuses on it;
- I press CTRL-SHIFT-2, which moves the focus to the other RStudio window and shows 2 new code files in there: Untitled1 and Untitled2;
- when I then close the extra window with CTRL-W, I get back to RStudio with the 2 new code files.

**Comment by kevinushey** [comment]
This is likely unintended fallout from making Copy + Paste official commands. See also:

https://github.com/rstudio/rstudio/issues/5894

**Comment by kevinushey** [comment]
Fixed via https://github.com/rstudio/rstudio/pull/6158.

**Comment by stgries** [comment]
Cool, thanks guys!!

**Comment by ronblum** [comment]
Copy/paste verified on Ubuntu 18.04 and MacOS 10.15.4. Opening a separate issue for Ctrl+Shift+2.
