### ISSUE TITLE
Support lua files in Go to file search box

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#5937]
It would be nice if `.lua` files can be supported in the Go to file search box. They are a great addition to Rmarkdown using pandoc and the syntax highlighting is already supported  

Here is what I get working on Rmarkdown package currently: `pagebreak.lua` is not found
![image](https://user-images.githubusercontent.com/6791940/71560384-7b7ddc00-2a69-11ea-9d1e-11fb786579f8.png)

Working with RStudio IDE 1.2.5019 here. 

Thank you !

**Comment by kevinushey** [comment]
This sounds reasonable to me, especially since we already have registered `.lua` as a known filetype.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rstudio/commit/9b1bc43dd4455122eeed142ccf5722018f1e06db
