### ISSUE TITLE
C++ autocompletion deactivates cursor

### ISSUE THREAD

**Issue by ksavin** [rstudio/rstudio#5941]
A minor (and by the looks of it, easily fixable issue).

Tested RStudio Desktop 1.2.5033, Windows 10

C++ autocompletion window behaves a bit differently from R autocompletion. If the mouse cursor happens to be at the location where autocomplete pops in, the typing cursor deactivates/defocuses, which prevents further typing/refining autocompletion.

![Rcpp_autocomplete](https://user-images.githubusercontent.com/4972262/71599264-146b3080-2b18-11ea-9e1f-45b056418005.gif)

STR: 
1. Trigger C++ autocompletion.
2. Hover mouse over one of the suggested options.
3. Try typing.

**Comment by kevinushey** [comment]
The problem here is that the autocompletion popup steals focus when the mouse cursor happens to be located at the position where the popup is displayed.

**Comment by R-Hannibal** [comment]
@ksavin, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build for the upcoming 1.4 release (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by ksavin** [comment]
@R-Hannibal  Yes, everything works as expected in the latest build. Thank you.
