### ISSUE TITLE
Suggestion: Keep text highlighted after auto-wrapping in quotes

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#5944]
Another convenience feature that I find quite nice from Atom:

I'm writing a loop that will run `system` on some indexed object, e.g.:

```
sprintf(cmd_fmt, DT$package[ii])
```

To test, I want to replace it with a specific value, e.g.:

```
sprintf(cmd_fmt, 'MASS')
```

To do so in RStudio, I think the most efficient way is:

 - highlight `DT$package[ii]`
 - backspace
 - type the full string: `'MASS'` including both `'` (I have auto-`''` turned off)

In Atom, it's ever-so-slightly nicer:

 - highlight `DT$package[ii]`
 - type `'` to auto-wrap
 - type `MASS`

This is possible because after typing `'` to auto-wrap, `DT$package` remains highlighted, so when I type `MASS`, `DT$package` is overwritten as usual with highlighted text overwrite. Whereas in RStudio, after auto-wrapping the cursor is moved after the `'`.

It's quite small -- by my accounting I've saved 2 keystrokes (backspace + 2nd `'`), but convenient nevertheless.

OTOH, this means we've got to `arrow` our way out of the highlighted text to continue typing to the right; I'm not sure if other users rely on this behavior, so maybe at best this new suggestion could be an option.

Thank you for your consideration.

**Comment by ronblum** [comment]
@MichaelChirico Thank you for the suggestion! We'll review it during our ongoing development of RStudio.
