### ISSUE TITLE
Console input unaffected by "Allow drag and drop of text" option

### ISSUE THREAD

**Issue by khvorov45** [rstudio/rstudio#5948]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows 10 1809
    R Version       : 3.6.2

### Steps to reproduce the problem

1. Turn "Allow drag and drop of text" off in Tools > Global options > Code > Display

2. Attempt to drag and drop text in Console input (drag and drop will still be active there).

### Describe the problem in detail

"Allow drag and drop of text" works correctly for Source input but not for Console input. It also breaks the blinking cursor behavior [#4895](https://github.com/rstudio/rstudio/issues/4895)

### Describe the behavior you expected

Drag and drop not being active in Console after turning it off.

![rstudiotermdrag](https://user-images.githubusercontent.com/44919476/71647550-ec184780-2d4c-11ea-8d6a-ebac123c1a9b.gif)

**Comment by ronblum** [comment]
@khvorov45 Thank you for filing the issue. I can reproduce it in RStudio Desktop 1.2.5033 on MacOS 10.15. I'll mark it as a bug to be reviewed as we continue development of RStudio.
