### ISSUE TITLE
Make `Insert Roxygen Skeleton` respond if documenting R6 class

### ISSUE THREAD

**Issue by akgold** [rstudio/rstudio#5956]
Roxygen recently added support to document R6 classes: https://www.tidyverse.org/blog/2019/11/roxygen2-7-0-0/

However, the documentation looks a little different than a normal R function outside an R6 class:
```r
#' R6 Class representing a person
# From examples in blog post above
#'
#' A person has a name and a hair color.
Person <- R6::R6Class("Person",
  public = list(
    #' @field name First or full name of the person.
    name = NULL,

    #' @field hair Hair color of the person.
    hair = NULL,

    #' @description
    #' Create a new person object.
    #' @param name Name.
    #' @param hair Hair color.
    #' @return A new `Person` object.
    initialize = function(name = NA, hair = NA) {
      self$name <- name
      self$hair <- hair
      self$greet()
    }
))
```

If you click `Insert Roxygen skeleton` inside a function in an R6 class, it doesn't recognize that it's inside an R6 class, and standard function documentation appears. It also appears unindented (though auto-indenting moves it to the correct spot).
```r
R6::R6Class("Class", 
            public = list(
#' Title
#'
#' @param a 
#' @param b 
#'
#' @return
#' @export
#'
#' @examples
              add = function(a, b) {
                a + b
              }
            ))
```

It would be awesome if inserting a Roxygen skeleton inside an R6 class provided the right formatting  by default.

**Comment by dmurdoch** [comment]
This is still an issue.

**Comment by saumil-sh** [comment]
This is still an issue. Please re-open this!
