### ISSUE TITLE
MLproject file should be searchable with "go to file/function" dialogue

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/rstudio#5963]
This would just make working with MLflow projects a bit more convenient. In the below screenshot, one can see that the file does not show up as a suggestion. 
![Screenshot from 2020-01-06 12-16-51](https://user-images.githubusercontent.com/10477073/71815062-872b5d00-307e-11ea-9b41-a10698acc92f.png)

I am using RStudio version 1.2.5019

**Comment by ronblum** [comment]
@lorenzwalthert Thank you for reporting this! We'll review this ticket as we continue development of RStudio.

[Dev: I'm not sure if this falls under bug, enhancement, or by-design, so I'm conservatively marking this as bug & triage.]

**Comment by jmcphers** [comment]
This is currently tracked in https://github.com/rstudio/rstudio/issues/2522.
