### ISSUE TITLE
rsession.conf not readable by user causes session to die

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#5964]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.5033-1
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

I believe this is an open source issue, but it may be Pro only since that is where I hit it. In any case, I did the following on RSP:
- Build server with `/etc/rstudio/rsession.conf` having `0600` permissions (owned by root)
- Start a session as a user on the server
- This is the only error message I saw in the log, which may be unrelated:
```
ERROR system error 111 (Connection refused); OCCURRED AT: void rstudio::core::http::LocalStreamAsyncClient::handleConnect(const rstudio_boost::system::error_code&) /var/lib/jenkins/workspace/IDE/pro-pipeline/v1.2-patch/src/cpp/core/include/core/http/LocalStreamAsyncClient.hpp:119
```
- Further, the user had a poor experience of "Could not connect to session."

### Describe the problem in detail

Ultimately, it seems that the session fails to start with little / no warning or notice if / when the `rsession.conf` file is not readable by the user. `rstudio-server verify-installation --verify-user rstudio` showed me the problem (is that available in open source?):

```
Unable to open config file: /etc/rstudio/rsession.conf
```

I suspect this could be a problem if group ownership / etc. excluded a user from being able to read the file as well.

### Describe the behavior you expected

I expected (1) the R Session to start gracefully without the `rsession.conf` config or (2) the server to fail in a more meaningful / descriptive way. Especially since other configuration files in `/etc/rstudio` are fine with (or even required to have) 0600 permissions, it was not immediately clear that `rsession.conf` kills R sessions if not readable by the end user.

This problem is the same and is still silent when using Local Launcher. We just get an exit code on the session (exit code 1) with no logging about why.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by colearendt** [comment]
Aww sad... any chance you can re-open this, stale-bot?

**Comment by mikebessuille** [comment]
Need to update the error message to make this more clear.  @colearendt would you expect the session to start anyway, with a default configuration?

**Comment by colearendt** [comment]
I'm not sure what I expected about "ideal behavior," to be honest. It is a weird point because (1) the IT admin is responsible for it, (2) the logging will likely only be accessible to the IT admin, (3) the user is the one who is affected (i.e. who gets the failure). Also, it gets really tricky when rsession.conf is inside of a docker image being launched by the launcher.

I also am not sure what the potential side effects of "starting anyway" would be... it's possible that disabled features and such would be accessible, which could be problematic. I think clear messaging is the imperative here, regardless of what we decide to do. I.e. maybe print the ownership information about the rsession.conf / who it is trying to be read by.

**Comment by kevinushey** [comment]
I just tried this (using RSP + local launcher) and I see the following in the diagnostics report:

```
08 Jul 2021 23:34:54 [rserver-monitor] ERROR 08 Jul 2021 23:34:54 [rserver] ERROR rserver-launcher: Unable to open config file: /etc/rstudio/rsession.conf; LOGGED FROM: void rstudio::server::ProcessMonitor::onProcessStderr(rstudio::server::ProcessMonitor::Process, const string&) src/cpp/server/ServerProcessMonitor.cpp:247|||
```

I'm curious why this isn't showing up in the logs in your case.

**Comment by colearendt** [comment]
Interesting! Yeah, it is possible that behavior inherently changed since 1.2 when I reported this 😄

**Comment by kevinushey** [comment]
If I understand correctly, it looks like Karl fixed this a while back, with https://github.com/rstudio/rstudio/commit/32e0d9e89c521643f7734026aa5b2f292620c48d.

@colearendt, would you be able to verify if you see an appropriate error (at least something admin-accessible) in this case?

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 1.5.192-1
    OS Version      : ubuntu20
    R Version       : 4.0.3

Verified that when `/etc/rstudio/rsession.conf` is set to 0600 permissions,
- the message `Unable to open config file: /etc/rstudio/rsession.conf` appears in the jobs details output
- the following error appears in `/var/log/rstudio/rstudio-server/rserver.log` : 
```

2021-07-13T19:06:12.758198Z [rserver] ERROR rserver-launcher: Unable to open config file: /etc/rstudio/rsession.conf; LOGGED FROM: void rstudio::server::ProcessMonitor::onProcessStderr(rstudio::server::ProcessMonitor::Process, const string&) src/cpp/server/ServerProcessMonitor.cpp:247
```
- the following error appears in `/var/log/rstudio/rstudio-server/rsession-<username>.log` :
```

2021-07-13T19:06:16.601632Z [rsession-valerie] ERROR system error 2 (No such file or directory) [path: /etc/rstudio/rsession.conf, description: Unable to open config file: /etc/rstudio/rsession.conf]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::openForRead(std::shared_ptr<std::basic_istream<char> >&) const src/cpp/shared_core/FilePath.cpp:1429; LOGGED FROM: bool rstudio::core::program_options::parseConfigFile(rstudio_boost::program_options::variables_map&, const string&, const rstudio::core::program_options::OptionsDescription&, bool) src/cpp/core/ProgramOptions.cpp:136```
