### ISSUE TITLE
Two backslashes change to a pipe and backslash on Debian 10

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5969]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Debian 10
    R Version       : 3.6.1

### Steps to reproduce the problem

In the source editor, type `#' "\\d+4"`

### Describe the problem in detail

The first backslash is converted to a pipe: `#' "|\d+4"`

### Describe the behavior you expected

The first backslash shouldn't change to a pipe.

[See issue #5924]

**Comment by kevinushey** [comment]
> The first backslash shouldn't change to a pipe.

I don't quite understand, and this behavior doesn't reproduce for me. What I do see is that the `\d` is highlighted in that text:

![Screen Shot 2020-01-07 at 11 19 19 AM](https://user-images.githubusercontent.com/1976582/71922357-a1793f80-313f-11ea-994e-38c0f4891c49.png)

Is it this highlighting that's incorrect? If not, can you elaborate a bit further on what you're seeing?

**Comment by kevinushey** [comment]
You might also want to confirm whether this depends on the font being used.

**Comment by ronblum** [comment]
Oops—I couldn't copy over from the VM so I typed our the result, and mistyped it:
typing
`#' "\\d+4"`
results in
`#' "|\d+4"`
I'll try other fonts.
