### ISSUE TITLE
Group information missing  in markdown 

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#5970]
Currently, when you display a grouped data frame "inline", it doesn't show any information about grouping:

<img width="739" alt="Screenshot 2020-01-06 at 1 54 35 PM" src="https://user-images.githubusercontent.com/4196/71919146-8ad7e600-3149-11ea-804c-9194cbd2f347.png">

I think this is one source of [grouping pain](https://github.com/tidyverse/dplyr/issues/4166) in dplyr.

**Comment by jmcphers** [comment]
There is currently no proposal for treatment so we need to think of something here. Colors? The default print method lists the grouped columns in a separate note.

![image](https://user-images.githubusercontent.com/470418/71940533-8290a280-316b-11ea-887e-1f7920c14730.png)

We can get the list of grouped columns by using `group_vars()`.

**Comment by hadley** [comment]
Perhaps the most general treatment would be to consider allowing a line or two at the top for summary information. That would keep it extensible for the future.

**Comment by jmcphers** [comment]
via @hadley , `tbl_sum()` is what we'd call to get summary information.

```r
library(dplyr, warn.conflicts = FALSE)
mtcars %>% tbl_sum()
#>         Description 
#> "df[,11] [32 × 11]"
mtcars %>% as_tibble() %>% tbl_sum()
#>  A tibble 
#> "32 x 11"
mtcars %>% group_by(cyl, vs) %>% tbl_sum()
#>      A tibble        Groups 
#>     "32 x 11" "cyl, vs [5]"
mtcars %>% rowwise(cyl) %>% tbl_sum()
#>  A tibble   Rowwise 
#> "32 x 11"     "cyl"
```

> you already display the first element so I'd suggest dropping that

**Comment by R-Hannibal** [comment]
@hadley, thanks again for reporting this issue.

We have a fix in place in our latest Daily build for the upcoming 1.4 release (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build (no worries if not, entering the issue report alone is a tremendous help and we appreciate it 👍)?

**Comment by hadley** [comment]
It looks great 😄
