### ISSUE TITLE
Keyboard shortcut for "run current line/selection and PRINT the output"

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5972]
In many cases, the user needs to see the output of running the current line/selection. It would be helpful to assign a keyboard shortcut to this goal.

Note: Currently, on iOS, both "control+return" and "command+return" run the current line/selection _without_ printing the output. One of these keyboard shortcuts can be used for the above purpose. Otherwise, they would do a duplicate job while a key task, mentioned above, remains without a shortcut.

**Comment by ronblum** [comment]
@hzarkoob Thank you for raising this. However, I'm not sure I understand: can you provide a simple reproducible example? For example, with something simple like
`1`
in an R file using cmd-return, the result `[1] 1` is displayed in the console, and with an R Markdown file, the result is displayed in both the Rmd file and the console.

**Comment by hzarkoob** [comment]
@ronblum Sure. Here is an example:

###
a = 0
b = a + 1

If we run the above codes, the outputs will not be displayed. It can be verified in both .R and .Rmd files. 

Of note, including the above lines in parentheses indeed results in printing the outputs. It would be great if we could get the same functionality through keyboard shortcuts. 

###
(a = 0)
(b = a + 1)

**Comment by ronblum** [comment]
@hzarkoob Ah! Thank you for the example. OK, I'll mark this as an enhancement to review.
