### ISSUE TITLE
Keyboard lag when connected to employer network

### ISSUE THREAD

**Issue by petemere** [rstudio/rstudio#5975]
### Summary
I recently upgraded R to version 3.6.2 and RStudio to version 1.2.5033 (and since then, to the preview version, 1.2.5036 and then the latest daily, 1.3.713) and now any keyboard input in either the console or source window has a lag of up to a couple of seconds, but **only** when my computer is connected to our work intranet. This did not happen on the previous version of RStudio (I don't recall the version number, but I last updated it in Jan 2019).

### System details
    RStudio Edition : Desktop
    RStudio Version : 1.2.5033, but also replicated on the current preview version, 1.2.5036, and the current daily build, 1.3.713 (but see notes below about the daily).
    OS Version      : Windows 7 Enterprise, Service Pack 1
    R Version       : 3.6.2

### Steps to reproduce the problem
Open RStudio while connected to my employer's network, then enter any keystrokes into a source window or the console.  The actual keystrokes don't matter; it could be a command, comment text, hitting TAB for auto-complete, or even just hitting ENTER in the console for a new line.

NB: In the daily version (1.3.713) the lag does not affect typing _comments_ in a source window, but remains when typing, editing, or executing code in either window, or even hitting ENTER on a blank line in the console.  Interestingly, hitting ENTER after typing a comment in the console takes just as long to return as a simple command (e.g. ls()).

Clearly, reproducing this outside my employer's network may be difficult, but I am not sure what further information would be relevant.

### Describe the problem in detail
There is a delay of between 1 and 3 seconds between typing and the result appearing in the relevant RStudio window.

- The lag happens both when working on an RStudio project and when working on a R script file not part of a project.
- The lag happens on both version-controlled and non-version-controlled projects (I've tested this with a project that uses intranet Bitbucket version control, but not git).
- The R script source file and package library folder are both on my laptop (i.e. not on network drives).
- There is no lag at all when I use the R GUI directly (i.e. without RStudio), regardless of what networks I'm connected to.
- In the 1.2.5033 and 1.2.5036 (preview) versions, the lag symptoms don't appear immediately on connecting to the intranet, nor do they disappear immediately after disconnecting from it; it takes around 10 seconds to change.
- In the 1.3.713 (daily) version the lag takes longer to appear (> one hour, but only two experiments with this version) after connecting to my employer's network with RStudio already open, but happens immediately if starting RStudio while already connected to my employer's network.  It also disappears immediately when disconnecting from my employer's network.
- There is no lag when not connected a network nor when only connected directly to the internet.
- I have already switched off the "Restore last cursor position when opening file" option, but it has no effect.

I have also posted this on the RStudio community website: https://community.rstudio.com/t/rstudio-desktop-slow-lagging-when-connected-to-intranet/48705

### Describe the behaviour you expected
Near instant response.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
RStudio has a front end (rstudio.exe) and back end (rsession.exe) that communicate over TCP. My guess is that, while connected to your employer's network, the packets travelling between the front and back ends are having to travel through some kind of local firewall or proxy which dramatically slows them. 

Does any software govern the connection to your employer's network? If so, maybe it has a firewall or proxy exclusion you could apply to rstudio.exe/rsession.exe? (the same is true for Windows Firewall).

**Comment by petemere** [comment]
Hi @jmcphers ,
Thanks for the insight.  I'll check in with the IT team and see what might be going on.  Seems odd that something from the work network would forcibly intervene between two applications on my laptop talking to each other - but that's not exactly my area.

@ronblum thanks for adding the labels.  Unfortunately due to the way this issue happens a normal repro is not possible.  However, if we do discover what is causing the issue form my work network I'll post the details here.

**Comment by jmcphers** [comment]
It's not unusual for software to insist on getting between all HTTP connections on the machine, even those both originating and terminating on the machine itself. Since we can't inspect your machine's configuration we can't offer much more in the way of advice here. If your IT department can point to something specifically problematic in RStudio's use of network facilities we could probably investigate further.

**Comment by petemere** [comment]
Hi @jmcphers,
Your initial response seems to have been on the money; the issue appears to be with the company proxy.

In case it is useful for anyone else having a similar problem, we managed to diagnose the problem by turning off the "Use automatic configuration script" tick-box in IE (Internet Options -> Connections -> LAN settings) and then checking to see if the RStudio delay was still there.  It wasn't.

The resolution is (as you suggested) to add exceptions for the two exe files.  Unfortunately, that's going to take a while, but that's nothing you can help with.

Thanks again,

Pete
