### ISSUE TITLE
Pressing backspace with Ubuntu hides lines on the editor

### ISSUE THREAD

**Issue by statnmap** [rstudio/rstudio#5977]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.723
    OS Version      :  Ubuntu 18.04 and Ubuntu 19.10
    R Version       :  3.6

### Steps to reproduce the problem

- Open Rmd file
- Write some text and hit backspace
- Some line sometimes disappear. The interface is partially unusable

### Describe the problem in detail

I can not reproduce this behavior with a specific protocol. It just appears sometimes when I hit backspace.  
I am aware of issue https://github.com/rstudio/rstudio/issues/4064 , but this one is different. It is not deleting lines of text, it renders part of the interface unusable.  
On the screenshot below, you can see that there is no lines after line 222, the UI is hidden.
![rstudio-dark-lines-with-backspace](https://user-images.githubusercontent.com/21193866/71968483-50338380-3205-11ea-8db2-e85a7f5b40aa.png)  
This behaviour only applies to the Rmd currently opened. This does not apply to the others Rmd in the same Rstudio session. If I close and re-open this Rmd file, the problem disappears.  
If I continue to work and hit backspace again, this may arise a second time on the same file, with three more lines disappearing.  

I do not know what triggers this. I know this won't be easy for you to debug if not reproducible, but if other users face the same problem, maybe we can find its origin.

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@statnmap Thank you for raising the issue! Did this issue occur in RStudio Desktop 1.2 (the latest is 1.2.5033)? Or is this only in 1.3?

**Comment by statnmap** [comment]
This appeared in the stable 1.2 too.  
I have been trying the dailies since beginning of last year to see if the problem disappears.

**Comment by statnmap** [comment]
This is still present in 1.4 although I still do not know how to reproduce it exactly. But this arises frequently.

**Comment by antuki** [comment]
I have the same issue on windows with the newest version of RStudio.

**Comment by statnmap** [comment]
This is still happening in RStudio 2022.01.0 Build 203
