### ISSUE TITLE
Un-minimizing RStudio indents text in source editor

### ISSUE THREAD

**Issue by Heke0** [rstudio/rstudio#5978]
When I un-minimize RStudio after minimizing it, RStudio adds an extra indentation at the cursor.
Seems to work similarly to pressing tab would: text is indented only when cursor is at the beginning of line or there is text selected.

Happens at least on Kubuntu 18.04 LTS, does not happen on windows. Doesn't seem to happen in any other program I tried.
RStudio version: 1.2.1335

**Comment by ronblum** [comment]
@Heke0 Thank you for raising the issue!  I'm unable to reproduce this on Ubuntu 18.04 using Gnome or Kubuntu 18.04 using KDE Plasma 5.12.9. Which desktop environment are you using, and can you provide a simple example of text for which this occurs?

Also, there is a more recent version of RStudio Deskop, currently 1.2.5033, at https://rstudio.com/products/rstudio/download/#download .

**Comment by kevinushey** [comment]
Also, in case it's relevant, how exactly are you minimizing and un-minimizing RStudio?

**Comment by Heke0** [comment]
Environment is KDE Plasma 5.12.9  and in case it matters we use the linux machines via NoMachine remote desktop.

The text doesn't seem to matter, this happens even for a fresh script file outside a project.
Just start a new script, write anything, move the text cursor to the beginning of the row and minimize an then un-minimize RStudio.

For minimizing I click either the minimize button in top right corner of the window or the window title in the bar at the bottom of screen (KDE's task manager panel). I maximize by clicking the title in that same panel.

I cannot test the new version of RStudio at the moment since these are my work machines and updates are managed centrally. I'll close this if it's been fixed in the newest version, once we update to it ourselves.
