### ISSUE TITLE
Table width / vertical alignment broken on data.frame with non-ASCII characters

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#5992]
```
x = data.frame(
  中文 = c("你好！", "你说什么？", "你做了什么？", "我会做。", "你想我了？", "他们会做。", "他们在说什么？", "你会做吗？", "你做什么工作？", "她做什么工作？"),
  sound_file = c("tmp1cctcn.mp3", "tmp4tzxbu.mp3", "333012.mp3", "G009-03.mp3", "334429.mp3", "G009-05.mp3", "tmpxth4o3.mp3", "R009-07.mp3", "R020-01.mp3", "R020-02.mp3"),
  media_id = c("7293", "1884", "7596", "7018", "6485", "1643", "4617", "6624", "4720", "7201")
)
print(x)
#               中文    sound_file media_id
#  1:         你好！ tmp1cctcn.mp3     7293
#  2:     你说什么？ tmp4tzxbu.mp3     1884
#  3:   你做了什么？    333012.mp3     7596
#  4:       我会做。   G009-03.mp3     7018
#  5:     你想我了？    334429.mp3     6485
#  6:     他们会做。   G009-05.mp3     1643
#  7: 他们在说什么？ tmpxth4o3.mp3     4617
#  8:     你会做吗？   R009-07.mp3     6624
#  9: 你做什么工作？   R020-01.mp3     4720
# 10: 她做什么工作？   R020-02.mp3     7201
```

Attaching a screen shot since it may depend on the display:

![Screenshot 2020-01-10 at 2 39 09 PM](https://user-images.githubusercontent.com/7606389/72131375-fe325f80-33b6-11ea-903c-4b6ba2d9f119.png)

Vertical alignment is all out of whack.

This does not happen in the terminal:

![Screenshot 2020-01-10 at 2 45 29 PM](https://user-images.githubusercontent.com/7606389/72131660-df809880-33b7-11ea-87b3-667882377284.png)

I just tried this on the latest daily build (1.3.730). Other system info:

<details>
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.9

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    packrat_0.5.0 
</details>

**Comment by ronblum** [comment]
@MichaelChirico Thank you for raising this! I can reproduce the issue in RStudio 1.2.5033 on MacOS 10.15,  as well as the expected behavior in R in the terminal. However, the same problem also occurs in the R application. Nonetheless, I'll leave this open for review in case there's something we can do.

<img width="667" alt="r_app_non_ascii" src="https://user-images.githubusercontent.com/31009952/72170660-40e83d80-339f-11ea-888a-f039b390b5f2.png">

**Comment by MichaelChirico** [comment]
OK great, I didn't think to check in the GUI. Have filed this with R-core:

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17697

**Comment by MichaelChirico** [comment]
@ronblum R-core bug updated. As noted, it's a problem of fonts; indeed, in RStudio, I can change to `Osaka-Mono` font and the issue goes away.

I'm not sure how you want to proceed -- I'm not sure this warrants changing the default fixed-width font on Mac (maybe it's sys-locale dependent?), or if there's any way to alert the user to this issue that's not overly intrusive to the many users who would never notice this... I leave it to you 😄
