### ISSUE TITLE
Feature request:  disable insertion of breakpoints on single mouse click

### ISSUE THREAD

**Issue by bmattsson** [rstudio/rstudio#5993]
When using RStudio I often highlight particular lines of code and run those individually.  The problem is that if the mouse click happens to fall too far to the left, an unwanted breakpoint is created and then I must click it again to remove it.

Please add a menu option to disable the creation of breakpoints via mouse click or require a double-click for creating a breakpoint in the margin.

**Comment by ronblum** [comment]
@bmattsson Thank you for the suggestion—we'll review it as we continue development of RStudio.
