### ISSUE TITLE
Dark themes ThemeInfo() ... $dark == FALSE

### ISSUE THREAD

**Issue by gwd999** [rstudio/rstudio#6000]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5033
    OS Version      :  WINDOWS 10 Pro 64bit 
    R Version       :  R-3.5.3 and R-3.6.2

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Steps to reproduce the problem 
After selecting/activating a dark theme in RStudio eg "Clouds Midnight" `getThemeInfo()` returns the following: 

````
rstudioapi::getThemeInfo()

$editor
[1] "Clouds Midnight"'

$global
[1] "Modern"

$dark
[1] FALSE

$foreground
[1] "rgb(146, 146, 146)"

$background
[1] "rgb(25, 25, 25)"
````

### Describe the problem in detail
Updating RStudio to 1.2.5033 has brought up the issue/bug #4850 (and #4914)- dark themes show `THEME$isDark == FALSE` or `getThemeInfo()` `$dark == FALSE` [again?]. 

### Describe the behavior you expected
On my second laptop with RStudio 1.2.5001 (same specs regarding OS etc) DARK themes show as TRUE ie correctly and so the fonts are readable in the dark themes. 
I have the same ~/.Renviron file in place on both machines (pls find it attached), which set the LC_ variables equal to "C", in order to cope with the common 'Failed to set LC_' warnings/messages. 
So imho mofifying the LOCALE env vars does not seem to fix this issue, at least for me, as is mentioned in some comments to #4850. 

[Renviron.txt](https://github.com/rstudio/rstudio/files/4050025/Renviron.txt)

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3  tools_3.5.3     rstudioapi_0.10 fortunes_1.5-4 
```
I have attached a rsession.log which shows some interesting messages ... 
Example: 
11 Jan 2020 20:44:06 [rsession-user] WARNING rs-theme-is-dark value is not a valid boolean string for theme "Solarized Dark".; LOGGED FROM: void __cdecl rstudio::session::modules::themes::`anonymous-namespace'::getThemesInLocation(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::tuple<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool>,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::tuple<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool> > > > *) C:\jenkins\workspace\IDE\windows-v1.2\src\cpp\session\modules\SessionThemes.cpp:185

[rsession-user.log](https://github.com/rstudio/rstudio/files/4049992/rsession-user.log)

**Comment by ronblum** [comment]
@gwd999 Thank you for raising this issue. Have you tried the investigation steps in #4850?

- Checking the JavaScript code: https://github.com/rstudio/rstudio/issues/4850#issuecomment-496317118
- Running `rstudioapi::getThemes()`

**Comment by gwd999** [comment]
@ronblum - will come back w requested info in approx. (3-4) hours

**Comment by gwd999** [comment]
> 
> 
> @gwd999 Thank you for raising this issue. Have you tried the investigation steps in #4850?
> 
>     * Checking the JavaScript code: [#4850 (comment)](https://github.com/rstudio/rstudio/issues/4850#issuecomment-496317118)
> 
>     * Running `rstudioapi::getThemes()`

pls see https://github.com/rstudio/rstudio/issues/6000#issuecomment-574191618

**Comment by gwd999** [comment]
Ok - here is the answer ie the problem solution ...at least on my machine 
After "investing" two evenings on this I have come to the conclusion that at least in my case this was/is based on the Language settings (99% assured) during the Rswitching the DARK Themes at coudl also be during the installation process itself I did not further investigate that issue. 
I was able to reproduce the behaviour via "pure" Language setting switching before doing DARK Theme changes in Studio as well. 
Changed Language settings of eg the SOLARIZED DARK theme produce a "civilized" dark themes again - ie no longer unreadable dark blue font on black background (when using Modern or Sky RStudio Themes).  

Here is what I did to the Language settings before reinstalling - I switched from English (Austria) to English (United States) - pay attention to the "arrow(s)" - this is the changed setting with which theme switching functions: 
![Language_Settings_Switch](https://user-images.githubusercontent.com/306826/73305229-f7f70c80-4219-11ea-9bf1-e62cb00aa013.PNG)

It seems that this solves the problem without needing a full re-install of RStudio - but I can no longer or do not want to invest the time to cross-check that solution. 

Now the result looks like this (again): 
![Working_Solarized_Dark](https://user-images.githubusercontent.com/306826/73304883-625b7d00-4219-11ea-90d8-9a0d5e4f092e.PNG)

Nice!
One should maybe mention that after reinstalling with the "functioning" Language settings and switching to (SOLARIZED) DARK theme for the first time I received the message that RStudio needs to be restarted for changes to take effect (as if I had changed R Versions) 
PLUS - the session terminated and restarted -> see here: 
![Change_Locale_Session_terminated_after_Switch_to_Solarized_Dark](https://user-images.githubusercontent.com/306826/73305718-fc6ff500-421a-11ea-8c78-ba32fbebec3a.PNG)

So finally here is the side-by-side comparison of SOLARIZED DARK one with good and one with BAD Language settings (during) install or switching the THEME! 
On the LEFT side I have also run `Sys.getlocale()` so you can see the "BAD" LOCALE settings that cause this behavior after THEME switching. 
![Side_By_Side_installs_Solarized_Dark](https://user-images.githubusercontent.com/306826/73305817-33dea180-421b-11ea-8e0e-2a8a8ad7f13d.PNG)

My GUESS is that RStudio will need to investigate a bit into interaction of theme switching and Locale/Language settings on Windows. 
I also hope this helps others in the same issue -> therefore I will leave this issue open as long as there is no fix to this settings combination. 

Greetings

**Comment by ronblum** [comment]
@gwd999 Thank you for your investigation and data!
@MariaSemple Do you have any thoughts on why changing language would cause the above?

**Comment by MariaSemple** [comment]
Unfortunately, I wasn't able to reproduce this issue. I tried changing the default app language to English (Austria) as well as the Windows Display Language. @gwd999, is it always occurring for you when the default app language and Windows Display Language are English (Austria)?

**Comment by gwd999** [comment]
@MariaSemple - Hi Maria, very weird awkward situation. I can also no longer reproduce this behavior/bug. Meaning if I just repeat the above steps that I documented above with the various screenshots, the readability problem (caused by not identifying the darkTheme) is no longer present. Looks like some sort of "Ghosts in the machine"  ...  which is interesting because a couple of days ago I was able to reproduce and fix this bug with the procedure described above. But I am glad it's possible to switch to my English (Austrian) Language settings now without having to worry about this issue. Thanks (also @ronblum ) for looking into this - and your assistance.

**Comment by gwd999** [comment]
So I will be a good sport and close this issue ...

**Comment by gwd999** [comment]
@MariaSemple: hmmm ... I did just happen to notice one thing though - when I currently switch language settings RStudio displays "C" as the result of `Sys.getlocale()` AND NOT "LC_COLLATE=English_Austria_65001; ..." as in the screenshot above! @MariaSemple => can u potentially check your output when fetching the locale as well - I still need to find out how I can make RStudio pick up that "ugly" Locale, but my guess is that this could bring that bug back to life?

**Comment by gwd999** [comment]
Closing this issue for now ...
