### ISSUE TITLE
save file error message

### ISSUE THREAD

**Issue by mhjoe** [rstudio/rstudio#6001]
This error massage

![캡처](https://user-images.githubusercontent.com/31664366/72216283-72f5cd00-3562-11ea-80c5-0c39b8695b49.JPG)

poped up continuously while I type codes.

When I click 'OK', nothing change but after I make a few code lines, It appear again.

How can I fix it?

**Comment by ronblum** [comment]
@mhjoe Thank you for raising the issue. Can you please provide the following information so that we can try to reproduce the issue:

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

Also, are you saving the file locally or over a network/shared drive?

**Comment by mhjoe** [comment]
RStudio Edition : Unknown
RStudio Version : 1.2.5033
OS Version      : Win10
R Version       : 3.5.0

I saved file over cloud network(Dropbox)



--------------------------------------------------------------

*조민혁 ｜ Min hyuk** Cho*

성균관대 국정전문대학원 박사과정 ｜
doctoral student, Graduate School of Governance, Sungkyunkwan University
성균관대 국정평가연구소 연구원｜
Research Fellow, Institute of Governance and Policy Evaluation

Office: 82-2-760-0407 / Mobile: 82-10-6757-5057
e-mail: cmh5057@gmail.com <joojy7120@gmail.com>


2020년 1월 13일 (월) 오후 11:24, Ron Blum <notifications@github.com>님이 작성:

**Comment by ronblum** [comment]
Is it possible to save a file locally and see if that makes a difference? We've seen issues in the past with saving on a network .

**Comment by jmcphers** [comment]
We haven't heard back in a few months so closing.
