### ISSUE TITLE
RStudio Server 1.2.5033: Does no longer work with libssl.so.1.0 (Only with libssl.so.1.1)

### ISSUE THREAD

**Issue by jtelleriar** [rstudio/rstudio#6006]
### System details

    RStudio Edition : RStudio Server
    RStudio Version : rstudio-server-rhel-1.2.5033
    OS Version      :  Amazon Linux AMI release 2018.03
    R Version       : R 3.6.2

```
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: AmazonAMI
Description:    Amazon Linux AMI release 2018.03
Release:        2018.03
Codename:       n/a

```

### Describe the problem in detail

RStudio Server Version 1.2.5033 cannot be launched with libssl.so.1.0 (Only with libssl.so.1.1)

### Describe the behavior you expected

Is it due to a configuration from my cluster? Or something has changed in the latest version of RStudio Server?

Thanks!

**Comment by jmcphers** [comment]
Please download the binary appropriate for your platform; we supply versions for both libssl1.0 and libssl1.1. If you're unsure, our community forum is the place to ask:

https://community.rstudio.com/c/rstudio-ide
