### ISSUE TITLE
Add progress bar for git push

### ISSUE THREAD

**Issue by JamieCranston** [rstudio/rstudio#6012]
Would it be possible for a progress bar to be displayed when pushing to a remote repository? Along the top where the tracker currently just pans left to right. 

Thanks!

![image](https://user-images.githubusercontent.com/36704853/72358253-2934f000-36e4-11ea-8bbd-aedf2af75996.png)

**Comment by ronblum** [comment]
@JamieCranston Thank you for the suggestion! We'll review it as part of our ongoing development of RStudio.
