### ISSUE TITLE
RStudio IDE fails to load after restarting rstudio-server

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#6018]
### System details

    RStudio Edition : Server Open Source
    RStudio Version : 1.3.740
    OS Version      : Ubuntu 18
    R Version       : 3.4.4

### Steps to reproduce the problem
1. have rstudio server running and log in as a user on a browser
2. on the server, run "rstudio-server restart"
3. refresh the browser page

### Describe the problem in detail
an error pops up and the IDE fails to load
<img width="761" alt="Screen Shot 2020-01-14 at 3 42 58 PM" src="https://user-images.githubusercontent.com/43964690/72387101-5e434180-36e8-11ea-86ce-114fbc9c3357.png">

error in logs
"ERROR system error 13 (Permission denied) [path: /var/run/rstudio-server/rstudio-rsession/rich5-d, user-id: 1003, stream-user-id: 999, request-uri: /rpc/client_init]; OCCURRED AT virtual void rstudio::core::http::LocalStreamAsyncClient::connectAndWriteRequest() src/cpp/server/ServerSessionProxy.cpp:77; LOGGED FROM: void rstudio::server::session_proxy::{anonymous}::logIfNotConnectionTerminated(const rstudio::core::Error&, const rstudio::core::http::Request&) src/cpp/server/ServerSessionProxy.cpp:382"

### Describe the behavior you expected
user is able to refresh the page and IDE is displayed

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
This was caused by my changes in: https://github.com/rstudio/rstudio-pro/pull/1356
