### ISSUE TITLE
Debugger keybindings

### ISSUE THREAD

**Issue by joeflack4** [rstudio/rstudio#6019]
## Feature request
I would like to request the following feature:

**Keybindings for debugger options**

## Additional information
I've searched for an existing issue. I was sure there was one, but I could not find.

Here's a screenshot of the buttons I'd like to keybind.

![Uploading Screen Shot 2020-01-14 at 5.17.15 PM.png…]()

**Comment by gtritchie** [comment]
The screenshot isn't showing, maybe it didn't upload correctly?

**Comment by jmcphers** [comment]
Superseded by https://github.com/rstudio/rstudio/issues/6020.
