### ISSUE TITLE
Debugger keybindings

### ISSUE THREAD

**Issue by joeflack4** [rstudio/rstudio#6020]
## Feature request
I would like to request the following feature:

**Keybindings for debugger options**

## Additional information
I've searched for an existing issue. I was sure there was one, but I could not find.

Here's a screenshot of the buttons I'd like to keybind.

<img width="341" alt="Screen Shot 2020-01-14 at 5 17 15 PM" src="https://user-images.githubusercontent.com/13045020/72387601-e1b56080-36f1-11ea-98de-81e6b0fb6172.png">

**Comment by jmcphers** [comment]
This is fixed in https://github.com/rstudio/rstudio/pull/5682.
