### ISSUE TITLE
Bad JSON in user preferences file results in an unusable session with no easy recovery

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6023]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.730
    OS Version      : MacOS 10.15.3 and Red Hat 7.7
    R Version       : 3.6

### Steps to reproduce the problem

1. Back up `rstudio-prefs.json`
2. Help -> Diagnostics -> Edit User Prefs File
3. Edit the contents with bad JSON, for example removing some commas and semicolons, and save
4. Close RStudio
5. Reopen RStudio Desktop or open a new session in RStudio Server
    - RStudio will fail to open
6. To return to the previous state, copy the backup file to `rstudio-prefs.json`

### Describe the problem in detail

If a user edits the user preferences file, `rstudio-prefs.json`, and the resulting code is invalid, RStudio ends up in an unusable state without an obvious way for the user to recover. 

- RStudio Desktop can be made to work again by deleting `rstudio-prefs.json`, although the user preferences will revert to the default values.
- RStudio Server can’t be reset by the user, since they can’t past the error message. If they have access to the file system, they can remove `rstudio-prefs.json` . Otherwise, they'll need the administrator to do so to restore the default state.

### Describe the behavior you expected

Possible solution: If the file contains an error, open a pop-up with an error message letting them know there was a problem, and then revert to factory settings.

RStudio Server when file has errors:
<img width="408" alt="json_server" src="https://user-images.githubusercontent.com/31009952/72457645-14646500-3795-11ea-984e-764aedaf3824.png">

RStudio Desktop when file has errors:
<img width="1207" alt="json_desktop" src="https://user-images.githubusercontent.com/31009952/72457660-1cbca000-3795-11ea-962b-4930b4f1915e.png">

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is important to fix, but it won't happen unless the file gets corrupted somehow and there's no mechanism that causes that to happen as far as I can tell (aside from intentional malice) so doesn't need to be fixed for the preview.

**Comment by ronblum** [comment]
So far it's only been my own intentional malice. Also, for what it's worth, RStudio Desktop starts up nicely in a default state if the file can't be read at all, e.g. by removing read permissions from the file with `chmod 333 rstudio-prefs.json`.

**Comment by jmcphers** [comment]
There's a secondary problem here, which is that you should have gotten a nice startup failure diagnosis page instead of those incomprehensible popups. I think that there's a good chance that my change https://github.com/rstudio/rstudio/pull/5509 doesn't actually work in release builds (just dev builds). I'll try to fix that at the same time.

**Comment by ronblum** [comment]
That makes sense—build 1.3.489 results in the "can't connect to server" page, but by build 1.3.546 we get the current behavior.

**Comment by ronblum** [comment]
@jmcphers RStudio starts up fine, but with no error message. Is this the expected behavior?

**Comment by jmcphers** [comment]
Yep, if you destroy your preferences we'll just leave you with defaults. You'll find a parse error in your logs.

**Comment by ronblum** [comment]
Great! Then it works.
