### ISSUE TITLE
Visual layout issue with Subversion history window

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6031]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1, 1.2, 1.3
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
Open a project which uses Subversion, and view the project history.

### Describe the problem in detail
The "Discard All" button is barely visible (a tiny bit of it is peeking up below the Context dropdown, but only way to reach it is via Tab key, which will cause it to scroll into view.

<img width="191" alt="2020-01-15_17-31-30" src="https://user-images.githubusercontent.com/10569626/72485748-96688400-37bd-11ea-812a-928a7f03710c.png">

### Describe the behavior you expected
Should look like it did in RStudio 1.0:

<img width="260" alt="2020-01-15_17-34-53" src="https://user-images.githubusercontent.com/10569626/72485756-9bc5ce80-37bd-11ea-9c96-4a2b34e43434.png">

**Comment by melissa-barca** [comment]
Verified in 1.4.954
