### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by marciz** [rstudio/rstudio#6035]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5036
    OS Version      :  Windows 10 1903
    R Version       :  3.6.1

### Steps to reproduce the problem
```
library(RSQLite)
con <- dbConnect(RSQLite::SQLite(), ':memory:')
x <- data.frame(varName = c(
  rep('aaaaa_a', 3),
  rep('yyyyy_y', 2),
  rep('qqqqq_q', 8),
  rep('xx_xxx_xxxx_xxx', 51158),
  rep('zzzzz_z', 40)
), stringsAsFactors = F)
dbWriteTable(con, 'x', x, overwrite = TRUE)
dbWriteTable(con, 'y', head(x, nrow(x)-1), overwrite = TRUE)
dbWriteTable(con, 'z', tail(x, nrow(x)-1), overwrite = TRUE)
dbGetQuery(con, "SELECT varName FROM x", n = 1)
# ok
dbGetQuery(con, "SELECT varName FROM x GROUP BY varName", n = 1)
# Error: unable to open database file
dbGetQuery(con, "SELECT varName FROM y GROUP BY varName", n = 1)
# ok
dbGetQuery(con, "SELECT varName FROM z GROUP BY varName", n = 1)
# ok
dbDisconnect(con)
```

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18362)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Latvian_Latvia.1257  LC_CTYPE=Latvian_Latvia.1257    LC_MONETARY=Latvian_Latvia.1257
> [4] LC_NUMERIC=C                    LC_TIME=Latvian_Latvia.1257    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] RSQLite_2.2.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.3      digest_0.6.23   zeallot_0.1.0   crayon_1.3.4    DBI_1.1.0       backports_1.1.5
>  [7] pillar_1.4.3    rlang_0.4.2     rstudioapi_0.10 blob_1.2.0      vctrs_0.2.1     tools_3.6.1    
> [13] bit64_0.9-7     bit_1.1-15.1    compiler_3.6.1  pkgconfig_2.0.3 memoise_1.1.0   tibble_2.1.3

### Describe the problem in detail
No error on RGui and 1.2.5033 (Ubuntu)
Also there is no error if change slightly `x` data.frame

### Describe the behavior you expected

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@marciz Thank you for raising this issue. You mention that this works in the RGUi on Ubuntu. What about on Windows?

**Comment by marciz** [comment]
RGui is on Windows, the same platform as Rstudio 1.2.5036

**Comment by jmcphers** [comment]
I could not repro this on 1.3 on macOS.

**Comment by marciz** [comment]
No issue on 1.3 and Win
