### ISSUE TITLE
Bug typo HOSTED SERVICES Be our guest, be our guest

### ISSUE THREAD

**Issue by brunocarlin** [rstudio/rstudio#6037]
As you can see there may be a typo in the webpage https://rstudio.com/

Under Products > Hosted Services

Right one: Be our guest

Current one: Be our guest, be our guest

**Comment by jmcphers** [comment]
It is intentional! It's a reference to the song _Be our guest, be our guest_ from _Beauty and the Beast_.

https://www.youtube.com/watch?v=afzmwAKUppU
