### ISSUE TITLE
Improve speed of console when it contains a lot of output

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6042]
## Repro

1. Create a new R session
2. Execute a command that creates lots of R console output, several times. 
3. Attempt to execute a command in the R console

## Problem

As the R console output grows, the console gets progressively more sluggish (and the rest of the UI can too). There's lag between pressing a key and seeing a letter appear, and between pressing Enter and having the command submit. 

This happens because the number of DOM elements grows unbounded, and the browser struggles with layouts/reflows as a result. 

We currently cap the number of lines in the console history to 1000 to help mitigate this effect, but that's an undesirable solution long-term:

- 1000 lines is not enough to capture long script outputs (arguably those should be captured with `sink()` but that's very sophisticated for some users)
- 1000 lines is--simultaneously--too many for some machines to handle; in recent versions of Chrome this seems to have gotten worse. 

We made it possible for users to adjust this themselves in https://github.com/rstudio/rstudio/pull/5919, which provides some limited mitigation for the users experiencing the most pain, but the best solution here is probably to virtualize the console contents, perhaps using Ace or similar, so that we don't have to manage the whole thing in the DOM. 

## Note

In RStudio 1.3 it is possible to mitigate this with an option, so make sure it's disabled:

```r
rstudioapi::writeRStudioPreference("console_line_length_limit", 2000L)
```

(requires a restart of the session and browser reload)

Internal support tickets: 43250, 43320, 43158, 43233

**Comment by rmccombie** [comment]
Additional internal support ticket: https://rstudioide.zendesk.com/agent/tickets/44727

**Comment by kevinushey** [comment]
I'm still seeing code cut off in unexpected ways with this feature on:

<img width="521" alt="Screen Shot 2020-10-15 at 3 38 24 PM" src="https://user-images.githubusercontent.com/1976582/96193191-8290b080-0efc-11eb-88cd-fdbce6a2304d.png">

It seems like, after a particular piece of console input, we're only retaining the last 1000 lines of output.

**Comment by kevinushey** [comment]
After reloading the UI (Right click -> Reload), I see after trying to scroll back to the top:

<img width="576" alt="Screen Shot 2020-10-15 at 3 42 14 PM" src="https://user-images.githubusercontent.com/1976582/96193474-16627c80-0efd-11eb-8444-b07b0057cd6c.png">

So it seems like the console history is then truncated in the "regular" way.

**Comment by gtritchie** [comment]
@kevinushey Want to add your findings to #7918

Seems like essentially the same problem?

**Comment by kevinushey** [comment]
Thanks! I've done so.

**Comment by kfeinauer** [comment]
Verified that the performance issue seems to have gone away with this change. Tested with latest dailies. Aside from the strangeness reported in #7918.

**Comment by rmccombie** [comment]
Is there a preview release I can suggest in 44727?

**Comment by adamconroy** [comment]
There is an outstanding bug (#8428) that may or may not be a blocker for the customer. I'm actively working on the fix but it's not ready yet. If they get latest, by default, the new feature that limits console output will be turned on.
