### ISSUE TITLE
auto-complete does not work for read.table when using a multi-line input

### ISSUE THREAD

**Issue by romunov** [rstudio/rstudio#6044]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.3.719
    OS Version      : Fedora 30
    R Version       : 3.6.2

### Steps to reproduce the problem
Enter a mult-line value into `read.table`.

```
read.table(text = "a b c
           1 2 3")
```

### Describe the problem in detail
When trying to complete argument name (CTRL+Space), no suggestions come up. I.e. try completing `stringsAsFactors`:

![Screenshot from 2020-01-17 11-05-45](https://user-images.githubusercontent.com/544571/72603745-e65c5d80-3919-11ea-86b8-0fcc151c94e5.png)

### Describe the behavior you expected

I would expect Rstudio to offer me a list of arguments to choose from. This happens if I type in a new line.

![Screenshot from 2020-01-17 11-10-55](https://user-images.githubusercontent.com/544571/72603825-0db32a80-391a-11ea-955f-a86e3bca06e2.png)

And works for single-line:

![Screenshot from 2020-01-17 11-15-03](https://user-images.githubusercontent.com/544571/72604166-a9dd3180-391a-11ea-9c59-b9f138b9e541.png)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@romunov Thank you for raising the issue! We'll review it as we continue development of RStudio.
