### ISSUE TITLE
New custom dictionary doesn't persist until RStudio is restarted or a new session is created

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6045]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.743 & 1.3.730
    OS Version      : MacOS 10.15.3 & Red Hat 7.8
    R Version       : 3.6.1 & 3.6.0

### Steps to reproduce the problem

1. Download a custom dictionary, such as the English medical terms en_med_glut.dic file at https://github.com/glutanimate/hunspell-en-med-glut
2. In IDE: Tools -> Global Options -> Spelling -> Add
3. Choose the new dictionary and click on “Open”
    - The new dictionary should show up in the list, e.g. en_med_glut 
4. Click on “OK"
5. Tools -> Global Options -> Spelling 
    - The dictionary is no longer in the list
6. Click on “Cancel”
7. Close and Restart RStudio Desktop or open a new session in RStudio Server
9. Tools -> Global Options -> Spelling 
    - The dictionary is listed

### Describe the problem in detail

The new dictionary isn’t listed under Global Options until RStudio Desktop is restarted or a new session is created in RStudio Server.

### Describe the behavior you expected

The dictionary should be available without having to restart RStudio or creating a new session.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rich-rstudio** [comment]
verified on 1.3.888
