### ISSUE TITLE
Custom dictionaries are being ignored by spellcheck

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6047]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.743
    OS Version      : MacOS 10.15.3
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Download a custom dictionary of English medical terms, the file `en_med_glut.dic` at https://github.com/glutanimate/hunspell-en-med-glut
2. In IDE: Tools -> Global Options -> Spelling -> Add
3. Choose the new dictionary and click on “Open”
4. Click on “OK"
5. Close and Restart RStudio Desktop or open a new session in RStudio Server (see #6045)
6. Tools -> Global Options -> Spelling 
    - Make sure that the dictionary is listed
7. In a new Rmd file, enter the following. text
```
allegra
Allegra
zyrtec
Zyrtec
fexofenadine
Fexofenadine
alleni
Alleni
latuda
Latuda
```
8. Save the file

Note: The example includes various capitalizations to make sure that’s not a factor.  

### Describe the problem in detail

Spellcheck results:
- _Allegra_ and _Zyrtec_ (capitalized) are identified as spelled correctly, but they’re also in the en_US dictionary.
- The rest of the terms are in the custom medical dictionary (though capitalization may differ), but they’re being labelled as misspelled.
- Right-clicking on the “misspelled” words only suggests words in English, if at all. For example, _alleni_ results in words such as _fallen_ and _alien_ as alternatives.

Similar behavior occurs when running spellcheck with Edit -> Check Spelling.

### Describe the behavior you expected

All terms in the custom dictionary should be marked as spelled correctly.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: this appears to be a problem in 1.2.5033 with Edit -> Check Spelling. Either this is an existing issue or I'm not using the custom dictionary correctly.

**Comment by rich-rstudio** [comment]
@adamconroy I get an error when trying to reproduce this on MacOS desktop Version 1.3.897. The custom dictionary is added but when I click the spellcheck button I get the error `Class$S314: (TypeError) : Cannot read property 'check' of undefined`
<img width="875" alt="Screen Shot 2020-03-11 at 10 05 53 AM" src="https://user-images.githubusercontent.com/43964690/76431814-1ce5b000-6380-11ea-99ce-502d2eb1c149.png">

**Comment by adamconroy** [comment]
@rich-rstudio looking into this now, can you confirm that you're getting any other errors in the inspect control panel when the app loads up? im getting an error loading the .aff file which would explain some things (though that file is normally optional) but no popup message like you're getting.

**Comment by adamconroy** [comment]
Also Rich I just added a potential fix. You could test it yourself by making an empty `.aff` file that lives in the same folder as the custom dictionary with the same name. So something like `en-us-med.aff` if the dictionary name is `en-us-med.dic`

**Comment by rich-rstudio** [comment]
chatted with @adamconroy , verified fixed
