### ISSUE TITLE
New project with renv in a new session impacts the original session

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#6053]
### System details

    RStudio Edition : RStudio Desktop Pro
    RStudio Version : 1.3.753-1
    OS Version      : MacOS 10.15.2
    R Version       : 3.6.2

### Steps to reproduce the problem
Open the New Project dialogue
Select to use `renv` and open the project in a new session
The library paths for the initial session are overwritten as the new project is opened

![renv-new-project](https://user-images.githubusercontent.com/10444878/72659742-c3659400-3981-11ea-8f5f-289ce24e4ac8.gif)

### Describe the problem in detail
When a new `renv` project is initialized in a new session from RStudio, the original R session inherits the `renv` library path of the new project.

### Describe the behavior you expected
The library paths of the original project should remain unchanged.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by blairj09** [comment]
Circling back to this. This issue is particularly troublesome with my current workflow:

I often have multiple RStudio projects open at a time. I frequently work with `renv` projects while keeping my global library up to date by regularly updating packages. If I'm not careful, updating packages in a non-`renv` project will unexpectedly update packages in some other `renv` project that I have activated. This has bitten me more than once 😞

**Comment by kevinushey** [comment]
I think this implies that RStudio should try to execute `renv::init()` in a separate sub-process.

**Comment by blairj09** [comment]
It seems like this issue is resolved (at least in RStudio Desktop Pro 1.4.1586-1). If I notice it again I'll try to re-open this issue.
