### ISSUE TITLE
JetBrains mono not listed in fonts

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rstudio#6059]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      :  elementary OS 5.1 Hera (Built on Ubuntu 18.04.3 LTS)
    R Version       :  3.6.2 

### Steps to reproduce the problem

Install [JetBrains mono](https://blog.jetbrains.com/blog/2020/01/15/jetbrains-mono-a-new-font-made-for-developers/). 
Open Global Options -> Appearance 

### Describe the problem in detail

JetBrains Mono is not listed among the available fonts. 

### Describe the behavior you expected

JetBrains Mono should be listed among the available fonts. 

### Some detail

[This comment](https://blog.jetbrains.com/blog/2020/01/15/jetbrains-mono-a-new-font-made-for-developers/#comment-337612) seems to point in the direction of the issue 

> On Ubuntu, fc-cache detect JetBrains Mono as a dual-width font, not monospace font.
> 
> RStudio, an IDE based on Qt, does not allow choosing non-monospaced fonts, and as such I cannot set JetBrains Mono to be my font in RStudio.

As the commenter says, there are multiple places where this issue could be resolved and it'd be understandable if it wasn't an issue with Rstudio. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Thanks for reporting this! Unfortunately this issue is indeed upstream -- RStudio doesn't attempt to determine whether fonts are monospace or not.

**Comment by eliocamp** [comment]
Thanks! The issue is fixed in the 1.0.2 version of the font.
