### ISSUE TITLE
During session ability to highlight words in source by double clicking disappears

### ISSUE THREAD

**Issue by majazaloznik** [rstudio/rstudio#6063]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.5036
    OS Version      : Manjaro Linux
    R Version       : 3.6.2

(I first reported this issue on [RStudio community forum](https://community.rstudio.com/t/during-session-ability-to-highlight-words-in-source-by-double-clicking-disappears/49449) with version 1.2.5001, and upgraded to the preview version based on the recommendation there.)

### Steps to reproduce the problem
After an undetermined amount of time of using RStudio - somewhere between a few minutes and half an hour maybe. I really don't know triggers the switch, or how I might figure it out... I just notice all of a sudden that it's stopped working the way I am used to. It invariably happens sooner or later.

### Describe the problem in detail
Clicking on a word in the source pane:
* double clicking on a word does nothing.
* triple clicking highlights the whole script.

### Describe the behavior you expected
At the start of a new session I get expected behaviour in the source pane:
* double clicking on a word highlights that word (and outlines other instances of that word)
* triple clicking highlights that row.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@majazaloznik Thank you for raising the issue. Note that we don't support Manjaro; our platform support is at https://rstudio.com/about/platform-support/ . However, as this might be an issue in other Linux platforms, we'll review it in our ongoing development of RStudio.

**Comment by majazaloznik** [comment]
sure thing Ron, thanks, i'll try it out on Ubuntu when i get a chance!

**Comment by wklink** [comment]
I have this issue in Ubuntu 18 w/Rstudio 1.2.5019.

It does seem to be related to how long I've been _actively_ using it, as I've opened Rstudio and left it idle for days and it works as expected when I start using it, but after an indeterminate amount of time, the problem starts to occur.

**Comment by wklink** [comment]
One other note: the problem occurs in the editor window.  If I have a second tab opened, that one may (or may not work) as well.  Closing the tab and re-opening the file resets the select behavior (for a while).

**Comment by kevinushey** [comment]
Does this still reproduce in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by majazaloznik** [comment]
I know I'm not relevant here, by virtue of being on Manjaro, but I did try the preview version and this problem did go away, but got replaced with _very_ regular freeze-crashes, that meant I had to kill the process to restart Rstudio, so I've switched back to the regular edition (1.2.5033.1), where i still have the issue from the OP, but am more chill about it these days B)

**Comment by ArtemiyGolden** [comment]
Same issue on Ubuntu 19.10, Rstudio Version 1.2.5042 and 1.2.5019. The behavior occurs in the editor window. I am able revert the behavior of double click to word selection by the combination of multiple clicks, `alt+selecting` and pressing `Esc`, I have not established a 100% working combination yet.
