### ISSUE TITLE
[Bug] Highlighting text selection conflicts with pre-defined theme background

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#6065]
Some customized Rstudio theme (e.g. Summerfruit) would specify the background color for R script comments. However, it is not compatible with background highlighting for text selection. Ideally, text selection should overwrite the background color as pre-defined by the theme. Currently, this does not happen leading to visual difficulties to identify which texts are selected.

![cd789d6afef191e91bcab31f214a878f050911e7 jpeg](https://user-images.githubusercontent.com/11802171/72768585-b7114f00-3bac-11ea-8db0-4e4f238e8b72.jpg)

**Comment by ronblum** [comment]
@Sibojang9 Thank you for raising this—I can reproduce the issue in RStudio Desktop 1.1.799 on MacOS 10.15.1. We'll review it as we continue with development of RStudio.
