### ISSUE TITLE
Have a dedicated help page to rstudio's View() function

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#6066]
related to https://github.com/rstudio/rstudio/issues/6007

Rstudio override `utils::View` and the Rstudio version behaves differently and has different formals, still `?View` leads to the help page of `utils::View()`,

Could we have a help page consistent with the observed behavior ?

**Comment by ronblum** [comment]
@moodymudskipper Thank you for opening this followup from #6067 for us to review!
