### ISSUE TITLE
Autocomplete inconsistent with formals in `View()`

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#6067]
related to https://github.com/rstudio/rstudio/issues/6066 and https://github.com/rstudio/rstudio/issues/6007

View's autocomplete shows arguments x and title, but Rstudio's `View()` 's formal is `...`, shouldn't they be consistent ?

**Comment by ronblum** [comment]
@moodymudskipper Thank you for bringing this up. We'll review it as we continue RStudio development. And referencing the other issues is very helpful!

**Comment by jmcphers** [comment]
Autocomplete does work with RStudio's `View()`:

![image](https://user-images.githubusercontent.com/470418/106501793-68151f80-6478-11eb-9514-33178b23fd4c.png)

**Comment by moodymudskipper** [comment]
Hi @jmcphers, I acknowledged that the above worked. The issue was that x and title were not formals of `View`, the only formal was `...` at the time of my post, maybe it changed since then.
