### ISSUE TITLE
detect SQL code in string and highlight accordingly

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#6068]
Rstudio supports SQL in `.sql` scripts or in `sql` chunks of markdown reports. I would love to benefit from this highlighting R code query strings.

I think we could make it work this way : 

* detect if literal strings are valid SQL (maybe with a bit of flexibility, so we can use `{}` in glue strings)
* if they are, grey out the surrounding quotes and format the content

There might be some false positives, as someone could mean `"select option from menu"` as a regular string, so maybe we'd have to opt in through options.

Not only would it make the code prettier and more readable, but syntax issues would be obvious, just as not closing a quote makes all the code green up to the next quote, and makes it obvious something is off, forgetting a coma or using invalid syntax would make the string appear as a regular string, prompting the user to fix it before running the script.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/2232.
