### ISSUE TITLE
A special function to use relevant syntax highlighting in strings for different languages

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#6069]
I proposed [here](https://github.com/rstudio/rstudio/issues/6068) to give a special treatment to strings specifying valid SQL, but SQL is not the only language that we code through strings using R.

Maybe we could have a special Rstudio function that would display its only string argument with adequate formatting ?

We'd have `code("SELECT col FROM table", "SQL")` highlight right in the script its first argument not as a string, but as code. It would work with `python`, making working with reticulate much more enjoyable. It would work with `html` and `css`, helping a lot with shiny apps, etc.. We could even support the R language itself and make it the default, so we'd have `code("head(iris)")` highlight `head(iris)` as code.

I think the output of `code()` could be a string with a S3 class `code` and a class `code_*language*` so we have a nice printing method for those and methods can be easily defined.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/2232.
