### ISSUE TITLE
Automation - Unique identifier for Files Pane

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#6070]
Requesting a unique identifier for automation to iterate through all the files in the Files Pane. Thanks!

<img width="736" alt="Screen Shot 2020-01-21 at 2 06 58 PM" src="https://user-images.githubusercontent.com/43964690/72839169-630f7480-3c57-11ea-9fff-256763041b64.png">

**Comment by gtritchie** [comment]
You can get all files in file pane using a selector like this:

`div#rstudio_workbench_panel_files .org-rstudio-core-client-cellview-LinkColumn-Styles-link`

This gives the divs containing the filenames, such as:
```
<div class="org-rstudio-core-client-cellview-LinkColumn-Styles-link org-rstudio-core-client-theme-res-ThemeStyles-handCursor" title="selenium_test_project.Rproj">selenium_test_project.Rproj</div>
```

Let me know if this does the trick for you. If you need access to other columns in the Files pane, might need to do more work. I'll leave this open until we've chatted about it.

**Comment by rich-rstudio** [comment]
Thanks @gtritchie , ill try it out

**Comment by gtritchie** [comment]
More details. To narrow down to a specific row (0-based, where row zero is usually the "parent folder" entry. Replace "2" with the row you want to select.

`div#rstudio_workbench_panel_files tr[__gwt_row="2"]`

To get the checkbox in a given row:

`div#rstudio_workbench_panel_files tr[__gwt_row="2"] input[type="checkbox"]`

**Comment by gtritchie** [comment]
I'm going to close this, think we have a workable solution?

**Comment by rich-rstudio** [comment]
yep got everything working now, thanks @gtritchie
