### ISSUE TITLE
Realtime spellchecking is ignoring the ignore-uppercase and ignore-number options

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6074]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.743
    OS Version      : MacOS 10.15 and Red Hat 7/8
    R Version       : 3.6

### Steps to reproduce the problem

1. Tools -> Global Options -> Spelling
2. Check "Ignore words in UPPERCASE", "Ignore words with numbers", and "Use real time spellchecking,"  if they aren't already checked.
3. Paste the following into an Rmd file:
````
This is misssspeled and numberish5 and CAPITALISH

```{r cars}
# This is misssspeled and numberish5 and CAPITALISH
summary(cars)
```
````
4. Save the file, if it hasn't previously been saved.

### Describe the problem in detail

The words in upper case and with numbers are getting identified as misspelled by real time spellchecking.

<img width="467" alt="numbers_and_capitals" src="https://user-images.githubusercontent.com/31009952/72909756-87298f00-3d05-11ea-91a0-edf567545277.png">

### Describe the behavior you expected

Real time spellchecking should ignore words in upper case and with numbers if these options are checked. Compare this to running spell check, Edit -> Check Spelling or <kbd>F7</kbd>, which ignored them.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by adamconroy** [comment]
@rich-rstudio please see issue #6271 
more detail in the pull request: https://github.com/rstudio/rstudio/pull/6267

**Comment by ronblum** [comment]
Verified that upper case is working. I'm marking this "verified" despite the number issue since that's covered in #6271.
