### ISSUE TITLE
Non covered exception for RTools check

### ISSUE THREAD

**Issue by Toniiiio** [rstudio/rstudio#6076]
### Steps to reproduce the problem
```
Sys.setenv(BINPREF = "C:/PROGRA~1/R/Rtools/mingw_64/bin") # note the missing forward slash at the end
Sys.which("gcc.exe")
TRUE

 install.package("ellipsis", type = "source")
Fehler in install.package("ellipsis", type = "source") :

[...]

C:/PROGRA~1/R/Rtools/mingw_64/bingcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c dots.c -o dots.o
C:/PROGRA~1/R/Rtools/mingw_64/bingcc: not found

```
### Describe the problem in detail
Skipping the last forward slash in the BINPREF variable

- passes the test in https://github.com/rstudio/rstudio/blob/275d6eba762ffa9d79a189033fd47a6f77781f33/src/cpp/session/modules/ModuleTools.R#L85-L88
- but during installation process results in `C:/PROGRA~1/R/Rtools/mingw_64/bingcc: not found`, see longer log above.

### Describe the behavior you expected

- either let the rtools check fails with sthg along
```
file.exists(paste(c(Sys.getenv("BINPREF"), "gcc.exe"), collapse = ""))

# or with pipes
library(magrittr)
Sys.getenv("BINPREF") %>% c("gcc.exe") %>% paste(collapse = "") %>% file.exists
```

- or check for missing forward slash and add it in case it is missing (if that is reasonable)

**Comment by ronblum** [comment]
@Timag Thank you for raising your concern. We'll review it during our ongoing development of RStudio.
