### ISSUE TITLE
Version 1.2.5033 vs 1.1.463

### ISSUE THREAD

**Issue by neuhausi** [rstudio/rstudio#6079]
### System details

    RStudio Edition : 
    RStudio Version : 1.2.5033
    OS Version      : MacOS
    R Version       : 3.6.1

### Steps to reproduce the problem
library(canvasXpress)
canvasXpress(
     data="https://www.canvasxpress.org/debug/Apoptosis.xml",
     graphType="Network"
 )
### Describe the problem in detail
Code  works in R-Studio version 1.1.463 but doesn't work in 1.2.5033 behind a proxy
### Describe the behavior you expected

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Sorry, there's not enough info here to diagnose. You haven't indicated what proxy you're using, how it's configured, or what error your are seeing. You should ask for help on our forum if you're still stuck:

https://community.rstudio.com/c/rstudio-ide
