### ISSUE TITLE
Triggering command via shortcut should close menus

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6080]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.772
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- Start RStudio Server
- Show File menu via <kbd>Ctrl+Alt+F</kbd>
- <kbd>Ctrl+2</kbd> to move focus to Console

### Describe the problem in detail
- Focus moves to console but menu remains displayed

### Describe the behavior you expected
- Firing a command via keyboard shortcuts should close open menus on Server
- Same goes for dropdown menus on toolbars, etc. (also applies on desktop IDEs)

**Comment by ronblum** [comment]
Verified in RStudio Server 1.3.910.
