### ISSUE TITLE
Code running with Version 1.1.463 but not 1.2.5033

### ISSUE THREAD

**Issue by JBLecomte** [rstudio/rstudio#6083]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      :  Windows >= 8 x64 (build 9200)
    R Version       :  3.6.2 (2019-12-12)

### Steps to reproduce the problem
```
install.packages(c("FLCore", "FLAssess", "FLXSA"), repos="http://flr-project.org/R")
library(FLCore)
library(FLAssess)
library(FLXSA)
data(ple4)
data(ple4.indices)
xsa.control <- FLXSA.control()
ple4.xsa    <- FLXSA(ple4, ple4.indices, xsa.control)
retro.years <- 2012:2017 # updated values from online tutorial
ple4.retro <- tapply(retro.years, 1:length(retro.years), function(x){
  window(ple4,end=x)+FLXSA(window(ple4,end=x),ple4.indices)
})
```

### Describe the problem in detail
The above code run with base R and Rstudio desktop version 1.1.463. When I run the code with Rstudio desktop version 1.2.5033:

```
retro.years <- 2012:2017 # updated values from online tutorial
ple4.retro <- tapply(retro.years, 1:length(retro.years), function(x){
  window(ple4,end=x)+FLXSA(window(ple4,end=x),ple4.indices)
})
```
I get the following error:
`Error in lapply(assess@index, FLQuant) :  negative length vectors are not allowed`

### Describe the behavior you expected
I expect the above code to run as in base R and Rstudio desktop version 1.1.463.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by pascaloettli** [comment]
Not reproducible under `Ubuntu 18.04.3` with Rstudio versions `1.2.5033` and `1.3.776`

**Comment by JBLecomte** [comment]
So it's a windows/Rstudio(1.2.5033) related issue. Before posting the issue, I made a clean install of R and Rstudio to be sure. I also tried on a different windows computer and I had the same error.

**Comment by ronblum** [comment]
@JBLecomte Thank you for filing the issue. I am able to reproduce this in RStudio Desktop 1.3.776 on MacOS 10.15.3. However, it's also an issue in 1.1.463, and in R 3.6.2 outside of RStudio. What do you get when you run it just in R, not in RStudio?

**Comment by JBLecomte** [comment]
The following code works for me with `R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"` outside of Rstudio Desktop  (1.2.5033) on a windows machine. I am able to create the object `ple4.retro` which I can't do inside Rstudio Desktop  (1.2.5033).

```
install.packages(c("FLCore", "FLAssess", "FLXSA"), repos="http://flr-project.org/R")
library(FLCore)
library(FLAssess)
library(FLXSA)
data(ple4)
data(ple4.indices)
xsa.control <- FLXSA.control()
ple4.xsa    <- FLXSA(ple4, ple4.indices, xsa.control)
retro.years <- 2012:2017 # updated values from online tutorial
ple4.retro <- tapply(retro.years, 1:length(retro.years), function(x){
  window(ple4,end=x)+FLXSA(window(ple4,end=x),ple4.indices)
})
```

However, I did not try RStudio Desktop 1.3.776.

**Comment by ronblum** [comment]
After trying to reproduce, I get:
- Windows 10 + R 3.6.2 + RStudio Desktop 1.2.5033 and 1.3.776: same as above—works in R but not RStudio
- MacOS 10.15.3 + R 3.6.2 + RStudio Desktop 1.2.5033 and 1.3.776: fails in R and RStudio
- Red Hat 7.8 + R 3.6.2 + RStudio Server 1.3.776: works in both R and RStudio.

It looks like this is only using Desktop and the behavior between operating systems is different. Since Windows shows a difference between R and RStudio's behavior, I'll mark this as a bug to review as we continue RStudio development.
