### ISSUE TITLE
Console output reannounced from start with Chrome

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6084]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.773
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- Using Chrome on Windows or Mac, load RStudio Server
- Start screen reader (VoiceOver on Mac, NVDA on Windows)
- Clear the Console (Ctrl+L)
- `> cat("One")` <kbd>Enter</kbd>
- `> cat("Two")`<kbd>Enter</kbd>

### Describe the problem in detail
- after the first command, correct output is read (the executed command and it's output)
- after the second command, the first command and its output is re-read, then the second command
- this continues with all subsequent output (the entire console is re-read from the beginning)

### Describe the behavior you expected
- only new output is read; this behaves correctly in Safari/VoiceOver on Mac, and FireFox/NVDA on Windows

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rich-rstudio** [comment]
@gtritchie I confirmed Chrome is working as expected but when I tried Safari it looks like the output is not being read

**Comment by gtritchie** [comment]
@rich-rstudio What version of Safari, macOS, and RStudio Server?

**Comment by rich-rstudio** [comment]
@gtritchie 
Safari - Version 13.0.5
MacOs - 10.14.6 Mojave
RStudio Server - Version 1.3.888

**Comment by gtritchie** [comment]
@rich-rstudio Perhaps an issue with VoiceOver on Mojave; just confirmed it's working as expected with Catalina. I don't have a machine running Mojave.

**Comment by ronblum** [comment]
Confirmed that it's working on Catalina, as well as Windows 10 with NVDA.
