### ISSUE TITLE
Freeze row number column in View() when scrolling to the right

### ISSUE THREAD

**Issue by hlhunkin** [rstudio/rstudio#6089]
When I scroll to the right when View()ing big dataframe, it becomes difficult to make sure I am reading along the same row of data, because the row number column disappears off the left of the panel.  The row number should be frozen on the left hand size of the panel so that it's easy to check data belongs to a specific row number in large dataframes.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/3463.
