### ISSUE TITLE
R script tabs should have the exit cross on the left-hand side

### ISSUE THREAD

**Issue by theoroe3** [rstudio/rstudio#6095]
R script tabs should have the exit cross on the left-hand side. This means you can close more than one tab in a row without having to move your cursor, like in safari on any apple product. 

Either this or the file name should not affect the length of the tab bar, such as in google chrome. 

Thanks!

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/4805.
