### ISSUE TITLE
Keyboard shortcuts Ctrl+X, Ctrl+C and Ctrl+V not working in new source windows

### ISSUE THREAD

**Issue by SebVen** [rstudio/rstudio#6096]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.776
    OS Version      :  Windows 10 10.0.18363
    R Version       :  3.6.2

### Steps to reproduce the problem
Open R or RMD script in a new source window using "Show in new window" function. In the new window select code and use keyboard shortcuts Ctrl+X, Ctrl+C or Ctrl+V.

### Describe the problem in detail
Ctrl+X, Ctrl+C or Ctrl+V do not work in new source windows in RStudio. Neither selected code is copied or cut nor can anything be pasted into the script using the shortcuts. These functions from the Edit or context menus work without any issue. Other shortcuts such as Ctrl+S or Ctrl+I work fine.

### Describe the behavior you expected
Cut, copy or paste when using Ctrl+X, Ctrl+C or Ctrl+V shortcuts respectively.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/5936.

**Comment by jamesdalg** [comment]
There may have been a reversion in 2023.12.1 Build 402, using Ubuntu 22.04.3 LTS. I have tried updated to today's daily after using apt-get purge rstudio, but I cannot get rid of it.
