### ISSUE TITLE
RStudio doesn't open after restoration to an earlier state

### ISSUE THREAD

**Issue by faltinl** [rstudio/rstudio#6099]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version : x86_64-w64-mingw32/x64 (64-bit) under Win10 x64 (build 18363), Bios V1.08
    R Version : MRO 3.5.1

### Steps to reproduce the problem
When trying to start RStudio both by klicking the icon on the WIN start pane or by any .R-document, the RStudio main menu bar appears but... 

### Describe the problem in detail
...then appears "this website is not accessible / 127.0.0.1 has declined connection..." (see screen shot):

![RStudio_20200127_1919](https://user-images.githubusercontent.com/22592465/73202419-50a3a800-413b-11ea-8660-4701b9f95770.PNG)

The menu buttons are clickable, i.e. change their shades, but don't initiate any reaction.

### Describe the behavior you expected
Destop opens, RStudio ready for use.
 
### Notes
1. I did not attempt to install a separate, beware the newest version of RStudio, because the aim of returning back to this restoration point was exactly to be able to see under which conditions my R-program was running 2 weeks earlier. There are numerous parameters exchanged between this (Keras-) machine learning program and the R/Python environment provided by Anaconda and I want to find out details in that context.
2. The diagnostic report was empty.
3. The WIN system menu "deinstall programs" shows my RStudio still existing with date of installation and version number.

**Comment by ronblum** [comment]
@faltinl Does the problem still occur with the current version of RStudio, 1.3.1056 https://rstudio.com/products/rstudio/download/#download ?

**Comment by faltinl** [comment]
@ronblum Thanks for your interest, Ron. I have to upgrade my existing RStudio first. Do I need to remove my previous version of RStudio manually in order to upgrade  to RStudio 1.3.1056 or will the new version do that automatically? I'm asking because I have Tensorflow 2.2.0 installed and it was an awful job to get that working; to loose that installation would be a hard blow for me, not to speak of all the other packages...

**Comment by ronblum** [comment]
@faltinl You don't need to remove the old version—you can just run the 1.3.1056 installer.

**Comment by faltinl** [comment]
Working perfectly now - tnx for your hint, Ron!-)
