### ISSUE TITLE
cannot insert roxygen2 skeleton from code menu for one line function

### ISSUE THREAD

**Issue by AlisonLanski** [rstudio/rstudio#6104]
If you to use the Code menu to "Insert roxygen2 skeleton" for one line functions you get a popup error message that your cursor is not inside the function (even if it is): 
![image](https://user-images.githubusercontent.com/40475397/73296044-dc1e4700-41d6-11ea-83a3-a685530cfd15.png)

This happens in standalone scripts or within a package/project

Rstudio version: 1.2.5033
R version: 3.6.2

**Comment by kevinushey** [comment]
This feature only works if the function body contains braces:

```
fail <- function (x) { x * 100 }
```

(side note: it also fails if the function is the first line in a script; adding a newline at the top of the script fixes that)
