### ISSUE TITLE
UI preferences update in undefined order

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#6105]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3
    OS Version      : Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem
- Go to Tools -> Global Options -> Spelling
- Uncheck the realtime spellchecking box
- Change the dictionary to English (United Kingdom)
- Notice in the Network tab of devtools that it loads the UK dictionary

### Describe the problem in detail
Right now preference pane options, afaik, are wholly independent so updating both realtime spellchecking and dictionary to load can happen in any order so the dictionary loader doesn't always know that it should be disabled when it gets the new dictionary update.

More importantly in this situation, if real time spellchecking is off and you turn it on AND change the dictionary the dictionary loader will assume it is still off so not load the dictionary.

### Describe the behavior you expected
A preference pane save should be able to batch all option updates as a whole so dependent UI preference handlers have the full picture in their onChange handlers.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by adamconroy** [comment]
Thought about this a bit more and most cases can be dealt with by sharing handlers and dealing with out of order updates. There may be cases where we need grouped updates but I'm not sure we have one at the moment so I'm closing this and will be more thoughtful when adding UI prefs and handlers.

**Comment by R-Hannibal** [comment]
Marking this ticket as verified, sounds like we re-thought this change.
