### ISSUE TITLE
INSTALL file mentions an apparmor profile, that does not exist

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#6110]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.5033 and git master
    OS Version      : openSUSE Tumbleweed, but actually irrelevant here
    R Version       : 3.6.2

### Steps to reproduce the problem

Check out the `INSTALL` file, it mentions apparmor profiles, but these do not exist in the source tree, as they got removed by commit e939585a19e9d98722328a0bac82619b0750aa3b.

### Describe the behavior you expected

Either the apparmor profiles should still exist or they should not be included in the `INSTALL` file.

**Comment by jmcphers** [comment]
Thank you for spotting this! We've just removed them from INSTALL.
