### ISSUE TITLE
Are the /var/*/rstudio-server directories still required?

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#6111]
I am currently working on a rpm package of rstudio-server for opensuse Tumbleweed and wanted to get some clarification concerning the following directories and whether they are actually still required:
- `/var/run/rstudio-server`
- `/var/lock/rstudio-server`
- `/var/log/rstudio-server`
- `/var/lib/rstudio-server`

Except for `/var/lib/rstudio-server` there's only mention of these directories in the legacy init scripts, which aren't required when using the systemd unit.

Are they all still required or can I omit all of them except `/var/lib/rstudio-server`?

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
