### ISSUE TITLE
INSTALL mentions directories in /var/ which do not appear to be in use anymore

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#6112]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.5033
    OS Version      : Linux
    R Version       : 

### Steps to reproduce the problem

The `INSTALL` file mentions the following directories that should be created manually:
- `/var/run/rstudio-server`
- `/var/lock/rstudio-server`
- `/var/log/rstudio-server`
- `/var/lib/rstudio-server`

Except for `/var/lib/rstudio-server` there's only mention of these directories in the legacy init scripts. Assuming that I am correct, could a note be added to the INSTALL file, that only `/var/lib/rstudio-server` is required as long as you use systemd?

**Comment by ronblum** [comment]
@dcermak Thank you for raising the issue. We'll review it as we continue development of RStudio.

**Comment by jmcphers** [comment]
`var/log/rstudio-server` is in fact needed (it is the default log location), but you're right about the rest. I'll remove these.
