### ISSUE TITLE
gwtc is always recompiled even if already built and the compilation runs on all cores

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#6121]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.5033
    OS Version      : openSUSE Tumbleweed
    R Version       : 3.6.2

### Steps to reproduce the problem

Get the source code of rstudio and then run:
``` ShellSession
$ mkdir build; pushd build
$ cmake -DRSTUDIO_TARGET=Desktop -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=/tmp/rstudio ..
$ make -j $(nproc) all # now wait for a while
$ make -j $(nproc) all # this should take no time at all, but gwtc is recompiled again
$ make install # this recompiles gwtc as well…
```
This is actually pretty annoying, because when building a package of rstudio, we cannot run a simple `make all; make install` because that will run the gwtc compilation twice wasting at least 1.5 minutes of build times.

There is also a second issue with the gwtc compilation: it runs on **all** cores by default. So if you run a `make -j N` (where you adjusted `N` so that it doesn't OOM your worker), your worker might still die, because the gwtc compilation will run alongside the C++ code compilation, but occupy all cores and consume ridiculous amounts of memory. This is manageable, we currently work around that by running:
``` ShellSession
$ make -j ${N} rstudio rsession rpostback rstudio-core rstudio-monitor rstudio-r rstudio-session-workers diagnostics rserver rserver-pam
$ make install
```
which runs the gwtc compilation in the install phase.

### Describe the behavior you expected

- gwtc should never be recompiled unless the sources changed
- the build should not run on all cores

**Comment by jmcphers** [comment]
Thanks for reporting this! Unfortunately this is a limitation of GWT/javac and not something RStudio can fix. We'd suggest looking into configuring the JVM and/or using e.g. `taskset` or `cgroups` to restrict CPU access to the compilation process at the OS level.
