### ISSUE TITLE
Problem between Qt (used by RStudio) and Nvidia OpenGL driver (I think)

### ISSUE THREAD

**Issue by SCZD** [rstudio/rstudio#6122]
When i launch Rstudio (1.2.5033) in ubuntu 18.04 the program start bug i mean in a very big windows empty. [Like this](https://i.stack.imgur.com/Qs1Fx.jpg).  I have a RTX2080 with nvidia-driver-435 (proprietary,tested).

**Comment by jmcphers** [comment]
Sorry, we would need much more detail to fix this. Please fully complete the issue template! If you need help:

https://community.rstudio.com/c/rstudio-ide
