### ISSUE TITLE
Error opening file on a proyect located at /srv/shiny-server

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#6127]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.776
    OS Version      : Ubuntu 18.04.3 LTS
    R Version       : 3.6.2

### Steps to reproduce the problem
* Open a Rstudio Project at /srv/shiny-server (I have set very lax permissions for testing i.e. 777)
* Open any file under that project

### Describe the problem in detail
When I try to open any file inside that project I get a pop-up window with an error message "The file is in a restricted path and cannot be opened by the source editor." even with 777 permissions.
![image](https://user-images.githubusercontent.com/14981085/73508653-9d40ea80-43aa-11ea-8bef-294d507d59e0.png)
But then if I immediately restart the RStudio session the file opens and I can edit it.
![image](https://user-images.githubusercontent.com/14981085/73508671-ac279d00-43aa-11ea-9f17-eaa7689af536.png)
![image](https://user-images.githubusercontent.com/14981085/73508683-b8135f00-43aa-11ea-83e6-335d7d355b8c.png)

I have used this setup for a very long time with 1.2 versions of RStudio without any issue.

### Describe the behavior you expected
I expect to open files normally as I used to do with 1.2 versions of RStudio

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is a new security feature in RStudio 1.3. Many users have complained that RStudio allows you to open any file on the system (which has obvious security ramifications). By default, you can only open files in known-safe paths. It is possible to configure RStudio to allow opening in other paths as well; see here for details:

https://docs.rstudio.com/ide/server-pro/latest/r-sessions.html#directory-management

**Comment by Avik1993** [comment]
Hi @jmcphers 
I am facing similar issue, even after configuring `rsession.conf` with whitelisted directories.
The interesting part is, every time I restart studio service, I am able to access files and very next moment I get the same error.

Any pointers on this?
