### ISSUE TITLE
Suggestion: Add tinytex package to list of LaTeX installations in new Rmd file dialogue 

### ISSUE THREAD

**Issue by remlapmot** [rstudio/rstudio#6128]
Under: File | New File | R Markdown... I suggest amending the message beside PDF, which currently mentions MiKTeX, MacTeX, and TeX Live, to include using your tinytex package:

![new-rmd-window](https://user-images.githubusercontent.com/3777473/73556490-74226780-4447-11ea-856d-07ff8ca30baa.png)

**Comment by ronblum** [comment]
@remlapmot Thank you for the suggestion! We'll review as part of our ongoing development of RStudio.

**Comment by remlapmot** [comment]
Great, thanks.
