### ISSUE TITLE
corrupt shortcut shown / used when binding keyboard shortcuts

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6129]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.3.803
    OS Version      : Windows 10 x64 (build 18362)
    R Version       : R version 3.6.1 (2019-07-05)

### Steps to reproduce the problem

Switch to a German (QWERTZ) keyboard layout, then try to change a keyboard shortcut using the Ctrl + Shift modifier keys. (For this example, I am trying to use <kbd>Ctrl + Shift + V</kbd>.)

### Describe the problem in detail

Sometimes, an invalid key (square box) is shown.

### Describe the behavior you expected

The key should be bound without issue.

### Notes

The `key` reported on the associated Javascript event appears to be corrupt.

<img width="364" alt="Screen Shot 2020-01-31 at 8 33 31 AM" src="https://user-images.githubusercontent.com/1976582/73556657-b5ddee80-4404-11ea-9883-f8a36fe35331.png">
<img width="668" alt="Screen Shot 2020-01-31 at 8 33 37 AM" src="https://user-images.githubusercontent.com/1976582/73556658-b5ddee80-4404-11ea-8a4b-2b5e74c8d2a3.png">

**Comment by kevinushey** [comment]
I can reproduce in Qt using the nano browser with <kbd>Ctrl + Z</kbd> and the default English keyboard layout.

**Comment by kevinushey** [comment]
Filed a Qt bug: https://bugreports.qt.io/browse/QTBUG-81783

**Comment by jmcphers** [comment]
It looks like this is going to need to be resolved on Qt's end, and even if they do commit a fix it's extremely unlikely we could bump Qt versions to pick it up in the 1.3 timeframe.

**Comment by AndriSignorell** [comment]
This bug appeared to have been solved, but it is back (again?) with Version 1.3.959 - and still annoying. ;-)

**Comment by kevinushey** [comment]
Unfortunately, no -- there isn't currently any workaround that I'm aware of.

This has been fixed in the latest versions of Qt, so we'll hopefully pick up this fix when we next update Qt (not in v1.4, but likely the release following that).

That said, I think this is worth tracking for v1.4 in case we can find a simple workaround that we can implement for v1.4 (without requiring a new version of Qt).

**Comment by jmcphers** [comment]
@kevinushey Any chance of a workaround in 1.3 patch? In my testing this is happening on any Ctrl-based keyboard shortcut on Windows which makes it very difficult to create any practical bindings. 

Also just reported on the blog:

https://blog.rstudio.com/2020/05/27/rstudio-1-3-release/#comment-4930897957

> On this new version, when I tried to change any shortcut to, for example "Run Selected Line" to 'Ctrl + R' it doesn't appear the "R" it appears a square: Ctrl + ☐. Looks like a bug

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version 1.3.1039, R Version 4.0.1, Windows 10 Desktop

Comparison testing between versions 1.3.959 and 1.3.1039, default English keyboard commands which were showing as Ctrl + Square symbol and non-functional are now setting and functioning correctly.
