### ISSUE TITLE
Allow opening files in RStudio by dragging them in

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#6134]
With many text editors (and other software), I'm used to being able to drag a file (from my desktop/explorer) into it, and that file opens in the software. When I try that with RStudio, nothing happens. It'd be very useful to me, and I presume to many others, if dragging an R file or any other text file would simply open it in RStudio. For R files I could simply double click the file to open it, but this has two limitations:

1. If I have multiple RStudio instances open and I want to open the file in a specific RStudio, I cannot
2. If I want to open a text file (such as DESCRIPTION, NEWS.md, csv files, etc) in RStudio rather than my default editor for that file extension, this won't work

This is related to #4037

**Comment by jmcphers** [comment]
We are using #4037 to track this.
