### ISSUE TITLE
Interest in / advice for better data.table integration

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#6135]
tab-complete for `data.table` is currently a bit rudimentary, essentially limited to column names within `[ ]`.

I have been mulling for a while with whether this integration could be improved, e.g. with column name tab completion for `setkey(x, <TAB>)` or `setorder(x, <TAB>)`, etc.

So a few questions:

Would such a thing be more appropriate as an add-in, or integrated to RStudio itself? If the latter, would RStudio accept a PR to that end?

Any advice for where to look in the current RStudio source to get started building this (either as an add-in or directly to RStudio) would also be appreciated.

Thanks as always!

**Comment by kevinushey** [comment]
Good question. One of the downsides of RStudio's autocompletion system is that, in its current form, it's challenging to extend. We'd like to eventually rectify that, but that's likely going to be a large project and we haven't scoped time to make that happen yet.

Some work has happened in the [completeme](https://github.com/jimhester/completeme) package to make an extensible completer, but we haven't yet evaluated whether this is something RStudio could use for completions behind the scenes, or whether its interface is flexible enough to accommodate what is required by `data.table`.

**Comment by MichaelChirico** [comment]
OK, makes sense. Shall I leave this open and the team can follow up when the bigger upstream issue comes more into focus?

**Comment by ronblum** [comment]
@MichaelChirico Let's leave the ticket open so that it's included when we review issues as part of development of RStudio.

**Comment by MichaelChirico** [comment]
Shall we close this to help unclutter the issue tracker? it's still kind of abstract
