### ISSUE TITLE
Keyboard shortcut(s) to automatically surround pasted text with quotes

### ISSUE THREAD

**Issue by stevecondylios** [rstudio/rstudio#6136]
When pasting text from external sources into RStudio, we often need to surround the pasted text with double quotes, single quotes, or backticks, so that the pasted content can be used as a string.

It would be very handy to have a keyboard shortcut that takes care of the quoting for us. 

### Example
Suppose the clipboard contained `here is my text` and we want that as a string, we must paste it and then manually add quote characters to the start/end of the pasted content. It's a minor inconvenience, but more of an inconvenience for larger clipboard contents (hence requiring scrolling).

It would be very useful to be able to automatically paste the clipboard contents surrounded in quotes, i.e. as `"here is my text"`, `'here is my text'` etc. 

Suggested keys could be along the lines of 

- <kbd>command</kbd> + <kbd>v</kbd> + <kbd>shift</kbd> + <kbd>'</kbd> for double quotes
- <kbd>command</kbd> + <kbd>v</kbd> + <kbd>'</kbd> for single quotes 
- <kbd>command</kbd> + <kbd>v</kbd> + <kbd>`</kbd> for backticks

(and PC equivalents using <kbd>ctrl</kbd> in place of <kbd>command</kbd>)

### Note

We could use `readClipboard()`, but function calls are arguably more fiddly than a keyboard shortcut.

**Comment by jmcphers** [comment]
Have you tried the datapasta add-in? https://github.com/MilesMcBain/datapasta

**Comment by francisbarton** [comment]
@stevecondylios if you write the quotes first and then paste in between them, does this not give you what you want, pretty easily?
