### ISSUE TITLE
Change Inc. to PBC

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6141]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3
    OS Version      : all
    R Version       : all

### Steps to reproduce the problem

Find places with the company name, including:
- Help -> About RStudio
- `RStudio.Version()$citation`

There may be others.

### Describe the problem in detail

The company name is listed as, "RStudio, Inc."

### Describe the behavior you expected

The new company name, "RStudio, PBC".

**Comment by jmcphers** [comment]
We also need to update our copyright headers and lots of other stuff. I'll take this on.

**Comment by dfalty** [comment]
Verified 1.3.822-1
