### ISSUE TITLE
dependency installer might install recursive dependencies multiple times

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6145]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : v1.3.804
    OS Version      : Ubuntu 18.04 LTS
    R Version       : R version 3.6.1 Patched (2019-09-23 r77210)

### Steps to reproduce the problem

Create a new project, and then delete any installed packages in your user library (to simulate a "fresh" install of required packages):

```
userlib <- .libPaths()[1]
pkgs <- list.files(userlib, full.names = TRUE)
unlink(pkgs, recursive = TRUE)
```

Then, try to create a new R Markdown document. You will be prompted to install the `rmarkdown` package + its dependencies; click yes.

### Describe the problem in detail

The packages are installed one-by-one, in alphabetical order, with sequential calls to `utils::install.packages()`:

https://github.com/rstudio/rstudio/blob/ff3353badf84d2e8b1dbb42984b3bf05e5e33525/src/cpp/session/modules/SessionDependencies.cpp#L343-L389

R will also install the recursive dependencies of these packages when requesting installation of a particular package. For example, when `knitr` is installed, its dependencies are also installed:

![Screen Shot 2020-02-03 at 3 46 16 PM](https://user-images.githubusercontent.com/1976582/73700780-54d04800-469c-11ea-9bc7-08969d3f4c36.png)

![Screen Shot 2020-02-03 at 3 49 07 PM](https://user-images.githubusercontent.com/1976582/73700977-fe173e00-469c-11ea-9a64-dfdce39fdc3d.png)

We then later go on to re-install some of the packages which R has already installed for us:

![Screen Shot 2020-02-03 at 3 48 33 PM](https://user-images.githubusercontent.com/1976582/73700900-bbedfc80-469c-11ea-948c-f5127830f423.png)

This leads to some recursive dependencies being installed twice, which is expensive for some packages (especially those requiring compilation).

### Describe the behavior you expected

Each dependency should only be installed once.

**Comment by jmcphers** [comment]
Good catch. We install the packages one by one so we can give meaningful progress, and we'd like to keep doing that. I think the correct fix for this issue is to topologically sort the packages so that we always install dependent packages first.

**Comment by rich-rstudio** [comment]
verified on Version 1.3.897
