### ISSUE TITLE
RStudio needs to be tested with Microsoft Edge / Chromium

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6146]
We need to decide if we support Microsoft Edge version 79 and above (i.e. the Chromium-based Edge) for RStudio Server.

Presumably this means a test-pass and updating our documentation.

See also comments in #5823

**Comment by scubastevew** [comment]
From Zendesk: https://rstudioide.zendesk.com/agent/tickets/44060

**Comment by rich-rstudio** [comment]
tested RStudio Server  1.3.926-1 on Edge Version 80.0.361.69 (Official build) (64-bit), no major issues found
