### ISSUE TITLE
Code Completion in Shiny

### ISSUE THREAD

**Issue by josephstatwick** [rstudio/rstudio#6149]
Are there plans to add more robust code completion for shiny input and output elements? I find that 90% of my bug troubleshooting in shiny is because I do something stupid like this:

```
# server code
output$box <- renderUI({
    checkboxInput("check", "a checkbox")
})

variable <- reactive({
    req(input$checkbox)
    some_code()
})
```
Since R generally uses lazy evaluation for shiny elements, my reactive variable never gets calculated (or my conditional UI doesn't show up, or whatever), because it's waiting for an input variable that doesn't exist. 

I've discovered that code completion only works in split apps and only for input variables that are defined in ui.r. For me, this means two—out of 40+ and counting. The vast majority of my inputs are constructed on the server side, since they're either conditionals that are too complicated for conditionalPanel() or are displayed in modals (or both). This essentially means that code completion is of no help to me. I would love it if code completion could actively parse the entire script the way it does for other script types, and while I'm wishing, I would love code completion for outputs too. Icing on the cake would be line-by-line "not in scope"-style error checking.

Thanks,

**Comment by ronblum** [comment]
@josephstatwick Good question—we'll review this as an enhancement request as we continue development of RStudio.
