### ISSUE TITLE
git features do not work in directory containing '!'

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6160]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : macOS 10.15.3
    R Version       : 3.6.1

### Steps to reproduce the problem

Create a new project called, for example, "Hello, world!". Initialize it with a git repository as well. Then, try editing files within the project.

### Describe the problem in detail

The Git pane does not update and show files as they are changed.

### Describe the behavior you expected

Changes should be reported as normal in the Git pane.

### Notes

I suspect the issue here is that we escape `!` characters for the shell here:

https://github.com/rstudio/rstudio/blob/66fad93935855d4599e0e74076e86aae6eda12a9/src/cpp/core/system/PosixShellUtils.cpp#L26

but `!` does not actually need to be escaped when quoted for the shell.

See also: https://community.rstudio.com/t/odd-rstudio-git-issue-git-tab-present-but-empty-even-when-changed-files-present/50969/3

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dfalty** [comment]
Tried `Hello, World!` git project on version 1.4.874 and this seems to work fine now.
