### ISSUE TITLE
git diff does not detect changes made within RStudio

### ISSUE THREAD

**Issue by nasifimtiazohi** [rstudio/rstudio#6162]
### System details

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night 

### Steps to reproduce the problem

1. clone a git repo
2. make any change in a file
3. run `git diff`; it will show all lines have been deleted and added

### Describe the problem in detail
When I change a file in a git repo from within RStudio; git diff does not detect the change. Rather, it shows all lines in that file are deleted and then added. Note that, my repo has subfolders and have capital letters and '_' in the folder names.

### Describe the behavior you expected
git diff should have correctly recognized only the modifications. 

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It might be helpful if you could share the output of `getwd()` in this project, just so we can know exactly what the path is and if there are any special characters that might cause issues with RStudio's git integration.

**Comment by jmcphers** [comment]
This may not be related to the path at all but to line endings -- i.e. that all of the "changed" lines just have an invisible change at the end of each line. Is it possible that you have checked out a git repo with one style of line endings, and that saving it is converting to another style of line endings? Can you share your Git config for line ending conversion and RStudio's settings for the same?
