### ISSUE TITLE
Relocation of RStudio-Desktop directory for Windows

### ISSUE THREAD

**Issue by kruess** [rstudio/rstudio#6163]
Right now, RStudio running on Windows keeps a mixture of temporary and persistent information in 

%LOCALAPPDATA%\RStudio-Desktop\

Unfortunately, this leads to problems on VDI or Shared hosted desktops because that part of the user profile is usually not going to be roamed and as such the information will not be available after the next logoff / logon. As a consequence, the enduser always has to reconfigure his RStudio to his desires (color, fonts, etc), which is quite annoying for a modern application.

It would be very useful, if some or all of the content of RStudio-Desktop would be relocated to

%APPDATA%\Rstudio-Desktop\

Mainly configuration stuff should be located there, whereas cache / logging / temporary information might stay in the %LOCALAPPDATA%.

This way, it would reflect the windows user profile design and follow best practices.

**Comment by jmcphers** [comment]
Good news, this is already addressed in the upcoming release of RStudio (1.3). You can try a preview here:

https://www.rstudio.com/products/rstudio/download/preview/
