### ISSUE TITLE
RStudio terminal might inherit obsolete R_LIBS_USER on R update

### ISSUE THREAD

**Issue by michaja** [rstudio/rstudio#6172]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : x86_64-pc-linux-gnu Ubuntu 19.10
    R Version       : 3.6.1

### Steps to reproduce the problem
* from an older R version, have Tools -> Global Options -> Terminal -> "Save and restore environment variables" checked (I think it's the default)
* use the terminal
* update R version
* invoke `Rscript` in the terminal
### Describe the problem in detail
The terminal saves `R_LIBS_USER`, which in my case pointed to `~/R/x86_64-pc-linux-gnu-library/3.4`.  After updating R from 3.4 to 3.6, `R_LIBS_USER` would still point to the R 3.4 library (being restored) and `Rscript` 3.6 (called from the terminal) would complain about packages being built for a different R version.
### Describe the behavior you expected
Not having the environment of the terminal point to obsolete R libraries.  
Maybe filter the R-related environment variables to prevent them from pointing to outdated libraries.  I'm not sure where `R_LIBS_USER` is coming from, but I suspect that it's set by RStudio in the first place.  So the information of "RStudio normally would set this variable to X" and "the terminal would inherit the value Y" should be available.  If users do need a specific value for `R_LIBS_USER` they should be able to set it using `.rstudio-bashrc`, from my understanding.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
`R_LIBS_USER` (and other similar environment variables) get set by R, within the system `Renviron` file. For example, I have on macOS:

```
$ cat $(R RHOME)/etc/Renviron
### etc/Renviron.  Generated from Renviron.in by configure.
###
### ${R_HOME}/etc/Renviron
###
### Record R system environment variables.

R_PLATFORM=${R_PLATFORM-'x86_64-apple-darwin15.6.0'}
## Default printer paper size: first record if user set R_PAPERSIZE
R_PAPERSIZE_USER=${R_PAPERSIZE}
R_PAPERSIZE=${R_PAPERSIZE-'a4'}
## Default print command
R_PRINTCMD=${R_PRINTCMD-'lpr'}
# for Rd2pdf, reference manual
R_RD4PDF=${R_RD4PDF-'times,inconsolata,hyper'}
## used for options("texi2dvi")
R_TEXI2DVICMD=${R_TEXI2DVICMD-${TEXI2DVI-'/usr/local/bin/texi2dvi'}}
## used by untar(support_old_tars = TRUE) and installing grDevices
R_GZIPCMD=${R_GZIPCMD-'/usr/bin/gzip'}
## Default zip/unzip commands
R_UNZIPCMD=${R_UNZIPCMD-'/usr/bin/unzip'}
R_ZIPCMD=${R_ZIPCMD-'/usr/bin/zip'}
R_BZIPCMD=${R_BZIPCMD-'/usr/bin/bzip2'}
## Default browser
R_BROWSER=${R_BROWSER-'/usr/bin/open'}
## Default editor
EDITOR=${EDITOR-${VISUAL-vi}}
## Default pager
PAGER=${PAGER-'/usr/bin/less'}
## Default PDF viewer
R_PDFVIEWER=${R_PDFVIEWER-'/usr/bin/open'}
## Used by libtool
LN_S='ln -s'
MAKE=${MAKE-'make'}
## Prefer a POSIX-compliant sed on e.g. Solaris
SED=${SED-'/usr/bin/sed'}
## Prefer a tar that can automagically read compressed archives
TAR=${TAR-'/usr/bin/tar'}

## System and compiler types.
R_SYSTEM_ABI='osx,gcc,gxx,gfortran,gfortran'

## Strip shared objects and static libraries.
R_STRIP_SHARED_LIB=${R_STRIP_SHARED_LIB-'strip -x'}
R_STRIP_STATIC_LIB=${R_STRIP_STATIC_LIB-'strip -S'}

#R_LIBS_USER=${R_LIBS_USER-'~/R/x86_64-apple-darwin15.6.0-library/3.6'}
R_LIBS_USER=${R_LIBS_USER-'~/Library/R/3.6/library'}

### Local Variables: ***
### mode: sh ***
### sh-indentation: 2 ***
### End: ***
## CRAN R ships with qpdf inside so use it unless directed otherwise
R_QPDF=${R_QPDF-'/Library/Frameworks/R.framework/Resources/bin/qpdf'}
```

It probably makes sense to unset some of these.

**Comment by gtritchie** [comment]
We have a blacklist option for environment variables restored by the session.

https://github.com/rstudio/rstudio/issues/5769

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> We have a blacklist option for environment variables restored by the session.
> 
> #5769

Unless I'm [missing something](https://support.rstudio.com/hc/en-us/articles/360009863114-Configuring-RStudio-Server-to-use-RStudio-Package-Manager), `rsession.conf` only applies to RStudio Server, while this bug (also) occurs in RStudio Desktop.  So 'session-env-var-save-blacklist' (#5770) isn't a solution for this.

Just ran into this again with R 4.0.2.

**Comment by michaja** [comment]
> We have a blacklist option for environment variables restored by the session.
> 
> #5769

Unless I'm [missing something](https://support.rstudio.com/hc/en-us/articles/360009863114-Configuring-RStudio-Server-to-use-RStudio-Package-Manager), `rsession.conf` only applies to RStudio Server, while this bug (also) occurs in RStudio Desktop.  So 'session-env-var-save-blacklist' (#5770) isn't a solution for this.

Just ran into this again with R 4.0.2.

**Comment by gtritchie** [comment]
Reactivating so I can ponder if we need a terminal blacklist for which env vars to save/restore.
