### ISSUE TITLE
Unicode in Jobs tab

### ISSUE THREAD

**Issue by CGMossa** [rstudio/rstudio#6173]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.803
    OS Version      :  Windows 10 x64 (build 17134)
    R Version       : R version 3.6.2 (2019-12-12)

### Steps to reproduce the problem

```
<U+2714> Package 'ggeffects' successfully installed.
```

### Describe the problem in detail

Pressing `install` when a source-file contains a `library(uninstalled_library)` starts a job
that attempts to install said `uninstall_library` if it is available. The last line contains this the
above snippet, but I am sure `<U+2714>` is supposed to be &#10004;.

### Describe the behavior you expected
I tried displaying unicode in the job tab using the `Source as Local Job...` and using `print`,
`cat`, and I couldn't display a unicode character. 

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@CGMossa Thank you for raising this issue! We'll review it during our ongoing work on RStudio. I can reproduce the issue on Windows 10. For comparison, it works correctly on MacOS 10.15.3:

<img width="318" alt="check_mark" src="https://user-images.githubusercontent.com/31009952/74051915-e4c90700-49a6-11ea-9ad1-9aa3e0154f0a.png">
