### ISSUE TITLE
Tutorials crashes if learnr not installed

### ISSUE THREAD

**Issue by ColinFay** [rstudio/rstudio#6176]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.776
    OS Version      : Mac OS
    R Version       : 3.6.0

### Steps to reproduce the problem

Launch the last version of the RStudio Preview without `{learnr}` installed

### Describe the problem in detail

I don't have `{learnr}` installed and tried the new Tutorial Pane, and the job crashes. 

```
Error in loadNamespace(name) : there is no package called ‘learnr’
Calls: sourceWithProgress ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

![Screenshot 2020-02-07 at 14 07 16](https://user-images.githubusercontent.com/17936236/74032170-9bcb7f80-49b3-11ea-85f9-6e4549e578d8.png)

### Describe the behavior you expected

As far as I see it the tutorial would be a good tool for beginners, but starting with this crash can be discouraging.

I would expect RStudio to either install the package automatically or to suggest to install it, instead of returning an error. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ColinFay Thank you for the suggestion! We'll consider it during our ongoing development of the RStudio IDE.

**Comment by kevinushey** [comment]
Closes via https://github.com/rstudio/rstudio/commit/fa73342438834faf17fd8e0e448cc22ae1f73996.
