### ISSUE TITLE
Tutorials : object 'tutorialLaunchBrowser' not found

### ISSUE THREAD

**Issue by ColinFay** [rstudio/rstudio#6177]
### System details

	RStudio Edition : Desktop
	RStudio Version : 1.3.776
	OS Version      : Mac OS
	R Version       : 3.6.0

### Steps to reproduce the problem

Launching learnr tutorials fails

### Describe the problem in detail

I've installed `{learnr}`, version 0.10.0 on my machine but when I tried to launch any of them, I have the following error: 

``` r
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'tutorialLaunchBrowser' not found
Calls: sourceWithProgress -> eval -> eval -> <Anonymous> -> ::: -> get
Execution halted
```

![Screenshot 2020-02-07 at 14 14 35](https://user-images.githubusercontent.com/17936236/74032474-565b8200-49b4-11ea-99f5-3bd987fe298d.png)

This doesn't seem to be `{learnr}` related as I can launch 

```
library(learnr)
run_tutorial("ex-data-basics", "learnr")
```

with success.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you have the development version of `rstudioapi` installed?

```
remotes::install_github("rstudio/rstudioapi")
```

**Comment by ColinFay** [comment]
Works with the dev version of `{rstudioapi}`, thanks ✅

**Comment by jmcphers** [comment]
RStudioapi 0.11 now on CRAN; this should be resolved.
