### ISSUE TITLE
Highlight Plumber tags

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#6180]
This is in reference to #2220. Plumber tags properly autocomplete in the IDE, but they aren't highlighted in any way. This is in contrast to roxygen comments, where the IDE highlights the roxygen tags:

![image](https://user-images.githubusercontent.com/10444878/74058717-d7f6e400-49a3-11ea-86e6-453eeca16459.png)

**Comment by gtritchie** [comment]
Can you provide more detail on what you're requesting?

See also these improvements made in 1.3:

#2219
#2220

**Comment by blairj09** [comment]
It would be nice to see this re-opened. Plumber tag highlighting would significantly improve the development experience for Plumber APIs
