### ISSUE TITLE
Commits panel doesn't render

### ISSUE THREAD

**Issue by ColinFay** [rstudio/rstudio#6181]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.776
    OS Version      : Mac OS
    R Version       : 3.6.0

### Steps to reproduce the problem

The Commit Pane stays blank or with "Loading Session"

### Describe the problem in detail

With the current dev version of RStudio, the Commit Pane doesn't render (it stays blank): 

If i click on commit here: 

<img width="1552" alt="Screenshot 2020-02-07 at 20 46 39" src="https://user-images.githubusercontent.com/17936236/74060918-3f845200-49eb-11ea-855a-6cd24fa1f724.png">

The new pane shows 'loading session...' for a while 

<img width="1440" alt="Screenshot 2020-02-07 at 20 46 49" src="https://user-images.githubusercontent.com/17936236/74060947-50cd5e80-49eb-11ea-9492-961eac8cf28c.png">

Waited for 10 minutes but nothing happened.

### Describe the behavior you expected

See the Commit Pane

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Thanks for the report! We are now tracking this more generally in https://github.com/rstudio/rstudio/issues/6201.
