### ISSUE TITLE
Error while rendering bookdowns

### ISSUE THREAD

**Issue by ColinFay** [rstudio/rstudio#6191]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.776
    OS Version      : Mac OS
    R Version       : 3.6.0

### Steps to reproduce the problem

An extra div in inserted when rendering bookdown. See below for comparison. 

### Describe the problem in detail

Using the default bookdown template in `1.3.776`: 

![Screenshot 2020-02-09 at 21 50 41](https://user-images.githubusercontent.com/17936236/74109822-392add00-4b87-11ea-9734-4c2445e6a549.png)

After switching back to version 1.2.5033 of RStudio:

![Screenshot 2020-02-09 at 21 56 08](https://user-images.githubusercontent.com/17936236/74109833-4ba51680-4b87-11ea-96a0-4d82f90f12de.png)

### Describe the behavior you expected

Same bookdown rendering

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ColinFay** [comment]
Note that I have noticed that in other bookdowns I have been writing, so it's not linked to the template.

**Comment by kevinushey** [comment]
I wasn't able to reproduce:

![Screen Shot 2020-02-10 at 9 13 54 AM](https://user-images.githubusercontent.com/1976582/74172773-aa00e200-4be5-11ea-9e65-66ad119634a8.png)

Could there be something else related to this issue? Also, it's not clear to me what you mean by:

> An extra div in inserted when rendering bookdown.
