### ISSUE TITLE
Can't change file type for "Find in Files"

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#6194]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.821
    OS Version      : macOS 10.15.2
    R Version       : 3.6.2

### Steps to reproduce the problem
Opening "Find in Files" and try to change the "Search these files" dropdown.

### Describe the problem in detail
When click on other types (e.g. "R Scripts") the selected value does not change.
Additionally, I can't seem to click on the "Package Source" type (it won't highlight). When I click on custom filter, the extra box for the filter appears but the dropdown value has not changed.
Doing it with arrows instead of the mouse has the same result.
It's not just a label update issue, as clicking on "R Scripts" results in Rstudio looking in all files.

### Describe the behavior you expected
I expect the dropdown value to update to the selected verion

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Hi @gregleleu I've identified the issue and am working on a fix for the selected 'All Files' value not changing.
Regarding the issue with "Package Source" this option is only available when you are in the base directory of a package containing a DESCRIPTION file. Can you confirm if this is where you have your 'Search in' path set to?

**Comment by gregleleu** [comment]
@melissa-barca 
No I wasn't working on a package, so it makes sense.
Thanks
