### ISSUE TITLE
Ctrl + Alt + B

### ISSUE THREAD

**Issue by Vivek-Prakash-US** [rstudio/rstudio#6196]
### System details

    RStudio Edition : Desktop (Zip/Tarballs)
    RStudio Version : 1.3.821
    OS Version      : Windows 10 (non-admin)
    R Version       : 3.6.2

### Describe the problem in detail
Ctrl + Alt + B does not work if script window is detached.
Works fine when the editor is docked.
### Describe the behavior you expected
For all lines from beginning of script to cursor to run.
Ctrl + Alt + R and Ctrl + Alt + E both work fine.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Vivek-Prakash-US Thank you for raising the issue.

QA notes:
1) Works in RStudio Desktop 1.3.842 on MacOS 10.15.4.
2) Works in RStudio Server 1.3.799 on Red Hat 7.8 using Safari 13.1
3) Need to testing RStudio Desktop on Windows 10. Check for 1.2 regression.

**Comment by ronblum** [comment]
@Vivek-Prakash-US Is this still an issue in the latest preview or dailies? I've tried it with a couple of versions on Windows 10,  but I can't reproduce the issue.

**Comment by Vivek-Prakash-US** [comment]
@ronblum I downloaded 1.3.905 this morning and the keyboard shortcuts are working fine. Thanks!

**Comment by Vivek-Prakash-US** [comment]
@ronblum I downloaded 1.3.905 this morning and all the keyboard shortcuts seem to be working fine. Thanks!

**Comment by ronblum** [comment]
@Vivek-Prakash-US Good to know, thank you for letting us know!
