### ISSUE TITLE
Keyboard invocation of main menu doesn't restore focus when menu closed

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6197]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.821
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- In RStudio server, observe where keyboard focus is located (e.g. Console) then use <kbd>Ctrl+Opt+F</kbd> for Mac or <kbd>Alt+Shift+F</kbd> for Win/Linux to focus the File menu
- Right/left arrow keys (optionally) to view other menus
- Exit menu in a variety of ways, including:
    - Change your mind and hit <kbd>Esc</kbd> until nothing is highlighted in menubar
    - Select a command from the menus (for example, one that brings up a dialog box such as Help / About, then close that dialog box)
    - While menus are showing, use a keyboard shortcut to invoke a command

### Describe the problem in detail
- When done using the menu (or a dialog box invoked from the menus) focus doesn't return to where it was before bringing up the menu with keyboard shortcut

### Describe the behavior you expected
- Focus should go back to where it was before menu bar was activated
- If the menu is used to trigger a command that brings up a dialog box, then after that dialog box is done focus should go back to where it was before the menu was brought up (unless the dialog box itself sets focus somewhere else)
- If you use the Tab or Shift+Tab key while menu is displayed, it should NOT restore focus to the previous location but instead move through the page's tab order

**Comment by gtritchie** [comment]
Investigating this for possible inclusion in 1.4. Would be a big win for keyboard-only users (including screen reader users).

**Comment by kfeinauer** [comment]
Verified fixed on RSP 1.4.940-1
