### ISSUE TITLE
Relaunch jobs from jobs pane

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#6198]
The use case for this may not be very wide, but for certain background jobs (Shiny and Plumber come to mind) it would be nice to have a way of restarting the job directly from the jobs pane after it's been stopped. Maybe an icon next to completed jobs that would start the job again with the same settings.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/5548.
