### ISSUE TITLE
Intermittent failure to load external window satellites

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6201]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.776-1 
    OS Version      : MacOS

### Steps to reproduce the problem

We do not have exact repro steps, but lots of users are seeing this hang when opening external satellite windows (such as the Git pane, Shiny, etc.)

We also have one report of this happening in the main RStudio window.

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/470418/74213139-bcfacd00-4c4c-11ea-8887-760fa6e2b18e.png)

![image](https://user-images.githubusercontent.com/470418/74213199-0fd48480-4c4d-11ea-86e1-e2145b1ab587.png)

### Describe the behavior you expected

Window opens successfully.

Some notes from users:

> Have been using RDP with 1.3.779-1 lately and have seen the "Git" pane hang indefinitely (several times). It seems that restarting R has no effect, but restarting the RStudio session resolves.

> I have seen this many times as well running 1.3. I believe it might be related to when I switch networks (e.g. from wifi to 3G) while the IDE is still open

> Horribly vague problem report. But after conf, I upgraded (to 1.3.776) and when I try to view the Git popup pane, I’m seeing this quite regularly, whereas I had not experienced this before. So far, quitting RStudio in the affected project and then restarting it there seems to solve it, in case that provides some data.

> I’ve found myself recently getting into an odd state with the latest daily builds for RDP on MacOS. The session won’t load and I get a screen that looks like this. I’ve also attached what I see in the DevTools console when this is happening. This doesn’t happen all the time, but every now and again it does. I haven’t been able to figure out a specific reprex.

**Comment by colearendt** [comment]
Just hit this after running `devtools::document()` on a package, which regenerated / modified several files (~10-15?). Then I clicked `Commit` to look at the file diff. Not sure if that was related or if the issue was already pre-existing 😬

**Comment by jmcphers** [comment]
@colearendt Have you seen this with the latest preview? 1.3.842-1:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by Deleetdk** [comment]
I have this bug in git menus (diff, commit), running Version 1.3.845 on Linux Mint (19.3). Does not always happen, not sure why.

**Comment by jmcphers** [comment]
We think that this is fixed in build 873, currently available as a daily. If anyone affected would like to upgrade and let us know if this is indeed the case we'd appreciate it.

https://dailies.rstudio.com/

**Comment by jmcphers** [comment]
No reports in builds > 873, so cautiously optimistic that this is fixed. We will reopen if we get any reports.

**Comment by jmcphers** [comment]
We now have reports in build 878.

**Comment by kevinushey** [comment]
My suspicion is that this may be related to this change:

https://github.com/rstudio/rstudio/commit/9a0490a32968dccede399c6eea6917e4e1e72234#diff-e6f918ab023e7f96c96f0e08150c2e80R70

The documentation at https://doc.qt.io/qt-5/qwebengineprofile.html#QWebEngineProfile-1 states:

> The storage name must be unique.

However, we are using the same profile name across every web page used by RStudio. My suspicion is that this causes, in rare cases, corruption of the on-disk cache of web resources if multiple pages are loaded at the same time (and so try to read or write to the cache at the same time).

I can reproduce the cache error fairly consistently if I load the Git Review Changes window from separate RStudio instances at the exact same time. I also see some errors logged in the terminal:

```
$ build && ./rstudio-dev
[2/2] Linking CXX executable desktop/RStudio.app/Contents/MacOS/RStudio
Using the same data path for profile, may corrupt the data.
Using the same data path for profile, may corrupt the data.
[2203:87811:0303/170921.505639:ERROR:backend_impl.cc(1065)] Critical error found -8
[2280:130819:0303/170921.689148:ERROR:entry_impl.cc(1065)] No file for 8000002f
[2280:130819:0303/170921.690127:ERROR:entry_impl.cc(1065)] No file for 80000030
```

which I suspect are internal Chromium errors re: an inability to read the cache.

@kfeinauer, it looks like you made this change. Do you recall why it was needed?

**Comment by kfeinauer** [comment]
@kevinushey I made this change so that I could load the same profile from disk on every startup. Effectively, this was so that sign in cookies for RDP->RSP would be loaded on subsequent launches of the IDE. Without this, the cookie store is lost, meaning the "Stay Signed In" feature doesn't work.

That's a pretty minor feature (and we use a separate mechanism for ensuring that new windows within the same desktop session maintain the sign in cookies), so if this really seems to be the culprit we could just back out the named profile change.

**Comment by jmcphers** [comment]
Not sure if it's related, but I have seen these errors at the console when running two instances at once (dev only):

```
ERROR:backend_impl.cc(1065)] Critical error found -8
Using the same data path for profile, may corrupt the data.

ERROR:connection.cc(1862)] Cookie sqlite error 1, errno 0: cannot start a transaction within a transaction, sql: BEGIN TRANSACTION
```

**Comment by jmcphers** [comment]
@kfeinauer How difficult would it be to load the default profile at startup for the very first (and likely only) instance of RSP, but to skip if the user opens multiple instances? This is similar to what we do today for e.g. projects -- a project can have only one set of source tabs persisted, so if you open a new project session while you already have one running, you don't get a source tabs.

![image](https://user-images.githubusercontent.com/470418/75900399-b5fd4f80-5df1-11ea-89e0-bd66bf0b9c0f.png)

**Comment by kfeinauer** [comment]
@jmcphers I think that will be overly difficult for little benefit. We'd have to add a system wide locking mechanism (like a file lock) to make sure that only one instance of the desktop application can use the profile. That allows users to have their cookies for their first session, but not their subsequent, which will lead to confusion about why it "sometimes works, sometimes doesn't".

**Comment by kevinushey** [comment]
We might be able to allow a shared cookie store but disallow sharing of other cacheable web resources.

**Comment by kfeinauer** [comment]
Spoke with @kevinushey and we think this may just mean we need to only use one `QWebEngineProfile` per process for all pages. He is going to test this theory out.

**Comment by jmcphers** [comment]
We think #6401 fixes this.
