### ISSUE TITLE
.rmd files keeps on crashing error: option error has null value

### ISSUE THREAD

**Issue by Ayeshasaeedhaq** [rstudio/rstudio#6212]
### System details

    RStudio Edition : 
    RStudio Version : 1.1.453
    OS Version      : 
    R Version       : 3.6

### Steps to reproduce the problem
Open a new rmd file and run any line of code. 
### Describe the problem in detail
My rmd file keeps on crashing/giving this fatal error
### Describe the behavior you expected
I have been running my rmd file for months now, but now suddenly it has started to crash. 

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [Y ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![image](https://user-images.githubusercontent.com/14228295/74352499-3940fd80-4d7e-11ea-951b-a22f70d6020a.png)

**Comment by kevinushey** [comment]
You need to update RStudio to v1.2, or use an older version of R.
