### ISSUE TITLE
warning related to new monitoring ignore list

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6215]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.827
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- I'm using a dev environment (rstudio server on mac).
- Start the rsession in terminal, connect in browser

### Describe the problem in detail
- See this in terminal:

12 Feb 2020 19:31:51 [rsession-gary] ERROR jsonrpc error 8 (Parameter missing) [description: missing default value for preference 'file_monitor_ignored_components']; OCCURRED AT T rstudio::session::prefs::Preferences::readPref(const std::string &) [T = rstudio::core::json::Array] src/cpp/session/prefs/UserPrefValues.cpp:68; LOGGED FROM: T rstudio::session::prefs::Preferences::readPref(const std::string &) [T = rstudio::core::json::Array] src/cpp/session/prefs/UserPrefValues.cpp:71

### Describe the behavior you expected
No error in routine use.

Should this (in `user-prefs-schema.json`):
```
        "file_monitor_ignored_components": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "List of path components; file monitor will ignore paths containing one or more of these components."
        }
```
be changed to this?

```
        "file_monitor_ignored_components": {
            "type": "array",
            "default": [],
            "description": "List of path components; file monitor will ignore paths containing one or more of these components."
        }
```

**Comment by kevinushey** [comment]
That looks correct to me.
