### ISSUE TITLE
 introduce quotes in install.packages auto suggestion

### ISSUE THREAD

**Issue by nambisra** [rstudio/rstudio#6219]
for installing a package we give command as install.packages("PackageName")...currently when we type install.pac we get suggestion for various commands, when we click on install.packages we get install.packages()..it would be better if get install.packages("") and the cursor in between the quotes. this way we can improve on "ease of navigation" feature.

**Comment by ronblum** [comment]
@nambisra Thank you for the suggestion! While this would help when installing a single package by name, there are other ways that the `install.packages()` is called that would require getting rid of the quotes. For example, one can load multiple packages at once, e.g. `install.packages(c("dplyr", "caret"))`. In this case introducing the quotes from the start would be a hinderance, hence their not included by default. But thank you for the observation!
