### ISSUE TITLE
Visually indicate which pane has focus

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6225]
Having the IDE "know" which pane is currently focused, would allow visually indicating the active pane in some fashion (maybe via changing the color of it's tab?).

Would also open up possibility for commands such as "Minimize/Zoom etc. Current Pane" instead of just having separate commands (and shortcuts) for each pane.

Somewhat related to #5652 and #5775

**Comment by kfeinauer** [comment]
Verified working 1.4.1069.
