### ISSUE TITLE
Create chunk with shortcut (ctrl+alt+i) and then paste (ctrl+v) causes Rstudio to become unresponsive.

### ISSUE THREAD

**Issue by m1kejay** [rstudio/rstudio#6226]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.820 (Bug happens with 1.2.x too)
    OS Version      :  Windows 10
    R Version       : 3.5.1

### Steps to reproduce the problem
1) Create a new .Rmd from the menu (I use the little icon, but both 'work')
2) Click OK (all default)
3) Go to line 29
4) press ctrl+alt+i
5) type:
```
blah %>%
  mutate(blah = blah) %>%
  filter(x != y)
```
6) Select the code in step 5 with mouse
7) Press ctrl + c
8) Click line 35
9) Press ctrl+alt+i
10) Press ctrl + v.

I originally posted about this bug here: https://community.rstudio.com/t/create-chunk-with-shortcut-ctrl-alt-i-and-then-paste-ctrl-v-causes-rstudio-to-freeze/52849/3

### Describe the problem in detail
After following the above steps, the code does not get copied and RStudio becomes unresponsive in ~ 75% of cases. If it doesn't freeze, repeating steps 9 and 10 eventually causes the problem to occur. Rstudio doesn't freeze/crash in the traditional sense (i.e. white screen/unexpected closing). Instead, the cursor is still present and flashing, and it all looks normal, but I can no longer type or engage with the gui.

This bug seems independent of RStudio versions or R.

### Describe the behavior you expected
I expect the code I copied in step 7 to be pasted into a new chunk in step 10.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by andresrcs** [comment]
I can confirm this issue

> RStudio Edition : Desktop
> RStudio Version : 1.3.776
> OS Version      :  Windows 10 pro x64 build (18363)
> R Version       : 3.6.2

**Comment by gregleleu** [comment]
Also the case on Mac

> RStudio Edition : Desktop
> RStudio Version : 1.3.821
> OS Version : Catalina 10.15.2
> R Version : 3.6.2

**Comment by gregleleu** [comment]
Same as #6210 ?

**Comment by kevinushey** [comment]
Looks like we're getting stuck in a JS infinite loop here:

<img width="471" alt="Screen Shot 2020-02-13 at 10 09 21 PM" src="https://user-images.githubusercontent.com/1976582/74506048-88398080-4ead-11ea-87e5-d90aeaec4e99.png">

For some reason, `w.$oldWidget` and `w` are the same thing, so this loop never exits.

Call stack:

<img width="541" alt="Screen Shot 2020-02-13 at 10 10 41 PM" src="https://user-images.githubusercontent.com/1976582/74506119-ba4ae280-4ead-11ea-98dc-dd132eaa7077.png">
