### ISSUE TITLE
Refresh open files after a global replace

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#6229]
This issue stems from a post on the community forums: https://community.rstudio.com/t/r-studio-version-1-3-820-global-find-replace-does-not-work/52683

### System details

    RStudio Edition : All
    RStudio Version :  v1.3.* 

### Steps to reproduce the problem

Open a file in RStudio. Perform a global find and replace for a word in the file. Although the file has changed outside of RStudio, the IDE does not reflect the change or indicate that there are now unsaved changes (reverting the replace) in the file.

### Describe the problem in detail

After performing a global replace we are not refreshing the currently open files to display the new results. This could lead to confusion when a user has multiple files open and performs a replace across them. It is currently very easy for changes to be lost.

### Describe the behavior you expected

When an open file is modified by a replace operation and doesn't have unsaved changes, refresh the file's buffer so the changes are displayed.

**Comment by armenic** [comment]
Dear developers,
Here is the GIF showing the issue and you can see that even close/open of file or R Studio does not help. Thanks for your time and dedication
![Video_2020-02-14_020138](https://user-images.githubusercontent.com/7897325/74492715-145c9f80-4ed0-11ea-8c32-1767175b6f2c.gif)
.

**Comment by melissa-barca** [comment]
Thanks for the gif @armenic, I was able to reproduce the issue in Windows and have opened PR #6235 with a fix. It should be in the daily build soon.

**Comment by melissa-barca** [comment]
After further research, the original description in this issue is not accurate. The files will be refreshed, though in windows this is briefly delayed and in the case of macos this won't happen until the user clicks into the file. It would be nice to have this happen automatically after a replace but it no longer needs to be a 1.3 bug. I'm closing this out and will open an enhancement.
