### ISSUE TITLE
Find in Files "search these files" option doesn't work (1.3.820 preview edition only)

### ISSUE THREAD

**Issue by jonathan-g** [rstudio/rstudio#6230]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Preview 1.3.820 "Middlemist Red" (bb7abc25, 2020-02-07) for Unknown OS
    OS Version      : Windows 10
    R Version       : 3.6.2

### Steps to reproduce the problem

Open "Find in Files" and select an option for "Search these files"

### Describe the problem in detail

If I choose any other option than "All Files" in "Search these files", Find in Files restores the option to "All Files" and searches all files.

This only happens with the preview edition. It does not happen with the current release.

### Describe the behavior you expected
I expect to be able to choose other search options.

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports. 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Hi @jonathan-g I believe this issue was fixed under PR #6195 and is now part of the daily builds.

**Comment by jmcphers** [comment]
You can get a daily build here: https://dailies.rstudio.com/

**Comment by jonathan-g** [comment]
Hi, @jmcphers and @melissa-barca 

Thanks for your quick attention to this.

I just downloaded and installed the latest daily (1.3.821) for Windows 10 and it shows the same faulty behavior: Whatever choice I make for "Search these files", the dialog returns to "All files".

However, I notice that the latest daily build for Windows is 2020-02-07, which is several days _before_ the PR you reference. There are current (2020-02-14) dailies for MacOS and Ubuntu, but Windows is a week behind.

Maybe something is funny with your daily build pipeline for Windows?

**Comment by ronblum** [comment]
@melissa-barca @jmcphers It's now working in RStudio Desktop 1.3.829 on MacOS. It looks like the MacOS build is from today (2/14/20), but the most recent Windows build, 1.3.821, is from 2/7/20—I think that was before the fix was picked up?

**Comment by gtritchie** [comment]
Yes, we are aware of the stalled Windows builds and are working on.

**Comment by jonathan-g** [comment]
It's all good. I just wanted to check that you were aware of the issues. 

I completely get that this is beta software and bugs are to be expected.

**Comment by jonathan-g** [comment]
This is to confirm that the latest daily build (1.3.839) fixes this bug for Windows.

**Comment by samssann** [comment]
This is happening again in workbench version:
```
RStudio 2022.07.1+554.pro3 "Spotted Wakerobin" Release (5f2e4a5b43b285f5416728d848ca0fe693662550, 2022-07-23) for Ubuntu Bionic
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47
```

**Comment by melissa-barca** [comment]
Hi @samssann I just tried reproducing based on the steps in the original issue, and I don't see the same behavior being described. When I select a different option for "Search the files", the option doesn't revert to "All Files" - it stays the same and performs the search as expected. Could you file a new issue with a minimal reproducible example of the issue you're experiencing?
