### ISSUE TITLE
Console pane in Safari jumps up when clicking in it before typing anything

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6231]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.799
    OS Version      : Safari on MacOS 10.15.4 beta viewing Red Hat 7.8
    R Version       : 3.6.0

### Steps to reproduce the problem

In Safari:
1. Make sure the console has enough rows in it, such that the pane scrolls. For example, with `version` if the pane is short enough.
2. Click on the source pane.
3. Click back on the console.
    - The display in the pane jumps somewhere higher up, as if the user scrolled up.
4. Type something, e.g. `RStudio.Version()` or anything else really.
    - The display returns to the prompt.
5. Click a little higher up on the console, on previous lines (without scrolling).
    - The display jumps again to earlier lines.

### Describe the problem in detail

The display in the Console pane jumps up, as if scrolling up, when on an empty prompt before typing anything.

![jumping_console](https://user-images.githubusercontent.com/31009952/74547769-a6899580-4f1a-11ea-9971-2f051c9e4d73.gif)

### Describe the behavior you expected

The console display should show the prompt, not the equivalent of scrolling up.

I do not see this issue with Chrome or Firefox, or in RStudio Desktop.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
> I do not see this issue with Chrome or Safari, or in RStudio Desktop.

Did you mean "Chrome or **FireFox**"?

**Comment by gtritchie** [comment]
Is this a regression from 1.2? If not, don't think it meets the bar for 1.3.

**Comment by ronblum** [comment]
Oops, I meant Firefox, thanks! I edited the original message. I like to include at least one mistake in every issue I file.

It's a regression—everything's fine in RStudio Server 1.2.5033, though it's on Ubuntu 18.04.3. I can switch Red Hat to 1.2, or Ubuntu to 1.3, if you think the OS could be a factor.

**Comment by gtritchie** [comment]
Highly unlikely to be related to the server OS. Not sure this meets the bar even as a regression, but leave it for now so I can take a peek just to see if there's something more nefarious at play.

**Comment by gtritchie** [comment]
Whatever changed was very early in 1.3; repro's with first build **1.3.2**.

**Comment by gtritchie** [comment]
Appears related to the Ace update we took for 1.3 (merged Sept 25, 2018). Built source right before that point and problem isn't exhibited; built right after, and it now happens.

**Comment by gtritchie** [comment]
@kevinushey you said you might have some insights into this? Assigning to you for now.

**Comment by rich-rstudio** [comment]
verified on Firefox and Safari on 1.3.888
