### ISSUE TITLE
Windows and Mac builds are for "Unknown OS"

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6232]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.824
    OS Version      : Windows or MacOS

### Steps to reproduce the problem

1. Open RStudio
2. Go to Help -> About

### Describe the problem in detail

The dialog says that the build is for an "unknown OS".

![image](https://user-images.githubusercontent.com/470418/74554801-375a7400-4f0f-11ea-985a-07ad477d7401.png)

### Describe the behavior you expected

Either name the OS we built for or omit this information (it's not terribly relevant for Mac/Windows builds as they're one size fits all).

**Comment by dfalty** [comment]
Verified fixed 1.3.867
