### ISSUE TITLE
Initial login after RStudio Server restart results in blank screen

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6233]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.799 & 1.2.5033
    OS Version      : Safari on MacOS 10.15.4 pointing at RStudio on Red Hat 7.8 & Ubuntu 18.04.3
    R Version       : 3.6.0

### Steps to reproduce the problem

This isn't the only way to reach this problem, but it's the most consistent.

1. In Safari, log out of RStudio Server
2. In a terminal, restart RStudio Server: `rstudio-server restart`
3. In Safari, go to RStudio Server
4. Log in
    - The result will be a blank screen
5. Reload the page
    - The login page reappears
6. Log in
     - Now login is successful

### Describe the problem in detail

Logging in after restarting RStudio results in a blank screen.

### Describe the behavior you expected

Logging in should always result in the IDE loading. 

This is not a problem in Chrome. It is as problem in 1.2, so this is not a regression in 1.3.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists. **I used 1.3.799**
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
I cannot reproduce this. Perhaps @dfalty or @jmcphers can try as well. I'd also suggest capturing a GIF and uploading it so we can visualize what's happening.

**Comment by kfeinauer** [comment]
Also @ronblum does this occur on RSP, or just open source?

**Comment by ronblum** [comment]
This is now happening to me consistently, without restarting RStudio Server (1.3.842). In addition, I usually have to reload the page and re-log in multiple times.

This is _not_ an issue in the open source version, so I should move this over to the other repo.
