### ISSUE TITLE
type greek latin letters in comment section of R script on the fly

### ISSUE THREAD

**Issue by user63230** [rstudio/rstudio#6243]
I asked this question on SO, [here](https://stackoverflow.com/questions/60207756/how-to-type-greek-latin-letters-in-comment-section-of-r-script-on-the-fly), and it was suggested to post as a feature request. 

SO question:

When I want to write greek/latin letters in a comment section in an R script (not R Markdown), I end up copying and pasting the relevant letters from another source. Is there a way to type these on the fly in a windows operating system?

typical rscript:

```
library(tidyverse)
#comment section
#gamma distribution has two parameters, α and β. Wait time follows Γ(k, λ)
x <- 1:10
```
All references I find are for writing these letters are for putting them in a graph (`expression(beta)`) or in R Markdown (`$\beta$`) which is not what I am after.

I was wondering does anyone know of an addin or how to create a snippet where you could press tab to see a list of all letters and simply click which one you wanted?

----------------------------------------------------------------

As you can see in the link, it was suggested that this may be possible with an addin where you could have a shortcut to have a popup window where you could select various letters quickly but maybe this could be done directly in RStudio? Or a tab completion style function may work too. Thanks

**Comment by jmcphers** [comment]
Yes, you can type these on Windows using alt codes (in any application).

https://www.alt-codes.net/
