### ISSUE TITLE
RStudio failed to start, core dumped error

### ISSUE THREAD

**Issue by bhvieira** [rstudio/rstudio#6247]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version :  `rstudio-1.3.820 (preview)` (previously on `rstudio-1.2.5001`and `rstudio-1.2.5033` as well)
    OS Version      :  Ubuntu 18.04.4 LTS
    R Version       :  R version 3.4.4 (2018-03-15) -- "Someone to Lean On"

### Steps to reproduce the problem

```
wget https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.3.820-amd64.deb
sudo gdebi rstudio-1.3.820-amd64.deb
rstudio
```

### Describe the problem in detail

RStudio worked before on this machine. All of sudden it stopped working, not sure if following packages updates or not. I've followed similar issues but couldn't find an answer that worked on my case.

Running this:

`QT_DEBUG_PLUGINS=1 /usr/lib/rstudio/bin/rstudio`

Dumps this stacktrace.

> QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/rstudio/plugins/platforms" ...
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqeglfs.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqeglfs.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "eglfs"
>         ]
>     },
>     "archreq": 0,
>     "className": "QEglFSIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("eglfs")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqlinuxfb.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqlinuxfb.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "linuxfb"
>         ]
>     },
>     "archreq": 0,
>     "className": "QLinuxFbIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("linuxfb")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqminimal.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqminimal.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "minimal"
>         ]
>     },
>     "archreq": 0,
>     "className": "QMinimalIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("minimal")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqminimalegl.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqminimalegl.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "minimalegl"
>         ]
>     },
>     "archreq": 0,
>     "className": "QMinimalEglIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("minimalegl")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqoffscreen.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqoffscreen.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "offscreen"
>         ]
>     },
>     "archreq": 0,
>     "className": "QOffscreenIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("offscreen")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqvnc.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqvnc.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "vnc"
>         ]
>     },
>     "archreq": 0,
>     "className": "QVncIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("vnc")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqwayland-egl.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqwayland-egl.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland-egl"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandEglPlatformIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("wayland-egl")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqwayland-generic.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqwayland-generic.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("wayland")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqwayland-xcomposite-egl.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqwayland-xcomposite-egl.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland-xcomposite-egl"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandXCompositeEglPlatformIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("wayland-xcomposite-egl")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqwayland-xcomposite-glx.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqwayland-xcomposite-glx.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland-xcomposite-glx"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandXCompositeGlxPlatformIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("wayland-xcomposite-glx")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/rstudio/plugins/platforms/libqxcb.so"
> Found metadata in lib /usr/lib/rstudio/plugins/platforms/libqxcb.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "xcb"
>         ]
>     },
>     "archreq": 0,
>     "className": "QXcbIntegrationPlugin",
>     "debug": false,
>     "version": 330752
> }
> 
> 
> Got keys from plugin meta data ("xcb")
> QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/rstudio/bin/platforms" ...
> loaded library "/usr/lib/rstudio/plugins/platforms/libqxcb.so"
> qt.qpa.xcb: could not connect to display
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
> 
> Abortado (imagem do núcleo gravada)
> 

### Describe the behavior you expected

I expected it to keep running on my machine 😄 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Sorry, I don't have a great idea of what could be causing this. I would start by searching for:

> qt.qpa.xcb: could not connect to display

and see if you find any other people bumping into similar problems. (Perhaps the issue occurred after your window display manager was updated / changed?)

**Comment by bhvieira** [comment]
I've found several people with this issue on Stackoverflow or elsewhere, but all the things they said worked for them didn't work for me, unfortunately, even the stuff at #4610

- https://stackoverflow.com/questions/56638781/rstudio-is-not-running-on-ubuntu-16-04-qt-qpa-xcb-could-not-connect-to-displa
- https://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without
- https://stackoverflow.com/questions/33051790/could-not-find-or-load-the-qt-platform-plugin-xcb

**Comment by bhvieira** [comment]
> (Perhaps the issue occurred after your window display manager was updated / changed?)

No, that's not it, sadly. I can't really say if other updates occured at the time, specially with drivers for NVidia. I might check that too,

**Comment by ferroao** [comment]
https://github.com/rstudio/rstudio/issues/4610#issuecomment-592117027

**Comment by bhvieira** [comment]
@ferroao thanks for the heads up. I thought about the LD_LIBRARY_PATH thing. Unfortunately that machine has the Matlab Compiler installed, which required messing with the LD_LIBRARY_PATH, which makes me uncomfortable since that always breaks other stuff. Due to that the first thing I did before reinstalling everything related to rstudio and lqt5 was to remove the MCR stuff from that path, to no avail.

The funny thing is that it worked fine before.

**Comment by ferroao** [comment]
Did you see my post in askubuntu?

**Comment by bhvieira** [comment]
Saw it, yeah. I'll try it and report back when I have the time (this machine is remote)

**Comment by jmcphers** [comment]
It's been a couple months, so closing -- but please feel free to reopen when you report back!
