### ISSUE TITLE
Text input boxes do not respect all system-wide cursor-blinking settings

### ISSUE THREAD

**Issue by khvorov45** [rstudio/rstudio#6250]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.2

### Steps to reproduce the problem

1. System settings -> Universal Access -> Cursor Blinking OFF

2. RStudio -> Tools -> Global Options -> Code -> Blinking Cursor OFF

3. Relauch Rstudio and observe cursor behaviour in text input boxes including the "Help", "Packages" and "Environment" panes search bars - the cursor will still be blinking with speed determined by the "Speed" slider in system settings.

### Describe the problem in detail

There are two system settings that control cursor blinking - speed and ON/OFF switch. Rstudio text input boxes respond to speed but not to the ON/OFF switch.

### Describe the behavior you expected

I expected the cursor to not blink in the text boxes when both RStudio's and the system's "blinking cursor" is turned off.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Most likely a web-browser issue (we use Chromium) but need to test and confirm. I did test on Windows where Chrome doesn't obey the similar Windows settings; haven't tried Linux yet.

**Comment by gtritchie** [comment]
See also: #4294

**Comment by ronblum** [comment]
I was able to reproduce this in Ubuntu 18.04.3, though that seems to be a problem not limited to RStudio.
