### ISSUE TITLE
Run Selected Line runs entire chunk

### ISSUE THREAD

**Issue by kcarnold** [rstudio/rstudio#6256]
In R chunks, Ctrl-Enter ("Run Selected Line(s)") runs only the current line, and the RStudio interface shows a green bar on the left next to that line to indicate so much. But in Python chunks, RStudio also shows that green bar on only the current line, but it actually runs the whole chunk.

I've seen this behavior on both RStudio 1.2 and 1.3 preview.

**Comment by mikebessuille** [comment]
UI bug - the UI indicates you are running just the line, but in reality the whole chunk is executed.

**Comment by melissa-barca** [comment]
Verified in 1.4.1017
