### ISSUE TITLE
NVDA in FireFox not reading correct characters in editor or console

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6257]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.845
    OS Version      : Windows FireFox with NVDA 2019.3.1
    R Version       : any

### Steps to reproduce the problem
- Load RStudio Server in FireFox with NVDA running
- Ctrl+2 to ensure focus in console
- Type abcdefg
- Use left / right arrows to move through line

### Describe the problem in detail
- NVDA reads the same character over and over instead of the focused character
- the actual character it gets stuck on seems to vary, but haven't figured out the pattern

### Describe the behavior you expected
- Must read the focused character

### Other details
- Same problem happens in text editor
- Both scenarios use Ace, and this problem also reproduces in the Ace test page, so isn't RStudio specific
- Does work correctly with Chrome instead of FireFox
- See also #6008 for similar problems with Safari / VoiceOver on Mac
- Found by @jooyoungseo

**Comment by gtritchie** [comment]
@jooyoungseo This is no longer happening for me with FireFox 77.0.1 and NVDA 2020.1.

**Comment by jooyoungseo** [comment]
Yes, I have also confirmed that this issue has been resolved (tested with RStudio Server v1.3.959).
