### ISSUE TITLE
can't scroll to bottom of R Markdown document with many outputs

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6261]
https://community.rstudio.com/t/scrolling-problem-in-1-3-820/52751

---

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : v1.3.846
    OS Version      : macOS Catalina 10.15.3
    R Version       : R version 3.6.2 Patched (2020-02-04 r77774)

### Steps to reproduce the problem

Create an R Markdown document with the contents:

`````
```{r}
mtcars
```

```{r}
mtcars
```

```{r}
mtcars
```
`````

Then, execute Run All Chunks.

### Describe the problem in detail

After the chunks have been executed, you will no longer be able to scroll to the bottom of the document.

![Screen Shot 2020-02-18 at 3 09 06 PM](https://user-images.githubusercontent.com/1976582/74786028-9d712f00-5260-11ea-84ff-d3fd2c48f923.png)

Note that the cursor is currently on the 15th row, but is not visible and you cannot scroll the cursor into view.

### Describe the behavior you expected

No issue scrolling to bottom.

**Comment by kevinushey** [comment]
Caused by this Ace patch:

https://github.com/rstudio/rstudio-ace/commit/7d1d7da65f04cb279a87b96d81d01e1c8a226e94

That change fixes an issue where the caret is placed at the wrong position when clicking in a document that contains HTML widgets, but unfortunately causes this regression. I'll revisit and see if there's a better fix.

**Comment by dfalty** [comment]
Verified fixed 1.3.867
