### ISSUE TITLE
Restarts

### ISSUE THREAD

**Issue by AdrianAntico** [rstudio/rstudio#6266]
Is there a way to flush the entire RStudio console when I restart a session from the IDE? I find myself pressing ctrl + shift + F10 four or five times to restart so when I install a package it will complete without an error telling me the library is loaded.

**Comment by ronblum** [comment]
@AdrianAntico If I understand correctly, CTRL+L should do what you're looking for—clearing out the console. If this isn't what you want, then please let us know. Thanks!

**Comment by AdrianAntico** [comment]
@ronblum Sorry, had to write that up quickly last night. So when I go to install a package with rcpp as a import on their description, I typically have to restart RStudio to get it to install. However, I've been finding that I have to restart RStudio multiple times before I can get the package to install and even sometimes that doesn't work. So I'll have to go to my R folder, delete the 00LOCK__ file, restart again, and then try installing again. 

Do you know why that happens? I would think that restarting would do the trick but it seems like when I restart, RStudio tries to hold onto the environment to some extent and my guess is that is what causes this issue. 

I can absolutely get the package installed but I'd love it if I didn't have to go through the above process every time I reinstall a package with Rcpp dependencies.

Thanks for your help!
