### ISSUE TITLE
IntelliPipe: Code suggestions for functions based on variable type on LHS

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/rstudio#6269]
## Summary

Exploring the possibility of function suggestions based on the LHS of a pipe.

## Motivation

RStudio and the tidyverse have made enormous advances in making R programming accessible to everybody. When teaching R to new users, I frequently see people struggle with questions along the lines of

> "What can I do [with this object] now?"

This is understandable. People coming from GUI tools such as Microsoft Excel are used to seeing all the options available to them in the form of buttons. This makes choices more obvious than "talking to R".

## Related solutions

Primarily object oriented scripting languages such as python have solved this to an extend in some IDEs with IntelliSense [e.g. VS Code](https://code.visualstudio.com/docs/editor/intellisense) and RStudio offers autocompletion for the available methods of an object as well:

![image](https://user-images.githubusercontent.com/17450586/74956702-ccc1a080-5406-11ea-934a-ecff6a8ca957.png)

However, Rs workflow is much more functional by nature, especially with the advent of the pipe `%>%`. For inspiration, let us turn to the purely functional language Haskell. They tackled the issue of discoverability with a search API called "Hoogle", that lets you find functions based on type signatures. For example, If I need a function that takes a function from a type `a` to a type `b`, and a list of `a`s (`[a]`) and returns a list of `b`s (`[b]`), I find the `map` function:

![](https://user-images.githubusercontent.com/17450586/74957255-959fbf00-5407-11ea-86a5-3b029edfea76.png)
(Source: https://hoogle.haskell.org/?hoogle=(a%20-%3E%20b)%20-%3E%20%5Ba%5D%20-%3E%20%5Bb%5D)

## Possibilities in R and RStudio

But R is not a statically typed language. While this means, that we can not prevent a user from passing a vector to a function that expects a tibble, we might be able to guide them nonetheless. It should, in theory, be possible to set up an optional type system, for example with `roxygen` comments. This would then serve as a basis for linters and autocompletion.
Additionally, for 

Wouldn't it be cool, if we could fill this void?

![image](https://user-images.githubusercontent.com/17450586/74958435-3a6ecc00-5409-11ea-97b2-3a6aa4309e90.png)

A more straightforward first step is to tackle objects with methods associated with them. For example: This

``` r
model <- lm(mpg ~ disp, data = mtcars)
methods(class = class(model))
#>  [1] add1           alias          anova          case.names     coerce        
#>  [6] ...     
```
could serve as the input to populate the autocompletion for

```
model %>% 
```

Let me know what you think! If you think that it is possible, I would be happy to dive in and make it happen.

Keep up the great work and everything you do for the community :)

**Comment by kevinushey** [comment]
Thank you for the thoughtful proposal!

I like the idea of the first step -- that is, providing a set of "default" completions when we can reasonably infer the set of functions most appropriate in that context.

The more ambitious proposals would likely take some more time to accomplish, and we'd want to be sure there is an appetite in the community for the associated steps in annotating functions / variables in a way that RStudio (or other R front-ends) could use to form smarter completions.

As an aside --  some work has been done in the [completeme](https://github.com/jimhester/completeme) package around the registration and usage of custom code completers; similarly, with type annotation in the [types](https://github.com/jimhester/types) package. There's also the [languageserver](https://github.com/REditorSupport/languageserver) package, supporting the language server protocol for autocompletion in R.

One hope is that, if a smart-enough completion system were to be implemented separately as e.g. part of an R package, then RStudio could simply delegate its completion work to that package.
