### ISSUE TITLE
Source only function not whole file to activate breakpoints after function source change

### ISSUE THREAD

**Issue by SamoPP** [rstudio/rstudio#6272]
I often have functions and code calling the functions with data management in a single R script while I am prototyping/developing functions. Somehow, sourcing only a function (after I update the code of the function) does not activate the breakpoint. Instead, in order to activate the breakpoint the whole R file must be sourced again, meaning that all the code and data management/reading/scrapping, model fitting (which are very lengthy tasks) needs to be performed. In StatET (R plugin for Eclipse) I can only source the function and breakpoints are valid an active after the source of a function has been changed. It would be beneficial that RStudio would support this.

**Comment by ronblum** [comment]
@SamoPP Thank you for the enhancement request, and giving us a reference point is helpful. We'll review this as we continue developing RStudio.

**Comment by jmcphers** [comment]
This is because "sourcing only a function" does not create source references (in the way that RStudio uses them). We could probably fix this by attaching source references and replaying breakpoints when a function is introduced or replaced in the global environment.
