### ISSUE TITLE
dependency manager does not update packages pane after install

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6274]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : v1.3.851
    OS Version      : macOS Catalina 10.15.3
    R Version       : R version 3.6.2 Patched (2020-02-04 r77774)

### Steps to reproduce the problem

Ensure that the `rmarkdown` package is uninstalled, with:

```
remove.packages("rmarkdown")
```

Then, try to create an R Markdown document. You will be prompted to install the `rmarkdown` package; proceed with installation.

### Describe the problem in detail

The Packages pane is not updated to reflect the fact that `rmarkdown` has been installed.

### Describe the behavior you expected

We should ensure the packages pane is updated after installing a package dependency.

**Comment by dfalty** [comment]
Verified fixed 1.3.867
