### ISSUE TITLE
New code chunk shortcut Ctrl-Alt-I doesn't work when Rmd editor is popped out

### ISSUE THREAD

**Issue by ntthung** [rstudio/rstudio#6279]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.8.20
    OS Version      : Windows 10
    R Version       : 3.6.2

### Steps to reproduce the problem
New R notebook, then pop the editor Windows out with the pop-out button, then press Ctrl-Alt-I to add a new code chunk.

### Describe the problem in detail
No code chunk is created. The focus moves to the main Rstudio window. 

Note: Ctrl-Alt-I still works if the Rmd editor is not popped out.

### Describe the behavior you expected
A new code chunk should be inserted in the popped-out Rmd editor

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ntthung Thank you for raising the issue, which I can reproduce. We'll review during our continuing development of RStudio.

This is a regression, as it works correctly in RStudio Desktop 1.2. In addition, it works correctly in RStudio Server.

**Comment by calegs** [comment]
Hi all. Found the same issue and tried Alt+c+i and it works. Hope this can be a workaround, meanwhile.

**Comment by sudeep-santhosh** [comment]
Is this issue resolved, as it still does not work

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2026.04.0-daily+471 on MacOS 26 and Windows 11. Test:
- R Markdown and Quarto
- Source and visual mode
- That chunk remains when popped back in.
