### ISSUE TITLE
[Feature] Fuzzy finder behavior for "Switch to Tab"

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#6280]
Currently, when searching in the "Switch to Tab" searchbox that comes up with `CTRL+Shift+T`, exact matching is applied.

Would it be possible to port the fuzzy search of "Goto File/Function" (`⌃. [period]`) to "Switch to Tab"?

I know that I could directly use "Goto File/Function" instead but would like to search on a subset only in some cases instead of all files downstream.

PS: Typo in the naming of "Goto File/Function"?

**Comment by ronblum** [comment]
@pat-s Thank you for the suggestion. We'll review it as we continue development of RStudio.

Note that the keyboard shortcut for "Switch to Tab" is <kbd>Ctrl-Shift-.</kbd>. Did you by chance modify the shortcut to <kbd>Cmd-T</kbd>? Also, regarding the spelling of "Go to File/Function," good catch! It appears to be correct in the drop down menus, but misspelled in the shortcuts page. Would you mind opening a separate issue for that? Thanks!

**Comment by pat-s** [comment]
> Did you by chance modify the shortcut to Cmd-T?

Oh yeah, I keep forgetting looking up the actual defaults ;)
