### ISSUE TITLE
landmark needed for the div region with id="rstudio_console_output"

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rstudio#6292]
Currently, RStudio Server has six landmark regions for screen readers.

1. Main menu and toolbar navigation
2. Workbench main
3. TabSet1
4. TabSet2
5. Source
6. Console

* Notes: to identify easily landmark region structure with each screen reader, do the following:

  * NVDA: NVDA+F7 and choose type as "Landmarks" (single key navigation is D for next landmark and Shift+D for previous ones.)
  * JAWS: CTRL+JAWS+R (single-key navigation is R for the next landmark; Shift+R for previous ones.)
  * VoiceOver: VO+U (VO indicates CTRL+OPT; choose landmarks by pressing left or right arrow keys when element list pops up)

Given that the most frequently-navigated output area would be console output div container denoted with id="rstudio_console_output", it would be nice if we could assign role = "navigation" and aria-lable = "console output" for the output block for screen-reader to make that as a new easily-navigable landmark.

**Comment by gtritchie** [comment]
This ended up being superseded (backed out) by https://github.com/rstudio/rstudio/pull/6422

Decided we didn't need a landmark for this region now that we have a keyboard shortcut that accomplishes the same thing (Help / Focus / Focus Console Output).
