### ISSUE TITLE
Custom git exec not honored in terminal

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#6295]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.845
    OS Version      : macOS 10.15.3
    R Version       : 3.6.2

### Steps to reproduce the problem

I've set a custom git exec in `~/.config/rstudio/rstudio-prefs.json` via `git_exe_path: /usr/local/bin/git`.

When starting RStudio and checking `which git` I still get `/usr/bin/git` instead of the changed value.
This also applies when making the change via the GUI interface.

Tested with `bash` and `fish`.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by luispuerto** [comment]
Hey! 

Same issue here. I guess that problem is only in the terminal, but we really don't have a way to know if RStudio is using the correct git. 

This is happening also in the current release of RStudio 1.2

**Comment by jmcphers** [comment]
Do you see the Git you requested displayed in Global Options -> Git?

**Comment by luispuerto** [comment]
@jmcphers yeah! the correct git is there, at least for me.

**Comment by jmcphers** [comment]
Great! That's what this option is supposed to do (change the Git exe for RStudio's Git UI).

If you want to change the Git used in RStudio's Terminal, you should use the same mechanism you would use to change the Git used in a shell (e.g., modify PATH in your `.bashrc`).

**Comment by luispuerto** [comment]
@jmcphers eh…. yeah, but in my shell of my computer git is the correct one. 

RStudio is doing something that is not honoring that… on the path of the RStudio terminal are the correct paths, the same ones as in my computer terminal and on my zsh config file. 

And…. the git, in RStudio es the wrong one.

**Comment by luispuerto** [comment]
You can see in this images. 

<img width="710" alt="Screen Shot 2020-02-24 at 20 30 50" src="https://user-images.githubusercontent.com/22882880/75180328-a40e1380-5744-11ea-8fa5-b3e32c752b0a.png">
<img width="681" alt="Screen Shot 2020-02-24 at 20 31 11" src="https://user-images.githubusercontent.com/22882880/75180331-a53f4080-5744-11ea-93a1-efd13f9512f5.png">

**Comment by luispuerto** [comment]
you need to put `usr/local/bin` in your path to make it work

**Comment by pat-s** [comment]
Indeed, thanks @luispuerto!
