### ISSUE TITLE
Print data.frame with Chinese strings column aligned

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#6296]
When a `data.frame` contains Chinese strings, the printing on the RStudio IDE console is not column aligned. This is very inconvenient for non-English users. When the table is large (with multiple columns), we can barely view it in console because the content is misaligned with the header.

A reproducible example can be found below. 

The reason I file this as a "Feature Request" instead of "Bug Reporting" is it happens on R's own console as well. However, if you think this is better to be reported on http://bugs.r-project.org/, please let me know.

### Code

```r
# RStudio Version 1.3.820
df1 <- data.frame(n = 1:2, a = c(123, 4567), b = c('aaa', 'bbbb'), c = c('bd', 'ef'))
df1
df2 <- data.frame(n = 1:2, a = c(123, 4567), b = c('中文字符', '汉语文字等'), c = c('bd', 'ef'))
df2
```

### Screenshot

<img width="779" alt="image" src="https://user-images.githubusercontent.com/8368933/75104824-6fb52d00-5648-11ea-9709-44775084579d.png">

### Session Info

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_1.5.1

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2    fs_1.3.1       glue_1.3.1     Rcpp_1.0.3     rlang_0.4.4   
```

**Comment by kevinushey** [comment]
Interestingly, it is formatted correctly in a terminal session for me (iTerm on macOS):

![Screen Shot 2020-02-24 at 9 40 35 AM](https://user-images.githubusercontent.com/1976582/75176817-bc047980-56e9-11ea-862c-1d332342dbf8.png)

And yet, that same output copy + pasted here into GitHub is misaligned:

```
> df2
  n    a          b  c
1 1  123   中文字符 bd
2 2 4567 汉语文字等 ef
> as_tibble(df2)
# A tibble: 2 x 4
      n     a b          c
  <int> <dbl> <chr>      <chr>
1     1   123 中文字符   bd
2     2  4567 汉语文字等 ef
```

I don't have an answer for why this is the case.

**Comment by shrektan** [comment]
Is it possible due to the font itself?

 As you can see on Terminal one Chinese character's width equals two English letters. In contrast, in RStudio IDE, three Chines character's width equals 5 English letters.

```r
cat('abcdefg\n中文中ab\n')
```

# Terminal macOS

<img width="245" alt="image" src="https://user-images.githubusercontent.com/8368933/75181993-6cba5980-577a-11ea-9fe3-a6e62aff47e1.png">


# RStudio

<img width="217" alt="image" src="https://user-images.githubusercontent.com/8368933/75182006-7348d100-577a-11ea-8c8a-ab614f22c6ee.png">

**Comment by shrektan** [comment]
OK, issue solved... I changed the font to SimHei (a Chinese font) and now it displays ok.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/8368933/75182193-cc186980-577a-11ea-8fef-2487f87b0625.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/8368933/75182490-78f2e680-577b-11ea-9caa-f416ab4a22f1.png">

The only issue is that I really don't like the English letter in a Chinese font...

Is it possible to use an English font while keeping the feature that the width of 1 Chinese Character always equal to 2 English letters?

**Comment by shrektan** [comment]
Another interesting observation is that the Editor Panel aligns both Chinese and English letters well. The misalignment happens only in the console.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/8368933/75213176-4b7e5b00-57c4-11ea-8aaa-e39045d548a7.png">

**Comment by ronblum** [comment]
@shrektan Thank you for filing the issue! Regarding this:
> The only issue is that I really don't like the English letter in Chinese font. Frankly speaking, I can't tolerate a Chinese font since most of the code is English letters.

This sounds like an enhancement request, I think. Would you mind filing a separate issue for it? Thanks!

**Comment by shrektan** [comment]
It’s complicated I’m afraid ... as I said 

> Another interesting observation is that the Editor Panel aligns both Chinese and English letters well. The misalignment happens only in the console.

So I’m not sure the real cause...

**Comment by shrektan** [comment]
Another observation: 

```r
cat('abcdefg\n中文中ab\n')
```

<img width="223" alt="image" src="https://user-images.githubusercontent.com/8368933/75407687-91672a80-594e-11ea-8f35-5428cc049205.png">

In the first two lines, 3 Chinese letters' width equal to 5 English letters. In contrast, even if you copy-paste the same string to the console, you can find that 1 Chinese letters' width equal to 2 English letters.

**Comment by shrektan** [comment]
OK, I see. The reason that code editing panel can display the mixing of Chinese and English correctly is that it sets the `width` for each of the Chinese characters.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/8368933/75412267-ead65600-595c-11ea-8988-6ef6bff4af30.png">


In contrast, the printing on the console panel simply uses the `<pre>` tag and it's not as tailor-tweaked as in the code-editing-panel. 

The root cause I believe is  `monospace` font doesn't support Chinese. And there's no good alternative (SimHei supports Chinese but the English letter style is bad). 

See https://stackoverflow.com/questions/50421855/how-can-i-line-up-english-and-chinese-characters-of-a-monospace-font-for-css

So I'm going to close this issue and file a new feature request.

Thanks!
