### ISSUE TITLE
Terminal not working (specified module not found) on Windows

### ISSUE THREAD

**Issue by arnyeinstein** [rstudio/rstudio#6297]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.3.820
    OS Version      :  Windows 10
    R Version       :  3.6.2

### Steps to reproduce the problem
Starting new terminal

### Describe the problem in detail
Terminal is not working. Only showing a blinking cursor. I had this in the officially released version too (however without blinking cursor). If I close the open terminal and start a new one, a pop-up appears with "The specific module could not be found" and the terminal window  shows "(busy)".

Here is the diagnosis of the terminal
`
Global Terminal Information
---------------------------
Loaded TerminalSessions: 1
Handle: 'A2F9528B' Caption: 'Terminal 1'

Terminal List Count: 1
Handle: 'A2F9528B' Caption: 'Terminal 1' Session Created: true

Current Terminal Session Information
------------------------------------
Caption:     'Terminal 1'
Title:       ''
Cols x Rows  '199 x 32'
Shell:       'Command Prompt'
Handle:      'A2F9528B'
Sequence:    '1'
Restarted:   'false
Busy:        'true'
Exit Code:   'null'
Full screen: 'client=false/server=false'
Zombie:      'false'
Track Env    'false'
Local-echo:  'false'
Working Dir: 'Default'
Interactive: 'Always'
WebSockets:  'true'

Current Terminal Emulator Settings
------------------------------------
bellStyle: sound
cursorStyle: block
fontFamily: "Lucida Console", monospace
fontWeight: normal
fontWeightBold: bold
rendererType: canvas
allowTransparency: false
cancelEvents: false
convertEol: false
cursorBlink: true
disableStdin: false
drawBoldTextInBrightColors: true
macOptionClickForcesSelection: false
macOptionIsMeta: false
rightClickSelectsWord: false
screenReaderMode: false
windowsMode: true
fontSize: 11
letterSpacing: 0
lineHeight: 1
tabStopWidth: 8
scrollback: 1000

System Information
------------------
Desktop:    'true'
Remote:     'false'
Platform:   'Windows'

Connection Information
----------------------
2020/2/23 12:38:13: Connect WebSocket: 'ws://127.0.0.1:7752/terminal/A2F9528B/'
2020/2/23 12:38:13: WebSocket connected
2020/2/23 12:38:13: Disconnected
2020/2/23 12:38:13: WebSocket closed

Local-echo Match Failures
-------------------------
<Not applicable>
`

### Describe the behavior you expected
dos cmd showing

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
The message "specified module could not be found" indicates a missing DLL, as was the case in this community discussion: https://community.rstudio.com/t/blank-unresponsive-terminal-pane-no-cursor/49601

In that case the fix was an OS upgrade, they were using Windows-7. In this case, perhaps a Windows-10 repair and see if that restores whatever DLL(s) have gone missing.

I'll look and see if I can add a more detailed error message to make it easier for troubleshooting this class of problem.

**Comment by hughandersen** [comment]
My RStudio session has the same problem (The specified module not found) after upgrading to the latest version 2022.12.0 Build 353 Elsbeth Geranium.
I have deleted the registry keys as suggested here 
https://answers.microsoft.com/en-us/windows/forum/all/the-error-the-specified-module-could-not-be-found/c7a9232c-4748-47d3-b6c5-58864ea47f24#:~:text=Boot%20your%20computer%20into%20Safe,whether%20the%20problem%20is%20solved. 

and re-booted but the problem remains.

My work laptop is using Windows 10.
Any advice please?
