### ISSUE TITLE
Wrong word highlighted in R Markdown editor during spell checking

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#6298]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.820
    OS Version      : Mac OS 10.14.6
    R Version       : 3.6.2

### Steps to reproduce the problem

- Open the default R Markdown template and three words at the end on three separate lines -- first two with spelling mistakes and the last one not.
- Go to Edit -> Check Spelling and start running through the errors and suggestions.

### Describe the problem in detail

- The spell check dialogue locates the first spelling mistake but the editor highlights the second one and places a green arrow next to it.

<img width="805" alt="Screenshot 2020-02-23 at 22 13 41" src="https://user-images.githubusercontent.com/5965649/75121219-e7577c00-5689-11ea-9659-2b359b092ace.png">

- Same issue with the second spelling mistake.

<img width="795" alt="Screenshot 2020-02-23 at 22 13 53" src="https://user-images.githubusercontent.com/5965649/75121226-f8a08880-5689-11ea-8d01-fe944af7ca45.png">

- When the spell check is complete, the last word in the document remains highlighted.

<img width="951" alt="Screenshot 2020-02-23 at 22 14 08" src="https://user-images.githubusercontent.com/5965649/75121258-27b6fa00-568a-11ea-8df8-f15094848dc5.png">

<img width="833" alt="Screenshot 2020-02-23 at 22 14 18" src="https://user-images.githubusercontent.com/5965649/75121263-2d144480-568a-11ea-9379-6504c76619ba.png">

### Describe the behavior you expected

I expected the incorrectly spelled word to be highlighted in the editor, and I did not expect the correctly spelled word to ever be highlighted.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
We should make sure that this isn't a regression from 1.2 (could be new behavior in the Ace update we took for 1.3)

**Comment by adamconroy** [comment]
I just tested and this is a regression. 1.2 did not even have highlights/arrow annotations at all, it just selected the word. This bug is likely caused but a confluence of changes as the real time spellchecking doesn't directly touch anything related to these forms of annotations. I'm on it.

**Comment by rich-rstudio** [comment]
verified in Version 1.3.897
