### ISSUE TITLE
RStudio freezes when trying to copy paste text/code within Rmarkdown files

### ISSUE THREAD

**Issue by ajabadi** [rstudio/rstudio#6299]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.3.820
    OS Version      : macOS Catalina 10.15
    R Version       : 3.6.2 (2019-12-12)

### Steps to reproduce the problem
Copy a chunk's code in Rmarkdown and try to paste it in another chunk

### Describe the problem in detail
Not always, but frequently enough, when I try to copy-paste within Rmarkdown files, RStudio freezes indefinitely (not responding to any inputs) and I have to force stop it eventually. Not sure if it is RStudio issue or macOS issue.

### Describe the behavior you expected
No freezing

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I believe this is a duplicate of https://github.com/rstudio/rstudio/issues/6226 (fixed in the daily build).

https://dailies.rstudio.com/

**Comment by ajabadi** [comment]
Thanks. I have installed 1.3.842 and the problem still persists.

**Comment by Vidaringa** [comment]
I'm having the same problem.

**Comment by kevinushey** [comment]
Unfortunately, without a reproducible example we cannot help. Given that only a few users are experiencing this issue, it might be some kind of bad interaction with other software running on your machine (e.g. a clipboard manager?)

**Comment by nobaluis** [comment]
I have the same problem, I am using RStudio v 1.25.5042 on Ubuntu 20.04. No matter which Rmarkdown file I open, when I try to copy text / code from another application (browser or some code editor) and paste into RStudio, the IDE freezes momentarily.
