### ISSUE TITLE
Using vim keybindings and saving forces editor from insert to command mode

### ISSUE THREAD

**Issue by rundel** [rstudio/rstudio#6302]
### System details

    RStudio Edition : Desktop / Server
    RStudio Version : 1.3.820
    OS Version      : MacOS 10.15.3 / Ubuntu 19.10
    R Version       : 3.6.2

### Steps to reproduce the problem

* Use the vim keybinding
* Open a script or text file
* Enter insert mode and edit the file
* Save via File menu (to avoid exiting insert mode)
* Editor is forced back to command mode

### Describe the problem in detail

When saving a file in RStudio's editor and using the vim keybindings the mode will be forced from insert into command mode. 

### Describe the behavior you expected

If the file is being saved via `:w` then this isn't an issue since the editor will already be in command mode. If the save action is triggered via the File menu, an auto-save, or `rstudioapi::documentSave` then this can be problematic (particularly for the latter two cases). This came up as an issue for someone trying to use vim keybindings with `livecode` (rundel/livecode#4) which uses `rstudioapi::documentSave` to trigger auto saves. This save behavior happens when file saves are triggered via auto-saves when the editor is idle (Save and write changes option or save on loss of focus).

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rundel** [comment]
After a bit of poking around it seems like the issue is that after each save event it all of the keyboard handlers (vim in this case) are removed and then reattached via `updateKeyboardHandlers` in `AceEditor.java` [code here](https://github.com/rstudio/rstudio/blob/b75cc6d710c3437e0a56a030b6a3fa958564a783/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#L978). 

This clears almost all of the vim state which happens to include the editor mode. It looks like only marks are carried over at the moment but it seems like it should also be possible to carry over the editor mode as well.

Is there a reason to wipe the local vim state after each save?

**Comment by kevinushey** [comment]
> Is there a reason to wipe the local vim state after each save?

This is normally done to ensure that some document-related state is properly changed in the case where (for example) the user has changed the file extension on save, and so a different document mode should now be used for the open document.

I suspect we are doing this over-aggressively; we may be able to skip some of these steps when we see that the editor language will not change on save.

**Comment by rundel** [comment]
I haven't come close to wrapping my brain around the save process code but given the case described above would it not make sense to distinguish between a save and a save as event? The former is what we are dealing with in all of these auto-save use cases. 

Are there other edge cases that I am not considering?
