### ISSUE TITLE
Typo in rstudioDiagnosticsReport() output

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#6307]
### System details

    RStudio Edition : Server open source and Pro
    RStudio Version : Version 1.3.862
    OS Version      :  MacOS 10.14.6
    R Version       : 3.4.4

### Steps to reproduce the problem
1. run rstudioDiagnosticsReport() in console
### Describe the problem in detail
typo in output
> rstudioDiagnosticsReport()
Diagnotics report written to: /home/rich2/rstudio-diagnostics/diagnostics-report.txt
### Describe the behavior you expected
Diagnostics is misspelled

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thank you for catching that!
