### ISSUE TITLE
Request Vertical Scrollbar in Modern Dracula or Colbalt Appearance

### ISSUE THREAD

**Issue by kojolinder** [rstudio/rstudio#6309]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows 10 Pro, Version 10.0.17763 Build 17763
    R Version       : 3.6.2

### Steps to reproduce the problem
Tools > Global Options > Appearance > RStudio Theme : Modern  ;Editor Theme: Dracula
### Describe the problem in detail
When I use Modern RStudio theme, the vertical scrollbar disappears for data frame tabs.   The vertical scrollbar is present for script tabs.  
### Describe the behavior you expected
I expected to see a vertical scrollbar like I see in the Classic RStudio theme. 

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kojolinder Thank you for filing the issue! However, I can't reproduce it on both Windows 10 and MacOS 10.15.4, using `View(mtcars)` and `View(cars)`. Would you mind providing a screen shot? Also, to make sure we're going through the same steps, do you see the issue with these `View`s? And does its happen with any other themes?

**Comment by kojolinder** [comment]
Hi, it seems like when the dataframe row count is large the scroll bar
disappears.  See attachment.  I can view mtcars and cars but their row
counts(<50) are small compared to mine (1000).  In classic mode, the scroll
bar is visible for really large row counts but the background is white.

Thanks for responding
