### ISSUE TITLE
Find in files Ctrl-Shift-F does not pre-fill the selected word when in a pop out window

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#6310]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.842
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.2

### Steps to reproduce the problem
 - Pop out a source window
 - type a word
 - Highlight the word
 - Press Ctrl-Shift-F

### Describe the problem in detail
The pre-filled word is not the highlighted word (for me it is the last-searched word). 

### Describe the behavior you expected
The highlighted word is prefilled.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kendonB Thank you for raising the issue! We'll review as we continue development of RStudio.

Reproducible with Cmd-Shift-F in RStudio Desktop on MacOS 10.15.4, and in addition, the focus shifts back to the main window. In RStudio Server on Red Hat 7.8 using Safari on MacOS 10.15.4, the field is empty; in addition, the Find in Files modal appears behind the popped-out window,
