### ISSUE TITLE
Find in Files: allow excluding folders - especially useful when using renv

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#6311]
I just tried doing a "find in files" in a project that's using `renv` to keep track of dependencies. The find feature is essentially useless because I'm getting 100s of results but only one of them is from my code, whereas the rest are from within the `renv` directory. I literally moved the renv folder, did my search, and moved it back. 

I think it'd be great if there was a better solution :)

Related to https://github.com/rstudio/rstudio/issues/5031

**Comment by jmcphers** [comment]
Also related to https://github.com/rstudio/rstudio/issues/1984.

**Comment by daattali** [comment]
Ah yeah that one covers this. My github search didn't find it:)
