### ISSUE TITLE
MathJax-related JavaScript exception

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6313]
### System details

    RStudio Edition : Server (dev mode server)
    RStudio Version : 1.3.866
    OS Version      : macOS
    R Version       : 3.6.1

### Steps to reproduce the problem
- Build and run RStudio via `ant devmode`, `rserver-dev`
- Start a session
- Look at the terminal where rserver-dev was started

### Describe the problem in detail
- Getting this JavaScript exception (not always, not sure what triggers it)
```
25 Feb 2020 04:26:42 [rserver] ERROR CLIENT EXCEPTION (rsession-gary): TypeError: i is not a function;
http://localhost:8787/mathjax/config/TeX-MML-AM_CHTML.js?rev=2.6.1@15862#56::Init
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@1030#19::Init
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@588#19::COMMAND
http://localhost:8787/mathjax/config/TeX-MML-AM_CHTML.js?rev=2.6.1@31943#56::anonymous
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@3084#19::execute
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@2661#19::cb
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@7293#19::Execute
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@10599#19::ExecuteHooks
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@3084#19::execute
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@2661#19::cb
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@7293#19::Execute
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@9345#19::Post
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@3084#19::execute
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@2661#19::cb
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@8561#19::Process
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@8818#19::call
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@6016#19::WAITEXECUTE
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@2661#19::cb
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@7293#19::Execute
http://localhost:8787/mathjax/MathJax.js?config=TeX-MML-AM_CHTML@15890#19::loadComplete
http://localhost:8787/mathjax/config/TeX-MML-AM_CHTML.js?rev=2.6.1@2855#69::anonymous
Client-ID: ef55fbcc-ccc8-4bf3-a936-fa77bb4748c3
User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
```

### Describe the behavior you expected
- No JavaScript exception

**Comment by gtritchie** [comment]
@jmcphers you did the last mathjax update, so assigning to you. Not sure if anybody else is seeing this, but I do see it on two separate machines (both Macs, if that's a factor).

**Comment by jmcphers** [comment]
I haven't ever been able to reproduce. @gtritchie have you seen it recently?

**Comment by gtritchie** [comment]
Nope, been a long time so seems safe to close.

**Comment by jmcphers** [comment]
Okay, thanks!

**Comment by roboton** [comment]
I'm still seeing this and can reproduce on rstudio-server running on Ubuntu 18.04. It's not a huge issue but can provide more details if needed:

Mar 28 17:19:57 wabox rserver[84440]: ERROR CLIENT EXCEPTION (rsession-xxx): TypeError: i is not a function;|||https://xx.xx/mathjax/config/TeX-MML-AM_CHTML.js?rev=2.6.1#-1::Init|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Init|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::COMMAND|||https://xx.xx/mathjax/config/TeX-MML-AM_CHTML.js?rev=2.6.1#-1::anonymous|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::execute|||com/google/gwt/user/cellview/client/AbstractCellTable.java#849::resources|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Execute|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::ExecuteHooks|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::execute|||com/google/gwt/user/cellview/client/AbstractCellTable.java#849::resources|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Execute|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Post|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::execute|||com/google/gwt/user/cellview/client/AbstractCellTable.java#849::resources|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Process|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::call|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::WAITEXECUTE|||com/google/gwt/user/cellview/client/AbstractCellTable.java#849::resources|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Execute|||https://xx.xx/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::loadComplete|||https://xx.xx/mathjax/config/TeX-MML-AM_CHTML.js?rev=2.6.1#-1::anonymous|||Client-ID: e27624eb-d706-4045-b92d-0fbfa618f199|||User-Agent: Mozilla/5.0 (X11  CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36
