### ISSUE TITLE
display issues

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#6315]
Lately my Rstudio has been having big display issues, I get this kind of screen when scrolling or typing, it comes in and goes away : 

![image](https://user-images.githubusercontent.com/18351714/75268801-463b0380-57f8-11ea-8b70-81cc539b2369.png)

Here's my `sessionInfo()` : 

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] liblog_0.0.0.9000 compiler_3.6.2    tools_3.6.2       packrat_0.5.0 
```

I tried reinstalling Rstudio but the issue remained, I only have this issue with RStudio.
I also tried to update my drivers but nothing changed.

It might have happened after I try to tweak graphic settings to be able to display Rstudio well on some screens, but I don't remember what I did...

Is there a quick fix ? Or could you tell me how to do a complete uninstall/reinstall of Rstudio ? As it seems I didn't get a fresh R studio by doing it the standard way.

**Comment by kevinushey** [comment]
You might try switching to software rendering: https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by moodymudskipper** [comment]
Fantastic! That did the trick. Thanks so much Kevin, it was making my work very uncomfortable. closing then.
