### ISSUE TITLE
Spellchecking in Spanish marks non-ASCII characters as errors

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#6317]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3
    OS Version      : Windows
    R Version       : 3.5.1

### Steps to reproduce the problem
1) Select the Spanish dictionary
2) type Spanish words using non-ASCII characters such as:
`¿Dónde estás?`
3) Observe that the spellchecker marks it as incorrect and tries to correct it as if the accents are invalid.

### Describe the problem in detail
Languages with accented versions of the characters are tricky. Many native speakers even will type the words without the accents due to knowledge/effort level/keyboard being used so the strictness of the dictionary is up to the developer, though often auto-correct is left on and relied on.

Anyway, we should definitely be allowing the correct accented characters. Not sure if I prefer if the source of the bug is typo.js or the dictionary itself but I'll know in a bit.

### Describe the behavior you expected
Accented characters are correctly identified and used in spellchecking.

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible in RStudio Desktop 1.3.842 on MacOS 10.15.4. However, French works:
```
Bonjour, comment allez-vous?
Je pense que l'hôtel ne'est n'est pas ici.
Voici le garçon. Il n'est pas un garcon. 
Je suis désolé, pas desole.
```

![desole](https://user-images.githubusercontent.com/31009952/75281169-c0f62580-57dc-11ea-8051-8b5bf42a3da2.png)

**Comment by adamconroy** [comment]
Yeah just checked and French appears to actually be UTF-8 unlike Spanish's ISO-8859-2. Going to see if there's a simple solution on the loading side but we might need to convert these/find alternatives.

**Comment by adamconroy** [comment]
Unfortunately, due to our infrastructure, dictionaries that are in arbitrary encodings are incompatible with the front-end spellchecker. I have converted all of the dictionaries to UTF-8. Users who have the old versions will want to delete their old directory and then re-download it with `Install more dictionaries...` from the options menu.

**Comment by rich-rstudio** [comment]
verified in Version 1.3.921
