### ISSUE TITLE
Why Cmd+v cannot paste text to the saveras dialog in Rstudio?

### ISSUE THREAD

**Issue by Jieli12** [rstudio/rstudio#6326]
The version of MacOs is Catalina 10.15.2, and Rstudio is  the latest version. When I save the R script as file, Cmd+v can not paste the text into the file name field. However,  I tried right click and chose paste, it worked.  

I also tried Mac build-in apps, Cmd+v works normally. For the third-party apps, I also found MATLAB has the same problem.

Would you please help me figure out this weird problem?

P.S.

Within Rstudio,  Cmd+C, V, X works well. It also works if one copies content into Rstudio from outside. The problem only happens at save-as step.

**Comment by ronblum** [comment]
@Jieli12 Thank you for filing the issue! We'll review it as we continue development of RStudio.

Reproducible in RStudio Desktop 1.3.842 on MacOS 10.15.4. Not an issue in RStudio Server on Red Hat 7.8 with Safari on MacOS.

**Comment by Jieli12** [comment]
@ronblum Thank you for replying me. Hopefully, it will be sovled next Rstudio desktop version.

**Comment by bakaburg1** [comment]
Hello! this is still happening in RStudio "Ghost Orchid" Release (8b9ced18, 2021-11-08) on macOS 12.0.1.
