### ISSUE TITLE
RStudio 1.3: Disable Tutorial Pane

### ISSUE THREAD

**Issue by jtelleriar** [rstudio/rstudio#6329]
Could RStufio 1.3 gain the ability to disable the tutorial pane? Experienced users do not need it!

**Comment by pascaloettli** [comment]
![Screenshot from 2020-02-26 17-29-19](https://user-images.githubusercontent.com/6613954/75326206-8f08c000-58bd-11ea-9104-b7aca3f5cb93.png)

**Comment by jtelleriar** [comment]
When disabling the tutorial pane, it moves from one block to another, you cannot make it not be there (hide it).

**Comment by jtelleriar** [comment]
The same behavior happens with the connection pane: Not everyone needs it or require it

**Comment by pascaloettli** [comment]
So please provide details when you open an issue. No time to guess

**Comment by gtritchie** [comment]
Ideally would behave like the terminal and jobs tabs and have a close [x] and remain closed unless reopened via View menu.

**Comment by jmcphers** [comment]
It's not currently possible to get rid of built-in panes. We're tracking that in https://github.com/rstudio/rstudio/issues/2854.
