### ISSUE TITLE
Error when saving files to UNC network share

### ISSUE THREAD

**Issue by RRLatFlinders** [rstudio/rstudio#6330]
We're encountering an error with R Studio v1.2+ where when attempting to save a file to a UNC network share (in our environment, the Documents, Desktop and some other profile folders are redirected to the users home drive network share). When attempting to save the file, an error dialogue appears 'Confirm Change File Type' asking if 'you are sure that you want to change the type of file so that it is no longer an R script?'. Clicking Yes presents another error message: Error Saving File: The filename, directory name, or volume label syntax is incorrect.

Saving the file by designating the mapped drive letter for the same location instead of the UNC path works correctly.

Tested and confirmed to fail in:
1.2.5033
1.3.842-1 Preview
Fault does not occur in:
1.1.453
Have tested with multiple different versions of R (3.4, 3.5, 3.6). 

Sommone else appears to have encountered the same issue here:
https://community.rstudio.com/t/rstudio-1-2-1335-cant-save-scripts-to-networked-drive/29816

**Comment by kevinushey** [comment]
@RRLatFlinders: Thanks for the bug report! We'd love to get to the bottom of this.

Can you please share a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report)? I'd also be curious to know the full path of the file that you're unable to save, in case it has special characters or something similar (as these have caused problems in the past).

**Comment by RRLatFlinders** [comment]
Hi Kevin,

Attached is the diagnostics report as requested. The file path I'm attempting to save to as a testis:
\\userqr\r\russ0207\Documents\test3.R
None of the file\folder paths I've attempted have had any fancy characters outside of the period for the file extension. Attempting to save the file without a file extension ('test3') produces the same results.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4273067/diagnostics-report.txt)

**Comment by kevinushey** [comment]
Thanks for following up! Unfortunately, nothing stands out in the diagnostics report :-/

One thing I'd ask -- does changing the `R_USER` environment variable globally to point to a local path make a difference? For example, you could try setting it to `C:\Users\<userHomeDir>`.

**Comment by RRLatFlinders** [comment]
Hi Kevin,

Yes, changing the R_USER environment variable to either a local path (tested with C:\users\public\documents\)or a mapped network drive ('U:\documents' which is our mapping for \\userqr\r\russ0207\documents\) works, the error is not produced and the file is saved correctly.

**Comment by kevinushey** [comment]
Tracking this in https://github.com/rstudio/rstudio/issues/6587 now.
