### ISSUE TITLE
Support for use of different dictionaries for one spellchecking

### ISSUE THREAD

**Issue by philgee1981** [rstudio/rstudio#6331]
I oftentimes work with multilingual texts. Examples are quotes in english and its translations in another language (in my case german). It would be great (and a huge advantage compared to other programs) to use several dictionaries for spellchecking at once. 

I know that one problem would be to distinguish paragraphs in the different languages. One approach is to have a primary language and a secondary one. While the regular parts of the document would be in the primary language (and checked regarding spelling in that one), only separate distinct blocks similar to code blocks would be checked in the secondary language. The YAML metadata could be used to specify this primary language. 

To illstrate the feature request here an example (sorry for using two graves for the foreign language block here, could not include them in a code block): 

````
---
title: Different languages in Rmarkdown - example
author: Philipp Giese
date: February 26, 2020
language: english
--- 

This would be a normal english text.

```  {lang=german}
Und das wäre ein deutscher Text. 
```

That would be english again.

````

**Comment by ronblum** [comment]
@philbtcecho Thanks for filing the enhancement. By the way, you can have three graves/tick marks by enclosing them in four of them: ` ```` `. I updated your initial request with this.

**Comment by adamconroy** [comment]
This is actually something I wanted to get in for the realtime update but it didn't quite fit into the architecture. I'm going to put this on the 1.4 milestone as I don't think it'll be a _ton_ of work to get going and would be a very nice feature.
