### ISSUE TITLE
Shiny app window doesn't automatically refresh

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#6332]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.867
    OS Version      : Mac
    R Version       : 3.6.2

### Steps to reproduce the problem

Run the following code to create a very simple shiny app:

```R
ui <- fluidPage("Hello")
server <- function(input, output, session) {}
shinyApp(ui, server)
```

Switch back to the main RStudio instance/console and press escape to quit the shiny app.

Modify the UI and then relaunch the app:

```R
ui <- fluidPage("Goodbye")
shinyApp(ui, server)
```

### Describe the problem in detail

The shiny window displays a greyed out/cancelled app. To get the new instance of the app to show, you have to click the refresh button.

### Describe the behavior you expected

App window should automatically refresh

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you have the Shiny application showing in the Viewer pane, or an external window?

**Comment by hadley** [comment]
External window

**Comment by ronblum** [comment]
Reproduced in RStudio Server 1.3.842 on Red Hat 7.8 using Safari.

**Comment by kevinushey** [comment]
Also fixed via https://github.com/rstudio/rstudio/pull/6338.

**Comment by hadley** [comment]
Thanks!
