### ISSUE TITLE
Connections Pane: connection history corrupted?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6336]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.867
    OS Version      : macOS 10.15.3
    R Version       : 3.6.1

I'm not sure exactly how I got into this state, beyond the fact that at the time I was messing with my `odbc.ini` and `odbcinst.ini` files.

Regardless, when I launch RStudio the Connections pane does not load. There is a JavaScript exception logged:

![Screen Shot 2020-02-26 at 1 11 01 PM](https://user-images.githubusercontent.com/1976582/75388217-71c1fa80-5899-11ea-85c0-fa217147b69b.png)

Diving in deeper, it looks like the connection history database was somehow corrupted:

```
kevinushey@Kevins-MacBook-Pro:~/.rstudio-desktop/monitored/connection_history
$ cat connection-history-database.json
[
    null,
    null
]
```

There are two things we could do here:

1. Find a root cause for how someone could end up with null entries in their connection history database;
2. Drop nulls when reading the set of available / known connections.

**Comment by tyluRp** [comment]
I keep running into this issue when I delete a connection from the pane. After deleting, a NULL pops up in `~/.rstudio-desktop/monitored/connection_history/connection-history-database.json` and I can no longer use the pane.

**Comment by kevinushey** [comment]
@tyluRp -- are you able to reproduce in the latest [daily builds](https://dailies.rstudio.com) of RStudio? This issue should (in theory) be fixed in v1.4; or at least, the issue with `null` entries in the history database should no longer cause this to happen.

**Comment by tyluRp** [comment]
@kevinushey Just downloaded the daily, `Version 1.4.794`. Can no longer reproduce the issue described above however, when I delete a connection, all connections are gone (i.e. the two I created).

**Comment by kevinushey** [comment]
> @kevinushey Just downloaded the daily, `Version 1.4.794`. Can no longer reproduce the issue described above however, when I delete a connection, all connections are gone (i.e. the two I created).
> 
> Note, the two connections I am creating are from the same server but different databases.

If you're still seeing this, could you please file a new issue?

**Comment by tyluRp** [comment]
Sure, when I have some time, I'll try and reproduce once more and then file a new issue if it persists.

**Comment by ronblum** [comment]
@tyluRp and @kevinushey I just ran across the same issue in 1.4—of all connection history disappearing—and filed issue #8204 for it.
