### ISSUE TITLE
Remove default keyboard shortcut for quit current R session and/or add a confirmation

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#6343]
Several times I have Accidentally hit Ctrl-Q when going for Ctrl-W only to find my R session quits without a confirmation option.

I recommend both removing the default shortcut for quit R session - as in don't assign one by default.

When executing this option I also recommend asking the user to confirm in a popup window.

**Comment by ronblum** [comment]
@kendonB Thank you for the suggestions! We'll review this as we continue development of RStudio. Personally, I think including it by default is useful—but that's a matter of opinion, and something to consider. As for a confirmation pop up, I agree that could be useful; I happened to do the same thing earlier today with the web browser, outside of RStudio, and managed to close all three open windows—including one in which I had been filling out a form. Ouch.
