### ISSUE TITLE
Copy-able directory path on the top of the file pane

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#6344]
The best way to navigate to a desired directory is through the file pane, in my opinion. However, when one gets there, there is no easy way to copy and paste the directory path into the source. It will help if the directory path at the top of the file pane is copy-able/editable.

PS. One could navigate through the directories using the path auto-complete feature of RStudio. This is a great feature, but it cannot be easily applied when one has only a rough idea of the location of the target directory.

**Comment by hzarkoob** [comment]
A workaround could be to set the working directory to the current directory in the file pane and go to the console pane to get a copyable version of the directory. But it is not a very convenient approach, because one needs to re-set the working directory afterward.

**Comment by nevilamos** [comment]
Whis would be a great gain in the usability fo the IDE, in windows I can use something like PathCopyCopy utility in file explorer to grab the  corretly formatted path - however when using Rstudio  on a server on AWS I cannot do this, and often end up having to type long path names
