### ISSUE TITLE
[FR] Explicitly set `width` for Chineses Letters that printing in the Console Panel

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#6346]
See discussion in #6296 

Chinese printing will be misaligned in the RStudio IDE's console panel. The cause is that the Console Panel doesn't set the Chinese character's width explicitly.

In contrast, the code editing panel (the Source Panel) will set every Chinese Character's width to a fixed number (double of a English letter). So the mixing of Chinese and English characters displays well in the Source Panel but no in the Console Panel.

So I'm filing this feature request that: **the Chinese character in the Console Panel should be set to double-width of the English letter explicitly**.

## Code

```r
# RStudio Version 1.3.820
df1 <- data.frame(n = 1:2, a = c(123, 4567), b = c('aaa', 'bbbb'), c = c('bd', 'ef'))
df1
df2 <- data.frame(n = 1:2, a = c(123, 4567), b = c('中文字符', '汉语文字等'), c = c('bd', 'ef'))
df2
```

## Screenshot

![](https://user-images.githubusercontent.com/8368933/75104824-6fb52d00-5648-11ea-9709-44775084579d.png)

## Expecting the Chinese letters to be set to double-width of the English letter as the code editing panel does

![](https://user-images.githubusercontent.com/8368933/75412267-ead65600-595c-11ea-8988-6ef6bff4af30.png)

**Comment by ronblum** [comment]
@shrektan Thank you for the suggestion! We'll review as we continue development of RStudio.
