### ISSUE TITLE
Multiline errors lose line breaks in RMarkdown

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#6347]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.867
    OS Version      : Mac
    R Version       : 3.6.2

### Steps to reproduce the problem

Create an RMarkdown document containing this chunk:

````
```{r}
rlang::quo(1) + 1
```
````

Run the chunk.

(I believe the problem occurs with any multi-line error, which we're starting to use more across the tidyverse. But this error from rlang is long standing, so should make it easier to reproduce)

### Describe the problem in detail

The chunk throws an multiline error, but the line breaks are lost:

<img width="767" alt="Screenshot 2020-02-27 at 7 15 59 AM" src="https://user-images.githubusercontent.com/4196/75448541-03307b80-5931-11ea-9366-fecf05b6c0ff.png">

### Describe the behavior you expected

The error should look the same as the error generated from the console:

```
Error: Base operators are not defined for quosures.
Do you need to unquote the quosure?

  # Bad:
  myquosure + rhs

  # Good:
  !!myquosure + rhs
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproduced in RStudio Server 1.3.842 running on Ubuntu 18.04.3. Also, today I learned a new word, _quosure_.

**Comment by kevinushey** [comment]
Looks like we need `white-space: pre` (or similar) in the CSS styles for the error text in the chunk.

**Comment by hadley** [comment]
That seems to do that job when I add it interactively in the DevTools
