### ISSUE TITLE
Run All Chunks Above does nothing if the last chunk is missing backticks

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6348]
# System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.842
    OS Version      : MacOS 10.15.4 & Red Hat 7.8
    R Version       : 3.6.2 & 3.6.0

### Steps to reproduce the problem

In a notebook with multiple chunks:
1. Remove the ending bacticks of the last code chunk so that the last chunk is unterminated.
2. Place the cursor below the incomplete chunks.
3. Click on Run -> Run All Chunks Above.
    - Nothing happens
4. Add a complete chunk below the unfinished chunk.
5. Place the cursor below the incomplete chunks.
6. Click on Run -> Run All Chunks Above.
    - All the chunks run correctly, except for the last chunk.
    - Background highlighting gets a bit confused.

<img width="604" alt="above_missing_backtick" src="https://user-images.githubusercontent.com/31009952/75460594-a4c6c580-594f-11ea-9e79-344fa512e2fe.png">

### Describe the problem in detail

None of the chunks run (step 4) and background highlighting gets confused.

### Describe the behavior you expected

Either:
- the complete chunks above the incomplete chunk run
- an error is displayed indicating that/why the good chunks didn't run.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
I forgot to mention that was first noted in the RStudio Community: https://community.rstudio.com/t/run-all-chunks-above-buttons-have-stopped-working-fixed-but-probably-a-bug/54576/2

**Comment by kevinushey** [comment]
The background highlighting looks (technically) correct in your screenshot. Or am I misunderstanding?

I think the fix here would be to indicate with an error if we detected that the document contained one or more unclosed chunks, or detected other chunk-related errors.

**Comment by ronblum** [comment]
@kevinushey My thought is that the background highlighting is including everything between the first and third backticks, rather than the first pair.

**Comment by mjbeggs** [comment]
It seems that an inaccurately formed code chunk demarcation (e.g., an extra space before the 3 tick marks) anywhere can cause the IDE to run chunks up to that point and then stop executing with no error message. The only indication that something is wrong is the background shading is off, and once the IDE hangs up, the chunk execution icons disappear. The lesson I learned is to carefully retype the 3 tick marks with no spaces before or after them.
