### ISSUE TITLE
"No such file or directory" when creating a C++ file

### ISSUE THREAD

**Issue by rstub** [rstudio/rstudio#6351]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.869 
    OS Version      : Debian 10
    R Version       : 3.6.2

### Steps to reproduce the problem

* remove the check-mark from `Tools > Global Options > Packages > Development > Use Rcpp template when creating C++ files`
* create a new C++ file via `File > New File > New C++ File`

### Describe the problem in detail

An error window with "No such file or directory" pops up.

### Describe the behavior you expected

An empty editor window in c++ mode.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible on MacOS 10.15.4 and Debian 10.
