### ISSUE TITLE
Use different shortcuts for main menu on Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6353]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.874
    OS Version      : Windows web browser
    R Version       : Any

### Steps to reproduce the problem
- Connect to RStudio Server from Windows browser
- Keyboard shortcuts for main menu are Ctrl+Alt+Letter such as <kbd>Ctrl+Alt+F</kbd> for File menu

### Describe the problem in detail
- These make sense on Mac (and are what Google Docs uses on Mac) but on Windows have a high chance of colliding with shortcuts for starting application (e.g. Ctrl+Alt+E for EdSharp a widely used text editor for the blind)

### Describe the behavior you expected
- On Windows, do what Google Docs does and use Alt+Shift+Letter, instead

**Comment by ronblum** [comment]
Confirmed in both Firefox and Chrome on Windows, and that it's unchanged in Firefox, Chrome, and Safari on MacOS.
