### ISSUE TITLE
Cannot install the required update to create an R Markdown

### ISSUE THREAD

**Issue by jrharris14** [rstudio/rstudio#6361]
I'm using RStudio and when I attempt to create I'm met with the pop-up: "Creating R Markdown documents requires an updated version of the digest package.
Do you want to install this package now?"
And when I accept it begins installing it but by the end says permission denied. This is my personal computer and I am of course the admin. Any ideas as to what might be the problem?

**Comment by jrharris14** [comment]
had to run as administrator lol

**Comment by ronblum** [comment]
@jrharris14 I'm glad to hear that's all it was!
