### ISSUE TITLE
Integrated learnr tutorial not opening on Server

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6362]
# System details

    RStudio Edition : Server
    RStudio Version : 1.3.842
    OS Version      : Red Hat 7.8
    R Version       : 3.6.0

### Steps to reproduce the problem

This was originally filed in the RStudio Community at https://community.rstudio.com/t/integrated-learnr-tutorial-not-opening-on-desktop/54371/8?u=rblum

An update on this, on the new preview version 1.3.869 links are working now, I have tried the first tutorial but when you run the code inside it, the tutorial crashes and if you stop the tutorial the home page never recovers, it just stays black.
Steps to reproduce would be as follow:

1. Start the first tutorial "Data basics" in the Tutorial pane
2. Press "Next topic" button
3. Type `mpg` in the code chunk as requested and press "Submit Answer"
   - The tutorial crashes and stays busy.
4. Stop the tutorial with the "Stop" button.
5. Try to get back to the home page with the "Home" button.
    - The home page never recovers, it just stays blank.
6. Stop the tutorial with the "stop" button in the Tutorial pane.
    - The screen is blank
 7. Click on the "home" button
    - The screen stays blank
8. Close the browser window
9.  Open a new browser window and connect to RStudio
10. Start the first tutorial "Data basics" in the Tutorial pane
    - Everything works fine now
2. Press "Next topic" button
    - Still working fine
3. Type `mpg` in the code chunk as requested and press "Submit Answer"
   - The tutorial crashes again and stays busy.
### Describe the problem in detail

The tutorial crashes and doesn't recover.

```
Listening on http://127.0.0.1:7174
Warning in selectChildren(jobs, timeout) :
  cannot wait for child 13794 as it does not exist
Warning: Error in [[: subscript out of bounds
  61: utils::URLencode
  60: id_to_filesystem_path
  58: storage_path
  56: tutorial_storage(session)$save_object
  55: save_object
  54: save_exercise_submission
  53: exercise_submission_event
  52: <observer>
   9: <Anonymous>
   7: rmarkdown::run
   4: learnr::run_tutorial
   3: eval
   2: eval
   1: sourceWithProgress
```

### Describe the behavior you expected

The tutorial should not crash. Note that this works in RStudio Desktop on MacOS 10.15.4 beta.

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rich-rstudio** [comment]
verified on Version 1.3.910
