### ISSUE TITLE
Make chunk names unique after splitting chunks using Cmd+Option+I

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#6364]
I often split long chunks using the shortcut Cms+Option+I (the Insert chunk button does the same thing). When I do that with a named chunk, the chunks have duplicate names, which makes knitr emit an error. An easy fix would be to automatically name the new chunk with a variant of the old name e.g. "oldname-1" or strip the name from the new chunk.

**Comment by dfalty** [comment]
I agree this would be nice to have, thank you for the suggestion! We'll review this as we continue the development of RStudio.

**Comment by sbalci** [comment]
There is a package for this. But it will be nice to have it as a feature.
https://github.com/lockedata/namer
