### ISSUE TITLE
File panel: Explore directories by toggling instead of changing view

### ISSUE THREAD

**Issue by statnmap** [rstudio/rstudio#6365]
I often move from sub-directories to other sub-directories, and I find it long and difficult to do it with the Rstudio Files pane.

For instance, if my architecture is:
```
golex
├── DESCRIPTION
├── NAMESPACE
├── R
│   ├── app_server.R
│   ├── app_ui.R
│   └── run_app.R
├── dev
│   ├── 01_start.R
│   ├── 02_dev.R
│   ├── 03_deploy.R
│   └── run_dev.R
├── inst
│   └── app
│       └── www
│           ├── favicon.ico
│           └── plop.js
└── man
    └── run_app.Rd
```

If I want to open `inst/app/www/plop.js` and then go back to open my `app_server.R` file, I need to click multiple times back and forth to do so. 
I was wondering if a toggling view, like the one in the "Environment" or "Connection" pane would be possible.
![image](https://user-images.githubusercontent.com/21193866/75563807-4121c280-5a4b-11ea-814d-ecc80b631dab.png)

**Comment by gtritchie** [comment]
Believe this is already covered by #2552
