### ISSUE TITLE
Change behavior of "soft spaces"

### ISSUE THREAD

**Issue by technocrat** [rstudio/rstudio#6368]
The conversion of tabs to soft tabs, consisting of spaces is highly desirable and should, of course be maintained.

On the other hand, when editing text containing multiple spaces, the cursor treat those spaces as tabs. A one-way conversion of tabs to spaces, without a return trip of spaces to tabs, would be preferable.

For a more detailed description, please see https://community.rstudio.com/t/navigating-double-spaces-with-arrow-keys/54132/14

**Comment by jmcphers** [comment]
Many people prefer the existing behavior so this would probably need to get set as a preference (marking as such)
