### ISSUE TITLE
Enable Comment/Uncomment in C files

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#6369]
C++ and `.h` files allow you to select a number of lines and (on the Mac) hit cmd+shift+c to comment/uncomment the block with `//`. Can we please get this in C files? I assume it would share the same implementation. It would greatly improve my quality of life 😬

**Comment by kevinushey** [comment]
This was also recently requested for JavaScript files as well. Seems like something we could enable by default, since Ace modes have the line comment prefix built-in for each mode; e.g. (for Shell):

https://github.com/ajaxorg/ace/blob/10427c0a17695d5190ae799de80aeeb7ff032d83/lib/ace/mode/sh.js#L51

**Comment by MichaelChirico** [comment]
Duplicate of #4109?

**Comment by MichaelChirico** [comment]
would still love to see this implemented

**Comment by DavisVaughan** [comment]
Keep alive!

**Comment by DavisVaughan** [comment]
Sure enough on 1.5.106 this does work. Thank you!
