### ISSUE TITLE
Dual source code file pane view

### ISSUE THREAD

**Issue by tallguyjenks** [rstudio/rstudio#6372]
# request 
I did some searching and cant seem to find anything open or closed on this, but being able to have 2 source code files open in the source pane for size by side editing. im imagining it like a vim vertical split, and hotkeys to support easy switching between them in vim mode would be icing on the cake `<C-h>` `<C-l>`

## usecase: 

often in my reports i encapsulate all my ETL for data into *.R scripts in the R/ directory and load them into my RMarkdown files having the script open on one side and the .Rmd on the other would be very nice for side by side editing, with less clicking around and if combined with hotkeys for switching pane focus, then would support the vim mode users like me to minimize how much clicking we need to do in the IDE.

## similar software:

the built in vim vertical split functionality and ctrl-h/l hotkeys for switching pane focus

**Comment by jmcphers** [comment]
We're currently tracking this in https://github.com/rstudio/rstudio/issues/2854.
