### ISSUE TITLE
RStudio 1.3 Global Options pane (still) doesn't open

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [rstudio/rstudio#6373]
Hi, I wrote about it a while ago, when RStudio version was 1.3.400. https://github.com/rstudio/rstudio/issues/5296
I experience the same problem now when RStudio preview version is: 
RStudio v1.3.878-1 Preview. 
I installed RStudio on my old laptop with GPU NVidia GT 425M, and on the other laptop where GPU is: GeForce 310M,  (both on Windows 10 x 64) and this does not work at all.
When I installed RStudio on relatively new laptops (eg. Lenovo Yoga, HP Pavillon G6) everything is OK. 
Does new Rstudio have a problem with older GPUs ? 
Any help would be much appreciated.

**Comment by dfalty** [comment]
Hi @Andrzej-Andrzej thanks for the update! Does clearing your state like @jmcphers mentioned in https://github.com/rstudio/rstudio/pull/5309#issuecomment-527609732 help?

**Comment by Andrzej-Andrzej** [comment]
Thank you @dfalty  very, very much indeed. It helped and is working now. I installed 1.3.881 version and Global Options pane works like a charm. 
best regards

**Comment by dfalty** [comment]
@Andrzej-Andrzej I'm glad it's now working for you now! Thank you for following up on the ticket.
