### ISSUE TITLE
Bug while scrolling in 'Update Packages' panel in preview 1.3.842

### ISSUE THREAD

**Issue by HanOostdijk** [rstudio/rstudio#6375]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  preview 1.3.842 ("Middlemist Red" (74333857, 2020-02-17) for Windows) 
    OS Version      :  Windows 10 x64 (build 18362)
    R Version       :  3.6.0 (2019-04-26)

### Steps to reproduce the problem 
Problem occurs in a clean session when I view the 'Update Packages' panel.

### Describe the problem in detail
I have a lot of packages installed and from time to time I check the 'Update Packages' panel to see which I would like to update. The first package displayed in the list is currently ' anytime'. I use the scrollbar to see other packages that can be updated. Then I see e.g. the contents in the screenshot below.

My small but annoying issue is the following: when I want to update both 'devtools' and 'digest' the panel is refreshed immediately after I flag 'devtools' (and then showing 'anytime' again as first updateable package) before I have an opportunity to also flag 'digest'. So I have to scroll downwards to 'devtools' and 'digest' again (where I see that 'devtools' is indeed flagged) and now flag 'digest'.

### Describe the behavior you expected

My preferred way of working would of course be to flag all the relevant packages in the current view and then scroll down to the next set of packages and repeat (without seeing the 'anytime' package anytime).

![image](https://user-images.githubusercontent.com/13506389/75614961-5af00200-5b3e-11ea-9b9b-8dd83af48949.png)

This was asked as question in [RStudio Community](https://community.rstudio.com/t/how-to-avoid-scroll-in-update-packages-panel-in-preview-1-3-842/54421) but marked by [kevinushey](https://community.rstudio.com/u/kevinushey) as a possible bug.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
**NB this is a preview version!**
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Investigation note: started with build 1.3.259 (f3ffa4b6).

**Comment by HanOostdijk** [comment]
I see the fix is included in daily build1.3.904. 
And it indeed solved my problem.
Thanks.

**Comment by rich-rstudio** [comment]
verified in 1.3.908
