### ISSUE TITLE
View() error when utils::menu() is run in RProfile 

### ISSUE THREAD

**Issue by irenetlv** [rstudio/rstudio#6377]
Originally posted on [RStudio Community](https://community.rstudio.com/t/view-error-when-utils-menu-is-run-in-rprofile/53646) cc @kevinushey 

--

In order to encourage myself to review vocab words more often, I wrote a function that calls `utils::menu()` and placed it in my RProfile.  That way, I would be asked about vocabulary every time I restart my R session.

However, this seems to lead to a weird error with View() (related GitHub issue at https://github.com/isteves/flashcards/issues/1):

```r
> View(mtcars)
Error in hist(hist_vals, plot = FALSE) : could not find function "hist"
```

I suspect that by running `utils::menu()`, I'm somehow blocking some start-up processes that normally run.  

Any insight into this problem would be great!

---

To reproduce this problem:

1. `usethis::edit_r_profile()` to open your RProfile
2. Comment out whatever is already there and add:

```r
if(interactive()) {
  utils::menu(c("apple", "orange", "carambola"), title = "pick a fruit")
}
```

3. Restart R
4. Run `View(mtcars)`

**Comment by leomarameo7** [comment]
Hello Irene and everyone else too, 

I have the same problem when I call "View ()". 
This happened after I actualized R (4.0.1) and R studio (1.3.959)
I'm working on MacOS Catalina 10.15.5 . 
The error message is 
 View()
Error in hist(hist_vals, plot = FALSE) : could not find function "hist"

My my RProfile is empty now. 

Does anyone help me with this bug , please ?

**Comment by kevinushey** [comment]
Does the error go away if you explicitly load the `utils` package, via `library(utils)`?

**Comment by nielsenrechia** [comment]
@kevinushey The error persists after load the utils package.
