### ISSUE TITLE
Unexpected "Registered S3 method overwritten"

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#6378]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.3 (Although I have been experiencing this with earlier versions, 

### Steps to reproduce the problem

Hard to tell, I cannot reproduce at will. 

### Describe the problem in detail

When I start project I often see this messages (on red) on the R panel of the RStudio (I don't see it when I open R on the same folder):

```r
Registered S3 method overwritten by 'enrichplot':
  method               from
  fortify.enrichResult DOSE
Registered S3 method overwritten by 'seriation':
  method         from 
  reorder.hclust gclus

Registered S3 methods overwritten by 'vegan':
  method         from      
  reorder.hclust seriation 
  rev.hclust     dendextend
```

![Screenshot from 2020-03-02 15-07-49](https://user-images.githubusercontent.com/6818218/75685164-6c4e2100-5c9a-11ea-9c32-40fb5484441e.png)

### Describe the behavior you expected

I don't know how is the startup of R inside Rstudio, but I think that I shouldn't see this. I have a ~/.Rprofile loaded but when I start R at the location of this project I don't see this method overwritten messages. Note that I also see it when I open other projects.

I opened the project by double clicking the `project.Rproj` and I didn't saw the messages, but when I open Rstudio from the desktop bar (I have it pinned there) it happens. Usually the message take a few seconds to appear. 

The packages that seem to be masking others do not appear to be attached as I can't see the asterisk on the `session_info()`, so it seems like they are loaded but not attached. (I would think this would indicate an issue with the `.Rprofile` but I don't experience this when I open R from the terminal where the `.Rprofile` is used too).

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by llrs** [comment]
Maybe it is related or maybe not, but I have seen twice the greeting info of the R session (in a project which uses `{renv}`) right after opening Rstudio:
![Two R session restarted](https://user-images.githubusercontent.com/6818218/75758147-e383c380-5d33-11ea-9b16-2de26eab6c01.png)

**Comment by kevinushey** [comment]
Loading `enrichplot` is enough to trigger this:

```
> library(enrichplot)

Registered S3 method overwritten by 'enrichplot':
  method               from
  fortify.enrichResult DOSE
```

So this is ultimately an issue independent of RStudio / `renv`.

**Comment by llrs** [comment]
Yes, that would produce the same messages but I don't load `enrichplot` nor renv on the first image capture. As I said, I saw this messages right after opening RStudio, and that wouldn't explain the masking "done" by `vegan` or seriation which as you can see they aren't called, nor the double R greeting from the second image capture.

Or do you mean that my .Rprofile is loading this packages in some unexpected way?
That wouldn't explain why I don't see this outside RStudio (unless I do `library("enrichplot")`.

**Comment by kevinushey** [comment]
What do you see in `loadedNamespaces()` after starting RStudio?

I don't know where or why the package is being loaded, but that appears to be the culprit.

**Comment by llrs** [comment]
Thanks (didn't know about loadedNamespaces), indeed Rstudio has loaded a lots of things:

```r
dput(loadedNamespaces())
c("backports", "fastmatch", "plyr", "igraph", "lazyeval", "splines", 
"BiocParallel", "usethis", "ggplot2", "lpsymphony", "urltools", 
"digest", "foreach", "htmltools", "GOSemSim", "viridis", "GO.db", 
"gdata", "fansi", "magrittr", "memoise", "covr", "cluster", "gclus", 
"limma", "remotes", "graphlayouts", "matrixStats", "methods", 
"metagenomeSeq", "beepr", "enrichplot", "prettyunits", "colorspace", 
"blob", "ggrepel", "dplyr", "callr", "crayon", "jsonlite", "iterators", 
"glue", "polyclip", "registry", "utils", "gtable", "webshot", 
"UpSetR", "RGCCA", "pkgbuild", "shape", "BiocGenerics", "scales", 
"DOSE", "IHW", "DBI", "graphics", "edgeR", "Rcpp", "viridisLite", 
"progress", "gridGraphics", "reactome.db", "bit", "europepmc", 
"stats4", "glmnet", "base", "htmlwidgets", "rex", "httr", "fgsea", 
"gplots", "RColorBrewer", "ellipsis", "pkgconfig", "farver", 
"locfit", "ggplotify", "tidyselect", "rlang", "reshape2", "AnnotationDbi", 
"stats", "munsell", "tools", "cli", "RSQLite", "audio", "devtools", 
"ggridges", "fdrtool", "stringr", "heatmaply", "grDevices", "org.Hs.eg.db", 
"processx", "bit64", "fs", "tidygraph", "caTools", "purrr", "dendextend", 
"ggraph", "packrat", "nlme", "slam", "DO.db", "xml2", "compiler", 
"rstudioapi", "plotly", "testthat", "tibble", "tweenr", "stringi", 
"cyclocomp", "ps", "desc", "lattice", "Matrix", "permute", "vegan", 
"vctrs", "pillar", "lifecycle", "BiocManager", "triebeard", "bitops", 
"data.table", "cowplot", "seriation", "qvalue", "R6", "TSP", 
"KernSmooth", "gridExtra", "IRanges", "sessioninfo", "integration", 
"codetools", "MASS", "gtools", "assertthat", "pkgload", "Wrench", 
"rprojroot", "withr", "Deriv", "S4Vectors", "datasets", "mgcv", 
"parallel", "hms", "clusterProfiler", "grid", "tidyr", "rvcheck", 
"ggforce", "rdoc", "Biobase")
```
How are these NAMESPACES loaded at the start? My .Rprofile only has:

```r
if (interactive()) {
  message("Loading the ~/.Rprofile")
  # suppressMessages(require(conflicted))
  suppressMessages(require(devtools)) # For package development
  suppressMessages(require(usethis)) # For some tasks
  suppressMessages(require(testthat)) # For package development
  suppressMessages(require(beepr)) # For beep
  suppressMessages(require(covr)) # For package development
  suppressMessages(require(cyclocomp)) # For package development
  options(Ncpus = 4, usethis.full_name = "NAME",
          devtools.name = "NAME",
          devtools.desc.author = "NAME & email",
          devtools.desc.license = "MIT",
          usethis.protocol = "ssh",

          warnPartialMatchArgs = TRUE,
          warnPartialMatchDollar = TRUE,
          warnPartialMatchAttr = TRUE
          )
  if (.Platform$GUI != "RStudio") {
    library(rdoc)
    use_rdoc()
  }
}

```

**Comment by llrs** [comment]
I had the same message appear on another project. I solved closing a tab viewing  an object created with these packages. Tried closing all the tabs and it disappeared when I reopened the project. It seems like there might share the rsession from them?

**Comment by ProfFancyPants** [comment]
@llrs I received the same message by merely assigning an object from another package. The following would be sufficient. 
```R
f <- pryr::f
```
> Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp

This message started during the update from R3.5 to R3.6. My issue is that this message should be irrelevant. The S3 method for 'pryr' might indeed be overwritten within 'pryr's environment, but there shouldn't be any masking outside of its environment.

**Comment by llrs** [comment]
I'm not sure this preloading is the reason of the message. Because I do have the same files open which load lots of packages and I do not longer see the message. 

I think it is related to recreate the environment for an object that has its own tab after calling `View(object)`. So when I closed all of them and opened again (without recreating that tab) it didn't need to load that environment so it didn't print the message.  
Anyway hope this isn't too serious and don't affect much.

**Comment by llrs** [comment]
I got the same error again on Rstudio Version 1.4.1103 and R 3.6.3. Closing the objects I had in View  and reopening the project didn't prevent the message to reapear. I think @ProfFancyPants is right and might be due to prereading the script (but haven't tested this with your minimal reprex).

**Comment by zagrosman** [comment]
I had the same error when running the **_ggVennDiagram_** package. I faced with the following error:
``````
Registered S3 methods overwritten by 'proxy':

  method               from    
  print.registry_field registry
  print.registry_entry registry

``````

**_Simply, I closed all open projects and restarted my RStudio. When I rerun the codes, it works fine. If you have installed different R versions, try to uninstall the oldest versions and reinstall RStudio and RTools. Then, this error will be disappeared from your RStudio pannel._**

**Comment by samuelfielding** [comment]
@zagrosman

> **_Simply, I closed all open projects and restarted my RStudio. When I rerun the codes, it works fine. If you have installed different R versions, try to uninstall the oldest versions and reinstall RStudio and RTools. Then, this error will be disappeared from your RStudio pannel._**

Unchecking "Show diagnostics for R" in RStudio > Tools > Code > Diagnostics seems to stop packages that are referenced in open source files being loaded when RStudio starts. I had ggtern functions in my opened source file referenced with `::` (e.g. `ggtern::ggtern()`) and the ggtern package was being loaded when I started RStudio. Turning off diagnostics stopped that. Funnily enough, `library(ggtern)` in open source files did not produce the same problem.

[https://stackoverflow.com/questions/67356592/registered-s3-method-overwritten-by-ggally-method-from-gg-rstudio-loading](https://stackoverflow.com/questions/67356592/registered-s3-method-overwritten-by-ggally-method-from-gg-rstudio-loading)

[https://stackoverflow.com/questions/67356592/registered-s3-method-overwritten-by-ggally-method-from-gg-rstudio-loading](https://github.com/ggobi/ggally/issues/416)
