### ISSUE TITLE
Shiny applications in Viewer pane are not displayed after refresh

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6381]
### System details

    RStudio Edition : Server
    RStudio Version : v1.2.5033, v1.3.867
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.1

### Steps to reproduce the problem

Create a Shiny application (e.g. with `File -> New File -> Shiny Web App...`), save that application, ensure it will run and show in the Viewer pane, and then run the application.

The Shiny application should now be showing in the Viewer pane. Now, refresh the browser.

### Describe the problem in detail

The previously-shown Shiny application is no longer visible. Its src has been reset to `about:blank`; attempting to manually reset the `src` URL fails with a "connection refused" message.

### Describe the behavior you expected

The Shiny application should open and render without issue.

### Notes

The `port-token` cookie appears to change with every new client connection, which invalidates any previously-known port mappings. This may be the underlying cause.

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I looked at this and discovered that this has never worked -- Shiny applications do not generate history or state in the Viewer pane and so have always been lost on reload; it's not that we're reloading and failing, it's that we forget the URL entirely. It would be nice to preserve this but no one's ever asked for it so I don't think it's super important.
