### ISSUE TITLE
Terminal text size differences in RStudio 1.3

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#6382]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.869
    OS Version      : Mac
    R Version       : 3.6.0

### Describe the problem in detail

I upgraded from RStudio 1.2 to Preview 1.3 and now the terminal text looks to be a different size and line height from my normal R script editor.

For reference, I sit at 110% zoom and an editor font size of 10. I use Firacode-retina font.

<img width="1317" alt="Screen Shot 2020-02-28 at 3 49 47 PM" src="https://user-images.githubusercontent.com/19150088/75716257-d10a7b00-5c9c-11ea-8d59-4360627b6a4d.png">

From Hadley:

"FWIW turning hardware acceleration and inspecting the font size does reveal that the console and terminal have different font sizes (14.667 vs 16) and line heights (21.2667 vs 19)"

**Comment by rboyes** [comment]
We recently upgraded to RStudio Server Pro 1.3, and I can see something similar:

![Capture](https://user-images.githubusercontent.com/10985641/87539369-b35f1080-c695-11ea-8a79-5d6a8d4f86bf.PNG)

**Comment by beanumber** [comment]
I see the same thing on Ubuntu and RStudio 1.3.1056. I know I have the problem when I can't see underscores (`_`) in the terminal. 

Turning off hardware acceleration solves the problem. But why? And why would you need hardware acceleration in a terminal?

**Comment by gtritchie** [comment]
> Turning off hardware acceleration solves the problem. But why? And why would you need hardware acceleration in a terminal?

The "hardware acceleration" is a feature of the [xterm.js](https://xtermjs.org/) library we use for the terminal. It renders using an HTML canvas instead of the DOM.

**Comment by gtritchie** [comment]
Figured out the discrepancy in font-size and will make a fix. Still working on figuring out the line-height difference.

**Comment by kfeinauer** [comment]
Verified fixed on RStudio 1.4.944. Tried with both terminal hardware acceleration on and off and with different zoom settings.
