### ISSUE TITLE
Inconsistent behavior of 'Knit to PDF' inside an rmarkdown website

### ISSUE THREAD

**Issue by jdblischak** [rstudio/rstudio#6383]
### System details

I confirmed this behavior using rstudio.cloud:

    RStudio Edition : Server
    RStudio Version : 1.2.5033.1
    OS Version      : Ubuntu 16.04.6 LTS
    R Version       : 3.6.0

And on my local machine:

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Ubuntu 18.04.4 LTS
    R Version       : 3.6.3

### Steps to reproduce the problem

I created a project on rstudio.cloud with all of the required files: [knit-pdf](https://rstudio.cloud/spaces/22884/project/1001086). Here's the [sharing link to the workspace](https://rstudio.cloud/spaces/22884/join?access_code=%2Fzz50xYHQNoq%2BAMwFSDBxTD4JX85j6W9FccrwGpS) (Hopefully it's public. I changed the sharing link to "Shared", but I can't really test it since I have to login to rstudio.cloud to see anything).

Alternatively, the code below creates a directory with all the required files:

```
d <- tempfile()
dir.create(d)
file.create(file.path(d, "index.Rmd"))
writeLines(c("output:",
             "  html_document:",
             "    theme: cosmo"),
           con = file.path(d, "_site.yml"))
writeLines(c("---",
             "title: The Knit button can create HTML or PDF",
             "output:", 
             "  pdf_document: default",
             "  html_document: default",
             "---", 
             "",
             "```{r}",
             "1 + 1",
             "```"),
           con = file.path(d, "test-html-and-pdf.Rmd"))
writeLines(c("---",
             "title: The Knit button always produces HTML",
             "output:", 
             "  pdf_document: default",
             "  html_document:",
             "    theme: cerulean", 
             "---",
             "",
             "```{r}",
             "1 + 1",
             "```"),
           con = file.path(d, "test-only-html.Rmd"))
```

After running that code, follow these steps:

1. Open `test-html-and-pdf.Rmd`
1. Click `Knit to PDF` in RStudio
1. If the PDF doesn't automatically open, observe it is created in `_site/`
1. Click `Knit to HTML`. Note that the HTML is created
1. Open `test-only-html.Rmd`
1. Click `Knit to PDF` in RStudio
1. Note that no PDF is created. Instead an HTML file is created.
1. Click `Knit to HTML` in RStudio
1. Note that again the HTML file is created

### Describe the problem in detail

In the context of an rmarkdown website (`index.Rmd` and `_site.yml` are present), it is possible to create a PDF using the `Knit to PDF` button in RStudio if only the default settings are used for `pdf_document` and `html_document`. These are the settings in `test-html-and-pdf.Rmd`.

```
---
title: The Knit button can create HTML or PDF
output:
  pdf_document: default
  html_document: default
---
```

However, if `html_document` is provided any options, then it is impossible to create a PDF using `Knit to PDF`. An HTML file is always created (and note that the settings to `html_document` are always applied, which I confirmed by overriding the `theme` in `_site.yml`). These are the settings in `test-only-html.Rmd`.

```
---
title: The Knit button always produces HTML
output:
  pdf_document: default
  html_document:
    theme: cerulean
---
```

### Describe the behavior you expected

I expect that clicking on `Knit to PDF` in RStudio will create a PDF file, even if custom settings are passed to `html_document`.

This is important to me because my package [workflowr](https://github.com/jdblischak/workflowr) uses an rmarkdown custom site generator (i.e. it is an rmarkdown-based website). Sometimes users want to be able to create a quick PDF of one of their webpages. I want them to be able to simply click `Knit to PDF` without having to manually run `rmarkdown::render("filename.Rmd", rmarkdown::pdf_document())`. This will work most of the time, but will unexpectedly fail if they set any custom settings to the output function, as demonstrated above.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jdblischak Thank you for raising the issue and sharing you rstudio.cloud project! I can reproduce it there, but not on my local environment; however, I may be doing it incorrectly there. @dfalty Can you provide any insight? Thanks!

**Comment by dfalty** [comment]
This isn't a cloud-specific issue and I'm able to reproduce on RStudio Server Pro with both 1.2.5033.1 and 1.3.885-1.
