### ISSUE TITLE
Named code chunk not shown in document outline of Rmarkdown editor

### ISSUE THREAD

**Issue by ntthung** [rstudio/rstudio#6387]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.820
    OS Version      : Windows 10
    R Version       :  3.6.2

### Steps to reproduce the problem
Start a new Rmarkdown file

### Describe the problem in detail
Named code chunks are not shown in the document outline of the Rmarkdown editor. This is a regression; it used to work correctly in RStudio 1.2.x
![image](https://user-images.githubusercontent.com/22501446/75749546-fe1e6280-5d5c-11ea-98db-e062bdf4e948.png)

### Describe the behavior you expected
Named code chunks should be shown in document outline

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ntthung Thank you for filing the issue. However, I can't reproduce the issue in a few versions of RStudio Desktop and Server, 1.3.766 and 1.3.842. What is your setting in Tools -> Global Options -> R Markdown -> Show in document outline? It should be set to "Sections and Named Chunks" or "Sections and All Chunks."

**Comment by ntthung** [comment]
@ronblum Thanks for your reply. I didn't realize that this option was available. Perhaps I set it with my previous RStudio version along time ago and forgot about it. After setting this up, things are in order.

**Comment by m-macaskill** [comment]
I've also just seen this, after upgrading to version 1.3.959. I wonder if something in the upgrade process causes the previous setting of "Sections and named chunks" to be overwritten to a default value of "Sections only"?
