### ISSUE TITLE
Ctrl-Up in console does not bring you to latest command, but random one

### ISSUE THREAD

**Issue by cactus74** [rstudio/rstudio#6388]
### System details

    RStudio Edition : Desktop AND Server
    RStudio Version : 1.3.878 and earlier since 1.3 came out
    OS Version      : Ubuntu 18
    R Version       : 3.6.2

### Steps to reproduce the problem
In the console, Ctrl+Up with or without any start of recent command.
### Describe the problem in detail
In the console, Ctrl+Up brings Popup command history. In RStudio 1.2 it used to give you the latest command or the latest command starting with input in console. Now it brings you to some (apparently) random command in the past. Very unpractical and probably a bug.
### Describe the behavior you expected
If not input in the console, I expect the latest command to be selected first, and then move back/forward to eventually select another one. If an input is given in the console, I expect the latest command starting with this input to be selected first with, again, the possibility to move forward/backward through available choices.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@cactus74 Thank you for filing the issue. I can't reproduce it, though, on Ubuntu 18.04.3, both in 1.3 versions of the RStudio Desktop and Server. In the graphing at straws department, what desktop are you using? I am currently using Gnome Shell 3.28.4. Thanks!

**Comment by kevinushey** [comment]
A screenshot might also be helpful, so we know exactly what you're seeing.

**Comment by cactus74** [comment]
Thank you very much guys for considering this issue.

Gnome Shell 3.28.4, google-chrome 80.0.3987.122 (but happened the same with earlier versions) when I use rstudio-server. I tried everything with all extensions disabled, no change.

I attach three screenshots. Everything is based on a brand new project, .rstudio folder and ~/.Rhistory empty.

As a side note, this behaviour is not always present if you start from an empty history. Sometimes two commands are enough. Sometimes you need 10.

- First screenshot shows a sequence of calls to source. I naturally expect the following Ctrl+Up to show me the history with  source('~/test_project/function_j.R') selected.
![1](https://user-images.githubusercontent.com/22644863/75807320-73059280-5d85-11ea-9270-62971fa77db7.png)

- Second screenshot shows this is not the case as source of function_h.R is selected. I need to press Down twice
![2](https://user-images.githubusercontent.com/22644863/75807322-739e2900-5d85-11ea-8e6e-a33028ceec16.png)

- Third screenshot shows this is not the case too if I input "so" before Ctrl+Up
![3](https://user-images.githubusercontent.com/22644863/75807323-7436bf80-5d85-11ea-913d-246f19f25fe2.png)
