### ISSUE TITLE
Ctrl+Shift+V in Windows Desktop app pastes output twice, Windows 10, RStudio 1.3 

### ISSUE THREAD

**Issue by remlapmot** [rstudio/rstudio#6395]
I am not sure if `Ctrl+Shift+V` is a supported shortcut. It doesn't appear to be mentioned in the official list of keyboard shortcuts but there was some discussion in #1687 and Windows users would appreciate/expect it in the Terminal pane.

On Windows 10 I find that it produces double output in both the Source and Terminal panes.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.878
    OS Version      : Windows 10 (Version 1909 Build 18363.657)
    R Version       : 3.6.3

### Steps to reproduce the problem

- copy some text
- paste with `Ctrl+Shift+V` in either the Terminal pane or the Source pane.

### Describe the problem in detail

- The output is pasted twice, e.g. I should just be pasting `echo "Hello, World!"`
![windows-terminal-csv](https://user-images.githubusercontent.com/3777473/75877370-75acca00-5e0f-11ea-907e-8107045789da.png)

### Describe the behavior you expected

- The output should only be pasted once.

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@remlapmot Thank you for filing the issue! I can reproduce this RStudio Desktop 1.3.878 with Command Prompt, PowerShell, and Git Bash. It works properly in 1.2.5033, so this is a regression. I'll mark this ticket for review as we continue development of RStudio. Thanks!

**Comment by gtritchie** [comment]
Not just terminal, happens anywhere you can paste text, the console, the editor, even simple textboxes.

Desktop only, can't repro in RStudio Server with Chrome or Firefox.

Also, Ctrl+Shift+V is not a supported shortcut.

**Comment by gtritchie** [comment]
Don't know that this meets the bar for 1.3, but will investigate and see if there's a safe fix.

**Comment by gtritchie** [comment]
Relatively recent regression, started with build 1.3.812 on Feb 5, 2020.

**Comment by gtritchie** [comment]
Believe this was caused by this PR: #6158

Specifically, this code:

https://github.com/rstudio/rstudio/blob/8437450d58fb5b99731d71b1e6ef4eefd4f02848/src/cpp/desktop/DesktopWebView.cpp#L172-L177

FWIW, none of the keyboard shortcut references mention this "Paste and Indent" shortcut.

**Comment by R-Hannibal** [comment]
Verified Fixed on: Version 1.3.926
Tested on Windows 10 desktop, pasting text tested in Console, Terminal, Source, and plain text.
