### ISSUE TITLE
RStudio-1.3.885 can't be launched on macOS

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#6398]
The latest daily builds for macOS can't be launched. 

https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.3.885.dmg

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/8368933/75906311-767e4400-5e81-11ea-9288-cd2585b44471.png">

However, the elder version RStudio-1.3.879.dmg is fine.

**Comment by jmcphers** [comment]
Can you be more precise about "can't be launched"? What are you seeing when you try to launch it? What version of macOS are you running?

I can't repro on Catalina (10.15). 

![image](https://user-images.githubusercontent.com/470418/75906768-0b3e5e80-5dfc-11ea-961f-b422d8009694.png)

**Comment by shrektan** [comment]
### my macOS version

<img width="532" alt="image" src="https://user-images.githubusercontent.com/8368933/75910138-47b79c00-5e88-11ea-8101-19fcdae82335.png">


### I'm using R3.6.2

### I mean this:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/8368933/75910064-2d7dbe00-5e88-11ea-8ffb-ba4ba7032ab9.png">

**Comment by jmcphers** [comment]
Thank you, that's very helpful! We have identified the issue and hope to have a fix soon.

**Comment by R-Hannibal** [comment]
Hey @shrektan, thanks again for finding and reporting this issue. We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by shrektan** [comment]
Yes, it has been fixed in the next day’s daily build after #6402 gets merged. I’ve been using the latest RStudio IDE for a few months already. Thanks.

**Comment by R-Hannibal** [comment]
Excellent, thanks for confirming!
