### ISSUE TITLE
blank lines omitted in notebook chunk output, but only in RStudio preview

### ISSUE THREAD

**Issue by jbullock35** [rstudio/rstudio#6399]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033 and 1.3.878
    OS Version      :  Windows 10 Pro
    R Version       :  3.5.1 and 3.6.3

### Steps to reproduce the problem
First, create this R notebook: 

    ---
    title: "Example: Omitting Blank Lines in Chunk Output"
    output: html_notebook
    ---

    ```{r, results = FALSE}  
    myString <- "The blank line after this one will appear in the chunk output."

    print("In RStudio Preview, the blank line that follows won't be printed.")        

    print("No blank line appears above this line in the previewed chunk output -- but a blank line should appear.")
    ```
Then run the chunk and preview the output in RStudio. The preview that I see is 

![image](https://user-images.githubusercontent.com/4016787/75913658-ee645400-5e18-11ea-965d-1d3de0ca3f7e.png)
<br><br>

### Describe the problem in detail
Blank lines that appear in code chunks are skipped in the RStudio Preview output if (a) they follow commands that print something to the screen, (b) one is working with an R Notebook, and (c) `results = FALSE`.

This isn't an `rmarkdown::render()` problem; when I render the document with `rmarkdown::render()` and then open the notebook in a browser, there is no problem. In addition, the problem doesn't occur in HTML documents (as opposed to notebooks). And it occurs whether `eval` is `TRUE` or `FALSE`. 

A related problem was described in #1556, but that issue seems to have been solved, and it was closed in 2017.

### Describe the behavior you expected
I expected that blank lines in a code chunk would appear in the RStudio preview of the rendered notebook. (Just as they do appear when I open the rendered notebook in a browser.)

- [ X ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ X ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ X ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jbullock35 Thank you for filing the issue, following up from the previous issue! I can reproduce it in the environment you describe, as well as MacOS and RStudio Server running on Red Hat 7.8. We'll review it as we continue development of RStudio.

Note: I tried the following code:
```
```{r, results = FALSE}
print("one")

print("two")

x <- 1

x <- 2

x <- 3

print(x)

print("four")
```
and the output is
```
print("one")
print("two")
x <- 1

x <- 2

x <- 3

print(x)
print("four")
```
