### ISSUE TITLE
Consider bundling R with RStudio Desktop setup

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6403]
For some users, especially beginners just getting into R, the ability to download RStudio, install it, and be up and running without having to do a separate download and install of R would be very nice.

Lots of factors to consider if we do that, but worth pondering.

**Comment by stephensrmmartin** [comment]
I would really prefer that Rstudio does not do that.

_If_ this were done, _please_ make it optional at compile time. The trend toward bundling everything has made linux packaging very difficult. Decoupling R from Rstudio is also crucial for having specific R builds (e.g., with BLAS, MKL, MS versions of R, different R interpreters, etc).
