### ISSUE TITLE
some RStudio internal functions fail when renv is loaded

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6404]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.885
    OS Version      : macOS 10.15.3
    R Version       : 3.6.1

### Steps to reproduce the problem

Try to execute the following code:

```
.rs.clearVar("hello")
library(renv)
.rs.clearVar("hello")
```

### Describe the problem in detail

`renv::remove()` rather than `base::remove()` is invoked after `renv` is loaded:

```
Warning in remove(list = fullName, pos = .rs.Env) :
  object '.rs.hello' not found
> library(renv)

Attaching package: 'renv'

The following object is masked from 'package:stats':

    update

The following objects are masked from 'package:utils':

    history, upgrade

The following object is masked from 'package:rmarkdown':

    run

The following object is masked from 'package:devtools':

    install

The following objects are masked from 'package:base':

    load, remove

> .rs.clearVar("hello")
Error in remove(list = fullName, pos = .rs.Env) : 
  unused arguments (list = fullName, pos = .rs.Env)
Traceback (most recent calls last):
4: .rs.clearVar("hello")
3: remove(list = fullName, pos = .rs.Env)
2: renv_dots_check(...) at remove.R#25
1: stop(err) at dots.R#32
```

### Describe the behavior you expected

Internal RStudio tools shouldn't be affected by the search path.

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rich-rstudio** [comment]
verified in Version 1.3.897
