### ISSUE TITLE
What about "X" for "Accessibility" accelerator key?

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rstudio#6410]
Current "Accessibility" accelerator key is assigned "E" under "Help" main menu in RStudio Desktop and Server.

I understand "A" has been preoccupied by "About" menu already.

Would "X" sound more similar to "Accessibility" instead of "E" then?

**Comment by gtritchie** [comment]
Unfortunately the way these work requires using a letter in the label. For a sighted user it shows that letter underlined indicating they can hit that select to select the item.

**Comment by gtritchie** [comment]
Fixed by https://github.com/rstudio/rstudio/pull/6431

I switched "About" to use the letter "B", and "Accessibility" to use the letter "A".
