### ISSUE TITLE
Make default indention in the source pane tidyverse-style-compliant

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/rstudio#6411]
When coding in the source pane of RStudio, breaking the line in a function call creates indention that is relative to the length of the name of the function (if there is already an argument on the first line: 
```r
this_is_a_long_call(y,
                    x = "after breaking the line I end here")
```

This is incompatible with the [tidyverse style guide section 2.5](https://style.tidyverse.org/syntax.html#), which would require
```r
this_is_a_long_call(y,
  x = "after breaking the line I end here"
)
```
If all but the first argument is named. If none is named, the line should even be broken before `y`. If the user breaks the line, the indention is already two spaces.

I think RStudio should by default just indent two spaces plus put the closing brace on a new line, but since this will be a rather significant change, there should be an option in settings to enable the current handling. 

This issue is supported by Hadley Wickham in https://github.com/r-lib/styler/issues/616

**Comment by ronblum** [comment]
@lorenzwalthert Thank you for filing the issue! What happens if you uncheck the following global option? 
- Tools -> Global Options -> Code -> Editing -> Vertically align arguments in auto-indent
I believe that when unchecked, it works as you describe. Note that the indentation will be the value of "Tab width" in the same pane.

**Comment by lorenzwalthert** [comment]
Indeed, you are right. How could I miss that... any considerations about making this the default? I think when the box is checked, hitting enter should also move the parenthesis to the next line, the same way it moves the parenthesis to the next line when you are 
```r
call( )
~~~~~^ if I am here and I hit enter
```

I get
```r
call(
  
~^ cursor
)
```

But when I already typed the first argument and hit enter, this does not happen, I will end up like this
```r
call(x = 3,
  )
~^ cursor
```

**Comment by ronblum** [comment]
@lorenzwalthert No sweat—it took me a couple of moments to recall the option. There are a lot to keep track of.

I can't reproduce the cursor-issue on RStudio Desktop or Server. However, can you file a separate issue for it? This way we keep this ticket as an enhancement request for the checking option by default, and track the bug separately.

**Comment by lorenzwalthert** [comment]
Sure. There was also an issue with formatting and I can try to make it more clear, maybe with a GIF.

**Comment by lorenzwalthert** [comment]
Well the question for here then remains to make this box checked the default I guess.

**Comment by kevinushey** [comment]
To be clear, according to the style guide vertical alignment is okay for function _definitions_:

```
# Good
long_function_name <- function(a = "a long argument",
                               b = "another argument",
                               c = "another long argument") {
  # As usual code is indented by two spaces.
}
```

But not for function _calls_:

```
# Bad
do_something_very_complicated("that", requires, many, arguments,
                              "some of which may be long"
                              )
```

That said, compliance with the Tidyverse style guide is not an explicit goal of RStudio's indentation system, and not all users of RStudio want to explicitly adhere to the Tidyverse style guide. This particular deviation is (IMHO) a fairly minor one.

We should make it possible to extend the indentation rules so that users can have more control over how things are indented, though.

**Comment by lorenzwalthert** [comment]
> We should make it possible to extend the indentation rules so that users can have more control over how things are indented, though.
 
Well in my understanding the user has already enough power with the option *Vertically align arguments in auto-indent* described above. It's just that when it's unchecked, the closing brace should move to the next line. As suggested by @ronblum, I'll open a separate issue to discuss this.

**Comment by lorenzwalthert** [comment]
I filed #6472 and also fixed an error in the description where I said above the undesired behaviour occurs when the box is checked, but it's actually when it is **not** checked.

**Comment by lorenzwalthert** [comment]
Related to what @kevinushey said: under section 3.2 in the tidyverse style guide, the argument *should* be indented for function declarations: 

```r
# Good
long_function_name <- function(a = "a long argument",
                               b = "another argument",
                               c = "another long argument") {
  # As usual code is indented by two spaces.
}

# Bad
long_function_name <- function(a = "a long argument",
  b = "another argument",
  c = "another long argument") {
  # Here it's hard to spot where the definition ends and the
  # code begins
}
```

This creates a conflict with the option *Tools -> Global Options -> Code -> Editing -> Vertically align arguments in auto-indent*, because it can never be style-guide-compliant for both function calls and declarations at the same time.
