### ISSUE TITLE
Build process for Windows outdated

### ISSUE THREAD

**Issue by Katzmann1983** [rstudio/rstudio#6412]
### System details

    RStudio Edition : latest
    RStudio Version :  latest
    OS Version      :  Windows 8
    R Version       : latest

### Steps to reproduce the problem
Try to follow the installation on Windows. Qt 5.12.6 is not available in the current Windows QT installer.

### Describe the problem in detail
The current QT installer allows only to install QT 5.12.7 or Qt 5.12.5. In the installation for windows requirements it states to install 5.12.6

### Describe the behavior you expected
Possible to build on a Windows machine

**Comment by ronblum** [comment]
@Katzmann1983 Thank you for filing the issue. What version of RStudio are you using? You state that it's the latest, but I'm not sure if you mean the GA release, 1.2.5033, or one of the preview releases, currently 1.3.887. Thanks!

**Comment by gtritchie** [comment]
@ron I believe they are trying to build from source. It is still possible to install 5.12.6 via the Qt online installer or to download the offline installer. I will update the instructions with details.

**Comment by tmcduff** [comment]
Available QT versions. 


![Screen Shot 2020-03-06 at 9 35 37 AM](https://user-images.githubusercontent.com/7966616/76107649-fc87b100-5f8d-11ea-84d7-464767ca4ec2.png)

**Comment by gtritchie** [comment]
Short answer, click "Archive" checkbox, then "Filter" button, and all versions will be available. About to update the README with that info.
