### ISSUE TITLE
cursor loses focus before right click paste and no paste occurs

### ISSUE THREAD

**Issue by HanOostdijk** [rstudio/rstudio#6413]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 1.3.889
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : 3.6.0 (2019-04-26)

### Steps to reproduce the problem
Start RStudio. The console has a black blinking cursor. Use 'Copy' at an arbitrary piece of text from somewhere outside RStudio. Left-click within the console panel. Right-click to initiate 'Paste' and the cursor no longer blinks and color becomes gray instead of black (loses focus?) When I select 'Paste' in the pop-up menu nothing happens (i.e. the pop-menu disappears but no text is pasted). 

### Describe the problem in detail
This is specific for RStudio: the 'Paste' in another application always succeeds .
Sometimes when I use the menu Edit I see that the cursor remains black so that I could do the 'Paste' but when I then again do the right-click the cursor becomes gray again.

### Describe the behavior you expected
I expect that I can always paste in an edit window (e.g. the console pane) that has focus.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks; I can reproduce this issue.

To be clear, it depends on where exactly you right-click:

1. If you right-click on the console history (text above the console input line), the paste attempt fails.
2. If you right-click on the console input line directly, the paste attempt succeeds.

This is a regression; it works as expected with RStudio v1.2.

**Comment by gtritchie** [comment]
Strongly suspect I caused this with a recent accessibility change. Investigating.

**Comment by rich-rstudio** [comment]
verified in Version 1.3.897
