### ISSUE TITLE
Tutorial pane doesn't indicate that rstudioapi version 0.11+ is required

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6418]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.889
    OS Version      : Multiple
    R Version       : 3.6.x

### Steps to reproduce the problem

Make sure you have a version of `rstudioapi` earlier than 0.11, which is probably what you have. Also, remove `learnr` if you have it, which you probably don't have if you haven't used tutorials before.

1. Go to the Tutorial pane.
    - You should see a message that states that `learnr` is required
2. Click on "click here."
    - `learnr` should get installed.
    - Several tutorials should appear in the Tutorial pane.
3.  Next to "Data Basics," click on "Start Tutorial."
    - The tutorial should hang.
    - The error message described in #6177, `object 'tutorialLaunchBrowser' not found`, should appear.
4. In the console, update the `rstudioapi` package with `install.packages("rstudioapi")`.
5. Click on the home icon in the Tutorial pane.
6. Next to "Data Basics," click on "Start Tutorial."
     - The tutorial should now run.

### Describe the problem in detail

Tutorials in the Tutorial pane require `rstudioapi` version 0.11, the current version on CRAN. However, there is no indication of this. 

See #6177 for the problem this causes.

### Describe the behavior you expected

Provide an easy method to install the a version of `rstufdioapi` >= 0.11, similar to the instructions and click to install `learn`. Or, at least, let the user know that it's needed.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
![tutorial_1](https://user-images.githubusercontent.com/31009952/76119381-49cf4700-5fbd-11ea-8838-899fca8f0cdb.png)

After clicking on "click here:"
![tutorial_2](https://user-images.githubusercontent.com/31009952/76119380-49cf4700-5fbd-11ea-8adb-e665fbb7cc80.png)

After running the tutorial:
![tutorial_3](https://user-images.githubusercontent.com/31009952/76119379-4936b080-5fbd-11ea-9370-e0a9de18746d.png)

After updating to `rstudioapi` version 0.11:
![tutorial_4](https://user-images.githubusercontent.com/31009952/76119378-4936b080-5fbd-11ea-9904-f2fa5d259e65.png)

**Comment by jmcphers** [comment]
@kevinushey Do we just need to add `rstudioapi` here:

https://github.com/rstudio/rstudio/blob/a87092af32b1e67355d1572abe7d4c5225119000/src/cpp/session/resources/dependencies/r-packages.json#L529-L534

**Comment by kevinushey** [comment]
@jmcphers I believe that's correct. I'll verify and submit a PR.

**Comment by rich-rstudio** [comment]
@kevinushey I was able to reproduce this on MacOS desktop Version 1.3.897, should that build have this fix?

**Comment by kevinushey** [comment]
I can reproduce as well as long as an older version of `rstudioapi` installed.

**Comment by rich-rstudio** [comment]
verified on Version 1.3.908
