### ISSUE TITLE
Continue comment on new line is falsely activated in markdown

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#6421]
# System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.3.879
    OS Version      : macOS  10.15.3
    R Version       : R version 3.6.0 (2019-04-26)

### Steps to reproduce the problem

1. Turn "continue comment when when inserting new line"
2. Open an markdown document
3. Type `# Heading` and press enter

### Describe the problem in detail

The next line starts with a `#`.

### Describe the behavior you expected

A heading is not a comment so you shouldn't get another `#`.

**Comment by ronblum** [comment]
Reproduced on Windows 10 using RStudio Desktop 1.3.895.

**Comment by hadley** [comment]
Please keep me alive 🧑‍⚕️

**Comment by astayleraz** [comment]
I verified on mac with Version 1.4.1572-4 R 4.0.3 that adding a new line via steps outlined is no longer adding # on the new line. Closing as fixed.
