### ISSUE TITLE
RStudio crashes when using python/reticulate

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#6423]
R version 3.6.1
RStudio Version 1.2.5033
reticulate version ‘1.14.9001’
‘rmarkdown’ version 2.1
‘knitr’ version 1.28
anaconda python version 3.7.6
I have set up the python using the use_python(<path to anaconda python>)

When I add a new python chunk and start typing "import pand..." Rstudio crashes every single time. 
Even if I don't try to import and simply "print(1)" it crashes when the chunk is executed. 
The enclosed screens have other details. 
Can someone help advise what is causing this crash?

I have retried this with Preview RStudio-1.3.878 and daily build RStudio-1.3.879 and still the same issue.

<img width="944" alt="delete_2" src="https://user-images.githubusercontent.com/37381682/76139466-11d80a80-6076-11ea-958e-2463711aefae.png">
<img width="945" alt="delete_1" src="https://user-images.githubusercontent.com/37381682/76139469-169cbe80-6076-11ea-85b5-fdf20acc7e0d.png">

**Comment by vinaychuri** [comment]
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.14-9001

loaded via a namespace (and not attached):
[1] compiler_3.6.2  Matrix_1.2-18   tools_3.6.2     Rcpp_1.0.3      grid_3.6.2      knitr_1.28      jsonlite_1.6.1  xfun_0.12      
[9] lattice_0.20-38

**Comment by vinaychuri** [comment]
Updates from more debugging!
I downloaded an earlier version of RStudio from "https://rstudio.com/products/rstudio/older-versions/" version = 1.1.463

And reticulate, python, import pandas, import csv, view a data frame all work correctly.

My anaconda, python, R/Python packages have all remained the same. Hence it's likely an issue with latest version of RStudio ??

**Comment by ronblum** [comment]
@vinaychuri Thank you raising this issue. Can you provide a simple example of sample code, so that I can try to reproduce the issue? Thanks!

**Comment by vinaychuri** [comment]
@ronblum Thanks for the response.
The code is as simple as follows:

```{r}
library(reticulate)
use_python("/Users/vinaychuri/anaconda3/bin/python")
```

```{python}
print("1")
```

When I execute the python chunk it crashes with the enclosed screen. 
If you view my earlier comment, If I use RStudio version = 1.1.463 it works correctly.
Current RStudio Preview 1.3.878 & Daily build v1.3.879 also fail.


<img width="1007" alt="delete_3" src="https://user-images.githubusercontent.com/37381682/76221946-db4deb80-623f-11ea-88e9-c855ab695d44.png">

**Comment by vinaychuri** [comment]
Update from more debugging.
@ronblum 
I checked my backup laptop which did not have this issue for the R/Python app/package versions along with the PATH and environment details.

The reticulate package was the culprit. I had version reticulate version ‘1.14.9001’ which is likely the dev version. I installed the version ‘1.14’ and its **all working fine now**.

But still curious why RStudio kept crashing fatally with no logs being generated at ".rstudio-desktop/log" and what's new in reticulate ‘1.14.9001’ that caused it?

**Comment by markderry** [comment]
I also had this problem and I believe that I may have found the problem. If you look in your .bash_profile file I found that over successive installs of python, anaconda, Miniconda etc
mine looked like this:
`
# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
# added by Anaconda3 2018.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/markderry/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/markderry/anaconda3/etc/profile.d/conda.sh" ]; then
# . "/Users/markderry/anaconda3/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/Users/markderry/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
# added by Miniconda3 4.7.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/markderry/opt/miniconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/markderry/opt/miniconda3/etc/profile.d/conda.sh" ]; then
# . "/Users/markderry/opt/miniconda3/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/Users/markderry/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
`
I replaced all of this with
`
# Setting PATH for Python 3.6
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
`
and the crashes stopped.

**Comment by jmcphers** [comment]
This is a crash in Python land which we can't fix in RStudio (and should not repro with newer reticulate).

> But still curious why RStudio kept crashing fatally with no logs being generated at ".rstudio-desktop/log" and what's new in reticulate ‘1.14.9001’ that caused it?

The fatal crash was in rsession, which is a separate process. The preview version of RStudio has some crash reporting that will help if you're still seeing this:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by HaniJieunKim** [comment]
Hi! 

I am getting the same issue even after making all the updates. I would be very grateful for any pointers. Thank you!

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] reticulate_1.20             SingleCellExperiment_1.14.1 SummarizedExperiment_1.22.0
 [4] Biobase_2.52.0              GenomicRanges_1.44.0        GenomeInfoDb_1.28.1        
 [7] IRanges_2.26.0              S4Vectors_0.30.0            BiocGenerics_0.38.0        
[10] MatrixGenerics_1.4.0        matrixStats_0.59.0          Matrix_1.3-4               

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7             lattice_0.20-44        png_0.1-7             
 [4] bitops_1.0-7           grid_4.1.0             jsonlite_1.7.2        
 [7] zlibbioc_1.38.0        XVector_0.32.0         rstudioapi_0.13       
[10] tools_4.1.0            RCurl_1.98-1.3         DelayedArray_0.18.0   
[13] compiler_4.1.0         GenomeInfoDbData_1.2.6
```

```
> rstudioapi::versionInfo()
$citation

To cite RStudio in publications use:

  RStudio Team (2021). RStudio: Integrated Development Environment for R.
  RStudio, PBC, Boston, MA URL http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, PBC},
    address = {Boston, MA},
    year = {2021},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.4.1717’

$release_name
[1] "Juliet Rose"
```

**Comment by kevinushey** [comment]
Do you see the same crash outside of RStudio?

**Comment by HaniJieunKim** [comment]
Hi 

I get this error (see below) when running outside Rstudio. I've also tried reverting to reticulate version 1.14, and still get the same error. 

Many thanks for helping out!

```
> "py3" %>% 
+     use_condaenv(required = TRUE)
> umap_module=import("umap",convert=TRUE)

INTEL MKL ERROR: dlopen(/Users/hani/opt/anaconda3/envs/py3/lib/libmkl_intel_thread.1.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/hani/opt/anaconda3/envs/py3/lib/libmkl_intel_thread.1.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.1.dylib.
```

**Comment by kevinushey** [comment]
This should be fixed if you're using the development version of reticulate together with the daily builds of RStudio. https://dailies.rstudio.com

See https://github.com/ContinuumIO/anaconda-issues/issues/12478 for more details.

**Comment by HaniJieunKim** [comment]
Thanks! 

Unfortunately, I get the same error even after installing the daily builds of RStudio and the development version of reticulate. 

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
[1] reticulate_1.20-9002
```

```
> rstudioapi::versionInfo()
$citation

To cite RStudio in publications
use:

  RStudio Team (2021). RStudio:
  Integrated Development
  Environment for R. RStudio,
  PBC, Boston, MA URL
  http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, PBC},
    address = {Boston, MA},
    year = {2021},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.5.241’

$release_name
[1] "Ghost Orchid"
```


```
(py3) hani@192 ~ % R

R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(reticulate)
suppressPackageStartupMessages(library(dplyr))
> suppressPackageStartupMessages(library(dplyr))
> "py3" %>% 
+     use_condaenv(required = TRUE)

umap_module=import("umap",convert=TRUE)
> 
> umap_module=import("umap",convert=TRUE)
INTEL MKL ERROR: dlopen(/Users/hani/opt/anaconda3/envs/py3/lib/libmkl_intel_thread.1.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/hani/opt/anaconda3/envs/py3/lib/libmkl_intel_thread.1.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.1.dylib.
(py3) hani@192 ~ % R
```

**Comment by kevinushey** [comment]
😞  I'm sorry; I'll have to investigate further.

Until we get this sorted out, my recommendation would be to use a pure Python virtual environment and avoid Anaconda. I realize that's not a great solution (and might not be feasible in your case) but unfortunately supporting Anaconda installations has been quite challenging for us.

**Comment by kevinushey** [comment]
I've filed https://github.com/rstudio/rstudio/issues/9657 for us to follow up.

**Comment by HaniJieunKim** [comment]
Thank you! I will await your response. Again many thanks for your help!

**Comment by vinaychuri** [comment]
Can you also check if there are multiple python version on your system and if RStudio/reticulate is pointing to the correct python version?

**Comment by DavorJ** [comment]
> It appears to be incompatible with the MKL upgrade in Anaconda. You'll have to run the following within your virtual environment as outlined [here](https://docs.anaconda.com/mkl-optimizations/index.html): `conda install nomkl numpy scipy scikit-learn numexpr` `conda remove mkl mkl-service`

`nomkl` is [no longer part of Conda](https://stackoverflow.com/a/66228570/1548942). See [this answer](https://stackoverflow.com/a/67954011/1548942) for a more recent way to use `openblas`.

Note though that this has no impect on `reticulate` these days as it works fine with `MKL`.

**Comment by ParissaM** [comment]
Hello,

For my case I was reading the data from an S3 bucket and I had the same issue. what helped for me was adding in the Python function the following snippet:

```
for c in df.columns:
    df[c] = np.array(df[c].values)
```

For my case I was reading the data from an S3 bucket and I had the same issue. what helped for me was adding in the Python function the following snippet:

for c in df.columns:
    df[c] = np.array(df[c].values)
So the Python function would look like this:

```
def get_data_from_db(db_name, query):
    df = wr.athena.read_sql_query(
    sql=query,
    database=db_name,
    ctas_approach=False
    )
    for c in df.columns:
        df[c] = np.array(df[c].values) 
   return df
```
