### ISSUE TITLE
R Studio v1.2.5033 wrong column ID when dataset has more that 50 columns

### ISSUE THREAD

**Issue by borexino** [rstudio/rstudio#6435]
I'm running R Studio Version 1.2.5033 with R version 3.6.0 (2019-04-26) on Platform: x86_64-apple-darwin15.6.0 (64-bit) Running under: macOS Mojave 10.14.6.

I noticed that the **R Studio Viewer** gives wrong column IDs when it is working with DFs with more than 50 columns as shown below.

In the example it is possible to notice that the last colum which is the 100th is listed as 150th by the viewer.

`df <- data.frame(matrix(ncol = 100, nrow = 0))`

 
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/U68e8.png

**Comment by WilDoane** [comment]
Related open issues:

Ordering/filtering fails when Viewing dataframes with many columns 
 https://github.com/rstudio/rstudio/issues/5701

Data viewer fails to display data frames in list columns above column 50 https://github.com/rstudio/rstudio/issues/5851

Wrong sorting in data viewer if columns in view don't start from the first https://github.com/rstudio/rstudio/issues/4682

**Comment by ronblum** [comment]
@borexino Thank you for raising this, and thank you @WilDoane for. culling together the related issues! I can reproduce this in RStudio Desktop 1.2.5033. This is resolved in the most recent previews of RStudio 1.3 Middle Mist, which is available at https://rstudio.com/products/rstudio/download/preview/, currently 1.3.895-2.
