### ISSUE TITLE
Rstudio Document Outline

### ISSUE THREAD

**Issue by mark-druffel** [rstudio/rstudio#6441]
I use the document outline feature in RStudio, but it does not allow outline indentation inside of functions so it's hard to tell what sections are children. Below is a reproducible example:
```

my_function <- function(x,y){
  # Unconditional ====
  print("Set some variables for the function")
  # Condition 1 ====
  if(x>100){
    # Action 1 ====  
    print("Do some stuff to x")
    # Action 2 ====  
    z <- x*pi
    }
  # Condition 2 ====
  else if(y<=100){
    # Action 1 ====  
    print("Do some stuff to x")
    # Action 2 ====  
    z <- psigamma(y)
    }
  # Condition 3 ====
  else if(x<=100){
    # Action 1 ====  
    print("Do some stuff to x")
    # Action 2 ====
    z <- x+100
  }
  # Otherwise ====
  else{
    z <- x+y
  }
  return(z)
}

```

The outline shows Action 1 & 2 within Condition 1 as being on equal level even though they are subroutines of Condition 1. After Condition 1, the remaining conditions (2, 3, & Otherwise) show up on the same level as my_function, but they are all subroutines within my_function and the actions are subroutines of the conditions. 
![rstudio_document_outline](https://user-images.githubusercontent.com/5033488/76366694-f5430900-62e7-11ea-9740-5c8225b89a12.PNG)

I would want the outline to function like this: 
my_function
- Unconditional
- Condition 1
-- Action 1
-- Action 2
- Condition 2
-- Action 1
-- Action 2
- Condition 3
-- Action 1
-- Action 2
- Otherwise

**Comment by astraetech** [comment]
I think it would be very useful. Don't see why it went stale.
