### ISSUE TITLE
yank (ctrl + U) works when `View`ing a function

### ISSUE THREAD

**Issue by TylerGrantSmith** [rstudio/rstudio#6444]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows 10
    R Version       : 3.6.2

### Steps to reproduce the problem
View a function. i.e.,  `View(library)`  go the end of line 1 in the tab that is created and press CTRL-U to yank the line.
### Describe the problem in detail
This allows you to edit displayed lines in the `View`ed function.  
### Describe the behavior you expected
Since no other editing seems to be allowed (e.g. typing/deleting/cutting), this would seem to be unintentional behavior.  

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@TylerGrantSmith Thank. you for reporting this issue! I can reproduce it on RStudio Desktop 1.3.900 on MacOS 10.15.4 and RStudio Server 1.3.900 on Red Hat 7.8 using Chrome. We'll review this as we continue development of RStudio.

Note: This is also true in 1.1.453 and 1.2.5033, so this is not a regression.
