### ISSUE TITLE
Keyboard backslash issue in latest dailies 

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#6447]
In the latest dailies since approx yesterday I can't type a backslash anymore:

When I try to type a backslash ("\\") a "Confirm Toggle Screen Reader Support" window pops up. I can't see anything in keyboard shortcuts to deactivate this.
I am on a macbook with a french azerty keyboard, backslash is option + shift + :

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.905
    OS Version      : Catalina 10.15.3
    R Version       : 3.6.2

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gregleleu** [comment]
Caused by #6409

on azerty keyboard backslash is Alt+Shift+/ ...

**Comment by ronblum** [comment]
@gregleleu Thank you for raising this issue!

**Comment by gtritchie** [comment]
Will fix today, thanks for reporting this.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.3.910.
