### ISSUE TITLE
"Rename in Scope" ends at "Code Section"

### ISSUE THREAD

**Issue by SigurdJanson** [rstudio/rstudio#6453]
### System details

    RStudio Edition  : Desktop
    RStudio Version : 1.2.5033
    OS Version        : Win 10
    R Version           : 3.6.2

### Steps to reproduce the problem

Write yourself a function that uses code sections INSIDE the function. Now use "rename in scope" with a variable that is used in several code sections. R-Studio will only find those instances in the SAME code section.

I can reproduce this outside functions as well.

### Describe the problem in detail

Look at the code below. When I use "Rename in Scope" (Ctrl-Alt-Shift-M) on 'N' R-Studio only catches only those instance of 'N' between step 1 and step 2 (i.e. 1. and 2. comment). 

```
GenData <- function(Data, NObs, NFactors = 0) {
  # Initialize variables and (if applicable) set random number seed (step 1) ------------
  N <- NObs #-dim(Data)[1]           # Number of cases
  k <- ncol(Data) #-dim(Data)[2]     # Number of variables
  Data <- matrix(0, nrow = N, ncol = k) # Matrix to store the simulated data
  Distributions <- matrix(0, nrow = N, ncol = k) # Matrix to store each variable’s score distribution
  
  # Generate distribution for each variable (step 2) -----
  for (i in 1:k)
    Distributions[,i] <- sort(sample(Data[,i], N, replace = TRUE)) 

# ...
}
```

### Describe the behavior you expected

My expectation would have been that a scope is the whole function. If it is not, it is pretty dangerous to use and not useful for refactoring.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@SigurdJanson Thank. you for raising the issue! I can reproduce it in the same environment, as well as in RStudio Desktop 1.3.900 on MacOS 10.15.4 and Windows 10, and RStudio Server 1.3.898 on Red Hat 7.8. We'll review this as we continue development of RStudio. Thanks!
