### ISSUE TITLE
RStudio blank 

### ISSUE THREAD

**Issue by kristielee98** [rstudio/rstudio#6454]
RStudio shows up as blank for me. I am unable to type in the console or terminal, and I can't create or open any files. I've tried deleting and reinstalling R and RStudio but that doesn't seem to work. I've also tried restarting my laptop but am still running into this same problem. 

Here is a screenshot of what my RStudio looks like: 
![image](https://user-images.githubusercontent.com/31837744/76497092-95d41e80-63f7-11ea-85e0-44b520601cf9.png)

**Comment by ronblum** [comment]
@kristielee98 Thank you for raising the issue. Can you please provide system information for your environment? Thanks.

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jragusa** [comment]
Similar problem, I'm unable to open RStudio from a file and I have no more entry in Activity panel or terminal. Seems happen since the recent update.

```
RStudio Edition : Desktop
RStudio Version : rstudio-1.2.5033-10.fc31.src.rpm
OS Version      : Fedora 31
R Version       : R-3.6.3-1.fc31.src.rpm
```

**Comment by kristielee98** [comment]
Hi Ron, how do you provide the system information for environment? Not sure how to find that. Thanks!

**Comment by jmcphers** [comment]
Closing since we have nothing to go on here. @kristielee98 if you're still in trouble, you can probably fix this by resetting RStudio's state:

https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
