### ISSUE TITLE
RStudio problems with dev.new function ignoring width height

### ISSUE THREAD

**Issue by rkbauer** [rstudio/rstudio#6455]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.903
    OS Version      :  Ubuntu 16.04 64bit
    R Version       :  3.6.1

### Steps to reproduce the problem
`dev.new(width=10, height=5, xpos=-1)`

### Describe the problem in detail
The arguments "width", "height" and "xpos" are apparently
ignored when calling dev.new() from inside RStudio. By contrast, they
work when running R from the terminal.
It further seems that in the newest RStudio-version (1.3.903) the first function call of dev.new() is being ignored as no graphic window pops up, even if executed with no function arguments...

I initially reported this bug in 2017 via the RStudio-Support Website. The link to my original post is no longer accessible due to lack of authorization/restructuring of the RStudio Website:

[https://support.rstudio.com/hc/en-us/community/posts/115007613728-RStudio-problems-with-dev-new-function-ignoring-width-height?page=1#community_comment_115004938828](url)

### Describe the behavior you expected
Similar behavior as in the terminal or x11()-function calls.

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@rkbauer Thank you for raising this! I can reproduce this with RStudio Desktop 1.3.900 on Ubuntu . I see other issues on other platforms, including the first request ignored, on other platforms, so I'll file an issue for that. Thanks!

**Comment by rkbauer** [comment]
I would like to highlight that this issue still persists!
