### ISSUE TITLE
Ace rendering error when pasting long wrapped line

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6457]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.897
    OS Version      : macOS 10.15.3
    R Version       : 3.6.4

### Steps to reproduce the problem

Copy this line to your clipboard:

```
This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. 
```

Now, open a new R Markdown document, and paste the line twice separated by a newline so the contents are now:

```
This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. 

This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. This is a long, wrapped line. 
```

Now follow these steps:

1. Click somewhere into the second wrapped line,
2. Press and hold the <kbd>Cmd</kbd> key,
3. Click somewhere into the first wrapped line,
4. Press <kbd>P</kbd> to paste from the clipboard.

### Describe the problem in detail

Some percentage of the time, the text is improperly rendered (overlaid) in the document.

<img width="432" alt="Screen Shot 2020-03-12 at 10 28 53 AM" src="https://user-images.githubusercontent.com/1976582/76548731-72878e80-644c-11ea-9068-587c6e84c819.png">

### Describe the behavior you expected

No rendering issue.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Notes

Initial reprex from @hadley.

**Comment by kevinushey** [comment]
See also:

https://github.com/ajaxorg/ace/issues/3997
https://github.com/ajaxorg/ace/pull/3998

**Comment by jmcphers** [comment]
Fixed by https://github.com/rstudio/rstudio/pull/6468.

**Comment by rich-rstudio** [comment]
verified in Version 1.4.77
