### ISSUE TITLE
RMarkdown doesn't recognize C comments in code chunk

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#6458]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.910
    OS Version      : Ubuntu 18
    R Version       : 3.6.2

### Steps to reproduce the problem

1. Add a `{c, eval=FALSE}` code chunk to an RMarkdown document.
2. Put C-style comments (`//` or `/* */`) in the chunk that include `'` or `"`.

### Describe the problem in detail
The code highlighting in the editor still treats the contents of the comments like code. `'` and `"` are treated like string openings. This doesn't occur if R style comments (`#`) are used instead. The knit document highlights comments correctly.

C-style comments in the editor:
![image](https://user-images.githubusercontent.com/37987486/76554938-f5f8ae00-6453-11ea-8b18-75f2ae4e31a5.png)

Result of inspecting a c-style comment:
![image](https://user-images.githubusercontent.com/37987486/76555543-0f4e2a00-6455-11ea-9c16-b08566a15865.png)

R-style comments in the editor:
![image](https://user-images.githubusercontent.com/37987486/76555042-23ddf280-6454-11ea-9df2-37a7a675f464.png)

Result of inspecting an R-style comment:
![image](https://user-images.githubusercontent.com/37987486/76555573-1f660980-6455-11ea-8595-fae86e2aada8.png)

Knit document: 
![image](https://user-images.githubusercontent.com/37987486/76555359-b67e9180-6454-11ea-9035-7d11b4c88dbd.png)

### Describe the behavior you expected
C-style comments should also be treated as comments.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It looks like R highlight rules are being used for C-engine chunks.

Note that C++ chunks (using Rcpp) should work fine, and this is more common. For example:

`````
```{Rcpp}
#include <Rcpp.h>
```
`````

**Comment by MariaSemple** [comment]
Setting Rcpp changed the highlighting rules for me. That's a big improvement, thanks! Are the highlight rules chosen in IDE code? If so, can you point me there?

**Comment by kevinushey** [comment]
This is where we embed highlight rules for R Markdown documents:

https://github.com/rstudio/rstudio/blob/47126b659470c0f1e5d9adb49881938063ec7c0e/src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js#L66-L74

And this is the gnarly regex we use to detect the editor language in the chunk header:

https://github.com/rstudio/rstudio/blob/47126b659470c0f1e5d9adb49881938063ec7c0e/src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js#L192

**Comment by DavisVaughan** [comment]
This is fixed by #6462 now right? Thanks @MariaSemple this was annoying me too!
