### ISSUE TITLE
Ctrl+Shift+2 may create two new files instead of one in Source pane

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6459]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.910
    OS Version      : MacOS 10.15.4 & Ubuntu 18.04.4 (Desktop), Red Hat 7.8 (Server) connected from MacOS
    R Version       : 3.6.x

### Steps to reproduce the problem

1. Close all open files: File -> Close All
2. Ctrl+Shift+2, which is supposed to maximize the Console pane
    - The Source pane is maximized
    - There are two new files: Untitled1 and Untitled2
3. Ctrl+Shift+2
    - Server: The IDE is back to four-pane layout
    - Desktop: The Console pane is maximized
4. Ctrl+Shift+2
    - Server: The Console pane is maximized
    - Desktop: The IDE is back to four-pane layout

### Describe the problem in detail

If no files are open, Ctrl+Shift+2 results in a maximized Source pane (not Console) and two new file tabs are created.

### Describe the behavior you expected

1. If there are no files, Ctrl+Shift+2 should still maximize the Console pane, not Source
2. Only one new file should get created when the Source pane is (correctly) shown. This said, only one file is created when using Ctrl+Shift+1.

Note that Windows Ctrl+Shift+2 isn't working at all, both Desktop and connecting to Server from Firefox and Chrome, so that's a separate issue.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I tried running these steps and got 5 new untitled tabs opened up a few times as well.

**Comment by gtritchie** [comment]
Some of this weirdness repros with 1.2.5033 (only tried Mac desktop).
