### ISSUE TITLE
current rstudio 1.1.456 build forces downgrade to 4 year old pyqt release

### ISSUE THREAD

**Issue by mjanson** [rstudio/rstudio#6470]
Please fix this, it is not pleasant to have my python environment tainted by trying to interop with R:

$ conda install rstudio
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/maj/anaconda3/envs/stat222

  added / updated specs:
    - rstudio

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyqt-5.6.0                 |   py37h22d08a2_6         4.4 MB
    sip-4.18.1                 |   py37hf484d3e_2         261 KB
    ------------------------------------------------------------
                                           Total:         4.6 MB
...
The following packages will be DOWNGRADED:

  pyqt                                 5.9.2-py37h05f1152_2 --> 5.6.0-py37h22d08a2_6
  qt                                       5.9.7-h5867ecd_1 --> 5.6.3-h8bf5577_3
  sip                                 4.19.8-py37hf484d3e_0 --> 4.18.1-py37hf484d3e_2

Proceed ([y]/n)?

**Comment by kevinushey** [comment]
We are not responsible for the versions of RStudio distributed with Conda. You will have to either raise this with the Anaconda team, or consider instead using the official RStudio binaries released at https://rstudio.com/products/rstudio/download/.
