### ISSUE TITLE
No scroll bar arrows in dark themes

### ISSUE THREAD

**Issue by JoachimP1** [rstudio/rstudio#6477]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows 10, version1903, build 18362.720
    R Version       : 3.6.2 (2019-12-12)

### Steps to reproduce the problem
Setting any dark theme: tools --> global options --> appearance --> RStudio theme: 'modern' + editor theme: for example the dark theme 'Monokai'

### Describe the problem in detail
The problem is that when you use a dark theme that the scroll bar arrows disappear. So you cannot scroll very accurate anymore.

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I believe this is the same thing as #4594
