### ISSUE TITLE
RStudio freezes after I switch to another program/app

### ISSUE THREAD

**Issue by bartonicek** [rstudio/rstudio#6478]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5033
    OS Version      :  Windows 10
    R Version       :  3.6.3

### Steps to reproduce the problem

1. Run RStudio
2. Switch to other application (e.g. Google Chrome)
3. Return to RStudio, RStudio does not respond (i.e. the vertical line cursor is not blinking, nothing except closing RStudio works).

### Describe the problem in detail

I've been having this problem for a while working on my home computer (a laptop) and it's been around for a couple of R versions, but I've only gotten around to reporting it now. What happens is that when I run RStudio and then switch to another program/app (e.g. Microsoft Word, Google Chrome, etc...), upon returning RStudio is frozen. By "frozen", I mean that I can't type or click on anything, and the cursor is not blinking either. The only thing I'm able to do is close RStudio, save my workspace after getting a prompt (silver lining), and run RStudio again. 

As far as I'm able to tell, the issue isn't tied to elapsed time - it can happen after tabbing away for just a few seconds, and other times RStudio will be running fine after I've came back after several minutes. It doesn't seem to be related to whether I'm actually running any code either - sometimes RStudio freezes even when it's just sitting idle, not running any R script. It does seem to be related to switching to another program though - if I leave a long script running for an hour or so without switching away from RStudio, then it finishes running just fine, but I tab away for a few seconds and it's frozen.

I've found this closed issue that seems to be similar to mine: https://github.com/rstudio/rstudio/issues/3850. The way how the issue was solved goes a bit over my head however - probably because I'm a beginner user and am running Windows.

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by BastiHz** [comment]
I seem to have the same problem as described above, also on Windows 10 and RStudio 1.2.5033. This seems to happen randomly after switching back to RStudio from another application. I have not yet found a way to trigger this bug reliably.

When this happens I am sometimes able to regain control by randomly and repeatedly minimising/maximising/windowing the program a few times and/or dragging the window around and/or switching back and forth to other applications. But other times nothing but restarting RStudio helps.

This has not yet happened on my private Linux Kubuntu machine with the RStudio Preview. But I can't test 1.3 on my work computer until the official release.

**Comment by ronblum** [comment]
@bartonicek and @BastiHz Thank you for filing the issue and providing more information on about it! I can't reproduce it, though. Would you be willing to try out [the latest 1.3 preview release](https://rstudio.com/products/rstudio/download/preview/)? Preview builds are meant for development and testing, but they're fairly stable at this point.
