### ISSUE TITLE
Crash after change language

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/rstudio#6483]
### System details

    RStudio Edition : desktop
    RStudio Version : v1.3.911-1 Preview
    OS Version      : Win 10 Pro
    R Version       : 3.6.3

### Steps to reproduce the problem
I cannot reproduced it, I can report what I was doing:
- xaringan presentation
- renv eneabled
- infinite moon reader on
- went to the option, download additional languages for dictionaries
- set italian language
- press: apply.

everything crash and still crashed!

### Describe the problem in detail
RStudio is completely freazed. I cannot do anything, neither stop it. If I kill the wholl process and re run it it still freazed,both if I start a new instanse of RStudio form the app launcher, and if I start it from a project file. I cannot type anything on the console, no button works. Menus are displayed (if I click, e.g., on "file" it shows the file menu, but no item works; the same for the help one to produce some diagnostic). I can try to log-off/log-in from teh user, restart the PC, reinstall RStudio... anything change. I cannot simply use it :-)

I cannot provide the diagnostic report because it throw the following error
```
Attempting to launch R session...
  R_HOME=C:\PROGRA~1\R\R-3.6.3
  PATH=C:\Program Files\R\R-3.6.3\bin\x64;C:\Rtools\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Rtools\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\WinSCP\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\corra\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\PyCharm Edu 2019.1\bin;;C:\texlive\2019\bin\win32;C:\Program Files\JetBrains\PyCharm 2019.1.3\bin;

R session launched, attempting to connect on port 11215...

Connected to R session, attempting to initialize...

Successfully initialized R session.

17 Mar 2020 09:02:49 [rsession-corra] ERROR r error 4 (R code execution error) [errormsg: Error in system(binaryPath, intern = TRUE) : 'C:\Program' not found
]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::r::exec::`anonymous-namespace'::evaluateExpressionsUnsafe(struct SEXPREC *,struct SEXPREC *,struct SEXPREC **,class rstudio::r::sexp::Protect *,enum rstudio::r::exec::`anonymous-namespace'::EvalType) src/cpp/r/RExec.cpp:171; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::session::module_context::sourceDiagnostics(void) src/cpp/session/SessionModuleContext.cpp:2227

C:\Program Files\RStudio>
```

### Describe the behavior you expected

Rstudio works... in whatever way :-)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio (preview) and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
To be clear, are you saying that downloading and enabling the Italian dictionary here:

<img width="596" alt="Screen Shot 2020-03-18 at 1 57 07 PM" src="https://user-images.githubusercontent.com/1976582/77006828-60ac5c80-6920-11ea-83ee-aaffdcc21cc9.png">

caused RStudio to stop functioning?

**Comment by kevinushey** [comment]
If you haven't already, you can try resetting RStudio's state: https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by adamconroy** [comment]
I just tested and it appears that the realtime spellchecking isn't compatible with the Italian dictionary that we download, we've found that many of the dictionaries that we ship with are just too heavy for the Typo.js library. https://github.com/rstudio/rstudio/issues/6041

I'll look for an alternative Italian dictionary and ask if we should blacklist this one as well. 

@CorradoLanera sorry you ran into this, I recommend turning off realtime spellchecking for now while using the Italian dictionary and I'll work to resolve this.

**Comment by CorradoLanera** [comment]
thank you @adamconroy. 
@kevinushey I will try resetting RStudio, and re-install the preview version!
Thanks.

**Comment by CorradoLanera** [comment]
I have changed the dictionary in `%appdata%\RStudio` from "it_IT" to "us_US", reinstalled the preview version, and it works properly.

For the moment, I do not activate the Italian dictionary.

**Comment by adamconroy** [comment]
Closing this issue now as it is now automatically rolled into #6116
