### ISSUE TITLE
Maintain consistent focus after dialog boxes

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6484]
After showing a modal dialog box, must return focus to the place it was before the dialog box was shown (unless the dialog box specifically sets focus somewhere when it closes).

From https://www.w3.org/TR/wai-aria-practices/#dialog_modal

>When a dialog closes, focus returns to the element that invoked the dialog unless either:
The invoking element no longer exists. Then, focus is set on another element that provides logical work flow.
The work flow design includes the following conditions that can occasionally make focusing a different element a more logical choice:
It is very unlikely users need to immediately re-invoke the dialog.
The task completed in the dialog is directly related to a subsequent step in the work flow.

**Comment by gtritchie** [comment]
This is generally working now, #7908 helped with cases involving using the main menu (on server) via keyboard.

If we find additional problems, we can open specific issues on the scenario(s).

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990
