### ISSUE TITLE
Dark theme text color applied to HTML widgets in R Notebooks with htmltools 0.4.0

### ISSUE THREAD

**Issue by glin** [rstudio/rstudio#6489]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033 (and also reproduced in 1.4.52) 
    OS Version      : Windows 10
    R Version       : 3.6.1

### Steps to reproduce the problem
Use a dark editor theme such as Dracula. Install the latest htmltools 0.4.0 and view an HTML widget in an R Notebook. The theme's text color will be applied to the output, making it hard to read text in widgets that don't set explicit text colors, like DT or dygraphs.

For example, using DT:
![image](https://user-images.githubusercontent.com/20401866/76923255-ef799480-68a0-11ea-99c7-ec898cc3b89b.png)

This only happens with htmltools 0.4.0. If you install the previous version of htmltools, 0.3.6, the theme's text color isn't applied and the table looks fine:
```r
devtools::install_version("htmltools", "0.3.6")
```
![image](https://user-images.githubusercontent.com/20401866/76923411-4ed7a480-68a1-11ea-874d-7b143f1beb6c.png)

### Describe the problem in detail
I think this issue was already fixed before in https://github.com/rstudio/rstudio/issues/1615, but htmltools 0.4.0 changed something that made it stop working. I'd guess it's this change to set the background color using CSS instead of inline styles: https://github.com/rstudio/htmltools/commit/f74b2aff9d4b98c43323307dee43f9c903a2a09f

If I run an HTML tag chunk that uses CSS to set a background color on the body, the theme's text color gets applied:
![image](https://user-images.githubusercontent.com/20401866/76923918-cc4fe480-68a2-11ea-9e70-51608300c31a.png)

Using an inline style instead, the theme's text color doesn't get applied:
![image](https://user-images.githubusercontent.com/20401866/76923922-ceb23e80-68a2-11ea-9132-0bcbedc9e5a6.png)

### Describe the behavior you expected

A dark editor theme's text color shouldn't be applied to HTML widgets in R Notebooks - see screenshot above with htmltools 0.3.6.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@glin Thank you for filing this issue! We're reviewing as part of our development of RStudio.

**Comment by jcheng5** [comment]
Might also have been https://github.com/rstudio/htmltools/commit/dd12341505805357b5afe231f68e675d1c88fef9

**Comment by kevinushey** [comment]
It looks like this does indeed affect all HTML widgets rendered within RStudio, at least to some degree.

If I recall correctly, we try to adjust the styles for "raw" HTML rendered in the IDE; e.g. for a chunk like:

`````
```{r}
knitr::asis_output("<p>Hello, world!</p>")
```
`````

as otherwise the text would effectively be invisible.

This is done here:

https://github.com/rstudio/rstudio/blob/1f9643c37d5e37e507c02adee00e591b6f9b9d20/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkHtmlPage.java#L119-L127

The simplest fix (as per @jcheng5) may be to check the computed styles, as opposed to the style set on the element.

**Comment by JMLuther** [comment]
I'm still looking for a workaround for this issue, to be able to preview html output in dark mode preview in an Rmd doc. 
Text is output but in dark text on dark background, visible only when it is selected...

![image](https://github.com/rstudio/rstudio/assets/21051511/f159ddce-c1d6-44e6-8152-020fbd9513ea)
![image](https://github.com/rstudio/rstudio/assets/21051511/ba0c33c1-126a-4369-802c-4df40e89a252)
