### ISSUE TITLE
Can't close RStudio after editing a RMarkdown file

### ISSUE THREAD

**Issue by diegoquintanav** [rstudio/rstudio#6493]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.5033
    OS Version      :  Linux Mint 19.3

```sh
$cat /etc/*release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic

```
    R Version       : 3.6.3 

```$R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

### Steps to reproduce the problem

Opened RStudio, ran a chunk in an existing RMarkdown file with no errors. Attempted to close Rstudio and it is hooked on closing the session, until my laptop freezes (or runs out of memory, I think)

![image](https://user-images.githubusercontent.com/16281387/77054628-4a5dd980-69d0-11ea-9f6a-44fcc1597cda.png)

### Describe the problem in detail

I can't close RStudio without killing the processes directly (using sigterm). 

I've tried isolated cases, and it happens only when I edit a specific Rmarkdown file, and running other Rmarkdown files does not raise this issue. I can't reproduce the problem, so I've been trying to inspect the logs, since I'm out of ideas. I can only provide the code that I'm using. 

[lab01.zip](https://github.com/rstudio/rstudio/files/4354014/lab01.zip)

The logs (diagnostics->show logs) don't have info about this. It seems that Rstudio is stuck in a loop, consuming memory until my laptop freezes. 

### Describe the behavior you expected

RStudio closes normally.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4353958/diagnostics-report.txt)
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by diegoquintanav** [comment]
I don't know if it makes sense, but after editing the RMarkdown header from

```yml
output:
  html_notebook: default
  pdf_document: default
```
to 

```yml
output:
  html_document: default
  pdf_document: default
```

Solves the issue. But I have no idea why.

**Comment by ronblum** [comment]
@diegoquintanav Thank for filing the issue! We technically don't support Linux Mint; the [supported platform list is listed here](https://rstudio.com/about/platform-support/). That said, would you be able to try [the preview of the upcoming 1.3 Middlemist Red release](https://rstudio.com/products/rstudio/download/preview/)? Previews are meant for development and testing purposes, but they're pretty stable at this point.

**Comment by kevinushey** [comment]
Most likely, the IDE is hanging while attempting to generate the Notebook preview.

If you could find a minimally reproducible example, we could investigate further.

**Comment by diegoquintanav** [comment]
I'm suspecting `pandoc` for the moment, as it is spawning some processes on closing the session. I will have something during the weekend.

**Comment by diegoquintanav** [comment]
I can't reproduce the issue, sorry. You may close this issue if you feel like it. Thanks!
