### ISSUE TITLE
"Manual Refresh Only" of Environment Pane Neglected when Returning from Browser/Debugger

### ISSUE THREAD

**Issue by akersting** [rstudio/rstudio#6494]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.869
    OS Version      :  Linux
    R Version       :  3.5 / 3.6

### Steps to reproduce the problem

1. Start a new session in RStudio
2. Select "Manual Refresh Only" in the Environment pane
3. Run `f <- function(x) browser()`.
4. Confirm that Environment pane is still empty for the Global Environment.
5. Run `f()`.
6. Confirm that Environment pane is empty while in debugger.
7. Return from debugger in any way (Stop, Continue, Next).
8. Environment pane shows `f` in the Global Environment.

### Describe the problem in detail
"Manual Refresh Only" is neglected when returning from the browser/debugger in step 8.

### Describe the behavior you expected
The Environment pane is not refreshed when returning from the browser when "Manual Refresh Only" is selected. For me this is a major issue if you have many complex objects in the Global Environment as it slows down returning from the browser dramatically and makes debugging a pain.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@akersting Thank you for filing the issue, and providing the simple steps to reproduce! I can reproduce this in RStudio Desktop 1.3.910 on MacOS 10.15.4 and RStudio Server 1.3.910 on Red Hat 7.8. We'll review this as we continue development of RStudio.

**Comment by akersting** [comment]
I dug a bit into this issue because it is really bothering my colleagues and me. 

It seems to come from the environment being shown in the Environment tab changing when returning from the debugger. And this change in environments apparently triggers the refresh.

What is worse is that stepping through the statements with the debugger makes the environment shown in the tab sometimes switch between the frame of the function being debugged and the Global Environment. This again seems to trigger a refresh of the Global Environment making debugging itself slow. This switch seems to happen mainly when executing a long running statement.

I worked around the issue by replacing `refreshView()` at https://github.com/rstudio/rstudio/blob/v1.3/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java#L191 with `refreshViewIfEnabled()`. Now, a manual or automatic switch of the environment in the Environment tab no longer updates the list of objects if "Manual Refresh Only" is selected.
