### ISSUE TITLE
Don't send empty newline to browser() when running selected lines

### ISSUE THREAD

**Issue by zerweck** [rstudio/rstudio#6496]
When using the browser() functionality, I might for whatever reason run a selected piece of code from the editor at the current browser position. However, if I select and run code containing empty lines, it will trigger the browser's reaction to run the next step in the function I am browsing.
It seems as if newlines at the beginning and end of my selection are ignored, but not in between valid code. Minimal example:
```R
funToBrowse <- function() return("I don't want to end up here accidentally")
debugonce(funToBrowse)
funToBrowse()

# Code to select and run during browsing
###### Start selection after this line

1+1

1+1

###### End selection so the Textcursor is on the previous line
```

If the selection is made as described in the comments, and then sent to the console via "Run Selection", the first and last newline do nothing, but the newline between the 1+1 statements triggers the browsers step. My console output looks like this:
```R
> funToBrowse()
debugging in: funToBrowse()
debug at #1: return("I don't want to end up here accidentaly")
Browse[2]> 1+1 
[1] 2 
Browse[2]>  exiting from: funToBrowse() 
[1] "I don't want to end up here accidentally" 
> 1+1 
[1] 2
```

**Comment by ronblum** [comment]
@zerweck Thank you for filing the issue. I can't reproduce it, though. Can you please provide the the system details so that we may try to reproduce in the same environment?
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by zerweck** [comment]
### System details

 ```
RStudio Edition : Desktop
RStudio Version : 1.3.911
OS Version      : Microsoft Windows 10 Pro, Build 17134
R Version       :  3.5.2 (it's a legacy project that I need to maintain)
```

**Comment by kevinushey** [comment]
You can set `options(browserNLdisabled = TRUE)` to disable this behavior. When that is set, only typing `n` will advance the debugger. See `?options` for more details.
