### ISSUE TITLE
Once Support content is merged to the docs.rstudio.com repo, remove the Professional Support in the admin guide

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rstudio#6498]
In an effort to eliminate duplicated content, I consolidated the need help/support section from the admin guides to a single document, living in the docs.rstudio.com site. Once that is approved and merged, this content (https://docs.rstudio.com/ide/server-pro/index.html#professional-support) should be removed from the admin guide.

rstudio/docs.rstudio.com#133

**Comment by AshleyHenry15** [comment]
Here is the new content: https://docs.rstudio.com/support/

**Comment by gtritchie** [comment]
Confirmed with Ashley that this old issue can be closed.
