### ISSUE TITLE
Copy in right-click context menu doesn't work with individual source window

### ISSUE THREAD

**Issue by michael-mastroianni** [rstudio/rstudio#6499]
### System details
RStudio Edition : 	Desktop
RStudio Version : 	1.3.921
					"Middlemist Red" (6a7e93b5, 2020-03-18) for macOS
					Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) 
					AppleWebKit/537.36 (KHTML, like Gecko) 
					QtWebEngine/5.12.6 Chrome/69.0.3497.128 Safari/537.36

OS Version      : 	macOS Catalina 10.15.3 (19D76)
R Version       : 	R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
					Copyright (C) 2020 The R Foundation for Statistical Computing
					Platform: x86_64-apple-darwin15.6.0 (64-bit)
### Steps to reproduce the problem
Open two source files in RStudio Desktop. Open the 2nd tabbed file in its own window. Try to copy text in a glue() function call by right-clicking text in newly-created window. Copy not available. 

### Describe the behavior you expected
I had two .R source files open in the editor. I opened the 2nd one into its own window, so that I could see both source files and copy/paste between them. When I attempted to copy some text inside a glue() function call from the newly-opened source window (no longer living as a tab) my right-click to copy was no longer selectable from the context menu at my mouse. (However, copy was available for other elements in the source window.)

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Sorry, but I wasn't able to reproduce. Can you provide any more information? A screencast might be helpful as well so we can see exactly what you're seeing. (If you aren't familiar, you can use <kbd>Cmd + Shift + 5</kbd> to open the  builtin macOS screen recording software)

**Comment by michael-mastroianni** [comment]
Good morning, Kevin,

Well, not sure what to say, I can’t reproduce it either now!

But I am now on to the Version 1.3.923 Preview Release. The unavailable
right-click “Copy” menu option was very repeatable last week, so not sure
what to say?

This issue was happening at my office, where I was using my MacBook Pro
with an external monitor; I am now working remotely at home without an
external monitor.

So a bunch of oddball potential causes to consider, perhaps.

Since I won’t be back in my office until coronavirus concerns relent most
likely, I may not be able to duplicate this for some time, or not at all.
If I can reproduce here at home I will update you and provide a screen cast
as suggested …

Sorry for not being able to shed more light on this … thanks for your
prompt and kind follow up!

Cheers,

Mike



On March 20, 2020 at 12:49:22 PM, Kevin Ushey (notifications@github.com)
wrote:

Sorry, but I wasn't able to reproduce. Can you provide any more
information? A screencast might be helpful as well so we can see exactly
what you're seeing. (If you aren't familiar, you can use Cmd + Shift + 5 to
open the builtin macOS screen recording software)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rstudio/rstudio/issues/6499#issuecomment-601802159>, or
unsubscribe

**Comment by ronblum** [comment]
I can't reproduce this, either, with RStudio Desktop 1.3.923 on MacOS 10.15.4. I tried with an external screen, but no luck. @michael-mastroianni could you provide sample code to make sure I'm replicating your steps correctly?

**Comment by michael-mastroianni** [comment]
Steps to attempt to reproduce:

1. Open two R script files, x.R, y.r in Rstudio, such that they are resident in respective tabs in the RStudio source editor pane.

2. Contents of x.R can be arbitrary (anything). 

3. In y.R place the following code:

```
library(glue)
sql_text <- glue(
"
SELECT foofighter from foofighters
WHERE foofighter == \"David Grohl\"
LIMIT 1000;
"
)
```

4. Use the editor widget to open y.R in its own window.

5. Copy the lines from SELECT through LIMIT by highlighting the text and right-clicking to get the Copy context menu. Copy context menu is greyed out (unselectable).

Just to be clear again, I have not been able to reproduce since working at home remotely, and one difference in environment is that I was using an external monitor along with my MacBook Pro's screen when the problem occurred, and now I am not using an external monitor. (That is not to say that I know that use of an external monitor is the problem.)

Once I return to working in my office, I will try to reproduce this problem again.

**Comment by jmcphers** [comment]
I also couldn't reproduce. @michael-mastroianni please feel free to reopen if you find a consistent repro and/or a clue from the environment.

**Comment by michael-mastroianni** [comment]
Will do, thanks for following up-

Mike
