### ISSUE TITLE
Multiple concurrent sign-in requests are possible

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6502]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.919

### Steps to reproduce the problem

1. Configure a system such that signing in takes a few seconds. This can be done by e.g., introducing a delay with `pam_script` and `sleep`.
2. Open RStudio Server, enter your credentials, and sign in.
3. While waiting for sign-in in to complete, click the sign in button again. 

### Describe the problem in detail

The second request to sign in is also made. Depending on the auth provider, this can fail since a sign-in is already in flight. @nwstephens has a demo of this here (for Desktop Pro): https://vimeo.com/398352339

### Describe the behavior you expected

1. The sign-in button should change state visually to indicate that the sign-in is in progress. This is especially important because the sign-in page is sometimes embedded in browsers that do not otherwise show progress (such as RStudio Desktop Pro).
2. The sign-in button should be disabled after submitting the first sign-in, so that it is not possible to stack sign-in requests.

**Comment by rich-rstudio** [comment]
verified on RSP Version 1.4.1048-1
