### ISSUE TITLE
enabling panmirror causes IDE to hang (subsequent launches hang as well)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6504]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.4.78
    OS Version      : Windows 10 x64
    R Version       : 3.6.2

### Steps to reproduce the problem

Enable panmirror support, and then try to open an R Markdown document.

### Describe the problem in detail

The IDE will hang, with the Qtwebengineprocess apparently chewing up a bunch of CPU. The IDE cannot be closed; it must be force-killed from the task manager.

Subsequent launches of the IDE (even an older release, e.g. RStudio v1.3) will then hang in the same way.

Deleting these folders:

```
%LOCALAPPDATA%\RStudio
%LOCALAPPDATA%\RStudio-Desktop
```

did help in getting out of this state.

### Describe the behavior you expected

No hang.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
I'm not able to repro this w/ 1.4.78. Could you provide explicit steps for the repro.

Could anyone else w/ a Windows VM or dev machine try to repro as well?

**Comment by kevinushey** [comment]
This doesn't seem to reproduce on my physical Windows machine at home, so it might be something unique to the Windows VM on my macOS machine. (on macOS, I'm using Parallels + RStudio is running with software rendering)
