### ISSUE TITLE
Portable installation breaks busy detection for custom shells on Windows

### ISSUE THREAD

**Issue by edavidaja** [rstudio/rstudio#6505]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.84
    OS Version      :  Windows 10 x64 (build 19587)
    R Version       :  3.6.3

### Steps to reproduce the problem

I have installed R, the latest RStudio daily and Git with [scoop](https://scoop.sh/), and set the custom shell to the path to where the scoop version of git bash is installed, with :

`C:\Users\WDAGUtilityAccount\scoop\apps\git\current\bin\bash.exe`

![image](https://user-images.githubusercontent.com/12927842/77256746-7e423480-6c46-11ea-8878-cd59eea3f9a3.png)

### Describe the problem in detail

If I attempt to close Rstudio after activating the terminal, it is incorrectly reported as busy. 

![image](https://user-images.githubusercontent.com/12927842/77256687-1f7cbb00-6c46-11ea-89f4-8d60d22ca425.png)

### Describe the behavior you expected

If I install git, R, and RStudio through the normal windows gui process, git bash is automatically detected as an available shell and busy detection works normally. (The current documentation on the [website](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal#busy) incorrectly states that busy detection does not work with git bash on Windows.)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@edavidaja Thank you for filing the issue! We'll review it as we continue development of RStudio.

**Comment by edavidaja** [comment]
![image](https://user-images.githubusercontent.com/12927842/87690550-9854d500-c757-11ea-8856-2fc6b48742bc.png)

It looks like this is fixed in Water Lily, closing.

**Comment by gtritchie** [comment]
Fixed by this PR: https://github.com/rstudio/rstudio/pull/7123
