### ISSUE TITLE
Feature request: Merge advantages of "grid" and "list" view for Environment Tab.

### ISSUE THREAD

**Issue by zerweck** [rstudio/rstudio#6507]
It seems strange that both contain good features that one cannot use together.
- Grouping by object type - **List only**
- Flexible column widths - **List only**
- `object.size()`-column- **Grid only**
- `length()`-column - **Grid Only**
- Sorting by a column - **Grid only**
- `str()`-column - **Both**

Why even maintain two systems with such a big feature overlap and not just offer a single view with optional selection what type of columns to show and if to use the grouping feature.

**Comment by ronblum** [comment]
@zerweck Thanks for filing the request! We'll review it during on ongoing development of RStudio.
