### ISSUE TITLE
Cannot compile bibliography is RStudio pdf Latex

### ISSUE THREAD

**Issue by davebernie89** [rstudio/rstudio#6508]
### System details

    RStudio Edition : <Desktop>
    RStudio Version : 1.2.5033
    OS Version      :  Windows 10 Home
    R Version       : 3.6.3

### Steps to reproduce the problem

1/ Compile test.tex in RStudio with MikTex 2.9 
[test.synctex.zip](https://github.com/rstudio/rstudio/files/4370440/test.synctex.zip)

### Describe the problem in detail
The bibliography section does not compile in RStudio, but works in all other compilers 

### Describe the behavior you expected
RStudio to perform as usual 

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@davebernie89 Thank you for filing the issue. You state that it works in other compilers—can you give an example? Thanks!

**Comment by jmcphers** [comment]
Haven't heard back in over a month, so closing.
