### ISSUE TITLE
stale Shiny viewer options from v1.2 can cause errors after upgrade

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6509]
### System details

    RStudio Edition : Both
    RStudio Version : v1.3.923
    OS Version      : macOS 10.15.3
    R Version       : 3.6.3

### Steps to reproduce the problem

Not exactly sure, but see https://community.rstudio.com/t/help-with-shiny-app-execution-error/57480/16 for details.

### Describe the problem in detail

Shiny applications fail to start.

### Describe the behavior you expected

No failure.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/rstudio/pull/6510.

**Comment by rich-rstudio** [comment]
verified on rstudio cloud Version 1.3.893-1 and rstudio desktop Version 1.3.921
