### ISSUE TITLE
Navigating to ... 500 errors

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#6514]
I upgraded to rstudio-server to the preview version today (1.3.923) but ran into lots of 500 errors navigating between directories and files. Problem went away after downgrading to stable release of Rstudio-server

### System details

    RStudio Edition : Open source
    RStudio Version :  Preview 1.3.923
    OS Version      :  Ubuntu 18.04 in docker
    R Version       :  3.6.3

### Steps to reproduce the problem

Navigate into directories and open files.

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/2998956/77377332-fa647700-6d2f-11ea-8924-fccb8c392a45.png)

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Are you able to provide a reproducible example? This is the first time such an issue has been reported.

**Comment by vnijs** [comment]
Sorry but I already downgraded to 1.2, and overwrote the old docker container. FYI this is running through jupyterhub. Works fine with the latest 1.2 version but 1.3 kept producing this error for multiple users.

**Comment by kevinushey** [comment]
Okay, but without a reproducible example it is unlikely this will be fixed for the v1.3 release.

**Comment by vnijs** [comment]
Understood. I'll see what I can do without disrupting student access

**Comment by vnijs** [comment]
I won't be able to try this out again on the server until summer most likely. If you want a closer look you would have to add the Rstudio preview version to the Docker file linked below (and perhaps run in JupyterHub).

https://github.com/radiant-rstats/docker/tree/master/rsm-jupyterhub

**Comment by vnijs** [comment]
Finally got a docker container ready for testing. Browsing and opening files in the preview version causes issues intermittently (see screenshot below) when we run from docker container vnijs/jupyterhub-test-user:latest with the current preview version of Rstudio Server preview (1.3.938) under jupyterhub on linux 18.04. This was never an issue with any previous version of Rstudio Server we have used and also not with Rstudio Server Pro, stable release. I also ran the container on macOS but there the problem does not seem to occur. 

![image](https://user-images.githubusercontent.com/2998956/79313391-1bdefb80-7eb5-11ea-9f91-ad0812356d36.png)

**Comment by vnijs** [comment]
Not sure if (really) related but this is also something my students see with some regularity using Rstudio server in Docker on their laptop computers.

![image](https://user-images.githubusercontent.com/2998956/79392108-a8c29d00-7f27-11ea-8331-eba1bc7e4020.png)

**Comment by vnijs** [comment]
@ronblum Were you able to reproduce this issue? I noticed that Rstudio 1.3 was released and was wondering if I should for 1.4 or is it likely that 1.3 will not show these issues?
