### ISSUE TITLE
Cannot choose archive to install packages using Windows File Explorer

### ISSUE THREAD

**Issue by drdanc** [rstudio/rstudio#6515]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by drdanc** [comment]
I just installed RStudio v. 1.2.5033 with R v. 3.6.3 on a Windows 10 desktop. When I go to Tools -> Install Packages and choose package archive, I can browse and select, but the content of the window path doesn't change - it shows "~/." no matter what I do. I cannot change it manually either. I deleted .RData, .Rhistory, uninstalled / reinstalled RStudio but nothing helped.

**Comment by ronblum** [comment]
@drdanc Thank you for filing the issue. I haven't been able to reproduce it, though. Does this only happen if you browse and select files under home directory, or does it happen if you browse elsewhere in the filesystem?

Also, the 1.3 (Middlemist Red) release is approaching and we have  a preview available at https://rstudio.com/products/rstudio/download/preview/ if you'd like to try it. Note that the previews are meant for testing, not production.

**Comment by jmcphers** [comment]
Haven't heard back for over a month, closing.

**Comment by kevinushey** [comment]
Note: https://github.com/rstudio/rstudio/issues/6587 is likely related; should be fixed in v1.3-patch.
