### ISSUE TITLE
Global replace for multiple files associates unwritable errors with the wrong file

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6519]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.923
    OS Version      : MacOS 10.15.4 and Red Hat 7.8
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Create a couple of files, `file_444.txt` and `file_777.txt`, with a common string in them.
2. Give one of the files read-only permissions, `chmod 444 file_444.txt`. This file will not be affected.
3. Give the other file all permissions, `chmod 777 file_777.txt`. This file will get changed.
4. In RStudio, Edit -> Find in Files and search for the text.
5. Replace the text.

### Describe the problem in detail

The output will show an error because of the read-only file, since it can't be modified. However, the error is associated with the wrong file—it shows up in the Find in Files pane as if the writing failed with the writable file (`file_777`). Meanwhile, the record for the read-only file (`file_444.txt`) just has the original text, without replacement text.

<img width="563" alt="file_failure" src="https://user-images.githubusercontent.com/31009952/77474122-ee8aba80-6dec-11ea-8599-db5208e25c5b.png">

### Describe the behavior you expected

1) The error should be associated with the file that failed.
2) The last entry should include the replacement text.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Fixed in #6521.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.3.929 on MacOS 10.15.4 and RStudio Server 1.3.929 on Red Hat 7.8.
