### ISSUE TITLE
creating new project with renv modifies current project state

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6522]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.926
    OS Version      : macOS 10.15.3
    R Version       : 3.6.3

### Steps to reproduce the problem

Create a new project using `renv`, and also check the box indicating you want to open that project in a new session.

### Describe the problem in detail

`renv::init()` is called in the current session, which modifies the current session. 

### Describe the behavior you expected

`renv::init()` should be called in the newly-created IDE session, or within an R subprocess to avoid modifying the current session.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rich-rstudio** [comment]
verified in Version 1.3.931
