### ISSUE TITLE
incorrect symbol shown for Enter key in menus

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6524]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.921
    OS Version      : macOS 10.15.3
    R Version       : 3.6.1

---

<img width="280" alt="Screen Shot 2020-03-25 at 9 18 56 AM" src="https://user-images.githubusercontent.com/1976582/77559656-ab2a5d80-6e79-11ea-8618-bdc076a6dc8e.png">

Looks like this is true in RStudio v1.2 as well; however, the expected symbol is shown in RStudio v1.1.

<img width="273" alt="Screen Shot 2020-03-25 at 9 19 42 AM" src="https://user-images.githubusercontent.com/1976582/77559743-c5643b80-6e79-11ea-81ec-b3162c744c09.png">

**Comment by ronblum** [comment]
Note: only an issue on MacOS Desktop—it works correctly when connecting from via browser from MacOS to RStudio Server. Also works correctly (Ctrl+Enter) in Windows and Linux.

**Comment by kevinushey** [comment]
Filing for 1.4 milestone as this should (in theory) be a simple fix.

**Comment by gtritchie** [comment]
Research note: The currently displayed symbol is actually correct for the <kbd>Enter</kbd> key on Mac. However, what we refer to as the "enter" key in our command definitions is actually the <kbd>Return</kbd> key on a Mac.

Enter key: ⌤
Return key: ⏎

More juicy details: https://en.wikipedia.org/wiki/Enter_key

Here's what's on an extended Mac keyboard.

![photo of a Mac extended keyboard](https://user-images.githubusercontent.com/10569626/92811121-0510d800-f373-11ea-96e4-4b724ef0b157.jpeg)

**Comment by kevinushey** [comment]
Interesting!

Just out of curiosity -- are there any cases where the behavior of the Enter key differs from that of the Return key?

**Comment by kevinushey** [comment]
I guess I can just read the Wikipedia article you linked :-)

> In Mathematica, the Return key creates a new line, whereas the Enter key (or Shift-Return) submits the current command for execution.

**Comment by kfeinauer** [comment]
Verified fixed on 1.4.944
