### ISSUE TITLE
update Rtools for R 4.0.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6530]
Assuming R 4.0.0 is going to use the new Rtools toolchain (https://cran.r-project.org/bin/windows/testing/rtools40.html), then we will need to update codepaths here:

https://github.com/rstudio/rstudio/blob/dc633397ba513a61441708e131a9abda36714160/src/cpp/core/r_util/RToolsInfo.cpp#L189

https://github.com/rstudio/rstudio/blob/dc633397ba513a61441708e131a9abda36714160/src/cpp/session/modules/build/SessionInstallRtools.cpp#L67

**Comment by jjallaire** [comment]
Also need to make sure that things continue working libclang (I've had to make some changes there in response to new version of Rtools & what/where they bundle system headers).

**Comment by jmcphers** [comment]
On hold until we know for sure whether R 4.0 is going to use the new toolchain.

**Comment by jmcphers** [comment]
Looks like it is going to use it:

https://twitter.com/opencpu/status/1250452381403398149

**Comment by jmcphers** [comment]
Fixed in 1.3.944-1

**Comment by R-Hannibal** [comment]
Verified Fixed on: Windows Desktop Version 1.3.944-1 (R version 4.0.0 alpha).

Tested that RStudio version 1.3 is installing the correct RTools version when running R version R 4.0 (in this case it was [rtools40](https://cran.r-project.org/bin/windows/Rtools/):

1. Make sure Rtools is not installed on your windows box.
2. Have R 4.0 installed.
3. Open the latest preview IDE version.
4. Run something that requires build tools. An easy one would be `pkgbuild::has_build_tools()`.
5. Verify the IDE will have a popup to install Rtools.
6. Verify it installs rtools40.
