### ISSUE TITLE
Glitchy scroll bar in snippets editor

### ISSUE THREAD

**Issue by BastiHz** [rstudio/rstudio#6534]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.926
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : 3.6.3

### Steps to reproduce the problem

Go to Tools -> Global Options -> Code -> Edit Snippets and place the cursor anywhere in the text.

### Describe the problem in detail

A blinking scroll bar is displayed at the position where the cursor is placed. See the attached screenshot. Moving the cursor left or right also moves the scroll bar left or right.
![snippets_bug](https://user-images.githubusercontent.com/41594266/77632575-7b00be80-6f4e-11ea-8344-f2a74dfe5782.png)

### Describe the behavior you expected

No glitchy scroll bar.
Interestingly, I see this bug only in some languages. If I go to the markdown snippets everything seems fine.
Glitchy: R, Tex, JavaScript, Java, Python, Stan
OK: C++, Markdown, HTML, CSS, SQL

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@BastiHz Thank you for filing the issue! I can't reproduce it with any of the file types, though, using the same environment and build. Have you by chance previously used an earlier build of 1.3 in which this worked correctly?

**Comment by BastiHz** [comment]
I have used earlier previews before but this is the first one where I opened the snippets.
It seems that this is affected by the "Rendering engine" setting. Selecting "Auto-detect" or "Software" shows the buggy behavior but it looks ok with "Desktop OpenGL".

**Comment by BastiHz** [comment]
It gets weirder. When I write a very long line (longer than the window width) in the R snippets, then the bug disappears. But a very long line in the C/C++ snippets causes a flashing horizontal scrollbar to appear. In the attached image the cursor is in line 14.

![snippets_bug_horizontal](https://user-images.githubusercontent.com/41594266/77667994-2a578880-6f83-11ea-98d0-acffd8e4f801.png)

**Comment by kevinushey** [comment]
I'm not able to reproduce. If using OpenGL software rendering works for you, I'd recommend setting that.
