### ISSUE TITLE
Return focus after successfully installing package dependencies

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6535]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.928 

### Steps to reproduce the problem

1. Open an R script that has `library()` calls for packages that are not yet installed
2. When the "install missing packages" bar appears, opt to install the packages

### Describe the problem in detail

Package installation proceeds, but the Jobs tab is left open when it's finished, so users need to manually return to their previous context.

### Describe the behavior you expected

This was done so users could see any package installation failures that occurred while installing packages, but there's no need to keep the tab open if the installation was successful, and doing so is confusing.  We should return focus when package installation is complete.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.3.938 on MacOS 10.15.4 and RStudio Server 1.3.938 on Red Hat 7.8 connected from Chrome on MacOS 10.15.14: Jobs pane with details remains but focus returns to Console.
