### ISSUE TITLE
Rstudio aborts R session when debugging

### ISSUE THREAD

**Issue by zlskidmore** [rstudio/rstudio#6537]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5033 - 1.2.5001
    OS Version      :  macOS Catalina 10.15.4
    R Version       : 4.0.0

### Steps to reproduce the problem

create the file below and source from Rstudio

```R
test <- function(x){
  browser()
}
test("test")
```
### Describe the problem in detail

When trying to debug code via breakpoints in Rstudio or via a `browser()` command Rstudio will pop up the standard screen saying the Rsession has been aborted. I downloaded the following binaries for mac from the Rstudio website to test:
https://download1.rstudio.org/desktop/macos/RStudio-1.2.5033.dmg
https://download1.rstudio.org/desktop/macos/RStudio-1.2.5019.dmg
https://download1.rstudio.org/desktop/macos/RStudio-1.2.5001.dmg
https://download1.rstudio.org/desktop/macos/RStudio-1.2.1335.dmg

I attempted to try a few other versions however some binaries appear to be missing from the Rstuio website and I could not get the latest Rstudio to compile from github.

version 1335 will not abort but has it's own problems. My feeling is this has something to do with the interactio between R 4.0.0  and Rstudio but I'm not sure how to debug the issue further.

### Describe the behavior you expected

Standard debugging behavior

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/). See also: https://github.com/rstudio/rstudio/issues/5888

@jmcphers, it looks like you were considering backporting that PR to the v1.2-patch branch. Is that something you're still considering?

https://github.com/rstudio/rstudio/pull/5922

**Comment by zlskidmore** [comment]
Yes this appears to be fixed in `1.3.929`

Perhaps the binary download paths I mention on the Rstudio site were not updated with the P?

**Comment by jmcphers** [comment]
I have already backported the release to 1.2, but it was after the last 1.2 stable build. It's in an as-yet-unreleased 1.2 build called Double Marigold. @zlskidmore you're welcome to try it.

https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.2.5036.dmg

**Comment by tmcduff** [comment]
Verified in R 4.0.0
RStudio: Version 1.2.5042-1

Using the following: 
create the file below and source from Rstudio

test <- function(x){
  browser()
}
test("test")
