### ISSUE TITLE
Themes unit tests failing

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6540]
### System details

    RStudio Edition : RStudio Dev environment
    RStudio Version : 1.4.100
    OS Version      : macOS
    R Version       : 3.6.1

### Steps to reproduce the problem
- `rstudio-tests --filter themes`

### Describe the problem in detail
- Lots of failures, gives up with too many failures

### Describe the behavior you expected
- No failures

Presumably caused by: https://github.com/rstudio/rstudio/pull/6440

**Comment by gtritchie** [comment]
I have disabled these tests for now, per #6656.

When you fix them, maybe add how-to details to: https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/themes/README.md

**Comment by gtritchie** [comment]
Fixed by f961f7c562bcb8eee3611a2f93201dff9888135f

**Comment by R-Hannibal** [comment]
Marking this issue as 'verified' without testing. Maintenance on the theme unit tests.
