### ISSUE TITLE
linter unit test outputting a bunch of errors (but is passing)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6541]
### System details

    RStudio Edition : dev environment
    RStudio Version : 1.4.100
    OS Version      : macOS
    R Version       : 3.6.1

### Steps to reproduce the problem
- `./rstudio-tests --filter linter`

### Describe the problem in detail
- although the tests ultimately pass, a large amount of error output is generated
- for example a lot of these (but some other errors, too):
```
26 Mar 2020 22:00:29 [rsession-gary] ERROR r error 7 (Unexpected data type); OCCURRED AT core::Error rstudio::r::sexp::extractFunctionInfo(SEXP, rstudio::core::r_util::FunctionInformation *, bool, bool) src/cpp/r/RSexp.cpp:1744; LOGGED FROM: rstudio::core::r_util::FunctionInformation rstudio::session::modules::rparser::(anonymous namespace)::getInfoAssociatedWithFunctionAtCursor(rstudio::core::r_util::token_cursor::RTokenCursor, rstudio::session::modules::rparser::ParseStatus &) src/cpp/session/modules/SessionRParser.cpp:1158
```

### Describe the behavior you expected
- clean runs

**Comment by gtritchie** [comment]
No longer happening. Neato! Not worth tracking down what fixed it.

**Comment by R-Hannibal** [comment]
Marking this issue as 'verified'. Issue seems to have fixed itself, taking the win.
