### ISSUE TITLE
Regex not working in Find in Files (Preview Release 1.3.929)

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#6544]
Regex isn't working in the preview release find in files:

![image](https://user-images.githubusercontent.com/25590353/77781392-1a8b8300-701b-11ea-828a-43f334397f92.png)

![image](https://user-images.githubusercontent.com/25590353/77781435-30994380-701b-11ea-8c9a-87cb4247f2a2.png)

Example of search term existing:

![image](https://user-images.githubusercontent.com/25590353/77781483-4149b980-701b-11ea-8646-e0c9be36b95c.png)

**Comment by melissa-barca** [comment]
Hi @jzadra to get this regex working properly you need to escape the curly brackets. Searching for `hd\d\{4\}\.csv` will give you your expected results.

**Comment by jzadra** [comment]
Thanks.  It would probably be a good idea to make the RStudio GUI regex syntax the same as R code regex syntax.  Escaping the curls are not required in R.

Thanks,

Jon

--
Jonathan Zadra, PhD (he/him)
Director of Data Science
Sorenson Impact Center
David Eccles School of Business, University of Utah
www.sorensonimpact.com
(801) 581-4815
On Mar 27, 2020, 1:06 PM -0600, Melissa Barca <notifications@github.com>, wrote:
> Hi @jzadra to get this regex working properly you need to escape the curly brackets. Searching for hd\d\{4\}\.csv will give you your expected results.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

--

**Comment by jzadra** [comment]
It also does not appear to handle capturing groups, which is sorely needed for find in files / replace in files

Thanks,

Jon

--
Jonathan Zadra, PhD (he/him)
Director of Data Science
Sorenson Impact Center
David Eccles School of Business, University of Utah
www.sorensonimpact.com
(801) 581-4815
On Mar 27, 2020, 1:13 PM -0600, Melissa Barca <notifications@github.com>, wrote:
> Closed #6544.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

--

**Comment by melissa-barca** [comment]
Hi Jon, I should've clarified earlier, RStudio uses `grep` under the hood to search through files so you'll need to use POSIX Basic Regular Expressions when searching through your files combined with appropriate escaping. You can group tokens together with parentheses (these needs to be escaped) and use `\1` through `\9` for backreferences.
