### ISSUE TITLE
Run .Rmd files with jobs pane in addition to .R files

### ISSUE THREAD

**Issue by kieran-mace** [rstudio/rstudio#6545]
Currently one can run a `script.R` file using the jobs tab. 

One cannot run a `script.Rmd` file that is a mix of R chunks and markdown. 

Feels like a nice feature, just strip out the markdown, merge the chunks, and run as an R script. no?

**Comment by ronblum** [comment]
@kmace Thank you for filing the request—we'll review it as we continue development of RStudio.

**Comment by jmcphers** [comment]
What does this give you that the Knit button doesn't? (knit also happens in a background task, just not technically a Job)

**Comment by jmcphers** [comment]
https://app.prodpad.com/feedback/521231/canvas 

> As a user, I would like to do "knit with parameters" (or other types of "knitting") as a background job straight from the IDE. This allows me to run several iterations of the report concurrently and easily monitor their output.
