### ISSUE TITLE
RStudio crash when knitting on second display

### ISSUE THREAD

**Issue by DvP17** [rstudio/rstudio#6546]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : MS Windows 10
    R Version       : 3.6.2

### Steps to reproduce the problem
- Open RStudio on Display 1
-  Drag RStudio Window to Display 2
- create new R markdown file
- press "Knit"
- watch how RStudio freezes

### Describe the problem in detail
When using a second display and dragging the RStudio window to display 2 and knitting R markdown files, Rstudio crashes. The pop-up window for the knitted html-file freezes and remains blank. RStudio stops answering.

### Describe the behavior you expected
It should be expected that the html-file gets knitted as normally.

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4395449/diagnostics-report.txt)

**Comment by ronblum** [comment]
@DvP17 Thank you for raising the issue! 
1) For the two displays, are you referring to two external monitors, or the laptop and one external  monitor?
2) Have  you tried switching to software rendering? Information about that [is available here](https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors).
3) Also, we are currently working on RStudio 1.3, Middlemist Red, and you can [download a preview version](https://rstudio.com/products/rstudio/download/preview/) if you'd like to check if that resolves the issue.

Thanks!

**Comment by DvP17** [comment]
@ronblum Thank you very much for your fast reply!

1. I am using the "second screen only" display setting on my notebook. There are two displays connected to my laptop. On display 2, RStudio runs seamlessly. On display 3 it crashes (display 1 is the laptop display, which is turned off). Display 2 is set up vertically and display 3 horizontally.
**2. Yes, switching to software rendering has resolved the issue.**
3. I have tested it (without software rendering) with RStudio 1.3, and the problem is still present.

Another issue:
When clicking any drop-down menu (without software rendering), RStudio crashes, too.

**Comment by DvP17** [comment]
@ronblum It turned out that the issue has nothing to do with RStudio but with OpenGL rendering on a second screen. Thus, I will close this issue.
