### ISSUE TITLE
Selectively Strip Trailing Whitespace from Rmd Files

### ISSUE THREAD

**Issue by connorp** [rstudio/rstudio#6558]
Per #3487, RStudio currently does not enforce Strip Trailing Whitespace on RMarkdown documents due to the significance of whitespace in Markdown. However, I believe a single trailing space at the end of a line is not significant, and could safely be removed. Could this more limited whitespace stripping be implemented?

**Comment by ronblum** [comment]
@connorp Thank you for the suggestion! We'll review during our ongoing development of RStudio.
