### ISSUE TITLE
Returning a source tab to main window causes tab-switching hotkey (Ctrl + Tab) fail to work

### ISSUE THREAD

**Issue by ukyoi** [rstudio/rstudio#6559]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.929 (Preview)
    OS Version      : macOS 10.15.4
    R Version       : 3.6.3

### Steps to reproduce the problem
1. Open multiple tabs in source tab.
2. Detach a tab to a new window (by pressing "show in new window" with an opened source tab or an opened data frame viewer, or just dragging it out of the tab bar). Until now, tab-switching hotkey works properly.
3. Press "Return to main window" on the tab which has been detached.

### Describe the problem in detail
Tab-switching hotkey fail to work.

### Describe the behavior you expected
Tab-switching still works.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ukyoi Thank you for raising the issue! I can reproduce this in the same environment. However, it works with the RStudio Server shortcuts, <kbd>Ctrl+F12</kbd> and <kbd>Ctrl+Alt+Right Arrow</kbd>, in Red Hat 7.8 via Google Chrome on MacOS 10.15.4. We'll review this as we continue development of RStudio.

Note: This is an issue in 1.2 as well, so it's not a regression.
