### ISSUE TITLE
OpenGL rendering looks blurry in some setups

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#6561]
This is how OpenGL rendering looks on my computer:
![opengl_text](https://user-images.githubusercontent.com/11860098/78007341-db28a380-7346-11ea-821c-0a29d7776ff6.png)

And this is how software rendering looks:
![software_text](https://user-images.githubusercontent.com/11860098/78007368-e1b71b00-7346-11ea-859c-e9dcf2f845ae.png)

The OpenGL one looks very blurry, and it's hard to read text from it.

**Setup:** RStudio 1.3.929, running on debian linux with AMD Vega 56 video card, mesa drivers 19.3.3-1, X11, KDE 5.17.5, zoomed to 110% from Tools -> Global Options -> Appearance.

**Comment by kevinushey** [comment]
Does switching to software rendering help? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by kevinushey** [comment]
Does the blurriness depend on the zoom level?

**Comment by david-cortes** [comment]
It does look less blurry when the zoom is set to 100%, but with the screen size I have, I wouldn't be able to tell if it's due to not being blurry or due to the fonts being very small. At least I cannot tell the difference compared to software rendering with zoom 100%.

**Comment by MariaSemple** [comment]
I was able to reproduce this on 1.3.937 with a new project, by doing the following:

1. Ensure that the rendering engine is Desktop OpenGL. (OpenGL for Embedded Systems does not appear to become blurry).
2. Open a file with text.
3. Reset Zoom to 0 (i.e. default view).
4. Ctrl-shift-= (one zoom-in level looks particularly blurry)

If the file is not in the editor view when zoom occurs it does not appear blurry. If the file becomes blurry, it does not become clear by switching editor tabs back and forth. It _does_ become clear if closed and re-opened.

Relevant system details:

    RStudio Edition : Desktop
    RStudio Version : 1.3.937
    OS Version      : Ubuntu 18.04.1
    R Version       : 3.6.2

![image](https://user-images.githubusercontent.com/37987486/78594845-df990480-77fd-11ea-943e-d16a1505bc92.png)

**Comment by eliocamp** [comment]
Con confirm that this is happening to me as well on elementary os (based on Ubuntu 18.04). The issue comes up when 1. not using software rendering, 2. not on the default zoom level and 3. the scroll is not aligned perfectly with the text.

This is with scrolling aligned:
![image](https://user-images.githubusercontent.com/8617595/80541735-10460700-8982-11ea-9ae7-5599862b3d1a.png)

And now this is if I scroll less than a full line:
![image](https://user-images.githubusercontent.com/8617595/80541743-15a35180-8982-11ea-85dc-b238cd1dc766.png)

**Comment by jthomasmock** [comment]
This `blurriness` also happens under the following conditions:
- Mac - OSX Catalina
- OS Scaling factor is Default for display
- Monitor Resolution: 2560 x 1440
- Global options -> advanced -> OS Integration -> Rendering Engine (autodetect or Open GL)

Behavior is reproduced ONLY when the scroll bar is pushed to the far right. I can prevent this behavior by:
- Setting rendering engine to software OR by expanding the screen size so no scroll bar is present in the Source pane.

**Comment by iago-pssjd** [comment]
Something like this happens to me without doing changes in zoom under:
```
RStudio Edition : Desktop
RStudio Version : 1.3.959
OS Version      : Debian 9.12
R Version       : 3.6.3
Monitor resolution: 1920 x 1080
```
After changing rendering engine from `Auto-detect` to `Software` it seems to be solved.

**Comment by carlosmag** [comment]
Changing the rendering engine to `Software` worked for me only in text editor, but not in terminal pane.
Setting zoom to 100% fixed blurry fonts in terminal.

`RStudio Edition : Desktop ;  
RStudio Version : 1.3.959 ;
OS Version: Kubuntu 18.04 ;
Monitor resolution: 1920 x 1080 ;
GPU: Nvidia RTX 2060 ;
GPU driver version: 435.21`

**Comment by chenwang** [comment]
> Changing the rendering engine to `Software` worked for me only in text editor, but not in terminal pane.
> Setting zoom to 100% or disabling hardware acceleration in Global options -> Terminal fixed blurry fonts in terminal. Nevertheless, the scrolling speed in terminal is not as fluid as in previous Rstudio versions #2100 .
> 
> `RStudio Edition : Desktop ; RStudio Version : 1.3.959 ; OS Version: Kubuntu 18.04 ; Monitor resolution: 1920 x 1080 ; GPU: Nvidia RTX 2060 ; GPU driver version: 435.21`
> 
> I do not have blurry fonts in RStudio Desktop v1.2.5033, with default rendering engine and zoom 110%.

I have some very similar experience. Have to revert back to v1.2.5033 such that both the terminal and editor are not blurry.

**Comment by bowenjfung** [comment]
I'm also having rendering issue in my editor pane using OpenGL. The other panes in the IDE seem unaffected. The blur occurs inconsistently depending on total window size and zoom level, but the easy fix is to use software rendering.

I am running RStudio 1.3.1073 under macOS 10.15, using an eGPU (RX 5700 XT), and a 1440p monitor at default scaling.

**Comment by iago-pssjd** [comment]
In fact, I can confirm the issue is yet present.
