### ISSUE TITLE
RStudio Desktop : Import Excel Screen can't import data when use Japanese Language sheet name.

### ISSUE THREAD

**Issue by tminoda** [rstudio/rstudio#6568]
I'm facing issues which Import Excel screen can't import data when I use Japanese Language sheet name.

**[Current Situation]**
- I want to upload Excel file which contains Japanese sheet name and data using Import Excel Data screen in Environment tab.
- I can see Japanese file name in "Sheet" and data was shown correctly Japanese text in this screen.
- However, when I select Japanese sheet name then popup error message raising with garbled Japanese character.
- Generated R codes in "Code Preview" is works fine.

- I updated latest version (Version 1.3.929) based on RStudio community advice, however, I faced same issue. 

I have already posted and discussed below RStudio Community before.
https://community.rstudio.com/t/rstudio-desktop-import-excel-screen-cant-import-data-when-use-japanese-language-sheet-name/57089

Please consider fix this issue if possible.

Best regards.
Thank you.

**Comment by ronblum** [comment]
@tminoda Thank you for following up from the Community post and filing the issue! Can you please provide a sample Excel file that has the issue? I want to make sure I've got Japanese characters correctly in the sheet name.

System information based on Community post:
```
    RStudio Edition : Desktop
    RStudio Version : 1.1.456 & 1.3.929
    OS Version      : Windows 10
    R Version       : 3.6.2
```

**Comment by tminoda** [comment]
Hi, @ronblum.
Thank you for your reply.

I attached sample Excel file which I used attempt for this bug confirmation.
Please see attached file.
[Japanese_excel_for_test.xlsx](https://github.com/rstudio/rstudio/files/4418323/Japanese_excel_for_test.xlsx)
