### ISSUE TITLE
Rstudio Error: Unable to establish connection with R session

### ISSUE THREAD

**Issue by thomastskng** [rstudio/rstudio#6569]
My problem is i have been able to use rstudio to write code for a long time. However, recently, when i start my rstudio, no matter which button i click or whatever I do, this **"Error: Unable to establish connection with R session"** pop up like every few seconds. When I tried to edit files, it shows up. When I tried to run code, it shows up. I couldn't remove plots. I could not do anything with Rstudio now. 

I uninstalled rstudio and then reinstall the version 1.2.5033. The same problem persists. 

Below are the methods I have tried and the "**Unable to establish connection with R sessino**" still would not go away. 
1. Resetting the Rstudio desktop by removing the entire folder.

2. Remove start-up files`.Rdata` , `.Rprofile` and `.Rhistory` and `Rprofile.site`

3. Changing software rendering  to "Software"

4. Uninstall R and RStudio and reinstall again. 

Note that I do not have anti virus software installed. 
I also notice that every time I started my RStudio, It reopened the multiple browser() windows (for debugging) that was closed previously. I am sensing that something must be corrupted or broken here. 

```

# ERROR: Definition of function 'testing' not found
# in namespace '.GlobalEnv'
```

I have attached my `SessionInfo()` below.

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Hong Kong SAR.1252  LC_CTYPE=English_Hong Kong SAR.1252    LC_MONETARY=English_Hong Kong SAR.1252
[4] LC_NUMERIC=C                           LC_TIME=English_Hong Kong SAR.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3      lattice_0.20-38 zoo_1.8-6       digest_0.6.23   later_1.0.0     mime_0.9        grid_3.6.3     
 [8] R6_2.4.1        xtable_1.8-4    magrittr_1.5    rlang_0.4.2     promises_1.1.0  tools_3.6.3     shiny_1.4.0.2  
[15] httpuv_1.5.2    fastmap_1.0.1   compiler_3.6.3  htmltools_0.4.0
```

None of the above works for me.

**Can RStudio please look into it please ?  I am working on my master thesis and the deadline is coming up.** 

:pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face:

**Comment by kevinushey** [comment]
In case you haven't already, to fully reset RStudio's state you also need to remove data in some folders outside of the RStudio directory. Please see:

https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

(sorry if you're already aware of this; it wasn't entirely clear to me from your post)

> I also notice that every time I started my RStudio, It reopened the multiple browser() windows (for debugging) that was closed previously. I am sensing that something must be corrupted or broken here.

Most likely this would be caused by a project-local or user-local `.Rprofile` where those `browser()` or debugger statements were being made, but it's hard to know for sure. Do you see the same issue with R launched separately from RStudio?

**Comment by lucasmation** [comment]
I am having the same problem. Really annoying! related to #3066

I removed all my R's and Rstudio. Then did a fresh install of:
R4.0.0, then Rools40, then Rstudio Version 1.2.5042. the problem still occurs. 
Then I tried the suggestion above of using Rstudio 1.3 preview (I used version 1.3.947).  The problem. I also tried deleting the `%localappdata%\RStudio-Desktop` folder. (problem still occurred

It is not that it never works. It keeps alternating between working and not working, I could not detect any pattern

This is as close to a reproducible exam as I can get:

After opening Rstudio I get:

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

```
Error: Unable to establish connection with R session
> 1+1
[1] 2
Error: Unable to establish connection with R session
> 1+1
[1] 2
> 1+1
[1] 2
> 1+1

```

By the way, I am using an AsusVivoBook15 PC with ADM-RYZEN5 processor. Could this be the reason? 

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] MASS_7.3-51.5  compiler_4.0.0 tools_4.0.0   


```

**Comment by biabbiassago** [comment]
Hello!
I am also having the same issue with R 4.0.2. The issue persists under multiple versions of R studio including 1.3.1073, and 1.2.5042. 
I also tried to resetting Desktop state : https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State. 
The issue persists, after following the steps outlined above as well:

- Resetting the Rstudio desktop by removing the entire folder.
- Remove start-up files.Rdata , .Rprofile and .Rhistory and Rprofile.site
- Changing software rendering to "Software"
- Uninstall R and RStudio and reinstall again.

Below is my `session.Info()`

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] MASS_7.3-51.5  compiler_4.0.0 tools_4.0.0   
```

Apologies if this does not constitute a fully reproducible example, let me know if any other information would be help. 
Any suggestions on how to handle this would be appreciated! Thanks!

**Comment by fernandovmacedo** [comment]
I had a setup with R 4+ and Rstudio 1.3+ and suddenly this problem started to occur. Some days before my system were working fine, so I doubted that this was a bug introduced by R, Rstudio or a package. Just to be sure I've updated everything to the latest version and the problem kept ocurring.

The next suspect would be something that have changed on my operation system as a whole. I had not updated my windows 10, so probably it would be some software, likely malicious that was interfering with Rstudio.

Running windows defender it found two malicious software related to the "RelevantKnowledge" malware that infected my computer. After some steps removing it, my Rstudio came back to working properly.

I'm not willing to recreate the issue, but it can probably be done in a sandbox setting if one purposely infect a windows 10 OS with the RelevantKnowlege malware (I don't know how I got it exactly, but I belive you can download the same malware at https://www.relevantknowledge.com), after that I believe Rstudio will stop working.

**Comment by mladencucak** [comment]
I have the same issue as people above. I had a problem with recent Win 10 update and this started occurring. Installed newest R, RStuio and Rtools and it is same. I might try sorting out windows and reinstalling everything.
Did anyone find any solutions?
