### ISSUE TITLE
Disabling 'blinking cursor' option disabled after a long-click or dragging

### ISSUE THREAD

**Issue by Hyeok-hee** [rstudio/rstudio#6573]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5033
    OS Version      : Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem
After selecting 'Tools → Global options → Code → Display' and unchecking 'blinking cursor', the cursor on editor should no longer blink.
But when I highlight words on editor or long-click/drag my mouse, the cursor starts to blink again

### Describe the problem in detail
Disabling 'blinking cursor' option disabled...The cursor blinks again

### Describe the behavior you expected
The cursor does not blink anymore

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This should be fixed in the RStudio v1.3 preview release: https://rstudio.com/products/rstudio/download/preview/
