### ISSUE TITLE
Keyboard shortcut to wrap / unwrap code in parentheses

### ISSUE THREAD

**Issue by stevecondylios** [rstudio/rstudio#6582]
Sometimes it's preferable to wrap commands in `(` and `)` so that the output prints to console

Random example: 

```
(logical_sample <- c(0,1,0,1,0,1,0,1,0))
(sample_mean <- mean(logical_sample))
(sample_st_deviation <- sd(logical_sample)) 
(n <- length(logical_sample))
```

It would be very handy to have a quick RStudio keyboard shortcut for un/parenthesising similarly to how we can use <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>c</kbd> to un/comment.

<kbd>command</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> (parenthesis) or <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>b</kbd> (brackets) would be a logical choices, but [they're both already assigned](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts), so I'm not sure what to suggest except to say the <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>?</kbd> convention works well and is easy to remember

**Comment by ronblum** [comment]
@stevecondylios Thank you for the suggestion! We'll review it as we continue development of RStudio.
