### ISSUE TITLE
Switch focus to console (not jobs) after launching tutorial

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#6584]
Currently, the IDE leaves the Jobs tab open after launching a tutorial, which hides the console tab, e.g.

<img width="1710" alt="Screen Shot 2020-04-03 at 11 30 40 AM" src="https://user-images.githubusercontent.com/85014/78378159-96974500-759e-11ea-92a7-1b63600efff9.png">

This seems helpful for debugging the tutorial launch, but a user who is reading a tutorial is very likely to want to use the console, for example to try out what they are learning. They are less likely to understand or use the Jobs tab. Also, many future tutorials will explicitly ask students to use the console. I suggest that we have the IDE shift focus back to the console after a tutorial successfully launches, e.g.

<img width="1710" alt="Screen Shot 2020-04-03 at 11 30 43 AM" src="https://user-images.githubusercontent.com/85014/78378169-9ac36280-759e-11ea-9da3-03fa7b2d2a4d.png">

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/6535.
