### ISSUE TITLE
Evaluate dropping support for OPENSUSE/SLES 12 in RStudio 1.4 desktop

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6585]
We build RStudio for OpenSUSE/SLES 12 (using opensuse/leap:42.3 in docker container).

Per https://www.suse.com/lifecycle/, "SUSE Linux Enterprise Desktop 12 SP4" went out of support on Dec 31, 2019. Per https://en.wikipedia.org/wiki/OpenSUSE_version_history, OpenSUSE Leap 42.3 went out of support on June 30, 2019.

We should consider dropping support for this in RStudio 1.4; it is our only remaining build still using Qt 5.10.

When we do this, can also scrub the code for QT_VERSION_CHECK and remove anything that was 5.10-specific.

**Comment by kfeinauer** [comment]
Verified removed via IDE builds
