### ISSUE TITLE
Not possible to save file from Rstudio 1.2.5033 and 1.3.036 (Windows 10) on network shares (UNC paths)

### ISSUE THREAD

**Issue by gwd666** [rstudio/rstudio#6587]
RStudio 1.2.5033 cannot save files (.R, .Rmd, etc) to Users home folder or any of its subfolders which is located on "\\\\server/path/to/USER/Daten" (Daten == Documents)   

### System details
- RStudio Edition: Desktop 
- RStudio Version: 1.2.5033  AS WELL AS 1.3.936  
- OS Version: MS WINdows 10 Enterprise - Version: 10.0.17763 Build 17763 
- R Version: 3.5.3 and 3.6.3 

**Description of issue** 
RStudio (1.2.5033 and 1.3.936) cannot save files (.R, .Rmd, etc) to Users home folder if is  located on Windows UNC path "\\\\server/path/to/USER/Daten" (Daten == Documents)   

### Steps to reproduce the problem
Open RStudio 1.2.5033 
Create New (empty) file - optionally write some content into it. 
Try to "Save As" ... anywhere on the (UNC path) Users home folder 

### Describe the problem in detail
Not possible to save any files on a UNC path "out of the box" (see also 'Attempted steps taken to fix' below) 

### Error Information: 
![image](https://user-images.githubusercontent.com/57595487/78394387-da646b80-75eb-11ea-853c-7f1c135bc350.png)

### Describe the behavior you expected
Ability to save files - just like with RStudio 1.1.463 under UNC-PATH USER home folder or its subfolders. 

**Attempted steps taken to fix** 
-  Replace UNC \\\\server/some/path/to/User/Documents with mapped drive letter eg: "L:/USER/Documents"; this works temporarily but is not a feasible permanent solution since after every login respectively even after restart  of RStudio 1.2.5033 the same bug reappears!    

- Output of diagnostics report (if possible):  
see attached .pdf file - interesting sidenote RStudio managed to create (the rstudio-diagnostics folder) and write the diagnostic-report.txt file to the users (UNC path) document folder w/o applying any fixes (eg as mentioned above mapping to drive letter etc.)  
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4429320/diagnostics-report.txt)

"Interesting" sidenote RStudio 1.2.5033 managed to create (the rstudio-diagnostics folder) and write the diagnostic-report file to the users (UNC path) document folder w/o applying any prior fixes (eg as mentioned above mapping to drive letter etc.) before that action. 
So it seems that UNC path access / write ability is hidden somewhere in there? 

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ X] I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Here's a few things that might help us better debug this issue:

1. With the file open that cannot be saved, what does:

```
context <- .rs.api.getSourceEditorContext()
context$path
path.expand(context$path)
```

print? Does it run successfully? Does the path look correct?

2. Does it work if attempt to edit a file using a different naming scheme for the path? For example:

```
file.edit("\\\\?\\server\\path\\to\\USER\\Daten\\test-1.txt")
file.edit("\\\\?\\UNC\\server\\path\\to\\USER\\Daten\\test-2.txt")
```

Do those files successfully open? Are you able to modify + save them?

3. If you're able, can you try using the Windows [process monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to monitor the `rsession.exe` process as it attempts to open these files? Does the `rsession.exe` process appear to be using the correct paths?

**Comment by kevinushey** [comment]
I'd also be curious to know what `path.expand("~/)` returns, in case this is somehow related to an incorrect tilde expansion happening for some UNC paths.

**Comment by gwd666** [comment]
Hi, will do - hope latest on Monday is ok? Thanks for quick reaction.

**Comment by gwd666** [comment]
This is imho an expected result since I cannot save anything to the UNC path, right? 

```
> context <- .rs.api.getSourceEditorContext()
> context$path
[1] ""
> path.expand(context$path)
```

Here are further results - I was so free to adjust your first test1 example a bit 
TESTING test1.txt:     
`> file.edit(paste(path.expand('~/'), "test-1.txt"))
`
works - including modifying test1.txt and saving the modified file.       

TESTING test2.txt:      
`> file.edit("\\\\server-unc-path/to/USER/Daten/test2.txt")
`
works - including modifying test2.txt and saving the modified file.       

TESTING test2.txt:      
`> file.edit("\\\\server-unc-path\\to\\USER\\Daten\\test3.txt")
`
works - including modifying test3.txt and saving the modified file.

**Comment by kevinushey** [comment]
Thank you for following up -- this is very helpful! A few more things to ask:

1. Does editing work with a plain old `file.edit("~/test4.txt")`; that is, without explicitly expanding the path beforehand?

2. If you hover your mouse over the tab name, it should show the full path to the file as understood by RStudio. Is the correct path still shown? For example, I see:

<img width="166" alt="Screen Shot 2020-04-05 at 9 00 35 AM" src="https://user-images.githubusercontent.com/1976582/78503529-01ba5600-771c-11ea-9fdb-e584755b731c.png">

3. Does the behavior differ based on whether you open files using the Files pane, versus the main menu `File -> Open File...`? (I wouldn't expect it to, but it would be helpful to verify.)

4. After opening a file in RStudio, you can press:

    Ctrl + `  (Ctrl + backtick)

to view the RStudio event log. There should be an `open_document` request there, and clicking on it will give you information on the parameters used by RStudio opening the document. For example:

<img width="315" alt="Screen Shot 2020-04-05 at 9 07 05 AM" src="https://user-images.githubusercontent.com/1976582/78503646-d6843680-771c-11ea-9ddb-1c31deed2e32.png">

Do you see the correct path reported there as well?

My hypothesis right now is that the path to the file as understood by RStudio is becoming truncated somehow when the file is opened, but only when opened through one of the main RStudio interfaces.

Again, I really appreciate you following up -- thanks!

**Comment by kevinushey** [comment]
> This first attempt of .rs.api.getSourceEditorContext() is an expected result since I cannot save anything to the described UNC path with a fresh start of RStudio 1.2.5033, correct?

Sorry, that's correct.

This might be more useful. After attempting to save the new document, you should be able to view the RStudio event log by typing:

    Ctrl + `

You should see an event called `save_document_diff`. Clicking on that should give more information about the event; e.g.

<img width="220" alt="Screen Shot 2020-04-05 at 9 34 24 AM" src="https://user-images.githubusercontent.com/1976582/78504274-e00f9d80-7720-11ea-9f12-43fe0e9131d7.png">

Do you see the correct path there? (I wonder if it's being malformed in a similar way to what you're seeing with the default working directory)

**Comment by gwd666** [comment]
1. Editing also works with `file.edit("~/test4.txt")`     
2. When hovering above the tab it shows ~/test4.txt 
3. Opening a file is not a problem 
4. Ctrl + ` output below   
![image](https://user-images.githubusercontent.com/57595487/78504446-a022d780-776d-11ea-88c2-45c26f085f69.png)

**Comment by kevinushey** [comment]
Good news! I've finally been able to reproduce this error locally. The issue does indeed occur if your home directory is set to a UNC path. I initially was not able to reproduce as I was setting the home directory but not matching the case of the UNC path correctly.

Here are some steps to reproduce the issue:

1. Set the `R_USER` environment variable to `\\path\to\server\home`. Be careful to make sure the case matches that of the server + filesystem.

2. Open RStudio, create a file, and then try to save it within the home directory.

That save fails, and it looks like it's because the path isn't constructed correctly:

<img width="225" alt="Screen Shot 2020-04-05 at 9 45 57 AM" src="https://user-images.githubusercontent.com/1976582/78504466-4f39c180-7722-11ea-9285-e79f8b8b5a1f.png">

Now that we can reproduce locally, we should be able to get to the bottom of this issue. Thank you for all your help!

**Comment by kevinushey** [comment]
And here's a way to reproduce locally without requiring a separate network share: just use a UNC path to the home directory.

```
R_USER = \\localhost\c$%HOMEPATH%
```

Will try to get to the bottom of this soon.

**Comment by gwd666** [comment]
Just a reminder comment - as mentioned in the issue title this also happens with RStudio 1.3.036.

**Comment by kevinushey** [comment]
For what it's worth, I believe one workaround would be to set `R_USER` to the same server path (as UNC), but with different casing -- e.g. with the server name capitalized. (This affects how RStudio tries to perform tilde expansion / path aliasing, which I believe is the root cause of the issue here)

If that works, would that suffice as a workaround in the interim?

**Comment by gwd666** [comment]
> If that works, would that suffice as a workaround in the interim?

I will give it a shot tomorrow - thanks a lot for this workaround suggestion. I'm definitely thankful for one until you come up with a fix.

**Comment by kevinushey** [comment]
Note to self: the error is here:

https://github.com/rstudio/rstudio/blob/a977037eac41d764768a06ab551bacadb4e16e8b/src/cpp/shared_core/FilePath.cpp#L1046-L1048

It looks like the file separators aren't normalized the same way in each path, and this causes the attempt to compute a lexically relative path to fail.

I think we can fix this by fixing the path separators before attempting to form a lexically relative path.

**Comment by gwd666** [comment]
> For what it's worth, I believe one workaround would be to set `R_USER` to the same server path (as UNC), but with different casing -- e.g. with the server name capitalized. (This affects how RStudio tries to perform tilde expansion / path aliasing, which I believe is the root cause of the issue here)
> 
> If that works, would that suffice as a workaround in the interim?

This work around does not make 'Save As' to the Users (UNC) home directory available in RStudio. 
Or could you be more a bit more precise on how to set this work-around up? Do you mean via .Rprofile (Sys.setenv()) or in .Renviron or all together outside of R eg defining R_USER in the Users WINDOWS ENV variables? Would appreciate a tip to spare myself trying out all possible combinations.

**Comment by kevinushey** [comment]
> Note: Defining "R_USER" (ie adding it) to the Users WINDOWS ENV variables, worked!

I think that's what I would expect -- RStudio reads the environment variable pretty early on during initialization, so it needs to be set when RStudio is launched (that is, before R itself is initialized).

**Comment by gwd666** [comment]
> > Note: Defining "R_USER" (ie adding it) to the Users WINDOWS ENV variables, worked!
> 
> I think that's what I would expect -- RStudio reads the environment variable pretty early on during initialization, so it needs to be set when RStudio is launched (that is, before R itself is initialized).

Thanks (again) for clarifying that ... so I won't invest any time into modifying Rprofile.site, I guess.

**Comment by gwd666** [comment]
I downloaded preview RStudio-1.3.947.zip and tried to save to UNC HOME fodler -> still the same issue!

**Comment by gwd666** [comment]
Again the save_document_diff details 

== REQUEST ======
{
  "method": "save_document_diff",
  "params": [
    "2ADD2ADE",
    null,
    null,
    null,
    "",
    [],
    "\n",
    937,
    1,
    true,
    "4218041572"
  ],
  "clientId": "33e600bb-c1b1-46bf-b562-ab5cba070b0e",
  "clientVersion": ""
}

== RESPONSE ======
{
  "result": "4218041572",
  "ep": "false"
}

**Comment by gtritchie** [comment]
The Initial 1.3 release will not contain this fix. It was made in 1.3-patch which will be the first bugfix release of 1.3 but is not yet being built. That will start happening once 1.3 has been released.

**Comment by R-Hannibal** [comment]
Hey @gwd666, thanks again for finding and reporting this issue. We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by gwd666** [comment]
@R-Hannibal - will do test - expect info from me by tomorrow

**Comment by gwd666** [comment]
> Hey @gwd666, thanks again for finding and reporting this issue. We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).
> 
> If you get the chance will you let us know if the issue is resolved for you in that build?

@R-Hannibal  first 'plain vanilla' attempts of saving files in RStudio to the Users UNC path home folder worked. I will probably do a couple more variations (eg with modifications in Global Options etc) some time later - but for now it looks very promising. 
Thanks a lot - nice job.

**Comment by R-Hannibal** [comment]
Thanks so much for confirming the fix @gwd666 , and for the kind words (I'm in Quality Assurance but will definitely pass your compliments on to the development team).

Please let us know if you see any variations or re-occurrences of this issue.
