### ISSUE TITLE
Prefer snake_case SQL naming

### ISSUE THREAD

**Issue by ricardofandrade** [rstudio/rstudio#6589]
### System details

    RStudio Edition : 
    RStudio Version : 1.4 
    OS Version      : Ubuntu 18
    R Version       : 3.6.1

### Steps to reproduce the problem

The database introduced for RStudio contains `PascalCase` objects, for example:
https://github.com/rstudio/rstudio/blob/22c112cc31df747e0357d5abf0448c5ced2b5ed7/src/cpp/server/db/20200226141952248123456_AddRevokedCookie.sql#L5

### Describe the problem in detail

For the last several decades, the industry adopted the `snake_case` naming convention for SQL objects such as tables, columns, etc. (with the notable exception of Microsoft SQL Server):
https://blog.jooq.org/2019/10/29/a-guide-to-sql-naming-conventions/
> Also, in most dialects, people prefer snake_case for identifiers, although in SQL Server, people seem to prefer PascalCase or camelCase.

The SQL Server case is more probably due to legacy compatibility MS Office Access than anything else.

There biggest technical reason for this adoption is actually the fact that the SQL standard is itself case-insensitive.
Objects (tables, columns) can be named with upper case characters but then you enter in the world of vendor-specific support (which involves quoting, collation, etc.):
https://stackoverflow.com/questions/153944/is-sql-syntax-case-sensitive

Here are some reasons why `snake_case` is still used even in modern databases:
https://stackoverflow.com/questions/16288586/any-reason-to-still-use-snake-case-for-database-tables-and-columns

Databases themselves use `snake_case` to names their own internal objects. For example here's the list of PostgreSQL own `information_schema` objects:
https://www.postgresql.org/docs/current/information-schema.html

Certain classes of problems are entirely avoided by just following this practice adopted by the majority of the industry:
- Name collision (just different case) with "global" objects. Those objects visible across the entire instance, through any database or schema.
- Naming confusion. Acronyms such as URL have only one representation in snake_case (`url`) but variants may exist when capital letters are used (`URL` or `Url`).
- Portability among database vendors. As mentioned above, mixed-case support varies across vendors. By sticking to `snake_case` it's one less hurdle to futurely add support to another database vendor.

### Describe the behavior you expected

All database objects named with the `snake_case` convention.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Breaking the rule here not to QA my own stuff, but I can assure that the DB entity names are all `snake_case` now

**Comment by ricardofandrade** [comment]
Indeed! I've confirmed that too.
