### ISSUE TITLE
Can't get rid of 'Insert Assignment Operator' keyboard shortcut in Console, only Editor

### ISSUE THREAD

**Issue by hlynurhallgrims** [rstudio/rstudio#6593]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : MacOS Catalina 10.15.4
    R Version       : 3.6.2

### Steps to reproduce the problem

Go to:
Tools > Modify Keyboard Shortcuts

Then remove the Shortcut for _Insert Assignment Operator_ and apply your changes.

![image](https://user-images.githubusercontent.com/6782760/78418594-21bf1c00-762d-11ea-8ce3-1f3872c7954d.png)

Then:
✅  😃 : Within the Editor press `Option`+`-` (or `Alt`+`-` on a PC) and it (thankfully) does not insert the assignment operator. 

❌ 😢 : **Within the Console press `Option`+`-` (or `Alt`+`-` on a PC) and it (sadly) still inserts the assignment operator.** 

### Describe the problem in detail

The default keyboard shortcut for inserting the <- assignment operator masks the keyboard shortcut for a backslash on a Nordic keyboard.

I've removed the shortcut, so I can use the backslash. But removing it only affects the Editor and not the Console. 

I've tried fiddlin' around with the json files for keybindings, to no avail.

~/.R/rstudio/keybindings/rstudio_commands.json
~/.R/rstudio/keybindings/editor_commands.json

So, in summation it seems there's no way to get the Console to stop inserting assignment operators when I want to type in a backslash.

I previously [posted this to the RStudio Community board and was asked by an RStudio Employee to file this bug report. ](https://community.rstudio.com/t/getting-rid-of-insert-assignment-operator-keyboard-shortcut-in-console/58050)

### Describe the behavior you expected

I expected the keyboard shortcut also to stop in the Console once it was removed in _Modify Keyboard Shortcuts_

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@hlynurhallgrims Thank you for filing the issue. I can reproduce it in RStudio 1.3.935 on MacOS 10.15.4. 

Note: that if the shortcut is modified, both the default and new shortcut work in the Console. The Editor is fine—only the new shortcut works.

**Comment by hlynurhallgrims** [comment]
> @hlynurhallgrims Thank you for filing the issue. I can reproduce it in RStudio 1.3.935 on MacOS 10.15.4.
> 
> Note: that if the shortcut is modified, both the default and new shortcut work in the Console. The Editor is fine—only the new shortcut works.

Thanks for the swift reply. I should add that for me (on the system mentioned in the original post) having a random keyboard shortcut (like `Cmd`+`Ctrl`+`Shift`+`M` in my case) works both in the Editor and Console, but doesn't *remove* the original keybinding within the Console. That is to say, even with the new keyboard shortcut defined, `Alt`+`-` does not allow me to write a backslash in the Console, but does in fact still output an assignment operator.

**Comment by rmccombie** [comment]
Ticket to update when this fix is released: 51075

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.753, R Version - 4.0.2, Windows 10 x64 - Desktop 

Comparison testing between current stable (1.3.1073) and the latest Daily, this issue is fixed (clearing the 'Insert Assignment Operator' keyboard shortcut now works in both source and the console).
