### ISSUE TITLE
Running a Shiny app from RStudio, and clicking Don't Save for files with unsaved changes, reverts those files to disk.

### ISSUE THREAD

**Issue by nicholasdavies** [rstudio/rstudio#6603]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : MacOS 10.15.3 Catalina
    R Version       : R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem
Sometimes I have multiple projects on the go in the same RStudio window. I have an R script, `a.R`, open for project 1, which I am making changes to, but have not saved yet as the changes are not complete. I switch over to the file `b.R` for project 2, a Shiny app, and click the `Run App` button. It asks me if I want to save `a.R`. I'm not finished editing that one, and anyway it's not needed to run the app since it's from a different project, so I click `Don't Save`. 

### Describe the problem in detail
Rather than leave `a.R` in its current unsaved state, RStudio reverts that file to the disk version, erasing my unsaved changes.

### Describe the behavior you expected
I expected it to leave `a.R` alone, rather than revert it to the disk version.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@nicholasdavies Thank you for filing this! I can reproduce this in 1.2.5040 and 1.3.935. It doesn't affect untitled files that haven't been saved—those remain unaffected, and aren't included in the list of files to save. I'll mark it for review as we continue development of RStudio.

**Comment by nicholasdavies** [comment]
Thanks @ronblum. Yes I am getting the same thing — the bug is not affecting untitled files. Thanks for looking into it.
