### ISSUE TITLE
Jumpy console while typing

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#6604]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.937
    OS Version      : Mac
    R Version       : 3.6.0

### Details

I am on the latest RStudio RC build for 1.3 (1.3.937) and the Console is “jumping” whenever I type. It doesn't seem to happen all the time, but it happens frequently enough that I really notice it often.

I've attached a .mov video of it happening.

[jumpy.mov.zip](https://github.com/rstudio/rstudio/files/4445675/jumpy.mov.zip)

I also put it on vimeo if that is easier (if it ever processes...) https://vimeo.com/405076804

**Comment by kevinushey** [comment]
Can you also share:

1. The font you're using,
2. The font size,
3. Whether the IDE is zoomed at all?

These factors might affect the behavior here.

**Comment by DavisVaughan** [comment]
Font: Fira Code-Retina
Editor font size: 10
Zoom: 110%

It was connected to an external monitor, but I disconnected it, restarted RStudio, and now it is happening on my laptop display. I am not sure if my external monitor is retina, but probably not.

**Comment by kevinushey** [comment]
Thanks -- I'm able to reproduce now as well after switching to a 110% zoom. Note that reproducing this is finnicky and seems to depend on the amount of console output in the history.

**Comment by DavisVaughan** [comment]
I think I see that too! On a fresh restart of rstudio it doesn't seem to do it immediately. But after typing in a few sets of commands into the console (~10 lines worth?) it starts to do it

**Comment by kevinushey** [comment]
If you hold the down arrow key down, you should also see the console text vibrate, which is fun.

**Comment by DavisVaughan** [comment]
Swapping back to 100% zoom immediately fixes it for me

**Comment by dfalty** [comment]
Looks like this was fixed before the 1.3-patch and is in 1.3.959 :)
