### ISSUE TITLE
Set SameSite explicitly on all cookies

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6608]
RStudio Server does not currently set the `SameSite` attribute on any of its cookies, relying on the browser defaults. There are no known security issues with browser default behavior. However:

1. It is best practice to be explicit about the security policy we want applied to the cookies. This could reduce attack surface; certain kinds of e.g., CSRF attacks become impossible when browsers respect `SameSite`. 
2. Browser defaults are subject to change. Chrome is [changing its default behavior starting in Chrome 80](https://www.chromium.org/updates/same-site). 

More info: https://web.dev/samesite-cookies-explained/

**Comment by jmcphers** [comment]
Like many security policies (e.g., origin checking) we will probably want to ship restrictive behavior out of the box, and allow admins to configure it as necessary for their use cases, e.g., to allow RStudio to run framed from a different domain.

**Comment by ricardofandrade** [comment]
### Testing Notes / Validation Steps

For all tests involving iframe embedding, be sure to set `www-frame-origin=any`.
Most tests should be done over HTTPS.

RStudio cookies are named `csrf-token`, `user-id` and `user-list-id`, `persist-auth`, `port-token` and `session-route`. You may need to check those on the browser dev tools.

**Primary Goal:** The point of the test is to see the IDE loading inside an iframe w/o having to do a double login b/c you should already be authenticated and the cookies should already be there.

**Secondary Goal:** Ensure it all still works fine over HTTP, not embedded, on other browsers, etc.

You can embed using this test site: https://codepen.io/jcheng5/full/vYOMOdv

- Confirm the new behavior works on Chrome 84+. Be sure Chrome is configured for SameSite cookies:
https://www.chromium.org/updates/same-site/test-debug#TOC-I-found-the-problematic-cookie-s-.-Now-what-
  **Login from a different browser tab**, then test that:
  - [ ] Embedding does _NOT_ work by default
  - [ ] Embedding does _NOT_ work with `www-same-site=lax`
  - [ ] Embedding works with `www-same-site=none`
  - [ ] Repeat the first 3 tests above **without embedding** (regular tab), it should always work
  - [ ] Repeat the first 3 tests above **without embedding** (regular tab) **over HTTP**, it should always work

- Confirm the new behavior works on Safari 12 (use browserstack, iOS12 device or macOS Mojave).
  **Login from a different browser tab**, then test that:
  - [ ] Embedding does _NOT_ work by default
  - [ ] Embedding does _NOT_ work with `www-same-site=lax`
  - [ ] Embedding works with `www-same-site=none`
  - [ ] Repeat the first 3 tests above **without embedding** (regular tab), it should always work
  - [ ] Repeat the first 3 tests above **without embedding** (regular tab) **over HTTP**, it should always work

- Confirm the new behavior works on other browser(s).
  **Login from a different browser tab**, then test that:
  - [ ] Embedding does _NOT_ work by default
  - [ ] Embedding _MAY STILL_ work with `www-same-site=lax`, depending on the browser (older should, recent Firefox no)
  - [ ] Embedding works with `www-same-site=none`
  - [ ] Repeat the first 3 tests above **without embedding** (regular tab), it should always work
  - [ ] Repeat the first 3 tests above **without embedding** (regular tab) **over HTTP**, it should always work

**Comment by kfeinauer** [comment]
@ricardofandrade Is there anyone working with Cloud that could verify this one for us? Weren't they the motivation for this change?

**Comment by ricardofandrade** [comment]
This is a security feature of the product in general.
Cloud does indeed wrap the IDE in an iframe, but I'm afraid asking them to test all the other scenarios on different browsers is too big of ask @kfeinauer .

**Comment by rich-rstudio** [comment]
verified functionality on Chrome 87, Safari 12, and Firefox 82.0.3
