### ISSUE TITLE
[Feature request] Closing all terminals panes on project reload

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#6615]
I am accumulating a lot of open terminals over time in a project: Every time I reload the project, RStudio also reloads the history in the terminal pane.
This often takes some seconds and because I do not want to wait, I open a new, fresh terminal using a keybinding. This goes on and on and usually I forget to clear up the list of open terminals, ending up with sometimes 50+ open terminals in a project.
At some point this might probably affect the responsiveness of the app or use quite some system resources?

It would be great if there would be a global option for either/both

- Killing all open terminal panes when quitting RStudio
- Not restoring/keeping terminal histories after reloading a project (i.e. if there are 3 terminals panes open, all would start fresh after a restart of RStudio without the history)

**Comment by ronblum** [comment]
@pat-s Thank you for raising this! There is a "Close All Terminals" menu item—does that do what you're looking for? It's at Tools -> Terminal -> Close All Terminals.

**Comment by pat-s** [comment]
@ronblum Thanks. I am aware of that but I do not like clicking buttons or performing this clean up task manually in general. FWIW I've written a custom addin that does this via the {rstudioapi} package but I'd like to see this one as a global option some time in the future :)

It's really about these two conditions (which might actually be the same)

- **when quitting RStudio**
- **when reloading a project**

**Comment by pat-s** [comment]
I think with the new command palette I am happy now :)

**Comment by ronblum** [comment]
@pat-s Cool, that's good to hear!
