### ISSUE TITLE
Dependency for SUSE 15 inaccurate

### ISSUE THREAD

**Issue by ajmcoqui** [rstudio/rstudio#6617]
Filing on behalf of an end user who emailed us.

----
Just downloaded the rstudio package for OpenSUSE 15:

https://download1.rstudio.org/desktop/opensuse15/x86_64/rstudio-1.2.5033-x86_64.rpm

However, one of the the dependencies its marked as requiring has a typo in it:

   Problem: nothing provides libxkbcommon-x11 needed by rstudio-1.2.5033-1.x86_64

On OpenSUSE Leap 15.x, the dependency is named "libxkbcommon-x11-0" rather than "libxkbcommon-x11".  So, the package refuses to install, unless the end user tells the package manager to ignore the problem and proceed.

The package itself *does* work if the problem is ignored. However, the dependency name should be fixed by whoever in your team creates the package.

Hope that helps. :)

----

**Comment by jmcphers** [comment]
This is fixed in 1.3; see https://github.com/rstudio/rstudio/pull/6276.

**Comment by justinclift** [comment]
Ouch.  Fixed in Feb, and it's now April.

Would it be feasible to add a warning or similar on the download page, letting people know they should just skip the warning message that will be displayed?
