### ISSUE TITLE
Visually indicate focus on Toolbar

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6619]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.929
    OS Version      : MacOS 10.15.4 and Windows 10 pointing at Red Hat 7.8
    R Version       : 3.6.0

### Steps to reproduce the problem

Focus on the toolbar with the toolbar shortcut, e.g. on MacOS, <kbd>Ctrl-Opt-Y</kbd>.

### Describe the problem in detail

Sometimes, nothing indicates that the toolbar has been highlighted. It's not consistent. It seems to always occur on MacOS 10.15.4 with Safari and VoiceOver turned on. Turned off, or on Windows with NVDA turned on or off, it seems to be inconsistent—sometimes it works, sometimes it doesn't. I haven't figured out a good reprex, other than MacOS 10.15.4 + VoiceOver + Safari.

### Describe the behavior you expected

When focusing on the Toolbar, always highlight the first Toolbar menu item, the New File icon, with a square around it.

<img width="199" alt="toolbar_square" src="https://user-images.githubusercontent.com/31009952/78796447-5233ec80-7984-11ea-8f75-a4b857016e62.png">

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
See also: #5960

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990, but there are some other bugs related to the toolbar. Will file issues for them accordingly.
