### ISSUE TITLE
Add Windows & Linux keyboard shortcuts for global & project options

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6620]
It would be great to have keyboard shortcuts for the Project Options and Global Options menus on Windows and Linux, both in RStudio Desktop and when connecting to RStudio Server. Currently they only exist on MacOS.

**Comment by gtritchie** [comment]
Windows applications don't typically have a shortcut for this (unlike Mac, where it's standard). One example that does is Visual Studio Code which uses Ctrl+comma.

**Comment by gtritchie** [comment]
Closing this as "won't fix". It's getting tougher to come up with available keyboard shortcuts, Windows programs don't have a standard shortcut for this (unlike Mac), and you can now also get at these via the Command Palette.

You can, of course, assign your own shortcuts to these.
