### ISSUE TITLE
IDE terminal no longer recognizing hyperlinks

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6621]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.938
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- Open a terminal (Tools / Terminal / New Terminal)
- Do something like `echo "https://rstudio.com"`
- Hover mouse over the resulting output

### Describe the problem in detail
- Nothing special happens

### Describe the behavior you expected
- In RStudio 1.1 and 1.2, you can click on this and launch it as a link in the web browser, but in 1.3 this doesn't happen

Note that xterm.js does not support ANSI hyperlink escapes, see https://github.com/xtermjs/xterm.js/issues/1134

Xterm.js is parsing literal URLs and treating them as links. At least it used to (presumably this stopped working when I updated RStudio 1.3 to newer xterm; this functionality probably moved into an xterm add-on which I didn't include).

**Comment by d-sci** [comment]
Upgraded to 1.3 this week and noticed this. Certainly something I miss! I used to always use the RStudio terminal to `git push` and I'd get a hook back from the remote with a URL to open a pull request; it's no longer clickable with 1.3

**Comment by gtritchie** [comment]
I'll take a look and see if this is something we can safely sneak back into 1.4, though we are getting close to code-complete so might not make it.

**Comment by dfalty** [comment]
Verified hyperlinks now are clickable in the terminal and open the desired link in the browser v1.4.874.
