### ISSUE TITLE
MacOS: Shift-CMD-/ does not activate Help - Search as is standard Mac behaviour

### ISSUE THREAD

**Issue by rkrug** [rstudio/rstudio#6625]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : macOS 10.15.4
    R Version       : 3.6.3

### Steps to reproduce the problem
- Start RStudio
- Press Shift-CMD-/

Nothing happens

The shortcut is systemwide activated and works in all other Apps I am aware off.

### Describe the problem in detail
The standard Mac command Shift-CMD-/ does not activate the Search in the Help Menu.

### Describe the behavior you expected
I expect the Search in the Help Menu to become activated to directly enter a search term

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@rkrug Thank you for filing the issue! This is fixed in the upcoming 1.3 Middlemist Red release. You can download [the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/) if you're interested. (Note that preview builds are intended for testing purposes only.)
