### ISSUE TITLE
Changed font now I have very odd help pane behaviour

### ISSUE THREAD

**Issue by rlh1994** [rstudio/rstudio#6626]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.5033
    OS Version      :  Windows 8.1 Enterprise
    R Version       :  3.6.1

### Steps to reproduce the problem
This was how I got the problem, however I cannot confirm exactly what caused it as changing the font back does not solve the issue:

- Install fira code font sets (https://github.com/tonsky/FiraCode) 
- Select one of these fonts within the RStudio preferences
- Reboot RStudio
- Load any function help page

### Describe the problem in detail

Since installing a new font and changing the font within RStudio I have had the help pane look very odd (similar to spongebob meme font...), with seemingly random upper and lower case letters for any function. The fonts load correctly in every other pane as far as I can tell (have not been able to test the connections pane).

Again, changing to another font seems to not be able to revert this bug. Also note that "code" text (Not sure official name, usually that created within ticks) is correctly displayed. 

![image](https://user-images.githubusercontent.com/8260415/78905348-c39f9800-7a75-11ea-9007-fefca6f2c617.png)

### Describe the behavior you expected

The normal text correctly displayed within the help pane.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@rlh1994 Thank you for raising the issue! I'm unable to reproduce it, though, on Windows 10 using either RStudio Desktop 1.3.395 and 1.2.5033, switching back and forth between Fira Code and non-Fira Code fonts. I'll mark it for triage to see if there's other information that could be useful.

**Comment by rlh1994** [comment]
Having look at it more than any sane man should, it looks a if its the same letters that are always upper or lowercase. I wonder if I somehow managed to break the default font when installing fira code, although I have no idea how. Do you know what font the help pane uses and if this is not overwritten by the user choice?

**Comment by kevinushey** [comment]
RStudio uses the system's default `sans-serif` font in the Help pane, so my best guess is you somehow changed the default system font and now RStudio is picking that up.

**Comment by rlh1994** [comment]
I've managed to find the issue. When changing the font I forgot that I had also installed a new theme; and given that it was the text looking weird I just assumed it was the font. When I change back to an in-built theme this all works correctly again, sorry!
