### ISSUE TITLE
Default light/dark themes, switch depending on OS theme

### ISSUE THREAD

**Issue by serivas** [rstudio/rstudio#6627]
# Theme sync with OS settings

It'd be great being having the option to automatically switch between themes depending on the OS's settings. For instance, if my Windows 10 OS is set to "dark", it'd be great having the option to make R Studio automatically switch to dark

# Default light/dark themes

As an extension, we could have 2 fields where we select which themes would this behavior default to

# Inspiration

VS Code has this exact same behavior, which is amazing for busy 'round the clock developers

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/5813.
