### ISSUE TITLE
Include RStudio/R version in startup diagnostics; provide copyable report

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6628]
RStudio 1.3 includes a new startup diagnostics feature that shows lots of diagnostic information (instead of the generic "can't connect to 127.0.0.1" web browser error) when the R session does not launch successfully.

People who are looking for help with their R session start failures have started posting screenshots of this page for help, e.g.:

https://community.rstudio.com/t/rstudio-desktop-issue-with-catalina/59809

This is much more helpful than the screenshots they used to share (which were just of the 127.0.0.1 error), but further improvement would be very helpful. In particular:

1. We should show the RStudio version (and the R version, if easy to obtain) on this page so it appears in screenshots. This will make it much easier to sort out whether the errors are due to older versions of RStudio.
2. We should provide a plain-text version of the errors which can be copied, or simply a "Copy problem report" button which prepares text on the clipboard. This will make it easier to report errors (it is trickier to upload images), and it will also make the text in the errors searchable, so people are more likely to discover other users who have the same problem.

**Comment by jmcphers** [comment]
We are still frequently getting screenshots of this error screen.

**Comment by cm421** [comment]
### Verified Fixed

```
RStudio Edition : Desktop
RStudio Version : 1.4.1680
OS Version      : macOS 11.2.3
R Version       : 4.0.5
```

Verified that:
- RStudio Version and platform info are included in error diagnostics
- The "Copy Problem Report" button copies the diagnostic report in plain markdown text
