### ISSUE TITLE
Cannot access files in ~/../<user>_x

### ISSUE THREAD

**Issue by viktor76525** [rstudio/rstudio#6629]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.5033
    OS Version      :  Linux 4.19.72-gentoo
    R Version       :  3.6.2

### Steps to reproduce the problem
1. make folder /home/<current_user>_test
2. use Files pane to browse to above location

### Describe the problem in detail
Attempting to open anything in the directory above will case error: 
"Error navigating to ~/../<current_user>_test: No such file or directory."
Then the Files browser will go to the home directory.
Doesn't happen when going to others' home directories.
Can manually enter path which opens fine but going into a subdirectory via clicks or clicking a file will throw above error "No such file or directory".
Have tried with <current_user>_h, <current_user>_test, didn't work. Have tried other folders "/home/other" not belonging to a system user which worked.

### Describe the behavior you expected
Can browse a directory in the Files pane in the form /home/<current_user>_test

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@viktor76525 Thank you for raising the issue! What are the permissions and ownership of the directory?

**Comment by kevinushey** [comment]
We've seen issues of this form occur when the `HOME` environment variable has a trailing slash. Is that true in your case? What is the output of:

```
Sys.getenv("HOME")
```

Note that this issue should be fixed in the v1.3 [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by viktor76525** [comment]
Sorry for the delay.

drwxrwxr-x user is owner, group is primary user group

> Sys.getenv("HOME")
[1] "/home/aaa00"

Actually the home directory is a symlink to another drive. The other users' directories that are accessible are normal, just like the ones with underscores.

**Comment by viktor76525** [comment]
I think it may have to do with the home location being a symlink. I have tried accessing a similar pattern and same folder with other user accounts, they all work.

**Comment by kevinushey** [comment]
What is the value of the symlink -- e.g. what is the output of:

```
readlink /home/aaa00
```

Was the symlink formed with a trailing slash?

**Comment by viktor76525** [comment]
symlink points to
`/mnt/E500/aaa00`
E500 is the mount point of another drive

**Comment by viktor76525** [comment]
I've tried to recreate the symlink with the command:
`/home # ln -s /mnt/E500/aaa00 aaa00`
still happening

**Comment by viktor76525** [comment]
Today I updated to Rstudio `1.3.959` and the issue is gone at least in 1.3. :tada:

**Comment by kevinushey** [comment]
Phew! That's great to hear.
