### ISSUE TITLE
Specify output units for --- and add rulers to --- plot viewer window pane 

### ISSUE THREAD

**Issue by ssp3nc3r** [rstudio/rstudio#6631]
Two features to the plot window --- 1) adding rulers (which can be shown or hidden) that can show various units (pixels and line and type units, and 2) adding a way to specify viewing window size based on units like mm --- would ease ongoing confusion between the various units at play in plots viewed this way (e.g., lines and type in units of mm, plot dimensions in units independent of those), and would make viewing more consistent with, say, saving the plot as a sized pdf.

**Comment by ronblum** [comment]
@ssp3nc3r Thank you for the suggestions! We'll review them as we continue development of RStudio.
