### ISSUE TITLE
provide command / icon to clear Build pane output

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6636]
If the Build pane becomes overloaded with output, the IDE will become very slow. We should consider providing a button to clear any build pane output in that case.

**Comment by cdriveraus** [comment]
This is killing my ability to work in Rstudio... any suggestions for workarounds in the meantime? I have a very modern pc but I think the switch to rtools 4.0 is generating more compile messages.

**Comment by cdriveraus** [comment]
just to add to this... it seems like builds are actually taking far longer than they should because of this issue, so simply clearing the log afterwards is only a minor patch on a bigger problem.

**Comment by kevinushey** [comment]
A reproducible example would be helpful.

**Comment by gtritchie** [comment]
See also: #7287

**Comment by jmcphers** [comment]
@adamconroy is this resolved now that the Build pane is virtualized?

**Comment by kevinushey** [comment]
I believe it will be once https://github.com/rstudio/rstudio/issues/7725 is resolved.

**Comment by adamconroy** [comment]
It would be, I suppose, though as user I wouldn't mind this functionality still being added. I looked into doing this last week and we already have a clear build pane command so it shouldn't be much more than adding in the icon we already have from the console and tying it to that command. I will do this the same time that I'm doing 7725.

**Comment by dfalty** [comment]
Verified functionality in v1.4.874.
