### ISSUE TITLE
unable to open new files after dismissing attempt to open a large file

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6637]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.938
    OS Version      : macOS 10.15.4
    R Version       : 3.6.3

### Steps to reproduce the problem

Create and open a text file ~3MB in size; e.g.

```
owd <- setwd(tempdir())
words <- rep.int("words", 6E5)
writeLines(words, con = "words.txt")
file.edit("words.txt")
setwd(owd)
```

When this code is run, you'll get a dialog asking if you want to open the large file. Click No on the dialog.

<img width="430" alt="Screen Shot 2020-04-10 at 3 02 53 PM" src="https://user-images.githubusercontent.com/1976582/79026036-6884a880-7b3c-11ea-9123-0677c002834d.png">

### Describe the problem in detail

After clicking No, no new files can be opened.

### Describe the behavior you expected

We should still be able to open files.

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.753, R Version - 4.0.2, Windows 10 x64 - Desktop 

Files can now be opened successfully after dismissing the dialogue option to open a large file.
