### ISSUE TITLE
Knit button don't update when output format change in yaml

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#6643]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.938
    OS Version      : Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem

* create a new Rmarkdown file using RStudio IDE. 
* This will be a `html_document` format and you'll have a Knit button with blue logo
* Save the file. 
* Change to `html_notebook` in the yaml header
* Re-save the modified file
* You'll still have the knit button instead of the usual preview button
*  if you right-click anywhere on RStudio IDE and click reload, you'll get the correct preview button

### Describe the problem in detail

When modifying the ouput format in the yaml, RStudio IDE does not update anymore its knit button to the correct format. 

### Describe the behavior you expected

In previous version 1.2.5033, when following the steps to reproduce, the knit button updates correctly to preview as soon as the document is saved with `html_notebook` in it. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I'd lay even money this is a regression from https://github.com/rstudio/rstudio/pull/6442.

**Comment by dfalty** [comment]
Verified fixed 1.3.1031.
