### ISSUE TITLE
Replace in files with UTF8

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/rstudio#6644]
## System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.938
    OS Version      :  Win 10 pro
    R Version       :  3.6.3 (64 bit)

### Steps to reproduce the problem
copy paste some UTF8 char from, eg Word to some file(s). You can try with an "à" or an m-dash, or an open-quote....

try to find-replace (eg w/ `\u00E0`, or `--`, or `\"`) from the standard (single file) interface, and it works correctly. Doing the same thing from the "Raplace All" in "Find in Files" produce unexpected errors (generates unexpected symbols in that interface, which are rendered as "?" in the file viewer.

### Describe the problem in detail

1. detection: 
![detect](https://user-images.githubusercontent.com/6473683/79047179-66dae380-7c15-11ea-9603-08a433fa06c5.png)

2. preview of the replace (in find all files) [which seems correct....] :
![preview_replace_all](https://user-images.githubusercontent.com/6473683/79047186-72c6a580-7c15-11ea-806c-885e805bafc4.png)

3. actual replacement [which is wrong!]:
![actual replacement](https://user-images.githubusercontent.com/6473683/79047200-8245ee80-7c15-11ea-94a7-313e731465f5.png)

4. standard replace "all" in a single file works properly!!

![standard-replace-all](https://user-images.githubusercontent.com/6473683/79047254-c46f3000-7c15-11ea-9efb-cd23713394ac.png)

### Describe the behavior you expected

It works correctly as in the standard interface

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@CorradoLanera Thank you for raising this! I can reproduce it in RStudio Desktop 1.3.395 on MacOS 10.15.4, and we'll review it during our ongoing development of RStudio.

**Comment by melissa-barca** [comment]
@ronblum I believe this issue was fixed with #6841. I just tried to reproduce and was unable to. Can you confirm? Thank you.

**Comment by melissa-barca** [comment]
This has been fixed for 1.4

**Comment by kevinushey** [comment]
Verified in 1.4.945. Tested with package sources at https://github.com/kevinushey/nihao.

<img width="273" alt="Screen Shot 2020-10-16 at 1 06 14 PM" src="https://user-images.githubusercontent.com/1976582/96304136-6c442c80-0fb0-11eb-9e61-5457ba0dd818.png">

<img width="609" alt="Screen Shot 2020-10-16 at 1 05 46 PM" src="https://user-images.githubusercontent.com/1976582/96304146-6ea68680-0fb0-11eb-90ba-fea7d7a2739b.png">

<img width="291" alt="Screen Shot 2020-10-16 at 1 06 06 PM" src="https://user-images.githubusercontent.com/1976582/96304149-7108e080-0fb0-11eb-949a-7d2c4b680460.png">
