### ISSUE TITLE
Consider dropping support for Internet Explorer in RStudio Server 1.4

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6648]
Opening for future discussion: can we reasonably drop support for Internet Explorer (including IE11) in RStudio Server 1.4?

IE11 is frozen in time and increasingly falling behind in basic HTML, CSS, and JavaScript functionality available in modern browsers (Chrome, Firefox, Edge/Chromium, Safari, etc.).

Not having to worry about coding for, or testing with, IE11 would be... nice.

**Comment by jmcphers** [comment]
It is not super likely that we can do this without angering at least some customers. IE11 is a pain, but it's a Windows component with an accompanying support agreement. It was just a couple of months ago that Windows Server 2012 users were urged to _upgrade_ to IE11. Some very big and conservative industries (banks, health care) do not permit the installation of any non-bundled browsers (including Edge).

 https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer-and-edge

**Comment by jmcphers** [comment]
This issue is IE11 specific: https://github.com/rstudio/rstudio/issues/6676. Anecdotally it turns out to have impacted a large number of RStudio.cloud users which is further evidence that we can't drop support anytime soon.

**Comment by R-Hannibal** [comment]
Marking this issue as 'verified'.

We will continue to support IE11 until we don't anymore 😜.

**Comment by gtritchie** [comment]
> We will continue to support IE11 until we don't anymore 😜.

Boo! Hiss!!
