### ISSUE TITLE
documentNew() creates as many new documents as existing popped out windows

### ISSUE THREAD

**Issue by AltfunsMA** [rstudio/rstudio#6649]
When I have any source documents popped out, calling `documentNew(text = "any text")` opens up a new script in the source editor pane and in all of the popped out windows. 

The expected behaviour is that it will only open a new script in the source editor pane.

This looks to be the same issue as rstudio/rstudioapi#55, which is marked as closed; but I'm afraid I didn't find any other hints that as to whether `documentNew()` should/shouldn't suffer from this still/anymore.

Running RStudio Desktop 1.2.5033 with R 3.6.3 and rstudioapi v. 0.11

**Comment by melissa-barca** [comment]
The new multiple source column code may need to be considered when implementing this fix.

**Comment by jmcphers** [comment]
The problem is probably that the event that triggers the new document to be created is inappropriately being propagated to the satellite windows. We could avoid that propagation, or we could ignore that event when we are a satellite.

**Comment by kevinushey** [comment]
In particular, I believe the event should be routed to the currently-active (or last-focused) Source window, rather than just always the main window.

**Comment by R-Hannibal** [comment]
@AltfunsMA, thanks again for finding and reporting this issue.

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by rich-rstudio** [comment]
verified on MacOS desktop Version 1.4.854
