### ISSUE TITLE
Callback for `rstudioapi::highlightUi`

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#6650]
`rstudioapi::highlightUi` allows us to highlight particular portions of the IDE. Unfortunately, we don't have a way for the user to "acknowledge" or dismiss the highlight.

<img width="350" alt="Screen Shot 2020-04-13 at 1 33 30 PM" src="https://user-images.githubusercontent.com/1593639/79148618-49dd1680-7db5-11ea-9df5-3c4565827bc9.png">

We'd like a way to monitor whether or not the user has clicked on the highlighted element. We could accomplish that either via:

1. a new callback parameter on `highlightUi` that tells you when the highlighted element has been clicked (might this be as simple as a click handler for `.highlightEl`?), or
2. global event callbacks -- if we had some event system in rstudioapi that allowed us to monitor all clicks globally (I'm envisinoing something like [jQuery's `.on()`](https://api.jquery.com/on/), then we could just monitor for the appropriate event ourselves.

-----

P.S. This feature might be a prerequisite for a more pronounced UI treatment of highilghts in which you gray out/blur the rest of the screen and leave only the highlighted element exposed. We could only consider such a treatment if we had a way to then remove that grayed-out background.

**Comment by kevinushey** [comment]
I think this also needs to be aware of the underlying command -- e.g. you'd likely want the highlight UI to be dismissed (or the tutorial to progress) if the user executed the command from a shortcut. In this example, if the user used <kbd>Ctrl + S</kbd> to save the document, that should likely suffice.

**Comment by trestletech** [comment]
Yeah. I agree that would be the best-case scenario. But honestly for the "getting started" use case that we have in mind, I think it'd be fine to require a click. I feel like that's the level of intelligence that I've seen in most of the in-product tutorials that I've seen. At least for our use-case, I wouldn't consider that functionality a requirement at all.

**Comment by jmcphers** [comment]
Fixed in #6735.

**Comment by R-Hannibal** [comment]
QA Note: This fix got merged into 1.3 and is now live in the current stable build 1.3.1073.

**Comment by R-Hannibal** [comment]
@trestletech - As per the previous comment, this fix is now live in the stable build but has not actually been verified as of yet.

Have you had a chance to try out this enhancement/is it looking like it meets your needs? No worries if you haven't had a chance to try it, we can verify internally on the [current stable 1.3](https://rstudio.com/products/rstudio/download/).

**Comment by trestletech** [comment]
Yes we've been using it and so far it's working as we expected!
