### ISSUE TITLE
Make highlights more noticeable

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#6651]
`rstudioapi::highlightUi()` helpfully highlights a part of the RStudio IDE with a blue bounding box. However, the highlight box blends in with the IDE background, which makes it easy to miss. Consider:

```r
rstudioapi::highlightUi("#rstudio_tb_savesourcedoc_7")
```

<img width="1546" alt="Screen Shot 2020-04-13 at 2 40 36 PM" src="https://user-images.githubusercontent.com/85014/79149214-ce6b6d00-7d94-11ea-933e-6e473445fa47.png">

Can we improve the effectiveness of the highlight result by altering the css, [here](https://github.com/rstudio/rstudio/blob/cc335fff58d2a1c150b9ec7996fbbde1a71a0e45/src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.css#L1-L54), to:
1. Increase the contrast of the highlight color vis-a-vis the IDE background
2. Add a pulse animation to the highlight

Thanks!

**Comment by trestletech** [comment]
(Just an FYI: it actually does have a pulse animation currently, it's just slow and subtle.)

**Comment by gregswinehart** [comment]
If we can add a border, then use a box-shadow to pulse, this CSS might look nice: https://animation--rstudio-com.netlify.com/animation/

**Comment by melissa-barca** [comment]
Closed in #6793

**Comment by dfalty** [comment]
Verified the functionality on version 1.4.874. @garrettgman @trestletech Let us know if this works for you!
