### ISSUE TITLE
Extend highlightUI to elements of the R Markdown editor

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#6652]
`rstudioapi::highlightUi` allows us to highlight particular portions of the IDE. However, `rstudioapi::highlightUi`provides limited ability to provide guidance on the R Markdown experience, because it cannot highlight elements that appear _within_ the R Markdown editor. This is a shame because the R markdown experience is the central IDE experience for many R users—including for beginners.

We'd like a way to be able to highlight:
1. The play button for a code chunk, perhaps designated by chunk label or line number
2. The other buttons associated with the code chunk
3. The results displayed inline beneath a code chunk
4. A portion of an open document, designated by line numbers
5. A portion of a line, designated by line number and column numbers

**Comment by melissa-barca** [comment]
Closed in #6787

**Comment by R-Hannibal** [comment]
@garrettgman, thanks for filing this 👍. 

It looks like this fix went out in the last 1.3 patch and is now a part of the [stable build](https://rstudio.com/products/rstudio/download/) even though it hasn't been formally verified as of yet. If you get the chance will you confirm that this enhancement has been added and is meeting your needs?

**Comment by melissa-barca** [comment]
Sorry about that @kfeinauer! The chunk names were standardized when closing #6897. That PR has the correct field names -- you can verify the names by going to the Help menu and selecting Diagnostics >> Show DOM Elements. This gives you the id and class name for every element we've intentionally assigned ones to.

**Comment by kfeinauer** [comment]
Thanks for the clarification @melissa-barca. Looks like everything works as expected on 1.4.944.

This worked for chunk output:

> rstudioapi::highlightUi(".rstudio_chunk_output_pressure")

Chunk run button:

> rstudioapi::highlightUi("#rstudio_source_text_editor_3 [title='Run Current Chunk']")

**Comment by kfeinauer** [comment]
@melissa-barca I have noticed an issue though - I don't think there is a way to differentiate between the various `Run Chunk` buttons - I see just the same DOM elements for all of them:

```
img.rstudio_run_chunk
div#rstudio_source_text_editor_3
div.rstudio_source_panel
div#rstudio_container
```

Does this warrant reopening the issue?

**Comment by melissa-barca** [comment]
@kfeinauer Nope, the intent is for those to be generic, but can be combined with a different class to highlight a specific one like we do in this example:

> rstudioapi::highlightUi("#rstudio_source_text_editor_3 [title='Run Current Chunk']")

**Comment by kfeinauer** [comment]
@melissa-barca the problem with that is in your original PR, you could differentiate between the different Run Current Chunk buttons. Whereas after the linked PR, there is no way to differentiate between them now - they all have the same base `source_text_editor` class and the same title name.

**Comment by melissa-barca** [comment]
@kfeinauer Sorry about that, you would run the following: 

> rstudioapi::highlightUi(".rstudio_chunk_pressure .rstudio_run_chunk")

The chunk has a specific class name, though it can't individually be highlighted nor will it show with the DOM helper so you need to include this with the button class. The way the UI is laid out the benefit of being able to highlight a specific chunk wasn't worth the cost.

**Comment by kfeinauer** [comment]
Okay thanks for the clarification @melissa-barca.

Working as expected!
