### ISSUE TITLE
Cmd-Enter not moving cursor to next line on latest Dailies on macOS 10.15.5

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#6653]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.185
    OS Version      : macOS 10.15.5 (beta 1)
    R Version       :  3.6.3

### Steps to reproduce the problem

Open up an existing or create a new R script in RStudio. Try to Cmd-Enter execute lines. The cursor does not move down a line.

Here's the pref's:

![image](https://user-images.githubusercontent.com/509878/79152276-e691bb00-7d99-11ea-87ec-5ea314f524cb.png)

Here's the behavior in action. NOTE that after Cmd-Enter fails to move to the next line (after a few tries) I used the down arrow just to show it happens on other lines.

![cmd-enter](https://user-images.githubusercontent.com/509878/79153126-5c4a5680-7d9b-11ea-93bb-f2d6dee6f4ea.gif)

### Describe the problem in detail

See ^^

### Describe the behavior you expected

The cursor to move to the next line.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be fixed by https://github.com/rstudio/rstudio/pull/6634. Thanks!
