### ISSUE TITLE
Different Column Number when Hovering Mouse over Column Name

### ISSUE THREAD

**Issue by hn4ever** [rstudio/rstudio#6659]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : macOS Catalina 10.15.4
    R Version       : 3.6.3

### Steps to reproduce the problem

Run this code:
`data <- matrix(rnorm(60*80), nrow = 60)`
`View(data)`

### Describe the problem in detail

When hovering over the column name, it shows the wrong number: it shows 107 instead of 77 (offset by 30).

![table](https://user-images.githubusercontent.com/34647172/79174348-4fcff900-7daf-11ea-97b0-3fac83344251.png)

### Describe the behavior you expected
I expect Rstudio to show the correct column numbers, for example: in the attached image I expect it to show 77 instead of 107.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@hn4ever Thank you for filing the issue! I can reproduce this in several instances of RStudio Desktop 1.2 on MacOS 10.15.4. However, this is working in 1.3.938 Middlemist Red. If you'd like to try it out, the [the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/) is available at https://www.rstudio.com/products/rstudio/download/preview/. (Note that preview builds are intended for testing purposes only.)
