### ISSUE TITLE
First boot of RStudio 1.3 does not show source tabs from 1.2

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6661]
### System details

    RStudio Edition : Desktop/Server
    RStudio Version : 1.3.938

### Steps to reproduce the problem

1. Remove all RStudio 1.3 state and settings (`~/.config/rstudio`, `~/.local/share/rstudio`) and close all copies of RStudio.
2. Install RStudio 1.2.5042.
3. Start RStudio, create a project and several R files. Open them all in editor tabs.
4. Close all copies of RStudio.
5. Install RStudio 1.3.938
6. Start RStudio. No editor tabs are open.
7. Close RStudio.
8. Start RStudio again. Editor tabs are restored.

### Describe the problem in detail

RStudio does not show any editor tabs in step 6, but does in step 8. 

### Describe the behavior you expected

Editor tabs should be restored on the very first RStudio boot.

**Comment by jmcphers** [comment]
The reason this is happening is that we are doing the context ID migration successfully but too late. Without the migrated context ID, the very first session doesn't get the right set of source tabs.

https://github.com/rstudio/rstudio/blob/5f78f5b6648d0bcda7dac41681ddf0efcc966f9d/src/cpp/session/modules/SessionUserPrefsMigration.cpp#L252-L255

**Comment by rich-rstudio** [comment]
verified on 
- MacOS RDP 1.3.944-1 Preview 
- MacOS OS desktop
- Ubuntu OS Server
