### ISSUE TITLE
FR: Unsaved changes dialog: Make it possible to tab through options?

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#6663]
Every time when this one pops up I have no way but to use the mouse to select the "don't save" option.

Is there a way to tab through the options and select "don't save" without using the mouse?

- `Return` selects the one highlighted in blue
- Esc essentially hits "cancel"

<img width="454" alt="Screenshot 2020-04-14 at 09 59 42" src="https://user-images.githubusercontent.com/8430564/79268263-c4339680-7e9a-11ea-919a-cdbbfe34f9f4.png">

**Comment by gtritchie** [comment]
This is, surprisingly enough, a feature you have to enable in macOS, and not a function of RStudio itself.

Done in Keyboard Preferences:

<img width="668" alt="macOS Keyboard Shortcut preferences showing checkbox for enabling Tab navigation" src="https://user-images.githubusercontent.com/10569626/79269999-2f0caf80-7e52-11ea-8a57-a2f93381be14.png">

**Comment by pat-s** [comment]
Oh wow ... ;) Thanks a ton, Gary!!

**Comment by pat-s** [comment]
@gtritchie Follow-up with possible bug(?): When I TAB through the options and select one that is not "Save" and hit `Return`, "Save" is executed nonetheless. Is this an issue of RStudio?

**Comment by gtritchie** [comment]
Use `spacebar` to activate the focused button. `return` actually always activates the "default" button (the one drawn in blue) no matter where focus is located. You can also see this (for example) if you try this scenario in TextEdit.

**Comment by gtritchie** [comment]
So, this is all behaving as expected (though almost nobody expects it or wonders why one of the buttons is blue!).
