### ISSUE TITLE
'rs.getPackageInformation' runs in background for a long time

### ISSUE THREAD

**Issue by Javdat** [rstudio/rstudio#6667]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      :  Mac OS 10.15.4
    R Version       :  Microsoft R Open 3.5.0

### Steps to reproduce the problem
It is automatic in background.
### Describe the problem in detail
 R sometime runs in the background and consumes heavy load for a long time. Debugging points at `rs.getPackageInformation`, which I think is used to get autocomplete information by Rstudio.

But it runs for a quite  a while. Any reason why it should runs for so long? Can it be bug or decreased?

![image](https://user-images.githubusercontent.com/19429297/79325327-48c0fc00-7f11-11ea-9d01-137214fe6fc0.png)

![image](https://user-images.githubusercontent.com/19429297/79325423-70b05f80-7f11-11ea-816f-a4916cbb02d5.png)
### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Javdat** [comment]
Attaching call sample:
[R.sample.txt](https://github.com/rstudio/rstudio/files/4480611/R.sample.txt)

**Comment by kevinushey** [comment]
IIUC it seems like a segfault occurred while R was trying to do some work, and (perhaps) got into a recursive loop in trying to handle that signal?

```
    24354 Thread_511268   DispatchQueue_1: com.apple.main-thread  (serial)
    + 24354 Rf_EncodeElement  (in libR.dylib) + 24  [0x10e8364e8]
    +   24354 _sigtramp  (in libsystem_platform.dylib) + 29  [0x7fff6d0395fd]
    +     24354 signalHandler(int, __siginfo*, void*)  (in libjvm.dylib) + 45  [0x1125dc98d]
    +       24354 JVM_handle_bsd_signal  (in libjvm.dylib) + 771  [0x1125df433]
    +         24354 os::Bsd::chained_handler(int, __siginfo*, void*)  (in libjvm.dylib) + 148  [0x1125dcaa0]
    +           24354 sigactionSegv  (in libR.dylib) + 303  [0x10e7fb3df]
    +             24354 0x0
    +               24354 _sigtramp  (in libsystem_platform.dylib) + 29  [0x7fff6d0395fd]
    +                 24354 signalHandler(int, __siginfo*, void*)  (in libjvm.dylib) + 45  [0x1125dc98d]
    +                   24354 JVM_handle_bsd_signal  (in libjvm.dylib) + 771  [0x1125df433]
    +                     24354 os::Bsd::chained_handler(int, __siginfo*, void*)  (in libjvm.dylib) + 148  [0x1125dcaa0]
    +                       24354 sigactionSegv  (in libR.dylib) + 303  [0x10e7fb3df]
    +                         24354 R_GetTraceback  (in libR.dylib) + 48  [0x10e7afe30]
```

You should also be able to call the function directly from RStudio; e.g. `.rs.getPackageInformation(...)`, with the required packages. Can you reproduce with some subset of the packages in your original report?

**Comment by Javdat** [comment]
Strangely when I run them manually (both individually and together) they finish fine.

```
.rs.getPackageInformation('GAS')
.rs.getPackageInformation('NNKCDE')
.rs.getPackageInformation('PerformanceAnalytics')
.rs.getPackageInformation('RFCDE')
.rs.getPackageInformation('TTR')
.rs.getPackageInformation('abind')
.rs.getPackageInformation('bartMachine')
.rs.getPackageInformation('caTools')
.rs.getPackageInformation('caret')
.rs.getPackageInformation('data.table')
.rs.getPackageInformation('doMC')
.rs.getPackageInformation('dygraphs')
.rs.getPackageInformation('esreg')
.rs.getPackageInformation('glmnet')
.rs.getPackageInformation('grf')
.rs.getPackageInformation('h2o')
.rs.getPackageInformation('magrittr')
.rs.getPackageInformation('matrixStats')
.rs.getPackageInformation('party')
.rs.getPackageInformation('quantreg')
.rs.getPackageInformation('quantregForest')
.rs.getPackageInformation('ranger')
.rs.getPackageInformation('reticulate')
.rs.getPackageInformation('rfinterval')
.rs.getPackageInformation('rqPen')
.rs.getPackageInformation('rugarch')
.rs.getPackageInformation('xts')


a  <- .rs.getPackageInformation(
  'GAS',
  'NNKCDE',
  'PerformanceAnalytics',
  'RFCDE',
  'TTR',
  'abind',
  'bartMachine',
  'caTools',
  'caret',
  'data.table',
  'doMC',
  'dygraphs',
  'esreg',
  'glmnet',
  'grf',
  'h2o',
  'magrittr',
  'matrixStats',
  'party',
  'quantreg',
  'quantregForest',
  'ranger',
  'reticulate',
  'rfinterval',
  'rqPen',
  'xts'
)

```

**Comment by mikebessuille** [comment]
Unfortunately we have not been able to reproduce this.  Closing; we can re-open if users continue to encounter this.
