### ISSUE TITLE
Running pwd in Terminal takes me to .Trash folder after launching .Rproj files

### ISSUE THREAD

**Issue by daranzolin** [rstudio/rstudio#6674]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.3.919
    OS Version      :  x86_64-apple-darwin15.6.0 (64-bit) macOS Mojave 10.14.6
    R Version       :  3.6.1

### Steps to reproduce the problem

1. Clone a git repository with a .Rproj.
2. Delete the entire directory.
3. Re-clone the same git repository.
4. Launch the .Rproj in RStudio and navigate to Terminal tab.
5. Run pwd

### Describe the problem in detail

I deleted an old, git-controlled, directory with a .Rproj file (rsfsu). I cloned the updated repo to the same location, launched the .Rproj in RStudio, but when I went to Terminal, it takes me to a strange location:

```
Davids-MacBook-Pro-2:rsfsu davidranzolin$ pwd
/Users/davidranzolin/Library/Mobile Documents/com~apple~CloudDocs/.Trash/rsfsu
```

Furthermore, my older, uncommitted git activity appears when I run `git status`. 

### Describe the behavior you expected

I would expect the pwd to be wherever I cloned the repo and to not include my old git activity.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@daranzolin Thank you for filing the issue! I can't reproduce it, though. When you clone the repository and delete it, are you doing so within RStudio or from the command line?

**Comment by daranzolin** [comment]
Hi @ronblum, thanks for reaching out! I was cloning from an open Terminal, and deleting and launching the project from Finder. I then tried deleting the repo again from the command line with the same result. Everything looks fine in the R console:
```
> getwd()
[1] "/Users/davidranzolin/Desktop/rsfsu"
> system("pwd")
/Users/davidranzolin/Desktop/rsfsu 
```
But again, running the same command from Terminal:

```
Davids-MacBook-Pro-2:rsfsu davidranzolin$ pwd
/Users/davidranzolin/Library/Mobile Documents/com~apple~CloudDocs/.Trash/rsfsu
```

**Comment by daranzolin** [comment]
Update: when I clone the repo to a different location, everything functions as expected.
