### ISSUE TITLE
Saving does not work in IE11

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6676]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.928

### Steps to reproduce the problem

1. Open a project in IE11
2. Open an .R file
3. Make some changes
4. Save them 
5. Switch to the Terminal tab and examine the actual contents of the file with e.g. `cat`

### Describe the problem in detail

RStudio does not actually save the changes; the file looks saved but its contents on disk do not change. 

### Describe the behavior you expected

All changes saved.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Server Version 1.3.944 (OS Info: SLES (SUSE) 12 SP4), accessed through an IE11 browser (Version 11.778.18362.0).

Verified that file changes across all different file types are now saving successfully. Files can be opened > edited > saved > closed > and re-opened, without losing edits in an IE11 browser.

**Comment by kippandrew** [comment]
Is there any chance this issue affect users of Microsoft Edge as well?

We've had several reports of this problem on rstudio.cloud, including some users saying they expiereced the problem on Edge as well as Internet Explorer.

**Comment by kevinushey** [comment]
I think you're correct -- it looks like `window.TextEncoder` is not defined for "old Edge" as well, which was the underlying source of this issue.

https://caniuse.com/#feat=textencoder

So this issue would've affected users on Windows using Internet Explorer or Edge.

Sorry for all the trouble this has caused. :-/
