### ISSUE TITLE
Switching 'RStudio theme' in the Options menu from 'Modern' to 'Sky' or vice versa requires starting a new session for the change to take effect.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#6677]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : Version 1.3.938
    OS Version      : Windows 10 Pro
    R Version       : 4.0.0 alpha

### Steps to reproduce the problem
1. Launch RStudio with default Appearance settings.
2. Select Tools > Global Options > Appearance.
3. Change RStudio theme from 'Classic' to 'Sky' and select Apply.
4. Return to Appearance options and now change RStudio theme from 'Sky' to 'Modern' > select Apply.

### Describe the problem in detail
RStudio theme can be successfully switched from Classic to either Sky or Modern, and back to Classic, within the same session. For some reason attempting to switch between Sky and Modern requires a new session for the changes to take effect.
### Describe the behavior you expected
Users are able to freely switch between all available RStudio themes within the same session.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MariaSemple** [comment]
I think it's expected that switching the RStudio theme (not the editor theme) requires an R session restart to take effect. I'm more surprised that switching from Classic to Sky or Modern _doesn't_ require a restart. I think if we want to change this, it would be an enhancement request rather than a bug.

**Comment by R-Hannibal** [comment]
@MariaSemple Ah ok, thanks for the info. 

Either way this is a pretty minor issue, but I went with bug initially due to the inconsistency between different themes feeling bug-like from an end user's perspective. 

Switching labels now.
