### ISSUE TITLE
Plot saving doesn't work with AGG graphics device backend

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rstudio#6679]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.206
    OS Version      : macOS Mojave 10.14.6
    R Version       : R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem

Set the graphics backend to AGG, then run this code. 

```r
plot(1)
```

Then click on "Export" -> "Save As Image". I see the following error:

<img width="1019" alt="Screen Shot 2020-04-16 at 3 04 15 PM" src="https://user-images.githubusercontent.com/1365941/79501522-cd844680-7ff3-11ea-818f-4662d2b0a953.png">

**Comment by kevinushey** [comment]
Note to self: likely need to update code here.

https://github.com/rstudio/rstudio/blob/8cb57c1f1ddb260d7ed8a08838e4807a2c7b3746/src/cpp/r/session/graphics/RGraphicsPlotManager.cpp#L326-L337

**Comment by petrbouchal** [comment]
Possibly related to plot image also not showing in Plot Zoom window (where the broken-image link shows, as it does in the Save Plot as Image dialog when the resize handle at bottom right is pulled.)

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.812, R Version - 3.6.3, Windows 10 x64 - Desktop 

No error is now being displayed when Exporting/Saving as image a plot that has been previewed in the viewer pane. Was not able to reproduce the original issue as all available dailies now include the fix.
