### ISSUE TITLE
Arrow keys stop functioning in RStudio's source pane

### ISSUE THREAD

**Issue by AGeographer** [rstudio/rstudio#6681]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Windows 10 LTSC
    R Version       : 3.6.3

### Steps to reproduce the problem
In the Source Pane of RStudio Desktop moving the cursor with arrow keys works fine until I switch my keyboard language using the Windows internally set shortcut `Windows + Space`. It doesn't happen when I switch the keyboard language using the mouse.

### Describe the problem in detail
I work in three different languages and frequently switch back and forth, esp. when making ggplot graphs. After using `Windows + Space` the arrow keys stop working. Further, the `Delete` key changes its behaviour to now act in the same way as the `Backspace` key does.
The problem can be resolved by changing to another Windows window (of a different software) that is already open and then switch back to RStudio.

### Describe the behavior you expected
Arrow keys should move the cursor even after switching languages with the Windows shortcut.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@AGeographer Thank you for raising this! I am able to reproduce this in 1.2. It's working in the upcoming 1.3 release. If you'd like to try it out, it's available at https://rstudio.com/products/rstudio/download/preview/ , though note that though fairly stable, they previews are intended for testing purposes.
