### ISSUE TITLE
options set browser get overwritten

### ISSUE THREAD

**Issue by kda-xyt** [rstudio/rstudio#6682]
Hi,
if I change the browser in `.Rprofile` Rstudio seems to overwrite it. Example I have

```
options(browser='C:/Program Files (x86)/Google/Chrome/Application/chrome.exe')
print(.Options$browser)
```

in my browser and on startup I see 
`[1] "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"`

but if I do `print(.Options$browser)` after the start I get
```
> print(.Options$browser)
function (url) 
{
    .Call("rs_browseURL", url)
}
<environment: 0x000002b54117cb48>
```

So Rstudio is overwriting that option. If I run R on it's own, it does not do that.
I see that this was raised here https://community.rstudio.com/t/changing-the-default-web-browser-used-in-rstudio/23653 but I don't see any feature request or bug in the github repo about it.

Would it be possible to stop this overwriting or add a feature to remove it or to show me where it is being done so I change it manually?

I am running on widows 10, R 3.6.3
thank you

**Comment by kevinushey** [comment]
You can set it within an rstudio.sessionInit hook. See:

https://rstudio.github.io/rstudioapi/articles/r-session.html

for an example.
