### ISSUE TITLE
Custom fonts in RStudio Server do not apply to Editor pane

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#6684]
### System details

    RStudio Edition : Server 
    RStudio Version : 1.4.209
    OS Version      : CentOS 7.7
    R Version       : 3.6.1

### Steps to reproduce the problem

Install a custom font into `/etc/rstudio/fonts` and change the font in the global options.

### Describe the problem in detail

The feature introduced in #6592 only works for the console and environment panes. The selected custom font is not honored in the editor pane. There, still "Monaco" is used as the default fallback.

In addition, different weights specified in subfolders following the instructions in the [README](https://github.com/rstudio/rstudio/blob/8cb57c1f1ddb260d7ed8a08838e4807a2c7b3746/src/cpp/server/fonts/README.md) of `/etc/rstudio/fonts` are not honored. Only the top level folder name of a custom font is shown in RStudio. I tried integers and real names for the subfolder names.

### Describe the behavior you expected

The font should also be used in the editor pane.
This applies to all fonts that are available (wherever they might come from).
(In addition (but probably a feature request) ligature support would be neat.)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I can't reproduce this. :-/ Can you share the exact font that you used, and your folder structure in /etc/rstudio/fonts?

**Comment by pat-s** [comment]
I tried https://github.com/tonsky/FiraCode.

Placed it in `~/etc/rstudio/fonts/Fira-Code` and then selected the font.

I see the font getting changed in the Console and Environment after reload but not in the editor.
This also applies to all other selected fonts in the menu (not just the one placed in `~/etc/rstudio/fonts`. Some have high visible differences to the default (Monaco) so its not a false-positive (because Fira Code and Monaco are not that much different).

Tested with Chrome and FF.
I can't show you a screenshot of the available fonts in the RStudio Options menu right now because opening the screenshot tool closes the window that shows all the discovered fonts 😅

**Comment by jmcphers** [comment]
What do you mean by "placed it in"? Can you show your exact folder structure? 

FiraCode should totally work! Here's what it looks like in my build:

![image](https://user-images.githubusercontent.com/470418/79597646-7df75680-8097-11ea-98c6-fbac7fb52e61.png)

And here's my folder structure:

```
/etc/rstudio/fonts
├── Fira Code
│   ├── 300
│   │   └── FiraCode-Light.woff2
│   ├── 400
│   │   └── FiraCode-Regular.woff2
│   ├── 500
│   │   └── FiraCode-Medium.woff2
│   ├── 600
│   │   └── FiraCode-SemiBold.woff2
│   └── 700
│       └── FiraCode-Bold.woff2
```

**Comment by pat-s** [comment]
<img width="1440" alt="Screenshot 2020-04-17 at 20 27 03" src="https://user-images.githubusercontent.com/8430564/79601988-fedf3e00-80e9-11ea-8427-8d89f1a3ee12.png">


```
/etc/rstudio/fonts/
├── Fira-Code
│   ├── 300
│   │   └── FiraCode-Light.woff2
│   ├── 400
│   │   └── FiraCode-Regular.woff2
│   ├── 500
│   │   └── FiraCode-Medium.woff2
│   ├── 600
│   │   └── FiraCode-SemiBold.woff2
│   ├── 700
│   │   └── FiraCode-Bold.woff2
│   └── README.md
└── README.txt
```

**Comment by jmcphers** [comment]
It looks like you've got it all set up correctly (and indeed the preview even works!), so not sure what's going on here!

Just to eliminate a variable: can you try switching to the default RStudio theme? (the theme you're using in that screenshot has a bunch of custom CSS that could be causing trouble)

**Comment by pat-s** [comment]
Yes, the preview works and also the environment and console panes. Only the editor pane does not.

Theme switching to a built-in theme does not help.

**Comment by jmcphers** [comment]
I found a repro for this; it's due to a somewhat subtle difference in environment between my development build and your RStudio Pro install. Should have a fix soon, thanks for reporting!

**Comment by pat-s** [comment]
Thanks Jonathan. Just tested 1.4.2227 and it now works! 🎉
