### ISSUE TITLE
Add global option to disable clickable hyperlinks

### ISSUE THREAD

**Issue by paulkaefer** [rstudio/rstudio#6689]
I frequently save URLs in comments, typically for sites that helped me solve a problem or internal resources (Jira, documentation, other related code, etc.).

I _also_ frequently have a variable set at the top like `local_GitHub_path` or `output_path`. Usually I'm running the code on one OS, but sometimes I switch to a different OS & have to modify these paths. To that effect, I'm often already pressing `shift` or `ctrl` to copy/paste, select part of the path, etc. And I frequently end up accidentally clicking the link, which I don't want.

I'd like to request a global option (that could default to being checked) to allow hyperlinks to be detected & clickable. And unchecking that box would prevent the parser from automatically underlining and making such links clickable.

**Comment by ronblum** [comment]
@paulkaefer Thank you for the suggestion! We'll review at as part of our ongoing development of RStudio.

**Comment by paulkaefer** [comment]
Thanks, @ronblum! With guidance, I'd be interested to take a look at putting in a fix.

**Comment by jmcphers** [comment]
PRs are always appreciated! 

Here are some instructions for adding preferences:

https://github.com/rstudio/rstudio/blob/2072c45fe663420578c8e5759474a8e85860b304/src/gwt/tools/generate-prefs.R#L16-L25

The web link behavior is hooked up here:

https://github.com/rstudio/rstudio/blob/9679854e04ab6b1358e4798250d535ef82b9f9e3/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorBackgroundLinkHighlighter.java#L150

So if you (a) add a pref, and (b) check that pref and avoid inserting the web link highlighter when it's turned off, you should get pretty close.

**Comment by paulkaefer** [comment]
@jmcphers I've been able to update & run `generate-prefs.R`, as you suggested.

I'm unsure how to check the pref in `AceEditorBackgroundLinkHighlighter.java`. Calling the imported `highlightWebLink()` (from the auto-generated [UserPrefsAccessor.java](https://github.com/rstudio/rstudio/blob/2072c45fe663420578c8e5759474a8e85860b304/src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java)) doesn't seem to work. Are there other examples of Java code using user preference boolean values? I'm struggling to find them.

Apologies if these are beginner questions... it's been a while since I've touched Java!

**Comment by jmcphers** [comment]
Yes, it's a little confusing! The accessor itself is just a lookup layer; it needs preferences behind it to function. Look in the code for `Provider<UserPrefs>` to find examples of what you want to do.

Once you have it hooked up to a pref, you will want to toggle the pref to see if it's working. Here are a couple of pointers there:

1. You can use `rstudioapi::writeRStudioPreference()` to change preferences before you have UI hooked up.
2. Preferences have a `bind()` method you can use to subscribe to preference changes. That will give you a place to inject and/or remove the highlighter when the preference changes. (If you don't do this then a full reload will be required to apply the preference.)
3. Once everything is working smoothly, you can add some UI for toggling your preference. Start here: https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java

**Comment by paulkaefer** [comment]
Good news, @jmcphers! I got the preference created & have a checkbox in the `Global Options` in my local build:

![Screen Shot 2020-05-12 at 16 15 39](https://user-images.githubusercontent.com/2408155/81746963-eeae4a80-946c-11ea-9565-41354ce176ed.png)

I'm struggling to find the `bind()` method... can you point me to where those reside? Perhaps the example for `continueCommentsOnNewline()`?

**Comment by jmcphers** [comment]
Nicely done!

The `bind()` is a method on a preference that allows you to attach an event handler to be called when its value changes. Here is an example:

https://github.com/rstudio/rstudio/blob/2cd1b38201914c81218938f72ab4ad6d81215436/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L905-L919

**Comment by paulkaefer** [comment]
@jmcphers, here are my changes thus far: https://github.com/paulkaefer/rstudio/commit/a8f84cb9aa09cbb77caea7501fb3516f44813b6e.

The `.bind()` method I added [here](https://github.com/paulkaefer/rstudio/blob/a8f84cb9aa09cbb77caea7501fb3516f44813b6e/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L7019-L7023) looks to match other such cases (events), but gives me this when I run the `sudo make install`:

```
    [javac] Compiling 2 source files to /home/ubuntu/GitHub/rstudio/src/gwt/bin
    [javac] /home/ubuntu/GitHub/rstudio/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java:7022: error: cannot find symbol
    [javac]                   docDisplay.setHighlightWebLink(arg);
    [javac]                             ^
    [javac]   symbol:   method setHighlightWebLink(Boolean)
    [javac]   location: variable docDisplay of type DocDisplay
    [javac] 1 error
```
I'm confused, as the `setHighlightWebLink` method exists just like the `showIndentGuides` method does in [src/cpp/session/include/session/prefs/UserPrefValues.hpp](https://github.com/paulkaefer/rstudio/blob/a8f84cb9aa09cbb77caea7501fb3516f44813b6e/src/cpp/session/include/session/prefs/UserPrefValues.hpp).

Am I on the right track? Like I said above, when I built this without touching `src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java`, I was able to get the toggle to work (but it would only work once, not on a re-toggle, hence the need for the `.bind()` method).

**Comment by jmcphers** [comment]
Yep, you're on the right track! The `setHighlightWebLink` method needs to be invoked on a UserPrefs object, not docDisplay.

**Comment by paulkaefer** [comment]
Just wanted to leave a comment that I'm still tinkering with this & feel optimistic that it's close. It didn't quite seem as straightforward as I thought from the previous comment, but I will play around with it a little more before asking for help again.

**Comment by paulkaefer** [comment]
@jmcphers Okay, this compiles, and the setting works. Is there something else I need to add? It still seems to only change the first time I open the system preferences & make a change. It does remember the setting across sessions, though, so that's a good sign.

[My changes](https://github.com/rstudio/rstudio/compare/master...paulkaefer:master) -- let me know if this is ready for a PR, or what I could add.

**Comment by jmcphers** [comment]
You're almost there!

```java
        releaseOnDismiss.add(prefs_.highlightWebLink().bind(
            new CommandWithArg<Boolean>() {
               public void execute(Boolean arg) {
                  prefs_.highlightWebLink().setGlobalValue(arg);
                  prefs_.writeUserPrefs();
               }}));
```

This bit should be removed; it is responding to a change in the preference value by setting the preference value (so the whole thing is effectively a no-op).

You should instead move this code to AceEditorBackgroundLinkHighlighter.java, where you can (in the body of the CommandWithArg) add or remove the webLinkHighlighter when the value changes. 

`UserPrefs` doesn't need to be static (revert that change)

**Comment by paulkaefer** [comment]
@jmcphers sorry for the delay! I think 81942b6 fixes what you last mentioned. Let me know what you think / if I should open a PR.

**Comment by jmcphers** [comment]
Looks like you're ready to open a PR!
