### ISSUE TITLE
Only first line of URL overflowing in Terminal highlights when hovering

### ISSUE THREAD

**Issue by stragu** [rstudio/rstudio#6691]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.3

### Steps to reproduce the problem
Execute a command that has a URL as an output in a terminal that is small enough / zoomed in enough to have the URL overflow one line.
For example, run the following code:

`echo https://github.com/rstudio/rstudio/issues/new?template=bug_report.md`

### Describe the problem in detail
Hovering over the URL only highlights the first line, and clicking it therefore leads to nowhere.

![image](https://user-images.githubusercontent.com/1747497/79940573-78d64500-84a5-11ea-9837-e6ae838e1169.png)

### Describe the behavior you expected
The whole URL should be recognised and be highlighted, just like in the source pane.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
## Background
RStudio uses xterm.js (https://github.com/xtermjs/xterm.js/) as its terminal emulator, and is provides the hyperlink functionality.

For RStudio 1.1 and 1.2, we used xterm.js version 2, and what you are seeing here is (likely) an issue with xterm2. For RStudio 1.3, upgraded to xterm.js v3, and unfortunately lost this feature in the process (#6621). Too late for fix that for 1.3, unfortunately, but will look at fixing it in RStudio 1.4.

**Comment by stragu** [comment]
Do you expect the multi-line issue described here to still be there once #6621 is fixed? If not, we might as well close this.

**Comment by gtritchie** [comment]
I need to check if this is actually an xterm.js issue versus something about how I incorporated it into RStudio, so will leave it open for now.

**Comment by stragu** [comment]
Hi @gtritchie , happy to report that this is fixed, as I just tested in 1.4.1103 !

Cheers :+1:
