### ISSUE TITLE
Add option to choose custom data separator when importing CSV dataset

### ISSUE THREAD

**Issue by SoptikHa2** [rstudio/rstudio#6695]
Hi,
when I create datasets, I often use non-standard separators, simply because I don't want to use a complex program/script that would properly quote values inside CSV file as data itself might contain (and do) characters like `', ;"`. So I just use some ridiculous character like `🦄` that I know that doesn't appear in the dataset so I don't have to think about all the things this could broke.

However, R studio lacks a way to specify custom separator while importing a dataset. Is there an easy way to add the feature?

Thanks

<small>Using RStudio 1.2.5033</small>

![image](https://user-images.githubusercontent.com/24734779/79699135-fa975a00-827c-11ea-9539-6979dc8e9cf2.png)

**Comment by ronblum** [comment]
@SoptikHa2 The other option for CSV files, "From text (readr)", has an "Other" option for custom delimiters. Does that do what want it to do?

**Comment by SoptikHa2** [comment]
That seems to be it, thanks! Sorry for requesting already implemented feature.
