### ISSUE TITLE
Console jumps when scrolling through old commands and a command is longer than the console width

### ISSUE THREAD

**Issue by thomasp85** [rstudio/rstudio#6697]
## Steps to reproduce
Write a command that takes up more space than the width of the console, and execute it. execute some shorter calls as well. When going through the call history with the arrow keys the console will jump in scroll position when the long command appears. If the console is resized so the long call can fit in one line the problem goes away

This is on RStudio Desktop 1.3.938 on Mac

**Comment by GegznaV** [comment]
I faced a similar issue on Windows 10 with RStudio Desktop 1.3.944-1. I cannot tell exactly how to reproduce it, but while browsing previous commands in R console with arrow button <kbd>↑</kbd> sometimes command from history appear as expected but sometimes console window gets automatically scrolled and the bottom lines with the commands of interest get out of the view. It is really inconvenient.

Possibly related: #6703

**Comment by lorenzwalthert** [comment]
I face exactly the same problematic behaviour as Thomas with same version number and OS. I tried the current RStudio stable release (v1.2.5042) and the problem does not occur, so it's a regression introduced in the preview release. One is not so likely to type such long commands manually, but rather c/p from the source panel or highlighting and Cmd + Enter. I agree with @GegznaV that this is really inconvenient.

**Comment by lorenzwalthert** [comment]
The issue persists with the latest available preview release (v1.3.947).
