### ISSUE TITLE
Support Report style headers in document outline for R script

### ISSUE THREAD

**Issue by BrianDiggs** [rstudio/rstudio#6698]
# Summary

I would like the RStudio IDE to recognize an additional format of sections when editing an R Script file. Currently, it recognizes

```
# Level 1 -----------------------------------------------------------------
```

I would like it to also recognize the format which is used by the "Compile Report" button (via `rmarkdown::render`):

```
#' # Level 1
```

# Details

I am writing R Scripts files using the notation that embeds the markdown formatting in roxygen style comments per https://rmarkdown.rstudio.com/articles_report_from_r_script.html. This includes being able to specify headers/sections using the standard markdown notation of leading hashes. However, one drawback to this approach is that the code editors does not support document navigation using either the "Document Outline" pane nor the section navigator on the status line (not sure I am using the right terminology for this; the pop-up that has "(Top Level)" and any other headings that you can select to jump to, or that updates as you move between sections). For an R Markdown file, the headers (`#`, `##`, etc.) are listed there.

This request may depend on Issue #4124. This requested format supports hierarchical/nested sections which is the subject of that issue.

**Comment by ronblum** [comment]
@BrianDiggs Thank you for the suggestion! We'll review it as we continue development of RStudio.
