### ISSUE TITLE
error: no member named 'get_io_service' in 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp, boost::asio::executor>'          pConnectionTimer_.reset(new boost::asio::deadline_timer(resolver_.get_io_service(), timeout));

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#6702]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : FreeBSD 12.1
    R Version       : 3.6.3

### Steps to reproduce the problem
Build

### Describe the problem in detail
```
/usr/ports/devel/RStudio/work/rstudio-1.2.5042/src/cpp/core/include/core/http/TcpIpAsyncConnector.hpp:80:76: error: no member named 'get_io_service' in 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp, boost::asio::executor>'
         pConnectionTimer_.reset(new boost::asio::deadline_timer(resolver_.get_io_service(), timeout));
                                                                 ~~~~~~~~~ ^
```
boost-libs-1.72.0_1

The error looks similar to https://github.com/rstudio/rstudio/issues/4636

**Comment by ronblum** [comment]
@yurivict Have you by chance tried the recent 1.3 (Middlemist Red) preview? #4636 should be fixed in it. The preview is available at 
[the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/) (Note that preview builds are intended for testing purposes only.)

**Comment by yurivict** [comment]
> Have you by chance tried the recent 1.3 (Middlemist Red) preview?

I got the error while trying to update the port, so the preview wouldn't work for me.

Any chance to back-port the fix into the branch where releases are made?

**Comment by yurivict** [comment]
Do you know which commit fixed this issue? I can also back-port a commit it it applies to the last release.

**Comment by kevinushey** [comment]
I believe this was fixed via https://github.com/rstudio/rstudio/commit/33c2c42d40ad97d97ca3907df51059cd2ce76fe3#diff-b6bf863118ea1d6aa369536e7ed0e392.

**Comment by yurivict** [comment]
The above patch worked, thanks for pasting it.

**Comment by gtritchie** [comment]
Closing this; appears a solution was provided and we won't be back-porting this to the 1.2 release branch.
