### ISSUE TITLE
Console scrolls on paste

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#6703]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.3.944-1
    OS Version      : Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem

Possibly related issue. Steps to reproduce:

1) Clear console.
2) Make it small enough.
![image](https://user-images.githubusercontent.com/12725868/79906573-b775ec00-8420-11ea-97c9-55de744f939d.png)
3) Run command that result does not fit in the console, e.g.,
```r
head(iris, n = 20)
```
The console looks like this:
![image](https://user-images.githubusercontent.com/12725868/79907107-bc876b00-8421-11ea-98c2-ce394fd99855.png)
The red arrow indicates the scrollbar position.
4) Place the cursor to position 1 (red dot in the fig. above) and paste (<kbd>Ctrl+V</kbd>) a piece of code that does not fit to one line in the current view, e.g.:
```r
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
5) The console automatically scrolls and the pasted code gets out of view (red line shows scrollbar position):
![image](https://user-images.githubusercontent.com/12725868/79907277-02dcca00-8422-11ea-9d45-4d5f38d70ce0.png)

### Describe the problem in detail

Console inadequately scrolls and the lines of interest get out of view.

### Describe the behavior you expected

 No automatic scrolling on paste.

Possibly related:  #6697

**Comment by ronblum** [comment]
@kevinushey Can this also be related to #6553?

**Comment by kevinushey** [comment]
@ronblum I believe so; at least, it's definitely in the same family of issues.
