### ISSUE TITLE
Two blinking coursors: in both console and editor

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#6704]
### System details

    RStudio Edition : Desktop or Server 
    RStudio Version : 1.3.944-1
    OS Version      : Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem

1) Put the cursor at the end of the current line in the console.
2) Put the cursor in source editor, e.g., line 296 in the example below.
3) Then move focus to some other non-RStudio Window. E.g., click somewhere on the web browser if it is open.
4) Put the cursor at the same place in the console as it was before.
5) Now two blinking cursors should be visible.

I'm not sure if it 100% reproducible.

### Describe the problem in detail

Two blinking cursors are visible and only one is active. It is really distracting.

![RS-two-coursors](https://user-images.githubusercontent.com/12725868/79908872-acbd5600-8424-11ea-85f1-d971e2206af3.gif)

### Describe the behavior you expected

The cursor should blink either in console or in source editor but not in both.

Is there any chance that this issue and rstudio/rstudioapi#175 are related?

**Comment by kevinushey** [comment]
Thanks -- I can reproduce this as well. For me, clicking out side of the RStudio window and then clicking back in (alternating between Console and Source) is enough to get into a state where both are blinking.

**Comment by GegznaV** [comment]
I cannot reproduce this in RStudio 1.4.1103. So it seems to be solved.
