### ISSUE TITLE
Database files stored in `/var/run`

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6706]
### System details

    RStudio Edition : Server
    RStudio Version :  1.4.221

### Steps to reproduce the problem

1. Start RStudio server.
2. Look in `/var/run/rstudio-server`.

### Describe the problem in detail

RStudio's database is stored there, in `rstudio.sqlite`. 

https://github.com/rstudio/rstudio/blob/e0f24229233f3dddba00d854e2487d4e366dfc4e/src/cpp/server_core/ServerDatabase.cpp#L42

This probably isn't where we want it because `/var/run` is intended to store ephemeral data that does not survive reboots.

> Files under this directory must be cleared (removed or truncated as appropriate) at the beginning of the boot process.

http://www.pathname.com/fhs/pub/fhs-2.3.html#VARRUNRUNTIMEVARIABLEDATA

### Describe the behavior you expected

Because this database stores state that is meant to survive reboots, it should be stored somewhere else. We might consider `/var/lib` where we already store e.g. nginx conf, or respecting `XDG_DATA_DIRS`.

**Comment by rich-rstudio** [comment]
verified on 1.4.1066-2
