### ISSUE TITLE
AWS CLI permissions (via IAM) failing inside RStudio Server terminal

### ISSUE THREAD

**Issue by mjsteinbaugh** [rstudio/rstudio#6707]
### System details

    RStudio Edition : Server Pro
    RStudio Version : 1.2.5042-1
    OS Version      : Ubuntu 18 LTS
    R Version       : 3.6.3

### Steps to reproduce the problem

On a machine with AWS CLI permissions managed with IAM:

Open new terminal session inside RStudio.

Attempt to list buckets, for example.

```sh
aws s3 ls
```

```
An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records. 
```

### Describe the problem in detail

I see permission errors for any type of AWS CLI command involving S3 buckets.

Also, I can reproduce this issue on other machines running standard RStudio Server (the non-Pro edition).

### Describe the behavior you expected

AWS CLI should be correctly authenticated without a key inside RStudio Server terminal. Loading up a shell session directly outside of RStudio Server terminal has no issues.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mjsteinbaugh** [comment]
And here is the version of AWS CLI installed:

```sh
aws --version
```

```
aws-cli/2.0.8 Python/3.7.3 Linux/4.15.0-1065-aws botocore/2.0.0dev12
```

**Comment by kevinushey** [comment]
Following the documentation here:

https://aws.amazon.com/premiumsupport/knowledge-center/access-key-does-not-exist/

Do those commands produce different output in a regular terminal vs. RStudio's terminal?

Odds are there are some environment variables that need to be set (or unset) to get this working.

**Comment by mjsteinbaugh** [comment]
`aws configure list` was extremely helpful thanks. I had an AWS token set in my shell configuration that was sourced specifically inside R, as I suspected and that was messing up the IAM configuration. Thanks for your help.
