### ISSUE TITLE
Store system persistent state in XDG_DATA_DIRS instead of /var/lib

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6715]
RStudio Server currently stores most system persistent state and data in `/var/lib`.

https://github.com/rstudio/rstudio/blob/b824a9179dcbba9e89c76b41e4837738c23acf6b/package/linux/debian-control/postinst.in#L46-L49

https://github.com/rstudio/rstudio/blob/b34b0236d71aee6a9833338ffae68d2f49048f51/src/cpp/server/ServerOptions.cpp#L194-L196

etc., etc. 

RStudio Server Pro stores many more elements there, including logs, nginx configuration, etc. 

This directory is not customizable or XDG-compliant, but it should be. XDG has an `XDG_DATA_DIRS` variable which is used to indicate the directory to store system-wide data. Just as we now respect `XDG_CONFIG_DIRS` as a list of directories from which to read system-wide configuration, we should respect `XDG_DATA_DIRS` as a list of directories from which to read and write system-wide data.

This is not currently high priority because while requests for loading configuration from alternate locations are common, we have few if any requests for storing data somewhere other than `/var/lib`.

**Comment by natestemen** [comment]
Would very much appreciate this. Is there any workaround for the time being so that `.rstudio_desktop` can be moved out of my home dir? What would be the repercussions to deleting it?

**Comment by jmcphers** [comment]
That part is already implemented in RStudio 1.4. Just set the `XDG_DATA_HOME` and `XDG_CONFIG_HOME` variables to the directories you want to use. (Note that they need to be set for RStudio itself, not just for the R session).

If you delete `.rstudio-desktop` you will effectively be doing a factory reset on RStudio 1.2 and prior as they store everything in that folder.

**Comment by natestemen** [comment]
Ah okay I understand. What will the folders be called in those respective dirs? Is it possible to move stuff from `~/.rstudio-desktop` to those? there's quite a lot of stuff in here, so I'm not sure where each piece should go.

```bash
$ ls ~/.rstudio-desktop
addin_registry       explorer-cache       pcs                  saved_source_markers
client-state         history_database     presentation         sessions
console06            log                  profiles-cache       sources
ctx                  monitored            projects_settings    viewer-cache
dictionaries         notebooks            rmd-outputs
```

**Comment by jmcphers** [comment]
You don't need to move anything yourself. RStudio 1.4 will do the migration necessary.

Generally it will migrate your user preferences to `~/.config/rstudio/rstudio-prefs.json`. Everything else above will get moved to `~/.local/share/rstudio/`.
