### ISSUE TITLE
Theme does not apply to all panels in debian 9

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#6717]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Linux 4.9.0-12-amd64 Debian 4.9.210-1 x86_64
    R Version       :  3.6.3

### Steps to reproduce the problem
Change the editor theme (to any theme) in Appearance and Apply.

### Describe the problem in detail
Editor theme only applies to Console and Source panels.
![rstudio_window](https://user-images.githubusercontent.com/40892925/80081065-bf35ad80-8552-11ea-9e6d-7da9eee69577.png)

### Describe the behavior you expected
It seems (https://support.rstudio.com/hc/en-us/articles/115011846747-Using-RStudio-Themes) it should apply to all panels.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Thank you!

**Comment by jmcphers** [comment]
The Classic theme does not have a dark version. If you switch to Modern you should see what you expect!

https://support.rstudio.com/hc/en-us/articles/115011846747-Using-RStudio-Themes
