### ISSUE TITLE
Support for Ubuntu/focal 20.04 (resolved: PEBKAC)

### ISSUE THREAD

**Issue by satmandu** [rstudio/rstudio#6723]
Now that Focal is out, could we get a ```Dockerfile.focal-amd64``` setup, even for rstudio 1.4 builds?

I'm not sure that we need to have a section adding a ```deb http://cran.rstudio.com/bin/linux/ubuntu bionic-cran35``` source since 3.6.3 is in the focal repositories already. (I'd imagine there will be a ```focal-cran40``` at some point since R 4.0.0 comes out tomorrow.)

**Comment by jmcphers** [comment]
Can you explain a little more why this would be useful? The binaries we build on Bionic should work on Focal.

**Comment by satmandu** [comment]
I'm having problems with the bionic binaries not working either on a focal booted machine or in my ChromeOS focal container, (maybe due to recent glibc changes?) and I figured the easiest way to troubleshoot it would be to try to build a focal targeted binary.

But retargeting the Dockerfile to focal isn't working for me, so I figured I'd see if punt to see if this is already something someone has put time into.

**Comment by kevinushey** [comment]
FWIW, the Bionic builds of RStudio work fine on Focal for me as well.

(We might want to update the daily build page to advertise the Bionic builds rather than Xenial, though -- the "Ubuntu" button there still points at Xenial.)

**Comment by jmcphers** [comment]
@satmandu  

> I'm having problems with the bionic binaries not working

Can you be more specific about what errors you're seeing?

**Comment by satmandu** [comment]
I try to import a xls file, it does an install, and then I start getting these errors:
```
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
```

**Comment by gtritchie** [comment]
`syscall 0230` is almost certainly the same thing described here: #6379

Have you tried a very recent 1.4 daily build? Note that these can be **quite unstable at this time so not suitable for regular use**, but we recently updated Qt in 1.4 specifically to fix this problem on newer Linux distros, and after 1.3 is released we will be making a 1.3 patch release with this fix, as well.

Daily builds here: https://dailies.rstudio.com/

**Comment by satmandu** [comment]
I wasn't able to get 1.4 to work. I had the same error.

I did manage to get a build of 1.3 working with qt 5 though on focal. 

```
diff '--exclude=.git' -Npaur a/docker/jenkins/Dockerfile.focal-amd64 b/docker/jenkins/Dockerfile.focal-amd64
--- a/docker/jenkins/Dockerfile.focal-amd64	1969-12-31 19:00:00.000000000 -0500
+++ b/docker/jenkins/Dockerfile.focal-amd64	2020-04-24 19:09:34.764504281 -0400
@@ -0,0 +1,112 @@
+FROM ubuntu:focal
+
+ARG AWS_REGION=us-east-1
+
+# install needed packages. replace httpredir apt source with cloudfront
+RUN set -x \
+    && sed -i "s/archive.ubuntu.com/$AWS_REGION.ec2.archive.ubuntu.com/" /etc/apt/sources.list \
+    && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get update \
+    && apt-get install -y gnupg \
+    && apt-get update
+#    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 39A90F2E6D5DCC5DFB39462B67C2D66C4B1D4339 \
+#    && echo 'deb http://ppa.launchpad.net/edd/r-3.5/ubuntu focal main' >> /etc/apt/sources.list \
+    #&& apt-get update
+
+# add ppa repository so we can install java 8 (not in any official repo for bionic)
+RUN apt-get update \
+  && apt-get install -y software-properties-common \
+  && add-apt-repository ppa:openjdk-r/ppa
+
+RUN apt-get update && \
+    export DEBIAN_FRONTEND=noninteractive && \
+    apt-get install -y \
+    ant \
+    autoconf \
+    build-essential \
+    clang \
+    curl \
+    debsigs \
+    dpkg-sig \
+    expect \
+    fakeroot \
+    git-core \
+    libattr1-dev \
+    libacl1-dev \
+    libbz2-dev \
+    libcap-dev \
+    libcurl4-openssl-dev \
+    libfuse2 \
+    libgpg-error0 \
+    libgtk-3-0 \
+    libgl1-mesa-dev \
+    libegl1-mesa \
+    libpam-dev \
+    libpango1.0-dev \
+    libuser1-dev \
+    libssl-dev \
+    libxslt1-dev \
+    lsof \
+    openjdk-8-jdk \
+    patchelf \
+    p7zip-full \
+    pkg-config \
+    python \
+    r-base \
+    sudo \
+    unzip \
+    uuid-dev \
+    valgrind \
+    wget \
+    yarnpkg \
+    zlib1g-dev
+
+# ensure we use the java 8 compiler
+RUN update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
+
+## build patchelf
+#RUN cd /tmp \
+#    && wget https://github.com/NixOS/patchelf/archive/0.10.tar.gz \
+#    && mv 0.10.tar.gz patchelf-0.10.tar.gz \
+#    && tar xzvf patchelf-0.10.tar.gz \
+#    && cd patchelf-0.10 \
+#    && ./bootstrap.sh \
+#    && ./configure \
+#    && make \
+#    && make install
+
+## run install-boost twice - boost exits 1 even though it has installed good enough for our uses.
+## https://github.com/rstudio/rstudio/blob/master/vagrant/provision-primary-user.sh#L12-L15
+COPY dependencies/common/install-boost /tmp/
+RUN bash /tmp/install-boost || bash /tmp/install-boost
+
+# set github login from build argument if defined
+ARG GITHUB_LOGIN
+ENV RSTUDIO_GITHUB_LOGIN=$GITHUB_LOGIN
+
+# install cmake
+COPY package/linux/install-dependencies /tmp/
+RUN /bin/bash /tmp/install-dependencies
+
+# install crashpad and its dependencies
+COPY dependencies/common/install-crashpad /tmp/
+RUN bash /tmp/install-crashpad bionic
+
+# install common dependencies
+RUN mkdir -p /opt/rstudio-tools/dependencies/common
+COPY dependencies/common/ /opt/rstudio-tools/dependencies/common/
+RUN cd /opt/rstudio-tools/dependencies/common && /bin/bash ./install-common
+
+# install Qt SDK
+COPY dependencies/common/install-qt.sh /tmp/
+COPY dependencies/linux/install-qt-linux /tmp/
+RUN export QT_VERSION=5.14.2 && \
+    cd /tmp && /bin/bash ./install-qt-linux
+
+# create jenkins user, make sudo. try to keep this toward the bottom for less cache busting
+ARG JENKINS_GID=999
+ARG JENKINS_UID=999
+RUN groupadd -g $JENKINS_GID jenkins && \
+    useradd -m -d /var/lib/jenkins -u $JENKINS_UID -g jenkins jenkins && \
+    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
+
diff '--exclude=.git' -Npaur a/src/cpp/desktop/CMakeLists.txt b/src/cpp/desktop/CMakeLists.txt
--- a/src/cpp/desktop/CMakeLists.txt	2020-04-24 19:10:33.142975086 -0400
+++ b/src/cpp/desktop/CMakeLists.txt	2020-04-24 15:35:56.236767540 -0400
@@ -38,7 +38,7 @@ if(NOT WIN32)
       if(APPLE)
          set(QT_CANDIDATES 5.12.8)
       else()
-         set(QT_CANDIDATES 5.12.8 5.10.1)
+         set(QT_CANDIDATES 5.14.2 5.12.8 5.10.1)
       endif()
 
       # find the newest installed Qt version among the versions we build
diff '--exclude=.git' -Npaur a/src/cpp/desktop/install/LinuxInstallQt.sh.in b/src/cpp/desktop/install/LinuxInstallQt.sh.in
--- a/src/cpp/desktop/install/LinuxInstallQt.sh.in	2020-04-24 19:10:33.150975401 -0400
+++ b/src/cpp/desktop/install/LinuxInstallQt.sh.in	2020-04-24 16:59:06.355996032 -0400
@@ -17,6 +17,7 @@ COMPONENTS=(
 	lib/libQt5Positioning.so.5
 	lib/libQt5PrintSupport.so.5
 	lib/libQt5Qml.so.5
+        lib/libQt5QmlModels.so.5
 	lib/libQt5Quick.so.5
 	lib/libQt5QuickWidgets.so.5
 	lib/libQt5Sensors.so.5
diff '--exclude=.git' -Npaur a/src/cpp/r/session/REmbeddedPosix.cpp b/src/cpp/r/session/REmbeddedPosix.cpp
--- a/src/cpp/r/session/REmbeddedPosix.cpp	2020-04-24 19:10:33.182976661 -0400
+++ b/src/cpp/r/session/REmbeddedPosix.cpp	2020-04-23 17:04:37.050171557 -0400
@@ -13,6 +13,8 @@
  *
  */
 
+#include <Rversion.h>
+
 #include <r/RExec.hpp>
 
 #include <shared_core/FilePath.hpp>
@@ -104,7 +106,11 @@ void runEmbeddedR(const core::FilePath&
    structRstart rp;
    Rstart Rp = &rp;
    R_DefParams(Rp) ;
-   Rp->R_Slave = FALSE ;
+#if R_VERSION < R_Version(4, 0, 0)
+   Rp->R_Slave = FALSE;
+#else
+   Rp->R_NoEcho = FALSE;
+#endif
    Rp->R_Quiet = quiet ? TRUE : FALSE;
    Rp->R_Interactive = TRUE ;
    Rp->SaveAction = defaultSaveAction ;

```

**Comment by satmandu** [comment]
FYI here's my cmdline debug output from 
[rstudio_out.txt](https://github.com/rstudio/rstudio/files/4532057/rstudio_out.txt)
[rstudio_debug_output.txt](https://github.com/rstudio/rstudio/files/4532058/rstudio_debug_output.txt)
```QT_DEBUG_PLUGINS=1 rstudio 2>rstudio_debug_output.txt``` and  ```rstudio 2>rstudio_out.txt```

**Comment by gtritchie** [comment]
@satmandu I see you did a build with Qt 5.14.2; Qt 5.12.8 is supposed to have the same glibc-related fix as 5.14.2, and we have updated `master` branch and the `v1.3-patch` branch to use it instead of 5.12.6.

You said an RStudio daily build exhibited the same problem? Can you confirm that build was using Qt 5.12.8 and not 5.12.6? Can be seen in the Help / About dialog.

**Comment by gtritchie** [comment]
I still can't reproduce this problem on Ubuntu Focal, even with RStudio 1.2.5042; starting with a cleanly installed 20.04 VM (plus all updates), then doing the following:

```
apt update
apt install gdebi-core
apt install r-base r-base-dev
wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5042-amd64.deb
gdebi https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5042-amd64.deb
```

After that tried a variety of operations in RStudio, including importing an Excel file, and haven't hit the problem.

So there's some other variable happening here...

**Comment by satmandu** [comment]
@gtritchie Major mea culpa here. I was testing rstudio on other machines over ssh, which wasn't working since I was having opengl forwarding issues. (This is resolved now since I've installed [virtualgl](https://www.virtualgl.org/), which appears to work splendidly.)

I still need to figure out why I'm getting this error on my crostini setup, but that's on the backburner at the moment.

**Comment by satmandu** [comment]
(To be clear, rstudio 1.2 is working fine on two focal machines now.)

**Comment by satmandu** [comment]
This might be related to my installation of R 4.0.

See what happens when you install this ppa  on focal: https://launchpad.net/~edd/+archive/ubuntu/r-4.0

**Comment by gtritchie** [comment]
I'm going to resolve this as "no-repro", just because the original reported issue (running RStudio on Focal) turned out not to be the problem.

We made some R 4.0 fixes recently in RStudio 1.2 and released 1.2.5042 with those fixes. If you still see a problem with that version, then go ahead and file a new issue. Thanks!

**Comment by satmandu** [comment]
@gtritchie I can confirm that the 1.2.5042 works just fine with R 4.0 on focal. Sorry again to bother everyone.

Interestingly, the 1.4 nightly ```rstudio-1.4.255-amd64.deb```, which _does appear to use Qt 5.12.8,_ still gives me that chromium error with R 4.0, whereas 1.2.5042 does not with R 4.0:
```../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230```

**Comment by gtritchie** [comment]
> Interestingly, the 1.4 nightly rstudio-1.4.255-amd64.deb, which does appear to use Qt 5.12.8, still gives me that chromium error with R 4.0, whereas 1.2.5042 does not with R 4.0

That is unexpected, I'll have to try and see if I can repro!

**Comment by gtritchie** [comment]
We have determined we will not need to produce a Focal-specific build, but there is a problem with the current 1.4 Bionic builds. This is being tracked in #6782.

**Comment by satmandu** [comment]
> We have determined we will not need to produce a Focal-specific build, but there is a problem with the current 1.4 Bionic builds. This is being tracked in #6782.

Fantastic. FYI I'm running focal based self-compiled v1.3-patch builds w/  Qt 5.15 RC using this script https://gist.github.com/satmandu/a450a6a97259f8fd5597ccdf351023ea and am not having any of the chromium errors at all. (I don't know if it helps that 5.15 uses a Chromium M80 based browser inside.)

**Comment by gtritchie** [comment]
The Bionic build should now be fine on Focal, starting with daily build 1.4.325. 1.3-patch build still a ways off but will also contain this fix.
