### ISSUE TITLE
double-clicking window pane min/max buttons causes blank panes

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6724]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : repros in 1.1, 1.2, and 1.3
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- open IDE in typical 4-pane configuration (including opening a file in the editor)
- double-click on the editor's maximize widget (shown in image below)

<img width="1144" alt="screenshot of IDE with 4 panes, highlighting editor's maximize widget" src="https://user-images.githubusercontent.com/10569626/80170726-7e16bb00-859d-11ea-941b-80e333efc5da.png">

### Describe the problem in detail
- after some panes "swooshing around", end up with a blank console panel

<img width="1145" alt="screenshot of IDE with blank console panel region" src="https://user-images.githubusercontent.com/10569626/80170778-a0a8d400-859d-11ea-967d-ab90ffe95a79.png">

### Describe the behavior you expected
- either ignore double-clicks, OR have them do the same thing as a single-click
- note there are other misbehaving variations; try double-clicking on the minimize/restore/maximize of any of the panes

**Comment by dfalty** [comment]
Verified double click does not cause the weird empty panel on version 1.4.874.
