### ISSUE TITLE
Make Remote link clickable in git pane

### ISSUE THREAD

**Issue by akgold** [rstudio/rstudio#6729]
After pushing a new branch to a remote in the git pane, it pops up with a link to make a merge request (at least for github). It'd be great if this link were clickable. Screenshot below. 

![image](https://user-images.githubusercontent.com/394930/80239137-ad750880-862d-11ea-8f8d-084929f3ae5d.png)

**Comment by gtritchie** [comment]
This pane is using the shared Console code, see also: #1941 and #2530
