### ISSUE TITLE
path autocompletion from project directory

### ISSUE THREAD

**Issue by dleopold** [rstudio/rstudio#6731]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5042
    OS Version      : Pop!_OS 19.10
    R Version       :  R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem

Create a project folder and an associated Rproject.
Create a subdirectory with an Rmarkdown file in it.
Set knit directory of rmarkdown file "Knit Directory" to"Project Directory"
Attempt to use path auto completion within a code chunk
Path autocomplete continues to default to the subfolder where the rmarkdown document resides, not the project folder.  

### Describe the problem in detail

Many people, myself included, organize project folder such that Rmarkdown files reside in a project subfolder. In order to use path completion in these Rmarkdown files I need the paths to be relative to the project folder, not the subfolder where the Rmarkdown file resides. However, I can not seem to make this happen. I understand that I can make the paths relative to the project folder when they are knit by setting the "Knit Directory". However, this does not change the behavior of path auto completion, making it very inconvenient to use (this has been preventing me from adopting an Rmarkdown or Rnotebook workflow for some time now). 

This problem has been discussed before, eg #4526. Howver, the issue was closed though the issue does not appear to be solved (ie, the behavior of path auto completion does not change after changing the knit directory). 

### Describe the behavior you expected

Setting knit directory for Rmarkdown files to the project directory should also set path auto completion to be relative to the project directory.

- [ X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/5412.
