### ISSUE TITLE
custom zoom value 

### ISSUE THREAD

**Issue by andresmorago** [rstudio/rstudio#6732]
Hello
Is it possible to have a custom zoom value under Global options > apperance ?
Im currently working at 75% but would like something between this value and 50% (which its already too little)

![Untitled](https://user-images.githubusercontent.com/13720514/80259400-1c148f00-864b-11ea-8d78-127fb1787871.jpg)

**Comment by EmanueleCagliero** [comment]
I have that issue too. 50% zoom too small, 75% too large.
A 67% zoom would probably be better.
I work on a 14'' laptop by HP.
I patched the problem using 50% zoom and "Editor font size" = 12 (instead of 10 under Tools/Global Options/Appearance).
