### ISSUE TITLE
Windows builds take too long (3 hours)

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6734]
Windows builds are currently taking almost 3 hours to run, which makes it (by far) the slowest build platform; for comparison, builds for *every Linux desktop and server platform* take about 20 minutes *total*. We could dramatically reduce our build turnaround times by making the Windows builds faster. Here's a recent log:

https://buildmaster.rstudioservices.com/job/IDE/job/windows-v1.4/203/consoleText

Possible candidates for speedup:

1. Reduce pre-build steps. It currently takes 13 minutes from the time the build starts to the time it is actually compiling code. This is largely due to unnecessary re-downloading and sometimes even re-building dependencies like SOCI and Boost. If we could bake these into the Docker image, we wouldn't need to reinstall them on every build, and we'd save on bandwidth too.
2. Change the spot fleet definition so that it requisitions a beefier machine. The Windows builds are run on slow hardware that just takes a long time to compile things, sometimes up to 20 seconds for a single C++ file. 
3. Use parallel/multithreaded compilation.

**Comment by gtritchie** [comment]
See also #2212

**Comment by jmcphers** [comment]
Largely resolved (aside from #2212) since now include Windows builds in the pipeline.
