### ISSUE TITLE
Allow project specific spell checking configuration

### ISSUE THREAD

**Issue by MLNW** [rstudio/rstudio#6736]
When creating RMarkdown documents the online spell checking added in 1.3 is a life saver. The problem is that I need to create documents in various languages. Usually one per project. At the moment it is only possible to configure this spell check on a global basis. It would be awesome if one could configure spell check per project.

**Comment by neuwirthe** [comment]
I would really like this feature also!

**Comment by hadley** [comment]
Me too 😄

**Comment by jjallaire** [comment]
Closed via https://github.com/rstudio/rstudio/commit/12640b4cea23d18292f8852a7067baa98814a835
