### ISSUE TITLE
Turn off "code browser"

### ISSUE THREAD

**Issue by MarcoPortmann** [rstudio/rstudio#6740]
It seems to me that there is no way to disable RStudio from opening a new "code browser" editor window when it runs into an execution error.

When I'm debugging a script, executing exactly one line and encountering an error, I often know pretty much what went wrong. Then I want to stay in the active editor and revise the line. It is only annoying when RStudio opens the code browser for the function in question and shows me its internals. I only lose time because I have to close the code browser and switch back to the desired script.

**Comment by kevinushey** [comment]
See e.g. in the main menu:

<img width="374" alt="Screen Shot 2020-04-27 at 11 03 46 AM" src="https://user-images.githubusercontent.com/1976582/80404933-c6bcc580-8876-11ea-91de-57d0ce549cc5.png">

I suspect you want Debug -> On Error -> Message Only or similar.

**Comment by MarcoPortmann** [comment]
Thanks for the advice. I should actually try out if "message only" does get me close to the desired behavior.

I would prefer to leave the debugging settings as they are, but have the option to turn off the code browser or an option that the code browser opens, but leaves the focus on the current tab/editor. This would also cover the case that I want to jump to a browser() statement in a function. Suppose, I have the function in the current tab in front of me. Then I execute the function. The code browser will be opened and I get the function read-only. I have to jump back to the last tab for small changes to the code while the function is still executed.

![image](https://user-images.githubusercontent.com/7468121/80447910-0b9a3800-891b-11ea-9c07-3d4690dfd74b.png)

**Comment by julou** [comment]
I bump this issue since I constantly run into the same undesired behaviour.
Any hint how to prevent the debug tab from opening? or is it simply not possible?

**Comment by marcus-eger** [comment]
I want to emphasize that this is also an issue for me - which strongly affects everyday work. The shifted focus very often leads to unintended behaviour, e.g. removal of lines of code marked for copy&paste.

**Comment by davidseres** [comment]
This is a really cumbersome debugging behaviour. Please add a switch button or any other means to stop R Studio to switch focus to the code browser. This issue has been open for 1.5 years and there still haven't been any replies from the Team... :/

**Comment by luca-scr** [comment]
It seems to be fixed on the daily builds of RStudio 
https://dailies.rstudio.com

**Comment by bokov** [comment]
Has that daily been released yet? What version number?

**Comment by luca-scr** [comment]
Preview version 2022.02.2 Build 485 works ok.
