### ISSUE TITLE
Go to function definition doesn't work properly if the function was reassigned

### ISSUE THREAD

**Issue by tomtom** [rstudio/rstudio#6741]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows
    R Version       : 3.6.2

### Steps to reproduce the problem

```{R}
foo <- function (a) a * 2
bar <- foo
bar(2)
```

1. Evaluate lines 1+2.
2. Place the cursor at `bar(2)`, and then invoke "Go to definition".

### Describe the problem in detail

Acutal results: RStudio displays the in memory definition of the function.

### Describe the behavior you expected

Expected result: Go to line 2, where `bar` was defined, so that I can jump to the definition of `foo` later on.

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Thank you so much for filing the issue @tomtom.
We were able to reproduce the issue on both Windows and Mac as well as versions 1.2.5042 & 1.3.952. We'll mark this issue as a bug and look to address it in future versions of RStudio.
