### ISSUE TITLE
Desktop and server share a source database

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6742]
### System details

    RStudio Edition : Both
    RStudio Version : 1.3.947

### Steps to reproduce the problem

Via @jjallaire:

> I've pretty much confirmed that server and desktop are sharing a source database. I made some edits in desktop then saw those same edits when I loaded the same project in server:

![image](https://user-images.githubusercontent.com/470418/80394068-3080a380-8866-11ea-98d6-527c27c50045.png)

> I chose to save the edits in server (after originating them in desktop), then when switching over to desktop and trying to save the same file (which still shows up unsaved), I get this:

![image](https://user-images.githubusercontent.com/470418/80394088-38d8de80-8866-11ea-816b-f0921dc3e4e4.png)

### Describe the behavior you expected

Separate source databases (sets of document tabs) for desktop and server.

**Comment by rich-rstudio** [comment]
verified on Ubuntu Desktop and Server v1.3.951
