### ISSUE TITLE
Themes unit tests broken

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6743]
The themes unit tests are currently broken on master. 

Sample output from a recent run (https://buildmaster.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/master/2436/pipeline/762):

```
[2020-04-26T23:57:10.418Z] Theme: Active4D

[2020-04-26T23:57:10.418Z] Element ".ace_comment-highlight" "background-color" rule doesn't match. Actual: #ffeccb, Expected: rgb(254, 155, 243) 

[2020-04-26T23:57:10.418Z] Theme: All Hallow's Eve

[2020-04-26T23:57:10.418Z] Element ".ace_comment-highlight" "background-color" rule doesn't match. Actual: #d1b78a, Expected: #5c4916 
```

Likely due to https://github.com/rstudio/rstudio/commit/736b25ead36ff6c9f396f226eb7e7d8a41b9074e.

**Comment by jmcphers** [comment]
Indeed, https://github.com/rstudio/rstudio/commit/736b25ead36ff6c9f396f226eb7e7d8a41b9074e changed a color but didn't regenerate the themes (so that's probably all that's needed here)

**Comment by jmcphers** [comment]
@MariaSemple @jjallaire mentioned that you were planning on fixing this by regenerating the themes (let me know if that isn't the case!)

**Comment by MariaSemple** [comment]
I was planning to regenerate the themes, but I didn't realize some of the themes had already been manually updated.

**Comment by MariaSemple** [comment]
Oh, I see - the tests are failing because the expected colour is the new colour and the themes haven't been regenerated.
