### ISSUE TITLE
R diagnostics aren’t turned off when the file type switches

### ISSUE THREAD

**Issue by brian-law-rstudio** [rstudio/rstudio#6751]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.5019 
    OS Version      :  On colorado
    R Version       : 3.6.2

### Steps to reproduce the problem
Start with a .R script then change its type to be .Rmd, the text highlighting works but it also finds errors in valid markdown syntax with the little red dot with white X appearing in the left margin. 

### Describe the problem in detail
The above covers it.

### Describe the behavior you expected
The now .Rmd file diagnostics would correctly not spot errors in valid markdown. Thank you!

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I wasn't able to repro with 1.2.5042 using macOS desktop version. Same no-repro with 1.3.497 (server). Can you elaborate on the exact repro steps you are using?

My specific steps:

- File / New File / R Script
- enter this in file:

~~~Rmd
---
title: this
output: html_document
---
  
```{r}
test <- 47
```

Ta Da!
~~~

- save file as test.R
- now see this (expected):

<img width="245" alt="screenshot showing errors in rmarkdown file checked as R script" src="https://user-images.githubusercontent.com/10569626/80535609-ef67bc80-8955-11ea-9d00-2f113eb60764.png">

- change file type to RMarkdown using editor control in lower-right
- errors go away

<img width="496" alt="2020-04-28_13-42-54" src="https://user-images.githubusercontent.com/10569626/80535917-64d38d00-8956-11ea-920b-77e446bb7c08.png">

**Comment by jmcphers** [comment]
> change its type to be .Rmd

I think @brian-law-rstudio did this by using Save As -> Rmarkdown rather than by switching the file mode.

**Comment by gtritchie** [comment]
Ah, got it now, here are the revised steps I followed (after peeking back at the video @brian-law-rstudio had posted in Slack originally):

- File / New File / R Script
- enter Rmd script as shown previously
- File / Save As / Type in "test.Rmd"
- this actually gets saved as "test.Rmd.R" and thus is still treated as an R file, and shows the diagnostic errors
- File / Rename / remove the trailling .R, giving file the intended "test.Rmd"
- Now type changes to R Markdown and initially the errors are gone
- But put cursor at end of editor and type something else, such as `cat("dog")`
- Wait a second or two, and the errors are shown again

<img width="460" alt="screenshot showing bogus diagnostic errors after doing File Rename" src="https://user-images.githubusercontent.com/10569626/80537760-69e60b80-8959-11ea-8cd9-bc781c3acc84.png">

**Comment by brian-law-rstudio** [comment]
Bingo. Thanks both!

-Brian
