### ISSUE TITLE
RStudio attempts to download Rtools even though already installed - can't use RTools as a result

### ISSUE THREAD

**Issue by analyticsfc** [rstudio/rstudio#6754]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Windows 7 64 bit
    R Version       : 3.6.3

### Steps to reproduce the problem
> library(pkgbuild)
> library(devtools)
Loading required package: usethis

Attaching package: ‘devtools’

The following object is masked from ‘package:pkgbuild’:

    build

> devtools::install_github("statsbomb/StatsBombR")
Downloading GitHub repo statsbomb/StatsBombR@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                         
2: CRAN packages only          
3: None                        
4: xml2 (1.3.1 -> 1.3.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
NA         (NA    -> 4f193c85e...) [Git]
dplyr      (NA    -> 0.8.5       ) [CRAN]
rvest      (NA    -> 0.3.5       ) [CRAN]
RCurl      (NA    -> 1.98-1.2    ) [CRAN]
doParallel (NA    -> 1.0.15      ) [CRAN]
foreach    (NA    -> 1.5.0       ) [CRAN]
sp         (NA    -> 1.4-1       ) [CRAN]
tidyr      (NA    -> 1.0.2       ) [CRAN]
iterators  (NA    -> 1.0.12      ) [CRAN]
tidyselect (NA    -> 1.0.0       ) [CRAN]
plogr      (NA    -> 0.2.0       ) [CRAN]
xml2       (1.3.1 -> 1.3.2       ) [CRAN]
selectr    (NA    -> 0.4-2       ) [CRAN]
bitops     (NA    -> 1.0-6       ) [CRAN]
Skipping 1 packages not available: SDMTools
Downloading git repo https://github.com/cran/SDMTools.git
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe'
Content type 'application/x-msdownload' length 108622512 bytes (103.6 MB)
downloaded 103.6 MB

Error: Failed to install 'StatsBombR' from GitHub:
  Failed to install 'unknown package' from Git:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

### Describe the problem in detail

When attempting to use devtools::install_github and RTools is required, RStudio states:

building r package from source requires installation of additional build tools - do you want to install the additional tools now?

Upon clicking YES it attempts to download RTools even though I already have it installed.
It then warns me RTools is already installed if I proceed with installation.

My path is:

"C:\\Program Files\\R\\R-3.6.3\\bin\\x64;C:\\Rtools\\bin;C:\\Rtools\\mingw_64\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Common Files\\Microsoft Shared\\Windows Live;C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\Windows Live;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program Files (x86)\\EgisTec MyWinLocker\\x64;C:\\Program Files (x86)\\EgisTec MyWinLocker\\"

My BINPREF is:

C:/Rtools/mingw_$(WIN)/bin/

### Describe the behavior you expected

I would expect RStudio to use RTools rather than ask me to install it, when it is already installed.

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Is this issue reproducible without `devtools::install_github()`? It's not clear that this is an issue with RStudio versus the package(s) you are using.

**Comment by analyticsfc** [comment]
I can replicate with

pkgbuild::check_build_tools(debug = TRUE)
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe'
Content type 'application/x-msdownload' length 108622512 bytes (103.6 MB)

This triggers the downloading of RTools35.exe then the warning it is already installed.

Yet if I run the below  I get True:

find_rtools()
[1] TRUE

Running pkgbuild::find_rtools(debug = TRUE) I get:

pkgbuild::find_rtools(debug = TRUE)
Scanning R CMD config CC...
cc_path:  
'' does not exist
Scanning path...
ls: C:\Rtools\bin\ls.exe 
gcc_path: C:\Rtools\mingw_64\bin\gcc.exe 
VERSION.txt
Rtools version 3.5.0.4 
Version: 3.5 
Found compatible gcc on path
[1] TRUE

**Comment by kevinushey** [comment]
I believe this is issue is separate from RStudio: you might want to follow up on the `pkgbuild` issues. https://github.com/r-lib/pkgbuild/issues
