### ISSUE TITLE
rtools40 not found

### ISSUE THREAD

**Issue by jshousephd** [rstudio/rstudio#6755]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Win10 Version 1909 x64
    R Version       : 4.0

### Steps to reproduce the problem
Install R4.0
Install Rstudio 1.2.5042
Install Rtools40 -> default location it puts it is in: c:\Rtools40
Install some packages that need Rtools (run from Rstudio "new script")

### Describe the problem in detail

```
install.packages(c("janitor","outliers","missForest","frequency","Amelia",
                   "diffobj","mice","VIM","mi",
                   "wrangle"), dependencies = TRUE)
```

Receive this message:
```
WARNING: Rtools is required to build R packages but no version of Rtools compatible with the currently running version of R was found. Note that the following incompatible version(s) of Rtools were found:

  - Rtools 3.4 (installed at c:\Rtools)

Please download and install the appropriate version of Rtools before proceeding:
```

***it does actually move on to install packages***
### Describe the behavior you expected
I expected it to look in correct location for the new Rtools40

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Did you follow all of the instructions here?

https://cran.r-project.org/bin/windows/Rtools/

In particular, see the instructions about putting Rtools on the PATH.

**Comment by jshousephd** [comment]
I did not! Failure to read on my part. Sorry!
However, following those directions resulted in an apparent success:

```
> Sys.which("make")
                              make 
"C:\\rtools40\\usr\\bin\\make.exe" 
```
But also caused this error to show up on R restart.  Also upon closing Rstudio and reopening.

```
Error: package or namespace load failed for ‘stats’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Program Files/R/R-4.0.0/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

During startup - Warning message:
package ‘stats’ in options("defaultPackages") was not found 
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Program Files/R/R-4.0.0/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.
```

**Comment by jshousephd** [comment]
Changing back to R 3.6.3 in Rstudio and restarting Rstudio retrieves similar message.

```
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error: package or namespace load failed for ‘stats’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Program Files/R/R-3.6.3/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

During startup - Warning message:
package ‘stats’ in options("defaultPackages") was not found 
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Program Files/R/R-3.6.3/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.
```

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding, but your updated PATH entry looks incorrect:

> writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${C:\\rtools40}"', con = "~/.Renviron")

This should just be:

> writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")

You might want to manually edit the file at `~/.Renviron` to fix that up.

**Comment by jshousephd** [comment]
> Maybe I'm misunderstanding, but your updated PATH entry looks incorrect:
> 
> > writeLines('PATH="${RTOOLS40_HOME}\usr\bin;${C:\rtools40}"', con = "~/.Renviron")
> 
> This should just be:
> 
> > writeLines('PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"', con = "~/.Renviron")
> 
> You might want to manually edit the file at `~/.Renviron` to fix that up.

Thank you. I misunderstood. I thought I was supposed to replace PATH with my path. I have edited the file directly and both R4.0 and the ability to install from binary are operational.  Thanks for your help.

**Comment by kevinushey** [comment]
Great! I'm glad to hear it.
