### ISSUE TITLE
Unable to launch RStudio on ubuntu 20.04 under WSL2

### ISSUE THREAD

**Issue by lepidonotus** [rstudio/rstudio#6760]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : ubuntu 20.04 under WSL2
    R Version       : 3.6.3

### Steps to reproduce the problem
```
wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5042-amd64.deb
sudo apt update
sudo apt install ./rstudio-1.2.5042-amd64.deb
rstudio
```
result:
bash: /usr/bin/rstudio: cannot execute binary file: Exec format error

**Comment by jmcphers** [comment]
RStudio is not supported on WSL. See https://github.com/rstudio/rstudio/issues/4367.

**Comment by abalter** [comment]
@jmcphers -- Is there any kind of explanation you can give for this? There 10s of thousands of people who want to run RStudio Desktop on WSL. Is it on the roadmap? Is there some sort of corporate reason for this?

**Comment by gtritchie** [comment]
@abalter -- You can run RStudio Server just fine on WSL2. See https://support.rstudio.com/hc/en-us/articles/360049776974-Using-RStudio-Server-on-Windows-with-WSL2 for more on that.

WSL (1 and 2) are intended for running terminal (command-line) applications and do not include an X-Windows server out of the box, therefore cannot run desktop programs such as RStudio or any others.

It is on Microsoft's roadmap to change this https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gui.

There are third-party options for adding X server support for WSL today, so it may be possible to hobble something together in the meantime, but this isn't something we can officially support. Once WSL has support for graphical applications, then it is very likely RStudio Desktop for Linux will work, and we'll certainly test it.

**Comment by abalter** [comment]
@gtritchie -- I understand your point somewhat. However, I and tons of other people DO use X11 solutions. I access WSL using MobaXTerm and run lots fo GUI applications, including RStudio Desktop 1.1.436 which seems to be the most recent version that WILL install in WSL. I was hoping with WSL2 with it being more native the situation would be better. but it's not.

RStudio Server does run fine, but it's clunky having to go through my browser. I an separate out a tab with RSS which makes it feel more native, but it's still nowhere near as good for production work.

Can you tell me what the exact problem is? Maybe some smart people in the hive mind can find a workaround.

Thanks, Ariel

**Comment by gtritchie** [comment]
The problem is time. I have a huge list of things to work on, and this, unfortunately, is very far down the list (isn't actually on the list, just something I'm poking at in my own time).

**Comment by gtritchie** [comment]
It will almost certainly be a problem with missing dependencies. There's no (known) technical reason it shouldn't work.

Also, there are some known problems with the version of Chromium (via Qt5) used in RStudio 1.2 on Ubuntu 20, so try using the latest 1.3 preview release, instead: https://rstudio.com/products/rstudio/download/preview/

Then try installing with gdebi to resolve dependencies:

```
sudo apt remove rstudio
sudo apt install gdebi-core
sudo gdebi RSTUDIO.deb <---obviously substitute the real thing here
```

Then see what errors are displayed and that might give additional hints.

**Comment by gtritchie** [comment]
Ok, I gave it a try (using MobaXTerm), WSL2, RStudio 1.3.1050 (Ubuntu Bionic build), and installed via gdebi, and have RStudio 1.3 Linux Desktop up and running.

Now back to my regularly scheduled job.

**Comment by gtritchie** [comment]
For future reference, here's what I did:

- fresh WSL2 Ubuntu 20.04 install
- sudo apt update
- sudo apt upgrade -y
- sudo apt install -y gdebi-core
- sudo apt install -y libnss3
- add to end of ~/.bashrc: `export DISPLAY="$(/sbin/ip route | awk '/default/ { print $3 }'):0"`
- (install R and related tools, leaving as exercise for the reader)
- wget https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.3.1050-amd64.deb
- sudo apt install -y ./rstudio-1.3.1050-amd64.deb
- in Windows, download, install, run MobaXterm: https://mobaxterm.mobatek.net/
- in WSL2, `rstudio`
- have to say "Yes" to a few prompts then RStudio appears

**Comment by abalter** [comment]
@gtritchie -- this is really awesome! I'll try it as well and post back. Thanks!

**Comment by abalter** [comment]
This worked! I do get two errors. Can you tell me if they are important?

At the command line I get

```sh
(base) balter@spectre:~$ rstudio
[25477:25477:20200626,181326.716466:ERROR filesystem_posix.cc:89] stat /home/balter/.r/crashpad_database: No such file or directory (2)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-balter'
qt.qpa.xcb: QXcbConnection: XCB error: 145 (Unknown), sequence: 178, resource id: 0, major code: 139 (Unknown), minor code: 20
```

In RStudio, when it launches, I get 

```r
Error in tools::startDynamicHelp() : internet routines cannot be loaded
```

One more thing, can you please explain what `export DISPLAY="$(/sbin/ip route | awk '/default/ { print $3 }'):0"` does? 

Thanks!

**Comment by gtritchie** [comment]
I think you can safely ignore those command-line messages (though I'm not sure what's causing them, I did not encounter them in my quick test).

The console error was mentioned here, so maybe something helpful: https://github.com/rstudio/rstudio/issues/4904

The DISPLAY export was something I found when I searched for "wsl2 mobaxterm", I think here: https://github.com/microsoft/WSL/issues/4106

**Comment by abalter** [comment]
@dorianps -- Thank you immensely for putting that together! I just went through it, and worked seamlessly. The data science community applauds you!

**Comment by ishwarvh** [comment]
Hello @gtritchie, thank you for this quick fix. However, I am getting the following error about unable to load Qt platform. 

I have tried to explicitly set the display variable to my windows IP address prior to starting rstudio in WSL2, as that was suggested in some forums to get some other Qt applications working in WSL2. However, that also didn't fix the problem. 

Here is the error message, hope you can steer me in the right direction.

Thank you,
> qt.qpa.xcb: could not connect to display xx.xx.xx.xx:0.0 (my windows IP address) 
plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

**Comment by gtritchie** [comment]
Just FYI I've been out for a few days (moving) so haven't had a chance to look into your question but I haven't forgotten!

**Comment by nickschurch** [comment]
I have this problem with the 2021.09.2+382 version on WSL2 Ubuntu 20.04 LTS, even with the display variable set correctly. I can display other X window GUIs just fine, but no rstudio.

Really surprised this isn't more of a priority to get working without old-version work arounds...

**Comment by dorianps** [comment]
@nickschurch The most streamlined approach I have found is to use RStudio Server instead of RStudio Desktop. Last time I installed and used it was 2 days ago on WSL2. Works also great when you work on a remote server. Just start rstudio-server and point the browser to the IP of the remote server (or the IP you see when Ubuntu starts on WSL2. No headaches with X-server and displays, and better looking text+graphics. I have written some instructions for using Rstudio Server as part of the ANTsR installation:
https://github.com/ANTsX/ANTsR/wiki/Installing-ANTsR-on-Windows-10-(using-WSL2)

**Comment by nickschurch** [comment]
Yes, U do this already. This has it's own wrinkles, however, particularly when it comes to pointing rstudio-server at the relevant  versions of R and packages when using conda environments. I was hopeful that this would prove more straightforward using Rstudio itself, but clearly that is not even an option.
