### ISSUE TITLE
Static URL for daily Linux builds?

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#6770]
Following @jmcphers [post about static URLs to the latest builds](https://support.rstudio.com/hc/en-us/articles/203842428-Getting-the-newest-RStudio-builds), I am unable to compose the correct one for Ubuntu (Desktop).

The following URLs do not work:

- https://www.rstudio.org/download/daily/desktop/ubuntu64/rstudio-bionic-latest-amd64.deb
- https://www.rstudio.org/download/daily/desktop/ubuntu64/rstudio-latest-amd64.deb
- https://www.rstudio.org/download/daily/desktop/ubuntu64/rstudio-desktop-bionic-latest-amd64.deb
- https://www.rstudio.org/download/daily/desktop/ubuntu64/rstudio-desktop-latest-amd64.deb

The following URL from the post linked above is also a 404: http://www.rstudio.org/download/daily/server/ubuntu64/rstudio-server-latest-amd64.deb

Are there currently static links for Linux flavors?

**Comment by jmcphers** [comment]
Very close! You need `/bionic/` in the URL and `/latest/`. This should work (feel free to reopen if it doesn't). 

http://www.rstudio.org/download/latest/daily/desktop/bionic/rstudio-latest-amd64.deb

**Comment by R-Hannibal** [comment]
After talking with @jmcphers we decided to replace the instructions on [Getting the newest RStudio builds](https://support.rstudio.com/hc/en-us/articles/203842428-Getting-the-newest-RStudio-builds) with a list of URLs in the **Via URL to install image** section.
