### ISSUE TITLE
Improvement to error output when generating SSH key

### ISSUE THREAD

**Issue by JsizzleR** [rstudio/rstudio#6771]
Customer request to improve this error so that it can be copied/resized.  They received the output while trying to generate a key for version control:

![image](https://user-images.githubusercontent.com/27960665/80620432-0240c680-8a14-11ea-89f9-31fa0895f3ba.png)

RSP version:  1.2.5033-1
Ticket: 47431

**Comment by gtritchie** [comment]
Confirmed this dialog doesn't allow selection/copy, and isn't resizable.

**Comment by dfalty** [comment]
Verified this dialog now word wraps and you can copy/paste the text on version 1.4.874. You still cannot resize the box but I think this will be sufficient. Please reopen if you feel otherwise.
