### ISSUE TITLE
Keyboard shortcut to paste to script pane with auto indenting temporarily disabled

### ISSUE THREAD

**Issue by stevecondylios** [rstudio/rstudio#6780]
RStudio's auto indenting feature is heavily utilised and it's very common for users to leave it on. There's a very frequent use case for _not_ wanting it though; that is when pasting a code representation of a data structure (i.e. typically the output of `dput()`) into the script pane. 

Simple example `dput(iris)` extends many columns wide when pasted into the RStudio script pane. 

It would be great to have a simple keyboard shortcut that allowed one to paste to the script pane auto indent temporarily deactivated. 

As a somewhat analogous feature in another suite of software, google docs have a simple way of pasting without formatting <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>v</kbd>. This is so simple, easy to remember (since it's very similar to the usual <kbd>cmd</kbd> + <kbd>v</kbd> for pasting), and a great time saver. Following this convention would be intuitive. 

I think it raises one question: if pasting without auto indenting, what format _should_ be used? I am not sure, but would guess 80 characters would be a sensible default? (other options could be as-is)

As an aside, another keyboard shortcut that `dput()`s output to clipboard would be pretty amazing too, as I don't believe there's any laconic way of doing it without user defined functions.

**Comment by jmcphers** [comment]
There is an undocumented way to do this. See here: https://github.com/rstudio/rstudio/pull/6451

Does that help?

**Comment by stevecondylios** [comment]
The unofficial command sounds like it would achieve the desired functionality, but it doesn't seem to work for me. 

For completeness, I tried pasting the output of `dput(iris)` with 'Auto-indent code after paste' unchecked, and tested all combinations of cmd, ctrl, shift and v (just to be thorough). I tried the same with 'Auto-indent code after paste'  checked as well, just to be sure. And then both previous combinations with 'Auto-detect code indentation both checked, then unchecked, just to be completely sure. 

But after these attempts (before and after reboots, and after updating to 1.2.5042), I still don't have any luck. 

Here are my settings and session info, in case they're relevant:

<img src="https://user-images.githubusercontent.com/16319829/81180309-2b51f000-8fee-11ea-8a78-ddfe8c3412a7.png" width=50% height=50%>

```R
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2   rsconnect_0.8.16 tools_3.6.2
```
