### ISSUE TITLE
Viewer no longer works for DT::datatable in Version 1.2.5042

### ISSUE THREAD

**Issue by AdrianHordyk** [rstudio/rstudio#6786]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : 1.2.5042
    OS Version      :  Windows 10
    R Version       : 4.0.0 

### Steps to reproduce the problem
```
library(DT)
datatable(data.frame(x = Sys.Date()))
```
### Describe the problem in detail
Datatable does not show in the Viewer panel most of the time. The icons in Viewer panel change, indicating that something has registered there, but the table does not show - even after waiting several minutes.

Repeatedly clicking 'Remove current viewer item' or 'Clear Viewer' and re-trying the code results in the table showing correctly occasionally. 

It appears to have stopped since I updated RStudio to the latest version.

I updated R at the same time - it works fine by opening datatable in web browser if run directly from R console. 

### Describe the behavior you expected
Usual behavior is to instantanously display the datatable in the Viewer panel. 

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is almost certainly another manifestation of https://github.com/rstudio/rstudio/issues/6737. I will reopen that and close this one.

**Comment by AdrianHordyk** [comment]
Not sure if it is helpful, but I forgot to mention that my CPU usage (shown in Task Manager) goes through the roof (95%+) when I run the code and the table doesn't show in the Viewer panel

**Comment by jmcphers** [comment]
Yep, @jcheng5 mentioned this too:

> Strangely, the rsession uses more and more CPU each time--each additional run seems to permanently spike one of my CPUs, in the rsession.exe process.
