### ISSUE TITLE
Changing rendering engine doesn't persist through restart so can't be changed; Linux

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#6789]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.944
    OS Version      :  Xubuntu 19.10
    R Version       :  3.6.1

### Steps to reproduce the problem
Open RStudio, tools, global options, general, advanced, rendering engine, change to software, requires restart, ok, go back to options, currently set option is auto-detect.

**Comment by SimonDedman** [comment]
Relates to [this](https://community.rstudio.com/t/video-lag-xubuntu19-10-weirdly-worse-than-other-programs/59517/2); I'll stop posting RStudio IDE bugs in Community & move em here.

**Comment by kevinushey** [comment]
I was able to reproduce this as well. It looks like this occurred because the preference file, located at:

```
~/.config/RStudio/desktop.ini
```

was owned by `root` rather than my user account. Do you see the same thing? If so, does `chown`-ing that (or removing it and letting RStudio re-create it) fix the issue?

**Comment by SimonDedman** [comment]
sudo chown me desktop.ini

Does indeed work, nice one. Haven't seen a desktop.ini in a while!

Good thinking. Option to make this user owned by default in future builds?

Cheers Kev

**Comment by jmcphers** [comment]
This is a special case of https://github.com/rstudio/rstudio/issues/6270; we'll track the issue there.
