### ISSUE TITLE
Opening Rds files from file explorer spawns new RStudio instance per file

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#6790]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.944
    OS Version      : xubuntu 19.10
    R Version       : 3.9.1

### Steps to reproduce the problem
File explorer is Thunar 1.8.14 (latest) on XFCE, never had this problem before. Have RStudio open, do some work, doubleclick an Rds file and it opens in a second instance of RStudio which spawns for it. If I click a third Rds file, it spawns a third RStudio.

**Comment by kevinushey** [comment]
By `Rds` file, do you mean a serialized R object (normally written by `saveRDS()`)? Or is this something else?

A reproducible example, or video, so we know exactly what you're doing would be helpful.

**Comment by SimonDedman** [comment]
As you expect yeah:
saveRDS(object, file = "object.Rds")
doubleclick object.Rds

**Comment by SimonDedman** [comment]
Works fine in latest preview version, 1.3.957
