### ISSUE TITLE
Apply eTag based caching in more places

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#6791]
There are a number of places where we set a cacheable file without enforcing revalidation. We should review these usages and decided whether any or all of them should have the force revalidation headers applied. If all, we may want to add a call to `setCacheWithRevalidationHeaders` to the implementation of `setCacheableFile`. Otherwise, we may want to make a method like `setRevalidationCacheableFile` which can be used to apply the revalidation headers and set the cacheable file.

Example of where we call both:
https://github.com/rstudio/rstudio/blob/master/src/cpp/core/gwt/GwtFileHandler.cpp#L184-L185

Example of where we only call `setCacheableFile`:
https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/rmarkdown/NotebookOutput.cpp#L308-L311

**Comment by R-Hannibal** [comment]
Marking this issue as 'verified', no QA run.
