### ISSUE TITLE
RStudio console and R's normal console behave differently when returning CHARSXP objects

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#6792]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2653c45e, 2019-10-16
    OS Version      : Archlinux
    R Version       : 3.6.0

#### RStudio console with reprex

If the code below is run from RStudio's console using reprex I get those errors related to attributes.

``` r
library(inline)  
as_char <- cfunction(c(x = "any"),
' SEXP x_;
  x_ = PROTECT(Rf_asChar(x));
  UNPROTECT(1);
  return x_;
')
as_char('coal')
#> Error in inherits(x, "htmlwidget"): cannot have attributes on a CHARSXP
foo <- as_char('coal')
foo
#> Error in inherits(x, "htmlwidget"): cannot have attributes on a CHARSXP
```

#### RStudio console without reprex

``` r
library(inline)  
as_char <- cfunction(c(x = "any"),
' SEXP x_;
  x_ = PROTECT(Rf_asChar(x));
  UNPROTECT(1);
  return x_;
')
as_char('coal')
#> <CHARSXP: "coal">
foo <- as_char('coal')
#> <simpleError in doTryCatch(return(expr), name, parentenv, handler): cannot have attributes on a CHARSXP>
#> <simpleError in is(obj, "ore.frame"): cannot have attributes on a CHARSXP>
#> Error in inherits(x, "data.frame") : cannot have attributes on a CHARSXP
foo
#> <CHARSXP: "coal">
```

#### R's normal console

The same code run from R console, runs fine without any warnings or errors.

``` r
library(inline)  
as_char <- cfunction(c(x = "any"),
' SEXP x_;
  x_ = PROTECT(Rf_asChar(x));
  UNPROTECT(1);
  return x_;
')

as_char('coal')
#> <CHARSXP: "coal">
foo <- as_char('coal')
foo
#> <CHARSXP: "coal">
```

### Describe the problem in detail

I know I should probably be not exposing a CHARSXP object to R la land. However, I found it pedagogical. Now the reason why I am reporting this as a bug is not so much because I get an error in RStudio but because it behaves differently from what would happen in a normal R console.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note that this only reproduces if the Environment pane is open, and this likely occurs because we try to introspect options in the Environment pane using some R APIs, and most of those cause an error when called on `CHARSXP`s. For example:

```
> ch
<CHARSXP: "coal">
> class(ch)
Error: cannot have attributes on a CHARSXP
> str(ch)
Error in str(ch) : cannot have attributes on a CHARSXP
```

To fix this, we'd need to be pretty diligent about screening out `CHARSXP` objects before calling any R APIs (as those will likely fail).
