### ISSUE TITLE
When I tried to install ggplot2 from rstudio getting so many errors

### ISSUE THREAD

**Issue by habeeb555-q** [rstudio/rstudio#6794]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.5042
    OS Version      : Ubuntu 18.04
    R Version       : R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem

     > install.packages("ggplot2")` 

### ggplot2 Installation error from RStudio

`In file included from /usr/include/ctype.h:39,
from names.c:1:
/usr/local/include/x86_64-linux-gnu/bits/endian.h:4:3: error: #error "Never use <bits/endian.h> directly; include <endian.h> instead."
4 | # error "Never use <bits/endian.h> directly; include <endian.h> instead."
| ^~~~~
make: *** [/usr/lib/R/etc/Makeconf:168: names.o] Error 1
ERROR: compilation failed for package ‘vctrs’`

    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/vctrs’
    Warning in install.packages :
    installation of package ‘vctrs’ had non-zero exit status
    ERROR: dependencies ‘farver’, ‘munsell’ are not available for package ‘scales’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/scales’
    Warning in install.packages :
    installation of package ‘scales’ had non-zero exit status
    ERROR: dependency ‘callr’ is not available for package ‘pkgbuild’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/pkgbuild’
    Warning in install.packages :
    installation of package ‘pkgbuild’ had non-zero exit status
    ERROR: dependencies ‘utf8’, ‘vctrs’ are not available for package ‘pillar’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/pillar’
    Warning in install.packages :
    installation of package ‘pillar’ had non-zero exit status
    ERROR: dependency ‘pkgbuild’ is not available for package ‘pkgload’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/pkgload’
    Warning in install.packages :
    installation of package ‘pkgload’ had non-zero exit status
    ERROR: dependencies ‘pillar’, ‘vctrs’ are not available for package ‘tibble’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/tibble’
    Warning in install.packages :
    installation of package ‘tibble’ had non-zero exit status
    ERROR: dependency ‘pkgload’ is not available for package ‘testthat’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/testthat’
    Warning in install.packages :
    installation of package ‘testthat’ had non-zero exit status
    ERROR: dependency ‘testthat’ is not available for package ‘isoband’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/isoband’
    Warning in install.packages :
    installation of package ‘isoband’ had non-zero exit status
    ERROR: dependencies ‘isoband’, ‘scales’, ‘tibble’ are not available for package ‘ggplot2’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/ggplot2’
    Warning in install.packages :
    installation of package ‘ggplot2’ had non-zero exit status

The downloaded source packages are in
‘/tmp/RtmpUDws3M/downloaded_packages’`

### Expected behavior
The installation must complete while installing all the required dependencies successfully without any issue. How will the user know what are the dependencies of a package?

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Although we got message that rstudio is installing so many dependencies but it produces errors for errors.

`Installing package into ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ps’, ‘processx’, ‘callr’, ‘prettyunits’, ‘backports’, ‘desc’, ‘pkgbuild’, ‘rprojroot’, ‘rstudioapi’, ‘evaluate’, ‘pkgload’, ‘praise’, ‘colorspace’, ‘assertthat’, ‘utf8’, ‘Rcpp’, ‘testthat’, ‘farver’, ‘labeling’, ‘munsell’, ‘R6’, ‘RColorBrewer’, ‘viridisLite’, ‘lifecycle’, ‘cli’, ‘crayon’, ‘ellipsis’, ‘fansi’, ‘magrittr’, ‘pillar’, ‘pkgconfig’, ‘vctrs’, ‘digest’, ‘glue’, ‘gtable’, ‘isoband’, ‘rlang’, ‘scales’, ‘tibble’, ‘withr’`

**Comment by kevinushey** [comment]
Sorry, but this isn't an RStudio issue. Most likely cause is that your system's headers / include paths are messed up.
