### ISSUE TITLE
New project > New Package with devtools results in: "Error: Internal error: use rlang's `is_interactive()` instead of `base::interactive()`"

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#6795]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.947 "Middlemist Red" (1549686f, 2020-04-22) for Ubuntu Bionic
    OS Version      : Archlinux
    R Version       :  3.6.0

### Steps to reproduce the problem

Steps:
1. Create a New Project
2. R Package using devtools
3. Pick a directory name (in my example I picked "foo")

### Describe the problem in detail

During the project setup RStudio throws this error:

```
Error: Internal error: use rlang's `is_interactive()` instead of `base::interactive()`
```

Here the whole log:

```
✓ Creating 'foo/'
✓ Setting active project to '/home/rmagno/dwl/foo'
✓ Creating 'R/'
✓ Writing 'DESCRIPTION'
Package: foo
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre] (<https://orcid.org/YOUR-ORCID-ID>)
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to
    pick a license
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.0
✓ Writing 'NAMESPACE'
✓ Writing 'foo.Rproj'
✓ Adding '.Rproj.user' to '.gitignore'
✓ Adding '^foo\\.Rproj$', '^\\.Rproj\\.user$' to '.Rbuildignore'
Error: Internal error: use rlang's `is_interactive()` instead of `base::interactive()`
✓ Setting active project to '<no active project>'
```

In pictures:

![Screenshot from 2020-05-02 14-28-25](https://user-images.githubusercontent.com/19862384/80865478-ad09ec80-8c81-11ea-9724-b70ef9f94a77.png)

![Screenshot from 2020-05-02 14-28-31](https://user-images.githubusercontent.com/19862384/80865487-b85d1800-8c81-11ea-9282-65402dd19bec.png)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Sorry, I wasn't able to reproduce. What is the output of `sessionInfo()`? Do you need to update your packages?

**Comment by ramiromagno** [comment]
Okay, so I just updated all packages. The error has changed now.

But before that, here's my `sessionInfo()`:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.6.so
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_DK.utf8         LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    packrat_0.5.0 
```

This log `/home/rmagno/.rstudio-desktop/log/rsession-rmagno.rotated.log`:

```
14 Oct 2019 11:22:08 [rsession-rmagno] ERROR Error parsing translation unit /home/rmagno/sci/code/R/pkg/glfw/src/gl_tex_coord.cpp; LOGGED FROM: rstudio::core::libclang::TranslationUnit rstudio::core::libclang::SourceIndex::getTranslationUnit(const string&, bool) /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/core/libclang/SourceIndex.cpp:270
14 Oct 2019 11:22:12 [rsession-rmagno] ERROR Error parsing translation unit /home/rmagno/sci/code/R/pkg/glfw/src/gl_tex_coord.cpp; LOGGED FROM: rstudio::core::libclang::TranslationUnit rstudio::core::libclang::SourceIndex::getTranslationUnit(const string&, bool) /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/core/libclang/SourceIndex.cpp:270
14 Oct 2019 11:22:13 [rsession-rmagno] ERROR Error parsing translation unit /home/rmagno/sci/code/R/pkg/glfw/src/gl_tex_coord.cpp; LOGGED FROM: rstudio::core::libclang::TranslationUnit rstudio::core::libclang::SourceIndex::getTranslationUnit(const string&, bool) /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/core/libclang/SourceIndex.cpp:270
```

In pictures:

![RStudio_error](https://user-images.githubusercontent.com/19862384/80999939-5f39e380-8e3d-11ea-94b2-0268899f627f.png)

BTW:

1. R starts fine from normal console, i.e., outside RStudio
2. I only have one R version in my machine
3. I don't have any customisations in `.Rprofile`.

**Comment by jmcphers** [comment]
I don't think the new error is related to the old one, so closing this (feel free to open another issue with the new error if you're still seeing it). You might also try upgrading to our preview release:

https://www.rstudio.com/products/rstudio/download/preview/
