### ISSUE TITLE
RStudio becomes unusable after tinkering with renv

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#6799]
I can't post exact reproducible steps unfortunately because I was just experimenting with renv and I kept noticing this problem. I created a few projects with renv and kept removing and re-adding renv, and my RStudio kept freezing like the screenshot below

![image](https://user-images.githubusercontent.com/952340/80923554-8667b680-8d52-11ea-8457-9d00da536a75.png)

The only way to close RStudio would be to kill it from the task manager. The project would become un-openable in RStudio and I'd be forced to delete the folder and re clone from git.

I know this isn't a terribly useful issue because of lack of detail.

**Comment by kevinushey** [comment]
Sorry, but unless you can provide a reproducible example this isn't helpful.

**Comment by daattali** [comment]
Yeah that's fair. At least if someone else runs into this in the future, there'll be a record of it happening in the past!
