### ISSUE TITLE
get_artist_audio_features from spotifyr doesn't work

### ISSUE THREAD

**Issue by ahoj101** [rstudio/rstudio#6800]
Hi.
I am using the spotifyr package to work with spotify data. I want use get_artist_audio_features for an artist called Jelen, so I put his name into the function:

```{r}
jelen<-get_artist_audio_features('Jelen')
```

It worked, but the features I received wasn't from Jelen, but Jelena Kerleusa. Then I found Jelen's artist ID and run the code again:

```{r}
 jelen<-get_artist_audio_features('2m34bLaM6TJ5Iw6TOB3ejr')   
 ```

but this time I only got an error:

 ```{r}
Error in parse_url(url) : length(url) == 1 is not TRUE
In addition: Warning messages:
1: Unknown or uninitialised column: 'id'. 
2: Unknown or uninitialised column: 'name'. 
```

I also asked on stackoverflow.com and I was recommended to make an issue here as it looks like a bug report. Do you have any idea how to make it work?

Thank you

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
