### ISSUE TITLE
Updating RStudio's Stan Syntax Checking

### ISSUE THREAD

**Issue by ssp3nc3r** [rstudio/rstudio#6802]
Stan v. 2.23 has new syntax for multithreaded chains:  `reduce_sum()` 

https://mc-stan.org/docs/2_23/stan-users-guide/reduce-sum.html

but RStudio's Stan syntax checking needs updating to recognize this as valid.

**Comment by ronblum** [comment]
@ssp3nc3r Thank you for bringing up the Stan update! We'll review your request as we continue development of RStudio.

**Comment by kevinushey** [comment]
Looks like `rstan` is still at version 2.21.1. Is there an update to `rstan` expected for this, or is this already available in the current version of `rstan`?

A concrete example of what you're seeing here would be helpful, as well -- e.g. the exact Stan document you're using, a screenshot of the error reported by RStudio, and so on.

**Comment by ssp3nc3r** [comment]
From the [Stan User Guide, now in version 2.24](https://mc-stan.org/docs/2_24/stan-users-guide/reduce-sum.html):

```
functions {
  real partial_sum(int[] y_slice,
                   int start, int end,
                   vector x,
                   vector beta) {
    return bernoulli_logit_lpmf(y_slice | beta[1] + beta[2] * x[start:end]);
  }
}
data {
  int N;
  int y[N];
  vector[N] x;
}
parameters {
  vector[2] beta;
}
model {
  int grainsize = 1;
  beta ~ std_normal();
  target += reduce_sum(partial_sum, y,
                       grainsize,
                       x, beta);
}

```

RStudio (Version 1.3.1070)'s syntax checking produces this error:

```
> rstan:::rstudio_stanc("test.stan")
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Variable "partial_sum" does not exist.
 error in 'model1d1918bc1980_test' at line 20, column 34
  -------------------------------------------------
    18:   int grainsize = 1;
    19:   beta ~ std_normal();
    20:   target += reduce_sum(partial_sum, y,
                                         ^
    21:                        grainsize,
  -------------------------------------------------

Error in stanc(filename, allow_undefined = TRUE) : 
  failed to parse Stan model 'test' due to the above error.
```

`rstan` is in 2.21.2, and I believe the developers are working to update the package to compile to the latest Stan syntax, but the above model syntax is correct and can be compiled using, for example, `cmdstanr`: _e.g._, `cmdstanr::cmdstan_model("test.stan")` The package `cmdstanr` is designed to be lightweight and stay automatically up-to-date with Stan's releases.

Does RStudio's syntax checking need to be interface/package specific to `rstan`?

**Comment by kevinushey** [comment]
This is an issue in the `rstan` package, then -- RStudio doesn't implement any of its own diagnostics for Stan models, it just uses whatever is built in to the `rstan` package. I believe this will be fixed once `rstan` is updated to use the latest version of Stan.

**Comment by ronblum** [comment]
This is also the behavior in the R GUI, outside of RStudio.

**Comment by R-Hannibal** [comment]
@ssp3nc3r - thanks again for filing this ticket, and for following up in the [rstan GitHub project](https://github.com/stan-dev/rstan/issues/821). Reading through that ticket it does sound like the issue will need to be fixed on the rstan side (and it sounds like they are discussing how to prevent this type of issue from occurring with a new release in the future).

Adding the verified label as we will not be taking any other action in RStudio at this time.

**Comment by mike-lawrence** [comment]
Sorry to chime in so belatedly, but I think the closure of this issue as relating to `rstan` misses the important point that the Stan dev team is encouraging folks/interfaces to move to using `cmdstanr` instead, where things will be more reliably up-to-date going forward.

**Comment by kevinushey** [comment]
@mike-lawrence: can you elaborate? Is `rstan` going to be deprecated or phased out, with `cmdstanr` becoming the recommended way to use Stan from R?

Our integration with `rstan` is mostly collected here:

https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/stan/SessionStan.R

I think a separate issue making this distinction clearer (need to use `cmdstanr` instead of `rstan`) would be helpful.

**Comment by guemues** [comment]
The problem now will be more severe as stan introduces deprecation of array declaration by placing brackets after a variable name.
