### ISSUE TITLE
routinely get this message Error: Unable to establish connection with R session

### ISSUE THREAD

**Issue by adprov81** [rstudio/rstudio#6803]
### System details

    RStudio Edition : RStudio Desktop 1.2.5042 for Windows 10
    R Version       : R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Platform: x86_64-w64-mingw32/x64 (64-bit)

### Describe the problem in detail

I'm a longtime RStudio user. About a month ago, I started to routinely get this message while working in RStudio:
Error: Unable to establish connection with R session
It shows up consistently, no matter what I do and no matter which files I am using. It occurs whether my working directory is linked to Dropbox or whether it is on my Desktop.

The problem does not occur with base R, only with RStudio

I've looked on the community boards and have tried the following things:
1. Uninstalling and reinstalling Rstudio
2. Changing the software rending to "Software"
3. Resetting Rstudio
4. Remove start-up files.Rdata , .Rprofile and .Rhistory and Rprofile.site

Issue seems very similar to the one described here: https://community.rstudio.com/t/rstudio-error-unable-to-establish-connection-with-r-session/58759

### Reproducing the issue
The issue ALWAYS happens within 20 seconds after I open RStudio. There is no pattern to the line of code that produces it or anything like that. 

X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@adprov81 Thank you for filing the issue, following up from Community discussion. I'm sorry that you're experiencing this problem. I can't reproduce it in a similar environment, though. I'll mark this as a bug to review as we continue work on RStudio development. In the meantime, we're working on a new release, 1.3 Middlemist Red, which is in the preview stage. If you'd like to try it and see if the problem is resolved, the latest RStudio preview is at https://www.rstudio.com/products/rstudio/download/preview/ .(Note that preview builds are intended for testing purposes only.)

**Comment by jmcphers** [comment]
Could you post a screenshot of what you see when you try the preview release? We have added startup diagnostics to RStudio 1.3, so you will see much more helpful errors when it cannot connect to the R session.

**Comment by adprov81** [comment]
It looks like the problem is gone in the preview release! I will let you know if it pops up again, but for now it seems like that solved it. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by adprov81** [comment]
Never mind – the problem is still there and I see the same message. Screenshot attached.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Myers, Adam S<mailto:amyers2@providence.edu>
Sent: Thursday, May 7, 2020 1:46 PM
To: rstudio/rstudio<mailto:reply@reply.github.com>; rstudio/rstudio<mailto:rstudio@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [External] Re: [rstudio/rstudio] routinely get this message Error: Unable to establish connection with R session (#6803)

It looks like the problem is gone in the preview release! I will let you know if it pops up again, but for now it seems like that solved it. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jmcphers** [comment]
Can you upload the screenshot via the Github issue tracker? Github does not support mail attachments.

**Comment by adprov81** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/64792609/81328217-81fd0f80-906a-11ea-84ca-99b75171ca12.png)

**Comment by adprov81** [comment]
Error message in bottom-left. Sometimes it occurs in a pop-up message too.

**Comment by jmcphers** [comment]
The most common cause of this problem is antivirus or firewall software blocking the connection between rstudio.exe (the front end) and rsession.exe (the R Session itself). Do you have any such software? If so, does adding an exclusion for RStudio help?

**Comment by adprov81** [comment]
I have Windows 10 and use Windows Defender. How do I add an exclusion for RStudio?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jmcphers** [comment]
Here is a video tutorial:

https://www.youtube.com/watch?v=G9sLSCyOk0s

**Comment by mikebessuille** [comment]
Probably related to https://github.com/rstudio/rstudio/issues/7818
