### ISSUE TITLE
[Website] On RStudio download website HTML code is visible

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#6806]
I'm not sure if this is the right place to report this, but something is wrong with RStudio Preview download website as HTML code is visible:

https://rstudio.com/products/rstudio/download/preview/

![image](https://user-images.githubusercontent.com/12725868/81007033-2b6cb700-8e59-11ea-875f-c62363888717.png)

**Comment by jmcphers** [comment]
Yes, we're aware and should have a fix soon!

**Comment by jmcphers** [comment]
Fixed now.
