### ISSUE TITLE
Please provide a way to open a recent project in a new instance

### ISSUE THREAD

**Issue by tomtom** [rstudio/rstudio#6812]
I have to frequently switch between projects. The recent projects menu replaces the current project with the new one. When switching back and forth between projects, it would be desireable to have a way to open a recent project from within rstudio -- without the help of a file explorer etc.

**Comment by jmcphers** [comment]
You can do this with the projects menu in the upper right:

![image](https://user-images.githubusercontent.com/470418/81234946-b4493700-8fae-11ea-9a77-bd0ebd343644.png)

**Comment by tomtom** [comment]
Thank you very much. I missed that and didn't find this info anywhere in the docs.It probably should be noted more prominently on the help pages about working with projects like https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects
