### ISSUE TITLE
Open recent project doesn't work with Windows shortcuts

### ISSUE THREAD

**Issue by tomtom** [rstudio/rstudio#6813]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows

### Steps to reproduce the problem

1. In the windows file explorer, create a shortcut to a *.Rproj file.
2. Move the file someplace else.
3. In RStudio, select File/Open Project -> select the shortcut

### Describe the problem in detail

Rstudio doesn't do anything.

### Describe the behavior you expected

RStudio should open the project the shortcut/link refers to.
- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tomtom Thank you for raising the issue! At the risk of stating the obvious, does the project open properly when the shortcut is in the original location?

**Comment by R-Hannibal** [comment]
@tomtom - I don't think the behavior you're seeing is a bug necessarily. Just tried opening a project via shortcut where the underlying project file has NOT been moved, and it does not appear to be supported behavior:
![Project_Shortcut_Error_Message](https://user-images.githubusercontent.com/62304541/82471279-1c5a4b80-9a8c-11ea-8c39-feefe52c95e1.PNG)

Additionally, even this baseline behavior does not appear to be supported by all Microsoft software (attempting to open a word doc in word via a shortcut does not work). So I don't think this is a bug.

However, the error message displayed above (which occurs when attempting to open a project via shortcut) should be more user friendly/clear and I will be filing an enhancement request to address this.
