### ISSUE TITLE
Console left, source right: staying 1/3 - 2/3

### ISSUE THREAD

**Issue by arnyeinstein** [rstudio/rstudio#6815]
Hi
I am using the developer version 1.3.957 on WIndows with R 4.0.0.  If I set the console on the left side and the source on the right side, it originally is divided 2/3 and 1/3. It would be great to  be able to set this to 1/3 and 2/3 and let it stay that way.

It would also be great if there is an option to keep the pane in the lower part of the left part could stay minimized. If I hit Ctrl+2 it is shown again. 
Cheers
Renger

**Comment by jmcphers** [comment]
> It would be great to be able to set this to 1/3 and 2/3 and let it stay that way.

You can drag the splitter between the panes to do this, or with a keyboard: View -> Panes -> Adjust Center Splitter.
