### ISSUE TITLE
Custom keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by weitzele** [rstudio/rstudio#6818]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5042
    OS Version      :  Windows 10
    R Version       :  4.0.0

### Steps to reproduce the problem
Run any line of code in an RScript or RMarkdown file such as:
9+9

### Describe the problem in detail
When I opened RStudio yesterday, I tried to run a line of code in an RScript using the custom keyboard shortcut Ctrl+R that I have used for years and set up every time I update, and nothing happened. Clicking the Run button ran the line, so I updated R to 4.0.0 and RStudio to 1.2.5042 and tried again. My custom keyboard shortcut still did not work, even though it clearly displayed Ctrl+R in the shortcut menu next to "Run Current Line or Selection." I uninstalled R and RStudio and tried again, with no luck. I reset my keyboard shortcuts so that the default Ctrl+Enter will run the line. But when I attempt to modify the keyboard shortcut for "Run Current Line or Selection," RStudio will not recognize the Ctrl+R key combination. It will let me set it to Ctrl+A or Ctrl+Enter or other things like Shift+R, but when I type Ctrl+R nothing shows up at all. Looking through all of the keyboard shortcuts, there does not appear to be a conflict.

### Describe the behavior you expected
Ctrl+R should be recognized by RStudio once I set it as a custom keyboard shortcut

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Most likely another program on your system (or the OS) is handling Ctrl + R before RStudio is able to see it and handle it. Have you installed or updated any software on your machine recently?

**Comment by weitzele** [comment]
Kevin, you solved it! The culprit is TinyTake by MangoApps, which I had recently installed. I just uninstalled it, and RStudio allowed me to use Ctrl+R. Then to test things, I reinstalled TinyTake and Ctrl+R broke again. So now, with that software uninstalled, everything works as it should. Thanks!

**Comment by kevinushey** [comment]
Great, I'm glad to hear it!
