### ISSUE TITLE
Debian GNU/Linux 10 post install verification error on 1.3.957

### ISSUE THREAD

**Issue by tmcduff** [rstudio/rstudio#6822]
RStudio Edition : Open 
RStudio Version : 1.3.957
OS Version      : Debian GNU/Linux 10
R Version       : 3.5.2

I don't often do installs with this combination, so I don't have any solid work around steps if this is indeed configuration related. I don't see that the install created (/home/rstudio-server/)

Install seems to succeed, but error is detected on verify-installation. 

 **sudo rstudio-server verify-installation** 

"06 May 2020 20:05:11 [rsession-rstudio-server] ERROR system error 13 (Permission denied) [path: /home/rstudio-server/.config/rstudio, target-dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) const src/cpp/shared_core/FilePath.cpp:634; LOGGED FROM: rstudio::core::Error rstudio::session::prefs::initializePrefs() src/cpp/session/prefs/UserPrefs.cpp:142
06 May 2020 20:05:11 [rsession-rstudio-server] ERROR system error 13 (Permission denied) [path: /home/rstudio-server/.config/rstudio/dictionaries/custom, target-dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) const src/cpp/shared_core/FilePath.cpp:634; LOGGED FROM: rstudio::core::Error rstudio::core::spelling::HunspellDictionaryManager::availableLanguages(std::vector<rstudio::core::spelling::HunspellDictionary>*) const src/cpp/core/spelling/HunspellDictionaryManager.cpp:158
06 May 2020 20:05:11 [rsession-rstudio-server] ERROR system error 13 (Permission denied) [path: /home/rstudio-server/.config/rstudio/dictionaries/custom, target-dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) const src/cpp/shared_core/FilePath.cpp:634; LOGGED FROM: std::vector<std::__cxx11::basic_string<char> > rstudio::core::spelling::HunspellCustomDictionaries::dictionaries() const src/cpp/core/spelling/HunspellCu

**Comment by osallou** [comment]
my 2 cents, seems debian package creates a user *rstudio-server* but does not seem to create user home dir (/home/rstudio-server). So either error is because user homedir does not exists, or a chown is missing.

**Comment by kevinushey** [comment]
I suspect @osallou is correct. What is the output of `$(whoami)` when you're running this -- are you running as your own user account, or as `rstudio-server`?

**Comment by tmcduff** [comment]
Recommend closing. second attempt was successful. unknown why the /home/rstudio-server was referenced.
