### ISSUE TITLE
Modifying the chunk options by mouse may delete chunk options

### ISSUE THREAD

**Issue by jarauh** [rstudio/rstudio#6829]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Open a new "R Markdown" file.
2. In the plot example (chunk `pressure`), add a chunk option `fig.cap = "a caption"`.
3. Click on the "chunk option gear icon".
4. Select "Use custom figure size". Then deselect it again.

### Describe the problem in detail

The chunk option `fig.cap = "a caption"` is mutilated.

### Describe the behavior you expected

The chunk option `fig.cap = "a caption"` is preserved.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Thank you @jarauh for raising this issue. We'll have the dev team look at it and try to address it in a future release.

**Comment by kevinushey** [comment]
Verified fixed in RStudio 2024.10.0 Build 192 on macOS.
