### ISSUE TITLE
Editor incorrectly handles wide unicode characters

### ISSUE THREAD

**Issue by johncolby** [rstudio/rstudio#6836]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : MacOS 10.15.4 
    R Version       : 3.6.2

### Steps to reproduce the problem

Open a new document in the IDE editor. Insert a wide unicode character. Edit any subsequent code.

### Describe the problem in detail

Text insertion will be wrong (i.e. offset the extra width) with respect to the apparent cursor position. See the attached screenshot (RStudio on left, Sublime Text on right). First, look at the cursor position. In RStudio, it is incorrectly placed in the middle of the brain. Second, when I edited subsequent text in RStudio, attempting to write TEXT in the middle of xxxx (i.e. xxTEXTxx), RStudio thinks it is doing so, but the text is actually inserted in the wrong spot (see Sublime on the right). I am not sure, but this may be related to issue #3698.

<img width="350" alt="Screen Shot 2020-05-07 at 3 58 55 PM" src="https://user-images.githubusercontent.com/473295/81352547-b2997500-907b-11ea-99f8-aa72a67e0be3.png">

### Describe the behavior you expected

Text will be inserted at the correct position.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jonaskn** [comment]
Just wanted to confirm this issue. Took me an hour to figure out it was a unicode character in the script throwing everything off. The parser shows errors on the code (because code was inserted to the wrong location), but the code shown in the editor looks correct until you close or reopen the file (or use Sublime Text).

**Comment by ronblum** [comment]
@johncolby Thank you for filing the issue! Could you please provide the code snippet you're using, including the brain? This will help us try to reproduce the issue as closely to your steps as possible. Thanks!

@jonaskn You can also show you're running into the issue by adding a thumbs-up at the top. We use these to help identify the impact of bugs and enhancements.

**Comment by johncolby** [comment]
1. Open any text document in the editor. For example:
    ```
    x = ''
    
    x = 'xxxx'
    ```
1. Paste in a wide unicode character (such as 🧠).
1. Edit any subsequent text.
1. Save and close/reopen (or view in another editor such as Sublime).
1. You will see your edits have been inserted at the wrong location, even though they appeared to be in the correct location in the editor (see initial screenshot, above).

**Comment by kevinushey** [comment]
This is now handled correctly in the latest versions of Ace:

https://ace.c9.io/build/kitchen-sink.html

so perhaps we'll be able to fix this by taking an Ace update.

**Comment by ronblum** [comment]
Note: Added `triage` tag, for consideration in Spotted Wakerobin. This, or something similar, just came up in #10639.

**Comment by gtritchie** [comment]
This is working in current releases of RStudio (and back several versions, though I didn't try to identify the first version with the fixes). We've updated Ace a few times since this issue was opened, which is what fixed it.
