### ISSUE TITLE
RStudio crashed if plot zoom window is closed with Alt+F4

### ISSUE THREAD

**Issue by dkondor** [rstudio/rstudio#6837]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Plot anything
e.g. plot(c(1,2,3),c(4,5,6))
2. Click on 'zoom'
(plot zoom window appears)
3. Close zoom window with Alt+F4

### Describe the problem in detail
RStudio crashes. It only happens if closing the window with Alt+F4, not with other ways (e.g. Ctrl+W or clicking the close button in the window title bar)

### Describe the behavior you expected
Plot zoom window closes. (If Alt+F4 is interpreted as a quit request for RStudio, then normal quit behavior, e.g. asking if to save files)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4597080/diagnostics-report.txt)
[rstudio-backtrace.txt](https://github.com/rstudio/rstudio/files/4597081/rstudio-backtrace.txt)

**Comment by ronblum** [comment]
@dkondor Thank you for raising the issue. I can't reproduce it with both 1.2 and the 1.3 preview, though. Just to rule out something obvious, what workspace are you using? I'm on kubuntu KDE Plasma. Thanks!

**Comment by ronblum** [comment]
@dkondor Also, does this happen only with the Plots pane, or does it also occur if you pop out a file in the Source Editor pane?

**Comment by dkondor** [comment]
Hi, I just tested, it actually only happens with the compiz window manager. I've tested under metacity and openbox additionally and it works fine under those.

**Comment by dkondor** [comment]
Hi, I downloaded and compiled rstudio from source (debug build) and cannot reproduce this in that case at all, only happens with the packaged version (1.2.5042). I'll report back if I find a way to reproduce this.

**Comment by ronblum** [comment]
@dkondor Thank you for investigating further! FWIW, the packaged version of 1.3.1056 for Ubuntu 18 is available at https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.1056-amd64.deb (linked from https://rstudio.com/products/rstudio/download/#download ).

**Comment by dkondor** [comment]
As I mentioned, I cannot reproduce this on newer versions, so I think it is fine to close this.
