### ISSUE TITLE
Data Viewer slow on wide data.table format 

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#6839]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : 1.2.5042
    OS Version      :  MacOS 10.15.4
    R Version       : 3.6.3

### Steps to reproduce the problem

My data contains strings and numerics, 2.4 million rows and 280 columns. 

### Describe the problem in detail

I've encountered the same problem described #1771 (closed issue now) with data.table format. 

I checked that once I convert the data into with data.frame (using `setDF(data)`) the Viewer opens snappy and works nicely. 
However with data.table format it becomes extraordinarily slow and I had to shut down RStudio quite often. I'm wondering if the above fix was not applied to `data.table`

**Comment by ronblum** [comment]
@mattgrogan Thank you for raising this. If I understand correctly, the dataset contains 672 million cells in 280 columns? I'm trying to reproduce this, perhaps overdoing it given the examples in #1771, but I tried the following with integers:
```
library(data.table)
x <- matrix(1:6.72e8, ncol = 280)
xdt <- data.table(x)
xdf <- data.frame(xdt)
xsetdf <- setDF(xdt)
View(x)
View(xdt)
View(xdf)
View(xsetdf)
```
In all cases, the data eventually appeared in the Data Viewer after a long time (under a minute). I might not be properly replicating what you're running into, though, since `setDF()` took a while, too. Would you be able to provide an example we can use to reproduce the problem? Thanks!

**Comment by mattgrogan** [comment]
Not for me, it's @matthewgson :)

Good luck!

**Comment by matthewgson** [comment]
@ronblum Thanks for the response. My data has 2.4M rows and 280 cols, so yes it would contain 2.4M*280= 672M cells. 

I made a replication like below. `system.time()` did not capture the real processing time `View()` took, but still gives a rough snapshot. 

```
d = data.frame(replicate(280,sample(0:200,2.4e6,rep=TRUE)))
d[,1:140] = lapply(d[,1:140], as.character)
class(d) # "data.frame"
library(data.table)
system.time(View(d))
  #  user  system elapsed 
  # 0.002   0.003   0.005 
setDT(d)
class(d) #[1] "data.table" "data.frame"
system.time(View(d))
 #   user  system elapsed 
 # 12.820   6.336  20.346 

# it took a lot longer than data.frame in real processing time

setDF(d)
class(d) #[1] "data.frame"

system.time(View(d))  # check once again
  #  user  system elapsed 
  # 0.002   0.000   0.003 


```

Above sample did not take too much time compared to my original data actually. Possibly because my original one has a lot longer character vectors.  My original one took literally more than 20 mins to view and I had to terminate the session because R session interrupt did not work. I was surprised it was a lot faster with `data.frame` class.

**Comment by ronblum** [comment]
@matthewgson Thank you! I can reproduce this.

@kevinushey Do you have any thoughts or next steps, regarding the difference between data.table and data.frame?

**Comment by kevinushey** [comment]
We'd ultimately just have to investigate whether:

1. We can avoid coercing `data.table` objects to `data.frame`, and
2. Whether we can use `data.table`-friendly APIs to subset and use `data.table`s instead of coercing to `data.frame`.
