### ISSUE TITLE
`file.edit()` in RStudio fails to recongize modified "~"'s path

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#6840]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.244 (not the very latest but it should still be reproducible)
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : 4.0.0 (2020-04-24)

### Steps to reproduce the problem

Assume you install R under folder `D:\app\R-4.0.0`

- Create a file named "Renviron.site" under `D:\app\R-4.0.0\etc`
- Add a line `R_USER = "D:/R"` into the new file "Renviron.site" so that the path of "~" is changed
- Run `file.edit("~/test1.txt")` **without** RStudio IDE, you will see a new file "test1.txt" created under folder "D:/R"
- Run `file.edit("~/test2.txt")` **inside of** RStudio IDE, you will find the new file "test2.txt" is not created under folder "D:/R". Instead, it gets created in "C:/Users/you-user/Document", i.e., the default "~" path.

It means, somehow, RStudio IDE doesn't  repect "Renviron.site" any longer. The previous RStudio IDE repects this (maybe before version 1.2.XXX ?) and have the same behavior as if executing the command in R itself.

### Describe the problem in detail

The steps above has described the problem in detail.

### Describe the behavior you expected

`file.edit()` should use the user-defined "~" path.

**Comment by jmcphers** [comment]
What does `path.expand("~/test2.txt")` return inside RStudio for you?

**Comment by shrektan** [comment]
![image](https://user-images.githubusercontent.com/8368933/81632225-55674000-943c-11ea-99ff-dbac6bd9d0bd.png)
