### ISSUE TITLE
Disable automatic unfolding of a block when executing it.

### ISSUE THREAD

**Issue by skanskan** [rstudio/rstudio#6842]
Hello.

When I write many lines of code I like to fold different blocks to keep it easily readable.
I only leave unfolded the sections I'm working on at that moment.
I know I can also split the code on different files, I'm also doing it.

But there is a problem, when I execute previous folded blocks they automatically get unfolded and I need to go back and fold them again.

Could you please add the option to disable automatic unfolding, please?
It would be great if we could also view the block folded on the REPL, instead of expand it.

**Comment by ronblum** [comment]
@skanskan Thank you for raising this! I would like to try to reproduce this. I realize this isn't especially complicated, but could you provide the following information?

1. A simple example of code you use, so that I can do the folding, executing, etc. with the same code as yours?
2. Also, the following information, so that I can try it out in the same environment?
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

Thank you!

**Comment by skanskan** [comment]
RStudio Edition : Desktop
RStudio Version : 1.3.571
OS Version      :  Windows 10 x64 Pro 18362
R Version       :  3.6.2

Hello @ronblum 

Any example is OK. I will provide a code with three blocks.
The first one is quite common, loading libraries. I have just specified ggplot2.
Then a simple code to calculate a Fibonacci numbers.
And a code to compare several simple regressions.

Imagine I want to have the first two blocks always folded.


```
####  Load libraries ###

# Any libraries...
library(ggplot2)

### End libraries

####  Recursive Fibonacci sequence up to n-th term ####
recurse_fibonacci <- function(n) {
if(n <= 1) {
return(n)
} else {
return(recurse_fibonacci(n-1) + recurse_fibonacci(n-2))
}
}
# take input from the user
nterms = as.integer(readline(prompt="How many terms? "))
# check if the number of terms is valid
if(nterms <= 0) {
print("Plese enter a positive integer")
} else {
print("Fibonacci sequence:")
for(i in 0:(nterms-1)) {
print(recurse_fibonacci(i))
}
}


####  End Fibonacci ####


recurse_fibonacci(30)



### Plots  ####


xx1 <- runif(25,0,300)
xx2 <- runif(25,0,300)
yy1 <- 50+0.5*xx1+rnorm(25,0,3)
yy2 <- 0-0.5*xx2+rnorm(25,0,30)

#datos1 <- data.frame(xx1,yy1, xx2,yy2)
datos <-  data.frame(xx=c(xx1,xx2),yy=c(yy1,yy2),zz=factor(c(rep(0,25),rep(1,25))))

ajuste1 <- lm(yy~xx, data=subset(datos,zz==0))
ajuste2 <- lm(yy~xx, data=subset(datos,zz==1))
ajuste3 <- lm(yy~xx+xx:zz, data=datos)  #mismo ao
ajuste4 <- lm(yy~xx*zz, data=datos)   #cambia todo
#ajuste5 <- lm(yy~xx+zz, data=datos)  # misma pendiente

# dos por separado
plot(datos$xx,datos$yy)
  abline(a=coef(ajuste1)[1],b=coef(ajuste1)[2],col= "red", lty=2)
  abline(a=coef(ajuste2)[1],b=coef(ajuste2)[2],col= "red", lty=2)

# mismo intercepto diferente pediente
#  plot(datos$xx,datos$yy)
  abline(a=coef(ajuste3)[1],b=coef(ajuste3)[2],col= "blue")
  abline(a=coef(ajuste3)[1],b=(coef(ajuste3)[2]+coef(ajuste3)[3]),col= "blue")

# diferente intercepto diferente pendiente.  Coincide con el "por separado"
#  plot(datos$xx,datos$yy)
  abline(a=coef(ajuste4)[1],b=coef(ajuste4)[2],col= "green")
  abline(a=(coef(ajuste4)[1]+coef(ajuste4)[3]),b=(coef(ajuste4)[2]+coef(ajuste4)[4]),col= "green")

  
#### End Plots ####
```
