### ISSUE TITLE
can't access help for "while" via console

### ISSUE THREAD

**Issue by drammock** [rstudio/rstudio#6843]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      :  Xubuntu 18.04
    R Version       : 3.6.3

### Steps to reproduce the problem
type `?while` in the RStudio console and press `escape` (to disable the popup suggestion for snippets, etc, and then press `enter`.

### Describe the problem in detail
instead of showing the help documentation for "control flow", a `+++` continuation line is shown.

### Describe the behavior you expected

Should bring up the help docs for "control flow"

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is true in a plain R console (outside of RStudio) as well.

**Comment by drammock** [comment]
> This is true in a plain R console (outside of RStudio) as well

oops.  Sorry for not testing that before filing the bug report.
