### ISSUE TITLE
raw strings reported as non-syntactic under R 4.0.x

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#6845]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.324
    OS Version      : macOS Mojave
    R Version       : 4.0.0

### Steps to reproduce the problem

```
x = r"(
blah blah
)"
```

### Describe the problem in detail

<img width="175" alt="Screenshot 2020-05-10 at 2 21 44 PM" src="https://user-images.githubusercontent.com/7606389/81492368-97bc4000-92c9-11ea-92f0-d3012fed084a.png">

### Describe the behavior you expected

As we all know (and love!) R 4.0.0 supports raw strings like this; it just appears that the RStudio linter is not yet up to date.

I figured this would be in the issue tracker already but it appears not.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@MichaelChirico Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.3.957 on MacOS 10.15.5. We'll review it as we continue development of RStudio.
