### ISSUE TITLE
some system command dont return output 

### ISSUE THREAD

**Issue by VictorYammouni** [rstudio/rstudio#6856]
Hello

I use commands "segrace" and "sepass" for managing passwords on Linux platform. These commands are part of "ETRUST" (Computer Associate). 

Usually, these commands produce outputs. For example, segrace -d 9999 gives the number of days before changing your password. Example :

segrace -d 9999

a831059's password should be changed in 56 day(s)
according to user's password interval (every 63 days)

If i execute this command with system() function under R GUI, it works fine

But under RStudio Server, this command produce no output. If i use intern=TRUE parameter, i got character(0)

Even under "Tools > Terminal" or Shell, there is no output

Do you have any idea?

Thank's

**Comment by ronblum** [comment]
@VictorYammouni Thank you for your question. I'll mark this for review as we continue development of RStudio. In the meantime, can you please provide the following information?
1) System details
    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 
2) Are other `system()` commands working as expected? E.g.
```
> system("echo 1")
1
```

**Comment by VictorYammouni** [comment]
RStudio Edition : RStudio Server Free For Redhat
Rstudio Version : 1.2.5001
OS Version : Red Hat Enterprise Linux Server release 7.7 (Maipo)
R Version : 3.5.3 (2019-03-11)

All other Linux commands work fine with system() function

![image](https://user-images.githubusercontent.com/34738798/81793445-aabd5300-9509-11ea-8059-9dc387ee7cb4.png)


Regards

**Comment by VictorYammouni** [comment]
Hello again

I got the same issue on an other server. The caracteristics of this server are:

RStudio Edition : RStudio Server Free For Redhat
Rstudio Version : 099.903
OS Version : Red Hat Enterprise Linux Server release 7.7 (Maipo)
R Version : 3.3.0 (2016-05-03)


Regards

**Comment by VictorYammouni** [comment]
Hello

It seems that the problem is probably due to Etrust. We will look for the reason with the admins


Regards

**Comment by ab2dridi** [comment]
Hello, we are still facing the same issue, is there a solution for this ?
