### ISSUE TITLE
"Missing Value" shown on sign-in page

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6859]
### System details

    RStudio Edition : Server
    RStudio Version : master
    OS Version      : macOS (dev server)
    R Version       : 4.0.0

### Steps to reproduce the problem
- Build master at 2cd1b38201914c81218938f72ab4ad6d81215436
- Run open-source dev-server
- Load in browser

### Describe the problem in detail
- Sign in page has "MISSING VALUE MISSING VALUE" in upper-right corner

### Describe the behavior you expected
- No "MISSING VALUE"

<img width="694" alt="screenshot of sign-in screen demonstrating issue" src="https://user-images.githubusercontent.com/10569626/81747975-e864a200-945d-11ea-9105-e265b819916c.png">

**Comment by ricardofandrade** [comment]
This issue has been fixed on https://github.com/rstudio/rstudio/commit/b00c1be52e52ecf366932367061b0d715cdd003a
