### ISSUE TITLE
patched nerdfonts not displaying correctly

### ISSUE THREAD

**Issue by tomjemmett** [rstudio/rstudio#6864]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.958 (also tested with 1.2.5042)
    OS Version      : Windows 10 Pro 1903
    R Version       : 3.6.3 (also tested with 4.0.0)

### Describe the problem in detail

I'm using the patched [Fura Code nerdfont](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode) and some of the icons do not appear correctly in RStudio.

In particular, "<<" looks like " <" and "<<-" looks like " <-", both are quite confusing. Some of the icons when library'ing tidyverse don't look correct.

![Rstudio-nf-issue](https://user-images.githubusercontent.com/12023696/81788201-10a1de80-94fa-11ea-92e1-90ff459216d5.PNG)

### Describe the behavior you expected

Here is a screenshot of that same code pasted into Windows Terminal, with the same font:

![Windows-Terminal](https://user-images.githubusercontent.com/12023696/81788107-ecde9880-94f9-11ea-8262-5697ed4489f7.jpg)

comparing the two screen shots, the Windows Terminal also joins up the "---" on the tidyverse lines, whereas RStudio does not.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tomjemmett Thank you for raising the issue! Can you please paste in a copy of the code? I want to make sure that we're using the exact same code when trying to reproduce this.

**Comment by tomjemmett** [comment]
@ronblum here is what I used in the example screenshots above:
```r
library(tidyverse)
cat("
<   single '<' character
<<  two '<' characters, should show two icons
<-  a '<' followed by a '-', displaying correctly
<<- two '<' followed by a '-', displaying incorrectly
")
```

here's my current session info, I've tried this with a couple of themes with the same results.
```r
> rstudioapi::getThemeInfo()
$editor
[1] "Ambiance"

$global
[1] "Modern"

$dark
[1] TRUE

$foreground
[1] "rgb(230, 225, 220)"

$background
[1] "rgb(32, 32, 32)"
```
```r
> rstudioapi::versionInfo()
$citation

To cite RStudio in publications use:

  RStudio Team (2020). RStudio: Integrated Development Environment
  for R. RStudio, PBC, Boston, MA URL http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, PBC},
    address = {Boston, MA},
    year = {2020},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] '1.3.958'

$release_name
[1] "Middlemist Red"
```
```r
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.0  htmltools_0.4.0 tools_4.0.0     yaml_2.2.1     
 [5] Rcpp_1.0.4.6    rmarkdown_2.1   knitr_1.28      xfun_0.13      
 [9] digest_0.6.25   rlang_0.4.6     evaluate_0.14  
```

**Comment by R-Hannibal** [comment]
Thanks for providing the code and session info @tomjemmett, that will make this issue much easier for our development team to work with. We'll send this issue on to them and look to address it during our ongoing development of RStudio.

**Comment by jmcphers** [comment]
We can't offer support for all 3rd party fonts and I suspect this is mostly a font issue as Fira Code ligatures work correctly. 

Can you open your theme's CSS and/or devtools (right click -> inspect element) and see if adding this rule fixes it?

```css
.ace_editor {
   text-rendering: optimizeLegibility;
}
```

**Comment by tomjemmett** [comment]
Just installed regular Fira Code and ligatures work fine - it's just the patched version with Nerd Fonts that doesn't seem to be behaving. I tried adding in the `text-rendering: optimizeLegibility` option and this didn't help.
