### ISSUE TITLE
Default Open Docs don't work

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#6865]
### System details
    RStudio Version : 1.3.x/1.4.x

### Steps to reproduce the problem

Load a new project that has `DefaultOpenDocs`. Notice that the listed documents do not show up in the source pane.

**Comment by dfalty** [comment]
Verified fixed 1.3.1031. 
I was able to manually create a testproject.Rproj file with the following and it open just fine as expected with whatever default docs I select in the source pane.
```
Version: 1.0
DefaultOpenDocs: welcome.txt
```
