### ISSUE TITLE
previewRd doesn't allow Rd macros to be loaded

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#6871]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      :  MacOS 10.13.6
    R Version       :  4.0.0

### Steps to reproduce the problem

Check out the `mathjaxr` package https://github.com/wviechtb/mathjaxr into a new project.  Navigate to the `man` directory, and preview `mathjaxr-package.Rd`.

### Describe the problem in detail

That package provides Rd macros to allow MathJax to be displayed in Rd help pages, and that page includes an example of it.  However, MathJax is not displayed, because the macros aren't processed.

### Describe the behavior you expected

If you run `?mathjaxr::mathjaxr`, the help page is properly displayed, showing the normal density function in the Examples section.

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

The issue appears to be that the RStudio api function `previewRd` doesn't accept an argument listing packages from which it should load Rd macros.  The `pkgload::print.dev_Topic` function is called before `previewRd`, and it correctly determines the macros to load, but doesn't pass them to `previewRd`, which only accepts one parameter, not two.

The C++ code in `src/cpp/session/modules/SessionHelp.cpp` calls `R CMD RdConv` to produce the preview; that command takes an optional argument `--RdMacros=pkglist`, which could be set to `--RdMacros=mathjaxr` to get a correct rending of the preview.

**Comment by dmurdoch** [comment]
Hadley's https://github.com/rstudio/rstudio/issues/5994 enhancement would make this easier to solve, because the `macros` object could just be passed to the API function and not need to be put on the `R CMD RdConv` command line.

**Comment by R-Hannibal** [comment]
Thank you so much @dmurdoch for raising this issue and for all the detail and follow up you put into the issue report. 

We'll mark this ticket for review as we continue development of RStudio.

**Comment by kevinushey** [comment]
I'm taking a look at this now. One issue is that the attempt to load MathJax fails in the Rd preview, as the relative MathJax load path no longer resolves in the right place.

By default, MathJax is loaded from a URL with:

```
src="../../mathjaxr/doc/mathjax/es5/tex-chtml-full.js"
```

The regular R help server (within RStudio) forms URLs as e.g.

```
src="http://127.0.0.1:26090/help/library/mathjaxr/html/mathjaxr-package.html"
```

and so this works fine. However, for previews, we use a different endpoint; e.g.

```
src="http://127.0.0.1:26090/help/preview?file=~%2Fr%2Fpkg%2Fmathjaxr%2Fman%2Fmathjaxr-package.Rd"
```

And this breaks resolution of `mathjaxr`'s local MathJax.

I'm not sure if there's a clean way to resolve this, beyond having RStudio form a preview URL that better mimics the format of the R help server. One solution is to use `Sys.setenv(MATHJAXR_USECDN = "true")` to avoid this issue, at least.
