### ISSUE TITLE
Add ability to remove local jobs based on job status

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/rstudio#6872]
Hi,

I was wondering if it would be a worthwhile minor feature to change the "broom" function in the `Jobs` tab to be able to separately clear jobs based on job status (i.e., whether they `Failed`, `Succeeded`, or `Remove All Completed Jobs`). Just a thought!

**Comment by ronblum** [comment]
@mattwarkentin Thank you for the suggestion! We'll review it as we continue development of RStudio.
