### ISSUE TITLE
Unavailable commands in command palette throw exception but nothing user-visible

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6874]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.337
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- open IDE in default configuration, no project
- Ctrl+Shift+P, type "restore"
- Select "Restore your project library from renv.lock"

### Describe the problem in detail
- Javascript exception:
```
14 May 2020 17:35:43 [rserver] ERROR CLIENT EXCEPTION (rsession-gary): AppCommand executed but nobody was listening: renvRestore;
rstudio-0.js@10#639::Throwable.createError
rstudio-0.js@48#703::Throwable.initializeBackingError
rstudio-0.js@8#546::Throwable.Throwable
rstudio-0.js@18#2279::Error.Error
rstudio-0.js@14#2342::AssertionError
rstudio-0.js@10#2116::makeAssertionError_Object
rstudio-0.js@23#115536::AppCommand.doExecute
rstudio-0.js@8#115547::AppCommand.execute
rstudio-0.js@22#186793::AppCommandPaletteEntry.invoke
...
```

### Describe the behavior you expected
Commands like this should either be hidden when unavailable, or at very least a message should be shown to user that "This command can't be executed right now".

When these are found, file issues on them and disable commands or groups of commands that are enabled when they shouldn't be. Also a problem if keyboard shortcuts are assigned.

**Comment by dfalty** [comment]
Verified the new functionality when commands can't be used on version 1.4.874
![image](https://user-images.githubusercontent.com/15237845/94373179-4f12f100-00c9-11eb-9fbf-ae667a1e1d82.png)
