### ISSUE TITLE
Unicode Characters do not Show Up correctly in Environment Viewer

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#6877]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem

1. `foo <- readLines(con="c:/tmp/c.txt", encoding="UTF-8")` (see attached file which is only the character `č` and a newline).  [c.txt](https://github.com/rstudio/rstudio/files/4634931/c.txt)
2. Look at the Environment pane and see a regular and not accented "c".
3. This may be locale-dependent, in which case, my locale is just below this list

```
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252   
```

### Describe the problem in detail

The environment pane does not show the correct content.  The actual character stored in the variable is Unicode and accented while the character shown is unaccented.

![image](https://user-images.githubusercontent.com/10359931/82061952-5fd14600-9697-11ea-9d64-c134954b2bf8.png)

### Describe the behavior you expected

I expected to see `foo | "č"` in the environment viewer.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

(Related to sfirke/janitor#376)

**Comment by kevinushey** [comment]
This is caused by R's format method:

```
> text <- intToUtf8(269L)
> text
[1] "č"
> format(text)
[1] "c"
```

which we use when formatting text for display in the Environment pane. We could probably avoid using `format()` for character vectors, and instead just use the string as-is.

**Comment by R-Hannibal** [comment]
@billdenney, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by billdenney** [comment]
@R-Hannibal, I will try to test it, but it may take some time as the simplest way to test it is on my normal, daily-use laptop.  Is it possible to keep my normal Rstudio installation and load the development copy temporarily (maybe with the installer-less build)?

**Comment by billdenney** [comment]
I just thought of the fact that I have another laptop that I could test it on.  It works for me.  Thanks!

**Comment by calpan** [comment]
In the latest daily build (875), raw character strings show up correctly, but character columns in data frames do not.

```
d = data.frame(xi='ξ')
```

![rstudio_2020-09-27_21-43-48](https://user-images.githubusercontent.com/806424/94391566-aab19e80-010a-11eb-91cc-c6f2e919e405.png)
