### ISSUE TITLE
Custom string representations in paged_table output

### ISSUE THREAD

**Issue by markromanmiller** [rstudio/rstudio#6878]
I'm trying to make a package that specifies a custom `vctrs`-based data type. Part of its behavior is to be easily readable as part of a data.frame or tibble when working in the interactive portion of an RMarkdown document, the primary part of my workflow. I was able to achieve that fairly quickly using the `format` method. This is good when the vector is printed by itself, or the table is rendered in the console. However, that is not the case in chunk output rendered interactively (with ctrl+enter).

If I am correct (and I may not be) `rmarkdown::paged_table` is the way data frames are rendered below R chunks when working interactively. I thought the rendering would involve some call to `print` or `format` or some related method, but it does not. When rendered, all my custom objects are stuck with the uninformative name <S3: vrm_vector3>.

**I'd like to be able to specify a string rather than <S3: vrm_vector3>?**

As a quick fix, I thought I could approach this by changing some part of the process in the rmarkdown library and then reinstall it, but rstudio seems to use its own install of rmarkdown.

The reprex is below.

````
---
title: "sample_reprex"
author: "Mark Roman Miller"
date: "5/13/2020"
output: html_document
---

```{r}
library(tidyverse)
library(tibble)
library(vctrs)
library(zeallot)

new_vector3 <- function(x=double(), y=double(), z=double()) {
  vec_assert(x, ptype=double())
  vec_assert(y, ptype=double())
  vec_assert(z, ptype=double())
  new_rcrd(list(x=x, y=y, z=z), class="vrm_vector3")
}

vector3 <- function(x, y, z) {
  c(x, y, z) %<-% vec_cast_common(x, y, z, .to=double())
  c(x, y, z) %<-% vec_recycle_common(x, y, z)
  new_vector3(x, y, z)
}

format.vrm_vector3 <- function(v, ...) {
  x <- field(v, "x")
  y <- field(v, "y")
  z <- field(v, "z")

  out <- paste0("(", x, ", ", y, ", ", z, ")")
  out[is.na(x) | is.na(y) | is.na(z)] <- NA

  out
}

vec_ptype_abbr.vrm_vector3 <- function(x, ...) {
  "vector3"
}

sqrt_1_3 <- sqrt(1/3)

sample_table <- tibble(pos = vector3(c(1, 0, 0, sqrt_1_3), c(0, 1, 0, sqrt_1_3), c(0, 0, 1, sqrt_1_3)))

sample_table
```
````

```
> xfun::session_info('rmarkdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS, RStudio 1.2.5042
Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
  LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3 digest_0.6.25   evaluate_0.14   glue_1.4.1      graphics_3.6.3  grDevices_3.6.3
  highr_0.8       htmltools_0.4.0 jsonlite_1.6.1  knitr_1.28      magrittr_1.5    markdown_1.1   
  methods_3.6.3   mime_0.9        Rcpp_1.0.4.6    rlang_0.4.6     rmarkdown_2.1.3 stats_3.6.3    
  stringi_1.4.6   stringr_1.4.0   tinytex_0.22    tools_3.6.3     utils_3.6.3     xfun_0.13      
  yaml_2.2.1     

Pandoc version: 2.3.1
```
This is a cross-post from https://github.com/rstudio/rmarkdown/issues/1822 where it was suggested to post here in rstudio.

**Comment by R-Hannibal** [comment]
Thanks for raising the issue @MrMallIronmaker . We'll take a look at this.

**Comment by jmcphers** [comment]
RStudio has its own built-in renderer for notebook (interactive) tables, which indeed does not run very much R code but displays most values natively. I'll mark this as an enhancement to use some R methods that could be overridden.

One thing you might try is overriding `as.data.frame` for your object -- we _do_ call that. You could convert your custom types to their preferred representation in that step.

https://github.com/rstudio/rstudio/blob/f4b2fccb51eff9d5ce6f762f559783eebdc53a73/src/cpp/session/modules/NotebookData.R#L88

Would that do what you want?

**Comment by MrMallIronmaker** [comment]
I've given it a quick test and wasn't able to get it to work, but I'm pressed for time at the moment - I'll come back to it.

If I understand correctly, `x` in this line is the whole table you're printing, right? I'd like to avoid changing how the overarching table renders, but rather how the individual column renders. My object is just a column in that data table.

**Comment by davidchall** [comment]
I just ran into this issue myself and tried to understand what the RStudio code is doing in the background based on @jmcphers link above. Here's what I _think_ is happening:

New vector classes based on [`vctrs::new_rcrd()`](https://vctrs.r-lib.org/reference/new_rcrd.html) or [`vctrs::new_list_of()`](https://vctrs.r-lib.org/reference/new_list_of.html) will return `is.list(x) = TRUE`. Then, RStudio will replace these table cells with an object summary like `<S3: vctrs_class>`.

https://github.com/rstudio/rstudio/blob/f4b2fccb51eff9d5ce6f762f559783eebdc53a73/src/cpp/session/modules/NotebookData.R#L296-L300

A good example is the [blob](https://blob.tidyverse.org/reference/blob.html) vector class. This class is based on `vctrs::new_list_of()` and so RStudio formats this column as `<S3: blob>` even though its own `format()` method returns strings like `blob[X B]`.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1804856/89473447-b5b60700-d737-11ea-9a9a-f8f093b77d37.png">

Perhaps the easiest solution is to be more selective when overwriting columns (L296 above), so RStudio doesn't overwrite vctrs-based classes. Then their `format()` methods will automatically get called [here](https://github.com/rstudio/rstudio/blob/f4b2fccb51eff9d5ce6f762f559783eebdc53a73/src/cpp/session/modules/NotebookData.R#L322).

**Comment by mitchelloharawild** [comment]
Still an issue that would be nice to resolve.

**Comment by davidchall** [comment]
Agreed - I'm still watching this issue 👍

**Comment by mjskay** [comment]
This is still an issue --- we see it with the `posterior::rvar` data type as well, and resolving it would make workflows with that datatype much more useful in notebooks in RStudio. Thanks!

**Comment by MrMallIronmaker** [comment]
I followed up on davidchall 's tracking down of the problem and I was able to produce the desired behavior. Now my question is how to determine which vectors should get this special treatment.

I did notice that each vector that has explicitly been mentioned (`dddr::vector3`, `posterior::rvar`, and `blob::blob`) is derived from vctrs, so checking for class "vctrs_vctr" may work well. This makes sense as vctrs seems to be the tool of choice when package developers are looking to define custom behavior for a vector but still let users expect the type to work like other vectors.

I would like other suggestions, too - especially if @mitchelloharawild is not using vctrs and can recall what he had in mind.

**Comment by mjskay** [comment]
FWIW @mitchelloharawild's {distributional} package also uses vctrs

**Comment by mitchelloharawild** [comment]
I missed these mentions, but was brought back here by https://github.com/tidyverts/fable/issues/376
This is a very common problem for me when teaching forecasting to my students in R Markdown with RStudio. I show our students how to disable inline chunk output because of this.
I think that checking for the `vctrs_vctr` class and then using the `format()` method for the variable should work fine.

**Comment by mitchelloharawild** [comment]
Yes, looks like a fairly minor review.
I don't think using `obj_sum()` methods is the way to go here though, I would prefer the `format()` method to be used.

``` r
dist <- distributional::dist_normal()
tibble::obj_sum(dist)
#> [1] "dist [1]"
format(dist)
#> [1] "N(0, 1)"
```

<sup>Created on 2022-10-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by davidchall** [comment]
@mitchelloharawild - I think the PR is using the class's `format()` method. It only uses `obj_sum()` if the class hierarchy doesn't provide a `format()` method.

**Comment by mitchelloharawild** [comment]
Ah, great. Thanks!

**Comment by davidchall** [comment]
I've reopened the PR, with some simplifications. If anyone here has time to build and test the modified RStudio, this might help get the PR approved.

**Comment by mitchelloharawild** [comment]
Great, the PR looks good to me! :+1:

**Comment by kevinushey** [comment]
Verified fixed in the development builds (should be in +290).

<img width="389" alt="Screen Shot 2022-10-26 at 12 23 20 PM" src="https://user-images.githubusercontent.com/1976582/198117804-06917ef3-65bd-4b76-81ab-e72a7a4c94a3.png">

**Comment by markromanmiller** [comment]
Thanks all! This ended up on the bottom of my queue when one project finished and another came to the front. Great to see it working now!
