### ISSUE TITLE
RStudio Server fails to start

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6883]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.311 and newer
    OS Version      : CentOS7
    R Version       : 3.6.0

### Steps to reproduce the problem
- Install RStudio Server on CentOS7
- Try to load a session

### Describe the problem in detail
- After logging in, get spinner followed by "RStudio Initialization Error: Unable to connect so service" dialog
- Confirmed that this broke starting with build 1.4.311 and all newer builds
- Haven't checked if this is CentOS7 only (suspect it is not)

<img width="403" alt="screenshot of error dialog as described above" src="https://user-images.githubusercontent.com/10569626/82098400-bf404d80-96b9-11ea-8a7d-28cf4534de66.png">

### Describe the behavior you expected
- Session starts

**Comment by kfeinauer** [comment]
Only 3 commits for this particular build that changed from 1.4.310: https://buildmaster.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/master/2498/changes

Might possibly be caused by: https://github.com/rstudio/rstudio/commit/867fb44800ad74bd6d453d828cfe55d141a7b674

Any errors in the logs?

**Comment by gtritchie** [comment]
It was that change, note "rsessio" instead of "rsession". It's a bit concerning to me that we don't notice breaks in open-source server for so long. We should have some sort of basic smoke test, at least.

```
May 15 14:10:38 localhost rserver[27507]: ERROR system error 2 (No such file or directory) [child-path: /usr/lib/rstudio-server/bin/rsessio]; OCCURRED AT rstudio::core::Error rstudio::core::system::runProcess(const string&, const string&, rstudio::core::system::ProcessConfig&, rstudio::core::system::ProcessConfigFilter) src/cpp/core/system/PosixSystem.cpp:2278; LOGGED FROM: rstudio::core::Error rstudio::core::system::launchChildProcess(std::string, std::string, rstudio::core::system::ProcessConfig, rstudio::core::system::ProcessConfigFilter, PidType*) src/cpp/core/system/PosixSystem.cpp:2139
```

**Comment by gtritchie** [comment]
I'll fix, this is blocking me.

**Comment by kfeinauer** [comment]
Yes, smoke tests + integration tests will be something we will need to build out in the future to reduce regressions especially. I didn't catch this because I spend all my time working with Pro. Also, most (all?) of our other developers work mostly with desktop.

Not to mention all QA effort is currently on 1.3.

**Comment by gtritchie** [comment]
Yes, makes sense. Most open-source server stuff is caught by `ant devmode` way of working (e.g. Mac server), but there are some nooks and crannies that misses.

**Comment by gtritchie** [comment]
I think our standard-ish way of merging Pro work would have prevented this? Do the open-source change first, then merge that into the full Pro-side change?

**Comment by kfeinauer** [comment]
Usually the development is done against pro in its entirety, then we just merge the open source specific pieces. I generally don't run open source when doing this as it would take a lot of extra time to build open source, install it, run it, and then switch back fro pro development.

**Comment by fvalka** [comment]
I've encountered the same issue, since this version hasn't been released yet, as far as I can tell. I worked out the following workaround and would like to leave it here for others:
Setting the path to the rsession binary in the rserver.conf manually. 

On Ubuntu 20.04. this can be done in the file:
`/etc/rstudio/rserver.conf` where the following content has to be added:
```
rsession-path=/usr/lib/rstudio-server/bin/rsession
```

Finally, the server needs to be restarted and then it works fine so far.

**Comment by andresrcs** [comment]
Rstudio Server Preview 1.3.1045 fails to start again

```
sudo rstudio-server verify-installation
25 Jun 2020 01:25:51 [rsession-rstudio-server] ERROR system error 13 (Permission                                                   denied) [path: /home/rstudio-server/.config/rstudio, target-dir: ]; OCCURRED AT                                                   rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) co                                                  nst src/cpp/shared_core/FilePath.cpp:648; LOGGED FROM: rstudio::core::Error rstu                                                  dio::session::prefs::initializePrefs() src/cpp/session/prefs/UserPrefs.cpp:142
25 Jun 2020 01:25:51 [rsession-rstudio-server] ERROR system error 13 (Permiso de                                                  negado) [path: /home/rstudio-server/.config/rstudio/dictionaries/custom, target-                                                  dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirector                                                  y(const string&) const src/cpp/shared_core/FilePath.cpp:648; LOGGED FROM: rstudi                                                  o::core::Error rstudio::core::spelling::HunspellDictionaryManager::availableLang                                                  uages(std::vector<rstudio::core::spelling::HunspellDictionary>*) const src/cpp/c                                                  ore/spelling/HunspellDictionaryManager.cpp:158
25 Jun 2020 01:25:51 [rsession-rstudio-server] ERROR system error 13 (Permiso de                                                  negado) [path: /home/rstudio-server/.config/rstudio/dictionaries/custom, target-                                                  dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirector                                                  y(const string&) const src/cpp/shared_core/FilePath.cpp:648; LOGGED FROM: std::v                                                  ector<std::__cxx11::basic_string<char> > rstudio::core::spelling::HunspellCustom                                                  Dictionaries::dictionaries() const src/cpp/core/spelling/HunspellCustomDictionar                                                  ies.cpp:33
```

**Comment by kevinushey** [comment]
@andresrcs: this looks like it might be a different problem; would you mind filing a separate issue?

**Comment by andresrcs** [comment]
Sure, here it is
https://github.com/rstudio/rstudio/issues/7221#issue-645574287

**Comment by kevinushey** [comment]
Thanks!
