### ISSUE TITLE
Code snippets show in reverse order

### ISSUE THREAD

**Issue by M3IT** [rstudio/rstudio#6891]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Win 10 v1909
    R Version       : 3.6.3

### Steps to reproduce the problem
Enter snippets with the same leading letters in snippet editor.
In IDE, type the first couple of letters and note order that options are presented.
Intuitively, I'd expect either alphabetical order or order entered in snippet editor, but they're in reverse order entered.

### Describe the problem in detail
Snippets suggested by autocomplete are shown in reverse order of entry in snippet editor
Entered in snippet editor:
```
snippet aaa
	snippet_content

snippet aab
	snippet_content

snippet aad
	snippet_content

snippet aaba
	snippet_content

snippet aaaa
	snippet_content

snippet aac
	snippet_content
```

Suggestions from typing aa in IDE. Note, in reverse order to above.
![image](https://user-images.githubusercontent.com/25129392/82110265-1e689580-9780-11ea-8db9-5e43e8252446.png)

This behaviour is acceptable if it's noted in the editor or its help screen, but I can't find it. A better option would be either order entered in editor or alphabetical order, ideally user-selectable between the two options.

### Describe the behavior you expected
Alphabetical order or order entered in snippet editor - ideally with user-selectable option.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@M3IT Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.3.958 on MacOS 10.15.4 with R 4.0.0. I even added `abba` in the middle, to make the issue more obvious.* We'll review this as we continue development of RStudio.

*And how can I resist it?

**Comment by M3IT** [comment]
Thanks Ron. 
I'm not sure **_How can I even try to go on?_** * while the error exists, but I'll give it a go.

*[Line 11](https://www.azlyrics.com/lyrics/abba/sos.html)
