### ISSUE TITLE
RStudio.Version() not functioning while knitting

### ISSUE THREAD

**Issue by engineerchange** [rstudio/rstudio#6892]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.4.26
    OS Version      : MacOS Catalina 10.15.3
    R Version       : 3.6.3

### Steps to reproduce the problem
Knit a file with the following:
````
```{r}
RStudio.Version()
```
````
### Describe the problem in detail
The console will return the following error:
```
Error in RStudio.Version() : could not find function "RStudio.Version" Calls: <Anonymous> ... handle -> with CallingHandlers -> withVisible -> eval -> eval Execution halted
```
### Describe the behavior you expected
Expected RStudio.Version() to print results in RStudio's RMarkdown console the same as the results it would in the standard RStudio console.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is as intended; documents are knitted in a clean, separate R session outside of the main RStudio session. If you need to knit in your main R session,  you can call `rmarkdown::render()` directly.
