### ISSUE TITLE
Support dual/charcell-spaced editor fonts (e.g. Fira Code)

### ISSUE THREAD

**Issue by salim-b** [rstudio/rstudio#6894]
### System details

RStudio Edition : Desktop  
RStudio Version : 1.3.959 ([Ubuntu 18/Debian 10 package](https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.959-amd64.deb))  
OS Version      : Linux (Ubuntu 20.04)  
R Version       : 4.0.0

### Steps to reproduce the problem

1. Install RStudio.

2. [Install Fira Code](https://github.com/tonsky/FiraCode/wiki/Installing), either [manually](https://github.com/tonsky/FiraCode/wiki/Linux-instructions#manual-installation) or by issuing

   ```sh
   sudo apt install fonts-firacode
   ```

3. Open RStudio, go to <kbd>Tools</kbd>→<kbd>Global Options...</kbd>→<kbd>Appearance</kbd> and try to select `Fira Code` as _Editor font_ (it doesn't show up!).

### Describe the problem in detail

RStudio detects available monospace fonts on Linux using this command:

https://github.com/rstudio/rstudio/blob/30aa1f83a276c19fb2212e562b436b0086fa4ef2/src/cpp/desktop/DesktopInfo.cpp#L117

<sub>(`fc-list :spacing=100` is equivalent to `fc-list :spacing=mono` or just `fc-list :mono`)</sub>

The problem is, that there are also so called "dual-width" and "charcell" (i.e. multiple-width) fonts (recent versions of [Fira Code](https://github.com/tonsky/FiraCode/) or [Terminus](http://terminus-font.sourceforge.net/) for example) which are **not** listed by the `:spacing=100` option **but** `:spacing=90` (or the equivalent `:spacing=dual` or just `:dual`) and `:spacing=110` (or the equivalent `:spacing=charcell` or just `:charcell`).

Possible `spacing` values in fontconfig are described [here](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html):

Constant | Property | Value
-------- | -------- | -----
proportional | spacing | 0
dual | spacing | 90
mono | spacing | 100
charcell | spacing | 110

Imortant in this context:

> [spacing is not set by the font. Spacing is calculated from actual glyph
sizes in the font file by fontconfig](https://github.com/kovidgoyal/kitty/issues/1968#issuecomment-531437076)

### Describe the behavior you expected

I expected dual-width fonts like Fira Code and charcell fonts like Terminus to show up by default in RStudio.

### Solution

I think the proper way to support dual-width and charcell fonts would be to change [line 117 of `src/cpp/desktop/DesktopInfo.cpp`](https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/DesktopInfo.cpp#L117) to something like:

```sh
"{ fc-list :mono -f '%{family}\n' & fc-list :dual -f '%{family}\n' & fc-list :charcell -f '%{family}\n'; } | cut -d ',' -f 1 | sort | uniq",
```

### Workaround

For now, a possible ("hackish") workaround is to [overwrite the `spacing` of the desired font to `100` (`mono`) using a custom fontconfig `.conf` file](https://github.com/tonsky/FiraCode/issues/840#issuecomment-531471498).

### See also

- https://github.com/rstudio/rstudio/issues/3862
- https://github.com/rstudio/rstudio/issues/3909
- [Rethinking the spacing detection: Dual Width => Multiple width](https://gitlab.freedesktop.org/fontconfig/fontconfig/issues/176)

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Thank you so much for reporting this issue @salim-b and for awesome level of detail and links provided. We'll review this as we continue our ongoing development of RStudio.

**Comment by salim-b** [comment]
Glad to hear! :upside_down_face: 

> We'll review this as we continue our ongoing development of RStudio.

As stated above, the fix is probably a simple one-line change. But I haven't really tested it since I didn't want to dive into the venture of building RStudio myself (I'm currently relying on the workaround described above).

**Comment by mikebessuille** [comment]
If this is a trivial fix, we can do it in Juliet Rose.  OTherwise, this area will change significantly with the upgrade to Electron for 1.5

**Comment by jmcphers** [comment]
> I think the proper way to support dual-width and charcell fonts would be to change line 117 of src/cpp/desktop/DesktopInfo.cpp to something like:

I've tested this and confirmed it is the change required. Thanks so much for the tip!

**Comment by astayleraz** [comment]
Verified in version 1.4.1598 I was able to install and select fira code for my font on ubuntu 20 desktop. Closing issue.
