### ISSUE TITLE
Consolidate previous work with ClassIds.java and idSafeString

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6897]
Opening to track cleanup mentioned In PR review comment from @melissa-barca 

>Overall LGTM, we should probably move the work I did to ClassIds.java at some point but I did add a comment to say they need to remain stable. Thanks for specifying the importance of starting with rstudio_, I'll need to update my code with that as well.
>
>I wasn't aware of ElementIds::idSafeString so I wrote my own StringUtils class here: https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/core/client/StringUtil.java#L950-L981. While the StringUtils function allows a little more variety in class names, the only issue I see with the ElementIds call is that it allows the id to lead with a digit.

https://github.com/rstudio/rstudio/pull/6832#issuecomment-625919810

**Comment by melissa-barca** [comment]
Thanks for making this @gtritchie! Do you have any thoughts on how we should handle the StringUtils vs ElementsId classes? My initial thought is to remove the StringUtils class and update idSafeString to replace leading digits.

**Comment by gtritchie** [comment]
I agree we should get rid of the StringUtils method and use one in ClassIds, instead.

Why is it necessary to replace leading digits?

**Comment by gtritchie** [comment]
I'm reluctant to mess with ElementIds.idSafeString given it has been around a while and the IDs it generates are used in our Selenium automation.

However the ClassIds.idSafeString is new, and though it currently delegates to the ElementId method, no reason it can't do its own thing. Main thing is to start with `rstudio_` so it is shows by the feature for finding IDs.

**Comment by R-Hannibal** [comment]
@gtritchie & @melissa-barca - Anything QA needs to or should check on this ticket?

**Comment by gtritchie** [comment]
I don't think so. Main symptom of a problem would be an automation failure.

Generally issues marked as "Developer" won't have much to validate beyond (1) did the code build and (2) did the automation pass? Of course if you take that at face value then I have some beautiful tundra in Northern Canada I'd like to sell you!

**Comment by R-Hannibal** [comment]
@gtritchie - that sounds just lovely, where do I pay in advance? ;)

In all seriousness though, I recognize that are some things manual QA just can't really verify. The fact that the code has been checked in/built successfully and automation is passing (I'm assuming this one based off lack of fires) is reassuring though.
