### ISSUE TITLE
Mouse clicks and scrolling stops working

### ISSUE THREAD

**Issue by kn1g** [rstudio/rstudio#6899]
### System details

    RStudio Edition : Desktop
    RStudio Version : Happened in 1.2.1335 and updating to 1.2.5042-1 did not solve the issue 
    OS Version      : Linux Manjaro latest - with i3wm
    R Version       : 4.0.0 Arbor day 

### Steps to reproduce the problem
Seems to crash randomly at the moment. Happened before but a restart solved it back then. Now it messed up the system permanently.

### Describe the problem in detail
Mouse clicks and scrolling is not working any more. It affects the whole OS. Rebooting does not help. It just screws over everything. I googled and found this problem at least also affected multiple people with Ubuntu years ago (just google "no more mouse events after using rdesktop"). I will put in more information if I find out more about the problem. 

As I also have keynav to navigate without a mouse I first thought I do not really care. But in the end it turns out, keynav clicks do also not work anymore. I cannot click at all. I just navigated here with shortcuts to write this description which is really annoying.

All in all I am currently looking on how to fix my mouse at all as restart does not fix it. *Help is HIGHLY APPRECIATED*.

### Describe the behavior you expected
Well, obviously a working mouse.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists. (At least the one available on pacman AUR)
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kn1g** [comment]
Ok, I managed to get the mouse working again with upgrading manjaro and rstudio and restarting. Please try to find out what the issue is. It seems to screw some major stuff... In case I can help please tell me what to do.

**Comment by jmcphers** [comment]
> Mouse clicks and scrolling is not working any more. It affects the whole OS. 

Sorry, we don't have anything to go on here. It is not clear what's happening here or even that RStudio is the problem. We also don't formally support Manjaro. You might try asking for help on our forum:

https://community.rstudio.com/c/rstudio-ide

**Comment by kn1g** [comment]
Just FYI it seems not related to Manjaro or i3wm as Ubuntu also seems to have this issue:
https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/55739

**Comment by kn1g** [comment]
I am again without a mouse. This time I am even more sure it is RStudio Desktop as it was the only program I used when it crashed the mouse. I again trying to fix it without any idea why and how this happens.

**Comment by kn1g** [comment]
> Sorry, we don't have anything to go on here. It is not clear what's happening here or even that RStudio is the problem. We also don't formally support Manjaro. You might try asking for help on our forum:
> 
> https://community.rstudio.com/c/rstudio-ide

@jmcphers Sorry, to point this out again. But this is the third reboot and I am no 100% sure it is an issue with RStudio Desktop. As this also at least seemed to be a problem on Ubuntu according to this forum, if you need any log files, please tell me I am more than happy to help.

I can now just add that everything works totally fine until I start RStudio. As soon as RStudio is running, my mouse still moves but I cannot click or scroll anymore. (Pretty annoying as I need to hand in my PhD thesis pretty soon and did everything in RStudio...)

**Comment by gtritchie** [comment]
The forum thread you are linking is 10 years old and from before RStudio even existed, plus RStudio is never mentioned. There is mention of "rdesktop" that isn't the same thing as RStudio.

**Comment by kn1g** [comment]
Ay, that sounds totally reasonable. I was googling for Rstudio desktop and this popped up with basically the same problem. Hence, I linked it together not knowing that RStudio did not exist there. Anyway, I just wanted to point out the problem which is obviously related to RStudio and my setup and is annoying for me. But I totally understand that you guys cannot care about any individual issue. For me it just seemed that I was not the only one with this issue. But apparently and unfortunately, I am.
