### ISSUE TITLE
High CPU usage (RStudio R Session)

### ISSUE THREAD

**Issue by profjoeweaver** [rstudio/rstudio#6900]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      :  Windows 10 (1803)
    R Version       :  4.0.0

### Steps to reproduce the problem

Running all chunks in .Rmd file.

### Describe the problem in detail

Working with .Rmd file. Knitting to HTML does not prolonged CPU usage (i.e., stops after knitting is complete) but remains high after running all chunks (around 35%). Running all chunks a second time causes CPU to max out. RStudio does not crash and no warnings are issued. The process that consumes the most CPU (per the windows task)  is "RStudio R Session."

Closing and reopening RStudio results in normal CPU usage until running all chunks again.

### Describe the behavior you expected

Once all chunks are run (i.e., processing of code stops), the CPU usage returns to normal (i.e., 1% or 2%).

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This sounds like a bug that's fixed in the preview release of RStudio (#6737). Can you try that and let us know if it's fixed for you?

https://www.rstudio.com/products/rstudio/download/preview/
