### ISSUE TITLE
Special characters in "Keyboard Shortcuts" have to be replaced with descriptive texts

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rstudio#6901]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.958
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

1. Load RStudio Server in your browser.
2. Press either Alt+Shift+K (on Windows/Linux) or Opt+Shift+K (on Mac) to open "Keyboard Shortcuts" window.
3. Find any columns describing "Mac" shortcuts.

### Describe the problem in detail

Current Mac OS X shortcut keys are represented using special characters. Although those are readable by screen readers, the screen-reader anouncement is very vision-oriented so that it would be hard for blind people to understand what the keys are referring to.

For example, "⌃" is read as "Up-arrow head," "⇧" is described as "upwards right-arrow."

These are not informative.

### Describe the behavior you expected

Please change the visual special characters into descriptive text alternatives like below.

* ⌃: Ctrl
* ⌥: Opt
* ⇧: Shift
* ⌘: Cmd

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
They are read correctly for me on MacOS Safari with VoiceOver. It also worked on Chrome for Mac.

They do not ready correctly on Windows, but I felt that was OK given a Windows user probably isn't interested in the Mac shortcuts.

That said, I can see the case for doing this in a more cross-platform fashion even for platform-specific content.

**Comment by gtritchie** [comment]
Note when verifying: this issue specifically refers to the web page version of keyboard shortcut reference that appears when screen reader mode is enabled and you display keyboard shortcuts.

If screen reader mode is off, you instead get a partially transparent popup window, and that still shows the symbols for these special keys on Mac (by design).

Instead of enabling screen reader mode you can also get from that popup to the webpage version via the "See all shortcuts..." link in the upper-right corner of the popup.

**Comment by gtritchie** [comment]
This is purely a static content issue and I have verified on Server 1.4.1034.
