### ISSUE TITLE
Multiple Shiny background jobs when stopping in the Viewer pane

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6904]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.214

### Steps to reproduce the problem

First, set Shiny applications to run in the background (pull down Run App menu in a Shiny .R file). Next:

1. Set Shiny applications to open in a window (also in Run App menu)
2. Start a Shiny application by clicking Run App
3. Close the window that opens.

Observe that the background job is stopped. Now:

1. Set Shiny applications to open in the Viewer pane (also in Run App menu)
2. Start a Shiny application by clicking Run App
3. Press Stop in the Viewer pane. 
4. Click Run App again.

### Describe the problem in detail

Pressing Stop in the Viewer Pane does not terminate the background job, and in step 4 above, a new background job is created (so now there are two!)

![image](https://user-images.githubusercontent.com/470418/82237903-3d376b00-98eb-11ea-9172-48875e25f356.png)

### Describe the behavior you expected

The job should be stopped when the viewer pane is stopped.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This may be fallout from work on the Tutorial Pane, as I did have to do some plumbing around how Shiny applications handle start + stop events. Let me know if you'd like me to dive in further.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 1.5.121 on MacOS 12 beta
- RStudio Server 1.5.139 on SLES 15 SP2 via Chrome on MacOS 12 beta

Note that the original issue also could be experienced by clicking "reload app" multiple times, and that it no longer causes a problem, either.
