### ISSUE TITLE
keras crashes reproducibly in rstudio server

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/rstudio#6908]
### System details

    RStudio Edition : Rstudio Server 
    RStudio Version : 1.3.958 (current preview) but also 1.2.5042 (current stable)
    OS Version      :  Ubuntu LTS 18.04
    R Version       :  3.6.3

### Steps to reproduce the problem
On a brand new Ubuntu 18.04 LTS (also testet and same issue with 16.04 LTS)  R (3.6.3) and Rstudio server (current preview) (also testet current stable) are installed.

In addition the following libraries are installed:
`sudo apt-get -y install build-essential libcurl4-gnutls-dev openjdk-7-* libxml2-dev libssl-dev`

R and RStudio Server seem to work great.

devtools and keras (latest master) are installed, no other packages:
```
install.packages("devtools")
devtools::install_github("rstudio/keras")
```

keras is installed:
```
library(keras)
install_keras()
```

All installations finish without any problem.

### Describe the problem in detail

When using keras, Rstudio crashes reproducibly, i.e:
```
library(keras)
mnist <- dataset_mnist()
```
Using the R console directly (without Rstudio) everything works as expected. (Mnist dataset gets downloaded).

### Describe the behavior you expected
Same behaviour as in R console.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8   
 [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3   

```

**Comment by fabiangehring** [comment]
Was able to run it after Cuda installation (see https://www.tensorflow.org/install/gpu) and newest Preview RStudio Server in Ubuntu 16.04 and 18.04.

**Comment by ronblum** [comment]
@fabiangehring I'm glad to hear you're able to get it to work! However, when you ran into the initial issue, by "crash" do you mean that 
- an error was thrown
- the R session crashed, possibly with the "unexpectedly crashed" dialog
- the server crash and stop running? 

or something else? Thanks!

**Comment by fabiangehring** [comment]
@ronblum Thanks for asking. In this case the console did just freeze and after some time the ression was restartet and showing a message that the previous sessios has ended unexpectedly. 

Keras seems to work now, even though there seem to be problems left:
When doing:

```
library(keras)
k <- backend()
k$
```

An error message is shown 
`
Error in py_get_attribute_types(x, names) : 
  SystemError: <built-in function __import__> returned a result with an error set
`

This seems to be more of a keras problem than a rstudio server issue. What confuses me a bit is the fact that the error is already shown when typing the "$" in "k$" whereas this does not happen in R's default console. Maybe you have a hint regarding this?

**Comment by kevinushey** [comment]
This might be an issue in RStudio's completion system -- perhaps an error is being emitted when attempting to infer what completions are appropriate or available.

Can you also share the output of:

```
reticulate::py_config()
keras:::keras_version()
```

**Comment by fabiangehring** [comment]
sure,

```
> reticulate::py_config()
python:         /home/fabian/.local/share/r-miniconda/envs/r-reticulate/bin/python
libpython:      /home/fabian/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.6m.so
pythonhome:     /home/fabian/.local/share/r-miniconda/envs/r-reticulate:/home/fabian/.local/share/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
numpy:          /home/fabian/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.18.1
> keras:::keras_version()
[1] ‘2.3.0’
```

**Comment by Lauler** [comment]
Running in to the same issue. 

I set up tensorflow/keras and it ran successfully once on Rstudio Server version 1.3.959 

Next day when I go to try again. It immediately crashes (The previous R session was abnormally terminated to due an unexpected crash. You may have  lost workspace data...). 

If I go to the computer my server is hosted on and fire up Rstudio 1.3.959 (not the server version), everything works fine. I can run the MNIST code example above. However, the same code crashes on Rstudio Server 1.3.959.

My setup was similar to @fabiangehring (except for installing a newer tensorflow version).

**Comment by gmkumar1988** [comment]
Getting the same issue since morning. Tried multiple ways, but again getting same issue " R Session Aborted". when i hit to_categorical(), immediately getting this error :(
