### ISSUE TITLE
Kable output renders incorrectly and blocks scrolling in notebook

### ISSUE THREAD

**Issue by serivas** [rstudio/rstudio#6909]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      :  Windows 10, 2004 build 19041.264
    R Version       :  3.6.3

### Describe the problem in detail

Whenever I create a table output using knitr::kable(), the direct chunk output looks very plain with **tons** of extra whitespace, picture below. This is not only aesthetically problematic, but when positioning the mouse pointer over the chunk's output, **scrolling is blocked** (using scroll wheel), which makes it very hard to navigate the file.

### Steps to reproduce the problem

Code:

```r
data.frame( Method = c("BIC","AIC","Optimal"),
                    Segment = c(1, 10, 6),
                    Lambda = c(val1  %>% scientific(),
                                        val2  %>% scientific(),
                                        val3 %>% scientific()),
                    Significant_Words = c(1, 65, 17),
                    row.names = NULL) %>% kable(caption = "Lambda selection",
                                                                        align = c("l","c","c","c"))
```

Output:

![image](https://user-images.githubusercontent.com/59834210/81503928-07233700-92ac-11ea-909a-52db63e495c3.png)

** YAML header:

        output:
          pdf_document:
            number_sections: yes
            toc: yes
          html_document:
            css: styles.css
            df_print: paged
            keep_md: yes
            number_sections: yes
            toc: yes
            toc_float: yes
          word_document:
            toc: yes
          github_document: null
        header-includes:
        - \setlength{\parskip}{\baselineskip}
        graphics: yes
        urlcolor: blue

### Describe the behavior you expected

I would expect normal scrolling when the mouse pointer hovers over the chunk output

### Other info

* I have MiKTeX installed
* If I don't use knitr::kable(), the problem goes away (but I end up with ugly tables in PDF output)

  R version 3.6.3 (2020-02-29)
  Platform: x86_64-w64-mingw32/x64 (64-bit)
  Running under: Windows 10 x64 (build 19041), RStudio 1.2.5033

**xfun::session_info('rmarkdown'):**

  Locale:
    LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United   States.1252
    LC_NUMERIC=C                           LC_TIME=English_United States.1252    
  
  Package version:
    base64enc_0.1.3 digest_0.6.25   evaluate_0.14   glue_1.4.0      graphics_3.6.3  grDevices_3.6.3 highr_0.8      
    htmltools_0.4.0 jsonlite_1.6.1  knitr_1.28      magrittr_1.5    markdown_1.1    methods_3.6.3   mime_0.9       
    Rcpp_1.0.4.6    rlang_0.4.5     rmarkdown_2.1   stats_3.6.3     stringi_1.4.6   stringr_1.4.0   tinytex_0.22   
    tools_3.6.3     utils_3.6.3     xfun_0.13       yaml_2.2.1     
  
  Pandoc version: 2.7.2

- [ X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@serivas Can you provide the code that defines the values of the objects—e.g. `val1` etc.—are defined so that we can try to reproduce this? Or does it occur with an even simpler example?

**Comment by serivas** [comment]
Hi @ronblum , this happens with any dataframe, regardless of size and structure. Minimum reproducible code:
```
data.frame(col1 = c(1,1), col2 = c(2,2)) %>% kable()
```

**Comment by jmcphers** [comment]
This is being tracked in https://github.com/rstudio/rstudio/issues/2202.
