### ISSUE TITLE
Pop-out Terminal tab as a separate window

### ISSUE THREAD

**Issue by zx8754** [rstudio/rstudio#6910]
Just like in **Source** panel files tabs can be popped out as a separate window, can we have **Terminal** to pop out, too?

Sometimes I work locally and remotely via ssh concurrently, and while working locally on **Console** I'd like to keep an eye on the process of scripts running on **Terminal**.

**Comment by lrnv** [comment]
This has been asked a lot. See #2833

**Comment by gtritchie** [comment]
I'm going to resolve this as a duplicate of #2833; that issue is tracking the more general request for popping out any pane types.
