### ISSUE TITLE
Feature Request: RStudio Package Manager - Primary CRAN Repo in a per Project Basis

### ISSUE THREAD

**Issue by jtelleriar** [rstudio/rstudio#6911]
Would it be possible to add within RStudio Projects Pane, an option to choose, the Primary CRAN Repo from RStudio Package Manager?:

![image](https://user-images.githubusercontent.com/29477671/82291376-28211180-99a9-11ea-8c19-f0993aa186b6.png)

![image](https://user-images.githubusercontent.com/29477671/82291445-41c25900-99a9-11ea-9d46-d17572099eb9.png)

In that way, If I share my RStudio Project with other colleagues, I can freeze my Package Repository Version to a given date (Eg: "https://packagemanager.rstudio.com/all/281"), plus use renv for reproducibility.

Thank you!

**Comment by kevinushey** [comment]
If you're using `renv`, the repositories will already be encoded in `renv.lock`. Is that sufficient?

**Comment by jtelleriar** [comment]
Yes, but if you are not using `renv`:

A simple Primary CRAN Repo Specification within the project, plus .libPaths() pointing to the Project Repository might also be interesting for *basic* project isolation
