### ISSUE TITLE
Manuals documents in R Help, extraneous letter n on top

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#6912]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Mac OS 10.15.4
    R Version       : R version 4.0.0 (2020-04-24)

### Steps to reproduce the problem

Go to Help -> R Help -> Click on any of the documents in the Manuals section

### Describe the problem in detail

Each of these documents have an extraneous letter "n" on top. I don't think it's intentional. I've included two screenshots below.

<img width="622" alt="Screenshot 2020-05-19 at 09 32 16" src="https://user-images.githubusercontent.com/5965649/82304085-c2865280-99b3-11ea-9ca6-bca5051934e4.png">

<img width="629" alt="Screenshot 2020-05-19 at 09 32 23" src="https://user-images.githubusercontent.com/5965649/82304109-c9ad6080-99b3-11ea-945f-6675523062e8.png">

### Describe the behavior you expected

I didn't expect an extraneous letter on top.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
I can reproduce this in RStudio Desktop 1.3.959 and 1.2.5040 on MacOS 10.15.4 with R 4.0.0, but not in RStudio Server 1.3.959 on Red Hat 7.8 with R 3.6.3 and 4.0.0. So this appears to be:
1) Limited to RStudio Desktop.
2) Not a regression.

**Comment by gtritchie** [comment]
Does not repro on Mac Desktop with R < 4.0, nor or Windows Desktop even with R 4.0; so appears Mac Desktop / R 4.0 specific.

**Comment by gtritchie** [comment]
This is external to RStudio; for example if you open (on Mac) the file directly in Chrome you will see this:

/Library/Frameworks/R.framework/Versions/4.0/Resources/doc/manual/R-intro.html

**Comment by kevinushey** [comment]
FWIW:

```
$ diff /Library/Frameworks/R.framework/Versions/4.0/Resources/doc/manual/R-intro.html ~/Desktop/R-intro.html
33c33,34
< <meta name="viewport" content="width=device-width, initial-scale=1.0">n<meta name="description" content="An Introduction to R">
---
> <meta name="viewport" content="width=device-width, initial-scale=1.0">
> <meta name="description" content="An Introduction to R">
380c381
< Next: <a href="#Preface" accesskey="n" rel="next">Preface</a>, Previous: <a href="dir.html#Top" accesskey="p" rel="prev">(dir)</a>, Up: <a href="dir.html#Top" accesskey="u" rel="up">(dir)</a> &nbsp; [<a href="#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="#Function-and-variable-index" title="Index" rel="index">Index</a>]</p>
---
> Next: <a href="#Preface" accesskey="n" rel="next">Preface</a> &nbsp; [<a href="#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="#Function-and-variable-index" title="Index" rel="index">Index</a>]</p>
7077c7078
< packages is described in <a href="https://cran.r-project.org/doc/manuals/R-exts.html#Creating-R-packages">Creating R
---
> packages is described in <a href="./R-exts.html#Creating-R-packages">Creating R
7097c7098
< <code>Packages</code> menu in the Windows and macOS GUIs, see <a href="https://cran.r-project.org/doc/manuals/R-admin.html#Installing-packages">Installing
---
> <code>Packages</code> menu in the Windows and macOS GUIs, see <a href="./R-admin.html#Installing-packages">Installing
```

So the rogue `n` is there, but surprisingly it's not in the "public" version. Maybe something weird happened when packaging R 4.0.0?
