### ISSUE TITLE
Javascript exception when loading GWT sources relying on Ace

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6913]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.358
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.0

### Steps to reproduce the problem

Launch RStudio with the DevTools inspector open.

### Describe the problem in detail

Exception while attempting to create the AceCommandManager:

<img width="1919" alt="Screen Shot 2020-05-19 at 11 17 14 AM" src="https://user-images.githubusercontent.com/1976582/82363188-53fcc100-99c2-11ea-9a54-f3927147e53a.png">

Normally, `$wnd.require` is a method which should be injected by Ace when it is loaded. However, `window.require` is not defined (and neither is `window.ace`).

### Describe the behavior you expected

No exceptions on startup.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I saw this one time (a few days ago), but couldn't repro on subsequent attempts.

**Comment by rich-rstudio** [comment]
verified on 1.4.768
