### ISSUE TITLE
The Git pane fails to detect saved changes to a .gitignore file until the next time the Git pane is interacted with (Refresh, History, etc.).

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#6917]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio Version 1.3.959
    OS Version      : Windows 10 Pro
    R Version       : R 4.0.0patched

### Steps to reproduce the problem

1. Open a Git Project in RStudio > select the Git pane > open the .gitignore file in source editor.
2. Make any change to the .gitignore file and save.

### Describe the problem in detail
The .gitignore file will not show up in the Git pane until there is some sort of interaction with the Git pane by the user (Refreshing, selecting History, attempting to commit a file, etc. all force the .gitignore file to show up in the Git pane).

This issue seems very minor due to any Git pane interaction 'fixing' the symptoms of the issue. However it IS a regression from 1.2 functionality.

### Describe the behavior you expected
Saving changes to a .gitignore file causes that file to immediately show up in the Git pane of the IDE.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Does this effect other files prefixed with a `.`, or only `.gitignore`? I suspect it might be because we normally treat these files as "hidden" from the file monitor and so it ignores changes to these files.

**Comment by R-Hannibal** [comment]
This looks to be specific to .gitignore (tried in the [rwars git project](https://github.com/Ironholds/rwars) to change and save .RbuildIgnore and it is immediately picked up/displayed in the Git pane).
