### ISSUE TITLE
Console moves while typing

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#6921]
**Steps to reproduce:**
* Put the console pane above the editor pane.
* Focus on the console.
* Start typing.

**Expected behavior:** should type in the console without affecting its size or scroll.

**Actual behavior:** the console size or scrolling or something else goes up and down as I type.

**Setup:** RStudio 1.3.947, running on debian linux (KDE).

![unstable_console](https://user-images.githubusercontent.com/11860098/82536238-d4e9c300-9b50-11ea-8b1c-6eb82131cb24.gif)

**Comment by kevinushey** [comment]
The latest version of the preview is 1.3.959. Does it reproduce with that version?

**Comment by david-cortes** [comment]
No longer reproducible in 1.3.959.
