### ISSUE TITLE
Bad display of traceback with delayed evaluation

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#6922]
### System details

    RStudio Edition : Server
    RStudio Version :  1.2.5042
    R version 3.4.0 (2015-04-16)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04.5 LTS

### Steps to reproduce the problem
1. Create and source the following 3 files:
```
# test3.R
test3 <- function() { 
  42   # <--- set a breakpoint here
  }

# test2.R
test2 <- function(arg = test3()) {
  arg + 1
}

#test1.R
test1 <- function() {
  test2()
}
```
2. Set a breakpoint where marked in test3
3. Run test1(), observe the traceback  

### Describe the problem in detail
This is the on screen view: 
![image](https://user-images.githubusercontent.com/73080/82554248-4126ef80-9b6e-11ea-9658-5fd0e8cfd550.png)

Note in the traceback pane that:
1. test2 and test1 is shown without lines
2. Therefore, when clicking on them - the editor does not navigate to the call site (In real life it navigates to random places in the file)
3. test1 is shown *only* when 'Show Internals' is checked.

### Describe the behavior you expected
As shown in the screenshot, lobster::cst() does show the correct and complete callstack, so it seems the information *is* available to R itself.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by OfekShilon** [comment]
This issue is very common in real life and makes debugging with  RStudio very unpleasent. 
Are you guys at least able to reproduce it?

**Comment by kevinushey** [comment]
Looks fine for me on macOS with R 4.0.0 and RStudio v1.3.959:

<img width="715" alt="Screen Shot 2020-05-26 at 1 56 58 PM" src="https://user-images.githubusercontent.com/1976582/82949657-d3593a00-9f58-11ea-9fd0-ed414397f7ab.png">

**Comment by jmcphers** [comment]
@OfekShilon Is it possible that you have the `keep.source` option turned off? What does this return for you?

```
getOption("keep.source")
```

**Comment by OfekShilon** [comment]
@jmcphers  my keep.source is true.
Are you able to try and reproduce it on RStudio server?

**Comment by OfekShilon** [comment]
Another info bit: 
I noticed that the bad display starts only on the *second* run and on. The first seems fine.

**Comment by kevinushey** [comment]
> I noticed that the bad display starts only on the second run and on. The first seems fine.

Thanks, that's what it took for me to reproduce this as well. This likely implies that the issue is caused by byte-compiling of the sourced functions.

**Comment by OfekShilon** [comment]
We'd really appreciate if you guys manage to squeeze this into v1.3. Debugging is what makes RStudio superior to an editor, and this would be a great step in making the debugger usable.

**Comment by jmcphers** [comment]
@kevinushey I'm surprised that this does not get reported more often given that it's a problem with R 3.4 and RStudio 1.2 (both pretty old at this point). Did R make a change sometime around 3.4 that caused them to do byte compiling more frequently or aggressively?

**Comment by kevinushey** [comment]
They did!

https://github.com/wch/r-source/blob/7d1608959550e95d810eb5c4fda660ac15969915/doc/NEWS.3#L2144-L2156

>     • The JIT (‘Just In Time’) byte-code compiler is now enabled by
>       default at its level 3. This means functions will be compiled on
>       first or second use and top-level loops will be compiled and then
>       run.  (Thanks to Tomas Kalibera for extensive work to make this
>       possible.)
> 
>       For now, the compiler will not compile code containing explicit
>       calls to browser(): this is to support single stepping from the
>       browser() call.
> 
>       JIT compilation can be disabled for the rest of the session using
>       compiler::enableJIT(0) or by setting environment variable
>       R_ENABLE_JIT to 0.

**Comment by OfekShilon** [comment]
@jmcphers  I myself can't claim that it started in 3.4. It might be much older.
Did you guys bisect it to 3.4?

**Comment by kevinushey** [comment]
Some code to make it easier to prepare the test environment:

```R
# create test files
writeLines("test1 <- function() {\n  test2()\n}", con = "test1.R")
writeLines("test2 <- function(arg = test3()) {\n  arg + 1\n}", con = "test2.R")
writeLines("test3 <- function() {\n  42\n}", con = "test3.R")

file.edit("test1.R")
file.edit("test2.R")
file.edit("test3.R")
```

**Comment by kevinushey** [comment]
The problem here comes down to finding source references when the byte compiler is active.

When an R function is byte-compiled, the associated R context `srcref` property gets replaced with a `<in-bc-interp>` marker. For this case, R has some internal machinery to resolve the source references associated with such a context; e.g.

https://github.com/wch/r-source/blob/819477cd6dbefb8fae61a07fc13064faa29a2714/src/main/eval.c#L6279-L6309

But those methods unfortunately are not made public. However, a srcref-annotated call can be accessed via the R level `sys.call()` function, so I'm going to try and investigate if we could use that in such cases.

**Comment by OfekShilon** [comment]
Will the fix be available in 1.4?

**Comment by R-Hannibal** [comment]
@OfekShilon, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990 with R 3.4.1 on macOS Catalina

**Comment by OfekShilon** [comment]
@R-Hannibal  sorry for the late reply. We're unable to install preview versions, will install, test and report immediately when 1.4 is officially released.

**Comment by OfekShilon** [comment]
@R-Hannibal  now that 1.4 is released - we installed and I can verify the fix.  This one's a life changer!  Thanks.
