### ISSUE TITLE
Debugger mixes variable 'n' and continue statement

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#6923]
**Steps to reproduce:**
* Create a function in the editor taking a parameter with name `n`.
* Put a breakpoint inside the function and execute to enter debug mode.
* Highlight the `n` in the editor and click Ctrl + Enter.

**Expected behavior:** should produce the command to show the variable `n` in the console - that is, ``` `n` ```.

**Actual behavior:** executes the next statement.

```r
some.func <- function(a = NULL, n = 10) {
    a = n + 1
    ### <put breakpoint above>
    n = n + 1
    ### highlight 'n' above, and press Ctrl + Enter
    return(n)
```

**Comment by kevinushey** [comment]
This is because `n` is interpreted by the R REPL (for which the debugger is active) as the actual debugger command `n`. You need to explicitly call e.g. `print(n)` to avoid this behavior.

**Comment by jmcphers** [comment]
We _could_ try to detect that an "n" is being sent from the source pane and have RStudio emit "print(n)" or "`n`" automatically, but not likely to try to make this work soon.
