### ISSUE TITLE
Yes / No dialog always selects No button via enter key

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6928]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.959 (probably older versions, too, but didn't confirm)
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- load RStudio server
- do an action that triggers a "Yes / No" dialog, easy example is Help / Accessibility / Screen Reader Support
- when Yes / No dialog appears, No key has focus (might need to tap Shift key to see this)
- use tab key to move focus to Yes key
- hit enter key

### Describe the problem in detail
- the "no" action is triggered
- for the screen reader support toggle example, you know this because the UI doesn't reload

### Describe the behavior you expected
- on a Yes / No dialog, expect Enter key to do the same thing as Spacebar key, and trigger the focused button
- presumably it is triggering the "default" button, but that concept doesn't make sense in this type of message dialog and we give no visual indication that there is a default button
- possibly a suspect in #6852

### Other Comments
- on Windows, if a screen reader is running (JAWS or NVDA tested) then the enter key does the same thing as spacebar; not true on Mac with VoiceOver, though

**Comment by gtritchie** [comment]
Notes: the "classic" RStudio theme did have a (barely noticeable) style difference for Default buttons via the `DefaultDialogAction` css style.

**Comment by gtritchie** [comment]
For discussion of current behavior on desktop dialogs, see: #6936

**Comment by kfeinauer** [comment]
Verified fixed on RSP 1.4.940-1
