### ISSUE TITLE
Warning in readChar(file, size, TRUE) :   truncating string with embedded nuls

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6932]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.957
    OS Version      : macOS 10.15.4
    R Version       : 4.0.0

### Steps to reproduce the problem

Create an R Notebook, with the contents:

`````
---
title: "R Notebook"
output: html_notebook
---

```{r}
plot(cars)
```
`````

Run the chunk (so that inline output is displayed), and then save the document.

### Describe the problem in detail

This warning is emitted into the console:

```
Warning in readChar(file, size, TRUE) :
  truncating string with embedded nuls
```

### Describe the behavior you expected

No warning.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The error is coming from here:

https://github.com/rstudio/rstudio/blob/2726eb55ae1d98a1a970ab42018e9a364f910d76/src/cpp/session/modules/SessionRmdNotebook.R#L112-L122

when attempting to read files with a `.snapshot` extension. We should add this file extension to the set of things we read as binary rather than text. (Or, perhaps skip it altogether as we don't make sure of these snapshot files when generating a notebook)

**Comment by kevinushey** [comment]
Note: you may need to press Enter in the Console for the warning message to be printed.

**Comment by EricGoldsmith** [comment]
Seems to a similar issue when using `kableExtra::kable_styling()`

https://github.com/haozhu233/kableExtra/issues/478

that is not resolved with RStudio version: 1.3.1019, which [contains this fix](https://rstudio.com/products/rstudio/download/preview-release-notes/#bugfixes).

**Comment by kevinushey** [comment]
This is indeed an RStudio bug, caused by RStudio attempting to read Bootstrap font files as though they were text files.

```
Browse[2]> con
A connection with                                                
description "bootstrap-3.3.5/css/fonts/Lato.ttf"
class       "file"                              
mode        "rb"                                
text        "binary"                            
opened      "opened"                            
can read    "yes"                               
can write   "no"  
```

I think we just need to be more careful about which files we attempt to read here:

https://github.com/rstudio/rstudio/blob/1889a1bce5322cb541b88adfe56ecdefa1b43a20/src/cpp/session/modules/SessionRmdNotebook.R#L120-L129

**Comment by luispuerto** [comment]
I have a similar issue

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1045, R Version - 4.0.0, Windows 10 Desktop 

Comparison testing between versions RStudio versions 1.3.959 and 1.3.1045, the warning was emitting in the old version, does not appear in 1.3.1045.

**Comment by EricGoldsmith** [comment]
I'm still seeing the issue ([replication steps](https://github.com/haozhu233/kableExtra/issues/478)) with RStudio 1.3.1045 ("Water Lily" (72424003, 2020-06-23) for macOS)
```
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5
```

@kevinushey, and you confirm the RStudio build that contains https://github.com/rstudio/rstudio/pull/7153?

**Comment by R-Hannibal** [comment]
@EricGoldsmith can you confirm that the repro steps you're using in RStudio 1.3.1045 to trigger this error are the same as those documented in the [kableExtra issue](https://github.com/haozhu233/kableExtra/issues/478) that you filed?

Not doubting what you're seeing, but when I run those steps on the same version of R/RStudio (granted I'm on Windows and not Mac, but I don't know that it should matter for this issue) I am unable to reproduce the error. Including my exact Console output below from after running the test:

```
R version 4.0.1 (2020-06-06) -- "See Things Now"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> library(dplyr)

Attaching package: �dplyr�

The following objects are masked from �package:stats�:

    filter, lag

The following objects are masked from �package:base�:

    intersect, setdiff, setequal, union

> library(knitr)
> library(kableExtra)

Attaching package: �kableExtra�

The following object is masked from �package:dplyr�:

    group_rows

> 
> cars %>%
+   kable() %>%
+   kable_styling()
> 
```

**Comment by EricGoldsmith** [comment]
```
R version 4.0.1 (2020-06-06) -- "See Things Now"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> warnings()
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> library(knitr)
> library(kableExtra)

Attaching package: ‘kableExtra’

The following object is masked from ‘package:dplyr’:

    group_rows

> 
> cars %>%
+   kable() %>%
+   kable_styling()
> warnings()
There were 26 warnings (use warnings() to see them)
>
```

Did you save the notebook after running the chunk? That's when the `knit`ing occurs, which generates the warnings.

>Run the chunk (so that inline output is displayed), and then **save the document**.

**Comment by kevinushey** [comment]
I also cannot reproduce. Can you confirm that `RStudio.Version()` does indeed report that you're running RStudio v1.3.1045?

**Comment by EricGoldsmith** [comment]
```
> RStudio.Version()
$citation

To cite RStudio in publications use:

  RStudio Team (2020). RStudio: Integrated Development Environment for R. RStudio, PBC, Boston, MA URL
  http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, PBC},
    address = {Boston, MA},
    year = {2020},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.3.1045’

$release_name
[1] "Water Lily"
```

**Comment by kevinushey** [comment]
Was finally able to reproduce. For posterity, one can reproduce with this document (copied from aforementioned issue):

`````
---
title: "R Notebook"
output: html_notebook
---

```{r echo=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)

cars %>%
  kable() %>%
  kable_styling()
```
`````

Copy this into an R Markdown document, save it, run the chunk, and then execute `warnings()` to see warnings printed.

**Comment by kevinushey** [comment]
Should now (hopefully!) be fixed in the next daily builds + next incoming preview release. Thanks again for testing + reporting @EricGoldsmith!

**Comment by EricGoldsmith** [comment]
Can confirm the issue is no longer present in RStudio Version 1.3.1054. Thanks for your diligence in fixing!

**Comment by kevinushey** [comment]
Phew! Glad to hear it; thanks for taking the time to follow up.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 x64 - Desktop 

Comparison testing between 1.3.1004 and 1.3.1054 using @kevin's repro example [HERE](https://github.com/rstudio/rstudio/issues/6932#issuecomment-650299770), 26 warnings listed in the console on the old build, no warning listed on the latest preview.

Interestingly, I was never able to successfully reproduce on 1.3.1045 on either Mac or Windows, had to go to the older build 1.3.1004. Probably user error on my part.

**Comment by lrdegeest** [comment]
Seeing this error in RStudio Cloud when running `library(tidyverse)`

**Comment by R-Hannibal** [comment]
Hey @lrdegeest, you are correct, this is still Not Fixed in RStudio Cloud.

The current build of RStudio Cloud does not include all the fixes in the current preview build of the IDE. We will be looking to update Cloud in the next few weeks and then this issue should be resolved for you in RStudio Cloud. Apologies I don't have an exact date to offer, all I can say is that our team is working diligently and we will update Cloud as soon as the build is ready.

**Comment by carmensandoval** [comment]
Seeing this issue in RStudio Server as well.

**Comment by R-Hannibal** [comment]
@carmensandoval - could you confirm the version of RStudio that is running on your server instance? `RStudio.Version()` in the console or Help > About RStudio.

**Comment by carmensandoval** [comment]
```
$mode
[1] "server"

$version
[1] ‘1.2.5042’

$release_name
[1] "Double Marigold"
```

**Comment by R-Hannibal** [comment]
Thanks so much @carmensandoval for the information and quick response!

This issue should be fixed in our latest preview build available [HERE](https://rstudio.com/products/rstudio/download/preview/). If you can upgrade to that version of RStudio it should resolve the issue for you. Just let us know if you have continued trouble after updating and we'll take another look at this issue, open a new ticket if we need to.
