### ISSUE TITLE
"Clear Terminal Buffer" shortcut not shown on menu

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rstudio#6934]
In RStudio Server v1.3.959, there's no default shortcut key provided for "Clear Terminal Buffer."

In light of its frequent use (especially for screen reader users to save more buffer for better readability), we might want to come up with a nice shortcut.

Would it possible to use `"Ctrl+L"` contextually? `"Ctrl+L"` has been already preserved for clearing console output; however, could we also use this key for terminal when focused?

**Comment by gtritchie** [comment]
Ctrl+L does clear the terminal when it is focused. It is not shown as a shortcut on the menu since it is not implemented as a traditional shortcut (it has special handling in the code instead of being part of the command metadata.

**Comment by gtritchie** [comment]
Will use this issue to track the fact it isn't shown on the menu item so is harder to discover especially via screen reader.
