### ISSUE TITLE
LoadLibrary failure only with the latest RStudio version

### ISSUE THREAD

**Issue by DavorJ** [rstudio/rstudio#6938]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-1.2.5042 and RStudio-1.1.463
    OS Version      :  Win 10
    R Version       :  3.6.1

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Belgium.1252  LC_CTYPE=Dutch_Belgium.1252    LC_MONETARY=Dutch_Belgium.1252 LC_NUMERIC=C                   LC_TIME=Dutch_Belgium.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1    tools_3.6.1       yaml_2.2.0        data.table_1.12.4
```

Is the same for 1.1.463 and 1.2.5042 on startup, except for yaml_2.2.0 which is apparently only loaded in 1.1.463.

### Steps to reproduce the problem

I am loading [spatialite](https://www.gaia-gis.it/gaia-sins/) dlls ([download-link](http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/mod_spatialite-4.3.0a-win-amd64.7z)):

```
  # iconv
  dyn.load('./../lib/spatialite/libiconv-2.dll')
  dyn.load('./../lib/spatialite/libfreexl-1.dll')

  # proj9
  dyn.load('./../lib/spatialite/libproj-9.dll')

  # xml
  dyn.load('./../lib/spatialite/zlib1.dll')
  dyn.load('./../lib/spatialite/liblzma-5.dll')
  dyn.load('./../lib/spatialite/libxml2-2.dll')

  # stdc
  dyn.load('./../lib/spatialite/libgcc_s_seh_64-1.dll')
  dyn.load('./../lib/spatialite/libstdc++_64-6.dll')

  # rgeos library
  dyn.load('./../lib/spatialite/libgeos-3-5-0.dll')
  dyn.load('./../lib/spatialite/libgeos_c-1.dll')

  # spatialite
  dyn.load('./../lib/spatialite/mod_spatialite.dll')
```

### Describe the problem in detail

This piece of code works without a problem in R (console) and RStudio 1.1.463. But for some unknown reason to me, it fails with RStudio 1.2.5042.

> Error in inDL(x, as.logical(local), as.logical(now), ...) : 
>   unable to load shared object './../lib/spatialite/libstdc++_64-6.dll':
>   LoadLibrary failure:  A dynamic link library (DLL) initialization routine failed.

I have compared environment variables using `Sys.getenv()` for RStudio 1.1.463 and RStudio 1.2.5042. The only differences are in __COMPAT_LAYER, HOME, RS_LOCAL_PEER, RSTUDIO_SESSION_PORT, MPLENGINE, QT_D3DCREATE_MULTITHREADED and changing them has no effect on the error.

I have also compared `getLoadedDLLs()`, and I do not see any difference between 1.1.463 and 1.2.5042. All paths point to dlls in the R directory, except "(embedding)" which I have no idea what it is.

Anyone a clue? I don't understand why RStudio would impact `dyn.load()`.

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@DavorJ Thank you for raising the issue! I'm marking it as a bug to review as we continue development of RStudio.

**Comment by DavorJ** [comment]
Just verified with RStudio-1.3.959: same error.

**Comment by jmcphers** [comment]
Can you narrow down _which_ of the dyn.load calls is giving you this error?

```
Error in inDL(x, as.logical(local), as.logical(now), ...) :
unable to load shared object './../lib/spatialite/libstdc++_64-6.dll':
LoadLibrary failure: A dynamic link library (DLL) initialization routine failed.
```

Once you figure out which, can you post the results of `ldd path/to/that/file.so` when run via (a) your system terminal, and (b) `system2`?

**Comment by DavorJ** [comment]
@jmcphers 

The `dyn.load('./../lib/spatialite/libstdc++_64-6.dll')` call is giving the error. Same as in the supplied error message.

As noted in requested information, I am on Windows, not Unix, so no `ldd`. I can give you information from dependency walker (or its image if you can use that):
![image](https://user-images.githubusercontent.com/4161918/83173871-d0597780-a119-11ea-883b-f5a3f4881a9b.png)

So to be able to load `libstdc++_64-6.dll`, you only need to load the previous DLL:

`dyn.load('./../lib/spatialite/libgcc_s_seh_64-1.dll')`
 
I have supplied the link where these DLLs can be downloaded from. Can you reproduce the problem?

**Comment by DavorJ** [comment]
In `RStudio-1.3.1073` I still have this error.

**Comment by DavorJ** [comment]
This issue still persists. The only thing I would like to know is what Rstudio does with R that is causing this error. As stated in the original post, loading these libraries works perfectly from R console.

**Comment by kevinushey** [comment]
My best guess is that this is occurring because RStudio is already linked to a particular implementation of the C++ standard library, and that is incompatible in some way with the version you're trying to load. I'm not sure there's much we can do.

**Comment by DavorJ** [comment]
Not really, because if that was the case, then the other libraries should be able to load. 

It is still not clear to me why Rstudio -- being an IDE for R -- is influencing the workings of the underlying R. An IDE shloudn't be supposed to do that? What is next (?), different results from Rstudio and R console?!?
