### ISSUE TITLE
Building Distill Blog in RStudio 1.3 results in `/rmd_output/{n}/{path} not found` error in preview pane

### ISSUE THREAD

**Issue by tjpalanca** [rstudio/rstudio#6945]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.959
    OS Version      : Debian Linux 9 (stretch)
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Create a new [distill blog](https://rstudio.github.io/distill/blog.html).
2. Build the website (using Ctrl + Shift + B) to generate the `_site` directory.
3. Go to the `welcome.Rmd`  
4. Knit the document by pressing the `Knit` button or using Ctrl + Shift + K.
5. The document renders correctly, but the preview does not display correctly and shows `/rmd_output/{n}/{relative path to _site folder} not found`.
6. If you press "Open in Browser", it opens the correct document.

### Describe the problem in detail

I am unable to easily build Distill blogs using the new RStudio.

### Describe the behavior you expected

I expect the preview to be correct. This happens when I downgrade to RStudio 1.2.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by tjpalanca** [comment]
For ease of reproduction:

1. Used `rocker/geospatial:3.6.1`  as base image and installed the current latest RStudio Server version on top of it in the Dockerfile.
2. Installed `{distill}` 
3. Created a new "Distill Blog"
4. Build the Website
5. Attempted to knit `welcome.Rmd` 

Screenshot
![image](https://user-images.githubusercontent.com/13010489/82758099-262ad880-9e17-11ea-900b-93a4989f5d16.png)

When you click "open in browser" it works well.
Downgrading to RStudio Server 1.2 fixes it.

**Comment by jmcphers** [comment]
Regression from https://github.com/rstudio/rstudio/commit/9fada22ad4405afe4366c1fa7e6dba66c75ebe71

**Comment by R-Hannibal** [comment]
@tjpalanca, thanks so much for finding and reporting this issue. 

We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by tjpalanca** [comment]
Hello, @R-Hannibal, apologies for the delayed reply.

I can confirm that the issue is resolved!

**Comment by R-Hannibal** [comment]
Thanks so much for the assist @tjpalanca! I ended up testing this one out myself as well (never used a Distill project before, very cool stuff), entering a verification comment below:

Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows - Desktop 

Comparison test run between 1.3.959 (current stable) and 1.3.1054 (current preview), on the older version the not found error is produced as described, new build `welcome.Rmd` is knitting/opening successfully.
