### ISSUE TITLE
Ctrl + I (Reindent) alignment & newline alignment disagree for chained []

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#6948]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.324
    OS Version      : Mojave
    R Version       : 4.0.0

### Steps to reproduce the problem

When chaining `[]` queries (e.g. for `data.table`), the behavior of using `Reindent`=<kbd>Ctrl</kbd>+<kbd>I</kbd> differs from that of adding a newline (<kbd>Return</kbd>). Very simple to reproduce:

 1. Baseline

```
DT[ , .(sum(x)), by = grp][ , median(V1)]
```

2. After pressing <kbd>Return</kbd> after `by = grp`:

```
# this is good!
DT[ , .(sum(x)), by = grp
    ][ , median(V1)]
```

After `Reindent`ing the source (<kbd>Ctrl</kbd> + <kbd>I</kbd>):

```
# this is bad!
DT[ , .(sum(x)), by = grp
][ , median(V1)]
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Thanks so much for raising this issue @MichaelChirico and for the great detail in the issue report. I was also able to reproduce the issue on 1.4 running on windows.

We'll review this as we continue development of RStudio.

**Comment by MichaelChirico** [comment]
anything I could do to help here?

**Comment by kevinushey** [comment]
I suspect this is caused by our outdenting behavior for braces, which happens here:

https://github.com/rstudio/rstudio/blob/e92d8790f8d135fc2e390b69ffcdbb917106729e/src/gwt/acesupport/acemode/r_matching_brace_outdent.js#L54-L79

You could see if there's a way to detect this specific case and avoid outdenting. You'd have to compare with the expected outdenting behavior of (for example):

```
x[
  1, 2, 3,
  4, 5, 6,
  7, 8, 9
]
```

**Comment by MichaelChirico** [comment]
I don't know the first thing about JS, so maybe we can attack this laterally -- what logic applies when pressing <kbd> Return </kbd> vs when when `Reindent`ing? 

e.g. I can get the "normal" brace outdenting behavior when I do

<kbd> x </kbd> :arrow_right: <kbd> [ </kbd> :arrow_right: <kbd> Return </kbd>

And (my) expected `data.table`-chaining outdent behavior when I do

<kbd> x </kbd> :arrow_right: <kbd> [ </kbd> :arrow_right: <kbd> 1 </kbd> :arrow_right: <kbd> Return </kbd>

**Comment by MichaelChirico** [comment]
If order matters, and the `Reindent` logic can't see the ordering, maybe it could at least recognize the chain-style syntax as "OK" (so don't apply the `Reindent`)?

i.e., I suspect it will be hard to look at code statically and detect whether it should be styled as a chain (indent increases with `]`) vs. "inline" (indent stays the same at `]`).

This is different from the case of pressing <kbd> Return </kbd> since there is the extra piece of information of _where in the line_ <kbd> Return </kbd> was pressed.

So it may not be possible to fix this issue, unless the Reindent code simply considers both the "chain" and "inline" styles to be OK.
