### ISSUE TITLE
pdf viewer unable to be invoked by RStudio

### ISSUE THREAD

**Issue by giuseppedelnapalle** [rstudio/rstudio#6950]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042-1
    OS Version      : Manjaro XFCE 20.0.1
    R Version       : 4.0.0

### Steps to reproduce the problem
Double click to open a pdf file in `RStudio`.

### Describe the problem in detail
When I tried to open a pdf file generated by `RStudio`, the default pdf viewer, namely `qpdfview` or `okular`, could not be invoked (no response at all). It seemed only `evince` can be used by RStudio. I installed `RStudio` from AUR of Archlinux. Not sure how `RStudio` from other installation methods behaved.

### Describe the behavior you expected
The built-in pdf viewer should be open after clicking a pdf file in `RStudio`.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@giuseppec Thank you for raising the issue! I'll mark it as a bug to review as we continue to develop RStudio.

**Comment by jmcphers** [comment]
Sorry, we do not support Manjaro. RStudio itself doesn't generate PDFs; that happens through a combination of R Markdown and Pandoc, so as a next step I'd suggest generating a PDF from rmarkdown using R in the terminal to see if those PDFs have the same issue.
