### ISSUE TITLE
Source pane in a bad state after opening deleted file

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6959]
## System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.393
    OS Version      : MacOS

### Steps to reproduce the problem

1. Create a new R script and add some text
2. Save it as `deleted.R`
3. Close all source tabs
4. Delete the R script created in step 2, `deleted.R`
5. Select File -> Recent Files -> `deleted.R`

### Describe the problem in detail

An error that the file doesn't exist (expected) followed by the Source pane opening in a fugue state (not expected).

![image](https://user-images.githubusercontent.com/470418/82942556-fd0c6400-9f4c-11ea-80bf-7bc632d0f5fc.png)

### Describe the behavior you expected

An error, but not a blank source pane.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I repro'ed this back in v1.0.153 -- looks like we've lived with this one for a while!
