### ISSUE TITLE
Compare Results doesn't work 

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6960]
### System details

    RStudio Edition : Any
    RStudio Version : 1.2.5042

### Steps to reproduce the problem

1. Create a Shiny application
2. Create some tests with shinytests (latest version on Github)
3. Run the tests
4. Open the test script
5. Click the "Compare results" button

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

Results comparison opens.

Happens because the shinytest package has again changed its directory layout. We look for the directory `shinytests`:

https://github.com/rstudio/rstudio/blob/3fdda38e9a78a984a25c44e1672cf0869fad19cd/src/cpp/session/modules/SessionTests.R#L41-L44

However the name is now `shinytest`:

https://github.com/rstudio/shinytest/blob/e95865c5026f5ad82ff5cd8a39fc4b1f4f0104ef/R/test-app.R#L140-L146

**Comment by dfalty** [comment]
Verified fixed on version 1.3.1031. Verified with the latest shinytest versions from GitHub and CRAN.
