### ISSUE TITLE
Feature request: Allow project settings to set code margin

### ISSUE THREAD

**Issue by AshesITR** [rstudio/rstudio#6972]
Currently using Code > Editing > Display > Margin Column, one can set a global margin width for all RStudio files.

While the tab width can be customized in project settings, this is not possible for the margin column.
Since different projects may have different coding standards (read `.lintr` settings), it would be very useful to store the appropriate margin width in the project specific settings.

**Comment by jmcphers** [comment]
This is currently tracked in https://github.com/rstudio/rstudio/issues/4335.
