### ISSUE TITLE
Numbers misaligned in data viewer in latest RStudio version

### ISSUE THREAD

**Issue by hrecht** [rstudio/rstudio#6974]
Hello, I recently upgraded to RStudio 1.3.959 on Mac OS Catalina using R 3.6.3. Since then I've been seeing misaligned numbers in the data viewer, where some are left aligned and some are right aligned. I haven't noticed any patterns with the error. This persists across projects and several datasets and after restart. Screenshot from one example is attached.

<img width="406" alt="Screen Shot 2020-05-27 at 3 52 34 PM" src="https://user-images.githubusercontent.com/9753760/83069103-581a8580-a037-11ea-9428-9208555801f5.png">

**Comment by kevinushey** [comment]
Did you intend to close this? Can you also provide a reproducible example?

**Comment by hrecht** [comment]
Yeah sorry, for some reason the issue template didn't pop up the first time.
