### ISSUE TITLE
RStudio Desktop on Linux stores state in folders differing only in case

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6979]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Linux (any)

### Steps to reproduce the problem

1. Start RStudio
2. Make any change to any option in Global Options
3. Apply changes and exit
4. List the contents of the `~/.config/` folder

### Describe the problem in detail

The following two folders are found:

```
~/.config/rstudio
~/.config/RStudio
```

### Describe the behavior you expected

Only one folder. 

The `~/.config/RStudio` folder is written by the front end (the `rstudio` binary), which happens to respect XDG standards for config files. We don't specify this path explicitly; Qt computes its path based on `QSettings::UserScope`. 

The `~/.config/rstudio` folder is written by the back end (the `rsession` binary); it primarily contains RStudio user settings (`rstudio-prefs.json`) but is also used for other per-user prefs such as settings saved from the RStudio API, etc. 

It's a confusing to have two folders which differ only in case, and could also cause trouble when backing up `~/.config` to storage that doesn't have case sensitivity. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mwip** [comment]
Along those lines, I wonder why RStudio creates a "Desktop State" in `$HOME/.rstudio-desktop`. Wouldn't that be better placed in `$XDG_CACHE_HOME`, e.g. `$HOME/.cache` or, in case it's more of a collection configs in `$HOME/.config` as well?

**Comment by jmcphers** [comment]
That's a good question! This is addressed in RStudio 1.4, which stores most of those files in `$XDG_DATA_HOME` (it's not a cache as it is durable state); RStudio 1.3 already stores configuration data in `$XDG_CONFIG_HOME`.

**Comment by klmr** [comment]
In addition to `$HOME/.rstudio-desktop` RStudio also creates `$HOME/.r`, and recreates it on every startup, to store the crash handler permission. It would be great if that could be moved elsewhere as well.

**Comment by Robinlovelace** [comment]
Not sure if this is related but another issue I found is that RStudio changes my preferences without asking!

:

```
cat ~/.config/rstudio/rstudio-prefs.json
{
    "default_project_location": "~/repos",
...
    "editor_theme": "Cobalt"
}
```

Seems the actual changes are going in the other file, this is confusing:

```
cat ~/.config/RStudio/rstudio-prefs.json 
{
    "rmd_chunk_output_inline": false
}
```

https://github.com/rstudio/rstudio/issues/5280

If this is a separate issue I can open it such, just wanted to add my voice, this seems like a fairly serious but easy-to-fix bug.

**Comment by jmcphers** [comment]
@Robinlovelace That's a separate issue and you can file it as such (please include a reproducible example if you can!)

**Comment by jmcphers** [comment]
This issue will go away on its own when we switch to Electron (see https://github.com/rstudio/rstudio/issues/7389) since it's Qt that writes one of the folders.

**Comment by Robinlovelace** [comment]
Hard to provide a reprex and hoping that it's fixed in the new Electron version. Can try out the new version and report a new issue if it's not fixed.

**Comment by jmcphers** [comment]
@Robinlovelace The issue you described above is tracked in #8683.

**Comment by ronblum** [comment]
This no longer appears to happen, so I'm closing the issue—even considering this as fixed by Electron. If anyone using builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) continues to run into this issue, please let us know!
