### ISSUE TITLE
Whitescreen crash v1.3.959 sigsys_handlers.cc:**CRASHING

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#6981]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Xubuntu 20.04
    R Version       :  4

### Steps to reproduce the problem
Open Rstudio, load recent project, often just whitescreens.
Just now I pasted and it crashed.

### Describe the problem in detail
Running rstudio in terminal, output was:

"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4692621/diagnostics-report.txt)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
This is same as #6782 and will be fixed in the first 1.3 bugfix release.

In the meantime you can try the workaround by running RStudio 1.3.959 via:

`export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox"
rstudio`

**Comment by SimonDedman** [comment]
Thanks Gary. Apologies, I looked for similar bugs but in my attempts to be super specific, I ended up missing the broader "this crashes" title!

To be clear, if one typically runs rstudio from a menu, in which case the command is

`/usr/lib/rstudio/bin/rstudio %F`

Should one prepend that with the workaround i.e.

`export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox" /usr/lib/rstudio/bin/rstudio %F`

Or is the workaround a separate one & done? Since it doesn't seem to launch rstudio...

Cheers again!

**Comment by gtritchie** [comment]
The workaround requires setting the environment variable:

`RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox"`

However you need to do that for RStudio to see it will work. The original example I gave should work if you are running RStudio from the terminal.

**Comment by SimonDedman** [comment]
Thanks again Gary.

`export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox" rstudio`

doesn't launch rstudio for me in terminal whereas

`rstudio`

does. If I try

`export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox" /usr/lib/rstudio/bin/rstudio %F`

I get

> bash: export: `/usr/lib/rstudio/bin/rstudio': not a valid identifier
> bash: export: `%F': not a valid identifier

Same if I put everything after the quotes in single quotes.

Any thoughts? Cheers!

**Comment by gtritchie** [comment]
Sorry, drop the “export”, in terminal just do RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox" rstudio

**Comment by SimonDedman** [comment]
cheers pal, much appreciated

**Comment by SimonDedman** [comment]
FWIW: this still shows the warning

> "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

IDK if this is a problem but I figured I'd flag it. Thanks again.

**Comment by gtritchie** [comment]
That warning is unrelated to the crash and should be harmless (though I’d like to fix it!)
