### ISSUE TITLE
setLibrary breaks R_LIBS_SITE on Debian

### ISSUE THREAD

**Issue by meztez** [rstudio/rstudio#6982]
### System details

    RStudio Edition : Server
    RStudio Version : Latest (1.3.959)
    OS Version      : Debian Buster
    R Version       :  4.0.0

### Steps to reproduce the problem
Run R from shell on Debian buster, printenv, check `R_LIBS_SITE`, should be a list of 3 values
Should match what's in `/etc/R/Renviron` under `R_LIBS_SITE`

### Describe the problem in detail
Since 1330290, `setLibrary` sets `R_LIBS_SITE` when `R_LIBS_SITE` was not previously set.

```cpp
const std::string& library() const { return library_; }
void setLibrary(const std::string& library)
{
   library_ = library;
   core::system::setenv(&environment_, "R_LIBS_SITE", library);
}
```

 This cause `/etc/R/Renviron` on Debian buster to ignore `R_LIBS_SITE` since parameter expansion used is `${parameter-word}`. (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02)

`/etc/R/Renviron` sample
```r
R_LIBS_SITE=${R_LIBS_SITE-'/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library'}
```

### Describe the behavior you expected
R_LIBS_SITE should be unset when /etc/R/Renviron is executed I guess.

### Mitigation
Replace R_LIBS_SITE line in `etc/R/Renviron` by
```r
R_LIBS_SITE=${R_LIBS_SITE:-'/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library'}
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Fixed in 1.3-patch.
