### ISSUE TITLE
git/svn

### ISSUE THREAD

**Issue by KUPPANNAGARIMAGHANA** [rstudio/rstudio#6983]
I'm not able to find path of svn
![Screenshot (409)](https://user-images.githubusercontent.com/51473291/83101197-64522180-a0cf-11ea-9923-9c59118e8d47.png)

**Comment by meztez** [comment]
If svn is installed on your machine, it has to be discoverable by being on PATH. Or you have to install it if you want to use it.

**Comment by jmcphers** [comment]
Sorry, there's not enough detail here for us to investigate. Please fill out the issue template completely.
