### ISSUE TITLE
GNOME Shell clipboard manager not supported

### ISSUE THREAD

**Issue by salim-b** [rstudio/rstudio#6985]
### System details

RStudio Edition : Desktop  
RStudio Version : 1.3.959 ([Ubuntu 18/Debian 10 package](https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.959-amd64.deb))  
OS Version      : Linux (Ubuntu 20.04)  
R Version       : 4.0.0

### Steps to reproduce the problem

1. Install RStudio.

2. Install the GNOME Shell extension [Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/).

3. Copy (<kbd>Ctrl</kbd>+<kbd>c</kbd>) multiple strings from any app, e.g. a web browser so that you have more than one entry in your clipboard indicator.

4. Open RStudio.

5. Select an entry in Clipboard indicator other than the most recent one and then try to paste it (<kbd>Ctrl</kbd>+<kbd>v</kbd>) in RStudio: Nothing is pasted! Pasting by context menu (right click, `Paste`) is not possible either (greyed out).

### Describe the problem in detail

So far, RStudio is the only application where I have observed this problem. Unfortunately, I don't have the technical expertise to speculate or even describe the actual cause of the problem but I guess the same problem occurs with [other clipboard managers for the Linux desktop](https://techwiser.com/clipboard-manager-for-ubuntu/).

Disabling `Enable X11 clipboard monitoring` under <kbd>Tools</kbd>→<kbd>Global Options...</kbd>→<kbd>General</kbd>→<kbd>Advanced</kbd> doesn't have any influence (problem persists).

### Describe the behavior you expected

I expected the clipboard entry selected in _Clipboard indicator_ to be insertable in RStudio. 

### See also

Might be related: #3160

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@salim-b Thank you for raising the issue! I'll mark it for review during our continuing development of RStudio.

**Comment by salim-b** [comment]
> I'll mark it for review during our continuing development of RStudio.

Thanks! This issue really annoys me as hell since the clipboard manager worked fine with RStudio under Ubuntu 16.04 (I used [Diodon](https://github.com/diodon-dev/diodon)). Now after upgrading to Ubuntu 20.04 (actually a fresh install), RStudio is the only app which doesn't work with the clipboard manager ([Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/) as described above). I really like Clipboard Indicator and it's features (i.a. full text search), so I didn't bother testing other clipboard managers.

But if I can test something specifically to help resolve this issue, let me know!

**Comment by salim-b** [comment]
### Addendum

I just glanced through open issues in Clipboard Indicators [bug tracker](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues) and googled a bit.

What I found out:

- GNOME 3.34's Mutter introduced a new selection API (Ubuntu 16.04 used the now deprecated [Unity](https://en.wikipedia.org/wiki/Unity_(user_interface)) under the hood; Ubuntu 20.04 uses GNOME 3.36).

    From the pertinent [Phoronix article from 2019-05-03](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.34-Clipboard-Manager):

    > The clipboard manager, which is responsible for serving the copy/paste functionality to the desktop, has been going through a rework / new implementation within Mutter itself and works on both X11 and Wayland. This new clipboard manager implementation has been under review for the past half-year while yesterday the code was merged into Mutter for the current 3.33 development series.
    > 
    > This new clipboard manager code offers a generic API for selections, simplifications to a lot of the (X)Wayland/X11 code, a simple memory-based selection source was introduced, and other API improvements and cleaning of existing Mutter code. This clipboard manager allows copying up to 4MB of text or 200MB of images.
    > 
    > More details on this improved clipboard manager code for GNOME 3.34 Mutter can be found via [this merge request](https://gitlab.gnome.org/GNOME/mutter/merge_requests/320).

- Clipboard Indicator [uses this new selection API](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/200#issuecomment-623176433). I think the API is documented [here](https://developer.gnome.org/gdk3/stable/gdk3-Selections.html).

- The only other report I spotted about an app not working altogether with Clipboard Indicator was [this comment](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/59#issuecomment-558060618) (the issue itself is way older than GNOME 3.34 and its selection API).

I hope you can make RStudio fully compatible with Mutter's selection API! 🙏

**Comment by salim-b** [comment]
Since a few days the issue is gone! 🙌

I don't really know what's changed under the hood. I regularly update RStudio to the latest [development snapshot](https://dailies.rstudio.com/), maybe some change in v1.4? Or otherwise a change in [Clipboard Indicator](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator)? (I don't really remember if there was an update on [extensions.gnome.org](https://extensions.gnome.org/extension/779/clipboard-indicator/)) Or a fix in some underlying Qt library?

Anyway, I close this issue and keep my fingers 🤞 that it stays that way.
