### ISSUE TITLE
Installation errors in Fedora 32

### ISSUE THREAD

**Issue by julienrbrt** [rstudio/rstudio#6986]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042-1.fc32
    OS Version      : Fedora 32
    R Version       : 3.6.3

### Steps to reproduce the problem

* Download RStudio from [rstudio.com](https://rstudio.com/products/rstudio/download/)
* `dnf localinstall rstudio-1.2.5042-x86_64.rpm`
* `dnf upgrade`

### Describe the problem in detail

RStudio is updated to rstudio-1.2.5042-1.fc32 and unavailable in the system.

The symbolic link from `/usr/bin/studio` to `/usr/lib/rstudio/bin/rstudio` is broken.
```
$ ls /usr/lib/rstudio/bin/
libcrypto.so.1.0.0  libssl.so.1.0.0
```

It appears that the new executable is at `/usr/libexec/rstudio/bin/rstudio`

### Describe the behavior you expected

RStudio not disappearing while updating itself. Or at least updating its `/usr/bin/rstudio` symblink.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
RStudio's package does not refer to libexec so it's getting placed there by Fedora policy -- it's possible we can't fix this.

Does the same thing happen with the latest version, 1.3.959?

Is the symlink correct when doing a fresh install (not an update)?

**Comment by julienrbrt** [comment]
I have uninstalled RStudio and downloaded the version 1.3.959. At the moment of installation I saw dnf suggestion for installing `rstudio-desktop` which seems to install the version 1.2.5042 again.
 
![image](https://user-images.githubusercontent.com/29894366/83176856-714a3180-a11e-11ea-98e8-16759125e303.png)
Using `sudo dnf install rstudio-desktop` the symlink was goodly set and I could see it on my machine.

```
$ ls -al /usr/bin/rst*
lrwxrwxrwx. 1 root root 32 Apr 29 16:25 /usr/bin/rstudio -> /usr/libexec/rstudio/bin/rstudio
```

I did still however uninstall it again and install the version 1.3.959 with `localinstall`, which seems to work fine too. The symlink is however still pointed at `/usr/lib/rstudio/bin/rstudio` and no update is available from dnf (contrary to the version 1.2 installed with `localinstall`).

So probably it's Fedora fault as if RStudio installed from the RPM (`/usr/lib/rstudio/bin/rstudio`) then updating will use the repository version and break the installation (as available then in `/usr/libexec/rstudio/bin/rstudio`).

**Comment by ronblum** [comment]
@julienrbrt What happens if you install with the full file name, `rstudio-1.3.959-x86_64.rpm` ?

**Comment by julienrbrt** [comment]
@ronblum, this is what I did with `localinstal`:

>I did still however uninstall it again and install the version 1.3.959 with localinstall, which seems to work fine too. The symlink is however still pointed at /usr/lib/rstudio/bin/rstudio and no update is available from dnf (contrary to the version 1.2 installed with localinstall).

**Comment by ronblum** [comment]
Repeating the steps starting with RStudio Desktop 1.3.959 on Fedora 31:

1. `dnf localinstall rstudio-1.3.959-x86_64.rpm` using the RStudio file installs correctly.

2. `dnf upgrade` removes everything from `/usr/lib/rstudio` (except for two symlinks) and installs 1.3.1056 in `/usr/libexec/rstudio`. The 1.3.1056 package comes from Fedora, not RStudio:

```
[root@ip-10-0-0-212 lib]# dnf whatprovides rstudio
Last metadata expiration check: 0:29:30 ago on Wed 12 Aug 2020 04:41:14 PM UTC.
rstudio-1.3.1056-1.fc31.x86_64 : RStudio base package
Repo        : @System
Matched from:
Provide    : rstudio = 1.3.1056-1.fc31

rstudio-1.3.1056-1.fc31.x86_64 : RStudio base package
Repo        : updates
Matched from:
Provide    : rstudio = 1.3.1056-1.fc31
```

3. `dnf localinstall rstudio-1.3.1056-x86_64.rpm` uses the RStudio file instead of Fedora version, which removes `/usr/libexec/rstudio` and installs everything in `/usr/lib/rstudio` as expected. In addition, this appears during installation, presumably removing Fedora's version:
```
Downgraded:
  rstudio-1.3.1056-1.x86_64                                                                                                              
```

@jmcphers Does this confirm that we have no control over what happens with `dnf upgrade`, since Fedora is maintaining a version of `rstudio`?

**Comment by Enchufa2** [comment]
@ronblum I'm the maintainer of RStudio for Fedora. We split RStudio into rstudio, rstudio-desktop and rstudio-server. The base package, rstudio, just contains common files for rstudio-desktop and rstudio-server. And yes, we use libexec. OpenSUSE does the same. Answering your question, no, packages cannot control what happens with `dnf upgrade`, but you could add `Provides: rstudio-desktop` to your build, which would help in these situations.

@julienrbrt If you are using the release version of RStudio, and not some alpha/beta/nightly build, my recommendation (Fedora hat on) is to stick to the one we provide. If you still want to manually download each new release from rstudio.com, then you'll need to add rstudio to excludes in your dnf.conf.
