### ISSUE TITLE
class cast exception on attempt to quit

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6996]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.4
    R Version       : 4.0.0

### Steps to reproduce the problem

Open an existing document, make some changes (without saving those changes), then try to quit the IDE. This modal is shown:

<img width="462" alt="Screen Shot 2020-05-28 at 2 59 10 PM" src="https://user-images.githubusercontent.com/1976582/83198345-d9cfe900-a0f3-11ea-9f0c-13badcf6d3a1.png">

Click <kbd>Don't Save</kbd>.

### Describe the problem in detail

The IDE doesn't quit.

### Describe the behavior you expected

The IDE should quit.

### Notes

Stack trace:

```
InternalPreconditions.checkCriticalType (InternalPreconditions.java:154)
InternalPreconditions.checkType (InternalPreconditions.java:138)
InternalPreconditions.checkType (InternalPreconditions.java:133)
Cast.castToString (Cast.java:81)
DesktopDialogBuilderFactory$Builder$lambda$0$Type.execute (DesktopDialogBuilderFactory.java:60)
(anonymous) (DesktopFrame__Impl.java:138)
(anonymous) (userscript:qwebchannel:353)
QWebChannel.handleResponse (userscript:qwebchannel:137)
QWebChannel.transport.onmessage (userscript:qwebchannel:86)
```

The issue appears to be caused by the callback here expecting a String:

https://github.com/rstudio/rstudio/blob/be929a082134ed5488c731014a56c7d1ea76a8dd/src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java#L113

However, the callback returns an `int`:

https://github.com/rstudio/rstudio/blob/be929a082134ed5488c731014a56c7d1ea76a8dd/src/cpp/desktop/DesktopGwtCallbackMac.mm#L172

Perhaps the newer version of GWT is more strict and disallows the implicit cast that we had here before?

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.757, R Version - 4.0.2, Windows 10 x64 - Desktop 

Issue is fixed on the latest Dailies, the IDE closes without error after dismissing an unsaved document prompt.
