### ISSUE TITLE
Saving Rmd with no YAML front matter and "---" in the source results in "Error: $ operator is invalid for atomic vectors"

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#6997]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.4.406
    OS Version      :  Mac OX
    R Version       : 

### Steps to reproduce the problem

1. Create an R Markdown document with the following text:

```markdown
<!--- html comment --->
```

2. Save the document. The following error will appear in the console:

```
Error: $ operator is invalid for atomic vectors
```

The error occurs because the YAML is extracted by splitting the document on "---" here: https://github.com/rstudio/rstudio/blob/feature/panmirror-dev/src/cpp/session/modules/SessionCodeTools.R#L2161

And of course the HTML comment provides the split.

We could split based on a more refined pattern (e.g. require that the "---" be on a line by itself) but ultimately I think we want to use a more robust parsing method. Perhaps call `rmarkdown::partitition_yaml_front_matter()`: https://github.com/rstudio/rmarkdown/blob/e72727503972bab327b6e54eea7c5950837c0d38/R/output_format.R#L692

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dfalty** [comment]
Verified fixed 1.3.1033
