### ISSUE TITLE
rstudio IDE doesn't recongize the new  r"(c:\a\b\c)" synax

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#6998]
R 4.0.0 supports a new synax to specify strings, i.e., `r"(what ever kind of text you want, no need to escape)"`, which is very convinient for Windows users, because we finally don't need to escape the windows file path that's copied from the file explorer.

However, the daily builds of RStudio IDE doesn't recongize this new synax as valid. Instead, it displays an error label saying "unexpected token".

(Note that I'm not using the very latest version of the RStudio IDE daily builds, as sometimes it's very slow to download in China. If it has been fixed already, please forgive me)

The RStudio version I use: Version 1.4.244 (build on 2020-04-24 for windows)

The R version: R4.0.0

Thanks!

![image](https://user-images.githubusercontent.com/8368933/83213827-b3fb2080-a195-11ea-8013-2cfe6f636857.png)

**Comment by jmcphers** [comment]
This is currently tracked in https://github.com/rstudio/rstudio/issues/6788.
