### ISSUE TITLE
[Bug] Failed to preview distill page

### ISSUE THREAD

**Issue by vinbrule** [rstudio/rstudio#7002]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1 3 959
    OS Version      : Mac catalina
    R Version       : 3.6.3

### Steps to reproduce the problem
0. Create a blog site using distill library
1. create a blog post
2. Build the blog post to preview it
### Describe the problem in detail
The preview panel cannot display the built blog post
### Describe the behavior you expected
Must show the blogpost
No error in Rstudio 1.2, only in 1.3
<img width="541" alt="image" src="https://user-images.githubusercontent.com/40869791/83276231-4d2e3500-a19e-11ea-9d69-853e782c6f61.png">

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Tracked in https://github.com/rstudio/rstudio/issues/6945
