### ISSUE TITLE
option to get package and function together with code completion

### ISSUE THREAD

**Issue by alp78** [rstudio/rstudio#7009]
This would be handy for conflicting functions, debugging purpose,  or communicating the code to others who are not familiar with used packages. Having to write down the packages manually is annoying and time consuming, it could be avoided with code completion.

this request has 2 parts:

**1) option to include masked functions in the completion pop-up menu**

Example:

`x magrittr::set_names() masks purrr::set_names()`

while typing `set_n` and tab in the text editor, we only see the unmasked function `magrittr::set_names()` in the completion menu. I'd like to be able to pick the one I need from the menu.

**2) option/shortcut to get code completion to write down both `package::function()`** 

Example:

for `magrittr::set_names()` when tabbing twice `set_n` in the text editor, code completion only writes down the function `set_names()`. I'd like an option/shortcut to get completion to write down the full designation `magrittr::set_names()`.

**Comment by Bijaelo** [comment]
feature 2) could further reduce time while creating packages, where prefixes are highly recommended.

**Comment by ronblum** [comment]
@alp78 Thank you for the suggestions, and @Bijaelo for the added reason. We'll review them as we continue developing RStudio.

**Comment by alp78** [comment]
> @alp78 Thank you for the suggestions, and @Bijaelo for the added reason. We'll review them as we continue developing RStudio.

Great, looking forward!
