### ISSUE TITLE
RStudio 1.3.959 Find and Replace in Files Regex does not work on Win 10 Home

### ISSUE THREAD

**Issue by yogat3ch** [rstudio/rstudio#7012]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      :  Windows 10 Home V 1903
    R Version       : MRO 3.5.3

### Steps to reproduce the problem
1. Create an R file and add the text: `test 2`
2. Save the file in a directory of your choice
3. Hit Ctrl + Shift + F to bring up find and replace in files
4. Point it to the directory in which the R file is saved
5. Type `test` and select the checkbox for "regular expressions"
6. Search
7. Note that it shows the single result
8. Add the regex token `\s` indicating a space following `test` IE `test\s`
9. Search
### Describe the problem in detail
RStudio will find no matches. The same holds true if R-like escaping `\\` is used before the `s`.
### Describe the behavior you expected
Find and replace matches on the same string but includes the space.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
This doesn't appear to be a regression so I changed the milestone to 1.4. Can reproduce on Windows in 1.2 and 1.3.

**Comment by melissa-barca** [comment]
I've confirmed that the repro provided does not work with the version of grep we use with windows so to fix this issue we'll need to bundle a different version of grep which is being tracked here in #3572

**Comment by kevinushey** [comment]
Looks like we opted to fix this in 1.5 instead -- moving out of 1.4 and tracking in https://github.com/rstudio/rstudio/issues/3572.
