### ISSUE TITLE
Error markdown rendering on https://rstudio.com

### ISSUE THREAD

**Issue by courtiol** [rstudio/rstudio#7019]
This is probably not the good place to post this, but I could not find better.
On the RStudio's website https://rstudio.com/products/rstudio/download/#download, one markdown link is not rendered properly.
Look at the bottom of the screenshot I just took:
<img width="1095" alt="Screen Shot 2020-06-02 at 09 20 45" src="https://user-images.githubusercontent.com/7499666/83491801-9b9b4680-a4b2-11ea-8169-3d1577b2eded.png">

**Comment by ronblum** [comment]
@courtiol This is the right place, and thank you for letting us know!

**Comment by jmcphers** [comment]
All fixed up. https://rstudio.com/products/rstudio/download/
