### ISSUE TITLE
MTurkR:Not able to connect to the server

### ISSUE THREAD

**Issue by kalyanikoul** [rstudio/rstudio#7024]
Using MTurkR package, I am trying to connect to call the API - AccountBalance(sandbox = TRUE)
I am getting below error.
Error in curl_fetch_memory(url = host, handle = h) : 
  Could not resolve host: mechanicalturk.sandbox.amazonaws.com

Can someone help to resolve the same.

Thanks.

**Comment by jmcphers** [comment]
Sorry, we can't help with RStudio or R questions here. The Github Issues page is for tracking bugs in RStudio itself. 

Please visit our community site to ask questions:

https://community.rstudio.com/

Hope you're able to find what you're looking for!
