### ISSUE TITLE
Switching projects stalls on Ubuntu 20.04

### ISSUE THREAD

**Issue by kiernann** [rstudio/rstudio#7025]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.0

### Steps to reproduce the problem

Open RStudio with no project selected. The IDE looks normal and code can be run without issue. Then, immediately chose any project from the drop down menu. The bug does not happen every time, but most often when attempting to chose a project very quickly after the program is started,

_Edit:_ The same bug can seemingly be reproduced when opening the git commit window immediately after pushing changes.

### Describe the problem in detail

The window stalls when switching projects, quickly displaying nothing buy a white screen. The program can then not be closed by any method than `pkill -f rstudio`.

![Screenshot from 2020-06-02 13-56-09](https://user-images.githubusercontent.com/18021678/83553196-db752480-a4d8-11ea-8926-63cc12449446.png)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
There are a couple of known issues with Ubuntu 20. Do you still see this issue in our preview release?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by kiernann** [comment]
I was actually having the same bug with the last preview, that's why I switched to the stable a few weeks back. I've just installed the latest preview (1.3.1004). I haven't been able to reproduce this bug yet!

**Comment by jmcphers** [comment]
Great!
