### ISSUE TITLE
Plots are rendered differently on different monitors

### ISSUE THREAD

**Issue by Mashin6** [rstudio/rstudio#7028]
I originally reported the problem in RMarkdown project [4521](https://github.com/rstudio/rstudio/issues/4521) and this might be issue related to [1827](https://github.com/rstudio/rmarkdown/issues/1827)

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : macOS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem
1. In R Markdown document create a plot that has many labels
2. Move R Studio window to different monitor
3. Slightly resize R Studio window
4. Rerun plot code

### Describe the problem in detail
RStudio renders figures inconsistently depending on which monitor is the code executed. When I run code chunk on retina display the text in the figure is rendered smaller, but when I move the window to my second 2K display (ThinkVision 23.8'' P24H-10 QHD) all the labels and margins are rendered way larger, which dramatically change how the figure looks like.

Here is a sample code (cowplot package is to exaggerate the issue, but it behaves the same when cowplot is deactivated) 

```
{r message=FALSE, warning=FALSE, fig.width = 8, fig.height = 6}
library(tidyverse)
library(cowplot)

data <- data.frame(x = rnorm(999), y = rep(c("a", "b", "c")))

p1 <- p2 <- data %>% ggplot() +
geom_histogram(aes(x = x, fill = y)) +
facet_wrap(vars(y)) +
scale_x_log10() +
labs(title = "Test subtitile")

plot_grid(p1, p1, labels = c("A", "B"), ncol = 1, label_size = 20) +
draw_plot_label("Test main titile", size = 25, x = 0.5, y = 1.015, hjust = 0.5, vjust = 0.5) +
theme(plot.margin = unit(c(1.5,0,0,0), "cm"))
```

Output 1:1 screenshots:

![83458112-df993780-a42f-11ea-95df-9f015dfdd99f](https://user-images.githubusercontent.com/5265707/83567138-21d57e00-a4ef-11ea-948c-022c750bf64e.png)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by EoinTravers** [comment]
I have the same issue.
I can add the following:

# This isn't restricted to ggplot

    ```{r fig.width=4, fig.height=4}
    plot(iris$Sepal.Length, iris$Sepal.Width)
    ```

Retina display:

![image](https://user-images.githubusercontent.com/3819320/110457567-aed2e680-80c2-11eb-8ce8-30c909e51d0d.png)

External display:

![image](https://user-images.githubusercontent.com/3819320/110457617-babea880-80c2-11eb-858b-74b7486c93f0.png)


# HTML Output Matches External Display

When the document is knit to html, using the default options, the generated images are small, the same as those seen on the external display.

# `fig.retina`

Kniting with default settings, the knitr `fig.retina` parameter is set to 2.

    knitr::opts_chunk$get('fig.retina')
    ## [1] 2

Changing this in the yaml 

    ---
    title: "Figure Problems"
    output: 
      html_document:
        fig_retina: 1
    ---

is registered...

    knitr::opts_chunk$get('fig.retina')
    ## [1] 1

...but doesn't change the size of the output figures, suggesting the issue might be somewhere in the knitr or rmarkdown packages.

Changing the setting for a specific chunk also has no effect on the output.

    ```{r fig.width=4, fig.height=4, fig.retina=2}
    knitr::opts_chunk$get('fig.retina')
    plot(iris$Sepal.Length, iris$Sepal.Width)
    ```


# System Info

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16
RStudio: 1.4.1103 (desktop)
```

**Comment by cderv** [comment]
I don't know if there is an issue with RStudio or not. Regarding last comment, I answered here https://github.com/rstudio/rmarkdown/issues/1827#issuecomment-1008931493 on how `fig.retina` plays out to me.

**Comment by EoinTravers** [comment]
[This discussion on twitter](https://twitter.com/LisaDeBruine/status/1447956903095644171) is relevant to this issue, and includes [this nice but hacky fix](https://gist.github.com/debruine/baa61e561935d5e0df1ea0f294399c6c).

**Comment by Mashin6** [comment]
Referencing related issues #2098 and #7892. (thanks @cderv for looking those up)

**Comment by cderv** [comment]
@ronblum would it be possible to reopen this issue closed by stale bot ? Seems still an issue and related to a few others about resolution of figure in Notebook . Thanks!

**Comment by jeffvroom** [comment]
I see a few problems that mostly center around [this code] (https://github.com/rstudio/rstudio/blob/2c92cd9adebc7c18c052d2547948f07db835b13c/src/cpp/session/modules/NotebookPlots.R#L27-L30) where it sets up the device to render the graph to a PNG image. 

1) It hardcodes the dpi used to convert inches to pixels as 96 rather than looking at the dpi parameter (if one is supplied).
2) It ignores `fig.retina` if it's being set in the annotations but instead always uses `devicePixelRatio` that comes from the IDE that gets it from the browser's `window.devicePixelRatio`.  [Here](https://github.com/rstudio/rstudio/blob/2c92cd9adebc7c18c052d2547948f07db835b13c/src/cpp/session/modules/rmarkdown/NotebookExec.cpp#L169) is where we get fig.width/height but do not get fig.retina to override the devicePixelRatio.
3) It multiplies the width and height by devicePixelRatio as well as `res` and that doubles the effect. So in my test, with fig.width/fig.height = 2", the resulting resolution is 768 that would be 4" on a display with 96 dpi.  

In at least one customer situation, it seems like we need a way to disable the effect of the retina, or to at least not double it up because the results of ggplot are not consistent with other graphics they are rendering.

**Comment by jeffvroom** [comment]
I believe this is where R is computing the scaling factor based on 'res' supplied above:

https://github.com/wch/r-source/blob/2370ec2512d2e78eea678213eb141eae878718c4/src/modules/X11/devX11.c#L3001-L3006

confirming to me that we don't have to do the scaling twice. These particular plots have fixed_width attribute set and the code to render the img tag is here:

https://github.com/rstudio/rstudio/blob/dc7f9e161b1b1fb0276de629b41ccd2c22781720/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkPlotWidget.java#L58-L62

To correct the plot size, the easiest thing would be to just remove the " * pixelRatio" in NotebookPlot.R in all 6 places where it appears. The img tag is already correcting for devicePixelRatio by scaling up the image by that factor. 

The downside of that is less clear plot images on retina. The better solution would be to only scale up 'res' (not width and height) and change the img tag to have width=(1/devicePixelRatio)% - i.e. width=50% for retina. That way, we'd have clearer plots. We could continue setting max-width to this value, so the image fits into the console window, even if a larger plot size is specified than will fit in the console or change it to width so the image is clipped if it's too large. I can see advantages either way... if there's other adjacent graphics, it looks wrong to display the wrong size image.

BTW, I found an easier to way to check the devicePixelRatio used by RStudio is:

`.Call("rs_devicePixelRatio")`

**Comment by ronblum** [comment]
Moving to Cherry Blossom, in order to verify that it's fixed by PR #12324. If it's not, we'll reassign it to the current milestone.

**Comment by jonvanausdeln** [comment]
I tried on latest daily, 2023.03.0-daily+280. However, I would like confirmation from @Mashin6 and/or @EoinTravers that this solves their issue.

**Comment by Mashin6** [comment]
I played a bit with the latest `2023.03.0-daily+293` and for me the main issue seems to be gone. Figures are rendered with the same proportion of text size, spacings, etc. 
However I noticed that at different screen resolutions/scalings the figures are rendered at different pixel dimensions. My suspicion is that the problem is somehow related to non-HiDPI resolutions/monitors.

retina display - all resolutions - figure dimensions 768 × 768 pixels
![retina-1512x982](https://user-images.githubusercontent.com/5265707/217197783-107ca161-871a-43ed-a505-f8a16a9ff1ec.png)

External Monitor - 2560x1140 (native) -  figure dimensions 384 × 384 pixels
![External-2560x1440](https://user-images.githubusercontent.com/5265707/217199707-d339bc69-698f-4c30-b4b9-7015c367b73e.png)

External Monitor - 1280x720 (HiDPI scale) -  figure dimensions 768 × 768 pixels
![External-1280x720](https://user-images.githubusercontent.com/5265707/217199996-96c3d7e7-0dda-489c-8a6e-8d5cbde5334a.png)

**Comment by jonvanausdeln** [comment]
Thank you @Mashin6! Since the main issue is resolved, I will close out this issue. Would you be able to open a new issue on what you are still experiencing? I would be happy to open if you'd like, I just don't want to miss any details.

**Comment by frederikziebell** [comment]
@jeffvroom Is there a way to set the device pixel ratio from a current RStudio session, similar to the `.Call` you described above to view it?

**Comment by kevinushey** [comment]
@frederikziebell I suspect not, but you might want to file a separate issue to make sure your request isn't lost.
