### ISSUE TITLE
Option to show Console errors/messages/warnings in same color as normal output

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7029]
R sends normal output to stdout, and the output from `message()`, `warning()`, `stop()`, and `stderr()` to... stderr.

The RStudio Console has one style for normal stdout text, and another (typically red) for stderr, making all those classes stderr-based output look like dire warnings.

See #2574 for more discussion (using that issue to track possibility of showing these different classes of output, e.g. warnings vs errors, in different colors).

This issue tracks request for feature to turn off the current behavior and have stdout and stderr output display the same way in the RStudio Console.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.757, R Version - 4.0.2, Windows 10 x64 - Desktop 

The option 'Different color for console error output (requires restart)' has been added to Tools > Global Options > Console. Tested enabling and disabling the option, verified console error output color changes appropriately to the setting.
