### ISSUE TITLE
Slowness in Find in Files panes

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#7036]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.958 (likely started before)
    OS Version      : macOS Mojave 10.15.6
    R Version       :  3.6.1 (2019-07-05)

### Steps to reproduce the problem

1. Bring up Find in Files pane. (CMD + SHIFT + F)
2. Select the drop down for 'Search the files' or 'Exclude these files'.
3. Observe the delayed opening

![image](https://user-images.githubusercontent.com/5323711/83695798-ad164880-a5af-11ea-83da-5b3e877843bd.png)

### Describe the problem in detail
With the 1.3 release, the drop down menus on this pane started taking slightly longer to load ("a distinct beat"). This only happens the first time they're dropped down on the pane. 

### Describe the behavior you expected
Menu should open quickly. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
I was not able to reproduce this but it happens consistently for Jenny Bryan.

**Comment by melissa-barca** [comment]
Hi @R-Hannibal is there someone who can help with the repro on this? It's a potential regression from 1.2 to 1.3

**Comment by rich-rstudio** [comment]
@melissa-barca I can try to help repro this

**Comment by melissa-barca** [comment]
I dug into this some more and used dev tools to analyze the performance but couldn't find anything taking abnormally long. I'm closing this for now, but if more users have issues we can reopen it.
