### ISSUE TITLE
RStudio Server Preview 1.3.1004 not working on Ubuntu 18 server

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#7037]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1004
    OS Version      : Ubuntu 18.04.4 LTS
    R Version       : 4.0.0

### Steps to reproduce the problem
* Install the preview version
```
wget https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64/rstudio-server-1.3.1004-amd64.deb
sudo gdebi rstudio-server-1.3.1004-amd64.deb
```
### Describe the problem in detail
After upgrading no error message is returned on the terminal but it's not possible to open an RStudio session (Chrome  83.0.4103.61)
![image](https://user-images.githubusercontent.com/14981085/83703705-d8ac2980-a5d5-11ea-8883-945e3fe205be.png)
This is what I get after running `sudo rstudio-server verify-installation`
```
 sudo rstudio-server verify-installation
04 Jun 2020 00:53:51 [rserver] ERROR system error 2 (No such file or directory) dio::core::system::runProcess(const string&, const string&, rstudio::core::systeSystem.cpp:2296; LOGGED FROM: rstudio::core::Error rstudio::core::system::launchonfig, rstudio::core::system::ProcessConfigFilter, PidType*) src/cpp/core/system
```
I have already tried:
* Resetting RStudios Server's state (all three configuration files).
* Clearing cookies on my browser

If I downgrade to the stable version (1.3.959) everything goes back to normal

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
This is a dup of #6883. Unfortunately a bad code merge caused this bug to be re-introduced in the 1.3.1004 preview build of RStudio Server.

The next preview build will contain the fix. In the meantime try:
```
wget https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64/rstudio-server-1.3.1006-amd64.deb
sudo gdebi rstudio-server-1.3.1006-amd64.deb
```
