### ISSUE TITLE
RStudio doesn't render when using multiple monitors

### ISSUE THREAD

**Issue by StuartHemming** [rstudio/rstudio#7040]
### System details

    RStudio Edition : Desctop
    RStudio Version : 1.3.959
    OS Version      :  Win 10
    R Version       : R version 4.0.0 Patched (2020-05-25 r78571) -- "Arbor Day"

### Steps to reproduce the problem

-  Open RStudio on a machine with multiple monitors (in my case I have a laptop and external screens)
- Carry out _any_ operation, even just typing in the console window, all is good.
- Move the window on to a 2nd monitor. Try typing. Noting appears. Mouse clicks on the menus _appear_ to work, but then none of the selected actions appear to do anything.
- Drag the window back on to the main screen and all of the typing and/or actions selected previously will be rendered.

### Describe the problem in detail
When _any_ RStudio window is not on the main monitor/screen then any action/input directed at such windows is not rendered.

**Note:** This "functionality" is limited to RStudio. This is a long standing setup and I use it for many applications including Visual Studio, and Office. Note also that RGui.exe works just fine on all monitors/screens

### Describe the behavior you expected
I would expect RStudio to operate correctly on any screen.

- [X ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@StuartHemming Thank you for raisin the issue! Does changing the rendering engine make a difference? The troubleshooting doc https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors shows how to do so.
