### ISSUE TITLE
Auto grow margin width

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#7042]
Hiya, quick & easy one here - 
Any chance the margin width (when used) could be allowed to / default to auto-grow as a function of number of lines in the script (floor to factor of 10) + extra space for debug icons?
Thanks. And super thanks for fixing that chromium launch bug on linux in the latest preview, y'all rock.

**Comment by jmcphers** [comment]
This would be pretty tricky. Is there another editor that does this well? What do you use this feature for?

**Comment by SimonDedman** [comment]
"Is there another editor that does this well?" I don't know, I only use RStudio.

"What do you use this feature for?" Referencing line numbers in notes, and if you have a margin option and then keep writing more script, the line numbers go from 1 to 10 to 100 to 1000 and unless you manually resize then the coding warnings and indentations can cause the numbers to get moved under the margin in some places but not others. I thought it was a bug for ages until I realised.

I'm surprised it'd be tricky but my program coding is worse than my R coding which is saying something. Still I figured it'd be
padding for debug icons & function expando + (n_pixels * factor of 10(script line length))

**Comment by SimonDedman** [comment]
Perhaps screenshots would help. I think this is actually a bug whereby something causes the margin behaviour to break after RStudio is initially loaded. Initial state:
![image](https://user-images.githubusercontent.com/4599748/224121682-2ee84953-cf73-4bf4-a22a-20cb74c1a925.png)

I can't find any instance of it going wrong at the moment but will update when I do. Essentially: the margin becomes too small for the line numbers, and the little arrows are no longer present to expand/contract functions/brackets.
