### ISSUE TITLE
First Esc keypress in IDE is not handled

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7045]
### System details

    RStudio Edition : Server
    RStudio Version : Development (master)
    OS Version      :  OS X
    R Version       :  3.6

### Steps to reproduce the problem

Load up the IDE and then do something which triggers a completion (e.g. type "plo" in the console or in a source editor). Once the completion popup is show, press Escape. The popup is not dismissed. Subsequent presses of Escape work as expected.

Note that this also occurs if I do something in visual mode which triggers a visual mode completion popup (e.g. type ":smi") so it's unlikely to be related to completion handling per se, but more likely some global keyboard shortcut handling code.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: Windows Desktop, RStudio Version 1.3.1023.

Was able to successfully reproduce the original issue on RStudio 1.3.1008 (only seemed to occur when using the first escape command on a per-session basis), but it is now fixed in the latest 1.3 patch preview.
