### ISSUE TITLE
Move Console options to a new pane

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7047]
User preferences for the Console are currently scattered amongst several (increasing crowded) locations in the Global Options Dialog.

A new Console pane should be added with a top-level entry in the left column, possibly after "Code".

Items to move include:

<img width="593" alt="screenshot of global options / general / advanced" src="https://user-images.githubusercontent.com/10569626/83913548-73b31980-a724-11ea-902d-e49c3f7a5695.png">

<img width="592" alt="screenshot of global options / code / display" src="https://user-images.githubusercontent.com/10569626/83913804-de645500-a724-11ea-97a8-8c497c9d2996.png">

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.757, R Version - 4.0.2, Windows 10 x64 - Desktop

Verified that all the designated Global Options have been successfully moved to the new Console pane (and removed from their original pane homes). Limited checks of actual option functionality, but everything seems stable thus far.
