### ISSUE TITLE
Display issue with "next columns" chunk output for remote tables

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#7048]
Basically the display of the tibble header (column names + connection details) gets corrupted when I click on the arrow for the next columns for remote (database tables).
(Crappy title, sorry.)

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.436 (had the bug for all 1.4 versions I believe)
    OS Version      : OS X 10.15.4
    R Version       : 3.6.2

### Steps to reproduce the problem
```
library(tidyverse)
library(magrittr)
library(DBI)

con <- dbConnect(RSQLite::SQLite(), ":memory:")

mtcars_rm <- con %>% copy_to(mtcars)

mtcars_rm
```

### Describe the problem in detail
First page displays ok 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/33321678/83922118-cbb24600-a74d-11ea-8c29-9fbf40c7ab00.png">

Gets corrupt when clicking on arrow to get next columns
<img width="811" alt="image" src="https://user-images.githubusercontent.com/33321678/83922164-dbca2580-a74d-11ea-80ca-7328ba6395f6.png">

And worse when I keep going for next column (or previous)
<img width="827" alt="image" src="https://user-images.githubusercontent.com/33321678/83922189-e71d5100-a74d-11ea-8f06-148302e899e8.png">

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
@gregleleu, thank you for finding and reporting this issue and adding so much detail, we appreciate users like yourself helping us to make the RStudio experience better (no points subtracted for the title 😜). 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by dfalty** [comment]
@gregleleu the formatting looks good to me using your example on version 1.4.874. Please reopen if it is not fixed for you.
