### ISSUE TITLE
Check Spelling via command palette inserts blank line in document

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7056]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.444
    OS Version      : Centos7 (Server), macOS (Desktop)
    R Version       : doesn't matter

### Steps to reproduce the problem
- open a file that supports spell checking such as an RMD or TXT file
- put cursor in row 1, col 1
- <kbd>Ctrl+Shift+P</kbd> to show command palette
- type `check spelling` then <kbd>Enter</kbd> to execute "Check spelling in document"
- spell check runs and shows result

### Describe the problem in detail
- source document is modified via <kdb>Enter</kdb> key
- if there is a spelling error, the first match is selected and replaced by a blank line

### Describe the behavior you expected
- <kdb>Enter</kdb> key must not be passed through to the document

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
The fix here is probably going to be to preventDefault on the Enter keydown event that closes the palette.

**Comment by jmcphers** [comment]
The gift of prophecy!

**Comment by dfalty** [comment]
Verified the check spelling command works as expected following the steps above on version 1.4.874.
