### ISSUE TITLE
Show job progress on RStudio server tab

### ISSUE THREAD

**Issue by Tazinho** [rstudio/rstudio#7059]
Hi, I couldn't find a similar issue, so I hope this is not a duplicate.

As a user of rstudio server I sometimes wait for long calculations to be finished and do other stuff in the browser. As I don't know when the calculations finish, I need to occasionally check, if the calculations are finished. Maybe this could be done easier, as one could show a little progress bar of the calculations in the rstudio server tab. I don't know enough about the IDE to know if this is possible, but at least if one has 1 job running, sth. like the following screenshot would be useful

![grafik](https://user-images.githubusercontent.com/11295192/84012742-4f4f7b00-a978-11ea-80e5-34de957cfe42.png)

(The screenshot is taken from here:
https://lifehacker.com/progress-bar-on-tab-shows-you-web-pages-progress-in-fir-5822845 )

**Comment by jmcphers** [comment]
Great idea, but this is unfortunately not possible -- the screenshot above is from a Firefox extension that shows a page's loading progress, and can't be customized to show anything else.
