### ISSUE TITLE
Error when scrolling a document then quickly closing it with realtime spellcheck on

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#7065]
1. Open an Rmd file with realtime spellchecking turned on
2. Scroll the document then close it quickly
3. See error in console

What's happening is that the setTimer callback in TextEditingTargetSpelling for linting is being called onto a null DocDisplay. Fixing this isn't as mega trivial as I hoped after 15 minutes of investigation but shouldn't be too bad.

**Comment by adamconroy** [comment]
I think this is actually fine. After some more testing it's consistent with the behavior that we have across the app for async callbacks and the user closing the document in the middle of it. TextEditingTarget has a few of these (like onCursorChanged) and we just log the error and don't surface anything to the user.

**Comment by R-Hannibal** [comment]
Closing as 'Out of Scope'.

Please see the previous comment.
