### ISSUE TITLE
Text is hidden in the lower part of Editor's window

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#7071]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1008
    OS Version      : Win 10
    R Version       : 4.0.1

### Steps to reproduce the problem

Sometimes it happens and I do not know to reproduce it. Maybe I will notice later.

Maybe it will be helpful:

1) I was working in the RStudio project to develop a package.
2) I was modifying `README.Rmd`.

### Describe the problem in detail

In a lower half of the editor's window, no text is visible (annotated as the red square in the gif). But the chunk buttons are visible.

In the gif I scroll up and down to make the issue visible.
![RS-half-window](https://user-images.githubusercontent.com/12725868/84125612-72942c00-aa45-11ea-81b5-d46d54218fa3.gif)

### Describe the behavior you expected

<details>
 <summary>Details</summary>

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
</details>

**Comment by kevinushey** [comment]
Thanks for the bug report! Interestingly, the chunk toolbar (e.g. the Run icon) appears to still get rendered in the correct place; it's just the Ace editor that's not rendering content in that region.

Does the issue go away if you resize the editor width? Does it affect other open documents, or just the one you're currently interacting with?

**Comment by GegznaV** [comment]
No, resizing had no effect: the "empty" half was proportional to the height of the window. The problem disappeared when I closed and reopened the document.

**Comment by kevinushey** [comment]
Thanks. Please let us know if you're able to find a way to reproduce the issue more consistently.

**Comment by GegznaV** [comment]
I close this as I was not able to reproduce this anymore. I'll reopen it if the issue in RStudio repeats.
