### ISSUE TITLE
Port RStudio to signals2?

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#7074]
When updating RStudio in openSUSE, I stumbled over this line:
https://github.com/rstudio/rstudio/blob/5b672c3b686a154e8b49abad2900a09a666564f6/src/cpp/CMakeLists.txt#L281

RStudio is working pretty well with signals2 in openSUSE Tumbleweed, so I guess this has been just forgotten?

**Comment by kevinushey** [comment]
RStudio should automatically use signals2 if your version of Boost is recent enough, though -- are you not seeing that?

(We should eventually remove that and just drop support for the older deprecated signals, though)

**Comment by kevinushey** [comment]
I see you followed up in https://github.com/rstudio/rstudio/issues/7075 -- let's continue the discussion there.
