### ISSUE TITLE
Boost version detection in src/cpp/CMakeLists.txt does not work

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#7075]
The version comparison in `src/cpp/CMakeLists.txt` to detect whether boost signals2 or signals1 should be used is broken:
https://github.com/rstudio/rstudio/blob/5b672c3b686a154e8b49abad2900a09a666564f6/src/cpp/CMakeLists.txt#L283

The issue is that `Boost_VERSION` is for example `1.71.0` and not `107100` as the code expects. This can be fixed as follows:
```patch
if(NOT RSTUDIO_BOOST_SIGNALS_VERSION)
-   if (Boost_VERSION LESS 106900)
+   if (Boost_VERSION VERSION_LESS 1.69.0)
      set(RSTUDIO_BOOST_SIGNALS_VERSION 1)
```
Then the signals version setting works as expected.

**Comment by kevinushey** [comment]
From the FindBoost documentation (https://cmake.org/cmake/help/v3.15/module/FindBoost.html):

```
Boost_VERSION          - if CMP0093 NEW => same as Boost_VERSION_STRING
                         if CMP0093 OLD or unset => same as Boost_VERSION_MACRO
```

So, the issue here depends on which CMake policy is set. I think we need to explicitly set the CMake policy or just avoid using `Boost_VERSION` and use `BOOST_VERSION_MACRO` directly.

**Comment by kevinushey** [comment]
(or, of course, use your fix with `BOOST_VERSION_STRING`)

**Comment by dcermak** [comment]
> From the FindBoost documentation (https://cmake.org/cmake/help/v3.15/module/FindBoost.html):
> 
> ```
> Boost_VERSION          - if CMP0093 NEW => same as Boost_VERSION_STRING
>                          if CMP0093 OLD or unset => same as Boost_VERSION_MACRO
> ```
> 
> So, the issue here depends on which CMake policy is set. I think we need to explicitly set the CMake policy or just avoid using `Boost_VERSION` and use `BOOST_VERSION_MACRO` directly.

I have actually tried both settings for the policy, but that did not make a difference. Although I guess that I messed up something as it *should* work.
