### ISSUE TITLE
Install packages helper - more intelligent ordering & stop on fail?

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#7078]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1011
    OS Version      : Xubuntu20.04
    R Version       : 4.0.1

### Steps to reproduce the problem
Open existing script, helper suggests installing packages, allow it to do so.

### Describe the problem in detail
Lots of packages depend upon the same other packages. If installing those dependencies fails (e.g. Rcpp) because a linux package isn't installed by the user, then the package install helper will just plough into the next package, which also has Rcpp as a dependency, will download it again, try to install it again, fail again, delete it again, and on and on. It ends with "✔ Packages successfully installed." which is very misleading - it's true, some were, but it intuitively implied ALL packages were successfully installed, which they may not have been. If the last package installed correctly you'll likely not see any error messages either. So then you have to scroll up and address issues sequentially. And, let's be real, you'd have to do it this way *without* the helper. The issue is the helper could help more, and the way it works currently means it takes ages on a fast machine to single-thread install attempt the same packages over and over.

### Describe the behavior you expected
Ideally have the feature: compile all dependencies of all packages first, dedupe, start with highest level dependencies, and go through sequentially, stopping if one fails. This allows the user to address the issues and retry.

- [X ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by SimonDedman** [comment]
Also the completion text itself is more than just misleading, it can be plain wrong:

> checking for gdal-config... no
> no
> configure: error: gdal-config not found or not executable.
> ERROR: configuration failed for package ‘sf’
> * removing ‘/home/simon/R/x86_64-pc-linux-gnu-library/3.6/sf’
> 
> The downloaded source packages are in ‘/tmp/Rtmp64YkGA/downloaded_packages’
> 
> ✔ Package 'sf' successfully installed.
> Warning message:
> In utils::install.packages("sf", repos = "https://cloud.r-project.org") :
>   installation of package ‘sf’ had non-zero exit status

**Comment by ronblum** [comment]
@SimonDedman Thank you for the suggestion and bug report! Would you mind opening a separate issue for the bug? I want to make sure that if one is addressed, the other one isn't lost. Thanks! And in either case, we'll review them as we continue development of RStudio.

**Comment by SimonDedman** [comment]
Sorry for the delay!
