### ISSUE TITLE
Cannot write tilde in preview release

### ISSUE THREAD

**Issue by Farbfetzen** [rstudio/rstudio#7092]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1014
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : 4.0.1

This bug was also reported by others in the community forum:
https://community.rstudio.com/t/rstudio-v1-3-1004-1-preview-cannot-insert-tilde/68512

### Steps to reproduce the problem

Open RStudio and attempt to write a tilde: "~" either in the console or in a script. I have a german keyboard so I press `Ctrl` + `Alt`+ `+` or `AltGr` + `+`.

### Describe the problem in detail
Instead of writing a tilde RStudio's request log opens.

### Describe the behavior you expected
A `~` is inserted.
This is working correctly in version 1.3.959.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
@BastiHz, thanks again for finding and reporting this issue. 

We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by BastiHz** [comment]
Thank you. It's fixed in 1.3.1023.

**Comment by R-Hannibal** [comment]
Excellent, thanks for the assist @BastiHz!
