### ISSUE TITLE
Autoloading packages in the background?

### ISSUE THREAD

**Issue by Vivek-Prakash-US** [rstudio/rstudio#7096]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1014 zip
    OS Version      :  Windows 10
    R Version       :  3.6.3

### Steps to reproduce the problem

I have a script open with focus containing only the lines below:

`library(magrittr)

library(data.table)

library(sf)

library(ggplot2)

library(tidycensus)

library(spdep)

spatialreg::sacsarlm()`

### Describe the problem in detail

Rstudio seems to be loading via namespace (but not attaching) packages that are used via the "::" method. With the above script in focus, without running any code whatsoever, here is the session info:

![image](https://user-images.githubusercontent.com/19595852/84310619-8ca63b00-ab27-11ea-9b65-1d1d7f13068a.png)

It's also registering methods. This at least pops up the usual warning. To trigger the behavior just save the document.

### Describe the behavior you expected
To do nothing!

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Vivek-Prakash-US** [comment]
Thank you for the clarification!

**Comment by martinamorris** [comment]
I'm not sure this is the behavior one would want (or expect).  For example, when working on different versions of packages.  Here's what I'm running into:

1. Install from github the desired set of packages into a personal library 

```
release_lib <- "~/R/release-library"
remotes::install_github("statnet/ergm.ego@master",
                        lib = release_lib)
```

Works, and installs the other github dependencies listed in the DESCRIPTION.

2. try to load the set of packages, with an explicit library order:

```
defaultPaths <- .libPaths()
.libPaths(c(release_lib, defaultPaths))
.libPaths() # check, works fine

library(ergm.ego)

Loading required package: ergm
Loading required package: network
Error in value[[3L]](cond) :
  Package ‘network’ version 1.16.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘network’ is imported by ‘ergm’, ‘networkDynamic’, ‘tergmLite’, ‘tergm’,
‘EpiModel’ so cannot be unloaded
```

So you probably won't reproduce this, unless you have **another tab open,** just sitting there, but not run, with an Rmd script that calls the package `EpiModel`, and you have the CRAN version of `EpiModel` installed in the **second** position in your modified libPath.

The only way I can load the right stack of packages from `release_lib` is to close all other script tabs that might be  harboring a library call that will sabotage the entire session.  Ironically, those calls in my other scripts are also preceded by libPath modifications to ensure they call from the right library, but the diagnostics doesn't see that context.

I know you folks do a lot of development, so what is the procedure you recommend?  I have 3 working libraries going at all times, default, github@master and github@dev (our development branch).   And often have multiple tabs open in a session to copy/paste code snippets.  Is there a way to prevent the session from loading the namespaces from other open but inactive tabs?

thx!
