### ISSUE TITLE
Keyboard tabbing issues in Accessibility Options dialog

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7098]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.458
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- Help / Accessibility / Accessibility Options
- Use Tab key to move forward through dialog and wrap around to beginning
- Use Shift+Tab key to move backwards through dialog and wrap back to end
- Now select Announcements tab and repeat tabbing experiments

### Describe the problem in detail
- When Shift+Tab is used the tab stop doesn't wrap around, it can escape the dialog

### Describe the behavior you expected
- Tabbing should always behave consistently and never leave a modal dialog

- (solution) We need to invoke refreshFocusableElements() on the container dialog when a different tab is selected in the case of a dialog where tab control is first thing in the dialog
- also impacts the Pro dialogs for Adhoc launcher jobs and opening shared projects

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed on both Desktop 1.4.944 and Server Pro 1.4.940-1
