### ISSUE TITLE
When RStudio is open, the entire computer slows down/lags

### ISSUE THREAD

**Issue by PietroD** [rstudio/rstudio#7100]
**System details**

```
Machine: iMac (Retina 5K, 27'', 2017 -  Radeon Pro 570 4GB VRAM) 
OS: macOS High Sierra (10.13.6)
RStudio Edition : Desktop
RStudio version: RStudio Preview v1.3.1014-1 
                 RStudio v1.2.5042
                 RStudio Daily 1.4.285
R version: 3.6.2
```

**Steps to reproduce the problem**

   Just open RStudio

**Describe the problem in detail**

When RStudio is open, every now and then (few seconds, variable time) I notice the cursor to freeze while typing or moving up and down with the arrows. At the same moment it freezes, I can also notice some other app freezing, for example, if I am listening to music on youtube or spotify, the music stops for a fraction of a second.
Also realized that even if I am not using RStudio but it is just open and I am scrolling web pages, then I notice the web page freezing for that fraction of a second like if RStudio is causing everything to lag.

Thanks

**Comment by kevinushey** [comment]
Do you see this issue with older releases of RStudio (e.g. v1.1)? Older versions of RStudio are available here: https://rstudio.com/products/rstudio/older-versions/

**Comment by PietroD** [comment]
I have to update that the problem originally occurred on iMac (Retina 5K, 27 pollici, 2017 -  Radeon Pro 570 4GB VRAM) while, **with the same settings**, the problem does not occurr on a MacBook Pro Retina 15'' mid 2012 (NVIDIA GeForce GT 650M 1024 MB and Intel HD Graphics 4000 1536 MB). Maybe related to graphics/high-res display?

**Comment by PietroD** [comment]
> Do you see this issue with older releases of RStudio (e.g. v1.1)? Older versions of RStudio are available here: https://rstudio.com/products/rstudio/older-versions/

Hi @kevinushey , I did a short test yesterday night and the problem was less evident, but I have to do more testing (i.e. more usage with that version), but I am on a different computer right now.

**Comment by PietroD** [comment]
> > Do you see this issue with older releases of RStudio (e.g. v1.1)? Older versions of RStudio are available here: https://rstudio.com/products/rstudio/older-versions/
> 
> Hi @kevinushey , I did a short test yesterday night and the problem was less evident, but I have to do more testing (i.e. more usage with that version), but I am on a different computer right now.

Update about this after 1 week of continuous usage (also with very heavy RMarkdown files):
It seems that the problem is **not** occurring with RStudio v1.1.463.
No lags notices so far.
Thanks @kevinushey for the hint. Would like to work smoothly also in latest RStudio versions.

**Comment by kevinushey** [comment]
Thanks for the update! For now, I can only recommend:

1. Trying to update to the latest version of macOS if you are able;
2. Using software rendering with RStudio 1.2+, as described in https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors;
3. Stick with 1.1 for now until you're able to update macOS.
