### ISSUE TITLE
Compilation commands shown as warning

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#7101]
**Steps to reproduce:**
* Write some C++ code in 3 different files.
* In the second C++ file in alphabetical order, write some code that would generate a warning when compiled, such as comparing signed and unsigned integers.
* Put all 3 files into an R package project under `/src` so that it would compile them.
* Open said project in RStudio.
* Click the `Build` pane, and select `Install and restart`.
* Check the messages that appear in the `Build` pane as it compiles the source files.

**Expected behavior:** should show the compilation commands (e.g. `g++ some_file -o ...`) with white text, as it is normal output.

**Actual behavior:** after encountering a warning in the compilation of some file, all subsequent compilation commands for other files will be colored as warnings.

**Setup:** RStudio 1.3.1004, R 4.0.1, running under debian linux.

**Comment by kevinushey** [comment]
Could you by any chance share a project (e.g. something on GitHub, or code that could initialize a project in this state) just to expedite the time taken to prepare an environment to reproduce this issue?

**Comment by david-cortes** [comment]
There you go:
https://github.com/david-cortes/isotree

but you still have to add it as a new project from existing folder.

**Comment by gtritchie** [comment]
Haven't tried this, but if it turns out to be related to the ANSI escape sequence handling in the console code, please assign to me.
