### ISSUE TITLE
New File does not switch keyboard focus to source pane

### ISSUE THREAD

**Issue by UweBlock** [rstudio/rstudio#7103]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.3.959
    OS Version      : Windows 10 x64 (build 18362)
    R Version       : R version 4.0.0 (2020-04-24)

### Steps to reproduce the problem

1. Create new project (keyboard focus is in the Control pane)
2. Press Ctrl-Shift-N to create new R Script source window (keyboard focus stays in the Control pane)

This can be reproduced also in other cases where the keyboard focus is NOT in the source pane and Ctrl-Shift-N is pressed.

### Describe the problem in detail

Keyboard focus stays with Control pane.

### Describe the behavior you expected

I expect that the keyboard focus is switched to the newly created source pane. Instead, I have to switch keyboard focus manually using the mouse or by pressing Ctrl-1.

If I recall correctly (but I am not 100% sure), this behaviour is new with latest RStudio release.

**Comment by gtritchie** [comment]
Confirmed this is a regression from RStudio 1.2.5042.

**Comment by gtritchie** [comment]
Regression started in build with these two changes (presumably it's the one with the word "focus" in the title...):

Avoid stealing focus when closing tabs #6056

Be more resilient to YAML load errors in dependency scan #6057

**Comment by dfalty** [comment]
Verified fixed 1.3.1033
