### ISSUE TITLE
Terminal is always marked as busy (even if it is not busy)

### ISSUE THREAD

**Issue by torockel** [rstudio/rstudio#7112]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1019
    OS Version      : Windows 10 x64 (build 17134)
    R Version       : 4.0.0

### Steps to reproduce the problem

Open a new terminal (Tools > Terminal > New Terminal)

### Describe the problem in detail

All terminals I open in RStudio are always marked as being busy, right after clicking "New Terminal". However, the terminal is not busy and I can type and execute commands. Pressing CTRL + c does not affect the status shown in RStudio. You can see the Terminal Diagnostics from RStudio below. The first time I noticed the problem was after updating RStudio to version 1.3.1007 (if I remember correctly) to solve the issue with rtools40. Upgrading to 1.3.1019 did not solve the problem. I am using Git for Windows version 2.27.0.

The status is not a real problem. However, every time I want to switch a project or close RStudio I get a dialogue like "The terminal is currently busy. Are you sure you want to quit?", which is a little bit annoying.

```
Global Terminal Information
---------------------------
Loaded TerminalSessions: 1
Handle: '08FF4F4F' Caption: 'Terminal 1'

Terminal List Count: 1
Handle: '08FF4F4F' Caption: 'Terminal 1' Session Created: true

Current Terminal Session Information
------------------------------------
Caption:     'Terminal 1'
Title:       'MINGW64:/c/Users'
Cols x Rows  '141 x 70'
Shell:       'Git Bash'
Handle:      '08FF4F4F'
Sequence:    '1'
Restarted:   'false
Busy:        'true'
Exit Code:   'null'
Full screen: 'client=false/server=false'
Zombie:      'false'
Track Env    'false'
Local-echo:  'false'
Working Dir: 'Default'
Interactive: 'Always'
WebSockets:  'true'

Current Terminal Emulator Settings
------------------------------------
bellStyle: sound
cursorStyle: block
fontFamily: "Lucida Console", monospace
fontWeight: normal
fontWeightBold: bold
rendererType: canvas
allowTransparency: false
cancelEvents: false
convertEol: false
cursorBlink: true
disableStdin: false
drawBoldTextInBrightColors: true
macOptionClickForcesSelection: false
macOptionIsMeta: false
rightClickSelectsWord: false
screenReaderMode: false
windowsMode: true
fontSize: 13
letterSpacing: 0
lineHeight: 1
tabStopWidth: 8
scrollback: 1000

System Information
------------------
Desktop:    'true'
Remote:     'false'
Platform:   'Windows'

Connection Information
----------------------
2020/6/12 13:13:05: Connect WebSocket: 'ws://127.0.0.1:7593/terminal/08FF4F4F/'
2020/6/12 13:13:05: WebSocket connected

Local-echo Match Failures
-------------------------
<Not applicable>
```

### Describe the behavior you expected

A terminal should only be marked as busy, if it is busy. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Thanks for the report. This appears to be a regression in 1.3, investigating now to see if we can get a fix into the next bug-fix release.

**Comment by gtritchie** [comment]
Regression is a side-effect of this change: #6828

**Comment by R-Hannibal** [comment]
@torockel, thanks again for finding and reporting this issue. 

We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by torockel** [comment]
Thank you for the fast fix. After updating to version 1.3.1023 the issue is resolved.
