### ISSUE TITLE
NOTICE is missing licenses

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#7113]
The NOTICE file is missing at least the following projects & licenses:

- reveal.js includes fonts licensed under the OFL-1.1 (see [`src/cpp/session/resources/presentation/revealjs/fonts/`](https://github.com/rstudio/rstudio/tree/master/src/cpp/session/resources/presentation/revealjs/fonts))
- the google closure compiler is not listed in the NOTICE at all, but it is present in [`/src/gwt/tools/compiler/`](https://github.com/rstudio/rstudio/tree/master/src/gwt/tools/compiler) which is licensed under the Apache-2.0 license and includes dependencies under the following licenses: (NPL-1.1 AND (MPL-1.1 OR GPL-2.0-or-later)) AND MIT AND CPL-1.0 AND BSD-3-Clause AND Apache-2.0

**Comment by jmcphers** [comment]
Re: the closure compiler, NOTICE contains only software that is packaged and distributed with RStudio. The closure compiler is an internal development tool and not packaged with the IDE or distributed to end users.

**Comment by melissa-barca** [comment]
`reveal.js` is a framework we include and make note of in `NOTICE` here: 
https://github.com/rstudio/rstudio-pro/blob/109fb1ff2dfc7bf568e2d2e6bad19ab9317e5eea/NOTICE#L2921-L2942

We are using version 2.4 of reveal.js which doesn't include the fonts under OFL-1.1. Once we upgrade reveal.js, it will include the required license here: https://github.com/hakimel/reveal.js/blob/master/dist/theme/fonts/source-sans-pro/LICENSE
