### ISSUE TITLE
Where does ./src/gwt/www/fonts/icomoon.woff come from?

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#7115]
The file [`./src/gwt/www/fonts/icomoon.woff`](https://github.com/rstudio/rstudio/blob/master/src/gwt/www/fonts/icomoon.woff) was added by #3929. The pull request and the NOTICE say that it comes from fontawesome, but the name and the file's metadata on the other hand suggest it comes from [icomoon](https://icomoon.io/). As we distribute this file as part of RStudio in openSUSE, this is potentially important licensing-wise.

**Comment by kevinushey** [comment]
cc: @adamconroy; can you comment here?

**Comment by adamconroy** [comment]
Good catch, I believe I was trying different icons out at thought I ended up using FontAwesome and apparently I didn't. I will address this

**Comment by adamconroy** [comment]
The good news is I used the free GPLv3 icons. I will update the NOTICE but everything else is in the clear!

**Comment by adamconroy** [comment]
@dcermak thanks for finding that, I've added icomoon under the GPLv3 license to our NOTICE. it will appear in the next 1.3 build of RStudio. https://github.com/rstudio/rstudio/commit/c19b14e5b08454b4df9fc3910f9fd1de4735b22f

**Comment by dcermak** [comment]
@adamconroy you should remove fontawesome from the NOTICE as well (unless you are using it somewhere else too)

**Comment by dcermak** [comment]
And as per this page: https://icomoon.io/icons-icomoon.html it's actually dual licensed under GPL3+ and CC-BY 4.0

**Comment by adamconroy** [comment]
https://github.com/rstudio/rstudio/commit/2fb2a188f5740c0f2001a8d04589a09cf412dd19 Updated.

**Comment by dcermak** [comment]
Thank you @adamconroy!

**Comment by adamconroy** [comment]
Hi @dcermak sorry for the confusion but we consulted with an open source lawyer and we are licensing this only under the CC BY 4.0 license. The icomoon website is a little unclear but the Free Icon Pack that we are using allows you to choose which license to use. https://github.com/Keyamoon/IcoMoon-Free/blob/master/License.txt

I have updated the NOTICE accordingly.

**Comment by dcermak** [comment]
adamconroy <notifications@github.com> writes:

> Hi @dcermak sorry for the confusion but we consulted with an open source lawyer and we are licensing this only under the CC BY 4.0 license. The icomoon website is a little unclear but the Free Icon Pack that we are using allows you to choose which license to use. https://github.com/Keyamoon/IcoMoon-Free/blob/master/License.txt
>

No problem at all, better safe than sorry! After all, *I* should be
the one apologizing here, as I told you that it is "GPL3 AND CC-BY 4.0"
and not "GPL3 OR CC-BY 4.0".

> I have updated the NOTICE accordingly.

Thank you very much for fixing this!

**Comment by dfalty** [comment]
Hey @adamconroy, do these changes need to go into the 1.3-patch? I noticed it was merged to master and in 1.4 but didn't make it to 1.3.1033.

**Comment by adamconroy** [comment]
@dfalty made the change in the v1.3 branch. should show up in next build. good catch!

**Comment by R-Hannibal** [comment]
@dcermak , thanks again for finding and reporting this issue! I'm adding the verified label as this issue looks fixed to me in the latest preview build, but please let us know if you see something different or have any additional issues.

Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 - Desktop 

Comparison test between 1.3.1008/1.3.1054, in the latest preview references to _fontawesome_ in the Open Source Components file (Help > About RStudio > Open Source Components) have been successfully replaced with _icomoon_.
