### ISSUE TITLE
Global Options not activating from Tools menu

### ISSUE THREAD

**Issue by aniruhil** [rstudio/rstudio#7116]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.461
    OS Version      : macOS 10.14.6
    R Version       : 4.0.0

### Steps to reproduce the problem

Click `Global Options...` in the `Tools` drop-down menu in RStudio 1.4.461

### Describe the problem in detail

The Global Options window does not open when Global Options is clicked on in the Tools menu. 

### Describe the behavior you expected

I expected the Global Options pop-up window to show up as it usually does. Worked as expected until RStudio 1.2 but not since then. 

My understanding from tech Support is that Global Options should pop-up even if there are some invalid settings in the existing `rstudio-prefs.json` 

Fix: I was advised to manually find and delete `rstudio-prefs.json` and then  restart.That did the trick. 

- [ X ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ X ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@aniruhil Thank you for copying over the issue from the Community site!

**Comment by jmcphers** [comment]
If deleting `rstudio-prefs.json` fixed the problem, then the issue was a corrupt `rstudio-prefs.json` file. That shouldn't keep the dialog from opening, though.

In order to reproduce this and/or investigate this we will need to see the corrupt file. Did you happen to save a copy?

**Comment by aniruhil** [comment]
Yes, @ronblum had asked me to. Here it is 

[copy-of-rstudio-prefs.json.zip](https://github.com/rstudio/rstudio/files/4772366/copy-of-rstudio-prefs.json.zip)

**Comment by jmcphers** [comment]
Thank you so much, that enabled us to find the issue!

**Comment by dfalty** [comment]
Looks like this is fixed in 1.3.1033 and 1.4.484 with the same exact json file @aniruhil. Let us know if you run into this again!
