### ISSUE TITLE
RStudio Desktop slow to quit on Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7117]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1019
    OS Version      : Windows-10 2004
    R Version       : 4.0.0

### Steps to reproduce the problem
- Start IDE on Windows, no source files open, no terminals, no project, etc.
- <kbd>Alt+F4</kbd> to quit (or via File / Quit, etc.)

### Describe the problem in detail
- Consistently takes about 3 seconds for RStudio to actually exit

### Describe the behavior you expected
- Exiting should be relatively instantaneous

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thank you for filing this -- I've noticed this as well and it's definitely annoying.

**Comment by gtritchie** [comment]
Marking as v1.3-giant-goldenrod. I haven't investigated cause yet, but suspect this will be a major issue for some workflows.

For example, the same delay seems to be there if you are working on a package and using "Install and Restart". There's a delay during the "Restarting R" phase.

**Comment by gtritchie** [comment]
Caused by this change: #5232 (ensure file monitor stopped for all forms of quit).

I built v1.3-giant-goldenrod with `system::file_monitor::stop();` commented out in SessionMain.cpp, and the delay on closing went away on Windows.

Note that this delay doesn't always repro if you start and exit the IDE quickly. You need to leave the IDE running for some period of time (just a few seconds seems to be enough, usually), for the delay on closing to manifest.

Assigning to @kevinushey to investigate further.

**Comment by gtritchie** [comment]
Closing, fix was merged into 1.3-goldenrod several days ago.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1065, R Version - 4.0.2, Windows 10 x64 - Desktop 

The close time (whether through manually closing window, Alt + F4, File > Quit Session, Session > Quit Session) for the IDE on Windows is now less than a second.
