### ISSUE TITLE
R Studio error file

### ISSUE THREAD

**Issue by antoniobrnjic** [rstudio/rstudio#7120]
So I'm currently taking a data scientist course on course era. This week, I was trying to integrate rstudio with git and github. I made my first repository and I'm trying to make a r script and commit it to the repository and see that there was an upload in github. I first made sure that everything was up to date and my r was no up to date, so I first updated that. Then, I made sure that my git was up to date and it was. For a long time, I didn't set up the path correctly for git (and i'm still confused as to why I have a ton of git.exe files on my mac). But, I did $which git in the terminal and I changed it back to the correct one. So, I still don't know what the problem is. This is the main problem..

Whenever I want to type an RScript, I'll start typing and I get an error message that a file can't be found (when I didn't even save yet). I'll even get the same error if I save it first and create the file and then start typing. Also, when I try to use the README.md file it'll sometimes say that the file doesn't exist or it can't load it. It'll work sometimes if I type something fast and then save and commit but I'm pretty that is NOT supposed to happen. So, I'm begging for help. I've been trying and looking for hours.

<img width="1280" alt="Screen Shot 2020-06-12 at 6 10 19 PM" src="https://user-images.githubusercontent.com/66037216/84553298-704a0000-acd9-11ea-9d80-1c5d33f2e2cf.png">
<img width="1280" alt="Screen Shot 2020-06-12 at 6 12 37 PM" src="https://user-images.githubusercontent.com/66037216/84553300-704a0000-acd9-11ea-991a-7c7e84a4bdb8.png">
<img width="1280" alt="Screen Shot 2020-06-12 at 6 12 46 PM" src="https://user-images.githubusercontent.com/66037216/84553301-70e29680-acd9-11ea-89c2-c10323488edf.png">
<img width="1280" alt="Screen Shot 2020-05-27 at 6 43 51 PM" src="https://user-images.githubusercontent.com/66037216/84553317-82c43980-acd9-11ea-8e5f-8fe4f9ba7280.png">

**Comment by ronblum** [comment]
@antoniobrnjic Thank you for raising the issue. Can you please provide the following information so that we can try to reproduce it, including which version of MacOS?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

In addition, does this only occur if you're within a project with version control, or also outside of project or a project without version control?

**Comment by antoniobrnjic** [comment]
RStudio Version: RStudio Desktop 1.3.959
OS Version: mOS Catalina 10.15.5
R Version: 4.0.1 (2020-06-06)

**Comment by antoniobrnjic** [comment]
The macbook is a MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by antoniobrnjic** [comment]
@ronblum Did you get a notification for my comment?
