### ISSUE TITLE
Expand HOSTNAME in XDG paths

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7122]
We currently expand the `USER` and `HOME` variables in XDG paths.

https://github.com/rstudio/rstudio/blob/078b70fad260768b795d807044ea90ac6e7188f9/src/cpp/core/system/Xdg.cpp#L87-L94

This makes it possible to e.g. store user state in `/mnt/megafs/rstudio-$USER`. 

Some customers who are looking to relocate `.rstudio` want to do so in order to share home directories between hosts that have different installations of RStudio that aren't supposed to share state, so they'd want to use something like `~/.rstudio-$HOSTNAME`. This is not currently possible since we don't expand the hostname, but would be an easy add and probably helpful for people trying to partition state by host (though of course it would make things like load balancing not work).

See internal support ticket: 48950

**Comment by jmcphers** [comment]
Good news, I did this one already! https://github.com/rstudio/rstudio/blob/468f2b1855a613a60eebdf7fc2ad459753967de1/src/cpp/core/system/Xdg.cpp#L158-L166

**Comment by mikebessuille** [comment]
I guess we should test this in 1.4-Juliet-Rose
