### ISSUE TITLE
RStudio console is unable to invoke system2() on interactive mode external program, but is able to invoke it via it's Terminal tab using R in interactive mode

### ISSUE THREAD

**Issue by carlosparadis** [rstudio/rstudio#7124]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : mac OS Catalina 10.15.1 
    R Version       : R version 3.6.1 (2019-07-05) -- "Action of the Toes"

### Steps to reproduce the problem

1. Download a trial version of: https://archdia.com/pages/dv8-standard-free-trial
2. Use system2("<path_you_install>/DV8/bin/dv8-console") from RStudio console tab

Alternatively, use any other program that launches an interactive session for it's CLI (I am not familiar with others). 

### Describe the problem in detail

I am currently using a proprietary program (DV8 above) that runs its CLI using interactive mode. The reason why I believe the issue lies within RStudio console is that:

 * Running the proprietary program via OS X terminal works. 
 * Running R in interactive mode from the OS X terminal, and then using system2() to invoke the program also works.
 * Running R in interactive mode from the Terminal tab **within R Studio** and using system2() call to invoke the application will also work! 
 * Using the console tab from R Studio, which I need in order to manage the R package which contains the system2 call to the proprietary program **does not** work. 

Reaching the company, I was told the root cause of the problem is that they chose to use interactive mode, while most other tools I had no issue with do not. They also said that:

> Most built-in process call functions actually disable this feature by default, but there should be some configs to enable it to make dv8-console go through.

However, since this problem only happens for the R Studio console, I am not sure how to go about it. 

### Describe the behavior you expected

I expect the R Studio console tab to behave the same way as it's terminal tab after launching R interactively, by running the proprietary tool which uses interactive mode.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Because the RStudio R console isn't a "real" console, attempts to run interactive programs through `system()` / `system2()` won't function as expected.

If you require this, I'd recommend running the application through a separate terminal in the Terminal pane (as you've already discovered).

**Comment by carlosparadis** [comment]
@kevinushey thank you for the follow-up. Just to be clear, there is no "settings" that would allow working this around RStudio console, correct? 

Also, because the data from this proprietary tool is used in a portion of my R package along with other functions, I have been using `/exec` to write batch scripts for my R package and running on the terminal. Is this the appropriate way to go when the package gets released for other people to use given the limitations? I had a hard time finding packages that offer batch scripts to learn by example or even finding discussion around online. 

It still requires running the batch script to write the data instead of just running a vignette due to the limitations, but it is the best I can think of.

**Comment by kevinushey** [comment]
Right, there unfortunately isn't any workaround available here for the "main" RStudio console.

> Is this the appropriate way to go when the package gets released for other people to use given the limitations?

I don't know how the tool is intended to be used, but at least in theory your R package could use this external tool non-interactively, and you could push all the interactivity into R (requesting user input via `readline()`). This does unfortunately duplicate effort, though.

**Comment by carlosparadis** [comment]
Thank you Kevin. I will go ahead and close the issue since there is nothing that can be done with the R console itself via RStudio, which is what I wanted to verify.

**Comment by carlosparadis** [comment]
Hi, 

I found a solution (more like a hack but I will take it). `rstudioapi` did the trick. Posting here if someone else finds their way here. It was clear that this could be done manually, but not automatically since I didn't know of `rstudioapi`! 

As I noted on the original post: 

> Running R in interactive mode from the Terminal tab within R Studio and using system2() call to invoke the application will also work!

From that standpoint, it dawned on me if I had a way to 

   1. convince the vignette to run a batch script under `/exec` to do everything and 
   2. save as a file in `/tmp/` and
   3. block the R Console of R Studio (which is the one which won't let me run the interactive terminal of the proprietary tool) until said file is saved, and then 
   4. load the /tmp/ saved file in R

then I can effectively automate as part of the vignette or even an R function the inconvenience to go to the terminal just to run it. Which is essential, as I intend to run said tool against a lot of data. 

In fact, the necessary workflow is the very example functions on [rstudioapi page for terminals](https://rstudio.github.io/rstudioapi/articles/terminal.html):

```
# Start a command with results displayed in a terminal buffer
termId <- rstudioapi::terminalExecute("ping rstudio.com")

# If viewing the result in the terminal buffer is sufficient,
# then no need to do anything else. The command will continue
# running and displaying its results without blocking the R session.

# To obtain the results programmatically, wait for it to finish.
while (is.null(rstudioapi::terminalExitCode(termId))) {
  Sys.sleep(0.1)
}
```

In the event the /exec script is executed server-side, then the end-user can run the /exec script directly, without the vignette.
