### ISSUE TITLE
RStudio v1.3.959 on macOS 10.15.4 Paste shortcut still fails in Save Dialogue

### ISSUE THREAD

**Issue by anwhite003** [rstudio/rstudio#7125]
Over the past several versions of RStudio on macOS Catalina/Mojave & before
when trying to save an R code file from Source Panel using Cmd-s to save which opens a Dialogue Window, when trying to use Cmd-v to paste the Source file string that I copied to clipboard with Cmd-c: it ALWAYS FAILS. 
(And it only fails on macOS not on Windows systems.)

However using the long way around with mouse clicks to select the top menubar's Edit menu and selecting "Paste" works to paste the string to the File Name slot of the Dialogue Window. 
But cmd-v never works.  

Other RStudio on Mac users in the past several years have noticed this code error.
Why is this so hard to fix?
Please correct this soon.

Thank you and Aloha, Andy White

**Comment by kevinushey** [comment]
Thanks for the bug report! This appears to be a Qt bug -- I've filed this at https://bugreports.qt.io/browse/QTBUG-85050.

**Comment by anwhite003** [comment]
Meaning: you will continue to ignore the issue
Gee thanks.
AW

With Aloha, Andy

**Comment by gtritchie** [comment]
This will be fixed by the move from Qt to Electron.

**Comment by kevinushey** [comment]
Unfortunately, there appear to be a couple of issues here with Electron still.

- [x] Cmd + V for paste
- [ ] Cmd + Z for undo
- [ ] Cmd + Shift + Z for redo
- [ ] Cmd + A for select all

I think these are worth fixing.

**Comment by anwhite003** [comment]
Good grief!
I had forgotten this and given up on any fix of Qt but i gotta say 1 fix out of 4 is a 25% win!
So mahal nui loa to all of you who managed to get Ctrl v working to enable pasting a string from the Clipboard to the filename field-slot when i try to save a file or script.

but 1 question:
in what RStudio version can I expect to see this fix implemented? 

With Aloha, Andy White

**Comment by anwhite003** [comment]
Mahalo Kevin !

With Aloha, Andy White

**Comment by anwhite003** [comment]
I have tested in latest RStudio Preview Electron (2022.07.0 B536 Electron) for macOS 12 Monterey and finally-finally-finally after several years of trying to paste text that has been copied to Clipboard into the File Save As dialogue window and always failing (and often freezing the RStudio app)  - it finally actually works !
Thank you. - anwhite003 (1 July 2022)

**Comment by ronblum** [comment]
@anwhite003 Thank you for the update! I'm glad to here that at long last, this works.
