### ISSUE TITLE
Recent Projects list broken in recent release

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#7126]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.3.1014
    OS Version      :  Linux 19.10 (saw the same thing in 20.04 I believe)
    R Version       :  3.6.3

### Steps to reproduce the problem
Open project A, do stuff, project list has project A in it.
Open project B, do stuff inc git commit push. Project list is blank.

Pretty sure this bug was introduced in the build before this one, *maybe* the build before that.
I don't think the git commit push element is necessarily related since I don't use this much. But I just did it and the project list is empty again so it might be. But I think the list just empties generally.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by SimonDedman** [comment]
Edit: Step 3: manually open project A since recent projects list was blank. Recent projects list now shows project A and project B, i.e. project B wasn't in the list after project B was manually opened, but B IS in the list after A is manually opened.

**Comment by ronblum** [comment]
@SimonDedman Thank you for raising the issue. Was the issue showing up in the latest release (as opposed to dailies), 1.3.959?

**Comment by SimonDedman** [comment]
Hi Ron,

I honestly couldn't say - I've been using only the dailies for a while now. That said, I presume 959 was a daily at some point? Certainly this is a relatively new introduction. Do let me know if there's more I can do to help diagnose.

Simon

**Comment by gtritchie** [comment]
I just repro'd using Mac Desktop v1.3.1019 with R 4.0.0. Sure enough after I did a git commit and push (step 2) the project list became blank. Then I did step 3 (manually selected the original project) and the list was once again populated correctly.

**Comment by R-Hannibal** [comment]
@SimonDedman, thanks again for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by SimonDedman** [comment]
Cheers Mario. I might struggle to get a chance to check this out in the next week or so but will do so asap. I presume this hasn't been pushed to today's/yesterday's Preview version?

**Comment by R-Hannibal** [comment]
Hey @SimonDedman, you are correct, the fix has not gone out to preview versions yet and is only in daily builds of the upcoming 1.4 release at the moment. 

We're actually getting fairly close to sending 1.4 to preview and the team is very excited for more folks to get their hands on some of the new stuff we've been working on, but we're not quite there yet 😊.

**Comment by SimonDedman** [comment]
That's great news mate, congrats. I'll try to play around with this issues in the dailies so it's checked before 1.4's pushed. Cheers!

**Comment by kfeinauer** [comment]
Verified fixed on RStudio 1.4.944
