### ISSUE TITLE
Debugger is funky

### ISSUE THREAD

**Issue by jmorim** [rstudio/rstudio#7127]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.989
    OS Version      :  Windows 10
    R Version       :  4.0.0

### Steps to reproduce the problem
Open a package as an R project. Open a file with functions you need. Try to set a breakpoint in a function.

### Describe the problem in detail
Breakpoint doesn't show up

### Describe the behavior you expected
A nice red circle where I want the debugger to trigger

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Can't set breakpoints in functions. Reopening RStudio puts in breakpoints that previously didn't show up. Version 1.3.959

Also occasionally in the browser (when debugging does trigger) outputs aren't printed in the console.

Also the code being executed and the code highlighted don't match.

**Comment by ronblum** [comment]
@jmorim Thank you for raising the issue. Can you provide an example so that we can try to reproduce it?

**Comment by jmorim** [comment]
Behavior to reproduce:

Open a package project

Open an R file with nested functions

Attempt to set a breakpoint within a nested function

Witness as breakpoints don't appear

Close RStudio

Reopen the R file with nested functions

Look at breakpoints appear when you don't want them now

Lament at your inability to remove breakpoints without reopening RStudio

**Comment by jmorim** [comment]
I'm a dummy and didn't realize breakpoints don't work in anonymous functions
https://support.rstudio.com/hc/en-us/articles/200534337-Breakpoint-Troubleshooting
