### ISSUE TITLE
More options of font size or zoom

### ISSUE THREAD

**Issue by MykolaPinchuk** [rstudio/rstudio#7128]
Is it possible to add more options of editor font size or zoom level? I have troubles setting the desired size of code and interface at both my laptop and desktop. The code is either too large or too small. To be more specific, under default layout, I prefer to have the editor window, accommodating 18 or 19 lines of code, but using all possible combinations of zoom/editor font size (without making them absurdly different), I can get either 17 or 20. In other words, is it possible to make font size or zoom grid finer?

**Comment by gtritchie** [comment]
Let's track this via: #6732

**Comment by karlmakepeace** [comment]
Is this possible yet?
