### ISSUE TITLE
Project specific language for spellcheck

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#7130]
I have several projects, some of them are mainly in one language and others are in another language. The new addition of automatic/real-time spellcheck (thanks for the addition!) uses a global option that is shared between projects.

I would like to be able to set a language for spellcheck on each project instead of a global Rstudio option. That way I could work with several different projects and spellcheck them without changing the global option. 

One solution is to have the global option and then a project option. 
This might also help for #6331 if uses the global language as primary language and the project option as secondary one.

PS: Not that I might change frequently the languages of the projects but each time I select a different language from the default list it takes a while to download the list of dictionaries available. Even if I do this on the same Rstudio session. 

```
OS: Ubuntu 20.0
Rstudio: Version 1.3.959
```

**Comment by ronblum** [comment]
@llrs Thank you for the suggestion. We'll review it as we continue development of RStudio.

**Comment by jjallaire** [comment]
Closed via https://github.com/rstudio/rstudio/commit/12640b4cea23d18292f8852a7067baa98814a835

**Comment by llrs** [comment]
Thanks @jjallaire!
