### ISSUE TITLE
Repeat issue https://github.com/rstudio/rstudio/issues/4034

### ISSUE THREAD

**Issue by shortyatz** [rstudio/rstudio#7132]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.2.5019
    OS Version      : Mac Catalina 10.15.5
    R Version       : 3.6.1

### Steps to reproduce the problem

HydroPSO optimization in within an RMarkdown, parallelization was used. Happened twice within an hour.

### Describe the problem in detail
Repeat of https://github.com/rstudio/rstudio/issues/4034. Will update with full error read out if it happens again.

### Describe the behavior you expected
RMarkdown to knit as usual, I knit the same document almost daily.

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x]
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4778696/diagnostics-report.txt)
 If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4778681/diagnostics-report.txt)

- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@shortyatz Thank you for filing this. Does this issue occur in the [current RStudio 1.3 release](https://rstudio.com/products/rstudio/download/)?

**Comment by jmcphers** [comment]
Haven't heard back in a week, plus we already have #4034 open so we should use that to track the issue (additional reports/info should be left as comments on that issue rather than new issues)
