### ISSUE TITLE
"Enable Automated Crash Reporting" prompt repeats when restarting R session. 

### ISSUE THREAD

**Issue by grantbrown** [rstudio/rstudio#7134]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      :  Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem

1. Open Rstudio, and make sure it is configured to not send automatic crash reports (global options)
2. Select Session > Restart R, and observe the crash report dialogue box
3. Repeat step 2 to demonstrate the recurring nature of the issue

### Describe the problem in detail

Upon restarting the R session, a dialogue box appears prompting the user to upload crash reports automatically, every time, and without the option to "not show this again", or similar. I understand the design decision to bug users on startup of Rstudio, but showing this dialogue upon a simple restart of the R session is disruptive. Some debugging workflows, especially (but not exclusively) involving packages require the user to restart the R session multiple times.

One solution would be to implement a "do not ask me again" type checkbox for this dialogue. Alternatively, the dialogue could be tied to the launch of Rstudio itself, rather than the R session. 

### Describe the behavior you expected

I would expect this dialogue to show up only on the launch of the Rstudio session itself. I would also prefer that it be made optional. 

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Whenever you respond to the prompt, a file should be created at `%LocalAppData%\R\crash-handler-permission`. If that file does not exist, you can simply create it manually (and leave it empty) to get the prompts to stop showing.

**Comment by grantbrown** [comment]
@kfeinauer Thanks, that fixed it.

**Comment by kevinushey** [comment]
If more users report this issue, it may be worth considering whether we could store this preference in the Windows registry as well.

**Comment by slowkow** [comment]
I face the same problem.

### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.1093
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

Each time I build my package in RStudio, I get the prompt again:

![Screen Shot 2020-12-14 at 3 59 10 PM](https://user-images.githubusercontent.com/209714/102153892-343d5680-3e46-11eb-985c-cf92744ec45f.png)

It would be nice to have the ability to disable this feature.

I went to preferences and checked the box:

![Screen Shot 2020-12-14 at 4 00 05 PM](https://user-images.githubusercontent.com/209714/102153918-43240900-3e46-11eb-84b6-ecaf963b1c5f.png)

I clicked "Apply", and still I get the same popup each time.

**Comment by kfeinauer** [comment]
@slowkow It's likely that for some reason, you don't have permission to write `%LocalAppData%\R\crash-handler-permission`. Can you send your `rsession-<username>`.log` file? You can find it by going to `Help -> Diagnostics -> Show Log Files` from within RStudio.

To get around the repeated prompts, you can simply create an empty file at the path noted above.

**Comment by slowkow** [comment]
@kfeinauer Thanks for the reply!

I'm on macOS, and I don't know where to find the `crash-handler-permission` file.

I also don't know where to get the log file... here's what I see:

<img src="https://user-images.githubusercontent.com/209714/102274741-5b516200-3ef2-11eb-9b64-4cd7690c91ce.png" width="50%"/>

**Comment by kfeinauer** [comment]
@slowkow My apologies - I should have noticed you were on macOS.

The log files will be available under `~/.rstudio-desktop/log`. The `crash-handler-permission` file can simply be written to `~/.r/crash-handler-permission` by simply running `touch ~/.r/crash-handler-permission` in a terminal as your current user.

**Comment by slowkow** [comment]
Thank you!
