### ISSUE TITLE
OpenSSL version mismatch leads to rsession errors or crashes

### ISSUE THREAD

**Issue by mcg1969** [rstudio/rstudio#7137]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.959
    OS Version      : CentOS 8
    R Version       : 3.5.0 (Anaconda-based)

### Steps to reproduce the problem

1. Create a conda environment using, say, `conda create -n testr r-base=3.5 r-jsonlite`
2. Launch RStudio
3. From the console, run:
```
jsonlite::fromJSON('https://repo.anaconda.com/pkgs/msys2/noarch/repodata.json')
```
You should see some SSL cipher errors.

### Describe the problem in detail

The problem is that RStudio's `rsession` is linked to OpenSSL 1.1. But if it pulls in a `libR.so` library that was linked to OpenSSL 1.0, errors like this occur. A similar but more serious issue occurs if you combine a CentOS 6/7 version of RStudio with an OpenSSL 1.1 linked version of R—I'm seeing explicit crashing.

The problem isn't RStudio at all, it's entirely `rsession`. In fact, I've developed a workaround: I installed _both_ versions of rsession on the same machine, one linked to OpenSSL 1.1 and one linked to OpenSSL 1.0. Then I wrapped them in an `rsession.sh` script that selects the correct choice depending on the version of R being used.

I'm wondering if there isn't a way for `rsession` to be designed such that it leverages whatever OpenSSL library `libR.so` itself seeks to pull in; but that's above my pay grade.

### Describe the behavior you expected

RStudio should be able to work with older and newer versions of R, whether running on CentOS 6/7 or CentOS 8.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mcg1969 Thank you for raising the issue! I'll mark it for triage as part of our ongoing development of RStudio.

**Comment by mcg1969** [comment]
Thank you, @ronblum! To be clear I have the workaround I need for the foreseeable future. RStudio is a great IDE and I'm glad we can help enable R users to take advantage of it.

**Comment by ronblum** [comment]
@mcg1969 I appreciate the sentiment! We take user feedback seriously, so it's nice to hear when y'all let us know you like the product, too. 😄 

Also, I'm glad you've been able to come up with the workaround! And it's helpful to know, in case other users run into the same issue.

**Comment by mikebessuille** [comment]
In our current architecture, we need to match the OpenSSL between RStudio, R, and the system.  This would be a lot of work.  Wondering how big of an impact this issue is causing for our users.

**Comment by mcg1969** [comment]
@mikebessuille when you say "current architecture" do you mean 1.4? Because in 1.3 my workaround is effective.

**Comment by mikebessuille** [comment]
Okay, glad to hear you have a workaround in 1.3.  I assume that will also work for 1.4.   We'd like to improve this eventually as it would fix other problems as well (for example, we could ship only a single install for all versions of Centos rather than different installs for different distro versions).  But it would be a lot of work.  Given the available workaround, I'm inclined to close this for now, and revisit it if it becomes a more intrusive problem.

**Comment by mcg1969** [comment]
I defer to you on that, certainly. Thank you for your input!

**Comment by mcg1969** [comment]
But to be clear—my workaround involves using a different `rsession` binary for each supported version of openssl. It does _not_ seem necessary to align RStudio and R, just `rsession` and R.
