### ISSUE TITLE
Template choices are not visible and do not align with New R Markdown From Template

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#7138]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3
    OS Version      :  Windows 10
    R Version       : 4.0.1

### Steps to reproduce the problem

1. Click the File menu
2. Click "New File"
3. Choose "R Markdown" from the choices
4. Go to "From Template" in the left box (you probably have to have multiple packages with templates installed)
    1. The packages that I have which provide templates from CRAN are "PKPDmisc", "mrgsolve", "rmarkdown, and "tufte", and I have a personal package called "bsd.report" from github at "billdenney/bsd.report".
5. Try to choose the correct template from the box on the right.

### Describe the problem in detail

When creating a new R Markdown document from a template in Windows 10, the choices are not visible and when they are, they do not align correctly.

When the window first opens, I see no options visible: 
![image](https://user-images.githubusercontent.com/10359931/84714962-32e5ac80-af3d-11ea-8788-2ac955e43755.png)

When I click on the box to the right even though it is invisible, the options appear, but the highlighted item tends to be one below the actual selected item.  (Meaning, when I click "OK" to create the template, it will be the item above the one that looks like it is highlighted in all cases that I recalled).

For example, after I clicked "OK" on the window that looked like this, I got the "basic report (HTML)" from PKPDmisc instead of the one that was highlighted.
![image](https://user-images.githubusercontent.com/10359931/84715557-cec3e800-af3e-11ea-81cd-7565917fe915.png)

Additional possibly important system details are:
* I have two monitors (the behavior of not seeing the template correctly is the same on both monitors)
* The two monitors have the same resolution of 3840x2160 with different scaling (the first is my laptop monitor, and it has 200% scaling; the second is an external monitor, and it has 150% scaling.
* I make use of both displays with the "Extend these displays" option in Windows (rather than duplicating the displays).

### Describe the behavior you expected

I should be able to see and select the template that I mean to select.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@billdenney Thank you for raising the issue! I can't reproduce the issue, but there's an excellent chance that I can't reproduce it because I don't have access to a similar enough environment. Would you mind trying out one or more of the following things? This would help pinpoint the source of the problem.

1) Changing the rendering engine. I would start with this, because if it works—all set! https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
2) Just using the laptop.
3) Changing scaling to 100% (FWIW, I normally use 175% myself)

Anything you can do will help. Thanks!

**Comment by jmcphers** [comment]
The fact that this involves (a) a region of the dialog not painting, and (b) happens *only* with software rendering suggests to me that it's the same underlying issue as https://github.com/rstudio/rstudio/issues/6268.

**Comment by billdenney** [comment]
@jmcphers , Thanks for the pointer to that.  Should I try one of the nightly builds?  (Are these usually in a good state that I won't break lots of other things if I do so?  That may be an impossible question to answer.)

As I've been using OpenGL for the last hour or so, I've been reminded of another issue (that I can't make a reproducible example for, so I don't think I have previously reported it) which causes screen flickering, especially when maximized.  Software works better for me, in general.

**Comment by billdenney** [comment]
FYI, this appears to have been resolved with version 1.4.1717.
