### ISSUE TITLE
Modifying keyboard shortcuts with Ctrl modifier fails on Windows

### ISSUE THREAD

**Issue by imanuelcostigan** [rstudio/rstudio#7142]
### System details

    RStudio Edition Desktop
    RStudio Version : 1.3.1004
    OS Version      :  Windows 10 x64 (build 17763)
    R Version       :  4.0.1 (but also there with 3.6.x)

### Steps to reproduce the problem

1. Open Modify Keyboard Shortcut option
2. Select any options (eg below is Quick Add)
3. Type any keyboard modifier combo that includes Ctrl 
4. The resulting printed shortcut in the option includes an empty box for the non-Ctrl key (should have been Ctrl-D in screenshot below)
5. Typing this shortcut does not work in the editor after clicking OK.

![image](https://user-images.githubusercontent.com/2107580/84722409-7c2e0e80-afc6-11ea-9304-d78b916f67d5.png)

### Describe the problem in detail

This seems to have been introduced at some point in the 1.3 release process as I was able to previously edit this successfully. One possible thing that might be unique about my set up is that I have remapped my caps lock to be a control key using a RegEdit patch. Using either of the physical Control keys on my machine results in the same issue above.

### Describe the behavior you expected

The keyboard shortcut prints properly and can be used in the editor.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is fixed in the current dailies but not in the v1.3 release -- looks like that fix needs to be backported.

**Comment by kevinushey** [comment]
Backported via https://github.com/rstudio/rstudio/commit/7d208677a46b945b17746d25c4914f60633e665f -- this fix will become part of a later v1.3 patch release. Thanks for the report!

**Comment by jmcphers** [comment]
This is fixed in the daily builds and will soon be fixed in 1.3 (preview ETA tomorrow).

**Comment by imanuelcostigan** [comment]
thank you all

**Comment by R-Hannibal** [comment]
Verified Fixed on: Windows Desktop, RStudio: Version 1.3.1030

@imanuelcostigan, thanks again for finding and reporting this issue, as well as the clear/concise issue report.
