### ISSUE TITLE
Not expected warning by RStudio

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#7143]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      :  Debian GNU/Linux 9.12 (stretch)
    R Version       : 3.6.3

### Steps to reproduce the problem
In an R file, with `tidyverse` and `magrittr` both loaded (I'm not sure if just with `dplyr` this would occur) introduce the next code:
```
matrix(c(1,2)) %>%
  `[`(,1)
```
It works as expected, but it produces a warning by RStudio:
`missing argument to function call`
![rstudio_fact](https://user-images.githubusercontent.com/40892925/84776518-aee50080-afe0-11ea-8050-568f0ff9a854.png)

Thank you!

*Update*: The same happens when using `extract` instead of `` `[` ``

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@iago-pssjd Thank you for filing the issue! I can reproduce it in RStudio Desktop 1.3.959 on MacOS 10.15 with R 4.0.0. The issue only warning message only occurs if the first argument is missing; if it's present and the second one is missing—e.g. ``` `[`(1,) ```—there's no warning.

Note: this is not a regression, as it occurs in RStudio Desktop 1.2.5040, as well.

**Comment by iago-pssjd** [comment]
As it is a bug rising a false warning, I believe this issue should not be closed.

**Comment by mikebessuille** [comment]
This won't affect many customers; closing this issue.
