### ISSUE TITLE
Keyboard shortcuts not loading on launch

### ISSUE THREAD

**Issue by luannnguyen** [rstudio/rstudio#7144]
In RStudio 1.3.959 on Mac OSX Mojave, custom keyboard shortcuts are not loading on launch. The default shortcuts are loaded instead.

For now, this can be worked around by opening Tools > Modify Keyboard Shortcuts and then closing the window again (has to be done every time RStudio is launched), but would be nice for this to be fixed

**Comment by ronblum** [comment]
@luannnguyen Thank you for raising the issue! Can you confirm that the file `~/.config/rstudio/keybindings/rstudio_bindings.json` is getting created and is readable? And if so, can you attach a copy of it?

**Comment by luannnguyen** [comment]
Yes that json file is readable and writable (has 755 permissions).
Below is the json file:
`cat /Users/lnguyen/.config/rstudio/keybindings/rstudio_bindings.json`
```
{
    "commentUncomment": "Cmd+/"
}
```

**Comment by ronblum** [comment]
@luannnguyen Thanks! I can't reproduce the problem, even when using the file contents above. I was wondering if the JSON was malformed for some reason, but that's not the case. One more question: is this just an issue with that particular shortcut or with other shortcuts if you modify them?

Regarding reverting back: that makes sense, since the user settings are stored differently in 1.2 and 1.3. Several sets of user settings were consolidated under the `~/.config/rstudio` directory, such as dictionaries and user preferencees.

**Comment by luannnguyen** [comment]
I did some further testing and the issue only occurred when an R project was open, and did not matter whether Rstudio was already open or not. So it seems like an R project related issue.

I also tried adding more shortcuts. Below is the new json:
```
{
    "commentUncomment": "Cmd+/",
    "newRNotebook": "Shift+Cmd+N",
    "newProject": "Shift+Cmd+P"
}
```

This led to very strange behavior:
- Upon opening a project, only "newRNotebook" works
- After executing "newRNotebook", the other shortcuts work

**Comment by DanyOTRON452** [comment]
Hello, I use Rstudio 1.3.959 on Ubuntu 18.04, Alt+/- doesn't work when I use it, It gives + or -. I need help

**Comment by wgrundlingh** [comment]
I can replicate this issue in the preview release (RStudio 1.4.953). It's still fixed when choosing Tools > Modify Keyboard Shortcuts and then closing it again.

**Comment by kevinushey** [comment]
I was able to reproduce this once, but not again since then. :-/ At least in my case, most actions within the IDE appear to cause the shortcuts to be properly refreshed and loaded -- e.g. creating a new R source document, or something else.

**Comment by wgrundlingh** [comment]
@kevinushey: Admittedly, when I load RStudio the first time, it struggles to connect to R, showing this:

![image](https://user-images.githubusercontent.com/1776164/97363781-506a4180-1860-11eb-8f4e-77cd4c535985.png)

I am running RStudio locally, on my work computer, using VPN, with some virus software running, so I don't pay much attention to the issue. I just click Retry and then things work, except for the keyboard shortcuts. Perhaps that's related?
