### ISSUE TITLE
New or opened files not appearing in source editor

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7145]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.475
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- close all source documents so the Console fills the entire column
- File / New File / R Script OR open an existing file (File / Open File...)

### Describe the problem in detail
- first problem: nothing seems to happen
- if you un-maximize the console, however, the source file then appears
- second problem: if you opened an existing file, when you expand the source pane there are two files, the one you opened and an "Untititle1" file

### Describe the behavior you expected
- creating a new source file should expand the source panel
- opening an existing file should expand the source panel but not also create an untitled file
- presumably a regression caused by work to support new source columns

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Closed in #7151
