### ISSUE TITLE
If defined, use str() method in environment pane

### ISSUE THREAD

**Issue by nealrichardson** [rstudio/rstudio#7147]
Hi! I was demoing something in the `arrow` package for @jjallaire a while ago, and he noticed that the environment pane showed `<Object containing active binding>` for all of my Arrow objects. He suggested that we should [define a `str()` method](https://jira.apache.org/jira/browse/ARROW-8718) for them to make prettier things show up. 

As it turns out, that doesn't work. It seems to be intentional: the feature of not calling `str()` on environments with active bindings was added in https://github.com/rstudio/rstudio/pull/796. 

It makes sense that you'd want to avoid accidentally triggering those bindings to display something in the environment pane, but it would be nice if there were a way for package developers to control that behavior. One idea would be that if there is a `str` method defined for the class, you always use that, regardless of whether the object has active bindings--we just want to avoid calling `utils:::str.default()`, right?

**Comment by jmcphers** [comment]
> One idea would be that if there is a str method defined for the class, you always use that, regardless of whether the object has active bindings

The goal is not to invoke the active binding as a side effect. The fact that there is a `str` method defined doesn't tell us whether invoking it will fire the binding, and in fact I'd suspect it will in most cases.

**Comment by nealrichardson** [comment]
Right, I understand the goal of not causing side effects. With R6 classes in particular, invoking an active binding isn't necessarily costly or something to be avoided, and it may not have side effects. In any case, the argument would be that if I've defined (for example) `str.ArrowObject`, then I've determined that it is safe to call it for summary/structure information.

**Comment by jmcphers** [comment]
Got it. I think this still may be intractable because we will need to introspect the object's class in order to determine whether it has a `str` method -- and introspecting the class means retrieving the value from the environment, which in turn will fire the active binding. So there's no way to tell if there's a safe `str` method until it's too late.

Maybe I'm missing something here re: a distinction between an object that _is_ an active binding and an object that _has_ an active binding?

**Comment by nealrichardson** [comment]
My reading of #796 (and my particular issue) is about environments that have active bindings; they are not themselves active bindings. And FWIW there are separate functions `hasActiveBinding` and `isActiveBinding`: https://github.com/rstudio/rstudio/pull/796/files#diff-80841db686c039427b41c90c3d4555b9R368-R375

**Comment by dfalbel** [comment]
This also happens for objects with `typeof(object)` = `"environment"`.
For example in torch we have:

```
> library(torch)
> x <- torch_randn(10, 10)
> str(x)
Float [1:10, 1:10]
```

But the env pane shows: 

![image](https://user-images.githubusercontent.com/4706822/91902767-95b32e00-ec78-11ea-8f9a-a38161c63944.png)

In this case the `x` object is an environment, but it doesn't contain any active bindings..

**Comment by thomasp85** [comment]
Just to add, I'm building a range of new primitive types in https://github.com/thomasp85/euclid with the structure of the types on the R side being a list containing a single external pointer. These show up as `List of <n>` with `<n>` being the length of the object (not the list). They have `str` methods defined but they are not getting called

**Comment by kevinushey** [comment]
One thing to be very careful of is that calls to `str()` could segfault if those are null pointers and your method doesn't check for that (we had that problem in the past with some packages and their own `str()` methods, IIRC)

**Comment by thomasp85** [comment]
I can see from your point of view that that is important (I do check, though:-)

**Comment by thomasp85** [comment]
but the same is true for `length()` which you do call, so I don't really see the distinction

**Comment by kevinushey** [comment]
True, but in practice we've seen that `str()` methods in the wild are less well-behaved than `length()` methods.
