### ISSUE TITLE
Function hint overlaps the function help popup

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#7154]
RStudio Edition : Desktop or Server
RStudio Version : 1.3.1023
OS Version      : Mac OS Catalina
R Version       :  4.0

### Steps to reproduce the problem
Mouse over any function preferably a function that has arguments so that you get the popup hint on the arguments.
The function name + the argument popup overlap each other and key argument details are hidden.

Screenshot enclosed.

### Describe the behavior you expected
Not sure why the function name is a popup hint and if that could be avoided.
Else, some intelligent gap between the function name and the argument hint popup.

![RStudio 2020-06-18 08-41-02](https://user-images.githubusercontent.com/37381682/84974245-84aa5480-b140-11ea-9169-beb3540df651.png)

**Comment by kevinushey** [comment]
Looks like there are a bunch of spurious calls to `stan_get_arguments` when this occurs. I'll take a look.

**Comment by vinaychuri** [comment]
@kevinushey . Thank you for the update.

**Comment by R-Hannibal** [comment]
@vinaychuri, thanks so much for finding and reporting this issue. 

We have a fix in place in our latest preview build 1.3.1054 (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by vinaychuri** [comment]
Yes, this is fixed with preview build 1.3.1054. We now see the function name along with all its arguments. 
The empty function name popup is no longer visible.

Thanks to the team for quick fix. The new screenshot is enclosed for reference.
![RStudio 2020-06-30 11-06-07](https://user-images.githubusercontent.com/37381682/86087536-15c6e700-bac2-11ea-941f-bdac2a140ce7.png)

**Comment by R-Hannibal** [comment]
I will pass along the thanks, thank you @vinaychuri again for assisting us in improving the IDE.
