### ISSUE TITLE
remove duplicated symbol maps

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7155]
RStudio installations contain a duplicated set of symbol maps, located at these paths:

- www/WEB-INF/deploy/rstudio/symbolMaps
- www-symbolMaps

We should avoid this duplication, especially as the symbol maps are very large.

**Comment by ronblum** [comment]
Verified on in RStudio Desktop 2022.02.0+337 on MacOS 12.1.

***Before change, in build 324:***
> sh-3.2# ls -d RStudio-2022.02.0-daily-324.app/Contents/Resources/www-symbolMaps RStudio-2022.02.0-daily-324.app/Contents/Resources/www/WEB-INF/deploy/rstudio/symbolMaps/ 
RStudio-2022.02.0-daily-324.app/Contents/Resources/www-symbolMaps
RStudio-2022.02.0-daily-324.app/Contents/Resources/www/WEB-INF/deploy/rstudio/symbolMaps/

***After change, in build 337:***
>sh-3.2# ls -d RStudio-2022.02.0-daily-337.app/Contents/Resources/www-symbolMaps RStudio-2022.02.0-daily-337.app/Contents/Resources/www/WEB-INF/deploy/rstudio/symbolMaps/ 
ls: RStudio-2022.02.0-daily-337.app/Contents/Resources/www/WEB-INF/deploy/rstudio/symbolMaps/: No such file or directory
RStudio-2022.02.0-daily-337.app/Contents/Resources/www-symbolMaps

**Comment by kforner** [comment]
out of curiosity, what's the utility of those symbol maps ? 
I tried to delete them, and fail to see any actual impact on rstudio.
Thanks

**Comment by kevinushey** [comment]
These symbol maps are used by RStudio to remap obfuscated GWT exception stacks into something human-readable; this is mainly done for error reporting / logging.

**Comment by kforner** [comment]
Thanks a lot.
