### ISSUE TITLE
Find/All button does not return prompts if no hits

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#7156]
Right now, both **Next** and **Prev** buttons return "No more occurrences" if there is no hits. However, **All** button does not return anything if no hits occurs. This is very counter-intuitive and can be misleading in some scenarios. It is desired that **All** behaves in the same manner as Next/Prev.

![Snap154](https://user-images.githubusercontent.com/11802171/84979376-2cde0000-b0e4-11ea-8daf-29ff59a549a9.jpg)

**Comment by ronblum** [comment]
@Sibojang9 Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.3.1039 on MacOS 10.15.6 with R 4.0.0. We'll review this as we continue development of RStudio.
