### ISSUE TITLE
Select to Start/End works in a strange way

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#7159]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Debian GNU/Linux 9.12 (stretch)
    R Version       : 3.6.3
 
### Steps to reproduce the problem

* Open an R file and introduce some code, for [example](https://blog.rstudio.com/2020/02/25/rstudio-1-3-integrated-tutorials/):
```

library(tidyverse)
library(nycflights13)

summarise(
  flights,
  delay = mean(dep_delay, na.rm = TRUE),
  total = sum(dep_delay, na.rm = TRUE)
)
```
* Place the cursor at the beginning of `summarise` or `library(nycflights13)`
* Apply the keyboard shortcuts Ctrl+Shift+Up/Down or Shift+Alt+Up/Down

### Describe the behavior you expected

My goal was to select from that point to the end of the file. Before looking at the keyboard shortcuts list, by intuition I tried Shift+Alt+Down, but instead of the selection I saw like the line where the cursor had been placed was copied below it, so

```

library(tidyverse)
library(nycflights13)

summarise(
summarise(
  flights,
  delay = mean(dep_delay, na.rm = TRUE),
  total = sum(dep_delay, na.rm = TRUE)
)
```
Then, after looking at the keyboard shortcuts list, I saw the Select to Start/End line. In my keyboard (Lenovo ideapad 520S laptop) I do not have (I believe) the Home/End keys, so I tried with Up/Down instead (Ctrl+Shift+Up/Down).
Ctrl+Shift+Down does anything.
Ctrl+Shift+Up after pressing up 2 or 3 times may select all the file from cursor to the end or all the file.

I introduce this as a bug because the Shift+Alt+Down behaviour, not the other which I know has other associated instruction, but specify its behaviour because I also found its behaviour strange.

Thank you!

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Can you try this in the ACE kitchen sink application to see if we are behaving the same way?  We inherit a lot of behaviour from that.   https://ace.c9.io/build/kitchen-sink.html

**Comment by iago-pssjd** [comment]
Yes! If I try Shift+Alt+Down, it does the same behaviour I explained above.

**Comment by mikebessuille** [comment]
This is the stock behaviour of the ACE editor; tough for us to change it.
