### ISSUE TITLE
Resizing panels from splitted-screen to full-screen

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#7160]
This is Rstudio desktop 1.3.959 on Ubunutu 20.04. 

I have just a single screen and from time to time I divide it in two one for rstudio and one for other things (stackoverflow, some remote terminal...).

When resizing Rstudio via `CMD/window`+`arrow` the panel keep their relative size:
![Full-screen Rstudio](https://user-images.githubusercontent.com/6818218/85011188-7d477300-b161-11ea-9e2e-efa444f014dc.png)
![Splitted-screen Rstudio](https://user-images.githubusercontent.com/6818218/85011198-80426380-b161-11ea-931a-57e198bd6ef2.png)

However if I adjust manually the size of a panel, move the right panels to narrow it: 
![Rstudio with narrow side panel](https://user-images.githubusercontent.com/6818218/85010887-145ffb00-b161-11ea-93f3-6c5ea9432927.png)
 and then go back to full screen, they do not recover their relative size compared to the full screen:
![full screen Rstudio with narrow side panel](https://user-images.githubusercontent.com/6818218/85010918-1cb83600-b161-11ea-8ad1-5f6dc33a475c.png)

There is some resizing but not fully. Could it be made

**Comment by ronblum** [comment]
@llrs Thank you for raising this! However, I'm not sure I understand the issue. From what I can tell, the width of the columns maintains the ratio. In the first two images, the width of the left column accounts for about 55% of the total width of the RStudio window, whereas in the next two images, the width of the left column accounts for about 90% of the total width of the window. (These are rough percentages—I was using a tape measure on a screen.) Is this correct? Or are you expecting different behavior?

**Comment by llrs** [comment]
Sorry I didn't calculate it but to me it looked like on the last image the width was less percentage wise than on the previous one.

**Comment by ronblum** [comment]
@llrs No problem—I actually thought the same thing! I neglected to mention that I tried it out on an Ubuntu instances with multiple widths and it worked. So only then, I decided to use the tape measure. :)  I'm glad it's working!
