### ISSUE TITLE
Selecting "next plot" can result in "invalid plot index" error

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#7161]
### System details

    RStudio Edition : Desktop
    RStudio Version : Pro 1.4 1.4.467-4
    OS Version      : mac osx something too lazy to look
    R Version       : 4

### Steps to reproduce the problem
1) Generate several different plots.
2) click the previous-plot button once (to move to the 2nd last plot)
3) quickly click the next-plot button TWICE. (to go beyond last plot)

### Describe the problem in detail
You will see:
![image](https://user-images.githubusercontent.com/10076690/85038276-677f8100-b154-11ea-8c47-1667ef02055f.png)

### Describe the behavior you expected

no error

Note: if you slowly click the next button, it grays itself out and then you can't click it anymore so you never get this error.  (Sidenote: yes, that's the correct spelling of gray).

**Comment by mirh** [comment]
This is still a thing in 2023 with the new IDE.
