### ISSUE TITLE
incompatibility when install Rstudio in case the user name of win10 is Chinese

### ISSUE THREAD

**Issue by yjm1992312** [rstudio/rstudio#7162]
I've been suffering from Rstudio because the incompatibility in case the user name of win10 is Chinese. I’ve been using Rstudio for a couple of years, but this problem is still existing .So I hope the developer of Rstudio could help us solve the problem. 
In case the user name of win is Chinese, Rstudio can't display picture.And we must reset the PATH in environment variable,and set the PATH without including Chinese, or we must close the account including Chinese name. So it make us annoying when facing this problem.

**Comment by ronblum** [comment]
@yjm1992312 Thank you for raising the issue! We've unfortunately into other issues with non-ASCII characters. By not displaying a picture, do you mean plots? Or is the problem you're encountering by chance similar to the one in #5062? Thanks!
