### ISSUE TITLE
RStudio crashes on exit sometimes

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#7164]
Sometimes, when I close an RStudio instance which has a project opened, it will crash on exit right after the confirmation dialog to save the session, and next time I open RStudio, all the opened files are gone, including unsaved files.

Not exactly sure what makes it crash like that, or how to reproduce it. Happens quite rarely - once every couple days of daily usage - but it's extremely inconvenient as it loses the unsaved files.

**Setup:** RStudio 1.3.1004, R 4.0.1, running on debian linux.

**Comment by gregleleu** [comment]
I have had similar crashes, also hard to explain.
One case is when I use reticulate and if I clear the environment before exiting. Hope it helps.

**Comment by ronblum** [comment]
@david-cortes Does this only occur within a project, or also outside of one>

@gregleleu What environment are you working?

**Comment by gregleleu** [comment]
R desktop 1.4.45
R 3.6.2
OS X Catalina 10.15.4

**Comment by david-cortes** [comment]
I'm not sure if it occurs outside of projects, because I mostly work within projects. At least I haven't yet experienced any such crash when not working on a project.

Also I have experienced these crashes without the reticulate package being involved.

**Comment by mikebessuille** [comment]
We need steps to reproduce, or a call stack.  We haven't seen this behaviour internally.  Not much we can do with this without some more information.  I'll close as cannot repro, but if you find some way of reproducing it, please let us know as this issue would be considered high priority if we can repro it.
