### ISSUE TITLE
Very useful feature has been lost to work with Beamer!

### ISSUE THREAD

**Issue by RogerBorras** [rstudio/rstudio#7165]
In version 1.1 of Rsutdio, it was possible to create a Latex document, and when you had already compiled, with a double click on a part of the presentation in pdf you could go directly to the code to modify. It is a very useful feature that has been lost for those of us who create presentations in Beamer. It would be ideal to have this option again in the future!

**Comment by ronblum** [comment]
@RogerBorras Thank you for raising the issue! I'm marking it as a possible bug to review as we continue development of RStudio.

**Comment by jmcphers** [comment]
Can you provide some more detail on this? 

- What version of RStudio are you using?
- What operating system are you using it on?
- How are you writing LaTeX in RStudio? Rnw? R Markdown?
- What PDF viewer are you using?
