### ISSUE TITLE
DataViewer Multisort order is unintuitive

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#7167]
See Darby's comments here for a detailed reprex: https://github.com/rstudio/rstudio/issues/1691

~~Unfortunately, trying to do a multisort with how our data is set up through R's built in sorting algorithms isn't intuitive how you'd assume it to be when UI driven. It doesn't respect ordering or priority. There are other sort options (ideally we could use one from the tidyverse but we can't import external libraries) but nothing trivial to get working and test thoroughly that was in the scope of that bug fix.~~

~~We might want to consider writing our own priority sorting here to get the desired functionality.~~

EDIT: See comments below. I'm finally remembering why this was hard. It's not R's fault. The DataViewer API doesn't currently support passing in the order that the user clicked on the sort rows so we have no idea what their desired priority is. It wouldn't be _too_ hard to enhance this but DataViewer.js out of the box doesn't seem to support this.

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding something but wouldn't `order()` suffice here? E.g.

```
> df <- data.frame(
+   x = rep(1:2, each = 2),
+   y = rep(letters[1:2], times = 2)
+ )
> df[order(df$x, df$y), ]
  x y
1 1 a
2 1 b
3 2 a
4 2 b
> df[order(df$y, df$x), ]
  x y
1 1 a
3 2 a
2 1 b
4 2 b
```

**Comment by adamconroy** [comment]
I am using order. Maybe I was doing something wrong in how I set this up but was not able to get it to consistently sort how I wanted to. My R is very elementary so even getting the `do.call` syntax here was difficult for me. If I remember correctly, mixing in descending sorts was what was making it difficult. It was a while ago now though so my memory is a little hazy on why this didn't seem to work. https://github.com/rstudio/rstudio/commit/faec96448ffb6ee2dd789acadba65dee2401852b

**Comment by adamconroy** [comment]
Oh! Now I'm starting to remember some things. It might be ENTIRELY because we don't get any ordering from what comes from the UI. We have no idea what the user clicked on first because we just get the sort columns in index order and that's it. We would have to enhance the interface to get the user order there.

**Comment by adamconroy** [comment]
Thanks for forcing me to jog my memory so it's properly recorded here. Should have filed an issue as the previous one was closed when it was fresh in my mind.

**Comment by kevinushey** [comment]
Ahh! Got it, that makes sense.

The UI portion of this seems challenging as well -- we'd need some way of signaling both the columns being used for sorting, and the priority of those columns. I think what we have now is a reasonable compromise.
