### ISSUE TITLE
Continually crashing

### ISSUE THREAD

**Issue by slmeyer** [rstudio/rstudio#7178]
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4804671/diagnostics-report.txt)

### System details

    RStudio Edition : desktop 
    RStudio Version : 1.2.5042 
    OS Version      : Linux 5.4.44
    R Version       : 4.01

### Steps to reproduce the problem
1. open .rmd file
2. run some code or scroll down in the file
edit: It most often happens when I scroll up or down with the keyboard arrows, and now and then also when I run some code. It seems to happen more often when the window is very high

### Describe the problem in detail
RStudio becomes one white undivided window with one top line with menus. Menus can scroll down but items are non-functional. RStudio cannot be closed, must be killed with -9
Has only happened with this version of RStudio.
No other apps are crashing on my computers
Happens both on laptop and stationary computer.
Changing to software rendering did not help.
Deleting .Rstudio and reinstalling extra packages helped for a few days.
Now the problem is back more severely - can only work for a few minutes before it crashes

### Describe the behavior you expected
Continue to function like in the last five ten years

- [ X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
> [ X] I have installed the latest version of RStudio and confirmed that the issue still persists.

The latest version is 1.3 -- could you confirm that it still happens with that version? We have a preview here which may have a fix for the issue, too:

https://rstudio.com/products/rstudio/download/preview/

**Comment by slmeyer** [comment]
Thanks, I was able to install rstudio-desktop-preview-bin-1.3.1019, and for the first hour there was no problem, I will test more the next few days

**Comment by danmrc** [comment]
I am just here to add a data point to this: I am using arch (which manjaro is based on, if I am not wrong) and was having the same problem as well. Sometimes under 2 minutes of use were enough to make rstudio disappear with all the panes and the only way to close it was by giving a terminate command. Installing version 1019 solved it. 

If you guys want me to post the rstudio diagnostics let me know.

**Comment by ronblum** [comment]
@slmeyer Thank you for trying a more recent version and providing feedback@

@danmrc A diagnostic report would be useful. Also, which version of RStudio and R are you using—especially, are you using 1.3.x?

**Comment by danmrc** [comment]
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4822831/diagnostics-report.txt)

@ronblum there it is. A small comment: I had to reinstall the OS (not related to this in anyway), so this is a clean installation of RStudio 959. I didn't change the distro, btw, just reinstalled it. Since R updated today (or yesterday), I had this bug on both 4.0.2 and 4.0.1.

**Comment by slmeyer** [comment]
I had one more crash on my notebook with version 1.3.1019, then upgraded to 1.3.1039 and had no more problems, was working a few hours after that.

**Comment by ronblum** [comment]
@danmrc Thank you! And let us know if you run into this issue again.

@slmeyer The fix was included in the update, 1.3.1056 Water Lily: https://rstudio.com/products/rstudio/download/#download If it still doesn't work, please let us know!
