### ISSUE TITLE
Having "To Console"/"To Source" options for Update packages

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#7179]
Hi,

As in the panel tab `History` there are the options `To Console` and `To Source` instead of one to execute the instructions automatically, it would be nice to have similar options when one wants to update packages. 

After clicking the `Update` button of the panel tab `Packages`, the button `Install Updates` install the packages automatically, but one may interested in editing the way in which the previously selected packages have to be installed (beyond changing the options of the function `install.packages` one may be interested in changing the function). For that, `To Console` and/or `To Source` options would be great.

Thank you!

**Comment by ronblum** [comment]
@iago-pssjd Thank you for filing the ticket. Interesting suggestion! We'll consider it as we continue development of RStudio.
