### ISSUE TITLE
Compile Report to PDF doesn't work if LaTex isn't installed on Mac

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#7180]
### System details

    RStudio Edition : Desktop Pro
    RStudio Version : Version 1.4.467-4
    OS Version      : Mac OSX latest
    R Version       : 4

### Steps to reproduce the problem
Fresh install of RStudio 1.4.x on the Mac
From a simple R file, select "Compile Report".

### Describe the problem in detail
Receive the following:
![Screen Shot 2020-06-19 at 10 56 04 AM](https://user-images.githubusercontent.com/10076690/85150266-52702400-b220-11ea-8cd9-786b7224c620.png)
No PDF is generated, and I'm sad.

In particular, 
"! sh: pdflatex: command not found"

### Describe the behavior you expected

It should be able to generate PDF files out of the box, without having to install LaTex separately.
One suggestion: we already support tinytex in other workflows but not in the Compile Report workflow.  Perhaps if we detect that no pdflatex is foun, then we try tinytex (and offer to install tinytex if it's not already installed).

**Comment by rmflight** [comment]
I don't know what it's like on Mac, but on Linux it took some work to even install tinytex properly so that it was discoverable by RStudio.

I ended up borrowing from the code that the rocker project uses https://gist.github.com/rmflight/36b69b2608b070d0dcd38c87dd585d71

**Comment by mikebessuille** [comment]
On the Mac, I simply installed MacTex (http://www.tug.org/mactex/).  Restarted RStudio so it could find the latex and pdf tools, and it works fine.

**Comment by ronblum** [comment]
@mikebessuille Were you getting the same behavior as in RStudio 1.3?

@kevinushey This is the expected behavior, or at least has been so far—is that correct?

**Comment by ronblum** [comment]
I'm changing labels because as far as I can know, it's an enhancement request—at least that's based on the behavior it's always been. (Though consistency is the hobgoblin etc.)

**Comment by mikebessuille** [comment]
I didn't try 1.3, but I expect it would behave the same.  Yes, this is by design and should be considered an enhancement request.

**Comment by ronblum** [comment]
@mikebessuille Cool, thanks! I misread it as first as a bug report, which didn't seem quite right. Thanks!
