### ISSUE TITLE
Buiding project is causing View to change

### ISSUE THREAD

**Issue by ldecicco-USGS** [rstudio/rstudio#7181]
### System details

    RStudio Edition : Desktop 
    RStudio Version :  Version 1.3.959
    OS Version      :  Windows 10
    R Version       :  4.0.0

"Middlemist Red" (3a09be39, 2020-05-18) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.6 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem

I think it could be related to #5771.
So I open up a project, I can view data frames with the nice fancy RStudio viewer. When I load a package I'm working on, from that point on, all data frames are loaded like this:

![view](https://user-images.githubusercontent.com/1105215/85163210-23f64700-b228-11ea-848c-44f6b2ac49ae.gif)

If I use the "Install and Restart" in the Build tab to build my package, I don't have this problem! 

### Describe the problem in detail

I develop many packages, and most don't do this. There must be something unique to this package, but I can't figure it out.

Nothing unusual in the .Rproj folder as far as I'm concerned:
```
Version: 1.0

RestoreWorkspace: No
SaveWorkspace: No
AlwaysSaveHistory: No

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 2
Encoding: UTF-8

RnwWeave: Sweave
LaTeX: pdfLaTeX

BuildType: Package
PackageUseDevtools: Yes
PackageInstallArgs: --no-multiarch --with-keep.source
PackageCheckArgs: --as-cran
PackageRoxygenize: rd,collate,namespace

QuitChildProcessesOnExit: Yes
```

### Describe the behavior you expected

I'd like to always get the View to behave like this whether or not I'm 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can you share a reproducible example? (Are you able to share the package sources for which this issue reproduces?)

**Comment by ldecicco-USGS** [comment]
This is the project:
https://github.com/USGS-R/EGRET

I just tried a fresh checkout of that repo on the master branch, and it still did it for me on my computer.

**Comment by ronblum** [comment]
@ldecicco-USGS Thank you! I can reproduce it on MacOS 10.15.6, as well, from 1.4.673 and going back at least to 1.2.5040.

**Comment by ldecicco-USGS** [comment]
Gah, this is now happening in another Project. It's SO hard to troubleshoot package outputs when the view is stuck in 1992. If there's anything that might help speed this along. Here's the latest repo to give me the same problem:
https://github.com/USGS-R/dataRetrieval

**Comment by kevinushey** [comment]
This occurs because the EGRET package imports `utils::View`, and so when `devtools::load_all()` is executed the version of `View` bundled with R is placed earlier on the search path, in front of the RStudio version.

```
> devtools::load_all()
Loading EGRET
> exists("View", envir = as.environment("package:EGRET"), inherits = FALSE)
[1] TRUE
```

I think this happens because your package explicitly imports the `utils` package here:

https://github.com/USGS-R/EGRET/blob/0788dda94c6229af8bed77b83cadccdaff897900/R/EGRET.R#L19

The workaround / fix here would be to only import the specific functions from the `utils` package that you need to use, e.g. via `@importFrom utils <...>`.

**Comment by ldecicco-USGS** [comment]
AHH! Thank you!!! It was only in the old packages where I was lazy like that (at the time didn't know better), but was never able to figure out what was different. This just made my week!
