### ISSUE TITLE
New Terminal command fails to start a terminal

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7186]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.471 through 1.4.492+
    OS Version      : macOS (probably all, only tested on Mac)
    R Version       : 4.0.0

### Steps to reproduce the problem
- started after merge of #7079
- start IDE, focus in Console Pane
- Tools / Terminal / New Terminal (or use keyboard shortcut)

### Describe the problem in detail
- terminal tab not selected, no terminal started, and a JavaScript exception thrown:
- another variation is to click on the Terminal tab (which will start a terminal) then try to create another terminal; get the exception again, but if you switch back to Console then back to Terminal, that new Terminal will then be created

```
20 Jun 2020 22:54:06 [rsession-gary] ERROR CLIENT EXCEPTION (rsession-gary): (TypeError) : Cannot read property 'c' of undefined;
org/rstudio/core/client/layout/LogicalWindow.java#76::getActiveWidget
org/rstudio/studio/client/workbench/ui/PaneManager.java#438::getParentLogicalWindow
org/rstudio/studio/client/workbench/ui/PaneManager.java#469::onActivateConsolePane
org/rstudio/studio/client/workbench/ui/PaneManager_Binder__Impl.java#9::onCommand
org/rstudio/core/client/command/CommandEvent.java#40::dispatch
com/google/web/bindery/event/shared/SimpleEventBus.java#173::doFire
com/google/gwt/event/shared/HandlerManager.java#117::fireEvent
org/rstudio/core/client/command/AppCommand.java#131::doExecute
org/rstudio/core/client/command/AppCommand.java#125::execute
org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java#266::activateTerminal
org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java#157::onNewTerminal
org/rstudio/studio/client/workbench/views/terminal/TerminalTab_Shim__Impl.java#139::onSuccess2
org/rstudio/studio/client/workbench/views/terminal/TerminalTab_Shim__Impl.java#132::onSuccess
com/google/gwt/core/client/impl/OnSuccessExecutor.java#33::execute
com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks
com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands
com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute
com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute
com/google/gwt/core/client/impl/Impl.java#306::apply
com/google/gwt/core/client/impl/Impl.java#345::entry0
rstudio-0.js#-1::eval
com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap
Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e
User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```
### Describe the behavior you expected
- Terminal tab show be shown and a new terminal started

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.757, R Version - 4.0.2, Windows 10 x64 - Desktop 

Terminals are now opening successfully through all known vectors (Terminal Options, Keyboard Shortcuts, Menu options). Tested with focus on various elements of the IDE (Terminal pane, Console, Source).
