### ISSUE TITLE
Add feature to insert whitespace per 'expected whitespace' diagnistics checker

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#7193]
The 'expected whitespace' is - like many of the diagnostics and other helper functions - great.
One thing which would be wonderful is if this (and others?) came with an ability to have RStudio automatically fix these in a document. This is especially true when importing someone else's code, where every line might have multiple instances of whitespace rulebreaking.

Would this be an easy thing to implement? I figure the existing code already finds user code which breaks the rule, which seems like the biggest challenge?

Cheers!

**Comment by jmcphers** [comment]
Can you post a code sample along with what you expected the result to be? Very often the reason code shows diagnostic errors is that it doesn't parse (i.e. is ambiguous) so there's no way to change it without making inappropriate assumptions about intent. 

If you just want to enforce a particular whitespace style, may we suggest the styler plugin? It will give you a new "style active file" command that can be used to clean up other peoples' code.

https://www.tidyverse.org/blog/2017/12/styler-1.0.0/

**Comment by SimonDedman** [comment]
![image](https://user-images.githubusercontent.com/4599748/85344320-37154b00-b4a4-11ea-9e75-1ed10fdb6d6c.png)

Simple example of some code I found online & am looking to follow, but would like a quick 1-click cleaning solution for. Looks like styler will handle this with aplomb - I'll give it a try now, thanks.

Might be cool to add a note about Styler in Option/Code/Diagnostics page, maybe at the bottom, and ideally within the 'Using Code Diagnostics' page as well.

Cheers again!
