### ISSUE TITLE
Inconsistent behavior in `rstudioapi::getActiveDocumentContext`

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#7198]
### System details

    RStudio Edition : RSP and Desktop
    RStudio Version : 1.3.1039, 1.4.137
    OS Version      : Mac OSX, Ubuntu 18.04
    R Version       :  R.6.3

### Steps to reproduce the problem

1. Open an R file and add some text to it
2. With the console in focus, run `rstudioapi::getActiveDocumentContext()`. 

### Describe the problem in detail

`getActiveDocumentContext()` shows the information of the console rather than the source file that's open. 

```
> rstudioapi::getActiveDocumentContext()
Document Context: 
- id:        '#console'
- path:      ''
- contents:  <1 rows>
Document Selection:
- [1, 1] -- [1, 1]: ''
```

If you really hurry, you can press enter in the console, then switch focus to the editor and you'll get the editor info instead of the console.

### Describe the behavior you expected

In 1.4.137 (and, I believe, historical releases), the response would show you the context of the source document. i.e. you get an ID and the contents of the source panel. 

```
> rstudioapi::getActiveDocumentContext()
Document Context: 
- id:        'C69E8747'
- path:      ''
- contents:  <2 rows>
Document Selection:
- [2, 6] -- [2, 6]: ''
> 
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I think this is expected -- `getActiveDocumentContext()` shows you the "active" document, which may be the console if it's currently active (focused by the user).

I suspect you want to use `getSourceEditorContext()`, which should return information on the currently-focused editor in the Source pane.

**Comment by trestletech** [comment]
Aha! I was unaware of that one. It looks like `getSourceEditorContext()` reliably works on all the environments that we care about so I'm happy.

I do still believe that there was a change in the behavior of `getActiveDocumentContext()` between this versions. But I'm fine just using the other function instead so no need to investigate on my behalf.

**Comment by kevinushey** [comment]
It was, the old behavior you saw was buggy behavior :-)
