### ISSUE TITLE
Terminal output unique ID

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#7200]
Requesting an unique ID for 

terminal output (similar to console output ID "rstudio_console_output")

Thanks!

**Comment by gtritchie** [comment]
See also: #6926

Note that unless terminal hardware acceleration is off OR screen reader support is on there isn't any DOM element for the terminal output (it uses canvas for rendering).

**Comment by gtritchie** [comment]
There's an existing `class="xterm-rows"` on the div that wraps the terminal buffer (when using dom renderer), so that should be close to what you want.

**Comment by rich-rstudio** [comment]
verified
