### ISSUE TITLE
Variable explorer for Python when using in Rstudio

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#7201]
I really apprciated that recently Rstudio had a big update that now I can see the Python object right into Environment pane. Howerver, I would like to request that we need to preview the structure of dataframe like in R (please see the picture). If we can do this, I think more Python developer will try to using R as an IDE for Python. Thank you!
![image](https://user-images.githubusercontent.com/63569637/85437509-e0e3fd00-b5b4-11ea-9f90-faacd5f932a0.png)

**Comment by R-Hannibal** [comment]
@ntluong95, thank you so much for finding and reporting this way to make the RStudio + Python experience better. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you check it out and confirm that the issue has been addressed?

**Comment by melissa-barca** [comment]
Verified in 1.4.1013.
