### ISSUE TITLE
Automation - Unique ID for Launcher modal tabs

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#7202]
Requesting unique IDs for two tabs on the launcher job modal

<img width="655" alt="Screen Shot 2020-06-23 at 1 12 45 PM" src="https://user-images.githubusercontent.com/43964690/85440130-57e8a980-b553-11ea-8f3d-063391611b67.png">

**Comment by gtritchie** [comment]
please reopen in Pro
