### ISSUE TITLE
Automation - RSP Homepage unique IDs

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#7203]
Requesting Unique IDs for RSP homepage buttons

New Session
Suspend All
quit All

![Screen Shot 2020-06-23 at 1 15 00 PM](https://user-images.githubusercontent.com/43964690/85440677-eb21df00-b553-11ea-995a-9d2041137ac2.png)

Unique IDs for new session modal elements (launcher enabled)
![Screen Shot 2020-06-23 at 1 18 18 PM](https://user-images.githubusercontent.com/43964690/85440798-0a207100-b554-11ea-9929-bef04e773573.png)

**Comment by gtritchie** [comment]
Please reopen in pro
