### ISSUE TITLE
Inactivity Logout

### ISSUE THREAD

**Issue by MiguelGodinhoMatos** [rstudio/rstudio#7205]
### System details

    RStudio Edition : Server Pro
    RStudio Version : Version 1.3.959-1
    OS Version :  Centos
    R Version : 4.0.1 (will happen in 3.6.0 and 3.5.1 too) 

### Steps to reproduce the problem

(1) Have two Rstudio-Server sessions open for the same user.

(2) Leave one session idle for XX minutes while working on the second session. 

(3) XX is the configuration for the auto-logout time window

(4) You will be logged out of both sessions 

### Describe the problem in detail

If you have two sessions open and one of them is idle while the other is not you will still be logged out even if you are working. 

I expected not to be logged out, because the user is not idle even if one of his sessions is. 

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Thanks for reporting the issue. We are aware of this and are actively working on a fix.

Tracking this in our pro repo:
https://github.com/rstudio/rstudio-pro/issues/1731
