### ISSUE TITLE
Desktop IDE non-functional (/ not found)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7206]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.502 (wasn't broken in 1.4.501)
    OS Version      : macOS 10.15.5, windows-10
    R Version       : 4.0.0

### Steps to reproduce the problem
- install and launch latest daily build (1.4.502) on mac or Windows (haven't tried Linux)

### Describe the problem in detail
- main window is all white and contains text "/ not found"

<img width="851" alt="screenshot of broken main window" src="https://user-images.githubusercontent.com/10569626/85446512-64680480-b549-11ea-846a-ccadff9f3a0e.png">

### Describe the behavior you expected
- more stuff in main window

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.757, R Version - 4.0.2, Windows 10 x64 - Desktop 

Tested in the latest Daily, IDE is launching successfully (*and displaying more stuff in the main window 😉).
