### ISSUE TITLE
File type in source column modifies toolbar of different source panel

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7208]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.501
    OS Version      : only tried Mac, probably happens on all
    R Version       : 4.0.0

### Steps to reproduce the problem
- starting with clean workbench (nothing loaded in source editor, no source columns)
- "Enable additional columns" from command palette
- File / New File / Text File, to create Untitled1 in "classic" source pane
- note its toolbar:

<img width="188" alt="editor toolbar for untitled1 text file" src="https://user-images.githubusercontent.com/10569626/85459258-d430bc00-b556-11ea-9605-32b519e96870.png">

- Pane Layout, add a source column, creates new column with Untitled2 R script in it
- click in the source column to ensure it has focus
- File / New File / Text File to create Untitled3 in new source column, giving it two tabs
- Click back and forth between Untitled2 and Untitled3

### Describe the problem in detail
- the toolbar of Untitled1 changed when the new source column was originally added and R script created (the Text file now has the toolbar buttons for an empty R script)

<img width="197" alt="editor toolbar for untitled1 text file after creating source column" src="https://user-images.githubusercontent.com/10569626/85459703-515c3100-b557-11ea-90ba-95eac7f29594.png">

- when clicking back and forth between the R script and the Text file in source column, the Untitled1 toolbar changes state to match the type of the selected tab in the source column

### Describe the behavior you expected
- type of file selected in one source column shouldn't impact toolbar of another source pane

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
I just tried to reproduce and this is no longer an issue.

**Comment by rich-rstudio** [comment]
tried reproducing this on Desktop version 1.4.798 (MacOS) 

"Enable additional columns" is not an option in the command palette

**Comment by melissa-barca** [comment]
Hi @rich-rstudio the command has been renamed "Allow source columns".

**Comment by rich-rstudio** [comment]
not reproducible on Version 1.4.793, verified
