### ISSUE TITLE
Editing preferences pane is slightly cut-off

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7211]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.4.501
    OS Version      : macOS 10.15.5
    R Version       : R 4.0.2

### Notes

<img width="601" alt="Screen Shot 2020-06-24 at 10 46 07 AM" src="https://user-images.githubusercontent.com/1976582/85606437-051cf980-b608-11ea-8bd9-c95281707480.png">

Note that the Snippets button is slightly cut off.

**Comment by jmcphers** [comment]
I think we should fix this by moving the new Rainbow Parentheses option to Display.

**Comment by adamconroy** [comment]
I think that's an ok bandaid for now. I think we're probably close to needing a mini-overhaul to the options panels now to allow them to support further growth. On my screen there is still plenty of room in Editing so we're just not consistent across resolution sizes at the moment.

![7YRnDfs](https://user-images.githubusercontent.com/136863/85611106-9e0e3d80-b625-11ea-958c-0b9781d2f315.png)

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1043
