### ISSUE TITLE
"execute current statement" fails when rainbow parentheses disabled

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7212]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.4.501
    OS Version      : macOS 10.15.5
    R Version       : 4.0.2

### Steps to reproduce the problem

First, ensure the Rainbow Parentheses preference is disabled. Then, in a new R document, create a multi-line expression; e.g.

```
.rs.addFunction("foo", function()
{
  1 + 1
})
```

Then, place the cursor on the first line, and try to execute it with <kbd>Cmd + Enter</kbd>.

### Describe the problem in detail

The first two lines are executed; not the whole statement.

### Describe the behavior you expected

The whole statement should be executed.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dfalty** [comment]
Verified the whole statement is now run on version 1.4.874
