### ISSUE TITLE
Rstudio crashes if i open a Javascript plot (dygraphs or plotly) after running sqldf::sqldf

### ISSUE THREAD

**Issue by JohannesNE** [rstudio/rstudio#7219]
**Edit:** Updated to 1.3.1045. Problem still exists.

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1045
    OS Version      : Pop!_OS 20.04 LTS
    R Version       : 4.0.1

### Steps to reproduce the problem

```
# creates plot
dygraphs::dygraph(xts::as.xts(sunspots))

# creates df
sqldf::sqldf('select * from iris')

# Generates dygraph object
dygraph_obj <- dygraphs::dygraph(xts::as.xts(sunspots))

# Either of the following makes Rstudio hang
plotly::plot_ly(mtcars, x = ~hp,  y = ~wt)
dygraph_obj
```

### Describe the problem in detail

If i try to view a Javascript plot after having used the sqldf::sqldf function, Rstudio will hang with a white viewer plane.
A process named `/user/lib/rstudio/bin/rsession --config-file none --program-mode desktop --www-port [xxxxx] --launcher-token [xxxxxxxx]` will use 120% CPU.

I have to kill this process to be able to restart rstudio.

The above code works as expected if i use R from the terminal (opens plots in chrome).

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4831123/diagnostics-report.txt)
[diagnostics-report.txt - 1.3.1045](https://github.com/rstudio/rstudio/files/4835390/diagnostics-report.txt)

### Describe the behavior you expected

View plot without crash.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
You are using an older preview release. Would you be willing to try with our new preview, 1.3.1045? This looks like a bug we resolved recently.

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by JohannesNE** [comment]
Just updated to 1.3.1045. Same problem. I'll update the description.

**Comment by jmcphers** [comment]
Does switching to software rendering fix this? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by JohannesNE** [comment]
No, the problem persist with both software rendering and auto-detect

**Comment by JohannesNE** [comment]
This bug is still still relevant in RStudio version 1.4.1103

**Comment by kevinushey** [comment]
I was able to reproduce on Linux. Backtrace:

```
Thread 1 "rsession" received signal SIGINT, Interrupt.
futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x561ce9a83340)
    at ../sysdeps/nptl/futex-internal.h:183
183	../sysdeps/nptl/futex-internal.h: No such file or directory.
(gdb) bt
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x561ce9a83340)
    at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f54bda0d940, cond=0x561ce9a83318)
    at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x561ce9a83318, mutex=0x7f54bda0d940) at pthread_cond_wait.c:638
#3  0x00007f54bd99c0af in Tcl_WaitForEvent () from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
#4  0x00007f54bd9572ce in Tcl_DoOneEvent () from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
#5  0x00007f54d0ac4d1a in TclSpinLoop (data=data@entry=0x0) at tcltk_unix.c:60
#6  0x00007f54d9456c7a in R_ToplevelExec (fun=fun@entry=0x7f54d0ac4d00 <TclSpinLoop>, 
    data=data@entry=0x0) at context.c:778
#7  0x00007f54d0ac4ce8 in TclHandler () at tcltk_unix.c:69
#8  0x00007f54d95f2696 in R_ProcessEvents () at sys-unix.c:883
#9  0x00007f54d9497485 in R_CheckUserInterrupt () at errors.c:143
< ... >
```

So that TCL event loop is taking control and getting us stuck here.

**Comment by kevinushey** [comment]
FWIW the session can recover if you explicitly send an interrupt; e.g.

```
kill -SIGINT $(pgrep -nx rsession)
```

And this is a simpler reprex:

```
library(tcltk)
dygraphs::dygraph(xts::as.xts(sunspots))
```
