### ISSUE TITLE
'Restart R' deletes variables in server version

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#7230]
**Steps to reproduce:**
* Launch an RStudio Server session.
* Create some variables in there.
* Restart R through `Session` -> `Restart R`.

**Expected behavior:** should restart R, keeping all the variables/objects that were there in the session before.

**Actual behavior:** restarts R, but all the variables/objects from the session are gone.

**Setup:** RStudio Server 1.2.5042, R 3.6.3, running on ubuntu 18.04, accessed through Vivaldi web browser.

**Comment by kevinushey** [comment]
What's the value for your `Save workspace to .RData on exit` preference? I can reproduce if I have this set to `Never`, as here:

<img width="599" alt="Screen Shot 2020-06-26 at 3 08 23 PM" src="https://user-images.githubusercontent.com/1976582/85904957-e3b23e00-b7be-11ea-84fb-b1fc650ec659.png">

**Comment by david-cortes** [comment]
It was set to "Never", and the variables are kept if I change it to "Ask".

**Comment by david-cortes** [comment]
@ronblum : shouldn't this design be changed? I mean, saving variables when exiting the session is one thing, but restarting it is a different thing. And it also doesn't ask for saving them when restarting the R session if I set the setting to "ask".

**Comment by ronblum** [comment]
@david-cortes Ah, I see what you mean. I'll reopen.

@kevinushey What are your thoughts on this? Is the option meant to only affect what happens when RStudio is closed/started up, or any time that an R session is closed/started?

**Comment by kevinushey** [comment]
I think this is the currently-intended behavior, but I think it's worth considering having separate preferences controlling this behavior. That is:

1. Whether or not we save / restore the environment when the session is quit, versus
2. Whether or not we save / restore the environment during a restart

are worth providing separate configuration for. (Option 2 could inherit from the value of 1 when unset, if we wanted to be "fancy" and preserve the current behavior.)

**Comment by david-cortes** [comment]
Still reproducible in the latest daily build.
