### ISSUE TITLE
R code execution error in Viewer with fs output

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#7239]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1050
    OS Version      : macOS 10.15.5
    R Version       : 4.0.1

### Steps to reproduce the problem

Run the following in the console:

```r
View(fs::dir_info())
```

### Describe the problem in detail

When I run the code above I get the following error in the console:

```r
#> Error in FUN(X[[i]], ...) : 
#>   INTEGER() can only be applied to a 'integer', not a 'double'
#> Error in FUN(X[[i]], ...) : 
#>   INTEGER() can only be applied to a 'integer', not a 'double'
```

The Viewer pops up, but gives an error as well `r error 4 (R code execution error)`:

<img width="759" alt="Screenshot 2020-06-26 at 21 21 23" src="https://user-images.githubusercontent.com/5965649/85903768-111edc00-b7ff-11ea-8cc8-b8760e4b3fe6.png">

Clicking Retry results in two more of the `INTEGER() can only be applied to a 'integer', not a 'double'` errors being printed in the Console and doesn't fix the issue.

### Describe the behavior you expected

Output of `fs::dir_info()` is a `data.frame`:

```r
class(dir_info())
#> [1] "data.frame"
```

so I expected that data frame to appear in the Viewer.

@jimhester suggested this might be because RStudio unconditionally coerces all vectors where `is.numeric()` returns `TRUE` to doubles at https://github.com/rstudio/rstudio/blob/3fdda38e9a78a984a25c44e1672cf0869fad19cd/src/cpp/session/modules/SessionDataViewer.R#L31 even though in this case the vector should actually be an integer. So then when the `format()` method runs on it, it fails. A minimal reprex is:

```r
x <- fs::as_fs_perms("777")
storage.mode(x) <- "double"
format(x)
#> Error in FUN(X[[i]], ...): INTEGER() can only be applied to a 'integer', not a 'double'
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by thomasvconti** [comment]
I am having the same issue and could not find a solution anywhere. Is there a workaround available?
