### ISSUE TITLE
Sections don't work since 1.3.959

### ISSUE THREAD

**Issue by felixradtke** [rstudio/rstudio#7241]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1050
    OS Version      : macOS 10.15.5. Reproducible in Windows 10, Version 1909.
    R Version       : 4.0.2

### Steps to reproduce the problem
1. Create a new R script / open one
2. Create the following line of code:
#####Test

### Describe the problem in detail
No new section with the name "Test" is introduced.

### Describe the behavior you expected
Before version 1.3.959, that line of code would introduce a section named "Test" that could be selected in the sections selector above the panel (which is set to '(Top Level)' in default). Currently, only untitled sections work as expected (just '#####' in one line). The issue was introduced in version 1.3.959 but still persists in the current version (1.3.1050).

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report (not necessary here)
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
The canonical format for sections is:

```
# Section Name ----
```

This is what you'll get with the Insert Section command. I'm surprised that `#### Test` worked as a section header in the past as it doesn't adhere to our section formatting rules.

https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections

**Comment by felixradtke** [comment]
@jmcphers Thank you for your fast response! Wow, that was surprising. I wasn't aware of that, since #####Test always worked before - but apparently wasn't the expected behavior. Thank you!
