### ISSUE TITLE
Disable Crash Reports Pop Up 

### ISSUE THREAD

**Issue by Nelson-Gon** [rstudio/rstudio#7243]
### System details

    RStudio Edition :  Desktop 
    RStudio Version : ‘1.3.959’
    OS Version      :  Windows 10
    R Version       :  R version 4.0.0 (2020-04-24

### Steps to reproduce the problem

* Open RStudio

### Describe the problem in detail

A pop up appears telling one to enable automatic crash reporting to RStudio. This can be disabled in Global options but not the pop up itself.
### Describe the behavior you expected

I expected to open RStudio and start writing code. I did not expect to have a popup. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
This pop up should only occur once. See #7134 

> Whenever you respond to the prompt, a file should be created at %LocalAppData%\R\crash-handler-permission. If that file does not exist, you can simply create it manually (and leave it empty) to get the prompts to stop showing.
