### ISSUE TITLE
Rstudio incorrectly interpretes ANSI inverse sequence

### ISSUE THREAD

**Issue by january3** [rstudio/rstudio#7250]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Ubuntu 16.04 LTS
    R Version       :  3.6.3

### Steps to reproduce the problem

Compare the output of the following command in rstudio and in vanilla R:

cat("\033[7m\033[31mThis is visible in both \033[39mThis is visible only in the terminal\033[27m")

or, equivalently,

library(crayon)
cat(inverse(red("This is visible in both ") %+% "This is visible only in the terminal"))

In the default terminal:
First part is white on red.
Second part is white on black.

In rstudio:
First part is red on black.
Second part is black on black.

### Describe the problem in detail

If an ANSI escape sequence is within the "inverse" tags, then foreground and background should be exchanged. This happens in the default R terminal. However, in Rstudio, if a tag within the inversed text sets the foreground color, then this foreground color is not exchanged with the background.

### Describe the behavior you expected

Behavior identical to default R terminal.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Confirmed as a bug in RStudio 1.3 (and also 1.2 and 1.1, so not a regression).

**Comment by gtritchie** [comment]
These are generally safe fixes (lot of unit-test coverage of this area), recommend leaving in 1.4.

**Comment by R-Hannibal** [comment]
@january3, thank you for finding and reporting this issue and the level of detail provided.

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by kfeinauer** [comment]
Verified fixed RDP 1.4.938-3
