### ISSUE TITLE
Typo in Review Changes dialog

### ISSUE THREAD

**Issue by BastiHz** [rstudio/rstudio#7254]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1054
    OS Version      : Windows 10
    R Version       : 4.0.2

Sorry, this is a bit nitpicky. Would try a fix myself but currently don't have the time to learn and set up the dev environment.

### Steps to reproduce the problem
In the git pane click on "commit" which opens the "Review Changes" window.
### Describe the problem in detail
The "Context" dropdown says "5 line", "10 line", etc.
### Describe the behavior you expected
It should be plural: "5 lines", "10 lines", etc., same as "All lines".

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
That's a tricky one, grammatically. You could read "Context: 5 line" as shorthand for either "show a 5-line context" or "show 5 lines of context". In any case there's an inconsistency due to the "All lines" being there. :-)

**Comment by gtritchie** [comment]
I do agree that the plural form is more natural. I could have fixed it in the time it took me to write this, so maybe I should just do that.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.747, R Version - 4.0.2, Windows 10 x64 - Desktop

All listed context dropdown menu entries have been updated to the plural '...lines'.
