### ISSUE TITLE
Emoji Unicode not showing in RStudio console

### ISSUE THREAD

**Issue by corriebar** [rstudio/rstudio#7255]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.959
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.2 (2020-06-22) -- "Taking Off Again"

### Steps to reproduce the problem
I was having some encoding issues and was going through the vignette of the `utf8` package https://cran.r-project.org/web/packages/utf8/vignettes/utf8.html

When using the following command in the Rstudio console (or in an Rmarkdown cell)
```r
print(intToUtf8(0x1f600 + 0:79)) # base R
```
I was expecting the result as described in the vignette:
```
[1] "\U0001f600\U0001f601\U0001f602\U0001f603\U0001f604\U0001f605\U0001f606\U0001f607\U0001f608\U0001f609\U0001f60a\U0001f60b\U0001f60c\U0001f60d\U0001f60e\U0001f60f\U0001f610\U0001f611\U0001f612\U0001f613\U0001f614\U0001f615\U0001f616\U0001f617\U0001f618\U0001f619\U0001f61a\U0001f61b\U0001f61c\U0001f61d\U0001f61e\U0001f61f\U0001f620\U0001f621\U0001f622\U0001f623\U0001f624\U0001f625\U0001f626\U0001f627\U0001f628\U0001f629\U0001f62a\U0001f62b\U0001f62c\U0001f62d\U0001f62e\U0001f62f\U0001f630\U0001f631\U0001f632\U0001f633\U0001f634\U0001f635\U0001f636\U0001f637\U0001f638\U0001f639\U0001f63a\U0001f63b\U0001f63c\U0001f63d\U0001f63e\U0001f63f\U0001f640\U0001f641\U0001f642\U0001f643\U0001f644\U0001f645\U0001f646\U0001f647\U0001f648\U0001f649\U0001f64a\U0001f64b\U0001f64c\U0001f64d\U0001f64e\U0001f64f"
```

but instead only got an empty string:
```
[1] ""
```
that interestingly when I copy-paste it actually does give me all the smileys:
```
[1] "😀😁😂😃😄😅😆😇😈😉😊😋😌😍😎😏😐😑😒😓😔😕😖😗😘😙😚😛😜😝😞😟😠😡😢😣😤😥😦😧😨😩😪😫😬😭😮😯😰😱😲😳😴😵😶😷😸😹😺😻😼😽😾😿🙀🙁🙂🙃🙄🙅🙆🙇🙈🙉🙊🙋🙌🙍🙎🙏"
```

If I run the same command from the terminal, it shows all the smileys correctly:
![image](https://user-images.githubusercontent.com/11877945/86240468-96104980-bba1-11ea-9b51-37df9eb6cf6e.png)

Running `Sys.getlocale()` gives me the same result both in the IDE and the terminal:
```
[1] "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=de_DE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=C"
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@corriebar Thank you for raising this! However, I can't reproduce this on Ubuntu 20.04, both in RStudio Server and Desktop; I get the smileys in both cases. What do you get when you run the command in standalone R?

**Comment by corriebar** [comment]
In the screenshot you can see that in RStudio, no smileys are shown and overlain is where I run the command in R run in the terminal (I assume that's what you mean with standalone R, right?). So in R without RStudio the command works fine (I was actually surprised the terminal can display emojis).

**Comment by ronblum** [comment]
@corriebar I'm sorry, I completely misunderstood the screenshot. OK—we'll review the issue as we continue RStudio 
 development.

@kevinushey Do you have any suggestions?

**Comment by kevinushey** [comment]
Interestingly, it works fine for me with the latest RStudio release (v1.3.1058; Ubuntu 20.04)

<img width="524" alt="Screen Shot 2020-07-29 at 10 32 52 AM" src="https://user-images.githubusercontent.com/1976582/88833314-ea99eb00-d186-11ea-8511-632beca013be.png">

What editor font are you using in the IDE? It looks like Ubuntu Mono, which I'm also using in my case and does work without issue.

Can you also share the output of `sessionInfo()`, just in case the behavior here depends on the R packages you have loaded / installed?

Can you think of anything else that might affect this behavior in your environment?

**Comment by corriebar** [comment]
Editor font is Ubuntu Mono. The behaviour also persists on a freshly loaded session
```{r}
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2    tinytex_0.23   xfun_0.14  
```

I tried some other fonts but it doesn't seem to change anything.
I was at some point wondering if it could also be a problem with my system. I noticed when copy-pasting some other R code with smileys into Slack, in the automatic code-formatting, the smileys also vanish.

**Comment by kevinushey** [comment]
Interesting -- if it reproduces in other Chromium applications (e.g. Slack), it may ultimately be a Chromium bug. If that's the case, there's unlikely to be much we can do on the RStudio side.

**Comment by Thell** [comment]
Fonts are tricky. Plain and simple. I was having issues with emoji rendering as well, and its doubtful they are going to go away completely but @corriebar one thing to do is make sure that you have your fonts setup _before_ you do your RStudio Desktop install, and if you do font changes then reinstall RStudio Desktop (perhaps you don't _need_ to reinstall and you could just remove your state, desktop prefs and such to force a reset/reload).

In my setup script I found that if I omitted any of the the three apt installed fonts then I'd get FUBAR results

```bash
cd /tmp
URL=https://api.github.com/repos/microsoft/cascadia-code/releases/latest
URL=$(curl ${URL} | grep download_url | cut -d\" -f4)
FONT_DIR="/usr/local/share/fonts/truetype/cascadia"
mkdir -p ${FONT_DIR}
curl -L -o cascadia-code.zip ${URL}
unzip cascadia-code.zip ttf/*.ttf -d ${FONT_DIR}

export DEBIAN_FRONTEND=noninteractive
packages=(
  ### APT Setup
  # With recommends.
  fonts-noto-color-emoji
  fonts-ubuntu-console
  fontconfig
  ttf-bitstream-vera
)
apt-get -y install ${packages[@]}
```

Even with these the results are a mish-mash of failure and success...

Consider both a
`wget https://unicode.org/Public/emoji/5.0/emoji-test.txt`
and
`devtools::install_github("hadley/emo")`
and then using both
`file.show("~/emoji-test.txt"`
along with
`cat(emo::jis[,3],'\n')`
and
`R -s -e "cat(emo::jis[,3],'\n')"`
in both the RStudio Desktop console and terminal as well as your OS terminal...

For me... the `cat` emoji in the RStudio console shows everything 👌 and the `file.show` of the test doc opens a tab displaying everything 👌 **but** if I copy the `R information` tab contents that was opened from the `file.show` command into a new tab then all the flags are borked along with a few other things (which are the same results I get from the OS shell) and if I issue the `cat` commands in the RStudio terminal I get totally messed up results where the "parts" (if that is what they are called) of the emoji overlaps and spacing is, well, horrid.

![image](https://user-images.githubusercontent.com/2185020/89263441-e8a4b180-d5f6-11ea-940a-146f4f3cc287.png)

![image](https://user-images.githubusercontent.com/2185020/89263825-89936c80-d5f7-11ea-97a9-2e3b9f8529e0.png)

you can't tell in that last image but everything in the terminal is actually worse than it appears at first glance...

![image](https://user-images.githubusercontent.com/2185020/89263952-c2cbdc80-d5f7-11ea-931b-037f8a417f05.png)

The point to all of that is... it isn't easy to get all the stars aligned to have things just work with fonts, but at least using that test document and Hadley's `emo` package you can quickly test a variety of setups while resetting everything in between. (How fun, right? lol)

**Comment by corriebar** [comment]
I tried the commands before and after install the packages and also reinstalled RStudio (now on version 1.4.531) but the results are unchanged:
This is what I get in RStudio:
![Rstudio_emojis1](https://user-images.githubusercontent.com/11877945/89293504-4f10ea80-d65e-11ea-9623-993d6ddce43d.png)
Interestingly, the result in the Rstudio Terminal is the same as in the RStudio console, whereas the output in the OS terminal looks like your output, bad spacing and partials:
![terminal_emojis1](https://user-images.githubusercontent.com/11877945/89293602-7798e480-d65e-11ea-9fae-de4a7a4141ed.png)
