### ISSUE TITLE
Install packages helper - completion text "successfully installed" when install fails

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#7259]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1011 (when bug discovered)
    OS Version      : Xubuntu20.04 (now 19.10)
    R Version       : 4.0.1 (now 3.6.3)

### Steps to reproduce the problem
See #7078 , install packages helper's completion text can tell you it was successful even if it wasn't:

> checking for gdal-config... no
> no
> configure: error: gdal-config not found or not executable.
> ERROR: configuration failed for package ‘sf’
> * removing ‘/home/simon/R/x86_64-pc-linux-gnu-library/3.6/sf’
> 
> The downloaded source packages are in ‘/tmp/Rtmp64YkGA/downloaded_packages’
> 
> ✔ Package 'sf' successfully installed.
> Warning message:
> In utils::install.packages("sf", repos = "https://cloud.r-project.org") :
>   installation of package ‘sf’ had non-zero exit status

**Comment by ronblum** [comment]
@SimonDedman Thank you for filing the issue, separating it from the original request!

**Comment by ronblum** [comment]
Another example, from #8721: 

```Installing 'png' for Python/Reticulate...
Installing package into ‘/home/at/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/png_0.1-7.tar.gz'
Content type 'application/x-gzip' length 24990 bytes (24 KB)
==================================================
downloaded 24 KB

gcc -I/opt/R/3.3.3/lib/R/include -DNDEBUG  -I/usr/local/include    `libpng-config --cflags` -fpic  -g -O2  -c read.c -o read.o
* installing *source* package ‘png’ ...
** package ‘png’ successfully unpacked and MD5 sums checked
** libs
/bin/bash: libpng-config: command not found
/opt/R/3.3.3/lib/R/etc/Makeconf:132: recipe for target 'read.o' failed
read.c:3:17: fatal error: png.h: No such file or directory
compilation terminated.
make: *** [read.o] Error 1
ERROR: compilation failed for package ‘png’
* removing ‘/home/at/R/x86_64-pc-linux-gnu-library/3.3/png’

The downloaded source packages are in
	‘/tmp/RtmpPp4MAs/downloaded_packages’


✔ Package 'png' successfully installed.
Warning message:
In utils::install.packages("png", repos = "https://cran.rstudio.com/") :
  installation of package ‘png’ had non-zero exit status
```

**Comment by ronblum** [comment]
Note: this is an issue when installing by clicking on "Install" at the top of an R Markdown file if a missing library is detected. The misleading success statement doesn't appear when run:
- directly in the console
- in standalone R
- as job using a script

(In this case, I tested the installing the R package `bbsBayes` without first installing JAGS, on which it depends.)
