### ISSUE TITLE
Tabular editing model for delimited text files

### ISSUE THREAD

**Issue by Patrick330** [rstudio/rstudio#7262]
It would be very beneficial to have a basic tabular editing interface for CSV, TSV, and other delimited text files. 

I work with Rstudio Server on a linux platform, and I often use CSV files to define parameters for the code I execute in R. In order to edit these on the linux server, I must open a remote desktop session and spin up LibreOffice. It is the only task that cannot be performed in either Rstudio or in the terminal.

Presently opening CSV files in Rstudio as text not only compresses the columns together, making it difficult to locate each one, but it also turns on word wrapping so that files with long lines are even more difficult to navigate.

Issue #2163 offers an enahancement intended to improve working with TSV files. Perhaps this could be expanded to align text in columns using the delimeter of the file.

**Comment by ronblum** [comment]
@Patrick330 Thank you for filing the suggestion, and for referencing the related enhancement! We'll review this as we continue development of RStudio.
