### ISSUE TITLE
Executing a traceback `trace(utils:::unpackPkgZip, edit=TRUE)` with Rendering Engine set to 'software' mangles the edit screen display.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#7266]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1054
    OS Version      : Windows 10 x64
    R Version       : 4.0.2

### Prerequisites

- Have the IDE's Rendering Engine set to Software (Tools > Global Options > General > Advanced).

### Steps to reproduce the problem

1. Enter `trace(utils:::unpackPkgZip, edit=TRUE)` in the console.

### Describe the problem in detail

The Edit screen that appears is translucent, text is mangled, and scrolling only appears to worsen the issue. This makes editing in this way virtually impossible.

![Software Rendering scary](https://user-images.githubusercontent.com/62304541/86410482-6dab4c80-bc80-11ea-8cbd-d5c2f866826f.gif)

### Describe the behavior you expected

The Edit screen is displayed successfully, whether instantly or after a delay if it needs to load/render before displaying.

### Notes

- This issue is NOT a regression, confirmed to be occurring in **1.3.959**.
- Adding the Windows label as I have not been able to reproduce this issue on Mac, including the console error I'm getting on Mac below:

```
trace(utils:::unpackPkgZip, edit=TRUE)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
  object 'unpackPkgZip' not found
>
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
A smaller reprex:

```
utils::file.edit("test.txt")
```

Looks like this only happens on Windows. Very weird!
