### ISSUE TITLE
Keyboard shortcut `Ctrl+Shift+R` not working in R Markdown documents

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rstudio#7268]
Appreciate the [code section](https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections) creator for r scripts. It helps to organize the codes. Neither the shortcut `ctrl+shift+r` nor the menu option doesn't work for code chunk in Rmarkdown however. It would be wonderful if it does.

**Comment by ronblum** [comment]
@sammo3182 Thank you for suggesting this! We'll review the enhancement request as we continue to develop RStudio.
