### ISSUE TITLE
Ctrl-Up and Ctrl-Down in editor jump between function definitions instead of scrolling a line in .R file

### ISSUE THREAD

**Issue by Takkoona** [rstudio/rstudio#7269]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.959
    OS Version      : Windows 7 [Desktop] and Ubuntu 18.04.4 using docker [Server]
    R Version       : 4.0.2 [Desktop] and 4.0.0 [Server]

### Steps to reproduce the problem

1. Create a test.R file with multiple function definitions.  For example:
```r
# test.R file

testFunc1 <- function(x, y) {
  print(x)
  print(y)
}

testFunc2 <- function(x, y) {
  print(x)
  print(y)
}

testFunc3 <- function(x, y) {
  print(x)
  print(y)
}

testFunc4 <- function(x, y) {
  print(x)
  print(y)
}

testFunc5 <- function(x, y) {
  print(x)
  print(y)
}

testFunc6 <- function(x, y) {
  print(x)
  print(y)
}
```
2. Open the test.R file in RStudio source editor.
3. Ajust the source editor pane size if needed to make sure its scrollbar appears.
4. Move cursor focus to source editor.
5. Press `Ctrl+Up` and `Ctrl+Down` to scroll the editor pane.

### Describe the problem in detail

Using `Ctrl+Up` and `Ctrl+Down` will scroll the editor pane and jump between function definitions in .R file.  For example:
1. Assume the cursor is at the line `print(y)` inside `testFunc3`, 
2. Pressing `Ctrl+Up` will move the cursor to the begining of the line `testFunc3 <- function(x, y) {`.
3. Press `Ctrl+Up` again, the cursor will move to the begining of the line `testFunc2 <- function(x, y) {`. 
4. Now if press `Ctrl+Down`, the cursor will go back to the begining of the line  `testFunc3 <- function(x, y) {`. 

The pane will scroll during the process depending on the initial position of the scrollbar.

But they do scroll the pane by one line and no jumping between function definitions when:
1. Using on other files such as C++, Rmd files
2. Change to other key bindings, such as `Alt+PageUp` and `Alt+PageDown`
3. There is no function definition code in the .R file

### Describe the behavior you expected

Using `Ctrl+Up` and `Ctrl+Down` scroll a line even with function definition(s) present in .R file.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Takkoona Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.3.1056 on Windows 10. We'll review this as we continue development of RStudio.
