### ISSUE TITLE
"Run Tests" button runs tests without running setup or teardown scripts

### ISSUE THREAD

**Issue by d-sci** [rstudio/rstudio#7271]
### System details

    RStudio Edition : Desktop (but I've experienced it on Server too)
    RStudio Version : 1.3.959 (but it's been present ever since introduction of the "Run Tests" button)
    OS Version      : Mac OS 10.15.5 (but I've experienced it on Ubuntu too)
    R Version       :  4.0.0 (but I've experienced it on 3.5 and 3.6 too)

### Steps to reproduce the problem
Create a test file using the testthat framework that relies on a `setup-*.R` script in tests/testthat (see example).
Run the test file by clicking the "Run Tests" button in the IDE.

### Describe the problem in detail
When I run a test file using `devtools::test(filter = '[regexp filtering to my file]')`, it first runs the `setup` scripts in tests/testthat, then the tests scripts, then the `teardown` scripts. But when I click the "Run Tests" button, it does not appear to run the setup or teardown scripts. This means tests relying on them can pass in the console but not in the build pane. 

As a specific (but contrived) example, I can have a `setup-env.R` script that runs `Sys.setenv(MY_TESTING_ENVVAR = 'value')` , and a `teardown-env.R` script that runs `Sys.unsetenv('MY_TESTING_ENVVAR')`. A test file that relies on the env var will then pass when run via `devtools::test` but fail when run via the "Run Tests" button:

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/6467018/86496316-e545ae00-bd4a-11ea-8ba4-a8396ed5c3e2.png">

Obviously there's some overlap with `testthat` and/or `devtools` here, but to me this does seem to be an issue with the "Run Tests" button in the IDE specifically. `devtools::test(filter = '^{name_of_current_file_without_test_prefix}$')` does exactly what I expect.

### Describe the behavior you expected

Clicking the "Run Tests" button should also run setup/teardown scripts, in addition to the test script, so that tests that rely on it can still pass. It should be roughly equivalent to running `devtools::test(filter = '^{name_of_current_file_without_test_prefix}$')`. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
We should likely call `devtools::test_file()` rather than `testthat::test_file()` here:

https://github.com/rstudio/rstudio/blob/b65bc9fbe62c8fc2ae9e984006de4094442bb1b1/src/cpp/session/modules/build/SessionBuild.cpp#L1172-L1175

**Comment by d-sci** [comment]
It appears that in testthat >= 3.0.0, `testthat::test_file` does run setup/teardown scripts. Closing issue, which in retrospect could have just been an issue for testthat in the first place.
