### ISSUE TITLE
Wrong indents in document outline when function doc contains macro

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#7273]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.538
    OS Version      : MacOS 10.15.5
    R Version       : 4.0.0

### Steps to reproduce the problem

place the following in an R script

```r
#' An x function
#'
fnx <- function(x) {
  return(x)
}

#' A y function
#'
#' \lifecycle{deprecated}
fny <- function(y) {
  return(y)
}
```

### Describe the problem in detail

When the Roxygen text in an R file contains a `\macro{command}`, the indentation in the document outline is wrong - the outline looks as if the below function were nested inside the above function. When the macro line is removed, the indentation in the outline is correct. When the bracketed part in the macro is removed, the indentation is incorrect in a different way (different number of tabs/spaces.) 

### Describe the behavior you expected

Functions existing at the same level in a script should appear at the same level in the outline.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I'm not able to reproduce:

<img width="293" alt="Screen Shot 2020-07-06 at 9 38 42 AM" src="https://user-images.githubusercontent.com/1976582/86617697-7e9fda80-bf6c-11ea-877f-516fea508d7a.png">

... unless I turn on rainbow parentheses:

<img width="319" alt="Screen Shot 2020-07-06 at 9 40 17 AM" src="https://user-images.githubusercontent.com/1976582/86617820-b4dd5a00-bf6c-11ea-97c4-04123c43567b.png">

Are rainbow parentheses enabled in your case?

**Comment by petrbouchal** [comment]
> Are rainbow parentheses enabled in your case?

Yes, they are - sorry, hadn't tested that eventuality.

**Comment by kevinushey** [comment]
> Yes, they are - sorry, hadn't tested that eventuality.

No worries; there are a lot of knobs and dials in the IDE and it's rarely clear which knobs might affect other parts of the IDE!

**Comment by kevinushey** [comment]
@adamconroy it looks like this gets into some of the hairier parts of the Ace tokenizer; I'm going to take a look.

**Comment by R-Hannibal** [comment]
@petrbouchal, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you take a look and let us know if the issue is resolved for you in that build?

**Comment by ronblum** [comment]
Verified in RStudio 1.4.727 on MacOS 10.15.6.

**Comment by petrbouchal** [comment]
Thanks - also am no longer seeing the issue - RStudio 1.4.727 on MacOS 10.15.5.
