### ISSUE TITLE
Selecting a document in tab overflow document switch menu in the source pane fails to change focus to the relevant document.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#7274]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.538
    OS Version      : Windows 10 x64
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Open RStudio. 
2. Open enough documents that it triggers the tab overflow document switch menu (example - 9 new R Scripts).
3. Select the tab overflow switch menu > select one of the documents from the list:
![tab_overflow_document_switch](https://user-images.githubusercontent.com/62304541/86535586-00c5cb80-bea7-11ea-83c9-e04521c873e1.png)

### Describe the problem in detail
Selecting a document from the list fails to switch focus to that document (essentially the menu appears non-functional).

### Describe the behavior you expected
Focus is switched to the selected document when selected from the menu as seen in previous versions and builds.

### Notes
[Note 1] This issue does **NOT** occur in the last stable build (1.3.959) or the latest preview build (1.3.1054). It appears to be newly introduced to the 1.4 branch.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
The first build where this is broken is v1.4.471 (it works in v1.4.470). Note sure how to easily ascertain which commits went into 1.4.471 but it should be pretty easy to figure out from there.

**Comment by jmcphers** [comment]
@melissa-barca The commit that landed in build 471 was the merge of the source column work (https://github.com/rstudio/rstudio/commits/4a5046f92f55bc1a6b3104db8a5ff470cadfccc3) so this is likely fallout from that change. Would you be willing to take a look?

**Comment by Andrzej-Andrzej** [comment]
In 1.4.542 still doesn' work.

**Comment by gtritchie** [comment]
> In 1.4.542 still doesn' work.

Yes, this issue is still open.

**Comment by Andrzej-Andrzej** [comment]
Where can I get this 1.4.470 version ?

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.546, R Version - 4.0.2, Windows 10 x64 - Desktop

This issue has been fixed in the latest daily build, selecting entries in the tab overflow document switch menu now correctly pulls up that document and switches focus to it.
