### ISSUE TITLE
feature request: Citation key auto completion in RMD

### ISSUE THREAD

**Issue by fangzhou-xie** [rstudio/rstudio#7276]
Thanks for your efforts in making RStudio a great tool for everyone! 

For academic writing, I used to use Atom editor for LaTeX, but recently write RMD a lot in R Markdown. However, I found out that it is somewhat difficult to write references in RStudio. I think that it would be great to have the feature where whenever we type `@` in RMD file, RStudio will automatically suggest citation keys from a `.bib` file. And when we type further, it refines results to match what we want better. It would work similarly as [code completion](https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion), where it scans some `.bib` files, instead of the code itself.

Thanks a lot and I am looking forward to this! I think many people would potentially benefit from this feature, though I didn't find anyone asking for this.

**Comment by ronblum** [comment]
@mark-fangzhou-xie Thank you for the suggestion! We'll consider at as part of our ongoing development of RStudio.

**Comment by jmcphers** [comment]
You can do this (with an extra click or two) with the citr addin:

https://github.com/crsh/citr

Citation autocompletion will also be available in the upcoming visual editing mode, which you can try in a daily build (https://dailies.rstudio.com/):

https://rstudio.github.io/visual-markdown-editing/#/technical?id=specifying-a-bibliography

**Comment by mark-fangzhou-xie** [comment]
Thanks for the reply! I am currently using `citr` package to insert citations (with some clicks). But I think our life would be much easier if there are automatic suggestions on citations :), and I am looking forward to this feature. I'll try the daily build as well.

BTW, also a very quick question, I wonder how one could specify the bibliography path in some other folders (other than the working directory)? For example, I wish to use the `Library.bib` file at my home directory, but the following command doesn't seem to work (I know we could use command on `date` (``date: "`r format(Sys.time(), '%B %d, %Y')`"``).

```r
bibliography: "`r paste(Sys.getenv('HOME'), 'Library.bib', sep = '/')`"
```

Thank you very much!

**Comment by salim-b** [comment]
I think this issue can be closed since more specific issues around RStudio 1.4's [already mentioned](https://github.com/rstudio/rstudio/issues/7276#issuecomment-661188371) citation assistance exist:

- Provide citation key auto-completion in source mode: #7876

- Do not require square brackets around citation keys: #7976

  RStudio's @dragonstyle acknowledged that the current design is wrong (not conforming with Pandoc's citation syntax) and that it will be fixed in [this comment](https://github.com/rstudio/rstudio/issues/7976#issuecomment-705195823).
