### ISSUE TITLE
Update Terminal support article for 1.3

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7280]
The Terminal pane in RStudio 1.3 now supports custom shells for Windows (previously only available on Mac/Linux).

Should update support article to mention that, and show an example for hooking up RTools4 as a terminal per #6810.

Also a quick skim for other helpful updates since this article was written for RStudio 1.1 and terminal has had several other enhancements.

https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal

**Comment by gtritchie** [comment]
Done, have updated the article at https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal to match 1.3 features, and description of how to configure RTOOLS4 as the terminal shell.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1056, R Version - 3.6.3, Windows 10 x64 - Desktop 

The fix here was an update to documentation, not a change in code. That being said, verified the instructions added [Advanced - Use RTOOLS4 Bash on Windows](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal#rtools) are accurate and understandable for even an intro level user, and was able to add a custom rtools4 terminal on Windows desktop.
