### ISSUE TITLE
Copy script path from tabs 

### ISSUE THREAD

**Issue by abfleishman** [rstudio/rstudio#7289]
Many IDEs allow you to copy the name of a script or the full path of a script by right-clicking on the tab (open script name) and selecting 'copy...' from a dropdown menu.  It would be very useful to have something similar, as I am often wanting to send paths to a file to colleagues.

**Comment by gtritchie** [comment]
See also: #1664

**Comment by gtritchie** [comment]
Fixed in v1.4-juliet-rose via #8737

**Comment by astayleraz** [comment]
Verified this in Version 1.4.1507-1 and R 3.6.0 in both server and pc/mac desktop versions. I checked chrome, safari, and firefox.
