### ISSUE TITLE
addin to test package in a package-agnostic way

### ISSUE THREAD

**Issue by pbreheny** [rstudio/rstudio#7290]
Simple request here -- the Ctrl + Shift + T shortcut to test a package is very useful, but only works for packages that use `testthat`. 
 An addin that simply ran the R code in the `tests` folder would be great to have as an additional option, as it would work with `testthat`, any other testing package, or packages that just use native R tools for testing.

If this already exists, then sorry!  I couldn't figure out any way to accomplish this other than to write an R package that provided this addin, which seems like a lot more work than it should be.

**Comment by kevinushey** [comment]
If you have `[ ] Use devtools package functions when available` unchecked, then this should do what you describe:

<img width="558" alt="Screen Shot 2020-07-07 at 9 38 14 AM" src="https://user-images.githubusercontent.com/1976582/86813927-9727f780-c035-11ea-9832-c71aa6e41b2c.png">

**Comment by kevinushey** [comment]
Perhaps we could change the behavior here to only use `devtools::test()` if we detect a `testthat` folder within the `tests` folder?

**Comment by pbreheny** [comment]
Oh, of course -- yes, that works perfectly.  Sorry, my mistake -- I wasn't connecting that box with testing, I thought it was referring to `load_all()`, `check()`, etc.
