### ISSUE TITLE
Function view tab triggered by browser() shows tabulator character

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#7291]
#5643 # System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      :  Mac Os 10.15.5
    R Version       : 4.0.0

### Steps to reproduce the problem

Just create a random function *in a script .R file*, doesn't trigger if the function is defined in the console.
The function needs to have a call to `browser()` inside, eg:

```
foo <- function() {
	browser()
	if (5 == 5) {
		bar <- 6
		}
}
```

then source the file and simply call the function.

### Describe the problem in detail

As expected a new tab opens in RStudio, but the tabulator character is visibile:

```
function() {
\tbrowser()
\tif (5 == 5) {
\t\tbar <- 6
\t\t}
}
```

### Describe the behavior you expected

The tabs should be properly formatted

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Does this also repro for you in later releases of R? (R 4.0.0 had a deparsing bug that affected the RStudio debugger.)

**Comment by bakaburg1** [comment]
Ok, I updated. I cannot say if the bug it's solved, because now the extra tab doesn't get open at all! (I think better this way, those tabs were annoying). So things changed for the better but I have no idea about the underlying bug. Let's see if it occurs again on other occasions.
