### ISSUE TITLE
Tabbing between "find" and "replace" boxes

### ISSUE THREAD

**Issue by burchill** [rstudio/rstudio#7295]
In RStudio, pressing Ctrl+F when editing a file will open up a pane for finding and replacing, and put the text cursor in the "find" textbox.  In previous versions of RStudio, you used to be able to press the Tab key to move directly from the find textbox to the "replace" textbox, which was incredibly helpful for a quick find-and-replace.  Now, pressing the Tab button moves the selection to the "Next" button, then the "Prev" button, then the "All" button, and _then_ the replace textbox.

It would be great if this could be brought back, or you could set up a key binding to select the "replace" textbox.

**Comment by gtritchie** [comment]
Adding a screenshot for context:

<img width="528" alt="screenshot of find replace bar" src="https://user-images.githubusercontent.com/10569626/86848449-e46e8e00-c062-11ea-9631-2e31af79c579.png">

Another fix would be to rearrange these controls so replace box is right after find box; it is an accessibility requirement that focus goes in the same order the controls are visually arranged.

**Comment by burchill** [comment]
Yes, I thought that might be the case, changing the order would be good as well

**Comment by config-i1** [comment]
I agree this is very annoying. Pressing "Tab" four times instead of one breaks the work flow for me. Previously, this worked perfectly, now it's a pain.

**Comment by config-i1** [comment]
Any update on this issue? v1.4.1103 still has this.
Just a though, allowing users to change the order would resolve this... :)

**Comment by gtritchie** [comment]
Quick and safe change, will include in 1.4-juliet-rose.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1540
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that by default the Find Panel controls are able to be tabbed through in the order they appear on screen. When the Command Palette option "Tab key moves focus directly from find to replace text in find panel" is checked and the focus is on the Find textbox, focus moves over to Replace box when tab is pressed. Once Replace is in focus, the controls listed after Replace on the Find Panel can be tabbed through in the order they appear on the screen.
