### ISSUE TITLE
R data viewer showing Latin characters instead of English

### ISSUE THREAD

**Issue by ShurliAgati** [rstudio/rstudio#7296]
Hi,
I am a newbie, loading data (_data(iris)_) into R. Everything is fine but when I do _View(iris)_, the Species names are shown in a different language. Wondering if there's a bug or something? Please see an example below.

![image](https://user-images.githubusercontent.com/67993529/86878386-5a363080-c11b-11ea-8e66-6605c19f5366.png)

**Comment by jmcphers** [comment]
Sorry, we'd need a lot more information to help! Please fill out the bug template completely or post as a question on our community forum.

**Comment by ShurliAgati** [comment]
OK, thanks
