### ISSUE TITLE
RStudio opens with a pop-up console window with an error

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#7298]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.553
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : 4.0.2

Opening up the latest daily version, I get a window with the following error (in addition to the regular RStudio window):

   DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Arena Chess Figurine", pointsize=12, pixelsize=13, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Arena Chess Figurine", lfWidth=0, lfHeight=-13) dpi=144

Arena is a chess GUI and Arena Chess Figurine must be a font of chess pieces I must have had installed at some point but it is not currently listed in Windows font list. In any case this was not present for any of the previous RStudio versions I've had installed and Arena must have been uninstalled eons ago. I tried reinstalling Arena in hopes it would fix it but it didn't. Closing the error window also closes RStudio.

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@martj42 Thank you for raising the issue! We'll review it during our continuing development.

**Comment by martj42** [comment]
This is fixed as of the latest dailies.

**Comment by ronblum** [comment]
@martj42 Thank you!
