### ISSUE TITLE
Clicking on the filtering boxes in data viewer will sort the data

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#7299]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.553
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : 4.0.2

When I open up a data frame with `View`, for example `View(mtcars)`, then click on the Filter button and on any of the filtering boxes that say All will sort the data by that column. However, I do not want to sort by that column, I want to just filter by that column. To sort, I can click anywhere else on that column's box. This is especially annoying when dealing with large data sets.

I think this is relatively new behaviour and wasn't present in at least 1.2.

Here's an image of what I'm talking about:

![](https://i.imgur.com/PglX7oK.png)

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@martj42 Thank you for filing the issue! I can reproduce this in both 1.2.5040 and 1.3.9559, when click within the box just to the right of "All". We'll review this as we continue development of RStudio.

**Comment by martj42** [comment]
Just a bit of feedback - this isn't exactly perfect yet. It will still sort if there is already text in the box and it's clicked or if the blinking text cursor is already in the box and it is clicked in again.

**Comment by R-Hannibal** [comment]
@martj42, thanks again for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by martj42** [comment]
Yep, seems fine to me in 1.4.747. 🙏
