### ISSUE TITLE
Mac terminal pane copy-paste error (prefix "00~" and suffix "01~" added)

### ISSUE THREAD

**Issue by ravichandrasekaran** [rstudio/rstudio#7303]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Mac 10.15.5 (Catalina)
    R Version       : 4.0.0

### Steps to reproduce the problem
1.  Go to Terminal pane
2.  Have open code pane with content, or run a command in terminal pane to get some output (e.g. ls) 
3.  Copy some text from terminal or code pane (using either menu or keyboard shortcut). 
4.  Paste in Terminal window (using either menu or keyboard shortcut).

(It's hard to know for sure, but I don't think I encountered this problem before I also saw the font differences in RStudio 1.3 https://github.com/rstudio/rstudio/issues/6382)

### Describe the problem in detail
The output from the Paste command will be prefixed by "00~" and suffixed by "01~".
For example, for a directory called "coursework" that I copy-pasted, the result looked like:

```
00~coursework01~
```

![Mac-RStudio-copy-paste-error](https://user-images.githubusercontent.com/1671691/86960892-17715a00-c115-11ea-97a5-a6c10bc0adcf.png)

### Describe the behavior you expected
Expected copy-paste without additional text

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I have not been able to reproduce this with the same configuration. Can you share your Terminal settings (e.g. Tool / Global Options / Terminal), both what's under General Tab and the Closing Tab?

**Comment by gtritchie** [comment]
Try turning off:

Tools / Global Options / Terminal / Closing: **Save and Restore Environment Variables**

Then close all existing terminals (Terminal pane dropdown / Close All Terminals) and open a new one, and repeat your copy/paste test.

**Comment by ravichandrasekaran** [comment]
Thanks. Unchecking that save and restore option did the trick!

**Comment by gtritchie** [comment]
Do you recall if you were seeing this issue with RStudio 1.2?

It would be greatly appreciated if you could try downloading and running 1.2.1054 just to check (don't have to install it, just run it from the opened DMG). https://download1.rstudio.org/desktop/macos/RStudio-1.2.5042.dmg

Good for us to know if this is a regression in RStudio 1.3 (perhaps due to fix made for #2267), or something about your shell config that is hitting this.

Thanks!

**Comment by ravichandrasekaran** [comment]
Didn't see it previously with RStudio 1.2. 

Just downloaded the 1.2.5042 image and tried it. Copy-paste worked fine on same test, and the checkbox for "Save and Restore Environment Variables" is still checked. Maybe regression?

Hope that helps, and thanks again?
