### ISSUE TITLE
Viewer: Data order and filters are still applied when moving to next "page" of 50 columns

### ISSUE THREAD

**Issue by markbneal** [rstudio/rstudio#7306]
In the viewer, when you have a dataframe wider than ~50 columns, it separates into multiple pages. However, when you filter or sort on the first page, that ordering or filtering is lost when you go to the second page.

**Comment by ronblum** [comment]
@markbneal Thank you for raising the issue! We'll review it as we continue development of RStudio.

**Comment by ronblum** [comment]
Duplicate with #7534.
