### ISSUE TITLE
Viewer search box should search column names (as well column contents) 

### ISSUE THREAD

**Issue by markbneal** [rstudio/rstudio#7307]
Viewer search box is great for quickly searching column contents, but it is not intuitive that it doesn't search column headers as well. Could it search the column headers too?

**Comment by ronblum** [comment]
@markbneal Thank you for the suggestion. We'll review it as we continue development of RStudio. Just to make sure I understand correctly, you'd like to search the column names themselves? Say, if there were 100 columns and two were called `tempo` and `temperature`, a search for `temp` would return just these columns?

**Comment by markbneal** [comment]
Maybe a better implementation is not to visually **select** those columns from the dataframe, but to take you to the first column where "temp" appears in the name?
