### ISSUE TITLE
Reorder scripts in the dropdown menu of the script window

### ISSUE THREAD

**Issue by markbneal** [rstudio/rstudio#7308]
In the scripting window, when you have numerous scripts, you can access them via a button (>>) that creates a drop-down list. I would enjoy being able to reorder scripts in that drop-down list.

**Comment by ronblum** [comment]
@markbneal Thank you for the suggestion! We'll review this as we continue development of RStudio. In the meantime, the order should reflect the order of the tabs in the source pane, so you can adjust them that way.

**Comment by markbneal** [comment]
Good to have it on the list. I'm guessing I'm not the only one that has a project with a lot of scripts that you want to quickly flick between, eg something like this:
![crowded_list](https://user-images.githubusercontent.com/33592517/87493631-4f424980-c6a1-11ea-957a-7e212ea6f2f5.png)
