### ISSUE TITLE
AGG backend fails in Rmarkdown when rendering inline

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#7313]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.558
    OS Version      : MacOS 10.15.5
    R Version       : 4.0.0

### Steps to reproduce the problem

1) Set the graphics backend to RAGG in Options > General > Graphics; leave antialiasing at default.
2) Place the following into a *.Rmd:

~~~
---
title: "ragg test"
output: html_document
---

```{r}
plot(pressure)
```
~~~

3) run chunk using button `Cmd`+`Shift`+`Enter`

### Describe the problem in detail

I see:
```
Error in match.arg(type) : 'arg' should be one of “cairo”, “cairo-png”, “Xlib”, “quartz”
```

### Describe the behavior you expected

An inline plot, fast...

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
@petrbouchal, thanks so much for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by petrbouchal** [comment]
Many thanks - now works as expected on RStudio 1.4.727 on MacOS 10.15.5 (which is excellent news)
