### ISSUE TITLE
Bold text in terminal using Git for Windows 2.27.0 and RStudio Terminal

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7325]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033, 1.3.1054
    OS Version      : Windows-10 v2004
    R Version       : 4.0.2, RTools40, Documents\.Renviron contains PATH="${RTOOLS40_HOME}\usr\bin;${PATH}" per RTools40 install instructions

### Steps to reproduce the problem
- Have Git for Windows 2.26.2 installed (64-bit, all defaults accepted in setup program)
- Run Visual Studio Code; it says:
> There are known issues with the installed Git 2.26.2.windows.1
> Please update to Git >= 2.27 for the git features to work correctly.

![screenshot of vscode git update message](https://user-images.githubusercontent.com/10569626/87231644-bd1f0600-c36d-11ea-8f16-8887596ae433.png)

- Follow the link and install Git 2.27.0
- Now run RStudio and open a git-bash terminal

### Describe the problem in detail
- Text in terminal is very "bold" after upgrading to 2.27.0 (screenshots below)
- I initially encountered significant instability (terminals hanging, failing to start) but could not reproduce this after I had uninstalled and reinstalled Git; perhaps ssh-agent.exe was still running from the older version and causing problems but that's just a vague theory

Terminal with Git 2.26.2:
![screenshot of terminal with Git 2.26.2](https://user-images.githubusercontent.com/10569626/87231719-6665fc00-c36e-11ea-83e4-9c9abc6d0254.png)

Terminal with Git 2.27.0:
![screenshot of terminal with Git 2.27.0](https://user-images.githubusercontent.com/10569626/87231725-6f56cd80-c36e-11ea-8017-25e55c76946d.png)

### Describe the behavior you expected

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Surely we can close this?  It sounds like it's a very specific circumstance, using an old git version

**Comment by gtritchie** [comment]
Yes closing is fine.
