### ISSUE TITLE
[feature request] Cutting Text A then copying Text B before pasting Text A deletes Text A

### ISSUE THREAD

**Issue by N-Accumbens** [rstudio/rstudio#7329]
I imagine it's actually something inherent to all text-editors, but it'd be nice for there to be an option to put the cut text back to where it was if I haven't pasted the text yet before mistakenly copying some other text. 

So something like how Windows Explorer grays out files that are about to be pasted after you cut them.

**Comment by ronblum** [comment]
@N-Accumbens Thank you for raising this. Isn't this accomplished by <kbd>ctrl-z</kbd> (or <kbd>cmd-z</kbd> on Mac), though?

**Comment by N-Accumbens** [comment]
It's true, it would be accomplished by `ctrl-z`, but that's only if you remember about it. 

And the thing is, it could also be the case that when you copy something before pasting the cut-clipboard, that you've already forgotten that you were going to paste the cut-clipboard. So I was hoping for some kind of fail safe.

**Comment by ronblum** [comment]
@N-Accumbens Thanks! We'll review this during our ongoing work on RStudio.
