### ISSUE TITLE
Platform-aware option to edit document templates within IDE

### ISSUE THREAD

**Issue by jmgirard** [rstudio/rstudio#7330]
The default document templates for new files (e.g,. `/resources/templates/r_markdown_notebook.Rmd` for R Notebooks) are pretty helpful for new users. But after a while, it is more convenient to replace these with a custom template that contains code to load your typical packages, set your typical chunk/markdown options, etc. From [this link](https://stackoverflow.com/questions/41333954/change-rstudio-default-r-notebook-to-blank), I learned how to make this change in my file system. However, in trying to teach this trick to other people, it is a pain because the location of these files differs between platforms and sometimes (e.g., on Windows) you need special permissions to make these modifications through the file system. It would be very handy to have some way to view, open, and edit these templates within the RStudio IDE itself. I think a lot of users would enjoy this ability to easily customize templates.

I defer to the devs on where this option should live, but I could see it living in the Tools menu, either as its own "Templates" option or as part of the "Global Options..." window.

**Comment by jmcphers** [comment]
As of RStudio 1.3, it is no longer necessary to have special permissions to edit default document templates. RStudio 1.3 will check a special folder in your home directory and use a template there if it finds one.

https://docs.rstudio.com/ide/desktop-pro/settings.html#other-settings

https://docs.rstudio.com/ide/server-pro/r-sessions.html#default-document-templates

However it is true that some research is required to figure out where to place these files. We will leave this open as a feature request to add a command to edit them from the IDE itself.

**Comment by jmgirard** [comment]
Oh, interesting. I got the permission problem but it was on 1.2.x. Thanks!
