### ISSUE TITLE
Rstudio 1.3.959 dark theme not rendered correctly on Win 10

### ISSUE THREAD

**Issue by TingjieGuo** [rstudio/rstudio#7331]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows 10 Pro build 19041.329
    R Version       : 4.0.2

### Steps to reproduce the problem
Not applicable

### Describe the problem in detail
I recently upgraded Rstudio to the latest version. However, the dark theme is no longer rendered properly. This issue did not exist before upgrading Rstudio on the same PC & OS. See a screenshot below:

![rstudio_darktheme](https://user-images.githubusercontent.com/8663013/87281826-e9648f00-c4f3-11ea-817c-5a61cbd20fe8.png)

### Describe the behavior you expected
Dark theme is rendered correctly.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Does setting your RStudio Theme to Modern fix the issue? In Global Options -> Appearance:

![image](https://user-images.githubusercontent.com/470418/87331381-b66bcc80-c4ee-11ea-9e9c-e68c0878d7ff.png)

**Comment by TingjieGuo** [comment]
> Does setting your RStudio Theme to Modern fix the issue? In Global Options -> Appearance:
> 
> ![image](https://user-images.githubusercontent.com/470418/87331381-b66bcc80-c4ee-11ea-9e9c-e68c0878d7ff.png)

Actually I am using Modern theme. Also tried to set classic and back to Modern/Sky, neither worked. I also tried reinstalling Rstudio but the issue remains.

I'm thinking maybe something is wrong with the theme setting. Is there a such setting file like json or something?

**Comment by jmcphers** [comment]
There is; it's in AppData/Roaming/RStudio/rstudio-prefs.json.

What editor theme are you using?

**Comment by TingjieGuo** [comment]
> There is; it's in AppData/Roaming/RStudio/rstudio-prefs.json.
> 
> What editor theme are you using?

Thanks! 

rstudio-prefs.json doesn't seem to allow me to set dark theme directly? I tried deleting it and reopen the Rstudio to generate a new json but it didn't solve the problem. BTW, light theme works fine.

I'm now using tomorrow night 80s but also tested a few other dark theme for editors. All has the same issue.

Is there a place where I can modify directly how colors are rendered?

**Comment by TingjieGuo** [comment]
> There is; it's in AppData/Roaming/RStudio/rstudio-prefs.json.
> 
> What editor theme are you using?

BTW, I just downgraded back to the version 1.2.5042 and the same problem occurred. This was not the case before my recent upgrading to 1.3. I'm totally confused now...

**Comment by matteodefelice** [comment]
Also the same issue, just commented https://github.com/rstudio/rstudio/issues/4850 but I didn't see this duplicated issue.

**Comment by matteodefelice** [comment]
I can confirm the same bug on RStudio 1.4

**Comment by gwd999** [comment]
I can also confirm that as of (my) Windows 10 update February 9, 2021—KB4601319 (OS Builds 19041.804 and 19042.804) the bug reported under [#6000](https://github.com/rstudio/rstudio/issues/6000)
as well as  #4850 or #7331 has reappeared again. 
Tinkering with the language settings (order of languages in system settings) as described in #6000 this time did not help anymore.

**Comment by gwd999** [comment]
> Tinkering with the language settings (order of languages in system settings) as described in #6000 this time did not help anymore.
> 
UPDATE: modifications of the LOCALE settings brought the correct rendering of DARK themes back [for me]! 

 When setting the WINDOWS 10 Language settings to English_US dark themes are readable again. 
I did also experiment with putting these changes into ~/.Renviron or ~/.Rprofile (as menioned [here](https://community.rstudio.com/t/dark-themes-not-working-properly-with-modern-and-sky-rstudio-themes-on-my-computer/81475) and [here](https://community.rstudio.com/t/during-startup-warning-message-setting-lc-ctype-failed-on-windows/21451/2) ) BUT nothing really helped as much as changing it here 
![image](https://user-images.githubusercontent.com/306826/107950653-5151eb00-6f97-11eb-931f-7f2557bbbdf9.png)

which results in the following `Sys.getlocalale()` output: 
 
```
LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252
```

**Comment by matteodefelice** [comment]
If I delete my Renviron file and set the Windows languages setting as you did (with English (US) in the top of the list), when I launch RStudio I get an error due to locale and still, the dark theme doesn't work.

**Comment by gwd999** [comment]
> If I delete my Renviron file and set the Windows languages setting as you did (with English (US) in the top of the list), when I launch RStudio I get an error due to locale and still, the dark theme doesn't work.

@matteodefelice - how does the output of `Sys.getlocale()` look after you modified your Language settings?

**Comment by matteodefelice** [comment]
@gwd999 The locale is always the same because it was set in my Renviron file:
```
> Sys.getlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
 ```
However, launching R outside R Studio gives me:
````During startup - Warning message:
Setting LC_CTYPE= failed
> Sys.getlocale()
[1] "LC_COLLATE=English_Netherlands.65001;LC_CTYPE=C;LC_MONETARY=English_Netherlands.65001;LC_NUMERIC=C;LC_TIME=English_Netherlands.65001"
```

Thanks to you I have found the solution!!!
I had to change not just the Language but the system locale, in Language > Region under the Windows 10 settings. I have changed the "Regional format" to English (United States) and now it works! 
![image](https://user-images.githubusercontent.com/6360066/108511238-efa7be80-72bf-11eb-9d17-84666aff1214.png)

**Comment by gwd999** [comment]
I still really hope they manage to get a handle on this ... since US is not the only Region/Language out there. 
I had basically the same issues with my (""native") German/Austrian settings. Interestingly they had this under control in RStudio 1.2 and after some time in RStudio 1.3 afair as well; hope it is also only s question of regression in this case (as well)
