### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by leepface** [rstudio/rstudio#7335]
I assume this should be `properties`, not `properites`: https://github.com/rstudio/rstudio/blob/4ad7d190b10fda8abd00e0dfbd89bc8edeb7525c/src/cpp/core/include/core/r_util/RActiveSessions.hpp#L53

**Comment by jmcphers** [comment]
It should, but because this is a path on disk, just fixing the misspelling would cause us to lose all the data in the `properites` folder. We also need to add code to migrate data from `properites` to `properties`.

**Comment by leepface** [comment]
I figured it wasn't a trivial fix, which is why I didn't send a PR.

**Comment by jmcphers** [comment]
@gtritchie You'll be glad to know this is going away when we migrate the properites to the database!

**Comment by gtritchie** [comment]
Nice!
