### ISSUE TITLE
Code diagnostics incorrectly flags “too many arguments in call to 'error'” inside of tryCatch()

### ISSUE THREAD

**Issue by torockel** [rstudio/rstudio#7336]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1056
    OS Version      : Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

Save a file with following content and open it (with "Check arguments to R function calls" enabled):

```{r}
library(log4r)
tryCatch(1 + 1,
         error = function(cnd) {
           error(logger, cnd)
         })
```
(It does not matter, if the code is executed or not. log4r version 0.3.2 installed)
### Describe the problem in detail

The line `log4r::error(logger, cnd)` inside of `tryCatch()` is marked with "too many arguments in call to 'error'`:
![short](https://user-images.githubusercontent.com/60826877/87325991-73334d00-c532-11ea-997f-08b96a09f43f.png)
However, this is not true. 

The problem seems to occur only inside of `tryCatch()` and goes away, if `::` is used:
![long](https://user-images.githubusercontent.com/60826877/87326231-bf7e8d00-c532-11ea-8f00-4446fb0ce96a.png)

### Describe the behavior you expected

The line should not be marked.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! I suspect this occurs because the indexer sees the inline error handler `error = function(cnd) { ... }`, and assumes that's a new function definition as opposed to just a function assigned as a handler to the `tryCatch` call.

We should tweak the diagnostics system here to properly handle this case.
