### ISSUE TITLE
RStudio - can not exit full screen mode

### ISSUE THREAD

**Issue by djhurio** [rstudio/rstudio#7340]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Linux Mint 20
    R Version       : 4.0.2

### Steps to reproduce the problem

Open RStudio (`/usr/lib/rstudio/bin/rstudio`).

### Describe the problem in detail

RStudio opens in full screen mode. It is not possible to switch to window mode.

### Describe the behavior you expected

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@djhurio Thank you for raising the issue. We don't support Linux Mint 20, and I can't reproduce it using Ubuntu 20.04. However, based on that—right clicking on RStudio in the menu bar on RStudio -> More Actions -> Maximize and unchecking  it doesn't help?

**Comment by djhurio** [comment]
I had the same issue with the Mint 19. However, I do not remember this problem with older versions of RStudio. Right clicking the menu bar does nothing. I am using MATE desktop environment. Please see the full screen image attached.

![image](https://user-images.githubusercontent.com/744800/88713115-767a2b80-d123-11ea-936e-77b657c20c49.png)

**Comment by djhurio** [comment]
If I open RStudio from other user on the same machine, it opens fine. The window is not in a full-screen mode. So the problem is in my user settings.

**Comment by ronblum** [comment]
@djhurio Thanks for the update! Please let us know if you figure out the setting causing the problem—it would be helpful to others who run into the same problem.
