### ISSUE TITLE
Some options in RStudio preferences file ignored after shutting down and re-opening RStudio

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#7342]
Windows 10 Pro
RStudio v1.3.959

Related to #7320 - I edited the `rsutdio-prefs.json` file to re-arrange the tabs so that "git" would be the right-most tab. My IDE immediately reflected this change. When I close RStudio and relaunch it, git goes back to being in its old location. I had to re-edit the file and introduce any change in it to re-trigger it to be read and only then the settings are re-applied.

This does not seem to hold true for all settings.

For example, if I set `"font_size_points": 8` and also set git to be at the right, then when I re-launch RStudio the font size setting is loaded correctly but the git tab location is not.

**Comment by kevinushey** [comment]
If you open the JavaScript console, do you see anything logged re: the pane configuration? (sometimes RStudio infers that the pane configuration is invalid, either correctly or incorrectly, and then resets to the default pane layout)

**Comment by daattali** [comment]
I see the below errors. I don't know if I had them in previous installations or not.

![image](https://user-images.githubusercontent.com/952340/87455080-e2f91480-c5d2-11ea-850d-9c17bca143b8.png)

**Comment by kevinushey** [comment]
Those are unrelated.

I can reproduce the issue if I try to put the VCS tab at the end, though:

<img width="329" alt="Screen Shot 2020-07-14 at 10 41 00 AM" src="https://user-images.githubusercontent.com/1976582/87458223-83910980-c5be-11ea-8056-23bc35ff65d2.png">

and IIRC this is intentional as the Presentation tab always needs to come last (for technical reasons).

**Comment by daattali** [comment]
Yes you're right - putting git just before presentation does seem to stick. I just happened to land on an edge case "feature not bug" :) If there are more such edge cases of things you cannot do with the prefs file, it might be worthwhile to have that list available. I'll close this issue as it's not a bug.

**Comment by jmcphers** [comment]
The prefs file is designed to be something you can sync between machines, read and understand, and check into source control. But cracking open a text editor and using it to make your own changes does not have guaranteed results as sometimes there are constraints on the values that can't be expressed in the JSON schema.

**Comment by daattali** [comment]
That's fair, I totally get that.

The [blog post](https://blog.rstudio.com/2020/02/18/rstudio-1-3-preview-configuration/) highlighting this feature does mention the file can be edited by hand and doesn't give any hints that doing so will sometimes cause seemingly acceptable values to fail. Not sure if the specific examples should be documented, but it should at least be mentioned that when editing by hand some things will not work even if they don't seem like errors to the user.
