### ISSUE TITLE
Viewer pane not working 

### ISSUE THREAD

**Issue by mrinal000** [rstudio/rstudio#7346]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.3.1056
    OS Version      : Windows 10 - Build: 18362.900
    R Version       : 4.0.0 (2020-04-24)

### Steps to reproduce the problem
```
library(Gmisc)
library(htmlTable)
x = rep(2:4, 10)
y = rep(1:2, 15)
z<-getDescriptionStatsBy(x,y, statistics = T, add_total_col = T, show_all_values = T)
htmlTable(z)
```
### Describe the problem in detail
The viewer pane is throwing the below error when tring to view htmlTable output.
`/session/file2a8c111c4c49.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A36464 not found`

### Describe the behavior you expected
It should result in a well formatted table that can be also viewed in an external browser through "Show in new window" button.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4919407/diagnostics-report.txt)
![SS](https://user-images.githubusercontent.com/62350753/87439544-89aed680-c60e-11ea-8ab9-5c3fdc37f257.PNG)

**Comment by jmcphers** [comment]
There are a number of problems know with R 4.0.0 and the Viewer pane. Does upgrading to R 4.0.1+ fix the problem?

**Comment by ronblum** [comment]
Note: I can't reproduce the issue with R 4.0.0 and 4.0.2.

**Comment by mrinal000** [comment]
> 
> 
> There are a number of known problems with R 4.0.0 and the Viewer pane. Does upgrading to R 4.0.1+ fix the problem?

After upgrading to R 4.0.2, the viewer pane is working as intended and I was unable to reproduce the above issue!

Thanks,
Mrinal

**Comment by jmcphers** [comment]
Glad to hear it, thanks for following up!
