### ISSUE TITLE
safer and generalized autocompletion after `$`

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#7354]
As I understand, autocompletion after `$` is triggered whenever we have a `foo$bar$baz$...` chain without function calls, so that `foo$bar()$` won't trigger autocompletion.

I believe this comes from the assumption that :

* `foo$bar` is cheap and safe (quick to run and no side effect)
* `foo$bar()` might not be cheap and safe

The former is generally true, but it might be wrong if `foo$bar` is an active binding or if `$` as applied to foo has been redefined. Active bindings are not so frequent in general but R6 encourages their use:

![autocomplete](https://user-images.githubusercontent.com/18351714/87519141-7ab53c00-c681-11ea-8d23-94ef84a02781.gif)

Additionally If I inserted `message()` or `warning()` calls in the definition of `$bar()` they wouldn't be displayed, but the output of `print()` would.

This issue is rare (to be fair I didn't encounter it as a bug in my use), but if it happens it would be hell to debug, and side effects could possibly include writing or removing files etc... 

I believe the output of print/cat should be removed too, and I think an option to opt out of autocomplete should be provided, at least for packaged code. 

Inversely, when a function is cheap and safe, we might want to benefit from autocompletion, such as in `head(iris)$` for example. The default behavior also makes for instance R6 method chaining less convenient than it could be as `my_R6_object$my_method1(arg)$` won't trigger autocompletion even if `$my_method1()` is cheap and safe, nor will `my_R6_object$my_method1(arg)$my_method2(`. In that case it would be convenient to be able to opt in for autocompletion. 

I believe opting in and out could be done either by setting attributes to the function (easy to do interactively), or by setting options (more discrete and cleaner I think, easier also to include base functions), in the latter case package developers might call an appropriate rstudioapi helper in `.onLoad()`, or packages such as {roxygen2} and {usethis} could make it more convenient.

**Comment by kevinushey** [comment]
Thanks for the bug report! To fix this, I think we'd need a "safe" evaluator for the completion system -- ultimately, the RStudio completion engine will try to evaluate `foo1$bar` to figure out what members are available on that object for the `$` operator, and so doing this would require us to first check whether `bar` is an active binding associated with `foo1`.

Similar arguments could then be made for function calls -- if the function declares itself "safe for evaluation", we could follow from that.

(Right now, I think ultimately all we do is screen out any "calls" that appear to use `(`.)

**Comment by moodymudskipper** [comment]
I was thinking about this a bit more.

A simpler way would be to trigger autocomplete with tab or shift + tab, so user would be responsible to evaluate or not the call preceding $. 

A really fancy way would be to have our function support an associated sister function that computes the names only, as sometimes we might have an expensive function with easily determined names, so no need to run a complex call to know what to complete.

**Comment by kevinushey** [comment]
> A simpler way would be to trigger autocomplete with tab or shift + tab, so user would be responsible to evaluate or not the call preceding $.

FWIW, this can be configured in the Global Options dialog (Tools -> Global Options... -> Code -> Completion):

<img width="600" alt="Screen Shot 2020-07-16 at 12 26 46 PM" src="https://user-images.githubusercontent.com/1976582/87713785-9ee74a80-c75f-11ea-9225-7266e9389762.png">
