### ISSUE TITLE
Rstudio sometimes not recognizing code chunks in Rmarkdown document

### ISSUE THREAD

**Issue by dmkaplan2000** [rstudio/rstudio#7355]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      :  Ubuntu 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem

I have created a knitr extension, knitrdata, that provides a "data" language engine for including data in Rmarkdown documents. Normally, when I create a data chunk, Rstudio recognizes that the chunk can be run manually by providing a green triangle at the upper right of the chunk that executes the chunk when clicked. But sometimes, particularly when I create a large Rmarkdown document (~1.5 MB), the green triangle disappears (on data chunks) and there is nothing I can do to get it back. I have tried to, after the fact, reduce the file size or replace essentially the entire document with simpler contents that work in other documents, but still the button is absent. The only thing that seems to get it back is opening the document in a clean, new Rstudio project, but this only works with smaller documents, not the original document that "lost" the green button.

### Describe the problem in detail

The green button is missing. Below I include a screenshot of a Rstudio session that has a Rmarkdown document open with the beginning of a data chunk and you can see that the execute chunk button is missing.

![Screenshot from 2020-07-15 16-20-19](https://user-images.githubusercontent.com/584741/87558976-fe8b1a80-c6b9-11ea-9ae7-15b1e6df1de6.png)

### Describe the behavior you expected

Rstudio should show the green triangle (execute chunk) to facilitate manual execution of the chunk.

- [ X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dmkaplan2000 Thank you for raising the issue! I'm marking it for review as we continue development of RStudio.

**Comment by allmedia-nz** [comment]
You know you haven't fixed this, dont you.

**Comment by ronblum** [comment]
@allmedia-nz Is the problem occurring the same conditions above, with `knitrdata` and very large files, or under other conditions?
