### ISSUE TITLE
RStudio data viewer showing Greek characters instead of English

### ISSUE THREAD

**Issue by ShurliAgati** [rstudio/rstudio#7358]
Hi,
I am having an issue with the dataviewer font in RStudio. It's just stuck and only shows Greek letters. I am trying to get it sorted but no luck so far. 

**### Steps to reproduce the problem**
> `data(iris)`
> `View(iris)`
> `head(iris)`

![image](https://user-images.githubusercontent.com/67993529/87641307-7ae53280-c77a-11ea-8f18-7587d62faf42.png)

When the same steps were followed in RGui, the result was as I would expect.

![image](https://user-images.githubusercontent.com/67993529/87641968-70776880-c77b-11ea-8e58-1c56cf029d63.png)

**### System details**
> `Sys.getlocale()`
[1] "LC_COLLATE=English_Australia.1252;LC_CTYPE=English_Australia.1252;LC_MONETARY=English_Australia.1252;LC_NUMERIC=C;LC_TIME=English_Australia.1252"
> 
    RStudio Edition  :  
    RStudio Version : Version 1.3.959
    R Version       : 4.0.1 (2020-06-06)
    OS Version         :  Windows 10 x64 (build 18362)
    Platform            :  x86_64-w64-mingw32/x64 (64-bit)

**Please see the following two posts for details:**
1. [RStudio font-family stuck on Deja Vu Sans](https://stackoverflow.com/questions/61765442/rstudio-font-family-stuck-on-deja-vu-sans)
2. [RStudio data viewer showing Greek characters instead of English](https://stackoverflow.com/questions/62791304/rstudio-data-viewer-showing-greek-characters-instead-of-english)

Will appreciate your help!
Cheers,
Shurli

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ShurliAgati Thank you for filing the issue, including the links to the external discussions! I can't reproduce the issue, including by changing to Australian locale. Is it safe to assume that the locale was never set to Greek in the past?

**Comment by ShurliAgati** [comment]
@ronblum Hi, yes I can confirm that the locale was never set to Greek - it was never played with  actually. Thanks for looking into this.
