### ISSUE TITLE
Sign-in page error with IE11 (Error: TypeError: Unable to get property 'split' of undefined or null reference)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7359]
### System details

    RStudio Edition : Server (dev server in my case)
    RStudio Version : master at commit mentioned below, also v1.3 branch
    OS Version      : macOS dev server
    R Version       : 3.6.3

Seen by customer on RStudio Pro Water Lily release: https://rstudioide.zendesk.com/agent/tickets/50361

### Steps to reproduce the problem
- build master (I'm doing a debug build on Mac) as of July 16, 2020 at 4:13 UTC, e13957b7054047e0899b910696b5795092b430bd
- `ant devmode -Dbind.address=0.0.0.0`
- load from Windows computer using IE 11
- try to sign in

### Describe the problem in detail
- sign-in page shows error saying "Error: TypeError: Unable to get properly 'split' of undefined or null reference"

![screenshot of sign-in page showing error messsage](https://user-images.githubusercontent.com/10569626/87696181-502cb700-c745-11ea-9b01-b322a01b8eca.png)

### Describe the behavior you expected
- no error message

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
🔥  IE11 strikes again 🔥

**Comment by gtritchie** [comment]
Confirmed this also repro's with same setup using v1.3-giant-goldenrod code (i.e. v1.3 branch).

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1073-1, R Version - 4.0.2, Windows 10 x64 - RedHat 8 Server, IE11 browser 

Tested login to an RSP instance through an IE11 browser, logging in and out/closing and opening sessions/etc. All logins successful, unable to reproduce the the reported error.
