### ISSUE TITLE
EPIC: Python Support

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7362]
- Add Python variables to Environment pane
- Add Python environment selection tools to Global Options

**Comment by mikebessuille** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Run Selected Line runs entire chunk #6256](https://github.com/rstudio/rstudio/issues/6256)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/11794962) | v1.4 | kevinushey | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [renv: implement options dialog #5404](https://github.com/rstudio/rstudio/issues/5404)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/11795390) | v1.5 | kevinushey | backlog | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by slopp** [comment]
> Add Python environment selection tools to Global Options

Are we also considering a way to make the Python option a Project Option? Or is that encompassed in #5404 ?

**Comment by kevinushey** [comment]
Yes, it will be possible to configure the version of Python used both per-project and globally.
