### ISSUE TITLE
EPIC: Visual markdown editor 

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7363]

**Comment by rstudio-codetree** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [improvements to rstudioapi for visual mode #7465](https://github.com/rstudio/rstudio/issues/7465)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/11981359) | v1.4 | kevinushey | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [support highlight of references in source mode #7309](https://github.com/rstudio/rstudio/issues/7309)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/11843703) | v1.4 | adamconroy | backlog | Open


###### do-not-edit-end-codetree-epic-issues
