### ISSUE TITLE
Provide UI for selecting default Python interpreter

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7365]
We should provide some UI within the Global Options and Project Options pane that will allow users to select the default Python interpreter to be used by `reticulate`.

Some concerns:

1. How should we resolve "conflicts" between the default version set through this UI, versus versions of Python requested via `reticulate::use_python()`?

2. Do we want to provide UI for creating Python environments (virtualenvs, condaenvs) as well?

3. Do we want UI affordances for cases where we cannot discover a compatible version of Python on the user's system? (We could use `reticulate::install_miniconda()`, for example, in this case.)

**Comment by kevinushey** [comment]
Main brunt of this work was implemented in https://github.com/rstudio/rstudio/pull/7497. Will file separate issues for other parts of this feature.

**Comment by melissa-barca** [comment]
Verified in 1.4.1013
