### ISSUE TITLE
Error running plot command on RStudio Server

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#7371]
### System details

    RStudio Edition : Server OS and Pro
    RStudio Version : Version 1.4.607

    OS Version      : openSUSE 15
    R Version       : 3.6

### Steps to reproduce the problem
1. run a plot command in console
ex. 
> x=1
> y=1
> plot(x,y)

### Describe the problem in detail
Error in RStudioGD() : 
  Shadow graphics device error: r error 4 (R code execution error)

logs:
17 Jul 2020 16:11:49 [rserver-monitor] ERROR 17 Jul 2020 16:11:49 [rsession-rich] ERROR r error 4 (R code execution error) [errormsg: Error in grDevices:::png("/tmp/Rtmpnc7ULN/2117a44c30f04a9b919989ec4936fef1.png",  : 
  X11 is not available
]; OCCURRED AT rstudio::core::Error rstudio::r::exec::evaluateString(const string&, SEXPREC**, rstudio::r::sexp::Protect*) src/cpp/r/RExec.cpp:327; LOGGED FROM: DevDesc* rstudio::r::session::graphics::handler::shadow::{anonymous}::shadowDevDesc(pDevDesc) src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp:217

might be related to https://github.com/rstudio/rstudio/issues/2214?

### Describe the behavior you expected
user is able to run plot command without errors

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
What is the output of `capabilities()` on that system? I wonder if R wasn't compiled with the necessary support for X11 / Cairo graphics, or if other required system libraries are missing.

How was R installed on this system?

**Comment by rich-rstudio** [comment]
capabilities()
       jpeg         png        tiff       tcltk         X11        aqua    http/ftp     sockets      libxml 
      FALSE       FALSE       FALSE       FALSE       FALSE       FALSE        TRUE        TRUE        TRUE 
       fifo      cledit       iconv         NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE       FALSE        TRUE        TRUE

**Comment by rich-rstudio** [comment]
R was installed from source

**Comment by kevinushey** [comment]
I suspect the problem here is that you compiled R without the requisite system libraries used for plot generation (e.g. Cairo) available.
