### ISSUE TITLE
Improve if/else-if block folding using tidyverse style rules

### ISSUE THREAD

**Issue by pnacht** [rstudio/rstudio#7376]
RStudio offers code-folding of if/else-if/else blocks. This is very useful.

However, basically all style guides I've seen (most importantly the tidyverse guide, which seems to be a touchstone for all others) recommend writing such blocks with the `else[ if]` on the same line as the closing brackets of the previous block:

```
if (foo) {
  do_this()
} else if (bar) {
  do_that()
} else {
  do_other()
}
```

However, this makes folding such blocks quite annoying, since it can only be done from the bottom up: if we fold the `if (foo)` block, we lose the widget to fold the `else if (bar)` block.

![image](https://user-images.githubusercontent.com/15221358/87828079-94f24400-c852-11ea-9b18-b50975b9cfe0.png)
![image](https://user-images.githubusercontent.com/15221358/87828110-a2a7c980-c852-11ea-9034-f09b206dcdca.png)

Note that we now only have the unfold widget, making it impossible to fold the `else if (bar)` block. We need to unfold everything and then start from the bottom: fold `else`, `else-if` and only then `if`.

![image](https://user-images.githubusercontent.com/15221358/87828240-e8649200-c852-11ea-83cd-db2c68be89c7.png)

I have no idea how this is implemented, but I'd hope the solution is as trivial as giving the "fold" widget higher precedence than the "unfold" widget. That is, if a line contains the start of a foldable block and an already-folded block, the "fold" widget should be given. After all, if the user wants to unfold the previous block, they can just click on the green box.

---

Also, the current folding scheme and this style don't mesh well together in that, as seen above, all the blocks get put into a single line. If this were a more complicated logic, with multiple `else if` blocks or just a few complicated conditions, the fully folded result would get very hard to visually parse and would possibly scroll off the screen.

In my personal opinion, it'd be best if these blocks were folded each into one line:

![image](https://user-images.githubusercontent.com/15221358/87828587-a2f49480-c853-11ea-84c6-42f781456862.png)

Which I only managed to do by writing the code as

```
{
  if (foo) {
    do_this()
  }
  else if (bar) {
    do_that()
  }
  else {
    do_other()
  }
}
```

But this only works inside a wrapping expression, which is why I had to add the brackets.

**Comment by kevinushey** [comment]
In C++ mode we do something a little different:

<img width="200" alt="Screen Shot 2020-07-17 at 2 14 38 PM" src="https://user-images.githubusercontent.com/1976582/87831263-e5a87380-c837-11ea-874b-0d9b7ff445fe.png">

**Comment by pnacht** [comment]
Sure, I'd be more than happy with that layout as well. Is there a way of using that in standard R mode?
