### ISSUE TITLE
Python objects appear in R Global Environment when source_python()

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#7383]
`source_python()` script with `Reticulate 1.16.9000` imports python objects to R Global Environment. 

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1058 and 1.4.614
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.2

### Describe the problem in detail
```
#test.py

import numpy as np
import pandas as pd
import datatable as dt
df = pd.DataFrame({'A': np.random.rand(5), 
                   'B': ['a', 'b', 'b', 'a', 'b']})
dt_df = dt.Frame(df)
from datatable import *
x = dt_df[:, mean(f.A), by(f.B)]
print(x)

> reticulate::source_python('~/test.py')
   | B          A
-- + --  --------
 0 | a   0.638371
 1 | b   0.323993

[2 rows x 2 columns]
```
![rstudio-py](https://user-images.githubusercontent.com/4111978/87866789-0bb14d80-c9c9-11ea-9ce3-186168c7a0f8.png)

**Comment by ronblum** [comment]
@Fred-Wu I believe this is the expected behavior, which is the behavior going back to 1.2, but I'll bump it over to the developers to review. Thanks!
