### ISSUE TITLE
Data import fails for Excel, STATA, and  SPSS

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#7384]
Hi all,

I found a serious isssue on this version

First, I can not import any file: Excel, STATA, SPSS. The notification is as below
![image](https://user-images.githubusercontent.com/63569637/87903468-3d3c1e80-ca86-11ea-97df-64614d765933.png)
Second, now Rstudio always run with 2 seperate window, but one is useless. Please see the picture
![image](https://user-images.githubusercontent.com/63569637/87903550-6ceb2680-ca86-11ea-8b30-dd369abff621.png)

I have tried to uninstall many recent version of daily Rstudio build but got the same error. When I installed the stable version, the error is no longer appear.

I am using Window 10, R version 4.0.2, Rstudio version 1.4.615

**Comment by ronblum** [comment]
@ntluong95 Thank you for raising the issue! Can you provide a sample dataset for reproducing the issue?

**Comment by ntluong95** [comment]
Dear ronblum,

It happened with all type of files

**Comment by ronblum** [comment]
@ntluong95 I tried reproducing the issue, but I can't reproduce it—I'm able to import non-text files. Can you provide a file—small, if possible—that results in this error? This will help reproduce the issue.
