### ISSUE TITLE
FR: Search/replace over files in multiple related projects

### ISSUE THREAD

**Issue by tomtom** [rstudio/rstudio#7386]
Currently, RStudio provides a "Find in Files ..." functionality. This works well when all the code is kept in a single project. Once you split up your work into several related projects/packages, this becomes cumbersome.

Could you please introduce the notion of "related projects" (like in, e.g., Eclipse) so that some features (e.g., "Find in Files", "Go To Function Definition") also include files from other projects.

**Comment by ronblum** [comment]
@tomtom Thank you for this suggestion, as well, and for Eclipse as a reference point.
