### ISSUE TITLE
bash (& stan) chunks in Rmarkdown only work (interactively) when chunk output is inline rather than to console

### ISSUE THREAD

**Issue by setgree** [rstudio/rstudio#7398]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1056 (and also 1.3.959)
    OS Version      : macOS Catalina 10.15.5 
    R Version       : 4.0.0 (2020-04-24)

### Steps to reproduce the problem
* Create a new Rmarkdown in Rstudio comprising the following:
````
---
title: "bash test"
author: "me"
date: "7/20/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
cat('hello')
```

```{python}
print('hello')
```

```{bash}
echo hello
```
````
* Attempt to execute each chunk (one at a time, with the menu option "Chunk Output in Console" selected, rather than knitting)
* the bash chunk will fail  with the following message:
```
Error: unexpected symbol in "echo hello"
```

* If you switch the editor options lines to:
```
editor_options: 
  chunk_output_type: inline
```

Then it will echo `hello`. 

### Describe the problem in detail

If executing code interactively in Rstudio, bash chunks only work if code output is set to inline rather than console. Otherwise, Rstudio interprets them as R code and therefore fails to parse the intended commands.

## Describe the behavior you expected

In general, I expect code to work identically no matter where its output is piped (I think of this as an aesthetic choice, independent of the inner workings of the project); and if there are differences, that's fine, so long as they are documented somewhere.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### related issues:
see:
[rstudio/rstudio#1880](https://github.com/rstudio/rstudio/issues/1880)
[@cderv](https://github.com/cderv) suggested I post this [here](https://github.com/rstudio/rmarkdown/issues/1868#issuecomment-661203091).

Thanks in advance for your help!

**Comment by ronblum** [comment]
@setgree Thank you for raising the issue!, and for referencing the Rmarkdown repository issue! We'll review this as we continue development of RStudio.

**Comment by vermosen** [comment]
Hi,

I believe the issue also affects the stan engine. The following notebook that has a similar problem:

````markdown
---
title: "a simple model in stan"
author: "me"
date: "11/8/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(rstan)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
```

```{stan output.var='schools'}
data {}
```
````

when I execute the stan chunk, I get the following error:
```
Error: unexpected '{' in "data {"
```
Similarly, switching to `chunk_output_type: inline` is fixing the problem.

**Comment by salim-b** [comment]
Please re-open! This is still an issue with latest stable versions of the involved software (RStudio 1.4.1717, knitr 1.34, rmarkdown 2.10, reticulate 1.20 etc.).

OP's example is a bit misleading since the code in the Python chunk (`print('hello')`) is also valid R code. This is a better test example:

````rmd
---
editor_options: 
  chunk_output_type: console
---

```{r}
cat('hello')
```

```{python}
def pyprint(x): print(x)
pyprint('hello')
```

```{bash}
echo hello
```
````

Also, for me all of the chunks work fine when I execute them chunk-by-chunk (one at a time), **but the Python and Bash chunks fail when I instruct RStudio to <kbd>Run All</kbd> (or <kbd>Run All Chunks Above</kbd> the last one, or <kbd>Run Selected Line(s)</kbd> when multiple chunks are selected).**

`rmarkdown::render()` OTOH works fine regardless of the `chunk_output_type` setting.

**Comment by setgree** [comment]
👋 this issue persists and FWIW I am not seeing how this is a duplicate of https://github.com/rstudio/rstudio/issues/11995

**Comment by ronblum** [comment]
@setgree It's not identical, but it's similar, and the same problem: non-R chunks don't work in inline mode. "Run all" is the same as running all of the chunks interactively.
