### ISSUE TITLE
RStudio won't load properly after upgrading to Catalina

### ISSUE THREAD

**Issue by jrede** [rstudio/rstudio#7400]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1056
    OS Version      : Mac OS Catalina 10.15.6
    R Version       : 4.0.2

### Steps to reproduce the problem
Simply launching RStudio

### Describe the problem in detail
RStudio opens but everything is blank. For example, I can click on files, plots, packages tabs but nothing is visible. I can write in the console but commands will not complete. Essentially a blank template of Rstudio opens that I cannot do anything with. Also, I have to force quit every time to close RStudio. These issues only happened after upgrading to Catalina. I tried uninstalling R (which works fine, just not RStudio) and RStudio and re-downloading but did not fix issue. I also tried installing R through Conda - Rstudio fails to open entirely, and I again must force quit to close out application. Please help!

### Describe the behavior you expected
To open properly.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jrede Thank you for raising the issue re the Catalina upgrade. We'll review it as we continue development of RStudio.

**Comment by jmcphers** [comment]
Unfortunately we have nothing to go on here as we have many thousands of RStudio users on Catalina who don't have this problem and no information about what might be different on your machine. :-/ This article may help:

https://support.rstudio.com/hc/en-us/articles/200488508-RStudio-Desktop-Will-Not-Start

If it doesn't, please look for help on our community forum:

https://community.rstudio.com/c/rstudio-ide

**Comment by aditi-d92** [comment]
I am having the same problem. I upgraded my mac to Catalina and RStudio has stopped working. It doesn't even open.
I uninstalled R and RStudio but only RStudio has the issue.
