### ISSUE TITLE
View / Panes / Console on Left or Right not working properly (1.4)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7405]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.618
    OS Version      : any
    R Version       : any

The same issue was logged and fixed in 1.3 (tracked by #7246). That fix was not sufficient for 1.4 due (presumably) to the work in progress on source columns, so opening this to track for 1.4.

### Steps to reproduce the problem
- startup IDE in a clean default state, with no files open in source pane (for best chance of repro, delete all previous settings including Qt-related settings if using Desktop)
- in View / Panes menu, note checkmark on "Console on Left" menu item
- select View / Panes / Console on Right

### Describe the problem in detail
- an editor document is opened (which is consistent with earlier versions) but the Console remains in lower-left corner
- View / Panes / Console on Right is now checked in the menu despite Console not being on right
- Problem persists even after quit and restart (i.e. Console in lower-left, menu says it's on right)

### Describe the behavior you expected
- Untitled editor document created
- Console panel switches places with Environment panel
- Menu checkbox matches actual visual state including after a restart

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1069
