### ISSUE TITLE
Add debug logging when not suspending a session

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#7411]
It could be useful for admins to see why long running sessions are not being suspended. To help with this, we could add some debug logs if the session has reached the configured `session-timeout-minutes` but we chose not to suspend it because of its current state.

Relevant support ticket: 50269

**Comment by kevinushey** [comment]
I suspect you've seen it, but this is the code where we check if the session can be suspended:

https://github.com/rstudio/rstudio/blob/7fbec0b01eaccab6970d2c295f73e086ba2446eb/src/cpp/session/SessionConsoleInput.cpp#L95-L103

**Comment by MariaSemple** [comment]
Ah, that is very helpful, thanks!
