### ISSUE TITLE
Update Plumber image in new project dialogue

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#7412]
The Plumber hex logo was [recently updated](https://github.com/rstudio/plumber/tree/master/logo). It would be nice to change to this image in the new project dialogue for Plumber APIs.

New Project -> Plumber API...
![image](https://user-images.githubusercontent.com/10444878/88107445-52877a80-cb64-11ea-832a-a978b53bc852.png)

cc @schloerke

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1073, R Version - 3.6.3, Windows 10 x64 - Desktop 

New Plumber image has replaced the old image in the new Plumber project dialogue, image quality looks fine.
