### ISSUE TITLE
Fixed column of DT table badly displayed when running Shiny in window, but not in browser 

### ISSUE THREAD

**Issue by etiennebacher** [rstudio/rstudio#7423]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959, also tested with 1.3.1065 (Preview)
    OS Version      : Ubuntu 18.04.4 LTS
    R Version       : 4.0.2

### Steps to reproduce the problem

Open a new session and run the following code. Make sure the Shiny app runs in a window:
```
library(shiny)
library(DT)

ui <- fluidPage(
  DT::dataTableOutput("test")
)

server <- function(input, output, session) {
  
  output$test <- DT::renderDataTable({
    datatable(
      cor(mtcars),
      extensions = c('Buttons', 'FixedColumns'), 
      options = list(
        dom = 'Bfrtip',
        buttons = c('excel', 'csv'),
        scrollX = TRUE,
        fixedColumns = TRUE
      )
    )
  }, server = FALSE)
  
}

shinyApp(ui, server)
```
Package versions: `shiny 1.5.0` and `DT 0.14`

### Describe the problem in detail

The first column (which is fixed) is not aligned with the other columns, i.e the second cell of the first column is overlapping the first and second cell of the second column. 

### Describe the behavior you expected

The first column should be well aligned with the other ones. This problem does not appear:
* if I remove `server = FALSE` from `DT::renderDataTable` (but I need this to download the full table)
* or if I add `options = list(launch.browser = TRUE)` in `shinyApp` to run the app in the browser.

***

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@etiennebacher Thank you letting us know! I can reproduce this with RStudio Server 1.3.1056 on Ubuntu 18.04 and RStudio Desktop 1.3.1058 on MacOS 10.15.6. We'll review this as we continue development of RStudio.
