### ISSUE TITLE
R notebook not generating (updating) notebook when chunk output:console

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#7424]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.959
    OS Version      : MacOS 10.15.5
    R Version       : 3.6.3

### Steps to reproduce the problem & Describe the problem in detail

When  
```editor_options: 
  chunk_output_type: console
```
it does not automatically generate (or update) html notebook file. 
The workaround was to set
```
editor_options: 
  chunk_output_type: inline
```
and save. Then it updates html file.

### Describe the behavior you expected
I'm not certain if this was intended behavior, but I expected it would update the html file as I hit the save button.

**Comment by ronblum** [comment]
@matthewgson Thank you for filing the issue! I can reproduce this in RStudio Desktop 1.3.1058 on MacOS 10.15.6 and RStudio Server  1.3.1056 on Ubuntu 18.04. We'll review this as we continue development of RStudio.

Reprex note: when changing the output type, save file first, then make the other changes to see the different behavior.

**Comment by jmcphers** [comment]
This is the intended behavior. `chunk_output_type: inline` enables notebook mode, in which your results appear beneath the chunk and are saved to the HTML file.  `chunk_output_type: console` switches to traditional R code execution, in which results are rendered to the R console, Plots tab, Viewer tab, etc.
