### ISSUE TITLE
FR : Run Chunks within the (sub)section in R notebook 

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#7425]
I thought it would be a really nice feature to add a keyboard shortcut for running chunks within the (sub)section.
It seems what's available currently is to run 'subsequent chunks', which runs all chunks below the prompt. 

To be more specific, if the prompt is located in section 1.2.3, then it runs all the subsequent code chunks within 1.2.3. If the prompt was located in section 1.2, then it runs all the code chunks within 1.2 and so forth.

**Comment by ronblum** [comment]
@matthewgson Thank you for the suggestion! We'll consider it as part of our ongoing development of RStudio.
