### ISSUE TITLE
Sync PDF view to editor location not working properly 

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#7426]
### System details
```
RStudio Edition : Desktop
RStudio Version : Version 1.3.959
OS Version      : MacOS 10.15.5
R Version       : 3.6.3
```
### Steps to reproduce the problem

I've installed tinytex on my machine (as suggested by Rstudio) and made a sample .Rnw file to check if it is working properly. It complied pdf without any hassle, but I noticed that forward / backward sync location (SyncTex) is not working well.

To be specific, when I cmd + click on the editor, it always highlight the first line of pdf, and if I do backwards it always locates prompt to the end of the editor. What is possibly causing this issue?

I'm using Version 1.3.959 Rstudio, and compiled the pdf with knitr.

![](https://community.rstudio.com/uploads/default/original/3X/0/9/0949e7bc57df23415e1feb6dde7dcc5193be0acb.png)

Below is the sample .Rnw file I used for testing.

```
\documentclass{article}

\begin{document}

dsf

sdf


asdfsdf

asdf

\end{document}

```
Please let me know if this issue should be reported somewhere else then I'll close the issue asap.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
In order for synctex to work, I believe you need to:

1. Compile your `.Rnw` using Sweave rather than `knitr`;
2. Ensure that `\SweaveOpts{concordance=TRUE}` is set.

Unfortunately, I'm not sure if concordance is supported by `knitr`.

**Comment by matthewgson** [comment]
@kevinushey Thanks, after some additional LaTeX package installation ('ae', 'grfext'), I confirm that it works with `sweave`. 

I've tried setting concordance with `knitr` by setting package option `knitr::opts_knit$set(concordance = TRUE)` but still the problem remains.
