### ISSUE TITLE
No border around additional source columns

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7435]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.630

### Steps to reproduce the problem

Add a source column (Tools -> Global Options -> Appearance).

### Describe the problem in detail

The source column (left) is missing the gray border that the other panels have (right). This makes the top of the editor tabs look cut off and causes a few other visual issues.

![image](https://user-images.githubusercontent.com/470418/88338512-4ed32f80-cced-11ea-8775-cca6a5e058b2.png)

### Describe the behavior you expected

Gray border around source columns.

**Comment by melissa-barca** [comment]
This will be fixed with #7408. The issue came from source columns being displayed directly as Source Panes rather than from within a logical window.

**Comment by jmcphers** [comment]
Nice!

**Comment by melissa-barca** [comment]
![image](https://user-images.githubusercontent.com/5323711/88339997-d6ba3900-ccef-11ea-8c14-8e8cb11c525b.png)

**Comment by melissa-barca** [comment]
Closed with #7408

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.747, R Version - 4.0.2, Windows 10 x64 - Desktop 

Wasn't able to reproduce the original issue (all available 1.4 [daily builds](https://dailies.rstudio.com/rstudio/oss/windows/) are post-fix), but borders on source pane (and additional source columns) appear normal/intact on the latest Daily.
