### ISSUE TITLE
Allow selection and removal of individual objects, rather than only the entire workspace

### ISSUE THREAD

**Issue by MavropaliasG** [rstudio/rstudio#7439]
Hi,

There is no option to remove individual objects from the UI, only clean the entire workspace.

**Comment by ronblum** [comment]
@MavropaliasG Thank you for filing this issue. Which objects are you referring to, though—for example, open files, plots, environment variables, entire panes, etc.? Also, what environment and version of RStudio are you working with?

**Comment by jmcphers** [comment]
There is! You can switch the Environment pane to Grid view, which will let you delete individual objects (plus sort by size so you can remove the biggest ones if you're looking to free memory)

![image](https://user-images.githubusercontent.com/470418/88412556-a2498a00-cd8e-11ea-8128-0432e05ef694.png)
