### ISSUE TITLE
Enable Shift+F6 to navigate counter clockwise between panes

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#7440]
PR #7408 adds the ability to navigate between panes with `F6`. Following convention we should implement `focusPreviousPane` with `Shift+F6`.

**Comment by melissa-barca** [comment]
@gtritchie "Shift + F6" is already in use by the `debugFinish` command. What do you think of changing `focusNextPane` to Cmd+Alt+F6 and `focusPreviousPane` to Cmd+Alt+Shift+F6? Unfortunately there aren't many good options left.

**Comment by gtritchie** [comment]
I’m inclined to change the existing usage of Shift+F6 given that using it for next/previous pane is essentially a defacto-standard (at least on Windows).

**Comment by melissa-barca** [comment]
Closed in #7463

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.739, R Version - 4.0.2, Windows 10 x64 - Desktop 

The `Shift + F6` command has been successfully updated to navigate to the previous pane, and finish debug has been moved to `Shift + F7`.
