### ISSUE TITLE
Implement focus for all Source Pane tab types

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#7441]
#7408 enables the `focusNextPane` command allowing users to cycle through panes via `F6` keyboard shortcut. Several tab types in the Source panel don't yet handle focus and prevent F6 from moving to that panel when they are selected.

- profile results (`ProfilerEditingTarget`)

- `UrlContentEditingTarget` (execute data() in the console)

- `DataEditingTarget` (execute View(mtcars) in console)

- `ObjectExplorerEditingTarget` (execute View(list("a" = 1.2, "b" = TRUE, "c" = 3:10)) in console)

**Comment by gtritchie** [comment]
Verified I can F6 and Shift+F6 into and out of source panes with the 4 indicated types. Used macOS Desktop build 1.4.1066.
