### ISSUE TITLE
"Find in Files" ignores files with a colon in the filename

### ISSUE THREAD

**Issue by dgkf** [rstudio/rstudio#7446]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio Pro v1.3.959-1
    OS Version      : macOS v10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Start a new project in RStudio (I created a new R Package project, though I don't think the project type is important)
2. Create two files, one with and without a colon in the filename. I used the "hello.R" file created as part of the R Package project type template, and duplicated it to a file called ":hello.R" and "hel:lo.R". 
  - Note: on macOS the "Copy To..." dialog doesn't let me enter these as file names and I had to create files with this name from the terminal. I inherited a project where I first encountered this bug from someone working on Windows, so it's possible this limitation isn't imposed on Windows machines.
3. Use the "Find in Files" dialog and search for "Hello" - this should appear in all files, but only is recognized in files without a colon in the filename. 

### Describe the problem in detail

"Find in files" does not search files with a colon in the filename. I encountered this when I inherited a project where there were files named as such and I was getting a bug pertaining to a function that never showed up when I searched within my project. This had me baffled for quite a while before I realized that not all my files were being searched through and that this code was invisible to the search due to the colon in the filename. 

I think it is bad practice to use such nonstandard characters in a filename in the first place, but they _are_ recognized in the R package build process and from the perspective of the R language, are perfectly valid. I would therefore expect them to pop up when searching through a project. 

### Describe the behavior you expected

Text within files should be found independent on filename if they fall within the file filters. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dgkf Thank you for raising the issue! I can also reproduce this in RStudio Server 1.3 on Ubuntu 20.04. We'll review this as we continue development of RStudio.
