### ISSUE TITLE
Rstudio dialogs are limited within the main Rstudio window

### ISSUE THREAD

**Issue by MavropaliasG** [rstudio/rstudio#7451]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959, installed via https://aur.archlinux.org/packages/rstudio-desktop-bin/
    OS Version      : Manjaro Linux with KDE Plasma 5.19.3
    R Version       : 4.0.2

### Steps to reproduce the problem
Open a dialog, try to move the dialog outside of the boundaries of the main Rstudio window

### Describe the problem in detail
Rstudio dialogs are limited in the main Rstudio window, you can't drag them outside, it feels that it is somehow a virtual environment. This Rstudio version is installed through here https://aur.archlinux.org/packages/rstudio-desktop-bin/

### Describe the behavior you expected
Being able to drag the dialogs outside of the main window. 

![image](https://user-images.githubusercontent.com/13523909/88477110-fbbcdf00-cf6f-11ea-840c-d96bd20a6941.png)

![image](https://user-images.githubusercontent.com/13523909/88477235-e7c5ad00-cf70-11ea-8880-d2f3bd712c8f.png)

- [ Χ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ Χ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ Χ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [Χ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MavropaliasG** [comment]
Also, I know that Rstudio is not officially supported in Arch Linux, however, from the available sources in AUR, which one would be recommended?

https://aur.archlinux.org/packages/rstudio-desktop-bin/

https://aur.archlinux.org/packages/rstudio-desktop-daily-bin/

https://aur.archlinux.org/packages/rstudio-desktop-git/

https://aur.archlinux.org/packages/rstudio-desktop/

https://aur.archlinux.org/packages/rstudio-desktop-preview-bin/

**Comment by MavropaliasG** [comment]
The same problem persists in Rstudio 1.3.1060 built from this AUR source https://aur.archlinux.org/packages/rstudio-desktop-preview-bin/

**Comment by gtritchie** [comment]
This is by design, the dialogs (with the exception of some system dialogs such as file pickers) are implemented using HTML and are part of the web page (i.e. the RStudio UI) and must be displayed within it.
