### ISSUE TITLE
Create New Project: Access Denied when HOME Environment Variable Set in Windows

### ISSUE THREAD

**Issue by ashleylester** [rstudio/rstudio#7455]
Steps to reproduce in Windows (RStudio version 1.3.1056):

(1) Set a system or user environment variable pointing to your user root directory, e.g. C:\Users\JohnSmith
(2) Create a subdirectory of this folder to contain your projects, e.g. C:\Users\JohnSmith\RProjects
(3) Open RStudio. Create a new project as a subdirectory of (2), e.g. C:\Users\JohnSmith\RProjects\MyTestProject
(4) RStudio will fail to create the project and a pop-up appears showing "Access is Denied"
(5) Instead, try creating the folder first, e.g. C:\Users\JohnSmith\RProjects\MyTestProject2
(6) Create a new project in RStudio from this existing folder of (5)
(7) RStudio again fails to create the project and a pop-up appears showing "Access is Denied"
(8) Delete the environment variable from (1) and restart the PC
(9) Re-attempt steps (2), (3), (5), (6) and RStudio creates the projects without any issues

**Comment by ronblum** [comment]
@ashleylester Thank you for filing the issue! I'm unable to reproduce this, both by setting HOME as a system or user variable. I'll mark it for review as we continue development of RStudio.

**Comment by luwidmer** [comment]
I get the same when the HOME environment variable has a trailing backslash in it, for saving files into the home directory or any subdirectory.

**Comment by kevinushey** [comment]
@luwidmer this sounds like an issue that should be resolved in the latest v1.3 release of RStudio. If not ... the simplest fix is to remove that trailing slash.

**Comment by luwidmer** [comment]
I removed the trailing slash, but with it, the issue is there in the current release version of RStudio on Windows
