### ISSUE TITLE
Unable to open a new terminal from Tools dropdown menu

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#7457]
### System details

    RStudio Edition : Server and Server Pro
    RStudio Version : 1.4.642, 1.4.640 Pro
    OS Version      : Ubuntu 18
    R Version       : 3.6

### Steps to reproduce the problem
1. Go the the tools dropdown menu -> terminal -> new terminal
### Describe the problem in detail
nothing happens, new terminal is not created

Console errors

DevTools failed to load SourceMap: Could not load content for http://18.236.84.73:8787/rstudio/focus-visible.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://18.236.84.73:8787/rstudio/xterm.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://18.236.84.73:8787/rstudio/xterm-addon-fit.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Describe the behavior you expected
a new terminal session is created

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Exception being thrown:
```
27 Jul 2020 19:15:24 [rserver] ERROR CLIENT EXCEPTION (rsession-gary): (TypeError) : Cannot read property 'normal__0_g$' of null;
rstudio-0.js@86#133638::LogicalWindow.equals
rstudio-0.js@28#358879::PaneManager.onActivateConsolePane
rstudio-0.js@29#359851::PaneManager_Binder__Impl$1.onCommand
rstudio-0.js@16#116619::CommandEvent.dispatch
rstudio-0.js@8#116609::CommandEvent.dispatch
rstudio-0.js@8#39767::GwtEvent.dispatch
rstudio-0.js@14#42744::dispatchEvent
rstudio-0.js@9#42854::SimpleEventBus.doFire
rstudio-0.js@8#42933::SimpleEventBus.fireEvent
rstudio-0.js@24#42686::HandlerManager.fireEvent
rstudio-0.js@23#114904::AppCommand.doExecute
rstudio-0.js@8#114910::AppCommand.execute
rstudio-0.js@51#565410::TerminalPane.activateTerminal
rstudio-0.js@20#569111::TerminalTabPresenter.onNewTerminal
rstudio-0.js@38#569946::TerminalTab_Shim__Impl$1.onSuccess2
rstudio-0.js@23#570013::TerminalTab_Shim__Impl$1$1.execute
rstudio-0.js@21#103955::AsyncShim.preInstantiationHook
rstudio-0.js@24#569893::TerminalTab_Shim__Impl$1.onSuccess
rstudio-0.js@27#23298::GWT$1.execute
rstudio-0.js@40#25243::executeScheduled
rstudio-0.js@9#24935::runScheduledTasks
rstudio-0.js@5#25034::SchedulerImpl.flushPostEventPumpCommands
rstudio-0.js@23#25188::SchedulerImpl$Flusher.execute
rstudio-0.js@19#24901::execute
rstudio-0.js@28#24557::apply
rstudio-0.js@16#24616::entry0
rstudio-0.js@14#24595::anonymous
rstudio-0.js@45#24955::callback_0_g$
Client-ID: 34ef8102-d683-40bb-9dcd-330fffb86ec9
User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
```

**Comment by rich-rstudio** [comment]
verified on RSP Version 1.4.750-1
