### ISSUE TITLE
R notebook does not render html properly

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#7464]
### System details

RStudio Edition : Desktop
RStudio Version : Version 1.3.959
OS Version      : MacOS 10.15.5
R Version       : 4.0.2

### Steps to reproduce the problem

I noticed that R notebook is not rendering html file properly in some cases. I made a minimal reproducible example here. 

```

---
title: "Hmm.."
output: 
  html_notebook: 
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

# R Notebook

## some heading

```{r, setup, message =F, include=F}
library('tidyverse')```


## some heading2


```{r, echo=FALSE}
print('This text is printed in wrong location')```


This text should be located below , but is printed above chunk output.


```{r}
print(iris)```



I can't see the table in the output file.

```

### Describe the problem in detail

Triple backtick  \`\`\` needs to be placed in newline for replication. 
Some text are misplaced and table is missing in the final output.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@matthewgson Thank you for raising the issue! I am able to reproduce it, and we'll review it as we continue working on RStudio.

**Comment by matthewgson** [comment]
@ronblum I wasn't entirely sure what possibly was causing the problem, but it seems like the `setup chunk` is making the error. It renders okay when `setup` was removed.

**Comment by ronblum** [comment]
I can confirm that it's the comma's fault. Here's an example with as much as possible stripped out. The output should be in alphabetical order, A through E.

````
---
title: Title
output:  html_notebook
---

```{r, setup}
print("A: Setup")
```

B: Text

```{r}
print("C: Code")
```

```{r}
print('D: Code')
```

E: Text
````

As is, the setup chunk is shown twice—once just the code, the second time code and output. The output is (A) B A C E.
<img width="651" alt="comma_yes" src="https://user-images.githubusercontent.com/31009952/88822550-0060dd80-d192-11ea-89d2-4e49290d7cd7.png">


If the comma in the setup chunk is removed, the output is in the correct order. Change 
````
```{r, setup}
````
to
````
```{r setup}
````

<img width="577" alt="comma_no" src="https://user-images.githubusercontent.com/31009952/88822236-99dbbf80-d191-11ea-9926-073178026e06.png">

**Comment by kevinushey** [comment]
Sounds like this may be a duplicated of https://github.com/rstudio/rstudio/issues/1540?

**Comment by ronblum** [comment]
@kevinushey I agree, with this showing a little  bit more about text placement.
