### ISSUE TITLE
improvements to rstudioapi for visual mode

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7465]
We need to make sure that both things behave sanely in the presence of visual mode and that we make some appropriate hooks available for add-ins that want to work well with visual mode. We should also create some documentation outlining best practices for add-ins that want to work w/ visual mode.

Here are the things that have been reported so far:

1) When highlighting an R chunk in visual mode then executing the "Style Selection" command from the [styler](https://github.com/r-lib/styler) package, the visual editor reverts to the regular editor and there is an error saying "No code selected". We should create a new API that is selection (rather than document context) oriented so that this sort of scenario can be made to work.

2) Running `bookdown::serve_book()` causes the active document to switch to visual mode. This is because `serve_book()` calls `rstudioapi::getSourceEditorContext()` to get the current document's path. Here I think we could add an API that just retrieves the path not the rest of the selection context.

3) Using `rstudioapi::navigateToFile()` doesn't seem to respect the "use visual editing by default for new documents" setting. This is because `navigateToFile()` uses the `jump_to_function` event, which in turn forces source mode.

cc @mine-cetinkaya-rundel @hadley

**Comment by kevinushey** [comment]
It would be ideal if we could find a way to allow users to use the same set of APIs for both source + visual mode. I strongly believe that we should avoid forcing addin authors to write two versions of their addins to support the different editor modes (although we should still allow this to be queried)

One potential solution would be to have a chunk-based API, where users could mutate documents on a chunk-by-chunk basis. For example:

- `chunkGetContext()`: Request the document context, separated into "chunks". Defaults to the document currently active / last-focused in the IDE.
- `chunkReplaceText()`: Replace the contents of a particular chunk; either in its entirety or at a specific position / selection. These actions could / should be undoable.
- `chunkInsertNew()`: Insert a brand new chunk, using the location of an existing chunk to adjust its position (e.g. before or after an existing chunk in the document)

These APIs could in theory also work in regular R scripts -- they would be treated as though they were just one R code chunk, without an associated header. That way, APIs using this "chunk-based" API could just work regardless of editor mode.

Sample API usage:

```
# silly example of lower-casing all R code in a chunk
context <- rstudioapi::chunkGetContext()
for (chunk in context$chunks) {
  if (chunk$type == "R") {
    code <- tolower(chunk$code)
    rstudioapi::chunkReplaceText(chunk$id, code)
  }
}
```

The 'context' returned would be compatible regardless of whether one is working on an R document, an R Markdown document in source mode, or visual mode.

One associated work item here would be to ensure we can split a source R Markdown document into chunks, but I figure `rmarkdown` / `knitr` have tools we could use here.

**Comment by jjallaire** [comment]
Once we've addressed the various motivating cases for this issue in the API, we should also add documentation on writing addins that work for both visual and source mode. If we put this on the rstudioapi website that's fine, but we might want a short section added here that references the rstudioapi docs: https://github.com/rstudio/visual-markdown-editing/blob/master/docs/additional.md

**Comment by kevinushey** [comment]
This is now complete on master. A short summary of the work done:

- We have APIs `selectionGet()` and `selectionSet()` for mutating the contents of the current selection;
- APIs `documentId()` and `documentPath()` were introduced, for getting the ID and/or path to the active document;
- `navigateToFile()` now uses `file.edit()` to navigate when no explicit cursor position is requested or specified.
- Documentation has been added, as a vignette in the `rstudioapi` package, for packages which want to build addins that play well in both visual and source mode.

I think this captures everything we needed for this issue, but I'm sure other items will pop up as addin authors kick the tires.

**Comment by kevinushey** [comment]
@lorenzwalthert brings up a good point: these APIs don't provide any mechanism for seeing the "context" around a selection, which is important in some cases (e.g. making sure the right number of line breaks are inserted).

I'm not sure what the right fix here is, beyond something more like the chunk-based API for modifying code chunks I suggested before (which will take more work).

**Comment by jjallaire** [comment]
Okay, I'll add a link to the vignette from the visual mode docs.

Let's discuss possible enhancements to deal with context realtime on Monday.

**Comment by kevinushey** [comment]
I believe we've done all the work necessary here now:

- We have a new set of APIs designed explicitly to work with both source + visual mode;
- We've done what we can to ensure that the existing APIs at least produce something sane / useful in visual mode whenever possible.

**Comment by kfeinauer** [comment]
@kevinushey It looks like `rstudioapi::documentId()` when run in the Console while a Visual Mode Rmd file is open returns "#console":
```
> rstudioapi::documentId()
[1] "#console"
> rstudioapi::documentPath()
[1] "~/testproj/TestRMD.Rmd"
```

However, the document path is correct. Should this be considered a bug? I am guessing it's because the Console has focus, but it is indeed not the active document.

**Comment by kevinushey** [comment]
@kfeinauer that's right; in this case you can use:

```
rstudioapi::documentId(allowConsole = FALSE)
```

to explicitly request the ID for the active source document even if it does not have focus.

**Comment by kfeinauer** [comment]
Thanks Kevin!

Verified on 1.4.1032
