### ISSUE TITLE
Rstudio Terminal and Plots

### ISSUE THREAD

**Issue by vivek-verma202** [rstudio/rstudio#7466]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1056
    OS Version      :  Windows 10 / Linux Centos 7.8.2003
    R Version       :  4.0.0

### Steps to reproduce the problem
plot(1,1)
### Describe the problem in detail
I was able to connect to remote HPC server using "terminal" tab and ssh -Y. However, I could not see plots for the r codes executed on remote terminal in the plot pane of Rstudio
### Describe the behavior you expected
a plot in Rstudio pane

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@vivek-verma202 Thank you for filing the issue! We'll review it as part of our ongoing RStudio development work.

**Comment by jmcphers** [comment]
It is possible to view plots created on a remote server on your local machine, but it requires a nontrivial amount of configuration. You can read about how to set this up here (not Pro specific despite article title).

https://support.rstudio.com/hc/en-us/articles/360019922654-Working-with-packages-that-require-X11-and-or-cairo-on-RStudio-Server-Pro
