### ISSUE TITLE
v1065 doesn't update in xUbuntu software / package manager (gnome-software)

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#7475]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1054
    OS Version      : xubuntu 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem
I've loved how the RStudio Preview deb packages allow update-in-place in (x)ubuntu package manager. Oddly this has broken in 1065 for me, but I don't know if this is because something changed at your end, or mine? Instead of saying upgrade, package manager thinks it's already v1065 so only gives the option to remove.
![rstudio1065update](https://user-images.githubusercontent.com/4599748/88831687-8bd37200-d184-11ea-99b4-577126e1f5a8.png)

The same is true for 1070. Ideally I won't have to uninstall RStudio, lose all my settings and project setups, and then reinstall.
This may be due to a change in gnome-software rather than RStudio but I figured I'd ask here first.
Thanks

- [X ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@SimonDedman Thank you for raising the issue! We'll review it as we continue development of RStudio.

**Comment by SimonDedman** [comment]
Cheers Rob. Keen to see if anyone can reproduce this - could very well be a bug in gnome-software instead.

**Comment by SimonDedman** [comment]
[cross-posted to gnome-software bugzilla](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1039); I'll update this if there's any intel from there. Cheers.

**Comment by SimonDedman** [comment]
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1039#note_884709

Turns out this was a deliberate change by gnome-software, that unfortunately makes the process a tiny bit worse. Nothing to do on RStudio team's end; closing. Cheers!

**Comment by ronblum** [comment]
@SimonDedman Thank you for following up!
