### ISSUE TITLE
Refresh viewer without reloading all the screens

### ISSUE THREAD

**Issue by N-Accumbens** [rstudio/rstudio#7478]
Let's say there's a dataframe open in the viewer using `View(df)`. Then the dataframe is deleted and overwritten with some other data while still using the same name. It seems like RStudio keeps on displaying the old dataframe, no problem.

What I was hoping was an option to refresh that viewer without clicking reload, since that also reloads all the viewers that are in a "new window" and is annoying in a multi-monitor set-up. It'd also be helpful to not have to exit it and re-click the object in the "Environment" pane.

**Comment by ronblum** [comment]
@N-Accumbens Thank you for the suggestion! We'll consider it as part of our ongoing development of the RStudio IDE.
