### ISSUE TITLE
Add option to change "Insert Section" format

### ISSUE THREAD

**Issue by maia-sh** [rstudio/rstudio#7480]
I'm a frequent user of the "Insert Section" shortcut (Ctrl+Shift+R/ Cmd+Shift+R on the Mac). However I find the style hard to see when I'm scrolling through my script. It would be great to have the option to change the format associated with the the "Insert Section" shortcut.

I could imagine this as an option under: `Tools` --> `Global Options` --> `Editing` OR `Display`
Ideally it would allow for user input within a set of parameters, or otherwise offer a few options such as those shown in [RStudio's Code Folding and Sections](https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections).

It would also be great to see this in combination with subsections, which has extensive discussion under #4124.

A current workaround would be to use [snippets](https://support.rstudio.com/hc/en-us/articles/204463668-Code-Snippets), which I found suggested on [SO](https://stackoverflow.com/questions/28795128/change-rstudio-shortcut-for-insert-section). For example,

```
snippet section
	#####${1:label}#####
	
	${2:}
```

Thanks for the great IDE and for considering this enhancement!

**Comment by ronblum** [comment]
@maia-sh Thank you for the suggested enhancement! I'm glad that you've figured out a way to make it work as is. Meanwhile, Ctrl-Shift-R and Cmd-Shift-R aren't working for me, so I've got a bug to file.
