### ISSUE TITLE
Opening and closing Global Options triggers unnecessary restart

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7495]
### System details

    RStudio Edition : Desktop (possibly server, too, haven't checked)
    RStudio Version : 1.2, 1.3, 1.4
    OS Version      : Windows (possibly all, haven't checked)
    R Version       : Any

### Steps to reproduce the problem
- Before running RStudio, clean up all prior state, e.g. on Windows you can use `clean-rstudio.bat` from https://github.com/rstudio/rstudio/tree/master/scripts
- Run RStudio
- Open Global Options, don't change anything, and click OK button

### Describe the problem in detail
- Get a dialog saying "Restart Required: You need to restart RStudio in order for these changes to take effect. Do you want to do this now?"

### Describe the behavior you expected
- Didn't change anything, shouldn't need a restart

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
I am also seeing this behavior on Windows 10 Desktop, stable Pro build 1.3.1056-1.

Wanted to call shenanigans when I saw the issue since I spend alot of time on Windows and have never seen this behavior before, but running the script beforehand is consistently reproing the issue for me.

**Comment by kevinushey** [comment]
Note: the desktop rendering engine options are a likely culprit here as they prompt for restart on change.
