### ISSUE TITLE
Add Color Highlight option like the VScode extension

### ISSUE THREAD

**Issue by will-r-chase** [rstudio/rstudio#7496]
I do a lot of data visualization in Rstudio and one of the things I've really started to miss compared to VScode is the option to highlight color hex codes directly in the editor so I don't have to constantly wonder: "which color is #DC5626?"

**Use case:** you have a color palette like so: 

```
colors <- c("#FD7D07", 
             "#CC351B", 
             "#E06C19", 
             "#D2B0AD", 
             "#603B23", 
             "#B0A8B8", 
             "#BB3326", 
             "#FF8001", 
             "#D0302D")
```

Now you want to shift things around, or pull out one of the specific colors for some reason but you can't remember which one is the red and which one is the blue, so you have to google all the hex codes or something to figure it out. You could use `scales::show_col()` but you still have to open the plot (maybe zoom), then find the right color, and copy and paste the hex code, and it's all quite annoying and takes you out of the flow of programming.

**Solution**
VScode has a really nice extension called [Color Highlight](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight) that automatically highlights any hex code or color designation it finds so you have an immediate visual queue that shows which code is which color and you never have to look them up. It seems small but I find it to be one of the most useful features in the VScode editor. 

![image](https://user-images.githubusercontent.com/29066798/88966752-cfa8a300-d27a-11ea-819e-985095bac8b8.png)

Thank you!

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/5424.
