### ISSUE TITLE
Edit snippets window doesn't play well with themes

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#7500]
The "edit snippets" window doesn't apply the theme correctly, which pose a problem with dark themes. I'm using cobalt, but it's the same with other themes:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/33321678/89049724-aaba3b80-d31f-11ea-8a68-ffd24a0b02f8.png">

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.656
    OS Version      : macOS Catalina 10.15.6
    R Version       : 3.6.2

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gregleleu Thank you for filing the issue! We'll review this as we continue development of RStudio.

This is a regression in 1.3: I can reproduce it in RStudio Desktop 1.3.959, 1.3.1056, and 1.4.640 on  MacOS 10.15.6, but it works correctly in 1.2.5040. It is not an issue with RStudio Server 1.4.640 on Red Hat 8.2.

**Comment by kevinushey** [comment]
Strangely, I cannot reproduce on macOS Catalina 10.15.5 (using RStudio 1.4.663). I wonder if something changed in the most recent Catalina update that breaks this somehow?

**Comment by ronblum** [comment]
Two more instances:
- RStudio Desktop 1.4.662 works on MacOS 10.15.2
- RStudio Desktop 1.4.656 fails on MacOS 10.15.6 (a different machine than the one above)
