### ISSUE TITLE
Error Opening Project

### ISSUE THREAD

**Issue by Mohamed-Hefnawy** [rstudio/rstudio#7503]
### System details

    RStudio Edition : "desktop"
    RStudio Version : ‘1.3.1056’
    OS Version      : Windows 10
    R Version       :  4.0.2 (2020-06-22)

### Steps to reproduce the problem

I am trying to open the project file I created yesterday, but I am not able to open it.

### Describe the problem in detail
I created a Project, I created Rmd file and started to write my code and saved it yesterday. today I started to work on my file, but unfortunately I am not able to open it. 

### Describe the behavior you expected
I am expecting the project file to open.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5009039/diagnostics-report.txt)
<img width="666" alt="Error Opening Project" src="https://user-images.githubusercontent.com/27974170/89077415-cb6bab00-d38a-11ea-8902-109464d511fe.PNG">

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The error message suggests that the `.Rproj` file referenced by that error message may have been corrupted -- you might try deleting that file and re-opening the project.

**Comment by Mohamed-Hefnawy** [comment]
Thanks, I guess I saved the R mark down file as the project file. I will delete the project file.
