### ISSUE TITLE
Viewer pane can't load generated html file

### ISSUE THREAD

**Issue by bajahranks** [rstudio/rstudio#7507]
System details

    RStudio Edition :  Desktop 
    RStudio Version : 1.3.1073
    OS Version      :  Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem
library(plotly)

fig <- plot_ly(
  x = c("giraffes", "orangutans", "monkeys"),
  y = c(20, 14, 23),
  name = "SF Zoo",
  type = "bar"
)
fig

**Describe the problem in detail**
Viewer pane shows this error
`/session/viewhtml5f183f6e4714/index.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A29249 not found`

Inspecting the viewer pane I see this error
`Failed to load resource: the server responded with a status of 404 (Not Found)`

I have confirmed that the `tempdir()` points to the location of the html file.

If I open the html file in a browser the expected interactive plot is displayed

I would also like to add that this began to happen after upgrading to the latest preview version of RStudio. Previously I was experiencing this issue https://github.com/rstudio/rstudio/issues/6737 but with an older version of RStudio. 

**Describe the behavior you expected**
interactive plot being displayed in viewer.

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I think you're experiencing a known problem on Windows with R 4.0.0 (exactly), which has been fixed in more recent versions of R. Can you try updating R and letting us know if that addresses the issue?

https://cran.r-project.org/bin/windows/base/

**Comment by bajahranks** [comment]
Thank you @jmcphers . After updating it now works as expected.
