### ISSUE TITLE
Allow for read-only chunks when opening Rmd files

### ISSUE THREAD

**Issue by olbapjose** [rstudio/rstudio#7510]
I regularly use package [nbgrader ](https://nbgrader.readthedocs.io/) in Jupyter for automatic grading of coding assignments. In the release version of an assignment notebook, the auto-grading cells (provided for the students to check their own solutions before they submit the notebook) are read-only and cannot be modified from within the notebook. Of course you can always modify them if you open the notebook as plain text with a text editor, but that requires more advanced knowledge and the students do not normally cheat like that. 

It would be nice to have the same feature in Rmd files, so that certain chunks, intended for checking your own solutions (or for other purposes other than teaching), are read-only and cannot be modified from within RStudio. Again you can always edit them with a plain text editor, but preventing them from being edited in RStudio would be a very nice start.

I know of package [learnr ](https://cran.rstudio.com/web/packages/learnr/index.html) but that's a step further. Read-only chunks would allow for an easier, more immediate way to create assignment-like Rmd files.

**Comment by ronblum** [comment]
@olbapjose Thank you for the detailed suggestion! We'll review your enhancement request as we continue developing RStudio.
