### ISSUE TITLE
Preview development documentation should consider aliases [Low Impact, Low? Effort]

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/rstudio#7512]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Win10
    R Version       : 3.6.3

### Steps to reproduce the problem

Hi,

I'm not sure this is unexpected and I couldn't find this in the numerous docs I went through, but rendering development documentation does not consider aliases.

I use them for some synonym functions in my package, and I never know which one I should use with `?`. BTW, `F1` does not trigger the dev preview, but this might deserve another ticket.

For instance:

```r
#' do things.
#' @export
#' @rdname foo
#' @aliases foo_synonym
foo= function(x){
  x*42
}

#' @rdname foo
#' @aliases foo
#' @export
foo_synonym = foo
```

```r
?foo #works
?foo_synonym #doesn't work
```

The latter will throw this error:

> Rendering development documentation for 'foo_synonym'
> Error in f(...) : 
>   The specified rdFile ' F:/GITHUB/crosstable/man/foo_synonym.Rd' does not exist.

If correcting this is not possible because of reasons, maybe it is possible to adapt the error message ([here ](https://github.com/rstudio/rstudio/blob/master/src/cpp/r/R/Api.R#L106)I guess?).

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@DanChaltiel Thank you for filing the issue! We'll review it as part of our ongoing development of RStudio.

**Comment by R-Hannibal** [comment]
Closing as out of scope.

While a valid request this out of scope for our current development plans for RStudio (we think this will affect very few package managers).
