### ISSUE TITLE
It is hard to leave the debugging mode after a call to debug(get)

### ISSUE THREAD

**Issue by courtiol** [rstudio/rstudio#7514]
Hi all,
Calling `debug(get)` and then starting for example to write the name of any function is sufficient to trigger the debugging mode.
I think that this is OK since I reckon that RStudio calls `get` in the background to retrieve the possible function names or something like that.
My issue comes after that: once you are in debugging mode, it is borderline impossible to leave it without killing RStudio.
I said "borderline" because I did manage to quit a few times successfully, but simply clicking on the stop sign or simply writing `Q` in the console once does not appear to be enough.
This is certainly a niche usage, and perhaps there is no work around, but you may want to know about this.

## Info for reproducibility

RStudio open version 1.3.1073 "Giant Goldenrod" (718e6d75, 2020-07-29) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6)
AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] ~If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report~
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@courtiol Thank you for filing the issue! I can reproduce this in RStudio Desktop on MacOS 1.3.1073 and 1.4.640, and RStudio Server 1.4.640 on Red Hat 8.2. We'll review this as we continue development of RStudio. In the meantime, although this isn't ideal, does `Session -> Terminate R` get you out of debug mode?
