### ISSUE TITLE
Change the names of links for Debian 9 and 10 on dailies and current download pages

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7515]
### System details

    RStudio Edition : 1.4 dailies and 1.3 current download page
    RStudio Version : N/A
    OS Version      : N/A
    R Version       : N/A

### Steps to reproduce the problem

Go to the 1.4 https://dailies.rstudio.com/ page and the current 1.3 Ubuntu/Debian download page https://rstudio.com/products/rstudio/download-server/debian-ubuntu/ .

### Describe the problem in detail

Some of the names are confusing/incorrect for Debian. The "Ubuntu 18+" build is also for Debian 10, and the "Debian 9+" build is only for Debian 9.

### Describe the behavior you expected

The names of the links for Ubuntu and Debian should reflect the proper links

*In dailies page:*
* Change
`    Ubuntu 18+`
to
`    Ubuntu 18+/Debian 10`

* Change
`    Debian 9+`
to
`    Debian 9`

*In current server download page:*
* Change
`   Debian 9+`
to
`   Debian 9`.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
This is still an issue and is confusing; every so often a user—including internal—with a Debian 10 instances will download the Debian 9+ build.

**Comment by jmcphers** [comment]
Done: 

https://github.com/rstudio/dailies/commit/88600952a31c1a392a5ef83f34529beece6d63f6
https://github.com/rstudio/rstudio.com/commit/b1cb41bca352fb28e46f009e4a3c806c3dde00f0

In the future, it's probably better to file issues on those repositories specifically as that's ultimately where the changes will need to be made.

**Comment by astayleraz** [comment]
I reviewed the provided links and see the requested changes to the text. Closing as fixed.
