### ISSUE TITLE
Avoid jobRunScript switching to jobs panel

### ISSUE THREAD

**Issue by dipterix** [rstudio/rstudio#7516]
Function `jobRunScript` automatically switch to `Jobs` panel. Is there any option to suppress this action and let users focus on R interactive programming itself?

**Comment by ronblum** [comment]
@dipterix Thank you for suggestion, which we'll review as we continue development of RStudio.

**Comment by kevinushey** [comment]
Note: moved to RStudio repository as I believe this will require changes on the RStudio side (and perhaps corresponding changes on the `rstudioapi` side if we change the signature)
