### ISSUE TITLE
Clicking "Apply" or "OK" in Global Options complains about Zotero API Key

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7517]
#7281 # System details

    RStudio Edition : Server
    RStudio Version : 1.4.673
    OS Version      : Ubuntu 20.04 and Red Hat 8.2
    R Version       : 3.6.3 and 4.0.2

### Steps to reproduce the problem

1. `Tools -> Global Options`
2. `Apply` or `OK`

### Describe the problem in detail

A pop up appears with the message, "You must provide a Zotero API Key for access to web libraries."
![image](https://user-images.githubusercontent.com/31009952/89212196-0d663e00-d591-11ea-932c-584b80af0d3c.png)

The only way out is to click on `Cancel`.

This is only a problem on RStudio Server—Desktop works.

### Describe the behavior you expected

Nothing should happen with `Apply`, and Global Options should go away with `OK`.

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Also repro'd on my install of 1.4.672 Server (CentOS7).

**Comment by jjallaire** [comment]
Yiks! I'll take care of this ASAP

**Comment by jjallaire** [comment]
Wasn't sure if I was supposed to close the issue after applying the fix or whether you only close after verification (so re-opening).

**Comment by ronblum** [comment]
@jjallaire Closing the issue is correct (for now, at least), which tells QA to verify it.

**Comment by ronblum** [comment]
Verified in RStudio Server 1.4.675 on Red Hat 8.2.
