### ISSUE TITLE
Deployment failure borks the R session's PATH

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#7518]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.x
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

- Set up a proxy that returns 401 in front of RStudio Connect
- Try to deploy

### Describe the problem in detail

- When the proxy responds with a 401, the IDE borks the user's R session path

### Describe the behavior you expected

- Path should never be broken

Transferred from: https://github.com/rstudio/rsconnect/issues/428

### More details:

This is quite strange and related to #427 . Not sure if this is an RStudio bug or an rsconnect bug 🤷‍♂️ Using RSP 1.2.5033-1 and tested both CRAN / devel rsconnect

I can execute:
```
> system("which sh")
/bin/sh
```
If I publish, I get this output in the Deploy tab of the IDE:
```
/opt/R/3.6.2/lib/R/bin/R: line 8: uname: command not found
Preparing to deploy application...Error: HTTP 401
GET http://apache-kerb/rsconnect/__api__/applications?filter=account_id:1&filter=name:test2&count=100&offset=0

<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
Execution halted
sh: 1: rm: not found
```
Going back to my main R session, the PATH is now funky:
```
> system("which sh")
sh: 1: which: not found
Warning message:
In system("which sh") : error in running command
> Sys.getenv("PATH")
[1] ":/usr/lib/rstudio-server/bin/rpostback:/usr/lib/rstudio-server/bin/postback"
```
I'm wondering if this is related to my user's username on Connect: bobo@DOCKER-RSTUDIO.COM. I have verified that the issue occurs whether I set these options or not:
```
options("rsconnect.libcurl.options" = list(gssapi_delegation = curl::curl_symbols("CURLGSSAPI_DELEGATION_FLAG")$value,
     httpauth = curl::curl_symbols("CURLAUTH_GSSAPI")$value,
     userpwd = ":"
   ))
options(rsconnect.http.verbose = TRUE)
options(rsconnect.http.trace.json = TRUE)
```
However, if I set these options in ~/.rsconnect_profile (which satisfies my proxy), then the deployment works as expected.

My guess now is that rsconnect / the IDE is not recovering cleanly from a 401 Unauthorized response.

**Comment by kevinushey** [comment]
Can you share what your PATH looks like before and after? That is, what is the output of `Sys.getenv("PATH")` before and after deployment?

You could also try running this before deployment:

```
trace(Sys.setenv, quote({
   dots <- list(...)
   if ("PATH" %in% names(dots))
      print(rlang::trace_back())
}))
```

and you might get lucky and see a stack trace from when the PATH change is made.

**Comment by colearendt** [comment]
Bump activity 😄 I'll give it a shot to grab the PATH beforehand and get a traceback.

Before was a normal path IIRC, something like `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`. After was  `:/usr/lib/rstudio-server/bin/rpostback:/usr/lib/rstudio-server/bin/postback`

**Comment by colearendt** [comment]
Not sure if this issue is still at large or not 🤷‍♂️
