### ISSUE TITLE
RStudio with empty R script crashing Chrome devtools / axe a11y checker

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7526]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1073, 1.4.x
    OS Version      : CentOS7
    R Version       : 3.6.2

### Steps to reproduce the problem
- load RStudio session in Chrome
- create a blank R script (Untitled1)
- bring up devtools and try to perform accessibility evaluation using axe-core or even Lighthouse (which uses axe under the covers)
- also crashes in Edge (with either Axe or Microsoft Accessibility Insights, another tool built on axe-core)

### Describe the problem in detail
- after some spinning, get error

<img width="1105" alt="screenshot showing crashed browser process and error message from axe" src="https://user-images.githubusercontent.com/10569626/89465671-5a7c1880-d727-11ea-9b51-e21cea1fefa9.png">

### Describe the behavior you expected
- accessibility audit results; works when nothing loaded in source panel
- makes it very difficult to audit accessibility; possible we are exposing a bug in Chromium or axe-core but need to narrow down what change in our HTML/CSS/JS triggered this

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Note, only happens if editor panel is showing (e.g. just a simple blank .R script will cause the crash).

**Comment by mikebessuille** [comment]
This is not necessarily a bug in RStudio itself - maybe a chrome dev tools bug.  But we should monitor this and try to reproduce it.  Leaving in 1.4 for now.

**Comment by gtritchie** [comment]
No longer reproing for me; looks like it was fixed externally.
