### ISSUE TITLE
Rstudio update package UI

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#7535]
Team,
This is a small feature request and completely understandable if it's in the parking lot for the next few years! :slight_smile:

RStudio->Tools->Check for Package Updates provides a dialog box that lists out all the packages that are available for updates. In my experience, there are 5-10 packages that I know or had installed but easily another 20+ packages that I do not know of nor have knowledge of installing them hence likely core or dependent packages.

The UI also provides details on the current and new version plus option to click on the "News" icon which takes me online for the version history information of the respective package.

It would be helpful to the user to get the user-friendly title & description of the package to enable the user to make the decision on the update.

As of now, I click on the "News" icon to open the internet page and remove the "news/news.html" from the URL in my browser to access the package description.

It would be preferred if either the mouse-hover on the package name provides the title+description of the package since the help files are already present locally OR, another column beside the "News" column that takes the user to the package details page online.

Thanks for your time

Vinay

**Comment by ronblum** [comment]
@vinaychuri Thank you for the suggestion! If you go to the Packages pane and click on `Update`, you get the same pop-up. But, in the Packages pane, the list of installed packages includes a description column. Are you looking for the same information—same column—in the updates pop-up?

**Comment by vinaychuri** [comment]
Hi Ron, Thanks for the tip on the packages tab, that was new for me as I am not sure how it was not enabled for my tabs.

Yes, the one-line description would be helpful in the "Update Package" so that user could make informed decisions.
Enclosed is my "Update Package" popup and I would not know what package "bit" is meant for, do I update, is it important for me etc.

I as an individual would be most happy with the one-line description as in the "Packages" pane but the RStudio UX team would have other ideas for sure.

<img width="472" alt="update package popup" src="https://user-images.githubusercontent.com/37381682/89540607-e58a0b00-d81a-11ea-80cb-b7066e8bc24d.png">
