### ISSUE TITLE
R Studio Segmentation fault Ubuntu 20.04 

### ISSUE THREAD

**Issue by jflournoy** [rstudio/rstudio#7539]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.684
    OS Version      : Linux Ubuntu 20.04 
    R Version       : 3.6.3

### Steps to reproduce the problem

Run `rstudio`

### Describe the problem in detail

R studio begins to start, but hangs with a blank black window and then segfaults.

The last few lines from running `strace rstudio` are:

```
ioctl(18, DRM_IOCTL_I915_GEM_CREATE, 0x7ffe87476ed0) = 0
ioctl(18, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe87476ec4) = 0
ioctl(18, DRM_IOCTL_I915_GEM_MMAP, 0x7ffe87476f10) = 0
ioctl(18, DRM_IOCTL_I915_GEM_CREATE, 0x7ffe87476d60) = 0
ioctl(18, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe87476d54) = 0
ioctl(18, DRM_IOCTL_I915_GEM_MMAP, 0x7ffe87476c00) = -1 ENOMEM (Cannot allocate memory)
ioctl(18, DRM_IOCTL_I915_GEM_MMAP_GTT, 0x7ffe87476b80) = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_SHARED, 18, 0x1007e9000) = -1 ENOMEM (Cannot allocate memory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xa0} ---
gettid()                                = 20141
getpid()                                = 20141
prctl(PR_SET_PTRACER, 20141)            = 0
prctl(PR_GET_DUMPABLE)                  = 1 (SUID_DUMP_USER)
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f047e6f8b50) = 20260
wait4(20260, [20260:20260:20200806,103957.373383:ERROR scoped_ptrace_attach.cc:45] ptrace: Operation not permitted (1)
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 20260
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=20260, si_uid=1000, si_status=1, si_utime=0, si_stime=3} ---
waitid(P_ALL, 0, {}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
rt_sigreturn({mask=[HUP SEGV]})         = 20260
prctl(PR_SET_PTRACER, 0)                = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f0482b233c0}, NULL, 8) = 0
rt_sigreturn({mask=[HUP]})              = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xa0} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

This is at the end of a long series of similar ioctl lines.

Diagnostics report here: [diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5036911/diagnostics-report.txt)

For what it's worth, the following did not work for me:

```
export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox"
rstudio
```

However, the following (found [here](https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1876219)) does work for me:

```
export MESA_LOADER_DRIVER_OVERRIDE=i965
rstudio
```

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jflournoy Thank you for raising the issue! We will review it as part of our continuing development of RStudio. I'm glad, though, that there is a workaround—thank you for including it!

**Comment by RobinKohrs** [comment]
@jflournoy I think I'm seeing a similar behavior. I'm running rstudio version 1.3.1093 on a very old macbook air on ubuntu 20.04. When I start up rstudio I get the message `Segmentation fault (core dumped)`.  Your suggestion to set `export MESA_LOADER_DRIVER_OVERRIDE=i965` sounds promising, but I'm not really sure what it's doing. I'm really sorry if this is not the right place to ask this...

**Comment by mxblsdl** [comment]
Mentioned above but want to reiterate

```
export MESA_LOADER_DRIVER_OVERRIDE=i965
```

Solved my issue. Also running Ubuntu 20.04 on older mac.

**Comment by mikebessuille** [comment]
Graphics driver crash related to QT.   Thanks for mentioning the solution to change the graphics driver!  Closing this issue; it should be fixed when we move to Electron.
