### ISSUE TITLE
Plot pane doesn’t render in native resolution on iPadOS

### ISSUE THREAD

**Issue by bastianolea** [rstudio/rstudio#7548]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.959
    OS Version      :  13.6
    R Version       :  3.6.2

### Steps to reproduce the problem
Plotting any graphic on RStudio Server accessed through an iOS device, such as an iPad, using Safari browser. Graphics look pixellated because they are rendered in half the native resolution, i.e. not in “retina” resolution (264 pixels per inch)

### Describe the problem in detail
Plots are rendered in the Plot pane in half the native resolution, instead of using the full resolution of an iPad screen. This produces graphics that look cluttered and blocky even if the device has enough resolution to plot thinner lines or smaller objects.

### Describe the behavior you expected
Expected behavior would be to have plots plotted in full retina resolution, but with graphic elements scaled up, so that text and other features don’t look too small due to increased resolution.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bastianolea Thank you for raising this! I can reproduce it on iPadOS 13.4.1 (time to update). We'll review this as we continue working on RStudio.
