### ISSUE TITLE
News icon on the Update GUI generates wrong URL

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#7550]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1073
    OS Version      : 18.04.5 LTS
    R Version       : 4.0.2

### Steps to reproduce the problem
* Search for updates using the GUI
* Click on the "show package news" icon

### Describe the problem in detail
The URL linked from the icon is relative to the server IP or domain, for example, news URL for this package gets generated as follows.
![image](https://user-images.githubusercontent.com/14981085/89722368-73e2c600-d9ae-11ea-972f-df823ef8c9a1.png)
![image](https://user-images.githubusercontent.com/14981085/89722385-9e348380-d9ae-11ea-8486-d25ab751e013.png)
If it is relevant I use Nginx as a reverse proxy with the official recommended configuration.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@andresrcs Thanks! I'm unable to reproduce the issue, in RStudio Server running on Ubuntu. The destination URL is
> https://cran.rstudio.com/web/packages/rgdal/ChangeLog

I'll mark this for review, and thanks for the added information re the reverse proxy!

**Comment by andresrcs** [comment]
The weird thing for me is that I was going to file this bug a while ago but at that time I updated to the latest preview release and the issue went away. It has come back since at least two releases ago, although I can' t be sure which one exactly.

**Comment by andresrcs** [comment]
Is there any news on this? This issue is still present on RStudio Server 1.4.1056 and I get this warning message on the console.
```
> 
Warning message:
In (function (packageName, libraryPath)  :
  Failed to infer appropriate NEWS URL: using 'NEWS' as best-guess candidate
```
Is there any information I can provide to help to debug this?

**Comment by kevinushey** [comment]
Can you try executing the following:

```
trace(.rs.rpc.get_package_news_url, quote(print(ls.str())))
```

and then sharing the output you see after you try to update packages + navigate to that NEWS URL?

**Comment by kevinushey** [comment]
FWIW, I see on macOS:

```
Tracing (new("functionWithTrace", .Data = function (packageName, libraryPath)  .... on entry 
libraryPath :  chr "/Users/kevinushey/r/r-devel-sanitizers/library"
packageName :  chr "rgdal"
```

on a development build of R I have running locally.

**Comment by andresrcs** [comment]
> Can you try executing the following:
> 
> ```
> trace(.rs.rpc.get_package_news_url, quote(print(ls.str())))
> ```
> 
> and then sharing the output you see after you try to update packages + navigate to that NEWS URL?

This is what I get

> trace(.rs.rpc.get_package_news_url, quote(print(ls.str())))
Tracing function ".rs.rpc.get_package_news_url" in package "rstudio"
[1] ".rs.rpc.get_package_news_url"
Tracing (new("functionWithTrace", .Data = function (packageName, libraryPath)  .... on entry 
libraryPath :  chr "/usr/local/lib/R/site-library"
packageName :  chr "ggeffects"
> 
Warning message:
In (new("functionWithTrace", .Data = function (packageName, libraryPath)  :
  Failed to infer appropriate NEWS URL: using 'news/news.html' as best-guess candidate
