### ISSUE TITLE
File looses its modified status when popped in from source window

### ISSUE THREAD

**Issue by gustavdelius** [rstudio/rstudio#7552]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.929
    OS Version      : Linux Mint 19.3 Cinnamon
    R Version       : 4.0.2

### Steps to reproduce the problem
Open a source file and pop it out into a source window. Make a modification in the file so that it is marked as unsaved (file name is shown in red with an asterix after it). Then, without saving it, pop it back into the main RStudio window or move it to another source window. You will see that it looses its "modified" status. The file name is no more shown in red with the asterix, and RStudio does not offer to save the file when for example doing a reload with Ctrl-Shift-L

### Describe the problem in detail
See above

### Describe the behavior you expected
I expected that moving the file between source windows would not make RStudio forget that the file has been changed.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@gustavdelius Thank you for filing the issue! Unfortunately, we don't support Linux Mint. The closest we support is Ubuntu. I tried both 18.04 and 20.04 (we only support LTS, so not 19.x), with both Plasma and Gnome, and I can't reproduce the issue on either one. However, this will be useful to keep here for other users who might run into the same issue on Linux Mint.

**Comment by gustavdelius** [comment]
@ronblum , thank you very much for doing that investigation. It is very interesting that such issues can be caused by which linux distro one is using.

**Comment by ronblum** [comment]
@gustavdelius You're welcome, and I'm sorry I couldn't be of more help. And yes, it is interesting—you can imagine what's involved in testing on multiple versions of Linux! It's one of the reasons we rely on users—like you—to try out the dailies. By the way, the desktop can also make a difference: I ran into #7585 while investigating this issue.
