### ISSUE TITLE
selectively turn off auto-indenting after right-arrow+carriage_return

### ISSUE THREAD

**Issue by higgi13425** [rstudio/rstudio#7553]
This is an enhancement request to adjust the automatic code indenting feature so that it does **not** indent the object name  that comes immediately after a right-arrow+ carriage_return combination

Example 1 below shows code for a typical pipe ending in a right arrow to assign a new data object. RStudio automatically indents each line after the first in an R script (or in a code chunk in an rmd document). However, when using the right-arrow for more literate programming, this indents the new data object.

The reasoning behind literate programming is to make code both machine-readable and human-readable, like sentences in English. It makes a lot of sense sense (for left-to-right English readers) to start with a subject (the original data object), piped into several (indented) verbs to wrangle the data, then right-arrowed into a resulting data object (the object of our sentence).

The right-arrow to assign a pipe result to a new object enhances literate programming.

However, if the resulting data object is hidden at the end of a line, or (per Example 2) auto-indented, the code is harder to read. And it makes it harder to find the resulting objects.

Conceptually, it would be nice to have data objects (both subjects and direct objects) line up on the left margin of code, with verbs in the pipe automatically indented. This separates data objects from data wrangling.
This would make it easy to find both the input data object (subject) and 
the output data object (direct object of the pipe).

It would be nice to have the option of setting RStudio to **not** auto-indent specifically after the combination of a right-arrow and a carriage_return,  as in Example 3 (in which I've manually removed the indent). 

I think this would make the code easier to read, since it would be more obvious where the data transformation pipe ends and where the resulting data object is.

Obviously, this is isn't a major issue, but just a feature that would be nice to have available for folks who are big believers in literate programming with the right-arrow.

```
# Example 1
mtcars %>% 
    filter(gear == 4) %>% 
    group_by(cyl) %>%
    summarize(mean_mpg = mean(mpg))-> mtcars_g4_mpg

# Example 2
mtcars %>% 
    filter(gear == 4) %>% 
    group_by(cyl) %>%
    summarize(mean_mpg = mean(mpg))->
    mtcars_g4_mpg

# Example 3
mtcars %>% 
    filter(gear == 4) %>% 
    group_by(cyl) %>%
    summarize(mean_mpg = mean(mpg))->
mtcars_g4_mpg
```

**Comment by thomas-neitmann** [comment]
This is an excellent proposal which I wholeheartedly support!

**Comment by ronblum** [comment]
@higgi13425 Thank you for the suggestion, as well as the detailed explanation and reasoning! We'll review your request as part our ongoing development of RStudio.

**Comment by higgi13425** [comment]
thanks!
    On Monday, August 10, 2020, 12:15:18 PM EDT, Ron Blum <notifications@github.com> wrote:  
 
 


@higgi13425 Thank you for the suggestion, as well as the detailed explanation and reasoning! We'll review your request as part our ongoing development of RStudio.
