### ISSUE TITLE
Console ANSI handler doesn't invert newly-set colors (256 color mode)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7557]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1 through latest 1.4
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
In Console, execute this command and look at the output; repeat this exercise in R running in the Terminal pane or a standalone terminal.

The command turns on inverse mode (exchange default foreground and background) then sets a red-tone (using 256-color mode, 196 is the color) for the foreground (which should be treated as the background), then resets the foreground (hence should reset the background).

```R
cat("\033[7m\033[38;5;196mInverted with red background \033[39mInverted with default background\033[27m")
```

### Describe the problem in detail
Console output is incorrect, color-wise. 

### Describe the behavior you expected
Same behavior in Console and a terminal.

Terminal (correct):

<img width="818" alt="screenshot of terminal showing correct output" src="https://user-images.githubusercontent.com/10569626/89810090-5bc78f80-daf1-11ea-90f2-6b44fb7b744e.png">

Console (incorrect):

<img width="780" alt="screenshot of terminal showing incorrect output" src="https://user-images.githubusercontent.com/10569626/89810127-6bdf6f00-daf1-11ea-9de1-c0349cb0a11e.png">

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.734, R Version - 4.0.2, Windows 10 x64 - Desktop 

Very basic comparison test between current stable (1.3.1073) and current daily builds using the codechunk noted in the issue report in the RStudio console, seeing incorrect (black background, red text) behavior on the old build and correct (half red background, half black background, all white text) on the daily.
