### ISSUE TITLE
Mis-match bracket type coloring with rainbow brackets in daily build

### ISSUE THREAD

**Issue by Maschette** [rstudio/rstudio#7559]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.692
    OS Version      :  Windows 10
    R Version       :  R4.0.2

### Steps to reproduce the problem
following on from #1888 (amazing feature) turn on rainbow color brackets. mismatch a bunch of bracket types
### Describe the problem in detail
not sure if this is the expected behaviour, sorry if it is. when you have a bunch of brackets if they are mismatched bracket types on the closed brackets eg ( ] they are becoming the same color matching. See full example in the image. 
![image](https://user-images.githubusercontent.com/14663215/89753494-e3c28f00-db1b-11ea-951e-53a3cfa35607.png)

### Describe the behavior you expected
I would expect the mismatched brackets to have color or .ace_paren_0 until it is matched with an opening bracket that matches, similar to what is happening to the closed brackets above in the bottom line. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Maschette Thank you for filing this! I was just getting ready to file the same thing, with an almost identical screen shot, so you saved me a bit of time. :) 

As a reference point: https://www.emacswiki.org/emacs/RainbowDelimiters#toc4 which allows one to specify `rainbow-delimiters-unmatched-face`

**Comment by jmcphers** [comment]
@adamconroy is this expected?

**Comment by adamconroy** [comment]
It is expected as that's how I'd want it to work if I were using the feature as it makes it very clear when you have mis-matched braces in your code (which, to me, would be the purpose of the feature). However, I can see that people might not like it. We could change this or make it a flag if people desired.

**Comment by kevinushey** [comment]
FWIW, I like the current behavior as well. If we see significant user interest in making this more customizable then we could consider taking the time to do so?

**Comment by jmcphers** [comment]
Agree that the current behavior is reasonable, we'll leave this open to gauge interest.

**Comment by zerweck** [comment]
For mis-matched brackets there already is the "unexpected token" warning if you activate Code Diagnostics.
How about a "warning" color that explicitly does not match other correctly opened-and-closed brackets?

**Comment by ronblum** [comment]
@adamconroy Is there a way for a user to customize this, the equivalent of `rainbow-delimiters-unmatched-face`?

**Comment by adamconroy** [comment]
There is not currently a way to do that but it's something that could be added. It wouldn't be a big change but it wouldn't be tiny either due to the way that the statefulness of the coloring executes.
