### ISSUE TITLE
savehistory() shim does not save the history

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/rstudio#7560]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.693
    OS Version      : Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

```r
savehistory(tmp <- tempfile())
readLines(tmp)
```

```
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\csard\AppData\Local\Temp\Rtmpwr8qAX\file3d241d0920b2': No such file or directory
```

### Describe the problem in detail

The `savehistory()` shim does not seem to to actually save the history.

### Describe the behavior you expected

I expected `savehistory()` to create `tmp`, with the command history of the current session, the last issues command, i.e. `savehistory()` itself, as the last line.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gaborcsardi** [comment]
It works on 1.3.1056, so this seems to be a new bug.

**Comment by gtritchie** [comment]
I cannot reproduce this with 1.4.862 (latest daily build) on Windows.

@gaborcsardi Can you check with latest build and see if it still happens for you?

**Comment by gaborcsardi** [comment]
@gtritchie It works fine now, thanks for looking. :)
