### ISSUE TITLE
Nested data frames will not sort by binary indicator in Data Viewer if 1 is originally the first row instead of 0

### ISSUE THREAD

**Issue by fordholland** [rstudio/rstudio#7562]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1056
    OS Version      : Windows 10 version 1803
    R Version       : 3.6.0
    dplyr Version   : 1.0.1

### Steps to reproduce the problem

1. Run the following code:

```{r}
df <- dplyr::tribble(
  ~ val, ~ tbl,
  1, dplyr::tibble(col1 = 1, col2 = 1), 
  0, dplyr::tibble(col1 = 0, col2 = 0), 
) 

View(df)
```
2. Note that clicking on the data frames in the `tbl` column to view displays two columns with values corresponding to the indicator `val`:
![image](https://user-images.githubusercontent.com/10606620/89816858-449a9900-db15-11ea-88bd-f7c75d88339b.png)
![image](https://user-images.githubusercontent.com/10606620/89816911-567c3c00-db15-11ea-90ac-c6f157bffbe8.png)

3. Sort by `val` so that the first row is `0`:
![image](https://user-images.githubusercontent.com/10606620/89818419-b673e200-db17-11ea-9a9b-2466f39cefc0.png)

4. Open the data frames in `tbl` again to find that the values no longer correspond to the indicator `val`.

### Describe the problem in detail

When using the RStudio Data Viewer to sort nested data frames according to a binary (`0` and `1`) column, the column containing nested data frames will not sort if the first row of the binary column was not `0` initially. 

This issue seems related but perhaps not identical to https://github.com/rstudio/rstudio/issues/7546.

### Describe the behavior you expected

Following the steps above, the Data Viewer correctly sorts the nested data frame values after running the following, where `0` is initially the first row value:
```{r}
df <- dplyr::tribble(
  ~ val, ~ tbl,
  0, dplyr::tibble(col1 = 0, col2 = 0), 
  1, dplyr::tibble(col1 = 1, col2 = 1), 
) 

View(df)
```

The Viewer also correctly sorts data frames when the column sorted on does not contain `0`:

```{r}
df <- dplyr::tribble(
  ~ val, ~ tbl,
  1, dplyr::tibble(col1 = 1, col2 = 1), 
  2, dplyr::tibble(col1 = 2, col2 = 2), 
) 

View(df)
```

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fordholland Thank you for filing the issue! I can reproduce it. Note, though, that for the last example, I do see an issue—when the `val` column is sorted in reverse, the same problem occurs. In any case, we'll review this as we continue developing RStudio.

**Comment by ahcyip** [comment]
stale, but unclear if fixed
