### ISSUE TITLE
Incorrect End key behavior in visual editing mode

### ISSUE THREAD

**Issue by jcheng5** [rstudio/rstudio#7563]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.694
    OS Version      : Ubuntu 18.04.5 LTS
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Launch visual editor
2. Enter text like the following (i.e. "two" and "four" are formatted as code):
> one `two` three `four` five
3. Put the cursor at the beginning of the line
4. Press the End key

### Describe the problem in detail

The cursor moves to the beginning of the code node (`two`).

Also, if you put the cursor inside of `two`, then pressing End does go to the end of the line. But if you put the cursor inside of "three", then pressing End goes to the beginning of `four`.

### Describe the behavior you expected

The cursor moves to the end of the line

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
fixed via: https://github.com/rstudio/rstudio/commit/be35e18a53e7ce92d7d3b31164385cf2ea4d2540 (will be tomorrow's daily build)

**Comment by jcheng5** [comment]
Sorry, still seeing this in build 1.4.715.

**Comment by jjallaire** [comment]
Okay, will take a look!

**Comment by jjallaire** [comment]
Same issue reported by @dragonstyle (but w/ select to end of line not go to end of line):

> Nit - When I have the following text Multi-library Support and place the cursor here: |Multi-library Support and the use Command+Shift+Right Arrow to select to the end of the line, the selection stops at the start of the - (e.g. |Multi|-library Support ). Happy to add as a bug if that is easier to track.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rstudio/commit/e881e67ff881a2c1526af9f0ba53e13ef15ef9cb#diff-e091cffd8e6a8cfd15859c4122d81d5e
