### ISSUE TITLE
Feature Request: Sort commands in command palette by frecency

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#7567]
The command palette is excellent addition to RStudio! I use it frequently and sometimes for the same command repeatedly. Using it for the same command twice requires repeating the same actions twice (typing enough to show the command, selecting the command, etc.). 

A great way to surface the last used and most frequently used commands would be to sort by [frecency](https://en.wikipedia.org/wiki/Frecency) (frequent + recent), for example using an algorithm similar to the [one described here](https://wiki.mozilla.org/User:Jesse/NewFrecency). Ideally, the last used command would be a few keystrokes away: open command palette and press enter. The current behavior is to run the first command in the list if the palette is empty; amusingly this runs `setwd()`.

**Comment by jmcphers** [comment]
This is a great idea (and pretty commonly done in command palettes in other apps).

**Comment by jmcphers** [comment]
Closed by https://github.com/rstudio/rstudio/pull/8645 in Juliet Rose.
