### ISSUE TITLE
Ctrl+d shortcut not working

### ISSUE THREAD

**Issue by mskar** [rstudio/rstudio#7572]
Ctrl+d is a default editor keyboard shortcut in RStudio
![image](https://user-images.githubusercontent.com/13444106/90047105-632c9b80-dc9f-11ea-890a-e345d9dac911.png)
but it does nothing.

I expect ctrl+d to delete 1 character to the right, just like the ⌦ key:
![image](https://user-images.githubusercontent.com/13444106/90048520-a0922880-dca1-11ea-82b6-71527c13585e.png)

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      :  MacOS Catalina 10.15.6
    R Version       : 4.0.2

### Steps to reproduce the problem
Press ctrl+d with the caret at the beginning of a character in the editor

### Describe the problem in detail
Nothing happens upon pressing ctrl+d
![image](https://user-images.githubusercontent.com/13444106/90049269-9290d780-dca2-11ea-947d-db037394d6df.png)

### Describe the behavior you expected
I expect the character on the right to be deleted.
![image](https://user-images.githubusercontent.com/13444106/90049389-bbb16800-dca2-11ea-850e-c6ac6afebd65.png)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mskar Thank you for filing the issue! I can't reproduce it, though—it works for me in the same environment setup. Can you check on a couple of things?
1) Does it work correctly in other applications? I used Notes and Word as a comparisons in which <kdb>Ctrl-D</kbd> deletes.
2) What happens if you change the shortcut to something else, say  <kbd>Ctrl-R</kbd>?

**Comment by mskar** [comment]
Hi @ronblum,

1. Yes, it works for me in Notes, Word, and Chrome.
2. Setting Delete to `Ctrl+R` works, i.e. I can then Delete with `Ctrl+R`.

I found out today that **Deleting with `Ctrl+D` works** for me **when Vim mode is off.**

I think the reason you can't reproduce this issue is that Vim mode needs to be turned on.
Can you try turning Vim mode on and then using `Ctrl+D`?

I did some further testing.
`Ctrl+D` only works with Vim mode off on both my MacBook Pros (MBP),
but I do not see this issue on my 2 MacBook Airs (MBA).
Please see more details below.

- 2019 MBP: `Ctrl+D` only works with Vim mode off
> RStudio Edition : Desktop
> RStudio Version : 1.3.1073
> OS Version      :  MacOS Catalina 10.15.6
> R Version       : 4.0.2

- 2017 MBP: `Ctrl+D` only works with Vim mode off
> RStudio Edition : Desktop
> RStudio Version : 1.4.559
> OS Version      :  MacOS Catalina 10.15.4
> R Version       : 4.0.0

- 2017 MBA: `Ctrl+D` works regardless of Vim mode setting
> RStudio Edition : Desktop
> RStudio Version : 1.1.442
> OS Version      :  MacOS Catalina 10.15.3
> R Version       : 3.6.2

- 2014 MBA: `Ctrl+D` works regardless of Vim mode setting
> RStudio Edition : Desktop
> RStudio Version : 1.1.414
> OS Version      :  MacOS Catalina 10.15.3
> R Version       : 3.6.2

**Comment by ronblum** [comment]
@mskar Thanks for checking further! I can confirm that the issue is in vim mode. <kbd>Ctrl-D</kbd> worked in RStudio 1.2.5040, so the problem appeared in RStudio 1.3. We'll review this as we continue development of RStudio.

That said: <kbd>Ctrl-D</kbd> doesn't work for me in Vim, both the GUI app and in the terminal. What behavior do you see?

**Comment by mskar** [comment]
Thanks for following up, @ronblum!

I can confirm that the issue did not exist in RStudio 1.2.5042 or earlier.

Yes, you are right that `Ctrl+D` is not a builtin Vim insert mode shortcut.
If I run `vim -u NONE` or `nvim -u NONE`, `Ctrl+D` does nothing in insert mode.
In my `.vimrc` and `init.vim`, I bind `Ctrl+D` to delete
```
inoremap <C-d> <C-g>u<Delete>
cnoremap <C-d> <Delete>
```

In general, I use many bash shortcuts in insert mode:
`Alt+B`: move👈1⃣word
`Alt+D`: delete👉1⃣word
`Alt+F`: move👉1⃣word
`Ctrl+A`: move👈to line start
`Ctrl+B`: move👈1⃣char
`Ctrl+D`: delete👉1⃣char
`Ctrl+E`: move👉to line end
`Ctrl+F`: move👉1⃣char
`Ctrl+H`: delete👈1⃣char
`Ctrl+K`: delete👉to line end
`Ctrl+U`: delete👈to line start
`Ctrl+W`: delete👈1⃣word

I can get all of the above shortcuts to work in RStudio with Vim mode on except `Ctrl+D`.
Some work by default (`Ctrl-A`, `Ctrl-E`, `Ctrl-F`, `Ctrl-B, `Ctrl-H`), others I have to remap in RStudio (`Alt-F, `Alt-B`, `Alt-D`, `Ctrl-U`), and `Ctrl-W` closes windows even after remapping in RStudio so I remap `Ctrl-W` using [karabiner](https://karabiner-elements.pqrs.org/).

**Comment by mskar** [comment]
Still a problem in RStudio version 1.4.1103
