### ISSUE TITLE
Double click selection behaviour is inconsistent between different panes

### ISSUE THREAD

**Issue by jarauh** [rstudio/rstudio#7577]
In the source pane, double clicking on a decimal number `0.1234567` will select everything after the dot (`1234567`).

In the console pane, double clicking on a decimal number `0.1234567` will select the complete number (`0.1234567`).

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows 10
    R Version       : 4.0.2

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jarauh Thank you for filing the issue! I can't reproduce it in either Windows 10 or MacOS 10.15.6. Does it happen when there's more code in the console in addition to `0.1234567`, or is even just `0.1234567` alone on the command line or output sufficient?

**Comment by mwip** [comment]
I cannot reproduce this on Linux (Version 1.3.1056). Not even with more characters (e.g. `c(0.1234678, 0.1234678, 0.1234678, 0.1234678)`)

**Comment by jarauh** [comment]
Ok, I figured out that the behaviour depends on the type of the file in the source pane: Specifically, the behaviour of selecting only the part after the dot happens for HTML and CSS files.

I observed this behaviour when computing numbers with R to substitute in CSS.

So the behaviour might actually be a feature... Not sure for whom, though.

**Comment by jarauh** [comment]
By the way, thanks for looking into this so quickly, @ronblum and @mwip.

**Comment by ronblum** [comment]
As a comparison point, on MacOS, the full number is selected in Notes but only to the partial number in Vim and Word.
