### ISSUE TITLE
IDE throws error if default arg of a pkg function contains non-ASCII strings on Windows

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#7580]
# System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.706 (The latest daily build)
    OS Version      :  Windows 10 **(it's only reproducible on Windows 10)**
    R Version       : R 4.0.0

### Steps to reproduce the problem

1. Write a package where one of the function's default argument contains non-ASCII characters.
2. Use Roxygen to update the doc and install the package
3. In RStudio IDE, type half of the function name to trigger the code auto-completion.
4. You can see the error message on the Screen. (Not all the non-ASCII characters will trigger the error message but it will be displayed as garbage letters)

### Describe the problem in detail

**I've created a sample package at https://github.com/shrektan/pkg.with.nonascii.doc** so that you can reproduce this easily.

Again, it can be only reproducible on Windows.

The screenshot:

![image](https://user-images.githubusercontent.com/8368933/90201683-2d59f500-de0e-11ea-9967-eb51a6d3c965.png)

![image](https://user-images.githubusercontent.com/8368933/90201694-377bf380-de0e-11ea-9c51-e6a1f7c489c0.png)

### Describe the behavior you expected

I know it's not a good practice to use non-ASCII characters in the R code. 

I know we can use `\uxxx` form to escape the UTF-8 strings. 

However, if the package is used only internally and considering the fact that it's much easier for the user to read the documents in plain text, I believe it's reasonable to display R document with non-ASCII characters in RStudio IDE.

Thanks!

**Comment by ronblum** [comment]
@shrektan Thank you for raising the issue! I'm unable to reproduce it on Windows 10 with R 4.0.2 and 3.6.2, but I'll leave this open to review.

**Comment by shrektan** [comment]
You can’t? Then it must relate to the OS language settings. I’ll take a look.

**Comment by shrektan** [comment]
@ronblum Yes, I can confirm that if you set the OS language to English, there will be no error message. However, you can see that the non-ASCII letters displayed are not expected. In contrast, `?hello` will give correct UTF-8 documents. 

So I expect RStudio IDE should display correct UTF-8 letters in such cases for the code-completion message.

In addition, you may have to set the language to Simplified Chinese (简体中文) in order to fully reproduce the error message that I use.

Thanks!

### You are using the English Language for the OS

![image](https://user-images.githubusercontent.com/8368933/90302224-4a0e2f80-ded7-11ea-94ed-ec588e431167.png)

### The auto-completion message display UTF-8 letters in the raw form

![image](https://user-images.githubusercontent.com/8368933/90302146-de2bc700-ded6-11ea-9647-08b83a933d35.png)

### R's documents display them correctly as expected

![image](https://user-images.githubusercontent.com/8368933/90302157-ed127980-ded6-11ea-8837-d207db25eb9f.png)

### If you want to see the error message as I experienced, you need to set the OS Language to Simplified Chinese

![image](https://user-images.githubusercontent.com/8368933/90302235-598d7880-ded7-11ea-95df-6b87a91654d9.png)

**Comment by kevinushey** [comment]
Just to confirm: does it absolutely depend on the OS's language setting, or can it also be reproduced by setting the R system locale via `Sys.setlocale()`? E.g.

```
Sys.setlocale(locale = "Chinese")
```

**Comment by shrektan** [comment]
@kevinushey Yes, you can reproduce the error without changing the OS's language setting, if you execute [the following code](https://github.com/Rdatatable/data.table/pull/4524#issuecomment-638969366):

```r
x <- list(
  LC_COLLATE = "Chinese (Simplified)_China.936",
  LC_CTYPE = "Chinese (Simplified)_China.936",
  LC_MONETARY = "Chinese (Simplified)_China.936",
  LC_NUMERIC = "C",
  LC_TIME = "Chinese (Simplified)_China.936"
)
for (i in seq_along(x)) {
  Sys.setlocale(names(x)[[i]], x[[i]])
}
```

Note that despite using `Sys.setlocale(locale = "Chinese")` seems get the same locale settings. However, in the latter case, RStudio IDE can display the UTF-8 strings correctly in the code completion and I don't know the reason.

So you need to use the code I provide above, in order to reproduce what I've experienced on Windows 10 with the "Simplified Chinese" language settings.

**Comment by kevinushey** [comment]
Thank you! I was able to reproduce.

**Comment by kevinushey** [comment]
Looks like we at least no longer give an error in the latest daily builds (tested on 1.4.933):

<img width="748" alt="Screen Shot 2020-10-14 at 11 48 24 AM" src="https://user-images.githubusercontent.com/1976582/96032204-3453b280-0e13-11eb-951e-ec87c51501b3.png">

Not sure if there's a way to avoid mis-encoding the arguments, though.

**Comment by shrektan** [comment]
I'm going to close this issue as the daily build seems resolved this issue already. 

(I think it may only display the native-encoding-representable strings well, but that's enough)

![image](https://user-images.githubusercontent.com/8368933/100036804-dbc4fb80-2e3b-11eb-999f-13c7af3daad7.png)


Thanks @kevinushey !
