### ISSUE TITLE
Shortcuts not working as expected inside visual editor

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#7581]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.708
    OS Version      : Windows 10
    R Version       :  4.0.2

### Steps to reproduce the problem

1. Open a new rmd document
2. Create a new R chunk (CTRL+ALT+I works)
3. write some R code 
4. try to comment them with comment shortcut (CTRL+SHIFT+C)
5. write some text outside of a chunk
6. try to comment them with comment shortcut (CTRL+SHIFT+C)

### Describe the problem in detail

The shortcut does not work the same inside the visual editor or in the Rmd doc itself. I find it confusing that it works differently for the same document depending if you are editing in the visual editor or not.

It may not be an issue at all if the keyboard shortcut are not suppose to work the same. 
I have not tested them all but others seems to be not working as expected. 

### Describe the behavior you expected

I expect it to work as in the Rmd document not inside the visual editor. 

* In the R chunk, I expect the line to be commented as in the Rmd doc

* Outside a chunk, I expected the line to be commented as in the Rmd doc but it seems it is now different in the visual editor (from https://rstudio.github.io/visual-markdown-editing/#/content?id=commenting) - it still odd to have a different behavior from inside the visual editor or not. Maybe I am expecting here that the new comment insertion from the visual editor is the same when used in traditional mode in Rmd file ? 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
@jmcphers Here we disable a bunch of source-editor commands while in visual mode:

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java#L543-L595

This is a carryover from when we were using CodeMirror as the embedded editor. It seems like just about all of these could be re-enabled, with a couple of qualifications:

1) They need to be enabled/disabled according to whether the cursor is in a code chunk;
2) They need to be "routed" to the correct code chunk.
