### ISSUE TITLE
Dropdown menus don't appear at first on Ubuntu 20.04 with Plasma

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7585]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1056 & 1.3.1073
    OS Version      : Ubuntu 20.04 with Plasma
    R Version       : 3.6.3

### Steps to reproduce the problem

1) Run RStudio Desktop on Ubuntu 20.04 with Plasma.
2) Click on the top menu bar, e.g. `Tools`
    - The name of the menu is highlight in blue
    - However, the dropdown menu doesn't appear
3) Switch to another application
4) Switch back to RStudio
5) Click on another item in the top menu bar, e.g. `Help`
     - The menu now appears
6) Click on the previous item, e.g. `Tools`
     - The menu now appears, as well

### Describe the problem in detail

The dropdown menus don't work at first. One has to switch to another application, then back, for them to work.

### Describe the behavior you expected

The dropdown menus should always appear when the menubar is clicked.

Note that this is issue occurs in Plasma on Ubuntu 20.04. It works correctly with Gnome on Ubuntu 20.04, and with both desktops on Ubuntu 18.04.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by nbafrank** [comment]
Hi everyone, I have installed the latest version of RStudio server on an Ubuntu 20.04.4 LTS machine. Same issue as described here. Any ideas?

**Comment by nbafrank** [comment]
Sorry following here as well! I am using Safari. Have not tried with Firefox

**Comment by nbafrank** [comment]
Update! It is perfectly fine with Firefox. It must be related to the latest Safari update then
