### ISSUE TITLE
The latest builds can't display HTML content in the Viewer

### ISSUE THREAD

**Issue by shrektan** [rstudio/rstudio#7590]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 1.4.706
    OS Version      :  Windows 10
    R Version       : R 4.0.0

### Steps to reproduce the problem

1. Prepare an enviroment: Windows 10 + RStudio IDE latest buids + Ivanti Softerware Monitor (LANDesk) + Trend Micro (Anti-virus)
1. Open RStudio IDE
1. Run `DT::datatable(iris)`
1. You will see the Viewer panel displays the following text *"/session/viewhtml3db85e6c1ed6/index.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A44006 not found"* but it should display a DT table

![image](https://user-images.githubusercontent.com/8368933/90357161-977bcf80-e084-11ea-99a1-b5c065df5b3c.png)

Note, I don't think it's reproducible without such specific enviroments (Trend micro + LANDesk), as I've tested on my Mac with a virtual machine running the Windows 10, RStudio IDE works good there.

### Describe the problem in detail

It's not the first version that I realized this issue. Version 1.4.244 (built on 2020.4.27) works good. However, after that version (maybe one or two months later), I can't display the HTML content in the Viewer panel any longer (I may have tried two or three versions in total).

### Describe the behavior you expected

It should works good.

I know a not reproducible example for you is difficult to solve, especially issues with those anti-virus software... 

However, any ideas / guesses about why of this issue happening? 

Thanks!

**Comment by jmcphers** [comment]
This is a known issue with R 4.0.0 (exactly). Please update R to 4.0.2 to resolve it:

https://cran.r-project.org/bin/windows/base/

Let us know if that doesn't resolve the problem!

**Comment by shrektan** [comment]
@jmcphers  Thanks a lot for your answer! I can confirm upgrading to R 4.0.2 will fix this issue!

**Comment by jmcphers** [comment]
Great, glad to hear it!
