### ISSUE TITLE
Data's font in viewer pane is serif instead of non-serif

### ISSUE THREAD

**Issue by ndoyle-1** [rstudio/rstudio#7593]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      : macOS Catalina
    R Version       : 4.0.0

### Steps to reproduce the problem
n/a
### Describe the problem in detail
Text in DataTables shown in the data viewer and in exported html files are displayed in a serif font.
### Describe the behavior you expected
A sans-serif font.

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ndoyle-1 Thank you for filing this issue. I see the serifed fonts when knitting an R markdown file to HTML. However, the font of the text in the data viewer is sans-serifed. Can you provide the code you're running and a screenshot? FWIW, I ran
```
View(iris)
View(data.table::as.data.table(mtcars))
```

**Comment by ndoyle-1** [comment]
Apologies: I misidentified the pane - it's in the viewer pane on the tab bottom right, screen grab below.
![Screenshot 2020-08-17 at 20 10 39](https://user-images.githubusercontent.com/53840168/90434737-d8e09f00-e0c5-11ea-88ab-18750827b77b.png)

**Comment by ndoyle-1** [comment]
Code here with the iris data, screen grab below:

library(DT)
datatable(iris, options = list(pageLength = 5))
![Screenshot 2020-08-17 at 21 34 08](https://user-images.githubusercontent.com/53840168/90441779-768d9b80-e0d1-11ea-8642-89116fc74a8a.png)

**Comment by ronblum** [comment]
@ndoyle-1 No problem! I do the came thing. That said—this is expected behavior. But I'll mark this for review, to see if there's a way to control the font.

**Comment by ndoyle-1** [comment]
Thank you. It is serif if save as web page is used. Is there a workaround?

**Comment by ronblum** [comment]
@kevinushey Do you know if there's a workaround for this? Thanks!

**Comment by kevinushey** [comment]
> Text in DataTables shown in the data viewer and in exported html files are displayed in a serif font.

If this issue occurs both in RStudio and in exported HTML files, it most likely indicates something odd with the system configuration. In other words, if the issue exists both within and outside of RStudio, it's unlikely to be an RStudio issue.

**Comment by ronblum** [comment]
Ah! The same occurs when running the same code in R, both GUI and terminal. I should have checked that.

**Comment by R-Hannibal** [comment]
@ndoyle-1 - the fact that this occurred both in the R GUI and in RStudio tells us this is not an issue which should be fixed on the RStudio side. 

The issue should be filed on the DT package.

**Comment by amholtz** [comment]
@ronblum I am having the same issue as you describe here. Did you ever find a solution?

**Comment by ronblum** [comment]
@amholtz Unfortunately, this is the behavior in R, outside of RStudio, so we have no control over it. If you run the same code in standalone R, you'll see the same behavior.
