### ISSUE TITLE
RPubs: unexpected behavior when trying to publish update using non-rendered Markdown 

### ISSUE THREAD

**Issue by datalowe** [rstudio/rstudio#7594]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.3.1073
    OS Version      : Mac OSX Mojave 10.14.6
    R Version       : 4.0.2

I'm not entirely certain if this should strictly count as a bug, but it appears to the user as a bug and it seems odd to consider it a feature request.

### Steps to reproduce the problem
1. Create a .Rmd document ('New File -> R Markdown...' works fine for reproducing).
2. Knit the document to HTML (again, just using the default template here works for reproducing).
3. Publish the document to RPubs, using the "Publish" button in the window with the rendition of the knitted document.
4. Enter the details for the document on RPubs (description+slug).
5. Close the RStudio window with the knit rendition.
6. Edit something in the Markdown document, e. g. remove and add some text, **without using Knit to HTML**.
7. Click the Publish button **at the upper right of the subwindow with your raw markdown text/script**
8. You're shown a dialog which suggests you can "Update Existing" (RPubs document). Click "Update Existing".
9. The dialog shows it's loading, with the text "Uploading document to RPubs...".
10. A new browser window/tab is opened with the RPubs document, but the changes you made in step 6 haven't been made, and you can tell by the "last update" time that a new document was never really uploaded (or at least, made to replace the previous document).

### Describe the problem in detail
To be very clear, the problematic behavior appears when using the dialog produced by clicking the button in the screenshot below, after having previously uploaded a HTML rendition of the document to RPubs:

<img width="1221" alt="problematic_button_rstudio_publish" src="https://user-images.githubusercontent.com/65363390/90408281-edae3a00-e0a7-11ea-81d4-5798aea7f688.png">
(so, I'm not talking about the "Republish" button in the window that's produced after running "Knit to HTML" - that works as expected AFAIK)

The problem is that to the user, it appears as though a new document is being uploaded, based on the Markdown document. In reality, if I understand correctly, the "publish" button simply uploads the most recent HTML rendition of the markdown, which means that any changes done after the rendition will not be uploaded. 

### Describe the behavior you expected
I expected RStudio to publish a document (new rendition) based on my current Markdown. I am not alone in being confused by RStudio's behavior here: see e. g. [this SO thread](https://stackoverflow.com/questions/36118952/update-r-presentation-in-rpubs-instead-of-creating-a-new-presentation), [this one](https://stackoverflow.com/questions/29571785/replacing-existing-rpubs-document-with-a-newer-version) and [this one](https://stackoverflow.com/questions/38710265/updating-existing-report-in-rpubs). As can be seen from the threads, some users even seem to come to the conclusion that it's not possible to easily update RPubs documents, instead opting for creating a new document entirely on RPubs. I don't know if this was in fact necessary in previous RStudio versions, but in either case it seems that many are still missing out on the update functionality.

### Possible solutions
I tried to look around at the code and I realized that the way things function aren't necessarily the problem, rather it's what expectations the users form. I think these two solutions might work, with the latter being preferable IMO but requiring some more work:
#### Possible Solution 1
Change the dialog box' message (line 113 of [this .java file](https://github.com/rstudio/rstudio/blob/3fdda38e9a78a984a25c44e1672cf0869fad19cd/src/gwt/src/org/rstudio/studio/client/common/rpubs/ui/RPubsUploadDialog.java)) from "This document has already been published on RPubs. You can choose to either update the existing RPubs document, or create a new one." to something like "This document has already been published on RPubs. You can choose to either update the existing RPubs document, or create a new one. Please note that this uploads your latest rendition/knit of the document, so make sure to use 'Knit to HTML' before upload." (this message might seem a bit off to users who have indeed knitted to HTML, and are using the "Republish" button in the rendition window)

#### Possible Solution 2
Set RPubs to send back a specific error if the user submits a document that is exactly the same as the previous one. I assume that on its side, RPubs already controls for this and skips replacing the document, since the "update time" doesn't change (see "steps to reproduce" above). So wherever this check occurs, an error could be attached to the response sent back to the user's computer. RStudio would then have to check for this error in the response, I'm guessing this would be added around line 124 of [the RPubsUploader.java file](https://github.com/rstudio/rstudio/blob/3fdda38e9a78a984a25c44e1672cf0869fad19cd/src/gwt/src/org/rstudio/studio/client/common/rpubs/RPubsUploader.java), since there already is a check for upload errors there. The difference of course is that additional logic related to this specific type of error would be needed. Either way, if this error could be checked for, an error message like "Upload error: It appears that you are trying to upload a previously uploaded version of your document. If you have made changes to your Markdown document, please Knit to HTML before republishing." could be shown in a dialog to the user.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report (not a crash)
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@datalowe Thank you for filing the detailed issue! The step-by-step reprex was very helpful for reproducing it (RStudio Desktop 1.4.703 on MacOS 10.15.6). We'll review this issue as we continue development of RStudio.

Note: the same occurs when publishing to RStudio Connect.
