### ISSUE TITLE
Better highlighting for matching bracket

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#7599]
Suggestion:
1) Increase default visibility of matching bracket highlight
2) Apply rsTheme setting for bracket matching (setting exists but isn't applied)
3) Add highlighting to bracket being matched at cursor position

Currently the bracket matching highlight is rather hard to find, as it defaults to a grey and has no other features:

![image](https://user-images.githubusercontent.com/25590353/90431795-ce52e500-e086-11ea-989e-ad631fcfa05b.png)

It would be very helpful if the matching bracket highlight color was much more visible. 

I'd suggest that the default be adjusted so that both brackets become bold and perhaps underlined and the matching one should also get a more noticeable background color instead of the light grey.  The reason for bold/underline for both the one the cursor is next to and the matching one is that when you have several parens next to each other, ie `))))`, and the cursor is between them, it isn't obvious whether the matching bracket is matched to the one on the left or the right of the cursor.

Additionally, while there is a setting in the rsTheme file that should adjust this (`.ace_marker-layer .ace_bracket`), it doesn't appear that RStudio implements it.  It would be great if this could be fixed as well.

Related to #1888

**Comment by ronblum** [comment]
@jzadra Thank you for adding this ticket!

**Comment by jzadra** [comment]
Update:

the rsTheme does affect the bracket highlight, it's just in a different location that specified at https://rstudio.github.io/rstudio-extensions/rstudio-theme-creation.html

The `.ace_bracket` `background-color:` setting will affect this.

**Comment by ideamotor** [comment]
I think it would be great to have this as a GUI option. I can barely see the default. Also, have you seen this?

![](https://user-images.githubusercontent.com/4662568/71432977-717d7580-2717-11ea-9c2e-f76c811e6f0d.gif)

Is something like that even possible? The lines make it incredibly easy to read.

**Comment by jzadra** [comment]
> I think it would be great to have this as a GUI option. I can barely see the default. Also, have you seen this?
> 

> 
> Is something like that even possible? The matching colored lines make it incredibly easy to read.

This would be awesome!

**Comment by ronblum** [comment]
@ideamotor Cool idea—can you open a new issue for it, so that we can track the two (related) requests separately? Thanks!
