### ISSUE TITLE
Environment pane: add ability to sort objects by time last assigned

### ISSUE THREAD

**Issue by stragu** [rstudio/rstudio#7602]
It would be very helpful to be able to sort objects in the Environment panel/tab by "last created/updated" or "last assigned" (not sure of the best terminology here...). That would allow users to have the most recent objects pop up at the top of the list, particularly handy when dealing with numerous objects.

It would add an extra column to the Environment panel's grid view, which might make it too busy and might benefit from also adding extra options for customisation (i.e. showing/hiding columns, and changing column widths - which is only available in the list view).

Here is a related issue about improving the Environment panel: https://github.com/rstudio/rstudio/issues/6507

RStudio version 1.3.1073
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Comment by ronblum** [comment]
@stragu Thank you for the thoughtful feature request!

**Comment by stragu** [comment]
My pleasure, @ronblum !
The tag should probably be "environment pane" though, instead of "data viewer". :slightly_smiling_face: 

https://github.com/rstudio/rstudio/labels/environment%20pane

**Comment by ronblum** [comment]
@stragu D'oh—thank you for the correction!
