### ISSUE TITLE
when navigating to rmd rendering errors, current mode (visual vs. source) should be respected

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7603]
Currently the user is always switched to source mode when navigating to an error.

**Comment by jjallaire** [comment]
@jmcphers What do you think about targeting this one for preview?

**Comment by jmcphers** [comment]
I don't think it's critical since navigation still goes to the error, but I'll take a look once I've got https://github.com/rstudio/rstudio/issues/7581 buttoned up.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
