### ISSUE TITLE
highlightUI highlights elementsthat aren't visible

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#7607]
### System details

    RStudio Edition : Server Pro
    RStudio Version : 1.3.1056-1
    OS Version      : Ubuntu 18.04
    R Version       : 3.6

### Steps to reproduce the problem

1. File > New Rmarkdown file (with the default starter template)
2. Shorten the file editor so that only the top ~10 lines are visible
3. Run the following in the console:

```
    rstudioapi::highlightUi(
      list(
        list(
          query=".rstudio_chunk_cars .rstudio_run_chunk"
        )
      )
    )
```

Observe that the location of the play button is highlighted down in the console. If you scroll the source editor down, it then becomes appropriately highlighted.

### Describe the behavior you expected

Highlight wouldn't be visible until the element in the source editor is visible.

**Comment by ronblum** [comment]
Reproducible in 1.4.703 on MacOS 10.15.6, as well. The highlighting is sticking to the right place in the source editor, but it's not hiding like it should: Scrolling back up in the source editor causes the highlight box to move down with the button until it's back on the console pane.
