### ISSUE TITLE
allow project-specific Python configuration

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7610]
https://github.com/rstudio/rstudio/pull/7497 made it possible to customize the Python interpreter used by `reticulate` globally; however, we should also consider allowing for per-project versions of Python.

Implementation note: we should consider how this would play together with projects using `renv`, since `renv` has its own notion of the project-default version of Python.

**Comment by melissa-barca** [comment]
Verified in 1.4.1013
