### ISSUE TITLE
cannot load CSV from URL (unable to load internet.so)

### ISSUE THREAD

**Issue by drammock** [rstudio/rstudio#7613]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      : Xubuntu 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem

```R
url_ <- "https://github.com/phoible/dev/blob/master/data/phoible.csv?raw=true"
col_types <- readr::cols(InventoryID='i', Marginal='l', .default='c')
phoible <- readr::read_csv(url(url_), col_types=col_types)
```

### Describe the problem in detail

loading the remote dataset fails with this error:

```
Error in url(url_) : internet routines cannot be loaded
In addition: Warning message:
In url(url_) :
  unable to load shared object '/opt/miniconda3/envs/rdev/lib/R/modules//internet.so':
  /opt/miniconda3/envs/rdev/lib/R/modules//../.././libssl.so.1.1: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0
```

Additional info that may be relevant (i.e., it works in a system terminal):

```console
$ echo $RSTUDIO_WHICH_R 
/opt/miniconda3/envs/rdev/bin/R
$ R --version
R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
<license info omitted for brevity>
$ Rscript -e "url_ <- 'https://github.com/phoible/dev/blob/master/data/phoible.csv?raw=true'; col_types <- readr::cols(InventoryID='i', Marginal='l', .default='c'); phoible <- readr::read_csv(url(url_), col_types=col_types); head(phoible)"
# A tibble: 6 x 48
  InventoryID Glottocode ISO6393 LanguageName SpecificDialect GlyphID Phoneme
        <int> <chr>      <chr>   <chr>        <chr>           <chr>   <chr>  
1           1 kore1280   kor     Korean       NA              0068    h      
2           1 kore1280   kor     Korean       NA              006A    j      
3           1 kore1280   kor     Korean       NA              006B    k      
4           1 kore1280   kor     Korean       NA              006B+0… kʰ     
5           1 kore1280   kor     Korean       NA              006B+0… kˀ     
6           1 kore1280   kor     Korean       NA              006C    l      
# … with 41 more variables: Allophones <chr>, Marginal <lgl>,
#   SegmentClass <chr>, Source <chr>, tone <chr>, stress <chr>, syllabic <chr>,
#   short <chr>, long <chr>, consonantal <chr>, sonorant <chr>,
#   continuant <chr>, delayedRelease <chr>, approximant <chr>, tap <chr>,
#   trill <chr>, nasal <chr>, lateral <chr>, labial <chr>, round <chr>,
#   labiodental <chr>, coronal <chr>, anterior <chr>, distributed <chr>,
#   strident <chr>, dorsal <chr>, high <chr>, low <chr>, front <chr>,
#   back <chr>, tense <chr>, retractedTongueRoot <chr>,
#   advancedTongueRoot <chr>, periodicGlottalSource <chr>,
#   epilaryngealSource <chr>, spreadGlottis <chr>, constrictedGlottis <chr>,
#   fortis <chr>, raisedLarynxEjective <chr>, loweredLarynxImplosive <chr>,
#   click <chr>
```

### Describe the behavior you expected

Remote dataset would be loaded into the variable `phoible`.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] ~~If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report~~ N/A
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@drammock Thank you for raising the issue!  I can't reproduce it, though, on Ubuntu 18.04 and 20.04, RStudio Desktop and  Server. What version of `readr` are you using?

**Comment by drammock** [comment]
```
packageVersion('readr')
[1] ‘1.3.1’
```

**Comment by drammock** [comment]
Though again, I should reiterate, the example works in an R REPL in a system terminal window.  It's only within RStudio that it fails.

**Comment by ronblum** [comment]
@drammock Yep, thanks for the R info! And I'm using the same version of `readr`, so that's not it. OK—in that case, we'll review this as we continue development of RStudio.

**Comment by drammock** [comment]
Not sure if this is helpful, but here's a bit more system info:

```console
$ find /opt/miniconda3 -name internet.so
/opt/miniconda3/pkgs/r-base-4.0.2-h95c6c4b_0/lib/R/modules/internet.so
/opt/miniconda3/pkgs/r-base-4.0.2-he766273_1/lib/R/modules/internet.so
/opt/miniconda3/envs/rdev/lib/R/modules/internet.so
$ find /opt/miniconda3/envs/rdev -name *libssl*
/opt/miniconda3/envs/rdev/lib/libssl.so
/opt/miniconda3/envs/rdev/lib/libssl.so.1.1
/opt/miniconda3/envs/rdev/lib/pkgconfig/libssl.pc
```

**Comment by jmcphers** [comment]
What does your `PATH` and `LD_LIBRARY_PATH` look like in the console and inside RStudio? The most likely cause of this problem is that the Conda environment is not fully configured inside RStudio.

**Comment by drammock** [comment]
In a terminal:

```console
$ echo $LD_LIBRARY_PATH

$ echo $PATH
/home/drmccloy/.rbenv/shims:/home/drmccloy/.rbenv/bin:/opt/miniconda3/envs/rdev/bin:/opt/miniconda3/condabin:/opt/node_global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

In RStudio R console:
```R
R> Sys.getenv('PATH')
[1] "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/rstudio/bin/postback"
R> Sys.getenv('LD_LIBRARY_PATH')
[1] "/opt/miniconda3/envs/rdev/lib/R/lib:"
```

**Comment by drammock** [comment]
So yeah, looks like Rstudio is not aware of the fact that it's using a conda-managed version of R.  Any suggestions?

**Comment by drammock** [comment]
FWIW, I tried this:

```console
$ conda env config vars set LD_LIBRARY_PATH="/opt/miniconda3/envs/rdev/lib"
To make your changes take effect please reactivate your environment
$ conda deactivate
$ conda activate rdev
$ echo $LD_LIBRARY_PATH
/opt/miniconda3/envs/rdev/lib
```

Afterward, my MWE snippet above works in RStudio, but only if I launch RStudio from a terminal with that conda env activated.  If I launch from a system menu or dock, it still doesn't work.

**Comment by jmcphers** [comment]
This isn't a bug in RStudio but a conda/system config issue; the best way forward would be to configure your system to launch RStudio with the conda env pre-activated so that it loads the correct libraries.

**Comment by drammock** [comment]
> configure your system to launch RStudio with the conda env pre-activated so that it loads the correct libraries

This is easier said than done, since RStudio won't run `.bashrc` before launching, and so therefore won't pick up on the usual ways of causing a particular conda environment to activate.  Here's what I had to do to solve it:

1. add `alias rstudio=/path/to/my/custom/launcher/rstudio.sh` to my `.bashrc` file

2. edit `/usr/share/applications/rstudio.desktop` so that the `Exec` line says `/path/to/my/custom/launcher/rstudio.sh`

3. create (and make executable) `/path/to/my/custom/launcher/rstudio.sh` with these contents:

```
#!/bin/bash
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
conda activate rdev && rstudio &
```

Personally I find this pretty hacky, not least because it copy-pastes some conda init code that is supposed to be managed by conda, but is now frozen into my custom launcher script.  Also there's a risk that my changes to the `.desktop` file will get overwritten by future updates?  I know this can happen with system config files, anyway.  I would gladly hear any advice on how to do this more cleanly (or better yet, I would gladly hear that there is something more sophisticated than `RSTUDIO_WHICH_R` that would allow for more seamless support of conda-managed R installs).
