### ISSUE TITLE
Subscript out of bounds error thrown for tinytex missing bin dir

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#7615]
Getting error `Error in subbin[[1]] : subscript out of bounds` when opening an Rmd document in some installations of RStudio 1.3

### System details

    RStudio Edition : Server, maybe Desktop too
    RStudio Version : 1.3
    OS Version      : 
    R Version       : Multiple

### Steps to reproduce the problem
1. After installing Rstudio 1.3, delete the `bin` directory inside `tinytex::tinytex_root`
2. Restart Rstudio and open an Rmd file
3. Note the error in the console

### Describe the problem in detail
We don't properly handle an empty/missing `bin` folder in the tinytex root currently. 

### Describe the behavior you expected
An error is not thrown and ensure that tinytex is installed correctly.

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Customer ticket: 51382.

**Comment by adamconroy** [comment]
Customer ticket: 51487

**Comment by kevinushey** [comment]
Would be helpful to know how people are ending up in this state as well.

**Comment by melissa-barca** [comment]
Verified in 1.4.954.
