### ISSUE TITLE
Publish latest version of reticulate to CRAN

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7618]
Some of the features in RStudio v1.4 will require tools in the development version of `reticulate`. We should publish an updated version of `reticulate` to CRAN sometime before the v1.4 release.

**Comment by kevinushey** [comment]
reticulate 1.17 is now on CRAN.

**Comment by melissa-barca** [comment]
Verified reticulate 1.18 is available on CRAN.
