### ISSUE TITLE
Command Palette shows wrong shortcut for Focus Console

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7625]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.725
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
Bring up command palette, search for focus console. Note that keyboard shortcut for Move Focus to Console is shown as <kbd>Alt+X</kbd>.

### Describe the problem in detail
<kbd>Alt+X</kbd> is only the shortcut if Emacs mode is activated, but it is shown in the command palette no matter which editor mode is in force.

### Describe the behavior you expected
Ideally the <kbd>Ctrl+2</kbd> shortcut is shown, as this is always valid, and is what is shown in "modify keyboard shortcuts" dialog. Presumably there are other commands with editor-specific bindings falling prey to this, but haven't gone looking.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Superseded by https://github.com/rstudio/rstudio/issues/8735.
