### ISSUE TITLE
Search Python interpreters called python2 and python3 in addition to python

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7636]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.728
    OS Version      : Any (tried on MacOS 10.15.6 and Red Hat 8.2)
    R Version       : 4.0.2

### Steps to reproduce the problem

Tools -> Global Options -> Python -> Python Interpreter ->  Select

### Describe the problem in detail

RStudio finds binaries called `python`.

### Describe the behavior you expected

The IDE should also find `python2` and `python3`, as there may be multiple version of Python on the system, installed with these names.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/rstudio/pull/7782.

**Comment by melissa-barca** [comment]
Verified in 1.4.1013
