### ISSUE TITLE
Deleting the .gitignore file does not update in the files panel

### ISSUE THREAD

**Issue by samperman** [rstudio/rstudio#7640]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1056-1
    OS Version      : Ubuntu Xenail (via RStudio Cloud)
    R Version       :  4.0.2

### Steps to reproduce the problem
1. Create a project from git
2. delete the .gitignore file
3. Observe the file pane still shows the file
4. Refresh the file pane, file disappears

### Describe the problem in detail
When deleting `.gitignore` the file pane is not updated to reflect that the file is gone.

### Describe the behavior you expected
The file pane should be updated to no longer display the deleted file.

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by samperman** [comment]
![gitignore-files-pane](https://user-images.githubusercontent.com/361036/91051028-83d4e980-e5ed-11ea-972d-8b574331c14b.gif)

**Comment by ronblum** [comment]
@samperman Thank you for filing the issue and providing the screen capture! I can reproduce this in RStudio Desktop 1.4.727 on MacOS 10.15.6, as well. Also, I've confirmed that other hidden files—anything beginning with `.`—work as expected.

**Comment by lmayfield78** [comment]
This issue presents some problems for our testing.
