### ISSUE TITLE
Ensure that embedded Pandoc works on Mac OS <= 10.13

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7643]
Current builds of Pandoc (at least >= 2.9.2.1, I haven't tried earlier) crash when running Lua filters on MacOS <= 10.13:

https://github.com/jgm/pandoc/issues/6622

Note that default `rmarkdown::render()` runs a Lua filter so this means you can't render R Markdown in this configuration.

The pandoc builds are now done on GitHub actions, which uses Mac OS 10.15 (from what I can gather they used to be done on Travis which had more OS versions to choose from).

We need to do one of several things here:

(1) Rely on a subsequent Pandoc binary which is built in a way that it also works on <= 10.13

(2) Build our own version of Pandoc in a way compatible with <= 10.13

(3) Say that RStudio v1.4 doesn't support Mac OS <= 10.13 (seems like this isn't viable, but I don't know what our normal course of deprecation policy for old Mac OS versions is). Note that if we do this I think we should actually fail to load rather than load without support for R Markdown. I guess we could alternatively "disable" R Markdown with an error whenever someone tries to Knit/Render.

(4) Switch to an earlier version of Pandoc that still works.

While (4) is the least work I don't think it's viable because users are always eager to get the latest pandoc improvements to "do more" with their R Markdown documents. If we freeze at an earlier version we lose both these enhancements as well as potentially important bug fixes. The visual editor also relies on using more recent versions to get features like underline and (soon) tables with row and column spans.

(3) As I said doesn't seem viable.

As we are getting closer to the end game for v1.4 we may want to pursue building our own version (2). This shouldn't be too difficult as all of the build scripts are publicly available and should still work on older OS versions. Hopefully though (1) will happen and there will be a solution for the entire pandoc community.

**Comment by jjallaire** [comment]
It looks like Pandoc is now built on OS X 10.13. Should we drop support for OS X 10.12 in this release?

**Comment by kevinushey** [comment]
Given the pending release of Big Sur, we could take that as an opportunity to drop support for macOS 10.12 at that point.

**Comment by jjallaire** [comment]
It looks like Big Sur is scheduled for release in October so that would be before RStudio v1.4. Seems quite reasonable to drop 10.12 for the release then. 

There is now a binary of Pandoc 2.10 built on Travis for compatibility with 10.13 (see discussion at https://github.com/jgm/pandoc/issues/6622). 

@ronblum Could we test this binary on an instance of 10.13 ASAP so we can provide feedback on whether it works for our use case? (I just have 10.12, 10.14, and 10.15 available in my configurations). 

This should be the binary to test: https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-macOS.pkg

**Comment by gtritchie** [comment]
According to this page we already dropped support for macOS 10.12 for RStudio Desktop (Pro): https://rstudio.com/about/platform-support/.

**Comment by jjallaire** [comment]
Will keep this bug open until pandoc 2.10.2 (which will be built on OS X 10.13) is released and we can test and integrate it.

**Comment by jjallaire** [comment]
@ronblum Have you been able to do this test yet?

**Comment by jjallaire** [comment]
Underlying issue has been addressed and closed by pandoc, so we can close this as well.

**Comment by ronblum** [comment]
Confirmed on MacOS 10.13 High Sierra using the current version of Pandoc, 2.11.2. Verified both knitting in RStudio and by using `rmarkdown::render()` directly. After three requests to test this—sorry!
