### ISSUE TITLE
Manipulate settings UI not visible on first plot

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7644]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959

### Steps to reproduce the problem

See https://github.com/rstudio/manipulate/issues/4. In summary:

```r
library(manipulate)
library(mosaic)
mplot(mtcars)
```

### Describe the problem in detail

The plot does not get a manipulator (settings gear in upper left). 

![image](https://user-images.githubusercontent.com/470418/91093052-bdb5e800-e60d-11ea-861f-d4371c2de3e6.png)

### Describe the behavior you expected

The plot should have a manipulator:

![image](https://user-images.githubusercontent.com/470418/91093337-243b0600-e60e-11ea-9b1f-dfa18f28e635.png)

Author of https://github.com/rstudio/manipulate/issues/4 reports that this is a 1.3 regression (works in 1.1 and 1.2).

**Comment by eliocamp** [comment]
I'm seeing this bug on RStudio 1.4.1712.

**Comment by nicholasjhorton** [comment]
Are you using manipulate directly? Or one of the https://github.com/ProjectMOSAIC/mosaic helper functions?

**Comment by eliocamp** [comment]
manipulate directly. It fails with ggplot2 plots. To make it work I need to first run `manipulate()` with a base plot function. There I get the cogwheel and further calls to manipulate with ggplot plots work fine.

**Comment by nicholasjhorton** [comment]
Sorry to hear about the complications.  

Randy Pruim did some trickery (see https://github.com/ProjectMOSAIC/mosaic/commit/190b6d76a44b10c3d88620dd15e1f216824f0197) to work around this issue in RStudio. Essentially he ran a simple manipulate::manipulate() plot to reset things. It's a workaround for sure but it helped address the issue on our end. 

@jjallaire had noted correctly that manipulate hasn't been touched in ages so it might be tricky to track down the bug.

**Comment by eliocamp** [comment]
Yeah, I'm having to do the same. It's a shame :(

**Comment by AnBarbosaBr** [comment]
> manipulate directly. It fails with ggplot2 plots. To make it work I need to first run `manipulate()` with a base plot function. There I get the cogwheel and further calls to manipulate with ggplot plots work fine.

Thanks for your work around. I´m also having this problem after upgrading RStudio to version 1.4
