### ISSUE TITLE
Terminal mousewheel scroll logs "Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7645]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.736
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- Start the IDE, open the terminal pane, execute commands that produce enough output to enable scrollback (e.g. on Posix `seq 1 5000`).
- Open the browser console (dev tools)
- Scroll the terminal back with mousewheel to look at earlier output (in my case I'm using 2-finger gesture on Mac touchpad to scroll back)

### Describe the problem in detail
- The browser dev console shows instances of "Unable to preventDefault inside passive event listener invocation" error message

<img width="765" alt="2020-08-24_13-56-51" src="https://user-images.githubusercontent.com/10569626/91096340-bf35df00-e612-11ea-82c5-fd8b4f86c08f.png">

### Describe the behavior you expected
No errors logged for a routine action such as this.

Note, this is fixed in xterm 4.8.1: https://github.com/xtermjs/xterm.js/issues/3004

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.746, R Version - 4.0.2, Windows 10 - Desktop

The errors are no longer being thrown in the browser console log and a brief sanity check of terminal functionality passed successfully.
