### ISSUE TITLE
An unsaved and edited open file cannot be saved after adding and then removing a new source column to the IDE.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#7653]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.739
    OS Version      : Windows 10 x64
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Launch the IDE and open an R Script file > edit the file but do not save.
2. Add a new source column to the IDE and then close the new column.
3. Re-select the edited file and attempt to save the file.

### Describe the problem in detail
Attempting to save the file has no effect (menu options are greyed out, the save button is inert when selected, and using the save current file keyboard shortcut does nothing).

The issue goes away after a new file is opened or the IDE is closed/re-opened.

### Describe the behavior you expected
Files can still be saved after adding/removing an additional Source column.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Data loss... marking as backlog for 1.4

**Comment by melissa-barca** [comment]
Closed by #7701

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.768, R Version - 4.0.2, Windows 10 x64 - Desktop 

Source column buttons (including save) remain functional after opening and closing new source columns.
