### ISSUE TITLE
Incorrect (broken) user dictionatries path in RStudio 1.3

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#7658]
In RStudio 1.2, `rstudioapi::userDictionariesPath()` pointed to the directory, which contained dictionaries downloaded via:

![image](https://user-images.githubusercontent.com/12725868/91209933-250a8f80-e715-11ea-9a03-767412fef19c.png)

In RStudio 1.3 `rstudioapi::userDictionariesPath()` points to the **directory that does not exist**.

1. Is this a bug or is it an intentional behavior?
2. Does the issue belong here or is it the _RStudio_ issue?
3. What is the official programmatic way to access the correct user dictionaries' dictionary in RStudio 1.3 on all platforms? 

I use _Windows_ 10, R 4.0.2, _RStudio_ 1.3.1073, **rstudioapi** 0.11.

**Comment by GegznaV** [comment]
On Windows it is `%AppData%\Roaming\RStudio`, but still I need an official way to access it as the path is OS-dependent.

**Comment by GegznaV** [comment]
I think this issue could be a part of a more general issue to make RStudio return paths  (via `rstudioapi`) directories for configuration files, dictionaries and other important directories. See also rstudio/rstudioapi#176

**Comment by GegznaV** [comment]
On RStudio 1.4.1103, `rstudioapi::userDictionariesPath()` still does not return the expected directory.
It returns `"C:/Users/User/AppData/Local/RStudio/dictionaries"` on Windows.
Is this behavior going to be fixed?

**Comment by kevinushey** [comment]
It looks like there are three locations where dictionaries can be downloaded / placed:

1. The 'bundled' location, for dictionaries bundled with RStudio;
2. The 'update' location, where RStudio downloads updated definitions of its default dictionaries,
3. The 'user' location, where users can write and place their own custom dictionaries.

Unfortunately, we only provide API access for (1) and (3); e.g.

```
> rstudioapi::dictionariesPath()
[1] "C:/Program Files/RStudio/resources/dictionaries"
> rstudioapi::userDictionariesPath()
[1] "C:/Users/kevinushey/AppData/Local/RStudio/dictionaries"
```

I think we need a separate API to provide the location for the newly-downloaded or newly-updated dictionaries.

**Comment by kevinushey** [comment]
All that said -- I think it's worth stating that the dictionaries as downloaded through the UI here are not considered "user" dictionaries; they're instead updated versions of the bundled RStudio dictionaries. However, because the location in which RStudio itself is normally not writable post-install, we have to download and install those to a separate location.

`rstudioapi::userDictionariesDir()` is supposed to point to a location where users can create and place their own bespoke custom dictionaries.

**Comment by GegznaV** [comment]
Still, if third-party tools (like package `hunspell`) have to access those _updated dictionaries_, there should be an official way to do that in RStudio.

**Comment by astayleraz** [comment]
Verified in Version 1.4.1586-2 I am seeing the 3 new API calls provide the 3 paths. Example ```> .rs.api.bundledDictionariesPath()
[1] "/usr/lib/rstudio-server/resources/dictionaries"
> .rs.api.extraDictionariesPath()
[1] "/home/rstudio/.config/rstudio/dictionaries"
> .rs.api.userDictionariesPath()
[1] "/home/rstudio/.local/share/rstudio/dictionaries"```
