### ISSUE TITLE
Second monitor ON/OFF crashes Rstudio

### ISSUE THREAD

**Issue by IsadoraBM** [rstudio/rstudio#7673]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      :  Windows 7 Platform: x86_64-w64-mingw32/x64 (64-bit)
    R Version       :  4.0.2

### Steps to reproduce the problem
Get an LG TV, use a USB video card to connect HDMI to USB, this would reproduce my setup.
Rstudio crashes when second monitor is turned on AFTER Rstudio is opened.
### Describe the problem in detail
 If monitor is already on, then Rstudio is opened, it is fine, but Rstudio will crash if it is already open when the monitor is turned on. 
OK order: turn on monitor, open Rstudio
Bug order: Open Rstudio, turn on monitor

Turning off the second monitor makes Rstudio quit without prompt to save or session aborted alert. It simply terminates the process. Reopening produces saved draft.

### Describe the behavior you expected
This behavior did NOT occur before the newest Rstudio, the equipment in "reproduce the problem" section is the same as before Rstudio update. This issue makes turning off the monitor to take a break, then resuming work impossible. 

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

- I have also enabled crash reports in RStudio
[rdesktop.log](https://github.com/rstudio/rstudio/files/5139281/rdesktop.log)

**Comment by IsadoraBM** [comment]
This is still happening on 
Version 1.4.1103
"Wax Begonia" (458706c3, 2021-01-07) for Windows

**Comment by gtritchie** [comment]
Likely an issue with a graphics driver and/or QtWebEngine; the latter will be going away with #7389 so hopefully will fix this issue.

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If you're willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by ronblum** [comment]
Closing this as fixed by Electron. If you try out builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) and the issue persists, please let us know!
