### ISSUE TITLE
Include version numbers in the RSP release notes. 

### ISSUE THREAD

**Issue by scubastevew** [rstudio/rstudio#7680]
The ask here is to include version numbers in the Release Notes. 

For example, I found this fix: https://github.com/rstudio/rstudio/issues/3013 which clearly states what version it was verified in version 1.3.743. However, what's not clear based on that, is that if that fix is in MiddleMist Red or Water Lily. 

We do know that it should be in latest release (1.3.1073) based purely on version numbers but if a customer is on Middlemist Red or Water Lily, it's potentially unclear if that fix is in their particular version of RSP 1.3. 

As an aside, we also note that this particular fix didn't make into any of the release notes which makes it harder to determine where that change was introduced. For customer-facing changes is it possible to include those in release notes too? It gives us more ammunition to ask a customer to upgrade to a version if the release notes contain a feature/fix that would resolve their issue instead of taking our word for it.

**Comment by jmcphers** [comment]
You can find a mapping of version numbers to release names on Tettra: https://app.tettra.co/teams/rstudio/pages/rstudio-release-code-names

The version is also in the release history: https://support.rstudio.com/hc/en-us/articles/200716783-RStudio-Release-History

All changes should be in the release notes; sorry we missed one!

If the above two links don't give you enough info, feel free to open an issue on rstudio.com to have the release notes upgraded (those are managed on rstudio.com, not in this repo).
