### ISSUE TITLE
Add 'rerun' button to jobs detail page

### ISSUE THREAD

**Issue by warnes** [rstudio/rstudio#7684]
I'm using 'jobs' (via 'run local job' or 'source as local job' to run regression tests.   Since I re-run the same job over and over, it would be nice to have a button on each row of the main jobs screen for 'rerun'.  (Also a mechanism to remove one specific job, not just all of them using the broom.).   It would also be nice to have a 'rerun' button inside the job output page.

**Comment by gtritchie** [comment]
Tracked by #5548, closing this as a dup.
