### ISSUE TITLE
Daily build: shortcut key ctrl-shift-F8 won't insert citation

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#7685]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.751
    OS Version      : Linux Mint 20 (~Ubuntu 20.04)
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Open Rmd file
1. Press ctrl-shift-F8 to enter visual editor mode
2. Place cursor somewhere, ready to insert citation
3. Press ctrl-shift-F8, the indicated shortcut key to insert a citation

### Describe the problem in detail

On pressing ctrl-shift-F8, the mode flips back to plain Rmd and no citation can be inserted.

### Describe the behavior you expected

The expected behaviour was:

- that 'insert citation' would use a unique shortcut key, not ctrl-shift-F8
- that a dropdown for citations would appear upon pressing the shortcut key for 'insert citation'

The ctrl-shift-F8 shortcut key is used both to toggle between plain and visual mode, and to insert a citation in visual mode. It appears that the former takes precedence, which is consistent IMHO, but this means that the indicated shortcut for inserting a citation is non-functional.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rstudio/commit/320d5cec0c93366013d6ee68444369cfb5539229
