### ISSUE TITLE
Inline code chunk output! (Visual Markdown Editor)

### ISSUE THREAD

**Issue by johnnybarrels** [rstudio/rstudio#7686]
Just throwing my hat in the ring for inline code output in the new Visual Markdown Editor!

Thanks so much for the visual editor, its great. Inline code chunk output would be amazing!

**Comment by jjallaire** [comment]
It's on the way: https://github.com/rstudio/rstudio/pull/7666

**Comment by jjallaire** [comment]
Closing this since the PR tracks the work and should be merged later this week.

**Comment by adamconroy** [comment]
Verified in 1.4.938
