### ISSUE TITLE
Additional source column sourcing wrong file

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#7688]
### System details

    RStudio Edition : Both
    RStudio Version : Version 1.4.752
    OS Version      : MacOS
    R Version       : 3.6

### Steps to reproduce the problem
1. create a new R file and save
2. add additional source column
3. create a new R file in the new source column.
4. click source in new source column
5. then click source in the original source column.

### Describe the problem in detail
1. The new source column file is being sourced even though the user clicked the original source column source button. The user has to click into the source pane first and then click "source" for the correct file to be sourced.
### Describe the behavior you expected
The correct file is being sourced

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1069
