### ISSUE TITLE
Shortcut for "Restart R session" from within RStudio

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#7695]
### System details

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6
Rstudio mode : desktop
Rstudio version : 1.3.1073

### Steps to reproduce the problem
On Mac Catalina, the following key sequence restarts R session : Command + Shift + 0(zero)

### Describe the problem in detail
The "Session" menu mentions the shortcut as Shift+Command+F10 to restart the R Session while it also restarts with Command + Shift + 0(zero)

### Describe the behavior you expected
Command + Shift + 0(zero) should not Restart R session since it's not mentioned anywhere nor its part of keyboard shortcuts.

This becomes an issue since Command + Shift + 0(zero) closely resembles Control + Shift + 0(zero) that is used to "Show All Panes" and results in a session restart in the middle of work! :-)

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![RStudio 1](https://user-images.githubusercontent.com/37381682/91788649-5bbb3b00-ec2a-11ea-8267-2a520c381c13.png)
<img width="609" alt="RStudio 2" src="https://user-images.githubusercontent.com/37381682/91788653-607fef00-ec2a-11ea-8f17-698e3abb3f9a.png">

**Comment by gtritchie** [comment]
As a workaround, if you delete the shortcut for Restart R Session (Shift+Cmd+F10), it also removes the hidden one. Same if you assign a new shortcut, that should prevent the hidden one from operating. Let me know if that isn't the case for you.

**Comment by vinaychuri** [comment]
Thanks for the workaround, I have deleted the default shortcut and now even the hidden does not work. 
Good to go! 👍

**Comment by gtritchie** [comment]
We did a poll and found that those who knew about this <kbd>Shift+Command+0</kbd> shortcut used it a LOT, and would be sad if it went away.

So the fix I made was to remove <kbd>Shift+Command+F10</kbd> altogether on Mac, so now <kbd>Shift+Command+0</kbd> is shown as the shortcut in the various UI locations, making it easier to hunt down and modify if you don't want it.

**Comment by astayleraz** [comment]
I verified in Version 1.5.104 that hitting Cmd+Shift+0 on Mac triggers Restart R, and is shown in shortcuts dialog, Session menu, command palette, and keyboard shortcut help. I also added a test for this checking via F10 on Linux to add coverage for that shortcut.  Closing issue.
