### ISSUE TITLE
Code completion for Rmd chunk options within visual mode

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7697]

**Comment by kfeinauer** [comment]
The code completion for the Rmd chunk options in visual mode works, but the suggestions are not the same as what you get in regular non-visual mode.

**Comment by kfeinauer** [comment]
![Nov-13-2020 15-17-26](https://user-images.githubusercontent.com/28230621/99122146-6a778400-25c3-11eb-81d8-6c96e35a2023.gif)

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1032
