### ISSUE TITLE
Update visual mode doc links once rstudio-web is deployed

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7698]
Merge this PR once rstudio-web is deployed: https://github.com/rstudio/rstudio/tree/feature/panmirror-doc-links

cc @jmcphers

**Comment by jmcphers** [comment]
Deployed and merged.

**Comment by jmcphers** [comment]
QA notes - this change just updates some help links to use our internal link redirector. The links updated should be relatively obvious from this commit: https://github.com/rstudio/rstudio/commit/2c304eab4c7ed32da04ab388d6e316e953bc7a2c

**Comment by kfeinauer** [comment]
Verified 1.4.1027
