### ISSUE TITLE
Error similar to Bug# 7652 for Void Tools Search Everything in Windows 10.

### ISSUE THREAD

**Issue by MonteShaffer** [rstudio/rstudio#7703]
```
01 Sep 2020 19:13:04 [rsession-Alexander Nevsky] ERROR system error 10053 (An established connection was aborted by the software in your host machine) [request-uri: /events/get_events]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:113; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:118

```

Similar to Bug #7652 ... not for OneDrive by Void Tools Search Everything for Windows 10.  When the "Drive of interest" was unselected as a real-time update, it seemed to stop Restarting RStudio.

It may also be linked to using file explorer to delete folders and then RStudio doesn't do a nice update, even after an RStudio Restart.  I believe it may be some folder-caching mechanisms behind the scenes.

**Comment by jmcphers** [comment]
Please fill out the bug template completely so we can help! You might also try a daily build since #7652 and several related bugs are closed there:

https://dailies.rstudio.com/
