### ISSUE TITLE
Clipboard data copied from data viewer not available in tabular format

### ISSUE THREAD

**Issue by MER-C** [rstudio/rstudio#7707]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1056
    OS Version      : Windows 10
    R Version       : 4.02

### Steps to reproduce the problem
View any data frame say `View(data.frame(x=c(1,2), y=c(3,4)))`. Select the data frame by clicking and dragging with the cursor and copy by pressing Ctrl+C. Paste into MS Word, Excel or Outlook.

Expected output: a table
Actual output: a new line (or in the case of Excel, nothing)

Pasting into a plain text editor confirms that there is data on the clipboard.

This is not #4574 - this issue deals with the existing ability to copy from the data viewer.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [NA] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
@ronblum - Confirmed the behavior as described by @MER-C (I'm on Windows 10, RStudio Desktop version 1.3.1093-1).
