### ISSUE TITLE
Virtual Scroller enabled console shows truncated content

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#7712]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4
    OS Version      :  Any
    R Version       :  Any

### Steps to reproduce the problem
1. Ensure that the Virtual Scroller feature is turned on in Global Options ("Limit console output to a subset...")
2. In the console perform the command as shown here: https://github.com/rstudio/rstudio/pull/7568#issuecomment-675010330
3. Note the oddly truncated content

### Describe the problem in detail
The data that is coming up from the server is coming in odd, non-contiguous chunks (this can be seen in the network pane). Even going to the `ConsoleProcess::onStdout` function shows that the truncation is happening a bit deeper down the line.

### Describe the behavior you expected
Ideally we get ALL of the data but there are incredibly degenerate cases where it'd lock up RStudio (for i in 1:99999999 etc) which is likely why we started doing this chunking in the first place. In which case if we could get it just to send the final chunk instead of disparate chunks that are intended to be trimmed anyway that would mimic the current functionality.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by adamconroy** [comment]
Little update on this. It appears that the data comes in differently depending on if it's running Desktop or Server. As far as I can tell Server operates totally fine. The CPP process correctly only sends up the data from the last thousand elements. In Desktop a few different `console_output` events are received (with the truncated data) but the Java side just overwrites the bad data as the new stuff comes in. Very curious.

**Comment by rich-rstudio** [comment]
verified on version 1.4.938 desktop
