### ISSUE TITLE
monospaced fonts, aren't

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7714]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073, 1.4.770
    OS Version      : macOS 10.15.6
    R Version       : R 4.0.0

### Steps to reproduce the problem

Copy and paste this into an editor in the Source pane:

```
════════════════════════════════════════════════════════════
────────────────────────────────────────────────────────────
```

### Describe the problem in detail

Observe that (at least, with Monaco, the default font) the two lines are of different lengths:

<img width="578" alt="Screen Shot 2020-09-02 at 3 58 03 PM" src="https://user-images.githubusercontent.com/1976582/92045323-18012800-ed35-11ea-915a-ff949a0a686e.png">

### Describe the behavior you expected

Both lines should be rendered with the same length.

This bug appears to have been introduced with the update from Qt 5.12.6 to Qt 5.12.8. (more specifically, it broke in Qt 5.12.6 -> 5.12.7, but we skipped that version)

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Also repros in Console, but not in the Terminal.

**Comment by gtritchie** [comment]
Also confirmed it is Mac-only (works fine on Linux and Windows desktop builds).
