### ISSUE TITLE
Windows installer: use current/previous path as default destination

### ISSUE THREAD

**Issue by realHenningLorenzen** [rstudio/rstudio#7715]
When I install RStudio as a non-admin user and subsequently upgrade the installation, for every upgrade I have to point the installer to the existing installation.

The default location (for non-admin) seems to be some user data directory, even if there is already something like `Computer\HKEY_CURRENT_USER\Software\RStudio\RStudio` present in the Windows registry.

![image](https://user-images.githubusercontent.com/61181314/92082380-c1dbc580-edc4-11ea-8c59-a664efdfa99c.png)

**Comment by gtritchie** [comment]
What technique are you using to perform the initial non-admin install?

**Comment by realHenningLorenzen** [comment]
🤔  I bypass the UAC with the ancient **RunAsInvoker** shim, e.g. in a PowerShell window:
```powershell
$env:__COMPAT_LAYER = "RunAsInvoker"
RStudio-1.4.869.exe
```
