### ISSUE TITLE
Daily build: shortcut key ctrl+shift+F12 just switches tab

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#7717]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.774
    OS Version      : Linux Mint 20 (~Ubuntu 20.04)
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Open Rmd file 
1. Press ctrl+shift+F12

### Describe the problem in detail

Nothing happens. If a second file is open as well, right next to the Rmd, focus switches to that tab when pressing ctrl+shift+F12.

### Describe the behavior you expected

ctrl+shift+F12 should switch to visual editor mode

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
@jjallaire I tested this in 1.4.938 and it looks like the `toggleRmdVisualMode` keyboard shortcut conflicts with `lastTab` and `lastTab` is executing instead.

**Comment by kevinushey** [comment]
Note: bindings are here;

https://github.com/rstudio/rstudio/blob/f23c1df50290b9e6f2bd9b2ecebca19b1c39bbf0/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L710-L711

vs.

https://github.com/rstudio/rstudio/blob/f23c1df50290b9e6f2bd9b2ecebca19b1c39bbf0/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L751

I think we should try to find a different binding for toggling visual mode.

**Comment by kfeinauer** [comment]
Verified on 1.4.1032
