### ISSUE TITLE
Daily build: filtering citations does not filter adequately

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#7719]
### System details

```
RStudio Edition : Desktop
RStudio Version : 1.4.774
OS Version : Linux Mint 20 (~Ubuntu 20.04)
R Version : 4.0.2
```

### Steps to reproduce the problem

1. Visual markdown editor: press ctrl+shift+F8
2. In the dialog box, go to a Zotero collection
3. In the 'search for citation field', type an author's name which should be rather unique in the Zotero DB.

### Describe the problem in detail

Still many records are shown after filtering. It may be that individual letters are being searched for, not words.

### Describe the behavior you expected

When entering a word which is unique in the database, only one record should remain.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
Thanks for reporting this. We are using approximate string matching for our search which won't result in unique/exact matching, but instead perform a weighted fuzzy search on Citekey, Author, Title, Publication, and Issue Date. If your search becomes unique enough, its possible that all the results but one will disappear, but typically I would expect there to be many matches, but sorted properly (e.g. the first item should be a great match).

If you're not seeing this, please do let me know as I can fine tune the approximation behavior and weighting and would be happy to do so to improve the search quality.

**Comment by florisvdh** [comment]
:+1: I can confirm that entries are properly sorted (in 1.4.823).
