### ISSUE TITLE
Calls to data viewer for the same object create a new tab each time

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7723]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.765 (also 1.4.627)
    OS Version      : MacOS 10.15.6 and Ubuntu 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem

In the conosole
1. `x <- cars`
2. `View(x)`
3. `View(x)`
4. `View(x)`

Alternatively, click on `x` In the Environment pane multiple times.

### Describe the problem in detail

Every time the data viewer is invoked, a new tab is created.

![image](https://user-images.githubusercontent.com/31009952/92121177-fa30d300-edc7-11ea-8b4d-5a05d3b2016d.png)

### Describe the behavior you expected

Only one tab should be created for an object, refreshed with each call.

This is a regression, as it is not an issue in RStudio 1.3.1073 or 1.2.5040.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by salim-b** [comment]
> Only one tab should be created for an object, refreshed with each call.

At this point it might be worth considering introducing an exception for this rule: When an object is named `.` – which is the case when piping `View()` – it would be convenient if an already existing tab wouldn't be refreshed but a new one created (manually setting `View(title = "...")` is tedious in such cases). Ideally this behaviour would be made opt-out (or opt-in) through RStudio's global options.

**Comment by gtritchie** [comment]
@salim-b Please open a new "enhancement" issue with your request, thanks.

**Comment by salim-b** [comment]
> @salim-b Please open a new "enhancement" issue with your request, thanks.

Ok, I've opened https://github.com/rstudio/rstudio/issues/7737

**Comment by kfeinauer** [comment]
Verified fixed RSP 1.4.940-1
