### ISSUE TITLE
Daily build: Default "Enter" behavior has changed in pop-out windows

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#7724]
### System details

    RStudio Edition : 
    RStudio Version : Daily 1.4.757
    OS Version      : Mac
    R Version       : 4.0.0

### Steps to reproduce the problem

In the Git pane, hit New Branch. Type in the branch name. Hit Enter/Return.

This used to automatically press the Create button for you.

Same problem happens with Find in Files. I open it with SHIFT+CMD+F, type in my search term, then hit Enter and it no longer automatically presses Find for me.

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Possibly fixed by 8e0e07a2 which is in 1.4.759 and newer.

**Comment by DavisVaughan** [comment]
Yes, looks like that did it! Thanks!
