### ISSUE TITLE
Replacing words across different directories in project fails (and crashes R)

### ISSUE THREAD

**Issue by AltfunsMA** [rstudio/rstudio#7732]
### System details

    RStudio Edition :  Server
    RStudio Version :   1.3.1073
    OS Version      :  Ubuntu 18.04.4
    R Version       :  3.6.3

### Steps to reproduce the problem
Attempt to replace words inside R scripts across different directories with the global search and replace function in RStudio.

### Describe the problem in detail
The first two images show output for a search and replace that failed with errors. The errors reported are rather cryptic. The diagnostic count of successes vs fails seems totally random: 64 vs 11, when actually nothing seems to have been replaced. Replacement didn't happen in the first file, either, although it reports no error. I was able to continue working normally afterwards.

When I try to replicate with just two R scripts containing an identical two-word phrase with one word to be replaced, the replacing pane gets stuck executing as in the third image below. Aborting it causes R to crash.

1
![image](https://user-images.githubusercontent.com/26325512/92189398-e2c61880-eea1-11ea-9221-df826092b0cb.png)
2
![image](https://user-images.githubusercontent.com/26325512/92189427-f7a2ac00-eea1-11ea-9f05-6b10259a21af.png)
3
![image](https://user-images.githubusercontent.com/26325512/92189819-faea6780-eea2-11ea-91fe-4b0bfccb4fc3.png)
### Describe the behavior you expected

Words to be replaced

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [NA ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
This should be fixed in the daily build from #8158
