### ISSUE TITLE
RStudio Desktop crashes with "Parent terminated" error

### ISSUE THREAD

**Issue by Anderson-Hicher** [rstudio/rstudio#7735]
### System details

    RStudio Edition : 
    RStudio Version : Version 1.3.1073
    OS Version      : 4.19.0-10-amd64 - Debian
    R Version       : R version 4.0.2

### Describe the problem in detail
It's my first time using the RStudio. I installed it following the indicated steps of the official website, but every time I tried to run a code, even a simple sum code, the RStudio crashes, in the log messages appear the following errors:
ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1371

### Describe the behavior you expected

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Anderson-Hicher Thank you for raising the issue! A couple of things:
1) We recently [released an update, version 1.3.1093](https://rstudio.com/products/rstudio/download/#download) of RStudio Desktop. Does the problem still occur with it? 
2) What happens if you [change to software rendering?](https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors) I'd be surprised if this were the issue, but I found a reference to a different bug (since resolved) that had a similar error.

Thanks!

**Comment by Anderson-Hicher** [comment]
@ronblum Thank you for responding to my issue.
I reinstalled the RStudio Desktop version 1.3.1093, and the problem still occurring. But folowing the second option you have offered, I changed the software rendering, on the settings of the RStudio, but surprisingle the error still ocurring. I searched for more info about this problem in the software rendering wille runing the RStudio Desktop, and try to force the rendering option via terminal wile initializing the program, using "QT_XCB_FORCE_SOFTWARE_OPENGL=1 /RStudio", and before that he start to function normally.

**Comment by Anderson-Hicher** [comment]
@ronblum Thank you for responding to my issue.
       1- I reinstalled the RStudio Desktop version 1.3.1093, and the problem stilled occurring. 
       2- I changed the software rendering, on the settings of the RStudio, but surprisingly the error stilled occurring. I searched for more info about this problem in the software rendering while running the RStudio Desktop, and tried to force the rendering option via terminal while initializing the program, using "QT_XCB_FORCE_SOFTWARE_OPENGL=1 /RStudio", and after that, he start to function normally. 

It's functioning normally now, but I still don't understand why the change of the rendering software does not work through settings and work by the command line.

Here is my OpenGL info:

OpenGL vendor string: nouveau
OpenGL renderer string: NV94
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.3 (Compatibility Profile) Mesa 18.3.6
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by ronblum** [comment]
@Anderson-Hicher Thank you for trying things out! We'll review this as part of our ongoing development, but at least in the meantime you have a workaround—which, if other users run into the same issue, will be helpful, so I appreciate it!

**Comment by Anderson-Hicher** [comment]
@ronblum  Thank you for your assistance, and I'm sorry for constantly keep closing and reopening the issue. I clicked many times on the wrong button. I hope that this was useful for others with the same problem.
