### ISSUE TITLE
unable to access index for repository https://cran.rstudio.com/src/contrib:  internet routines cannot be loaded

### ISSUE THREAD

**Issue by Liripo** [rstudio/rstudio#7745]
Dear:
  I installed Rstudio server using WSL2,and  installed R by conda.
 When I started the Rstuio server, I could not download the R package and encountered the following error.
![image](https://user-images.githubusercontent.com/54770415/92325775-b7992000-f07f-11ea-8a28-eebed4c3109a.png)
But I can download it by starting R under the command line
Thank you !

**Comment by Liripo** [comment]
Rstudio version:   1.3.1073 (Giant Goldenrod) for Ubuntu Bionic
```R
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS/LAPACK: /mnt/d/linux/software/miniconda3/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2
```

**Comment by kevinushey** [comment]
I suspect part of the issue relates to your using an Anaconda installation of R rather than one of the regular R binaries. That said, I don't think we'll be able to provide much support beyond suggesting you use an alternate download method; e.g.

```
options(download.file.method = "curl")
```

**Comment by Liripo** [comment]
Thank you!

**Comment by thesuperzapper** [comment]
If you are using RStudio Server and conda, you might need to start it with the `--rsession-ld-library-path=/opt/conda/lib` command line argument.

This is because RStudio ignores the servers `LD_LIBRARY_PATH` when starting R sessions.
