### ISSUE TITLE
Project user directory on VMWare virual session

### ISSUE THREAD

**Issue by edonnachie** [rstudio/rstudio#7752]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows 7
    R Version       :  4.0.2

### Steps to reproduce the problem

1. Log into a VMWare horizon virtual session, identified by a computer name that contains an automatically generated number
2. Open a project, thus creating a user project directory under .Rproj.user
3. Log out of the virtual session 
4. Start a new virtual session, identified by a new automatically generated computer name
4. Reopen the project

### Describe the problem in detail

I am using RStudio on a VMWare horizon virtual session. Each new session receives a new IP address and a new computer name with [automatically generated number](https://docs.vmware.com/en/VMware-Horizon-7/7.12/horizon-virtual-desktops/GUID-26AD6C7D-553A-46CB-B8B3-DA3F6958CD9C.html). 

RStudio stores user session data under `<project root>/.Rproj.user/<contextId>`, where `contextId` is defined by the user name and the session name. As a result, each new log in creates a new directory under .Rproj.user. The project status for the user is lost, and the .RProj.user accumulates junk. This is annoying and detrimental to the user experience.

RStudio 1.1 and 1.2 were used on the same VMWare system without such issues. It seems that the definition of the `contextId` changed with 1.3 (see also #6227).

### Describe the behavior you expected

As far as possible, user project data should be restored after starting a new virtual session with different computer name. At the very least, an accumulation of absolete directories under `.Rproj.user` should be avoided.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
IIUC, according to the linked PR, this is fixed in the latest v1.3 release (1.3.1073). https://rstudio.com/products/rstudio/download/#download

Do you see the same issue in the latest RStudio release?

**Comment by edonnachie** [comment]
We can try the latest release, but this is a different issue. The problem is not the migration from 1.2 to 1.3, but the behaviour under 1.3.

It seems contextId was introduced/modified with 1.3 (Commit: 6f42ceaabe323f8e064eb00ac27240df02eb8a03). How was the user identied in previous versions?

**Comment by kevinushey** [comment]
Older versions of RStudio did also create and store a context ID; this was created at:

```
%LOCALAPPDATA%\RStudio-Desktop\monitored\user-settings\user-settings
```

with a field called `contextIdentifier`. My understanding is that the first v1.3 release of RStudio had an issue where this context identifier was not properly migrated, and so new RStudio launches were treated as though they were launched by brand new users.

This setting is now called `context_id`, and is normally contained within a JSON file located at:

```
%LOCALAPPDATA%\RStudio\rstudio-desktop.json
```

That said, this context ID should still be shared by new sessions (assuming `%LOCALAPPDATA%` is "mirrored" to each virtual session).

**Comment by edonnachie** [comment]
Thank you for the information, that helps a lot. It seems that the %LOCALAPPDATA%\RStudio is lost after each session. Horizon is a bit tricky and I believe our admins needs to configure syncronisation of this local folder manually. 

This may take a few days to test, but I will report if it works.

**Comment by edonnachie** [comment]
I can confirm that this solves the problem with context_id. The session was restoring `%LOCALAPPDATA%\RStudio-Desktop` but not `%LOCALAPPDATA%\RStudio`
