### ISSUE TITLE
Enhancement of Pane-File window

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#7753]
A couple of enhancements can make the Pane-File window more handy and powerful:
1. File - right click: Add an option of “Open with system program”
2. File - right click: Add an option of “delete” the file
3. Add a column of “file type"; so files can be sorted by types.

![image](https://user-images.githubusercontent.com/11802171/92544893-d7595100-f203-11ea-8405-b168dd882be9.png)

Thanks.

**Comment by gtritchie** [comment]
Great ideas, thanks!

Note you can already sort by File Type but it isn't very obvious. Click above the file icons, and it will sort by file type:

<img width="414" alt="screenshot of Files pane with arrow pointing to file-type column header" src="https://user-images.githubusercontent.com/10569626/92639852-429d3480-f291-11ea-8db1-59f0fd817d82.png">
.
