### ISSUE TITLE
Code highlighting logic error for C: trailing backslash in inline comment

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#7754]
I learned today that a line-continutation `\` in C also works for inline comments:

https://stackoverflow.com/a/19405555/3576984

That is, this is valid syntax:

```
// this is a comment \
that continues on this line
```

But RStudio treats the second line as a separate expression:

![Selection_018](https://user-images.githubusercontent.com/7606389/92552614-1650cc00-f22f-11ea-9dce-efe6841c62ee.png)

I'm using a daily build: "Wax Begonia" (0c5a82ea, 2020-08-16) for Ubuntu Xenial

Also note, that I don't write code like this, nor have I seen code like this written by anyone else (including the R source: `grep -Er "//.*[\]\s*$" ~/svn/R-devel --include=*.{c,h}`), so I don't think it's a huge priority.

**Comment by ronblum** [comment]
@MichaelChirico Interesting—thank you for letting us know!
