### ISSUE TITLE
Problem with the Reload App button

### ISSUE THREAD

**Issue by herambgadgil** [rstudio/rstudio#7762]
Hello,

I am facing this issue with the Reload button for `RStudio - 1.3.1056` and recently on `RStudio - 1.4.x`

Error : `error (TypeError) : Cannot read property 'id' of null`

![image](https://user-images.githubusercontent.com/15884914/92698862-82841a80-f36a-11ea-80c5-3cbeac45a55e.png)

I have mentioned the steps to reproduce the error in the attached folder's `app.R` file. Below are the other required details

```
sessionInfo()

R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       digest_0.6.25    withr_2.2.0      later_1.1.0.1    mime_0.9         R6_2.4.1         jsonlite_1.7.0  
 [8] xtable_1.8-4     magrittr_1.5     rlang_0.4.7      promises_1.1.1   tools_3.6.3      tinytex_0.25     rsconnect_0.8.16
[15] httpuv_1.5.4     xfun_0.16        fastmap_1.0.1    compiler_3.6.3   Rserve_1.7-3.1   htmltools_0.5.0 
```
![image](https://user-images.githubusercontent.com/15884914/92699440-34bbe200-f36b-11ea-9684-5475bc7c916d.png)

First mention of this bug : https://community.rstudio.com/t/reload-app-not-working-on-newest-ide-release/75501

Additional Snaps that might be helpful: 

1 of 2 
![image](https://user-images.githubusercontent.com/15884914/92700083-07236880-f36c-11ea-8a3e-dcfc3d4c0982.png)

2 of 2 
![image](https://user-images.githubusercontent.com/15884914/92700201-29b58180-f36c-11ea-8614-2af237f600e0.png)

[reprex-example.zip](https://github.com/rstudio/rstudio/files/5200077/reprex-example.zip)

Thanks!
Heramb

**Comment by ronblum** [comment]
@herambgadgil Thank you for bringing over the problem from Community! We're considering it for RStudio 1.4 Wax Begonia.

**Comment by jmcphers** [comment]
I reproduced this on 1.4.814. I'll take a look.

**Comment by R-Hannibal** [comment]
@herambgadgil, thanks again for finding and reporting this (and other 😊) issues. As well as for providing the example file, makes our job easier and we appreciate it.

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by herambgadgil** [comment]
@R-Hannibal - Tested and Verified.. All is well!

Thanks!
Heramb
