### ISSUE TITLE
Unable to establish connection with R session raised by "src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244"

### ISSUE THREAD

**Issue by yuliu426** [rstudio/rstudio#7772]
### System details

    RStudio Edition :  Desktop
    RStudio Version :   1.3.1073 (details below)
    OS Version      :  windows 10
    R Version       :  4.0.2

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

### Steps to reproduce the problem

create R markdown or execute some commands, the IDE will occasionally throw this failure (but sometimes it succeeded).

### Describe the problem in detail

So I try to look at the log under RStudio-Desktop\log\rsession-YULIU which shows the following

11 Sep 2020 17:18:13 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:19:36 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:19:41 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:19:51 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:19:56 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:20:13 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:20:16 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:20:19 [rsession-YULIU] ERROR system error 10053 (????????????????????) [request-uri: /events/get_events]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:113; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:118
11 Sep 2020 17:20:24 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:20:30 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:20:36 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:20:36 [rsession-YULIU] ERROR system error 10053 (????????????????????) [request-uri: /events/get_events]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:113; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:118
11 Sep 2020 17:20:49 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:21:31 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:21:38 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244
11 Sep 2020 17:22:23 [rsession-YULIU] ERROR system error 258 (????????); OCCURRED AT void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionListenerImpl<class rstudio_boost::asio::ip::tcp>::handleAccept(const class rstudio_boost::system::error_code &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:244

### Describe the behavior you expected

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by yuliu426** [comment]
some related issues and solution (use older version)
https://community.rstudio.com/t/error-unable-to-establish-connection-with-r-session-on-windows-pc/45732
https://community.rstudio.com/t/help-error-unable-to-establish-connection-with-r-session/51303
https://community.rstudio.com/t/2019-error-unable-to-establish-connection-with-r-session/44076/3

**Comment by ronblum** [comment]
@yihui Thank you for filing the issue! Can you provide a sample file/code as well as commands that result in the error, so that we can try to reproduce this? Thanks!

**Comment by yihui** [comment]
@ronblum You probably meant `@yuliu426` instead of `@yihui` :)

**Comment by yuliu426** [comment]
@ronblum  the error just popping out randomly. For example, when typing in' 1+1', it sometimes runs correctly, sometimes, for the same command, it just shows that error. 
I download an old version, turned out that one works smoothly without this error continuously popping out.
