### ISSUE TITLE
Error: Rstudio unable to establish connection with r session #5367

### ISSUE THREAD

**Issue by Aduragbemi123** [rstudio/rstudio#7778]
I tried using my R software to create a consensus map. However, on opening my R software it keeps popping the message Rstudio unable to establish a connection with r session. I have tried all possible solutions which I surfed from the web and also some on GitHub but all to no avails. Please I need help.

**Comment by ronblum** [comment]
@Aduragbemi123 I'm sorry you're running into this issue. Can you provide the following information about your environment? Thanks!

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by Aduragbemi123** [comment]
RStudio Edition : Desktop 
RStudio Version : the latest version
OS Version      : windows 10
R Version       : 4.0.2

**Comment by Aduragbemi123** [comment]
Sorry I believe am using 
RStudio Edition :

**Comment by cathblatter** [comment]
@ronblum  - sorry to barge in, but I encounter the same problem with:

RStudio Edition : Desktop
RStudio Version : 1.3.1093
OS Version : Mac OS X 10.15.6
R Version : 4.0.2

I also irregularly get the issue with the Error message displayed above (unable to establish connection), but more often I just get a blank console - but when typing some code (e.g. `sessioninfo::sessionInfo()`) the connection to R is there . The whole things happens in irregular intervals and I checked multiple blog-posts on community.rstudio.com - I re-installed both R and RStudio including re-setting the desktop-state (https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State) 

I don't have any antivirus software installed, no firewall, and it happens in various different wlans/lans and with/without vpn. 

Actually, I can fully work, but at this point I'm really curious to understand what is happening :) I also have a student with the same issue (also on Mac OS X). Thanks for any inputs!
