### ISSUE TITLE
Access to add-ins menu from popped-out source window

### ISSUE THREAD

**Issue by francisbarton** [rstudio/rstudio#7779]
This is a new issue as a way of re-opening #1836 - I thought this would be better than commenting on a closed issue.

I like working with a source document in a separate (popped-out) window. However it's not possible to access the add-ins menu from this window, for example to use the styler add-in to reformat code (though keyboard shortcuts to add-in functions still work, of course).

There are quite a few add-ins now that relate to the active file, helping the user to do things like style or wrap text, knit or render a document or insert various pieces of code. However as soon as you switch back to the main RStudio window, the "active file" switches to any file you have open in the main window.
It doesn't seem reasonable to have to assign and learn a keyboard shortcut for every add-in function so that they can be used in a popped-out window.
Thank you.

**Comment by ronblum** [comment]
@francisbarton Thank you for filing the request. We'll review this as we continue development. I can't guarantee that we'll add that, but review and consider your request!

**Comment by francisbarton** [comment]
Just adding a thought - no action or response required.
I don't have a working daily build of RStudio, only the stable version. So I haven't tested if the new extra Source pane (within main window) feature contains access to the add-ins menu. Worth checking.

**Comment by jmcphers** [comment]
This is now possible using the Command Palette, which is accessible in source windows.
