### ISSUE TITLE
"Find in Files" incorrectly matches the sequence of symbols

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#7780]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.3.1091
    OS Version      : Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Use this project: [rstudio-search-issue.zip](https://github.com/rstudio/rstudio/files/5217332/rstudio-search-issue.zip)
2. Open the global "Find in files" window and type `[Sąsaja tarp kategorinių kintamųjų]` as shown:
![image](https://user-images.githubusercontent.com/12725868/93066882-2a5b5a00-f683-11ea-803f-ffbe367f7887.png)
3. Push the "Find" button.

### Describe the problem in detail

The result in the "Find in Files" tab does not match the sequence of symbols correctly (`[Sąsaja tarp kategorinių kintamųjų]`):
![image](https://user-images.githubusercontent.com/12725868/93067274-ae154680-f683-11ea-8814-c42ffff5e1d0.png)

**Context**

I was trying to fix cross-references in a `bookdown` project. There were more matches in my project and most of them were correct. But some were not. So in some situations, it is possible that not all matches are incorrect.

### Describe the behavior you expected

I expect the exact match of the sequence of interest in all situations.

Related: #6819

***

<details>
<summary>Checkboxes</summary>

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
</details>

**Comment by ronblum** [comment]
Thank you @GegznaV for filing the issue! I can reproduce it in RStudio Desktop 1.3.109-2 on MacOS 10.15.6. We'll review it as we continue developing RStudio.

**Comment by GegznaV** [comment]
Cannot reproduce anymore
