### ISSUE TITLE
Preview knitted odt in Open Office Writer

### ISSUE THREAD

**Issue by moacirp** [rstudio/rstudio#7783]
When I knit an Rmd to an odt document, it is previewed in MS Word. As pointed out to me by cderv in https://community.rstudio.com/t/can-t-preview-in-open-office-writer-only-in-ms-word/80302/9, this is the intended behaviour of R Studio. I think it may be useful if there is a way to configure this behaviour and have the option to choose Open Office Writer to preview ODT files. Thanks.

**Comment by ronblum** [comment]
@moacirp Thank you for the suggestion! We'll review it as we continue development of RStudio. Also, thank you for including a reference to the Community discussion!
