### ISSUE TITLE
excessive 'set_client_state' RPCs sent periodically

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7785]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.813
    OS Version      : macOS 10.15.6
    R Version       : 4.0.2

### Steps to reproduce the problem

Start the IDE, and leave it idle for a little while. Then, open the request log.

### Describe the problem in detail

A large number of `set_client_state` RPCs are made, evidently to update the window splitter position. However, the splitter position is not actually changed for each call.

<img width="956" alt="Screen Shot 2020-09-14 at 1 32 53 PM" src="https://user-images.githubusercontent.com/1976582/93135365-0bfb5b80-f68f-11ea-843c-11d365ecc9e6.png">

### Describe the behavior you expected

We should avoid calling `set_client_state` when the client state has not changed.

Note that there are no ill effects from this issue; it's ultimately just to reduce overall chattiness between the client and server.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Verified on 1.4.1033 on macOS Big Sur.
