### ISSUE TITLE
Cascading tables in DB view

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#7787]
###System details

    RStudio Edition : Server
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

With SQL Server (and perhaps other databases),  add/remove multiple connections until you see them start to cascade.

### Describe the problem in detail

![DreScBy](https://user-images.githubusercontent.com/136863/93137797-0c561f80-f6ac-11ea-9c54-493863eba2bd.png)
It should not look like this :)

Unfortunately the customer didn't give us much more to go on and I have not been able to repro it but it's worth another glance.

### Describe the behavior you expected
The icons are all lined up neatly on the right side.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by adamconroy** [comment]
Customer ticket: 50873

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/3746
