### ISSUE TITLE
Typing is temporarily sluggish when visual editor contains many code chunks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7791]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.814

### Steps to reproduce the problem

1. Open an R Markdown document that contains a large number of R code chunks. For example: https://github.com/Robinlovelace/geocompr/blob/master/05-geometry-operations.Rmd
2. Switch to visual editing mode
3. Immediately begin typing in a prose section of the document

### Describe the problem in detail

The CPU usage is high, and typing is sluggish. This is the case for several minutes until the document is fully loaded. 

### Describe the behavior you expected

It's normal for the CPU usage to be high as RStudio works on loading the code chunks in the long document. However, it's annoying that typing is slow and at times almost unresponsive. Typing should be responsive even while RStudio renders in the background.

**Comment by adamconroy** [comment]
This feels pretty good now, though there are still some hitches here and there with scrolling and starting to type after a bunch of scrolling. Fairly minimal though. Verified on 1.4.938

**Comment by eliocamp** [comment]
I'm on 1.4.1103 and experiencing the typing lag issue. CPU usage is not high, but the lag is noticeable and distracting.

This video illustrates the lag when writing on a fairly complex document: 

https://user-images.githubusercontent.com/8617595/108223067-2b078900-7118-11eb-8d9f-3a3838b386b8.mp4

For comparison, here's how it works on a new document (with just the example chunks and code)

https://user-images.githubusercontent.com/8617595/108223147-42df0d00-7118-11eb-8e50-33eb1ccdec5d.mp4
