### ISSUE TITLE
Cannot store user data in ~/.rstudio in RStudio 1.4

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7792]
### System details

    RStudio Edition : Both
    RStudio Version :  1.4.814

### Steps to reproduce the problem

1. Note that RStudio stores user data in `~/.local/share/rstudio`.
2. Attempt to configure RStudio to store user state to `~/.rstudio`, as it did in RStudio 1.3.
3. You cannot.
4. You are very frustrated.

### Describe the problem in detail

RStudio 1.4 follows the XDG standard for user data and stores it in `~/.local/share/rstudio`, as described in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), as of https://github.com/rstudio/rstudio-pro/pull/1602. It includes code for migrating from the `~/.rstudio` path used by 1.3 and prior versions of RStudio.

The folder is customizable by setting `XDG_DATA_HOME`, but there's a catch: this specifies the *root* data directory (`~/.local/share/`) by default, beneath which we use a directory named `rstudio`. So you cannot tell RStudio to use `~/.rstudio` since you're not in control of the last part of the path. 

### Describe the behavior you expected

It should be possible for users to continue to use `~/.rstudio` for user data if they want to. Even though it's not officially supported, some tools and installations symlink `~/.rstudio`, or introspect it. These will all break if we change the location without recourse.

There are a lot of ways we could address this; here are two:

1. Do not be XDG compliant by default: abandon the `~/.local/share/rstudio` path as a default, and continue to use `~/.rstudio`. No one is really asking for us to change the default. Or...
2. Add an RStudio-specific environment variable or setting which can override `XDG_DATA_HOME` (and other directories, for symmetry) with a specific directory instead of a root. Customers who really need user data to be stored in `~/.rstudio` 
can set e.g., `RSTUDIO_DATA_HOME=$HOME/.rstudio`.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1013
