### ISSUE TITLE
Border still remains when using "Copy to Clipboard" (similar to *closed* report #4864)

### ISSUE THREAD

**Issue by schwa021** [rstudio/rstudio#7794]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      :  Windows 10
    R Version       :  x64 4.0.2

### Steps to reproduce the problem
Generate any plot, select "Copy to clipboard", paste into word, ppt, etc...

### Describe the problem in detail
I hope it's appropriate to repost - but this problem was brought up earlier (#4864) and "closed" - but it was not "resolved"

When I create any plot, use Copy to clipboard, and paste into another program (e.g. power point), a thin grey border remains at the top and left (note, the old "resize handle" from #4864 is absent).

![image](https://user-images.githubusercontent.com/25011558/93225566-f857ff80-f737-11ea-85ff-e0d48c9101c0.png)

Note that this is in "bitmap" form. When I copy to clipboard in metafile format, the borders are not there, BUT the plot pastes as a tiny upper right corner of a big empty white canvas - so this ends up requiring cropping as well.
### Describe the behavior you expected
I expected no borders, and that the pasted image would look like the copied image.

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
As a workaround, does Right Click -> Save Image As... save the image as expected?

**Comment by schwa021** [comment]
> As a workaround, does Right Click -> Save Image As... save the image as expected?

Hi Kevin,

Thanks for the suggestion, it definitely works.  The saving of the images works, in general.

- So does sending to a window via windows(w, h, etc...)). 
- So does taking screenshot

However, those are a far cry from the simplicity of copy/paste. 

Also, their is a "copy to clipboard" menu item present - so I imagine the Rstudio developers intended this to work like every other copy/paste operation.

For publications, etc... it's fine. But for the convenience of on-the-fly/interactive work, it's just a bit of an irritant (it is not the end of the world).

**Comment by kevinushey** [comment]
Thanks! I just wanted to confirm since those methods of "saving" an image go through different code paths; it's likely that the right fix here would be to just ensure that all forms of saving a file use the same internal save mechanism in RStudio if possible.

**Comment by hannevlaeminck** [comment]
I still have the same issue. A fix would be appreciated because I agree it's annoying for on the fly type of work!

**Comment by schwa021** [comment]
> I still have the same issue. A fix would be appreciated because I agree it's annoying for on the fly type of work!

I agree that this seems like it should be fixed. I also agree that this is largely for such "on the fly" work (sending email, creating a quick presentation, blog posts, etc...). 

Since posting, I have started using the following "workaround"

1. Plot to a window
2. Right click and "copy as bitmap"
3. Paste that into the target document (email, ppt, blogpost, etc...)

windows(6,4)
plot(x,y)
"right click, copy as bitmap"
paste

Example directly below of this approach

![image](https://user-images.githubusercontent.com/25011558/107642582-b07fca80-6c3a-11eb-95b4-c9a25b0c3916.png)

**Comment by hannevlaeminck** [comment]
What works too for me is to click on the "zoom" button (next to the "export" button in R studio) and then right click "copy image". However, to then paste it in another application e.g. powerpoint, I cannot do a standard paste (nothing is pasted), but need to right click again and choose ("paste as picture").
