### ISSUE TITLE
Update zoom commands to account for multiple columns

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#7801]
Our `Zoom Left Column` command doesn't make sense when a user has multiple source columns open. We need to come up with a way where any column can be zoomed in on and rename `Zoom Left Column` to something more appropriate. There are a few different ways we can do this:

1. Create a new command for `Zoom Current Source Column` that is only active when a user is in a source column and will zoom the currently active column. Leave the existing commands as there are - possibly rename `Zoom Left Column` to `Zoom Left / Center Column`. This follows the design we used for focusing splitter positions in #7481.

2. Remove `Zoom Right Column` and `Zoom Left Column` and replace them with a single  `Zoom Current Column` which detects which column has focus and zooms it. This would put us in a better place if we decide to allow more panes/columns on the right, but requires the user to be more aware of what they have focused.

**Comment by gtritchie** [comment]
I agree that "Zoom current column" will be tidier. Until we have a consistent visual indication of which column is current, though (#6225) it might be confusing to use.

Don't know how much this gets used, honestly. I added them to 1.3 via #5874.

Another way to accomplish some of this would be to rewrite the current `Zoom Source` command so it applies to the currently focused source pane's column. Right now it always does the "traditional" one, even when focus is in a source column. If it zoomed the source column, instead, it would accomplish "zooming" that (single-pane) column.

**Comment by melissa-barca** [comment]
Updating `Zoom Source` is a good idea; I think it keeps things simple and flexible.

**Comment by mikebessuille** [comment]
Leaving in 1.4 to fix opportunistically, but could be moved out if we run out of time

**Comment by kfeinauer** [comment]
Verified working (Zoom source zooms most recently used source pane) in 1.4.1069
