### ISSUE TITLE
R session crashes due to system error 134 when using file browser

### ISSUE THREAD

**Issue by JoFAM** [rstudio/rstudio#7807]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      :  Windows Server x64 build 14393
    R Version       :  4.0.2

### Steps to reproduce the problem

- Open RStudio on a server installation. 
- use file browser to browse through the mapped network drive 

R session gets aborted

### Describe the problem in detail

R and RStudio are installed on a application server that uses Citrix connection manager so students can use these tools from home in the configuration used in class. The complete version info for RStudio: 

"Giant Goldenrod" (718e6d75, 2020-07-29) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
AppleWebKit/537.36 (KHTML, like Gecko) 
QtWebEngine/5.12.8 
Chrome/69.0.3497.128 
Safari/537.36

After opening RStudio through the citrix gateway on the web, using the file browser to go to the necessary project files aborts the R session. The following screens pop up:

![Screenshot - 16_09_2020 , 12_50_28](https://user-images.githubusercontent.com/809906/93328411-f5363f80-f81b-11ea-9c27-0275d2f4ea4d.png)

![Screenshot - 16_09_2020 , 12_50_47](https://user-images.githubusercontent.com/809906/93328430-fb2c2080-f81b-11ea-83f7-fe5e35879a0f.png)

In the log file, the following message is added : 

> 16 Sep 2020 10:35:18 [rsession-jfmeys] ERROR system error 134 (An attempt was made to use a JOIN or SUBST command on a drive that has already been joined) [parse-error: file line number 3 is invalid, line-contents: for examining results]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::text::parseDcfFile(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool,class rstudio_boost::function<bool __cdecl(struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const &)>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *) src/cpp/core/text/DcfParser.cpp:124; LOGGED FROM: class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > __cdecl rstudio::session::modules::r_addins::'anonymous-namespace'::AddinRegistry::parseAddinDcf(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) src/cpp/session/modules/SessionRAddins.cpp:279

> 16 Sep 2020 10:36:00 [rsession-jfmeys] ERROR system error 134 (An attempt was made to use a JOIN or SUBST command on a drive that has already been joined) [parse-error: file line number 3 is invalid, line-contents: for examining results]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::text::parseDcfFile(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool,class rstudio_boost::function<bool __cdecl(struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const &)>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *) src/cpp/core/text/DcfParser.cpp:124; LOGGED FROM: class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > __cdecl rstudio::session::modules::r_addins::'anonymous-namespace'::AddinRegistry::parseAddinDcf(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) src/cpp/session/modules/SessionRAddins.cpp:279

This occurs once or twice, and after that the problem disappears. The R session reboots correctly and can be used further on.

### Describe the behavior you expected

No system errors.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5231771/diagnostics-report.txt)

**redacted**

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Most likely a duplicate of #7637.

If so, this has been fixed in the next 1.3 release, available as a preview at https://rstudio.com/products/rstudio/download/preview/

**Comment by JoFAM** [comment]
Not certain, as I didn't refresh. All I need to do is to open it up, try to open a file. Within a few secconds the R session aborts. It also only occurs on the network installation, I haven't been able to reproduce this locally.

**Comment by gtritchie** [comment]
The issue described in #7637 reproduces in more scenarios than described in that issue (i.e. not just refreshing the UI), but all had the same underlying cause.

For example, crashes were happening in routine use of the Files pane on Windows, see also: #7652, #7665.

We'll keep this issue open until the next release of 1.3 is generally available and you've had a chance to try it in your environment.

**Comment by lofung** [comment]
error 134 has nothing to do with Rstudio. I get that out of a very random package when using Rstudio desktop. It seems this error code is something else caught in a if-else statement. 

That blanket somewhere caught everything and throw out error 134
