### ISSUE TITLE
source window ghosts in feature : multiple source panes

### ISSUE THREAD

**Issue by herambgadgil** [rstudio/rstudio#7809]
### System details

    RStudio Edition : Desktop OpenSource
    RStudio Version : 1.4.824
    OS Version      : Windows
    R Version       : 3.6.3

### Steps to reproduce the problem
Open `RStudio` >> `Tools` >> `Global Options` >> `Pane Layout` >> `Add Column` (Repeat this 3 times - maximum) >> Click `Apply` >> `Remove Column` (Repeat this 3 times - maximum) >> Click `Apply` >> Click `OK`

### Describe the problem in detail

If we add more than 1 source window panes and then try to close them, the editors are closed. But the source window itself remains as is on the screen and disfigures the layout. Only way to bring it back is to close the session and restart RStudio. 

### Describe the behavior you expected

Expected behavior is the panes should go away completely and the layout should not have any blank and unusable source window space. The files present on the removed window pane should shift into the existing pane or the default source window. 

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![feature mpanes ghost](https://user-images.githubusercontent.com/15884914/93388857-f94c7680-f888-11ea-9a6f-3cd3e5529a9c.png)

**Comment by R-Hannibal** [comment]
@herambgadgil, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by herambgadgil** [comment]
I already downloaded and tested. It is working all fine now! 

Thanks for reaching out!

Regards!
Heramb

**Comment by rich-rstudio** [comment]
verified on macos desktop Version 1.4.854
