### ISSUE TITLE
Import Dataset with readr throws error "Is this a valid CSV file?"

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#7814]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.828
    OS Version      : MacOS Catalina 10.15.6 (19G2021)
    R Version       : 4.0.2

<details><summary>Session Info</summary>

```
─ Session info ─────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.6      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-09-16                  

─ Packages ──────────────────────────────────────────────────────────
 package    * version    date       lib source                       
 assertthat   0.2.1      2019-03-21 [1] CRAN (R 4.0.2)               
 BH           1.72.0-3   2020-01-08 [1] CRAN (R 4.0.2)               
 cli          2.0.2      2020-02-28 [1] CRAN (R 4.0.2)               
 clipr        0.7.0      2019-07-23 [1] CRAN (R 4.0.2)               
 crayon       1.3.4.9000 2020-09-09 [1] Github (r-lib/crayon@6b3f0c6)
 digest       0.6.25     2020-02-23 [1] CRAN (R 4.0.2)               
 ellipsis     0.3.1      2020-05-15 [1] CRAN (R 4.0.2)               
 fansi        0.4.1      2020-01-08 [1] CRAN (R 4.0.2)               
 glue         1.4.2      2020-08-27 [1] CRAN (R 4.0.2)               
 hms          0.5.3      2020-01-08 [1] CRAN (R 4.0.2)               
 lifecycle    0.2.0      2020-03-06 [1] CRAN (R 4.0.2)               
 magrittr     1.5        2014-11-22 [1] CRAN (R 4.0.2)               
 pillar       1.4.6      2020-07-10 [1] CRAN (R 4.0.2)               
 pkgconfig    2.0.3      2019-09-22 [1] CRAN (R 4.0.2)               
 R6           2.4.1      2019-11-12 [1] CRAN (R 4.0.2)               
 Rcpp         1.0.5      2020-07-06 [1] CRAN (R 4.0.2)               
 readr        1.3.1      2018-12-21 [1] CRAN (R 4.0.2)               
 rlang        0.4.7      2020-07-09 [1] CRAN (R 4.0.2)               
 tibble       3.0.3      2020-07-10 [1] CRAN (R 4.0.2)               
 utf8         1.1.4      2018-05-24 [1] CRAN (R 4.0.2)               
 vctrs        0.3.4      2020-08-29 [1] CRAN (R 4.0.2)               

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

### Steps to reproduce the problem

1. Create a CSV file in the current working directory (or wherever, really)

   ```r
   readr::write_csv(mtcars, "mtcars.csv")
   ```

2. Navigate to the folder containing the new CSV file in the files pane.

3. Click on the file and select _Import Dataset_

4. After dialog opens:

   ```
   Error

   Is this a valid CSV file?

   could not find function ".rs.tryCatch"
   ```

![image](https://user-images.githubusercontent.com/5420529/93402359-9344fc80-f852-11ea-975a-b379c34681db.png)

### Describe the problem in detail

See above. The error is dismissable, but no preview is ever rendered.

### Describe the behavior you expected

Expected a preview of the data set without error.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
@gadenbuie, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by gadenbuie** [comment]
Yup, it's working great now!
