### ISSUE TITLE
The character limited in one line

### ISSUE THREAD

**Issue by byzheng** [rstudio/rstudio#7815]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      :  Windows 10
    R Version       :  4.0.0

### Steps to reproduce the problem
* In the editor, create a very long character string in **one line** (more than 3863 character), e.g. a <- "this is a very long string ..."
* Run the current line with ctrl + enter

### Describe the problem in detail
The command line will wait for further inputs. 

### Describe the behavior you expected
The same commands is working in the RGUI and splitting into multiple lines in RStudio. 

PS: The best option for me is to put string in one line for debugging purpose. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@byzheng Thank you for letting us know! I can reproduce this in RStudio Desktop 1.4.840 on MacOS 11 Big Sur beta, when run from the source pane, directly in the console, and as a Notebook chunk. We'll review it as we continue development of RStudio.
