### ISSUE TITLE
Ability to close multiple running jobs and not having to confirm to remove completed jobs

### ISSUE THREAD

**Issue by thisisnic** [rstudio/rstudio#7816]
I've currently started running my Shiny apps as background jobs so they're not blocking the main session (LOVE this feature btw).

When I'm iterating quickly through changes I'm making to my Shiny app, my workflow is something like:

1. Make small change
2. Run app to see how it looks/if it's worked as expected
3. Repeat 1 and 2 rapidly until I'm happy with the current change

When I've done this, I end up with lots of running copies of my Shiny app running as jobs, which I then need to shut down.  I have to click them individually to stop them running and then confirm I want to remove them, which is a tiny bit jarring compared to the experience of just clicking a single button with no confirmation needed to close a Shiny app that's running in the R console.

A couple of small requests I'd like to make that'd help make my workflow a little smoother:

- the ability to configure RStudio not to ask for confirmation to remove completed jobs
- the ability to stop multiple running jobs at once instead of having to click them all individually

Thanks again for this capability to run Shiny apps as background jobs, it's already sped up some of my dev work!

**Comment by jmcphers** [comment]
Glad you're finding the feature helpful! See also: https://github.com/rstudio/rstudio/issues/6904.
