### ISSUE TITLE
The R startup information (version etc.) isn't displayed if RStudio is opened with no open files

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7820]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.x (1.3.958 to 1.3.1091)
    OS Version      : MacOS 10.15.6 and Red Hat 8.2
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Open RStudio Desktop.
    * In the console, the usual information about the R version, etc. should appear.
    > R version 4.0.2 (2020-06-22) -- "Taking Off Again”
	Copyright (C) 2020 The R Foundation for Statistical Computing
	Platform: x86_64-apple-darwin17.0 (64-bit)
	etc.
 
(If it doesn’t appear, that’s the bug.)

2. Open a file.
3. Close RStudio.
4. Open RStudio.
    * In the console, the usual information should appear.
5. Close all open files.
6. Close RStudio.
7. Open RStudio.
    * Most likely the usual information won’t be displayed.
    * You might need to close and reopen RStudio.

This is going back to 1.3.958 Water Lily. It seems to work in 1.4.823. Also, the equivalent in RStudio Server to closing and reopening is to close the session and open a new one.

### Describe the problem in detail

Normally, when R first starts, there’s a bunch of standard information displayed, including the version. However, it’s not displayed if there are no open files when RStudio starts up and creates a new R session.

### Describe the behavior you expected

The R startup information should always be displayed when RStudio starts up.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
From Community members:
- https://community.rstudio.com/t/r-version-not-consistently-given-when-start-rstudio/75883/7
- https://community.rstudio.com/t/r-version-session-is-missing-in-rstudio-1-3/80635/3

**Comment by mikebessuille** [comment]
Can we please retest this in the latest 1.4?  if this is no longer an issue in 1.4, we can close this.

**Comment by ronblum** [comment]
Confirmed (thanks @rich-rstudio!) in RStudio Desktop 1.4.854 on MacOS 10.15 Catalina and 1.4.840 on MacOS 11 beta Big Sur.
