### ISSUE TITLE
Terminal line spacing too small on Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7827]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : started with 1.4.717
    OS Version      : Windows
    R Version       : any

### Steps to reproduce the problem
- I'm only hitting this on Windows, and only on a certain machine (my Windows laptop). It is happening on both Desktop and Server (in Chrome, Firefox, and Edge).
- Not sure it's relevant, but the display on this machine is 1920x1080, running at 125% scaling (both are the recommended values)
- Start the IDE
- Create a terminal (I'm using WSL Bash, but can also repro with Git-Bash)
- Write some output: `printf "[[hello]]\n[[world]]\n"`

### Describe the problem in detail
- The output is crammed together vertically; the square brackets are overlapping; here's an example from Windows Desktop:

![screenshot of terminal pane showing overlapping output](https://user-images.githubusercontent.com/10569626/93535025-01dd9500-f8fb-11ea-8c36-6d8912026654.png)

Example from RStudio Server with Chrome 85:

![screenshot of terminal pane showing overlapping output using RStudio Server](https://user-images.githubusercontent.com/10569626/93535196-5719a680-f8fb-11ea-87cc-f2380bc6607a.png)

### Describe the behavior you expected
- No overlap

Regression caused by this change: https://github.com/rstudio/rstudio/pull/7601

First noticed this when I was evaluating a newer version of xterm.js (https://github.com/xtermjs/xterm.js/releases/tag/4.9.0): it throws an exception about line-height being too small when I tried to load a terminal on this system. Example:

![error dialog showing xterm.js complaining about line height-error](https://user-images.githubusercontent.com/10569626/93535287-83cdbe00-f8fb-11ea-830e-b0e67f2abd00.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.949 on Windows 10 with a variety of scaling and resolution settings
