### ISSUE TITLE
file.edit() does not send focus to documents open in visual mode

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7832]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.6
    R Version       : 4.0.2

### Steps to reproduce the problem

Create a new R Markdown document, switch to visual mode, and then save it to `hello.Rmd`. Then, open a new separate file (so that the tab for the document is available, but not open). Then, execute:

```
file.edit("hello.Rmd")
```

### Describe the problem in detail

The visual mode document is opened, but it does not receive focus.

### Describe the behavior you expected

The document should be both opened and focused.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It looks like this issue has been fixed in the latest daily builds, although unfortunately I don't know which PR / commit provided the fix.

**Comment by kfeinauer** [comment]
@kevinushey The `file.edit` command doesn't seem to be focusing any type of file on 1.4.1027. Focus stays with the Console. Is this intended or did it break again?

**Comment by kevinushey** [comment]
Looks like this did indeed regress.

**Comment by kfeinauer** [comment]
Just tested this again on 1.4.1035. It looks like this somewhat doesn't work.

If you only have a single open file which is a Visual Editor file, `file.edit` will select that file and focus it as expected. However, if you open an additional file (of any type), focus that file, then rerun the `file.edit` command, the first file will be activated but focus will remain in the Console.

@kevinushey Thoughts on reopening?

**Comment by kevinushey** [comment]
Looks like you're right -- will fix this up.

**Comment by kevinushey** [comment]
Fixed in https://github.com/rstudio/rstudio/commit/060d9d66148c63f998d7d8cbf60abe97dd846309.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1038
