### ISSUE TITLE
Knit button still don't update correctly when output format change in yaml header

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#7833]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.3.1073 and 1.4.838
    OS Version      :  WINDOWS 10
    R Version       :  R 4.0.2

### Steps to reproduce the problem

* create a new Rmarkdown file using RStudio IDE. 
* This will be a `html_document` format and you'll have a Knit button with a menu and three choice to render format
* Save the file. 
* Change to another format like `bookdown::html_document2` in the yaml header
* Re-save the modified file
* You'll still have the knit button with the same menu with the three choices, and not the format `bookdown::html_document2`
*  if you right-click anywhere on RStudio IDE and click reload, you'll get the correct preview button

### Describe the problem in detail

When modifying the ouput format in the yaml, RStudio IDE does not update anymore its knit button to the correct format. 
I think this is related to https://github.com/rstudio/rstudio/issues/6643 that only fix the issue for`html_notebook` preview mode. 

It happens in the last 1.3 and also in the daily

### Describe the behavior you expected

The Knit button should update to the new format as in 1.2 (see below)

![knit-button](https://user-images.githubusercontent.com/6791940/93589055-918f4c00-f9ac-11ea-8566-35acb0934663.gif)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
closing/opening the doc or reloading the IDE is a reasonable short-term workaround, for something that happens relatively infrequently.  moving this out of 1.4

**Comment by cderv** [comment]
IMO one example that could be more frequent than we think: Currently it means that whenever you create a default new Rmarkdown document from the IDE using the menu New File > R Markdown... you'll get a Rmd document with a default format in the yaml header. And usually you will change the format in the header to the one you want for your document (`bookdown::html_document2`, `github_document`, `rmdformats::material` or any other) and you will save the file. Doing that won't change the Knit button unfortunatly. You'll need indeed to Right Click > Reload or close and reopen.

I encountered it quite often also while currently developing and testing with multiple formats on **bookdown**, **rmarkdown** and other package I work on. When using multiple format in a yaml header, the drop-down menu is quite useful.

**Comment by mikebessuille** [comment]
We can try to fix it for 1.4 but only if it's a simple / low risk fix at this point. Otherwise we should move it out to 1.5.

**Comment by jmcphers** [comment]
This is probably another regression from https://github.com/rstudio/rstudio/pull/6442. We used to do quite a lot of work on save, but a great deal of it was intrusive when done implicitly (i.e. for autosave), so now we are much more careful about what goes in the save path. This one requires a full recompute of the editor toolbar which we probably don't want to be doing on autosave.

**Comment by cderv** [comment]
Awesome ! this works ok in 1.4.932 now (with autosave disable). Thank you !

**Comment by kevinushey** [comment]
Thanks for verifying @cderv!
