### ISSUE TITLE
Adding of push and pull requests of VCS in top right toolbar for quick commiting and pushing

### ISSUE THREAD

**Issue by galanteria01** [rstudio/rstudio#7841]

**Comment by ronblum** [comment]
@galanteria01 Thank you for filing the request. However, I'm not sure what the request is. There are already buttons in the Git pane for pull, push, and commit. What are you looking for that's different?

<img width="352" alt="pushmepullyou" src="https://user-images.githubusercontent.com/31009952/93789875-64d37280-fc00-11ea-8cc8-c6601cfafbe1.png">

**Comment by galanteria01** [comment]
Something similar to android studio and pycharm i.e top-right edge has 3 buttons,Push,pull and commit.. It's too handy

**Comment by ronblum** [comment]
@galanteria01 When you say top-right edge, are you referring to the right border of the IDE, or the source pane, etc.? Also could you provide a screenshot of what you're looking for as a comparison point? Thank you!

**Comment by gtritchie** [comment]
They are referring to the main toolbar, here's PyCharm:

<img width="1199" alt="screenshot of PyCharm with an arrow pointing at the Git commands on toolbar" src="https://user-images.githubusercontent.com/10569626/93795116-d1914180-fbed-11ea-93dc-63c2b6d370f7.png">

**Comment by galanteria01** [comment]
![Screenshot from 2020-09-22 08-12-09](https://user-images.githubusercontent.com/58800160/93839696-702fa800-fcab-11ea-8998-c4131333d80d.png)
Some thing similar to this
