### ISSUE TITLE
Allow multiple windows/panes open on same file

### ISSUE THREAD

**Issue by ashenkin** [rstudio/rstudio#7842]
This has been requested elsewhere, but I haven't found it here.  It would be very nice to be able to have two windows or panes open on the same file at the same time.  This is useful when working on longer files where one doesn't want to lose her place when jumping around.

Older request: https://community.rstudio.com/t/split-panes-in-source-editor/11992

**Comment by ronblum** [comment]
@ashenkin Thank you for the suggestion! We've introduced the ability to open multiple source panes in RStudio 1.4, which you can do with _View -> Panes -> Add Source Column_ or _Tools -> Global Options -> Pane Layout_. However, I don't believe this accomplshes what you're asking for, so I'll mark this as a feature request to review.

**Comment by jmcphers** [comment]
It's tracked here: https://github.com/rstudio/rstudio/issues/2129
