### ISSUE TITLE
buttons not visible on chunk output toolbar in dark (dracula) mode

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7843]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.8.841
    OS Version      :  OS X 10.15.5
    R Version       : 3.6.1

### Steps to reproduce the problem

1) Create a code chunk with an error in it:

````
```
{r}
x <- c(1:10)
y <- x[[5]
```
````

2) Execute the chunk.

3) Output toolbar buttons are not visible:

<img width="622" alt="Screen Shot 2020-09-21 at 6 56 42 AM" src="https://user-images.githubusercontent.com/104391/93759501-46598100-fbd8-11ea-82ce-5a6b09aa0f1c.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Appears to be desktop-only for some reason.

Server mode:

![image](https://user-images.githubusercontent.com/470418/93813684-54bf9100-fc08-11ea-9542-4247b7625f6c.png)

Desktop mode:

![image](https://user-images.githubusercontent.com/470418/93815442-d3b5c900-fc0a-11ea-9206-609c1aafa885.png)

**Comment by jmcphers** [comment]
This appears to be a QtWebEngine issue. The buttons are dark images that are made visible in dark mode by using a CSS color inversion filter, `filter: invert(100%)`:

https://github.com/rstudio/rstudio/blob/79aee8e21783e76b0a56e8f8ac42a36e2101bea4/src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css#L2489-L2497

This CSS rule is active (according to Chromium) in visual mode, but it doesn't do anything (even if applied directly to the HTML). Conversely in source mode, QtWebEngine applies the filter correctly. 

So we'll need to either figure out what's triggering the QtWebEngine filter bug and work around it, or manually create lighter versions of these images for dark mode so we don't have to rely on the filter to invert them.
