### ISSUE TITLE
Spellcheck options for quoted strings

### ISSUE THREAD

**Issue by gregorp** [rstudio/rstudio#7847]
#5009 has been closed for 8 months, and strings in R code are no longer spell-checked. And today I just sent a client a chart with the word "Schol" instead of "School" in a plot title.

Obviously it's hard to know the difference between strings that might show up in plot labels vs file names, column names, hex colors, etc., that likely aren't real words. But I'd hope there's a middle ground where *some* quoted strings are checked, at least as an option. 

Reprex: Save as a `.R` file these two lines:

```
# This is spelchecked
"But this is not spelchecked"
```

I think it would be really nice to have an option - perhaps only with button click - to spellcheck quoted strings.

**Comment by ronblum** [comment]
@gregorp Interesting idea, thank you for the suggestion! We'll review it as part of our ongoing development of RStudio. And I'm sorry about it contributing to sending the misspelled word to the client. For what it's worth, I often end up editing my comments here two or three times, after I discover spelling and grammar errors in them after I've saved them...
