### ISSUE TITLE
S4 method parameter auto-completion does not appear to work

### ISSUE THREAD

**Issue by brodieG** [rstudio/rstudio#7851]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : OS X 10.14.6
    R Version       : 4.0.2

### Steps to reproduce the problem

```
install.packages('diffobj')
library(diffobj)
diffPrint('hello', 'world', for<autocomplete>)
```

Where &lt;autocomplete&gt; means attempting to engage the auto-complete to fill in additional parameters (e.g. in this case going for `format`).

### Describe the problem in detail

Autocomplete for S4 method parameters not in the generic does not appear to work.  In this case, these are the docs that show the parameters of the "default" method:

```
Usage
diffPrint(target, current, ...)

## S4 method for signature 'ANY'
diffPrint(
  target,
  current,
  mode = gdo("mode"),
  context = gdo("context"),
  format = gdo("format"),
... snip ...
```

Only the parameters in the generic are available for auto-completion.

### Describe the behavior you expected

Autocompletion to succeed as suggested in this [blog post][1].

[1]: https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@brodieG Thank you for raising the issue! We'll review it as we continue to work on RStudio.
