### ISSUE TITLE
graphic shown twice when executing code chunk with knitr::include_graphics

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#7853]
We currently sniff out the `knitr::include_graphics()` in code chunks and show a preview here:

https://github.com/rstudio/rstudio/blob/master/src/gwt/panmirror/src/editor/src/nodes/rmd_chunk/rmd_chunk-image.ts

However, if we execute the code chunk we end up seeing it twice:

<img width="789" alt="Screen Shot 2020-09-22 at 7 51 11 AM" src="https://user-images.githubusercontent.com/104391/93878741-90119c80-fca8-11ea-9d1d-cf88c128c80c.png">

I think that the chunk output should get priority here (as there could be other output created therin) so we need to find a way to suppress the image preview when chunk output is visible.

The two approaches to this would be to somehow have chunk output be a part of document state OR to create a bridge between where we create this plugin (https://github.com/rstudio/rstudio/blob/5e004eef5d8ccca3e5a50c9554f9fab51d58d26a/src/gwt/panmirror/src/editor/src/nodes/rmd_chunk/rmd_chunk.ts#L115) and the code which knows about the state of all node views (https://github.com/rstudio/rstudio/blob/master/src/gwt/panmirror/src/editor/src/optional/ace/ace-node-views.ts).

**Comment by jjallaire** [comment]
Resolved by removing support for include_graphics image preview

**Comment by adamconroy** [comment]
verified on 1.4.938
