### ISSUE TITLE
R studio can't be installed in Manjaro Linux

### ISSUE THREAD

**Issue by dir0417** [rstudio/rstudio#7856]
Hello everyone, I am a Manjaro Linux user.  
R studio can't be installed in Manjaro Linux.
I was wondering if someone could make R studio compatible to Manjaro linux?

**Comment by ronblum** [comment]
@dir0417 Unfortunately, RStudio does not support Manjaro Linux. The supported platforms list is available at https://rstudio.com/about/platform-support/ . A quick web search shows that some users have had some success with it. However, we can't state authoritatively which of these suggestions is successful.
