### ISSUE TITLE
Contextual menu in git pane does not render correctly when put at the bottom

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#7859]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.854
    OS Version      :  WINDOWS 10
    R Version       :  4.0.2

### Steps to reproduce the problem

Layout should change and the git pane should be put at the bottom and not in the default at upper right. 

have a rather long list of file modified or untracked by git. 

Right click on a file (to revert for example)

### Describe the problem in detail

When right clicking on a file, a contextual menu opens. 

If the file is on top, it prints ok. 
![image](https://user-images.githubusercontent.com/6791940/93934379-5c278d00-fd23-11ea-92b5-6c3ff745b493.png)

If in the middle, the box is reduced with a scroll
![image](https://user-images.githubusercontent.com/6791940/93934462-7c574c00-fd23-11ea-8495-9be2b95f6493.png)

If the file is at the bottom, we can't even scroll and it impossible to use the contextual menu
![image](https://user-images.githubusercontent.com/6791940/93934572-a577dc80-fd23-11ea-880e-de4bb0701913.png)

The problem does not appear when git pane is upper right because it can overlay on the below pane it seems.

### Describe the behavior you expected

The contextual menu could be show **above** the pointer and not always **under** when we are near the edge of the pane.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I have repro'd and am working on the fix.

**Comment by R-Hannibal** [comment]
@cderv, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by cderv** [comment]
Just tried and it works as expected ! 🎉 Pop up is now above the pointer when not enough space below . Way better for the user experience ! Thanks a lot !
