### ISSUE TITLE
Opening the Find in Files dialog in a project on Ubuntu results in errors

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7864]
### System details

    RStudio Edition :Desktop
    RStudio Version : 1.3.1093
    OS Version      : Ubuntu 18.04.5
    R Version       : 4.0.2

### Steps to reproduce the problem

1) Open a project or create a new one
2) Edit -> Find in Files
3) Wait a moment

### Describe the problem in detail

Errors start appearing in the console:
```
vmware@ubuntu:~$ rstudio
"Class$S314: (TypeError) : Cannot read property 'path' of null"
"Class$S314: (TypeError) : Cannot read property 'path' of null"
"Class$S314: (TypeError) : Cannot read property 'path' of null"
"Class$S314: (TypeError) : Cannot read property 'path' of null"
```

### Describe the behavior you expected

The errors should not appear. Note, though, that find and replace both work properly.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Verified fixed in 1.4.945 on Ubuntu 20.04.
