### ISSUE TITLE
Daily build: cannot launch RStudio in Ubuntu 20.04 (libssl.so.1.0.0: cannot open shared object file)

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#7865]
### System details

```
RStudio Edition : Desktop
RStudio Version : 1.4.861
OS Version      : Linux Mint 20 (~Ubuntu 20.04)
R Version       : 4.0.2
```

### Steps to reproduce the problem

In the shell, type `rstudio &`

### Describe the problem in detail

I get this error:

```
rstudio: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

[1]+  Exit 127                rstudio
```
It works with 1.4.823 without problem.
This is my version of OpenSSL:
```
$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```

### Describe the behavior you expected

RStudio should launch without errors.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
It sounds like you may have downloaded a build meant for an older version of Ubuntu. Does one meant for Bionic (Ubuntu 18) or newer work? Direct link:

https://s3.amazonaws.com/rstudio-ide-build/desktop/bionic/amd64/rstudio-1.4.861-amd64.deb

**Comment by florisvdh** [comment]
You're right! Thanks for the feedback. I had taken the 'quick route', i.e. clicking the below 'Ubuntu' button at https://dailies.rstudio.com/. (Previously I did go via 'Ubuntu 18+', no problem there.) And indeed, when hovering on the button I can see it links to a build for Xenial.

![afbeelding](https://user-images.githubusercontent.com/19164640/94110008-2fb66280-fe42-11ea-87ec-25227275a456.png)

IMHO I think the appearance of this Ubuntu button without mentioning the Xenial version is rather misleading - maybe it can be made more specific? Anyway, I thank you for supporting multiple Linux distributions and versions!! :clap: :clap: :clap: :+1:

**Comment by florisvdh** [comment]
Just my suggestion: link the button to version 18.04+ (instead of 16.04, which represents a smaller user group I expect). And then mention 18.04+ in the button.

**Comment by jmcphers** [comment]
That's a good idea!

**Comment by jmcphers** [comment]
Done.
