### ISSUE TITLE
Daily build: 'insert citation' does not switch to active Zotero profile

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#7867]
### System details

```
RStudio Edition : Desktop
RStudio Version : 1.4.823
OS Version      : Linux Mint 20 (~Ubuntu 20.04)
R Version       : 4.0.2
```

### Steps to reproduce the problem

1. Setup Zotero with at least two profiles (the first time, launch Zotero with `zotero --ProfileManager`), i.e. each with its own database & settings. (In my case: one for production, one for testing) Here, I'll refer to these profiles as profile A and profile B.
1. Open Zotero with profile A.
1. Launch an RStudio project in VME mode, open an Rmd file, press ctrl-shift-f8 and check that data from profile A are connected into the insert-citation dialog
1. Close RStudio and Zotero
1. Open Zotero with profile B.
1. Reopen the RStudio project in VME mode, open an Rmd file, press ctrl-shift-f8 and verify which Zotero profile is connected

### Describe the problem in detail

The RStudio project stays connected to profile A. It does not take into account the active profile. There is no obvious way to switch profile.

EDIT: this also holds between different RStudio projects: a new RStudio project does not switch to profile B even though that one is active.

Also, it seems that the project connects to this profile even when Zotero is not opened again.

### Describe the behavior you expected

I would expect that the active Zotero profile determines which profile (database) is connected to by RStudio. Only if Zotero is not running, it is sensible to me that RStudio defaults to the latest connected profile (database).

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Charles, this doesn't seem critical for 1.4 but please move it into 1.4 if you feel it's critical.

**Comment by jjallaire** [comment]
fixed here: https://github.com/rstudio/rstudio/commit/61124b1817115b3250f35e5c0278f46ce417dea1

**Comment by florisvdh** [comment]
While using version 1.4.1010, given my multiple profile history as described, no Zotero entry was shown anymore (at all) in 'insert citation'. However I found out this can now be controlled manually by the global RStudio option 'Zotero Data Directory', so that is a sufficient solution to me :+1: .

However, note that:

- there was no automatic handling/detection of Zotero profiles or the active profile (contrary to the [online](https://rstudio.github.io/visual-markdown-editing/#/citations?id=citations-from-zotero) documentation: _'If you have Zotero installed locally it’s location will be detected automatically '_)
- the option 'Zotero Data Directory' only worked for me after I provided the actual folder with `zotero.sqlite` (i.e. a subfolder 'deep down' like `~/.zotero/zotero/(profilename)/zotero`), contrary to the example screenshot in https://rstudio.github.io/visual-markdown-editing/#/options?id=citation-options, where a high-level folder is used (AFAIK the folder with `zotero.sqlite` will normally be nested deeper)

**Comment by kfeinauer** [comment]
Community verified.
