### ISSUE TITLE
RStudio failing to find libR.so

### ISSUE THREAD

**Issue by gavinsimpson** [rstudio/rstudio#7868]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073 (provided by Fedora's repos)
    OS Version      : Linux (Fedora, 32)
    R Version       : 4.0.2

### Steps to reproduce the problem

Copy the script below to `~/bin/R` (or somewhere on your path, or wherever user scripts live) and make it executable
Start RStudio
(it runs `~/bin/R` see below)
RStudio fails to find `libR.so`
Raises Dialogue box
RStudio closes when you click OK

### Describe the problem in detail

I start R via a shell script `~/bin/R` with an extra note to indicate which BLAS is being used and to preload that BLAS when starting R (This is the suggested way to swap out the BLAS on Fedora so I can use other BLAS options when developing or doing research). The script I use is:

```
#!/bin/sh

echo "Starting R with Atlas BLAS support"
LD_PRELOAD=/lib64/atlas/libsatlas.so.3 \
/usr/bin/R  ${args} "${@}"
```

When I start RStudio it fails to locate `libR.so`, produces a dialogue box with the following information:

>    Unable to find libR.so in expected locations within R Home directory Starting R with Atlas BLAS support
>    /usr/lib64/R; R home path (Starting R with Atlas BLAS support
>    /usr/lib64/R) not found

If I comment out the line `echo "Starting R with Atlas BLAS support"` in the script RStudio starts up normally.

### Describe the behavior you expected

I expect RStudio to start normally and find R

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
RStudio tries to query information about installed versions of R by invoking the moral equivalent of:

```
R --vanilla -s -e <...>
```

and then attempts to parse that output. I'm guessing interleaving your own messages is causing issues with that process.

**Comment by Enchufa2** [comment]
@gavinsimpson FYI, from Fedora 33 on, FlexiBLAS is the preferred way to switch BLAS. See [this](https://fedoraproject.org/wiki/Changes/FlexiBLAS_as_BLAS/LAPACK_manager) and [this](https://cran.r-project.org/bin/linux/fedora/#blaslapack-switching).
