### ISSUE TITLE
Word count option for the visual markdown editor

### ISSUE THREAD

**Issue by annafergusson** [rstudio/rstudio#7872]
The [visual markdown editing mode](https://rstudio.github.io/visual-markdown-editing/#/) is amazing but it would be even more amazing if the **Word count** option from the Edit menu worked in this mode, particularly to help writing productivity 💻 😊

**Comment by jmcphers** [comment]
What version are you using? We recently enabled this. :-)

**Comment by annafergusson** [comment]
Ah - sorry, should have checked the latest build! I'm using version 1.4.785 :-) Thanks!
