### ISSUE TITLE
[Bug] [RStudio Server] Many times, Rstudio rerun some code that overwrite my previous figure with a blank one when I login again after it logout

### ISSUE THREAD

**Issue by DawnEve** [rstudio/rstudio#7875]
### System details

    RStudio Edition : "Middlemist Red" (3a09be39, 2020-05-18) for CentOS 6
    RStudio Version : Version 1.3.959
    OS Version      :  CentOS 6
    R Version       : 
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree

### Steps to reproduce the problem
When I'm working under Rstudio and left with a Win+L, the next morning, or when Rstudio web logout automatically, I will find a  figure in PDF lost after I login again.

### Describe the problem in detail
Many times since new Rstudio with new feature (that will logout after 1 hour) was installed.
When I come back in the morning, I would find one of my PDF file contents will be disappear with a blank.
The fear made me mad!!! especially when I counld'nt find which file was over-write. (See figure attached.)

### Describe the behavior you expected
I expected the previous version of Rstudio, which will always online.
I DO NOT need Rstudio web to logout, as it is my own computer, I have other password to ensure security.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
![1](https://user-images.githubusercontent.com/5974903/94096140-ec65ef00-fe55-11ea-8a5a-793cc2df7cd1.png)
![2](https://user-images.githubusercontent.com/5974903/94096145-ef60df80-fe55-11ea-87cb-81c2545de11e.png)

**Comment by ronblum** [comment]
@DawnEve Thank you for raising the issue! Two things:
1) The blank PDF is likely a bug, so I'll mark it as such.
2) Regarding the session timeout, you can adjust this with one of the following settings in the `/etc/rstudio/rserver.conf`
    - `auth-stay-signed-in-days=7`
    - `auth-timeout-minutes=20`

You can read more about this in the administrative guide at https://docs.rstudio.com/ide/server-pro/authenticating-users.html#authorization-timeout

**Comment by DawnEve** [comment]
Thank you for your reply. Hope this will be solved.
I wonder if I can set this option if I have no root.

**Comment by mikebessuille** [comment]
This could be a bug in pdf.js.   we need to try to reproduce this.

**Comment by mikebessuille** [comment]
@dawneve, can you please try to reproduce this in the latest server build in 1.4?

**Comment by DawnEve** [comment]
OK, I'll try, if I meet it again.

This is a low frequency error, It apeared about once every 2 month or so.

It seems to happen when using blocks with CairoPDF() or pdf() and dev.off() as the last exe R code, before I left and Rstudio logout in the night.

**Comment by ronblum** [comment]
@DawnEve If I understand correctly, the server is on CentOS 6, and I think you're working from Windows, as you mentioned Win+L. What version of Windows and which browser are you using?

**Comment by DawnEve** [comment]
> @DawnEve If I understand correctly, the server is on CentOS 6, and I think you're working from Windows, as you mentioned Win+L. What version of Windows and which browser are you using?

Yes, server is CentOS 6, I work under win10 + chrome.

This bug not occur again, up to now.

I think you can put a "Login until the browser close" option when login Rstudio server, giving end user the option to set whether he or she prefer to logout or not, instead of the server administrator.

**Comment by ronblum** [comment]
I can't reproduce this using Chrome on Windows 10, although I'm using RStudio Server 1.4.1100, not 1.3. Note that when a user is signed out, what I do see is that the PDF preview window disappears altogether.

**Comment by DawnEve** [comment]
> I can't reproduce this using Chrome on Windows 10, although I'm using RStudio Server 1.4.1100, not 1.3. Note that when a user is signed out, what I do see is that the PDF preview window disappears altogether.

Since we have set the `auth-timeout-minutes` to more than 100hours, the session never logouted by the system. So the problem didnt occur since then. 

This should be close now.

**Comment by jmcphers** [comment]
@DawnEve Thanks for the update, glad the issue's resolved from your end!
