### ISSUE TITLE
R Notebook inline chunk execution hangs indefinitely if a shiny app was running during first execution attempt

### ISSUE THREAD

**Issue by edvald-motus** [rstudio/rstudio#7877]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : Windows 10 Enterprise (10.0.19041)
    R Version       :  4.0.2 and 3.6.2 tested

### Steps to reproduce the problem

1. Start with a new project. 
2. Create an R Notebook file
3. Create a single-file shiny application (app.R) 
4. Run shiny app
5. Try to run code chunk in the R Notebook file, then cancel it
6. Stop shiny app
7. Try to run code chunk in the R Notebook file, it will be scheduled to run but won't run. Clicking "Don't run" to cancel the scheduled run does not solve the problem. The only way to get it to run is to restart R studio.

### Describe the problem in detail

Attempting to run an R Notebook chunk while a shiny app is running will make R Studio unable to run any chunks, even after the shiny app has been stopped.

### Describe the behavior you expected

After stopping the shiny app, the R session should be free again to execute any code blocks in R notebooks.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@edvald-motus Thank you for reporting the issue!
@R-Hannibal I can't reproduce this on MacOS 11 Big Sur beta 8. Can you try this on Windows 10? Thanks!

**Comment by R-Hannibal** [comment]
@ronblum - confirmed this is occurring on Windows 10 desktop, RStudio version 1.3.1093-1.

Adding appropriate labels as this appears to be Windows only.
