### ISSUE TITLE
Auth-none=1 no longer works on RStudio 1.3

### ISSUE THREAD

**Issue by nadenf** [rstudio/rstudio#7879]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1093
    OS Version: Ubuntu 18
    R Version: 3.6.1
    Browsers: Chrome + Safari

### Steps to reproduce the problem

1. Install 1.3.1093 using the Debian package.
2. Set auth-none=1 in /etc/rstudio/rserver.conf
3. Launch /usr/lib/rstudio-server/bin/rserve

### Describe the problem in detail

Opening http://127.0.0.1:8787 will cycle between the following two urls:

http://127.0.0.1:8787/
http://127.0.0.1:8787/auth-sign-in

If you set auth-none=0 in the config it will take you to the login page as normal.

Looks to be related to #7575.

### Describe the behavior you expected

It should take me straight into RStudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ricardofandrade** [comment]
@nadenf We could not reproduce the issue in 1.3.1093.
We've installed it on a fresh new box and it worked.
Could you please clear all cookies for RStudio on your browser and try it again?
Also, be sure to not run `rserver` as root.

**Comment by nadenf** [comment]
I believe this is because rserver was being run as root. Looks good now.
