### ISSUE TITLE
Code editor commands active outside code editors in visual mode

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7886]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.869

### Steps to reproduce the problem

The Reindent command shortcut does not work in the visual editor:

1. Open an R Markdown document with code chunks
2. Select some code inside a code chunk
3. Press the keyboard shortcut for Reindent (Cmd+I); nothing happens

The Reflow Comment command is active even when not in an editor:

1. Open an R Markdown document with code chunks
2. Place the cursor in a prose section (anywhere outside a code chunk)
3. Open the Code menu and note that Reflow Comment is active
4. Invoke Reflow Comment from the keyboard shortcut or menu; nothing happens 

### Describe the problem in detail

These are just two specific examples; the problem is generally that commands that work with code are not correctly enabled/disabled based on whether visual mode has an active (currently focused) editor.

### Describe the behavior you expected

Commands that act specifically on code should be disabled when the cursor is not inside a code editor.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
