### ISSUE TITLE
tab-separator in plaint text file get replaced by spaces 

### ISSUE THREAD

**Issue by renozao** [rstudio/rstudio#7894]
### System details

    RStudio Edition :Server
    RStudio Version : Version 1.2.5019
    OS Version      :  Ubuntu Bionic 18.04 LTS
    R Version       :  3.6.1

### Steps to reproduce the problem

1. Create a tab-separated text file "my_file.txt" (not in RStudio)
2. Open the file in RStudio, where the option of using spaces instead tab is checked
3. Make a small change and save

### Describe the problem in detail

The tabs are replaced by spaces, despite the extension `.txt`

### Describe the behavior you expected

Files that have extensions known to be for plain text files should not be saved with the options that typically apply to R or other code files

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@renozao Thank you for raising the issue! We'll review this as part of our ongoing development of RStudio.
