### ISSUE TITLE
Git History tab doesn't show diff in some cases

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7912]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.6
    R Version       : 4.0.2

### Steps to reproduce the problem

Open a project with a large Git history (say, RStudio), then click the History button from the Git pane. Try navigating through the different commits.

### Describe the problem in detail

In some cases, the associated commit data is not shown.

<img width="1072" alt="Screen Shot 2020-09-29 at 12 02 59 PM" src="https://user-images.githubusercontent.com/1976582/94603878-ba84cc00-024b-11eb-98bf-eae00c16eedb.png">

### Describe the behavior you expected

We should show the diff associated with a commit whenever possible.

### Notes

We use `git show` to collect a diff for these commits, but this doesn't always give us what we want. For example:

```
$ /usr/local/bin/git -c core.quotepath=false show --pretty=oneline -M -c 5a388f06cface0f4445630a5fe3cf269d975f8b4
5a388f06cface0f4445630a5fe3cf269d975f8b4 Merge pull request #7901 from rstudio/bugfix/esc-main-menu-with-popup
```

Compare to:

```
$ git diff '5a388f06cface0f4445630a5fe3cf269d975f8b4^!'
diff --cc src/gwt/lib/gwt/gwt-rstudio/about.html
index 54cd7bcdd4,54cd7bcdd4..783b20d7b0
--- src/gwt/lib/gwt/gwt-rstudio/about.html
+++ src/gwt/lib/gwt/gwt-rstudio/about.html
@@@ -43,7 -43,7 +43,7 @@@
              <td id="title"><a href="http://code.google.com/webtoolkit/">Google Web Toolkit</a></td>
           </tr>
           <tr>
--            <td id="version">Version 2.9.0 <br> (Git revision 115659954)</td>
++            <td id="version">Version 2.9.0 <br> (Git revision d2342c015)</td>
           </tr>
        </table>

<...>
```

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1035
