### ISSUE TITLE
Virtual scroller enabled console truncates output but not associated prompt

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7918]
### System details

    RStudio Edition : Server (probably desktop, too, but I only tried server)
    RStudio Version : 1.4.878
    OS Version      : CentOS 7
    R Version       : 3.6.2

### Steps to reproduce the problem

This was noted during a PR https://github.com/rstudio/rstudio/pull/7568#discussion_r470294749 . Still happens so opening an issue.

- Turn on Virtual Scroller: Global Options / Console: "Limit console display to a subset of total content"
- In the console, do:

```
for (i in 1:2000) cat(c(i, "\n"))
```

### Describe the problem in detail
As expected, the output is truncated to about 1000 lines. However, the prompt for the command that generated the truncated output is still shown, making it difficult to realize content was dropped.

### Describe the behavior you expected
Same behavior as when Virtual Scroller is off; the prompt gets truncated with the rest of the output.

Note, I don't know how important this is in real-world use. It seems like it could be troublesome, though.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I'm still seeing code cut off in unexpected ways with this feature on:

<img width="521" alt="Screen Shot 2020-10-15 at 3 38 24 PM" src="https://user-images.githubusercontent.com/1976582/96193191-8290b080-0efc-11eb-88cd-fdbce6a2304d.png">

It seems like, after a particular piece of console input, we're only retaining the last 1000 lines of output.

After reloading the UI (Right click -> Reload), I see after trying to scroll back to the top:

<img width="576" alt="Screen Shot 2020-10-15 at 3 42 14 PM" src="https://user-images.githubusercontent.com/1976582/96193474-16627c80-0efd-11eb-8444-b07b0057cd6c.png">

So it seems like the console history is then truncated in the "regular" way.

**Comment by kevinushey** [comment]
The original issue still reproduces for me.

**Comment by astayleraz** [comment]
Verified in Version 1.4.1606-1 with the setting on and off and that the truncated text will show when expected and hide when not expected. Added the following QA test/changes for this: https://github.com/rstudio/rstudio-ide-automation/pull/227
