### ISSUE TITLE
FR: "open in a new column" for files

### ISSUE THREAD

**Issue by ColinFay** [rstudio/rstudio#7920]
It would be awesome to be able to do "Open in a new column" when selecting one or more documents in the file pane. 

For example here, a "Open in a new column" would be very handy: 

![Screenshot 2020-09-30 at 16 05 58](https://user-images.githubusercontent.com/17936236/94696042-ec269180-0336-11eb-86b0-fd6d0488832f.png)

**Comment by ronblum** [comment]
@ColinFay Thank you for the suggestion. We'll review this as we continue to work on improving RStudio. I hope this means that you're getting some good use of the multiple source columns (new in 1.4 Wax Begonia).

**Comment by valerie-rstudio** [comment]
### Verify Failed

    RStudio Edition : Server
    RStudio Version : 2021.12.0-daily+80
    OS Version      : ubuntu20
    R Version       : 4.0.3

### Summary
A blank column is opened if an already open file is selected by "Open File in New Column".

### Repro Steps
1. Create a new R Script. Save and name it. Keep the file open in the editor.
2. Click File > Open File in New Column.
3. Select the newly created R Script that is already open in the original editor column.
4. **Expected**: No new column is created.
5. **Actual**: New blank column is created. File remains open in original column.

### Notes
The "Open Each File in New Columns" option from the Files pane follows the expected results.

<hr>

### Verified Fixed
Verified that...
- The "Open File in New Column" option can open any file type in a new column
- The "Open File in New Column" option no longer appears in the File menu once the maximum number of columns is reached
- There is no default keyboard shortcut for the "Open File in New Column"
- The "Open Each File in New Columns" option from the Files pane can open any file type in a new column
- The "Open Each File in New Columns" option from the Files pane opens each selected file in a new column. Once the maximum number of columns is reached, additional files are opened in the last opened column
- The "Open Each File in New Columns" option from the Files pane opens files in the order they are listed in the Files pane.
- The "Open Each File in New Columns" option from the Files pane does not open a blank column if an already opened file is selected

**Comment by GCRev** [comment]
@valerie-rstudio That's the main menu File button that you're referencing right? 

If that's the case, then I think we need a new issue opened for that because its behavior was not modified for this feature, which only targeted the Files pane.

**Comment by valerie-rstudio** [comment]
Opened a new ticket for the issue mentioned above https://github.com/rstudio/rstudio/issues/9891. The remainder of the functionality has been verified.
