### ISSUE TITLE
visual mode chunk toolbar overflows in very narrow editors

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7926]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.886
    OS Version      : macOS Catalina 10.15.6
    R Version       : R version 4.0.2 Patched (2020-06-30 r78761)

### Steps to reproduce the problem

Open a visual mode editor, and then decrease the editor width so it's quite narrow.

### Describe the problem in detail

The chunk toolbar overflows the display to the left.

<img width="198" alt="Screen Shot 2020-09-30 at 11 36 26 AM" src="https://user-images.githubusercontent.com/1976582/94725906-588e9a00-0311-11eb-8d23-b76f197de2bf.png">

### Describe the behavior you expected

The chunk toolbar should (ideally) not be drawn outside the bounds of the shaded chunk region.

**Comment by kevinushey** [comment]
(also, as a matter of pixel-smithing, I think the toolbar should be nudged up a couple pixels to be in line with the chunk header)

**Comment by jmcphers** [comment]
Things aren't much better in source mode.

![image](https://user-images.githubusercontent.com/470418/94735781-1c166a80-0320-11eb-9ce4-827c559379fa.png)
