### ISSUE TITLE
The IDE overrides colon ':' keystrokes as forward slashes '/' when they are entered contextually after a package name on a French azerty keyboard layout.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#7932]
### System details

    RStudio Edition : Server only
    RStudio Version : 1.4.869-4 (has existed at least as far back as 1.2.1335)
    OS Version      : Windows base OS, tested on a RH 8 RSP instance
    R Version       : 4.0.2

### Prerequisite

- This issue is browser specific, confirmed to occur on IE 11, Edge, and Chrome. Does NOT occur on Firefox.
- This issue only occurs when using a French azerty keyboard (Guide on how to [add/change keyboard layouts on Windows](https://www.windowscentral.com/how-change-your-keyboard-layout-windows-10)).

### Steps to reproduce the problem

1. In the IDE console, enter a package name (example: `askpass`).
2. After the package name hit the `:` key on the French azerty keyboard (that would be the key labeled `.` on a default English keyboard layout).

![colon_to_forward_slash](https://user-images.githubusercontent.com/62304541/94747427-7de8cb80-0344-11eb-9568-660cf37e8e8b.gif)

### Describe the problem in detail

On certain browsers the IDE overrides the `:` keystroke and makes it a `/` . This only occurs contextually, confirmed after a package name but there may be other scenarios where this override occurs.

### Describe the behavior you expected

User keystrokes are interpreted successfully by the IDE on all Keyboard layouts and in all supported browsers.

### Notes

- This issue was brought to our attention via a customer support ticket: [52825](https://rstudioide.zendesk.com/agent/tickets/52825).
- This issue is confirmed to occur in both the Source editor and IDE console.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It looks like this happens specifically when the autocompletion popup is displayed. As soon as the popup is hidden, the issue no longer occurs.

It also doesn't effect other document types (e.g. Python), so it's likely something idiosyncratic to the R completion manager.

**Comment by kevinushey** [comment]
🚬 🔫 :

https://github.com/rstudio/rstudio/blob/da52b5af3978d4f3fab3dbcb4a6092ee09f8ab9d/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java#L551-L557

<img width="794" alt="Screen Shot 2020-09-30 at 4 37 57 PM" src="https://user-images.githubusercontent.com/1976582/94750648-648f5180-033b-11eb-9624-84204eed90d7.png">

Evidently, browsers associate key code 191 with `/` on English keyboards, and `:` on French keyboards. We make the assumption that keycode 191 is always a `/`, which is obviously wrong in this case.

**Comment by adamconroy** [comment]
Verified in 1.4.5002!
