### ISSUE TITLE
`Ctrl + Enter` or `Ctrl + Shift + C` does not work within RMarkdown file

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#7934]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.890
    OS Version      : Windows 10 Enterprise 64-bit
    R Version       : 4.0.2 64-bit

### Steps to reproduce the problem

File -> New File -> R Markdown

### Describe the problem in detail

Couldn't run any code (using Ctrl + Enter) or comment/uncomment lines within RMarkdown file. Ctrl + Shift + Enter still worked

![](https://i.imgur.com/wInzlki.png)

### Describe the behavior you expected

Ctrl + Enter or Ctrl + Shift + C should work as normal

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by tungmilan** [comment]
FYI the preview version `1.4.869` does not have this problem.

**Comment by vinaychuri** [comment]
I can confirm this issue is happening on MacOS as well.

RStudio Edition : Desktop
OS Version : Mac OS Catalina
R Version : 4.0.2
RStudio Desktop Version : 1.4.890 

This does not happen on & 1.4.869
