### ISSUE TITLE
Chunk execute option icons not visible after toggle between Visual Markdown Editor & Normal edit mode

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#7936]
### System details

RStudio Edition : Desktop
OS Version : Mac OS Catalina
R Version : 4.0.2
RStudio Desktop Version : 1.4.890 & 1.4.869

### Steps to reproduce the problem
Open new R Notebook.
New R Notebook opens with default template and one chunk with "plot(cars)" pre-filled.
The chunk has the execute option icons visible on the right side of the chunk.

Click on the "Switch to visual markdown editor" and it will now display the new editor mode.
The chunk has the execute option icons visible on the right side of the chunk.

Now click on the "Switch to source editor" and it will now display the earlier editor mode.
The chunk does not show the execute option icons on the right side of the chunk.

### Describe the problem in detail
screen images enclosed as pdf.

### Describe the behavior you expected
The chunk should show the execute chunk icons in all editor formats i.e normal editor as well as 
[Rstudio_chunk_bug.pdf](https://github.com/rstudio/rstudio/files/5310180/Rstudio_chunk_bug.pdf)
visual markdown editor

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1035
