### ISSUE TITLE
Scroll past end of document jumps back on code run

### ISSUE THREAD

**Issue by osymandius** [rstudio/rstudio#7937]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.869 | "Wax Begonia" (7cce2066, 2020-09-24) for macOS
    OS Version      : macOS Catalina 10.15.6
    R Version       : 4.0.2 (2020-06-22)

### Steps to reproduce the problem

1) Preferences --> Code --> Display --> Allow scroll past end of document [ON]
2) Scroll source window so last line of code is in the middle of the screen
3) Run any code

### Describe the problem in detail

When code is run, the source pane reverts to having the last line of code at the bottom of the screen.

### Describe the behavior you expected

Source pane/last line of code should remain in the same place as before code was run.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@osymandius Thank you for pointing this out! I can reproduce this consistently in RStudio Desktop 1.4.869 and 1.3.1093 on MacOS 11 Big Sur beta 8, and in RStudio Server 1.4.869 on Red Hat 8.2. We'll review this as we continue development of RStudio.
