### ISSUE TITLE
Up and Down arrow keys in Console to navigate last commands don't work correctly anymore 

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#7945]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.893
    OS Version      : WINDOWS 10
    R Version       :  4.0.2

### Steps to reproduce the problem

Open a script and add 
```r
sum(1:10)
1+1
print("b")
```
Execute line by line (optional, clear the history before that to have a clean history)

This will run the commands in the console and populate the history. 

Place the cursor in the console and press the Up arrow key to show last commands and try to go up the history then down. 
This won't work as before. Down arrow key does not work and Up command also. 

See Gif below

### Describe the problem in detail

I am trying to do the same as below in 1.3 pressing 

Up > Up > Up > Down > Down > Down > ... to navigate the last commands from the console

![not-working-1 4](https://user-images.githubusercontent.com/6791940/94917843-a0e4be00-04b1-11eb-803e-b3f38c54bbe9.gif)

### Describe the behavior you expected

The same as in RStudio 1.3. 

Doing same as above here and as it works, it is more explicit
Up > Up > Up > Down > Down > Down > Down > Up > Up > Up ... 

![working-1 3](https://user-images.githubusercontent.com/6791940/94917860-ab9f5300-04b1-11eb-8978-5a0ff14aaf59.gif)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Hi @cderv ! Thank you for raising this. I haven't been able to reproduce this yet. Two things:
1) Based on the screenshot, it looks like only the last command, `print("b")`, doesn't appear. The other two, do. Is that correct?
2) Do all the commands appear in the history pane, or are any of them missing?

**Comment by cderv** [comment]
Hum this is inconvenient. I retried and still get the same issue.

> Based on the screenshot, it looks like only the last command, print("b"), doesn't appear. The other two, do. Is that correct?

When I first press Up, I get `1+1` and  not `print("b")` that is correct. If I try to press Down, nothing happen. If I press Up again, I get `sum(1:10)`, and can't go back pressing Down to `1+1`. I can only go Up and from the before last command. 

> Do all the commands appear in the history pane, or are any of them missing?

They are all in the history pane - nothing is missing.

**Comment by ronblum** [comment]
OK, I can reproduce this on Windows 10 in RStudio Desktop 1.4.894.

**Comment by ronblum** [comment]
@cderv Just checked, and it worked in 1.4.890, so this is brand new.

**Comment by tungmilan** [comment]
This is happening to me on 1.4.894 too. When I started on a new session of a project, pressing Up button in the console showed a random line in the history. For example, I ran several lines but when I pressed Up, it displayed `dpi = 300)`

![](https://i.imgur.com/7aEefzi.png)

**Comment by WilDoane** [comment]
This issue is present on MacOS as well

RStudio Version: 1.4.900
R Version: 4.0.2
OS: MacOS 10.15.6

**Comment by realHenningLorenzen** [comment]
For me, this issue is two-fold:

1. I cannot  pick the very last command from the history with the "up" key.
2. Once I have cycled past some previous commands with "up", I cannot cycle back with "down".

RStudio Version: 1.4.900 Desktop
R version: 4.0.3 RC (2020-10-02 r79292)
OS: Windows 10 x64 (build 17134)

**Comment by ronblum** [comment]
Reproducible in in RStudio Server 1.4.896 on Red Hat 8.2, as well, so removed the "desktop" tag.

**Comment by hadley** [comment]
This effectively makes RStudio unusable for me. Is there a known good daily that I can roll back to?

**Comment by kevinushey** [comment]
You can use the current [preview release](https://rstudio.com/products/rstudio/download/preview/).

**Comment by cderv** [comment]
@hadley, per a comment above after some tests, last version that worked for me was 1.4.890

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 1.4.904 on MacOS 11 Big Sur beta 8
- RStudio Server 1.4.904 on Red Hat 8.2

**Comment by cderv** [comment]
And verified on windows 10 Version 1.4.905  - it is a lot better now ! Thank you !
