### ISSUE TITLE
en-dash is smaller than hyphen in visual markdown editor.

### ISSUE THREAD

**Issue by Aariq** [rstudio/rstudio#7948]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 1.4.869
    OS Version      :  macOS 10.14.6
    R Version       :  4.0.2

### Steps to reproduce the problem

Type a hyphen and an en-dash (opt + -) in visual markdown.

### Describe the problem in detail

The en-dash renders shorter than a hyphen in the visual markdown editor.

In RStudio with markdown visual editor:
![Screen Shot 2020-10-02 at 2 48 17 PM](https://user-images.githubusercontent.com/25404783/94958943-59186380-04be-11eb-9d8b-35f4cafcb915.png)

Switching back into regular editor:
![Screen Shot 2020-10-02 at 2 49 12 PM](https://user-images.githubusercontent.com/25404783/94959008-73ead800-04be-11eb-8914-dc86b7c600c6.png)

### Describe the behavior you expected

An en-dash should be longer than a hyphen, but shorter than an em-dash.

In textEdit: 
<img width="283" alt="Screen Shot 2020-10-02 at 2 46 33 PM" src="https://user-images.githubusercontent.com/25404783/94958772-19517c00-04be-11eb-8048-a633de1fcd82.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is a "feature" of the Lucida Sans font that is the default in the visual editor. You can find another mention of it here:

https://forums.zotero.org/discussion/69567/font-for-zotero

> On macOS this would be the difference between Lucida Grande (hyphens slightly longer than en dashes)...

**Comment by Aariq** [comment]
🤦🏻‍♂️ Thank you.

**Comment by jmcphers** [comment]
Certainly a questionable choice by the font designer but not something we can address, so closing this one. You might file a feature request to use a different default on MacOS (maybe San Francisco which seems to be Apple's new darling) or make the font customizable.
