### ISSUE TITLE
Keyboard shortcut for insert comment not working in visual markdown editor

### ISSUE THREAD

**Issue by Aariq** [rstudio/rstudio#7949]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      : macOS 10.14.6
    R Version       : 4.0.2

### Steps to reproduce the problem

In the visual markdown editor, when I press command + shift + C, nothing happens.  The same shortcut works fine for commenting out lines in the source editor, so I don't think it's a problem with a conflicting keyboard shortcut.

### Describe the problem in detail

I'm not sure if this is related, but in Tools > Modify Keyboard Shortcuts... the shortcut listed for Comment/Uncomment section is Shift+Cmd+C.  In the command palette, the command for this is listed as Ctrl+Shift+C.  In the source editor, both of these shortcuts work to comment out lines of code or text.  In the visual editor, these shortcuts both work inside code chunks, but neither do anything in markdown text.  Using Insert > Comment does work though.

### Describe the behavior you expected

I expected Cmd+Shift+C to insert `<-- #  -->` at the cursor position.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Thanks for the report! I think you're seeing a bug that has been fixed very recently. Can you check to see whether this issue reproduces in our daily build?

https://dailies.rstudio.com/

**Comment by Aariq** [comment]
It appears like it's fixed in the daily build.  Thanks.

**Comment by mvanaman** [comment]
What about commenting out highlighted text? When using the regular ol' editor, you can highlight text, use the Ctrl+Shift+C shortcut, and any text that is highlighted goes into the comment. Not so for visual editor, at least for me . Then again, maybe that's not the expected behavior, and that should be a feature request?

System deets:
R Version 4.3.1 (2023-06-16)
Quarto Version 1.3
RStudio Version 2023.06.1+524 (2023.06.1+524)
