### ISSUE TITLE
The first emoji in a series of emojis is larger than the rest in the visual R markdown editor

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7950]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.869
    OS Version      : MacOS 10.15.6 and Red Hat 8.2 
    R Version       : 4.0.2

### Steps to reproduce the problem

1. In an R markdown or notebook file, past the following while in visual mode: 😀😀😀😀😀
    - All the emojis are the same size.
2. Switch to source mode
    - All the emojis are the same size
3. Switch to visual mode
    - The first emoji is slightly larger than the rest, as if it’s an uppercase emoji.
![image](https://user-images.githubusercontent.com/31009952/94963366-0a6ec780-04c6-11eb-88ab-84e3c5fd8889.png)
4. Copy the emojis.
5. Paste the emojis elsewhere in the document, or in another application.
    - The emojis are all the same size.

### Describe the problem in detail

The first emoji in a series of emojis is a little larger than the rest, as if it were upper case.

### Describe the behavior you expected

The emojis should always be the same size.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1032
