### ISSUE TITLE
Changing panes layout turns visual mode RMarkdown file blank

### ISSUE THREAD

**Issue by skranz** [rstudio/rstudio#7952]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.894
    OS Version      :  Windows 10
    R Version       :  4.0.2

### Steps to reproduce the problem

Open some Rmd file in visual mode and then change the pane layout, e.g. swap the console from left to right as shown in this image:

![rstudio_layout1](https://user-images.githubusercontent.com/1413022/94985756-7bab8a80-0559-11eb-92da-ab34871001f2.PNG)

### Describe the problem in detail

After the layout change the Rmd window becomes blank and cannot be edited anymore:

![rstudio_layout2](https://user-images.githubusercontent.com/1413022/94985768-9da50d00-0559-11eb-97cf-7f69b24576ca.PNG)

Only after closing the Rmd file and loading it again, everything works again. I can consistently reproduce this problem on my computer.

### Describe the behavior you expected

The Rmd visual mode editor pane should not become blank when the RStudio panes layout is changed.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
@jmcphers I have no idea how the pane manager is interacting w/ the editor. I noted that even if you start out in source mode and do the pane switch, the editor is somehow set to null. I have a feeling that when panes move there is some type of global re-initialization / re-layout happening that the visual mode widget is somehow not participating in but I'm not aware of how all of that works so can't speculate how.

**Comment by jmcphers** [comment]
The problem is that the PanmirrorWidget gets detached during the move, and when it gets detached it completely destroys its editor instance. 

https://github.com/rstudio/rstudio/blob/f67dfaf70ec3acaa182435d9bc8345766f673992/src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorWidget.java#L356-L373

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
