### ISSUE TITLE
www-root-path doesn't work on RStudio 1.4

### ISSUE THREAD

**Issue by nadenf** [rstudio/rstudio#7953]
### System details

    RStudio Edition: Server
    RStudio Version: rstudio-server-1.4.897-amd64.deb
    OS Version: Ubuntu 18.0.4 
    R Version: 3.6.3 

### Steps to reproduce the problem

/etc/rstudio/rserver.conf:

auth-none=1
www-root-path=/test

### Describe the problem in detail

When trying to view /test it shows the following error:
<img width="599" alt="Screen Shot 2020-10-03 at 5 43 56 pm" src="https://user-images.githubusercontent.com/657041/94986473-77578f80-05a2-11eb-9296-6f413366b728.png">

### Describe the behavior you expected

Would have expected the normal UI to appear.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
`www-root-path` doesn't cause RStudio to become accessible from that particular URL - you would need a proxy to do that. This setting merely tells RStudio where it is being hosted at (by the proxy), so we can better perform redirections and other operations internally. 

For more information on setting up a proxy with RStudio, see https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy

**Comment by jprukner** [comment]
### System details
```
RStudio Edition: Server
RStudio Version: rstudio-server-rhel-2022.07.0-548-x86_64.rpm 
OS Version: amazonlinux2
```
### Steps to reproduce the problem
I used nginx to set up reverse proxy as described in https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy and even with the reverse proxy in place, I am getting the error. @kfeinauer 

For testing purposes, I am using ip addresses.

nginx running on http://10.0.37.224/ with following config:
```
root@nginx:/# cat /etc/nginx/nginx.conf

events {
    worker_connections 1024;
}
http {

  # Support proxying of web-socket connections
  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }
  
  server {
    listen 80;
    
    location /ws/9724b65b-6d33-44ee-a99f-5544257350dd/ {
      # Needed only for a custom path prefix of /ws/9724b65b-6d33-44ee-a99f-5544257350dd
      rewrite ^/ws/9724b65b-6d33-44ee-a99f-5544257350dd(.*)$ /$1 break;

      # Use http here when ssl-enabled=0 is set in rserver.conf
      proxy_pass http://10.0.35.180:8787;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 20d;

      # Not needed if www-root-path is set in rserver.conf
      proxy_set_header X-RStudio-Root-Path /ws/9724b65b-6d33-44ee-a99f-5544257350dd;

      # Optionally, use an explicit hostname and omit the port if using 80/443
      proxy_set_header Host $host:$server_port;
    }
  }
}
```
I even included the header ` X-RStudio-Root-Path ` to make sure I really don't need it. I also made changes in rstudio server config as follows.
 
rstudio-server running on  http://10.0.35.180:8787; with config:
```
# cat /etc/rstudio/rserver.conf 

# Server Configuration File
www-root-path=/ws/9724b65b-6d33-44ee-a99f-5544257350dd
```
### Describe the problem in detail
When I access nginx proxy on http://10.0.37.224/ws/9724b65b-6d33-44ee-a99f-5544257350dd/, result is not found page @nadenf reported.

![Screenshot from 2022-07-20 11-13-24](https://user-images.githubusercontent.com/13995559/179945317-ad40725a-49c9-419b-81b1-086f7db06006.png)

### Describe the behavior you expected

Would have expected the normal UI to appear. Am I missing something?

**Comment by jprukner** [comment]
In the console, you can see It's trying to load 
 http://10.0.37.224/css/page.css and http://10.0.37.224/images/rstudio-logo.png

It seems like www-root-path both in the config form and header are ignored.

**Comment by jprukner** [comment]
Or at least they are kind of ignored because the script in the html header contains this line:
`var baseUri = "http://10.0.37.224:80/ws/9724b65b-6d33-44ee-a99f-5544257350dd/";` but it also contains this line `/images/rstudio-logo.png`
```

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>RStudio Server</title>
   <script>
      function getBaseUri()
      {
         var baseUri = "http://10.0.37.224:80/ws/9724b65b-6d33-44ee-a99f-5544257350dd/";
         if (!baseUri)
         {
            baseUri = window.location.href;
         }
         var index = baseUri.lastIndexOf("//");
         if (index > 0)
         {
            return baseUri.substring(0, index);
         }
         return "/";
      }

      var cssLink = document.createElement("link");
      cssLink.href = getBaseUri() + "/css/page.css";
      cssLink.type = "text/css";
      cssLink.rel = "stylesheet";
 
      var iconLink = document.createElement("link");
      iconLink.href = getBaseUri() + "/images/favicon.ico";
      iconLink.rel = "shortcut icon";
   
      document.getElementsByTagName("head")[0].appendChild(cssLink);
      document.getElementsByTagName("head")[0].appendChild(iconLink);
   </script>
   <style>
      #banner {
         margin-bottom: 0;
      }
      p {
         margin: 20px 20px 10px 20px;
      }
   </style>
</head>

<body>

   <div id="view" class="container">

   <div class="header-box">
       <img class="logo-image" alt id="logo" src="/images/rstudio-logo.png" />
       <h2>RStudio Server</h2>
   </div>
     
   <p>The requested page was not found.</p>

   <p>Please contact your system administrator for assistance, or click <a href="#" onClick="history.back();">here</a> to go back.</p>

   </div>

<script>
   document.getElementById("logo").src = getBaseUri() + "/images/rstudio-logo.png";
</script>

</body>
</html>
```
