### ISSUE TITLE
Sort command palette commands in line with menus

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#7956]
Here are the commands I see when opening the command palette

![image](https://user-images.githubusercontent.com/5420529/95025878-33749100-065b-11eb-9a3e-c18864b17da3.png)

It can be frustrating to have to step over less used commands, in particular creating a new **R Markdown** document is always a little frustrating because the **R** is matched against "C**r**eate" instead of "**R** Markdown".

![image](https://user-images.githubusercontent.com/5420529/95025939-92d2a100-065b-11eb-9c34-1eff915e0bfe.png)

While this would likely be resolved by sorting by frecency (#7567) but even among command search hits the most relevant commands (i.e. R-related first) should be the first option.

**Comment by ronblum** [comment]
@gadenbuie Thank you for the suggestion—we'll review it as we continue development of RStudio.

**Comment by jmcphers** [comment]
Closed by https://github.com/rstudio/rstudio/pull/8645 in Juliet Rose.
