### ISSUE TITLE
Document outline indicator is not in sync with chunk after code execution

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#7957]
### System details

RStudio Edition : Desktop
OS Version : Mac OS Catalina
R Version : 4.0.2
RStudio Desktop Version : 1.3.1093

### Steps to reproduce the problem
User to open a new R Markdown document and the standard template it prefilled.
Enable the document outline mode. This will enable a pane on the right side that will display the chunks.
User to create more chunks via copy+paste existing or keyboard shortcut.
More default chunks will be created and the document outline mode will be updated accordingly.
Assume that chunk#1 to Chunk#4 has been created.

Click on chunk#2 code and the indicator within the document outline pane will change and reflect the active chunk#2.

### Describe the problem in detail
Now, without clicking inside the chunk#4 execute the chunk#4 code by click on the execute option icon.
The chunk#4 output will be displayed inline but the document outline indicator does not change to chunk#4.
Pls refer enclosed pdf.

### Describe the behavior you expected
Since user has executed the chunk the document outline indicator should show the same chunk as being active.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[Rstudio document outline.pdf](https://github.com/rstudio/rstudio/files/5325171/Rstudio.document.outline.pdf)

**Comment by kevinushey** [comment]
IMHO worth investigating for v1.4 and fixing if the fix is simple.

**Comment by mikebessuille** [comment]
We think this is working as designed; the chunk indicator in the document outline is showing the current focus (i.e., where the cursor is).  That doesn't change when you execute other chunks, so the outline staying on chunk 1 is correct in this case.

**Comment by adamconroy** [comment]
verified in 1.4.1038 that it works as specified
