### ISSUE TITLE
Insert chunk keyboard shortcut doesn't work in visual markdown mode

### ISSUE THREAD

**Issue by dwhdai** [rstudio/rstudio#7963]
### System details

    RStudio Edition : RStudio Desktop 
    RStudio Version : Version 1.4.869
    OS Version      :  Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem
1. Use visual mode in RMarkdown
2. Use Ctrl + Alt + I keyboard shortcut to insert chunk

### Describe the problem in detail
The Ctrl + Alt + I keyboard shortcut to insert code chunks does not work in RMarkdown visual mode, but works fine in source editor mode.

### Describe the behavior you expected
I expected a code chunk to be inserted upon pressing Ctrl + Alt + I.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dwhdai Thank you for raising the issue!
@R-Hannibal Can you take a look at this? It works in RStudio Desktop on MacOS and RStudio Server on Ubuntu 20.04, so it might be Windows specific.

**Comment by R-Hannibal** [comment]
@dwhdai - thanks again for reporting the issue.

I just tried to repro this on Windows desktop and I'm not able to reproduce the issue (`Ctrl + Alt + I` consistently adding an R chunk whether I'm in or out of visual mode). 

What kind of keyboard mapping/layout are you using? Sometimes issues like this are only reproducible on specific keyboard setups (see #7960), so please let us know if you're using something other than ENG/QWERTY and we'll try reproducing the issue again.

**Comment by dwhdai** [comment]
> @dwhdai - thanks again for reporting the issue.
> 
> I just tried to repro this on Windows desktop and I'm not able to reproduce the issue (`Ctrl + Alt + I` consistently adding an R chunk whether I'm in or out of visual mode).
> 
> What kind of keyboard mapping/layout are you using? Sometimes issues like this are only reproducible on specific keyboard setups (see #7960), so please let us know if you're using something other than ENG/QWERTY and we'll try reproducing the issue again.

Just tried it again, and it seemed to be working fine now! It might have been conflicting with Vim mode (which I have turned off recently). Thanks again for looking into this, feel free to close this issue.

**Comment by R-Hannibal** [comment]
Thanks for the update @dwhdai, glad to hear it's working for you. 

I'll go ahead and close the ticket for now, but please let us know if it re-occurs or if you have any other issues with the IDE.
