### ISSUE TITLE
allow getSourceEditorContext() to return path, id even when cursor not in Ace instance

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7964]
For visual mode.

**Comment by kevinushey** [comment]
Looks like this has already been implemented! To test:

1. Create a new R Markdown document,
2. Switch to visual mode,
3. Select some non-code-chunk text,
4. Run `rstudioapi::getSourceEditorContext()` in the console.

You should see something like:

<img width="302" alt="Screen Shot 2020-10-19 at 3 34 35 PM" src="https://user-images.githubusercontent.com/1976582/96518843-98fe7b00-1220-11eb-898b-18d6205dfac3.png">

Note that https://github.com/rstudio/rstudio/issues/8108 tracks extra work around whether we could provide a whole document context + a cursor position in this case; for now, it's okay that the contents + selection are left unset.

**Comment by kfeinauer** [comment]
This currently doesn't track the correct selection text because when the Console is focused, the selection text disappears. This is due to what's noticed in #7925. Reopening that so we can reverify if/when that is fixed.

**Comment by mikebessuille** [comment]
For 1.4 it's okay that we don't return the selection.  The original problem in this issue is fixed; I will open a new issue for the contents and selection.

**Comment by kfeinauer** [comment]
Verified 1.4.1032
