### ISSUE TITLE
blogdown:::insert_image_addin() fails in latest builds

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7965]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.4.dev
    OS Version      : macOS 10.15.6
    R Version       : 4.0.2

### Steps to reproduce the problem

Try to use the Blogdown Insert Image addin.

### Describe the problem in detail

<img width="907" alt="Screen Shot 2020-10-05 at 10 46 03 AM" src="https://user-images.githubusercontent.com/1976582/95114006-1f32a180-06f8-11eb-96e6-6cb180408c6b.png">

### Describe the behavior you expected

Should work without issue.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rich-rstudio** [comment]
verified on Version 1.4.938
