### ISSUE TITLE
Git blame for local (non-github) repos

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#7967]
For github projects, RStudio can already annotate (i.e. git blame) a file:
![image](https://user-images.githubusercontent.com/73080/95116777-38ffd300-0750-11eb-9f35-20eedb3beb50.png)

Unlike many other git features - this one isn't available to local-git users.
We're using git but not on github, and would very much like to be able to blame from within RStudio.

**Comment by ronblum** [comment]
@OfekShilon Thank you for pointing this out! We'll review it as a possible future enhancement.
