### ISSUE TITLE
UI glitches when resizing panes

### ISSUE THREAD

**Issue by SuhasSrinivasan** [rstudio/rstudio#7971]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073 
    OS Version      : Windows 10 2004 Build 19041.508
    R Version       : 3.6.3

### Steps to reproduce the problem
Resizing the RStudio panes in horizontal or vertical direction causes glitches. 
Happens almost each time when using the cursor to resize panes in arbitrary sizes.

### Describe the problem in detail
This issue seems to be Windows 10 version independent. It was occurring on Windows 10 1909 also.
The glitches happen in the lower half of the RStudio window.
Alternate blocks of Source or Console panes appear with RStudio background color.

**Please see attached screenshot.**

![Screenshot 2020-10-05 183407](https://user-images.githubusercontent.com/32346517/95139132-c5eb6200-0739-11eb-9ed7-211023c3b0be.png)

### Describe the behavior you expected
Pane resizing should not cause glitches.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.   
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Does switching the RStudio rendering engine make a difference? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by SuhasSrinivasan** [comment]
Switching to the software rendering engine appears to fix the issue. 
But the responsiveness of the UI slows down.
