### ISSUE TITLE
Noisy Terminal when Directory is deleted

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#7974]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      :  Ubuntu 20.04
    R Version       :  4.0.3

### Steps to reproduce the problem

1. Create a new RStudio project
2. Open a terminal and run `mkdir test && cd test`
3. Close RStudio

In a terminal delete the directory `test/` and open the RStudio project again

```
ncsg3@jetset:.../test/test$
> 06 Oct 2020 12:46:25 [rsession-ncsg3] ERROR system error 2 (No such file or directory) [description: Error changing directory: '/tmp/test/test']; OCCURRED AT rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:724; LOGGED FROM: rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:724
06 Oct 2020 12:46:25 [rsession-ncsg3] ERROR system error 2 (No such file or directory) [description: Error changing directory: '/tmp/test/test']; OCCURRED AT rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:724; LOGGED FROM: rstudio::core::Error rstudio::core::system::ChildProcess::run() src/cpp/core/system/PosixChildProcess.cpp:724
```

### Describe the problem in detail

Clearly the directory `test/` no longer exists, but the output from RStudio is a bit noisy

### Describe the behaviour you expected

A nicer error message?

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@csgillespie Thank you for raising the issue! I can reproduce it on MacOS, as well, both in RStudio Desktop 1.4.904 and 1.3.1093, so it looks like the issue has been around for a while. We'll review it as we continue development of RStudio.

That said, aside from the noisy error, does it interfere with any other work?

**Comment by csgillespie** [comment]
> That said, aside from the noisy error, does it interfere with any other work?

No.

But I've found that RStudio has been crashing a lot on me when rebuilding packages. So this is part of me trying to narrow that issue down (hence the few recent issues).

BTW, I don't think this is related to the crashing.

Cheers
