### ISSUE TITLE
Terminal Colours Showing ANSI Escape Sequences

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#7975]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      :  Ubuntu 20.04
    R Version       :  4.0.3

### Steps to reproduce the problem

I use [bat](https://github.com/sharkdp/bat) to display files - nicer version of `cat`. Install via

```
apt install bat
```

Whenever I `batcat` a file, I get the problem. `batcat` works on other terminals

### Describe the problem in detail

Here's a screenshot from `batcat ~/.gitignore`

![bat](https://user-images.githubusercontent.com/1267747/95204191-a6a51100-07db-11eb-9ea5-7ab2bd3d1ec5.png)

My terminal has no other problems displaying colours

![colour](https://user-images.githubusercontent.com/1267747/95204254-be7c9500-07db-11eb-9807-99c9157363f3.png)

### Describe the behaviour you expected

Not display Unicode

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Data point: On Mac, with `bat` installed with brew, it seems to be working ok in the RStudio terminal with 1.4.906. Some of the colours aren't ideal for the default theme (e.g. some text displays in white on a white background), but I'm not seeing escape sequences as seen in the screenshot from Ubuntu 20. Haven't tried that platform yet.

**Comment by csgillespie** [comment]
For info. Redid the `bat` installation with `apt install bat`. The above behaviour still persists, except using the function `batcat` (you need a symlink to call bat)

**Comment by csgillespie** [comment]
An easier method to generate the same issue
```
git log --pretty=format:'%C(yellow)%h' --color=always  | less
```
But replacing `less` with `more`, `head` or `tail` is fine.
