### ISSUE TITLE
disable JS / CSS diagnostics by default for now

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7979]
Ace bundles some tools for providing diagnostics in JS / CSS files, but those tools are now quite old and provide false positive errors for more modern usages. We should disable these by false, and allow users to re-enable them via a preference.

**Comment by stla** [comment]
This is already possible.

![rstudioOptions](https://user-images.githubusercontent.com/4466543/95330257-8f802500-08a8-11eb-9abf-b7081a5bf7a2.png)

**Comment by kevinushey** [comment]
@stla you are quite right -- thanks for pointing that out! In that case, all we need to do is disable these diagnostics by default, I think. (And re-enable them in the future after we have more modern tools bundled.)

**Comment by jmcphers** [comment]
Resolved in https://github.com/rstudio/rstudio/pull/8003

**Comment by kfeinauer** [comment]
Verified fixed in 1.4.944
