### ISSUE TITLE
Update the About logo to use the flat circle instead of the 3D ball

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7980]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.904
    OS Version      : MacOS, Red Hat, etc.
    R Version       : 4.0.2, etc.

### Steps to reproduce the problem

Help -> About RStudio

### Describe the problem in detail

The logo in the About modal uses the older 3D version for both RStudio Desktop and Server. RStudio Server, especially, has both the flat version in the upper lefthand corner along with the 3D version in the About popup.

### Describe the behavior you expected

Consider updating to the newer, more current flat version. 

<img width="72" alt="flat_and_3d" src="https://user-images.githubusercontent.com/31009952/95239435-f7ffd100-07d8-11eb-9995-8dee5a2914d7.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is an intentional difference; I switched it to the flat logo a few years ago but was asked to switch it back to maintain our trademark. https://github.com/rstudio/rstudio/commit/c649c5cd557c179da4d3d15bbb24c6d639d48832#diff-8dfda389c1af89c6fe5b9b949a1d2442
