### ISSUE TITLE
Font for chunk outputs doesn't follow settings

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#7984]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.900
    OS Version      : macOS

### Steps to reproduce the problem

1. Set your editor font size to be larger than 10 points (e.g., 12 pt)
2. Create a chunk in visual mode that outputs only text.
3. Run the chunk.

### Describe the problem in detail

Reported via @hadley:

![image](https://user-images.githubusercontent.com/470418/95268421-263adc00-07ec-11eb-89be-9f25f1fb9af1.png)

And in this video:

![image](https://blog.rstudio.com/2020/09/30/rstudio-v1-4-preview-visual-markdown-editing/images/visualmode-demo.gif)

The chunk editor font size tracks the setting, but the chunk output font is at 10 points regardless of the setting. 

### Describe the behavior you expected

The chunk output should use the same size font as the chunk editor.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
