### ISSUE TITLE
Data viewer on list column generates wrong links when filtered by search or by Filter

### ISSUE THREAD

**Issue by ahcyip** [rstudio/rstudio#7986]
### System details

$mode
[1] "desktop"

$version
[1] ‘1.3.1093’

OS Version      : Windows 10 enterprise
R Version       : 3.6.2

### Steps to reproduce the problem

test <- 1:10 %>% map(~seq(1:.x) %>% as_tibble()) %>% enframe()
View(test)

Then I use the magnifying glass and/or use the Filter funnel e.g. type in 8 

Then I click on the data frame icons in the list column and I get:

  > View(test[[2]][[1]])

### Describe the problem in detail

It looks like the Viewer has fixed links for data frames in list columns that are based on row number.
It looks like they don't adjust when search/filter shrinks the number of rows.

Please also see similar/related problem with list-column data frame links: #7985 

### Describe the behavior you expected

I expected to see the data frame that is described when I hover over the data frame icon (list(value = 1:8))

which is View(test[[2]][[8]])

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ahcyip** [comment]
Looks like this was filed previously as #7546

The View command that is written and run is clearly incorrect and based on the row number.

**Comment by ronblum** [comment]
@ahcyip Thank you for raising the issue, and pointing out that this is a duplicate! I'll close it as such, as we have the original to track.
