### ISSUE TITLE
Clearing Recent Project List

### ISSUE THREAD

**Issue by jaleo** [rstudio/rstudio#7988]
I do not know if this is a bug or an improvement but the problem is anoying.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5019
    OS Version      :  Windows 10
    R Version       :  3.6.0

### Steps to reproduce the problem
Open a Project in a Google File Stream Drive. -> Project is in the Recent Project List
Close rstudio
Close Google File Stream ->(Access to files is now impossible)
Open rstudio -> Project is in the Recent Project List, but is not opened.
Try to open the projet -> rstudio warnings you and deletes project from Recent Projet List (this is the problem)
Open Google File Stream
The recent project is no longer available.

### Describe the problem in detail
The problem is that rstudio deletes automatically the project from list if the unit in which resides is not available. And this situation is very frequent when uses cloud filesystems.

### Describe the behavior you expected
Maintain the recent project list even if the project is not available.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jaleo Thank you for filing this! Working with external drives and Cloud-based files is always a bit tricky. I'll mark this as an issue to review as we continue development of RStudio. (I'm not certain if this is a bug, enhancement, or by design, so I'll mark it as a bug for now.)
