### ISSUE TITLE
3rd outermost rainbow color parentheses have the same color as character in Idle Fingers theme

### ISSUE THREAD

**Issue by zerweck** [rstudio/rstudio#7989]
Activate Idle Fingers color theme and rainbow color parentheses, then type this somewhere:
```R
((""(""(((((())))))"")""))
```

The 3rd outermost parentheses matches the color of the characters and quotation marks color. This makes it harder to spot if the parentheses is itself part of a character vector or only next to one.

An example where it was confusing to me if the preceding character vector continues or ends before the closing parentheses:
![image](https://user-images.githubusercontent.com/5678151/95326303-a754aa80-08a2-11eb-8a4c-1846197c71a2.png)

It would be great if the rainbow colors somehow would avoid colors of objects next to them or at least can not take the color of other "surrounding" operators in the active scheme.

**Comment by ronblum** [comment]
@zerweck Thank you for filing this request! I'll mark it as an enhancement to consider as we continue development of RStudio.
