### ISSUE TITLE
Save output of the R console directly to a Word or pdf file

### ISSUE THREAD

**Issue by ArminNP** [rstudio/rstudio#7990]
There should be an easy way to capture the output from the console and directly save it in doc or pdf. I have searched but there doesn't appear to be one.

**Comment by ronblum** [comment]
@ArminNP Thank you for filing the request! Interesting suggestion—I'll mark it as an issue to review as we continue to develop and update RStudio.

**Comment by ArminNP** [comment]
Thank you! It would be really helpful.
