### ISSUE TITLE
Execute code in chunks in Normal mode not possible after switch to Visual Editor

### ISSUE THREAD

**Issue by statnmap** [rstudio/rstudio#7991]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.910
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem

- Create a Rmd
- Save Rmd
- Add a chunk with R code
- Execute a line of code using Ctrl + Enter : It works properly
- Switch to Visual Mode
- Save Rmd
- Switch back to Editor Mode
- Execute a line of code using Ctrl + Enter : It does not work anymore. 
- If you look at the "Code" Menu, all execution code actions are not usable

### Describe the problem in detail

I cannot execute code line by line in Editor after I used Visual Mode once

### Describe the behavior you expected

We should be able to switch from Visual to Editor mode without side effects (except appearance due to pandoc that is documented)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@statnmap Thank you for filing the issue! I can reproduce it, in my case on MacOS 11 Big Sur beta 8. Note that as a workaround, if you modify the file—such as adding a blank space and removing it—<kbd>Ctrl-Enter</kbd> works again. We will review this, though!

**Comment by kfeinauer** [comment]
Verified fixed on 1.4.1027
