### ISSUE TITLE
Exporting from viewer onto clipboard provides a nonsensical screenshot

### ISSUE THREAD

**Issue by kiernang** [rstudio/rstudio#7992]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1093
    OS Version      : Windows 10
    R Version       :  4.02

### Steps to reproduce the problem
Using a data.frame and the gt package (as well as dplyr):
```
example_df<- data.frame(a = c('This', 'Does', 'Not', 'Work'), b = c(0,0,0,0))
example_table <- example_df %>% gt () %>%
  tab_header(title = "Broken Export") %>% opt_row_striping(row_striping = TRUE) %>%
  tab_source_note(source_note = "This does not export properly")

example_table
```

From there, click 'Export' and then 'Copy to clipboard'. When you paste the picture, the picture will include your code.

### Describe the problem in detail
Trying to export a table from the viewer to an external report. When the table is copied to the clipboard, it is not the table, but instead a screenshot of the table as well as the code in the background. See attached picture.
![image](https://user-images.githubusercontent.com/66456229/95353807-fd861580-08c3-11eb-93a9-a0cd540c0119.png)

### Describe the behavior you expected
Expected just the table. Similar to below image.
![image](https://user-images.githubusercontent.com/66456229/95354251-7b4a2100-08c4-11eb-9f1d-37b1d563cab6.png)

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kiernang Thank you for raising the issue! We'll review it as a possible fix in the upcoming 1.4 Wax Begonia release.

**Comment by mikebessuille** [comment]
Consider for 1.5.  Need QA to reproduce this; does it happen all the time for copy to clipboard?

**Comment by kiernang** [comment]
Happens all the time.

**Comment by ronblum** [comment]
I can reproduce this on MacOS 11 Big Sur beta 10, as well. Note that this was the behavior in 1.2.5042, as well.

**Comment by iago-pssjd** [comment]
I can reproduce it on `Debian GNU/Linux 9.12 (stretch)` under RStudio 1.4.1103, as well.

**Comment by timtmok** [comment]
As I'm implementing the zooming actions in the Electron port, I noticed this in the Qt version. It seems to be triggered by setting a zoom level other than 100%. I think the code for retrieving the bounds of the area to export as an image doesn't handle the zoom level correctly so it copies the wrong part of the iframe.

**Comment by timtmok** [comment]
As for Electron, the viewer pane export is completely broken. Due to the change to Electron, the code needs to handle the portion of the viewer to export in a different way. It can't find the bounds of the viewer's contents.

**Comment by kevinushey** [comment]
We might just be able to execute the "copy image" command (or a similar Electron API for getting the current "view" captured as an image).

**Comment by timtmok** [comment]
Looks like the viewer might not always show an image. The reproduction example renders as a table in the viewer. I think we can use https://github.com/bubkoo/html-to-image to generate the image from the HTML but I'm not quite if it can do that with the iframe preview.

**Comment by timtmok** [comment]
I have a fix for Electron that also works with the zoom level. Electron has API to capture the page so this is the same as what Qt did but happens to work with all zoom levels.

**Comment by ronblum** [comment]
Verified that this works correctly in Electron, using RStudio Desktop 2022.06.0-daily-322 on MacOS 12.4.
