### ISSUE TITLE
Feature request: indent lines after `+`

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#7993]
Rstudio automatically indents lines after a `%>%` pipe.  It would be great if it did the same with lines following a line that ends with `+` so that ggplot chains are indented:

```
mtcars %>% 
   ggplot(x = mpg, y = cyl) + 
      geom_point() + 
      ggtitle("mtcars")
```

This helps visually set apart the components of the ggplot, rather than what happens now:
```
mtcars %>% 
   ggplot(x = mpg, y = cyl) + 
   geom_point() + 
   ggtitle("mtcars")
```

**Comment by ronblum** [comment]
@jzadra Thanks for the enhancement suggestion! We'll review your request as we continue developing and improving RStudio.

**Comment by iago-pssjd** [comment]
I fully agree with this FR. For the moment, it works within curly brackets as follows:
```r
mtcars %>% 
   {ggplot(., aes(x = mpg, y = cyl)) + 
      geom_point() + 
      ggtitle("mtcars")}
```
