### ISSUE TITLE
Feature request: "Reformat Code" should split pipe chains across lines.

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#7995]
It would be great if the "Reformat Code" function would split pipe chains across lines.  Currently it does so for function arguments (which actually I find to be annoying - perhaps this could be an option?), but does not do anything to pipe chains.  When highlighting the following code and choosing this option from the edit menu, nothing happens:

`mtcars %>% mutate(cyl2 = cyl*2) %>% mutate(hpcs = cumsum(hp))`

It would be nice if Reformat Code turned the above code into this:

```
mtcars %>% 
   mutate(cyl2 = cyl*2) %>% 
   mutate(hpcs = cumsum(hp))
```

**Comment by jmcphers** [comment]
If you want this behavior today, you can get it from the styler addin:

https://github.com/r-lib/styler

That'll give you a new Style Selection command which will format your pipe as you expect.
