### ISSUE TITLE
! Package caption Error: \caption outside float.

### ISSUE THREAD

**Issue by frankbach** [rstudio/rstudio#7997]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : MacOS 10.15.6
    R Version       : 4.0.2

I attach a log file since I don't at all understand what is happening, but have tried everything I know of.
[NPreligion.log](https://github.com/rstudio/rstudio/files/5343007/NPreligion.log)

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cderv** [comment]
This is not an issue with RStudio IDE I believe, but rather an error occuring during the rendering to PDF from your rmarkdown document, right ? 

> ! Package caption Error: \caption outside float.

This may means you have a caption for a table or a figure not correctly formatted and that is causing an error whild rendering to PDF ? 

Can you asked on https://community.rstudio.com in Rmarkdown catezgory by including some code example of what you have in your document ? 
I believe the RStudio Github Issue Tracker is not the right place to discuss such error - the community forum is better.

Thank you !

**Comment by ronblum** [comment]
Closing as per @cderv's recommendation above.
