### ISSUE TITLE
Python Global Environment Doesn't Register First Import When Automatically Switching from R to Python

### ISSUE THREAD

**Issue by chriscardillo** [rstudio/rstudio#7999]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.909
    OS Version      : Mac OS 10.15.2
    R Version       : 3.6.2

### Steps to reproduce the problem

Open RStudio and open a new .py file in the source editor. Make your .py file contain the following

```python
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

my_df = pd.DataFrame({"col1": [1, 2, 3], "col2": [4, 5, 6]})

sns.pointplot(x='col1', y='col2', data=my_df)
plt.show()
```

While your development environment is still set up for R (e.g. R REPL, R environment pane, etc.) run the the first like of the .py, `import pandas as pd`. The console will switch to Python REPL, but `pd` will not show up in the variable explorer. You will still be able to access `pd` functions, classes, etc., but it doesn't show up in the explorer. Now, if you continue to run lines, e.g. `import seaborn as sns`, you will see these subsequent variables, as RStudio is now set up as a Python environment.

### Describe the problem in detail

See above.

### Describe the behavior you expected

I expected, when I run the first line of the .py, `import pandas as pd`, that `pd` would be a variable I can see in the environment pane.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by chriscardillo** [comment]
@kevinushey - here you go! :)

**Comment by kfeinauer** [comment]
@kevinushey Attempting to verify this on 1.4.990. I just set up Python for the first time, selected my interpreter (`/usr/bin/python`) and am trying to use Ctrl + Enter on the first line in my test.py file (which matches Chris's above). 

The IDE is not automatically switching into Python mode, and is attempting to run `import pandas as pd` as R code, so I get an R error in the console:

> Error: unexpected symbol in "import pandas"

I have tried deleting my RStudio cache under ~/.local/share/rstudio and the problem persists. The first time I tried Ctrl+Enter, I was prompted to install the necessary R/Python packages, but since then it just seems to be stuck in a broken state.

Any ideas?

**Comment by kfeinauer** [comment]
I am able to use the reticulate package to manually get a REPL in the console like so:

```
> reticulate::repl_python()
Python 2.7.16 (/usr/bin/python)
Reticulate 1.18 REPL -- A Python interpreter in R.
>>> import pandas as pd
>>> 
```
I am using a fairly old version of R, 3.4.1

**Comment by kevinushey** [comment]
This might be a new bug: https://github.com/rstudio/rstudio/issues/8243

I'll take a look and see if I can figure out what's going on there.

**Comment by kfeinauer** [comment]
@kevinushey I am still seeing some weirdness around the first run of an import statement which kicks off the Python REPL.

On the latest daily, if I try to source the `import pandas as pd` script above, the first time I get the following error:

```
> reticulate::source_python('~/test.py')
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'module' object has no attribute '__import__' 
12.
stop(structure(list(message = "AttributeError: 'module' object has no attribute '__import__'", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("1   reticulate.so                       0x0000000110256fb4 _ZN4Rcpp9exceptionC2EPKcb + 196", 
    "2   reticulate.so                       0x0000000110256de5 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 53",  ... 
11.
initialize at loader.py#13
10.
loader$initialize(py_module_loaded) 
9.
py_inject_hooks() 
8.
ensure_python_initialized() 
7.
reticulate::import_builtins(convert = FALSE) 
6.
.rs.reticulate.onPythonInitialized() 
5.
callback() 
4.
initialize_python(required_module, use_environment) 
3.
ensure_python_initialized() 
2.
py_run_file(file, local = FALSE, convert = convert) 
1.
reticulate::source_python("~/test.py") 
```

On subsequent sources, the import works as expected.

**Comment by kevinushey** [comment]
@kfeinauer can you also share the output of `reticulate::py_config()`?

**Comment by kfeinauer** [comment]
@kevinushey 

```
> reticulate::py_config()
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.16 (default, Apr 17 2020, 18:29:03)  [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
numpy:          /Users/kfeinauer/Library/Python/2.7/lib/python/site-packages/numpy
numpy_version:  1.16.6
```
NOTE: Python version was forced by use_python function

**Comment by kevinushey** [comment]
Thanks! I'm able to reproduce now,

**Comment by kevinushey** [comment]
Should be fixed in the development version of `reticulate` with https://github.com/rstudio/reticulate/commit/4ccd71ab3fbce9f1d9781c0563fd52706817fe6c.

@kfeinauer if you are able to try and re-verify, you could do the following:

```
install.packages("remotes")
remotes::install_github("rstudio/reticulate")
```

Then, restart the IDE and re-run the repro steps.

The other thing you could try -- make sure you have Python 3 installed (e.g. via Homebrew or something similar), and then use:

```
reticulate::use_python("/usr/local/bin/python3", required = TRUE)
```

to force `reticulate` to bind to a Python 3 installation rather than the system-default Python 2.7.

**Comment by kfeinauer** [comment]
Thanks @kevinushey, looking good now.

Verified fixed with latest reticulate.
