### ISSUE TITLE
(un)comment lines in yaml

### ISSUE THREAD

**Issue by sfr** [rstudio/rstudio#8005]
It would be nice, if editor, when editing yaml document could comment and uncomment blocks of lines the same way as it's done in R Scripts.

![image](https://user-images.githubusercontent.com/2040557/95445349-38895700-095f-11eb-801d-c429fd632c07.png)

**Comment by ronblum** [comment]
@sfr Thank you for the suggestion! I'll mark it as an enhancement request for review during our ongoing development of RStudio.
