### ISSUE TITLE
Make ctx and suspended-session-data paths configurable

### ISSUE THREAD

**Issue by Debilski** [rstudio/rstudio#8007]
If I understand it correctly, RStudio server uses the `~/.rstudio/ctx` path to store some temporary session data, perhaps similarly to the path `~/.rstudio/sessions/active/session-xyz/suspended-session-data`.
The problem that we are experiencing is that our home folders are on a nfs network share and writing to these locations can take a long time (we’ve had 35GB written recently), bringing down the network access for everybody, and what’s worse is that the users are not aware when and why this is happening, nor that it is their process that does it.

I couldn’t find any setting that lets us change the location for this to a faster file system but I think this would be a nice addition. Otherwise our only option would be to deactivate suspension completely.

**Comment by ronblum** [comment]
@Debilski Thank you for raising the issue! We'll review this as we continue development of RStudio.

**Comment by jmcphers** [comment]
You can change the location of `~/.rstudio` in RStudio 1.4 and newer (currently in preview). Docs here:

https://docs.rstudio.com/ide/server-pro/1.4.912-1/r-sessions.html#user-state-storage

Preview here:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by kevinushey** [comment]
Verified in RStudio Server Pro 1.4.940-1, on Ubuntu 20.04.

Following instructions in https://docs.rstudio.com/ide/server-pro/1.4.912-1/r-sessions.html#user-state-storage, I used:

```
sudo systemctl edit rstudio-server
```

with the contents:

```
[Service]
Environment="XDG_DATA_HOME=/tmp/$USER"
```

After restarting RStudio Server and starting a new session, I see session state written to `/tmp/$USER`:

<img width="330" alt="Screen Shot 2020-10-16 at 1 35 09 PM" src="https://user-images.githubusercontent.com/1976582/96306378-6a7c6800-0fb4-11eb-8f5b-9105b55fce4a.png">
