### ISSUE TITLE
View(<DataFrame>) produces viewer with tab labeled "object"

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8010]
### System details

    RStudio Edition : All
    RStudio Version : 1.4.915
    OS Version      : macOS 10.15.6
    R Version       : 4.0.2

### Steps to reproduce the problem

(Note: requires a Python installation with `pandas` available.)

Open a Python script, and run:

```
mtcars = r["mtcars"]
View(mtcars)
```

### Describe the problem in detail

The viewer is opened, but the object is just called 'object'.

<img width="585" alt="Screen Shot 2020-10-08 at 10 49 29 AM" src="https://user-images.githubusercontent.com/1976582/95495210-f3135c80-0953-11eb-9714-ba2622e6a7a0.png">

### Describe the behavior you expected

If at all possible, we should preserve the "real" name of the object.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
if this is complicated or risky to fix, we should consider fixing it for 1.4-Juliet-Rose.

**Comment by melissa-barca** [comment]
Verified in 1.4.1013
