### ISSUE TITLE
auto number or rename chunks when a chunk is divided

### ISSUE THREAD

**Issue by sbalci** [rstudio/rstudio#8019]
Hi,
When I divide a chunk, it keeps same chunk name. Would it be possible to add a suffix or prefix to that name automatically.
See image. I would like it to be "something-1" "something-2"

<img width="549" alt="Ekran Resmi 2020-10-09 12 25 16" src="https://user-images.githubusercontent.com/7208830/95604259-11667e80-0a60-11eb-92d4-7c81b4d92484.png">

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/6364.
