### ISSUE TITLE
Shortcut 'Close' quits RStudio

### ISSUE THREAD

**Issue by hamedbh** [rstudio/rstudio#8029]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.904
    OS Version      : macOS 10.15.7
    R Version       : 4.0.2

### Steps to reproduce the problem

With no files open press CMD + W

### Describe the problem in detail

I pressed CMD + W several times to close open scripts. Pressed it once more than the number of files I had open, this quit RStudio. 

I have tested this again several times with the same results. 

### Describe the behavior you expected
I expected nothing to happen, as I expect the Close shortcut to only close files and not quit the application. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is standard behavior for macOS apps. If you try it in e.g., Chrome, Safari, or VS Code, you'll see that <kbd>Cmd</kbd><kbd>w</kbd> closes a tab, but if you press it with no tabs open it closes the whole window.

We aren't totally standard here; most macOS apps have a state wherein they are still running even if they have no windows open, whereas when you close RStudio's main window it quits outright. Were you expecting RStudio's main window to close but for the app to still be running (so you could e.g., start a new R session?).

**Comment by hamedbh** [comment]
I don't think this is standard behaviour for Mac apps. There is a distinction between Close (<kbd>Cmd</kbd> + <kbd>W</kbd>) and Quit (<kbd>Cmd</kbd> + <kbd>Q</kbd>) in the vast majority of Mac apps, including the three you mentioned (Chrome, VS Code, and Safari): 

- Close will close the window _but the app keeps running_; 
- Quit will kill the app. 

Whereas in the version of RStudio referenced above, 1.4.904, Close has the same effect as Quit. I tried reverting to the stable release version (1.3.1093) and it behaves the same. 

Chrome on Mac even prevents a user quitting with a quick press of <kbd>Cmd</kbd> + <kbd>Q</kbd>, forcing the user to hold them down so that it's a confirmed Quit action. 

I'd say the current RStudio behaviour is undesirable for at least two reasons: 

1. Users can lose objects in the Global Environment by pressing <kbd>Cmd</kbd> + <kbd>W</kbd> one time too many; 
2. It's not consistent with the app on Windows, where there's a distinction between <kbd>CTRL</kbd> + <kbd>W</kbd> and <kbd>Alt</kbd> + <kbd>F4</kbd>. 

Re. point 1: I know it's bad practice to rely on the Global Environment as storage, and I don't. But this bit me at a point where I was in the middle of analysis and had objects in memory that had taken 30 mins + to create, so it definitely cost me some time!

**Comment by kevinushey** [comment]
For what it's worth, you can close tabs without closing RStudio via <kbd>Ctrl + W</kbd>, as opposed to <kbd>Cmd + W</kbd>.
