### ISSUE TITLE
Loading usethis breaks rstudioapi

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#8031]
```R
devtools::load_all("~/documents/devtools/usethis")
rstudioapi::versionInfo()
#> Error in utils::packageVersion(x) : there is no package called ‘1.4.869’
```

Traceback:

```
    █
 1. └─rstudioapi::versionInfo()
 2.   └─rstudioapi::callFun("versionInfo")
 3.     └─global::f(...)
 4.       └─usethis::package_version(info$version)
 5.         └─utils::packageVersion(x) R/latest-dependencies.R:37:2
```

It seems like `callFun()` is looking in the wrong place — it should never look in the global env.

**Comment by hadley** [comment]
@mikebessuille I think that's unlikely — I'm pretty sure this will only affect package developers, and only if the package includes a function with the same name as a base R function that rstudioapi uses. (So I think it's mostly an annoyance to the developers of the usethis package, but it may affect other packages and they just didn't know where to report the problem)

**Comment by mikebessuille** [comment]
Thanks Hadley.  Given that information, at this stage of the 1.4 release we need to only be looking at critical fixes.  moving this to 1.5

**Comment by kevinushey** [comment]
Simpler reprex:

```
> package_version <- function(...) { stop("oops") }
> .rs.api.versionInfo()
 Error in package_version(info$version) : oops 
```

Basically, if someone happens to mask one of the base functions used by any of our APIs, they could break -- which is pretty brittle.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/189ea233a6bcda93f78c75fb42277722ace4fe70 is a 1.4-safe bandaid for this particular iteration of the issue, but we should really assess if we could (should?) better control the evaluation environment for API functions (but thats for 1.5)

**Comment by jennybc** [comment]
I found this issue by accident but for the record I fixed it in usethis a couple of weeks ago:

https://github.com/r-lib/usethis/commit/32949d6f20c61a8723d2d94899ccc3f819d21b95

So this should either be closed or be generalized to guarding against the problem in the future.

**Comment by jennybc** [comment]
This is still a problem (yes, mostly for usethis). For example, internally usethis has switched entirely to withr and I actually mask `on.exit()` in order to force use of `defer()`. I wanted to add this story to this issue, because there are legitimate reasons that a package developer might mask a base function and, if that happens to overlap with any function used by rstudioapi, it's very painful.

**Comment by kevinushey** [comment]
I think the proper fix for this is to have two environments:

- One environment on the search path, which contains all of our internal functions;
- Another environment, which all our functions use as a parent environment, for symbol lookup.

In other words, the environment where our functions live (on the search path) would be different from the environment used for evaluation (internally referenced by functions placed on the search path). The second environment would be constructed explicitly by us, using the base R packages that we know we require.

For extra color, here's what the environment chain looks like now for internal functions vs. API functions:

```
> library(pryr)
> parenvs(.rs.activateGraphicsDevice)
   label                            name               
1  <environment: 0x12a70c0c8>       "tools:rstudio"    
2  <environment: package:stats>     "package:stats"    
3  <environment: package:graphics>  "package:graphics" 
4  <environment: package:grDevices> "package:grDevices"
5  <environment: package:utils>     "package:utils"    
6  <environment: package:datasets>  "package:datasets" 
7  <environment: package:methods>   "package:methods"  
8  <environment: 0x159930b98>       "Autoloads"        
9  <environment: base>              ""                 
10 <environment: R_EmptyEnv>        ""                 
> parenvs(.rs.api.versionInfo)
  label                      name
1 <environment: R_GlobalEnv> ""
```

Note that our "internal" functions depend on where `tools:rstudio` is on the search path, so users could in theory something like the following to mess things up. For example:

```
> envir <- as.environment("tools:rstudio")
> detach("tools:rstudio")
> attach(envir, name = "tools:rstudio", pos = length(search()))
> parenvs(.rs.activateGraphicsDevice)
  label                      name           
1 <environment: 0x12a70c0c8> "tools:rstudio"
2 <environment: base>        ""             
3 <environment: R_EmptyEnv>  ""             
Error in object.size(obj) : could not find function "object.size"
```

To the best of my knowledge, this hasn't happened in practice but the fact that it's relatively simple to do is a bit worrisome.

**Comment by hadley** [comment]
@kevinushey that sounds like the right structure to me, because it basically matches what packages do (where "another" environment = the imports environment)

**Comment by mikebessuille** [comment]
@jgutman probably an issue you'd want to look at, but this is not a "good first issue" :)

**Comment by romainfrancois** [comment]
Verified with the original example (loading `usethis`)

``` r
devtools::load_all("~/git/usethis")
#> ℹ Loading usethis
#> ✔ Setting active project to '/Users/romainfrancois/git/usethis'
rstudioapi::versionInfo()
#> $mode
#> [1] "server"
#> 
#> $version
#> [1] '2022.2.999.999'
#> 
#> $long_version
#> [1] "2022.02.999-dev+999"
#> 
#> $release_name
#> [1] "Spotted Wakerobin"
```

and the simpler reprex from Kevin: 

``` r
package_version <- function(...) { stop("oops") }
.rs.api.versionInfo()
#> $mode
#> [1] "server"
#> 
#> $version
#> [1] '2022.2.999.999'
#> 
#> $long_version
#> [1] "2022.02.999-dev+999"
#> 
#> $release_name
#> [1] "Spotted Wakerobin"
```
