### ISSUE TITLE
Changed behaviour in insertText?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#8032]
I have an addin that I've been using for a while that uses `insertText()` ([inserts dashes until column 80](https://github.com/mine-cetinkaya-rundel/addmins/blob/15af1bdd9e97209cac58420b0f4ca74a34322049/R/insert_dashes.R#L19)). The behaviour of the addin changed recently such that the text is selected after being inserted, and I haven't touched my code so I think the new behaviour might be due to a recent change in `insertText()`. I was wondering if this is intended behaviour or not. If it's here to stay I'll update my addin but I wanted to ask here first in case that was an unintended change.

**Comment by kfeinauer** [comment]
Verified fixed on version 1.4.944
