### ISSUE TITLE
Unicode characters in data frame columns do not appear as-is in Environment Viewer

### ISSUE THREAD

**Issue by calpan** [rstudio/rstudio#8033]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.904
    OS Version      : Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Create a data frame containing a column with Unicode characters in it.

### Describe the problem in detail

Unicode characters within data frames are not shown as-is.  A similar issue (#6877) was fixed in #7370.

```
d = data.frame(xi='ξ')
```

![rstudio_2020-09-27_21-43-48](https://user-images.githubusercontent.com/806424/94391566-aab19e80-010a-11eb-91cc-c6f2e919e405.png)

### Describe the behavior you expected

The Unicode characters should be shown in their un-encoded form.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is just the default behavior of R's `str()` method, which forces this transcoding. To fix this we'd have to implement our own version of `str()`.

**Comment by ronblum** [comment]
Note: this appears to be limited to RStudio Desktop on Windows. It works as expected on MacOS 11 and in RStudio Server on Red Hat 8.2.
