### ISSUE TITLE
Feature Request: Python Support: Help Pane

### ISSUE THREAD

**Issue by jtelleriar** [rstudio/rstudio#8037]
When pressing F1 for accessing to Python Function / Method Documentation:

This does work, and show the documentation as expected:
```{python}
ObjectName.MethodName()
```

But the second case does not:
```{python}
ObjectName\
     .MethodName()
```
Would it be possible to make the second case also work?

It is a stopper for me for not moving to Python programming to RStudio, and still relying on Pycharm.

Thank you in advance!

**Comment by melissa-barca** [comment]
Verified in 1.4.1013
