### ISSUE TITLE
Can't close files on v1.4.922

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#8038]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.922
    OS Version      : Windows 10 Enterprise 64-bit
    R Version       : 4.0.2 64-bit

### Steps to reproduce the problem

Open any R script then try closing it

### Describe the problem in detail

Cannot close file either using Ctrl + W or using left mouse on X button

### Describe the behavior you expected

File's gone

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be fixed in next dailies.

**Comment by kfeinauer** [comment]
Verified on 1.4.1032
