### ISSUE TITLE
RStudio cannot incorporate ulimit change made in .bashrc

### ISSUE THREAD

**Issue by gundalav** [rstudio/rstudio#8039]
Currently in my RStudio I ran this code with this error:

    > library(gtools)
    > nrow(combinations(n=448,r=2,v=1:448,repeats.allowed=F))
    Error: C stack usage  7971524 is too close to the limit

What I did, is I add this line 

    ulimit -s 16384

in my bashrc.

The R code above runs ok if I execute it with R console in my terminal.
But it still gives an error when I run it RStudio console.

How can I fix the issue?

**Comment by ronblum** [comment]
@gundalav Thank you for filing the issue. Can you please provide the system details you are using so that we can review?


    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by technocrat** [comment]
Same issue as [8067](https://github.com/rstudio/rstudio/issues/8067), which has MWE

**Comment by jmcphers** [comment]
RStudio Desktop doesn't run your `bashrc`, so you can't change the ulimit there; you'd need to have whatever launcher you're using with Ubuntu set the ulimit for the process.

**Comment by Steviey** [comment]
Launcher???
