### ISSUE TITLE
snippets currently don't work in visual mode

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8044]

**Comment by kevinushey** [comment]
Seems to work fine for me:

![visual-snippets](https://user-images.githubusercontent.com/1976582/95897087-cd19fd80-0d41-11eb-8038-431f6a1984bd.gif)

**Comment by kevinushey** [comment]
@hadley confirmed that this is snippets for Markdown mode (triggered via <kbd>Shift + Enter</kbd>). Unfortunately, snippets are currently only available for Ace so it's expected that snippets won't work in this case.

Is getting this to work something worth exploring? Does prosemirror have its own concept of snippets / snippet completions?

**Comment by jjallaire** [comment]
No prosemirror doesn't have snippets. The closest thing it has is input rules (which is what we use for markdown shortcuts) but nothing as elaborate as what Ace does for snippets. I don't think we can get this to work for this release.

**Comment by jmcphers** [comment]
Requested on community forum: https://community.rstudio.com/t/markdown-snippets-in-visual-mode/95162/2

**Comment by TarjinderSingh** [comment]
Inserting snippets in the Markdown part using Shift+Tab doesn't work in visual mode (https://support.rstudio.com/hc/en-us/articles/204463668-Code-Snippets). At the moment, I switch between the visual and rmarkdown mode to get that functionality.

**Comment by jjallaire** [comment]
The equivalent here would probably by `Cmd/Ctrl + /` (omin-insert) which lets you insert many types of markdown construct or as mentioned before input rules. We won't therefore support generic raw markdown snippets in visual mode.
