### ISSUE TITLE
Update to Qt 5.15.1

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8045]
Opening issue to track updating RStudio Desktop to Qt 5.15.1, to get fixes in the newer QtWebEngine/Chromium.

Based on problems found in initial test builds, we're scaling back to only considering updating Qt for macOS Desktop for 1.4.

### Issues possibly fixed by this update ###
https://github.com/rstudio/rstudio/issues?page=1&q=is%3Aissue+is%3Aopen+label%3Aqtwebengine

### Workarounds that _might_ no longer be needed in our code ###

Mouse back/forward button clicks:
- https://bugreports.qt.io/browse/QTBUG-85360
- https://github.com/rstudio/rstudio/pull/7272

Scrollbars on macOS:
- https://bugreports.qt.io/browse/QTBUG-65745
- https://github.com/rstudio/rstudio/issues/1953

**Comment by gtritchie** [comment]
Resolving as out-of-scope now that we're not upgrading to 5.15 for RStudio 1.4.

**Comment by paulmenzel** [comment]
Our distribution is going to update from Qt 5.12 to 5.15, so I am wondering, what the corresponding issue and maybe feature branch for RStudio is? Is the update plan publically accesible?

**Comment by jmcphers** [comment]
There's a feature branch here, but this work is not likely to ever be merged (we are hoping to transition away from Qt entirely). https://github.com/rstudio/rstudio/tree/feature/qt-5.15.1
