### ISSUE TITLE
Update to CRAN version of rmarkdown

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8046]
PR https://github.com/rstudio/rstudio/pull/8042 started embedding the rmarkdown package from Github; we need to  switch back to the CRAN version once a version of the rmarkdown package supporting Pandoc 2.11 (rmarkdown >= 2.5) is on CRAN.

**Comment by cderv** [comment]
FYI **rmarkdown** 2.5 has been released to CRAN
https://github.com/rstudio/rmarkdown/releases/tag/v2.5

**Comment by jjallaire** [comment]
IDE now points at CRAN: https://github.com/rstudio/rstudio/commit/a635f9a10ce7b444255b0d5d0bdc052f929488b9

**Comment by gtritchie** [comment]
Verified that RStudio build 1.4.959 installs rmarkdown from CRAN and not github.
