### ISSUE TITLE
Remove support for IE11

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8052]
RStudio Server currently supports Internet Explorer 11. This browser will be supported by Microsoft itself for a very long time (perhaps 2025) as it's considered a Windows component. 

https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge

However, Microsoft's _own web properties_ have decided to drop IE11 support significantly before this date. Office 365, Microsoft's flagship office suite, will stop supporting IE11 in August 2021.

https://support.microsoft.com/en-us/office/which-browsers-work-with-office-for-the-web-ad1303e0-a318-47aa-b409-d3a5eb44e452

> Microsoft 365 apps and services will not support Internet Explorer 11 starting August 17, 2021

It is probably not necessary for us to extend more support to IE11 than Microsoft themselves; we do not yet have a release date for RStudio 1.5, but late 2021 is an approximate enough ballpark that it make sense to signal dropping support with the 1.5 release.

See also: https://death-to-ie11.com/

**Comment by gtritchie** [comment]
Yes, Yes, a zillion times YES!

**Comment by mikebessuille** [comment]
Definitely should do this for 1.5!   Was accidentally moved out in a bulk move.

**Comment by jmcphers** [comment]
We wound up doing this in Juliet Rose due to Microsoft's announcement ending IE11 support for Teams.

**Comment by jmcphers** [comment]
Fixed in PR: https://github.com/rstudio/rstudio/pull/9054

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1671-1, R Version - 4.0.4, RHEL7 - Server 

Attempting top open an R Session in IE11 now presents the user with a page informing them that the current browser is not supported and lists our supported browsers as well as a link to [Platform Support](https://www.rstudio.com/about/platform-support/).
