### ISSUE TITLE
Rmd {cpp11} chunks should highlight like {Rcpp} chunks

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#8062]
Highlighting currently defaults to R code. i.e. compare the two images below:

<img width="599" alt="Screen Shot 2020-10-14 at 1 12 20 PM" src="https://user-images.githubusercontent.com/19150088/96022510-f8bee580-0e1e-11eb-8e78-3b3307753f1d.png">
<img width="573" alt="Screen Shot 2020-10-14 at 1 12 29 PM" src="https://user-images.githubusercontent.com/19150088/96022517-fb213f80-0e1e-11eb-8e3c-ca4abc0fabc1.png">

**Comment by kevinushey** [comment]
Marking at 1.4 since this should be a straightforward fix.

**Comment by kevinushey** [comment]
Closed via https://github.com/rstudio/rstudio/pull/8064.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.949
