### ISSUE TITLE
Notebooks do not preview with older xfun package

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8063]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.930

### Steps to reproduce the problem

1. Install version 0.13 of the xfun package
2. Click File -> New R Notebook
3. Click Preview in the editor toolbar

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/470418/96027092-3c5c2400-0e0c-11eb-99a0-f3caae6342cd.png)

### Describe the behavior you expected

You should be prompted to install a newer version of `xfun` so that notebook preview works correctly.

The rmarkdown package appears to rely on a newer version of xfun, as `base64_encode` doesn't exist in version 0.13.

**Comment by melissa-barca** [comment]
Verified fix in 1.4.938.
