### ISSUE TITLE
cannot View objects after calling source_python

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8065]
At the beggining of an R script, I call:

.
library(reticulate)
use_python("C:\\Users\\jpuig\\Anaconda3\\envs\\tf_gpu\\python.exe", required = TRUE)
source_python("expICH/00_core/expICH_functions.py")
.

expICH_functions.py looks like:

import pandas as pd
import numpy as np

def function1():
.
def functionN():

As soon as the source_python function gets called, any variable I create in the R environment can't be visualized, I got the following errors:

![image](https://user-images.githubusercontent.com/9660118/96027810-b9ad8600-0e58-11eb-84fd-8ea97eeb67de.png)

_Originally posted by @jpuig005 in https://github.com/rstudio/rstudio/pull/6862#issuecomment-708573296_

**Comment by melissa-barca** [comment]
Verified in 1.4.944 on macOs.
