### ISSUE TITLE
toggling visual mode unwantedly alter the structure of source document

### ISSUE THREAD

**Issue by enixam** [rstudio/rstudio#8069]
I am using the rmarkdown document 

```
---
title: "Test of visual mode" 
output: bookdown::pdf_document2: default 
---

$$
a ^ 2 + b^2  = c^2
$$ 
one paragraph under latex formula

$$
(a + b)^2 =  a^2 + 2ab + b^2
$$ 
another paragraph

another paragraph

another paragraph
```

If I do not include an empty line between equations and a normal paragraph, toggling visual mode and then switch back to source editor will move the paragraph upwards to the end of the latex block. The R Markdown document becomes 

```
---
title: "Test of visual mode" 
output: bookdown::pdf_document2: default
---

$$
a ^ 2 + b^2  = c^2
$$ one paragraph under latex formula

$$
(a + b)^2 =  a^2 + 2ab + b^2
$$ another paragraph

another paragraph

another paragraph

```

While this behaviour does not change the output, it could mess up the source document. There will be 

- falsely recognized chunk 

- no automatic latex preview

![image](https://user-images.githubusercontent.com/48123899/96084673-0d1fe280-0ef2-11eb-9b47-29d68d7ae3de.png)

while the look of oringinal source document is 

![image](https://user-images.githubusercontent.com/48123899/96085125-ea41fe00-0ef2-11eb-876f-dea83289ab75.png)
 

session info 

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362), RStudio 1.4.904

Locale:
  LC_COLLATE=English_United States.1252 
  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    
system code page: 936

Package version:
  base64enc_0.1.3 compiler_4.0.2  digest_0.6.25   evaluate_0.14  
  glue_1.4.2      graphics_4.0.2  grDevices_4.0.2 highr_0.8      
  htmltools_0.5.0 jsonlite_1.7.1  knitr_1.30      magrittr_1.5   
  markdown_1.1    methods_4.0.2   mime_0.9        rlang_0.4.8    
  rmarkdown_2.4   stats_4.0.2     stringi_1.5.3   stringr_1.4.0  
  tinytex_0.26    tools_4.0.2     utils_4.0.2     xfun_0.18      
  yaml_2.2.1   
```

**Comment by jjallaire** [comment]
We don't control writing of markdown at a granular level --- it's all done by pandoc. So when pandoc sees that construct it re-writes it w/ it's logical equivalent according to it's "canonical" form. There are a number of other instances of this we've identified: https://rstudio.github.io/visual-markdown-editing/#/markdown?id=markdown-output.

Ultimately this is just a tradeoff for using the visual editor (you need to change the way you write/edit in the source editor). If the pandoc conventions for writing markdown are not tenable for you then it's better to not use visual mode.
