### ISSUE TITLE
FR: Default five-pane / three-column layout option

### ISSUE THREAD

**Issue by francisbarton** [rstudio/rstudio#8071]
Alternative title for this issue: Allow splitting non-Console/Source panes across three quadrants not just two.

I really like the new option to open an extra column/pane for Source. In fact I like it so much that I would like to make it my default layout, and have the option to never use the "old" Source quadrant pane.

This would mean that I would then potentially have the ability to either:
a. keep a [three-quadrant layout](#2854) plus the Source column, by having the old Source quadrant permanently unused, or
b. use the "old" Source quadrant for something else, such as (ref screenshot below) select Environment only in the top middle area and Plots and Viewer in the bottom middle area, for example.

... or other things!

edit: I have edited and re-uploaded screenshot below to better show what I mean in `b.` above:

![image](https://user-images.githubusercontent.com/1819920/96928552-9fa32180-14b0-11eb-837e-91fb8b97b9a8.png)

Some connection to #7919.

**Comment by ronblum** [comment]
@francisbarton Thank you for the suggestion! We'll review it as we continue development of RStudio. And, I'm glad to hear that you're enjoying having multiple source panes!

**Comment by stla** [comment]
Wow I was not aware of this new feature. I'm currently developing some [HTML widgets](https://github.com/stla/monaco) which provide an additional source editor in RStudio. Anyway I have fun with developing them :-) And Monaco is better than Ace for JavaScript.

**Comment by francisbarton** [comment]
I think this is fixed now - or at least its aim is included in the goals of some of the epics around panes and layout. Basically, more often than not, I get the extra Source pane by default when launching a project, which is what this was mostly about.
