### ISSUE TITLE
inline code chunk in Rmarkdown does not exectute for preview anymore and is changed to block code chunk

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#8074]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.938
    OS Version      :  WINDOWS
    R Version       :  4.0.2

### Steps to reproduce the problem

* Open a rmarkdown file
* Type some text with inline code 
````md
---
title: "test.Rmd"
output: html_document
---

Add some inline code `r 1+1`
````
* Save (you'll see some changes in the interface)
* Try to execute the inline code for previewing - won't work
* Open the icon menu to change the chunk name for example (this should not be possible)
* it will overwrite the text

### Describe the problem in detail

* When saving, RStudio will show the icon bar usually shown for Code blocks not inline code. 
* Trying to execute the inline code for previewing won't work. Something empty is sent to consol (see the `>` added in the console each time CTRL+ENTER is hit
* Try to use the icon bar that should not be there: you'll be able to enter a chunk name but... it will replace your source code 

![inline-code](https://user-images.githubusercontent.com/6791940/96146552-b244b600-0f06-11eb-9ee0-9b3b3420ce49.gif)

### Describe the behavior you expected

It should work like before: inline can be previewed and it is not seen as code chunk by RStudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for reporting! Should be fixed in the next daily builds.

**Comment by cderv** [comment]
You're welcome! I'll keep them coming while using the daily if any.

**Comment by melissa-barca** [comment]
Verified in 1.4.944 on macOS.
