### ISSUE TITLE
segfault when executing inline chunks

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8076]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.900
    OS Version      : macOS 10.15.7
    R Version       : 4.0.2

### Steps to reproduce the problem

Create an R Markdown document with the contents:

```
`r 1 + 1`
```

Then, place the cursor within that inline chunk, and try to execute it (e.g. with <kbd>Cmd + Enter</kbd>).

### Describe the problem in detail

RStudio crashes.

### Describe the behavior you expected

The chunk should be executed without issue.

### Notes

Appears to have broken with one of these recent commits: https://github.com/rstudio/rstudio/commits/0e568659

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Verified in 1.4.944 on macOs.
