### ISSUE TITLE
Link in comment fails to open in web browser with "Safari.app is not open anymore"

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8080]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.xxxx (experimental private build for Qt 5.15.1 evaluation)
    OS Version      : macOS (version?)
    R Version       : any

### Steps to reproduce the problem

- have a comment with url "https://hackage.haskell.org/package/pandoc-types-1.20/docs/Text-Pandoc-Definition.html"
- cmd + click on it

### Describe the problem in detail
- get an error "The application Safari.app is not open anymore" (which is not true)

### Describe the behavior you expected
- link opens in browser

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I wasn't able to reproduce on macOS 10.15.7. @gtritchie, were you testing with a Big Sur beta by any chance? Do things work if you use Chrome as the default browser instead of Safari?

**Comment by gtritchie** [comment]
This was originally reported to me by @jjallaire in Slack (and he heard about it from @hadley); I have not been able to repro on Catalina or Big Sur, whether Chrome or Safari is set as default browser.

**Comment by hadley** [comment]
BTW it went away for me after rebooting, and I haven't seen it again.

**Comment by mikebessuille** [comment]
Several people can't repro, so closing this for now.

**Comment by gtritchie** [comment]
Resolving as out-of-scope now that we're not upgrading to 5.15 for RStudio 1.4.
