### ISSUE TITLE
Broken pipe errors from stream capture thread can fill disk quickly

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8082]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1073

### Steps to reproduce the problem

Run a command in R which streams a lot of output, then do something that breaks the file descriptors that capture the output streams (we don't know how this happens)

Originally from https://rstudioide.zendesk.com/agent/tickets/53571.

### Describe the problem in detail

The logs are quickly overwhelmed with errors that look like this: 

```
ERROR system error 32 (Broken pipe); OCCURRED AT rstudio::core::system::{anonymous}::standardStreamCaptureThread(int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&, int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&)::__lambda0 src/cpp/core/system/PosixOutputCapture.cpp:78; LOGGED FROM: rstudio::core::system::{anonymous}::standardStreamCaptureThread(int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&, int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&)::__lambda0 src/cpp/core/system/PosixOutputCapture.cpp:78
```

These can fill up a disk quickly enough to crash the server and have been observed doing so.

### Describe the behavior you expected

We already specifically exclude `EAGAIN` and `EINTR` from this error logging, possibly for similar reasons.

https://github.com/rstudio/rstudio/blob/f23c1df50290b9e6f2bd9b2ecebca19b1c39bbf0/src/cpp/core/system/PosixOutputCapture.cpp#L76-L81

We should make sure this can't happen by:

- Also suppressing `EPIPE`, and/or
- Suppressing multiple instances of the same error being logged back to back (or some other cool-off mechanism)

**Comment by R-Hannibal** [comment]
I reached out to the CS Rep working on the zendesk ticket (https://rstudioide.zendesk.com/agent/tickets/53571) to inform them that the fix is ready, but until then we do not have repro steps to verify this fix is working.
