### ISSUE TITLE
HTML range input (slider) is not pretty in the viewer pane

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#8087]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.3

### Steps to reproduce the problem

Make a HTML widget with an `<input type="range"/>` element.

### Describe the problem in detail

The range input (slider) is not pretty in the viewer pane:

![viewerPaneRangeInput](https://user-images.githubusercontent.com/4466543/96255166-bf20e280-0fb6-11eb-8486-75240ec55b3f.png)

### Describe the behavior you expected

I expect to see a prettier slider. In Chrome it is blue with a round thumb. Here it is very sober. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by stla** [comment]
Found [a way to customize the slider](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/). Works fine!

**Comment by ronblum** [comment]
@stla Thank you for raising this! We'll review to determine, in part, whether this is an issue to address or if this is by design. So I'll mark it as a bug first.
