### ISSUE TITLE
Closing All Except Current does not keep the correct file

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#8092]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.944
    OS Version      :  WINDOWS 10
    R Version       : 4.0.2

### Steps to reproduce the problem

* Open several files in the source pane (Rmd, R files, ...)
* Create a new R file - it will be untitled
* Write in this R file **but don't save**
* Select one of the other saved file
* Click on File > Close All Except current
* A pop up will open to ask if you wan't to save Untitled file - **anwer don't save**
* It will close all except... the untitled file you explicitly say to not saved. 

### Describe the problem in detail

* When Closing all except one , the incorrect file is kept in the source pane

![closing-1 4](https://user-images.githubusercontent.com/6791940/96294832-438e5800-0fed-11eb-93cc-f6f57aec3d5c.gif)

### Describe the behavior you expected

Same as in RStudio 1.3 - the correct file is kept. 

![closing-1 3](https://user-images.githubusercontent.com/6791940/96294821-3ec9a400-0fed-11eb-8ebb-f8f63d6bf802.gif)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.949
