### ISSUE TITLE
Option to re-run old jobs with same parameters

### ISSUE THREAD

**Issue by TylerGrantSmith** [rstudio/rstudio#8094]
I am hoping that it would be possible to add a button that allows you to re-execute an old job from the jobs pane, maybe by clicking on the job and hitting a 're-run' button, or adding a re-run button where the stop button is for currently running jobs.  It should use the same parameters (e.g. if export global environment was selected the first time, I would expect it to use that option).

**Comment by gtritchie** [comment]
Tracked by #5548, closing this as a dup.
