### ISSUE TITLE
Visual Markdown editor replaces URL-encoded sequences in image URLs

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#8099]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.945 (daily build)
    OS Version      :  MacOS 10.15.7
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Enter markdown image tag with URL containing %20 for spaces
2. Switch to visual markdown editor using button
3. Switch back to normal editing mode

The %20 sequences are replaced by regular spaces. This makes the image URL not work e.g. in a README.md file on Github.

This does not happen to regular links, only images. It occurs in .md and .Rmd files.

### Describe the problem in detail

Before:

![image](https://user-images.githubusercontent.com/1666657/96340157-04b5dc00-1099-11eb-9001-677399f15b73.png)

After switching to Visual Markdown editor:

![image](https://user-images.githubusercontent.com/1666657/96340290-0ed7da80-1099-11eb-8400-71ad705a03c5.png)

After switching back:

![image](https://user-images.githubusercontent.com/1666657/96340389-15fee880-1099-11eb-9fb4-a5852f10cb51.png)

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Thanks for this! Should be fixed here: https://github.com/rstudio/rstudio/commit/4fd73a0d33883a7624b0eb5ac79a1ee7252ba0a4 (will be in tomorrow's daily build)

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
