### ISSUE TITLE
Error: Rstudio unable to establish connection with R session

### ISSUE THREAD

**Issue by DChuguashvili** [rstudio/rstudio#8100]
When I start my Rstudio, no matter which button I click or whatever I do, this "Error: Unable to establish connection with R session" pop up. 
I have no Antivirus.
I have already tried to uninstall and reinstall R and Rsdtudio, also the previous version.
clear all old files corresponding to R/Rstudio.

But no result, there is the same error,
what should I do?
![Error](https://user-images.githubusercontent.com/64915274/96349189-eb278b00-10be-11eb-9dc6-13ac6c92d15a.PNG)

**Comment by kevinushey** [comment]
You can try resetting RStudio's state: https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
