### ISSUE TITLE
Don't Save file button not working

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#8102]
### System details

    RStudio Edition  Server
    RStudio Version : 1.4.949
    OS Version      : ubuntu 18
    R Version       : 4.0.2

### Steps to reproduce the problem
1. open a few new files (r script, text, python)
2. go to File -> Close All
3. a popup should display prompting the user to save changes
4. click the "don't save" button

<img width="1544" alt="Screen Shot 2020-10-19 at 9 31 30 AM" src="https://user-images.githubusercontent.com/43964690/96465279-663b8f00-11ee-11eb-95bf-e10e47d7f739.png">

### Describe the problem in detail
nothing happens
### Describe the behavior you expected
the popup is closed and files are not saved

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
This problem seems to be unique to linux - I could reproduce there but not on my mac (haven't tried windows).

**Comment by kfeinauer** [comment]
Verified fixed RStudio 1.4.954
