### ISSUE TITLE
citations missing after installing citr on Rstudio preview 1.4

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#8104]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4 Preview
    OS Version      : Ubuntu 20.04
    R Version       : 4.01

### Steps to reproduce the problem

On a project without the citr package open a document (.Rmd) edit in visual mode to include some citation  and build it (In my case it was a bookdown, but I think this will be common).
Install citr package and build it again. It will report that those `pandoc-citeproc: reference x not found`.

### Describe the problem in detail

citr package BibLaTex and the default citekey without installing it aren't compatible or at least not the same. This leads to missing references that appear as [????] 

### Describe the behaviour you expected

I would expect no errors/warnings about reference not found. 
Additionally when I open the add visual edition of citations the view of the document moves to the top. I would like to stay on the same position I was before. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Yes we definitely should look at this for v1.4 if there is the potential to break people's documents.

**Comment by dragonstyle** [comment]
Hi -thanks for reporting this issue. I'm working to reproduce this and having some trouble. Can you share sample documents/bibliographies that demonstrate the issue?

**Comment by llrs** [comment]
Thanks for the quick reply! The book I am editing is on https://github.com/llrs/thesis. I have also committed the .log file in case it helps. 
The references added with Rstudio citation manager are on 01_introduction.Rmd, right before the 4th level title of "Output results": 

> HUMAnN, LEfSe [@franzosa2018; @truong2015; @segata2011]. 

However in my library on Zotero the @franzosa2008 article's citekey is @franzosaSpecieslevelFunctionalProfiling2018. Other relevant information might be the configuration I have on Zotero>Edit>Preferences>"Better BibTex" for citation key is `[auth:lower][shorttitle3_3][year]`. I think it is the default but might have changed, because Rstudio seems to assume `[auth:lower][year]` but should use whatever there is in use imho.

I'll try to create a more minimal reprex in some hours (~12h). Not sure if there is any workaround, might also explore it.

**Comment by jjallaire** [comment]
You might need to explicitly configure RStudio to use Better Bibtex for CItekeys:

![](https://rstudio.github.io/visual-markdown-editing/images/visual-editing-options-citations.png)

Does that make a difference?

**Comment by llrs** [comment]
Oh, I've missed (I might have configured it in one computer but not on the current one) and this might make the issue void. When I select the option  "Use Better BibTeX for citation keys..." the existing citations do not update, not sure it was intended. Testing it now
Then my only concern is that when adding a new citation the document view moves to the top. for context and moving

**Comment by llrs** [comment]
The problem was that configuration that I didn't set up correctly on Rstudio (perhaps another configuration that can go for project as it will be stored in the repository as well as global?).

**Comment by jjallaire** [comment]
@llrs We will work on making Better Bibtex a project-level option. 

We haven't been able to reproduce the document view moving to the top. Do you have a document where this happens every time that you can share with us?

**Comment by llrs** [comment]
It happens to me on the same repo I posted above llrs/thesis. On that repo, what I need to do is go to a document on visual edition and then Ctrl+Shift+P search for citation and then the view is moved. When I directly use Ctrl+shift+F8 it doesn't move the view. I can't reproduce in any other file or project. Sorry for all the nagging, I'll close the issue

**Comment by jjallaire** [comment]
Thanks, will investigate!

**Comment by jjallaire** [comment]
Was able to repro when using `Ctrl+Shift+P`. Fix for that is here: https://github.com/rstudio/rstudio/commit/2f7fbf2606bfb79880de22860597ba8c06252bbf (will be in tomorrow's daily build)

**Comment by llrs** [comment]
Great! Many thanks! Not sure if it is worth to open a new issue but I expected to be able to add several citations at once with `Shift/Ctrl+mouse click` as in selecting multiple files. Anyway this is a great addition!

**Comment by jjallaire** [comment]
You can add multiple citations at once using the "+" sign at the right of the entries. Is that what you are looking for?

**Comment by dragonstyle** [comment]
> Great! Many thanks! Not sure if it is worth to open a new issue but I expected to be able to add several citations at once with `Shift/Ctrl+mouse click` as in selecting multiple files. Anyway this is a great addition!

FYI shift+click will be supported in an upcoming update. Thanks for the great suggestion.
