### ISSUE TITLE
QT Update build on Windows is opening the IDE in a completely blank state, or crashing on 1st launch.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#8106]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.5002
    OS Version      : Windows 10 x64
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Install the QT update branch build of RStudio 1.4 (Pro or Open Source).
2. Launch RStudio.

### Describe the problem in detail
The IDE is opening in a completely blank state (see screenshot below). The top-bar menu is displayed but does not function. This behavior remains consistent after closing/re-opening the IDE, holding Ctrl during launch (I tried this and switched to Software Rendering, got the same behavior), and restarting the PC.

![Screenshot 2020-10-16 150652](https://user-images.githubusercontent.com/62304541/96311645-8f320900-0fcf-11eb-8f76-e14222a19a3e.png)

### Describe the behavior you expected
The IDE opens successfully.

### Notes

- I've tried the QT builds on 2 different machines (desktop and laptop) and gotten different behavior on each. On the desktop, 1st launch of the build crashed. Subsequent launches seem stable. On the laptop (which is the more 'pristine' of the 2 rigs), I get the behavior described in this issue report. Additional data-points may be useful to help ascertain which of these 2 behaviors is more consistent/common. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
After getting reports that this is NOT occurring for other folks (thanks for the assist @ronblum), I tried something else:

Launch the IDE while holding Ctrl, switch rendering engine from Software to Desktop OpenGL. And the IDE launched and opened successfully.

If I then switch back to Software rendering, I again get the blank IDE issue described in the issue report.

**Comment by kevinushey** [comment]
That's pretty concerning -- many users run with software rendering forced (or we force it ourselves in some cases!) to work around various bugs that occur in the gargantuan matrix of (video card x display driver version) combinations.

**Comment by gtritchie** [comment]
I'm encountering variations of this; on my laptop with an external monitor I can launch with default settings; but when I use the built-in display I'm getting a solid black screen (where QtWebEngine lives) then the app terminates.

**Comment by CassioAlan** [comment]
When I start RStudio without an external monitor on my laptop, it works fine.
With the external monitor I need to run RStudio with software rendering engine, otherwise it opens in a blank state with " (Not responding)" on title.

![image](https://user-images.githubusercontent.com/2096641/96519356-35397980-1243-11eb-8b08-b20ec8ce54eb.png)

**Comment by kevinushey** [comment]
For me, all 4 permutations of (Software vs. Desktop) x (Builtin display vs. external monitor) work without issue.

**Comment by gtritchie** [comment]
We've decided against updating Qt on Windows for the 1.4 release. Closing this.

**Comment by R-Hannibal** [comment]
Adding the verified label.

We will not be updating Qt on any distro for the 1.4 release.
