### ISSUE TITLE
Auth-none=1 is broken when www-root-path is used

### ISSUE THREAD

**Issue by nadenf** [rstudio/rstudio#8119]
### System details

    RStudio Edition: Server
    RStudio Version: 1.4.954
    OS Version: OSX 10.15.3
    R Version: 3.5.1

### Steps to reproduce the problem
Using the following two config parameters with USER=rstudio:
```
auth-none=1
www-root-path=/test
```
### Describe the problem in detail

When you don't have www-root-path set everything works fine. But when it is enabled any URL you enter will redirect to:

```
/test/auth-sign-in?appUri=%2F 
```

### Describe the behavior you expected

It should go straight into the main UI and not redirect to the login screen.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ricardofandrade** [comment]
@ronblum Were you behind a proxy with the additional path `/test`?
Otherwise, it's not expected to work at all.

That's because `www-root-path` will make all cookies have the path configured.
So, unless you're behind a proxy with the same path, the cookies simply doesn't exist for the browser, breaking authentication.

**Comment by FernandezMathieu** [comment]
Facing the same issue.

```
RStudio Edition: Server  
RStudio Version: 1.4.954  
OS Version: RHEL7  
R Version: 3.6.1 (installed with conda r-base)
```

We are trying to launch Rsession in a Jupyterlab environnement. We use [rsession-proxy ](https://github.com/jupyterhub/jupyter-rsession-proxy/tree/v1.2.0) to do that.

The library execute the command `/usr/lib/rstudio-server/bin/rsession --standalone=1 --program-mode=server --log-stderr=1 --session-timeout-minutes=0 --user-identity=jovyan --www-port=1523` but when we are trying to see the result on browser, Rstudio is stuck on `/rstudio/auth-sign-in?appUri=%2F` url.

**Comment by nadenf** [comment]
> @ronblum Were you behind a proxy with the additional path `/test`?
> Otherwise, it's not expected to work at all.

I wasn't aware cookies were involved when auth-none=1. Let me investigate.

**Comment by nadenf** [comment]
Apologies for this. Can confirm it works with an actual proxy in front. Closing.
