### ISSUE TITLE
Large files sizes when saving JS graphs as PNGs

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#8121]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.904
    OS Version      : 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem

Run 

```
plotly::ggplotly(
  ggplot2::ggplot()
)
```
Then export the resulting file as a png. The file size is particularly large >> 2MB. If I use ragg, it's better, but still >>1MB.

Running a simple optimiser on the image brings it down to 24kb

### Describe the problem in detail

I realise this might not be a bug, but it doesn't seem like a feature request.

### Describe the behavior you expected

 * Smaller file size, and/or
 * a warning on a large file and/or
 * a box to set optimisation

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@csgillespie Thank you for raising this! Using the download file option 
![image](https://user-images.githubusercontent.com/31009952/96630384-ef33f280-12e2-11eb-8867-07560f2f8a78.png)

within the Viewer pane results in a significantly smaller file, so it's worth understanding if this is something that could be changed or managed by RStudio, or if this is as expected. We'll review this as we continue developing RStudio.
