### ISSUE TITLE
warning re: partial matching of YAML header fields

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8123]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

Create a new R Markdown document, with the contents:

`````
---
runtime_oops: hello
---

Hello, world!
`````

Then, save the document somewhere (any name / place is fine).

### Describe the problem in detail

Partial match warnings are emitted to the console after save:

<img width="405" alt="Screen Shot 2020-10-20 at 10 51 55 AM" src="https://user-images.githubusercontent.com/1976582/96624893-46759b00-12c2-11eb-97f3-09d28cf63cd4.png">

### Describe the behavior you expected

No warnings.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Verified in 1.4.978
