### ISSUE TITLE
Source tabs cannot be dragged / rearranged

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8126]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.2

### Steps to reproduce the problem

Using a Qt 5.15.1 build of RStudio, open a new source document, then click on the tab to try and drag it to a new position.

### Describe the problem in detail

Dragging doesn't occur.

### Describe the behavior you expected

Dragging should occur.

### Notes

Based on some initial investigation, looks like the problem is that we listen for a dragenter event here, but that never gets fired (but dragstart does):

https://github.com/rstudio/rstudio/blob/e527463081fc095bbe69d43ae2949ff03f44e9a5/src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java#L424

https://github.com/rstudio/rstudio/blob/e527463081fc095bbe69d43ae2949ff03f44e9a5/src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java#L134
---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Weirdly, I'm no longer able to reproduce this on local builds.

**Comment by gtritchie** [comment]
I also cannot repro on current 5.15.1-based Mac build 1.4.999 (c3bd072b, 2020-10-23)

**Comment by kevinushey** [comment]
Closing as no longer reproducible.

**Comment by gtritchie** [comment]
Resolving as out-of-scope now that we're not upgrading to 5.15 for RStudio 1.4.
