### ISSUE TITLE
Add color for Python function

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#8128]
It will be better if python function can be displayed as different color to easier recognize.
I hope this feature will be come soon.

Thank you

**Comment by ronblum** [comment]
@ntluong95 Thank you for the suggestion! Do you mean that when `Tools -> Global Options -> R Markdown -> Enable chunk background highlight` is checked, the background for chunks is currently gray, and you'd like the color for Python to be different? I suppose the feature request could be expanded to controlling the background color for different types of code chunks—R, Python, bash, etc. We'll review this request as we continue our ongoing development of RStudio.

**Comment by ntluong95** [comment]
Thank you robblum, that is a great suggestion. However, I meant the python keywords should be highlighted.
