### ISSUE TITLE
Separator lines are missing from the IDE Toolbar's New File menu on MacOS 11 Big Sur

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8130]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042, 1.3.1093, and  1.4.94
    OS Version      : MacOS 11 Big Sur beta 10
    R Version       : 4.0.3

### Steps to reproduce the problem

On MacOS 11 Big Sur beta 10: in IDE Toolbar, click on the "New File" icon, the furthest to the left: 
![image](https://user-images.githubusercontent.com/31009952/96639643-00373080-12f0-11eb-9789-f0333061e46d.png)

### Describe the problem in detail

On Big Sur, the separator lines are missing from the IDE Toolbar's "New File" menu. 

![image](https://user-images.githubusercontent.com/31009952/96639677-088f6b80-12f0-11eb-826f-8435f121ea23.png)

Note that 
1) there's a bit of extra space between some items, as expected. Only the lines are missing.
2) this is a Big Sur problem: the problem occurs in 1.2.5042 and 1.3.1093, not just 1.4.940. Everything's fine on Catalina.

### Describe the behavior you expected

Include the separator lines in the menu.

![image](https://user-images.githubusercontent.com/31009952/96639706-104f1000-12f0-11eb-803e-61349fa2f011.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Can you give the Qt 5.15.1 preview a try to see if that makes any difference? Be a good data point.

**Comment by ronblum** [comment]
No change, alas.

**Comment by jmcphers** [comment]
@ronblum Can you still reproduce this? I can't, on either my local dev build or RStudio 1.4.959. 

I'm on macOS Big Sur 11.0 Beta (20A5395g). Is it possible Apple fixed the underlying issue?

**Comment by ronblum** [comment]
The issue turns out to be with zooming: when zoomed out to 50% or 90%, the separators disappear. They're present at all other values.

See also #8086  for disappearing lines.

**Comment by jmcphers** [comment]
This doesn't reproduce in RStudio Server on Big Sur, so is a qtwebengine issue (or at least a qtwebengine + big sur issue). It is minor, doesn't affect functionality, and doesn't affect the typical use case (100% zoom), so moving to our ever-growing "Fixed By Electron" pile.

**Comment by gtritchie** [comment]
Confirmed this still repros with the most current daily (Qt-based) build on macOS 12.3, at certain zoom levels.

It does not repro with the Electron build (2022.06.0-daily+248), so appears the updated Chromium did the trick.
