### ISSUE TITLE
Additional Redacting Terms for Diagnostic Report

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#8134]
The TRAVIS API tokens are added as either `R_TRAVIS_COM` or `R_TRAVIS_ORG` - see output below.

This sort of token isn't stripped from the [diagnostic report](https://github.com/rstudio/rstudio/blob/47f9907ec50dcd54f24fa59f907cfdcaadadc61a/src/cpp/r/R/Diagnostics.R#L28) 

Happy to make a tiny PR

```
✓ [master]> travis::browse_travis_token()
travis: Env var `R_TRAVIS` not set by user. Defaulting to '.com' endpoint. If
supplied, the `endpoint` argument in any `travis_*()` function will take
precedence. (This message is displayed once per session.)

ℹ Querying API token...
→ Opening URL <https://travis-ci.com/account/preferences>.
ℹ Call `usethis::edit_r_environ()` to open '~/.Renviron' and store the
  API key as env var `R_TRAVIS_COM` (or `R_TRAVIS_ORG` if you are using
  the '.org' endpoint). Example: `R_TRAVIS_COM = <key>`

The API key can alternatively be stored in '~/.travis/config.yml'. This
  is only suggested if you previously used the Travis CI CLI tool.
```

**Comment by kevinushey** [comment]
This is where our redact list lives:

https://github.com/rstudio/rstudio/blob/291c992854e1c8372dfde650e2813aea5cd17699/src/cpp/r/R/Diagnostics.R#L25-L35

You could add `R_TRAVIS` to that list, I think?
