### ISSUE TITLE
"Run selected line(s)" not working correctly with multi line example in roxygen

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#8135]
# System details

    RStudio Edition :  Desktop or Server
    RStudio Version :  1.4.933
    OS Version      : Windows 10 
    R Version       : 4.0.3

### Steps to reproduce the problem
- Create a function with the following roxygen documentation:
```r
#' @examples 
#' x <- 1 +
#' 1
```
- Put the cursor at the end of the first line of the example, the line starting with x. 
- Run "Run selected line(s)"

### Describe the problem in detail

When running the steps described only the first line in the example is executed in the console, unlike when the same is done from within an R script.

### Describe the behavior you expected

The full example being executed in the console.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This sounds like a feature request -- that is, to have RStudio's "multi-line expression" execution logic work in roxygen example comment blocks as well. Is that correct?

**Comment by BartJanvanRossum** [comment]
Yes, that is correct
