### ISSUE TITLE
Middle click event ignored on file editor tab strip

### ISSUE THREAD

**Issue by nfultz** [rstudio/rstudio#8140]
### System details

    RStudio Edition : Server [Open Source]
    RStudio Version : 1.2.1335
    OS Version      : Ubuntu 20.04.1 LTS
    R Version       : R version 4.0.2 (2020-06-22)

### Steps to reproduce the problem

Open two or more files in the text editor.

### Describe the problem in detail

When I middle click on a tab in the file editor tab strip, nothing happens.

### Describe the behavior you expected

Middle clicking on the tab should close the tab. If the clicked buffer is unsaved, maybe the confirmation dialog should pop up first.

**Comment by kevinushey** [comment]
Do you also see this in the latest RStudio release (1.3.1093)? Or in the latest [preview](https://rstudio.com/products/rstudio/download/preview/) (1.4.933+)?

**Comment by nfultz** [comment]
Seems like it is fixed after updating to 1.4.933. Thanks!
