### ISSUE TITLE
"Create project as subdirectory of" field blank on state reset; prevents creation of project

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8145]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

Reset RStudio's state, using `scripts/clean-rstudio`. Then, launch a new copy of RStudio and try to create a new package project.

### Describe the problem in detail

The "Create project as subdirectory of" box is blank, and attempts to create a package silently fail.

<img width="550" alt="Screen Shot 2020-10-21 at 2 05 19 PM" src="https://user-images.githubusercontent.com/1976582/96787460-a47bae80-13a6-11eb-8740-50dd577fe37b.png">

### Describe the behavior you expected

We should provide a default project location (home directory?), rather than leaving that entry blank.

Note that while the resolution here is simple (ensure a proper sub-directory is selected) the fact that there is no UI response when the attempt to create a project fails makes me think this is worth fixing in 1.4.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Also true for the Global Options dialog:

<img width="603" alt="Screen Shot 2020-10-21 at 2 08 35 PM" src="https://user-images.githubusercontent.com/1976582/96787651-f7556600-13a6-11eb-87a1-8f95a4b5b5c3.png">

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990
