### ISSUE TITLE
some Hunspell dictionaries are mis-encoded

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8147]
RStudio retrieves "extra" dictionaries from AWS here:

https://rstudio-dictionaries.s3.amazonaws.com/all-dictionaries.zip

via:

https://github.com/rstudio/rstudio/blob/6da40861669dafb40c6c019bbafe4446dcb254dd/src/cpp/session/modules/SessionSpelling.R#L16-L51

However, some of the dictionaries appear to be mis-encoded:

- `cs_CZ.aff` declares its encoding as `SET ISO-8859-2` but is actually `UTF-8`;
- `de_DE_neu.aff` declares its encoding as `SET ISO8859-1` but is actually `UTF-8`;
- `pt_br.aff` declares its encoding as `SET ISO8859-1`, but is actually `UTF-8`.

Using these dictionaries will lead to mis-encoded spelling suggestions. For example, with Portuguese (Brazil);

<img width="427" alt="Screen Shot 2020-10-21 at 4 46 33 PM" src="https://user-images.githubusercontent.com/1976582/96801660-fb8c7e00-13bc-11eb-8d1a-deb2c1691939.png">

as RStudio tries to convert from the dictionary-declared encoding to UTF-8, which errs here since the dictionaries already are UTF-8.

**Comment by dpprdan** [comment]
Isn't this just a matter of changing `SET ISO8859-1` to `SET UTF-8` in the three files mentioned and uploading the zip file to S3?
Or am I missing something?

**Comment by kevinushey** [comment]
You are correct, that should suffice for fixing the issue.

**Comment by dpprdan** [comment]
FWIW, this is the zip file with the updated files. Only the files you mentioned initially need changing.
https://1drv.ms/u/s!AnawHDtdOl-4hd90TUspwl5lNVK-PQ?e=1czJLu

**Comment by pmagdon** [comment]
Just updated the R-Studio, but the Problem still exits. Since the bug was identified and solution is clear should be easy to fix this or?

**Comment by gtritchie** [comment]
I did the following:

- downloaded and extracted the existing `all-dictionaries.zip` from S3
- changed encoding in the three files (cs_CZ.aff, de_DE_neu.aff, pt_br.aff) to `SET UTF-8`
- created new zip and uploaded to S3, replacing the old one

Then re-downloaded via RStudio's "Update dictionaries..." at bottom of language choices in Global Options / Spelling / Main dictionary language, and confirmed the downloaded dictionaries (on Mac/Linux this is under `~/.config/rstudio/dictionaries/languages-system`) have the new encoding.

Also tried the case given earlier with Brazillian Portuguese ("nao") and confirmed it now displayed correctly.

I don't have test cases for the other two languages.

**Comment by ronblum** [comment]
@pmagdon @dernst @dpprdan would any of you be willing to try this out, following @gtritchie's comment above?

**Comment by gtritchie** [comment]
Added fix to NEWS: https://github.com/rstudio/rstudio/commit/c870264b3aaa9fe055e198f5ada0f9081ce965b8

**Comment by dpprdan** [comment]
> @dpprdan would any of you be willing to try this out

@ronblum works on my machine (apparently).
