### ISSUE TITLE
pandoc-citeproc issue on RStudio preview

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#8151]
Great to see the migration to Pandoc 2.11.

This is just a pre-emptive heads-up: when I installed the latest preview version of 1.4 and tried to knit an Rmd file I got this error:

```
Could not find executable pandoc-citeproc
Error: pandoc document conversion failed with error 83
In addition: There were 17 warnings (use warnings() to see them)
```

I guess that is because of this, which is a good thing I think: https://github.com/rstudio/rstudio/pull/8042

I'm going to update Pandoc version, will let you know of any further issues. Opening this as a heads-up that it may be an issue on the next release. I'm on Ubuntu 18.04 running 

```
pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/robin/.pandoc

rstudio --version                          
1.4.953
```

**Comment by Robinlovelace** [comment]
Another link, is this linked to the deprecation of `pandoc-citeproc`? https://github.com/jgm/citeproc/issues/9

**Comment by Robinlovelace** [comment]
Update: Updating pandoc version didn't resolve the issue for me. I was on 

```
pandoc --version
pandoc 2.11.0.2
```

**Comment by ronblum** [comment]
@Robinlovelace Thank you for raising the issue! Can you provide the system environment so that we can try to reproduce? Spec. RStudio version, operating system, and version of R.

**Comment by Robinlovelace** [comment]
Here's some info, let me know if you'd like more:

```
R --version
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.


➜ lsb_release -a                      
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

➜ rstudio --version
1.3.1093
```

**Comment by Robinlovelace** [comment]
I've switched back to the current release and, with the latest version of pandoc there is still an issue...

**Comment by cderv** [comment]
@Robinlovelace did you had the last version of rmarkdown when you tried ?
 
You need version 2.5 that has been released on CRAN this week and that contains support for Pandoc 2.11. With previous version of rmarkdown, Pandoc 2.11 won't work. 

I believe RStudio IDE 1.4 is requiring CRAN rmarkdown 2.5 now (https://github.com/rstudio/rstudio/issues/8046) but you need one of the lastest dailies (yesterday or today)

**Comment by Robinlovelace** [comment]
Hi @cderv I think that's it, I thought I updated all my packages but after checking I see I'm on 2.4:

```
Rscript -e 'packageVersion("rmarkdown")'
[1] ‘2.4’
```

**Comment by Robinlovelace** [comment]
Yes, updating to the latest version of RMarkdown, apparently released yesterday, works :tada: Many thanks @cderv and @ronblum for quick responses on this, hope me raising this will be of use to others.
