### ISSUE TITLE
Run selected line(s) bug in 1.4.953

### ISSUE THREAD

**Issue by mike-lawrence** [rstudio/rstudio#8156]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.953
    OS Version      :  Ubuntu 20.04
    R Version       : 4.0.3

### Steps to reproduce the problem
Enter the following in a text editor:
```r
library(tidyverse)
# a = 
	(
		tibble(v1=1)
	)
```
Then place the cursor anywhere after or below the hash, hit ctrl-enter, and the `library(tidyverse)` part is run, never the rest of the code.

### Describe the problem in detail
I have an admittedly idiosyncratic style whereby I prototype processing chains enclosed in parens with an assignment at the beginning that is commented-out at first. On Rstudio 1.3.1093 and earlier, the IDE had no problems with this and I could hit ctrl-enter on any line inside the parens to run the whole chunk (it also worked if I placed the cursor on the commented-out assignment line, on the opening paren line, and on the close paren line). I just downloaded 1.4.953 and observe that even when the cursor is inside the parens, the code inside the parens is not run by ctrl-enter, instead the line immediately preceding the commented-out assignment line is run. 

### Describe the behavior you expected
If the cursor is placed anywhere on or after the commented-out assignment line, I expected ctrl-enter to run the contents of the parens-encapsulated chunk. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mike-lawrence Thank you for raising this issue!

1) I can reproduce the above in RStudio Desktop 1.4.953 on Ubuntu 20.
2) Things work fine in RStudio Desktop 1.4.953 on MacOS 11 beta 10 and RStudio Server 1.4.953 on Red Hat 8.2.

**Comment by mikebessuille** [comment]
This sounds related to another bug Kevin was recently looking at...?

**Comment by melissa-barca** [comment]
@kevinushey This appears to be broken for example 13 in the daily build (1.4.978 Desktop).  `Ctrl+Enter` move from line 89 to 91 to 92 and then to 94. https://github.com/rstudio/rstudio/blob/master/src/gwt/test/test-multiline-expr.R#L89-L92

**Comment by kevinushey** [comment]
Note: reproduces only when rainbow parentheses are enabled.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990
