### ISSUE TITLE
Fonts are wrong in macOS build with Qt 5.15.1

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8157]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.999, Qt 5.15.1 branch

### Steps to reproduce the problem

Start RStudio; examine the fonts closely.

### Describe the problem in detail

The font used for much of the user interface is the default sans-serif font.

![image](https://user-images.githubusercontent.com/470418/96914758-44464480-145a-11eb-8fb4-146002d2dbd3.png)

This font has slightly different metrics than our usual font, so it looks misaligned. It's the default sans-serif font, but it should be _Lucida Grande_.

### Describe the behavior you expected

Here's what it should look like; this is 1.4.959, Qt 5.12, Lucida Grande.

![image](https://user-images.githubusercontent.com/470418/96914909-722b8900-145a-11eb-8fa4-f8f9b9addb39.png)

**Comment by jmcphers** [comment]
This is now resolved on the Qt development branch.

**Comment by gtritchie** [comment]
Resolving as out-of-scope now that we're not upgrading to 5.15 for RStudio 1.4.
