### ISSUE TITLE
Visual Markdown Editor: Interactive table column width breaks GitHub README

### ISSUE THREAD

**Issue by ARMurray** [rstudio/rstudio#8159]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      :  Windows 10.0.18363
    R Version       :  4.0.2

### Steps to reproduce the problem

Create a README.md file for use with GitHub page. 
Add a table either with straight markdown or using the add table tool in the visual markdown editor.
Add content to table
Change the column widths of the table
Switch out of visual markdown editor to confirm format change
Push to GitHub
Observe table appears corrupted in GitHub

### Describe the problem in detail

When using the visual markdown editor to interactively change column widths, the formatting changes and makes it so GitHub cannot parse it to show as a table. The image below shows before and after using the interactive column slider.

![image](https://user-images.githubusercontent.com/36209610/96926670-db73c200-1483-11eb-8d06-9aaccffa6b09.png)

### Describe the behavior you expected

The interactive slider should play nice with markdown and I'm not sure why GitHub cannot parse it.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Marking as 1.4 just so we take a look.

**Comment by ronblum** [comment]
Adjusting the width turns the table into a grid table, and from what I can tell, GitHub doesn't support grid tables. So @kevinushey I don't think there's anything we can do about it?

To reproduce, insert the following in README.md and check it in:

```
Regular Table

| Col1 | Col2 |
|------|------|
| R1C1 | R1C2 |
| R2C1 | R2C2 |


Grid Table

+-------+------+
| Col1  | Col2 |
+=======+======+
| R1C1  | R1C2 |
+-------+------+
| R2C1  | R2C2 |
+-------+------+
```

The result is at GitHub is:

<img width="957" alt="readme" src="https://user-images.githubusercontent.com/31009952/97042010-6dd89c00-153e-11eb-9c98-f2af7ea46492.png">

**Comment by kevinushey** [comment]
Perhaps we could control whether RStudio uses grid tables or not when generating the source Markdown? It'd be useful to say for documents destined for GitHub that tables should always be rendered as regular tables.

**Comment by ARMurray** [comment]
> Perhaps we could control whether RStudio uses grid tables or not when generating the source Markdown? It'd be useful to say for documents destined for GitHub that tables should always be rendered as regular tables.

Seems like it could at least be noted that it is incompatible with GitHub, although it seems like GitHub should be able to support grid tables (hopefully in the future?).

**Comment by jjallaire** [comment]
If you put the document in `gfm` mode then it will not generate grid tables: https://rstudio.github.io/visual-markdown-editing/#/markdown?id=github-markdown

If you use the `github_document` output format in your Rmd we will also default to `gfm` mode (and not write the grid tables).

All of that said, we might also want to default to `gfm` mode automatically whenever we are editing a README file within a Git  repo.

**Comment by jjallaire** [comment]
With this change we automatically use `gfm` mode for README files in git repos: https://github.com/rstudio/rstudio/commit/726aa19140add320629621f5f5ecf092a90446e8 (which will in turn prevent writing of grid tables)

**Comment by kfeinauer** [comment]
Verified that table type is not rewritten for `README` files within a Git repo on 1.4.1032 - changes to the column widths in Visual Mode are not persisted in regular source mode.
