### ISSUE TITLE
insertion of colon doesn't outdent in C++ files

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8165]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a C++ file,
2. Enable rainbow parentheses,
3. Try typing:

```
class test {
    public:
}
```

When `:` is inserted after `public`, you should see the line "outdented", with `public` pushed to the left.

### Describe the problem in detail

![outdent-bad](https://user-images.githubusercontent.com/1976582/96930987-731be500-1471-11eb-9217-d4c2396afaf2.gif)

### Describe the behavior you expected

![outdent-good](https://user-images.githubusercontent.com/1976582/96930997-77480280-1471-11eb-9f1f-eff61db6f4d7.gif)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990
