### ISSUE TITLE
Chunk background color misaligned

### ISSUE THREAD

**Issue by mbojan** [rstudio/rstudio#8171]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.959
    OS Version      : Windows 10
    R Version       :  R 4.0.3

### Steps to reproduce the problem

Edit RMarkdown document

### Describe the problem in detail

The background color of R chunks are misaligned with the chunks. See screenshot below. Re-opening the file makes the chunk colors correct.

![obraz](https://user-images.githubusercontent.com/636574/97003157-50ee9980-153b-11eb-9b20-7e3a77ab32b9.png)

### Describe the behavior you expected

Proper coloring of chunks

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Hi @mbojan thank you for reporting this. I'm closing this issue as it's currently being tracked here: https://github.com/rstudio/rstudio/issues/8088

Could you confirm that you are using an additional source column when this misalignment occurs?

**Comment by mbojan** [comment]
Thanks @melissa-barca . What do you mean by "additional source column"?

**Comment by melissa-barca** [comment]
In 1.4 we added the ability to have two source editors open at a time (https://blog.rstudio.com/2020/10/21/rstudio-1-4-preview-multiple-source-columns/), currently we think this may be related to the chunk highlighting issue.

**Comment by mbojan** [comment]
I replied in #8088.
