### ISSUE TITLE
Calling `rs_runScriptJob` fails if path contains special characters

### ISSUE THREAD

**Issue by netique** [rstudio/rstudio#8172]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.953
    OS Version      : Windows 10 Home (2004, build 19041.572)
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem

Make a file (R script preferably) in a fashion that its path contains special characters, e.g. "á" ("\u00e1" in Unicode escape).

```
C:/ááá/script.R
```
The content doesn't really matter, paste, say, the obligatory:

```
print("Hello world!")
```

Now use `rstudioapi::jobRunScript`, or directly acces the compiled C++ function `rs_runScriptJob` using the aforementioned path.

This fails issuing the error:

```
Error: The script file 'C:/ááá/script.R' does not exist.
```

### Describe the problem in detail

The problematic call in better detail, derived from tracing `rstudioapi::jobRunScript`:

```
.Call("rs_runScriptJob", path = "C:/ááá/script.R", name = NULL, encoding = "unknown", workingDir = NULL, 
          importEnv = FALSE, exportEnv = "", PACKAGE = "(embedding)")
```

Note that `file.exist()` returns `TRUE` and the path is also printed correctly in the error message. Escaping the special characters like `C:/\u00e1\u00e1\u00e1/script.R` prints the same correct path, but fails too.

### Describe the behavior you expected

The call should result in a Job that prints "Hello world!". Or, at least, reach the file and try to run it.

The solution probably requires editing https://github.com/rstudio/rstudio/blob/3fdda38e9a78a984a25c44e1672cf0869fad19cd/src/cpp/session/modules/jobs/SessionJobs.cpp#L205

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Thanks for reporting! This is currently tracked in https://github.com/rstudio/rstudio/issues/6701.
