### ISSUE TITLE
No more preview in Rmarkdown document anymore

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#8173]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.966
    OS Version      :  Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

* Create a new Rmd doc and Sabe
* Try to execute a chunk using the green arrow
* Nothing show ! 

### Describe the problem in detail

Nothing is seen inline. A `>` is sent to console. 

![preview-1 4](https://user-images.githubusercontent.com/6791940/97015424-dc702680-154b-11eb-987d-d5ca655be41f.gif)

### Describe the behavior you expected

To have a preview of the result inline.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
I'm also seeing this. Tested back on the dailies and `1.4.963` is the last clean Daily where this issue does NOT occur.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.967, R Version - 4.0.3, MacOS 11 beta (Big Sur) - Desktop 

Verified that code chunks can now be run successfully within a Markdown file.
