### ISSUE TITLE
Cursor position not updated in visual mode

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8174]
### System details

    RStudio Edition : Both 
    RStudio Version : 1.4.963

### Steps to reproduce the problem

1. Open an R Markdown document in source mode.
2. Move the cursor inside the document; note that the cursor position (the `row:column` indicator in the bottom left corner of the editor) updates.
3. Switch to visual mode.
4. Move the cursor again.

### Describe the problem in detail

The cursor position does not update in visual mode.

![image](https://user-images.githubusercontent.com/470418/97039730-b9c91800-1521-11eb-8285-c6bd20233e91.png)

### Describe the behavior you expected

It'd be nice if there were some notion of a cursor position in visual mode, but as there isn't, we should probably just hide the indicator.

**Comment by kfeinauer** [comment]
Verified cursor position hidden in Visual Mode 1.4.1027
