### ISSUE TITLE
Impossible to deactivate implicit header references or backlash brackets delimiters

### ISSUE THREAD

**Issue by jdutant** [rstudio/rstudio#8181]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.952
    OS Version      : MacOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

Create a new markdown document and paste this:

```markdown
As we'll recount in the [next section](#models), Wiseman famously claimed that:

> Not all [models] are [simple].

And also that: 

>  Not all [simples] are \[models\].

# Models
```
Switch to the Visual Markdown Editor and back. In the first quotation "models" has been turned into an explicit header reference: `[models](#models)`. In the second quotation the escaped brackets are rendered as display equations in Visual Mode and turned into `$$` equation delimiters when returning to the source. Neither was intended.

Moreover, if the RMarkdown > Visual option "Write canonical markdown in source mode" is enabled, these replacements are applied to the source upon saving. 

### Describe the problem in detail

This is a niche bug, but it'll happen a few times. Square brackets are used in academic writing to indicate parts edited parts of a quotation. If the inserted text happens to match an automatically generated identifier of a header, the visual editor interprets them as an implicit header references. Moreover, the Visual Editor markdown assumes that the `tex_math_single_backslash` extension in `pandoc` is activated and interprets escaped square brackets as equation delimiters.

In `pandoc` we can avoid the problem in two ways: escape the square brackets (and leave `tex_math_single_backslash` disabled, as it is by default) or disable the  `implicit_header_references` extension. 

### Describe the behavior you expected

A feature that would solve that and potentially other issues: **be able to configure which pandoc extensions of markdown are applied by the Visual Editor** (at least for some of them).

For this particular bug, one of these:

1. Have (document- or project-level) Visual R Markdown settings to disable implicit header references and/or single backslash equation delimiters.
2. Implicit header reference are left as is. We can then avoid the problem by running `pandoc` with `implicit_header_references` disabled.
2. Escaped square brackets are left as is. The document would look wrong in visual mode, but we could run `pandoc` without `tex_math_single_backslash` extension.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Interestingly, pandoc is making both of these transformations so when the visual editor gets the AST it looks like this:

```json
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": [
    {
      "t": "Para",
      "c": [
        {
          "t": "Str",
          "c": "As"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "we’ll"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "recount"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "in"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "the"
        },
        {
          "t": "Space"
        },
        {
          "t": "Link",
          "c": [
            [
              "",
              [],
              []
            ],
            [
              {
                "t": "Str",
                "c": "next"
              },
              {
                "t": "Space"
              },
              {
                "t": "Str",
                "c": "section"
              }
            ],
            [
              "#models",
              ""
            ]
          ]
        },
        {
          "t": "Str",
          "c": ","
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "Wiseman"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "famously"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "claimed"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "that:"
        }
      ]
    },
    {
      "t": "BlockQuote",
      "c": [
        {
          "t": "Para",
          "c": [
            {
              "t": "Str",
              "c": "Not"
            },
            {
              "t": "Space"
            },
            {
              "t": "Str",
              "c": "all"
            },
            {
              "t": "Space"
            },
            {
              "t": "Link",
              "c": [
                [
                  "",
                  [],
                  []
                ],
                [
                  {
                    "t": "Str",
                    "c": "models"
                  }
                ],
                [
                  "#models",
                  ""
                ]
              ]
            },
            {
              "t": "Space"
            },
            {
              "t": "Str",
              "c": "are"
            },
            {
              "t": "Space"
            },
            {
              "t": "Str",
              "c": "[simple]."
            }
          ]
        }
      ]
    },
    {
      "t": "Para",
      "c": [
        {
          "t": "Str",
          "c": "And"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "also"
        },
        {
          "t": "Space"
        },
        {
          "t": "Str",
          "c": "that:"
        }
      ]
    },
    {
      "t": "BlockQuote",
      "c": [
        {
          "t": "Para",
          "c": [
            {
              "t": "Str",
              "c": "Not"
            },
            {
              "t": "Space"
            },
            {
              "t": "Str",
              "c": "all"
            },
            {
              "t": "Space"
            },
            {
              "t": "Str",
              "c": "[simples]"
            },
            {
              "t": "Space"
            },
            {
              "t": "Str",
              "c": "are"
            },
            {
              "t": "Space"
            },
            {
              "t": "Math",
              "c": [
                {
                  "t": "DisplayMath"
                },
                "models"
              ]
            },
            {
              "t": "Str",
              "c": "."
            }
          ]
        }
      ]
    },
    {
      "t": "Header",
      "c": [
        1,
        [
          "models",
          [],
          []
        ],
        [
          {
            "t": "Str",
            "c": "Models"
          }
        ]
      ]
    }
  ]
}
```

The `[models]` being transformed to a "real" link in the AST is something we have to live with unfortunately unless/until pandoc provides more semantics in the AST.

For the display equation transform, believe it or not `tex_math_single_backslash` is on by default for rmarkdown! (https://github.com/rstudio/rmarkdown/blob/master/R/output_format.R#L360). This was because it was enabled in RMarkdown v1, and we didn't want to break people's documents when migrating. That said, this is really an anomaly that almost no one is even aware of, so disabling that for the visual editor (thus allowing the escapes to work) seems like the right fix here.

**Comment by jjallaire** [comment]
This commit eliminates the math problem: https://github.com/rstudio/rstudio/commit/1d7945355e3fd9293e1cf2d469739e2825e01831

The other conversion of explicit header reference into literal reference we can't avoid given what we are handed by the pandoc AST (hopefully that's the lesser of the two problems in any case).

**Comment by jdutant** [comment]
Great, thanks. So we can just escape the square brackets when the word within brackets happen to be the same as an auto identifier created by Pandoc. That seems like the best solution.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 2021-08.0 Build 310
    OS Version      : mac 11.5.2
    R Version       : 4.1.0

Verified that escaped square brackets are no longer erroneously rendered as an equation when switching into and out of visual edit mode for markdown docs. The conversion of explicit header reference into literal reference still occurs. See above comments for further details.

**Comment by jjallaire** [comment]
Unfortunately we needed to revert this change as it caused a converse problem of every time the user typed square brackets in the visual editor it was turned into a display equation in rmarkdown! This manifested in a couple of pretty serious bugs:

- https://github.com/rstudio/rstudio/issues/10075
- https://github.com/rstudio/rstudio/issues/10131

Note that in the original bug report it was noted that if the visual editor could have its use of pandoc extensions configured that would also provide a solution. This capability does exist (docs: https://rstudio.github.io/visual-markdown-editing/markdown.html#modes-extensions) so hopefully provides enough knobs to work around the problem.
