### ISSUE TITLE
Unable to "Save" new R script if first save is canceled

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#8186]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.972
    OS Version      : macOS Catalina 10.15.7 x86_64-apple-darwin15.6.0 (64-bit)
    R Version       : 3.6.3 or 4.0.2

### Steps to reproduce the problem

- Create new R Script
- Press `Cmd/Ctrl` + `S` to save the R Script, or click Save icon, or File > Save
- Cancel the file location/name dialog
- Repeat action to save the file
- No dialog or file saving occurs

### Describe the problem in detail

Attempting to save a new file for which a previous save process was aborted fails to open the save file dialog. It's possible to get around the error by using "Save As".

### Describe the behavior you expected

I expected that trying to save an untitled file (a previously unsaved file) will always initiate the save file process, regardless of whether or not a save was previously attempted.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note: occurs because `isSaving_` flag doesn't get reset after a cancel.

https://github.com/rstudio/rstudio/blob/4e62ee4be9f5fb7df001890750a339076267a852/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L3740-L3741

**Comment by R-Hannibal** [comment]
I'm also getting this issue on the latest 1.4 daily build (1.4.972).

This is not limited to to R scripts, seems to effect any kind of file. Save button also fails to respond when trying to save an unmodified new file.

This is a regression in functionality from 1.3 to 1.4.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.978, R Version - 4.0.3, Windows 10 x64 - Desktop 

Save button is now functioning as expected, new files can be saved and saves can be cancelled without any negative impact on the user's ability to save the file later.
