### ISSUE TITLE
Wrap open source license text and restrict horizontal scrolling

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8190]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.1093, 1.4.962, and 1.4.999 
    OS Version      : MacOS 10 and 11, and Red Hat 8.2
    R Version       : 3.6.3 and 4.0.3

### Steps to reproduce the problem

1. Help -> About RStudio
2. Click on "Open Source Components"
3. Using the touchpad, scroll down and left to right

### Describe the problem in detail

Most of the text wraps within the width of the window. However, some does not, esp. icomoon and PostgreSQL. As a result, one can scroll from the white screen—in which most of the text appears—to the right and a gray potion of the screen.

![image](https://user-images.githubusercontent.com/31009952/97191564-67843300-177d-11eb-97af-e6ae5700e8e7.png)

### Describe the behavior you expected

The open source licensing text should wrap and be confined to the space visible within the About window. icomooon
and PostgreSQL are the main culprits, but focus-visible, OpenSSH, and RapidJSON, and the URL `  https://github.com/apache/hadoop/tree/master/hadoop-common-project/hadoop-common/src/main/winutils
` near the top might cause problems, as well, though not as egregious.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
@gtritchie Do we care that there are a few asterisks in the gray area requiring scrolling?

![image](https://user-images.githubusercontent.com/5323711/97326359-4f2e1a00-184a-11eb-9cf8-9bbe982e636e.png)

**Comment by gtritchie** [comment]
No don't think we care. It has always had some small amount of horizontal scrolling (and the width varies slightly by platform/font), but this change got rid of some extreme horizontal scrolling that had crept in.

**Comment by melissa-barca** [comment]
Verified in 1.4.978.
