### ISSUE TITLE
rstudio 1.3.1093 crashes on Debian10

### ISSUE THREAD

**Issue by krostifangers** [rstudio/rstudio#8201]
I am on Debian 10 Buster, with R3.6 installed. I downloaded the Debian10 installer for Rstudio 1.3.1093 and installed it using
sudo dpkg -i rstudio-1.3.1093-amd64.deb . However the program crashes after a few seconds.
Can you please help me?
Thank you in advance
Christophe

**Comment by ronblum** [comment]
@krostifangers Thank you for raising this! Does installing with `gdebi` work? This'll hopefully work:
```
sudo apt-get install gdebi-core
sudo gdebi rstudio-1.3.1093-amd64.deb
```

**Comment by ronblum** [comment]
Closed due to inactivity.
