### ISSUE TITLE
jsonlite erroring in RStudio only

### ISSUE THREAD

**Issue by tjtnew** [rstudio/rstudio#8203]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 1.3.1093
    OS Version      :  Fedora 33
    R Version       : 4.0.3

### Steps to reproduce the problem
``` r
con <- pipe("gh api /orgs/r-lib/repos")
raw_dat <- jsonlite::stream_in(con)
#> opening pipe input connection.
#> Error: lexical error: invalid char in json text.
#>                                        [1;38m[[m
#>                      (right here) ------^
#> closing pipe input connection.
```

### Describe the problem in detail
Running the above in RStudio errors as shown.  However, this will run, save a warning, if R is loaded from the command line.  Apologies but this does use the new GitHub gh cli tool (unfortunately I couldn't create a more contained example). 

### Describe the behavior you expected
Running from the command line:

``` r
con <- pipe("gh api /orgs/r-lib/repos")
raw_dat <- jsonlite::stream_in(con)
#> opening pipe input connection.
#> Warning in readLines(con, n = pagesize, encoding = "UTF-8"): incomplete final
#> line found on 'gh api /orgs/r-lib/repos'
#>  Found 1 records... Imported 1 records. Simplifying...
#> closing pipe input connection.
```

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Best guess -- `gh` needs to be configured somehow to avoid producing ANSI-colored output?

**Comment by tjtnew** [comment]
Oh that does makes sense.  Would that only cause an issue when the warning was rendered in the RStudio console?  I tried wrapping the line in `suppressWarnings` to no avail.  I'll dig in to the gh settings and update if resolved.

**Comment by tjtnew** [comment]
So I've tried changing the connection to:
```r
con <- pipe("env NO_COLOR=1 gh api /orgs/r-lib/repos")
```
This seems to remove colour on my command line but I still obtain the same error within RStudio.  Interestingly if I use the command directly in bash within the RStudio terminal then the NO_COLOR environment variable seems to be ignored and I still get coloured output.  I'm afraid I'm not knowledgeable enough to say if this is an issue with the RStudio terminal or with the tool.

Feel free to close the issue if this is something that should be raise on the gh tool repo.

Cheers

**Comment by kevinushey** [comment]
I think ultimately this needs to be raised on their repository -- I think they need to detect whether `gh` is being invoked with a terminal / tty, and then color output depending on whether that is the case.
