### ISSUE TITLE
Removing a connection in the Connections pane removes all connection history

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8204]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.962
    OS Version      : MacOS 11 and Red Hat 8.2
    R Version       : 4.0.3

### Steps to reproduce the problem

In the Connections pane:
1. Click on `New Connection`
2. Create a new connection, e.g. to a database using a DSN, or to Spark, etc., and connect.
3. Close the connection by clicking on the "disconnect" icon: 
![image](https://user-images.githubusercontent.com/31009952/97349323-ba391a00-1865-11eb-947c-8c635fe5ed29.png)
4. Return to the pane's starting screen by clicking on the left arrow: 
![image](https://user-images.githubusercontent.com/31009952/97349610-0dab6800-1866-11eb-8ad1-1d8c4f2488e3.png)
    - Note that the connection is now listed in the pane
5. Click on `New Connection`
6. Create a new connection, e.g. to a database using a DSN, or to Spark, etc., and connect.
7. Close the connection by clicking on the "disconnect" icon
8. Return to the pane's starting screen by clicking on the left arrow.
9. Click on one of the connections.
10. Remove the connection by click on the trash icon: 
![image](https://user-images.githubusercontent.com/31009952/97349765-41868d80-1866-11eb-92dd-0277b5b4b219.png)
    - We are back at the main screen of the Connections pane, but all of the connections are gone.

### Describe the problem in detail

All the connections get removed.

### Describe the behavior you expected

Only the connection that was marked for removal should be removed; the rest should still be available.

I'm not sure if this qualifies as a regression, a new issue, or a variant of an existing issue (#6336), so I'm marking it for 1.4 for the moment.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks @ronblum! I can reproduce this as well with your instructions.

**Comment by melissa-barca** [comment]
Verified in 1.4.997
