### ISSUE TITLE
R User Manuals in the Help pane fail to open when selecting the relevant link and cannot be opened at all in PDF format.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#8206]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.4.999 (384ca38f) , Qt internal build
    OS Version      : macOS 11.0 Beta (Big Sur)
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Load the IDE and open the Help Pane.
2. From Help pane home, select 'User Manuals' > select any Manual link (example: `utils::Sweave`) or the associated PDF link.

### Describe the problem in detail
Manuals fail to open and no indication of an error or failure is displayed. 

Manuals can still be opened in `source` or `R code`.

### Describe the behavior you expected

Testing this same behavior in the latest 1.4 daily build (1.4.979), selecting manual links opens them in a PDF format outside of the IDE. Same behavior is expected from the Qt build.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Adding this issue to the 1.4 milestone since it appears to be a direct product of the Qt update on macOS.

**Comment by kevinushey** [comment]
With Qt 5.15.2, I see the following navigation request:

```
QUrl("chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html?http://127.0.0.1:32718/help/library/utils/doc/Sweave.pdf") [ QWebEnginePage::NavigationTypeLinkClicked ]
```

which a Google search suggests is used for Google's own internal PDF viewer.

**Comment by kevinushey** [comment]
See also:

https://bugreports.qt.io/browse/QTBUG-75588

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/rstudio/commit/4361420782946211cdb93475abeab9fde6378caf. (Sorry, forgot to make this a PR first...)

**Comment by gtritchie** [comment]
Marking as out-of-scope now that we're not upgrading to 5.15 for RStudio 1.4.
