### ISSUE TITLE
rstheme .ace_keyword affects console output

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#8207]
The console output color is affected by the `.ace_keyword` rsTheme variable.

**Comment by ronblum** [comment]
@jzadra Thank you for raising the issue! Can you provide a brief example so that we can try to reproduce this? Also, what environment are you working with? Specifically:

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jzadra** [comment]
Example: edit the color for `.ace_keyword` in an rsTheme, then switch themes to some other one and back to the custom theme.  The console output has changed to the color for `.ace_keyword` (and in fact the previous console output color matched the previously set color).

This occur on both of my systems:

R version 4.0.2 (2020-06-22)
macOS Mojave 10.14.6  and Catalina  
RStudio 1.2.5033 and 1.4.970
