### ISSUE TITLE
Scroll bar activation

### ISSUE THREAD

**Issue by robross45** [rstudio/rstudio#8210]
When I move my mouse pointer across a scroll bar in the script pane and into another pane I often find that the scroll bar activates (as if I had clicked on the scroll bar), which results in me scrolling all around my script at random.

RStudio version 1.3.1073
MacOS 10.15.7

**Comment by ronblum** [comment]
@robross45 Thank you for raising this! As a comparison point, does this happen when you used the trackpad, as well, or just an external mouse?

**Comment by robross45** [comment]
Hi Ron,

The problem occurs with my trackpad too. Interestingly, I can’t put my finger on exactly what makes the problem start. It has something to do with my interactions with RStudio environment because when the problem is not occurring I can move my mouse around in the RStudio and the problem never starts. Rather, I have to highlight some code, scroll through my code, etc to make the problem begin at some random moment. Once the problem has started if I click on the slider and shift it around a bit then the problem will stop for some time, until it begins again after a few minutes of working in RStudio.

Rob
