### ISSUE TITLE
Monospace font preview is variable-width instead of fixed-width

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8212]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.999 384ca38f
    OS Version      : MacOS 11 Big Sur
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Tools -> Global Options -> Appearance
2. Set editor font to "monospace", if it isn't already.
    - The preview text will be in a variable-width font

### Describe the problem in detail

The preview text for "monospace" is in variable-width font.

<img width="453" alt="monospace" src="https://user-images.githubusercontent.com/31009952/97468176-5cffa000-191b-11eb-9d49-9fbe5cb91704.png">

### Describe the behavior you expected

The text should be fixed-width. Note that applying the font works fine. It's only the preview that has an issue.

This appears to be a problem with the updated Qt package, as it works fine in 1.4.962.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: It's not an issue on MacOS 10.15.6 Catalina. And I don't think that  "monospace" is even supposed to be an option.

**Comment by ronblum** [comment]
The stray "monospace" font has disappeared, so I can't reproduce this...

**Comment by kevinushey** [comment]
I've seen this a couple times as well. From what I can recall, it seems like this happened when switching back and forth between the "regular" 1.4 preview release and the Qt 5.15.2 experimental builds.

**Comment by gtritchie** [comment]
Resolving as out-of-scope now that we're not upgrading to 5.15 for RStudio 1.4.
