### ISSUE TITLE
Shiny Run Document dropdown empty

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8213]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.980 (tried back to 1.4.100 with same results)
    OS Version      : any (tried Mac Catalina and Big Sur, Windows-10 for desktop, Centos7 for server)
    R Version       : various

### Steps to reproduce the problem
- File / New File / R Markdown...
- Configure for Shiny as follows:

<img width="532" alt="New R Markdown dialog with Shiny selected" src="https://user-images.githubusercontent.com/10569626/97470699-1606b000-1905-11eb-9321-5b0be9bf9dad.png">

- Click on the little arrow next to Run Document button on editor toolbar

### Describe the problem in detail
- Get a little grey box, no dropdown

<img width="352" alt="screenshot of little rectangle shown instead of dropdown menu" src="https://user-images.githubusercontent.com/10569626/97471065-90373480-1905-11eb-815b-9a3f2085b1a6.png">

### Describe the behavior you expected
- Dropdown as shown here in 1.3.1093 with Record Test and Run Tests options

<img width="594" alt="dropdown showing " src="https://user-images.githubusercontent.com/10569626/97470821-3afb2300-1905-11eb-8505-5bfa80e0a554.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note: the menu appears to show up after the document has been saved.

<img width="515" alt="Screen Shot 2020-10-28 at 1 42 11 PM" src="https://user-images.githubusercontent.com/1976582/97494368-71e03180-1923-11eb-81c9-754085db87d0.png">

<img width="520" alt="Screen Shot 2020-10-28 at 1 42 31 PM" src="https://user-images.githubusercontent.com/1976582/97494375-73115e80-1923-11eb-94ea-64c1408aae2e.png">

**Comment by kevinushey** [comment]
The plot thickens:

<img width="215" alt="Screen Shot 2020-10-28 at 3 52 33 PM" src="https://user-images.githubusercontent.com/1976582/97505174-a52bbc00-1935-11eb-89be-5b7d38f472b3.png">

<img width="231" alt="Screen Shot 2020-10-28 at 3 52 42 PM" src="https://user-images.githubusercontent.com/1976582/97505170-a4932580-1935-11eb-9afb-33751e870130.png">

Looks like when the document is first loaded, the wrong menu button is being toggled into visibility here.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990
