### ISSUE TITLE
system error 17 (file exists) when using replace all in find in files window

### ISSUE THREAD

**Issue by nevilamos** [rstudio/rstudio#8218]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.3.1093
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem
seach of text in project using menu "find in files" and provide replace text
### Describe the problem in detail
on using replace all button no text is replaced in files and error 17 file exists error is retruned for eahc case where text should be replaced.  Screen grab incuded below.
![Untitled](https://user-images.githubusercontent.com/47512331/97504562-38fb9780-19cb-11eb-820f-a0d1837b2526.png)

### Describe the behavior you expected
replacement of found text with  replacement text in place idetified by find in files

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This should be fixed in the latest [daily builds](https://dailies.rstudio.com).

**Comment by melissa-barca** [comment]
@nevilamos Please let us know if this issue persists in the daily builds. Thanks!

**Comment by nevilamos** [comment]
Thanks Daily build sorted the issue
