### ISSUE TITLE
Rtools not recognized even when it is installed

### ISSUE THREAD

**Issue by herambgadgil** [rstudio/rstudio#8221]
### System details

    RStudio Edition : Desktop - Open Source
    RStudio Version : 1.4.887 - Wax Begonia
    OS Version      : Windows 10
    R Version       : 3.6.3
    Rtools Version  : 3.5.0.4

### Steps to reproduce the problem
Install `Rtools` in a location other than `C:\Rtools\` 

### Describe the problem in detail
I have all my R-installations `R-3.6.3`, `RStudio` and `Rtools` in my personalized folder `C:\Users\ID\OneDrive - Org\OpenSources\R`

Following locations are added to the `PATH` variable
`C:\Users\ID\OneDrive - Org\OpenSources\R\Rtools\bin`
`C:\Users\ID\OneDrive - Org\OpenSources\R\Rtools\mingw_32\bin`
`C:\Users\ID\OneDrive - Org\OpenSources\R\Rtools\mingw_64\bin`
`C:\Users\ID\OneDrive - Org\OpenSources\R\R-3.6.3\bin\x64`

But still the following message pops-up every time while installing a package
```
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
```
The warning goes away if `devtools::find_rtools()` is executed at the start. 

### Describe the behavior you expected

If the `Rtools` paths are added to the `PATH` variable, RStudio should find it automatically. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@herambgadgil Thank you for raising this issue! We'll review it as part of our development cycle.

**Comment by ronblum** [comment]
@herambgadgil Actually, a few questions:
1) Does adding `${RTOOLS40_HOME}\usr\bin` to `PATH` make a difference? See the  "Putting Rtools on the PATH" at https://cran.r-project.org/bin/windows/Rtools/ . 
2) If you used RStudio Desktop 1.3, did it work there?

**Comment by herambgadgil** [comment]
@ronblum - It did the same on `Rstudio - 1.3`

I thought `Rtools40` is for `R-4.0.0` and higher. I am still on `3.6.3`. Do you still recommend installing it?

Thanks!
Heramb

**Comment by ronblum** [comment]
@herambgadgil No, you don't need to--I've led you astray. I'll try to reproduce with Rtools 3.5 and see what happens.

**Comment by kevinushey** [comment]
Can you also confirm what the following reports?

```
.rs.isRtoolsOnPath()
```

One possibility is that you need to set the `BINPREF` environment variable as well; normally it needs to be set as e.g.:

```
Sys.setenv(BINPREF = "C:/Users/ID/OneDrive - Org/OpenSources/R/Rtools/mingw_$(WIN)/bin/")
```

Note that you may have trouble using an edition of Rtools installed in a path containing spaces, though.

**Comment by herambgadgil** [comment]
@kevinushey  I get the following - 

```
> .rs.isRtoolsOnPath()
[1] FALSE
> devtools::find_rtools()
[1] TRUE
> .rs.isRtoolsOnPath()
[1] TRUE
```
`Sys.setenv(BINPREF = "C:/Users/ID/OneDrive - Org/OpenSources/R/Rtools/mingw_$(WIN)/bin/")` has the same temporary effect as `devtools::find_rtools()`. It needs to be done every time I start a new session. 

But if I define it in `Control Panel > Enviroment Variables` then `.rs.isRtoolsOnPath()` returns `TRUE` the first time itself. 

> Note that you may have trouble using an edition of Rtools installed in a path containing spaces, though.

I had that feeling earlier. Spaces in file paths make me uncomfortable. But I have a very little control over it. :-)

**Comment by jmbuhr** [comment]
I believe I have some more hints on this. It is not related to Rtools iself. The culprit is OneDrive. As of this point I am unsure what exactly breaks, but it might be related to long file paths being a problem on windows. A student of mine was unable to display tibbles/dataframes in Rmd files underneath code chunks. I believe this happened because in order to do that a temporary file is created whose path exceeds the limit of 260 characters if the project is in a folder that is being backed up by OneDrive.
