### ISSUE TITLE
UI doesn't update based on changes in Keyboard Shortcuts

### ISSUE THREAD

**Issue by taswiq** [rstudio/rstudio#8222]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      :  Windows 10 
    R Version       :  3.5.1/3.5.3/4.0.2

### Steps to reproduce the problem

Change the keyboard shortcut from _Ctrl+Shift+F10_ to _anything else_
Go to the session menu and see the Restart R shortcut, it will still be Ctrl+Shift+F10

### Describe the problem in detail
The UI doesn't update to show the new shortcut.

### Describe the behavior you expected
The UI should show the new shortcut

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@taswiq Thank you for raising this! We have an open issue to track this, #5256, so I'm marking this as a duplicate.
