### ISSUE TITLE
projects with UTF-8 characters in path cannot be opened via rstudioapi

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8225]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : Windows 10 x64
    R Version       : 4.0.3

### Steps to reproduce the problem

Try running the following script:

```
nihao <- "~/你好"
dir.create(nihao)
rstudioapi::openProject(nihao)
```

### Describe the problem in detail

RStudio fails to initialize the project:

<img width="763" alt="Screen Shot 2020-10-29 at 10 51 53 AM" src="https://user-images.githubusercontent.com/1976582/97612520-c2fc2e00-19d4-11eb-826d-4c60e79c0f31.png">

### Describe the behavior you expected

RStudio should be able to open and initialize the project without issue.

See also: https://github.com/r-lib/usethis/issues/1231

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Verified in 1.4.997
