### ISSUE TITLE
C++ autoindent tests are broken

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8229]
### System details

    RStudio Edition : N/A
    RStudio Version : 1.4.984

### Steps to reproduce the problem

1. Clone the RStudio repo.
2. From `rstudio/src/gwt/tools`, run `sync-ace-commits` to clone our Ace editor fork.
3. Open the C++ autoindent tester:

```
src/gwt/test/autoindent_test_cpp.html
```

### Describe the problem in detail

JavaScript errors:

```
Uncaught RangeError: Invalid array length
    at CppCodeModel.getNextLineIndent (cpp_code_model.js:1523)
    at Mode.getNextLineIndent (c_cpp.js:176)
    at Editor.insert (ace.js:13710)
    at doIndentTest (autoindent_test_cpp.html:763)
    at autoindent_test_cpp.html:833
```

as well as a number of failing tests, e.g.: 

![image](https://user-images.githubusercontent.com/470418/97622402-7834e300-19e1-11eb-92cb-ab2e308e36b4.png)

### Describe the behavior you expected

These tests should run and pass. I was able to get most of the tests running with https://github.com/rstudio/rstudio/commit/f07c3d116eb236010cf434abc06f8086394226ff, but not all. I've also hand-checked the scenarios that were failing and didn't find any regressions in functionality, so suspect that there's something wrong with the test setup (missing dependency or other runtime state?) that's causing it to fail.

**Comment by kfeinauer** [comment]
Verified - developer only.
