### ISSUE TITLE
The shortcut to focus the cursor on the terminal is not documented in the Keyboards Shortuts help

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#8230]
This affects RStudio V1.4.

### Describe the behavior you expected

After pressing Alt+Shift+K I expected to see the updated shortcut to focus the cursor on the terminal console. Instead I saw this:

![image](https://user-images.githubusercontent.com/1825120/97628441-9b34b680-1a24-11eb-8b4f-0e07added415.png)

I found the new default shortcut in [`keyboard.htm`](https://github.com/rstudio/rstudio/blob/97d7fc61728ad9693d79ef7b5f6d7dd1318c55d1/src/gwt/www/docs/keyboard.htm)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
It is actually there, but under a different section. I'll move it under the Terminal section to be more consistent with the layout in keyboard.htm.

<img width="198" alt="2020-10-29_14-42-38" src="https://user-images.githubusercontent.com/10569626/97635756-1b432800-19f5-11eb-88ea-ebd7f5322cf4.png">

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990
