### ISSUE TITLE
files created via File -> New File -> R Markdown... ignore source columns

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8235]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.978
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Ensure the IDE has one or more source columns open.
2. Focus one of those source columns.
3. Create a new R Markdown document via the File -> New File -> R Markdown... "wizard" accessed from the main menu.

### Describe the problem in detail

The new document is created in the "main" source window, rather than in the last-active source column.

### Describe the behavior you expected

The new document should be opened in the last-active source column.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note that things work as expected if you create the document using "internal" RStudio UI; e.g. via the New Document button at the top-left corner of the IDE:

<img width="230" alt="Screen Shot 2020-10-29 at 2 57 07 PM" src="https://user-images.githubusercontent.com/1976582/97636924-0bc4de80-19f7-11eb-9895-dbf1f5cf9500.png">

**Comment by gtritchie** [comment]
Verified on macOS Big Sur using 1.4.1033.
