### ISSUE TITLE
Ctrl + 1 always targets "main" Source editor

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8236]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.978
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Ensure your IDE has a source column available.
2. Create an R script in that source column.
3. Focus the R script in the source column.
4. Use `Ctrl + 2` to focus the R console.
5. Use `Ctrl + 1` to return focus to the source column.

### Describe the problem in detail

`Ctrl + 1` always sends focus to the "main" source window.

### Describe the behavior you expected

`Ctrl + 1` should send focus to the last-focused source column (if any), or the "main" source window if none available.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Verified in 1.4.1033 on macOS Big Sur.
