### ISSUE TITLE
multiple blinking cursors in Ace instances

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8237]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.978
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Create a new source document,
2. Click on the Console pane, to send focus to the console input,
3. Click outside of RStudio into a separate window,
4. Return focus to RStudio, clicking on the Source pane.

### Describe the problem in detail

Some percentage of the time, you will end up in a state where bot the console cursor + the Source editor's cursor are blinking.

![dual-blinking-cursors](https://user-images.githubusercontent.com/1976582/97640324-b93af080-19fd-11eb-911b-4f1adbaade84.gif)

### Describe the behavior you expected

Only the actually focused editor should have a blinking cursor.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990
