### ISSUE TITLE
Unable to connect to BetterBibTeX

### ISSUE THREAD

**Issue by LeonBarmuta** [rstudio/rstudio#8241]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.983
    OS Version      :  Microsoft Windows 10 Enterprise Version 10.0.19041 Build 19041
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Start Zotero (Better BibTeX issues usual information about starting; latest updates have been installed. Zotero version 5.0.92).
2. Start RStudio via double-clicking on .rproj file. (Using Visual R Markdown    @##mode.)
3. Menu sequence: Tools > Global Options > Rmarkdown > Citations and check "Use Better BibTeX..." box. Press OK. 
4. Insert reference either via short cut key or menu and popup opens with banner as shown in the attached image, announcing that Zotero and BetterBibTeX are not running. 

### Describe the problem in detail
![BetterBibTeX_RStudio](https://user-images.githubusercontent.com/13636037/97661427-6a0dc200-1ac8-11eb-8b99-4ead56f9813b.png)

Same behaviour if RStudio is started first and then Zotero. If I go ahead and export a selected reference anyway, the record arrives in the local .bib file without line breaks. However, the .Rmd file renders OK and citations and bibliography are formatted correctly - but with additional junk in some fields that I have set Better BibTeX to omit on export. 

If the "Use Better BibTeX..." box is unchecked, the selected reference is copied to the local .bib file with line breaks. 

### Describe the behavior you expected

Expected BetterBibTeX settings to be respected when reference is exported (in particular I'm trying to exclude fields that don't mesh with the CSL I intend to use). 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
I have reproduced this on a local windows installation so I'm in progress taking a closer look.

**Comment by gtritchie** [comment]
Fixed via #8268

**Comment by kfeinauer** [comment]
@LeonBarmuta We believe this should be fixed in the latest daily build of RStudio. Would you be able to check to see if this fixed for you?

**Comment by LeonBarmuta** [comment]
Ran a couple of short tests yesterday, and this seem to have been fixed. Thank you‼

Cheers,
Leon
Dr Leon A. Barmuta
+ 61 3 6226 2785 | Fax + 61 3 6226 7222
[cid:image001.png@01D6BCF9.B8A136E0]
CRICOS 00586B
