### ISSUE TITLE
Hanging after opening a project

### ISSUE THREAD

**Issue by mbojan** [rstudio/rstudio#8242]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.972
    OS Version      : Windows 10
    R Version       : R 4.0.3

### Steps to reproduce the problem

Open a project. The project was closed with some files open.

### Describe the problem in detail

RStudio hangs, as in the screenshot below. The file tab is not loading, the console is not responsive (i enter an expression, press enter and nothing happens:

![rstudio-files](https://user-images.githubusercontent.com/636574/97703194-8271e280-1ab0-11eb-8eab-34a31158cdd9.PNG)

The diagnostic reports comes from a separate launch so I'm not sure if it is of any use...
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5465045/diagnostics-report.txt)

The task manager shows that some crash handlers are running, but nothing happened for several minutes:

![rstudio-taskmgr](https://user-images.githubusercontent.com/636574/97703248-9d445700-1ab0-11eb-828e-27b3358c16b6.PNG)

### Describe the behavior you expected

RStudio works seamlessly as usual.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mbojan** [comment]
I updated to 1.4.990 and the problem persists. Interestingly, it seems it happens only when I open one particular RStudio project.

**Comment by kevinushey** [comment]
Is there any chance you could share those package sources so we could try to reproduce ourselves?

You might also try resetting RStudio's state (specifically, the project-specific state for that project): https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by mbojan** [comment]
Thank you @kevinushey . The repo are half-baked teaching materials that I'd rather not make public. However, I'll happy to add you or someone else from RStudio to the repo so that you can debug this further. 

Meanwhile, I have reset the RStudio state as you suggested (I renamed both `rstudio` and `rstudio-desktop` folders in `appdata\local`). The problem persists on my laptop, but I can't reproduce it on my desktop. This is very strange.

**Comment by mbojan** [comment]
Btw, if I have two Rstudio installations 1.2.xxx and 1.4.990 are they sharing the state?

**Comment by kevinushey** [comment]
No, RStudio 1.2 and 1.4 use different folders for their saved state.

**Comment by mbojan** [comment]
I can't seem to reproduce it myself on a different machine (same operating system, R version and RStudio version, repo commit). Perhaps the hang was caused by some strange combination of the RStudio state, project state and so on.

I think it we can close it at this time @kevinushey .
