### ISSUE TITLE
clicking at end of line ending with inline math doesn't place cursor at end

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8249]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

Create a new R Markdown document, enter visual mode, and then create a line with the contents:

```
This is some inline math: $\sum_{i=1}^nX_i$
```

Then, try to click to the right of the inline math, to place the cursor as the end of the line.

### Describe the problem in detail

The cursor is placed somewhere into the (expanded) inline math equation after click. It also seems like, at least in this case, the inline math shouldn't be expanded as the click target was the end of the line as opposed to the math expression (although that's somewhat fuzzy)

![visual-mode-inline-math](https://user-images.githubusercontent.com/1976582/97746895-5b171780-1aa8-11eb-946a-3b531ff28950.gif)

### Describe the behavior you expected

The cursor should be placed at the end of the line, if the user had targeted beyond the end of the (displayed) line.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
This is by design as we can't actually distinguish where the click occurs so we always place the cursor in the middle.
