### ISSUE TITLE
Failure to load R when starting projects on Windows long path (versions 1.4xxx)

### ISSUE THREAD

**Issue by javbermejo** [rstudio/rstudio#8256]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  Previews all 1.4xxx above (works with 1.3xxx)
    OS Version      :  Windows
    R Version       :  4.03

### Steps to reproduce the problem
Attempting to load a project in a long trajectory fails to load R and.

### Describe the problem in detail
When loading a project stored in a "long path" directory trajectory (Windows), R crashes. Works OK with RStudio versions 1.3xxxx

### Describe the behavior you expected
Load properly (as in versions 1.3xxx)

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![image](https://user-images.githubusercontent.com/73740700/97776930-a4309f80-1b6c-11eb-8024-8756d13dee15.png)
![image](https://user-images.githubusercontent.com/73740700/97776944-b9a5c980-1b6c-11eb-9162-55f4bde251fd.png)

**Comment by kevinushey** [comment]
> When loading a project stored in a "long path" directory trajectory (Windows), R crashes. Works OK with RStudio versions 1.3xxxx

It would help if you could provide an example path wherein this issue reproduces.

**Comment by javbermejo** [comment]
"C:\Users\javie\Madrid Digital\HGUGM CARDIOLOGIA - Investigación Imagen - Investigación Imagen\Indices of AS\Stats Indices of AS\Indices of AS.Rproj"
Opens OK with any version < 1.4xxxx

**Comment by Yoshinobu-Ishizaki** [comment]
Same error occurs on me. 
I think this is related to the windows path which contains non-ascii character.
When I intend to create a new R project at "C:\\日\" folder ( 日 is a one of Japanese character), RStudio crashes with a same message below.

![image](https://user-images.githubusercontent.com/36043439/98119796-75118980-1ef0-11eb-8514-12f60a6106e2.png)


```
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)
```

OK on 1.3.x but NG on 1.4.x-previews ( 1.4.993 at this time) .

**Comment by kevinushey** [comment]
Thanks! I was able to reproduce something similar after trying to switch to a Japanese locale from an English locale:

```
> Sys.setlocale(locale = "Japanese")
[1] "LC_COLLATE=Japanese_Japan.932;LC_CTYPE=Japanese_Japan.932;LC_MONETARY=Japanese_Japan.932;LC_NUMERIC=C;LC_TIME=Japanese_Japan.932"
Warning message:
In dir.create(tempPath, recursive = TRUE) :
  cannot create dir 'C:\Users\kevinushey\scratch\?', reason 'Invalid argument'
```

**Comment by gtritchie** [comment]
I was able to repro as follows with 1.4.1001 (build just before the fix):

- created a new project from the IDE with non-ascii Japanese characters
- in Console, `Sys.setlocale(locale = "Japanese")`
- get `cannot create dir` error that Kevin observed

With build 1.4.1007, this error no longer happens.
