### ISSUE TITLE
RStudio sources on save even though that option is unselected

### ISSUE THREAD

**Issue by arencambre** [rstudio/rstudio#8259]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      :  Windows 10 20H2
    R Version       : 4.0.3

### Steps to reproduce the problem
Hit Ctrl-S to save when the **Source on Save** button is unchecked in the IDE.

### Describe the problem in detail
When I save an R script, the script is being sourced on each save even though the checkbox is not checked:
![image](https://user-images.githubusercontent.com/411495/97810220-fb4f7680-1c37-11eb-9ce3-1d0696dfb9eb.png)

I know it's being sourced because 1. the script takes a long time to run and 2. this is being run in the console each time I save the file:
`source('C:/Users/[path to file]/database test.R')`

A few minutes ago, **Source on Save** _was_ checked. I do not recall checking it. It was saved once or twice with this checked, and it would be expected behavior for the file to source on save with that option checked. However, I unchecked the box, and the file kept sourcing on saves.

### Describe the behavior you expected

If **Source on Save** is not checked, then files should never be sourced upon a save.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: I'm unable to reproduce this on Windows 10 with RStudio Desktop 1.3 and 1.4.

**Comment by arencambre** [comment]
Same here. Cannot reproduce.

**Comment by R-Hannibal** [comment]
Closing this issue for now based on our lack of ability to successfully reproduce it.

@arencambre -please re-open the ticket if this starts happening for you again 👍.
