### ISSUE TITLE
File path autocompletion fails in Rmarkdown document

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/rstudio#8260]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.993
    OS Version      : pop-os 20.10
    R Version       : 4.0.3

### Steps to reproduce the problem

Create an Rmarkdown document in a subdirectory of an RStudio project.
In a code chunk, type opening and closing quotation marks (`""`) and activate the file path autocompletion
with Ctrl+Space or Tab.

### Describe the problem in detail

The following error-box appears: `R code execution error`
with the console message:

```
Error in isNamespaceLoaded(pkg) : 
  attempt to use zero-length variable name
```

This does not happen if you explicitly add the dot (`.`) to signify
the current directory in the quotation marks before triggering
autocompletion. `""` Fails, `"."` works.

### Describe the behavior you expected

File path autocompletion works.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Could we please repro this on a supported OS to see if it's only a pop-os issue?

**Comment by mikebessuille** [comment]
In any case, this is not a critical issue for 1.4.  There is an easy workaround for this.

**Comment by jmbuhr** [comment]
I was just able to reproduce it on the latest Windows 10, using the same steps.

**Comment by kevinushey** [comment]
This needs to be fixed in 1.4 and the fix will be trivial.

**Comment by kevinushey** [comment]
I've definitely seen this issue before but I'm now struggling to reproduce. @jmbuhr can you provide any extra context? Can you share a project or something similar where you can reliably reproduce this behavior?

**Comment by jmbuhr** [comment]
I noticed something weird I haven't considered before! It is not about the location of the Rmd document in the project, it is the existence of a folder named `data` in the same directory

**Comment by kevinushey** [comment]
Thanks! I can reproduce given that information.

**Comment by melissa-barca** [comment]
Verified in 1.4.1000.
