### ISSUE TITLE
Theme setting lost after restarting RStudio or R within RStudio (on MacOS but not Linux)

### ISSUE THREAD

**Issue by courtiol** [rstudio/rstudio#8264]
When I set the appearance theme (any) and apply it, I see the expected change in RStudio but then when I click on Session/Restart R (or when I restart RStudio), I get back the initial theme...

I have this problem on my Mac:
Version 1.4.993 "Wax Begonia" (3c5a8f29, 2020-10-30) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

BUT not on my Linux:
Version 1.4.993 "Wax Begonia" (3c5a8f29, 2020-10-30) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

On my Mac I also had the same problem before updating to preview with the latest RStudio (1.3.1093)

I have no other Mac at hand to check if this is a machine issue or a RStudio issue... Sorry.

**Comment by courtiol** [comment]
Same as gif:
![Uploading issue8264_small.gif…]()

**Comment by courtiol** [comment]
Ha! I found the issue, this was a local issue: I had change my R_HOME in .Renviron
I leave this open for you to judge if it is simply a misconfiguration or if it should work no matter the settings for R_HOME
I guess the former is correct, but we never know!

**Comment by ronblum** [comment]
@courtiol What did you set `R_HOME` to? I've tried several cases, but I don't have a theme issue—RStudio doesn't start up at all.

<img width="1326" alt="r_home_1" src="https://user-images.githubusercontent.com/31009952/98710071-31d07400-2351-11eb-97d3-8b1f27b6fe09.png">

<img width="1268" alt="r_home_2" src="https://user-images.githubusercontent.com/31009952/98710120-3eed6300-2351-11eb-8fa6-b00ab038fd1a.png">

**Comment by courtiol** [comment]
Very sorry @ronblum, I should have written tht down and I did not... I can no longer reproduce :-/
I cannot recall in the first place why did I try to mess with R_HOME.
If I do, I will reopen and issue. In the meantime, I close it.
