### ISSUE TITLE
R studio crashed while running python 

### ISSUE THREAD

**Issue by Butterflyer043** [rstudio/rstudio#8274]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1093
    OS Version      : "Darwin" 
    R Version       : "R version 3.6.3 (2020-02-29)"

### Steps to reproduce the problem
I run the {r} chunk first:
 ```{r}
library(reticulate)
#mac environment 
use_condaenv('r-reticulate',required=TRUE)
```
And then run the {python} chunk:
```{python}
# import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pylab import *
import matplotlib.colors as colors
```
The R studio crashed without any other information.
![image](https://user-images.githubusercontent.com/57601781/97938866-8b80df00-1d50-11eb-8d67-000aebc936fe.png)

I tried to re-install the package "rcpp" and "reticulate" but it does not work.

**Comment by cderv** [comment]
For reference, also posted on community : https://community.rstudio.com/t/r-studio-crashed-while-running-python-by-reticulate-packages/86712

**Comment by mikebessuille** [comment]
Kevin can you please have a look at this one potentially for 1.4?

**Comment by kevinushey** [comment]
Does this work if you use a different Python installation (not Conda)?

**Comment by Butterflyer043** [comment]
> Does this work if you use a different Python installation (not Conda)?

No, it doesn't work.

**Comment by Butterflyer043** [comment]
I have solved the problem. It is the path problem, the path that got from the py_config() in r and "conda info --envs" in the terminal doesn't work.

I ran the:
(base) MacBook-Pro:~ **$ conda activate
(base) MacBook-Pro:~ **$ which python
/opt/anaconda3/bin/python

then ran in R-studio:
use_python("/opt/anaconda3/bin/python",required=TRUE)

**Comment by kevinushey** [comment]
Thanks for reporting back; glad to hear you were able to resolve the issue!

**Comment by kfeinauer** [comment]
Verified not a bug.
