### ISSUE TITLE
Harmonize command names for `Execute Subsequent Chunks` function

### ISSUE THREAD

**Issue by davidski** [rstudio/rstudio#8275]
The nifty command palette in RStudio 1.4 exposes some inconsistency in how RStudio functions are displayed through the interface. One that I regularly encounter is the `Execute Subsequent Chunks` function. This is labelled `Execute Subsequent Chunks` in the Modify Keyboard Shortcuts dialog, as `Run All Chunks Below` in the Run drop down in a RMarkdown notebook, and `Run all chunks after the current one` in the command palette.

I often try to use the palette keyboard shortcut to run this function, keying in `below`, only to be surprised that the function is not found. I have to use one name in the palette and another when demonstrating the function to graphical users. That there is a third version in the keyboard shortcuts is just madness. 😜 I suspect Execute Subsequent Chunks is a more canonical name, given that that's what appears under `~/.config/rstudio/keybindings/rstudio_bindings.json`.

In addition to discoverability issues, this may impact accessibility for some users.

**Comment by jmcphers** [comment]
You're right, these could be better.

**Comment by jmcphers** [comment]
Fixed in Juliet Rose via #8602

**Comment by davidski** [comment]
I feel sheepish for mentioning it, but does that big merge change the behavior of the execute subsequent chunks to run chunks after, but not including, the current chunk? I had started [this thread](https://community.rstudio.com/t/behavior-of-run-chunks-before-vs-run-chunks-after/90120) on the RStudio Community forum about what is -- for me -- non intuitive behavior of this function. I'm happy to open another issue for consideration. Since it looks like some replumbing was done there now, I'm hoping this isn't too much scope creep. :smile:

**Comment by jmcphers** [comment]
No, it doesn't change the behavior of the commands. You're welcome to open another issue to suggest that Run Below should not run the current chunk. We probably won't change the semantics there unless at least a few people show support for it since some people have likely grown to depend on the way things work now.
