### ISSUE TITLE
libtinfo.so.6: no version information available (required by bash)

### ISSUE THREAD

**Issue by f0nzie** [rstudio/rstudio#8278]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.3.1093
    OS Version      : Debian Buster
    R Version       : 3.6.3

### Steps to reproduce the problem
1. Install a Python environment with Anaconda 3 (Version July 2020)
2. Add three code chunks of R, bash and Python
3. Knit to HTML
4. A warning you will see in the Bash box when `reticulate::py_config()` is called

### Describe the problem in detail
I have been using RStudio to build books with `bookdown`, and when reviewing more in detail I found out that Bash chunk boxes throw a warning like this: ` libtinfo.so.6: no version information available`. After googling for some time, I tried different solutions with `LD_LIBRARY_PATH`, `LD_PRELOAD`, and also with five different `conda` environments. The warning always came up.

I found that there is only one case that the warning doe not pop up. And that is, when reticulate::py_config() is not used before the `bash` chunk.

For instance, this will throw the bash warning:

```
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, results = "markdown", collapse=FALSE}
library(reticulate)
# reticulate::use_condaenv("porepy")
# reticulate::use_condaenv("python_book")
reticulate::use_condaenv("man_ccia")
py_config()
``` .

``` {bash, results = "markdown", collapse=FALSE, message=FALSE, warning=FALSE}
echo $PATH
echo "working from the terminal"
```  .

```{python}
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```   .
```

while this other won't:

```
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, results = "markdown", collapse=FALSE}
library(reticulate)
# reticulate::use_condaenv("porepy")
# reticulate::use_condaenv("python_book")
reticulate::use_condaenv("man_ccia")

``` .

``` {bash, results = "markdown", collapse=FALSE, message=FALSE, warning=FALSE}
echo $PATH
echo "working from the terminal"
```  .

```{r
py_config()
```  .

```{python}
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```   .
```

### Describe the behavior you expected
I am attaching couple of screnshots that sumarizes the problem.

![rsudio-bash-libtinfo-1](https://user-images.githubusercontent.com/29108853/98028537-dc85e700-1dd3-11eb-8261-4b7878bf41a3.png)
![rsudio-bash-libtinfo-2](https://user-images.githubusercontent.com/29108853/98028655-07703b00-1dd4-11eb-946d-fca76e5475c9.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is an issue with Conda unrelated to RStudio. You can find more info here: https://stackoverflow.com/questions/51408698/when-in-conda-tmux-and-emacs-throw-error-while-loading-shared-libraries-libti

**Comment by aakhmetz** [comment]
I don't know whether it is directly related to conda, but I have got that message after installing r-reticulate

**Comment by scemama** [comment]
A possible cause could be that you prepended `$CONDA_PREFIX/lib` to `LD_LIBRARY_PATH`

**Comment by tautomer** [comment]
> A possible cause could be that you prepended `$CONDA_PREFIX/lib` to `LD_LIBRARY_PATH`

Even if I move `$CONDA_PREFIX/lib` to the end, this error message still shows up. At the end, I have to explicitly prepend `/lib64` to `$LD_LIBRARY_PATH`. I guess this is the same case if the original `$LD_LIBRARY_PATH` doesn't contain the default library locations.

```shell
export LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH:$CONDA_PREFIX/lib`
```
