### ISSUE TITLE
Column numbering in Viewer fails for wide dataframes.

### ISSUE THREAD

**Issue by Arf9999** [rstudio/rstudio#8281]
Apologies if this has been reported, I couldn't find it with a search.

### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.4.904    OS Version      : MacOS darwin17.0 
    R Version       : R version 4.0.2 (2020-06-22)
### Steps to reproduce the problem
`View()` for a wide dataframe shows first 50 columns, if the ">>" button is pressed to view rightmost columns, the numbers shown in the heading are incorrect. 
e.g in a with a dataframe of 93 columns, pressing the ">>" button  causes the selection to show "43 - 50" when in fact the columns displayed are 44 to 93
![image](https://user-images.githubusercontent.com/36820513/98100708-ebcf6800-1e99-11eb-81d3-48a51024cb1f.png)

### Describe the problem in detail
The same issue arises if the actual requested column numbers are typed in. Typing in "50 - 60" displays the correct columns, but the display shows "cols: << < 49 - 50 > >>"
![image](https://user-images.githubusercontent.com/36820513/98100586-bfb3e700-1e99-11eb-8c92-be80b97fbce2.png)

### Describe the behavior you expected
The displayed column numbers should be consistent with the actual columns displayed.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by baderstine** [comment]
same observed in Rstudio 1.4.1103, R version 3.6.3. 

Additionally (possibly a different issue), when a View filter is applied, it is silently removed after the `>` or `>>` buttons are pressed.

**Comment by ronblum** [comment]
Reproduced in RStudio Desktop 1.4.1106 on MacOS 12 beta, but it works as expected in 1.4.1717 and 2021.09.0+351, so it's fixed. If you still run into the issue with the latest releases, please let us know!
