### ISSUE TITLE
View() shows incorrect elements with repeated names

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#8283]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

This was reported on SO, here: https://stackoverflow.com/q/64684900/2554330

I'll give a slightly simplified version:

``` r
mylist <- list(data.frame(x=1), data.frame(y=2))
names(mylist) <- c("A", "A")
mylist
#> $A
#>   x
#> 1 1
#> 
#> $A
#>   y
#> 1 2
```

Now running `View(mylist)` shows the first component twice:

![Screen Shot 2020-11-04 at 1 06 45 PM](https://user-images.githubusercontent.com/1935680/98151728-a2cde280-1e9e-11eb-9d4b-4971300271c4.png)

### Describe the problem in detail

The `View` display  shows the first element twice.

### Describe the behavior you expected

I'd like to see the object displayed correctly, showing the two different components with the same names.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Thanks for the report! This is a long-standing issue, first reported in https://github.com/rstudio/rstudio/issues/2966.
