### ISSUE TITLE
Zotero Group Libraries do not show up

### ISSUE THREAD

**Issue by lucavd** [rstudio/rstudio#8288]
### System details

    RStudio Edition : 
    RStudio Version : 1.4.993-1
    OS Version      : Windows 10 (updated)
    R Version       : 4.0.3

### Steps to reproduce the problem
In Visual Markdown (or standard Markdown) when trying to add a citation from Zotero, only my personal folder is showing up and I can't select the group libraries (even also the references that are in there are not present)

See here for some screenshots

https://community.rstudio.com/t/zotero-group-libraries-do-not-show-up-in-rstudio-citation-in-visual-rmarkdown/86879

### Describe the problem in detail
I tried in different systems and with different Zotero accounts but everyone have the same problem

### Describe the behavior you expected
I expected to see both my library and the group libraries as stated in the presentation blog post of the 1.4 Preview version of RStudio

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
Hi @lucavd. By default, we only show citations from 'My Library.' If you'd like to include group libraries in these searches as well, you can enable them in the Global Options. You can do this at:

Tools > Global Options > R Markdown > Citations 

From there, choose 'Selected Libraries' and select the libraries that you'd like to cite (you should see 'My Library' + a your group libraries):

![Screen Shot 2020-11-05 at 8 19 08 AM](https://user-images.githubusercontent.com/261654/98246202-f7756a00-1f3f-11eb-8b3d-a6f86df8b7fd.png)

Once you've enabled the groups you're interested in globally, you can scope the libraries you use for each document by specifying the libraries you'd like to use for a document in the YAML front matter:

![Screen Shot 2020-11-05 at 8 20 40 AM](https://user-images.githubusercontent.com/261654/98246217-fe03e180-1f3f-11eb-9fec-dee6f0574a58.png)

Hope this gets you going and thanks for reporting the issue!

**Comment by lucavd** [comment]
Cool thank you
