### ISSUE TITLE
Read only mode.

### ISSUE THREAD

**Issue by DirtyWhispers** [rstudio/rstudio#8290]
Hi,

It's very simple really, I journal with Dynalist and I don't want my Journal for 2020 overwitten in anyway, and I think it would be a wheeze if for instance; once files were put in the Archive that they should become read only.

**Comment by jmcphers** [comment]
RStudio doesn't have an Archive -- is this repository where you meant to file the request?

**Comment by DirtyWhispers** [comment]
Sorry, I got linked here to suggest a feature on Dynalist!

This can be deleted.

**Comment by jmcphers** [comment]
No worries! :-)
