### ISSUE TITLE
RStudio intermittently becomes unresponsive when closing the visual editor

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8291]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.999

### Steps to reproduce the problem

1. Open an R Markdown document which has a lot of code chunks (https://github.com/hadley/mastering-shiny has a good set, try e.g., `action-tidy.Rmd`)
2. Switch the document to visual mode
3. Wait for the visual mode switch to complete, then close the tab
4. Open the document again
5. Shortly after the document has appeared in the visual editor, close the tab
6. If RStudio does not hang, repeat steps 4-5

### Describe the problem in detail

Sometimes, RStudio hangs and becomes completely unresponsive at step 5. 

### Describe the behavior you expected

No hang.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
