### ISSUE TITLE
JS exception when attempting to read console history

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8293]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

Run some R code that generates an error; e.g.

```
stop("Oh no!")
```

### Describe the problem in detail

On occasion, a JS error is seen in the console:

<img width="1920" alt="Screen Shot 2020-11-04 at 1 56 26 PM" src="https://user-images.githubusercontent.com/1976582/98172142-ad3faa80-1ea5-11eb-8967-350e6a7fddae.png">

This effects later attempts to access the console history.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1007
