### ISSUE TITLE
Close all except current does not close all

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#8295]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1002
    OS Version      :  Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem
* Open RStudio
* Open somes files with an unsaved new Rscript in the middle
* Select one of the file (before last one for example) 
* Close All Except Current - Don't save when asked
* The file is there but is not the only kept 

### Describe the problem in detail

![close-all](https://user-images.githubusercontent.com/6791940/98230667-b12e0400-1f5b-11eb-90f4-d7b14b28a202.gif)

Previous similar issue reported : https://github.com/rstudio/rstudio/issues/8092

### Describe the behavior you expected

Only the selected file should be kept

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Interestingly, I'm not able to reproduce on macOS (1.4.1000).

Out of curiosity, does this work if you have multiple unsaved documents? (In this case, we show a different type of dialog that might make a difference here.)

**Comment by melissa-barca** [comment]
I wasn't able to reproduce on macOS but am on Windows 1.4.1004.

**Comment by gtritchie** [comment]
See also: #8092

**Comment by melissa-barca** [comment]
@cderv Hm coming back to this and I'm struggling to reproduce. How consistently can you reproduce this?

**Comment by cderv** [comment]
@melissa-barca I can reproduce each time on some configurations: 

* No file opened in source pane
* Open a file with content
* Open another file with content
* Create a new R file and type some content -> **do not save**
* Open another file with content
* Open another file with content
* **select the second opened file**
* File > Close all except current -> don't save
* Two files are open and the one selected is the one that has been opened after the unsaved file. 

This works with only three file too for me:
* Open a file with content
* Create a new file -> type something but don't save
* Open a file with content
* select the first > Close all except current > don't save 
* The two file are still here and the last one is selected 

This works each time I try - even after I retry. 

I tested some edge case (like unsaved one at start or unsaved one at end) and this is odd too.. maybe it will help you to reproduce
* Create new file > add content > but do not save
* Open File 
* Open another file 
* Last one is selected > close all except current > don't save
* Only the second file is kept in the editor! the one that should be kept is close.

If unsaved file is positioned at the end, it works. 

Possibly related to some sort of index of filename after the unsaved one ? 

> Out of curiosity, does this work if you have multiple unsaved documents? (In this case, we show a different type of dialog that might make a difference here.)

@kevinushey it closes correctly if I have several files open no matter the configuration I try
* File1> unsaved File > File2 > Unsaved File > File3 
* File1> unsaved File > Unsaved File > File3 

Hope it helps reproduce. Tell me if I could do anything else.

**Comment by melissa-barca** [comment]
Thank you @cderv! This was a big help, I can now reproduce consistently even on macOS.

**Comment by melissa-barca** [comment]
I'm also seeing strange behavior with this command and multiple source columns. Adding this to 1.4 as it's a regression and shouldn't require a risky fix.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1013
