### ISSUE TITLE
JSON does not appear for text file format choices in scrolling menu

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#8296]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1002
    OS Version      : WINDOWS 10
    R Version       : 4.0.2

### Steps to reproduce the problem

* Open a new text file 
* You can't choose JSON as a highlighting format in the menu bottom right of source pane
* Save it with `.json` extension, and the JSON choice will appear

### Describe the problem in detail

We can't choose JSON highlighting for file that are JSON format but without json extension (like [`.theme` file for Pandoc](https://pandoc.org/MANUAL.html#option--highlight-style))

![json-file](https://user-images.githubusercontent.com/6791940/98232574-197de500-1f5e-11eb-8cc4-07bf4b29a898.gif)

### Describe the behavior you expected

JSON should be in the choice list with other format like YAML or XML as it already exists but not appear by default.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1013
