### ISSUE TITLE
Visual editor does not scroll to search matches inside R code chunks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8298]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1001

### Steps to reproduce the problem

1. Create a new R Notebook
2. Switch the editor into visual mode
3. Add a new R code chunk at the bottom
4. Paste or enter enough lines of R code into the chunk that the chunk's height exceeds that of the source editor (e.g. you could paste in the contents of https://github.com/rstudio/rstudio/blob/9b7772e3d61e2bc159cf7547eafd53126a4476ce/src/cpp/session/modules/SessionTests.R)
5. Scroll the visual editor to the top
6. Search for a string that exists inside the R code chunk (e.g., `shinyDir` if you pasted the above)

### Describe the problem in detail

The editor scrolls to the visual chunk that contains the matches, but it does not scroll down far enough to show the matches themselves. It looks like the search doesn't work. 

![image](https://user-images.githubusercontent.com/470418/98280178-dcaaf180-1f4f-11eb-86e8-448c7dfc89c7.png)

### Describe the behavior you expected

The editor should scroll all the way to the search match, like this.

![image](https://user-images.githubusercontent.com/470418/98280231-f3514880-1f4f-11eb-855d-9a73752e568d.png)

**Comment by jmcphers** [comment]
This is the crux of the problem:

https://github.com/rstudio/rstudio/blob/9b7772e3d61e2bc159cf7547eafd53126a4476ce/src/gwt/panmirror/src/editor/src/api/scroll.ts#L42-L50

The `resultNode` here is just the top level node that contains the result. Scrolling to that node works pretty well if the node is small, but not if the node is large. That means that this is an issue for _any_ large node, including paragraphs: if you have a long paragraph that exceeds the height of the editing surface, you'll observe the same issue.

I think that the right fix for this is going to be more involved than we'd like: we probably need to wait to scroll until the find markers have actually been rendered. Once the find markers are actually in the DOM we can reliably find the offset of the selected one.

**Comment by kevinushey** [comment]
Could we reliably detect those mutations via a short-lived MutationObserver or something similar?

**Comment by jmcphers** [comment]
I think so.

**Comment by jjallaire** [comment]
Another approach might be to put scrollInfoView events from the find module into a holding area or queue of some kind, and then wait for the `LayoutEvent` to fire (which should reflect all DOM changes from the last transaction): https://github.com/rstudio/rstudio/blob/9b7772e3d61e2bc159cf7547eafd53126a4476ce/src/gwt/panmirror/src/editor/src/editor/editor.ts#L808 before actually performing the scroll (and in that case targeting the selected item)

**Comment by jjallaire** [comment]
I think I have a simpler fix for this, stay tuned.

**Comment by jjallaire** [comment]
It turns out that the find markers are already rendered at this point (the `update()` call on the plugin is made after the entire DOM has been rendered). So it's simply a matter of looking for `.pm-selected-text` and targeting that (with a position based fallback if that fails).

@jmcphers I'm not sure if this addresses the originally reported Ace auto-scroll issue b/c I'm less familiar w/ how it handles selection/find decorations. This does definitely address the issue for long paragraphs (for both find and interactive spellchecking)

**Comment by ntluong95** [comment]
@jmcphers could you please instruct me how to display the arrow in the script like in your picture?

**Comment by jmcphers** [comment]
@ntluong95 It is a feature of the font I'm using. Install a font like FiraCode or JetBrains Mono and then tell RStudio to use it in  Options -> Appearance. :-) https://github.com/tonsky/FiraCode

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
