### ISSUE TITLE
Cmd + Up / Cmd + Down doesn't scroll cursor into view

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8300]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

Create an R Markdown document, then switch to visual mode, and add a large code chunk. Click on the code chunk to send focus, and then use Cmd + Up and Cmd + Down to scroll within the editor.

### Describe the problem in detail

The cursor is moved as appropriate, but the cursor is not scrolled into view. (It seems that the view is instead placed where the cursor originally was)

### Describe the behavior you expected

The cursor should be scrolled into view.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It looks like PageUp + PageDown have similar issues.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
