### ISSUE TITLE
Slide preview cursor synchronization does not work in visual mode

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8301]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.999

### Steps to reproduce the problem

1. Create a new ioslides presentation (File -> New -> R Markdown -> Presentation -> ioslides)
2. Put the editor in source mode 
3. Save and knit the presentation
4. Place the cursor at the end of the line reading `Slide with Bullets`
5. Knit the presentation again. Observe that the preview window shows the slide containing the cursor (*Slide with Bullets*, expected)
6. Switch the editor to visual mode
7. Place the cursor at the end of the line reading `Slide with R Output`
8. Knit the presentation again. 

### Describe the problem in detail

The preview that appears after knitting continues to show the slide _Slide with Bullets_.

### Describe the behavior you expected

The preview should show the slide where the cursor is located -- in this case, _Slide with R Output_.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
