### ISSUE TITLE
citation completions dissapear after a couple of seconds

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8314]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1013
    OS Version      : OS X
    R Version       : 4.0.3

### Steps to reproduce the problem

From @hadley: In the ggplot2 book (http://github.com/hadley/ggplot2-book), if I type @murr to get the citation autocomplete and wait a second or two, the autocomplete box disappears (which is frustrating because I'm trying to figure out which citation I want)

### Describe the behavior you expected

Completions don't dissapear.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
@dragonstyle LMK if this is something we should fix before the citation post goes live on Monday.

**Comment by dragonstyle** [comment]
Will re-open if we can reproduce the issue. Current best guess was something 'stealing' focus.

**Comment by kfeinauer** [comment]
Also not able to reproduce on 1.4.1073. Will mark as verified.
