### ISSUE TITLE
adapt to updated graphics device

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8316]
https://github.com/wch/r-source/commit/0dc3cb95b319a3c473094da2272b63ef3bb8e0a6

Fortunately doesn't change struct layout so shouldn't require any changes for 1.4.

**Comment by kevinushey** [comment]
Implemented in https://github.com/rstudio/rstudio/issues/8383.

**Comment by gtritchie** [comment]
Verified; in Windows Desktop v1.4.1029 when I tried to plot with R 4.1 (devel) installed an error was shown in console and the plot was shown in a separate window (not the Plots pane).

With 1.4.1067, the plot showed in the pane, as expected.
