### ISSUE TITLE
rstudioapi::hasConsoleColor() reports FALSE even when available

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8323]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

Compare the output of `rstudioapi::hasConsoleColor()` with RStudio's actual ability to render ANSI colors.

### Describe the problem in detail

RStudio reports that ANSI colors are not supported, even though they are.

<img width="293" alt="Screen Shot 2020-11-09 at 1 38 44 PM" src="https://user-images.githubusercontent.com/1976582/98599512-e787be00-2290-11eb-9a6b-28fc17adf07c.png">

### Describe the behavior you expected

`rstudioapi::hasConsoleColor()` should report `TRUE` if ANSI color codes are supported.

### Notes

Issue appears to be a change in the preference format that's not handled in the associated R API?

<img width="401" alt="Screen Shot 2020-11-09 at 1 40 28 PM" src="https://user-images.githubusercontent.com/1976582/98599619-23228800-2291-11eb-84ef-af65e3a3e77d.png">

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1016
