### ISSUE TITLE
RStudio opens to blank window, Manjaro Linux

### ISSUE THREAD

**Issue by mcsimenc** [rstudio/rstudio#8327]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093-1
    OS Version      : Manjaro Linux 20.2, full system update 11/9/20, reinstalled rstudio-desktop
    R Version       : 4.0.3

### Steps to reproduce the problem
Open RStudio

### Describe the problem in detail
RStudio opens a window that is blank except for the menu bar and the toolbar with icons for new document, open document, etc. I can interact with the menus, for example by selecting File->New File->R Script which appears to do nothing.
### Describe the behavior you expected
RStudio opens and is fully functional

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you have better luck with the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio?

**Comment by mcsimenc** [comment]
Hi Kevin, I've been unable to install the preview to Manjaro Linux where I get the errors:
```
:: unable to satisfy dependency 'libssl1.0.0' required by rstudio
:: unable to satisfy dependency 'libssl1.0.2' required by rstudio
```
I have openssl v1.1.1h installed, and when I try to install openssl v1.0.2 I still don't get libssl1.0.2.

**Comment by jmcphers** [comment]
We do not officially support Manjaro Linux. Which installer did you use? You probably just need to download a build of RStudio linked against libssl1.1 (try Redhat 8 for an RPM or Ubuntu Bionic for a DEB)

**Comment by mcsimenc** [comment]
Thanks Jonathan. I used the Debian installer so I'll try a different installer.

**Comment by ronblum** [comment]
@mcsimenc Have you had any luck?

**Comment by mcsimenc** [comment]
Hey Ron, I previously had Manjaro installed with the XFCE desktop environment. I reinstalled Manjaro with Gnome and I haven't had this problem since.
