### ISSUE TITLE
Unexpected scroll jump and selection in visual mode with large code chunks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8332]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1013

### Steps to reproduce the problem

1. Create a new R notebook
2. Switch to visual editing mode
3. Create a new R code chunk at the end of the notebook
4. Paste a large chunk of R code into the chunk, e.g. https://raw.githubusercontent.com/rstudio/rstudio/master/src/cpp/session/modules/SessionTests.R
5. Place the cursor on the last line of the chunk
6. Scroll the editor up until the cursor is no longer visible
7. Click anywhere in the top 1/2 of the visual editor inside the code chunk

### Describe the problem in detail

The scroll position jumps unexpectedly, and a section of text is selected.

![image](https://user-images.githubusercontent.com/470418/98709778-ae565900-2337-11eb-8f0d-db81d2272db3.png)

### Describe the behavior you expected

The cursor should move to the location you clicked on. No scrolling should occur, and no selection should be made.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
