### ISSUE TITLE
Duplicate Bibliography Entry using Pubmed, Datacite, Crossref, and DOI

### ISSUE THREAD

**Issue by dragonstyle** [rstudio/rstudio#8335]
When searching for a reference in a third party database (Pubmed, Datacite, Crossref, and DOI), RStudio may insert a duplicate entry (with a unique citekey) into the user's bibliography. It is possible to detect duplicate entries using a DOI, so it would be nice if we would just see the existing entry and use that CiteKey.

See:
https://community.rstudio.com/t/mechanism-to-check-for-duplicate-citations-while-adding-citations-in-the-preview-releases/87335

### System details

    RStudio Edition : All
    RStudio Version : All 
    OS Version      :  All
    R Version       : 

### Steps to reproduce the problem
1) Insert from DOI using:
10.5281/ZENODO.4266706

2) Ensure that this entry is present in bibliography

3) Insert Citation, Search Datacite, use '10.5281/ZENODO.4266706' as search term.

4) Select the first entry and insert it.

### Describe the problem in detail
A second entry with a citekey @Bermudez2020a is created.

### Describe the behavior you expected
The entry with citekey @Bermudez2020 is used.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
I just confirmed that this should be fixed in existing daily builds (was fixed previously, so no new commit).

**Comment by astayleraz** [comment]
Verified in version 2021-07.0.285-2 this is no longer showing duplicate entries and added a test for this case. Closing issue.
