### ISSUE TITLE
Floating images leak into code chunks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8343]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1013

### Steps to reproduce the problem

1. Create a new R Notebook.
2. Switch to visual editing mode.
3. Place the cursor just above the code chunk
4. Insert an image, e.g., https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
5. Click the image, then click the ellipsis (`...`) to open the image info dialog
6. Click the Attributes tab
7. In the CSS Styles textbox, enter `float: right;`
8. Click OK

### Describe the problem in detail

The layout is compromised; the image floats *inside* the chunk and behind it. 

![image](https://user-images.githubusercontent.com/470418/98750161-12960e80-2372-11eb-9f28-86b6e720ddd5.png)

### Describe the behavior you expected

The chunk and image should not overlap.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1027
