### ISSUE TITLE
~ home directory - workspace reload issue

### ISSUE THREAD

**Issue by alanpaulkwan** [rstudio/rstudio#8350]
Hi, I don't know if this is a duplicate bug. 
![image](https://user-images.githubusercontent.com/8321252/98884035-2a80a600-24ca-11eb-92b7-67d061cdc90f.png)

Ubuntu 20 / Rstudio server / R 3.6.3

Basically, it doesn't matter how small or large my workspace is (if my suspended-session-data is 1mb), this error recurs consistently and I have to delete my session entirely - then I am OK. 

FWIW, I do use some somewhat exotic packages like arrow. I only mention this package because before I upgraded, arrow 0.6 (something archaic, now we're on 2.0) would crash rstudio but not R. Odd. Or that might be a red herring. 

Any ideas? Hopefully this is a duplicate of a bug being solved or it is easily correctable user stupidity. Thanks!

**Comment by kevinushey** [comment]
Next time this occurs, can you share your `suspended-session-data` so we can try and reproduce locally?

**Comment by alanpaulkwan** [comment]
https://www.dropbox.com/sh/nbyac3a30u633z1/AAB8tWEwwoOpypOmu837d3pNa?dl=0

Here's a guess. 
![image](https://user-images.githubusercontent.com/8321252/99042999-a82adb80-25c8-11eb-91f9-cfd0719f9f5f.png)

viewer-cache has 500. Is it crashing because of the permissions there?
