### ISSUE TITLE
Dancing console

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#8351]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1022
    OS Version      : Windows 10 Enterprise 64-bit
    R Version       : 4.0.3 64-bit

### Steps to reproduce the problem

This is really strange. I was reading an Excel xlsx file which had 17 columns using `read_xlsx` from the `readr` package then this happened when viewing the `dat` output

``` r

  dat <- read_xlsx(file_name,
                   skip = 4,
                   sheet = "data",
                   col_names = FALSE)
  dat

```

![acSHs0qLnp](https://user-images.githubusercontent.com/6590141/98902843-4e60cf00-246b-11eb-9615-a7738bc724a8.gif)

If I ran the next lines to get different output, e.g., `summary(dat)` then the console stopped jumping.
But if I scrolled backup to where the `dat` console output was, the console was in party mode again :)

### Describe the problem in detail

See above

### Describe the behavior you expected

No data frame output jumping around in the console

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Any chance you can provide a reproducible example?

**Comment by tungmilan** [comment]
@kevinushey: I can't share the data but I'll see if I can modify it before posting. I would be more comfortable to send over email than posting on GitHub. Would it work for you guys? Thanks!

**Comment by kevinushey** [comment]
@tungmilan: I was more hoping that (if you're able to spare the time) you could generate a sample dataset that exhibits the same issue. My hope is that the issue could be reproduced with a similarly-formatted data frame made up of random data.
