### ISSUE TITLE
Can't open same file in different source panes

### ISSUE THREAD

**Issue by paulsharpeY** [rstudio/rstudio#8354]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1013
    OS Version      :  Ubuntu 18.04.4 LTS
    R Version       :  3.6.3 (2020-02-29) -- "Holding the Windsock"

### Steps to reproduce the problem

Add source pane and select file already open in existing source pane.

### Describe the problem in detail

File not opened in new source pane.

Filed as a bug rather than a feature request as I think users would expect to be allowed to simultaneously see portions of the same file. It's a feature in most source editors as it provides support for editing large files.

### Describe the behavior you expected

Same file visible in both source panes.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Thank you for the feedback! This is something we'd like to include in a future version of RStudio, and we have an issue open for it here: #2129. I'm going to close this one, but you can upvote the original issue as we take that number into consideration when planning releases.
