### ISSUE TITLE
Warnings about App Defaults being reset after installing on Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8358]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3, 1.4
    OS Version      : Windows-10 2004
    R Version       : 4.0.3

### Steps to reproduce the problem
- on a clean Windows-10 machine, install R 4.0.3 then RStudio desktop
- start RStudio

### Describe the problem in detail
- after a few seconds get some Windows notification about "An app default was reset" including "An app caused a problem with the default app setting for .pdf files, so it was reset to Microsoft Edge."

![screenshot of Windows-10 notifications](https://user-images.githubusercontent.com/10569626/98986275-8a327d80-24d9-11eb-9663-3e303b246d42.png)

### Describe the behavior you expected
- no such notifications

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you see this every time RStudio is launched, or only on the first launch after install?

**Comment by gtritchie** [comment]
Already reset the VM, but 95% sure it was only first launch after install. Don't think we change file associations except via setup. So not a serious issue, but mildly weird.
