### ISSUE TITLE
Highlighted selection background color changes when cursor blinks

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#8360]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.4.1016
    OS Version      : macOS Catalina 10.15.5
    R Version       : 4.0.3

### Steps to reproduce the problem

When text is selected in the editor, the highlight color blinks along with the color. With the colors I'm using, the change is pretty subtle.

In this screencap, it changes from a slightly more purple to a slightly more blue color.

![2020-11-12 15 40 15](https://user-images.githubusercontent.com/86978/98999709-d68fb480-24fd-11eb-903e-18918a43d58a.gif)

**Comment by ronblum** [comment]
@wch What theme are you using? I can't reproduce it, but it's possible the change is too subtle for me to recognize in them—I can see it in your screen capture.

**Comment by wch** [comment]
I'm using the default Textmate theme. Oddly enough, it doesn't seem to be happening when I try it now. Feel free to close this issue.

**Comment by ronblum** [comment]
OK! Will do. Though I'll keep an eye out for it.
