### ISSUE TITLE
Support running RStudio Desktop on ARM Macs via Rosetta2

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8362]
Currently untested, but expectation is current x64 builds of RStudio will NOT run on the new ARM Macs via Rosetta2 due to known issues in Chromium/QtWebEngine (https://bugreports.qt.io/browse/QTBUG-86405).

**Comment by mikebessuille** [comment]
putting this in 1.5 as we will need to have support very quickly via the emulator.

**Comment by mikebessuille** [comment]
Was mistakenly moved out of 1.5 as part of a bulk move.  This needs to be supported (tested) in 1.5.

**Comment by kevinushey** [comment]
Looks like our fears here were unfounded; RStudio does indeed run without issue on arm64 (including using native arm64 binaries with 1.4-JR)
