### ISSUE TITLE
Pane Profiles

### ISSUE THREAD

**Issue by MyKo101** [rstudio/rstudio#8369]
I believe it would be a useful feature for many to be able to define and select a "Pane Profile" depending on a user's current situation.

My personal use-case is that I have my own preference for pane layout (Script on the top left, Console on the bottom right, Env/Files/Plot/etc... top right). However, as I also teach R to beginners, I re-arrange my pane layout before lessons to match (as best I can) the default view when opening RStudio (Script top left, Console bottom left, Files/Plots bottom right, Env/etc... top left).

It would be beneficial during these times to be able to switch from a "Personal" to a "Tutoring" pane profile. I can also imagine users having different pane layouts depending on whether they are writing RMarkdown files vs R Script files.

I cannot foresee a reason why this wouldn't be possible. A further extension might be to tie Pane Profiles in with different .RProj files (although I'm not sure how this would be implementable.

**Comment by ronblum** [comment]
@MyKo101 Thank you for the suggestion! We'll review it as part of our ongoing development of RStudio applications.

**Comment by jmcphers** [comment]
This is currently being tracked in https://github.com/rstudio/rstudio/issues/4276. Appreciate the suggestion!
