### ISSUE TITLE
Packages link in Help pane results in "internal server error"

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8372]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1025
    OS Version      : Ubuntu 20.04.1
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Open Help pane
2. Click on "Packages"

### Describe the problem in detail

The resulting page says, "Internal Server Error". Here's the Console output, the Help pane, and the error when inspecting:

<img width="831" alt="help_packages" src="https://user-images.githubusercontent.com/31009952/99090993-4739de00-259d-11eb-9189-1d755e61de70.png">

### Describe the behavior you expected

To see the Help pane's packages page.

Note: This works in RStudio Desktop on MacOS 11.0.1 and RStudio Server on Ubuntu 20.04.1.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This works for me. I see different output in the console, though:

<img width="251" alt="Screen Shot 2020-11-13 at 2 51 30 PM" src="https://user-images.githubusercontent.com/1976582/99128466-b88a8880-25bf-11eb-9dda-f17d257baa88.png">

@ronblum: can you share the output of:

```
utils:::make.packages.html(temp = TRUE)
```

on your machine? It might also be helpful to see the following:

1. Launch a new IDE session,
2. Run this code in the console: `trace(utils:::make.packages.html, quote(print(ls.str())))`,
3. Open the Help pane,
4. Try and click the Packages link.

I see the following:

<img width="1031" alt="Screen Shot 2020-11-13 at 2 54 37 PM" src="https://user-images.githubusercontent.com/1976582/99128634-28990e80-25c0-11eb-8dc5-423a4da56629.png">

**Comment by ronblum** [comment]
I never get to "done":
<img width="541" alt="utils" src="https://user-images.githubusercontent.com/31009952/99268850-ae50d000-27f3-11eb-8bfa-9adcce8216c7.png">
<img width="591" alt="trace" src="https://user-images.githubusercontent.com/31009952/99268858-b14bc080-27f3-11eb-94cc-fde0cc2c850f.png">

**Comment by kevinushey** [comment]
Do you get any extra output if you use:

```
options(error = rlang::entrace)
utils:::make.packages.html(temp = TRUE)
```

Can you also share how R was installed on your machine? Are you just using the regular `apt-get` installed binary, or something else?

**Comment by mikebessuille** [comment]
can you please also test this in 1.3?  If this is a regression we should fix it.

**Comment by ronblum** [comment]
It turned out that the `here` package was corrupted (@kevinushey's discovery; all I did was type). Once removed and reinstalled, everything worked fine in 1.3.1093 and 1.4.1032, so closing.

**Comment by wjtimmerman** [comment]
In case this helps anyone else, this error can also appear when you're using renv for package management with a synced/cloud folder (e.g., OneDrive in my case) where certain help files in your packages are only available online and you currently don't have your cloud syncing application (again, things like OneDrive) turned on.

**Comment by kevinushey** [comment]
FWIW my recommendation here would be to use `RENV_PATHS_LIBRARY` or `RENV_PATHS_LIBRARY_ROOT` to ensure the `renv` project library is stored outside of your cloud-sync'ed project. This is described a bit more in https://rstudio.github.io/renv/reference/paths.html.

**Comment by blessingalabi** [comment]
Hi @wjtimmerman,
I encountered the same issue and I use one drive, any suggestions on what I can do. I'm not deep with R, I only lightly use it.

**Comment by wtimmerman-fitp** [comment]
@blessingalabi assuming renv is being used and is the issue here, I would suggest right clicking your folder you're working in and choosing "always keep files on this device"  (or whatever the option is). Good luck!
