### ISSUE TITLE
Add Rename File to document tab context menu

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8374]
Once the document tabs have a context menu, it should contain the Rename File command. This will need to be aware of whether the tab contains a file-based entity (e.g. shouldn't be shown for non-document tabs that be displayed in the source region, columns, and satellite windows).

This request was extracted from #1664

**Comment by gtritchie** [comment]
Once this is added, these existing issues will become more prominent and should be fixed in the same release:

- Renaming a file doesn't update tab tooltip #8491
- Renaming a File open in satellite window doesn't update name #8490

**Comment by gtritchie** [comment]
This was implemented in juliet-rose via: #8530

**Comment by astayleraz** [comment]
Verified in Version 1.4.1507-1 and R 3.6.0 that I can right click on tabs and rename saved files.
