### ISSUE TITLE
Reproducible rstudio crash depends on browser and code in the editor

### ISSUE THREAD

**Issue by traversc** [rstudio/rstudio#8377]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1093
    OS Version      :  Centos Linux 7
    R Version       : 4.01

### Steps to reproduce the problem

Here's a gif of the issue, which both myself and another person have been able to 100% reproduce. The gif shows that saving a file crashes with some code but not other code. **~The crash only happens in Chrome and not Firefox~**.

https://imgur.com/a/2RjIm1c

(Not shown in the gif is when I pressed Ctrl-S, which was done twice: before and after changing the code in the editor)

The crash was also tested on more than one server. 

1) Make a new file. 
2) Enter in the code:
```
myfunc <- function() {
    v <- lapply(v, function(x) {
        gsub("\\*$", "", x)
    })
}
```
3) Ctrl-S to save

### Describe the problem in detail

Trying to save particular code using rstudio-server and chrome does not save the file and eventually causes rstudio to crash with error "Unable to establish connection with R session".

Session info:
```
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.1 tools_4.0.1   
```

### Describe the behavior you expected

The file should save. 

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ (no root privileges)] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, I'm not able to reproduce this locally.

**Comment by ronblum** [comment]
Note: marking to reproduce with RStudio Server on CentOS 7/Red Hat 7, as it might be OS specific (not present on Ubuntu, MacOS, or Red Hat 8).
