### ISSUE TITLE
Roxygen documentation editing problems

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#8378]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.4.1016
    OS Version      : macOS Catalina 10.15.5
    R Version       : 4.0.3

### Describe the problem in detail

When editing roxygen documentation, I run into a number of pain points.

* The tab stops for examples are offset by one from where they should be. The content starts at the 3rd position, but the tab stops are at 2, 4, etc. This results in a lot of manual deleting and adding spaces, especially for code examples. Backspace deletes to the 2, 4, etc. tab stops, so I often press backspace then add one more space to get to the third position. (In general, in comments, I don't want backspace to delete to the previous tab stop, because I'm usually writing text.)

```
#' This is some text
#'
#' @examples
#' for (i in 1:10) {
#'   print(i)
#' }
```

* Markdown code chunks get wrapped as text, but they shouldn't be.  For example, this:

```
#' ```
#' 1 + 1
#' ```
```

gets transformed to this by wrapping:

```
#'  ``` 1 + 1 ```
```

* `\describe`, `\itemize`, and `\enumerate` blocks get mangled by wrapping. For example, this:

```
#' \describe{
#'   \item{ABC}{
#'     Description here.
#'   }
#'   \item{XYZ}{
#'     Description here.
#'   }
#' }
```

gets transformed to this:

```
#' \describe{ \item{ABC}{ Description here. } \item{XYZ}{ Description here. } }
```

* `\preformatted{ }` blocks lose their formatting when wrapped.

* Markdown bullet lists lose their structure when wrapped.

**Comment by jennybc** [comment]
Some threads I've been part of that have partial overlap with this:

* Sub-conversation in #2701 about reflowing mangling, e.g., bullet lists in roxygen comments (https://github.com/rstudio/rstudio/issues/2701#issuecomment-384694914)
* Reflowing adding extra lines to roxygen comments #5886

**Comment by hadley** [comment]
Maybe, when markdown mode is on, the IDE could just pass off to pandoc for the reformatting — that would also normalise the markdown formatting, but I think on the whole that would be a feature.

These days, I think it's probably fine to worry less about reformatting Rd formatted text since it's relatively less common, and is likely to require a substantial amount of bespoke code to nicely reformat.

**Comment by romainfrancois** [comment]
The latest build in https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/ have both #12016 and #12012 which should improve the situation. cc @wch @jennybc

**Comment by jonvanausdeln** [comment]
I tried some of the examples in 2022.12.0-daily+260 and seems to behave as expected.

I'm by no means an expert, so I'd appreciate if @wch could take a quick look as well.  I'll close this for now as it seems to address the main issues.
