### ISSUE TITLE
Visual markdown insert citation: bibliography is empty while bibliography files are present

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#8384]
### System details

```
RStudio Edition : Desktop
RStudio Version : 1.4.1029
OS Version : Linux Mint 20 (~Ubuntu 20.04)
R Version : 4.0.3
```

### Steps to reproduce the problem

1. Start with this situation:
    - at least one json/yaml/bib file with references and one Rmd file in a Rstudio project folder (example is given in details)
    - a Zotero installation (with data) is present on the system, for which the profile directory was previously changed through the RStudio global options, by specifiying a local Zotero directory in Global Options -> R Markdown -> Citations (cf. https://github.com/rstudio/rstudio/issues/7867#issuecomment-724157533). _However I don't know whether that switch is necessary to invoke the problem._
2. Either keep Zotero enabled, or reset 'Zotero Library' to 'None' (in Global Options -> R Markdown -> Citations')
3. Open the RStudio project, go to visual mode in the Rmd file, open 'insert citation' and go to 'My sources -> Bibliography'

### Describe the problem in detail

No references are shown under 'Bibliography', even though entries do exist in the bibliography files. See screenshots.

I remember that it did work some time ago (in earlier daily builds, at least before I made a profile switch in 1.4.1010). I noticed the issue after I made the switch to another Zotero profile directory as I described in https://github.com/rstudio/rstudio/issues/7867#issuecomment-724157533 (and as described there, at least in 1.4.1010 I did not see any Zotero profile anymore: up to that point I had never had to select a Zotero data folder). However I cannot be sure that this setting of the data directory (of a second profile) was the trigger for current issue.

Some screenshots:

- with Zotero disabled in the global options:

![Schermafdruk van 2020-11-14 18-27-51](https://user-images.githubusercontent.com/19164640/99153166-2a89cd00-26a7-11eb-934d-a8bdb60ef3ae.png)

- with Zotero enabled in the global options:

![Schermafdruk van 2020-11-14 18-29-35](https://user-images.githubusercontent.com/19164640/99153217-6de43b80-26a7-11eb-88e4-170a7d097357.png)

Below are the project directory contents:

<details><summary><strong>Project directory contents</strong></summary>

```
.
├── hello.Rmd
├── references.bib
├── references.yaml
├── .Rhistory
├── .Rproj.user
│   ├── 574D656F
│   │   ├── bibliography-index
│   │   ├── ctx
│   │   ├── explorer-cache
│   │   ├── pcs
│   │   │   ├── files-pane.pper
│   │   │   ├── source-pane.pper
│   │   │   ├── windowlayoutstate.pper
│   │   │   └── workbench-pane.pper
│   │   ├── presentation
│   │   ├── profiles-cache
│   │   ├── rmd-outputs
│   │   ├── saved_source_markers
│   │   ├── sources
│   │   │   ├── per
│   │   │   │   ├── t
│   │   │   │   └── u
│   │   │   ├── prop
│   │   │   │   ├── 4A035B88
│   │   │   │   ├── 9D791704
│   │   │   │   ├── C2958D18
│   │   │   │   └── INDEX
│   │   │   └── s-7CBB436F
│   │   │       ├── 8DF86AC1
│   │   │       ├── 8DF86AC1-contents
│   │   │       ├── B9BF3A5D
│   │   │       ├── B9BF3A5D-contents
│   │   │       └── lock_file
│   │   ├── tutorial
│   │   ├── unsaved-notebooks
│   │   │   └── 8DF86AC1
│   │   └── viewer-cache
│   └── shared
│       └── notebooks
│           ├── 94269D73-hello
│           │   └── 1
│           │       ├── 574D656F00B90602
│           │       │   └── chunks.json
│           │       ├── 574D656F5F72066F
│           │       │   └── chunks.json
│           │       ├── 574D656F985CFB74
│           │       │   └── chunks.json
│           │       └── s
│           │           └── chunks.json
│           ├── patch-chunk-names
│           └── paths
└── using_rbbt_etc2.Rproj
```
</details>

### Describe the behavior you expected

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
@florisvdh thanks for the detailed write up- really helpful to have all this detail. 

Something more unusual is happening (at least that is my guess based upon your screenshots).  I can see that the dialog is actually presenting a bibliography to be created (defaulting to references.yaml), which means that we couldn't find your bibliography for some reason (hence the offer to create one). 

What does the front matter / yaml look like for the document hello.Rmd look like? Is there any conflicting project configuration that might be pointing to another bibliography that no longer exists?

**Comment by florisvdh** [comment]
@dragonstyle  This is the Rmd frontmatter:

```
---
title: "Hello"
author: "Name"
date: "14-11-2020"
output: html_document
---
```

With that, you indeed found the reason why it says 'create bibliography' in the dialog. So the bibliography key is needed. Changing frontmatter to:

```
---
title: "Hello"
author: "Name"
date: "14-11-2020"
output: html_document
bibliography: [references.yaml, references.bib]
---
```

... solves the 'create bibliography' (now it says 'add to bibliography'), but still the existing references are not shown in Bibliography (shown with Zotero disabled).

![Schermafdruk van 2020-11-16 11-49-37](https://user-images.githubusercontent.com/19164640/99244158-fe369380-2801-11eb-8182-28d64658029f.png)

Also, note that it offers both files (from the frontmatter) in the dropdown to add references to:

![Schermafdruk van 2020-11-16 12-02-40](https://user-images.githubusercontent.com/19164640/99245444-df390100-2803-11eb-99aa-18239ec679e6.png)

You gave a good hint, because by digging further I found the reason why it was blank :smile:. It seems that **multi-file bibliography** is not supported.

When changing `bibliography` key to:

```
bibliography: references.yaml
```

I get:

![Schermafdruk van 2020-11-16 11-52-38](https://user-images.githubusercontent.com/19164640/99244681-b6643c00-2802-11eb-982c-0c93cc1c25a2.png)

Same with the bib file. (Although BTW I saw it gives a _blank_ result again when one record in the bibfile misses a bibtex key - perhaps you may want to make a separate issue of that)

Regarding the bib-file, it's even more odd. One record did miss a bibtex key. When adding it (id 'n2khab'), blank content is solved not only for the `bibliography: references.bib` case but in part also for `bibliography: [references.yaml, references.bib]`, as in both cases shows (only) the **bib** file contents:

![Schermafdruk van 2020-11-16 12-10-09](https://user-images.githubusercontent.com/19164640/99245949-c3822a80-2804-11eb-9f2b-a69a2770cb2e.png)

Both files attached for reference: [references.zip](https://github.com/rstudio/rstudio/files/5545838/references.zip)

Solved? Yes and no. I think multi-file bibliography would best be supported (at this point, I conclude it only shows the bib-file contents - didn't check json), as it is supported by pandoc + R markdown. Support for multi-file bibliography is useful in collaborative, heterogeneous environments. Also, I believe it would fit the dialog setup, which offers the indicated files to append records to (and I've tested that it works for both files, by appending references to each one, from Zotero).

**Comment by dragonstyle** [comment]
This is great detective work- thanks for putting the time into better understanding the issue and documenting it so thoroughly. We did properly support multiple Bibtex bibliography files in the same document, but not json or yaml, and not the mixing of bibliography files of differing types either.

We did make a fix (https://github.com/rstudio/rstudio/commit/24b3701f14b69ecb33634b38111a7be87271c9fb) to address this and should now support:
- Any number of bibliographies of whatever format
- Cross format mixing ok (e.g. `["references.bib", "references.json", "references.yaml"]`)
- Inline references in the document will also be included in completions and dialog

Should make its way to daily builds tomorrow, I believe.

Thanks again!

**Comment by florisvdh** [comment]
Thanks a lot @dragonstyle, I look forward to it. I really hope the great citation feature will become available in source mode as well.

**Comment by dragonstyle** [comment]
I'll chime in with the suggestion for source mode- right now it is tied more closely to the visual editor in terms of implementation, so it would definitely be some work...

**Comment by florisvdh** [comment]
I confirm the multi-format bibliograpy works nicely in 1.4.1038 ! :tada: Thanks!
