### ISSUE TITLE
vim quit-all command (qa, qall) not working

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8388]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : last worked with 1.4.470
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- set editor to vim keybindings
- open several source files, modify some of them but don't save
- with focus on editor, issue: `:qa` or `:qall` command

### Describe the problem in detail
- the current editor tab stays open, but all others close; those with changes are closed without warning, losing changes

### Describe the behavior you expected
- all tabs should close including the current one, after a prompt regarding what to do about unsaved files

If you do `:qa!` or `:qall!`, all tabs close without prompting for or saving modified tabs. This works correctly.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1035
