### ISSUE TITLE
Syntax highlighting not working on Mac OS Big Sur

### ISSUE THREAD

**Issue by ssp3nc3r** [rstudio/rstudio#8392]
Syntax highlighting not working in rstudio on Mac Big Sur, which also affects dark mode themes.

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1029
"Wax Begonia" (a2ec3e61, 2020-11-13) for macOS
    OS Version      : Mac Big Sur
    R Version       : 4.0.3

### Steps to reproduce the problem

Open any code file in Rstudio on Mac Big Sur. 

### Describe the problem in detail

Syntax highlighting not working.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by RLumSK** [comment]
@ssp3nc3r I double-checked, but it looks good to me, the syntax highlight works as expected. My system:

```
RStudio (Desktop):  1.4.1029 ("Wax Begonia" (a2ec3e61, 2020-11-13) for macOS)
macOS: 11.0.1 (Big Sur)
```

**Comment by ssp3nc3r** [comment]
Ok, I re-checked and it seems that it's also due to the choice of fonts. I've been using Source Code Pro forever and it worked fine for syntax highlight in RStudio until I upgraded to Big Sur. But changing to another font lets syntax work again.

**Comment by kevinushey** [comment]
Works fine for me with Source Code Pro, so there must be something else going on.

**Comment by ronblum** [comment]
@ssp3nc3r Does it only work in other fonts, or does it work in Source Code Pro if you switch to something else, then back to Source Code Pro?

**Comment by ssp3nc3r** [comment]
Hmmm. No, Switching away and back doesn't fix it.

But I'm also seeing other oddities. Like in Options | Appearance | Editor Theme, when I click once on any theme, the preview window does not show syntax highlighting, and the cancel and apply buttons get blacked out. If I click on the same theme a second time, the preview does show syntax highlighting, but the two buttons do not become visual again. Here's an example where I click once on the default theme (notice no syntax highlighting in preview):

<img width="587" alt="image" src="https://user-images.githubusercontent.com/19272141/99305889-69905d80-2822-11eb-8917-841d27a302cd.png">

**Comment by mmstuiverebp** [comment]
I can confirm, I have the same issue with Source Code Pro, using RStudio  1.3.1093 "Apricot Nasturtium" on Big Sur. It seems all other fonts work fine. Deinstalled and reinstalled the font, to no avail.

**Comment by elgarteo** [comment]
I had the same issue with Source Code Pro in RStudio 1.3.1093. Reinstalled a freshly downloaded copy of the font and the problem is gone. Perhaps it is to do with the older versions of the font?

**Comment by RLumSK** [comment]
I became curious. While I did not have this problem as written above, I never had this particular font installed. So I tried again today after downloading and installing the font for the first time: No problem, the syntax highlight works just fine. 

```
RStudio (Desktop):  1.4.1032 ("Wax Begonia" (33d8cb27, 2020-11-15) for macOS)
macOS: 11.0.1 (Big Sur)
```

**Comment by punchcutter** [comment]
For Source Code Pro (and some other fonts) it's because of the SVG table. Something changed in Big Sur where the SVG table interferes with syntax highlighting. The [latest release](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro%2F1.052R-it%2F1.012R-VAR) from last week has this table removed so it should work.

**Comment by mmstuiverebp** [comment]
@punchcutter This solved the problem. Thank you very much!

**Comment by ssp3nc3r** [comment]
Yes, the modified font does work. The blacked-out buttons are still a problem, though. Should it be re-posted in a separate issue?
