### ISSUE TITLE
Sort installed packages by (update) date and other

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#8394]
Hi,

I would like having the option of sorting packages in the Packages pane by updating date. It would be great if further, we could sort them by (first) installation date, if it was possible. 

And, as an extra, since we can see 4 columns in that pane ("load marks", Name, Description and Version), why not having the chance of sorting by them? (for "load marks", this would be the issue #2435).

I have not found any other issue with the main FR.

Thank you!

PS: I use often https://cran.r-project.org/web/packages/available_packages_by_date.html, but I have to look which of all CRAN packages have I installed, and further, one could not having all their packages updated, so the order would be different.

**Comment by ronblum** [comment]
@iago-pssjd Thank you for raising the issue! I'll mark it as an enhancement to consider as we continue development of RStudio. And I'm glad everything is otherwise working for you!
