### ISSUE TITLE
Display total number of errors in source editor

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#8398]
Hello,

 The source editor displays crosses inside a red square in front of the lines where it detects an error, and that is nice. It would be even more nice if the total number of errors were displayed somewhere (as in VS Code). Because when the script is long we can easily miss a spotted error.

**Comment by ronblum** [comment]
@stla Thank you for the suggestion! We'll review it as we continue development of the RStudio IDE.

Note: I'm marking this
