### ISSUE TITLE
keyboard shortcut for adding source column not working on Mac desktop

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8401]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1033
    OS Version      : macOS 11.0.1, also repros on Catalina 10.15.7
    R Version       : 3.6.1

### Steps to reproduce the problem
- start desktop IDE on macOS
- <kbd>Ctrl+F7</kbd> to add a source column (as seen under View / Panes / Add Source Column)

### Describe the problem in detail
- nothing happens

### Describe the behavior you expected
- source column should be added (up the maximum of 3)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
I'm inclined to want to fix this for 1.4 given that source columns is a brand new feature

**Comment by gtritchie** [comment]
Looks like Ctrl+F-key is generally reserved for various accessibility shortcuts on more recent macOS's.

![screenshot of keyboard shortcut preferences on macOS](https://user-images.githubusercontent.com/10569626/99310906-920f5c00-2810-11eb-8b2b-4b5b2fbd1c7b.png)

**Comment by adamconroy** [comment]
verified in build https://github.com/rstudio/rstudio/commit/4395ed8316977a96cdcbf8c26f13837b24c7e6f5
