### ISSUE TITLE
Installation on Red Hat 7 fails due to dependency on a PostgreSQL package

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8403]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1034
    OS Version      : Red Hat 7
    R Version       : 3.6.3

### Steps to reproduce the problem

Install RStudio 1.4 on Red Hat 7.

### Describe the problem in detail

The installation fails because it's dependent on a ProgreSQL library:
> --> Finished Dependency Resolution
Error: Package: rstudio-server-1.4.1034_1-1.x86_64 (/rstudio-server-rhel-pro-1.4.1034-1-x86_64)
           Requires: postgresql-libs
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

### Describe the behavior you expected

Installation succeeds on its own.

The solution is to install the PostgreSQL libraries from https://yum.postgresql.org/13/redhat/rhel-7-x86_64/repoview/postgresql13-libs.html 

```
yum install https://yum.postgresql.org/13/redhat/rhel-7-x86_64/postgresql13-libs-13.1-1PGDG.rhel7.x86_64.rpm
```

Perhaps this is expected, in which case this is something worth documenting.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This seems to work for me: I get prompted to install `postgresql-libs` after trying to install RStudio Server.

```
kevin@centos-7:~/Downloads
$ sudo yum install rstudio-server-rhel-1.4.1036-x86_64.rpm
Loaded plugins: fastestmirror, langpacks
Examining rstudio-server-rhel-1.4.1036-x86_64.rpm: rstudio-server-1.4.1036-1.x86_64
Marking rstudio-server-rhel-1.4.1036-x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package rstudio-server.x86_64 0:1.4.1036-1 will be installed
--> Processing Dependency: postgresql-libs for package: rstudio-server-1.4.1036-1.x86_64
Loading mirror speeds from cached hostfile
 * base: centos.s.uw.edu
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirrors.xtom.com
 * updates: mirror.centos.lax1.serverforge.org
--> Running transaction check
---> Package postgresql-libs.x86_64 0:9.2.24-4.el7_8 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================
 Package              Arch        Version                Repository                                 Size
=========================================================================================================
Installing:
 rstudio-server       x86_64      1.4.1036-1             /rstudio-server-rhel-1.4.1036-x86_64      515 M
Installing for dependencies:
 postgresql-libs      x86_64      9.2.24-4.el7_8         base                                      234 k

Transaction Summary
=========================================================================================================
Install  1 Package (+1 Dependent package)

Total size: 516 M
Total download size: 234 k
Installed size: 516 M
Is this ok [y/d/N]: 
```

**Comment by kevinushey** [comment]
(This is on CentOS 7 rather than Redhat 7, but hopefully they would be the same here?)

**Comment by ronblum** [comment]
Interesting—this works for me on CentOS 7, too. I'll spin up another instance of Red Hat 7 to see if I can reproduce it on a pristine Red Hat 7 environment.

**Comment by kevinushey** [comment]
FWIW:

```
$ yum info postgresql-libs
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.s.uw.edu
 * epel: mirrors.kernel.org
 * extras: mirror.sjc02.svwh.net
 * updates: mirrors.unifiedlayer.com
Installed Packages
Name        : postgresql-libs
Arch        : x86_64
Version     : 9.2.24
Release     : 4.el7_8
Size        : 667 k
Repo        : installed
From repo   : base
Summary     : The shared libraries required for any PostgreSQL clients
URL         : http://www.postgresql.org/
License     : PostgreSQL
Description : The postgresql-libs package provides the essential shared
            : libraries for any PostgreSQL client program or interface. You will
            : need to install this package to use any other PostgreSQL package
            : or any clients that need to connect to a PostgreSQL server.

Available Packages
Name        : postgresql-libs
Arch        : i686
Version     : 9.2.24
Release     : 4.el7_8
Size        : 234 k
Repo        : base/7/x86_64
Summary     : The shared libraries required for any PostgreSQL clients
URL         : http://www.postgresql.org/
License     : PostgreSQL
Description : The postgresql-libs package provides the essential shared
            : libraries for any PostgreSQL client program or interface. You will
            : need to install this package to use any other PostgreSQL package
            : or any clients that need to connect to a PostgreSQL server.
```

So this package _should_ be available from the base repository and so available by default. In theory.

**Comment by ronblum** [comment]
@kevinushey Could it be because my Red Hat repository subscription expired?

**Comment by kevinushey** [comment]
That's possible! Does `yum upgrade` run successfully or warn about anything like that?

**Comment by ronblum** [comment]
I just had to update my subscription—all set!
