### ISSUE TITLE
"Profile selected lines" gets confused by trailing comments

### ISSUE THREAD

**Issue by lionel-** [rstudio/rstudio#8407]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1032
    OS Version      : macOS 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

- Input this in a file:

    ```r
    profvis::pause(1) # ends in a comment
    ```

- Place cursor on the line and click on Profile / Profile selected lines(s)

Originally reported in rstudio/profvis#88.

### Describe the problem in detail

RStudio evaluates this in the console:

```r
profvis::profvis({profvis::pause(1) # ends in a comment})
```

The comment causes incomplete input.

### Describe the behavior you expected

RStudio should strip comments from the code to evaluate:

```r
profvis::profvis({ profvis::pause(1) })
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Fixed in 1.4-JR via https://github.com/rstudio/rstudio/pull/8412.
