### ISSUE TITLE
RStudio crashes when file path to a project contains umlauts

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/rstudio#8408]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.993
    OS Version      : Windows 10 latest
    R Version       : 4.0.3

### Steps to reproduce the problem

Attempt to create a project from RStudio where either the project name itself or the path to the project folder contains an umlaut  like ä,ö,ü)

### Describe the problem in detail

RStudio crashes with the following log message:

`]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::r::exec::`anonymous-namespace'::evaluateExpressionsUnsafe(struct SEXPREC *,struct SEXPREC *,struct SEXPREC **,class rstudio::r::sexp::Protect *,enum rstudio::r::exec::`anonymous-namespace'::EvalType) src/cpp/r/RExec.cpp:186; LOGGED FROM: int __cdecl rstudio::r::session::RReadConsole(const char *,char *,int,int) src/cpp/r/session/RStdCallbacks.cpp:297
17 Nov 2020 12:28:24 [rsession-Shadow] ERROR r error 4 (R code execution error) [errormsg: Error in dir.exists(x) : file name conversion problem -- name too long?
]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::r::exec::`anonymous-namespace'::evaluateExpressionsUnsafe(struct SEXPREC *,struct SEXPREC *,struct SEXPREC **,class rstudio::r::sexp::Protect *,enum rstudio::r::exec::`anonymous-namespace'::EvalType) src/cpp/r/RExec.cpp:186; LOGGED FROM: int __cdecl rstudio::r::session::RReadConsole(const char *,char *,int,int) src/cpp/r/session/RStdCallbacks.cpp:297`

I tested this on Ubuntu as well and the problem appears only on Windows. It also appears on the non-preview version of RStudio. Sometimes the problem shows in a more subtle way: It appears to work but tibbles/dataframes can't be displayed in Rmd documents. I believe this is because in order for this to happen, a temporary file has to be created, which fails du to the umlauts.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5553479/diagnostics-report.txt)

### Describe the behavior you expected

RStudio opens the project

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This should be already be fixed in the latest [preview release](https://www.rstudio.com/products/rstudio/download/preview/) -- can you please upgrade and let us know if you're still having problems?

**Comment by jmbuhr** [comment]
Almost. RStudio no longer crashes, but certain chunk output like dataframes or tibbles can't be displayed in Rmd files. I believe this is because a temporary file is created in order to do that. I originally attributed this issue to OneNote, but now it is definetly the umlauts. With

```{r}
palmerpenguins::penguins
```
the following error appears:

```
Error in tempfile(pattern = "_rs_rdf_", tmpdir = outputFolder, fileext = ".rdf") : unable to translate 'C:/Users/Shadow/Desktop/<fc>/.Rproj.user/shared/notebooks/473E1CBF-test/1/s/cpmebfks80q36_t' to native encoding
```

This is in a fresh project with the name "ü", which appears to be translated to "<fc>", on a fresh install of RStudio.
My students had  the issue of non-appearing output already in the stable version, but only the preview version actually shows the error message.

**Comment by kevinushey** [comment]
This is due to a change in the newest versions of R. I can reproduce the error in R 4.0.3; however, there is no error (although the path is wrong) in R 3.6.3.

```
> dir <- paste(getwd(), "鬼", sep = "/")
> tempfile(pattern = "file-", tmpdir = dir, fileext = ".test")
Error in tempfile(pattern = "file-", tmpdir = dir, fileext = ".test") : 
  unable to translate 'C:/Users/kevinushey/scratch/borg/<U+9B3C>' to native encoding
```

For now, I'd recommend just working in a path without any special characters.
