### ISSUE TITLE
Visual editor cursor invisible for dark theme

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#8409]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1032
    OS Version      : Windows10
    R Version       : 4.0.3

### Steps to reproduce the problem

- Select a dark theme for RStudio
- Create a new .Rmd file
- Switch to visual editing
- Click anywhere in the normal text
- The clicked location is invisible

### Describe the problem in detail

The screenshot shows the situation after clicking between the k and d in Markdown, in the header.     
I used the ambiance theme, but testing with some other dark themes gave the same result.

![image](https://user-images.githubusercontent.com/28725410/99403844-36fe6780-28eb-11eb-9305-1b7a89b4f261.png)

Despite the clicked location being invisible the correct location is selected as can be confirmed by inserting some text.    
Also clicking in a code chuck, clearly shows the position.

I did notice some resemblance to #2685, but I think it is actually a different issue.

### Describe the behavior you expected

The clicked location visible.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For context, I am able to reproduce when using the Ambiance editor theme. (FWIW I haven't seen this issue with Tomorrow Night Bright)

**Comment by kevinushey** [comment]
These appear to be the effected editor themes:

- Ambiance
- Chaos
- Gob

**Comment by kevinushey** [comment]
We extract the Ace cursor color here:

https://github.com/rstudio/rstudio/blob/060d9d66148c63f998d7d8cbf60abe97dd846309/src/gwt/src/org/rstudio/studio/client/panmirror/theme/PanmirrorThemeCreator.java#L40

But some editor themes (e.g. Ambiance) color the cursor using only a border, for whatever reason:

https://github.com/rstudio/rstudio/blob/060d9d66148c63f998d7d8cbf60abe97dd846309/src/cpp/session/resources/themes/ambiance.rstheme#L54-L56

**Comment by jmcphers** [comment]
@kevinushey Do you want to take a crack at fixing this or would you like me to take it?

**Comment by kevinushey** [comment]
I'll take a look!

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1043.
