### ISSUE TITLE
"max print" equivalent for rmarkdown inline chunk output

### ISSUE THREAD

**Issue by naikymen** [rstudio/rstudio#8410]
RStudio hangs or becomes unbearably slow when printing the list of a split dataframe (many "pages", see pic below), but not when printing the original dataframe (one "page").

It would make sense that an equivalent to R's base option "max.print" is also available and enabled by default on rmarkdown's inline chunk output (for pages particularly).

I file this as a feature request, even though I consider it a bug.

![image](https://user-images.githubusercontent.com/3259326/99405755-dca1de80-28cb-11eb-9a72-440d0130fec9.png)

A question though: ¿is anyone else's RStudio hanging while printing long text output from chunks inline? perhaps the annoyingness of long inline chunk outputs is actually related (since printing the list to console also hangs RStudio).

**Comment by ronblum** [comment]
@naikymen Thank you for raising this! I'll mark it as a bug for the moment, though we might switch this over to the enhancement queue.

**Comment by ronblum** [comment]
@naikymen Also, can you provide the environment you're working with?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by naikymen** [comment]
Hello @ronblum, thank you!

Here are my details:

```
RStudio Edition : Desktop
RStudio Version : 1.3.1073
OS Version      : Arch Linux (x86_64 Linux 5.4.77-1-lts; last -Syu'd yesterday)
R Version       : 4.03
```
