### ISSUE TITLE
Pylab plots do not show in Plots Pane

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#8414]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1038
    OS Version      : macOS Catalina
    R Version       : 3.6.1 

### Steps to reproduce the problem

1. Run a Python script using `import pylab` e.g.
```
import pylab
import numpy as np

x = np.linspace(0, 20, 1000)
y = np.sin(x)

pylab.plot(x,y)
pylab.show()
```

### Describe the problem in detail
The script runs and the plot is displayed in a new RStudio window rather than the Plots Pane. Trying to close the window leads to the spinning wheel. If you source the script rather than running it you can still use the main RStudio window while the other window is stuck. If you run the same plot with pyplot instead there aren't any issues. 

### Describe the behavior you expected

The plot should be displayed in the pane.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It actually looks like this may have been fixed by https://github.com/rstudio/rstudio/pull/8419?

**Comment by melissa-barca** [comment]
> It actually looks like this may have been fixed by #8419?

That would make sense -- at one point I saw the same exception but I thought it was left over from the other issue.

**Comment by melissa-barca** [comment]
I've verified this is fixed in 1.4.1043 🎉

**Comment by melissa-barca** [comment]
@kevinushey Spoke to soon, if you start a fresh session and run the script with `pylab` it opens in a new window that crashes the session when you try to close it. Interestingly enough, if you run a script with `pyplot` first, the pylab plot then works as expected.

**Comment by melissa-barca** [comment]
Verified in 1.4.1052
