### ISSUE TITLE
Disabling automatic tabbing with C++ function modifiers

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#8417]
It would be great if RStudio could support not tabbing over automatically when trying to add these C++ (or C) function modifiers on their own line.

The attached video shows where this happens:
https://vimeo.com/480458175

In case the video isn't working for some reason, here are some pictures. You can see in the first that when I hit Enter after typing `static`, the cursor tabs over when I didn't want it to. In the second, you can see that when I copy the function, delete it, then paste it back in, the automatic tabbing gets applied to the whole function.

<img width="515" alt="Screen Shot 2020-11-17 at 2 34 21 PM" src="https://user-images.githubusercontent.com/19150088/99438785-462ce780-28e2-11eb-8e4e-f10900b29408.png">
<img width="460" alt="Screen Shot 2020-11-17 at 2 34 46 PM" src="https://user-images.githubusercontent.com/19150088/99438786-475e1480-28e2-11eb-8531-75e82ae6f0c6.png">

**Comment by DavisVaughan** [comment]
Keep alive

**Comment by DavisVaughan** [comment]
Keep alive

**Comment by jonvanausdeln** [comment]
Verified on
2022.11.0-78
Windows11, MacOS 12.4, Ubuntu 22.04

Tested several different snippets of C++ code and indent was as expected.
