### ISSUE TITLE
chunk output missing when virtualized output enabled

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8418]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1039
    OS Version      : macOS 11.0.1
    R Version       : 4.0.3

### Steps to reproduce the problem

Ensure that the `Limit visible console output` preference is on:

<img width="628" alt="Screen Shot 2020-11-17 at 11 40 13 AM" src="https://user-images.githubusercontent.com/1976582/99439605-3d301c00-28ca-11eb-9e54-d543a9bc2861.png">

If you need to toggle it on, make sure to restart RStudio afterwards.

Then, open an R Markdown document, and execute a chunk with code:

`````
```{r}
str(mtcars)
```
`````

### Describe the problem in detail

No console output is shown.

<img width="732" alt="Screen Shot 2020-11-17 at 11 45 30 AM" src="https://user-images.githubusercontent.com/1976582/99439705-6781d980-28ca-11eb-9f88-ac6fd00d0295.png">

### Describe the behavior you expected

Console output should be displayed as usual.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note: JS exception described in https://github.com/rstudio/rstudio/issues/8416 is probably related.

**Comment by jmcphers** [comment]
@adamconroy can you take a look for 1.4?

**Comment by adamconroy** [comment]
Interestingly I'm getting the JS exception but cannot reproduce not getting the output. I'm always seeing the dataframe in the console.

**Comment by kevinushey** [comment]
Verified fixed in 1.4.1050 on macOS.
