### ISSUE TITLE
RStudio installer cannot be run if username contains characters from other codepages

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8421]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1042
    OS Version      : Windows 10 x64
    R Version       : <NA>

### Steps to reproduce the problem

Create a Windows account with the username 鬼, and then try to download the RStudio installer (I used the one at https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.4.1042.exe) to the user's Downloads folder, and then try to run it.

### Describe the problem in detail

The installer fails to run and instead pops up an error message "Error launching installer":

<img width="242" alt="Screen Shot 2020-11-17 at 9 13 10 PM" src="https://user-images.githubusercontent.com/1976582/99486784-bdca3900-2919-11eb-90a2-db7c8fd502b2.png">

### Describe the behavior you expected

The installer should be able to run without issue.

### Notes

I suspect this issue effects anyone who tries to use a username with words or characters not representable in the "default" system codepage. This is ultimately going to be rare, but logging this for posterity.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I'll take a look, will either be easy to convince NSIS to work in Unicode, or impossible.

**Comment by gtritchie** [comment]
A workaround is to move the installer package to a folder that doesn't contain any double-byte characters in the path.

For example, in the repro case, I moved from C:\Users\鬼\Downloads to C:\Users\Public\Public Downloads and the installer worked.

**Comment by gtritchie** [comment]
Mentioned here, will see if rebuilding with Unicode True fixes this.

https://sourceforge.net/p/nsis/bugs/1013/

**Comment by gtritchie** [comment]
Fixed via: https://github.com/rstudio/rstudio/pull/8480

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1510, R Version - 3.6.3, Windows 10 - Desktop 

Tested that installer now runs successfully when it is in a folder location including non-standard characters (tested with 鬼). Wax Begonia builds produce the error when run from this location, juliet-rose builds install successfully.
