### ISSUE TITLE
Feature Request: Add the ability to create project favicons, making it easier to navigate between multiple open projects.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#8424]
### Feature Request
Add the ability to create favicons on a per-project level which either replaces or superimposes onto the RStudio logo.

### Use Case 
Users (*especially 'power-users') of RStudio often have multiple projects open in the IDE simultaneously and do alot of switching back and forth between them (see example use case [HERE](https://www.youtube.com/watch?v=boKFxBniUH0)). Having the ability to visually distinguish between these projects would be a quality of life improvement. Admittedly minor, but an improvement all the same (not to mention it being fun for users to be able to assign custom icons to their projects).

<img width="1440" alt="FavIcons_mac" src="https://user-images.githubusercontent.com/62304541/99562129-5c43b200-298d-11eb-99f6-55abff09549b.png">

**Comment by florianm** [comment]
If working on a package, a default to the package hexlogo would be nice.

**Comment by kaijagahm** [comment]
Even just different colors would be cool, if not actual icons.

**Comment by mikebessuille** [comment]
Lots of upvotes; we will consider this.

**Comment by mikebessuille** [comment]
This is out of scope due to the high cost, brand implications, etc, compared with the benefit.   Other applications don't do this...
