### ISSUE TITLE
Add internal command for closing all buffers without saving

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8425]
For automation, it would be very helpful to have a command to close all open buffers (including satellite windows and source columns) without prompting to save modified buffers.

Perhaps simply: `.rs.api.closeAllSourceBuffersWithoutSaving()` or something equally ugly. Don't think it should be hooked to a menu or even the command-palette as accidentally triggering would be Bad (tm).

**Comment by gtritchie** [comment]
Missed a case, if you have a modified but never saved file (e.g. Untitled1.R) then it still prompts.

**Comment by kfeinauer** [comment]
Verified working on 1.4.1052
