### ISSUE TITLE
Console not virtualized by default

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8434]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1039

### Steps to reproduce the problem

1. Install a fresh version of RStudio (clear any user settings in ~/.config/rstudio)
2. Go to Tools -> Console -> Display
3. Examine the "Limit console display" checkbox

### Describe the problem in detail

The box is not checked.

### Describe the behavior you expected

The box should be checked by default so that all users get the improvements we've made to console performance.

**Comment by jmcphers** [comment]
Notes:

- Introduced with https://github.com/rstudio/rstudio/commit/bceeadede78395223ff73e779dbec11bc2e215d0
- https://github.com/rstudio/rstudio/issues/8418 should be fixed first (so we don't break notebooks)

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1052
