### ISSUE TITLE
warnings on session launch when username contains non-ASCII chars

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8435]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1042
    OS Version      : Windows 10 x64
    R Version       : R 4.0.3

### Steps to reproduce the problem

On Windows, create a user account with a name containing special characters. (In this case, I used the account name Crème Brûlée.) Then, try to start a new RStudio session, and create a new R Package project within the home directory somewhere.

### Describe the problem in detail

When the session is initialized, some errors are printed to the console:

<img width="417" alt="Screen Shot 2020-11-18 at 3 25 12 PM" src="https://user-images.githubusercontent.com/1976582/99600436-48f70d80-29b2-11eb-8434-134f77de78cd.png">

If you then try to execute a command, you'll see another warning:

<img width="653" alt="Screen Shot 2020-11-18 at 3 25 43 PM" src="https://user-images.githubusercontent.com/1976582/99600461-544a3900-29b2-11eb-99da-4c344f13ac49.png">

### Describe the behavior you expected

No warnings or errors on opening a standard package project.

### Notes

These errors / warnings are not seen with R 3.6.3 or older, so it is likely related to something that changed in R 4.0.x.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
I just tested this with the same username in 1.4.1054 and see this error:
![image](https://user-images.githubusercontent.com/5323711/99827086-34885180-2b27-11eb-9443-9d8d3c3dffba.png)

Then the next line of code I run in the console gives me this exception, though any lines after that work as expected:
![image](https://user-images.githubusercontent.com/5323711/99827184-52ee4d00-2b27-11eb-88e2-86a5e038d84e.png)

**Comment by melissa-barca** [comment]
Verified in 1.4.1060
