### ISSUE TITLE
autocomplete variable names within ggplot2 aes() calls

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8444]
Given the code:

```
library(ggplot2)
ggplot(mtcars, aes(...))
```

It would be useful if we provided autocompletion results for the column names from `mtcars` within the aesthetic mapping.

**Comment by iago-pssjd** [comment]
A few later I added #8459 without having saw this issue. Is it maybe related?

**Comment by kevinushey** [comment]
This issue merely described an unimplemented feature; I suspect yours is similar.

**Comment by mikebessuille** [comment]
We believe this is low priority; unless additional users can justify the importance of this, we will likely not get to it in the near term.

**Comment by KyBroecker** [comment]
Would LOVE to see this feature, as someone who does a lot of plotting with dfs with all sorts of column names, and sometimes you just cant remember what the exact column name was.

**Comment by DrJCampbell** [comment]
I teach R and not having tab auto-complete for column names is a definite gripe from my learners

**Comment by LibbyHeeren** [comment]
My R learners would also love this functionality (and have brought it up in class!)

**Comment by kevinushey** [comment]
As much as it pains me to say ... we should probably bump this to the next release.

**Comment by vladtarko** [comment]
The autocomplete works if you're using the pipe: 

     mtcars |>
       ggplot(aes(...))

**Comment by JMLuther** [comment]
Autocompletion is a major convenience in ggplot functions.
The only ggplot function that I use commonly that does not support it are the `facet_` functions. 
It would save a bit of time if autocomplete could be implemented there as well. Thanks!

eg, while typing last line here:
```
Theoph %>% 
  ggplot(aes(Time, conc, group=Subject)) +
  geom_line() +
  facet_wrap(~Subject)
```

**Comment by kevinushey** [comment]
Coming to the next daily builds at https://dailies.rstudio.com. You should be able to see both aesthetics that are relevant to the current geom:

<img width="503" alt="Screenshot 2024-02-02 at 2 03 31 PM" src="https://github.com/rstudio/rstudio/assets/1976582/675016c7-8471-4986-84f0-79521a6e7ffb">

As well as variable names (if any) available from the dataset provided to the ggplot2 call.

<img width="496" alt="Screenshot 2024-02-02 at 2 03 37 PM" src="https://github.com/rstudio/rstudio/assets/1976582/2133ce10-243a-4578-8813-744bbaab275e">

We would greatly appreciate any testing and feedback!

**Comment by JMLuther** [comment]
Nice! thanks- variable name suggestions now work for facet_wrap for me (Windows; daily build 397). 
A little sluggish responsiveness on first run, but probably just due to other tasks running on my laptop.

**Comment by olivroy** [comment]
@kevinushey an important test case is the following. with a pipe. IIRC, it worked pretty well before the feature.

```r
mtcars |>
  dplyr::mutate(zz = vs ** 2) |>
  ggplot(aes(<TAB1>, y = <TAB2>)) +
  geom_point() +
  geom_label(data = iris, aes(<TAB3>))
```

In the first TAB1, I would expect aes and column names to show up. (including zz)
![image](https://github.com/rstudio/rstudio/assets/52606734/15405972-35d4-449e-9356-1bdd04b3fdda)


In TAB2, I would expect column names to show up
![image](https://github.com/rstudio/rstudio/assets/52606734/a077c1d7-ab30-4069-b412-5bb696c81e1b)


TAB3 works as expected currently, 
![image](https://github.com/rstudio/rstudio/assets/52606734/2046394e-5698-4456-924d-3017f972f50f)

**Comment by kevinushey** [comment]
@olivroy many thanks; I will take a look!

**Comment by olivroy** [comment]
Thanks for taking a look.  Everything
Just a tiny issue left I think.

## order of the aesthetics suggestions (every case)

![image](https://github.com/rstudio/rstudio/assets/52606734/ffb63518-6c92-4ddc-8b5b-475defff21da)

Should override completions from `aes()`. (this worked correctly the first time. Problem piped or not.

## Piped data + 2 `aes()` calls with the same data.


There is no variable completion in subsequent `aes()` calls for the same data: (my cursor is at `shape = <TAB>`

![image](https://github.com/rstudio/rstudio/assets/52606734/220c8305-0683-41d7-b525-9145df5bfbb6)

This works as expected when the data is not piped in.
![image](https://github.com/rstudio/rstudio/assets/52606734/fdb0b557-1571-4239-bcbe-150d69dbe958)

 still working as expected for a new data
![image](https://github.com/rstudio/rstudio/assets/52606734/e3b26602-9edc-46fa-83e4-ba9509ca1e9f)

And works ok after as well
![image](https://github.com/rstudio/rstudio/assets/52606734/c9edc0ae-c895-4c37-9217-0dbb51bbc586)

**Comment by olivroy** [comment]
On the ggplot2 side, it mostly seems good with #14309. Although I may have found a regression in https://github.com/rstudio/rstudio/issues/14232#issuecomment-1959791168.

Maybe last tiny thing is that newly created variables show in the first `aes()` call, but not in the following ones.

Shown: (note that some variables are missing, but this issue is a broader issue (that shows in other context) Opened #14311 to track this.
![image](https://github.com/rstudio/rstudio/assets/52606734/a28c6cc0-ea98-44d0-a0a3-60bf2d2bf7b0)
Not shown
![image](https://github.com/rstudio/rstudio/assets/52606734/916aad34-ba24-44e9-9ff1-d3ffb0df7aff)


```r
library(tidyverse)
mtcars |>
  tibble::rownames_to_column() |> 
  mutate(
    xz = vs ** 2,
    label = glue::glue("{rowname}, {hp}"),
    aaa = ifelse(gear >= 3, "yes", "no"),
    s2 = vs**2,
    f1 = case_when(
      s2 > 100 ~"Yes",
      .default = "No"
    )
  ) |>
  ggplot(aes(x = xz, y = disp)) +
  geom_point()+ 
  ggrepel::geom_text_repel(
    aes(label = label) # No new variable suggestion shown.
  )
```

(Took a while to isolate things, but I think I have a good understanding now!)

**Comment by kevinushey** [comment]
I believe that issue ultimately comes down to a limitation in how RStudio's autocompletion system tries to find the correct pipe context for a statement. The fact that this code is mixing `|>` (dplyr pipes) and `+` (ggplot2 layer additions) causes trouble here.

I'm going to file that as a separate issue to further enhance this autocompletion feature.

**Comment by kevinushey** [comment]
Also, just to emphasize once more -- thanks @olivroy for taking the time to test each of these revisions; the feature is far more complete than it would have been without your help!
