### ISSUE TITLE
Installing packages graphically does not install dependencies

### ISSUE THREAD

**Issue by ultraviolet-1986** [rstudio/rstudio#8446]
When selecting 'Tools > Install Packages', the box for 'Install Dependencies' is checked but does not install the software with its dependencies.

Specifically, the box being checked produces the output of `install.packages("package_name")` instead of `install.packages("package_name", dependencies = TRUE)`.

This is true for v1.3.1093 under Fedora Silverblue 33. Thank you for your time.

**Comment by kevinushey** [comment]
By default, `install.packages("<pkg>")` does install dependencies -- the default value for the `dependencies` argument is `NA`, and from `?install.packages`:

> The default, NA, means c("Depends", "Imports", "LinkingTo").

Can you elaborate a bit more on the behavior you're seeing?

**Comment by ultraviolet-1986** [comment]
Apologies, you're absolutely right. I thought I'd caught something there.

It's not strictly connected but I've had problems building libraries from source and I thought it was because I was missing dependencies while installing though RStudio - this was not the case; in fact, it was Anaconda's libraries interfering with the system's (such as libfortran and gcc/g++).

Marking this as closed. Thanks again, I'm still learning.
