### ISSUE TITLE
Switching back and forth from normal Markdown editor to visual editor produces unexpected characters sequence

### ISSUE THREAD

**Issue by Waldi73** [rstudio/rstudio#8452]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1048 - preview
    OS Version      : Win 10
    R Version       :  4.0.2

### Steps to reproduce the problem
I'm testing Rmarkdown visual editing mode.
I copied a standard Rmardown r chunck into a visual editor chunck, and made the error to copy the whole chunck including the delimiters into the visual chunck which resulted in following minimal reproducible Rmarkdown code :

````
---
title: "Test"
output: html_document
---

```{r}
```{r}
# Wrong copy paste from normal standard editor chunck to visual editor chunck keeping chunck delimiters
```
```

```{r}
cat('test')
```
````
 
In standard editor, an error is shown : ``unexpected token '`'``
However if I don't correct it and switch to visual editor, the second chunck is transformed in : 
````
```f3175f2a-e8a0-4436-be12-b33925b6d220
31b8e172-b470-440e-83d8-e6b185028602:dAB5AHAAZQA6AFoAZwBBAHoAQQBEAEUAQQBOAHcAQQAxAEEARwBZAEEATQBnAEIAaABBAEMAMABBAFoAUQBBADQAQQBHAEUAQQBNAEEAQQB0AEEARABRAEEATgBBAEEAegBBAEQAWQBBAEwAUQBCAGkAQQBHAFUAQQBNAFEAQQB5AEEAQwAwAEEAWQBnAEEAegBBAEQATQBBAE8AUQBBAHkAQQBEAFUAQQBZAGcAQQAyAEEARwBRAEEATQBnAEEAeQBBAEQAQQBBAAoAcABvAHMAaQB0AGkAbwBuADoATQBRAEEAMwBBAEQASQBBAAoAcAByAGUAZgBpAHgAOgAKAHMAbwB1AHIAYwBlADoAWQBBAEIAZwBBAEcAQQBBAGUAdwBCAHkAQQBIADAAQQBDAGcAQgBqAEEARwBFAEEAZABBAEEAbwBBAEMAYwBBAGQAQQBCAGwAQQBIAE0AQQBkAEEAQQBuAEEAQwBrAEEAQwBnAEIAZwBBAEcAQQBBAFkAQQBBAD0ACgBzAHUAZgBmAGkAeAA6AA==:31b8e172-b470-440e-83d8-e6b185028602
````

and when I switch back to standard editor I get : 
````
---
title: "Test"
output: html_document
---

```{r}
```{r}
# Wrong copy paste from normal standard editor chunck to visual editor chunck keeping chunck delimiters
```


    ```f3175f2a-e8a0-4436-be12-b33925b6d220
    31b8e172-b470-440e-83d8-e6b185028602:dAB5AHAAZQA6AFoAZwBBAHoAQQBEAEUAQQBOAHcAQQAxAEEARwBZAEEATQBnAEIAaABBAEMAMABBAFoAUQBBADQAQQBHAEUAQQBNAEEAQQB0AEEARABRAEEATgBBAEEAegBBAEQAWQBBAEwAUQBCAGkAQQBHAFUAQQBNAFEAQQB5AEEAQwAwAEEAWQBnAEEAegBBAEQATQBBAE8AUQBBAHkAQQBEAFUAQQBZAGcAQQAyAEEARwBRAEEATQBnAEEAeQBBAEQAQQBBAAoAcABvAHMAaQB0AGkAbwBuADoATQBRAEEAMwBBAEQASQBBAAoAcAByAGUAZgBpAHgAOgAKAHMAbwB1AHIAYwBlADoAWQBBAEIAZwBBAEcAQQBBAGUAdwBCAHkAQQBIADAAQQBDAGcAQgBqAEEARwBFAEEAZABBAEEAbwBBAEMAYwBBAGQAQQBCAGwAQQBIAE0AQQBkAEEAQQBuAEEAQwBrAEEAQwBnAEIAZwBBAEcAQQBBAFkAQQBBAD0ACgBzAHUAZgBmAGkAeAA6AA==:31b8e172-b470-440e-83d8-e6b185028602
````
### Describe the problem in detail
Switching back and forth from standard Rmarkdown with error to visual editor produces an unexpexted characters sequence
### Describe the behavior you expected
I would expect to get the same error in visual editor as in standard editor and that switching back and forth keeps source code unchanged, especially for the chuncks without error.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I can reproduce this with the above example. This is an ambiguous situation for the parser but shouldn't result in base64/UUID text becoming part of the document...

**Comment by jmcphers** [comment]
Discussed this with @jjallaire; I will try to craft a fix which makes it more difficult for this accident to happen by discarding nested chunk delimiters in visual mode.

**Comment by kfeinauer** [comment]
@jmcphers I am seeing issues with the fix in the latest daily:

1. Paste the original example into an empty RMD in Visual Mode
2. Switch to source mode
3. Remove inner chunk from root R chunk such that you are left with:
---
title: "Test"
output: html_document
---

```{r}
cat('test')
```

4. Run the Chunk
5. Switch back to Visual Mode, then back to Source Mode
6. Insert the text `This is a chunk:` above the chunk on line 6.
7. Switch to Visual Mode
8. Observe that the Visual Mode renderer is now broken, and renders a very long base64 sequence.

**Comment by jmcphers** [comment]
Yes, the fix just was just for the obvious route. As noted in the QA notes in the PR, there are still several ways to shoot yourself in the foot. We'll leave this open to track those, but I don't think they meet the bar for 1.4.

**Comment by kfeinauer** [comment]
@jmcphers Sorry about that - didn't see the PR notes (impossible to see those in many cases when working through Code Tree). Sounds good!

**Comment by jjallaire** [comment]
I believe we can now close this as I (as part of the v1.4 patch release) implemented a behavior whereby if we see **any** artifacts of failure to parse the markdown (which will generally be a specific sentinel uuid) then we just refuse to switch to visual mode (so no document corruption occurs). Here's what I now get for the minimally reproducible case presented above:

![Screen Shot 2021-07-20 at 9 09 02 PM](https://user-images.githubusercontent.com/104391/126414816-95df1bfa-6706-408a-a223-7895f80dde9e.png)

**Comment by jmcphers** [comment]
@jjallaire closed, thanks!
