### ISSUE TITLE
Keyboard shortcuts not working on RStudio Cloud on iPad

### ISSUE THREAD

**Issue by argenton** [rstudio/rstudio#8456]
### System details

    RStudio Edition : RStudio Cloud
    RStudio Version : 
    OS Version      : iPadOS 14.2
    R Version       : 

### Steps to reproduce the problem
The issue happens in RStuio Cloud running on iPad Pro 9.7in with external keyboard from apple (magic keyboard) and when trying to code in a R Notebook

### Describe the problem in detail
Many of the keyboard shortcuts are not working. Example command+alt+I to insert a new chunk doesn’t work or control+shift+M to insert a pipe operator is not working.

### Describe the behavior you expected
THe keyboard shortcuts should work just like when coding on a laptop or desktop

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
On macOS and iPadOS the shortcut for "Insert Pipe Operator" is actually <kbd>Command+Shift+M</kbd>, not <kbd>Ctrl+Shift+M</kbd>. It is shown incorrectly in the keyboard shortcut help. I'll open a separate issue to clean that up.

I did confirm that <kbd>Cmd+Alt+I</kbd> for a new chunk is not working in cloud or server from iPadOS 14.2, but does work from Safari on macOS. Not sure if this is a new regression in iPadOS or has been broken all along.

**Comment by argenton** [comment]
Thanks, gtritchie. 

Confirmed that pipe  is working on iPad with Command+Shift+M. (I was used to the Ctrl+Shift+M that works on Mac).

Cmd+alt+I indeed not working. Unfortunately!
