### ISSUE TITLE
RStudio Desktop missing text in menu bar and behaviour spreads to other Windows applications

### ISSUE THREAD

**Issue by pmoris** [rstudio/rstudio#8458]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093 (also tested on 1.2.5042)
    OS Version      : Windows 10 Enterprise version 2004 (OS build 19041.630)
    R Version       : R for Windows 4.0.3

### Steps to reproduce the problem

1. Install RStudio Desktop
2. Launch it
3. Inspect menu bar
4. Launch Outlook / Windows explorer / an installation or removal wizard / a save dialogue.

### Describe the problem in detail

As soon as I install RStudio Desktop and launch it, the menu bar at the top contains garbled text. Either all text is missing, text is written in CamelCase, there's weird pixelation/distortion, words are written partly in reverse, or blank spaces appear in the middle of words. 

Afterwards, text starts disappearing from other applications, either immediately or upon moving the mouse cursor over them. In Outlook the mailbox pane entries go blank upon moving the cursor over them, but the message pane and menu bar remain untouched. In File Explorer, file names go blank, although file icons are normal. The start menu and context menus are fine as well, as is the task bar. Uninstall wizards are blank (text and buttons are empty). Save dialogues are also missing text and buttons, and the typing dialogues are extremely narrow (but can still be interacted with through invisible text). Window title bars are unaffected. The RStudio options menu appears normal as well.

This only happens when Rstudio is opened; closing it before switching to an Outlook window for example prevents the text from disappearing. EDIT: upon further testing this behaviour is not consistent. Closing Rstudio and reopening outlook, after text had already disappeared, did not bring back the text.

Signing in and out of Windows resets the problem, until RStudio is opened again. I tested this with RStudio-1.3.1093 and RStudio-1.2.5042 on an admin account in Windows 10 Enterprise version 2004 (OS build 19041.630).

Uninstalling RStudio removes the problem. Installing other software does not have the same affect. Clicking the "restore default font settings" (or enabling the "Hide fonts based on language settings") does not resolve the issue. Switching between hardware and software rendering in RStudio does not make a difference.

The specific way text is messed up in RStudio's menu bar appears to be random (upon both reinstallation and just relaunching the application, reloading the UI via help keeps distortion the same as it was), the disappearing text in Windows is always the same.

I can provide screenshots or a screen capture if desired.

### Describe the behavior you expected

Text in the menu bar should be ligible. RStudio should not distort text in other Windows applications.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Screenshots would indeed be useful, but this issue sounds especially bizarre!

**Comment by pmoris** [comment]
> 
> 
> Screenshots would indeed be useful, but this issue sounds especially bizarre!

It's just one of those Mondays I guess.

Here's a gif showing the entire process: installation -> normal view of Outlook -> launching RStudio -> blank spaces in menu bar text -> text disappearing in Outlook -> blank dialogues in uninstall wizard. Note that the gif loops back to the start, but in reality the issue does not disappear immediately after uninstalling RStudio, only after logging out and back into Windows.

![rstudio-fonts](https://user-images.githubusercontent.com/13552343/100000638-24d86980-2dc2-11eb-91fa-db3245c8c083.gif)

And here's a picture I took of my screen (a terrible sin, I know), showing one of the other ways the menu bar text can distort: 

![rstudio-fonts](https://user-images.githubusercontent.com/13552343/100000218-92d06100-2dc1-11eb-85dd-0711904c6e95.PNG).

I'm pretty flabbergasted myself. I kind of doubt this issue is caused by RStudio directly, having never had issues with it on my previous machines (both Windows and Linux). I suspect there is some weird interplay going on with the specific software/settings on this one, perhaps how it the Qt5 backend. I've searched around for similar problems people reported about Windows, but couldn't find much besides suggestions to turn of Cleartype text or changing locales. The closest report I could find was this one: https://stackoverflow.com/questions/21908334/qt-application-is-killing-characters-accidentally-drawtext-produces-bug and perhaps this one as well: https://stackoverflow.com/questions/34056095/messed-up-layout-in-deployed-qt-application-on-windows-10

I will also try launching Windows in safe mode and see what happens then.

**Comment by R-Hannibal** [comment]
@pmoris - thank you for reporting this issue and providing the gif + screenshot. This is indeed a bizarre and interesting issue, sorry you're experiencing it.

My own attempts to reproduce the issue have been unsuccessful so far. I think you're right and this may be specific interaction of software/settings that is causing the issue.

I'm curious, is this still occurring for you in our latest release (1.4) of RStudio (available [HERE](https://rstudio.com/products/rstudio/download/))? Even though we didn't specifically address this issue, other fixes may have impacted it.

**Comment by pmoris** [comment]
Hi @R-Hannibal, I just gave RStudio 1.4 a try and unfortunately the issue still persists.

If I ever manage to reproduce the problem on another machine myself, I'll make sure to post about it in this issue.
