### ISSUE TITLE
Variables completion does not work inside dplyr `join` functions

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#8459]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : Debian GNU/Linux 9.12 (stretch)
    R Version       : 3.6.3

### Steps to reproduce the problem
With `dplyr` library loaded starts to write any of the next lines:
```r
band_members %>% inner_join(band_instruments %>% filter(name == "John"))
band_members %>% inner_join(band_instruments %>% select(name, plays))
```
You can change the function by `mutate` or others (I do not know the generality of this issue) and `inner_join` by `full_join` or any other `dplyr::..._join`.

### Describe the problem in detail

When one has already written
```r
band_members %>% inner_join(band_instruments %>% filter())
# or
band_members %>% inner_join(band_instruments %>% select())
```
with the cursor inside `filter` or `select` or any other similar function like `mutate`..., and starts to write the variable, it does not work the completion function that works outside `join` functions

### Describe the behavior you expected

Variable names completion working inside `join` functions.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@iago-pssjd Thank you for raising this! Since the behavior is the same in standalone R, I'm marking this as an enhancement to review as a continue development of RStudio.

**Comment by iago-pssjd** [comment]
This issue seems to be a bug, so it should not be closed

**Comment by olivroy** [comment]
Seems to work now! Or I misunderstood the problem. (2023.09.0.401)

**Comment by ronblum** [comment]
@olivroy Thank you for noting this! I'll close the issue.
