### ISSUE TITLE
Panes without tabs should always be minimized

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#8460]
### System details

    RStudio Edition : Both
    RStudio Version : 1.3+
    OS Version      : All
    R Version       : All

### Steps to reproduce the problem

1. Navigate to the Pane Layout section of Global Options and hide all tabs from one or both tab sets.
2. Select Apply.

### Describe the problem in detail
In 1.3 we added the ability for a user to hide all tabs in a pane, however a gray square is still displayed in its place (see picture). This pane will pop open in other circumstances as well. 

### Describe the behavior you expected
Empty panes should default to always being minimized. 

![image](https://user-images.githubusercontent.com/5323711/99985863-7d851380-2d7c-11eb-9404-486221640564.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
I tested this on Version 1.4.1534 and I saw the bottom pane minimize but the top one was not minimizing when I cleared all items set to show. Setting back to in progress.

**Comment by astayleraz** [comment]
Verified in mac desktop Version 1.4.1541 that panes are minimizing and displaying based on if there are items/tabs in those panes or not. Closing as fixed.
