### ISSUE TITLE
Emoji assigned to variable results in unicode value on MacOS

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8463]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1056
    OS Version      : MacOS 11.1 beta
    R Version       : 4.0.3

### Steps to reproduce the problem

Type the following in the console
```
z <- "😀"
z
```

### Describe the problem in detail

The output is the unicode value for the grinning face:
```
> z <- "😀"
> z
[1] "\U0001f600"
```

The environment pane shows the unicode value, as well, instead of the emoji.
<img width="204" alt="env_mac" src="https://user-images.githubusercontent.com/31009952/100017798-745e6b80-2da9-11eb-925d-6a85a3494c37.png">

Note that the same issue occurs when running this code inside an R Markdown chunk.

### Describe the behavior you expected

The smiley emoji should be displayed instead. 

This works as expected in 
- RStudio Desktop 1.4.1056 on Red Hat 8.2
- RStudio Server 1.4.1032 on Red Hat 8.3 using Chrome or Safari from MacOS 11.1
<img width="198" alt="env_nonmac" src="https://user-images.githubusercontent.com/31009952/100017873-8d671c80-2da9-11eb-99eb-4a718199c666.png">

Note: the same problem occurs when running standalone R on Mac, and works in R on other platforms, so we may be limited by R's behavior.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
As an extra data point, `cat(z, sep = "\n")` does display the expected thing here on Windows.

**Comment by kevinushey** [comment]
We could likely fix this by implementing our own `encodeString()` function, which only escapes control characters and leaves everything else alone.

https://github.com/rstudio/rstudio/blob/b384ffea2af481006e9d89b3df91fe5f9029e9aa/src/cpp/session/modules/SessionEnvironment.R#L77-L92

For reference, the R implementation is here:

https://github.com/wch/r-source/blob/9bba9c79731f301622d7fc52b15d3d7f78fa376f/src/main/printutils.c#L659-L694
