### ISSUE TITLE
no output shown when executing inline code chunk

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8465]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 11.0.1
    R Version       : 4.0.3

### Steps to reproduce the problem

Create a new R Markdown document, and then try to run an inline R chunk. For example, with the code:

`````
`r runif(1)`
`````

### Describe the problem in detail

A blank white output box is shown.

<img width="144" alt="Screen Shot 2020-11-23 at 3 05 35 PM" src="https://user-images.githubusercontent.com/1976582/100025655-111b0c00-2d9e-11eb-9907-883d4305506f.png">

### Describe the behavior you expected

The output of the executed command should be shown.

<img width="173" alt="Screen Shot 2020-11-23 at 3 05 27 PM" src="https://user-images.githubusercontent.com/1976582/100025671-15dfc000-2d9e-11eb-954b-df2636b70969.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Verified in 1.4.1063
