### ISSUE TITLE
URLs with no spaces gets combined, converting bracketed links to inline (markdown)

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8471]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1056
    OS Version      : MacOS 11.1 & Red Hat 8.2 (Desktop) and Ubuntu 20.04 (Server)
    R Version       : 4.0.3

### Steps to reproduce the problem

In an R Markdown document:
1. Start in source mode
2. Add the following content:
```
1. [Foo1](https://bar1.com)[Foo2](https://bar2.com)
2. [![](foo3)](https://bar3.com)[foo4](https://bar4.com)
3. <https://bar5.com><https://bar6.com>
4. <https://bar7.com>[Foo8](https://bar8.com)
```
3. Switch to visual mode
4. Switch back to source mode
    - The result is:
```
1.  [Foo1Foo2](https://bar1.com)
2.  [![](foo3)foo4](https://bar3.com)
3.  [https://bar5.comhttps://bar6.com](https://bar5.com){.uri}
4.  [https://bar7.comFoo8](https://bar7.com){.uri}
```

### Describe the problem in detail

Links are combined if there’s no space between them:
- place two links next to each other, or a link next to an image with a link; and
- don’t leave any space between them; and
- switch from visual to source mode

then the links get combined.  In addition, if you do that with links in brackets, they also get turned into inline links in markdown format, and the `.uri` class gets added (examples 3 and 4).

### Describe the behavior you expected

The links should remain separate.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I think this behavior occurs because links are classified as "marks", which by default are combined when adjacent -- e.g. for the bold mark, `<b>foo</b><b>bar</b>` can and should be combined to `<b>foobar</b>`.

**Comment by kevinushey** [comment]
As far as I can see, the issue only reproduces if the links are indeed exactly next to each other (with no spaces). For example, this appears fine to me:

```
1.  [Foo1](https://bar1.com) [Foo2](https://bar2.com)
2.  [![](foo3)](https://bar3.com) [foo4](https://bar4.com)
3.  <https://bar5.com> <https://bar6.com>
4.  <https://bar7.com> [Foo8](https://bar8.com)
```

which makes me think that unless the fix is very straightforward this doesn't meet the bar for 1.4-JR. (Please correct me if I am mistaken!)

**Comment by jmcphers** [comment]
I picked this up a few weeks ago and did some analysis. I think it should be possible to prevent Prosemirror from combining these marks by turning off `spanning` for anchor marks:

https://prosemirror.net/docs/ref/

> spanning: ?⁠bool
> Determines whether marks of this type can span multiple adjacent nodes when serialized to DOM/HTML. Defaults to true.

but in my testing, it didn't.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 2021.12.0-daily+80
    OS Version      : ubuntu20
    R Version       : 4.0.3

Verified that links with no spacing between them are no longer erroneously combined by switching into and out of the Visual Markdown editor.
