### ISSUE TITLE
Real time spell-checking stops identifying existing misspellings after cycling between visual and source modes

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8473]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1056
    OS Version      : MacOS 11.1 and Red Hat 8.2
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open an R Markdown file.
2. Switch to visual mode (if not already in it).
3. In a content area, type `hellllo`.
    - `hellllo` is underlined, identified as misspelled.
4. Switch to source mode.
5. Switch to visual mode.
    - `hellllo` is no longer underlined.
6. Type `bbbbbye`.
    - `bbbbbye` is underlined as misspelled.
    - `hellllo` is still treated as if it's spelled correctly.

### Describe the problem in detail

Real time spell-checking works initially, but if switching back and forth between visual and source modes, existing misspelled words are no longer underlined. However, all newly misspelled words are correctly identified.

### Describe the behavior you expected

Misspelled words should continue to be identified in real time when switching back-and-forth between visual and source modes.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rgayler** [comment]
Issue still exists in RStudio 1.4.1103-4

![Screenshot from 2021-01-24 11-31-13](https://user-images.githubusercontent.com/5409051/105618189-b141ef80-5e38-11eb-8b34-50e5d299c3ed.png)

![Screenshot from 2021-01-24 11-32-12](https://user-images.githubusercontent.com/5409051/105618194-bf900b80-5e38-11eb-9f77-f4f3bb56ed21.png)

**Also**, possibly related: in a much longer R Markdown document I have noticed some misspelled words are not being detected by an explicit spellcheck (F7). I am unlikely to have accidentally added these particular typos to the spellcheck dictionary. Unfortunately I haven't yet been able to reproduce this in a short document. It *might* possibly be restricted to unordered list items.

**Comment by mikebessuille** [comment]
I think this warrants fixing for 1.4-Juliet-Rose, assuming it's not a hugely complex / risky fix.

**Comment by rgayler** [comment]
Possibly related:

In Rstudio 1.4.1106-4 after editing a longish markdown document for some hours with multiple switches between source and formatted mode I noticed that invoking spellcheck (with F7) in source mode returns "Spell check complete" with no spelling errors found, whereas invoking spellcheck (with F7) in formatted mode on exactly the same text returns multiple spelling errors.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.4.1606 on MacOS 11.3 beta and RStudio Server 1.4.1620 on SLES 15 SP2.

@rgayler Thank you for raising this—can you please file a separate issue for this? And if you can include sample code for which this happens, or at least the length of the document you're seeing this in, that would be useful. Thanks!

**Comment by rgayler** [comment]
@ronblum I am really sorry, but I cannot now reproduce the behaviour in [https://github.com/rstudio/rstudio/issues/8473#issuecomment-786416332](https://github.com/rstudio/rstudio/issues/8473#issuecomment-786416332) so haven't opened an issue for it. (When I initially raised it, my intent was to assist diagnosis of https://github.com/rstudio/rstudio/issues/8473

The Rmd file I was editing at the time was ~400 lines, mostly text, with only a few code chunks.

**Comment by ronblum** [comment]
@rgayler Thanks! I haven't been able to reproduce the issue yet with a large file, but I'll try a bit.
