### ISSUE TITLE
Three visual editor shortcuts don't work as expected on Windows and one on Linux

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8475]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1056
    OS Version      : Windows 10 and Linux (Red Hat 8.3 and Ubuntu 20.04.1)
    R Version       : 4.0.3

### Steps to reproduce the problem

On Windows, use the following shortcuts:
1. <kbd>Shift-Ctrl-\ </kbd>
    - Clears formatting, like <kbd>Ctrl-\ </kbd>
2. <kbd>Shift-Ctrl-\ </kbd>
    - Applies italics, like <kbd>Ctrl-I</kbd>
3. <kbd>Ctrl-K</kbd>
    - Nothing happens

### Describe the problem in detail

A few shortcuts aren't properly recognized on Windows.

### Describe the behavior you expected

The Windows shortcuts should do the following:
1. <kbd>Shift-Ctrl-\ </kbd>: Insert/format as a code block
2. <kbd>Shift-Ctrl-\ </kbd>: Insert an image
3. <kbd>Ctrl-K</kbd>: Insert a link

On Linux, on ly <kbd>Ctrl-K</kbd> is a problem.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I can reproduce this as well with Qt 5.12.10, so unfortunately upgrading Qt would not be a fix for these.

The behavior of <kbd>Ctrl + K</kbd> is a bit strange -- the front-end receives a "keyup" event, but no preceding "keydown" event.
