### ISSUE TITLE
No autocomplete in chained data.table operations

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8479]
If I try to chain operations in a `data.table` object with `magrittr` pipes, the autocomplete will not bring up column names of the `data.table` object - e.g. `dt[<focus here>]` gets autocomplete, whereas `dt %>% .[<focus here>]` does not.

**Steps to reproduce:**
* Execute the following code:
```r
library(magrittr)
library(data.table)
dt <- data.frame(col1 = 1:10, col2=11:20)
dt <- as.data.table(dt)
```
* Write the following lines:
```r
dt %>%
    .[co<focus here>]
```
* Focus where it says `focus here` and press tab.

**Expected behavior:** should bring up the column names as suggestion for autocompletion.

**Actual behavior:** doesn't bring up column names for autocomplete.

**Setup:** RStudio 1.4.1055.

**Comment by kevinushey** [comment]
Isn't this sort of chaining fairly uncommon? I thought the idiomatic thing with `data.table` was to explicitly chain usages of `[`.

**Comment by david-cortes** [comment]
It's certainly not commonplace and I think most users of `data.table` would frown at such code, but I've seen other people use pipes with `data.table` too.

**Comment by david-cortes** [comment]
Still relevant.
