### ISSUE TITLE
Cannot create RMarkdown with underscores in title

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8482]
**Steps to reproduce:**
* Click the button at the top-left below `File` which has a green plus sign over a white paper.
* Select `R markdown...`.
* Try to write something with underscores in the title.

**Expected behavior:** should let me write a title with underscores.

**Actual behavior:** doesn't let me write a title with underscores.

**Setup:** RStudio 1.4.1056.

**Comment by kevinushey** [comment]
Can you clarify a bit more? Do you mean that you are unable to insert underscores, or that you see an error if you try to create such a document?

Can you also please share your operating system?

**Comment by david-cortes** [comment]
Yes, that was a bad description. Should have said "doesn't show me underscores when I'm creating the file". The file is created correctly, but RStudio shows the underscores as spaces.

**Comment by david-cortes** [comment]
Come to think about it, could also be an issue with fonts similar to this: https://github.com/rstudio/rstudio/issues/2710

**Comment by ronblum** [comment]
FWIW, I can't reproduce either issue on Debian 10, Windows 10, and MacOS 11.1. Does it only occur with certain themes, like cloud midnight last time?

**Comment by david-cortes** [comment]
@ronblum Still reproducible with the default theme.

**Comment by david-cortes** [comment]
![no_underscores](https://user-images.githubusercontent.com/11860098/100928656-2b1bc380-34ef-11eb-899f-e3aa66beca7a.png)

**Comment by david-cortes** [comment]
@ronblum : does it reproduce if you install debian with only the KDE desktop? (I think the default is XFCE)

**Comment by ronblum** [comment]
I can't reproduce this in Plasma, either (I was earlier using Gnome). I tried a few themes and fonts, as well, including the defaults, as well as the Clouds Midnight theme and Hack font.
