### ISSUE TITLE
Restarting R with .rs.restartR() crashes RStudio after reading file with read_table

### ISSUE THREAD

**Issue by uqrmaie1** [rstudio/rstudio#8487]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      :  macOS Catalina 10.15.4
    R Version       : 4.0.3

### Steps to reproduce the problem

readr::read_table('file')
.rs.restartR()

### Describe the problem in detail

I only have this problem since upgrading to R 4.0.3. Downgrading readr to an older version fixes the problem, so maybe it's an issue with readr.
The problem is also present in RStudio version 1.4

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5611406/diagnostics-report.txt)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@uqrmaie1 Thank you for raising this! Does the problem occur only when using `.rs.restartR()` or does it also happen with the menu item Session -> Restart R?

**Comment by uqrmaie1** [comment]
Only when using `.rs.restart()`, and when rebuilding a package with Command + Shift + B. Session -> Restart R works without problems.

**Comment by kevinushey** [comment]
What version of 1.4 are you testing with? This sounds like an issue that should be resolved in the latest [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

Alternatively, you might want to ensure that all of your R packages are up-to-date as I believe this may have been resolved in the latest releases of `cpp11` and `readr` as well.

**Comment by uqrmaie1** [comment]
I tested it with RStudio-1.4.904. Was the issue already resolved in this version? I did re-install all R packages, but maybe my `cpp11` or compiler are out of date.

**Comment by kevinushey** [comment]
No, only the most recent builds of RStudio 1.4 will have the associated fix.

**Comment by uqrmaie1** [comment]
Thanks, can confirm that the issue is resolved in RStudio 1.4.1063!

**Comment by kevinushey** [comment]
Phew! Glad to hear it; thanks for reporting back.
