### ISSUE TITLE
Issue with persistent output messages left in the console

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#8488]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1056
    OS Version      : Ubuntu 18.04.5 LTS
    R Version       : 4.0.3

### Steps to reproduce the problem
* Render a reprex (On a headless server)
```
reprex::reprex({1 + 1})
```
* Choose to "Open the output file for manual copy"
* Close the pop-up window
* Clear the console (Ctrl + l)
* Repeat all steps at least 2 times

### Describe the problem in detail
The "Clipboard on X11" warning message stays persistently on the console no matter what.
![image](https://user-images.githubusercontent.com/14981085/100546586-2ecdf280-3230-11eb-8ad1-578fcffd8974.png)

I suspect this is RStudio related since this only started happening after updating to the current preview version.

### Describe the behavior you expected
The console would be completely cleared after pressing Ctrl + l

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by andresrcs** [comment]
This is also happening on the Windows desktop version of RStudio and with other packages too, Installing packages with `remotes::install_github()` leaves output messages permanently on the console.

![image](https://user-images.githubusercontent.com/14981085/100548172-f2eb5b00-3238-11eb-9687-726d8b9a1a67.png)

**Comment by adamconroy** [comment]
This is probably the same as https://github.com/rstudio/rstudio/issues/8428. Linking these for this repro as well. Thank you for reporting this issue.

**Comment by kfeinauer** [comment]
@andresrcs Would you be willing to check the latest daily to see if it fixes your issue?

**Comment by adamconroy** [comment]
Sorry this shouldn't be fixed yet. Still working on it! #8428 encompasses this issue but it's also more complex.

**Comment by kfeinauer** [comment]
@adamconroy Sorry about that! Got confused by looking at this issue view in Code Tree!

**Comment by kfeinauer** [comment]
@andresrcs This should be fixed now in the latest daily. Would you mind giving it a try to see if it fixes your issue?

**Comment by andresrcs** [comment]
The issue seems to be solved on both, the desktop and server versions.
