### ISSUE TITLE
Renaming a File open in satellite window doesn't update name

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8490]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.1063 (also 1.3.1093)
    OS Version      : macOS 11.0.1
    R Version       : 3.6.1

### Steps to reproduce the problem
- open a file from the Files pane (e.g. `a.R`) into the source pane
- move to a satellite window ("Show in new window") and arrange so you can see both the satellite window and the Files pane
- rename that same file `a.R` from the Files pane (or in macOS desktop IDE, use File / Rename from main menu while focus was on the satellite window)

### Describe the problem in detail
- the file is renamed in the filesystem, but the tab in satellite window still shows the old name
- secondary problem: now click on the renamed file in the Files pane; it opens again in the main window with the new name while keeping it open in the satellite window with the old name
- so now seem to have the same file open twice; if you then close and restart RStudio it comes back this way (except now both show the same correct filename but we don't support opening the same file twice so this is bad)

### Describe the behavior you expected
- renaming an open file updates the tab to match whether it's in the main window, a source column, or a satellite window
- should not be able to open the same file in separate editor tabs (until we implement such a feature, that is)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Fixed in 1.4-juliet-rose via #8727

**Comment by valerie-rstudio** [comment]
### Verified fixed

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1518
    OS Version      : 4.0.2
    R Version       : macOS 11.1 & centos8

Verified that a file can be successfully renamed while that file is being viewed in a new window. This also prevents the secondary issue of being able to open a file twice, since the name of the file in the satellite window is updated immediately upon renaming.
