### ISSUE TITLE
Renaming a file doesn't update tab tooltip

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8491]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.1066
    OS Version      : macOS 11.0.1
    R Version       : 3.6.1

### Steps to reproduce the problem
- open an existing file in the RStudio editor
- File / Rename, change name of file
- Hover over the file's editor tab

### Describe the problem in detail
- Shows the original name of the file (before doing the rename operation)

### Describe the behavior you expected
- Tooltip always shows the actual filename

- See also: #8490

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: also in 1.3.1093.

**Comment by gtritchie** [comment]
Fixed in 1.4-juliet-rose via #8727

**Comment by astayleraz** [comment]
Verified tooltip now shows correct after a file is renamed. Checked this on desktop and server Version 1.4.1507-1 and R 3.6.0.
