### ISSUE TITLE
Support for separate font settings for text and code block in R Markdown

### ISSUE THREAD

**Issue by enixam** [rstudio/rstudio#8493]
Since people are increasingly authoring books and documents directly in R Markdown, it should be helpful to set different font settings (font family, size) for normal text and code blocks. Mono font doesn't work well outside code.

**Comment by kevinushey** [comment]
I think this is ultimately resolved via the visual editor mode in 1.4? We don't intend to allow users to customize the fonts used in the source editor on a chunk-by-chunk basis.

**Comment by enixam** [comment]
Yes, but I notice that users can't customize font settings in visual mode.
