### ISSUE TITLE
Add flexibility for new file definitions

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#8498]
When a new Plumber file is created in the IDE, the new file is automatically populated with a template:
```r
#
# This is a Plumber API. You can run the API by clicking
# the 'Run API' button above.
#
# Find out more about building APIs with Plumber here:
#
#    https://www.rplumber.io/
#

library(plumber)

#* @apiTitle Plumber Example API

#* Echo back the input
#* @param msg The message to echo
#* @get /echo
function(msg = "") {
    list(msg = paste0("The message is: '", msg, "'"))
}

#* Plot a histogram
#* @png
#* @get /plot
function() {
    rand <- rnorm(100)
    hist(rand)
}

#* Return the sum of two numbers
#* @param a The first number to add
#* @param b The second number to add
#* @post /sum
function(a, b) {
    as.numeric(a) + as.numeric(b)
}
```

When this template is run with the latest CRAN release of Plumber (1.0.0), a user sees the following message printed to the console:
```
Warning message:
Plumber tag `#* @png` is deprecated.
Use `#* @serializer png` instead. 
```

It would be nice if the IDE provided a template based on the version of the Plumber package that was being used. This could be extended to other template files for other packages as well.

**Comment by kevinushey** [comment]
We opted to just update the template. See: https://github.com/rstudio/rstudio/pull/9402
