### ISSUE TITLE
Certain file types (.pdf and .docx) files will not open in the IDE on macOS Big Sur.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#8506]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093 / 1.4.1072
    OS Version      : macOS Big Sur Version 11.1 Beta
    R Version       : 4.0.3

### Steps to reproduce the problem
1. Open the IDE > Navigate in the files pane to either a .docx or .pdf file and select it.

### Describe the problem in detail
These 2 doc types (.docx + .pdf) appear inert in the IDE as selecting them from the files pane has no effect.

### Describe the behavior you expected
Selecting either a .docx or .pdf file in the files pane opens it outside of the IDE.

### Notes

- This issue has been reported by multiple users on community: https://community.rstudio.com/t/rstudio-accessing-word-and-or-pdf-previewer/88951

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rressler** [comment]
I have the same issue (Mac os 11.0.1). It also affects html files. They will open in the editor but not in the browser.

**Comment by shirispitzsiddiqi** [comment]
Same issue for me! I have no info to add, just want to make it known...

**Comment by R-Hannibal** [comment]
Moving this issue into 1.4, seems like this is effecting lots of users.

Also, comment from @jjallaire - If this also prevents PDF preview for R Markdown / Sweave from working then it definitely meets the bar (for 1.4).

**Comment by ronblum** [comment]
The problem is limited to files with spaces in the name.

**Comment by ronblum** [comment]
Note: This also includes .html, .xls, and .xlsx files with spaces in the name. So, probably anything that involves opening an external application, if there are spaces in the name. (Checked on MacOS Big Sur 11.1 Beta 20C5048k.)

**Comment by rressler** [comment]
I experience with files with no spaces in the name, e.g., hw_forcats_lubridate.html

**Comment by kevinushey** [comment]
@rressler: what is the full path to the file? Does that path contain any spaces (e.g. in your user name, project name, or elsewhere)?

**Comment by rressler** [comment]
Kevin,
Yes there are spaces in the OneDrive connection. When I put an HTML file with no spaces in the name in the Users/rressler directory above that it works fine. If I then add a space in the filename, it does not work.
So as RonBlum pointed out, the spaces are an issue, and that is if they occur anywhere in the complete path/filename.

/Users/rressler/OneDrive - american.edu/Courses/STAT-412-612/Lectures_All/12_forcats-lubridate/a_factors.html

Thanks!
Richard

**Comment by gtritchie** [comment]
Investigation in progress, some notes:

- this is Big Sur-specific (doesn't happen on Catalina)
- if you run RStudio from terminal, and try to open a pdf, word-doc, etc. with spaces in the path you see something like this:

```
The file /Applications/RStudio.app/Contents/MacOS/file:/Users/gary/Desktop/word the doc.docx does not exist.
```

In this case that actual file is `/Users/gary/Desktop/word the doc.docx` not sure why the Application path is being prepended to the error displayed by the `open` command.

The code that loads files in this situation is here: https://github.com/rstudio/rstudio/blob/3ce9c7e533df26117069882734144bf933de4b6b/src/cpp/desktop/DesktopGwtCallback.cpp#L209-L234

I tried a few obvious escaping strategies with no success (surround the path with quotes, put backslash in front of spaces).

**Comment by ronblum** [comment]
Confirmed in RStudio Desktop 1.4.1093 by open a file with .html, .docx, .xlsx, and .pdf files with spaces in the name, and .xlsx with a space in the parent directory's name. In addition, for .xlsx, also confirmed that Import Dataset is successful.
