### ISSUE TITLE
Crtl + Tab Should be Infinite

### ISSUE THREAD

**Issue by mertbakir** [rstudio/rstudio#8507]
**Feature Request:**

Hi, this is very small request. Crtl + Tab Should be Infinite

**How it's currently:**

Currently, in Rstudio, if I'm in the last opened file it requires a Ctrl Shift Tab to go back and Ctrl Tab doesn't go to the next (first one) since it's the last documents.

**How it should be:**
Ctrl Tab should go to first file if current selected one is last. Similaryl Crtl Shift Tab should go to last file if current selected one is the first file.

**Comment by jmcphers** [comment]
Do you have tab wrapping turned on? (Options -> General -> Wrap around when navigating)

**Comment by mertbakir** [comment]
Ah, thanks. Sorry, I actually searched for it before opening the thread.
