### ISSUE TITLE
Cut and Copy Current Line Without Selection

### ISSUE THREAD

**Issue by mertbakir** [rstudio/rstudio#8508]
**Feature Request:**

I would like to be able to cut and copy a line without first selecting the next like in Visual Studio Code. 

CTRL X: Cut the line where the cursor is
CTRL C: Copy the line where the cursor is

It would be very useful for feature for me and probably for most of us.

**Comment by ronblum** [comment]
@mertbakir Thank you for the suggestion! I'll mark it for review as part of development cycle.

**Comment by fabeit** [comment]
Hello, is there still not shortcut for this function, I use all the time in Sublime Text
