### ISSUE TITLE
Add a button to Hide Variables in "Environment" Section

### ISSUE THREAD

**Issue by mertbakir** [rstudio/rstudio#8509]
**Feature Request:**

Add a button to hide variables in "Environment" section.

**Why This is Needed:**

I'm using RStudio 1.4 beta and it shows Python variables via reticulate. So, there is variable called ```r``` in Python Variables and it's basically all python variables again. It's a very huge list and clutters up the space. You may consider hiding r in python section and py in r section but I think ability hide any variable and leaving the choice to user is will be better.

**Comment by ronblum** [comment]
@mertbakir Thank you for the suggestion(s)! We'll review them as we continue development of RStudio.
