### ISSUE TITLE
Carriage Returns cause degenerate output with Limit Console Output turned on

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#8511]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. Turn on Limit Console Output
2. Follow the output posted by Kevin https://github.com/rstudio/rstudio/issues/8428#issuecomment-732379178 and notice that output gets jumbled around when using carriage returns.

### Describe the problem in detail

In certain cases, particularly when using multiple carriage returns in a single line, the output gets jumbled and not what you would expect. I have a pretty thorough set of tests that I'm using to narrow down exactly what's happening but I don't quite have my finger on it yet, the other issues that cropped up while investigating #8428 were pulling me away from the primary cause.

### Describe the behavior you expected

Carriage returns always bring the cursor to the beginning of the line.

**Comment by adamconroy** [comment]
https://gist.github.com/adamconroy/862b08e80b6766c7c212bd12b40f09de

This is a gist of the ways I'm testing right now. There are different symptoms based on whether there are unicode characters, new lines, where the carriage returns are, the length of lines...and more. It's made narrowing down exactly what's going on tricky, especially with some non-regression weird functionality showing up as well.

**Comment by mikebessuille** [comment]
We need to either fix this, or disable the console limiting feature until it's fixed.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1078.
