### ISSUE TITLE
RangeError when switching between source and visual mode

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8513]
It's possible for users to get into a state where they are unable to switch between source and visual mode due to a "RangeError" that occurs when attempting to restore the cursor position in visual mode. This video illustrates:

![Screen Recording 2020-12-01 at 5 50 00 PM](https://user-images.githubusercontent.com/104391/100861623-18a67900-3460-11eb-8722-83ab5d2533e0.gif)

This is the document being used within the video: https://github.com/rstudio/blog/pull/369

The error is likely due to attempting to address a position which is no longer valid (e.g. b/c the document has become shorter). The bug here is not really the invalid position (that is bound to happen) but rather than that it prevents switching to the visual editor entirely. 

Earlier in the development process we wanted these to be user level errors so we could discover problems in our position restoration logic, but at this point we should swallow this error silently. We unfortunately still don't have a reliable repro (which would help in targeting the fix correctly).

**Comment by jjallaire** [comment]
I would speculate that this could be caused by having the cursor near the end of the document in visual mode and then removing a part of the document in source mode (such that the cursor position becomes invalidated).

**Comment by kfeinauer** [comment]
Verified no error on 1.4.1078

**Comment by jdeboer** [comment]
I'm experiencing this error in RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-23) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.07.1+554 Chrome/102.0.5005.63 Electron/19.0.4 Safari/537.36

This is with a Quadro presentation I am working on.

I can switch from Visual to Source, but I can't switch back to Visual again unless I close the RStudio the project then reopen. This error happen even without moving the typing cursor. I.e. If I switch from Visual to Source without moving the cursor and then back to Visual again, I will still get this error message: "RangeError: Position 16604 out of range".

**Comment by antaldaniel** [comment]
The R version 4.4.0 (2024-04-24 ucrt), Windows 10 x64 (build 19045),  collate  English_United Kingdom.utf8,  ctype    English_United Kingdom.utf8,  rstudio  2024.04.1+748 Chocolate Cosmos (desktop) also produces this error.
