### ISSUE TITLE
Can’t click into blocks and code chunks with visual mode in RStudio Server with Firefox and Safari

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8518]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1032 (I'll check on a more recent version)
    OS Version      : MacOS 11.1 beta, Windows 10, and Red Hat 8.3 (probably other Linux flavors, too)
    R Version       : 4.0.3

### Steps to reproduce the problem

In visual mode:
1) Insert a table: <kbd>Table -> Insert Table</kbd>
2) Insert a code chunk: <kbd>Insert -> Code Chunk -> R</kbd>
3) Enter a line of code: `x <- 1`
4) Click in the table.
    - Cursor moves inside the table, as expected. 
5) Click in the code chunk
    - The display jumps to the top of the file.
    - The cursor moves to the bottom of the file.

#### Failure Details
- You can’t click into blocks and code chunks in RStudio Server using Firefox, Safari and Microsoft Edge.
- Can’t click inside code chunks and blocks—R, Python, etc. code chunks, YAML, HTML, etc. 
- I think it’s anything that begins with ` ``` ` or `{`.
- The display jumps to the top of the file.
- The cursor moves to the bottom of the file.

#### Success Details
- Works in Chrome, Edge, and RStudio Desktop.
- Works with stuff like tables and divs.
- Works with inline code; for example it works with TeX inline but not with TeX blocks.
- Can insert a chunk, block, etc. and write code in it. But after leaving it, can’t go back.

### Describe the behavior you expected

We should be able to go back into code chunks and blocks, as with RStudio Desktop and RStudio Server using Chrome or Edge.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
It's not even limited to clicking -- just moving the cursor into these regions via arrow keys reproduces the issue, too.

I'd initially suspected that the misfire was coming from our code that attempts to keep the cursor in view (as Prosemirror can't scroll it automatically) but whatever's sending things off the rails is doing it much earlier than the cursor sync code.

**Comment by jmcphers** [comment]
This is pretty mysterious. The scroll to the top is happening in a very implicit way -- it doesn't involve any explicit scroll commands as far as I can tell and _doesn't even generate a scroll event_. It's not a side effect of selection forwarding, our Ace focus/blur handlers, or the inert or focus-visible polyfills.

Another clue is that it doesn't generate a focus event, either, but the `<body>` tag is becoming the active element. My best guess at this point is that the Ace hidden input element is being destroyed when it has focus, and since focus has to go _somewhere_ it's getting picked up by the `document` itself.

**Comment by ronblum** [comment]
Note: This works with Microsoft Edge on Windows 10.

**Comment by ronblum** [comment]
Confirmed with Safari and Firefox on MacOS 11.1 using RStudio Server 1.4.1081 on Ubuntu 20.04. No impact on Chrome. I need to check Edge before marking "verified."

**Comment by ronblum** [comment]
Confirmed in RStudio Server 1.4.1096 using Firefox and Safari.
