### ISSUE TITLE
RStudio v1.4.1074-1 Preview Bug - Console jumps around

### ISSUE THREAD

**Issue by jzadra** [rstudio/rstudio#8529]
I just installed the RStudio v1.4.1074-1 Preview. The console jumps around. Hitting "latest" does something, but doesn't solve it. Hitting escape a few times will stop it temporarily, but then it will start again after scrolling.

https://imgur.com/a/og7sxtl

─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────

version R version 4.0.2 (2020-06-22)
os macOS Catalina 10.15.7
system x86_64, darwin17.0
ui RStudio
language (EN)
collate en_US.UTF-8
ctype en_US.UTF-8

**Comment by gtritchie** [comment]
May already be covered by other fixes (or at least other existing issues) but will let @adamconroy make that determination.

**Comment by lrdegeest** [comment]
Also seeing this. Same version of RStudio. Windows machine.

**Comment by adamconroy** [comment]
This is likely the same as the above issue. I will need a reprex.

**Comment by kevinushey** [comment]
@jzadra @lrdegeest: can you please provide a reproducible example? Preferably, a snippet of code that we could copy + paste to run in RStudio, and then scroll around and see the jumpy console issue you're referring to.

**Comment by jzadra** [comment]
Sorry I uninstalled it because it was unusable, so I can't test.  It happened as soon as the console in the new session had enough output that it started to scroll.  

One thought to try if it isn't occurring is that I have my tibble options set to print 50 rows instead of the default (10 i think?).  I also have the GUI setting for "Limit output line length to:" at 100.

My tibble options are set in the options block of my .Rprofile:
`  tibble.print_max = 70, tibble.print_min = 50`

**Comment by adamconroy** [comment]
@jzadra thanks, I'll see if I can reproduce it with those settings. An example data frame would go a long way as well but I'll do my best.

For reference you can go to options -> Console -> Limit console output and that will restore the old console functionality so you don't have to uninstall.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1597
    OS Version      : mac OS 11.2.1
    R Version       : 4.0.3

Verified that the console no longer appears to be jumping around. Tested with the tibble settings `tibble.print_max = 70, tibble.print_min = 50`. Also tested various console scrolling and focus functionality with Limit Console Output turned off to ensure no other bugs were introduced.
