### ISSUE TITLE
Add preferences toggle (or new shortcut) for the forthcoming (and now in R-devel) native pipe symbol (|>)

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#8534]
While not a trivial feature request ask, a toggle to have `cmd-shift-M` use the new native pipe symbol vs {magrittr}'s would be great! The suggestion for an alternate keybinding by @Robinlovelace (in the parallel feature req) for a separate keybinding would be a fine alternative as well, cmd-shift-> (greater than) seems to be available at least on macOS and seems like a pretty good one.

A cosmetic A++ parallel request to this is to figure out why |> does not render ligatured (as a right-facing triangle) as it does in Sublime, iTerm, VS Code, etc. (this may be an un-fixable-by-RStudio QT issue, tho).

The ligature rendering works fine when backtick-quoted or single/double quoted.

<img width="93" alt="image" src="https://user-images.githubusercontent.com/509878/101150005-aebbda00-35ed-11eb-857c-3d4dd181eb81.png">

**Comment by Robinlovelace** [comment]
> Suggested ways it could be supported:
> 
>     *

**Comment by Robinlovelace** [comment]
Just a comment on accessibility from Barry Rowlingson:

> Obscuring underlying character codes with ligatures is *not* good for accessibility. Don't do it.

Implication: any changes should not become the default and people should think twice before setting ligatures.

**Comment by hrbrmstr** [comment]
Um, ligatures are a personal choice. Nobody has to use a ligature-enabled font. Barry's comment is woefully uninformed.

**Comment by Robinlovelace** [comment]
> Um, ligatures are a personal choice. Nobody has to use a ligature-enabled font. Barry's comment is woefully uninformed.

I don't know much about it. Is there any evidence about it? The reason for raising this was that it seemed to ring try: if newbies start seeing triangles and arrows could that not make R seem harder than it is? Slightly off topic but interesting ideas both ways.

**Comment by hrbrmstr** [comment]
All other decent coding editors provide the option to support ligatures.
Flat out preventing the ability to choose to use them seems pretty counter
intuitive to me.

I’m not trying to counter any accessibility claims, but dictating to me
that I should not be able to use them if I want to is a pretty strong and
wrong position for him or anyone to hold.

**Comment by Robinlovelace** [comment]
I see your point. Barry's comment on Twitter was a bit dictatorial. Hopefully my suggestion that

> any changes should not become the default and people should think twice before setting ligatures

is more nuanced and compatible with that - agree, I'm 'pro choice' on this ; )

**Comment by jmcphers** [comment]
Ligature fonts are so popular that we briefly entertained the idea of shipping a couple with RStudio Server, but decided against it for the reasons @Robinlovelace mentioned. However we'd like them to work correctly for folks who prefer them. 

@hrbrmstr Feel free to file a separate issue on the ligature. We'll need to know what specific ligature font you're using, too.

**Comment by kevinushey** [comment]
Will be fixed by https://github.com/rstudio/rstudio/issues/8534 (we need to ensure `|>` is tokenized as a single token, which is done in that PR)

**Comment by Robinlovelace** [comment]
Wow fast work guys, seems the solutions are in place less than 24 hours after R's 'native pipe' was available!

**Comment by ntluong95** [comment]
sorry @kevinushey. I updated the newest version of Rstudio and R-devel but I can not display the native pipe like that. Also we should consider about the short cut for it. It should be different with Ctrl + Shift + M

**Comment by Robinlovelace** [comment]
Ctrl + Shift + P gets my vote

**Comment by ntluong95** [comment]
That makes sense

**Comment by gtritchie** [comment]
Ctrl+Shift+P is already used by the new command-palette feature in 1.4.

**Comment by Robinlovelace** [comment]
Aha. M is my vote then, unless there are reasons not to go for that :+1:

**Comment by andrie** [comment]
I suspect that there will be quite a long transition period where the `magrittr` pipe `%>%` as well as the base R pipe `|>` will be in use.

Thus I suggest the keyboard shortcut `Shift + Ctrl + |` as the keyboard shortcut for the base R pipe.

**Comment by ntluong95** [comment]
I think Ctrl + Shift + > may be easier to remember as ">" symbol meaning forward. In addition, the symbol ">" is near with letter M

**Comment by andrie** [comment]
The shortcut `Ctrl + Shift + >` is already in use to surface a quick change of open tabs:

![image](https://user-images.githubusercontent.com/479998/101344088-db395580-387c-11eb-967f-d0d2d4bf62c6.png)

**Comment by hadley** [comment]
I would recommend making the existing pipe shortcut configurable rather than adding a new keyboard shortcut. It should definitely require user opt-in, since while the magrittr 2.0.0 pipe and the base pipe are very similar, there are a few differences on edge cases that might catch folks out.

**Comment by mikebessuille** [comment]
To consider for 1.4-Juliet-Rose or 1.5.

**Comment by kevinushey** [comment]
@hadley: do you imagine that in the future, use of the native pipe over the magrittr pipe will be encouraged in the tidyverse? Or will they just be two potential alternatives based on what the user wants to do?

**Comment by kevinushey** [comment]
(Another way of putting it: will some future version of tidyverse documentation use `|>` over `%>%`?)

**Comment by hadley** [comment]
@kevinushey the plan is to gradually switch to use the base pipe. Unfortunately we don't have an exact plan for how to do while keeping our guarantee that the tidyverse works with the last five versions of R. We'll probably need to do some `\Sexpr{}` magic in examples so that new versions of R see `|>` and old versions see  `%>%`.

**Comment by jmcphers** [comment]
This is now implemented in the Juliet Rose branch.

**Comment by astayleraz** [comment]
Verified setting shows now in Version 1.4.1507-1 and R 3.6.0. Added QA automation test to verify changing this setting and the output text that shows when the hot key command is used.

**Comment by gforge** [comment]
Column name hints are not yet available when using |> (version 1.4.1714)

**Comment by mikebessuille** [comment]
@gforge that is covered separately in this issue: https://github.com/rstudio/rstudio/issues/9385
