### ISSUE TITLE
Support the new base R pipe |>

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#8536]
This looks very exciting: https://twitter.com/henrikbengtsson/status/1334703130378788866

Suggested ways it could be supported:

- [ ] Ligatures show nicely as in F: https://twitter.com/nanxstats/status/1334741663294611457
- [ ] Shortcut (e.g. Ctl+Shift+P, short for Pipe and no clash with Ctl+Shift+F)

Visual comparison + online question: https://twitter.com/robinlovelace/status/1334795568762281988

**Comment by hrbrmstr** [comment]
FWIW: https://github.com/rstudio/rstudio/issues/8534

**Comment by Robinlovelace** [comment]
You got their first. Closing as duplicated. Thanks @hrbrmstr !
