### ISSUE TITLE
autocompletion entries inappropriately quoted in some cases

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8538]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1078
    OS Version      : macOS 11.0.1
    R Version       : 4.0.3

### Steps to reproduce the problem

<img width="277" alt="Screen Shot 2020-12-04 at 9 37 05 AM" src="https://user-images.githubusercontent.com/1976582/101195459-4df3c800-3614-11eb-9129-cf436a834152.png">

### Describe the problem in detail

<img width="212" alt="Screen Shot 2020-12-04 at 9 37 10 AM" src="https://user-images.githubusercontent.com/1976582/101195469-521fe580-3614-11eb-9428-88b4e68cd7e2.png">

### Describe the behavior you expected

No backticks around completion insertion.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Seems to just be strings with spaces or = ?    Is this a regression?  if not... we could consider moving this to 1.4-J-R

**Comment by kevinushey** [comment]
This is unfortunately a regression; fortunately it should be a safe fix.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1085
