### ISSUE TITLE
Rstudio diagnostic isn't compatible with new native R pipe

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#8543]
![image](https://user-images.githubusercontent.com/63569637/101217163-2f77e600-3681-11eb-82cf-2f969c84b402.png)

Rstudio recognizes the new R pipe as a bug

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/rstudio/pull/8533.

Note that these changes won't be available in the daily builds yet -- we've merged these to a separate branch that will later become the "main" daily builds after the initial 1.4 release has been made.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1547, R Version - 3.6.3, Windows 10 - Desktop 

Support successfully added for the new pipe operator `|>` and shorthand for anonymous functions `\(x) x`. Tested with the below piece of code, which returns errors in Wax begonia (1.4.1103) and now runs successfully in Juliet-Rose builds.

```
foo <- \(x, y, z) {
  x |> y() |> z()
}
```
