### ISSUE TITLE
Syntax highlighting for Python keyword

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#8545]
Can we have the update on the next version of Rstudio to highlight several keywords function when writing Python code in Rstudio. It could be a valuable upgrade

![image](https://user-images.githubusercontent.com/63569637/101245247-b2de1980-370b-11eb-9e94-f6b62456f327.png)

**Comment by ronblum** [comment]
@ntluong95 Thank you for the suggestion! We'll review it as we continue to make changes to RStudio, including support for Python.

**Comment by kevinushey** [comment]
Note that these functions are not keywords (in the sense of being specially-handled tokens by the Python parser); they're just regular old functions. For that reason, they are not given any special highlighting.

**Comment by lonelyjoeparker** [comment]
Have to agree that extra python highlighting would be really useful
