### ISSUE TITLE
String Encoding Error in Notebook output

### ISSUE THREAD

**Issue by 4Urban** [rstudio/rstudio#8546]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 1.4.1066
    OS Version      : Windows 10/8/7 (64-bit)
    R Version       : R x64 4.0.3

### Steps to reproduce the problem
To reproduce the problem, no need to get any data.
It occurs at any time when logging any character that is not the English alphabet.

For example, when running the below code for the first time, the result is as follows.

```
library(dplyr)
```
![image](https://user-images.githubusercontent.com/49590998/101282157-be6a3700-3816-11eb-8b82-202f01791158.png)

It's same in the console.

![image](https://user-images.githubusercontent.com/49590998/101282988-6c77e000-381b-11eb-8385-00c5768b1fa6.png)

### Describe the problem in detail

However, if I run the **same code** in the *console for the first time*(not again, after restarting the R), it prints without any error.

![image](https://user-images.githubusercontent.com/49590998/101283001-77cb0b80-381b-11eb-84f9-5d9eb543d55e.png)

That is, I get an error ONLY when I interact in the Notebook console.

Below is my basic settings in the Notebook.

![image](https://user-images.githubusercontent.com/49590998/101283055-afd24e80-381b-11eb-83f6-7d10949fcf9e.png)

### Describe the behavior you expected

I want to get correctly encoded messages in the Notebook console as same as in the console.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note for testing: to get Korean output on an English copy of Windows, you'll need to activate a Korean locale and also request Korean message translations. This can be done with:

```
Sys.setlocale(locale = "Korean")
Sys.setenv(LANGUAGE = "ko")
```

**Comment by kevinushey** [comment]
Interestingly, errors are properly translated -- it appears just package startup messages (and perhaps other conditions) are the problem?

<img width="547" alt="Screen Shot 2020-12-07 at 2 47 20 PM" src="https://user-images.githubusercontent.com/1976582/101414535-1fd3e980-389b-11eb-8a6f-b9f7a0883b56.png">

**Comment by 4Urban** [comment]
You're right. I can reproduce that problem only when starting packages too. In my memory, all the error messages in Korean also showed the same problem before, but it doesn't not now except startup.

I'll comment later when I get the same problem in other conditions.

Thank you!

**Comment by kevinushey** [comment]
This is indeed an RStudio issue: we're not properly handling the encoding of R conditions. Will keep taking a look!

**Comment by 4Urban** [comment]
Ok! Thank you!

**Comment by jmcphers** [comment]
Fixed in Juliet Rose via #8565.

**Comment by 4Urban** [comment]
@kevinushey Thank you for the fast fixing!

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1545
    OS Version      : Windows 10
    R Version       : 4.0.3

Verified that package startup messages in Notebook and Console are now properly UTF-8 encoded. Tested with the Korean language.
