### ISSUE TITLE
Math preview stops working in the editor after using `\text`

### ISSUE THREAD

**Issue by fnaufel** [rstudio/rstudio#8547]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1038
    OS Version      : Ubuntu 20.04.1 LTS, Linux 5.4.0-56-generic (x86_64)
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem

1. Create a new RMarkdown file or open an existing Rmd file.

2. Type some math expression --- e.g., $y = f(x)$ --- in the source editor.

3. Place the cursor inside the math expression you just typed. The math preview appears, as expected.

4. Type another math expression, this time containing a `\text` command --- e.g., $\text{Cov}(X, Y)$ or $\textrm{Cov}(X, Y)$. 

5. Move the cursor outside this second math expression.

6. Place the cursor inside **any** math expression in the document. The math preview will not appear anymore.

7. Only by closing and reopening RStudio can I make the previews appear again. Existing math expressions, even those containing `\text`, will show normally, until I type a new math expression containing `\text`.

### Describe the problem in detail

Math preview fails to show in the source editor after a math expression containing the `\text` command is typed. After such a command is typed, math preview stops working for any LaTeX expressions anywhere in the document.

### Describe the behavior you expected

Math preview should appear for any math expression at all times.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by fnaufel** [comment]
Just checked my rsession log file and found this MathJax error:

```
06 Dec 2020 16:49:31 [rsession-fnaufel] ERROR CLIENT EXCEPTION (rsession-fnaufel): (TypeError) : Cannot read property 'eC' of null;
org/rstudio/studio/client/common/mathjax/MathJaxTypeset.java#42::onMathJaxTypesetComplete
org/rstudio/studio/client/common/mathjax/MathJaxTypeset.java#87::onMathJaxTypesetCompleted
rstudio-0.js#-1::eval
com/google/gwt/core/client/impl/Impl.java#306::apply
com/google/gwt/core/client/impl/Impl.java#345::entry0
rstudio-0.js#-1::eval
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::execute
com/google/gwt/user/cellview/client/AbstractCellTable.java#849::resources
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Process
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Push
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Typeset
rstudio-0.js#-1::eval
com/google/gwt/core/client/impl/Impl.java#306::apply
com/google/gwt/core/client/impl/Impl.java#345::entry0
rstudio-0.js#-1::eval
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::execute
com/google/gwt/user/cellview/client/AbstractCellTable.java#849::resources
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Process
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Push
http://127.0.0.1:17205/mathjax/MathJax.js?config=TeX-MML-AM_CHTML#-1::Queue
org/rstudio/studio/client/common/mathjax/MathJaxTypeset.java#56::typesetNative
org/rstudio/studio/client/common/mathjax/MathJaxTypeset.java#39::onExecute
org/rstudio/core/client/SerializedCommandQueue.java#71::executeNextCommand
org/rstudio/core/client/SerializedCommandQueue.java#59::run
org/rstudio/core/client/SerializedCommandQueue.java#36::addCommand
org/rstudio/studio/client/common/mathjax/MathJax.java#528::renderPopup
org/rstudio/studio/client/common/mathjax/MathJax.java#241::renderLatexImpl
org/rstudio/studio/client/common/mathjax/MathJax.java#224::onLoaded
org/rstudio/studio/client/common/mathjax/MathJaxLoader.java#73::withMathJaxLoaded
org/rstudio/studio/client/common/mathjax/MathJax.java#123::run
com/google/gwt/user/client/Timer.java#124::fire
rstudio-0.js#-1::eval
com/google/gwt/core/client/impl/Impl.java#306::apply
com/google/gwt/core/client/impl/Impl.java#345::entry0
rstudio-0.js#-1::eval
Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e
User-Agent: Mozilla/5.0 (X11  Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

**Comment by kevinushey** [comment]
Thanks for the bug report! Unfortunately, I'm not able to reproduce (macOS 11.0.1; RStudio 1.4.1078). For reference, this is the document I tested (typed in following instructions in the report)

`````
---
title: "Untitled"
output: html_document
---

First paragraph.

$y = f(x)$

Second paragraph.

$\textrm{Cov}(X,Y)$

$\text{Cov}(X, Y)$

Third paragraph.
`````

Entering the second and third math expressions did not effect the IDE's ability to preview equations.

**Comment by fnaufel** [comment]
Thanks for the quick response!

Upgraded to 1.4.1078 last night and could not reproduce it either.

Closing the issue, then. Sorry about that.

**Comment by kevinushey** [comment]
No worries; thanks for reporting. Feel free to re-open the issue if it resurfaces!
