### ISSUE TITLE
Python cp949 encoding error

### ISSUE THREAD

**Issue by issactoast** [rstudio/rstudio#8549]
### System details

    RStudio Edition : 
    RStudio Version : 1.4.1056
    OS Version      : Windows10
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem
print korean letters in Rstudio python py file and run
``
print("안녕")
``
### Describe the problem in detail
If I run the print Korean word using the print function, it shows the following error.
```
reticulate::repl_python()
Python 3.8.3 (C:/Users/issac/miniconda3/python.exe)
Reticulate 1.18 REPL -- A Python interpreter in R.
>>> print("안녕")
UnicodeEncodeError: 'cp949' codec can't encode character '\xc8' in position 1: illegal multibyte sequence
```
I check out the same code in miniconda python, it shows Korean 안녕 correctly.

### Describe the behavior you expected
print Korean word in console "안녕"

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Thank you for reporting this issue. I can reproduce in 1.4.1081 on Windows. 
@kevinushey do you think this is something we can get into 1.4?

**Comment by kevinushey** [comment]
I don't think this quite meets the bar for 1.4 since we're so close to release, but let's definitely fix for 1.4-JR.

**Comment by astayleraz** [comment]
I tested this in desktop Version 1.4.1514 and get the following error still `> reticulate::repl_python()
Python 3.6.12 (C:/Users/IEUser/AppData/Local/r-miniconda/envs/r-reticulate/python.exe)
Reticulate 1.18.9005 REPL -- A Python interpreter in R.
>>> print("안녕")
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
>>> print("你好")
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>`

**Comment by kevinushey** [comment]
Thanks for catching this @astayleraz: this was my fault; I have my Windows VM configured with the environment variable:

```
PYTHONIOENCODING = utf-8
```

and that is also required for this fix to be fully "done". I think this should be the default, so I'm going to update `reticulate` to make that happen.

**Comment by kevinushey** [comment]
Should now be fixed in the development version of `reticulate`, via https://github.com/rstudio/reticulate/commit/6213b15455dc76708477e5bf816775ce6c7d337e.

@astayleraz: please re-install the development version of `reticulate` with `remotes::install_github("rstudio/reticulate")`, and then run the test again; hopefully all should be well now!

**Comment by issactoast** [comment]
@kevinushey I have tested this also in RStudio version 1.4.1533 with latest reticulate! works perfect! thanks!!
