### ISSUE TITLE
Unable to print tibble in debug mode

### ISSUE THREAD

**Issue by ad2021** [rstudio/rstudio#8556]
I have the exact same issue that was described here:

https://community.rstudio.com/t/cant-print-data-frames-or-tibbles-while-in-the-debugger/51068/2

I do not see a fix for this

RStudio Server
Version 1.3.1093

> R.Version()
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.2"

$year
[1] "2020"

$month
[1] "06"

$day
[1] "22"

$`svn rev`
[1] "78730"

$language
[1] "R"

$version.string
[1] "R version 4.0.2 (2020-06-22)"

$nickname
[1] "Taking Off Again"

**Comment by ardydavari** [comment]
Looks like this issue only occurs when using Rmarkdown. Is there some sort of sink command that needs to be called prior?

**Comment by jmcphers** [comment]
This is expected behavior inside R Notebooks. While a notebook chunk is running, data frames (etc) are captured and sent to the notebook instead of the R console.

**Comment by jmcphers** [comment]
You can see where this gets set up here:

https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/NotebookData.R#L16-L27

If you need to, you can override methods like `print.data.frame` again inside the debugger so the notebook doesn't get a chance at the data.
