### ISSUE TITLE
Collapse the contents of a R6 class generator function, similar to standard functions

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/rstudio#8557]
Hi,

Just thought it might be a useful feature to offer RStudio support for collapsing/folding the contents of `R6` class generator objects (i.e. `R6::R6Class(...)`) in `R` scripts, similar to how one can fold the contents of standard functions.

`R6` classes can get long enough to consume a good amount of the Editor window, so it would be nice to be able to fold these up while working in the IDE.

**Comment by ronblum** [comment]
@mattwarkentin Thank you for the suggestion! We'll review it as we continue development of RStudio.
