### ISSUE TITLE
Rstudio crashes when running CRAN lightgbm example code, Rgui doesn't crash

### ISSUE THREAD

**Issue by tonyk7440** [rstudio/rstudio#8558]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1081
    OS Version      : Windows 10
    R Version       : 4.0.3

### Steps to reproduce the problem
Install the current preview version from: https://rstudio.com/products/rstudio/download/preview/
Open Rstudio and run the code below with the CRAN version of lightgbm
```
# install.packages("lightgbm")
library(lightgbm)

data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)

model <- lgb.train(
  params = params
  , data = dtrain
  , nrounds = 5L
  , valids = valids
  , min_data = 1L
  , learning_rate = 1.0
  , early_stopping_rounds = 3L
)
```
### Describe the problem in detail
Rstudio crashes(see image below), I tried the code via Rgui and it works fine(see other image)

![image](https://user-images.githubusercontent.com/4944073/101404194-35aed200-38ce-11eb-8995-5f4ce4021ec1.png)

![image](https://user-images.githubusercontent.com/4944073/101404258-4eb78300-38ce-11eb-8777-be186ae0fd9a.png)

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5655230/diagnostics-report.txt)

### Describe the behavior you expected

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It seems to work fine on my Windows machine. Does reinstalling the `lightgbm` package as well as its dependencies make a difference?

**Comment by tonyk7440** [comment]
Closing this as the issue also happens in the Rgui. Issues are open in the {lightgbm} repo
