### ISSUE TITLE
line wrapping in visual markdown breaks bookdown text reference

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8561]
Originally reported at: https://community.rstudio.com/t/line-wrapping-in-visual-markdown-breaks-bookdown-text-reference/90159

Hi everyone. I am using the new markdown editor in Rstudio 1.4.1056. In this I can set the line wrapping to 'sentence' (https://rstudio.github.io/visual-markdown-editing/#/markdown?id=line-wrapping ) which I think is really helpful when using it for manuscripts with a lot of text in combination with GIT version control. 

However,  a bookdown text reference with multiple sentences will break as soon as I switch to visual markdown editing, since the line wrapping is also performed on the text in the bookdown text reference block. Is there any way to circumvent this behavior and let Rstudio always perform line wrapping except for when a bookdown text reference is used?

The Rmarkdown example  below can reproduce the problem (save this code as Rmarkdown, then switch to visual markdown editing).

````markdown
---
title: "minimal example"
output: bookdown::html_document2
editor_options:
  markdown:
    wrap: sentence
---

# Plot

Reference text below with random text:

(ref:pressure) Folly words widow one downs few age every seven. If miss part by fact he park just shew. Discovered had get considered projection who favourable. Necessary up knowledge it tolerably. Unwilling departure education is be dashwoods or an.

```{r pressure, fig.cap="(ref:pressure)"}
plot(pressure)
```
````

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1087
