### ISSUE TITLE
rstudio not recognizing pandas, numpy packages on ubuntu

### ISSUE THREAD

**Issue by MahreenAthar** [rstudio/rstudio#8564]
I'm using RStudio and anaconda on the same laptop. I didn't install rstudio from anaconda-navigator, I have installed it separately from it's website. Now when i run rstudio and try to import pandas or numpy or any other library it gives this error:

![r](https://user-images.githubusercontent.com/39671939/101481466-0acc8880-3977-11eb-93fb-9850134deb8b.png)

I have both anaconda and miniconda. I have been using jupyter notebook for a while now and it works fine, the libraries get imported and everything works. How can I connect rstudio with those already installed libraries of anaconda? or do i have to install them separately using pip install?
[I posted this question on stackoverflow too](https://stackoverflow.com/questions/65198346/rstudio-not-recognizing-pandas-numpy-packages-on-ubuntu)

**Comment by ronblum** [comment]
@MahreenAthar Thank you for filing the issue! Can you please provide your system details so that we can try to reproduce the issue?


    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by MahreenAthar** [comment]
RStudio Edition : 
RStudio Version :  1.3
OS Version      : Ubuntu 18.04
R Version       : 3.4.4

**Comment by kevinushey** [comment]
Did you install the pandas package into your Miniconda environment? `reticulate::py_install("pandas")`

**Comment by MahreenAthar** [comment]
@kevinushey no i didn't install with miniconda. I have it installed with anaconda and i have used it with jupyter notebook. I was hoping if there's any way i can use the same anaconda's installed pandas with rstudio

**Comment by jmcphers** [comment]
@mahreenathar, do you also see this when using reticulate in base R? We suspect this an issue in `reticulate` itself, or in your machine's Python configuration.
