### ISSUE TITLE
Show active Python environment in the IDE

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8569]
We've received feedback from several sources that it isn't clear enough what the current Python environment is. You can find this information in Options or Project Options, and it's also available by asking reticulate via `py_config`, but there's nothing on the actual workbench itself.

As a point of reference, the VS Code plugin for Python shows the Python environment name in the lower left:

![image](https://user-images.githubusercontent.com/470418/101548589-f67d9100-3960-11eb-90ea-07e2ade65ee2.png)

We would want to show the name of the configured environment if possible (e.g., the name of the virtualenv or conda env), not just the Python version number.

**Comment by kevinushey** [comment]
A potentially lower-cost solution to this:

<img width="596" alt="Screen Shot 2021-02-08 at 10 25 45 AM" src="https://user-images.githubusercontent.com/1976582/107264603-031d7480-69f8-11eb-8bdb-fc15c1ddee45.png">

We could include the Python version at the top-right of the Console pane when the `reticulate` REPL is active. If the R REPL is active, we could instead display the active R version.

Displaying it the console in response to REPL activation frees us from having to figure out how to communicate the "selected but not yet active" version of Python.

**Comment by mikebessuille** [comment]
I like showing it in the console for when the REPL is active.  But what about when they are writing code in py files, rather than the console?  Seems to me we should be consistent about how we show this in all cases, not just REPL.

**Comment by astayleraz** [comment]
Verified currently-active interpreter in the Console pane now shows in Version 1.4.1588-2. Checked on mac and pc desktop as well as ubuntu. Rich also added a test for this. Closing issue.
