### ISSUE TITLE
Rapid scrolling before DataCite search results before the results appear might minimize the search window

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8576]
### System details

    RStudio Edition : Desktop and server
    RStudio Version : 1.4.1078 
    OS Version      : MacOS 11.1
    R Version       : 4.0.3

### Steps to reproduce the problem

It’s possible to screw up the UI with a DataCite search on Big Sur with unusual scrolling.

- Do a citation search, like “bobolink” in DataCite.
- Quickly move the pointer over the results area.
- Quick again: scroll up fast while the results haven’t come back yet—using two fingers from the bottom to the top of the trackpad. The easiest to reproduce is to just keep doing this repeatedly as you wait for the results to show up.
    - When the results should show up, they don’t. Instead, most of the modal disappears, with only a wide, short, nonworking modal with just the title “Insert Citation.”
<img width="1003" alt="citation_scrolling" src="https://user-images.githubusercontent.com/31009952/101641666-06987d80-3a00-11eb-9653-2aaa9ba1593a.png">

    - The IDE is not responsive, and needs “Force Quit” to exit.
    - (After a bit) Now it’s happening every time I use Crossref, without scrolling before results.
    - (After a little while) And now it’s fine.

### Describe the problem in detail

See above.

### Describe the behavior you expected

The results should always appear and the IDE continue to work.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
It's now happening to me in an instance of Chrome on MacOS 11.1. Reloading the page, closing and opening a new window, or closing and restarting Chrome doesn't help. My instance is current stuck with this behavior.

**Comment by ronblum** [comment]
Note: This is due to a record that came in without an author field. An example is the reference with DOI 10.3133/93888. Possibly a separate issue, technically, since it was simply having this record in the references file that cause the problem, not the rapid, repeated scrolling. (So actually I'll probably open a separate issue for the original problem.)

**Comment by ronblum** [comment]
FYI, confirmed fixed on in RStudio Desktop 1.4.1096 on MacOS Desktop and RStudio Server 1.4.1096 on Ubuntu 20.04.4 using Firefox on Ubuntu 20.04.1.

**Comment by mikebessuille** [comment]
Can we close this issue?

**Comment by ronblum** [comment]
Fixed!
