### ISSUE TITLE
JSON code sometimes sent to console when Crossref search results are returned

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8579]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1078
    OS Version      : MacOS 11.1 beta
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a markdown document in visual mode.
2. Perform a citation search using Crossref.
    - Sometimes JSON code (I think it’s JSON) shows up in the console when Crossref search results are returned.
    - I think it’s only Crossref.
    - It only happens sometimes—I haven’t figured out the pattern.

After happening several times, I haven't been able to reproduce it.

### Describe the problem in detail

Sometimes JSON code (I think it’s JSON) shows up in the console.

### Describe the behavior you expected

Nothing should get sent to the console (which is most of the time).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For posterity, can you share the JSON that you see when this happens?

**Comment by ronblum** [comment]
@kevinushey Will do! Entering <kbd>Ctrl-L</kbd> in the console was probably not the best way to investigate this issue.

**Comment by dragonstyle** [comment]
Note - I believe this was DataCite and was fixed in this commit:

https://github.com/rstudio/rstudio/commit/fa23a89efff55bd0ea12ec2915003c2a1266c185#diff-fe06442e1eaa0fb84a09e04891347ffd862db207cfcd2cbba5fd7b28d25609a3
