### ISSUE TITLE
Add Shift to "Run previous chunks" in Visual Markdown Editor documentation

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8580]
### System details

    RStudio Edition : N/A (Documentation)
    RStudio Version : N/A
    OS Version      : N/A
    R Version       : N/A

### Describe the problem in detail

In the documentation at https://rstudio.github.io/visual-markdown-editing/#/shortcuts , “Run previous chunks” should be <kbd>⇧ ⌥ ⌘ P</kbd> (Shift-Alt-Cmd-P). Currently, the Shift (⇧) is missing.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Fixed up by https://github.com/rstudio/visual-markdown-editing/commit/fd0389ade6c8652101e2367496611009e79645c0.

**Comment by kfeinauer** [comment]
@kevinushey I am on the latest Mac daily build 1.4.1087-5 (pro), and I see the re run command does not have a Shift:

![Screen Shot 2020-12-10 at 10.03.27 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/88ba3700-0068-4d02-8f38-d905135ba9ad/Screen+Shot+2020-12-10+at+10.03.27+AM.png)

Correct me if I am missing something, but now it looks like the docs are incorrect with the executable.

**Comment by kfeinauer** [comment]
Also, perhaps found another issue with Re-Run Previous. It looks like it only reruns the previous chunk if the cursor is within that chunk. If the cursor is anywhere else in the document, the chunk does not run. Is this expected? It doesn't seem so, as if that were expected we should gray out that menu item (which we don't).

**Comment by jmcphers** [comment]
That's a bug, but not one we will fix for Wax Begonia. It's tracked here: https://github.com/rstudio/rstudio/issues/8500

**Comment by kevinushey** [comment]
@kfeinauer: I think these are actually two separate commands:

https://github.com/rstudio/rstudio/blob/53f696753e78c4416266f854c671b943e4d43b88/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L817

https://github.com/rstudio/rstudio/blob/53f696753e78c4416266f854c671b943e4d43b88/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L827

Cmd+Alt+P should re-run the last-executed piece of code; Cmd+Alt+Shift+P should run all chunks prior.

**Comment by kfeinauer** [comment]
Thanks @kevinushey - as long as a chunk has focus that command does work. Is it in the menu somewhere? I don't see it.

**Comment by kfeinauer** [comment]
(Verified 1.4.1085-1)

**Comment by kevinushey** [comment]
I don't think we show the Execute Previous Chunks item as part of the global menu; AFAICS it's just part of the chunk toolbar.
