### ISSUE TITLE
Run All Chunks Above or Below executes only when inside a chunk

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8582]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.1081
    OS Version      : MacOS 11.1 beta and Red Hat 8.3
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a new R Markdown document, using the default template, in visual mode.
2. Place the cursor between the second and third code chunks.
3. Choose "Run All Chunks Above" or "Run All Chunks Below".
    - Nothing happens.
4. Click inside a code chunk.
5. "Run All Chunks Above” or "Run All Chunks Below".
    - The chunks run.

### Describe the problem in detail

"Run All Chunks Above" and "Run All Chunks Below" only executes when the cursor is inside a chunk.

### Describe the behavior you expected

These commands should work outside of chunks, as well.

This might qualify as a 1.4 Wax Begonia issue, but arguably this can be handled in Juliet Rose.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/8500.

**Comment by astayleraz** [comment]
Verified in Version 1.4.1507-1 / R 3.6.0 that the code chunks are run above and below in this case in visual mode. Closing as fixed.
