### ISSUE TITLE
Chunk results sent to console even when "Chunk Output Inline" is selected

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8583]
### System details

    RStudio Edition : Desktop or Serve
    RStudio Version : 1.2.5042, 1.3.1093, 1.4.1078
    OS Version      : MacOS 11.1 beta and Chrome pointing at Red Hat 8.3
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a new R Markdown document, using the default. Can be either source or visual mode.
2. Make sure "Chunk Output Inline" is selected.
3. <kbd>Run -> Restart R and Run All Chunks</kbd>
    - The chunks are run, with the proper inline display
    - However, the results of the `summary(cars)` is also sent to the console.

### Describe the problem in detail

Results are sent to the console even when "Chunk Output Inline" is selected.

### Describe the behavior you expected

Output is only displayed in the document, not the console, if "Chunk Output Inline" is selected.

Note that this goes back to 1.2 or earlier, so either it's something that's been overlooked for a while, or it's correct behavior. I think it's a bug.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
I'll leave this open for discussion, but it is the intended behavior. Submitting code from an R Notebook executes it at the R console, then copies (not moves) the output to the Notebook. This is intended to help reinforce the idea that the R Notebook is not a separate environment -- code executed in the Notebook shares your global environment, working directory, etc..

**Comment by ronblum** [comment]
As distinguished from knitting a file, in which that's not the case. OK, that makes sense. Closing!
