### ISSUE TITLE
Tab key inserts a tab in code chunk when "Tab Key Always Moves Focus" is selected

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8584]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.1081
    OS Version      : MacOS 11.1 and multiple browsers pointing at RStudio Server
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a markdown document in visual mode.
2. <kbd>Tools -> Global Options -> Accessibility -> Tab Key Always Moves Focus
3. Create a code chunk if one doesn't already exist.
4. Click inside the chunk.
5. <kbd>Tab</kbd>
    - The tab moves the cursor (bug)
6. Click outside of the chunk.
7. <kbd>Tab</kbd>
    - The focus is changed (correct)

### Describe the problem in detail

The tab key insert tabs/spaces.

### Describe the behavior you expected

The tab key should switch focus, not insert a tab.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
we could consider fixing this for 1.4 if the fix is low-risk

**Comment by mikebessuille** [comment]
from JJ:  the value of that pref can be read from here in typescript: https://github.com/rstudio/rstudio/blob/master/src/gwt/panmirror/src/editor/src/api/ui.ts#L128

**Comment by jmcphers** [comment]
Fixed in Juliet Rose via #8596.

**Comment by astayleraz** [comment]
I verified the tab key switches focus and does not insert a tab. Verified in Version 1.4.1507-1 RSP R version 3.6.0.
