### ISSUE TITLE
C++ compilation database needs to be invalidated when compiler updated

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8588]
### System details

    RStudio Edition : Both
    RStudio Version : All
    OS Version      : macOS 11.0.1
    R Version       : 4.0.3

### Steps to reproduce the problem

Distilled from discussion in https://github.com/rstudio/rstudio/issues/4685#issuecomment-741950741. Roughly, the steps would be:

1. Use RStudio in a project with C++ sources,
1. Close RStudio,
1. Upgrade your C++ compiler (e.g. on macOS, upgrade command line tools),
1. Re-open RStudio in that project.

### Describe the problem in detail

Diagnostics may fail to run in that project, as the cached compilation arguments + headers are no longer valid.

### Describe the behavior you expected

We should invalidate our compilation database if we detect that the compiler has been updated.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/rstudio/pull/8591.

**Comment by astayleraz** [comment]
I verified that the correct diagnostics are emitted following the steps outlined. I verified on Mac desktop Version 1.4.1572 with R 4.0.3. Closing as fixed.
