### ISSUE TITLE
Add "whole word" filter to "Find in files" 

### ISSUE THREAD

**Issue by warnes** [rstudio/rstudio#8594]
I often make use of the `Find in Files` tool. Currently, matching a whole word requires enabling `Regular expression` and adding `\b` before and after the word.

It would be helpful to have a `Whole word` checkbox, as is already present in the code editor's `Find` tool.

**Comment by mikebessuille** [comment]
leaving in 1.4-JR assuming it is low-risk

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1533
    OS Version      : mac OS 11.1
    R Version       : 4.0.2

Verified that Find in Files now has a "whole word" checkbox that causes find to only give the search results where the whole search word or entire search phrase is found. Also verified that the "whole word" checkbox and "regex" checkbox cannot be checked at the same time (if one is checked, and the other is clicked, the first is deselected and the other is selected).
