### ISSUE TITLE
Inserting a hard line break using the menu isn't inserting a trailing backslash

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8601]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.1081
    OS Version      : MacOS 11.1 and Ubuntu 20.04.1
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a markdown document in visual mode
2. In the middle of a paragraph, hit <kbd>Return</kbd>
    - The current line is split in two
    - The cosmetic blank line between the two represents a paragraph break
3. Click elsewhere in the middle of a paragraph
4. Insert a hard line break using the keyvoard shortcut <kbd>Shift-Return</kbd>
    - The current line is split
    - There is no blank line between the two, indicating a hard line break
5. Click elsewhere in the middle of a paragraph.
6. Insert a hard line break using the drop down menu : <kbd>Insert -> Special Characters -> Hard Line Break</kbd>
    - The current line is split
    - There is no blank line between the two, indicating a hard line break
7. Switch to source mode
    - There is an empty line between the two lines from step 2, for a paragraph break
    - There is a backslash ` \` at the end of the first line from step 4, for a hard line break
    - There is no empty line or trailing backslash with the lines from step 6
8. Switch back to visual mode
    - The paragraph break from step 2 is preserved (works)
    - The hard line break from step 4 (keyboard shortcut) is preserved (works)
    - The hard line break from step 6 (menu) is not preserved (bug)

Note: inserting multiple hard line breaks in step 6 will result in multiple empty lines, which are treated as a single paragraph break, like step 2.

### Describe the problem in detail

Inserting a hard line break using the menu is inserting the equivalent clicking <kbd>Return</kbd> in source mode, not the equivalent of a trailing `\`.

### Describe the behavior you expected

The menu item to insert a hard line break should adding a trailing slash (in source), the same as the shortcut.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Doesn't meet the bar currently for 1.4.   @jjallaire do you think this should be fixed urgently for 1.4-Juliet-Rose?

**Comment by astayleraz** [comment]
I verified in Daily Version 2021-07.0.285-2 I am seeing the correct trailing \ following the steps provided. Closing issue.
