### ISSUE TITLE
FR: Detect pandoc.header in document outline

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#8609]
The situation is an R Markdown document with a chunk with a loop (`for`, `while`...) inside of which I want to add section titles, so I use `pandoc.header("My section title", level = 3)`. It is great, and it would be even better if RStudio detect it and place it in some way* in the document outline. So, this is my feature request

*I say in some way, because I understand these titles cannot be well defined, since they may depend on the loop iteration, and even on the number of iterations of the loop (I use `pandoc.header` inside a `for`, but why not inside an uncertain `while` loop).
I believe it could be just shown as a unique title with the argument passed to `pandoc.header`.

Thank you!

**Comment by ronblum** [comment]
@iago-pssjd Thanks for the suggestion! We'll take a look at it as part of our ongoing development of RStudio.
