### ISSUE TITLE
Connections pane not showing

### ISSUE THREAD

**Issue by marissabarlaz** [rstudio/rstudio#8610]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : Windows 10
    R Version       : 4.0.3

### Steps to reproduce the problem
Opening R Studio and choosing the connections tab
![Capture3](https://user-images.githubusercontent.com/35778650/102096126-fa3e6700-3de9-11eb-88a1-a422924be01a.PNG)
### Describe the problem in detail
In the past month or so, all of a sudden the connections panel is empty. I cannot see any open connections, nor can I see any buttons to connect, disconnect, etc. I have not done anything I know of to change this behavior. I have tried uninstalling and reinstalling Rstudio but that did not work.

### Describe the behavior you expected
I expect the connections panel to show current and previous connections.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Can you include a diagnostics report? (there may be errors in your logs)

Does resetting RStudio's state help? (do this after generating the diagnostics report) https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by marissabarlaz** [comment]
I was able to fix the problem by deleting this file:

 .rstudio/monitored/connection-history-database.json
