### ISSUE TITLE
Shiny app crashes when running caret's predict function.

### ISSUE THREAD

**Issue by viniciusdel** [rstudio/rstudio#8611]
### System details

    RStudio Edition : Desktop
    RStudio Version :  R version 4.0.2
    OS Version      :  Windows 10 KB4592438
    R Version       :  R version 4.0.2 (2020-06-22)

### Steps to reproduce the problem
I have a trained model that gets read using readRDS, and then the predict function is called in a hosted shiny app:
https://viniciusdel.shinyapps.io/deploy/

### Describe the problem in detail
The problem is that the first predict function (using RandomForests) works for the first tab, but the second predict (using caret) makes the system crash. I checked the logs and this is what it tells me:

'Warning: Error in UseMethod: no applicable method for 'predict' applied to an object of class "c('train', 'train.formula')"'

### Describe the behavior you expected
The shiny application crashes when running a prediction of the caret package.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@viniciusdel Thank you for raising the issue! I'll mark it for review as we continue development of RStudio. Is this what leads to the "Disconnected" issue when clicking "Submit" on the Personal Medical Insurance Costs and Diabetes tabs?
<img width="299" alt="shiny" src="https://user-images.githubusercontent.com/31009952/102135958-be75c280-3e26-11eb-89e9-3a03daea836b.png">

**Comment by viniciusdel** [comment]
Hello! Thank you for the reply. 

I am not 100% sure, but it seems that this is what causes it, yes. All the logs mention is the line where the predict() function is called. This, however, doesn't happen with the predict from RandomForests, just caret.

I wonder if it has anything to do with that.

**Comment by jmcphers** [comment]
This is an issue on shinyapps.io, not with the core IDE. Please open a thread there if you're still having trouble:

https://community.rstudio.com/c/shiny/shinyappsio/24
