### ISSUE TITLE
C/CPP code blocks don't look like they're inserted and prevent from switching back to visual mode

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8618]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1088
    OS Version      : MacOS 11.1
    R Version       : 4.0.3

### Steps to reproduce the problem

Starting with visual mode:
1. Open a new R markdown file in visual mode.
2. Insert a new code block: <kbd>Insert -> Code Block</kbd>.
3. Choose `c` or `cpp` as the language and click "OK".
    - Issue 1: It looks like nothing happened.
4. Switch to source mode.
    - Actually, a code block did get entered:
````
``` {.cpp}
```
````
5. Switch back to visual mode.
    - Issue 2: An error message modal appears.
    - Pressing "OK" takes you back to source mode.
    - The only way back to visual mode is to remove the code block or to change it to something else, like `.html` or `.awk`.

### Describe the problem in detail

Issue 1: Entering a C or CPP code block looks like nothing happened.
Issue 2: A C or CPP code block in source mode will prevent you from switching to visual mode.

Note: I'm marking this as two related issues, since starting in source mode and writing the code block manually will also prevent you from switching to visual mode.

### Describe the behavior you expected

C and CPP code blocks should be shown in visual mode and not prevent you from switching to visual mode. 

Two notes:
1) This appears to be limited to RStudio Desktop on MacOS. It works in:
    - RStudio Desktop on Ubuntu 20.04.1
    - RStudio Server using Chrome and Firefox on MacOS
    - RStudio Server using Chrome on Ubuntu 20.04.1
    - I haven't tried it on Windows.
2) There are several dozen possible languages, and I haven't looked at them all—I've only looked at a quasi-random sample. It works for other types, like `r`, `html`, `awk`, and `bash`. If there are others that I should look at as possible candidates for error, let me know (or, I can test all of them if you'd prefer).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Jonathan, this yours?  or JJ?

**Comment by jmcphers** [comment]
This one (and https://github.com/rstudio/rstudio/issues/8617) are technically JJ, but I can take a look if he doesn't have time.

**Comment by ronblum** [comment]
Confirmed in RStudio Desktop 1.4.1096 on MacOS 11.1.
