### ISSUE TITLE
Stale RStudio `latest` build links

### ISSUE THREAD

**Issue by pkq** [rstudio/rstudio#8633]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1095
    OS Version      : macOS 11.0.1
    R Version       : 4.0.3

### Steps to reproduce the problem
Request a stable installer URL (e.g., `wget https://rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg`) and compare the version downloaded to the corresponding daily version (e.g., https://dailies.rstudio.com/rstudio/oss/mac/)

### Describe the problem in detail
As of this writing, the stable installer URL for Mac downloads RStudio-1.3.1095.dmg, whereas the latest Mac daily is listed as RStudio-1.4.1095.dmg. This issue was [first reported](https://community.rstudio.com/t/stale-rstudio-latest-build-links/76827) on RStudio Community back in August, but despite several attempts by @jmcphers to resolve the issue, it still appears (at least partially) broken.

### Describe the behavior you expected
Per https://support.rstudio.com/hc/en-us/articles/203842428-Getting-the-newest-RStudio-builds, the stable installer URLs should download the latest build of the version requested.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Aron also seeing this internally.

**Comment by mikebessuille** [comment]
Does not block 1.4 release

**Comment by pkq** [comment]
Much appreciated!

**Comment by aronatkins** [comment]
Confirmed that `https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg` redirects to https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.4.1099.dmg

**Comment by valerie-rstudio** [comment]
### Verified Fixed

Verified that the https://rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg link now downloads the most up to date version of the RStudio daily build.
