### ISSUE TITLE
Python version not aligned when publishing reticulate apps

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8636]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1093 

### Steps to reproduce the problem

1. Create a Python virtual environment. 
2. In Project Options, tell RStudio to use the virtual environment as the active Python interpreter.
3. Install one or more Python packages.
4. Create an R Markdown document that emits the Python version via `reticulate::py_config()`
5. Knit the document and examine the Python version
6. Publish the document to RStudio Connect
7. View the document on RStudio Connect

### Describe the problem in detail

The Python versions do not match; nor do installed packages. This can break the R Markdown document (or Shiny app, etc.). 

### Describe the behavior you expected

Python versions should match.

This bug exists because the IDE does not pass any information about the active Python version to the subprocess used to publish content. 

The IDE calls `deployApp` here:

https://github.com/rstudio/rstudio/blob/df886df0ffb0bc8a7ab056470265f9f5682bb34e/src/cpp/session/modules/SessionRSConnect.cpp#L175

There are a couple of ways it could pass the Python environment correctly when deploying; likely the best is for it to use the `python` arg to `deployApp`:

https://github.com/rstudio/rsconnect/blob/3b04a6d1e41bd7262bfe58a7cddb7b954f180d2c/R/deployApp.R#L62-L66

**Comment by jmcphers** [comment]
Notes/thoughts:

- `reticulate::py_config()` will return useful info including the path to the Python interpreter.
- We should check `reticulate::py_available(initialize = FALSE)` prior to calling `reticulate::py_config()` so we don't accidentally force all the bindings to initialize as a side effect.
- Passing `python` directly as an argument will make it impossible to override; maybe we want to set `RETICULATE_PYTHON` instead? It could be forwarded as-is if it already exists, and derived from `reticulate::py_config()$python if not.

**Comment by kevinushey** [comment]
You can also use `py_discover_config()` to figure out which version of Python reticulate would bind to if Python isn't actually initialized it, but the user has instructed `reticulate` to use a particular version of Python (e.g. via `RETICULATE_PYTHON` or one of the `reticulate::use_python()` helpers).

So the scaffolding would basically be:

```
if (reticulate::py_available(initialize = FALSE) {
  # python already loaded; use py_config()
} else {
  # python not yet loaded; infer based on py_discover_config()
}
```

**Comment by jmcphers** [comment]
> You can also use py_discover_config() to figure out which version of Python reticulate would bind to

I started playing with this, but discovered that this method prompts to install miniconda in some cases (which we obviously don't want here as we're after passive detection). Is there a way to turn that off that doesn't require some fudging to make `reticulate::is_interactive()` false?

**Comment by kevinushey** [comment]
You can also set `Sys.setenv(RETICULATE_MINICONDA_ENABLED = "FALSE")` to disable that prompt. (I think technically setting that only disabled the auto-install prompt; `reticulate` will still use an existing Miniconda installation if available and no other Python version has been requested)

**Comment by astayleraz** [comment]
I verified on a mac with Version 1.4.1533 I was able to successfully publish a rmd file with no issues or errors in the deploy console. Closing as fixed.
