### ISSUE TITLE
Can't insert a code chunk in a footnote

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8643]
### System details

    RStudio Edition : Desktop or Server 
    RStudio Version : 1.4.1093
    OS Version      : MacOS 11.1 and Red Hat 8.3 (and others)
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Create a footnote.
2. Try to insert a code chunk using one a shortcut, menu, or with ` ``` `.

### Describe the problem in detail

Nothing happens. It's not possible to insert a code chunk.

### Describe the behavior you expected

Consider allowing a code chunk in a footnote. When using the source code with a code chunk in a footnote, the code will get processed and the results will be displayed in the rendered document. Consider this permissible in visual mode. I don't know if this is a likely placement for a code chunk, but it is permissible, so I'm tagging this for consideration in Juliet Rose.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@jjallaire Is this something you'd like to consider?

**Comment by jjallaire** [comment]
While the pandoc schema allows for this, currently if we enable it it will mess up our calculations that match visual editor code chunks with source editor scope tree chunks (because there will be "extra" chunks in the footnotes and we furthermore need to order them correctly as footnotes can appear either immediately after blocks or at the end of the document in source mode.
