### ISSUE TITLE
Quicklook for 

### ISSUE THREAD

**Issue by lewkrr** [rstudio/rstudio#8646]
It would be nice to have all R Studio installations automatically install quickook support on Macs.  A [developer made one several years ago](https://github.com/hrbrmstr/QuickLookR), but it has not been updated and is no longer supported by MacOS.  Perhaps R Studio would be able to keep this up to date.  It is certainly a great feature for R and Rmd files.

**Comment by ronblum** [comment]
@lewkrr Thank you for the suggestion! We'll review it as we continue development of RStudio. We also count on users creating add ons, packages, etc., especially in this case which is more broadly for R. I see that you filed an issue at the repository for it, which is the the right thing to do. :)
