### ISSUE TITLE
Continuous clicking the up arrow in a markdown file generates an innocuous error in the terminal

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8648]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1094
    OS Version      : openSUSE 15.2, Ubuntu 20.04.1
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Run RStudio from the command line in a terminal window.
2. Open an R markdown document in visual mode.
3. Click on the up arrow till reaching the top and getting the gap cursor.
4. Keeping clicking on the up arrow.

### Describe the problem in detail

The following error is written to the terminal:
`"Uncaught RangeError: Position -1 out of range"`

### Describe the behavior you expected

No error should be displayed. Note that this isn't causing any problems. The workaround is to stop the meaningless repeated clicking of the up arrow once at the top of the file.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
This is actually happening inside prosemirror (our code is not on the stack) so not much we can do about it. I think we should "won't fix" this one.

**Comment by astayleraz** [comment]
Closing issue as won't fix as this is not an issue on our end.
