### ISSUE TITLE
Add native support for Apple's ARM chips (arm64, M1) to RStudio for macOS

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8652]
R and RStudio work today on the M1 chip, albeit with compromised performance, via [Rosetta2](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment), an emulation layer. This issue tracks the work needed to add native support for Apple's new ARM-based silicon to RStudio. 

- We should do this as a [universal binary](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary), supporting x86_64 and arm64 without requiring a separate download. Thankfully it is possible to build arm64 binaries on x86_64 hardware. The only downside of this approach is that it will make the binary enormous (as we will ultimately ship x86_64 and arm64 versions of Chromium).
- Our build infrastructure will need to be updated to the latest version of Xcode to get support for cross-compiling to arm64.
- Because we load R as a library, we need to wait for R itself to be ported to Apple silicon before RStudio can be fully ported. This is in the works, but currently held up due to dependencies on tooling further upstream. See [Will R Work on Apple Silicon?](https://developer.r-project.org/Blog/public/2020/11/02/will-r-work-on-apple-silicon/) from the R Core team.  (Update: It works now. https://mac.r-project.org/)
- On the front end, we depend on QtWebEngine, which also does not build for M1 (see [QT-85279](https://bugreports.qt.io/browse/QTBUG-85279)). This should not be an issue since we hope to move to Electron (https://github.com/rstudio/rstudio/issues/7389), which [supports M1 as of the 11.0 release](https://www.electronjs.org/blog/apple-silicon). 
- Several binaries we bundle will have to continue to run under Rosetta2 since they don't have M1 ports available and won't for the foreseeable future. See e.g., https://github.com/jgm/pandoc/issues/6960

Other useful links

- @hrbrmstr's field report: https://rud.is/b/2020/11/18/apple-silicon-big-sur-rstudio-r-field-report/
- Benchmarking performance of R/RStudio under Rosetta2: https://forums.macrumors.com/threads/data-science-r-and-spss-26-etc-under-rosetta-2-apple-silicon-m1.2269302/?post=29326680#post-29326680
- Does It Arm: RStudio: https://doesitarm.com/app/rstudio/
- r-devel (R 4.1) macOS builds with native ARM binaries: https://mac.r-project.org/

**Comment by elbamos** [comment]
Now that there's a stable R 4.1-devel binary for Apple Silicon, is there anything people can do to be helpful in moving this issue forward? 

(If I might suggest, more important than making a universal binary, is making an Apple Silicon binary that is capable of loading either an x86_64 or osx_arm64 R binary.  I don't think people would be bothered by the effort of choosing the frontend appropriate to their architecture when they download.  A greater concern is whether I will still be able to use RStudio with both the most current R and older R versions still resident on my system.)

**Comment by mattwaltbriggs** [comment]
RStudio depends on gdb. Without an M1 port of gdb, compilation is a no-go. (Correct me if I'm wrong.)

**Comment by elbamos** [comment]
RStudio could help tide us over if you made available linux aarch64 debian packages that could be included in a docker...

**Comment by jmcphers** [comment]
@elbamos We are tracking the Linux support for this architecture in https://github.com/rstudio/rstudio/issues/8809.

**Comment by elbamos** [comment]
I have rstudio server compiling on OS X with M1.  Note that pandoc must be added manually and crashpad must be disabled.  But I get 

```
dyld: Symbol not found: _GEkillDevice
  Referenced from: /opt/rstudio-server/bin/rsession
  Expected in: flat namespace
 in /opt/rstudio-server/bin/rsession
``` 

On verify-installation

I'm tracking my progress here:  https://github.com/elbamos/rstudio/tree/feature/m1

**Comment by mikebessuille** [comment]
Using this issue to track native M1 support for the whole RStudio IDE, not just running RSessions.  Sessions with native M1 version of R will be supported in 1.4-Juliet-Rose.

**Comment by gtamayo59** [comment]
I am beginning to think that my purchase of M1 Mac mini was a mistake. I can not run anything!  R and Rstudio and all other free softwares that run over R....  I am not a programmer, I am just an user and love Mac for being user-friendly. 
My big question:  is there any serious development towards writing and R and Rstudio package ready to be installed in M1 Macs? Or even, ARM64 Windows?

**Comment by kevinushey** [comment]
The daily builds of RStudio support arm64 builds of R: https://dailies.rstudio.com

**Comment by mshamash** [comment]
@gtamayo59 There is also a stable version of R 4.0.3 available via miniforge (or just conda-forge channel) which is native for M1/arm64 macs and will work with daily builds of RStudio linked above

**Comment by gtamayo59** [comment]
> @gtamayo59 There is also a stable version of R 4.0.3 available via miniforge (or just conda-forge channel) which is native for M1/arm64 macs and will work with daily builds of RStudio linked above
> 
> ```
> > version
>                _                           
> platform       aarch64-apple-darwin20.0.0  
> arch           aarch64                     
> os             darwin20.0.0                
> system         aarch64, darwin20.0.0       
> status                                     
> major          4                           
> minor          0.3                         
> year           2020                        
> month          10                          
> day            10                          
> svn rev        79318                       
> language       R                           
> version.string R version 4.0.3 (2020-10-10)
> nickname       Bunny-Wunnies Freak Out  
> ```

For a non-verse programmer nor unix user, it seems complicated. Any recipe direction will be great!  A wiki document (kind of "for dummies" will be appreciated!  I tried following your directions (OK, I got it, I need to install first R. But this (https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#g_t_0060Apple-Silicon_0027) it is impossible for me, to deduct what I need to do first. Download the Xquartz, downloaded the Darwin.20-arm64.tar, which in turn downloaded R and from there, I went nowhere.

**Comment by mshamash** [comment]
@gtamayo59 you should be able to download the R 4.2.0 beta installer (R-devel 4.2.0 Under development, r80216) from this link: https://mac.r-project.org/#nightly
Then just run through the installer and you should have native arm64 R installed - without the hassle of compilation!

**Comment by mshamash** [comment]
@gtamayo59 if you want to use latest stable version of R (4.0.5, 2021-03-31, Shake and Throw) here is a small guide which is basically what I followed:

- Install homebrew by running the one command they list on their website (https://brew.sh/)
- Run the command `brew install r` from your Mac's Terminal
- Run the command `sudo mkdir /usr/local/bin && sudo ln -s /opt/homebrew/bin/R /usr/local/bin/R` [this is a workaround since RStudio doesn't look in the homebrew for ARM folder by default, so we make a shortcut]
- Open RStudio (latest daily build from here https://dailies.rstudio.com/) and run the version command in the R command line to make sure the arch is aarch64, and you are running version 4.0.5

**Comment by gtamayo59** [comment]
@mshamash, great!  One quick question:  do I have to make a daily re-build of RStudio?

**Comment by mshamash** [comment]
@gtamayo59 You shouldn't *have to* per se, but there will be new daily builds available at the rstudio dailies link, every day. These kinds of builds are usually bleeding-edge so may have some bugs, but I think the next version of RStudio (v1.4 juliet rose) which should be released end-April/early-May will have support for ARM RSessions by default, so once that's out you can just switch to that version of RStudio instead of daily builds. Hope that was clear enough!

**Comment by gtamayo59** [comment]
@mshamash, checking on the R.version, I see the report:
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.5                         
year           2021                        
month          03                          
day            31                          
svn rev        80133                       
language       R                           
version.string R version 4.0.5 (2021-03-31)
nickname       Shake and Throw       

It seems that I download a wrong version of R or RStudio, as the platform was not recognized

**Comment by mshamash** [comment]
@gtamayo59 Looks like you have the Intel version of R installed, maybe in addition to the ARM version, but RStudio is only choosing one to work with. It should still work fine with all your packages though (in theory), since macOS' Rosetta translation layer is really great, but if you want to continue setting up the native ARM version only, then feel free to reach out to me by email (on my GitHub profile I have my personal webpage link, email at the bottom) - just so we don't keep alerting everyone in this thread.

**Comment by astamm** [comment]
Hi all,
I was wondering if there was any progress and if you were planning on releasing a native ARM version of RStudio anytime soon. Thanks for all the hard work you put in RStudio. I've been using it for more than a decade and really enjoy what it has become!

**Comment by mikebessuille** [comment]
@astamm , sessions can now be run natively on an M1 processor as part of our build, as of Juliet Rose which was released in May 2021.  Give that the IDE itself works well using apple's translation layer, we don't expect to release the rest of the IDE in native mode for awhile, late 2022 at the earliest.

**Comment by astamm** [comment]
Thanks @mikebessuille . I was indeed talking about the IDE itself. I was trying to avoid as much as possible having to resort to Rosetta2 because I feel like it's a pity having M1 processors and not fully taking advantage of them, but, given the timeline you are announcing, I might fall back to it for the time being. Thanks anyway for the quick follow-up.

**Comment by mikebessuille** [comment]
The vast majority of performance gain you will see from an M1 chip is when running R code, and the R session is already native on the M1, so additional performance improvements by making the IDE itself native will be relatively small in comparison.

**Comment by astamm** [comment]
Thanks for this remark. That's what I thought as well. I am going to proceed with the installation of RStudio through Rosetta2 and keep enjoying your work!

**Comment by gtritchie** [comment]
We will use this issue to track confirming that all components other than the IDE itself are M1 native.

For the IDE itself (the desktop app and the rsession), that's tracked in: #10116.

**Comment by marko-asplund** [comment]
Any progress on this?

**Comment by kevinushey** [comment]
The latest releases of RStudio support arm64 builds of R. Work is ongoing to produce arm64-native builds of RStudio.

**Comment by kevinushey** [comment]
This has technically been implemented, but I guess we'll want to wait until we start publishing preview builds of RStudio with Electron until we officially consider it closed?

**Comment by mikebessuille** [comment]
@kevinushey I think this should be in Test, since the work is done to create the build.

**Comment by gtritchie** [comment]
Closing, we've been producing universal Mac builds of RStudio Electron for months now. They aren't prominently linked yet, but people have been finding them.

**Comment by elbamos** [comment]
Can you provide some advice for finding them? @gtritchie

**Comment by elbamos** [comment]
Runs great so far! New icon looks yucky like a Microsoft icon.

**Comment by gtritchie** [comment]
The new icon isn't specific to Electron. See https://github.com/rstudio/rstudio/issues/8395 for more on that saga.
