### ISSUE TITLE
Cmd-U underlines, but Cmd-U does not un-underline.

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#8656]
RDP 1.4.1099-1 (RC)

Open an RMD in Visual Markdown mode.  
Select some text
Cmd-B bolds the selection; Cmd-B again unbolds it.
Cmd-i works. too.
Cmd-U underlines the selection, but another Cmd-b does not un-underline it.  However, the Underline button in the toolbar does correctly remove the underline.

There's a workaround so I'm not keen on including it in 1.4.   However, I can see the case being made that it's critical functionality given the importance of Visual Markdown and how common it will be.

**Comment by mikebessuille** [comment]
@jjallaire - leaving this OUT of 1.4 for now, so we can proceed with testing the RC.  But I can see this potentially needing to be fixed for 1.4 considering how often this could occur.  It's low severity, but high priority.  THere is a clear workaround (use the button in the toolbar).   I would suggest looking into it and if the fix is trivial / obvious / low risk, then we can consider for 1.4, but otherwise it's probably not that big of a problem to just fix it for 1.4-Juliet-Rose.

**Comment by jmcphers** [comment]
This appears to be a problem with the key binding and not the command itself. On this line:

https://github.com/rstudio/rstudio/blob/c200d146e0fc40f4cb30819210457dc4a6028c72/src/gwt/panmirror/src/editor/src/marks/underline.ts#L57

If I supply a key binding (`[]` => `['Mod-u']`) then everything works as expected. I suspect there's a reason we don't use a binding here but I'm not sure what it is.

**Comment by jmcphers** [comment]
Indeed this shortcut was removed intentionally: https://github.com/rstudio/rstudio/commit/87cdf0b17652be6dd77643cebcc3fbb5bcec81f4

So the mystery isn't why Cmd+U isn't reversible, it's why it works in the first place.

**Comment by jjallaire** [comment]
Fixed via #8663

**Comment by jjallaire** [comment]
Re-opening until the PR is merged into juliet-rose.

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 1.4.1507 on MacOS 11.1
- RStudio Server 1.4 on Red Hat 8.3 from Chrome on MacOS 11.1

The shortcut is only for MacOS, but double-checked that there's no change to button behavior in RStudio Desktop 1.4.1514 on Ubuntu 20.04.
