### ISSUE TITLE
add '.renvignore' to allow list for Files pane lister

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8658]
https://github.com/rstudio/rstudio/blob/7c0a954d57ddda43f649332b88e98202885aa85e/src/cpp/session/SessionModuleContext.cpp#L1941-L1955

**Comment by colearendt** [comment]
Is it possible to make this user-extensible, toggleable, or just remove the functionality altogether? I find this to be a perpetual source of confusion for me. I have all sorts of `rstudioapi::navigateToFile`, `cat file`, workarounds for this feature in my personal workflow.

**Comment by kevinushey** [comment]
It can indeed be toggled:

<img width="522" alt="Screen Shot 2020-12-23 at 1 56 59 PM" src="https://user-images.githubusercontent.com/1976582/103039861-c1f40280-4526-11eb-88a6-6dffab96bb76.png">

I think we have a separate issue covering whether this should be configurable.

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/3221.

**Comment by mikebessuille** [comment]
Assuming this is a trivial change, for Juliet-Rose

**Comment by ronblum** [comment]
@jmcphers Can we make this case-insensitive? We're not hiding files like `.Rhistory` and `.Renviron` because the *R* is uppercase.

**Comment by jmcphers** [comment]
Not sure I understand the comment -- it already is case insensitive, and we should not hide those files by default since they are on the allow list.

**Comment by ronblum** [comment]
Ah—the problem isn't with this. It's a problem with renaming hidden files on MacOS where the only change is to casing (not a problem on Linux). I'll file a separate issue for it. This issues seems to work (from what I've looked at so far.)

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 1.4.1572 on MacOS 11.3
- RStudio Server 1.4.1758 on Ubuntu 20.04.2 using Chrome on MacOS 11.3
