### ISSUE TITLE
Define installation dependencies for Debian 10 Buster

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#8660]
Since you offer .deb files for Debian 10, it would be possible for you to define a `dependencies\linux\install-dependencies-buster` file for those of us who want to compile from source on a Debian 10 based distribution?
Using the install-dependencies-stretch file is not straight forward since there are some package incompatibilities and missing package versions on the list, also, I don't know if the old package versions are actually required on Buster for RStudio server to work.

**Comment by ronblum** [comment]
@andresrcs Thank you for bringing this up! I'll mark it as a bug to review.

**Comment by andresrcs** [comment]
On a related matter, could you check if your dependencies scripts are up to date? I have noticed that when RStudio Server is installed from a .deb file `sentry-cli` doesn't get installed, but when compiling from source, `dependencies/common/install-common` installs it, and If I simply comment `"#./install-sentry-cli"` on it, RStudio compiles successfully, so, I suspect is not actually required.
