### ISSUE TITLE
pasting cells from mac excel results in both a table and an image

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8665]
### System details

    RStudio Edition : Mac OS X Desktop
    RStudio Version :  1.4.1100
    OS Version      : 10.15.5
    R Version       : 4.0.2

### Steps to reproduce the problem

From @mine-cetinkaya-rundel:

If I copy a cell from an Excel file into the visual editor, it pastes the contents twice — once as text and once as an image (and places the image in an images folder in the directory). I imagine the text being pasted as image isn’t desirable?

From @ronblum:

FWIW, I tried it out in RStudio Desktop and a few combinations of browser/RStudio Server on MacOS 11.1 Big Sur beta, Windows 10, and Ubuntu 20.04.1, and the only place I can reproduce this is with desktop on MacOS

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Reopening and assigning to Verifying state per new bug workflow

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1532
    OS Version      : mac OS 11.1
    R Version       : 4.0.2

Verified that pasting a cell value from Excel into the Visual Markdown Editor now only pastes the text and not also an image of the cell.
