### ISSUE TITLE
RStudio installation broken in openSUSE Tumbleweed v.20201227: libboost v.1.74 needed, only v.1.75 available

### ISSUE THREAD

**Issue by tdEmpl064** [rstudio/rstudio#8667]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.1073-3.1
    OS Version      : OpenSUSE Tumbleweed v.20201227
    R Version       : 4.0.3-39.44

### Steps to reproduce the problem

In a system equipped as above, when attempting to install RStudio as root user:

```
# zypper in rstudio
Retrieving repository 'Science' metadata .................................[done]
Building repository 'Science' cache ......................................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...
Problem: nothing provides libboost_program_options.so.1.74.0()(64bit) needed by rstudio-1.3.1073-3.1.x86_64
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tdEmpl064 Thank you for raising the issue! Technically, only support LTS versions of operating systems, which in this case would be openSUSE Leap 15.2. However, I'll leave this open, 1) to be prepared in case this becomes an issue with future updates to Leap, and 2) in case there's anything we can do with Tumbleweed.

**Comment by dcermak** [comment]
> 2) in case there's anything we can do with Tumbleweed.

Could you please make a new release or tag a pre-release? Currently we cannot build the latest stable release of rstudio on Tumbleweed because https://github.com/rstudio/rstudio/pull/8042 has not made it into a release yet, but Tumbleweed updated pandoc to >= 2.11. At this point rstudio cannot be even installed anymore, because the last successful build is now a few months old and it's dependencies are no longer in the repositories.

**Comment by tdEmpl064** [comment]
> @tdEmpl064 Thank you for raising the issue! Technically, only support LTS versions of operating systems, which in this case would be openSUSE Leap 15.2. However, I'll leave this open, 1) to be prepared in case this becomes an issue with future updates to Leap, and 2) in case there's anything we can do with Tumbleweed.

@ronblum You are very welcome. I was surprised to see installation break for the specific reason. Maybe there could be an RStudio nightly drop where the dependency on the libboost_* libraries is relaxed beyond the strict demand for v. 1.74 to allow for installation with the newer libboost_* v.1.75?...
True, I'm certainly unaware about what the libboost increment may include, but I was wondering whether the fix might be something as simple as modifying the RStudio RPM spec file to have a dependency on libboost_* >= 1.74 so the installation can be enabled on Tumbleweed, too.
Thank you either way. I only recently had to reside to OpenSUSE Tumbleweed so the discrepancy was an unfortunate but easy catch for me.

**Comment by dcermak** [comment]
> > @tdEmpl064 Thank you for raising the issue! Technically, only support LTS versions of operating systems, which in this case would be openSUSE Leap 15.2. However, I'll leave this open, 1) to be prepared in case this becomes an issue with future updates to Leap, and 2) in case there's anything we can do with Tumbleweed.
> 
> @ronblum You are very welcome. I was surprised to see installation break for the specific reason. Maybe there could be an RStudio nightly drop where the dependency on the libboost_* libraries is relaxed beyond the strict demand for v. 1.74 to allow for installation with the newer libboost_* v.1.75?...
> True, I'm certainly unaware about what the libboost increment may include, but I was wondering whether the fix might be something as simple as modifying the RStudio RPM spec file to have a dependency on libboost_* >= 1.74 so the installation can be enabled on Tumbleweed, too.
> Thank you either way. I only recently had to reside to OpenSUSE Tumbleweed so the discrepancy was an unfortunate but easy catch for me.

If you are installing rstudio from the opensuse repositories, then this is not possible for the reasons that I outlined in https://github.com/rstudio/rstudio/issues/8667#issuecomment-754094717 (rstudio cannot be build in Tumbleweed for months now).

**Comment by kevinushey** [comment]
RStudio currently bundles and builds against Boost 1.69:

https://github.com/rstudio/rstudio/blob/7b0ab620deb7c3be75362357574fe19123e81a68/src/cpp/CMakeLists.txt#L199-L202

and those building RStudio can configure the version of Boost used (or whether to link to the system version of Boost) via `RSTUDIO_USE_SYSTEM_BOOST`:

https://github.com/rstudio/rstudio/blob/7b0ab620deb7c3be75362357574fe19123e81a68/src/cpp/CMakeLists.txt#L204-L207

The fact that 1.74 is being requested but is not found makes me believe that something independent is configuring the version of Boost to be used here.

@dcermak: we're preparing a release of RStudio 1.4 with an updated version of Pandoc, so this should be resolved very soon.

**Comment by tdEmpl064** [comment]
I see; thank you all very much for the information and the insight!

**Comment by dcermak** [comment]
> @dcermak: we're preparing a release of RStudio 1.4 with an updated version of Pandoc, so this should be resolved very soon.

Any rough ETA?

**Comment by jmcphers** [comment]
We're currently in Release Candidate status, so probably ~2 weeks.

**Comment by dcermak** [comment]
Jonathan <notifications@github.com> writes:

> We're currently in Release Candidate status, so probably ~2 weeks.

Awesome, thank you!

**Comment by tdEmpl064** [comment]
A quick note to acknowledge that I was able to install RStudio Desktop v.1.4.1103 and run it fine on OpenSUSE TumbleWeed. Thank you all again very much for the discussiona and your efforts.

**Comment by daniellga** [comment]
Hi, I have the same problem on OpenSuse Tumbleweed when trying to install rstudio 1.4.1717-2.2 from the main repository (OSS) :

```
Problem: nothing provides 'libboost_filesystem.so.1.76.0()(64bit)' needed by the to be installed rstudio-1.4.1717-2.2.x86_64
 Solution 1: do not install rstudio-1.4.1717-2.2.x86_64
 Solution 2: break rstudio-1.4.1717-2.2.x86_64 by ignoring some of its dependencies
```

**Comment by usuallycwdillon** [comment]
I can confirm that this broke again when I updated from rstudio-1.4.1717-1.x to the rstudio-1.4.1717-65.1 in the Tumbleweed repositories on 03 October.  

I uninstalled from repos and installed a downloaded rpm from the rstudio page (usually a good solution). The rpm installs silently and can be run from the icon, but produces a blank window that needs to be killed to close.
