### ISSUE TITLE
unable to git commit in v1.4-juliet-rose 

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8669]
### System details

    RStudio Edition : RStudio Desktop and Server Dev
    RStudio Version : v1.4-juliet-rose branch
    OS Version      : OSX 10.15.5
    R Version       : 4.0.2

### Steps to reproduce the problem

Attempt to git commit. Nothing happens and the following client side exception occurs:

```
30 Dec 2020 10:31:05 [rserver] ERROR CLIENT EXCEPTION (rsession-jjallaire): (TypeError) : Cannot read property 'limitVisibleConsole_1_g$' of null;
rstudio-0.js@146#229093::ShellWidget.ShellWidget
rstudio-0.js@20#597742::ConsoleProgressWidget
rstudio-0.js@24#597467::ConsoleProgressDialog.createDisplayWidget
rstudio-0.js@29#160701::ProgressDialog.ProgressDialog
rstudio-0.js@23#160689::ProgressDialog.ProgressDialog
rstudio-0.js@23#597394::ConsoleProgressDialog.ConsoleProgressDialog
rstudio-0.js@30#597421::ConsoleProgressDialog
rstudio-0.js@4#613302::GitReviewPresenter$17$4.onResponseReceived
rstudio-0.js@8#613286::GitReviewPresenter$17$4.onResponseReceived
rstudio-0.js@24#202081::ConsoleProcess$ConsoleProcessFactory.connectToProcess
rstudio-0.js@85#313210::RemoteServer$ConsoleProcessCallbackAdapter.onResponseReceived
rstudio-0.js@8#313200::RemoteServer$ConsoleProcessCallbackAdapter.onResponseReceived
rstudio-0.js@36#313172::RemoteServer$8.onResponseReceived
rstudio-0.js@18#311926::<anonymous>
rstudio-0.js@28#24557::apply
rstudio-0.js@16#24616::entry0
rstudio-0.js@14#24595::onResponse
rstudio-0.js@25#312852::RemoteServer$1ResponseHandler.performCallback
rstudio-0.js@10#312846::RemoteServer$1ResponseHandler.onResponseReceived
rstudio-0.js@36#313042::RemoteServer$5.onResponseReceived
rstudio-0.js@38#132741::RpcRequest$1.onResponseReceived
rstudio-0.js@17#43285::Request.fireOnResponseReceived
rstudio-0.js@28#43634::RequestBuilder$1.onReadyStateChange
rstudio-0.js@18#93252::<anonymous>
rstudio-0.js@28#24557::apply
rstudio-0.js@16#24616::entry0
rstudio-0.js@14#24595::<anonymous>
Client-ID: 8335ef46-a223-4d52-bbbb-241a3b1293f3
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by adamconroy** [comment]
Looks like there's Injection conditions where an empty prefs is passed in. Easy fix.

**Comment by gtritchie** [comment]
Fixed in juliet-rose via: #8682

**Comment by adamconroy** [comment]
Weird, the auto close with "Fixes X" didn't seem to work.

**Comment by jmcphers** [comment]
@adamconroy Bugs are only auto closed when their fixes are merged to the primary branch.

**Comment by astayleraz** [comment]
I verified I was able to do a git commit on mac osx 10.15.17 and mac desktop version Version 1.4.1527 and R 4.0.3. Closing as fixed.
