### ISSUE TITLE
Rstudio 1.4 - Visual editor - option to close code chunks

### ISSUE THREAD

**Issue by WattsMatthew** [rstudio/rstudio#8672]
It would be really useful to have an option in the visual editor to close code chunks, so you only get the output only i.e. a table or figure. This feature is available in the usual R-markdown view. For example, I'm currently writing a paper using in visual editor mode, i'm done with all the code and don't need to see it anymore - so the code chunks get in the way.

**Comment by ronblum** [comment]
@WattsMatthew Thank you for the suggestion! We'll review it as we continue development of RStudio.

**Comment by ronblum** [comment]
Pinging this to unstale it—I think we should still consider this. I'll mark it as "Later," though.

**Comment by jjallaire** [comment]
Closing as duplicate of https://github.com/rstudio/rstudio/issues/8613
