### ISSUE TITLE
e cannot find the entry point of the procedure EXTPTR_PTR in the library of dynamic  links  C\Users\Elena\Documents\R\win-library\3.6\Rcpp\libs\i386\Rcpp.dll.

### ISSUE THREAD

**Issue by ElenaOS97** [rstudio/rstudio#8674]
### System details

    RStudio Edition : DESKTOP
    RStudio Version :  RStudio Desktop 1.3.1093
    OS Version      :  Windows 10 18363.1256
    R Version       : R version 3.6.1

### Problem Description

WHENEVER I get into Rstudio, the following message pops up:  "We cannot find the entry point of the procedure EXTPTR_PTR in the library of dynamic  links  C\Users\Elena\Documents\R\win-library\3.6\Rcpp\libs\i386\Rcpp.dll.

I cannot work with Rstudio, it doesn't allow me to run ANY COMMANDS. 

- [ YES] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [YES ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [YES ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [YES ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ElenaOS97 Thank you for raising the issue! We'll review it as we continue developing RStudio.

**Comment by kevinushey** [comment]
You likely need to reinstall the Rcpp package. See also: https://rickpackblog.wordpress.com/2020/08/06/updating-rcpp-extprt_ptr-error/
