### ISSUE TITLE
UI mishandles data frame variables names with backtick (`) in name

### ISSUE THREAD

**Issue by mainwaringb** [rstudio/rstudio#8675]
The RStudio GUI appears to mishandle data frames variable names with a backtick in the variable name. The R language allows backticks in data frame variable names; working with such a variable requires frequent the use of escape characters. RStudio doesn't seem to know that backticks in variable names need to be prefaced with with an escape character. It also doesn't seem to know that (escape character + backtick) has a fundamantally syntactical role than (backtick) by itself in a `df$` statement.

There are at least two circumstances in which this is evident:

- The data frame variable autocomplete (IE, if I start typing `df2$` in the console, RStudio suggests variable) suggests invalid variables. Code that results from the autocomplete won't run!
- The red X's on the left hand of the source pane are incorrect. They flag variables as syntactically invalid, when in reality that variables are syntactically valid.

I don't have the technical background to suggest a fix for this unilaterally. However, I'd be happy (and enthusiastic) to be part of a fix.

The nature of this is issue is slightly difficult to outline in a GitHub Markdown format, rather than an Rmarkdown format. I hope the below is clear, but can try to elaborate. I've resorted to screenshots in order to identify UI issues, and hope this does not create accessibility or readability problems.

## How R handles Backticks in Data Frame Variables
Before we illustrate the the bug, we first need to remember how _R_ (not RStudio) handles variable names with backticks. Let's start to define a simple example:

```
library(dplyr)

# Create sample data frame
df <- data.frame(
    gender = c("male", "female", "male", "male", "female", "male", "female"), 
    age = factor(
        c("18-29", "65+", "18-29", "30-44", "65+", "45-64", "45-64"), 
        levels = c("18-29", "30-44", "45-64", "65+")),
    stringsAsFactors = TRUE
)

df2 <- cbind(df,  recode(df$age, `18-29` = "18-44", `30-44` = "18-44"))
```

The above code block created a new data frame variable, with a backtick in the name. How do we access this new variable by name? The easy way is to save the name as a string variable, then use `[[ ]]` on this string variable. The following lines run and behave as expected.
```
new_variable_name <- names(df2)[3]
df2[[new_variable_name]]
```

It's slightly more difficult to reference the column interactively. We can do it, but it's a bit tricky:

```
# Print column names to screen
# Should print "recode(df$age, `18-29` = \"18-44\", `30-44` = \"18-44\")"
names(df2)[3]

## Example 1 - Doesn't run
# If we copy the printed variable name above, and paste it inside backticks, this doesn't work!
# R looks for a nonexistent variable called 'recode(df2$age, ' 
# R then tries separately tries to evaluate the invalid statement 18-29` = \"18-44\", `30-44` = \"18-44\")`
# (the next line of code doesn't run, and generates an error)
df2$`recode(df$age, `18-29` = \"18-44\", `30-44` = \"18-44\")`

## Example 2 - Does run
# To access the column name, we need to add a backslash escape character before the backticks
# (the next line of code runs and generates the expected output)
df2$`recode(df$age, \`18-29\` = \"18-44\", \`30-44\` = \"18-44\")`
```

We can't just copy the variable name that gets printed to the screen, and then paste it after `df2$`, even if we encapsulate the pasted variable name in backticks. We need to first add escape characters before the backticks in the variable name!

## Bug 1 : Data Frame Variable Autocomplete
The Rstudio autocomplete functionality suggests the invalid syntax 
```
df2$`recode(df$age, `18-29` = \"18-44\", `30-44` = \"18-44\")`
```
Instead of the valid syntax
```
df2$`recode(df$age, \`18-29\` = \"18-44\", \`30-44\` = \"18-44\")`
```
As shown in the following screenshot:

![bad autocomplete](https://user-images.githubusercontent.com/11147012/103446672-ee56ff80-4c47-11eb-9efe-f72c9e503bb1.png)

Rstudio autocomplete knows to encapsulate the variable name in backticks. However, it appears to just offer the outcomes of `names(df2)` as possible autocomplete options for `df2$`. 

The solution here should seems to be: check for backticks in the output of `names(df2)`, and add an escape character before any backticks, when making autocomplete suggestions.

## Bug 2: Falsely Flagging Code as Invalid/Incomplete
RStudio uses red X's in the left-hand margin of the source pane, in order to flag lines of code that are invalid or incomplete. In the following screenshot, the line of code from Example 1 above is (correctly) identified as invalid:
![good_example_of_red_x](https://user-images.githubusercontent.com/11147012/103446676-f1ea8680-4c47-11eb-813f-b1f2692ba34e.png)

However, as shown in the next screenshot, RStudio also (incorrectly) identifies the line of code from Example 2 above as invalid:
![bad_example_of_red_x](https://user-images.githubusercontent.com/11147012/103446678-f4e57700-4c47-11eb-8474-8165b61c70b2.png)

R (the programming language) knows that (backslash + backtick) has a different syntactical role than just (backtick), when identifying data frame variables. However, the RStudio UI doesn't appear to detect this difference. It treats everything between the first two backticks as a variable name - even if the backtick is following an escape character. As such, it thinks the code in Example 2 is invalid.

Without a detailed understanding of how RStudio checks syntax validity, I am uncertain about the exact solution. However, it likely involves ensuring that RStudio recognizes (backslash + backtick) as a separate syntactical construct.

## Relevance
There are a number of reasonable contexts in which R might introduce backticks into variable name by default. `cbind` is probably the most common way of introducing backticks into variables, as in the above example. When creating hundreds of new variables in bulk, the default names generated by `cbind` are helpful; relying on syntax like`df2$newvar` instead may not be practical.

Model matrices, generated by `model.matrix` or the `model` element of regression objects, produce the same result as `cbind` statements. For example:

```
myglm <- glm(
    recode(age, `18-29` = "18-44", `30-44` = "18-44") ~ gender,
    data = df,
    family = "binomial"
)
processed_df <- myglm$model
names(processed_df)
```

In these instances, `cbind`,`lm`, `model.matrix` or a similar command is combined with nonstandard evaluation, where  factor levels are referenced via backticks instead of quotes. Tidyverse packages make extensive uses of nonstandard evaluation, so the problem might extend beyond `recode`.

Manually constructing a model matrix, even with standard evaluation, can also introduce backticks into variable names:
```
transformed_df <- as.data.frame(model.matrix( ~ age + gender, data = df))
transformed_df2 <- cbind(transformed_df, transformed_df$`age30-44` * transformed_df$gendermale)
```
These manual constructions are sometimes necessary to get around restrictions in the default behavior of `model.matrix`, for example in models with complex interactions and missingness. They are also required by `glmnet`, and for exporting data to be modeled in Spark, Python, or other languages.

The issues flagged in this report are unlikely to be _common_ - but are also unlikely to be vanishingly rare. The first bug, where RStudio suggests incorrect variable names, has potential to generate extreme frustration - analysts who have limited experience with backticks and escape characters may not be able to find a workaround.

**Comment by mikebessuille** [comment]
Thanks for the incredibly detailed report!   Much appreciated.  We'll have a look...

**Comment by jonvanausdeln** [comment]
Tested on 2023.03.0-daily+312
Desktop: Windows 11
Server: Ubuntu 22

Autocomplete is now correct. Additionally, the syntax highlighting issues also behaves as expected.
