### ISSUE TITLE
Function pop-up shows up when writing parentheses inside string

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8677]
**Steps to reproduce:**
* Start writing a call with some function, passing a character (to be written in the next step) as some argument.
* Write some text enclosed in quotes as the function argument.
* While writing the character variable's text, open parentheses.

**Expected behavior:** nothing special should happen.

**Actual behavior:** brings back the pop-up with the function signature for the function being called.

**Setup:** RStudio 1.4.1100, R 3.6.3, running on debian bullseye.
![func_popup](https://user-images.githubusercontent.com/11860098/103560565-a2fb5600-4ec0-11eb-9f44-5d163e5e8db9.png)

**Comment by mikebessuille** [comment]
Should this issue be in test?

**Comment by rich-rstudio** [comment]
verified on Version 1.5.76
