### ISSUE TITLE
Repetitive autosave?

### ISSUE THREAD

**Issue by Foreist** [rstudio/rstudio#8678]
RStudio Edition : server
    RStudio Version : 1.2.5042
    OS Version      : ubuntu 18.04
    R Version       : 3.6.1

![image](https://user-images.githubusercontent.com/46616734/103602531-983bd200-4f4f-11eb-8fd4-e53abba26870.png)

Ask for saving every time you type.
The above message occurs.

Not even saved.
I granted root authority to all places in Ubuntu, but it is not saved.

Please tell me how to give rstudio sudo permission.
It is not properly written anywhere.

**Comment by kevinushey** [comment]
This usually means RStudio lacks write permissions to the `~/.rstudio` folder (or some files within that directory). You can try `chown`-ing all the files within to your user account.

**Comment by Foreist** [comment]
> This usually means RStudio lacks write permissions to the `~/.rstudio` folder (or some files within that directory). You can try `chown`-ing all the files within to your user account.

All files in .rstudio were processed through `sudo chown -R root:root`.
So, no repetitive messages appeared.
Still, the same message appears when saving the file.
