### ISSUE TITLE
Copying from panes and pasting to Messages results in English chars turned into Chinese chars

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8681]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.5042 and 1.4.1096
    OS Version      : MacOS 11.1
    R Version       : 4.0.3

### Steps to reproduce the problem

In RStudio Desktop on MacOS
1. Switch to the Help pane
2. Search for a help topic, e.g. "markdown"
3. Click on a topic, e.g. the `here::markdown` vignette
4. Select and copy some of the text, e.g. `The here package enables easy file referencing`
5. Open the Messages app
6. Paste in the Messages app

### Describe the problem in detail

The content pasted is in Chinese characters, e.g. `吀栀攀 栀攀爀攀 瀀愀挀欀愀最攀 攀渀愀戀氀攀猀 攀愀猀礀 昀椀氀攀 爀攀昀攀爀攀渀挀椀渀最`

### Describe the behavior you expected

The text pasted should be the original text, e.g. ``The here package enables easy file referencing`

Notes:
- This is in 1.3.1093, though not 1.2.5042, so this is not a regression.
- It also seems limited to RStudio Desktop, not server.
- It happens when copying from the Tutorial pane or a Shiny web app.
- It doesn't happen pasting into some other apps, such as Notes and Word.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This seems like a macOS bug. I have this content on my clipboard:

```
This is an example of Markdown vignettes
```

This is what I see if I paste into Messenger:

```
吀栀椀猀 椀猀 愀渀 攀砀愀洀瀀氀攀 漀昀 䴀愀爀欀搀漀眀渀 瘀椀最渀攀琀琀攀猀
```

The pasteboard viewer indicates that this content is on the Pasteboard, with a variety of types:

<img width="600" alt="Screen Shot 2021-01-05 at 10 13 41 AM" src="https://user-images.githubusercontent.com/1976582/103683205-bea54180-4f3e-11eb-926a-853320aebe05.png">

And that all looks correct, so it really looks like the Messenger application is mis-interpreting content on the pasteboard.

**Comment by kevinushey** [comment]
I suspect also that this is another bug that will be resolved once we upgrade to Electron.

**Comment by gtritchie** [comment]
I cannot reproduce this on macOS 12.0.1. Monterey with Juliet-Rose, Ghost-Orchid, or latest daily Prairie Trillium. Or Electron, FWIW.

The clipboard has the same content as seen by Kevin in his comments. Strongly suspect this was a bug in the Mac Messenger app that has since been fixed. I'm going to mark this as ready for test / external.

It's possible we can still repro this on an earlier macOS, but I don't have access to such at the moment, and even if we can repro, we're not likely to do anything specifically to work around such a bug in an earlier macOS.

**Comment by ronblum** [comment]
Confirmed that it works correctly on MacOS 12.1 beta, both for RStudio Desktop 1.3.1093 and 2022.01.0-daily+252.
