### ISSUE TITLE
Can't run rsession unit tests on macOS

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8685]
### System details

    RStudio Edition : dev environment
    RStudio Version : 1.4 master or juliet-rose branch
    OS Version      : macOS 11.1
    R Version       : 3.6.1

### Steps to reproduce the problem
- build RStudio locally
- from build directory, run `rstudio-tests` script

### Describe the problem in detail
- the core tests run, but then rsession fails as follows:
```
Running rsession tests...
dyld: Symbol not found: _GEkillDevice
  Referenced from: /Users/gary/rstudio/src/cpp/cmake-build-debug/session/rsession
  Expected in: flat namespace
 in /Users/gary/rstudio/src/cpp/cmake-build-debug/session/rsession
/bin/bash: line 1: 83111 Abort trap: 6           env SEGFAULT_SIGNALS='abrt segv' LD_PRELOAD= /Users/gary/rstudio/src/cpp/cmake-build-debug/session/rsession --run-tests --config-file=/Users/gary/rstudio/src/cpp/cmake-build-debug/conf/rsession-dev.conf
Running r tests...
dyld: Symbol not found: _GEkillDevice
  Referenced from: /Users/gary/rstudio/src/cpp/cmake-build-debug/session/rsession
  Expected in: flat namespace
 in /Users/gary/rstudio/src/cpp/cmake-build-debug/session/rsession
/bin/bash: line 1: 83114 Abort trap: 6           env SEGFAULT_SIGNALS='abrt segv' LD_PRELOAD= /Users/gary/rstudio/src/cpp/cmake-build-debug/session/rsession --run-script "source('/Users/gary/rstudio/src/cpp/tests/testthat/run-tests.R'); runAllTests('/Users/gary/rstudio/src/cpp', '/Users/gary/rstudio/src/cpp/cmake-build-debug')" --config-file=/Users/gary/rstudio/src/cpp/cmake-build-debug/conf/rsession-dev.conf
```

### Describe the behavior you expected
Able to run unit tests on macOS.

Note that due to #6890 we haven't hit this in the official builds.

Likely due to #8619.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This actually works fine for me on my 1.4-JR build. This part of the `rstudio-tests` script is supposed to handle it:

https://github.com/rstudio/rstudio/blob/d3b104505268387a80a61c09a70b6e1e210e8e0b/src/cpp/rstudio-tests.in#L139-L142

Does re-running `cmake` (so that the tests script is re-generated) help here?

**Comment by gtritchie** [comment]
Had blown away build output folder before doing full build. Am using bash from homebrew, have occasionally hit differences from that.

**Comment by gtritchie** [comment]
So far only I have repro'd this (on two machines), so assigning to myself.

**Comment by melissa-barca** [comment]
I can reproduce on master and juliet-rose with macOS 11.1

**Comment by gtritchie** [comment]
Assigning to @kevinushey since he made the fix.

**Comment by R-Hannibal** [comment]
Closing, Developer issue.
