### ISSUE TITLE
Relax the requirement on the png library for Python

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#8692]
The first time a python session is started, the environment pane switches to Python. If the pane is switched to R and then switched back, the user is prompted to install the `png` library and is unable to open the Python environment pane without installing the package. This feels confusing for the user, as the pane was already successfully open. If `png` fails to install, the pane will not switch back to Python.

We should either prompt the installation of `png` immediately, or relaxing the requirement, allowing the pane to still open if the installation of `png` fails.

**Comment by kevinushey** [comment]
I've decided to cut the Gordian knot by just having `reticulate` depend on the `png` package, so that attempting to install `reticulate` will also install `png`. Will be fixed once the next release of `reticulate` is on CRAN.

**Comment by kevinushey** [comment]
reticulate 1.19 is now on CRAN.
