### ISSUE TITLE
Clicking a python history item exits python

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#8693]
### System details

    RStudio Edition : Desktop
    RStudio Version : OS
    OS Version      : Centos 7
    R Version       : 3.2.5
    Python Version  : 3.6.12

### Steps to reproduce the problem
Here is a recording of the issue:

https://user-images.githubusercontent.com/37987486/103834177-977e6b00-5037-11eb-91f6-6270907d3e42.mov

1. Enter a python session (`reticulate::repl_python()`)
2. Take some actions in the python console
3. Open the History pane
4. Click on an earlier action

### Describe the problem in detail

Python exits and the command is sent to R instead.

### Describe the behavior you expected

The command should be sent to python.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
Verified this fixed in 1.4.1652-1 and added an automation test to test this as well. Closing issue.
