### ISSUE TITLE
Missing symbol is indicated as syntax error but R interprets the statement correctly

### ISSUE THREAD

**Issue by SigurdJanson** [rstudio/rstudio#8697]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      :  Win 10
    R Version       :  4.0.3 (2020-10-10)

### Steps to reproduce the problem
Copy this code to the code editor:
```
d <- cbind(c(1,2,3), c(4,5,6))
m <- quote(f(,))[[2]] # The elusive missing symbol
z <- do.call('[', alist(d, m, 2))
z
```

### Describe the problem in detail
R Studio indicates an error in line 2 ("missing argument to function call"). However, R interprets the code without complaints and returns `[1] 4 5 6`.

### Describe the behavior you expected
`quote(f(,))[[2]]` should not be indicated as false syntax. It returns a representation of the "missing symbol" in calls like `df[,2]` and is valid R.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@SigurdJanson Thank you for raising the issue! I can reproduce this in RStudio Desktop 1.4.1100, but also as far back as 1.2.5042. I'll mark this as a bug to review.

Note: print the values of `m` results in a similar error in the IDE's Console Pane as well as in standalone R, which is probably (related to) the reason for the diagnostics warning:

```
> m
Error: argument "m" is missing, with no default
```

**Comment by kevinushey** [comment]
Note: to fix, we'd need to check whether we're in an NSE-function here:

https://github.com/rstudio/rstudio/blob/d3b104505268387a80a61c09a70b6e1e210e8e0b/src/cpp/session/modules/SessionRParser.cpp#L2551-L2563

(which is true since `quote()` performs NSE, in the sense that it does not evaluate the underlying call)

**Comment by ronblum** [comment]
Reviving.
