### ISSUE TITLE
Settings/Code/Diagnostics/style: don't warn for whitespace after { if followed by #

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#8706]
[Using RStudio desktop latest preview]

Somewhere between a bug and a feature request:

RStudio's Diagnostics are great. One thing about the style diagnostics that I'd argue could do with a tiny tweak is that it currently flags whitespace after open bracket e.g.

`} else { print("foo")`

Is bad, and should be 

`} else {print("foo")`

However one of the elements of style that's suggested is long (vertical) formatting, defensive brackets etc, which lends itself to lines like:

`} else {`

However if one wants to comment that line, RStudio will flag that as a style fail unless you remove the space, which looks worse:

![rstudio_testformat_spaceAfterCurlyBracketComment](https://user-images.githubusercontent.com/4599748/104071061-2ff22800-51bd-11eb-9f40-3fbdd2d9ba20.png)

So I propose a mini amendment to the style check code which allows whitespace after open brackets if the next non-whitespace character on the line is a #comment

Cheers!

**Comment by ronblum** [comment]
@SimonDedman Thank you for raising this! I'll mark it as a bug, since 1) it's a legitimate way of commenting, and 2) some style guides recommend _two_ spaces before the pound sign `#`.
