### ISSUE TITLE
Greek label problem in displayed (but not written to file) ggplot labels

### ISSUE THREAD

**Issue by GeoffRussell** [rstudio/rstudio#8709]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      :  Ubuntu 20.04.1 LTS
    R Version       :  4.0.3

### Steps to reproduce the problem

The following code will write a file and also display a plot ... the **displayed** plot is (for me) missing the theta in the
x axis label. Saving the displayed plot doesn't help. 

But the written file is fine ... it has the theta. 

```
library(tidyverse) 
df<-data.frame(x=seq(0,1,by=0.01), 
           y=runif(101) 
) 
p<-df %>% ggplot()+geom_point(aes(x=x,y=y))+ 
  labs(y="Density",x=expression(theta)) 
p 
pdf("okplot.pdf") 
p 
dev.off() 

```

### Describe the problem in detail

See above

### Describe the behavior you expected

See above. 

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Cheers,
Geoff

**Comment by ronblum** [comment]
@GeoffRussell Thank you for raising the issue. I'm unable to reproduce the problem (RStudio Desktop on Ubuntu 20.04.1 and MacOS 11.1, and RStudio Server on Ubuntu 20.04.1). The theta appears in both the Plots pane and the saved PDF file. What do you get when running in R outside of RStudio?

**Comment by GeoffRussell** [comment]
Thanks @ronblum ... using R outside of RStudio is fine. Attached is screenshot showing my (actual) ggplot command and resulting plot pane.

![missingThetaScreenshot](https://user-images.githubusercontent.com/6374333/104255798-c8dcb800-54c9-11eb-8036-34a17e39ee20.png)
