### ISSUE TITLE
Autofill popup yields 'Error in if (length(object)) { : argument is of length zero' when writing a function

### ISSUE THREAD

**Issue by gcpoole** [rstudio/rstudio#8711]
This bug is regarding the "autofill" popup that appears after typing the first three letters of a `name` while writing code in RStudio.  When there is a name conflict between a loaded package variable and a parameter name I choose when writing a function, the popup can fail, writing an error message to the console with every keystroke typed.

To replicate the behaviour:

1) load dplyr v. 1.0.2

`library dplyr`

2) Load a new R script in RStudio, and enter the following function in the script:

```
foo = function(.data) {
  .data %>%
    c(bar)
}
```
3) Now highlight the text "bar" and replace it by typing "xxx".  When you type the third "x", RStudio will show the following error in the console: 

` Error in if (length(object)) { : argument is of length zero`

Now change the name `.data` to `data` in both places.  The error disappears.  The error also is resolved by unloading dplyr.

The problem seems to be that dplyr's environment has a variable called `.data`, which holds a `pronoun`:

```
> dplyr::.data
<pronoun>
> dplyr::.data %>% class()
[1] "rlang_fake_data_pronoun"
```
Apparently, when trying to generate the autofill popup menu, RStudio finds this variable in the environment path and it causes the error.

Basic info about my RStudio environment from "About RStudio' popup:

RStudio Version 1.3.959
"Middlemist Red" (3a09be39, 2020-05-18) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.6 Chrome/69.0.3497.128 Safari/537.36

**Comment by ronblum** [comment]
Note: I can reproduce this in the console by select `bar`, typing `x`, then <kbd>Tab</kbd> for autocompletion, and the same error is generated.

**Comment by kevinushey** [comment]
Thanks for the bug report! This will be fixed via an update coming in the next version of `rlang`.
