### ISSUE TITLE
prefer curl to libcurl with older versions of R (older than R 3.4.0)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8717]
### System details

    RStudio Edition : All
    RStudio Version : All
    OS Version      : All
    R Version       : 3.3.3 and older

### Steps to reproduce the problem

The error here is pretty specific. When using R 3.3.3 (or older), with the `libcurl` downloader enabled, and the public RSPM instance, try to install a package:

```
options(download.file.method = "libcurl")
options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/latest"))
install.packages("digest")
```

### Describe the problem in detail

An avalanche of `=` is printed to the console, freezing the session.

```
> install.packages("digest")
Installing package into ‘/home/ron/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/latest/src/contrib/digest_0.6.27.tar.gz'
Content type 'text/html; charset=utf-8' length 151 bytes
============================================================================================== <...>
```

### Describe the behavior you expected

Package installation should succeed without issue.

### Notes

https://github.com/rstudio/rstudio/blob/3732339a57ede03c1693259dd8f0286a78ae0bbd/src/cpp/session/modules/SessionPackages.R#L1258-L1275

We might consider bumping the minimum version for `libcurl` to 3.4.0.

(Spotted by @astayleraz)

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: Reproduced in RStudio Server on Ubuntu 20.04.1.

**Comment by mikebessuille** [comment]
Workaround: Set download.file.method option to wget or curl, set in R profile.  Given the older version of R, we're not likely to fix this at this point.
