### ISSUE TITLE
MakeCluster crash in RStudio preview on Windows

### ISSUE THREAD

**Issue by kjbeath** [rstudio/rstudio#8724]
### System details

    RStudio Edition : DeskTop
    RStudio Version : 1.4.1103
    OS Version      : Windows 10
    R Version       : 4.03

### Steps to reproduce the problem

The following code causes R to crash when it is either sourced or run completely. It seems to have something to do with the graphing followed by makeCluster. Running them separately works fine. Works fine in MacOS, in Windows in the RGui and Windows RStudi0 1.3.1093.

set.seed(12345)
library(lattice)
library(doRNG)

if (!exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) runif(1)
seed <- get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)

test <- data.frame(x=runif(100),y=runif(100))

xyplot(y~x, data=test)

cores <- 4
notrials <- 10

cl <- parallel::makeCluster(cores)
doParallel::registerDoParallel(cl)
res = foreach(i = 1:notrials, 
              .options.RNG=seed[1]) %dorng% {
                solve(matrix(runif(1000*1000),ncol=1000))
              }
parallel::stopCluster(cl)

### Describe the problem in detail

R Session aborted

### Describe the behavior you expected

R Session continues

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kjbeath** [comment]
What I did in my package to avoid the crash was to put a 0.1 second delay in before the makeCluster, which allows any plot updating to complete.

**Comment by bkmontgom** [comment]
Simpler example:
plot(x = 0.5, y = 0.5)
cl <- parallel::makeCluster(1)
stopCluster(cl)

Runs fine line-by-line, but source crashes
Adding Sys.sleep(0.1) after plot works, but Sys.sleep(0.01) crashes
R version 4.0.4, RStudio Desktop 1.4.1103, Windows 10 x64 (build 19042)

**Comment by kevinushey** [comment]
I'm not able to reproduce in the latest [daily builds](https://dailies.rstudio.com).

**Comment by kjbeath** [comment]
Yes, now works fine for me.
