### ISSUE TITLE
Request: make button to run Roxygen on by default

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8734]
When creating a new project in RStudio, the option `Generate documentation with Roxygen` under `Project Options` -> `Build Tools` is ticked off by default.

One usually **does** want to build documentation with Roxygen, at least in R package projects. This documentation under the default options is only generated on demand (when clicking `Document` or pressing Ctrl + Shift + D), so there is no harm in leaving the option there without having to manually activate it to make the button appear.

**Comment by ronblum** [comment]
@david-cortes As always, thank you for the suggestion! :)

**Comment by david-cortes** [comment]
Still relevant.

**Comment by david-cortes** [comment]
Still relevant.
