### ISSUE TITLE
Some shortcuts shown by command palette are incorrect

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8735]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.1103
    OS Version      : MacOS 11.1, Ubuntu 20.04.1, openSUSE 15.2, SLES 15 SP2
    R Version       : 3.6.3 and 4.0.3

### Steps to reproduce the problem

1. Open the Command Palette: `Tools -> Show Command Palette`
2. Type "Move Focus"
3. Clear and type "Switch Focus"

### Describe the problem in detail

The shortcuts displayed to the right of the command names are incorrect in these cases:
* Move focus to console: `Alt-X`
* Switch focus between source/console: `Ctrl-X, 0`

There might be others; these are just two that I found.

### Describe the behavior you expected

The correct shortcuts should be shown.
* Move focus to console: `Ctrl-1`
* Switch focus between source/console: I can't find one for it in Modify Keyboard Shortcuts or Keyboard Shortcuts Help.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1541
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that the Command Palette now shows the correct keyboard shortcuts for listed commands (compared against various commands listed on https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts). Also verified that when a user has a custom keyboard shortcut for a command, the custom shortcut is shown in the Command Palette instead of the default for that command.
