### ISSUE TITLE
support new pipe-lambda syntax in r-devel

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8742]
https://github.com/wch/r-source/commit/263d6bcf0ba5f2a87d6ba24a795125e19359c675

For example:

```
mtcars |> d => lm(mpg ~ cyl, data = d)
```

We should support highlighting of `=>` as a single token, and (if possible) make sure the diagnostics system treats these sanely.

**Comment by ntluong95** [comment]
When it becoming the new feature for Rstudio 1.4?

**Comment by kevinushey** [comment]
Implemented in https://github.com/rstudio/rstudio/pull/8744.

**Comment by ntluong95** [comment]
@kevinushey Can I download it for testing now?

**Comment by kevinushey** [comment]
No, builds of 1.4-JR are not yet available. We plan to make them available sometime in the next couple of weeks.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1531, R Version - 3.6.3, Windows 10 - Desktop 

With ligature enabled fonts (e.g. Fira Code) `|>` and `=>` are now rendering as single tokens.

@ntluong95 - This fix is now available in our [daily builds](https://dailies.rstudio.com/) of the upcoming 1.4 Juliet-Rose release (these are early development builds and may not be as stable our [current 1.4 builds](https://rstudio.com/products/rstudio/download/)).
