### ISSUE TITLE
Add shortcut tabs to File Explorer

### ISSUE THREAD

**Issue by MyKo101** [rstudio/rstudio#8743]
I think it would be useful to have a set of personalisable tabs within the Files Explorer in RStudio that can act as shortcuts to specific folders.

My use-case is during package development, switching between the `test` folder and the `R` folder is repetitive, but having a few File Explorer Tabs open would make this much easier.

I know this is isn't a _needed_ feature, and those few extra clicks aren't much, but I think it would be useful nonetheless.

**Comment by ronblum** [comment]
@MyKo101 Thank you for the suggestion! We'll consider it as we continue development of RStudio. For what it's worth, many enhancements aren't needed, per se, but still highly desirable. :)
