### ISSUE TITLE
Searching variables (objects) inside a dataframe

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#8749]
Hi Rstudio development team,
Happy new year 2021.

I would like to request for the feature that we can search name of variables in dataframes. For examples, I would like to search variable "mpg" in mtcars dataset. Furthermore, it can be shown results of other dataframes that also contain mpg variable. That would be nice when you working with multiple datasets and a lot of variables
![image](https://user-images.githubusercontent.com/63569637/104810568-c3e37580-57f5-11eb-94af-0f05529c4cf5.png)

**Comment by ronblum** [comment]
@ntluong95 Thank you for the suggestion! We'll review it as we continue development of RStudio.
