### ISSUE TITLE
Any way for us users to improve the RStudio spellcheck? 

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#8751]
I don't know what dictionary the IDE uses, but I just noticed that the word "resizes" appears as a spelling error. I added it to my personal dictionary and want to add it to RStudio's built in dictionary if that's possible

**Comment by jmcphers** [comment]
You can, just make a PR for this file:

https://github.com/rstudio/rstudio/blob/99a689fd9a0f7901582ff13e020baca56214c1a2/src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv

**Comment by daattali** [comment]
Thanks!
