### ISSUE TITLE
Spellcheck should be disabled inside the `#' @examples` documentation section

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#8752]
When building a package and adding code to the example section, that area is riddled with squiggly lines because it's code rather than English

**Comment by kevinushey** [comment]
Reproducible examples are always helpful, even for simple issues. To reproduce, open an R document with these contents:

```
#' This is Roxygen!
#'
#' @example
#' stats::rnorm(n = 1)
#'
#' @export
NULL
```

And see:

<img width="244" alt="Screen Shot 2021-01-19 at 9 58 21 AM" src="https://user-images.githubusercontent.com/1976582/105074166-def3f680-5a3c-11eb-80a0-02c13d9fd07f.png">

**Comment by daattali** [comment]
Yes you're right, thanks for including code for me

**Comment by daattali** [comment]
If this issue doesn't get added to a milestone,  it'll just get closed as unresolved?
