### ISSUE TITLE
Preview not opening, for .pdf documents

### ISSUE THREAD

**Issue by mebden** [rstudio/rstudio#8753]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1103
    OS Version      : darwin17.0           (MacOS Catalina 10.15.7 (19H114))
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem

File -> New File -> New RMarkdown
Settings wheel -> ensure 'Preview in Window' is selected
Knit -> Knit to PDF

### Describe the problem in detail

Following the above steps, the preview does not appear. Neither does it work on my previously created .rmd presentation files. I tried upgrading RStudio and R to the latest (as you can see above) but this did not fix the issue. Also I tried switching to 'Preview in Viewer Pane' but the .pdf doesn't appear there either.

I have used RStudio since 2016 and this is the first time I can recall this happening. 

### Describe the behavior you expected

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mebden** [comment]
Note that .pdf documents are successfully created, and viewable if I navigate to them in my filestore and use Adobe.

**Comment by jmcphers** [comment]
Might be related to https://github.com/rstudio/rstudio/issues/8113

**Comment by mebden** [comment]
Thank you, jmcphers! Yes, in #8113 they alerted me to Tools -> Global Options -> Sweave -> Preview PDF. 

Mine was set to 'No preview' for some reason. Problem solved!

**Comment by iMSQ** [comment]
> Thank you, jmcphers! Yes, in #8113 they alerted me to Tools -> Global Options -> Sweave -> Preview PDF.
> 
> Mine was set to 'No preview' for some reason. Problem solved!

The same issue after latest RStudio update.
