### ISSUE TITLE
d3tree2 duplicates map plotting without calling it.

### ISSUE THREAD

**Issue by Jalanjii** [rstudio/rstudio#8754]
I have a problem as you can see in the picture https://i.stack.imgur.com/5P6CF.jpg. I have the `d3tree2` interactive plot, and it plots other static ones along with the interactive rather than only the interactive one.

How can I remove the two static ones, and only allow the `htmlwidget` one?

The problem has nothing to do with reporoducible code, as much it has to do with a problem with d3tree2. It plots static plots with being called. Only the interactive one is called.

**Comment by ronblum** [comment]
@Jalanjii Thank you for raising this. Can you please provide
1) Sample code so that I can try to reproduce this, including installing the package, since it's not in the CRAN repository; and
2) Your system details.

Thanks!

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :
