### ISSUE TITLE
roundtrip of raw text inline not handled correctly by visual editor

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8755]
From @mine-cetinkaya-rundel: 

I’m also seeing something similar to https://github.com/rstudio/rstudio/issues/8073 still happen, especially when there is no empty line between the plain text and the math text in the document originally authored in the source editor. Try creating a document with the following in the source editor and then switching to the visual editor back and forth.

```
---
output: html_document
---
## No empty line between plain and math text

Hi hello
\begin{align*}
\text{point estimate} \pm 1.96 \times SE &= 0.090 \pm 1.96 \times 0.028 \\
&= (0.035, 0.145)
\end{align*}
jello

## Empty line between plain and math text

Hi hello

\begin{align*}
\text{point estimate} \pm 1.96 \times SE &= 0.090 \pm 1.96 \times 0.028 \\
&= (0.035, 0.145)
\end{align*}

jello
```

**Comment by jjallaire** [comment]
@mine-cetinkaya-rundel This fix should allow the inline tex to round trip correctly. Note however that editing of multi-line raw tex inlines isn't currently well supported (unless you use `$$`).  So I'd generally recommend $$ for display math.

**Comment by mikebessuille** [comment]
reopening and assigning to Verifying state per new bug workflow

**Comment by ronblum** [comment]
I'm still seeing the issue in RStudio Desktop 1.4.1540 on MacOS 11.1 and RStudio Server 1.4.1533 on Red Hat 8.3. The result in source mode after the round trip is: 

````
---
output: html_document
---

## No empty line between plain and math text

Hi hello \begin{align*}
\text{point estimate} \pm 1.96 \times SE &= 0.090 \pm 1.96 \times 0.028 \\
&= (0.035, 0.145)
\end{align*} jello

## Empty line between plain and math text

Hi hello

```{=tex}
\begin{align*}
\text{point estimate} \pm 1.96 \times SE &= 0.090 \pm 1.96 \times 0.028 \\
&= (0.035, 0.145)
\end{align*}
```
jello
````

**Comment by jjallaire** [comment]
This is actually technically behaving correctly since a mere newline in markdown is equivalent to a space. If you want a hard line break you need to do this:

```
Hi hello\
\begin{align*}
\text{point estimate} \pm 1.96 \times SE &= 0.090 \pm 1.96 \times 0.028 \\
&= (0.035, 0.145)
\end{align*}\
jello
```
