### ISSUE TITLE
websites should not auto-preview by default when supporting files (e.g. _site.yml or css) are changed

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#8756]
This behavior has proven confusing (b/c we don't pick all of the cases where we should preview) and inconvenient (where building the site is expensive). We should change the default to `FALSE`

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 1.4.1540 on MacOS 11.1
- RStudio Server 1.4.1533 on Red Hat 8.3 via Chrome on MacOS 11.1

Tested using the default `bookdown` project and updating the `_bookdown.yaml` file.
- Adding a space at the end of the line is sufficient.  
- Also made sure if `Build -> More -> Configure Build Tools -> Re-knit etc.` is checked, the auto-preview works.

Note: In this project, only `_bookdown.yaml` automatically refreshed the site when the box was checked. Changing `_output.yaml` and `style.css` did not. @jmcphers or @jjallaire, should changes to these files have resulted in an auto-preview? If so, I'll file a separate issue for that. (This is the same going back to 1.2.)
