### ISSUE TITLE
par() parameter xpd switches suddenly from FALSE to TRUE if "previous plot" is clicked in the "Plots" tab

### ISSUE THREAD

**Issue by GCC75** [rstudio/rstudio#8757]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      : Win 10
    R Version       : 4.0.2

### Steps to reproduce the problem

Hit "Source" in Rstudio to source the following example code: 
```r
x_dat <- c(1,2,3,4,5)
y_dat <- c(2,1,4,3,6)

plot(x=x_dat,
     y=y_dat)

abline(a=0,b=1)

my_grid <- seq(0,7, by=1)

abline(h=my_grid, 
       lty="solid", 
       col="grey")

barplot(x_dat)

```
Then click on "previous plot" to look at the scatter plot (which looks as it should) and then hit "Source" again to run the code. Now click again on "previous plot" to look at the scatter plot (which now does not look as it should: the lines produced by `abline()` go beyond the boundaries of the plotting area).

### Describe the problem in detail
If I use the button "Source" in Rstudio to source the example code from above I get two plots in the "Plots" tab: a scatter plot hidden behind a barplot. Both plots are as expected, in particular the lines produced by `abline()` are confined within the borders of the box aroung the plot.  If I click now on "previous plot" to look at the scatter plot and then hit "Source" again, then the plots are generated again, with the scatter plot hidden behind the barplot. But now the lines produced by `abline() `go beyond the plotting box. The reason is that the` par()` parameter `xpd` has been switched to TRUE. 

THIS DOES NOT HAPPEN IF after sourcing I click on "previous plot" to look at the scatter plot and then click on "next plot" going back to the barplot. Sourcing now the code again keeps the `par() `parameter `xpd` at FALSE and the lines created by `abline()` remain inside the plotting box.

### Describe the behavior you expected
I would expect that irrespective of whichever plot I am looking at (the last, the first, each other in between) in the "Plots" tab sourcing should give always the same graphic output. In other words: the setting of the `par()` parameter `xpd` should not depend on the plot which is currently open in the "Plots" tab.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@GCC75 Thank you for raising this issue. I can reproduce this in
- RStudio Desktop 1.4.1103 on MacOS 11.1
- RStudio Server 1.4.1103 on Red Hat 8.3 using Chrome on MacOS 11.1

We'll review this as we continue development of RStudio.
