### ISSUE TITLE
Rstudio 1.4 rainbow parentheses adjustment rstheme

### ISSUE THREAD

**Issue by Danny-dK** [rstudio/rstudio#8760]
I installed Rstudio 1.4 today. I enabled rainbow parentheses and according to https://blog.rstudio.com/2020/11/04/rstudio-1-4-preview-rainbow-parentheses/ and https://rstudio.github.io/rstudio-extensions/rstudio-theme-creation.html it should be possible to adjust the colours of the rainbow parentheses. I'm however unable to do so. 

I use an adjusted form of the vibrant ink theme (with extension rstheme instead of txt, rstheme was not supported for upload here):

[adjusted_vibrantink.txt](https://github.com/rstudio/rstudio/files/5834822/adjusted_vibrantink.txt)

Just for testing, I have tried adding:

```
.ace_paren_color_0 {
  color: #ffffff;
}
```

to see if something changed, but nothing did. What am I doing wrong? Should it be in a specific place or is one of the theme settings overriding the adjustment?

**Comment by kevinushey** [comment]
Does it make a difference if you use `!important` to override the default existing highlight rules?

**Comment by ntluong95** [comment]
I confirmed that it should be !important following the code

**Comment by Danny-dK** [comment]
@kevinushey Ah, that indeed did it! Thanks for the help!
