### ISSUE TITLE
Project ignores tab width

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8761]
**Steps to reproduce:**
* Import a project that uses 4 spaces per tab and uses spaces.
* Optionally ensure that both the global and the project settings are set to 4 spaces per tab and as spaces.
* Edit some file in the project.

**Expected behavior:** should either (a) catch that the file being edited is using 4 spaces per tab; (b) respect the project settings that say 4 spaces per tab; or (c) respect  the global settings which say 4 spaces per tab in the absence of project-specific settings.

**Actual behavior:** uses RStudios factory default of 2 spaces per tab.

**Setup:** RStudio 1.4.1100.

Video below:
![wrong_tab_size](https://user-images.githubusercontent.com/11860098/105062876-c3f8a500-5a83-11eb-958b-0078ce723d5f.gif)

As a test case, try importing catboost as a project in RStudio: https://github.com/catboost/catboost

**Comment by astayleraz** [comment]
I was able to reproduce this with their project in Version 1.4.1514 mac desktop.

**Comment by kevinushey** [comment]
There are a couple potential issues here:

- The source file you reference uses a mix of 2-space indent and 4-space indent. This may be confusing RStudio's automatic indent inference. You can disable this here:

<img width="602" alt="Screen Shot 2021-01-27 at 11 05 14 AM" src="https://user-images.githubusercontent.com/1976582/106040787-c4023180-608f-11eb-899c-110433ba7b89.png">

- The root directory at https://github.com/catboost/catboost does not actually contain a `.Rproj` file, so the default 2-space indent would apply.

When I tested, changing the project indent to use 4-space indent and turning off the automatic indentation inference fixed the issue.

**Comment by david-cortes** [comment]
@kevinushey but it still keeps using 2 spaces after I disable the option to auto-detect indentation.

**Comment by kevinushey** [comment]
Please provide a fully reproducible example (and preferably one that doesn't require cloning a 1.5GB repository). I tried and wasn't able to reproduce.
