### ISSUE TITLE
allow reticulate Python REPL to be interrupted

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8763]
Note: needs to be implemented in `reticulate`, but filing here to scope as part of 1.4-JR work.

**Comment by kevinushey** [comment]
Fixed via https://github.com/rstudio/reticulate/pull/928.

For testing, first install the development version of `reticulate` with:

```
remotes::install_github("rstudio/reticulate")
```


Then, in a Python script, try to run the following Python code:

```
import time
time.sleep(10)
```

Then, try to interrupt execution in a couple ways; e.g. by pressing Ctrl + C, or Escape, or by pressing the Stop button.

**Comment by astayleraz** [comment]
I verified on mac Version 1.4.1527 and r 4.0.3 that I was able to interrupt execution pressing Ctrl + C, or Escape, or by pressing the Stop button. Closing as fixed.
