### ISSUE TITLE
Python environment pane toolbar not baseline aligned

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8769]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1103-3

### Steps to reproduce the problem

Open the Environment Pane and switch it to Python view.

### Describe the problem in detail

The text and icons in the Environment Pane's toolbar are not consistently aligned. 

![image](https://user-images.githubusercontent.com/470418/105112975-e0431480-5a78-11eb-98d6-c9182e20fdd1.png)

To my eyes, it looks like "Python" is too low and the module name about 1px high.

### Describe the behavior you expected

Neatly aligned text and icons in the toolbar.

**Comment by astayleraz** [comment]
I verified in Version 1.4.1564-1 this is showing aligned. Closing as fixed.
