### ISSUE TITLE
C++ indentation not working correctly

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#8770]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Mac
    R Version       : 4.0.3

### Describe the problem in detail

I’m not entirely sure how this happened, but I’m having issues editing C++ files where the indentation for things like braces seems pretty off. I’ve had this issue consistently for 2 weeks now. It persists on the current daily version, and in this video, which is RStudio 1.4.1103. I first noticed it after working on a project that had some non-standard indentation, but has since “spread” to other projects as well. It may or may not be related to that project, I’m not sure. Any ideas?

https://user-images.githubusercontent.com/19150088/105183613-65bbd880-5afc-11eb-96de-bd43683f30ae.mov

**Comment by ronblum** [comment]
@DavisVaughan Thanks for raising this! I can't reproduce this, though, in the same environment: the indentation is restored when I hit <kbd>Return</kbd>. I'll bump it up for review.

**Comment by DavisVaughan** [comment]
I know it is a bit hard to create a reproducible example here.

FWIW I was working on this clock package, which uses some C++ code that formats slightly differently than what I normally do (function modifiers and return type on their own line, function brackets start on the LHS margin). But I still can't see why this would cause hitting Return to work as it did in my video.

https://github.com/DavisVaughan/clock/blob/c8301c1d0a551eff4dcbcade78a31673554e2080/inst/include/date/date.h#L1295-L1305

Feel free to ping me on slack, I'm happy to screen share to investigate further.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1533
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that in a C++ file, inserting a `{` automatically inserts a `}` and hitting enter automatically indents the newline. Also verified that the autoclosing of braces and indentation works as expected within nested braces.
