### ISSUE TITLE
many issues with simpie roundtrip using visual editor for real-life complex Rmd-document

### ISSUE THREAD

**Issue by N0rbert** [rstudio/rstudio#8774]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1103
    OS Version      : Ubuntu MATE 18.04.5 LTS x86_64
    R Version       : 3.4.4 from official bionic universe repository

### Steps to reproduce the problem

1. Clone the bookdown repository - `git clone https://github.com/rstudio/bookdown`
1. Navigate to the `bookdown/inst/examples` with [great book](https://bookdown.org/yihui/bookdown/) about Bookdown
1. Open biggest Rmd file named `02-components.Rmd` in RStudio
1. Switch RStudio to new visual editor mode
1. Save the `02-components.Rmd` document.

### Describe the problem in detail

Simple open-save procedure gives unnecessary differences from the original document. 
The resulting diff is in attachment - [rvis.patch.diff.txt](https://github.com/rstudio/rstudio/files/5849243/rvis.patch.diff.txt). 
It is 44K which is absolutely not expected.

Technically the resulting document violates many linter's rules like shipped with [`remark`](https://www.npmjs.com/package/remark-lint) and [`mdl` / `markdownlint`](https://github.com/markdownlint/markdownlint) . 
Below is a short list of major cases:

* `Incorrect list-item indent: remove 2 spaces  list-item-indent        remark-lint` or `MD030 Spaces after list markers` for resulting lines like

      -   one item
      
      -   one item
      
      -   one item
      
          -   one item
          -   one item

* <pre>Marker should be `1`, was `2`                ordered-list-marker-value        remark-lint</pre>  
   or `MD029 Ordered list item prefix` for resulting lines like

      1.  the first item
      2.  the second item
      3.  the third item

* `MD031 Fenced code blocks should be surrounded by blank lines` for resulting lines like

      ```{=tex}
      \begin{equation*}
      \frac{d}{dx}\left( \int_{a}^{x} f(u)\,du\right)=f(x)
      \end{equation*}
      ```
      Below is an `align` environment \@ref(eq:align):

The above list may become longer if we choose other document with more formatting applied. If you are interested I can file them separately when found in other documents.

### Describe the behavior you expected

Currently there are many toy projects from enthusiasts around the world who invent their brand new homemade Markdown editors. 
It would be really bad if commercial successful application like RStudio will suffer from the same problems. 
Your visual markdown editor initiative is great, so please do not get me wrong.

So I expect that RStudio did not make massive document rewrite on simple open and save round trip. 
Currently it is very difficult to use new visual editor with Git workflow.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@N0rbert Thank you for raising this! This is by design, though. Visual mode generates markdown using Pandoc, so markdown is rewritten to use Pandoc idioms. [The "Markdown Output" section of the Visual R Markdown Guide](https://rstudio.github.io/visual-markdown-editing/#/markdown?id=markdown-output) provides details of Pandoc conventions to which the code will conform: https://rstudio.github.io/visual-markdown-editing/#/markdown?id=markdown-output

If you prefer to keep the source code unchanged, [the "Writer Options" section](https://rstudio.github.io/visual-markdown-editing/#/markdown?id=canonical-mode) describes how to do so by switching to canonical mode: https://rstudio.github.io/visual-markdown-editing/#/markdown?id=canonical-mode

**Comment by N0rbert** [comment]
Thank you for the details, @ronblum. 

So I have added

```
---
editor_options:
  markdown:
    canonical: true
---
```

in the first lines of `02-components.Rmd` file, but it does not prevent unnecessary changes in the output file. 
How should I correctly apply this *canonical-mode* ? Could you please share reproducible example in this context?

**Comment by N0rbert** [comment]
Some new notes are below.

I'm seeing big differences for output documents when set `delete_merged_file: no` in `_bookdown.yml`.
I wonder why this new visual mode does not use the same options for `pandoc` execution?
For example `bookdown::html_document2` uses the following

> `/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS bookdown-demo-rus.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output bookdown-demo-rus.html --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /tmp/RtmpgClZvZ/fileb763ae295ee --self-contained --wrap preserve --standalone --section-divs --table-of-contents --toc-depth 5 --variable toc_float=1 --variable toc_selectors=h1,h2,h3,h4,h5 --variable toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --number-sections --variable 'theme:bootstrap' --include-in-header /tmp/RtmpgClZvZ/rmarkdown-strb76317f9065.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --citeproc `

Maybe this will help to avoid massive changes like shown below:

| **Original Rmd** | **Output of Visual Rmd** |  
|------------------------|-----------------------------------|
| `* list item`           | `-   list item`                      |
| `[url](url)`             | `<url>`                              |
| `#`                        | `\#`                                  |
| `_`                        | `\_` |
| `line  `                  | `line\` |
| `**bold**` | `__bold__` |
| `***bold italic***` | `___bold italic___` |
| `---` | `-------------------` (very long) |
| `>` | `\>` |
| `@` | `\@` |
| `~` | `\~` |
| `--` | `–` |
| `---` | `—` |
| `1.` `1.` `1.` | `1.` `2.` `3.` |
| `+ list item` | `-   list item` |
| `[^1]` | `[^chapter-1]` |
| `[^1]: endnote text` | `[^chapter-1]: endnote text` |
| `![fig](fig.png){width=1cm}` | `![fig](fig.png){width="1cm"}` |
| `Table: (\#tab:tab-lab)  ` | `: (\#tab:tab-lab)\` |
| `\begin{equation} ...\end{equation}` | `{=tex}\begin{equation}...\end{equation}` |


So I hope that new visual mode will be adapted for better compatibility with plain text mode.
