### ISSUE TITLE
Incorrect shortcuts on tooltips if the shortcuts are changed from the default

### ISSUE THREAD

**Issue by StuieT85** [rstudio/rstudio#8777]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Windows10
    R Version       : 4.0.2

### Steps to reproduce the problem
Change a shortcut using Tools -> Modify Keyboard Shortcuts... that also appears as a button on a toolbar

### Describe the problem in detail
I needed to change the shortcut for insert an R chunk from Ctrl+Alt+I to Ctrl+Shift+I as I felt it was easier to press. I have realised that when it was changed, the button to insert a chunk in the visual editor still has text which states that the shortcut is Ctrl+Alt+I. I have checked with other shortcuts and the same applies. I have checked that this occurs on tooltips in the non-visual editor of RMarkdown and I changed the shortcut for save document and an incorrect tooltip appeared in both the source editor and the main toolbar.

### Describe the behavior you expected
The tooltip to change in accordance with shortcuts even when changed, not just the defaults. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![rstudio-shortcut](https://user-images.githubusercontent.com/46073353/105384490-2f6c7f00-5c0a-11eb-8f81-75c18fc021ea.png)

![rstudio-tooltip](https://user-images.githubusercontent.com/46073353/105384194-d69ce680-5c09-11eb-9c3d-1d8ababf8805.png)

**Comment by ronblum** [comment]
@StuieT85 Thank you for raising this! We're tracking this behavior in issue #5256, so I'm marking this as a duplicate.
