### ISSUE TITLE
Locate to folder where script is located

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#8780]
Hi, I have a request for browsing folders within RStudio. 
Many times I open scripts that are located here and there, and I thought it would be great if there was a "go to folder where script is located" button. Thank you and please let me know if I'm missing already available feature.

**Comment by jmcphers** [comment]
Does this do what you want?

![image](https://user-images.githubusercontent.com/470418/105427802-cd5c4b80-5c02-11eb-9c06-87a4b6face80.png)

**Comment by matthewgson** [comment]
@jmcphers No, but it could be a workaround - what I meant was to show the script folder location in the file section of the Rstudio.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/46496637/105427979-5f248280-5c1c-11eb-83de-28e826b3a205.png">

**Comment by jmcphers** [comment]
Ah! That's tracked here (comment/upvote!) https://github.com/rstudio/rstudio/issues/6781

**Comment by matthewgson** [comment]
Thanks -! It seems I overlooked.
