### ISSUE TITLE
"Hand pointer" mouse cursor in RStudio does not follow system theme and it is much smaller than normal size

### ISSUE THREAD

**Issue by matguidi** [rstudio/rstudio#8781]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1103
    OS Version      :  Manjaro GNOME 20.2.1
    R Version       :  4.0.3

### Steps to reproduce the problem
- Open RStudio
- When the mouse cursor is moved over one of the icons under the menu ("New File", "Open an existing file") or others (like "Export" for exporting images), the cursor becomes much smaller and does not follow the system theme anymore (e.g. while I use a dark cursor theme, the "Hand Pointer" cursor is white).

### Describe the behavior you expected
- The mouse cursor should follow the system theme and be of the normal size, not smaller.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

See the video below to see what happens:

https://user-images.githubusercontent.com/59918868/105491076-0bff0e00-5cb6-11eb-80ee-164ffc82dfa6.mp4

**Comment by kevinushey** [comment]
We should just remove our custom hand cursor.

https://github.com/rstudio/rstudio/blob/56418c18fcec9bdf1de62b088dc9281f78b5faf4/src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css#L357-L365

**Comment by astayleraz** [comment]
Verified in Version 1.4.1592 on Linux desktop the hand icon has changed and I was not seeing it shrink on mouseover. Closing issue.
