### ISSUE TITLE
Undo destroy .rmd document

### ISSUE THREAD

**Issue by alxleroux** [rstudio/rstudio#8783]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1093
    OS Version      :  Linux Manjaro updated 20.01.21
    R Version       :  R version 4.0.3

### Steps to reproduce the problem
Open a .rmd, write prose and code,  have vim keybinding enabled - I couldn't reproduce the error again

### Describe the problem in detail
When I performed an undo on my .rmd document the portion of text became scrambled and some paragraph disappeared.

Going back in the undo history made chunk of text and code appears seemingly at random on the page and over new line number; I lost the document.

Here is a example :

```
## What are the most important themes in the model? 
 
The third become a tad more interesting and relates to event, action manifestation , protest. 
```{r}
labelT
t <- toptopic$topic[3]opics(fit, toptopic$topic[3] , n = 10)
```topic$topic[3]t
findThoughts(stmfit3, texts = as.character(dfm_stm$meta$message_processed), 
             n = 5, topics =  t)$docs[[1]]
 
 
 
So now that we have categorisation of text we can see of those are distributed among pages. 
For example the topic 3 is oriented around "k".
 
 
 
topto3
 
 
 
 
 
Let's see how this is distributed among pages :
 
First we get the $theta the topic estimate for each documents then aggregate it's mean per pages.
```

 

### Describe the behavior you expected

Keep my undo history, and have consistant undo.

```
  ## What are the most important themes in the model? 

The third become a tad more interesting and relates to event, action manifestation , protest. 
```{r}
t <- toptopic$topic[3]
findThoughts(stmfit3, texts = as.character(dfm_stm$meta$message_processed), 
             n = 5, topics =  t)$docs[[1]]
labelTopics(fit, t , n = 15)

Let's see how this is distributed among pages :
 
First we get the $theta the topic estimate for each documents then aggregate it's mean per pages.
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue. → it only happen once, hard to be constitent

**Comment by ronblum** [comment]
@alxleroux Thank you for raising this. I can't reproduce it, though. Was this a one-time thing, or are you able to reproduce it again? Also, were you using Vim's undo (`u` in normal mode) or the IDE's undo (<kbd>Ctrl-Z</kbd>>?

**Comment by alxleroux** [comment]
I've been working on the same file yesterday on another computer (same os) and wasn't able to raise it again. Could it be a bit flip ?

I'm sorry I don't remember, I probably tried the two while panicking but I cannot say for sure what triggered the event.
