### ISSUE TITLE
support Python installations installed via pyenv

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8784]
Users can install Python via [pyenv](https://github.com/pyenv/pyenv), and those normally get installed into a known location (`~/.pyenv/versions`). We should support the lookup and use of Python installations installed in this way.

**Comment by ronblum** [comment]
Verified for both global and project options in
- RStudio Desktop on MacOS 11.1
- RStudio Server on Red Hat 8.3
- RStudio Server on Ubuntu 20.04.1

Note: Ran into this issue along the way. https://github.com/rstudio/reticulate/issues/944
