### ISSUE TITLE
show Stop button when running long-running Python computation

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8785]
For example, try running the following code in Python:

```
import time
time.sleep(10)
```

No Stop button is displayed, and so the computation cannot be interrupted via UI.

**Comment by mikebessuille** [comment]
yes for Juliet-Rose, assuming the functionality for interrupting Python is already done.

**Comment by astayleraz** [comment]
I verified in Version 1.4.1527 that running python the user can now stop what is running. Closing as fixed.
