### ISSUE TITLE
Error: unexpected symbol in SQL and Bash chunks

### ISSUE THREAD

**Issue by johnbde** [rstudio/rstudio#8786]
I am getting **Error: unexpected symbol in:** in SQL and Bash Chunks.

```
```{sql sql-not-r, exercise = TRUE, connection="mammals"}
SELECT *
FROM `surveys`
LIMIT 10
```

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

```
**RStudio Version 1.2.5042** Same issue in latest version of RStudio 1.4

Try this file for reproducibility - 
[polyglot.Rmd](https://github.com/rstudio/learnr/blob/master/inst/tutorials/polyglot/polyglot.Rmd)

It works when I run the whole document but does not work if I run the current chunk of SQL and Bash. Run button also does not appear in SQL and Bash.

**Comment by ronblum** [comment]
@johnbde Thank you for raising this! I tried reproducing this in RStudio Desktop 1.4.1507 on MacOS 11.1 and RStudio Server 1.4.1103 on Ubuntu 20.04.

- I get a similar error when running the document, e.g.
><text>:1:6: unexpected string constant 1: echo "hello world" ^

Do you get this error?

- I'm able to run the individual SQL and Bash chunks in the R markdown file itself, though. But you don't see run buttons at all for these in the R markdown document, is that correct? Is this in source mode or visual mode? Thanks!

**Comment by johnbde** [comment]
Yes I don't see run buttons at all for these in the R markdown document in source mode. Similar issue reported in #6220

**Comment by panporter** [comment]
@johnbde any chance that "Show output inline for all R Markdown documents" is switched OFF at your side?

![image](https://user-images.githubusercontent.com/68369549/125414406-05b7d10e-3c1c-4f97-a730-502f0bea7f11.png)

This gives me the same error.

Everything back to normal by switching the option ON again.

![image](https://user-images.githubusercontent.com/68369549/125414742-82f95e26-ae6e-4dba-8183-6364728fe849.png)
