### ISSUE TITLE
As a R developer on linux, I have trouble to change the path of R

### ISSUE THREAD

**Issue by chen244** [rstudio/rstudio#8787]
I compile a new R and want to change the R versions in Rstudio ,but I get trouble,and I also want to change the path where to save my package.

Finally I find such two environment variable: R_LIBS and RSTUDIO_WHICH_R

```sh
export R_LIBS=$HOME/.R_package
export RSTUDIO_WHICH_R=/opt/R4/bin/R
```

First I export the two into my zsh, and open the Rstudio, and it works! I feel very happy,then I write it into .profile and .zshrc.but it trouble me when I open Rstudio from the menu, nothing changed. Then I think it cannot read the variable in my zsh

Finally I make another package from yours! I write a bash named rstudio.sh
```sh
if [ ! -e $HOME/.rprofile ]
then
    cd $HOME
    cp /opt/apps/com.rstudio.rstudio/files/bin/rprofile .rprofile
fi
cd /opt/apps/com.rstudio.rstudio/files/bin
source $HOME/.rprofile
./rstudio $1
```

and what in the rprofile is :

```sh
#here you can set the path of R_LiBS and RSTUDIO_WHICH_R to open which R you want to open and where to save the package
#export R_LIBS=$HOME/.R_package
#export RSTUDIO_WHICH_R=/opt/R4/bin/R
```

Then everytime before the rstudio is opened ,it will load the two variables,then I can change my R version and the path to save my packages. I think it is a good idea for you to satisfied we developers on linux , and it simply needs a little changes. I think I find a smart way to solve my problem and I hope you can accept my advice.

**Comment by chen244** [comment]
when I want to change the path of R version, all I need to do is to write the .profile in the $HOME path...This make me very happy.

**Comment by ronblum** [comment]
@chen244 Thank you for raising this!
@kevinushey Is this the best way to achieve what @chen244 is trying to accomplish? Or is this a matter of preference, and even something to discuss in the Community?

**Comment by kevinushey** [comment]
The `RSTUDIO_WHICH_R` environment variable can be used to control the version of R used by RStudio. However, I would not recommend setting `R_LIBS` since that path should normally be unique for each R installation (and R will choose appropriately-versioned paths for you).

If you need to custom library paths, it's in general better to set `R_LIBS_USER` and to follow the documentation in `?.expand_R_libs_env_var`.
