### ISSUE TITLE
Make clicks on the trace pane switch to the clicked function environment

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#8788]
While stopped at a breakpoint, more often than not we need to explore previous frames to debug. When clicking on a frame the variable watch indeed changes to that frame, but the interactive console doesn't - and we can't e.g. evaluate the frame-variables or any expressions in them interactively.

What could be helpful is if a click on a frame would behave as a selection in `recover`, something like `eval(substitute(browser(..., envir = sys.frame(which))`, and thus enable interactive investigation of the clicked frame.

**Comment by ronblum** [comment]
@OfekShilon Thank you for the suggestion! We'll review it as we continue developing RStudio.
