### ISSUE TITLE
Add syntax support (and file type recognition support) for .swift

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#8790]
I've got some nascent "use compiled Swift code from R" capability — https://git.rud.is/hrbrmstr/swiftspeech — working and rly prefer RStudio over Xcode.

Ace already has the support files:

- https://github.com/ajaxorg/ace/blob/a0aa78a05f5391100abf967526f038e8735da0c7/lib/ace/mode/swift.js
- https://github.com/ajaxorg/ace/blob/a0aa78a05f5391100abf967526f038e8735da0c7/lib/ace/mode/swift_highlight_rules.js 

and, IIRC from a previous PR I did, there are just some minor tweaks to let RStudio know `.swift` is recognized as an openable file type.

If this sounds like something y'all wld accept a PR for I'd be 👍🏽 to do so.

**Comment by kevinushey** [comment]
That would be appreciated! I just merged a PR bringing in Swift highlight rules to the version of Ace we bundle:

https://github.com/rstudio/rstudio/commit/969d7d4da356f93301b9a4a16f7f92af85631d89

The next step would be to wire that up to RStudio. Here's an example we used for the `Dockerfile` format that you can use as a template if needed:

https://github.com/rstudio/rstudio/commit/6a8f5784eb4e66c4bdc238529c523a0e419d3866

**Comment by hrbrmstr** [comment]
👍🏽 I'll fire up the mbpro in front of the fireplace this weekend
