### ISSUE TITLE
Ability to read a .sql script in Rmd files

### ISSUE THREAD

**Issue by gcameron89777** [rstudio/rstudio#8791]
This feature request stems from [this](https://community.rstudio.com/t/rmd-file-with-embedded-sql-chunk-possible-to-move-the-sql-to-external-file-then-source/49651/7) thread on the Rstudio community.

It is already possible to write sql chunks in RMD. But for longer sql files this hogs up space. Although it's possible to collapse a chunk, whenever you rerun it it automatically expands. 

I enjoy writing sql directly in the editor with an open sql file. With a conn specified at the top, the wider editor helps me focus on just sql. There's some minor friction to work flow when then copy pasting my updated sql to a rmd chunk.

Based on the linked post above, I'm currently using `readLines()` to read in a .sql file, which sometimes requires some extra steps with `glue::glu_sql()`.

This request is therefore for the ability to have a purpose built function to read in .sql files to .Rmd files, perhaps passing a conn along with the function call.

Would be swell if such a function worked in both .Rmd and regular .R files.

**Comment by ronblum** [comment]
@gcameron89777 Thank you for the suggestion! We'll review it as we continue development of RStudio. By the way, thank you for pointing out `glue::glue_sql`—I've been using `readline` as well, then concatenating lines into one; it works, but your method is much more appropriate.
