### ISSUE TITLE
RStudio freezes on startup after change of spelling/dictionary

### ISSUE THREAD

**Issue by sebastiansauer** [rstudio/rstudio#8793]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Mac OS 11.1
    R Version       :  4.0.2 (2020-06-22) -- "Taking Off Again"

### Steps to reproduce the problem

I was about to change the spell check language (to "German New"). (Then Rstudio freezed.)

### Describe the problem in detail

After having tried to change the spell check language (to"German New"), RStudio freezed and does not react anymore. Even restarting and re-installing RStudio did not help - it keeps stuck right after startup. The GUIs open and looks normally, but it does not react. See the screenshot:

![image](https://user-images.githubusercontent.com/4342172/105641543-c2b0e900-5e84-11eb-9e34-dd60268f15ae.png)

I uninstalled Hunspell (and reinstalled via Brew) , as I suspect the problem is related to some hick-up in a Hunspell dictionary. However, uninstalling/reinstalling Hunspell did not help.

In addition, I removed the Hunspell package, but it did not help.

The problem emerges irrespective if I open an RStudio project or not. I tried to open different Rmd- and R files, to no avail.

I tried different version of RStudio including 1.4.11.03 and 1.4.1512 (daily build).

### Describe the behavior you expected

The software should not crash after selecting a different spell check language.

Here's my diagnostic report:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5863016/diagnostics-report.txt)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report. Unfortunately, I'm not able to reproduce -- while I see the IDE takes much longer to initialize when this dictionary is active, it does not totally freeze.

You can try resetting RStudio's state: https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by sebastiansauer** [comment]
Thanks, your hint helped to to resolve the issue. What I now did was:

1. I navigated to `~/.config/rstudio`
2. I renamed this folder

In this folder, the dictionaries are stored, which I suspect caused the trouble. 

Now the issue is resolved. 💯 🎉 . Many thanks!

**Comment by ronblum** [comment]
@sebastiansauer Thank you for following up! Does German (New) dictionary work for you now?

**Comment by sebastiansauer** [comment]
Yes, German New dictionary/spell check does now work for me.
