### ISSUE TITLE
adding a background image to RStudio 

### ISSUE THREAD

**Issue by feddelegrand7** [rstudio/rstudio#8795]
Hi, 

It's possible to put a background image within RStudio (https://twitter.com/moh_fodil/status/1353648318409306112?s=20) using the devtools however I've to add the image each time I close and reopen the IDE. I think it would be nice to add an option (maybe at global options -> appearance) that allows the user to put a background image in a persistent manner. 

Best.

**Comment by ntluong95** [comment]
You can customize your own theme (RSTHEME file) and load it into Rstudio.

**Comment by feddelegrand7** [comment]
I've used rsthemes in the past but I don't know if it's possible to add a background image ?

**Comment by ntluong95** [comment]
Yes, you can. I did it and it was successfully

**Comment by feddelegrand7** [comment]
That's awesome will try thank you !
