### ISSUE TITLE
remove Makevars generation code on macOS

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8800]
https://github.com/rstudio/rstudio/blob/1ae3c5a669fd63fbeee55d6edea2239af5dc5c41/src/cpp/session/modules/build/SessionBuild.cpp#L2144-L2168

We did this back in the good old days when Apple was transitioning from gcc to clang, to help ensure users were using the right compiler.

Unfortunately, this breaks things with newer releases of R as R on macOS encodes the default C++ compiler into `CC` and `CXX` now. For example, my R 4.0.3 installation has:

```
CXX = clang++ -mmacosx-version-min=10.13 -std=gnu++11
```

and so we're actually overriding the default compiler setting used by R. This can lead to issues; for example:

https://github.com/RcppCore/RcppArmadillo/issues/324

To fix, I think we should:

1. Stop writing `~/.R/Makevars`;
1. Remove the `~/.R/Makevars` file if it has the contents we wrote previously but that does not agree with `R CMD config CC` and `R CMD config CXX`.

**Comment by mikebessuille** [comment]
@kevinushey what things are broken if we don't change this?  Can you justify the urgency for this being in Juliet-Rose?

**Comment by kevinushey** [comment]
Users are unable to install R packages from sources, and they will likely end up bugging the maintainers of those packages because they have no way of knowing that RStudio broke package installation (because we do this silently behind the scenes for users).

**Comment by mikebessuille** [comment]
I think that justifies we look at it for 1.4-Juliet-Rose.  Thanks.

**Comment by astayleraz** [comment]
I verified that file no longer exists following the steps outlined and checked this on mac desktop Version 1.4.1527 with R 4.0.3.

**Comment by slowkow** [comment]
> Users are unable to install R packages from sources, and they will likely end up bugging the maintainers of those packages because they have no way of knowing that RStudio broke package installation (because we do this silently behind the scenes for users).

Oh...

Could I offer a suggestion?

When RStudio does this kind of stuff behind the scenes, could we please consider leaving a message for the user like this?

```
# This file was automatically modified by RStudio on {Sys.date()}
```

This would help to resolve many mysterious issues. I feel like I might have encountered this many times without realizing it over the past year or two.

**Comment by kevinushey** [comment]
Yes, we really should've done that originally (and normally I believe we do) ... but in this particular instance, we did not. 😞 

> This would help to resolve many mysterious issues. I feel like I might have encountered this many times without realizing it over the past year or two.

Please file a bug report if you find any instances of this; normally I think we should be tagging anything generated by RStudio as such.
