### ISSUE TITLE
Check `yaml-cpp` break build against the system `yaml-cpp` on the Linux host.

### ISSUE THREAD

**Issue by bartoszek** [rstudio/rstudio#8801]
When building against system `yaml-cpp` on Linux host `cmake` pulls configuration from `/usr/lib/cmake/yaml-cpp/yaml-cpp-config.cmake` which don't host direct path to library file, instead just lib name for linker to search.
`yaml-cpp-config.cmake`
```cmake
# - Config file for the yaml-cpp package
# It defines the following variables
#  YAML_CPP_INCLUDE_DIR - include directory
#  YAML_CPP_LIBRARIES    - libraries to link against

# Compute paths
get_filename_component(YAML_CPP_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(YAML_CPP_INCLUDE_DIR "${YAML_CPP_CMAKE_DIR}/../../../include")

# Our library dependencies (contains definitions for IMPORTED targets)
include("${YAML_CPP_CMAKE_DIR}/yaml-cpp-targets.cmake")

# These are IMPORTED targets created by yaml-cpp-targets.cmake
set(YAML_CPP_LIBRARIES "yaml-cpp")
```
This line won't work with `YAML_CPP_LIBRARIES` defined in `yaml-cpp-config.cmake` defined in the system package cmake configuration. 
https://github.com/rstudio/rstudio/blob/4b1e497085e89dc817af708d418f7b5ce5365f16/src/cpp/CMakeLists.txt#L222

**Comment by kevinushey** [comment]
Thanks; should be fixed on master now.

**Comment by bartoszek** [comment]
Wow you're fast :feelsgood:
