### ISSUE TITLE
ignore anaconda environments found in revdep folders

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8805]
<img width="994" alt="Screen Shot 2021-01-25 at 1 32 56 PM" src="https://user-images.githubusercontent.com/1976582/105768942-f2f29900-5f11-11eb-87bf-fece8dfd5874.png">

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 1.4.1540 on MacOS 11.1
- RStudio Server 1.4.1533 on Red Hat 8.3

I cheated a bit; instead of using `revdepcheck::revdep_check()`, I used `reticulate::conda_create()` and changed the name of the environment to `revdep`.
