### ISSUE TITLE
Shortcut for { does not work anymore

### ISSUE THREAD

**Issue by agila5** [rstudio/rstudio#8811]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : x86_64-w64-mingw32 
    R Version       : 3.6.3

I have an HP ENVY Notebook 13-ab0XX with Italian keyboard and I don't have any specific key for { or }. 

### Steps to reproduce the problem

I updated the Rstudio version from 1.2.5042 to 1.4.1103 a few minutes ago and the with the new Rstudio version I cannot use the "AltGr + Alt + Shift + [" shortcut to add a curly bracket (i.e. `{`). That shortcut works everywhere (Mozilla browser, Word, Notepad++, TexStudio) but in Rstudio. The weird thing is that the equivalent shortcut (i.e. "AltGr + Alt + Shift + ]") for the closing curly bracket, `}`, works also in Rstudio.  

### Describe the problem in detail

I cannot use anymore the shortcut for the curly bracket, i.e. "Altgr + Alt + Shift + ["

### Describe the behavior you expected

The previously mentioned shortcut works for adding a curly bracket everywhere but in Rstudio. The equivalent shortcut for } is still working. The problem persists even after resetting Rstudio global options. The problem persists also with Rstudio version 1.4.1518. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@agila5 Thank you for raising this. We'll review it as we continue developing the RStudio IDE.
