### ISSUE TITLE
Old File Appears in Recent Files After Being Renamed

### ISSUE THREAD

**Issue by valerie-rstudio** [rstudio/rstudio#8813]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1518 (also in 1.3.109) & 1.4.154-2
    OS Version      :  mac OS 11.1 & centos8
    R Version       :  4.0.2

### Steps to reproduce the problem

1. Open a file and save it.
2. Rename the file
3. Click on Open Recent Files drop-down (or go to File -> Recent Files)

### Expected Behavior
The old name of the file does not appear in the recent files list.

### Actual Behavior
Old name of file listed in Recent Files. When you click on the old file in the list, you get a message pop up saying "Error while opening file. No such file or directory"
<hr>

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Good catch! I'll put in 1.4-juliet-rose and do if it's simple and safe, otherwise easily punted.

**Comment by gtritchie** [comment]
Not going to get to this in juliet-rose.

**Comment by gtritchie** [comment]
Resolving as "won't fix". It's always been this way when using the Rename command on the main menu and from the Files pane.
