### ISSUE TITLE
Implement "Choose R Installation" dialog for Electron desktop on Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8815]
Hold down <kbd>Ctrl</kbd> when launching RStudio desktop on Windows to show the following dialog. It is also available from inside RStudio via Global Options / General  / Basic / R Versions.

![screenshot of Choose R Installation dialog on RStudio 1.4](https://user-images.githubusercontent.com/10569626/105896398-95bb1e00-5fcb-11eb-94f5-4fa7c232e67f.png)

This dialog is a Qt native dialog (one of only a few we have), and needs to be rewritten to be available in Electron-based RStudio. See also: https://github.com/rstudio/rstudio-pro/issues/2309 for another example.

The R version selected via this dialog must be persisted, and used when the IDE is run again (without showing the dialog).

The list of available R versions should match what is seen in the Qt desktop.

The detail on holding down Ctrl to force display of the dialog is covered here: #10401

This also contains "Rendering Engine" setting; we can remove this for now, and track whether we need to put it back via separate work item: #10695

**Comment by gtritchie** [comment]
What do you know, we already have an issue for this that I opened in January!

**Comment by kevinushey** [comment]
For testing, this issue specifically tracks whether different R versions located in `C:/R` and `C:/Program Files/R` are displayed in the startup "Select R" dialog.
