### ISSUE TITLE
Allow Xaringan presentations to be edited in visual mode

### ISSUE THREAD

**Issue by kcarnold** [rstudio/rstudio#8816]
It makes sense that Xaringan presentations are excluded from visual mode at this point (https://github.com/rstudio/rstudio/commit/5b332a45d5406202e01c747cd27ac544c92e229e). With the different Markdown syntax and various customizations possible, I imagine it would be hard to make a good visual editing experience. And Xaringan users are supposedly ninjas already. But in the name of inclusion, I'm suggesting this anyway.

Hacking around the tripwire (by removing `xaringan` from the YAML) shows that the visual editor makes a half-decent display of a xaringan deck already. It doesn't yet round-trip correctly (e.g., the slide separator `---` gets replaced by a full-width rule), and there's a lot of visual and semantic improvements that could be made, but it seems promising. So here's a shot at what it might need:

- [ ] Display and round-trip slide separators (`---`)
- [ ] Protect inline HTML from getting munged into Pandoc blocks etc.
- [ ] Design a visual style for inline and block CSS classes
- [ ] Make sure incremental slides (`--`) work
- [ ] probably lots more...

For reference, here are references for remarkjs's Markdown syntax (which, unfortunately, has extensions that are *different from Pandoc's*):

* https://bookdown.org/yihui/rmarkdown/xaringan-format.html
* https://github.com/gnab/remark/wiki/Markdown

**Comment by ronblum** [comment]
@kcarnold Thank you for the suggestion, and for calling out specific examples! We'll review this as we continue development of RStudio and the visual markdown editor.
