### ISSUE TITLE
Custom font size per pane other than help

### ISSUE THREAD

**Issue by meztez** [rstudio/rstudio#8820]
I would be interested in having the option to adjust the font size of the `History`, `Build` independently.

I could probably wiggle a PR together based on #5470 if you think this could be interesting.

Thank you

**Comment by colearendt** [comment]
I think this seems interesting! I don't maintain the IDE, but I would think this type of thing could be useful for accessibility. I'm curious to hear more about why adjusting them independently would be helpful!

**Comment by mikebessuille** [comment]
I think this would cause too much complexity - now the user would have to be able to independently change the font size / zoom of each window independently.  It would also make for an IDE that visually  might look visually unappealing.   If this issue gets a lot of upvotes we'd consider it, but currently I think this is unlikely.

**Comment by meztez** [comment]
I was able to achieve it through theming.

id : rstudio_workbench_panel_build
child class : ace_editor ace_scroller
