### ISSUE TITLE
clicking the empty space below the console input doesn't send focus to console input

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8824]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 99.9.9
    OS Version      : macOS  11.1
    R Version       : R version 4.0.3 (2020-10-10)

### Steps to reproduce the problem

Clear the console with e.g. Ctrl + L, then try to click in the empty space below the console input line.

https://user-images.githubusercontent.com/1976582/106036617-6f0fec80-608a-11eb-9d94-37ff17233a7c.mov

### Describe the problem in detail

The console input line is not focused.

### Describe the behavior you expected

Focus should be sent to the console input.

**Comment by kevinushey** [comment]
Note: suspect the code here is over-aggressively preventing focus transfer.

https://github.com/rstudio/rstudio/blob/77d945bf383cb983ff3070aaca3c7c377799d050/src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java#L630-L635

**Comment by adamconroy** [comment]
This was fixed here in Juliet-Rose: https://github.com/rstudio/rstudio/pull/8779

**Comment by kevinushey** [comment]
Reproduced in 1.4.1522.

**Comment by adamconroy** [comment]
Interesting, yeah I can't reproduce that on Juliet Rose on my Mac. Cleared console a bunch of times, trying clicking from desktop and from code buffer into console and it always gets focus properly.

**Comment by adamconroy** [comment]
Figured it out. Out of habit I had picked J-R to merge the above PR into instead of master. I'll recreate the changes there and leave the branch orphaned instead of cherry picking.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1533 & 1.4.1533-1
    OS Version      : mac OS 11.1 & centos7
    R Version       : 4.0.2 & 4.0.3

Verified that clicking on the empty space in the console switches focus to the console. Also verified that clearing the console still works as expected.

### Notes
Waiting to close ticket until this can also be verified on Windows.
