### ISSUE TITLE
[Git pane] focus on search when branch selector appears

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#8825]
In the git pane when I go to select a branch,  a dropdown appears enumerating all the branches.

In projects that have lots of branches, the only meaningful way to select the one I want is to search for it. So I typically want to start searching immediately after I open this dropdown. I think it would be a nice usability win if the search textbox were automatically selected/focused when the branch selection dropdown appears so the user could immediately start typing to search for the branch of interest.

**Comment by ronblum** [comment]
@trestletech Thank you for the interesting suggestion! We'll review it as part of our ongoing development of the RStudio IDE.
