### ISSUE TITLE
Python very slow in RStudio 1.4.1103

### ISSUE THREAD

**Issue by viniciusbrei** [rstudio/rstudio#8829]
### System details

    RStudio Edition : desktop 
    RStudio Version : 1.4.1103
    OS Version      :  MAC OS BIG SUR 11.1
    R Version       : 4.0.1

### Steps to reproduce the problem
I enjoy RStudio and as an R and Python user, I was happy with the version 1.4 recently launched. However, I’m quite disappointed with how slow it is to run Python scripts. Very simple commands such as df.info( ) take many seconds to run. It is so slow that at this moment I am not considering adopting RStudio as my only IDE for both R and Python.
Do you have any suggestions on how can I increase the speed of Python code running on RStudio?

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thank you for the bug report -- can you please provide a reproducible example show-casing exactly what behavior you're seeing? That is, a Python script that when run showcases the slowness you're observing?

**Comment by viniciusbrei** [comment]
Thank you for your message. These were the steps and results:
1. In Anaconda Navigator, I created a shared R/Python (version 3.8) environment, imported the 'pandas' and 'time' libraries. Next I activated this environment to run the Python scripts in RStudio (version 1.4.1103). Also in Anaconda Navigator, I created a Python-only environment to run the Python scripts in Spyder (version 4.2). 
2.  I've run the same script in my Macbook pro 2017 (2.9GHz; 16GB RAM) and measured the processing time for each command, on both RStudio (using environment "R/Python") and Spyder (using environment Python only):

import pandas as pd #after this command RStudio calls Reticulate version 1.18 automatically
import time
import numpy

start = time.time()
df = pd.read_csv(c:/'xxxxxx.csv',low_memory=False) # this is a CSV file with 2.81GB (dataframe: 11114099 lines and 22 columns
end = time.time()
print(end - start)

3. These are the resulting processing time comparing a few commands of Python running on RStudio 1.4.1103 against Spyder 4.2:
pd.read_csv: RStudio = 67.54; Spyder = 47.20
df.info(): RStudio = 0.125; Spyder = 0.010
df.head(): RStudio =  0.057; Spyder = 0.0004
df.tail(): RStudio = 0.043 ; Spyder = 0.0002
df.shape(): RStudio = 0.179; Spyder = 0.061
df.nunique(): RStudio = after 10 minutes running without results, I restarted RStudio; Spyder = 0.139

As you can see, RStudio has been much slower than Spyder to run the same Python code, using the same computer, libraries, and dataframe.

Any recommendations on how to increase RStudio's speed?
Thanks!
