### ISSUE TITLE
Enable moving to named segments (e.g. Headers, Chunks) via keyboard search

### ISSUE THREAD

**Issue by mjfs** [rstudio/rstudio#8832]
When updating a larger document the functionality that supports navigation to connected segments as quickly as possible is a time saver and in addition minimizes the overhead of mental context switching.

RStudio offers "Jump to" (with `Alt+Shift+J` as default shortcut) for the stated purpose. Although one can move in the displayed menu via keyboard, in a larger document the number of key presses is often high and requires user attention when selecting desired item.

A filter box (for shown items) at top of the "Jump to" menu with (focused by default) would enable significantly faster navigation in larger document. Furthermore, when navigating distinct phrases, no user attention would be required (e.g. when moving to "References", "Introduction" etc.) since there would be only one item displayed after completing with entry.

**Comment by ronblum** [comment]
@nfjs Thanks you for the suggestion! We'll review this one, as well, as part of our ongoing development of RStudio.

**Comment by mjfs** [comment]
I can confirm that the issue remains unresolved 1.5.244.

RStudio supports moving to a function by using as shortcut (`Ctrl + .`) and entering a part of a function name. Having something similar available for text (i.e. RMarkdown documents) would make editing without a mouse faster (e.g. jumping between an Appendix and Chapter currently edited or some other document composition workflow).
