### ISSUE TITLE
Ctrl+click does not always scope correctly

### ISSUE THREAD

**Issue by samrickman** [rstudio/rstudio#8845]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 7 x64 (build 7601) Service Pack 1 / x86_64-w64-mingw32/x64 (64-bit)
    R Version       : 3.6.3 (2020-02-29)

### Steps to reproduce the problem

1. Type `df <- data.frame()` in the source window.
2. Run that line.
3. Ctrl + click `df`.
4. The Rstudio View window opens up with the definition of the *function* `df`.

### Describe the problem in detail

If the above steps are repeated with a differently named data frame which does not clash with an existing function, it works correctly and open a preview of the (empty) data frame.

Also, `View(df)` works correctly and opens the data frame called `df`. 

It is only Ctrl + click that opens the definition from the unexpected scope.

### Describe the behavior you expected

I expected it to open the View window with the contents of the data frame displayed.

I thought you might want to be aware of this but it is really not a huge issue. Rstudio is great - I am particularly loving it since the implementation of rainbow brackets. Keep on doing what you're doing!

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@samrickman Thank you for raising the issue! On Windows 10, I can reproduce this as described. On MacOS 11.3, I can reproduce this using <kbd>Cmd-Click</kbd>. We'll review this as we continue development of RStudio.

Note: This occurs going back to at least 1.2.5042, so this is not a regression.
