### ISSUE TITLE
Switch statements in C++ files indent incorrectly

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#8846]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1527
    OS Version      : Mac
    R Version       : 4.0.0

### Describe the problem in detail

When working with C++ files, `case` parts of switch statements indent very oddly, and it stacks with multiple case statements. It's most annoying when copying/pasting a function containing a switch statement with multiple case statements, as they will paste and reformat themselves with this odd indenting.

I _think_ the previous behavior was that after I typed the `:` after `year` it would un-indent itself to align with the switch.

May be related to https://github.com/rstudio/rstudio/issues/8770, but I'm not sure.

https://user-images.githubusercontent.com/19150088/106287602-f6896700-6214-11eb-9874-52d915fe59f2.mov

**Comment by kevinushey** [comment]
I'm not able to reproduce in 1.4.1533 -- I cloned the project at https://github.com/DavisVaughan/clock, opened `duration.cpp`, and then tried to edit the document in exactly the same way and the `case` entries were indented properly.

In particular, after typing `:`, the associated line is outdented to match the `switch()` indentation.

**Comment by DavisVaughan** [comment]
As odd as this sounds, I seem to be able to trigger this bug by turning Rainbow Parenthesis on. If I turn them off, it works as expected.

**Comment by kevinushey** [comment]
This actually makes a lot of sense -- thanks! I'll take a look.

**Comment by mikebessuille** [comment]
Mistakenly added it to Tiger Daylily.  Was meant for JR

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1597
    OS Version      : mac OS 11.2.1
    R Version       : 4.0.3

Verified that C++ switch cases now auto-align with the indentation of the switch statement when rainbow parentheses are turned on.
