### ISSUE TITLE
Visual Citation - Issue with full pathname in YAML Header

### ISSUE THREAD

**Issue by polc1410** [rstudio/rstudio#8847]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.1103
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : R version 4.0.3 (2020-10-10)

### Steps to reproduce the problem
Create a demo Rmd file. (standard template)
Use visual markdown editor
Click add citation button ([@])
Enter a PMID Number and search for it (e.g. 31483278)
Click OK
Citation is added
YAML Header is updated to contain: bibliography: references.bib

Now update the YAML header to the full qualified path (on windows) of the bibliographhy file.  This is necessary if knitting to PDF through pandoc and the file is not on a local drive.  e,g, bibliography: U:/My Documents/MyProject/references.bib

Now add a second citation using the same steps using a seperate PMID if (e.g. 32904933)
R Studio will hang will not insert the citation

### Describe the problem in detail
When the bibliography.bib file in the YAML header has a full path name, the Insert Citation window will stay "stuck" saying "Creating bibliography entry"

### Describe the behavior you expected
Either:
(Preferred) - the bibliography entry is created, the citation is added to the markdown  OR
- an error message is reported to say the bibliography file was not accessible

**Comment by ronblum** [comment]
@polc1410 Thank you for raising the issue! I can reproduce it in
- RStudio Desktop 1.4.1507 on MacOS 11.1
- RStudio Server 1.4.1514 on Red Hat 8.3 from Chrome on MacOS 11.1

Can you confirm that this happens with a full path to a local file, not just for mapped drives? Also, I'm able to exit and return to the editor by clicking on "Cancel"—does that work?

Note: This happens even for a reference that already exists in the file; for example, use PMID 31483278 both times.

**Comment by polc1410** [comment]
Yes. I can confirm (Windows) I am seeing the same if C:\user\path\references.bib is used rather that U:\

**Comment by polc1410** [comment]
and Cancel works, allowing you to safely return to the editor but no citation is added

also presumably related if you type [@ in the editor a drop down appears to select a citation. the same issue occurs - if the file has a pathname the citation is not correctly handled.

**Comment by mikebessuille** [comment]
Reopening as the new process is to leave an issue open and mark with "test" label so that QA will test it.  QA will close when testing is complete.

**Comment by ronblum** [comment]
Confirmed in
- RStudio Desktop 1.4.1627 on MacOS 11.3
- RStudio Server 1.4.1639 on Ubuntu 20.04 using Chrome on MacOS 11.3
