### ISSUE TITLE
Find system python installations and allow user input

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#8852]
### System details

    RStudio Edition : All
    RStudio Version : 1.4+
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

Install python into the system at `/opt/python/...` (i.e. `/opt/python/3.7.7/bin/python`). This is our recommendation in enterprise environments.

Notice that these paths do not show up when searching for python in the IDE. In case python is elsewhere (and not on the path), we should also give the user the option to find a python installation themselves.

We could also consider admin configuration of usable python directories.

### Describe the problem in detail

Finding / using python on a system can be challenging - we should make it configurable.

### Describe the behavior you expected

- Flexibility to use the python versions I want to use
- Configuration to pre-set these values for users

**Comment by astayleraz** [comment]
I verified in Version 1.4.1564-1 I am able to see and select versions of python installed in /opt/python/. Closing as fixed.
