### ISSUE TITLE
Scrolling leads to brighter-colored and bolder text

### ISSUE THREAD

**Issue by pnacht** [rstudio/rstudio#8853]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 10 Home 64-bit (10.0, Build 18363)
    R Version       : 4.0.2

### Steps to reproduce the problem
- Have a file long enough to allow for plentiful scrolling.
- Have a theme with bright text colors
- Scroll quickly down until you notice the colors become brighter (this may involve scrolling enough so that the caret moves off-screen)

### Describe the problem in detail
Frequently when scrolling through a file in RStudio, the text colors seemingly brighten and the text seems to become "bold". As soon as I click or type something, the colors dim back to normal.

For example, after some scrolling, I got the following color for my strings:

![image](https://user-images.githubusercontent.com/15221358/106325953-7259d280-625a-11eb-8aeb-11f21c571931.png)

But then I click anywhere on the editor and the text goes back to normal:

![image](https://user-images.githubusercontent.com/15221358/106325974-7a197700-625a-11eb-91bf-8e4b972bacfd.png)

If useful, here are a dummy lorem-ipsum file and my .rstheme, though I've noticed this behavior multiple times in other RStudio versions with other themes, I just didn't bother posting this bug report until now.

[colorBug.zip](https://github.com/rstudio/rstudio/files/5896297/colorBug.zip)

### Describe the behavior you expected
The colors shouldn't change after scrolling.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@pnacht Thank you for raising the issue! We'll review it as we continue development of RStudio.

**Comment by R-Hannibal** [comment]
@pnacht - thanks again for finding and reporting this issue, as well as providing the example file/theme.

I have not been able to reproduce the issue thus far (testing on Windows 10, RStudio version 1.4.1103). Does changing your Rendering Engine (Tools > Global Options > General > Advanced) having any impact on the issue? Or does it occur with both Software Rendering and Desktop OpenGL? Also, if you're able to provide a GIF example of the issue occurring that may help us in our efforts to reproduce it in house.

**Comment by pnacht** [comment]
I had the rendering engine set to "Auto-detect". I tried both "Software" and "Desktop OpenGL", as well as all the different combinations of (dis)activating "Use GPU blacklist" and "Use GPU driver bug workarounds" for each engine, the problem always remained.

Here's a GIF. In this example I used the scroll wheel, but using the scrolling bar has the same effect.

![F823Itf6YG](https://user-images.githubusercontent.com/15221358/107398922-e1e38380-6ade-11eb-97c8-fdf65a7482ff.gif)

**Comment by kevinushey** [comment]
Hopefully will be fixed in 1.5 via Electron; not worth investigating for 1.4.

**Comment by R-Hannibal** [comment]
Thanks @kevinushey.

@pnacht - Thanks for the additional info and providing the gif. We're thinking this issue is related to the IDE's reliance on QT Web Engine in our desktop builds. The fix will be for us to move away from QT, which we have planned for an upcoming release later this year.

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If anyone is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by ronblum** [comment]
Closing this as fixed by Electron. If anyone using builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) continues to run into this issue, please let us know!
