### ISSUE TITLE
Python version that shows from reticulate::py_config() in the console does not match when knit

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#8854]
### System details

    RStudio Edition : 
    RStudio Version : 1.4.1533
    OS Version      : Mac 10.15.17
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Create a Python virtual environment.
2. In Project Options, tell RStudio to use the virtual environment as the active Python interpreter.
3. Install one or more Python packages.
4. Create an R Markdown document that emits the Python version via reticulate::py_config()
5. Knit the document and examine the Python version that shows in the viewer vs the output that shows in the console.

![Screen Shot 2021-01-29 at 3 09 58 PM](https://user-images.githubusercontent.com/1482677/106333218-6a436800-6245-11eb-8389-feb4b3c62f9b.png)

 

### Describe the problem in detail
It is confusing why those versions are not matching.

### Describe the behavior you expected
I would expect the versions of what shows in the source and console to match what is showing in the knitted document. 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Moving to Juliet Rose for discussion. See related https://github.com/rstudio/rstudio/issues/8844, https://github.com/rstudio/rstudio/issues/8636. We should probably forward the Python environment when knitting since we do when publishing, so that the two are symmetric. 

Via @kevinushey :

> [... ] That is, it seems like the version of Python set in RStudio should be lower priority than whatever version of Python the document specifically requests (if anything), but should still be in the lookup hierarchy. [...] I think it's reasonable for the Python interpreter used when rendering a particular document to be tied to the project state, and for that document to potentially not be reproducible if moved out of that project.

**Comment by jmcphers** [comment]
Responsible for this community forum issue: https://community.rstudio.com/t/knitr-fails-with-the-newest-python-interpreter-option-in-rstudio-1-4/94519

**Comment by astayleraz** [comment]
I have verified in Version 1.4.1564-1 the version of python showing matches in the viewer, visual mode and in the console and will also show the correct matching version when changing python versions.
