### ISSUE TITLE
Closing a modified buffer via context menu doesn't prompt to save

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#8856]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.1532
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- open an R script, make a change, but don't save it
- right-click on tab and select "Close"

### Describe the problem in detail
- the file immediately saves and closes

### Describe the behavior you expected
- should be prompted to "Save", "Don't Save", "Cancel" as you'd get closing via the [x] or File / Close

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1546
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that when closing an unsaved R Script via the right click context menu, you are now prompted to Save, Don't Save, or Cancel. Also verified this works as expected with Close All and Close All Others, and when multiple documents are in an unsaved state.
