### ISSUE TITLE
Source editor display issue when emojis with variation selector in file

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#8859]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : Version 1.4.1533
    OS Version      : macOS 11.1
    R Version       : 4.0.3

### Steps to reproduce the problem

Type the following in the source editor and then try to insert a 2 where it belongs.

```
🗓️134

🗓134
```

Here is what happens:

https://user-images.githubusercontent.com/5965649/106341986-13ff1500-6297-11eb-8cac-aef67c71f608.mov

### Describe the problem in detail

With the top string, the cursor is not where it appears to be.

These strings look identical here, but in the source editor there is a character between the emoji and the 1 in the first string, it's `U+FE0F`.

Here is another look at the first string:

```r
utf8splain::runes("🗓️134")
#> utf-8 encoded string with 10 runes
#> 
#> U+1F5D3   F0 9F 97 93   11110000 10011111 10010111 10010011    Spiral Calendar Pad : calendar, day 1
#> U+FE0F       EF B8 8F            11101111 10111000 10001111    Variation Selector-16                
#> U+0031             31                              00110001    Digit One                            
#> U+0033             33                              00110011    Digit Three                          
#> U+0034             34                              00110100    Digit Four                           
```

And here it is for the second string:

```r
utf8splain::runes("🗓️134")
#> utf-8 encoded string with 10 runes
#> 
#> U+1F5D3   F0 9F 97 93   11110000 10011111 10010111 10010011    Spiral Calendar Pad : calendar, day 1
#> U+0031             31                              00110001    Digit One                            
#> U+0033             33                              00110011    Digit Three                          
#> U+0034             34                              00110100    Digit Four                           
```

### Describe the behavior you expected

I expected the first string to behave like the second one as I'm not sure how the additional character `U+FE0F` got added in there and it's not visible in the source editor.

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Appears to also be broken on https://ace.c9.io/build/kitchen-sink.html, so my initial hope that upgrading Ace would fix this is unfortunately dashed.

**Comment by kevinushey** [comment]
I've filed an issue upstream at https://github.com/ajaxorg/ace/issues/4434.

**Comment by luisvalenzuelar** [comment]
I think this problem is broader than it looks. The problem described [in this post](https://stackoverflow.com/questions/70283761/cursor-shifted-after-some-spanish-accent-marks-in-rstudio-editor) is of the same nature. I have this when importing some data with Spanish words. Encoding option in `read.csv` does not solve the problem.
