### ISSUE TITLE
FR: insert citations new (1.4) features in non-visual mode

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#8863]
Hi!,

First of all, I have asked previously -but without any satisfactory answer- if the features I am asking are somehow implemented: https://community.rstudio.com/t/insert-citations-in-non-visual-markdown-editor/94028

As I believe they aren't, I ask here for these features, which actually  are the new features on citations ([https://blog.rstudio.com/2020/11/09/rstudio-1-4-preview-citations/](https://blog.rstudio.com/2020/11/09/rstudio-1-4-preview-citations/)), but only on the visual markdown editor, while it would be very helpful to have them also in the source editor for markdown documents. I copy from the link the features I mean, but mainly it would be to have access to the **Insert citation** dialog and the completion interface for searching available citations without having to switch to visual mode:

- You may insert citations using the **Insert -> Citation** command, after placing your cursor in the body of your document where you’d like to insert the citation. Alternatively, you can use markdown syntax directly (e.g. by typing [@cite] or @cite) .
- Use the  `@` toolbar button or the `⇧⌘ F8` keyboard shortcut to show the **Insert Citation** dialog:
![image](https://user-images.githubusercontent.com/40892925/106439151-a958ff80-6477-11eb-91ac-d6746fcca156.png)
Note that you can insert multiple citations by using the add button on the right side of the item display.

If you insert citations from Zotero, DOI look-up, or a search then they are automatically added to your document bibliography.

- You can also insert citations directly using markdown syntax (e.g. [@cite]). When you do this a completion interface is provided for searching available citations:

Thank you!

**Comment by ronblum** [comment]
@iago-pssjd Thank you for the suggestion! I took a look at the Community post, too, and correct—the citation insert and lookup are only available in visual mode. We'll review this request to include it in source mode as we continue development of RStudio.

**Comment by iago-pssjd** [comment]
Oh! now I see this is a duplicate of #7876, so I close it.
