### ISSUE TITLE
document IDE's Python integration

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8870]
Most likely as an article on https://support.rstudio.com/hc/en-us? The article should discuss:

- The `reticulate` package, and how RStudio uses `reticulate` to interface with Python,
- The Python tab in the Global Options pane,
- General "getting started" strategies.

**Comment by kevinushey** [comment]
Python documentation is now available at https://support.rstudio.com/hc/en-us/articles/1500007929061.

I'm not sure what it means to "test" the documentation, though -- perhaps just sanity check?

**Comment by ronblum** [comment]
A few notes:

1) The comma is included in the Windows link: `https://www.python.org/downloads/windows/,`
2) Change
> reticulate will unable to bind 

to
> reticulate will be unable to bind 

3) We first tell people to install `reticulate` under the "Using Python" section. However, we mention it several times in the beforehand in the "Installing Python" section, so I suggest moving the installation of `reticulate` to the top of that section. Then keep the "Using Python" explaining what the package does, etc., as is.

**Comment by ronblum** [comment]
Confirmed—thank you!
