### ISSUE TITLE
File saving and chunk execution not working in Visual Editor

### ISSUE THREAD

**Issue by maciejkos** [rstudio/rstudio#8873]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 10 x64 (build 19042)
    R Version       : 4.0.2 (2020-06-22)

### Steps to reproduce the problem
1. Work with a file in Visual Editor for over a day. 
2. Attempt to save the file.
3. If the file not saved, try to execute a chunk.

### Describe the problem in detail
After working on the same file in Visual Editor for while - say, a day - it becomes impossible to save the file using CTRL-S or the File menu. While no error message is produced, the .Rmd is not saved as confirmed by:
1) Date modified no changed in Windows Explorer;
2) Asterisks displayed in RStudio's file tab;
3) After shutting down RStudio and reopening the file, all changes to the file are lost.

Once saving stops working, you cannot execute individual chunks in the .Rmd file. Nothing happens. However, saving and executing code in Rstudio's regular editor works. Execution in the console works too. 

**NOTE**: I have just submitted another Visual Editor issue (issue #8872). I am mentioning it here in case they are related to each other or they can point to an issue on my end.

### Describe the behavior you expected
The file should be saved. Chunks should get executed.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@maciejkos Thank you for raising this issue, as well! I can't reproduce it in the same environment, though. However, we'll review this issue as we continue development of RStudio. I'm glad to hear that at least you have a workaround, saving from the source editor.
