### ISSUE TITLE
Adding Poppins font Family

### ISSUE THREAD

**Issue by JeevasathyaDhanapal** [rstudio/rstudio#8874]
Hi Team,
 
I am contacting from Ovintiv .We got a request as below
 
Can you please add the Poppins font family (https://fonts.google.com/specimen/Poppins) into the RStudio server? We specifically use Semibold, Medium, Light, Regular, but it would be great if they could all be deployed.

**Comment by jmcphers** [comment]
Good news, you can do this yourself! See instructions in our admin guide. (Note that this is a new feature in RStudio Server 1.4).

https://docs.rstudio.com/ide/server-pro/r-sessions.html#fonts
