### ISSUE TITLE
RStudio automatically shuts down when computer goes to sleep

### ISSUE THREAD

**Issue by EvPop21** [rstudio/rstudio#8876]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1103
    OS Version      :  Windows 10 Pro Version 20H2
    R Version       :  4.0.3

### Steps to reproduce the problem
After my computer goes to sleep, RStudio automatically shuts itself down. There are no error messages or anything. I tried uninstalling and reinstalling the latest version of R and RStudio but no luck.
### Describe the problem in detail
After my computer goes to sleep and wakes up, RStudio is closed. It does not matter if I am in an R project or not.
### Describe the behavior you expected
Same as above.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@EvPop21 Thank you for raising the issue! I can't reproduce using the same setup, though. Can you provide the following information? It might useful:
- The output of `sessionInfo()`
- A copy of the log files: https://support.rstudio.com/hc/en-us/articles/200554756-RStudio-Application-Logs

**Comment by EvPop21** [comment]
@ronblum Thank you for your comment. Please see the output of `sessionInfo()` below:
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3

**In the log file the only lines in there are the line below repeating many times over the past two weeks:**
ERROR system error 10053 (An established connection was aborted by the software in your host machine) [request-uri: /events/get_events]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:113; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:118
