### ISSUE TITLE
RStudio does not prompt for restart after changing a preference via command palette requiring restart

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8879]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1541
    OS Version      : macOS 11.1
    R Version       : 4.0.3

### Steps to reproduce the problem

Change a preference requiring restart via the command palette; for example:

<img width="632" alt="Screen Shot 2021-02-02 at 11 57 21 AM" src="https://user-images.githubusercontent.com/1976582/106655220-edb6cf00-654d-11eb-9792-1f5cc232701d.png">

### Describe the problem in detail

Although we prompt to restart when that preference is changed via the preferences pane, we don't do so here.

https://github.com/rstudio/rstudio/blob/d1cbdd276dca6fdf2e1c81c198f8ec3016db6f6b/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/ConsolePreferencesPane.java#L102-L107

### Describe the behavior you expected

After the palette is closed, the user should be prompted to restart, to enable the newly-changed settings.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
It would be great to have a "requires restart" flag right in the prefs schema so rest of UI could just automatically do the right thing (probably reasons that's not so simple).

**Comment by jmcphers** [comment]
The reason it isn't so simple is that the prefs schema is a JSON schema, which _itself_ has a schema (something I refer to mentally as the "JSON Schema Schema"). It would be nice to extend that with other metadata like "changing this pref requires restart" or "hide from the command palette" or "this is a file path, not a regular string", etc. but the last time I looked I didn't see a natural place to do that. Perhaps we need a separate file that contains this extra metadata.
