### ISSUE TITLE
Document scrolls up unpredictably when executing a code chunk in a list

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8883]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1103, Wax Begonia 

### Steps to reproduce the problem

1. Create a long R Markdown document with several pages worth of any kind of content.
2. At the bottom of the document, add a list.
3. Add an executable R chunk nested inside a list item (by indenting it 4 spaces)
4. Ensure the editor is in visual mode.
5. Run the R chunk.

Here's an example of one such chunk (in a list which is itself in a long document):

https://github.com/hadley/r4ds/blob/2390ed29b182824f8d72ef7a30e365775395fc6f/relational-data.Rmd#L549-L551

### Describe the problem in detail

The document scrolls dramatically, to the top or near the top.

### Describe the behavior you expected

If the document scrolls at all, it should only be to reveal the output of the code chunk that was executed.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
First reported by @slopp and @JosiahParry.

**Comment by ronblum** [comment]
Validated in
- RStudio Desktop 1.4.1572 on MacOS 11.3
- RStudio Server 1.4.1578 on Ubuntu 20.04.2 using Firefox on MacOS 11.3
using the code linked to above.
