### ISSUE TITLE
'badly formed function expression' error from debugger

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8885]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.1545
    OS Version      : macOS  11.1
    R Version       : R version 4.0.3 (2020-10-10)

### Steps to reproduce the problem

Run the following script:

```
renv:::enumerate(list(a = 1), function(key, value) {
   browser()
})
```

### Describe the problem in detail

The following is printed in the console:

```
Called from: f(n[[i]], x[[i]], ...)
Error in deparse(object, width.cutoff = 500L) : 
  badly formed function expression
```

### Describe the behavior you expected

No error.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1591, R Version - 4.0.3, Windows 10 - Desktop

Missed the dailies where the error was reproducible, but I can confirm that the included script is no longer throwing an error in console and that behavior is consistent across 1.3 Apricot Nasturtium, 1.4 Tiger Daylily, and 1.4 Juliet Rose.
