### ISSUE TITLE
Debian build links against wrong libssl

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8894]
**Steps to reproduce:**
* Have a debian bullseye system.
* Install the latest daily build of RStudio.
* Launch the newly installed RStudio.

**Expected behavior:** the installer should either link to libraries that are available in debian, or bundle such requirements if not possible.

**Actual behavior:** rstudio: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory

**Comment by kevinushey** [comment]
Do the Ubuntu Bionic builds work here? (https://dailies.rstudio.com/rstudio/oss/bionic/x86_64/)

**Comment by david-cortes** [comment]
Yes, it works correctly.

**Comment by kevinushey** [comment]
Then I think we need to advertise on the daily builds page that the "Ubuntu 18+" builds are also compatible with Debian 10+.

https://dailies.rstudio.com/

We do make that more clear on the official download page:

https://rstudio.com/products/rstudio/download-server/debian-ubuntu/

<img width="1017" alt="Screen Shot 2021-02-04 at 1 13 30 PM" src="https://user-images.githubusercontent.com/1976582/106955936-c8ab9300-66ea-11eb-879b-1f8d42db6c15.png">

**Comment by ronblum** [comment]
See #7515 regarding the names of the downloads at https://dailies.rstudio.com.

**Comment by tzycce** [comment]
Still happens and now debian 11 is the current stable.
