### ISSUE TITLE
Visual markdown editor breaks (hardcodes) numbered examples

### ISSUE THREAD

**Issue by jdutant** [rstudio/rstudio#8896]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  irrelevant
    R Version       :  irrelevant

### Steps to reproduce the problem

Enter the following in a blank R Markdown document:

```markdown
(@test) This is a numbered example.

The reference (@test) will also be turned into a number.

(@) A more interesting example.
```

Switch the visual editor mode and back. The code becomes:

```markdown
(1) This is a numbered example.

The reference (1) will also be turned into a number.

(2) A more interesting example.
```

### Describe the problem in detail

Numbered examples and crossreferences to them are harcoded
when switching to the visual markdown editor. Once they are
hardcoded there is no easy way to reorder them or insert
new ones in-between --- we have to renumber everything 
manually. This defeats the point of using them. 

I recently edited an article with 50+ continuous numbered examples.
Imagine having to renumber them manually if the author has to 
drop item 23, and fixing all the crossreferences. 

### Describe the behavior you expected

The visual markdown editor should leave the markup as is. 

Probably the intention behind processing them upon the
switch to visual editor was to ensure no code was visible
in the visual editor. But I think in this particular
case this is a bad idea: those of us who do use 
this markup do it precisely because we want to
avoid hardcoded numbers and hardcoded
crossreferences. We'd rather have `(@ref)` markup
in our visual editor than not being able to use
it at all.

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jdutant Thank you for raising the issue! We'll review it as we continue development of RStudio, including the visual markdown editor.

**Comment by ronblum** [comment]
Note: I can reproduce this in
- RStudio Desktop 1.5.1450 on MacOS 11.3
- RStudio Server 1.5.1433 on Ubuntu 20.04

**Comment by jjallaire** [comment]
The problem we've run into here is that Pandoc doesn't round-trip example lists in markdown (i.e. when writing markdown from a Pandoc AST node that has an example list, you get a numbered list). For example, consider this markdown:

```markdown
(@) My first example
(@) My second example
```

Run this bash command to "round trip" it through the pandoc AST (JSON representation) and back to markdown (this is essentially what the visual editor does when load and save a document):

```bash
pandoc example.md --to json | pandoc --from json --to markdown
```

You get the following markdown:

```markdown
(1) My first example
(2) My second example
```

Once pandoc supports writing example lists using `(@)` we can definitely support this in the editor. In the meantime, I think the correct behavior is for the visual editor to refuse to load if there are example list items in the markdown source (as you point out the round trip is destructive and I doubt anyone would want to live w/ the results of this). I'll work on this.

**Comment by jjallaire** [comment]
Addressed with: https://github.com/rstudio/rstudio/commit/24ede65648dbd97633db471a31bc1b099bd46d55

**Comment by astayleraz** [comment]
Verified in version 2021-07.0.285-2 the new alert warning in the case there is an example list and the user cannon use the visual editor. Also added an automated test for this case. Closing issue.
