### ISSUE TITLE
Change font size of a ggboxplot

### ISSUE THREAD

**Issue by tutaabsoluta** [rstudio/rstudio#8899]
Hi, i want to change the size if this ggboxplot significance results.

![000083](https://user-images.githubusercontent.com/78579628/106988322-2664cd00-6735-11eb-873a-5940e0aa2aac.png)

**Comment by jan-glx** [comment]
Welcome to Github & R, @tutaabsoluta !
Github issues are usually meant for bug reports (about errors in the code of the repository) only. When you opened this issue you should have seen something like: 

> Ask a Question
> The issue tracker is not for questions -- please ask questions at https://community.rstudio.com/c/rstudio-ide.

However, your question does not even seem to be about `rstudio` but about `ggpubr` or `ggplot2` so please **close this issue** here and consider googling for the answer and if you can find the answer asking your question on e.g. Stackoverflow. Just make sure to provide a reproducible example there and make more clear what you mean by "change the size if".
