### ISSUE TITLE
Win, Rstudio 1.4, Rmarkdown SQL chunk. Special chars fails (encoding). Works in 1.3

### ISSUE THREAD

**Issue by hbachdk** [rstudio/rstudio#8900]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 7 x64 (build 7601) Service Pack 1 and Windows 10 x64 (build 18363)
    R Version       : 4.0.3 
    
    locale: LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252

### Steps to reproduce the problem

`````
```{r}
library(tidyverse)
library(DBI)
```

```{r}
mydb <- dbConnect(RSQLite::SQLite(), "")
testdb <- tribble(~variable_name_normal, ~variable_name_spec_ø,
                  'value', 'value',
                  'æøå', 'æøå')

dbWriteTable(mydb, 'test_table', testdb, overwrite = TRUE)
```

```{sql, connection='mydb', output.var='local_file'}
select
  variable_name_normal,
  variable_name_spec_ø 
from test_table
```
`````

Error msg:
```
Fejl: no such column: variable_name_spec_Ã¸
Failed to execute SQL chunk 
```

### Describe the problem in detail
In 1.4 the code in a SQL chuck are send to SQL server with wrong encoding
In the provided sample "ø" is rendered as "Ã¸" and this triggers a parsing error on the SQL server side

### Describe the behavior you expected
Spec chars are encoded as they are written inside the SQL chunk when passed on to the SQL server

Note:
It works on windows in Rstudio 1.3 (all other settings equal)
It works on my Mac also in Rstudio 1.4. 
Fails on Win 7 and Win 10 at least with DK codepage

Brgds. Henrik

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Most likely fixed by ensuring the code is passed along here as UTF-8:

https://github.com/rstudio/rstudio/blob/e92d8790f8d135fc2e390b69ffcdbb917106729e/src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp#L440-L445

**Comment by kevinushey** [comment]
Appears to be fixed for me in the latest daily builds of RStudio.

<img width="485" alt="Screen Shot 2021-03-16 at 11 45 16 AM" src="https://user-images.githubusercontent.com/1976582/111363287-15b94800-864d-11eb-8387-1de86666a2e6.png">

**Comment by hbachdk** [comment]
Yes - that looks perfect...
I will download latest build  :-)
Thanks for heads up

/Henrik

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1637
    OS Version      : Windows 10
    R Version       : 4.0.3

Verified that characters now appear to be encoding correctly. Tested that the "ø" character correctly displays as "ø" in an sql database.
