### ISSUE TITLE
Incorrect source sentinel file written on suspend

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#8903]
### System details

    RStudio Edition : RStudio Server / Server Pro
    RStudio Version : 1.4.x

### Steps to reproduce the problem

1. In a terminal, navigate to `~/.local/share/rstudio/sources`
2. Remove all subdirectories under `sources` (be sure you have no unsaved file changes you wish to keep - you are blowing away your source database)
3. Launch a new session
4. verify no restart or suspend files are present by running `find . -iname "restart_file"` and `find . -iname "suspend_file"` underneath the `sources` dir
5. Suspend the session from the homepage
6. Check for restart/suspend files again

### Describe the problem in detail

When suspending the session, a restart file is created instead. This is incorrect and can cause other subtle issues in the source database.

### Describe the behavior you expected

A suspend_file is created when suspending. The restart_file is only created when restarting the R session.

**Comment by kfeinauer** [comment]
@R-Hannibal This is a new bug for Tiger Daylily. Fix was committed in https://github.com/rstudio/rstudio/commit/2a95bc060e65e3fc044e47615666ceda68b6967b. The notes in this ticket should be enough to test.

**Comment by R-Hannibal** [comment]
Re-opening so we can test the fix against Tiger-Daylily builds.

**Comment by astayleraz** [comment]
I verified in Version 1.4.1106-4 that when I followed the steps I only saw a file named suspend_file. Closing issue as fixed.
