### ISSUE TITLE
Error saving file (now outside of Dropbox)

### ISSUE THREAD

**Issue by ninohardt** [rstudio/rstudio#8904]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1103
    OS Version      :  Windows 10
    R Version       :  4.0.2

### Steps to reproduce the problem
Save an .r file.
Specifically, save a file that is part of another project, while the other project might (or might not) be open in a separate RStudio instance.
The project is saved outside of a Dropbox folder, just under c:/users/username/rproject

### Describe the problem in detail

I think fellow RStudio users already have nightmares about this error:
Error message
![image](https://user-images.githubusercontent.com/4387287/107079391-cd8d4700-67bd-11eb-8813-e744be797973.png)

### Describe the behavior you expected

It should just save!

How about moving all that .Rproj.user stuff somewhere else, like a local database with meta-information? That might fix a lot of issues.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
@ninohardt Thank you for filing the issue! I’m unable to reproduce it in RStudio Desktop 1.4.1103 on Windows 10. Have you by chance used a previous version of RStudio, such as 1.3.1093, and was this a problem in a previous version of RStudio? I might have missed or did your steps differently than you did so if there are any more details you can add that could help. I was not sure if the r file or the project file should be saved in drop box and opened on another machine via drop box, so if you can be clear on all the steps to be able to reproduce this 100% of the time that would help. It sounded like the file might not have to be open in another rstudio instance and if that was on the same machine or a different one? What ever you can reproduce consistently and with the least amount of steps to reproduce will help us out to try to reproduce it on our end. Thank you.

**Comment by ninohardt** [comment]
No, I filled it out correctly, it is the recent 1.4.11 version.

Scenario:
[Project A is open, on dropbox with sync deactivated] [Project B is open, not on dropbox]
I am in [Project A] and open a file from [Project B]. I try to save that file, that is in Project B, in the RStudio session with Project A open. I get the error. I close Project B, I still get the error.

It is somewhat sporadic, as in I can't reproduce it 100% of time time. When the Dropbox problems first appeared (was that like 2 years ago?) issues were also not there 100% of the time.

I just don't see how this is Dropbox related, because Project B with the relevant file is completely outside of a dropbox.

Maybe you could shed some light on the internals, that would help setting up a reproducible scenario. Does opening a project  create lock files? Why is this the only IDE that has these weird errors?

**Comment by astayleraz** [comment]
@ninohardt Are you editing a c++ file by chance? Your issue seems similar to this one: https://github.com/rstudio/rstudio/issues/6940

**Comment by ninohardt** [comment]
Yes, it was on a .cpp file. When I tried to recreate the problem, I didn't use a .cpp file, and so I failed to replicate it there. Thanks for the pointer!
