### ISSUE TITLE
Return code and errno aren't checked after sysconf() system call 

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#8908]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1093
    OS Version      : FreeBSD 12.2
    R Version       : irrelevant

### Steps to reproduce the problem

The call here https://github.com/rstudio/rstudio/blob/master/src/cpp/shared_core/system/User.cpp#L54 doesn't check the error code.

The sysconf(3) manpage says that the return code -1 stands for error:
```
RETURN VALUES
     If the call to sysconf() is not successful, -1 is returned and errno is
     set appropriately.  Otherwise, if the variable is associated with
     functionality that is not supported, -1 is returned and errno is not
     modified.  Otherwise, the current variable value is returned.
```
and it fails and RStudio Server fails:
```
$ sudo /usr/local/lib/rstudio-server/bin/rserver 
05 Feb 2021 21:30:50 [rserver] ERROR Unexpected exception: vector
```

The code even mentions that ```some systems return -1```
```
      // Get the maximum size of a passwd for this system.
      long buffSize = ::sysconf(_SC_GETPW_R_SIZE_MAX);
      if (buffSize == 1)
         buffSize = 4096; // some systems return -1, be conservative!
```

**Comment by kevinushey** [comment]
Although we don't explicitly test the value `-1`, we do check for negative values and set something "sane" here:

https://github.com/rstudio/rstudio/blob/master/src/cpp/shared_core/system/User.cpp#L53-L56

and that should've been fixed in https://github.com/rstudio/rstudio/commit/82dfb766faf3761aab7dae0878c22b6e015ca8e7.
