### ISSUE TITLE
rsession stays after the rserver daemon is gracefully stopped

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#8917]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1093
    OS Version      : FreeBSD 12.2
    R Version       : irrelevant

### Describe the problem in detail

When ```rserver``` is running ```rsession``` is its child:\
```
-+= 00001 root /sbin/init --
...
 |-+= 65621 nobody /usr/local/lib/rstudio-server/bin/rserver --server-user nobody
 | \--= 65653 yuri /usr/local/lib/rstudio-server/bin/rsession -u yuri --session-use-secure-cookies 0 --launcher-token A263DC96 --r-restore-workspace 2 --r-run-rprofile 2
...
```
but after ```rserver``` is killed in a graceful way in order to stop the daemon ```rsession``` stays and changes its parent to the ```init``` process:
```
-+= 00001 root /sbin/init --
...
 |--= 65653 yuri /usr/local/lib/rstudio-server/bin/rsession -u yuri --session-use-secure-cookies 0 --launcher-token A263DC96 --r-restore-workspace 2 --r-run-rprofile 2
...
```

All relevant processes should be terminated automatically when the service is stopped.

**Comment by ronblum** [comment]
@yurivict Thank you for raising this! We'll review the issue as we continue development of RStudio. One question: What are you using to kill the process gracefully?

**Comment by yurivict** [comment]
> What are you using to kill the process gracefully?

I run RStudio server as a FreeBSD service. The ```service(8)``` command ```"service rstudio-server stop"``` kills the ```rserver``` process with the ```TERM``` signal.

The process is supposed to handle the ```TERM``` signal and perform a cleanup that should include killing all other server processes spawned by it during its lifetime.

**Comment by yurivict** [comment]
ping.

**Comment by mikebessuille** [comment]
You should stop the server using rstudio-server stop, as it performs a number of cleanup activities that are not performed if you stop the service the way you've done above.  This is by design currently.  See the related discussion on systemd / systemctl management in https://github.com/rstudio/rstudio-pro/issues/2585
