### ISSUE TITLE
Web session sometimes errors out when the same user is already logged in from another browser: Error occurred during transmission

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#8918]
### System details

    RStudio Edition : Server
    RStudio Version :  1.3.1093
    OS Version      : FreeBSD 12.2
    R Version       : irrelevant

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/271906/107136174-c8132800-68b5-11eb-98d2-c35412c8a50d.png)

**Comment by ronblum** [comment]
@yurivict Thank you for raising the issue! I can't reproduce it, though—I'm seeing the expected message:
<img width="533" alt="same_login" src="https://user-images.githubusercontent.com/31009952/107256218-34ea0780-6a07-11eb-83e2-5957e453476b.png">

Do you get this most of the time? Also, when you run into the issue, are you doing something specific, such running a script, or under all circumstances?

**Comment by yurivict** [comment]
I saw the problem when I re-typed the same URL in another browser with the same user logged in in both browsers. Sometimes the message is ```R Session Disconnected``` (like you pasted), and sometimes the error like I pasted.

**Comment by yurivict** [comment]
I can reproduce it with http://localhost:8787/ opened in 2 Firefox tabs for the same user.

Open it in one tab, then in the second tab, then reload the first tab, then reload the second tab. Eventually one of them fails instead of showing the "Reconnect" message.

I don't think that this is FreeBSD specific. This is a web-related problem, or a Firefox compatibility problem.

**Comment by yurivict** [comment]
Same error in the same tab in Chrome when clicked on the "Terminal" tab:

![image](https://user-images.githubusercontent.com/271906/107279593-19353000-6a0c-11eb-9d83-c3b0691fcf0a.png)

**Comment by yurivict** [comment]
ping.

**Comment by mikebessuille** [comment]
I'm not sure what you are expecting.  You cannot use the same URL in two different browsers (cannot connect to the same session with the same user in two browsers).  This looks to me like it's working as designed.
