### ISSUE TITLE
Add "Create R Markdown file from R script" button to R source editor

### ISSUE THREAD

**Issue by stragu** [rstudio/rstudio#8919]
In RStudio 1.4.1103, we have a "Compile report from R script" button, which is great for a quick and easy output. However, an **extra button to "Create R Markdown file from R script"** would be wonderful: it would allow to get to the intermediate stage and further edit and customise the document before compiling to a wider range of formats.

The three main steps in the conversion would be:

* Wrap (valid) blocks of code into chunks
* Convert (blocks of) comments to plain markdown text (without breaking valid blocks of code, e.g. comment lines inside a function definition or a loop or a pipeline)
* Convert comments that are used as headings (e.g. finishing with `####` or `----`) to markdown headings of level 2

Comments that share a line with code would be kept inside the corresponding chunk.

This could be extended to other source editors like Python by changing the language in the chunk headers.

**Comment by ronblum** [comment]
@stragu Thank you for the suggestion! We'll consider during our ongoing issues review and RStudio development.
