### ISSUE TITLE
Support save and load Python workspace in Rstudio

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#8920]
I am using Python in Studio and very enjoy it. However, an inconvenient is whenever I close Rstudio, I have to run Python code chunk again to load objects. Is it possible to create a feature like R, that everytime we close Rstudio, it will save a workspace and load for the next time? 

Thank you for your all supports!

**Comment by ronblum** [comment]
@ntluong95 Thank you for the suggestion! We'll review it as we continue to expanding RStudio's Python features.

**Comment by kevinushey** [comment]
One of the primary challenges here is that Python's `pickle` module doesn't support saving + loading Python workspaces out of the box. (In theory [dill](https://pypi.org/project/dill/) would get us closer to that.)
