### ISSUE TITLE
New citation source for Insert Citation dialog in the visual editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#8921]
It would be helpful to have "R packages" as a citation source listed on the left side of the Insert Citation dialog in the visual editor. This source would list the packages the user has installed and allow them to pick a package and easily insert its citation, also adding the bib entry for it to the bib file for the document.

**Comment by melissa-barca** [comment]
I've verified this is present in 2022.01.0-daily+197.pro1. Automation that an R Package citation can be added and removed is included in this PR: `rstudio/rstudio-ide-automation#515`
