### ISSUE TITLE
Rmd, Visual Mode, inconsistent reference @ symbol detection

### ISSUE THREAD

**Issue by HannesOberreiter** [rstudio/rstudio#8924]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  darwin19.6.0
    R Version       : 4.0.3

### Steps to reproduce the problem

Create a Rmd File, switch to visual mode. `@` symbol for references is not always recognized.

### Describe the problem in detail

If I write in the visual mode the `@` symbol for references is not always recognized and it gives me no autocompletion. The problem is very inconsistent and deleting and writing it new or switching between visual and markdown mode helps. Especially if I have multiple citations in a bracket, this happens frequently to me `[@correct; @nope; @correct, ...]`.

It is only a visual problem, so it is not that big of a deal. I can still write my citation and references without the autocompletion and after compiling it sets the correct references in the output. 

### Describe the behavior you expected

`@` in visual mode should first give me the autocomplete option and only if I press the back (del) button it should change to the `@` symbol by itself (as I think it is intended). 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@HannesOberreiter Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.4.1540 on MacOS 11.3. As you describe, it's intermittent. We'll review this as we continue developing RStudio and the visual markdown editor.

Note: Another workaround seems to be deleting the `@` that isn't recognized and typing `@` again.

**Comment by dragonstyle** [comment]
Moving this - reproducing it is possible, but inconsistent. The fix is going to be risky - so moving to the next milestone when we'll a little more time to consider the best and safest approach.

**Comment by HannesOberreiter** [comment]
@dragonstyle I could not reproduce it anymore, seems to be solved. 

Thanks for your effort.
