### ISSUE TITLE
Code editor and console frozen while executing codes

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#8925]
### System details

    RStudio Edition : 
    RStudio Version :  1.4.1554
    OS Version      :  Windows 10 Enterprise 20H2 x64
    R Version       : 4.0.3

### Steps to reproduce the problem

Run an R script that about 1000 lines which calls a function (has `read_xlsx()` and `tidyverse`  functions) 50 times. Inside the function, there are also multiple `print()` for debugging. 

### Describe the problem in detail

When the code first ran, I could go to the code editor and scrolled up and down a little bit but it felt really sluggish. 
After a few seconds, both the code editor and the console frozen for a while. The print out message from the function did not show up each time the code called it within a loop. The console was only updated at the end of that function then froze again.

Note that I did not have this problem with version 1.4.1103.

### Describe the behavior you expected

- Nothing is frozen.
- Be able to work on the code editor while it's running. 
- All print out message show up in the console as the code loops through the function.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tungmilan Thank you for raising this! A few questions:
- Does the problem only occur with code that's 1000 lines long, or also for short scripts?
- Does it happen only when the functions you mention are included, or do other functions cause the failure as well?
- Can you provide sample code? It will help in trying to reproduce and investigate the issue

**Comment by tungmilan** [comment]
Thanks for the quick reply! I have to go back to the previous version for now. I'll try to produce a reprex on my other computer later this week.

**Comment by tungmilan** [comment]
Looks like this problem has been fixed with the latest preview 1.4.1120 version. Thanks!

**Comment by ronblum** [comment]
@tungmilan Great to hear, and thanks for checking!

**Comment by tungmilan** [comment]
FYI, this problem returned for both preview version `RStudio-1.4.1711` and the daily version `RStudio-1.5.42.exe`

**Comment by tungmilan** [comment]
I tried version 1.4.1717 version and did not experience the issue anymore
