### ISSUE TITLE
renv causing RStudio to fail to start

### ISSUE THREAD

**Issue by rschauner** [rstudio/rstudio#8928]
I'm going to preface this with this: I have no idea how to supply a reproducible example. 

When I try to start my RStudio project that uses renv, RStudio will give the "R failed to start screen" but I can open a new RStudio session outside a project and other projects that don't use renv. I have used Visual Studio Code to do some R development but working with reticulate and radian in VSCode is next to impossible. 

Things I've tried:
1. Update RStudio to latest version
2. Completely reinstalling R and RStudio locally (remove pref files, etc)
3. Using a parsed down version of the project on RStudio Server (some system libraries aren't available to install everything)

RStudio Server works better as I can actually run code, but there are issues that don't make it a good option as the sole workspace.

What information can I give you to help even start to understand what is happening?

System Information:
OS: MacOS 10.15.7
R: 4.0.3
RStudio: 1.4

**Comment by kevinushey** [comment]
The fact that the error message indicates a failure to use RStudio's `rs_readUserPref` API makes me think this is an issue in RStudio itself (but still no idea how to reproduce).

**Comment by rschauner** [comment]
Would it be helpful to provide the renv.lock file and enviorment.yaml?

**Comment by mafw** [comment]
Are you by any chance loading `retiuclate` on startup or using `renv` to keep track of your python modules? It seems that Rstudio has problems loading `reticulate` when starting, as documented in this [thread](https://community.rstudio.com/t/rstudio-crashes-during-start-up-when-package-reticulate-is-installed/93574/7)

**Comment by rschauner** [comment]
I was using `renv` to keep track of python modules for those R packages that need some.

**Comment by mafw** [comment]
So that could explain why Rstudio is crashing when you launch it. Try commenting out the line `source("renv/activate.R")` in your `.Rprofile` file for the project and see if that helps. The next step would be to deactivate python integration for the project by running `renv::use_python(FALSE)` to check if that solves the problem. My understanding is that the newest version of Rstudio has some problems loading python when starting.

**Comment by rschauner** [comment]
Yep! Disabling python integration got Rstudio to start normally. Is there are fix in the works?

**Comment by kevinushey** [comment]
Sorry for the delayed response. Do you still see this with the latest daily builds of RStudio (https://dailies.rstudio.com/)?

**Comment by NBatyrbekova** [comment]
I encountered the same situation after having updated RStudio, R and all packages.
