### ISSUE TITLE
RStudio reliably crashing when executing RMarkdown chunk importing more than 1 CSVs-- But when I (a) already have objects in my environment, or (b) break a chunk of multiple imports into smaller chunks of 1 import, it runs and does not crash

### ISSUE THREAD

**Issue by JacobElder** [rstudio/rstudio#8929]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5019
    OS Version      : Mojave, 10.14.6
    R Version       : 4.0.2

### Steps to reproduce the problem

This seems to be a difficult issue to reproduce because it is something I experience for my scripts across two different computers when I import from a remote server or Google Drive, but I am not sure how to have someone on external hardware interfacing with a different server or Google Drive replicate.

### Describe the problem in detail

If I ever try to execute an entire R Markdown script with an empty environment, and I have a chunk at the beginning for importing all my files like below, it will reliably crash:

![image](https://user-images.githubusercontent.com/16260312/107290738-eb57e780-6a1b-11eb-8bbb-ac3d55d6f624.png)

However, if I break my chunk into scripts of single imports, for example, use a chunk with only one import, then it will import fine. See below for example:

![image](https://user-images.githubusercontent.com/16260312/107290751-f14dc880-6a1b-11eb-8df6-58081091139d.png)

Additionally, if I have any object in my environment before I execute the chunk with multiple imports, then it will run fine. Below is an example with df1 as an object in my environment but it could easily be anything, even just "test <- 1". If anything is in my environment, the chunk of imports will execute.

![image](https://user-images.githubusercontent.com/16260312/107290768-f6ab1300-6a1b-11eb-87f0-8f7bbe7aa90f.png)

So my dilemma is:
R Studio will crash for R Markdown scripts with a chunk with multiple imports consistently and reliably.

My solutions are:
(1) Import one at a time in separate chunks
(2) Execute the chunk of multiple imports with an object in environment

These are not great fixes as sometimes you want to execute a script all at once with an empty environment or you don't want to split all your imports into a chunk per import.

Miscellaneous notes:
- This occurs for all CSVs; appears to be regardless of CSV size
- I have latest version of R and RStudio. This persists across multiple R and RStudio versions.
- Oddly, it does not crash in a normal (.r) script. It is exclusive to RMarkdown
- It usually takes any more than 1 CSV to crash.
- It crashes regardless of when I load my libraries. Does not matter if I load libraries before or after
- Occurs across multiple computers as well
- If I use data.table::fread, it will import multiple csv files in a chunk the first time I execute. If I attempt to do it again, it will crash.
- I believe the issue primarily occurs when importing from a remote server or Google Drive

### Describe the behavior you expected

As described above, I expect for the multiple imports within one chunk to import successfully without crashing. It appears to be an RMarkdown specific issue in which multiple CSVs crash within a chunk but one CSV does not and a standard R file does not crash.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@JacobElder Thank you for raising the issue! I can't reproduce it in RStudio Desktop 1.2, 1.3, and 1.4 on MacOS, though.
- Do you run into the issue in the current version of RStudio. 1.4.1103? https://rstudio.com/products/rstudio/download/#download
- Does the problem occur if you load local files, or only with Google Drive?
- Can you provide sample files so that we can try to reproduce exactly what you're experiencing?

Thanks!
