### ISSUE TITLE
Behaviour when open RStudio in multiple window-projects

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#8933]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103 
    OS Version      :  Debian 9
    R Version       : 3.6.3

### Steps to reproduce the problem

I have an RStudio project `X` open. I execute Rstudio again to open another project/session/window in which I want to work in no project. If this window opens with the same project `X`, then let's `Close Project`.

### Describe the problem in detail

In previous versions of RStudio, after closing the project `X`, the workspace loaded a kind of `default` environment distinct of that of the project `X` (that saved in `~/.RData`) and the working directory was the default one `~`. Now, when I close the project in the second window, the environment and the working directory do not change, are those of the previously open (and yet currently open in another window) project `X`.

And, if I change the working directory and the workspace of the none-project RStudio session, once these projects are closed, the next time I execute to open twice RStudio, one window is the one for project `X` (this is fine) and the other is the one for the none-project RStudio session, but again with the working directory and environment of the project `X`.

### Describe the behavior you expected

The old one.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I suspect this is a duplicate of https://github.com/rstudio/rstudio/issues/8683.

**Comment by iago-pssjd** [comment]
Thanks! @kevinushey, at least it seems to be a consequence of that issue, so I close this one.

**Comment by R-Hannibal** [comment]
@iago-pssjd - thanks again for bringing this issue to our attention 👍.

We have a fix available in our latest preview builds (available [HERE](https://rstudio.com/products/rstudio/download/preview/)) if you'd like to try it out.
