### ISSUE TITLE
Tabbing for second-level list items doesn't work in tables in visual mode

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#8935]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1103
    OS Version      : macOS 11.2
    R Version       : 4.0.3

### Steps to reproduce the problem

In the visual editor:

1. Create a bulleted list and type something, then hit enter and then tab, this creates a second-level list item where you can type something else.
2. Insert a table. In one of the cells of the table try to repeat Step 1 -- create a bulleted list and type something (this works), then hit enter and then tab (this doesn't work, moves the cursor to the next cell).

Below is a minimal Rmd that exemplifies this.

```
---
output: html_document
---

-   Hi

    -   hello

+--------+-------+
| -   Hi | hello |
| -      |       |
+--------+-------+
```

### Describe the problem in detail

It's not possible to get a second-level list item in a table in the visual mode.

When this didn't work I tried converting to source mode to get an indented list, but the result was even more surprising. See below for a screengrab -- note that the text for the second line gets split and part of it is moved to the next cell. This may not have been the right way to address the original problem, but the text getting split seems undesirable nonetheless.

https://user-images.githubusercontent.com/5965649/107404313-1286e580-6afe-11eb-9b4a-a57c7f4be7f8.mov

### Describe the behavior you expected

I expected tabbing to work inside a table in the same way it works outside a table, even though I realize tab moving the cursor to the next cell can be useful when not writing a list.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mine-cetinkaya-rundel! I'll mark this as an enhancement, because we're trying to get two around having two meanings to <kbd>Tab</kbd>, depending on the context.

By the way, you can use <kbd>Format -> Bullets & Numbering -> Sink Item` and `Lift Item` to change the item level, even within a table.

**Comment by mine-cetinkaya-rundel** [comment]
Ah, thanks for the tip @ronblum!

**Comment by jjallaire** [comment]
Addressed here: https://github.com/rstudio/rstudio/commit/481c412a01d83fcfd71bf70def43e0a7698cdc37

**Comment by astayleraz** [comment]
I verified in 2021-08.0 Build 305-1 that tabbing, in this case, will now add a second-level list. I was not able to add an automation test for this case. Closing issue.
