### ISSUE TITLE
API for document activation

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#8938]
Distilled from a Slack conversation with @kevinushey

It would be nice if one could explicitly activate a document via its path or ID. My initial wish pertains to rstudioapi, but apparently it needs to happen here first, then be exposed there.

Other challenges noted with current API:

  * `rstudioapi::navigateToFile()` is not synchronous, which leads to great puzzlement when subsequently trying to determine/set/act on the active document
  * `rstudioapi::navigateToFile()` should return useful data, such as the document ID, so you can capture and use in subsequent calls, e.g. `rstudioapi::setSelectionRanges()`

For context, the actual task that motivated this issue was to open a particular file, make sure it's focused / activated, and do "Select all".

**Comment by jennybc** [comment]
Please don't close this issue.

**Comment by romainfrancois** [comment]
Moved back to `in progress` until #10521 is dealt with

**Comment by jgutman** [comment]
Verified in 2022.06.0-daily+104 on Windows 11 (build is not yet available for MacOS, but should work the same across platforms).
