### ISSUE TITLE
Show Traceback doesn't function when Limit visible console output on

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8940]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.1560
    OS Version      : macOS Big Sur 10.16
    R Version       : R version 4.0.3 (2020-10-10)

### Steps to reproduce the problem

Run a command that produces an error with a traceback; for example:

```
f <- function() stop()
g <- function() f()
h <- function() g()
k <- function() h()

k()
```

Then, try to click Show Traceback in the console output.

<img width="679" alt="Screen Shot 2021-02-09 at 1 23 04 PM" src="https://user-images.githubusercontent.com/1976582/107430398-f3765c80-6ad9-11eb-939c-d7b9bcfb10a4.png">

### Describe the problem in detail

No traceback is shown.

### Describe the behavior you expected

The traceback should be shown.

If I turn 'Limit visible console output' back to off, restart the IDE, and then re-run these steps, it appears to work.

**Comment by adamconroy** [comment]
Very interesting. I fixed this back in October, at least it appeared that I had in my dev environment. I wonder what is happening. https://github.com/rstudio/rstudio/pull/7942/files

**Comment by astayleraz** [comment]
Verified in Version 1.4.1621-2 that the traceback is working in the console with the limit enabled and disabled and added an automated test to check this. Closing issue.
