### ISSUE TITLE
CSV reader assumes that columns starting with missing values are logical

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8945]
**Steps to reproduce:**
* Produce a CSV file that would have a column starting with many missing values. Example:
```r
df = data.frame(col1=rep(NA, 1e5), col2=rep(NA, 1e5))
df$col1[1e2] = 1
df$col1[1e5] = 5000
write.csv(df, "problem.csv", row.names=FALSE, na="")
```
* Try to import such CSV from `File` -> `Import Dataset` -> `From Text (readr)`.

**Expected behavior:** should get the types of the columns right, and offer selectable options that would let the user help the IDE get them right.

**Actual behavior:** if the first couple thousand values in a column are missing, will assume that the column is of type `logical`, which is a very questionable assumption (factor would be a better default). There is no button to select which type should such columns have if the first values are missing, and no option to set the search depth from there. The only thing one can do is to manually change the types of every column individually from logical to something else, and that is assuming that the user already knows what's in the CSV.

**Comment by kevinushey** [comment]
Presumedly this is because we generate our preview from the first 50 rows, and so entries that would change the assumed type aren't actually read.

We could probably use `guess_max` and `n_max` more appropriately here:

https://github.com/rstudio/rstudio/blob/92e3ca8861fe4e4ff8ca65f355e928eadf2d81cb/src/cpp/session/modules/SessionDataImportV2.R#L417-L431

**Comment by romainfrancois** [comment]
I tried to make it do `read_csv(n_max = <maxRows>, guess_max = Inf)` but this is user error https://github.com/r-lib/vroom/issues/392, that we may make more explicitly fail in https://github.com/r-lib/vroom/pull/393

We could lazily read the full data and extract the first few rows, but that may be too expensive: 

``` r
library(readr)

tf <- tempfile(fileext = ".csv")
df = data.frame(col1=rep(NA, 1e7), col2=rep(NA, 1e7))
df$col1[1e2] = 1
df$col1[1e5] = 5000
write.csv(df, tf, row.names=FALSE, na="")

system.time(df1 <- readr::read_csv(tf, n_max = 50))
#> Rows: 50 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> lgl (2): col1, col2
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#>    user  system elapsed 
#>   0.206   0.021   0.228
str(df1)
#> spec_tbl_df [50 × 2] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
#>  $ col1: logi [1:50] NA NA NA NA NA NA ...
#>  $ col2: logi [1:50] NA NA NA NA NA NA ...
#>  - attr(*, "spec")=
#>   .. cols(
#>   ..   col1 = col_logical(),
#>   ..   col2 = col_logical()
#>   .. )
#>  - attr(*, "problems")=<externalptr>

system.time(df2 <- readr::read_csv(tf, lazy = TRUE, guess_max = Inf)[seq_len(50), ])
#> Rows: 10000000 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> dbl (1): col1
#> lgl (1): col2
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#>    user  system elapsed 
#>  12.649   2.581  10.042
str(df2)
#> tibble [50 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ col1: num [1:50] NA NA NA NA NA NA NA NA NA NA ...
#>  $ col2: logi [1:50] NA NA NA NA NA NA ...
```

<sup>Created on 2021-12-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

but at least we would get the same types as what we get when executing the preview code and slicing. 

Maybe we should have some "Preview Options" ui ?

**Comment by romainfrancois** [comment]
``` r
library(readr)

temp_data <- function(n = 1e5) {
  tf <- tempfile(fileext = ".csv")
  df = data.frame(col1=rep(NA, n), col2=rep(NA, n))
  df$col1[1e2] = 1
  df$col1[1e5] = 5000
  write.csv(df, tf, row.names=FALSE, na="")
    
  tf
} 

tf5 <- temp_data(1e5)
tf7 <- temp_data(1e7)
```

when the file is not too big, types are correctly guessed
I suppose `guess_max` is just overuled

``` r
system.time(
  readr::read_csv(tf5, guess_max = 50)[1:50, ]
)
#> Rows: 100000 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> dbl (1): col1
#> lgl (1): col2
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#>    user  system elapsed 
#>   0.266   0.031   0.238
```

if the file is too big, it looks like `guess_max` is honored
and the reading time is ok, but then when we get to a cell that does not fit with the guessed
type, we get `problems()`

``` r
system.time(
  data <- readr::read_csv(tf7, guess_max = 50)
)
#> Warning: One or more parsing issues, see `problems()` for details
#> Rows: 10000000 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> lgl (2): col1, col2
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#>    user  system elapsed 
#>   5.601   0.366   0.659
data[1:50, ]
#> # A tibble: 50 × 2
#>    col1  col2 
#>    <lgl> <lgl>
#>  1 NA    NA   
#>  2 NA    NA   
#>  3 NA    NA   
#>  4 NA    NA   
#>  5 NA    NA   
#>  6 NA    NA   
#>  7 NA    NA   
#>  8 NA    NA   
#>  9 NA    NA   
#> 10 NA    NA   
#> # … with 40 more rows
```

perhaps we can promote this to the ui somehow

``` r
problems(data)
#> # A tibble: 1 × 5
#>      row   col expected           actual file                                   
#>    <int> <int> <chr>              <chr>  <chr>                                  
#> 1 100001     1 1/0/T/F/TRUE/FALSE 5000   /private/var/folders/4b/hn4fq98s6810s4…
```

<sup>Created on 2021-12-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

So I think we could use `guess_max` instead of `n_max` for the preview, and show the `problems()` if any somehow.

**Comment by cm421** [comment]
RStudio Edition : Rstudio Desktop
RStudio Version : 2022.02.0-daily+365
OS Version      : macOS 12.1
R Version       : 4.1.2

Verified with the following steps:
1. Generated some data using the provided code snippet in the QA section above
2. Imported the smaller CSV using `readr`. 
   1. Verified that the type for `col1` was `double` and `col2` was `logical`
   2. Verified that there were no problems importing the CSV by calling `problems(X1e5)`
3. Imported the larger CSV using `readr`. 
   1. Verified that the type for `col1` and `col2` was `logical`
   2. Verified that there _were_ problems importing the CSV by calling `problems(X1e7)`, and checking the footer in the `Import Text Data` window
       ```
       > problems(X1e7)
       # A tibble: 1 × 5
            row   col expected           actual file                
          <int> <int> <chr>              <chr>  <chr>               
       1 100001     1 1/0/T/F/TRUE/FALSE 5000   /Users/craig/1e7.csv
       ```
