### ISSUE TITLE
"Missing package dependencies" install command does not respect "repos" option

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#8946]
### System details

    RStudio Edition : Server Pro
    RStudio Version : 1.4.1103-4
    OS Version      : Ubuntu 20.04
    R Version       : Any

### Describe the problem in detail

When required packages of a an `.R` or `.Rmd` file are missing, RStudio suggests to install these in a yellow menu.
If a user decides to follow the suggestions, RStudio launches a "job" to install the packages.

However, neither the "repos" option of the current R session nor the one specified in the R Version wide `.Rprofile` is respected in this case.
Instead the RStudio CRAN mirror is used.

This is quite problematic if a fixed RSPM snapshot has been configured for many users in a distributed RSP environment.
Many people are tempted to click the suggested popup and then install R package versions which differ from the globally defined "repos" setting.

### Describe the behavior you expected

RStudio should respect the "repos" setting of the current session.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This should work as we do pass along the current repositories here:

https://github.com/rstudio/rstudio/blob/92e3ca8861fe4e4ff8ca65f355e928eadf2d81cb/src/cpp/session/modules/SessionDependencies.cpp#L537

**Comment by kevinushey** [comment]
The generated install script should be of the form:

```
options(repos = c(CRAN = 'https://cran.rstudio.com'), download.file.method = 'libcurl', HTTPUserAgent = 'RStudio Desktop (99.9.9); R (4.0.3 x86_64-apple-darwin17.0 x86_64 darwin17.0)')

options(install.lock = TRUE)

cat('Installing \'BH\' ...\n\n')
# BH -------------

utils::install.packages('BH', repos = 'https://cran.rstudio.com')

message('\n\n\u2714 Package \'BH\' successfully installed.')
```

So things definitely look "correct". Can you provide a reproducible example? What is the output of `getOption("repos")`?

**Comment by kevinushey** [comment]
Although it could be problematic that we're explicitly passing the CRAN repository URL here (and other places):

https://github.com/rstudio/rstudio/blob/92e3ca8861fe4e4ff8ca65f355e928eadf2d81cb/src/cpp/session/modules/SessionDependencies.cpp#L369-L370

Note that we use whatever `getOption("repos")[["CRAN"]]` reports here.

I suspect we should just leave that unset and rely on the globally-set `repos` option at the start of the script.

**Comment by pat-s** [comment]
Thanks Kevin!

> Note that we use whatever getOption("repos")[["CRAN"]] reports here.

This could be the issue - the name for the repo set in our case is not `"CRAN"` - hence it will then fall back to your default.

> I suspect we should just leave that unset and rely on the globally-set repos option at the start of the script.

In the assumption that at least one repo setting is usually set to a repository containing CRAN-like packages, this should work.

**Comment by astayleraz** [comment]
Verified in Version 1.4.1598-2 I was able to change my global repository and the download was using what I had set and showed in getOption("repos")[["CRAN"]] . Closing issue.
