### ISSUE TITLE
In Dataviewer, headers for date columns report "Unknown" type

### ISSUE THREAD

**Issue by arencambre** [rstudio/rstudio#8947]
### System details

    RStudio Edition : desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 10 20H2
    R Version       : 4.0.3

### Steps to reproduce the problem
Open a data frame or tibble in the viewer, then hover the a column header for a column whose data has the Date or POSIXct class.

### Describe the problem in detail
When hovering over column headers, you see the column type in a tooltip. When hovering over a header with certain date/time types, it reports as unknown. For sure, columns with data of the Date class or POSIXct class cause this problem. There may be more.

An example:
![image](https://user-images.githubusercontent.com/411495/107523506-69320500-6b7a-11eb-9800-8fb122f9bb56.png)

Yes, I confirmed its type:
![image](https://user-images.githubusercontent.com/411495/107523544-74853080-6b7a-11eb-908a-298c50288f6d.png)

### Describe the behavior you expected
The tooltip reports the class of the data type instead of "unknown" when the class is available.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@arencambre Thank you for raising this issue! I can reproduce it in RStudio Desktop 1.4.1554 on MacOS 11.3 and RStudio Server 1.4.1554 on SLES 15 SP2. We'll review it as we continue to develop RStudio.

QA note: The following will reproduce the problem:
```
df <- data.frame(as.character("2001-04-09"), as.Date("2001-04-09"), as.POSIXct("2001-04-09"))
View(df)
```

**Comment by arencambre** [comment]
Not stale!

**Comment by arencambre** [comment]
Not stale!
