### ISSUE TITLE
RStudio Desktop indefinitely hangs on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by mariusbarth** [rstudio/rstudio#8949]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 20.04 LTS
    R Version       : 4.03

### Steps to reproduce the problem

Install RStudio Desktop on Ubuntu 20.04 LTS with R 4.0.3 and start RStudio IDE.

### Describe the problem in detail 

The IDE indefinitely hangs, i.e. shows all the usual contents, but doesn't react to any mouse or keyboard input. Also, closing RStudio IDE does not work, and RStudio has to be killed via `sudo pkill rstudio`. The problem persists after re-installing RStudio 1.4.1103. Re-installing an older version of RStudio (1.3.1093) solved the issue, but I would be happy to use the newest version RStudio.

### Describe the behavior you expected

I expected RStudio to work on Ubuntu 20.04 LTS.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Thanks @mariusbarth for raising this! I can't reproduce it, though, using the same setup. Are there log files in `~/.local/share/rstudio/log` and if so, can you share them?

**Comment by mariusbarth** [comment]
Hi @ronblum, my logs don't show anything related to the issue (except for the terminated parents). However, I re-installed (again) and now I also don't encounter the problem, anymore. Still, thanks for responding so quickly!

**Comment by mariusbarth** [comment]
Happy too early: I tried to switch to another dictionary (`Geman (new)`) for one of my projects, and now the described behavior re-occurs.
