### ISSUE TITLE
Request: run summary instead of View after reading data

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8950]
When I read some CSV file or similar using the "import dataset" menu, it will by default open the data viewer. I don't ever want to view the data like that when I load it, but instead, want to run `summary` on it to get an overview of what it contains and how the columns were read, which I don't get from `View`.

Would be nice if the interface allowed an option for running `summary` instead of `View` after loading a data file, and if this default command to run after were selectable form the global options (plus selectable in the data viewer before loading).

**Comment by ronblum** [comment]
@david-cortes Thank you for the suggestion!

Meanwhile, I took a look at the data import (even though you're making a request, not reporting a bug) and found #8953.
