### ISSUE TITLE
Requiring an alternate version of Python in R Markdown is ignored when knitting

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8951]
### System details

    RStudio Edition : Desktop & probably Server
    RStudio Version : 1.4.1554 f8ca1fdf
    OS Version      : MacOS 11.3 (but probably the rest, too)
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Install two versions of Python. For example 3.6.11 and 3.7.9.
2. Set `Global Options -> Python -> Python interpreter` to one of them. For example, `~/Library/r-miniconda/envs/r-reticulate/bin/python` which is 3.6.11.
3. Create an R markdown document
    - which uses `reticulate::use_python` to use the other Python interpreter, and
    - sets `required = TRUE`; 
    - for example, `reticulate::use_python("/Users/ronblum/.pyenv/versions/3.7.9/bin/python", required = TRUE)` which is version 3.7.9.

Something like this:
````
---
title: "Pythy"
author: "Ron Blum"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
reticulate::use_python("/Users/ronblum/.pyenv/versions/3.7.9/bin/python", required = TRUE)
reticulate::py_config()
```
````
4. Knit the file.

### Describe the problem in detail

The version of Python that gets used is the session default (3.6.11) instead of the one requested (3.7.9).

```
Pythy
Ron Blum
2/10/2021

reticulate::use_python("/Users/ronblum/.pyenv/versions/3.7.9/bin/python", required = TRUE)
reticulate::py_config()

## Warning: Python '/Users/ronblum/.pyenv/versions/3.7.9/bin/python' was requested
## but '/Users/ronblum/Library/r-miniconda/envs/r-reticulate/bin/python' was loaded
## instead (see reticulate::py_config() for more information)

## python:         /Users/ronblum/Library/r-miniconda/envs/r-reticulate/bin/python
## libpython:      /Users/ronblum/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
## pythonhome:     /Users/ronblum/Library/r-miniconda/envs/r-reticulate:/Users/ronblum/Library/r-miniconda/envs/r-reticulate
## version:        3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:19:23)  [GCC Clang 10.0.1 ]
## numpy:          /Users/ronblum/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
## numpy_version:  1.19.2
## 
## NOTE: Python version was forced by RETICULATE_PYTHON
```

### Describe the behavior you expected

Knitting should use the executable set by `reticulate::use_python("</path/to/python>", required = TRUE)` instead. Note that the desired behavior occurs when only running the chunk.

```
> reticulate::use_python("/Users/ronblum/.pyenv/versions/3.7.9/bin/python", required = TRUE)
> reticulate::py_config()
python:         /Users/ronblum/.pyenv/versions/3.7.9/bin/python
libpython:      /Users/ronblum/.pyenv/versions/3.7.9/lib/libpython3.7m.dylib
pythonhome:     /Users/ronblum/.pyenv/versions/3.7.9:/Users/ronblum/.pyenv/versions/3.7.9
version:        3.7.9 (default, Feb  2 2021, 14:31:48)  [Clang 12.0.0 (clang-1200.0.31.1)]
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
From @kevinushey: 
> RStudio is setting the default version of Python, via RETICULATE_PYTHON, to match what is "active" in the current session. That overrides the default version of Python requested in the document.

**Comment by jmcphers** [comment]
I don't think this needs to be fixed for Juliet Rose. The workaround is to use the Python version settings at the global or project level instead of trying to set them in the document. The only situation in which this isn't possible is one in which you have a single project that contains documents that require different Python versions, which seems very unlikely (not to mention unadvisable) in practice. 

That said, it seems like what we need here is a way to set the Python version that's softer than `RETICULATE_PYTHON` (i.e. it won't override `use_python` but will become a fallback if the doc never calls `use_python`). I'm not even sure if there is such a mechanism in reticulate today. @kevinushey do you know if there is?

**Comment by kevinushey** [comment]
> That said, it seems like what we need here is a way to set the Python version that's softer than RETICULATE_PYTHON (i.e. it won't override use_python but will become a fallback if the doc never calls use_python). I'm not even sure if there is such a mechanism in reticulate today. @kevinushey do you know if there is?

There isn't, but I want to add this to `reticulate` -- we should have something like `RETICULATE_PYTHON_FALLBACK` that acts the same way as `RETICULATE_PYTHON` but has lower priority than a "required" version of Python.

**Comment by jmcphers** [comment]
Moving this out of JR since we don't have a mechanism by which to implement it and the scenario isn't common.
