### ISSUE TITLE
Data import only displays first fifty column names in preview

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8953]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.5042, 1.4.1554
    OS Version      : MacOS 11.3 and SLES 15 SP2
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Create a data file—say, in CSV or Excel format—with more than fifty columns .
2. <kbd>File -> Import Dataset -> From Text (readr)</kbd> or <kbd>From Excel</kbd>.
3. <kbd>Browse</kbd>.
4. Choose a file and click <kbd>Open</kbd>.

Sample file: [wide_file.xlsx](https://github.com/rstudio/rstudio/files/5961662/wide_file.xlsx)

### Describe the problem in detail

All of the columns and data are previewed. However, headers are displayed only for the first 50 columns.

### Describe the behavior you expected

Display all column names.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by lukaszkruk** [comment]
I'm also facing this problem. I wanted to use the preview to manually override some column type guesses, but without the headers displayed it's impossible to do. Does anyone know a workaround?

**Comment by jgutman** [comment]
Verified on 2023.3.0.84 on MacOS 13.0 using Excel file with 120 columns.
