### ISSUE TITLE
Malformed bookdown index hangs UI

### ISSUE THREAD

**Issue by mirh** [rstudio/rstudio#8954]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 10
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Create a bookdown document 
2. Edit index.rmd, and put `library(bookdown)` *before* the YAML header
3. Reload the project

### Describe the problem in detail

The UI (or whatever the "interface viewport" could be called) becomes grey and FUBAR

### Describe the behavior you expected

Just about anything that doesn't make the program unusable. Maybe the bad file should be outright rejected, maybe the wrong part could just be skipped and a big error printed, but I shouldn't have to use task manager to kill the whole program. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! It looks like this is actually a bug in the `rmarkdown` package -- I've filed an associated issue here:

https://github.com/rstudio/rmarkdown/issues/2043

I think this issue is more easily fixed on the `rmarkdown` side, but will keep this issue open just in case.

**Comment by mirh** [comment]
Thank you for your way more comprehensive and precise bug report. 

***Though*** I'm wondering if "waiting for input" is even a good reason for the whole program to pass ~~out~~ away.

**Comment by yihui** [comment]
This has been fixed in the development version of **rmarkdown**:

```r
remotes::install_github('rstudio/rmarkdown')
```

Thanks for the report!

**Comment by mirh** [comment]
Nice then I guess.
