### ISSUE TITLE
RStudio stops working properly (Can not create projects or set global options) when Rtools40 is in path

### ISSUE THREAD

**Issue by ermueller** [rstudio/rstudio#8956]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Windows 10
    R Version       :  4.0.3

### Steps to reproduce the problem

I installed RStudio Version 1.4.1103 in the standard path and installed Rtools40 in the standard C:/rtools40 directory. The only prerequisite is that C:/rtools40/usr/bin is in the system PATH variable.
I can reproduce the problem, even if I completely remove everything R-related (R, RStudio, Rtools) and reinstall it in the standard paths and re-add Rtools to the PATH. This problem stops immediately when I take Rtools40 out of the PATH.

### Describe the problem in detail

When trying to click on "File" -> "New Project..." or trying to open the "Tools" -> "Global Options..." from the dropdown menu, RStudio does nothing, even if I try repeatedly. Also, the window doesn't exactly crash, as I can still input text, but I can neither save nor do anything other substantial. When trying to close RStudio in this state, nothing happens either, and I need to close it using the task manager. This also means that I can not supply a crash report. 

Furthermore, for every time I try to create a new project, a new "make.exe" process gets spawned, I can see this in the Task Manager, so it could be possible that the Rtools40 make is responsible for this problem? 

The same problem was already described in 2019 here:
https://community.rstudio.com/t/new-project-problem-dialog-to-create-new-project-is-not-appearing/24037/8

but no concrete solution was found. To reiterate, this problem stops occurring when Rtools40 is not in the PATH anymore.

### Describe the behavior you expected

Rstudio should open the dialog window for eithere creating a new project or for setting global options.

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ermueller** [comment]
I just noticed that trying to create a new project also spawns an "sh.exe" process, and the dialogue window to let me create a new project actually appears when I kill this "sh.exe" process.

**Comment by ronblum** [comment]
@ermueller Thank you for raising the issue, and the additional investigation! We'll mark it for review and reproducibility as part of our ongoing development of RStudio.

**Comment by kevinushey** [comment]
I'm not able to reproduce this on my Windows VM. Is there anything else unique about the way you've configured your machine? Anything else that might be necessary in order to reproduce?

**Comment by ermueller** [comment]
I actually tried this again recently after freshly installing Windows and it happened again, so I cant't really say for sure that there's anything particularly unusual about my set-up. I installed R and some other programming language related stuff (python mostly), but nothing comes to mind that could or should interfere with Rstudio or RTools.
