### ISSUE TITLE
Not possible to tell when console print is truncated

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8958]
Follow up on previous issue: https://github.com/rstudio/rstudio/issues/8567

**Steps to reproduce:**
* Print some long character variable in the console (desktop version) - e.g.:
```r
long <- as.character(1:1E4)
writeLines(long)
```

**Expected behavior:** should display all the output. If the output is too large, it should start eliminating earlier lines on a FIFO-basis as they are printed, like in pretty much every terminal emulator, other IDEs, and Python mode under reticulate. That means: the comand that is issued should go into the console first, lines should start printing as they go, once the limit is reached the command should no longer be visible, and lines should keep on being left out in the some order in which they were printed to make space for new ones. That way it becomes very clear that the output was truncated.

As an alternative, could perhaps print only the tail but have a big message at the top beneath the issued command saying that the output was truncated (but this is less ideal).

**Actual behavior:** the output gets truncated, but it's not possible to tell that it is. Only the tail gets printed, while the issued command remains there.

(This is a regression over 1.3)

**Comment by kevinushey** [comment]
If I understand correctly: the problem here is that only the generated output is truncated; the command generating the truncated output is not.

<img width="512" alt="Screen Shot 2021-02-11 at 2 33 11 PM" src="https://user-images.githubusercontent.com/1976582/107706987-13428780-6c76-11eb-8088-8c58d9dc4d9e.png">

**Comment by gtritchie** [comment]
I think this is the same as #7918. Closing this as a duplicate.
