### ISSUE TITLE
Environment Pane loses controls when narrower than 400px

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8959]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1566
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem

Resize the Environment pane until it is smaller than 400px. 

![image](https://user-images.githubusercontent.com/470418/107698207-08352a80-6c69-11eb-86c1-b22088730c6d.png)

### Describe the problem in detail

Controls begin to slide off the end of the Environment Pane and become inaccessible. 

![image](https://user-images.githubusercontent.com/470418/107703866-243cca00-6c71-11eb-8082-c8ba4e80429d.png)

### Describe the behavior you expected

We can't support arbitrarily narrow panes, but with the addition of the Memory Usage widget, we now have a much wider minimum width. This could be a problem because people often have very narrow Environment panes that *already* are the minimum width to show all the controls. For example, from a recent presentation by @slopp (see https://twitter.com/rstudio/status/1359556275772616705):

![image](https://user-images.githubusercontent.com/470418/107703172-281c1c80-6c70-11eb-8602-629a1683d9a5.png)

We could support a better minimum width by shortening or removing text labels like "Import Dataset" when the pane becomes narrow. We already have some logic of this nature in the Source Editor toolbar. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1591
    OS Version      : mac OS 11.2.1
    R Version       : 4.0.3

Verified that the Environment Pane gracefully resizes by truncating and then eliminating the Import Dataset label as the pane decreases in size. As the pane increases in size, the truncated label appears and then becomes the full label name.
