### ISSUE TITLE
Show \describe and \item like a list when reflowing comments

### ISSUE THREAD

**Issue by lambdamoses** [rstudio/rstudio#8962]
When writing R packages, I sometimes need to use `\describe` and `\item` to list items and explain each of them in the documentation, such as a list of acceptable options for an argument and the columns of a data frame returned by a function. To make the `roxygen2` comments more readable by developers and myself, I like writing the items like this:
<img width="369" alt="Screen Shot 2021-02-11 at 6 40 14 PM" src="https://user-images.githubusercontent.com/32186361/107724424-a391c400-6c98-11eb-888a-7e33da1a80f6.png">

I generally find comment reflowing very helpful when writing `roxygen2` comments. However, after reflowing, the `\describe` and `\item` became
<img width="552" alt="Screen Shot 2021-02-11 at 6 40 28 PM" src="https://user-images.githubusercontent.com/32186361/107724508-db990700-6c98-11eb-9f1c-d8767b31a9fa.png">
which is less readable.

Here I request a feature to keep the `\describe` and `\item` formatted like in the first screenshot after reflowing. Or better yet, have reflow reformat existing `\describe` and `\item` like in the first screenshot.

**Comment by jmcphers** [comment]
Thanks for the idea! Currently tracked in https://github.com/rstudio/rstudio/issues/3989.
