### ISSUE TITLE
Add ability to choose a repository in the Install Packages popup

### ISSUE THREAD

**Issue by Mosk915** [rstudio/rstudio#8969]
We use RStudio Server Pro and RStudio Package Manager.  In the RStudio IDE, we include both a curated CRAN repository as well as the overall CRAN repository in the `repos` option for our users.  Although we encourage users to use packages in the curated CRAN repository, we still allow them to install any package from CRAN if they want to.

If a package is installed through the "Install Packages" popup in the IDE, the version that is installed will be the latest version found in any of the repositories.  It would be useful if in the "Install from:" dropdown you could choose which of the repositories to install from, in addition of course to still being able to install the latest version found in any repository as it works currently.

**Comment by ronblum** [comment]
@Mosk915 Thank you for the suggestions! We'll review this as we continue development of RStudio. (And if there's a setting for just this that I'm not aware of, we'll address that, too.)
