### ISSUE TITLE
Add the ability to expand environment variables in Rstudio Server config files

### ISSUE THREAD

**Issue by lewinfox** [rstudio/rstudio#8970]
We are running RStudio Server (Pro) on a server with multiple hard disks. The user `$HOME` directories are on a disk with limited capacity so we want to encourage users to work on another disk with more capacity. Let's say it's mounted at `/big_disk`.

We would like to maintain a separate working directory for each user, `/big_disk/${USER}` and we want that directory to be the default when a new session is started. In addition to the disk capacity issue this also makes permission management easier as we can give users visibilty over each others' work without opening up parts of their home dirs.

However, as described in this forum post (from someone else): [Unable to use ${USER} variable in default working dir configuration (rsession.conf)](https://community.rstudio.com/t/unable-to-use-user-variable-in-default-working-dir-configuration-rsession-conf/31303): we can't use the `${USER}` environment variable as part of the path specification for `session-default-working-dir` or `session-default-new-project-dir`.

I believe some other config files accept a `{USER}` (without the dollar sign) parameter? In our case adding this support to `rsession.conf` would be sufficient.

At the moment we are trying a workaround to symlink `~/rstudio_home` to `/big_disk/${USER}` and then setting `session-default-working-dir=~/rstudio_home` but it would be nice to be able to do it all in `rsession.conf`. 

Maybe a bit of a niche use case, but clearly at least two people would find it useful and I couldn't find an equivalent issue already created.

Thanks for an awesome product!

**Comment by ronblum** [comment]
@lewinfox Thank you for the suggestion! Thank you for referencing the existing Community post, as well. We'll review as part of ongoing development of RStudio.

Note: I found this discussion, with @cole, we well: https://community.rstudio.com/t/set-default-home-directory-for-all-users-as-admin/34850

**Comment by lewinfox** [comment]
Thanks @ronblum - appreciate the response and the link!

**Comment by lewinfox** [comment]
No, I just used the symlink workaround described in my initial post. Not
ideal but it served our purpose. Sorry I don’t have anything better for you!
