### ISSUE TITLE
R session crashes when taking shinytest screenshots after recreating ShinyDriver

### ISSUE THREAD

**Issue by AdroMine** [rstudio/rstudio#8974]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 10 (20H2) (also on 1909)
    R Version       : 4.0.3

### Steps to reproduce the problem
Create any shiny app. Example:
``` r 
library(shiny)
ui <- fluidPage(
    titlePanel("Test"),
)

server <- function(input, output) {
    # Nothing here
}

# Run the application 
shinyApp(ui = ui, server = server)
```

Use the following commands for crash:
``` r
app <- ShinyDriver$new("path/to/app") # create webdriver
app$takeScreenshot()                  # take screenshot
app$stop()                            # stop app
app <- ShinyDriver$new("path/to/app") # start webdriver again
app$takeScreenshot()                  # R session crashes here
```

### Describe the problem in detail
When using shinytest, if I initialise a ShinyDriver object, take a screenshot, stop the driver, re-initialise again and take a screenshot, R session in Rstudio crashes. 

Running the same in Rgui, I don't get a crash. 
I don't get a crash on Rstudio cloud either (Rstudio version 1.4.1103-4 and Linux?)

### Describe the behavior you expected
No crash

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report). [diagnostics-report.txt]
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[Diagnostics Report](https://github.com/rstudio/rstudio/files/5989950/diagnostics-report.txt)

**Comment by ronblum** [comment]
@AdroMine Thank you for raising the issue! I can reproduce it in
- RStudio Desktop 1.4.1106 on Windows 10

However, I can't reproduce it in
- RStudio Desktop 1.4.1106 and 1.4.1572 on MacOS 11.3

We'll review this as we continue our development of the RStudio IDE.
