### ISSUE TITLE
Row number column can't be sorted in increasing order in the data viewer

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8975]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.5042, 1.3.1093, 1.4.1106, and 1.4.554,
    OS Version      : MacOS 11.3 and Red Hat 8 using Chrome on MacOS 11.3
    R Version       : 4.0.3

### Steps to reproduce the problem

1. In console, `View(iris)`
     - Rows are sorted by column number (first column).
2. Sort by the first column, row number.
    - Nothing happens

You can see this further by sorting by another column, then the first column (row numbers), and trying to sort by the first column again.

### Describe the problem in detail

The first column, row numbers, only sorts by increasing order, not decreasing order. 

### Describe the behavior you expected

The row numbers should be sortable in both increasing and decreasing order.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by BartJanvanRossum** [comment]
I think this is the same as #5146
