### ISSUE TITLE
consent error when creating project from RStudio Server with "use renv with this project" 

### ISSUE THREAD

**Issue by ras44** [rstudio/rstudio#8977]
after creating a new R project in RStudio Server 1.4.1103 (R 4.0.3) and checking "use renv with this project", an error appears that says "please run consent first" and the project is not set up with renv.  If consent is needed, perhaps a consent prompt would help?

**Comment by ras44** [comment]
thanks for transferring!

**Comment by kevinushey** [comment]
I believe this was fixed a while back:

https://github.com/rstudio/rstudio/blob/4d1fc87218497d67342f961e27eeb151e8d161a9/src/cpp/session/modules/SessionRenv.R#L166-L167

The issue can be verified by trying to create a new project using `renv` on a system that hasn't ever used `renv` before. If you're on macOS and want to simulate this, you can do something like:

```
rm -rf ~/Library/Application\ Support/renv
```

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.5.197
    OS Version      : mac OS
    R Version       : 4.1.0

Verified that no errors appear when creating a new R project and checking the "Use renv with this project" box on a system that hasn't used renv before.
