### ISSUE TITLE
Git Review change window does not have navbar with Button anymore

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#8983]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1576
    OS Version      : Windows 10
    R Version       : 4.0.4

### Steps to reproduce the problem

* Open the daily build on a project with git
* In the git pane click on the history button
* A pop up window show and there is no button in the navbar

### Describe the problem in detail
![image](https://user-images.githubusercontent.com/6791940/108211791-6eb8bd80-712d-11eb-8c03-287cdb96e6ff.png)

### Describe the behavior you expected

It was working in previous build 1.4.1575

![image](https://user-images.githubusercontent.com/6791940/108211926-9871e480-712d-11eb-83b0-119d808f77c5.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
@jmcphers Haven't tried to repro but sounds like it could be related to your toolbar resize work that just went in?

**Comment by jmcphers** [comment]
I think it is. I'll take a look.

**Comment by astayleraz** [comment]
I verified Version 1.4.1588-2 the satellite windows and their toolbars are showing up correctly. Closing issue.
