### ISSUE TITLE
Package delete button eclipsed by scrollbar

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#8984]
### System details

    RStudio Edition : Server Pro
    RStudio Version :  1.4.1039-1
    OS Version      :  Ubuntu 18
    R Version       : 3.6

### Steps to reproduce the problem

- On a mac, configure the following scroll conditions (perhaps the default?)
<img width="510" alt="Screen Shot 2021-02-17 at 9 11 44 AM" src="https://user-images.githubusercontent.com/1593639/108224356-bb52c780-7132-11eb-9f26-a2fa8e2e0f46.png">
- Delete a package
- Try to delete another package Note that the scrollbar prevents you from being able to click the x and you have to wait for it to timeout.

### Describe the problem in detail

By my calculation, this 118-frame gif should be worth 118 thousand words describing the problem.

![2021-02-17 09-17-31 2021-02-17 09_17_59](https://user-images.githubusercontent.com/1593639/108224944-58156500-7133-11eb-8521-b9cf777a6e1b.gif)

### Describe the behavior you expected

I'd just like to click the X again to rapid-fire clear out my library.

**Comment by ronblum** [comment]
@trestletech Thank you for raising the issue! I can reproduce it in
- RStudio Server 1.4.1578 on Ubuntu 20.04.2 using Firefox on MacOS 11.3.

However, it works fine in Chrome. We'll review this as part of our ongoing development of RStudio.

For completeness, what browser and version of MacOS are you using? Thanks!

**Comment by trestletech** [comment]
Nice!

I'm on Firefox on Catalina 10.15.7
