### ISSUE TITLE
{.active} attribute doesn't work in flexdashboard

### ISSUE THREAD

**Issue by Waldi73** [rstudio/rstudio#8990]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Win 10
    R Version       : 4.0.3

### Steps to reproduce the problem
This is a follow-up of this [issue](https://github.com/rstudio/rmarkdown/issues/789#issuecomment-616358150), and [no answer was found with Stackoverflow](https://stackoverflow.com/a/66250741/13513328).

Run following Markdown :
```
---
title: "Active Tabset"
output: flexdashboard::flex_dashboard
---

Column {.tabset}
-------------------------------------
   
### Tab 1

Some text
 
### Tab 2 {.active}

Some other text
```
### Describe the problem in detail
the `{.active}` attribute doesn't make second tab active with `flexdashboard`
### Describe the behavior you expected
same behaviour as with `html_document` output : change active tab

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cderv** [comment]
I believe this is an issue with **flexdashboard** not RStudio IDE (which this repo is about)

The tabset feature from **flexdashboard** is not exactly the same and is documented here: https://rmarkdown.rstudio.com/flexdashboard/layouts.html#tabset_column

@ronblum you can move this to flexdashboard repo I believe.

**Comment by cderv** [comment]
Or you can even close as there is a duplicate issue open in https://github.com/rstudio/rmarkdown/issues/2048

**Comment by Waldi73** [comment]
Sorry, I already copied it to Rmarkdown : I close it here
