### ISSUE TITLE
separate console output in R Markdown chunk should be separated by newline

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8992]
### System details

    RStudio Edition : Any
    RStudio Version : 1.4.1577
    OS Version      : macOS 11.2
    R Version       : 4.0.4

### Steps to reproduce the problem

Using an R Markdown document with the contents:

`````
---
title: "Untitled"
output: html_document
---

```{r}
library(tidyverse)

mpg %>%
  filter(cyl == 4) %>%
  ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point()
```
`````

Run the first chunk.

### Describe the problem in detail

The two lines of output are placed on the same line.

<img width="521" alt="Screen Shot 2021-02-18 at 9 46 13 AM" src="https://user-images.githubusercontent.com/1976582/108398785-42a14900-71ce-11eb-9168-324c823fff2d.png">

### Describe the behavior you expected

The two lines of output should be placed on separate lines, as is done in the R console.

<img width="568" alt="Screen Shot 2021-02-18 at 9 46 38 AM" src="https://user-images.githubusercontent.com/1976582/108398832-4d5bde00-71ce-11eb-8752-e98b7facc1ad.png">

### Notes

Since the output here is just placed within `<span>`s, we probably need to weak the display to ensure that separate outputs are placed on different lines.

<img width="254" alt="Screen Shot 2021-02-18 at 9 48 17 AM" src="https://user-images.githubusercontent.com/1976582/108398954-6ebcca00-71ce-11eb-8d1c-05473a9c2043.png">

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by emjames** [comment]
Hi, I gave this a go with #9535 . What do you think of it?
Looking forward to your comments.

**Comment by mikebessuille** [comment]
This has already been merged, so moving to Ghost Orchid for verification.  Thank you for contributing!

**Comment by ronblum** [comment]
Thanks @emjames, great work! And I can confirm that these are on separate lines in
- RStudio Desktop 2021-08.0.295 on MacOS 12 beta
- RStudio Server 2021.8.0.297 on Ubuntu 20.04.2 via Safari on MacOS 12 beta

![issue_8992.png](https://codetreeusercontent.s3.amazonaws.com/uploads/3803425a-b89f-4d7b-bf49-ff628b0c4093/issue_8992.png)
