### ISSUE TITLE
Add option to set the default location to install packages

### ISSUE THREAD

**Issue by ailich** [rstudio/rstudio#8994]
Add option under Tools > Global Options to set the default location to install packages. The default on Windows is under "Documents/R/win-library" which is now linked to Onedrive on many PC's which can cause long sync times and take up space in people's allotted cloud storage. The secondary location from `.libPaths()` is "C:/Program Files/R/" and it would be useful to be able to change that to the default. I've found some solutions online involving editing the R_LIBS_USER environment variable or the Rprofile/Rprofile.site files, but they're a bit involved for the casual user and it doesn't seem like one solution works for all users. It also seems like the behavior for storing libraries is a bit different for the 2 main locations as under Program Files there is a new library for every single increment in version (e.g "C:/Program Files/R/R-3.6.3/library") whereas under Documents it's only to the minor version level (e.g. "Documents/R/win-library/3.6").

https://medium.com/@ValidScience/how-to-fix-rstudios-package-installation-on-windows-10-c1e602bf3a1f
https://www.youtube.com/watch?v=2CYKuj8SEPA
https://code.adonline.id.au/changing-the-default-library-folder-path-in-r/
https://www.reddit.com/r/rstats/comments/6wjy3u/r_in_windows_really_likes_onedrive_for_some_reason/

**Comment by ronblum** [comment]
@ailich Thank you for the suggestion! I can understand wanting to get around OneDrive slowness using the UI. I'll mark this for review as part of our ongoing development of RStudio.
