### ISSUE TITLE
'Replace one' button/shortcut key in global search/replace interface

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#9001]
Not sure what the procedure is for 'unclosing' issues that have gone 'stale' but after trying to reopen https://github.com/rstudio/rstudio/issues/6293 I thought I'd open it here. I think many people will find this useful. No problem if it's out of scope or a 'wontfix' would just be good to have an explicit decision rather than an automated bot closing it after a more-or-less evidence-based number of days of inactivity (even though I tried to keep it alive by commenting)!

**Comment by ronblum** [comment]
Hi Robin! You might've seen the note already, but the original ticket should have become "unstaled." @mikebessuille reopened it, so I'm closing this one as a duplicate. Sorry about that!

Also, @salim-b, since we reopened #6293, I suggest adding the 👍 to it so it's recorded.

**Comment by Robinlovelace** [comment]
Many thanks guys.
