### ISSUE TITLE
Rstudio ignoring LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by azzaea** [rstudio/rstudio#9003]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 16.04.7 LTS
    R Version       : 4.0.4 (2021-02-15)

### Steps to reproduce the problem
1. Install ICU 58 as below:
```
$ cd /home/p287664/software
$ wget https://github.com/unicode-org/icu/archive/release-58-3.tar.gz
$ tar xvzf release-58-3.tar.gz
$ cd icu-release-58-3/icu4c/source
$ ./configure
$ make
# make install #I don't have sudo permissions, so this won't work
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}://home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib
$ echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}://home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib" > ~/.Renv
```
2.  Run R and install `igraph` package (works fine when R starts from the command line):
```
$ R
...
> install.packages("igraph")
...
* DONE (igraph)

The downloaded source packages are in
        ‘/tmp/RtmphzzNwB/downloaded_packages’
> library(igraph)

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union
```
3. Upgrade RStudio to the version reported (done by the system administrator)
4. Load the `igraph` package
```
> library(igraph)
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/p287664/R/x86_64-pc-linux-gnu-library/4.0/igraph/libs/igraph.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
```
Before the upgrade, loading the `igraph` package both the command line and RStudio worked OK.

### Describe the problem in detail

From within Rstudio, the environment variable `LD_LIBRARY_PATH` is properly set, but it seems not to go through afterwards.
```
> Sys.getenv("LD_LIBRARY_PATH")
[1] "/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/jre/lib/amd64/server://home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib"

> library(igraph)
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/p287664/R/x86_64-pc-linux-gnu-library/4.0/igraph/libs/igraph.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
```
It is strange why linking is not done given the proper environment variable is set

### Describe the behavior you expected

For the package to load normally (as in R run from the terminal)

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by azzaea** [comment]
For completion, and in case someone else faces the same problem, the workaround I found was by installing `igraph` this way:
```
withr::with_makevars(c(PKG_LIBS="-L/home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib"), install.packages("igraph"), assignment="+=")
```
(again, this last step was not needed with the previous version of RStudio)

**Comment by kevinushey** [comment]
For posterity, can you also share the output of:

```
system("ldd /home/p287664/R/x86_64-pc-linux-gnu-library/4.0/igraph/libs/igraph.so")
```

from within RStudio?

**Comment by azzaea** [comment]
Yes, kindly find:
```
> system("ldd /home/p287664/R/x86_64-pc-linux-gnu-library/4.0/igraph/libs/igraph.so")
	linux-vdso.so.1 =>  (0x00007ffdd590b000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fb7b98e7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb7b96ca000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fb7b944a000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fb7b8c67000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fb7b8a06000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007fb7b8626000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb7b831d000)
	libR.so => /usr/lib/R/lib/libR.so (0x00007fb7b7c8a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb7b7908000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb7b76f2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb7b7328000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb7b7124000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007fb7b6d90000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb7b6b76000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb7b6954000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb7ba1c8000)
	libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007fb7b48c0000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fb7b4595000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fb7b4356000)
	libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007fb7b4110000)
	libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fb7b3e97000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fb7b3c87000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb7b3a7f000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fb7b385d000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007fb7b1da6000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fb7b1b7d000)
```

**Comment by kevinushey** [comment]
Looking again at your `LD_LIBRARY_PATH`, it has:

```
<...> /usr/lib/x86_64-linux-gnu <...> /home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib
```

The fact that `/usr/lib/x86_64-linux-gnu` shows up first means that any libraries found in that path will be preferred to those in your ICU library path. I think you need to move `/home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib` to the front of your `LD_LIBRARY_PATH`.

**Comment by azzaea** [comment]
I devised the test below:

1. I modified my `~/.Renviron` file to change the order, so we have (from RStudio):
```
> Sys.getenv("LD_LIBRARY_PATH")
[1] "/home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib/:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/jre/lib/amd64/server"
```
2. I removed the `igraph` package. 
3. Re-installed (also from RStudio)- it gives a different type of error this time:
```
> install.packages("igraph")
:
DensityGrid.cpp:46:26: fatal error: igraph_error.h: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:181: recipe for target 'DensityGrid.o' failed
make: *** [DensityGrid.o] Error 1
ERROR: compilation failed for package ‘igraph’
```
4. With the `withr::with_makevars` trick above, I could cleanly install and load `igraph`

Also to note: when I was working with the command line invocation (outside RStudio), I could already install and successfully load `igraph` with the order:
```
LD_LIBRARY_PATH=<...> /usr/lib/x86_64-linux-gnu <...> /home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib
```

**Comment by azzaea** [comment]
Probably this is also another symptom of this bug:
When checking my current package (i.e, `build` panel --> `more` --> `Check Package`), my check fails with an error:
```
Error: package ‘lattice’ was installed before R 4.0.0: please re-install it
Execution halted
```
So, I reinstalled `lattice`, and I can load it safely. 
```
> install.packages("lattice")
:
* DONE (lattice)

The downloaded source packages are in
	‘/tmp/RtmpbYGk8P/downloaded_packages’
>
> library("lattice") # works
>
> find.package("lattice")
[1] "/home/p287664/R/x86_64-pc-linux-gnu-library/4.0/lattice"
```

My current path looks:
```
> .libPaths()
[1] "/home/p287664/R/x86_64-pc-linux-gnu-library/4.0"
[2] "/usr/local/lib/R/site-library"                  
[3] "/usr/lib/R/site-library"                        
[4] "/usr/lib/R/library"  
```
I explicitly specify  `Depends: R (>= 4.0)` in the package DESCRIPTION file, the top of the build log (in RStudio) reads:
```
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory ‘/home/p287664/github_repos/pcgen2.Rcheck’
─  using R version 4.0.4 (2021-02-15)
```
Yet, the build fails with the error above, which is similar to the error generated when loading `lattice` from the 4th directory in my path:
```
> library("lattice", lib.loc = .libPaths()[1]) #works
>
> library("lattice", lib.loc = .libPaths()[4])
Error: package or namespace load failed for ‘lattice’:
 package ‘lattice’ was installed before R 4.0.0: please re-install it
>
> library("lattice", lib.loc = .libPaths()[3])
Error in library("lattice", lib.loc = .libPaths()[3]) : 
  there is no package called ‘lattice’
>
> library("lattice", lib.loc = .libPaths()[2])
Error in library("lattice", lib.loc = .libPaths()[2]) : 
  there is no package called ‘lattice’
```

Would you kindly advise if there's something I could do to customize the build process?

Thank you,
Azza

**Comment by kevinushey** [comment]
I think the more problematic issue here is that you have a mixture of R packages installed for different versions of R. I suspect you previously had an older version of R installed, updated R, but did not uninstall and reinstall your older R packages in those library paths.

**Comment by azzaea** [comment]
@kevinushey : Yes, you are correct. I was working with an older R version then upgraded. 

I don't have permission over the `/usr/lib/R/library` path, hence couldn't uninstall. Hoping my system administrator would help. Will get back with how this works.

```
> remove.packages("lattice") #works
Removing package from ‘/home/p287664/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
>
> remove.packages("lattice", lib="/usr/lib/R/library")
Updating HTML index of packages in '.Library'
Warning in remove.packages :
  cannot create file '/usr/share/R/doc/html/packages.html', reason 'Permission denied'
Warning in remove.packages :
  cannot update HTML package index
```

**Comment by azzaea** [comment]
`lattice` is now removed from the old installation directory, but the build process still fails for a similar reason with a different package:
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Matrix’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```
Yet, the `Matrix` package is actually installed. It seems that the build process still looks for it in a different directory:
```
> find.package("Matrix")
[1] "/home/p287664/R/x86_64-pc-linux-gnu-library/4.0/Matrix"
>
> .libPaths()
[1] "/home/p287664/R/x86_64-pc-linux-gnu-library/4.0"
[2] "/usr/local/lib/R/site-library"                  
[3] "/usr/lib/R/site-library"                        
[4] "/usr/lib/R/library"    
>                         
> library("Matrix", lib.loc = .libPaths()[4])
Error in library("Matrix", lib.loc = .libPaths()[4]) : 
  there is no package called ‘Matrix’
> library("Matrix", lib.loc = .libPaths()[3])
Error in library("Matrix", lib.loc = .libPaths()[3]) : 
  there is no package called ‘Matrix’
> library("Matrix", lib.loc = .libPaths()[2])
Error in library("Matrix", lib.loc = .libPaths()[2]) : 
  there is no package called ‘Matrix’
> library("Matrix", lib.loc = .libPaths()[1]) #works
> 

```

**Comment by pachamaltese** [comment]
thanks @azzaea, I have the same problem with RStudio 1.4.1106 and R 4.0 (fresh system, just formatted)

here's my sessionInfo
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_CL.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_CL.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4 tools_4.0.4 
```

**Comment by pachamaltese** [comment]
_Here's how I solved for a particular directory that I needed in LD_LIBRARY_PATH..._
_I was able to load arrow from R in the termina, but not from RStudio_

If, by any reason, you have problems with arrow and Rstudio, here's how I solved myself the problem of writing in Atom and testing in very inefficient ways from terminal.

if you use something like this in ~/.bashrc (Linux, or at least Ubuntu)
```export ARROW_HOME=~/.arrow
export LD_LIBRARY_PATH=${ARROW_HOME}/lib:${LD_LIBRARY_PATH}
export ARROW_R_DEV=true```
just paste the same thing in ~/.profile, which will enable those variables for desktop apps, then reboot and RStudio will show this beautiful output:

```> Sys.getenv("LD_LIBRARY_PATH")
[1] "/usr/lib/R/lib:/home/pacha/.arrow/lib::::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server:/home/pacha/.arrow/lib:"
> library(arrow)

Attaching package: ‘arrow’

The following object is masked from ‘package:utils’:

    timestamp

> ```
Instead of:
```> library(arrow)
Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/pacha/R/x86_64-pc-linux-gnu-library/4.0/arrow/libs/arrow.so':
  /home/pacha/R/x86_64-pc-linux-gnu-library/4.0/arrow/libs/arrow.so: undefined symbol: _ZN5arrow2fs9S3Options13FromAccessKeyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_
 ```

**Comment by pachamaltese** [comment]
_Here's how I solved for a particular directory that I needed in LD_LIBRARY_PATH..._
_I was able to load arrow from R in the termina, but not from RStudio_

If, by any reason, you have problems with arrow and Rstudio, here's how I solved myself the problem of writing in Atom and testing in very inefficient ways from terminal.

if you use something like this in ~/.bashrc (Linux, or at least Ubuntu)
```export ARROW_HOME=~/.arrow
export LD_LIBRARY_PATH=${ARROW_HOME}/lib:${LD_LIBRARY_PATH}
export ARROW_R_DEV=true```
just paste the same thing in ~/.profile, which will enable those variables for desktop apps, then reboot and RStudio will show this beautiful output:

```> Sys.getenv("LD_LIBRARY_PATH")
[1] "/usr/lib/R/lib:/home/pacha/.arrow/lib::::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server:/home/pacha/.arrow/lib:"
> library(arrow)

Attaching package: ‘arrow’

The following object is masked from ‘package:utils’:

    timestamp

> ```
Instead of:
```> library(arrow)
Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/pacha/R/x86_64-pc-linux-gnu-library/4.0/arrow/libs/arrow.so':
  /home/pacha/R/x86_64-pc-linux-gnu-library/4.0/arrow/libs/arrow.so: undefined symbol: _ZN5arrow2fs9S3Options13FromAccessKeyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_
 ```

**Comment by KayShelton** [comment]
I am facing a similar issue to that originally identified. Using Ubuntu 18 and R4.0.

I am trying to get the RNetCDF package to be loadable in RStudio (I have tried 1.4.1106 and 1.3.1093). I have managed to get it to install (after setting CPPFLAGS, LDFLAGS and explicitly setting my LD_LIBRARY_PATH in .Renviron) using the standard install.packages approach. But when I try to load the package I get an error:

libnetcdf.so.19: cannot open shared object file: No such file or directory

I have checked the RNetCDF.so using ldd; libnetcdf.so.19 is addressed correctly and this file (symbolic link to an existing file) is valid.

I have also tried this with R3.6. In all cases command line R can install and load the package correctly. Rstudio throws up the above error when I try to load the package.

Note I have installed the netcdf libraries in a specific location, not the default, as this is a shared machine. The libraries (C, fortran and C++) have all been built and work as anticipated for other applications.

I have attempted the withr::with_makevars workaround (explicitly setting the "PKG_LIBS" and "PKG_CPPFLAGS"), but yielded the exact same result.

Is there anything else I can try? Any compiler settings I might need or anything else? Or is this version of the netcdf libraries (netcdf-c-4.8.0, built with hdf5-1.10.7) just not compatible with RStudio?

**Comment by kevinushey** [comment]
> libnetcdf.so.19: cannot open shared object file: No such file or directory

Can you please share the full error? Can you also confirm what `system("ldd /path/to/RNetCDF.so")` reports in RStudio?

**Comment by KayShelton** [comment]
Yep, no problem:

```
> library(RNetCDF)
Error: package or namespace load failed for ‘RNetCDF’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/kayshelton/R/x86_64-pc-linux-gnu-library/4.0/RNetCDF/libs/RNetCDF.so':
  libnetcdf.so.19: cannot open shared object file: No such file or directory
```

and:
```
> system("ldd /home/kayshelton/R/x86_64-pc-linux-gnu-library/4.0/RNetCDF/libs/RNetCDF.so")
	linux-vdso.so.1 (0x00007fff4e1cc000)
	libudunits2.so.0 => /usr/lib/x86_64-linux-gnu/libudunits2.so.0 (0x00007f1b25c16000)
	libnetcdf.so.19 => /home/kayshelton/Build_WRF/LIBRARIES/netcdf/lib/libnetcdf.so.19 (0x00007f1b25852000)
	libR.so => /usr/lib/R/lib/libR.so (0x00007f1b251b8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1b24dc7000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f1b24b95000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1b247f7000)
	libhdf5_hl.so.100 => /home/kayshelton/Build_WRF/LIBRARIES/hdf5/lib/libhdf5_hl.so.100 (0x00007f1b245d4000)
	libhdf5.so.103 => /home/kayshelton/Build_WRF/LIBRARIES/hdf5/lib/libhdf5.so.103 (0x00007f1b23fe0000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f1b23d60000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1b23b41000)
	libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f1b238d4000)
	libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (0x00007f1b2368b000)
	libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f1b23409000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f1b231e3000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f1b22fd3000)
	libz.so.1 => /home/kayshelton/Build_WRF/LIBRARIES/grib2/lib/libz.so.1 (0x00007f1b22db5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1b22bad000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1b229a9000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f1b225f1000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f1b22150000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f1b21f21000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1b2604c000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f1b21cfc000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f1b21adf000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f1b218c3000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f1b216b5000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f1b2147f000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f1b21119000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f1b20ece000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f1b20c7c000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f1b20a6e000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f1b20844000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f1b1ec9b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1b1e912000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1b1e6fa000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f1b1e37c000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f1b1e148000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f1b1dec7000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f1b1db98000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f1b1d985000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f1b1d6af000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f1b1d47d000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f1b1d279000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f1b1d06e000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f1b1ce54000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f1b1cc39000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f1b1c9f8000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f1b1c7f0000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f1b1c5ec000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f1b1c3e3000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f1b1c156000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f1b1beb4000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f1b1bc7e000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f1b1ba68000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f1b1b83f000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f1b1b630000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f1b1b3e6000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f1b1b0dd000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f1b1aea5000)

```

**Comment by kevinushey** [comment]
Here's one possibility... The documentation for [dlopen()](https://man7.org/linux/man-pages/man3/dlopen.3.html) has:

>        o   If, at the time that the program was started, the environment
>            variable LD_LIBRARY_PATH was defined to contain a colon-
>            separated list of directories, then these are searched.  (As
>            a security measure, this variable is ignored for set-user-ID
>            and set-group-ID programs.)

How is LD_LIBRARY_PATH being set in your application? If I understand correctly, it would not suffice to set it within, say, your `.Rprofile` or `.Renviron`.

One thing to check: do things work if you set `LD_LIBRARY_PATH` and then launch RStudio from a terminal? For example:

```
LD_LIBRARY_PATH=<...>
/usr/lib/rstudio/bin/rstudio
```

**Comment by azzaea** [comment]
> How is LD_LIBRARY_PATH being set in your case? 
As part of the `.Renviron` file:

```
$ cat .Renviron
LD_LIBRARY_PATH=/home/p287664/software/icu58/icu-release-58-3/icu4c/source/lib/:${LD_LIBRARY_PATH}
```

> If I understand correctly, it would not suffice to set it within, say, your `.Rprofile` or `.Renviron`.
Yes
 
> One thing to check: do things work if you set `LD_LIBRARY_PATH` and then launch RStudio from a terminal? 
This actually works!

**Comment by kevinushey** [comment]
I _think_ one way to make this work by default would be to modify the `ldpaths` script that comes with R, normally located at:

```
file.path(R.home("etc"), "ldpaths")
```

This is just a small shell script that R uses to compute `LD_LIBRARY_PATH` on startup.

You could try updating the `LD_LIBRARY_PATH` set there, to append or prepend entries as appropriate. Does that make a difference? If so, then I believe setting the library paths there would ensure they are set and used consistently between both R and RStudio.

**Comment by azzaea** [comment]
Thank you @kevinushey. I've been away from that PC since yesterday. I will report back once I'm working on it again (tomorrow or on Saturday)

**Comment by pachamaltese** [comment]
i can confirm this problem still happens from time to time after re-installing packages

**Comment by azzaea** [comment]
Apologies for the delay in checking. I'm afraid I don't have permissions to change the contents of the `ldpaths` file on my machine (shared).
```
> file.path(R.home("etc"), "ldpaths")
[1] "/usr/lib/R/etc/ldpaths"
```

**Comment by afandiadib** [comment]
I'm having the same problem as the title - Rstudio ignoring LD_LIBRARY_PATH. I am loading Tensorflow package but it failed to detect CUDA library. LD_LIBRARY_PATH works fine when I run R directly on terminal or even through Jupyter notebook. All of them has the same Sys.getenv('LD_LIBRARY_PATH').

My intuition tells me that any package that operate at a low level ignores LD_LIBRARY_PATH from the top level i.e. current session and use LD_LIBRARY_PATH before R initialize to load the package. That means .Renviron or .Rprofile won't work.
My solution: I am using Rstudio server, so I set LD_LIBRARY_PATH at a low level (require admin privilege) before initialize R.

Two hacky solution for Rstudio Desktop (I'm using this as well):
1) Define LD_LIBRARY_PATH in .bashrc and launch Rstudio using terminal.
2) Define LD_LIBRARY_PATH in rstudio.desktop file. Open Rstudio like normal i.e. double clicking the icon

I wish there is a way to define LD_LIBRARY_PATH at a low level for Rstudio Desktop just like for Rstudio Server.

**Comment by mikebessuille** [comment]
Closing this as-designed.

**Comment by mxposed** [comment]
@mikebessuille could you please clarify this design or link to this design explained somewhere? I think it would be very helpful to modify LD_LIBRARY_PATH in user session of rstudio server where the user does not have control over the rstudio server installation
