### ISSUE TITLE
Rstudio load package automatically in project startup with previous opened data viewer

### ISSUE THREAD

**Issue by dracodoc** [rstudio/rstudio#9004]
I met this problem again today, did a little search and found a bug report in rstudio community 2 years ago by myself. That bug report was not noticed. 
https://community.rstudio.com/t/rstudio-load-package-automatically-in-project-startup-with-data-viewer-open/12333

A simple search found another mysterious bug report may actually caused by this behavior #8714, and I'm guessing some recent package installation auto restart R session failure may also be related #2656

### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1106
    OS Version      :  win10
    R Version       :  4.0.4

### Steps to reproduce the problem
1. with a RStudio project, open some data with data viewer that need certain package support. For example, a raster object need raster package
2. quit RStudio. Open it again with same project
3. RStudio will load the package automatically and keep the data in data viewer, even if the setting is do not load any rdata or workspace.

### Describe the problem in detail
rstudio is loading a package automatically in project startup, when I didn't save/load workspace. Turned out that I have some tabs of data/variable viewer open, which needed the package. For example I have a data viewer for raster stack, then rstudio will load raster, sp when I load the project.

I think with previous version of rstudio, reopen a project will just show those data viewer as data not available since they are not in environment anymore. But somehow version Build 832 (a17fc948) will load the needed package.

### Describe the behavior you expected
Since the workspace was not saved/loaded and user probably want a clean start, I think the proper behavior is just discard those data viewers as before, not loading package and try to show them.

Previously opened data viewer should not cause the data being saved and get loaded next time. I guess the data viewer may saved the data in somewhere else, because I specifically don't load any .rdata.

This may also interfere with the package installation process when rstudio tried to restart session and install new packages. If some packages were loaded automatically out of normal path, this can cause a loop. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by chris-nunn** [comment]
This is an issue I have been having as well. I agree with the op's suggestion for a preferred default or at least a warning as to why the packages are being loaded

**Comment by dracodoc** [comment]
I don't really like the bot actions that mark issues without activities as stale then close them automatically after some time.

I understand data viewer is an epic task and was in the todo list for long time, still, closing issue usually means issue no longer exist, which is not the case. Is there some KPI related to opened issues, and the auto closing bot is part of a KPI hacking process? 

I must reported more than 5 long standing issues with rstudio which never solved but all closed and I kept receiving new user comments on those old closed issues. 

Maybe Rsudio can actually delete these issues which will hide the problem better, and I don't want to receive more emails on these issues either since nothing ever happen.
