### ISSUE TITLE
Previous/Next chunk navigation commands do not work in visual mode

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9005]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1103 

### Steps to reproduce the problem

1. Bind a keyboard shortcut to the _Go to Next Chunk_ command
2. Open an R Markdown document with multiple R chunks
3. Switch to visual mode (if not already in visual mode)
4. Place the cursor in one of the R chunks
5. Invoke the _Go to Next Chunk_ command, via the shortcut or Command Palette

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

The cursor should move to the next code chunk.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
I verified in Version 1.4.1606-1 the next and previous chunks and sections are working as expected and added an automated test for the next and previous chunks functionality. Closing issue.
