### ISSUE TITLE
Error: C stack usage  7957552 is too close to the limit 

### ISSUE THREAD

**Issue by krushnach80** [rstudio/rstudio#9006]
### System details

    RStudio Edition : 
    RStudio Version : Version 1.3.1093
    OS Version      : centos-release-7-9.2009.1.el7.centos.x86_64
    R Version       : R version 3.6.0 (2019-04-26) -- "Planting of a Tree"

### Steps to reproduce the problem
Every time I logout a project session this error comes up.
```
Error saving session (options): R code execution error
Error: C stack usage  7957552 is too close to the limit
Error saving session (options): R code execution error
Error: C stack usage  7957552 is too close to the limit
Error saving session (options): R code execution error
Error: C stack usage  7957552 is too close to the limit
```

### Describe the problem in detail
The problem is described above.
### Describe the behavior you expected

I thought due to large workspace data this might be happening so I tried clearing workspace every-time I logout a project session.But still  the issue persists. And few times I have come across this "error occurred during transmission error" when i can connect to the server but can;t open the studio server interface.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you still see this in the latest RStudio release (1.4)?

**Comment by krushnach80** [comment]
"Do you still see this in the latest RStudio release (1.4)?"  let me update it and will let you know if the issue persists.

**Comment by krushnach80** [comment]
After updating to the 1.4 version so far the freezing issue haven;t come across..

**Comment by kevinushey** [comment]
Glad to hear it!
