### ISSUE TITLE
Choose Directory dialogue is adding to everyday frustration when it easily doesn't have to

### ISSUE THREAD

**Issue by torbjorn** [rstudio/rstudio#9007]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Fedora 32
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Start RStudio
2. File -> New Project... -> New Directory -> R Package
3. Click "Browse" to choose where to put the new directory
4. Bask in the gory of the dot files and folders in a users home directory

### Describe the problem in detail

The dialog should prompt for a directory but also suggests files as valid options. This, although doesn't prevent the operation to complete, is arguably a bug.

The dialog should not suggest dot directories as those are highly unlikely options for this and are confusing for exactly the type of user who would go down this wizard route in the first place. I am myself arguably not that type, but trying it out as preparation for a course I'll be giving, I had to hit Page Down 9 times (!) to clear all the dot folders _and files_ of my home directory.

Suggesting dot directories, as mentioned earlier, is counter intuitive as the typeof users who needs this level of help, likely will be very confused by all this. He will not understand what he sees, just that he has to scroll really far to find what he searches for.

### Describe the behavior you expected

1. Suggest directories only (its a Directory Chooser after all)
2. Hide dot directories. The knowledgable user who for some reason needs this, knows to hit Ctrl-L and type it in any way.

**Comment by torbjorn** [comment]
Quick update, I realise that files, although listed in the interface, are disabled options. Still. As with any space on your screen, they are taking up precious real estate.

**Comment by kevinushey** [comment]
Can you also provide a screenshot of what you're seeing? Here's what I see on Ubuntu 20.04 with gnome:

<img width="756" alt="Screen Shot 2021-02-22 at 11 32 42 AM" src="https://user-images.githubusercontent.com/1976582/108759794-afd01980-7501-11eb-80e7-1824eca432fd.png">

In fact, there is a dotfile called `.dotfile` in that folder, but it is not displayed for me. Files are displayed, but they are greyed out and cannot be selected.

**Comment by torbjorn** [comment]
That's odd. Here is one from me:

![Selection_060](https://user-images.githubusercontent.com/4111/108843458-02313900-75db-11eb-95b0-dfd7eac7839d.png)

Arguably I could probably remove a bunch of no-longer-used dot entries, but that's besides the point.

My standard file viewer does not list dot paths. (cinnamon DE / Fedora linux )

**Comment by ronblum** [comment]
@torbjorn I'm cheating a bit by using Red Hat 8.3 instead of Fedora 32. That said, when I toggle "Show Hidden Files" in the Files app, RStudio shows or hides hidden files depending on the setting. Is the toggle not being respected? What about with other applications?

<img width="769" alt="redhat_hidden_files" src="https://user-images.githubusercontent.com/31009952/109848912-ca4f7480-7c1e-11eb-841d-aeeaad78445e.png">

**Comment by torbjorn** [comment]
My RStudio File->Open... dialgoue does not offer anything besides selecting things from the filesystem hierarchy. Also it looks different from the file viewer of my desktop environment (DE).

My DE's file viewer offers a check box for showing or hiding hidden files, just like yours, and my DE file viewer respects it.

RStudio's File->Open view however remains unaffected.
