### ISSUE TITLE
Cell-by-cell execution on .py scripts

### ISSUE THREAD

**Issue by AltfunsMA** [rstudio/rstudio#9008]
`.R` scripts opened in Rstudio can be executed by cell, aka code section as opposed to by line or by script using `# Section ----"` markers. 

It would be nice to have the same ability with `.py` scripts, perhaps borrowing the `# %%` markers that can be used on VS Code or Spyder.

Thanks for a truly great package!

**Comment by kevinushey** [comment]
This would need to be implemented on the RStudio side as opposed to reticulate; transferring the issue over.
