### ISSUE TITLE
Run current section (Ctrl+Alt+T) runs the whole code when no text in the section header

### ISSUE THREAD

**Issue by RemiDav** [rstudio/rstudio#9015]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1103
    OS Version      :  Windows 10 64bits
    R Version       :  3.6.1 (2019-07-05)

### Steps to reproduce the problem
```
# ----
print("Section 1")
# Section 2 ----
print("Section 2")
# Section 3 ----
print("Section 3")
```

Place pointer on line 2 and press Ctrl + Alt + T.
This outputs the following:
```
> # ----
> print("Section 1")
[1] "Section 1"
> # Section 2 ----
> print("Section 2")
[1] "Section 2"
> # Section 3 ----
> print("Section 3")
[1] "Section 3"
```

Adding some text on line 1 solves the problem:
```
# SOME TEXT HERE ----
print("Section 1")
# Section 2 ----
print("Section 2")
# Section 3 ----
print("Section 3")
```
Output:
```
> print("Section 1")
[1] "Section 1"
```
### Describe the problem in detail

Delimiting a section with `# ----` is recognized for code folding purposes, but not recognized correctly by the "run current section" shortcut. 

### Describe the behavior you expected

R Studio should run only the code between `# ----` and the next section delimiter ( `# ----` or `# Text here ----`).

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@RemiDav Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.4.1106 on Windows 10. It appears that if there is text in all three, there are three sections according to the document outline:
<img width="114" alt="yes_text" src="https://user-images.githubusercontent.com/31009952/109179129-94f6e280-7757-11eb-93af-23e19ced0234.png">

However, if there is no text in the first line, it is treated as the first section, and the other two sections are treated as subsections of it:
<img width="116" alt="no_text" src="https://user-images.githubusercontent.com/31009952/109179331-c66fae00-7757-11eb-9275-4bb0b90132ef.png">

I believe this is incorrect (though I may be wrong). I'll mark this as a bug to review as we continue development of RStudio.

**Comment by RemiDav** [comment]
I could reproduce the issue in R 1.4.1717 on Windows 10, it seems it has not been resolved.

**Comment by colearendt** [comment]
Nothing to see here stale bot. Move along
