### ISSUE TITLE
Environment Pane memory display is distracting

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9020]
### System details

    RStudio Edition : Any
    RStudio Version : 1.4.1500+
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

Use RStudio and keep an eye on the Environment pane. 

![image](https://user-images.githubusercontent.com/470418/109070654-9e287680-76a7-11eb-83a5-74465c5307c6.png)

### Describe the problem in detail

The session memory usage label (183 MiB in this example) changes frequently; almost any action will make it wiggle a little. Sometimes it goes up for no obvious reason; at other times it doesn't go down when you think it should. See https://github.com/rstudio/rstudio/issues/8960, for example.

### Describe the behavior you expected

The display isn't _incorrect_ -- it is showing what's really happening to the session's memory consumption in real time. However it is probably going to be more distracting than helpful for most users. We should not show it by default.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Another problem with showing the value to average users is that many will mistake it for the total amount of memory used (e.g. in a containerized environment), and could become confused when it looks like they're only using a few MiB but yet total container usage is pushing a much larger limit.

**Comment by mikebessuille** [comment]
I think the feature is good as it is, and that we could defer these issues pending customer feedback.  If you agree, we can move this to a future milestone.

**Comment by jmcphers** [comment]
I'm just going to close this because lots of people seem to like it as-is and no one has complained that it is misleading or updates too frequently.
