### ISSUE TITLE
Enable Dark Theme for Git Commit Pop-Up

### ISSUE THREAD

**Issue by ashbaldry** [rstudio/rstudio#9026]
I currently use the Cobalt theme in RStudio, and whenever I open up the Git commit page it appears super bright. Would it be possible to have the editor theme copy over to the Git popup? Even if it is just the background colour and text colour, it would make a big difference!

![image](https://user-images.githubusercontent.com/8420419/109193106-ef139a00-778f-11eb-97ff-1d1db8eefa4f.png)

**Comment by ronblum** [comment]
@ashbaldry Thank you for raising this! This might be a bug, so I'll mark it as such for review.

**Comment by gtritchie** [comment]
Reopening; we've implemented dark mode for modal dialogs in the upcoming 2026.04 (Globemaster Allium) release of RStudio, so extending that support to the Git window would be a nice touch.
