### ISSUE TITLE
Incorrect warning for checking arguments to R function when declaring package explicitly and using pipes

### ISSUE THREAD

**Issue by Mikea0228** [rstudio/rstudio#9028]
With "Check arguments to R function calls" checked in the diagnostics options, Rstudio flags a function call where you explicitly state the package as having not enough arguments when using a magrittr pipe. See example below.

```
library(stringr)
library(magrittr)

letters %>%
  str_detect("f") %>%
  which()

letters %>%
  stringr::str_detect("f") %>%
  which()
```

![Screenshot 2021-02-25 200822](https://user-images.githubusercontent.com/24625851/109210812-407a5400-77a5-11eb-8da1-f1a62cbea788.png)

**Comment by ronblum** [comment]
@Mikea0228 Thank you for raising this issue! I can easily reproduce this, including confirming that the code works when executed. I'll mark it for us to review as continue our development and improvement of RStudio.
