### ISSUE TITLE
[UI] Some dialogs have abnormally large text

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#9033]
Windows 10 RStudio Desktop 1.4.1103

When I close an unsaved file this dialog shows up

![image](https://user-images.githubusercontent.com/952340/109255469-09ff0200-77c2-11eb-96ee-41137cdedb33.png)

The text for the 3 buttons is awkwardly large and looks like a magnifier glass tool is being used. The tiny margins on "Don't Save" also contribute to it looking broken. 

The "New Folder" dialog has both the text and the buttons as huge

![image](https://user-images.githubusercontent.com/952340/109357220-dec2f400-784f-11eb-815c-f5199176fd15.png)

Other dialogs have a mix like that as well. It doesn't match the system font size and looks buggy.

It only started appearing this way when I installed 1.4.

**Comment by ronblum** [comment]
@daattali Thank you for raising this! I'll mark this for review, including an attempt at reproducibility on our end.

**Comment by astayleraz** [comment]
@daattali I attempted to reproduce what you are seeing but things look correct for me. Have you tried this on the latest daily build to see if you are seeing the issue with the latest build? We had made some changes to windows font that may impact the things you are seeing? If you are still seeing this on the latest daily build, are you using any special system font settings I should be aware of to try and reproduce what you are seeing? Below is what I was seeing:

![Screen Shot 2021-03-05 at 10 29 48 AM](https://user-images.githubusercontent.com/1482677/110152258-ba5e9e80-7d9e-11eb-808f-6cd6f18f8c3f.png)
![Screen Shot 2021-03-05 at 10 30 19 AM](https://user-images.githubusercontent.com/1482677/110152264-bb8fcb80-7d9e-11eb-8c49-eae157861d70.png)

**Comment by kevinushey** [comment]
Reproducing this issue probably requires one to have the operating system's screen scaling set to something other than 100%, and it might only reproduce for certain values (e.g. 150% or 175%) and perhaps only in certain screen configurations (e.g. only if you have multiple monitors with different screen scaling for each display).

**Comment by daattali** [comment]
@kevinushey is probably correct because I am set to 125% (that's the factory default recommended setting for my machine) and I do see this issue when I'm connected to an external monitor.

**Comment by astayleraz** [comment]
@daattali I checked with our dev on this and this should hopefully be resolved in our move to electron when that happens and unfortunately, we cannot provide a timeline when we should expect that. If this issue still happens after our switch to electron then we can reevaluate and prioritize this issue. Closing the issue for now.
