### ISSUE TITLE
Suggestion: Open R Markdown documents and Shiny apps in Viewer pane by default

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#9035]
Currently, in a fresh and new (first-run) RStudio session, such as on Cloud or any local installation, the default behavior when previewing an R Markdown document after knitting is to open the document in a new window.

On Desktop, this default is often surprising to new R Studio users (who are most likely to see it). In the browser, this often triggers pop-up window blocking with an intimidating warning both from the browser and RStudio:

![image](https://user-images.githubusercontent.com/5420529/109335132-9f84ab00-782f-11eb-9722-cd85f4ee8ceb.png)

Since this behavior is most likely seen by new R Studio users, it's also very likely to be confusing. For more experienced users it is a least annoying. As an instructor, I often have to comment on this behavior and guide users around it. Having the default be to open the preview in the viewer pane seems like the path of least surprise.

**Comment by jmcphers** [comment]
The default comes from here: 

https://github.com/rstudio/rstudio/blob/87dd17b7340105409b045a573a67af2dec7849f5/src/cpp/session/resources/schema/user-prefs-schema.json#L815-L821
