### ISSUE TITLE
[Feature Request]: Selection of column names/head in the data viewer window.

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#9047]
For Rsutdio 1.4.1103, only the texts in table cells can be selected in the viewer window. It will be much handy if column names can be selected (for copy/highlight) as well. Currently, right-click doesn't trigger any action for the column head. 

![snap1158](https://user-images.githubusercontent.com/11802171/109569235-f4792900-7a9c-11eb-88a6-ccc2329b058f.jpg)

![snap1159](https://user-images.githubusercontent.com/11802171/109569240-f5aa5600-7a9c-11eb-820f-69a8c993d003.jpg)

**Comment by ronblum** [comment]
@Sibojang9 Thank you for raising this! Clicking on the column names is already, used for sorting. A workaround (mouse only) is to select multiple records, pulling the mouse up so that it includes the column row. I'll leave this open to be reviewed for a more elegant solution.

**Comment by Sibojang9** [comment]
@ronblum Thanks for the suggestion. That workaround would always select all the column names instead any single column name. Right now, left-click is indeed used for sorting. Why don't we make better use of the right-click?
