### ISSUE TITLE
Nicer error message when connection with R could not be established

### ISSUE THREAD

**Issue by raffaem** [rstudio/rstudio#9048]
Due to a naive iptables configuration, iptables was blocking incoming connections on localhost.

When I started RStudio under this configuration, only the menu bar was shown. The inside of the window was completely white and blank (and of course, no panels were shown).

Allowing connections between server/clients on localhost fixed the problem.

It would be really nice and useful if RStudio could throw more meaningful error messages, instead of just a white screen, I think.

**Comment by gtritchie** [comment]
What version and flavor (desktop vs server) were you using? We have added better feedback about this to the UI in some cases.

**Comment by raffaem** [comment]
RStudio 1.4.1106 (it was some 0.0.000x version below, then I updated but the behaviour persisted) on desktop, in particular on Ubuntu 20.10
