### ISSUE TITLE
lintr::lint crashes RStudio but provides correct lints

### ISSUE THREAD

**Issue by nlarusstone** [rstudio/rstudio#9050]
### System details
I've seen this on both:
    RStudio Edition : Server
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 16.04
    R Version       : 4.0.3

   RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : OSX Big Sur 11.2
    R Version       : 4.0.3

### Steps to reproduce the problem
This is hard to provide a reprex for, as I would have to put my entire project up in order to reproduce (just copying the file does not seem to reproduce). However, when I run `lintr::lint(<FILE>)` on a file that requires changes, it ends the RStudio session.

### Describe the problem in detail
I run `lintr::lint(<FILE>)` from the console in RStudio and it pops up a warning `RStudio Session Ended` and gives me a button to create a new session.
The "new session" doesn't actually have new data or anything -- it keeps my old environment.
It also populates the `Markers` tab with the linter errors correctly.

### Describe the behavior you expected
I expected the `Markers` tab to populate, but RStudio NOT to crash

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you see the same crash with an independent R session (outside of RStudio)?

Unfortunately without a reproducible example it's unlikely that we can do anything.

**Comment by nlarusstone** [comment]
Good catch -- looks like it's crashing R. Let me reopen under the lintr repo
