### ISSUE TITLE
Installation with gdebi produces: `FutureWarning: Possible nested set at position 1`

### ISSUE THREAD

**Issue by andypea** [rstudio/rstudio#9053]
This is the most minor of bugs.
It doesn't prevent installation of RStudio, but simply results in a rather cryptic warning being displayed.

### System details

    RStudio Edition :Server
    RStudio Version : 1.4.1106
    OS Version      : Ubuntu 20.04.1
    R Version       : 3.6.3 (2020-02-29)

### Steps to reproduce the problem

Install RStudio using gdebi as described on the [RStudio website](https://rstudio.com/products/rstudio/download-server/debian-ubuntu/):

```
sudo apt-get install gdebi-core
wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.4.1106-amd64.deb
sudo gdebi rstudio-server-1.4.1106-amd64.deb
```

### Describe the problem in detail

After executing `sudo gdebi rstudio-server-1.4.1106-amd64.deb` the installation proceeds as normal, but also prints the following warning to the console:

```
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
```

### Describe the behavior you expected

I expected the installation to work without gdebi producing any warnings.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Looked into this briefly a while back, seems like an issue with gdebi itself (which is possibly no longer maintained, but haven't found where I saw that again); here's one example: https://askubuntu.com/questions/1150864/future-warning-with-gdebi-while-installing-some-packages

**Comment by ronblum** [comment]
FWIW, I can confirm that `gdebi` produces this warning with other `.deb` files I've installed from other sources.
