### ISSUE TITLE
Error Starting R The R session failed to start.  ERROR MESSAGE.

### ISSUE THREAD

**Issue by krushnach80** [rstudio/rstudio#9056]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : centos-release-7-9.2009.1.el7.centos.x86_64
    R Version       : R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
![Screenshot from 2021-03-04 11-50-40](https://user-images.githubusercontent.com/8524258/109920395-3e9e1c80-7ce0-11eb-98af-87f57fe94347.png)

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@krushnach80 Thank you for raising the issue. I'll mark it for review. However, can you please provide the version number for the RStudio product that you're using? Thanks!

**Comment by krushnach80** [comment]
"However, can you please provide the version number for the RStudio product that you're using? Thanks!" i not sure what command to use to look for since i can;t click on the menu and see the version

**Comment by krushnach80** [comment]
So I tried to install the desktop version by downloading this version and I get this message

```
sudo rpm -ivh rstudio-1.4.1106-x86_64.rpm 
warning: rstudio-1.4.1106-x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID e331692f: NOKEY
Preparing...                          ################################# [100%]
	package rstudio-1.4.1106-1.x86_64 is already installed

```

**Comment by krushnach80** [comment]
this is my version 1.4.1106

**Comment by gadenbuie** [comment]
I'm also seeing the same type of crash with RStudio Desktop Pro 1.4.1606-1 (build id `56b84d0ea504dd3ad0bbcf0fb53877b6-19`):

```
R session launched, attempting to connect on port 33109...
08 Mar 2021 15:13:27 [rsession-garrick] ERROR generic error 8 (Exec format error) [r-home: /Library/Frameworks/R.framework/Resources, r-archs: , rsession-archs: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::(anonymous namespace)::validateCompatible(const std::string &) src/cpp/r/session/RSession.cpp:270; LOGGED FROM: int main(int, char *const *) src/cpp/session/SessionMain.cpp:2200
08 Mar 2021 15:13:27 [rsession-garrick] ERROR generic error 8 (Exec format error) [r-home: /Library/Frameworks/R.framework/Resources, r-archs: , rsession-archs: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::(anonymous namespace)::validateCompatible(const std::string &) src/cpp/r/session/RSession.cpp:270; LOGGED FROM: int main(int, char *const *) src/cpp/session/SessionMain.cpp:2200
```
