### ISSUE TITLE
Feature Request: Absolute/relative link checking

### ISSUE THREAD

**Issue by bearloga** [rstudio/rstudio#9057]
**Problem**: when including links in R Markdown documents, if I forget to include `http://` or `https://` at the beginning of a URL, the rendered/knit version will have it as a relative link (e.g. `www.github.com/bearloga` becomes `https://mpopov.com/blog/www.github.com/bearloga`).

**Proposed Solution**: a "Check Links…" in RStudio's Edit menu just like there's a "Check Spelling…" that would scan the document for links/URLs that should be absolute but are currently relative.

**Comment by ronblum** [comment]
@bearloga Thank you for raising this! Can you provide a bit of sample code? I'm trying to reproduce this, but I don't think I'm doing so properly.

Also, can you provide the system details? Thanks!

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by bearloga** [comment]
Sure, @ronblum! If you make an example.Rmd with the following contents:

```rmarkdown
---
title: "Untitled"
output: github_document
---

[Absolute link](https://github.com/rstudio/rstudio/issues/9057)

[Relative link](github.com/rstudio/rstudio/issues/9057)
```

and knit it, the first link will take you to this page and the second link will (correctly) error, because technically that second link starts with a subdirectory called "github.com".

I wouldn't call this a bug, because sometimes you do want to link to files & folders (e.g. CSS, JavaScript, and media files), so this really is just about adding a feature for checking to see if there are any URLs in the document that are maybe missing the `http://` or `https://`

-----

RStudio Edition : Desktop
RStudio Version : 1.4.1103
OS Version      : macOS Big Sur 11.2.2
R Version       : 4.0.4

**Comment by ronblum** [comment]
@bearloga Thank you! That was simple, and I see why I was getting something different. Alright—we'll review this as we continue development of RStudio, and I'll mark this as an enhancement—I misfiled it as a bug.

**Comment by bearloga** [comment]
Thank you!

**Comment by ronblum** [comment]
Pinging, as it has multiple 👍 s.

**Comment by colearendt** [comment]
Love this idea! 🔗

**Comment by colearendt** [comment]
Links make life better
But when they are wrong it is
Not ideal or fun

**Comment by jmcphers** [comment]
Hah, love the haiku!
