### ISSUE TITLE
Visual Editor's Import Citations tool doesn't import authors when format is BibTeX

### ISSUE THREAD

**Issue by amoeba** [rstudio/rstudio#9059]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1586 & 1.4.1614
    OS Version      : macOS 11.2.1
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem

1. Create a new RMarkdown document
2. Switch to the Visual Editor by clicking the "switch to visual markdown editor" toolbar item
3. Move the text cursor into the body of the RMarkdown document
4. Click the "Insert" toolbar item in the Visual Editor toolbar to open the menu
5. Select the menu item item labelled "Citation"
6. In the "Insert Citation" window that appears, change the source on the left from "My Sources" to "From DOI"
7. Paste any of the below DOIs into the search box at the top and wait for a result to appear below
8. Ensure the "Format" drop-down at the bottom of the Insert Citation window is set to BibTeX
9. Click the "Insert" button
10. Observe the corresponding entry in `references.bib` is missing the `author` tag

### Describe the problem in detail

I was testing out the Visual Editor's new Insert Citation tool with DOIs for some datasets and found none of them imported as I expected. Three example DOIs are:

- `doi:10.18739/A23R0PT35`
- `doi:10.18739/A29W09071`
- `doi:10.5061/dryad.31zcrjdh2`

One common property of the three above DOIs is that they are of the type "dataset". They import with authors if I change the import format from BibTeX to CSL+JSON and I can confirm they convert correctly on https://doi2bib.org ([example](https://doi2bib.org/bib/doi:10.18739/A29W09071)) thanks to @cderv over on my RStudio Community [thread](https://community.rstudio.com/t/some-dois-not-importing-correctly-with-visual-editors-insert-citation-tool/97867).

### Describe the behavior you expected

I expected each of the above DOIs to have BibTeX entries with the `author` tag. The entries appear to be correct otherwise.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
Thanks for reporting this issue! It should be fixed in the latest daily build.

**Comment by amoeba** [comment]
Many thanks @dragonstyle. I can confirm things seem to be working as I expected with the latest RStudio Daily (1.4.1620).

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.4.1627 on MacOS 11.3.
