### ISSUE TITLE
Global Options - Edit Snippets screen problem

### ISSUE THREAD

**Issue by rcesarpacheco** [rstudio/rstudio#9066]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : Windows 10 - 19042.804
    R Version       : 4.04

### Steps to reproduce the problem
Open Tools -  Global Options - Code - Edit Snippets
### Describe the problem in detail
I can't see what is written on the lines of the screen that shows up.  All the lines are really messed. Running in a laptop. If I run Rstudio in another pc, everything is fine.
I tried several things: reinstalling Rstudio, windows. Update graphic cards drivers. Nothing worked.
![image](https://user-images.githubusercontent.com/32118879/110164942-de3ad800-7dd0-11eb-8181-da2a06dfd52e.png)

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rcesarpacheco** [comment]
I figured out that if I use "Desktop OpenGL" as the rendering engine (Tools-Global Options - General - Advanced), I solved this problem. Is this somehow expected?

**Comment by kevinushey** [comment]
If switching to software rendering resolved the issue, then the issue is most likely some sort of bad interaction with RStudio and the particular graphics cards on your machine. What kind of graphics card is installed?

**Comment by jmcphers** [comment]
Internal note: also seen by a customer in ticket 59195.

**Comment by ute** [comment]
Same here, and using Desktop OpenGL did solv it, thank you, @rcesarpacheco !

![image](https://user-images.githubusercontent.com/5145859/120101319-df687080-c145-11eb-948a-3b5aac977e04.png)
