### ISSUE TITLE
Vertical tabs like the new Edge?

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#9069]
I've started playing with Microsoft Edge vertical tabs in Canary & Beta and they're finally available to general users:

![image](https://user-images.githubusercontent.com/509878/110226905-ed994e80-7ec0-11eb-82f5-35203e554125.png)

it provided major vertical real estate savings for folks on 10"/12"/13"/14" screens (tables and mbpros, etc). 

i have no idea how hard that'd be but it's been great in day-to-day Edge use.

**Comment by ronblum** [comment]
@hrbrmstr I just tried it out on Edge—neat! I'll mark this as an enhancement to review.

**Comment by mike-lawrence** [comment]
I started using vertical tabs in Firefox recently (via the "Tree Style Tab" extension) and can't imagine going back now. I'd love it if Rstudio's editor had a vertical tabs option for files; having vertical tabs in Firefox has left me really noticing how painful it is to scroll through Rstudio's horizontal tabs with big projects.
