### ISSUE TITLE
Text alignment in visual markdown editor / chunk folding

### ISSUE THREAD

**Issue by torch0703** [rstudio/rstudio#9070]
Hi, I've recently begun to use the visual mode of r markdown.
It's such a great experience but I noticed two issues that might make it even better.

1) text alignment
To make some text aligned in the middle, the /div command which inserts
new div with customizable CSS styles can be used. (adding text-align: center;)
I thought it would be great to make this action into a shortcut (or a button) 
which can provide a word processor-like experience.

2) chunk folding
In the original editor, I can fold code chunks by pressing option+cmd+L, but it seems it isn't working in the
visual mode. Please consider adding this for continuity of experience between the two modes.

I always appreciate your hard & excellent work :)

**Comment by ronblum** [comment]
@torch0703 Thank you for the kind words! And for the suggestions. We'll review them while we continue development of RStudio, including the visual markdown editor.
