### ISSUE TITLE
Add lualatex engine to compile PDF

### ISSUE THREAD

**Issue by cbrnr** [rstudio/rstudio#9071]
Since `tinytex` supports the `lualatex` engine (#2788), it would be nice if RStudio also supported setting this option. Currently, only `pdflatex` and `xelatex` work, but many people (including me) seem to prefer `lualatex` for various reasons.

**Comment by ronblum** [comment]
@cbrnr Thank you for the suggestion! We'll review this as we continue development of RStudio.

**Comment by cbrnr** [comment]
I would like to revive this issue. RStudio is a great LaTeX editor, and I really need LuaTeX in some of my documents. Since `tinytex` already supports this with `tinytex::lualatex()` I think adding that option wouldn't be too much effort for someone familiar with the code.

**Comment by cbrnr** [comment]
Maybe it's as easy as adding a third value `"LuaLaTeX"` here?

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/tex/SessionPdfLatex.cpp#L46-L50
