### ISSUE TITLE
Allow GWT to detect desktop mode for both Qt and Electron

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9082]
During development we want GWT to detect both the existing QtWebEngine-based desktop app and the future Electron-based app.

**Comment by gtritchie** [comment]
Implemented via https://github.com/rstudio/rstudio/pull/9085

**Comment by astayleraz** [comment]
Verified in Version 1.5.104 I am still seeing the desktop variation of the UI. Closing issue.
