### ISSUE TITLE
Add UI localization support

### ISSUE THREAD

**Issue by ca-scribner** [rstudio/rstudio#9083]
I work on a team that needs internationalization support (specifically: French language support) for RStudio.  Has there been any past work on this?  We searched but did not find anything.

Unless there is something we missed, we plan to implement this in the next few weeks and contribute it.  If there are any preferences on what/how, please let us know!  Otherwise I'll report back in a bit with what we decide to do.

Thanks!

**Comment by gtritchie** [comment]
Do you mean localization of the UI into French or internationalization e.g. support for editing scripts containing French?

Localization has not been done and is not on our short-term roadmap.

Internationalization is already relatively robust for most languages and writing systems, at least LTR scripts.

**Comment by ca-scribner** [comment]
Sorry for the ambiguity. I mean localization for the UI.

Ok if I can contribute localization of the UI is that something that would
be appreciated upstream?

**Comment by gtritchie** [comment]
Certainly would be appreciated, but there will be significant challenges, there's a lot of UI with layout that assumes displayed text has a certain length. 

Also UI text is hardcoded into source code in most cases versus being broken out into separate language resource files.

**Comment by ca-scribner** [comment]
Sounds good and thanks for the tips.  I'll let you know how it goes!

**Comment by ca-scribner** [comment]
Been looking through the codebase and have a better idea.  Some things are easier (hard-coded strings in some places are straight forward), but I wasn't so sure the best approach for things like the commands defined in `Commands.cmd.xml`.  

If I understand the function around `Commands.cmd.xml`, the xml file is used as a spec for compile-time generated (using gwt's generators) java classes that provide the UI for misc commands.  So if I added some new command (eg: `id="newSpecialMarkdownDoc"` to go in `File->New File->___` with a `menuLabel="Special Markdown Script"`) I would define that in `Commands.cmd.xml` and the UI builds with that new command.  

To internationalize, a new entry in the xml file would also need new entries in a Constants interface (`String newSpecialMarkdownDocMenuLabel="Special Markdown Script"`) for the default language, and then corresponding entries in a `.properties` file for each language (`_en.properties` being the same, others being translations).  If the goal of the xml was to let UI changes happen in one central place, I think I need to make the Constants interface also generated at compile time based on the XML, and maybe even the `_en.properties` file if that is possible.  Does that make sense, or would a different way be preferred?

Any suggestions are appreciated - thanks!

**Comment by gtritchie** [comment]
In general that sounds about right. I've never done anything with localization of GWT-based UI, so am not familiar with the model for it. We will be gradually moving off GWT in future releases (a multi-release process) and I'm going to make sure we adopt a localizable approach from day one (including pulling forward any progress you make on the current code!)

**Comment by ca-scribner** [comment]
Ok that sounds great! I’ll keep that in mind when specking something out,
and if I can avoid using anything too GWT specific to keep an eye on the
future.

Are there any other parts of the front end that work similarly to this
commands xml? Just trying to find where other challenging parts might be.

**Comment by gtritchie** [comment]
We also generate our settings (preferences) from a json file, and it contains text that surfaces in various locations in the UI (e.g. the Options dialog, the Command Palette).

Those live here:

https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/schema/user-prefs-schema.json
https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/schema/user-state-schema.json

These aren't automatically generated during the build, you have to manually run the R script (that will let you discover what files are generated via git status):

https://github.com/rstudio/rstudio/blob/master/src/gwt/tools/generate-prefs.R

There may be others, I'll let you know when they occur to me!

**Comment by gtritchie** [comment]
Small thing (capturing to remind "future me"): we generate element IDs for some GWT controls at runtime based on the control's visible label, and we have Selenium automation that depends on these.

So a localized build would fail our automation until we make these display-language independent. This would be nice for other reasons, such as UI text tweaks breaking our automation (e.g. recently changed some menu labels from "Cheatsheets" to "Cheat Sheets" and that broke automation).

**Comment by ca-scribner** [comment]
Slowly chipping away.  Got something working for commands and menus in Commands.cmd.xml, and also made sure I can handle static strings (although there's a lot of them, so I haven't gone through everything yet).

Was just handling the `user-*-schema.json` files as you mentioned.  My initial thought was that this text would surface in the Global Options menu (I thought that was what you meant by the Options dialog), but realized after implementing the i18n that the preference menus are coded elsewhere.  @gtritchie could you point me to where I would find the title/description text from the schema's popping up?  Thanks!

**Comment by ca-scribner** [comment]
Nevermind - got them to pop up through the comand pallette after all.  Just took some coaxing to get the command pallette to show up.  

I was surprised these strings weren't used in the settings menus as well

**Comment by gtritchie** [comment]
Thanks for update, and for looking into this! If you have any work-in-progress on a branch or fork you'd like to share to get some feedback let me know and I'd be happy to take a look. Making this happen (localizing RStudio) would make a lot of people very happy and we aren't going to get to it ourselves for some time so really appreciate your efforts here.

**Comment by ca-scribner** [comment]
Yeah input would be great.  It is rough atm but I've been working [on this branch/fork](https://github.com/ca-scribner/rstudio/pull/1).  I just added a summary of what's been done so far on there.  I'll flesh the issue out with checkboxes for coming tasks shortly, but it'll give you a starting point.  

Sorry for it being messy and hard to approach.  I'm new to GWT, never used R, and barely written java, so I've had a lot of learning to do :smile:.  Feedback is really appreciated though!

**Comment by gtritchie** [comment]
Cool, I'm out this week (moving) so will be a few days before I am able to take a look.

**Comment by ca-scribner** [comment]
No problem, I’ll keep updating as I go and we can touch base when you’re
available. Good luck with the move!

**Comment by ca-scribner** [comment]
@gtritchie been slowly chipping away at this.  As you probably guessed the changes are wide reaching - how should I approach trying to upstream it?  I think if I try to make one large PR that covers this, we'll have a few problems:
* I'll never actually catch up (my base will always be changing)
* It'll be a terrible mess for someone to review

An option could be that as I go, I start PRing it in pieces.  I could start with the basics needed to make GWT's i18n work (changes to top level XML, etc), plus some simple changes (maybe pick a few simple pages with constants/messages, plus some of the places I've added `$NON-NLS-1$` comments to suppress hard coded string literals.  What do you think?  This way it doesn't have to be done at once, but through setting a default language and not accepting other options we could keep everything forced to English until it is all done.

**Comment by gtritchie** [comment]
Thanks again for tackling this, I wish I had time to pitch in. I haven't had time to even look at your WIP, sorry.

I agree waiting and doing it all in one PR is too painful all around. I like your idea of submitting it in smaller chunks. Getting some basics in place for GWT and some examples showing how to use it would be great.

A scoped change like that will let us get our minds wrapped around it so we can offer a meaningful review, and then we can start using it ourselves for any new UI we're adding.

**Comment by ca-scribner** [comment]
Sounds great, thanks Gary!  No problem on not having time for the WIP,
honestly even that felt too big as a starting PR to look at.

Ok I'll slice off a small piece in a way I think will provide no breaking
changes but also demonstrate how future work can be done.  Your input on
that will be appreciated too as there's some architecture questions I have
that I'm not qualified to answer.  I'll keep you up to date!

**Comment by skyeturriff** [comment]
Hi @gtritchie ! We're close to having another PR ready for you guys. Would you prefer if we resolve the change requests on the existing one first, or you want us to go ahead and send the next one over as soon as it's ready?

This next one is independent of the existing, and deals with the more standard i18n stuff.

cc @rohank07

**Comment by gtritchie** [comment]
If it doesn't overlap the other one then go ahead and submit it when ready. Thanks!

**Comment by skyeturriff** [comment]
Hey @gtritchie ! I think I've figured out how Shortcuts are being built, but I wanted to confirm my understanding of how they're rendered to the UI which will help me figure out how to properly implement the i18n.

From what I gather, the `ShortcutsEmitter` generates the code that registers each shortcut with `ShortcutManager`. This is what creates the `KeyboardShortcut` and the `ShortcutInfo` that ultimately powers the UI elements (these being the menu labels, command palette, keyboard shortcuts help, and the modify keyboard shortcuts panel - am I missing anything?).

What I was hoping to confirm is if the value displayed (i.e. "Ctrl+ O" for the Open File menu item) is coming from the `toString(boolean pretty)` method of `KeyboardShortcut` (which ultimately calls on `KeySequence` and `KeyCombination`)? I can see this is where the int enum val of the modifiers are mapped back to their sting vals (i.e. "Ctrl+", "Atl+", etc.). If I can pinpoint this as what's driving the values for the UI, I can go from there for the i18n.

When I make changes directly in the `toString(boolean pretty)` method of `KeyCombination`, I see the changes in the Keyboard Shortcuts Help and the Modify Keyboard Shortcuts pane, but not in the file Menus or the Command Palette. From what I can tell, `AppCommand` appears to be building the menu items using the same through it's various methods. But maybe that's not the case?

**Comment by gtritchie** [comment]
Great questions and I don't know the answers without digging into the code. I may not have time to do that before I'm OOO.

**Comment by gtritchie** [comment]
Open source is now localizable, for the most part. I don't think we need this general issue to linger, we can open specific issues as needed.
