### ISSUE TITLE
RStudio cant connect to a R Session

### ISSUE THREAD

**Issue by agodha32** [rstudio/rstudio#9084]
Whenever I try to import a dataset, or set a working directory, it gives me the following error,

Error: Unable to establish connection with R session

**Comment by ronblum** [comment]
@agodha32 Thank you for raising the issue! Can you please provide your system details?

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

Also: 
1) Can you include with diagnostics report? https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
2) What are the paths you're using?

**Comment by agodha32** [comment]
Here is what I get when I type in Sys.info()

![image](https://user-images.githubusercontent.com/57735762/110863135-36208580-828e-11eb-9955-f70adbfa2bac.png)

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/6126289/diagnostics-report.txt)

Finally, I just use fread, and read_csv, to get files that are stored in a shared google drive, G drive.
