### ISSUE TITLE
"STOP" button is hidden when console is minimized

### ISSUE THREAD

**Issue by oscarbaruffa** [rstudio/rstudio#9090]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : Windows 10 Pro
    R Version       : 4.0.3

### Steps to reproduce the problem
Run a script that needs a bit of time to run so that the "STOP" button on the top right displays
Reduce the width of the console, or start with a reduced width console, the STOP button disappears

### Describe the problem in detail
If the console pane is not wide enough to display the STOP button, then its not immediately obvious that a script is executing, or if you wish to stop one that is executing, its not clear where the button is. 

### Describe the behavior you expected

Regardless of the width of the console, I expected the STOP button to be visible while a script is running

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by datawookie** [comment]
An alternative option would be to have the **STOP** button located somewhere else in the UI so that it's not affected by resizing the console.

**Comment by Lextuga007** [comment]
This is important, especially for new users to R Studio. The resizing in the console is very nice so I make a point of highlighting that to new users in introduction courses but the Stop needs to be available as well as having people aware.

**Comment by avila** [comment]
As a workaround you can set a keybind to `Interrupt R Session`.

I agree that the Stop sign is a better visual feedback and could get a more prominent placement on the interface, you can get a visual feedback that the R is not idle by looking at the `>` at the command prompt. The `>` prompt is only shown when idle and this should be visible whenever the Console pane is visible, even if only one char wide. 

#### Setting keyboard shortcut 
![image](https://user-images.githubusercontent.com/31955632/132516091-46f39484-cc07-4467-acbe-065fe90040b3.png)

Note: I am not sure what `Send Interrupt` does, but `Interrupt R Session` seems to work just as clicking at the Stop sign. 


#### Comand prompt `>` as indicator of idle
![image](https://user-images.githubusercontent.com/31955632/132517085-9597641c-3ed6-410e-b942-fe3092296c2e.png)

**Comment by colearendt** [comment]
🛑

**Comment by colearendt** [comment]
I said 🛑 , stalebot
