### ISSUE TITLE
RStudio Server login screen dark mode pls

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#9092]
macOS is in dark mode and Edge/Chromium knows I'm in dark mode but RStudio does not 

![image](https://user-images.githubusercontent.com/509878/110854203-9a3d4c80-8282-11eb-8c28-8d0d237e3564.png)

(been working in the middle of the night more and have been blinded enough times to finally take the time to file an issue).

I'll take a look at the code for it if you're up for a PR (y'all beat me to a PR for arm64 `rsession`, but I can prblyu knock this out alot faster than I could resolve the toolchain issues preventing me from getting RStudio to compile on big sur).

**Comment by gtritchie** [comment]
Always happy to get contributions! We no longer support IE so prefers-color-scheme media query is now in play on all browsers (I think, haven't actually checked).

**Comment by astayleraz** [comment]
Verified in 1.4.1668-1 dark mode setting is now being respected in the system settings and or the browser setting. Closing issue.
