### ISSUE TITLE
RStudio Server logo is blurry on Retina/high DPI displays

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9093]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1600

### Steps to reproduce the problem

Sign in to RStudio Server in a browser on a high DPI display (OS scaling set to 200%)

### Describe the problem in detail

The RStudio logo is blurry.

![image](https://user-images.githubusercontent.com/470418/110855453-38251d00-826b-11eb-9cb0-6b216c90f2ad.png)

### Describe the behavior you expected

Doesn't make a great first impression. We should have a crisp 2x version of this logo. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified, comparing RStudio Server 1.4.1660 and 1.4.1668 via Safari and Chrome on MacOS 11.3. And it seems to work well past 200%, if my somewhat shoddy eyesight is any judge.
