### ISSUE TITLE
spell check ignoring chunk header content inconsistently between source and visual editor modes

### ISSUE THREAD

**Issue by rgayler** [rstudio/rstudio#9094]
## Describe the problem in detail

While editing an Rmarkdown document in the RStudio IDE, spell check in visual editor mode looks at (at least) the chunk label in the chunk header, whereas using spell check on the same document in source mode does not look at the chunk label.

## Describe the behaviour you expected

Spell check obviously has some rules around what text to ignore (generically, ignore code).
I expected the rules on what text to ignore for spell checking to be the same regardless of the editor mode (source/visual).

- [x] I have read the guide for submitting good bug reports.
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [NA] If I am reporting a RStudio crash, I have included a diagnostics report.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

## System details

```
RStudio Edition : Desktop
RStudio Version : Preview build 1.4.1106-5
OS Version      : Ubuntu 20.10
R Version       : 4.0.3
```

## Steps to reproduce the problem

1. Open a new Rmarkdown file from the RStudio IDE ( File | New file | R Markdown ... | Document | OK )  
  The first code chunk of the initial template document has the chunk header `{r setup, include=FALSE}`.
  The document editor should have opened in source mode.
2. Spell check the document ( F7 ).  
  Spell check should return `Spell check is complete.`, that is, no spelling errors detected.
3. Switch to visual editor mode.
4. Spell check the document ( F7 ).  
  The spell checker picks up the chunk label `setup` as a possible spelling error.

**Comment by ronblum** [comment]
@rgayler Thank you for pointing this out! I see a discrepancy as well, but it's slightly different, using the default R Markdown template:
1) The chunk label is ignored in both cases by default (correctly-spelled `setup`).
2) If the chunk label is misspelled, e.g. `seetup`, the spell checker ignored it in source mode but catches it in visual mode.
3) In visual mode, the spell checker treats `html` in the YAML's `html_document` as a possible misspelling and suggests alternatives like `hmm`, but the source editor ignores it.

This is true both in RStudio Desktop 1.4.1106 on MacOS 11.3 and Ubuntu 20.04.1, and 1.4.1606 on MacOS 11.3. We'll review this inconsistency as part of the ongoing development of RStudio.

Note: In all cases, real time spell-checking ignores all of the above.

**Comment by rgayler** [comment]
> I see a discrepancy as well, but it's slightly different

The difference may be due to me using the Australian English dictionary.

**Comment by ronblum** [comment]
Added information from #9287 
> This appears to be what PR #3339 (in response to #1588) intended to do, per its description. #9094 might be related, although it might relate more specifically to the Visual Editor or a particular dictionary?

**Comment by jjallaire** [comment]
address with https://github.com/rstudio/rstudio/commit/0086c2f961fa1a5d88badcfc27d7994375c333ad

**Comment by R-Hannibal** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.01.0-daily+259
    OS Version      : Windows 10
    R Version       : 4.2.0

### Summary
Verified that spell check now consistently ignores chunk header content in both source and visual editor modes (previously chunk headers were ignored by spellcheck in source mode but picked up in visual mode).

### Automation
- No Unit or E2E tests added. Seems like a a pretty minor change with low consequences if it breaks that would take me more time to script a test for than it'd be worth.

**Comment by cm421** [comment]
An automated test has been added to verify consistent spellcheck results between visual and editor modes
