### ISSUE TITLE
RStudio Terminal colors inverting when using other Terminal than 'cmd' 

### ISSUE THREAD

**Issue by gwd999** [rstudio/rstudio#9095]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106 (and 1.4.1103)
    OS Version      :   WIN 10 PRO 20H2 build 19042.867
    R Version       :   R-4.0.4 

### Steps to reproduce the problem 
Start Rstudio; under Tools->Global Options->Terminal set up a different Terminal than "Command Prompt" (eg Git Bash, Windows Powershell, Bash (WSL2))  

### Describe the problem in detail
After a "normal" black background all Terminal output receives a sort of color inversion on its first input and all the following in- and outputs. 
Example [Windows Powershell Terminal]: 
![image](https://user-images.githubusercontent.com/306826/110878938-668f1080-82dc-11eb-97bb-b81c9229feb1.png)
 
Example [Git Bash at startup]: 
![image](https://user-images.githubusercontent.com/306826/110879243-e61cdf80-82dc-11eb-9fd5-a51f66ee1d5b.png)
Opening a vim window in RStudio Terminal: 
![image](https://user-images.githubusercontent.com/306826/110879310-0cdb1600-82dd-11eb-8be9-4a3d5b826c0c.png)

These color disturbances do not occur outside of RStudio - ie when opening Powershell, Git Bash or WSL2 bash "natively" - see below [expected behvior]. 

### Describe the behavior you expected
Nice dark background in the Terminal. 
For comparison Git Bash (outside of RStudio): 
![image](https://user-images.githubusercontent.com/306826/110879458-5166b180-82dd-11eb-9fa5-abbadd844ece.png)
or Vim in Git bash: 
![image](https://user-images.githubusercontent.com/306826/110879739-c5a15500-82dd-11eb-9e15-0391c724a033.png)

What could potentially cause such a distortion - I have not managed to identify a reason; especially since I have a different laptop that does not behave like this. 

Feel free to request additional infos if needed. 

- [X] I have read the guide for [submitting good bug reports]
- (https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
@gwd999 - thank you for reporting this issue and for the amount of detail/screenshots provided. 

Testing 1.4.1106 on Windows 10 desktop I have not been able to reproduce the issue thus far. 

I'm using the 'Nacht' editor theme with a bash terminal and Rendering Engine (Tools > Global Options > Advanced) is set to Software. Could you provide info on the exact editor theme you're using (or let us know if this occurs across multiple themes) as well as what your Rendering Engine is set to? That may aid us in our attempts to reproduce the issue. 

Thanks again for taking the time to file the issue.

**Comment by gtritchie** [comment]
There have been an increasing variety of these sorts of issues reported on Windows. See also: #7623, #5613

Ultimately we are going to need to implement this change to improve robustness here (it's a non-trivial feature-sized change): #3798

**Comment by gwd999** [comment]
> Testing 1.4.1106 on Windows 10 desktop I have not been able to reproduce the issue thus far.

@R-Hannibal - thanks for the swift reply ... I totally understand your result (ie "not reproduceable on your machine") since as I mentioned I also have another machine where this does not occur; 
but since I have basically done everything I could to resolve via the "normal methods" (uninstalling, reinstalling RStudio, removing %LOCALAPPDATA%/rstudio-desktop folders etc. I decided to report it with you here and check if this is an issue that you maybe have on the radar, or a solution for. 
Regarding your question it basically occurs on all themes) no matter if dark or light and with all Rendering engines (another screenshot below)  

![image](https://user-images.githubusercontent.com/306826/111034737-50d23600-8417-11eb-9011-ecaf279e1bd5.png)

So thanks to @gtritchie for coming to my assistance ie adding links to similar issue tickets therefore hopefully releasing me from having to supply further details and also assuring me that you already have that on your radar and started looking into it. 
Greetings 
PS: and thanx for an awesome editor!

**Comment by skeyser** [comment]
Reopening this issue. Just updated git-for-windows on my personal computer and now RStudio Terminal is inverting color scheme. Any ideas? Has this issue been resolved elsewhere?

Session and Info
`RStudio Edition : Desktop
RStudio Version : 2022.12.0+353 Elsbeth Geranium
OS Version      :   WIN 10 Education 10.0.19045 build 19045
R Version       :   R-4.2.2`

Git for windows version
2.39.2.windows.1
![Capture](https://user-images.githubusercontent.com/35746882/222859902-584d8a0a-01bc-4111-8dd4-8df684e63f62.JPG)
