### ISSUE TITLE
RStudio 1.4 ignores split_bib

### ISSUE THREAD

**Issue by NixImagery** [rstudio/rstudio#9096]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1106
    OS Version      :  OSX 11.2.1
    R Version       : 4.0.4 (2021-02-15)

### Steps to reproduce the problem
Build a bookdown project with split_bib: yes in _output.yml

### Describe the problem in detail
References are not produced at the end of each section (if split_by: section). Also, bibliography line spacing is too small.

Opening the RProj file in RStudio 1.4.1106 and building the project manifests the issue. Opening the same RProj file in RStudio 1.3.1093 and building the project does not (see screen shots attached: side by side comparison of output from RStudio 1.4.1106 on the left, and 1.3.1093 on the right)

![Screenshot 2021-03-12 at 09 23 27](https://user-images.githubusercontent.com/5462406/110921811-e20db380-8316-11eb-8345-0893340d6ca0.png)
![Screenshot 2021-03-12 at 09 23 41](https://user-images.githubusercontent.com/5462406/110921821-e4700d80-8316-11eb-913c-00fa2dc77de1.png)

### Describe the behavior you expected
References should be included at the end of a section if split_by: section, and split_bib: yes. Bibliography lines should be spaced more.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@NixImagery Thank you for bringing this up! I can reproduce the problem in RStudio Desktop 1.4.1106 and 1.4.1606, as well as that it works in 1.3.1093. We'll review this as part of our ongoing development of RStudio.

**Comment by NixImagery** [comment]
Can this be kept open please? The problem hasn’t been fixed so the bug remains. Surely it should either be fixed or the documentation updated to show this feature does not work in 1.4?

Thanks.

Nick Hood FRSA CPhys CSci MInstP MRAeS BSc (Hons) LRPS

**Comment by NixImagery** [comment]
Further to this, I installed RStudio 1.4.1717 this morning and the expected behaviour is given building a Bookdown Project. `split_bib` now functions as expected so I am closing this ticket. Thanks to the devs for fixing this :-)
