### ISSUE TITLE
Move Rmd option "evaluate chunks in directory:" to project settings or Rmd yml and change autocompletion 

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/rstudio#9097]
I love Rmarkdown. I use it in all my projects and it is one of the first things I teach as well. However, one major caveat is, as is so often, the confusion about working directories and filepaths, which becomes especially prominent when I push for my students to use RStudio projects. I then have to explain how working directories work differently in Rmarkdown.
It get's even more confusing when the behavior of code chunks changes based on
```
editor_options: 
  chunk_output_type: console
```
, which is not immediately obvious (see: https://github.com/rstudio/rstudio/issues/2595).

The `here` package tries to alleviate this confusing by building filepaths for us https://here.r-lib.org/articles/rmarkdown.html
However, when typing a filepath inside of a string in the `here` function, RStudio's autocompletion still assumes that the working directory is the directory of the Rmd file, which throws a lot of people off.
Someone previously addressed this in an issue in `here`, but didn't seem to follow up on it (https://github.com/r-lib/here/issues/35)

There is the option in RStudio to set the working directory of Rmarkdown documents globally:
![image](https://user-images.githubusercontent.com/17450586/110929891-c3b0b380-8328-11eb-8a7f-204baeeb0dcc.png)
but there are two major drawbacks to this:
- The autocompletion doesn't respect this option
- It is part of a users global configuration and thus not reproducible

What I would love to see is this option as part of either the yml frontmatter to make it a shareable property of the document, like `chunk_output_type: console`, or at least as part of the project specific RStudio configuration to make it reproducible within the project. Of course it would then be great if the autocompletion could recognize this option.
These two changes would make Rmarkdown documents inside of RStudio projects work more seamlessly. And even if it doesn't fully remove the need for the here package it would make working with it more streamlined.

Here is a loose list of previous discussions on this topic:
- https://github.com/ropensci/targets/issues/230
- https://github.com/r-lib/here/issues/14
- https://community.rstudio.com/t/setting-working-directory-in-rmarkdown/70849
- https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html
- https://github.com/ropensci/ezknitr

**Comment by ronblum** [comment]
@jmbuhr Thank you for the suggestion, and I'm glad to hear how much you enjoy R Markdown! We'll review this as part of ongoing development of RStudio.

**Comment by justbrowsn** [comment]
Having same issue

**Comment by steffen-stell** [comment]
Having "evaluate chunks in directory" in the project options would be a substantial improvement for reproducibility. If you have `.rmd`'s anywhere other than root in a repo means it does not work for others that don't have the same settings.

**Comment by DavorJ** [comment]
This is a well-researched and good suggestion. Shame it has been abandoned as it seems relevant even 5 years after its initial suggestion.
