### ISSUE TITLE
Run Shiny app on localhost vs 127.0.0.1 (or ability to customize)

### ISSUE THREAD

**Issue by gregleleu** [rstudio/rstudio#9100]
When Rstudio launches a Shiny app, the URL visited is `127.0.0.1:[port]`. 
For some authentication applications (single sign-on etc.), the domain has to be specified (we can put localhost but not an IP), hence it would be nice if the Shiny app were visited from `localhost:[port]`.

**Comment by ronblum** [comment]
@gregleleu Thank you for the suggestion! We'll review it as we continue development of RStudio.

**Comment by jvelghe** [comment]
I am actually getting this error when trying to launch a shiny app that worked previously, and I tried to specify an IP but couldn't figure that out. any suggestions on how I could get this shiny app launched again? It seems to be an issue from the RStudio end
<img width="1440" alt="Screen Shot 2021-05-07 at 7 49 00 PM" src="https://user-images.githubusercontent.com/62624873/117523460-493d9200-af6d-11eb-8528-4cbf2803b655.png">
