### ISSUE TITLE
 [Feature request] Add option to de-select wrap button by default OR add a warning for FIND box

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#9101]
During the searching process, sudden jumping from the bottom to top can be quite disturbing. It is desirable to provide an option to de-select the Wrap by default or prompt a warning box when search reaches the end. This can save a lot of efforts needed to de-select the wrap button every time when the search panel is triggered.

![snap1401](https://user-images.githubusercontent.com/11802171/111014301-f4f4a800-8357-11eb-956a-baef7b4be02f.jpg)

**Comment by ronblum** [comment]
@Sibojang9 Thank you for the suggestion! We'll review it as we continue to develop RStudio.
