### ISSUE TITLE
Midline evaluation to enhance pipe-based exploration

### ISSUE THREAD

**Issue by gh-allee** [rstudio/rstudio#9102]
I see myself and people do this all the time:

Delete or comment `%>%` in the midline to see the state of the transformation prior to other transformation or plotting

```
df %>%
  mutate(...) %>%
  pivot_longer() %>%
  summarize() # %>% # <-- either delete or comment for a sec
  ggplot(aes(...)) +
  geom_histogram()
``` 

It would be super nice if rstudio has a function where I can evaluate lines from non-blank line upto the current line where a cursor is while ignoring magrittr pipe operator.

If this dream comes to reality, this function, along with a easy keyboard shortcut, will collectively save enormous amount of time of all rstudio users

**Comment by ronblum** [comment]
@gh-allee Thank you for filing the issue! Just so I understand correctly, when you say evaluate, do you mean run the code up to that point without having to comment out the pipe `%>%`, by clicking on the midline followed by <kbd>Cmd-Return</kbd> or <kbd>Ctrl-Enter</kbd>?

**Comment by gh-allee** [comment]
@ronblum Thank you for your reply

 when you say evaluate, do you mean run the code up to that point without having to comment out the pipe %>%

Yes, exactly!

**Comment by ronblum** [comment]
@gh-allee Yep! We're on the same page regarding the request. Thanks!
