### ISSUE TITLE
Cannot call Python object from R chunk in R notebook

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/rstudio#9103]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1106
    OS Version      :  Windows 10 pro 64-bit
    R Version       :  4.0.3

### Steps to reproduce the problem
create a new R notebook 
create  python chunk and  assign value to a variable
create  r chunk  and call the python variable with py$y
Error: object  'py' not found

### Describe the problem in detail
When I try to call a python variable from a r chunk I get the error message: object 'py' not found even though the object is in hte python environment. 

### Describe the behavior you expected
I expect to see the value of the variable in the python environment displayed in the r chunk

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![python_chunk](https://user-images.githubusercontent.com/61335136/111077177-c805d980-84ac-11eb-9db3-b3f5a645b039.PNG)

**Comment by ronblum** [comment]
@rleyvasal Thank you for filing the issue! I believe the problem is that the reticulate package hasn't been loaded yet. What happens if you include `library(reticulate)` in the first R chunk?

**Comment by rleyvasal** [comment]
@ronblum Yes, loading the reticulate package `library(reticulate)`  does fix the issue. Thank you for the quick reply.

**Comment by ronblum** [comment]
@rleyvasal You're welcome! Glad it worked out.
