### ISSUE TITLE
Stan diagnostics handler duplicated on save

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9106]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1612
    OS Version      : macOS 11.2.3
    R Version       : 4.0.4

### Steps to reproduce the problem

Create a Stan document, with e.g.

```
file.edit("~/test.stan")
```

Then, execute this in the R console:

```
count <- 0
trace(.rs.stan.runDiagnostics, quote(.GlobalEnv$count <- .GlobalEnv$count + 1))
```

Then, try editing and saving the file a couple of times. Watch the `count` variable increase in the Environment pane.

### Describe the problem in detail

The save handlers are duplicated, causing the diagnostics engine to be run multiple times for each save. The `count` variable starts incrementing multiple times on each save.

### Describe the behavior you expected

Handlers should not be duplicated.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The fix should be simple:

https://github.com/rstudio/rstudio/blob/aced3d1872861c879a2f7a523768bd20bb51707a/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java#L243-L257

Those handlers need to be saved as a local variable and then detached in the detach() method.

**Comment by mikebessuille** [comment]
If this is going to resolve #9055, and if it's easy to fix, we should definitely fix this soon.

**Comment by ronblum** [comment]
Using the example above, this is getting incremented twice each time, which is better than before, but still greater than 1.

**Comment by nicokist** [comment]
@ronblum That is what I found as well.

**Comment by ronblum** [comment]
Testing note: Switching back and forth between the Editor and Console panes triggers the issue, as well, so check both with that and with updating/saving the file.

**Comment by ronblum** [comment]
Validated in
- RStudio Desktop 1.5.168 on MacOS 12 beta
- RStudio Server 1.5.168 on SLES 15 SP2 via Chrome on MacOS 12 beta
- RStudio Server 1.5.168 on Ubuntu 20.04 via RStudio Desktop 1.5.168-1

Note that even switching to a different window and back increases the count, but the counts are only incrementing by 1.
