### ISSUE TITLE
Inconsistent backspace behaviour in lists in the visual editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#9112]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1627
    OS Version      : macOS 11.2.2
    R Version       : 4.0.4

### Steps to reproduce the problem

- Type the following in the source editor in an Rmd file and then activate the visual editor

```
Hello

-   Mello
```

- Place cursor before M and hit backspace, the bullet point is deleted as expected.
- Now a sub-item to the bulleted list:

```
Hello

-   Mello

    -   Jello
```

- Still in the visual editor, place cursor right before M again. The bullet point isn't deleted, instead, the text above ("Hello") is highlighted.

### Describe the problem in detail

When a list has two levels, behaviour of backspace changes. Pressing backspace again in the scenario above deletes "Hello" instead of the bullet point.

Here is a short clip that demonstrates the issue:

https://user-images.githubusercontent.com/5965649/111314478-5c14a400-8659-11eb-88b9-1d490ddf8642.mov

### Describe the behavior you expected

I expected the bullet point to be deleted regardless of existence of second-level item in the list.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
I checked and this occurs in the simple Prosemirror example here: https://prosemirror.net/examples/basic/

This means that to overcome we need to hack around Prosemirror's default keyboard handling for lists (which is quite complicated to begin with).

**Comment by jjallaire** [comment]
I don't think we should fix this (given that its Prosemirror's default behavior, and deviating from this will be both costly and risky visa-vi regressing other list editing behavior)
