### ISSUE TITLE
Paste image followed by deleting image from R notebook (markdown) leaves old image behind on disk.

### ISSUE THREAD

**Issue by christopherball** [rstudio/rstudio#9114]
When using the extremely useful functionality to paste images from clipboard into R notebooks (I use the visual editor mode), this works perfectly.  If I later decide I want to make a change to the image and re-paste another image in its place, this results in the original image being left behind on disk under the ./images folder.

Unless I am unaware of some additional Rstudio functionality that resolves this, I would recommend deleting the file on disk as an event hook tied to deleting the image in the notebook, or at least offering a menu option to reconcile unused images for the current notebook.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@christopherball Thank you for the suggestion! We'll review it as part of our continuing development of RStudio, including the visual markdown editor. 

Also, does this cause any functional problems? I understand the need/desire for removing clutter and saving disk space, but I want to make sure that the current behavior doesn't break anything.

**Comment by christopherball** [comment]
Functionally nothing appears to break.  Beyond disk clutter, in my case, I was also trying to reduce git clutter. :)

**Comment by jjallaire** [comment]
I would very much hesitate to delete _any_ user files as a side effect of editing. Even if we could reliably remember that it was copied there as a result of a paste, the user may have spend time directly editing the image and our delete would lose those edits. In this case I'd rather have disk clutter than causing users to lose work (even if the odds of an actual loss are low).
