### ISSUE TITLE
forward PATH environment variable when running rmarkdown render

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9116]
From JJ:

> When I set the Python Environment for a project, I see that reticulate uses it by default and that it shows up in the Terminal. However, when I execute a Quarto render command it's not on the PATH (Quarto render happens in the normal course of R Markdown render, it's essentially a custom knit handler that we automatically use when we see the "format" key and Quarto is installed).
> 
> Right now my workaround is to add this to .Rprofile:
> 
> Sys.setenv(PATH=paste(path.expand("~/opt/miniconda3/envs/quarto-cli/bin"), Sys.getenv("PATH"), sep=":"))
> 
> However I don't think most users will think/know to do this. What would you think about adding the configured Python environment to the PATH whenever we execute an Async R Process? 

I think this change would happen around here:

https://github.com/rstudio/rstudio/blob/b0f09584d8f231604c5ecf3ba2d114e64b3e3f0e/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L553-L599

**Comment by ronblum** [comment]
@kevinushey Does this apply with R Markdown in general or is it specific to a custom renderer/using Quarto?

**Comment by kevinushey** [comment]
Quarto in this context is just a special kind of R Markdown output type; it motivates this change but I think in general we do want to ensure that the requested version of Python (or the associated environment) is on the PATH for renders.

**Comment by ronblum** [comment]
Tested in
- RStudio Desktop 1.4.1660 on MacOS 11.3
- RStudio Server 1.4.1660 on SLES 15 SP2 using Chrome from MacOS 11.3

by setting both global and project options. With no project, the path of the global Python interpreter is added to `PATH`, and in a project, the project-level path is added. 

However, rendering the R Markdown file is changing the `PATH` for the R session, not just scoped in the rendering. So in the Console:

```
> # Before Knitting
> Sys.getenv("PATH")
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/RStudio-pro-1.4.1660-1.app/Contents/MacOS/postback"
> 
> # After Knitting
> Sys.getenv("PATH")
[1] "/Users/ronblum/Library/r-miniconda/envs/r-reticulate/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/RStudio-pro-1.4.1660-1.app/Contents/MacOS/postback"
```

Is this intended?

**Comment by kevinushey** [comment]
I think that is intended, and is likely caused beforehand by `reticulate` itself initializing the Python session. Can you check a case where:

1. You've configured RStudio with a particular version of Python (via Global Options),
2. You have an R Markdown document to render,
3. You haven't actually run any Python code yet.

**Comment by ronblum** [comment]
Done. I didn't run any Python code, in fact, when rendering, just R chunks.

Note: Outside of R Markdown, the same thing happens when `reticulate::repl_python` is invoked:
```
> Sys.getenv("PATH")
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/RStudio-pro-1.4.1660-1.app/Contents/MacOS/postback"
> reticulate::repl_python()
Python 3.6.11 (/Users/ronblum/Library/r-miniconda/envs/r-reticulate/bin/python)
Reticulate 1.18.9006 REPL -- A Python interpreter in R.
>>> quit
> Sys.getenv("PATH")
[1] "/Users/ronblum/Library/r-miniconda/envs/r-reticulate/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/RStudio-pro-1.4.1660-1.app/Contents/MacOS/postback"
```
