### ISSUE TITLE
RStudio session launch diagnostics don't pick newest log entries

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9117]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4+

### Steps to reproduce the problem

1. Collect session logs for enough time that a `.rotated.log` session log file appears (or create one manually)
2. Break R such that it will not launch correctly
3. Start RStudio

### Describe the problem in detail

The diagnostics screen that appears shows old rotated logs instead of more recent logs. 

![image](https://user-images.githubusercontent.com/470418/111391853-a6eee580-8672-11eb-9830-f87e1441cf82.png)

This is a problem because the old rotated logs are not likely to contain the error message that caused R to fail to start.

### Describe the behavior you expected

Only the most recent logs should be displayed. Here's where we attempt to enforce this:

https://github.com/rstudio/rstudio/blob/1bb39da12b54628625286e074e49ecbf89f77752/src/cpp/desktop/DesktopSessionLauncher.cpp#L223-L238

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
The user who created this screenshot shared the directory listing of `~/.local/share/rstudio/log`, which showed that the correct log file existed *and* had a newer write time than the `.rotated.log` file that was displayed. Maybe we're just sorting incorrectly.

**Comment by mikebessuille** [comment]
Marking for Juliet Rose since this affects both customer's and support's ability to diagnose problems

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1661
    OS Version      : mac OS 11.2.3
    R Version       : 4.0.3

Verified that:
- Version and platform info are included in error diagnostics
- The "copy report" button copies the diagnostic report in plain markdown text
- The "recent log error" shows the most recent log
