### ISSUE TITLE
Add "x" to close the file on the list of all files open

### ISSUE THREAD

**Issue by kelnerrr** [rstudio/rstudio#9118]
I would love to have the possibility to close the files directly from the list of all files.
We can close each file with an "x" button on the file tab now but those "x"s do not appear on the list of all open files.
Here is a simple sketch of the idea:
![image](https://user-images.githubusercontent.com/16717101/111443969-32678580-870a-11eb-8749-a5a446b62d81.png)

**Comment by ronblum** [comment]
@kelnerrr Thank you for the suggestion! I'll mark it for review as part of our ongoing development of RStudio.

[Comparison point: The Packages pane uses this for uninstalling packages.]

**Comment by colearendt** [comment]
Love this idea
