### ISSUE TITLE
Breakpoints and stepping not working properly with R4

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#9119]
Breakpoints and stepping ('n') worked fine in R3.4. Attached is a screen capture demonstrating problems we came across while trying to upgrade to R4.0.3:

(1) After stopping at a breakpoint, a 'next' command ('n') is issued by the IDE automatically, so the breakpoint is missed.
(2) This 'n', as well as any user-invoked 'n', actually operate as a 'continue' ('c') - so the ability to step over a single code line is lost.

https://user-images.githubusercontent.com/73080/111445739-5e880400-8714-11eb-93bb-cd33662b9a97.mp4

### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 18.04.5
    R Version       : 4.0.3 (2020-10-10)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@OfekShilon Thank you for raising the issue! Did this occur in previous versions of RStudio Server, or is it new in 1.4?

**Comment by OfekShilon** [comment]
We only recently started experimenting with R4, and only on the latest
RStudio. No idea how previous RStudio versions handled R4.

**Comment by OfekShilon** [comment]
I just verified that the stepping problem doesn't happen in naked R console:
```r
> ff <- function() {
+ print("a")
+ print("b")
+ print("c")
+ print("d")
+ }
> debug(ff)
> ff()
debugging in: ff()
debug at #1: {
    print("a")
    print("b")
    print("c")
    print("d")
}
Browse[2]> n
debug at #2: print("a")
Browse[2]> n
[1] "a"
debug at #3: print("b")
Browse[2]> n
[1] "b"
debug at #4: print("c")
Browse[2]> n
[1] "c"
debug at #5: print("d")
Browse[2]> n
[1] "d"
exiting from: ff()
```
It does happen in emacs+ESS.  So maybe something did change in R-debugging internals.

**Comment by OfekShilon** [comment]
> @OfekShilon Thank you for raising the issue! Did this occur in previous versions of RStudio Server, or is it new in 1.4?
@ronblum  did you manage to reproduce it?  For us this is quite major (severely degrades the debugging experience)

**Comment by ronblum** [comment]
@OfekShilon I cannot, at least not exactly, but I'll kick it up a notch to see if there's something else to look at.

@kevinushey Would you mind taking a look at this? I'm not sure if the way I'm not sure if the way I'm trying to reproduce this is correct. Thanks!

**Comment by kevinushey** [comment]
Seems to be working for me on macOS Desktop:

https://user-images.githubusercontent.com/1976582/112549404-fe7c0800-8d7a-11eb-9498-464c97259608.mov

Note that even though the `n` is sent, the debugger is still placed into the correct context.

**Comment by OfekShilon** [comment]
I upgraded to R4.0.4 and srepping seems to be working again... I suspect this item in 4.0.4 NEWS is related:

.traceback(n) keeps source references again, as before R 4.0.0, fixing a regression;
introduced by the PR#17580.

Sorry for troubling you guys. Closing the bug.

**Comment by ronblum** [comment]
@OfekShilon It's no trouble at all! This is what we're here for, to listen to your RStudio IDE troubles and help diagnose potential bugs—so, thank you for identifying the cause and resolution!

**Comment by OfekShilon** [comment]
I regret to say this just started happening  for R4.0.4 in RStudio too.

**Comment by kevinushey** [comment]
If this is now working, then the question I think is: what changed? Presumedly there's something else going on that's influencing the behavior here.

**Comment by OfekShilon** [comment]
@kevinushey  I agree completely - but how can I check what?
I poked at this from various directions, debugged `.rs.findBreakpointSteps` and `.rs.stepsAtLine` (both called upon breakpoint setting, not stepping), and even stopped at `.doTrace`. I can verify that `.doTrace(browser)` is called, but the IDE triggers `n` immediately afterwards.
I also have a properly debuggable R3.4 environment, and I verified that e.g. `.rs.findBreakpointSteps(body(f))` returns identical to the problematic R4 environment.

**Comment by kevinushey** [comment]
> I agree completely - but how can I check what?

I wish I knew!

> It does happen in emacs+ESS. So maybe something did change in R-debugging internals.

Is that still true? It could be something special that R does if it sees it's being run in a certain way (?)

**Comment by OfekShilon** [comment]
I apologize again - it was us after all. A package loaded a C library that implemented functions which clashed with RStudio's...

**Comment by kevinushey** [comment]
Which package was that? Is this something we could resolve in RStudio,, or is the package itself misbehaving in some way?

**Comment by OfekShilon** [comment]
@kevinushey  no, it was an internal package.  Not sure how functions like `debug` were resolved to the shared library that came with it, but that was the root cause.
