### ISSUE TITLE
Option to modify zoom in/out shortcuts

### ISSUE THREAD

**Issue by MichalLauer** [rstudio/rstudio#9125]
### Context of use
When using RStudio, the shortcut to "Move focus to Source" zooms in instead of actually changing the focus. I've uploaded the behavior on [youtube](https://youtu.be/gdASwZyTQFU), so you can take a quick look. This gets really annoying as I have to lift my mouse every time when switching between console and source. The same behavior (zooming in) happens in both cases - when I press ctrl+1 and ctrl++. I've tried asserting the "Zoom In" shortcut to a different key, but it still zooms in with ctrl+1.

**Default browser**: Google Chrome
**Keyboard layout**: Czech - Czech (QUERTY) keyboard
**RStudio version**:  1.4.1103
**OS**: Windows 10

### Proposed solutions
My guess is that the main problem is with Accessibility settings. As per the image below, "Zoom In" is bound on ctrl++.

![image](https://user-images.githubusercontent.com/20439350/111681723-df81f100-8823-11eb-88fe-feca7911e21c.png)

[On the RStudio blog](https://support.rstudio.com/hc/en-us/articles/360044226673-RStudio-Accessibility-Features#zoom_h) is written that zooming relies on your default browser. If we could either bind manually these shortcuts or disable this Accessibility altogether, this issue should be fixed.

I've found similar issues #5612 and #1683, but they were closed. I decided to put raise this as an Enhancement as this behavior is expected, but could be greatly improved.

---------
- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@MichalLauer Thank you for raising this! This sounds like a bug: <kbd>Ctrl-1</kbd> should switch to the source pane, not zoom in. I just did a quick check of Czech QWERTY: Can you confirm that <kbd>+</kbd> is achieved with <kbd>Shift-1</kbd>? By comparison, on a US QWERTY keyboard, <kbd>Shift-=</kbd> is used. My guess is that we're not properly respecting the Czech QWERTY keyboard layout.

**Comment by MichalLauer** [comment]
@ronblum After pressing `shift+1`, i get only 1. When I press `1` without any modifiers, i get +.

**Comment by MichalLauer** [comment]
@ronblum Reproduced in Notepad, Notepad++, Chrome, and RStudio - `shift+1` makes 1, `ctrl+1` doesn't produce any character.

**Comment by ronblum** [comment]
@MichalLauer Aha! I just added the Czech QWERTY layout, and it turns out that I misunderstood how the number and symbol keys work: In Czech QWERTY, 1 and + are the same key, with + being the individual keypress, and 1 achieved by adding shift. But in US QWERTY, it's the opposite: 1 and ! are on the same key, but the individual keypress is 1, and adding shift results in !. 

This is a bug. Thank you for your help!

**Comment by MichalLauer** [comment]
@ronblum Yup, that's it! Thanks for taking the time to understand this issue. Looking forward to the fix:)

**Comment by ronblum** [comment]
@MichalLauer My pleasure!
