### ISSUE TITLE
Bug with rainbow parentheses inside \Sexpr in .Rnw-files

### ISSUE THREAD

**Issue by pehaugedal** [rstudio/rstudio#9127]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106 and 1.4.1641 (daily build)
    OS Version      : Windows 10 64-bit
    R Version       : 4.0.4

### Steps to reproduce the problem
1. Turn on rainbow parentheses: Tools --> Global options --> Code --> Display
2. Create a new .Rnw-file
3. Insert the following text into the file:
    At first everything is fine, but after these rainbow parenthesis \Sexpr{((()))}, it is no longer fine. Words like for, if 
    and else are interpreted as code and marked in blue, and functions like \Sexpr{} are no longer recognised.

### Describe the problem in detail
In .Rnw-files, when the option for rainbow parentheses are turned on, text starts getting interpreted as code after 
there have been parentheses inside a \Sexpr, and functions like \Sexpr are no longer recognised.

### Describe the behavior you expected
I expect the text on both sides of a \Sexpr to be interpreted the same way no matter if the \Sexpr contains 
parentheses or not. 

By turning off rainbow parentheses you get the expected behaviour.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is where RStudio embeds R highlight rules for use within `\Sexpr{}`:

https://github.com/rstudio/rstudio/blob/75778c39c0669507a553830680f573c43675dd5e/src/gwt/acesupport/acemode/sweave_highlight_rules.js#L40-L53

That embedded rule needs to be made rainbow-aware.

**Comment by abeeisnotabug** [comment]
Hi, I'm having the same issue in 2022.12.0+353.
