### ISSUE TITLE
Inconsistent console wrap output behavior in R Studio Server

### ISSUE THREAD

**Issue by mpr1255** [rstudio/rstudio#9132]
### System details

    RStudio Edition : Server
    RStudio Version : Version 1.4.1106
    OS Version      : Ubuntu 20.04 (Note: this is running in WSL 1 on Windows 10, 20H2 OS build 19042.867)
    R Version       : R version 4.0.4 (2021-02-15)  

### Steps to reproduce the problem
When R Studio Server attempts to print a string without any spaces, the text does not wrap in the console as it should. You can test it like this:

```

strings_wont_wrap <- c("Sedutperspiciatisundeomnisistenatuserrorsitvoluptatemaccusantiumdoloremquelaudantium,totamremaperiam,eaqueipsaquaeabilloinventoreveritatisetquasiarchitectobeataevitaedictasuntexplicabo.Nemoenimipsamvoluptatemquiavoluptassitaspernaturautoditautfugit,sedquiaconsequunturmagnidoloreseosquirationevoluptatemsequinesciunt.Nequeporroquisquamest,quidoloremipsumquiadolorsitamet,consectetur,adipiscivelit,sedquianonnumquameiusmoditemporainciduntutlaboreetdoloremagnamaliquamquaeratvoluptatem.Utenimadminimaveniam,quisnostrumexercitationemullamcorporissuscipitlaboriosam,nisiutaliquidexeacommodiconsequatur?Quisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequatur,velillumquidoloremeumfugiatquovoluptasnullapariatur?", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

print(strings_wont_wrap)

strings_will_wrap <- c("Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?")

print(strings_will_wrap)

```
### Describe the problem in detail
If you run the above in an R Studio Server instance (I have done so on two now - my own and the latest pro version), you'll find that not only do the `strings_wont_wrap` not wrap, but AFTER running them, the `strings_will_wrap` will no longer wrap!

This suggests it's indeed a bug, since the output behavior of the console changes depending on previous inputs. After clearing the console, `strings_will_wrap` will wrap properly again.

### Describe the behavior you expected
All of those strings should simply wrap when printed to the console. This is the behavior in the Windows R Studio desktop IDE. It's inconsistent and confusing otherwise.

PS: Note that it took about an hr to isolate this behavior. I thought it was `data.table` causing the problem, but I investigated and found this got the same result. I'm dealing with a lot of Chinese text strings that don't have spaces; works fine in Windows, breaks in R Studio Server.

PPS: Note that in the R console in Ubuntu -- not R Studio -- the wrapping behavior is as expected. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@mpr1255 Thank you for raising this! So that we can try to reproduce this in the same way, what browser are you using?

**Comment by mpr1255** [comment]
Hello! I was using Edge, but I just tried it in Brave and the problem persists. But even if you do it in the R Studio Cloud server -- i.e.  the official one, Version 1.4.1106-5 -- it displays this behavior. So I think that means it's not a WSL issue. 

Final point: I've now resorted to pushing stuff to console using `as_tibble()`, and it wraps as expected.

**Comment by colearendt** [comment]
We should see if this still reproduces, since it's been a while

**Comment by mpr1255** [comment]
Apologies. I should have updated on this. This error no longer occurs, as far as I can tell. I get appropriately wrapped text now when printing with data.table (that was based on another task; but I just re-ran the reprex and confirm once more).

**Comment by ronblum** [comment]
@mpr1255 No problem—thank you for the update!
