### ISSUE TITLE
Extra commands for git

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#9133]
Looking back through my command line history, I see a few commands repeated frequently.

`git stash` is one, but issue https://github.com/rstudio/rstudio/issues/8603 has already suggested it.

The others are:  

- `git difftool` to run an external diff tool.  I think adding support for this need only involve a configuration change so the `git diff` button ran my external tool instead of the standard one.  (I use Beyond Compare, in case anyone is interested.)

- `git merge`.  I always get nervous before running this, because I can't remember whether you specify one name or two.  (You checkout the target, specify the name of the one to merge into it.)  A friendly dialog would be reassuring.

And that's it for my request.  I have used other commands:  `git remote`, `git fetch`, `git branch -d`, but I'm not sure they'd be appropriate additions to RStudio.

**Comment by ronblum** [comment]
@dmurdoch Thank you for the suggestion—including building on top of the previous suggestion! I'll mark it for consideration as we continue to develop RStudio.

**Comment by colearendt** [comment]
Related to #2994 as well

**Comment by jeffkeller-einc** [comment]
I would also like the ability to use an external diff tool. For example, [difftastic](https://difftastic.wilfred.me.uk/introduction.html) provides syntax-aware diffing.

I tried setting`git config` to use `difft` but this results in a blank diff in the RStudio "Review Changes" window.

```bash
git config diff.external difft
git diff
```
<img width="766" alt="Screenshot 2023-08-31 at 9 17 52 AM" src="https://github.com/rstudio/rstudio/assets/113363108/46198f30-e66f-4d3e-84ea-bca4f2f6a86f">

<img width="674" alt="Screenshot 2023-08-31 at 9 15 28 AM" src="https://github.com/rstudio/rstudio/assets/113363108/37fde856-220a-4503-a4aa-cc043b50cd2f">
