### ISSUE TITLE
Packages fail to load in R Console only

### ISSUE THREAD

**Issue by MikeJohnPage** [rstudio/rstudio#9134]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : macOS 11.2.3
    R Version       : 4.0.4

### Steps to reproduce the problem
Load selected packages in the R Console in RStudio, this issue will focus on a single package:

```r
library(utf8)
```

### Describe the problem in detail
The R Console in RStudio fails to load certain packages. The error message indicates the package image (or sometimes a package dependency) cannot be found. For example:

```
> library(utf8)
Error: package or namespace load failed for ‘utf8’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/4.0/site-library/utf8/libs/utf8.so':
  dlopen(/usr/local/lib/R/4.0/site-library/utf8/libs/utf8.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/utf8/libs/utf8.so
  Reason: image not found
```

However, if I naviagte to the correct directory specifed in the error message, the correct files *can* be found. Outside of the R console (e.g., in a Terminal or other editor such as VSCode), the same packages load successfully without error.

### Describe the behavior you expected
I expected the R Console to load packages that can be loaded outside of it.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Additional Information
- I've uninstalled and reinstalled R
- I've uninstalled and reinstalled RStudio
- I've uninstalled and reinstalled the packages that are failing to load
- I use Homebrew to manage R, RStudio, and system dependencies
- It *may* be related to #5836
-  Session Info:

```
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin20.3.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /usr/local/Cellar/r/4.0.4_1/lib/R/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4 tools_4.0.4 
```

**Comment by ronblum** [comment]
@MikeJohnPage Thank you for raising the issue! I'm marking for review, to try to reproduce. In the meantime, what are a couple of other packages that won't load? Thanks!

**Comment by kevinushey** [comment]
>   dlopen(/usr/local/lib/R/4.0/site-library/utf8/libs/utf8.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib

> LAPACK: /usr/local/Cellar/r/4.0.4_1/lib/R/lib/libRlapack.dylib

This is probably caused by some kind of crossed wires between your Homebrew R installation and your CRAN R installation.

**Comment by MikeJohnPage** [comment]
@ronblum other packages that fail to load include `sf`, `corrr`, and `ggridges`.

@kevinushey I believe I have only installed R via Homebrew and not CRAN directly (unless I have inadvertently done this). My first thought too was that this is probably an issue with Homebrew. It is just strange that some packages load in the R console, and all packages load outside of RStudio. This lead me to wonder if RStudio was causing the error. Any ideas on how we can test this hypothesis?

Thank you both for taking the time to respond.

**Comment by astayleraz** [comment]
I tried to reproduce this on my mac with 11.2.3 and r 4.0.4 and I was not seeing this issue. I had installed r from here https://cran.r-project.org/bin/macosx/R-4.0.4.pkg. Not sure if you try installing r from here as well if that works for you @MikeJohnPage ?

**Comment by MikeJohnPage** [comment]
@astayleraz thanks for trying to replicate the issue.

I've not installed the official CRAN binary you listed, because ideally, I would like to keep using homebrew to manage my R installation if possible.

The fact you can't replicate the issue indicates it probably is something to do with homebrew. It is just strange that everything works fine outside of RStudio in VSCode and Terminal.

**Comment by MikeJohnPage** [comment]
I completely uninstalled RStudio and R from my machine and then installed the official R binary from CRAN. The same problem now persists in a Terminal window so I can confirm this is not an RStudio issue. No idea what has happened! Thanks for looking into this.
