### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [rstudio/rstudio#9135]
[jw@cn05 build]$ cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release -DBOOST_INCLUDE_DIR=/usr/include/boost
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Machine architecture: aarch64
-- CMake build type: Release
-- Using RStudio tools root: /opt/rstudio-tools/aarch64
-- LSB release: fedora
-- Configured to build GWT
-- Using ant: /usr/bin/ant
-- Configured to install GWT
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
CMake Error at src/cpp/CMakeLists.txt:222 (message):
  yaml-cpp not found (re-run dependencies script to install)

-- Configuring incomplete, errors occurred!
See also "/home/jw/rstudio/build/CMakeFiles/CMakeOutput.log".
[jw@cn05 build]$ 

But yaml-cpp is yum-installed.

**Comment by ronblum** [comment]
@LutzWeischerFujitsu Thank you for raising this!

@kevinushey or @jmcphers Do you have any suggestions of what to look at, to try to reproduce?

**Comment by mikebessuille** [comment]
We don't currently support compiling for arm64 on linux; we have a request for this enhancement: https://github.com/rstudio/rstudio/issues/8809.  Closing this as a duplicate.

**Comment by kevinushey** [comment]
Or set `-DRSTUDIO_USE_SYSTEM_YAML_CPP`. https://github.com/rstudio/rstudio/blob/e8c085170ca51b29ec1d7bc1385f5ce8d9ce6f8c/src/cpp/CMakeLists.txt#L209-L219
