### ISSUE TITLE
create redshift connection fails when sourcing file from RMarkdown

### ISSUE THREAD

**Issue by ras44** [rstudio/rstudio#9136]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 20.04 focal
    R Version       : 4.0.3

### Steps to reproduce the problem
I have three files in a project:
- **project/R/exploratory/study_001.Rmd**
- **project/R/setup.R**  (contains library imports and other functions)
- **project/R/config.R** (creates a list named `config` containing user-specific configuration like redshift username, password)

**project/R/exploratory/study_001.Rmd:**
```
library(here)
# Define config in config.R; see config_example.R for an example to modify
source(here('R/config.R'))
source(here('R/setup.R'))
```

**project/R/setup.R:**
```
library(here)
library(RJDBC)
library(whisker)

# a shortcut to whisker-render queries
wr <- function (s, c = config){
  whisker.render(s,c)
}

# download Amazon Redshift JDBC driver
# download.file('http://s3.amazonaws.com/redshift-downloads/drivers/RedshiftJDBC42-1.2.1.1001.jar','RedshiftJDBC42-1.2.1.1001.jar')

# connect to Amazon Redshift
driver <- JDBC("com.amazon.redshift.jdbc42.Driver", "redshift-jdbc42-2.0.0.2.jar", identifier.quote="`")

url <- wr(
  "jdbc:redshift://redshift_url:redshift_port/dwhprod?ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory"
)

conn <- dbConnect(
  driver,
  url,
  user=config$username,
  password=config$redshift_password)

# un-comment to list tables
dbListTables(conn)

```

**project/R/config.R**:
```
config <- list(
  
  username = 'my_username',

  # uncomment the below to define redshift password in config
  redshift_password = 'my_password',

  # define a date string
  today = format(Sys.Date(),"%Y%m%d")
)
```

If I first manually run **project/R/config.R** (create the config list), then **project/R/setup.R** (create the connection to redshift), the connection is properly set up and I can then use the connection in the rmarkdown document to query databases.  However, if I attempt to run code chunks in the RMarkdown document, which sources the config.R and setup.R files in the same sequence, I receive the error:
```

Error in .jfindClass(as.character(driverClass)[1]) : java.lang.ClassNotFoundException

8. | stop(structure(list(message = "java.lang.ClassNotFoundException", call = .jfindClass(as.character(driverClass)[1]), jobj = new("jobjRef", jobj = <pointer: 0x559a40bca3a8>, jclass = "java/lang/ClassNotFoundException")), class = c("ClassNotFoundException", "ReflectiveOperationException", "Exception", "Throwable", "Object", ...
-- | --

7. | .jfindClass(as.character(driverClass)[1])
-- | --

6. | is.jnull(.jfindClass(as.character(driverClass)[1]))
-- | --

5. | JDBC("com.amazon.redshift.jdbc42.Driver", "redshift-jdbc42-2.0.0.2.jar", identifier.quote = "`") at setup.R#18
-- | --

4. | eval(ei, envir)
-- | --

3. | eval(ei, envir)
-- | --

2. | withVisible(eval(ei, envir))
-- | --

1. | source(here("R/setup.R"))
-- | --

```

Further, if I then attempt to manually source R/setup.R by running all the code in it, I receive the same error.  I have to restart the R session and only then can I source the config.R and setup.R again to correctly make the connection to redshift.

## Environment details
Perhaps something is happening that is corrupting the environment from the R markdown document?  I have also tried all permutations of the options:

```
source(here('R/setup.R'), local=TRUE/FALSE, chdir=TRUE/FALSE)
```

I am also using renv to manage all packages in the library.

Finally, I notice that when I run `print(Sys.getenv())` in setup.R, I get slightly different results, based on whether I am sourcing setup.R from the RMarkdown document or not:

Running code manually in `setup.R`:
```
RENV_DEFAULT_R_ENVIRON               <NA>
RENV_DEFAULT_R_ENVIRON_USER          <NA>
RENV_DEFAULT_R_LIBS                  <NA>
RENV_DEFAULT_R_LIBS_SITE             
RENV_DEFAULT_R_LIBS_USER             ~/R/x86_64-pc-linux-gnu-library/4.0
RENV_DEFAULT_R_PROFILE               <NA>
RENV_DEFAULT_R_PROFILE_USER          <NA>
RENV_PROJECT                         /home/xyz/2021_03_15_matchit_example
```

Running code via sourcing `setup.R` from the R-markdown document:
```
RENV_DEFAULT_R_ENVIRON       <NA>
RENV_DEFAULT_R_ENVIRON_USER
                             <NA>
RENV_DEFAULT_R_LIBS          <NA>
RENV_DEFAULT_R_LIBS_SITE     
RENV_DEFAULT_R_LIBS_USER     ~/R/x86_64-pc-linux-gnu-library/4.0
RENV_DEFAULT_R_PROFILE       <NA>
RENV_DEFAULT_R_PROFILE_USER
                             <NA>
RENV_PROJECT                 /home/xyz/2021_03_15_matchit_example
```

ie. the RENV_DEFAULT_R_ENVIRON_USER and RENV_DEFAULT_R_PROFILE_USER variables are displayed on the next line.

No idea if that actually has anything to do with the issue at hand.

### Describe the behavior you expected
I would be able to source config.R and setup.R and have the connection created just as if I had manually run the code in each file sequentially.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
@ras44: did you intend to close this issue? The issue is most likely something Java-related though (perhaps the `CLASSPATH` environment variable needs to be set)

**Comment by ras44** [comment]
hi @kevinushey - thanks for following up.  I did close the issue, because I realized that the code in the setup.R file was not using `here()`.

```
# connect to Amazon Redshift
driver <- JDBC("com.amazon.redshift.jdbc42.Driver", "redshift-jdbc42-2.0.0.2.jar", identifier.quote="`")
```

So I believe what was happening is that it just wasn't finding the .jar file and providing a somewhat unhelpful error message.  Once I converted to:

```
# connect to Amazon Redshift
driver <- JDBC("com.amazon.redshift.jdbc42.Driver", here("redshift-jdbc42-2.0.0.2.jar"), identifier.quote="`")
```

everything worked fine.  Since the markdown file is not in the same path as the config file which is not in the same path as the .jar file, the .jar was not being found, even with the chdir options.

Thanks again for taking the time to check in.
