### ISSUE TITLE
[Documentation] Would it be possible to mention boost as dependency, and the version of boost?

### ISSUE THREAD

**Issue by rubyFeedback** [rstudio/rstudio#9137]
Hey there guys,

I am using linux, slackware linux, and self-compiling from source, so I know a
bit about linux.

I am trying to compile rstudio-1.4.1106.

Right now I seem to not have boost installed or an adequate version:

    Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least
    version "1.69.0")

Ok no problem, that is my fault - so I am compiling boost right now.

I am using boost 1.74.0 right now:

https://sourceforge.net/projects/boost/files/boost/1.74.0/boost_1_74_0.tar.bz2

However had, my experience has been that often newer version of
boost do not work. For example, the game called "wesnoth" has this
problem where I then have to use an older boost version.

Anyway - my request is quite simple.

- Could it be mentioned somewhere which boost versions or range
are allowed?

I had a look at:

https://github.com/rstudio/rstudio/blob/master/dependencies/common/install-boost

and this shell file seems to simply hardcode boost 1.69.0, so I am testing
with 1.74.0, and if that does not work I'll install boost 1.69.0 - but it would
be nice if this could be mentioned somewhere more explicitely.

**Comment by kevinushey** [comment]
FWIW you can invoke CMake with `-DRSTUDIO_USE_SYSTEM_BOOST` to tell RStudio to build with whatever version of Boost is installed globally for the system.

**Comment by ronblum** [comment]
@rubyFeedback Let us know if this works—it may be helpful to others, as well!

**Comment by kevinushey** [comment]
We might also want to have something like `-DRSTUDIO_USE_SYSTEM_LIBRARIES` to force RStudio to use system versions of installed libraries as opposed to the versions we bundle and install.
