### ISSUE TITLE
Previous and next plot button on the plot zoom window

### ISSUE THREAD

**Issue by TheChemENG** [rstudio/rstudio#9139]
Dear All, 
Is it possible to add two buttons on the plot zoom window to switch between plots directly from the zoom plot panel ? 
Currently, to switch between the plots (next or previous) the users need to go back to the plots panel on RStudio window. 

Thanks in advane,
Kind regards.

**Comment by ronblum** [comment]
@TheChemENG Thanks for the suggestion! We'll consider it as we continue development of RStudio.

**Comment by colearendt** [comment]
I love this idea
