### ISSUE TITLE
RStudio does not interactively run external code chunks in RMarkdown

### ISSUE THREAD

**Issue by smingerson** [rstudio/rstudio#9140]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Windows 10
    R Version       :  4.0.4

### Steps to reproduce the problem

1. Create a new RMarkdown document, deleting the placeholder content.
2. Add a chunk with the following definition.
````
```{r code = readLines("test.R")}
```
````
(Code edited to reflect Kevin Ushey's advice below.)

3. Create the `test.R` file with content `a <- 1;print(a)`.
4. Click "Run current chunk" for the code chunk.
5. Note that `a` does not print, and does not get created.
6. Knit the document. Notice that `a` is created and printed. 

### Describe the problem in detail

RMarkdown allows [external scripts](https://bookdown.org/yihui/rmarkdown-cookbook/option-code.html) to be loaded into a chunk using the `code` chunk argument. When running these chunks interactively, RStudio does not execute the code.
This can be worked around using `source("test.R")` in the chunk content, but is less preferable, as outlined in the link.

### Describe the behavior you expected

RStudio should evaluate the code argument and load the results into the environment. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
For what it's worth, you can include an arbitrary number of backticks for your code chunk; e.g.

`````
```{r}
# this is an R code chunk; I've used 5 backticks for the code fence
```
`````

**Comment by ronblum** [comment]
@smingerson Thank you for bringing this to our attention! I can reproduce this issue on
- RStudio Desktop 1.2.5042 on MacOS 11.3
- RStudio Server 1.4.1639 on Ubuntu 20.04.2 using Chrome on MacOS

Note that this isn't just with using an external file; `code` is ignored even if this chunk is run:

````
```{r code=1}
```
````

It evaluates when the file is knitted, though.

**Comment by ronblum** [comment]
.
