### ISSUE TITLE
Terminal in Rstudio doesn't share the PATH variable in windows10

### ISSUE THREAD

**Issue by issactoast** [rstudio/rstudio#9142]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1666 (juliet-rose daily)
    OS Version      : Windows 10 20H2
    R Version       : R4.0.x (I tried 4.0.5), RTools40 for Windows

### Steps to reproduce the problem
- install R 4.x
- install rtools40 per https://cran.r-project.org/bin/windows/Rtools/
- modify system path (control panel) to include `C:\rtools40\mingw64\bin`
    - Tap Windows key, type "edit system environment variables" and select that option
    - Click Environment Variables button in resulting dialog
    - Double-click Path in the lower region (System variables) to bring up the edit UI
    - Select "New" button to add a path
    - Enter  `C:\rtools40\mingw64\bin`, then OK buttons until all dialogs dismissed
    - Start a new command-prompt or Powershell, then execute `c++ --version` to confirm tools are on path:

```
C:\Users\gary_>c++ --version
c++ (Built by Jeroen for the R-project) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- Start RStudio, configure terminal use use Powershell (Tools / Global Options / Terminal / "New Terminals Open With" dropdown)
- Start a new RStudio terminal (Tools / Terminal / New Terminal)
- Try executing `c++ --version` in that Powershell terminal

### Describe the problem in detail
User reports this is not working. I have not been able to reproduce but capturing the steps I tried here.

Note you must start a new RStudio instance (i.e. close current ones, then restart) after modifying the system path for this to work.

### Describe the behavior you expected
The RStudio terminal, using Powershell, sees the RTools on the path just like a standalone Powershell.

This is working for me, so this is (so far) a no-repro.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

(user's original report here, didn't follow our template so I filled that out above)
![rcpp](https://user-images.githubusercontent.com/13303749/112232843-af659400-8c0f-11eb-80c1-21914a88c552.png)

Hi, I register the path "rtools40\mingw64\bin" to the PATH variable in windows10 and it works in PowerShell. However, when I open PowerShell from Rstudio, c++ command doesn't work.

Is this a bug or should I do an extra thing in Rstudio?

**Comment by gtritchie** [comment]
Interesting, I'll take a look and see if I can reproduce this.

@issactoast How, specifically, are you setting the PATH variable? Control panel? Per user, or for the entire system? Thanks!

**Comment by issactoast** [comment]
![env](https://user-images.githubusercontent.com/13303749/112368145-23a44400-8cb1-11eb-9c32-79cb164b0e39.png)

I set PATH to system-wide and I changed it via the control panel as in the picture above. Also, I made a separate R project as in the previous picture I attached.

**Comment by gtritchie** [comment]
Thanks, haven't had a chance to try this yet but will soon!

**Comment by gtritchie** [comment]
I haven't been able to repro, see my steps above. You didn't specify which version of RStudio you were using (in the future please fill out the template you get when opening a new issue in this repo), so I tried latest daily build.

Let me know if my steps match what you had tried.

**Comment by issactoast** [comment]
@gtritchie Hi gray thanks for the detailed follow-up! Sorry for the unfilled template, I will recheck every step you put and add more detailed repro steps!
