### ISSUE TITLE
RStudio does not start to work

### ISSUE THREAD

**Issue by Didehkhani** [rstudio/rstudio#9147]
The issue tracker is not for questions. If you have a question, please feel free to ask it on our community site, at https://community.rstudio.com/c/rstudio-ide.

Today I was going to install R and RStudio, all the steps went well, but when I clicked on RStudio, the program did not run and after a long time, it gave an error. I deactivated the program several times and reinstalled it, but it did not work. I just got a white page saying"  "  for half an hour and then I closed it.I also searched on various sites but again no results were found.  Do you have a suggestion?
 RStudio-1.4.1106
Windows 10
R-4.0.4-win
![3](https://user-images.githubusercontent.com/73781831/112384542-2e3ff700-8d0c-11eb-975d-01926179624e.jpg)
![333](https://user-images.githubusercontent.com/73781831/112384545-2f712400-8d0c-11eb-9dd5-4bddaf235f87.jpg)

e700-8d0b-11eb-9c07-b9cb3c987f84.jpg)

**Comment by ronblum** [comment]
@Didehkhani Thank you for filing the issue! I'm sorry you're running into this. I'm looking back at a few issues with similar issues, although some seem to be resolved. A couple of questions that might be of use:

1) Can you run a diagnostics report and provide it? The instructions for RStudio Desktop are about halfway down the page here: https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
2) What version of R are you using, and did you update it recently?
3) Is this a problem in RStudio Desktop 1.3.1093? It's available at https://www.rstudio.com/products/rstudio/older-versions/
4) Are you running any antivirus programs, by chance?

**Comment by mikebessuille** [comment]
This issue needs more information before we can reproduce it and consider it.

**Comment by Didehkhani** [comment]
HiI bought a SSD and change my Windows and installed the last versions of both R and RStudio so the problem solved.
    On Friday, March 26, 2021, 05:57:59 PM GMT+4:30, Ron Blum ***@***.***> wrote:  
 
 


@Didehkhani Thank you for filing the issue! I'm sorry you're running into this. I'm looking back at a few issues with similar issues, although some seem to be resolved. A couple of questions that might be of use:
   
   - Can you run a diagnostics report and provide it? The instructions for RStudio Desktop are about halfway down the page here: https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
   - What version of R are you using, and did you update it recently?
   - Is this a problem in RStudio Desktop 1.3.1093? It's available at https://www.rstudio.com/products/rstudio/older-versions/
   - Are you running any antivirus programs, by chance?
