### ISSUE TITLE
Support building an RStudio Desktop (Electron) release w/o root access

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9149]
As discussed here: #7389

> Just one note about packaging, containers, and root: Arch linux build scripts cannot touch root. The build process is, effectively, just a bash script that defines meta-data, build instructions, and packaging instructions. That script is then run with the UID of the user (and in some cases, using fakeroot just for the uid). For this reason, any method that, say, installs to /opt/rstudio-tools is completely dead in the water. This is part of the reason why either that location must be variable at build-time (so that we can specify that directory to be one within the scope of the build directories defined by the PKGBUILD file), or to tweak the scripts (terrible to do, since we have to patch downstream), or to use system-libs (preferable, because it's considerably cheaper, and easy to just link where things need to be). I believe the Rstudio team in the past has accommodated these needs by allowing for system-libs to be used, rather than bundling [for Qt, and for Soci]; and we intervene in the dependency installation by instead soft-linking to system libs (e.g., for pandoc) or downloading them ourselves (e.g., gwt) [/opt/rstudio-tools cannot be used; so we've had to manually intervene to fix that].
> 
> All this to say - Preferably, the build system can be /self-contained/, and not stomp on anything outside the build directories because it's against policy and best-practices to do so. Building a package /shouldnt/ require modifying root in untrackable ways; we would greatly appreciate any effort to avoid that, especially with regard to electron.

**Comment by kevinushey** [comment]
The directory used for RStudio's bundled dependencies can be configured with CMake, using e.g.

```
cmake -DRSTUDIO_TOOLS_ROOT=/path/to/tools
```

And Electron itself gets installed into a local `node_modules` folder in the regular case.

Does that get us far enough to have this issue be considered resolved?

**Comment by gtritchie** [comment]
> Does that get us far enough to have this issue be considered resolved?

I think it does. Closing!
