### ISSUE TITLE
file upload can fail if unzip utility is not available on PATH

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9151]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.dev
    OS Version      : macOS 11.2.3
    R Version       : 4.0.4

### Steps to reproduce the problem

On a machine without the `unzip` utility installed, try to upload a `.zip` file.

### Describe the problem in detail

The upload fails, with the following nebulous error in the logs:

> 28 Feb 2021 16:53:10 [rserver-monitor] ERROR 28 Feb 2021 16:53:10 [rsession-kevin] ERROR system error 127 (Key has expired) [description: Unexpected result for unzip command]; OCCURRED AT rstudio::core::Error rstudio::session::modules::files::{anonymous}::detectZipFileOverwrites(const rstudio::core::FilePath&, const rstudio::core::FilePath&, rstudio::core::json::Array*) src/cpp/session/modules/SessionFiles.cpp:695; LOGGED FROM: rstudio::session::modules::files::{anonymous}::handleFileUploadRequestAsync(const rstudio::core::http::Request&, const string&, bool, const UriHandlerFunctionContinuation&)::__lambda2 src/cpp/session/modules/SessionFiles.cpp:867

### Describe the behavior you expected

We should handle this more gracefully. We should either:

1. Provide a better user-facing error message;
2. Improve the error logging (note that the status code 127 is returned by the shell fora command that is not available; the description "Key has expired" is nonsense);
3. Allow `.zip` file uploads to succeed regardless of whether `unzip` is installed.

### Notes

https://github.com/rstudio/rstudio/blob/f70d93b21a88ad5617410f8ecb605450c4ca6de0/src/cpp/session/modules/SessionFiles.cpp#L665-L671

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Yet another option would be to bundle a small statically linked unzip utility and use that if there's not one on `$PATH`.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 1.5.96-2
    OS Version      : ubuntu20
    R Version       : 4.0.2

Verified that zip files upload and are unzipped when unzip is on the PATH. Verified that when unzip is not on the PATH and a zip file upload is attempted, users are presented with a dialog option to upload the zipped version of the file. Also verified the user is presented with a dialog option to overwrite a zip file if one of the same name already exists.

### Notes
- This cannot be automated until we get the Fabric framework up and running, since we need to be able to uninstall the unzip utility and reinstall it on cleanup.
