### ISSUE TITLE
RStudio sessions take minutes to start on slow disks, resulting in timeouts

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9152]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4+

### Steps to reproduce the problem

1. Set up RStudio Server (or RStudio Desktop on a Unix platform) so that user home directories are on a moderately slow disk.
2. Create a lot of content (say, 10,000 random files) in the `~/.local/share/rstudio` folder. Many users have accumulated lots of content in this folder, but for the purposes of the reproducing the bug it doesn't matter what the content actually is, only that there are many individual files. 
3. Start several RStudio sessions. 

### Describe the problem in detail

The sessions take several minutes to start, and the browser reports "Unable to connect to service" instead of loading them. 

### Describe the behavior you expected

Sessions should start and load quickly. 

This is a regression from 1.3 and appears to be at the source of a number of internal support tickets related to connectivity issues at session startup after upgrading to 1.4 (57485 and 57728, to name a few). 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
The core problem from analyzing traces from aforementioned tickets appears to be that R sessions call `chown()` thousands of times (almost 9000 in one trace) at startup, consuming a huge amount of time and overwhelming the disk. 

This happens because we have some new logic in 1.4 that attempts to ascertain whether users' state folders are writeable, and attempts to recursively `chown()` their entire RStudio state folder if they aren't.

https://github.com/rstudio/rstudio/blob/f70d93b21a88ad5617410f8ecb605450c4ca6de0/src/cpp/core/system/Xdg.cpp#L231-L247

However, `testWritePermissions` works by actually trying to open the directory in a binary write mode.

https://github.com/rstudio/rstudio/blob/f70d93b21a88ad5617410f8ecb605450c4ca6de0/src/cpp/shared_core/FilePath.cpp#L1596-L1597

It is not possible to write binary data to directories, so this fails. The session concludes that the directory is not writable and proceeds to recursively `chown()` the entire tree, resulting in the dramatic startup delay observed above.

**Comment by astayleraz** [comment]
Darby and I verified in version 1.4.1658-1that we were able to start multiple r sessions with no issues or errors when using a slow EFS disk. Closing issue.
