### ISSUE TITLE
Feature request: Case insensitive history search

### ISSUE THREAD

**Issue by IndigoJay** [rstudio/rstudio#9160]
The history search tool is convenient. The search is case sensitive, which is good for searching for code and function names, but when looking for variables, I don't remember the exact case, and have no or incomplete results. 

This feature request is for a "Match Case" checkbox to be added to the history pane's bar (similar to the 'find' tools 'match case' option in the source view).

**Comment by ronblum** [comment]
@IndigoJay Thank you for the suggestion! We'll consider it as we continue to develop and improve RStudio.
