### ISSUE TITLE
Please add a cmake variable to use external pandoc

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#9163]
```pandoc``` package is available on FreeBSD and many other systems: https://repology.org/project/haskell:pandoc/versions

```RStudio``` through this and other lines https://github.com/rstudio/rstudio/blob/master/src/cpp/session/CMakeLists.txt#L582 builds and installs pandoc.

These places have to be patched out in the FreeBSD port.

Looking forward it's best to have a cmake option, for example ```USE_EXTERNAL_PANDOC``` that would instruct RStudio to use external pandoc.

**Comment by JanMarvin** [comment]
You could simply create a pandoc folder and link the system pandoc into the build directory. Been doing this on Arch since forever. This way patching cmake can be avoided.

https://github.com/JanMarvin/rstudio-archlinuxpkg/blob/a0f359b13cd9b8194dc117bb23cbb2ae2e51ed1b/rstudio/PKGBUILD#L92-L100
