### ISSUE TITLE
No "Add Column" and "Remove Column" icons are not shown in "Options Global - Pane Layout"

### ISSUE THREAD

**Issue by calote** [rstudio/rstudio#9165]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1652
    OS Version      : MacOS Big Sur
    R Version       : 4.0.3

### Steps to reproduce the problem

Open "Options Global" and select "Pane Layout".

### Describe the problem in detail

The option to add new source code columns does not appear.

### Describe the behavior you expected

Two icons should appear: "Add Column" and "Remove Column".
<img width="596" alt="RStudioNoApareceAddColumnSource_27mar2021" src="https://user-images.githubusercontent.com/4060891/112719865-8e48c000-8efb-11eb-81ac-17e578659c0c.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@calote Thank you for raising this, for us to review! I can reproduce this in:
- RStudio Desktop 1.4.1606 and 1.4.1650 on MacOS 11.3
- RStudio Server 1.4.1653 on Ubuntu 20.04 using Chrome on MacOS 11.3

Note that this was working in RStudio Desktop 1.4.1572 on MacOS 11.3.

**Comment by gtritchie** [comment]
I'll take a look.

**Comment by gtritchie** [comment]
Note to self: First happens with build 1.4.1576 - b3928c76, 2021-02-16

**Comment by jmcphers** [comment]
@gtritchie Urgh, that's mine. LMK if you want me to take this one.

**Comment by gtritchie** [comment]
@jmcphers Sure would appreciate if you take this one. Assigning to you.

**Comment by calote** [comment]
With build 1.4.1660, the toolbar with the buttons for new columns does appear.
<img width="590" alt="Captura de pantalla 2021-04-01 a las 11 07 34" src="https://user-images.githubusercontent.com/4060891/113271615-025bdd00-92db-11eb-9d25-7678cfae029a.png">

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1660, R Version - 4.0.4, Windows 10 - Desktop 

The Add and Remove Column buttons are again appearing (and functioning) as expected in the latest daily build.
