### ISSUE TITLE
Changing Shortcut of "Delete" causes strange behaviour

### ISSUE THREAD

**Issue by martin-borkovec** [rstudio/rstudio#9168]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : Win 10 64bit
    R Version       : 4.0.3

### Steps to reproduce the problem

Go to "Modify Keyboard Shortcuts..." and set [Name] Delete to [Shortcut] "Shift+Delete"

### Describe the problem in detail
Open a script and type: 
``` r
x1 <-  1:5
```
 (Two spaces between the assignment operator and 1:5)

Set the cursor inbetween the two spaces, press delete and rstudio will copy paste everything right of the cursor to the next line, as seen here:
``` r
x1 <- 1:5
 1:5
``` 

### Describe the behavior you expected

When changing the Keyboard Shortcut for Delete I would either expect pressing the button Delete to do nothing at all or work as normal. 
Changing the Keyboard Shortcut of Delete to "Shift+Delete" I expect to no longer cut on pressing "Shift+Delete". (which works as expected.)

Additional problem: I couldn't figure out how to reset only the "Delete" shortcut, since Delete alone will not be accepted as a shortcut. Therefore, afaik you have to reset all shortcuts, if you come in this situation. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@martin-borkovec Thank you for raising this issue! We'll review it as a we continue development of RStudio. Two things that would be helpful:
1) What happens with the <kbd>Delete</kbd> key if you change the keyboard shortcut to something using a normal character instead, such as <kbd>Ctrl-R</kbd>?  
2) Can you file a bug report for the second issue you describe, that a shortcut can't be updated to just use <kbd>Delete</kbd>? Thanks!

**Comment by martin-borkovec** [comment]
thanks for this great piece of software! happy to help.

ad 1. it's the same. the assigned shortcut (ctrl+R) works as it should (deletes) and the delete key mostly also deletes, except in a situation like described above. 

ad 2. will do.
