### ISSUE TITLE
shortcut for delete cannot be reset without resetting all shortcuts

### ISSUE THREAD

**Issue by martin-borkovec** [rstudio/rstudio#9170]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      :  Win 10 64bit
    R Version       :  4.0.3

### Steps to reproduce the problem

Go to "Modify Keyboard Shortcuts..." and set [Name] Delete (defaults to [Shortcut] "Delete") to a new shortcut.

### Describe the problem in detail
As far as I can tell, there is no way to reset  [Name] "Delete" to [Shortcut] "Delete", other than resetting all shortcuts (which might cause some trouble).
Resetting the shortcut might be necessary because of a problem I described here: https://github.com/rstudio/rstudio/issues/9168

### Describe the behavior you expected
I'm not sure what to expect, since pressing the delete key probably still should delete the entry of the shortcut field. Maybe an option to reset keys individually would be a solution.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@martin-borkovec Thank you for transferring this over from #9168! 

Reproducible on:
- RStudio Desktop 1.4.1655 on Windows 10
- RStudio Server 1.4.1655 on Red Hat 8.3 using Chrome on Windows 10
