### ISSUE TITLE
Issue with RStudio user authentication cookies

### ISSUE THREAD

**Issue by tsaastam** [rstudio/rstudio#9175]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1106
    OS Version      : Ubuntu 20.04.1 LTS
    R Version       : 4.0.4

### Describe the problem in detail

There seems to be an issue with cookie-based user authentication in RStudio.

a) What I did: I ran RStudio in a Docker container on a local machine, logged in, obtained authentication cookies (so, for a while at least, I don't need to log in again).

b) What happened: However, I was then able to use these cookies to bypass the authentication on a different RStudio instance, which had a different password.

### Describe the behavior you expected

c) That probably shouldn't happen.

### Steps to reproduce the problem

1) Clear any cookies you may have in your browser which originate from `localhost`.

2) Run the RStudio Docker container: `docker run -it --rm --name=rstudio1 -p 8787:8787 -e USER=user -e PASSWORD=pass123 rocker/rstudio:4.0.4`.

3) Navigate to http://localhost:8787 in your browser. You should see a login page; use the username & password from the previous step to log in.

4) You should now be in RStudio, as normal. Check that everything works as expected. Then kill the Docker container with e.g. `docker kill rstudio1`.

5) Start a different RStudio Docker container: `docker run -it --rm --name=rstudio2 -p 8686:8787 -e USER=user -e PASSWORD=pass456 rocker/rstudio:4.0.4` - note that the username here is the same, but the password etc are different.

6) Navigate to http://localhost:8686 using the same browser as before (don't clear the cookies in between).

7) RStudio will log you in as `user` automatically, despite the different password, and despite the fact that this is a completely different RStudio instance.

A different thing happens when one modifies the username in step 5:

5b) Start a different RStudio Docker container: `docker run -it --rm --name=rstudio2 -p 8686:8787 -e USER=user2 -e PASSWORD=pass456 rocker/rstudio:4.0.4` - note that the username here is now different as well.

6b) Navigate to http://localhost:8686 using the same browser as before (don't clear the cookies in between).

7b) RStudio will get stuck in a loop, with the following being spammed in the Docker output:

    31 Mar 2021 11:59:23 [rserver] ERROR system error 2 (No such file or directory) [description: User not found., user-value: user];
    OCCURRED AT rstudio::core::Error rstudio::core::system::User::Impl::populateUser(rstudio::core::system::User::Impl::GetPasswdFunc<T>&, T)
    [with T = const char*  rstudio::core::system::User::Impl::GetPasswdFunc<T> = std::function<int(const char*,
    passwd*, char*, long unsigned int, passwd**)>] src/cpp/shared_core/system/User.cpp:68; LOGGED FROM:
    bool rstudio::server::auth::validateUser(const string&, const string&, unsigned int, bool)
    src/cpp/server/auth/ServerValidateUser.cpp:52

This looks like RStudio is trying to automatically log in `user`, based on the cookies, but this is failing since we have specified `user2` in the environment variable and therefore `user` does not exist in the currently running RStudio.

My question is: what is going on with the authentication? Surely cookies from one RStudio instance should not be valid for logging into another, completely different RStudio instance?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [N/A] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tsaastam Thank you for raising this issue! I'll mark it for review as we develop RStudio.

**Comment by tsaastam** [comment]
@hsintonen tells me that there's a configuration file which seems related to cookie authentication called `secure-cookie-key`. In these Docker images one can check it as follows:

    cat /var/lib/rstudio-server/secure-cookie-key ; echo

And indeed when you run two copies of the `rocker/rstudio:4.0.4` Docker image, the contents of the above file are identical in both.

Perhaps this issue is due to how the `rocker/rstudio:4.0.4` image is set up initially? I tried digging into its initialisation scripts briefly but did not get very far. If one were to generate the above file randomly when the image is run (not when it's constructed), perhaps that would solve or at least mitigate the issue.

**Comment by jmcphers** [comment]
> And indeed when you run two copies of the rocker/rstudio:4.0.4 Docker image, the contents of the above file are identical in both.

Yes, that's why you are seeing this behavior. If you want to run two different RStudio Server instances on the same hostname, they need to have different cookie keys.

By default RStudio Server generates a unique cookie key when it is started, if such a file doesn't already exist, so the fact that you have two instances with the same key suggests that the key is baked into the image. Removing the key from the image should address the issue. 

https://github.com/rstudio/rstudio/blob/fef6fd2b1364e95fbdd7d6e1619812cad4c0c984/src/cpp/server_core/SecureKeyFile.cpp#L30-L96

**Comment by cboettig** [comment]
Thanks @jmcphers .  I help maintain that docker image, but we are doing a relatively vanilla install using this script: https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_rstudio.sh.  Any ideas where this key is being created?

**Comment by jmcphers** [comment]
Yes, it's happening right here:

https://github.com/rocker-org/rocker-versioned2/blob/fec4bc683b2d9ece6425833d4a288bbfd2919281/scripts/install_rstudio.sh#L95

RStudio creates the key when it starts, so starting the server during install is causing the key to be created. Since you stop the server afterwards, you could just clean up the key so a fresh (unique) one will be created on next startup.

**Comment by cboettig** [comment]
Thanks @jmcphers , but I don't quite follow.  I believe those lines are just quoted and being echoed into the run command,  right?

https://github.com/rocker-org/rocker-versioned2/blob/fec4bc683b2d9ece6425833d4a288bbfd2919281/scripts/install_rstudio.sh#L92-L96

container build does not call `rserver`, that does not happen until the user calls `docker run`.  hmm... maybe the quoting isn't working?  (I do indeed see the file is already there,

    docker run --rm -ti rocker/rstudio:4.0.4 ls /var/lib/rstudio-server

but I believe the line you link is merely echoed into the init script as evidenced by

    docker run --rm -ti rocker/rstudio:4.0.4 cat /etc/services.d/rstudio/run
    
and not being run until `init` is called by the container default command.  What am I missing?

**Comment by cboettig** [comment]
@jmcphers Just following up here.  

I can confirm that the file `/var/lib/rstudio-server/secure-cookie-key` first appears after running the line installing the .deb file, 
https://github.com/rocker-org/rocker-versioned2/blob/e09ead9d39efdc8ec00d94a3ac29a09308d50d27/scripts/install_rstudio.sh#L67

No idea why that should be but does not seem to suggest our configuration file is the issue?  As Dirk points out, it doesn't appear to be in the .deb (https://github.com/rocker-org/rocker-versioned2/issues/137#issuecomment-819681837) so not sure where it is coming from. Thanks for the help.

**Comment by cboettig** [comment]
@jmcphers Apologies for the noise, but as far as I can tell, this file is being created by the standard RStudio install step.  It is not being caused by line https://github.com/rocker-org/rocker-versioned2/blob/fec4bc683b2d9ece6425833d4a288bbfd2919281/scripts/install_rstudio.sh#L95 which calls `echo`.  Would you prefer we open a fresh issue for this?

**Comment by kevinushey** [comment]
If it's happening during package install, then the most likely explanation is that something in our post-install script is tripping that code. This all lives here:

https://github.com/rstudio/rstudio/blob/main/package/linux/debian-control/postinst.in

and that does indeed include code to restart the server automatically; e.g.

https://github.com/rstudio/rstudio/blob/47108c2d96cbc87c5d3e558cd7eea0c492bc6b92/package/linux/debian-control/postinst.in#L91-L108

so perhaps that is the "real" culprit?
