### ISSUE TITLE
Spurious RStudio-generated normalizePath warnings

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#9177]
While working in the rstudio console sporadically (typically close to a session start) I get multiple warnings like:
```
Warning message:
In normalizePath(dirname(f)) : path[1]="NA": No such file or directory
```
Setting `debug(normalizePath)` did catch them a few times, but showed no R-stack - so I assume it is rstudio internal.

Any insights/workarounds/ways to check what's going on would be appreciated.

### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 18.04.5 LTS
    R Version       :  3.4  / 4.0.4 (observed on both)

### Steps to reproduce the problem
Unknown

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Next time it occurs, you could try getting a GDB stack trace from the `rsession` process to get some better hints at what code we might be executing.

**Comment by OfekShilon** [comment]
@kevinushey  sure, will try.

**Comment by edaustin** [comment]
Identical issue. invariably when R starts, and during the session, exactly the same versioning as the previous contributor, same OS, R and RStudio versions. Will try and get a stack trace!

**Comment by kevinushey** [comment]
Thanks! For what it's worth, the approach I typically use is something like:

1. Use `debug(normalizePath)` in R, and then get the R interpreter to stop next time `normalizePath()` is called in a case where the error is triggered,
2. Attach GDB / LLDB to the rsession process, and print the C stack trace via `bt`.

**Comment by OfekShilon** [comment]
After trying for a long while, I'm afraid I can say this doesn't reproduce with a breakpoint in `normalizePath`.  It *is* called, but the path=NA error does not occur.
Below are two screenshots of typical stacks, perhaps they can help focus the search.
![image](https://user-images.githubusercontent.com/73080/117259166-751a2400-ae56-11eb-9228-2efc1e099565.png)
![image](https://user-images.githubusercontent.com/73080/117258987-4308c200-ae56-11eb-8c91-28a491b466ba.png)

**Comment by OfekShilon** [comment]
I also tried
```r
f <- function() { if (is.na(parent.frame()$path[1])) traceback() }
trace(normalizePath, f )
```
And the mere tracing stopped the warnings.
