### ISSUE TITLE
Open saved files automatically picks up changes made to them externally

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9178]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.3.1093, 1.4.1653
    OS Version      : MacOS 11.3, Ubuntu 20.04 using Chrome on MacOS 11.3
    R Version       : 4.0.4

### Steps to reproduce the problem

1. Open a new R script file in RStudio.
2. Add `x = 1` to the file.
3. Save the file.
4. Change the contents to `x = 2` but don't save the file.
5. Use an external editor to edit the file, e.g. vi in a terminal.
    - Note that the file still says `x = 1` as expected.
6. Using the external editor, change the contents to `x = 3`.
8. Save and close the file in the external editor.
9. Switch to RStudio and click in the source pane.
    - A message pops up stating that the file changed.
10. Choose "Yes" to load the updated version.
    - The contents in the source pane switches from `x = 2` to `x = 3`.
11. Change the contents to `x = 4`.
12. Save the file.
5. Open the file again using an external editor.
    - The file says `x = 4` as expected.
6. Using the external editor, change the contents to `x = 5`.
8. Save and close the file in the external editor.
9. Switch to RStudio and click in the source pane.
    - No message pops up stating that the file changed.
    - The contents in the source pane switches from `x = 4` to `x = 5`.

### Describe the problem in detail

If a file is open and saved, then edited externally, the file in the IDE changes without warning.

### Describe the behavior you expected

RStudio should warn the user that the file has been updated and allow the user to not load the changes.  Compare this to what happens if the file has been edited but unsaved in the IDE, or similarly if the open file has been deleted under the seams.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
> If a file is open and saved, then edited externally, the file in the IDE changes without warning.

This is intentional. Some people like to keep RStudio open for easy access to its tools but do heavier editing tasks in external editors. It'd drive them nuts if we emitted popups all the time. We could probably make it an option ("warn before synchronizing external edits?"), but I think you'll find that most editors behave this way (i.e. they only warn if synchronizing edits will cause unsaved changes to be discarded).

**Comment by ronblum** [comment]
Sounds good. And if this is ever done unintentionally, undoing with <kbd>Ctrl-Z</kbd>/<kbd>Cmd-Z</kbd> will take care of it. 

[Admittedly, I was trying to be rude to myself, but it sounds like my attempt at self-sabotage instead replicates commonly intentional behavior.]
