### ISSUE TITLE
Inconsistent Class Type for R Studio Preference `font_size_points`

### ISSUE THREAD

**Issue by elmstedt** [rstudio/rstudio#9179]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.953
    OS Version      : Windows 10 v.1909 Build: 18363.1440
    R Version       : 4.0.3

### Steps to reproduce the problem
1.  `Tools > Global Options > Appearance > Font Size: 10`
```
class(rstudioapi::readRStudioPreference("font_size_points", FALSE))
# [1] "numeric"
```
2.  `Tools > Global Options > Appearance > Font Size: 12`
```
class(rstudioapi::readRStudioPreference("font_size_points", FALSE))
# [1] "integer"
```
### Describe the problem in detail
Attempting to programmatically set the IDE font size
```
rstudioapi::writeRStudioPreference("font_size_points", font_size_var)
```
can result in one of two possible errors, depending on the current classes of the preference and the value to be set
```
Error in .rs.writePrefInternal("rs_writeUserPref", prefName, value) :
  Type mismatch: expected <Real>; got <Integer>
```
or 
```
Error in .rs.writePrefInternal("rs_writeUserPref", prefName, value) :
  Type mismatch: expected <Integer>; got <Real>
```
### Describe the behavior you expected
I expect the `font_size_points` user preference to consistently be a numeric or integer class object.

### Current work-around
This can be considered a low-priority issue as (for this particular use-case) there is an easy, available solution.

It is possible to sidestep this issue by reading the current preference to determine its class and casting the new value to that before attempting to set the user preference.
```
fsp <- rstudioapi::readRStudioPreference("font_size_points", FALSE)
fsp_sm <- as(Sys.getenv("RS_FONT_SIZE_SM", "10"), class(fsp))
```

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@elmstedt Thank you for raising the issue. I tried everything from 7 to 36, and it looks like 10 is the only value that's treated as numeric—the rest are integers. I'll mark this for review as we continue development of RStudio. And in the meantime, I'm glad to hear you've figured out a workaround!

Reproduced in
- RStudio Desktop 1.4.1660 on MacOS 11.3
- RStudio Server 1.4.1668 on Red Hat 8.3 via Safari on MacOS 11.3
