### ISSUE TITLE
Export PDF Size Wrong

### ISSUE THREAD

**Issue by dipterix** [rstudio/rstudio#9185]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1106
    OS Version      :  OSX Catalina
    R Version       :  4.0.3

### Steps to reproduce the problem

Export any image in PDF format: `plots` panel > `Save as PDF`

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/8163576/113549576-4985ee80-95b7-11eb-801a-95ef8caead81.png)

The default height and width are reversed by default. Should be `5.26 x 7.85` instead of `7.85 x 5.26`. The exported figures are in landscape mode, but portrait canvas with height > width (should be landscape canvas too).

**Comment by ronblum** [comment]
@dipterix Thank you for raising this! However, I'm not sure I'm reproducing this properly. Can you provide sample code with the plot that you're describing? Thanks!

**Comment by dipterix** [comment]
Sure @ronblum , 

Let plot a horizontal figure
```r
x <- seq(0,10,by = 0.01)
plot(x, sin(x))
```
It looks like this 
![image](https://user-images.githubusercontent.com/8163576/114289796-546dd280-9a40-11eb-8152-f8c906bceb78.png)


Go to `plots` panel, export PDF. Do not set anything (accept default settings)
![image](https://user-images.githubusercontent.com/8163576/114289808-68b1cf80-9a40-11eb-9db0-a68e43147c54.png)

Here's the result
![image](https://user-images.githubusercontent.com/8163576/114289821-8f700600-9a40-11eb-919c-ece4d9bc7121.png)

**Comment by dipterix** [comment]
@ronblum Any updates?

**Comment by ronblum** [comment]
@dipterix Ah! I can reproduce this if I set the orientation to Landscape. What happens with Portrait?

**Comment by dipterix** [comment]
Thanks @ronblum The Portrait looks like "horizontal", which produces correct desired result (as-is like in the rstudio viewer). However, isn't it suppose to be default?

**Comment by ronblum** [comment]
@dipterix I'll make a note to check what the default is, but once you set the orientation, it'll stick in future PDFs previews and save. But it looks like they might've gotten reversed! I'll investigate further.

**Comment by dipterix** [comment]
Yeah. I think if you export png files, the orientation is correct, but not for PDFs. Also even though with the option remembered within a session, but when I close the RStudio and re-open it again, the settings are reset to Landscape. Therefore it might be great if the default is consistent with the plot viewer in RStudio.

Thanks!

**Comment by timtmok** [comment]
Looks like a straightforward fix. It seems that the portrait orientation is treated as the default for the given width and height. I think it's widely considered that monitors are landscape by default so selecting that makes the plot exporter swap the width and height.

I think it makes sense to swap the device size values. This would definitely make more sense and match the 4x6, 5x7, 6x8 settings that are also expected to be landscape by default. I'll also check rotated displays so that it still makes sense for portrait displays.

**Comment by dipterix** [comment]
Yes, exactly. Thanks for considering the fix.

**Comment by timtmok** [comment]
So I've tested what happens with a rotated display and it works by treating the specified size as height x width. This will match the paper and photo size options. Much more intuitive now and it will export to PDF what is shown in the plots panel.

I'll put up a PR for this change shortly.

**Comment by timtmok** [comment]
Hmmm.. on second thought, this might be better if landscape set the dimensions where the long end is the width and the short end is the height. Then flipping it for portrait. I think the confusion is that the plots pane considers the orientation to be portrait even if the dimensions have the long end as the width.

I think the assumption is that portrait will always create a PDF where the plot has a width shorter than the height. Landscape would be expected to have the width longer than the height. Ignoring the order of the dimensions, I think it makes most sense for the device size option to size the plot as specified in the orientation option. The other paper and photo sizes will remain the same as how we normally interpret portrait/landscape.

**Comment by jgutman** [comment]
Verified in RStudio Desktop 2022.06.0-daily+36 with Mac OS 12.1 (R 4.1.2) with devices of different dimensions/orientations. 

Also verified in RStudio Desktop 2022.06.0-daily+36 with Windows 11 Enterprise (R 4.1.2)

**Comment by jgutman** [comment]
I wonder if the dimensions displayed in the PDF Size export pane should be flipped when switching between portrait and landscape? For example, whether you choose Device Size, or a fixed size like US letter, the dimensions do not reorder when changing the orientation. So if I have my device set to 7 inches tall and 4 inches wide, and I choose Export > Save as PDF, it will say (Device size) 4 x 7 inches. If I choose Portrait orientation, then I will get a PDF that is 7 inches tall and 4 inches wide. If I choose Landscape orientation, then I will get a PDF that is 4 inches tall and 7 inches wide. 

If I resize my device to be 7 inches wide and 4 inches tall, then the export pane will say (Device size) 7 x 4 inches, and whether I choose portrait or landscape, my PDF dimensions will be the same as they were when my device size was 4 x 7, and I selected the corresponding option. I think the produced dimensions of the output make perfect sense, I only wonder if how we display the dimensions in the PDF size boxes, as to which number comes first and which number comes second should reflect the dimensions and whether I've chosen portrait or landscape. 

Similarly, if I've chosen US letter, then I might expect it to display as 8.5 x 11 if I have Portrait selected, but to display as 11 x 8.5 if I have Landscape selected.
