### ISSUE TITLE
Realtime spelling decorations in Visual Mode will sometimes clear improperly

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#9187]
### System details

    RStudio Edition : Desktop or Server 
    RStudio Version : 1.4
    OS Version      :  Any
    R Version       : Any

### Steps to reproduce the problem

1. Type a misspelled word
2. Hit spacebar and see the underline show up
3. Hit backspace and notice it disappear

### Describe the problem in detail

The logic behind clearing decorations is overly aggressive. This is also affecting the removal of Typo.js logic with how it does the initial focus decoration addition. 

### Describe the behavior you expected

Misspelled words are always underlined.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@adamconroy does this need to be done along with the removal of typo.js?

**Comment by adamconroy** [comment]
Fixed in commit: https://github.com/rstudio/rstudio/commit/cee6c3e8181d3020b5a2eed8d1e1562caad9e8c5

This was as trivial a commit as possible so I just pushed it.

**Comment by rich-rstudio** [comment]
verified on MacOS desktop 1.4.1696
