### ISSUE TITLE
terminal should place configured version of Python on the PATH

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9188]
Chatting with @jjallaire: If the user has configured a global / project version of Python for RStudio, that version of Python should be placed on the PATH.

**Comment by kevinushey** [comment]
It looks like getting this right is a bit more challenging than it looks like at first glance. When launched as a login shell, bash (and presumedly, other shells) take the inherited path, but push other relevant path entries in front as appropriate. For example:

```
$ PATH=__INHERITED_PATH__ /bin/bash --login --norc -c 'echo $PATH | tr ":" "\n"'
/Users/kevinushey/.yarn/bin
/Users/kevinushey/.config/yarn/global/node_modules/.bin
/usr/local/bin
/Library/TeX/texbin
/usr/local/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/TeX/texbin
/usr/local/share/dotnet
/opt/X11/bin
~/.dotnet/tools
/Library/Apple/usr/bin
__INHERITED_PATH__
```

Note that `__INHERITED_PATH__` is stuck at the bottom. Ultimately, this implies that we need to find a way to run our own custom code (modifying the PATH) after the shell has processed any login-related startup scripts.

**Comment by ronblum** [comment]
This works as expected in RStudio Server 1.4.1692. However, in RStudio Desktop on MacOS 11.3, when opening a new terminal, the following also happens:

1. Set the Python interpreter (global or project—I don't think it matters).
2. `Terminal`
3. `echo $PATH`
    - Python's parent directory is at the start of the path.
4. Change Python interpreter.
5. In the same terminal as before, `echo $PATH`
    - The new interpreter's parent directory is at the start of the path.
    - A different interpreter's parent directory is second to last in the path, right before RStudio's .../postback directory.
6. Open a new terminal
7. `echo $PATH`
    - The path is now correct.

**Comment by mikebessuille** [comment]
Moving this ticket back to "verifying" - I think it's now been verified?

**Comment by elbamos** [comment]
Hope this is helpful and not counterproductive -- if the user's chosen python is a conda or virtualenv environment, shouldn't the correct behavior be to call the appropriate `activate` script rather than adjusting the `PATH` directly?  My concern is that the path-editing is going to interfere with whatever path editing is taking place in the user's startup script; or some greater confusion will occur if the user tries to change their active python environment from the terminal.

**Comment by kevinushey** [comment]
@elbamos that's a good point; I think you're right. (Note that we already do the gymnastics necessary to ensure the user's startup profile scripts, if any, are properly sourced -- and we only then update the PATH afterwards, to ensure that the user's profile scripts don't stomp on our changes)

**Comment by ronblum** [comment]
@kevinushey I moved this back to "in progress" because it sounds like we want to take the approach above instead? Or else, kick it back to me.

**Comment by ronblum** [comment]
This works eminently, including in RStudio Desktop 1.4.1707 on Red Hat 8.3.
