### ISSUE TITLE
Unit tests failing on official Mac build machine

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9190]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4 (master as of 2021/04/05)
    OS Version      : macOS build machine
    R Version       : any

### Steps to reproduce the problem
Look at Mac build results from official builder. Marked as unstable.

### Describe the problem in detail
It looks like the tests are failing due to being unable to fine libpq.5.dylib

### Describe the behavior you expected
No failures for unit tests.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Unit tests are now running _and_ passing on CI. Joy!

https://build.rstudioservices.com/blue/organizations/jenkins/IDE%2Fmacos-v1.4/detail/macos-v1.4/1215/pipeline/44
