### ISSUE TITLE
Rstudio with google-drive-ocamlfuse is too slow

### ISSUE THREAD

**Issue by ByungjunKim** [rstudio/rstudio#9191]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.1114
    OS Version      :  Ubuntu 20.04
    R Version       :  4.0.5

### Steps to reproduce the problem
I used google-drive-ocamlfuse(https://github.com/astrada/google-drive-ocamlfuse) which is google drive's cli edition.
Whenever I run the codes with Rstudio on google-drive-ocamlfuse's folder, it is too slow to respond.

### Describe the problem in detail
It is too slow to save and run code, so I transfer the R file on google-drive-ocamlfuse's folder to normal folder.
On the normal folder, it was fast.

### Describe the behavior you expected
On google-drive-ocamlfuse's folder, Rstudio's reaction speed needs to improve.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ByungjunKim Thank you for raising this issue! We've seen other issues with local vs. network file systems, which we've tried to address. We'll review this as we continue development of RStudio.
