### ISSUE TITLE
JUnit missing from NOTICE

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#9192]
The NOTICE file should contain all the used licenses of RStudio, but the file appears to be missing JUnit, which is included in the source tree in [`./src/gwt/lib/junit-4.9b3.jar`](https://github.com/rstudio/rstudio/blob/master/src/gwt/lib/junit-4.9b3.jar). If my research is correct, then JUnit 4 uses the Eclipse Public license 1.0, which should be probably added as well?

**Comment by jmcphers** [comment]
Thanks for spotting this! NOTICE refers specifically to open source components that are bundled with RStudio when it is packaged for distribution (i.e. they are part of the runtime). JUnit is only used during development and is not an RStudio component.
