### ISSUE TITLE
redirected to auth-sign-in after valid sign-in

### ISSUE THREAD

**Issue by ras44** [rstudio/rstudio#9193]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu focal
    R Version       : 4.0.3

### Steps to reproduce the problem
Be signed out, then attempt a sign-in with valid credentials.

### Describe the problem in detail
About 80% of the time after being automatically signed out, I attempt a valid sign-in on, RStudio Server looks like it is about to load, but then I am redirected to sign-in again.  I have tried resolving it by hard-reloading the page, visiting on another browser or with a different device (via developers console), and restarting the server: none consistently solve the problem.  At times it seems to resolve itself by just waiting.  I'm sure I'm entering the correct credentials.  I am connecting via a VPN that can at times be slow- I'm unsure if this could be exacerbating the situation.  I wish I could provide details on how reproduce consistently, but after a couple weeks of trying I'm unable to consistently reproduce the issue.  It seems to me like it could possible be related to some kind of timeout or cookie issue, but it's not my area of expertise.

### Describe the behavior you expected
I would expect to provide valid credentials and then be logged in.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
> I am connecting via a VPN that can at times be slow- I'm unsure if this could be exacerbating the situation.

Is there any way to test whether the issue can be reproduced independent of the VPN?

**Comment by ras44** [comment]
Unfortunately, I can only connect to this particular server via their VPN.  I could attempt to set up another instance that's not on a VPN to see if I can replicate.  FYI, I did just speak with another colleague who is running into the same issue.  Thanks for your consideration!

**Comment by ras44** [comment]
Just curious if anyone else is running into this issue.  We've on-boarded a variety of new employees recently and multiple users (all connecting from within a VPN) are running into it; leading to a challenging first UX with RStudio.

**Comment by kevinushey** [comment]
Thus far we still haven't had any other reports of this, unfortunately.

One thing that might be useful: would you be able to collect a HAR so we can have a network trace from the browser as to what's happening when the authentication + redirect happens? See https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting for some instructions.

**Comment by ras44** [comment]
great idea @kevinushey - thanks!

**Comment by mahsoud** [comment]
Found that RStudio Server v1.4.1717; when deployed behind an AWS ALB that terminates SSL has an issue with sign in if since rstudio redirects always to HTTP, thus I am receiving "400 Bad Request: The plain HTTP request was sent to HTTPS port" from load balancer at redirect to /auth-sign-in

is this a separate issue?

**Comment by ras44** [comment]
@mahsoud I'm not receiving a 400 Bad Request error, but I just get redirected back to the sign-in.  It looks like the sign-in screen has a continual refresh loop happening in the background (judging by the network output), and if the sign-in click happens during some unusual condition of that refresh, it will sign in, but then redirect back to the log in prompt.

**Comment by mahsoud** [comment]
Thank you for your response, it clarified well for me.

**Comment by falaki** [comment]
This seems identical to https://github.com/rstudio/rstudio/issues/7319

**Comment by ras44** [comment]
this might have been resolved via the fix described in https://github.com/rstudio/rstudio/issues/7319, however I haven't been able to build and test to confirm
