### ISSUE TITLE
Search for file/dir only works if file/dir has already been accessed 

### ISSUE THREAD

**Issue by louisgrimaldi** [rstudio/rstudio#9194]
### System details

    RStudio Edition : Desktop  - bug also happens on Server
    RStudio Version : 1.2.1335
    OS Version      : Windows 10
    R Version       : 3.6.1

### Steps to reproduce the problem
Open Rstudio
Set working directory to preferred directory
Search for file with the search file tool within that directory. File/Dir won't be found

Then open the file from the files pane.
Now search for file using the search tool, it will be found.

### Describe the problem in detail
I need to open recursively all of my 324 files and directories to have them indexed in the search file/dir tool. 

### Describe the behavior you expected
I shouldn't have to manually open my files for them to be indexed in the search file/dir tool.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
RStudio only indexes files and folders open within the current project. Have you opened the root directory of your project as an RStudio project?
