### ISSUE TITLE
Switching from Visual Markdown Editor to Source Editor deletes html code

### ISSUE THREAD

**Issue by chrismgentry** [rstudio/rstudio#9198]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Windows 10 Enterprise
    R Version       :  4.0.4

### Steps to reproduce the problem
- Create new R Notebook (or R Markdown)
- Switch to Source Editor
- Paste following code:

```
---
title: "R Notebook"
output: html_notebook
---
<details><summary><big>View directions <span style="color: #ff4500"><b>HERE</b></span></big></summary>
A list of <b>directions</b>... 
<blockquote>insert images and text here</blockquote> 
wrap it up.
</details>
<hr></hr>
```

- Preview or knit to html (looks as it should)
- Then switch back and forth from Visual Markdown Editor to Source Editor (`<span></span>` is now lost)

### Describe the problem in detail

Following the description above, when you set the color of HERE using `<span style = color...</span>`, that section of code is lost when moving between the visual and source editor screens. The rest of the html styling (`<big>`,`<b>`) remains after switching.

### Describe the behavior you expected
I would expect all of the html code written to remain when moving between visual and source editor. When switching it also repositions the code. This is less important than completely removing the `<span>` code, however, I don't see a why `<hr></hr>` would become
```
<hr>
</hr>
```
just because of switching between the two editor viewing modes. While I admittedly am not an expert at html, markdown, or r, I have used this same exact code more than a couple dozen times in the past without error. Only moving between the two editors now causes this issue.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@chrismgentry Thank you for raising the issue! Visual mode will sometimes rewrite markdown code using standard Pandoc idioms: https://rstudio.github.io/visual-markdown-editing/#/markdown?id=markdown-output
However, I'll mark this for review of these specific changes.

Also, if you want to avoid the code changing at all, set the markdown mode to `gfm`, so the YAML block at the start is:
```
---
title: "R Notebook"
output: html_notebook
editor_options:
  markdown:
    mode: gfm
---
```

Finally, I made a couple of small changes to your initial post, for the code to show up properly. Can you make sure that the code it looks correct?

**Comment by chrismgentry** [comment]
Thanks so much @ronblum! This is my first ever "bug" post so I'll try to format it better next time. I really appreciate your response, advice, and assistance.

**Comment by ronblum** [comment]
You're welcome! It's pretty easy. If you click to edit the original comment (click on the three dots, then `Edit`), you can get an idea of what I did. But it's basically similar to the markdown you're used to:
For `inline` code, places single ticks `` ` `` around the code, e.g.

```
Before `inline` after
```
will result in:

Before `inline` after

For a block of code, wrap it in three ticks ` ``` `, e.g.

````
```
Line 1
<br>line 2</br>
`Line 3`
Line 4
```
````
results in:

```
Line 1
<br>line 2</br>
`Line 3`
Line 4
```

**Comment by mikebessuille** [comment]
For the workaround, you should use Format -> Raw -> HTML Block for this html block.

**Comment by jjallaire** [comment]
Addressed with https://github.com/rstudio/rstudio/commit/3e76d3e0fed3d0ea4297195974910a1ceca798af

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 2021.12.0-daily+80
    OS Version      : ubuntu20
    R Version       : 4.0.3

Verified that color style from the html span is now preserved when switching into and out of the Visual Markdown Editor mode.
