### ISSUE TITLE
Proxying localhost ports causes absolute paths to fail

### ISSUE THREAD

**Issue by lukedyer-peak** [rstudio/rstudio#9201]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1106
    OS Version      : Ubuntu 20.04.1 LTS (rocker docker image)
    R Version       : 4.0.4

### Steps to reproduce the problem

1. Run a webserver that contains absolute paths in the body of the HTML files.  (For instance `jupyter notebook` will start a jupyter server on `localhost:8888`)
2. Open the webpage `utils::browseURL("http://localhost:8888")`
3. The webpage won't render as the absolute paths haven't been converted to relative paths.

This issue occurs with any service that uses absolute paths instead of relatives one - even services that are set to up understand that they are being proxied by inspecting the headers

### Describe the problem in detail

In the proxying of ports absolute paths are turned to relative paths BUT only for SparkUI.  Also as this isn't done no headers are added to the   This should be done for all responses where absolute paths are detected:

https://github.com/rstudio/rstudio/blob/e4a1c219cbf6c10d9aec41461d80171ab3009bef/src/cpp/server/ServerSessionProxy.cpp#L337-L343

https://github.com/rstudio/rstudio/blob/e4a1c219cbf6c10d9aec41461d80171ab3009bef/src/cpp/server/ServerSessionProxy.cpp#L260-L268

### Describe the behavior you expected

I'd expect a similar implementation to `jupyter-sever-proxy`:

https://github.com/jupyterhub/jupyter-server-proxy/blob/ed9301aa179d02219cbc79b1dafae73f97afcd7e/jupyter_server_proxy/handlers.py#L167-L184

This is either:
 - The proxying to change absolute paths to relative ones
 - The following headers added to the request to say that this request is being proxied: `X-Forwarded-Context`, `X-ProxyContextPath`, `X-Forwarded-Prefix`.  Some applications check these to see where they are being proxied from.  This isn't done where the headers are handled during the proxying:
 https://github.com/rstudio/rstudio/blob/e4a1c219cbf6c10d9aec41461d80171ab3009bef/src/cpp/server/ServerSessionProxy.cpp#L846-L865

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
@lukedyer-peak - Thanks for finding and reporting this issue. 

Just want to make sure I'm reproducing this issue accurately:

On Ubuntu20, RStudio Server version 1.4.1106 -
- While ssh'd into the server, run `jupyter notebook`.
- Open an rstudio server session, and in the console run `utils::browseURL("http://localhost:8888")`.
- Get loaded into a browser tab as seen below:

![jupyter_absolute_path_issue](https://user-images.githubusercontent.com/62304541/114229213-20f64f80-993d-11eb-99e9-c71d8c304e76.PNG)

Is that the issue you're seeing? If so, I can confirm that this same behavior persists in the early builds of our next release Juliet-Rose, and will most likely need to be addressed in a subsequent release.

**Comment by lukedyer-peak** [comment]
Hi @R-Hannibal thanks for the quick reply.  Yes that's a correct workflow to reproduce the issue.  If you then open the developer tools for that website (I'm using chrome) you'll see the following:

The console has lots of 404 errors from the RStudio server
![Screenshot 2021-04-13 at 09 34 14](https://user-images.githubusercontent.com/52414512/114522807-9a42ba80-9c3b-11eb-8815-1d149d64f056.png)

Going to the source the errors become more obvious.
In the HTML page all the paths are absolute.
This means instead of trying access `...com/p/ab5f7c97/static/...`  we're trying to access files at  `...com/static/...` (directly on RStudio instead of on the proxy).
![Screenshot 2021-04-13 at 09 34 47](https://user-images.githubusercontent.com/52414512/114522802-99118d80-9c3b-11eb-8421-8bc4f6eb5ade.png)

I've tried implementing the headers potential solution I had outlined above but still had this issue.

This makes me think that this code that modifies the paths to be relative instead of absolute could be expanded to all requests where absolute paths are used

https://github.com/rstudio/rstudio/blob/e4a1c219cbf6c10d9aec41461d80171ab3009bef/src/cpp/server/ServerSessionProxy.cpp#L337-L343
where the relevant lines in `sendSparkUIResponse` are 
https://github.com/rstudio/rstudio/blob/e4a1c219cbf6c10d9aec41461d80171ab3009bef/src/cpp/server/ServerSessionProxy.cpp#L259-L269

Note that the paths in the `head` would need to change too

If you think that this is a good solution (we can discuss it more) then I'd be interested in writing a PR for this.  My `C++` is a ~tad~ *very* rusty but I'd been keen to give it a go, although I might need some pointers around where the tests and the easiest way to set up the dev environment (I see there is some VS code support).

**Comment by R-Hannibal** [comment]
@lukedyer-peak - thanks so much for the detailed response as well as the offer to help with the PR 😁.

I'll add this issue to our backlog for consideration by our development team, but I'll also note it as one where we already have a proposed fix and see if any of our C++ developers have bandwidth to respond to your fix proposal (if your C++ is rusty my own is decrepit).
