### ISSUE TITLE
can't kill-yank across documents with emacs keybindings

### ISSUE THREAD

**Issue by AltfunsMA** [rstudio/rstudio#9213]
### System details

    RStudio Edition : Server
    RStudio Version :  1.4.1106
    OS Version      : Ubuntu 20.04
    R Version       :  4.0.4

### Steps to reproduce the problem
Activate emacs keybindings, write in one script. Kill text in any way (C-w, C-k, C-u) and attempt to yank (C-y) it in another script, whether brand new or an existing document.

### Describe the problem in detail
Nothing happens. You can only yank inside the script you killed in.

### Describe the behavior you expected
You should be able to kill and yank across scripts as well as within them.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@AltfunsMA Thank you for raising this! I can reproduce the issue in
- RStudio Server 1.4.1106 on Red Hat 8.3 via Chrome on MacOS 11.3
- RStudio Server 1.4.1681 on Ubuntu 20.04 via Firefox on MacOS 11.3

It works correctly, though, in
- RStudio Desktop 1.4.1681 on MacOS 11.3

We'll review this as part of our ongoing development of RStudio.
