### ISSUE TITLE
Auto-complete not usable when entering snippets variables

### ISSUE THREAD

**Issue by avila** [rstudio/rstudio#9214]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1103
    OS Version      : Pop!_OS 20.04 LTS x86_64
    R Version       :  R version 4.0.5 (2021-03-31) -- "Shake and Throw"

### Steps to reproduce the problem

within RStudio's editor 

1) type `lib`
2) press  <kbd>TAB</kbd> to trigger snippet

Then  auto-complete is not accessible while entering the package name. 

### Describe the problem in detail

This, of course applies to all other snippets, but it is more annoying in the simple ones, because it is clearly inferior to a simple auto-complete. For example:

1) type `libr`
2) press  <kbd>TAB</kbd> to trigger auto-complete 

Then auto-complete is still accessible.

This issue was mentioned in #3859, but the current one aims to be more general than that.

### Describe the behavior you expected

The best behaviour would be to have auto-complete accessible even in _longer_ snippets with multiple variables (entries), where first the auto-complete is solved, and then <kbd>TAB</kbd> would move the cursor to the next variable. 

If this behaviour is too complex, maybe it would be possible to have auto-complete  _"triggerable"_ via <kbd>ctrl</kbd>+<kbd>space</kbd> within entering snippets variables. 

### Simple workaround that solves this issue for single-entry snippets 

Auto-complete functionality is accessible after entering the last snippet variable, usually of index `0`.  So 
changing the index of single entry snippets from `1` to `0` solves this issue for such snippets.

#### Example 

with the following snippets, `lib` blocks auto-complete and `req` does not (note the different indices)

```r
snippet lib
	library(${1:package})

snippet req
	require(${0:package}) 
```

### Further suggestions 

Personally, I believe the following suggestions would be also a improvement specially in the `if` snippet because it is very likely that the the _condition_ will refer to an object where auto-complete would be very useful. 

```r
snippet if_default
	if (${1:condition}) {
		${2:code}
	}

snippet if_suggestion
	if (${0:condition}) {
		
	}

snippet fun_suggestion
	${1:name} <- function(${0:variables}) {
		
	}
... and so on ...
```
### summary 

- Just changing the default single entry snippets to use the 0th index would be a easy fix and great improvement IMHO,
- Making more usage of the 0th index in double or multiple-entry snippets could also be an improvement for some users. 
- The actual solution would be having auto-complete always accessible, even if only via ctrl+space when within snippets. 

### "EULA" :)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@avila Thank you for bringing this up! I'll mark this for review, to consider changing the snippets, as we continue to develop RStudio.
