### ISSUE TITLE
Bolding a text string with math text in it behaves differently in source vs. visual editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#9220]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1671
    OS Version      : macOS 11.2.3 
    R Version       : 4.0.4

### Steps to reproduce the problem

Suppose your goal is to get the following text string that involves some plain text and some math text all **bolded**: `text1 $math$ text2` and you're working in a project with canonical mode on.

- Visual editor experience:
  - Write the following in an Rmd document using the visual editor: `text1 $math$ text2`
  - Highlight and bold the text, you'll notice that `text1` and `text2` are bolded but not `$math$` -- I would have expected the entire text string to be bolded, not just the plain text, but I think here my expectation is wrong.
  - Switch to source editor, the underlying code matches what you see `**text1** $math$ **text2**`

- Source editor experience:
  - Write the following in an Rmd document using the source editor: `**text1 $math$ text2**`
  - Hit save, the text gets updated to the following: `**text1** $math$ text2`, so `text2` is no longer bolded -- Given what happens in the visual editor I would have expected the text to at least be the same as the visual editor bolding, i.e. `**text1** $math$ **text2**`.

### Describe the problem in detail

Bolding a text string with math text in it behaves differently in the source and visual editors.

### Describe the behavior you expected

I would have expected `**text1 $math$ text2**` to be updated to `**text1** $math$ **text2**` with canonical mode.

Note that in a project without canonical mode `**text1 $math$ text2**` is considered valid, although if you knit the document you observe that math text is indeed not bolded.

----

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
I think this is because there are different expressions being saved (`**text1** $math$ **text2**` vs `**text1 $math$ text2**`) and pandoc does something different with each. I also believe that we have a constraint in place that math can't be bolded (since that is what pandoc enforces on render) which is why the formatting comes out the way it does when you select the region and bold it. 

Long winded way of saying I don't think we can easily address this.
