### ISSUE TITLE
ioslides_presentation() does not open in viewer pane 

### ISSUE THREAD

**Issue by malcolmbarrett** [rstudio/rstudio#9222]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1106
    OS Version      : macOS
    R Version       : 4.0.4

### Steps to reproduce the problem

 Using `ioslides_presentation()`, knitting presentations does not preview in the viewer pane even when the settings are set as such. I can reproduce this problem by using the default ioslides template and changing the knit settings to preview in the viewer pane. 

### Describe the problem in detail

As above; no other details

### Describe the behavior you expected

I expected the HTML slides to open in the viewer pane like other HTML slides

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This is done intentionally because ioslides doesn't scale or work nicely when embedded in the Viewer pane.

https://github.com/rstudio/rstudio/blob/0899d13386fd5e61ec847cc62a6eb252702a5ebc/src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutput.java#L685-L688

**Comment by malcolmbarrett** [comment]
I see--thanks! I filed an issue over at rmarkdown to document this behavior
