### ISSUE TITLE
arm64 binary reports i386 in shell commands

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9223]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.dev
    OS Version      : macOS 11.2.3 arm64
    R Version       : Any

### Steps to reproduce the problem

Use RStudio with an arm64 binary of R, and then try to execute:

```
Sys.info()[["machine"]]
system("uname -m")
```

### Describe the problem in detail

The following counter-intuitive output is displayed:

```
> Sys.info()[["machine"]]
[1] "arm64"
> system("uname -p")
i386
```

### Describe the behavior you expected

The values here should be congruent.

Note that this issue also implies that RcppParallel cannot be compiled while within RStudio, as per https://github.com/RcppCore/RcppParallel/issues/162.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
We would fix this by changing how the session is launched here:

https://github.com/rstudio/rstudio/blob/9ec82bad34502a68b94af7ac7283528abe248e56/src/cpp/desktop/DesktopSessionLauncher.cpp#L516-L520

In particular, we'd have to run the moral equivalent of `arch -arm64 /path/to/rsession-arm64`.

**Comment by kevinushey** [comment]
Note: validated as working in https://github.com/rstudio/rstudio/pull/9232#issuecomment-819742422, but we may want to do this ourselves in QA (should hopefully be easy to verify on an M1 macOS machine).

**Comment by astayleraz** [comment]
I verified in version 1.4.1681 on an m1 I am now seeing that `system("uname -m")` reports `arm64`. Closing issue.
