### ISSUE TITLE
Add "Use sentence-based line wrapping" as an option when switching to visual editor mode

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#9225]
Currently I see this when switching to visual editor mode:

![image](https://user-images.githubusercontent.com/1825120/114508190-fef61900-9c2b-11eb-9dce-50f1a51eb7b3.png)

Sentence wrapping is not on the list and should be due to its usefulness as outlined [here](https://blog.rstudio.com/2020/09/30/rstudio-v1-4-preview-visual-markdown-editing/), which states that: 

> You can also configure visual mode to write markdown using one sentence per-line, which makes working with markdown files on GitHub much easier (enabling line-based comments for sentences and making diffs more local to the actual text that has changed).

You *can* but most users will be unaware of this awesome feature if they have not yet experienced the joys of sentence-base line wrapping.

**Comment by Robinlovelace** [comment]
Update, having looked at the code I guess it's this file that would need a (I guess minimal) update to fix this, should be a quick fix with big benefits for fans of sentence-based text wrapping. https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/dialogs/VisualModeLineWrappingDialog.java

**Comment by ronblum** [comment]
@Robinlovelace Thank you for the suggestion! I'll mark this for review as part of work on RStudio, specifically the visual markdown editor.

**Comment by jjallaire** [comment]
This dialog isn't really intended to make all of the options available, it's more to prevent aggressive re-writing of column-based files to wrapping (or vice versa). We can't easily detect sentence based vs. line based, so adding sentence based doesn't really fit in the logic of the dialog. We could create a generic dialog that presents every time you open a file, but I think that would be too much.

Hopefully the "Learn more" link does trick in terms of educating people further about sentence-based.

**Comment by Robinlovelace** [comment]
Good point: switching to sentence-based wrapping can lead to pretty big changes.

**Comment by Robinlovelace** [comment]
For anyone hitting this and wanting it to be the default, you can set this on a per document basis:

```
editor_options:
  markdown:
    wrap: sentence
```

**Comment by Robinlovelace** [comment]
Here's a GIF showing how it works: https://twitter.com/robinlovelace/status/1515208580445741059
