### ISSUE TITLE
'Clear all breakpoints' causes an internal error

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#9226]
Working on R-server, clicking 'Clear all breakpoints...' from the 'debug' menu doesn't work, and the rserver emits these errors:
```
rserver[20769]: message repeated 4 times: 
[ ERROR CLIENT EXCEPTION (rsession-ofek): 
;|||com/google/gwt/emul/javaemul/internal/InternalPreconditions.java#430::
checkCriticalNotNull|||com/google/gwt/emul/java/lang/String.java#377::
compareTo|||org/rstudio/studio/client/common/debugging/BreakpointManager.java#866::
compareTo|||org/rstudio/studio/client/common/debugging/BreakpointManager.java#866::
compareTo|||com/google/gwt/emul/java/lang/Comparable.java#30::
compareTo_Ljava_lang_Object__I__devirtual$|||com/google/gwt/emul/java/util/Comparators.java#44::
compare|||com/google/gwt/emul/java/util/TreeMap.java#793::
insert|||com/google/gwt/emul/java/util/TreeMap.java#521::
put|||com/google/gwt/emul/java/util/TreeSet.java#65::
add|||org/rstudio/studio/client/common/debugging/BreakpointManager.java#750::
clearAllBreakpoints|||org/rstudio/studio/clien]

```
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 18.04.5 LTS
    R Version       : 4.0.4

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@OfekShilon Thank you for raising this! I can't reproduce the issue in either RStudio Server 1.4.1106 or RStudio Desktop 1.4.1106, though. I'll mark it as a bug to review as we continue developing the RStudio IDE.
