### ISSUE TITLE
Building source package deletes local files under inst

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9230]
**Steps to reproduce:**
* Make an R package project with vignettes (example to use: https://github.com/david-cortes/MatrixExtra).
* Create a sub-folder `inst/doc` and put some files there (e.g. a PDF or alike).
* Go to the build pane -> More -> Build Source Package.

**Expected behavior:** should include the `inst/` files in the package.

**Actual behavior:** ***deletes*** the local files without warning and does not include them in the source build.

**Setup:** RStudio 1.5.1547.

This is BTW not an issue with R itself since `R CMD build` will not delete local files and will end up including the `inst` folder.

The build pane shows the following before deleting the files:
```
─  checking for empty or unneeded directories
   Removed empty directory ‘MatrixExtra/inst’
```

The same problem occurs also with `Check Package`.

**Comment by kevinushey** [comment]
This is caused by `devtools::build()`. I don't know why it deletes that folder, but that is the cause.
