### ISSUE TITLE
Cursor is dislocated on lines with certain special characters (e.g. Tibetan text, IPA)

### ISSUE THREAD

**Issue by kayaulai** [rstudio/rstudio#9233]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      :  Windows 19041.867
    R Version       : 3.6.1

(However, I have experienced this in many versions of RStudio throughout the years)

### Steps to reproduce the problem

Insert the following in the editor:

tibetan = "སྒྱོགས་རྟགས་ག་པར་ཕྱིན་སོང་།"
IPA = "xwɑ˧˥ ʂu˨˩ ʈʂʅ˨˩ piɑʊ˥ tsai˥˧ nɑɻ˨˩˧"

### Describe the problem in detail

The displayed cursor location should be much farther to the left than it should be.

This is not just problem with composite characters; Tibetan text without composite characters still face the problem.

### Describe the behavior you expected

The cursor should be displayed at the correct place. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kayaulai Thank you for raising this! I can reproduce the issue in
- RStudio Desktop 1.4.1668 on MacOS 11.3
- RStudio Server 1.4.1106 on Red Hat 8.3 using Chrome on MacOS 11.3

We'll review this as we continue to develop RStudio.

Example: note location in which the cursor appears, well past the end of the text:
<img width="362" alt="tibetan" src="https://user-images.githubusercontent.com/31009952/115429922-e2c91d80-a1d1-11eb-8724-35d3eb759689.png">
