### ISSUE TITLE
Function in console not colored at init

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9236]
**Steps to reproduce:**
* Configure RStudio to color function calls in the console.
* Close RStudio and start it again.
* Before anything is executed, but the focus in the console and write some function.

**Expected behavior:** the function should be colored.

**Actual behavior:** the function is not colored until something gets executed.

**Setup:** RStudio 1.4.1547.

**Comment by ronblum** [comment]
@david-cortes Thanks! I can't reproduce this, though, in a number of places and versions. Was this working in most recent release, Wax Begonia 1.4.1106? And is this an issue in Windows or Debian? Thanks!

**Comment by david-cortes** [comment]
Fixed in the latest preview.
