### ISSUE TITLE
Setting for auto-detect indentation requires restart but is not documented

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9238]
**Steps to reproduce:**
* Set the option to auto detect indentation (Tools -> Global Options -> Code).
* Restart RStudio.
* Open some file with a different indentation than the one configured in the global options.
* Tick off the option to auto detect indentation.
* Write something with indentation in the file.

**Expected behavior:** should use the indentation configured in the global options.

**Actual behavior:** will not use the indentation configured in the global options until restarting RStudio.

**Comment by ronblum** [comment]
Thanks @david-cortes ! I'll mark this is as a bug, probably either that the option should take effect immediately (if possible), or that a notification should appear that a restart is required.
