### ISSUE TITLE
Support for iterative version scanning / Integrate conda environments

### ISSUE THREAD

**Issue by Hoeze** [rstudio/rstudio#9239]
Hi, we are happy users of Rstudio Server Pro but we are currently limited to the admin pre-installed R versions.
- This means that we have to switch to our Jupyterhub as soon as we need a project-specific R version.
- Also, it is an unnecessary burden since the developers have to ask admins for installing additional R versions.

**Could you please add some functionality to dynamically add/remove R versions?**

Optimally, the Rstudio Server would scan in a fixed interval (e.g. 30s) for R versions and lets me select from all installed environments like Jupyterhub does:
![image](https://user-images.githubusercontent.com/1200058/115147948-a2489300-a05d-11eb-80c2-92cc44cadd5d.png)

- One possible way to implement this would be to allow running an external command that returns a list of R installations:
`jupyter kernelspec list --json | parse_lang_eq_R | json_to_list`
- Even better would be to directly parse the jupyter kernelspecs

**Comment by ronblum** [comment]
@Hoeze Thank you for the suggestion! Since this is regarding an RStudio Server Pro feature, I'm moving the request over to the (private) pro repo for review. Thanks!

Side note: FWIW, R versions will get picked up by issuing a SIGHUP to RStudio Server: https://docs.rstudio.com/ide/server-pro/r-versions.html#determining-available-versions (section 6.4.1.2).

**Comment by Hoeze** [comment]
Hi @ronblum, are there any updates on this issue?
We're now using rstudio workbench but we still cannot use arbitrary conda environments created by the users.
Unfortunately I cannot see the discussions in your private repo :smile:

**Comment by ronblum** [comment]
@Hoeze Re-looking at this: By default, we look at the directories described at https://docs.rstudio.com/ide/server-pro/r_versions/using_multiple_versions_of_r.html
However, you can specify additional locations in the `/etc/rstudio/r-versions` file, described in the same document section. Does including the location, using the home directory, accomplish what you're looking for?
