### ISSUE TITLE
VIM keybinding to paste from system clipboard doesn't work

### ISSUE THREAD

**Issue by raffaem** [rstudio/rstudio#9241]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1106
    OS Version      :  Ubuntu 20.10
    R Version       :  4.0.5

### Steps to reproduce the problem
In Tools->Global Options->Code->Editing tab ->Keybinding select "VIM"

Go to some application and copy something to the clipboard.

Return to RStudio and we will try to paste.

In VIM, to paste from system clipboard, we can use `"*p` or `"+p`. See [here](https://stackoverflow.com/questions/11489428/how-to-make-vim-paste-from-and-copy-to-systems-clipboard).

None of these keybindings work in RStudio.

### Describe the problem in detail

See above

### Describe the behavior you expected

I would expected the text from the system clipboard to be pasted in the RStudio code editor.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@raffaem Thank you for the suggestion! I'll mark this for review as we continue development of RStudio.

**Comment by colearendt** [comment]
All the vimprovements are my favorite!
