### ISSUE TITLE
Bring Visual Studio Code keybindings as an option to RStudio

### ISSUE THREAD

**Issue by kieran-mace** [rstudio/rstudio#9242]
VSCode is one of the worlds most popular editors, and many RStudio users are accustomed to using their keybindings.

I'd really love to see VSCode's keybindings added to the set of options along Default/VIM/Emacs/Sublime

![Screen Shot 2021-04-19 at 8 44 47 AM](https://user-images.githubusercontent.com/18296227/115265026-afac5e80-a0eb-11eb-87f9-f6fa2da034e3.png)

**Comment by kieran-mace** [comment]
@ronblum any update? Is this something that the community could help with?

**Comment by ronblum** [comment]
@kieran-mace We're always glad to consider community contributions! Here's a brief description of what's needed for that: https://github.com/rstudio/rstudio/blob/main/CONTRIBUTING.md#contributing-code

**Comment by colearendt** [comment]
Shhhhh. Back to sleep stalebot.
