### ISSUE TITLE
Realtime Spellcheck: Custom Imported Dictionary Words Not Ignored

### ISSUE THREAD

**Issue by valerie-rstudio** [rstudio/rstudio#9244]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1671-2
    OS Version      : ubuntu18
    R Version       : 4.0.2

### Steps to reproduce the problem
1. Go to Tools > Global Options > Spelling and import a custom dictionary ([download example.dic](https://drive.google.com/file/d/1_UYNe89rfFIfn0btdrenjkuhgC9APMw-/view?usp=sharing))
2. Open an R Markdown file
3. Type one of the words from the custom dictionary (i.e. eggsample)
4. **Expected:** The word will not be underlined in red, as it is ignored by the spellchecker.
5. **Actual:** The word has a red underline.

### Notes
- Discovered while testing the PR for (and still occurring after) https://github.com/rstudio/rstudio/issues/9145 
- Also not working for Edit > Check Spelling method of spellcheck either
- Could not attach the example.dic file directly in GitHub, as the .dic filetype is not supported

**Comment by colearendt** [comment]
github-actions isn't a word either, stale bot

<img width="335" alt="image" src="https://user-images.githubusercontent.com/23075542/166400524-afaf46d2-a078-40c6-945f-58d9e466e01f.png">

Dictionaries are important
