### ISSUE TITLE
Column range indicator doesn't update properly in data viewer

### ISSUE THREAD

**Issue by wgrundlingh** [rstudio/rstudio#9247]
Consider the following example:

    data <- tibble(
      a = paste0(
        rep(LETTERS, 4),
        1:(length(LETTERS) * 4)
      ),
      b = 1:(length(LETTERS) * 4)
    ) %>% pivot_wider(
      names_from = `a`,
      values_from = `b`
    )

This creates `data` to have over 100 variables (columns). When I `View(data)`, it shows the column 0 - 50 in the data view column range. This should actually be 1 - 50. Clicking on right arrow `>` jumps to the next 50, but shows 50 - 50 instead of 51-100. Click on the end arrow `>>` jumps to the last 50, but shows 54 - 50 instead of 55 - 104.

![temp](https://user-images.githubusercontent.com/1776164/115452422-41db6200-a1d3-11eb-94e5-b7bc27d2a406.gif)

It seems like the range start indicator is off by one and the range end indicator isn't updated at all.

Using RStudio Version 1.4.1106.

**Comment by ronblum** [comment]
@wgrundlingh Thank you for raising this! This came up before (#9036), and the problem fixed in the latest development builds for an upcoming release. You can get them from https://dailies.rstudio.com. However, please note that these are for testing purposes only.)
