### ISSUE TITLE
Cannot install/load ggplot2 (how to update rlang to 0.4.10? ; how to make Rtools work?)

### ISSUE THREAD

**Issue by AndresPeredo** [rstudio/rstudio#9250]
Hi!

Everything was working fine with R (as far as I know) until I tried to load the package "ggpubr". After doing so, ggplot wasn't working anymore. I tried to just load it and didn't work. I tried to reinstall ggplot2 and it didn't work as it could find the package "lifecycle". I tried to install ggplot2 with dependencies, and also tried to install lifecycle directly, but I didn't succeed.

The problem was that "lifecycle" needs the most updated version of "rlang" (I had 0.4.5 but it asked for 0.4.10).
I tried to update it from "Tools/Check for Package Updates", but apparently it didn't work. I tried to update it by installing it from the root,
> install.packages("https://cran.r-project.org/src/contrib/rlang_0.4.10.tar.gz", repos = NULL, type="source")

but it gave me an error message saying that "make" is not found.
I updated R to the latest version, without solving anything.

I followed this thread then:
#https://stackoverflow.com/questions/53279685/r-make-not-found-when-installing-a-r-package-from-local-tar-gz

so I installed then Rtools and created a .Renviron as it is explained [here](https://cran.r-project.org/bin/windows/Rtools/)

Now it gaves me this error:
![r error 2](https://user-images.githubusercontent.com/11272855/115533057-a90e1a80-a296-11eb-994c-e906ac441145.png)

As far as I understood reading about it, now R doesn't understand where the tools are and several things are meant to be changed manually, but every explanation I find is too confusing to follow.

Thank you for your help, this is driving me crazy

edit: Some general info
I work on PC, Windows10, now I have the current latest version of Rstudio (Version 1.4.1106) and Rtools40 (which is installed in C:/rtools40)

If I look for "make" in R, it finds it in the Rtools file (as I changed the .Renviron).
Rstudio is installed in the default folder ("C:/Users/andre/Documents/R" in my case)

**Comment by AndresPeredo** [comment]
I work on PC, now I have the current latest version of Rstudio (Version 1.4.1106) and Rtools40 (which is installed in C:/rtools40)

If I look for "make" in R, it finds it in the Rtools file (as I changed the .Renviron).
Rstudio is installed in the default folder ("C:/Users/andre/Documents/R" in my case)

**Comment by kevinushey** [comment]
Can you just install the latest binary of `rlang`? A plain `install.packages("rlang")` should suffice, assuming you're using a new-enough version of R.

Rtools40 is for R (>= 4.0); you likely need to install one of the older versions of Rtools here: https://cran.r-project.org/bin/windows/Rtools/history.html (choose the version appropriate for the version of R you're using)

**Comment by AndresPeredo** [comment]
Thanks for your feedback, we are maybe doing some progress.
The direct installation didn't work, but I installed the Rtools35 (ticking the box to include it in my PATH) as suggested (my R version is 3.5.1) and it fixed the "rlang" package (and the "lifecycle") installation... BUT now is the package "pillar" the one which is not working.

Same procedure, I tried to install the whole "ggplot2" with dependencies. As "pillar" was giving me an error, I tried to install it directly, but it didn't work as well. Now is this error showing:
![r error 3](https://user-images.githubusercontent.com/11272855/115607093-cff33d80-a2e4-11eb-8e98-7c33a4e23033.png)

**Comment by kevinushey** [comment]
That error likely implies that you need to update the `vctrs` package before updating `pillar`. Unfortunately, `pillar` depends on a specific newer version of the `vctrs` package but doesn't properly declare that in its DESCRIPTION file.

**Comment by AndresPeredo** [comment]
It worked! Thanks a lot!

Too bad I don't know the source of the issue so the solution was mostly patchwork, but I am not going to complain!
