### ISSUE TITLE
session fails to start if reticulate is loaded in .Rprofile

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9253]
### System details

    RStudio Edition : All
    RStudio Version : 1.4.1681
    OS Version      : macOS 11.2.3
    R Version       : 4.0.5

### Steps to reproduce the problem

In your `.Rprofile`, put something like:

```
library(reticulate)
```

### Describe the problem in detail

RStudio fails to start.

---

### RStudio Version

RStudio 1.4.1681, "Juliet Rose" (6381b1a1, 2021-04-21) for macOS

Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

### Error message

The R session had a fatal error.

21 Apr 2021 22:22:55 [rsession-kevinushey] ERROR r error 4 (R code execution error) [errormsg: Error in .Call(method, prefName, PACKAGE = "(embedding)") : 
  "rs_readUserPref" not available for .Call() for package "(embedding)"
]; OCCURRED AT rstudio::core::Error rstudio::r::exec::evaluateString(const std::string &, SEXP *, sexp::Protect *, rstudio::r::exec::EvalFlags) src/cpp/r/RExec.cpp:349

### Process Output

The R session exited with code 2. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*/Users/kevinushey/.local/share/rstudio/log/rsession-kevinushey.log*

```
"rs_readUserPref" not available for .Call() for package "(embedding)"
]; OCCURRED AT rstudio::core::Error rstudio::r::exec::evaluateString(const std::string &, SEXP *, sexp::Protect *, rstudio::r::exec::EvalFlags) src/cpp/r/RExec.cpp:349
; LOGGED FROM: void (anonymous namespace)::rSuicide(const std::string &) src/cpp/session/SessionMain.cpp:1175

```

**Comment by rich-rstudio** [comment]
verified on Version 1.4.1689 MacOS
