### ISSUE TITLE
Rstudio deb not installable on Debian 11 (bullseye)

### ISSUE THREAD

**Issue by highvoltage** [rstudio/rstudio#9255]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Debian 11 (bullseye)
    R Version       : 4.0.4

### Steps to reproduce the problem

Install the rstudio package from the rstudio repository

### Describe the problem in detail

The package is built against a previous version of Debian, so the dependencies are out of date. A new binary package should be generated and uploaded to the rstudio archive.

### Describe the behavior you expected

Package gets installed and my users are satisfied.

**Comment by jmcphers** [comment]
We do not formally support Debian 11 as it hasn't been released yet. We will likely add support for it in the version of RStudio that follows the Debian 11 stable release.

**Comment by jmcphers** [comment]
See also: https://github.com/rstudio/rstudio/issues/8894. Have you tried using the build intended for Ubuntu Bionic?

**Comment by ronblum** [comment]
FWIW, I'm able to install the Debian 10/Ubuntu 18+ RStudio Desktop 1.4.1106 binaries on Debian 11, and it starts up.

**Comment by bathyscapher** [comment]
Hey, as Debian 11 Bullseye was released August 2021, could you update the [download info](https://www.rstudio.com/products/rstudio/download/#download) accordingly? Btw, I just downloaded and installed  rstudio-2021.09.0+351-amd64.deb on Debian 11 succesfully. Thanks! :-)

**Comment by ronblum** [comment]
@bathyscapher Technically, we don't yet fully support Debian 11. We've done some testing on it, but it hasn't yet been fully certified. Though as you use it, if you run into any issues, please let us know (with new bug reports), which would help us and others—thank you in advance!

**Comment by bathyscapher** [comment]
Okay, good to know, thanks. I will let you know if I find something!

**Comment by mikebessuille** [comment]
I will file an issue on rstudio.com to identify the ubuntu 18 bionic build as working for Deb 11.

**Comment by mikebessuille** [comment]
Closing - this issue belongs in the rstudio.com repo
