### ISSUE TITLE
Ctrl + Left mouse click opens object, but moves to the top of the script

### ISSUE THREAD

**Issue by NordinZandhuis** [rstudio/rstudio#9257]
RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Windows 10, Version: 10.0.19042 Build 19042
    R Version       :  4.0.5

### Steps to reproduce the problem
Use (left) control and left mouse click to open up an object. 

### Describe the problem in detail
I tend to use long Rmarkdown scripts. Whenever I want to take a quick look at a given object, I use ctrl + left mouse click to open up an object. Everytime I open up an object it goes back to the top of the entire Rmarkdownfile (all the way to the part where I load multiple packages), which means I have to scroll down all the way down again to continue working on my code. 

### Describe the behavior you expected
I expect that Rstudio remains on the same line of code that I opened the object from.

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@NordinZandhuis Thank you for raising this! Does this occur only with long R markdown files, or even for something like the default when creating a new Rmd file? I ask because I can't reproduce this, when using RStudio Desktop 1.4.1106.
