### ISSUE TITLE
Running single test file triggers full package recompilation

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9264]
**Steps to reproduce:**
* Load some R package project with compiled C/C++ code and tests using testthat (example to use: xgboost downloaded from CRAN).
* Install the package from the build pane, leaving all the compiled objects where they should be.
* Modify some R file.
* Pick some random test file within the tests folder and click `Run Tests`.

**Expected behavior:** should not trigger a recompilation unless the files to compile have changed.

**Actual behavior:** triggers a full recompilation, in debug mode. The issue is not present when running all the tests through the build pane instead.

**Setup:** RStudio 1.4.1118.

**Comment by david-cortes** [comment]
Still relevant.

**Comment by mikebessuille** [comment]
@romainfrancois  you were mentioning a desire to improve the way tests are run in the IDE...

**Comment by david-cortes** [comment]
It actually affects other packages too, such as this one: https://github.com/david-cortes/isotree

I'm not 100% sure, but I think the problem does not happen when running windows OS, and I _think_ it's more prone to happen when there is a file `~/.R/Makevars` with non-default compilation arguments.

**Comment by gaborcsardi** [comment]
Yes, sometimes pkgbuild is not able to deduce correctly if a package should be recompiled or not. You can file an issue in pkgbuild, and I will take a look.

**Comment by romainfrancois** [comment]
Closing this here then, as the solution is more likely to involve `pkgbuild` work.
