### ISSUE TITLE
Add support for new homebrew install path on ARM Macs

### ISSUE THREAD

**Issue by mshamash** [rstudio/rstudio#9265]
Hi,

Homebrew on ARM/M1 Macs now defaults to installing packages to /opt/homebrew/bin as opposed to /usr/local/bin for compatibility. Since some R users choose to install R this way (via brew), this means we'd need to run `export RSTUDIO_WHICH_R=/opt/homebrew/bin/R` before opening RStudio via the command line each time.
Would it be possible to add `/opt/homebrew/bin/R` to the list of `rScriptPaths` so users who install via this method can just launch RStudio directly without need for CLI/launch scripts?

I've linked the lines of code which I believe are in question below.

Cheers.

https://github.com/rstudio/rstudio/blob/0899d13386fd5e61ec847cc62a6eb252702a5ebc/src/cpp/core/r_util/REnvironmentPosix.cpp#L106-L119

**Comment by ronblum** [comment]
@mshamash Thank you for bringing this up! And I especially appreciate that you included the location in the code. I'll mark this for review, as we are working on support for ARM/M1.

**Comment by mshamash** [comment]
> @mshamash Thank you for bringing this up! And I especially appreciate that you included the location in the code. I'll mark this for review, as we are working on support for ARM/M1.

Great, looking forward to it! Happy to help.

**Comment by astayleraz** [comment]
I verified in version 1.4.1689 on an m1 mac and r installed via brew only, I was able to launch and use rstudio. Closing issue.
