### ISSUE TITLE
Performance Issue with -- Tools > Global Options > Console > ANSI Escape Codes : "Show ANSI Colors"

### ISSUE THREAD

**Issue by bschulth** [rstudio/rstudio#9266]
### System details

    RStudio Edition : RStudio Workbench/RStudio Server Pro
    RStudio Version : Dailies: 1.4.1644-1
    OS Version      : Ubuntu 18.04
    R Version       :  R 4.0.4

- I realize this is a daily release, but wanted to report the issue in hopes that you could fix it prior to official 1.4 release.

### Steps to reproduce the problem
- To enable performance problem, set:
   - `Tools > Global Options > Console > ANSI Escape Codes : "Show ANSI Colors" `
  
- To disable performance problem, set:
   - `Tools > Global Options > Console > ANSI Escape Codes : "Remove ANSI codes" `

### Describe the problem in detail
- When the R Console is rendering ANSI colors the code finishes in expected time, however, the UI locks up for a long'ish time and does not respond to input in the editor or anywhere (and sometimes in Chrome, pops up the Wait or Exit long running script).

### Code To repeat the issue

To see the problem, run following code with  `Tools > Global Options > Console > ANSI Escape Codes : "Show ANSI Colors" `...this should return control to user in about *35-40 seconds*

To see the expected timing, run following code with  `Tools > Global Options > Console > ANSI Escape Codes : "Remove ANSI codes" `....this should render output and return control to user in about *5 seconds*.

```r
tcars <- tibble::as_tibble(mtcars)
system.time({
     for (i in 1:100) {
          # Printing a tibble with Ansi Colors
          print(tcars, n=100)
     }
})
```

### Describe the behavior you expected
- In prior releases, the performance was basically as fast as when NOT rendering ANSI colors.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@bschulth Thank you for raising this! I can't reproduce it, but it might be because I'm not reproducing the exact environment.
- What operating system are you connecting from to RStudio Server—is it also Ubuntu 18.04, or another OS?
- Does the issue appear in browsers besides Chrome?

Also, regarding reporting an issue with a daily release: That's they're main purpose, for our user community to try out and provide feedback, so I appreciate your trying it out and filing the issue!

**Comment by gtritchie** [comment]
@ronblum if you get a repro, please assign issue to me! Thx.

**Comment by KaiAragaki** [comment]
Hello!

I have been able to reproduce this issue on a Windows machines

RStudio Edition : RStudio Desktop
RStudio Version : Preview: 1.4.1711
OS Version      : Windows 10.0.19043 Build 19043
R Version       :  R 4.1.0

Everything @bschulth described was the same for my: the system time check was short for both cases:
(ANSI off)
   user  system elapsed 
   2.64    0.02    2.64 
(ANSI on)
   user  system elapsed 
   2.67    0.00    2.67 

However, the wall clock time from code execution was considerably longer (~30...didn't time it). 

Something that may be required is to open a .Rproj that _already has ANSI escape codes in R console enabled_
I found that if I disasbled ANSI escape codes, closed my R studio session, opened the project, and turned on ANSI escape codes it would run fine.

**Comment by bschulth** [comment]
Sorry @KaiAragaki I just saw your request for more information.  Glad you were able to repeat it.  For completeness, rstudio is running on Ubuntu 18.04 and was accessing from Mac via Chrome.  But it seems you have found it to be related to how the setting is set prior to open an R project.

**Comment by bschulth** [comment]
@KaiAragaki  thanks, updated the post to @mention ronblum

**Comment by bschulth** [comment]
@ronblum, @gtritchie 
Outside of the context of an RStudio Project (e.g. no project selected), I did find that the first time I toggled the `ANSI Escape Codes` value, I did have to restart my R session to trigger the behavior. But all subsequent toggles of the property took effect immediately without an R Session restart.
