### ISSUE TITLE
(C++) Enter key doesn't work when pressed after #ifdef with macro

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9267]
**Steps to reproduce**:
* Create a new C++ source file.
* Write some function in there.
* Start writing this (but do not copy it from here, needs to be letter-by-letter):
```cpp
#ifdef __SSE__
```
* Once the line above has been written in full, press enter.

**Expected behavior:** should switch to a new line.

**Actual behavior:** nothing happens. The issue is present when invoking any compiler-defined macro.

**Setup:** RStudio 1.4.1118.

**Comment by ronblum** [comment]
@david-cortes Thank you! For the issues you filed in the last few days, are they in Debian or Windows? And do you know if they worked correctly in previous releases?

**Comment by david-cortes** [comment]
This is in debian testing, and I don't know if they were working correctly before.

**Comment by kevinushey** [comment]
Not able to reproduce (RStudio 1.4.1681; macOS 11.3)
