### ISSUE TITLE
Erratic crashes with parallel/makeCluster

### ISSUE THREAD

**Issue by Thorsten-Behrens** [rstudio/rstudio#9271]
### System details
    RStudio Edition : Desktop
    RStudio Version : RStudio-1.4.1106
    OS Version      : Windows 10
    R Version       : 4.0.5

### Steps to reproduce the problem
calling parallel::makeCluster kills RStudio - Bomb....

### Describe the problem in detail
After upgrading to RStudio-1.4.1106 RStudio crashes when calling makeCluster. In somce functions it works in some not. There is really no differences in the code. Running some of these functions manually step by step all is fine. But within a function call it crashes.

Going back to RStudio-1.3.1093 solves the issue.

Cheers,
Thorsten

**Comment by Thorsten-Behrens** [comment]
https://github.com/rstudio/rstudio/issues/8724 seems to be realted

**Comment by kevinushey** [comment]
Does this reproduce for you in the latest [daily builds](https://dailies.rstudio.com)?

**Comment by Thorsten-Behrens** [comment]
No! 
With RStudio-1.4.1695 the issue seems to be solved!
Thanks!
