### ISSUE TITLE
Environment section automatically resets column width everytime an element is updated

### ISSUE THREAD

**Issue by andresmorago** [rstudio/rstudio#9274]
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/6385979/diagnostics-report.txt)

### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1106
    OS Version      :  Windows 10 Pro - 2004
    R Version       :  4.0.4

### Steps to reproduce the problem

I create a test element
`this_is_a_test_element = 3`

I manually change the column width on the Environment tab:
![image](https://user-images.githubusercontent.com/13720514/116273787-ae141380-a747-11eb-9b4b-aaad9210ab52.png)

After running any kind of function than either creates of modifies an element:
`this_is_a_test_element = 3.5`

the column width is automatically restored:
![image](https://user-images.githubusercontent.com/13720514/116273946-d13ec300-a747-11eb-8fd0-16eb41729b54.png)

### Describe the behavior you expected
I would like the column to maintain the width i have set even after running a command that modifies the content of an element

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@andresmorago Thank you for raising this! I can reproduce this in
- RStudio Desktop 1.4.1689 on MacOS 11.3
- RStudio Server 1.4.1687 on Ubuntu 20.04 via Chrome on MacOS 11.3

It only happens when the first value is updated.

1. `this_is_a_test_element = 3`
2. Adjust column width in Environment pane.
3. `this_is_a_test_element = 3.5`
    - The column widths are reset.
4. Change the column width.
5. `x <- 3`
    - The column widths are unchanged.
6. `a <- 3`
    - The column widths are reset.
7. Change the column width.
8. `this_is_a_test_element = 3`
    - The column widths are unchanged.
9. `a <- 3.5`
    - The column widths are reset.

**Comment by andresmorago** [comment]
Do you think this can be fixed in a near future?
