### ISSUE TITLE
All column types are "unknown" when viewing zero-row data frame

### ISSUE THREAD

**Issue by arencambre** [rstudio/rstudio#9280]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Windows 10 20H2
    R Version       : 4.0.5

### Steps to reproduce the problem
1. `summary <- data.frame(category = character(), amount = numeric())`
2. `View(summary)`
3. Hover mouse over any column name.
 
### Describe the problem in detail

You see that the column is of "unknown" type in the tooltip:
![image](https://user-images.githubusercontent.com/411495/116409318-5a620280-a7f9-11eb-8fae-f006f5e3f38d.png)

### Describe the behavior you expected
You see the column type, which in this case is double. That is confirmed with `typeof(summary$amount)`, which returns `double`.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
This may be a valid issue, but it is an edge case that I expect would affect very few workflows.  Unfortunately, given the large backlog of urgent issues we are facing, I'm closing this.  If a lot of users have issue with this and upvote it, we can reconsider.
