### ISSUE TITLE
RStudio crashes when plot() is called while there is an open chess engine handler created with bigchess::uci_engine()

### ISSUE THREAD

**Issue by dryguy** [rstudio/rstudio#9281]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.1114
    OS Version      : Windows 10 x64 (build 19041)
    R Version       : R version 4.0.5 (2021-03-31)

### Steps to reproduce the problem
install the Stockfish chess engine (https://stockfishchess.org/)
open RStudio
install the bigchess package
run this code (usually crashes right away; sometimes it takes two or three tries):

foo <- 1:100
engine <- bigchess::uci_engine('//stockfish_13_win_x64_bmi2.exe')  # change directory as required
plot(foo)

### Describe the problem in detail
Doing the above causes RStudio to crash with the messages:

R Session Aborted
R encountered a fatal error.
The session was terminated.

I cannot reproduce the problem outside of RStudio. The code runs fine in the Rgui, or when using a different editor (Tinn-R), which is why I suspect it may be an issue with RStudio rather than bigchess or Stockfish.

### Describe the behavior you expected
I expected RStudio to not crash.

**Comment by kevinushey** [comment]
Sorry, but I wasn't able to reproduce on my machine.

**Comment by dryguy** [comment]
I've corresponded with the author of bigchess, and he was unable to reproduce the crash with:

foo <- 1:100
engine <- bigchess::uci_engine("./stockfish_13_linux_x64")
plot(foo)

but was able to reproduce it with:

foo <- 1:100
engine <- bigchess::uci_engine("./stockfish_13_linux_x64_bmi2")
plot(foo)

so apparently the exact version of Stockfish matters. It seems that the bug may be specific to the bmi2 version of Stockfish.

**Comment by ronblum** [comment]
@kevinushey I'm able to reproduce this with the following, but only if running this a script all at once. Line by line works fine.
```
plot(1)
engine <- bigchess::uci_engine('//Program Files/Stockfish/stockfish_13_win_x64_bmi2.exe') # change directory as required
```
