### ISSUE TITLE
Command history is incomplete / inconsistent

### ISSUE THREAD

**Issue by ksvanhorn** [rstudio/rstudio#9290]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : macOS Catalina (10.15.7)
    R Version       : 4.0.5

### Steps to reproduce the problem
I have not been able to figure out how to reproduce this. It is an intermittent problem.

### Describe the problem in detail
After shutting down RStudio for the day (answering "yes" to whether I wanted to save the workspace) and restarting it in the morning, there were anomalies in my command history. (Note that I have "Restore .RData into workspace at startup" checked, as well as "Always save history (even when not saving .RData)". The command history I see in the "History" window is missing a large block of commands from the end of previous day. Oddly enough, however, if I do a history search and then click on one of the results to see the context, it shows me the missing history.

Here is a specific example. The most recent commands showing in the History window were

```
    plot(foo$seasonal[1:70], typ='l')
    names(res)
    names(ressin)
    devtools::load_all(".")
    names(mdl_lon)
    mdl_lo$toJSON
    mdl_lon$toJSON
    foo <- readRDS('~/Tmp/mdl_lon.res')
    foo <- readRDS('~/Tmp/mdl_lon.rds')
    foo$toJSON
    names(res)
    foo <- readRDS('~/Tmp/res-pnw.rds')
    names(foo)
    getwd()
    rm(fpp)
    rm(foo)
```

The line `devtools::load_all(".")` was the first command I issued when I restarted RStudio in the morning. I did a search for `rm(foo)`, which is the most recent command in the above history, and clicked on the first (most recent) search result to see the context. Here is what I got (showing only the most recent commands, the tail of the context):

```
    mdl_sin <- bf5a_fitobj_to_spiky_dlmti(dsin2, ressin)
    save.image()
    saveRDS(mdl_sin, '~/Tmp/mdl_sin.rds')
    devtools::load_all(".")
    names(mdl_lon)
    mdl_lo$toJSON
    mdl_lon$toJSON
    foo <- readRDS('~/Tmp/mdl_lon.res')
    foo <- readRDS('~/Tmp/mdl_lon.rds')
    foo$toJSON
    names(res)
    foo <- readRDS('~/Tmp/res-pnw.rds')
    names(foo)
    getwd()
    rm(fpp)
    rm(foo)
```

You'll notice that the two diverge prior to `devtools::load_all(".")`, the first command I issued on restarting RStudio. If I recall correctly, the lines you see in the regular History are from much earlier in the day yesterday; what I see in the context history does look like my final commands before shutting down for the day.

As one other datum, I did note that the timestamp on  `.Rhistory` was from yesterday morning, whereas the timestamp on `.RData` matched the time I shut down RStudio yesterday. Again, let me emphasize that in Preferences I have checked "Always save history".

### Describe the behavior you expected

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ksvanhorn Thank you for raising this! You mention that the problem is intermittent: Did this only occur one time, or does this happen occasionally?

**Comment by ksvanhorn** [comment]
It's happened maybe three times over the last several months.

**Comment by colearendt** [comment]
👍
