### ISSUE TITLE
Support loading of cached code chunks

### ISSUE THREAD

**Issue by ugroempi** [rstudio/rstudio#9291]
Thank you for providing RStudio with Rmarkdown. Below you find a wish for a utility in connection with cached chunks, which I had originally posted [in the Rmarkdown repo](https://github.com/rstudio/rmarkdown/issues/2124):
Working with Rmarkdown documents, I often want to play with a particular chunk interactively without running the entire document. It is easy to run the entire document up to the chunk in question with the `Run all chunks above` command. If some of the chunks contain lengthy computations, it would be very helpful if there were a `load relevant cached chunks` (or similar) command that would load cached content from the chunks that are listed in the `dependson` chunk option of the chunk in question. I can load those stored chunks with code, but I would expect that I am not the only one who would appreciate an automation of this otherwise cumbersome step. 

In this connection, it would certainly also be helpful if the feature request of issue [8149](https://github.com/rstudio/rstudio/issues/8149) could be implemented.

Thanks and regards,
Ulrike

**Comment by ronblum** [comment]
@ugroempi Thank you for the enhancement request, and also for referencing the other requests! We'll review this as we continue to develop RStudio.

And most of all:
> Thank you for providing RStudio with Rmarkdown.

You're welcome! 😃

**Comment by colearendt** [comment]
👍
