### ISSUE TITLE
Add the option to copy environment variables to clipboard with one click and allow more levels of code folding

### ISSUE THREAD

**Issue by pozlepster** [rstudio/rstudio#9292]
Hi, 

it would be really great if one could easily copy the data from the R environment to clipboard (and subsequently Excel) using a click of a button. The current procedure of selecting the data manually or of having to write custom functions to copy variables to clipboard is not very practical. This is a minor feature request, but I am sure it would be useful for many of us who work in primarily Excel based institutions which means we need to copy data from RStudio frequently.

My other feature request is to add the ability to have a more levels of code folding. Right now you can fold the code between the #### TEXT ----- and  #### TEXT2 -----. However I very often encounter situations where I would need to fold the code inside this folded code. I would be very grateful if you could allow two or three levels of code folding. 

Thank you for your consideration.

**Comment by ronblum** [comment]
@pozlepster Thank you for the suggestions!
- For the environment variables request, I'll mark this for review as part of our ongoing development of RStudio.
- For the code folding request, can you open up a separate issue, and include a simple example of code with multiple levels? I want to make sure I'm looking at it properly, and I suspect that I'm not.

Thanks!

**Comment by pozlepster** [comment]
@ronblum great thank you very much. I will open a separate issue for code folding.

**Comment by colearendt** [comment]
👍

**Comment by colearendt** [comment]
Getting things onto the clipboard quickly is a key improvement for interoperability with other programs!
