### ISSUE TITLE
Code completion can make incorrect substitution

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#9293]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : macOS Catalina 10.15.7
    R Version       : 4.0.3 patched r79912

### Steps to reproduce the problem

Install the packages `rgl`, `Rglpk`, `rglwidget`.

In the console, type `library(rgl` quickly.  (Typing slowly gives different behaviour.)

### Describe the problem in detail

After typing `library(rgl`, the code completion popup comes up.  The list of options is `Rglpk`, `rgl`, `rglwidget`, with the
default being the first, so if you hit Enter quickly, the console executes `library(Rglpk)` instead of what I intended.

If I type `rgl` slowly, the list at the end is in the order `rgl`, `rglwidget`, `Rglpk`, `rgdal`, `brglm`, which is fine.

I can also get the bad list by typing the full statement, then backspacing to leave `library(`, and typing `rgl` slowly, but in this case I need to type the closing `)`, and I end up with the correct `library(rgl)` command.

### Describe the behavior you expected

Since the console contains `library(rgl)` (with the cursor before the closing `)`) at the time of the popup, and that's one of the code completion choices, it should be left as the default choice, as it is if I type slowly.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@dmurdoch Thank you for bringing this up! An even simpler example: `base` results in `base64enc` and `base`, in that order, unless typing slowly. I'll mark this for review as we continue to develop RStudio.

Note: In 1.0.153, the order was alphabetical.
<img width="177" alt="base_10153" src="https://user-images.githubusercontent.com/31009952/117042190-a5888380-acd9-11eb-8b04-b76a9e75e839.png">

Starting in 1.1.453 and now in 1.4.1695, the order is different, so the first match often doesn't match what was first typed. 
<img width="211" alt="base_141695" src="https://user-images.githubusercontent.com/31009952/117042249-b6d19000-acd9-11eb-9782-2d632b985623.png">

Whatever the logic of the order, I think that if the characters typed so far match a package, it should be shown first.

**Comment by dmurdoch** [comment]
Just tried both examples today, and things worked properly.  I'm using the same 1.4.1103 version of RStudio, so maybe the bad ordering was being done by a package?

**Comment by kevinushey** [comment]
I believe this is because the initial completion list produced and presented by RStudio did not have any defined ordering; it appeared to be in whichever order the RStudio package indexer happened to find that package. I've created a PR to improve the behavior here (properly sort completions when first presented).

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 1.5.232 on MacOS 12 beta
- RStudio Desktop 1.5.233 on Ubuntu 20.04.2
- RStudio Server 1.5.233 on Ubuntu 20.04.2 via Safari on MacOS 12 beta

Marking for possible automated tests.

**Comment by astayleraz** [comment]
I looked into automating this but was not successful. As well, this looks like a case that would be better to automate at a lower level in the code and not in the UI. Closing issue.
