### ISSUE TITLE
rmarkdown fails on vanilla rmarkdown document supplied with rstudio

### ISSUE THREAD

**Issue by RobinHankin** [rstudio/rstudio#9295]
### System details

    RStudio Edition : desktop; "Tiger Daylily" (2389bc24, 2021-02-11) for macOS    RStudio Version : 1.4.1106
    OS Version      : macos 10.15.7
    R Version       : 4.0-5

### Steps to reproduce the problem

Brand new computer today.    All software on it was installed this morning including R and RStudio and all packages and texlive.

Open rstudio.  File -> New File -> R-Markdown -> OK ; knit ; accept default.

I am trying to knit the default vanilla Rmd example file that comes bundled in with RStudio.

### Describe the problem in detail

on clicking "knit", rmarkdown fails with the following error:

```
processing file: _main.Rmd
Error in parse_block(g[-1], g[1], params.src, markdown_mode) : 
  Duplicate chunk label 'setup', which has been used for the chunk:
knitr::opts_chunk$set(echo = TRUE)
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
In addition: Warning message:
In xfun::prose_index(x) : Code fences are not balanced
Please delete _main.Rmd after you finish debugging the error.
Execution halted
```

### Describe the behavior you expected

I expected the vanilla Rmd file to knit and display a nicely formatted document.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@RobinHankin Thank you for raising this! I'll mark this for review. In the meantime, what happens when running something as simple as:

````
---
title: "One"
output: html_document
---

```{r one}
print(1)
```
````

**Comment by RobinHankin** [comment]
Thanks for this @ronblum.  Just now, I created a file called `one.Rmd`, pasted the code above in to it, opened it from the commandline with `open one.Rmd` which fired up RStudio, and . . . got the same error message:

```
processing file: _main.Rmd
Error in parse_block(g[-1], g[1], params.src, markdown_mode) : 
  Duplicate chunk label 'setup', which has been used for the chunk:
knitr::opts_chunk$set(echo = TRUE)
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
In addition: Warning message:
In xfun::prose_index(x) : Code fences are not balanced
Execution halted
```

[I don't think it's relevant but I have added  a `_bookdown.yml` file with the single line `delete_merged_file: true` because the knit system was complaining about a pre-existing `_main.Rmd` file]

Best wishes, Robin

**Comment by RobinHankin** [comment]
I have discovered that RStudio creates a file called `_main.Rmd` whenever I click the  "knit" button in Rstudio, even if I knit an empty file.  Looking at the `_main.Rmd`, it contains some of my work from a previous bookdown project.   I can remove `_main.Rmd` but Rstudio creates it again whenever I click knit.   But the file that Rstudio creates is, I think, malformed or corrupted in some way.  Is there any way to control this process?

**Comment by RobinHankin** [comment]
Also, `rmarkdown::render()` works fine.

**Comment by kevinushey** [comment]
I'm not entirely familiar with how `bookdown` operates here but it seems to be responsible for creating a file `_main.Rmd`, and I suspect that it tries to combine R Markdown files in the project in some way during render. Perhaps multiple of those .Rmd files contain a chunk called "setup", and that causes problems during render?

**Comment by kevinushey** [comment]
You might be able to reproduce by running `bookdown::render_book()`.

**Comment by cderv** [comment]
I can confirm that bookdown is creating the `_main.Rmd`. This is the default book filename if none is provided. So it seems this is using a bookdown project. By default, bookdown will use a merge and knit method which means that all Rmd files in the project will be merged together and rendered as a single Rmd file. This means that limitations of unique chunk name applies on the multiple Rmd file. 

I think @kevinushey suggestion is the correct cause: multiple Rmd are probably merged in a single one by bookdown. 

@RobinHankin it is not clear to me if you are explicitly working in a bookdown project or not. RStudio IDE will detect this type of project based on the file in the working directory. So files from bookdown project and other project should not be mixed in the same RStudio project if there are not related. 

Anyhow, if you share more on your working directory / project setup, I could probably help you with this. I don't think this is an issue with the IDE itself but maybe something with the current setup.

**Comment by RobinHankin** [comment]
thanks for this Christophe.  In the end I "solved" the problem when the
lease on my desktop ran out and I could work on a clean install.  But I
suspect you are right in that there was a lot of junk in my home directory
which-- unbeknownst to me --was causing the problems.

Best wishes

Robin
***@***.***>
