### ISSUE TITLE
Warning when function doesn't exist

### ISSUE THREAD

**Issue by rmflight** [rstudio/rstudio#9296]
Motivated by the error I'm sure we've all seen: could not find function lenght

But, given the ability to hit F1 for help on a function, as well as tab completion, it seems like RStudio should have been able to **warn** the script / function writer that this "lenght" function is not known to RStudio in any of the installed packages, or in the global namespace ....

    foo = lenght(c("bar1", "bar2"))

It seems like the *lenght* function should be highlighted somehow to indicate to the user that maybe they need to double check the function call they are making.

**Comment by kevinushey** [comment]
What version of RStudio are you using? Did you enable all of the diagnostics here?

<img width="607" alt="Screen Shot 2021-05-03 at 11 35 51 AM" src="https://user-images.githubusercontent.com/1976582/116917606-b8308900-ac03-11eb-934b-b12c2ef06301.png">

**Comment by rmflight** [comment]
Well look at that, it already does it!

Apparently I didn't have enough diagnostics enabled!
Thanks Kevin!
