### ISSUE TITLE
debugger prints 'Error in object[[i]] : subscript out of bounds' error in some cases

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9299]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1695
    OS Version      : macOS 11.3
    R Version       : 4.0.5

### Steps to reproduce the problem

Try debugging a function call with 2 or more `NULL`s passed to it; e.g.

```
debug(stats::rnorm)
stats::rnorm(NULL, NULL, NULL)
```

### Describe the problem in detail

An error is printed in the console:

<img width="373" alt="Screen Shot 2021-05-03 at 12 05 58 PM" src="https://user-images.githubusercontent.com/1976582/116920802-ed3eda80-ac07-11eb-846c-d25309b11ffe.png">

In addition, the debugger appears to be blank:

<img width="796" alt="Screen Shot 2021-05-03 at 12 06 26 PM" src="https://user-images.githubusercontent.com/1976582/116920848-ffb91400-ac07-11eb-9e7b-3fb7b30af5b1.png">

### Describe the behavior you expected

No error, and the traceback + values should show without issue.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Should be resolved via https://github.com/rstudio/rstudio/pull/9300.

**Comment by ronblum** [comment]
@kevinushey I tried reproducing this in RStudio Desktop 1.4.1717 on MacOS 12.1 with R 4.1.1, but I couldn't quite reproduce it. Here's what I get:
![debug.png](https://codetreeusercontent.s3.amazonaws.com/uploads/a2e63c3a-0bf3-4cb2-a29d-b39e24a24504/debug.png)

Is this what's expected, including the error message after clicking on "next"? Do you think there's something I need to do differently to reproduce it, such as a different version or R?

**Comment by kevinushey** [comment]
Hmm. Based on https://github.com/rstudio/rstudio/pull/9300:

> Addresses #9299. Regressed in c3959eb#diff-acb7e18d1d539ae9118a0fa5da125619159028eef4c76661553b87b2f968f30b; bug was never part of a public release.

So it sounds like it won't be possible to reproduce the error in an older version of RStudio? It should suffice that you don't see the buggy behavior in the current release, I think.

**Comment by ronblum** [comment]
In that case, the error doesn't appear in
- RStudio Desktop 2022.02.0+377 on MacOS 12.1
- RStudio Server 2022.02.0+375 on Ubuntu 20.04 via Chrome on MacOS 12.1
