### ISSUE TITLE
RSTUDIO_DATA_HOME is not passed to rsession correctly

### ISSUE THREAD

**Issue by tdb** [rstudio/rstudio#9303]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1106
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.5

### Steps to reproduce the problem

In trying to change the directory where RStudio stores its data, I have set `RSTUDIO_DATA_HOME` in the systemd unit as suggested in the documentation:

```
$ cat /etc/systemd/system/rstudio-server.service.d/override.conf
[Service]
Environment="RSTUDIO_DATA_HOME=$HOME/.rstudio-$HOSTNAME"
```

However, the directory is not changed with the default `$HOME/.local/share/rstudio` still being used.

### Describe the problem in detail

The problem is that although the environment variable is correctly set for the `rserver` process, when launching `rsession` the environment variable is discarded. This appears due to code in the `ProcessConfig` function in `ServerSessionManager.cpp` which sets up the environment.

Using `Sys.getenv()` from inside RStudio confirms that the environment variable hasn't been set.

As a test, I applied the following patch:

```
diff --git a/src/cpp/server/ServerSessionManager.cpp b/src/cpp/server/ServerSessionManager.cpp
index 6e37578cab..2433bb7775 100644
--- a/src/cpp/server/ServerSessionManager.cpp
+++ b/src/cpp/server/ServerSessionManager.cpp
@@ -198,6 +198,8 @@ core::system::ProcessConfig sessionProcessConfig(
    environment.push_back(
          std::make_pair(kSessionTmpDirEnvVar, sessionTmpDir().getAbsolutePath()));

+   core::system::setenv(&environment, "RSTUDIO_DATA_HOME", core::system::getenv("RSTUDIO_DATA_HOME"));
+
    // build the config object and return it
    core::system::ProcessConfig config;
    config.args = args;
```

With this applied the expected behaviour is observed. Whilst not necessarily the correct solution it does help to confirm the cause of the problem.

### Describe the behavior you expected

I expected that RStudio would store its data in `~/.rstudio-$hostname` (where `$hostname` is expanded to the hostname of the current machine) rather than `~/.local/share/rstudio`.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
Thank you for the very detailed report! I'm pretty sure I fixed this a few weeks ago in https://github.com/rstudio/rstudio/commit/8cfbe1cc0eaaafa0328a4b601b88bd6844f6334e. Could you confirm in a recent daily build?

https://dailies.rstudio.com/

**Comment by tdb** [comment]
@jmcphers Yes, the latest daily worked. I'm sorry - I should have tested that first. Thought I'd done all the obvious things!

**Comment by jmcphers** [comment]
Great, glad to hear it!
