### ISSUE TITLE
Spell Check - non comment lines in R file are being spell checked

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#9305]
### System details

    RStudio Edition : Both
    RStudio Version : 1.4.1696
    OS Version      : Ubuntu, MacOS
    R Version       : 4.0.2

### Steps to reproduce the problem
1. open an R file
2. type a bunch of misspelled words

### Describe the problem in detail
Non comment lines are being spell checked

![Screen Shot 2021-05-04 at 10 42 34 AM](https://user-images.githubusercontent.com/43964690/117030811-9d264d80-acc5-11eb-9b52-059c15ef63aa.png)

### Describe the behavior you expected
only comments are spell checked in a R file

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Those are code / diagnostic errors, not spelling errors. The errors are indicating that the R code is invalid.
