### ISSUE TITLE
tweak how R functions are invoked by RStudio

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9307]
Currently, when an RStudio function is invoked, the call stack can appear a bit wonky as the actual function definition is substituted for the "name" of that function. For example:

```
    █
 1. └─(function (token, string, type, numCommas, functionCallString, ...
 2.   └─.rs.getCompletionsDollar(...)
```

This happens because we look up the function explicitly early, and then form an expression using the function object (rather than a binding to that function) here:

https://github.com/rstudio/rstudio/blob/05d10c8cd49c5d2b9563d2838e796d9a6b1757b5/src/cpp/r/RExec.cpp#L394-L397

It may be helpful to just use the name of the function here (as an R object) rather than the resolved function object.

**Comment by mikebessuille** [comment]
@kevinushey wondering the benefit to the customer; would this make it easier to diagnose problems in the product?  In user code?

**Comment by rich-rstudio** [comment]
verified on Version 1.5.64
