### ISSUE TITLE
R Studio v1.4.1106 opens only with "sudo rstudio" - the desktop icon doesn't work, nor does the terminal command work without "sudo". Nor does the RSTUDIO_WHICH_R variable.

### ISSUE THREAD

**Issue by MyGithubNotYours** [rstudio/rstudio#9309]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : Ubuntu 18.04
    R Version       : 4.0.5

### Steps to reproduce the problem

1. sudo apt-get install ./rstudio-1.4.1106-amd64.deb _(for Ubuntu 18)_
2. _... installation completes with no errors, icon is created on desktop..._
3. Click on the icon and an R Studio error window opens (pasted below)

### Describe the problem in detail

The R Studio installation process seems to complete without any errors. An icon is produced on my desktop. However, when I click the icon, I get this error message in the R Studio GUI:

```
Error Starting R
The R session failed to start.

ERROR MESSAGE
[No error available]
PROCESS OUTPUT
The R session process exited with code 2.

ERRORS
06 May 2021 03:20:55 [rsession-xxx] ERROR system error 13 (Permission denied) [path: /home/xxx/.local/share/rstudio/sources/s-4881061B, target-dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) const src/cpp/shared_core/FilePath.cpp:809

OUTPUT
[No output emitted]
RECENT LOG
/home/xxx/.local/share/rstudio/log/rsession-xxx.log
13 Sep 2020 17:34:13 [rsession-xxx] ERROR system error 22 (Invalid argument); OCCURRED AT rstudio::core::Error rstudio::session::source_database::get(const string&, bool, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) src/cpp/session/SessionSourceDatabase.cpp:670; LOGGED FROM: rstudio::core::Error rstudio::session::source_database::list(std::vector<rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> >*) src/cpp/session/SessionSourceDatabase.cpp:809
13 Sep 2020 17:34:13 [rsession-xxx] ERROR system error 22 (Invalid argument); OCCURRED AT rstudio::core::Error rstudio::session::source_database::get(const string&, bool, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) src/cpp/session/SessionSourceDatabase.cpp:670; LOGGED FROM: void rstudio::session::modules::explorer::{anonymous}::removeOrphanedCacheItems() src/cpp/session/modules/SessionObjectExplorer.cpp:81
13 Sep 2020 17:34:17 [rsession-xxx] ERROR system error 22 (Invalid argument); OCCURRED AT rstudio::core::Error rstudio::session::source_database::get(const string&, bool, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) src/cpp/session/SessionSourceDatabase.cpp:670; LOGGED FROM: rstudio::core::Error rstudio::session::source_database::list(std::vector<rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> >*) src/cpp/session/SessionSourceDatabase.cpp:809
```

However, R Studio will open successfully if I open it through a terminal by typing "sudo rstudio". If sudo is not included, the same error happens.

Also, setting RSTUDIO_WHICH_R in ~/.profile does not work for R Studio v1.4.1106. If R is not in /usr/bin/, then an R Studio popup complains:

- Unable to find an installation of R on the system (which R didn't return valid output); Unable to locate R binary by scanning standard locations

The RSTUDIO_WHICH_R environment variable works successfully when I revert my installation back to R Studio v1.3.1093. To avoid this problem, it seems that my desired version of R must exist in /usr/bin/.

Summary of problems with R Studio v1.4.1106:
- R Studio will open successfully only if I use "_sudo rstudio_" in a terminal. R Studio will not open successfully without "sudo" or if I click the desktop icon.
- R Studio does not seem to recognize the setting RSTUDIO_WHICH_R in ~/.profile. 

### Describe the behavior you expected
I expected R Studio to start without any problems. When I revert to R Studio v1.3.1093, there is no problem.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
> 06 May 2021 03:20:55 [rsession-xxx] ERROR system error 13 (Permission denied) [path: /home/xxx/.local/share/rstudio/sources/s-4881061B, target-dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) const src/cpp/shared_core/FilePath.cpp:809

You need to ensure that `/home/xxx/.local/share/rstudio` is owned by your user account; e.g. via a recursive `chown`.

**Comment by MyGithubNotYours** [comment]
@kevinushey 
> You need to ensure that `/home/xxx/.local/share/rstudio` is owned by your user account; e.g. via a recursive `chown`.

Thanks much for the reply. But why does R Studio v1.3 work without me having to do that? Literally, I can install/uninstall the versions back and forth and R Studio v1.3 works without having to change ownership. All I have to do is 'apt-get install RStudio-1.3.1093.deb".

Here's my R Studio v1.3.1093 permissions
```
ls -l /home/xxx/.local/share/rstudio/
total 1232
-rw-rw-r-- 1 root root   1201 May  5 20:30 addin_registry
drwxrwxr-x 2 root root   4096 May  5 17:14 bibliography-index
drwxr-xr-x 2 root root   4096 May  5 20:31 client-state
drwxrwxr-x 2 root root   4096 Feb 19  2020 ctx
drwxrwxr-x 3 root root   4096 Feb 19  2020 dictionaries
drwxrwxr-x 2 root root   4096 Feb 19  2020 explorer-cache
-rw-rw-r-- 1 root root 386051 May  5 18:27 history_database
-rw-rw-r-- 1 root root 768031 Jun 28  2020 history_database.1
drwxrwxr-x 2 root root   4096 Jun 28  2020 jobs
drwxrwxr-x 2 root root   4096 May  5 17:58 log
drwxrwxr-x 6 root root   4096 Feb 19  2020 monitored
drwxrwxr-x 2 root root   4096 Jul  3  2020 notebooks
drwxr-xr-x 2 root root   4096 May  5 20:31 pcs
drwxrwxr-x 2 root root   4096 Feb 19  2020 presentation
drwxrwxr-x 2 root root   4096 Feb 19  2020 profiles-cache
drwxrwxr-x 3 root root   4096 Feb 19  2020 projects
drwxrwxr-x 2 root root   4096 Feb 19  2020 projects_settings
-rw-rw-r-- 1 root root      5 May  5 20:31 rmd-outputs
-rw------- 1 root root    229 May  5 20:30 rstudio-desktop.json
drwxrwxr-x 2 root root   4096 Jun 28  2020 rversion-settings
-rw-rw-r-- 1 root root     27 May  5 20:31 saved_source_markers
drwxrwxr-x 3 root root   4096 Feb 19  2020 sessions
drwxrwxr-x 4 root root   4096 May  5 20:31 sources
drwxrwxr-x 2 root root   4096 Jun 28  2020 tutorial
drwx------ 2 root root   4096 Feb 19  2020 viewer-cache

```

**Comment by MyGithubNotYours** [comment]
> @MyGithubNotYours Up till version 1.3 of RStudio Desktop, the directory `/home/xxx/.rstudio-desktop` was used. Starting with 1.4, `/home/xxx/.local/share/rstudio` is the equivalent directory. What are the permissions like in it?

##### `/home/xxx/.rstudio-desktop` 
```
ls -l /home/xxx/.rstudio-desktop/
total 96
-rw-rw-r-- 1 xxx xxx  1201 May  6 20:41 addin_registry
drwxrwxr-x 2 xxx xxx  4096 May  6 20:41 client-state
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 ctx
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 explorer-cache
-rw-rw-r-- 1 xxx xxx 17563 May  5 19:30 history_database
drwxrwxr-x 2 xxx xxx  4096 May  5 19:30 log
drwxrwxr-x 5 xxx xxx  4096 May  5 19:24 monitored
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 notebooks
drwxrwxr-x 2 xxx xxx  4096 May  6 20:41 pcs
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 presentation
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 profiles-cache
drwxrwxr-x 3 xxx xxx  4096 May  5 19:24 projects
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 projects_settings
-rw-rw-r-- 1 xxx xxx     5 May  6 20:41 rmd-outputs
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 rversion-settings
-rw-rw-r-- 1 xxx xxx    27 May  6 20:41 saved_source_markers
drwxrwxr-x 3 xxx xxx  4096 May  5 19:24 sessions
drwxrwxr-x 3 xxx xxx  4096 May  6 20:41 sources
drwxrwxr-x 2 xxx xxx  4096 May  5 19:24 tutorial
drwx------ 2 xxx xxx  4096 May  5 19:24 viewer-cache
```

##### `/home/xxx/.local/share/rstudio/`
```
ls -l /home/xxx/.local/share/rstudio/
total 1232
-rw-rw-r-- 1 root root   1201 May  5 20:30 addin_registry
drwxrwxr-x 2 root root   4096 May  5 17:14 bibliography-index
drwxr-xr-x 2 root root   4096 May  5 20:31 client-state
drwxrwxr-x 2 root root   4096 Feb 19  2020 ctx
drwxrwxr-x 3 root root   4096 Feb 19  2020 dictionaries
drwxrwxr-x 2 root root   4096 Feb 19  2020 explorer-cache
-rw-rw-r-- 1 root root 386051 May  5 18:27 history_database
-rw-rw-r-- 1 root root 768031 Jun 28  2020 history_database.1
drwxrwxr-x 2 root root   4096 Jun 28  2020 jobs
drwxrwxr-x 2 root root   4096 May  5 17:58 log
drwxrwxr-x 6 root root   4096 Feb 19  2020 monitored
drwxrwxr-x 2 root root   4096 Jul  3  2020 notebooks
drwxr-xr-x 2 root root   4096 May  5 20:31 pcs
drwxrwxr-x 2 root root   4096 Feb 19  2020 presentation
drwxrwxr-x 2 root root   4096 Feb 19  2020 profiles-cache
drwxrwxr-x 3 root root   4096 Feb 19  2020 projects
drwxrwxr-x 2 root root   4096 Feb 19  2020 projects_settings
-rw-rw-r-- 1 root root      5 May  5 20:31 rmd-outputs
-rw------- 1 root root    229 May  5 20:30 rstudio-desktop.json
drwxrwxr-x 2 root root   4096 Jun 28  2020 rversion-settings
-rw-rw-r-- 1 root root     27 May  5 20:31 saved_source_markers
drwxrwxr-x 3 root root   4096 Feb 19  2020 sessions
drwxrwxr-x 4 root root   4096 May  5 20:31 sources
drwxrwxr-x 2 root root   4096 Jun 28  2020 tutorial
drwx------ 2 root root   4096 Feb 19  2020 viewer-cache
```

Thanks @ronblum - I've posted the info above. Also, do you have any idea why the environment variable **RSTUDIO_WHICH_R** does not seem to be working for me in v1.4.1106? I'm setting it in the ~/.profile file.
