### ISSUE TITLE
Show Python documentation in Python session

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/rstudio#9311]
When working in RStudio in a `.py` file or in a python code chunk in a Rmd notebook, I think autocompletion would increase efficiency, but it's apparently hard to do: https://github.com/rstudio/reticulate/issues/318. 

My next efficiency tool would be documentation in the editor, but I can't make it work: It seems to work when using python in an R session via {reticulate}: https://github.com/rstudio/rstudio/issues/3114

However, when writing *native* python code, the following doesn't work:

![Screenshot 2021-05-05 at 11 05 42](https://user-images.githubusercontent.com/10477073/117119066-d7f5b780-ad91-11eb-813d-e849f8551a8a.png)

In the help panel, I see `/python/LinearRegression.html not found`. In a python console started from bash or similar, documentation is displayed in the console since at least `help(object)` is valid Python code, e.g. `help(LinearRegression)` with prior import.

My final way to get the arguments would be to jump to the declaration with `Ctrl + [click on python object]`, which works.

Not sure this issue is a {reticulate} or RStudio issue. I also tried hard searching existing issues, but couldn't find this.

## System information
```
RStudio Edition : Desktop
RStudio Version : 1.4.1106
OS Version      :  macOS 10.15.7
R Version       :  4.0.5
{reticulate} Version: 1.20
```

**Comment by fdetsch** [comment]
Same here running RStudio Desktop stable version 1.4.1106 on Ubuntu. My Python version is

```py
> import sys
> print (sys.version)
3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
```

Updating to the latest RStudio Desktop preview version 1.4.1712 and **reticulate** 1.20-9000 makes no difference.

<details>
    <summary>sessionInfo()</summary>

      R version 4.1.0 (2021-05-18)
      Platform: x86_64-pc-linux-gnu (64-bit)
      Running under: Ubuntu 20.04.2 LTS
      
      Matrix products: default
      BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
      LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
      
      locale:
       [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
       [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
       [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
      [10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
      
      attached base packages:
      [1] stats     graphics  grDevices utils     datasets  methods   base     
      
      loaded via a namespace (and not attached):
       [1] compiler_4.1.0    Matrix_1.3-3      tools_4.1.0       Rcpp_1.0.6        reticulate_1.20  
       [6] grid_4.1.0        data.table_1.14.0 jsonlite_1.7.2    cluster_2.1.2     png_0.1-7        
      [11] lattice_0.20-44 

</details>

**Comment by jmbuhr** [comment]
I also get an error as of lately trying to open python help files (with `?` or `F1`). The R session aborts and the R console shows:
`[<some numbers>:ERROR elf_dynamic_array_reader.h:61] tag not found` multiple times. Maybe this helps. I am running RStudio Version 1.4.1668

**Comment by kevinushey** [comment]
@jmbuhr a reproducible example would be helpful.

**Comment by kevinushey** [comment]
Looks like the original issue may be a regression in `reticulate`:

```
> result <- py_run_string("x = 1", local = TRUE)
> print(result)
{}
```

Normally, the result set should include any defined variables. Will take a closer look soon.

**Comment by kevinushey** [comment]
This is unfortunately a regression in 1.4-JR; will submit a PR with as narrowly scoped a fix as possible.

**Comment by kevinushey** [comment]
Actually, because this issue can be resolved in reticulate (without any changes in RStudio) I don't think any code changes for RStudio are necessary.

**Comment by fdetsch** [comment]
In my case, fixed today with `remotes::install_github("rstudio/reticulate")`.

**Comment by jmbuhr** [comment]
This worked for me as well. No more error messages.

**Comment by lorenzwalthert** [comment]
Same for me. Thanks @kevinushey.
