### ISSUE TITLE
Allow more levels of code folding in RStudio

### ISSUE THREAD

**Issue by pozlepster** [rstudio/rstudio#9312]
Hi, 

I would like to propose that you allow more levels of code folding in RStudio. Right now it is possible to fold code between # Section 1---- and # Section 2----.  However, there may be examples where an R script may have multiple sections each with its own subsections. Therefore, it would be useful to allow multiple levels of folding so that one could work only on one subsection and hide all the rest of the code. I am not sure what the best implementation of such code folding would be, but one suggestion would be: 

```
# First level folding ----- 

## Second level folding----- 

### Third level folding ----- 

# First level folding ----- 
```

Thank you for your consideration.

**Comment by pozlepster** [comment]
@ronblum

**Comment by ronblum** [comment]
@pozlepster Thank you for filing it here! And thank you for the code—I was wondering if there was already an option that already exists, but it results in this, which is *not* what you're proposing:

<img width="240" alt="Screen Shot 2021-05-07 at 10 28 09 AM" src="https://user-images.githubusercontent.com/31009952/117464797-0359dd00-af1f-11eb-96b1-9b4876f5c4f3.png">

I'll mark this as an enhancement to consider as part of our development process and review.

**Comment by zykezero** [comment]
Just wanted to tack onto this enhancement with two related comments to folds. I hope it's not rehashed content.

1) exclude code chunks from 'collapse folds'
If we consider folds as hierarchical; and that chunks are the highest level, it'd be nice to have an option to collapse all folds up to the code chunk. Small change but it'd be a nice option.

2) 'end fold marker' 
Folds seem to all collapse down to the next fold. It would be great if there was a way to mark a fold to not collapse down but to just mark the end of a fold. I've found one working example of this in RStudio, when you create a new workbook, the top of the document there is this set of code. And it collapses inwards. The bottom `---` doesn't  collapse down to the first fold section it "folds up".
I know it sounds 'silly' to ask but when all the folds collapse the spacing between each section goes away and the spacing helps me with readability.
```
---
title: "R Notebook"
output: html_notebook
---
```
Before folding
```
#### start fold 1 ####V
# some code
#################^

#### start fold 2 ####V
# some code
#################^
```
After
```
#### start fold 1 ####V
#################^

#### start fold 2 ####V
#################^
```

**Comment by colearendt** [comment]
Agree

**Comment by colearendt** [comment]
Moar folding, stalebot!

**Comment by estroger34** [comment]
Similar issue related to spacing between folded sections had been brought up few years ago here: [https://github.com/rstudio/rstudio/issues/5099](url). Would be great if it could be implemented, because readability of long scripts really suffers with no spacing between folded sections/chunks.

**Comment by BernardoMB** [comment]
End region is needed.

Folding like in c#:

#region 

#endregion <---- We need this

**Comment by seredes** [comment]
I agree, I would also like to have an end region, so we would not need to start another section to "end" the folding. In addition, the hierarchy in folding could be useful just for organizational purposes;
the following:
# Section ####  
could still be rendered in bold in the file structure
while
# Subsection ----
could be rendered in plain text

**Comment by BernardoMB** [comment]
We still need this. Please incorporate this functionality (:
