### ISSUE TITLE
Pasted code in R cell is not reindented

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9314]
**Steps to reproduce:**
* Create an RMarkdown document.
* Copy some R code with at least two levels of indentation, starting from the point within a line in which the letters start - e.g.:
```r
myfun <- function() {
    <start here>another_fun(arg1,
                            arg2)
}
```
* Paste said code in an R cell in the Rmd file.

**Expected behavior:** should auto-adjust the indentation of the pasted text, just like it does when pasting it into an R file.

**Actual behavior:** the code indentation is not adjusted, thus the first line has a different indentation than the following lines.

**Setup:** RStudio 1.4.1118.

**Comment by ronblum** [comment]
Thanks @david-cortes! I can reproduce.

First the behavior in an R script, which I believe is correct:
```
myfun <- function() {
   another_fun(arg1,
               arg2)
}
```

But the following
```
myfun <- function {
          another_fun(arg1,
                            arg2)
}
```

occurs in
- RStudio Server 1.4.16955 on Ubuntu 20.04 and Red Hat 8.3
- RStudio Desktop 1.4.1695 and 1.2.5042 on MacOS 11.3

**Comment by ronblum** [comment]
@kevinushey This is the issue I'm seeing.
@david-cortes Is this what you're running into? Rereading your description, what I'm seeing might be a bit different.

https://user-images.githubusercontent.com/31009952/117711652-85f1cf00-b1a1-11eb-850e-5a68f0080496.mov

**Comment by david-cortes** [comment]
Yes, that's the issue.

**Comment by david-cortes** [comment]
Still relevant.

**Comment by kevinushey** [comment]
If someone wants to investigate, I suspect this is the relevant code:

https://github.com/rstudio/rstudio/blob/main/src/gwt/acesupport/acemode/r_matching_brace_outdent.js

(This is the code responsible for re-indenting braces as they're inserted, which I think would include pasting)
