### ISSUE TITLE
Error in readRDS(dest) : error reading from connection

### ISSUE THREAD

**Issue by Teerapon789** [rstudio/rstudio#9316]
### System details

    RStudio Edition : 
    RStudio Version :  1.4.1106
    OS Version      :  11.3.1 (macOS Big Sur)
    R Version       :  4.0.5

### Steps to reproduce the problem
      Install packages using BiocManager::install()
### Describe the problem in detail
      I have tried to change the CRAN mirror. However, it still has an error in readRDS(dest) : error reading from connection
### Describe the behavior you expected
      I feel that something might interfere to connect to the CRAN server. I would like to fix it as soon as possible

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X
<img width="628" alt="Screenshot 2564-05-09 at 01 01 22" src="https://user-images.githubusercontent.com/65317606/117549197-2f7e7680-b063-11eb-9aa3-da797c7a6807.png">
] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sashajoo** [comment]
I met the same problem and can hardly use BiocManager::install() to install any packages. I almost tried every solution provided on Google and this error keeps coming out.

**Comment by kevinushey** [comment]
Probably https://github.com/Bioconductor/BiocManager/issues/100

**Comment by Teerapon789** [comment]
> Probably [Bioconductor/BiocManager#100](https://github.com/Bioconductor/BiocManager/issues/100)

Yes. I can confirm that it worked for me. Thank you so much
