### ISSUE TITLE
GUI: No reload on theme change

### ISSUE THREAD

**Issue by mavenor** [rstudio/rstudio#9318]
Does not automatically reload when switching between the themes *“Sky”* and *“Modern”*.
Switching to and from *“Classic”* works fine, however.

### System details
```
RStudio Edition : Desktop
RStudio Version : 1.4.1106 (“Tiger Daylily”, 2389bc24)
OS Version      : macOS Big Sur 11.3.1 (20E241)
R Version       : 4.0.5_1 (”Shake and Throw”, 2021-03-31)
```

### Steps to reproduce the problem
1. Fire up an RStudio instance.
2. Ensure that the GUI theme is currently one of *either* the **default** (*“Modern”*), *or* **“Sky”**. (Restart / reload GUI if needed)
3. Change the theme to the other of the two from the **Appearance pane** of **Preferences**.
4. Click **Apply**. (may additionally also close preferences pane by clicking **Okay**)

### Describe the problem in detail
The window fails to reflect the change of preference on clicking **Apply**. This is not true for shifting to and from *“Classic”*, which works fine (from any theme erstwhile selected).
If the GUI is forced to update by selecting **Help** -> **Diagnostics** -> **Reload UI**, however, the changes are then reflected. The same applies to restarting the instance altogether.

### Describe the behaviour you expected
The GUI reloads on theme change, to immediately reflect the user’s preference; just like it does with the **Classic** theme.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
---
### Bonus Screen-grab for reaching This Far Down (😁😝)

https://user-images.githubusercontent.com/69630953/117586110-aaaf5d80-b133-11eb-8d3c-2ecbfe1862c6.mp4

**Comment by ronblum** [comment]
@EccentricHyphus37 Thank you for the raising the issue! I can reproduce it in
- RStudio Desktop 1.4.1707 on MacOS 11.3
- RStudio Server 1.4.1707 on Red Hat 8.3 via Firefox on MacOS 11.3

We'll review it as we continue development of RStudio.
