### ISSUE TITLE
Add ability to "Ctrl+Click" on R6 class to go to definition

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#9324]
Related to #9320 (in the inverse) and potentially #8390

Just like we can "Ctrl+Click" on a function to go to its definition, it would be nice to be able to "Ctrl+Click" on an R6 class / object and go to its class definition.

I.e. 
```
Test <- R6::R6Class("Test", public = list())

Test$new()
```

I want to click on `Test$new()` and go to the definition of `Test` even if it is in a different package, file, etc.

**Comment by ronblum** [comment]
@colearendt I imagine this would apply to <kbd>F1</kbd> as well?

**Comment by colearendt** [comment]
Bump

**Comment by colearendt** [comment]
Ohhh no you don't! This is one of my favorites, stale bot! Don't you want to be able to "go to definition" on an R6 class!? How cool would that be!

**Comment by petrbouchal** [comment]
I think this would be useful for any object - unless I am missing a feature that is already there? (i.e. the equivalent of "Go To Definition" in VS Code). Ideally also bound/bindable to a keyboard shortcut.
