### ISSUE TITLE
debugger barfs on missing arguments

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9328]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1707
    OS Version      : macOS 11.3.1
    R Version       : 4.0.5

### Steps to reproduce the problem

Run the following R code:

```
foo <- function(x) {
   browser()
}

do.call(foo, list(x = quote(expr = )))
```

### Describe the problem in detail

<img width="398" alt="Screen Shot 2021-05-11 at 11 00 44 AM" src="https://user-images.githubusercontent.com/1976582/117863013-24d10680-b248-11eb-8a60-7b1f24acb30f.png">

### Describe the behavior you expected

No error.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Notes

A similar issue:

```
library(lifecycle)
foo <- function(x = deprecated()) {
  force(x)
  browser()
}

foo()
```

<img width="436" alt="Screen Shot 2021-05-11 at 11 19 46 AM" src="https://user-images.githubusercontent.com/1976582/117865417-cc4f3880-b24a-11eb-8483-2a6fbdc8662b.png">

**Comment by ronblum** [comment]
Note (to self): This is a regression from 1.4.1106, as a comparison point.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.4.1711 on MacOS 11.3.
