### ISSUE TITLE
unit test failures re: Python terminal integration

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9331]
### System details

    RStudio Edition : All
    RStudio Version : 1.4.1707
    OS Version      : macOS 11.3.1
    R Version       : 4.0.5

### Steps to reproduce the problem

Run unit tests on macOS; see the following error:

> 11 May 2021 23:09:08 [rsession-kevinushey] ERROR r error 4 (R code execution error) [errormsg: Error in .Call(method, prefName, PACKAGE = "(embedding)") :
  "rs_readUserPref" not available for .Call() for package "(embedding)"
]; OCCURRED AT rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:186; LOGGED FROM: bool rstudio::session::console_process::(anonymous namespace)::augmentTerminalProcessPython(rstudio::session::console_process::ConsoleProcessPtr) src/cpp/session/SessionConsoleProcess.cpp:828

This most likely implies we're trying to run some of this code before we've been able to finish initializing the R sesion.

**Comment by mikebessuille** [comment]
This can be fixed after certification starts.

**Comment by ronblum** [comment]
The failure is only because of when we run them, but if run appropriately, they'd pass—is that correct?

**Comment by kevinushey** [comment]
The failure only occurs because the way we initialize R when running tests differs from "regular" R sessions. In particular, we weren't initializing some bits that are actually required by the tests.

**Comment by kevinushey** [comment]
Note: the associated PR fixing this has been merged, but we're seeing separate unit test failures on the Juliet Rose build machine that we thus far have not been able to diagnose.

**Comment by jmcphers** [comment]
I can't reproduce this and unit tests are now clean, so closing -- feel free to reopen if you see this again.
