### ISSUE TITLE
Switching back and forth in visual markdown editing corrupts dynamic image path

### ISSUE THREAD

**Issue by Waldi73** [rstudio/rstudio#9334]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106 
    OS Version      : Win 10
    R Version       : 4.0.3

### Steps to reproduce the problem
Start with following `RMarkdown`:
````
---
title: "mre"
output: html_document
---

```{r}
path <- 'images/test.png'
```

![myimage](`r path`)
````
Now switch to visual editing mode and back to standard editing mode.

Image insertion code is now :
```
![myimage](%60r%20path%60)
```

### Describe the problem in detail
The modified image insertion code doesn't work anymore

### Describe the behavior you expected
I would expect to get back to : 
```
![myimage](`r path`)
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Waldi73 Thank you for raising this! We'll review this as we continue to developer RStudio.

Reproducible in:
- RStudio Desktop 1.4.1707 on MacOS 11.3
- RStudio Server 1.4.1695 on Red Hat 8.3 via Firefox on MacOS 11.3

**Comment by mikebessuille** [comment]
Why are you not using knitr include graphics https://www.rdocumentation.org/packages/knitr/versions/1.33/topics/include_graphics

**Comment by jjallaire** [comment]
The problem here is that we use pandoc to read the source file, and pandoc doesn't know about the `` `r path` `` syntax so it makes the conversion to `%60r%20path%60`. I don't see an easy way around this problem other than to use conventional R code chunks.
