### ISSUE TITLE
Show memory usage values in MiB, not KiB

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9351]
The Memory Usage Report (Tools -> Memory) shows very exact values in KiB:

![image](https://user-images.githubusercontent.com/470418/118297866-90f37a80-b493-11eb-9b73-67b32520499e.png)

We've received a lot of requests to show these values in MiB instead for better readability.

**Comment by rich-rstudio** [comment]
verified on MacOS desktop Version 1.5.64
