### ISSUE TITLE
Previewing plot PDF export results in R code execution error in Linux desktop

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9352]
### System details

    RStudio Edition : Dektop
    RStudio Version : 1.4.1707
    OS Version      : Red Hat 8.3
    R Version       : 4.0.5

### Steps to reproduce the problem

1. Console: `plot(cars)`
2. Plots: <kbd>Export -> Save as PDF...</kbd>
3. Modal: <kbd>Preview</kbd>

### Describe the problem in detail

Instead of displaying a preview, an R code execution error message appears:
<img width="426" alt="r_exec" src="https://user-images.githubusercontent.com/31009952/118294519-cb1b4700-b4a8-11eb-9cdb-55d73ab7a855.png">

### Describe the behavior you expected

The PDF plot is previewed.

This works in
- RStudio Desktop 1.4.1707 on MacOS 11.3
- RStudio Server 1.4.1707 on Ubuntu 20.04 via Firefox on MacOS 11.3

I haven't tried this on previous versions of RStudio Desktop, or on other Linux environments; let me know if you'd like me to check.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Should see if this is a regression in 1.3 or 1.4 Tiger Dailily.

**Comment by kevinushey** [comment]
I tried but was unable to reproduce with 1.4.1712 on RedHat 8. @ronblum, if you have some time later can we try to screen share and explore the issue a bit more?

**Comment by ronblum** [comment]
@kevinushey I can no longer reproduce the bug. It went from consistently happening to not happening at all. I'll close this and reopen if it happens again.
