### ISSUE TITLE
Ability to reorder launched jobs

### ISSUE THREAD

**Issue by mike-lawrence** [rstudio/rstudio#9362]
I'm currently using runJobsScript to run a parent function that in turn calls addJob to show individual progess on sub-functions, and at present the parent appears first then the child jobs are added on top. It would be nice if there were a way to set the order of jobs in the jobs pane.

**Comment by ronblum** [comment]
@mike-lawrence Thank you for the suggestion! We'll review it as we continue to develop RStudio.

**Comment by jmcphers** [comment]
We did think about this scenario when originally putting together the feature, and had the idea (though it wasn't implemented) for a job to have a concept of a parent (e.g., for subtasks). I think some treatment of grouping or nesting automatically based on a parent job ID would ultimately be less complicated than ordering hints.

**Comment by mike-lawrence** [comment]
> I think some treatment of grouping or nesting automatically based on a parent job ID

Yup, that'd work for my use-case!

**Comment by colearendt** [comment]
I like this idea a lot!

**Comment by colearendt** [comment]
🎉
