### ISSUE TITLE
View() crashes for data frames with incorrect row.names

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rstudio#9364]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1106
    OS Version      : Fedora 34
    R Version       : 4.0.5

### Steps to reproduce the problem

```r
# row.names larger than the data frame
attr(iris, "row.names") <- seq_len(nrow(iris)+1)
# try to view
View(iris)
```

### Describe the problem in detail

RStudio crashes. This is the backtrace:

```
Truncated backtrace:
Thread no. 1 (10 frames)
 #0 Rf_length at ../../src/include/Rinlinedfuns.h:523
 #1 rstudio::r::sexp::length at /usr/src/debug/rstudio-1.4.1106-1.fc33.x86_64/src/cpp/r/RSexp.cpp:640
 #2 rstudio::session::modules::data::viewer::(anonymous namespace)::getData at /usr/src/debug/rstudio-1.4.1106-1.fc33.x86_64/src/cpp/session/modules/data/DataViewer.cpp:700
 #3 rstudio::session::modules::data::viewer::(anonymous namespace)::getGridData at /usr/src/debug/rstudio-1.4.1106-1.fc33.x86_64/src/cpp/session/modules/data/DataViewer.cpp:798
 #4 boost::detail::function::void_function_invoker2<rstudio::core::Error (*)(rstudio::core::http::Request const&, rstudio::core::http::Response*), void, rstudio::core::http::Request const&, rstudio::core::http::Response*>::invoke at /usr/include/boost/function/function_template.hpp:117
 #5 boost::function2<void, rstudio::core::http::Request const&, rstudio::core::http::Response*>::operator() at /usr/include/boost/function/function_template.hpp:763
 #6 rstudio::core::http::(anonymous namespace)::runSynchronousHandler at /usr/src/debug/rstudio-1.4.1106-1.fc33.x86_64/src/cpp/core/http/UriHandler.cpp:76
 #7 rstudio::core::http::visitHandler(boost::variant<boost::function<void (rstudio::core::http::Request const&, boost::function<void (rstudio::core::http::Response*)> const&)>, boost::function<bool (rstudio::core::http::Request const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, boost::function<void (rstudio::core::http::Response*)> const&)> > const&, rstudio::core::http::Request const&, boost::function<void (rstudio::core::http::Response*)> const&) at /usr/include/boost/function/function_template.hpp:763
 #8 rstudio::session::http_methods::handleConnection at /usr/include/boost/optional/detail/optional_aligned_storage.hpp:40
 #9 rstudio::session::http_methods::waitForMethod(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<void ()> const&, boost::function<bool ()> const&, rstudio::core::json::JsonRpcRequest*) at /usr/src/debug/rstudio-1.4.1106-1.fc33.x86_64/src/cpp/session/SessionHttpMethods.cpp:536
```

### Describe the behavior you expected

RStudio should handle this situation properly (e.g., showing missing values at such positions, as R does if you print the data frame).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Enchufa2 Thank you for raising this issue! We'll review it as we continue to develop RStudio.

Reproducible in
- RStudio Desktop 1.4.1707 on MacOS 11.3 and Red Hat 8.3
- RStudio Desktop 1.2.5042 on MacOS 11.3
- RStudio Server 1.4.1707 on Ubuntu 20.04

**Comment by kevinushey** [comment]
It's also possible to get stuck in an ugly crash loop where the IDE crashes every time you start up (as it tries to open and re-render the data viewer tab, and crashes in the process).

<img width="787" alt="Screen Shot 2021-05-17 at 11 18 42 AM" src="https://user-images.githubusercontent.com/1976582/118537297-a53caf00-b701-11eb-987f-385de0f84acf.png">

**Comment by rich-rstudio** [comment]
verified on Version 1.5.76
