### ISSUE TITLE
Cursor Low Refresh Rate in RStudio (Fixed by turning off GSync for RStudio in Nvidia Control Panel)

### ISSUE THREAD

**Issue by davidnield** [rstudio/rstudio#9367]
## System Details
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)
RStudio version 1.4.1106

I noticed my cursor had a noticeably lower refresh rate (seemed to drag across the screen) when RStudio was the program in focus relative to using any other program (e.g. even just alt-tabbing quickly to Desktop, File Explorer, Chrome).

Attempted to troubleshoot by restarting RStudio, restarting my computer, updating RStudio to the latest version (then repeating the restarting steps), explicitly setting the Rendering Engine in Global Options > General > Advanced > Rendering engine to "Desktop OpenGL", and turning off "Use GPU blacklist" and "Use GPU driver bug workarounds" then repeating restarting steps. None worked.

Found this issue (https://github.com/microsoft/terminal/issues/649) on Microsoft Terminal that describes the exact behavior I was experiencing with the hardware/software that I use (Windows, high refresh rate monitor that uses GSync) and the solution was adding Terminal to NVidia Control Panel and turning off GSync for Terminal in Program-specific settings. I used the same solution from that bug and it resolved my issue.

## Solution

```
1. Open NVidia Control Panel.
2. On the left, select Manage 3D Settings.
3. Select the Program Settings tab.
4. You will have to add the RStudio app to the list of programs in the drop down.
5. One of the options in the box should show G-Sync is enabled. Disable it.
6. Apply changes.
```

Sharing in case others experience this issue and in case there is something RStudio can do to solve this bug without users with GSync monitors needing to implement this workaround.

Extra context about GSync: it's an NVidia software for NVidia GPUs and GSync compatible high refresh rate monitors designed primarily for gaming that allows the monitor to synchronize the monitor's refresh rate to the frames per second you are actually getting in a program/game, designed to make the programs visually smoother in cases where your PC is not able to achieve as many frames per second in the program as your monitor is able to output in its refresh rate (e.g. if you have a 144 Hz monitor with GSync enabled and you're using a program where you are only achieving 90 frames per second, the monitor will adjust its refresh rate down to 90 Hz). I am by no means a developer or engineer but I know that FPS is sometimes tied to tick rates in games, so I wonder if RStudio's rendering refresh rate is fixed to some low rate and is tricking GSync into thinking that needs to adjusting its refresh rate downwards to match it.

**Comment by ronblum** [comment]
@davidnield Thank you for raising this! We do occasionally run into issues with graphics drivers, etc. I'll mark this for review to see if there's something that can be changed in RStudio, or if the solution you provided is what we have to rely on.

**Comment by ronblum** [comment]
Update: As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. If you're willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.0+548.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by ronblum** [comment]
Closing this as fixed by Electron. If you try out builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) and the issue persists, please let us know!
