### ISSUE TITLE
Debug hyperlinks to source files fail to open the file

### ISSUE THREAD

**Issue by aljabadi** [rstudio/rstudio#9372]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : macOS Big Sur 11.2.3
    R Version       : 4.0.5

### Steps to reproduce the problem

In a package development environment:

* Add a `stop()` to a source code
* Run a command that would encounter that `stop()`
* In RStudio IDE look at the call stack and try to click on the hyperlink to the source file

### Describe the problem in detail

The hyperlink seems to be misspecified. This issue is new and did not happen with older RStudio version I had.

### Describe the behavior you expected

Open the source file containing the bug as hyperlinked in the call stack

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report. Could you by any chance provide some more detail? A screencast would be especially helpful just to be sure we understand the issue you're seeing.

**Comment by aljabadi** [comment]
This behaviour is not reproducing anymore. I'm going to assume it was a local issue that is now fixed. Thanks.
