### ISSUE TITLE
Code completion bug: column names not shown if namespace is stated

### ISSUE THREAD

**Issue by kristian-bak** [rstudio/rstudio#9374]
Hello,

I noticed the TAB and code completion feature does not show column names if namespace is used, for instance dplyr::filter().  Could you please check if it is the case for you as well?

Thanks

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : Windows 10
    R Version       : 4.1.0

### Steps to reproduce the problem

```
library(dplyr)

## Pressing tab in filter() produces a drop down menu with column names
iris %>% filter()

## Pressing tab in filter() does not provide any column names
iris %>% dplyr::filter()
```

### Describe the problem in detail
It works without namespace:

![example - code completion works](https://user-images.githubusercontent.com/60940231/118828643-bc280080-b8bd-11eb-8962-0e99efb43328.png)

But it does not work with namespace:
![example - code completion does not work](https://user-images.githubusercontent.com/60940231/118829019-1032e500-b8be-11eb-9c19-5cef88d68865.png)

This also applies to other functions such as select and mutate. 

### Describe the behavior you expected

I would expect auto completion would work regardless of stating the namespace or not. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kristian-bak Thank you for raising this! I can reproduce this in RStudio Desktop on MacOS 11.3 and Red Hat .3, as well. We'll review this as we continue development of RStudio.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+301 on MacOS 13.2.
