### ISSUE TITLE
Python instances not discoverable on Windows if an instance is already chosen

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9379]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1712-1
    OS Version      : Windows 10
    R Version       : 4.1.0

### Steps to reproduce the problem

If a Python instance isn't already chosen:
1. Tools -> Global Options -> Python -> Select
2. Select a Python instance to use
3. OK

Then:

4. Tools -> Global Options -> Python -> Select

### Describe the problem in detail

After step 4, no Python instances are discovered. An empty window pops up:
<img width="154" alt="python_path" src="https://user-images.githubusercontent.com/31009952/119004386-838b3400-b95c-11eb-8adb-e89be2d4a528.PNG">

### Describe the behavior you expected

I installed the Python instances in their default locations. They should be discoverable.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Tested with RStudio Desktop 1.4.1716 on Windows 10, but it doesn't work.

I have three instances of Python installed:
- Python 3.8 using the default (user directory): `C:\Users\RonBl\AppData\Local\Programs\Python\Python38`
- Python 3.9 using custom system installation: `C:\Program Files\Python39`
- Python 2.7 in the root directory: `C:\Python27`

Python only shows up if at least one of these is added to the PATH. 

1) If only Python 2.7 (root) is added to PATH, only it shows up.
2) If only Python 3.8 (system) is added to PATH, both 2.7 and 3.8 show up, but 3.9.
3) If only Python 3.9 (user) is added to PATH, all three show up.

**Comment by kevinushey** [comment]
Note: most likely cause appears to be the set of discovered Python versions being converted to a Javascript map rather than array.

<img width="818" alt="Screen Shot 2021-05-24 at 2 43 49 PM" src="https://user-images.githubusercontent.com/1976582/119411751-bf493500-bc9f-11eb-94b6-73593539813c.png">

Also: need to ensure that Python installations in C:\Program Files are discovered as well.

**Comment by ronblum** [comment]
Verified that this works in RStudio Desktop 1.4.1717 on Windows 10, even when no Python executables are in the path.
