### ISSUE TITLE
Code completion: column names not shown when using native pipe

### ISSUE THREAD

**Issue by long39ng** [rstudio/rstudio#9385]
I've noticed that code completions for column names within function chains are only provided when using the magrittr pipe operator, but not with the new native pipe. Could you please check if this is reproducible?

### System details

```
RStudio Edition : Desktop
RStudio Version : 1.4.1714
R Version       : 4.1.0
```

### Steps to reproduce the problem

```
## Pressing tab in select() produces a drop down menu with column names
mtcars %>% select()

## Pressing tab in select() does not provide any column names
mtcars |> select()
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by rich-rstudio** [comment]
verified on Version 1.5.64

**Comment by luciorq** [comment]
Looks like it has been solved on daily builds, at least since __Daily Version 2021-08.0.291__.

![image](https://user-images.githubusercontent.com/22479186/129950402-0c4901aa-e1d6-41e1-a215-e6035b3ad0b5.png)

Tested on both RStudio Desktop and Server.
