### ISSUE TITLE
Console window won't scroll properly, and form-feed suppresses subsequent output

### ISSUE THREAD

**Issue by chernavsky** [rstudio/rstudio#9389]
In past versions of RStudio, I would always include this statement toward the top of my scripts: `cat('\f')` .  This had the effect of clearing the console pane by sending a form-feed to it.  In the current preview version of RStudio (1.4.1714), the command _does_ clear the console, but it _also_ acts to suppress any subsequent output.

Another issue (possibly related?) is that the output doesn't scroll properly during the execution of the script.  Instead, the output runs off the bottom of the console pane and disappears.  It only appears again when the script terminates.  Here is a reproducible example:

```
i <- 1
while (i < 1000)
{
  cat(i, " ")
  Sys.sleep(0.01)
  i <- i + 1
}
```

### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.4.1714
    OS Version      :  Windows 10 64-bit, ver. 20H2 build 19042.964
    R Version       :  4.1.0 (2021-05-18)

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [N/A ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
-

**Comment by jmcphers** [comment]
Does this reproduce if you uncheck `Tools -> Global Options -> Console -> Limit visible console output` and restart?

**Comment by chernavsky** [comment]
OK, that fixed both issues I had described.  Thank you.  Did the default change in RStudio 1.4.1714?  I've never made changes to that setting in the past.

**Comment by jmcphers** [comment]
It did, but we are going to change it back before we release due to this issue and several like it. See https://github.com/rstudio/rstudio/pull/9384.
