### ISSUE TITLE
Animation that scrolls between files is very slow

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9391]
**Steps to reproduce:**
* Open ~30 files or so in RStudio.
* Switch from some file near the beginning of the list to a file near the end of the list through the arrows button at the top right corner of the editor pane.

**Expected behavior:** should quickly switch between files.

**Actual behavior:** switching takes a long time due to the animation that scrolls between files. Can get very annoying when the number of opened files is larger.

**Comment by gtritchie** [comment]
Does it happen if you select "Reduce User Interface Animations" in Global Options/Accessibility?

**Comment by david-cortes** [comment]
That solves it, although I'd suggest to make it a default, at least for this particular animation.

**Comment by mikebessuille** [comment]
Closing as this is stale and there's an option to cover this situation.
