### ISSUE TITLE
RStudio crashes when using mongolite

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#9397]
Code of ours that uses the `mongolite` package works on an R console, but crashes RStudio (at least server). Below are detailed repro steps, including a mongo server setup on a ubuntu machine (via docker - but that isn't necessary for the crash repro).

1) Setup a mongo server:
```bash
sudo docker pull mongo
sudo docker run -p "27017:27017" -d mongo mongod --bind_ip_all

sudo docker ps     # -> check image name in NAMES column
sudo docker exec -it <NAME> bash
mongo
db.createUser({user: "user", pwd: "1234",roles: [ { role: "userAdminAnyDatabase", "db":"admin"} ] })
```
Screen capture:

https://user-images.githubusercontent.com/73080/119265423-573b1600-bbef-11eb-94f6-97f1c4c64154.mp4

(Embedded videos seem not to be working in some browsers, here's a direct url: `https://user-images.githubusercontent.com/73080/119265423-573b1600-bbef-11eb-94f6-97f1c4c64154.mp4`

2) In the RStudio console:

```r
library(mongolite)
mm <- mongo(collection="test", url="mongodb://user:1234@<mongo machince's ip>:27017/test")
```
Wait a few seconds, perhaps press Enter once or twice, and RStudio will crash.
Screen capture:

https://user-images.githubusercontent.com/73080/119267332-d3852780-bbf6-11eb-81cb-cd59b19fc423.mp4

(`https://user-images.githubusercontent.com/73080/119267332-d3852780-bbf6-11eb-81cb-cd59b19fc423.mp4`)

### System details

    RStudio Edition : Server
    RStudio Version :  1.4.1103
    OS Version      : Ubuntu 18
    R Version       : 3.4

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
**** I tried to run `rstudio-server run-diagnostics`, but it seems to not work.

- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by OfekShilon** [comment]
We were able to take a crash stack trace. Our RStudio is a stripped binary package, so I'm not sure how helpful it would be - but here it is anyway:
```
             Stack trace of thread 7412:
                #0  0x00007f2b64c0af47 raise (libc.so.6)
                #1  0x00007f2b64c0c8b1 abort (libc.so.6)
                #2  0x00007f2b64c55907 n/a (libc.so.6)
                #3  0x00007f2b64c5c97a n/a (libc.so.6)
                #4  0x00007f2b64c63fd0 cfree (libc.so.6)
                #5  0x00007f2b65697c0c _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm (libstdc++.so.6)
                #6  0x00007f2b6569894b _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm (libstdc++.so.6)
                #7  0x0000555eba37338e n/a (rsession)
                #8  0x0000555eba35dcde n/a (rsession)
                #9  0x0000555eba35dd63 n/a (rsession)
                #10 0x0000555eba35cad7 n/a (rsession)
                #11 0x0000555eb9c43f1d n/a (rsession)
                #12 0x0000555eb9c49bce n/a (rsession)
                #13 0x0000555eb9baaea3 n/a (rsession)
                #14 0x0000555eba4b835e n/a (rsession)
                #15 0x00007f2b670deb28 Rf_ReplIteration (libR.so)
                #16 0x00007f2b670deeb1 R_ReplConsole (libR.so)
                #17 0x00007f2b670def48 run_Rmainloop (libR.so)
                #18 0x0000555eba4d98e6 n/a (rsession)
                #19 0x0000555eba4b0d22 n/a (rsession)
                #20 0x0000555eb9b50dca n/a (rsession)
                #21 0x00007f2b64bedb97 __libc_start_main (libc.so.6)
                #22 0x0000555eb9b77f09 n/a (rsession)
```

**Comment by OfekShilon** [comment]
@ronblum  are you guys able to reproduce?  This one had forced our team to go back to using inferior R IDEs...  hopefully temporarily   :)

**Comment by jmcphers** [comment]
Thank you for the very thorough and self-contained repro steps and for including a stack trace. It looks like the crash is coming from `rsession` so we'll try to reproduce and take a look.

**Comment by kevinushey** [comment]
Unfortunately, I wasn't able to reproduce (either on macOS or on Ubuntu 20.04), although this was using a development server based off of 1.5 rather than 1.4.

**Comment by OfekShilon** [comment]
Would a core dump be helpful? (again. of stripped binaries)

**Comment by OfekShilon** [comment]
We discovered that the repro is machine dependent. I.e, starting the mongo docker on some machines does _not_ crash RStudio.

**Comment by OfekShilon** [comment]
We upgraded to a more recent version of mongolite and can no longer reproduce this...   Sorry for the trouble, I'm closing the bug.

**Comment by ronblum** [comment]
@OfekShilon I'm glad to hear upgrading mongolite resolved the issue. And it's no trouble at all—thank you for letting us know it all worked out!
