### ISSUE TITLE
Qt scripts to build from source not working + proposed fix for Ubuntu

### ISSUE THREAD

**Issue by pachamaltese** [rstudio/rstudio#9398]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4 (GitHub)
    OS Version      :  Ubuntu 20.04
    R Version       :  4.1.0

### Steps to reproduce the problem

```
git clone https://github.com/pachamaltese/rstudio
cd rstudio/dependencies/linux/
sudo su
./install-qt-linux
```

### Describe the problem in detail

The script fails on line 33 (https://github.com/pachamaltese/rstudio/blob/main/dependencies/linux/install-qt-linux#L33), after it can  find `install-qt.sh`.

### My proposed solution

After a few tries, this one liner:
```
sudo apt-get install qt5-default qtcreator qtbase5-examples qtwebengine5-dev libqtsensors5-dev libqt5svg5-dev libqt5xmlpatterns5-dev
```

allows me to run cmake and proceed building RStudio with a little change (ref https://community.rstudio.com/t/build-issue-did-not-find-supported-qt-sdk/40621/2):
```
qmake -v
cmake .. -DRSTUDIO_TARGET=Desktop -DRSTUDIO_PACKAGE_BUILD=1 -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake
```

This Qt setup could be added to the documentation, as it just works.

But, this needs to install libicu60 as in https://askubuntu.com/a/1331914

### Describe the behavior you expected

It should have installed Qt 5.12.8.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The `install-qt.sh` script is located here:

```
$ ag -g "install-qt.sh"
dependencies/common/install-qt.sh
```

so I suspect the issue is just that we aren't changing the working directory as appropriate.

**Comment by kevinushey** [comment]
Compare with how the script is invoked on macOS:

```
dependencies/osx/install-qt-macos
50:   ../common/install-qt.sh --version $QT_VERSION --directory ${QT_SDK_DIR} \
```

However, we munge the paths a bit in our Docker scripts so it may be more complicated to fix than at first glance.

(either way, Qt will be going away in 1.5 so this isn't particularly high priority)

**Comment by jmcphers** [comment]
This will shortly become irrelevant as @kevinushey notes, so we don't plan to work on it (but if you figure it out, we'd accept a PR to make the paths correct!).
