### ISSUE TITLE
End key does not jump to the end inside LaTeX in visual editor

### ISSUE THREAD

**Issue by ArtificialTruth** [rstudio/rstudio#9406]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1120
    OS Version      :  Windows 10
    R Version       :  4.0.3

### Steps to reproduce the problem
0. Open RMarkdown document in visual editor
1. Create inline LaTeX using $$
2. Press End key on keyboard
3. Cursor jumps to end of line, then immidatly back at the same point
![Inl6YHAA4N](https://user-images.githubusercontent.com/3297866/119476299-389f6100-bd4e-11eb-93ea-3953803f4398.gif)

### Describe the problem in detail
The problem does not occur in "Display math" regions ($$ <LaTeX here> $$)

### Describe the behavior you expected
The End key will make the "cursor" jump to the end of the line.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ArtificialTruth Thank you for the bug report! We'll review it as we continue to develop RStudio.

**Comment by jjallaire** [comment]
Addressed here: https://github.com/rstudio/rstudio/commit/560c6ed45e14980a0b0ed6b8fc557b7ad2417d6b

**Comment by valerie-rstudio** [comment]
@ronblum - I can't seem to repro the original issue now on 1.4.1717 on Windows 10. Since you were able to repro the issue, could you take a look and verify this is fixed?

**Comment by mikebessuille** [comment]
manual test only

**Comment by ronblum** [comment]
Verified that this works in RStudio Desktop 2022.01.0-daily+290 on Windows 10.

1) When in LaTeX math, both inline and display, <kbd>Home</kbd> and </kbd>End</kbd> move to start and end of LaTeX section.
2) When on the same line as inline math, but not in the math section, the keys go to start and end of the line.
