### ISSUE TITLE
Make native pipe toggle a project-level setting

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rstudio#9409]
It will be some time before most of the R community is updated to the new 4.1.0 version and so even if an user has R 4.1.0 and wants to use the native pipe for many applications, it's very likely that in some projects they might need to revert back to magrittr, such as code that needs to be compatible with older versions of R or collaborations with people running old versions. 

Right now the toggle to use magrittr or native pipe with Ctr + Shift + M is a global option, but for the reasons above, it might make sense being able to change it from the default on a per-project basis.

**Comment by ronblum** [comment]
@eliocamp Thank you for the suggestion! We'll review it as we continue to develop RStudio.

**Comment by colearendt** [comment]
Agree

**Comment by ShixiangWang** [comment]
I also encounter such issue. Currently, the RStudio support setting native pipe in "Global Options", how about adding an option to "Project Options" to enable/disable native pipe operator?

**Comment by jgutman** [comment]
One concern is that having both a project level option and a global level option for the pipe operator could lead to confusion, as we've with the tab width setting which is configurable in both settings. 

We could 1) remove the global option entirely and have it only be a project level option -- however that would leave no way to configure the operator outside of the context of a project

Or 2) change the global preference to have 3 options: always use the native pipe, never use the native pipe (always use magrittr) and add a third choice, use the native pipe only when running R 4.1+. This would seem to meet the use case of supporting projects that use older code -- if I switch the R version used by RStudio in order to work on a project that uses R 3.6, for example, my pipe operator would automatically switch to a magrittr pipe.

Does that meet the need?

**Comment by eliocamp** [comment]
I have R 4.1+ installed, but I might be collaborating with some who doesn't, or developing to deploy code somewhere with an old version, or writing a package and trying to keep the R version dependency as low as possible. 

Why would there be confusion? Right now there are several options that can be set up both at the global and project level. Dictionary and saving / restoring .RData, for example.

**Comment by ShixiangWang** [comment]
> One concern is that having both a project level option and a global level option for the pipe operator could lead to confusion, as we've with the tab width setting which is configurable in both settings.
> 
> We could 1) remove the global option entirely and have it only be a project level option -- however that would leave no way to configure the operator outside of the context of a project
> 
> Or 2) change the global preference to have 3 options: always use the native pipe, never use the native pipe (always use magrittr) and add a third choice, use the native pipe only when running R 4.1+. This would seem to meet the use case of supporting projects that use older code -- if I switch the R version used by RStudio in order to work on a project that uses R 3.6, for example, my pipe operator would automatically switch to a magrittr pipe.
> 
> Does that meet the need?

The way 2) seems sound.

**Comment by kevinushey** [comment]
> 2) change the global preference to have 3 options: always use the native pipe, never use the native pipe (always use magrittr) and add a third choice, use the native pipe only when running R 4.1+.

This sounds like a good approach to me as well.

As a separate issue, it would be useful if we had some way of indicating to the user whether a particular preference they were looking at in the Global Options pane had a corresponding project-specific override... but I'm not sure how to best communicate that given the limited space in our dialog. The closest analogue we have is the

```
View All Prefs
```

command, but it's unlikely the average user is going to know about that.

Maybe worth filing for posterity anyhow?

**Comment by jgutman** [comment]
Thanks all for the feedback -- this feature has been added, and can be previewed in the latest dailies for 2022.06.0 at https://dailies.rstudio.com/

**Comment by ShixiangWang** [comment]
@jgutman Thanks, I found that on Project options

![image](https://user-images.githubusercontent.com/25057508/165211246-a06dee4e-7540-46e4-a049-15eaa3623bf2.png)

**Comment by jgutman** [comment]
As of 2022.06.0-daily+374, failure point referenced above now passes, but please feel free to test further

**Comment by ronblum** [comment]
Fix verified in RStudio Desktop 2022.06.0-daily+406 on MacOS 12.4.
