### ISSUE TITLE
Colored text for jobRunScript output

### ISSUE THREAD

**Issue by mike-lawrence** [rstudio/rstudio#9411]
I have a script that uses the crayon package to color text, and when sourced in the console I get the expected coloring of cat() outputs, but when using `rstudioapi::jobRunScript()` the job's output isn't colored. For example:
```r
tmp= tempfile()
write('cat(crayon::red("hello"))',tmp)
rstudioapi::jobRunScript(tmp)
```

**Comment by ronblum** [comment]
@mike-lawrence Thank you for raising this! We'll review it as part of our ongoing RStudio development.

**Comment by mike-lawrence** [comment]
Somewhat tangential, but I also notice that the content of the jobs output pane is far uglier than the equivalent in the terminal that comes with ubuntu. I'm generating progress bars and while this is what it looks like in the ubuntu terminal:
![Screenshot from 2021-06-08 21-45-10](https://user-images.githubusercontent.com/150781/121275402-fd02ac00-c8a2-11eb-9d2c-e8977dc346e0.png)

While this is what I get in the Jobs output pane:
![Screenshot from 2021-06-08 21-45-46](https://user-images.githubusercontent.com/150781/121275430-0c81f500-c8a3-11eb-913c-f395ac80f079.png)

(code to generate:
```R
jobID = rstudioapi::jobAdd('test')
bar_width = 80 - 2
warmup_width = floor(bar_width/2)
sampling_width = bar_width - warmup_width
bar = paste0(
	'\U00C ' #scroll to next page (hack bc the clear screen and cursor set control sequences don't work)
	, strrep('\U2592',warmup_width) #lighter shade block
	, strrep('\U2593',sampling_width) #darker shade block
	, '\n'
	, '['
	, strrep('\U2588',warmup_width-1) #full block character
	, '\U258B' #partial block character (full set: c('\U258F','\U258E','\U258D','\U258C','\U258B','\U258A','\U2589','\U2588') ) 
	, strrep(' ',sampling_width)
	, ']\n'
)
cat(bar)
rstudioapi::jobAddOutput(jobID,bar)
```

**Comment by mike-lawrence** [comment]
Ah, yes, when I belatedly just now tried simply using control codes to do the colors manually, they come out fine, so this is a crayon issue rather than an rstudio issue. Thanks for helping work this out!

**Comment by mike-lawrence** [comment]
Note,[ made an issue for this on the crayon repo](https://github.com/r-lib/crayon/issues/121), including code demonstrating it's selective to jobs launched with `rstudioapi::jobRunScript()` (though still a crayon issue since explicit color codes work fine).
