### ISSUE TITLE
PackagesPreferencePane may miss when repo changed to URL

### ISSUE THREAD

**Issue by ca-scribner** [rstudio/rstudio#9413]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

I have not produced this in RStudio but instead inferred the possible bug from the code

### Describe the problem in detail

`rstudio/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java` detects whether a cran repo is changed from a standard repo to a URL-defined repo through 
```
boolean cranRepoChangedToUrl = cranRepoChanged &&
                                                         mirrorTextValue.startsWith("http");
```
but the form to enter the repo name/URL in the UI does not enforce that URL-based repos must start with "http".  Unless something else is going on that I'm missing, this will only fire on a subset of the desired cases.

### Describe the behavior you expected

All URL-based cran repos be identified and handled as URL-based and not standard named repos

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ca-scribner Thank you! We'll review this as we continue to develop RStudio

**Comment by mikebessuille** [comment]
Per kevin, this is likely a rare occurence.
