### ISSUE TITLE
Start new session with specific R version

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rstudio#9415]
I frequently need to change R versions (e.g., to work on a project started with an earlier R version or to test a package on older or devel versions of R). Currently, to change R versions, I need to click Tools → Global options… → R version [Change…] → select the version [OK] → [OK]→ Session → New Session…

This is tedious, and I then need to switch the option back to my main R version. It would be really helpful if there were an option in the Session menu to "Start New Session with a Specific Version of R"

**Comment by ronblum** [comment]
@bwiernik Thank you for the suggestion! We'll review it as we continue to develop RStudio.

**Comment by colearendt** [comment]
Bump!

**Comment by colearendt** [comment]
I must haz the specific R version, Stalebot!
