### ISSUE TITLE
Duplicate elementIDs caused by r_logo.svg

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9417]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4+
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
Load RStudio Server in browser, and run an accessibility evaluation using axe devtools.

### Describe the problem in detail
Duplicate element IDs (gradientFill-1 and gradientFill-2). These are hardcoded into the r_logo.svg used in multiple locations.

One potential fix is to to use a tool like this to inject the SVGs into the page; this process is supposed to fix duplicate IDs (though I haven't tested it): https://github.com/iconfu/svg-inject

### Describe the behavior you expected
No duplicate element IDs; standard accessibility requirement (and also requirement of valid HTML). Not worth fixing for 1.4, but definitely want to fix for 1.5.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
what are the actual accessibility ramifications of this?  The logo isn't something that would be tabbed to or spoken by a screen reader anyway.  How will this break accessibility?

**Comment by gtritchie** [comment]
Short answer:

I'd be fine with bumping this to a future milestone, but want to keep it active as having us produce valid HTML is important for basic accessibility.

Long answer:

Just because you can't tab to it doesn't mean it isn't going to be read by a screen reader. You can navigate the entire UI with a screen reader, not just parts that get keyboard focus.

I have experienced cases (in RStudio) where duplicate element IDs confused, and in some cases crashed, screen readers and/or accessibility testing tools. In general, as soon as we let duplicate IDs creep back in we're losing ground and making it easier to ignore more duplicate IDs in the future. Also, I will have to document this in the VPAT as a known problem and being able to refer back to an issue is helpful in demonstrating that we intend to fix it at some point.

In this case, there's no accessibility information on the image so it will indeed be ignored. That's a potential accessibility issue, too. Anytime a graphic is communicating information (non-cosmetic) then have to ensure the same information is communicated to screen reader users. We show the R version right next to it in text form, and that IS correctly read by screen readers (just tried) so the image is indeed cosmetic and can remain invisible.

**Comment by gtritchie** [comment]
Closing this. Although the duplicate IDs does makes this invalid HTML, it does not cause any known accessibility issues. Duplicate IDs can be a problem if they are on interactive controls, and/or referenced via aria properties, but that isn't the case here.

Also, there is talk of potentially removing this criteria in a future WCAG, though very controversial.

https://github.com/w3c/wcag/issues/2820
