### ISSUE TITLE
R version 4.1.0 runs slowly inside RStudio version 1.4.1717 on M1 Mac

### ISSUE THREAD

**Issue by awcm0n** [rstudio/rstudio#9418]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1717 "Juliet Rose" (df86b69e, 2021-05-24)
    OS Version      :  11.3.1 (20E241)
    R Version       :  4.1.0 Patched (2021-05-23 r80364)

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/6549829/diagnostics-report.txt)

### Describe the problem in detail
Execution of an R script slows to a crawl at seemingly random points within a chunk. For example, executing a `case_when` statement might take minutes instead of a fraction of a second.
  
Resetting RStudio by executing the following commands in Terminal seems to fix the issue temporarily because the script runs without slowdowns after a reset:

```
defaults delete com.rstudio.desktop
rm -Rf ~/.local/share/rstudio
rm -Rf ~/.config/rstudio
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@awcm0n Thank you for raising this! To help reproduce the issue, can you provide sample code that causes the issue?

**Comment by awcm0n** [comment]
> @awcm0n Thank you for raising this! To help reproduce the issue, can you provide sample code that causes the issue? Also, does the same code result in the problem when run in the console instead of an R Markdown of Notebook?

This issue happens frequently, but too inconsistently to provide a reproducible example. Code execution slows down at seemingly random points in a code chunk. However, after two successive force-quits of RStudio, the same code chunk might run flawlessly.

The slow-down issue does not occur when I run code in the R desktop application.

**Comment by kevinushey** [comment]
Without a reproducible example there is not much we can do.

**Comment by awcm0n** [comment]
> Without a reproducible example there is not much we can do.

After further evaluation, I'm finding that the intermittent slow-down not only affects code execution but other RStudio Desktop behaviors such as opening or saving source files, quitting RStudio.
