### ISSUE TITLE
Allow changing of global options with option() for "surround selection on text insertion" and "insert matching parens/quotes"

### ISSUE THREAD

**Issue by systemnova** [rstudio/rstudio#9440]
I find the surround selection option makes it more likely that i make errors while using RStudio. To solve I turn off the option in the dialogue menu, however it would be great if this was one of the global options that could be set with options()?

Allow changing of global options with option() for "surround selection on text insertion" and "insert matching parens/quotes".

Also would be good to be able to set "editor content width" via script .

**Comment by ronblum** [comment]
@systemnova Thank you for the suggestion! However, do `readRStudioPreference` and `writeRStudioPreference` address what you're looking for? For example: 

```
> .rs.api.writeRStudioPreference("surround_selection", "quotes")
> .rs.api.readRStudioPreference("surround_selection", FALSE)
[1] "quotes"
```
