### ISSUE TITLE
Modify cross-reference visualization

### ISSUE THREAD

**Issue by malcolmbarrett** [rstudio/rstudio#9441]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version: MacOS Big Sur
    R Version : 4.0.4

### Steps to reproduce the problem
Use bookdown in visual R Markdown mode to use figure and table cross-referencing

### Describe the problem in detail

Visual R Markdown formats the syntax in a strange way, deleting just the leading `\`, showing e.g. `@ref(...)`, which is confusing for students to read and understand. 

### Describe the behavior you expected

I think the visual mode version should be either simplified or show the entire syntax, e.g. either `\@ref(fig:chunk-name)` or some simplified version, e.g. `Cross-reference: chunk-name`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Thanks @malcolmbarrett !

**Comment by jjallaire** [comment]
We understand this is confusing, but the `\@` syntax is a bit of a hack to distinguish citations from crossrefs. The `\` is actually an escape character for pandoc markdown, so ultimately `\@` and `@` are the same thing (the only reason bookdown uses `\@` is to make it easier to write a regex to find and substitute for the references. 

Anyway, it's very tricky for us to include characters in the visual editor that aren't actually written to the source mode (it can be done but often with other side effects). In Quarto (https://quarto.org) we've unified the syntax for citations and crossrefs (https://quarto.org/docs/authoring/cross-references.html) so this won't be an issue.
