### ISSUE TITLE
EPIC: Visual Editor

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9443]

**Comment by jmcphers** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Inserting a hard line break using the menu isn't inserting a trailing backslash #8601](https://github.com/rstudio/rstudio/issues/8601)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/12741685) | 1.5 (Q3 2021) | dragonstyle | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Safari number/bullet for new list lines don't show up until typing content #8581](https://github.com/rstudio/rstudio/issues/8581)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/12737314) | 1.5 (Q3 2021) | kevinushey | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [URLs with no spaces gets combined, converting bracketed links to inline (markdown) #8471](https://github.com/rstudio/rstudio/issues/8471)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/12711091) | 1.5 (Q3 2021) | dragonstyle | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [strange behavior with Shift + Down with gap cursor #8167](https://github.com/rstudio/rstudio/issues/8167)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/12596156) | 1.5 (Q3 2021) | N/A | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Daily build, insert citation: previously deleted Zotero items still show up at Zotero root #7722](https://github.com/rstudio/rstudio/issues/7722)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/12345696) | 1.5 (Q3 2021) | dragonstyle | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Provide ability to comment out regions of content in visual mode #7583](https://github.com/rstudio/rstudio/issues/7583)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/12268422) | 1.5 (Q3 2021) | N/A | backlog | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [[Feature request] User-friendlier interface for chunk options in the visual markdown editor #7332](https://github.com/rstudio/rstudio/issues/7332)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/11865562) | 1.5 (Q3 2021) | dragonstyle | backlog | Open


###### do-not-edit-end-codetree-epic-issues
