### ISSUE TITLE
Undocumented (and dangerous) shortcut for "Restart R session"

### ISSUE THREAD

**Issue by davidski** [rstudio/rstudio#9445]
### System details

R version 4.0.5
OS Version: MacOS BigSur
Rstudio mode : Desktop
Rstudio version : 1.4.1717
Steps to reproduce the problem

### Describe the problem in detail

This is a reopen of issue #7695, which was closed due to inactivity, but is still present. Modified details from that bug report are:
 
On MacOS, the following key sequence restarts R session : Command + Shift + 0(zero). This shortcut is undocumented and it is unclear to a user how to disable this shortcut.

The "Session" menu mentions the shortcut as Shift+Command+F10 to restart the R Session,  while it also restarts with Command + Shift + 0(zero)

Command + Shift + 0(zero) closely resembles Control + Shift + 0(zero) that is used to "Show All Panes" as well as Command + Shift  + P (for command palette, which I use _all the time_) and results in a session restart in the middle of work! 🙀 With the inclusion of the command palette function in recent RStudio versions this is (for this clumsy typist) an extreme source of frustration.

### Describe the behavior you expected

Command + Shift + 0(zero) should not Restart R session since it's not mentioned anywhere nor its it part of keyboard shortcuts.

### Describe the behavior you expected

Keyboard shortcuts listed in the keyboard shortcut pane should match what are in effect.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I reopened #7695, so will close this one.
