### ISSUE TITLE
Starting Electron RStudio desktop with --version should show build version

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9459]
## Feature

Start RStudio desktop from command-line, with --version switch; it should print the build number to stdout and terminate without showing a window. This feature exists in all Qt-based Desktop releases.

- Mac: `RStudio.app/Contents/MacOS/RStudio --version`
- Windows: `RStudio.exe --version`
- Linux: `RStudio --version`

## Work Items
- implementing within the app (already done)
- hooking up build such that real version is stamped into the packaged build (not done)
- automation to verify behavior (integration/Selenium test, not done)

**Comment by gtritchie** [comment]
This was having issues after the move to electron-forge, needs more investigation.

**Comment by gtritchie** [comment]
This is working. On a production build, launch with `--version` to see a JSON-formatted dump of component versions. For example, on MacOS: `/Applications/RStudio.app/Contents/MacOS/RStudio --version`.

On a development environment using `yarn start`, you must include two sets of `--` before the switch. This is a combined quirk of electron-forge and yarn. So: `yarn start -- -- --version`.

**Comment by matheustavaresdev** [comment]
Fixed with https://github.com/rstudio/rstudio/commit/f934909cd4a95f934d7676492e58d03858801b92

**Comment by gtritchie** [comment]
Moving out of test, pending outcome of investigation here: #10794

**Comment by gtritchie** [comment]
Closing, testing tracked via #10794.
