### ISSUE TITLE
Starting Electron RStudio desktop with --version-json should show detailed build version

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9460]
## Feature

Start RStudio desktop from command-line, with `--version-json` switch; it should print detailed version info, in JSON format, to stdout then exit. This includes the rstudio version, but also details on major components such as Chromium, Node.js, and Electron. Others are also included, at the whim of Node.js.

```
{
  "node": "14.16.0",
  "v8": "9.1.269.28-electron.0",
  "uv": "1.40.0",
  "zlib": "1.2.11",
  "brotli": "1.0.9",
  "ares": "1.16.1",
  "modules": "89",
  "nghttp2": "1.41.0",
  "napi": "7",
  "llhttp": "2.1.3",
  "openssl": "1.1.1",
  "icu": "68.1",
  "unicode": "13.0",
  "electron": "13.1.1",
  "chrome": "91.0.4472.77",
  "rstudio": "1.5.0"
}
```

- Mac: `RStudio.app/Contents/MacOS/RStudio --version-json`
- Windows: `RStudio.exe --version-json`
- Linux: `RStudio --version-json`

## Work Items
- implementing within the app (already done)
- hooking up build such that real rstudio version is stamped into the packaged build (not done)
- automation to verify behavior (integration/Selenium test, not done)

**Comment by ronblum** [comment]
I'm marking this as a bug because it's not working properly in 1.4.1717 and previous releases. @gtritchie Is this new in Electron, or should it work in existing releases?

**Comment by gtritchie** [comment]
This was new in Electron, wanted a way to view version info on Electron, Node, etc. So not a bug.

**Comment by gtritchie** [comment]
This is working. On a production build, launch with `--version-json` to see a JSON-formatted dump of component versions.

On a development environment using `yarn start`, you must include two sets of `--` before the switch. This is a combined quirk of electron-forge and yarn. So: `yarn start -- -- --version-json`.

**Comment by gtritchie** [comment]
Tested and verified working with latest daily Electron builds on Mac, WIndows-11, and Ubuntu 20.
