### ISSUE TITLE
R Markdown does not hide JS code chunk

### ISSUE THREAD

**Issue by helgasoft** [rstudio/rstudio#9468]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1717
    OS Version      :  Win 10
    R Version       :  4.1.0

### Steps to reproduce the problem
Open new R Markdown file, copy/paste code below, save, knit.
````
---
title: "test"
output: 
html_document:
code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### R Markdown can't hide JS code chunks?
```{r cars}
summary(cars)
```
here is the JS chunk:
```{js, eval=FALSE, collapse=TRUE}
alert('Hide me!');
```
````
### Describe the problem in detail
after "code_folding: hide" and "collapse=TRUE" one would expect all chunks to be hidden at start
### Describe the behavior you expected
I would like to hide all code chunks, not only R, but JS as well.

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@helgasoft Thank you for raising this! I can reproduce this in RStudio Desktop 1.4.1717 on MacOS 12 beta. I also tried the following code, to compare the JavaScript and R chunks that are evaluated:

````
---
title: "test"
output: 
   html_document:
       code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
A JS chunk with collapse=TRUE
```{js, collapse=TRUE}
alert('Hide me JS!');
```
A JS chunk with collapse=FALSE
```{js, collapse=FALSE}
alert("Don't hide me JS!");
```
An R chunk with collapse=TRUE
```{r, collapse=TRUE}
print('Hide me R!')
```
An R chunk with collapse=FALSE
```{r, collapse=FALSE}
print("Don't hide me R!");
```
````

The JavaScript alerts work correctly. The output hides the R chunk correctly, but not the JavaScript chunk.

````
test
A JS chunk with collapse=TRUE

alert('Hide me JS!');
A JS chunk with collapse=FALSE

alert("Don't hide me JS!");
An R chunk with collapse=TRUE

An R chunk with collapse=FALSE

## [1] "Don't hide me R!"
````

**Comment by cderv** [comment]
Is this related to the IDE ? 

If feels something more about the usage of **rmarkdown** itself. 

Note that `collapse` option **is not** related to `code_folding`. It is used to collapse source and result into the same output 

See about `collapse` in https://bookdown.org/yihui/rmarkdown-cookbook/opts-collapse.html
See about how to control folding at the chunk basis in : https://bookdown.org/yihui/rmarkdown-cookbook/fold-show.html

That being said, it is true that `code_folding` does not work with all language by default. But it can be generalized by adding the class `.foldable` to the chunk. Try 

````markdown
---
title: "test"
output: 
   html_document:
       code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A JS chunk with collapse=TRUE

```{js, class.source=".foldable"}
alert('Hide me JS!');
```

An R chunk with collapse=TRUE

```{r, collapse=TRUE}
print('Hide me R!')
```

An R chunk with collapse=FALSE

```{r, collapse=FALSE}
print("Don't hide me R!");
```
````

the R chunk result with `collapse = FALSE` is not folded and it is expected as currently only source code can be folded. 

Not sure there is an issue here (but `class?source = ".foldable"` needs to be documented for such usage)

**Comment by helgasoft** [comment]
**_```class.source = ".foldable"``` needs to be documented_** - agree. And it does the trick, thank you.
