### ISSUE TITLE
prompt for reticulate installation when running Python chunks

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9471]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : macOS 11.4
    R Version       : 4.0.4

### Steps to reproduce the problem

First, ensure the `reticulate` package is uninstalled, e.g. via

```
remove.packages("reticulate")
```

Then, create an R Markdown document with a single Python chunk; e.g.

`````
---
title: "Untitled"
output: html_document
---

```{python}
import sys
sys.version
```
`````

and try to run that chunk.

### Describe the problem in detail

RStudio does not prompt the user to install `reticulate`; instead, it just blindly attempts to activate `reticulate` and run the code (which fails):

<img width="448" alt="Screen Shot 2021-06-08 at 1 00 14 PM" src="https://user-images.githubusercontent.com/1976582/121249497-7fff1480-c859-11eb-96b9-33a308b70ca2.png">

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified using the steps described above in:
- RStudio Desktop 1.5.121 on MacOS 12 beta
- RStudio Server 1.5.121 on Ubuntu 20
