### ISSUE TITLE
repeatedly executing a Python chunk causes RStudio to jump back and forth between Python mode

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9476]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : macOS 11.4
    R Version       : 4.1.0

### Steps to reproduce the problem

Create a chunk with the contents:

`````
---
title: "Untitled"
output: html_document
---

```{python}
import sys
sys.executable
```
`````

Then try to run the chunk multiple times.

### Describe the problem in detail

Every time the chunk is run, the reticulate banner is shown in the chunk output.

<img width="564" alt="Screen Shot 2021-06-08 at 4 35 47 PM" src="https://user-images.githubusercontent.com/1976582/121270994-974cfa80-c877-11eb-8270-dbdfdf618a84.png">

### Describe the behavior you expected

There are two somewhat similar issues:

1. We shouldn't include the `reticulate` banner in the chunk output.
2. We probably shouldn't be toggling Python mode off and on each time we execute the same Python chunk.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in
- RStudio Server 2021-08.0.297 on Red Hat 7.9 via Chrome on MacOS 12 beta.
- RStudio Desktop 2021-08.0.295 on MacOS 12 beta

**Comment by astayleraz** [comment]
Added automation test for this issue. Closing issue.
