### ISSUE TITLE
RStudio won't open FILE.c if file.c is open already

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/rstudio#9480]
1. Open a fake project in `/tmp/test`
2. `touch /tmp/test/FILE.c && touch /tmp/test/file.c`
3. Click `file.c` in the `Files` pane
4. Try to click `FILE.c`.

It won't open.

Now close `file.c`, and open `FILE.c` -- it opens. But try opening `file.c` -- it won't open.

Tested on:

```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.3
```

Latest RStudio daily build: Version 1.5.90 (and also before I updated on circa 1.4.x)

**Comment by ronblum** [comment]
Thanks @MichaelChirico! I can reproduce this in RStudio Server 1.4.1717 on Red Hat 8.3, which also ought to distinguish between the two. We'll review this as we continue developing RStudio.
