### ISSUE TITLE
More robust ctrl-return "send to console" behaviour amid an admittedly idiosyncratic code style

### ISSUE THREAD

**Issue by mike-lawrence** [rstudio/rstudio#9483]
I've lately come to really like writing pipes encapsulated with parens like this:
```r
(
  input
  %>% do_something()
  %>% do_something_else()
) -> 
    output
```
And the "send to console" shortcut (ctrl-return) usually behaves great with this pattern such that triggering it when the cursor is anywhere in the pipe and the whole thing is run. However a corner case that I encounter decently often is when I use an anonymous function anywhere in the pipe:
```r
(
  input
  %>% do_something()
  %>% do_something_else()
  %>% {function(x){
    #custom code here that's hard to pipe-ify
    return(z)
  }}()
) -> 
    output
```
In that case, when the cursor is inside the anonymous function, triggering "send to console" seems to only "see" the function definition block and sends whatever lines consist of a single statement associated with the line I'm on. It's pretty easy for me to simply remember to move the cursor for this scenario before triggering the shortcut, and it wouldn't surprise me if it'd be difficult to make the shortcut "work" for this case while not breaking expected behaviour otherwise, but I thought I'd mention it in case this impression is inaccurate.

**Comment by ronblum** [comment]
@mike-lawrence Even if it's idiosyncratic, it's good to keep this request open and see if others people code the same and would like the same enhancement.

**Comment by colearendt** [comment]
Bump

**Comment by colearendt** [comment]
CTRL+Return to tell stale-bot to go take a hike 😄
