### ISSUE TITLE
Q on the "stop" button for jobs

### ISSUE THREAD

**Issue by mike-lawrence** [rstudio/rstudio#9494]
I'm using `rstudioapi::jobRunScript()` to launch a background job that in turn spawns it's own processes via `processx::process()`. I'm reluctant to use the `cleanup` argument to `processx::process()` as frankly I've encountered scenarios where RStudio crashes while the job is running and I don't want the computations to stop in that case. But I would like a mechanism to let the user manually stop the processes. I can do so by writing out the PIDs and using 'ps::ps_kill()', putting that in a wrapper function for users to call, but it'd be nice if I could bind the stop button to that function as well. Any thoughts on how I might go about achieving such binding? If using `rstudoapi::jobAdd()` I could simply supply the kill function as the value to the `stop` entry in the list supplied to the `actions` argument, but `rstudioapi::jobRunScript()` doesn't have an `actions` argument (see  #9361).

**Comment by jmcphers** [comment]
Sorry, these can't be modified; when the script starts, it runs `.rs.scriptActions()` to get the list of actions (including stop): 

https://github.com/rstudio/rstudio/blob/c8b1631fa3149c5cc56cc3a80c9a1deedfe78701/src/cpp/session/modules/SessionJobs.R#L18-L27
