### ISSUE TITLE
RStudio Server cannot start as non-root user

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#9496]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4 (probably earlier as well)
    OS Version      : N/A
    R Version       : N/A

### Steps to reproduce the problem

1. Run rserver directly as a non-root user.

### Describe the problem in detail

`rserver` exits with an error that the user `""` does not exist.

### Describe the behavior you expected

`rserver` should run as long as the user that started `rserver` is the `server-user`.

This is happening due to this block of code: https://github.com/rstudio/rstudio/blob/main/src/cpp/server/ServerOptions.cpp#L259-L262

An alternative that would not cause this error to occur (in pseudo code):

```
if (!core::system::realUserIsRoot())
    {         
        if (serverUser_ != core::system::getEffectiveUser()) {
              LOG_WARNING("Cannot switch users from " + effectiveUser + " to " + serverUser_ + ". Running rserver as " + effectiveUser);
              serverUser_ = effectiveUser;
        }
    }
```

Alternatively we can log that message at the error level an return an error from this function to force rserver to exit with a failure.

We should make a similar change here, as well as provide more context in the warning that is logged there about why rserver is being run as root.: https://github.com/rstudio/rstudio/blob/main/src/cpp/server/ServerOptions.cpp#L270-L276

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
@MariaSemple Could you add the ticket number that lead to this issue?

**Comment by MariaSemple** [comment]
61879

**Comment by astayleraz** [comment]
I verified in version 2021-08.0.317-2 with ubuntu20 and Kubernetes I was able to run rstudio as a non-root user. Closing issue.
