### ISSUE TITLE
R_USER (and/or) R_LIBS residing on OneDrive (RStudio Desktop for WINDOWS) 

### ISSUE THREAD

**Issue by gwd666** [rstudio/rstudio#9504]
Prepare (or make sure) RStudio Desktop for WINDOWS to gracefully handle USER HOME folder (respectively  "R_USER") as well as probably/potentially "R_LIBS" (resp. the default or one of the subordinate library installation paths) being MS "OneDrive" (paths/folders)  

In case of needed support with testing or similar assistance - feel free to get in touch.

**Comment by ronblum** [comment]
@gwd666 Does this mean that they aren't working with OneDrive? And if so, are they working with local paths? Thanks!

**Comment by gwd666** [comment]
@ronblum - I mainly recorded this feature request as a way to get investigate or get the discussion going far the various OneDrive peculiarities (like downloading files from cloud on-demand, etc.) do or potentially could trigger problems in RStudio - eg on startup when indexing library folders; there are currently some problems with RS 1.3.1098 and 1.4.1717 have when USERSHARE (resp. the R_USER) path is pointing to WINDOWS network shares (UNC-paths) both during startup and also during knitting; 
I was wondering if RStudio Desktop has tested interaction with OneDrive in enough detail to potentially use OneDrive as a solution to that problem, or if this will open up Pandora's box and a bunch of other issues along with it?
