### ISSUE TITLE
Git repository displayed on RStudio Mac dock icon even when not using Git

### ISSUE THREAD

**Issue by zsiegel92** [rstudio/rstudio#9517]
### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 1.4.1717, "Juliet Rose" (df86b69e, 2021-05-24) for macOS
    OS Version      : 11.3.1
    R Version       : 4.1.0 (2021-05-18) -- "Camp Pontanezen"

### Steps to reproduce the problem

* Select "Git/SVN" in "Preferences" or "Global Options" to allow version control for RStudio projects.
* Navigate to a folder with a .git repository in RStudio. The dock icon now shows the project/repository name as a badge on the dock icon.
* Turn off version control in RStudio
* The dock badge remains

### Describe the problem in detail

The dock badge remains even after turning off version control in RStudio. I don't know how to turn it off. I don't particularly want my dock icon for RStudio to always have the name of a repository that I accessed through RStudio one time.

### Describe the behavior you expected

The dock icon badge should disappear when not accessing a git repository in any meaningful way within RStudio (e.g. no files in that repository are open and the working directory does not have the .git content). Certainly when version control is turned off altogether in the RStudio settings this badge should go away.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@zsiegel92 I believe what you're describing is due to being in a project, regardless of whether or not version control is enabled. What happens if you close the project?

**Comment by zsiegel92** [comment]
@ronblum You're right, that did it! Sorry and thank you for your time.

**Comment by ronblum** [comment]
@zsiegel92 No problem at all—I'm glad that took care of it!
