### ISSUE TITLE
Shiny App crashes every other time from Reticulate function call

### ISSUE THREAD

**Issue by kyletgoldberg** [rstudio/rstudio#9521]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : x86_64-apple-darwin17.0   
    R Version       : 4.1.0

### Steps to reproduce the problem

**reprex**

**py_file.py**
>import numpy as np
>a=np.array([1,2,3])

**app.R**
>library(shiny)
>library(reticulate)
>ui <- fluidPage(
  fluidRow( 
    column(12, 
           h3("Test"),
           h3(textOutput("a")))))

>server <- function(input, output, session){
   observe({
    py_run_file("py_file.py")
    output$a<- renderText({paste(py$a)})  
  })
}
>shinyApp(ui, server)

**Session/Python Config Info**
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4
Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] reticulate_1.20 shiny_1.6.0    
loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        jquerylib_0.1.4   bslib_0.2.5.1     pillar_1.6.1      compiler_4.1.0    later_1.2.0       shinyjs_2.0.0    
 [8] tools_4.1.0       digest_0.6.27     jsonlite_1.7.2    lattice_0.20-44   lifecycle_1.0.0   tibble_3.1.2      gtable_0.3.0     
[15] png_0.1-7         pkgconfig_2.0.3   rlang_0.4.11      Matrix_1.3-4      DBI_1.1.1         rstudioapi_0.13   fastmap_1.1.0    
[22] withr_2.4.2       dplyr_1.0.6       sass_0.4.0        generics_0.1.0    vctrs_0.3.8       grid_4.1.0        tidyselect_1.1.1 
[29] glue_1.4.2        R6_2.5.0          fansi_0.5.0       minpack.lm_1.2-1  ggplot2_3.3.4     purrr_0.3.4       magrittr_2.0.1   
[36] scales_1.1.1      promises_1.2.0.1  ellipsis_0.3.2    htmltools_0.5.1.1 assertthat_0.2.1  mime_0.10         colorspace_2.0-1 
[43] xtable_1.8-4      httpuv_1.6.1      utf8_1.2.1        munsell_0.5.0     cachem_1.0.5      crayon_1.4.1     

> reticulate::py_config()
python:         /opt/anaconda3/envs/r-reticulate/bin/python
libpython:      /opt/anaconda3/envs/r-reticulate/lib/libpython3.9.dylib
pythonhome:     /opt/anaconda3/envs/r-reticulate:/opt/anaconda3/envs/r-reticulate
version:        3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35)  [Clang 11.1.0 ]
numpy:          /opt/anaconda3/envs/r-reticulate/lib/python3.9/site-packages/numpy
numpy_version:  1.21.0
python versions found: 
 /opt/anaconda3/envs/r-reticulate/bin/python
 /usr/bin/python3
 /usr/local/bin/python3
 /usr/bin/python

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/6697568/diagnostics-report.txt)

### Describe the problem in detail
Every other run the Shiny app crashes after running this without any warning and/or error message. Seems to be the same problem as https://github.com/rstudio/reticulate/issues/683 but on macOSx. Similar to this issue, it works every time when running the app in the RGUI. That issue was fixed by https://github.com/rstudio/rstudio/pull/6140 which could potentially be the same idea of what's going wrong here.

### Describe the behavior you expected
Expect the Shiny app not to crash on every other run just from running a Reticulate function.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kyletgoldberg Thank you for raising the issue!

I can reproduce the issue in
- RStudio Desktop 1.4.1717 on MacOS 12 beta

However, it works in
- RStudio Desktop 1.4.1106 on MacOS 12 beta
- RStudio Server 1.4.1717 on Red Hat 8.4 via Chrome on MacOS 12 beta

So it looks like it's a regression specific to RStudio Desktop.

**Comment by kevinushey** [comment]
The problem here is pretty dicey...

A recent change in `reticulate` changed how we initialize our interrupt handler, as part of this PR. https://github.com/rstudio/reticulate/pull/988.

The motivation was a recent change in Python (https://mail.python.org/pipermail/python-checkins/2021-March/169297.html) which basically causes Python to die when we tried to handle signals ourselves rather than via the Python interface.

However, because the Python event loop doesn't get a chance to run here (since R is at the foreground), Python never actually gets a chance to handle the interrupt.

I'll have to see if there's some other way around this. 😞

**Comment by kyletgoldberg** [comment]
Does the fact that the issue doesn't occur in R-GUI help at all? Thanks for taking a look.

**Comment by kevinushey** [comment]
To be clear, by R-GUI do you mean `R.app` (the built-in GUI distributed with R on macOS)?

**Comment by kyletgoldberg** [comment]
yes! apologies for not being clear

**Comment by kevinushey** [comment]
Thank you! Sorry, I just want to be absolutely sure I understand what you're seeing as getting this behavior right is a bit finicky.

**Comment by kevinushey** [comment]
I've now merged a change to the master branch of reticulate that should hopefully resolve the issue you're describing. Would you be willing to try installing it, with:

```
remotes::install_github("rstudio/reticulate")
```

then, restart the R session and let me know if you're still seeing this issue?

**Comment by kyletgoldberg** [comment]
Confirming that after installing that and restarting the session I am no longer having the issue. Thanks for the quick fix! Much appreciated.

**Comment by rhensen** [comment]
Hi there. I am experiencing this same issue with the following: 

R version 4.2.3 (2023-03-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.7.4
python version:        3.9.5 (default, Nov 30 2021, 17:25:25)  [Clang 12.0.5 (clang-1205.0.22.11)]


Every other time I load the app it doesn't quit on me. When I reload it, I can see a print function from the python functions I was calling in the unexpectedly closed session.
