### ISSUE TITLE
Duplicate entry for importDatasetFromSAV in commands.cmd.xml

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9523]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4, 1.5 (main)
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem

- pointed out in this PR: https://github.com/rstudio/rstudio/pull/9507
- opening this issue to resolve independently from that PR

Two entries with the same id in commands.cmd.xml:

```xml
   <cmd id="importDatasetFromSAV"
        label="Import Dataset from SAV..."
        menuLabel="From _SAV..."
        context="import"
        windowMode="main"/>

   <cmd id="importDatasetFromSAV"
        label="Import Dataset from SPSS..."
        menuLabel="From _SPSS..."
        context="import"
        windowMode="main"/>
```

The second one "wins" and is shown in the menus:

![screenshot of File / Import Data submenu](https://user-images.githubusercontent.com/10569626/123021577-3221fa80-d389-11eb-8d55-1d732d2f3b07.png)

The command handler:

```java
   void onImportDatasetFromSAV()
   {
      view_.bringToFront();
      dataImportPresenter_.openImportDatasetFromSAV("");
   }
```

### Describe the problem in detail
Duplicates in commands.cmd.xml currently "works", but will not with the upcoming localization changes.

### Describe the behavior you expected
No duplicates; need to confirm which of these entries gets deleted. Presumably the one that's hidden ("Import Dataset from SAV...") since it is not shown, and has been this way for several years.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 1.5.168 on MacOS 12 beta
- RStudio Server 1.5.168 on SLES 15 SP2 via Safari on MacOS 12 beta

Validated by comparing the import screens and resulting Data Viewer to the ones in RStudio Desktop 1.4.1722.
