### ISSUE TITLE
Scrollbox in vertical scrollbar in source pane becomes unusably thin on multi-monitor set-ups with 1 hi-res and 1+ lo-res monitors

### ISSUE THREAD

**Issue by Matherion** [rstudio/rstudio#9534]
First off, of course, thank you for creating one of the most awesome FLOSS applications I use!!! And thanks for the rainbox parentheses, while I'm at it :-)

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows 10
    R Version       : 4.1.0

### Steps to reproduce the problem

Install R and RStudio on a PC with multiple monitors, one high-res (in my case, 4K), one or more low-res (in my case, two monitors of 1280x1024).

### Describe the problem in detail

In the source pane, the scrollbox on the vertical scrollbar resizes as a function of the length of the opened document. However, the minimum size seems to be determined based on some generic setting instead of as a function of the monitor resolution/size. This causes the scrollbox to become unusably small. This makes scrolling impossible; the scrollbar doesn't contians up/down scrolling arrows, so you can only use the keyboard or click the areas on top and at the bottom of the scrollbox, which are very inaccurate as for large documents, they cover a lot of ground.

This is how it looks on my hi-res screen (my laptop screen, 4K):

![image](https://user-images.githubusercontent.com/2077242/123412243-ad65f500-d5b1-11eb-947f-ced67b3d2481.png)

If I move RStudio over to my secondary monitor (or tertairy; they're identical), the scrollbox in the vertical scrollbar becomes larger:

![image](https://user-images.githubusercontent.com/2077242/123412528-f6b64480-d5b1-11eb-9150-f8203538800e.png)

I assume that the height actually stays the same in number of pixels; but everything else adjusts (in number of pixels) to the higher resolution of my primary monitor (i.e. text stays roughly the same size, I can still see and use the buttons), so I assume this is just a tiny glitch where just the height of the scrollbox isn't properly constrained or checked.

### Describe the behavior you expected

I expect the scrollbox to not shrink below a given minimum size; a minimum size that is determined adequately regardless of however many monitors in whichever resolutions the user uses.

### Checkboxes

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Matherion Thank you for raising the issue! We'll review it as part of our ongoing development of RStudio.

**Comment by R-Hannibal** [comment]
@Matherion - I was able to successfully reproduce the issue, that scroll bar does get EXTREMELY tiny on 4k:

4k Scroll bar:
![4k_display](https://user-images.githubusercontent.com/62304541/123873046-7e29ed80-d8fb-11eb-89b5-fdb1914066c2.PNG)


Scroll bar on 2nd (lower resolution monitor):
![low_res_display](https://user-images.githubusercontent.com/62304541/123873077-87b35580-d8fb-11eb-959c-134725735f77.PNG)

Will go ahead and send the issue on to our development team for consideration, thanks again for bringing it to our attention 👍.

**Comment by Matherion** [comment]
Wow, this is awesome - great that this can be added to the backlog so quickly, thank you! I hope this is something that can easily be fixed and isn't a problem of the framework that RStudio uses (or whatever that stuff like Electron etc are called)!

In any case, thank you very much!!! 🙏

**Comment by kevinushey** [comment]
This belongs in the "probably fixed by Electron" bag.

**Comment by grantmcdermott** [comment]
Just to add: I have exactly the same behaviour on a pure HiDPI setup (i.e. no mixing of lo-res and hi-res monitors). The scrollbox is impossibly thin. Combined with the missing scrollbox arrows (#4594), this means that the lovely 'Modern' theme is unfortunately unusable on my system. 

![rstudio-modern](https://user-images.githubusercontent.com/10285037/135523259-5b34bdea-9737-4828-85ee-c4aec5ced41d.jpg)

The 'Classic' theme remains fine.

![rstudio-classic](https://user-images.githubusercontent.com/10285037/135523258-e160d307-eb1d-4636-9eb0-dcf317122a49.jpg)

FWIW I've noticed this behaviour for some time, but am currently running the preview release of RStudio on Arch Linux.

```r
sessionInfo()
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Arch Linux
...

rstudioapi::versionInfo()$version
#> [1] ‘2021.9.0.351’
```

**Comment by rebeccagj** [comment]
I have a similar setup to @grantmcdermott, two hi-res monitors and impossibly thin scale bars when using a Modern, Dark theme. Modern, light themes work ok. I'm on Ubuntu, though, maybe this OS info is helpful for testing?

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

> rstudioapi::versionInfo()$version
[1] ‘2022.2.0.443’
```

**Comment by chris-dworschak** [comment]
Glad this is being raised, have the same issue where I can basically not use the scroll bar (gets so small, both horizontally and vertically, that I cannot see it anymore). I'm on Linux Mint 20.3 Cinnamon with a high res screen. Thanks all!

`> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20.3

> rstudioapi::versionInfo()$version
[1] ‘2022.2.2.485’`

**Comment by mikebessuille** [comment]
@rebeccagj @chris-dworschak @grantmcdermott @Matherion can you please retest this with the latest Electron build of the desktop, which you can find now in preview: https://www.rstudio.com/products/rstudio/download/preview/.    (See "desktop electron version"?  Thanks!

**Comment by rebeccagj** [comment]
Can confirm that my scrollbars are fixed for my dark theme in the 'desktop electron version.'

![image](https://user-images.githubusercontent.com/15958358/175426615-60404840-2bac-439b-82ff-190949308817.png)

```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS
> rstudioapi::versionInfo()$version
[1] ‘2022.7.0.536’
```

**Comment by Matherion** [comment]
I can unfortunately confirm that with the latest RStudio (2022.07.1, build 554), the problem persists on my PC:

![image](https://user-images.githubusercontent.com/2077242/181539049-b4a42dfa-bcbd-422d-9139-0b52ac710df0.png)

`> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

>rstudioapi::versionInfo()$version
[1] ‘2022.7.1.554’`

Sorry 😕

**Comment by kevinushey** [comment]
@Matherion Can you give one of the daily Electron builds of RStudio a try? https://dailies.rstudio.com

**Comment by ronblum** [comment]
As we port RStudio Desktop from the Qt to Electron framework, we're hoping that the switchover resolves the issue. Thank you @rebeccagj for checking it! And if anyone else is willing to try it out, that would be very helpful.

To try out Electron:
- Electron builds as [a preview of the most recent release](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version), Spotted Wakerobin 2022.07.1+554.
- For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). 
 
Please note that these are meant for testing and development purposes, not production.

**Comment by mikebessuille** [comment]
Per above, this appears to be fixed in the Electron build.
