### ISSUE TITLE
EPIC: Client Connectivity

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#9536]

**Comment by jmcphers** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Reliable aborts even if the R session doesn't respond to interrupts #8865](https://github.com/rstudio/rstudio/issues/8865)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/12855252) | 1.5 (Q3 2021) | jeffvroom | backlog | Open


###### do-not-edit-end-codetree-epic-issues
