### ISSUE TITLE
.Rmd files intermittently do not save

### ISSUE THREAD

**Issue by ayushnoori** [rstudio/rstudio#9547]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1717
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : 4.1.0

Please see https://github.com/rstudio/rmarkdown/issues/2174, transferring the issue here based on the advice of @cderv.

### Describe the problem in detail

I am a frequent user of markdown documents and appreciate the convenient organization of code and documentation which they facilitate. However, after upgrading to R 4.1.0, I have recently encountered an issue with saving `.Rmd` files.

Occasionally, I will be unable to save the markdown file I am working on in RStudio. Pressing `CTRL + S` or File > Save in the IDE does not save the file (the file name at the top remains in blue font with an asterisk). Further, when this occurs, I have noticed that pressing `CTRL + Enter` does not execute the current line of the markdown file in the console; rather, I have to manually copy the line to the console.

After I notice that the file is not saving, I have no choice but to close the RStudio session, re-open my project, and re-execute the code chunks up to where I was working on. When I re-open the project, the markdown file is able to be saved again by pressing `CTRL + S`, and any changes made in the interim are usually preserved (i.e., when I open the project, the file name at the top is in blue font w/ asterisk), with my changes unsaved but present.

### Steps to reproduce the problem

The error occurs intermittently with no discernable pattern or warning. It is not limited to a particular markdown document or set of documents, and length of the document also does not seem to matter. All the markdown documents I have experienced this issue with have been contained within R projects and I am editing largely in visual mode; I can test on a markdown file outside of a project or without the visual markdown editor if that would be useful.

As noted at https://github.com/rstudio/rmarkdown/issues/2174, the error persisted after upgrading from RStudio Version 1.4.1106 to Version 1.4.1717.

### Describe the behavior you expected

I would expect to be able to save the `.Rmd` file upon pressing `CTRL + S` or File > Save.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ayushnoori Thank you for raising this issue! I'll mark it for review. In the meantime, any information about whether it only happens within projects and/or visual mode would be helpful, I appreciate it!

**Comment by ayushnoori** [comment]
Thanks @ronblum, will investigate. Quick note - I realized that this bug seems to be file-specific. That is, if I have two `.Rmd` files open and one fails to save, I am still able to make edits to and save the other open `.Rmd` file.

**Comment by kevinushey** [comment]
Does your R Markdown document by any chance contain C++ code chunks? (Or, is there anything else that makes this document unique?)

**Comment by ayushnoori** [comment]
Perhaps that I am currently using the [`prettydoc`](https://github.com/yixuan/prettydoc) theme? I thought the theme only affects rendering when I knit, though. Other than that, nothing else stands out that I can think of. No `C++` code chunks. Here's my `prettydoc` header information in the remote possibility that it's relevant:
```
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    css: code/css/custom.css
```

**Comment by kevinushey** [comment]
One other thing: when this issue occurs, is the IDE otherwise responsive? Are you able to execute code, or perform other actions? It sort of sounds like the R session itself could be frozen and so all actions (including saving files) will fail.

Unfortunately, without a reproducible example it will be challenging for us to make any progress.

**Comment by ayushnoori** [comment]
Interestingly enough, the IDE is otherwise responsive. I am able to navigate as normal (and save _other_ open `.Rmd` files). The only thing I am unable to do when this issue occurs is to press `CTRL + Enter` to execute the current line of the markdown file in the console; rather, I have to manually copy the line to the console.

When I get a chance, will try and investigate further to formulate a reproducible example. It is tough because the issue occurs intermittently - I haven't run into this problem for the past few days. If it doesn't occur again within a reasonable window, I will hope that it is resolved and close the issue.

**Comment by ayushnoori** [comment]
As far as I can tell, I have not encountered this bug within the past two weeks. Hence, I will close the issue for now. Will reopen if the bug reoccurs. I have recently updated several packages (please see https://github.com/rstudio/distill/issues/392), including `rmarkdown` and Pandoc, so perhaps this resolved the issue.

**Comment by smasongarrison** [comment]
I'm having a similar issue but it isn't file specific. R studio will just refuse to let me save files

**Comment by kevinushey** [comment]
@smasongarrison can you please file a new issue with more details?
