### ISSUE TITLE
Can't build docker image if dependent files are open in a Rstudio Project

### ISSUE THREAD

**Issue by Ada-Nick** [rstudio/rstudio#9569]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1103
    OS Version      :  Windows 10 x64 (build 19042)
    R Version       :  4.1.0

### Steps to reproduce the problem
1. Build a dockerfile that copies a repository onto an image
2. Make an R project in the repository 
3. Open in the R project in R studio
4. Try and build the docker image

### Describe the problem in detail

The container build crashes, I'm assuming it can't copy the repository because R studio has it open. The build works when I close
the project.  

The docker build error is as follow:
```
#10 [internal] load build context
#10 sha256:12d95b8641084b446d361becf142d9b94df09a1cdad580f820dc44cbb860036a
#10 transferring context: 8.34kB 0.0s done
#10 CANCELED
error from sender: context canceled
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Ada-Nick Thank you for raising the issue! I'll mark it for review as part of our ongoing development of RStudio.

**Comment by mikebessuille** [comment]
This isn't something we can directly fix.
