### ISSUE TITLE
error attempting to add files to rstudio connect document publish

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#9571]
### System details

    RStudio Edition : Server (built locally from `main`: b286238df645f21b35fc24680cba575aa98f89d9)
    RStudio Version : Dev
    OS Version      : OS X 10.15.5
    R Version       :  4.0.3

### Steps to reproduce the problem

1) Create a new R Markdown document using the "New R Markdown" UI

2) Set `self_contained: false`:

```yaml
---
title: "Untitled"
output: 
   html_document:
      self_contained: false
---
```

3) Render the document

4) Publish to RStudio Connect, selecting "Publish finished document only"

5) Attempt to "Add More..." files to the publish

6) Select any file, you'll see this error message:

<img width="966" alt="Screen Shot 2021-07-07 at 1 54 10 PM" src="https://user-images.githubusercontent.com/104391/124807005-50602c80-df2b-11eb-9c0d-fc617c02572e.png">

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - RStudio-2021-08.0.317 , R Version - 4.1.0, macOS 11.3 - Desktop 

Error no longer appearing, after selecting a knitted document (with `self_contained: false`), was able to select additional files for publish with no error occurring.
