### ISSUE TITLE
Focus on console

### ISSUE THREAD

**Issue by dipterix** [rstudio/rstudio#9575]
API function `jobRunScript` automatically switch to Jobs panel. My users (not frequent RStudio users) are often confused because the job output panel looks similar to the console but works differently. They tried to type command but nothing appeared. 

Is there any way to switch back to console panel? In this way users can focus on typing R codes.

**Comment by jmcphers** [comment]
Yes, there is! 

```r
rstudioapi::executeCommand("activateConsole")
```
