### ISSUE TITLE
`rmarkdown` syntax to reuse code chunks is flagged with warnings

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#9579]
In`rmarkdown`, you can embed one code chunk in another code chunk by enclosing its label in `<<>>`.
https://bookdown.org/yihui/rmarkdown-cookbook/reuse-chunks.html

But when I do so, although the document knits without any issues, the editor keeps flagging it:

<img width="714" alt="Screenshot 2021-07-08 at 19 26 20" src="https://user-images.githubusercontent.com/11330453/124965424-6866a780-e022-11eb-81c4-db3f0a46b8a9.png">

<img width="663" alt="Screenshot 2021-07-08 at 19 29 26" src="https://user-images.githubusercontent.com/11330453/124965840-d90dc400-e022-11eb-9865-be1927c52975.png">

Is it possible for the editor to recognize this as a valid syntax?

**Comment by ronblum** [comment]
@IndrajeetPatil Thank you for raising this! To simplify a bit, this is legitimate too, without nesting in a function:

````
```{r show_components}
<<test_connection>>
<<environment_information>>
```
````

I'll mark this as an enhancement to consider in future releases of RStudio.

**Comment by IndrajeetPatil** [comment]
Yes, of course, I just literally screen-captured what I was working on :)

Thanks!

**Comment by ronblum** [comment]
Verified in
- RStudio Server 2021-08.0.305 on Red Hat 8.4 via Safari on MacOS 12 beta
- RStudio Desktop 2021-08.0.295 on MacOS 12 beta

I also included a bogus entry with only one `<` and `>` to intentionally induce an error.
![signs.png](https://codetreeusercontent.s3.amazonaws.com/uploads/fb9cf920-83bd-4cff-a66e-5851900617f0/signs.png)
