### ISSUE TITLE
Make it possible to publish Quarto documents

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9581]
Make it possible to publish Quarto documents and websites from the editor as well as the Viewer pane.

(See #9556)

**Comment by mikebessuille** [comment]
I believe it's reasonable for this PR to go into Ghost Orchid, but for this issue (i.e., the testing of the feature) to be delayed to next release.  The feature isn't a released feature in Ghost Orchid, and we don't have time to test it right now.

**Comment by jmcphers** [comment]
Agree that we don't have to test Quarto publishing itself -- but we churned a TON of the publishing code and that's very fragile stuff. At a minimum we should sanity check that existing publish scenarios didn't regress.

**Comment by R-Hannibal** [comment]
Moving this to Prairie Trillium for verification (code is in Ghost Orchid).

**Comment by ronblum** [comment]
Retagging for triage so that this is reassigned to the proper milestone.

**Comment by ronblum** [comment]
This has been around for two releases while Quarto's been in preview, so this has gotten some decent usage, meaning that 1) publishing in Quarto works, and 2) R Markdown publishing continues to work as before. But I'll still do some testing.

**Comment by mikebessuille** [comment]
Ron will test this on Windows

**Comment by ronblum** [comment]
The `rsconnect` package is getting updated on CRAN, so I want to run a few more tests on CRAN before closing this.

**Comment by ronblum** [comment]
All set!

In one very particular case, I can't republish an R Markdown document that's inside of a Quarto project, and I still have to figure out a reprex for it (it's working in most cases). But Quarto publishing works well.
