### ISSUE TITLE
Move from CentOS 8 to another RedHat compatible OS for builds

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9584]
RStudio Server and Desktop for most RedHat compatible platforms (Fedora, Red Hat Enterprise Linux, and CentOS) are today built on, and for, CentOS 8.

https://github.com/rstudio/rstudio/blob/4d1fc87218497d67342f961e27eeb151e8d161a9/Jenkinsfile#L190-L191

https://github.com/rstudio/rstudio/blob/main/docker/jenkins/Dockerfile.centos8-x86_64

However, CentOS is going to reach EOL in just a few months due to RedHat dropping support. There's no longer a CentOS version downstream of RHEL that we can use. 

https://phoenixnap.com/kb/centos-8-early-eol-in-2021

We have a few options here but will need to pick a lane in the next few months, as there's no guarantee our builds against CentOS 8 will continue working once it reaches EOL. Here are some possible paths forward:

1. A couple of new open source projects have sprung up to try to fill the gaping hole left by CentOS, including [Rocky Linux](https://rockylinux.org/) and [Alma Linux](https://almalinux.org/). We could use one of these instead of CentOS. 
2. CentOS "stream" is still a thing; it's upstream of RHEL. We could use this instead of CentOS for building and releasing, which has the advantage of getting us ahead of RHEL changes but the disadvantage of making it difficult to maintain compatibility with older RHEL releases.

**Comment by mikebessuille** [comment]
We will follow what the Platform team decides for corporate centos replacement

**Comment by R-Hannibal** [comment]
Link [HERE](https://docs.google.com/document/d/1HkcuclvBwqifp4TSyIRz_kwoPQs_Nh2mvwpnujnZA94/edit#) to the Platform Support doc where available options are discussed, sounds like we have decided on a path forward.

**Comment by mikebessuille** [comment]
The document talks about making a note about what is supported, but it doesn't actually choose a new flavour if linux to use for testing or build systems.

**Comment by jmcphers** [comment]
For build systems, we don't need a great deal of RHEL 8 fidelity; the only things that really matter are that (a) the library versions we link to are the ones RHEL 8 uses, and (b) the RPM packaging is RHEL 8 compatible. That's a pretty low bar. I'd recommend moving to Rocky Linux for the build systems so we don't introduce a licensing requirement for local or lab based builds of the IDE.

For release testing, I think (although someone from QA should verify) that since our automated test environment scripts already create EC2 instances, it wouldn't be a big deal to test on RHEL 8 itself since RHEL 8 AMIs are readily available. The platform support doc also indicates that we'll do testing and validation on RHEL 8.

**Comment by R-Hannibal** [comment]
Can confirm that we already do release testing against RHEL8 environments and can continue to do so 👍.

**Comment by jmcphers** [comment]
Notes:

- CentOS 8 EOL date is December 31. https://www.centos.org/centos-linux-eol/
- When CentOS 7 EOL'ed, they pulled their Docker images literally the next day, causing all our builds to fail. 
- This change _could_ be as easy as changing the `FROM: ` on our Dockerfile (and references to it) that produces the RHEL 8 installers.

**Comment by melissa-barca** [comment]
I moved this back into In Progress because even though there have been succesful builds from Rocky Linux 8 there are a few things we need to do outside of this repo to make sure our links are pointing at the correct location and that our fuzzbucket environments work.

PR for updating our dailies page is here: rstudio/latest-builds/pull/34
