### ISSUE TITLE
how to disable csrf checking? login error:Error: Temporary server error, please try again

### ISSUE THREAD

**Issue by jianboy** [rstudio/rstudio#9594]
The issue tracker is not for questions. If you have a question, please feel free to ask it on our community site, at https://community.rstudio.com/c/rstudio-ide.

![image](https://user-images.githubusercontent.com/11532015/125193918-87af4000-e281-11eb-93d3-ff6867f0015c.png)

**Comment by ronblum** [comment]
@jianboy Information about CSRF is available in the Admin Guide:
-  Additional Security Considerations: https://docs.rstudio.com/ide/server-pro/access-and-security.html#additional-security-considerations
- Browser Security: https://docs.rstudio.com/ide/server-pro/hardening.html#browser-security
