### ISSUE TITLE
findProgramOnPath should handle .exe (and other executables) on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9608]
- Should we can use `PATHEXT` to figure out what files are considered "executable" on Windows? (Maybe not because users might put arbitrary "stuff" there.)
- Just look for the "defaults"?

**Comment by kevinushey** [comment]
https://github.com/python/cpython/blob/bd4ab8e73906a4f12d5353f567228b7c7497baf7/PC/launcher.c#L916-L951 uses the Windows [SearchPath](https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-searchpatha) API.

**Comment by mikebessuille** [comment]
Can you explain what is the actual result?  Was this seen in a customer ticket?

**Comment by kevinushey** [comment]
The actual result is it doesn't find any executables on Windows, thereby ensuring any usage of it is broken on Windows.

**Comment by kevinushey** [comment]
I don't think there's a straightforward way for QA to verify, and if any issue crops up it should be immediately visible to developers so I think this can be closed.
