### ISSUE TITLE
RStudio Server sqlite database error

### ISSUE THREAD

**Issue by Chris-Engelhardt** [rstudio/rstudio#9609]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717
    OS Version      :  Red Hat Enterprise Linux Server release 7.9 (Maipo)
    R Version       : 4.1.0

### Steps to reproduce the problem

On a fresh EC2 instance running AMI ID ami-0916c408cb02e310b in AWS, I ran the following lines to create an environment: 

```
sudo yum update -y 
sudo yum install -y yum-utils wget 
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum-config-manager --enable "rhel-*-optional-rpms"
export R_VERSION=4.1.0
curl -O https://cdn.rstudio.com/r/centos-7/pkgs/R-${R_VERSION}-1-1.x86_64.rpm
sudo yum install -y R-${R_VERSION}-1-1.x86_64.rpm
sudo ln -s /opt/R/${R_VERSION}/bin/R /bin/R
sudo ln -s /opt/R/${R_VERSION}/bin/Rscript /bin/Rscript
export R_STUDIO_VERSION=1.4.1717
wget https://download2.rstudio.org/server/centos7/x86_64/rstudio-server-rhel-${R_STUDIO_VERSION}-x86_64.rpm
sudo yum install -y rstudio-server-rhel-${R_STUDIO_VERSION}-x86_64.rpm
sudo useradd rstudio
sudo echo "rstudio:rstudio" | sudo chpasswd
sudo groupadd rstudio_users
sudo usermod -a -G rstudio_users rstudio
echo "auth-required-user-group=rstudio_users" | sudo tee -a /etc/rstudio/rserver.conf
sudo su rstudio -c "mkdir -p ~/.config/rstudio"
echo "DenyGroups rstudio_users" | sudo tee -a /etc/ssh/sshd_config
sudo service sshd restart
sudo rstudio-server restart
```

### Describe the problem in detail

I can authenticate as the rstudio user just fine and log in. When I run `sudo rstudio-server status`, no errors are returned. However, once I log out and run `sudo rstudio-server status`, I receive the following error (copied from /var/log/messages): 

`rserver[5199]: ERROR database error 7 (sqlite3_statement_backend::loadOne: unable to open database file) [description: Could not insert revoked cookie into the database]; OCCURRED AT virtual rstudio::core::Error rstudio::core::database::Connection::execute(rstudio::core::database::Query&, bool*) src/cpp/core/Database.cpp:510; LOGGED FROM: void rstudio::server::auth::handler::invalidateAuthCookie(const string&, rstudio::core::ExponentialBackoffPtr) src/cpp/server/auth/ServerAuthHandler.cpp:550`. 

I can wrangle this error by deleting /var/lib/rstudio-server/rstudio.sqlite and then re-starting the server. However, this approach doesn't seem like a great long-term solution, because re-starting the server creates another rstudio.sqlite file owned by an rstudio-server user and rstudio-server group.

I also dealt with the issue by changing permissions on /var/lib/rstudio-server: `chown -R rstudio-server:rstudio-server /var/lib/rstudio-server/`. This change addresses the problem, even though deletion of the database and re-start of rstudio server. 

If I don't make the change above, rstudio-server status continues to return additional errors following each user log-out. How concerned should I be about these errors? They don't seem to interfere, at least not yet, with my ability to authenticate and log in and use R.  

My issue seems somewhat related to https://github.com/grst/rstudio-server-conda/issues/11, but happening outside of a Docker container. 

### Describe the behavior you expected

I expected `rstudio-server status` to not throw an error following a user log-out. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This is where the database is created by default:

```
$ namei -l ${PWD}/rstudio.sqlite 
f: /var/lib/rstudio-server/rstudio.sqlite
drwxr-xr-x root           root           /
drwxr-xr-x root           root           var
drwxr-xr-x root           root           lib
drwxr-xr-x rstudio-server rstudio-server rstudio-server
-rw-r--r-- rstudio-server rstudio-server rstudio.sqlite
```

You should confirm that those permissions are properly set. Alternatively, you can set

```
provider=sqlite
directory=/somewhere/writable
```

in your `/etc/rstudio/database.conf` file.

**Comment by Chris-Engelhardt** [comment]
ty @kevinushey!

For some reason, I see a slightly different permission structure on this build:

```
$ namei -l ${PWD}/rstudio.sqlite
f: /var/lib/rstudio-server/rstudio.sqlite
dr-xr-xr-x root           root           /
drwxr-xr-x root           root           var
drwxr-xr-x root           root           lib
drwxr-xr-x root           root           rstudio-server
-rw-r--r-- rstudio-server rstudio-server rstudio.sqlite
```

As you can see, `/var/lib/rstudio-server` is writeable by root only, which explains why users can't write there. Changing permissions in line with your suggestion fixed the issue: 

```
sudo chown rstudio-server:rstudio-server /var/lib/rstudio-server/
```

Should we close this issue or leave it open?

**Comment by kevinushey** [comment]
I think this is worth leaving open since it'd be nice if RStudio were more clear about why the file couldn't be opened.

**Comment by ronblum** [comment]
Verified—see #9705.
