### ISSUE TITLE
"Find in files" pane not un-minimized when matches are not found

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9610]
**Steps to reproduce:**
* Switch to some R package project.
* Minimize the pane with the console and the "find in files" tabs.
* Press Ctrl + Shift + F (shortcut for "Find in Files").
* Try to find some word within the project's folder that does not exist in any file.

**Expected results:** should switch to the "Find in files" tab, un-minimizing the pane if it is minimized.

**Actual results:** switches to the "Find in files" tab, but if no results are found, the pane will not be un-minimized.

**Comment by ronblum** [comment]
@david-cortes I can't reproduce the problem. Which version of RStudio is this, and is it Debian 10 or Windows 10?

**Comment by david-cortes** [comment]
@ronblum This is RStudio 1.4.1725, running on debian 11. I notice it only happens when the console pane is configured to be above the source pane.
