### ISSUE TITLE
Chunk Options Not Being Used

### ISSUE THREAD

**Issue by toidtoistic** [rstudio/rstudio#9616]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717-3
    OS Version      : MacOS Big Sur 11.4
    R Version       : 4.1.0

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/8879115/126239918-0c8d6ed5-6d27-47e2-a305-41d6689d6bc0.png)

### Describe the problem in detail

Hi! I was wondering if I could get some help with an odd issue that I've encountered when setting up a new computer.

Usually, I like running all of my chunks in RMarkdown as opposed to knitting since my file can be quite large and I sometimes will run chunks out of order. However, one issue I've seen is that my global chunk options aren't being respected. In particular, I'm seeing messages and warnings inline even though I've explicitly set them to FALSE. The example I posted above demonstrates this issue. In particular, what I see is that 
![image](https://user-images.githubusercontent.com/8879115/126239658-f4e72d6e-704c-4c15-9dd3-b1c5b952cd21.png)

As you can see, the message shows up even though I've explicitly set it to FALSE in my global chunk settings. Even weirder, when I set the chunk options i.e.,

```{r, message = FALSE, warning = FALSE}```
within the chunk for messages/warnings, I still get the same result.

However, when I knit this file, it works fine; i.e., there isn't a message that shows up in the html file, so my sense is that this issue is potentially related to RStudio's inline rendering. Please let me know if you have any suggestions—any help is greatly appreciated!

### Describe the behavior you expected

I would expect that both the chunk options at the top of the file + at the beginning of the chunk are used when I'm running from within RStudio (not knitting.) This is because this behavior worked in previous versions of RStudio, including versions 1.3.1093 and 1.4.1106.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@toidtoistic Thank you for raising this! Would you mind including a minimal example of the code you used—written, not just screenshots? It doesn't have to be the entire file, just some individual chunks and how you set the global variables. It would make it easier to reproduce, especially making sure I use the exact same code as you.

That said, @kevinushey do you think this is already enough information to address, or do we need to wait for the above?

**Comment by cderv** [comment]
For reference, this was initially posted in the RStudio Community here: https://community.rstudio.com/t/chunk-options-not-being-used/109154

@ronblum minimal reprex can be found there that you can copy. You can copy it here for convenience if you want.

* I tested with 1.4.1106 and it is working as described, `message = FALSE` seems to apply
* But with last version, the global option `message = FALSE` seems not to apply

I think it will help you test this and confirm you also see the same thing.

**Comment by cderv** [comment]
This is still happening in last dev version for me.

**Comment by jefferis** [comment]
This issue also affects options associated with each individual chunk in an Rmarkdown notebook. For example the following file
````
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r, message=F}
message("I am a message. You should not see me!")
cat("You should always see cat!")
```
````

shows both statements when the chunk is run interactively (green triangle, first screenshot) and only the cat statement when using Knit to HTML (second screenshot). Like the others here, I see that this is a regression as earlier rstudio releases respected this option. I liked to use it for example to suppress verbose package startup messages in a notebook. 

![image](https://user-images.githubusercontent.com/23763/149747027-005d4b65-e775-4e71-a833-ae9e163789c4.png)

![image](https://user-images.githubusercontent.com/23763/149746913-2771155a-b869-4681-8a42-29d2c88d7f32.png)

**Comment by kevinushey** [comment]
This was fixed in https://github.com/rstudio/rstudio/pull/10348, but the fix was merged into the Spotted Wakerobin (SW) branch, so currently you should only see the fix available here:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/

See also: https://github.com/rstudio/rstudio/issues/9436

Note that the SW and current development branch, Prairie Trillium have diverged, so some fixes available in SW might not be available in PT.

**Comment by jefferis** [comment]
Many thanks for taking the time to supply these details @kevinushey. Will test the daily you link.

**Comment by cderv** [comment]
Thanks @kevinushey ! 

Good to know that we need to check different version. I'll do that next time. And I confirm this is working fine on SW.
