### ISSUE TITLE
auto-activate anaconda python if no valid version of python (python3) on PATH

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9618]
The intention here is, if the user has done the work to install Anaconda Python, we should assume the user wants to use it, and so auto-activate it in IDE sessions (presuming they haven't already explicitly selected something else).

Note: other "valid" Python installations would still have precedence.

- On macOS, avoid `/usr/bin/python3`.
- On Windows, avoid Windows store Python stub.

https://github.com/rstudio/rstudio/blob/43d9a465ea13141586c94073f83f09ba1cd07fe0/src/cpp/session/modules/SessionPythonEnvironments.R#L81-L131 -- need Anaconda lookup at bottom of this code block.

Would also want to look for `python3` on the PATH for macOS + Linux here, screening out potentially "bad" versions of Python.

Also consider (time permitting): comment colors for `#| output: true` metadata comments.

Note: this issue wraps up Python-related Quarto work for 1.5 with @jjallaire.

**Comment by R-Hannibal** [comment]
Moving this to Prairie Trillium for verification (code is in Ghost Orchid).

**Comment by kevinushey** [comment]
We ended up backing this out -- the change here was ultimately too aggressive. See also:

https://github.com/rstudio/rstudio/issues/9952
https://github.com/rstudio/rstudio/issues/9999
https://github.com/rstudio/rstudio/pull/10000

For now, users who want to bind a version of Python to be used in their projects explicitly can do so via project preferences.
