### ISSUE TITLE
multicolumn dataframe; previous and next cols buttons display as  □□ 1-50 □□

### ISSUE THREAD

**Issue by tynot** [rstudio/rstudio#9623]
### System details

    RStudio Edition : <Server>
    RStudio Version : 1.4.1717 (Juliet Rose) for Ubuntu Bionic
    OS Version      : Ubuntu server 20.04
    R Version       :  Microsoft R open 4.0.2

### Steps to reproduce the problem
Using Google Chrome  91.0.4472.124 in Windows 10 Home 21H1
Sign in IP:8787
open a multicolumn dataframe(more than 50 cols)
the last/next 50 cols and first/last cols buttons display incorrectly
### Describe the problem in detail
Open a multicolumn dataframe(more than 50 cols)
The last/next 50 cols and first/last cols buttons display incorrectly as □□ 1-50 □□
### Describe the behavior you expected
The buttons should be << < 1-50 > >> like the previous version such as Rstudio server 1.3.1093

### sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /opt/microsoft/ropen/4.0.2/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/4.0.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_11.0.2     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7       magrittr_2.0.1   tidyselect_1.1.1 munsell_0.5.0    colorspace_2.0-2 R6_2.5.0         rlang_0.4.11     fansi_0.5.0     
 [9] dplyr_1.0.7      patchwork_1.1.1  tools_4.0.2      grid_4.0.2       gtable_0.3.0     utf8_1.2.1       DBI_1.1.1        ellipsis_0.3.2  
[17] assertthat_0.2.1 tibble_3.1.2     lifecycle_1.0.0  crayon_1.4.1     purrr_0.3.4      ggplot2_3.3.5    vctrs_0.3.8      ggrepel_0.9.1   
[25] glue_1.4.2       compiler_4.0.2   pillar_1.6.1     generics_0.1.0   scales_1.1.1     pkgconfig_2.0.3 

###
- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![cols](https://user-images.githubusercontent.com/59528267/126419518-999043b6-6ce6-4e4a-8bb0-97c10005c5a8.jpg)

**Comment by tynot** [comment]
picture attached
![cols](https://user-images.githubusercontent.com/59528267/126419437-7c2e9687-f26f-43e1-a0d7-2ca6e35eed7a.jpg)

**Comment by kevinushey** [comment]
Probably a fonts issue, since we use CSS to render the arrows here:

<img width="194" alt="Screen Shot 2021-07-21 at 1 13 52 PM" src="https://user-images.githubusercontent.com/1976582/126553844-6efa7c15-95fe-425f-9e62-af9bab91841a.png">

We might just want to use icons explicitly here.

**Comment by jmcphers** [comment]
See also this issue from the community forum:

https://community.rstudio.com/t/rstudio-server-gui-little-bag/124417

We should probably just use images here since the font glyphs we're using today do not render consistently in all fonts.

**Comment by jmcphers** [comment]
Also reported on rstudio.cloud: https://github.com/rstudio/lucid-images-ide/issues/133

**Comment by jonvanausdeln** [comment]
Verified on 
2022.11.0-78 
Windows 11, Server on Ubuntu 22.04 w/Win11 Edge and Chrome on Ubuntu as clients.

Tested with several different datasets, both created on command line and imported different file formats.  All gave correct navigation arrows for the columsn.
