### ISSUE TITLE
Reproducible example for RStudio (Pro) arm64 rsession-arm64 crash (generates apple crashdump)

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#9625]
Per an extended email discussion with @ronblum (who also poked @kevinushey) I ran into a situation in early July where RStudio (Pro) on the M1 Mini crashed (`rsession-arm64` crashed). Unfortunately, the code and data weren't share-able.

I managed to hit another crash today and skimmed down the code to a reproducible (with the attached data):

```r
library(tidyverse)

read_lines("icsa-alerts.txt")
```

I shared the apple crash report privately.

- RStudio (Pro) 1.5.209-4

```
 tidyverse   * 1.3.0   2019-11-21 [1] CRAN (R 4.1.0)                       
 readr       * 2.0.0   2021-07-20 [1] CRAN (R 4.1.0)                       
```

[icsa-alerts.txt](https://github.com/rstudio/rstudio/files/6856725/icsa-alerts.txt)

**Comment by kevinushey** [comment]
The crash report indicates the crash is happening in the `vroom` package (which is used under the hood by `readr` now)

> Thread 0::  Dispatch queue: com.apple.main-thread
> 0   libsystem_kernel.dylib        	       0x19336d0a4 __psynch_cvwait + 8
> 1   libsystem_pthread.dylib       	       0x1933a5a14 _pthread_cond_wait + 1240
> 2   libc++.1.dylib                	       0x1932f426c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
> 3   libc++.1.dylib                	       0x1932f4e28 std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) + 56
> 4   libc++.1.dylib                	       0x1932f4ee0 std::__1::__assoc_sub_state::wait() + 56
> 5   vroom.so                      	       0x1082f0f44 vroom::delimited_index_connection::delimited_index_connection(SEXPREC*, char const*, char, bool, bool, bool, bool, unsigned long, unsigned long, char const*, bool, std::__1::shared_ptr<vroom_errors>, unsigned long, bool) + 4612
> 6   vroom.so                      	       0x1082f3178 vroom::delimited_index_connection::delimited_index_connection(SEXPREC*, char const*, char, bool, bool, bool, bool, unsigned long, unsigned long, char const*, bool, std::__1::shared_ptr<vroom_errors>, unsigned long, bool) + 56
> 7   vroom.so                      	       0x108300698 make_delimited_index(cpp11::sexp const&, char const*, char, bool, bool, bool, bool, unsigned long, unsigned long, char const*, bool, std::__1::shared_ptr<vroom_errors> const&, unsigned long, bool) + 600
> 8   vroom.so                      	       0x108301714 vroom::index_collection::index_collection(cpp11::r_vector<SEXPREC*> const&, char const*, char, bool, bool, bool, bool, unsigned long, unsigned long, char const*, bool, std::__1::shared_ptr<vroom_errors> const&, unsigned long, bool) + 212
> 9   vroom.so                      	       0x108301db8 vroom::index_collection::index_collection(cpp11::r_vector<SEXPREC*> const&, char const*, char, bool, bool, bool, bool, unsigned long, unsigned long, char const*, bool, std::__1::shared_ptr<vroom_errors> const&, unsigned long, bool) + 56
> 10  vroom.so                      	       0x108304a38 vroom_(cpp11::r_vector<SEXPREC*> const&, SEXPREC*, char, bool, bool, bool, char const*, bool, unsigned long, long, bool, cpp11::sexp const&, cpp11::sexp, cpp11::sexp, cpp11::sexp, SEXPREC*, cpp11::r_vector<cpp11::r_string> const&, cpp11::r_vector<SEXPREC*> const&, long, unsigned long, unsigned long) + 632
> 11  vroom.so                      	       0x1082e45cc _vroom_vroom_ + 780
> < ... >

I'd double-check whether this reproduces after reinstalling `readr` + all of its dependencies; if it does, this could be worth filing on the `readr` repository.

As a side note, the crash report also suggests magrittr is on the stack:

> 105 magrittr.so                   	       0x103a7f0e0 eval_pipe_lazy + 76 (pipe.c:183) [inlined]
> 106 magrittr.so                   	       0x103a7f0e0 magrittr_pipe + 1568 (pipe.c:105)

Are you sure the code you shared is the exact same code you used to reproduce the crash? (I wasn't able to reproduce locally on a couple of tries.)
