### ISSUE TITLE
Reformat Code added indentation for empty line inside functions

### ISSUE THREAD

**Issue by tonyxu-io** [rstudio/rstudio#9628]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      :  macOS Big Sur 11.4
    R Version       :  4.0.3 (2020-10-10)

### Steps to reproduce the problem

R code with empty lines inside functions, example:

```
someFunction <- function() {
  var1 <- var1

  var2 <- var2
}
```
Click Reformat Code. Extra spaces will be added:

```
someFunction <- function() {
  var1 <- var1
  
  var2 <- var2
}
```

### Describe the problem in detail

2 spaces indentation will be added to the empty lines, which is unnecessary.

### Describe the behavior you expected

Empty lines inside functions should not have indentation (extra spaces)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tonyxu-io Thank you for pointing this out! After a bit of research, there's some disagreement over what the behavior should be in different tools and languages.

@kevinushey I think this might be intentional behavior. Is that correct?

**Comment by kevinushey** [comment]
I think for R at least it'd be ideal if we preserved the whitespace used on blank lines (or leave it empty if so) but the solution is pretty easy (configure RStudio to trim trailing whitespace on save) so I don't think this is worth addressing.

**Comment by tonyxu-io** [comment]
Thank you @kevinushey this works for me. Feel free to close it.
