### ISSUE TITLE
Data frame attributes in environment pane create clutter

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#9635]
I'm curious if you could have a setting to view attributes in the environment pane. Some might find it helpful but I find it mostly creates clutter and more scrolling on my end. Is it possible for RStudio to just note that there are attributes or have a setting to display it or not? This feedback is the same for grouped data frames, units on difftime calculations, etc.
```r
library(readr)
x <- read_delim(readr_example("mtcars.csv"))
```
![image](https://user-images.githubusercontent.com/14003618/126679819-4393e796-c30b-4027-886c-e52f0c1f4f12.png)

Here's a more extreme example: `readr` column specs + difftime field + grouped
![image](https://user-images.githubusercontent.com/14003618/126680612-2b228245-bd89-4265-8aea-89009a7ffdc5.png)

**Comment by ronblum** [comment]
@rjake Thank you for the suggestion! We'll review it as part of our ongoing development of RStudio.
