### ISSUE TITLE
rsconnect deployApp should include quarto engine requirements 

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#9641]
Currently we pass an `isQuarto` flag, this needs to turn into a richer data structure that includes (at a minimum) the engines used by the deployed artifact.

Note that this also requires that the `rsconnect` package write the richer info the deployment manifist.

Further, we should update the quarto R package to do the same.

**Comment by jjallaire** [comment]
rsconnect expects to consume this:

```js
{
  quarto: {
    version: "XXX",
    engines: ["knitr", ...]
  }
}
```

**Comment by jjallaire** [comment]
Addressed with: https://github.com/rstudio/rstudio/commit/b48db8a77bf296ff59ec3367794477f8d950a6bf

**Comment by jjallaire** [comment]
Note to QA: @aronatkins Will be verifying this as part of his work on RSC server support for quarto.

**Comment by R-Hannibal** [comment]
Moving this to Prairie Trillium for verification (code is in Ghost Orchid).

**Comment by astayleraz** [comment]
Verified in 2022.01.0-daily+199.pro1 I am able to publish a quarto file and added an automation test for this as well. Closing issue.
