### ISSUE TITLE
Addins dcf in `R_user_dir`

### ISSUE THREAD

**Issue by dipterix** [rstudio/rstudio#9648]
Currently package addins are detected within `[package path]/rstudio/addins.dcf`. Is it possible to also detect from `file.path(R_user_dir([package], "config"), "rstudio/addins.dcf")`?

One example is that package now can dynamically add/remove/change the addin content (of course requires restarting RStudio).

In `shrtcts` package (see this issue https://github.com/gadenbuie/shrtcts/issues/17), they have to change the package's content on the fly, which might violate the CRAN policy. However, edits in `R_user_dir` seems to be much more reasonable.

**Comment by astayleraz** [comment]
This enhancement has been added @dipterix. Let us know if you run into any issues with this. Closing issue.
