### ISSUE TITLE
Chunk not rendering correctly in daily version of RStudio Workbench 1.5

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#9649]
### System details

    RStudio Edition : Server
    RStudio Version : 1.5.233-9
    OS Version      :  Ubuntu
    R Version       : 4.1.0

### Steps to reproduce the problem

Open up RStudio Workbench in the browser and type the following into the RStudio console:

```r
u = "https://github.com/zonebuilders/zonebuilder/raw/master/vignettes/paper.Rmd"
f = basename(u)
download.file(url = u, destfile = f)
file.edit(f)
```

Scroll down to line 200.

### Describe the problem in detail

The code is not rendered correctly. It looks like this:

![image](https://user-images.githubusercontent.com/1825120/126891987-9ddd7988-4861-4213-9a06-7713cdb73869.png)

### Describe the behavior you expected

I would expect it to look more like this, with correct code syntax-based colours:

![image](https://user-images.githubusercontent.com/1825120/126892083-55e1de81-6545-42a4-9422-562bfb621294.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks; I've reproduced in the latest 1.5 daily builds. A smaller reproducible example:

`````
<!-- a comment -->

```{r}
# no highlighting for me
```
`````

<img width="221" alt="Screen Shot 2021-07-26 at 10 15 23 AM" src="https://user-images.githubusercontent.com/1976582/127031003-beeeb8fa-a733-44b1-a2ca-4c415a7e79da.png">

**Comment by kevinushey** [comment]
Should be fixed in the next daily builds; thanks for reporting!

**Comment by Robinlovelace** [comment]
Thanks for the quick fix, you guys are :fire:
