### ISSUE TITLE
Invalid LaTeX Equation Identified as Valid

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#9661]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows 10
    R Version       : 4.1.0

### Steps to reproduce the problem

Enter the following equation in an Rmd document (example attached, simply rename from .txt to .Rmd: [latex_issue.txt](https://github.com/rstudio/rstudio/files/6888543/latex_issue.txt)):

`$$D = A^\left(E - 1\right)$$`

### Describe the problem in detail

The equation is not valid LaTeX; it requires additional braces (`{}`) around the exponent as follows:

`$$D = A^{\left(E - 1\right)}$$`

The equation shows up in the preview below where it is entered, but it should not.

### Describe the behavior you expected

I would have expected the equation not to show up since it is not valid LaTeX.

My guess is that this is a problem upstream of Rstudio, but I don't know what the upstream is to report it.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@billdenney Thank you for raising this! R Markdown in RStudio uses MathJax by default, for which this is acceptable syntax. [An example](https://arachnoid.com/latex/?equ=D%20%3D%20A%5E%5Cleft(E%20-%201%5Cright)) with an online evaluator is available [here](https://arachnoid.com/latex/?equ=D%20%3D%20A%5E%5Cleft(E%20-%201%5Cright)).
