### ISSUE TITLE
Splitter cursor different on Mac Desktop (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9673]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : dev build
    OS Version      : macOS 11.5.1
    R Version       : Any

### Steps to reproduce the problem
Build and run RStudio Desktop (Electron) on Mac. Hover mouse over vertical splitter (or horizontal splitter).

Compare the mouse cursor to what is seen on current released RStudio Desktop (Qt).

### Describe the problem in detail
Electron shows this:

![vertical splitter mouse cursor on Electron](https://user-images.githubusercontent.com/10569626/127409540-1bed06d7-090f-4741-ac47-7a3b49418d80.png)

Released desktop shows this:

![vertical splitter mouse cursor on Qt desktop](https://user-images.githubusercontent.com/10569626/127409567-1dddebf4-7882-4406-bee9-c8975d9060fc.png)

### Describe the behavior you expected
Ideally they should be the same. The cursor for horizontal splitter exhibits similar difference.

I did not test Windows or Linux.

Note, this code is a factor, commenting out changes to a generic move icon (probably better if we can't get the desired behavior):

https://github.com/rstudio/rstudio/blob/c4ad23bda66b964354ef95d15ba7df7302540df3/src/node/desktop/src/main/desktop-browser-window.ts#L167-L174

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Here's where this style `avoid-move-cursor` style is applied in the C++ desktop app:

https://github.com/rstudio/rstudio/blob/c24322d993dd07233c14a95824c7a57112a7c24b/src/cpp/desktop/DesktopBrowserWindow.cpp#L270-L276

For Electron:

https://github.com/rstudio/rstudio/blob/c24322d993dd07233c14a95824c7a57112a7c24b/src/node/desktop/src/main/desktop-browser-window.ts#L238-L246

The CSS is here:

https://github.com/rstudio/rstudio/blob/c24322d993dd07233c14a95824c7a57112a7c24b/src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css#L988-L993

**Comment by matheustavaresdev** [comment]
@gtritchie as the action when interacting with this element can resize the window to any extent, I have set it to be just like it is right now on the regular RStudio app.

https://github.com/rstudio/rstudio/blob/c24322d993dd07233c14a95824c7a57112a7c24b/src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css#L988-L993

Regarding the above, I'm not sure why those icons are being used, but I have added a code that fixes the problem and should also get rid of it for every platform. Please let me know if this PR ( #10288 ) brings the desired result, or if I should do some code cleanup or take another approach!

**Comment by gtritchie** [comment]
Verified that I'm seeing the expected cursor for the splitters. Tried on Mac, Windows, and Ubuntu 20, using Electron 2022.06.0-daily+247.
