### ISSUE TITLE
Editing and navigation slow when many code sections are collapsed

### ISSUE THREAD

**Issue by TaylorRPatterson** [rstudio/rstudio#9683]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1717
    OS Version      : macOS Catalina v 10.15.7
    R Version       : 4.1.0 (2021-05-18)

### Steps to reproduce the problem

Unsure, creating many empty sections in a new .R file does not recreate the problem alone. Many code sections with contents may be required.

### Describe the problem in detail

I have a .R source file that is ~5k lines with around 40 code sections, mostly related to creating figures with ggplot. Recently, editing text has become extremely slow, laggy, or delayed. Navigation and other actions in R studio are also delayed, such as switching between panes or source file tabs.

The delays and slowness are observed even when no code has been run, R studio has been restarted, the console cleared, no packages loaded and no objects are in the environment.

The slowness appears to be somehow related to the collapsed sections. If all sections are expanded, editing text and navigation does not have a noticeable delay.

Other, smaller .R files open in separate tabs do not have the issue; editing and navigation within source files and around R studio are as expected.

Things I've tried: 
Disabling diagnostics, checking zoom level, clearing console, restarting R, R Studio, and machine.

Diagnostics request log shows that many "get_events" are taking a long time.

### Describe the behavior you expected

Editing and inputing text to be without delay. Navigation within source files, between panes, and within R studio menus to be quick and without delay.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Can you please share a reproducible example? You could share an example document that, when all sections are collapsed, the slowness is observed. The following didn't reproduce any slowness for me:

```
# Section
print(1 + 1)

< ... repeat 1000 times >
```

**Comment by TaylorRPatterson** [comment]
That example also didn't reproduce the issue for me.

While trying to create an example I tried putting several types of content within each section of 1000 sections. The thing that produced the most noticeable delays when all sections were collapsed was actually comment lines. 

Each of my sections, when expanded, looks like this:

```
# section 1 ----
# comment line 1 that contains no functions
# comment line 2 that is longer but contains no functions
# comment line 3 that is slightly longer yet but contains no functions
# comment line 4 that is shorter than the last
```

With 1000 such sections, when all the sections were collapsed, I observe the slowness most obviously in the later sections (e.g.  section 995). Collapsing and expanding the lower sections is slightly delayed, as is cursor placement and movement occasionally.

**Comment by mdgrant** [comment]
I have a similar problem with large markdown files. I noticed the issue sometime after version RStudio-1.4.1120.  I have gone back to that version because the collapsing hangs interminably at times.  With the older version all works just fine. The attached video shows it with a link to a version of the file. 

https://user-images.githubusercontent.com/10179515/134087749-1e992ef6-674b-41ef-90e8-b35434c34a72.mov

A version of the file is here https://github.com/mdgrant/Fasting/blob/master/analysis/cho_final.Rmd
