### ISSUE TITLE
macOS build doesn't include `-daily-` in filename

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9684]
### System details

    RStudio Edition : Both
    RStudio Version : 2017.0.280+
    OS Version      :  macOS
    R Version       : N/A

### Steps to reproduce the problem

Look at dailies.rstudio.com.

### Describe the problem in detail

The macOS daily builds don't have `-daily-` in their filenames, but all the other builds do.

![image](https://user-images.githubusercontent.com/470418/127710427-380c72f9-3925-4092-ab53-e463932c0989.png)

The same is true for Desktop Pro.

### Describe the behavior you expected

All builds (or none of them) should have `-daily-` in their filenames.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The (likely) implicated code: https://github.com/rstudio/rstudio/blob/d4434f596515fe4eb3b40fc301e6fdb6dbcb035e/package/osx/make-package#L56-L77
