### ISSUE TITLE
Diagnostics alter local R session

### ISSUE THREAD

**Issue by TimTaylor** [rstudio/rstudio#9692]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1717
    OS Version      : Fedora 34
    R Version       :  4.0.5

### Steps to reproduce the problem
Ensure you have an empty .Rprofile and then run the following code line by line
```r
f <- tempfile(fileext = ".R")
file.create(f)
cat("xts::as.xts(Sys.Date())", file = f)
library(dang)
sessionInfo()
file.edit(f)
sessionInfo()
unlink(f)
```
### Describe the problem in detail
After running the `file.edit` command above I see the following appear in my console window
```r
Registered S3 method overwritten by 'xts':
  method    from
  print.xts dang
```
Full output from console below:
```r
> f <- tempfile(fileext = ".R")
> file.create(f)
[1] TRUE
> cat("xts::as.xts(Sys.Date())", file = f)
> library(dang)
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 34 (Container Image)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dang_0.0.13

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5   
> file.edit(f)
Registered S3 method overwritten by 'xts':
  method    from
  print.xts dang
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 34 (Container Image)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dang_0.0.13

loaded via a namespace (and not attached):
[1] zoo_1.8-9       compiler_4.0.5  tools_4.0.5     xts_0.12.1      grid_4.0.5     
[6] lattice_0.20-44
```
I can stop this happening by turning of diagnostics.

### Describe the behavior you expected
I would not expect opening a file to modify my local R session. If there is no way to have diagnostics run without affecting the local R session then, then perhaps they should default to being off?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
If you turn off the package suggestor (global options -> code -> diagnostics -> Prompt to install missing R packages) does that resolve the problem?  It would help for us to know which specific diagnostics is causing the problem.

**Comment by TimTaylor** [comment]
No that is not the one. The trigger is the `show diagnostics for R` option (global options -> code -> diagnostics -> Show diagnostics for R)). I have confirmed this with all other options unchecked.

**Comment by TimTaylor** [comment]
FI - this is likely the issue in https://github.com/rstudio/rstudio/issues/8072 and possibly in https://github.com/rstudio/rstudio/issues/6378

**Comment by wlandau** [comment]
Could https://github.com/Rdatatable/data.table/issues/5103 be an instance of this issue?

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+245 on Windows 11. 
- All diagnostics turned on, to be safe.
- The message doesn't appear when opening the file. It appears when the code inside the file is run, as expected. (But if I'm wrong about this, please let me know!)
