### ISSUE TITLE
Outline Indentation is wrong when putting Comments inside brackets

### ISSUE THREAD

**Issue by zerweck** [rstudio/rstudio#9701]
### System details

    RStudio Edition : Desktop
    RStudio Version: 1.4.1717  
    OS Version: Windows 10 
    R Version: Both 3.6.3 or 4.1.0  

### Steps to reproduce the problem
Open an empty file, open outline (CTR-Shift-o) and compare indentation for these two snippets:
```R
## asd ####
## asd ####
## asd ####
{
}
```

```R

{
## asd ####
## asd ####
## asd ####
}
```

![XLKSHOcnNl](https://user-images.githubusercontent.com/5678151/128350630-6cd702ee-e858-44a3-83bb-976f5823107d.gif)

### Describe the problem in detail
The Indentation does add 1 additional indentation space after the first magic comment
### Describe the behavior you expected
All Indentations should be 2 spaces in for the 3 magic comments

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@zerweck Thank you for raising this! I can't reproduce it, though. Could you grab a screenshot of the editing global options? <kbd>Tools -> Global Options -> Code -> Editing</kbd>

**Comment by zerweck** [comment]
@ronblum sure:
![image](https://user-images.githubusercontent.com/5678151/128485160-35172737-987b-47ba-8cd8-0caddef6942f.png)

**Comment by kevinushey** [comment]
FWIW I was able to reproduce locally (both on Windows and macOS).
