### ISSUE TITLE
revoked_cookie table not getting updated when a user logs out

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9705]
### System details

    RStudio Edition : Server (open source)
    RStudio Version : 1.4.1717 and 2021-08.0.294
    OS Version      : Ubuntu 18.04.5 and RHEL 8.4
    R Version       : 4.1.0

### Steps to reproduce the problem

1. In a web browser, log in as a user.
2. Log out.
3. Check the `revoked_cookie` table for a new user entry:
    - In 1.4, `sqlite3 /var/lib/rstudio-server/rstudio.sqlite`, and in 2021-08.0, `sqlite3 /var/lib/rstudio-server/rstudio-os.sqlite`
    - Execute `select * from revoked_cookie ;`

### Describe the problem in detail

No new entries are added to the `revoked_cookie` table.

### Describe the behavior you expected

Records in `revoked_cookie` should be updated or inserted when a user logs out. This is an issue in the open source version of RStudio Server; it appears to work in RStudio Workstation.

Notes:
1. If an upgrade from 1.3 was involved, there will be records that were migrated from the revocation file.
2. This is not a regression, as it's also the case in 1.4.
3. I'm assuming that the table should be populated, since a) the file was updated in 1.3, and b) the tables is updated in the pro server.
4. I don't see any errors or warnings in `rserver.log` or `rsession-XXX.log`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jeffvroom** [comment]
This problem turned out to be incorrect permissions on the /var/lib/rstudio-server directory. The rstudio-server user needs to have write permission over both the rstudio-os.sqlite file and the directory the file is in. An obstacle in finding this was [this issue](https://github.com/rstudio/rstudio/issues/9715) that hid the database error. 

As for this issue, it seems like rserver does not update the permissions of  the /var/lib/rstudio-server directory when they do not allow write access so I'm leaving this open. Are they ok on clean install or is this still a high priority?

**Comment by ronblum** [comment]
It looks like RStudio Workbench is creating the `/var/lib/rstudio-server` directory with rstudio/rstudio ownership, but RStudio Server open source creates it with root/root. The SQLite file is rstudio-server/rstudio-server in both cases. Could this be the issue? Both were with clean installations. Examples:


**RHEL 7.9**

*PRO*
> [root@ip-172-98-22-110 ec2-user]# echo ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server/rstudio*.sqlite ; rstudio-server version ; source /etc/os-release ; echo $PRETTY_NAME ; echo
> 
> /var/lib/rstudio-server 755 drwxr-xr-x user:rstudio-server group:rstudio-server
/var/lib/rstudio-server/rstudio.sqlite 644 -rw-r--r-- user:rstudio-server group:rstudio-server
2021-08.0.297-1 Workbench (Ghost Orchid) for CentOS 7
Red Hat Enterprise Linux Server 7.9 (Maipo)


*OPEN SOURCE*

> [root@ip-172-98-22-110 ec2-user]# echo ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server/rstudio*.sqlite ; rstudio-server version ; source /etc/os-release ; echo $PRETTY_NAME ; echo
>
> /var/lib/rstudio-server 755 drwxr-xr-x user:root group:root
/var/lib/rstudio-server/rstudio-os.sqlite 644 -rw-r--r-- user:rstudio-server group:rstudio-server
2021-08.0.297 (Ghost Orchid) for CentOS 7
Red Hat Enterprise Linux Server 7.9 (Maipo)


**UBUNTU 18**

*PRO*

> root@ip-172-98-29-70:/home/ubuntu# echo ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server/rstudio*.sqlite ; rstudio-server version ; source /etc/os-release ; echo $PRETTY_NAME ; echo
>
> /var/lib/rstudio-server 755 drwxr-xr-x user:rstudio-server group:rstudio-server
/var/lib/rstudio-server/rstudio.sqlite 644 -rw-r--r-- user:rstudio-server group:rstudio-server
2021-08.0.297-1 Workbench (Ghost Orchid) for Ubuntu Bionic
Ubuntu 18.04.5 LTS

*OPEN SOURCE*

> root@ip-172-98-29-70:/home/ubuntu# echo ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server ; stat -c "%n %a %A user:%U group:%G" /var/lib/rstudio-server/rstudio*.sqlite ; rstudio-server version ; source /etc/os-release ; echo $PRETTY_NAME ; echo
>
> /var/lib/rstudio-server 755 drwxr-xr-x user:root group:root
/var/lib/rstudio-server/rstudio-os.sqlite 644 -rw-r--r-- user:rstudio-server group:rstudio-server
2021-08.0.297 (Ghost Orchid) for Ubuntu Bionic
Ubuntu 18.04.5 LTS

**Comment by ronblum** [comment]
Checked: Changing the ownership of `/var/lib/rstudio-server` to rstudio-server/rstudio-server with

`chown rstudio-server:rstudio-server /var/lib/rstudio-server/`

fixes this.
