### ISSUE TITLE
Treat "Caption/Alt" field for images differently depending on file type

### ISSUE THREAD

**Issue by pommevilla** [rstudio/rstudio#9713]
The current 'Edit Attributes' menu for Images in the Visual Editor has these options:

![image](https://user-images.githubusercontent.com/6981612/128758089-4e8cff2a-6517-45de-8fcc-15c606a96600.png)

I suggest the "Caption/Alt" field be treated differently depending on the file type. 

## Markdown/R Markdown  files

For Markdown/ R Markdown files, this field should be renamed 'Alt text'. Here's the 'Edit Attributes' window:
![image](https://user-images.githubusercontent.com/6981612/128758545-77a5de9c-4156-44d8-bed2-ec5d75d027c9.png)

The Visual Editor writes the following Markdown: `![This is alt text.](images/visual-editing-attributes.png)`

And the alt text renders as expected:

![image](https://user-images.githubusercontent.com/6981612/128758689-fc0fb313-2d9c-45dc-a108-93dd5261c8df.png)

Removing the "Caption" text from this field will prevent some confusion from people trying to add captions to images in pure Markdown documents.

## Quarto files

For `qmd` files, I suggest that "Caption" and "Alt text" get their own separate boxes. While it is currently possible to add alt-text in Visual Editor using the Other section under Attributes, it'll be clearer to the user if the caption and alt-text fields are separated for Quarto documents. 

Here's an example:
![image](https://user-images.githubusercontent.com/6981612/128768649-011af665-0279-40ca-98d3-acd1a97a8d5f.png)

The caption correctly shows up:

![image](https://user-images.githubusercontent.com/6981612/128768870-623f8c34-d764-46fe-a535-b6f4f71caa48.png)

And creates this HTML:

![image](https://user-images.githubusercontent.com/6981612/128768767-7ee3d47b-fcd8-44ae-a46d-6fe58cdfb928.png)

I can insert alt-text by add the `fig-alt="..."` key/value under attributes:

![image](https://user-images.githubusercontent.com/6981612/128769000-5a8dd1d0-55d3-4de5-b676-efb00f5d66be.png)

and this will render correctly with the caption and the corresponding alt text:

![image](https://user-images.githubusercontent.com/6981612/128769101-cb63da0b-86fa-4fd9-81f1-3db2b3aad7f3.png)

Separating the `Caption/Alt` fields into separate fields for Quarto documents will make it a lot easier for users to use these features without them having to know:

1. The `fig alt` chunk option
1. Where to put it 
1. How to format it

**Comment by ronblum** [comment]
@pommevilla Thank you for the suggestion! I'll mark it for review as part of the Quarto/IDE integration.

**Comment by dragonstyle** [comment]
@jjallaire added a revised figure dialog for Quarto docs (in dailies now!)

![Screen Shot 2021-09-28 at 2 30 59 PM](https://user-images.githubusercontent.com/261654/135145290-57e6bbd0-a126-4220-a66e-02a4dfbe56b2.png)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.02.0+377 on MacOS 12.1.
