### ISSUE TITLE
Log file permissions for rserver change after session start in open source version

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#9715]
### System details

    RStudio Edition : OS
    RStudio Version : latest

### Steps to reproduce the problem

  Enable log-level=debug in logging.conf, start a session in the open source version. Last message is: 

2021-08-09T19:26:21.929080Z [rserver] DEBUG Launched session process for user: mario: /usr/lib/rstudio-server/bin/rsession pid: 73651

   and no more messages will be logged after this point.

   Do ls -l of /var/log/rstudio/rstudio-server/rserver.log and see its now owned by the user who started the session. 

### Describe the problem in detail

Tracked this down to [this line of the function permanentlyDropPriv](https://github.com/rstudio/rstudio/blob/ff9bd9e4e9424e2be8408e07a04dd5daaffec5e9/src/cpp/core/system/PosixSystem.cpp#L2477) that is running after the fork, before the exec for the session. Since we haven't exec'd at this point, but are running as the session user, and have privs, the log destinations are for the parent not the child as expected.

I can see the temporarilyDropPriv does need this call because it's not about to call exec. All of the calls to permentlyDropPriv that I could see are between fork and exec so I think we should just remove that line.

**Comment by astayleraz** [comment]
I verified in version 2021-08.0 Build 317-2 that with a clean install on a Linux machine, /var/lib/rstudio-server is owned and writable by rstudio-server. Closing issue.
