### ISSUE TITLE
Sometimes the arrows don't appear when clicking on a pane border in RStudio Desktop 

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9723]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021-08.0.295
    OS Version      : MacOS 12 beta 21A5294g
    R Version       : 4.1.0

### Steps to reproduce the problem

1. Start RStudio Desktop on MacOS.
2. Switch to another application.
3. Switch back to RStudio.
4. Try dragging the pane borders, to adjust the pane sizes.

### Describe the problem in detail

Sometimes the arrows don't appear.

### Describe the behavior you expected

The arrows should always appear. Clicking into a different application and then back to RStudio usually resolves the problem.

Note:
1. This happens not infrequently, but not consistently.
2. I'm using MacOS 12 beta 21A5294g. Unlike the previous betas, in which many applications—including some OEM ones—had serious issues, the current beta is stable enough that I'd consider this an RStudio concern.
3. I'm marking this as "Electron" in the hope that it fixes this.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Stray click, didn't mean to close.

**Comment by gtritchie** [comment]
I haven't been able to repro this with Electron, so going to close.
