### ISSUE TITLE
Drag-and-drop images link to absolute path in Visual Editor

### ISSUE THREAD

**Issue by pommevilla** [rstudio/rstudio#9734]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2021-08.0.295 "Ghost Orchid" Daily (2317fa73d9d01c15476707bdd767899ff1e175e1, 2021-08-06) for Windows
    OS Version      :  Windows 10
    R Version       : R version 4.1.0 (2021-05-18)

### Steps to reproduce the problem

1. Open a qmd file in R Studio 
1. Switch to Visual Editor
1. Drag and drop an image into the document
1. Check the Markdown path

The file path generated is an absolute path to the image that was dropped into the document. No image folder is created, nor is the image copied into an existing image folder if there is one.

### Describe the problem in detail

The drag and drop functionality for images into the Visual Editor isn't working as expected on my Windows desktop. 
When I drag an image into a Visual Editor document, it creates a link to the original image instead of creating a copy in my current directory.

This happens in `qmd`, `rmd`, and `md` files, and happens whether or not I have an `images` folder in the directory.

### Describe the behavior you expected

1. For the image to be copied into `images/image_name`
1. For the Markdown generated by Visual editor to link to `images/image_name`, 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Addressed with https://github.com/rstudio/rstudio/commit/c4c7ee17d5395633099789e44ab6a394b9be9825

**Comment by GCRev** [comment]
I've verified that this fix works as indented on Windows, in QT Desktop. Drag-and-drop currently doesn't work on Electron Desktop, so that would need to be fixed as a separate issue.

The output generated by pandoc for an image dragged in to the visual editor was the following, which specifies a valid path to a file on my computer.
```markdown
![](images/pause_octagon.PNG)
```
