### ISSUE TITLE
Menu bar clipping; get rid of RStudio classic theme.

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#9738]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717
    OS Version      : window
    R Version       : 3.5.2, 4.1.0, possibly others

### Steps to reproduce the problem
Turn on the "Classic Theme", the menu bar appears clipped off.

![image](https://user-images.githubusercontent.com/5323711/129574493-652214f7-224f-478d-83ef-1dab41d2dbde.png)

### Describe the problem in detail
Starting with Juliet Rose, the Classic theme displays with a clipped menu bar.

Reported on this [community post](https://community.rstudio.com/t/menu-bar-clipping/108508) and support issue #64641. 

The original description in this issue was written before we'd determined the cause:
~~After upgrading to 1.4.1717, some users are experiencing a clipped menu bar. 
The issue appears to be per user, regardless of browser or computer. One user can reproduce the issue on another user's computer, with the same browser, where the computer's owner does not see the issue. This issue only appeared after upgrade to 1.4.1717, and happens in open source and workbench (server), regardless of project or no project opened. Clearing the user's state did not fix the issue.~~

### Describe the behavior you expected
The menu bar should be fully rendered and legible.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment]
Not able to reproduce this one currently. Tried both Open Source and RSW server environments built to 1.4.1717(-3). 

Very odd that this is occurring on a user by user basis, but given that factor not surprising that we're struggling to reproduce it in house (where most test environments are brought up in a 'clean' state. Not sure what info could be gathered on the individual users this seems to be effecting that might help us to reproduce.

Link to relevant [support ticket #64641](https://rstudioide.zendesk.com/agent/tickets/64641).

**Comment by R-Hannibal** [comment]
We found it (thanks @dfalty!) - 

This appears to be a bug caused by setting Global `Options -> Appearance -> RStudio theme: Classic`. Reproduced on both Juliet-Rose and Ghost Orchid builds (2021-08.0.309-5).

**Comment by mikebessuille** [comment]
Could get rid of this theme entirely.

**Comment by jmcphers** [comment]
This is going to be a real chore because even though the "classic" theme doesn't actually work it is still, from a technical perspective, the base theme. The "modern" themes are really just the classic theme with thousands of CSS changes overlaid with an `rstudio-themes-flat` selector. To keep the code clean we really need to get rid of not only the theme as an option but also clean up all the stale CSS, deleting the `.rstudio-themes-flat` selector and making all the style rules it enables the new defaut.

**Comment by markkauf** [comment]
This issue also appeared support issue 67940.

**Comment by GCRev** [comment]
We should be able to close out this issue now. PR #10081 resolves the issue with the menu header's layout issue.
