### ISSUE TITLE
RStudio dailies "latest" aliases are stuck pointing at old builds

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#9743]
It seems with the recent changes in the versioning scheme the `rstudio-daily` cask does not work as intended anymore.

It looks up https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg which points to `RStudio-1.0.264.dmg`:

```
curl https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg                                                                                ✘ 23 09:33:59
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-1.0.264.dmg">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at www.rstudio.org Port 443</address>
</body></html>
```

but I think it should resolve to something like `RStudio-2021-08.0.319.dmg` judging from the list on https://dailies.rstudio.com/rstudio/oss/mac/.

The `RStudio-1.0.264.dmg` lists itself as "Ghost Orchid" (484e78e6, 2021-07-27) for macOS.

I can make a PR to the homebrew cask if needed - but maybe its sufficient to fix the `RStudio-latest.dmg` link?

**Comment by aronatkins** [comment]
Confirmed that this is an issue and other scripted installs that depend on the "latest" redirect are also failing to obtain the most recent daily build.

**Comment by ronblum** [comment]
Also confirmed that it's an issue with builds for other operating systems, e.g. the latest for RStudio Server on Red Hat 7/CentOS 7
https://rstudio.org/download/latest/daily/server/centos8/rstudio-server-rhel-latest-x86_64.rpm is pointing to `rstudio-server-rhel-1.5.244-x86_64.rpm`.


Reference: https://support.rstudio.com/hc/en-us/articles/203842428-Getting-the-newest-IDE-RStudio-builds

**Comment by pat-s** [comment]
I know this issue is still open so you're probably still working on it.
Just wanted to share that the low-level link points to the right file now but it fails to resolve it. Looks like the `+` in `+daily` is stripped for a whitespace which makes the URL fail.

```
curl -L https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg                                                                                                         08:11:18
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>desktop/macos/RStudio-2021.11.0-daily 23.dmg</Key><RequestId>NHAW9S3Z96ZPP4S9</RequestId><HostId>rNhoJueU9JRTOeJB/qJV2V6aRO/Xkb8QCFtoWv7RBgzgB/PFmB2tKyRShl8ldvEiiosQcheSY0o=</HostId></Error>⏎
```

**Comment by ronblum** [comment]
@pat-s Thanks for the update! We're working on it—we've run into a few issues with the `+` in the filename/URL with some services.

In the meantime, you might've noticed that the latest dailies are now for the next release, 2021.12.0 Prairie Trillium. The imminent release, 2021.09.0  Ghost Orchid, is now in preview, and you can grab the latest previews with https://rstudio.org/download/latest/preview/desktop/mac/RStudio-latest.dmg which I confirmed works. (Note that previews aren't updated as frequently as dailies.)

**Comment by ronblum** [comment]
FYI, I just tried out a few of the links. The preview links now download a preview build, but the wrong ones: The current published preview is build 341, but the latest preview links are pointing to build 340.

**Comment by aronatkins** [comment]
Update: `https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg` is now redirecting to `https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-2021.12.0-daily%2B90.dmg`, which is a version from the future!

**Comment by MariaSemple** [comment]
That's correct, we use the expected release date as the edition for our daily builds.

**Comment by eitsupi** [comment]
I found a similar problem, the link from the download site to the GitHub tag also seems to be broken.

https://www.rstudio.com/products/rstudio/download/
![image](https://user-images.githubusercontent.com/50911393/144753592-c21bfcdc-fb9b-4967-9248-939a9d8741f0.png)

It link to https://github.com/rstudio/rstudio/releases/tag/2021.09.1+372

This is probably due to the fact that when we first changed the versioning, we used tags without the prefix `v`, but soon went back to tags with `v`.
correct url: https://github.com/rstudio/rstudio/releases/tag/v2021.09.1+372

**Comment by aronatkins** [comment]
The macOS latest link appears stuck, as well.

This sends us to 2022.01.0-daily+235; the actual latest is 284.

```bash
curl -I https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg
```

```
HTTP/1.1 302 Found
Date: Mon, 06 Dec 2021 20:41:16 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-2022.01.0-daily%2B235.dmg
Content-Type: text/html; charset=iso-8859-1
```

**Comment by ronblum** [comment]
Confirmed that some of the `latest` builds don't download, such as https://rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg, with `wget` and via a web browser. Perhaps the fix in #10026 only fixed the links for stable builds?

**Comment by aronatkins** [comment]
@ronblum The behavior has changed. As of my last comment, the "latest" builds were stuck at an earlier, but valid URL. Now, the latest URL redirects to `https://s3.amazonaws.com/rstudio-ide-build/desktop/mac/RStudio-2022.01.0-daily-290.dmg`, which results in a 404.

**Comment by jeffvroom** [comment]
Yes, the stable links and source tarball links mentioned above are fixed. Most latest daily links are working but some of the desktop links are still broken. I am waiting on builds to test them again. I'll give this the "test" label when they are all working.

**Comment by aronatkins** [comment]
Confirmed that `https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg` now redirects to `https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-2022.01.0-daily-294.dmg`, which downloads and installs successfully.

**Comment by jeffvroom** [comment]
Ok, looks like all of the /latest/daily URLs on this page: https://dailies.rstudio.com/links/ are working except for the xenial platform, which we are no longer building.  Should the xenial links point to an older build (and be displayed with a warning perhaps?) or should we just remove them from that page?  The latest points to an older build but the preview does not work.

Here is the list of URLs I am testing. My script currently just gets the Location of the redirect but I will add at least a 'HEAD' of the file itself to be sure the downloads themselves are available but don't want it to download everything so we can run it more frequently. 

https://rstudio.org/download/latest/daily/desktop/windows/RStudio-latest.exe
https://rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg
https://rstudio.org/download/latest/daily/desktop/bionic/rstudio-latest-amd64.deb
https://rstudio.org/download/latest/daily/desktop/debian9/rstudio-latest-amd64.deb
https://rstudio.org/download/latest/daily/desktop/opensuse15/rstudio-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/desktop/centos7/rstudio-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/desktop/centos8/rstudio-latest-x86_64.rpm

https://rstudio.org/download/latest/daily/server/bionic/rstudio-server-latest-amd64.deb
https://rstudio.org/download/latest/daily/server/debian9/rstudio-server-latest-amd64.deb
https://rstudio.org/download/latest/daily/server/centos8/rstudio-server-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/centos7/rstudio-server-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/bionic/rstudio-workbench-latest-amd64.deb
https://rstudio.org/download/latest/daily/server/opensuse/rstudio-server-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/opensuse15/rstudio-server-latest-x86_64.rpm

https://rstudio.org/download/latest/daily/desktop/bionic/rstudio-pro-latest-amd64.deb
https://rstudio.org/download/latest/daily/desktop/opensuse15/rstudio-pro-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/desktop/debian9/rstudio-pro-latest-amd64.deb
https://rstudio.org/download/latest/daily/desktop/centos7/rstudio-pro-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/desktop/centos8/rstudio-pro-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/desktop/centos7/rstudio-latest-x86_64.rpm

https://rstudio.org/download/latest/daily/server/opensuse/rstudio-workbench-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/opensuse15/rstudio-workbench-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/debian9/rstudio-workbench-latest-amd64.deb
https://rstudio.org/download/latest/daily/server/opensuse15/rstudio-workbench-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/centos7/rstudio-workbench-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/centos8/rstudio-workbench-rhel-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/server/bionic/rstudio-workbench-latest-amd64.deb

https://rstudio.org/download/latest/daily/desktop/mac/RStudio-pro-latest.dmg
https://rstudio.org/download/latest/daily/desktop/bionic/rstudio-pro-latest-amd64.deb
https://rstudio.org/download/latest/daily/desktop/opensuse15/rstudio-pro-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/desktop/debian9/rstudio-pro-latest-amd64.deb
https://rstudio.org/download/latest/daily/desktop/centos7/rstudio-pro-latest-x86_64.rpm
https://rstudio.org/download/latest/daily/desktop/centos8/rstudio-pro-latest-x86_64.rpm

**Comment by aronatkins** [comment]
Unclear if something changed again, but macOS daily link is again redirecting to an S3 location that returns 404.

```
https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg
=> 
https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-2022.01.0-daily-309.dmg
=> 404
```

The https://dailies.rstudio.com page indicates that the daily+308 build is the daily; maybe there is a timing issue or an error that caused part of the updates to flow?

**Comment by ronblum** [comment]
FWIW, pro for MacOS works: https://rstudio.org/download/latest/daily/desktop/mac/RStudio-pro-latest.dmg

**Comment by ronblum** [comment]
Note: Pro is still at build 300, while open source is now at 308. Could that have made a difference?

**Comment by jeffvroom** [comment]
Thanks for catching that! I put the mac desktop link in pro linux build. I should have just added it do the mac pro build... I'll fix that!

**Comment by ronblum** [comment]
The MacOS open source RStudio Desktop download link now works for me. @aronatkins Can you confirm that it works?

**Comment by aronatkins** [comment]
Confirmed. The https://dailies.rstudio.com page reports 2022.02.0-daily+316 as the latest daily, and that is the version referenced by https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg.

My fetch-and-install script (https://github.com/aronatkins/install-rstudio-daily) has been updated to handle the current version/filename changes (plus-sign in version; minus-sign in filename). It successfully installs the macOS dailies.

**Comment by ronblum** [comment]
I think that's it—@jeffvroom is that correct?

**Comment by jeffvroom** [comment]
Yes, I think this one is finally fixed for all of the platforms. I updated this page as well:

https://dailies.rstudio.com/links/

so that includes all of the daily, preview, and stable links for all platforms that we build. My test script shows that all the links are downloading the correct version. It would be nice to run these on a periodic basis so we are alerted if the links break.

**Comment by mikebessuille** [comment]
So this can be closed?

**Comment by ronblum** [comment]
Shortly! I'm looking at the new page, as well to see if anything needs to be updated in the support article.

**Comment by ronblum** [comment]
Verified:
- Links page https://dailies.rstudio.com/links/ : A sample of the links, including the known repeat offenders
- Support article https://support.rstudio.com/hc/en-us/articles/203842428-Getting-the-newest-IDE-RStudio-builds. : Links are current. Need to make one small unrelated tweak, but I'll file that separately.

**Comment by ronblum** [comment]
Note: Also checked with
- Dead Link Checker: https://www.deadlinkchecker.com
- W3C Link Checker: https://validator.w3.org/checklink?uri=https%3A%2F%2Fdailies.rstudio.com%2Flinks%2F&hide_type=all&depth=&check=Check

**Dead Link Checker Summary**
<img width="363" alt="dead_link_checker" src="https://user-images.githubusercontent.com/31009952/146409417-1d823d71-da52-44a5-9cc4-1faaf31fa8c7.png">

**W3C Link Checker Summary**
<img width="1039" alt="w3c_link_checker_results" src="https://user-images.githubusercontent.com/31009952/146410787-61285336-e0e9-409a-b467-db3b99b50702.png">

**W3C Link Checker Details**
[w3c_link_checker_results.txt](https://github.com/rstudio/rstudio-pro/files/7728909/w3c_link_checker_results.txt)
