### ISSUE TITLE
version1.4 can not display Chinese reference in Rmarkdown :@Citation for zotero 

### ISSUE THREAD

**Issue by swcyo** [rstudio/rstudio#9745]
My system is Macos. In the RStudio version1.4, you added the fuction of  visual R markdown, it's a fantastic function. 
However, when I  added the Rmarkdown file, after using @Citation to cite the references from zotero-my library,  I had found the Chinese text cannot be displayed. After knitr, it all displays '???'.Then I still found in the automatically generated .bib format, the Chinese  characters are all ???, but if you manually modify the .bib file or directly use the bib file exported by Zotero, the Chinese characters can be displayed normally

**Comment by ronblum** [comment]
@swcyo Thank you for raising this! I can reproduce this in RStudio Desktop 2021-08.0-317 on MacOS 12 beta, as well. We'll review this as part of our ongoing development of RStudio.

**Comment by astayleraz** [comment]
Verified in 2022.01.0-daily+205 on mac os that zotero now shows @nihaoya instead of @cite. We do not have zotero setup with our current web automation, so we are not going to cover this case in QA automation. Closing issue.
