### ISSUE TITLE
MS Edge version 92 gets unsupported browser error from Rstudio-Server, even though minimum version is listed as 79

### ISSUE THREAD

**Issue by timcera** [rstudio/rstudio#9748]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717-1
    OS Version      : Redhat 7.9
    R Version       : 3.6.1

### Steps to reproduce the problem

Use what should be a acceptable version of Edge (>79) and get an unsupported browser page.

### Describe the problem in detail

Use Edge version 92.0.902.73 (Official build) (64-bit) and get the following unsupported browser page.

> Your web browser is not supported by RStudio.
> 
> RStudio requires one of the following browser versions (or higher):
> •Firefox 68
> •Safari 12.1
> •Google Chrome 71
> •Microsoft Edge 79
> 
> See the RStudio Platform Support page for more information about browser support in RStudio products.

### Describe the behavior you expected

MS Edge 92 should work if version 79 is indeed the minimum version required.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@timcera Thank you for raising this! I can't reproduce it, though, using the same version of Edge. At which point does it fail? Is it in the IDE, the home page, clicking from the home page to a session, etc?

**Comment by timcera** [comment]
The home page.
![Screenshot 2021-08-23 12 10 38](https://user-images.githubusercontent.com/297142/130481126-d928299f-f768-42ea-bc16-cbc0c1d8b91a.png)

**Comment by mikebessuille** [comment]
Is it possible that Edge is in IE compatibility mode?  Could you paste the results from https://www.whatismybrowser.com/

**Comment by timcera** [comment]
Says Edge 92 on Windows 10

Here are details:
[https://www.whatismybrowser.com/w/XKQCXHH?utm_source=whatismybrowsercom&utm_medium=internal&utm_campaign=homepage&utm_content=unique-url-readout](url)
