### ISSUE TITLE
Zotero entry with Chinese author and title uses generic "cite" for citation key

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9754]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021-08.0-317
    OS Version      : MacOS 12 beta
    R Version       : 4.1.0

### Steps to reproduce the problem

1. Create an entry in Zotero that uses Chinese (simplified) for the title and author. For example:
    - Title: `早上好`
    - Author last name: `你好呀`
    - Note that Zotero generates a citation key using pinyin romanization, `nihaoyaZaoShangHao`
<img width="331" alt="pinyin_zotero_key" src="https://user-images.githubusercontent.com/31009952/130081377-afdca318-808f-44bb-87cb-a9d9a298a329.png">

2. Create an R Markdown file in RStudio Desktop.
3. Switch to visual mode, if not already in it.
4. <kbd>Insert -> Citation</kbd>
5. Choose <kbd>My Sources -> Zotero</kbd> to show the available Zotero entries.

### Describe the problem in detail

The entry shows the citation key as `@cite` instead of Zotero's key.

<img width="921" alt="chinese_zotero_entry" src="https://user-images.githubusercontent.com/31009952/130079578-14ecad93-7b01-4d3b-afd9-085fe3880407.png">

### Describe the behavior you expected

Use the citation key that Zotero uses. 

[Note: See also #9745.]

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment]
Our support for non-ascii characters in citekeys has been improved significantly as of this commit: 9d1a78ee75c2fc8f26bcda31b702e7daea57c429.

We now will pinyinize or transliterate non ascii characters to try to provide the most usable cite key that we can. Note that users can always provide their own citekeys (either by editing the cite key when inserting or by pinning a cite key in Zotero if they're using Zotero).

**Comment by astayleraz** [comment]
Verified in 2022.01.0-daily+205 on mac os that zotero now shows @nihaoya instead of @cite. We do not have zotero setup with our current web automation, so we are not going to cover this case in QA automation. Closing issue.
