### ISSUE TITLE
Ctl+K failed to add a hyperlink in visual mode

### ISSUE THREAD

**Issue by Robinlovelace** [rstudio/rstudio#9763]
Apologies for lack of detail but basically same set-up as in #9762. Simple issue: the shortcut failed but the GUI button worked when I tried it just now. Opening in case of use/interest for RStudio developers and the wider community.

![Peek 2021-08-21 13-40](https://user-images.githubusercontent.com/1825120/130322164-ba6f51bb-4b51-4c0f-ac8e-13c677d2e408.gif)

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Robinlovelace Thank you! I can reproduce this in 
- RStudio Server 2021.09.0-preview+337 on Ubuntu 20.04 via Firefox on Ubuntu 20.04

Note that
1) The equivalent MacOS command <kbd>Cmd + K</kbd> works in RStudio Desktop 2021.09.0-preview+337
2) The command palette in Firefox on Ubuntu 20.04 shows <kbd>Ctrl + K</kbd> as the right shortcut:
<img width="602" alt="ubuntu_visual_link" src="https://user-images.githubusercontent.com/31009952/130620441-10d085db-e151-4b43-bdd6-9162ff561f12.png">

**Comment by jjallaire** [comment]
Addressed with https://github.com/rstudio/rstudio/commit/998bf4710614ad6478c18888c5f9fa7e95cef2df

**Comment by AndrewMcClain** [comment]
Confirmed fixed in:
 - RStudio Server 2022.01.0-daily-233
 - RStudio Desktop 2022.01.0-daily-233

In both cases produces a working link in visual mode.

**Comment by Robinlovelace** [comment]
:tada: excellent work, many thanks!
