### ISSUE TITLE
Update links to cheatsheets

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#9764]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.1717
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.1 (2021-08-10)

### Steps to reproduce the problem
1 Click: 
![image](https://user-images.githubusercontent.com/12725868/130337212-86bedeec-1ce3-4ac7-8f71-63f628272e22.png)
2. Get 404 error.

### Describe the problem in detail

Links to some of the cheatsheets are broken. Related: 
- https://github.com/rstudio/cheatsheets/issues/202

### Describe the behavior you expected

Update RStudio to open all the cheatsheets correctly. 

There were new cheatsheets added this summer, so in the next RStudio release consider if any new cheatsheets should be included in or any current cheatsheets excluded from the menu.

**Comment by ronblum** [comment]
@GegznaV Thanks! It looks like the two that aren't working are 
- Data Visualization with ggplo2
- R Markdown Cheat Sheet

We'll review this as part of our ongoing development, as this is also an issue in RStudio Desktop and Server 2021.09.0-preview+337.

**Comment by mine-cetinkaya-rundel** [comment]
- Data Visualization with ggplot2 should go to https://github.com/rstudio/cheatsheets/blob/master/data-visualization.pdf
- R Markdown Cheat Sheet should go to https://github.com/rstudio/cheatsheets/blob/master/rmarkdown.pdf

**Comment by averiperny** [comment]
The R Markdown reference guide has also been removed from the cheat sheet website.

**Comment by ronblum** [comment]
@mine-cetinkaya-rundel I think that would be useful, or perhaps a redirect from the old locations to the new ones?

**Comment by mine-cetinkaya-rundel** [comment]
All links in the current IDE are now functional as I added a copy of the new cheatsheets with their old names into the cheatsheets repo. However the following would be good to do nonetheless:

1. Update the data visualization and R Markdown links:
    - Data Visualization with ggplot2 should go to https://github.com/rstudio/cheatsheets/blob/master/data-visualization.pdf
    - R Markdown Cheat Sheet should go to https://github.com/rstudio/cheatsheets/blob/master/rmarkdown.pdf
 2. Remove the link to the R Markdown Reference Guide sheet (we’re no longer maintaining this resource in this format, so it might get out of date at some point)
 3. Update names cheatsheets to be "Sentence case" and specifically the following cheat sheets whose titles have changed:
     - "List manipulation with purrr" = "Apply functions with purrr cheatsheet" 
     - "Web applications with shiny" = "Interactive wep apps with shiny"
     - "Interfacing Spark with sparklyr = "Data science in Spark with sparklyr"
     - "R Markdown Cheat Sheet" = "Dynamic documents with rmarkdown"
 4. Add the following cheat sheets (note that there are a few other featured/updated cheatsheets but the following were chosen as I expect they're equally commonly used as the ones already on the list)
     - "Data tidying with tidyr": https://github.com/rstudio/cheatsheets/raw/master/tidyr.pdf
     - "Data import with readr, readxl, and googlesheets4": https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf
     - "Python with R and reticulate": https://github.com/rstudio/cheatsheets/raw/master/reticulate.pdf

**Comment by assignUser** [comment]
All links (except "Browse cheatsheets") are now broken due to rstudio/cheatsheets#218

**Comment by jmcphers** [comment]
Should be all fixed now, thank you for the ping!

**Comment by rich-rstudio** [comment]
verified on 2022.01.0 Build 253
