### ISSUE TITLE
Configuration that loses X-CSRF-Token causes infinite sign in loop

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9768]
### System details

    RStudio Edition : Server
    RStudio Version : 2021.09.0

### Steps to reproduce the problem

1. Put RStudio behind a proxy that discards or re-uses the `X-CSRF-Token` header. A simple way to do this is to put RStudio behind an nginx instance with `proxy_set_header X-CSRF-Token ""`. 
2. Attempt to sign in. 

### Describe the problem in detail

The browser enters an infinite redirect sign-in loop that never reaches an R session.

This happens through a medium-sized string of dominoes:

1. Sign-in succeeds
2. The user is redirected to the IDE for their R session
3. The browser  attempts to call `client-init` to establish the connection to the back end
4. That RPC is rejected because it is missing the `X-CSRF-Token` HTTP header (and/or the header has the wrong value), with an Unauthorized status
5. The browser sees that the request is Unauthorized and assumes that it's because the login cookie is stale. It calls `auth-update-credentials`.
6. This also fails (as an aside it looks like no actual auth providers implement this?), so the browser assumes the user is not authorized and sends them to sign in again
7. The sign in page sees that the user has valid login cookies, so it goes to step 2. 

### Describe the behavior you expected

RStudio can't work if the CSRF header is dropped, but the observed behavior should not be an infinite redirect loop with no logging. The user should get some kind of error indicating a security issue, and the admin should be able to troubleshoot it. 

See also https://github.com/rstudio/rstudio-pro/issues/2931.

**Comment by jmcphers** [comment]
I think the best place to break this loop is probably at (5) above; we need the browser (client) to be able to distinguish between "this request was denied due to bad login cookies" and "this request was denied due to missing CSRF data".

**Comment by jeffvroom** [comment]
Addressed in: https://github.com/rstudio/rstudio/pull/9927

The IDE will now display a specific error message about the missing CSRF header (in addition to the server log) so this one should be easy to diagnose now.  To test it, access RStudio via an nginx proxy server and add:

         `  proxy_set_header X-RS-CSRF-Token "";`

**Comment by rich-rstudio** [comment]
verified on 2022.01.0-daily+129.pro1
