### ISSUE TITLE
submit reticulate 1.21 to CRAN

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9773]
To coincide with the RStudio GO release (or soon after).

The CRAN submission channel is closed until September 1st, so we'll have to do this soon after CRAN opens back up.

**Comment by mikebessuille** [comment]
@jjallaire would you mind taking care of this update in early Sept, as Kevin will be out of the office?

**Comment by mikebessuille** [comment]
@kevinushey, Jonathan tells me that only you can submit this to Cran...  Would you mind doing that?

**Comment by kevinushey** [comment]
reticulate 1.21 is now on CRAN.

**Comment by jmcphers** [comment]
@kevinushey Do we need to bump our reticulate dependency to 1.21 on the IDE side?

**Comment by kevinushey** [comment]
Thanks for catching that. I don't think it's absolutely vital; there are some important changes but I don't know if we want to force users of R (< 4.0.0) to install reticulate from sources.
