### ISSUE TITLE
Redirect always uses HTTP protocol.

### ISSUE THREAD

**Issue by mahsoud** [rstudio/rstudio#9777]
### System details

    RStudio Edition : Server
    RStudio Version : v1.4.1717
    OS Version      :  Ubuntu 18.04.5 LTS
    R Version       :  4.1.1

### Steps to reproduce the problem

Install RStudio Server with default config on a ubuntu system (AWS EC2) without enabling SSL
Deploy an AWS ALB with an SSL certificate associated. 
Forward traffic from ALB to target group containing VM with RStudio installed.
Access RStudio via AWS ALB

### Describe the problem in detail

Found that RStudio Server v1.4.1717; when deployed behind an AWS ALB that terminates SSL has an issue with sign in if since rstudio redirects always to HTTP, thus I am receiving "400 Bad Request: The plain HTTP request was sent to HTTPS port" from load balancer at redirect to /auth-sign-in

### Describe the behaviour you expected

Redirect URL protocol should be kept from the original request.

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@mahsoud, could you please verify that this works as you expect with Ghost Orchid?  Previews are available now, and it will be released in early Sept.

**Comment by ronblum** [comment]
Note: Previews are available at https://www.rstudio.com/products/rstudio/download/preview/.
