### ISSUE TITLE
Arrow icons are missing on the column switcher

### ISSUE THREAD

**Issue by andresmorago** [rstudio/rstudio#9783]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1106
    OS Version      :  Debian 9
    R Version       :  3.6.3

### Steps to reproduce the problem
```
df = data.frame(replicate(100, sample(0:1,10, rep=TRUE)))
View(df)
```

### Describe the problem in detail
When viewing a wide dataframe, the arrows to switch from one columns page to another one are missing

![imagen](https://user-images.githubusercontent.com/13720514/131174614-6a81c30a-9573-4c9b-b0f8-e5232cd8afb9.png)

### Describe the behavior you expected
![imagen](https://user-images.githubusercontent.com/13720514/131174815-386ce493-279e-49c9-a9c6-f22c01aa3043.png)

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@andresmorago Thank you for raising the issue! I can also reproduce it in RStudio Server 2021.09.0-preview+340 on Red Hat 7.9 via Safari on MacOS. We'll review this as part of our ongoing development of RStudio.

**Comment by jmcphers** [comment]
Currently tracked in https://github.com/rstudio/rstudio/issues/9221.
