### ISSUE TITLE
Autocomplete for column names does not work in pipeline when package name is specified

### ISSUE THREAD

**Issue by nmarantz** [rstudio/rstudio#9786]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      :  MacOS 11.5.1
    R Version       :  4.1.0

### Steps to reproduce the problem
1. Load `tidyverse` and create tibble from the mtcars dataset:
```
library(tidyverse)
df <- tibble(mtcars)
```
2. Type: `df %>% dplyr::filter(gea)` Note: auto-complete does not suggest gear:
![Screen Shot 2021-08-27 at 2 58 01 PM](https://user-images.githubusercontent.com/25621920/131192868-11409bf5-d104-4995-9712-7d9f0b6599aa.png)

### Describe the problem in detail
Auto-complete does not suggest column names when the data frame is piped and the function's package name is specified. 

### Describe the behavior you expected
Auto-complete _does_ suggest column names when the data frame is piped and the function's package name is _not_ specified. For example, typing `df %>% filter(gea)` yields: 
![Screen Shot 2021-08-27 at 2 50 13 PM](https://user-images.githubusercontent.com/25621920/131193140-3958564d-e315-4d19-a963-7c44aa9430d2.png)

Auto-complete also suggests columns names when the function's package name is specified and the data fame is _not_ piped. For example, typing `dplyr::filter(df$gea)` yields: 
![Screen Shot 2021-08-27 at 2 59 35 PM](https://user-images.githubusercontent.com/25621920/131193258-2d07ad2e-221c-4c6f-8068-226ad2d5cd66.png)

I expected consistent behavior (i.e., the suggestion of column names) when the data frame is piped and the package name is specified.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@nmarantz Thank you for raising this! I can reproduce the issue in
- RStudio Desktop 2021.09.0-preview+337 on MacOS 12 beta
- RStudio Server 2021.09.0-preview+340 on Red Hat 7.9 via Safari on MacOS 12 beta

We'll review this as we continue to develop RStudio.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+301 on MacOS 13.2. Tested with both the magrittr/dplyr and native R pipes.

```
df %>% dplyr::filter(gea)
df |> dplyr::filter(gea)
```
