### ISSUE TITLE
Redirect link to RStudio daily build broken, breaks homebrew

### ISSUE THREAD

**Issue by noamross** [rstudio/rstudio#9788]
The stable URL to the RStudio build is broken.  This breaks the [Homebrew cask](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/rstudio-daily.rb), at least.

Specifically, the URL

    https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg

does a 302 redirect to 

    https://s3.amazonaws.com/rstudio-ide-build/desktop/macos/RStudio-2021.11.0-daily+17.dmg

However, this can't be downloaded, and at this URL one gets

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>desktop/macos/RStudio-2021.11.0-daily 17.dmg</Key>
<RequestId>ZXM75BZ1C07VDPWZ</RequestId>
<HostId>
rexpRQafIUgwAMRUGYL5sDH4Blnh2NkskNwjOYD+mR6z6iAMv+bwuWY/nP56dh0bjnbRqt9LkLM=
</HostId>
</Error>
```

I believe this is because AWS can't handle the unescaped `+` in the URL. (Note that it disappears in the `<Key>` field above.)  If one replaces the `+` in the URL with `%2B`, the download works correctly. 

Regular and preview links work fine, probably because they don't have a `+` in them.

**Comment by ronblum** [comment]
@noamross Thank you for raising this! This is one of the failures described in https://github.com/rstudio/rstudio/issues/9743#issuecomment-906539330, so I'm marking this as a duplicate.
