### ISSUE TITLE
Context menu does not take focus when opened with the menu key

### ISSUE THREAD

**Issue by RichardJActon** [rstudio/rstudio#9790]
### System details

    RStudio Edition : Both
    RStudio Version :  server 1.4.1717, desktop 1.41029
    OS Version      :  ubuntu 20.04
    R Version       :  4.1.1

### Steps to reproduce the problem

- Place the cursor in some text in the editor
- Press the menu key
- The menu opens but does not take focus. Using the arrow up/down keys keeps moving the cursor and not the item highlighted in the context menu.
    - Note that on server the context menu opens in the top right of the editor not at the cursor position this is not the case on desktop

### Describe the behavior you expected

The context menu should take focus when opened with the menu key, and should be located close to the cursor not in the top right of the pane.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ~ I tried it in the preview of server was still an issue quick search didn't find a prior bug report] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
> 2. What do you mean by "menu key?" Do you mean a keyboard shortcut, and if so, which one?

I assume they mean the dedicated menu key found on most PC keyboards.

https://www.howtogeek.com/425623/what-is-the-menu-key-for-and-how-to-remap-it/

**Comment by RichardJActon** [comment]
Hi @ronblum. Yes I mean the dedicated menu key - https://en.wikipedia.org/wiki/Menu_key.
I have seen this behavior on Linux across several distros but all KDE desktops and in Firefox as well as several chromium based browsers (brave, vivaldi et al.). I can provide system info for specific example if you like but seems to occur under a variety of circumstances.

**Comment by ronblum** [comment]
Thank you both! My current external keyboard is insufficient, since it's designed for a Mac, so I'll have a Windows one in a few days. In the meantime, though, <kbd>Shift-F10</kbd> isn't opening the menu for me at all in RStudio Desktop 2022.01.0-daily+290, but it does in other applications. I'll check older versions to see if it's a regression, and whether or not the menu key works or not in it.

**Comment by ronblum** [comment]
Unstaling. Need to try to reproduce.

**Comment by RichardJActon** [comment]
For me with these versions this bug appears to be resolved - I'm not sure when it got fixed or what change fixed it, nor if it is fixed in other contexts than the below version information:

RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Jammy
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0

I will close this issue but it'd be nice to get some confirmation from anyone who'd like to quickly check that this is fixed in other contexts as it's unclear, at least to me, what fixed it.
