### ISSUE TITLE
RSTUDIO_VERSION is not parseable as a package version

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9795]
### System details

    RStudio Edition : Any
    RStudio Version : 2021-09.0-preview+338

### Steps to reproduce the problem

Create an R Markdown document with the following code:

```r
Sys.getenv("RSTUDIO_VERSION")
package_version(Sys.getenv("RSTUDIO_VERSION"))
```

Run the code. 

### Describe the problem in detail

The version of RStudio returned by the environment variable is not parseable by R's `package_version` function.

![image](https://user-images.githubusercontent.com/470418/131546464-1e485686-e6cc-436b-90e2-e660cdba8eb4.png)

This can be a problem because we use the `RSTUDIO_VERSION` environment variable to provide RStudio's version to various places, such as child processes that can't use rstudioapi.

https://github.com/rstudio/rstudio/blob/f959961729aed15efbc0a8b163857d458e418709/src/cpp/session/modules/build/SessionBuild.cpp#L354-L355

No ill affects in the IDE itself; this is just a problem for packages or code that may depend on the existing behavior.

### Describe the behavior you expected

The `RSTUDIO_VERSION` environment variable should match the value of `rstudioapi::versionInfo()$version` rather than `rstudioapi::versionInfo()$long_version`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified in:
- RStudio Desktop 2021.09.0-preview+341 on MacOS 12 beta
- RStudio Server RStudio 2021.09.0-preview+341 on Ubuntu 20.04 via Safari on MacOS 12 beta

Code:
````
# I'm a New Version
```{r}
rstudioapi::versionInfo()$long_version
rstudioapi::versionInfo()$version
Sys.getenv("RSTUDIO_VERSION")
Sys.getenv("RSTUDIO_LONG_VERSION")
package_version(Sys.getenv("RSTUDIO_VERSION"))
```
````

Result:
![rstudio_version.png](https://codetreeusercontent.s3.amazonaws.com/uploads/68065098-53bc-4b8a-930c-caa334d194ee/rstudio_version.png)

**Comment by cderv** [comment]
@ronblum I think I found a missing spot for this while working with last released version. 
See comment here: https://github.com/rstudio/rstudio/pull/9796#issuecomment-931200543

I could open a new issue if that is the way you are tracking things.

**Comment by ronblum** [comment]
I can reproduce this in with 2021.09.0+351 on MacOS 12 beta, and with 2021.09.0+351.pro6 on MacOS 12 beta and Ubuntu 20.04. Reopening.

**Comment by cderv** [comment]
FYI I added a handling of version scheme in **distill** package where we use the `RSTUDIO_VERSION` value to "fix" when it still contains long version name. (https://github.com/rstudio/distill/commit/52ba8cf3e240a25048c7dcf8a3cf5f55d5f18f01) 

Not ideal but should prevent users to have issues with new IDE version just publish. We'll push the patch to CRAN soon.

**Comment by mikebessuille** [comment]
Closing as the missing piece is described in #9903
