### ISSUE TITLE
Where in RStudio source to add PATH ?

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#9799]
On FreeBSD RStudio-server fails to find ```gmake``` because default path of the daemon doesn't include /usr/local/bin where gmake is.

What is the best place in the source code to add an extra-path?

Currently the RStudio port suggests to execute this R code in the session:
> Sys.setenv(PATH = paste("/usr/local/bin:",Sys.getenv("PATH"), sep=""))

but this isn't convenient.

**Comment by ronblum** [comment]
@yurivict One way to set environment variables like `PATH` is with the `Renviron` file. [This article](https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/) describes how to use it.
Methods within the code are [described here](https://community.rstudio.com/t/adding-to-the-path-variable/12066/2) (note another alternative in the last comment).

**Comment by yurivict** [comment]
> One way to set environment variables like PATH is with the Renviron file.

Is there a central ```Renviron``` file (not a per-user one) that can be modified once for all users?

**Comment by jmcphers** [comment]
Yes, there is, it's called `Renviron.site`. 

https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html
