### ISSUE TITLE
Faster loading of new references from Zotero

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#9800]
When using visual editor markdown I insert citations using the editor but between I add a new reference to Zotero and that citation appearing on the menu it takes some time (30s-2 minutes). 
If I had already the citation window open it won't show new citations (even if they match the exact same title). 

My workaround is to:
1. Add citation to Zotero.
2. Open citation manager on Rstudio (doesn't show the new reference)
3. Switch windows (back to the browser or to do other things)
4. Switch back to Rstudio
5. Close the citation window
6. Open it again and search for the reference. Then the reference might appear. 

If the new references were loaded faster I wouldn't waste much time and could focus more on writing and adding the references. 

I understand that probably now it only checks for new reference upon opening/loading the "Insert Citation" window, I hope there is a we to know if new references are added to Zotero and then load them on the RStudio Window

Many thanks.

**Comment by ronblum** [comment]
@llrs Thank you for raising the issue! Can you also provide the following information?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by llrs** [comment]
Ups, sorry, thought it was a feature request. 

RStudio Edition : Desktop
RStudio Version : 1.4.1717
OS Version      : Ubuntu 20.04
R Version       : 3.6.3 (I can test it with other R versions too, but I'm working on 3.6.3) 

Not sure how to add a more detailed reproducible example. Would recording a video/gif that be helpful?

**Comment by ronblum** [comment]
@llrs Thank you for the additional info! And a video never hurts. 🙂  I marked this as a bug because of the time to for the references to first appear after creating it in Zotero. If this is expected, though, we can switch this over to an enhancement.

**Comment by llrs** [comment]
https://user-images.githubusercontent.com/6818218/131690355-9e61ac3e-c8b2-4afc-a552-d28ebb4be9db.mp4

The end is cut, but after going back to the RStudio the reference was there.

**Comment by ccamara** [comment]
I am having the same problem (Actually, it may not be the same, as I updated the library one week ago and the reference is not yet present in Zotero's library, according to RStudio).

This is my system information:

RStudio Edition : Desktop
RStudio Version : 2021.09.0 Build 351
OS Version : Ubuntu 18.04, x86_64
R Version : 4.1.1

**Comment by astayleraz** [comment]
Verified on mac with version 2022.01.0-daily+205 that adding a new citation in Zotero, it would show in RStudio right away. I also did not experience any slowness. Not adding automation for this case as it involves zotero that we do not have setup on the web instances. Closing issue.

**Comment by llrs** [comment]
I still see some pause between adding a title and finding the document but it might be my computer.

**Comment by dragonstyle** [comment]
How long would you estimate the pause is before the reference is available in RStudio? I would expect perhaps a few seconds, but would hope it isn't more than that.

**Comment by llrs** [comment]
Yes it is 1 or 2 seconds, in the modern computer world that feels long. But don't worry I'll wait :smiley:
