### ISSUE TITLE
Copy with Ctrl+C not working in console, while right click + "Copy" does

### ISSUE THREAD

**Issue by etiennebacher** [rstudio/rstudio#9801]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2021.11.0 (Build 17), also the case with 1.4.1717
    OS Version      : Kubuntu 20.04.3 LTS x86_64 
    R Version       : 4.1.1

### Steps to reproduce the problem

* Run some code in the console, e.g `print("Testing the copy-paste functionality")`. 
* Use Ctrl+C to copy anything that is in the console (the output, a part of the code, anything). 
* Try to paste it anywhere: in the console, the editor, a browser, etc. 

### Describe the problem in detail

Nothing is pasted (except maybe what you had in the clipboard before).

Same steps, but this time copy with right click + "Copy" (and not with Ctrl+C). This time, the selection is correctly copied and can be pasted.

Note that both Ctrl+C and right click + "Copy" work in the source pane.

### Describe the behavior you expected

Ctrl+C should work as right click + "Copy" does.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@etiennebacher Thank you for raising this. I haven't been able to reproduce this using RStudio Desktop 1.4.1717 and 2022.02.0+366 on a couple of Ubuntu 20.04.3 desktop environments, though. Note that we don't support Ubuntu 21.11, only the LTS releases (18.04 and 20.04). But I'll leave this open to test when we start certifying with 22.04. Hopefully it's not an issue there, but issues in the non-LTS releases are often indicators of what's to come.

**Comment by etiennebacher** [comment]
Thank you for coming back to this. I think the problem was due to some custom themes I applied for the whole desktop (not RStudio themes). I reinstalled Kubuntu 20.04 a few weeks ago (for other reasons than this bug) and I don't have this problem anymore.

**Comment by ronblum** [comment]
@etiennebacher I'm glad to hear it's working! I'll close the issue, then, but if you run into the issue again, please let us know.

**Comment by brianmsm** [comment]
Hello

I have this same problem on GNU/Linux distributions using the KDE desktop. When using Gnome (Ubuntu for example), it does not happen.

The problem is solved for a short time when you right click and click reload. But after a few minutes the clipboard stops working again.
