### ISSUE TITLE
RStudio Server on Red Hat 8 doesn't work with PostgreSQL

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9802]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717 and 2021.09.0-preview+340
    OS Version      : Red Hat 8.4 (but not 7.9) and CentOS 8.3
    R Version       : 4.1.0

### Steps to reproduce the problem

Using RStudio Server (open source and Workbench) on Red Hat 8 or CentOS8:
1. Configure `database.conf` so that the internal database is in a PostgreSQL database.
2. `rstudio-server verify-installation` or `rstudio-server start` or `rstudio-server restart`

### Describe the problem in detail

With PostgreSQL 9.6, the output includes
> /usr/lib/rstudio-server/bin/rserver: /usr/pgsql-9.6/lib/libpq.so.5: no version information available (required by /usr/lib/rstudio-server/bin/rserver)

PostgreSQL 13.4 has a similar result. The server isn't running properly, so it's not possible for users to connect to the IDE, even the login screen.

### Describe the behavior you expected

No error and RStudio Server runs properly.

Note:
1) This is not an issue on Red Hat 7, CentOS 7, and Ubuntu 20.04.2.
2) This is the case for both open source and pro (Workbench).

`file /usr/pgsql-9.6/lib/libpq.so.5.9` results in
> /usr/pgsql-9.6/lib/libpq.so.5.9: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=09d612e474ff346563611033c43a59ffcff690e9, stripped

`ldd /usr/lib/rstudio-server/bin/rsession` yields
> /usr/lib/rstudio-server/bin/rsession: /usr/pgsql-9.6/lib/libpq.so.5: no version information available (required by /usr/lib/rstudio-server/bin/rsession)
	linux-vdso.so.1 (0x00007fff06efa000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fbeb8933000)
	libR.so => not found
	libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007fbeb861f000)
	libpq.so.5 => /usr/pgsql-9.6/lib/libpq.so.5 (0x00007fbeb83ed000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fbeb81e9000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fbeb7fe1000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fbeb7dd9000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fbeb7bc2000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007fbeb792e000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fbeb7448000)
	libpam.so.0 => /lib64/libpam.so.0 (0x00007fbeb7238000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbeb7018000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fbeb6c83000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fbeb6901000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fbeb66e9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fbeb6324000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbeba02a000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fbeb60cf000)
	libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007fbeb5e78000)
	libaudit.so.1 => /lib64/libaudit.so.1 (0x00007fbeb5c4e000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fbeb5965000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fbeb574e000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fbeb554a000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fbeb5339000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fbeb5135000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fbeb4f1e000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fbeb4d0e000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007fbeb4af0000)
	libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007fbeb48ea000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fbeb46c0000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fbeb4497000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fbeb4213000)

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MariaSemple** [comment]
Ron and I investigated this together.

It looks like the `libpq.so.5.9 ` dynamic library is missing its version definition section, which is causing these messages to be emitted, but they do not impact functionality. `rstudio-server verify-installation` is showing an exit code `0` (success), and we are able to log in, log out, and launch sessions despite these messages. The database is updated correctly as well.

For reference, the `readelf --version-info /usr/psql-9.6/lib/libpq.so.5.9` output (note the lack of a `.gnu.version_d` section):

```
Version symbols section '.gnu.version' contains 364 entries:
 Addr: 0000000000003e12  Offset: 0x003e12  Link: 3 (.dynsym)
  000:   0 (*local*)       2 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)
  004:   3 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  008:   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  00c:   4 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)   5 (GLIBC_2.2.5)   0 (*local*)    
  010:   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)
  014:   4 (GLIBC_2.2.5)   6 (GLIBC_2.3.4)   4 (GLIBC_2.2.5)   0 (*local*)    
  018:   3 (OPENSSL_1_1_0)   0 (*local*)       2 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)
  01c:   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   0 (*local*)    
  020:   5 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)
  024:   3 (OPENSSL_1_1_0)   5 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)
  028:   7 (gssapi_krb5_2_MIT)       6 (GLIBC_2.3.4)   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  02c:   3 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)
  030:   4 (GLIBC_2.2.5)   6 (GLIBC_2.3.4)   2 (OPENSSL_1_1_0)   0 (*local*)    
  034:   4 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)
  038:   2 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)   8 (GLIBC_2.3)     4 (GLIBC_2.2.5)
  03c:   0 (*local*)       4 (GLIBC_2.2.5)   0 (*local*)       3 (OPENSSL_1_1_0)
  040:   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   0 (*local*)    
  044:   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   0 (*local*)    
  048:   4 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   8 (GLIBC_2.3)  
  04c:   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  050:   0 (*local*)       3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)
  054:   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  058:   3 (OPENSSL_1_1_0)   5 (GLIBC_2.2.5)   8 (GLIBC_2.3)     3 (OPENSSL_1_1_0)
  05c:   7 (gssapi_krb5_2_MIT)       0 (*local*)       2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  060:   0 (*local*)       4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)
  064:   3 (OPENSSL_1_1_0)   5 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   6 (GLIBC_2.3.4)
  068:   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)
  06c:   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   0 (*local*)    
  070:   4 (GLIBC_2.2.5)   7 (gssapi_krb5_2_MIT)       3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  074:   2 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   0 (*local*)       5 (GLIBC_2.2.5)
  078:   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)
  07c:   2 (OPENSSL_1_1_0)   9 (GLIBC_2.4)     4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)
  080:   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)   5 (GLIBC_2.2.5)
  084:   7 (gssapi_krb5_2_MIT)       3 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)
  088:   4 (GLIBC_2.2.5)   8 (GLIBC_2.3)     2 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)
  08c:   2 (OPENSSL_1_1_0)   7 (gssapi_krb5_2_MIT)       2 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)
  090:   8 (GLIBC_2.3)     4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)
  094:   4 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   7 (gssapi_krb5_2_MIT)    
  098:   4 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)   7 (gssapi_krb5_2_MIT)       3 (OPENSSL_1_1_0)
  09c:   6 (GLIBC_2.3.4)   2 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   0 (*local*)    
  0a0:   2 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   6 (GLIBC_2.3.4)   4 (GLIBC_2.2.5)
  0a4:   2 (OPENSSL_1_1_0)   5 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  0a8:   2 (OPENSSL_1_1_0)   5 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)
  0ac:   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   5 (GLIBC_2.2.5)   2 (OPENSSL_1_1_0)
  0b0:   3 (OPENSSL_1_1_0)   2 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)
  0b4:   3 (OPENSSL_1_1_0)   3 (OPENSSL_1_1_0)   4 (GLIBC_2.2.5)   5 (GLIBC_2.2.5)
  0b8:   5 (GLIBC_2.2.5)   a (GLIBC_2.14)    4 (GLIBC_2.2.5)   3 (OPENSSL_1_1_0)
  0bc:   5 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)   4 (GLIBC_2.2.5)
  0c0:   2 (OPENSSL_1_1_0)   1 (*global*)      1 (*global*)      1 (*global*)   
  0c4:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0c8:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0cc:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0d0:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0d4:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0d8:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0dc:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0e0:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0e4:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0e8:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0ec:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0f0:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0f4:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0f8:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  0fc:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  100:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  104:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  108:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  10c:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  110:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  114:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  118:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  11c:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  120:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  124:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  128:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  12c:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  130:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  134:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  138:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  13c:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  140:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  144:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  148:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  14c:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  150:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  154:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  158:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  15c:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  160:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  164:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   
  168:   1 (*global*)      1 (*global*)      1 (*global*)      1 (*global*)   

Version needs section '.gnu.version_r' contains 5 entries:
 Addr: 0x00000000000040f0  Offset: 0x0040f0  Link: 4 (.dynstr)
  000000: Version: 1  File: libgssapi_krb5.so.2  Cnt: 1
  0x0010:   Name: gssapi_krb5_2_MIT  Flags: none  Version: 7
  0x0020: Version: 1  File: libpthread.so.0  Cnt: 1
  0x0030:   Name: GLIBC_2.2.5  Flags: none  Version: 5
  0x0040: Version: 1  File: libc.so.6  Cnt: 5
  0x0050:   Name: GLIBC_2.14  Flags: none  Version: 10
  0x0060:   Name: GLIBC_2.4  Flags: none  Version: 9
  0x0070:   Name: GLIBC_2.3  Flags: none  Version: 8
  0x0080:   Name: GLIBC_2.3.4  Flags: none  Version: 6
  0x0090:   Name: GLIBC_2.2.5  Flags: none  Version: 4
  0x00a0: Version: 1  File: libssl.so.1.1  Cnt: 1
  0x00b0:   Name: OPENSSL_1_1_0  Flags: none  Version: 3
  0x00c0: Version: 1  File: libcrypto.so.1.1  Cnt: 1
  0x00d0:   Name: OPENSSL_1_1_0  Flags: none  Version: 2
```

**Comment by ronblum** [comment]
Note: Adding `/usr/lib64/` to `LD_LIBRARY_PATH` gets rid of the messages. That is, 

1) Adding
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64`

to the environment; and 

2) Setting
```
[Service]
Environment="LD_LIBRARY_PATH=/usr/lib64/"
```
for the `rstudio-server` service, following the instructions provided in the RStudio Admin Guide under "Storage Location Customization:" https://docs.rstudio.com/ide/server-pro/latest/r_sessions/workspace_management.html?q=Storage%20Location%20Customization#storage-location-customization
