### ISSUE TITLE
Adding Sys.setenv(PATH = ...) to /usr/local/lib/R/etc/Renviron.site doesn't change PATH in RStudio-server

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#9804]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717
    OS Version      :  FreeBSD 13
    R Version       : 4.1.1

### Describe the problem in detail
On FreeBSD RStudio-server needs /usr/loca/bin to be in PATH in order for "gmake" to be found.

I added this code:
> Sys.setenv(PATH = paste("/usr/local/bin:",Sys.getenv("PATH"), sep=""))

to /usr/local/lib/R/etc/Renviron.site but ```gmake``` is still not found.

Why doesn't this change the path?

**Comment by Mosk915** [comment]
Renviron.site does not accept R code.  To set the PATH using the code you wrote, you would have to do it in Rprofile.site.

If you want to set the PATH in Renviron.site, you need to do it in a key-value format.  I think this would work:
`PATH="/usr/local/bin:$PATH"`

Source:  https://support.rstudio.com/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf

**Comment by yurivict** [comment]
```PATH="/usr/local/bin:$PATH"``` in ```Renviron.site``` doesn't change the path for some reason.

Other environment variables get set from ```Renviron.site```, but not PATH.

**Comment by yurivict** [comment]
Same with ```Rprofile.site``` - pasting my R code into it doesn't change ```PATH```, but other environment variables change fine.

**Comment by yurivict** [comment]
I added a more specific bug report: https://github.com/rstudio/rstudio/issues/9815
