### ISSUE TITLE
Visual markdown mode turns tight lists into spaced out lists

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/rstudio#9806]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717
    OS Version      : Fedora 30
    R Version       : 4.1.1

Also tested on ubuntu with the latest desktop preview version:

RStudio 2021.09.0-preview+340 "Ghost Orchid" Preview (8aea4f32e427a4f97a9fedf507a3ef88a228553e, 2021-08-27) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem

Set the global (and / or project settings) of the visual markdown mode `default spacing between list items: tight`.
Open a new Rmarkdown document, add these lines:

```
- this is
- a bullet point
  - with a sub-point
  - actually 2
 ```

Open and close the visual editor mode.

### Describe the problem in detail

The lines turn into:

```
-   this is

-   a bullet point

    -   with a sub-point
    -   actually 2
```

-> the lines are now spaced out
-> spaces are added between the dashes and the text

### Describe the behavior you expected

Lines stay tight.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Addressed here: https://github.com/rstudio/rstudio/commit/0de33ebb849227a6d2971dc8e80b40e0249f62fa

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 2021.12.0-daily+80
    OS Version      : ubuntu20
    R Version       : 4.0.3

Verified that switching the Visual Markdown Editor mode on and off now maintains the tight spacing between list items.
