### ISSUE TITLE
Limit/warn size of `environmentTmp` files.

### ISSUE THREAD

**Issue by layik** [rstudio/rstudio#9809]
I am not sure if this is seen by anyone else but accidentally discovered that somehow I had managed to create a file which was `159G	.Rproj.user/E899E94D/ctx/ctx-31584/environmentTmp` in size.

I just thought maybe this is something to consider for future releases, I believe such a size should never be written to disk without some constant warning. Given, we still are within < 1TB machine disks.

Feel free to close if impossible to put into practice.

**Comment by ronblum** [comment]
@layik Thank you for the suggestion! We'll review it as part of our ongoing development of RStudio.

That said, FWIW:
- You should be able to delete the file, if you have the data you need is saved elsewhere: https://community.rstudio.com/t/is-it-safe-to-delete-environmenttmp/3740/3
- This is article has some suggestions regarding "Filling up the home directory with RStudio Workbench / RStudio Server":  https://support.rstudio.com/hc/en-us/articles/218417097-Filling-up-the-home-directory-with-RStudio-Workbench-RStudio-Server

**Comment by kevinushey** [comment]
Given that user workspaces can be arbitrarily large, we should try to find some way to improve the way we handle serialization of sessions with very large objects.

**Comment by jmcphers** [comment]
Yes we should! https://github.com/rstudio/rstudio/issues/4345

**Comment by mikebessuille** [comment]
closing this as a duplicate of #4345
