### ISSUE TITLE
An odd situation where a character vector cannot be passed along with pipe using CTRL+ENTER when the cursor is at one of the following functions

### ISSUE THREAD

**Issue by zenggyu** [rstudio/rstudio#9810]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Ubuntu 20.04
    R Version       : 4.1.0

### Steps to reproduce the problem

Minimal example:

```r
c("
)
") |> # place the cursor above `print()` and press CTRL+ENTER, then no error will be raised.
  print() # place the cursor after `print()` and press CTRL+ENTER, then it will result in the following error:

## Error in print.default() : argument "x" is missing, with no default
```

This problem also happens to `%>%`:

```r
library(magrittr)

c("
)
") %>% # place the cursor above `print()` and press CTRL+ENTER, then no error will be raised.
  print() # place the cursor after `print()` and press CTRL+ENTER, then it will result in the following error:

## Error in print.default() : argument "x" is missing, with no default
```

### Describe the problem in detail

When there is a line in a character string that contains only the `)` symbol and the cursor is below the pipe operator, if I try to execute the statement using CTRL + ENTER, the command will result in an error indicating that the downstream function does not receive any data from the pipe. However, if I select the whole statement or if I put the cursor anywhere above the downstream function, and then press CTRL + ENTER, then there will be no error.

This is a trivial problem but still has some negative impact on user experience so I think I should mention it here. I discovered this problem when I used `DBI::dbGetQuery()` where it has a SQL statement that contains a line with only the `)` symbol.

### Describe the behavior you expected

The command should be executed without any error, and print:

```
[1] "\n)\n"
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by colearendt** [comment]
👋  stale bot! Fancy seeing you here!
