### ISSUE TITLE
.ssh folder location inconsistent under Windows

### ISSUE THREAD

**Issue by EricMarcon** [rstudio/rstudio#9811]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows 10.0.19043.1165
    R Version       : 4.1.1

### Steps to reproduce the problem

SSH keys and known_hosts are in `C:\Users\<username>\.ssh`.
git is installed and found by Rstudio (GIT/SVN global option > Git executable : `C:/Program Files/Git/bin/git.exe`.
RStudio Terminal is Git Bash.

Open a shell (menu Tools > Shell...) and run "ssh -T git@github.com" to test GitHub SSH connection returns "Hi EricMarcon! You've successfully authenticated, but GitHub does not provide shell access.", i.e. my SSH key is found.

In the terminal, an error is returned : "Could not create directory '/c/Program Files/RStudio/resources/terminal/bash/.ssh'."

### Describe the problem in detail

In the terminal, in contrast to the shell behavior, the ssh command searches the keys in `c/Program Files/RStudio/resources/terminal/bash/.ssh` instead of in the user's profile.

This seems to be an issue of the last version of Rstudio since it did not happen before upgrading to v. 1.4.1717.

### Describe the behavior you expected

The terminal should behave the same way as the shell and search SSH keys in the user's profile.

Thanks for your great work!

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by JrmFRL** [comment]
I encounter the same issue here. 
Waiting a fix, you can still duplicate your `/.ssh` folder into `/c/Program Files/RStudio/resources/terminal/bash/.ssh`.

This is ugly but this will make your Rstudio terminal work.

**Comment by kevinushey** [comment]
Do you know why the terminal is looking in that location? (What is the output of the `HOME` environment variable? Or, does any similar environment variable point there?)

Disabling the "Enable Python integration" option may fix this:

![Capture](https://user-images.githubusercontent.com/1976582/135672763-49ffdb02-fc78-485d-aab3-93810e45480f.PNG)

**Comment by JrmFRL** [comment]
@kevinushey 
Here is the value of $HOME:

`$ echo $HOME`
`/c/Program Files/RStudio/resources/terminal/bash`

**Comment by kevinushey** [comment]
What about the `USERPROFILE` environment variable? Does that point to a location that exists?
