### ISSUE TITLE
Project-level Appearance settings

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rstudio#9812]
In my daily work, I use an editor font with programming ligatures and font size 12. However, I also teach using RStudio. When I do this, I need to change my Appearance settings to use a different font and a larger font size. Currently, I need to manually make these changes before and after class. It would be really nice if I could set these options at the project level so that I could use a "Teaching" project for class but keep my regular options for other settings.

**Comment by hadley** [comment]
@bwiernik it's likely you could automate this using the same approach as `usethis::use_blank_slate()`, based on https://blog.rstudio.com/2020/02/18/rstudio-1-3-preview-configuration/.

**Comment by bwiernik** [comment]
That's a good idea! Thanks for the tip
