### ISSUE TITLE
find + replace whole word shows whole word only but replaces partial matches

### ISSUE THREAD

**Issue by AltfunsMA** [rstudio/rstudio#9813]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717
    OS Version      :  Ubuntu 20.04
    R Version       :  4.1.0

### Steps to reproduce the problem

1. Create at least one file with the text "proc" and one with "processed" (for example)
2. Search for "proc" with 'whole word' checked in the Find in Files menu
3. Only the one 'proc' will be displayed
4. Replace 'proc' with 'extracted'
5. Result will be 'extracted' in one file and 'extractedessed' in the other

### Describe the problem in detail

The whole word option is ignored during replacement. Even though the GUI displays the number of successes corresponding to the actual count of "proc" it has also replaced all partial matches, and shows them, too.

In the real life case for me this was the result:

![image](https://user-images.githubusercontent.com/26325512/132082070-85c9aaad-fc54-4e45-bf47-874c9313c64c.png)

### Describe the behavior you expected

Only full word matches (equivalent to a regex like "\bproc\b") to be replaced. Alternatively, a clear warning that this option will not work for "replace".

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@AltfunsMA Thank you for raising this!

Reproducible
- RStudio Desktop 1.4.1717 and 2022.02.0+364 on MacOS 12.1
- RStudio Server 2021.09.0+351 on SLES 15 SP3 via Chrome on MacOS 12.1

**Comment by timtmok** [comment]
Working well on Mac and Windows!
