### ISSUE TITLE
Renviron.site and Rprofile.site don't allow to change the PATH environment variable

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#9815]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717
    OS Version      : FreeBSD 13
    R Version       : 4.1.1

### Steps to reproduce the problem
Adding
> PATH="/usr/local/bin:$PATH"

in ```Renviron.site``` or adding
> Sys.setenv(PATH = paste("/usr/local/bin:",Sys.getenv("PATH"), sep=""))

in ```Rprofile.site``` doesn't change the ```PATH``` variable.

Other variables can be changed this way, but not ```PATH```.

### Describe the problem in detail
On FreeBSD ```gmake``` is in ```/usr/local/bin```  which isn't in the default path. The ```PATH``` variable needs to be changed and both above described ways fail.

**Comment by llrs** [comment]
This might be related to this point of the [NEWS for R 4.1.0](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html):

> The base environment and its namespace are now locked (so one can no longer add bindings to these or remove from these). 

So you'll need to add the new folder on the PATH outside R files.

**Comment by ronblum** [comment]
@yurivict Is the modified value of `PATH` as expected in standalone R, outside of RStudio?

@llrs Thank you for pointing this out!

**Comment by ronblum** [comment]
@yurivict Also, check out the following, for setting `PATH` within RStudio: https://community.rstudio.com/t/adding-to-the-path-variable/12066

**Comment by kevinushey** [comment]
That is unrelated. The change refers to bindings (R variables); those can no longer be changed in the base namespace. This doesn't affect environment variables.

The more likely explanation is that something else is changing or setting the PATH after the site-wide startup scripts are executed, but without a reproducible example we have no way of knowing.

**Comment by yurivict** [comment]
> The more likely explanation is that something else is changing or setting the PATH after the site-wide startup scripts are executed, but without a reproducible example we have no way of knowing.

The FreeBSD port is a reproducible example. ```RStudio-server``` runs with a wrong ```PATH``` and the above methods don't change it.

**Comment by yurivict** [comment]
ping

**Comment by jawhiteley** [comment]
I am noticing the same behaviour on macOS 13.5.2.

## Steps to reproduce the problem

Adding

    PATH="/opt/homebrew/bin:$PATH"

in `~/.Renviron` (actually, `$PATH` does not seem to work in this context at all) nor adding

    Sys.setenv(PATH=paste("/opt/homebrew/bin", Sys.getenv("PATH"), sep=":"))

in `.Rprofile` does not affect the PATH environment variable in the R session within R Studio.  At least, not persistently.  If I add this line to the end of `~/.Rprofile`, it shows the expected modified PATH in the console output at the start of a session:
```
cat(Sys.getenv("PATH"), "\n")
````

    /opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin 

But once the session has started, this command:

    Sys.getenv("PATH")

Shows something completely different, with none of the paths prepended in `.Renviron` or `.Rprofile` included.  Something in RStudio is clearly overwriting the `PATH` environment variable _after_ loading `.Rprofile`.

To reply to @ronblum's question: **the modified value of `PATH` _is as expected_ in the R GUI outside of RStudio**, and also in R started from the Terminal (zshell), though in the latter case, R is clearly picking up the `PATH` environment variable from the shell.

**Comment by turbanisch** [comment]
I'm experiencing exactly the same issue as @jawhiteley on MacOS version 14.2.1 and RStudio version 2023.12.1+402 (2023.12.1+402). Any changes in `~/.Renviron` are picked up by R GUI but not by R Studio.

**Comment by dmurdoch** [comment]
I don't see exactly what @turbanisch described.  Some variables `~/.Renviron` show up, but the `PATH` variable does not.  I assume this is because RStudio asks the system for `PATH`, and then modifies it, losing the modifications that R made on startup.

A solution to this would be for RStudio to query R for `PATH` after R starts, rather than getting it from the system.  Then it can modify `PATH` and things should be fine.  (It might need to **also** modify the system version if some part of its startup needs the paths it added.)

**Comment by kevinushey** [comment]
Something like the following:

```
trace(Sys.setenv, quote({
  if ("PATH" %in% ...names()) {
    print(rlang::trace_back())
  }
}))
```

in your `~/.Rprofile` could be useful in trying to diagnose where and why the PATH environment variable is being set, assuming that this is happening through R.

**Comment by dmurdoch** [comment]
I put this code in my `.Rprofile`:
```
print(Sys.getenv("PATH"))
Sys.setenv(PATH=paste("test", Sys.getenv("PATH"), sep = ":"))
print(Sys.getenv("PATH"))

trace(Sys.setenv, quote({
  if ("PATH" %in% ...names()) {
    print(rlang::trace_back())
  }
}))
```
 It printed this on startup:

```

[1] "/usr/bin:/bin:/usr/sbin:/sbin"
[1] "test:/usr/bin:/bin:/usr/sbin:/sbin"
Tracing function "Sys.setenv" in package "base"
[1] "Sys.setenv"
Tracing Sys.setenv(`_R_NS_LOAD_` = package) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = nsname) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = package) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = nsname) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = package) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = nsname) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = package) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = nsname) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = package) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = nsname) on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = package) on entry 
Tracing Sys.setenv(RSTUDIO_WINUTILS = "bin/winutils") on entry 
Tracing Sys.setenv(`_R_NS_LOAD_` = package) on entry 
Tracing Sys.setenv(RSTUDIO_PANDOC = "/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools",  .... on entry 
```

After it started, I ran `Sys.getenv("PATH")` in RStudio and it printed this:

```
> Sys.getenv("PATH")
[1] "/usr/local/bin:/usr/local/bin:/usr/local/opt/bzip2/bin:/Users/murdoch/perl5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/git/bin:/Users/murdoch/bin:/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools:/Users/murdoch/R/bin:/Users/murdoch/Applications/quarto/bin:/usr/texbin:/Users/murdoch/svn/MyR/quarto-cli/package/dist/bin:/Applications/RStudio.app/Contents/Resources/app/bin/postback"
```

So it appears that RStudio is making its modifications to the path after the `.Rprofile` is run, but it is not calling `Sys.setenv()`, or at least not the copy that is being traced.

Here's my session info just after that:
```
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.7.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Toronto
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.3.1 tools_4.3.1
```
