### ISSUE TITLE
Set up a way to render Rmarkdown to google doc like online WYSIWYG editor

### ISSUE THREAD

**Issue by MichelNivard** [rstudio/rstudio#9816]
Rmarkdown is amazing, the new WYSIWYG editor is amazing, yet its still not a feasible way to collaborate with the code averse among us.

Rmarkdown needs to have a way to render to an (online) text editor where we can let others (copy editors, scientists, co-authors, management) edit the document but perhaps not the code/tables/figs. This could be like a lightweight google docs of sorts, the author or others should then be able to rendered back to Rmarkdown/Rstudio to work on the code etc.

 I imagine the complexities of what i request are enormous and this can only be made feasible for paid users as there would be server costs ect involved, still it would be a great way to allow for reproducible uninterrupted collaboration across those who code, and those who don't. 

Sorry if this is a duplicate, I had a look but could not find a similar request, I am also sorry if its beyond the scope of this forum.

**Comment by ronblum** [comment]
@MichelNivard Thank you for the neat suggestion! It might be beyond the scope of what we'd do, but it's the right forum to request this. I'll mark this for review as part of the continuing development of RStudio, including the visual editor.
