### ISSUE TITLE
Use file-choose dialog when exporting plots as images

### ISSUE THREAD

**Issue by hcadavid** [rstudio/rstudio#9817]
Rstudio is an excellent piece of software,  however, updating a previously exported plot is a bit cumbersome and error-prone. In The 'Save Plot as Image option', you have to enter the file name in a text field (rather than using a file-choose dialog), so in an update use case, you have to check for the file name in a terminal/file manager, and copy the name to make sure you spelled it correctly (this often leads to duplicate files with similar names and hence to versioning issues). This is particularly an issue while working on a research paper, as you have to update many plots frequently. This usability design decision seems off-place as everything else is rather consistent and intuitive, and I think it can be easily fixed just by adding the file-choose option.

**Comment by mikebessuille** [comment]
Thanks very much for the suggestion.  While this might not currently be high on our priority list, would be interested in knowing if it affects a lot of people and workflows.  If others feel this is in need of a change, please upvote.

**Comment by hadley** [comment]
I think in most cases we should be encouraging folks to save plots with code, rather than with UI.
