### ISSUE TITLE
The R session process exited with code 9

### ISSUE THREAD

**Issue by dexterslaboratory** [rstudio/rstudio#9818]
Pasting the report below. I've tried reinstalling R and R studio. Doesn't seem to work. What else can I do here? Thanks :)

### RStudio Version

RStudio 1.4.1717, "Juliet Rose" (df86b69e, 2021-05-24) for Ubuntu Bionic

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 9. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*/home/siddharth/.local/share/rstudio/log/rsession-siddharth.log*

```
03 Sep 2021 08:15:47 [rsession-siddharth] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1408
03 Sep 2021 19:25:39 [rsession-siddharth] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1408
06 Sep 2021 13:27:45 [rsession-siddharth] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1408

```

**Comment by biqiyong** [comment]
this problem encounter to me.

**Comment by ronblum** [comment]
@dexterslaboratory and @biqiyong Does the problem occur only in RStudio, or also when starting up standalone R?

**Comment by dexterslaboratory** [comment]
@ronblum It occurs only while using RStudio. R works fine on my terminal.
