### ISSUE TITLE
Ctrl+Clicking on object names do not observe the environment hierarchy

### ISSUE THREAD

**Issue by santiagogualchi** [rstudio/rstudio#9819]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows 10 x64
    R Version       : R version 4.0.5 (2021-03-31)

### Steps to reproduce the problem

 1. Declare a data.frame that overrides a function name. For example:
    ```r
    data <- data.frame()
    ```

 2. Control-click on the data.frame name (`data`, in the example).

### Describe the problem in detail

When a data.frame overrides a function name, ctrl-clicking on that name will open the function declaration instead of the data.frame view. This happens with both built-in and user-defined functions.

### Describe the behavior you expected

I expected ctrl-clicking to open de data.frame view instead of the function declaration.

**Comment by mikebessuille** [comment]
This is not likely to be addressed in the near term.
