### ISSUE TITLE
Add option to change default Project location

### ISSUE THREAD

**Issue by netique** [rstudio/rstudio#9825]
At the moment, the default location for Projects is defined by `HOME` or `R_USER` env variables. However, the user may want to change that _without_ impacting the `R` behaviour itself. I would definitely appreciate an option to change that particular location either in GUI (as it is currently possible for the location of "No project") or using some env variable.

**Comment by ronblum** [comment]
@netique Thank you for the suggestion! We'll consider it as we continue development of RStudio.

**Comment by colearendt** [comment]
I like this idea 🎉  Moar project management customization! 😄
