### ISSUE TITLE
RStudio-Server: dyn.load fails, but works in R

### ISSUE THREAD

**Issue by kelbstf** [rstudio/rstudio#9832]
Hello,

apparently LD_PRELOADING and/or dynamic loading of shared libraries, which works fine for R on CLI, does not work for RStudio Server.

### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1717-01
    OS Version      : CentOS 7.6
    R Version       : 4.1.0

### Steps to reproduce the problem

a) Failure:

1. Login to R-Studio-Server
2. Sys.setenv(LD_LIBRARY_PATH=paste("/opt/hdf5-1.12.0/lib", Sys.getenv("LD_LIBRARY_PATH"),sep=":"))
3. dyn.load('/opt/hdf5-1.12.0/lib/libhdf5_hl.so.200')
4. Error in dyn.load("/opt/hdf5-1.12.0/lib/libhdf5_hl.so.200") :
  unable to load shared object '/opt/hdf5-1.12.0/lib/libhdf5_hl.so.200':
  libhdf5.so.200: cannot open shared object file: No such file or directory

b) Success:

1. export LD_PRELOAD=/opt/hdf5-1.12.0/lib/libhdf5.so:/opt/hdf5-1.12.0/lib/libhdf5_hl.so
2. launch R
3. Sys.setenv(LD_LIBRARY_PATH=paste("/opt/hdf5-1.12.0/lib", Sys.getenv("LD_LIBRARY_PATH"),sep=":"))
4. dyn.load('/opt/hdf5-1.12.0/lib/libhdf5_hl.so.200')
5. library(hdf5r)

### Describe the problem in detail

In order to make use of hdf5r 1.3.4 in R 4.1.0 under CentOS7 compiled against a local "hdf5-1.12.0", setting the LD_LIBRARY_PATH is not sufficient for making "dyn.load('/opt/hdf5-1.12.0/lib/libhdf5_hl.so.200')" succeed, which is prerequisite for loading "library(hdf5r)" eventually. 
It also takes to "export LD_PRELOAD="/opt/hdf5-1.12.0/lib/libhdf5.so:/opt/hdf5-1.12.0/lib/libhdf5_hl.so" prior to starting R. But that works.

The same does not work for R-Studio's console: here "dyn.load('/opt/hdf5-1.12.0/lib/libhdf5_hl.so.200')" keeps failing all the time. 
It makes no difference to have the PRELOAD applied on the CLI of the same user upfront, although this is the same user account.
Restarting R from within the RStudoio session also does not work.

### Describe the behavior you expected

1. Login to R-Studio-Server
2. Sys.setenv(LD_LIBRARY_PATH=paste("/opt/hdf5-1.12.0/lib", Sys.getenv("LD_LIBRARY_PATH"),sep=":"))
3. dyn.load('/opt/hdf5-1.12.0/lib/libhdf5_hl.so.200')
4. library(hdf5r)

My question:

- How would one make LD_PRELOAD work for studio-server?
- Or better: how would one make "Sys.setenv(LD_LIBRARY_PATH..." alone sufficient? 

The latter would be highly preferred.
Because only this approach ,would allow for giving the user dynamic control over shared libraries, according to the actual needs of the current project...

How do you handle this situation?

Best regards

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@kelbstf Thank you for raising the issue! I'll mark it for review as we continue development of RStudio.

**Comment by kevinushey** [comment]
`LD_LIBRARY_PATH` cannot be changed dynamically within a running process, it needs to be set _before_ the process is launched. I suspect the same is true of `LD_PRELOAD`.

**Comment by mikebessuille** [comment]
We don't currently support this.  Per Kevin's comment, you will need to set those environment variables in advance of the session being launched.

**Comment by kelbstf** [comment]
Hello to all of you,
sorry for not properly responding in time.
Just wanted to thank you very much for your help!
I'll try to find a workaround.
Best

**Comment by TakashiKoyama** [comment]
@kelbstf 
I have same problem.
How did you solve this problem?
