### ISSUE TITLE
Rmarkdown image preview not showing when bracketed citation is in caption

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/rstudio#9838]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 341
    OS Version      : pop-os-21.04
    R Version       : 4.04

### Steps to reproduce the problem

Open an Rmarkdown document and insert an image with markdown syntax. A preview of the image is displayed in the editor.

### Describe the problem in detail

However, when a bracketed citation is included in the caption, the image preview does not appear. For inline citations it still works, e.g. here, the first line works, the second doesn't:

```
![Cute little monsters as Rmarkdown Wizards by @ArtworkAllisonHorst](https://github.com/allisonhorst/stats-illustrations/raw/master/rstats-artwork/rmarkdown_wizards.png)

![Cute little monsters as Rmarkdown Wizards by [@ArtworkAllisonHorst]](https://github.com/allisonhorst/stats-illustrations/raw/master/rstats-artwork/rmarkdown_wizards.png)
```

### Describe the behavior you expected

Image preview is displayed no matter the content of the image caption.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jmbuhr Thank you for raising the issue. I'm not sure if I'm trying to reproduce it correctly.

1) Can you provide a screenshot? It would be helpful to compare.
2) I assume you're working in visual mode—is that correct?
3) When you `knit`, is the rendered file correct?

**Comment by jmbuhr** [comment]
Sorry, I should have made this more explicit. This is not in the visual editor, just the inline image preview that appears in a markdown text when the cursors was on the image file path at some point:

![image](https://user-images.githubusercontent.com/17450586/133335362-fd1022f9-6c85-44cd-88b7-ed49ad24ebbb.png)

and both versions knit fine.
