### ISSUE TITLE
Disable scrolling through tabs 

### ISSUE THREAD

**Issue by oduilln** [rstudio/rstudio#9840]
I would like the option to disable scrolling through open tabs of source within R Studio. When I have clicked an active file, I can scroll up and down through the code using my mouse's wheel, but the problem occurs that when I click on another tab, it will now default to scrolling through tabs with the scroll wheel. I would like the option to disable this and have it default to always scrolling vertically through the currently open source document.

It is a common occurrence that I will click on another tab, assume that when I scroll it will scroll down through the document, and instead it scrolls through the other tabs and I lose my place.

**Comment by ronblum** [comment]
@oduilln Thank you for raising this—is this the behavior you're describing? https://github.com/rstudio/rstudio/issues/8541#issuecomment-739049847

**Comment by oduilln** [comment]
Yes this is exactly it. I am using Mac OS, actually I am using RDP to connect to a Windows machine but the host OS is Mac. I get the same issue using my mouse as the trackpad, I understand the mouse can add an extra layer of complexity that could be causing the issue.
