### ISSUE TITLE
Add option to filter, search, and/or sort Rmd templates when opening new file

### ISSUE THREAD

**Issue by rbcavanaugh** [rstudio/rstudio#9851]
I've looked through the current enhancements and I apologize if I missed this. 

*Problem:* I have installed a number of packages that include Rmd templates, to the extent that finding the Rmd template I'm looking for is getting a bit cumbersome (see gif). 

![Screen_Recording_2021-09-15_at_9_29_48_AM_SparkVideo](https://user-images.githubusercontent.com/46727239/133443734-250c8c70-2ed6-4742-9ef8-b22ac898ba0f.gif)

*Potential solutions:* 
- When opening a new Rmd template, user is given the option to filter by package, search by package or template name, or sort by package or template name. 
- Allow the pop-up box to be re-sized so that it is much larger and more templates can be seen at once. 

Thanks for a great product!

**Comment by ronblum** [comment]
@rbcavanaugh Thank you for the suggestion! I'm not aware of a similar enhancement request, either, so I'll mark this for review as part of ongoing development of RStudio. And thank you for the kind words!

**Comment by colearendt** [comment]
This becomes more and more important with each passing Rmd Template!
