### ISSUE TITLE
Warn if pasting large amounts of text

### ISSUE THREAD

**Issue by wurli** [rstudio/rstudio#9856]
As a data scientist regularly working with large datasets and RStudio, very occasionally I'll accidentally end up pasting thousands of rows of data into a script, which causes RStudio to freeze for a long time before I can `ctrl + z` my way out of the mess I've made. I would love a feature that warns before attempting to paste so much text. It might not be used by too many people, but it would be a life-saver for me when I'm wrangling whilst uncaffeinated. I'm writing this feature request while waiting for RStudio to unfreeze after exactly this happened!

RStudio is an awesome tool. Thanks for all the hard work on it :)

**Comment by ronblum** [comment]
@wurli Thank you for the suggestion! We're here to help the caffeinated and uncaffeinated alike, so we'll review this as we continue to develop RStudio. Also, thank you for the kind words!

Note: I can reproduce this with copying and pasting about 120K rows in both RStudio Desktop 1.4.1717 and 2021.09.0.341 on MacOS 12 beta.

**Comment by zenggyu** [comment]
Here is a probably related [issue](https://github.com/MilesMcBain/datapasta/issues/125). Although it's not an RStudio issue, it'll still help to provide users with a warning when they paste a long line of text into a script or console.
