### ISSUE TITLE
Centos 7: Links from RNotebook files and RMarkdown files fail to open

### ISSUE THREAD

**Issue by valerie-rstudio** [rstudio/rstudio#9862]
### System details

    RStudio Edition : Desktop Open Source
    RStudio Version : 2021.09.0+350
    OS Version      : Centos 7
    R Version       : 3.3.3

### Summary
Error in terminal when attempting to open links from knitted RMarkdown or previewed RNotebook documents. Links fail to open.

### Steps to reproduce the problem
1. Open the terminal and launch RStudio with the command `rstudio`
2. Open an RNotebook file
3. Preview the default RNotebook file and click on the R Markdown link contained in it
4. Check the terminal
5. **Expected**: The link opens in your default browser. The external terminal contains no error messages.
6. **Actual**: The link opens a .html file in notepad. The external terminal contains the following messages:
```
"Uncaught TypeError: channel.execCallbacks[message.id] is not a function"
This tool has been deprecated, use 'gio open' instead.
See 'gio help open' for more info.
```

Notes:
- This issue is not occurring on other operating systems tested during regression.

**Comment by mikebessuille** [comment]
Centos rarely used for desktop, so this is almost certainly not urgent for Ghost Orchid at this point.  However, it's strange that this is suddenly not working.

**Comment by R-Hannibal** [comment]
@mikebessuille - moving this out to Prairie Trillium as per our talk yesterday.

**Comment by valerie-rstudio** [comment]
Closing as Not a Bug.
This was only occurring on Centos7 for me. Upon further inspection, it appears that the underlying cause for me was an issue with the Chromium browser installed on my instance of Centos7, not a bug in RStudio.
