### ISSUE TITLE
Preview button is missing for rnotebook file

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#9866]
### System details

    RStudio Edition : 
    RStudio Version : 2021.12.0-daily+64
    OS Version      : ubuntu20
    R Version       : 4.1.1

### Steps to reproduce the problem
Automation failure. job/qa-opensource-automation/855/testReport/junit/rstudio_server_pro.tests.Files.test_RNotebook/TestRNotebook/test_creating_new_r_notebook_and_preview/

Test failed in build 2021.12.0-daily+64
Test last passed in build 2021.12.0-daily+33

1. Create new rnotebook file from the console: .rs.api.executeCommand('newRNotebook')
2. Save the file.
3. Set preview to viewer pane and click preview

### Describe the problem in detail
The Preview button is not showing. The attached image shows the preview button in the preview build but the localhost URL that is the daily build, the button is missing.

![Screen Shot 2021-09-20 at 2 48 30 PM](https://user-images.githubusercontent.com/1482677/134081608-5b3c8ca7-a658-416d-8dd9-fa32e60cc2be.png)

### Describe the behavior you expected
The preview button should be showing.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
FWIW I can't reproduce this on main (about +70). At Step 2, I see this:

![image](https://user-images.githubusercontent.com/470418/134251730-fd07de91-9be8-4923-884e-866670517477.png)

**Comment by jmcphers** [comment]
Looks like https://github.com/rstudio/rstudio/commit/5adc32552110ad8b1db8a02768ddc28b9ec52355#diff-3eaa763c8b4da53d2e3e14760d47e28a2cc9adc4f64489c7a5d0a1690dc5444c broke this.

**Comment by astayleraz** [comment]
Confirmed this has been fixed in 2022.01.0-daily+89.pro1 and has been passing in our automated runs since build 2021.12.0-daily+72. Closing issue.
