### ISSUE TITLE
Errors when opening or saving RMarkdown documents when R runtime is busy

### ISSUE THREAD

**Issue by jeffvroom** [rstudio/rstudio#9868]
### System details

    RStudio Edition : All
    RStudio Version : Ghost orchid

### Steps to reproduce the problem

Run an R command to make the runtime busy, or set session-handle-offline-timeout-ms=0, then open or save an RMarkdown document.  The Rsession will log these errors:

```
2021-09-20T23:54:21.547174Z [rsession-jvroom] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83
2021-09-20T23:54:21.547622Z [rsession-jvroom] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:140
2021-09-20T23:54:21.547891Z [rsession-jvroom] ERROR r error 5 (R symbol not found) [symbol: .rs.extractRCode]; OCCURRED AT rstudio::core::Error rstudio::r::exec::RFunction::call(SEXP, bool, SEXP *, sexp::Protect *) src/cpp/r/RExec.cpp:475; LOGGED FROM: void rstudio::session::modules::code_search::RSourceIndexes::update(const boost::shared_ptr<SourceDocument> &) src/cpp/session/modules/SessionCodeSearch.cpp:1000
```

### Describe the problem in detail

The code is making use of a utility extractRCode. For regular RScripts, it does not use the R runtime, but for RMarkdown, Sweave, and Cpp files it calls an R function with a regular expression to extra just the R source from the file.  

This is all part of updating the R source code index. In addition to the error, the index won't be updated due to this error.

### Describe the behavior you expected

It should not log an error and the index should be updated even if the R thread is busy.  Or the index update could be delayed until the R runtime becomes available.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
The file is still saved despite the error, so I don't think this qualifies to delay Ghost Orchid.  Putting this into Prairie Trillium.

**Comment by kevinushey** [comment]
Some example backtraces:

> Backtrace (most recent calls first):
> 
> 0   rsession                            0x0000000104d4c0bc rstudio::core::backtrace::printBacktrace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 280
> 1   rsession                            0x0000000104d8aa68 rstudio::core::thread::assertMainThread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rstudio::core::ErrorLocation const&) + 72
> 2   rsession                            0x0000000104b12704 rstudio::session::modules::rmarkdown::rmarkdownPackageAvailable() + 120
> 3   rsession                            0x0000000104b1b800 rstudio::session::module_context::isWebsiteProject() + 16
> 4   rsession                            0x00000001049ec6dc rstudio::session::modules::build::(anonymous namespace)::onSourceEditorFileSaved(rstudio::core::FilePath) + 88
> 5   rsession                            0x0000000104914524 rstudio_boost::detail::function::void_function_invoker1<void (*)(rstudio::core::FilePath), void, rstudio::core::FilePath>::invoke(rstudio_boost::detail::function::function_buffer&, rstudio::core::FilePath) + 44
> 6   rsession                            0x000000010486c9a4 rstudio_boost::function1<void, rstudio::core::FilePath>::operator()(rstudio::core::FilePath) const + 60
> 7   rsession                            0x000000010486c7d8 rstudio_boost::signals2::detail::slot_call_iterator_t<rstudio_boost::signals2::detail::variadic_slot_invoker<rstudio_boost::signals2::detail::void_type, rstudio::core::FilePath>, std::__1::__list_iterator<rstudio_boost::shared_ptr<rstudio_boost::signals2::detail::connection_body<std::__1::pair<rstudio_boost::signals2::detail::slot_meta_group, rstudio_boost::optional<int> >, rstudio_boost::signals2::slot<void (rstudio::core::FilePath), rstudio_boost::function<void (rstudio::core::FilePath)> >, rstudio_boost::signals2::mutex> >, void*>, rstudio_boost::signals2::detail::connection_body<std::__1::pair<rstudio_boost::signals2::detail::slot_meta_group, rstudio_boost::optional<int> >, rstudio_boost::signals2::slot<void (rstudio::core::FilePath), rstudio_boost::function<void (rstudio::core::FilePath)> >, rstudio_boost::signals2::mutex> >::dereference() const + 96
> 8   rsession                            0x000000010486ba90 rstudio_boost::signals2::detail::signal_impl<void (rstudio::core::FilePath), rstudio_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, rstudio_boost::function<void (rstudio::core::FilePath)>, rstudio_boost::function<void (rstudio_boost::signals2::connection const&, rstudio::core::FilePath)>, rstudio_boost::signals2::mutex>::operator()(rstudio::core::FilePath) + 332
> 9   rsession                            0x000000010486b56c rstudio_boost::signals2::signal<void (rstudio::core::FilePath), rstudio_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, rstudio_boost::function<void (rstudio::core::FilePath)>, rstudio_boost::function<void (rstudio_boost::signals2::connection const&, rstudio::core::FilePath)>, rstudio_boost::signals2::mutex>::operator()(rstudio::core::FilePath) + 68
> 10  rsession                            0x0000000104990e4c rstudio::session::modules::source::(anonymous namespace)::saveDocumentCore(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rstudio::core::json::Value const&, rstudio::core::json::Value const&, rstudio::core::json::Value const&, rstudio::core::json::Value const&, rstudio::core::json::Value const&, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>, bool) + 2584
> 11  rsession                            0x0000000104986e58 rstudio::session::modules::source::(anonymous namespace)::saveDocumentDiff(rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*) + 1236
> 12  rsession                            0x0000000104dc2e68 rstudio::core::json::(anonymous namespace)::runSynchronousFunction(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&) + 92
> 13  rsession                            0x00000001046903e8 rstudio::session::rpc::handleRpcRequest(rstudio::core::json::JsonRpcRequest const&, rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) + 1052
> 14  rsession                            0x00000001046989a8 rstudio::session::http_methods::handleConnection(rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) + 1288
> 15  rsession                            0x00000001047c799c rstudio::session::OfflineService::run() + 1072
> 16  rsession                            0x0000000104fb0978 rstudio_boost::(anonymous namespace)::thread_proxy(void*) + 176
> 17  libsystem_pthread.dylib             0x00000001bc06d4ec _pthread_start + 148
> 18  libsystem_pthread.dylib             0x00000001bc0682d0 thread_start + 8
> 2021-11-16T06:17:09.639783Z [rsession-kevin] ERROR 'bool rstudio::session::modules::rmarkdown::rmarkdownPackageAvailable()' was called from non-main thread; LOGGED FROM: bool rstudio::session::modules::rmarkdown::rmarkdownPackageAvailable() src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp:1680

> Backtrace (most recent calls first):
> 
> 0   rsession                            0x0000000104d4c0bc rstudio::core::backtrace::printBacktrace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 280
> 1   rsession                            0x0000000104d8aa68 rstudio::core::thread::assertMainThread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rstudio::core::ErrorLocation const&) + 72
> 2   rsession                            0x0000000104ec1498 rstudio::r::options::getOption(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 136
> 3   rsession                            0x0000000104a3edb8 bool rstudio::r::options::getOption<bool>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool const&, bool) + 64
> 4   rsession                            0x0000000104eb921c rstudio::r::exec::(anonymous namespace)::DisableErrorHandlerScope::DisableErrorHandlerScope() + 128
> 5   rsession                            0x0000000104ebb198 rstudio::r::exec::RFunction::call(SEXPREC*, bool, SEXPREC**, rstudio::r::sexp::Protect*) + 92
> 6   rsession                            0x0000000104973e6c rstudio::core::Error rstudio::r::exec::RFunction::callUtf8<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 72
> 7   rsession                            0x000000010497226c rstudio::session::r_utils::(anonymous namespace)::extractRCode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 252
> 8   rsession                            0x0000000104971f78 rstudio::session::r_utils::extractRCode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 696
> 9   rsession                            0x00000001047e9d04 rstudio::session::modules::code_search::RSourceIndexes::update(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> const&) + 96
> 10  rsession                            0x00000001049964f4 rstudio_boost::function1<void, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> >::operator()(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) const + 60
> 11  rsession                            0x00000001049963f4 rstudio_boost::signals2::detail::void_type rstudio_boost::signals2::detail::call_with_tuple_args<rstudio_boost::signals2::detail::void_type>::m_invoke<rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, 0u, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>&>(rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>&, rstudio_boost::signals2::detail::unsigned_meta_array<0u>, std::__1::tuple<rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>&> const&, rstudio_boost::enable_if<rstudio_boost::is_void<rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>::result_type>, void>::type*) const + 56
> 12  rsession                            0x00000001049962a8 rstudio_boost::signals2::detail::slot_call_iterator_t<rstudio_boost::signals2::detail::variadic_slot_invoker<rstudio_boost::signals2::detail::void_type, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> >, std::__1::__list_iterator<rstudio_boost::shared_ptr<rstudio_boost::signals2::detail::connection_body<std::__1::pair<rstudio_boost::signals2::detail::slot_meta_group, rstudio_boost::optional<int> >, rstudio_boost::signals2::slot<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)> >, rstudio_boost::signals2::mutex> >, void*>, rstudio_boost::signals2::detail::connection_body<std::__1::pair<rstudio_boost::signals2::detail::slot_meta_group, rstudio_boost::optional<int> >, rstudio_boost::signals2::slot<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)> >, rstudio_boost::signals2::mutex> >::dereference() const + 76
> 13  rsession                            0x0000000104995ee0 rstudio_boost::signals2::detail::signal_impl<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::function<void (rstudio_boost::signals2::connection const&, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::signals2::mutex>::operator()(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) + 332
> 14  rsession                            0x00000001049802f8 rstudio_boost::signals2::signal<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::function<void (rstudio_boost::signals2::connection const&, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::signals2::mutex>::operator()(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) + 68
> 15  rsession                            0x000000010498faa8 rstudio::session::modules::source::(anonymous namespace)::sourceDatabasePutWithUpdatedContents(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>, bool, bool) + 220
> 16  rsession                            0x0000000104986f6c rstudio::session::modules::source::(anonymous namespace)::saveDocumentDiff(rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*) + 1512
> 17  rsession                            0x0000000104dc2e68 rstudio::core::json::(anonymous namespace)::runSynchronousFunction(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&) + 92
> 18  rsession                            0x00000001046903e8 rstudio::session::rpc::handleRpcRequest(rstudio::core::json::JsonRpcRequest const&, rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) + 1052
> 19  rsession                            0x00000001046989a8 rstudio::session::http_methods::handleConnection(rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) + 1288
> 20  rsession                            0x00000001047c799c rstudio::session::OfflineService::run() + 1072
> 21  rsession                            0x0000000104fb0978 rstudio_boost::(anonymous namespace)::thread_proxy(void*) + 176
> 22  libsystem_pthread.dylib             0x00000001bc06d4ec _pthread_start + 148
> 23  libsystem_pthread.dylib             0x00000001bc0682d0 thread_start + 8
> 2021-11-16T06:17:09.647482Z [rsession-kevin] ERROR 'SEXP rstudio::r::options::getOption(const std::string &)' was called from non-main thread (Reading R option: rstudio.errors.suppressed); LOGGED FROM: SEXP rstudio::r::options::getOption(const std::string &) src/cpp/r/ROptions.cpp:83

> 0   rsession                            0x0000000104d4c0bc rstudio::core::backtrace::printBacktrace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 280
> 1   rsession                            0x0000000104d8aa68 rstudio::core::thread::assertMainThread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rstudio::core::ErrorLocation const&) + 72
> 2   rsession                            0x0000000104eb9aac rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXPREC*, SEXPREC*, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::(anonymous namespace)::EvalType) + 184
> 3   rsession                            0x0000000104ebb1b4 rstudio::r::exec::RFunction::call(SEXPREC*, bool, SEXPREC**, rstudio::r::sexp::Protect*) + 120
> 4   rsession                            0x0000000104973e6c rstudio::core::Error rstudio::r::exec::RFunction::callUtf8<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 72
> 5   rsession                            0x000000010497226c rstudio::session::r_utils::(anonymous namespace)::extractRCode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 252
> 6   rsession                            0x0000000104971f78 rstudio::session::r_utils::extractRCode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 696
> 7   rsession                            0x00000001047e9d04 rstudio::session::modules::code_search::RSourceIndexes::update(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> const&) + 96
> 8   rsession                            0x00000001049964f4 rstudio_boost::function1<void, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> >::operator()(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) const + 60
> 9   rsession                            0x00000001049963f4 rstudio_boost::signals2::detail::void_type rstudio_boost::signals2::detail::call_with_tuple_args<rstudio_boost::signals2::detail::void_type>::m_invoke<rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, 0u, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>&>(rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>&, rstudio_boost::signals2::detail::unsigned_meta_array<0u>, std::__1::tuple<rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>&> const&, rstudio_boost::enable_if<rstudio_boost::is_void<rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>::result_type>, void>::type*) const + 56
> 10  rsession                            0x00000001049962a8 rstudio_boost::signals2::detail::slot_call_iterator_t<rstudio_boost::signals2::detail::variadic_slot_invoker<rstudio_boost::signals2::detail::void_type, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument> >, std::__1::__list_iterator<rstudio_boost::shared_ptr<rstudio_boost::signals2::detail::connection_body<std::__1::pair<rstudio_boost::signals2::detail::slot_meta_group, rstudio_boost::optional<int> >, rstudio_boost::signals2::slot<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)> >, rstudio_boost::signals2::mutex> >, void*>, rstudio_boost::signals2::detail::connection_body<std::__1::pair<rstudio_boost::signals2::detail::slot_meta_group, rstudio_boost::optional<int> >, rstudio_boost::signals2::slot<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)> >, rstudio_boost::signals2::mutex> >::dereference() const + 76
> 11  rsession                            0x0000000104995ee0 rstudio_boost::signals2::detail::signal_impl<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::function<void (rstudio_boost::signals2::connection const&, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::signals2::mutex>::operator()(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) + 332
> 12  rsession                            0x00000001049802f8 rstudio_boost::signals2::signal<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>), rstudio_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, rstudio_boost::function<void (rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::function<void (rstudio_boost::signals2::connection const&, rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>)>, rstudio_boost::signals2::mutex>::operator()(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>) + 68
> 13  rsession                            0x000000010498faa8 rstudio::session::modules::source::(anonymous namespace)::sourceDatabasePutWithUpdatedContents(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>, bool, bool) + 220
> 14  rsession                            0x0000000104986f6c rstudio::session::modules::source::(anonymous namespace)::saveDocumentDiff(rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*) + 1512
> 15  rsession                            0x0000000104dc2e68 rstudio::core::json::(anonymous namespace)::runSynchronousFunction(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&) + 92
> 16  rsession                            0x00000001046903e8 rstudio::session::rpc::handleRpcRequest(rstudio::core::json::JsonRpcRequest const&, rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) + 1052
> 17  rsession                            0x00000001046989a8 rstudio::session::http_methods::handleConnection(rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) + 1288
> 18  rsession                            0x00000001047c799c rstudio::session::OfflineService::run() + 1072
> 19  rsession                            0x0000000104fb0978 rstudio_boost::(anonymous namespace)::thread_proxy(void*) + 176
> 20  libsystem_pthread.dylib             0x00000001bc06d4ec _pthread_start + 148
> 21  libsystem_pthread.dylib             0x00000001bc0682d0 thread_start + 8
> 2021-11-16T06:17:09.650339Z [rsession-kevin] ERROR 'rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType)' was called from non-main thread; LOGGED FROM: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) src/cpp/r/RExec.cpp:138

**Comment by kevinushey** [comment]
FWIW, I saw similar backtraces when saving regular `.R` files and `.cpp` files, so I think this could effect saving any sort of file, not just R Markdown documents.

**Comment by kevinushey** [comment]
One of the other challenges here is that, on save, we send some signals:

https://github.com/rstudio/rstudio/blob/2838ce24e8c6bf0a8d1cea83663cbf2231abdab7/src/cpp/session/modules/SessionSource.cpp#L497-L498

https://github.com/rstudio/rstudio/blob/2838ce24e8c6bf0a8d1cea83663cbf2231abdab7/src/cpp/session/modules/SessionSource.cpp#L204-L207

and those listeners may expect to be running on the main thread. For example:

https://github.com/rstudio/rstudio/blob/2838ce24e8c6bf0a8d1cea83663cbf2231abdab7/src/cpp/session/modules/build/SessionBuild.cpp#L165-L206

I'm not sure what the most straightforward solution here is, but it feels a little hairy. (Maybe put those signals on a queue that is later called by the main thread somewhere appropriate?)

**Comment by cm421** [comment]
```
OS         : Fuzzbucket ubuntu20 environment
RSW Version: 2022.02.0-preview+386.pro3
```

Verified that opening RMD, Sweave, and CPP files does not generate an error when the R main thread is busy
Verified that creating a new RMD and Sweave file while R main thread is busy works

Found that creating a new CPP file while the R main thread is busy does not work. (No error, no reaction from the GUI) This is captured in https://github.com/rstudio/rstudio/issues/10406

**Comment by datakid** [comment]
I believe this is seen in the wild on support ticket: #72722
