### ISSUE TITLE
Enable source diagnostics within visual editor

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#9874]
Use the gutter area we are also now using for collapse/expand to enable source diagnostics indicators in visual mode code chunks.

**Comment by mikebessuille** [comment]
@cm421 did you assign this to yourself to test it?  If so, do you feel you can complete it by end of next week?  What automation is needed?

**Comment by cm421** [comment]
Yes, for testing! I got distracted by other tests and am now checking for a way to automate testing for this. It will be done by tomorrow (hopefully with an automated test, but manually at a minimum)

**Comment by cm421** [comment]
Tested on RSW `2022.01.0-daily+295.pro1` on Ubuntu 20.

Steps made to test
- Made a function call inside an r code block, but with a missing comma
- An error icon appears in the gutter indicating a missing comma
- Making an edit on the line with the error temporarily removes the error icon
- Pausing for a few seconds, the error returns if it was not fixed

An automated test was created to repeat these steps as well
