### ISSUE TITLE
Rmd python chunk cannot be saved twice 

### ISSUE THREAD

**Issue by Yiguan** [rstudio/rstudio#9875]
It's a weird issue with .rmd.

When the .rmd file contains python chunk, if I make some changes within the python chunk, it can be correctly saved. Then I make changes again within the python chunk, it can't be saved this time!! Some other operations within Rstudio doesn't work either.
 
I need to  restart Rstudio.  But the problem continues: any changes within the python chunk can only be saved once, it doesn't work if any further saves are needed.

If the chunk label changed from `python` to `r`, the issue disappears. If the changes I made are outside of the python chunk, the issue no longer exists.

Rstudo version:  Version 1.4.1717 on Windows10

**Comment by Yiguan** [comment]
Update: I think the issue is caused by `reticulate` (version 1.22). I removed the package, and the issue is solved!

**Comment by ronblum** [comment]
@Yiguan Thank you for raising this! Which version of `reticulate` does this work with? Also, what version of R are you using?

**Comment by Yiguan** [comment]
> @Yiguan Thank you for raising this! Which version of `reticulate` does this work with? Also, what version of R are you using?

The `reticulate` version is 1.22 and the R version is 4.0.3
I have set `python.reticulate=FALSE` in order to knit without `reticulate` (I don't need to run Python chunk in my Rmd file).
