### ISSUE TITLE
Remove r-base from `recommends` package

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#9880]
### System details

    RStudio Edition : All
    RStudio Version : Any
    OS Version      :  Ubuntu/Debian
    R Version       : Any

### Steps to reproduce the problem
On a machine with R installed, install the RStudio debian package  (`.deb`) with `apt` or `apt-get`. Note that `r-base` is installed.

### Describe the problem in detail
R is getting installed even once it's already installed, which can lead to the user running an unexpected version of R (worst case) or having an extra version of R they don't use (best case).  The [Admin guide](https://docs.rstudio.com/ide/server-pro/latest/r_versions/installing_r.html) recommends install our R binaries, not the vendor versions.  In the past we've recommended users install RStudio using `gdebi`, which this does **not** happen with.

The issue stems from `apt` installing recommended dependencies while `gdebi` does not. When running with `---no-install-recommends`, R will not be installed. 

### Describe the behavior you expected
We should remove `r-base` from the recommended depencies: https://github.com/rstudio/rstudio/blob/main/package/linux/CMakeLists.txt#L206

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment]
Verified on an x86_64 VM. `r-base` shows up in the suggested list now.
