### ISSUE TITLE
"Find in Files" does not find files if non-ASCII characters are contained in the path name

### ISSUE THREAD

**Issue by aryoda** [rstudio/rstudio#9881]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows NT 10.0; Win64; x64
    R Version       : 4.1.0 (2021-05-18) on Platform x86_64-w64-mingw32/x64 (64-bit) Running under Windows 10x64 (build 19042)

### Steps to reproduce the problem

Open RStudio and a new R file. Put this code into it but don't save it:

```
folder <- "~/search äöü test/subfolder" 
dir.create(folder)
setwd(folder)
x <- "hello world"
write.csv(x, "hello.txt")
dir()
```

Execute the code to create the folders and file.

Now use "Edit > Find in Files", change the "Search in" path to the above folder and search for "hello".

On Windows no file will be found even though "hello.txt" contains the search text!

### Describe the problem in detail

If the 2nd or higher parent folder contains a non-ASCII character like a german umlaut or french accent
then "Find in Files" does not find a text file with a matching content (if the file is contained at least one folder
deeper than the path component containing a non-ASCII character!).

The file will not be shown in the result list tab "Find in Files" on Windows OS.

On Linux it works!

Saving the R code with different encodings and recreate the folder structure does not help.

I am using a NTFS formatted file system.

### Describe the behavior you expected

The file "hello.txt" must be found if I search in "Find in Files"

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@aryoda Thank you for raising this! We unfortunately run into variations of path and encoding bugs, which we've been trying to fix. I'll add this to the list. Thanks!

**Comment by jgutman** [comment]
Note: This still succeeds on Mac and fails on Windows using R 4.0.0, 4.1.2, and 4.2.0 using RStudio Desktop 2022.06.0+70

**Comment by jgutman** [comment]
Needed to update the grep binary for windows again. With updated binary, this now succeeds on Windows using the UCRT UTF-8 build of R 4.2 -- need to test this with R < 4.2 with non UCRT R session as well.

**Comment by jgutman** [comment]
This would greatly benefit from some automated tests.

Paths to test should include non-ASCII characters, Chinese characters, spaces, and recursive elements
```
search äöü test/subfolder
test-äöü/äöü
dir with spaces
你好
你好/你好
你好/subfolder
```

**Comment by timtmok** [comment]
It's looking good for RStudio-2022.06.0-daily-246 on Windows.
