### ISSUE TITLE
Pheatmap not drawn in shiny app window, but in plots pane

### ISSUE THREAD

**Issue by paulimer** [rstudio/rstudio#9883]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717-2
    OS Version      : Fedora 34 (Wayland session)
    R Version       : 4.0.5

### Steps to reproduce the problem
Use the plots pane (with a command such as `RColorBrewer::display.brewer.all()`).
Then run a shiny app with a heatmap from the package pheatmap.
The heatmap does not show in the app, but in the plots pane.

### Describe the problem in detail
Below is some sample code with which I have been able to reproduce the issue. One should use the Plots Pane, then run the shiny app below. This issue disappears on a R session restart, and reappears if the plots pane is used at some point.
Furthermore, this issue does not affect ggplot2's plots, or base plots, but only pheatmap's.

```r
library(shiny)
library(pheatmap)
library(ggplot2)
library(dplyr)

ui <- fluidPage(
  title = "Heatmap",
  plotOutput("heatmap"),
  plotOutput("ggplot"),
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$heatmap <- renderPlot(
    {
      data <- mtcars %>% 
        select(where(is.numeric))
      data_cor <- cor(t(data))
      pheatmap(
        mat = as.matrix(data_cor)
      )
    }
  )
  output$ggplot <- renderPlot({
    mtcars %>% ggplot(aes(x = mpg, y = hp)) +
      geom_point()
  })
  output$plot <- renderPlot({
    plot(x = mtcars$mpg, y = mtcars$hp)
  })
}

shinyApp(ui, server)
```

### Describe the behavior you expected
The pheatmap heatmap to appear in its rightful place, in the app itself.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [  ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@paulimer Thank you for raising this! I can't reproduce it, though. Could you provide a screenshot of what you're seeing?

**Comment by paulimer** [comment]
Oh I just realized that I commented out `plotOutput("heatmap")` in the reproducible example (edited now). If you comment it in, and then run the app, you will (hopefully) see the 3 plots, such as this :
![before_using_plot_pane](https://user-images.githubusercontent.com/72985844/141837537-ca1c61a3-c07e-4174-bcfc-deb347d1b7b4.png)
If, aftewards, you use the plots pane, with a command such as `RColorBrewer::display.brewer.all()` for instance, and then rerun the app, the heatmap will be missing, such as that :
![after_using_plots_pane](https://user-images.githubusercontent.com/72985844/141837827-4a759b2f-4d11-4ce2-8164-ec9c219af661.png)

Thanks for your answer! 

PS : It is not a big issue anyways, and if anyone needs to circumvent it, one can use the `ComplexHeatmap::pheatmap()` converter, as the issue does not affect plots drawn with the Bioconductor ComplexHeatmap package.

**Comment by ronblum** [comment]
@paulimer That `#` makes all the difference. :) I can reproduce this in the current development release of RStudio Desktop, 20212.01.0+-daily+199, and all the way back to 1.2.5042 (similar though not identical behavior) on MacOS 12. We'll review this as we continue development of RStudio.
