### ISSUE TITLE
.rs.describeObject calls length S3 generic, which might fail 

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#9887]
Here is a minimal example:

```
length.foo = function(x) stop("error!")
registerS3method("length", "foo", length.foo)
foo <- 1
attributes(foo) <- list(class = "foo")
#> Error in length.foo(obj) : error!
foo
#> [1] 1
#> attr(,"class")
#> [1] "foo"
```

`.rs.describeObject` seems to be called whenever an object is created or modified in the console and it uses `length`, `length` being a generic, some S3 methods might fail.

I don't know if it's ever desirable to have a length method fail, but the error is hard to debug if we do. Moreover I believe this might lead to other errors as I suspect you actually want the length of the underlying atomic object, you might need `length(unclass(x))` rather than `length(x)`.

**Comment by kevinushey** [comment]
We could do something here, but IMHO any `length` implementation that doesn't return a numeric value is poorly behaved and is bound to be broken in a myriad of other contexts.
