### ISSUE TITLE
Sort tabs in source edit window

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#9890]
This was already filed a few years ago, as https://community.rstudio.com/t/sort-source-file-tabs-alphabetically-in-ide/5760, but that was closed when https://github.com/rstudio/rstudio/issues/1664 was opened.  However, the request to sort tabs alphabetically never made it into 1664.  So, I'd like to suggest it again.

The original suggestion would have something like "Sort tabs" on the tab context menu.  An alternative way to do it is to add a project option to "keep source files sorted alphabetically".  I'd slightly prefer the latter, but either one would be fine.

**Comment by ronblum** [comment]
@dmurdoch Thank you for filing the suggestion! We'll review it as we continue development of RStudio.

**Comment by kuriwaki** [comment]
As the author of that original inquiry, I want to thank @dmurdoch for reviving this.  I think this is a common enough use case and will also incentivize the tidyverse style guide recommendation of naming scripts 01_, 02_.
