### ISSUE TITLE
"Open File in New Column" opens blank column when attempting to open a file currently in the editor

### ISSUE THREAD

**Issue by valerie-rstudio** [rstudio/rstudio#9891]
### System Details

    RStudio Edition : Server
    RStudio Version : 2021.12.0-daily+80
    OS Version      : ubuntu20
    R Version       : 4.0.3

### Summary
A blank column is opened if an already open file is selected by "File > Open File in New Column".

### Repro Steps
1. Create a new R Script. Save and name it. Keep the file open in the editor.
2. Click File > Open File in New Column.
3. Select the newly created R Script that is already open in the original editor column.
4. **Expected**: No new column is created.
5. **Actual**: New blank column is created. File remains open in original column.

### Notes
The "Open Each File in New Columns" option from the Files pane follows the expected results.

**Comment by mikebessuille** [comment]
Seeing a file in two columns is covered in https://github.com/rstudio/rstudio/issues/2129.   If the user is able to close the blank column, we should close this as expected behaviour for now, until #2129 is implemented.

**Comment by mikebessuille** [comment]
See previous comment; closing this in preference of #2129.
