### ISSUE TITLE
In visual mode, line numbers show in collapsed chunks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9892]
### System details

    RStudio Edition : Both
    RStudio Version : 2021.12.0+80

### Steps to reproduce the problem

1. Open an R Markdown document in the visual editor.
2. Create an R chunk with a few lines of code.
3. Turn on the option that shows line numbers in the visual editor (e.g. Command Palette => Show line numbers in visual mode chunks)
4. Run the chunk
5. Collapse the chunk

### Describe the problem in detail

The line numbers are still rendered, and overlap the chunk's output.

![image](https://user-images.githubusercontent.com/470418/134987064-f4ab6b8c-b867-4add-9984-4656361ec3d3.png)

### Describe the behavior you expected

The line numbers should not be visible.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by valerie-rstudio** [comment]
@jmcphers - Is the expected result now that after running and collapsing a chunk in visual mode, both the code and the output is collapsed? Or is the expected result now that after running and collapsing a chunk in visual mode, the code is collapsed, the line numbers are no longer shown, and the output is still visible?
