### ISSUE TITLE
.rs.api.getActiveDocumentContext() and .rs.api.getSourceEditorContext() return "path" with incorrect encoding

### ISSUE THREAD

**Issue by ArcadeAntics** [rstudio/rstudio#9897]
`.rs.api.getActiveDocumentContext` and `.rs.api.getSourceEditorContext` return component "path" without a declared encoding.
They should be declared explicitly as "UTF-8" encoded.

I have no reproducible example, but I have a screenshot of the unexpected behaviour:
![image](https://user-images.githubusercontent.com/14181583/135345512-c2503987-9b38-42fc-9c59-7f117d22422f.png)

Thank you!

**Comment by ArcadeAntics** [comment]
@ronblum One thing I hadn't considered before, it's possible that this is a Windows exclusive problem. So maybe you won't notice it on another OS. In Windows, I did something like:

```
x <- path.expand("~/\u{03B4}.R")
file.create(x)
```

and then once I had it open in RStudio, I ran:

```
paths <- paths2 <- c(
    active = .rs.api.getActiveDocumentContext()$path,
    source = .rs.api.getSourceEditorContext()$path
)
Encoding(paths2) <- "UTF-8"
paths <- c(paths, paths2)


print(cbind(
    paths, Encoding(paths), file.exists(paths), deparse.level = 2
))
```

which returned:

```
> paths <- paths2 <- c(
+     active = .rs.api.getActiveDocumentContext()$path,
+     source = .rs.api.getSourceEditorContext()$path
+ )
> Encoding(paths2) <- "UTF-8"
> paths <- c(paths, paths2)
> 
> 
> print(cbind(
+     paths, Encoding(paths), file.exists(paths), deparse.level = 2
+ ))
       paths    Encoding(p... file.exist...
active "~/Î´.R" "unknown"     "FALSE"      
source "~/Î´.R" "unknown"     "FALSE"      
active "~/δ.R"  "UTF-8"       "TRUE"       
source "~/δ.R"  "UTF-8"       "TRUE"       
> 
```

showing that the paths without a declared "UTF-8" are incorrect.

**Comment by kevinushey** [comment]
I think this has since been fixed in the `rstudioapi` package; we take care of marking the encoding there.

https://github.com/rstudio/rstudioapi/blob/dedf09faccccd0eb89c58c5d742a4336bc37af86/R/document-methods.R#L215-L216

We could also consider marking the encoding on the RStudio side, but since users should normally be calling RStudio's APIs through the `rstudioapi` package I think we can close this.
