### ISSUE TITLE
RStudio 2021.09.0+351 fails to start if old `directory-view-whitelist` option is present in /etc/rstudio/rsession.conf

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#9898]
### System details

    RStudio Edition : Server
    RStudio Version : 2021.09.0+351
    OS Version      : Ubuntu Server 20.04.3 LTS
    R Version       : 4.1.1

### Steps to reproduce the problem
- Add `directory-view-whitelist=/srv/shiny-server` to `/etc/rstudio/rsession.conf`
- Upgrade RStudio Server from 1.4.1717 to 2021.09.0+351
  ```
  wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2021.09.0%2B351-amd64.deb
  sudo gdebi rstudio-server-2021.09.0+351-amd64.deb
  ```
- Try to log-in

### Describe the problem in detail
After upgrading RStudio Server I can't log-in, I get the error message "Cannot Connect to R Session" if `directory-view-whitelist=/srv/shiny-server` is set in `/etc/rstudio/rsession.conf`, I had this option to allow me to open RStudio Projects from "forbidden" locations since RStudio 1.3, apparently, you have changed this option name to `directory-view-allow-list` and if the old option is present it prevents RStudio from starting without giving any useful error message.
![image](https://user-images.githubusercontent.com/14981085/135363607-a8d94eab-47fb-4f43-9366-77b91c07a3c9.png)
```
ubuntu@ip-172-31-38-71:~$ sudo rstudio-server verify-installation
Error reading /etc/rstudio/rsession.conf: unrecognised option 'directory-view-whitelist'
```
If I rename the option, everything works as expected, although it seems is no longer needed for `/srv/shiny-server/` since I can open RStudio Projects from '/srv/shiny-server' without the option set.

### Describe the behavior you expected

Back compatibility with the old option name or a more informative error message when the log-in fails instead of a "Cannot Connect to R Session" message.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
This was listed in the Ghost Orchid release notes as a breaking change, but can see where having a previously working installation stop working after upgrade is not ideal.

> BREAKING: The session-env-var-save-blacklist option has been renamed to session-ephemeral-env-vars.
> BREAKING: The directory-view-whitelist option has been renamed to directory-view-allow-list.

Thanks for the report.

**Comment by andresrcs** [comment]
I noticed it hours after filing this issue, maybe you could consider adding a warning about this breaking changes in the blog post as well, not all people installing RStudio Server are sys admins and many like me are just going to rush installing the new version after read the blog post and without going through the complete release notes.

**Comment by mikebessuille** [comment]
Next time we introduce a breaking change like this, we need to do better.  For this particular case, I'm not aware of many support concerns so I'll close this particular issue, but will make sure any future breaking changes get better up-front coverage, and that we do better to detect and notify users who are using deprecated settings (or auto-update them where appropriate)
