### ISSUE TITLE
RSTUDIO_VERSION not set correctly when rendering website in Build Pane

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#9903]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2021.12.0.89
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.1 (2021-08-10)

### Describe the problem in detail

This follows previous issue #9795 reported and PR #9796 to fix it which seem to be incomplete.

Currently, the environment variable `RSTUDIO_VERSION` is not set the same when code is executed in the "Build" Pane or in "Render" pane. In the latter, `RSTUDIO_VERSION` is set to a parsable R string version but in the former, it is still set to the long version string. The previous PR has correctly fix the issue for Render Pane only, tested when knitting. 

When rendering a website in the IDE, the rendering is trigger in the Build pane and it seems to be a different environment. 

## Step to reproduce

* Create a new R Markdown website
* Paste the chunk in `index.Rmd`
  ````r
  ```{r, error = TRUE}
  Sys.getenv("RSTUDIO_VERSION")
  Sys.getenv("RSTUDIO_LONG_VERSION")
  package_version(Sys.getenv("RSTUDIO_VERSION"))
  ```
  ````
* Build the site using the button in Build site. Result of the chunk will be: 
  ````
  Sys.getenv("RSTUDIO_VERSION")
  ## [1] "2021.09.0+351"
  Sys.getenv("RSTUDIO_LONG_VERSION")
  ## [1] ""
  package_version(Sys.getenv("RSTUDIO_VERSION"))
  ## Error: spécification de version incorrecte '2021.09.0+351'
  ````

* Render `index.Rmd` using the knit button (preview mode for a wesbite - render only one doc)
  Result will be 
  ````
  Sys.getenv("RSTUDIO_VERSION")
  ## [1] "2021.09.0.351"
  Sys.getenv("RSTUDIO_LONG_VERSION")
  ## [1] "2021.09.0+351"
  package_version(Sys.getenv("RSTUDIO_VERSION"))
  ## [1] '2021.9.0.351'
  ````

As you see the value to `RSTUDIO_VERSION` is not the same depending how the website is rendered in the IDE.

## Expect behavior

It should be the same in both environment with `RSTUDIO_VERSION` being a R parseable string version using only numbers and `.`. Same fix as what as been done in #9796. 

In fact, I thought it would apply everywhere in the IDE. but I discovered this with last release made while working on **distill**. I should have tested more. 

BTW I did not tested rendering in Jobs pane as I don't know if that could happen or not really - maybe same issue ?

As this is a breaking behavior for **distill** users with last IDE, we have pushed a fix on our side in dev version of the R package: https://github.com/rstudio/distill/commit/52ba8cf3e240a25048c7dcf8a3cf5f55d5f18f01

But it would be better for it to be fixed upstream in the IDE.

**Comment by ronblum** [comment]
Added failure: publishing to Connect results in a similar issue, even for a knitted Rmd file.

**Comment by ronblum** [comment]
Assigning for the moment to Prairie Trillium, but tagging as `triage` to consider for Ghost Orchid.

**Comment by mikebessuille** [comment]
Could consider backporting to 2021.09.1 if necessary.

**Comment by jgutman** [comment]
With changes under review, above reprex now works correctly and identically when knitting and when using the build pane to render the website: 

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/7817881/159363094-9bf96ada-2258-4893-97ab-a0c5676fae23.png">

**Comment by timtmok** [comment]
Looks good in 2022.06.0-daily+246
