### ISSUE TITLE
`UNKNOWNSIG _gpgbuilder` when Validating RStudio Signed Build Signatures

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#9904]
I got the next when I follow instructions specified in https://www.rstudio.com/code-signing/, previously to install the last version of rstudio:
```r
gpg --keyserver keys.openpgp.org --recv-keys 3F32EE77E331692F
dpkg-sig --verify rstudio-2021.09.0+351-amd64.deb
Processing rstudio-2021.09.0+351-amd64.deb...
UNKNOWNSIG _gpgbuilder E331692F
```
Is it fine?

Nottwithstanding, it seems there is no problem installing it by means of `dpkg -i rstudio-2021.09.0+351-amd64.deb
`.

### System details

    RStudio Edition : Desktop
    RStudio Version : Ghost Orchid
    OS Version      : Linux  5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux (Debian GNU/Linux 11 (bullseye))
    R Version       :  4.1.1

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@iago-pssjd Thank you for raising this! I believe this is an issue we are currently trying to resolve, but let's keep this open in the meantime.

**Comment by jeffvroom** [comment]
Updated the documentation at this link:  https://www.rstudio.com/code-signing/ to point to a different keyserver and added instructions on how to manually import the signing key if the keyserver is not accessible for some reason.

**Comment by AndrewMcClain** [comment]
Confirmed that the docs changes lead to being able to verify the signing key.

keys.openpgp.org is returning a key without a user id
