### ISSUE TITLE
Insert assignment operator shortcut `Alt+-` inserts `=` instead of `<-` in R chunks in R Markdown file

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/rstudio#9905]
Using `Alt+-` inserts `=` instead of `<-`  in R chunks in an R Markdown file. Is this behaviour expected? I found it surprising. Could it be a regression in this last version?

### System details

    RStudio Edition : Desktop
    RStudio Version : "Ghost Orchid" Release (077589bc, 2021-09-20) 
    OS Version      : Linux  5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux (Debian GNU/Linux 11 (bullseye))
    R Version       :  4.1.1

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@iago-pssjd Thank you for the bug report! Although I can't reproduce this within chunks, I can reproduce this in the body of an R Markdown document in both RStudio Desktop 2021.09.0+351 on MacOS 12 and Debian 11.

**Comment by mikebessuille** [comment]
the body of the r markdown is not R, it's markdown, so it's expected that the shortcut wouldn't result in <-

**Comment by iago-pssjd** [comment]
@mikebessuille  It happened to me inside R chunks. How could I create a reprex for this? Anyway, in one file I found this behaviour on Friday, today it is working rightly. May this behaviour be related to another strange behaviour, which causes sometimes (I do not know how to identify them) RStudio do not shading exactly the RMarkdown lines where the chunk is placed?

**Comment by mikebessuille** [comment]
@iago-pssjd, yes, if RStudio was incorrectly identifying your chunks as though they were not chunks, the keyboard shortcuts would work as you described (The IDE thinks it's not in a chunk when it is).   I think we need a clear reprex to figure out what's going on.
