### ISSUE TITLE
Graphical output of Python cells not displayed in Quarto notebooks

### ISSUE THREAD

**Issue by almereyda** [rstudio/rstudio#9908]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for CentOS 8
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Fedora 34
    R Version       : 4.0.5 (2021-03-31) -- "Shake and Throw"

### Steps to reproduce the problem

1. Create a Quarto notebook with `qmd` extension #9556
2. Use a Python kernel to generate graphical output
3. Only find the internal Python representation of the object, and not its `__repr__` displayed

### Describe the problem in detail

Please see this screenshot:

![Bildschirmfoto von 2021-10-02 10-42-29](https://user-images.githubusercontent.com/1645308/135709982-725ed044-43ff-49e7-b927-cc1e4ba488ed.png)

### Describe the behavior you expected

Instead of `<graphviz.files.Source object at 0x7f9dc9e6ef10>` we would like to see the rendered output here, similar to Jupyter.

`quarto convert index.qmd`

In Visual Studio Code:

![Bildschirmfoto von 2021-10-02 10-48-40](https://user-images.githubusercontent.com/1645308/135709962-062a5b2c-3a6f-4e70-a51a-8b0cf8c84791.png)

In Jupyter Lab:

![Bildschirmfoto von 2021-10-02 10-49-58](https://user-images.githubusercontent.com/1645308/135709969-0d0bc32e-c5a7-4d37-9de8-36d867c269c7.png)

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] ~~If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).~~
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by almereyda** [comment]
This might also be due to a mix of Python environments, where site-packages are loaded from system, but certain modules imported from the venv:

![Bildschirmfoto von 2021-10-02 11-16-58](https://user-images.githubusercontent.com/1645308/135710485-166be0ef-e1a2-4cc4-bb23-c7b11c5c3523.png)

This can possibly be a mixup between the `pyenv` `python3` shim and the used `pipenv`, where RStudio cannot decide between the one or the other.

```shell
# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x [11:14:59]
$ type python3
python3 is /home/yala/.pyenv/shims/python3

# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x [11:19:15]
$ type python
python is /home/yala/.pyenv/shims/python

# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x [11:19:20]
$ pipenv shell
Launching subshell in virtual environment...
 . /home/yala/.local/share/virtualenvs/documentation-EDOFPCMD/bin/activate

# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x [11:19:30]
$  . /home/yala/.local/share/virtualenvs/documentation-EDOFPCMD/bin/activate
(documentation)
# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x documentation-EDOFPCMD [11:19:31]
$ type python3
python3 is /home/yala/.local/share/virtualenvs/documentation-EDOFPCMD/bin/python3
(documentation)
# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x documentation-EDOFPCMD [11:19:34]
$ type python
python is /home/yala/.local/share/virtualenvs/documentation-EDOFPCMD/bin/python
(documentation)
```

```shell
# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x documentation-EDOFPCMD [11:19:37]
$ pyenv local
pyenv: no local version configured for this directory
(documentation)
# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x documentation-EDOFPCMD [11:21:01] C:1
$ pyenv global
system
(documentation)
# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x documentation-EDOFPCMD [11:21:09]
$ exit

# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x [11:21:12]
$ pyenv local
pyenv: no local version configured for this directory

# yala @ pons in ~/src/lab.libreho.st/libernetes/documentation on git:main x [11:21:16] C:1
$ pyenv global
system
```

**Comment by almereyda** [comment]
Attempting to render will yield the same output as https://github.com/quarto-dev/quarto-cli/issues/121

```
Starting Jupyter kernel...Done


An error occurred while executing the following cell:
------------------

# imports
import os
import sys
import types
import json

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = fig_dpi
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  pio.renderers.default = "notebook_connected"
except Exception:
  pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass



# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))


# reset state
%reset

def ojs_define(**kwargs):
  import json
  from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v
  
  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define

------------------

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_26224/4071903457.py in <module>
     53   if path.endswith(".pyc") or path.endswith(".pyo"):
     54     path = path[:-1]
---> 55   kernel_deps[path] = os.stat(path).st_mtime
     56 print(json.dumps(kernel_deps))
     57 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.9/pydoc_data/topics.py'
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.9/pydoc_data/topics.py'
```

**Comment by jjallaire** [comment]
I think the issue is that RStudio currently only recognized some HTML/image output sources (e.g. we do support matplotlib and seaborn, but not Jupyter widgets). One thing we recently added was support for discovering and calling any `to_html()` method on objects. Do you know if the graphviz object has a `to_html()` method?

**Comment by almereyda** [comment]
That module currently only implements a `_repr_svg()` method.

https://github.com/xflr6/graphviz/blob/6e9774b578d86e8048bec90db6c745cedbaa768b/graphviz/files.py#L140-L141

Would it be sufficient to upstream the need for a `_repr_html()` method to be called

**Comment by almereyda** [comment]
Thanky you for jumping on this on a weekend. 🙏 That module currently only implements a `_repr_svg()` method.

https://github.com/xflr6/graphviz/blob/6e9774b578d86e8048bec90db6c745cedbaa768b/graphviz/files.py#L140-L141

Would it be sufficient to upstream the need for a `_repr_html()` method here?

Fruther I am a little confused, why this works through IPython notebooks. They appear to be less strict with the `_repr*` function they choose to display?

In my understanding, and please correct me, if I am wrong, because I wasn't able to find a technical specification for either Quarto (notebooks) or R markdown (whose processor is used in RStudio, if not mistaken, but extended for Quarto?) similarily to the one in https://ipython.readthedocs.io/en/stable/config/integrating.html, Quarto is not recognising other than `_repr_html_()` methods of an object, and omits the possibility to display any other. Maybe it would be possible to follow the Jupyter specification here more strictly, to achieve equal interoperability?

Unfortunately I can also not find the place in the Quarto, nor RStudio sources, where it calls `to_html()`, which then uses `_repr_html_()` to retrieve what it needs. Eventually SVG is only another XML dialect, and should be able to be displayed natively by the HTML engine that RStudio uses.

Is there a list of the other supported image sources which can be valuable mediums for outputting to RStudio?
