### ISSUE TITLE
Unable to see/ open News while updating packages through GUI.

### ISSUE THREAD

**Issue by nviraj** [rstudio/rstudio#9909]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  2021.09.0+351
    OS Version      :  Windows 10 x64 (build 19043)
    R Version       :  4.1.1 (2021-08-10)

### Describe the problem in detail

Hi, 
So when I try to update packages through RStudio, the update packages window opens fine. I can also update all packages flawlessly. The issue is with the news section.

Clicking on the News button opens a small notification saying "Opening NEWS" but doesn't do anything post that. Currently, I have to search for news manually. Kindly let me know if you need any additional information from my end.

![rstudio_nwh48giDy6](https://user-images.githubusercontent.com/8409854/135743126-cdc5aa3e-97a1-4f06-91a4-7405b3c79969.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@nviraj Thank you for raising this! I'm unable to reproduce the problem, though, in RStudio Desktop 2021.09.0+351 on MacOS 12 and Windows 10. Could you please include the recent log files, after you run into the issue? You can find them with <kbd>Help -> Diagnostics -> Show Log Files</kbd>.

**Comment by nviraj** [comment]
Hi @ronblum,

Thanks for looking into this. Here you go! One log file is from the date I raised the issue (Oct 3rd), the other one is from today (Oct 5th). 
[rsession-user.2-20211003.log](https://github.com/rstudio/rstudio/files/7286882/rsession-user.2-20211003.log)
[rsession-user-20211005.log](https://github.com/rstudio/rstudio/files/7286883/rsession-user-20211005.log)

Hope this helps!

**Comment by nviraj** [comment]
I am not sure if it is related, but I sometimes see this message in Console tab after updating packages.
`Warning message:
In .rs.rpc.get_package_news_url("stringi", "C:/Users/user/Documents/R/win-library/4.1") :
  Failed to infer appropriate NEWS URL: using 'NEWS' as best-guess candidate`
