### ISSUE TITLE
Hard hang on open in Ubuntu 21.10 

### ISSUE THREAD

**Issue by QMeqGR** [rstudio/rstudio#9910]
### System details

    RStudio Edition : Desktop
    RStudio Version : rstudio-2021.09.0-351-amd64.deb
    OS Version      : Ubuntu 21.10 beta
    R Version       : 4.0.2

### Steps to reproduce the problem

issue the command 'rstudio'

### Describe the problem in detail

On starting Rstudio the application window opens, but is empty except for the menu bar. None of the pulldown menus work.

### Describe the behavior you expected

To open as it usually does.

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[rstudio-hang.txt](https://github.com/rstudio/rstudio/files/7273530/rstudio-hang.txt)

**Comment by ronblum** [comment]
@QMeqGR Thank you for raising this! This was also reported previously, as #9854. There a couple of suggestions, including a workaround described at https://github.com/rstudio/rstudio/issues/9854#issuecomment-926445284.
