### ISSUE TITLE
Rstudio desktop fails to run under Debian 10 (Buster)

### ISSUE THREAD

**Issue by celaxodon** [rstudio/rstudio#9912]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0-351
    OS Version      : Debain 10 
    R Version       : 3.5.2

### Steps to reproduce the problem

[This Dockerfile](https://gist.github.com/celaxodon/c66122fb12bf294d1b5609afba3d7309) contains a minimal reproduction based on docker.io/debian:buster-slim:
```
$ docker build . -f rstudio-repro.Dockerfile -t rstudio-repro:latest
$ docker run --rm -it e DISPLAY=<my-vnc-address> rstudio-repro:latest
root@229180c9451d:/# rstudio
qt.qpa.xcb: failed to initialize XRandr
qt.qpa.xcb: X server does not support XInput 2
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
rsession-[61]: WARNING Unable to determine LANG (proceeding with no LANG set; LOGGED FROM: void rstudio::core::r_util::ensureLang() src/cpp/core/r_util/REnvironmentPosix.cpp:1000

[8:81:1004/181235.306003:ERROR:gl_surface_glx_qt.cpp(141)] GLX 1.3 or later is required.
[8:81:1004/181235.306052:ERROR:gl_ozone_glx_qt.cpp(57)] GLSurfaceGLXQt::InitializeOneOff failed.
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
QSGContext::initialize: stencil buffer support missing, expect rendering errors
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 168, resource id: 53, major code: 131 (Unknown), minor code: 47
rsession-[61]: ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1431

rsession-[61]: ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1431

Segmentation fault (core dumped)
```

### Describe the problem in detail

I am trying to create a container image based on R 3.5.2 and have rstudio working. My users use VNC sessions, and launching Rstudio in the VNC session for development can work quite well for them. For example, the [compdatasci/rstudio-desktop](https://github.com/compdatasci/rstudio-desktop) container image (Ubuntu 18.04 base image using R 3.6.3 and Rstudio desktop version xenial-1.1.383) can work using the above instructions. Unfortunately, in newer versions or with different base operating systems/R versions it seems like there are some library issues and rstudio desktop is crashing when launched, possibly due to GLX errors.

Wondering if this is similar to #9515.

Diagnostics reports fail to run with similar output:
```
root@229180c9451d:/# rstudio --run-diagnostics
qt.qpa.xcb: failed to initialize XRandr
qt.qpa.xcb: X server does not support XInput 2
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

Using R script: /usr/bin/R

Attempting to launch R session...
  R_HOME=/usr/lib/R
  R_DOC_DIR=/usr/share/R/doc
  R_INCLUDE_DIR=/usr/share/R/include
  R_SHARE_DIR=/usr/share/R/share
  LD_LIBRARY_PATH=/usr/lib/R/lib:/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  HOME=/root

R session launched, attempting to connect on port 34151...
rsession-[165]: WARNING Unable to determine LANG (proceeding with no LANG set; LOGGED FROM: void rstudio::core::r_util::ensureLang() src/cpp/core/r_util/REnvironmentPosix.cpp:1000

2021-10-04T18:25:34.380230Z [rsession-] WARNING Unable to determine LANG (proceeding with no LANG set; LOGGED FROM: void rstudio::core::r_util::ensureLang() src/cpp/core/r_util/REnvironmentPosix.cpp:1000
[111:185:1004/182534.468990:ERROR:gl_surface_glx_qt.cpp(141)] GLX 1.3 or later is required.
[111:185:1004/182534.469051:ERROR:gl_ozone_glx_qt.cpp(57)] GLSurfaceGLXQt::InitializeOneOff failed.
Successfully initialized R session.

Diagnostics report written to: /root/rstudio-diagnostics/diagnostics-report.txt
Please audit the report and remove any sensitive information before submitting.

Connected to R session, attempting to initialize...

qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 168, resource id: 53, major code: 131 (Unknown), minor code: 47
```
### Describe the behavior you expected

Expect Rstudio desktop to launch in a GUI session without crashing.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report). (attempted)
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by benjamir** [comment]
(Debian Buster:)
# apt policy libqt5gui5
libqt5gui5:
  Installed: 5.11.3+dfsg1-1+deb10u4
  Candidate: 5.11.3+dfsg1-1+deb10u4
  Version table:
 *** 5.11.3+dfsg1-1+deb10u4 500
        500 http://ftp.de.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
     5.11.3+dfsg1-1+deb10u3 500
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages

# ldd /usr/bin/rstudio | head -2
/usr/bin/rstudio: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/bin/rstudio)
	linux-vdso.so.1 (0x00007ffd65caf000)


The package for Ubuntu Bionic/Debian 10 ("Buster") wants Qt_5.12 but neither Bionic (5.9) nor Buster (5.11) use that version?

**Comment by MariaSemple** [comment]
Can you check whether there are libQt `so` files under `/usr/lib/rstudio/lib`? That is where my local installation is looking. If that is the case, you may be able to resolve the QT dependency issue by setting `LD_LIBRARY_PATH=/usr/lib/rstudio/lib:${LD_LIBRARY_PATH}`  in your dockerfile.

**Comment by celaxodon** [comment]
Thanks for the suggested workaround , @MariaSemple. Unfortunately this did not work. Confirmed I do have `.so` files under `/usr/lib/rstudio/lib`, but after updating LD_LIBRARY_PATH I still get GL errors and a segfault:

```
root@914ab5b9cf5e:/# set | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=/usr/lib/rstudio/lib:/usr/lib/R/lib:/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server

root@914ab5b9cf5e:/# rstudio
qt.qpa.xcb: failed to initialize XRandr
qt.qpa.xcb: X server does not support XInput 2
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
rsession-[283]: WARNING Unable to determine LANG (proceeding with no LANG set; LOGGED FROM: void rstudio::core::r_util::ensureLang() src/cpp/core/r_util/REnvironmentPosix.cpp:1000

[230:303:0120/201520.107659:ERROR:gl_surface_glx_qt.cpp(141)] GLX 1.3 or later is required.
[230:303:0120/201520.107715:ERROR:gl_ozone_glx_qt.cpp(57)] GLSurfaceGLXQt::InitializeOneOff failed.
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
QSGContext::initialize: stencil buffer support missing, expect rendering errors
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 168, resource id: 53, major code: 131 (Unknown), minor code: 47
rsession-[283]: ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1431

rsession-[283]: ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1431

Segmentation fault (core dumped)
```
