### ISSUE TITLE
External hook to open file / notebook in server?

### ISSUE THREAD

**Issue by matthew-brett** [rstudio/rstudio#9925]
Please forgive me if this is not the right place to ask.

What is the the correct way to send a message, to RStudio server, from an external process, to request that it open a file, and particularly, a notebook?

The reason I am asking is that I use this feature all the time, in teaching and tutorials, for Jupyter Notebooks, and via services like BinderHub.

BinderHub allows me to craft a link in my textbook, of the following form:

https://mybinder.org/v2/gh/resampling-stats/resampling-with/gh-pages?filepath=python-book/ambulances.ipynb

This opens the Jupyter Notebook attached to a (free) cloud instance, via a customized [repo2docker](https://github.com/jupyterhub/repo2docker) docker container *at the specified notebook*, so the student can interact with the notebook immediately.  This is very useful, particularly for beginners.

I really want to be able to do this with an RStudio notebook, but, as things stand, this is not possible - see [this Github issue](https://github.com/jupyterhub/binderhub/issues/325).   I can only ask for RStudio to be opened, but the user must then nagivate to the particular notebook, and open it.  For a fairly large textbook, this will be confusing.

Are we missing some simple way to pass a message to a running RStudio process, to open a notebook?   There are some details about what we have found, and what we need at [this comment](https://github.com/jupyterhub/binderhub/issues/325#issuecomment-935865113), but I'm happy to explore for more information if that would help.

**Comment by ronblum** [comment]
@matthew-brett Yep, you're in the right place, since it's possible that it's a bug or enhancement request for RStudio! I'm not sure if this would be considered a bug or enhancement, so I'll start by labeling it as a bug for review.

**Comment by ryanlovett** [comment]
Hi @ronblum , I noticed that [rstudioapi::remote](https://rdrr.io/cran/rstudioapi/src/R/remote.R) uses the value of three environment variables to hook into RStudio: `RSTUDIOAPI_IPC_REQUESTS_FILE`, `RSTUDIOAPI_IPC_RESPONSE_FILE`, and `RSTUDIOAPI_IPC_SHARED_SECRET`. Can those values be shared via externally accessible API, or can RStudio be configured with these values at launch? If so, would that be sufficient to help @matthew-brett do what he wants?

**Comment by matthew-brett** [comment]
Just a ping here - for our textbook, we have to decide whether to use RStudio, or switch to using R in the Jupyter notebook.    We'd rather use RStudio, because it's a better match for what the students should be learning for later R use, but it would just be too clunky and confusing to send them into the default RStudio GUI, with the instruction to remember the filename of the notebook they need, and navigate to it.   Is it reasonable to hope for a solution in the next month or so?  Or should we switch to Jupyter?

**Comment by matthew-brett** [comment]
OK - we'll switch to using R in Jupyter, assuming that no changes are imminent here, but please do let us know if that changes.

**Comment by stefanv** [comment]
Still a valid feature request.

**Comment by jameshowison** [comment]
Just a note that this request working would be great for course material with server hosted Rstudio instances.  It is (I think) needed for the infrastructuring underlying a gitpuller approach (I give a student a link with a git repo encoded in it, the system syncs the repo to their workspace, then opens a file for them to work in, e.g., an Rnotebook file.

**Comment by matthew-brett** [comment]
Still wishing for this feature so we can teach R in RStudio rather than Jupyter ...
