### ISSUE TITLE
FR: spell check for content in heading and subheadings in `{rmarkdown}` files

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#9926]
Currently, spell check works only for the body of the content, but not for headings and subheadings of {rmarkdown} document. 

It would be nice if _RStudio_ can also flag spelling mistakes in headings and subheadings:

![image](https://user-images.githubusercontent.com/11330453/136219304-92c03676-4ce9-4396-8ce4-649e53cd0b7b.png)

**Comment by ronblum** [comment]
@IndrajeetPatil Thank you for the suggestion! We'll review it as we continue to consider feature requests as part of our ongoing development.
