### ISSUE TITLE
ragg backend rendering doesn't work in RMarkdown inline execution

### ISSUE THREAD

**Issue by Gedevan-Aleksizde** [rstudio/rstudio#9931]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 build 351
    OS Version      : MacOS Catalina 10.15.7
    R Version       : 4.1.1

### Steps to reproduce the problem

1. set `AGG` as RStudio's backend graphic device
2. write any plot code in a Rmd file, e.g., 
    ````
	---
	title: "Minimal Example"
	output:
	  html_document:
            dev: ragg_png
	---

	```{r}
    plot(1, main = "あいう ABC", xlab = "あいう ABC")
	```
    ````
3. run the chunk inline (click "run current chunk" or press `cmd` + `shift`  + ` return`)

### Describe the problem in detail

The font is not fallbacking and the Japanese letters are not displayed correctly (see the image). So the output graphic seemed not to be rendered by ragg device. 

<img width="1427" alt="スクリーンショット 2021-10-08 1 19 35" src="https://user-images.githubusercontent.com/8291043/136424533-932eb7db-9f34-461b-bd9e-f6f0e0cf5669.png">

NOTE 1: the versions of related packages and libraries are the latest:

* rmarkdown: 2.11
* knitr: 1.36
* ragg: 1.1.3
* XQuartz: 2.8.1

NOTE 2: I confirmed that ragg's font fallbacking works correctly when running the same code in the console (see the Plots pane in the image).

NOTE 3: This problem may be related with issue #7313. But in my cases, there is no explicit error or warning.

NOTE 4: I added extra line to specify Japanese font like the following code (`YuMincho` is one of the Japanese standard font families in MacOS).

````
```{r}
par(family = "YuMincho")
plot(1, main = "あいう ABC", xlab = "あいう ABC")
```
````

Then the following warnings return and the output has no text:

<details>
  <summary>click to expand</summary>

```
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in axis(side = side, at = at, labels = labels, ...) :
  no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
Warning in title(...) : no font could be found for family “YuMincho”
```

<img width="694" alt="スクリーンショット 2021-10-08 1 26 27" src="https://user-images.githubusercontent.com/8291043/136425802-edc13cf5-0b15-4130-a615-2c6595c08f52.png">

</details>

This code return the correct output when running in the console too. So I infer the ragg device is not called correctly when running inline.

### Describe the behavior you expected

I want to have the inline graphics rendered by a graphic device which is selected as backend. In particular, ragg's font-fallbacking is essential.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@ronblum does this work correctly with the default renderer?
@Gedevan-Aleksizde, does this work if you knit the whole document?

**Comment by ronblum** [comment]
This doesn't work with the default renderer, either.

**Comment by Gedevan-Aleksizde** [comment]
@mikebessuille This issue happens only inside the Rmd editor. either running by "knit" button or executing in console have no problem.

**Comment by kevinushey** [comment]
My guess is that `ragg` is not being used when rendering plots inline in R Markdown documents.

We set a custom graphics device when rendering inline graphics, as per here:

https://github.com/rstudio/rstudio/blob/7c8e5e25f47ae2e1d7fff80c28e030e0931c10ce/src/cpp/session/modules/NotebookPlots.R#L16-L69

But that isn't respecting the requested use of `ragg`. I think we're failing to pass down the configured graphics device type for inline graphics.

**Comment by kevinushey** [comment]
To fix this, I think we would need to pass along the configured graphics device type in the call here:

https://github.com/rstudio/rstudio/blob/7c8e5e25f47ae2e1d7fff80c28e030e0931c10ce/src/cpp/session/modules/rmarkdown/NotebookPlots.cpp#L358-L386

If you want a really hacky workaround, you can execute:

```
trace(.rs.createNotebookGraphicsDevice, quote({
  args$type <- "ragg"
}), at = 3L)
```

**Comment by jgutman** [comment]
Can test this works with the following file:
~~~
---
title: "Minimal Example"
output:
  html_document
---

```{r setup}
install.packages("ragg")
getOption("RStudioGD.backend")
#knitr::opts_chunk$set(dev="ragg_png")
```

```{r debug_chunk, dev='ragg_png'}
getOption("RStudioGD.backend")
plot(1:10, 1:10, main = "あいう ABC", xlab = "あいう ABC")
```

```{r}
getOption("RStudioGD.backend")
plot(1:10, 1:10, main = "あいう ABC", xlab = "あいう ABC")
```

```{r dev='quartz_png', warning=FALSE}
getOption("RStudioGD.backend")
plot(1:10, 1:10, main = "あいう ABC", xlab = "あいう ABC")
```

```{r}
getOption("RStudioGD.backend")
```
~~~
Japanese characters render properly when the RStudio backend device is set to ragg any of the following ways:

via Tools > Global Options > Graphics > Backend -> AGG
via adding dev='ragg_png' to a knitr header chunk and executing that chunk inline
via adding knitr::opts_chunk$set(dev='ragg_png') to the setup chunk to execute all chunks with ragg
Japanese characters do not render and display as empty boxes when the RStudio backend device is set to anything else, including default, quartz, and Cairo.

Chunk options override the global RStudio option, so the dev='quartz_png' will not render the characters even when the global option is set to ragg, and the dev='ragg_png' chunk will render the characters even when the global option is set to default

We can check the value of the option at the beginning, end, and during chunk execution to ensure that the option changes temporarily during chunk execution based on that chunk's header, but is restored to the global option after that chunk finishes executing.

**Comment by romainfrancois** [comment]
This looks great @jgutman. 

Should we be concerned that things do look different between when the graphics is rendered on the notebook, which now honors `RStudioGD.backend` : 

![image](https://user-images.githubusercontent.com/2625526/150573454-7bca3268-2241-4770-984e-b96446c8325b.png)

![image](https://user-images.githubusercontent.com/2625526/150573475-abc05f04-bc99-4fed-bb50-a093b6e79732.png)

and the file is rendered with `knit` : 

![image](https://user-images.githubusercontent.com/2625526/150573561-8919fc05-6968-4b11-aba0-b9776687f132.png)

**Comment by jgutman** [comment]
Good question. The RStudioGd backend option will only handle the rendering
within rstudio console and inline chunks. To render when knit, you'll need
to add dev='ragg_png' as chunk option or chunk default. RStudio will
respect that chunk option, even if the option is not set, but knitr will
only recognize if it's set as the chunk option

**Comment by romainfrancois** [comment]
Right. I think we can close this then. 🎉

**Comment by kevinushey** [comment]
The only thing I'd add -- we might want a separate issue tracking support for reading the requested device from the YAML header. (We generally encourage the use of an R setup chunk + knitr options, but not all users will prefer that workflow).

After that issue has been filed, I think this can be closed.
