### ISSUE TITLE
Sentry: filter out crashes in user's code

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#9932]
There's nothing we can do about crashes in user's code.  We shouldn't bother uploading those reports to Sentry.  This would greatly reduce the number of incoming reports, and allow us to focus on fixing the problems over which we have control.

**Comment by mikebessuille** [comment]
Talk to @kevinushey to plan this, as he's already thought about this problem.

**Comment by ronblum** [comment]
Not planned.
