### ISSUE TITLE
Trouble knitting page number of citations from visual rmarkdown editor

### ISSUE THREAD

**Issue by ghost** [rstudio/rstudio#9938]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2021.09.0+351
    OS Version      :  Windows NT 10.0; Win64; x64
    R Version       :  R version 4.0.3 (2020-10-10)

### Steps to reproduce the problem
I work with visual rmarkdown.
When I add a citation key, for instance [@dunlopPossibleExpertsHow2014], and then add a page number [@dunlopPossibleExpertsHow2014, 209], this no longer gets knitted properly. RStudio knits the citation key rather than the citation itself, centered and a on a new line. The citation knits without problems if I do not add the page number.

### Describe the problem in detail
I'm knitting to a bookdown::pdf_document2 output, documentclass: article. I use the BibTex citation keys from my Zotero library. When I switch back to non visual Rmarkdown the citation key was changed to: \\[@dunlopPossibleExpertsHow2014, 209\\]
I don't know where these backslashes came from. Importantly, if I use the NON visual Rmarkdown editor to add a page number, the page number is added without a problem. So the problem really arises when I knit from visual rmarkdown.
My MiKTeX is updated.
### Describe the behavior you expected
I would have simply expected to have a page number added.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Verified using the example at https://github.com/rstudio/rstudio/issues/10075#issuecomment-969134598 in
- RStudio Desktop 2022.01.0-daily+290 on MacOS 12.1
- RStudio Server 2022.01.0-daily+290 on Ubuntu 20.04.2 via Safari on MacOS 12.1
