### ISSUE TITLE
Warning message on crash does not mention that RStudio has closed the active project

### ISSUE THREAD

**Issue by cboettig** [rstudio/rstudio#9949]
As you know, RStudio provides a helpful error message when in resumes after terminating unexpectedly: https://github.com/rstudio/rstudio/issues/9526

It appears that RStudio also closes the current active project, if any, when this event occurs.  This makes sense -- presumably this is a defensive choice to avoid getting stuck in a vicious cycle.  I'm just writing to request that it be mentioned in the warning; something like "RStudio has not restored the previously active project as a precaution. You may switch back to it using the Projects menu." 

I have dozens of times seen students resume work after such a crash, only to realize that they are no longer in the right project at some point down the road.  

I think the problem is made worse by the fact that RStudio will keep open the same active files(?), but the user is no longer in the active project, so visually, other than the active project name in the top right corner, there is no indication that the user is not back to where they left off.  However, saving those files later results in an error.  (We see this explicitly in RStudio-server setups on kubernetes, which shuts down student's cloud container after inactivity).

**Comment by cboettig** [comment]
@mikebessuille Having that option would be great.  It might be even better if there were an option to re-open the project while jettisoning the active environment and saved open files.  

The reasons for not automatically restoring the previous project are well founded -- over a dozen times this week I have had to give students directions on how to first delete .RData and .RProj.user files in the the crashed project before switching back to it -- a frustrating task since the latter aren't visible from the nice RStudio file-browser pane.  The source of the problems is usually one of two things: attempting to display a large data object in an active Rmd notebook -- causing the student's browser to become unresponsive due to lack of RAM on their own machine; or attempting to read a large data object (or other R session crash) and running out of RAM on the VM side.  

Students also struggle a bit with the difference between these two cases.  (Aside, but RStudio notebooks do an impressive job of *not* printing huge data.frames, thanks to the pretty-print data frame interface, almost too good since when my students first encounter json, lists and other non-rectangular structures in our final module it is suddenly a rude shock to realize that merely trying to print an object they have computed can crash their session!  I know we could have more aggressive max.print settings, but even that struggles with large text blobs. I wonder if there's a more clever default RStudio could use to avoid printing above a threshold number of bytes (either to a notebook or the R console).... is it worth opening a separate issue for that?

**Comment by kevinushey** [comment]
An alternative solution would be to re-open the project in "safe" mode, wherein we bypass most of the session restore machinery (e.g. we don't reload `.RData`, and we don't open any editor tabs). We could indicate this is the case via a message in the console, or a warning bar.

**Comment by cboettig** [comment]
@kevinushey :tada: oh, that sounds brilliant!

**Comment by mikebessuille** [comment]
Could have 3 options:
1) open previous project (normally)
2) Open previous project in safe mode
3) Don't open previous.

**Comment by jgutman** [comment]
This error message is only available in RStudio Server, not RStudio Desktop.

![image](https://user-images.githubusercontent.com/7817881/150161725-698879a1-0d53-43d5-9862-ddbe82b3feab.png)

**Comment by jgutman** [comment]
Verified in RStudio Server 2022.06.0-15.
