### ISSUE TITLE
Custom shortcuts not reflected in "Keyboard Shortcuts Help"

### ISSUE THREAD

**Issue by GCRev** [rstudio/rstudio#9953]
### System details

```shell
    RStudio Edition : Desktop/Server
    RStudio Version : "Prairie Trillium" Daily (99999999, 2021-10-05)
    OS Version      : Ubuntu Hirsute 21.04
    R Version       : 4.1.1
```

### Steps to reproduce the problem

This behavior is described in https://github.com/rstudio/rstudio/issues/5256, but this issue is focused only on "Keyboard Shortcuts Help"

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/5544965/137218278-b0cee0e2-eb55-49b3-b332-ff7c3e7d710f.png)

![image](https://user-images.githubusercontent.com/5544965/137218341-46482182-55cd-4700-b2fa-b653b2e5689a.png)

Customized keyboard shortcuts do not appear in the Keyboard Shortcuts Help overlay.

### Describe the behavior you expected

Custom shortcuts should print out in the Keyboard Shortcuts Help overlay, including when they are cleared out.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] ~If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).~
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
Verified in 2022.01.0-daily+199.pro1 remapping works for a command with and without a default command and added automation coverage for those cases. Closing issue.
