### ISSUE TITLE
Cannot install source package from menu

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9959]
**Steps to reproduce:**
* Download some R package from CRAN in source format (.tar.gz).
* Go to some RStudio project, click `Tools` -> `Install Packages ...` -> `Install from:` -> `Package archive file (.tar.gz)`.
* Click the `Browse` button in `Package archive` below.
* Select said package.

**Expected behavior:** should select the package that was just selected through the selection dialog, and be able to install it from this installation menu.

**Actual behavior:** the source package is not selected and cannot be installed.

**Setup:** RStudio 2021.09.0 Build 351, R 4.1.1, running on debian linux.

This is a regression over previous RStudio versions.

**Comment by johnmackintosh** [comment]
Having updated to build 492 today, I can report this is no longer an issue for me - I was able to browse to the archive , the path was retained in the dialogue box upon selection, and the package was installed successfully:

RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
