### ISSUE TITLE
Rstudio displays the wrong data when viewing nested tibble while filtered

### ISSUE THREAD

**Issue by GeoffRussell** [rstudio/rstudio#9960]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 351
    OS Version      : Ubuntu 20.04.3 LTS
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem

```r
library(tidyverse)
df<-read_csv("Country,Year,Type,TWh,MWhPerCap
Canada,1980,XXX,6.808,0.261
Canada,1981,XXX,6.808,0.461
Canada,1980,SSSS,6.808,0.261
Canada,1981,SSSS,6.808,0.661
France,1980,XXX,6.808,0.261
France,1981,XXX,6.808,1.261
France,1980,SSSS,6.808,0.261
France,1981,SSSS,6.808,1.261
France,1982,SSSS,6.808,2.261
France,1983,SSSS,6.808,3.861
")
ndf<-df %>% group_by(Country,Type) %>% nest()
```

### Describe the problem in detail

Run the above code and then view ndf in rstudio. Hover over any of the nesting icons and the data popped up is good. Now
search for "France" and some lines will disappear. Hover over any of the nesting icons and the data popped up is good.

BUT ... click on the nesting icon and you will see the wrong data.

### Describe the behavior you expected

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [NA ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Cheers,
Geoff

**Comment by jgutman** [comment]
Adding for reference a slightly more minimal reprex:

```
library(dplyr)
library(tidyr)
df<-dplyr::tibble(
  Country=c("Canada", "Canada", "France", "France", "France"), 
  Row=c("Canada1", "Canada2", "France1", "France2", "France3")
)

ndf<- df %>% 
  group_by(Country) %>% 
  nest()
View(ndf)
```
and then follow the same steps above to filter and click into the nested data.

**Comment by jgutman** [comment]
Duplicate #7546 provides another reprex of the same problem using list-cols: 
1. Run the following:
```
df <- dplyr::tribble(
  ~ id, ~ val,
  "1", list(1, 2, 3),
  "2", list(4, 5, 6),
  "3", list(7, 8, 9)
) 

View(df)
```
2. In Data Viewer, filter to id equals 3

**Comment by paulstillman** [comment]
I'm having a similar issue with nested data and using the Viewer to sort my data. Here's a quick reprex:

```r
my_data <- tibble(x = c(1,1,1, 2,2,2), var_1 = c(1,1,1,2,2,2), var_2 = c(3,3,3,4,4,4)) |> 
  nest(data = -x)
View(my_data)
```
If you click on the `data`  in the first and second rows, you'll see it pulls out the correct dataframe (for both x = 1 and x = 2). But if you use the little arrows at the top of the columns to sort the data such that now x = 2 is on top, then click through the `data` of the first row (for x = 2), you'll see that it still gives the `data` for x = 1. 

If you look at the console, it's clear what is happening: 
`> View(my_data[[2]][[1]])` 
Which is the same call as when you click on the data of the first row before sorting.

So what appears to be happening is: In the viewer I've sorted the dataframe, but I haven't sorted the underlying data. When I click on any nested dataframe, it pulls out the dataframe in that position from the original (unsorted) data (as opposed to the dataframe that I actually want). So in other words, if I have a more complicated dataframe and I've done some sorting via the Viewer, then I click on the 5th row's nested dataframe, it will pull out for me the dataframe at the 5th row in the original, unsorted data. 

I hope this is helpful -- I imagine these issues have a similar root (though I'm also happy to make this its own issue). This was the source of an extremely confusing bug for me that took me quite a while to realize what was happening (I thought nest was working incorrectly).

**Comment by ronblum** [comment]
See also issue #15041 in which @raykrajci provides a step-by-step reprex.

**Comment by kevinushey** [comment]
Internal note: the main challenge here is reconciling the difference in how the different types of R data frames are indexed, particularly around row names.

We'll also want to take the time to make sure we properly handle "automatic" / integer row names, versus explicitly-set character row names. We'll probably want to use JSON encoding for the row names, so we can more easily differentiate between numeric and non-numeric row names.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+106 on Windows 11 using examples above and in #15041.
