### ISSUE TITLE
Error going into visual markdown editor

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#9963]
### System details

    RStudio Edition : 
    RStudio Version : 2022.01.0-daily+129.pro1
    OS Version      : ubuntu20
    R Version       : 4.1.1

### Steps to reproduce the problem

1. Create a new R Markdown document.
2. Click to go into visual mode.

### Describe the problem in detail
The user gets attached Error and cannot use the visual editor.
![Screen Shot 2021-10-15 at 10 24 16 AM](https://user-images.githubusercontent.com/1482677/137528754-73a6bb38-01df-4d8c-8c26-cc0c281a7f59.png)

### Describe the behavior you expected
No errors and visual editor to load.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
This is pretty bad.  Surely this is environment-specific?  Or something that recently changed?  This works fine in Ghost Orchid.

**Comment by stepp1** [comment]
A similar error seems to be occurring on the desktop version.

```
RStudio Edition   : <!-- Desktop -->
RStudio Version  : 2022.02.0 Build 443
OS Version         : EndeavourOS 5.16.14-arch1-1
R Version            : 4.1.3
```
## Steps to reproduce the problem

Same steps.

## Describe the problem in detail

Open a .Rmd and go into visual mode, i.e. same behaviour but without the error

![2022-03-18-004426_1920x1080_scrot](https://user-images.githubusercontent.com/40745694/158934209-81c8422d-6ce7-4e9d-b3fe-a6574b6b0d19.png)

RStudio's env seems to be correct: 
```
> Sys.getenv("RSTUDIO_PANDOC")
[1] "/usr/lib/rstudio/bin/quarto/bin"
```
but the folder doesn't exist.  Pandoc seems to be at  `"/usr/lib/rstudio/bin/pandoc"` 

## Describe the behavior you expected

No loading wheel/white screen and load visual mode.
