### ISSUE TITLE
Improve Error Message for GitHub and RStudio Authentication/Credentials 

### ISSUE THREAD

**Issue by angeliamarie4** [rstudio/rstudio#9965]
**System details**

>RStudio Edition : Desktop
RStudio Version : 1.4.1717
OS Version:          Windows 10
R Version       : 4.1

**Describe the problem in detail**
I am new to RStudio and Github, and recently created my first project repository on GitHub for internal and external collaboration amongst my project team. The goal was to clone this new GitHub repo into a Version Controlled project onto my RStudio Desktop and local drive. Once the clone was initiated in RStudio, it created the project folder, but then idled on the processing window for the next hour and a half without cloning the remaining files in the repository (which was just a README.md file at the time). 

With some experienced guidance, we were able to identify that the issue originated from my lack of authentication and/or credential verification from GitHub to communicate with my local RStudio. Once a personal token was generated from GitHub and provided to Git and RStudio, I was able to clone the repository instantly onto my local drive, with all of the git, commit, push and pull functionality. 

**Describe the behavior you expected**
It would be useful, especially for the new users who don't foresee the need to clone projects or remote coding at the onset of their work in R and RStudio, to have an error message output on the clone window identifying the lack of credentials or authentication from GitHub which was causing the clone to fail.

**Comment by ronblum** [comment]
@angeliamarie4 Thank you for raising this! In addition to an informative error message, at the very least—at the risk of stating the obvious—the IDE shouldn't hang for an hour and a half. I'll mark this for review as we continue development of RStudio.
