### ISSUE TITLE
Show active tab title in detached windows' headers on Mac (and PC also probably)

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#9974]
Hello, I hope my terminology is appropriate!

At the moment, when a window is detached from the main RStudio, its header just shows that it is an "RStudio Source Editor" window. The same happens if one checks the list of open windows in the Window bar menu:
![image](https://user-images.githubusercontent.com/777560/137919835-d4582663-e329-42ea-ab1b-ea4e7110a6b9.png)
I'm reporting the issue for Mac Os but I know is present also on Windows and Linux.

This is problematic when multiple detached windows are present (common with multiple displays).

It would be much more useful to show the title of the active tab also in the window header so that one can identify and select the window of interest more easily.

**Comment by ronblum** [comment]
@bakaburg1 Thank you for the suggestion! We'll review it as we continue development of RStudio.
