### ISSUE TITLE
Python interpreters search results in error pop-up in RStudio Desktop

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9975]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0+351 & 2021.12.0+122
    OS Version      : MacOS 12 beta
    R Version       : 3.6.3 & 4.1.1

### Steps to reproduce the problem

1. Close any open projects.
2. <kbd>Tools -> Global Options -> Python</kbd>
3. <kbd>Select</kbd>

### Describe the problem in detail

**Non-MacOS**

This is not on issue in RStudio Desktop on Windows or RStudio Server on Ubuntu 20.04. This is a regression, as it works RStudio Desktop 1.4.1717.

**MacOS 12**

On MacOS 12 beta, when no projects are open, an error message pops up:
> Error finding Python interpreters: R code execution error

The following is written to the console:
> Error in system2(conda, args, stdout = TRUE, stderr = FALSE) : 
  error in running command
<img width="297" alt="interpreter_error" src="https://user-images.githubusercontent.com/31009952/137920863-37976f3e-ce38-45c0-af98-aa5ad6e25a53.png">

If a project is open, the list of interpreters correctly appears for both Global and Project Options.

### Describe the behavior you expected

The list of available interpreters should always appear, without error.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
> @gtritchie is this related to #9952?

@mikebessuille Possibly, looking now.

**Comment by kevinushey** [comment]
Technically there is a tool for updating the ld shared cache, but ...

```
$ update_dyld_shared_cache --help
This tool is deprecated.
```
