### ISSUE TITLE
"dyld: No shared cache present" error dialog when selecting python interpreter

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9978]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0+351 & 2021.12.0+122
    OS Version      : macOS 11.6 (Intel)
    R Version       : 3.6.3 & 4.1.1

This was originally logged as part of #9975, splitting into a distinct issue.

### Steps to reproduce the problem

- Close any open projects.
- Tools -> Global Options -> Python
- Select

### Describe the problem in detail

**Non-MacOS**

This is not on issue in RStudio Desktop on Windows or RStudio Server on Ubuntu 20.04. This is a regression, as it works RStudio Desktop 1.4.1717.

**MacOS 11**

On MacOS 11, the message "Python cannot be opened because of a problem" pops up, but then list of interpreters is correctly made available:

![137921293-5618450b-206a-46b0-b5a3-10d724e7694b](https://user-images.githubusercontent.com/10569626/137970913-6f18f88f-6860-4c68-a426-b9791d50afea.png)

### Describe the behavior you expected

No error message

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Moving this out of Ghost Orchid until we figure out if this is a code problem or a configuration error.

In either case, although ugly, it appears this doesn't block the user from actually bringing up the list of Python environments so not quite as severe as some others we've fixed.

**Comment by kevinushey** [comment]
Do we know how Python 3.7 was installed in this case? I note that installers of Python 3.7 are no longer available on macOS (at least, from https://www.python.org/downloads/macos/).

**Comment by colearendt** [comment]
Shhh stale bot. This may still be an issue. We just don't know yet 😄
