### ISSUE TITLE
Recognize presence of an "ED25519" format SSH key

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9991]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : All up to current daily builds
    OS Version      : Any
    R Version       : Any

Note, this was split out from #8255 (that issue covers adding full support for ed25519, including generating it from the UI). This one just covers making the UI recognize there is an ed25519 key present.

### Steps to reproduce the problem

- Follow github instructions to create and use an SSH key in the preferred ed25519 format (https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
- Verify that it is active and working with github (from a terminal outside RStudio)
- RStudio: Tools / Global Options / Git/SVN

### Describe the problem in detail

The UI says there are no SSH RSA keys:

![Screen Shot of Git Global Options with (None) shown for key](https://user-images.githubusercontent.com/10569626/138366616-fcc89580-b512-4333-9b2a-d7db35869b19.png)

### Describe the behavior you expected

Since RStudio's github support works fine with the ed25519 key, we should show it here, otherwise users who followed github instructions think something is not working.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by AndrewMcClain** [comment]
Confirmed, id_ed25519 is detected, displayed, and used.
