### ISSUE TITLE
IDE does not always prevent deploy of an item when its app type has changed

### ISSUE THREAD

**Issue by joshfrench** [rstudio/rstudio#9997]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 351
    OS Version      : Mac OS 11.6
    R Version       : 4.1.1

### Steps to reproduce the problem
1. Create a new project with an R Markdown doc
2. Push-button publish, selecting "Publish finished document only"
3. Add `runtime: shiny` to R Markdown doc and save
4. Push-button publish again

### Describe the problem in detail
The deploy succeeds and the new version is still marked as `rmd-static` even though the app type has changed.

### Describe the behavior you expected
In other workflows, the deploy is rejected if the app type has changed. The user is given an error explaining that they need to create a new content item if they want to change types.

E.g.: select "Publish document with source code" when first publishing, then change type and re-publish. The update is rejected and an error message is displayed in the Deploy tab.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by astayleraz** [comment]
I was able to reproduce this and saw when I downloaded from the kebab menu > source versions the file showed "appmode": "static" and I was not given any error when uploading that I needed to create a new content item.

**Comment by colearendt** [comment]
Rough edges make life hard for users _stale bot_. You of all... creatures?... should know
